### ISSUE TITLE
Container with drain timeout gets stuck in "stopping" state forever because of rancher-server restarts causing LB websocket connections to be closed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10004]
Rancher versions:v1.6.11-rc1
Steps to Reproduce:
Create a service - S1 with ```drain_timeout_ms``` set .
Create an LB service with service S1 as target.
Restart rancher server.
Upgrade S1.
Service container is stuck in "stopping" state forever.

LB logs shows that websocket connection that was closed  when rancher-server was restarted was never re-established.

```
10/3/2017 2:55:15 PMtime="2017-10-03T21:55:15Z" level=warning msg="websocket closed: websocket: close sent"
```

**Comment by cjellick** [comment]
Can be tested on v1.6-development as time/date of this comment

**Comment by sangeethah** [comment]
Tested with rancher-server  - v1.6-developement

Create a service - S1 with drain_timeout_ms set .
Create an LB service with service S1 as target.
Restart rancher server.
Upgrade S1.
Service S1 gets upgraded without any problem.

LB services constantly retry to subscribe to events when rancher-server is down and is able to subscribe successfully once it is up.
 
```
10/10/2017 11:44:14 AMtime="2017-10-10T18:44:14Z" level=error msg="Error subscribing to events: dial tcp <ip>8:8080: getsockopt: connection refused" subscribeUrl="ws://<ip>/v2-beta/subscribe?eventNames=target.drain&eventNames=ping"
10/10/2017 11:44:14 AMtime="2017-10-10T18:44:14Z" level=error msg="Exiting subscriber: dial tcp <ip>:8080: getsockopt: connection refused"
10/10/2017 11:44:15 AMtime="2017-10-10T18:44:15Z" level=info msg="Initializing event router" workerCount=250
10/10/2017 11:44:16 AMtime="2017-10-10T18:44:16Z" level=info msg="Connection established"
10/10/2017 11:44:16 AMtime="2017-10-10T18:44:16Z" level=info msg="Starting websocket pings"
```
