### ISSUE TITLE
Access Control - AD with TLS:  Error creating ssl connection: LDAP Result Code 200

### ISSUE THREAD

**Issue by pingutux** [rancher/rancher#10008]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.11.9
network-services: 0.9.4
scheduler: 0.8.2

**Docker version: 1.12.6

**Operating system and kernel: CentOS Linux 7 - 3.10.0-693.2.2.el7.x86_64**

**Type/provider of hosts: Virtual via KVM**

**Setup details: HA rancher, external DB**

**Environment Template: Cattle**

**Steps to Reproduce:**
***Setup Infrastructure***
Access Control via Active Directory
Local CA

****2 AD Controllers**** 
ad01.domain.a.b
Cert Details:
  Subject: CN=ad01.domain.a.b
  X509v3 Subject Alternative Name: 
     DNS:ad01.domain.a.b, DNS:domain.a.b, DNS:CORP

openssl s_client -showcerts -connect ad02.domain.a.b:636
...
subject=/CN=ad01.domain.a.b

ad02.domain.a.b
Cert Details:
  Subject: CN=ad02.domain.a.b
  X509v3 Subject Alternative Name: 
     DNS:ad02.domain.a.b, DNS:domain.a.b, DNS:CORP

openssl s_client -showcerts -connect ad02.domain.a.b:636
...
subject=/CN=ad02.domain.a.b

***Setup Rancher***
I upgraded from 1.6.7 to 1.6.10 and I know the about the Active Directory changes with TLS enabled in 1.6.10.
The CA is imported (http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#ldap)

Access Control with Active Directory, I tested the connection with the following Hostnames:
ad01.domain.a.b
ad02.domain.a.b
domain.a.b

**Results:**

Can't authenticate authenticate against AD.

From inside of the RancherServer Container:
root@bfc6d07e4de5:/var/lib/cattle/logs# tail -f cattle-debug.log
...
2017-10-04 09:22:05,208 ERROR [:] [] [] [] [p1020391880-160] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500, message: Error creating ssl connection: LDAP Result Code 200 "": read tcp 172.17.0.3:50828->10.78.102.107:636: read: connection reset by peer 

But when I  check the connection with openssl, I get no error:

root@bfc6d07e4de5:/var/lib/cattle/logs# openssl s_client -showcerts -connect ad01.domain.a.b:636 -CApath /var/lib/rancher/etc/ssl/
CONNECTED(00000003)
depth=1 XXXXXXXXXXXXXXXXXXXXXXXX
verify return:1
depth=0 CN = ad01.domain.a.b
verify return:1
...
    Verify return code: 0 (ok)

root@bfc6d07e4de5:/var/lib/cattle/logs# openssl s_client -showcerts -connect ad02.domain.a.b:636 -CApath /var/lib/rancher/etc/ssl/
CONNECTED(00000003)
depth=1 XXXXXXXXXXXXXXXXXXXXXXXX
verify return:1
depth=0 CN = ad02.domain.a.b
verify return:1
...
    Verify return code: 0 (ok)

root@bfc6d07e4de5:/var/lib/cattle/logs# openssl s_client -showcerts -connect domain.a.b:636 -CApath /var/lib/rancher/etc/ssl/
CONNECTED(00000003)
depth=1 XXXXXXXXXXXXXXXXXXXXXXXX
verify return:1
depth=0 CN = ad02.domain.a.b
verify return:1
...
    Verify return code: 0 (ok)

So, what is wrong with my setup?

THX
Oliver

**Comment by janeczku** [comment]
@pingutux OpenSSL does not verify the certificate names (subject/subject alternative) against the hostname used so your tests would pass even if there was indeed a mismatch.

Please post the output of this command:

```
openssl s_client -connect domain.a.b:636 -CAfile /var/lib/rancher/etc/ssl/ca.crt | openssl x509 -noout -text | grep "DNS\|Subject"
```

**Comment by pingutux** [comment]
@janeczku 
Thank you for you help, please see the output:

`[root@rancher01 ~]# docker exec -ti RancherServer bash
root@1afbecfde9e6:/# openssl s_client -connect domain.a.b:636 -CAfile /var/lib/rancher/etc/ssl/ca.crt | openssl x509 -noout -text | grep "DNS\|Subject\|Signature Algorithm"                                              
depth=1 DC = b, DC = a, DC = domain, CN = DomainCA
verify return:1
depth=0 CN = ad01.domain.a.b
verify return:1
    Signature Algorithm: sha512WithRSAEncryption
        Subject: CN=ad01.domain.a.b
        Subject Public Key Info:
            X509v3 Subject Key Identifier: 
            X509v3 Subject Alternative Name: 
                DNS:ad01.domain.a.b, DNS:domain.a.b, DNS:DOMAIN
    Signature Algorithm: sha512WithRSAEncryption
^C
root@1afbecfde9e6:/# openssl s_client -connect domain.a.b:636 -CAfile /var/lib/rancher/etc/ssl/ca.crt | openssl x509 -noout -text | grep "DNS\|Subject\|Signature Algorithm"
depth=1 DC = b, DC = a, DC = domain, CN = DomainCA
verify return:1
depth=0 CN = ad02.domain.a.b
verify return:1
    Signature Algorithm: sha512WithRSAEncryption
        Subject: CN=ad02.domain.a.b
        Subject Public Key Info:
            X509v3 Subject Key Identifier: 
            X509v3 Subject Alternative Name: 
                DNS:ad02.domain.a.b, DNS:domain.a.b, DNS:DOMAIN
    Signature Algorithm: sha512WithRSAEncryption
`

**Comment by janeczku** [comment]
I think the clue is the use of a SHA512 signature algorithm by your CA. There is a known issue where MS IIS will abort the TLSv1.2 handshake when the server certificate is signed with SHA512 but the client does not advertise a SHA512 based signature algorithm in the TLS client hello. See https://groups.google.com/a/tagpma.org/d/msg/tagpma-general/_NbjhvKJ4qI/WYFK17UWof0J
 
We have recently switched to a Golang microservice for AD authentication. And apparently the Golang TLS client does not advertise any SHA512 based signature algorithms.

A possible workaround would be to force TLSv1.1 on the initial connection. This would have to be implemented as a configuration option. @mrajashree

**Comment by pingutux** [comment]
@janeczku 

Yes, this was the problem! I downgrade to SHA265 and everything works. ;-)

**Comment by janeczku** [comment]
@pingutux Glad to hear that!

**Comment by eici** [comment]
> A possible workaround would be to force TLSv1.1 on the initial connection. This would have to be >implemented as a configuration option. @mrajashree

Hi! Any update on this? I'm facing the same problem but we won't downgrade our certificates!
Is there another solution to solve this?

**Comment by janeczku** [comment]
Fyi, Go 1.10 has this issue fixed: https://github.com/golang/go/commit/96cd66b266a24d8ed1f66dfa10ddb86d88b50fca

**Comment by deniseschannon** [comment]
There is an issue with Go1.10 that doesn't allow us to bump up the GO version. Waiting for Go 1.10.1 that has the fix.

**Comment by deniseschannon** [comment]
After looking at the configuration options, we have decided to go with the route of bumping up golang 1.10, which has some dependency bumps in our SAML provider that will also need to be validated.

**Comment by deniseschannon** [comment]
@galal-hussein with the changes we've made to fix this issue, we've had to update our SAML library dependencies, can we make sure that shibboleth, keycloak and ping are still working properly?

**Comment by deniseschannon** [comment]
@pingutux Would you be willing to test upgrading to v1.6.17-rc2 with a SHA512 certificate to see if that works for you?

**Comment by sangeethah** [comment]
Tested with latest build from master:
Ping Federator Auth works except for some minor issues seen which are tracked as separate issues.

**Comment by deniseschannon** [comment]
Verified with another user that the SHA512 is working in v1.6.17-rc3.

**Comment by manwanth** [comment]
Hi I am getting "Error creating ssl connection: LDAP Result Code 200 "": x509: certificate signed by unknown authority" while implementing AD authentication using TLS. 

Rancher version is v.1.6.18.

Signature Algorithm: sha256WithRSAEncryption

**Comment by janeczku** [comment]
@manwanth you need to provide the CA certificate of the Active Directory server to the rancher/server container: https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#ldap

If that doesn't work please file a new issue. Thanks!

**Comment by manwanth** [comment]
I did same thing, I used CA certificate of the Active Directory server to the rancher/server:v1.6.18 container and certificate got added to keystore successfully.

Adding ca.crt to Certs.
Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
Certificate was added to keystore

**Comment by janeczku** [comment]
@manwanth 
> LDAP Result Code 200 "": x509: certificate signed by unknown authority"

is a different error than the one resolved here:

> LDAP Result Code 200 "": read: connection reset by peer

Please file a new ticket.
