### ISSUE TITLE
2.0 preview - "scale" (only the number) can go beyond "scaleMax" using CLI for scaling 

### ISSUE THREAD

**Issue by golvteppe** [rancher/rancher#10019]
**Rancher versions:**
rancher/server: v2.0.0-alpha9 
rancher/agent: v2.0-alpha4

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.12.3
network-services: network-manager:v0.8.6
scheduler: v1.7.6-netes2-1
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"

Kernel: 3.10.0-514.6.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher 
external DB  - Server version: 5.5.52-MariaDB MariaDB Server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Rancher 2.0

**Steps to Reproduce:**

Rancher CLI Version: v1.0.0-alpha4

Edit service and set min max increment values in UI

``` ./rancher --env <env> scale <service>=<num > maxScale> ```

In my test scenario: ``` ./rancher --env 1a5 scale faas-rancher=40 ```

**Results:**

"scale": 40,
"scaleIncrement": 2,
"scaleMax": 10,
"scaleMin": 1,

Actual number of containers stays @ scaleMax, so only the scale number goes over. Still confusing in UI / when using the scale number in external applications. 

currentScale is also set to "null" and I think this follows the exact count for number of containers in 1.x.x.

Let me know if you need any more info.

**Comment by vincent99** [comment]
These options no longer exist in native kubernetes-land...
