### ISSUE TITLE
kubelet container fails to start due to missing cgroup mount on Amazon Linux

### ISSUE THREAD

**Issue by jc1518** [rancher/rancher#10015]
**Rancher versions:**
rancher/server: v2.0.0-alpha8
rancher/agent: rancher/agent:v2.0-alpha4

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Amazon Linux AMI"
VERSION="2017.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.03"
PRETTY_NAME="Amazon Linux AMI 2017.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Steps to Reproduce:**
After added a new host, kubelets container fails to start on the new host. The error message: error: failed to run Kubelet: invalid configuration: cgroup-root "/" doesn't exist

**Results:**
Error message inside the kubelets container

+ FQDN=ip-172-27-170-153
+ '[' kubelet == kubelet ']'
++ docker info
++ grep -i 'cgroup driver'
++ awk '{print $3}'
+ CGROUPDRIVER=cgroupfs
+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --require-kubeconfig --allow-privileged=true --register-node=true --cloud-provider=auto-detect --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --network-plugin=cni --cni-conf-dir=/etc/cni/managed.d --pod-infra-container-image=rancher/pause-amd64:3.0 --cgroup-driver=cgroupfs --hostname-override ip-172-27-170-153
I1005 03:43:00.948594   30484 feature_gate.go:144] feature gates: map[]
I1005 03:43:00.950104   30484 client.go:72] Connecting to docker on unix:///var/run/docker.sock
I1005 03:43:00.950122   30484 client.go:92] Start docker client with request timeout=2m0s
I1005 03:43:00.960234   30484 manager.go:143] cAdvisor running in container: "/docker/27aec1b949c0a6586d9a5cec8cbaf47dd68eeadd91051c55c26b0601ee5d9c56"
W1005 03:43:00.980775   30484 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
I1005 03:43:01.001060   30484 fs.go:117] Filesystem partitions: map[/dev/xvda1:{mountpoint:/var/lib/docker major:202 minor:1 fsType:ext4 blockSize:0}]
I1005 03:43:01.004034   30484 manager.go:198] Machine: {NumCores:4 CpuFrequency:2800019 MemoryCapacity:7844536320 MachineID: SystemUUID:EC29FD9B-325D-BAC5-59C5-FAFAEB432DD9 BootID:3dc7ab77-1300-46bc-b72d-cebc637404d5 Filesystems:[{Device:/dev/xvda1 DeviceMajor:202 DeviceMinor:1 Capacity:8318783488 Type:vfs Inodes:524288 HasInodes:true} {Device:overlay DeviceMajor:0 DeviceMinor:91 Capacity:8318783488 Type:vfs Inodes:524288 HasInodes:true}] DiskMap:map[202:0:{Name:xvda Major:202 Minor:0 Size:8589934592 Scheduler:noop}] NetworkDevices:[{Name:eth0 MacAddress:06:07:3f:04:5f:2a Speed:0 Mtu:9001}] Topology:[{Id:0 Memory:7844536320 Cores:[{Id:0 Threads:[0 2] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[1 3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:26214400 Type:Unified Level:3}]}] CloudProvider:AWS InstanceType:c3.xlarge InstanceID:i-0ba9e92d23b04cee6}
I1005 03:43:01.004992   30484 manager.go:204] Version: {KernelVersion:4.9.27-14.33.amzn1.x86_64 ContainerOsVersion:Ubuntu 16.04.1 LTS DockerVersion:17.03.2-ce DockerAPIVersion:1.27 CadvisorVersion: CadvisorRevision:}
I1005 03:43:01.005570   30484 server.go:536] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
error: failed to run Kubelet: invalid configuration: cgroup-root "/" doesn't exist: <nil>

**Comment by superseb** [comment]
Most likely due to Amazon Linux having cgroup sysfs on `/cgroup` instead of `/sys/fs/cgroup`, and we do mount `/sys` but not `/cgroup`. To make sure, you can upgrade and change the mount. We can think of a more elegant solution

**Comment by tobiajo** [comment]
I have the same issue with `boot2docker v17.06.2-ce`.

**images**
rancher/agent:v1.2.6
rancher/k8s:v1.7.7-rancher1

This means I can not use the vSphere machine driver.

Logs: https://pastebin.com/raw/FCYbSym9

**Comment by gangefors** [comment]
I encounter the same issue as @tobiajo and I can't figure out how to fix it.

1. Installed Rancher 1.6  on it's own docker host with
`sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:stable`
2. Created 5 docker hosts on a vSphere server using docker-machine and boot2docker v17.06.2-ce.
3. Added the hosts to Rancher as instructed.
4. Created Kubernetes stack from the catalog, kept all default values.
5. All services except kubelet start successfully.

Kubelet image: `rancher/k8s:v1.7.4-rancher2`
Kubelet logs: https://pastebin.com/raw/7WZB46x5

docker info for one of the Rancher hosts:
```
Containers: 14
 Running: 13
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 69
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.86-boot2docker
Operating System: Boot2Docker 17.06.2-ce (TCL 7.2); HEAD : ff16afa - Wed Sep  6 00:17:25 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.908GiB
Name: rancher-node1
ID: TJR3:N2SI:QNDX:44IY:HF3V:BD33:DEKX:GUMR:SW6R:MCXF:7EG6:LOBJ
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 100
 Goroutines: 95
 System Time: 2017-11-14T11:47:34.048582099Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarevsphere
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
Live Restore Enabled: false
```

**Comment by gangefors** [comment]
I can also reproduce it on latest RC of Rancher 1.6. Same setup as above when it comes to the docker hosts.

Versions
```
Rancher | v1.6.11-rc10
Cattle | v0.183.30
User Interface | v1.6.30
Rancher CLI | v0.6.5
Rancher Compose | v0.12.5
```

Kubelet logs
```
11/14/2017 5:33:34 PMumount: /var/lib/docker/plugins: not mounted
11/14/2017 5:33:34 PM+ true
11/14/2017 5:33:34 PM+ for i in '$(DOCKER_API_VERSION=1.22 ./docker info 2>&1  | grep -i '\''docker root dir'\'' | cut -f2 -d:)' /var/lib/docker /run /var/run
11/14/2017 5:33:34 PM++ tac /proc/mounts
11/14/2017 5:33:34 PM++ grep '^/run/'
11/14/2017 5:33:34 PM++ awk '{print $2}'
11/14/2017 5:33:34 PM+ for i in '$(DOCKER_API_VERSION=1.22 ./docker info 2>&1  | grep -i '\''docker root dir'\'' | cut -f2 -d:)' /var/lib/docker /run /var/run
11/14/2017 5:33:34 PM++ tac /proc/mounts
11/14/2017 5:33:34 PM++ grep '^/var/run/'
11/14/2017 5:33:34 PM++ awk '{print $2}'
11/14/2017 5:33:34 PM+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/93acbe235d0e '!=' /var/run/nscd ']'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/93acbe235d0e '!=' /run/nscd ']'
11/14/2017 5:33:34 PM+ umount /var/run/docker/netns/93acbe235d0e
11/14/2017 5:33:34 PM+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/c7fbbc83879f '!=' /var/run/nscd ']'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/c7fbbc83879f '!=' /run/nscd ']'
11/14/2017 5:33:34 PM+ umount /var/run/docker/netns/c7fbbc83879f
11/14/2017 5:33:34 PM+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/41b0efae43c1 '!=' /var/run/nscd ']'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/41b0efae43c1 '!=' /run/nscd ']'
11/14/2017 5:33:34 PM+ umount /var/run/docker/netns/41b0efae43c1
11/14/2017 5:33:34 PM+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/635d2ce33bea '!=' /var/run/nscd ']'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/635d2ce33bea '!=' /run/nscd ']'
11/14/2017 5:33:34 PM+ umount /var/run/docker/netns/635d2ce33bea
11/14/2017 5:33:34 PM+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/b0dd445bdb67 '!=' /var/run/nscd ']'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/b0dd445bdb67 '!=' /run/nscd ']'
11/14/2017 5:33:34 PM+ umount /var/run/docker/netns/b0dd445bdb67
11/14/2017 5:33:34 PM+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/64acfb8b59a7 '!=' /var/run/nscd ']'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/64acfb8b59a7 '!=' /run/nscd ']'
11/14/2017 5:33:34 PM+ umount /var/run/docker/netns/64acfb8b59a7
11/14/2017 5:33:34 PM+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/default '!=' /var/run/nscd ']'
11/14/2017 5:33:34 PM+ '[' /var/run/docker/netns/default '!=' /run/nscd ']'
11/14/2017 5:33:34 PM+ umount /var/run/docker/netns/default
11/14/2017 5:33:34 PM+ mount --rbind /host/dev /dev
11/14/2017 5:33:34 PM+ mount -o rw,remount /sys/fs/cgroup
11/14/2017 5:33:34 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:34 PM+ '[' -d /sys/fs/cgroup/blkio ']'
11/14/2017 5:33:34 PM+ mkdir -p /sys/fs/cgroup/blkio/kubepods
11/14/2017 5:33:34 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:34 PM+ '[' -d /sys/fs/cgroup/cpu ']'
11/14/2017 5:33:34 PM+ mkdir -p /sys/fs/cgroup/cpu/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/cpuacct ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/cpuacct/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/cpuset ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/cpuset/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/devices ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/devices/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/freezer ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/freezer/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/hugetlb ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/hugetlb/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/memory ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/memory/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/net_cls ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/net_cls/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/net_prio ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/net_prio/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/perf_event ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/perf_event/kubepods
11/14/2017 5:33:35 PM+ for i in '/sys/fs/cgroup/*'
11/14/2017 5:33:35 PM+ '[' -d /sys/fs/cgroup/pids ']'
11/14/2017 5:33:35 PM+ mkdir -p /sys/fs/cgroup/pids/kubepods
11/14/2017 5:33:35 PM++ hostname --fqdn
11/14/2017 5:33:35 PM+ FQDN=rancher-node1
11/14/2017 5:33:35 PM+ '[' kubelet == kubelet ']'
11/14/2017 5:33:35 PM++ docker info
11/14/2017 5:33:35 PM++ awk '{print $3}'
11/14/2017 5:33:35 PM++ grep -i 'cgroup driver'
11/14/2017 5:33:35 PM+ CGROUPDRIVER=cgroupfs
11/14/2017 5:33:35 PM+ '[' rancher == azure ']'
11/14/2017 5:33:35 PM+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --allow-privileged=true --register-node=true --cloud-provider=rancher --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --fail-swap-on=false --cluster-domain=cluster.local --network-plugin=cni --cni-conf-dir=/etc/cni/managed.d --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --cgroup-driver=cgroupfs --hostname-override rancher-node1
11/14/2017 5:33:35 PMI1114 16:33:35.181622   25583 feature_gate.go:156] feature gates: map[]
11/14/2017 5:33:35 PMI1114 16:33:35.181681   25583 controller.go:114] kubelet config controller: starting controller
11/14/2017 5:33:35 PMI1114 16:33:35.181684   25583 controller.go:118] kubelet config controller: validating combination of defaults and flags
11/14/2017 5:33:35 PMI1114 16:33:35.183375   25583 client.go:75] Connecting to docker on unix:///var/run/docker.sock
11/14/2017 5:33:35 PMI1114 16:33:35.183418   25583 client.go:95] Start docker client with request timeout=2m0s
11/14/2017 5:33:35 PMI1114 16:33:35.186902   25583 feature_gate.go:156] feature gates: map[]
11/14/2017 5:33:35 PMI1114 16:33:35.232029   25583 manager.go:149] cAdvisor running in container: "/sys/fs/cgroup/cpu"
11/14/2017 5:33:35 PMW1114 16:33:35.244006   25583 manager.go:157] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
11/14/2017 5:33:35 PMW1114 16:33:35.244087   25583 manager.go:166] unable to connect to CRI-O api service: Get http://%2Fvar%2Frun%2Fcrio.sock/info: dial unix /var/run/crio.sock: connect: no such file or directory
11/14/2017 5:33:35 PMI1114 16:33:35.255371   25583 fs.go:139] Filesystem UUIDs: map[0a41439f-7030-453f-a17c-1fc0642d0d6f:/dev/zram0 2017-09-06-00-20-02-00:/dev/sr0 6f9ada6f-063e-455d-bdfb-1d0de57428ad:/dev/sda1 cad93338-9bc3-4c4e-89c0-3d6a96bb3854:/dev/sda2]
11/14/2017 5:33:35 PMI1114 16:33:35.255392   25583 fs.go:140] Filesystem partitions: map[tmpfs:{mountpoint:/dev major:0 minor:116 fsType:tmpfs blockSize:0} cgroup:{mountpoint:/sys/fs/cgroup major:0 minor:19 fsType:tmpfs blockSize:0} /dev/sda1:{mountpoint:/etc/resolv.conf major:8 minor:1 fsType:ext4 blockSize:0} shm:{mountpoint:/var/lib/docker/containers/834a29dd99ed5714cb64c7bdd0a6904eecbde6a74e554d36225302d9de78317a/shm major:0 minor:42 fsType:tmpfs blockSize:0} none:{mountpoint:/ major:0 minor:114 fsType:aufs blockSize:0}]
11/14/2017 5:33:35 PMI1114 16:33:35.256654   25583 manager.go:216] Machine: {NumCores:2 CpuFrequency:2596992 MemoryCapacity:2049028096 HugePages:[{PageSize:2048 NumPages:0}] MachineID: SystemUUID:420B3886-4977-DCE5-7635-1D5A1C2B73AA BootID:6b6a426a-8d6b-4d90-973a-1fc50fe08b69 Filesystems:[{Device:cgroup DeviceMajor:0 DeviceMinor:19 Capacity:1024512000 Type:vfs Inodes:250125 HasInodes:true} {Device:/dev/sda1 DeviceMajor:8 DeviceMinor:1 Capacity:19210215424 Type:vfs Inodes:2438832 HasInodes:true} {Device:shm DeviceMajor:0 DeviceMinor:42 Capacity:19210215424 Type:vfs Inodes:2438832 HasInodes:true} {Device:none DeviceMajor:0 DeviceMinor:114 Capacity:19210215424 Type:vfs Inodes:2438832 HasInodes:true} {Device:tmpfs DeviceMajor:0 DeviceMinor:116 Capacity:1844125696 Type:vfs Inodes:250125 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:20971520000 Scheduler:deadline} 251:0:{Name:zram0 Major:251 Minor:0 Size:453636096 Scheduler:none}] NetworkDevices:[{Name:dummy0 MacAddress:6a:4b:23:0d:0b:5e Speed:0 Mtu:1500} {Name:eth0 MacAddress:00:50:56:8b:70:ee Speed:10000 Mtu:1500}] Topology:[{Id:0 Memory:0 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:41943040 Type:Unified Level:3}]} {Id:2 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:41943040 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
11/14/2017 5:33:35 PMI1114 16:33:35.257396   25583 manager.go:222] Version: {KernelVersion:4.4.86-boot2docker ContainerOsVersion:Ubuntu 16.04.1 LTS DockerVersion:17.06.2-ce DockerAPIVersion:1.30 CadvisorVersion: CadvisorRevision:}
11/14/2017 5:33:35 PMI1114 16:33:35.257767   25583 server.go:422] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
11/14/2017 5:33:35 PMerror: failed to run Kubelet: invalid configuration: cgroup-root "/" doesn't exist: <nil>
```

**Comment by krishofmans** [comment]
We're also running into this issue, preventing us to spin up kubernetes using rancher and boot2dockers on vmware.

Has anyone found a potential workaround?

**Comment by superseb** [comment]
On Amazon Linux I successfully tested Amazon Linux 2017.09 and Docker 17.06 (default `yum install`) by changing the mount from `/sys:/sys:ro` to `/cgroup:/sys/fs/cgroup:ro`. Let me know what versions are being used if this doesn't work.

For boot2docker, please try mounting the cgroup directory by changing `/sys:/sys:ro` to `/sys/fs/cgroup:/sys/fs/cgroup:ro`

**Comment by raihan2006i** [comment]
@krishofmans I followed superseb's last comment related to **boot2docker** and it fixed both **kubelet** and **kubelet-unschedulable** services.

FYI I tested locally in my laptop with: 
**docker-machine: v0.13.0**
**boot2docker: v1.13.1**
**Rancher: v1.6.13**
**Kubernetes: v1.8.5**
**Etcd: v2.3.7**

**Comment by jorgermp** [comment]
@raihan2006i how i can change the cgroup mount directory in boot2docker? I'm trying to do the same with rancher and I don't know how do it.

Thanks.

**Comment by raihan2006i** [comment]
@jorgermp Go to your Kubernetes environment Dashboard. Then go to KUBERNETES > Infrastructure Stacks > kubernetes and then click on Upgrade of **kubelet** service as shown in following screenshot:

![screenshot--2018-01-25-17-58-19-032](https://user-images.githubusercontent.com/1857356/35401329-7a5738ac-01f9-11e8-8fba-6ba37e0af63e.png)

And then go to Volumes tab and find **/sys:/sys:ro,rprivate** and change it to **/sys/fs/cgroup:/sys/fs/cgroup:ro,rprivate** and then click Upgrade button as shown in following screenshot:

![screenshot-89 31 77 139-8080-2018-01-12-11-42-35-821](https://user-images.githubusercontent.com/1857356/35401397-a99d8404-01f9-11e8-9526-7cddaffa014a.png)

After clicking Upgrade you might see Finish Upgrade option. Please click that to confirm Upgrade. Do same for **kubelet-unschedulable** service if you have that under kubernetes stack.

**Comment by jorgermp** [comment]
@raihan2006i thanks!!! now works fine 🎉

**Comment by deniseschannon** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!

**Comment by avoidik** [comment]
regardless of rancher v2 this still an issue for v1.6, may I know which versions of docker, docker-machine and boot2docker required to overcome workarounds and install k8s without any issues?

**Comment by garzj** [comment]
I had the same problem, it wasn't a problem with my volume mappings. I figured I had to downgrade to cgroup v1 by adding `systemd.unified_cgroup_hierarchy=0` to `GRUB_CMDLINE_LINUX`  in `/etc/default/grub`.
After a `update-grub2 && reboot` everything worked fine.

**Comment by lbcd** [comment]
@garzj work for me! Many thx.
