### ISSUE TITLE
[RFE] expose port/path on rancher agent to check its health

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10016]
Enhancement request to allow for the ability to monitor rancher agent health/liveness. The use case being: having an agent in an autoscaling group, where if the agent stops responding, we want the host to be recycled.

**Comment by fmunteanu** [comment]
I think this is an important feature. We need a way to monitor if the rancher/agent:latest container is up and running. If is not, we spin a new EC2 custom instance and destroy the old one.

**Comment by onlydole** [comment]
I’ve seen instances where the Docker daemon dies too and prevents containers from properly being scheduled on a host. Having this in place to signal a new machine is needed would greatly help!

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
