### ISSUE TITLE
Stop all for Stacks does not stop containers

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10014]
**Rancher versions:**
rancher/server: 2.0 master 8/4

**Steps to Reproduce:**
1.  Create a Stack with a container & a service
2. From the stack menu click on Stop All

**Results:**  The container stops, then restarts.  It should act like the stop menu does for containers and completely stop the container.

**Comment by ibuildthecloud** [comment]
@alena1108 The stop needs to be done setting the source as user
