### ISSUE TITLE
Start/Stop All menu item for stacks don't exist if I only have stand-alone containers

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10018]
**Rancher versions:** 2.0 master 8/5

**Steps to Reproduce:**
1.  Create a stack that only has stand-alone containers in it
2.  Click on Stack's menu to try to start/stop all

**Results:**  Menu items don't exist.  Have to have at least 1 service for those to show up.

**Comment by vincent99** [comment]
can{Start,Stop}All needs to look for containers in addition to services...
