### ISSUE TITLE
Not able to  create services with retainIp enabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10024]
Rancher versions: v2.0.0-alpha9

Steps to reproduce the problem:

Create a service from UI by enabling "Retain IP" option.
Once the service is created , this option is not set for the service.
In 1.x , we used to have ```retainIp``` field in service which I dont see anymore.

Also setting ```retain_ip: true``` in docker-compose.yml when creating stack also does not result in this option being enabled in service.

**Comment by deniseschannon** [comment]
We do not plan on supporting retainIP for services/workloads in Rancher v2.0.

**Comment by m4ce** [comment]
@deniseschannon - sorry to comment over a closed issue. Is there a reason why it will no longer be supported?

**Comment by vincent99** [comment]
2.0 is now based entirely on Kubernetes and they do not have an option like this.  The closest equivalent is stateful sets, which have different DNS and upgrade behaviors vs a deployment.

**Comment by m4ce** [comment]
@vincent99, thanks for the feedback. It's a shame that retainIp goes away. Certain deployments scenarios like MySQL group replication do-not-work-well/break without it :/

**Comment by vincent99** [comment]
Maybe there's some DNS caching issue but I would think StatefulSet would work, each pod gets a fixed `mysql-1`, `mysql-2`, etc name resolvable inside the cluster.

**Comment by m4ce** [comment]
@vincent99 , it's not related to DNS caching. Another example. If you want to build a Redis cluster, you can only do that using IPs, hostnames are not even supported :/ However, if the containers change IPs, the cluster will be in a broken state.
