### ISSUE TITLE
Agent logs v1 endpoint in CATTLE_URL while it actually checks v3

### ISSUE THREAD

**Issue by bhinkle-work** [rancher/rancher#10025]
**Rancher versions:**
rancher/server: 2.0.0-alpha9
rancher/agent: 2.0.0-alpha4

**Infrastructure Stack versions:**
healthcheck: N/A (new environment)
ipsec: N/A (new environment)
network-services: N/A (new environment)
scheduler: N/A (new environment)
kubernetes (if applicable): N/A (new environment)

**Docker version: (`docker version`,`docker info` preferred)**
17.09.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS (Xenial Xerus)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware Workstation 11.0

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single-node Rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes, built-in distro from 2.0

**Steps to Reproduce:**
1) Create a new Rancher server running 2.0-alpha9
2) From a cluster (either the default one, or a newly created one), choose Add Host and select the Custom host type
3) Run the resulting command (which shows /v3 in the URL being targeted) on a separate Linux server running Docker.

**Results:**
After pulling the agent image, you will see the following logs (substitute IP or FQDN for URL_OF_RANCHER_SERVER):

INFO: Running Agent Registration Process, CATTLE_URL=http://URL_OF_RANCHER_SERVER:8080/v1
INFO: Attempting to connect to: http://URL_OF_RANCHER_SERVER:8080/v1
ERROR: http://URL_OF_RANCHER_SERVER:8080/v1/ is not accessible (The requested URL returned error: 404 Not Found)

The last error message repeats until you Ctrl-C to exit.

The expected result would be for the CATTLE_URL value to have /v3 in the path instead of /v1. The command to run the agent references /v3 and the /v3 URL loads in a browser. /v1 returns a 404.

**Comment by superseb** [comment]
This looks only like an output error, see this function: https://github.com/rancher/rancher/blob/master/agent/run.sh#L67 and the use: https://github.com/rancher/rancher/blob/master/agent/run.sh#L330 and https://github.com/rancher/rancher/blob/master/agent/run.sh#L331

But the actual check goes to the correct URL: https://github.com/rancher/rancher/blob/master/agent/run.sh#L334

Just tested by adding a node and that works fine here, can you double check that the URL is valid and it is reachable?

**Comment by bhinkle-work** [comment]
I confirm that @superseb is correct, when I ran with the debug option it showed the /v3 URL was being checked. This turned out to be a typo in the container registration URL - and his pull request should hopefully make the error messages more useful in the future!

**Comment by superseb** [comment]
Will revisit this when the custom host function is added to Tech Preview 2.
