### ISSUE TITLE
[ipsec] Add regions support

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#10037]
https://github.com/rancher/rancher/issues/9839

**Comment by leodotcloud** [comment]
Fixed in `rancher/net:v0.13.8`

**Comment by sangeethah** [comment]
Regions support is available in v1.6.15-rc1 with rancher/metadata:v0.10.1,rancher/network-manager:v0.7.19,rancher/net:v0.13.9 and rancher/network-policy-manager:v0.2.5

Bugs found when testing regions feature are tracked as different bugs - 
https://github.com/rancher/rancher/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fregion
