### ISSUE TITLE
kubectl download config adding using https

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#10036]
I'm setting up Rancher in a dev environment.  I added the Rancher master as a node on the cluster, created a Kubernetes environment where the Kubernetes services all run on the Rancher master as well (there's cpu/memory to spare).

The in-browser `kubectl` client works great, but when I download the config and try to run it locally I get a connection refused.

Turns out what's happening is that deploying my Rancher as `http` and but the config is providing an `https` URL.  Adjusting the downloaded config to `http` resolved the issue.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Comment by superseb** [comment]
Sounds similar to https://github.com/rancher/rancher/issues/7937, how are you exposing `rancher/server` to the outside, i.e. what URL do you visit when you generate the `kubectl` config?

**Comment by superseb** [comment]
Explanation is mostly in https://github.com/rancher/rancher/issues/7937, let me know if this is not the case for you.
