### ISSUE TITLE
Non latin characters not supported in usernames

### ISSUE THREAD

**Issue by MartinLeedotOrg** [rancher/rancher#10032]
**Rancher versions:**
rancher/server: 1.6.10

**Infrastructure Stack versions:**

**Steps to Reproduce:**
Attempt to register a user using SSO (github in this case) for a user who has non latin characters in their name.

**Results:**
```
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Incorrect string value: '\xC5\x81ukas...' for column 'name' at row 1
Query is: insert into `account` (`name`, `kind`, `uuid`, `state`, `created`, `data`, `external_id`, `external_id_type`, `health_state`, `version`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters ['Łukasz Smith','user','bc3b10ca-1179-4b86-9bfe-c49e94f184b5','requested','2017-10-06 11:31:12.473','{}','3295190','github_user','healthy','2']
```

To clarify, Ł is a pretty common character in some European countries:
https://en.wikipedia.org/wiki/Ł

**Comment by superseb** [comment]
Is this using internal or external DB? Can you run

```
USE cattle;
SELECT @@character_set_database, @@collation_database;
```

**Comment by MartinLeedotOrg** [comment]
This is using an external DB in RDS - MySQL 5.7.17

latin1	latin1_swedish_ci

latin1 appears to be the RDS default :(

**Comment by superseb** [comment]
Including link to the docs on this for completeness:

http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#launching-rancher-server---single-container---external-database
