### ISSUE TITLE
HealthCheck\Scheduler stuck `initializing`

### ISSUE THREAD

**Issue by aequasi** [rancher/rancher#10046]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: holder
network-services: rancher/network-manager:v0.7.7
scheduler: 0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OVH Bare Metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Rancher Server, 3 Agents (one on server). Scheduler on server. Healthchecks not on server are having issues

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
unknown

**Results:**
Health Check's and Scheduler stuck initializing.

Port 42 is open on all hosts
Port 80 open on server. http request to /healthchec is successful
Telnets to 42 on hosts are successful

**Comment by aequasi** [comment]
Ended up resolving itself. Methinks a DNS issue.

**Comment by mzygmunt** [comment]
@aequasi I've exactly the same issue. What kind of DNS issue that occured in your environment?

**Comment by superseb** [comment]
The overlay network is created using the IP's shown in Infrastructure -> Hosts screen, are those all correct? When running `rancher/agent` on the same server as `rancher/server`, you will need to specify `CATTLE_AGENT_IP` to make sure the IP is correct.
