### ISSUE TITLE
register a host on the same machine as the rancher server

### ISSUE THREAD

**Issue by lucevers** [rancher/rancher#10048]
Example below used the ip address of the server! (not 127.0.0.1)

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4a62646810>: Failed to establish a new connection: [Errno 111] Connection refused',))

Got the same result if I use another server as hos (add a host)t.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha9` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`authenticated.clusters.cluster.host-new`|

**Comment by superseb** [comment]
If you are also getting it from another machine, are you sure the IP address you have in your Host Registration URL is reachable on port 8080 from that other machine? Are you exposing port 8080 in the `docker run` command of the `rancher/server` ?

**Comment by lucevers** [comment]
Running Rancher server:

bcf7e18a25e5        rancher/server:preview   "/usr/bin/entry /usr/"   2 days ago          Up 43 minutes       3306/tcp, 0.0.0.0:8080->8080/tcp   admiring_gates


Command in the worker
 sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v2.0-alpha4 http://192.168.1.28:8080/v3/scripts/5C790AFEBDEAE745D721:1483142400000:5KaBWrKcVThNfflSu03M7GqiAQ

INFO: Running Agent Registration Process, CATTLE_URL=http://192.168.1.28:8080/v1
INFO: Attempting to connect to: http://192.168.1.28:8080/v1
ERROR: http://192.168.1.28:8080/v1 is not accessible (Failed to connect to 192.168.1.28 port 8080: No route to host)
ERROR: http://192.168.1.28:8080/v1 is not accessible (Failed to connect to 192.168.1.28 port 8080: No route to host)
ERROR: http://192.168.1.28:8080/v1 is not accessible (Failed to connect to 192.168.1.28 port 8080: No route to host)

**Comment by superseb** [comment]
No route to host usually means exactly that, the node doesn't know to get to `192.168.1.28`. This could either be a firewall or network configuration, are you running VirtualBox and what networks are attached to this VM and the VM running `rancher/server`?

**Comment by KaelBaldwin** [comment]
I'm having this same issue, nothing fancy going on network wise, I'm just using a vultr vm with a rancher preview server running on it trying to create a host on that same server. I tried to register a host on a different server and it worked perfectly.

I've done pretty much the same process with v1.0 and it works there.

I'm going to try some different things on the container and see what I can find out.

**Comment by superseb** [comment]
What image are you using at Vultr, and are you including Private network and IPv6 when you launch it?

**Comment by KaelBaldwin** [comment]
Ubuntu 16.04, no private network or ipv6

**Comment by KaelBaldwin** [comment]
actually i spoke to soon, ipv6 is enabled.

**Comment by superseb** [comment]
I'm going to need some output/logging after you run the `docker run rancher/agent` command on the host to say something useful about this.

**Comment by KaelBaldwin** [comment]
Yes, I now think my issue is on that server in general. I'll figure it out from here. Definitely having connectivity issues in a fresh ubuntu container I started up. Must have knocked something out of wack when I was setting up docker for the rancher preview. Thank you.

**Comment by lucevers** [comment]
Answer question:

No route to host usually means exactly that, the node doesn't know to get to 192.168.1.28. This could either be a firewall or network configuration, are you running VirtualBox and what networks are attached to this VM and the VM running rancher/server?

All firewalls on the machines were stopped.
I'm using 2 Linux box's, a portable (wlan) and a fix pc server.
Both on the same locql lqn.

**Comment by Angelinsky7** [comment]
Got the same issue with 

```
Component | Version
-- | --
Rancher | v1.6.14
Cattle | v0.183.37
User Interface | v1.6.37
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5
```

installed on 
`CentOS Linux release 7.4.1708 (Core)`

with a fresh install of everything...

The machine is accessible : 
```
[root@swarm ~]# curl http://10.138.222.36:8080/v1/scripts/0C00E26DE1531614B156:1514678400000:U5QZ2Ay0EdpZCiphreIZkS27o
#!/bin/sh

export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"
export CATTLE_REGISTRATION_SECRET_KEY="0C00E26DE1531614B156:1514678400000:U5QZ2Ay0EdpZCiphreIZkS27o"
export CATTLE_URL="http://10.138.222.36:8080/v1"
export DETECTED_CATTLE_AGENT_IP="10.138.222.36"
```

And from my "client window 10 machine" with docker installed :
```
docker run -e CATTLE_AGENT_IP="10.138.222.36"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 http://10.138.222.36:8080/v1/scripts/B4D6A7322BD6CA299386:1514678400000:gm7GVu1TIDmsmaTWlx34GhiFWLk
Unable to find image 'rancher/agent:v1.2.9' locally
v1.2.9: Pulling from rancher/agent
b3e1c725a85f: Pull complete
6a710864a9fc: Pull complete
d0ac3b234321: Pull complete
87f567b5cf58: Pull complete
063e24b217c4: Pull complete
d0a3f58caef0: Pull complete
16914729cfd3: Pull complete
dc5c21984c5b: Pull complete
d7e8f9784b20: Pull complete
Digest: sha256:c21255ac4d94ffbc7b523f870f2aea5189b68fa3d642800adb4774aab4748e66
Status: Downloaded newer image for rancher/agent:v1.2.9

INFO: Running Agent Registration Process, CATTLE_URL=http://10.138.222.36:8080/v1
INFO: Attempting to connect to: http://10.138.222.36:8080/v1
INFO: http://10.138.222.36:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=79588191ACBFCFB210E8
INFO: ENV: CATTLE_AGENT_IP=10.138.222.36
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=http://10.138.222.36:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=10.138.222.53
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.9
INFO: Launched Rancher Agent: 9af597e323d905e2125c2e4ec32b61e019e7a6160c703bf9d12ee07a000d3037
```

Can you help me understand what i'am doing wrong ?
Thanks

**Comment by Angelinsky7** [comment]
I solved this issue my putting the docker0 bridge in the trusted zone....
thanks to https://github.com/docker/docker/issues/16137#issuecomment-271615192
sorry for the noise

**Comment by superseb** [comment]
With the release of Tech Preview 2, the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha16 is most likely invalid.

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM) to learn more about the changes in 2.0 in Tech Preview 2.

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha16+). As always, thanks for using Rancher!

**Comment by evaldobarbosa** [comment]
sudo docker run --net mynet --ip 172.99.0.55 --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.10 http://172.99.0.49:8080/v1/scripts/abc123:zya999
