### ISSUE TITLE
[UI] Links of navigation items Stacks and Catalog are not consistent

### ISSUE THREAD

**Issue by dimw** [rancher/rancher#10055]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.6.10

**Steps to Reproduce:**
1. Open Rancher UI.
2. Click on _Stacks_ in navbar.
3. Click on _Catalog_ in navbar.

**Results:**
It is observed that click on _Catalog_ opens the overview of _All_ catalogs but click on _Stacks_ opens a (filtered) view over the _User_'s stack. This behavior is not consistent. The main navigation elements should both open either the overview over _All_ entities or the default filtered view. Otherwise the issue may lead to user errors (e.g. #9942).

**Comment by vincent99** [comment]
The main link opens the set that is most commonly used, which is User stacks and All catalogs.

**Comment by vincent99** [comment]
l
