### ISSUE TITLE
Rancher 2 Preview - Links are not being created

### ISSUE THREAD

**Issue by jslay88** [rancher/rancher#10051]
**Rancher versions:**
rancher/server: v2.0.0-alpha9
rancher/agent: v2.0-alpha4

**Docker version:**
17.09.0-ce

**Steps to Reproduce:**
Fresh Ubuntu 16.04.3 installs on both Rancher Server and Rancher Host.
Fresh Rancher Server (Tag: Preview) install.
Fresh Host added.

Create MariaDB container in SQL stack
Create PHPMyAdmin container in SQL stack
When creating PHPMyAdmin container, add link to MariaDB, as db.

**Results:**
No link created.

API shows `null`

**Comment by deniseschannon** [comment]
As of the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!
