### ISSUE TITLE
Compose keys that do not work in 2.0

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10059]
**Rancher versions:**
rancher/server:v2.0.0-alpha8

The following keys are currently not functional in 2.0

1. "entrypoint" in docker is "command" in kubernetes
2. container_name won't work
3. labels will only exist as metadata in cattle and won't be propagated to kubernetes
4. stop_signal doesn't work https://github.com/kubernetes/kubernetes/issues/30051
5. stop_grace_timout won't work
6. dns and dns_search don't work
7. no keys regarding logging work
8. network_mode will only work with value "host" (no net: "none", no net: "container:xxx")
9. ulimits isn't currently supported in kubernetes https://github.com/kubernetes/kubernetes/issues/3595
10. init and init path won't work
11. io.rancher.container.requested_ip
12. io.rancher.container.hostname_override
13. log_driver
14. Keys related to Volumes

**Comment by soumyalj** [comment]
In docker inspect, cpu_shares  always shows up as 2  irrespective of the value provided.
Ex: cpu_shares: 1024
Docker inspect: 
```
            "Isolation": "",
            "CpuShares": 2,
            "Memory": 0,
```

**Comment by tomtom54** [comment]
Hello,

I've found another issue in 2.0. 
When I do an upgrade on an app, it's seems to just restart the container. 
For me it should pull the image and run a new container as we see it on the v1.6 or maybe it is wanted ? 

Thanks,

**Comment by superseb** [comment]
@tomtom54 Please search through the issues or create a new one for this, this issue is for compose keys.

**Comment by tomtom54** [comment]
@superseb you've right sorry for this. 
I was staying on the idea that it was for old feature that does not works. 
Opening new one.

**Comment by deniseschannon** [comment]
As of the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!
