### ISSUE TITLE
Add request timeout back to ui fetch

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#10058]
Add support for abortable fetch (https://developers.google.com/web/updates/2017/09/abortable-fetch) in ember-api-store so that the `timeout` option in `rawRequest()` (`addon/services/store.js`) is actualy used again.

**Comment by loganhz** [comment]
@vincent99 Do we need an AbortController polyfill?

**Comment by vincent99** [comment]
No, if you could polyfill it in a meaningful way (actually killing the request) then there wouldn't be a need for abort controller in the first place... Just make sure it doesn't explode if it doesn't exist, but I think all the evergreen browsers have it already.

**Comment by loganhz** [comment]
it looks like the`fetch` we are using from `ember-network` doesn't support the abort feature. (as `ember-network` is using `whatwg-fetch` )
