### ISSUE TITLE
The docker 17.03.0-ce does not support Rancher 2.0 Preview？

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/rancher#10064]
**Rancher versions:**
rancher/server:v2.0 Preview
rancher/agent: default 

**Infrastructure Stack versions:**
healthcheck: default
ipsec: default
network-services: default
scheduler: default
kubernetes (if applicable):
default
**Docker version: (`docker version`,`docker info` preferred)**
17.03.0-ce, build 60ccb22
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos7  3.10
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware 
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Hi,all:
    I have two host and installed CentOS OS, According to Quick Start Guide(https://github.com/rancher/rancher.github.io/blob/master/rancher/v2.0/en/quick-start-guide/index.md),  
I  have Run this Docker command on my host:
sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview

And add a Custom Host:
sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v2.0-alpha4
http://192.168.100.100:8080/v3/scripts/D5433C26EC51325F9D98:1483142400000:KvILQKwz1N2MpOkOiIvGYKKGdE

**Results:**
![1](https://user-images.githubusercontent.com/20707603/31403343-6ca8c60c-ae2b-11e7-97e0-dcb214a4556d.png)
![2](https://user-images.githubusercontent.com/20707603/31403355-72c2a472-ae2b-11e7-8092-f99b0b4e0754.png)

**Comment by superseb** [comment]
It works on Docker 17.03.0, I just tested CentOS 7.3 and 7.4. The problem seems to be in the 4 lines saying `WARNING: NO xx support`. How is the image built that you are using?

Can you supply:

`cat /etc/os-release`
`cat /proc/cmdline`
`rpm -qi kernel`

Closing this as not-a-bug, but we can figure out why Docker is misbehaving.

**Comment by hongxiaolu** [comment]
Thanks!  Recently, testing on Ubuntu or centos, using rancher1.x to deploy k8s, k8s1.6.6 and k8s1.7.7 have similar problems on docker 1.12.6 and 1.13.1 .As long as the kubernete-agent service is running, cgroup functions will be problematic. However, docker depends on cgroup, so the final container will not work properly. After this problem, even restarting the host won't solve the problem

**Comment by hongxiaolu** [comment]
+k8s1.7.2
