### ISSUE TITLE
Alibaba Cloud DNS doesnt validate ttl info on initial start

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10063]
**Rancher versions:**
rancher/server: 1.6.10
rancher/external-dns: v0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
 17.06.2-ce

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Aaliyun
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Alibaba Cloud DNS invalid input in TTL information (Ex: 60), the container will have the error log. 
Ideally, it could validate the Settings and either improve log or show the service as unhealthy.

The error log:

level=error msg="Failed to add DNS record to provider {nginx-service1 nginx-stack2 {nginx-service1.nginx-stack2.default2.cnrancher.cn. [47.95.223.64] A 60}}: Alibaba Cloud API call has failed: Aliyun API Error: RequestId: EC8E09C6-3A49-4403-B4EE-52F3F3161A92 Status Code: 400 Code: QuotaExceeded.TTL Message: The TTL value is less than the minimum value allowed.”

**Comment by loganhz** [comment]
The thing is that dns will just call query on initial start. If we want to fix it, we need to add a dns entry during start.  I don't think we need to do it.

**Comment by yasker** [comment]
Though we need to check if there is a way to show the service as unhealthy in this scenario.

Need to discuss with Craig and Alena to finalize the design.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
