### ISSUE TITLE
Upgrading LB service by upgrading image after rancher-server upgrade results in LB service stuck in "ugrading" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10061]
Set up - rancher-server - v1.6.10
Have Lb services deployed .
Upgrade rancher-server to v1.6.11-rc2
After upgrade , upgrade LB service to latest Lb image.

LB service is stuck in upgrading state forever. Lb container fails to start with following error:

```
10/9/2017 8:17:54 PMtime="2017-10-10T03:17:54Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
10/9/2017 8:17:54 PMtime="2017-10-10T03:17:54Z" level=info msg="Starting Rancher LB service"
10/9/2017 8:17:54 PMtime="2017-10-10T03:17:54Z" level=fatal msg="CATTLE_ENVIRONMENT_ADMIN_ACCESS_KEY is not set, fail to init of Rancher LB provider"
10/9/2017 8:18:10 PMtime="2017-10-10T03:18:10Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
10/9/2017 8:18:10 PMtime="2017-10-10T03:18:10Z" level=info msg="Starting Rancher LB service"
10/9/2017 8:18:10 PMtime="2017-10-10T03:18:10Z" level=fatal msg="CATTLE_ENVIRONMENT_ADMIN_ACCESS_KEY is not set, fail to init of Rancher LB provider"
```
agent is missing from io.rancher.container.agent.role and it is set as follows:

``` io.rancher.container.agent.role: environmentAdmin```

**Comment by sangeethah** [comment]
Set up - rancher-server - v1.6.10
Have Lb services deployed .
Upgrade rancher-server to v1.6.11-rc2
After upgrade , upgrade LB service to latest Lb image.

LB upgrade succeeds.

**Comment by bascht** [comment]
Just to be sure – as I ran into this issue yesterday. The currently published `v0.7.12` of `rancher/lb-service-haproxy` won't work until the fix is done upstream in the next Rancher release?

**Comment by sangeethah** [comment]
Set up - rancher-server - v1.6.10
Have Lb services deployed .
Upgrade rancher-server to v1.6.11-rc3 (with rancher/lb-service-haproxy:v0.7.13)
After upgrade , upgrade LB service to latest Lb image.

LB upgrade succeeds.

**Comment by bascht** [comment]
Mhhhh, alright. Thanks for testing – I might wait for `v1.6.11` to be released, then. ;)

**Comment by kucerarichard** [comment]
if you are here because of the access key "fail" message, in my case it was simply an ergonomic issue (laziness) was due to migrating a stack to test using the docker-compose.yml but NOT the rancher-compose.yml.     You need both.   Copy/paste both,  then load balancer comes up.
