### ISSUE TITLE
When host labels are removed/edited,existing containers that were deployed with host affinity label continues to be running on these hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1006]
Server Version - build from master 06/01

Steps to reproduce the problem:

1.Have a host -h1 with label set to  "foo=bar"
2.Activate a service which has host affinity label set to "foo=bar" and global set to true -
("io.rancher.scheduler.global" = "true" and "io.rancher.scheduler.affinity:host_label" ="foo=bar"
3.Instance gets created in host1
4.Remove the label "foo=bar" from this host

Instances created on host1 continue to be in "running" state on host1.

Should we expect , the instances to be removed since the host does not have the label that is needed for the service any more ?

Or should there be a confirmation presented to the user , before making a decision on whether these containers need to be removed or not ?

**Comment by will-chan** [comment]
Son, what should be the right behavior here?

**Comment by sonchang** [comment]
I think I recall Darren mentioning we should be careful about stopping containers so I think the best behavior would be to prompt the user.

**Comment by will-chan** [comment]
Perhaps this could be part of our "Trigger" feature.

**Comment by sonchang** [comment]
Related issue #1114
