### ISSUE TITLE
Not able to start LB containers with older images.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10069]
**Rancher versions:**
rancher/server: v1.6-development

Steps to reproduce the problem:

Scenario1:
Create a new LB service using older image ```rancher/lb-service-haproxy:v0.7.9```  using rancher cli.

Lb service fails to start with the following errors in logs:
```
10/10/2017 2:21:11 PMtime="2017-10-10T21:21:11Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
10/10/2017 2:21:11 PMtime="2017-10-10T21:21:11Z" level=info msg="CATTLE_ACCESS_KEY is not set, skipping init of Rancher LB provider"
10/10/2017 2:21:11 PMtime="2017-10-10T21:21:11Z" level=info msg="Starting Rancher LB service"
10/10/2017 2:21:11 PMtime="2017-10-10T21:21:11Z" level=fatal msg="CATTLE_ACCESS_KEY is not set, fail to init of Rancher LB provider"
```

**Comment by sangeethah** [comment]
Note - Scaling up existing services that was started in the previous version works fine.
Following are the use cases that fail:

1. Upgrading an LB service with older image ( without upgrading the image)
2. Cloning  an LB service with older image

**Comment by prachidamle** [comment]
@sangeethah we should re-test https://github.com/rancher/rancher/issues/10061 after this fix.

**Comment by sangeethah** [comment]
Rancher versions: upgraded to v1.6.11-rc3

Steps to reproduce the problem:
Fresh install of Rancher versions: v1.6.10.
Have few LBs created with targets.
Upgrade to v1.6.11-rc3.

Scenario 1:
Clone existing LB. 
Cloned LB service with older Lb image is able to start successfully.

Scenario 2:
Upgrade existing LB (by adding new labels).
Upgrade of existing LB succeeds.

Scenario 3:
Create a new LB service using older image rancher/lb-service-haproxy:v0.7.9 using rancher cli.
Lb is able to start successfully.

**Comment by prachidamle** [comment]
We should re-test this once PR#3066 is merged.

**Comment by sangeethah** [comment]
Retested all the above scenarios above with v1.6.11-rc4. 
All the scenarios work as expected.
