### ISSUE TITLE
Use per-host-network, Load Balancer failed to start

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10074]
**Rancher versions:**
rancher/server: v1.6-development
rancher/net :v0.13.0

**Docker version: **
17.06.2-ce

**Type/provider of hosts: **
AWS

**Environment Template: **
Cattle

**Steps to Reproduce:**
1. Create a new environment with Use per-host-network.
2. Add a nginx service.
3. Add Load Balancer, and Target points to the nginx service.
**Results:**
Load Balancer failed to start
```
level=fatal msg="Error reading self service metadata: Error 404 accessing /self/service path

```

https://github.com/rancher/rancher/issues/9153

**Comment by niusmallnan** [comment]
Cause Analysis:
When a container wants to read `/self/service` from metadata, this depends on whether the metadata already has the IP information for the container.

The `per-host-subnet` networking doesn't use rancher-ipam, it uses `host-local-ipam`.
The `host-local-ipam` runs on each agent node.
When a container starts to run, this container has no IP address, it shoud wait `host-local-ipam` to allocate IP. Then rancher-agent can read this container's IP and push it to rancher-server.
Finally, we can read this container's IP information in the metadata.

If the container has been started, but the metadata has not yet received the container IP information, it will appear this error.

**This is a common issue** for `per-host-subnet`.
But for rancher-lb, there can be some hacking approach to avoid this problem.

I will make a PR to rancher-lb, we can discuss the rationality of the program.
@yasker @kingsd041

**Comment by kingsd041** [comment]
**Rancher versions:**
rancher/server: v1.6.11-rc4
rancher/lb-service-haproxy: v0.7.14
rancher/net: v0.13.1

Issue has been fixed.

LB logs:
```
2017/10/20 上午11:50:19Waiting for metadata self service
2017/10/20 上午11:50:20e57ab9ae-be15-4f72-9295-fa741d390b61time="2017-10-20T03:50:20Z" level=info msg="Starting Rancher LB service"
2017/10/20 上午11:50:20time="2017-10-20T03:50:20Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
2017/10/20 上午11:50:20time="2017-10-20T03:50:20Z" level=info msg="CATTLE_ACCESS_KEY is not set, skipping init of Rancher LB provider"
2017/10/20 上午11:50:21time="2017-10-20T03:50:21Z" level=info msg="LB controller: rancher"
2017/10/20 上午11:50:21time="2017-10-20T03:50:21Z" level=info msg="LB provider: haproxy"
2017/10/20 上午11:50:21time="2017-10-20T03:50:21Z" level=info msg="starting rancher controller"
2017/10/20 上午11:50:21time="2017-10-20T03:50:21Z" level=info msg="Healthcheck handler is listening on :10241"
2017/10/20 上午11:50:21time="2017-10-20T03:50:21Z" level=info msg="Initializing event router" workerCount=250
2017/10/20 上午11:50:21time="2017-10-20T03:50:21Z" level=info msg="Connection established"
2017/10/20 上午11:50:21time="2017-10-20T03:50:21Z" level=info msg="Starting websocket pings"
2017/10/20 上午11:50:22time="2017-10-20T03:50:22Z" level=info msg=" -- starting haproxy\n * Starting haproxy haproxy\n[WARNING] 292/035021 (37) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n[WARNING] 292/035021 (38) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n   ...done.\n"
```
