### ISSUE TITLE
[UI] Wrong environment value for AzureUSGovernmentCloud

### ISSUE THREAD

**Issue by chriswastaken** [rancher/rancher#10073]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: n/a

**Infrastructure Stack versions:**
n/a

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure - AzureUSGovernmentCloud

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes
**Steps to Reproduce:**
Try to add a host in AzureUSGovernmentCloud
**Results:**
"Error with pre-create check:"Invalid Azure environment:\"AzureUSGovernment\", supported values: AzurePublicCloud,AzureUSGovernmentCloud,AzureChinaCloud,AzureGermanCloud"

Adjusting rancher/ui/app/utils/azure-choices.js line 304 to be AzureUSGovernmentCloud might resolve it.

**Comment by tfiduccia** [comment]
@chriswastaken - I am unable to add host to government section.  Can you verify in 1.6 after the next release?  Should be in v1.6.11.

**Comment by deniseschannon** [comment]
@chriswastaken As this was introduced in v1.6.11 and we don't have this Azure US govt cloud account. Please re-open if you are still having issues.

**Comment by chriswastaken** [comment]
@deniseschannon This works much better! I'm sorry that this isn't so quickly after you resolved it.  However, I'm running into a further issues around VM Size which I've detailed in #11609 . Thanks again!
