### ISSUE TITLE
documentation site > search results are full of ads

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#10079]
documentation site > search results are full of ads

this is a just too much:

![image](https://user-images.githubusercontent.com/2150990/31430559-86142424-ae71-11e7-814c-df254238bac0.png)

4 first links are ads, 5th is about an other version of rancher, and I don't even see the first real result flly.

**Comment by vincent99** [comment]
You cannot pay Google to not show ads anymore, and it doesn't work very well in general.  We will be looking at redoing the docs site after getting the main site off of WordPress and probably switching to Algolia or similar.
