### ISSUE TITLE
Script crowdin updates

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#10078]
The "source of truth" for all language translations files (except English) is in [CrowdIn](https://translate.rancher.com).  Syncing them with the git source is currently a manual pain.

Add a `scripts/update-translations` to the UI repo which uses the crowdin API, CLI, and/or Docker (preferably, instead of installing stuff) to:
  - Upload the current copy of `en-us` (and `zh-hans` if you want to start managing that as first-class language inside git) from local to crowdin
  - Create a "build" of the updated approved translations
  - Download the build
  - Update the appropriate files in `translations` (but don't touch `en-us`)
  - Bonus points: Print out how many keys are awaiting approval

(Assume `$CROWDIN_API_KEY` is set in the environment, and ping me on Slack for credentials.)

**Comment by deniseschannon** [comment]
@vincent99 Not sure there's anything to specifically test, but I've closed this. If you need more from @loganhz, re-open.
