### ISSUE TITLE
Modify environment name on the Rancher, metadata doesn't change

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10077]
**Rancher versions:**
rancher/server: Rancher 1.6.10 
rancher/external-dns: v0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Rancher catalog deployment Alibaba Cloud DNS.
2. Create service "foo" in stack "bar" belongs to environment "baz".
2. Modify the stack name or environment name on the rancher.
**Results:**
The A record and TXT record for the Aliyun DNS are not updated

Other：
**Infoblox DNS has the same bug**

**Comment by loganhz** [comment]
When you edit the stack name or env name, the metadata doesn't change.
It looks like metatdata doesn't change until the services are upgraded.
DNS just use what the stack name from metadata.
This issue can be linked to [rancher/rancher#7860](https://github.com/rancher/rancher/issues/7860)

**Comment by yasker** [comment]
https://github.com/rancher/rancher/issues/10234 should address this. It's in the latest 1.6. @kingsd041 can you try again?

**Comment by kingsd041** [comment]
@yasker  
Tested with rancher-server version- v1.6.11-rc6. 
When I change the stack name, A record and TXT record will be updated to Aliyun DNS.
**But modifying the environment name is still not updated.**

Can I close this Issue?

**Comment by yasker** [comment]
@alena1108 do you think modify environment name should be supported as well?

**Comment by alena1108** [comment]
@yasker sure

**Comment by loganhz** [comment]
Created a PR for the env name issue

**Comment by deniseschannon** [comment]
This needs a PR to use `rancher/external-dns:v0.7.9` for the relevant catalog entries using external DNS. .

**Comment by loganhz** [comment]
PR for catalog change is https://github.com/rancher/community-catalog/pull/688

**Comment by deniseschannon** [comment]
Available with template v0.3.0

**Comment by yasker** [comment]
Thanks @deniseschannon

**Comment by kingsd041** [comment]
@yasker 
Tested with rancher-server version- v1.6.13-rc2 with template v0.3.0.
When I change the environment name, A record and TXT record will be updated to Aliyun DNS.
Test passed.
