### ISSUE TITLE
auditLog authenticatedAsIdentityId contains invalid ID

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#10089]
AuditLog entries have an `authenticatedAsIdentity` and `authenticatedAsIdentityId` field.  The ID field contains a value that is different (numeric id not obfuscated) than the ID you get back if you actually look up the identity.

This breaks caching in the UI because I never think I've found it since no entry with that ID exists in memory:

```http
GET /v3/auditlogs/1al245
{
  "id": "1al245",
  "type": "auditLog",
  "links": {
    ...
    "authenticatedAsIdentity": "…/v3/identities/1i!rancher_id:7"
  },
  ...
  "authenticatedAsIdentityId": "1i!rancher_id:7",
}
```

```http
GET "…/v3/identities/1i!rancher_id:7"
{
  "id": "1i!rancher_id:1a7",
  "type": "identity",
  ...
}
```

**Comment by loganhz** [comment]
Close it as it is for old 2.0
