### ISSUE TITLE
Cannot add a host

### ISSUE THREAD

**Issue by CodingSpiderFox** [rancher/rancher#10084]
**Rancher versions:**
Rancher	v1.6.10
Cattle	v0.183.22
User Interface	v1.6.23
Rancher CLI	v0.6.4
Rancher Compose	v0.12.5
Rancher Agent v1.2.6

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:v0.11.9
network-services: rancher/metadata:v0.9.4
rancher/network-manager:v0.7.8
scheduler: rancher/scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
docker info:

Containers: 8
 Running: 5
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 1.957GiB
Name: nasvm
ID: WIH2:BB5H:YNWV:4UVY:UVR3:UBIO:EU42:L3L4:35DT:SVLI:TQGI:UFE6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux nasvm 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM on QNAP TS 251+ (don't know which Hypervisor they use)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Don't know - if I didn't configure kubernetes, swarm or mesos, I guess it's cattle, right?

**Steps to Reproduce:**
Start rancher behind a nginx reverse proxy. See config attached. 

With the command

sudo docker run -e CATTLE_AGENT_IP="a.b.c.d"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://rancher/v1/scripts/<HIDDEN_KEY>

try to add a node

**Results:**

rancher-server_1        | time="2017-10-11T20:14:45Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-10-10 23:34:30.470655098 +0000 UTC. Closing connection."
rancher-server_1        | time="2017-10-11T20:14:45Z" level=info msg="Exiting go-machine-service" service=gms
rancher-server_1        | time="2017-10-11T20:14:46Z" level=info msg="Starting go-machine-service..." gitcommit=v0.39.0 service=gms
rancher-server_1        | time="2017-10-11T20:14:46Z" level=info msg="Waiting for handler registration (1/2)" service=gms
rancher-server_1        | time="2017-10-11T20:14:48Z" level=info msg="Initializing event router" workerCount=5
rancher-server_1        | time="2017-10-11T20:14:48Z" level=info msg="Connection established"
rancher-server_1        | time="2017-10-11T20:14:48Z" level=info msg="Starting websocket pings"
rancher-server_1        | time="2017-10-11T20:14:48Z" level=info msg="Waiting for handler registration (2/2)" service=gms
rancher-server_1        | time="2017-10-11T20:14:48Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-10-10 23:34:33.588758506 +0000 UTC. Closing connection."
rancher-server_1        | time="2017-10-11T20:14:48Z" level=info msg="Exiting rancher-compose-executor" version=v0.14.18
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Initializing event router" workerCount=250
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Connection established"
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Starting websocket pings"
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Starting rancher-compose-executor" version=v0.14.18
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Updating driver packet from  => https://github.com/rancher/machine-package/releases/download/v0.10.0-pre1/docker-machine.tar.gz" service=gms
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Updating driver amazonec2 from  => https://github.com/rancher/machine-package/releases/download/v0.10.0-pre1/docker-machine.tar.gz" service=gms
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Initializing event router" workerCount=250
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Connection established"
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Starting websocket pings"
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Updating driver azure from  => https://github.com/rancher/machine-package/releases/download/v0.10.0-pre1/docker-machine.tar.gz" service=gms
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg=Event eventId=6481b463-6d98-4ff5-aa3a-3b7221596ba8 name="machinedriver.reactivate;handler=goMachineService-machine" resourceId=1md2 service=gms
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg="Updating driver digitalocean from  => https://github.com/rancher/machine-package/releases/download/v0.10.0-pre1/docker-machine.tar.gz" service=gms
rancher-server_1        | time="2017-10-11T20:14:49Z" level=info msg=Event eventId=ab30e56e-5027-499b-ab19-b4771f81f30b name="machinedriver.reactivate;handler=goMachineService-machine" resourceId=1md3 service=gms
rancher-server_1        | time="2017-10-11T20:14:50Z" level=info msg="Installing builtin drivers" service=gms
rancher-server_1        | time="2017-10-11T20:14:50Z" level=info msg="Downloading all drivers" service=gms
rancher-server_1        | time="2017-10-11T20:14:50Z" level=info msg=Event eventId=21e147d6-e4ad-4e19-abea-3aab8f00f72e name="machinedriver.reactivate;handler=goMachineService-machine" resourceId=1md4 service=gms
rancher-server_1        | time="2017-10-11T20:14:50Z" level=info msg="Done downloading all drivers" service=gms
rancher-server_1        | time="2017-10-11T20:14:51Z" level=info msg="Creating schema amazonec2Config, roles [service member owner project admin user readAdmin readonly restricted]" id=1ds1 service=gms
rancher-server_1        | time="2017-10-11T20:14:52Z" level=info msg="Creating schema azureConfig, roles [service member owner project admin user readAdmin readonly restricted]" id=1ds2 service=gms
rancher-server_1        | time="2017-10-11T20:14:52Z" level=info msg="Initializing event router" workerCount=250
rancher-server_1        | time="2017-10-11T20:14:52Z" level=info msg="Connection established"
rancher-server_1        | time="2017-10-11T20:14:52Z" level=info msg="Starting websocket pings"
rancher-server_1        | time="2017-10-11T20:14:53Z" level=info msg="Creating schema digitaloceanConfig, roles [service member owner project admin user readAdmin readonly restricted]" id=1ds3 service=gms
rancher-server_1        | time="2017-10-11T20:14:53Z" level=info msg="Updating machine jsons for  [amazonec2 packet amazonec2 azure digitalocean]" service=gms
rancher-server_1        | time="2017-10-11T20:14:53Z" level=info msg="Creating schema machine, roles [service]" id=1ds4 service=gms
rancher-server_1        | time="2017-10-11T20:14:54Z" level=info msg="Creating schema host, roles [service]" id=1ds5 service=gms
rancher-server_1        | time="2017-10-11T20:14:55Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds6 service=gms
rancher-server_1        | time="2017-10-11T20:14:56Z" level=info msg="Creating schema host, roles [project member owner]" id=1ds7 service=gms
rancher-server_1        | time="2017-10-11T20:14:57Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds8 service=gms
rancher-server_1        | time="2017-10-11T20:14:57Z" level=info msg="Creating schema host, roles [admin user readAdmin]" id=1ds9 service=gms
rancher-server_1        | time="2017-10-11T20:14:58Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds10 service=gms
rancher-server_1        | time="2017-10-11T20:14:58Z" level=info msg="Creating schema host, roles [readonly]" id=1ds11 service=gms
rancher-server_1        | time="2017-10-11T20:14:59Z" level=info msg="Updating machine jsons for  [azure packet amazonec2 azure digitalocean]" service=gms
rancher-server_1        | time="2017-10-11T20:15:01Z" level=info msg="Creating schema machine, roles [service]" id=1ds12 service=gms
rancher-server_1        | time="2017-10-11T20:15:03Z" level=info msg="Creating schema host, roles [service]" id=1ds13 service=gms
rancher-server_1        | time="2017-10-11T20:15:03Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds14 service=gms
rancher-server_1        | time="2017-10-11T20:15:04Z" level=info msg="Creating schema host, roles [project member owner]" id=1ds15 service=gms
rancher-server_1        | time="2017-10-11T20:15:04Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds16 service=gms
rancher-server_1        | time="2017-10-11T20:15:05Z" level=info msg="Creating schema host, roles [admin user readAdmin]" id=1ds17 service=gms
rancher-server_1        | time="2017-10-11T20:15:05Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds18 service=gms
rancher-server_1        | time="2017-10-11T20:15:06Z" level=info msg="Creating schema host, roles [readonly]" id=1ds19 service=gms
rancher-server_1        | time="2017-10-11T20:15:06Z" level=info msg="Updating machine jsons for  [digitalocean packet amazonec2 azure digitalocean]" service=gms
rancher-server_1        | time="2017-10-11T20:15:08Z" level=info msg="Creating schema machine, roles [service]" id=1ds20 service=gms
rancher-server_1        | time="2017-10-11T20:15:10Z" level=info msg="Creating schema host, roles [service]" id=1ds21 service=gms
rancher-server_1        | time="2017-10-11T20:15:11Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds22 service=gms
rancher-server_1        | time="2017-10-11T20:15:12Z" level=info msg="Creating schema host, roles [project member owner]" id=1ds23 service=gms
rancher-server_1        | time="2017-10-11T20:15:12Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds24 service=gms
rancher-server_1        | time="2017-10-11T20:15:12Z" level=info msg="Creating schema host, roles [admin user readAdmin]" id=1ds25 service=gms
rancher-server_1        | time="2017-10-11T20:15:13Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds26 service=gms
rancher-server_1        | time="2017-10-11T20:15:13Z" level=info msg="Creating schema host, roles [readonly]" id=1ds27 service=gms
rancher-server_1        | time="2017-10-11T20:15:49Z" level=info msg=Event eventId=c270c9cd-7ae9-4eb9-b0ee-490746998d56 name="machinedriver.reactivate;handler=goMachineService-machine" resourceId=1md1 service=gms
rancher-server_1        | time="2017-10-11T20:15:49Z" level=info msg="Copying /var/lib/cattle/machine-drivers/1f7058341420e2f525168052818c3f819ff78e9ca5f57d5a650a049bcd5945e9-docker-machine-driver-packet => /usr/local/bin/docker-machine-driver-packet-tmp" service=gms
rancher-server_1        | time="2017-10-11T20:15:50Z" level=info msg="Creating schema packetConfig, roles [service member owner project admin user readAdmin readonly restricted]" id=1ds28 service=gms
rancher-server_1        | time="2017-10-11T20:15:50Z" level=info msg="Updating machine jsons for  [packet packet amazonec2 azure digitalocean]" service=gms
rancher-server_1        | time="2017-10-11T20:15:54Z" level=info msg="Creating schema machine, roles [service]" id=1ds29 service=gms
rancher-server_1        | time="2017-10-11T20:15:56Z" level=info msg="Creating schema host, roles [service]" id=1ds30 service=gms
rancher-server_1        | time="2017-10-11T20:15:56Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds31 service=gms
rancher-server_1        | time="2017-10-11T20:15:57Z" level=info msg="Creating schema host, roles [project member owner]" id=1ds32 service=gms
rancher-server_1        | time="2017-10-11T20:15:57Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds33 service=gms
rancher-server_1        | time="2017-10-11T20:15:57Z" level=info msg="Creating schema host, roles [admin user readAdmin]" id=1ds34 service=gms
rancher-server_1        | time="2017-10-11T20:15:58Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds35 service=gms
rancher-server_1        | time="2017-10-11T20:15:59Z" level=info msg="Creating schema host, roles [readonly]" id=1ds36 service=gms
rancher-server_1        | 2017-10-11 20:16:11,258 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p
[docker-stack.zip](https://github.com/rancher/rancher/files/1377072/docker-stack.zip)
.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [3]
rancher-server_1        | 2017-10-11 20:16:16,263 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [4]
rancher-server_1        | 2017-10-11 20:16:21,264 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [5]
rancher-server_1        | 2017-10-11 20:16:26,266 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [6]
rancher-server_1        | 2017-10-11 20:16:26,267 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Scheduling reconnect for [2]
rancher-server_1        | 2017-10-11 20:16:30,725 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [7]
rancher-server_1        | 2017-10-11 20:16:35,730 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [8]
rancher-server_1        | 2017-10-11 20:16:40,736 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [9]
rancher-server_1        | 2017/10/11 20:29:32 http: proxy error: net/http: request canceled

**Comment by CodingSpiderFox** [comment]
PS: The node I tried to add is the VM where rancher runs behind the proxy

**Comment by CodingSpiderFox** [comment]
The same versions on the same host worked.

Rancher-server
sudo docker run -d -v <host_vol>:/var/lib/mysql --restart=unless-stopped -p 8080:8080 rancher/server

Agent:
sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://<a.b.c.d>/v1/scripts/<HIDDEN_KEY>

**Comment by CodingSpiderFox** [comment]
Must have something to do with the reverse proxy. I fixed this by specifying <IP>:<PORT> instead of <HOSTNAME> (which should have been forwarded to the <rancher-server container>:8080 by the nginx reverse proxy. Maybe something in the nginx config is wrong. Help would be appreciated

**Comment by superseb** [comment]
Can you add the logs from the `rancher/agent` container, this will point out the problem. We have an example config for nginx here; http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#example-nginx-configuration

**Comment by superseb** [comment]
Please reply if you need help on this.
