### ISSUE TITLE
K8s certs assume k8s will be discovered using rancher-dns

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#10086]
we currently generate the certs assuming k8s will be discovered using rancher-dns. We should add sky-dns resolvable fqdn to the list.

Example error message:
```
time=“2017-10-11T17:17:15Z” level=error msg=“Cannot initialize services collection: unable to list Kubernetes services: unable to query any API servers: Get https://kubernetes.default.svc/api/v1/services: x509: certificate is valid for 10.43.0.1, kubernetes, kubernetes.kubernetes, kubernetes.kubernetes.rancher.internal, not kubernetes.default.svc” source=“service.go:117”
```

**Comment by xetys** [comment]
fix https://github.com/rancher/rancher-catalog/pull/966 is not complete, I would add all conventions here

**Comment by sangeethah** [comment]
Tested with K8s - v1.9.2-rancher-1.

SAN now has additionally the  following 2 dns entries - ```DNS:kubernetes.default.svc.cluster, DNS:kubernetes.default.svc,```

Log into kubernetes service containers:
go /etc/kubernetes/ssl
execute this command `openssl x509 -noout -text -in cert.pem`

SAN has the following entries now:

```
            X509v3 Subject Alternative Name:
                IP Address:10.43.0.1, DNS:10.43.0.1, DNS:kubernetes.default.svc.cluster.local, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.default.svc, DNS:kubernetes, DNS:kubernetes.kubernetes, DNS:kubernetes.kubernetes.rancher.internal

```
