### ISSUE TITLE
load balancer losses a container reference after upgrading a container

### ISSUE THREAD

**Issue by kpolszewski** [rancher/rancher#10080]
**Rancher versions:**
rancher/server: v2.0.0-alpha9 (preview)
rancher/agent: v2.0-alpha4

**Steps to Reproduce:**
1. add container (e.x. ghost)
2. add a load balaner with some rule targeting a container from point 1
3. upgrade a container from point 1

**Results:**
load balancer's rule lacks a container reference
![image](https://user-images.githubusercontent.com/26391541/31445683-d65bd6de-ae9e-11e7-97f3-7fd7462baa93.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 10/17
This is reproducible on current master.  When we edit/upgrade container, we delete the old container and create a new one.  Since it's a new container with a new id, the load balancer can no longer find it.

**Comment by alena1108** [comment]
seems to be very similar to https://github.com/rancher/rancher/issues/10043
