### ISSUE TITLE
Support drain_timeout_ms in docker-compose

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10088]
Currently we are allowed to add ```drain_timeout_ms``` in rancher-compose.yml only. 
We should be allowed to add  ```drain_timeout_ms``` in docker-compose as well.

**Comment by prachidamle** [comment]
The field drain_timeout_ms worked in both compose files.

**Comment by sangeethah** [comment]
Tested with rancher cli version - v0.6.5-rc1 
 drain_timeout_ms works in both compose files.
