### ISSUE TITLE
Add Licenses

### ISSUE THREAD

**Issue by CodingSpiderFox** [rancher/rancher#10085]
Please add licenses to all rancher repos as far as applicable. 

For example, https://github.com/rancher/agent-instance currently doesn't have a license

**Comment by CodingSpiderFox** [comment]
Any updates on this one?

**Comment by CodingSpiderFox** [comment]
You should keep this open. Or simply add licenses. Shouldn't be too hard.

**Comment by loganhz** [comment]
Thanks. I am looking at it

**Comment by loganhz** [comment]
We need to add license to the following repos

https://github.com/rancher/cadvisor-package
https://github.com/rancher/agent-binaries
https://github.com/rancher/longhorn-catalog
https://github.com/rancher/openstack-catalog
https://github.com/rancher/agent-instance
https://github.com/rancher/os-vbox
https://github.com/rancher/ui-driver-rackhd
https://github.com/rancher/ui-example-addon-machine
https://github.com/rancher/kubernetes-model
https://github.com/rancher/demo-compose-templates
https://github.com/rancher/rancher-swarm
https://github.com/rancher/sherdock
https://github.com/rancher/qind
https://github.com/rancher/drone-sd
https://github.com/rancher/etcdb
https://github.com/rancher/test-images
https://github.com/rancher/zookeeper
https://github.com/rancher/rancherclient-gloang
https://github.com/rancher/rancher-node-simulator
https://github.com/rancher/docker-alpine-stunnel
https://github.com/rancher/tiny-build
https://github.com/rancher/vagrant
https://github.com/rancher/server-chart
https://github.com/rancher/docs
https://github.com/rancher/quickstart
https://github.com/rancher/charts
https://github.com/rancher/rancher.github.io
https://github.com/rancher/pipeline-example-go
https://github.com/rancher/rancher-catalog
https://github.com/rancher/install-docker
https://github.com/rancher/longhorn-ui
https://github.com/rancher/jenkins-rancher-validations
https://github.com/rancher/community-catalog
https://github.com/rancher/machine-package
https://github.com/rancher/pipeline-tools
https://github.com/rancher/pipeline-kube-apply
https://github.com/rancher/rio-website
https://github.com/rancher/buildroot
https://github.com/rancher/best-practice-guide
https://github.com/rancher/rancher-logs-collector
https://github.com/rancher/rancher-net
https://github.com/rancher/ansible-playbooks
https://github.com/rancher/ipsec
https://github.com/rancher/terraform-modules
https://github.com/rancher/pipeline-jenkins-server
https://github.com/rancher/pre-pull-images
https://github.com/rancher/os-system-docker
https://github.com/rancher/go-rancher-metadata
https://github.com/rancher/rancher-tools-catalog
https://github.com/rancher/k8s-training-templates
https://github.com/rancher/strato
https://github.com/rancher/strato-packages
https://github.com/rancher/jenkins-boot
https://github.com/rancher/windows-binaries
https://github.com/rancher/win-route-netsh
https://github.com/rancher/swarmkit-operator
https://github.com/rancher/test-catalog
https://github.com/rancher/smoketest
https://github.com/rancher/network-diagnostics
https://github.com/rancher/socat-test
https://github.com/rancher/strongswan-package
https://github.com/rancher/goautoneg
https://github.com/rancher/brand-guidelines
https://github.com/rancher/qa-catalog
https://github.com/rancher/public-dns-client
https://github.com/rancher/training-exercises
https://github.com/rancher/build-tools
https://github.com/rancher/git-container
https://github.com/rancher/flavors
https://github.com/rancher/infra-catalog
https://github.com/rancher/rancher-catalog-service
https://github.com/rancher/confd-base
https://github.com/rancher/telemetry-ui
https://github.com/rancher/os-engines
https://github.com/rancher/windows-bootstrap
https://github.com/rancher/rancher-catalog-v1.1
https://github.com/rancher/secrets-bridge
https://github.com/rancher/convoy-agent

**Comment by vincent99** [comment]
Many of those are going to be ancient abandoned things that are little more than a dockerfile or catalog item and should just be archived, or other special cases...

**Comment by vincent99** [comment]
The list above is virtually all old 1.x stuff.  If there are specific modern repos missing a license please open an issue in them (or here if issues are disabled).
