### ISSUE TITLE
Sometimes, a host will display multiple additions

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/rancher#10093]
**Rancher versions:**
rancher/server:v1.6.5 - v1.6.10
rancher/agent:default

**Infrastructure Stack versions:**
healthcheck:default
ipsec:default
network-services:default
scheduler:default
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
All supported versions
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
All supported versions
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware 、VirtualBox、Ali cloud、Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
All
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Hi,all
    This is an occasional problem. A host that has been added, When the add command is executed again, two of the same hosts are displayed on the Infrastructure\host page,For example, the following pictures：
<img width="629" alt="1" src="https://user-images.githubusercontent.com/20707603/31476708-7353fd54-af3a-11e7-982d-9c9093d5c838.png">

**Steps to Reproduce:**
Edit the /var/lib/rancher/state/.registration_token file, modify the value inside, and then add the add host command again.

**Results:**
![2](https://user-images.githubusercontent.com/20707603/31478500-59902e20-af43-11e7-80dc-c38287cef38f.jpg)

**Comment by yasker** [comment]
I think it can be added to https://github.com/rancher/rancher/issues/10093

**Comment by vincent99** [comment]
What?  This isn't a problem, the UUID **is** the identity of the host, if you change it, it is by definition a different host.

**Comment by yasker** [comment]
To @hongxiaolu 's defense, modify token is not acceptable, but we shouldn't accept the host with the same IP anyway, as we stated in #9326 .
