### ISSUE TITLE
Having a host without FQDN added to a Kubernetes environment makes cloudprovider fail to lookup hosts with FQDN added after

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10096]
**Rancher versions:**
rancher/server:v1.6.10 and v2.0.0-alpha10
rancher/agent:v1.2.6 and v2.0.0-alpha4

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.7.7-rancher1

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create Kubernetes environment
2. Add a host with `hostname` and `hostname -f` returning hostname only, i.e. `host1`
3. Add a host with `hostname -f` returning FQDN, i.e. `host2.local`

**Results:**
`kubelet` container on `host2.local` will log:

```
E1012 12:52:08.805135   12170 kubelet_node_status.go:357] Error updating node status, will retry: error getting node "host2.local": nodes "host2.local" not found
```
**Solution:**
This statement in the else (which is only triggered when a hostname is found) overwrites `hostname` while it should be using `rancherHostname`. It should also not use `fqdnParts[0]` but `rancherFQDNParts[0]`.

Code:
https://github.com/rancher/kubernetes/blob/v1.7.7-rancher/pkg/cloudprovider/providers/rancher/rancher.go#L818

I copied the cloudprovider code to Golang playground to test, see the `// Bugged` and `// Fix`
https://play.golang.org/p/XGaPbjvXBk

**Comment by diegodurante** [comment]
We are also facing this issue with Rancher 1.16.12, Kubernetes 1.8.3 with plane isolation, Docker 17.03.2-ce, and a Cloud provider that is different from AWS/Azure/GCP etc...

Here all information about what we are facing: https://github.com/rancher/rancher/issues/10616

**Comment by sn00p** [comment]
racnher v1.6.13, k8s v1.8.5, docker 1.13.1, cloudprovider rancher. 
Old cluster with 5 nodes registered with short name can't add another host registered with FQDN with error
` E0107 14:29:42.102306   16341 kubelet_node_status.go:79] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: instance not found
`
Changing hostname of new node to short name fixes node registration. 
prod-dc-kubernetes-01      Ready     <none>    103d      v1.8.5-rancher1
prod-dc-kubernetes-02      Ready     <none>    103d      v1.8.5-rancher1
prod-dc-kubernetes-03      Ready     <none>    103d      v1.8.5-rancher1
prod-dc-kubernetes-04      Ready     <none>    103d      v1.8.5-rancher1
prod-dc-kubernetes-05      Ready     <none>    103d      v1.8.5-rancher1
prod-dc-vm-kubernetes-01   Ready     <none>    38s       v1.8.5-rancher1

**Comment by strowi** [comment]
did anyone find a solution to this?
