### ISSUE TITLE
Kubernetes agent didn't populate Kubernetes service to Rancher correctly

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#10099]
**Rancher versions:**
rancher/server: v1.6.11-rc3
kubernetes (if applicable): 1.8

when the call to Rancher API to add the kubernetes services fails for any reason the service doesn't get populated ever:
```
time="2017-10-11T19:00:33Z" level=info msg="Received event: [ADDED] for Service: default/tea-svc, Handling event." 
time="2017-10-11T19:00:33Z" level=error msg="Error Handling event: [ADDED] for Service default/tea-svc: Post https://x.x.x.x:8080/v2-beta/externalserviceevents: EOF" 
```
The only way to repopulate the service is to delete and recreate it:
```
time="2017-10-11T19:17:50Z" level=info msg="Received event: [DELETED] for Service: default/tea-svc, Handling event." 
time="2017-10-11T19:18:01Z" level=info msg="Received event: [ADDED] for Service: default/tea-svc, Handling event."
```

We should add a retry to kubernetes agent for the service add event handler.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
