### ISSUE TITLE
Pending: containers with incomplete status: [dns-init];containers with unready status: [first-773b1d80-ac46-4064-973b-8919ff11b7f5 rancher-pause]

### ISSUE THREAD

**Issue by dotnet123** [rancher/rancher#10092]
Rancher versions:2.0
I add a new container, but it took this error message.

1)

![1](https://user-images.githubusercontent.com/21954452/31475857-b0bd9ec0-af35-11e7-8869-9e3d4a4157c7.png)

2)

![tim 20171012100542](https://user-images.githubusercontent.com/21954452/31475753-302b0d42-af35-11e7-8484-ea226dc941b8.png)

**Comment by superseb** [comment]
Can you switch to `System` (top right) and show the container and host status from there?

**Comment by superseb** [comment]
With the release of Tech Preview 2, the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha16 is most likely invalid.

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM) to learn more about the changes in 2.0 in Tech Preview 2.

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha16+). As always, thanks for using Rancher!
