### ISSUE TITLE
 scheduler service keeps removing itself and restart.   

### ISSUE THREAD

**Issue by zk4** [rancher/rancher#10113]
*Describe your issue here*
scheduler service keeps removing itself and restart.    the other user service all unavailable. like wordpress, gitlab.
this happens after I have restarted the host for serval times.
 I notice  that host  "ubuntu2"`s ip changed from 192.168.0.19  to 172.17.0.1.  is that the cause?
![image](https://user-images.githubusercontent.com/996674/31530520-b65cf2ce-afa6-11e7-9da1-6f70624d6fbf.png)

![image](https://user-images.githubusercontent.com/996674/31530336-5ee95934-afa5-11e7-944d-5e70cbad6b2c.png)

![image](https://user-images.githubusercontent.com/996674/31530365-910624b0-afa5-11e7-9cc2-f827f01e145c.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by superseb** [comment]
If you have multi-homed hosts or are running the `rancher/agent` container on the same hosts as the `rancher/server` container, be sure to specify `-e CATTLE_AGENT_IP=host_ip` when running the `rancher/agent` container. This will make sure it's registered with the correct IP so the overlay network can be created.

**Comment by VinceBT** [comment]
Did this trick and still the scheduler keeps restarting

**Comment by superseb** [comment]
Please delete the scheduler container (not the stack or service), and let it be re-created. If it still keeps restarting, please share the logs of the scheduler container. (assuming all the hosts have their correct IPs now)

**Comment by VinceBT** [comment]
Does the stack creates the containers itself or do I have to upgrade it ?

**Comment by superseb** [comment]
Assuming the rest of the infrastructure stack services are running ok, it comes back automatically if you only delete the container (2nd screenshot on the bottom, not the top)

**Comment by VinceBT** [comment]
The hosts are set correctly as they have their external IP and not their public one, the server is one the first and it had 172.x.x.x before I used ``` -e CATTLE_AGENT_IP="$(ifconfig enp1s0 | grep 'inet ' | cut -d ' ' -f10 | awk '{ print $1}')"```

![image](https://user-images.githubusercontent.com/1362505/31905583-f363e44e-b82e-11e7-9c7c-b625eec32011.png)

**Comment by VinceBT** [comment]
Here are the logs
![image](https://user-images.githubusercontent.com/1362505/31905748-7adf6ca4-b82f-11e7-9e6a-8f971078f25c.png)

**Comment by superseb** [comment]
Any chance you can jump on Rancher Users Slack and show me this? (https://slack.rancher.io)

**Comment by superseb** [comment]
Tracked this down to overloaded host running the `rancher/server` and `rancher/agent` where the user `jenkins` was logged in and was spawning a lot of processes. Server load was ~3000 and machines was almost unresponsive. Killed the jenkins, cleaned up the host and it recovered.

**Comment by tuwid** [comment]
Have the same issue, machine is not overloaded running rancher/server:v1.6.30
