### ISSUE TITLE
Adding a cluster after deleting last one generates UI error

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#10118]
**Rancher versions:**
rancher/server: v2.0.0-alpha10

On manage clusters page

1. Remove all clusters.
2. Click Add Cluster button.

First time the UI shows a red error message:
`There are no active environments. You will need to create or activate one before you can do anything else.`

The second time you click Add Cluster button, you can proceed.

**Comment by loganhz** [comment]
can not reproduce this issue

**Comment by deniseschannon** [comment]
@loganhz this is before the new 2.0 changes.
