### ISSUE TITLE
[external-dns] Result set too large (> 1000) when using Infoblox provider

### ISSUE THREAD

**Issue by samihamza** [rancher/rancher#10117]
**Rancher versions:**
rancher/server: 1.6
rancher/agent: 1.6

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:net:v0.11.2
metadata:v0.9.1
scheduler:v0.7.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.2 LTS  Linux 4.4.0
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Install Infoblox Plugin from Rancher Catalog 
**Results:**
```
13/10/2017 14:51:21time="2017-10-13T12:51:21Z" level=info msg="Starting Rancher External DNS service v0.7.5"
13/10/2017 14:51:212017/10/13 12:51:21 WARNING: SSL cert verification  disabled
13/10/2017 14:51:212017/10/13 12:51:21 GET /wapi/v1.4/zone_auth  payload:
13/10/2017 14:51:222017/10/13 12:51:22 GET /wapi/v1.4/record:a?_return_fields=ttl,name,zone,disable,ipv4addr  payload:
13/10/2017 14:51:22time="2017-10-13T12:51:22Z" level=info msg="Healthcheck handler is listening on :1000"
13/10/2017 14:51:24time="2017-10-13T12:51:24Z" level=fatal msg="Failed to ensure upgrade: Infoblox API call decode has failed: Error AdmConProtoError: Result set too large (> 1000) - Client.Ibap.Proto - Result set too large (> 1000)"
```

**Comment by deniseschannon** [comment]
@samihamza can you test again with the latest template?
