### ISSUE TITLE
rancher2.0部署k8s集群

### ISSUE THREAD

**Issue by yoo2767** [rancher/rancher#10115]
求rancher2.0部署k8s集群教程

**Comment by niusmallnan** [comment]
Rancher2.0使用非常简单，使用embedded模式，添加Host之后，就是k8s集群。
为什么不去动手试一试，学习的过程就是成长的过程。

另外，这里是一个国际化的交流社区，不建议你使用中文，这样对其他国家的人很不友好。

Close this issue.

**Comment by yoo2767** [comment]
OK!
I try it !
