### ISSUE TITLE
Service Links removed automatically, without notification

### ISSUE THREAD

**Issue by autumnus** [rancher/rancher#10116]
I had a mongodb container, which was not reachable/stoppable/restartable/killable anymore.
So I hat to remove it ( with "docker rm --force") and create it new. As I have a lot of other containers, which have a service link to that I chose the same name.

BUT:
In all stacks/services the service link was removed!
On the one hand, I understand, because the IP of the container changes and the destination of the link just vanished.
On the other hand I had the problem, that I had to search through all stacks and remember, if there was a link, and which name it had. And I had to restart all that containers.

If it is really necessary to remove the service link, it would have been nice to be notified in which stack which changes were made! 

(great tool nevertheless!!)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.5` Cattle: `v0.182.1` UI: `v1.6.9` |
|Access|`localauth` |
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
