### ISSUE TITLE
Could you support Keybase Git system?

### ISSUE THREAD

**Issue by MichelDiz** [rancher/rancher#10122]
https://keybase.io/blog/encrypted-git-for-everyone

**Comment by vincent99** [comment]
Not at present, the helper would have to be loaded into the server container in the first place and then you need to login to a user that has access inside there too, and be multi-tenant-safe, etc.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
