### ISSUE TITLE
Vultr driver not working

### ISSUE THREAD

**Issue by MichelDiz** [rancher/rancher#10125]
**Rancher versions:**
rancher/server: v2.0.0-alpha9
rancher/agent: from v2.0.0-alpha9 command

*inside the Vm Photon OS (docker)

**Comment by MichelDiz** [comment]
I removed the alpha version and installed "Latest". Vultr drive work, but does not appear in the Add Host options. I open a new issue?

Component	Version
Rancher	v1.6.10
Cattle	v0.183.22
User Interface	v1.6.23
Rancher CLI	v0.6.4
Rancher Compose	v0.12.5

**Comment by tfiduccia** [comment]
@MichelDiz - this is already fixed and will be in the next version

**Comment by tfiduccia** [comment]
Closing in favor of new 2.0 UI.  Vultr will be tested as part on new machine driver code.
