### ISSUE TITLE
A highly available scheduling scheme？

### ISSUE THREAD

**Issue by goudai** [rancher/rancher#10123]
I am wondering if I can have a new scheduling scheme, a highly available scheduling scheme that ensures that the application 's replica set is always running on a specified number of physical machines, such as 10 physical machines, applications Started 15 copies of the set, I hope that the 15 copies of the set can be balanced to the distribution of the 10 physical machines, rather than now always scheduled to the same 1-3 machines.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
