### ISSUE TITLE
git.rancher.io being down shouldnt cause server to not start

### ISSUE THREAD

**Issue by aequasi** [rancher/rancher#10120]
**Rancher versions:**
rancher/server: preview

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OVH Baremetal

**Steps to Reproduce:**
Run rancher/server:preview while https://git.rancher.io/community-catalog.git is unavailable

**Results:**
Rancher Server wont start

**Comment by aequasi** [comment]
Loops while logging this:

```
time="2017-10-14T00:23:32Z" level=error msg="Catalog refresh failed for community (https://git.rancher.io/community-catalog.git): Remote commit check failed: Repo [https://git.rancher.io/community-catalog.git] is not accessible: Get https://git.rancher.io/repos/community-catalog/commits/v2.0-release: dial tcp: lookup git.rancher.io on 8.8.4.4:53: read udp 172.17.0.2:46543->8.8.4.4:53: i/o timeout"
time="2017-10-14T00:23:32Z" level=error msg="Catalog refresh failed for library (https://git.rancher.io/rancher-catalog.git): Remote commit check failed: Repo [https://git.rancher.io/rancher-catalog.git] is not accessible: Get https://git.rancher.io/repos/rancher-catalog/commits/v2.0-release: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

**Comment by vincent99** [comment]
Did you actually try to go to it?  The catalog service and various other things are separate processes, the server is already up and listening on 8080 before catalog service is even started.

The server is up when  `Startup Succeeded, Listening on port 8081` is printed (8080 is a proxy that routes requests around, so the actual server is on 8081).

**Comment by aequasi** [comment]
I did, but i might have been having some other DNS issues at the time.

**Comment by aequasi** [comment]
Can close
