### ISSUE TITLE
credentialProvider mixing up private registry credentials

### ISSUE THREAD

**Issue by fdevaux** [rancher/rancher#10139]
**Rancher versions:**
rancher/server: 1.6.8
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.11.9
network-services: 0.7.8
scheduler: 
kubernetes (if applicable): 1.7.7-rancher1

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   ac13b2b
 Built:        Wed Mar 22 02:52:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   ac13b2b
 Built:        Wed Mar 22 02:52:47 2017
 OS/Arch:      linux/amd64
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.4"
ID="ol"
VERSION_ID="7.4"
PRETTY_NAME="Oracle Linux Server 7.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.4

# uname -r
4.1.12-94.3.9.el7uek.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Openstack/KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

Define multiple private registries with different credentials

**Results:**

The Kubernetes rancher credentialProvider appears to be mixing up the credentials from different private registries. 

E.g. say I have `registry1.corp.com:5000` with `user1/pass1` and `registry2.corp.com:5000` with `user2/pass2`. 
- Defining just registry1 everything works fine. 
- After adding registry2 pulls from registry1 will start to fail (kubelet erroring with `Failed to pull image 'registry1.corp.com/some/image": rpc error: code = 2 desc = unauthorized: authentication required`)
- Changing the credentials for registry2 to `user1/pass1` pulls from registry1 start to work again.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
