### ISSUE TITLE
Some container stats are n/a but docker stats has data

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#10130]
Docker stats shows:
<img width="935" alt="screen shot 2017-10-17 at 10 06 13 am" src="https://user-images.githubusercontent.com/131730/31639118-daa1ccd4-b322-11e7-9b51-677da8b8fc72.png">

However rancher shows the container as n/a for stats in the hosts view:
<img width="1431" alt="screen shot 2017-10-17 at 10 07 01 am" src="https://user-images.githubusercontent.com/131730/31639143-f610a792-b322-11e7-988e-f0b6632f2a5b.png">

If I click through to the container, we can see the stats ok:
<img width="1515" alt="screen shot 2017-10-17 at 10 07 48 am" src="https://user-images.githubusercontent.com/131730/31639177-1b761968-b323-11e7-871d-6419a002f3b9.png">

**Rancher versions:**
rancher/server: 1.6.10

**Docker version: (`docker version`,`docker info` preferred)**
17.03.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Does not occur with all container services, but usually most.

**Comment by Ariemeth** [comment]
I'm seeing the same thing using docker 17.06.2-ce with the default kubernetes template

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
