### ISSUE TITLE
Schema type change for memorySwap/memory for container

### ISSUE THREAD

**Issue by prashant68** [rancher/rancher#10141]
Hi Guys,

Excellent work.. Thank you.  I have noticed that generated Java object (rancher-java-sdk git project) for Container.getMemory() is getting integer.  When memory is high (256GB), running into integer overflow issue.   Is it possible to change the type from "int" --> "long".  

      "id": "container",
      "type": "schema",
      "links": {
        "self": "http://xxxxxxxxx:8080/v2-beta/schemas/container",
        "collection": "http://xxxxxxxx:8080/v2-beta/containers"
      },
      "actions": {},
      "pluralName": "containers",
      "resourceFields": {
      ....
        "memorySwap": {
          "type": "int",
          "description": null,
          "create": true,
          "update": false,
          "nullable": true,
          "readOnCreateOnly": false
        },
        "memory": {
          "type": "int",
          "description": null,
          "create": true,
          "update": false,
          "nullable": true,
          "readOnCreateOnly": false
        },

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.7` Cattle: `v0.183.5` UI: `v1.6.17` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
