### ISSUE TITLE
Health Check stuck Initializing when used a host that have a connection via VPN to the server where is rancher

### ISSUE THREAD

**Issue by ElPsyCongro** [rancher/rancher#10148]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.1.4
network-services: v0.2.6
scheduler: v0.6.3

**Docker version:**
Docker version 17.06.2-ce, build cec0b72

Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1022-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: ip-172-31-36-116
ID: 6FWI:DJAB:IRFB:2JXT:EUJO:TDBW:JZHD:IV5A:2ONN:62XH:LHXU:AJNK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

This docker info is from one of the hosts.

**Operating system and kernel:**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-1022-aws

**Type/provider of hosts:**
AWS

**Setup details:)**
Single node rancher, internal DB

**Environment Template:**
Cattle

**Steps to Reproduce:**

1. I have a OpenVPN server hosted on AWS (I followed this guide https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04?comment=64972). This VPN configuration force all traffic trough the VPN connection.

2. I have a local server that doesn't have a public IP and is connected to the OpenVPN Server. This local server have the Rancher Server exposed through some port in order to be accesible via VPN_CLIENT_IP:PORT from others VPN Clients. (When a client is connected to the VPN it adds a tun0 interface with the corresponding IP for the VPN).

3. I created two instances in AWS, both have his OpenVPN client configuration and can ping to the local server. Also installed docker using this command `curl https://releases.rancher.com/install-docker/17.06.sh | sh` (Got it from here http://rancher.com/docs/rancher/latest/en/hosts/). Note: My VPN server is in another region and my host are them in the same region in AWS.

4. Add hosts, I use Elastic IP from AWS so I have to add the hosts of AWS via Custom. This the command that I execute in every host.
`sudo docker run -e CATTLE_AGENT_IP="HOST_PUBLIC_IP"  -e CATTLE_HOST_LABELS='type=cache'  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://RANCHER_LOCAL_SERVER_VPN_IP:PORT/v1/scripts/TOKEN`

**Results:**
 Results on the terminal when adding hosts

INFO: Running Agent Registration Process, CATTLE_URL=http://RANCHER_LOCAL_SERVER_VPN_IP:PORT/v1
INFO: Attempting to connect to: http://RANCHER_LOCAL_SERVER_VPN_IP:PORT/v1
INFO: http://RANCHER_LOCAL_SERVER_VPN_IP:PORT/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=ACCESS_KEY
INFO: ENV: **CATTLE_AGENT_IP=HOST_PUBLIC_IP**
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_HOST_LABELS=type=cache
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=http://RANCHER_LOCAL_SERVER_VPN_IP:PORT/v1
INFO: ENV: **DETECTED_CATTLE_AGENT_IP=HOST_VPN_IP**
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.6
INFO: Launched Rancher Agent: SOME_ID

![screen shot 2017-10-17 at 3 46 32 pm](https://user-images.githubusercontent.com/10093369/31693341-eb3bfb5c-b352-11e7-80d2-e9e274928ec2.png)

![screen shot 2017-10-17 at 3 51 35 pm](https://user-images.githubusercontent.com/10093369/31693371-1721a60e-b353-11e7-9c8b-e80f57d152e1.png)

Log of health check container stucked in Initializing
![screen shot 2017-10-17 at 3 52 22 pm](https://user-images.githubusercontent.com/10093369/31693424-562ed4ca-b353-11e7-9f5a-cfcff0d7474c.png)

And because of that can't ping between containers and there is no communication between my services that use those hosts.

Any help?

**Comment by ElPsyCongro** [comment]
@superseb here is the issue, any help?

**Comment by superseb** [comment]
The IP in `CATTLE_AGENT_IP="HOST_PUBLIC_IP"`, is used to configure the overlay network between nodes. That means that UDP/500 and UDP/4500 should be allowed between these hosts (so `HOST_PUBLIC_IP_HOST1` <- `UDP/500 + UDP/4500` -> `HOST_PUBLIC_IP_HOST2`). If you are forcing all traffic from the hosts through your VPN (not sure if this is the case) you probably have to use those IP's to set it up. Do you need to expose ports to the outside as well on these hosts?

**Comment by ElPsyCongro** [comment]
@superseb Yes I'm forcing all traffic through the VPN and yes if I use the VPN IPs of the hosts the connection works fine except that I use a host for a load balancer and assign a certificate to it. Said so, my app only will be reachable from inside the VPN (I think the edition of the service use the host IP that will be the private IP of the VPN causing to only be reachable from inside VPN) and I need it reachable from everywhere through the domain that needs to be pointing to the public IP of the host used for the load balancer. 
I don't know if I explain well what I'm trying to reach.

**Comment by leodotcloud** [comment]
@ElPsyCongro If you load balancer has both public and VPN ip address, then your app should be available via the public IP.

**Comment by ElPsyCongro** [comment]
@leodotcloud The Load Balancer host needs to be added with VPN IP address in order to get connection with the other services... Where can I assign the public IP to the Load Balancer host?
Or you mean that once added with the VPN IP it should be accesible through the Browser with the Public IP?

Maybe is the fact that I force all traffic through the VPN... because I can't ssh into the AWS host or see anything exposed on the Public IP through the browser unless I am connected to the VPN... I don't know anymore.

**Comment by leodotcloud** [comment]
@ElPsyCongro It's been a while since I worked on OpenVPN, but there is a setting in there where you don't have to route all the traffic through the tunnel but selected subnets.

Say for example if you have a host in AWS with public IP, acting as a loadbalancer, you can create a tun0 interface and use that IP for registering in rancher/server. In your lb config, you can point yourservice.company.com to your service IP address. Then you can use the public IP address of LB to expose your service to the outside world.

**Comment by ElPsyCongro** [comment]
@leodotcloud I see, umm you mean this configuration? 
<img width="1190" alt="screen shot 2017-10-24 at 2 06 55 pm" src="https://user-images.githubusercontent.com/10093369/31968058-ba510682-b8c4-11e7-893e-20c5f9d96855.png">

Right now I don't have the LB configured for the certificate but I think it should look something like this? ...

<img width="1205" alt="screen shot 2017-10-24 at 2 13 55 pm" src="https://user-images.githubusercontent.com/10093369/31968313-a081786c-b8c5-11e7-8960-8552a93e84a6.png">

Specifying the public IP and adding the certificate. Is this correct? If it is correct the only thing left to do I think it will be look up for that OpenVPN configuration you mentioned.

**Comment by leodotcloud** [comment]
That's Rancher's loadbalancer, I thought you were using your own load balancer?

**Comment by ElPsyCongro** [comment]
@leodotcloud No, sorry for the misunderstanding, I'm using Rancher's loadbalancer

**Comment by leodotcloud** [comment]
@ElPsyCongro yes you can use lb settings to be able to route to a service. Using the LB host's public IP address, your service should be addressable.

**Comment by ElPsyCongro** [comment]
Hi @leodotcloud and @superseb  I was able to reach then next state:

- I have my VPN Server that allows client-to-client communication without forcing all traffic through the VPN. 

- My Rancher is on a local Server without public IP and it's connected as a VPN client, reachable for any host that is also connected to the VPN.

- My Hosts are from Digital Ocean with their public IP and are also connected as a VPN client.

- My host where added using the private IP of the VPN (CATTLE_AGENT_IP) via Add Custom Host.

- I use a Load Balancer created with Rancher.

Now, All this setup makes the application reachable normally and the application works with public IP of the Load Balancer, but since the hosts where added with their private IP (VPN), I believe that the communication between those services occurs through the VPN tunnel leading on a really slow load time on my application.

A quick note, if I try to add the host via public IP, when I execute the command of the rancher agent in the host, it autodetects the CATTLE_AGENT_IP as the private IP (VPN) even when I specified the public IP on the command. Also the health-check fails and there is no communication between
health-check containers of the hosts

Through some poor research I find something about the Scheduler IPs for Hosts with more that one IP. I don't know if private and public count as more that one for rancher and also don't know for what the Scheduler IPs is for (I read the documentation about, but still I haven't understood at all what is it for).

I was wondering if you guys know some way to get the connection between services with the public IP but that the hosts also communicate with my local rancher with the private IP (VPN)?

**Comment by vincent99** [comment]
The agents open the connection to the server at the configured host registration URL.  It does nothing special here, so whatever the routing table says is how it's going to reach that IP. 

The overlay network is between the IP addresses shown on each host in the UI.  This is "auto detected" as the IP the agent connection (above) comes in from, and can be overridden with the CATTLE_AGENT_IP environment variable to the agent. All combinations of hosts in an environment need to be able to reach each other on that displayed IP on 500+4500/UDP.

Scheduler IPs is for publishing ports in services and has nothing to do with above.  With no configured scheduler IPs, ports (like the equivalent of `-p 80:80`) are bound to 0.0.0.0.  If you add a list of scheduler IPs to the host, one IP that has the desired port available is selected and the port is bound only to that IP. So your can have multiple services listening on 80, each on a different IP.

**Comment by ElPsyCongro** [comment]
@vincent99 thank you for you answer and the information about the Scheduler IPs.
And yes running the agent with the CATTLE_AGENT_IP it does add the host with the public IP and my local rancher recognize the host.
![screen shot 2018-03-05 at 4 16 21 pm](https://user-images.githubusercontent.com/10093369/37007596-e5dd1db4-2092-11e8-9d6a-03dcdccef094.png)

But I also get this errors again in the healthcheck container. 
<img width="299" alt="screen shot 2018-03-05 at 4 20 15 pm" src="https://user-images.githubusercontent.com/10093369/37007608-027ad84e-2093-11e8-826a-4f01a918340a.png">
<img width="957" alt="screen shot 2018-03-05 at 4 28 46 pm" src="https://user-images.githubusercontent.com/10093369/37007613-07c31046-2093-11e8-97a1-ab5b5fad6da2.png">

any help?

**Comment by vincent99** [comment]
Nothing in the log is an error... 

The alert triangle means the service is in initializing state.  The health check service also checks itself, and healthchecks run over the overlay network.  So this basically tells you that the overlay isn't working, because the healthcheck containers can't reach reach other.

You're showing one host with an x-ed out IP, so I can't really help you there.  But every host needs to be able to reach every other host using the IPs shown there, on 500/udp and 4500/udp.  And if you're going over a VPN you may need to adjust the MTU.

**Comment by ElPsyCongro** [comment]
Humm... 

The x-ed IP is the public IP of the Host and they have the inbound rules added (500/udp and 4500/udp). 

@vincent99 Thanks for the information, I will check the MTU and see if helps.

**Comment by ElPsyCongro** [comment]
Just to notify that the correct way to get this to work was

- Modifying the MTU in the client-config.ovpn of every host that need to be added and can only reach Rancher through VPN.
- Adding the host with the public IP specifying it on the CATTLE_AGENT_IP.

Thanks to everyone (@superseb, @leodotcloud, @vincent99) for the help. This issue can now be closed.
