### ISSUE TITLE
Upgrading Services that using Volumes

### ISSUE THREAD

**Issue by alexandrst88** [rancher/rancher#10159]
Hi! is there any documentation how to upgrade services that are using EBS, because when I prepared upgrade of service, i receive error that volume can be attached only to instance that container is running?

**Comment by loganhz** [comment]
https://rancher.com/docs/rancher/v1.6/en/rancher-services/storage-service/rancher-ebs/

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
