### ISSUE TITLE
Stack Name & -<number> not added to container name when converted to services

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10153]
**Rancher versions:** 2.0 master 10/16

**Steps to Reproduce:**
1.  Create a stack named "StackA"
2.  Create a container named "ContainerA"
3.  Convert the container to a service
4.  View the API of the new service's container

**Results:**  Notice the name of the container is "ContainerA", should be "StackA-ContainerA-1".  If I restart the service the name changes.

**Comment by alena1108** [comment]
@deniseschannon when container is converted to the service, its name doesn't change as changing it would require a container recreation. All new containers added to the service (by scaling it up), will have the correct names assigned.
