### ISSUE TITLE
rancher host is always disconnected

### ISSUE THREAD

**Issue by laoshancun** [rancher/rancher#10156]
## docker info
```
[root@docker-node1 ~]# docker info
Containers: 15
 Running: 14
 Paused: 0
 Stopped: 1
Images: 26
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 30.52 GiB
Name: docker-node1.hualv.net
ID: 4K3Y:NRIV:6OG7:WVHW:OSYW:HCWV:4I3A:VNNU:HGWP:YH62:JQ4P:INSD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com
Live Restore Enabled: false
```
## agent version : v1.2.6
agent error log
```
time="2017-10-18T01:59:21Z" level=error msg="Error writing EOT message." error="write unix @->/var/run/docker.sock: write: broken pipe"
time="2017-10-18T01:59:58Z" level=error msg="Error with the container log scanner." error="context canceled"
```

**Comment by superseb** [comment]
Can you please use the template and fill in all the possible details and the steps to reproduce? It's pretty hard from this info to retrieve what's going on.

One pointer:
Kernel `3.10.0-327.el7.x86_64` is a pretty bad in combination with Docker

**Comment by laoshancun** [comment]
**Rancher versions:**
rancher/server:v1.6.10
rancher/agent:v1.2.6

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec: rancher/net:holder
network-services:rancher/network-manager:v0.7.8
scheduler:rancher/scheduler:v0.8.2
--



kubernetes (if applicable):no

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-327.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
hyper-v
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- add a host to rancher,
- and do some regular operation(like add stack,add service,upgrade service)。
**Results:**
host is disconnected!

**Comment by superseb** [comment]
- What specs do you give the machines running the `rancher/agent` container?
- What networking do you have enabled on Hyper-V side?
- What is the complete logging from the `rancher/server` and `rancher/agent` from the moment you are about to add a host and when it's in disconnected state?

**Comment by laoshancun** [comment]
- `rancher/agent` is on the same machine with `rancher/server`.about(24core,30GB)
- hyper-v networking is external.

**Comment by superseb** [comment]
Please supply the logging when it happens from both containers.

**Comment by superseb** [comment]
Let us know if we can help on this.
