### ISSUE TITLE
Sidekicks don't cleanup after delete

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10154]
**Rancher versions:**  2.0 master 10/16

**Steps to Reproduce:**
1.  Create a service
2.  Add a sidekick
3.  Delete the sidekick

**Results:**  Sidekicks sits in stopped state with trash icon until I manually clean up the service.  It should completely remove from UI and state in API should be "Removed"

**Comment by alena1108** [comment]
@tfiduccia Deleting the sidekick is an equivalent to service.edit (upgrade). We leave the "old" containers around, so then if user decides to rollback to the older revision, the stopped sidekick (Pending-Delete in the UI) will be brought back to the service = started. And just as in case of regular edit (upgrade), the old containers can be cleaned up with service.cleanup option.


@deniseschannon it works as expected, but if this user experience is not quite obvious, we might want to document it.

**Comment by tfiduccia** [comment]
ok, so the problem isn't that the container isn't being cleaned up.  The problem is that on edit/upgrade of a service, the old container is cleaning itself up.
