### ISSUE TITLE
[rancher-compose] Support for docker-compose 2.1

### ISSUE THREAD

**Issue by rockandska** [rancher/rancher#10158]
Hi,

Is there any plan to support the whole 2.1 docker-compose options and particularly [healthcheck](https://docs.docker.com/compose/compose-file/#healthcheck) and integrate it in the UI ?

I think it is a nice feature to be able to add some check not related with tcp / http for containers who doesn't expose ports.

Best regards,

**Comment by CpuID** [comment]
https://github.com/docker/libcompose/pull/507 gets you a portion of the way to resolving this (when released using the latest libcompose). At least the `docker-compose.yml` files will parse correctly, as a start.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
