### ISSUE TITLE
Labels aren't saved when adding hosts

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10155]
**Rancher versions:** 2.0 master 10/16

**Steps to Reproduce:**
1.  Add host with a label foo=bar

**Results:**  Label is sent in POST but ignored in back-end.

**Comment by alena1108** [comment]
@deniseschannon @StrongMonkey tested by registering host with the command, works fine:

```
docker run -e CATTLE_HOST_LABELS='foo=bar&hello=world' --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v2.0-alpha4 http://10.0.2.2:8080/v3/scripts/CB37F8F1CFDB07EC6B72:1483142400000:tQxeHv0SiY7ZVPTxOe8CnYZdjQ
```

GMS issue?

**Comment by StrongMonkey** [comment]
@alena1108 yeah, i had a pr to fix this bug. It was a regression bug caused by me :).

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/15
Verified fixed
