### ISSUE TITLE
Add sidekick removes & recreates primary container

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10152]
**Rancher versions:** 2.0 master 10/16

**Steps to Reproduce:**
1.  Create a service
2.  Add a sidekick

**Results:**  Notice the primary container deletes then recreates.  We should keep the main container active and just add the sidekick?

**Comment by deniseschannon** [comment]
This is the design of how k8s handles adding containers into a pod. The primary container must be restarted.
