### ISSUE TITLE
Bad image causes service to get stuck in removing with no error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10151]
**Rancher versions:** 2.0 master 10/16

**Steps to Reproduce:**
1.  Create a service and put in a image that doesn't exist

**Results:**
The container gets stuck in removing, I never see the "bad image" error like I did in 1.6.  And because the container is stuck it's hard to get the service to delete

**Comment by StrongMonkey** [comment]
There are two issues:
1. a bad image doesn't cause container goes to error state.
2. a stuck container preventing service to be removed.
