### ISSUE TITLE
rancher/external-dns using deactivated API for DNSimple provider

### ISSUE THREAD

**Issue by camAtGitHub** [rancher/rancher#10167]
Adding a dnsimple 'stack' from the community catalog with my newly created DNSimple account, fails to deploy the stack.

The error messages is time="2017-10-18T23:29:00Z" level=fatal msg="Failed to get provider 'dnsimple': Failed to list zones: GET https://api.dnsimple.com/v1/domains: 429 Too many requests"

Researching the error leads me to this page: https://developer.dnsimple.com/v1/ which states: "DNSimple API v1 is deprecated and in maintenance-only. API v1 will be discontinued on October 1st, 2017."

I suspect new accounts are blocked from using v1 API.

Can this DNS Provider be upgraded to use version 2 of their API?

I have also tested rancher/external-dns v.0.7.6 and it fails with the same error 

**Steps to Reproduce:**
Sign up at DNSimple
Deploy https://github.com/rancher/community-catalog/tree/master/templates/dnsimple
Watch it fail to deploy.

**Results:**
Fail to deploy Stack and Container

**Comment by camAtGitHub** [comment]
Sorry not a developer but from what I can determine in:

 https://github.com/rancher/external-dns/blob/master/providers/dnsimple/dnsimple.go 

line 12: `api "github.com/weppos/go-dnsimple/dnsimple"`

weppos/go-dnsimple/dnsimple is an unmaintained fork of 'https://github.com/dnsimple/dnsimple-go' perhaps you could use the DNS Providers library instead of the fork?

**Comment by JannikZed** [comment]
Hi there, any chance, that the creators of this service take a look at it?

**Comment by thebennos** [comment]
This issue may be not solved, because rancher moves completly to kubernetes and rancher is something like an UI for Kubernetes.. External DNS services need to be completly rewritten to work with the kubernetes API's.

**Comment by JannikZed** [comment]
There is a Kubernetes Helm for external dns which also supports DNSimple, so the moment everything around Helm works 100% with rancher we might use the dns feature like this.
________________________________

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
