### ISSUE TITLE
Place managed containers at the bottom of the list of containers 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1016]
On the Containers page and the list of containers on a host, place the managed containers (i.e. Network Agent, LB Agent) at the bottom of the list of containers.

**Comment by will-chan** [comment]
I would prefer if "System" containers are placed in the detail page in another tab or like Denise said..grouped at the bottom or in a way where it's easily recognizable.

**Comment by deniseschannon** [comment]
@tfiduccia had first requested this in another bug before i closed it for @vincent99 half fix for that bug.

**Comment by vincent99** [comment]
This was indirectly done when they were reorganized into stacks first and then standalone containers.
