### ISSUE TITLE
Detelte Node Can't Delte Node's contianers

### ISSUE THREAD

**Issue by UnknowName** [rancher/rancher#10169]
In last server stable version(v1.610). When i  delete the node host. The node host's system containers(like rancher agent,rancher ipse and so on) will staill running.
I hope when the node host deleted.The system container will be clean.
Thank you.

**Comment by vincent99** [comment]
This is intentional.  Deleting a host from Rancher does not affect the containers running on it.

**Comment by UnknowName** [comment]
I  mean the containser of Rancher.Not other contaners. When the node add to the Rancner servers.The node host will  launch new containers : rancher-agent ,rancher-ipse, rancher-routers and so on. I want this container which new lauched will be deleted. Is this intentional?

**Comment by superseb** [comment]
```
NOTES:
For custom hosts, all containers including the Rancher agent will continue to remain on the host. Also, the IP set on the docker0 interface by the Rancher network driver will remain.
```
http://rancher.com/docs/rancher/v1.6/en/hosts/#removing-hosts

Does this answer your question?
