### ISSUE TITLE
Single host internal network suddenly becomes disconnected

### ISSUE THREAD

**Issue by asciiman** [rancher/rancher#10172]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 23
 Running: 22
 Paused: 0
 Stopped: 1
Images: 32
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 224
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-58-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.16 GiB
Name: db-1
ID: WM6W:RH7N:3UHE:GVKG:KNG7:FRPM:YMAX:VKE4:Q4TI:5RA2:25B3:AYIT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu
4.8.0-58-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
3 different environments, between 3-8 host machines per environment

**Results:**
Suddenly a host will become disconnected from the rancher internal network.  I can ping inside the same machine.  I can ping out to the internet.  But I can't ping other hosts from inside that host.  Other hosts can ping services inside each other, but not ping services inside of that host.  It's happening to a random host every 1-2 days.  It happens on different environments.

```
time="2017-10-19T03:41:12Z" level=warning msg="Hit websocket pong timeout. Last websocket ping received at 2017-10-19 03:40:57.665948396 +0000 UTC. Closing connection." 
time="2017-10-19T03:41:12Z" level=error msg="Received error reading from socket. Exiting." error="read tcp x.x.x.x:60036->y.y.y.y:443: use of closed network connection" 
time="2017-10-19T03:41:12Z" level=error msg="Failed to connect to websocket proxy: %vread tcp x.x.x.x:60036->y.y.y.y:443: use of closed network connection" 
time="2017-10-19T03:41:19Z" level=error msg="Error processing event &events.Message{Status:\"die\", ID:\"b3b106b02868d466dba5767846ab554558e5e12176f8d02da17748d48b406e69\", From:\"rancher/scheduler:v0.8.2\", Type:\"container\", Action:\"die\", Actor:events.Actor{ID:\"b3b106b02868d466dba5767846ab554558e5e12176f8d02da17748d48b406e69\", Attributes:map[string]string{\"image\":\"rancher/scheduler:v0.8.2\", \"io.rancher.container.mac_address\":\"02:c6:26:18:5d:73\", \"io.rancher.container.uuid\":\"5433fbb8-dbbc-479d-a649-3ae5439af891\", \"io.rancher.environment.uuid\":\"3eaf60dc-e00d-4ad7-a135-a8af3afe7841\", \"io.rancher.stack.name\":\"scheduler\", \"io.rancher.stack_service.name\":\"scheduler/scheduler\", \"io.rancher.cni.wait\":\"true\", \"io.rancher.container.agent_service.scheduling\":\"true\", \"io.rancher.container.create_agent\":\"true\", \"io.rancher.container.ip\":\"10.42.166.167/16\", \"io.rancher.container.system\":\"true\", \"io.rancher.service.launch.config\":\"io.rancher.service.primary.launch.config\", \"exitCode\":\"0\", \"io.rancher.cni.network\":\"ipsec\", \"io.rancher.container.name\":\"scheduler-scheduler-1\", \"io.rancher.project.name\":\"scheduler\", \"io.rancher.service.deployment.unit\":\"a9434bff-c73a-405c-8c66-eb0f9b2c16be\", \"io.rancher.container.agent_id\":\"396\", \"io.rancher.project_service.name\":\"scheduler/scheduler\", \"io.rancher.service.hash\":\"ed6a3f7d68f4dde633fb9fe6e844e637215435d4\", \"name\":\"r-scheduler-scheduler-1-5433fbb8\"}}, Time:1508384469, TimeNano:1508384469139165620}. Error: Post https://rancher.zzz.com/v1/containerevents: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-19T03:41:27Z" level=error msg="Failed to get rancher client for host-api startup: Get https://rancher.zzz.com/v1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-19T03:41:42Z" level=error msg="Failed to get rancher client for host-api startup: Get https://rancher.zzz.com/v1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-19T03:41:57Z" level=error msg="Failed to get rancher client for host-api startup: Get https://rancher.zzz.com/v1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-19T03:42:02Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-10-19 03:40:57.593272429 +0000 UTC. Closing connection." 
INFO: Starting agent for 29ACEACBE6C1242665AE
INFO: Starting agent for 29ACEACBE6C1242665AE
INFO: Starting agent for 29ACEACBE6C1242665AE
INFO: Starting agent for 29ACEACBE6C1242665AE
INFO: Access Key: 29ACEACBE6C1242665AE
INFO: Config URL: https://rancher.zzz.com/v1
INFO: Storage URL: https://rancher.zzz.com/v1
INFO: API URL: https://rancher.zzz.com/v1
INFO: IP: x.x.x.x
INFO: Port:
INFO: Required Image: rancher/agent:v1.2.6
INFO: Current Image: rancher/agent:v1.2.6
INFO: Using image rancher/agent:v1.2.6
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
INFO: Downloading agent https://rancher.zzz.com/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading https://rancher.zzz.com/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading https://rancher.zzz.com/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67/apply.sh
INFO: Updating host-api
INFO: Downloading https://rancher.zzz.com/v1//configcontent//host-api current=1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Already up to date
INFO: Sending host-api applied 1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Updating python-agent
INFO: Downloading https://rancher.zzz.com/v1//configcontent//python-agent current=1-006597b7de613bf359a79e8eec7b7c3b114e6f49584aa04993d3163f3fab9f37
INFO: Already up to date
INFO: Sending python-agent applied 1-006597b7de613bf359a79e8eec7b7c3b114e6f49584aa04993d3163f3fab9f37
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/agent
INFO: Updating host-config
INFO: Downloading https://rancher.zzz.com/v1//configcontent//host-config current=host-config-1-5b8d58878ed11fbf976b700d9cdecdfadfacbb901812d2758e139ff6f46ba6e5
INFO: Already up to date
INFO: Sending host-config applied 1-5b8d58878ed11fbf976b700d9cdecdfadfacbb901812d2758e139ff6f46ba6e5
time="2017-10-19T03:50:01Z" level=info msg="Launching agent" 
time="2017-10-19T03:50:01Z" level=info msg="Listening for events on https://rancher.zzz.com/v1" 
time="2017-10-19T03:50:01Z" level=info msg="launching hostapi" 
time="2017-10-19T03:50:01Z" level=info msg="Serialize compute requests: false, driver: aufs" 
time="2017-10-19T03:50:01Z" level=info msg="Initializing event router" workerCount=250 
time="2017-10-19T03:50:01Z" level=info msg="Starting event router." 
time="2017-10-19T03:50:01Z" level=info msg="Connection established" 
time="2017-10-19T03:50:01Z" level=info msg="Starting websocket pings" 
time="2017-10-19T03:50:01Z" level=info msg="Connecting to proxy." url="wss://rancher.zzz.com/v1/connectbackend?token=zzz" 
time="2017-10-19T03:50:10Z" level=info msg="Received event: Name: storage.image.activate, Event Id: 95048d17-2ffd-4957-ae26-2ca0f66ed8cf, Resource Id: 1ispm2712" 
time="2017-10-19T03:50:10Z" level=info msg="Reply: 95048d17-2ffd-4957-ae26-2ca0f66ed8cf, storage.image.activate, 1ispm2712:imageStoragePoolMap" 
time="2017-10-19T03:50:10Z" level=info msg="Received event: Name: storage.volume.activate, Event Id: 3c0c66ab-e5de-4211-b565-b42506be36cb, Resource Id: 1vspm3505" 
time="2017-10-19T03:50:10Z" level=info msg="Reply: 3c0c66ab-e5de-4211-b565-b42506be36cb, storage.volume.activate, 1vspm3505:volumeStoragePoolMap" 
time="2017-10-19T03:50:11Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: c0f15d50-fd75-43c3-b566-90c719b75b34, Resource Id: 1ihm2716" 
time="2017-10-19T03:50:11Z" level=info msg="rancher id [2848]: Container with docker id [8256bd105752a32fce4106264a3d087b439bbd37e6e20a7adae4149198a86734] has been started" 
time="2017-10-19T03:50:11Z" level=info msg="Reply: c0f15d50-fd75-43c3-b566-90c719b75b34, compute.instance.activate, 1ihm2716:instanceHostMap" 
time="2017-10-19T03:50:13Z" level=info msg="Received event: Name: compute.instance.inspect, Event Id: 76ed316f-f277-488f-bf45-58ba4640a6e4, Resource Id: " 
time="2017-10-19T03:50:13Z" level=info msg="rancher id []: Container with docker id [b3b106b02868d466dba5767846ab554558e5e12176f8d02da17748d48b406e69] has been inspected" 
time="2017-10-19T03:50:13Z" level=info msg="Reply: 76ed316f-f277-488f-bf45-58ba4640a6e4, compute.instance.inspect, :instanceInspect" 
time="2017-10-19T03:50:21Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: ce453e25-e3d2-4c11-a49b-0270ae15c7aa, Resource Id: 1vspm820" 
time="2017-10-19T03:50:21Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: 4121ba4c-1207-4a85-bcc5-89b615e5d56a, Resource Id: 1vspm3445" 
time="2017-10-19T03:50:21Z" level=info msg="rancher id [1vspm3445]: Volume with name [] has been removed" 
time="2017-10-19T03:50:21Z" level=info msg="Reply: 4121ba4c-1207-4a85-bcc5-89b615e5d56a, storage.volume.remove, 1vspm3445:volumeStoragePoolMap" 
time="2017-10-19T03:50:21Z" level=info msg="rancher id [1vspm820]: Volume with name [] has been removed" 
time="2017-10-19T03:50:21Z" level=info msg="Reply: ce453e25-e3d2-4c11-a49b-0270ae15c7aa, storage.volume.remove, 1vspm820:volumeStoragePoolMap" 
time="2017-10-19T03:50:22Z" level=info msg="Received event: Name: storage.volume.activate, Event Id: dc8f2060-0944-4e9a-bd64-bc4e10484266, Resource Id: 1vspm3506" 
time="2017-10-19T03:50:22Z" level=info msg="Reply: dc8f2060-0944-4e9a-bd64-bc4e10484266, storage.volume.activate, 1vspm3506:volumeStoragePoolMap" 
time="2017-10-19T03:50:22Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 6c36db9d-ee57-486b-9fbd-7dd8bbdd803e, Resource Id: 1ihm2717" 
time="2017-10-19T03:50:22Z" level=info msg="Reply: 6c36db9d-ee57-486b-9fbd-7dd8bbdd803e, compute.instance.activate, 1ihm2717:instanceHostMap" 
time="2017-10-19T03:50:31Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: 8acaf16f-78c0-42f6-99c7-473ac8f25211, Resource Id: 1vspm3506" 
time="2017-10-19T03:50:31Z" level=info msg="rancher id [1vspm3506]: Volume with name [] has been removed" 
time="2017-10-19T03:50:31Z" level=info msg="Reply: 8acaf16f-78c0-42f6-99c7-473ac8f25211, storage.volume.remove, 1vspm3506:volumeStoragePoolMap" 
time="2017-10-19T03:50:36Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: c9c84a71-93fe-4590-860e-7665cfde8aac, Resource Id: 1vspm3495" 
time="2017-10-19T03:50:36Z" level=info msg="rancher id [1vspm3495]: Volume with name [] has been removed" 
time="2017-10-19T03:50:36Z" level=info msg="Reply: c9c84a71-93fe-4590-860e-7665cfde8aac, storage.volume.remove, 1vspm3495:volumeStoragePoolMap" 
```

**Comment by superseb** [comment]
Are you saying you also have network connectivity issues on the host itself? How are the specs and how is the health of the system (load/mem/swap/disk)

Also, `ifconfig` output could be handy here.

Is there anything in front of the `rancher/server`?

**Comment by asciiman** [comment]
The host is in good shape load/mem/swap/disk -wise.  The host has network connectivity out to the internet just fine.  I haven't tried pinging internal rancher services from the host.  I fixed the issues already and the machines are working.  If it happens again I can try the other ping and do an `ifconfig`.

We have cloudflare orange cloud in front of the rancher/server machine.  It looks like cloudflare recycles socket connections every once in a while.  I'm wondering if rancher has a hard time re-establishing the connection when the socket drops sometimes?  It's worked fine in the past on earlier versions of rancher.  The issue seemed to start recently.

**Comment by superseb** [comment]
Ok, if you could collect those and report back, that would be great. Earlier versions are all before v1.6.10?

Also, if you can't ping other hosts from a host, that's not really related to something in front of `rancher/server`. The errors in the log could be however.

**Comment by asciiman** [comment]
Another host went down today in the way I described above.  I did some research and found that the host that disconnected could ping other host machines fine.  But if I tried from the down host machine to ping the ip address of a container on another host that would fail.

**Comment by superseb** [comment]
Please supply logs from `rancher/server` and affected `rancher/agent` so we can investigate, pretty hard to say anything about this.

**Comment by ValentinOdier** [comment]
Hi, 

I think i have the same issue : 

**host setup :** 
Containers: 19
 Running: 16
 Paused: 0
 Stopped: 3
Images: 19
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 208
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.674 GiB
Name: sat-aws-14
ID: BVMH:NNAB:CNBF:GBCZ:BYLJ:AIYU:RP2B:KX4G:CPCH:RDM3:CE4Z:JFB4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8

**Rancher** : 1.6.10  (cattle)

container rancher running on the given host : 

- rancher/healthcheck:v0.3.3
- rancher/net:v0.11.9
- rancher/dns:v0.15.3
- rancher/net:holder
- rancher/network-manager:v0.7.8
- rancher/net:v0.11.9
- rancher/metadata:v0.9.4
- rancher/agent:v1.2.6 

What i can tell :

From times to times containers on host A or the host A cannot ping a container on host B
It will not work until i restart IPSEC. Then (whithout doing anything else) everything goes back to normal.
The host is not disconnected or anything, it just looks like part of the network was lost. Usually it does not affect the entire network meaning maybe A cannot reach a container on host B but can reach a container on host C.

We had this issue multiple times and restarting rancher infrastructure containers seems to fix the issue. However it might come back latter on.

Attaching logs for IPSEC as well as the agent and rancher. (before restarting to fix the issue)
We have nothing in front of rancher no proxy nothing.

Please let me know if the format is wrong or if you need anything else.

[agent.log](https://github.com/rancher/rancher/files/1539681/agent.log)
[ipsec.log](https://github.com/rancher/rancher/files/1539682/ipsec.log)
[rancher.log](https://github.com/rancher/rancher/files/1539683/rancher.log)

**Comment by superseb** [comment]
There have been quite some improvements on ipsec regarding dropping connections. Please try v1.6.14.

@asciiman If you are still experiencing issues, let me know so we can investigate.

**Comment by ValentinOdier** [comment]
Fixed by upgrading to rancher/server:stable and updating internal services 

Thanks
