### ISSUE TITLE
description field for Cluster/Environments not shown anywhere.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10179]
**Rancher versions:** 2.0 master 10/19

**Steps to Reproduce:**
1.  Create a cluster and an environment and add a description to them

**Results:**  Notice there is nowhere in the UI that shows the description?

**Comment by loganhz** [comment]
added the description in cluster dashboard page

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/16
Verified fixed
