### ISSUE TITLE
Need GPU support for deep learning application

### ISSUE THREAD

**Issue by suleisl2000** [rancher/rancher#10184]
**Rancher versions: 1.6.x
rancher/server:

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Problem Description:**
I come from an autonomous driving company and we are running a lot of deep learning workload including training and inference on GPU boxes every day. Currently, we are trying to migrate our applications into Rancher (with cattle). Unfortunately, we found Rancher don't support GPU scheduling at all. It extremely blocked our migrating progress.

Deep learning has two kind of workload types, training and inference. In our company, we have both. Generally speaking, the former one can consume all resource on one GPU card while the other one has lower GPU utilization. We generally let a training job use entire GPU card for training job exclusively. But for inference job, we expect multiple inference jobs share a GPU card. In addition, training job often consume more than one GPU card on multi-GPU box for parallelization. So, if we run the training job in a container, we have to allocate more than one GPU one same host for the container.

We'd like Rancher to provide a GPU reservation attribute (say gpu_reservation) like mem_reservation at least or something like this. The attribute can be passed to scheduler so that we can implement our own scheduling logic. Moreover, it is great if Rancher can support more for fine-grained GPU scheduling like different GPU mode (default vs exclusive). I believe the requirement is non-trivial due to hot AI industry at present.

**Comment by MihaiAnei** [comment]
@suleisl2000 Let's say that the "industry" of container scheduling is, generally, moving towards Kubernetes or flavors of it. As you can see [here](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview/7405) Rancher is doing this as well. The reason would be that Kubernetes is, in my opinion, doing the best job at managing infrastructure based on containers. For this reason, I think that Cattle will be deprecated in the near future (I really don't know for sure, someone from the team might bring more light onto this topic).

I advise you to take a look at this: [KubernetesGPUSupport](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/) and maybe continue researching what plans are in place for a better GPU scheduling support in Kubernetes.

Hope it helps. Cheers!

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
