### ISSUE TITLE
Allow description when stack is created from CLI using rancher up

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#10192]
**Rancher versions:** 1.6.10

Add ability to take description value when stack is created from CLI using rancher up.  Customers use description field for entering semantic versioning info (like, v.1.2.2).  Ideally, they would like to enter this as part of stack name.  But we do not allow it as it conflicts with our internal DNS service.  So customer has to create stack from CLI and then go to UI to add version info under description

**Comment by deniseschannon** [comment]
Available with v1.6.6-rc1

**Comment by StrongMonkey** [comment]
should be cli v0.6.6-rc1 :)

**Comment by soumyalj** [comment]
Tested with CLI version v0.6.6-rc1 using rancher v1.6.12. Created a stack by adding description as below:
```
rancher-v0.6.6-rc1 soumya$ ./rancher up -d --stack descriptiontest --description clitesting --file basicservice.yml
INFO[0000] Creating stack descriptiontest               
INFO[0001] [service2]: Creating                         
INFO[0001] Creating service service2                    
INFO[0001] [service2]: Created                          
INFO[0001] [service2]: Starting                         
1s70
INFO[0013] [service2]: Started                    

```
Stack was created with a description
<img width="962" alt="screen shot 2017-12-01 at 4 00 12 pm" src="https://user-images.githubusercontent.com/18536626/33508964-90dbfecc-d6b2-11e7-90e0-46426a52f33d.png">
