### ISSUE TITLE
Changing cluster id of an existing Environment through API, removes all stacks/services/containers 

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rancher#10194]
**Rancher versions:**
rancher/server: master

**Steps to Reproduce:**
Create two clusters
Create an environment in one
Add stack/services/containers
Edit cluster id for environment through the API to the other cluster

**Results:**
View the environment now in the second cluster, all stacks/services/containers are gone

**Comment by vincent99** [comment]
That...shouldn't be editable...
