### ISSUE TITLE
[rancher v2] Upgrade service 

### ISSUE THREAD

**Issue by tcheronneau** [rancher/rancher#10201]
**Rancher versions:**
rancher/server: v2.0.0-alpha9
rancher/agent: v2.0-alpha4

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.12.3
network-services: v0.8.6
scheduler: v1.7.6-netes2-1
kubernetes (if applicable): v1.7.6-netes2-1

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.03 LTS Xenial
4.4.0-97-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Launch a service. 
Create a new version of the image. 
Go on Rancher UI and use "upgrade" button
**Results:**
When you use Rancher UI to upgrade a service it is not running a new container. 
You see that you container has not change. It should destroy and run a new one like in rancher v.1.6 (I think because it's not an upgrade else). 

Thanks,
Thomas.

**Comment by deniseschannon** [comment]
As of the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!

**Comment by sannysoft** [comment]
I am having the same issue with rancher 2.0.2. Is there anything I'm doing wrong? I click workload->Edit->Upgrade. Should it download new image from docker hub and launch new instance?

**Comment by Joshua-JD-Lee** [comment]
I am having the same issue with rancher 2.0.8. Any updated about this issue?
