### ISSUE TITLE
Intermittent 503 Service Unavailable when using host based ingress with Rancher ingress controller

### ISSUE THREAD

**Issue by parmarnandish** [rancher/rancher#10206]
**Rancher versions:**
rancher/server:v1.6.7
rancher/agent:v0.6.6

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:rancher/net:v0.11.7
network-services:rancher/network-manager:v0.7.7, rancher/metadata:v0.9.3
scheduler:rancher/k8s:v1.7.7-rancher1
kubernetes (if applicable):rancher/k8s:v1.7.7-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux 7 (Core), 3.10.0-693.2.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher with external mysql DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Deploy any service inside kubernetes cluster
2. Create an ingress using host path and use annotation: io.rancher.scheduler.global: "true" . This also creates an rancher ingress lb in the Rancher UI. 
3. Browse the host path in any browser, and intermittently instead of loading the kubernetes service, we get 503 Service Unavailable - No server is available to handle this request. 
4. If you refresh the browser multiple times (between 3 to 12 times), the service will load. 
5. This happens will all the ingress that I create in the cluster
**Results:**
Expected result is to not have 503 Service unavailable error and load the service everytime you browse for that hostname.

**Comment by parmarnandish** [comment]
I have recently updated rancher server to v1.6.10, but I am still getting this error.

**Comment by sn00p** [comment]
They spawn new haproxy instance for every new ingress resource. It is totally killing all the idea of ingress. It have to be one  haproxy instance with virtualhosts inside. Every new ingress resource added should just update this haproxy instance without adding new one.  
Rancher v1.6.14 still spawns new haproxy instance on every ingress resource added. It leads to port conflicts and 503 all the way.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
