### ISSUE TITLE
Stacks with same name, after a rename, merge services in UI link selection

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#10208]
**Rancher versions:** 1.6

Two problems:
1. `Add Stack` forces uniqueness constraint from UI while `Edit` does not

<img width="939" alt="screenshot 2017-10-20 16 30 05" src="https://user-images.githubusercontent.com/11086008/31970034-96816ac4-b8cb-11e7-802b-540aadbbc3e6.png">

2. `foo.bar` is the name of Stack A.  When I edit Stack B and change its name to`foo.bar`, UI displays services across Stack A and Stack B under one grouping `foo.bar`, in some selection dropdowns, making it feel like the services belong to a single stack.

<img width="962" alt="screenshot 2017-10-24 14 57 28" src="https://user-images.githubusercontent.com/11086008/31970071-af1438e6-b8cb-11e7-8dde-3930f1ed4664.png">

<img width="1213" alt="screenshot 2017-10-24 14 47 46" src="https://user-images.githubusercontent.com/11086008/31970107-cc00a71e-b8cb-11e7-9be9-50396b83483a.png">

Notice from the above screenshots, dokuwiki-server and MyTopService are shown under a single stack

**Comment by alena1108** [comment]
@kinarashah we need to fix edit, do not allow renaming to something that already exists. Code needs to be done in StackValidationFilter

**Comment by jambajaar** [comment]
@alena1108 @kinarashah 

I reckon the fix will ensure uniqueness in stack name in the edit scenario.

But if there are existing duplicates out there then the resolution for the user is to simply rename such stack name(s) to a unique name to address the dropdown issue?

**Comment by kinarashah** [comment]
@jambajaar yes, the dropdown issue gets solved with the fix. 

For test, I renamed test to test2 - 

<img width="781" alt="screen shot 2017-10-26 at 8 36 53 pm" src="https://user-images.githubusercontent.com/16870565/32086975-8ecd7f16-ba8d-11e7-94aa-c18449aa2d8e.png">

**Comment by vincent99** [comment]
The UI groups the options by name because it is what is displayed and it's supposed to be unique.  If there is a case where it's actually ambiguous what service you're choosing, you have far bigger real problems like overlapping DNS entries, ambiguous access by name in metadata or the `/r` proxy, etc.

**Comment by kinarashah** [comment]
Not sure how/where can I make additional change for existing duplicates?

**Comment by vincent99** [comment]
@kinarashah You can't (and don't need to)

**Comment by sangeethah** [comment]
Tested with latest build from v1.6 branch.
Not allowed to edit stack name to a name that is already associated with existing stack in the same environment. User is presented with - ```Validation failed in API: name is not unique```.

**Comment by jambajaar** [comment]
Looks like this fix is available in 1.6.11
