### ISSUE TITLE
Generate service dependency graph based on depends_on

### ISSUE THREAD

**Issue by fsword** [rancher/rancher#10212]
**Rancher versions:**
rancher/server: all
rancher/agent: all

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Add a stack with multi services, use `depends_on` to setup the dependency between them.

**Results:**
In the Rancher UI, it doesn't show the dependency graph based on `depends_on`. Can we add a feature to generate dependency graph based on `depends_on` ?

**Comment by loganhz** [comment]
@fsword please use English to submit an issue next time. thanks
