### ISSUE TITLE
update aws-sdk-go to the latest version

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10221]
Ticket to track work item for updating the aws-sdk-go library used in external-dns.

**Comment by aemneina** [comment]
needs to include this pr [#96](https://github.com/rancher/external-dns/pull/96) to make max retries configurable

**Comment by deniseschannon** [comment]
Available with `rancher/external-dns:v0.7.7` in the v1.6-development catalog branch.

**Comment by sangeethah** [comment]
Rancher-server - Built from v1.6
rancher/external-dns:v0.7.7

Have Route53 catalog installed. When installing Route53 stack , user is now given the option to configure "Maximum number of retries for rate-limited API calls" which is defaulted to 3.
Create a stack with 100 services having exposed port.

Create another environment.
Create a stack with 100 services having exposed port.
Have Route53 catalog installed.

Activate/Deactivate stacks from both environments which would result in Route53 DNS entries being reprogrammed.

I was not able to see the "Rate Limit Exceeded" issue which prevents records from being updated.

When I upgrade Route53 stack and set the retry count to "1" , then I see  "Rate Limit Exceeded" issue  show up in the logs.

There is  1 issue seen when testing the above scenario which is tracked in https://github.com/rancher/rancher/issues/10253
