### ISSUE TITLE
"Test and Save" button never gets activated even after all the fields are entered in "Edit Active Directory" page since test login field is empty.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10227]
**Rancher versions: Build from v1.6 branch
**Steps to Reproduce:**
Enabled AD auth. 
While enabling auth set the "Name Field" for User and Group to "NAME" (instead of the the default value name) and "Login Field" to "SAMAccountName".
Go to "Edit Active Directory" page and enter new information.
"Test and Save" button never gets activated even after all the required fields are entered in "Edit Active Directory" page since test login field is empty.

**Comment by sangeethah** [comment]
The other issues seen in this setup:
 
User name/ Group name not shown in "Edit Environment" page.
User name not shown in "Accounts" page.
Login Name not showing up when account's avtar is highlighted.

**Comment by deniseschannon** [comment]
Available on master with rancher-auth-service v0.4.23

**Comment by sangeethah** [comment]
Tested with rancher-server build from v1.6 branch.
Enabled AD auth.
While enabling auth set the "Name Field" for User and Group to "NAME" (instead of the the default value name) and "Login Field" to "SAMAccountName".

All the issues mentioned in the bug are not reproducible anymore and account name appears in the UI as expected.
