### ISSUE TITLE
About user first login automatically create user environment.

### ISSUE THREAD

**Issue by jinghuaz** [rancher/rancher#10229]
**Rancher versions:**
rancher/server:1.6.10
rancher/agent:1.2.6

Integrate Microsoft Active Directory
When you log in, you create a default environment automatically？
Can you cancel the environment that does not automatically create a user when each user logs in?

**Comment by vincent99** [comment]
Go to `http://your-rancher:8080/v2-beta/settings/project.create.default`, click Edit, change the value to false, Show Request, Send Request.

**Comment by jinghuaz** [comment]
@vincent99   good! Referring to your method, i have set it up successfully. thanks a lot.
