### ISSUE TITLE
Authentication fails for Active Directory users added after an user which is disabled

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10224]
**Rancher versions:**
rancher/server: v1.6.10

**Steps to Reproduce:**
1. Configure Access Control for Active Directory
1.  Create three accounts - testuser1, testuser2 & testuser3
2.  Add all three users to the environment with `restricted` role
3.  Disable testuser2 in AD
4.  try to log in as testuser3
 
**Results:**
`Error communicating with the authentication provider`

Logging
```            
[31mERRO [0m[2017-10-20T13:09:56Z] GetToken failed with error: Permission denied 
2017-10-20 13:09:56,787 ERROR [:] [] [] [] [tp1020391880-60] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500, message: Permission denied
```

**Comment by pasikarkkainen** [comment]
Hmm, I wonder if this is still broken in rancher v1.6.11 ?

**Comment by soumyalj** [comment]
Tested with master setup with AD enabled. Added testuser1, testuser2, testuser3.
After testuser2 was disabled, login with testuser3 was successful. Added one more user testuser4 and logged in with testuser4. No issues found.
