### ISSUE TITLE
The popup of Rancher UI doesn't show in the screen top

### ISSUE THREAD

**Issue by Maxwell1987** [rancher/rancher#10237]
**Rancher versions:**
rancher/server: all

The popup/modal shows in the top of UI but not the top of screen.
If we have a lot of stacks, we need to scroll up to click the confirm button.
it will be very great if it shows on the top of browser.

**Comment by loganhz** [comment]
@Maxwell1987 please use English to submit issue next time. thanks

**Comment by tfiduccia** [comment]
Version - v1.6.11-rc7
Verified Fixed
