### ISSUE TITLE
Azure machine driver randomly working after docker run rancher/server

### ISSUE THREAD

**Issue by alcaneo** [rancher/rancher#10239]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: N/A

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
redhat:enterprise_linux:7.3:GA:server
3.10.0-514.28.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
```
echo -e 'Prepare SE Linux for rancher'
yum -y install selinux-policy-devel
make -f /usr/share/selinux/devel/Makefile
semodule -i virtpatch.pp
semodule -l

echo -e 'Install Docker'
curl https://releases.rancher.com/install-docker/17.06.sh | sh

echo -e 'Run Rancher Server'
docker run -d --restart=unless-stopped -p 8080:8080 rancher/server
```

**Results:**
Azure machine driver is up & running once out of 3-4 attempts.
From the machine driver list page, it is running, but on the "Add host" page, it is not available.

**Note:**
I automate the deployment of Rancher with Terraform on azure. But it does not come from Terraform scripts as I reproduce manually.

I then need to automatically launch the first agent using rancher REST API.

I tried to always call API to "reactivate" before using it, but without 100% success (sometimes it works, sometimes it doesn't).
Tried to deactivate then reactivate, still the same not 100% success rate.

Each time I wait for "state":"active" before my host creation.

When it doesn't work I get:
`{"id":"0d0ac71d-72d3-4774-8a33-f05a8a9f4778","type":"error","links":{},"actions":{},"status":405,"code":"Method not allowed","message":"Method not allowed","detail":null,"baseType":"error"}`

The problem doesn't come from my API call for host creation because it works each time I manually go to activate Azure machine driver using the UI.

Thanks for your help.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
