### ISSUE TITLE
UI: Ability to add drain timeout during service creation and upgrade

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#10235]
**Rancher versions:**
rancher/server: 1.6.11

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

With the 1.6.11, we will be supporting haproxy drain feature. To enable drain, parameter 'drain_timeout_ms' can be added in the service launch_config via rancher_compose. 

Parameter details:
name: drainTimeoutMs (time in milliseconds to drain a service's containers) 
[Field in rancher_compose is drain_timeout_ms]
Type: integer

Following are the UI changes needed:
1) We need the abillity to add this parameter while creating a Service via UI. 
2) Also Upgrading a service should let user change the value of this parameter.
3) Note that this parameter can only be added for a Primary Service - so we don't need to provide this ability for sidekick services.

**Comment by loganhz** [comment]
hi @prachidamle @vincent99 , where should we put the field in the UI when creating or updating a service?

**Comment by vincent99** [comment]
It's both a property of the `service` resource and the `upgrade` action?  That's weird since none of the other upgrade options are like that (in 1.x).

For upgrade the obvious place is:

![image](https://user-images.githubusercontent.com/753917/32149381-c5e0f372-bcc0-11e7-90b1-1b78f6ba77c1.png)

For create I guess underneath Command -> Auto Restart... there's really not a great place since none of the other options for stop signal, stop timeout, batch size, batch interval, start first, etc are part of the service definition in 1.x.

![image](https://user-images.githubusercontent.com/753917/32149407-33e5a336-bcc1-11e7-9b9d-07e23c13ba11.png)

**Comment by loganhz** [comment]
add this parameter while creating a Service
![image](https://user-images.githubusercontent.com/21168270/32154337-fcd53a04-bcfd-11e7-87c3-1db17a907d37.png)

update this parameter while upgrading a Service
![image](https://user-images.githubusercontent.com/21168270/32154342-0a71846a-bcfe-11e7-80a9-cc5d40e68822.png)

this parameter doesn't show in a Sidekick service
![image](https://user-images.githubusercontent.com/21168270/32154387-6682a356-bcfe-11e7-8ec1-f102d4b694d0.png)

**Comment by prachidamle** [comment]
@vincent99 this parameter is part of launch_config of a service. So to add a value to it, it has to be on service creation page, since default is zero for this.

Also if user wants to change the value on a service, since the value belongs to service's launch_config, upgrade service is the action that will allow user to go change its value - I guess an edit service wont be applicable here?

**Comment by sangeethah** [comment]
@loganhz , @prachidamle , we can continue to have the "Darin Timeout" under command tab for service during upgrade workflow as well. Why should it be part of upgrade options ?

**Comment by vincent99** [comment]
I misunderstood and thought there was an upgrade action field too; if it's just an editable part of the service then it can just be in the one place in @loganhz 's first screenshot for new or edit.

**Comment by sangeethah** [comment]
@vincent99 , there is no support for this field in standalone containers. Will introducing this field for service also result in this field being made available in standalone container create page ?

**Comment by loganhz** [comment]
@sangeethah no, it will not show in standalone container page.

**Comment by deniseschannon** [comment]
Available with v1.6.11-rc6

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.11-rc6

Able to set drain timeout during service creation and upgrade . This option is available under "command" tab.

This option is not presented for sidekicks and for standalone containers.
