### ISSUE TITLE
Kubernetes dashboard fails to launch after changing the log level of Kubernetes Add-ons

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10236]
**Rancher versions:**
rancher/server: v1.6-development

**Docker version: (`docker version`,`docker info` preferred)**v1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Create a 3 node Kubernetes setup
2. Perform Kubernetes upgrade and change the log level of Kubernetes add-ons from 2 to 10 or from 2 to 5 and then to 10
3. The dashboard fails to launch after the upgrade
```
soumyas-MBP:~ soumya$ kubectl get pod --namespace kube-system
NAME                                   READY     STATUS             RESTARTS   AGE
heapster-85f47587f9-ldtx4              1/1       Running            0          29m
kube-dns-66d7576cbd-plvc5              3/3       Running            0          30m
kubernetes-dashboard-96d74575c-fb2bf   0/1       CrashLoopBackOff   6          9m
monitoring-grafana-997796fcf-g8w9v     1/1       Running            0          4h
monitoring-influxdb-56fdcd96b-x5ql5    1/1       Running            0          4h
tiller-deploy-6dc4b49488-kxdxg         1/1       Running            0          30m



```

```
soumyas-MBP:~ soumya$kubectl -n kube-system logs kubernetes-dashboard-96d74575c-fb2bf
Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Using service account token for csrf signing
No request provided. Skipping authorization header
I1027 23:23:53.592066       1 round_trippers.go:383] GET https://10.43.0.1:443/version
log: exiting because of error: log: cannot create log: open /tmp/dashboard.kubernetes-dashboard-96d74575c-fb2bf.unknownuser.log.INFO.20171027-232353.1: no such file or directory
```
It was also observed that changing the level from 10 to 2 fixed the issue.

**Comment by moelsayed** [comment]
Dashboard is trying to write logs to /tmp, while the image doesn't have a /tmp directory. Will set it to use --logtostderr instead.

**Comment by soumyalj** [comment]
Tested using rancher v1.6.11-rc6 with Kubernetes v1.8.2-rancher2-etcdv3. Steps below:
1. Create a 3 node Kubernetes setup
2. Perform Kubernetes upgrade and change the log level of Kubernetes add-ons from 2 to 10 or from 2 to 5 and then to 10
Dashboard launched successfully after log level change.
