### ISSUE TITLE
API got modified

### ISSUE THREAD

**Issue by atheoscommune** [rancher/rancher#10231]
**Rancher versions:**
rancher/server:v2.0.0-alpha10
rancher/agent:

**Steps to Reproduce:**
Try accessing /v3/token or v2/token or v1/token

**Results:**
`userIdentity` missing in data.
![image](https://user-images.githubusercontent.com/15967659/32088761-73701438-bb03-11e7-8aae-f18499da1b65.png)

**Possible source of Cause**
``
Class<?> io.cattle.platform.iaas.api.auth.dynamic.DynamicSchemaFactory.getSchemaClass(String type)
``
returns a `SchemaImpl` devoid of `resourceFields#userIdentity`

**Comment by vincent99** [comment]
There is explicitly no access control and therefore no identities supported in the current preview.

**Comment by atheoscommune** [comment]
Thanks @vincent99 . Wondering if it is possible to allow access control in cattle by tweaking some clases. Let me know if possible.
