### ISSUE TITLE
403 fetching Custom UI component from GitHub release

### ISSUE THREAD

**Issue by ajmadsen** [rancher/rancher#10230]
**Rancher versions:**
rancher/server: v1.6.10

**Steps to Reproduce:**
1. Add a custom machine driver
2. Add a custom UI URL from a GitHub release (e.g., https://github.com/ajmadsen/ui-driver-linode/releases/download/v0.1-alpha/component.js)
3. Attempt to add a new host

**Results:**
Receive a UI failure when trying to load the custom UI. The proxy returns a 403 trying to fetch `component.js`.

As far as I can tell this is because Cattle's `GenericWhitelistedProxy` explicitly sets a `Host` header on all proxied requests. When fetching a release from GitHub, the proxy receives a redirect to S3 with a pre-signed URL. When the proxy follows the redirect, it resends the explicitly set `Host` header (in this case `Host: github.com`) in the request it sends to S3, it receives a 403 with the `SignatureDoesNotMatch` error, because the `Host` header sent with the request does not match what was pre-signed (`Host` being some S3 address).

**Comment by vincent99** [comment]
While this may be true, it won't work regardless.  Github is not meant to be used as a CDN, and they send `Content-Disposition: attachment; filename=component.js` and `Content-Type: application/octet-stream` so the file will be downloaded instead of executed.
