### ISSUE TITLE
Multiple projects per host?

### ISSUE THREAD

**Issue by jonpugh** [rancher/rancher#1023]
I'm probably not thinking this through all the way, but it would be awesome if multiple projects could use the same host.

I've noticed #583, about moving hosts between projects.

Are there major technical blockers to being able to do this?

Thanks!

**Comment by vincent99** [comment]
Yes.. for example we have 'native docker integration', where you can use the CLI on the host and we'll reflect those changes.  So if you did `docker run ...` on the host, which environment* would the container get added to (and therefore which overlay network, etc).

*: Note: There is some temporary confusion here because we swapped these words.  The "multiple separate accounts that can be shared among users and own the hosts" concept (with the dropdown in the header) are now called "environment" as of v0.22.  A "project" is now a group of services, which matches the definition used by docker-compose.

**Comment by deniseschannon** [comment]
@jonpugh This is very similar to #583. What is your use case that you want to share hosts across projects (assuming you mean environments in the new UI)? Specifically, why would you need hosts across environments?

We've added in a lot of new updates to services, which may address your desire to share hosts across multiple environments. For example, with host/container labels, you are able to schedule/specify which hosts you'd want a service/container to be launched on.

**Comment by jonpugh** [comment]
My use case is to have multiple customers per host.  I'm not talking about letting an environment use more than one host, but letting more than one Project use a single host.

A "Project" would be owned by a customer, and would represent a single website, for example. Then each "environment" within a project would just be a copy of that website... like a "live", "dev" environment and a "test" environment.

In the current way Rancher works, each project requires it's own host.  I'd like to start increasing the density of websites per host, but I can't really do that if each new project requires a new host.

I can see that this adds access control complexity, as a Project member can see their host, and all of the containers on that host.  

If you were to implement a way for hosts to be available to multiple projects, you would need to control access on a per-container level, as users from multiple projects should not be able to see containers from another project.

Thanks for your replies!

**Comment by hrwebasst** [comment]
Environments should all have their own name-space IMO. That would allow for multiple teams to re-use the same hosts.

**Comment by vincent99** [comment]
Just to clarify again...
  - **Environment**: A group of infastructure resources (i.e. hosts).
  - **Project**: A group of service definitions and their containers. (a docker-compose project).
  - Projects and hosts are owned by a single environment.
  - An environment can have many projects and hosts.

I don't really see how sharing a host across environments, or more importantly tenants, is practical.  The owner of each environment can run privileged containers, which have full control of the entire host.  So it is not possible to isolate 2 customers who have access to all of Rancher sharing a host.

If you are creating a container on the customer's behalf (e.g. you're running a SaaS that gives me an installed copy of $app), then you're probably not giving the customer direct access to Rancher.  In that case you could stamp out a compose project for each customer within a single environment (let's all take a second to stop here and re-read the definitions above again :smile:).  This would be as safe as anything else using Docker to enforce isolation between tenants is.

Another option would be to use [rancherio/vm](https://github.com/rancherio/vm) to create many smaller host VMs inside a single physical/virtual machine, then give one of those to each customer.  This lets you easily spin up containers that create actual VMs and use them to provide stronger isolation within a single physical machine (with increased memory that comes along with VMs, of course).

**Comment by jonpugh** [comment]
So you are saying that you've switched what you call a project and an environment?  Any idea when will that switch be released?

Here's a screenshot of the current "beta" rancher server image...

![screenshot-localhost 12345 2015-06-09 10-16-12](https://cloud.githubusercontent.com/assets/106420/8060005/e3147b48-0e90-11e5-8e55-ba63b7847a4d.png)

I will shed a small tear over this change, as it lined up perfectly with my system, but i am sure it will work out.  We use "project" to represent a site and "environment" to represent instances of that site.  

>If you are creating a container on the customer's behalf (e.g. you're running a SaaS that gives me an installed copy of $app), then you're probably not giving the customer direct access to Rancher.

This is exactly what we are going to end up doing, except DevShop is more of an Open PaaS.  See https://www.drupal.org/files/devshop.png to see a single project's interface.

Thanks again for being so responsive, this information is very helpful!

**Comment by jonpugh** [comment]
Reading back it's clear that's what you've all said, I apologize for that taking so long to sink into my brain!

**Comment by vincent99** [comment]
Hmm.. I'm on my phone but either we have totally forgotten to update the `:beta` label or you need to do a `docker pull` to download a current copy. Your picture looks to be about v0.20, ~3 weeks old.  Either way that certainly explains the extra confusion :-)

Yes, we swapped the names because docker-compose uses project to mean group of services.

**Comment by jonpugh** [comment]
ah hah!

I totally forgot to docker pull.  

Still getting used to docker, I see it now.  

Looks good!

**Comment by vincent99** [comment]
It was actually both then, :beta wasn't updated since we started using `-rcX` labels.  So fail all around :-)

**Comment by kaos** [comment]
This could be closed, no?

**Comment by vincent99** [comment]
(Thanks @kaos)
