### ISSUE TITLE
Rancher 2.0 vxlan don't work

### ISSUE THREAD

**Issue by aol56** [rancher/rancher#10244]
**Rancher versions:**
rancher/server: 2.0 alpha10

**Infrastructure Stack versions:**
vxlan

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

-  There are some errors when we try to set up a new cluster with vxlan instead of ipsec:

1) In core service, when we define an other interface name than docker0 in Docker Bridge, the RANCHER_BRIDGE env variable of vxlan service seems not be set.

2) r-core-services-vxlan-router does not start:

worker-01 dockerd[894]: level=error msg="containerd: start container" error="oci runtime error: sysctl \"io.rancher.container.orchestration\" is not in a separate kernel namespace\n" id=896d212dd9673e65972577ee79e10f3c80c2b795d95918639a40fcaf63571b13
worker-01 dockerd[894]: level=error msg="Create container failed with error: invalid header field value \"oci runtime error: sysctl \\\"io.rancher.container.orchestration\\\" is not in a separate kernel namespace\\n\""
worker-01 dockerd[894]: level=error msg="Handler for POST /v1.24/containers/896d212dd9673e65972577ee79e10f3c80c2b795d95918639a40fcaf63571b13/kill returned error: Cannot kill container 896d212dd9673e65972577ee79e10f3c80c2b795d95918639a40fcaf63571b13: Container 896d212dd9673e65972577ee79e10f3c80c2b795d95918639a40fcaf63571b13 is not running"

Regards

**Comment by superseb** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!
