### ISSUE TITLE
[external-lb] when creating external-lb container, getting errors and cannot use external lb.

### ISSUE THREAD

**Issue by c-yokoyama** [rancher/rancher#10240]
**Rancher versions:**
rancher/server:
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec: v0.1.4
network-services: v0.2.6
scheduler:v0.6.3
external-lb:v0.1.1

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS, kernel 4.4.0-97-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create container using F5 BIG-IP catalog built-in rancher v1.6.

**Results:**
I got error logs as follows.

```
10/30/2017 10:39:37 AMtime="2017-10-30T01:39:37Z" level=error msg="f5 GetLBConfigs: Error getting the pool: /Test/Web_Endnode, err: Found unexpected URI tmapi_mapper/ltm/pool//Test/Web_Endnode.\n"
10/30/2017 10:39:37 AMtime="2017-10-30T01:39:37Z" level=error msg="f5 GetLBConfigs: Error getting the pool: /kubernetes-static/k8s-apiserver-pools, err: Found unexpected URI tmapi_mapper/ltm/pool//kubernetes-static/k8s-apiserver-pools.\n"
10/30/2017 10:39:37 AMtime="2017-10-30T01:39:37Z" level=error msg="f5 GetLBConfigs: Error getting the pool: /kubernetes-static/k8s-apiserver-stg-pool, err: Found unexpected URI tmapi_mapper/ltm/pool//kubernetes-static/k8s-apiserver-stg-pool.\n"
```
`Test` and `Kubernetes` are the partition I created before and not related to this rancher environment.

I read the code and I thought here was suspicious.
https://github.com/rancher/external-lb/blob/master/providers/f5/f5_bigip.go#L272-L274

**Comment by aemneina** [comment]
Partitions arent [supported yet](https://github.com/scottdware/go-bigip/issues/12) in the [go-bigip](https://github.com/scottdware/go-bigip/) library.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
