### ISSUE TITLE
Selected specific host during creation doesn't be selected when try to upgrade it

### ISSUE THREAD

**Issue by Maxwell1987** [rancher/rancher#10241]
**Rancher versions:**
rancher/server: 1.6.x

1. Create a new service
2. In scheduling tab, select `run all containers on a specific host`
3. Select the second host in host list in the drop-down
4. Upgrade the service

**Result:**
In scheduling tab, the selected host is the first host instead of the second one.

**Comment by loganhz** [comment]
@Maxwell1987 Please use English to submit an issue next time. thanks

**Comment by loganhz** [comment]
@Maxwell1987 I cannot reproduce this issue.
Can you provide your console log?

**Comment by Maxwell1987** [comment]
@loganhz This bug maybe only on firefox?

**Comment by loganhz** [comment]
@Maxwell1987 yes, I can see it in firefox . thanks

**Comment by tfiduccia** [comment]
Version - 1.6.11-rc7
Verified fixed
