### ISSUE TITLE
GitHub Enterprise config gets cleared after adding organisations/users

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10247]
**Rancher versions:**
rancher/server: v1.6.10

**Steps to Reproduce:**
1. Setup Access Control using GitHub and specify an Enterprise server
1. Active Access Control by hitting `Authenticate using GitHub`
1. After successful authentication, add a user/org and hit Save.

**Results:**
Config parameters which point to Enterprise install are reset (`githubConfig.hostname` == null, `githubConfig.scheme` == 'https'). After the activation of access control, the parameters are there but when clicking `Save` they are not send.

**Comment by tfiduccia** [comment]
Logan - on the post the UI is not sending the 'hostname' and the schema is 'https' even thou I had set it to unsecured.  This is causing the access to get messed up.

**Comment by deniseschannon** [comment]
Available with v1.6.11-rc6

**Comment by tfiduccia** [comment]
Version - v1.6.11-rc6
Verified fixed
