### ISSUE TITLE
vSphere Docker Volume Service error in docker compose

### ISSUE THREAD

**Issue by thiagolealassis** [rancher/rancher#10248]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: default from rancher/server 1.6.10
ipsec: default from rancher/server 1.6.10
network-services: default from rancher/server 1.6.10
scheduler: default from rancher/server 1.6.10
kubernetes (if applicable): na

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-693.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Im am usin the vSphere Docker Volume Service as my storage driver (https://vmware.github.io/docker-volume-vsphere/), im testing with this compose below

version: '2'
services:
  redis:
    image: redis:3.0.7
    volumes:
    - test@VNX_STG_VMDATA_LAB:/data
    labels:
      io.rancher.scheduler.affinity:host_label: redis=true
volumes:
  test@VNX_STG_VMDATA_LAB:
    driver: vsphere
    driver_opts:
      size: "1gb"

Then i created a new stack called redis, so i'm getting the following error:

Error response from daemon: create redis_test@VNX_STG_VMDATA_LAB_05cc8: VolumeDriver.Create: Invalid datastore 'VNX_STG_VMDATA_LAB_05cc8'.

As can i see in Rancher docs (http://rancher.com/docs/rancher/latest/en/rancher-services/storage-service/): "In Rancher, stack scoped volumes are named with the stack name as a prefix to indicate which stack the volume is scoped to and suffixed with a random number to guarantee no duplication. When referencing the volume, you still use the original volume name. For example, if you create a volume called foo in stackA, the volume name in the UI and on your hosts will be stackA_foo_randomNumber, but to use the same volume in your service, you would use the name foo."

The vSphere Docker Volume Service volume name have the following syntax: name@DATASTORE, and rancher appends an randomNumber to the end of volume name. There is an way to avoid rancher append randomNumber ? or append a randomNumber before @DATASTORE like stackA_foo_randomNumber@DATASTORE ?

**Results:**

I cant use the vSphere Docker Volume Service.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
