### ISSUE TITLE
Failing dns, ipsec and/or network services on fresh install of ubuntu 17.10

### ISSUE THREAD

**Issue by kallqvist** [rancher/rancher#10249]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.1.4
network-services: 0.2.6
scheduler: 0.6.3
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**

root@qs01:~# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.8.3
 Git commit:   092cba3
 Built:        Thu Oct 12 22:34:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   092cba3
 Built:        Thu Oct 12 22:34:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-16-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.696 GiB
Name: qs01
ID: 6QME:DKKC:35D4:M3DU:4N5B:2G2D:32MG:24F7:M7AF:NKZ2:F5KC:TZW5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
root@qs01:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-poli
cy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

root@qs01:~# uname -r
4.13.0-16-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher w/ external db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- new install of ubuntu 17.10
- all apt updates applied
- docker installed from default ubuntu apt sources
(sudo apt-get install -y docker.io=1.13.1-0ubuntu6)

**Results:**
Rancher metadata, rancher ipsec and rancher dns fail to start.

**Rancher network manager logs:**
```
30/10/2017 19:53:24time="2017-10-30T18:53:24Z" level=info msg="routesync: DOCKER_BRIDGE=docker0, METADATA_IP=169.254.169.250"
30/10/2017 19:53:24time="2017-10-30T18:53:24Z" level=info msg="routesync: starting monitoring on bridge: docker0, for metadataIP: 169.254.169.250 every 60 seconds"
30/10/2017 19:53:24time="2017-10-30T18:53:24Z" level=info msg="Waiting for metadata"
30/10/2017 19:54:08Creating metadata client: Get http://169.254.169.250/2016-07-29/version: dial tcp 169.254.169.250:80: getsockopt: no route to host
````

**Rancher metadata logs:**
```
30/10/2017 19:57:18time="2017-10-30T18:57:18Z" level=info msg="Starting rancher-metadata v0.9.4"
30/10/2017 19:57:18time="2017-10-30T18:57:18Z" level=info msg="Subscribing to events"
30/10/2017 19:57:18time="2017-10-30T18:57:18Z" level=fatal msg="Failed to subscribeGet https://rancher.mydomain.com/v2-beta: dial tcp: lookup rancher.mydomain.com on 127.0.0.53:53: read udp 127.0.0.1:40884->127.0.0.53:53: read: connection refused"
```

**Notes:**
This is happening on two freshly installed machines in an otherwise healthy rancher environment with the rest of the (problem-free) nodes running ubuntu 14.04 or ubuntu 16.04, (all of these nodes are running docker 1.12.6).
Other than differences in ubuntu- and docker-versions all nodes have identical configurations and their correct host IP's set in the 192.168.1.x private net of the rack they're in.
- Rancher agent can connect without issue to the rancher master.
- No firewall is in place in the network between the servers
- UFW service is disabled on both of the new servers.

Both docker 1.12.x and 1.13.x are listed as supported versions for rancher so I'd imagine this could be about some changes in ubuntu dns and/or ip routing in the new 17.x releases?

Any tips for next steps for me to take or how to debug this further?

**Comment by superseb** [comment]
Problem seems to be Ubuntu 17 using `systemd-resolved`, which puts `127.0.0.53` inside `/etc/resolv.conf` which is then used by the metadata container to query for your configured Rancher server API endpoint (`rancher.mydomain.com`). You can see a whole thread on this here (https://github.com/docker/libnetwork/issues/1654).

To fix this, you can do multiple things but depends on your setup. Are you allowed to disable `systemd-resolved` and configure `/etc/resolv.conf` as you want it? Do you get the info from DHCP?

Don't forget to restart metadata after the changes.

**Comment by kallqvist** [comment]
Yes, getting rid of systemd-resolved is both allowed here and it solved my issues :)
Now I just need to figure out how to get DHCP config of nameservers back but I'll let that be an exercise for another week...

Thanks!

For anyone googling their way here, here are the steps I went through to disable systemd-resolvd and setting up google nameservers manually on ubuntu 17.10 (run as sudo and before starting rancher agent):
```
systemctl disable systemd-resolved.service

service systemd-resolved stop

rm /etc/resolv.conf

cat << EOF > /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF

service systemd-networkd restart
```

**Comment by MosheL** [comment]
I was solved the same problem with --dns



 docker run -d --volumes-from rancher-data \
  --restart=unless-stopped \
    -p 80:80 -p 443:443 \
--dns 10.1.130.252 \
    rancher/rancher:stable
