### ISSUE TITLE
Make SAML Service name configurable

### ISSUE THREAD

**Issue by ocasta** [rancher/rancher#10245]
I have successfully configured the Shibboleth authentication to use Google's SAML authentication. I can see from other messages that people have also successfully used it for PingID. Unfortunately the button on the login screen always says "Authenticate with Shibboleth" which my users find confusing. 

It would be good if the _ Shibboleth_ part of the string was configurable so I could change it to something more meaningful.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
