### ISSUE TITLE
Administration submenu is showing up for non-admin

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1024]
v0.23.0-rc1
Steps:
1.  Log in and Authenticate as you
2.  Create and environment and give rancherdev access
3.  Log in as rancherdev
4.  Click on your settings drop-down in upper right

Results:
![image](https://cloud.githubusercontent.com/assets/11514927/7968091/68797a3e-09e3-11e5-945d-9715e27de62b.png)

Expected:
No Administration submenu

**Comment by deniseschannon** [comment]
As of v0.37.0-rc1, no longer relevant as there is an admin tab.
