### ISSUE TITLE
Default scheduling host is not the host where we click add container

### ISSUE THREAD

**Issue by Maxwell1987** [rancher/rancher#10242]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent:

**Steps to Reproduce:**
1. INFRASTRUCTURE | Hosts
2. click "Add Container" in `host A` detail page
3. click "Scheduling" tab
4. expect `host A` is selected for "Run on a specific host" 

**Results:**

The first host in hosts list got selected instead of `host A`

**Comment by loganhz** [comment]
@Maxwell1987 please use English to submit an issue next time .
thanks

**Comment by loganhz** [comment]
@Maxwell1987 I cannot reproduce this issue.
Can you provide your console log?

**Comment by tfiduccia** [comment]
Version - 1.6.11-rc7
Verified fixed
