### ISSUE TITLE
misleading "Timeout getting IP address" when host memory is low

### ISSUE THREAD

**Issue by robbatt** [rancher/rancher#10254]
**Rancher versions:**
rancher/server: v1.6.10 (separate Host)
rancher/agent: v1.2.6 (2 Hosts)

**Infrastructure Stack versions:**
healthcheck: v0.3.3 (catalog v0.3.3)
ipsec: net:v0.11.9 (catalog v0.1.4)
network-services: mgr v0.7.8 / metadata v0.9.4  (catalog v0.2.6)
scheduler: v0.8.2 (catalog v0.6.3)
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
`Containers: 89
 Running: 62
 Paused: 0
 Stopped: 27
Images: 370
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 971
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-nfs
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.71GiB
Name: host1
ID: JH47:ITJ3:WKUV:AEBS:RMQI:KMH6:OSSI:Z4KU:RKAW:2SYZ:OL5X:ROP5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
`

`Containers: 72
 Running: 36
 Paused: 0
 Stopped: 36
Images: 82
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 443
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-nfs
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.71GiB
Name: host2
ID: JH47:ITJ3:WKUV:AEBS:RMQI:KMH6:OSSI:Z4KU:RKAW:2SYZ:OL5X:ROP5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
host1 and host2:
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
3.16.0-4-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VSphere 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 separate rancher server, 2 hosts in environment, DB(s) internal

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Our system has been running for about half a year now, upgrades from earlier rancher versions and docker included. We recently started to add automated deployment from gitlab-ci via rancher-cli (rancher up + compose files) and running builds via gitlab-multi-runner the same rancher environment. After some time we hit the "aufs cache" problem of docker 17.06.1 where old diffs wouldn't be cleaned from /var/lib/docker/aufs, an upgrade to docker 17.06.2 solved that but it seems there are other problems turning up with extended use. We are currently running about 100 containers, the memory of both hosts is at around 9/16GiB and 14,5/16GiB.

I just tried adding another container that takes up to 3 GB of memory on host2. I saw several containers turn "unhealthy" and finally be restarted. That's when the shit hit the fan ... response times from rancher scheduler increased and ran into timeouts, finally none of the unhealthy containers came back online, saying "Timeout getting IP address" ... kind of distracting from the memory issue of the host. Some status bar in the hosts tab or general warning/error notification would be great.

After removing the new container, everything turned back to normal again.

**Results:**

**Comment by robbatt** [comment]
After adding a memory limit, we also saw containers using swap up to 10 GB of 4 GB available instead. Again some global monitoring Dashboard would be great.

**Comment by superseb** [comment]
Thanks for reporting, closing this in favor of https://github.com/rancher/rancher/issues/3527
