### ISSUE TITLE
TCP connections timeout behind load balancer

### ISSUE THREAD

**Issue by kooinam** [rancher/rancher#10250]
I am currently using Rancher to  setup load balancer ( HAProxy ) and several TCP services, Postgres, Mongo, Logstash. I'm able to establish TCP connection with these services, but they all got timeout after few minutes.

Timeout errors im getting are like 

> Mongo::Error::SocketTimeoutError, Socket request timed out

> server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.

> [LogStashLogger::Device::TCP] Errno::EPIPE - Broken pipe

<img width="1362" alt="rancher_" src="https://user-images.githubusercontent.com/1638504/32194652-f30c581a-bdf5-11e7-86cb-3f3d964be61a.png">
My Rancher load balancer setup.

 I'm unsure of what the problems could be. Rancher ? HAProxy ? Docker ? Any help is appreciated.

**Comment by dim777** [comment]
Hi!
Probably your issue could resolve correct configuration for rancher lb. 
In my case following haproxy config resolved timeout issue:
```bash
version: '2'
services:
  cilb:
    scale: 1
    lb_config:
      config: |-
          global
              maxconn 4096
              maxpipes 1024
          defaults
              timeout client 36000s
              timeout server 36000s
      port_rules:
        #mongodb
        - source_port: 9017
          target_port: 27017
          protocol: tcp
          service: mongodb
      health_check:
          port: 42
          interval: 2000
          unhealthy_threshold: 3
          healthy_threshold: 2
          response_timeout: 2000
```
yml configs are here:
https://github.com/dim777/ci/tree/master/rancher/mock-services

**Comment by superseb** [comment]
Closing as stale
