### ISSUE TITLE
Invalid Value for environment variable should not be thrown

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#10265]
**Rancher versions:**
rancher/server: 2.0.0-alpha9
rancher/agent: v2.0-alpha4

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.12.3
network-services: n/a
scheduler: n/a
kubernetes (if applicable): not sure

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

HyperV

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

2.0.0 Quick Start Guide

**Steps to Reproduce:**

Create a container with a colon (":") in the name of the environment variable. This is necessary for some .Net AspNetCore applications when overriding appsettings.json values.

**Results:**

```text
spec.containers[0].env[0].name: Invalid value: "Redis:Host": a valid C identifier must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name', or 'MY_NAME', or 'MyName', regex used for validation is '[A-Za-z_][A-Za-z0-9_]*')
```

**Comment by superseb** [comment]
This is basically validated in Kubernetes here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L305

If I read through posts and docs on people running .Net, they use double underscore as a replacement of the colon. Can you try if this solves your usecase?

From: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?tabs=basicconfiguration
```If : cannot be used in environment variables in your system, replace : with __ (double underscore```

**Comment by deniseschannon** [comment]
As of the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!
