### ISSUE TITLE
health check blocked when update or upgrade container

### ISSUE THREAD

**Issue by GxlZ** [rancher/rancher#10264]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.3.3

ipsec: rancher/net:v0.11.9, rancher/net:holder

network-services: rancher/metadata:v0.9.4, rancher/network-manager:v0.7.8

scheduler: v0.8.2

**Docker version: 17.06.2-ce **

**Operating system and kernel: ubuntu:16.04 **

**Type/provider of hosts: aliyun**

**Setup details: HA rancher, external DB)**

**Environment Template: Cattle**

**Steps to Reproduce:**

> container health check info:
"healthCheck": {
"type": "instanceHealthCheck",
"healthyThreshold": 2,
"initializingTimeout": 60000,
"interval": 1000,
"name": null,
"port": 8989,
"recreateOnQuorumStrategyConfig": null,
"reinitializingTimeout": 60000,
"requestLine": "GET \"/\" \"HTTP/1.0\"",
"responseTimeout": 1000,
"strategy": "none",
"unhealthyThreshold": 3
},

1.in container : `curl  localhost:8989/sleep` (sleep 100s)
2.stop container on rancher UI
![image](https://user-images.githubusercontent.com/11898514/32322978-67c1ec98-bf94-11e7-8d18-438b86cf104f.png)

3.look at `Processes` health check blocked.
![image](https://user-images.githubusercontent.com/11898514/32323057-a9ae2e1e-bf94-11e7-919c-e5bc067f9f8c.png)

4.traefik not remove graceful-shutdown container
![image](https://user-images.githubusercontent.com/11898514/32323139-f59b636e-bf94-11e7-9d28-98903290fb0d.png)

I want graceful-shutdown my app.
What should i do ?

**Comment by superseb** [comment]
We recently made a first effort to do draining on the included haproxy loadbalancer here: http://rancher.com/docs/rancher/v1.6/en/cattle/adding-load-balancers/#draining-target-connections-for-a-load-balancer

Regarding traefik, this is something you have to take care of. e.g. watching for the stop event and telling traefik to lower the weight to drain connections.
