### ISSUE TITLE
rancher aws doesn't use main volume

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#10274]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.6

**Type/provider of hosts: AWS**

**Setup details: HA Rancher**

**Environment Template: Cattle**

**Steps to Reproduce:**

From Rancher hosts when adding a new AWS i3.large which has 1 x 475 NVMe SSD we need to set a root size in GB (in my case it's 300GB).

This make the 1 x 475 NVMe SSD completely useless as the root partiion will not be mount on this.
![df_h](https://user-images.githubusercontent.com/1558372/32438380-8c5d9f9e-c2ea-11e7-8e2d-adc23ab835d5.png)
![lsblk](https://user-images.githubusercontent.com/1558372/32438384-8f510222-c2ea-11e7-86ce-8532aa038094.png)

How can I make Rancher install the OS on the 475 NVMe SSD partition?

**Comment by vincent99** [comment]
We use docker-machine to deploy the instance, which does not have any special options for handling multiple disks or knowing where you want to mount them.  You can still partition, mount it somewhere appropriate (perhaps `/var/lib/docker`), and use it.  Or using a different AMI that is instance-store only and has no EBS root would probably work.

**Comment by jean-francois-labbe** [comment]
Thanks to the explanation.

But the instance-store AMI is not working with the kind of host I want.

`Error in driver during machine creation: Error launching instance: UnsupportedOperation: AMI 'ami-015c7272' with an instance-store root device is not supported for the instance type 'i3.large'.`

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
