### ISSUE TITLE
Adding a hostlabel with value containing whitespace will cause unexpected scheduling error when trying to fix/re-add the label without whitespace

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10271]
**Rancher versions:**
rancher/server: v1.6.10

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Add a host to Cattle environment using the custom command and add the label `key`:`testlabel`,`value`:`true ` (note the whitespace at the end)
1. Correct the label through the UI by using `Edit` on the host, when its submitted, it look resolved but in the DB the whitespace is still present. Scheduling a service to this label (even using the dropdowns) won't work. `(Failed to allocate instance [container:1i22]: Bad instance [container:1i22] in state [error]: Allocation failed: needs host with label testlabel: true)`
1. Delete the label from the host and re-add it without whitespaces
1. Label will show correct in the UI but service won't be scheduled with the same error.

**Results:**
Once there is a label in the DB with whitespace, that label can not be corrected anymore by UI/API actions as the underlying code will check the value without whitespace.

Query to run if you think you are hitting this.
```
select id, quote(`key`),quote(value) from label where type='host' AND state='created' AND value like ' %' OR value like '% ';
```

**Comment by sangeethah** [comment]
Tested with rancher/server: v1.6.11-rc7
1. Add a host to Cattle environment using the custom command and add the label ```key:test1,value:value1 ``` (note the whitespace at the end).
2. Try to schedule a service to host with label ```test1=value1```.Able to schedule containers to this host as expected.

Setup with rancher/server: v1.6.10
1. Add a host to Cattle environment using the custom command and add the label ```key:test2,value:value2 ``` (note the whitespace at the end).
2. Try to schedule a service to host with label ```test2=value2```. Scheduler will not be able to allocate containers to this host.
3. Upgrade to rancher/server: v1.6.11-rc7
4. Edit host and delete the label and re-add it without whitespaces. After this container from step2 will be able to schedule on this host.
5. Also Editing host and editing the label value to have no whitespaces will also result in  container from step2 to be schedule on this host.

1 Related issue - https://github.com/rancher/rancher/issues/10279
