### ISSUE TITLE
Cattle agent ping-pong

### ISSUE THREAD

**Issue by atheoscommune** [rancher/rancher#10270]
**Rancher versions:**
rancher/server:v2.0.0-alpha10
rancher/agent:v2.0-alpha4

**Cattle tracking reply of a ping packet**
How does cattle get reply of its ping packets to agent? Cattle pings every 3 seconds and on success it processes the reply. What is the form of reply that cattle gets? Is it the HTTP GET/POST from agent which is resolved as reply or is it just ack packet?

My firewall drops some suspicious packets (like websocket packets) and it causes the pings to fail.

**Comment by vincent99** [comment]
All of the agent (and also updating of the UI) communication is WebSockets.

**Comment by superseb** [comment]
If you have any other questions, don't mind asking them in the forums (https://forums.rancher.com)
