### ISSUE TITLE
UI: lbService.update should respect regionName, environmentName, weight

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#10280]
**Rancher versions:**
1.6.11

We have to add "show region options" to LoadBalancer screen (add only when at least one region is present in the system). Once clicked, region (string), environment (string), weight (int) should be shown. This way when lb got configured using rancher-compose, we do not override those fields by lb edit

**Comment by sangeethah** [comment]
Rancher versions: Build from https://github.com/alena1108/cattle - "region"

User is provided with "Show region options" on Edit and Add Load Balancer when there is atleast 1 region entry configured in the rancher-server . When using this option, user would be able to enter Region,Environment and Weight for selector port rules.
