### ISSUE TITLE
Show LB host IP in the Service View

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1028]
Currently, the only way to find the LB host IP on a service would be to click into the LB service->LB agent and then to HostIP.  In our "normal" LB, the Host IP is right front and center.

**Comment by vincent99** [comment]
@will-chan agree but think I'm going to have go with 'no' on this one for beta.. There is no efficient way to get this from a service, it's many links and potential calls.  We should add an efficient way to get this into the API.  On the regular LB they have hosts directly so it's simpler, but still too complicated.

```
get lbservice
follow 'instances' link
foreach instances {
  follow 'hosts' link
  foreach hosts {
    follow ipAddresses link
  }
}
```

**Comment by will-chan** [comment]
Yeah, not required for beta.

**Comment by deniseschannon** [comment]
There are a couple of enhancements for this.

1. The exposed port is available in the stack view and links directly to a host IP and port.
<img width="754" alt="screen shot 2015-12-29 at 3 00 23 pm" src="https://cloud.githubusercontent.com/assets/11410997/12043763/086bd71e-ae3d-11e5-9a16-bd07e8224d9a.png">

2. In the summary view of the load balancer, you can find all the host IPs that have the load balancer container. 
<img width="966" alt="screen shot 2015-12-29 at 3 00 39 pm" src="https://cloud.githubusercontent.com/assets/11410997/12043764/0d54fc42-ae3d-11e5-93e4-1de47081a05f.png">

3. In the detailed view of the load balancer, you can find all the host IPs for each container. 
<img width="465" alt="screen shot 2015-12-29 at 3 02 07 pm" src="https://cloud.githubusercontent.com/assets/11410997/12043773/35dfc836-ae3d-11e5-8788-cecc2283443d.png">
