### ISSUE TITLE
UI: service.update - respect cross environment links

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#10281]
Rancher versions:
1.6.11

Currently UI understands only links in the format of stackName/serviceName: alias. Cross environment links created using rancher-compose (regionName/environmentName/stackName/serviceName or environmentName/stackName/serviceName, are not being recognized by the UI, and service.edit overrides them.

**Comment by sangeethah** [comment]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch

When there is atleast 1 region entry , there is a "custom" option that is available in "service destination" drop down menu were user has the ability to enter any text. This can be used for also editing existing  cross environment links.

There is no loss of data when UI is used to view/update the service which have cross environment links created using rancher-compose .
