### ISSUE TITLE
specifying mac address for container doesnt work

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10284]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Steps to Reproduce:**
tried using `mac_address` for compose with bridged and managed network modes as well as attempting to modify the mac address with `io.rancher.container.mac_address`.

There's actually limited success using the label, the containers' network interface gets the mac address but metadata has a different mac address, which causes arp sync issues.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
