### ISSUE TITLE
[gdapi-python]  No way to create an environment key using python api

### ISSUE THREAD

**Issue by timlinux** [rancher/rancher#10283]
Hi

It seems the the gdapi-python library doesn't provide a simple way to get an environment key and secret equivalent to:

http://rancher.foo.com:8080/v1/projects/12259/apikeys?name=FakeClientKey

Am I missing something obvious or is it missing from the api?

CC @dimasciptura

**Comment by superseb** [comment]
```gdapi create-apiKey --accountId ENV_ID```
