### ISSUE TITLE
Docker-compose support version 2.2 or 3

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#10290]
**Rancher versions:**
rancher/server: 1.6.10

**Infrastructure Stack versions:**

**Docker version: 17.06**

**Type/provider of hosts: (AWS**

**Environment Template: Cattle**

Is there any plan to support docker-compose version 2.2 or 3?

I would need to set the `cpus` option https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources and currently I get an error.

Even if I couldn't be able to modify it from the interface just taking it into account would be great.

**Comment by superseb** [comment]
`cpus` will be implemented in https://github.com/rancher/rancher/issues/9454
