### ISSUE TITLE
LDAP group mapping not working with Oracle Directory Server EE

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#10292]
**Rancher versions:**
rancher/server: 1.6.10
cattle

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Auth enabled with OpenLDAP integration

**Steps to Reproduce:**
1. Configure OpenLDAP with a Oracle DSEE server
UserMemberAttribute: `ismemberof`

**Results:**
Users are able to login, but their group membership is not applied which prevents them to access environments that their groups are authorized in.

Tracelogs show that Rancher is unable to find the `UserMemberAttribute` after fetching the user's regular and operational attributes.

The reason is that with Oracle DSEE `ismemberof` is a virtual attribute which does not get returned in a search unless explicitly requested.

> If you want operational attributes returned as a result of a search operation, you must explicitly specify them in the search command.
_[source](https://docs.oracle.com/cd/E19424-01/820-4811/gdxph/index.html)_

**Comment by teebeey** [comment]
`ismemberof` (which contains the groups of a user) and `entryDN` (which contains the full path of the LDAP object as an attribute) are not shown in case of OpenLDAP's method to request operational attributes.

However both of them can be requested explicitly on Oracle DSEE this way:
```
root@c50302b4b34b:/# ldapsearch -D "cn=rancher,dc=adm" -W -h ldapserver -b cn=myuser,ou=people,dc=adm entryDN ismemberof
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <cn=myuser,ou=people,dc=adm> with scope subtree
# filter: (objectclass=*)
# requesting: entryDN ismemberof
#

# myuser, people, adm
dn: cn=myuser,ou=people,dc=adm
entryDN: cn=myuser,ou=people,dc=adm
ismemberof: cn=dummy_group_1,ou=rancher-groups,dc=adm
ismemberof: cn=dummy_group_2,ou=rancher-groups,dc=adm

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

**Comment by deniseschannon** [comment]
@sangeethah work with @mrajashree and @rawmind0 to get access to an oracle setup. 

Note: the fix was *after* v1.6.15-rc6.

**Comment by sangeethah** [comment]
Tested with latest build from v1.6 branch.

Configure OpenLDAP with a Oracle DSEE server with following attributes:
UserMemberAttribute: ismemberof
schema: object class for groups: groupOfUniqueNames

Following scenarios relating to Groups works:

1. Add group to "Restrict access to only Authorized users and Organization"

Log in as user who is part of this group. User is able to log in successfully to rancher-server.

Remove an existing group from "Restrict access to only Authorized users and Organization" list.

Log in as user who is part of this group. User is denied access with error message - "Your account does not have access"

2. Add group to "Allow members of the Environment , Plus Authorized users and Organization"

Log in as user who is part of this group. User is able to log in successfully to rancher-server.
This will result in default environment getting created for this user.

Remove existing group from  "Allow members of the Environment , Plus Authorized users and Organization"

Log in as user who is part of the removed group but who is not a member of any existing environment.
User is denied access with error message - "Your account does not have access"

Add the group that the user belongs to as part of one of the existing environments.

Log in as this user. User is able to log in successfully to rancher-server.

Removed this group from the member list of the existing environment.

Log in as this user. User is denied access with error message - "Your account does not have access"

**Comment by sangeethah** [comment]
@galal-hussein Can you have some testing done on openLDAP (especially on group related cases)  to make sure there is no regression when using openLDAP auth?

**Comment by galal-hussein** [comment]
Rancher version: v1.6.15-rc7
I ran all openLDAP tests that affect users and groups and all Passed successfully
