### ISSUE TITLE
Region - When one of external service names does not resolve , there is no attempt made to resolve other  external service names

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10294]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch
Steps to reproduce the problem:

1. Create a region entry (self) with name - "region1".
2. Create env - "test2" with stack - "stack2" and service name - "test2" and "target1"
3. Create env - "test1" with stack -"stack1" having a service that links to service - "test2" created in step2 as "/region1/test2/stack2/test2" and LB with portrules having "region" as "region1 and environment as "stack2" (instead of "test2".

Even though we are not able to resolve the external account link for LB (because of being invalid), we should have been able to  resolve the external account link for service link which did not happen.

**Comment by alena1108** [comment]
@sangeethah I can no longer reproduce this issue, could you recheck if it happens on the latest?

**Comment by sangeethah** [comment]
Tested with Rancher versions: v1.6.13-rc3
catalog - https://github.com/leodotcloud/rancher-catalog.git branch- regions

This issue is not seen anymore.
