### ISSUE TITLE
Can not see catalog entry in Windows environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10298]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
N/A
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
N/A
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
N/A
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
N/A
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. Create your catalog repo and put a Windows catalog entry in it. Put it into `templates` folder.
2. Add your catalog repo into your Windows environment.

**Results:**
Cann't see the added entry.

There is a workaround. Put the catalog entry into `infra-templates` folder. And you can see the catalog entry. But I think it needs enhancement.

**Comment by tfiduccia** [comment]
Templates are based on Orchestration type.  The ```templates``` folder works only for Cattle orchestration.  Try adding a ```windows-templates``` folder.

**Comment by deniseschannon** [comment]
Verified that if you add `windows-templates` folder, these templates would show up.
