### ISSUE TITLE
Scaling replication controller using dashboard is not functional

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10296]
**Rancher versions:**
rancher/server:v1.6.11-rc8

kubernetes (if applicable):K8s1.8.2-rancher3-etcdv2

**Docker version: (`docker version`,`docker info` preferred)** v1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**Digital Ocean

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes setup (K8s1.8.2-rancher3-etcdv2)
2. Create few rcs/pods/services
3. Launch dashboard, and scale replication controller by right clicking the RC.
Scale increase/decrease does not take into effect. Dashboard logs below:

```
11/8/2017 3:09:24 PM[2017-11-08T23:09:24Z] Outcoming response to 10.42.0.1:34762 with 200 status code
11/8/2017 3:09:41 PM[2017-11-08T23:09:41Z] Incoming HTTP/1.1 PUT /api/v1/scale/Replication%!C(MISSING)ontroller/default/k8testrc6?scaleBy=10 request from 10.42.0.1:56586: {
11/8/2017 3:09:41 PM  "Content-Type": "application/json"
11/8/2017 3:09:41 PM}
11/8/2017 3:09:41 PMthe server could not find the requested resource
11/8/2017 3:09:41 PM[2017-11-08T23:09:41Z] Outcoming response to 10.42.0.1:56586 with 404 status code

```
Note: Editing the yaml file to increase the scale is working. Deleting resources using dashboard is working

**Comment by galal-hussein** [comment]
the logs show error in the dashboard code, after updating the dashboard to v1.7.1 it solved the problem

**Comment by soumyalj** [comment]
Tested with rancher v1.6.11-rc9 using Kubernetes v1.8.2-rancher4. Scaling repication controller using dashboard is functional.
