### ISSUE TITLE
[gdapi-python] How do you create a host

### ISSUE THREAD

**Issue by pdonorio** [rancher/rancher#10305]
**Rancher versions:**
rancher/server: 1.6.11-rc6
gdapi: 0.5.3

**Docker version: (`docker version`,`docker info` preferred)**
1.13.x

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
```python
import gdapi

client = gdapi.Client(url=..., access_key=..., secret_key=...)

client.create_host()
# or
client.by_id_project(...).create_host()
```

**Results:**

The GDAPI does not exist to create a host or a container in a project. And I cannot find a way around since there is no description anywhere. Could you help and provide an example?
All the rest of the functions found with python introspection do work, like listing or creation of other type of resources.

Thank you

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
