### ISSUE TITLE
Region - Service links to cross environment stacks are not getting deleted when services they are linked to get deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10300]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch

Steps to reproduce the problem:

1. Create a region entry (self) with name - "region1".
2. Create env - "test2" with stack - "stack2" and service name - "test2"
3. Create env - "test1" with stack -"stack1" having a service - "test1" that links to service created in step2 as "/region1/test2/stack2/test2 with alias "myweb"
4. From containers of service test1 , we are able to resolve to containers of "test2" successfully using the service link name - "myweb".
5. Delete service - "test2" in env - "test2".

Even after this service is deleted , "test1" continues to have the link in "linkedServices" .

Expected behavior:
Link should get removed from the service when service it is linked to gets deleted.

**Comment by alena1108** [comment]
We are not going to validate the services cross regions. If the link to non-existing service is present, it will simply not gonna be resolved in dns. @deniseschannon closing the issue for now
