### ISSUE TITLE
[external-lb] Is there a way to deploy external load-balancer providers for development purposes?

### ISSUE THREAD

**Issue by tintoy** [rancher/rancher#10309]
Hi.

I'm looking at writing an `external-lb` provider for our cloud's load-balancer facility; I'm fine with _writing_ the provider (the code for existing providers seems pretty simple), but I'm not sure of the best way to go about _deploying_ it. Does it have to be built into the official image, or is there a way to tell Rancher to use a custom image so I can test my changes without impacting anyone else?

**Comment by tintoy** [comment]
I've done some digging and it looks to me like you have to deploy the container yourself, so it looks like we can just deploy an image with a custom build it'll automatically watch the cluster and call our provider as required.

Is this correct?

**Comment by superseb** [comment]
Yes, it will retrieve the data from metadata. Please see an example here for f5: https://github.com/rancher/community-catalog/tree/master/templates/f5/0

Let me know if you have any other questions.

**Comment by tintoy** [comment]
Thanks, that'll do nicely :)
