### ISSUE TITLE
Tags of stack can be set in rancher compose

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10301]
**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1. Set a tag for a stack.
2. Use the `compose YAML` view of the stack and copy the compose files to another environment to bring up the stack.

**Results:**
Need to set the tag again in the new environment.

If there is a way to save the tag of stack in rancher compose file, it will be more convenient.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
