### ISSUE TITLE
[cli] Can I download the kubernetes cluster configuration file via Rancher cli?

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#10315]
Hello -

Can I download the kubernetes cluster configuration file via Rancher cli? I am trying to work with multiple kubernetes clusters and having an option to download the respective config. files via Rancher cli would be greatly helpful. 

Thanks!

**Comment by superseb** [comment]
Not today, the config is templated in the UI (see https://github.com/rancher/ui/blob/1.6-dev/app/k8s-tab/kubectl/controller.js). The token can be generated on the command-line like this: https://gist.github.com/superseb/d35c5f1521bc9ed2f8044fd87a03bf63

But I would agree, API call to get the config would be nice for automation.

**Comment by krishofmans** [comment]
We would also prefer downloading the kubernetes config through rancher-cli/api. Currently this is a painful manual gap in our otherwise fully automated process.

**Comment by fuxjezz** [comment]
Hi, 

We are running into the same "gap". 

@superseb : Serveral new versions of Rancher have been released since the last update, has this feature request perhaps been implemented in one of those releases?

Kind regards,

Ruben

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by vincent99** [comment]
Also 2.x has an API call for this (and I think CLI command already).
