### ISSUE TITLE
when upgrading k8s 1.7 to 1.8, kubelets fail to start if swap is enabled on the host

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10311]
After upgrading to k8s 1.8 in my rancher 1.6.11-rc build, kubelets failed to start citing running with swap is not supported. We should either leverage that flag by default or release note the change in behavior.

related ticket:
https://github.com/kubernetes-incubator/kubespray/issues/1787

**Comment by moelsayed** [comment]
Tested by upgrading from v1.6.10 to v1.6.11-rc9 with k8s 1.8.2 and swap enabled hosts. Upgrade completed successfully and kubelet started correctly with no problems. When the new option "fail on swap" is set to true, kubelet failed to start.
