### ISSUE TITLE
healthcheck services and scheduling services are automatically rebuilt every few minutes

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#10312]
**Rancher versions:**
rancher/server:1.6.7
rancher/agent:default

**Infrastructure Stack versions:**
healthcheck:  default
ipsec:  default
network-services:  default
scheduler:  default
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7.3 
Linux Docker84-2 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
**There are many logs in the healthCheck service：**

11/9/2017 9:06:33 PMtime="2017-11-09T13:06:33Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/9/2017 9:06:33 PMtime="2017-11-09T13:06:33Z" level=info msg="Scheduling apply config"
11/9/2017 9:06:33 PMtime="2017-11-09T13:06:33Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 312/130633 (61) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 312/130633 (61) : config : 'option forwardfor' ignored for backend 'cattle-407d9c9f-1665-4f77-85ae-0788839631b2_9df16a7f-0bea-4946-a54f-213500132951_1' as it requires HTTP mode.\n[WARNING] 312/130633 (61) : config : 'option forwardfor' ignored for backend 'cattle-407d9c9f-1665-4f77-85ae-0788839631b2_0e463e97-df09-4f4c-92ed-f48979ab3916_1' as it requires HTTP mode.\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #2 failed: Invalid argument (errno=22)\n[ALERT] 312/130633 (61) : sendmsg logger #1 failed: Invalid argument 

Other services run normally without error logs.

Ping other services in healthCheck services ， the following information appears：
ping: sendmsg: Invalid argument
ping: sendmsg: Invalid argument
ping: sendmsg: Invalid argument

Looking at IP neigh, we found that the number of ARP entry is more
Guess because the local ARP table is full, it is impossible to insert a new ARP record

Modify kernel parameters and increase ARP table capacity

sysctl -w net.ipv4.neigh.default.gc_thresh1=1024
sysctl -w net.ipv4.neigh.default.gc_thresh2=2048
sysctl -w net.ipv4.neigh.default.gc_thresh3=4096
sysctl -p
sysctl -a |grep net.ipv4.neigh.default.gc_thresh

**Results:**
Problem solving.

Are there any optimization methods for this kind of problem? thanks!

**Comment by nayang777** [comment]
To add some clarification for this issue, when ARP table is full, Healthcheck and Scheduler services keep restarting every few mins, which are abnormal. And this problem will affect both VXLAN and Flat networking.  We are looking for a fix or workaround for this issue if possible.

**Comment by superseb** [comment]
Thoughts @leodotcloud ?

**Comment by leodotcloud** [comment]
@hongxiaolu @nayang777 can you please ping me on slack with the setup details?

**Comment by anzersy** [comment]
As investigation of the issue, we got the root cause was the current arp entries exceeded the setting of arp cache for kernel. Extend the cache size should be the good way to prevent the issue.

**Reference for details**
Ubuntu Xenial(kernel 4.4.0):https://github.com/torvalds/linux/blob/5bbcc0f595fadb4cac0eddc4401035ec0bd95b09/net/core/neighbour.c#L303

CentOS7.3(kernel 3.10.0):http://elixir.free-electrons.com/linux/v3.10/source/net/core/neighbour.c#L270
