### ISSUE TITLE
Selecting lines in Execute Shell is off

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10313]
**Rancher versions:**
rancher/server: v1.6.11-rc9

ui: 1.6.29

**Steps to Reproduce:**
Execute Shell on container (Tested with Chrome Version 62.0.3202.75 and Safari Version 11.0.1 (12604.3.5.1.1) on Mac)

**Results:**
1.6.28
<img width="956" alt="screen shot 2017-11-10 at 14 21 43" src="https://user-images.githubusercontent.com/2620179/32660332-b2eac430-c622-11e7-8193-922cfe10f56d.png">

1.6.29
<img width="1215" alt="screen shot 2017-11-10 at 14 22 24" src="https://user-images.githubusercontent.com/2620179/32660343-b9ac234a-c622-11e7-9a14-eafa2e4e510b.png">

**Comment by loganhz** [comment]
@vincent99 sorry about that. PR submitted

**Comment by superseb** [comment]
This was resolved in v1.6.11
