### ISSUE TITLE
Start-once containers are being started even though they shouldn't be

### ISSUE THREAD

**Issue by pgorni** [rancher/rancher#10314]
**Problem description**

I have a container which is used to generate analytics & reports. It should be ran every Thursday at 19:00. I wanted to employ some cron-based system like [rancher/container-crontab](https://github.com/rancher/container-crontab) or [rancher-cron](https://github.com/SocialEngine/rancher-cron), but none of them would work; [the container would be run every 1h15'](https://github.com/rancher/rancher/issues/10255). I disabled the `container-crontab` service and decided to run the container manually.

Today I noticed that the container is *still* being run every 1h15' despite having no external interference, so my guess is that Rancher itself runs it for some reason.

**Problem summary**
Containers which have `start-once` setting are being started every 1h15'.

**Expectation**
Containers with `start-once` setting aren't being executed unless I want them to.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`github` |
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by superseb** [comment]
Sorry for the late response, can you please try the latest version as the library was bumped to a newer version in v0.3.0 and up. Let me know if this doesn't work.

**Comment by sebastianwahn** [comment]
I have the same problem, although I don't have a crontab service running at all.
In my case, the started-once service will be restarted from time to time. I didn't messure the time between the restarts.


Rancher | v1.6.18
-- | --
Cattle | v0.183.52
User Interface | v1.6.43
Rancher CLI | v0.6.10
Rancher Compose | v0.12.5

**Comment by ikogan** [comment]
Still happening with v1.6.21.
