### ISSUE TITLE
[ipsec] Enable healthcheck for service

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#10326]
Related: 
- https://github.com/rancher/rancher/issues/9855
- https://github.com/rancher/rancher/issues/10217

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.6.13-rc3

ipsec version 0.2.2 with rancher/net:v0.13.6.

ipsec service is now health check enabled.

Following test cases were executed - 
[Ipsec_health_Check.xlsx](https://github.com/rancher/rancher/files/1564157/Ipsec_health_Check.xlsx)

Issue found - https://github.com/rancher/rancher/issues/10584
