### ISSUE TITLE
k8s audit logs dont see to have a maxage or maxsize configuration. 

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10325]
k8s audit logs dont see to have a maxage or maxsize configuration. causing massive amounts of log files

https://github.com/rancher/rancher/issues/6119

**Comment by aemneina** [comment]
the issue might be we're launching the docker containers without max-size max-file options.

**Comment by aemneina** [comment]
Workaround could be to upgrade the k8s service within the k8s stack and provide max-size and max-file under the log options in the security/host tab.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
