### ISSUE TITLE
deploy rancher k8s  1.7.7 rancher cli shows disconnected

### ISSUE THREAD

**Issue by hekan321** [rancher/rancher#10338]
*Describe your issue here*
deploy rancher k8s  1.7.7 rancher cli shows disconnected，dashboard doesn't work

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.kubectl`|

**Comment by superseb** [comment]
There is not much to go on here. My guess would be:

- kubectl showing disconnected is the container being killed not being healthy in time.
- dashboard not working probably also has to do with infrastructure stacks not being healthy.

Best place to start is to look at Kubernetes -> Infrastructure Stacks and see what the status of the stacks are. Also, logging of the kubelet usually tells you what's going on.

**Comment by superseb** [comment]
Please reply if you need help on this.
