### ISSUE TITLE
Not able to scale up service when container/service associated with the services scheduling policy is deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1033]
Steps to reproduce the problem:

Assume container c1 is running on host1.
Ass service s1 with rule to pick host that must have container with name “c1” and has scale 3.
Activate service.
3 containers for s1 get deployed in host1.
Now destroy c1.
scale up s1.
S1 is stuck in “update-activating” state since it can’t find placement. 

What should be the expected behavior here? Since the container has been removed , the situation can  never be corrected. There is no way for user to recover form this state.

We will end up with the sane scenario when we have rules for having host that must have service with name and the service with that name gets deleted,

**Comment by sonchang** [comment]
I think this and several other issues can all be grouped into the general category of relaying to the user why a container is not up and running (or why it failed to be allocated).  Ultimately, there are probably numerous other ways a user can shoot themselves in the foot with the various scheduling rules.

**Comment by sonchang** [comment]
@will-chan This one likely won't make it into Beta since it'll require UI work/coordination too.

**Comment by alena1108** [comment]
@sangeethah there is a way for a user to recover from this state - start a new container c1 on the host. If he put "pick host with c1 container", it might be a requirement for him, and he should take care of ensuring that c1 containers is already there.
