### ISSUE TITLE
[Load Balancer] Support haproxy "peers" feature / stick-table sync

### ISSUE THREAD

**Issue by DaveOHenry** [rancher/rancher#10339]
It would be great if the Rancher Loadbalancer could support the peers feature. We have some applications that need sticky sessions based on some portion of the path or header fields. For increased availability we currently use 2 manually set up haproxy instances in different locations that sync their stick-tables.

For example: A file is initially opened on a backend server and the loadbalancers have to know which server currenty holds which file id, because when another user requests the same file he has to be forwarded to the same backend server.

When using a single Rancher Loadbalancer in this scenario everything works fine, but as soon as more lbs are added the persistence information is not consistent any more.

Problem is that every loadbalancer has to know the other loadbalancers by their ips and names for the stick-table sync to work. See https://cbonte.github.io/haproxy-dconv/1.6/configuration.html#peers

**Comment by shatil** [comment]
Rancher allows one to extend its HAProxy configuration. Are you unable to configure `peers` in there? Or is the difficulty in determining _who_ those `peers` are?

Have you a working `peers` section example to test out?

**Comment by DaveOHenry** [comment]
I know that one can customize the haproxy config as I already customized the hell out of it :-)
But the problem here is to determine who those peers are.

```
peers my_haproxy_servers
        peer my-haproxy-1 10.11.12.13:1024
        peer my-haproxy-2 10.11.12.14:1024

backend my_custom_backend
        stick-table type string len 256 size 1m expire 12h peers my_haproxy_servers
        stick on path,regsub(/something.*CustomId,CustomId,i),regsub(%20MoreCustomStuff.*,,i) table my_custom_backend if { path_beg /something }
...
```

So basically every haproxy loadbalancer needs to know all other haproxies in its "peers" section. The port can be anything, but every loadbalancer has to have the same config and the names have to match the hostnames of the haproxy instances, because they are used at protocol level to identify each instance.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
