### ISSUE TITLE
services portReservation

### ISSUE THREAD

**Issue by phiedulxp** [rancher/rancher#10349]
*Describe your issue here*
Allocation failed: Host must satisfy resource constraints: [51321:8081/tcp portReservation].   
ports:
 - 8081
as the 51321 was set by the rancher cattle
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by superseb** [comment]
Can you elaborate a bit more on this issue? Do you find the error message misleading or is that there a bug in the logic?
