### ISSUE TITLE
Supporting Pre-installed Docker on CentOS/RHEL 7

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1034]
Per #5, Rancher is currently supporting CentOS/RHEL 7 with the latest version of Docker when installing the binary. This issue is to remain open until we officially support pre-installed Docker on CentOS/RHEL 7.

**Comment by ibuildthecloud** [comment]
@deniseschannon Now that Centos/RHEL 7 includes 1.6.x things should work.
