### ISSUE TITLE
Detect and show/log when wrong database collation/character set is used

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10342]
Explore what we can do to check/show/log wrong database collation/character set.

**Comment by dymo** [comment]
I don't know how the migrations work, but maybe something like [this](https://stackoverflow.com/questions/1294117/how-to-change-collation-of-database-table-column/35978109#35978109) might work.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
