### ISSUE TITLE
Regions - Not able to reach  sidekick targets from LB with network policy set to "allow within linked services".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10357]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch
network policy manager - leodotcloud/network-policy-manager:regions

Steps to reproduce the problem:
Network policy set to "allow within linked services" and "deny" set for all other rules.
Create a service - s1 with sidekick - sk1 having labels foo=bar
Create a LB service with "selector rule" set to "foo=bar" so that sidekicks get added as targets to LB.
LB is not functional , since sidekick containers are not able to reach from lb container.

**Comment by alena1108** [comment]
@sangeethah @leodotcloud LB shouldn't accept sidekicks as targets. Although it is possible to achieve via labels/selectors, this is not the use case users would exercise.

**Comment by deniseschannon** [comment]
@leodotcloud can you help update the regions document so that it indicates that sidekicks are not valid targets. 

@sangeethah does targeting sidekicks in regular setups work?

**Comment by leodotcloud** [comment]
I have updated the Regions wiki with notes.

**Comment by sangeethah** [comment]
Regions wiki documents this limitation.
