### ISSUE TITLE
add ssh keys to manually created hosts (so rancher cli works)

### ISSUE THREAD

**Issue by kgk** [rancher/rancher#10356]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent:  v1.2.6 

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS through spotinst integration.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
singlenode 
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Spotinst is adding AWS spotinsts through a direct call the rancher/agent:v1.2.6 
i.e. sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6  ...

These nodes come up but with very little information and even though they are on aws with ssh keys that I have provided, rancher does not have access to the keys.   I am wondering if there is a way automatically or from the rancher cli to add the proper host key to rancher DB.

**Comment by cjellick** [comment]
Unfortunately, there is not. The ability to access hosts from the CLI is accomplished by using docker-machine to create the machine and persisting and using the docker-machine configuration.

**Comment by aemneina** [comment]
I'll close this out @kgk as this feature would need to be implemented [here](https://github.com/docker/machine) first. We can revisit if it gets added to docker-machine.
