### ISSUE TITLE
Add Host in Rancher from docker-compose.yml 

### ISSUE THREAD

**Issue by olegkolner** [rancher/rancher#10352]
**Rancher versions:**
rancher/server: latest 
rancher/agent: latest 

**Docker version: (`docker version`,`docker info` preferred)**
Docker ce 17.09

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 9

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

docker-compose.yml: 

version: '3'
services:
  rancher_server:
    image: rancher/server:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./serverdb:/var/lib/mysql
      - ./certs/cert.crt:/var/lib/rancher/etc/ssl/ca.crt

 rancher_agent:
    image: rancher/agent:latest
    restart: always
    env_file:
      - ./.env
    command: http://${IP}:8080/v1/scripts/${TOKEN}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/rancher:/var/lib/rancher

I need to have the possibility to start Rancher Server with all hosts within only one docker-compose.yml file in order to easily deliver the product (just one file^^). But when I start the docker-compose file, which is written above, and go to the rancher webpage -> infrastructure -> hosts, then I see the recently added host as not activated. But when I try to add the host with the "pure" docker commando (docker run --rm --privileged -v /var/run/docker.sock:/var....) then I can see the activated host. So what could be the reason of that magic? And how can I add the host from docker-compose properly?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
