### ISSUE TITLE
Speed up rancher-nfs with fscache

### ISSUE THREAD

**Issue by huggla** [rancher/rancher#10350]
Could you make an option to turn on fscache for rancher-nfs? It would improve nfs performance.

**Comment by huggla** [comment]
## How to enable fscache for rancher-nfs
(Tested on RancherOS hosts).

### Edit the nfs-driver service like this:

Entry Point: `/bin/sh -c`

Command: 
```
'(ls /sbin/cachefilesd) || (apt update && apt install cachefilesd && rm -rf /var/lib/apt/lists/*) ; (cachefilesd -ds && start.sh storage --driver-name rancher-nfs)'
```

Add volume: `/var/cache/fscache:/var/cache/fscache`

### On hosts that is running the nfs-driver:

Make sure fscache and cachefiles kernel modules are loaded, else run:

```
modprobe fscache
modprobe cachefiles (on RancherOS you need to first enable kernel-extras)
```

Then create a (1GB) cache file and mount it as /var/cache/fscache:

```
mkdir -p /var/cache/fscache && dd if=/dev/zero of=/var/cache/cache.ext4fs bs=1024 count=1048576
mkfs.ext4 -F /var/cache/cache.ext4fs
mount -t ext4 -o loop /var/cache/cache.ext4fs /var/cache/fscache
```

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
