### ISSUE TITLE
When creating a docker container in rancher 2.0, I cannot add a volume using the "Add Volume..." button, then selecting the Bind-mount a host directory.

### ISSUE THREAD

**Issue by pmualaba** [rancher/rancher#10355]
*Describe your issue here*
When creating a docker container in rancher 2.0, I cannot add a volume using the "Add Volume..." button, then selecting the Bind-mount a host directory.

Even selecting the non-greyed out options (coming soon...) dus not do anything, So I cannot create any volume or Bind-mount a host directory.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha10` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`containers.run`|

**Comment by pmualaba** [comment]
This seems to be a Google Chrome issue... seems to work on Firefox...

**Comment by superseb** [comment]
Can you provide a screenshot and exact Chome version and OS used?

**Comment by pmualaba** [comment]
![image](https://user-images.githubusercontent.com/1754718/32957386-ddc2d316-cbbb-11e7-917e-c5d29e703ef9.png)

Google Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Linux Mint 18.2 Cinnamon 64-bit

**Comment by deniseschannon** [comment]
I'm unable to re-produce using Version 63.0.3239.132 (Official Build) (64-bit).

Please try again with Tech Preview 2 and the latest version of Chrome. 

With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM&t=4s) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!

**Comment by JohnDavidLarsen** [comment]
I and others in the slack channel are having this same issue with beta4 (I've been having the issue for a month now but haven't said anything).
I tried updating chrome but it hasn't helped. I'm seeing the same issue in Firefox as well. None of the dropdown options for Volume work when creating a new Container. It seems to be a client side javascript issue, maybe its because I'm referencing my site via IP address and not a DNS address?

**Comment by vincent99** [comment]
Nobody ever mentioned it but I eventually figured out this affected only people with a  touch-screen device like an iPad/Surface/Chromebook. It was fixed after beta4.

**Comment by JohnDavidLarsen** [comment]
Weird, I have a touchscreen and a mouse, but the mouse doesn't work either. Would it work if I disconnected my touch device? Should I just wait till beta5?

**Comment by vincent99** [comment]
Yes the presence of a touch screen changes the way more events are received even if you are using the mouse/trackpad.  There are newer images in `rancher/rancher`, we are going to use that for 2.0 to reduce (/create different) confusion on 1.6 vs 2.0 `latest`/`stable`.
