### ISSUE TITLE
Specify `--anonymous-auth=false` in kube-apiserver

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10366]
**Rancher versions:**
rancher/server: v1.6.11

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.8.3-rancher2

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Add a host to Kubernetes environment

**Results:**
`kube-apiserver` will log:

```
AnonymousAuth is not allowed with the AllowAll authorizer.  Resetting AnonymousAuth to false. You should use a different authorizer
```

`--authorization-mode` is defaulting to `AlwaysAllow` and `--anonymous-auth` is defaulting to true.

**Comment by sangeethah** [comment]
Tested with rancher/k8s:v1.9.1-rancher1-1 using rancher-server version-1.6.15-rc1.
kube-apiserver  is launched with "--anonymous-auth=false" 

```1/16/2018 2:28:20 PM+ exec kube-apiserver --storage-backend=etcd2 --storage-media-type=application/json --service-cluster-ip-range=10.43.0.0/16 --etcd-servers=http://etcd.kubernetes.rancher.internal:2379 --insecure-bind-address=0.0.0.0 --insecure-port=0 --cloud-provider=rancher --allow_privileged=true --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --client-ca-file=/etc/kubernetes/ssl/ca.pem --tls-cert-file=/etc/kubernetes/ssl/cert.pem --tls-private-key-file=/etc/kubernetes/ssl/key.pem --runtime-config=batch/v2alpha1 --anonymous-auth=false --authentication-token-webhook-config-file=/etc/kubernetes/authconfig --runtime-config=authentication.k8s.io/v1beta1=true --external-hostname=kubernetes.kubernetes.rancher.internal --advertise-address=10.42.84.155
```

Following message seen in logs with rancher/k8s:v1.8.5-rancher4 is not seen anymore:

``` AnonymousAuth is not allowed with the AllowAll authorizer.  Resetting AnonymousAuth to false. You should use a different authorizer```
