### ISSUE TITLE
[RFE] UI - Multiple selections can be enabled in Stack details UI  

### ISSUE THREAD

**Issue by nayang777** [rancher/rancher#10360]
**Rancher versions:**
rancher/server: 1.6.x
 
For stack with many services, when user wants to upgrade or delete multiple services, this feature will be very helpful.

**Comment by vincent99** [comment]
In 2.0 already for actions that make sense, not going to happen for 1.x.

Upgrade is not an action that can makes sense in bulk, you go through the UI to potentially change the whole service definition.  The only case that could make some sense is if it was a separate action for change-nothing-but-pull-images-and-redeploy...

**Comment by nayang777** [comment]
make sense. Thanks for the prompt response, Vincent.
