### ISSUE TITLE
[RFE] UI - Alert/Msg when containers keep restarting

### ISSUE THREAD

**Issue by nayang777** [rancher/rancher#10361]
**Rancher versions:**
rancher/server: 1.6.x

Instead the infinite restarting of a container when there is a problem without knowing it, whether user can get an alert from UI about such problem when a container keeps restarting over 50 or 100 times?

**Comment by nayang777** [comment]
whether this feature can be included in 2.0?

**Comment by yasker** [comment]
@zionwu Should be able to implement using AlertManager right?

**Comment by zionwu** [comment]
@nayang777 these features will be included in 2.0.

**Comment by nayang777** [comment]
got it. Thanks!
