### ISSUE TITLE
Check PersistentVolumeLabel admission controller status for kube-apiserver

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10367]
**Rancher versions:**
rancher/server: v1.6.11

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.8.3-rancher2

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Add a host to Kubernetes environment

**Results:**
`kube-apiserver` will log:

```
PersistentVolumeLabel admission controller is deprecated. Please remove this controller from your configuration files and scripts.
```

References:
https://github.com/kubernetes/kubernetes/pull/44680
https://github.com/kubernetes/features/issues/88
https://kubernetes.io/docs/admin/admission-controllers/#persistentvolumelabel

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
