### ISSUE TITLE
how to upgrade rancher-compose.yml e.g health rule via rancher-cli

### ISSUE THREAD

**Issue by jinghuaz** [rancher/rancher#10379]
**Rancher versions:**
rancher/server:1.6.10
rancher/agent:0.6.5

how to upgrade rancher-compose.yml e.g health rule via rancher-cli?

**Comment by jinghuaz** [comment]
my means how to post healthy rules via rancher cli,rancher-compose or rancher command ?
i used rancher --rancher-compose option,but didn't modify healthy rules.

**Comment by jinghuaz** [comment]
i means if rancher-compose.yml content have changed how to upgrade via rancher-cli?

**Comment by aemneina** [comment]
`rancher-compose` and `rancher` clie should both support the `--force-upgrade` flag. Doc links that could be helpful:
http://rancher.com/docs/rancher/v1.6/en/cli/commands/#rancher-up-reference
http://rancher.com/docs/rancher/latest/en/cattle/upgrading/#step-1-performing-the-upgrade

**Comment by jinghuaz** [comment]
Thanks man. I have test it, it's work fine.
