### ISSUE TITLE
[external-dns] invalid memory address or nil pointer dereference seen when route53 zone contains traffic policy record

### ISSUE THREAD

**Issue by jmirc** [rancher/rancher#10377]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
external-dns: 0.7.8 

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install Route53 DNS from Library Catalog

**Results:**
I tried with different version from 0.7.0 to 0.7.8 and I am getting the same error.

Open the log file

```
11/20/2017 10:42:58 PMtime="2017-11-21T03:42:58Z" level=info msg="Starting Rancher External DNS service v0.7.8"
11/20/2017 10:42:58 PMtime="2017-11-21T03:42:58Z" level=info msg="Configured Route 53 with hosted zone test.expedia.com."
11/20/2017 10:42:58 PMtime="2017-11-21T03:42:58Z" level=info msg="Healthcheck handler is listening on :1000"
11/20/2017 10:43:30 PMpanic: runtime error: invalid memory address or nil pointer dereference
11/20/2017 10:43:30 PM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9dec2b]
11/20/2017 10:43:30 PMgoroutine 1 [running]:
11/20/2017 10:43:30 PMgithub.com/rancher/external-dns/providers/route53.(*Route53Provider).GetRecords(0xc420116e00, 0x0, 0x0, 0x0, 0x0, 0x0)
11/20/2017 10:43:30 PM	/go/src/github.com/rancher/external-dns/providers/route53/route53.go:228 +0x56b
11/20/2017 10:43:30 PMmain.EnsureUpgradeToStateRRSet(0x0, 0xbdaf68)
11/20/2017 10:43:30 PM	/go/src/github.com/rancher/external-dns/external-dns.go:182 +0x6d
11/20/2017 10:43:30 PMmain.main()
11/20/2017 10:43:30 PM	/go/src/github.com/rancher/external-dns/main.go:102 +0xf8
```

The issue occurs on the line 228 in route53.go which is

```
223     dnsRecord := utils.DnsRecord{
224            Fqdn:    *rrSet.Name,
226            Records: records,
227           Type:    *rrSet.Type,
228            TTL:     int(*rrSet.TTL),
        }
```

**Comment by superseb** [comment]
Are you using `AWS_ACCESS_KEY`/`AWS_SECRET_KEY` or IAM role, and does it have the right permissions for the configured zone name/id?

**Comment by superseb** [comment]
Debug logging:

```
11/22/2017 6:17:27 AMtime="2017-11-22T11:17:27Z" level=debug msg="Fqdn: RECORD."
11/22/2017 6:17:27 AMtime="2017-11-22T11:17:27Z" level=debug msg="records: [This resource record set includes an attribute that is unsupported on this Route 53 endpoint. Please consider using a newer endpoint or a tool that does so.]"
11/22/2017 6:17:27 AMtime="2017-11-22T11:17:27Z" level=debug msg="Type: CNAME"
11/22/2017 6:17:27 AMpanic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by deniseschannon** [comment]
Availabe with template `v0.7.9` for Route 53

**Comment by sangeethah** [comment]
Able to reproduce this issue when testing with v1.6.12 and rancher/external-dns:v0.7.7

``
12/15/2017 1:54:33 PMtime="2017-12-15T21:54:33Z" level=info msg="Starting Rancher External DNS service v0.7.7"
12/15/2017 1:54:34 PMtime="2017-12-15T21:54:34Z" level=info msg="Configured Route 53 with hosted zone sangee-test.com."
12/15/2017 1:54:34 PMtime="2017-12-15T21:54:34Z" level=info msg="Healthcheck handler is listening on :1000"
12/15/2017 1:54:34 PMpanic: runtime error: invalid memory address or nil pointer dereference
12/15/2017 1:54:34 PM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9deb2b]
12/15/2017 1:54:34 PM
12/15/2017 1:54:34 PMgoroutine 1 [running]:
12/15/2017 1:54:34 PMgithub.com/rancher/external-dns/providers/route53.(*Route53Provider).GetRecords(0xc4200a5e60, 0x0, 0x0, 0x0, 0x0, 0x0)
12/15/2017 1:54:34 PM	/go/src/github.com/rancher/external-dns/providers/route53/route53.go:228 +0x56b
12/15/2017 1:54:34 PMmain.EnsureUpgradeToStateRRSet(0x0, 0xbdaf60)
12/15/2017 1:54:34 PM	/go/src/github.com/rancher/external-dns/external-dns.go:182 +0x6d
12/15/2017 1:54:34 PMmain.main()
12/15/2017 1:54:34 PM	/go/src/github.com/rancher/external-dns/main.go:102 +0xf8
```


This issue is not seen when testing with v1.6.13-rc3 and rancher/external-dns:v0.7.9.
Able to bring up route53 service successfully. Able to see route 53 entries being programmed for services with exposed ports.
