### ISSUE TITLE
Rancher auth service binary fails to run

### ISSUE THREAD

**Issue by atheoscommune** [rancher/rancher#10372]
**Rancher versions:**
rancher/server:alpha 2.0

**Docker version: Docker version 1.12.6, build 78d1802**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.10.0-38-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
1) clone rancher-auth-service
2) checkout tag v0.4.2 or remain in master
2) build binary using godep/ go build
3) copy the created binary to container to usr/bin and usr/local/bin and restart container

**Results:**
rancher-auth-service: error while loading shared libraries: libxmlsec1-openssl.so.1: cannot open shared object file: No such file or directory
 in docker logs

**Comment by atheoscommune** [comment]
I did it after running trash command.

**Comment by superseb** [comment]
In the `Dockerfile.dapper` file you can see how you can build it yourself. There is also a `Makefile` where you can use `make` to build a complete binary. Let me know if this does not work.

**Comment by princerachit** [comment]
Thanks @superseb. `make` worked like a charm. Maybe the README.MD should be update.

**Comment by princerachit** [comment]
Thanks @superseb. `make` worked like a charm. Maybe the README.MD should be update.

**Comment by atheoscommune** [comment]
Thanks @superseb. `make` worked like a charm. Maybe the README.MD should be update.
