### ISSUE TITLE
[Rancher API] Upgrade Container (with secrets)

### ISSUE THREAD

**Issue by martin-kieliszek** [rancher/rancher#10378]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck:0.33
ipsec: rancher/net:v0.11.9 and rancher/net:holder
network-services: rancher/metadata:v0.9.4 and rancher/network-manager:v0.7.8
scheduler: rancher/scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
docker --version
Docker version 17.06.0-ce, build 02c1d87

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
# uname -r
3.10.0-514.el7.x86_64

# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Enable secrets (rancher/storage-secrets:v0.6.8)
2. Create a service container with any image.
3. Add secrets into this service container config
4. After it is deployed and active get postman or something else that is capable of hitting the rancher apis on /v2-beta/ (ensure you've obtained an API KEY and API SECRET from top right hand side of rancher)

5. NOW - attempt to upgrade the service completely via API as opposed to front end.
You will find that the problem is the upgrade is rejected with 422 response code. THIS DOES NOT HAPPEN IF I remove the secrets from the service config.

I use a python wrapper to upgrade containers. I have not encountered a problem before until one of my containers used secrets.
```
# Python exerpt that works fine for all containers except ones with secrets
def upgrade_service(
        self,
        id,
        batch_size = 1,
        interval = 2000,
        full_upgrade = True,
        try_finish = True,
        safe = True,
        launch_config = None
    ):
        url = self.base_url + "services/%s?action=upgrade" % id
        if try_finish: self._service_try_finish(id)
        if launch_config == None: launch_config = self._service_launch_config(id)
        if safe and not self._service_active(id):
            raise appier.OperationalError(
                message = "Service is currently not ready for upgrade"
            )
        contents = self.post(
            url,
            data_j = dict(
                inServiceStrategy = dict(
                    batchSize = batch_size,
                    intervalMillis = interval,
                    fullUpgrade = full_upgrade,
                    launchConfig = launch_config,
                    secondaryLaunchConfigs = []
                )
            )
        )
        data = contents["data"]
        return data

```
**Results:**
```
{u'code': 422, u'message': u'[422] Problem in the HTTP request', u'session': u'162bc9dc2c367a6ecb9fc7f7cdd47faeeb6d903c1b0d3b42695a496611f04f40', u'name': u'HTTPError', u'result': u'error'}
```

**Comment by vincent99** [comment]
Please record and post the complete HTTP request and response.  Error responses have a body with more information which you're not showing (or, presumably, looking at).
