### ISSUE TITLE
Possible to deploy Rancher Server on an existing Kubernetes cluster

### ISSUE THREAD

**Issue by piwi91** [rancher/rancher#10370]
Is it possible to deploy a Rancher Server Cluster on an existing Kubernetes Cluster? I want to use Rancher to simplify the Kubernetes management, but I don't want Rancher to install the Kubernetes Cluster itself.

**Comment by superseb** [comment]
This is something that is in 2.0, please see all details here http://rancher.com/rancher2-0/ and here http://rancher.com/docs/rancher/v2.0/en/faq/. Try it out and let us know what you think!

**Comment by piwi91** [comment]
@superseb Don't know if you understood my question because I can't find it in the FAQ or in docs about 2.0. I want to deploy Rancher on top of an existing Kubernetes Cluster. How will this work, because Rancher Server has an embedded Kubernetes master.
