### ISSUE TITLE
Add FAQ on localhost reference in /etc/resolv.conf

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10371]
Add explanation to Agent FAQ when following log message is seen:

```ERROR: DNS Checking loopback IP address 127.0.0.0/8, localhost or ::1 configured as the DNS server on the host file /etc/resolv.conf, can't accept it```

https://docs.docker.com/engine/installation/linux/linux-postinstall/#dns-resolver-found-in-resolvconf-and-containers-cant-use-it

**Comment by jwausle** [comment]
Check ranger [docu](https://rancher.com/docs/rancher/v1.6/en/faqs/agents/) for details.
