### ISSUE TITLE
Ipsec-router pending restart.

### ISSUE THREAD

**Issue by pdhung** [rancher/rancher#10385]
Hi everybody,

I am trying to install Rancher 2.0 preview, but I got a problem regarding the ipsec-router sidekick. I managed to start Rancher server, then add custom hosts, but the ipsec-router didn't work, and the healthcare services as well.

_**core-services-ipsec-router log:**_
+ export CHARON_PID_FILE=/var/run/charon.pid
+ CHARON_PID_FILE=/var/run/charon.pid
+ rm -f /var/run/charon.pid
+ GCM=false
+ (( i=0 ))
+ (( i<6 ))
+ ip xfrm state add src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp mode tunnel aead 'rfc4106(gcm(aes))' 0x0000000000000000000000000000000000000001 128 sel src 1.1.1.1 dst 1.1.1.1
+ GCM=true
+ ip xfrm state del src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp
+ break
+ '[' false == true ']'
+ DEBUG=
+ mkdir -p /etc/ipsec
+ '[' true = true ']'
+ curl -s -f http://169.254.169.250/2016-07-29/self/service/token
[repeat]

_**core-services-healthcheck logs:**_
level=fatal msg="Get http://169.254.169.250/2015-12-19/version: dial tcp 169.254.169.250:80: getsockopt: no route to host"
[repeat]

**Rancher versions:**
rancher/server: 2.0 preview
rancher/agent: 2.0 alpha4 preview

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
   - status: pending restart
ipsec: rancher/net:v0.12.3 
    - status: ipsec starts, ipsec-router: pending restart (error)
network-services: cni rancher/net:v0.12.3

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6 upstream
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 3.10.0-514.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM

**Firewall**
sudo firewall-cmd --list-ports
443/tcp 10250/tcp 10255/tcp 30000-32767/tcp 500/udp 4500/udp 42/tcp

**docker info**
Containers: 10
 Running: 8
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 7.292 GB
 Data Space Total: 40.8 GB
 Data Space Available: 33.51 GB
 Metadata Space Used: 2.142 MB
 Metadata Space Total: 427.8 MB
 Metadata Space Available: 425.7 MB
 Thin Pool Minimum Free Space: 4.079 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: DEFR4APP340
ID: OIF5:NAZ3:QEEX:BPSA:MJT4:5ILC:RJSA:F7T5:U2B3:WZ6Y:QZWG:FUYY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by superseb** [comment]
What does metadata log say? And network-manager?

Can you share full output of `uname -r` and `docker info`

**Comment by pdhung** [comment]
Hi @superseb 
Attached is the metadata log.
[metadata.log](https://github.com/rancher/rancher/files/1495384/metadata.log)

**Comment by pdhung** [comment]
I have tried with **ranger-agent alpha2** and **alpha3**, it still has the same error.
@superseb , could you please remove the needed information tag?

**Comment by superseb** [comment]
Seems to be related to firewalld, can you try:

```
firewall-cmd --permanent --zone=trusted --change-interface=docker0
firewall-cmd --reload
```

**Comment by pdhung** [comment]
Thanks a lot @superseb ! It works now!

Just a question: I have opened the necessary firewall ports:

sudo firewall-cmd --list-ports
443/tcp 10250/tcp 10255/tcp 30000-32767/tcp 500/udp 4500/udp 42/tcp

Why didn't it work then? What is the difference to your command?

**Comment by superseb** [comment]
Ok great, closing this out. You can read a whole chunk of the problem here: https://github.com/moby/moby/issues/16137

Basically `firewalld` uses `iptables` but also introduced zones, which needs specific configuration regarding to Docker.
