### ISSUE TITLE
Environment variables get cleared/reset when an upgrade is done

### ISSUE THREAD

**Issue by nimboya** [rancher/rancher#10386]
**Rancher versions:**
rancher/server: v1.6.8
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:**

**Comment by superseb** [comment]
Unable to reproduce this on `v1.6.11`, can you share steps taken/definitions used and try if it still happens on v1.6.11?

**Comment by nimboya** [comment]
1. Create a service with certain environment variables
2. Upgrade and add new environment variables
3. Allow automated deployment to make an update.

PS: Automated deployment from: https://github.com/phedoreanu/rancher-auto-redeploy
Dockherhub: phedoreanu/rancher-auto-redeploy

**Comment by superseb** [comment]
Not completely sure what happens in `rancher-auto-redeploy` but it seems like it's using old information to upgrade the service? Can you reproduce by using manual steps?

**Comment by superseb** [comment]
Closing as stale.
