### ISSUE TITLE
Loadbalancer logs "CATTLE_ACCESS_KEY is not set, skipping init of Rancher LB provider" upon startup

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10380]
**Rancher versions:**
rancher/server: v1.6.11

**Infrastructure Stack versions:**
lb-service-haproxy: v0.7.15

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Add a host
1. Add stack with a service
1. Add lb pointing to that service

**Results:**
Log will show

```
21/11/2017 11:37:27time="2017-11-21T10:37:27Z" level=info msg="CATTLE_ACCESS_KEY is not set, skipping init of Rancher LB provider"
```

Haven't seen any impact, just the logging should be fixed.

**Comment by KingsDevelopment** [comment]
+1 ran into the same problem

**Comment by superseb** [comment]
@KingsDevelopment Do you have issues running the LB? As this should only be a log message, not actually cause impact as far as I could see.

**Comment by KingsDevelopment** [comment]
No it works fine, but stays on "initializing"

**Comment by superseb** [comment]
What does the rest of the log say? Stuck on `Initializing` is not correct, or there is something else wrong inside the Infrastructure stacks?

**Comment by KonstantinCodes** [comment]
Having the same problem here!

**Comment by hugohenley** [comment]
Same here: 
05/12/2017 23:30:03time="2017-12-05T22:30:03Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"

05/12/2017 23:30:03time="2017-12-05T22:30:03Z" level=info msg="CATTLE_ACCESS_KEY is not set, skipping init of Rancher LB provider"

**Comment by superseb** [comment]
Update on this, the logging is confusing (hence this ticket), but shouldn't break any loadbalancer functionality. It should start like:

```
06/12/2017 11:02:56time="2017-12-06T10:02:56Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
06/12/2017 11:02:56time="2017-12-06T10:02:56Z" level=info msg="CATTLE_ACCESS_KEY is not set, skipping init of Rancher LB provider"
06/12/2017 11:02:562d011157-9474-4162-819d-365e60bc4c3dtime="2017-12-06T10:02:56Z" level=info msg="Starting Rancher LB service"
06/12/2017 11:02:57time="2017-12-06T10:02:57Z" level=info msg="LB controller: rancher"
06/12/2017 11:02:57time="2017-12-06T10:02:57Z" level=info msg="LB provider: haproxy"
06/12/2017 11:02:57time="2017-12-06T10:02:57Z" level=info msg="starting rancher controller"
06/12/2017 11:02:57time="2017-12-06T10:02:57Z" level=info msg="Healthcheck handler is listening on :10241"
06/12/2017 11:02:58time="2017-12-06T10:02:58Z" level=info msg="Initializing event router" workerCount=250
06/12/2017 11:02:58time="2017-12-06T10:02:58Z" level=info msg="Connection established"
06/12/2017 11:02:58time="2017-12-06T10:02:58Z" level=info msg="Starting websocket pings"
06/12/2017 11:02:58time="2017-12-06T10:02:58Z" level=info msg=" -- starting haproxy\n * Starting haproxy haproxy\n   ...done.\n"```

If it's stuck in Initializing, usually the healthcheck containers are not able to healthcheck the loadbalancer container and it will be deleted and re-created over and over. You can check this by using `View Logs` on the healthcheck containers and see what they report.

In case of @hugohenley , the healthcheck containers had $CATTLE_URL set to an old value, so the healthcheck containers got stuck. Deleting the heathcheck containers helped here.

It's better to file a new issue describing your problem, as this is an issue for removing the confusing logging, not an actual functional problem.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
