### ISSUE TITLE
Cattle does not allow for custom user iptable rules

### ISSUE THREAD

**Issue by BastianHofmann** [rancher/rancher#10387]
**Rancher versions:**
rancher/server: 1.6.11
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.2.0
network-services: 0.2.7
scheduler: 0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 19
 Running: 19
 Paused: 0
 Stopped: 0
Images: 26
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-101-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.795GiB
Name: censored
ID: censored
Docker Root Dir: /mnt/vdb1/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3
4.4.0-101-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

- `iptables -I FORWARD 1 -i eth0 -m set ! --match-set someset src -j DROP`
- wait some time

**Results:**

The jump CATTLE_FORWARD chain is now again on the top of the forward chain. This was introduced with issue #8978. But a similar issue existed before this change was introduced.
This behaviour of the iptable chains makes it impossible to add custom iptable rules, because all packets are accepted before they reach the custom user rules.
What we really need is a CATTLE_USER chain similar to the DOCKER_USER chain provided by Docker. This chain should always be in front of the other CATTLE_* chains.

**Comment by BastianHofmann** [comment]
Could I get some feedback on if and when this is fixed?

**Comment by maltyxx** [comment]
me too https://github.com/rancher/rancher/issues/11242

**Comment by conet** [comment]
I would also love having this fixed otherwise there is no easy way to adopt rancher in a mixed environment where access to services should be controlled by a firewall.

**Comment by superseb** [comment]
@leodotcloud Can you take a look?

**Comment by leodotcloud** [comment]
I think this is a good feature request. May be we can provide PRE and POST hooks too. 

CC: @deniseschannon.

**Comment by alwinmarkcf** [comment]
@leodotcloud  @deniseschannon As we had the same problem, which become critical, we had to monkey patch the plugin-manager, to move on. As i couldn't find any Contribution guidelines I did the usual stuff so I hope this is ok.

**Comment by CrowdfoxMKL** [comment]
Hi, my colleague just made pull request "fixing" this issue, as we ran in the same problem.
It can be found in the plugin-manager repo:
https://github.com/rancher/plugin-manager/pull/123

**Comment by leodotcloud** [comment]
I will look into this issue.

**Comment by marvinwankersteen** [comment]
Any news on this? In my opinion this is a must have feature. I use shorewall and I was wondering, why my rule is ignored. Before #8978, it was possible to start docker after shorewall.
Without this feature it's also not possible to use fail2ban.

**Comment by rossigee** [comment]
+1 for this. I also have a situation where we need to add custom iptables rules, but are unable to because Rancher just keeps overriding them.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
