### ISSUE TITLE
Couldn't bring up network: couldn't find any CNI network configurations

### ISSUE THREAD

**Issue by emichaf** [rancher/rancher#10383]
**Rancher versions:**
rancher/agent: 1.2.6
Rancher: v1.6.10
Cattle: v0.183.22
User Interface: v1.6.23
Rancher CLI: v0.6.4
Rancher Compose: v0.12.5

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.7.7-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7.4 (3.10.0)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Results:**
The following components are not starting, see error msg below!
ipsec
etcd
kubectl-shell
kubernetes
rancher-kubernetes-auth

Error message:
Expected state running but got error: Couldn't bring up network: couldn't find any CNI network configurations

**Comment by superseb** [comment]
It sounds like https://github.com/rancher/rancher/issues/10033, are you on v1.6 or on the 2.0 preview? And if you are on v1.6, can you share full details on OS/kernel/Docker version?

**Comment by emichaf** [comment]
Version: v1.6 
Docker : 1.12.6
OS/kernel: RHEL 7.4 (3.10.0)

**Comment by superseb** [comment]
Can you post the output of `docker info`?

**Comment by emichaf** [comment]
Containers: 35
 Running: 20
 Paused: 0
 Stopped: 15
Images: 21
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: vg00-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 6.823 GB
 Data Space Total: 12.38 GB
 Data Space Available: 5.559 GB
 Metadata Space Used: 2.994 MB
 Metadata Space Total: 100.7 MB
 Metadata Space Available: 97.67 MB
 Thin Pool Minimum Free Space: 1.238 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: null bridge host overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 31.26 GiB
Name: xxxxxxxxxxx.xxxxxx.xxxxxxxxxx.xx
ID: xx.xx.xx.xx...
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Insecure Registries:
 127.0.0.0/8
Registries: registry.access.redhat.com (secure), docker.io (secure)

**Comment by superseb** [comment]
Ok couple of things to check:

Can you share output of this? That will make sure that there are no routing issues for metadata.
```
#!/bin/bash
curl -s $RANCHER_URL/containers | jq '.data[] | select(.data.dockerContainer.Labels["io.rancher.stack_service.name"] == "network-services/metadata") | .primaryIpAddress'
```
You can also check the response of `curl 169.254.169.250/latest/self/host/uuid` inside the network-manager container, it should return the same UUID in every request.

Also, logs from metadata/network-manager would help.

**Comment by emichaf** [comment]
Added "v1" in URI

curl -s $RANCHER_URL/v1/containers | jq '.data[] | select(.data.dockerContainer.Labels["io.rancher.stack_service.name"] == "network-services/metadata") | .primaryIpAddress'

Output:
"172.17.0.3"
"172.17.0.6"
"172.17.0.3"

In container (image rancher/network-manager:v0.8.6)
curl 169.254.169.250/latest/self/host/uuid

Output:
curl: (7) Failed to connect to 169.254.169.250 port 80: Connection refused

**Comment by superseb** [comment]
Can you supply logging of metadata

**Comment by emichaf** [comment]
I'm new to Rancher, how to get the metadata log?

**Comment by superseb** [comment]
Select metadata container, `View Logs`

**Comment by emichaf** [comment]
Alot of:
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Applied http://xxxxx.xx:8080/v1/configcontent/metadata-answers?client=v2&requestedVersion=124065?version=124065-4f3c5c96fb170da7fa8781d4ac55192c"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Download and reload in: 50.028734ms"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Update requested for version: 124066"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Downloaded in 13.926136ms"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Generating and reloading answers"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Generating answers"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Generated and reloaded answers"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Applied http://xxxxx.xx:8080/v1/configcontent/metadata-answers?client=v2&requestedVersion=124066?version=124067-4f3c5c96fb170da7fa8781d4ac55192c"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Download and reload in: 40.83716ms"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Update requested for version: 124068"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Downloaded in 26.164688ms"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Generating and reloading answers"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Generating answers"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Generated and reloaded answers"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="http://xxxxx.xx:8080/v1/configcontent/metadata-answers?client=v2&requestedVersion=124068?version=124068-4f3c5c96fb170da7fa8781d4ac55192c"
11/22/2017 2:29:55 PMtime="2017-11-22T13:29:55Z" level=info msg="Download and reload in: 44.875515ms"
11/22/2017 2:29:56 PMtime="2017-11-22T13:29:56Z" level=info msg="Update requested for version: 124069"
11/22/2017 2:29:56 PMtime="2017-11-22T13:29:56Z" level=info msg="Downloaded in 28.581655ms"
11/22/2017 2:29:56 PMtime="2017-11-22T13:29:56Z" level=info msg="Generating and reloading answers"
11/22/2017 2:29:56 PMtime="2017-11-22T13:29:56Z" level=info msg="Generating answers"
11/22/2017 2:29:56 PMtime="2017-11-22T13:29:56Z" level=info msg="Generated and reloaded answers"..............

**Comment by superseb** [comment]
Ok ping me on Rancher Users Slack and I'll take a look (https://slack.rancher.io)

**Comment by PaulKruger** [comment]
Did this come to resolution?  I'm having the same issue.

**Comment by superseb** [comment]
I don't think there was a response on this, are you running the same stack (v1.6.10 on RHEL 7.4)?

Do you have `firewalld` running?

**Comment by PaulKruger** [comment]
No, I'm running on Centos.  I've tried various versions of docker/rancher all to no avail.  The only thing I can isolate so far seems to be that the problem occurs more frequently when the server/agent are on the same machine.

**Comment by HcgRandon** [comment]
Also getting this on 1.6.14

**Comment by superseb** [comment]
Please report back or ping me on Rancher Users Slack so we can troubleshoot this

**Comment by elfrinjo** [comment]
Hi, was there additional activity on this issue on slack? I am currently expieriencing somthing similar with rancher 1.6.17, CentOS 7 and the Oracle Cloud Infrastructure.

**Comment by mjaverto** [comment]
Experiencing this with 1.6.18 and Rancher OS 1.3.0 in a brand new Rancher environment.
