### ISSUE TITLE
problems setting up ceph

### ISSUE THREAD

**Issue by josrom** [rancher/rancher#10388]
Following up this tutorial (https://crondev.com/kubernetes-persistent-storage-ceph/) I get the kubernetes storage class setup I do a claim and that gives me a persistant storage all green so far. But when I try to mount the claim into a pod I get this error....
On the other hand I need to do setup the keyring for the users manually on all the kubelets...

cd /etc/ceph
rm ceph.client.kube.keyring
cat > ceph.client.kube.keyring <<EOF
[client.kube]
    key = AQAWJhRaEKXpCxAA5xcQthQ7xJyHCCmrDiAFfA==
    caps mon = "allow r"
    caps osd = "allow rwx pool=kube"
EOF

And I get this error:
MountVolume.SetUp failed for volume "pvc-a2754739-cf6f-11e7-a7a5-02e985942c89" : rbd: map failed exit status 2 2017-11-22 12:35:53.503224 7f0753c66100 -1 did not load config file, using default settings. libkmod: ERROR ../libkmod/libkmod.c:586 kmod_search_moddep: could not open moddep file '/lib/modules/4.9.45-rancher/modules.dep.bin' modinfo: ERROR: Module alias rbd not found. modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.45-rancher/modules.dep.bin' modprobe: FATAL: Module rbd not found in directory /lib/modules/4.9.45-rancher rbd: failed to load rbd kernel module (1) rbd: sysfs write failed In some cases useful info is found in syslog - try "dmesg | tail" or so. rbd: map failed: (2) No such file or directory

I think is various problems on rancher but not being able to mount the modules is a blocker...

Component | Version
-- | --
Rancher | v1.6.11
Cattle | v0.183.30
User Interface | v1.6.30
Rancher CLI | v0.6.5
Rancher Compose | v0.12.5

**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by superseb** [comment]
Seems like we are missing the volume `/lib/modules:/lib/modules` in the kubelet definition, can you upgrade your service using this volume and check?

**Comment by mpsnp** [comment]
@superseb I've checked, indeed, addition of this mount to kubelet solves the issue.

**Comment by adalga** [comment]
@mpsnp How could you add volume mount to kubelet ? I have same problem. I used rke for deployment and I don't know what I need to do for adding /lib/modules to my kubelet. Can you help me ?

**Comment by mpsnp** [comment]
@adalga You need to go to "Infrastructure Stacks", select "kubelet" in kubernetes stack, then click "Upgrade" and add `/lib/modules:/lib/modules` volume.

**Comment by rdissauer** [comment]
@mpsnp There is no "Infrastructure Stacks" -> "kubelet" in latest 2.0.7 rancher.

Can anyone please give me a hint how to solve this issue in 2.0.7? I'm running rancheros 1.4 if this is an issue

**Comment by sergii-bond** [comment]
@rdissauer please see how to do mount in the newer versions of rancher [here](https://github.com/rancher/rancher/issues/13774#issuecomment-421633426).

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by shubb30** [comment]
This problem still exists in Rancher 2.x, so this should be re-opened.

I am using RKE to create a Kubernetes 1.11.3 cluster, and then imported into Rancher 2.1.0.
If I try to mount a CEPH volume, I get the following errors:

```
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        2m13s (x7 over 2m17s)  default-scheduler        pod has unbound PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled               2m12s                  default-scheduler        Successfully assigned scott-test/ubuntu5-774467c65-7htgf to 10.199.32.24
  Normal   SuccessfulAttachVolume  2m12s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-f91a1bf8-dc99-11e8-b5cb-00505698ef5e"
  Warning  FailedMount             117s                   kubelet, 10.199.32.24    MountVolume.WaitForAttach failed for volume "pvc-f91a1bf8-dc99-11e8-b5cb-00505698ef5e" : rbd: map failed exit status 2, rbd output: 2018-10-30 23:17:50.903950 7feedb9e0100 -1 did not load config file, using default settings.
2018-10-30 23:17:50.907113 7feedb9e0100 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.kube.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
libkmod: ERROR ../libkmod/libkmod.c:586 kmod_search_moddep: could not open moddep file '/lib/modules/4.4.0-138-generic/modules.dep.bin'
modinfo: ERROR: Module alias rbd not found.
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-138-generic/modules.dep.bin'
modprobe: FATAL: Module rbd not found in directory /lib/modules/4.4.0-138-generic
rbd: failed to load rbd kernel module (1)
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail" or so.
rbd: map failed: (2) No such file or directory
  Warning  FailedMount  116s  kubelet, 10.199.32.24  MountVolume.WaitForAttach failed for volume "pvc-f91a1bf8-dc99-11e8-b5cb-00505698ef5e" : rbd: map failed exit status 2, rbd output: 2018-10-30 23:17:51.639525 7fbf1cde9100 -1 did not load config file, using default settings.
```

If I add a bind mount for `/lib/modules:/lib/modules` to kubelet, then CEPH works fine.

**Comment by loganhz** [comment]
You can find how to bind it in 2.0 via https://github.com/rancher/rancher/issues/13774#issuecomment-427899206
Please raise a new ticket if you would like RKE bind it by default.
