### ISSUE TITLE
didn't upgrade image's tag

### ISSUE THREAD

**Issue by jinghuaz** [rancher/rancher#10393]
**Rancher versions:**
rancher/server:1.6.10
rancher/cli:0.6.5
I modify docker-compose.yml image: {**tag**},i only modify tag-version，then i use rancher up --force-upgrade or conifrm-upgrade，But the tag is old,didn't change on rancher server.
so,how can i change image:tag,what patament in cli.

"rancher",
                                           "--env", str.upper(self.environment),
                                           "up",
                                           "--force-upgrade",
                                           "--batch-size", self.batchSize,
                                           "--interval", self.interval,
                                           "--rancher-file", 'rancher-compose.yml',
                                           "--env-file", 'env.yml',
                                           "--file", 'docker-compose.yml',
                                           "--stack", self.stack,
                                           "-d"

**Comment by superseb** [comment]
You are probably looking for `--upgrade`, see all docs here: http://rancher.com/docs/rancher/v1.6/en/cli/commands/#rancher-up-reference.

Let me know if this doesn't work for you.

**Comment by jinghuaz** [comment]
Hi superseb:
  thank you for your answer, i have know doesn't work reason: i'm not should use --force-upgrade first,i should used --upgrade then used --force-upgrade for ture.
