### ISSUE TITLE
Rancher preview not working on Ubuntu in VirtualBox

### ISSUE THREAD

**Issue by dinkarthakur** [rancher/rancher#10396]
**Rancher versions:**
rancher/server:preview

**Docker version:**
17.09.0-ce, build afdb6d4

**Operating system and kernel:**
Ubuntu 16.04 LTS

**Type/provider of hosts:**
VirtualBox

**Setup details:**
single node rancher

install rancher by using 
```
sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview
```

result:
```
HTTP ERROR 403

Problem accessing /. Reason:

    Forbidden

Powered by Jetty://**
```

**Comment by superseb** [comment]
* What network adapters are attached to the VM?
* Are you in a proxy environment?
* Any logging in the `rancher/server` container when you try to reach it?
* Can you reach it locally? (`curl localhost:8080`)

**Comment by dinkarthakur** [comment]
Network Adapter: Bridged Adapter
There is no proxy. 
Yes, it logs about not able to download plugins from github
No, I was not able to reach locally.

**Comment by sdupont** [comment]
Hi @dinkarthakur !

I experienced same problem last week (Ubuntu 16.04 on Virtual Box).
To fix the 403 error, you have to pass the proxy environment variables to the container as explained here : [https://jackiechen.org/2017/10/09/http-error-403-of-rancher-server-2-0-preview/](url)

I did it and i don't have 403 anymore, but now i have an issue about the catalog templates. Tell me if you have the same.

Simon.

**Comment by dinkarthakur** [comment]
Hi @sdupont (Simon) 
I don't have any proxy in place its just Host and Virtual Box, There is no proxy in place. 

Regards
Dinkar

**Comment by superseb** [comment]
Can you try using the `rancher/server:v2.0.0-alpha10` image?

**Comment by sdupont** [comment]
Hi @superseb ,

I try this right know and let you know.

Thanks,

Simon.

**Comment by sdupont** [comment]
Ok Rancher server is up using `rancher/server:v2.0.0-alpha10` image (no 403 anymore).
But I can't add host and i have this message : 

> Upgrade Environment Rancher includes changes that require upgrading the existing system services and load balancer containers. Only an owner of this environment or an administrator can perform the upgrade.

It looks to be an issue about my docker `version 1.13.1` : [link](http://rancher.com/docs/rancher/latest/en/hosts/#supported-docker-versions).
I can try to downgrade my docker version to `1.12.3 ` which supports Kubernetes.

Simon

**Comment by sdupont** [comment]
@superseb I tried `rancher/server:v2.0.0-alpha10` image with Docker version 1.12.3 and 1.12.6 but i can't add host.

> Upgrade Environment Rancher includes changes that require upgrading the existing system services and load balancer containers. Only an owner of this environment or an administrator can perform the upgrade.

**Comment by aderumier** [comment]
Hi, I had same problem with 403 forbidden.
The problem was a dns problem, as rancher try to use google dns 8.8.8.8 and it blocked on my infra.
on my host, /etc/resolv.conf is 127.0.0.1 (because I have a local cache), so I think docker fallback on google dns in this case.

I have fixed it with adding

/etc/docker/daemon.json

{
   "dns": ["X.X.X.X"]
}


I'm using debian stretch with docker-ce 17.09.

(note that setting dns in /etc/default/docker on debian is not working anymore with systemd)

**Comment by sdupont** [comment]
Hi @aderumier .

thanks for your reply, it's fixed now.

Other question, did you have any Load Balancing issue with Rancher 2 ?
Cause i have a simple stack with two services, one front and one LB. I set the LB like i used to do with Rancher 1 and I face to a 503 error when I try to access my app :

> 503 Service Unavailable. No server is available to handle this request.

I saw many post about LB and 503 error but it didn't help.

Any idea ?

**Comment by aderumier** [comment]
Loadbalancer is working fine.

I had another problem, with container could'nt go outside their network.
This was because my host local cache, was listening to 0.0.0.0:53, and rancher dns service could'nt start (and other kubernetes services, which manage iptables nat rules).

Are all containers in the system environment ok ?

**Comment by sdupont** [comment]
@aderumier My system containers look OK. I'm using same OS and Docker versions than you but the `rancher/server:v2.0.0-alpha10` image.

**Comment by deniseschannon** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM&t=4s) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!
