### ISSUE TITLE
External Network

### ISSUE THREAD

**Issue by TomH34** [rancher/rancher#10391]
Is it possible to use external networks from docker compose in Rancher ?   
I am trying and it seems it's ignoring the external network part from my docker-compose . 

(From issue https://github.com/rancher/rancher/issues/5715 it's not clear whether this is possible at this moment)

Rancher Version:
{
  "major": "1",
  "minor": "2+",
  "gitVersion": "v1.2.0-rancher-1",
  "gitCommit": "ed6532f975cff184196dbe214de8fa0198b415ef",
  "gitTreeState": "clean"
}

**Comment by superseb** [comment]
No, it's not supported. The referenced ticket is to implement it and it's still open but most likely not going to happen.

Also, v1.2.0 is almost a year old.
