### ISSUE TITLE
when i add cmd in dockerfile, upgrade failed got expected error

### ISSUE THREAD

**Issue by efvhi** [rancher/rancher#10394]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`localauth` |
|Orchestration|`Cattle`|
|Route|`service.new`|

**Comment by superseb** [comment]
More steps to reproduce please, `Dockerfile` is build time, does it work on local Docker? What steps are you taking to deploy and upgrade on Rancher?

**Comment by efvhi** [comment]
sorry, i made a stupid mistake , the script by cmd executed just done and docker exited by default,  i just thought it would work  like " run -it . /bin/bash ",  sorry for my mistake
