### ISSUE TITLE
Request to add the "retain_ip" configuration for LB infrastructure service in UI

### ISSUE THREAD

**Issue by anzersy** [rancher/rancher#10399]
**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by anzersy** [comment]
Few users were going to asking for more opening configuration items of Rancher infrastructure service like retain_ip of load balancer.

Description of requirement:
Users was preferred to get a fixed ip for each LB service container while they did not want to discovery service by DNS.

There is a convenient way to implement this feature currently, update the rancher-compose file of load balancer stack and set the value of retain_ip field to "true", however we have to update manually rather than configure through UI. Could Rancher provide one more better way to do this? Thanks a lot.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
