### ISSUE TITLE
network-manager watchers start with sleeping instead of executing syncs

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10392]
**Rancher versions:**
rancher/server: v1.6.11

**Infrastructure Stack versions:**
network-services: v0.2.7 (network-manager:v0.7.18)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Add host to environment

**Results:**
1. See healthchecks fail to reach $CATTLE_URL and be re-created 2/3 times before the defaultsyncinterval on iptablessync (120 seconds) has passed before it is marked as active.
 
healthcheck container will log:
```
Get $CATTLE_URL: dial tcp x.x.x.x: i/o timeout
```

**Comment by leodotcloud** [comment]
Related: https://github.com/rancher/rancher/issues/10319

**Comment by leodotcloud** [comment]
Fixed with `network-services:v0.2.8, network-manager:v0.7.19`

**Comment by sangeethah** [comment]
Tested with Rancher versions:  build from v1.6 branch
Infrastructure Stack versions:
network-services: v0.2.8 (network-manager:v0.7.19)
When new host gets added , health check containers gets to "healthy" state quickly. There is no logs relating to not being able to reach $CATTLE_URL  in the health check container logs ( like what is seen with v1.6.12 ).
