### ISSUE TITLE
Rancher Server won't start on Ubuntu 16.04 instance in AWS

### ISSUE THREAD

**Issue by pcgeek86** [rancher/rancher#10398]
### Overview

I'm trying to run Rancher Server in a single-container / non-HA scenario, on Ubuntu 16.04 on an AWS EC2 instance, and am running into some issues getting it to complete initialization and start running.

My goal is to simply use Rancher to set up a Kubernetes cluster.

**Rancher versions:**
rancher/server: `sha256:6c4395b5515a99aa44c57a801d78f9e441ee30993921ff8b68c39b58b68a9404`
rancher/agent: 

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: bridge
scheduler: Docker
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)** 

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1041-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-172-31-28-155
ID: C3ZH:BEHY:6SQ6:DJCA:7UAC:EKMQ:MCHS:PKIC:6CFH:C5TY:BWSV:GIIE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** `Linux ip-172-31-28-155 4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single container

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** n/a

**Steps to Reproduce:**

* Create AWS EC2 instance running Ubuntu 16.04
* Ensure EC2 security group has port 8080 open
* Install Docker Engine `sudo apt install docker.io --yes`
* Add `ubuntu` user to `docker` group `sudo usermod --append --groups docker ubuntu`
* Pull Rancher Server container image from Docker Store `docker pull rancher/server`
* Run Rancher Server container `docker run --detach --interactive --tty --publish 8080:8080 rancher/server`

**Results:**

* Rancher Web UI is inaccessible
* Container appears to be hung during initialization process

**Container Logs**: https://gist.github.com/anonymous/e65a896a71bc4a1c61cf8333689633a1

### Snippet of last 10 lines

```
[34mINFO[0m[0038] Creating schema packetConfig, roles [service member owner project admin user readAdmin readonly restricted]  [34mid[0m=1ds28 [34mservice[0m=gms
[34mINFO[0m[0038] Updating machine jsons for  [packet packet amazonec2 azure digitalocean]  [34mservice[0m=gms
[34mINFO[0m[0038] Creating schema machine, roles [service]      [34mid[0m=1ds29 [34mservice[0m=gms
[34mINFO[0m[0039] Creating schema host, roles [service]         [34mid[0m=1ds30 [34mservice[0m=gms
[34mINFO[0m[0039] Creating schema machine, roles [project member owner]  [34mid[0m=1ds31 [34mservice[0m=gms
[34mINFO[0m[0040] Creating schema host, roles [project member owner]  [34mid[0m=1ds32 [34mservice[0m=gms
[34mINFO[0m[0040] Creating schema machine, roles [admin user readAdmin]  [34mid[0m=1ds33 [34mservice[0m=gms
[34mINFO[0m[0040] Creating schema host, roles [admin user readAdmin]  [34mid[0m=1ds34 [34mservice[0m=gms
[34mINFO[0m[0040] Creating schema machine, roles [readonly]     [34mid[0m=1ds35 [34mservice[0m=gms
[34mINFO[0m[0040] Creating schema host, roles [readonly]        [34mid[0m=1ds36 [34mservice[0m=gms
```

Cheers,
Trevor Sullivan

**Comment by vincent99** [comment]
That is a normal startup log and your problem is probably with security groups.  The server is up many lines before that at

`2017-11-24 17:17:31,702 INFO    [main] [ConsoleStatus] [DONE ] [39431ms] Startup Succeeded, Listening on port 8081 `

(And it says 8081 because there's an internal proxy from 8080 to there and other services).  Various things happen asynchronously after that, like downloading and activating machine drivers.  Your last ten lines are just what the last thing that happened was.

Also you don't need `-i` or `-t`, and without `--restart=unless-stopped`  it won't come back on reboot...

**Comment by pcgeek86** [comment]
Great, I just uncovered a VPN configuration problem. Sorry for the false report.
