### ISSUE TITLE
Pipeline UI does not load

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10404]
**Rancher versions:** version - v1.6.10

**Steps to Reproduce:**
1.  Click on Launch Pipeline UI

**Results:**  Page doesn't load
![image](https://user-images.githubusercontent.com/11514927/33282410-d10e592c-d365-11e7-946c-443134fca287.png)

**Comment by biblesyme** [comment]
Lawrence and I can't reproduce it, we just encountered it once when we set up environment in the first time.

**Comment by biblesyme** [comment]
I finally found that it's caused by bad networking, when networking is really bad, the file `/assets/vendor.js`can't be load properly, and the browser start to analyze `/assets/ui.js`. 

If networking is fast enough, there won't be any problem.

@vincent99  Did you know why it act like this?

**Comment by tfiduccia** [comment]
Version - master 12/6
Verified fixed
