### ISSUE TITLE
When switching between environments, Pipeline menu item sometimes dissapears

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10408]
**Rancher versions:** v1.6.10

**Steps to Reproduce:**
1.  Create at least two environments
2.  From the environment drop-down, switch between the two

**Results:**  Sometimes the Pipeline menu doesn't show up
![image](https://user-images.githubusercontent.com/11514927/33285564-e5d878f6-d36f-11e7-9d56-6778f2eaa8d5.png)

**Comment by biblesyme** [comment]
Fixed it in (http://35.202.69.220:8080/)

It's the same problem with #10405 #10407

For more details, see #10405

**Comment by tfiduccia** [comment]
Version - master 12/6
Verified fixed
