### ISSUE TITLE
Rancher 2.0 : host scheduling not working

### ISSUE THREAD

**Issue by olivierboudet** [rancher/rancher#10403]
I have created a service with host scheduling in order to have all containers on one host : 
![host_scheduling](https://user-images.githubusercontent.com/857205/33270476-7a27f036-d384-11e7-973c-c313d6939fe6.png)
 
But when stopping and deleting containers, they are also started on others hosts : 
![host_scheduling2](https://user-images.githubusercontent.com/857205/33270585-d537544e-d384-11e7-8fd5-f016673d28df.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha9` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`authenticated.clusters.index`|

**Comment by tfiduccia** [comment]
Retest in current version

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/11
Verified fixed in new 2.0 version
