### ISSUE TITLE
Rancher v1.6.11-ipsec-Kubernetes,When there is only one host, ETCD is still forced to have 2 running instances

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#10401]
**Rancher versions:**
rancher/server: v1.6.11

**Infrastructure Stack versions:**
rancher/lb-service-rancher:v0.7.17
rancher/etc-host-updater:v0.0.3
rancher/k8s:v1.8.3-rancher2
rancher/kubectld:v0.8.5
rancher/kubernetes-auth:v0.0.8
rancher/dns:v0.15.3
rancher/kubectld:v0.8.5
rancher/scheduler:v0.8.2
rancher/healthcheck:v0.3.3
rancher/metadata:v0.9.5
rancher/net:v0.13.1
rancher/network-manager:v0.7.18
rancher/etcd:v2.3.7-13
rancher/agent:v1.2.7

kubernetes (if applicable):
k8s:v1.8.3-rancher2
**Docker version: (`docker version`,`docker info` preferred)**
1.12.3
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux node2 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox VMware. Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
All
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1 . I manually created a new Kubernetes environment template, set up IPSec as a network driver, and built a new environment.
2. I only add a host to the environment
3.  I have only one host, but the ETCD service runs two instances,(one  normal operation,  one failed reconstruction)

![1](https://user-images.githubusercontent.com/20707603/33267416-5c91233c-d3b4-11e7-8114-b624148f9152.png)

![2](https://user-images.githubusercontent.com/20707603/33267410-56114370-d3b4-11e7-9cf7-64cb519033ab.png)
![3](https://user-images.githubusercontent.com/20707603/33267420-5fe3c8d2-d3b4-11e7-95bb-c096b230a9eb.png)

**expected result**
There should be only one ETCD instance running properly

**Results:**
A ETCD runs normally, but another instance is rebuilt repeatedly

**Comment by superseb** [comment]
We have this https://github.com/rancher/rancher/issues/10306 which we couldn't reproduce (could take ~1min to go away).

Is this from scratch and there was only 1 host in this environment ever (Not added/deleted etc of any other hosts?)

**Comment by hongxiaolu** [comment]
@superseb  Hi.
Yes, I'm a new environment, just adding a host.

**Comment by dmnt3d** [comment]
I was able to reproduce the same error by doing the following:
- Adding two host in a Kubenetes Cluster
- Inactivate both hosts and delete
- Add only one host.

**Comment by jamelseagraves** [comment]
I also have the same issue. Two hosts in a k8s cluster. Then remove one host. One etcd instance is green. Second etcd instance keeps trying to start, but obviously fails.

**Comment by jamelseagraves** [comment]
@superseb I am not sure why this happens. The only way I have found to stop this etcd error from happening is to spin up another host to contain the loose etcd instance.

**Comment by verenion** [comment]
We are also seeing this on v1.6.14. Started with three hosts - all running fine. Drained and removed two hosts. etcd fails to start, due to two instances just looping through "Starting", "Stopping" and "Error". Ran `disaster` on the etcd sole-survivor - which fixes the issue, but the other two instances continue to loop through errors. After adding new (freshly formatted) nodes, the sole survivor continues to work, but keeps failing to scale to other nodes - essentially making those nodes unusable.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
