### ISSUE TITLE
Clicking on launch pipeline for environment with no host bring up Error page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10407]
**Rancher versions:** v1.6.10

**Steps to Reproduce:**
1.  Create a new environment
2.  Do not add hosts
3.  Go to Pipeline page and click on Launch Pipeline

**Results:**  Cannot read property 'length' of undefined error page comes up
![image](https://user-images.githubusercontent.com/11514927/33285407-719a3fd8-d36f-11e7-8675-b205b8f3e924.png)

**Comment by biblesyme** [comment]
Fixed it in (http://35.202.69.220:8080/)

It's the same problem with #10405 #10408

**Comment by tfiduccia** [comment]
Now the Pipeline menu doesn't show up at all for new environments.  We should not hide/show menu items depending on if hosts are there or not.

**Comment by tfiduccia** [comment]
Closing this.  I added the catalog and now the button doesn't show up until Host are added.
