### ISSUE TITLE
RHEL/CentOS 7 inside all Rancher launched containers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1041]
Currently, Rancher uses ubuntu inside all containers (server, agent, agent-instance). We need to support being able to launch RHEL/CentOS 6/7 inside the containers.

**Comment by pwFoo** [comment]
I prefer centos over ubuntu. So would be fine :)

**Comment by aemneina** [comment]
@deniseschannon @ibuildthecloud has anyone requested this? It doesnt seem like we're seeing any demand for this. I could be wrong.

**Comment by vincent99** [comment]
Sounds like no.
