### ISSUE TITLE
Containers are Unable to Relove DNS when install using rancher

### ISSUE THREAD

**Issue by dinkarthakur** [rancher/rancher#10418]
**Rancher versions:**
rancher/server:  rancher/server:stable

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: cni-driver rancher/net:v0.11.9,rancher/net:holder
network-services: rancher/metadata:v0.9.4, rancher/network-manager:v0.7.8
scheduler: rancher/scheduler:v0.8.2
Swarm: rancher/swarmkit:v1.13.0-beta.1

**Docker version:**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-101-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859GiB
Name: dinkarthakurlinux
ID: B5M5:34F7:FQWF:XSLD:B6MZ:64EQ:3EJD:YWYF:AKC7:SSXR:GZJ6:CRYZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel:**
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

**Type/provider of hosts: VirtualBox**

**Setup details: HA rancher**

**Environment Template: Swarm**

**Steps to Reproduce:**
Just install Rnacher with Docker Swarm and add any image container
Enter to the Container's shell and try to ping google.com or any other domain.

**Results:**
Container was not able to resolve any Url, and gives Unknown Host response. 
If we ping the IP of domain ping succeeds.

**Comment by superseb** [comment]
Can you check what `/etc/resolv.con` contains inside a container? This should give you a pointer why it can't resolve DNS names

**Comment by superseb** [comment]
Please report back if so we can investigate.
