### ISSUE TITLE
The unexpected appearance of elastic etcd service

### ISSUE THREAD

**Issue by anzersy** [rancher/rancher#10412]
**Rancher versions:**
rancher/server:
v1.6.11
rancher/agent:
v1.2.7
**Infrastructure Stack versions:**
healthcheck:
v0.3.3 
ipsec:
v0.13.2
network-services:
metadata(v0.7.18),dns(v0.15.3),network-manager(v0.7.18)
scheduler:
v0.8.2
kubernetes (if applicable):
v1.8.3-rancher1
**Docker version: (`docker version`,`docker info` preferred)**
v1.12.3
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. Add two or more hosts to kubernetes cluster
2. Just remain only one host in kubernetes cluster and deactive/delete the other hosts 

**Results:**
Scheduler was always going to start one more etcd container on this left host, however it should be got a failure because the scheduling policy of etcd service was set to "the host must not have a host label of io.rancher.stack_service.name=$${stack_name}/$${service_name}"

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/10411
