### ISSUE TITLE
The problems of multi host healthcheck and scheduler

### ISSUE THREAD

**Issue by yangjia517** [rancher/rancher#10419]
**Rancher versions:**
rancher/server:v1.6.11
rancher/agent:v1.2.7

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec:v0.13.2
network-services:v0.9.5
scheduler:v0.8.2
kubernetes (if applicable):null

root@ubuntu:/var/lib/rancher# docker info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: nlix8v2qufh30gg8uulij898x
 Is Manager: true
 ClusterID: 0yte1awl1bup4pvvcn1ahf331
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.229.130
 Manager Addresses:
  192.168.229.130:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.937 GiB
Name: ubuntu
ID: QFKM:XNH6:YYJ3:LYOI:SJO6:LQLS:SXBN:2RSE:WYRH:WTJF:WRIZ:RXYA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jarno517
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Hi：
I installed rancher on 1 hosts and added another host (non HA). I observed that my healthcheck and scheduler always showed yellow hints. Is this normal?
And it's not a long time to restart healthcheck?

![111111](https://user-images.githubusercontent.com/33953118/33309122-043767a6-d458-11e7-9809-c237a1826aa1.png)
![22222](https://user-images.githubusercontent.com/33953118/33309205-4420b26e-d458-11e7-9ebe-19f0d1eab102.png)
![333333](https://user-images.githubusercontent.com/33953118/33309211-46f4f310-d458-11e7-9ae3-89f8129d6bbd.png)
![555551](https://user-images.githubusercontent.com/33953118/33309244-5f4c5fd4-d458-11e7-92fd-83762aae6c70.png)
 Scheduler's log is as follows:

2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Connecting to cattle event stream."
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Subscribing to metadata changes."
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Initializing event router" workerCount=100
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Connection established"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Starting websocket pings"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host  a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host  a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [memoryReservation] with total 2079326208 and used 0 for host  a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [storageSize] with total 13614227 and used 0 for host  a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[2201:d7b48aca-547d-4a4c-9d10-ed131d94b097 8801:d7b48aca-547d-4a4c-9d10-ed131d94b097 8080:88bfc890-c8b4-48fb-9eb3-93a12bd7f176]], ports map udp map[0.0.0.0:map[500:3942fe9e-71b7-4420-8bc6-3f3a6eb7538b 4500:3942fe9e-71b7-4420-8bc6-3f3a6eb7538b]] for host a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [hostLabels] with label map [map[io.rancher.host.agent_image:rancher/agent:v1.2.7 io.rancher.host.docker_version:17.03 io.rancher.host.linux_kernel_version:4.4]]"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 9 for host  97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host  97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [memoryReservation] with total 2079326208 and used 0 for host  97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [storageSize] with total 15768231 and used 0 for host  97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[5000:156818ff-7d03-422d-9be7-6e79cd9ade02]], ports map udp map[0.0.0.0:map[500:7a622d1b-eaac-4a92-b165-d9bcd56297ea 4500:7a622d1b-eaac-4a92-b165-d9bcd56297ea]] for host 97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/28 下午4:08:50time="2017-11-28T08:08:50Z" level=info msg="Adding resource pool [hostLabels] with label map [map[io.rancher.host.agent_image:rancher/agent:v1.2.7 io.rancher.host.docker_version:17.03 io.rancher.host.linux_kernel_version:4.4]]"

**Comment by Edenshaw** [comment]
I was facing the same issue, although I deleted the healthcheck stack and re-created using the Catalog. Now helathcheck is green but scheduler is still yellow and no logs at all

**Comment by superseb** [comment]
@yangjia517 The `docker info` output shows the node is part of a Swarm cluster, are you deploying as a stack or separate `docker run` commands? Can you supply the steps you took to get the environment in this state so I can reproduce?

@Edenshaw Same question for you.

Things to check are:
* Are all the hosts in Infrastructure -> Hosts view showing the correct IP address (and that they can reach other using UDP/500 and UDP/4500)
* Is cross-host networking working properly? (you can run the following command inside a ipsec-router container:
```
for i in `curl -s 169.254.169.250/latest/self/service/containers/` ; do id=$(echo $i| cut -f1 -d=) ; name=$(echo $i| cut -f2 -d=) ; echo " ---- $name --------" ; ping -c2 `curl -s curl 169.254.169.250/latest/self/service/containers/$id/primary_ip` ; done
```
* If scheduler is stuck in `Initializing`, you can check the logs by using `View Logs` in the UI or `docker logs` on the host where the scheduler container is running.

**Comment by yangjia517** [comment]
As you say, I've built swarm before, and now I've run docker swarm leave.
According to your suggestion, check the results:
![image](https://user-images.githubusercontent.com/33953118/33354994-7b4f629c-d4f0-11e7-8ab0-699fda8aead6.png)
![image](https://user-images.githubusercontent.com/33953118/33355003-863afd24-d4f0-11e7-86bc-c997507823e2.png)

![image](https://user-images.githubusercontent.com/33953118/33354869-e33ebfe8-d4ef-11e7-80ce-1ecc6f7b7153.png)
scheduler View Logs：
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Connecting to cattle event stream."
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Subscribing to metadata changes."
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host  97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host  97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [memoryReservation] with total 2079326208 and used 0 for host  97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [storageSize] with total 15768231 and used 0 for host  97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[5000:156818ff-7d03-422d-9be7-6e79cd9ade02]], ports map udp map[0.0.0.0:map[500:7a622d1b-eaac-4a92-b165-d9bcd56297ea 4500:7a622d1b-eaac-4a92-b165-d9bcd56297ea]] for host 97d800e6-2bbb-42e4-b238-962037e3a516"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [hostLabels] with label map [map[io.rancher.host.agent_image:rancher/agent:v1.2.7 io.rancher.host.docker_version:17.03 io.rancher.host.linux_kernel_version:4.4]]"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host  a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host  a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [memoryReservation] with total 2079326208 and used 0 for host  a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [storageSize] with total 13614227 and used 0 for host  a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[2201:d7b48aca-547d-4a4c-9d10-ed131d94b097 8801:d7b48aca-547d-4a4c-9d10-ed131d94b097 8080:88bfc890-c8b4-48fb-9eb3-93a12bd7f176]], ports map udp map[0.0.0.0:map[500:3942fe9e-71b7-4420-8bc6-3f3a6eb7538b 4500:3942fe9e-71b7-4420-8bc6-3f3a6eb7538b]] for host a2a6c585-fce9-44c9-a138-270cba0e31ba"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Adding resource pool [hostLabels] with label map [map[io.rancher.host.agent_image:rancher/agent:v1.2.7 io.rancher.host.docker_version:17.03 io.rancher.host.linux_kernel_version:4.4]]"
2017/11/29 上午10:31:49time="2017-11-29T02:31:49Z" level=info msg="Initializing event router" workerCount=100
2017/11/29 上午10:32:16time="2017-11-29T02:32:16Z" level=info msg="Connection established"
2017/11/29 上午10:32:16time="2017-11-29T02:32:16Z" level=info msg="Starting websocket pings"

**Comment by vincent99** [comment]
No, the 172.17 one is the Docker interface.  Each host needs a unique IP that every other host in the environment can reach.  You do not have that.  If that is the host that is running the server container, auto-detection of the right IP cannot be done and you need to provide it with the CATTLE_AGENT_IP environment variable.

**Comment by yangjia517** [comment]
@vincent99 Thank you very much for your answer。
How should I increase the variables?

**Comment by yangjia517** [comment]
like this?
sudo docker run -e CATTLE_AGENT_IP=172.17.0.1 -d --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://172.17.0.3:8080/v1/scripts/DB121CFBA836F9493653:1434085200000:2ZOwUMd6fIzz44efikGhBP1veo

**Comment by yangjia517** [comment]
@vincent99 @superseb 
The problem has been solved, thank you very much!
Explain：
You need to specify CATTLE_AGENT_IP when you add a host, and now all the hosts' healthcheck and scheduler are normal.
