### ISSUE TITLE
Loadbalancer "Host IP" configuration is lost on next "edit configuration".

### ISSUE THREAD

**Issue by xeagle2** [rancher/rancher#10414]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.1.4
network-services: 0.2.6
scheduler: 0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external database

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Edit loadbalancer
2. Turn on "Show host IP Addresses"
3. Specify "Host IP" for any particular 'Public' rule.
4. Click on "Edit" button to finalize changes.
5. Edit loadbalancer again, turn on "Show host IP Addresses" and see that "Host IP" configuration fields are empty even though they were specified on last edit. The expected result is to see the lastly saved "Host IP" configuration.

**Results:**

**Comment by aemneina** [comment]
I believe the original value of the service had no entry for the host ip. I believe it would be preserved if it was originally there. Can you confirm?

**Comment by xeagle2** [comment]
@aemneina, If I create an new entry "Service Rule" and specify "Host IP", save it, edit loadbalancer configuration again and the field is empty on UI. Maybe it's preserved somewhere, however the there is no value in UI and if you save the configuration again, so the empty value is saved.

**Comment by superseb** [comment]
Confirmed, ports are present in `launchConfig` but not (re)-used when editing the LB in the UI.

**Comment by xeagle2** [comment]
The same issue exists for "Host IP" configured for service itself in "Port Map" section.

**Comment by loganhz** [comment]
we need `sourceIp` field in `portrule`. It's not in `portrule` schema.
Even `ports` are in  `launchConfig `. But UI doesn't know how to map them.
This should be working once server side populates the `sourceIp`

![image](https://user-images.githubusercontent.com/21168270/37140076-64e329f0-22eb-11e8-909b-74007c6399b7.png)

**Comment by vincent99** [comment]
Not that simple.  The balancer container _doesn't know_ the IP the request was for because it's always the 10.42.x.y IP.  The problem here is that the 1.x UI allows expressing things that can't actually be represented in the API, and therefore can't be restored back on edit.  You cannot route a single target port to different targets based on the (incoming) destination IP.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/11223
