### ISSUE TITLE
There are no compatible templates after adding catalog in rancher

### ISSUE THREAD

**Issue by jkull99** [rancher/rancher#10415]
Running rancher 1.6.10

I am an IT systems guy (not a developer) and I am trying to build a SIEM Monster deployment using Rancher and docker from a pre built Ubuntu Image (using vmware OVF file.) The instructions I have have me add a catalog to rancher called SIEM using the github url - http://github.com/siemonster/rancher-free. I need this catalog to add two apps called heaven and siemonster.

When I launch the catalog I get the there are no compatible templates error. I have looked at several articles on this site and none of them seem to have an answer that works. I have tried manually adding the apps with the Rancher CLI and that produced this error:  Could not parse config for project siemonster-project-siem : template: template:58: function "SITE_DNAME" not defined. I found an article about escaping the variable - which I tried and got the same error. I added the # notemplating and still got errors.

I have tried to figure out where the ranger and or catalog logs are located as the refresh button on the catalog page has a triangle with an exclamation, so I know its generating an error. If someone can point me to the logs for the rancher catalog I think this might be a good place to start.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.index`|

**Comment by aemneina** [comment]
What version of the CLI did you run this from? It should prompt for variables that arent present as environmental variables. I was able to launch heaven from the UI after adding that github url as a catalog, siemonster seems to want a few hosts with specific host labels, but no nasty errors thrown. Did you pick master as the siemonster branch? You might want to engage the author of that plugin on the github issues section: https://github.com/siemonster/rancher-free/issues

**Comment by jkull99** [comment]
I downloaded the CLI from the link in the lower right section  of the rancher management page. I am running 1.6.10. Yes, I selected master as the branch. 

I guess I should have mentioned, I was able to add the heaven app through the CLI although I am not sure it prompted for all the fields I need. Below is the output when I try to do SIEMonster with the CLI. I have ran it multiple times after making the edits as described earlier:

C:\Users\jkull\Downloads\rancher-windows-386-v0.6.4\rancher-v0.6.4>rancher up -d -s siemonster-project-siem
Enter Gmail Relay e-mail address.
GMAILRELAY_EMAIL GMAILRELAY_EMAIL[]:
enter password for e-mail address.
GMAILRELAY_EMAILPASS GMAILRELAY_EMAILPASS[]:
Specify the domain name of the site.
Site domain name SITE_DNAME[projectname.portal.siemonster.com]: siem.corp.siemonster.local
Specify the branch name to checkout.
Branch name BRANCH_NAME[master]:
ELASTICSEARCH_KRAKEN_TIAMAT_HEAP_SIZE ELASTICSEARCH_KRAKEN_TIAMAT_HEAP_SIZE[2g]:
ELASTICSEARCH_PROTEUS_CAPRICORN_HEAP_SIZE ELASTICSEARCH_PROTEUS_CAPRICORN_HEAP_SIZE[1g]:
[31mERRO[0m[0007] Could not parse config for project siemonster-project-siem : template: template:58: function "SITE_DNAME" not defined
[31mFATA[0m[0007] Failed to read project: template: template:58: function "SITE_DNAME" not defined

**Comment by jkull99** [comment]
I might also mentioned it looks like someone has opened a similar issue @ https://github.com/siemonster/rancher-free/issues and it has been open for 23 days with no replies.

**Comment by rchayes** [comment]
Do you by chance block external DNS resolution on your network?  It took me forever to figure out that although the server hosting Rancher has our local DNS set (and working), Rancher is in a Docker container that is still trying to use Google DNS.  Opened up DNS on our firewall for this server and template loaded with no problem.

**Comment by jkull99** [comment]
First, thanks for responding!
I am able to see the other catalogs (library and community) - just not the SIEMONSTER catalogs, so I think DNS is working fine from rancher or I would think I would not see ANY catalogs

**Comment by rchayes** [comment]
Yes mine was the same.  Like I said I'm unsure why but I could see all community catalogs, etc. but that was all I could see until I opened up dns.  I'm actually proceeding with the install now.  I found this in the docker logs for the rancher container: https://git.rancher.io/repos/community-catalog/commits/master: dial tcp: lookup git.rancher.io on 8.8.4.4:53.  That was what clued me in.

**Comment by jkull99** [comment]
I just took a look at our firewall logs and I am seeing traffic to 8.8.4.4 and 8.8.8.8 being allowed out. Where are the rancher logs located you are looking at? I would like to have a look. I assume the traffic comes from the actual server that hosts the container - correct? I am not seeing any traffic denied from the container hosts.

**Comment by rchayes** [comment]
SSH into your server
docker ps    - to get your container id
docker logs CONTAINERID

**Comment by jkull99** [comment]
Checked the logs and saw a similar entry to what you had (see below) - except I am pointing to two internal DNS servers. First server IP was invalid. Updated IP and tried refreshing - rancher still trying to talk to the bad DNS IP. If I do an nslookup on the box it is pointing to the right DNS. tried a reboot after the dns updates and it still tries contacting the bad IP address when I do a refresh.

[https://git.rancher.io/community-catalog.git] is not accessible: Get https://git.rancher.io/repos/community-catalog/commits/master: dial tcp: lookup git.rancher.io on 172.20.0.17:53: read udp 172.17.0.2:56810->172.20.0.17:53: i/o timeout"

**Comment by jkull99** [comment]
I got it fixed!! 
Found in the documentation for SIEMONSTER that I had to update the /etc/docker/daemon.json entry for local DNS. This file still had the old DNS server listed. Not sure why rancher did not try the second DNS server since it was valid but now I have the two apps showing in the catalog.

Thanks rchayes for pointing me in the right direction!
