### ISSUE TITLE
[rancher-compose] Update to supporting secrets in rancher-compose?

### ISSUE THREAD

**Issue by senica** [rancher/rancher#10417]
**Rancher versions:**
rancher/compose: 0.12.5

**Steps to Reproduce:**
Any docker file with a service that has `secrets` defined

**Results:**
```
 Could not parse config for project : Unsupported config option for redis service: 'secrets' 
```

Is there any update to supporting secrets with rancher-compose. Would be awesome if it created secrets for you when you launched a service (if it doesn't exist)

**Comment by senica** [comment]
It looks like secrets are supported in Rancher CLI. I did not realize there was a difference.

**Comment by superseb** [comment]
Thanks for reporting. rancher-compose CLI is not being actively developed anymore, meaning that new features will only be added to Rancher CLI.
