### ISSUE TITLE
[rancher-dns] [rancher-net] l2-flat network should update DNS for all containers on managed network

### ISSUE THREAD

**Issue by someone1** [rancher/rancher#10426]
**Rancher versions:**
rancher/server: V1.1.0
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
l2-flat: v0.13.4
network-services: v0.7.18
scheduler: v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:48:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.1.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.1.0
PRETTY_NAME="RancherOS v1.1.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

4.9.45-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 Rancher Host Node w/ Internal DB + 2 Agent Nodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a Stack+Service and DO NOT expose any ports. Since the managed networking is l2-flat, even with no exposed ports (which just forwards from the host IP to the container), the container is still accessible from external devices. This is desired for situations in which each host has multiple services required by external applications running on overlapping ports - thus different IPs for each container is desired so that the services can operate on the same port.

**Results:**
The problem is that DNS updates are only triggered if the service has a port exposed, and even then it doesn't update the DNS entry to the IP on the managed network, it updates to the host's IP. I can understand why this is desirable in other network overlays, but it is not desirable in the l2-flat network configuration I had in mind.

I do see TXT entries added to the target DNS server for each container, but no A records for them unless a port is mapped and even then its for the IP of the host, not the container.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
