### ISSUE TITLE
Add simple host based L7 router service

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1042]
Add a host based L7 router service to allow for things like forwarding foo.example.com -> foo or bar.example.com -> bar.

**Comment by pwFoo** [comment]
Will it support multiple ports / protocols like http, https (webservers) and ssh (management containers with ssh service running)?

**Comment by will-chan** [comment]
- Support hostname routing
- Support path based routing
- Add Rancher compose support
- Add ability to read from legacy tables and new one.

**Comment by will-chan** [comment]
Closing feature.  Any bugs found should be filed separately.
