### ISSUE TITLE
Add Pipeline Repository UI bugs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10425]
**Rancher versions:**v1.6.10

**Results:**
- [x] Add Pipeline Step 1 - Selecting user highlights everything in blue, but the name of the user is also in blue so you can't really see the name
![image](https://user-images.githubusercontent.com/11514927/33295987-1348b33e-d396-11e7-94bf-2306a0f84d46.png)

- [x] Clicking on the name in the User drop-down take to new page with user's avatar.  There should not be a link in the drop-down.  I should be able to select anywhere on that row and have it just select.

- [ ]  Refresh repository hint needs to be changed.  Should simply say "Refresh repository" (Vincent thinks this refresh shouldn't even exist and should be taken out)
![image](https://user-images.githubusercontent.com/11514927/33296088-c31997a6-d396-11e7-8255-dd77bf7de9e5.png)

- [x] Spell out repository in initial info
![image](https://user-images.githubusercontent.com/11514927/33296131-f5c953da-d396-11e7-81b9-db18727d8c7c.png)

- [x] Webhook should always just be  checkbox on or off.  And should not be a yellow X.
![image](https://user-images.githubusercontent.com/11514927/33338653-f561b4f8-d433-11e7-9841-19901767e316.png)

- [x] Webhook hint should say something like "Automatically run pipeline after commits"

- [x] User box get significantly bigger after you select someone.  Should not change size/get bigger.
![image](https://user-images.githubusercontent.com/11514927/33338703-20638820-d434-11e7-8b2c-7cff5ba461f5.png)

- [x] We are not adding a step to the stage at this point.  So that should not be the title of the modal.  "Add Repository" might be a good title.  Also please remove  "1. Source Code Management"
![image](https://user-images.githubusercontent.com/11514927/33338747-40a47f54-d434-11e7-89b2-48749cfe488c.png)

- [x] No error message for "User" is required, remove ! from all error messages and Repository should be a valid git address!  should be "Repository" is required
![image](https://user-images.githubusercontent.com/11514927/33345083-55e0cd5a-d448-11e7-9392-1dbcc5d6f03e.png)

- [x] When modal opens, focus should already be on the User drop-down.  Right now there is no default focus.
![image](https://user-images.githubusercontent.com/11514927/33346048-935a3196-d44b-11e7-9988-b1b2990aa7c9.png)

**Comment by biblesyme** [comment]
Fixed in latest version in (http://120.78.135.106:8082/)

For the issues 

1. ` User box get significantly bigger after you select someone. Should not change size/get bigger.` 
2. `When modal opens, focus should already be on the User drop-down. Right now there is no default focus.`

I solved it by setting the first repository and first user as the default value, and focusing branch input box.

**Comment by kingsd041** [comment]
The pended issue has moved to #10719
