### ISSUE TITLE
Pipeline UI doesn't open for new environments

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10421]
**Rancher versions:** v1.6.10

**Steps to Reproduce:**
1. Create a new environment
2. Add a host
3. Add the CICD catalog and deploy CICD
4. Once it's all setup go to Pipelines
5.  Click on Launch Pipeline UI

**Results:**  Getting a build error page
![image](https://user-images.githubusercontent.com/11514927/33337102-1fcafad8-d42f-11e7-8f3b-5d5231531ca8.png)

**Comment by biblesyme** [comment]
Can you specify which version of catalog you are using?

**Comment by tfiduccia** [comment]
Well at the time, I swear there was only 1.  Today there are three versions in 
https://github.com/gitlawr/rancher-catalog-1.git.  So I'm going to say 0.0.1-dev

**Comment by biblesyme** [comment]
Now, we have updated the deploy guide(https://github.com/rancher/pipeline/blob/docs/docs/Deploy_guide_1.6.md) to the latest one, please follow it to test it again.

**Comment by kingsd041** [comment]
Tested with rancher-server version- v1.6.13 with pipeline v0.1.0. 
No error message appears.
