### ISSUE TITLE
Rancher agent not registring into rancher

### ISSUE THREAD

**Issue by manwanth** [rancher/rancher#10422]
**Rancher versions:**
rancher/server: v1.6.9
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)** 
17.09.0-ce, build afdb6d4

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux ran01 3.10.0-693.1.1.el7.x86_64 #1 SMP Thu Aug 3 08:15:31 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
RHEL 7.3 - Custom Azure VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

**Results:**
time="2017-11-28T18:36:31Z" level=error msg="Failed to get connection token for host-api startup: Reached max retry attempts for getting token"
time="2017-11-28T18:36:36Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid=f1887f9d-38e9-4934-4ee9-bda4ac710511
time="2017-11-28T18:36:37Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid=f1887f9d-38e9-4934-4ee9-bda4ac710511
time="2017-11-28T18:36:38Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid=f1887f9d-38e9-4934-4ee9-bda4ac710511
time="2017-11-28T18:36:40Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid=f1887f9d-38e9-4934-4ee9-bda4ac710511
time="2017-11-28T18:36:41Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=4 reportedUuid=f1887f9d-38e9-4934-4ee9-bda4ac710511
time="2017-11-28T18:36:42Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=5 reportedUuid=f1887f9d-38e9-4934-4ee9-bda4ac710511
time="2017-11-28T18:36:43Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=6 reportedUuid=f1887f9d-38e9-4934-4ee9-bda4ac710511

**Comment by Joni-Lover** [comment]
try to downgrade kernel to 3.10.0-514. It's work for me.

**Comment by aemneina** [comment]
Have you added the agent using the flag `-e CATTLE_AGENT_IP`? I also believe that docker version might be 'too new' for running k8s 1.6.x.

**Comment by aemneina** [comment]
Another question, are you reusing the agent?

**Comment by Joni-Lover** [comment]
I am try use CATTLE_AGENT_IP and it's no way for me. And yes, i am init new node on 3.10.0-693 kernel and after than downgrade kernel.

**Comment by Joni-Lover** [comment]
but i am use Rancher 1.2.2

**Comment by Gr1dd** [comment]
Same issue here.
Docker 17.06
Latest everything besides docker.
Agent is in DMZ home here, manager is in cloud on google. Everything is wide open

**Comment by Gr1dd** [comment]
Alright, I resolved my issue here:  

Well.. it WAS there but under settings I set my url to port 8080 after my domain name since I was http-proxying my port 8080 to 80 for webend users. this set my url to the url that's not port 8080, maybe it should be hardcoded in.

**Comment by superseb** [comment]
Let us know if you still encounter issues with this.
