### ISSUE TITLE
Pipeline code causing error/going to wrong page when switching environments

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10420]
**Rancher versions:** v1.6.10

**Steps to Reproduce:**
1. Switch environments

**Results:**  Goes to Manage Environments page instead of Stacks page.  Error in console, Regions don't exist in 1.6.10 or 1.6.11.  Should find out when that is releases or turn off that call.
fetch.js:404 GET http://35.202.69.220:8080/v2-beta/schemas/region?sort=name 404 (Not Found)

**Comment by biblesyme** [comment]
Actually, this version of UI is not based in v1.6.10, it's based on branch v1.6-dev for merging.

But, we used rancher/server:v1.6.10 as the backend. 

@vincent99 Should I use`rancher/server:v1.6-development` for test, or any other image?

**Comment by vincent99** [comment]
You have UI based off of "master" (1.6-dev), which has Regions support for a future release trying to hit an API that doesn't exist in 1.6.10.  So you either one of:

-  a newer backend that does have regions
- a hack to disable trying to get them in the UI (app/authenticated/route.js preload)
- or rebase the UI changes against the release UI tag for Rancher 1.6.10 or 11.

**Comment by biblesyme** [comment]
We want to release Pipeline UI in 1.6.12, so for test purpose, I should rebase it into `rancher/ui` `tag: v1.6.12`, and use the latest rancher/server:v1.6.12-rc1 as backend, right?

**Comment by biblesyme** [comment]
@vincent99 I've rebased code into tag v1.6.10, and requested a new PR.

**Comment by tfiduccia** [comment]
Version - master 12-6
Verified fixed
