### ISSUE TITLE
OpenStack Controller deletes the ssh-key when deleting a node

### ISSUE THREAD

**Issue by hvpareja** [rancher/rancher#10435]
**Rancher versions:**
rancher/server: 1.6.11
rancher/agent: Irrelevant

**Docker version: (`docker version`,`docker info` preferred)**
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-327.36.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Just a Rancher Server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1) Create a new node using the OpenStack driver
2) Delete the node

**Results:**
The node is deleted but I can't reuse the same ssh key anymore because has been deleted after the DELETE request to OpenStack.

I suggest not to send the key name in the DELETE request for the node deletion

**Comment by vincent99** [comment]
docker-machine creates a unique SSH key for each host and deletes it when the host is removed.  You shouldn't be reusing them.
