### ISSUE TITLE
AliCloud agent disconnected after upgrading to 1.6.11 and 1.6.12

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#10439]
Upgrade from v1.6.10 to v1.6.11 or v1.6.12, one AliCloud host failed to connect to server. Errors in rancher agent as below:

ime="2017-12-01T05:54:30Z" level=info msg="Starting event router."
panic: runtime error: index out of range

goroutine 11 [running]:
github.com/rancher/agent/vendor/github.com/denverdino/aliyungo/metadata.(*MetaData).Zone(0xc4202877d0, 0xc4200161c0, 0xc4202fea20, 0x0, 0x0)
        /go/src/github.com/rancher/agent/vendor/github.com/denverdino/aliyungo/metadata/client.go:229 +0xb0
github.com/rancher/agent/cloudprovider/aliyun.metadataClientImpl.Zone(0xc4202877d0, 0x0, 0xc420037e60, 0x4ecbbb, 0xc4200161c0)
        /go/src/github.com/rancher/agent/cloudprovider/aliyun/aliyun_provider.go:43 +0x2b
github.com/rancher/agent/cloudprovider/aliyun.(*Provider).GetHostInfo(0xc420251b00, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/agent/cloudprovider/aliyun/aliyun_provider.go:57 +0x48
github.com/rancher/agent/cloudprovider.GetCloudProviderInfo.func1(0xf4af80, 0xc420251b00)
        /go/src/github.com/rancher/agent/cloudprovider/cloud_provider.go:60 +0x64
created by github.com/rancher/agent/cloudprovider.GetCloudProviderInfo
        /go/src/github.com/rancher/agent/cloudprovider/cloud_provider.go:80 +0x1f5

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by loganhz** [comment]
Aliyun Metadata service returns 500 on that node. Aliyun SDK breaks in this case. We need to make a PR to Aliyun SDK and update rancher/agent.

You can submit a ticket to Aliyun and let them check why Aliyun Metadata service returns 500.
Or you can replace the go-agent.tar.gz in rancher server manually and re-add this host.

**Comment by loganhz** [comment]
Workaround is using `-e CATTLE_DETECT_CLOUD_PROVIDER=false` to the command running `rancher/agent`

**Comment by pengjiang80** [comment]
Got it. Last time the parameter I got is -e DETECT_CLOUD_PROVIDER=false which missed CATTLE so didn't work. :）

**Comment by deniseschannon** [comment]
This was fixed in v1.6.13.
