### ISSUE TITLE
rancher-lb: haproxy 1.8 http2 and orchestration support

### ISSUE THREAD

**Issue by kgk** [rancher/rancher#10431]
**Rancher versions:**
rancher/server:1.6.10
rancher/agent:

Feature request that rancher-lb uses the new haproxy 1.8

Supports http2 and dynamic server adjustments with api

https://www.haproxy.com/blog/whats-new-haproxy-1-8/

**Comment by marcbachmann** [comment]
That's also requested in here: https://github.com/rancher/rancher/issues/6847

**Comment by defcon8** [comment]
Update of haproxy wanted in Rancher! 1.6.14 !!!!!!

**Comment by superseb** [comment]
If testing is good, 1.8.4 will be in v1.6.15.

**Comment by defcon8** [comment]
That's really great to hear @superseb !

**Comment by superseb** [comment]
Before there are any false promises, Haproxy is being updated but there will not be any functionality configurable like http2 as that is tracked in https://github.com/rancher/rancher/issues/6847. Let me close this regarding 1.8, additional functionality will be track in https://github.com/rancher/rancher/issues/6847.

**Comment by bearmoo-repo** [comment]
Any update on this?
