### ISSUE TITLE
Healthcheck failing on kubernetes environment

### ISSUE THREAD

**Issue by mickengland** [rancher/rancher#10433]
*Describe your issue here*es 

After having issues trying to upgrade to latest Kubernetet I created a new environment selecting Kubernetes and I now get a problem with the healthcheck failing to initialize. I get this error.

healthcheck (Failed to allocate instance [container:1i2508]: Bad instance [container:1i2508] in state [removed]: Failed to find network for networkMode managed) 

In the hosts I see networking-manager and metadata but no healthcheck. I have two nodes configured in the environment -- one failed on startup repeatedly, which is another issue. The Kubernetes stack just stays in a state of Creating Kubernetes system stack forever.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.11` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`stacks.index`|

**Comment by aemneina** [comment]
hey @mickengland it might be good to connect with us over [slack](https://rancher-users.slack.com/) looks like a more fundamental issue going on with your setup.

**Comment by mickengland** [comment]
Relaunching with the default Ubuntu images fixed this.
