### ISSUE TITLE
Copy/paste doesn't work with Firefox 57.0.0.1

### ISSUE THREAD

**Issue by thenets** [rancher/rancher#10437]
**Firefox version:**

57.0.0.1
Windows 10 Pro (1703)

**Rancher versions:**

rancher/server: 1.6.11
rancher/agent: 1.2.7

**Docker version:**

17.05.0-ce

**Operating system and kernel:**

Ubuntu 16.04.3 / 4.2.0-36-generic

**Steps to Reproduce:**

1. Open any container
2. Go to options
3. Open "Execute Shell"
4. Try to paste (doesn't work)
    - Ctrl+V (pass ^V input)
    - Ctrl+Shift+V (nothing happen)
    - Right click (menu doesn't open)

**Results:**

Don't paste.

**Comment by aemneina** [comment]
As a datapoint this works on mac osx + firefox 57.0.1

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
