### ISSUE TITLE
Multicast communication restriction

### ISSUE THREAD

**Issue by khauser** [rancher/rancher#10441]
**Rancher versions:**
rancher/server: 1.6.11
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.1.1
network-services: v0.2.6
scheduler: v0.6.3

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.1.0 (with KVM) (4.9.45)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
one rancher host and one agent
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Using the network-policy-manager the communication between stacks could be restricted. A simple ping for instance between different stack services isn't possible. The problem now is that a service in one stack still receives Multicast messages from services in other stacks.
Is it possible to prevent also this communication in Rancher?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
