### ISSUE TITLE
[cli]  Environment variables trump explicit "--config" option

### ISSUE THREAD

**Issue by rmalchow** [rancher/rancher#10443]
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Darwin rm100270-2.local 16.7.0 Darwin Kernel Version 16.7.0:

**Steps to Reproduce:**

set RANCHER_URL, RANCHER_SECRET_KEY etc as environment variables,

call rancher with --config options.

**Results:**

the CLI uses the values from the environment variables rather than the values from the config JSON, this is slightly confusing.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
