### ISSUE TITLE
Bootstrap agent in windows environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10448]
related to https://github.com/rancher/rancher/issues/10442

Enhance the agent setup experience in windows environment.
* The agent's binary will be download from rancher server
* Set host labels and agent IP to windows environment variable when bootstrapping agent.
* Setup and start agent service in windows

**Comment by deniseschannon** [comment]
Merged into Cattle. 

Closing as testing will be for overall windows experience and new issues will be filed.
