### ISSUE TITLE
nfs Cannot mapping files

### ISSUE THREAD

**Issue by vesaaa** [rancher/rancher#10440]
volume mapping Folder is OK， but mapping files is error.
vollume is from nfs . eg: rancher-nfs

step1 ：  use rancher-nfs mount nfs server  IP:/folder
step2  :    add service use volume 
step3  :     eg(host):    /opt/logs:/opt/logs    is  ok
                eg(host):    /opt/nginx/nginx.conf:/opt/nginx/nginx.conf    is  ok
                eg(nfs):     logs:/opt/logs    is  ok
                eg(nfs):     nginx/nginx.conf:/opt/nginx/nginx.conf      is   error

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.11` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.launch`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
