### ISSUE TITLE
Rancher windows enhancement

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10442]
Rancher windows environment enhance list

* Networking enhance.
  * Support per-host-subnet 
  * Support port mapping in per-host-subnet
  * Setup per-host-subnet as windows service
* Bootstrap agent in windows environment.
  * Support setting host labels when adding host
  * Support setting agent IP when adding host
  * Support downloading binaries from rancher server when adding host
  * UI change for new adding host page
* Metadata service supported in windows environment
* DNS service supported in windows environment

**Comment by jinhong-** [comment]
Hey!
Just wondering, with the new enhancements in Windows 1709, would it be possible to see a future version of rancher with kubernetes in a mixed environment mode? Link below:
http://blog.kubernetes.io/2017/09/windows-networking-at-parity-with-linux.html?m=1

**Comment by orangedeng** [comment]
This feature will be close. All the needed issues and PRs have been closed and merge.
