### ISSUE TITLE
Scheduler constantly recreated

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#10444]
**Rancher versions:**
rancher/server: v 1.6.11
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.2
network-services: rancher/metadata:v0.9.5
scheduler: v0.8.2

**Type/provider of hosts: AWS**

**Setup details: HA rancher**

**Environment Template: Cattle**

The Scheduler is constantly re-created. If you upgrade a stack, service at the time the scheduler is down then container placement is not respected.

![rancher_scheduler](https://user-images.githubusercontent.com/1558372/33484531-efefa91e-d6a2-11e7-89d1-1dd099d6eb9b.png)

![rancher_scheduler_2](https://user-images.githubusercontent.com/1558372/33488126-f00ad6fa-d6af-11e7-9671-83dde0b8cbb5.png)

I'm also facing #10252 which might be linked

**Comment by cjellick** [comment]
what's in the logs for one of your scheduler containers?
If it is constantly being recreated, odds are it is having a networking problem. Do you notice any other networking issues in your environment?

**Comment by cjellick** [comment]
Nevermind, I see your logs in the other issue

**Comment by jean-francois-labbe** [comment]
Yes I just got the error now, and the container is removed then created.
But sometimes it stays down

**Comment by jean-francois-labbe** [comment]
![rancher_scheduler_restarts](https://user-images.githubusercontent.com/1558372/33515100-e73e641a-d75e-11e7-8247-65055958afca.png)

**Comment by jean-francois-labbe** [comment]
I got a lot of `Get http://rancher-metadata/2015-12-19/services: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"` in my load balancers

**Comment by mcanevet** [comment]
Same problem here with 1.6.12

**Comment by superseb** [comment]
How many hosts are there in the environment? Are the hosts under heavy load when it happens? If you can supply us with something to reproduce, we can investigate. Please report back if you are still facing issues.
