### ISSUE TITLE
Support per-host-subnet on windows environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10447]
related to https://github.com/rancher/rancher/issues/10442

Support per-host-subnet network model on windows.
* refer to https://kubernetes.io/docs/getting-started-guides/windows/ , use two NICs. One is for NAT and the other is for routing traffic between containers.
* NAT and port mapping are supported by windows RRAS NAT service.
* Routing is supported by windows RRAS routing service.

**Comment by deniseschannon** [comment]
Merged into Cattle. 

Closing as testing will be for overall windows experience and new issues will be filed.
