### ISSUE TITLE
UI Show pulled images for each host for re-pulling or deletion

### ISSUE THREAD

**Issue by themotu** [rancher/rancher#1044]
Sometimes I want to re-pull an image to have it ready to deploy faster or delete older images that are no longer being used to clear up host space.

**Comment by will-chan** [comment]
Yep, this is something we will work on shortly after beta.  Some type of image management on the host and/or GC policy to clean it up.

**Comment by will-chan** [comment]
#1277

**Comment by will-chan** [comment]
Closing and tracking with #1277
