### ISSUE TITLE
[Region] - Change helper text for Environment from being an id to name.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10457]
Rancher server version - v1.6-development

Go to "Add Load Balancer" page .
Use "Show region options" and add "Add selector Rule".
Helper text for Environment shows environment id .It needs to changed to reflect the fact that environment name has to be used entered.

**Comment by deniseschannon** [comment]
Available in the `stable` release of UI

**Comment by sangeethah** [comment]
@loganhz , I see the helper text for environment as "eg. uat" (not id anymore). Is this the suggested helper text for environment name ?

**Comment by loganhz** [comment]
@deniseschannon @vincent99 Can you provide the suggested  placeholder for the environment field in a LB port rule? Now it is `e.g. uat`.

**Comment by vincent99** [comment]
development?

**Comment by sangeethah** [comment]
Tested with Rancher server version - v1.6.13-rc3.
Helper text for environment shows "e.g development" .
