### ISSUE TITLE
2.0 - Improve status information about Kubernetes hosts

### ISSUE THREAD

**Issue by gtirloni** [rancher/rancher#10458]
The status shown in the Rancher UI doesn't machine the Kubernetes status (`kubectl get nodes`).

Sometimes the host is not even showing through `kubectl` but Rancher is reporting it as `active`.

There should be some distinction about a Rancher agent status and Kubernetes status.

**Rancher versions:**
rancher/server: 2.0.0-alpha10
rancher/agent: 2.0.0-alpha4

**Comment by deniseschannon** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM&t=4s) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!
