### ISSUE TITLE
DNS service support in windows environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10450]
related to https://github.com/rancher/rancher/issues/10442

* Adding CI process for DNS service.
* Using Powershell command to setup DNS service IP when starting this service.
* Because share network namespace is not supported in Windows docker, we use 169.254.169.251 as the DNS server ip. Different from Linux environment.
* Adding an infrastruct service for Windows environment project template.

**Comment by deniseschannon** [comment]
Available in `v1.6-development` branch. 

Closed as windows will be tested in its entirety and new issues will be filed.
