### ISSUE TITLE
Do not show "Show region options" in "Add Load Balancer" page when there is no regions entry.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10456]
Rancher Server build - v1.6-developement

"Add Load Balancer" page has  "Show region options" which should not be presented to the user unless there is atleast 1 region entry.

**Comment by loganhz** [comment]
fixed in https://github.com/rancher/ui/pull/1469/commits/bc448e9c472353d45b05b7d15c5338559ca5f3d3

**Comment by sangeethah** [comment]
With latest Rancher Server build from v1.6-developement
"Add Load Balancer" page does not has "Show region options" when there is no region entry.
