### ISSUE TITLE
Please move stack restart button into the ... menu. It looks like a refresh button.

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#10452]
After hitting refresh on catalog and getting stack up, waiting for container health, stack restart button was hit thinking it was a refresh button to get my CPU/NETWORK/STORAGE/MEMORY information.

Not sure why, the information does not appear to be connecting. Are there internal docker ports that need to be opened to get my statistics for CPU, memory etc.? 

Thanks.

I'm on the latest rancher.
Latest supported docker.

**Comment by aemneina** [comment]
do you have a load balancer in front of rancher?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
