### ISSUE TITLE
RancherUI containers tab: displayed container's IP is not refreshed after its network has been changed

### ISSUE THREAD

**Issue by vasmancs** [rancher/rancher#10467]
I moved user containers to a new network (connected to the new then disconnected from the old in CLI), however RancherUI still shows the old IP address (from the range of the old network that has already been deleted) even after server reboot.

When checking the IP address of that container in CLI (docker inspect) I can see only the new network's IP address, range, gw. Cannot find any reference to the old IP, network anywhere in the inspect result. 

Wondering where the RancherUI gathers this info from? Would be great if it were refreshing these info when opening the containers tab on the UI.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`containers.index`|

**Comment by superseb** [comment]
What does `moving user containers to a new network` mean? Are we talking about our own overlay network or you using Docker libnetwork network(s)?

**Comment by superseb** [comment]
Closing as stale.
