### ISSUE TITLE
Service pending in stopped status after host reboot

### ISSUE THREAD

**Issue by JialiangSong** [rancher/rancher#10465]
**Rancher versions:**
rancher/server: 1.4.3
rancher/agent: 1.2.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 14.04.4 LTS
4.2.0-040200-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
multiple nodes rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1) upgrade a service and do not "Finish upgrade" with service in "Upgraded" status
2) reboot the host on which the conatiners being upgraed locates
3) after the host complete reboot, the service is pending in stopped status, the upgraded container and the new created container are both in stopped status.

**Results:**
the service is pending in stopped status, while the expected status is, at least one containter, in running status

**Comment by JialiangSong** [comment]
This issue is reproduceable in rancher 1.4 and 1.6.

**Comment by vincent99** [comment]
This is intentional in 1.x, no further orchestration actions happen while a service is in upgraded state.  (In 2.0 there is no explicit finish action anymore so this is no longer applicable)
