### ISSUE TITLE
Need a quick option in UI to select distributing containers on different hosts or on different hosts of a certain label. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1046]
Build from master - Jun/04

If I have to distribute containers of a service with a specified scale to different hosts , I need to have a scheduling rule set as host must not have service name pointing to the service name that is being currently created.

This is not very intuitive.
This is a very common use case for scheduling that it may be good to provide this as an additional option to users , so that they have the ability to choose an option like "distribute containers of a service".

**Comment by sangeethah** [comment]
![screen shot 2015-06-04 at 10 52 30 am](https://cloud.githubusercontent.com/assets/4266958/7990744/ee7add5c-0aa7-11e5-9a3c-20aa86051a95.png)

**Comment by vincent99** [comment]
Is this just the $stack_name/$service_name variables?

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/1402
