### ISSUE TITLE
Getting client timeouts even with --wait argument

### ISSUE THREAD

**Issue by Somebi** [rancher/rancher#10469]
time="2017-12-01T10:58:45+02:00" level=error msg="Failed Starting myproject-api-web : Get http://19.16.28.131:8111/v2-beta/projects/1a54/services/1g508: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-12-01T10:58:45+02:00" level=error msg="Failed to start: myproject-api-web : Get http://19.16.28.131:8111/v2-beta/projects/1a54/services/1g508: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-12-01T11:08:50+02:00" level=fatal msg="Get http://19.16.28.131:8111/v2-beta/projects/1a54/services/1g508: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

**Comment by superseb** [comment]
This is the Rancher API not respoding in time/being under load/any other difficulties. We need a bit more info to reproduce and investigate.

Let us know if you can provide more steps to reproduce.
