### ISSUE TITLE
Add Pipeline page UI Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10477]
**Rancher versions:**v1.6.10

**Results:**

- [x] "Pipeline Name is required shows up when I first get into the page.  It should only show up if I click on Add and I don't have a Pipeline Name.
![image](https://user-images.githubusercontent.com/11514927/33345829-ec347dae-d44a-11e7-941e-e534dad4d47c.png)

- [x] Add/Cancel button should be on the bottom, center of page.  Not at top.  Also the error messages should be on bottom, not the top.
![image](https://user-images.githubusercontent.com/11514927/33345848-f93794e6-d44a-11e7-9142-6ff24b27b75a.png)

- [x] Remove SCM: so you can see more of the URL and change font size to smaller size.
![image](https://user-images.githubusercontent.com/11514927/33345916-28c4e24a-d44b-11e7-981d-db2dd0c4b4b5.png)

- [x] Should either make enough room for whole text or change the text to just say "Source Code"
![image](https://user-images.githubusercontent.com/11514927/33346122-e12dd0ee-d44b-11e7-9653-83937bf367e6.png)

**Comment by biblesyme** [comment]
We updated the deploy-guide yesterday(China Time). We currently just have one version in  catalog item. And we use `reg.cnrancher.com/pipeline/ui:v1.0` as the latest UI in catalog. So, I think your version of catalog is outdated, we will keep updating the environment (http://35.202.69.220:8080/) to the latest one. Could you please use this environment to test it, in case you are working on outdated version.

**Comment by biblesyme** [comment]
For the issue, 
`Remove SCM: so you can see more of the URL and change font size to smaller size.`

No matter how small it is, it's hard to show it all, So I added this tips to show it.

![image](https://user-images.githubusercontent.com/9334435/33658711-a5e4a9ae-dab8-11e7-8c92-ecc4a960d99f.png)

**Comment by tfiduccia** [comment]
Pipeline is required error message still at top.  Needs to be on bottom.

**Comment by biblesyme** [comment]
Sorry, I missed this one. Now, it's fixed.

**Comment by kingsd041** [comment]
Tested with rancher-server version- v1.6.13 with pipeline- v0.1.0
Test passed.
