### ISSUE TITLE
Container's metadata is not updated when restarting service in windows environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10471]
steps to reproduce
1. Create a service `microsoft/iis:nanoserver` with transparent network
2. Wait for service start success
3. Restart this service
4. After you wait for a long time and restart success, IP is not updated in UI or in metadata service.

But if I run a stand alone container, the metadata can be updated. 

OS: windows server 2016
Rancher server version: N/A
Docker version: 
```
Client:
 Version:      17.06.2-ee-4
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   dd2c358
 Built:        Thu Oct 12 16:16:50 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-4
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   dd2c358
 Built:        Thu Oct 12 16:25:33 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Comment by orangedeng** [comment]
I test it in v1.6.14 and I never get the same issue again.
@kingsd041 Can you help me to confirm this?

**Comment by kingsd041** [comment]
I did not encounter the same issue when testing on v1.6.14. 
Close it.
