### ISSUE TITLE
Ability to rotate IDP keys and secrets without disabling auth

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#10484]
When using SAML integration there doesn't appear to be a way to rotate the secrets/keys used to bind Rancher with the SAML provider without disabling auth controls and allowing unrestricted access to Rancher. For security interests it would be preferable to be able to do this without impacting access control.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
