### ISSUE TITLE
Host cannot be added by rancher-server!!!

### ISSUE THREAD

**Issue by tces1** [rancher/rancher#10480]
**Rancher versions:**
rancher/server: v1.6.12
rancher/agent:v1.2.7

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 83.92 GiB
Name: booster
ID: 24VK:XFK2:OF2A:GZSY:PIDZ:UEYV:25C5:RH7B:ZTKO:DW45:YY6Y:QN7H
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://10.158.100.8:8080/
Https Proxy: http://10.158.100.8:8080/
No Proxy: localhost,127.0.0.1,135.251.197.94,instance-data,169.254.169.254,.nsn-net.net,.nsn-rdnet.net,.ext.net.nokia.com,.int.net.nokia.com,.inside.nsn.com,.inside.nokiasiemensnetworks.com
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 135.251.197.94:1024
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-514.26.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add Host

**Results:**
CANNOT add success, always TIMEOUT 
**rancher-server process** 
io.cattle.platform.async.utils.TimeoutException: Timeout
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl.retry(RetryTimeoutServiceImpl.java:41)
	at sun.reflect.GeneratedMethodAccessor824.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**rancher-agent logs:**
time="2017-12-06T03:37:21Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:22Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:23Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:24Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:26Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=4 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:27Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=5 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:28Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=6 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:29Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=7 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:30Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=8 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:31Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=9 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:32Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=10 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:33Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=11 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:34Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=12 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:35Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=13 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:36Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=14 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:37Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=15 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:38Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=16 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:39Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=17 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:40Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=18 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:41Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=19 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:42Z" level=error msg="Failed to get connection token for host-api startup: Reached max retry attempts for getting token" 
time="2017-12-06T03:37:47Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:48Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:49Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:50Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid=16f0a1ad-b74a-44eb-4bab-136a74008cd4 
time="2017-12-06T03:37:51Z" level=error msg="Failed to get connection token for host-api startup: Failed to create hostApiProxyToken: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized, baseType=error] from [http://10.109.1.127:8080/v1/hostapiproxytokens]" 
time="2017-12-06T03:37:56Z" level=error msg="Failed to get rancher client for host-api startup: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized, baseType=error] from [http://10.109.1.127:8080/v1]" 
time="2017-12-06T03:38:01Z" level=error msg="Failed to get rancher client for host-api startup: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [baseType=error, code=Unauthorized, message=Unauthorized] from [http://10.109.1.127:8080/v1]" 
time="2017-12-06T03:38:02Z" level=error msg="Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized, baseType=error] from [http://10.109.1.127:8080/v2-beta/publish]" 
time="2017-12-06T03:38:02Z" level=error msg="Error processing event" err="Error sending reply fee17156-8e8c-4278-82a4-ea9bc68bba53: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized, baseType=error] from [http://10.109.1.127:8080/v2-beta/publish]" eventId=fee17156-8e8c-4278-82a4-ea9bc68bba53 eventName=ping resourceId=1a88 
time="2017-12-06T03:38:02Z" level=error msg="Error sending error-reply" err="Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized, baseType=error] from [http://10.109.1.127:8080/v2-beta/publish]" 
time="2017-12-06T03:38:06Z" level=error msg="Failed to get rancher client for host-api startup: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized, baseType=error] from [http://10.109.1.127:8080/v1]" 
time="2017-12-06T03:38:11Z" level=error msg="Failed to get rancher client for host-api startup: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized, baseType=error] from [http://10.109.1.127:8080/v1]" 
time="2017-12-06T03:38:15Z" level=error msg="checking aliyun cloud provider error after 2 attempts, last error: Get http://100.100.100.200/latest/meta-data/zone-id: dial tcp 100.100.100.200:80: i/o timeout" 
time="2017-12-06T03:38:16Z" level=error msg="Failed to get rancher client for host-api startup: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [baseType=error, message=Unauthorized, code=Unauthorized] from [http://10.109.1.127:8080/v1]"

**Comment by tces1** [comment]
?

**Comment by superseb** [comment]
Did you follow the suggestion in https://github.com/rancher/rancher/issues/10472#issuecomment-351108643?

**Comment by tces1** [comment]
I change the rancher server from http to https, solve this issue.
