### ISSUE TITLE
Can not switch to windows environment when editing project template

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10481]
**Rancher versions:**
rancher/server: 1.6.11
rancher/agent:N/A

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows

**Steps to Reproduce:**
1. Get in to `Manage Environments` page.
2. Click `Add template`
3. Click `Windows` template

**Results:**
It shows error 
```
Conflict
The currently enabled stack "Healthcheck Service" does not support Windows (Experimental) Orchestration.
```

**Comment by orangedeng** [comment]
@yasker @vincent99

**Comment by deniseschannon** [comment]
@loganhz can you take a look at this?

**Comment by deniseschannon** [comment]
@orangedeng please try with the `stable` release of UI

**Comment by orangedeng** [comment]
Problem still exists.
Steps to reproduce:
1. Get in to Manage Environments page.
2. Click Add template
3. Click Windows template

Result:
```
The currently enabled stack "Rancher IPsec" does not support Windows (Experimental) Orchestration.
```

**Comment by loganhz** [comment]
You can disable IPsec. IPsec is not required.

**Comment by orangedeng** [comment]
It can work. But I think there will be some enhancement for it.
I will file a new issue as the enhancement.

**Comment by encript** [comment]
I am not able to create Windows template using RancherOS 1.1.1 Rancher 1.6.12. I get the same error message. I can not disable healthcheck, network services or scheduler as they are required for one template but not for Windows. Please advise.

**Comment by ramalhais-sky** [comment]
I have the same issue using the current stable version (IIRC 1.6.12). I already have other environments created. Can this be the issue?

**Comment by ramalhais-sky** [comment]
Tested with a fresh stable version and it still doesn't allow me to create a Windows environment template

**Comment by ramalhais-sky** [comment]
rancher/server v1.6.13 already includes the default Windows environment template and i could also create a new windows environment template.
