### ISSUE TITLE
[Region]API should not allow for creating LB with port rules without environment when region is specified.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10487]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch

Steps to create the issues:
Create LB service having selector port rules without environment when region is specified using compose yml files.

LB creation is successful. But the selector labels are not getting applied to all environments in this region and Lb gets created with no backend targets.

LB creation should not succeed in this case.

**Comment by sangeethah** [comment]
@alena1108 , what is the expected behavior in this case ?
when region is specified ( and environment is not specified) , lb gets created successfully but with port rules not having regions  set .
Expected behavior should be to error out in this case ?

**Comment by alena1108** [comment]
@sangeethah just to confirm - this happens using rancher-compose. @kinarashah looks like rancher-compose resets the region when environment is empty. It should not do that. It should send it as it is, and then the validation will be done on API side.

**Comment by alena1108** [comment]
Looks like it was tested with non-updated rancher compose. Should be fixed once rancher-compose is updated.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.13-rc5 ( which has the rancher-compose executor that supports regions fields).

When trying to create a LB with port rules having region set but without environment , service creation fails with following error:
 
```Error (Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, baseType=error, fieldName=environment] from [http://localhost:8080/v2-beta/projects/1a69/loadbalancerservices])```
