### ISSUE TITLE
when add webhook api, The correct tag cannot be verified

### ISSUE THREAD

**Issue by gumutianqi** [rancher/rancher#10489]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: rancher/net:v0.13.5
network-services: v0.7.18

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux docker-171 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
When I add webhook, input that infomation:

```
Name: sb-hello
Kind: upgrade-service
Webhook Payload Format: Docker Hub
Image Tag: sxw/sb-hello:1.0.0
//...
//Other options use default values
```

**Results:**
Throw an error after confirmation, as this message:

Invalid tag sxw/sb-hello, tag length must be < 128, must contain [a-zA-Z0-9.-_] characters only, cannot start with '.' or '-'

**Comment by vincent99** [comment]
That is not a tag, it's an image (sxw/sb-hello) and a tag (1.0.0).

**Comment by gumutianqi** [comment]
@vincent99 Want how to set up, thank you!

**Comment by loganhz** [comment]
@gumutianqi You should input `1.0.0` in image tag field instead of a full image name . By the way, you can find Rancher China support team by searching `RancherLabsChina` in WeChat.
