### ISSUE TITLE
[Regions] "links" tab does not load properly when there are cross environment service links.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10491]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch

Steps to create the issues:
Create a service with cross environment service links.
Go to "links" tab of the container. Notice that the page does not load properly.

**Comment by deniseschannon** [comment]
Available in the `stable` release of UI

**Comment by sangeethah** [comment]
Tested with latest build from v1.6-development.
This issue is not seen anymore.Able to  show cross environment links in  "links" tab for service containers.
