### ISSUE TITLE
Incorrect MTU on veth interfaces on the host makes packets drop that are too large and not fragmented

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10498]
**Rancher versions:**
rancher/server: v1.6.12

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.2.1
network-services: v0.2.7
scheduler: v0.6.3

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Have seen two environments where this happened.

One was a container running a Go application trying to snmpwalk a network device, in the `tcpdump` output of `docker0`, we saw the response packet having a length of `1419`. The MTU on `eth0` inside the container is `1402` (`1500` - `98` overhead).

Another was an user running the setup from `rancher/vagrant` setup. Running curl with a small response succeeds `curl http://api.ipify.org`, but larger requests hangs (i.e. downloading ISO).

In both cases, forcing the veth interface (on the host) to MTU 1402 fixes this problem. We need to see if we can make this fix or what options we have. As they are tied to docker0 and that has a MTU setting as well. 

Possibly related: https://github.com/moby/moby/issues/12565

**Comment by jimrobinson-croud** [comment]
A temporary workaround from [https://github.com/moby/moby/issues/12565](https://github.com/moby/moby/issues/12565) seems to be to change the --mtu option for the docker daemon.

Using docker-machine:
```
docker-machine create --engine-opt mtu=1402
```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
