### ISSUE TITLE
Service link alias is not resolvable if the same service appears more than once in a list

### ISSUE THREAD

**Issue by xeagle2** [rancher/rancher#10494]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.1.4
network-services: 0.2.6
scheduler: 0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external database

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create external service "demo-service" and specify IP.
2. Create any service and add 2 service links

"demo-service" > "service1"
"demo-service" > "service2"

3. Run container, login to container and execute

$ ping service1
64 bytes from XX.XX.XX.XX: icmp_seq=1 ttl=64 time=0.041 ms
64 bytes from XX.XX.XX.XX: icmp_seq=2 ttl=64 time=0.037 ms

$ ping service2
ping: unknown host service2

**Results:**

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
