### ISSUE TITLE
UI will broke with Pipeline UI update

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10492]
refer to https://github.com/rancher/ui/commit/4b0d5f93657a3181b6e9846127df5ffbe2a05933

With this commit, UI will broke when we add  `service alias`.

Steps to reproduce:
1. use this commit
2. add stack
3. add service
4. add service alias or service link.

Result:
UI broke!

**Comment by deniseschannon** [comment]
@orangedeng  should be fixed in the `stable` release of UI

**Comment by deniseschannon** [comment]
@biblesyme @orangedeng if it works with the `stable` release, please close the issue. thanks!

**Comment by orangedeng** [comment]
Tested
