### ISSUE TITLE
Kubernetes dashboard would silently crash

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10493]
There were ~2000 evicted pods in the environment. When opening up the k8s dashboard it would go unresponsive. We were triggering the OOM killer for that container as 50mb was most likely a limiting factor. If users wanted to have an environment with 2k pods, it would most likely crash the dashboard as well... ideally we can surface the mem/cpu limits for this addon in the k8s template.

**Comment by deniseschannon** [comment]
Available with `v1.8.5-rancher1`

**Comment by soumyalj** [comment]
Tested with Kubernetes v1.8.5-rancher1. K8s template allows configuring memory and cpu limits for dashboard addon. Created a template configuring different values for memory and cpu. After K8s was deployed, the values were verified using `kubectl describe pod kubernetes-dashboard-7c99886798-m6wbx --namespace kube-system`
