### ISSUE TITLE
can read System resource consumption of container

### ISSUE THREAD

**Issue by 1026524749** [rancher/rancher#10496]
*Describe your issue here*
environment：ranhcer 1.6.3 docker 17.03.2 
使用rancher的cattle编排启动应用，会出现容器无法读取到cpu，内存等信息。docker stats命令也无法查询到。有些服务是全部容器读不到，有些是部分容器读不到，有些容器可以通过多次重启能拿到数据。
Using the rancher to deploy application, the container cannot read the CPU, memory, and so on. The docker stats command is also unsearchable. Some of the services are not readable in all containers, some are not readable in some containers, and some containers can be rebooted to get data.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.3` Cattle: `v0.181.13` UI: `v1.6.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by cjellick** [comment]
This issue isn't stated clearly enough to take action on and it seems to possibly report multiple problems. Could you break them down into separate descriptions with clear steps to reproduce and expected vs actual results?

**Comment by superseb** [comment]
Please report back if we can help.
