### ISSUE TITLE
Vault Volume Driver Tracking Issue

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#10500]
**Rancher versions:**
rancher/server:
>= 1.6.12

This issue is to track the creation of the Vault Volume Driver storage plug-in that will production ready Secrets-Bridge functionality.

Currently under development in `cloudnautique/vault-volume-driver`. Repo will be moved to Rancher Organization once a testable version is ready.

Rancher Catalog infra-template will be the release mechanism.

**Comment by cloudnautique** [comment]
Relies on PR rancher/storage#74

**Comment by cloudnautique** [comment]
Likely will need to fix: #8346

**Comment by deniseschannon** [comment]
Closing as any bugs found during testing will be opened separately.
