### ISSUE TITLE
" Invalid weight: " error message when trying to create Lb.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10501]
Rancher versions: cattle from v1.6-development

Steps to reproduce the problem:
Create LB service with portrules ( service rule / selector rule).
" Invalid weight: " error message is presented to user.

**Comment by loganhz** [comment]
Hi, @sangeethah . I can not reproduce this issue. What's your input for weight field?

**Comment by sangeethah** [comment]
@loganhz This is the case with no regions entry, so UI does not provide an option to enter "weight" field which is correct. But user gets "Invalid weight: " when he tries to create LB.

**Comment by sangeethah** [comment]
This issue is not seen in v1.6.13-rc3.
