### ISSUE TITLE
Support for Docker 17.12 (upcoming stable)

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10502]
Since 17.11.0, Docker is based on containerd 1.0 (beta). Logging of `rancher/agent` on Docker v17.12.0-ce-rc1

```
Found container ID: 65241c93d1071fdd4bc22fc38246b9229c8476e2800ed5d3847b3c8bb5277a7e
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
time="2017-12-09T10:16:10Z" level=fatal msg="Failed to find state.json"
```

New state path needed (`/run/docker/runtime-runc/moby`)

**Comment by jloisel** [comment]
:+1: docker-ce >= 17.11 currently doesn't work with Rancher V1.6.x.

**Comment by jloisel** [comment]
17.12 is official out since 2017-12-27:
https://docs.docker.com/release-notes/docker-ce/

**Comment by superseb** [comment]
Thanks, we got the fix ready for the next release.

**Comment by jloisel** [comment]
2.x or 1.6.x or both?

**Comment by vincent99** [comment]
1.6+Cattle; 2.0 is Kubernetes and they don't claim to support anything beyond 17.03.

**Comment by dhawton** [comment]
I keep seeing there is no support for docker beyond 17.03, but that contradicts the Rancher Docs... http://rancher.com/docs/rancher/v1.6/en/hosts/

**Comment by vincent99** [comment]
There is no contradiction, support in general for Cattle/Swarm (in the "Supported" column) and support for Kubernetes (in the "Kubernetes Supported" column next to it) are just not the same.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#external-dependencies

> The validated docker versions are the same as for v1.8: 1.11.2 to 1.13.1 and 17.03.x

**Comment by jloisel** [comment]
Thanks for the clarification Vincent.

**Comment by sangeethah** [comment]
Tested with v1.6.14-rc2 and rancher/agent:v1.2.9
Able to add hosts  with docker version - v17.12 successfully.

**Comment by IgorGrishkov** [comment]
Please open issue, don't work agent v1.2.9 with 17.12.0-ce, always restart and have bug how in head post:
```
Found container ID: 52f514f0d09055e5b370744e038cec7d341cddf3a1bd51a0b2307430e67fbf63
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
Checking root: /host/run/docker/runtime-runc/moby
time="2018-01-15T17:28:03Z" level=fatal msg="Failed to find state.json" 
```

Start in:
**Docker machine:**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.108-boot2docker
Operating System: Boot2Docker 17.12.0-ce (TCL 8.2.1); HEAD : 378b049 - Wed Dec 27 23:39:20 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955GiB
Name: worker1
ID: LRGO:AMZB:FHA4:KW75:LKGT:55N5:WZK4:OM6L:FWSB:MAC4:HTVH:VHIX
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 39
 System Time: 2018-01-15T18:07:59.505754172Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: true
Insecure Registries:
 192.168.111.130:55555
 127.0.0.0/8
Live Restore Enabled: false
```

**Rancher server:**

```
Rancher | v1.6.14
Cattle | v0.183.37
User Interface | v1.6.37
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5

```
**Rancher agent:**

`rancher/agent:v1.2.9`

Or maybe I'm not full understand??? And need wait new release where fix it this problem?)

**Comment by jloisel** [comment]
Works for me. Tested on Ubuntu 16.04.3 LTS with docker 18.01-ce and Rancher 1.6.14.

**Comment by IhorHryshkov** [comment]
@jloisel Very interesting. In 16.04.3 LTS with docker 17.12.0-ce works fine but in Boot2Docker image(docker-machine with virtualbox driver) with docker 17.12.0-ce or 18.01-ce have this problem but in Boot2Docker docker 17.09.1-ce works fine, it's magic))) Ok, maybe this problem in Boot2Docker. I will watch the logs and look for the problem, while use 17.09.1-ce. Cheers.

**Comment by laibulle** [comment]
I have the same issue using Rancher 2.0 and docker 17.12.0-ce

```
Found container ID: xxxxxxxxxxxxxxxxx
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
time="2018-01-18T15:19:04Z" level=fatal msg="Failed to find state.json"
```

Rancher agent version: rancher/agent:v2.0-alpha4
Rancher version: rancher2.0.0-alpha-10.

It used to work with docker 17.05 but it displayed a message saying 'unsupported docker version in the rancher UI'.

**Comment by adityapatadia** [comment]
I still face this issue on rancher 1.6.14 and agent version 1.2.9. I use Nvidia runtime, does it make any difference? https://github.com/NVIDIA/nvidia-docker

**Comment by floranger** [comment]
As @adityapatadia stated, I use Nvidia runtime and I cannot add a host too.

**Docker info:**
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 178
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f-dirty (expected: b2567b37d7b75eb4cf325b77297b140ea686ce8f)
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.787GiB
Name: ams-1
ID: 5DQR:QSG3:AO7F:XXXL:TVOM:H6DX:ILVZ:TGA4:2V5D:KSP7:OP6L:3M7Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
WARNING: No swap limit support

**Rancher Server version:**
Rancher | v1.6.14
Cattle | v0.183.37
User Interface | v1.6.37
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5

**Rancher Agent image:**
rancher/agent:v1.2.9

**docker logs rancher-agent:**
Found container ID: aa2c2211797e8485ec1b2110a49e26fb88c8da3d6614af8be11c77ac3cc1d8c3
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
Checking root: /host/run/docker/runtime-runc/moby
time="2018-02-16T17:28:00Z" level=fatal msg="Failed to find state.json"

**Comment by superseb** [comment]
@floranger If you can send me the output of `find / -type f -name state.json` from the host, the path can be added. Not familiar with nvidia runtime.

**Comment by floranger** [comment]
@superseb 
/run/docker/runtime-nvidia/moby/9fc0fc5f76d4e0df4db5a4df9b27ecad762ebcfa1e038601999ad5e7becf06d9/state.json

**Comment by superseb** [comment]
@floranger Created https://github.com/rancher/rancher/issues/11467

**Comment by dahuzi998** [comment]
hi, i change the default Docker Root Dir: /var/lib/docker  to Docker Root Dir: /export/docker/lib,
docker agent log msg="Failed to find state.json"
