### ISSUE TITLE
Restored container cannot use active credentials.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1050]
v0.23.0-rc4

Steps To Reproduce:
1. Add a container from private registry that requires credentials
2. Restore the errored container
3. Add credentials to registry
4. Start the container

Result: Container will still be in error state saying that there are no permissions.

Expected Result: If I restore and add credentials, it should attempt to re-pull the image.

Note: If we aren't going to support, what is the purpose of having restore for a container?

**Comment by will-chan** [comment]
Not sure what you did here Denise.  Did you add a registry with credentials set 1 and later added credentials set 2?

**Comment by deniseschannon** [comment]
When a container is in error state, you have the ability to "Restore" in the dropdown. From there, you can start the container. 

Basically, I used an image that required permissions, noticed that the container was an error due to my permissions, restored the container to prevent it from being purged. Added appropriate credential and tried to start the stopped container.

**Comment by vincent99** [comment]
This doesn't really make sense.. If the container failed to create then you shouldn't be able to restore it, it should go to a (non-existent at the moment) `error` state.  And from that state you should be able to Clone in the UI but not `restore`.

**Comment by vincent99** [comment]
Should address in #384

**Comment by alena1108** [comment]
Today if instance fails to create, it goes to Error state. And from error state, there is no way to restore it. @deniseschannon can you verify

**Comment by deniseschannon** [comment]
Verified with v0.63.0. 

With the introduction of the Error state, there is no ability to restore from error state.
