### ISSUE TITLE
[Load Balancer] Cannot prevent 504 for long running HTTP requests

### ISSUE THREAD

**Issue by yatesco** [rancher/rancher#10503]
**Rancher versions:**
rancher/server:latest
rancher/agent:1.2.7

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec:0.13.5
network-services:0.9.5/0.7.18
scheduler:0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 20
 Running: 18
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 188.8GiB
Name: rincewind
ID: 5EOV:7PXQ:K3VU:2PUM:UHUK:6OUW:N3SN:A6PR:R73Y:ONKV:UEKX:NFQ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
`uname -r` = `4.4.0-103-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single rancher server with a single host
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Setup rancher, configure a web server for a request that takes > 3 minutes to run, add loadbalancer and then call the URL.
**Results:**
504 is returned and the destination container serving the request is restarted

Hi all - loving Rancher!

However, I can't figure out how to increase the proxy timeouts. I need to configure them so they don't terminate after a few minutes. 

I have tried adding the following to the `haproxy.cfg` in the loadbalancer:
```
defaults
        timeout connect 3600000
        timeout client 3600000
        timeout server 3600000
```
which didn't make any difference - the container was restarted after ~2 minutes.

I then configured the `health-check` not to restart containers but after ~5 minutes a `502` is then returned.

I have read the documentation but can't figure out what is needed. And no, "write better services" isn't an option ;-).

Suggestions please.

**Comment by superseb** [comment]
Are we talking about using Rancher loadbalancer (`lb-service-haproxy`) and change config settings on that or are you talking about the healthcheck containers which are checking the configured healthchecks?

**Comment by yatesco** [comment]
Hi @superseb - it was a while ago, but I recall adding the config to the `lb-service-haproxy`.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
