### ISSUE TITLE
Rancher Agent on boot2docker can't find state.json

### ISSUE THREAD

**Issue by Lerentis** [rancher/rancher#10509]
Hello there,

I tried to set up a infrastructure with boot2docker on VMs and Rancher, but when i try to add the boot2docker instances to rancher i get the error that a `state.json` could not be found and the rancher agent restarts forever. any hints how to debug this or is this a known limitation while working with boot2docker?
on the same infrastructure with ubuntu VMs it works as expected.
i also tested it with two PCs i got laying around on bare metal with the same result.

**Rancher versions:**
rancher/server:stable
rancher/agent:v1.2.7

**Infrastructure Stack versions:**
all up to date

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:32:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:39:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.4.100-boot2docker
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

* Bare-metal 
* ESXI VM's

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher server and agent on boot2docker

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

* Cattle

**Steps to Reproduce:**

Try to start rancher/agent on a boot2docker host

**Results:**
* docker run ...
```
INFO: Running Agent Registration Process, CATTLE_URL=<>
INFO: Attempting to connect to: <>
INFO: <> is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: true
INFO: Host writable: false
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=A311D6282FFF5F397607
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=<>
INFO: ENV: DETECTED_CATTLE_AGENT_IP=<>
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.7
INFO: Launched Rancher Agent: de8da5e2522a55a4e674f511d51b22dd1275e1ac4f55d54bd07c2c9f7818a321
```
* docker logs rancher-agent
```
Found container ID: 5c0fe225d89cac52a6baad273678e374645d8cdfea3a00315da5fbdc9da9a12f
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
time="2017-12-11T11:15:36Z" level=fatal msg="Failed to find state.json" 
Found container ID: f3966138685d4bf2ea2283a84f6b431eef35fde7bdda5e690e1ba7333ee31b54
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
time="2017-12-11T11:16:36Z" level=fatal msg="Failed to find state.json" 
```

**Comment by superseb** [comment]
As 17.11 is an edge release, we don't support it. Support for 17.12 is being tracked in https://github.com/rancher/rancher/issues/10502

**Comment by adityapatadia** [comment]
I still face this issue on rancher 1.6.14 and agent version 1.2.9

**Comment by dlednik** [comment]
I see the same issue on fresh Ubuntu Server 17.10 install. I was preparing new installation as I want to use nvidia-docker too. But rancher agent keeps restarting with `Failed to find state.json` error.

**Comment by superseb** [comment]
@dlednik You need `rancher/server:v1.6.14` and `rancher/agent:v1.2.9` for this to work with Docker 17.12. I just tested it on with Ubuntu 17.10 and it worked. Please double-check the agent version you are using.

**Comment by dlednik** [comment]
@superseb Thanks, will check in the evening when I get to my server 👍

**Comment by zot24** [comment]
I'm still seeing the `Failed to find state.json` error with `rancher/server:v1.6.14`, `rancher/agent:v1.2.9` and https://github.com/docker/toolbox/releases/tag/v17.12.0-ce 

However I'm using the boot2docker version that comes with ☝️ and no Ubuntu @superseb

**Comment by superseb** [comment]
@zot24 Please see https://github.com/rancher/rancher/issues/10970

**Comment by zot24** [comment]
Just saw the new issue https://github.com/rancher/rancher/issues/10970 👍

**Comment by saikaushik-itsmyworld** [comment]
I'm using the ubuntu 16.04 and rancher/agent:v1.2.5 and still facing the same issue. rancher agent keeps restarting with Failed to find state.json error.
