### ISSUE TITLE
rancher-ha config script forgets about the starting rancher version

### ISSUE THREAD

**Issue by charandas** [rancher/rancher#10512]
**Rancher versions:**
rancher/server: v1.0.2
rancher/agent: N/A (during the HA setup phase)

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Docker version 17.09.0-ce, build afdb6d4
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.4.0
VERSION_ID=1576.4.0
BUILD_ID=2017-12-06-0449
PRETTY_NAME="Container Linux by CoreOS 1576.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare ESXi

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1. Follow official instructions [here](https://rancher.com/docs/rancher/v1.0/en/installing-rancher/installing-server/multi-nodes/) and get to the step where `rancher-ha.sh` is downloaded. NOTE: the config gen rancher server ran `rancher/server:v1.0.2`
2. Bring down the config gen server, and run the `rancher-ha.sh` script.

**Results:**
1. It goes ahead and downloads `rancher/server:latest`, giving errors such as:
```
core@localhost ~ $ docker logs -f rancher-ha
/usr/bin/entry: line 119: exec: ha: not found
```
2. Errors do not happen if I do:
```
sudo /var/lib/rancher/bin/rancher-ha-start.sh rancher/server:v1.0.2
```

**Comment by aemneina** [comment]
Please dont use rancher 1.0.2, its quite dated at this point. The latest stable is 1.6.12.

**Comment by superseb** [comment]
Rancher v1.0.2 is 1.5 years old, and in v1.2 HA was completely re-done (https://github.com/rancher/rancher/releases/tag/v1.2.0). We can't fix anything into this deprecated part of HA logic.

I highly recommend to upgrade to a recent version (v1.6), as there are many many improvements.

**Comment by charandas** [comment]
Thanks. Need to pay attention to:

>These docs are for Rancher v1.0, for the current version, see here.

on top of docs pages. Thanks @superseb @aemneina
