### ISSUE TITLE
applications always remain "Removing", and can not be removed

### ISSUE THREAD

**Issue by nefuddos** [rancher/rancher#10518]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha10` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`apps-tab.index`|

**Comment by superseb** [comment]
There have been major changes since this tech preview, please try the latest (`v2.0.0-alpha23`, https://forums.rancher.com/t/rancher-tech-preview-update-3-26-2018/9893) and file a new issue if you run into trouble.
