### ISSUE TITLE
A packet sent to the exposed port was sent back towards the router with the 10.42.x.x IP address.

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#10511]
Possible reason/theory:

```- After reboot of the host, docker0 doesn't have 10.42.0.1/16 IP address.
- From outside of the host, try to send continuous packets to load balancer. (Ex: while true; do curl http://HOSTIP:11000; sleep 1; done)
- Start docker.
- Depending on the order in which the containers come up and the go routines inside the "network-manager" start, there can be a very small window when the hostnat/hostport iptables rules are configured on the host but the 10.42.0.1/16 IP address is not configured on the docker0 bridge.
- At this point, the packets sent to HOSTIP:11000 get DNAT'ed to CONTAINERIP(10.42.x.y):11000 due to the iptables rules, but there is no route on the host for 10.42.0.0/16. So the default gateway is used to send this packet.```

**Comment by leodotcloud** [comment]
Steps:
Click on Stacks > Infrastructure Stacks
Expand “network-services” stack
Click the Upgrade button (button with an up arrow inside a circle) next to “network-manager” service.
In the service upgrade page, change the image under “Select Image” to the leodotcloud/network-manager:10511_v0.1
Click Upgrade
 
The private image and instructions to upgrade have been sent to the original reporter. Waiting for him to test out the changes.

@chrisurwin can you please follow up?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
