### ISSUE TITLE
[rancher-dns] How to add new service label to override externalIP

### ISSUE THREAD

**Issue by thejmazz** [rancher/rancher#10515]
I made a [fork](https://github.com/thejmazz/external-dns/tree/service-external_dns_ip) of external-dns, and thought I added the correct code to be able to have `io.rancher.server.external_dns_ip` take precedence over `io.rancher.host.external_dns_ip`, but from building + pushing my fork (`dapper -s`, `export REPO=thejmazz`, `./scripts/ci`, `docker push` on host), I don't see it working. My diff was:

```
 			var externalIP string
-			if ip, ok := host.Labels["io.rancher.host.external_dns_ip"]; ok && len(ip) > 0 {
+			
+			// Allow setting IP from service label
+			if service_provided_ip, ok := service.Labels["io.rancher.service.external_dns_ip"]; ok {
+ 				externalIP = service_provided_ip
+			}
+			
+			if ip, ok := host.Labels["io.rancher.host.external_dns_ip"]; ok && len(ip) > 0 && len(externalIP) == 0 {
```

Am I doing something wrong? Is their other code overwriting this, have I modified in the wrong place?

Thanks

**Comment by thejmazz** [comment]
ping @alena1108 :p

**Comment by superseb** [comment]
If you are not seeing the error here (https://github.com/thejmazz/external-dns/blob/6a56f3f09b02d8c8c18e4163c28e780169c4afc0/metadata/metadata.go#L155), then it either gets overwritten by https://github.com/thejmazz/external-dns/blob/6a56f3f09b02d8c8c18e4163c28e780169c4afc0/metadata/metadata.go#L144 or https://github.com/thejmazz/external-dns/blob/6a56f3f09b02d8c8c18e4163c28e780169c4afc0/metadata/metadata.go#L151. Addind a few debug lines should be enough to figure out what the content of `ExternalIP` is at various moments.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
