### ISSUE TITLE
[API Interceptor] -"Method not allowed" error when trying to add a member to exitsing environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10513]
Rancher server versions: v1.6.13  (Also seen with cattle build from v1.6-development)

Steps to reproduce the problem:
Have api.interceptor.config set to 
```
{
    "requestInterceptors": [
      {
            "type": "authTokenValidator",
            "paths": [
                "/v2-beta/project", "/v2-beta/projects",
                "/v2-beta/projecttemplate", "/v2-beta/projecttemplates",
                "/v2-beta/projects/{path:.*}",
                "/v2-beta/projects/{path:.*}/{path:.*}",
                "/v2-beta/projects/{path:.*}/{path:.*}/{path:.*}",
                "/v2-beta/projects/{path:.*}/{path:.*}/{path:.*}/{path:.*}",
                "/v2-beta/projects/{path:.*}/{path:.*}/{path:.*}/{path:.*}/{path:.*}",
                "/v2-beta/projects/{path:.*}/{path:.*}/{path:.*}/{path:.*}/{path:.*}/{path:.*}",
                "/v2-beta/projects/{path:.*}/{path:.*}/{path:.*}/{path:.*}/{path:.*}/{path:.*}"
            ],
            "endpoint": "",
            "methods": [ "post", "put", "delete" ],
            "secretToken": ""
      }
  ]
}
```
Enable Auth.
Try to add a member to existing environment.

User is presented with "Method not allowed" error:
```
Request URL:http://<ip>:8080/v2-beta/projects/1a5
Request Method:PUT
Status Code:405 Method Not Allowed
Remote Address:<ip>:8080
Referrer Policy:no-referrer-when-downgrade
```

**Comment by prachidamle** [comment]
As analysed this issue is also seen with 1.6.12, so not something introduced with recent interceptor fixes.

**Comment by soumyalj** [comment]
The same issue is seen in v1.6.26-rc4

**Comment by alena1108** [comment]
@soumyalj could you post the exact error you are seeing

**Comment by alena1108** [comment]
@prachidamle we should look into this issue

**Comment by soumyalj** [comment]
When I add new members or remove members in the setup with interceptors, the error message seen is below:
```
id: "e853aef5-3df3-40b5-867d-3072b5edffcb", type: "error", links: {}, status: 422,…}
actionLinks: {}
baseType: "error"
code: "ActionNotAvailable"
detail: null
fieldName: "action"
id: "e853aef5-3df3-40b5-867d-3072b5edffcb"
links: {}
message: null
status: 422
type: "error"

```
<img width="803" alt="screen shot 2019-01-25 at 2 58 51 pm" src="https://user-images.githubusercontent.com/18536626/51777392-c3ee8600-20b1-11e9-962e-c244fb9226be.png">

**Comment by alena1108** [comment]
Can be tested on `rancher/server:v1.6.26-rc6`

**Comment by soumyalj** [comment]
Tested with v1.6.25-rc6. 
Created cattle environment and enabled AD auth in the setup
Added and deleted members to the environment successfully. The errors above did not show up.
