### ISSUE TITLE
lb-service does not create links from selector-rules at runtime, but on startup

### ISSUE THREAD

**Issue by thomasbuengener** [rancher/rancher#10523]
**Environment:**
rancher/server: v1.6.12
lb-services: lb-service-haproxy:v0.7.15 (on both A and B)
using Cattle 

**Situation:**
We have one central lb-service (A) which has a selector rule with target = "publichost=true" and 
"hostname=*.mydomain.com".

We have many lb-services (B1,B2,B3,...) labeled "publichost=true" and hostname="Bx.mydomain.com".
Routing works correctly by hostname from A to B for all Bs. 

LB A will pick up all Bs correctly, create the routing information and links to Bs upon startup.

**Problem:**
Whenever we add a new  lb-service (e.g. B4) with label "publichost=true" at runtime, the routing A to B works ok, but A does not create a link to B4 as it should and did with previous Rancher versions. (visible via the UI under the "links" tab in LB A). 
It doesn't make a difference wehter B is create manually on the UI or via rancher-compose.

This leads to a problem when the rancher/network-policy-manager:v0.2.4 ist configured to allow communication between linked services only, as the missing link from A to B obviously prevents the communication from A to B. A will try to communicate with B correctly, but is not allowed to do so because of the missing link.

**current workarounds: (not very viable)**
1) Disable restricted network policy which we obviously do not want. 
2) When de LB A ist restartet, the link will appear after restart - as manual restart will disrupt communication with other services and is also not an acceptable solution.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
