### ISSUE TITLE
Rancher API v3

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1052]
As we change names of fields and types in the UI we should rename them in the API to match before a general availability release.  This issue will track all those things.
- [x] `create`, `update`, and `remove` shouldn't appear as actions (requires #384).
- [ ] `project` -> `environment` ("UI Environment")
- [x] `environment` -> `stack` ("UI Stack")
- [ ] `dnsService` -> `aliasService`
- [ ] `pidMode`: add "new" option instead of being nullable
- [x] `service` label `io.rancher.environment.name` -> project
- [x] ~~`service` links `consumed[by]services` -> `consumed[By]Services`~~ n/a
- [x] ~~LBConfigs, reusing configurations, first-class listeners, etc.~~ Remove standalone loadBalancers in general.
- [ ] Registries have multiple credentials as first-class objects but we only want people using one.
- [x] `id` fields are marked `type: int` in schemas, should be `type:string`
- [ ] sort keys in maps (`links`, `actions`)
- [ ] `tokens` and authConfigs are collections of always one thing.  Should just be a resource.
- [ ] Admin sees every type at version-root level, including all the resources owned by project/environments.
- [x] ~~Pagination + Include is weird.  It should "round up" (or down) to the nearest complete main resource, not break in the middle of a collection of included resources and then send a different copy of the main resource with different included resources on the next page.~~ Clients should just not do that
- [x] Embedded types do not have a `type` field to tell what type they are (without looking at the type of the field in the parent schema)
- [x] Turn off returning recently removed/purged resources for X minutes by default.  It's more confusing than helpful, but could be opt-in with a setting or an `X-API-Recently-Deleted: true` header.
- [ ] Show `type` in schema
- [ ] Standardize all actions to camelCase
- [x] `degraded` is a fake state calculated by the UI instead of a real one in the API
- [ ] remove `all=true/false` magic filters on projects/preferences, make a real property for belongs to me and support a real filter on it.

**Comment by sshipway** [comment]
It would be useful if Certificate objects had a field containing number of seconds until expiry (or 0 if expired).  While it does have expiryDate, this is as a string which needs to be parsed and compared to the current date/time in order to calculate expiry.  Having a 'secondsUntilExpiry' attribute would greatly simplify monitoring tools using the API.
