### ISSUE TITLE
Rancher Certified, Community catalog and custom templates not showing up after enabling them.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10525]
**Rancher versions:** 2.0 master 12/12

**Steps to Reproduce:**
1.  Go to Global/Catalogs
2.  Enable Rancher Certified and Community catalogs
3.  Go to Project/Catalog Apps
4.  Click on Launch
5.  Refresh screen

**Results:**  Rancher Certified and Community catalog templates don't show up.

**Comment by vincent99** [comment]
This appears to be because nothing supports converting `${RELEASE}` to an actual branch name.

**Comment by StrongMonkey** [comment]
old catalogs are gone now :)

**Comment by deniseschannon** [comment]
As of now, we plan on not supporting the old catalogs.
