### ISSUE TITLE
After I delete/disable a catalog, a get is called and fails with 500 error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10527]
**Rancher versions:** 2.0 master 12/12

**Steps to Reproduce:**
1.  Add a catalog
2. Open dev tools
3.  Delete the catalog

**Results:**  Catalog is deleted then a Get is called which ends up throwing a 500 (internal Server error) in the dev tools

**Comment by mumutu66** [comment]
similar problem  the wrong record in cattle.catalog was not removed

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified fixed
