### ISSUE TITLE
Web-hook Deploy Broken

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#10524]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node / external db
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
use web-hook to auto deploy a group of services...give each service a different command
**Results:**
dockerhub fires webhook....rancher upgrades...the commands are randomly changed to that from another service

**Comment by cristianbica** [comment]
Happens with the latest 1.6rc (v1.6.15-rc4). Issue seems to be in the code here: https://github.com/rancher/webhook-service/blob/v1.6/drivers/service_upgrade.go#L201-L279.
Based on the order the services are restarted it will merge and override service config from one service to another (cmd, entrypoint, labels)

**Comment by SashaSirotkin** [comment]
Still is an issue `1.6.16`. We upgraded from `1.6.10` two days and may need to revert due to this bug.

**Comment by Scentyoo** [comment]
Could you please fix this?

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.26-rc1`

**Comment by gitlawr** [comment]
Steps to reproduce:
1. Create a stack.
2. Add a service with name=`ngx1`, image=`someprivate/nginx`, command=`nginx -g "daemon off; env test=1;"`, label=`test=true`
3. Add a service with name=`ngx2`, image=`someprivate/nginx`, command=`nginx -g "daemon off; env test=2;"`, label=`test=true`
4. Add a webhook to upgrade services with selector `test=true`, tag `latest`
5. push an image to `someprivate/nginx` repo
6. After these services are upgraded, check their commands.

Result:
You may see that command of `ngx1` changes to `nginx -g "daemon off; env test=2;"`, or ngx2's command changes, randomly.

**Comment by ItsReddi** [comment]
And the other Bug: #11588

1. Create a stack.
2. Add a service with name=ngx1, image=someprivate/nginx, label=test=true, drainTimeout=5000
4. Add a webhook to upgrade services with selector test=true, tag latest
5. push an image to someprivate/nginx repo
After these services are upgraded, check the draintimeout.

**Comment by bacheson** [comment]
blast from the past...I can't believe this wasn't fixed yet....I'm so glad I moved to Google Kubernetes Engine long ago...so much better/easier

**Comment by soumyalj** [comment]
Reproduced the issue in v1.6.25.
Tested with v1.6.26-rc1 with the steps below:
1. Create a stack.
2. Add a service with name=ngx1, image=someprivate/nginx, command=nginx -g "daemon off; env test=1;", label=test=true
3. Add a service with name=ngx2, image=someprivate/nginx, command=nginx -g "daemon off; env test=2;", label=test=true
4. Add a webhook to upgrade services with selector test=true, tag latest
push an image to someprivate/nginx repo

After the services are upgraded, the commands do not change.

**Comment by soumyalj** [comment]
Specified a drain timeout while creating the services with image=abc/nginx with label set as "test=true"
Added a webhook to upgrade services with selector "test=true". Push an image to abc/nginx repo.
After upgrade, the drain timeout setting is lost.

**Comment by soumyalj** [comment]
Tested with v1.6.26-rc2.
Specified a drain timeout while creating the services with image=abc/nginx with label set as "test=true"
Added a webhook to upgrade services with selector "test=true". Push an image to abc/nginx repo.
After upgrade, the drain timeout setting was retained as expected.
