### ISSUE TITLE
Add labels error when add host in windows environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10521]
**Rancher versions:**
rancher/server: 1.6.13-rc2
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows

**Steps to Reproduce:**
1. Add label, e.g. `k=k`
2. change current label, e.g. `k=kk`
3. keep changing current label, eg, `kk=kk`

**Results:**
you would see more than one labels in run cmd of `step 7` .

**Comment by kingsd041** [comment]
Tested with Rancher/server:1.6.13-rc3.
Test passed.
