### ISSUE TITLE
If template is missing config, it doesn't show up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10530]
**Rancher versions:** 2.0 master 12/12

**Steps to Reproduce:**
1.  Create a catalog template that is missing the config.yml
2.  Add that catalog
3.  Go to Catalog Apps

**Results:** Template doesn't show up.  It did show up in 1.6, not sure if we are still supporting this or not.

**Comment by StrongMonkey** [comment]
we need to discuss with @ibuildthecloud. Right now the old catalog is gone.
