### ISSUE TITLE
Kind is not being return so can't change catalog to Helm

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10531]
**Rancher versions:** 2.0 master 12/12

**Steps to Reproduce:**
1.  Create a custom catalog and change the Kind to Helm

**Results:**  Post is sending Helm but response doesn't have Kind, so it just reverts back to Native.

**Comment by StrongMonkey** [comment]
should be fixed in master now

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
