### ISSUE TITLE
Error in server logs

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#10539]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:v0.13.5
network-services:
rancher/metadata:v0.9.5
rancher/network-manager:v0.7.18
scheduler:v0.8.2
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```bash
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1043-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.9MiB
Name: ip-10-0-0-58
ID: OGE4:6JUL:LEEA:QTOD:NDQC:UE2E:5OLE:I3VL:4YIK:DLHY:PNDH:NONJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ uname -r
4.4.0-1043-aws

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
The Rancher server is behind a classic ELB with SSL termination (on the ELB)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
For the time being, just the Rancher Server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
1. Log in to the host running the rancher/server container
2. Get the id of the rancher/server container
3. execute `docker logs -f <container_id>`

**Results:**
The following string keeps appearing in the logs

```
time="2017-12-13T10:03:27Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
```

Just before the first occurrence of the above error, the following error came up first:

```
2017/12/13 10:01:22 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"; err=<nil>
```

The ui seems to be working properly in the mean time (at least for some rudimentary operations we have performing so far.

**Comment by superseb** [comment]
I've seen `Error looking up token.` when the Kubernetes environment is not yet active. Do you see this from scratch? (with the Default cattle environment?)

**Comment by pkaramol** [comment]
@superseb I am currently unable to check the logs with only the default (cattle) env present since I am in the middle of a k8s env set up process.

What I can verify is that it **does** appear when the k8s env becomes active (the dashboard and the cli are available and responsive now) and the error keeps coming up

i.e. now only the following line:

```
time="2017-12-29T10:55:21Z" level=error msg="Error looking up token." error= 
```

**Comment by superseb** [comment]
Do you have any other k8s environments that could trigger this? I think we can make the logging better, to include k8s env not being ready.

**Comment by pkaramol** [comment]
No, for the time being only the default / cattle and an extra k8s I am working on.
Sorry.

**Comment by superseb** [comment]
The reason for this "should" be that kube-apiserver is unreachable to retrieve information in any k8s env. If there is a reproducible scenario to trigger it without this condition, let me know how to reproduce so we can investigate.
