### ISSUE TITLE
v2.0 - Compose YAML doesn't save name/description/tags

### ISSUE THREAD

**Issue by naisanza** [rancher/rancher#10535]
**Rancher versions:**
rancher/server: 
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 90
 Running: 69
 Paused: 0
 Stopped: 21
Images: 22
Server Version: 17.09.1-ce
Storage Driver: zfs
 Zpool: turtle
 Zpool Health: ONLINE
 Parent Dataset: turtle/_ubuntu/rancher/docker
 Space Used By Parent: 27648
 Space Available: 11709249370624
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 17.64GiB
Name: bigma
ID: UWKU:2Q36:44LW:HH6M:5DI3:YERH:WHCZ:YT5X:LDP2:QP4F:7Y4W:BHS2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.4.0-98-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
Bare-metal
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
```
Ubuntu 16.04 server
Docker-CE (latest)
docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview
```

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
```
Rancher 2.0 default
```

**Steps to Reproduce:**
The Compose YAML doesn't save tags

**Results:**

**Comment by vincent99** [comment]
Compose files describe the resources _inside_ a stack.  Name, description, tags (which is "group" in the API), etc are properties _of_ an instance of a stack itself.

**Comment by naisanza** [comment]
@vincent99 I suppose you're right about that, but from a user experience, why not just one-single Compose YAML to just export everything, rather than each stack one-by-one.

Also, if the stack is relevant only to Rancher, and not Kubernetes, why not just add it into the Compose YAML as comments, which would be ignored by Kubernetes, but not to Rancher.

And also, really well done on the interface, it's very nice to use.

**Comment by vincent99** [comment]
Because the same compose file can be deployed multiple times to make multiple stacks, which can each have their own name, description, tags, etc.

In the current 2.0 preview, a Rancher Environment is a K8s Namespace, but that doesn't really work very well because you can't e.g. deploy the same stack twice (all the names have to be unique within a namespace).  In 2.0-preview2+ a stack _is_ a namespace and an Environment (which will be called Project now) is a collection of namespaces.

**Comment by naisanza** [comment]
@vincent99 its nice being able to filter across stacks. I was using namespaces and switched to stacks because of this.

How do you manage the ports bring used and not used? Can there be a future where loadbalancers assign a hostport automatically? There isn't a way to know which hostport are free unless you dig around, or pick one and increment when the service fails

**Comment by naisanza** [comment]
@vincent99 the Compose file was nice when I wanted to rip down and rebuild all of docker and rancher again. 

That's why I was asking for a single compose file to be used as a full single backup.

Destroy a host and cluster, and restore it back to 100% with a single Compose file. No going through multiple tabs/windows/namespaces on the same host just to restore each one at a time

**Comment by superseb** [comment]
Closing as stale, with the new architecture you can use the CLI to create clusters and kubectl definitions to deploy the workloads.
