### ISSUE TITLE
External DB Password visible

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#10538]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:v0.13.5
network-services:
rancher/metadata:v0.9.5
rancher/network-manager:v0.7.18
scheduler:v0.8.2
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```bash
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1043-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.9MiB
Name: ip-10-0-0-58
ID: OGE4:6JUL:LEEA:QTOD:NDQC:UE2E:5OLE:I3VL:4YIK:DLHY:PNDH:NONJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ uname -r
4.4.0-1043-aws

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
For the time being, just the Rancher Server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
1. Log in to the host running the rancher/server container
2. Get the id of the rancher/server container
3. execute `docker inspect <container_id>`

**Results:**
The full string used to attach the external db **including the password** is visible in plain text

**Comment by ptrunk** [comment]
I think it'd be a nice feature to enable something like
```
--db-pass-file=
```
so we could use docker secret to store such information and the password would be no longer visible in plain text. The official mysql and postgres container work like this. So maybe rancher could offer this too.

**Comment by vincent99** [comment]
Supporting taking a secret is fine, but the use-case is something like being able to have a compose file describe the server without having the password in it.  Which doesn't come up all that often for us since you are bootstrapping an orchestration system itself.

If someone is on the host and able to talk to the docker daemon, they are root on that machine and you've already lost.. they can just run `docker exec container_id cat path_to_pass_file`  to get it.  Or launch their own container using the same secret.  Or tcpdump the MySQL connection, scan through all the memory, etc

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
