### ISSUE TITLE
Not all Security Groups listed when adding EC2 instances as Rancher hosts

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#10540]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:v0.13.5
network-services:
rancher/metadata:v0.9.5
rancher/network-manager:v0.7.18
scheduler:v0.8.2
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```bash
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1043-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.9MiB
Name: ip-10-0-0-58
ID: OGE4:6JUL:LEEA:QTOD:NDQC:UE2E:5OLE:I3VL:4YIK:DLHY:PNDH:NONJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ uname -r
4.4.0-1043-aws

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
The Rancher server is behind a classic ELB with SSL termination (on the ELB)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
For the time being, just the Rancher Server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
1. Start adding EC2 hosts to a region with pre-defined security groups
2. When reaching to the point where SGs should be added, not all of the existing ones are listed:

![screenshot from 2017-12-13 12-41-51](https://user-images.githubusercontent.com/2778429/33935042-3f7a6afa-e003-11e7-9a95-26d7ddb84a5c.png)
![screenshot from 2017-12-13 12-43-01](https://user-images.githubusercontent.com/2778429/33935043-3f9ee0ba-e003-11e7-93c0-3cc7f295c192.png)

**Results:**

**Comment by vincent99** [comment]
Only ones for the selected vpc are available (so one of the two named default), and "launch-wizard-*" are specifically excluded because they are plentiful and useless in most people's accounts.

**Comment by pkaramol** [comment]
Perhaps that's a weird design decision given that someone could have configured one of them (as happened to be my case) to be useful.
Even in that case a relevant heads-up would be user friendly given that one could lose time trying to debug this situation (why not all are selectable)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
