### ISSUE TITLE
NAT is not set up when adding windows host

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10544]
**Rancher versions:**
rancher/server: 1.6.13-rc2
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. Following the steps to add host in windows environment
2. wait and see host is added.
3. metadata service keep restarting
4. checkout for nat setting with `netsh routing ip nat show interface` and it shows error.

**Comment by kingsd041** [comment]
Tested with rancher/server:v1.6.13-rc3, metadata service started successfully.
