### ISSUE TITLE
Allow access to all certificate information via the API

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#10548]
I believe it would be nice to have an advanced option that allows admins who know what they are doing to enable the retrieval of private keys via the API for certificates stored in rancher.

Rancher provides a powerful API to store and access this sort of information and while I 100% understand the desire to make it so that private keys cannot be read out, I believe there should be an advanced option to allow this behavior.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
