### ISSUE TITLE
Forbidden error in UI while editing network policy in environment

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#10551]

**Comment by loganhz** [comment]
According to the screenshot which @leodotcloud posted in frontend slack channel, it looks like a backend issue. Server side returns `403` sometimes.

**Comment by loganhz** [comment]
Hi, @leodotcloud 
are you still suffering this issue?

**Comment by leodotcloud** [comment]
@loganhz I will debug this later. Thanks.

**Comment by jacobbdavis1991** [comment]
i am currently still having this issue. Any fix?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
