### ISSUE TITLE
[Vault]Instance tokens get revoked only when the stack to which the instance belongs gets deleted. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10554]
Rancher versions: Build from v1.6-development

Steps to reproduce the problem:
Have a setup with 2 hosts.
Deploy "vault-volume-driver" using catalog https://github.com/cloudnautique/rancher-catalog - branch add_vault_volume_driver

Create a service using volumes in vault-volume-driver with vault policies:
Once service container is running successfully , from within the containers , unwrap intermediate token to get instance token.

Scenario1:
In the following 2 cases , new instance token gets created for the user but the old instance tokens  do not get revoked:

Stop service container.
Delete service container.
Restart service container.

Scenario2:
Scale down service.
Delete service.
Even after service instances get deleted, instance tokens associated with the deleted instance are not revoked.

Instance tokens will get revoked only when the stack to which the service instances belongs to gets deleted .

**Comment by cloudnautique** [comment]
In v0.2.0 the token is revoked every time the container is started.

**Comment by cloudnautique** [comment]
This should also be addressed in latest release.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.15-rc3 and secrets-bridge-v2 version - v0.3.0

Tokens get revoked as soon as the instances get deleted in all the scenarios mentioned in this issue.
