### ISSUE TITLE
Translation not found errors for 2.0

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10552]
**Rancher versions:** 2.0 master 12/13

**Steps to Reproduce:**
1.  Go to Global

**Results:**
In Add Cluster - 
![image](https://user-images.githubusercontent.com/11514927/33965185-3974cdfc-e018-11e7-9e38-6c08a3a1b07c.png)

In Dev Tools - 
![image](https://user-images.githubusercontent.com/11514927/33965056-dcfec9c4-e017-11e7-95e9-16d533ab9f9d.png)

**Comment by vincent99** [comment]
The lower part had to be from a failure loading the translation file or something; all (or at least most of) those keys exist.

**Comment by loganhz** [comment]
add a `wontfix` label, please let me know if there is anything we can do.
