### ISSUE TITLE
Add a host

### ISSUE THREAD

**Issue by south270** [rancher/rancher#10561]
*Describe your issue here*

I could not add a host successfully.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by superseb** [comment]
We need a little more info, how are you adding a host, what logging is present in the `rancher/server` and `rancher/agent` container?

**Comment by superseb** [comment]
Please reply if you need help with the additional info.
