### ISSUE TITLE
`pm2 ls` display nothing

### ISSUE THREAD

**Issue by zyf0330** [rancher/rancher#10566]
*Describe your issue here*
`pm2 ls|l|list|status` displays nothing. `pm2 show id` and `pm2 monit` and `pm2 logs` works.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`container.volumes`|

**Comment by superseb** [comment]
Can you describe what you are trying to run and a way to reproduce so we can take a look at it?

**Comment by zyf0330** [comment]
After I upgrade centos kernel, it is ok.
