### ISSUE TITLE
Restart service, the container IP address will change

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10567]
Rancher versions:
rancher/server: 1.6.13-rc3
rancher/agent:

Docker version: (docker version,docker info preferred)
17.06.2-ee-6
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Windows Server 2016 Standard
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
VirtualBox
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
Windows

**Steps to Reproduce:**
1. Add Service 
2. Remember the container IP address
3. Restart this service
**Results:**
Container IP address has changed

**Comment by orangedeng** [comment]
Because of IPAM is handled by docker for now, it is expected and same as nat network do.
Please close this issue.
