### ISSUE TITLE
[Vault]Not able to unwarp instance token when a container is restarted after its instance token is expired. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10560]
Rancher server version - Built from v1.6 branch

Steps to reproduce the problem:
Have a setup with 2 hosts.
Deploy "vault-volume-driver" using catalog https://github.com/cloudnautique/rancher-catalog - branch add_vault_volume_driver

Create a service using volumes in vault-volume-driver with vault policies:
Once service container is running successfully , from within the containers , unwrap intermediate token to get instance token.
Wait for this instance token to expire.
stop/start or restart instance.

Once container is started , attempting to unwrap the instance token with the intermediate token fails:

```
root@c6b6544326a3:/# ./vault unwrap a4099b7c-ba57-e460-57be-fc1dfc73b762
Error making API request.

URL: PUT http://<ip>:8200/v1/sys/wrapping/unwrap
Code: 403. Errors:

* permission denied
root@c6b6544326a3:/#
```

**Comment by cloudnautique** [comment]
I believe this is caused by the CLI storing the authentication in ~/.vault-token file when validating the first token. Clear this file before trying to unwrap the second+ time and things should work.

**Comment by sangeethah** [comment]
After clearing ~/.vault-token which was already expired , able to unwrap the instance token successfully.
