### ISSUE TITLE
Vanilla Kubernetes, kube-proxy don't proxy Grafana correctly

### ISSUE THREAD

**Issue by blacksd** [rancher/rancher#10573]
**Rancher versions:**
rancher/server: v1.6.12
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.5
kubernetes (if applicable): k8s:v1.8.3-rancher3

**Docker version:** 17.09.0-ce

**Operating system and kernel:** CoreOS 1576.4.0, kernel 4.13.16-coreos-r2

**Type/provider of hosts:** vSphere self-hosted

**Setup details:** single-node Rancher + 3 hosts 

**Environment Template:** Kubernetes

**Steps to Reproduce:** 

1. Add three hosts. 
2. Deploy Kubernetes using the vanilla template. 
3. Access to the web interface and run via cli `kubectl cluster-info`. 
4. Access to the URL of "monitoring-grafana", such as `https://<rancher-server>:8080/r/projects/1a7/kubernetes:6443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy`.

**Results:**

The `kube-proxy` component fails to route the requests for some components of the page, which go 404

![image](https://user-images.githubusercontent.com/5203115/33984662-b770907e-e0b8-11e7-89b9-cbc237849239.png)

The resources are available directly (like in `http://<rancher-server>:8080/r/projects/1a7/monitoring-grafana:3000/public/css/fonts.min.css`) but Grafana can't be opened at the base address of `http://<rancher-server>:8080/r/projects/1a7/monitoring-grafana:3000` for "Invalid API Key".

**Comment by blacksd** [comment]
I believe it's somehow related to #8594, but more tied to the proxy component.

Also, I'm pretty new both to Rancher and Kubernetes.

**Comment by vlczero** [comment]
I'm having the same issue the `/r/projects/1a244/monitoring-grafana:3000` url is giving me the same `Invalid API Key` message even though `GF_AUTH_BASIC_ENABLED: false` is set

**Comment by vlczero** [comment]
More info:
I'm accessing grafana with `https://rancher.example.com/r/projects/1a244/kubernetes:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana:80`

This page loads but all the urls are not correct and are pointing to `https://rancher.example.com/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana:80/public/css/fonts.min.css`

It's missing the `/r/projects/1a244/kubernetes:6443` part.


I can get to the css and other files files with the following url `https://rancher.example.com/r/projects/1a244/kubernetes:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana:80/public/css/grafana.dark.min.af13213c.css`

**Comment by mdgs** [comment]
Hi @vlczero did you solve the issue? 

I exactly has the same issue. Somehow, when I access the grafana link generated by kubectl cluster-info, the resources will missing the r/projects/1a155/kubernetes:6443 part.

rancher: 1.6.14
rancher/agent: 1.2.9
kubernetes: 1.8.10

**Comment by vlczero** [comment]
@mdgs I "fixed" this by not using the proxy through rancher but make a service that opens a port on the instances. My AWS Application Load balancer has a target group for grafana that points to the open port. Sadly I could not get the proxy to work due to the url prefixes rancher introduces.

My service and deployment files: https://gist.github.com/vlczero/7cf850ea605cae7ae4adeff34a32fb9a

This will overwrite the default grafana deployment and ads persistency for grafana setting/users by storing it in an external mysql database . If you don't want that you can remove the GF_DATABASE_* env values.

Due note that the influxdb is not persistent and you will loose all data when it is rescheduled/crashes. I'm still looking for a way to keep the influxdb data.

**Comment by vladislavPV** [comment]
im running 
```bash
   kubectl proxy 
```
this helped in my case
```bash
- name: GF_SERVER_ROOT_URL
    value: "http://localhost:8001/api/v1/namespaces/monitoring/services/http:grafana:3000/proxy/"
```

**Comment by alexiri** [comment]
I had a similar issue, and I finally solved it by adding the following annotation to the L7 Ingress object: `nginx.ingress.kubernetes.io/rewrite-target: /`

And the following to grafana's configuration:
```
[server]
root_url = %(protocol)s://%(domain)s/grafana/
```
Source: https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/rewrite

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
