### ISSUE TITLE
Add a service using the managed network type, the container gets the wrong IP

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10570]
Rancher versions:
rancher/server: 1.6.13-rc3
rancher/agent:

Docker version: (docker version,docker info preferred)
17.06.2-ee-6
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Windows Server 2016 Standard
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
VirtualBox
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
**Windows**

**Steps to Reproduce:**
1. Add service，'Network' select managed.
2. Create service
2. Check the IP address of the container.
**Results:**
The container gets the IP address of type 'NAT'.

<img width="786" alt="2" src="https://user-images.githubusercontent.com/19684717/33983048-b7b9ed5c-e0ed-11e7-92cf-0c96a979ba2f.png">

<img width="269" alt="3" src="https://user-images.githubusercontent.com/19684717/33983096-da2a7618-e0ed-11e7-95e2-be492a4980d4.png">

**Comment by deniseschannon** [comment]
Available with v1.6.13-rc4

**Comment by kingsd041** [comment]
Tested with Rancher/server:v1.6.13-rc4.
Added service page has the disabled managed network.
