### ISSUE TITLE
Create a Stack+Service using the 'Transparent' or 'NAT' network. When clone or upgrade Service, Missing 'managed' option

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10576]
Rancher versions:
rancher/server: 1.6.13-rc3
rancher/agent:

Docker version: (docker version,docker info preferred)
17.06.2-ee-6
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Windows Server 2016 Standard
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
VirtualBox
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
**Windows**

**Steps to Reproduce:**
1. Create Stack + Service, 'Network' using 'Transparent' or 'NAT'
2. Clone or upgrade this Service
3. Check the contents of 'Network'
**Results:**
'Network' can only choose 'Transparent' or 'NAT'，Missing 'managed' option

<img width="1039" alt="4" src="https://user-images.githubusercontent.com/19684717/33988219-ba43f1f6-e0fe-11e7-9ebe-80be399f2e9b.png">

**Comment by orangedeng** [comment]
That is expected. The managed network should not be seen in add service page. When creating a service with managed network, UI will automatically set it to `transparent` instead of `nat`.

**Comment by deniseschannon** [comment]
Available with v1.6.13-rc4

**Comment by kingsd041** [comment]
Tested with Rancher/server:v1.6.13-rc4.
Added service page has the disabled managed network.
