### ISSUE TITLE
关于如何将容器添加进自定义应用中

### ISSUE THREAD

**Issue by Hello-Linux** [rancher/rancher#10572]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`containers.index`|
你好,最近我在本地主机上跑了一个rancher之后我在物理主机上的docker上运行了一个tomcat容器,我现在想把这个容器划分到这个Default 应用当中该怎么放进去呢,我打开这个Default服务后里面让我基于镜像去创建一个容器而没有怎么把我刚才在系统上跑的容器添加进去,请问我改怎么做呢
![1](https://user-images.githubusercontent.com/17851645/33984898-025fe176-e0f4-11e7-9979-71360ba1427f.png)
![2](https://user-images.githubusercontent.com/17851645/33984900-02983fc6-e0f4-11e7-9804-2b90ab51e0ed.png)
![3](https://user-images.githubusercontent.com/17851645/33984903-02cc686e-e0f4-11e7-8433-1203d7659a26.png)

**Comment by loganhz** [comment]
目前不支持这个功能，在Rancher中创建的服务才能被添加到某个应用栈里。
