### ISSUE TITLE
Create a Stack+Service using the 'managed' network. Clone or upgrade Service, 'Network' defaults to 'Transparent'

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10571]
Rancher versions:
rancher/server: 1.6.13-rc3
rancher/agent:

Docker version: (docker version,docker info preferred)
17.06.2-ee-6
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Windows Server 2016 Standard
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
VirtualBox
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
**Windows**

**Steps to Reproduce:**
1. Create a Stack+Service, 'Network' select 'managed'
2. Clone or upgrade this service
**Results:**
'Network' defaults to 'Transparent' network

<img width="1022" alt="3" src="https://user-images.githubusercontent.com/19684717/33983788-63e77868-e0f0-11e7-89cd-caf0c6e026f5.png">

**Comment by orangedeng** [comment]
please refer to https://github.com/rancher/rancher/issues/10576

**Comment by deniseschannon** [comment]
Available with v1.6.13-rc4

**Comment by kingsd041** [comment]
Tested with Rancher/server:v1.6.13-rc4.
Added service page has the disabled managed network.
