### ISSUE TITLE
v2.0 - Denial of Service

### ISSUE THREAD

**Issue by naisanza** [rancher/rancher#10586]
**Rancher versions:**
rancher/server: 
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 90
 Running: 69
 Paused: 0
 Stopped: 21
Images: 22
Server Version: 17.09.1-ce
Storage Driver: zfs
 Zpool: turtle
 Zpool Health: ONLINE
 Parent Dataset: turtle/_ubuntu/rancher/docker
 Space Used By Parent: 27648
 Space Available: 11709249370624
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 17.64GiB
Name: bigma
ID: UWKU:2Q36:44LW:HH6M:5DI3:YERH:WHCZ:YT5X:LDP2:QP4F:7Y4W:BHS2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.4.0-98-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
Bare-metal
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
```
Ubuntu 16.04 server
Docker-CE (latest)
docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview
```

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
```
Rancher 2.0 default
```

**Steps to Reproduce:**
I some how Denial of Serviced Rancher when I used a 70 character alpha-numeric + special characters string for an environment variable for the docker image https://hub.docker.com/r/jdeathe/centos-ssh/. Example string below.

`SSH_USER_PASSWORD`:
```
5CDv:Tym2nYEbaZoXhN`U7%Qq*3=K\4zR/cMHi+6!frp;GAL'J^.@VP,8d$j9&WxSut"es
```

Some of the containers were stuck in Delete/Initialize. Restarting the server, all of the containers wouldn't start. I checked Disk I/O, [ulimits, inotify limits](https://github.com/lxc/lxd/blob/master/doc/production-setup.md), memory, cpu load. Nothing looked out of the ordinary 

I deleted everything, the zfs datasets, the docker service; and just restored everything using the compose yaml files.

**Results:**

**Comment by naisanza** [comment]
It happened again with only a long alphanumeric string

**Comment by naisanza** [comment]
When this happens, you must restart for Rancher to add a Host, otherwise, it never shows

**Comment by naisanza** [comment]
I am purging the following directories `/var/lib/rancher`, `/var/lib/docker`, and reinstalling `docker-ce:latest`

After purging and re-installing, Rancher v2.0 is very unstable. and becomes unresponsive, the container logs report it is no longer able to authenticate, other logs state processes are missing, and "unable to save state"

Below is the simple script used to purge and rebuild Rancher v2.0.

rancher-reset.sh:
```
#!/bin/bash

# Reset Rancher and reinstall


echo "[*] Running..."

service docker stop && echo "[*] docker stopped" || echo "[!] unable to stop docker"
umount -frl /var/lib/rancher/* && echo "[*] Umounted all /var/lib/rancher/" || echo "[!] Failed to umount all of /var/lib/rancher/"
umount -frl /var/lib/docker/* && echo "[*] Unmounted all /var/lib/docker/" || echo "[!] Failed to umount all of /var/lib/docker"
rm -rf /var/lib/rancher/* && echo "[*] Deleted all of /var/lib/rancher/*" || echo "[!] Failed to clean /var/lib/rancher/"
rm -rf /var/lib/docker/* && echo "[*] Deleted all of /var/lib/docker/*" || echo "[!] Failed to clean /var/lib/docker/"
zfs destroy -r turtle/_ubuntu/rancher/docker && echo "[*] Destroyed ZFS dataset" || echo "[!] Failed to destroy turtle/_ubuntu/rancher/docker"
zfs create -o mountpoint=/var/lib/docker/ turtle/_ubuntu/rancher/docker && echo "[*] Created ZFS dataset" || echo "[!] Failed to create turtle/_ubuntu/rancher/docker"

read -p "Continue? [yn] " yn
if [ "$yn" == "y" ]; then
  apt install --reinstall docker-ce && echo "[*] Reinstalled docker-ce" || echo "[!] Failed to reinstall docker-ce"
  #docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview
  docker run -d --restart=unless-stopped -p 8080:8080 rancher/server
fi
```

**Comment by deniseschannon** [comment]
As of the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!
