### ISSUE TITLE
Improve error logs in health check containers when health check is paused when ipsec is not in "active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10580]
Rancher server - Build from v1.6-development

Steps to reproduce the problem:
Upgrade ipsec service.

When ipsec service is getting upgraded ,  health check  is paused resulting in following error message:

```
12/14/2017 10:01:28 AMtime="2017-12-14T18:01:28Z" level=error msg="Failed to report status 25e575c6-3bd8-480a-aa17-c3dc6ff7cf04_e79ef58d-370e-4f1e-9b51-7538c96a391d_1=DOWN 1/2: Bad response from [http://104.198.156.63:8080/v2-beta/serviceevents], statusCode [409]. Status [409 Conflict]. Body: [{\"id\":\"320fc91a-0152-4592-abe8-2c5be68c8220\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}]"
12/14/2017 10:01:28 AMtime="2017-12-14T18:01:28Z" level=error msg="Failed to report status 25e575c6-3bd8-480a-aa17-c3dc6ff7cf04_98dac6e4-12c6-4c41-bbe5-a51f346e7910_1=DOWN: Bad response from [http://104.198.156.63:8080/v2-beta/serviceevents], statusCode [409]. Status [409 Conflict]. Body: [{\"id\":\"d0a91a13-3648-4a53-a622-1b432cd4dcfc\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}]"
12/14/2017 10:01:28 AMtime="2017-12-14T18:01:28Z" level=info msg="25e575c6-3bd8-480a-aa17-c3dc6ff7cf04_5441afe7-4bb8-4820-9814-cda2667cbc15_1=INIT"
12/14/2017 10:01:28 AMtime="2017-12-14T18:01:28Z" level=info msg="25e575c6-3bd8-480a-aa17-c3dc6ff7cf04_0dc1f85a-4fda-4080-b851-6dfc259602ec_1=INIT"
12/14/2017 10:01:30 AMtime="2017-12-14T18:01:30Z" level=error msg="Failed to report status 25e575c6-3bd8-480a-aa17-c3dc6ff7cf04_98dac6e4-12c6-4c41-bbe5-a51f346e7910_1=DOWN 1/2: Bad response from [http://104.198.156.63:8080/v2-beta/serviceevents], statusCode [409]. Status [409 Conflict]. Body: [{\"id\":\"c26d3887-ea3f-408b-8254-68033004cfa0\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}]"
```

These error messages can be improved to be reflect the state rather than a 409 conflict error

**Comment by KOBA789** [comment]
I have the same issue (and LB can't continue to run so repeats restarting)

**Comment by KOBA789** [comment]
It appeared after upgrading k8s but just clicking "Finish Upgrading" solved this problem in my situation.

**Comment by ankurgadgilwar** [comment]
I am facing similar issues. My health status and ipsec are not coming up, they just seem to be hung. I tried installing the haproxy package and enabling it on all the hosts, still no good. 
I tried restarting docker and nothing good came out of it. Please help!

**Comment by thatbudakguy** [comment]
Same problem as @ankurgadgilwar. I can only have one host running; all others can't bring up healthcheck/ipsec because of the 409. This happens as soon as the host is initially added.

**Comment by ankurgadgilwar** [comment]
I had that persistent issue for a long time, HTTP 409 keeps on occurring, Try updating yum and restarting the node, that actually worked for me. I don't have anything running on my cluster yet, so I can afford to reboot the machine and restart docker. Give it a try. 
Also, I would recommend you to have atleast 4 nodes in your cluster.

**Comment by thatbudakguy** [comment]
Updated system packages (`apt`, since I'm on Ubuntu) and updated to latest stable docker, rancher-server, and rancher-agent on all nodes. Still running into the problem.

I can afford to reboot the machine and restart docker, but I certainly can't afford more than 3 nodes. ;)

**Comment by frekele** [comment]
Same error with Rancher v1.6.14 + docker 17.12.1-ce in Host debia. 9(jessie) 64x, when run cluster in mode host.

**Comment by andredasilvapinto** [comment]
Same here

**Comment by deas** [comment]
Not quite sure if another repro matters, but I can easily reproduce the issue using one physical (ubuntu 17.10) machine running v1.6.15 on the host and two docker-machine vm nodes. The following code creates kvm vms, but virtualbox works equally.

```
docker-machine create \
    --driver kvm \
    --kvm-cpu-count 2 \
    --kvm-memory 1092 \
    --kvm-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v17.12.1-ce/boot2docker.iso \
    kvm-1712-1
    
docker-machine create \
    --driver kvm \
    --kvm-cpu-count 2 \
    --kvm-memory 1092 \
    --kvm-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v17.12.1-ce/boot2docker.iso \
    kvm-1712-2    
```
Start from an empty environment and create the first custom host, "docker-machine ssh kvm-1712-1" and paste the command line from rancher.

The services go up and everything is green.

Now add the second node. 

ipsec/healthcheck go Up/Down/Initializing/Unhealthy

ipsec-router logs show entries such as:

```
3/22/2018 3:49:51 PMtime="2018-03-22T14:49:51Z" level=info msg="samonitor: expected SA for host: 172.17.42.1, but not found."
3/22/2018 3:49:51 PMtime="2018-03-22T14:49:51Z" level=error msg="samonitor: error initiating missing SA child-172.17.42.1: unsuccessful Initiate: CHILD_SA config 'child-172.17.42.1' not found"
```

healthcheck logs go:
```
3/22/2018 3:55:35 PMtime="2018-03-22T14:55:35Z" level=error msg="Failed to report status 8734367f-1c29-4d3b-8214-e939fc06f058_5a30ec2b-3a98-481b-be9e-11138b7fbff0_1=DOWN: Bad response from [http://.../v1/serviceevents], statusCode [409]. Status [409 Conflict]. Body: [{\"id\":\"16d637fd-f0eb-487d-b94a-2c6511597b4b\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}]"

```

**Comment by Stark-X** [comment]
I've faced similar issues. 

### Solution:
- Review the address on Rancher UI -> Hosts, check if the ip of the hosts correct or not.
- `Add Host`, filling Step 4 with the docker server's IP
- run the docker agent with Step 5 command.

In my case, our environment had been destroied in some reason, then we are going to recreate all the compoent. 
I've tried to start the agent without specified agent located server's IP, when the second hosts set up, the issue  comes up. Then I check the logs of the agent, found that `DETECTED_CATTLE_AGENT_IP` is wrong, and the IP of the host on the Rancher UI shows the same one for each hosts, and it might lead to the rancher trying to edit the same record in the DB, that'll caused the dead lock.

P.S. If you're facing the same issue, you could specified the IP for fixing in time, then contact to your network administrator to troubleshoot the network settings.

**Comment by mjaverto** [comment]
I have the same issue here. 1.6.15 using RancherOS 1.3.0 with agents at 1.2.10

@Stark-X I tried your solution to no avail. I'm running all the agents as private IPs and the DETECTED_CATTLE_AGENT_IP is correct on resolution so it sounds like a different cause for me.

- My rancher server IP is a DNS entry that resolves to a private IP address.
- My agents are all private IP addresses and I can confirm DETECTED_CATTLE_AGENT_IP is getting the correct private IP address for each service.

I can verify the issue is only with services that have healthchecks enabled and when deleting the service and recreating withOUT healthchecks, everything is fine.

I deactivated the machine and activated the rancher Host a few times and somehow the healthcheck service became healthy and now it is running as expected with no more 409s.

This is a big problem for us and seems to have only surfaced around 1.16.4 / 5 that we've noticed.

**Comment by thatbudakguy** [comment]
fwiw I had the same setup as @mjaverto : server is a DNS entry that resolves to private IP; hosts are all private IPs in same subnet. have rebuilt hosts from bare VM several times and re-registered to no avail; server also. >1 host will reproduce the issue, but exactly one host will run fine (doesn't matter which).

**Comment by deas** [comment]
FWIW: Got some more clues with regards to my KVM/Virtualbox multi hosts issue.

The virtual hosts somehow pick up the IP of the Docker bridge interface of the **rancher-server** (which happens to be running on the same physical machine). In the console, I see:

```
INFO: ENV: DETECTED_CATTLE_AGENT_IP=172.17.42.1
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.10
```
And that IP also displays in the Rancher-UI for **each** host.

**Comment by mjaverto** [comment]
@deas it sounds like @Stark-X 's solution may work for you.

**Comment by paulobezerr** [comment]
If you put you host in a DHCP and this IP changes, you will have two problems:

- Health check will crash
- IPSec will crash too

You need to set fixed IP's for your hosts. Then this problem will never occour.
After reset the IPs, you can restart the services and all will gonna work fine.

**Comment by ssmithTaylor** [comment]
I'm using DHCP and ran into this issue as well. (Though my DHCP address has not changed)

Restarting the network stack in ROS resolved the issue I was having with the health check service.

**Comment by pkaramol** [comment]
https://github.com/rancher/rancher/issues/12981

**Comment by surendrababukandhikattu** [comment]
> Same problem as @ankurgadgilwar. I can only have one host running; all others can't bring up healthcheck/ipsec because of the 409. This happens as soon as the host is initially added.
> 
> additionally, the ipsec service for the "first" host changes to "unhealthy" and its router sidekick shows:
> 
> ```
> 2/27/2018 4:04:06 PM00/34.210.145.90 not found for delete
> 2/27/2018 4:04:06 PM05[KNL] creating acquire job for policy 10.42.220.193/32[6/38324] === 10.42.49.143/32[6/42] with reqid {1234}
> 2/27/2018 4:04:06 PM15[CFG] trap not found, unable to acquire reqid 1234
> 2/27/2018 4:04:06 PM07[IKE] retransmit 5 of request with message ID 0
> 2/27/2018 4:04:06 PM07[NET] sending packet: from 10.42.71.31[500] to 34.210.145.90[500] (500 bytes)
> 2/27/2018 4:04:06 PM09[KNL] creating delete job for CHILD_SA ESP/0x00000000/34.210.145.90
> 2/27/2018 4:04:06 PM16[JOB] CHILD_SA ESP/0x00000000/34.210.145.90 not found for delete
> 2/27/2018 4:04:06 PM07[KNL] creating acquire job for policy 10.42.71.31/32[6/47022] === 10.42.90.215/32[6/80] with reqid {1234}
> 2/27/2018 4:04:06 PM11[CFG] trap not found, unable to acquire reqid 1234
> 2/27/2018 4:04:06 PM08[KNL] creating delete job for CHILD_SA ESP/0x00000000/34.210.145.90
> 2/27/2018 4:04:06 PM05[JOB] CHILD_SA ESP/0x00000000/34.210.145.90 not found for delete
> 2/27/2018 4:04:06 PM13[KNL] creating acquire job for policy 10.42.220.193/32[6/40772] === 10.42.90.215/32[6/80] with reqid {1234}
> 2/27/2018 4:04:06 PM12[CFG] trap not found, unable to acquire reqid 1234
> 2/27/2018 4:04:06 PM11[IKE] giving up after 5 retransmits
> ```
