### ISSUE TITLE
[Windows] UI Updates for Add Host

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10587]
**Rancher versions:**
rancher/server: v1.6.13-rc3

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows

UI Updates

[ ] Remove the `Windows Host` text. 

<img width="191" alt="screen shot 2017-12-15 at 12 06 56 am" src="https://user-images.githubusercontent.com/11410997/34032629-ebb1562a-e12b-11e7-952e-c16ebd768fcf.png">

[ ] Step 1: Similar to the Linux Add Host page, we should refer to the latest supported versions of Docker. We should update the Docs to include what is supported for Windows. 
http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions

<img width="294" alt="screen shot 2017-12-15 at 12 07 33 am" src="https://user-images.githubusercontent.com/11410997/34032698-308d3c6e-e12c-11e7-9939-053eb092c675.png">

[ ] Step 2: Make a note that the Windows machine will need to be rebooted if the applications were installed. 

[ ] Step 3: Change the text to `Specify a unique subnet for the Windows host. In order to support an overlay network in Windows, each host in the environment must have a unique subnet.`

[ ] Step 4: Change the text to `Specify the router IP for the host's subnet. This IP is used to forward network traffic between the different hosts.`

**Comment by deniseschannon** [comment]
Available with v1.6.13-rc4

**Comment by sabiodelhielo** [comment]
Text is updated in v1.6.13-rc4
