### ISSUE TITLE
Add Rancher Pipeline Into Community Catalog

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#10591]
We need to integrate Rancher Pipeline into [Community Catalog](https://github.com/rancher/community-catalog) so that user can easily deploy Rancher Pipeline.

**Comment by orangedeng** [comment]
@deniseschannon Please help to review this community-catalog pr if available.

**Comment by deniseschannon** [comment]
As this is reviewed and merged, I'm going to close this issue.
