### ISSUE TITLE
Wrong config in loadbalancer when target is a selector pointing o other lb

### ISSUE THREAD

**Issue by micw** [rancher/rancher#10592]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: 1.2.7

**Docker version: (`docker version`,`docker info` preferred)**
17.09.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
debian stretch with backport kernel 4.13

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
create a service listening on port 3000 (something other than 80)
create a private loadbalancer on http/80 sending all traffic to service:80
label the private lb as foo=bar
create a public loadbalancer on http/80 sending all traffic to selector foo=bar port 80

**Results:**
the public loadbalancer gets a configuration sending all traffic on the private load balancer, port 3000. If the private load balancer has more than one service, the public load balancer gets several service config entries pointing to the private lb but to the ports of the services.

Somehow, the public lb mixes the configuration from the private lb with it's own.

**Comment by micw** [comment]
That's the config of my public lb:

backend 80_
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
   http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
   http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_proto
mode http
server 788979c9fda15c2856e6486288c62684731abe07 10.42.15.79:3000

10.42.15.79 is the ip of the private lb which is listening on :80

**Comment by micw** [comment]
The same configuration works if I use service rules instead of selector rules

**Comment by johnhidey** [comment]
Have the same issue and would like to see this get fixed.  I know everyone is working hard on getting 2.0 out the door but I just hope the team doesn't forget about 1.6.x.

**Comment by dimitribellini** [comment]
We have notice the same problem and it was a very frustrating. I think is very easy to fix but i did not know how is create the rule inside the "Public LB". 
Please fix it because we are in a evaluate phase on Rancher with our best customer :-)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by dimitribellini** [comment]
Please close the bug.
Thanks very much
