### ISSUE TITLE
Haproxy: DrainTimout breaks service-restart

### ISSUE THREAD

**Issue by 0ff** [rancher/rancher#10593]
Since upgrading to 1.6.12 we've noticed that setting a `drain_timeout_ms` (as per #2777) breaks restarting services.

You can reproduce this very easily: Create a stack with a single HAProxy and a single service with one container.
Then, restart the single container and observe the proxy setting the backend-weight to `0` (to drain the connection).
NOTE: You don't even need an active connection for this to break!

As the service is not upgraded but restarted, the lb-controller will pick up the change in rancher but generate the very same config file, thus not re-evaluating it.
In the end, this leads to the backend being stuck at `weight 0` and the service not receiving any new connections, even though it was restarted successfully - returning 503 to every request.

In the HAProxy stats you can actually see the service being stuck with weight 0:
<img width="1333" alt="screen shot 2017-12-15 at 17 29 15" src="https://user-images.githubusercontent.com/1755213/34051076-8227510e-e1bd-11e7-88ce-ffd09a8da2c9.png">

I guess a good approach would be to reset the `weight` to 1 once the service is `running` again (in rancher); this way there would be really no downtime (as long as there's at least a second container).

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Orchestration|`Cattle`|

**Comment by loganhz** [comment]
Can you try v1.6.22, please? It should be fixed.

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
