### ISSUE TITLE
OpenNebula host type unusable. 

### ISSUE THREAD

**Issue by Darkknight33** [rancher/rancher#10594]
**Rancher versions:**
rancher/server: v2.0.0-alpha10
rancher/agent:n/a

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.66-1.ph2-esx
Operating System: VMware Photon OS/Linux
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.957GiB
Name: photon-machine
ID: XXXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Vmware Photon 2.0, 4.9.66-1.ph2-esx

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Vsphere/Opennebula

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single rancher server preview node for testing

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Default

**Steps to Reproduce:**
Goto Machine Drivers, enable OpenNebula. Goto Add hosts and select OpenNebula.

**Results:**
Nothing happens. Info boxes below do not change from previous host type selected. Unable to use OpenNebula at all.

**Comment by superseb** [comment]
This was just recently improved. Can you try with `v2.0.0-alpha23`? We can reopen if you still experience issues.
