### ISSUE TITLE
Is there a container draining state? And is it available through metadata?

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#10597]
Hi,

We want to implement connection drain with our own load balancer.
How does connection drain work with the rancher built-in haproxy?
And how the haproxy knows that a container is in "draining" state?
Is there any way to know if a container is in draining state via metadata?

Thanks,

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
