### ISSUE TITLE
v2.0 cannot set log for container/service

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#10605]
**Rancher versions:**
rancher/server: v2.0.0-alpha10
rancher/agent: v2.0-alpha4

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher + external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
create a service and set the log driver or log options.

**Results:**
the log driver and log options settings didn't take effect. when i `docker inspect $container`, I see it continue to use the default logging settings from `/etc/docker/daemon.json`.

**Comment by vincent99** [comment]
Kubernetes does not support Docker log drivers and has its own mechanisms which we will be integrating with.  The options in the UI are just leftover from Cattle.
