### ISSUE TITLE
Kubernetes addons are not verified after trying to launch them using kubectl

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10618]
**Rancher versions:**
rancher/server: v1.6.13-rc4

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.8.5-rancher3

**Steps to Reproduce:**
Have a not yet healthy k8s cluster, addons-starter is being run and the `kubectl` commands to launch addons are executed.

**Results:**
Cluster is not yet healthy and is responding (in this case) with unavailable etcd. This is not being handled (i.e. check exit code and loop till it succeeds or verify deployments)

```
++ grep -r kubernetes-dashboard-amd64:v1.8.0 /etc/kubernetes/addons
+ desired_version=v1.8.0
+ '[' -z '' ']'
++ echo k8s-app=kubernetes-dashboard,kubernetes-dashboard-amd64:v1.8.0,/etc/kubernetes/addons/dashboard
++ cut -d, -f3
+ kubectl --namespace=kube-system replace --force -f /etc/kubernetes/addons/dashboard
Error from server: error when deleting "/etc/kubernetes/addons/dashboard/dashboard-controller.yaml": client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.42.220.216:2379: getsockopt: connection refused
```

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
