### ISSUE TITLE
proxy requests in host OS

### ISSUE THREAD

**Issue by wormen** [rancher/rancher#10610]
tell me
how can I configure proxy requests on an application that runs without a container?

example
```
rancher-server > localhost:port
rancher-server > 10.*.*.*:port
```

**Comment by superseb** [comment]
Not completely sure what you are trying to achieve here, maybe External Services could help you? http://rancher.com/docs/rancher/v1.6/en/cattle/adding-external-services/

Otherwise I would need a bit more information on what you are trying to do.

**Comment by wormen** [comment]
unfortunately, this is not what I need
in the load balancer UI need a functional, with the help of which it will be possible to indicate which IP:PORT proxy the request (for an application that runs without a container)

**Comment by superseb** [comment]
If you create an external service (a reference to an application running outside of Rancher), you can use this in a loadbalancer to target.

Please describe your scenario in more detail so I can help answer your question.
