### ISSUE TITLE
Kubernetes setup stuck at "Creating Kubernetes system stack"

### ISSUE THREAD

**Issue by ashokm** [rancher/rancher#10613]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
network-services: network-manager: 0.7.18, metadata:v0.9.5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-693.11.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
RHEL 7.4 VMs

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
The Kubernetes Cloud Provider (http://rancher.com/docs/rancher/v1.6/en/kubernetes/providers/) within the Rancher Environment Template is set to:

```
    CLOUD_PROVIDER": "rancher"
```

When adding RHEL 7.4 hosts to a Rancher Kubernetes template environment, the hosts are added to Rancher, however, the 'rancher-agent' container logs indicate that there is attempts to connect to the AWS provider:

**Results:**

rancher-agent container logs indicate there is attempts to connect to EC2 resources:

```
12/18/2017 1:41:14 PMtime="2017-12-18T13:41:14Z" level=warning msg="stat /var/lib/rancher/state/info.json: no such file or directory"
12/18/2017 1:41:26 PMtime="2017-12-18T13:41:26Z" level=error msg="checking aws cloud provider error after 6 attempts, last error: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get http://169.254.169.254/latest/dynamic/instance-identity/document: dial tcp 169.254.169.254:80: getsockopt: no route to host"
12/18/2017 1:43:14 PMtime="2017-12-18T13:43:14Z" level=error msg="checking aliyun cloud provider error after 2 attempts, last error: Get http://100.100.100.200/latest/meta-data/zone-id: dial tcp 100.100.100.200:80: i/o timeout"
12/18/2017 1:44:37 PMtime="2017-12-18T13:44:37Z" level=error msg="Error with the container log scanner." error="context canceled"
```

**Comment by superseb** [comment]
We got a PR in review for logging it as info here: https://github.com/rancher/agent/pull/257

Is there any functional problem in your setup?

**Comment by ashokm** [comment]
The 'Setting up Kubernetes... process is stuck at "Creating Kubernetes system stack"

**Comment by superseb** [comment]
Ok, can you check the status of Kubernetes -> Infrastructure stacks? All Rancher components (healthcheck/ipsec/network-services) should be green. You can check logging of the `kubernetes/kubernetes` service and the `kubernetes/kubelet` service.

Also, check if all the hosts are registered with the correct IP in Infrastructure -> Hosts.

**Comment by ashokm** [comment]
There is only one 'network-services' stack which is all green.
The hosts are also successfully added and green.
Still stuck "Creating Kubernetes system stack" though :/

**Comment by superseb** [comment]
Can you check for this log message in `rancher/server` container? http://rancher.com/docs/rancher/v1.6/en/faqs/server/#why-is-rancher-server-logging-javasqlsqldataexception-incorrect-string-value-

**Comment by ashokm** [comment]
I don't have access to the rancher/server container logs at this time.
Will report back once/if I get these.

**Comment by superseb** [comment]
We have https://github.com/rancher/rancher/issues/10342 open for handling this situation, for now you can convert the database as described in the FAQ or get a new database with the right character set/collation as show in the docs (http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#single-container-external-database)

**Comment by ashokm** [comment]
Converting the DB as described in the FAQ resolved this for us. Thanks!
