### ISSUE TITLE
Checking DISABLE_ADDONS in addons-starter.sh is unneeded

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10615]
**Rancher versions:**
rancher/server: v1.6.13-rc4

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.8.5-rancher3

**Steps to Reproduce:**
Try to disable Kubernetes addons using `Enable Kubernetes Add-ons` = `false` in catalog item. (which translates to `$ENABLE_ADDONS ` = `true`)

**Results:**
The script that runs to execute addons checks:

```
if [ ${DISABLE_ADDONS} == "true" ]; then
    echo "addons have been disabled"
    sleep infinity
fi
```

https://github.com/rancher/kubernetes-package/blob/v1.8.5-rancher3/package/addons-update.sh#L6

**Comment by superseb** [comment]
Seems to have moved to a conditional in the catalog item on the whole service `addons-starter`: https://github.com/rancher/rancher-catalog/blob/v1.6-release/infra-templates/k8s/38/docker-compose.yml.tpl#L406

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
