### ISSUE TITLE
v1.6.12 - Load Balancer does not retain Host IP Address

### ISSUE THREAD

**Issue by naisanza** [rancher/rancher#10628]
**Rancher versions:**

Rancher | v1.6.12
-- | --
Cattle | v0.183.30
User Interface | v1.6.30
Rancher CLI | v0.6.5
Rancher Compose | v0.12.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 90
 Running: 69
 Paused: 0
 Stopped: 21
Images: 22
Server Version: 17.09.1-ce
Storage Driver: zfs
 Zpool: turtle
 Zpool Health: ONLINE
 Parent Dataset: turtle/_ubuntu/rancher/docker
 Space Used By Parent: 27648
 Space Available: 11709249370624
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 17.64GiB
Name: bigma
ID: UWKU:2Q36:44LW:HH6M:5DI3:YERH:WHCZ:YT5X:LDP2:QP4F:7Y4W:BHS2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.4.0-98-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
Bare-metal
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
```
Ubuntu 16.04 server
Docker-CE (latest)
docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview
```

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
```
Rancher 2.0 default
```

**Steps to Reproduce:**
After setting the host IP address to use, editing the Load Balancer loses the IP address configuration. And saving it will revert it back to having no host IP address.

![screenshot from 2017-12-19 14-47-30](https://user-images.githubusercontent.com/1614425/34175775-95c43f72-e4cb-11e7-9fd7-bfceebc2f358.png)

**Results:**

**Comment by michael-x** [comment]
I'm observing the same issue as well: When editing a HAProxy configuration that uses the Host IP the Host IP column is not shown automatically. When clicking on "Show host IP address options.", the column remains empty. When clicking on "Edit" (with or without showing the host IP address options), the Host IP binding is removed.
Shouldn't this be categorized as a bug, rather than an enhancement? After all clicking on "Edit" without making any changes, removes the binding.

**Comment by naisanza** [comment]
@michael-x it should be a bug

But I'm guessing with the release of 2.x this won't be a problem anymore, since it doesn't happen in their, IIRC

**Comment by loganhz** [comment]
duplicated with https://github.com/rancher/rancher/issues/10414
