### ISSUE TITLE
[Windows Eevironment] Can not resolve service.stack in the container

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10626]
Rancher versions:
rancher/server: 1.6.13-rc4
rancher/agent:

Docker version: (docker version,docker info preferred)
17.06.2-ee-6
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Windows Server 2016 Standard
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
VirtualBox
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
**Windows**

**Results:**

1. Can not resolve service.stack inside the container
```
PS C:\> Resolve-DnsName service1.stack1
Resolve-DnsName : service1.stack1 : DNS name does not exist
At line:1 char:1
+ Resolve-DnsName service1.stack1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (service1.stack1:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName
```
2. If you modify the DNS server, let 169.254.169.251 ranked first, service1.stack1 can be resolved.

<img width="837" alt="44" src="https://user-images.githubusercontent.com/19684717/34150274-de5cb702-e4e2-11e7-9217-03a7e21b0d50.png">

**Comment by kingsd041** [comment]
@deniseschannon @orangedeng 
In v1.6.13-rc5 version, it's not solved yet.

**Comment by deniseschannon** [comment]
@kingsd041 can you please re-test with v1.6.13-rc6

**Comment by kingsd041** [comment]
Tested with v1.6.13-rc6.
Test passed.
