### ISSUE TITLE
Cluster - make fields required

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10623]
**Rancher versions:** 2.0 master 12/18

**Steps to Reproduce:**
1.  Go to Create Cluster and Select "Create a Cloud Cluster"
2.  Click on Create without inputting anything in any of the fields

**Results:**  A Cluster is created with random name and is stuck in "Provisioning".  Make Name, Service Account, Quantity & Machine Type, Kubernetes Version required or go to a default if you change it to null.

**Comment by deniseschannon** [comment]
Backend now has requirements. Can UI make it more user friendly? 

```
"Credential" is required

"Project" is required
```

**Comment by deniseschannon** [comment]
Another note: Error message when required fields does not disappear when switching between cloud providers on the add cluster page.

**Comment by vincent99** [comment]
Project is read from the credential.

It all needs to be interactive to get the current k8s version for the selected zone anyway, so once there's an API for that you won't be creating a cluster until both of these are already known and validated.

**Comment by deniseschannon** [comment]
Change in workflow for adding GKE makes more sense. 

1/22 build
