### ISSUE TITLE
[Region] Region match in LB port rules is case sensitive. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10624]
Rancher versions: v1.6.13-rc3
catalog - https://github.com/leodotcloud/rancher-catalog.git branch- regions

Steps to reproduce the problem:
Create 1 rancher-server instance   as "sjc" with environment - test1 which has service with label "test1=vaule1"
Create another  rancher-server instance  as "rtp" with environment - test2.
Create Load balancer in "test2" environment , with port rules having region set to "SJC" for  environment - test1 with target = "test1=vaule1"
Once LB is created ,  "rtp/test2" gets linked " to "sjc/test1". But Lb does not have any targets that match the lables "test1=vaule1" from "sjc/test1".

Once Lb is edited and region is set to "sjc" from "SJC" , targets get programmed as expected.

**Comment by alena1108** [comment]
@kinarashah can you check if LB service gets region comparison in case sensitive manner, and change it to be done in case insensitive way?

**Comment by sangeethah** [comment]
Tested with rancher-server built from 1.6 branch with rancher/lb-service-haproxy:v0.7.20.
Region and environment name in port rules are case insensitive now.
