### ISSUE TITLE
Should be allowed to add port rules with no region by providing only environment field.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10625]
Rancher versions: v1.6.13-rc3
catalog - https://github.com/leodotcloud/rancher-catalog.git branch- regions

Steps to reproduce the problem:
Create LB rule with port rules having no region but only environment field.
User is presented with  error message - "Region is required if environment field is not empty".
This should be allowed from UI.
API would default region to local region in this case.

**Comment by sangeethah** [comment]
When trying to open LB service (for editing) that is created with port rules having  no region set but environment only using compose yml files , porRules are presented without "Show Regions" option enabled so environment that was set is not visible until user enables "Show Regions" option .

**Comment by deniseschannon** [comment]
Available in v1.6.15-rc2

**Comment by sangeethah** [comment]
Tested with rancher server build from 1.6 branch.
UI allows for creating port rules with no region by providing only environment field.
But when you open this LB service (for editing) ,portRules are presented without "Show Regions" option enabled so environment that was set is not visible until user enables "Show Regions" option .

Reopening this issue to get this addressed.

**Comment by sangeethah** [comment]
Tested with v1.6.15-rc3.

This issue is not seen anymore.
