### ISSUE TITLE
Support webhook payload format for Azure Container register

### ISSUE THREAD

**Issue by mnasyrov** [rancher/rancher#10639]
**Rancher versions:**
rancher/server: 1.6.12

This is a feature request.
Currently "Upgrade a Service" webhook supports payload formats only for "Docker Hub" and "Alibaba Cloud Docker Hub". Please support payloads from [Azure Container register](https://docs.microsoft.com/en-in/azure/container-registry/container-registry-webhook-reference).

**Comment by deniseschannon** [comment]
@kingsd041 this is available in the current master of v1.6-development. you can use `rancher/server:v1.6-development` or wait for the next RC

**Comment by kingsd041** [comment]
@mnasyrov  We have made a change to support Azure Container Registry in v1.6.15-rc1. Can you have a try, please?

**Comment by mnasyrov** [comment]
@kingsd041 Tested "Upgrade a Service" webhook using Rancher Server v1.6.15-rc1 and Azure Container registry: was able to make a push to the webhook and upgrade a service.
Great work, thank you!

**Comment by deniseschannon** [comment]
Thank you @mnasyrov!
