### ISSUE TITLE
wrong behaviour when auto-discovery reloads HAProxy

### ISSUE THREAD

**Issue by tuwid** [rancher/rancher#10633]
**Rancher versions:**
rancher/server: 1.6.12

**Infrastructure Stack versions:**
healthcheck:rancher/healthcheck:v0.3.3
ipsec: rancher/net:holde / rancher/net:v0.13.5
network-services: rancher/network-manager:v0.7.18 rancher/metadata:v0.9.5
scheduler:rancher/scheduler:v0.8.2
lb: rancher/lb-service-haproxy:v0.7.17

**Docker version: (`docker version`,`docker info` preferred)**
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
Linux ip-10-103-0-10 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
any
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Spin up a couple of service behin e LB and restart one of them. 
Then just start hitting the LB with ab with a concurrency of 5 like this
ab -c 5 -n 10000 http://LB_ENDPOINT/
**Results:**
`ab` gets a connection reset and drops the test like below
```
$ ab -c 10 -n 10000 http://LB_ENDPOINT/
Benchmarking http://LB_ENDPOINT/ (be patient)
...
apr_socket_recv: Connection reset by peer (104)
Total of 3652 requests completed
```
with the -r option we see the that there are failed requests: 
```
Benchmarking http://LB_ENDPOINT/  (be patient)
...
Complete requests:      200000
Failed requests:        504
...
  50%      2
  95%      2
  99%      3
 100%     15 (longest request)
```

Expected behaviour is that the haproxy would wait for the connection to end before reloading and use the socket reuse option so no connection would be dropped( according to the haproxy configuration in rancher thats what they do but its not working) 

**Possible solutions:**
- first suggested solution: queue up SYN packets and temporarily block SYN packets before reloading haproxy on configuration regeneration.

```
# Set up the queuing discipline
tc qdisc add dev lo root handle 1: prio bands 4
tc qdisc add dev lo parent 1:1 handle 10: pfifo limit 1000
tc qdisc add dev lo parent 1:2 handle 20: pfifo limit 1000
tc qdisc add dev lo parent 1:3 handle 30: pfifo limit 1000

# Create a plug qdisc with 1 meg of buffer
nl-qdisc-add --dev=lo --parent=1:4 --id=40: plug --limit 1048576
# Release the plug
nl-qdisc-add --dev=lo --parent=1:4 --id=40: --update plug --release-indefinite

# Set up the filter, any packet marked with "1" will be
# directed to the plug
tc filter add dev lo protocol ip parent 1:0 prio 1 handle 1 fw classid 1:4
```

Mark SYN packets: 
```
iptables -t mangle -I OUTPUT -p tcp -s 169.254.255.254 --syn -j MARK --set-mark 1
```
If we do the reloading like this: 
```
  sudo iptables -I INPUT -p tcp --dport LB_PORT --syn -j DROP
  # fancy haproxy reload here 
  sudo iptables -D INPUT -p tcp --dport LB_PORT --syn -j DROP
```
We can see that we have 0 failed requests:
```
$ ab -c 10 -n 200000  http://LB_ENDPOINT/
Benchmarking  http://LB_ENDPOINT/ (be patient)
...
Complete requests:      200000
Failed requests:        0
...
  50%      2
  95%      2
  99%      6
 100%   1002 (longest request
```

- second suggested solution: Use DNS round robin load balancing from rancher's internals to not pinpoint it in the HAProxy configuration and we would potentially just remove the IP from the DNS record of the service and flush the cache.

- temporary workarounds:
For light loads one could simply ensure that their HAProxy process is always bound to the same CPU that receives network interrupts. That is doable only with single-queue NICs or multi-queue NICs if all interrupts are routed to the same CPU. Don’t do this when dealing with tens of thousands of connections per second or with multi-gigabit loads requiring multi-queue to stay enabled. Example of binding the NIC and haproxy to CPU 0:
```
$ grep eth0- /proc/interrupts
28: 1259842789 181 PCI-MSI-edge eth0-rx-0
29: 1276436141 772 PCI-MSI-edge eth0-tx-0
$ for i in $(grep eth0- /proc/interrupts |cut -f1 -d:); do
echo 1 > /proc/irq/$i/smp_affinity
done
```

For higher loads, or those who cannot apply the above, or those who use nbproc and cannot bind haproxy’s sockets to the same CPUs that bring the incoming traffic, CAN however block incoming empty ACKs during the reload operation. It is viable to block empty ACKs because they don’t cause any extra delays (contrary to SYNs). ACKs are used to confirm the connection (and are immediately followed by other data), and they are used to acknowledge receipt of segments so that the window can advance (but as long as the send window is not full, segments continue to be transmitted). And they are used at the end to close a LAST_ACK connection and that can safely be delayed as well.
The iptables rule I showed above cannot be used as-is in production because it relies on TCP timestamps and would block other packets without them. The following one presented below is intended for production. It blocks all pure ACK packets as well as those carrying less than 3 bytes of payload without a PUSH flag. It is not possible to match a single byte here because U32 references 32-bit payloads only, but at the same time, 3-byte packets without a PUSH flag do not make sense:
```
$ sudo iptables -I INPUT -i lo -p tcp --dport 80 --tcp-flags SYN,PSH,ACK,FIN,RST ACK -m u32 \! --u32 '0>>22&0x3C@12>>26&0x3C@0&0x0=0:0' -j DROP
$ sudo iptables -I INPUT -i lo -p tcp --dport 443 --tcp-flags SYN,PSH,ACK,FIN,RST ACK -m u32 \! --u32 '0>>22&0x3C@12>>26&0x3C@0&0x0=0:0' -j DROP
```

References: 
http://lartc.org/howto/
https://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html 
https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/

**Comment by tuwid** [comment]
Any updates ? This is a blocker for fully 0 downtime operations in rancher

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
