### ISSUE TITLE
Network policy prevents traffic between cross environment links (within the same region) when region is not specified.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10636]
Rancher versions:v1.6.13-rc6

Steps to reproduce the problem:
Set up has 3 environments - test1 (with stack1/service1), test2 (with stack2/service2) , test3 (with stack3/service3) with "allow access between linked services" network policy.
Create a cross environment service links from test1/service1 to test2/stack2/service2  with alias name say "link1" without specifying regions in the links.

This results in test1 and test2 environments getting linked. Also able to resolve "link1" to container ips of  test2/stack2/service2. But these container ips are not reachable.

**Comment by leodotcloud** [comment]
Fixed in `network-policy-manager:v0.2.6`

**Comment by sangeethah** [comment]
Reopening this issue because of the following 2 issues encountered when testing with network-policy-manager:v0.2.6:


https://github.com/rancher/rancher/issues/11156
https://github.com/rancher/rancher/issues/11210

**Comment by sangeethah** [comment]
Tested with rancher/network-policy-manager:v0.2.7

Have network policy set to "allow within linked services" and "deny" for all others.
Lb with port rules not having regions specified defaults to local region and is functional .
Links with alias name not having regions defaults to local region and is functional .
