### ISSUE TITLE
When remote region url is not reachable , metadata takes very long to respond and scheduler keeps getting recreated. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10647]
Rancher versions:v1.6.13-rc6

Steps to reproduce the problem:
Deploy rancher servers for region1 and region2.
Have cross regions links between environments in region1 and region2.

Make region1's url unreachable.

Metadata requests in region2 start taking very long time to respond ( like 30-45 secs).

Scheduler service becomes unhealthy and scheduler containers keep getting recreated since they get stuck in Initializing state forever.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
