### ISSUE TITLE
Host disconnected due to rancher-ipsec open too many files 

### ISSUE THREAD

**Issue by ezq** [rancher/rancher#10642]
**Rancher versions:**
rancher/server: v1.6.11
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.2
network-services: v0.7.18
scheduler: v0.8.2
kubernetes (if applicable):

**Docker version:**

Containers: 24
 Running: 22
 Paused: 0
 Stopped: 2
Images: 25
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 222
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: docker-aws-stage-2
ID: 6BWW:X54M:LTXA:DDEY:5XQX:BW6K:AOPL:UG63:X65Z:LGYF:HVW3:WKPU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel:**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-103-generic

**Type/provider of hosts: AWS**

**Setup details: single rancher node + external DB (RDS)**

**Environment Template: Cattle**

**Steps to Reproduce:**

Keep running agents for a week

**Results:**

Custom config: 

```
$ grep fs.file-max /etc/sysctl.conf 
fs.file-max = 150000
```

Problem:

```
$ cat /proc/sys/fs/file-nr
137824	0	150000

$ uptime
 15:24:14 up 6 days,  1:21,  1 user,  load average: 1.31, 1.03, 0.97

$ ps fax | grep ipsec
12281 ?        Ssl   44:26      |   \_ rancher-ipsec --gcm=true --charon-launch --ipsec-config /etc/ipsec

$ sudo lsof -p 12281 | wc -l
66954
```

Docker limit configs:

```
$ grep limit /etc/init/docker.conf 
limit nofile 524288 1048576
limit nproc 524288 1048576
```

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
