### ISSUE TITLE
Even after remote region url is edited and set to a new value, there is a constant attempt made by metadata to reach the old rancher url.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10648]
Rancher versions:v1.6.13-rc6

Steps to reproduce the problem:
Deploy rancher servers for region1 and region2.
Have cross regions links between environments in region1 and region2.

Made region1's url unreachable and then changed region1's url to point to a new rancher url.

Metadata containers start using the new rancher url. But there is also constant attempt made to reach the old rancher url which keeps failing.

**Comment by sangeethah** [comment]
Keeping this issue in reopened state , so the this issue can be verified again when  fixes are made to metadata for addressing - https://github.com/rancher/rancher/issues/10299 and https://github.com/rancher/rancher/issues/10364

**Comment by sangeethah** [comment]
I am still able to not see the changes in region(url/keys) being picked up by the metadata services.
Reopening this issue.

**Comment by kinarashah** [comment]
I am kinda confused for 1 & 2, but how I think -  If SA account is deleted or its credentials are invalidated by deleting apiKeys, everything is going to function as it is but no new links can get created. 
3. No, none of them will be allowed to edit. 
4. Deleting a region entry should delete all the account links and agents. On recreating the entry, every thing should be back up and functional. 

Need @alena1108 to confirm

**Comment by sangeethah** [comment]
Tested with v1.6.15-rc4

Region1 - with 3 environments
Region2 - with 3 environments

Deactivate Region1's api keys.

Try to create LB from region1 with targets in region2.
Environment links between the region1 and region2 succeed. This seems to be expected since region1 is still able to access region2.


Try to create LB from region2 with targets in region1.

In this case , I see the account_link stuck in "registering" in DB but environments link in metadata shows that region2 is connected to region1. 

This should not be happening.

Reopening this issue to see why environments link in metadata shows that region2 is connected to region1 even though the account_links table shows it as being stuck in "registering" state.

Note - The reverse link from region1 to region2 was not created which prevents LB to be functional ( network policy prevents this). But LB gets programmed with all the targets which is not expected in this case.

**Comment by sangeethah** [comment]
Moving forward when I edit the region1 entry in region2 and set it to a new set of api keys , all the existing account_links to region1 gets removed. 

But the links are not getting recreated because of this issue - https://github.com/rancher/rancher/issues/11407

**Comment by sangeethah** [comment]
Tested with latest build from 1.6 branch:

Steps to Reproduce:
Region1 - with 3 environments - test1region1, test2region1, test3region1
Region2 - with 3 environments - test1region2, test2region2, test3region2

1. LB in test1region1 linked to targets in test1region2
2. Instance in test2region1 linked to instances in test2region2
3. LB and instances work as expected.
4. Deactivate SA keys for region1

5. Try to create LB in test3region1 linked to targets in test3region2

6.  LB gets created successfully . But it is not able to reach targets in region2 since there is no link created from test3region2 to test3region1. This is as expected.
But I also see that the previously created LB and links cross regions stop working which is tracked in https://github.com/rancher/rancher/issues/12082.

7. Try to create LB in test3region2 linked to targets in test3region1. This fails to get created which is as expected.

8. Create new api keys for the service account of region1.
9. Update region1 entry in region2 to point to correct values.

After this I see the following problems:

1. LB created in step 5 , does not become functional at all since the external links that failed to get created do not ever get recreated.

2. Tried to create a new LB service pointing to existing services cross region from region1 -> region2.
LB service has targets programmed but is not functional.

3. Tried to create a new LB service pointing to new services cross region from region1 -> region2.
LB service does not have even targets programmed. Seems like metadata is not even getting the new updates.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
