### ISSUE TITLE
User API needs Activate and Deactivate actions

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10646]
**Rancher versions:** 2.0 master 12/22

**Results:**

- [x] Description field missing from API

- [ ] Need Activate/Deactivate actions added

**Comment by cjellick** [comment]
A few questions regarding activate/deactivate:

1. Is the intended functionality of activate/deactivate that they shouldn't be able to log into the UI or use the API? 
2. Should admin still be able to add them to groups/projects/clusters?
3. Any other impllications I'm not thinking of?
4. The terminology and paradigm of activate and deactivate actions was largely due to the framework in v1.6. Could we just add a `disabled` boolean field and you PUT and update @vincent99?

Ping @vincent99 @tfiduccia

**Comment by cjellick** [comment]
description field added

**Comment by cjellick** [comment]
> Is the intended functionality of activate/deactivate that they shouldn't be able to log into the UI or use the API?
Yes

> Should admin still be able to add them to groups/projects/clusters?
Yes

> Any other impllications I'm not thinking of?
No for now

> The terminology and paradigm of activate and deactivate actions was largely due to the framework in v1.6. Could we just add a disabled boolean field and you PUT and update @vincent99?
No, keep it as activate/deactivate actions

**Comment by vincent99** [comment]
It can't be `disabled` because of my usual double negative complaint, but `enabled: false` or similar would be ok.

I'll present it as an action in the UI either way.  It doesn't particularly matter to me if the result of clicking it is changing a field and saving or calling an action.

**Comment by dramich** [comment]
Backend is merged, needs UI work

**Comment by deniseschannon** [comment]
@sangeethah backend is in ready for testing

**Comment by adingilloRancher** [comment]
Enabled ADFS
Logged in as testuser2.
Logged out of testuser2.
Set enabled:false for testuser2 as admin.
Logged back in as testuser2.

Creates a new user record for testuser2 after first record is set to inactive. User is able to login. 


![screen shot 2018-08-06 at 9 36 00 am](https://user-images.githubusercontent.com/38012481/43729175-40c6730a-995c-11e8-95ec-33aae56e1edb.png)

**Comment by dramich** [comment]
The user being created again was not related to this, it's a know issue with editing a user through the API UI. 

SAML was not returning a redirect if the user was not enabled so it looked like the login just failed with no error.

**Comment by adingilloRancher** [comment]
Master 6/8

Error is now seen on failed login.
