### ISSUE TITLE
Users UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10645]
**Rancher versions:** 2.0 master 12/21

**Results:**

- [x] On Users list page, Edit on does not go to new edit page.
![image](https://user-images.githubusercontent.com/11514927/34268874-912795ca-e63f-11e7-95bc-8c465cb50212.png)
- [ ] Add User - No Global Roles section
![image](https://user-images.githubusercontent.com/11514927/34270132-5a6e1fae-e644-11e7-9ccb-466c765843f0.png)
- [x] On Users list page, Name is not a required field so Username should be first in list.
![image](https://user-images.githubusercontent.com/11514927/34268856-850dd916-e63f-11e7-9dc6-56b81212f8f9.png)

- [x] On Users list page, Name is not a required field, so link to details page should be on Username.
![image](https://user-images.githubusercontent.com/11514927/34268857-85c7418a-e63f-11e7-8743-ba2bdd323978.png)

- [x] On Users list page, Type is no longer changeable and should not be listed on main page.
![image](https://user-images.githubusercontent.com/11514927/34268903-b0d16716-e63f-11e7-9703-4a8eb904b8c2.png)

- [x] Add User - Change Add Account to say Add User
![image](https://user-images.githubusercontent.com/11514927/34270147-674c5fce-e644-11e7-8410-cb965e01a941.png)

- [x] User Details - Change Account Details to User Details
![image](https://user-images.githubusercontent.com/11514927/34270207-a0601648-e644-11e7-867f-cb9901cc735a.png)

- [x] User Details - Why are there two Project Roles sections?  One should probably be Cluster
![image](https://user-images.githubusercontent.com/11514927/34270264-d070d3f4-e644-11e7-8511-05f72dd1da80.png)

- [x] Edit User - Main field names should not be small and grey.
![image](https://user-images.githubusercontent.com/11514927/34270424-67577c64-e645-11e7-92cd-c9ba95b2ea3f.png)

**Comment by westlywright** [comment]
Items that should go into a new ticket:
* Edit Description/Show Description does not work because the user does not have a description field in the api. it was left in because the user will prob get a desc field eventually.
* Actions do not work because most of the actions do not exist on the user object in the api currently. when they are available they will show up and work.

**Comment by tfiduccia** [comment]
Version - 2.0 master 12/22 
Verified fixed
