### ISSUE TITLE
adding the vultr machine driver does not work

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#10658]
ros 1.1.1 / rancher 1.6.13 / linux 64

Installating a new vultr driver ( 1.4 ) using: https://github.com/janeczku/docker-machine-vultr/releases/download/v1.4.0/docker-machine-driver-vultr-Linux-x86_64

When adding a new host i get:
![image](https://user-images.githubusercontent.com/136934/34320441-c70e5842-e7fa-11e7-9104-496b464c8c2d.png)

When i also manual download the machine-driver (in addition) on the host of the rancher-server into `/usr/local/bin/docker-machine-driver-vultr` the same error occurs

**Comment by EugenMayer** [comment]
Just for reference, the reasons i am trying to upgrade from 1.2.0 is, that i cannot add a host, i registers the host but stops on "waiting for ssh to become available". The referenced ssh-key is actually deployed i can connect to the vultr host using ssh, but it never becomes available in rancher. See https://github.com/janeczku/docker-machine-vultr/issues/35

**Comment by EugenMayer** [comment]
Could that be related to the fact that the current releases are no longer an archive as it used to be in 1.2.0 ?

old url: https://github.com/janeczku/docker-machine-vultr/releases/download/v1.2.2/docker-machine-driver-vultr-v1.2.2-Linux-x86_64.tar.gz

new url: https://github.com/janeczku/docker-machine-vultr/releases/download/v1.4.0/docker-machine-driver-vultr-Linux-x86_64

**Comment by EugenMayer** [comment]
It seems the issue is related the point is, the binary from 1.2.0 will be named `docker-machine-driver-vultr` after getting unpacked, while the 1.4.0 will be named `docker-machine-driver-vultr-Linux-x86_64` thus the machien driver will be named vultr-linux-x86

![image](https://user-images.githubusercontent.com/136934/34320586-ea0cc286-e7fd-11e7-956f-a3f78f96e657.png)

**Comment by EugenMayer** [comment]
could pin that one down - the filename is the actual issue. Its not only _64, its the whole suffix `-x86_64`

i republished 1.4.0 here https://github.com/EugenMayer/docker-rancher-extra-catalogs/tree/master/machine-templates/vultr/releases/1.4.0 using `docker-machine-driver-vultr` as the filename - and using this as my download url https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/machine-templates/vultr/6/url - this will work.

using -x86 or -x86_64 as suffix for the filename will lear to the issue above, now also show up without the suffix:

![image](https://user-images.githubusercontent.com/136934/34320721-915aad12-e800-11e7-9fa2-f883e1545fe6.png)

i guess the binary has to match the `docker-machine-driver-<name>` while name being the catalog name.

**Comment by deniseschannon** [comment]
The vultr machine driver is community driven, and we welcome PRs: https://github.com/rancher/community-catalog/tree/master/machine-templates/vultr

**Comment by DarkBlaez** [comment]
Anyone actually get this to work using the default settings, aside from the usual API key, ssh key etc. I see that no matter which version I use it hangs waiting for SSH attempt

DB

**Comment by EugenMayer** [comment]
thanks to @superseb who found out that this can be fixed by just not providing a ssh-key at all!

So just leave that one blank and it will be able to establish whatever SSH connection is done here..

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
