### ISSUE TITLE
catalog fail clone

### ISSUE THREAD

**Issue by wormen** [rancher/rancher#10659]
added a directory from a private repository, a link format
```
https://{user}:{password}@gitlab.com/{user}/{repo}.git
```
```
ERROR [:] [] [] [] [cutorService-10] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [service.remove:1487255] on [467], canceled by [State [purged] is not valid for process [instance.stop:2043765] on resource [33201]] 
time="2017-12-23T15:44:51Z" level=error msg="Failed to perform catalog refresh: [Catalog refresh failed for Calalog2 (https://{user}:{password}@gitlab.com/{user}/{repo}.git): Clone failed: exit status 128]" 
```
in the terminal this repository is successfully cloned by this link, the problem is only in `rancher`

how can I correct this error within the framework of `rancher`?

`rancher` version 1.16.13
`os` ubuntu 16.04

**Comment by deniseschannon** [comment]
Private repos aren't supported with catalog.

https://github.com/rancher/rancher/issues/3248
