### ISSUE TITLE
Rancher/Cattle: answer to catalog question of type service should be formatted differently

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#10656]
**Rancher versions:**
Rancher | v1.6.12
Cattle | v0.183.30
User Interface | v1.6.30
Rancher CLI | v0.6.5
Rancher Compose | v0.12.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
````
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: app-docker11
ID: HDJR:3TS3:3FCI:XGVZ:CZJW:QKXZ:N5TL:D4ZY:P3TZ:BYUP:RPWA:O63U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.tno.nl:8080/
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
````

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
````
4.4.0-53-generic
````
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Really just question. When I specify in rancher-compose for the catalog a question of type ``service``, the value I get on an answer is ``<stackname>/<servicename>``.

In my case you would like to get a service that I can look up in DNS, i.e. the answer should be formatted as: ``<servicename>.<stackname>``.

Can this be done?  Add a setting to toggle this?

**Results:**

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
