### ISSUE TITLE
Aliyun Webhook service doesn't work with internal Aliyun Dockerhub

### ISSUE THREAD

**Issue by itanger** [rancher/rancher#10654]
我使用的阿里云是内网的地址，使用webhook之后就变成外网

**Comment by itanger** [comment]
1.6.12

**Comment by orangedeng** [comment]
能否提供一下重现的步骤呢？看描述不太理解，提供步骤以后我会把issue用英文重新发一次。

**Comment by itanger** [comment]
使用webhook升级之后，镜像地址由registry-vpc.cn-beijing.aliyuncs.com变更为：registry.cn-beijing.aliyuncs.com

**Comment by loganhz** [comment]
@itanger 能提供一下payload的截图吗？目前Rancher只支持`repo_type : "PUBLIC"`。
![770dcce6442c60fe60b3e85c1e7edeaafef95379](https://user-images.githubusercontent.com/21168270/34344634-ba1c9390-ea22-11e7-8982-8bb24bdf7bb6.png)

**Comment by loganhz** [comment]
We need a new field to let user specify which address (`public`, `internal` or `vpc`) should be used for Aliyun Dockerhub.

![2017-12-26 11 59 13](https://user-images.githubusercontent.com/21168270/34346594-3944041c-ea34-11e7-9dd1-babb88f8046f.png)

**Comment by deniseschannon** [comment]
@kingsd041 this is available in the current master of v1.6-development. you can use `rancher/server:v1.6-development` or wait for the next RC

**Comment by kingsd041** [comment]
Tested with rancher-server version- v1.6.15-rc1 with webhook-service version v0.9.12.
I can get different Aliyun address according to different address types.
`Public --> registry.cn-beijing.aliyuncs.com`
`Classic --> registry-internal.cn-beijing.aliyuncs.com`
`VPC --> registry-vpc.cn-beijing.aliyuncs.com`

@itanger 在Rancher/server v1.6.15-rc1中已经解决，创建webhook时如果你想使用vpc网络，你可以选择`VPC网络`

**Comment by q980916297** [comment]
阿里云国际版对应的镜像仓库地址为registry-intl.xxxx，请问这个地方的地址可以自定义修改么
