### ISSUE TITLE
Agent error when using LetsEncrypt cert

### ISSUE THREAD

**Issue by MarcSaric** [rancher/rancher#10655]
I am having trouble registering a host/agent using certificates from letsencrypt.
I used the certbot to generate the certificates - and configured those into nginx - and browser is accepting the certificate with no warnings. See also 
https://github.com/rancher/rancher/issues/6607#issuecomment-353018686

Setup details.

**Rancher versions:**
rancher/server: 

Component | Version
-- | --
Rancher | v1.6.13
Cattle | v0.183.35
User Interface | v1.6.34
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5

rancher/agent: rancher/agent:v1.2.8

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:v0.13.7
network-services: rancher/metadata:v0.9.5
scheduler: rancher/scheduler:v0.8.3
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)** 
```
marc@xbox:~$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
marc@xbox:~marc@xbox:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
internal DB
startup using the following command:

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start rancher-server using

```
docker run -d --name=rancher-server -v /opt/rancher/var/lib/mysql:/var/lib/mysql --restart=unless-stopped rancher/server:latest
```

Once up, start nginx container using
```
docker run -d --name=nginx --restart=unless-stopped -p 80:80 -p 443:443 -v /etc/letsencrypt:/etc/letsencrypt -v /opt/rancher/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf --link=rancher-server nginx:1.11
```

Login to rancher, add access restrictions, add a host to the Default environment, select custom, copy the resulting string into a local console of the host to be connected and execute:

**Results:**

I expected a succesfull connection, but got the above mentioned error.

However I get this error
```
[...]
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590
[...]
```

I am using the fullchain.pem from certbot, snippet from generation shown below

```
[...]
  /etc/letsencrypt/live/<mydomain>.<dyndns-provider>/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/<mydomain>.<dyndns-provider>/privkey.pem
   Your cert will expire on 2018-03-18. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
[...]
```
nginx config

```
upstream rancher {
  server rancher-server:8080;
}
map $http_upgrade $connection_upgrade {
  default Upgrade;
  ''      close;
}
server {
  listen 443 ssl spdy;
  server_name <mydomain>.<dyndns-provider>;
  ssl_certificate /etc/letsencrypt/live/<mydomain>.<dyndns-provider>/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/<mydomain>.<dyndns-provider>/privkey.pem;
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://rancher;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
    proxy_read_timeout 900s;
  }
}
server {
  listen 80;
  server_name <mydomain>.<dyndns-provider>;
  return 301 https://$server_name$request_uri;
}
```

basically the same shown in the Rancher documentation HowTo.

Further info:

The rancher-server itself sits behind a NAT router in a private network. The NAT router maps external port 4433 to internal port 443 on the nginx container. Consequently, the rancher-server has https://<mydomain>.<dyndns-provider>:4433 as his Host Registration URL in settings.

However, the host in question, which complains about a invalid SSL CERT is on the inside (same subnet behind the NAT router as the rancher-server).

Similar setups work for all kind of other services on VMs in the private network from the inside and outside (e.g. calendar sync using Zimbra over CALDAV and CARDDAV, access to other web applications).

However, if I disable TLS (i.e. start rancher-server with -p 8080:8080 and the appropriate NAT rule I am able to connect internal and external hosts without problem. It is either a nginx or a TLS cert issue in my opinion.

Thanks.

**Comment by superseb** [comment]
Can you share the output of `openssl s_client -showcerts -connect www.example.com:443` here? (from inside the `rancher/agent` container)

**Comment by MarcSaric** [comment]
As the rancher/agent is not starting, that would be difficult (I could start it using a rancher-server without TLS, but would that be the same?

The output of `openssl s_client -showcerts -connect www.example.com:443` from the machine hosting the custom container would be

`marc@xbox:~$ openssl s_client -showcerts -connect www.example.com:443
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
verify return:1
depth=0 C = US, ST = California, L = Los Angeles, O = Internet Corporation for Assigned Names and Numbers, OU = Technology, CN = www.example.org
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=Los Angeles/O=Internet Corporation for Assigned Names and Numbers/OU=Technology/CN=www.example.org
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
-----BEGIN CERTIFICATE-----
MIIF8jCCBNqgAwIBAgIQDmTF+8I2reFLFyrrQceMsDANBgkqhkiG9w0BAQsFADBw
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS8wLQYDVQQDEyZEaWdpQ2VydCBTSEEyIEhpZ2ggQXNz
dXJhbmNlIFNlcnZlciBDQTAeFw0xNTExMDMwMDAwMDBaFw0xODExMjgxMjAwMDBa
MIGlMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEUMBIGA1UEBxML
TG9zIEFuZ2VsZXMxPDA6BgNVBAoTM0ludGVybmV0IENvcnBvcmF0aW9uIGZvciBB
c3NpZ25lZCBOYW1lcyBhbmQgTnVtYmVyczETMBEGA1UECxMKVGVjaG5vbG9neTEY
MBYGA1UEAxMPd3d3LmV4YW1wbGUub3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAs0CWL2FjPiXBl61lRfvvE0KzLJmG9LWAC3bcBjgsH6NiVVo2dt6u
Xfzi5bTm7F3K7srfUBYkLO78mraM9qizrHoIeyofrV/n+pZZJauQsPjCPxMEJnRo
D8Z4KpWKX0LyDu1SputoI4nlQ/htEhtiQnuoBfNZxF7WxcxGwEsZuS1KcXIkHl5V
RJOreKFHTaXcB1qcZ/QRaBIv0yhxvK1yBTwWddT4cli6GfHcCe3xGMaSL328Fgs3
jYrvG29PueB6VJi/tbbPu6qTfwp/H1brqdjh29U52Bhb0fJkM9DWxCP/Cattcc7a
z8EXnCO+LK8vkhw/kAiJWPKx4RBvgy73nwIDAQABo4ICUDCCAkwwHwYDVR0jBBgw
FoAUUWj/kK8CB3U8zNllZGKiErhZcjswHQYDVR0OBBYEFKZPYB4fLdHn8SOgKpUW
5Oia6m5IMIGBBgNVHREEejB4gg93d3cuZXhhbXBsZS5vcmeCC2V4YW1wbGUuY29t
ggtleGFtcGxlLmVkdYILZXhhbXBsZS5uZXSCC2V4YW1wbGUub3Jngg93d3cuZXhh
bXBsZS5jb22CD3d3dy5leGFtcGxlLmVkdYIPd3d3LmV4YW1wbGUubmV0MA4GA1Ud
DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdQYDVR0f
BG4wbDA0oDKgMIYuaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL3NoYTItaGEtc2Vy
dmVyLWc0LmNybDA0oDKgMIYuaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL3NoYTIt
aGEtc2VydmVyLWc0LmNybDBMBgNVHSAERTBDMDcGCWCGSAGG/WwBATAqMCgGCCsG
AQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMAgGBmeBDAECAjCB
gwYIKwYBBQUHAQEEdzB1MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy
dC5jb20wTQYIKwYBBQUHMAKGQWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9E
aWdpQ2VydFNIQTJIaWdoQXNzdXJhbmNlU2VydmVyQ0EuY3J0MAwGA1UdEwEB/wQC
MAAwDQYJKoZIhvcNAQELBQADggEBAISomhGn2L0LJn5SJHuyVZ3qMIlRCIdvqe0Q
6ls+C8ctRwRO3UU3x8q8OH+2ahxlQmpzdC5al4XQzJLiLjiJ2Q1p+hub8MFiMmVP
PZjb2tZm2ipWVuMRM+zgpRVM6nVJ9F3vFfUSHOb4/JsEIUvPY+d8/Krc+kPQwLvy
ieqRbcuFjmqfyPmUv1U9QoI4TQikpw7TZU0zYZANP4C/gj4Ry48/znmUaRvy2kvI
l7gRQ21qJTK5suoiYoYNo3J9T+pXPGU7Lydz/HwW+w0DpArtAaukI8aNX4ohFUKS
wDSiIIWIWJiJGbEeIO0TIFwEVWTOnbNl/faPXpk5IRXicapqiII=
-----END CERTIFICATE-----
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
-----BEGIN CERTIFICATE-----
MIIEsTCCA5mgAwIBAgIQBOHnpNxc8vNtwCtCuF0VnzANBgkqhkiG9w0BAQsFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTEzMTAyMjEyMDAwMFoXDTI4MTAyMjEyMDAwMFowcDEL
MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3
LmRpZ2ljZXJ0LmNvbTEvMC0GA1UEAxMmRGlnaUNlcnQgU0hBMiBIaWdoIEFzc3Vy
YW5jZSBTZXJ2ZXIgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2
4C/CJAbIbQRf1+8KZAayfSImZRauQkCbztyfn3YHPsMwVYcZuU+UDlqUH1VWtMIC
Kq/QmO4LQNfE0DtyyBSe75CxEamu0si4QzrZCwvV1ZX1QK/IHe1NnF9Xt4ZQaJn1
itrSxwUfqJfJ3KSxgoQtxq2lnMcZgqaFD15EWCo3j/018QsIJzJa9buLnqS9UdAn
4t07QjOjBSjEuyjMmqwrIw14xnvmXnG3Sj4I+4G3FhahnSMSTeXXkgisdaScus0X
sh5ENWV/UyU50RwKmmMbGZJ0aAo3wsJSSMs5WqK24V3B3aAguCGikyZvFEohQcft
bZvySC/zA/WiaJJTL17jAgMBAAGjggFJMIIBRTASBgNVHRMBAf8ECDAGAQH/AgEA
MA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
NAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy
dC5jb20wSwYDVR0fBEQwQjBAoD6gPIY6aHR0cDovL2NybDQuZGlnaWNlcnQuY29t
L0RpZ2lDZXJ0SGlnaEFzc3VyYW5jZUVWUm9vdENBLmNybDA9BgNVHSAENjA0MDIG
BFUdIAAwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQ
UzAdBgNVHQ4EFgQUUWj/kK8CB3U8zNllZGKiErhZcjswHwYDVR0jBBgwFoAUsT7D
aQP4v0cB1JgmGggC72NkK8MwDQYJKoZIhvcNAQELBQADggEBABiKlYkD5m3fXPwd
aOpKj4PWUS+Na0QWnqxj9dJubISZi6qBcYRb7TROsLd5kinMLYBq8I4g4Xmk/gNH
E+r1hspZcX30BJZr01lYPf7TMSVcGDiEo+afgv2MW5gxTs14nhr9hctJqvIni5ly
/D6q1UEL2tU2ob8cbkdJf17ZSHwD2f2LSaCYJkJA69aSEaRkCldUxPUd1gJea6zu
xICaEnL6VpPX/78whQYwvwt/Tv9XBZ0k7YXDK/umdaisLRbvfXknsuvCnQsH6qqF
0wGjIChBWUMo0oHjqvbsezt3tkBigAVBRQHvFwY+3sAzm2fTYS5yh+Rp/BIAV0Ae
cPUeybQ=
-----END CERTIFICATE-----
---
Server certificate
subject=/C=US/ST=California/L=Los Angeles/O=Internet Corporation for Assigned Names and Numbers/OU=Technology/CN=www.example.org
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3388 bytes and written 431 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: E0578F2321DA79E0264C7CACA4A4F9F8697A4FB39C72E90B19535B2450596633
    Session-ID-ctx: 
    Master-Key: 55553F4BBF1259903FBDAB80E56A97ABCC10747EA1652BF0E6D83D1D8A3478925823D7EE905338C8254BFEEC3CD975A3
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 41 16 de 65 10 e9 94 00-21 24 67 0b 67 6e dc 43   A..e....!$g.gn.C
    0010 - 3c 11 a5 9e 52 57 7e 54-13 b4 48 76 b4 c4 64 12   <...RW~T..Hv..d.
    0020 - f7 41 77 43 89 fb 1c a5-b4 af a2 1e c0 ee 49 15   .AwC..........I.
    0030 - 35 67 6a 92 e4 7c 28 68-06 dd f9 cc da 8c c0 5f   5gj..|(h......._
    0040 - 7a 75 5d bf d0 19 a1 90-38 24 4c 92 7a 4d 06 77   zu].....8$L.zM.w
    0050 - 17 be dd aa b2 0b f1 c6-24 db 96 92 ed 1f 66 ff   ........$.....f.
    0060 - 63 a5 89 5a fe b8 80 d4-8c 6f f1 5a ed c1 e4 0c   c..Z.....o.Z....
    0070 - 01 55 b7 c7 9e 22 da 4f-e6 45 dd 90 da 15 4a 5c   .U...".O.E....J\
    0080 - 2f ad ce ee 12 bc df a4-b0 9e 0e bb de e7 32 4c   /.............2L
    0090 - 01 24 fb 99 89 cb 63 10-e8 71 a2 a7 25 b5 c6 5a   .$....c..q..%..Z

    Start Time: 1514057299
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
read:errno=0
`

**Comment by MarcSaric** [comment]
And again the full error from trying to start an agent on the internal subnet:

```
marc@xbox:~$ docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.8 https://<mydomain>.<dyndns-provider>:4433/v1/scripts/00F777D98E78E715A743:1483142400000:THFbUF0lG682VByLgIiQxMd3cdM
Unable to find image 'rancher/agent:v1.2.8' locally
v1.2.8: Pulling from rancher/agent
b3e1c725a85f: Pull complete 
6a710864a9fc: Pull complete 
d0ac3b234321: Pull complete 
87f567b5cf58: Pull complete 
063e24b217c4: Pull complete 
d0a3f58caef0: Pull complete 
16914729cfd3: Pull complete 
a9fe38da1fa4: Pull complete 
fc0115c1d040: Pull complete 
Digest: sha256:e5a9cd17ceb29eab2749428a6ed49a85f3457d080d76ea9ec3c6d943e1cbf313
Status: Downloaded newer image for rancher/agent:v1.2.8

INFO: Running Agent Registration Process, CATTLE_URL=https://<mydomain>.<dyndns-provider>:4433/v1
INFO: Attempting to connect to: https://<mydomain>.<dyndns-provider>:4433/v1
INFO: https://<>.<>:4433/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 318, in _load_schemas
    schema_text = self._get_raw(schema_url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 64, in wrapped
    return fn(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 259, in _get_raw
    r = self._get_response(url, data)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
marc@xbox:~$ 
```

**Comment by MarcSaric** [comment]
It was a problem with non-standard ports??

If I set the NAT router to forward std https port 443 to 443 on the nginx container, everything works as it should.

This is definitely not what I would expect. Other web-applications do not balk at having a nonstandard port set to e.g. 4434, 4343, or 4433 or another unpriviledged port-number. Somewhere in the registration, a standard https-port seems to be expected?

Of course, this could be my NAT router doing weird things on forwarding, but the rules are easy enough (TCP 4434 or so to dedicated internal IP port 443, plus a matching firewall-rule, that is all.

**Comment by girtsf** [comment]
FYI, not sure if it's the same issue or not, but I got it to work with Let's Encrypt certs. I had to take  `fullchain.pem` that certbot generates and append the `O=Digital Signature Trust Co., CN=DST Root CA X3` root cert to it.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
