### ISSUE TITLE
Rancher Load Balancer - Error 503

### ISSUE THREAD

**Issue by CarTerr** [rancher/rancher#10652]
**Rancher versions:**
rancher/server: v1.6.12
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec:
network-services:
network-manager:v0.7.7
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
$ docker version
Client:
Version: 17.09.0-ce
API version: 1.32
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:42:18 2017
OS/Arch: linux/amd64

Server:
Version: 17.09.0-ce
API version: 1.32 (minimum version 1.12)
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:40:56 2017
OS/Arch: linux/amd64
Experimental: false

$ docker info
Containers: 2
Running: 2
Paused: 0
Stopped: 0
Images: 38
Server Version: 17.09.0-ce
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
apparmor
seccomp
Profile: default
Kernel Version: 4.4.0-101-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.938GiB
Name: ub
ID: NN4Y:PPBP:X4D4:4ED5:D6YQ:PLGT:DXTI:QLUC:HF4U:QGSJ:MF42:54ZS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

$uname -r
4.4.0-101-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
In new environment add Load Balancer
In Load Balancer add in custom haproxy.cfg next:
```
frontend http-frontend
bind *:80
mode http
redirect scheme https code 301 if !{ hdr(Host) -i zato-admin.local } !{ hdr(Host) -i zato-api.local } !{ ssl_fc }
```
All domain name redirect to 443 port -- it's right
But domain name zato-admin.local and zato-api.local through time receive an error 503. I update the browser's page via f5 and service is opens.
I want the redirection to occur only if there is a domain name have 443 port.
How to do it?

**Results:**

**Comment by CarTerr** [comment]
![1](https://user-images.githubusercontent.com/3523808/34287336-a970f924-e6f7-11e7-9a1e-01ce81060dcd.png)
![2](https://user-images.githubusercontent.com/3523808/34287337-a993f1d6-e6f7-11e7-8ff0-dbd4f94968e5.png)
![3](https://user-images.githubusercontent.com/3523808/34287338-a9b7faea-e6f7-11e7-95ed-fb7013c7e64b.png)

**Comment by MherX** [comment]
frontend 80
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

https://github.com/rancher/rancher/issues/3505

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
