### ISSUE TITLE
kubernetes-dashboard:9090/# Service unavailable

### ISSUE THREAD

**Issue by blueapple168** [rancher/rancher#10650]
*Describe your issue here*
kubernetes-dashboard shows Service unavailable

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.13` Cattle: `v0.183.35` UI: `v1.6.34` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.dashboard`|

**Comment by loganhz** [comment]
@blueapple168 By default, the dashboard image is from google dockerhub which has been blocked in China. You can set up VPN on your server or you can follow the instruction to config it to aliyun dockerhub. https://www.cnrancher.com/kubernetes-installation/

You can find us on `WeChat`. Our `WeChat` ID is RancherLabsChina.
