### ISSUE TITLE
Switch to k8s.gcr.io for container images from GCR

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10666]
```
Use "k8s.gcr.io" for container images rather than "gcr.io/google_containers".  
This is just a redirect, for now, so should not impact anyone materially.  

Documentation and tools should all convert to the new name. 
Users should take note of this in case they see this new name in the system.
```

https://github.com/kubernetes/release/issues/281

https://github.com/kubernetes/kubernetes/pull/54174

**Comment by deniseschannon** [comment]
For 1.6, in the next k8s release (k8s 1.9), we plan on moving all images in GCR into dockerhub so that people without access to GCR would be able to access the images.

**Comment by hogepodge** [comment]
@deniseschannon what's the status of this? Do you have a link to the dockerhub images, or further documentation on how this is going?

**Comment by superseb** [comment]
This is going into the next 1.6 release, which is targeted for end of February. When it releases, all docs will be available.

**Comment by deniseschannon** [comment]
@hogepodge From an end user perspective, you won't notice the difference, but it's been changed in our k8s 1.9 images to pull from dockerhub instead of gcr: https://github.com/rancher/kubernetes-package/pull/133/files
