### ISSUE TITLE
Webhook(host scale up), doesn't work.

### ISSUE THREAD

**Issue by ekonomizer** [rancher/rancher#10668]
Hi! When i tried to add webhook for host upscale, I got some strange warnings: "hostTemplateId is not provided". 
I had host template with label - group: webservice. And I write these key: value in "Host Selector". And I got warnings when click to "Create"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha10` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`hosts.index`|

**Comment by deniseschannon** [comment]
As of the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!
