### ISSUE TITLE
Data lost from the ebs volume in the container when host is rebooted

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10667]
**Rancher versions:**
rancher/server:daishan1992/server:v1.6.12-flexvol
rancher/agent: rancher/agent:v1.2.7-rc2

**Docker version: (`docker version`,`docker info` preferred)**: 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single nose

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a volume 'testebs' from the UI
2. Create a service (of scale 3) using the volume 'testebs' with mountpoint /mydata
3. From one of the containers write data in directory /mydata
4. Reboot host 

After reboot, data is lost from the mountpoint in the containers

**Comment by StrongMonkey** [comment]
@soumyalj i can't reproduce this issue. If one of the container is moved to another then it might be a duplicate of https://github.com/rancher/rancher/issues/10689

**Comment by soumyalj** [comment]
Tested few times with ebs v0.5.0. There was no data loss from the ebs volume after host reboot.
