### ISSUE TITLE
[Windows]Rancher Agent upgrade

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10662]
Now a days, Rancher agent in windows is run as a Windows service. It can not detect the rancher version has update and upgrade itself. It need to support that we can upgrade rancher easily or even automatically.

**Comment by kingsd041** [comment]
@orangedeng 
Tested with rancher/server:v1.6.15-rc3.
I think I still cannot close the issue because I have the following error when updating the agent
```
PS C:\Users\Administrator> $obj |& "C:\Program Files\rancher\startup.ps1"
checking per-host-subnet update
The process cannot access the file 'C:\program files\rancher\per-host-subnet.exe' because it is being used by another pr
ocess.
Get error while running startup.ps1
```

**Comment by orangedeng** [comment]
We are using Windows service to register agent service and handle the crash thing. But we can also use the failure action to upgrade the agent automatically and restart the service. It only requires adding the failure action for it. So I add a crash-loop.ps1 to handle the service stop action and it will connected to Rancher server and download the newest agent version for it.

**Comment by kingsd041** [comment]
I still can not close this issue because I found a new issue #11302

**Comment by kingsd041** [comment]
I tested from v1.6.13 or v1.6.14 upgrade to v1.6.15-rc5, everything is normal after the upgrade. 
But it still cannot be automatically upgraded. You need to manually execute the command upgrade
