### ISSUE TITLE
[Pipeline] Some translation issues

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#10665]
- [x] 1.
![image](https://user-images.githubusercontent.com/9334435/34346716-ad51818a-ea35-11e7-92f0-be1225645aac.png)

- [x] 2.
![image](https://user-images.githubusercontent.com/9334435/34346723-b617d666-ea35-11e7-9ee1-64fe37433ddc.png)

**Comment by kingsd041** [comment]
Tested with Rancher-server v1.6.13 with pipeline v0.1.1
The above problem has been fixed.
