### ISSUE TITLE
Rancher Windows in Feb Release

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10661]
This is the main issue for Rancher Windows support in Feb Release.

There following major features for this release.
* Rancher Agent upgrade
* Webhook service for windows
* CLI support for Windows environment
* Windows environment validation test

**Comment by deniseschannon** [comment]
All parts except for validation testing will be available in v1.6.15-rc2

**Comment by kingsd041** [comment]
The features included in this version have been tested and passed.
About windows environment validation test, I submitted a new issue #12115
