### ISSUE TITLE
Fail to get repo list of authorized GitLab users

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#10676]
**Rancher versions:**
rancher/server: v1.6.13
rancher/agent: v1.2.8

**Pipeline version: v0.1.0**

**Steps to Reproduce:**
1. Set up a fresh GitLab 9.5.10-ce.0
2. Add a group `g1`
3. Add a project `test` to `g1` group
4. Set up GitLab authentication in Pipeline UI
5. Try to add a new pipeline using `test` project

**Results:**
Cannot get `test` project in repo list.

**Comment by gitlawr** [comment]
This is a bug that occurs when a user has permissions to a project via groups but he himself is not a project member.
Currently, a workaround is to add the user to project members via `project settings->members->add to project`. Then you can get the repo list by clicking the refresh button on source code step.
This will be fixed in the next release.

**Comment by kingsd041** [comment]
Tested with Rancher-server v1.6.13 with pipeline v0.1.1
When the user only group permissions can get repo
