### ISSUE TITLE
Service alias changes don't correctly propagate to loadbalancer

### ISSUE THREAD

**Issue by eerootsus** [rancher/rancher#10675]
We are seeing an issue where changes to service alias do not properly make it to the HAProxy loadbalancer.

Our setup is LB -> Alias -> Service stack. We deploy by creating a new stack and once it is up and running we switch the alias to the new stack. This worked perfectly in Rancher v1.2.1. 

But we recently migrated to v.1.6.10 and something seems broken. This happens both from the UI and via CLI.

As you can see, we have two stacks, two containers each, and alias pointing to only one.
![screenshot 2017-12-28 08 12 57](https://user-images.githubusercontent.com/5171437/34402193-cfbf17fe-eba8-11e7-8135-6e60e3fcb197.png)

API also shows only one service link.

But in the LB config all four containers are listed as backends:
![screenshot 2017-12-28 08 13 22](https://user-images.githubusercontent.com/5171437/34402217-f2ce72b2-eba8-11e7-8401-4660a78f651b.png)

When changing the alias again and again we see that `haproxy_new.cfg` is propagated to the container, but still contains 4 backends:
![screenshot 2017-12-28 08 13 39](https://user-images.githubusercontent.com/5171437/34402247-1813d0e4-eba9-11e7-8f68-08209b99dc94.png)

And from logs I can confirm traffic is balanced between 4 containers:
![screenshot 2017-12-28 08 12 30](https://user-images.githubusercontent.com/5171437/34402295-5580e692-eba9-11e7-99c5-9b502a674d42.png)

So it seems that during the initial alias change all four containers are briefly "active". In the UI we can clearly see for a few seconds the alias pointing to both. This change gets to the LB. But then the removal of old stack no longer propagates and currently the only solution we have worked out is to stop/delete the old stack.

**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.11.9
network-services: v0.7.8 (manager) and v0.9.4 (metadata)
scheduler: v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 29
 Running: 28
 Paused: 0
 Stopped: 1
Images: 28
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 271
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: pm-dhost-1
ID: BDKZ:26EO:UUAL:DA5Z:Q4A4:2WX4:TFKF:CMF4:K2DK:LPHS:JYP4:F52F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
```
4.4.0-97-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`OpenStack`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single rancher, DB running in a container on the same host.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Comment by eerootsus** [comment]
I tried to reproduce this and created a small Rancher setup on my own machine. Everything works. So I suspect this is related to the latency within a larger setup. Maybe related to internal DNS?

Alias change on my own machine was instant.

**Comment by eerootsus** [comment]
Yes - I can confirm DNS retains the old alias and returns both new and old stack container IPs.

```
curl -vvv secure-token-service-production.secure-token-service.rancher.internal
* Rebuilt URL to: secure-token-service-production.secure-token-service.rancher.internal/
*   Trying 10.42.51.182...
* connect to 10.42.51.182 port 80 failed: Connection refused
*   Trying 10.42.212.205...
* connect to 10.42.212.205 port 80 failed: Connection refused
*   Trying 10.42.210.212...
* connect to 10.42.210.212 port 80 failed: Connection refused
*   Trying 10.42.186.218...
* connect to 10.42.186.218 port 80 failed: Connection refused
* Failed to connect to secure-token-service-production.secure-token-service.rancher.internal port 80: Connection refused
* Closing connection 0
```

**Comment by eerootsus** [comment]
Upgraded to latest stable v.1.16.12 and upgraded all the infrastructure and LB stacks to latest - the issue still persists.

**Comment by conet** [comment]
Will anyone look at this? It is very simple to reproduce using the following steps:
1. Setup a stack containing a load balancer and a service alias named `alias`
2. In the load balancer container run `watch -n 0.1 "curl -v -o /dev/null alias 2>&1 | grep 'Connected to alias'"` (use this because ping is not available)
3. Observe a single IP is returned (assuming that the alias points to a service with only one container)
4. Edit the alias and change it to point to another service with only 1 container
5. Observe that both IPs are still returned even though the alias now points towards the second service

**Comment by conet** [comment]
The firs IP is removed from the alias only when the container is stopped.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
