### ISSUE TITLE
[Windows] Routerip not found on Windows Server 2016

### ISSUE THREAD

**Issue by IAPOLINARIO** [rancher/rancher#10679]
**Rancher versions:**
rancher/server: 1.6.13
rancher/agent: 0.1.0

**Docker version:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1944.amd64fre.rs1_release.171129-2100)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 12.22GiB
Name: ttxtc04-dockwin
ID: ESWD:EY3I:REP3:NQEZ:I5QA:MR4W:AD5X:WHZU:RWC4:PDLO:OJOQ:23XN
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows Server 2016 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
- Windows

**Steps to Reproduce:**

- Setup a new machine with Windows Server 2016
- Install all the updates
- Install Docker (following this link: https://docs.docker.com/engine/installation/windows/docker-ee/#optional-make-sure-you-have-all-required-updates)
- Install Docker Compose 
- Create a new docker network (transparent)
- Go to Rancher Server
- Create a new environment
- Add a new catalog (Windows)
- Click to add a new host
- Fill the information in the screen
- Run the command generated by Rancher in your host, for ex:
`New-Item -Path 'C:\Program Files\rancher' -Type Directory
$obj=$(docker run --rm -v "C:\Program Files\rancher:C:\Program Files\rancher" rancher/agent-windows:v0.1.0 -RegisterUrl http://<myhost>.com/v1/scripts/0598300E1213C58B12A2:1483142400000:ZgxnJ2kxZJqzXSy3hlJgoqI8nLg)
$obj |& "C:\Program Files\rancher\startup.ps1"`

**Results:**
```
 not found
At C:\Program Files\rancher\startup_per-host-subnet.ps1:240 char:9
+         throw "$routerip not found"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ( not found:String) [], RuntimeException
    + FullyQualifiedErrorId :  not found
```

**Comment by orangedeng** [comment]
1. Can you give me the information you fill in the add-host page?
2. What does `ipconfig` show?
3. is there other error?

**Comment by IAPOLINARIO** [comment]
1 - Just the subnet for the Windows host: `192.168.0.0/24`
2 - Windows IP Configuration:
```
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : mydomain.COM
   Link-local IPv6 Address . . . . . : fe80::a963:c2f3:7e82:70f6%3
   IPv4 Address. . . . . . . . . . . : 192.168.213.74
   Subnet Mask . . . . . . . . . . . : 255.255.252.0
   Default Gateway . . . . . . . . . : 192.168.213.254

Ethernet adapter vEthernet (HNS Internal NIC):

   Connection-specific DNS Suffix  . : 
   Link-local IPv6 Address . . . . . : fe80::fc03:b2c3:407f:899%10
   IPv4 Address. . . . . . . . . . . : 172.19.112.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 

Ethernet adapter vEthernet (HNSTransparent):

   Connection-specific DNS Suffix  . : 
   Link-local IPv6 Address . . . . . : fe80::592e:23cf:c4c7:1b97%18
   Autoconfiguration IPv4 Address. . : 169.254.27.151
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . : 

Ethernet adapter Ethernet 3:

   Connection-specific DNS Suffix  . : 
   Link-local IPv6 Address . . . . . : fe80::582e:a185:8686:f23c%40
   Autoconfiguration IPv4 Address. . : 169.254.242.60
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . : 

Tunnel adapter isatap.mydomain.COM:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : mydomain.COM

Tunnel adapter isatap.{251B0FA0-EA2D-41C8-A846-07B53C525FB2}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Tunnel adapter isatap.{2023D663-07CA-4733-8336-2895D83201BD}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Tunnel adapter isatap.{0704417C-6443-4F80-9F2C-529D7971A3B5}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
```

3. Only that error.

4 - Docker networks:
```
NETWORK ID          NAME                DRIVER              SCOPE
cd7759475ce8        nat                 nat                 local
addf8deba06a        none                null                local
7daac634a5e8        transparent         transparent         local
```

**Comment by orangedeng** [comment]
Please refer to https://github.com/rancher/rancher/wiki/Creating-Windows-Environments-in--v1.6.13#adding-hosts-into-rancher and try it.
I think you will need to clean up the environment first.

**Comment by IAPOLINARIO** [comment]
Fixed.

Just had to start some services manually:
- `Start-Service rancher-agent`  
- `Start-Service rancher-per-host-subnet`.

Even so, I think you should include more details with that exception message. Just adding the link above with the error message will save a lot of time for many people.

Anyway, thanks a lot for your help!

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
