### ISSUE TITLE
Containers of a service with EBS volume lose the volume/data after host Power OFF

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10689]
Rancher versions:
rancher/server:v1.6.12-flexvol

EBS driver Version: daishan1992/storage-ebs:dev

**Docker version: (docker version,docker info preferred)**1.12.6

Operating system and kernel: (cat /etc/os-release, uname -r preferred) Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

Steps:
1. Create a setup with 3 hosts "h1, h2, h3" on AWS
2. Launch EBS catalog and create a ebs volume "testvol" from the UI storage tab
3. Create a service(non healthcheck enabled) "service1" of scale 3 using ebs volume "testvol"
4. Power OFF the host "h1" where service1 exists.
5. Two containers on host h1 move to h2, and one container moves to h3

The containers on the host h2 do not contain the volume any more and there is no data. The container on h3 contains the volume and data. Since EBS volume is shared between the containers of the service, the volume does not exist in the containers on h2. All containers of the service with EBS volume should exist on the same host.

The same was observed for healthcheck enabled service. Volume from the container which moved to another host( where volume does not exist)
```
root@fd2ca1bbae39:/data# ls
ls: reading directory .: Input/output error
root@fd2ca1bbae39:/data#
```
<img width="1123" alt="screen shot 2017-12-29 at 12 06 36 pm" src="https://user-images.githubusercontent.com/18536626/34446590-2f942492-ec91-11e7-9e89-a5fa26d101ec.png">

**Comment by StrongMonkey** [comment]
can’t reproduce after the new build, noticed that @alena mentioned there is a race condition that the instance get reconciled right before host goes down. so they can be moved to another host  . However, no matter whether the race condition will happen, the containers will not go to different hosts due to the volume affinity rule. Let me know if this is not the case when you retest it with the new build.

**Comment by soumyalj** [comment]
Tested with ebs v0.5.0. Created a  health check enabled service using ebs volume. Powered off the host where the service containers existed. The containers moved to another host and data was intact in the volume.
https://github.com/rancher/rancher/issues/10716
