### ISSUE TITLE
Service Link and External Service information is not showing up in Details page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1068]
v0.23.0-rc1
Steps:
1. Create a service and start it
2. Create another service and link to the first service, put "TestName1" in the As Name field for link
3. Create and start service
4. Click on Service name to go to Service details page

Results:
The service link information does not show up anywhere on the details page.

Expected:
The information should show up so user know how to use it.

**Comment by vincent99** [comment]
Agree would be nice, but not for release.

**Comment by tfiduccia** [comment]
This is happening for External Services as well.  Please add external IP info

**Comment by tfiduccia** [comment]
This was added in the new UI.  Fixed
