### ISSUE TITLE
Default rancher security group (rancher-machine) prevents access to logs

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#10697]
**Rancher versions:**
- rancher/server: 1.6.12
- rancher/agent: 1.2.7

**Infrastructure Stack versions:**
- healthcheck: v0.3.3
- ipsec:v0.13.5
- network-services:
- rancher/metadata:v0.9.5
- rancher/network-manager:v0.7.18
- scheduler:v0.8.2
- kubernetes (if applicable): rancher/k8s:v1.8.3

**Docker version: (`docker version`,`docker info` preferred)**
```bash
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1043-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.9MiB
Name: ip-10-0-0-58
ID: OGE4:6JUL:LEEA:QTOD:NDQC:UE2E:5OLE:I3VL:4YIK:DLHY:PNDH:NONJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ uname -r
4.4.0-1043-aws

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS - using `t2.small` instance for the Server.
The Rancher server is behind a classic ELB with SSL termination (on the ELB)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- 1 Rancher Server
- 3 Rancher Nodes
- External db (RDS instance)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create a kubernetes environment
2. When adding hosts to the respective infrastructure, select the proposed (`rancher-machine`) security group for them
3. Deploy a pod
4. Try to access its logs via `kubectl logs -f <pod_id>`

**Results:**
No logs appear.
When trying to access the pod's logs via the k8s dashboard, an empty page is returned.

**However** when allowing all traffic from all sources to the `rancher-machine` sg, the problem is resolved.

**Proposed solution**: modify the settings of  `rancher-machine` sg to allow logs access.
In the mean time it would be highly valuable to inform us on what port and from which source we should open on the particular security group.

**Comment by pkaramol** [comment]
** update **: not only the above issue prevents access to logs, but also prohibits attaching to a container.

```
kubectl exec -it <pod_id> -- /bin/bash
```

not working by default.

When allowing all ports from all sources on `rancher-machine`, it works.

**Comment by pkaramol** [comment]
What is more, when exposing a `LoadBalancer` service (which in our case will create a HAProxy container) e.g. as follows:

```
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
  - name: http
    port: 80
    targetPort: my-named-port
    protocol: TCP
  - name: https
    port: 443
    targetPort: my-named-port
    protocol: TCP
  selector:
    some-pod-label: some-pod-label-value
  type: LoadBalancer
```

so that both ports `80` and `443` become available the result is as follows:

- with the default `rancher-machine` sg settings, only port `80` is available
- when allowing once again all ports/all sources, both `80` and `443` become available!

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
