### ISSUE TITLE
Sensitive log in pipeline server

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#10694]
**Rancher versions:**
rancher/server: v1.6.13
rancher/agent: v1.2.8

**Pipeline version: v0.1.0**

There is sensitive data exposing in pipeline-server logs when authenticating a git account:
```
json={"credentials":{"scope":"GLOBAL","id":"gitlab:root","username":"oauth2","password":"5cb657ba3e1423b900071a1a6cf65a867876584049a03ac53572cd38f8b55a40","description":"","$class":"com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"}}183.14.132.107 - - [28/Dec/2017:09:33:34 +0000] "POST /v1/settings?action=oauth HTTP/1.1" 200 618
```
We should remove it.

**Comment by kingsd041** [comment]
Tested with Rancher-server v1.6.13 with pipeline v0.1.1
Authorized gitlab, sensitive logs have been removed from pipeline serve
