### ISSUE TITLE
Container List is swamped with purged entries

### ISSUE THREAD

**Issue by robertstagg** [rancher/rancher#10698]
After restarting the rancher server host, I have 300+ purged entries in the container list. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.13` Cattle: `v0.183.35` UI: `v1.6.34` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`containers.index`|

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
