### ISSUE TITLE
Swarmkit Initializing

### ISSUE THREAD

**Issue by jinghuaz** [rancher/rancher#10692]
**Rancher versions:**
rancher/server:v1.6.10
rancher/agent:v1.2.6

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec:v0.11.9
network-services:v0.15.3
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Dcoker 17.09.0-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux release 7.3.1611 (Core) 3.10.0-514.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Dell

When i add five hosts,i found the Infrastructure service:swarmkit-mon(rancher/swarmkit:v1.13.0-beta.1) state: Initializing.
four of five nodes are normal,but have one state Initializing Only,i check logs:
2017/12/29 下午3:10:45time="2017-12-29T07:10:45Z" level=info msg="Listening on port: 2378"
2017/12/29 下午3:20:53Metadata not ready
2017/12/29 下午3:20:54time="2017-12-29T07:20:54Z" level=info msg="Listening on port: 2378"
2017/12/29 下午3:23:49time="2017-12-29T07:23:49Z" level=info msg="Listening on port: 2378"

**Comment by jinghuaz** [comment]
![image](https://user-images.githubusercontent.com/9525903/34431977-4a719926-ecae-11e7-8d95-bf3517c7e54d.png)

**Comment by jinghuaz** [comment]
have any update please,wait...

**Comment by jinghuaz** [comment]
2017/12/29 下午4:17:03time="2017-12-29T08:17:03Z" level=info msg="Listening on port: 2378"
2018/1/2 上午10:04:38Metadata not ready
2018/1/2 上午10:04:39time="2018-01-02T02:04:39Z" level=info msg="Listening on port: 2378"

**Comment by jinghuaz** [comment]
![image](https://user-images.githubusercontent.com/9525903/34477140-67775b06-efd2-11e7-89a3-6be43664e6f8.png)
meta-data service is ready! i don't know why error:Metadata not ready

**Comment by jinghuaz** [comment]
who can help me analytics.thanks.

**Comment by jinghuaz** [comment]
when i add the six host nodes, the six node status is normal,Only the five host node status is Initializing!
![image](https://user-images.githubusercontent.com/9525903/34516570-4ed9d6ba-f0b2-11e7-9802-6b56f91ae621.png)

**Comment by jinghuaz** [comment]
oh,no people can help me ?

**Comment by jinghuaz** [comment]
Hi guys, i have upgraded rancher server to V1.6.14 and all module upgraded latest. the quesition i will focus on it. thanks

**Comment by sebastien85** [comment]
@jinghuaz did you find any solution to that ?
I´m having the same problem.

**Comment by superseb** [comment]
Swarm is experimental and won't be developed/enhanced further.
