### ISSUE TITLE
kubernetes-dashboard not found

### ISSUE THREAD

**Issue by wanghuatao** [rancher/rancher#10696]
*Describe your issue here*
when i computer restart,then kubernetes-dashboard can not found.but  from Applications show Applications was actice. 

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "endpoints"
  },
  "code": 404
}

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha10` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`k8s`|

**Comment by superseb** [comment]
There have been major changes since this tech preview, please try the latest (`v2.0.0-alpha23`, https://forums.rancher.com/t/rancher-tech-preview-update-3-26-2018/9893) and file a new issue if you run into trouble.
