### ISSUE TITLE
Services switch order when I edit them on main Service page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1070]
v0.23.0-rc1
Steps:
1.  Create a Service and name it AService
2.  Create a Service Balancer and name it ABalancer
3.  Start both service and make sure you are on the main Service list page (notice that ABalancer is first and AService is second)
4.  Go to ABalancer menu and click on edit
5.  Cancel edit

Results:
AService is now first and ABalancer is second
![image](https://cloud.githubusercontent.com/assets/11514927/8013790/8560da54-0b80-11e5-99a8-50327afed5e1.png)
![image](https://cloud.githubusercontent.com/assets/11514927/8013803/9770efae-0b80-11e5-999f-725457c2cc2a.png)

Expected:
The Services should not move around because of editing.

**Comment by deniseschannon** [comment]
No longer valid with new UI. Services are added to list alphabetically. 

Verified with v0.49.0-rc1
