### ISSUE TITLE
Agent not Working with Docker in VirtualBox.

### ISSUE THREAD

**Issue by MichelDiz** [rancher/rancher#10704]
**Rancher versions:**
rancher/server: v1.6.13
rancher/agent: v1.2.8

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: net:v0.13.7 /net:holder
network-services: metadata:v0.9.5 / network-manager:v0.7.19
scheduler: v0.8.3
kubernetes (if applicable): nops

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.10.0-ce, build f4ffd25

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Just server, I can't run the agent
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Install Virtual box
install Docker Quickstart terminal (Docker Toolbox)
run Rancher image
Run Agent
No Agent appears
**Results:**
in video.
https://youtu.be/6w9i3He62vM

This is also happening in Windows 10. And it also occurred in a similar context only that the Server was local and the Agent was in the Google Cloud. Today I have not yet tested the GC, but what matters to me right now is to run locally for routine pre-tests.

**Comment by aemneina** [comment]
A couple issues I see. Youre running the agent and server on the same host without adding `-e CATTLE_AGENT_IP` on the agent startup command. You're also not cleaning up the agent state between redeployments. That involves removing the `rancher-agent-state` docker volume and `/var/lib/rancher/state` folder on the agent host.

It might also be helpful to provide the logs of the launched agent, what was displayed was the logs for the boot strap process for the rancher agent.

**Comment by MichelDiz** [comment]
Okay, but this was a clean install. In the video is showing my second attempt just to simulate the issue. I formatted the MAC, installed VirtualBox and then installed Docker and then Rancher. When this issue occurred on the first attempt. That the Host was not listed.

However, I re-formatted the Mac OS for other reasons. And I reinstalled everything again. But this time I installed to tryout version 2.0. And installed the Agent in the first atempt. But it did not start anything (pods stuck). I even made a machine with an older version of Docker2Boot.iso. But it did not work. That's when I decided to try again to install version 1.6 and installed everything right. Finaly the agent was there.

We may declare this as a "resolved issue," but I find it interesting to go deeper into this. Is not there a test team at Rancher to evaluate multiple scenarios at the same time?

I can not generate more logs of that issue, since I formatted every operating system. However, version 2.0 did not work with this same context described.

As I said, it happend even in Google Cloud and also with "Play with Docker".

**Comment by superseb** [comment]
`docker logs rancher-agent` should help here, it will print why it can't join the cluster

**Comment by MichelDiz** [comment]
I did 
`docker logs rancher-agent 2>&1 | tee michellogs3.txt`

But the logs are gigantic. 4MB of data. But this issue I opened earlier is no longer happening. But I'm with another one, it does not open the Shell anymore and it does not display Stats. But it says the container is running.

I'm using the agent now inside a virtual machine with RancherOS.

**Comment by MichelDiz** [comment]
Closing, I will reopen if it happens again and I can post Logs of the Act.
