### ISSUE TITLE
rancher会支持Calico 网络插件吗？

### ISSUE THREAD

**Issue by freedba** [rancher/rancher#10703]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.index`|

**Comment by niusmallnan** [comment]
Rancher2.0是完全基于k8s设计的，Calico本身就和K8s可以很好的集成，所以2.0会支持Calico。

而1.6.x版本的Cattle引擎可以支持Calico，我们有一些付费用户使用了它，但并不向社区用户公开。

**Comment by aemneina** [comment]
this wont be supported for 1.6.

**Comment by aemneina** [comment]
will close it out.
