### ISSUE TITLE
Default subnet start/end ip address will not work for any subnet setting other than default subnet.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10714]
Rancher versions: v1.6.13
Catalog: https://github.com/leodotcloud/rancher-catalog.git
Branch: regions

When older version of ipsec service upgrades to ipsec - leodotcloud/net:regions with subnet being set to any value other than default - 10.42.0.0/16, subnet start/end ip address gets defaulted to incorrect values.

**Comment by deniseschannon** [comment]
In the template merged to catalog, there is no default for subnet start/end IP, so nothing will be automatically set.

**Comment by sangeethah** [comment]
Tested upgrade from 1.6.14 which has environment with subnet as "10.43.0.0/16" to 1.6.15-rc3.
When ipsec is upgraded , there is no default for subnet start/end IP present. When ipsec is upgraded , subnet continues to have start_address as 10.43.0.2 and end_address as 10.43.255.250 which are the default values assigned it to when in 1.6.14.
