### ISSUE TITLE
[cli] Feature required

### ISSUE THREAD

**Issue by MichelDiz** [rancher/rancher#10725]
I would like to have an option to give the CLI "restart" command only on the containers that have a certain Label. Today there is only the option to restart the service or if we know the ID of the container. If I need to restart a set of services and maybe its Sidekicks I would have to do one by one manually. Soon it becomes necessary a feature that allows us to restart any container with a certain label.

Example:

```
rancher restart <Label> <Value>
rancher restart update true
```

or

```
rancher restart target true
rancher restart updService true
rancher restart canRestart true
```

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by MichelDiz** [comment]
Does that mean that there will never be features again? This is curious.

Cheers.

**Comment by loganhz** [comment]
Hi @MichelDiz 
We are focusing on 2.0 now. I guess we will only implement new feature in 1.6 if it is a customer requirement. 
Please let me know if you think we should keep this issue open. Maybe we can come back to implement it in the feature. 
Also any PR is always welcome!
