### ISSUE TITLE
[Pipeline]Default 'Step Running Mode' for stage is not saved correctly 

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#10720]
**Rancher versions:**
rancher/server: v1.6.13
pipeline version: v0.1.0

**Steps to Reproduce:**
1. Add a pipeline, add some stages with default `parallel` Step Running Mode.
2. Save the pipeline.
3. View pipeline config

**Results:**
The running mode of the stages becomes `serial`
![image](https://user-images.githubusercontent.com/5697937/34513857-58236cf2-f0a5-11e7-8fb9-2f69eefb1401.png)

**Comment by kingsd041** [comment]
Tested with Rancher-server v1.6.13 with pipeline v0.1.1.
Test passed.
