### ISSUE TITLE
Retain_ip breaks routing of ssl 

### ISSUE THREAD

**Issue by JohnDavidLarsen** [rancher/rancher#10722]
**Rancher versions:**
rancher/server:v1.6.13
(works in v1.6.10 broken in 1.6.12 and 1.6.13 (not sure about .11)
**Infrastructure Stack versions:**
net:v0.13.7

**Environment Template: Cattle

**Steps to Reproduce:**
Run an nginx container using https ssl port 443.  Set it to Retain IP

**Results:**
Traffic will never reach the port 443.   port 80 works fine.
v1.6.10 works fine, v1.6.12 works until I upgrade the ipsec stack to use v0.13.7  and fresh install straight to v1.6.12 (or 13) is broken.  Site works fine if I don't set retain_ip: true

**Comment by superseb** [comment]
* Are you running ipsec or vxlan?
* Can you share the stack definition so I can reproduce?
* What does `Traffic will never reach the port 443` mean, what error do you get and how are you trying?

**Comment by JohnDavidLarsen** [comment]
ipsec.

In trying to reproduce, I found that only my custom nginx-lua image wasn't
working with the 1.6.12 and retain_ip (its still failing silently) .  A
regular nginx image works.
Close this, I'll open a ticket once I've figured out an easily reproducable
issue. Thanks.
