### ISSUE TITLE
[ui] strange problem in the code of `model/stack` when running `stack.get('externalIdInfo')`.

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#10739]
***Useful Information***
|Versions|Rancher `v1.6.13` Cattle: `v0.183.35` UI: `v1.6.34` pipeline:`0.1.0`|
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|

**Steps to Reproduce:**
For more details, please refer to issue #10738 

***Trigger Condition***
When stack's type is `composeProject`.

**Results:**
`stack.get('externalIdInfo')` returned `undefined` and doesn't run into the code in the `model/stack` in the below
```
externalIdInfo: function() {
    return parseExternalId(this.get('externalId'));
  }.property('externalId')
```

***Expected Results***
`stack.get('externalIdInfo')` run into the code above and return an `object` in any situation.

***Worries***
I think this is an abnormal executing result. This may cause some other strange problems in some other places.

**Comment by biblesyme** [comment]
Below are the normal status and abnormal status comparison between two version of UI on the same code.
![image](https://user-images.githubusercontent.com/9334435/34572054-475a57bc-f1ab-11e7-9180-f1ce14582e07.png)

![image](https://user-images.githubusercontent.com/9334435/34572062-4c65a5a4-f1ab-11e7-8388-6daa1d53dea8.png)

I don't know if there something changed on 2.0 code when stack type is `composeProject`. Did I miss something?

**Comment by biblesyme** [comment]
In the beginning, I thought it was caused by the different version of ember used in UI 1.6.34 and UI 2.0. When I downgrade ember version of pipeline-ui into `"ember-cli": "2.9.1"`. The abnormal situation didn't change.  Or maybe I missed something changed in the logic of dealing with the stack of `composeProject`?

**Comment by vincent99** [comment]
There is no composeProject type in the current 2.0 API, or model class in the current 2.0 UI, so the model you have is presumably a generic ember-api-store Resource.. which doesn't extend Stack and therefore doesn't have externalIdInfo.

(Also Stack no longer exists in 2.0, they're Namespace now)

**Comment by biblesyme** [comment]
Gotcha, thanks, I forgot to check the models in the 1.6.34.
I will close this issue.
