### ISSUE TITLE
Read-Only users can't filter "User" stacks

### ISSUE THREAD

**Issue by kwaio** [rancher/rancher#10736]
When set as a read-only user, the menu entry "Stacks" only contains "All", despite being able to filter stack via the url : /env/1a7/apps/stacks?which=user

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`openldap` |
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by vincent99** [comment]
The main "Stacks" header item goes to User stacks.  This is not going to change for 1.x, and there is no equivalent control for 2.0.
