### ISSUE TITLE
[Pipeline] upgradeStack step finish successfully when the upgrade fails

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#10735]
**Rancher versions:**
rancher/server: v1.6.13
pipeline version: v0.1.0

**Steps to Reproduce:**
1. deploy `test` stack with `ngx` service
2. upgrade stack to:
```
services:
  ngx:
    image: nginx:nonexists
```
**Results:**
Pipeline completed successfully but the upgrade failed.

**Comment by kingsd041** [comment]
Tested with Rancher-server v1.6.13 with pipeline v0.1.1
When I used a non-existent image upgrade, the pipeline upgrade failed. 
Test passed.
Upstack will prompt failure log.
```
 time="2018-01-08T18:29:45Z" level=info msg="Updating ngx" 
2018/1/9 上午2:29:16  time="2018-01-08T18:29:45Z" level=info msg="Upgrading ngx" 
2018/1/9 上午2:35:54  time="2018-01-08T18:36:24Z" level=info msg="[1/1] [ngx]: Started " 
2018/1/9 上午2:35:54  upgrade service test fail:
2018/1/9 上午2:35:54      Expected state running but got error: Error response from daemon: manifest for nginx:20593d8b8468f9616254e212c3e35f3aceab4d30 not found
2018/1/9 上午2:35:54  Build step 'Execute shell' marked build as failure
2018/1/9 上午2:35:55  
2018/1/9 上午2:35:55  Finished: FAILURE
```

![image](https://user-images.githubusercontent.com/19684717/34686762-94cb8a22-f4e7-11e7-848a-4ef5f09a18ca.png)
