### ISSUE TITLE
Include docker versions > 17.06  in Docker install url when adding hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10730]
Rancher server version - v1.6-development

While adding hosts (docker machine), docker versions up to 17.06 is provided as options to choose from for Docker install url.

As of v1.6.13 , docker version 17.09 is already supported and we now extend support for 17.12.
Include docker versions > 17.06  in Docker install url when adding hosts.

**Comment by deniseschannon** [comment]
Can we only show the stable versions? 1.12.x, 1.13x and 17.03,17.06,17.09,17.12?

**Comment by loganhz** [comment]
@deniseschannon done

**Comment by sangeethah** [comment]
Tested with - v1.6.14-rc1

While adding hosts (docker machine), following docker versions shows up now - 1.12.x, 1.13x ,17.03.x,17.06.x,17.09.x,17.12.x and latest ( get.docker.com).
