### ISSUE TITLE
[Pipeline] Add more github users error when using GitHub Enterprise

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#10734]
**Versions info:**
rancher/server: v1.6.3
piepline v0.1.0

***Reproduce Steps***
1. Authenticate user in setting page
2. Authenticate GitHub user
3. After success of step 2, click `Authenticate with GitHub again`

***Result:***
The URL for authentication is wrong.
***Expected Results:***
Go to GitHub in the popping window.

![image](https://user-images.githubusercontent.com/9334435/34549664-5a0bd388-f145-11e7-90ab-80aac402730b.png)

**Comment by kingsd041** [comment]
Tested with Rancher-server v1.6.13 with pipeline v0.1.1
Now you can add more GitHub accounts
