### ISSUE TITLE
Incoherent UX for read-only users

### ISSUE THREAD

**Issue by kwaio** [rancher/rancher#10737]
When logged as a read only user, some buttons disappear (the ability to upgrade a service, to execute a shell and so on), but some still appear and issue an error message "Method not allowed" : 

- "Add Stack"
- "Add from catalog"
- "Add Service / Load Balancer / Alias"
- Scale "+" on a service page
- "Clone" on a service

There should be a unique way to deal with Read Only users, either with a full interface and error messages or mask all unavailable buttons.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`openldap` |
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by vincent99** [comment]
Actions are dynamically removed because they depend on the state of the resource regardless of the kind of user.  Other things don't and haven't been implemented.  #1990.

**Comment by xinity** [comment]
,, w
