### ISSUE TITLE
[cli] "rancher restart" don't restart service with Started-Once state

### ISSUE THREAD

**Issue by MichelDiz** [rancher/rancher#10755]
```sh
./rancher restart <stack/service>
1s26
```

It returns the service ID, but the service does not restart.

```
Component | Version
-- | --
Rancher | v1.6.13
Cattle | v0.183.35
User Interface | v1.6.34
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5


```

**Comment by elfrinjo** [comment]
This is also true when restarting from the web-ui and from container crontab.
Watch out if your backups rely on dumps created by start-once containers

**Comment by mmouterde** [comment]
As workaround, you could change scale to 0 then to 1 :/
~~~
curl -u {...} -X PUT \
-H 'Content-Type: application/json' \
-d '{"scale": 0}' \
./v2-beta/projects/{...}/services/{...}
~~~

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
