### ISSUE TITLE
Rancher database reports "joins without indexes"

### ISSUE THREAD

**Issue by nheinemans** [rancher/rancher#10753]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.2.1
network-services: 0.2.7
scheduler: 0.6.3

**Docker version: (`docker version`,`docker info` preferred)**
17.06.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Rancheros 1.1.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware ESX

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, external MySQL 5.6 Database (Galera cluster with 1 master)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
When running the mysqltuner.pl script against out master MySQL database host, it reports a high number of joins without indexes. We believe this is causing a high disk IO load on our database server which in turn causes aborted connections (17%) and high response times in the Rancher UI/API.

**Results:**
Rancher is responding slow, hosts get disconnected.

**Comment by nheinemans** [comment]
The slow-query log with all queries without indexes:
[zs94a-iog089-slow.log](https://github.com/rancher/rancher/files/1605882/zs94a-iog089-slow.log)

Our my.cnf:
```
[client]
password = 
port = 3306
socket = /var/lib/mysql/mysql.sock

[isamchk]
key_buffer_size = 16M

[mysqld]
basedir = /usr
bind-address = 0.0.0.0
binlog_format = ROW
character-set-server = utf8
collation-server = utf8_general_ci
datadir = /var/lib/mysql
default_storage_engine = InnoDB
expire_logs_days = 10
innodb_autoinc_lock_mode = 2
innodb_buffer_pool_size = 2G
innodb_fast_shutdown = 1
innodb_log_file_size = 256M
join_buffer_size = 1M
key_buffer_size = 16M
log-error = /var/log/mysqld.log
max_allowed_packet = 16M
max_binlog_size = 100M
max_connections = 451
max_heap_table_size = 128M
pid-file = /var/run/mysqld/mysqld.pid
port = 3306
query_cache_limit = 4M
query_cache_size = 0
query_cache_type = 0
skip-external-locking
skip-name-resolve
socket = /var/lib/mysql/mysql.sock
ssl = false
ssl-ca = /etc/mysql/cacert.pem
ssl-cert = /etc/mysql/server-cert.pem
ssl-key = /etc/mysql/server-key.pem
thread_cache_size = 32
thread_pool_size = 24
thread_stack = 256K
tmp_table_size = 128M
tmpdir = /tmp
user = mysql
wsrep_cluster_address = gcomm://zs94a-iog089,zs94a-nnc6te,zs94a-tt809t
wsrep_provider = /usr/lib64/libgalera_smm.so
wsrep_provider_options = gcs.fc_limit=40; gcs.fc_factor=0.8
wsrep_slave_threads = 8
wsrep_sst_auth = sstuser:
wsrep_sst_method = xtrabackup-v2

[mysqld-5.0]
myisam-recover = BACKUP

[mysqld-5.1]
myisam-recover = BACKUP

[mysqld-5.5]
myisam-recover = BACKUP

[mysqld-5.6]
myisam-recover-options = BACKUP

[mysqld-5.7]
myisam-recover-options = BACKUP

[mysqld_safe]
log-error = /var/log/mysqld.log
nice = 0
socket = /var/lib/mysql/mysql.sock

[mysqldump]
max_allowed_packet = 16M
quick
quote-names
```

**Comment by nheinemans** [comment]
We found out our database is never cleaned, meaning it still contains all hosts we ever created since at least 1 year. While investigating, we noticed our database structure differs from an initial database after starting a rancher 1.6.13 server:

- Column agent.external_id is missing from our database
- Column service_consume_map.consumed_service is missing in our database
- Table region is missing from our database

**Comment by nheinemans** [comment]
At the moment, we have the following two questions for Rancher support:
- Why is there no cleaning done on our database? This causes the tables agent and account to grow to about 675k rows.
- Why do we have missing columns and table in our database (as compared to a new rancher install)?

**Comment by BobVanB** [comment]
Is it safe to remove the purged rows from the database?
**For example**: will rancher crash if a audit log is read where a account_id is purged from account.

Something like:
```
##################
# create temporary table
create temporary table purged_account_tmp select id, project_template_id, state from account where kind = 'agent' and state = 'purged'
create temporary table purged_agent_tmp select agent.id, agent.account_id, agent.agent_group_id, agent.zone_id from agent join purged_account_tmp as p on agent.account_id = p.id;

# delete queryies
delete from account where id in (select id from purged_account_tmp);
delete from agent where id in (select id from purged_agent_tmp);

# optimize
optimize table account;
optimize table agent;
```

**Comment by vincent99** [comment]
Foreign key constraints will prevent deleting rows that are still referenced; but the cleanup image I already pointed you guys at handles this...

**Comment by nheinemans** [comment]
@vincent99 We tried this cleanup image on our sandbox environment, but it only cleaned 100k agents out of the 450k in the database. That's why we're wondering if we can safely remove all agents with state purged.

**Comment by vincent99** [comment]
If you have a test environment and a backup of the DB you can try it, but I would not suggest running ad-hoc queries to delete things as safe.

Nothing that's referenced is removed by the cleanup, and Audit Logs are kept for 30 days by default, so that could be a significant number of them.  You can turn down the audit log period (`audit_log.purge.after.seconds` setting) or I suppose truncate the table (nothing references it).  It's also popular there are circular references so running the cleanup more than once finds additional things that are now unreferenced.

**Comment by nheinemans** [comment]
I've tried the cleanup image on a copy of our production DB. It starts with 669828 and 627210 rows in the agent and account tables. After the first run, these tables still contain 644959 and 602132 rows. Running the image again, doesn't change anything on these tables.

Our audit logs are purged after 30 days:
audit_log.purge.after.seconds=2592000

**Comment by deniseschannon** [comment]
@nheinemans There has been separate analysis done that someone has done and we plan on adding the following 3 indexes:

Note: I do not know what the name of the indexes will be yet, but we plan on adding this in an upcoming release. 

```
create index indexA (host_id, state);
create index indexB on host (physical_host_id, id);
create index indexC on physical_host (id);
 ```

**Comment by BobVanB** [comment]
@alena1108 i don't mind having a slow database during an upgrade. If that means that the rest of the time the database has a normal response. Such a task can be explaned.

**Comment by alena1108** [comment]
@BobVanB I understand. My concern wasn't about whether we should add the key to `container_event`, but rather to validate if our cleanup thread does its job on its table, and if not, apply the fixes.

Also primary keys are implicitly indexed in mysql, so no need to index `physical_host.id` and `host.id`

**Comment by sangeethah** [comment]
Tested with Rancher versions: rancher/server: 1.6.15-rc3

Following are the new indexes that have been added:
1. container_event
```
 container_event |          1 | idx_container_event_host_id_state      |            1 | host_id            | A         |          38 |     NULL | NULL   | YES  | BTREE      |         |               |
| container_event |          1 | idx_container_event_host_id_state      |            2 | state              | A         |          50 |     NULL | NULL   |      | BTREE      |         |               |
+
```
2.host 

```
| host  |          1 | idx_host_physical_host_id_id |            1 | physical_host_id | A         |           7 |     NULL | NULL   | YES  | BTREE      |         |               |
| host  |          1 | idx_host_physical_host_id_id |            2 | id               | A         |           7 |     NULL | NULL   |      | BTREE      |         |               |
+-------+------------+------------------------------+--------------+------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
```

**Comment by kinarashah** [comment]
@sangeethah yeah, that is correct. Didn't add for ```physical_host``` since its id was already primary key. Do I need to add anything else for this issue? cc @deniseschannon
