### ISSUE TITLE
[Pipeline] Sort the `History` list in the Pipeline detail page in descending order by time

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#10754]
**Rancher versions:**
rancher/server:v1.6.13
rancher/agent:v1.2.8

**Infrastructure Stack versions:**
pipeline: v0.1.0

**Steps to Reproduce:**
1. Create a Pipeline
2. Run it server times
3. Get into the detail page of this Pipeline.
**Results:**
The history list is in ascending order by time
**Expected Results**
The history list should be descending order by time

**Comment by kingsd041** [comment]
Tested with Rancher-server v1.6.13 with pipeline v0.1.1
Test passed.
