### ISSUE TITLE
Site Access reverts to "Restrict access only...." after rancher/server container restarts

### ISSUE THREAD

**Issue by abienkowski** [rancher/rancher#10756]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.5
network-services: v0.9.5 v0.7.18
scheduler: v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
$ docker info | head
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

$ uname -r
4.4.0-64-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Configure AD/LDAP  and set Site Access to "Allow members of Environments...."

**Results:**
After sometime, highly likely caused by container restart, either manual or application crashing, the setting reverts to "Restrict access to only ...."

Resulting in access denied to users which are members of specific environments.

**Comment by tfiduccia** [comment]
@abienkowski - I am unable to reproduce your problem.  If you have upgraded from a previous version, we did change AD backend and the setting changed and that may have been the problem.  
Can you tell me if you do a restart on the rancher container now, does this still happen?  Did it happen more than once while you are in the same version (1.6.12?)

**Comment by abienkowski** [comment]
Yes, it keeps happening few times a week, We've upgraded to 1.6.12 about a month ago.

I just verified that restart causes the problem to happen.

**Comment by abienkowski** [comment]
Rancher crashed/restarted last night and we lost access again.

**Comment by superseb** [comment]
@abienkowski To reproduce this we need the exact details used on your setup so we can build the same:

- Complete command used to launch `rancher/server`
- Details on DB setup (version, single/multi, proxy/lb)

Can you also share the specs of the machine you are running `rancher/server` on?

**Comment by abienkowski** [comment]
@superseb  I have a reproducible setup :) is there anything I can do on my side to help you debug it.

This maybe a problem in database upgrade. I have first deployed rancher server in around August so this would be probably v1.6.7  I may have skipped couple releases getting it to v.1.6.12 (current)

**Comment by abienkowski** [comment]
Happened again today, log bellow.  Users lost access to the service.

{"log":"2018/01/16 07:30:40 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-16T07:30:40.602515179Z"}
{"log":"2018/01/16 07:30:40 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-16T07:30:40.602521554Z"}
{"log":"2018/01/16 07:30:40 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-16T07:30:40.602529689Z"}
{"log":"2018/01/16 07:30:40 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-16T07:30:40.602538469Z"}
{"log":"2018/01/16 07:30:40 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-16T07:30:40.602545161Z"}
{"log":"2018/01/16 07:30:40 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-16T07:30:40.602551485Z"}
{"log":"time=\"2018-01-16T07:30:40Z\" level=fatal msg=\"Exiting go-machine-service: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [] from [http://localhost:8080/v2-beta]\" service=gms \n","stream":"stderr","time":"2018-01-16T07:30:40.602557803Z"}
{"log":"2018/01/16 07:30:40 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-16T07:30:40.602589034Z"}
{"log":"time=\"2018-01-16T07:30:40Z\" level=fatal msg=\"Parent process went away. Shutting down.\" \n","stream":"stderr","time":"2018-01-16T07:30:40.702021427Z"}
{"log":"Certificate was added to keystore\n","stream":"stderr","time":"2018-01-16T07:30:58.255906258Z"}
{"log":"CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz\n","stream":"stdout","time":"2018-01-16T07:30:58.494219097Z"}
{"log":"CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/go-agent.tar.gz\n","stream":"stdout","time":"2018-01-16T07:30:58.494288979Z"}
{"log":"CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8\n","stream":"stdout","time":"2018-01-16T07:30:58.494296785Z"}

**Comment by abienkowski** [comment]
crashed again, lost access.

{"log":"2018/01/18 08:57:54 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-18T08:57:54.253851396Z"}
{"log":"2018/01/18 08:57:54 http: proxy error: dial tcp 127.0.0.1:8081: getsockopt: connection refused\n","stream":"stderr","time":"2018-01-18T08:57:54.25386Z"}
{"log":"time=\"2018-01-18T08:57:54Z\" level=fatal msg=\"Parent process went away. Shutting down.\" \n","stream":"stderr","time":"2018-01-18T08:57:54.25386828Z"}
{"log":"Certificate was added to keystore\n","stream":"stderr","time":"2018-01-18T08:58:03.49189495Z"}
{"log":"CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz\n","stream":"stdout","time":"2018-01-18T08:58:03.575156409Z"}
{"log":"CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/go-agent.tar.gz\n","stream":"stdout","time":"2018-01-18T08:58:03.575274379Z"}
{

**Comment by Toonix** [comment]
got the same problem since 1.6.10

and the site access dosn't list any ad groups...

**Comment by pingutux** [comment]
Same here...

Rancher versions:
rancher/server: 1.6.14
rancher/agent: 1.2.9

Infrastructure Stack versions:
healthcheck: v0.3.3
ipsec: v0.13.7
network-services: v0.9.5 v0.7.19
scheduler: v0.8.3
kubernetes (if applicable):

Docker version: (docker version,docker info preferred)
$ docker info | head
Containers: 14
 Running: 11
 Paused: 0
 Stopped: 3
Images: 36
Server Version: 1.12.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Native Overlay Diff: true
Logging Driver: journald


Operating system and kernel: (cat /etc/os-release, uname -r preferred)
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


$ uname -r
3.10.0-693.17.1.el7.x86_64

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
KVM

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
HA rancher with external DB (Maria DB galera Cluster)

Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
Cattle

**Comment by superseb** [comment]
Can you share the output of the following DB query before and after it happened:

```
select * from setting where name LIKE '%auth%';
```

Particularly interested in accessmode and allowed.identities, but sharing all would be best.

Thanks

**Comment by abienkowski** [comment]
Before (now)
-----------------
id      name    value
1       api.auth.ldap.openldap.group.dn.field   entryDN
2       api.auth.ldap.openldap.group.member.user.attribute      entryDN
7       api.auth.ldap.access.mode       required
8       api.auth.ldap.domain    <removed>
9       api.auth.ldap.group.search.domain       <removed>
10      api.auth.ldap.group.name.field  name
11      api.auth.ldap.group.object.class        group
12      api.auth.ldap.group.search.field        sAMAccountName
13      api.auth.ldap.login.domain
14      api.auth.ldap.port      <remvoed>
15      api.auth.ldap.server    <removed>
16      api.auth.ldap.service.account.password  <removed>
17      api.auth.ldap.service.account.user      <removed>
18      api.auth.ldap.tls       false
19      api.auth.ldap.user.enabled.mask.bit     2
20      api.auth.ldap.user.enabled.attribute    userAccountControl
21      api.auth.ldap.user.login.field  sAMAccountName
22      api.auth.ldap.user.name.field   name
23      api.auth.ldap.user.object.class person
24      api.auth.ldap.user.search.field sAMAccountName
25      api.auth.ldap.connection.timeout        1000
27      api.auth.provider.configured    ldapconfig
28      api.auth.ldap.allowed.identities        <removed>
29      api.auth.enabler        <removed>
30      api.auth.access.mode    restricted
31      api.auth.user.type      ldap_user
32      api.auth.external.provider.identity.separator   #
33      api.auth.allowed.identities     <removed>
34      api.auth.provider.name.configured       ldapconfig
35      api.auth.external.provider.configured   true
36      api.auth.external.provider.no.identity.lookup   false
37      auth.service.config.update.timestamp    2018-02-15 14:55:57.088684692 +0000 UTC

**Comment by abienkowski** [comment]
I restarted the rancher server container and that causes the issue to occur.

id      name    value
1       api.auth.ldap.openldap.group.dn.field   entryDN
2       api.auth.ldap.openldap.group.member.user.attribute      entryDN
7       api.auth.ldap.access.mode       required
8       api.auth.ldap.domain    ********
9       api.auth.ldap.group.search.domain       ********
10      api.auth.ldap.group.name.field  name
11      api.auth.ldap.group.object.class        group
12      api.auth.ldap.group.search.field        sAMAccountName
13      api.auth.ldap.login.domain
14      api.auth.ldap.port      ********
15      api.auth.ldap.server    ********
16      api.auth.ldap.service.account.password  ********
17      api.auth.ldap.service.account.user      ********
18      api.auth.ldap.tls       false
19      api.auth.ldap.user.enabled.mask.bit     2
20      api.auth.ldap.user.enabled.attribute    userAccountControl
21      api.auth.ldap.user.login.field  sAMAccountName
22      api.auth.ldap.user.name.field   name
23      api.auth.ldap.user.object.class person
24      api.auth.ldap.user.search.field sAMAccountName
25      api.auth.ldap.connection.timeout        1000
27      api.auth.provider.configured    ldapconfig
28      api.auth.ldap.allowed.identities        ldap_user:CN=Adrian Bienkowski,********#ldap_group:********
29      api.auth.enabler        ldap_user:CN=Adrian Bienkowski,********
30      api.auth.access.mode    required
31      api.auth.user.type      ldap_user
32      api.auth.external.provider.identity.separator   #
33      api.auth.allowed.identities     ldap_user:CN=Adrian Bienkowski,********#ldap_group:CN=DevOps users,********
34      api.auth.provider.name.configured       ldapconfig
35      api.auth.external.provider.configured   true
36      api.auth.external.provider.no.identity.lookup   false
37      auth.service.config.update.timestamp    2018-02-15 14:55:57.088684692 +0000 UTC

**Comment by abienkowski** [comment]
@superseb  Any updates?  

The issue does not happen as often with 1.6.14, as it seems more stable.  Before upgrading to the 1.6.14 release the service would restart at least once a week, sometimes more, which would change the settings in the database somehow.

However, I can still reproduce the problem by manually restarting the docker service.

**Comment by abienkowski** [comment]
Problem occurred this morning, service must have crashed and restarted.

**Comment by abienkowski** [comment]
Again issue occurred sometime in the last 24 hours..

Please provide an email where I can send you the logs.

**Comment by superseb** [comment]
Send it to `seb@hostname.com` where hostname is `rancher`.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by Polosa** [comment]
The issue is reproducible on every intentional/unintentional `rancher/server` (1.6.30) restart. The value of `api.auth.access.mode` in the DB (table `setting`) is reset to the default "required". 

Hi @abienkowski, have you found any workaround?

**Comment by Polosa** [comment]
Finally found workaround for us. 

On start or rancher, value of `api.auth.ldap.access.mode` (possibly some legacy entry used in previous versions) is overwriting `api.auth.access.mode` (value used in the current version).

The fix was:
```
update setting set value = 'restricted' where name = 'api.auth.ldap.access.mode';
update setting set value = 'restricted' where name = 'api.auth.access.mode';
```

After that restart of rancher is not causing reset of the flag.
