### ISSUE TITLE
Cannot resolve rancher-metadata.rancher.internal

### ISSUE THREAD

**Issue by building39** [rancher/rancher#10757]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec:
network-services: 
scheduler:
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 17.09.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 219
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 63.04GiB
Name: dcmail-07
ID: F7PS:YXRY:LMYW:PUW5:DXI5:OCCE:ZXRJ:MEHM:UWAL:MYAV:N2UE:4TQN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Digital Ocean

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start container based on Alpine 3.7
Execeute shell
do: curl http://rancher-metadata/latest/self/host

**Results:**
Expected: host metadata
Actual: 
curl: (6) Could not resolve host: rancher-metadata

**Comment by scippio** [comment]
I confirming this. The `curl http://172.17.0.2` is fine.

**Comment by superseb** [comment]
Closing as stale. Most (if not all) references to rancher-metadata have been replaced with IP.
