### ISSUE TITLE
Lb is not functional because of weight being set to "0"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10769]
Rancher versions: v1.6.13
Lb image - ```kinarashah/lb:v0.7.15```

Steps to reproduce the problem:
Note - There is no regions entry.

Create LB service.
When trying to access LB ip,  we get a "503 service unavailable" error.

All the server entries in haproxy.config get programmed with weight 0 because of UI setting weight to "0" for portRules.

```
server dfb78d6bde449053b2a02f02d92cd834214913f5 10.42.125.52:80  weight 0
```

In this case , UI should not be sending "weight" as part of portRules at all or it can set weight to "1" which is what cattle code defaults to .
 @alena1108 , can you confirm what UI should be doing here?

**Comment by sangeethah** [comment]
This issue will be encountered when we upgrade Lb images from rancher/lb-service-haproxy:v0.7.15 to kinarashah/lb:v0.7.15 ( an image which will support weight) for future releases. When deploying LB from UI, weight gets set to “0” which is ignored by “rancher/lb-service-haproxy:v0.7.15" , but weight gets stored in DB as “0” in portRules. Once we upgrade to “kinarashah/lb:v0.7.15" (lb image that supports weight) , weight gets programmed as “0” and Lb becomes non functional .

**Comment by loganhz** [comment]
Changed the default weight value to 1. For a non-region port rule, the weight value will get reset to 1 if users upgrade this LB via UI.

**Comment by sangeethah** [comment]
@loganhz ,  Can the UI be fixed so that it does not send "weight" parameter as part of portRules at all in case of  non region setups ?

**Comment by sangeethah** [comment]
Scenario 1:
Tested with v1.6.14-rc1
Lb image - kinarashah/lb:v0.7.15
Note - There is no regions entry.

Create LB service. Lb works as expected. Weight does not get set for server entries.

Scenario 2:
Tested with v1.6.14-rc1
Lb image -  rancher/lb-service-haproxy:v0.7.15 

When LB images get upgraded  from rancher/lb-service-haproxy:v0.7.15 to kinarashah/lb:v0.7.15 ( an image which will support weight) for future releases, weight does not get set for portRules and LB continues to work as expected after image upgrade.
