### ISSUE TITLE
NFS volume support in 2.0 with kubernetes PV and PVC

### ISSUE THREAD

**Issue by SacDin** [rancher/rancher#10767]
**Rancher versions:**
rancher/server: 2.0
rancher/agent: 2.0-alpha-4

I have setup PV (Persistent Volume) and PVC (Persistent Volume Claim) in kubernetes with NFS and the pods are able to successfully access volumes when deployed through RC (Replication Controller). However, these services deployed through RC are not editable or upgradable through Rancher 2.0 UI (Standalone services as displayed in UI). If I deploy it through rancher, I just need to put volume mount details in kubernetes config file, but rancher does not provide option to edit it and replication is managed by rancher. Can you please on priority provide option to set following in pod yaml : 

```
volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
```

Thank you in anticipation.

**Comment by vincent99** [comment]
There is no support for persistent volumes in the current preview.  We know.

https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview/7405

> Known Major Issues
> Currently, only host bind mounted volumes work. The catalog has been pared down to eliminate the apps that currently use anonymous volumes or named volumes. As we introduce volume support, we’ll add those apps back into the catalog.

**Comment by SacDin** [comment]
Hello @vincent99 
Yes, I know that PV is not supported in rancher 2.0 yet.
All the best for the production 2.0 release.

But, do you have workaround to use NFS or any other persistent volumes on current release right now ? Also, what is the status of implementation and how can I put my effort into coding it and making it live faster ?

Regards.
