### ISSUE TITLE
Cluster with no nodes causes namespace page to 404

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10762]
**Rancher versions:** 2.0 master 1/5

**Steps to Reproduce:**
1.  Create a cluster but don't add any hosts
2.  Switch to that Cluster
3.  Go to Namespace page

**Results:**  Page 404s.
![image](https://user-images.githubusercontent.com/11514927/34623325-281efec6-f20e-11e7-878b-62c95e2d40b3.png)

**Comment:**  All the pages in the cluster menu seem to throw errors in the dev tools cause it's looking for a cluster but it can't find it if there are no nodes.

**Comment by deniseschannon** [comment]
I get a different 404 picture in today's build 

<img width="434" alt="screen shot 2018-01-16 at 2 31 24 pm" src="https://user-images.githubusercontent.com/11410997/35015606-fbc687b2-fac9-11e7-9a1a-00e5e0d31d39.png">

**Comment by deniseschannon** [comment]
Seems fixed in 1/20 morning build?

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Namespace page doesn't show up if you don't have nodes.
