### ISSUE TITLE
Going to project that has no nodes in cluster causes 404 error page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10763]
**Rancher versions:** 2.0 master 1/5

**Steps to Reproduce:**
1.  Create a cluster with no nodes
2. Go to cluster and create a project
3.  From drop-down try to go to project

**Results:**  404 page comes up.

**Comment by deniseschannon** [comment]
Related #10762

**Comment by deniseschannon** [comment]
1/20 - 3pm build, looks fixed?

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
