### ISSUE TITLE
DNS problems

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#10760]
**Rancher versions:**
rancher: v1.6.12

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:v0.13.5, rancher/net:v0.13.5
network-services: rancher/dns:v0.15.3
scheduler: rancher/scheduler:v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
````
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
````
4.4.0-53-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
5 node cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
The problems are intermittent and turn up in different cases:

Case 1:
In this case the container queries its IP address directly after startup via ``hostname -i``. Occasionally this fails. I suspect that the problem is related to DNS. DNS may have no record for the container yet. I have changed the script to use ``$(ip route get 1 | awk '{print $NF; exit}')`` to prevent a DNS query. This seems to work so far.

Case 2:
The set of containers I use rely on a startup order. There is one master container that must be started and be ready prior to all others. The master container opens a network port once it is ready. The slave containers check on this port and proceed when the port is open. Each slave container uses the following command to check for the port ```nc -z -w1 $LRC_MASTERHOST $LRC_MASTERPORT < /dev/null > /dev/null; echo $?```. LRC_MASTERHOST is the containter DNS name. This appears to work fine.

Next, each slave container needs to get the network interface used for connecting to the master (I spare the details why). For this I use the following commands:
````
	HOSTIP=$(getent hosts "$HOSTNAME" | awk '{print $1; exit}')
	NETIF=$(ip route get "$HOSTIP" | awk '{print $5; exit}')
````
Here HOSTNAME is set to the DNS name of the master container.
It turns out that ``getent hosts`` does not always return a HOSTIP (just empty), even when the master container is up and running for some time.

**Results:**
Intermittent problems in resolving DNS names.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
