### ISSUE TITLE
change rancher server ip, agent connets to server error

### ISSUE THREAD

**Issue by pixyonly1** [rancher/rancher#10777]
**Rancher versions:**
rancher/server:                      v1.5.5
rancher/agent:                       v1.2.2

**Infrastructure Stack versions:**
healthcheck:                       rancher/healthcheck:v0.2.3
ipsec:                                  rancher/net:v0.11.2
network-services:               rancher/dns:v0.14.2
scheduler:                           rancher/scheduler:v0.7.5
kubernetes (if applicable):  no

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux 4.6.0-1.el7.elrepo.x86_64 #1 SMP Mon May 16 10:54:52 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DELL R730/R720

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
step1.Install rancher server verson 1.5.5 and add 3 hosts to Cattle environment, then create a stack, it's all ok
step2. Change rancher server ip .
step3. In Rancher, go to Admin -> Settings and update the Host Registration with the updated URL for Rancher server.
After the Host Registration has been updated, go to Infrastructure -> Add Hosts -> Custom. The docker run command to add Rancher agents will have been updated with the new information. Using the updated command, run the command on all the hosts inside my Rancher server environments.

Look up the rancher agent log, you will see error about agent connect to server.

**Results:**

websocket ping closed by server, agent print "connection reset by peer" log.
in rancher server ui, the host will be disconnected .

log:
time="2018-01-04T06:38:46Z" level=info msg="Launching agent" 
time="2018-01-04T06:38:46Z" level=info msg="http://172.16.167.160:8080/v1CBE9356CA022064B1ADAKva6iWeUMcJdNrcdonCDCArHQ5jmdfrzcXjshSK5" 
time="2018-01-04T06:38:46Z" level=info msg="Listening for events on http://172.16.167.160:8080/v1" 
time="2018-01-04T06:38:46Z" level=info msg="launching hostapi" 
time="2018-01-04T06:38:46Z" level=info msg="Starting event router." 
time="2018-01-04T06:38:46Z" level=info msg="Connecting to proxy." url="ws://172.16.167.160:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJyZXBvcnRlZFV1aWQiOiIwNWE5ZGQ3MC1kZjNjLTQ0OTAtNTQ5YS0xZjg5MGY0YjNkOWQiLCJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNTE1MDQ4MjI2LCJpYXQiOjE1MTUwNDc5MjZ9.W7y8yqSFAiEvqCib3nJRx5di_KA2VJGoa_UfLotFU33L1u3KtQkI-9JkVzi_u1D1o0K_PTD4yeQyR3BZqan1UvfaahAiX6p2DdCaAgRaqw5Kr_miR_5r1q3jFQb2pXrQ273V5Hy8DHOeTQYpEmGs-MPtCcUQjetHMkSqguXk3CXoa8-2ZTpBltC96UWGS_jc-VzxHsFXQfozq1boowkjSsvgZpgoambYdWVnallX1RjRhzvNoad0geHhzZ1vbsVKpcbZ8R9yMEDWb29KDs7c5bZpkAaGaMgRe1QcQfF2ffTSo89gjgIMiYS09h94RLb1trS5zjnsJZ26e6PbR9ozIA" 
time="2018-01-04T06:38:46Z" level=info msg="Serialize compute requests: false, driver: overlay" 
time="2018-01-04T06:38:46Z" level=info msg="Initializing event router" workerCount=250 
time="2018-01-04T06:38:46Z" level=info msg="Connection established" 
time="2018-01-04T06:38:46Z" level=info msg="Starting websocket pings" 
time="2018-01-04T06:38:51Z" level=error msg="Received error reading from socket. Exiting." error="read tcp 172.16.167.160:51184->172.16.167.160:8080: read: connection reset by peer" 
time="2018-01-04T06:38:51Z" level=error msg="read tcp 172.16.167.160:51184->172.16.167.160:8080: read: connection reset by peer" 
time="2018-01-04T06:38:56Z" level=warning msg="Hit websocket pong timeout. Last websocket ping received at 2018-01-04 06:38:46.566924623 +0000 UTC. Closing connection." 
time="2018-01-04T06:38:56Z" level=info msg="Connecting to proxy." url="ws://172.16.167.160:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJyZXBvcnRlZFV1aWQiOiIwNWE5ZGQ3MC1kZjNjLTQ0OTAtNTQ5YS0xZjg5MGY0YjNkOWQiLCJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNTE1MDQ4MjM2LCJpYXQiOjE1MTUwNDc5MzZ9.kAdngcqwfsZqmzM4RTgpTvS4JfFvMzWw2dpfUtGUhtrWUvgKkzHeBfhKYzSALjf_f5_MWPXwvKp3jKZZezGnIgb3hAnh2UvNTsN9ckpkpbomZiryuAaubmaeS7UhT9TtmQz0RzGoq0pjYfAYI1BfrWx3wleR3P6E780NMmJ403_Mic62evYnol6OSYaH7OsmTGxyiMR2drAD0J1EevjvjZxi3KLDpnAzJ4lM_ONOrAm6FZO4Bij2hx3gchFt0jYaBHba20yP5wnVKuH4VDU6cVzZzVi7GtsmvjHDeJv7rf0X3ASgHtGM5zhR1jLIQzmGzC7uJ_goY_bcnI2hK8I2ZQ" 
time="2018-01-04T06:39:26Z" level=info msg="Received event: Name: storage.volume.activate, Event Id: 5ad203df-60dd-47c9-a6b9-e23b1fb7ae3e, Resource Id: 1vspm856" 
time="2018-01-04T06:39:26Z" level=info msg="Reply: 5ad203df-60dd-47c9-a6b9-e23b1fb7ae3e, storage.volume.activate, 1vspm856:volumeStoragePoolMap" 
time="2018-01-04T06:39:26Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: ba0a643c-f33f-42f2-ac62-fab062a88336, Resource Id: 1ihm288" 
time="2018-01-04T06:39:26Z" level=info msg="rancher id [340]: Container with docker id [a6a67700bb85702ef6ab9938e9325350170ea05dd845372a5beb471f0aaaa72c] has been started" 
time="2018-01-04T06:39:26Z" level=info msg="Reply: ba0a643c-f33f-42f2-ac62-fab062a88336, compute.instance.activate, 1ihm288:instanceHostMap" 
time="2018-01-04T06:39:31Z" level=error msg="Received error reading from socket. Exiting." error="read tcp 172.16.167.160:51266->172.16.167.160:8080: read: connection reset by peer" 
time="2018-01-04T06:39:31Z" level=error msg="read tcp 172.16.167.160:51266->172.16.167.160:8080: read: connection reset by peer" 
time="2018-01-04T06:39:36Z" level=info msg="Connecting to proxy." url="ws://172.16.167.160:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJyZXBvcnRlZFV1aWQiOiIwNWE5ZGQ3MC1kZjNjLTQ0OTAtNTQ5YS0xZjg5MGY0YjNkOWQiLCJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNTE1MDQ4Mjc2LCJpYXQiOjE1MTUwNDc5NzZ9.aOL9NkHI9K7WbvlVEHCAvmcpPFmBudaJxXIi6Ewu89Mws90reHlPqTb9O1MSDIs6JrQTpXrW6p_PXbg0ZsQNhFiP7PHHWQ2TRZPKqrgj8E4mFTt8KjT-CIYTAwJKxh_L7RiXk6Pg1T3_ur-oNx80pdZXz8V1Yw5sCN4WV5rv9wDdUDmOfqSmg2RRXLUWmt9cy75l05MFAALfY-yVGq1g9_DeNMg7D98_MxeL7psM139TwCOCC6RfFCHhwCVUoTImHbQBENNWDtT_7SgoOo1egihFJhJpYKwl5C6fR-ZNkLBvxFo-Igb8OV9BZzPFZhWjy-3tcPNgyeUKTI8LcTn84Q" 
time="2018-01-04T06:39:41Z" level=warning msg="Hit websocket pong timeout. Last websocket ping received at 2018-01-04 06:39:26.597310255 +0000 UTC. Closing connection." 
time="2018-01-04T06:42:13Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: db9a3ac2-dee4-4e9c-b67c-e48b0d9486df, Resource Id: 1ihm288" 
time="2018-01-04T06:42:24Z" level=info msg="rancher id [340]: Container with docker id [a6a67700bb85702ef6ab9938e9325350170ea05dd845372a5beb471f0aaaa72c] has been deactivated" 
time="2018-01-04T06:42:24Z" level=info msg="Reply: db9a3ac2-dee4-4e9c-b67c-e48b0d9486df, compute.instance.deactivate, 1ihm288:instanceHostMap"

**Comment by pixyonly1** [comment]
rancher server log example：
2018-01-09 03:33:42,519 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [6] count [7] 
2018-01-09 03:33:42,520 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [13] count [7] 
2018-01-09 03:33:42,520 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [7] 
2018-01-09 03:33:47,522 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [8] 
2018-01-09 03:33:47,522 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [6] count [8] 
2018-01-09 03:33:47,523 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [13] count [8] 
2018-01-09 03:33:52,524 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [6] count [9] 
2018-01-09 03:33:52,524 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [9] 
2018-01-09 03:33:52,525 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [13] count [9]

**Comment by superseb** [comment]
Not sure if this is caused by switching IP or anything in front of rancher/server. Is the newly set `Host Registration URL` the IP of the machine running `rancher/server` or are you using a proxy/loadbalancer in front?

**Comment by pixyonly1** [comment]
The ip of rancher/server changed from 172.17.0.3 to 172.17.0.4 . If the ip is the same, rancher/server's log is normal.

**Comment by AmitDJagtap** [comment]
Can someone help with ho to fix this issue ..

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
