### ISSUE TITLE
Cattle: LB should log startup problems

### ISSUE THREAD

**Issue by pcornelissen** [rancher/rancher#10775]
**Rancher versions:**
rancher/server: 1.6.13
rancher/agent: 1.6.13

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**

I now frequently have LB instances that just go off into a restart loop where the LB instance is restarted every few seconds (often too fast to even click on the logs link in the UI).

When I am able to get the logs I only see the error messages mentioned in #10380 
As @superseb  pointed out, this is just a warning that is printed in successful starts as well.

But haproxy should be configured to log whatever leads to the failure. Right now it's impossible to see what may be the cause of the problem and when this is the case even deleting the container won't help because the new one will have the same problem.

Interesting side notes:
- I use these LBs internally to load balance hosts that I don't access via a service registry. So there if no public port conflict or anything like that.
- The LBs have a health check configured, but the service is not killed due to the health check because it's restarting within 1-2 sec, which is too fast for health based restarts
- The host contains system and application containers, but has plenty of unused resources and no load when this happens
- Removing the LB service and re-adding is not a valid option because other services have links on the LB service which get removed along with the service, leaving all linked services in a broken state. (Why is the link removed then? Couldn't it not just be set in a invalid state and then brought back when the service is added again? This would be much more resilient and at the same time would resolve dependencies during deployment)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
