### ISSUE TITLE
healthCheck error

### ISSUE THREAD

**Issue by weiweinews** [rancher/rancher#10771]
**Rancher versions:**
rancher/server:v1.6.13
rancher/agent:v1.2.8

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec:holder,net:v0.13.7
network-services:network-manager:v0.7.19,metadata:v0.9.5
scheduler:scheduler:v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
 Experimental: true
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
[root@rancher11 ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
[root@rancher11 ~]# uname -r
3.10.0-514.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
RHEV
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher,external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:**
Add new host,

**Comment by weiweinews** [comment]
2018/1/8 上午11:37:25time="2018-01-08T03:37:25Z" level=info msg="Starting haproxy listener"
2018/1/8 上午11:37:25time="2018-01-08T03:37:25Z" level=info msg="healthCheck -- starting haproxy\n * Starting haproxy haproxy\n   ...done.\n"
2018/1/8 上午11:37:25time="2018-01-08T03:37:25Z" level=info msg="Scheduling apply config"
2018/1/8 上午11:37:25time="2018-01-08T03:37:25Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 007/033725 (34) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n"
2018/1/8 上午11:37:25time="2018-01-08T03:37:25Z" level=info msg="Scheduling apply config"
2018/1/8 上午11:37:26time="2018-01-08T03:37:26Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2018/1/8 上午11:37:27time="2018-01-08T03:37:27Z" level=info msg="Scheduling apply config"
2018/1/8 上午11:37:27time="2018-01-08T03:37:27Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2018/1/8 上午11:37:27time="2018-01-08T03:37:27Z" level=info msg="Scheduling apply config"
2018/1/8 上午11:37:28time="2018-01-08T03:37:28Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2018/1/8 上午11:37:28time="2018-01-08T03:37:28Z" level=info msg="Scheduling apply config"
2018/1/8 上午11:37:29time="2018-01-08T03:37:29Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2018/1/8 上午11:37:29time="2018-01-08T03:37:29Z" level=info msg="Scheduling apply config"
2018/1/8 上午11:37:30time="2018-01-08T03:37:30Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2018/1/8 上午11:37:32time="2018-01-08T03:37:32Z" level=info msg="Scheduling apply config"
2018/1/8 上午11:37:32time="2018-01-08T03:37:32Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2018/1/8 上午11:37:42time="2018-01-08T03:37:42Z" level=info msg="Scheduling apply config"
2018/1/8 上午11:37:42time="2018-01-08T03:37:42Z" level=info msg="healthCheck -- no changes in haproxy config\n"

**Comment by superseb** [comment]
Can you share the state of the healthcheck? Are they in Initializing? All the info provided does not indicate any error.

**Comment by superseb** [comment]
Please report back so we can investigate.
