### ISSUE TITLE
Can't keep connection two services with network cni rancher

### ISSUE THREAD

**Issue by phucvinh52** [rancher/rancher#10774]
**Rancher versions:**
rancher/server: 1.6.3
rancher/agent:

Hi team,
I have 2 services A and B. Service A connect to service B via socket connection(IPsec rancher network). But It connection can't keep in 5min. Before I used rancher/server:1.1.4 is not fail in this case.
Please help or give me a advice.

Thanks.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
