### ISSUE TITLE
[Pipeline] User-defined Variables Don't Show Hints In CodeMirror

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#10776]
**Rancher versions:**
rancher/server: v1.6.13
rancher/agent: v1.2.8

**Infrastructure Stack versions:**
pipeline: v0.1.0

**Steps to Reproduce:**

1. Create a new Pipeline and Add serval Parameters.
2. Get into any CodeMirror component and input "$".

**Results:**
It hints no user-defined variables.

**Expected Results: **

It hints user-defined variables.

**Comment by kingsd041** [comment]
Tested with Rancher-server v1.6.13 with pipeline v0.1.1
Get into any CodeMirror component and input "$", I can see prompted user-defined variables.
