### ISSUE TITLE
Shell closing fast and no Stats but stats from the Machine showing.

### ISSUE THREAD

**Issue by MichelDiz** [rancher/rancher#10770]
**Rancher versions:**
rancher/server: v1.6.12
rancher/agent:v1.2.7

**Infrastructure Stack versions:**
healthcheck: healthcheck:v0.3.3
ipsec: net:v0.13.5 dns:v0.15.3 metadata:v0.9.5
network-services:v0.7.18
scheduler:v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
```bash
[rancher@rancheros-01 ~]$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
[rancher@rancheros-01 ~]$ docker info
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 19
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.69-rancher
Operating System: RancherOS v1.1.2
OSType: linux
Architecture: x86_64
CPUs: 7
Total Memory: 4.266GiB
Name: rancheros-01
ID: OV3I:HRSZ:3JHE:ZAP2:FTCH:VWM3:PVCW:SO75:BQOW:4FD3:GZX7:LR2Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Rancher OS latest - 4.9.69-rancher
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
VirtualBox => Rancher OS with server NAT
VirtualBox => Rancher OS with agent NAT
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Normal steps.
Prune everething, volumes include, and
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
install all again
**Results:**
1 - Shell closing fast
2 - no Stats
3 - CPU and so on "Connecting..."
But http://hostIP:8080/env/1a5/infra/hosts/1h1/containers is showing Stats from the machine.
```
192.168.25.150 
CPU:
Total: 7x2.57 GHz Limit: 7000 mCPU
Memory:
Total: 4.27 GiB Limit: 4.27 GiB
Storage:
29.4 GiB Local Limit: 24.5 TiB
Provider:
Custom
Kernel:
4.9.69
Docker:
17.06.2-ce
OS:
RancherOS v1.1.2
```

```
Found container ID: 9226437624b19e229902f9d9bb50516d152368face42760f34b6dbf19a56e218
Checking root: /host/run/runc
Checking file: 2910380b0496735bf1fc83271800a173aabbb2dc277cfc185bf0dcb5a3548d50
Checking file: 77e1e219584f6d2842999d809e1df2083047661cd7500868ec768aa96080a024
Checking file: 8ba031d6976d93517b6d7e86137bc17fb8a2966daf76876b2f9a3d8f9c555822
Checking file: 9226437624b19e229902f9d9bb50516d152368face42760f34b6dbf19a56e218
Found state.json: 9226437624b19e229902f9d9bb50516d152368face42760f34b6dbf19a56e218
time="2018-01-08T02:42:54Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/7375/ns/mnt -F -- 
```

The rest of it =============> https://pastebin.com/bdYntNbA
Log from the server =====> https://pastebin.com/0DFmhJfV

**Comment by loganhz** [comment]
@MichelDiz I think this link will help.

http://rancher.com/docs/rancher/v1.6/en/faqs/troubleshooting/#help-i-cannot-execute-the-shell-or-view-logs-of-the-container-from-the-ui-how-does-rancher-access-the-shelllogs-of-a-container

**Comment by loganhz** [comment]
please check that the date/time of the Rancher Server host and Rancher Agent host are in sync.

**Comment by MichelDiz** [comment]
Okay, well, that's probably it. Because I tend to keep the machines in "Saved" state. This should generate some time difference. As before it was just a virtual machine I did not see it happening. These days I decided to separate them and this happened.

Is there any way to synchronize the time in Rancher OS? I'm looking here and I still have not found it. There's just like seeing "date -u" and I see the difference is 10 min.

Cheers

**Comment by loganhz** [comment]
RancherOS has enabled `ntpd` by default. If the server is able to connect to NTP server, it will synchronize the time for you automatically later. As `ntpd` synchronizes the time slowly by design, it might take some time.

More info about `ntpd` https://linux.die.net/man/8/ntpd

**Comment by MichelDiz** [comment]
Solve it - Shell is working now! xD
Wait for the ntpd update does not work. I waited for over an hour and nothing. I had to do it manually even via SSH.
```bash
DATE=`date '+%Y-%m-%d %H:%M:%S'` && ssh rancher@192.168.25.XX "sudo date -u -s '$DATE'" && echo $DATE
```
 Thank you for your support. I Appreciate it
