### ISSUE TITLE
We should be able to set weight per server entry in haproxy config.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10780]
Rancher versions: v1.6.13
Lb image - kinarashah/lb:v0.7.15

Steps to reproduce the problem:
Weight can be set for PortRules when creating LB services.  
All server entries for the backend ( relating to the portRule) ends up having the same weight.

We should have the ability to set weights for each of the the server entries rather than set it to the same value for all the server entries for a backend.

**Comment by alena1108** [comment]
The weight was added for selector based use case, when multiple services get added for the same hostname routing rules. This way weight can be added on per service basis. We are not gonna implement it on per ip basis. Closing for now
