### ISSUE TITLE
Can't activate/Deactivate Node drivers

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10786]
**Rancher versions:** 2.0 master 1/8

**Steps to Reproduce:**
1.  Go to Node Drivers page
2.  Try to activate dimmed Built-In drivers
3.  Try to deactivate Active Built-In drivers

**Results:**  Can't Activate or Deactivate Built-In drivers

**Comment:** I can't activate or deactivate custom node drivers that I added.

**Comment by vincent99** [comment]
UI code is there, need actions on the resource...

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
