### ISSUE TITLE
Failed to upgrade service in rancher stack

### ISSUE THREAD

**Issue by daneb5** [rancher/rancher#10798]
**Rancher versions:**
rancher/server: v1.6.12
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.5
network-services: metadata v0.9.5, network-manager v0.7.18
scheduler: v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
Docker Version: 17.12.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-62-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
- Setup a internal gitlab server with ci, registry and self-signed certificate. 
- Added the certficate to /etc/docker/certs.d/hostnameofgitlabserver/ca.crt
- Create the Stack and the service in Rancher with the docker image in the gitlab registry

**Results:**

```
service.upgrade.wait.exception | Failed to allocate instance [container:1i177]: Bad instance [container:1i177] in state [error]: Error response from daemon: Get https://gitlabserver:4567/v1/_ping: x509: certificate signed by unknown authority
-- | --
```

Gitlab-Runner works fine with the self-signed certificate.
docker login, pull, push works also fine with gitlab-runner with the added certificate in the docker folder.
Our gitlab-ci.yml script runs perfectly, but only the step: deploy_development with the rancher upgrade --stack getting stucked.
Is there a way to ignore the certificate in rancher?

Many thanks

Greetings

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
