### ISSUE TITLE
Nodes stuck in removing state

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10796]
**Rancher versions:** 2.0 master 1/8

**Steps to Reproduce:**
1.  Add an EC2 or DO node
2. After it's completely provisioned, delete it

**Results:**  Error "Waiting on foregroundDeletion" error
![image](https://user-images.githubusercontent.com/11514927/34699305-b22b32d2-f499-11e7-833a-8aad0ae4465b.png)
![image](https://user-images.githubusercontent.com/11514927/34699285-9f31835c-f499-11e7-95a0-78669265141d.png)

**Comment by tfiduccia** [comment]
Although this is being removed from the UI, the node still exist and is stuck in removing ("Waiting on foregroundDeletion")

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed

**Comment by phutchins** [comment]
For anyone still experiencing this issue, I found the solution here: https://github.com/rancher/rancher/issues/13314

It involves re-registering the node you're attempting to delete but with a different hostname. May not work if you don't want to re-add that host however...
