### ISSUE TITLE
Add rolling-upgrade support for Rancher CLI with compose

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1079]
With DNS Service and LB Service, a user can easily perform a green/blue upgrade scenario.  However, we need to support the capability for Rancher CLI/UI to perform a rolling upgrade of a service A to service A'.  It should support by percentage or by number with some type of time interval of bringing down containers from service A and bringing up the same # from service A'.

**Comment by will-chan** [comment]
Closing issue as the primary feature is complete.  Any issues found should be filed separately.

**Comment by flaccid** [comment]
This is in v0.30.0 but I'm not sure if it is documented in http://docs.rancher.com/rancher/rancher-compose/ yet?

**Comment by deniseschannon** [comment]
@flaccid The forums don't do a great job of creating yaml files or fenced code blocks. The documentation will be added shortly! 

syntax to use upgrade: `rancher-compose upgrade service1 service2 <upgrade options>`

Docker-Compose.yml Example
```
service1:
service2:
  image: ubuntu:14.04
```

**Comment by adamkdean** [comment]
+1

**Comment by rebyn** [comment]
+1 this is gold. Giving this a try today!
