### ISSUE TITLE
Separate out compute node traffic to different IPs

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#108]
We need to separate the traffic out between 9345/9346 and 500/4500.  Right now we use the same IP for both.  imagine VPC. 500/4500 should be on the internal VPC IP and then 9345/9346 should be on the public elastic IP.

**Comment by deniseschannon** [comment]
@cjellick Is this still valid now that we've added in the webproxy and no longer need 9345/9346?

**Comment by vincent99** [comment]
This particular phrasing isn't, but we do eventually need to keep track of multiple host IPs, expose them in the API/UI for port mapping, and decide what the right one to use for IPSec communication to a particular target is.
