### ISSUE TITLE
Canceling out of Create Cloud Cluster takes me to a random Cluster page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10809]
**Rancher versions:** 2.0 master 1/9

**Steps to Reproduce:**
1.  Create a cluster
2.  From drop-down go to cluster
3.  Click through the top menu options (Dashboard, Projects, Namespaces, Nodes)
4.  From the drop-down go to Global
5.  Click on Add Cluster
6.  Select Cloud or RKE
7.  Click on Cancel

**Results:**  Seems to take me back either to Projects or Namespace page.  I would like Cancel to take me back to Cluster list page.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/11
This is still broken for me.  If I have been clicking around for a while.  When I cancel out of Add Cloud Cluster page, it takes me to random page.  Same thing if I cancel out of Add RKE cluster.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/10910
