### ISSUE TITLE
Environment variables get removed on `rancher-compose up --upgrade`

### ISSUE THREAD

**Issue by alex-mohemian** [rancher/rancher#10801]
**Rancher versions:**
rancher/server: 1.6.12

**Docker version: (`docker version`,`docker info` preferred)**
12.12.0

I have some production environment variables for my services configured (only) in Rancher. Our CI/CD environment is upgrading the existing service through `rancher-compose up -d --upgrade --force-upgrade --pull --confirm-upgrade` which works fine because the `rancher-compose.yml` and `docker-compose.yml` files are in source control.

However, since the service is re-created, it loses the production value of the environment variables, because these (secret) values are obviously not in source control, nor can our CI/CD environment access them. Basically I'm talking about things like secret keys, passwords etc.

I was hoping that if the environment variable is not defined in the `docker-compose.yml` that it would merge it with the existing variables (that I configured through the Rancher UI) but it seems to just delete them.

What would be the correct way to upgrade a service (or actually just pull the Docker image and restart the service using the new one) without knowing the values of the current environment variables?

**Comment by crolfe** [comment]
I can't comment if this is the intended behaviour or not (it seems reasonable enough to me that it would be), but I am having good success deploying stacks with a combination of Hasicorp's Vault (https://www.vaultproject.io/) and envconsul (https://github.com/hashicorp/envconsul) to set secret/config environment variables when I deploy a stack.  

It does take a bit of work to get these tools up and running, but it has been well worth the investment for my team to put this in place.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
