### ISSUE TITLE
Regions - Document the max limit/any special character restrictions that can be used in PSK field.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10808]
Document the max limit/any special character restrictions that can be used in PSK field.

**Comment by leodotcloud** [comment]
Max size: 64 bytes
- PSK cannot contain newline or double-quote characters.
- PSK can be represented as hexadecimal or Base64 encoded binary values
- A character sequence beginning with 0x is interpreted as sequence hexadecimal digits.
- A character sequence beginning with 0s is interpreted as Base64 encoded binary data.

Only these characters are allowed to be used for setting pre-shared secret key :
 alphanumeric characters      a-z A-Z 0-9
 special characters           - + & ! @ # $ % ^ * ( ) , . : ; _ = < > { } /


References:
- https://wiki.strongswan.org/projects/strongswan/wiki/PskSecret
- https://wiki.strongswan.org/issues/569
- https://community.ubnt.com/t5/EdgeMAX/IPsec-VPN-pre-shared-secret-allowed-characters/td-p/1359612

**Comment by sangeethah** [comment]
Regions wiki documents the requirements for PSK.
