### ISSUE TITLE
Proofreader request for Ukrainian language

### ISSUE THREAD

**Issue by andruwa13** [rancher/rancher#10803]
I would like to become a proofreader on Crowdin for Ukrainian language.

My profile can be seen here: https://crowdin.com/profile/andruwa13

**Comment by vincent99** [comment]
ok, added; There's still a lot changing for 2.0 so it's kind of awkward time to be translating it to another language, but I will sync them before the next preview release and it will settle down eventually.

**Comment by andruwa13** [comment]
Thank you
