### ISSUE TITLE
RKE clusters fail to finish provisioning with nodes that have capital letters

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10802]
**Rancher versions:** 2.0 master 1/9

**Steps to Reproduce:**
1.  Add three DO node
2. Create a RKE cluster using these nodes

**Results:**  Fails to finish provisioning.  We should either prevent them from using capital letters in node creation or allow them.  Error in API - 
"lastUpdateTime": "2018-01-09T18:22:29Z",
"message": "Failed to provision cluster [tanirkecluster]: rpc error: code = Unknown desc = Failed to deploy addon execute job: Job.batch \"rke-network-plugin-deploy-job\" is invalid: spec.template.spec.nodeName: Invalid value: \"taniDOhosts19-1\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')",
"reason": "Error",
"status": "Unknown",
"type": "Provisioned"

**Comment by deniseschannon** [comment]
Related: https://github.com/rancher/rancher/issues/10862

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed
