### ISSUE TITLE
fd/socket leak in the agent

### ISSUE THREAD

**Issue by Nicofuma** [rancher/rancher#1081]
Hi,

Yesterday I had to kill the agent manually (using `kill -9`) because the docker daemon was out of file descriptors.

I gave it a quick look and that's the timeline:
 - `2015/06/03 21:44:54` I enable the rancher agent
 - `2015/06/04 18:00:21` the docker deamon is out of fd
 - A few days later I noticed the issue and killed the agent

I grab the whole docker and rancher agent logs if you want me to search for something in them.

**Comment by ibuildthecloud** [comment]
@Nicofuma Was the docker daemon out of FDs or the rancher agent?  Also, is this RancherOS?  In RancherOS we need to increase the default ulimits given to Docker.

**Comment by Nicofuma** [comment]
It is rancherOS yes. The user docker daemon was out of FDs and when I killer the rancher agent it was back to normal with around 100 FDS instead of 1024.

**Comment by ibuildthecloud** [comment]
@Nicofuma please reopen if you see this issue again.  There has been tons of fixes in Docker since this issue was files that address memory and FD leaks.
