### ISSUE TITLE
Could not decode a text frame as UTF-8

### ISSUE THREAD

**Issue by itanger** [rancher/rancher#10812]
不能远程查看日志
component.js:84 WebSocket connection to 'ws://127.0.0.1:8080/v1/logs/?token=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYXR0bGUiLCJob3N0VXVpZCI6IjExNWU5YmIxLWYzNjUtNDU0Ny01YzY2LTFkMWI1OTQwZmZkOSIsImtpZCI6RlZmF1bHQiLCJpc3MiOiJodHRwOlwvXC9jYXR0bGUuaW8iLCJleHAiOjE1MTU1Nzc2NDksImxvZ3MiOnsiQ29udGFpbmVyIjoiZjRjY2MyZmI4OWY4MDA2NzhiZmQ4ZTc3NGU0MjdiMzlmOWMyMGQyNzkwZTU3ODQ4M2VmMjk0MTUyMDNiNGEyMiIsIkxpbmVzIjo1MDAsIkZvbGxvdyI6dHJ1ZX0sImlhdCI6MTUxNNzM0OX0.UIDZfOSKgq95uBsW6ah_Auq3MaFDFOqh3nAqC5i7tJb1mMlQd7uEStS0x2DAyPpf6_0cXhjV8JOm055rKlMHgCoa2UwFfJAe5TOJDxQfunrFhsd4qlWz6SB0q83vO7ViehuUzW8wnhxX27Yuds4KETYo0xpMbsCd_49xWPUOTzISU1952MDzDjx3iKUatLrMTkulXm6NTGDEmOftUMP2ttCu_GNTYbTqWZF6eyKNpJsz42Lenms9_jPK4JyhrKfHYK25n8CKYyoT5pBG51nSm2vK3-IcFAUbum2HeU8MiyhCblI7WucRcagfICepYHV9ltPyCRqiAxzCS3dmpMpicQ' failed: Could not decode a text frame as UTF-8.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
