### ISSUE TITLE
[Windows] Standalone Containers allows add multiple containers of the same port

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10813]
**Rancher versions:**
rancher/server: 1.6.13
rancher/agent: 

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. Go to the Infrastructure page
2. Add Standalone Containers and set port mapping 80:80
3. Add Standalone Containers again on the same host and set the same port mapping 80:80
**Expected results**
Step 3 add the container failure, the prompt port is already used.
**Results:**
Add container success

**Comment by orangedeng** [comment]
Same thing happened in linux environment with rancher 1.6.12. I think that is a common bug.

**Comment by orangedeng** [comment]
I want to move it out of Feb release because it will need to be fixed and test both in windows and linux environment. @deniseschannon

**Comment by deniseschannon** [comment]
Is this only for standalone containers? For services, you are not allowed to add multiple services of the same port, correct? @kingsd041 @orangedeng

**Comment by orangedeng** [comment]
No, you are not allowed to do that. I think that cattle does the validation for service port but not for standalone container port.
