### ISSUE TITLE
reboot machine or restart docker service rancher/server is not running as expected

### ISSUE THREAD

**Issue by pixyonly1** [rancher/rancher#10811]
**Rancher versions:**
rancher/server:        v1.5.5
rancher/agent:        rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck:            rancher/healthcheck:v0.2.3
ipsec:                       rancher/net:v0.11.2
network-services:    rancher/network-manager:v0.6.6  rancher/dns:v0.14.2  rancher/metadata:v0.9.1
scheduler:                rancher/scheduler:v0.7.5
kubernetes (if applicable):  no

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
os  :  centos 7.2  
kernel : 4.6.0-1.el7.elrepo.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Dell R720/R730
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node with internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1.Add the same machine that is running the rancher/server container as a host ( i set the public ip)
2.Reboot machine or restart docker service
3.restart a container on rancher/server host by rancher UI
see rancher/server log 
**Results:**
connection reset by peer
rancher/server log:
time="2018-01-10T02:32:09Z" level=info msg="Registering backend for host 339bc9ba-de1f-42d5-46c0-1316152e90be with session ID 05057ef0-b4c4-4ec4-a314-38cac55ccd25." 
time="2018-01-10T02:32:24Z" level=info msg="Shutting down backend 772b99fa-8c49-43ce-58be-022d9400fa43. Connection closed because: read tcp 172.17.0.5:8080->172.17.0.1:48210: read: connection reset by peer." 
time="2018-01-10T02:32:24Z" level=info msg="Removed backend. Key: 772b99fa-8c49-43ce-58be-022d9400fa43. Session ID c20cf44e-14db-4bf2-9413-18ff1012e148 ." 
time="2018-01-10T02:32:29Z" level=info msg="Handling backend connection request." 
time="2018-01-10T02:32:29Z" level=info msg="Registering backend for host 772b99fa-8c49-43ce-58be-022d9400fa43 with session ID 81a0d34c-f920-4003-9ae7-c531340b8d55." 
time="2018-01-10T02:34:14Z" level=info msg="Shutting down backend 772b99fa-8c49-43ce-58be-022d9400fa43. Connection closed because: websocket: close 1006 unexpected EOF." 
time="2018-01-10T02:34:14Z" level=info msg="Removed backend. Key: 772b99fa-8c49-43ce-58be-022d9400fa43. Session ID 81a0d34c-f920-4003-9ae7-c531340b8d55 ." 
time="2018-01-10T02:34:20Z" level=info msg="Handling backend connection request." 
time="2018-01-10T02:34:20Z" level=info msg="Registering backend for host 772b99fa-8c49-43ce-58be-022d9400fa43 with session ID 435bef71-3108-42e6-bf89-4cf2e7753614." 
time="2018-01-10T02:35:00Z" level=info msg="Shutting down backend 772b99fa-8c49-43ce-58be-022d9400fa43. Connection closed because: read tcp 172.17.0.5:8080->172.17.0.1:35516: read: connection reset by peer." 
time="2018-01-10T02:35:00Z" level=info msg="Removed backend. Key: 772b99fa-8c49-43ce-58be-022d9400fa43. Session ID 435bef71-3108-42e6-bf89-4cf2e7753614 ." 
time="2018-01-10T02:35:05Z" level=info msg="Handling backend connection request." 
time="2018-01-10T02:35:05Z" level=info msg="Registering backend for host 772b99fa-8c49-43ce-58be-022d9400fa43 with session ID 2c2117da-8647-405b-8058-24f904f2dfab." 

**Reason:**
rancher/server internal ip is changed.
before reboot or restart docker service rancher/server internal ip(172.16.0.3) and iptables

153: eth0@if154: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.3/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:3/64 scope link 
       valid_lft forever preferred_lft forever

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9420 to:172.17.0.2:9418
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.17.0.3:8080
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9418 to:172.17.0.5:9418

after reboot/resart docker service

193: eth0@if194: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:05 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.5/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:5/64 scope link 
       valid_lft forever preferred_lft forever

 Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9420 to:172.17.0.2:9418
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9418 to:172.17.0.3:9418
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.17.0.5:8080

**Comment by pixyonly1** [comment]
rancher 1.6.10 has the same problem

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
