### ISSUE TITLE
Can't edit a GKE node

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10817]
**Rancher versions:** 2.0 master 1/10

**Steps to Reproduce:**
1.  Edit a GKE cloud node
2.  Change the custom name and add a label
3.  Save your changes

**Results:**  the changes flash in the UI then disappear.  If you go back to edit you can see that your changes have been removed.

**Comment by StrongMonkey** [comment]
Not able to reproduce in the latest build now.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed
