### ISSUE TITLE
milliCPU API validation failure

### ISSUE THREAD

**Issue by parthiban-srinivasan** [rancher/rancher#10810]
*Describe your issue here*
After expanding & closing "Advanced Options" under Add Host, encountering below error message while submitting "Create".

"milliCPU API" when no values are entered for CPU.     

Via try.rancher.com
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.17` |
|Access|`github` |
|Orchestration|``|
|Route|`hosts.index`|

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
