### ISSUE TITLE
Secret keys do not work with the forward slash in them

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#10815]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.2.0
ipsec: v0.8.1
network-services: v0.9.1
scheduler: ?

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Container Linux by CoreOS 1520.8.0 (Ladybug)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a secret with a key containing a `/` in it (such as `foo/bar`)
OR
Assign a secret to the container with the name containing a `/` in it (such as `foo/bar`)

**Results:**
500 error when trying to mount secrets

**Workaround:**
Avoid using slashes in the keys

**Expected behaviour**
For slashes to work or for Rancher to stop me when slashes would break the mounting of secrets.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
