### ISSUE TITLE
[Windows] Remove container, port mapping has not been removed

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10814]
**Rancher versions:**
rancher/server: 1.6.13
rancher/agent:

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. Follow #10813  to add two containers of the same port
2. Waiting for the container to running
3. Delete these two containers
4. Run `netsh routing ip nat show interface` on the windows host to check the port mapping
**Results:**
Port mapping is not removed
```
PS C:\Users\Administrator> netsh routing ip nat show interface
>>

NAT Ethernet 2 Configuration
---------------------------
Mode              : Address and Port Translation


NAT Static Port Mapping Configuration
-------------------------------------
Protocol          : TCP
Public address    : 0.0.0.0
Public port       : 80
Private address   : 192.168.2.104
Private port      : 80

Protocol          : TCP
Public address    : 0.0.0.0
Public port       : 80
Private address   : 192.168.2.8
Private port      : 80

PS C:\Users\Administrator>
```

**Comment by orangedeng** [comment]
Root cause has been located.
Because https://github.com/rancher/rancher/issues/10813 , after adding multiple containers with exposing same port, the NAT in the host broke. The metadata service can not get any updated so per-host-subnet can not get the new status of containers. Therefor, per-host-subnet does not delete those rules

**Comment by orangedeng** [comment]
Assume that https://github.com/rancher/rancher/issues/10813 should not happen. This bug will not be fixed for now.
