### ISSUE TITLE
Kubernetes CLI shell window is broken

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10816]
**Rancher versions:**
rancher/server: v1.6.14-rc1

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Deploy Kubernetes, open Kubernetes -> CLI

**Results:**
<img width="755" alt="k8sclibroken" src="https://user-images.githubusercontent.com/2620179/34794237-58ffa4fc-f64e-11e7-8169-695627b2c190.png">

Chrome Version 63.0.3239.132 (Official Build) (64-bit)
macOS High Sierra 10.13.2

**Comment by soumyalj** [comment]
Tested with v1.6.14-rc2. Kubernetes CLI shell window is functional.
<img width="1085" alt="screen shot 2018-01-11 at 12 16 05 pm" src="https://user-images.githubusercontent.com/18536626/34845314-54226854-f6c9-11e7-904c-9d785c3efeec.png">
