### ISSUE TITLE
Can't remove custom name from node created from machine driver

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10818]
**Rancher versions:** 2.0 master 1/10

**Steps to Reproduce:**
1.  Add a Digital Ocean node
2.  Edit the DO node
3.  Add a custom name and save
4.  Edit the DO node
5.  Remove the custom name and save

**Results:**  The custom name is not removed.  Should remove and go back to display name.

**Comment by StrongMonkey** [comment]
Can't reproduce in latest build. Right now you can modify custom name as you want.

**Comment by tfiduccia** [comment]
@StrongMonkey I can change the custom name but I can't remove it.  Delete the text and save.

**Comment by StrongMonkey** [comment]
But when i type a empty space, it is actually sending a null name which worked
![screen shot 2018-01-19 at 10 03 39 am](https://user-images.githubusercontent.com/9203378/35162173-b5f81e48-fcff-11e7-8669-e901041244a0.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
