### ISSUE TITLE
Nodes are disconnecting in loop when I deploy OCI/RunC container using rancher cattle 

### ISSUE THREAD

**Issue by senpx** [rancher/rancher#10828]
When we tried to deploy OCI/RunC container using rancher cattle, Nodes are disconnecting and reconnecting from the rancher dashboard. ANd cant display that OCI/RUNC container in the rancher. Can anyone confirm whether it's supported or not?

**Comment by loganhz** [comment]
It's supported. If you use docker run to start a container on a host. In Rancher host page, you can see the container in Standalone Containers section of the hosts.

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
