### ISSUE TITLE
Kontainer-Engine Specific Update Operations

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#10829]
We need to create operations in kontainer-engine that are smaller and more focused than the existing "update" operation. Specifically these operations are:

* get/set Kubernetes version
* get/set cluster (*not* control plane) size

We would like these to be implemented as interfaces that a given driver (RKE, GKE, AKS, etc.) can implement.  This poses a problem with the RPC server, because it depends only on the "Driver" interface. We will need to add a capabilities API to the RPC server so it can query what operations a driver can execute, because not all drivers will support all the operations (maybe this will mean we can't have separate interfaces for the drivers?).

The get/set version operation will also pose a problem with the RKE driver, because there is not currently a 1 to 1 mapping of docker images and Kubernetes versions.  We will need to find some way to implement this mapping so the end-user can specify a Kubernetes version instead of a docker image.

**Comment by deniseschannon** [comment]
@vincent99 the backend is merged, needs UI work next.

**Comment by vincent99** [comment]
This works in theory since the last add-cluster redesign, you can edit the cluster options.  Probably more fields than you should be allowed to edit, depending on the provider and their rules...

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/3
Verified fixed
