### ISSUE TITLE
Clusters/Nodes in removing state are not showing up in UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10821]
**Rancher versions:** 2.0 master 1/10

**Steps to Reproduce:**
1.  Delete a cluster or a node

**Results:**  Cluster/Node immediately disappears from the UI, even thou it's hasn't been deleted.  It's still in a removing state and if it errors, I can't see that there was a problem.

**Comment by westlywright** [comment]
@tfiduccia can we test this again? delete states are showing up but want to make sure we're not missing anything?

**Comment by westlywright** [comment]
@tfiduccia nvm i was able to get it to happen. fixing.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
