### ISSUE TITLE
Can delete cloud cluster node through node UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10820]
**Rancher versions:** 2.0 master 1/10

**Steps to Reproduce:**
1.  Create a GKE cloud cluster
2.  Go to nodes screen and delete one of the active GKE nodes

**Results:**  Should not be able to delete the node.  Delete should be dimmed.  Need capability flag on the cluster for UI

**Comment by tfiduccia** [comment]
Once capabilities are added - check to make sure that GKE clusters are not showing up in Add Node/Cluster Options drop-down.

**Comment by StrongMonkey** [comment]
I can remove the `remove` link for gke nodes so it doesn't show remove. For adding Nodes page, Assume @vincent99 can fix this in UI? or do we need backend validation to reject machine that is created under a gke cluster?

**Comment by vincent99** [comment]
Yes, removing the `remove` link will make the delete option go away.

I'll hack up capabilities for now based on which provider config is populated, but ideally the server should have and enforce them.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
