### ISSUE TITLE
How to activate the debug on rancher-dns ?

### ISSUE THREAD

**Issue by Fridus** [rancher/rancher#10827]
**Rancher versions:**
rancher/server: 1.6.12

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.2.1
network-services: 0.2.7
kubernetes (if applicable): 1.7.7

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**My question**
How to activate the debug on rancher-dns ?

See https://github.com/rancher/rancher/issues/10390

**Comment by superseb** [comment]
Did you try https://github.com/rancher/rancher/issues/10390#issuecomment-346784457 ?

**Comment by Fridus** [comment]
@superseb Yes

**Comment by Fridus** [comment]
- `KUBERNETES -> Infrastructure Stacks
 -> network-services`
- line `meta-data` > button "Upgrade"
- check `Which Services` [x] dns
- Edit command of dns
