### ISSUE TITLE
Rancher agent upgrade can cause previous agent to go dead, blocking upgrade of agent

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10826]
**Rancher versions:**
rancher/server: 1.6.12
docker: 17.06
Somewhat related to: https://github.com/rancher/rancher/issues/9164 and https://github.com/moby/moby/issues/21083#issuecomment-239578836

I believe the rancher-agent-upgrade process doesnt wait long enough for the previous agent to exit. The agent upgrade then sends a sig-kill to the rancher agent process and then the agent process goes dead.

**Comment by sangeethah** [comment]
Upgraded rancher server v1.6.12 having 20 nodes to v1.6.15-rc6.
Rancher agent in all nodes got upgraded successfully with out any issues.
