### ISSUE TITLE
[2.0 Feature request] Catalog multi-tenant

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#10838]
**Rancher versions:**  2.0

Hi, 

Rancher 2.0 supports multiple environments on the same cluster, this is wonderful, but can catalogs set to be global or environment level so users can decide if catalogs can be access by anyone or within environment? Because private catalogs may contain sensitive configs. Thanks.

**Comment by vincent99** [comment]
Not currently but before a final 2.0 release, yes; this is already how catalogs work in 1.6.
