### ISSUE TITLE
hostname field is missing from nodes API

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10834]
**Rancher versions:** 2.0 master 1/11

**Steps to Reproduce:**
1.  Add a node
2.  Go to API

**Results:** hostname field is missing.  So it's not being displayed in Edit Node UI

**Comment by deniseschannon** [comment]
I think this is UI? It should pull from API for `requestedHostname` for the "edit node" page as we list the name of the node when listing the nodes.

**Comment by tfiduccia** [comment]
@deniseschannon - I asked Vincent and he said it was backend.

**Comment by vincent99** [comment]
`requestedHostname` the UI sets on create.  This is given to docker-machine.

A machine is created, and registers with some name that possibly relates to the name you asked for.  It should come back as `hostname` and update if the hostname is changed on the machine later.

The user can then override the displayed name in the UI by setting `name`, which should initially be null.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/16
Verified fixed
