### ISSUE TITLE
Don't round CPU on dashboard

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10830]
**Rancher versions:**  2.0 master 1/11

**Steps to Reproduce:**
1.  Create a cluster with 3 nodes
2.  Go to dashboard

**Results:**  My CPU is 64% and says 2 of 3 used.  Should not be 2, looks like we are rounding when we should just give percent.

**Comment by deniseschannon** [comment]
build 1/16 - With a cluster of 3 nodes, at 24%, it says 0.73 of 3 nodes.

**Comment by tfiduccia** [comment]
This is not fixed.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
