### ISSUE TITLE
In Add Project shouldn't see Cluster level Roles (no way to filter)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10837]
**Rancher versions:** 2.0 master 1/11

**Steps to Reproduce:**
1.  Go to Add Project
2.  Click on Add User
3.  Click on Role drop-down

**Results:**  All Roles are showing up.  Should not have Cluster level roles in projects?

**Comment by cjellick** [comment]
Backend done. UI needs to respect it. over to @vincent99

**Comment by deniseschannon** [comment]
This is now in the "custom" section modal for add projects. Is there anyway to remove "Cluster" related permissions on "Add Project"? 

@westlywright @vincent99

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
