### ISSUE TITLE
Some hosts are in Reconnected state after upgrade to rancher 1.6.14

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#10840]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.5
network-services: v0.9.5
scheduler: v0.8.3

**Docker version: 17.06.2-ce*

**Operating system and kernel: Ubuntu**

**Type/provider of hosts: AWS**

**Setup details: HA rancher**

**Environment Template: Cattle**

**Steps to Reproduce:**

Update Rancher server from 1.6.11 to 1.6.14

Lot's of my hosts are now in **Reconnected** state (they seem to be available).

I'd like to understand what is this state and why some of my hosts are in this state

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
