### ISSUE TITLE
How to use longhorn with rancher 2.0 ?

### ISSUE THREAD

**Issue by SacDin** [rancher/rancher#10857]
**Rancher versions:**
rancher/server: 2.0
rancher/agent: 2.0-alpha-4

I know that there are no PV solutions yet available for 2.0 but is it possible to run longhorn in current situation as storage providers ? Thanks.

**Comment by superseb** [comment]
This was announced yesterday, please check it out: https://rancher.com/project-longhorn-now-available-kubernetes/
