### ISSUE TITLE
rancher orchestration mode auto change

### ISSUE THREAD

**Issue by jinghuaz** [rancher/rancher#10859]
**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:rancher/healthcheck:v0.3.3
ipsec:rancher/net:v0.11.9
network-services:rancher/metadata:v0.9.4
scheduler:rancher/scheduler:v0.8.2
kubernetes (if applicable):

Docker version: (17.06)

Operating system and kernel: (centos7.3)

Type/provider of hosts: (physical)

Setup details:  HA rancher,external DB)

Environment Template: (Swarm)

BUG：
When I create the environment choose swarm orchestration mode,
Suddenly discovered after two weeks using orchestration became cattle？

Orchestration mode is not only created can be modified? Why suddenly change the layout mode, how can I change back now, in a hurry...
![image](https://user-images.githubusercontent.com/9525903/34925326-a60916a0-f9e3-11e7-9f19-5fa40cc9a58b.png)

**Comment by jinghuaz** [comment]
Hi guys, i have upgraded rancher server to V1.6.14 and all module upgraded latest. the quesition i will focus on it. thanks

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
