### ISSUE TITLE
Error messages not showing up in Add Cluster page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10855]
**Rancher versions:** 2.0 master 1/13

**Steps to Reproduce:**
1.  Create a cluster called "cluster1"
2.  Try to create another cluster call "cluster1"

**Results:**  The screen flashes.  There is actually an error that you can't have duplicate cluster names.  But it's not showing up in the UI.  None of the associated error messages are showing up.

**Comment by deniseschannon** [comment]
@loganhz once an error shows up, it doesnt disappear if i switch to another cloud provider.

**Comment by deniseschannon** [comment]
related: https://github.com/rancher/rancher/issues/10623#issuecomment-358191277

**Comment by loganhz** [comment]
@deniseschannon fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/17
