### ISSUE TITLE
Containers scheduled unbalanced

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#10852]
**Rancher versions:**
rancher: v1.6.12

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:v0.13.5, rancher/net:v0.13.5
network-services: rancher/dns:v0.15.3
scheduler: rancher/scheduler:v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
````
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
````
4.4.0-53-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
5 node cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I have a composition with one large container (6Gb data). The composition itself has 3 containers.
Depending on the run, Rancher schedules the containers:
- all one one host
- sometimes on two
- and seldomly on three.

I expect the scheluder to be more clever, i.e.always spread the containers over the 5 hosts. Nothing else (except the infra containers) are running.

**Results:**
Overloaded hosts in some runs.

**Comment by loganhz** [comment]
Please try https://github.com/rancher/rancher/issues/8080#issuecomment-302500050

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
