### ISSUE TITLE
GKE cluster name is not being passed to Google's k8s cluster.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10856]
**Rancher versions:** 2.0 master 1/13

**Steps to Reproduce:**
1.  Create a GKE cluster and give it a name
2. Go to Google's k8's cluster list

**Results:**  Cluster name is "cluster-<random>" instead of name I gave it.  This used to work.
![image](https://user-images.githubusercontent.com/11514927/34912556-996b3c5e-f8a1-11e7-8e66-2d498709bff2.png)
![image](https://user-images.githubusercontent.com/11514927/34912557-a2e0c132-f8a1-11e7-99f2-eb82e690850b.png)

**Comment by deniseschannon** [comment]
it worked for me with the latest build, but can you confirm as well @tfiduccia

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/16
Verified fixed.
