### ISSUE TITLE
RKE cluster gets stuck in updating after being active

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10864]
**Rancher versions:** 2.0 master 1/13

**Steps to Reproduce:**
1.  Create a RKE node and wait for it to be active.
2.  Go to Default
3.  Add a pod
4.  Go back to Cluster page  

**Results:**  Cluster now says updating and is stuck there.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/16
Still having this problem 
![image](https://user-images.githubusercontent.com/11514927/35018017-e92d29b8-fadc-11e7-83c9-a3ea9f4f8b33.png)

**Comment by sangeethah** [comment]
I see the same issue when testing with gke cluster where the cluster that was reported as being in "active" state is now stuck in "updating" state.

I had added another user as member to a cluster that was created as “admin” user. After this is when I noticed that the cluster is stuck in “Updating” state .For a while i was not able to log in to UI and got a 500 Internal server error ,but now i am to log in but status of cluster continues to be in “updating” state.


[4:23] 
 ```ime="2018-01-17T00:18:47Z" level=info msg="Cluster [cluster-kbk4h] condition status unknown"
time="2018-01-17T00:18:54Z" level=info msg="cluster [cluster-kbk4h] provisioning: Cluster sangeecluster is running"
time="2018-01-17T00:18:54Z" level=info msg="cluster [cluster-kbk4h] provisioning: Updating node number to 3"
time="2018-01-17T00:18:55Z" level=info msg="cluster [cluster-kbk4h] provisioning: reconciling cluster sangeecluster......"
time="2018-01-17T00:19:00Z" level=info msg="cluster [cluster-kbk4h] provisioning: Cluster sangeecluster is running"
time="2018-01-17T00:19:00Z" level=info msg="cluster [cluster-kbk4h] provisioning: Cluster sangeecluster is running"
time="2018-01-17T00:19:00Z" level=info msg="Provisioned cluster [cluster-kbk4h]"```

**Comment by alena1108** [comment]
The appliedSpec seems to be reset on any update coming through the UI. Just resetting the description on the cluster makes it happen. And as RKE update is called when spec != appliedSpec, appliedSpec being reset causes constant updates.

**Comment by deniseschannon** [comment]
Should be fixed in 1/18 build at 9pm, but need more testing

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed

**Comment by deniseschannon** [comment]
Tested with Rancher server - v2.0 - master 1/18 9:30pm build

This issue with node being stuck in "updating" state is not not seen in the following 2 cases:

when adding users to a cluster
When adding new node to an existing cluster
