### ISSUE TITLE
Lot of standalone containers in stopped state in containers view but not in hosts view

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#10866]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3-1
ipsec: v0.2.2
network-services: v0.2.8
scheduler: v0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
```
# docker info
Containers: 44
 Running: 35
 Paused: 0
 Stopped: 9
Images: 53
Server Version: 1.12.6
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-192-168-1-22
ID: QMA7:YHSV:KFXU:PKY6:NBSF:EQP2:QE6L:G7JR:VOMH:HOQH:OGBH:CBQ3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
and
```
# uname -r
4.4.0-109-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
In every environment we have a `conplicity`[0] stack that is launched once a day by Rancher's `container-crontab` stack. The Conplicity container connects to the docker socket and launches a `duplicity` container for each named volume and backs it up to an object storage. The process runs fine and conplicity ensures that every duplicity container launched is destroyed (which works fine because we don't have any `duplicity` container left in `docker ps -a`). The problem is that after a few days I can see a lot of `camptocamp/duplicity:latest` containers stopped in the containers view (but not in the hosts view as standalone containers) and it looks like it slows down a lot the webUI (I cleaned everything up last friday and the Web UI looked way faster after that, but the stopped containers came back this morning...)

![containers view](https://user-images.githubusercontent.com/2950673/34932385-ee05f13c-f9d2-11e7-90d1-311b413db2e0.png)
![hosts view](https://user-images.githubusercontent.com/2950673/34932386-ee1e881e-f9d2-11e7-8fa1-2d6b53dcc4f0.png)

[0] https://github.com/camptocamp/camptocamp-rancher-catalog/tree/master/templates/conplicity/45
**Results:**

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
