### ISSUE TITLE
Nodes with Upper case or special characters causing cluster to fail to provision

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10862]
**Rancher versions:** 2.0 master 1/13

**Steps to Reproduce:**
1.  Create a node with upper case letter through RKE page or through Node page (associate to cluster)

**Results:**  The cluster fails to provision cause it doesn't allow character that aren't compliant with DNS labels (Kubernetes requirement).  We need to warn user and not move off page.

**Comment by deniseschannon** [comment]
duplicate/same as https://github.com/rancher/rancher/issues/10885

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Added to API
