### ISSUE TITLE
Metadata using 100% CPU when new rancher hosts are added

### ISSUE THREAD

**Issue by adenot** [rancher/rancher#10860]
**Rancher versions:**
rancher/server: 1.6.13
rancher/agent: 1.2.8

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: holder
network-services: metadata: v0.8.5, network-manager: v0.7.19
scheduler: v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 14
 Running: 10
 Paused: 0
 Stopped: 4
Images: 12
Server Version: 17.06.2-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 3.539GB
 Data Space Total: 23.33GB
 Data Space Available: 19.79GB
 Metadata Space Used: 2.458MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 22.71MB
 Thin Pool Minimum Free Space: 2.333GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.70-25.242.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.672GiB
Name: ip-172-18-21-90
ID: 2TKP:DNS7:GLJD:32OP:BBJP:IFKU:PH6S:QUQZ:DLFL:34JB:ORZP:VZ5Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```
```
4.9.70-25.242.amzn1.x86_64
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Host is added to rancher

**Results:**
CPU consumption on all rancher hosts went up to 100% on 1 CPU nodes and 50% on 2 CPU nodes. That was caused by the metadata container consuming 100% of one cpu.

After a while, once containers are up, CPU utilisation on all hosts went down to 20% (normal).

Looks like everytime an infrastructure service container is added or removed, metadata starts consuming 100% cpu on all hosts of the cluster. 

The problem is triggered on 2 occasions: 
- A new rancher host is added by autoscaling, causing 100% CPU on all hosts, triggering multiple autoscaling on other hosts, repeating until all ASGs reach max capacity.
- A new rancher host is added and has an issue (ex. out of memory) which causes infrastructure containers to restart, causing all hosts go 100% CPU from the metadata container.

The issue seems to be related to #9957 but we already tried adding CPU shares and interval=5000 to metadata service with no luck.

**Comment by dstokes** [comment]
seeing the same issue on Rancher v1.6.14

**Comment by moshe0076** [comment]
For 1.6.14 I see this:

# pidstat 1 | grep rancher-metadat
Average:      UID       PID    %usr %system  %guest    %CPU   CPU  Command
09:28:29 AM     0     12539   41.75    0.00    0.00   41.75     1  rancher-metadat
09:28:30 AM     0     12539   42.00    3.00    0.00   45.00     1  rancher-metadat
09:28:31 AM     0     12539   22.00    0.00    0.00   22.00     0  rancher-metadat
09:28:32 AM     0     12539   13.00    0.00    0.00   13.00     1  rancher-metadat
09:28:33 AM     0     12539   17.00    2.00    0.00   19.00     0  rancher-metadat
09:28:34 AM     0     12539   36.00    0.00    0.00   36.00     1  rancher-metadat
09:28:35 AM     0     12539   40.00    2.00    0.00   42.00     0  rancher-metadat
09:28:36 AM     0     12539   36.00    2.00    0.00   38.00     0  rancher-metadat
09:28:37 AM     0     12539   12.00    0.00    0.00   12.00     0  rancher-metadat
09:28:40 AM     0     12539    1.00    0.00    0.00    1.00     1  rancher-metadat
09:28:41 AM     0     12539    3.00    0.00    0.00    3.00     1  rancher-metadat
09:28:42 AM     0     12539   12.00    0.00    0.00   12.00     0  rancher-metadat
09:28:43 AM     0     12539   49.00    2.00    0.00   51.00     0  rancher-metadat
09:28:44 AM     0     12539   42.00    0.00    0.00   42.00     0  rancher-metadat
09:28:45 AM     0     12539   45.00    2.00    0.00   47.00     1  rancher-metadat
09:28:46 AM     0     12539    4.00    0.00    0.00    4.00     0  rancher-metadat
09:28:47 AM     0     12539    1.00    0.00    0.00    1.00     1  rancher-metadat
09:28:51 AM     0     12539    4.00    0.00    0.00    4.00     1  rancher-metadat
09:28:57 AM     0     12539    8.00    0.00    0.00    8.00     1  rancher-metadat
09:28:58 AM     0     12539   48.00    1.00    0.00   49.00     1  rancher-metadat
09:28:59 AM     0     12539   43.00    1.00    0.00   44.00     1  rancher-metadat
09:29:00 AM     0     12539   42.00    1.00    0.00   43.00     1  rancher-metadat
09:29:01 AM     0     12539   17.00    1.00    0.00   18.00     0  rancher-metadat
09:29:03 AM     0     12539    4.00    0.00    0.00    4.00     0  rancher-metadat
09:29:12 AM     0     12539    9.00    1.00    0.00   10.00     1  rancher-metadat
09:29:13 AM     0     12539   52.00    2.00    0.00   54.00     0  rancher-metadat
09:29:14 AM     0     12539   38.00    4.00    0.00   42.00     0  rancher-metadat
09:29:15 AM     0     12539   45.00    2.00    0.00   47.00     1  rancher-metadat
09:29:16 AM     0     12539   42.00    2.00    0.00   44.00     0  rancher-metadat
09:29:17 AM     0     12539   13.00    0.00    0.00   13.00     1  rancher-metadat
09:29:18 AM     0     12539    4.00    1.00    0.00    5.00     1  rancher-metadat
09:29:23 AM     0     12539    4.00    0.00    0.00    4.00     0  rancher-metadat
09:29:27 AM     0     12539   13.00    0.00    0.00   13.00     0  rancher-metadat
09:29:28 AM     0     12539   43.00    1.00    0.00   44.00     1  rancher-metadat
09:29:29 AM     0     12539   52.00    2.00    0.00   54.00     1  rancher-metadat
09:29:30 AM     0     12539   30.00    1.00    0.00   31.00     1  rancher-metadat
09:29:31 AM     0     12539   42.00    0.00    0.00   42.00     1  rancher-metadat
09:29:33 AM     0     12539    2.00    0.00    0.00    2.00     1  rancher-metadat
09:29:34 AM     0     12539    1.00    1.00    0.00    2.00     1  rancher-metadat
09:29:37 AM     0     12539   20.00    0.00    0.00   20.00     1  rancher-metadat
09:29:38 AM     0     12539   32.00    3.00    0.00   35.00     1  rancher-metadat
09:29:39 AM     0     12539   29.00    2.00    0.00   31.00     1  rancher-metadat
09:29:40 AM     0     12539   38.00    0.00    0.00   38.00     1  rancher-metadat
09:29:41 AM     0     12539   39.00    3.00    0.00   42.00     1  rancher-metadat
09:29:44 AM     0     12539   39.00    1.00    0.00   40.00     0  rancher-metadat
09:29:45 AM     0     12539   42.00    3.00    0.00   45.00     1  rancher-metadat
09:29:46 AM     0     12539   43.00    1.00    0.00   44.00     0  rancher-metadat
09:29:47 AM     0     12539   36.00    1.00    0.00   37.00     1  rancher-metadat
09:29:49 AM     0     12539    1.00    0.00    0.00    1.00     0  rancher-metadat
09:29:50 AM     0     12539    4.00    0.00    0.00    4.00     0  rancher-metadat
09:29:51 AM     0     12539    1.00    0.00    0.00    1.00     0  rancher-metadat
09:29:54 AM     0     12539    2.00    0.00    0.00    2.00     0  rancher-metadat
09:29:58 AM     0     12539   51.00    3.00    0.00   54.00     1  rancher-metadat
09:29:59 AM     0     12539   44.00    1.00    0.00   45.00     0  rancher-metadat
09:30:00 AM     0     12539   38.00    3.00    0.00   41.00     1  rancher-metadat
09:30:01 AM     0     12539   16.00    0.00    0.00   16.00     0  rancher-metadat
09:30:02 AM     0     12539    0.00    1.00    0.00    1.00     0  rancher-metadat
09:30:03 AM     0     12539    1.00    0.00    0.00    1.00     0  rancher-metadat
09:30:04 AM     0     12539    1.00    0.00    0.00    1.00     0  rancher-metadat
09:30:05 AM     0     12539    1.00    1.00    0.00    2.00     0  rancher-metadat
09:30:12 AM     0     12539    1.00    0.00    0.00    1.00     0  rancher-metadat
09:30:13 AM     0     12539   52.00    2.00    0.00   54.00     1  rancher-metadat
09:30:14 AM     0     12539   38.00    2.00    0.00   40.00     1  rancher-metadat
09:30:15 AM     0     12539   40.00    2.00    0.00   42.00     1  rancher-metadat
09:30:16 AM     0     12539   45.00    0.00    0.00   45.00     1  rancher-metadat
09:30:17 AM     0     12539    9.00    0.00    0.00    9.00     1  rancher-metadat
09:30:18 AM     0     12539    4.00    0.00    0.00    4.00     1  rancher-metadat

**Comment by brandonpalmer** [comment]
Also seeing the same issues -- causing a lot of load in our environment.

**Comment by eliaoggian** [comment]
Same here with 1.6.17: 
DEV [root@svgecod027 ~]$  pidstat 1 | grep rancher-metadat
03:18:25 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:18:32 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:18:40 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:18:42 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:18:45 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:18:52 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:18:55 PM     0     24363   10.00    1.00    0.00   11.00     1  rancher-metadat
03:18:57 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:19:02 PM     0     24363    1.00    1.00    0.00    2.00     1  rancher-metadat
03:19:07 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:19:17 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:19:25 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:19:32 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:19:42 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:19:43 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:19:56 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:20:02 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:20:04 PM     0     24363    2.00    0.00    0.00    2.00     1  rancher-metadat
03:20:08 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:20:10 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:20:22 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:20:27 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:20:32 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:20:42 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:20:47 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:20:57 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:21:02 PM     0     24363    2.00    0.00    0.00    2.00     1  rancher-metadat
03:21:07 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:21:16 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:21:18 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:21:24 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:21:32 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:21:42 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:21:46 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:21:55 PM     0     24363   10.00    2.00    0.00   12.00     1  rancher-metadat
03:21:59 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:22:04 PM     0     24363    2.00    0.00    0.00    2.00     1  rancher-metadat
03:22:05 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:22:07 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:22:18 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:22:26 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:22:32 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:22:38 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:22:47 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:22:51 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:22:56 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:23:06 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:23:14 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:23:19 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:23:31 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:23:37 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:23:43 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:23:47 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:23:48 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:23:52 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:23:58 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:24:04 PM     0     24363    2.00    0.00    0.00    2.00     1  rancher-metadat
03:24:06 PM     0     24363   51.00    5.00    0.00   56.00     1  rancher-metadat
03:24:07 PM     0     24363   48.00    1.00    0.00   49.00     1  rancher-metadat
03:24:08 PM     0     24363   43.00    2.00    0.00   45.00     1  rancher-metadat
03:24:09 PM     0     24363   50.00    3.00    0.00   53.00     1  rancher-metadat
03:24:10 PM     0     24363   48.00    2.00    0.00   50.00     1  rancher-metadat
03:24:11 PM     0     24363   44.00    3.00    0.00   47.00     1  rancher-metadat
03:24:12 PM     0     24363   47.00    4.00    0.00   51.00     1  rancher-metadat
03:24:13 PM     0     24363   44.00    4.00    0.00   48.00     1  rancher-metadat
03:24:14 PM     0     24363   49.00    2.00    0.00   51.00     1  rancher-metadat
03:24:15 PM     0     24363   41.00    4.00    0.00   45.00     1  rancher-metadat
03:24:16 PM     0     24363   50.00    3.00    0.00   53.00     1  rancher-metadat
03:24:17 PM     0     24363   44.00    3.00    0.00   47.00     1  rancher-metadat
03:24:18 PM     0     24363   46.00    5.00    0.00   51.00     1  rancher-metadat
03:24:19 PM     0     24363   44.00    5.00    0.00   49.00     1  rancher-metadat
03:24:20 PM     0     24363   49.00    2.00    0.00   51.00     1  rancher-metadat
03:24:21 PM     0     24363   41.00    3.00    0.00   44.00     1  rancher-metadat
03:24:27 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:24:30 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:24:31 PM     0     24363   48.00    2.00    0.00   50.00     1  rancher-metadat
03:24:32 PM     0     24363   45.00    5.00    0.00   50.00     1  rancher-metadat
03:24:33 PM     0     24363   45.00    3.00    0.00   48.00     1  rancher-metadat
03:24:34 PM     0     24363   46.00    4.00    0.00   50.00     1  rancher-metadat
03:24:35 PM     0     24363   46.00    5.00    0.00   51.00     1  rancher-metadat
03:24:36 PM     0     24363   47.00    3.00    0.00   50.00     1  rancher-metadat
03:24:37 PM     0     24363   39.00    3.00    0.00   42.00     1  rancher-metadat
03:24:43 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:24:46 PM     0     24363    7.00    2.00    0.00    9.00     1  rancher-metadat
03:24:47 PM     0     24363   54.00    5.00    0.00   59.00     1  rancher-metadat
03:24:48 PM     0     24363   47.00    3.00    0.00   50.00     1  rancher-metadat
03:24:49 PM     0     24363   42.00    4.00    0.00   46.00     1  rancher-metadat
03:24:50 PM     0     24363   45.00    4.00    0.00   49.00     1  rancher-metadat
03:24:51 PM     0     24363   46.00    4.00    0.00   50.00     1  rancher-metadat
03:24:52 PM     0     24363   46.00    4.00    0.00   50.00     1  rancher-metadat
03:24:53 PM     0     24363   47.00    4.00    0.00   51.00     1  rancher-metadat
03:24:54 PM     0     24363   43.00    2.00    0.00   45.00     1  rancher-metadat
03:24:55 PM     0     24363   47.00    2.00    0.00   49.00     1  rancher-metadat
03:24:56 PM     0     24363   44.00    4.00    0.00   48.00     1  rancher-metadat
03:24:57 PM     0     24363   47.00    4.00    0.00   51.00     1  rancher-metadat
03:24:58 PM     0     24363   45.00    3.00    0.00   48.00     1  rancher-metadat
03:24:59 PM     0     24363   46.00    5.00    0.00   51.00     1  rancher-metadat
03:25:00 PM     0     24363   46.00    6.00    0.00   52.00     1  rancher-metadat
03:25:01 PM     0     24363   19.00    1.00    0.00   20.00     1  rancher-metadat
03:25:02 PM     0     24363    1.00    1.00    0.00    2.00     1  rancher-metadat
03:25:06 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:25:07 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:25:17 PM     0     24363    2.00    0.00    0.00    2.00     1  rancher-metadat
03:25:24 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:25:30 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:25:32 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:25:38 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:25:47 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:25:52 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:26:03 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:26:04 PM     0     24363    3.00    0.00    0.00    3.00     1  rancher-metadat
03:26:06 PM     0     24363    2.00    0.00    0.00    2.00     1  rancher-metadat
03:26:08 PM     0     24363    0.00    1.00    0.00    1.00     1  rancher-metadat
03:26:17 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat
03:26:26 PM     0     24363    1.00    0.00    0.00    1.00     1  rancher-metadat

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
