### ISSUE TITLE
Rancher Agent does not seem to work on Raspberry PI.  Is there a special agent image that should be used for Raspberry PIs?

### ISSUE THREAD

**Issue by zvercodebender** [rancher/rancher#10868]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.11.9
network-services: v0.9.4
scheduler: v0.7.8
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 17.09.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.59-v7+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 875.8MiB
Name: pi3
ID: OLYG:7BOD:F3F5:ZZOW:RXFE:7IFB:WRAT:IIPQ:YV5C:3TR7:OLS7:7HAD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.1.11:5000
 bilbo.inhouse-broker.org:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.59-v7+
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal *Raspberry PI 3

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher admin server is running on an Intel Linux server (4.13.5-100.fc25.x86_64).  I am trying to add a new cluster running on a couple of raspberry PI 3s.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Install docker from the docker.com site (`curl -fsSL get.docker.com -o get-docker.sh`)
2. Add host using the command from the docker admin console see:
`sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://bilbo.inhouse-broker.org:8080/v1/scripts/5863D0B0E29D46A636B2:1514678400000:fxaPfthM2cNkcOic3ORMKeQhg`

**Results:**

`root@pi3:~# sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://bilbo.inhouse-broker.org:8080/v1/scripts/5863D0B0E29D46A636B2:1514678400000:fxaPfthM2cNkcOic3ORMKeQhg
standard_init_linux.go:185: exec user process caused "exec format error"`

**Comment by frankh** [comment]
Raspberry pi's use arm processors and rancher doesn't currently run on arm processors

See this issue https://github.com/rancher/rancher/issues/4703

**Comment by jmreicha** [comment]
Working on getting an ARM based cluster up and running, would really like to see support for ARM.

**Comment by ags131** [comment]
I have managed this with Rancher 2.0, there is a small issue where you need to use the `View in API` option to change a cluster setting in Rancher in order to use a custom agent image. https://gist.github.com/ags131/7bdde11c932ef7a54f44c6decbfd88b8

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/2101
