### ISSUE TITLE
Add node crashes rancher when selecting a custom driver

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10873]
**Rancher versions:** 2.0 master 1/15

**Steps to Reproduce:**
1.  Add a node driver (I added vultr)
2.  Go to API and make sure it's active (if not activate it)
3.  Go to Add Node and select Docker Machine (node driver will show in Driver list)
4.  Try to get out of this page 

**Results:**  Can't get out of this page, basically rancher is hung and have to refresh to get it work again.  Couple of errors in console:
component.js:26 Uncaught TypeError: Cannot read property 'filterBy' of undefined
util.js:453 Uncaught Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction

**Comment by loganhz** [comment]
Hi @tfiduccia, I can not recreate this issue.  Can you try again, please? thanks

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
