### ISSUE TITLE
Adding machine driver from github isn't grabbing the name properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10874]
**Rancher versions:** 2.0 master 1/15

**Steps to Reproduce:**
1.  Add the vultr or ubiquity driver from github (URL for vultr - https://github.com/janeczku/docker-machine-vultr/releases/download/v1.4.0/docker-machine-driver-vultr-Linux-armhf)

**Results:**  name of machine is machinedriver-<random> instead of vultr (which we used to pull).  And the node driver list page UI is showing "Generic".  The Add node docker machine drop-down is showing them as machinedriver-<random>, so I have no idea which driver I actually need to select.

**Comment by StrongMonkey** [comment]
same as https://github.com/rancher/rancher/issues/11039

**Comment by deniseschannon** [comment]
Closing in favor of #11039
