### ISSUE TITLE
When I click Add Node from Add Cluster there is text at top left of Template & Add Node modals

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10875]
**Rancher versions:** 2.0 master 1/15

**Steps to Reproduce:**
1.  Go to Add Cluster
2.  Select RKE
3.  Click on Add Node
4.  Click on Configure

**Results:**  On the first page of Add Node machineTemplate text appears on upper left.  On the Add Node page itself, add is showing up.
![image](https://user-images.githubusercontent.com/11514927/34964852-f66c995e-fa0c-11e7-9f73-5d096584f2bb.png)
![image](https://user-images.githubusercontent.com/11514927/34964865-0d5cac58-fa0d-11e7-9d30-65566697d557.png)

**Comment by deniseschannon** [comment]
@tfiduccia I can't reproduce or find this text. Can you re-check?

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/17
Verified fixed
