### ISSUE TITLE
Amazon EC2 driver not sending Security Group

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10876]
**Rancher versions:** 2.0 master 1/15

**Steps to Reproduce:**
1.  Go to Add Cluster
2.  Select Create RKE cluster
3.  Fill out Name
4.  Click on Add a New Node
5.  Click on Configure
6.  Select Amazon EC2 template
7.  Fill out all info and select All-Open for the Security Group (I set scale to 3)
8.  Finish Cluster info and Create

**Results:**  The Security Group in EC2 says Docker-machine instead of All-open.  This prevents the cluster from finishing provisioning.
![image](https://user-images.githubusercontent.com/11514927/34966597-3239ce7c-fa1a-11e7-8688-ed07b2bf57fc.png)

**Comment by StrongMonkey** [comment]
should be fixed in latest build.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/16
Verified fixed
