### ISSUE TITLE
Scheduler never runs on specific server only

### ISSUE THREAD

**Issue by phackwer** [rancher/rancher#10881]
If someone can answer me this, will be enough: how to manually add the scheduler that is not being added by the agent?

**Rancher versions:**
rancher/server: 1.6
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Just Docker added

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
None, just adding hosts

**Steps to Reproduce:**
I really don't know how to reproduce it, as it's constant only on this VM.
I've have setup both VMs in Azure at exactly same time (2 terminals side by side), they have both DS2_V3 size, and both were created using Ubuntu 16.04.

But for some crazy reason, only on this server the scheduler never runs.

The command I ran was:

 sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 http://SERVEROMMITTED:8080/v1/scripts/Q
HASHOMMITED:THATPARTTOO

**Results:
Scheduler never runs on specific server.

![image](https://user-images.githubusercontent.com/4871786/34991451-83f03cc2-fac1-11e7-8ff0-01f21fab2fe2.png)

**Comment by superseb** [comment]
Not completely sure if I follow, scheduler is a service with one container, which runs on a host in the cluster. If you delete the container itself, it gets rescheduled to the same or another host. Do you want to run it `avatar-baker` instead of `api-qa`?

**Comment by phackwer** [comment]
My bad, I saw I can add instances to the stack quite simple.
