### ISSUE TITLE
GKE clusters should not be in Add Node Cluster drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10889]
**Rancher versions:** 2.0 master 1/16

**Steps to Reproduce:**
1.  Create a GKE cluster (Wait for it to be active)
2.  Go to Node page and click Add node
3.  Click on Cluster drop-down in Cluster options section

**Results:**  GKE clusters show up in list
![image](https://user-images.githubusercontent.com/11514927/35018994-a5f5e234-fae1-11e7-9c00-e009fbb29680.png)

**Comment by alena1108** [comment]
@vincent99 is there any attribute that can be set so the node is not picked by the UI? Or can UI already use nodeConfig https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/machine_types.go#L69 for filtering

**Comment by deniseschannon** [comment]
I don't see any GKE clusters when I tested 1/22 build. @tfiduccia ?

**Comment by tfiduccia** [comment]
Version -2.0 master 1/23
Verified fixed - this was fixed a while ago.
