### ISSUE TITLE
Can't use Packet to create nodes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10888]
**Rancher versions:** 2.0 master 1/16

**Steps to Reproduce:**
1.  Add cluster
2.  Add Nodes
3.  Try to add packet nodes

**Results:**  When I tried to authenticate, it says Bad Gateway: undefined
![image](https://user-images.githubusercontent.com/11514927/35016477-f4226b8c-fad5-11e7-962a-3c1c933076f5.png)

**Comment by tfiduccia** [comment]
Packet still not working - new error
![image](https://user-images.githubusercontent.com/11514927/36623402-a8ba06b4-18c1-11e8-8aa3-21178ac6cc0e.png)

**Comment by vincent99** [comment]
The version of the packet driver bundled is old and only supports ubuntu 14.04.  https://github.com/rancher/rancher/pull/11612

**Comment by tfiduccia** [comment]
2.0 master 2/26
Still doesn't create - No VM in Packet.net and in the ui it's waiting...
![image](https://user-images.githubusercontent.com/11514927/36700355-a6e6bdf8-1b0c-11e8-888c-d34e9789ce63.png)

**Comment by aiwantaozi** [comment]
The latest relase have this issue
https://github.com/packethost/docker-machine-driver-packet/issues/22

I use the old release, and it could work. https://github.com/packethost/docker-machine-driver-packet/releases/download/v0.1.4/docker-machine-driver-packet_linux-amd64.zip

**Comment by tfiduccia** [comment]
Version - 2.0 master 6/26
Verified fixed
