### ISSUE TITLE
Going into cluster while it's provisioning gives me a 404 error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10884]
**Rancher versions:** 2.0 master 1/16

**Steps to Reproduce:**
1.  Create a GKE cluster
2.  While it's provisioning go to the menu and select the cluster

**Results:** 404 error
![image](https://user-images.githubusercontent.com/11514927/35004197-683beda6-faac-11e7-87df-12b9167c2283.png)

**Comment by deniseschannon** [comment]
Related: https://github.com/rancher/rancher/issues/10762

**Comment by loganhz** [comment]
UI needs to load `/v3/clusters/${clusterId}/schema` for checking RBAC. But backend returns `404`. I think we need to fix the related backend issue first.

**Comment by sangeethah** [comment]
I see a similar issue in the following use case.

Log in admin user and create a cluster.

While cluster is still in provisioning state , log out.

Try to log in again.
User is not allowed to log in and is presented with the following page:

/Users/sangeethahariharan1/Desktop/Screen Shot 2018-01-18 at 10.05.05 PM.png

**Comment by vincent99** [comment]
There's still some edge cases here like you're in a cluster that then becomes not-active, but you can no longer casually/accidentally hit this.  Login goes to the clusters page and does not try to select a project, and projects for not-active clusters are hidden in the dropdown.

**Comment by tfiduccia** [comment]
Version -2.0 master 1/20
Verified fixed
