### ISSUE TITLE
Active Dirctory Authentication always required domain\username

### ISSUE THREAD

**Issue by calloes** [rancher/rancher#10893]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent:1.2.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 1.1.3

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 Node Cluster withe External MySQL Database.

Would like to utilise the Default Login Domain option in the Configure Active Directory Server page but it does not work always comes back with error.

Error in ldap bind for service account: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839

Using LDAP port 389, 

Works fine if Default Login Domain blank and domain\user is used.

**Comment by superseb** [comment]
Can you share what Windows server/Active Directory you are using here?

**Comment by calloes** [comment]
Windows 2012 R2 Servers running behind an F5 TCP Loadbalancer.

**Comment by superseb** [comment]
Can you configure debug logging on the auth service, try to configure it and share the logs from the attempt?

Configure debug logging (no restart required)
```
use cattle; insert into setting (name,value) values ('auth.service.log.level', 'DEBUG');
```

Should show in `docker logs rancher-server-container-name-or-id`

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
