### ISSUE TITLE
When adding nodes to existing cluster using node template from DO, it shows generic machine driver

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10899]
1/16 8pm master

1. Create a RKE cluster and create DO node template
2. After cluster is active, add another node using same DO node template

Result: 

Page shows Generic Docker Machine Driver image and text 
Driver is blank on page

<img width="681" alt="screen shot 2018-01-16 at 8 39 22 pm" src="https://user-images.githubusercontent.com/11410997/35026018-6c60bcb2-fafd-11e7-9b7f-ce1d0e23f6f3.png">

Expected Result:

Page show Digital Ocean image and text
Driver shows Digital Ocean

**Comment by tfiduccia** [comment]
Note - This is the Add Node from the Cluster level.  The global Level add node is showing the correct image.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed
