### ISSUE TITLE
RKE: No error message if I try to create without adding any nodes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10897]
Version: 1/16 8pm master

1. Go to add RKE cluster
2. Click on Create (with no nodes added)

Results: Nothing
Expected Result: Error indicating I need to add nodes

**Comment by tfiduccia** [comment]
This is now stuck in Saving and throwing an error in console - controller.js:148 Uncaught TypeError: Cannot read property 'findTranslationByKey' of undefined.  

Also please remove this "fix" as you should be able to create cluster with no nodes.

**Comment by deniseschannon** [comment]
@ibuildthecloud @vincent99 do we really want to be able to add RKE clusters with no nodes to start? what's the point of this screen on the RKE launch page then if we don't validate against it?

<img width="1166" alt="screen shot 2018-01-18 at 9 48 47 pm" src="https://user-images.githubusercontent.com/11410997/35136614-67af332c-fc99-11e7-97f2-cbc5f5475067.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/19
Verified fixed
