### ISSUE TITLE
ipaddress/cpu/RAM/pods info is not present for host in etcd plane.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10894]
Rancher versions: rancher/cattle:master  built on 01/16 at ~ 3:30 pm 

Steps to reproduce the problem:
create a RKE cluster with 3 nodes with node1 in etcd plane, node2 in control plane and node3 in worker plane.
Cluster gets created successfully with 3 nodes.
node1 deployed as etcd does not have information about ipaddress/cpu/RAM/pods.
All other nodes have these info.

**Comment by sangeethah** [comment]
Tested with Rancher versions: rancher/cattle:master built on 01/20 morning.

Nodes with only etcd role , still does not show the status properly:

This is what i see for cpu/RAM/pods.
```
NaN/1 | NaN/892 MiB | NaN/110
```

**Comment by deniseschannon** [comment]
should be in next build 1/20 after 4pm

**Comment by sangeethah** [comment]
Tested with Rancher versions: rancher/cattle:master built on 01/20 at ~ 4:00 pm

create a RKE cluster with 3 nodes with node1 in etcd plane, node2 in control plane and node3 in worker plane.
etcd node displays all stats as expected.
