### ISSUE TITLE
RKE: Checkbox for being able to select all roles for a node

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10898]
1/16 maser at 8pm

It'd be nice to have a checkbox that would select all roles when adding a node for RKE. 

<img width="1212" alt="screen shot 2018-01-16 at 8 29 00 pm" src="https://user-images.githubusercontent.com/11410997/35025778-4173aa24-fafc-11e7-940a-f540c881bc7b.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed
