### ISSUE TITLE
When adding nodes using node template to existing cluster,  cluster shows ID instead of cluster name

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10900]
1/16 8pm master

1. Create a RKE cluster and create node template
2. After cluster is active, add another node in cluster using node template

Result: 

Cluster ID is displayed instead of Cluster name

<img width="654" alt="screen shot 2018-01-16 at 8 43 17 pm" src="https://user-images.githubusercontent.com/11410997/35026160-26e1f3d0-fafe-11e7-9311-3c7bca6c78ef.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed
