### ISSUE TITLE
cluster state stuck in "Updating" even after a worker node was added successfully to the RKE cluster. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10901]
Rancher versions: rancher/cattle:master built on 01/16 at ~ 3:30 pm
Steps to reproduce the problem:
Create RKE cluster with 3 nodes.
Wait for cluster state to become "Active".

Add another worker node to this cluster using "Add Node" option.

Even after the host is added successfully to the cluster,  cluster state is stuck in "Updating" forever. Transition message - "Finished building Kubernetes cluster successfully"  indicates success.

**Comment by alena1108** [comment]
Closing as a duplicate of https://github.com/rancher/rancher/issues/10864
