### ISSUE TITLE
When adding nodes (not using node template) through add node in the existing cluster, no cluster shows up or is available to be selected

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10905]
1/16 8pm master

1. Create a RKE cluster 
2. After cluster is active, click on cluster name. 
3. Go to add another node in cluster but do not select an existing node template

Result:

No cluster is selected and no options to select one.

<img width="623" alt="screen shot 2018-01-16 at 9 27 16 pm" src="https://user-images.githubusercontent.com/11410997/35027173-12ae9c00-fb04-11e7-9253-8ced17372f0f.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/19
Verified fixed
