### ISSUE TITLE
crontab:v0.3.0 is having issues with sidekicks

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10908]
crontab:v0.3.0

The return value of getRancherServiceNameFromLabels for a sidekick is something like "mainname/sidekickname" but we only need "sidekickname" for this to work.

**Comment by soumyalj** [comment]
Tested with Cron v0.5.0 . Created a cron job for a service with sidekicks using the following labels:
```
cron.schedule=0 */1 * * * *
cron.action=start
```
All the containers including sidekicks restarted every minute
