### ISSUE TITLE
"Edit Project" page does not list users that were added to it and project owner is listed incorrectly.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10904]
Rancher versions: rancher/cattle:master built on 01/16 at ~ 3:30 pm

Steps to reproduce the problem:
Log in as "admin"
Create a cluster.
Create a project -P1.
Edit project and add a user (say user1) to this project (with any role).

Click on "Edit Project" again , to view all the users added.
List of users that were added in the previous edit project step is not listed.

Log in as "user1"
Navigate to project P1 and click on "Edit project".
Notice that "user1" is listed as the Project owner.

When logged in as "admin", "Edit project" for P1 lists "admin" as Project owner.

**Comment by sangeethah** [comment]
The same behavior is also seen with clusters.

**Comment by cjellick** [comment]
Project ID is screwed up in the API  it shows "<project id>" instaed of "<cluster id>:<proejct id>" even though the underlying CRD has "<cluster id>:<proejct id>".
Darren's bug, but leaving myself assigned for tracking purposes

**Comment by cjellick** [comment]
Probably maybe fixed

**Comment by sangeethah** [comment]
With rancher server master built at 9:30 pm on Jan18 , this issue is not seen anymore.

Able to see all the users added to the cluster/project . Cluster/Project owner is listed incorrectly which is tracked in - https://github.com/rancher/rancher/issues/10983
