### ISSUE TITLE
Include roles in node list view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10907]
Rancher versions: rancher/cattle:master built on 01/16 at ~ 3:30 pm
Steps to reproduce the problem:
Create RKE cluster with 3 nodes.
Wait for cluster state to become "Active".
Got to "Nodes" tab.
Nodes listed in this view does not show role.

It would be good to include the roles of the nodes.

**Comment by tfiduccia** [comment]
This has been added
![image](https://user-images.githubusercontent.com/11514927/35064918-d08cd816-fb88-11e7-81b8-1c950e531483.png).
