### ISSUE TITLE
User created with "Standard User" permission is not able to login.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10914]
Rancher versions: rancher/cattle:master built on 01/16 at ~ 3:30 pm

Steps to reproduce the problem:
As admin user , Create a user with "Standard User" permission.
Log in as this user using valid username and password.
User is presented with "Invalid Credential" error.

login api returns - "401 Unauthorized"

**Comment by tfiduccia** [comment]
This is fixed through the UI.  Can you do a pull and retest.

**Comment by sangeethah** [comment]
This issue does not repro when testing with  rancher/cattle:master built on 01/17 at ~ 1:00 pm.
