### ISSUE TITLE
GKE stats and nodes don't show up in global until you go to the cluster level project page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10911]
**Rancher versions:** 2.0 master 1/17

**Steps to Reproduce:**
1.  Create a GKE cluster
2. Wait for it to be active
3.  Go to the global Node page

**Results:**  Notice that the nodes aren't showing up and the stats on the Global cluster page don't show up.  IF you go to cluster level project/node page then back the nodes & stats will show up.

**Comment by alena1108** [comment]
@tfiduccia I can't reproduce the issue on the latest master, could you recheck?

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/3
This was fixed a while ago.  Verified fixed
