### ISSUE TITLE
Node added through global Add Node page does not have roles array

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10919]
**Rancher versions:** 2.0 master 1/17

**Steps to Reproduce:**
1.  Create a RKE cluster
2.  Go to Nodes page and use template to create a worker node

**Results:**  The added node does not have the roles array so the Roles section in UI is not filling out.
![image](https://user-images.githubusercontent.com/11514927/35065482-a01648fa-fb8a-11e7-9bbb-cae0c72032e8.png)

**Comment by StrongMonkey** [comment]
@tfiduccia you should be able to specify role in here?
![screen shot 2018-01-18 at 5 55 41 pm](https://user-images.githubusercontent.com/9203378/35129395-a93d5bc8-fc78-11e7-98d4-715ddad6ea9b.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed
