### ISSUE TITLE
add/edit Project - the Name field and Add User drop-down are showing different fields

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10912]
**Rancher versions:** 2.0 master 1/17

**Steps to Reproduce:**
1.  Add at least 1 User and fill out username and Display name with different information
2.  Go to Add Project
3.  Click on Add user and click on name Drop-down

**Results:** The Name field is showing the display name but the drop-down is showing username.  For those field it should either be Display Name or both.
![image](https://user-images.githubusercontent.com/11514927/35059659-2cb5c6d0-fb79-11e7-8ad0-57d369d97e76.png)

**Comment by vincent99** [comment]
@loganhz can you make it consistently use `displayName` (which is `name` or `username`) everywhere; The new change is not great:

![image](https://user-images.githubusercontent.com/753917/35122360-bbc1d48a-fc5b-11e7-853a-3993825e9b96.png)

**Comment by loganhz** [comment]
@vincent99 done.
But if a user doesn't have a `name`, we will show `username` in the dropdown.
This issue is just talking about this case.

**Comment by vincent99** [comment]
Showing `displayName` in both places is fine, the problem before was one place showed `name` (Default Admin) and the other `username` (admin).

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/19
Verified fixed
