### ISSUE TITLE
Username not populated in "users" list view / Edit view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10916]
Rancher versions: rancher/cattle:master built on 01/16 at ~ 3:30 pm

Steps to reproduce the problem:
As admin user , Create a user.
Username field is seen in list view.
Refresh this page.
In the list view / Edit view , username field is not populated.

**Comment by tfiduccia** [comment]
I can't reproduce this - can you add a screenshot.

**Comment by sangeethah** [comment]
This issue does not repro when testing with  rancher/cattle:master built on 01/17 at ~ 1:00 pm.
