### ISSUE TITLE
When nodes is setting up, node info is not localized

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10918]
**Rancher versions:** 2.0 master 1/17

**Steps to Reproduce:**
1.  Create a RKE cluster
2.  After it's fully setup go to global node page and click on Add Node
3.  Use template to add node to the cluster

**Results:** While the node is setting up, the node info (CPU, RAM, Pods) is not localized

![image](https://user-images.githubusercontent.com/11514927/35065137-865d9e8c-fb89-11e7-8a94-f86ac5c44c6b.png)

**Comment by loganhz** [comment]
This is network issue. Is there anything we can do ? @vincent99

**Comment by vincent99** [comment]
How is that a network issue?  It's fine that there's no data but it should say 'n/a', not sure a brush translation...

**Comment by loganhz** [comment]
it shows `%generic.na%`. Can we do something to avoid it ?

**Comment by vincent99** [comment]
Yes, not display that 😄

I'm guessing it's computed before the translations are loaded.. So move it to later or into the template by handling null in the template instead of returning a translated string.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed
