### ISSUE TITLE
v2.0 - Error connecting to Websocket

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10917]
1/16 build

1. Created a GKE cluster
2. Deleted the GKE cluster from GKE

Result: Started seeing this websocket error

![pasted image at 2018_01_16 05_10 pm](https://user-images.githubusercontent.com/11410997/35063251-684ecc4e-fb7b-11e7-9ad2-c512c29bddc4.png)

**Comment by vincent99** [comment]
These are all different ways to say the same thing.  You can't use projects or parts of the cluster like namespaces if the cluster isn't active and running the cluster API (**in** that cluster).  https://github.com/rancher/rancher/issues/10884
