### ISSUE TITLE
RKE - Removing worker node results in cluster being broken.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10926]
Rancher versions: 2.0 - master 1/17

Steps to reproduce the problem:
Create a RKE cluster with 3 nodes - node1 - etcd , node2 - controller and node3 - worker.
Wait for cluster to get to "Active" state.
Remove worker node.

Node gets removed but cluster is stuck in "updating" state with following message - 
```
failed to construct cluster [cluster-tplpl] spec: driver change from rancherKubernetesEngine to not allowed
```

<img width="1332" alt="screen shot 2018-01-17 at 3 30 39 pm" src="https://user-images.githubusercontent.com/4266958/35072893-6fed67d8-fb9b-11e7-9846-6c7b7d2dc23c.png">

**Comment by alena1108** [comment]
@galal-hussein `driver change from rancherKubernetesEngine to not allowed` indicates that the driver is being reset from rke to empty. Most likely it has the same root cause with the bug @vincent99 and @ibuildthecloud fixed yesterday - when PUT/Edit done from UI, were resetting some data. Could you test on the latest, and see if the problem still persists?

**Comment by galal-hussein** [comment]
@alena1108 i don't see this error now, but i see different error:
```
time="2018-01-19T20:18:32Z" level=info msg="ClusterController cluster-96xzv completed with dropped err: [cluster-provisioner-controller] failed with : waiting for nodes to provision or a valid configuration"
```
i can see the deleted nodes still in the cluster spec, i will debug more to check the root cause.

**Comment by sangeethah** [comment]
Rancher versions: 2.0 - master 1/20

Steps to reproduce the problem:
Create a RKE cluster with 3 nodes - node1 - etcd , node2 - controller and node3 - worker.
Wait for cluster to get to "Active" state.
Remove worker node.

Worker node gets removed successfully and cluster gets to "active" state.
