### ISSUE TITLE
Two error messages show up if I don't put in json info for GKE

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10924]
**Rancher versions:** 2.0 master 1/17

**Steps to Reproduce:**
1.  Go to Add cluster and select GKE
2.  Don't put any info in the Service Account field (No json)

**Results:**  Two error messages are being thrown.  And only 1 should show up.
![image](https://user-images.githubusercontent.com/11514927/35072411-b9c30510-fba1-11e7-848b-23eaf854bc88.png)

**Comment by deniseschannon** [comment]
Related: https://github.com/rancher/rancher/issues/10623

**Comment by tfiduccia** [comment]
version - 2.0 master 1/18
Verified fixed
