### ISSUE TITLE
There is no indication about the which user is logged in.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10921]
Rancher versions: 2.0  - master 1/17

There is no indication about the which user is logged in.

<img width="1164" alt="screen shot 2018-01-17 at 1 25 03 pm" src="https://user-images.githubusercontent.com/4266958/35067839-19a85132-fb8a-11e7-90fc-7f61be67377e.png">

Including username would be helpful.

**Comment by tfiduccia** [comment]
The username should be showing up in the right-hand box that is currently grey - not in the Menu drop-down for clusters/projects/namespaces.
![image](https://user-images.githubusercontent.com/11514927/35068724-2d97d18a-fb95-11e7-8502-98060eca84ed.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/18
Verified fixed
