### ISSUE TITLE
Can't add labels to nodes from GKE

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10922]
**Rancher versions:** 2.0 master 1/17

**Steps to Reproduce:**
1.  Setup a GKE node

**Results:**  There is no way to add a label for the nodes.  I have to edit each node separately to get a label associated.

**Comment by loganhz** [comment]
@vincent99 How do we support this feature in UI?

**Comment by vincent99** [comment]
There is no API for this on our side, and probably none in Google...

**Comment by jiaqiluo** [comment]
The enhancement is validated on rancher: master 2/13 
Rancher HA setup

Steps:
- add a GKE cluster with a lable `test-key` = `123456`

Result:
 The label is applied to all nodes in the GKE cluster. 
<img width="1345" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52736162-72d20380-2f86-11e9-838c-8b686dcc90f0.png">
