### ISSUE TITLE
RKE Cluster is stuck in updating due to port errors - need to verify after port checking is added back into RKE

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10937]
Rancher server - v2.0 - master 1/17 9pm build

Steps to reproduce the problem:
Create a RKE cluster and wait for it to become "Active".
Add a user to this cluster (In my case role was "cluster owner")
Right after this , cluster state changes to "updating" and is stuck in "updating" state forever.

Following is 1 of the transition messages seen:

```
"Failed to start [rke-port-listener] container on host [45.55.55.128]: Error response from daemon: driver failed programming external connectivity on endpoint rke-port-listener (7f1ac9f3455ca02b9c9737bfc2cd2b74b68bcea369203feea27f4675f7fedfef): Error starting userland proxy: listen tcp 0.0.0.0:6443: bind: address already in use"
```

**Comment by sangeethah** [comment]
I see the same issue when adding more nodes to an existing cluster. 
Cluster state gets stuck in "updating" forever and i see similar transition messages.

**Comment by soumyalj** [comment]
Created a 3 node cluster as below:
N1: etcd, worker, control
N2: etcd
N3: etcd

Cluster provisioning fails with the below error:
```
E0118 20:09:22.842143       1 generic_controller.go:185] ClusterController cluster-tvq62 [cluster-provisioner-controller] failed with : Failed to start [rke-port-listener] container on host [159.203.68.226]: Error response from daemon: driver failed programming external connectivity on endpoint rke-port-listener (86e8f2b98909d2dc559dd7a5e0b99c744fb814ac29aa085d30e1e6556714d1b8): Error starting userland proxy: listen tcp 0.0.0.0:6443: bind: address already in use

```

**Comment by alena1108** [comment]
@sangeethah @soumyalj @moelsayed lets keep 2 problems separate: 

Problem #1 - RKE update is called on cluster even when nothing is changed in the spec. That is already tracked: https://github.com/rancher/rancher/issues/10864
Problem #2 - update on RKE fails due to port error. This bug is to keep track of this issue.

**Comment by sangeethah** [comment]
Tested with Rancher server - v2.0 - master 1/18 9:30pm build

This issue  with node being stuck in "updating" state is not not seen in the following 2 cases: 
1. when adding users to a cluster
2. When adding new node to an existing cluster

**Comment by deniseschannon** [comment]
should be in the next build 1/20 after 4pm

**Comment by sangeethah** [comment]
Rancher server - v2.0 - master 1/120 4pm build

This issue with node being stuck in "updating" state is not not seen in the following 2 cases:

When adding users to a cluster
When adding new node to an existing cluster

**Comment by sangeethah** [comment]
@soumyalj , can you make sure your scenario also works with latest build?

**Comment by soumyalj** [comment]
Creating a 3 node cluster as below is successful:
N1: etcd, worker, control
N2: etcd
N3: etcd
