### ISSUE TITLE
EBS volume loses data after EBS infrastructure stack upgrade

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10934]
**Rancher versions:**
rancher/server: Upgrade from v1.6.14 to v1.6.15-rc1

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a setup in v1.6.14 and launch EBS catalog
2. Create few services with EBS volumes(Env scoped/stack scoped/container scoped)
3. Upgrade rancher server to v1.6.15-rc1 and upgrade Network services/IPsec stack
4. Upgrade some services created in v1.6.14 to use new ebs volumes and also create new services which use new volumes
5. Upgrade EBS infra stack

Services which were created in v1.6.14 and upgraded to have new ebs volumes after rancher server upgrade lose data.
```
root@ce1926c01077:/testdata# ls
ls: reading directory .: Input/output error

```
root@26f0339ca90b:/mydata# ls
ls: reading directory .: Input/output error
```

**Comment by StrongMonkey** [comment]
The upgrade steps are not correct. You have to upgrade ebs-driver first before you upgrade other services. If you don't follow this step there is a risk that the volume will be umounted because the garbage collector will not work properly. Let me know if you have seen any problems by upgrading ebs-driver first.

**Comment by sangeethah** [comment]
@StrongMonkey , We cannot be assume that users are going to upgrade EBS stack as soon as they have upgraded rancher-server.  There would always be many users who choose NOT to upgrade EBS stack  and do it at a later point. 

If we are saying that there could be a volume loss if  a service with EBS volume gets upgraded with 1.6.15 rancher-server (and EBS not upgraded to use flex volumes) , this is not acceptable. 
Is this risk of loosing volume restricted to only services that were upgraded or even new services that were created in 1.6.15 rancher-server with  EBS not upgraded to use flex volumes ?

**Comment by StrongMonkey** [comment]
@sangeethah there are two points:
1. if user upgrade to v1.6.5, the default volume deployment is flex volume if driver is rancher-managed drivers. That means if you upgrade or redeploy any of the service using these driver, the service will deploy with bind mount instead of docker volume.
2. If user upgrade rancher, and don't upgrade ebs, that's fine. But if they decide to upgrade one of their service using ebs driver, i don't see why they shouldn't upgrade ebs before they upgrade ebs service. If you upgrade service first without upgrading ebs, so service is deployed with bind mount while the old driver is still applying docker-volume based GC, and the volume is likely to be unmounted.

**Comment by StrongMonkey** [comment]
We need to force upgrade EBS driver stack(or other flex volume driver) before we do any operation on services.

**Comment by deniseschannon** [comment]
@soumyalj can you retest with the new requirements?

**Comment by deniseschannon** [comment]
We've changed the approach with old/new volumes.

Previously, for the rancher/agent to decide between using the new flexvolumes/hostbindmounts or the legacy docker volumes code, we looked for the existence of a `rancher.sock` file to know whether or not the driver is a rancher driver. That file exists in both the old way and new way, so we cant distinguish between  a non-upgraded driver and an upgraded one

In the next RC (v1.6.15-rc3), we are going to add an api to the volume driver that will be exposed on the `rancher.sock` file. This api call will tell us if flexVolumes is supported and it will ONLY by on upgraded drivers. So, to determine whether to use the old way or the new way, we will look for the existence of the `rancher.sock` file AND make a "supportsFlexVolumes" call to that sock file
if that call fails, then we know the volume driver has not been upgraded and we need to mount the volume through the legacy docker volume code path.

**Comment by deniseschannon** [comment]
@soumyalj please test using the original use case that you had filed.

**Comment by soumyalj** [comment]
Tested with v1.6.15-rc3. 
1. Create a setup in v1.6.14 and launch EBS catalog
2. Create few services with EBS volumes(Env scoped/stack scoped/container scoped)
3. Upgrade rancher server to v1.6.15-rc1 and upgrade Network services/IPsec stack
4. Upgrade some services created in v1.6.14 to use new ebs volumes and also create new services which use new volumes
5. Upgrade EBS infra stack
Services which were created in v1.6.14 and upgraded to have new ebs volumes after rancher server upgrade did not lose data.  Read and write to volumes was successful.
The two volumes in the service and data shown below:

```
root@d5c7a74fad4f:/mydata# cat test.txt
Hello envvolume1
Hello after rancher upg
Hello final
root@d5c7a74fad4f:/mydata# cd ../
root@d5c7a74fad4f:/# cd second/
root@d5c7a74fad4f:/second# cat test.txt
Hello second volume after rancher upg
Hello final

```
