### ISSUE TITLE
Service Alias and External Service

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1093]
v0.23.0-rc6

It'd be nice to have something to indicate what is a service alias versus external service in the graph view of a service.

Right now, it just says "No containers" underneath, which doesn't give you good insight on why there are no containers.

**Comment by vincent99** [comment]
Yes, that especially makes no sense since they can't have containers.  And the icon should reflect what kind of service the box is.  But not going to happen before beta.

**Comment by vincent99** [comment]
Or not.. I changed the icons to match a couple days ago.  It still says "No containers" though.

**Comment by will-chan** [comment]
UI 2.0 will indicate this.
