### ISSUE TITLE
Cannot add a custom host in the same machine running the server

### ISSUE THREAD

**Issue by swapnil-pandey** [rancher/rancher#10938]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
16.04LTS 
4.13.0-26-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Docker

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Steps to Reproduce:**
I run the server successfully using the command: 
`sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server`
The ui is accessible on 192.168.0.61:8080(my local ip).
But when I add a custom host using:
`sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 http://192.168.0.61:8080/v1/scripts/9A7593113BC0BE3BD206:1514678400000:KYukHa4kJAcLMPnVlNTBFMgthY`
or
`sudo docker run -e CATTLE_AGENT_IP="192.168.0.1"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 http://192.168.0.61:8080/v1/scripts/9A7593113BC0BE3BD206:1514678400000:KYukHa4kJAcLMPnVlNTBFMgthY`

My ifconfig gives:
`docker0   Link encap:Ethernet  HWaddr 02:42:a7:e5:7b:b8  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:a7ff:fee5:7bb8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:43705 errors:0 dropped:0 overruns:0 frame:0
          TX packets:60832 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:42918703 (42.9 MB)  TX bytes:9830762 (9.8 MB)

enp2s0    Link encap:Ethernet  HWaddr d8:cb:8a:b7:b6:52  
          inet addr:192.168.0.61  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::6b7d:9db0:c9ed:79f1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:620763 errors:0 dropped:0 overruns:0 frame:0
          TX packets:335177 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:775744709 (775.7 MB)  TX bytes:44898813 (44.8 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4339 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4339 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2095373 (2.0 MB)  TX bytes:2095373 (2.0 MB)

veth6061644 Link encap:Ethernet  HWaddr 52:32:9a:5c:f6:79  
          inet6 addr: fe80::5032:9aff:fe5c:f679/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:43551 errors:0 dropped:0 overruns:0 frame:0
          TX packets:60863 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:43509239 (43.5 MB)  TX bytes:9811813 (9.8 MB)`
**Results:**
No host gets created

Edit. I looked into the network logs using: `sudo cat /var/log/syslog | grep Net' and found something fishy:

`Jan 18 14:06:12  NetworkManager[771]: <warn>  [1516264572.4251] device (veth7bd8b17): failed to find device 30 'veth7bd8b17' with udev
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.4263] manager: (veth7bd8b17): new Veth device (/org/freedesktop/NetworkManager/Devices/40)
Jan 18 14:06:12  NetworkManager[771]: <warn>  [1516264572.4265] device (veth14e03f0): failed to find device 31 'veth14e03f0' with udev
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.4272] manager: (veth14e03f0): new Veth device (/org/freedesktop/NetworkManager/Devices/41)
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.4310] devices added (path: /sys/devices/virtual/net/veth14e03f0, iface: veth14e03f0)
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.4311] device added (path: /sys/devices/virtual/net/veth14e03f0, iface: veth14e03f0): no ifupdown configuration found.
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.4335] devices added (path: /sys/devices/virtual/net/veth7bd8b17, iface: veth7bd8b17)
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.4335] device added (path: /sys/devices/virtual/net/veth7bd8b17, iface: veth7bd8b17): no ifupdown configuration found.
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.8835] device (veth7bd8b17): driver 'veth' does not support carrier detection.
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.8882] devices removed (path: /sys/devices/virtual/net/veth7bd8b17, iface: veth7bd8b17)
Jan 18 14:06:12  NetworkManager[771]: <info>  [1516264572.9086] device (veth14e03f0): link connected
Jan 18 14:06:14  NetworkManager[771]: <warn>  [1516264574.0548] device (veth9f5be77): failed to find device 32 'veth9f5be77' with udev
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.0562] manager: (veth9f5be77): new Veth device (/org/freedesktop/NetworkManager/Devices/42)
Jan 18 14:06:14  NetworkManager[771]: <warn>  [1516264574.0566] device (veth4a4e5d5): failed to find device 33 'veth4a4e5d5' with udev
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.0574] manager: (veth4a4e5d5): new Veth device (/org/freedesktop/NetworkManager/Devices/43)
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.0645] devices added (path: /sys/devices/virtual/net/veth9f5be77, iface: veth9f5be77)
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.0645] device added (path: /sys/devices/virtual/net/veth9f5be77, iface: veth9f5be77): no ifupdown configuration found.
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.0650] devices added (path: /sys/devices/virtual/net/veth4a4e5d5, iface: veth4a4e5d5)
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.0652] device added (path: /sys/devices/virtual/net/veth4a4e5d5, iface: veth4a4e5d5): no ifupdown configuration found.
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.5435] devices removed (path: /sys/devices/virtual/net/veth9f5be77, iface: veth9f5be77)
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.5443] device (veth9f5be77): driver 'veth' does not support carrier detection.
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.5449] device (veth4a4e5d5): link connected
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.8276] device (veth4a4e5d5): link disconnected
Jan 18 14:06:14  NetworkManager[771]: <warn>  [1516264574.8276] device (veth9f5be77): failed to find device 32 'veth9f5be77' with udev
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.8286] manager: (veth9f5be77): new Veth device (/org/freedesktop/NetworkManager/Devices/44)
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.8388] devices added (path: /sys/devices/virtual/net/veth9f5be77, iface: veth9f5be77)
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.8389] device added (path: /sys/devices/virtual/net/veth9f5be77, iface: veth9f5be77): no ifupdown configuration found.
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.9596] devices removed (path: /sys/devices/virtual/net/veth9f5be77, iface: veth9f5be77)
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.9604] device (veth9f5be77): driver 'veth' does not support carrier detection.
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.9605] device (veth4a4e5d5): driver 'veth' does not support carrier detection.
Jan 18 14:06:14  NetworkManager[771]: <info>  [1516264574.9642] devices removed (path: /sys/devices/virtual/net/veth4a4e5d5, iface: veth4a4e5d5)
Jan 18 14:06:18  NetworkManager[771]: <info>  [1516264578.8034] device (veth14e03f0): link disconnected
Jan 18 14:06:18  NetworkManager[771]: <warn>  [1516264578.8035] device (veth7bd8b17): failed to find device 30 'veth7bd8b17' with udev
Jan 18 14:06:18  NetworkManager[771]: <info>  [1516264578.8053] manager: (veth7bd8b17): new Veth device (/org/freedesktop/NetworkManager/Devices/45)
Jan 18 14:06:18  NetworkManager[771]: <info>  [1516264578.8114] devices added (path: /sys/devices/virtual/net/veth7bd8b17, iface: veth7bd8b17)
Jan 18 14:06:18  NetworkManager[771]: <info>  [1516264578.8115] device added (path: /sys/devices/virtual/net/veth7bd8b17, iface: veth7bd8b17): no ifupdown configuration found.
Jan 18 14:06:19  NetworkManager[771]: <info>  [1516264579.1076] devices removed (path: /sys/devices/virtual/net/veth7bd8b17, iface: veth7bd8b17)
Jan 18 14:06:19  NetworkManager[771]: <info>  [1516264579.1077] device (veth7bd8b17): driver 'veth' does not support carrier detection.
Jan 18 14:06:19  NetworkManager[771]: <info>  [1516264579.1078] device (veth14e03f0): driver 'veth' does not support carrier detection.
Jan 18 14:06:19  NetworkManager[771]: <info>  [1516264579.1139] devices removed (path: /sys/devices/virtual/net/veth14e03f0, iface: veth14e03f0)`

**Comment by swapnil-pandey** [comment]
I solved this issue by looking at the docker logs of the 'rancher-server' container and subsequently fixing the dnsmasq issue.

**Comment by duylddev** [comment]
How did you fix that?
