### ISSUE TITLE
Ability to update cached images on hosts

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1094]
Currently, there is no way to force Rancher to pull the latest version of an image from DockerHub if a latest version image is already on the host. 

Ideally, there would be some kind of mechanism or option to pull a latest version of an image so that when we start the container (or containers from a service) it could pull a new latest before it runs.

**Comment by stephenlawrence** [comment]
I would add that its an issue with private registries as well.

**Comment by jwhitcraft** [comment]
:+1:  for this!

**Comment by will-chan** [comment]
#1277

**Comment by phallguy** [comment]
I was about to post a similar request but I wonder though if this is a good idea. I would think that for production ops, we would want to be pretty explicit about the version of the container that we use. So using the explicit release version for the container we're interested should be enough to get the latest image on all the hosts.

It would certainly be convenient to have some sort of universal 'pull' request that would fetch all the latest images on all the hosts, but I wonder if thats actually a good idea?

**Comment by stephenlawrence** [comment]
Here is a use-case for this:

As I am building my rancher stack and testing out each container I run into a problem with one of my docker builds for a container. I make a change to the Dockerfile, re-build it, push it to our registry and re-create it in rancher using the same image.

Now, I could just create a new tag every time I make a change, but since this is still experimental I am re-building the containers.

Another use-case: We want to just have a general "Development" version of a container that can be used at any time to have the latest development version of the service container from our develop branch. I cannot just "refresh" my rancher stack to pull a newly updated image.

**Comment by phallguy** [comment]
Yep, that's the exact same scenario that drove me to this PR. I wanted to iterate on a container without having to tag and modify the build scripts each time I made a small change. I think it would be nice to have some sort of command that I could tell rancher to pull down the latest image. I'm just raising the question that if this is easy to do, that it might encourage less than best-practice from users of rancher. To be clear, not raising an objection to the feature, I want it as well, just surfacing the question intended/desired behavior from an ops stack.

Using their api it's not too hard to write a script that iterates through each of the hosts registered with docker and issue a docker pull for the image in question. 

In the end I just ended up build a rake task that builds and tags the container and updates the version automatically. Kind of the best of both worlds - deploying a specific version but still pretty easy to iterate.

**Comment by lucacri** [comment]
+1 for this too. I'm using private repositories and if i tag an image as "latest", I'd assume that rancher would check if the image is updated every time a container is created. Without it, I'd have to tag every image during CI builds, and I guess i'd have to change the rancher-compose.yml file (this is getting dirty) to reference the new tag.

Without the "latest" check, automating pushes and continuos deployment becomes very tricky

**Comment by vincent99** [comment]
While I expect we'll implement an optional way to do this, and can see the convenience value for development, it is definitely a concern that this is a terrible thing to encourage for production use.

Using `latest` means (short of comparing sha256-sums) you're going to have no idea what version is deployed on a particular container, whether they all match, or have an easy way to go back to the previous revision when things go bad.  It's also a slow asynchronous action that might fail, now in the critical path of starting a container.  When it does fail that now has to be surfaced somewhere as a partial-success (or the deploy fails, but then DockerHub downtime becomes a denial of service on your Rancher.)

**Comment by lucacri** [comment]
@vincent99 The issue is that as of now, with rancher-compose I can't specify a image version to override the one in the yaml file, so I'd have to create a bash script that creates a new docker-compose.yml every time i want to make an updated deploy.

If it helps, the people of Tutum suggest using versioning (i agree that it's a more secure/safe way), but in case the service uses a image:latest, the node will pull it before each new deploy (not before each start, just when a redeploy is issued)

**Comment by vincent99** [comment]
We will have support for templates/variable substitution in the compose.yml file soon: https://github.com/rancher/rancher/issues/1272

Right, I meant critical path of "creating" a container, not "[re]starting".  Do they special-case only "latest"?  That seems bizarre, people use things like "beta" too.  Maybe something like not matching  `/^v?[0-9.]+$/` would be more reasonable but I still don't like the idea of the behavior being implicit magic vs an explicit checkbox.

Another way to accomplish this is polling (or web hook triggers) to run `docker pull` on images you care about periodically (or when they change).  That gets you updated images on the hosts you care about, so you could run it only in dev.  And it works with anything, without requiring any integration into Rancher.  We built a toy version of this at the last DockerCon hackathon: https://github.com/rancher/sherdock

**Comment by garyatpibenchmark** [comment]
Yes, we definitely need this, thanks.

**Comment by flaccid** [comment]
+1

**Comment by Tails** [comment]
+1

**Comment by sangeethah** [comment]
Tested with build from master - Sep 18 and rancher-compose version - v0-4-0-rc2

Following options are now supported and functional (for details of how these options work refer to - #1955 )
1) rancher-compose pull [--cached] [SERVICE...]
2) rancher-compose upgrade --pull ...
3) io.rancher.container.pull_image=always

Issues seen when testing these options are tracked in different tickets.

**Comment by emudojo** [comment]
I know this is a VERY OLD thing, which was working perfectly until a while ago when I updated to the latest stable version of rancher... images are getting cached in my hosts... and updating to image:latest yields the same old cached image.. effectively breaking our dev process, tagging works fine but that triggers builds on prod and is LESS than ideal.

using v2-beta

**Comment by superseb** [comment]
Please file a new issue with the used versions and used config so we can take a look.
