### ISSUE TITLE
GKE Number of hosts not showing up until I go to cluster project and back

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10941]
**Rancher versions:** 2.0 master 1/18

**Steps to Reproduce:** 
1.  Create a GKE cloud cluster
2.  Wait for it to finish provisioning

**Results:**  All other info is filling out except for the amount of hosts number.
![image](https://user-images.githubusercontent.com/11514927/35113659-78e3365c-fc3f-11e7-84fc-cfd06090379d.png)

**Comment by StrongMonkey** [comment]
can't produce it now.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Darren fixed this - validated fixed
