### ISSUE TITLE
Dashboard for GKE has a Add Node page while it's provisioning

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10940]
**Rancher versions:** 2.0 master 1/18

**Steps to Reproduce:**
1.  Create a GKE cloud cluster
2.  While it's provisioning go to the dashboard

**Results:**  The dashboard page comes up with the message that it's still provisioning.  But the Add node page is below it as well with a Add node button.  Can't add nodes to Cloud Cluster, so this should not show up.
![image](https://user-images.githubusercontent.com/11514927/35113153-bca1763a-fc3d-11e7-876d-10e1b288a95f.png)

**Comment by loganhz** [comment]
@vincent99 what should we do in this case?

**Comment by loganhz** [comment]
Would you like to disable the add node button for cloud cluster? @tfiduccia @deniseschannon

**Comment by vincent99** [comment]
Eventually for GKE and probably all other cloud cluster providers there should be a way to trigger the API call to tell it to scale up the cluster to more nodes.

I'd like there to be a a declaration in the API of what things the cluster supports..  adding individual nodes (as in RKE), scaling up/down the node quantity (as in cloud providers), if pod security policies can be used (some clusters won't support them), etc.

But that's not going to happen, so for now @loganhz add a computed property on cluster for `canAddNode` that returns true if the cluster has a non-null `rancherKubernetesEngineConfig`.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
