### ISSUE TITLE
Name field is too small on Nodes page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10942]
**Rancher versions:** 2.0 master 1/18

**Steps to Reproduce:**
1.  Create a few GKE or RKE clusters
2.  Go to node page

**Results:**  The Name field is far too small and I think it might be them most important field?  There seems to be a lot of information but I would to see this field bigger.
![image](https://user-images.githubusercontent.com/11514927/35114020-98f9402a-fc40-11e7-9c5e-d5ae1985cdf3.png)

**Comment by vincent99** [comment]
Moved roles under the cluster.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
