### ISSUE TITLE
User created with is presented with "Change Admin Password" screen.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10949]
Rancher versions: Build jan 17 ~9 pm

Steps to reproduce the problem:
Create a user - user1  with "Require user to change their password on next login" option enabled.

Log in as user1 with valid credential user.

"Change Admin Password" screen is presented to the user where there is are reference to "admin" user in title and text .

When user enters password  and saves , it fails because of -
 https://github.com/rancher/rancher/issues/10948

UI is stuck in "Saving" state.

<img width="1464" alt="screen shot 2018-01-18 at 1 28 32 pm" src="https://user-images.githubusercontent.com/4266958/35122601-284114de-fc54-11e7-8b84-55faf31b2032.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
