### ISSUE TITLE
RKE - When adding a new node to an existing cluster with multiple roles , only 1 role is being honored.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10944]
Rancher versions: 2.0 master build jan 17 night

Steps to reproduce the problem:
Create a RKE cluster with 1 node have etcd,control and worker roles.
once cluster is in "active" state , add another node to this cluster having all 3 roles -  etcd,control and worker roles.
This node gets added only with "worker" role.

**Comment by soumyalj** [comment]
Start a two node cluster with 
N1 - control, worker, etcd
N2 - control
After the cluster comes up, add another node N3 with role "control"
N3 gets added as a worker
<img width="1274" alt="screen shot 2018-01-18 at 11 31 00 am" src="https://user-images.githubusercontent.com/18536626/35117297-1ad0f99c-fc43-11e7-9bb0-b792f8af24d4.png">

**Comment by sangeethah** [comment]
Tested with master build from Jan18 ~8:30 pm.

Adding a new node to an existing cluster with multiple roles , all roles are being set for the node.
