### ISSUE TITLE
Cluster with no nodes - when adding new nodes, there is no role check/validation

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10947]
If you end up with a cluster with no nodes (after deleting all of them), if you go to add new nodes, there is no UI validation that we have the correct roles.

<img width="822" alt="screen shot 2018-01-18 at 11 30 00 am" src="https://user-images.githubusercontent.com/11410997/35117244-f061678c-fc42-11e7-995d-9e83b639416b.png">

When creating RKE clusters, we see this:

<img width="1033" alt="screen shot 2018-01-18 at 11 30 25 am" src="https://user-images.githubusercontent.com/11410997/35117257-ffddec58-fc42-11e7-8900-a4f20563818c.png">

**Comment by vincent99** [comment]
This was intentional because there needs to be a way to make an empty cluster.  There's now "setup nodes later" and "setup nodes now" and if you pick now a valid set of roles is required.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/6
Verified fixed
