### ISSUE TITLE
Create projects and clicking on project name doesn't switch to the correct project

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10958]
1. In a cluster, create multiple projects.
2. From the list of projects for the cluster, click on the name of any of the projects that is not the `Default`

<img width="603" alt="screen shot 2018-01-18 at 8 44 30 pm" src="https://user-images.githubusercontent.com/11410997/35135199-6f57dff6-fc90-11e7-917c-37275915fdc0.png">

Results: 
I'm directed to the `Workloads` page, but it's not the correct project of the cluster that I clicked on.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
