### ISSUE TITLE
GKE - Duplicate node entries created and all nodes are reported as "worker" nodes. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10955]
Rancher versions: version 2.0 master build from jan/17

Steps to reproduce the problem:
Created a GKE cluster with 3 nodes.

Once the cluster was created , I see 5 node entries , out of which 2 of the node entries are duplicate entries .

Also all nodes are reported with "Worker" role.
<img width="1395" alt="screen shot 2018-01-18 at 3 40 20 pm" src="https://user-images.githubusercontent.com/4266958/35127837-a1847188-fc68-11e7-8d0b-4559160f5c13.png">

**Comment by vincent99** [comment]
All nodes in a GKE cluster are workers; etcd and the control plane are invisible to the user in GKE.

**Comment by alena1108** [comment]
So this issue is to track duplicated worker nodes only. The fact that there is no control/etcd plane nodes, is not a bug.

**Comment by deniseschannon** [comment]
still seeing this issue in the 1/20 at 4pm

**Comment by soumyalj** [comment]
Tested with Jan 23rd build. Created a 3 node GKE cluster few times. No duplicate entries are created for the nodes.
