### ISSUE TITLE
Namespace Options: `Add Container` doesn't work 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10959]
In a cluster, under the "Namespace" tab, the list of options for a namespace include "add Container".

<img width="1190" alt="screen shot 2018-01-18 at 8 53 33 pm" src="https://user-images.githubusercontent.com/11410997/35135371-af043252-fc91-11e7-9dbf-4106dcee65f7.png">

1. Rename from "Add Container" to "Add Pod"

2. Fix so the link works as it errors out when you click on it:

<img width="419" alt="screen shot 2018-01-18 at 8 54 06 pm" src="https://user-images.githubusercontent.com/11410997/35135381-bfa25f26-fc91-11e7-88f0-4b59fc61f036.png">

**Comment by loganhz** [comment]
`Add Pod` will be disabled for the namespace with a `none` project.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
