### ISSUE TITLE
New roles added does not get displayed in the "Node" list view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10952]
Rancher versions: v2.0 master build from jan/17

Steps to reproduce the problem:
As admin user , create a new role going to "Security/Role".
Newly added role is not listed in the "Role" view.

It does get listed in the Role drop down for "Inherit from a Role" When another Add role is attempted.

**Comment by tfiduccia** [comment]
version - 2.0 master 1/20
Not fixed - The role is add to list on the Roles page, but not to any of the drop-downs.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
