### ISSUE TITLE
Host ip address is truncated in the Load Balancers list view when the host name is long.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1095]
Server version - V0.23.0-rc6

When Load Balancer is created for a host that has long host name , Host ip address is truncated the Load balancer list view 

![screen shot 2015-06-08 at 2 31 29 pm](https://cloud.githubusercontent.com/assets/4266958/8045832/217ef878-0deb-11e5-978a-01a3798e42da.png)

**Comment by deniseschannon** [comment]
With the new UI, this view is no longer valid.
