### ISSUE TITLE
Renaming catalog makes it unable to remove the catalog

### ISSUE THREAD

**Issue by elnebuloso** [rancher/rancher#10969]
**Rancher versions:**
rancher/server: v1.6.14

After renaming the catalog name from **foo-bar** to **foo/bar** it is not possible to delete the catalog.
The DELETE Request returns 404

Request URL:http://rancher/v1-catalog/catalogs/foo/bar
Request Method:DELETE

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
