### ISSUE TITLE
Creating gke cluster add admin a second time automatically

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10964]
**Rancher versions:** 2.0 master 1/18

**Steps to Reproduce:**
1.  Go to Add CLuster and try to add a gke cluster

**Results:**  Notice when you click Create it add the Default Admin a second time to the list.
![image](https://user-images.githubusercontent.com/11514927/35136480-19e23722-fca1-11e7-961b-f03361526e06.png)

**Comment by deniseschannon** [comment]
This doesn't actually add/create another admin. It just shows up again for some reason right before cluster creation. Seems some kind of syncing issue right before it's created.

**Comment by cjellick** [comment]
I think this is because the UI is pretend adding the current user as the owner but then the backend adds them for real and the UI gets the event that theyve been added and it shows up.
@westlywright do you think that might be what is happening?

**Comment by deniseschannon** [comment]
@westlywright the UI doesn't show up the default admin in a new row, but a new row still pops up.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
