### ISSUE TITLE
Trying to move namespace get stuck in "Saving"

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10967]
**Rancher versions:** 2.0 master 1/18

**Steps to Reproduce:**
1.  Create a cluster
2.  Go to Cluster
3.  Create a namespace and add it to the default project
4.  Create a new project called "project1"
5.  Go to namespace and use from menu to try and move it to project1

**Results:**  Stuck in Saving.  Error from console:
ember-fetch.js:471 PUT http://localhost:8080/v3/clusters/cluster-bcsbm:rancher-default/namespaces/namespace2 404 (Not Found)

**Comment:** If I try to change the project from the namespace's edit modal I get a "clusters.management.cattle.io "rancher-default" not found: undefined"

**Comment by deniseschannon** [comment]
@tfiduccia I was unable to reproduce using today's build (1/22),

Can you re-test?

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
