### ISSUE TITLE
Error when creating GKE cluster - e.alertChildDidSave is not a function

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#10963]
1/18 - master build 9:40pm 

1. Attempt to creat GKE cluster
2. Click on "Create".

Result: Extra user added in security section
Errors out, but in the background, the GKE cluster is being created.

<img width="694" alt="screen shot 2018-01-18 at 9 41 43 pm" src="https://user-images.githubusercontent.com/11410997/35136435-6c37ef5c-fc98-11e7-93ae-967f5df48bbb.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
