### ISSUE TITLE
Make cluster & node name required and change type to dnsLabel

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10965]
**Rancher versions:** 2.0 master 1/18

**Results:** Make the names field required and the change the type to dnsLabel so we can validate the name field without having to POST.

We really need to do this so that we can validate the Node name during the template creation instead of during RKE cluster creation.  Especially since i can't remove or edit them after I added them.
![image](https://user-images.githubusercontent.com/11514927/35136804-e6502a20-fca2-11e7-94c6-f2e2e94f7c40.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/29
Name is not required.  Validation for DNS label is also not working.

**Comment by moelsayed** [comment]
Currently, Machine/Node has 4 name fields:

Field | Type | Create | Update
-------|---------|-----------|-----------
 `requestedHostname` | dnsLabel| true| false
 `hostname`| string  |false|false
 `nodeName`|          string| false | false
 `name`| string| true  | true

I discussed this with @vincent99 and he said that this is the correct state, and no further changes are required.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/20
Verified fixed
