### ISSUE TITLE
When DO machine provisioning errors out , node state is stuck in "provisioning" state and it gets included in cluster node count.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10968]
**Rancher versions: 2.0 master build on Jan 18 ~9:30 pm

Steps that resulted in the problem:
Created a cluster with 1 node (having all roles) using DO template.
Node provisioning failed and Node was stuck in "Provisioning" state.
Cluster state was also stuck in "provisioning"

Following errors seen:
```
time="2018-01-19T06:25:50Z" level=info msg="stdout: Detecting the provisioner..."
time="2018-01-19T06:25:51Z" level=info msg="stdout: Provisioning with ubuntu(systemd)..."
time="2018-01-19T06:26:05Z" level=info msg="stdout: Installing Docker..."
time="2018-01-19T06:26:25Z" level=info msg="stdout: Copying certs to the local machine directory..."
time="2018-01-19T06:26:26Z" level=info msg="stdout: Copying certs to the remote machine..."
time="2018-01-19T06:26:28Z" level=info msg="TokenActionHandler called for action logout"
time="2018-01-19T06:26:30Z" level=info msg="stdout: Setting Docker configuration on the remote daemon..."
time="2018-01-19T06:26:34Z" level=info msg="stdout: Checking connection to Docker..."
time="2018-01-19T06:26:36Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag."
time="2018-01-19T06:26:36Z" level=info msg="stdout: "
time="2018-01-19T06:26:37Z" level=info msg="Generating and uploading machine config santest11"
E0119 06:26:37.031813       1 generic_controller.go:185] MachineController cluster-6jdr9/machine-z84bm [machine-controller] failed with : Error creating machine: Error checking the host: Get https://api.digitalocean.com/v2/droplets/79336842: read tcp 172.17.0.2:48544->104.16.25.4:443: read: connection reset by peer
```

Added another node (With all 3 roles) to this cluster.
This node provisioned successfully.
Cluster gets to "Active" state now with node count as "2" when actually the cluster has only 1 node.

Also should the node that is stuck in "provisioning" state be set to "error" state ?

**Comment by aiwantaozi** [comment]
Hi @sangeethah I have try several machine and could not reproduce the error in log. And what do you mean when the cluster get Active with node count 2, in which page, I use the latest v2.0.0-alpha21 and see this picture.
![wx20180312-110303](https://user-images.githubusercontent.com/5936271/37263907-5eb69600-25e5-11e8-9fc7-932770623d2c.png)

**Comment by sangeethah** [comment]
@aiwantaozi  , This issue will be seen only when you have DO machine error out for some reason and the host gets stuck in "provisioning" state.

In this case , even the host has not been added to the K8s cluster , cluster will already show the node count as 2. 


<img width="1304" alt="screen shot 2018-03-16 at 4 51 20 pm" src="https://user-images.githubusercontent.com/4266958/37549129-7863afc2-293a-11e8-8b33-0e29c093b02c.png">


<img width="1322" alt="screen shot 2018-03-16 at 4 51 34 pm" src="https://user-images.githubusercontent.com/4266958/37549132-7ddc90e0-293a-11e8-8b9f-4dfd58bd626b.png">

Ideally , the node count on the cluster page should not reflect the host that was never added to the cluster ( when it is still in the process of provisioning ).

In case host gets stuck in provisioning , currently the user needs to manually delete this node which will trigger another node to be added to the set up. Do we want to do anything better in this case of being able to delete the nodes that are stuck in "provisioning" state automatically  ?

**Comment by vincent99** [comment]
I said this somewhere else already, but the node count is the count of nodes.  It should match the number of nodes you see if you go into the cluster, which has nothing to do with the state they are in.

**Comment by aiwantaozi** [comment]
Yes, I have seen what you mean in this issue https://github.com/rancher/rancher/issues/11152, so the count is we expected.
