### ISSUE TITLE
Error shows up when adding user to cluster

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10977]
**Rancher versions:** 2.0 master 1/19

**Steps to Reproduce:**
1.  Create a GKE cluster
2.  Go to Users page and Add User
3.  For User have Global Permission = Standard User
4.  Edit the GKE cluster and try to add the user

**Results:** The user is actually added to the cluster but and error shows up and the Edit Cluster page stays up.
![image](https://user-images.githubusercontent.com/11514927/35164321-226578e4-fd07-11e7-9cde-8a8223d0b2d5.png)

**Comment by deniseschannon** [comment]
seemed to work with 1/20 build.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
If my user is an admin user, I'm still seeing the problem

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
