### ISSUE TITLE
Changing parameters on kubernetes addons do not get applied after first run

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10971]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent:

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Set up Kubernetes environment
1. Change DNS replicas to something else and upgrade

**Results:**
Changes won't get applied. The introduced version check does not trigger a replace if the image version stays the same.

**Comment by deniseschannon** [comment]
Fixed in `k8s:v1.9.3-rancher1-2`. If you "upgrade" to the same image for add-ons and change any of the template options for add-ons, it'll upgrade the add-ons correctly.

**Comment by moelsayed** [comment]
Validated using `rancher/server:v1.6.15-rc7`:
- Created a k8s environment.
- Upgraded the k8s environment to:
  - Increase kubedns replicas
  - Increates k8s components log verbosity level. 
- Confirmed changes are reflected to the k8s environment as expected. 
- Updated the environment to change the verbosity level again.
- Confirmed changes are reflected to the k8s environment as expected.
