### ISSUE TITLE
Should block deleting the last RKE node with etcd

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rancher#10976]
I am able to remove nodes when they are the last node to either have controlplane or etcd. I figure we need to block this action when it is the last node to have either.

**Comment by deniseschannon** [comment]
In order to save the state of the RKE cluster, we shouldn't allow removing the last `etcd` node after nodes have been added.

**Comment by deniseschannon** [comment]
With master 3/1, I was able to delete the last node in a DO cluster. Rancher doesn't do anything to prevent deleting the last node. 

Related: https://github.com/rancher/rancher/issues/11520
