### ISSUE TITLE
Rancher 2.0: Attempt at using an existing Kubernetes cluster created using conjure-up results in "Forbidden: disallowed by cluster policy"

### ISSUE THREAD

**Issue by domtoupin** [rancher/rancher#10972]
**Rancher versions:**
rancher/server: v2.0.0-alpha10
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): 1.9.1

**Docker version: (`docker version`,`docker info` preferred)**
`docker info`
```
Containers: 26
 Running: 13
 Paused: 0
 Stopped: 13
Images: 11
Server Version: 1.13.1
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-25-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26 GiB
Name: juju-fd6ef0-7
ID: SPXX:TF5G:WGOO:7DJM:354S:NEXB:RCUT:IE4A:APWD:TKTC:CYN5:5YD4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`cat /etc/os-release`
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
`uname -r`
```
4.13.0-25-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
LXD on localhost via conjure-up/juju

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Install a clean Kubernetes Cluster using `conjure-up canonical-kubernetes` on localhost with default options for everything else (as documented [here](https://docs.ubuntu.com/conjure-up/devel/en/index), only change is `kubernetes` to `canonical-kubernetes`)
On the same machine install Docker and Rancher (rancher/server:preview)
In a browser, go to localhost:8080
Select "Use existing Kubernetes"
Copy paste the`kubectl apply` command and run it on the host

**Results:**
`kubectl apply -f http://192.168.xxx.xxx:8080/v3/scripts/[...]:[...].yaml`
```
namespace "cattle-system" configured
serviceaccount "rancher" unchanged
clusterrolebinding "rancher" configured
secret "rancher-credentials-0095a658" created
pod "cluster-register-0095a658" created
The DaemonSet "rancher-agent" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```

**Comment by superseb** [comment]
The cluster does not allow privileged, which is needed for running `rancher-agent`. Seems to be possible executing:

```
juju config kubernetes-master allow-privileged=true 
juju config kubernetes-worker allow-privileged=true
```

**Comment by domtoupin** [comment]
@superseb Quick reply, and, best of all, it works (only the first one is required though)!!! One just need to wait a little for the kubernetes-master to be back from `maintenance` to `active` via `juju status` :-)

Thanks a lot! :1st_place_medal:

**Comment by sixcorners** [comment]
Couldn't this be documented on the page that gives you the command to run on the server?
