### ISSUE TITLE
Support for running rancher/agent on boot2docker with Docker 17.12 and up

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10970]
Follow-up on https://github.com/rancher/rancher/issues/10502.

The statepath is prefixed with `/var` on Boot2Docker.

**Comment by nmarquesantos** [comment]
@superseb any idea when this is going to get fix? It's really impacting development for some teams

**Comment by superseb** [comment]
@nmarquesantos This will be in the next release v1.6.15

**Comment by nmarquesantos** [comment]
perfect. cheers :)

**Comment by roccolangeweg** [comment]
Is there any way to manually get the docker-agent working for now?

**Comment by tecknicaltom** [comment]
I just ran into this issue early in my initial attempts to evaluate using Rancher in my company's infrastructure (Rancher stable (1.6.14) deploying hosts with vmwarevsphere driver). Is there a good workaround so that I can continue to evaluate Rancher's viability?

**Comment by moelsayed** [comment]
Tested `rancher/server:v1.6.15-rc3` and `rancher/agent:v1.2.10-rc3` on boot2docker with docker version `17.12.1`. I was able to launch the cluster successfully.

**Comment by jeff1evesque** [comment]
Hi guys,
The information from this issue, along with recommendation from @superseb was very helpful:

```bash
$ docker-machine.exe env rancher
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="C:\Users\jlevesque\.docker\machine\machines\rancher"
export DOCKER_MACHINE_NAME="rancher"
export COMPOSE_CONVERT_WINDOWS_PATHS="true"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env rancher)
$ eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env rancher)
```

After this, I was able to add the host:

```bash
docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v
/var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 http://192.168.99.100:80
80/v1/scripts/158B4FACE558A3EC2740:1514678400000:iX22YoCOQBXC5K6f8jgCoZVBeYw
```

**Note:** if anyone is interested, I'm writing a general rancher [install script](https://github.com/jeff1evesque/machine-learning/issues/2935#issuecomment-372054645), called `install_rancher`. If anyone is interested helping, or committing that would be cool. Otherwise, feel free to recycle my code as you please.
