### ISSUE TITLE
Standard user should be created with role - "user" instead of "user-base"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10984]
rancher versions: v2.0 master build from jan/18 at ~9:30 pm

Steps to reproduce the problem:
Create a user with Global Permissions set to "Standard User".
User gets created with "user-base" role. 

```
type: "globalRoleBinding", globalRoleId: "user-base", subjectName: "user-7ht4j", subjectKind: "User"}
globalRoleId:"user-base"
subjectKind:"User"
subjectName:"user-7ht4j"
type:"globalRoleBinding"
```

Expected behavior:
When user chooses "Standard User", "user" role should be assigned .

**Comment by deniseschannon** [comment]
fixed in latest 1/20 build

**Comment by sangeethah** [comment]
Tested with rancher versions: v2.0 master build from jan/20 

Standard user get created with "user" role.
