### ISSUE TITLE
Edit Project page - Not able to add/remove users.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10985]
Rancher versions: rancher/cattle:master built on 01/18 at ~ 9:30 pm

Steps to reproduce the problem:
Create a cluster.
Once the cluster is created , navigate to any project in this cluster and use "edit" option.
On the Edit Project page , add/remove users and click on "Edit"

<img width="1330" alt="screen shot 2018-01-19 at 2 26 33 pm" src="https://user-images.githubusercontent.com/4266958/35174742-4ffc6baa-fd25-11e7-9003-2fefba45964c.png">

**Comment by deniseschannon** [comment]
Fixed in 1/20 morning build

**Comment by sangeethah** [comment]
This issue is not seen rancher/cattle:master built on 01/20
