### ISSUE TITLE
Edit Cluster/Project page shows the current user as Owner of Cluster/Project that it does not own.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10983]
Rancher versions: rancher/cattle:master built on 01/18 at ~ 9:30 pm

Steps to reproduce the problem:
Create user - user1.
Log in as user1 and create a cluster - C1.

Log in as admin.
Edit cluster C1.
Notice that "Default Admin" user is presented as the "Cluster Owner".

Try to edit the default project under C1.
Notice that "Default Admin" user is presented as the "Cluster Owner".

In both these cases "user1" should be shown as  "Project Owner".

**Comment by deniseschannon** [comment]
fixed in 1/20 morning build

**Comment by sangeethah** [comment]
Tested with rancher versions: v2.0 master build from jan/20 

This issue is not seen any more. Correct owner is presented in the Edit Cluster/Project page.
