### ISSUE TITLE
Creating RKE cluster throws "subjectName" error if I remove an empty User

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10988]
**Rancher versions:** 2.0 master 1/19

**Steps to Reproduce:**
1.  Go to Add Cluster
2.  Go to RKE cluster
3.  Put a Name in
4.  Click on Add User
5.  Remove the User
6.  Click on Create

**Results:** Error - Validation failed in API - subjectName must be set

**Comment by deniseschannon** [comment]
Unable to reproduce - 1/23 build morning

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
