### ISSUE TITLE
Project members are not allowed to see the list of users who has access to the project.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10996]
Rancher versions: rancher/cattle:master built on 01/19 at ~ 9:30 pm

Steps to create the problem:
1. As admin user , create cluster- C1.
2. Create user1 , user2.
3. Create a project P1 and add  user1 and user2 to this project as "Project Member" role.
4. Log in a user1.
5. Edit project P1.

In the Edit project View , no existing members of the projects are listed.

**Comment by cjellick** [comment]
fixed. just waiting on the next official build

**Comment by sangeethah** [comment]
Tested with Rancher versions: rancher/cattle:master built on 01/20

project members are able to list other members of the project.
