### ISSUE TITLE
Roles of nodes are not displayed at the cluster level for a RKE cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10993]
**Rancher versions:**
rancher/cattle:master

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**DO

**Steps to Reproduce:**
1. Create a 3 node RKE cluster "cluster1" 
2. Click on 'cluster1' and then nodes tab

Roles of the nodes are not displayed at the cluster level. Displaying the roles of the nodes will be helpful especially when we want to delete nodes with specific roles.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
