### ISSUE TITLE
OOM rancher/server

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1099]
A server running rancher/server:v0.23.0-rc1 is going OOM once a day.  Logs can be d/led here:

https://drive.google.com/file/d/0B0ADltRgaJpcZmtXZHg0Q3oxRDQ/view?usp=sharing

**Comment by ibuildthecloud** [comment]
There was an issue websockets would hold open references to objects even after the websocket disconnects.  To reproduce just refresh the web browser a lot of times.  Then start and stop a lot of instances.  The memory will slowly increase.
