### ISSUE TITLE
Deleting nodes in a RKE cluster freezes the UI 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10991]
**Rancher versions:**
rancher/cattle:master

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**DO

**Steps to Reproduce:**
1. Create a 4 node RKE cluster(N1 with all 3 roles, N2, N3 with worker and N4 with control)
2. Delete 3 nodes in the cluster (N2, N3, N4)
After deleting the nodes, cluster is stuck in updating state and the UI is frozen in the cluster screen. We cannot navigate to other tabs/screens

**Comment by deniseschannon** [comment]
Unable to reproduce with 1/23 morning build

**Comment by soumyalj** [comment]
Tested with Jan 23rd build. UI is not frozen after deleting nodes in a RKE cluster.
