### ISSUE TITLE
"Edit User" page for a user created with "Standard User" permission shows "custom" permission with no options enabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10992]
Rancher versions: rancher/cattle:master built on 01/19 at ~ 9:30 pm

Steps to reproduce the problem:
Create a user  with "Standard User" permission
Once user is created, choose "Edit" option.

Edit User" page for a user created with "Standard User" permission shows "custom" permission with no options enabled.

**Comment by deniseschannon** [comment]
Instead of selecting `Standard User` it shows this: 

<img width="808" alt="screen shot 2018-01-20 at 11 24 29 am" src="https://user-images.githubusercontent.com/11410997/35187186-89db285c-fdd4-11e7-848b-6cc63a288218.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed.
