### ISSUE TITLE
Allowed to create projects with duplicate names within the same cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10998]
Rancher versions: rancher/cattle:master built on 01/18 at ~ 9:30 pm
Steps to reproduce the problem:
Create a cluster C1.
Create a project with name - "test" in C1.
Create another project with same name - "test" in C1.

Project gets created successfully.

<img width="1115" alt="screen shot 2018-01-19 at 6 43 07 pm" src="https://user-images.githubusercontent.com/4266958/35179146-dc2b16bc-fd48-11e7-8bba-e487c3229f70.png">

Should we prevent creating projects with same name ?

**Comment by cjellick** [comment]
es bueno

**Comment by cjellick** [comment]
we should not prevent dupe names of projects

**Comment by cjellick** [comment]
userx and usery cannot see each others projets, so we shouldnt have global project name uniqueness
