### ISSUE TITLE
User created with "Administrator" permission is not able list/create new namespaces in clusters that were created by other users.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11000]
Rancher versions: rancher/cattle:master built on 01/18 at ~ 9:30 pm

Steps to reproduce the problem:
Create a user - u1 with "Standard User" permissions.
Create a user - a1 with "Administrator" permissions.
As user u1 , create a cluster - C1 and project - P1 in it.
Also create few namespaces in this project.

Log in as "a1".
Able to see cluster C1 and project P1.
But not able to see any namespaces.

When you attempt to create a namespace in project p1, it fails with following error message 
```namespaces is forbidden: User "user-qlvg2" cannot create namespaces at the cluster scope```

**Comment by cjellick** [comment]
this is by design. being a global admin does not mean you have full privilges into each cluster by default
