### ISSUE TITLE
Roles drop-down looks like is has dups, but roles names are on two lines.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11016]
**Rancher versions:** 2.0 master 1/20

**Steps to Reproduce:**
1.  Go to Add Cluster
2.  In the Member section, add a user and click on the role drop-down

**Results:**  Looks like roles showing up multiple times, but two lines are making it messy
![image](https://user-images.githubusercontent.com/11514927/35186772-02a9dca4-fdd7-11e7-9e79-61f23ce9ea99.png)

**Comment by vincent99** [comment]
This is getting redone to look more like global roles (owner, member, custom)

**Comment by tfiduccia** [comment]
Still looks the exact same.  Assign back when it's changed?

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
