### ISSUE TITLE
[cli] Optimize Dockerfile

### ISSUE THREAD

**Issue by iBobik** [rancher/rancher#11012]
Current Dockerfile for CLI contains many unnecessary layers, is not well formatted, Docker seems not be in PATH (#8771), autobuild on Hub is not used etc.

Will be nice if some Docker experienced developer will rework it to follow all best practices. At least declare PR is welcome.

**Comment by aemneina** [comment]
@iBobik PR's definitely welcome.

**Comment by iBobik** [comment]
Some of my objections are solved here: https://github.com/rancher/cli/pull/111

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
