### ISSUE TITLE
Clusters get stuck in removing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11014]
**Rancher versions:** 2.0 master 1/20

**Steps to Reproduce:**
1.  Add any kind of cluster
2.  After it's active try to remove it

**Results:**  Stuck in removing
![image](https://user-images.githubusercontent.com/11514927/35186460-e6498942-fdd1-11e7-9509-ea30477f00c8.png)

**Comment by ibuildthecloud** [comment]
In latest build https://github.com/rancher/cluster-controller/pull/80

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/21
Verified fixed
