### ISSUE TITLE
Canceling out of Edit Cluster takes user back to login page

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11019]
Rancher version - 2.0 built jan 19 night.

Steps to reproduce the problem:

Create RKE cluster with 3 nodes:
Use "Edit" option for cluster to launch "Edit Cluster" page.
Using "Cancel" button here takes user back to login page.

**Comment by deniseschannon** [comment]
Related: https://github.com/rancher/rancher/issues/10910

**Comment by vincent99** [comment]
These are all the same thing (#10910)..
