### ISSUE TITLE
AWS: Creating a new rancher-nodes security group doesn't open up the ports needed for kubernetes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11017]
1/20 morning build

1. Launch RKE cluster with 1 AWS node and have Rancher create the security group `rancher-nodes`
2. Security group doesn't have the necessary ports open. 

Inbound Rules: 

<img width="789" alt="screen shot 2018-01-20 at 10 59 46 am" src="https://user-images.githubusercontent.com/11410997/35186926-151d9e4e-fdd1-11e7-8ba8-c5a3c988bda5.png">

Outbound Rules:

<img width="874" alt="screen shot 2018-01-20 at 11 00 15 am" src="https://user-images.githubusercontent.com/11410997/35186932-20b99852-fdd1-11e7-89ec-3a7883ba422e.png">

**Comment by StrongMonkey** [comment]
https://github.com/rancher/machine/pull/3

**Comment by deniseschannon** [comment]
Fixed in the 1/20 3pm build:

<img width="935" alt="screen shot 2018-01-20 at 3 41 41 pm" src="https://user-images.githubusercontent.com/11410997/35189094-7b6be18e-fdf8-11e7-806b-60348ceb25f4.png">
