### ISSUE TITLE
RKE cluster with >1 node is deleting all nodes except 1

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11013]
**Rancher versions:** 2.0 master 1/20

**Steps to Reproduce:**
1.  Create an RKE cluster with 3 nodes
2.  Wait for it to become active

**Results:**  All three nodes become active, but only 1 node stays.  The other two nodes are deleted.

**Comment by soumyalj** [comment]
Tested with rancher/cattle:master build(Sat 4:00pm build). Creation of RKE cluster with multiple nodes is successful. Cluster and the nodes are active. Namespace creation also works.
