### ISSUE TITLE
Make add user drop-down in cluster/project sort alphabetically

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11010]
**Rancher versions:** 2.0 master 1/20

**Steps to Reproduce:**
1. Go to users and add testuser1 and testuser2
2.  Go to Add Cluster and click on the User drop-down in the member section
3.  Go to Add project and click on the User drop-down in the member section

**Results:**  The list is not sorted in any way the customer would be able to use.  Please sort it alphabetically
![image](https://user-images.githubusercontent.com/11514927/35186057-57487178-fdcb-11e7-9632-8696041c710e.png)

**Comment by westlywright** [comment]
https://github.com/rancher/ui/pull/1581

**Comment by deniseschannon** [comment]
not quite completely alphabetical. 

<img width="202" alt="screen shot 2018-01-20 at 5 31 58 pm" src="https://user-images.githubusercontent.com/11410997/35189815-dc09c1aa-fe07-11e7-9607-32379a58e60e.png">

if the user has no display name, it shows the username in the dropdown. so it sorts all the ones with no display name alphabetically and then the ones with display names.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
