### ISSUE TITLE
GKE node is creating/showing up twice

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11020]
**Rancher versions:** 2.0 master 1/20

**Steps to Reproduce:**
1.  Create a GKE cluster with 3 nodes
2.  Go to nodes page (either global or cluster)

**Results:**  4 nodes are showing up.  One node is repeating but it's being created twice in the API, so we are showing it.
![image](https://user-images.githubusercontent.com/11514927/35188190-7932b78a-fdee-11e7-8990-9c0ad91895bb.png)

**Comment by sangeethah** [comment]
@tfiduccia  This is similar to this issue - https://github.com/rancher/rancher/issues/10955

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed.
