### ISSUE TITLE
When a user is added to a cluster with "view nodes" role , user is not able to see nodes in the cluster. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11022]
Rancher versions: rancher/cattle:master built on 01/20

Steps to reproduce the problem:
As admin user , create cluster - C1.
Create user1.
Add user1 to this cluster with "View Node" role.
Log in as user1.
user1 is able to see cluster C1.  
But there is no nodes listed in the "Node" tab.

**Comment by cjellick** [comment]
I could not reproduce this. @sangeethah does this happen consistently for you?

**Comment by sangeethah** [comment]
@cjellick , I am not able to reproduce this issue anymore when testing with rancher/cattle:master built on 01/20 built 4 pm.
