### ISSUE TITLE
RKE - Removing a node in control plane  results in cluster getting to "Unavailable" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11029]
Rancher version - master build done on jan20 at ~4 pm

Steps to reproduce the problem:
Create a cluster with 3 nodes:
node1 - controller
node2 - etcd
node3 - worker
Wait for cluster to become active

Added 2 more nodes:
node4 - controller
node5 - worker
Wait for cluster to become active

Remove node1 ( controller node)

Node gets removed.

Cluster was in "updating" state for a long time after which it went to "unavailable" state with error message - 
```
"Failed to communicate with API server: Get https://<ip>:6443/api/v1/componentstatuses: dial tcp <ip>:6443: getsockopt: connection refused"
```

Following errors seen repeatedly in server logs:
```
E0121 02:15:05.233198       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:111: Failed to list *v1.RoleBinding: Get https://159.203.170.229:6443/apis/rbac.authorization.k8s.io/v1/rolebindings?resourceVersion=0: dial tcp 159.203.170.229:6443: i/o timeout
E0121 02:15:05.234419       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:111: Failed to list *v1.ClusterRole: Get https://159.203.170.229:6443/apis/rbac.authorization.k8s.io/v1/clusterroles?resourceVersion=0: dial tcp 159.203.170.229:6443: i/o timeout
E0121 02:15:05.243760       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:111: Failed to list *v1.RoleBinding: Get https://159.203.170.229:6443/apis/rbac.authorization.k8s.io/v1/rolebindings?resourceVersion=0: dial tcp 159.203.170.229:6443: i/o timeout
E0121 02:15:05.244929       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:111: Failed to list *v1.Event: Get https://159.203.170.229:6443/api/v1/events?resourceVersion=0: dial tcp 159.203.170.229:6443: i/o timeout
E0121 02:15:05.246621       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:111: Failed to list *v1.RoleBinding: Get https://159.203.170.229:6443/apis/rbac.authorization.k8s.io/v1/rolebindings?resourceVersion=0: dial tcp 159.203.170.229:6443: i/o timeout
E0121 02:15:05.265224       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:111: Failed to list *v1.ClusterRoleBinding: Get https://159.203.170.229:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?resourceVersion=0: dial tcp 159.203.170.229:6443: i/o timeout
```

**Comment by galal-hussein** [comment]
@sangeethah I tested with the latest master, i can see the error logs but those are expected because these indicate that the old control was removed but after the rke do the update with the new servers, these error no logs show.

**Comment by soumyalj** [comment]
Tested with master. The following steps were performed : 
Create a cluster with 3 nodes:
Step 1:
node1 - control
node2 - etcd
node3 - worker
Wait for cluster to become active and create workloads

Step 2:
Added 2 more nodes:
node4 - control
node5 - worker
Wait for cluster to become active and create workloads

Delete the control node(node1) that was added in the step 1 from the nodes list tab. The control node node gets removed and new control node gets provisioned successfully. The cluster is active. Old workloads are still active and new workloads can be deployed successfully.

**Comment by selmison** [comment]
I'm facing the same issue when remove one node control/etc of a cluster.

Also when I created a cluster with two master nodes, an error appears stating that the certificate is only valid for the first node I added
