### ISSUE TITLE
Add pod section to Node Detail's page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11024]
**Rancher versions:** 2.0 master 1/20

**Results:**  Add a section to the Nodes Detail page that will show all pods that exist on that Node.

gz#6859
gz#4457

**Comment by loganhz** [comment]
There is no API to get all pods on a particular node for now.

**Comment by vincent99** [comment]
@loganhz pods have `nodeId`, which doesn't exactly directly map, but you should be able to do a `hasMany()` mapping `pod` `nodeId` to `machine` `nodeName`.

**Comment by loganhz** [comment]
@vincent99 I have tried `hasMany('nodeName', 'pod', 'nodeId')` in machine model, but it doesn't work. 
It looks like we have to get all `projects` inside the `cluster`. Then we can send requests manually to get all of the pods in each project and filter out the pods which not on the node.
But the solution sounds really bad.

**Comment by loganhz** [comment]
@vincent99 The pod create event comes from project level websocket. However, the node page is in cluster level. So it will not create the project level ws at all in node detail page. Also, the pods on a node could be in different projects. So the live update won't work without backend API supports. I think we need a cluster level API to get all of the pods in the cluster.

**Comment by vincent99** [comment]
Yes, that makes sense with how things are currently organized.

**Comment by bdentino** [comment]
Is this functionality now available? Or was this closed as a "won't fix"?

**Comment by Leen15** [comment]
Any update here?

**Comment by wpwoodjr** [comment]
k9s allows you to drill down from a node to see what pods are running on it.  I use it all the time.  Would love to see this in Rancher too.

**Comment by axeal** [comment]
@wpwoodjr FYI k9s is available in the built-in shell in the Cluster Explorer UI in Rancher v2.5, you can test this out by launching a Rancher v2.5.2 instance, opening the Explorer UI for a cluster, opening a Shell, and executing `k9s`.

**Comment by vincent99** [comment]
Explorer has this in 2.6+ (possibly earlier, don't remember when it was added).
