### ISSUE TITLE
Error when saving the password of the default admin during logging in for the first time 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11027]
1/20 4pm build

1. Launch Rancher
2. Login as default admin
3. Try to save new password with same default password shows error:

<img width="401" alt="screen shot 2018-01-20 at 4 09 04 pm" src="https://user-images.githubusercontent.com/11410997/35189301-8603948a-fdfc-11e7-8d81-5f9036edb144.png">

Detailed Error shows: 

```
{"actionLinks":{},"baseType":"error","code":"InvalidBodyContent","links":{},"message":"new password must be different from current","status":422,"type":"error"}
```
1. if we're forcing changing hte password, can we get a help text/note that it can't be the same? And if it's the same, share the error message?

If you try and update the password again, you get

```
{"actionLinks":{},"baseType":"error","code":"InvalidBodyContent","links":{},"message":"must specify current password","status":422,"type":"error"}
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
