### ISSUE TITLE
When I logout then login, the number of nodes on Cluster page say 0

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11038]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  Create multiple clusters
2.  Logout
3.  Log back in

**Results:**  Then number of nodes in the cluster all say 0 until I refresh page
![image](https://user-images.githubusercontent.com/11514927/35200563-19b4d4ec-fece-11e7-937b-f3704b139262.png)

**Comment by loganhz** [comment]
@vincent99 It looks like `hasMany` will not work if user logout then login.

https://github.com/rancher/ember-api-store/blob/master/addon/utils/denormalize.js#L146
How to set the `registered` to false if user logout?

**Comment by loganhz** [comment]
Can we reload the page after user clicks logout button? 

```
        setTimeout(function () {
          window.location.href = "/login";
        }, 500);
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
