### ISSUE TITLE
Initial provision status is red instead of blue

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11037]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1. Create a cluster

**Results:**  Sometimes the provisioning status is red instead of blue making me thing it's in error.  It happens a lot with the first initial status
![image](https://user-images.githubusercontent.com/11514927/35200327-2f5d2c04-fec9-11e7-9685-327babf32760.png)

**Comment by deniseschannon** [comment]
@vincent99 how/when does it decide to turn red? is it based on being a certain state for a specific amount of time?

**Comment by vincent99** [comment]
States have their own colors assigned, Red is transitioning=error and overrides the state color.

**Comment by deniseschannon** [comment]
@galal-hussein @moelsayed when does RKE send transitioning errors during provisioning? it seems like it's throwing an error before it's done provisioning.

**Comment by moelsayed** [comment]
RKE breaks in almost all error cases. We just quit on errors. The message shown in the screen shot is not an error message. It's a normal info level message. So, not sure what really happened. Can you send a full log when this happen ?

**Comment by deniseschannon** [comment]
I no longer see this as an issue with RKE, but instead only see this issue: https://github.com/rancher/rancher/issues/11443.

@tfiduccia can you try provisioning some nodes with node pools to confirm that during provisioning, it no longer gets red? I had only done 1 test case.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Verified fixed
