### ISSUE TITLE
Sync information from Dockerfile when containers are created from rancher server.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1103]
When I use rancher server UI to create container by providing only image name , I do not see information  about certain docker parameters like Entrypoint and command.

But when I started a container from host using docker run command specifying only the image name , the synced container object in the server has information about docker parameters like Entrypoint and command.

Can this information be made available for the containers created from rancher UI ?

**Comment by will-chan** [comment]
Is this a API issue or UI? @cjellick @vincent99

**Comment by cjellick** [comment]
Ping @ibuildthecloud you have any thoughts on this? We only do full backpopulation if the container is a "native" container. Does that seem right to you?
