### ISSUE TITLE
Not able to add user when creating cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11031]
Rancher version - master built on jan 20 at ~9:00 pm

Steps to reproduce the problem:
Create user  - user1.
Create a cluster  by adding additional member - user1 to the cluster.
Cluster creation succeeds but user does not get added to the cluster.

UI shows following error: "Validation failed in api name"

UI looses the member added when showing the error message (UI issue)

<img width="903" alt="screen shot 2018-01-20 at 9 36 33 pm" src="https://user-images.githubusercontent.com/4266958/35191243-010bcee4-fe2b-11e7-94f4-e50047adbe4d.png">

```
Request URL:http://<ip>:8080/v3/clusterroletemplatebinding
Request Method:POST
Status Code:422 Unprocessable Entity
Remote Address:35.192.149.238:8080
Referrer Policy:no-referrer-when-downgrade
```

```
{type: "clusterRoleTemplateBinding", clusterId: "cluster-svxvt", name: "", subjectKind: "User",…}
clusterId:"cluster-svxvt"
name:""
roleTemplateId:"cluster-member"
subjectKind:"User"
subjectName:"user-zjjnk"
type:"clusterRoleTemplateBinding"
```

```
{"actionLinks":{},"baseType":"error","code":"InvalidFormat","fieldName":"name","links":{},"message":"InvalidFormat 422: invalid value : a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","status":422,"type":"error"}
```

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/norman/pull/67

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/20
Verified fixed
