### ISSUE TITLE
Provide a  way to get ssh login details for host added to RKE clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11032]
Rancher version - master built on jan 20 at ~9:00 pm

Currently there is no way to  get ssh login details for hosts added using docker machines as part of RKE clusters.

**Comment by deniseschannon** [comment]
@StrongMonkey does the API in 2.0 exist to get the info for this as we had it in 1.6?

**Comment by sangeethah** [comment]
Tested with  rancher server version - v2.0.0-alpha12

Nodes added to RKE cluster have "machineConfig" link using which we are able to download the machine Configs needed to ssh to the nodes.

Able to use the downloaded machine Configs to ssh to host.
