### ISSUE TITLE
Network connectiviti issue when connecting to remote (non-docker) application

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#11042]
Rancher versions:
rancher: v1.6.12

Infrastructure Stack versions:
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:v0.13.5, rancher/net:v0.13.5
network-services: rancher/dns:v0.15.3
scheduler: rancher/scheduler:v0.8.2

Docker version: (docker version,docker info preferred)
Docker version 17.03.2-ce, build f5ec1e2

Operating system and kernel: (cat /etc/os-release, uname -r preferred)

NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-53-generic

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
Bare metal.

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
5 node cluster

Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
Cattle

Steps to Reproduce:
A containerized application under rancher connects to a remote application over a WAN. Initial connections seems ok, but over time I get errors.

When I look in container log of ipsec > sidekicks I see entries like:
````
22-1-2018 16:12:2013[IKE] sending DPD request
22-1-2018 16:12:2013[ENC] generating INFORMATIONAL request 1368 [ N(NATD_S_IP) N(NATD_D_IP) ]
22-1-2018 16:12:2013[NET] sending packet: from aa.aa.aa.aa[4500] to bb.bb.bb.bb[4500] (113 bytes)
22-1-2018 16:12:2010[NET] received packet: from bb.bb.bb.bb[4500] to aa.aa.aa.1a71[4500] (113 bytes)
22-1-2018 16:12:2010[ENC] parsed INFORMATIONAL response 1368 [ N(NATD_S_IP) N(NATD_D_IP) ]
22-1-2018 16:12:2007[KNL] querying policy failed: No such file or directory (2)
22-1-2018 16:12:2013[KNL] querying policy failed: No such file or directory (2)
22-1-2018 16:12:2014[KNL] querying policy failed: No such file or directory (2)
22-1-2018 16:12:2014[KNL] querying policy failed: No such file or directory (2)
````

And in ipsec cni driver container log:

````
22-1-2018 16:06:26time="2018-01-22T15:06:26Z" level=info msg="rancher-cni-bridge: fastPathMac: 00:18:8B:0D:4F:2B fastPathIP: IP4:{IP:{IP:10.42.154.86 Mask:ffff0000} Gateway:<nil> Routes:[]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}"
22-1-2018 16:06:26time="2018-01-22T15:06:26Z" level=info msg="rancher-cni-bridge: for container: 09083955c22eb67c16e757cf67f1146bbf8556ca68615e6ed93c4ad660b09a3e(cbfce2ae-1d7c-443a-9c26-9f059b574e2e) using mac: 00:18:8B:0D:4F:2B"
22-1-2018 16:06:26time="2018-01-22T15:06:26Z" level=info msg="rancher-cni-bridge: for container: 09083955c22eb67c16e757cf67f1146bbf8556ca68615e6ed93c4ad660b09a3e(cbfce2ae-1d7c-443a-9c26-9f059b574e2e) using ip: {10.42.154.86 ffff0000}"
````

What does this mean?

Anywhere else where I should look?

**Results:**
Bad connection between the applications.

**Comment by superseb** [comment]
The logs are annoying but harmless. They will be gone in a next release.

What exactly are you running and do you get when you get errors? Is it refused connections, timeouts? Does it restore when you restart something? Is connecting over a WAN just meaning that it goes out a host interface to another subnet/internet or another tunnel?

**Comment by bergtwvd** [comment]
The application that is ran on both sides of the WAN is what you may call a "gateway". The two gateways allow communication across a WAN using a point-to-point TCP/IP connection. On the other side of each gateway these is a cluster of (simulation) applications; on the Rancher side these simulation applications are containerized. To test connectivity, I just run the gateways without these simulation applications.

If I run the same setup using a single Docker Engine in combination with Docker Compose, it works fine; also when I use the full set of simulation applications I get connectivity across the WAN to the other side without problem.

When I use Rancher the gateway on the Rancher side (my side), the initial connection seems fine, but eventually reports data packets lost and attempts to re-connect. The exact same test under Docker Engine works fine. The WAN address on the other side in in another network (between two nations).

Anything I can pull of of any logfile?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
