### ISSUE TITLE
When adding "nodes" to cluster , cluster and host state transitions from "Active"->"Unavailable"->"Active".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11043]
**Rancher versions: 2.0 build from jan 20 night

Steps to reproduce the problem:
Create RKE cluster and wait for it to become "Active".
Add 1 node (with all roles) to this cluster.

Cluster state transitions from "Active"->"Unavailable"->"Active".
Following is the transition message presented to the user when in "Unavailable" state - "Not received heartbeat from cluster-agent"

Can this state transition to "Unavailable" be prevented?

**Comment by sangeethah** [comment]
Also we see the host have the following state transition:
Active->Unavailable->Active


<img width="1269" alt="screen shot 2018-01-22 at 1 39 32 pm" src="https://user-images.githubusercontent.com/4266958/35245998-02ead8cc-ff7a-11e7-97dd-e4d890ef0ec1.png">

**Comment by alena1108** [comment]
The issue `Not received heartbeat from cluster-agent` should be resolved in the latest, could you check

**Comment by soumyalj** [comment]
Tested with master from March 5th. Cluster goes from updating state to Active state, but nodes are still in "Unavailable" state. 
<img width="1396" alt="screen shot 2018-03-05 at 1 40 13 pm" src="https://user-images.githubusercontent.com/18536626/37001377-2d2b905a-207b-11e8-9d8e-954adebdcf30.png">

**Comment by deniseschannon** [comment]
Active -> Unavailable -> Active is typically as we wait for the k8s cluster to be up and active. 

I'm going to close in favor of these other issues as the heartbeat issue has been resolved.

https://github.com/rancher/rancher/issues/11443
