### ISSUE TITLE
Rancher 2.0 configuring openstack driver fails

### ISSUE THREAD

**Issue by simon-k8s** [rancher/rancher#11041]
**Rancher versions:**
rancher/server: 2.0 preview
rancher/agent:

**Docker version: (`docker version`,`docker info` preferred)**

Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 57
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 149
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953GiB
Name: web01
ID: P7GA:N3XZ:Z2OU:4NSE:4JSN:3YQP:AIBM:KX7V:IFND:N5Z4:SJKZ:I3WK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: 
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.0.0/24
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-98-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

openstack

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

kubernetes

**Steps to Reproduce:**

I am trying to add the docker machine openstack driver. I am able to activate the driver. Then I filled in the required data. After clicking on save the UI hangs in Saving. Nothing else happens and I don't have a clue why. Can you help me find the problem.

**Comment by loganhz** [comment]
This issue has been fixed in v2.0.4. OpenStack driver is working now.

**Comment by simon-k8s** [comment]
Nice thanks i will test it shorty
