### ISSUE TITLE
No pause, Start, restart, Stop actions for workload/Pods

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11052]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  Create a workload or pod

**Results:**  There are no Start, restart, Stop, or pause actions available.  They don't exist in API for UI to use.

**Comment by alena1108** [comment]
We are going to support pause/upgrade/rollback operations - whatever kubernetes supports. Closing this bug in favor of https://github.com/rancher/rancher/issues/11692
