### ISSUE TITLE
Launch kubectl doesn't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11053]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  Create cluster
2.  Go to Dashboard
3.  Click on Launch Kubectl

**Results:**  Empty modal pops up.

**Comment by deniseschannon** [comment]
Able to launch kubectl shell, but commands are not working. 

Getting the certs fixed will be tested with https://github.com/rancher/rancher/issues/12283
