### ISSUE TITLE
Docker version selected is not honored when nodes are created.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11058]
Rancher version - 2.0 built on Jan 20 ~9:30 pm

Steps to reproduce the problem:
Create a cluster by adding nodes which have   "Docker Install URL" set to a specific version - In my case used - https://releases.rancher.com/install-docker/17.12.sh.

engineInstallUrl is being sent when machine template api is created:

```
{type: "machineTemplate", driver: "digitalocean",…}
description:"nyc3 / 1gb"
digitaloceanConfig:{accessToken: "****", backups: false,…}
driver:"digitalocean"
engineEnv:{}
engineInstallUrl:"https://releases.rancher.com/install-docker/17.12.sh"
engineLabel:{}
engineOpt:{}
labels:{}
name:"sandocversionagain"
type:”machineTemplate”
```

Docker version that gets installed in the host is 17.03.2.

Machine Template Spec for the machine has ```Engine Install URL``` set to 17.03.2

```
  Machine Template Spec:
    Description:         nyc3 / 1gb
    Display Name:        sandocversionagain
    Driver:              digitalocean
    Engine Install URL:  https://releases.rancher.com/install-docker/17.03.2.sh
```

**Comment by deniseschannon** [comment]
It doesn't look like this is an option anymore in the UI? should it still be available? @vincent99 @StrongMonkey

**Comment by vincent99** [comment]
UI bug, it's missing from the engine options section because it's conditional (not all drivers have a choice) and isn't currently set to on by default.

**Comment by soumyalj** [comment]
Tested with master from March 1st. Created a cluster with DO template using Docker 1.12.x
[https://releases.rancher.com/install-docker/17.12.sh]
The node template had the right URL set in the API
```
"driver": "digitalocean",
"engineEnv": { },
"engineInstallURL": "https://releases.rancher.com/install-docker/1.12.sh",
"engineLabel": { },
"engineOpt": { },

```
The nodes had the docker version 1.12.x as expected
