### ISSUE TITLE
Execute Shell for workloads does not function

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11051]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  Create a workload
2.  Execute shell

**Results:**  Shell come up but never becomes active

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Not fixed - the shell is still not connecting

**Comment by loganhz** [comment]
it looks like `kubectl exec` is broken in `rancher/server:master`
```
kubectl exec -it abc-84c45bfd9c-f84m6 bash
```
error
```
unable to upgrade connection: you must specify at least 1 of stdin, stdout, stderr
```

We need fix it in backend.

**Comment by loganhz** [comment]
@tfiduccia Can you try again with `master` image, please? the backend issue has been fixed.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
