### ISSUE TITLE
Switching workload views causing error in console

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11068]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  Create a cluster that has project/namespaces and workloads
2.  Open dev tool
3.  Go to Workloads page
4.  Change the view to Flat list or any other other view

**Results:** Error in dev console everytime I switch views.  Seems like we are trying to post the preference and it's getting an error.
ember-fetch.js:471 POST http://localhost:8080/v3/preference 422 (Unprocessable Entity)
ember-metal.js:3511 undefined

**Comment by loganhz** [comment]
can not reproduce this issue

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/29
Verified fixed.  I can also no longer reproduce this.
