### ISSUE TITLE
External LB for Kubernetes

### ISSUE THREAD

**Issue by MherX** [rancher/rancher#11067]
Hi all!
Rancher by default, add LB to the first host for Kubernetes.
If I have multiple hosts and falls first, where LB, the entire infrastructure becomes unavailable.
I think that you can solve this problem if you put an external LB, I’ve read a lot of articles online but have not found how to do it for Kubernetes in rancher.
Please tell me what are the ideas to solve my problem?
Thank you in advance!

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
