### ISSUE TITLE
Clicking on namespace in workload view goes to Error page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11069]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  Create a cluster/project/namespace/workload
2.  Go to workload view and group by Namespace
3.  Click on the namespace

**Results:** Error page "Unable to find schema for "stack"

**Comment by loganhz** [comment]
As there is no namespace detail page, so I linked it to namespace list page.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
Verified fixed
