### ISSUE TITLE
Tags in edit namespace causing error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11075]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  As Admin create a cluster/project/namespace
2.  Edit namespace and try to add a tag

**Results:**  Error "Namespace parameter required." coming up.  Also it doesn't clear out when I hit cancel and if I try to edit anything else (like description) in any namespace, the error will continue to come up until I refresh page.

**Comment by loganhz** [comment]
server sends a wrong `self` link `https://0.0.0.0:8000/v3/projects/local/namespaces/default` via web-socket for `namespace` sometimes.

**Comment by loganhz** [comment]
The `self` link should be `/v3/clusters/local/namespaces/default`

**Comment by loganhz** [comment]
Another issue is that `tags` field will be ignored by server side even UI sends it.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
