### ISSUE TITLE
When a user with "cluster member" is deleted from the cluster , he continues to be the project member for the project he created.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11070]
Rancher versions: 2.0 master 1/21

Steps to reproduce the problem:
Create user - user1.
Create a cluster - c1.
Add "user1" as  "cluster member" of c1.
As user1, create project p1 in c1 and few namespace in p1.
Remove "user1" from cluster - c1.

Log in as user1.

User is allowed to see existing namespaces in p1 and is also able to create new namespace in p1.
Should the user be revoked of all the project owner privileges for all the projects that he has created.

**Comment by will-chan** [comment]
RBAC can get complicated so the simplest is to treat it as a granting or removal of permissions.  In this example, you are removing the user's permission to create projects.  By removing his permission to do this, he simply cannot do that anymore.  When he created projects previously, he was automatically granted additional permissions as a project owner.  That was not removed which is why he should be still able to manage the projects he created while he was a cluster member.  You can argue whether we should automatically removal this privilege but let's not go down that road because without this automatic grant process, the user that created the project wouldn't be able to do anything.

**Comment by cjellick** [comment]
Discuss and debated this with @deniseschannon @ibuildthecloud @vincent99 @will-chan and here is the conclusion we came to:

There are two options for the implementation/functionality:
- There current functionality is that removing the "Cluster member" role from a user in the cluster _only_ impacts what that role explicitly allows, which is to create new projects and view other cluster members. The user continues to be a member of whatever projects they were a part of
- The alternative functionality that this bug report proposes is that the user be removed from all projects that they are a member of

There is a case to be made for both options and either one will be wanted/expected by some subset of users. However,  @will-chan and I decided the right thing to do is leave the implementation as-is (the first option), document the behavior, and have the UI note/warn the user and potentially direct the user to a page where they could remove the user under question from all projects in the cluster.

Reasons for this conclusion:
1. Some percentage of users will want the first option and some will want the second option. But if we implement the second option (removing from all projects), users who want the first option are 100% out of luck. They would need to _readd_ the user to all the projects they were auto-removed from. The solution of leaving it as-is with UI enhancements basically enables both sets of users to accomplish what they want
2. Implementing the second option to do special cascading logic will be a rats-nest rabbit-hole beehive can-of-worms of edge cases. The first option is clean and simple from ta documentation perspective with no unexpected side-effects.

Assigning over to @vincent99 to do whatever UI things he thinks necessary.

**Comment by cjellick** [comment]
lol. i just wrote all that without seeing that @will-chan commented yesterday. thanks for commenting will

**Comment by cjellick** [comment]
There is no bug here. This is intended behavior. Im not going to close until @deniseschannon and I can talk, but i'll remove some labels

**Comment by deniseschannon** [comment]
We need UI to figure out a solution of being able to warn users that when deleting a cluster member, it does not change/alter any of the users permissions if directly added to a project.

**Comment by tfiduccia** [comment]
Version - 2.1 master 8/29
Not complete

- [ ] Removing user when Editing Cluster does not have warning.  We might want to have add a note in the description on edit only, saying "Note: Removing User will not remove their project permissions"
![image](https://user-images.githubusercontent.com/11514927/44816878-70c2e680-ab98-11e8-84ec-71a671a6a99a.png)

- [ ] Change text on Delete User modal - Note: User's project permissions will not be removed.

**Comment by tfiduccia** [comment]
Version - 2.1 master 8/30
Verified fixed
