### ISSUE TITLE
[kubectl] User is able to create namespace in a project that he does not have access.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11077]
Rancher versions: 2.0 master 1/21

Steps to reproduce the problem:
As Default admin user:
Create user - user1.
Create a cluster - c1.
Create a project - p1. Assign "user1" as  "project member" of project p1.
Create a project - p2.

From kubectl , user1 is allowed to create namespace  in project p2 as well. 
But he does not have access to the namespace he has created in p2.

It would be good to restrict user from being even able to create a namespace in the project he has no access to.

**Comment by cjellick** [comment]
We cant restrict at the K8S rbac level. So from kubectl, users will always be able to create NS in other projects. What we could do is add validation to rancher API to ensure user has access to the project to which they are adding the NS

**Comment by cjellick** [comment]
Wont fix because of my above comment Assigned both @sangeethah and @deniseschannon so that you both see it in case you want to discuss/debate this further, but there really is nothing we can do.
