### ISSUE TITLE
Can't see workloads after moving namespace to another project

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11074]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  As Admin create a cluster
2.  Create two projects
3.  In first project, add two workloads to a namespace
4.  Move the namespace to the second project
5.  Go to workloads page

**Results:**  Can't see the workloads, if I move it back to original project, they show back up.

**Comment by cjellick** [comment]
appears to be fixed. no single code change was made to fix this, but a ton of changes were made in this area; looks to me like one of them addressed this bug.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/4
Verified fixed
