### ISSUE TITLE
Deleting Project modal needs new text

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11076]
When deleting a project the modal pops up with this text:

<img width="707" alt="screen shot 2018-01-22 at 3 45 48 pm" src="https://user-images.githubusercontent.com/11410997/35250431-6ae624a2-ff8b-11e7-9cde-9c2972d6e11b.png">

Note: All resources inside this Project will be permanently removed, including any namespaces that were created through Rancher.

**Comment by deniseschannon** [comment]
In the same sense, when deleting clusters we should add in a Note similar to what was on the project level.

```
Note: All resources inside this Cluster will be permanently removed, including any nodes that were created through Rancher.```

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
