### ISSUE TITLE
"User drop down" field missing in "Edit cluster/Edit Project" pages.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11084]
Rancher versions: 2.0 built jan 22

Steps to reproduce the problem:
Create a cluster c1 and a project p1.
Edit cluster c1 and click on "Add User" option.
Notice that "User drop down" field  missing.
<img width="1125" alt="screen shot 2018-01-22 at 9 52 36 pm" src="https://user-images.githubusercontent.com/4266958/35260185-e87961ee-ffbe-11e7-9d3c-14f6957daa08.png">

Edit project p1 and click on "Add User" option.
Notice that "User drop down" field  missing.

<img width="1137" alt="screen shot 2018-01-22 at 9 53 05 pm" src="https://user-images.githubusercontent.com/4266958/35260189-ee58d81a-ffbe-11e7-8314-77d1df91f7bf.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
