### ISSUE TITLE
there is a error when add a host

### ISSUE THREAD

**Issue by yanyouqiang1** [rancher/rancher#11088]
INFO: Updating host-api
INFO: Downloading http://192.168.0.100:8080/v1//configcontent//host-api current=1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Already up to date
INFO: Sending host-api applied 1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Updating python-agent
INFO: Downloading http://192.168.0.100:8080/v1//configcontent//python-agent current=1-8ecf2cf4a616b933d905134749006b1321ad3e6d7eb25695192efe6f1e16787a
INFO: Already up to date
INFO: Sending python-agent applied 1-8ecf2cf4a616b933d905134749006b1321ad3e6d7eb25695192efe6f1e16787a
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
ERROR: DNS Checking loopback IP address 127.0.0.0/8, localhost or ::1 configured as the DNS server on the host file /etc/resolv.conf, can’t accept it

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by superseb** [comment]
This is expected, when `127.0.0.1` is present in `/etc/resolv.conf`, this is usually a local caching nameserver which can't be reached/used inside a container. Please read the FAQ entry on this how to resolve: http://rancher.com/docs/rancher/v1.6/en/faqs/agents/#reference-to-localhost-present-in-etcresolvconf

**Comment by zyra83** [comment]
I'm still having this issue on Ubuntu 16.04 with Rancher 1.6.16 (try.rancher).

A simple workaround is to uncomment DNS line in `/etc/default/docker` and restart docker daemon.

```sh
sudo gedit /etc/default/docker
# replace 
# # DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
# by
# DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
# then restart Docker
sudo service docker restart
```

**Comment by as-prod-autodeployment** [comment]
you replacing one thing with the same thing, I don't understand

**Comment by zyra83** [comment]
> you replacing one thing with the same thing, I don't understand

Sorry it was a typo. I forgot to remove the "#". Uncommenting DOCKER_OPTS line forces Docker to use the specified DNS instead of Ubuntu's DNS which is "localhost".

**Comment by sabhriti** [comment]
I have the similar problem. What is actually the fix to this problem?
