### ISSUE TITLE
When I bring up the custom modal in Add/Edit cluster/Project it doesn't go to top

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11087]
**Rancher versions:** 2.0 master 1/23

**Steps to Reproduce:**
1.  Create a Cluster
2.  Add user and give them custom role

**Results:** The custom role modal comes up, but the page doesn't go to top.  So you only see bottom of it.
![image](https://user-images.githubusercontent.com/11514927/35262385-a7bae3ae-ffd1-11e7-9cfc-a74e845e4e87.png)

**Comment by loganhz** [comment]
I can not reproduce this issue. It has been fixed I guess.

**Comment by deniseschannon** [comment]
@loganhz instead of marking `status/wontfix` just ask @tfiduccia to re-test with a `status/to-test` label.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/3
Verified fixed.  Yeah someone fixed it at some point
