### ISSUE TITLE
Create button missing on GKE "Add Cluster" page

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11085]
**Rancher versions:**
rancher/cattle:master - Jan 22 8:00pm build

Create a GKE cluster from Add Cluster button. 
Create button is missing

<img width="1023" alt="screen shot 2018-01-22 at 10 13 32 pm" src="https://user-images.githubusercontent.com/18536626/35260829-3b6a9c76-ffc2-11e7-8c9a-c32677897e06.png">

**Comment by tfiduccia** [comment]
Error message after json - ember-metal.js:2266 Uncaught TypeError: Cannot read property 'type' of null

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/23
Verified fixed
