### ISSUE TITLE
Error messages from previous attempts shows up on "Add Namespace" page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11086]
Rancher version - 2.0 built from jan 22 

Steps to reproduce the problem:
As admin , create cluster c and project p.
Create a user - u1 with "Standard User" permissions.
As user u1 , create a cluster - C1 and project - P1 in it.
Also create few namespaces in this project.
Log in as default admin user.

Able to see cluster C1 and project P1.
Attempt to create namespace in p1 fails as expected with forbidden error.
After this , got to cluster c and attempt to add namespace in project p.
"Add Namespace" launches with  forbidden error seen from previous attempt.

<img width="1328" alt="screen shot 2018-01-22 at 10 27 43 pm" src="https://user-images.githubusercontent.com/4266958/35261119-9ffa9866-ffc3-11e7-9bfa-9f16228e734a.png">

**Comment by sangeethah** [comment]
Same behavior is also seen with "Edit Cluster" page where the Error messages from previous attempts shows up on  entering "Edit cluster" page.

<img width="1288" alt="screen shot 2018-01-22 at 10 59 35 pm" src="https://user-images.githubusercontent.com/4266958/35262092-fc80955a-ffc7-11e7-8779-1ce910866556.png">

**Comment by sangeethah** [comment]
Tested with v2.0.0-alpha12

This issue is still reproducible.

**Comment by loganhz** [comment]
@vincent99 this is a backend issue?

**Comment by vincent99** [comment]
No, the `errors` property on the controller just isn't being cleared by resetController in the route.  Controllers are singletons so the value sticks around.

**Comment by loganhz** [comment]
ah, my bad. Thanks

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
