### ISSUE TITLE
Deleting more than (n/2) etcd nodes causes quorum loss

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#11093]
When etcd node gets deleted, the machine will be deleted immediately before RKE update happens and removes the etcd node gracefully, so quorum may be lost if the user deleted more than half of etcd nodes in the cluster

**Comment by soumyalj** [comment]
Tested few times with master from march 2nd 
1. Created a cluster with 3 node pools
N1 - all roles
N2 - etcd
N3 - etcd
2. Deployed workloads
3. Deleted both N2 and N3 (which is more than n/2 nodes)
The nodes were deleted successfully and cluster was active again. There was no quorum loss
4. The old workloads were still active. Deployed more workloads successfully
