### ISSUE TITLE
Make data only containers available only in the volumes from and container list.

### ISSUE THREAD

**Issue by jmfrappier** [rancher/rancher#1109]
I use data containers and don't have to start them.
With the new version, they don't appear in Rancher unless i start the data container, which i don't want/need to.

Thanks

**Comment by will-chan** [comment]
Is this still happening?

**Comment by cjellick** [comment]
With first class volume support in docker and rancher, the need for data containers has waned. I don't think it is worth the effort to support this. @will-chan?
