### ISSUE TITLE
Websocket error when UI is refreshed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11097]
**Rancher versions:**
rancher/cattle: master

**Steps to Reproduce:**
1. Create few RKE/GKE clusters in the setup
2. Refresh UI from the global level 

Websocket error shows up as below and the number of nodes in each cluster is shown as zero

<img width="1389" alt="screen shot 2018-01-23 at 12 04 20 pm" src="https://user-images.githubusercontent.com/18536626/35302316-de6fed4c-0042-11e8-842b-0f56bf597de1.png">

**Comment by deniseschannon** [comment]
Latest build (1/23 late night) seems to have addressed this
