### ISSUE TITLE
Deletion of namespace by project owner results in forbidden message.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11095]
Rancher server - 2.0 built on jan 22.

Steps to reproduce the problem:
Create a cluster and add "user1" as "owner"/"member" of the cluster.
As user1,
Create a project.
Create a namespace in the project.
Try to delete the namespace.

Namespace deletion fails with following error message- 
```
Error deleting
projects.management.cattle.io "cluster-lmn77" is forbidden: User "user-fr25h" cannot get projects.management.cattle.io at the cluster scope
```

**Comment by cjellick** [comment]
appears to be fixed

**Comment by soumyalj** [comment]
Tested with v2.0.0-alpha17.  Followed the below steps:

Create a cluster and add "user1" as "owner"/"member" of the cluster.
As user1,
Create a project.
Create a namespace in the project.
Delete the namespace.

The cluster owner and member  can delete a namespace in the project
