### ISSUE TITLE
panic in ProjectController in server logs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11098]
Rancher server - v2.0 built jan 22.

Following error seen server logs for many projects:

```
E0123 21:44:50.791642       1 generic_controller.go:191] ProjectController cluster-pbccf/project-v2wn8 recovered from panic "reflect: call of reflect.Value.Len on zero Value". (err=<nil>) Call stack:
```

**Comment by deniseschannon** [comment]
Without the full stack trace, it's impossible to debug. If we see it again, can we open a new one with more details @sangeethah

**Comment by sangeethah** [comment]
There was no stack trace provided in the logs when this error was seen.

**Comment by sangeethah** [comment]
Dont see the panic in logs when testing with latest 2.0 builds from master.
