### ISSUE TITLE
Cluster/Project created even though I got API error and stayed in Add

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11101]
**Rancher versions:** 2.0 master 1/23

**Steps to Reproduce:**
1.  Go to Add Cluster
2.  Click on Add User under Security section but don't add name
3.  Click on Create

**Results:**  You get an API error that says you need a name but if you cancel out, the cluster is actually creating.  The same thing happens in Add Project

**Comment by vincent99** [comment]
There's nothing we can do about the actual title, the cluster has to be created before the bindings can be sent.  But rows with no user should just be ignored on add, not cause an error.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
Verified fixed
