### ISSUE TITLE
GKE-When provisioning a GKE cluster with a cluster name that already exists , cluster keeps getting to "updating" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11107]
Rancher versions: Build from jan 23

Steps to reproduce the problem:
Created a RKE cluster with a cluster name that already existed in GKE.
Cluster gets to "Active" state almost immediately and the nodes also get synced .
After a while it keeps toggling between "updating" and "active" state.

Following error messages seen repeatedly in server logs:

```
E0123 21:55:16.158130       1 generic_controller.go:191] ClusterController cluster-z7bm9 [cluster-provisioner-controller] failed with : failed to construct cluster [cluster-z7bm9] spec: driver change from rancherKubernetesEngine to googleKubernetesEngine not allowed
```

**Comment by deniseschannon** [comment]
Added an existing GKE cluster and the cluster will eventually become `Active` in Rancher.
