### ISSUE TITLE
Not able to show custom Roles in "Edit Project" page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11103]
Rancher versions built on Jan 23

Steps to reproduce the problem:
Create a user - user1.
Create a cluster c1.
Create a project P1 by adding user1 with customer Role - "Readonly"
Edit Project P1.
users's custom role is shown as blank.

<img width="1312" alt="screen shot 2018-01-23 at 3 34 46 pm" src="https://user-images.githubusercontent.com/4266958/35306588-5932db9c-0053-11e8-925d-24bf23a5c670.png">

**Comment by tfiduccia** [comment]
Changed the way we display user's in edit.  This should be fixed

**Comment by sangeethah** [comment]
Tested with v2.0.0-alpha12

When Custom roles are associated with 1 permission , it gets displayed as expected. With multiple permissions we see "Multiple Roles" tracked in https://github.com/rancher/rancher/issues/11148
