### ISSUE TITLE
Upgrade from v1.6.10 to 1.6.14 wiped out load balancer port rules

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#11106]
**Rancher versions:**
rancher/server: 1.6.10 to 1.6.14
rancher/agent: 1.2.6 to 1.2.9

**Infrastructure Stack versions:**
healthcheck, ipsec, network-services , scheduler are all at default versions

**Docker version: (`docker version`,`docker info` preferred)**
```
# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
#
# docker info
Containers: 17
 Running: 14
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.517GiB
Name: ip-10-61-69-111.ap-southeast-2.compute.internal
ID: NYT6:RQUH:QUUD:QVUK:LNXI:L4HV:PTKI:WAC7:5L5Z:K56N:UCMK:SH5J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
#
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
#

# uname -r
3.10.0-693.11.6.el7.x86_64
#
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS m3.medium

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher with RDS (Aurora DB)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add a load balancer in Rancher Master v1.6.10 which has Rancher Workers (on Rancher Agent v1.2.6) and add few targets in **Port Rules**

Then upgrade the Rancher Master v1.6.14 along with Rancher Workers (now on Rancher v1.2.9).

**Results:**
The upgrade goes fine, but somehow the port rules get wiped out. See the ones which were wiped out and had to be added manually in the screenshot

![2018-01-24_10-26-00](https://user-images.githubusercontent.com/6998650/35308689-db40003e-00fc-11e8-90d2-bff80819e184.png)

**Comment by superseb** [comment]
Can you share the definitions for the loadbalancer as it was used in v1.6.10?

**Comment by vikas027** [comment]
Hey @superseb ,

Sorry, I don't have it anymore but I think this is easily reproducible. You can create some rules as I have shown in the [screenshot](https://user-images.githubusercontent.com/6998650/35308689-db40003e-00fc-11e8-90d2-bff80819e184.png) and upgrade from one version to other.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
