### ISSUE TITLE
Users with Custom Global role - "Manage All Clusters" are not able to see the members of the cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11104]
Rancher versions build on jan 23

Steps to reproduce the problem:
As admin , Create a cluster c1 and add "user1" as owner.
Create "user2" with custom role - "Manage All Clusters".
Log in as user2.
User is able to see C1. 
But he is not able to list members of C1.

**Comment by cjellick** [comment]
This is intended behavior. But will bring it up in a dicussion where we holistically reevaluate all of our auth related intended behaviors.

**Comment by deniseschannon** [comment]
This role is being removed from the global level.

**Comment by sangeethah** [comment]
"Manage All Clusters" is removed from global role level now.

The only cluster level global permission we have is "create cluster".  Users with this privilege are allowed to create clusters and assign users to them.
