### ISSUE TITLE
Dashboard Service deleted when K8 Nodes are restarted

### ISSUE THREAD

**Issue by hemanthavs** [rancher/rancher#11102]
**Rancher versions:**
rancher/server: 

Rancher | v1.6.14
-- | --
Cattle | v0.183.37
User Interface | v1.6.37
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5

rancher/agent: 

**Infrastructure Stack versions:**
healthcheck: healthcheck:v0.3.3
ipsec: /net:holder, net:v0.13.7
network-services: network-manager:v0.7.19
scheduler: 
kubernetes (if applicable): v1.8.5-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
All Nodes
Version:      1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Rancher Host::
  - CentOS Linux 7 (Core)
  - 3.10.0-693.11.6.el7.x86_64
K8 Node::
  - Ubuntu 16.04.3 LTS
  - 4.4.0-108-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Softlayer Virtual Host
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**

1. Deploy a Rancher Instance
2. Configured K8 cluster with Gluster using ( https://github.com/gluster/gluster-kubernetes )
    - First time script failed in networking issue
    - Restarted Network manager manually
    - Reran the script and Gluster is working fine with K8
3. I can access the K8 Dashboard and use K8 cluster properly
    -  I can see the Dashboard srv
      ```
      kc get svc -n kube-system                                                                                                       
      NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
      heapster               ClusterIP   10.43.15.33     <none>        80/TCP          1h
      kube-dns               ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP   1h
      kubernetes-dashboard   ClusterIP   10.43.207.26    <none>        80/TCP          1h
      monitoring-grafana     ClusterIP   10.43.194.223   <none>        80/TCP          1h
      monitoring-influxdb    ClusterIP   10.43.125.153   <none>        8086/TCP        1h
      tiller-deploy          ClusterIP   10.43.123.201   <none>        44134/TCP       1h
       ```
4. Restart all the  K8 Nodes
    - Networking not working
    - Restarted Network manager manually
    - Kubectl / Existing Application is working properly
5. No longer able to access the Dashboard
    - Reason - Restarting node deleted the dashboard Dashboard service
      ```
      kc get svc -n kube-system                                                                                                       
      NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
      heapster               ClusterIP   10.43.15.33     <none>        80/TCP          1h
      kube-dns               ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP   1h
      monitoring-grafana     ClusterIP   10.43.194.223   <none>        80/TCP          1h
      monitoring-influxdb    ClusterIP   10.43.125.153   <none>        8086/TCP        1h
      tiller-deploy          ClusterIP   10.43.123.201   <none>        44134/TCP       1h
       ```

I am suspecting DaemonSet with hostNetwork: true and privileged: true causing the Network and this issue

Issue created for Networking seperatly https://github.com/rancher/rancher/issues/10322

**Results:**

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
