### ISSUE TITLE
DYNAMIC RBAC User added to a cluster with "manage-cluster-members" is not able to modify users of the cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11116]
Rancher versions: v2.0 built on jan23

Steps to reproduce the problem:
Create a cluster c1.
Create a project P1.
Add "user1" with "manage-cluster-member" option.

Log in as user1.
Try to edit cluster c1 and add a new user to the cluster.

This fails with
```
clusters.management.cattle.io "cluster-xr7k6" is forbidden: User "user-c85lg" cannot update clusters.management.cattle.io at the cluster scope
```

The request made by UI is edit cluster for which the user does not have access to fails:
```
Request URL:https://***/v3/clusters/cluster-xr7k6
Request Method:PUT
Status Code:403 Forbidden
Remote Address:*:443
```
We should be able to decouple the edit cluster action and add/edit member to cluster action.

**Comment by westlywright** [comment]
@sangeethah i think this should be an API issue. If we want to change the way a role functions I don't think that should be happening on the front end and this seems to be a permission error coming from the API not the UI. 

cc @deniseschannon

**Comment by cjellick** [comment]
@westlywright  to be clear, the role does exactly what it states: gives the permission to CRUD members of the cluster (POST/PUT/DELETE CRTBs). But the UI throws in a PUT to the cluster to update the name/description which has nothing to do with managing members and _that_ is failing. But, I outlined a solution based on dynamic-rbac in the very similar issue:
https://github.com/rancher/rancher/issues/11105

Will keep the discussion thread in that issue

**Comment by deniseschannon** [comment]
If you update the members from the members tab of a cluster, you will be able to manage cluster membership. The reason why it doesn't work in "Edit Cluster" is because you are trying to also edit the cluster, which you don't have permissions.

**Comment by deniseschannon** [comment]
When confirming that this use case is working, we should also test CLI to ensure that this use case in this issue is also fixed: https://github.com/rancher/rancher/issues/12892
