### ISSUE TITLE
User added with "manage project" role to cluster , is allowed to add namespace to project he does not own but is not able to list it. Also not able to list namespace from other projects.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11110]
Rancher versions: v2.0 built on Jan 23

Steps to reproduce the problem:
As admin , Create a cluster with project p1 with namespace n1. 
 Add "user1" with "manage project" role .

Log in as user1.
User is able to list project P1. But he is not able to list any namespace in this project.

User is allowed to create namespace in project P1. But i not able to list this namespace he had created.

**Comment by cjellick** [comment]
Mostly intended behavior. But will bring it up in a dicussion where we holistically reevaluate all of our auth related intended behaviors.
Manage project means the ability to see, create, and delete projects, not to maniupate the resources inside of them. So not being able to list namespaces in a project is expected/intended
Being able to create NSs in other projects is basically a flaw that we new we would have except for awhile, but we can mitigate it by validating in our API (it woudl still be reproducable via kubectl)

**Comment by cjellick** [comment]
Also note that the "user is allowed to create namesapce in P1" portion of this bug is captured in https://github.com/rancher/rancher/issues/11077

**Comment by deniseschannon** [comment]
We are removing this role "Manage Projects" from the cluster role options.

**Comment by sangeethah** [comment]
There is no "manage project" custom role at the cluster level.
