### ISSUE TITLE
User added with "view projects" role to cluster , is not able list all namespaces under the projects.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11111]
Rancher versions: v2.0 built on Jan 23

Steps to reproduce the problem:
As admin , Create a cluster with project p1 with namespace n1.
Add "user1" with "view projects" role .

Log in as user1.
User is able to list project P1. But he is not able to list any namespace in this project.

Should he be allowed to list namespace as well?

**Comment by cjellick** [comment]
This is intended behavior. But will bring it up in a dicussion where we holistically reevaluate all of our auth related intended behaviors.

**Comment by deniseschannon** [comment]
We are updating so that the text says "View All Projects" and that the behavior should be able to read only all project info including project members, namespaces, workloads, etc.

**Comment by sangeethah** [comment]
Tested with latest build from master 

User added to a cluster with "View All project" is able to see all projects , namespaces and workloads in cluster.
