### ISSUE TITLE
RKE - Cluster state keeps toggling between "active" and "unavailable" when adding a node with a name that is already name of existing node in cluster. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11113]
Rancher server: v2.0 built on jan 23.

Steps to reproduce the problem:
Create RKE cluster with 3 nodes say node1(ip1),node2(ip2) and node3 (ip3).
Added another node to the cluster with node name that is already existing in the cluster , say "node3"(ip4).
Node gets added to the cluster.

Cluster state keeps toggling between "active" and "unavailable" when adding a node with a name that is already name of existing node in cluster. 

Following is the error state when node is in   "unavailable"  state:
"Not received heartbeat from cluster-agent"

In the Nodes page , I see the ip address of the newly added node , node3's ip address switching between ip3 and ip4 constantly.

Should RKE prevent a node with duplicate name to be added to the cluster?

**Comment by galal-hussein** [comment]
@sangeethah this issue has been resolved from rke's side by validating duplicate nodes, also it has been resolved from the UI side, where you can't create two nodes with the same name

**Comment by soumyalj** [comment]
Tested with master from March 2nd. UI does not allow duplicate names for nodes. Although we can have duplicate pool names, the node names are always unique
