### ISSUE TITLE
Role names in Add Cluster and Project aren't consistent

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11114]
**Rancher versions:** 2.0 master 1/23

**Steps to Reproduce:**
1.  Create a cluster and add a user
2.  Edit the cluster and add a user
3.  Do the same with project

**Results:**  Notice that the initial role is using three different names to say the same thing - Cluster Owner, cluster-owner & Owner.  Same with Member and Custom.  Please them be consistent.  Cluster Owner, Cluster Member, <Single Custom role>, or Multiple if you have more than one.  Also fix it in Project.

**Comment by westlywright** [comment]
https://github.com/rancher/ui/pull/1606

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
The person creating the cluster/project is still using different term to mean same thing.  So I have Cluster Owner or Project Owner for creator.  But just Owner for additional users.  Please make initial user also just say "Owner"

![image](https://user-images.githubusercontent.com/11514927/35585560-80fd4dd0-05b5-11e8-82d3-9a7058b52707.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
Verified fixed
