### ISSUE TITLE
Cluster Owners/Members do not get project membership permissions unless added to a project as an owner or with "manage project members" permissions

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11127]
Rancher version - 2.0 built on Jan 23

Steps to reproduce the problem:
As admin user:
1. Create a cluster1 - C1 with project P1.
2. Create a user - user1 as standard user.

Scenario1:
Add "user1" as "cluster owner" role to C1.

user1 will have the ability to delete project P1. But not have the ability to  add/delete/modify member list for project P1.

Scenario2:
Add "user1" with "Manage Projects" role to C1.

user1 will have the ability to delete project P1. But not have the ability to  add/delete/modify member list for project P1.

Scenario3:
Create user user2 with custom role - "Manage All Clusters".
User2 will have the ability to delete project P1. But not have the ability to  add/delete/modify member list for project P1.

In all above scenarios , It is more intuitive to assume that these users are given the ability to  add/delete/modify member list for project when they have ability to delete the projects.

**Comment by deniseschannon** [comment]
With the changes in how we handle adding users to clusters/projects and using `owner` or `member`, scenario 1 and 2 appeared to be fixed. Let's re-test.

I don't think Scenario 3 is valid anymore as the custom roles are clearly defined and there is a space for "managing" the users.

**Comment by soumyalj** [comment]
Tested with master from Feb 28. Scenario 1 is still not functional.
As a cluster owner, adding project members, listing project members and deleting is not functional.
<img width="614" alt="screen shot 2018-02-28 at 4 07 19 pm" src="https://user-images.githubusercontent.com/18536626/36820451-c37a3c6e-1ca2-11e8-99fa-fc5e577453ff.png">

Scenario 2 seems like it is a custom  with "Manage Projects" role. This cannot be tested at the moment as there is issue https://github.com/rancher/rancher/issues/11696

**Comment by deniseschannon** [comment]
Spoke with @cjellick and this is the current design decision.

Cluster ownership, ability to manage clusters/projects does not automatically provide permissions to manage project membership without explicitly being added to the project with these permissions.

**Comment by deniseschannon** [comment]
We will be updating so that "Custer Owners" will automatically be given permissions to manage project members. 

Cluster Members would need this permissions explicitly added as cluster members only have these perms:
```
-> Create Projects
-> View Cluster Members
-> View Nodes
-> Use Volumes
```

**Comment by sangeethah** [comment]
Tested with latest 2.0 build from master.

cluster owners now has the ability to add/remove member for the cluster.
"Manage Projects" and "Manage All Clusters" roles  are not present any more.
