### ISSUE TITLE
Add Registry page shows password unmasked in form field

### ISSUE THREAD

**Issue by ernstae** [rancher/rancher#11126]
The "Add Registry" page shows the password in cleartext within the GUI.  It probably shouldn't do that (someone might be looking over my shoulder)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha12` UI: `v2.0.16` |
|Access|`local` `admin`|
|Route|`authenticated.project.registries.new`|

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
Verified fixed
