### ISSUE TITLE
Can add custom catalog without URL

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11133]
**Rancher versions:** v2.0.0-alpha12

**Steps to Reproduce:**
1.  Click on Add Catalog
2.  Click on Create

**Results:**  Creates a Custom catalog even thou there is no URL for it to point to.  Shouldn't be able to create without URL.

**Comment by vincent99** [comment]
@loganhz Anything like this where a field should be required but isn't should be fixed in the schema, not with custom UI validation.

**Comment by loganhz** [comment]
@deniseschannon Who can I ask for to fix this issue in server side?
The url field of `/v3/schemas/catalog` should be required.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/28
Verified fixed
