### ISSUE TITLE
[Windows] Add a container to INFRASTRUCTURE and set the link, Can only link to the container on the host where the container is located.

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#11139]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent:

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 2016
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. Select a host in INFRASTRUCTURE to add a container
2. Click "Networking" -> "Add Link"
3. Click the drop-down box to select the container
**Results:**
Can only link to the container on the host where the container is located. In the drop-down box cannot display the other host's container

**Comment by orangedeng** [comment]
Located the root cause 
https://github.com/rancher/ui/blob/1.6-dev/app/mixins/container-choices.js#L89
All container links will only show up when network mode is managed.

**Comment by orangedeng** [comment]
@kingsd041 @deniseschannon I want to move it out of Feb release because it will need a big change for Windows that rename the default network from `transparent` to `managed`. It will be more consistency with Linux environment.

**Comment by deniseschannon** [comment]
@orangedeng Is there a way to update the UI so that it could know that `transparent` for Windows environments was the same as `managed` for non-windows?

**Comment by orangedeng** [comment]
We don't have a way to tell users about it. I plan for using `managed` network name instead of `transparent` in the feature release and it will be solved naturally then.
