### ISSUE TITLE
No Custom option Rancher 2.0:preview

### ISSUE THREAD

**Issue by DarkBlaez** [rancher/rancher#11136]
Currently when creating an RKE cluster there is no Custom option to use existing or baremetal servers. When looking in Node Drivers there is no option present to activate. This prevents use of existing hardware or the mechanism which was present in prior releases

Version: rancher/server:preview

DB

**Comment by superseb** [comment]
Please read the announcement on features included in tech preview 2 and what is upcoming (https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282):

```
Custom Node Support - Ability to add nodes from anywhere similar to how 1.6 custom node management worked.
```
