### ISSUE TITLE
GKE cluster showing up in Add Node drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11131]
**Rancher versions:** v2.0.0-alpha12

**Steps to Reproduce:**
1.  Create 4 gke cluster (I named the first one name1)
2.  Named all other clusters tanigkecluster1-3
3.  Went to Add Node and clicked on the Cluster drop-down

**Results:** name1 showed up in list.  It's a gke cluster and shouldn't be in list.

**Comment by loganhz** [comment]
This issue can be reproduced by entering add rke cluster page first, then click cancel and add a gke cluster.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
Verified fixed
