### ISSUE TITLE
Can create Node Driver without Download URL

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11132]
**Rancher versions:** v2.0.0-alpha12

**Steps to Reproduce:**
1.  Click on Add Node Driver
2.  Without entering any info, click on create

**Results:**  Driver creates.  Shouldn't be able to create without a download url.

**Comment by loganhz** [comment]
The url field of `/v3/schemas/machineDriver` should be required.
We need to fix it in backend by updating the schema of it.

**Comment by loganhz** [comment]
@deniseschannon Can you find someone to fix it in backend, please?

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/21
Verified fixed
