### ISSUE TITLE
Invalid command line. Found extra arguments shown when provisioning nodes with a boolean flag

### ISSUE THREAD

**Issue by marcusianlevine** [rancher/rancher#11143]
I am trying to create a cluster in preview2 with RKE on AWS, but I received the following stream of events after configuring a node with the recommended Rancher AMIs and specifying `rancher` as the SSH user.

This node is supposed to be launched into a private subnet using only the private IP address. I did not pre-create the SG, so RKE is supposed to create the `rancher-nodes` SG but that never appears either.

Initialized | True | 10:52 AM |   |  
-- | -- | -- | -- | --
Provisioned | False | 10:52 AM | Error | Invalid command line. Found extra arguments  [--amazonec2-block-duration-minutes 0 --amazonec2-device-name /dev/sda1  --amazonec2-tags  --amazonec2-spot-price 0.50 --amazonec2-ssh-user  rancher --amazonec2-instance-type m3.medium --amazonec2-keypair-name   --amazonec2-secret-key XXX  --amazonec2-session-token  --amazonec2-subnet-id subnet-75ee0458  --amazonec2-userdata  --amazonec2-access-key XXX  --amazonec2-iam-instance-profile rancher-agent --amazonec2-ssh-keypath   --amazonec2-ami ami-72613d08 --amazonec2-retries 5 --amazonec2-root-size  16 private-a]
Ready | False | 10:56 AM | Error | Invalid command line. Found extra arguments  [--amazonec2-block-duration-minutes 0 --amazonec2-device-name /dev/sda1  --amazonec2-tags  --amazonec2-spot-price 0.50 --amazonec2-ssh-user  rancher --amazonec2-instance-type m3.medium --amazonec2-keypair-name   --amazonec2-secret-key XXX  --amazonec2-session-token  --amazonec2-subnet-id subnet-75ee0458  --amazonec2-userdata  --amazonec2-access-key XXX  --amazonec2-iam-instance-profile rancher-agent --amazonec2-ssh-keypath   --amazonec2-ami ami-72613d08 --amazonec2-retries 5 --amazonec2-root-size  16 private-a]
Saved | False | 10:56 AM | Error | Timeout waiting for ssh key

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha12` UI: `v2.0.16` |
|Access|`local` `admin`|
|Route|`node`|

**Comment by LarsVonQualen** [comment]
I get the exact same thing when trying to provision nodes on DigitalOcean.

**Comment by superseb** [comment]
@LarsVonQualen You are getting AWS related errors when provisioning DO? Can you create a new issue wit the exact logging?

**Comment by superseb** [comment]
@marcusianlevine Seems to be related how we generate the commandline when there is a boolean. We don't just add the flag but add `true` as well, which breaks the command. Similar bug: https://gitlab.com/gitlab-org/gitlab-runner/issues/1104. Fix should be in next update.

**Comment by LarsVonQualen** [comment]
@superseb Just to be clear, i saw the same "Invalid command line. Found extra arguments" and "Timeout waiting for ssh key" messages, but with DigitalOcean Docker Machine arguments :)

**Comment by superseb** [comment]
@LarsVonQualen Thanks, should be the same boolean issue we fixed.

**Comment by deniseschannon** [comment]
Validated with master 02/07. Able to start a DO host with prviate networking enabled and it provisions as expected.
