### ISSUE TITLE
ERROR "Validation failed in API: nodes" when creating the 1st cluster

### ISSUE THREAD

**Issue by picoroma** [rancher/rancher#11141]
ERROR "Validation failed in API: nodes" when creating the 1st cluster
after a fresh installation on Ubuntu 16.04 HOST (hosted on AWS EC2 t2.medium)
I almost cannot do nothing...
REgards

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha12` UI: `v2.0.16` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.new.rke`|

**Comment by superseb** [comment]
Can you provide the steps you took, or attach a screenshot of the screen so we can see what you configured?

**Comment by deniseschannon** [comment]
@picoroma

Can you re-test using `rancher/server:v2.0.0-beta1`? We've made a bunch of improvements since you last tested. If you're still facing issues, please re-open a new issue.
