### ISSUE TITLE
ClusterRoles created for user created roles does not get updated when roles are modified.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11147]
Rancher versions: v2.0.0-alpha12

Steps to reproduce the problem:

1. Created a custom Role by granting access to  namespace and pod.
2. Added a standard user with this custom role to an existing project.
3. User was not able to deploy pods.  At this point , I see the "ClusterRole" associated with the "RoleBinding" to have the right resources in it but still did not work. This issue tracked in https://github.com/rancher/rancher/issues/11146
4. Edit custom Role and grant additional access to replication controller.
5. This did not result in ClusterRole to be updated with the new permissions granted.
6. Added a new user with this ClusterRole   to the same project.
7. This resulted in the  ClusterRole to be updated with the new permissions relating to Namespace being granted

After step5 , we expect the ClusterRole to be updated , so that all existing users associated with the role get the updated access rights.

**Comment by cjellick** [comment]
Note to self: cause is that the roleTemplate user controller is created as "clusterScoped", which is wrong bc roleTemplates are not a cluster scoped resource

**Comment by sangeethah** [comment]
Rancher versions: Build from latest master

Steps to reproduce the problem:

1. Created a custom Role by granting access to namespace , pod and deployment
2. Added a standard user with this custom role to an existing project.
3. User is able to deploy deployments successfully. But gets a 403 forbidden error when trying to deploy statefulset.
4. Edit the  custom Role  and granting access to statefulset as well.
5. User is now able to deploy statefulset successfully.
