### ISSUE TITLE
Websocket sends namespace update event with wrong links

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#11140]
In `rancher/server:v2.0.0-alpha12`, the websocket `/v3/clusters/${cluster-id}/subscribe` will push namespace change event with wrong `links` url.

![image](https://user-images.githubusercontent.com/21168270/35379126-0d035262-01f0-11e8-86d7-17e6fb74cabd.png)

**Comment by loganhz** [comment]
It should be `/v3/projects/cluster-6wlz4:project-9kxp5/namespaces/a` instead of `/v3/projects/cluster-6wlz4/namespaces/a`

The project id part is missing in the links.

**Comment by vincent99** [comment]
Namespaces belong to the cluster too and are unique within them.  You can list then through the cluster or a project within the cluster, but they are ultimately the same resource.

Is there a specific thing this is breaking?

**Comment by loganhz** [comment]
yes, edit action doesn’t work. It should be v3/cluster or v3/project/$cluster_id : $prject_id. But now it returns v3/project/$cluster_id

**Comment by loganhz** [comment]
The self url returns 404

**Comment by loganhz** [comment]
It still happens in `rancher/server:master` (image uuid `3bb66789dc2f`).
The self link fo `namespace` returns 400 sometimes with error message `Namespace parameter required.`

**Comment by loganhz** [comment]
@StrongMonkey can you help to check it, please?

**Comment by alena1108** [comment]
Steps to reproduce from @loganhz 

```
Step to reproduce:
1. create a cluster
2. create a project `abc`
3. create a namespace `n1` into project `Default`
4. edit namespace `n1` to update the description of it.
5. in chrome dev tool network part, if you select the websocket `subscribe?sockeid=2`, you can see two `resource.change` events. The first one is correct, but the second one is wrong.
```
@loganhz is going to workaround it for now in the UI by using the first - correct one - event.

**Comment by alena1108** [comment]
@ibuildthecloud mentioned that the problem will get fixed by the refactoring work he is doing right now.

**Comment by alena1108** [comment]
Should be fixed, could you retest @loganhz

**Comment by loganhz** [comment]
verified with 03/01 master build.
