### ISSUE TITLE
Add network policy between projects so it's defaulted to deny

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11145]
In 2.0, the networking between projects should be defaulted to not allow communication.

**Comment by sangeethah** [comment]
With latest build from master, able to verify that with canal networking , containers within the same same project ( same namespace and across different namespace) are able to ping each other using their assigned ip - 10.233.x.x but containers across different projects are not able to.

**Comment by salvob** [comment]
How can I enable communication between projects?

**Comment by mikolajkomisarek** [comment]
Anyone ? How can I enable communication between projects?

**Comment by sn0opy** [comment]
@salvob @mikolajkomisarek what I've found so far is this: https://forums.rancher.com/t/network-policies-for-projects/10231/5

Basically change the network plugin from Canal to Flannel or Calico to disable all default rules, which also means you have to configure them by yourself.
