### ISSUE TITLE
Not able to see the permissions set in "Edit Project"/"Edit Cluster"  when there are multiple permissions associated with "Custom roles"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11148]
Rancher versions: v2.0.0-alpha12

Steps to reproduce the problem:
Edit Cluster/Project and add users with Custom roles by choosing multiple permissions.
Launch Edit Cluster/Project page 
Custom roles with multiple permissions are shown as "Multple Roles"
<img width="1320" alt="screen shot 2018-01-25 at 12 33 57 pm" src="https://user-images.githubusercontent.com/4266958/35411060-340210f2-01cc-11e8-8a29-ffec7644d0e1.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
Verified fixed
