### ISSUE TITLE
Supports custom images for RKE 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#11155]
Users in China can not access `gcr.io/google_containers` without VPN.
Can we make it configable when creating a cluster via UI?

**Comment by loganhz** [comment]
@deniseschannon @vincent99 any suggestion on this?

**Comment by loganhz** [comment]
Can we use the images on dockerhub instead of gcr.io by default ? @will-chan

**Comment by tfiduccia** [comment]
Let me know when this is ready and how I can test please
