### ISSUE TITLE
Authentication Logs

### ISSUE THREAD

**Issue by Fenikkusu** [rancher/rancher#11158]
I've installed rancher on a server recently and put it behind a SSL Cert w/Local Access Controls. This all works great. I'd like to add fail2ban to the server to block anyone that tries to authenticate but fails. I'm not able to find any guides/docs indicating where invalid logins are logged at. I'm also open to alternative suggestions (IE: Perhaps Rancher has this built in?).

v1.6.14 Server on RancherOS, installed less than 2 weeks ago.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
