### ISSUE TITLE
Rancher CLI 2.0 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11164]
Rancher CLI for 2.0

**Comment by dramich** [comment]
Initial cli design:
`project ~~ environment
namespace ~~ stack

rancher login --token=12312313 --cacertDir --name=RANCHERNAME  https://server
    after login ask cluster/project and set as current
    (stretch: generate name on server side)
    
rancher project ls
SERVER CLUSTER PROJECT
rancher project create [name]
rancher project delete

rancher rm/delete [--type=foo] id

rancher switch/use [servername/[cluster/]]project
                    server/cluster
                    cluster/project
                    ask on ambiguity


rancher ps
    workloads /v3/workloads
    pods /v3/pods?workloadId_null

rancher 

rancher run
rancher auth

rancher lb/loadbalancer
rancher discovery
rancher volume
rancher cert/certificate
rancher registry
rancher secrets
rancher cluster create
    kontainer-engine args except rke --network-type
rancher node create --cluster-id=foo
   
   kontainer-engine
    embedded rke config to help generate`

**Comment by dramich** [comment]
Working on Namespace

**Comment by deniseschannon** [comment]
Closing as we introduce new commands, we'll create new issues to test. 

https://github.com/rancher/rancher/issues/11526
https://github.com/rancher/rancher/issues/11755
