### ISSUE TITLE
Add Github auth provider 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11161]

**Comment by deniseschannon** [comment]
Backend is in and ready for UI integration.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified added - bug will be entered separately from this issue.

**Comment by PhroZenOne** [comment]
@tfiduccia I am playing around with this feature and found some issues. Do you want any reports for this and if that's the case should I create separate issues? 

Issues found where: 
1. Not being able to remove users/org once added.
2. Organizations does not load properly (tried added "saiaku-gaming" ended up blank).
![bild](https://user-images.githubusercontent.com/868493/36621060-7a9f6258-18f6-11e8-9190-04e2d347a700.png)

**Comment by deniseschannon** [comment]
@PhroZenOne Can you create any new issues that you've found?
