### ISSUE TITLE
DYNAMIC RBAC to allow UI to enable/disable functionality based on your permissions

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11165]
- Hid/show collections methods (such as GET and POST) on the schema for each resource
- Hide/show update and delete links on each resource based 
- Hide/show action links on resources based on update access to that resource

gz#6027

gz#4198

**Comment by cjellick** [comment]
related:
https://github.com/rancher/rancher/issues/11116
https://github.com/rancher/rancher/issues/11105

**Comment by vincent99** [comment]
Explorer does this.
