### ISSUE TITLE
Add PingFederate Support

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11169]

**Comment by deniseschannon** [comment]
Currently, we'll be adding in support and testing using Ping Federator. For 2.0, we will be adding in specific identity providers as we test them.

**Comment by olljanat** [comment]
@deniseschannon do you mean that you will add Ping Federator, Shibboleth, ADFS, etc SAML providers separately? Can I ask that what is point on that? SAML 2.0 is standard so why not just add generic implementation?

**Comment by vincent99** [comment]
"Standard" does not mean they all use the same parts of it or the same way, so for all auth providers we are not going to advertise support for things we don't test. Variants of the same standard will share the same implementation internally unless changes are needed.

**Comment by olljanat** [comment]
IMO, you should be still able to say example that all SAML 2.0 IDPs which can provide claims X, Y and Z, which use NameID format A and which provides logout url in format B are supported.

That is at least how we have defined supported federation methods for our customers who want use SSO to our SaaS applications.

I have been working with this stuff quite lot so I can help with testing when there working implemention.

**Comment by slattery** [comment]
Thanks for adding this to the milestone!   Will there be a general use, but specific to Rancher-as-SP, profile that we could adapt our IdP entries to?

**Comment by cjellick** [comment]
I dont quite understand what you are asking @slattery, Could you elaborate?

**Comment by slattery** [comment]
Thanks @cjellick.   It may be moot or nonsense if I failed to understand the thread above.   The comment about specific identity providers makes me think that we can have SAML but only if we are running dex, or keycloak or some specific product.    I was hoping that as long as Rancher has a published SP metadata spec, then we can choose our own SAML IdP.    I understand that you can only verify certain SP/IdP combinations and not guarantee others.    Cheers!

**Comment by cjellick** [comment]
This ticket represents only supporting explicitly ping federate, though other saml providers will be much faster follow-ons. They should just be primarily framework configuration and validation of the provider.

**Comment by adingilloRancher** [comment]
Completed authentication test scenarios.
