### ISSUE TITLE
Add Logging into 2.0

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11167]
Disabled by default. Enabling will install Fluentd

[ ] Support for ability to configure cluster-wide logging of stdout/err of containers and workloads
[ ] Support for ability to configure project-wide logging of stdout/err of containers and workloads
[ ]Support for ability to configure workload logging of a specific directory
[ ] Support for following Log Targets
   [ ] Rancher embedded logging - Experimental and used for testing
   [ ]  ElasticSearch
   [ ]  Splunk
   [ ] Syslog
   [ ]  Kafka

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified added - bug will be entered separately from this issue.

**Comment by blaggacao** [comment]
[Fluent Bit!](http://fluentbit.io/documentation/current/about/fluentd_and_fluentbit.html)
