### ISSUE TITLE
Kubectl behind local authentication enabled:  serializer for text/html doesn't exist

### ISSUE THREAD

**Issue by julienTocci** [rancher/rancher#11174]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.8

**Infrastructure Stack versions:**
kubernetes (if applicable): 
`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-rancher1", GitCommit:"6cb179822b9f77893eac5612c91a0ed7c0941b45", GitTreeState:"clean", BuildDate:"2017-12-11T17:40:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
`

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.09.0-ce build afdb6d4

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 rancher Server node
1 rancher Agent node
Local access setup with 1 user on rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
kubectl is configured and can talk to rancher if Rancher does't have local access configured.
When i configure it with a user (local access), kubectl does'nt work properly and get html response from rancher server. I don't know why its happening, maybe normal behaviour but I can't find an answer.

**Results:**
Can't give whole logs but this is what i get as error with kubectl -v=10
error got 
    `\<head>
    \<meta charset="utf-8">
    \<meta http-equiv="X-UA-Compatible" content="IE=edge">
    \<meta id="viewport" name="viewport" content="width=device-width, initial-scale=1">
    \<link rel="icon" href="/assets/images/logos/favicon.ico">
    \<title>Loading&hellip;</title>
    \
    \<meta name="description" content="">
    \<base href="/" />
    \<link id = "vendor" rel="stylesheet" href="/assets/vendor.css">
    \<link id="theme" rel="stylesheet">
  \</head>
  \<body>
    \<script src="/assets/vendor-77489dadbb0709acf44882f0dde4b110.js"></script>
    \<script src="/assets/ui-6c38067a2183dfbe129e78b84f21a3a7.js"></script>
    \<div id="ember-basic-dropdown-wormhole"></div>
  \</body>
\</html>`
: invalid character < looking for beginning of value

and finally with `kubectl get nodes` :
`serializer for text/html doesn't exist`

**Comment by superseb** [comment]
With auth, https is required in the `server` parameter in `.kube/config`. Do you have this? Even without SSL termination, `rancher/server` will handle it.

**Comment by julienTocci** [comment]
Ok i changed this line to true (was false)
`insecure-skip-tls-verify: true`

The error i get now is:
`Unable to connect to the server: x509: certificate is valid for 127.0.0.1 not SOME_IP`

I am not sure, do i have to setup certifates with Let's Encrypt or i am missing something again.
Thanks for the fast answer.


Notice, this is my ~/.kube/config

`
apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    insecure-skip-tls-verify: true
    server: "https://SOME_IP/r/projects/1a36/kubernetes:6443"
  name: "Kubernetes-cluster"
contexts:
- context:
    cluster: "Kubernetes-cluster"
    user: "Kubernetes-cluster"
  name: "Kubernetes-cluster"
current-context: "Kubernetes-cluster"
users:
- name: "Kubernetes-cluster"
  user:
    token: "TOKEN"
`

**Comment by julienTocci** [comment]
Here is the config i am using (i retrieved it from the rancher UI):
`apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    insecure-skip-tls-verify: true
    server: "https://MY_IP:PORT/r/projects/1a36/kubernetes:6443"
  name: "Kubernetes-cluster"
contexts:
- context:
    cluster: "Kubernetes-cluster"
    user: "Kubernetes-cluster"
  name: "Kubernetes-cluster"
current-context: "Kubernetes-cluster"
users:
- name: "Kubernetes-cluster"
  user:
    token: "TOKEN"`

The line was false before i setup the local auth
`    insecure-skip-tls-verify: false
`
and now it's true, are you talking about this line?
I now have this 
`kubectl version`
`Unable to connect to the server: x509: certificate is valid for 127.0.0.1 not SOME_IP`

Do i have to setup some certificates with Let's encrypt ?
Thanks

**Comment by superseb** [comment]
When using the default, the certificate will be self signed and the flag must be ```insecure-skip-tls-verify: true```. You should be able to copy-paste the generated config from the UI and use that.

**Comment by superseb** [comment]
Please report back if it does not work with the kubeconfig generated in the UI.

**Comment by julienTocci** [comment]
I didn't have the time to check again this until now, I found MY error (the generated config works perfectly) it can be helpful for people so i am gonna write it down. Thanks for the responses.

My ~/.kube/config file was created by the template module with ansible and the token was created with this:

`- name: Get rancher's kubectl token to configure kubctl
  shell: "curl '{{rancher_server_container_http_url}}/v2-beta/apikeys' -H 'content-type: application/json' --data-binary '{\"type\":\"apiKey\",\"accountId\":\"1a1\",\"name\":\"kubectl\",\"description\":\"Provides workstation access to kubectl\"}' --compressed | jq -r  '.publicValue + \":\" + .secretValue' | base64 | tr /+ _- | tr -d ="
  register: kubeToken
`
I then found:
https://forums.rancher.com/t/how-to-generate-environment-api-token-for-kubernetes-1-6/6954

after some test, this is the magic formula (had a lot of error because of line break and spaces)

And added 'Basic ' for during the creation of the token
`- name: Get rancher's kubectl token to configure kubctl
 shell: "curl '{{rancher_server_container_http_url}}/v2-beta/apikeys' -u {{ lookup('file', '/home/ansible/ForgePlqybooks/roles/rancherServer/templates/accessKey') }}:{{ lookup('file', '/home/ansible/ForgePlqybooks/roles/rancherServer/templates/secretKey') }} -H 'content-type: application/json' --data-binary '{\"type\":\"apiKey\",\"accountId\":\"1a1\",\"name\":\"kubectl\",\"description\":\"Provides workstation access to kubectl\"}' --compressed | jq -r  '.publicValue + \":\" + .secretValue' | echo -n $(cat -) | base64 | echo -n $(cat -) | tr /+ _- | tr -d ' '  | echo -n Basic $(cat -) | base64 | echo -n $(cat -) | tr /+ _- | tr -d ' '  | tr -d = "
  register: kubeToken
`
giving a working token for Rancher configured with Basic auth. Everything worked perfectly after that
