### ISSUE TITLE
Rancher shows resource status as "Healthy" and "Green" when agents are not connected.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#11178]
Rancher reports all Stack/Service/Container resources as Green and Healthy when agents are in a disconnected state.  That _might_ be true, but how does rancher really know?

The real problem is that from the default screen (User Stacks) there are no visual indicators that there is something wrong with my agents. We should not hide the status of a node or service from the user. 

I look at the screen, yup everything healthy, run an upgrade and boom. This has bit me more then once in production environments.

I don't think that everything should go red and blinking. Maybe a nice soothing blue ? icon to show true status without causing undo panic.

**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
ipsec: 0.1.3
networks-services: 0.2.5
healthcheck: 0.3.0
scheduler:  0.6.3

**Docker version: (`docker version`,`docker info` preferred)**
Any

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Any

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Any

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Tested on single node, but seen in HA rancher with external DB.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle, but probably others too.

**Steps to Reproduce:**
Rancher server started, but agents are offline. 

**Results:**
![screenshot from 2018-01-26 11-18-34](https://user-images.githubusercontent.com/5324639/35452076-06a3f76e-028b-11e8-9d8d-cef131233d2b.png)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
