### ISSUE TITLE
Add Alerting into 2.0 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11170]
Disabled by default. Enabling will install Prometheus AlertManager
Support for basic out-of-box alert conditions (final list TBD)
Support for following notifiers (Slack, Email, PagerDuty, Webhooks)
Support for alert management including creating, deleting, disabling, and muting alerts
Support for out-of-box system alerts (system services, networking, etc.) that can be configured with a notifier
Support for selector labels on cluster and project-wide resources (pod, nodes, etc.)
Support for “Test” notifier feature
No support for “management” plane alerts (i.e Cluster 1 went down)

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified added - bug will be entered separately from this issue.
