### ISSUE TITLE
No longer authenticated and tried to add host label

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1118]
v0.23.0-rc6

Steps to Reproduce:
1. Start Rancher server and leave in browser until authentication has been timed out (not sure how long we stay logged in for)
2. Try to add a host label

Result:
Unauthorized error displayed when trying to save label.

Expected Result:
If I'm logged out, then it should force me to authenticate so I know the error.

**Comment by hibooboo2** [comment]
16 hours is the timeout for logins.

**Comment by hibooboo2** [comment]
This can be changed with a setting in cattle "api.auth.jwt.token.expiry=57600000" change to a number you see fit.

**Comment by deniseschannon** [comment]
No longer seeing this as an issue.
