### ISSUE TITLE
Need flag for APIKeys so we can hide the UI Session key, also need activate/deactivate actions

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11182]
**Rancher versions:** v2.0.0-alpha12

**Steps to Reproduce:**
1.  Go to API Keys
2.  Create a key

**Results:**  
- [x]  There is a UI Session key there.  If a user deletes it, it will break 2.0.  We need a flag in API so we can hide the key.  
![image](https://user-images.githubusercontent.com/11514927/35456377-74f4f7ac-0292-11e8-869e-f709bc45f366.png)
- [x]  Moved out into a new ticked: https://github.com/rancher/rancher/issues/15293
~~Also notice there is no Activate/Deactivate actions for the key.  We should support these actions.
![image](https://user-images.githubusercontent.com/11514927/35456554-259634b8-0293-11e8-9c40-5b136b808f22.png)~~

**Comment by cjellick** [comment]
The flag is `isDerived`. True indicates that this was not a login token

**Comment by cjellick** [comment]
Assigning to @vincent99 for UI developer routing

**Comment by vincent99** [comment]
@cjellick Not sure that's the same thing; What I'd like to know is if the token is _the current_ session authorizing the request, so that one can be hidden and doesn't get killed if you do e.g. select all/delete.

**Comment by cjellick** [comment]
lets call the new field "current"

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/19
Verified fixed
