### ISSUE TITLE
Can bypass change password first time logging in

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11186]
**Rancher versions:** v2.0.0-alpha12

**Steps to Reproduce:**
1.  Create a new rancher setup
2.  Go to login screen and put admin for username/password
3.  When change password screen comes up, go to URL and remove the /login and refresh

**Results:**  Takes you into Rancher on the cluster page.

**Comment by vincent99** [comment]
Changed the wording to "Ask", this can't _really_ be enforced without complicated backend checking.  You have to be actually logged in to make the call to change the password, and that token can do whatever the user has access to.  And nothing prevents you from changing the password from A -> B -> A.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/30
Verified fixed
