### ISSUE TITLE
Remember username, default to generating a random password on first login

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#11184]
- Remember username on login:

![image](https://user-images.githubusercontent.com/753917/35460468-ff43d990-0298-11e8-8d6e-af4709a8c948.png)

- Default to generating random password:

![image](https://user-images.githubusercontent.com/753917/35460563-55d2c1b8-0299-11e8-8bcd-6fc949db010c.png)

Separately, the backend will require you to change the password to something not the same (again) soon, and will provide a way for the UI to know that this is a new install so that it can bring you straight to setting the password.

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/29
Verified fixed
