### ISSUE TITLE
Add PublicEndpoints propagation to Node/Service/Pod

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11181]
Similar to Rancher 1.6, we have to save public endpoints on per 

- [ ] node level, HostPort and NodeIP Service
- [ ] pod level, only for HostPort
- [ ] service level, but only for NodeIP service

PublicEndpoint object struct:

```
type PublicEndpoint struct {
	nodeName string
	nodeIP   string
	port     int32
	protocol string
        namespace string
	// for nodeport service
	serviceName string
	// for host port on pod
	podName string
	//serviceName and podName are mutually exclusive
}
```

**Comment by deniseschannon** [comment]
Over to UI for implementation. @loganhz
