### ISSUE TITLE
How to use a custom mirror warehouse address?

### ISSUE THREAD

**Issue by flyskyz** [rancher/rancher#11198]
How did I solve this problem when I was using pipeline to build project push mirrors to a custom warehouse?

---
The registryindex.docker.io haven't been authenticated, click here to authenticate it.
![qq 20180129105848](https://user-images.githubusercontent.com/3203054/35491749-6be04b82-04e3-11e8-8033-50f33e02fe02.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.settings`|

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
