### ISSUE TITLE
Force LowerCase for Cluster-Name on kubeconfig import

### ISSUE THREAD

**Issue by Geo719** [rancher/rancher#11196]
**Rancher versions:**
rancher/server: 2.0.0-alpha12

Importing a kubeconfig file fails if cluster name has upper case letters ("Test")

An API error is given which does point to the error, but does not make it clear its not an error of the .yml (atlast for me)

Either force lowercase in Frontend, convert to lowercase or regex field to test for compliance.

**Comment by deniseschannon** [comment]
For Beta, we're moving from importing existing kube-configs to being able to use a `kubectl apply` command on your k8s cluster, which would make the UX simpler for users.
