### ISSUE TITLE
Need support cn-northwest region at AWS

### ISSUE THREAD

**Issue by phirov** [rancher/rancher#11192]
**Rancher versions:**
rancher/server: v2.0.0-alpha12

can not support cn-northwest-1 region at AWS

**Comment by loganhz** [comment]
cn-northwest-1  is supported now

**Comment by loganhz** [comment]
We need to update docker-machine to `0.15` from `0.14` to support `cn-northwest-1`.

**Comment by deniseschannon** [comment]
@loganhz rancher is updated to `machine v0.15.0`, can you add that region to the list in the UI?

**Comment by loganhz** [comment]
It’s already in. I guess we can close it now.

**Comment by guangbochen** [comment]
Verified fixed and close it. master 07/25.
![image](https://user-images.githubusercontent.com/4569037/43175293-f37a0658-8ff0-11e8-9a05-9c4bea536853.png)
