### ISSUE TITLE
Can't enable and use local auth

### ISSUE THREAD

**Issue by nwalke** [rancher/rancher#11199]
**Rancher versions:**
rancher/server: 1.6.13 and 1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.1.3
ID=rancheros
ID_LIKE=
VERSION_ID=v1.1.3
PRETTY_NAME="RancherOS v1.1.3"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Linode

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node, just ran `docker run -d --restart=unless-stopped --name=rancher-server -p 8080:8080 rancher/server`

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Default is Cattle from the command above I believe

**Steps to Reproduce:**
Watch the gif here: https://imgur.com/pXTB87V
Note that I haven't done anything other than click "Okay" on the box that asks if I want to submit usage details.  I went straight from there to the access control page.

**Results:**
I am unable to log in to Rancher after it telling me local authentication was enabled.  There's nothing fun in the logs either, but here they are if you want to look: https://gist.github.com/nwalke/842ca293d3e7d77c3d15239075c99d51

That server is gone so don't care about the keys showing up in the logs there.  

What am I doing wrong?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
