### ISSUE TITLE
Scheduling Logic Flaw

### ISSUE THREAD

**Issue by stobias123** [rancher/rancher#11190]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
```
rancher/storage-nfs:v0.8.5
rancher/storage-ebs:v0.8.1
rancher/net:v0.11.7
rancher/dns:v0.15.1
rancher/net:holder
rancher/metadata:v0.9.3
rancher/net:v0.11.7
rancher/network-manager:v0.7.7
rancher/agent:v1.2.5
```
**Docker version: (`docker version`,`docker info` preferred)**
```
# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
root@system:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@system:~# uname -r
4.4.0-1044-aws
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 

**Steps to Reproduce:**
Schedule a service with an EBS volume. Then upgrade the service with new **HARD** affinity labels.  

**Results:**
Cattle will schedule the container back where the EBS was last mounted, rather than where matching container affinity labels exist.

I would think that affinity labels for containers should take precedence over almost any other scheduling logic, especially when using a hard label..

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
