### ISSUE TITLE
Can Rancher Manage HAProxy Reverse Proxy/Load Balancer from UI

### ISSUE THREAD

**Issue by c0fe** [rancher/rancher#11209]
I was reading this documentation:

http://rancher.com/docs/rancher/v1.2/en/cattle/adding-load-balancers/

But I am confused as to whether Rancher provides capabilities to manage a reverse proxy/load balancer for a particular group of containers.

For example, if I am running:

Docker Program A
Docker Program B
Docker Program C

Each one having their own domain attached, does Rancher provide support for this?

**Comment by superseb** [comment]
Yes, please check the latest docs here for defining service rules to map a domain to a service: http://rancher.com/docs/rancher/latest/en/cattle/adding-load-balancers/#request-hostpath

Let me know if you have any other questions on this.

**Comment by c0fe** [comment]
@superseb is this a text or is it managed through the GUI?

Also is there a tutorial on how to get this working with HAProxy?

**Comment by superseb** [comment]
This explains how to add it through the UI: http://rancher.com/docs/rancher/latest/en/cattle/adding-load-balancers/#load-balancer-options-in-the-ui

This is the description for using the CLI: http://rancher.com/docs/rancher/latest/en/cattle/adding-load-balancers/#adding-a-load-balancer-with-rancher-compose

The loadbalancer that is mentioned and included within Rancher is based on HAProxy.
