### ISSUE TITLE
New Installation and Rancher UI is not accessible

### ISSUE THREAD

**Issue by c0fe** [rancher/rancher#11207]
**OS:** Ubuntu 16.04 LTS
**Environment:** Fresh Install/VirtualBox
**Docker Version:** Docker Community Edition (docker-ce)
**Commands Entered:**
```
-apt-get install docker-ce -y
-systemctl enable docker
-systemctl start docker
-docker run -d --name rancher --restart=unless-stopped -p 8080:8080 rancher/server:stable
```
**Problem:**

The UI is not accessible after the container is running. If I go <IP OF ADDRESS>:8080 I get an error "Connection Refused"

**Comment by superseb** [comment]
- Is the container running? (`docker ps`)
- Are you hitting the IP of the machine in VirtualBox?
- Does `curl http://localhost:8080/ping` work? (should respond pong)

**Comment by c0fe** [comment]
@superseb oddly enough it is now running and I gained access.

It looks like for whatever reason there is a delay in deployment, from the time the docker runs to where I can access the UI, appears to be about 16 minutes.

**Comment by vincent99** [comment]
Startup is under a minute with a  fast SSD, and down from there with spinning disks or maybe I/o in virtualbox is slow.
