### ISSUE TITLE
Wrong service in load balancer when use rules for wildcard and root domain

### ISSUE THREAD

**Issue by morrizon** [rancher/rancher#11201]
Component | Version
-- | --
Rancher | v1.6.0
Cattle | v0.179.7
User Interface | v1.6.1
Rancher CLI | v0.6.0
Rancher Compose | v0.12.5

**Steps to Reproduce:**

Make the following service rules in the load balancer:

Access | Protocol | Request Host | Port | Path | Target* | Port*
-- | -- | -- | -- | -- | -- | --
public | HTTP | *.example.com | 80 | | web1 | 80
public | HTTP | example.com | 80 | | web2 | 80

**Results:**

Requests to www.example.com or example.com will be use the first defined service, in the current example will be web1. I think the problem is how the rules for HAProxy are made:

```
backend 80_example_com_
  acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
  acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
      http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
      http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_proto
  mode http
  server 65b035694c0e22db7858c3a9d7eb7e4b2982df5d 10.42.37.127:80

 acl 80_example_com__host hdr_end(host) -i .example.com
  acl 80_example_com__host hdr_end(host) -i .example.com:80
  use_backend 80_example_com_ if 80_example_com__host

 acl 80_example_com__host hdr(host) -i example.com
  acl 80_example_com__host hdr(host) -i example.com:80
  use_backend 80_example_com_ if 80_example_com__host
```

There is only a backend definition instead of 2 and both case use the same backend. Maybe the problem is that the name conventions for the wildcard case match with the root domain case.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
