### ISSUE TITLE
Adding host gets stucked in "Provisioning with ubuntu(systemd)

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#11203]
**Rancher versions:**
- rancher/server: 1.6.14
- rancher/agent: 1.2.7

**Infrastructure Stack versions:**
- healthcheck: v0.3.3
- ipsec:v0.13.5
- network-services:
- rancher/metadata:v0.9.5
- rancher/network-manager:v0.7.18
- scheduler:v0.8.2
- kubernetes (if applicable): rancher/k8s:v1.8.3

**Docker version: (`docker version`,`docker info` preferred)**
```bash
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1049-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-10-0-1-38
ID: 3NGX:SYKA:NDIT:MZDZ:7FDX:XN5J:4E5O:25CO:XHRI:WOEC:SATK:63ZT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false



WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ uname -r
4.4.0-1043-aws

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS - using `t2.small` instance for the Server.
The Rancher server is behind a classic ELB with SSL termination (on the ELB)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- 1 Rancher Server
- 1 Rancher Node
- External db (RDS instance)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Add a host to a Cattle environment
2. When adding hosts to the respective infrastructure, select the proposed (`rancher-machine`) security group for them

**Results:**
Process stucks in 

> Provisioning with ubuntu(systemd)...

**Comment by superseb** [comment]
Your `docker info` displays `4.4.0-1049-aws` but the `uname -r` displays `4.4.0-1043-aws`. Can you share what AMI ID you are specifying when adding a node?

**Comment by superseb** [comment]
Please report back so we can investigate.

**Comment by namehta** [comment]
I'm seeing the same issue that occurs only when trying to add a host with a private IP. Using ami-d15a75c7. Does not occur when using a public IP.

**Comment by rflume** [comment]
This issue 

> I'm seeing the same issue that occurs only when trying to add a host with a private IP. Using ami-d15a75c7. Does not occur when using a public IP.

Me too. Rancher and provisioning nodes are in same subnet but cluster nodes won't provision further than "Provisioning with ubuntu(systemd)" with only private IP addresses

**Comment by shitalp** [comment]
Hey guys u have any idea... i am seeing the same issue.

**Comment by Caldas** [comment]
@superseb please re-open this issue.

The main problem here as described by @rflume, @namehta and @shitalp is `cluster creation stuck when using Private IP only` using **EC2** cluster.

I'm also facing the same issue and I really need to use only private IP for those instances. Please @superseb re-open so we can try to reach to a solution.

**Comment by Caldas** [comment]
Hey @rflume, @namehta, and @shitalp again

reading more at the internet I found https://forums.rancher.com/t/add-clone-ec2-host-whit-no-public-ip/6657/2 where a `Rancher Labs` guy explain:
![image](https://user-images.githubusercontent.com/938045/80645652-cde3ff00-8a41-11ea-9d54-2d33b4fbc91c.png)

In my case this option `b` is the problem why my environment stucked (since I was using 3 subnets).

I hope this can help you guys !!

**Comment by kisulken** [comment]
Same here. Stuck on `Provisioning with ubuntu(systemd)...`
Ubuntu 18.04
