### ISSUE TITLE
Unable to import GKE cluster

### ISSUE THREAD

**Issue by s4rd1nh4** [rancher/rancher#11208]
**Rancher versions:**
rancher/server:preview
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.8.6-gke.0

**Docker version: (`docker version`,`docker info` preferred)**
17.05.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Import GKE Cluster

**Results:**
``
Post https://xxx.xxx.xxx/api/v1/namespaces/default/serviceaccounts: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output=
``
--

**Comment by vincent99** [comment]
The config GKE constructs contains commands to run for it to get the secrets instead of the actual secrets.  So that only works on your workstation.

An upcoming release will go back to defaulting to showing a `kubectl apply ...` command to run on the cluster to import it, which will work in this situation.

**Comment by deniseschannon** [comment]
For Beta, we're moving from importing existing kube-configs to being able to use a kubectl apply command on your k8s cluster, which would make the UX simpler for users.
