### ISSUE TITLE
RKE cluster using custom doesn't return Node name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11218]
**Rancher versions:** 2.0 master 1/29

**Steps to Reproduce:**
1.  Create RKE Cluster
2.  Add Nodes
3.  Select Custom
4.  Fill out all info including name

**Results:**  The UI post is sending the node name, but the response does not have that.  So the node name is showing up as random letter with parens around it.
![image](https://user-images.githubusercontent.com/11514927/35541169-aac8a758-0516-11e8-8e67-7c1d7456bd40.png)

**Comment by deniseschannon** [comment]
Fixed in master build 02/07 12pm
