### ISSUE TITLE
RKE Cluster with Custom doesn't validate any information

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11216]
**Rancher versions:** 2.0 master 1/29

**Steps to Reproduce:**
1.  Create a Digital Ocean machine
2.  Create a RKE cluster and click on Add a new node
3.  Select Custom for nodes
4.  Fill out Custom section but put invalid hostname, ssh username & ssh private key info

**Results:**  Cluster starts creation and add nodes that don't exist, giving the impression that it's actually working.  We should do some validation before we allow them to leave the Add node pages.

**Comment by tfiduccia** [comment]
We still are not validating any info - not sure how much info we can validate but we should do at least some.

**Comment by deniseschannon** [comment]
We're no longer supporting being able to provide SSH details to add nodes into rancher. We will only be supporting `docker run` to add in nodes for 2.0. 

Also, the workflow for provisioning is changing, so not sure if this will be relevant.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/20
Verified fixed
