### ISSUE TITLE
Change Password UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11214]
**Rancher versions:** 2.0 master 1/29

**Results:**

- [x] Current Password is a required field so add * to the field

- [ ] No password in field error message should say "Current Password required" and should be left justified.
![image](https://user-images.githubusercontent.com/11514927/35537554-d95771d0-0507-11e8-8783-7d5fc654d412.png)

- [ ] Incorrect password error message should be "Invalid Current Password" (Capitalize the first letter of each word) and should be left justified
![image](https://user-images.githubusercontent.com/11514927/35537624-1d08e486-0508-11e8-89f4-3f6cc375a4bd.png)

- [x] Random generator field and copy to clipboard button should be left justified or something?

- [x] I'm not a fan of random generator being default or the flippy thing back and forth when I select the radio buttons.

**Comment by vincent99** [comment]
Error messages are from the API.  @cjellick will add unique `codes` to key translations off of.

**Comment by deniseschannon** [comment]
Copied the remaining open issues into #12752
