### ISSUE TITLE
Edit/Upgrade load balancer with a HostIP, causes HostIP to be removed on 1.6

### ISSUE THREAD

**Issue by linkvt** [rancher/rancher#11223]
**Rancher versions:**
rancher/server: 1.6.12

**Steps to Reproduce:**
1. Create a load balancer with a hostip
2. Edit/Upgrade load balancer

**Results:** Notice the hostip is no longer visible. If you click the link for it to show up again, you will also notice that it's blank.

**Expected:** HostIP should show up on edit/upgrade.

**Notes:**
Despite being fixed in #7288 for 2.0, it is still broken in 1.6 and the original issue received no further replies.
I know the works for Rancher 2.0 have high priority, but the [documentation](http://rancher.com/support-maintenance-terms/) says 1.6 will get full support till end of 2018 and me and a few others would really appreciate this bugfix.

When balancing an SSH port from another IP this bug gets really annoying, because after updating the load balancer without the host IP the SSH access to the VM will stop working - because it's routed to a container.

I have domain A to connect to my VM.
I have domain B with another IP address on that VM which I want to use to connect to my Gitea without having to use a non-default SSH port.
This is my use case with using an SCM plattform which I want to with a separate domain and ip without using a non-default SSH port.

Thanks in advance.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
