### ISSUE TITLE
[Rancher 2.0/RKE] Create a 11 nodes cluster took more than 30 minutes 

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#11222]
Used RKE with AWS hosts (T2.medium with Ubuntu images), created 11 nodes (1 as etcd and mangement, other 10 as worker). It took more than 30 minutes until the cluster showed active status. Is it normal? Based on server log, it seems the reconciling cluster action repeated for a long time.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `preview` UI: `v2.0.16` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by vincent99** [comment]
Everything is currently done in serial so the time it takes is proportional to the number of nodes, how fast pulling from dockerhub is, and how fast the nodes' cpu/disk are. 
 More of it will be done in parallel soon, please follow https://github.com/rancher/rke/issues/261
