### ISSUE TITLE
containers with managed network  can not connect ui shell

### ISSUE THREAD

**Issue by shykingu** [rancher/rancher#11221]
*Describe your issue here*

containers with managed network  can not connect ui shell
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`service.new`|

**Comment by superseb** [comment]
We need some more info here. Can you share the logs from the `rancher-agent` container where the container is running on? Can you run a shell from the command line? (`docker exec -ti container_id bash`)

**Comment by riyasoni42** [comment]
$ docker exec -it cli bash
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
