### ISSUE TITLE
Setting up Kubernetes failed

### ISSUE THREAD

**Issue by lovelivestyle1102** [rancher/rancher#11238]
**Rancher versions:**
rancher/server: latest
rancher/agent: latest

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: 17.12.0-ce

**Operating system and kernel: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: VirtualBox

**Setup details: single node rancher

**Environment Template: Kubernetes

**Steps to Reproduce:
    Setting up Kubernetes

**Results:
time="2018-01-31T04:57:24Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
time="2018-01-31T04:57:24Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
time="2018-01-31T04:57:24Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
2018-01-31 04:57:44,538 ERROR [e70b0f37-f977-4012-ac09-d74f51712821:131] [agent:1] [agent.activate->(MetadataProcessHandler)] [] [cutorService-13] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for registeredAgent:1 
2018-01-31 04:57:44,805 ERROR [3946a398-13cb-46c1-920e-7d23bcd65037:133] [agent:2] [agent.activate->(MetadataProcessHandler)] [] [ecutorService-1] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for registeredAgent:2 
time="2018-01-31T04:57:49Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
time="2018-01-31T04:57:55Z" level=info msg="Creating Machine" eventId=7dd18215-8e3c-453a-b325-60d3ee8bfe3d resourceId=1ph1 service=gms 
time="2018-01-31T04:57:55Z" level=info msg="Activating Machine" eventId=a0aeb89e-996f-4835-bf7e-c375159aca26 resourceId=1ph1 service=gms 
time="2018-01-31T04:57:56Z" level=info msg="Handling backend connection request." 
time="2018-01-31T04:57:56Z" level=info msg="Registering backend for host 48019b15-dc23-43dc-679f-dad8aafaff16 with session ID 9f301f5e-de3f-4e67-b817-75b1ff62dc96." 
time="2018-01-31T04:57:56Z" level=info msg="Creating Machine" eventId=c82d32d2-9ebe-4d07-9071-beeb738331e5 resourceId=1ph2 service=gms 
time="2018-01-31T04:57:56Z" level=info msg="Activating Machine" eventId=b6cda648-8ca5-4711-a01c-ae938444ef9d resourceId=1ph2 service=gms 
time="2018-01-31T04:57:57Z" level=info msg="Handling backend connection request." 
time="2018-01-31T04:57:57Z" level=info msg="Registering backend for host 3cbc8c92-2d9c-43f3-4091-bc40caa2e298 with session ID 5420d581-0147-4cd5-8773-1266117cd4e0." 
2018-01-31 04:57:58,523 ERROR [:] [] [] [] [ecutorService-4] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataChangedException: Database record has been changed
	at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:550)

**Comment by superseb** [comment]
How many hosts are you adding to the setup and what are the specs? Are the infrastructure services coming up? If so,  you can check the `kubelet` logs for more info.

**Comment by lovelivestyle1102** [comment]
I add two hosts to space, if I don't add kubernetes environment, it works.
But when I add kubernetes it will don't work.I guess it maybe some infrastructure doesn't start completely. But pull docker image from the hub.

**Comment by superseb** [comment]
There are more resources needed for running Kubernetes as it runs more containers. What are the specs of the hosts you are adding?

**Comment by lovelivestyle1102** [comment]
I add a centos7 from virtualbox

**Comment by superseb** [comment]
Specs was meant for in terms CPU/memory. Let me know if you still run into trouble.
