### ISSUE TITLE
Create mapping of k8s version and other images 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11231]
As RKE relies on other images (e.g. `etcd`) to deploy successfully, we want to be able to pin a specific version of k8s to a specific version of these other images. 

We should create a map of k8s version to these other images.

**Comment by alena1108** [comment]
https://github.com/rancher/rke/issues/287

**Comment by deniseschannon** [comment]
Available for UI to incorporate into Rancher

**Comment by vincent99** [comment]
This was put in a while ago, but there's only one version right now..

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/2
Verified fixed
