### ISSUE TITLE
Append private registry to default image in Rancher code

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11232]
The flow:

* UI passes images w/o repo (dockerhub by default) + private registry (optional)
* if private registry is not empty, attach the registry to every image

**Comment by deniseschannon** [comment]
Available for UI to incorporate into Rancher

**Comment by vincent99** [comment]
![image](https://user-images.githubusercontent.com/753917/36919870-02e3ea60-1e1c-11e8-87d6-dc633035b4cb.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/2
Verified added.
