### ISSUE TITLE
RancherUI,Can't add USER to Env and form validate err

### ISSUE THREAD

**Issue by shang7053** [rancher/rancher#11239]
**Rancher versions:**
rancher/server:1.6.14
rancher/agent:1.2.9

**Infrastructure Stack versions:**
healthcheck:0.3.3
ipsec:0.13.7
network-services:0.9.5
scheduler:0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
beside the point
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
beside the point
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
beside the point
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
beside the point
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
ERR01
**Steps to Reproduce:**
ALL Name input ! if i fill with chinese,RancherUI will report me error,when I del it and fill english,it still report me error!
**Results:**
report me error

ERR02
**Steps to Reproduce:**
* enable access control
* add user test
* into Manage Environments
* click button Add Environment
* in Access Control area
* fill test and click +
* report Identity not found: test
**Results:**
report Identity not found: test
ALL user unless root can't login
but when the new user is admin role,all will be ok,please tell me if all user need set to admin role?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
