### ISSUE TITLE
docker-machine generic driver not working

### ISSUE THREAD

**Issue by kerk1v** [rancher/rancher#11241]
*Unable to add bare-metal nodes to an rke cluster*

Hello, 

It seems currently the generic docker-machine driver is broken. 

It does not allow to enter any info for a pre-existing node, and also does not show any control to confirm data, so those of us who don't run one of the supported providers, or bare metal can't use Rancher to spin up a new RKE kubernetes cluster

(I am using rke natively, which works very well indeed, but it would be nice to have that integrated)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha12` UI: `v2.0.16` |
|Access|`local` `admin`|
|Route|`global-admin.machine-drivers`|

**Comment by superseb** [comment]
This is described as upcoming feature in the announcement (https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2):

```Custom Node Support - Ability to add nodes from anywhere similar to how 1.6 custom node management worked.```

And we have https://github.com/rancher/rancher/issues/10873 open for custom machine drivers.
