### ISSUE TITLE
Dark theme issue 2.0

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11247]
**Rancher versions:** 2.0 master 1/31

**Results:**

- [x] Preferences - Line separating username and preferences is too dark and you can't see it.
![image](https://user-images.githubusercontent.com/11514927/35639141-71b9aafa-0676-11e8-9253-73a68da3ac23.png)

- [x] API Key created modal - copy to clipboard color is light blue and you can barely see it against the dark grey background
![image](https://user-images.githubusercontent.com/11514927/35639199-aa5410da-0676-11e8-8593-b47c9d6fb9a2.png)

- [x] Lines in item menu are dark black and you can't see them
![image](https://user-images.githubusercontent.com/11514927/35639257-e33b37ac-0676-11e8-87f6-95974b558345.png)

- [x] In edit, field you can't modify are not showing up as fields?
![image](https://user-images.githubusercontent.com/11514927/35639644-15067b9c-0678-11e8-9590-3bb5ce68b01f.png)

- [x] Custom role modal in Add/Edit Cluster/Project needs to be fixed
![image](https://user-images.githubusercontent.com/11514927/35639776-909882fa-0678-11e8-9d04-4e72836d45fd.png)

**Comment by lvuch** [comment]
@tfiduccia the edit view name is styled that way to indicate that is not editable in any way. If we had a disabled field around it it'd suggest that there would be a way to edit it.

**Comment by tfiduccia** [comment]
Last issue still needs fixing.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/2
Verified fixed
