### ISSUE TITLE
Can not use AWS for RKE add cluster

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#11248]
**Rancher versions:**
rancher/server:master

**Steps to Reproduce:**
1. Run the command  `docker run -itd  -p 8443:443 -p 8080:80 rancher/server:master`
2. login and add cluster , choose RKE
3. click "add a new node", choose AWS, after fill in all the input, click "Next"
4. UI displays error message "XMLParserError: error on line 1 at column 1: Document is empty"

![image](https://user-images.githubusercontent.com/1213386/35641245-de65f964-067c-11e8-9b37-7d6ed0a86a29.png)

![image](https://user-images.githubusercontent.com/1213386/35641261-e834d85c-067c-11e8-83a3-2d50f5a72df8.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/1
Verified fixed
