### ISSUE TITLE
When I refresh the screen the search field is off the page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11245]
**Rancher versions:** 2.0 master 1/31

**Steps to Reproduce:**
1.  Log into rancher
2.  Refresh the browser (try a couple of time if it doesn't do it first time

**Results:**  the search field for clusters is way off the page and to the right.  You can tell because a scrollbar appears on the bottom.  Scroll all the way to the right and you will see the search field.
![image](https://user-images.githubusercontent.com/11514927/35639015-03e993dc-0676-11e8-989a-cd61a65e3586.png)
![image](https://user-images.githubusercontent.com/11514927/35639043-25fd74a2-0676-11e8-8158-12905cc87a7e.png)

**Comment by loganhz** [comment]
Hi @tfiduccia , do you still see this issue in current version? I can not recreate this issue.

**Comment by deniseschannon** [comment]
@tfiduccia can you try reproducing?

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/27
I can no longer reproduce.
