### ISSUE TITLE
Can't add member from Project security/member page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11259]
**Rancher versions:** 2.0 master 1/31

**Steps:**
1.  Create a cluster/project
2.  Go to project
3.  Go to Security/Members
4.  Click on Add Member
5.  Select a user and click on Create

**Results:** Error saying "Please select a user."
![image](https://user-images.githubusercontent.com/11514927/35654955-c2e3fc4c-06ac-11e8-98d9-25096b9175be.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/1
Verified fixed

**Comment by rondlite** [comment]
I am having this issue on version `2.4.8`
