### ISSUE TITLE
Rancher CLI initial commands

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#11279]
`login`
`clusters` `list` `import` `get-command`
`projects` `list` `create`
`ps`
`kubectl`

**Comment by deniseschannon** [comment]
Available with CLI: `v1.0.0-alpha5`

**Comment by sangeethah** [comment]
Tested with cli version - v1.0.0-alpha5 for initial set of commands that are available.
Bugs are logged for issues found  during testing.
