### ISSUE TITLE
Deploying a workload, gives me 3 instead of 1

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11272]
**Rancher versions:** 2.0 master 2/1

**Steps to Reproduce:**
1.  Create a cluster
2.  Go to Project and deploy a single pod or a workload

**Results:**  Gives me three items in the list instead of 1
![image](https://user-images.githubusercontent.com/11514927/35707338-90c7a6cc-0766-11e8-9812-5963d81f830a.png)

**Comment by deniseschannon** [comment]
Workloads is being refactored, so will be fixed during the refactor.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/20
Verified fixed
