### ISSUE TITLE
Attempting to access resources from a project that user does not have access to should result in API failing with "Unauthorized" error code.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1127]
Server version - build from master jun/09

Github user test1 belongs to github group - g1.

Add g1 as member to Default environment.
Create env1. 
Create env2 and add g1 as member.

Create API keys for a github user account - test1.

Using this apikey , try to access project ev1( which user has no access to) using  /v1/projects/env1id. 
API returns 404 
{
"id": "88ad188a-e302-4117-a66e-185923ac8ca0",
"type": "error",
"links": { },
"actions": { },
"status": 404,
"code": "Not Found",
"message": "Not Found",
"detail": null,
}
Using this apikey , try to access any resource from project env1 using /v1/projects/env1id/containers.
API returns 500 Internal server error:

{
"id": "4eb14925-f0f2-4291-8258-21f32a71998e",
"type": "error",
"links": { },
"actions": { },
"status": 500,
"code": "Internal Server Error",
"message": "Internal Server Error",
"detail": null,
}

**Comment by hibooboo2** [comment]
This has been fixed on master.

**Comment by sangeethah** [comment]
Tested with server version - V0.24.0-rc1

scenario 1:
Using user apikey , try to access a project which the user has no access to using /v1/projects/env1id. 
API still returns 404 

scenario 2:

Using this apikey , try to access any resource from a project that user does not have access to using /v1/projects/env1id/containers.
API returns 403 Forbidden error as expected:

{
"id": "bd3d91de-5b11-40c4-af7e-9293a5b614fe",
"type": "error",
"links": { },
"actions": { },
"status": 403,
"code": "Forbidden",
"message": "Forbidden",
"detail": null,
}

Reopening this issue to fix scenario 1 to return 403 as well.

**Comment by vincent99** [comment]
Either 404 or 403 would be fine here, but it should be consistent.

The more important thing to check is that you get the same error response whether the request is for an actual or non-existent collection name, resource id, filter/include/sort/pagination params, etc.  Not a slightly different response if that id actually exists vs it doesn't.  There probably shouldn't be more than one spot in the code that handles this.

**Comment by hibooboo2** [comment]
The behavior her is as expected. 403 forbidden when trying to auth as a project you can't is expected. error 404 when listing a project is expected as you have no access but you shouldn't be told the project exists.

**Comment by vincent99** [comment]
This is not "as expected".  It's returning different status codes depending on the URL hit and trivially tells me whether the project exists or not.

With a (project) API Key:
`/v1/projects/:has_access`: 200
`/v1/projects/:no_access/`: 404
`/v1/projects/:no_access/containers`: 403
`/v1/projects/:no_access/non_existent_collection`: 403
`/v1/projects/:non_existent/`: 404
`/v1/projects/:non_existent/containers`: 500
`/v1/projects/:non_existent/non_existent_collection`: 500

All of these (except the first) should be 403.

Exercise for the reader/tests: repeat with user API key, as admin, with a token, etc.

**Comment by hibooboo2** [comment]
`/v1/projects/:has_access/`: 200
`/v1/projects/:no_access/`: 404
`/v1/projects/:no_access/containers`: 403
`/v1/projects/:no_access/non_existent_collection`: 403
`/v1/projects/:non_existent/`: 404
`/v1/projects/:non_existent/containers`: 403
`/v1/projects/:non_existent/non_existent_collection`: 403

Is the desired outcomes as per the discussion we had a month or two ago. if that has changed between you and @ibuildthecloud's discussion that is fine. The bug here is that there is a 500 on a nonexistent project resources and not a 403

**Comment by hibooboo2** [comment]
This is fixed in current versions.

**Comment by vincent99** [comment]
@aruneli This has been floating around forever, can you check that the return codes are as James says above?

**Comment by sangeethah** [comment]
Tested with rancher-server build - v0.41.0-rc1

Following are the return codes , when trying to access resources using user api keys which is as expected:

/v1/projects/:has_access/: 200
/v1/projects/:no_access/: 404
/v1/projects/:no_access/containers: 403
/v1/projects/:no_access/non_existent_collection: 403
/v1/projects/:non_existent/: 404
/v1/projects/:non_existent/containers: 403
/v1/projects/:non_existent/non_existent_collection: 403
