### ISSUE TITLE
Import cluster - cluster name error could be more descriptive

### ISSUE THREAD

**Issue by gtirloni** [rancher/rancher#11285]
When importing a cluster using the kubeconfig contents, if one forgets to name the cluster, this is the message that is displayed in light red:

```
Validation failed in API: invalid name %!s(<nil>): a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

It seems an error message down the stack is being passed back to the interface, probably after trying to use the kubeconfig? In any case it would be more intuitive if the interface said something like "Invalid cluster name" and highlight the "Cluster Name" field.

Rancher 2.0.0-alpha12

**Comment by deniseschannon** [comment]
In our next preview, we've moved away from importing kubeconfig to giving a `kubectl apply` command to be able to import existing clusters.

In the same release, when creating clusters, the UI also automatically takes capital letters and converts to lower case.

**Comment by gtirloni** [comment]
@deniseschannon thank you!
