### ISSUE TITLE
Catalog Apps - Refresh button fails

### ISSUE THREAD

**Issue by gtirloni** [rancher/rancher#11286]
**Rancher versions:**
2.0.0-alpha12

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, cluster with 3 masters and 3 nodes (created with RKE and imported).

**Steps to Reproduce:**
1. Go to Cluster > Catalog Apps > Launch
2. Click on "Refresh"

**Results:**
The refresh button shows an alert sign and this is logged to the browser console:

```
VM36:1 POST https://hostname/v3/templates?refresh&action=refresh 422 ()
(anonymous) @ VM36:1
(anonymous) @ ember-fetch.js:471
C @ rsvp.js:429
e @ rsvp.js:882
e.fetch @ ember-fetch.js:434
n @ fetch.js:19
rawRequest @ store.js:244
request @ store.js:256
(anonymous) @ service.js:57
m @ rsvp.js:221
k @ rsvp.js:403
S @ rsvp.js:388
e.invoke @ backburner.js:289
e.flush @ backburner.js:159
e.flush @ backburner.js:361
e.end @ backburner.js:471
e.run @ backburner.js:560
Ne @ ember-metal.js:3875
e.handler @ action.js:119
(anonymous) @ event_dispatcher.js:235
dispatch @ jquery.js:5206
g.handle @ jquery.js:5014
```

Nothing is logged to Rancher's container logs.

**Comment by vincent99** [comment]
None of the catalog works in alpha12.

**Comment by tfiduccia** [comment]
@gtirloni - this is part of our standard test cases and will be tested when catalog functionality become available.  So i'm going to close this issue.

**Comment by gtirloni** [comment]
Oh, I didn't know, sorry. Thanks for checking that though.
