### ISSUE TITLE
Custom cluster showing two nodes when I only added 1

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11298]
**Rancher versions:** 2.0 master 2/4

**Steps to Reproduce:**
1.  Go to Add RKE cluster
2.  Go to Custom
3.  Create a DO host from Digital Ocean site
4.  In Custom fill out info for DO host
5.  Create cluster

**Results:**  Everything passes but it looks like I added two nodes instead of just one.
![image](https://user-images.githubusercontent.com/11514927/35793746-39e6910e-0a10-11e8-91a2-e84b8fe432d7.png)

**Comment by deniseschannon** [comment]
Even when I have a failed SSH host, the non-real node gets created and shows up.

**Comment by deniseschannon** [comment]
It seems like as soon as you try to start creating, it creates a node before even trying to SSH into the actual node that you want to add into Rancher.

**Comment by deniseschannon** [comment]
It's cause during cluster creation we create a node entry and after the node is added, the node syncer logic is supposed to find the node entry created and sync up, but that's not happening.

**Comment by deniseschannon** [comment]
Fixed in master 02/07 12pm
