### ISSUE TITLE
Move RKE network plugins system images to Rancher repo

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11295]
To fully support private registries, we have to move flannel, calico, weave, canal images to rancher repo as well. That would require:

* adding them to system images in types
* changing rke code to accommodate the changes

**Comment by soumyalj** [comment]
Tested with v2.0.0-alpha17. Created clusters using calico, canal and flannel network plugins. 
Logged in to the hosts and verified that all the images were from rancher repo[except alpine, weave which were already in docker hub]
