### ISSUE TITLE
rancher-nfs - active hosts list not honouring scheduling labels

### ISSUE THREAD

**Issue by bluemalkin** [rancher/rancher#11309]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: 1.6.12

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.2.1
network-services: v0.2.7
scheduler: v0.6.3

**Docker version:**
17.09.1-ce

**Operating system and kernel:**
Ubuntu 16.04.3 LTS (4.4.0)

**Type/provider of hosts:**
AWS

**Setup details: **
Single node and H.A. both external RDS DB

**Environment Template:**
Cattle

**Steps to Reproduce:**
Add rancher-nfs infrastructure stack from Catalog.

Upgrade the service and add a host label to only schedule the nfs service on hosts with X label.

**Results:**
The nfs service is correctly scheduled on just the X hosts.

BUT when you go to Infrastructure, Storage. It shows that the service is active on ALL hosts instead of just X hosts.
The list needs to be updated to reflect where the service actually runs.

**Comment by loganhz** [comment]
There is a label `io.rancher.scheduler.global=true` on the nfs service. If `io.rancher.scheduler.global` is true, other scheduling rules will be ignored.
