### ISSUE TITLE
helm certificate 509

### ISSUE THREAD

**Issue by loverto** [rancher/rancher#11311]
*Describe your issue here*

> helm list
Error: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authoritycertificate "cattle")
>

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.kubectl`|

**Comment by superseb** [comment]
What steps did you take to get into this situation? How many hosts, did you re-use certain hosts? Was something rebooted/restarted? Are you using separate planes (resiliency planes) or not?

**Comment by loverto** [comment]
1. 2 hosts , 
3. use rancher server hosts  for k8s
2. no restart
3. default planes

**Comment by loverto** [comment]
k8s use 1 hosts , cattle use 1 hosts , total 2 hosts

**Comment by JannikZed** [comment]
having the same issue: k8 everything on a single node. 

```
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

```
helm install stable/traefik --name traefik-triebwork-release --namespace kube-system --debug

[debug] Created tunnel using local port: '49707'
[debug] SERVER: "127.0.0.1:49707"
[debug] Original chart version: ""
[debug] Fetched stable/traefik to /Users/jannik/.helm/cache/archive/traefik-1.21.1.tgz
[debug] CHART PATH: /Users/jannik/.helm/cache/archive/traefik-1.21.1.tgz
Error: Get https://10.43.0.1:443/version: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "cattle")```

**Comment by okaufmann** [comment]
I have the same issue: https://forums.rancher.com/t/x509-certificate-signed-by-unknown-authorit-when-using-kubectl-or-helm/10255

**Comment by Natalique** [comment]
Same here :(

**Comment by opensorceror** [comment]
Same issue here

**Comment by srodriguezOPT** [comment]
Same here...

**Comment by srodriguezOPT** [comment]
I was working with helm v2.8.2 version...

Updating to helm 2.9.1 worked for me.

**Comment by superseb** [comment]
If this can be reproduced on the latest version, let me know. There are two resolutions based on the comments and the forum post.
