### ISSUE TITLE
New tokens not generated on container restart on rancher-server upgraded from 1.6.14 -> 1.6.15-rc3

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11317]
Fresh install of rancher-server v1.6.14

Have an environment with 3 hosts having secrets-bridge-v2 and secrets deployed.
Deploy services having volumes using secrets-bridge-v2.
From service containers able to fetch secrets using the instance token that gets unwarpped from the intermediate token presented in the volume.

Upgrade rancher-server to v1.6.15-rc3.

Note -  secrets-bridge-v2 and secrets are still in the older version.

Restart one of the service containers that was deployed deployed before rancher-server was upgraded.

Once the new container is started , we are not able to use the token that is present in the volume. New token was not generated in this case.

```
root@30d05854c9f9:/# ./vault unwrap 6649c017-8957-327c-a53c-43768138b419
Error making API request.

URL: PUT http://159.89.190.231:8200/v1/sys/wrapping/unwrap
Code: 400. Errors:

* wrapping token is not valid or does not exist
root@30d05854c9f9:/#
``` 

The same behavior is also seen when new services with volumes using secrets-bridge-v2 are deployed.
Able to use the token generated for fetching instance token successfully and fetch secrets.

But on restart of these instances , token does not get regenerated.

**Comment by cloudnautique** [comment]
```
#GOOD WORKING 1.6.14
2/12/2018 5:32:56 PMtime="2018-02-13T00:32:56Z" level=info msg=unmount.request name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:32:56 PMtime="2018-02-13T00:32:56Z" level=info msg=unmount.response name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:32:57 PMtime="2018-02-13T00:32:57Z" level=info msg=attach.request name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:32:57 PMtime="2018-02-13T00:32:57Z" level=info msg="Updating volume test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274 (1v38) secrets-bridge-v2:1sd2 on 1h1, state active => active" err=<nil>
2/12/2018 5:32:57 PMtime="2018-02-13T00:32:57Z" level=info msg=attach.response name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:32:57 PMtime="2018-02-13T00:32:57Z" level=info msg=mount.request name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:32:57 PMtime="2018-02-13T00:32:57Z" level=info msg="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274 already mounted on /var/lib/rancher/volumes/secrets-bridge-v2/test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:32:57 PMtime="2018-02-13T00:32:57Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/secrets-bridge-v2/test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274" name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"




# BAD REQUEST 1.6.15-rc3
2/12/2018 5:37:27 PMtime="2018-02-13T00:37:27Z" level=info msg=unmount.request name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:37:27 PMtime="2018-02-13T00:37:27Z" level=info msg=unmount.response name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:37:28 PMtime="2018-02-13T00:37:28Z" level=info msg=mount.request name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:37:28 PMtime="2018-02-13T00:37:28Z" level=info msg="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274 already mounted on /var/lib/rancher/volumes/secrets-bridge-v2/test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
2/12/2018 5:37:28 PMtime="2018-02-13T00:37:28Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/secrets-bridge-v2/test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274" name="test_vault-tokenn_1_2fe651a8-d1c2-4cff-aa10-9cbc3efc3189_02274"
```

**Comment by cloudnautique** [comment]
There is also another issue this uncovered where the contents of the directory are note removed properly in the unmount call. Will address.

**Comment by StrongMonkey** [comment]
@sangeethah can you re-test it at some point? given that i made a fix in agent and bill also made a fix in storage driver side.

**Comment by sangeethah** [comment]
@StrongMonkey , I tested upgrade from 1.6.14 -> 1.6.15-rc5 and see the same issue.

**Comment by cloudnautique** [comment]
@StrongMonkey the agent is missing a call to the volume driver.

**Comment by sangeethah** [comment]
Tested with  rancher-server upgrade from v1.6.14 -> 1.6.15-rc6

Have an environment with 3 hosts having secrets-bridge-v2 and secrets deployed.
Deploy services having volumes using secrets-bridge-v2.
From service containers able to fetch secrets using the instance token that gets unwarpped from the intermediate token presented in the volume.

Upgrade rancher-server to v1.6.15-rc3.

Note - secrets-bridge-v2 and secrets are still in the older version.

Restart one of the service containers that was deployed before rancher-server was upgraded.
New tokens get generated as expected. Able to use to it unwrap and get tokens which can be used for fetching secrets successfully.

Deploy new services.
Restart / stop (and wait for the container to start) . New tokens get generated as expected. Able to use to it unwrap and get tokens which can be used for fetching secrets successfully.
