### ISSUE TITLE
Ressource management at runtime

### ISSUE THREAD

**Issue by mboussaa** [rancher/rancher#1131]
Hi all,
Is there any attempt to manage containers configuration at runtime?
I have to change ressources limitation at runtime.
it would be great to manage all containers settings at runtime like memory or CPU customization.
For example, while container is running, I would like to change the memory limit or cpu usage.

Thanks in advance.

**Comment by vincent99** [comment]
Generally we support what Docker supports, and this is something that is controversial there.  See:  https://github.com/docker/docker/issues/6323 & https://github.com/docker/docker/pull/11442
