### ISSUE TITLE
Unable to create port mapping with host-ip

### ISSUE THREAD

**Issue by Schlangguru** [rancher/rancher#11316]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: 1.2.9

**Steps to Reproduce:**
Create a service with port-mapping of style [host-ip:host-port:container-port] Eg. 10.1.0.1:8080:80

**Results:**  Failed to allocate instance [container:1i1450]: Bad instance [container:1i1450] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [10.1.0.1:8080:80/tcp portReservation, instanceReservation: 1

Expected: Port Mapping should only listen on specified Host-IP

The corresponding Docker CLI Comman "docker run ... -p 10.1.0.1:8080:80 ..." works as expected.

**Comment by superseb** [comment]
Did you configure scheduler IPs? http://rancher.com/docs/rancher/v1.6/en/rancher-services/scheduler/#scheduling-onto-multiple-ips-of-a-single-host

**Comment by Schlangguru** [comment]
That's it! Thank you for the right hint. Maybe one could add this hint to the Port Mapping section of the services docs (https://rancher.com/docs/rancher/latest/en/cattle/adding-services/#port-mapping) I was googling for hours, but found nothing relevant.
