### ISSUE TITLE
Rancher server v1.6.14 memory constantly increasing

### ISSUE THREAD

**Issue by tyronzerafa** [rancher/rancher#11314]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:

1. net:holder
1. net:v0.13.7

network-services:
  
1. network-manager:v0.7.19
1. metadata:v0.9.5

scheduler: rancher/k8s:v1.8.5-rancher4
kubernetes (if applicable): v1.8.5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS (Xenial Xerus)
4.4.0-112-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO (Hosts created manually and not automatically by Rancher's machine driver)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher - external database (Nginx in front of Rancher instance)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1) Created MySQL instance
1) Started Rancher instance as container
1) Deployed Nginx in front of Rancher
1) Created Kubernetes cluster
1) Added 5 digital ocean hosts (following Rancher's separate resiliency planes for HA k8s)
1) Added other worker machines.

**Results:**
Memory is constantly increasing on the Rancher server's host; the memory is being used by the java process executing within the rancher-server container. Memory usage keeps increasing until the container runs out of memory, after which the container is rebooted - Rancher comes up successfully after reboot. Once Rancher server is rebooted, memory starts increasing again until it gets rebooted again. The following graph shows this constant memory usage increase over time:

<img width="392" alt="screen shot 2018-02-06 at 10 02 56" src="https://user-images.githubusercontent.com/5180848/35850394-f3be903a-0b24-11e8-9974-52936fc31463.png">

We are seeing the following errors in the Rancher server container logs:
`2018-02-06 14:54:20,429 ERROR [3e18146f-d44d-4995-bbb7-17a47aa57a5d:7288] [agent:86] [agent.deactivate->(MetadataProcessHandler)] [] [ecutorService-1] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:86
2018-02-06 14:54:20,902 ERROR [1737f66c-db6d-4bc7-81ae-e22f968395db:7271] [agent:85] [agent.deactivate->(MetadataProcessHandler)] [] [cutorService-11] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:85
2018-02-06 14:54:21,196 ERROR [8ab2afa5-8fef-412a-a704-849c59a4b001:7380] [agent:86] [agent.remove->(MetadataProcessHandler)] [] [ecutorService-1] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:86
2018-02-06 14:54:21,448 ERROR [a8391510-d445-4517-a5e1-e58f1570fad1:7383] [agent:85] [agent.remove->(MetadataProcessHandler)] [] [cutorService-11] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:85`

Furthermore, we're also seeing the following logs within different containers, could these indicate a problem with our setup or the constant memory increase?

In the Rancher agent, we're constantly seeing the following log lines:
`06/02/2018 10:53:12time="2018-02-06T09:53:12Z" level=info msg="Connecting to proxy." url="wss://xxx/v1/connectbackend?token=<token>"
06/02/2018 10:53:41time="2018-02-06T09:53:41Z" level=warning msg="stat /var/lib/rancher/state/info.json: no such file or directory"
06/02/2018 10:53:41time="2018-02-06T09:53:41Z" level=error msg="retry check cloud provider" count=2 error="EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: EC2MetadataError: failed to make EC2Metadata request\ncaused by: not found"
06/02/2018 10:54:11time="2018-02-06T09:54:11Z" level=warning msg="stat /var/lib/rancher/state/info.json: no such file or directory"
06/02/2018 10:54:11time="2018-02-06T09:54:11Z" level=error msg="retry check cloud provider" count=3 error="EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: EC2MetadataError: failed to make EC2Metadata request\ncaused by: not found"
06/02/2018 10:54:41time="2018-02-06T09:54:41Z" level=warning msg="stat /var/lib/rancher/state/info.json: no such file or directory"
06/02/2018 10:54:41time="2018-02-06T09:54:41Z" level=error msg="retry check cloud provider" count=4 error="EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: EC2MetadataError: failed to make EC2Metadata request\ncaused by: not found"`

In the healthcheck containers, we're constantly seeing the following log lines: 
`05/02/2018 22:52:14time="2018-02-05T21:52:14Z" level=info msg="Scheduling apply config"
05/02/2018 22:52:15time="2018-02-05T21:52:15Z" level=info msg="healthCheck -- no changes in haproxy config\n"
05/02/2018 22:52:17time="2018-02-05T21:52:17Z" level=info msg="Scheduling apply config"
05/02/2018 22:52:17time="2018-02-05T21:52:17Z" level=info msg="healthCheck -- no changes in haproxy config\n"`

In the metadata containers, we're constantly seeing the following log lines: 
`05/02/2018 22:52:17time="2018-02-05T21:52:17Z" level=info msg="Generating and reloading answers"
05/02/2018 22:52:17time="2018-02-05T21:52:17Z" level=info msg="Generating answers"
05/02/2018 22:52:17time="2018-02-05T21:52:17Z" level=info msg="Generated and reloaded answers"
05/02/2018 22:52:17time="2018-02-05T21:52:17Z" level=info msg="Applied https://xxx/v1/configcontent/metadata-answers?client=v2&requestedVersion=1285?version=1287-25f88b208a323837e5062060b101a217"
05/02/2018 22:52:17time="2018-02-05T21:52:17Z" level=info msg="Download and reload in: 505.317523ms"`

**Comment by superseb** [comment]
So you are only seeing this on the host running the `rancher/server` container? What specs does the host have? And can you share what you are using to determine it's the java process claiming the memory.

**Comment by tyronzerafa** [comment]
Yes, we are only seeing this on the host running the `rancher/server` container. This host is only running this container and has 2gb memory. After we saw the container running out of memory and rebooting a couple of times, we limited the container memory to 1.7gb and the Java heap space to 1.5gb - this did not have any effect. We are using the `top` Linux command to find out which process is using this memory:

<img width="642" alt="screen shot 2018-02-07 at 15 02 32" src="https://user-images.githubusercontent.com/5180848/35920388-03b1e9bc-0c18-11e8-9652-e12867e92e9e.png">

**Comment by tyronzerafa** [comment]
Furthermore, whenever the memory usage (docker) stat of the Rancher server container gets to 100%, the block input stat of this same container starts increasing at a rate of 1Gb per second, see attached screenshot: 

![2018-02-12](https://user-images.githubusercontent.com/5180848/36106847-b3c72714-1018-11e8-81ec-133ff3210a14.png)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
