### ISSUE TITLE
rancher-ebs driver unable to attach after a restart

### ISSUE THREAD

**Issue by ivanincanada** [rancher/rancher#11328]
This appears to be still the case and doesn't appear fix, it is repeatbale just by creating an EBS rancher volume, size etc, and restarting the container that depends on it. most often than not, rancher will fail to restart those services. I am unsure why. 

![screenshot1](https://user-images.githubusercontent.com/20289840/35892601-ec1f6a5e-0b5e-11e8-95fa-c97c4efaeca6.png)

**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by aemneina** [comment]
Can you share logs from the rancher-ebs driver (please mask any sensitive info)? Is the host that the ebs volume attached to okay or did it go down?

**Comment by ivanincanada** [comment]
> /6/2018 1:35:52 PMtime="2018-02-06T21:35:52Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-www-data
2/6/2018 1:35:52 PMtime="2018-02-06T21:35:52Z" level=info msg=attach.request name=wsad-gitlab-app-data
2/6/2018 1:35:52 PM
2/6/2018 1:35:52 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 1:35:52 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 1:35:52 PM
2/6/2018 1:35:52 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 1:35:53 PMtime="2018-02-06T21:35:53Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"wsad-gitlab-app-data\",\"rancher\":\"true\",\"size\":\"100\",\"volumeID\":\"vol-0f4ee1d5f2e2838c9\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 1:35:53 PMtime="2018-02-06T21:35:53Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=wsad-gitlab-app-data
2/6/2018 4:59:34 PMtime="2018-02-07T00:59:34Z" level=info msg=attach.request name=bdg-joomla-db-data
2/6/2018 4:59:34 PM
2/6/2018 4:59:34 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:34 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:35 PM
2/6/2018 4:59:35 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:36 PMtime="2018-02-07T00:59:36Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-db-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-0b4d3cf85f5eaf94c\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:36 PMtime="2018-02-07T00:59:36Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-db-data
2/6/2018 4:59:36 PMtime="2018-02-07T00:59:36Z" level=info msg=attach.request name=bdg-joomla-db-data
2/6/2018 4:59:36 PM
2/6/2018 4:59:36 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:36 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:36 PM
2/6/2018 4:59:36 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:37 PMtime="2018-02-07T00:59:37Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-db-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-0b4d3cf85f5eaf94c\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:37 PMtime="2018-02-07T00:59:37Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-db-data
2/6/2018 4:59:37 PMtime="2018-02-07T00:59:37Z" level=info msg=attach.request name=bdg-joomla-www-data
2/6/2018 4:59:38 PM
2/6/2018 4:59:38 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:38 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:38 PM
2/6/2018 4:59:38 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:39 PMtime="2018-02-07T00:59:39Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-www-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-094da5cf3d5a90d6e\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:39 PMtime="2018-02-07T00:59:39Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-www-data
2/6/2018 4:59:39 PMtime="2018-02-07T00:59:39Z" level=info msg=attach.request name=bdg-joomla-db-data
2/6/2018 4:59:39 PM
2/6/2018 4:59:39 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:40 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:40 PM
2/6/2018 4:59:40 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:41 PMtime="2018-02-07T00:59:41Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-db-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-0b4d3cf85f5eaf94c\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:41 PMtime="2018-02-07T00:59:41Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-db-data
2/6/2018 4:59:41 PMtime="2018-02-07T00:59:41Z" level=info msg=attach.request name=bdg-joomla-www-data
2/6/2018 4:59:41 PM
2/6/2018 4:59:41 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:41 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:42 PM
2/6/2018 4:59:42 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:42 PMtime="2018-02-07T00:59:42Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-www-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-094da5cf3d5a90d6e\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:42 PMtime="2018-02-07T00:59:42Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-www-data
2/6/2018 4:59:42 PMtime="2018-02-07T00:59:42Z" level=info msg=attach.request name=bdg-joomla-db-data
2/6/2018 4:59:43 PM
2/6/2018 4:59:43 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:43 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:43 PM
2/6/2018 4:59:43 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:44 PMtime="2018-02-07T00:59:44Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-db-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-0b4d3cf85f5eaf94c\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:44 PMtime="2018-02-07T00:59:44Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-db-data
2/6/2018 4:59:44 PMtime="2018-02-07T00:59:44Z" level=info msg=attach.request name=bdg-joomla-www-data
2/6/2018 4:59:45 PM
2/6/2018 4:59:45 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:45 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:45 PM
2/6/2018 4:59:45 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:46 PMtime="2018-02-07T00:59:46Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-www-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-094da5cf3d5a90d6e\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:46 PMtime="2018-02-07T00:59:46Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-www-data
2/6/2018 4:59:46 PMtime="2018-02-07T00:59:46Z" level=info msg=attach.request name=bdg-joomla-db-data
2/6/2018 4:59:46 PM
2/6/2018 4:59:46 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:46 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:47 PM
2/6/2018 4:59:47 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:48 PMtime="2018-02-07T00:59:48Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-db-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-0b4d3cf85f5eaf94c\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:48 PMtime="2018-02-07T00:59:48Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-db-data
2/6/2018 4:59:48 PMtime="2018-02-07T00:59:48Z" level=info msg=attach.request name=bdg-joomla-www-data
2/6/2018 4:59:48 PM
2/6/2018 4:59:48 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:48 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:49 PM
2/6/2018 4:59:49 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:49 PMtime="2018-02-07T00:59:49Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-www-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-094da5cf3d5a90d6e\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:49 PMtime="2018-02-07T00:59:49Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-www-data
2/6/2018 4:59:50 PMtime="2018-02-07T00:59:50Z" level=info msg=attach.request name=bdg-joomla-www-data
2/6/2018 4:59:50 PM
2/6/2018 4:59:50 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:50 PM/usr/bin/rancher-ebs: line 228: [: -eq: unary operator expected
2/6/2018 4:59:50 PM
2/6/2018 4:59:50 PMAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials
2/6/2018 4:59:51 PMtime="2018-02-07T00:59:51Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"ec2_az\":\"ca-central-1a\",\"ec2_region\":\"ca-central-1\",\"name\":\"bdg-joomla-www-data\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-094da5cf3d5a90d6e\"}: {\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}"
2/6/2018 4:59:51 PMtime="2018-02-07T00:59:51Z" level=error msg=attach.response error="{\"status\":\"Failure\",\"message\":\"Failed to detach ebs volume by force. \\nAn error occurred (AuthFailure) when calling the DetachVolume operation: AWS was not able to validate the provided access credentials\"}" name=bdg-joomla-www-data
2/6/2018 11:20:06 PMtime="2018-02-07T07:20:06Z" level=info msg="container 2c1f611c6d4c6b5f82926c82a84ef04c2aa1ecffab124763a68410dfff60f038 destroyed"
2/6/2018 11:20:06 PMtime="2018-02-07T07:20:06Z" level=info msg="container 4919b29502e7d155eb05def6af977737fa834196f012050acdc60ff09318e561 destroyed"
2/6/2018 11:20:54 PMtime="2018-02-07T07:20:54Z" level=info msg="container ae7dae10c7ea374ecb24030fa36ed124faa8514b0506d34e7bc514d54c2c8232 destroyed"
2/6/2018 11:21:08 PMtime="2018-02-07T07:21:08Z" level=info msg=remove.request name="letsencrypt_wsadLetsEncryptData_06138"
2/6/2018 11:21:09 PMtime="2018-02-07T07:21:09Z" level=error msg=remove.response error="Failed to describe volume vol-0f2b7e3f85394e64a: \nAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials" message="Failed to describe volume vol-0f2b7e3f85394e64a: \nAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials" name="letsencrypt_wsadLetsEncryptData_06138" status=Failure
2/6/2018 11:21:10 PMtime="2018-02-07T07:21:10Z" level=info msg=remove.request name="letsencrypt_wsadLetsEncryptData_06138"
2/6/2018 11:21:10 PMtime="2018-02-07T07:21:10Z" level=error msg=remove.response error="Failed to describe volume vol-0f2b7e3f85394e64a: \nAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials" message="Failed to describe volume vol-0f2b7e3f85394e64a: \nAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials" name="letsencrypt_wsadLetsEncryptData_06138" status=Failure
2/6/2018 11:21:11 PMtime="2018-02-07T07:21:11Z" level=info msg=remove.request name="letsencrypt_wsadLetsEncryptData_06138"
2/6/2018 11:21:12 PMtime="2018-02-07T07:21:12Z" level=error msg=remove.response error="Failed to describe volume vol-0f2b7e3f85394e64a: \nAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials" message="Failed to describe volume vol-0f2b7e3f85394e64a: \nAn error occurred (AuthFailure) when calling the DescribeVolumes operation: AWS was not able to validate the provided access credentials" name="letsencrypt_wsadLetsEncryptData_06138" status=Failure
2/6/2018 11:21:15 PMtime="2018-02-07T07:21:15Z" level=info msg="container e5acc528c0623e12d144fc41d4a53c45d2ff68c8dedc3e690390dbcd8a5c8f16 destroyed"
2/6/2018 11:21:15 PMtime="2018-02-07T07:21:15Z" level=info msg="container 6b666633a2d21e05962026b454a7966c48ea0e18352c234cd8e96e0c7128617d destroyed"





2/6/2018 1:26:31 PMtime="2018-02-06T21:26:31Z" level=info msg=Running
2/6/2018 1:26:31 PMtime="2018-02-06T21:26:31Z" level=info msg=Starting
2/6/2018 1:26:31 PMtime="2018-02-06T21:26:31Z" level=info msg="Running on host wsadHost2(1h110) with driver rancher-ebs(1sd6)"
2/6/2018 1:26:31 PMtime="2018-02-06T21:26:31Z" level=info msg="Starting plugin for rancher-ebs"
2/6/2018 1:27:41 PMtime="2018-02-06T21:27:41Z" level=info msg="container 6f6dee016d4825356d0745f062f34a3d99572b594c3f2057df375a9d22854a13 destroyed"
2/6/2018 1:28:40 PMtime="2018-02-06T21:28:40Z" level=info msg="container 9d2ebf451cebf30e78c94f9459b3a42cf73b370f95ca204dc94b413d20753b11 destroyed"
2/6/2018 1:30:50 PMtime="2018-02-06T21:30:50Z" level=info msg=Running
2/6/2018 1:30:50 PMtime="2018-02-06T21:30:50Z" level=info msg=Starting
2/6/2018 1:31:45 PMtime="2018-02-06T21:31:45Z" level=info msg="Running on host wsadHost2(1h110) with driver rancher-ebs(1sd6)"
2/6/2018 1:31:45 PMtime="2018-02-06T21:31:45Z" level=info msg="Starting plugin for rancher-ebs"
2/6/2018 1:31:54 PMtime="2018-02-06T21:31:54Z" level=info msg="container 33a19a867c1c253e1baa36fc02971824cb4b99fb7aac2c1352c257275f05cc13 destroyed"
2/6/2018 1:31:54 PMtime="2018-02-06T21:31:54Z" level=info msg="container dcbc84985bcf9f5af8000ffd2f2c571d0bed952832c826747cb7d4dede5eef53 destroyed"
2/6/2018 1:31:54 PMtime="2018-02-06T21:31:54Z" level=info msg="container 70b93f72c64d6756100b8eaf1af3e87ae7f853288c39eb66fad8f6422a61514a destroyed"
2/6/2018 1:32:54 PMtime="2018-02-06T21:32:54Z" level=info msg="container c5fa86a6105c093055d589de9cc66d0abd6a3abcac21e318aac10732d6c92547 destroyed"
2/6/2018 1:32:54 PMtime="2018-02-06T21:32:54Z" level=info msg="container 8629e1016a3ac74b815b01dfba24f2702ca6722ba682d74d24a951339f227f26 destroyed"
2/6/2018 1:32:56 PMtime="2018-02-06T21:32:56Z" level=info msg="container ba02a47473399c050d21f45d71a34159adea07df460ee72f2a2cc793f47ea902 destroyed"

**Comment by ivanincanada** [comment]
while at first it is complaining about access credentials, the credentials are valid to my knowledge. ec2, s3, full access etc. later, it stops complaining about access credentials, despite them not changing.

atm, 1 of the 3 nodes involved in the volumes is caught in reboot cycle (container marked for removal but can't remove, need to restart to reconcile service). 

Im wondering, can I remove the driver, remove the drives from storage, export the configs for all my dependent services and then reinstall it from scratch and redeploy the services. but im unsure how the driver works, does it take care of attaching the volume on aws to whatever instance, take care of the underlining device mapping etc, or do i need to attach them manually to a node. i did force connect two volumes a few moments ago but i see, despite the other volumes not been in use, they are still attached to one of the 3 instances. im thinking now how to repair :/

**Comment by ivanincanada** [comment]
I tried various methods but this is what worked for me. 

1) Export config from all effected services (and all those using ebs)
2) Delete all services that use EBS
3) Went into storage and deleted the volumes by hand now that they were detached
(this does not delete them on aws, so its safe)
4) Reboot the Rancher Master and Cattle (i did this)
5) Started docker, no more remaining services using rancher-ebs
6) Inspected the logs of the 3 EBS services in 3 different environments, 

they were each using the same credentials and if one was show authentication issues, then all should have been. all were working fine (in the logs) except which was caught in reboot, this was also the one that had the unable to authenticate logs

7) force detached all RANCHER-EBS volumes from all EC2 instances
8) Manually reattached all vlumes back to the same EC2 instance I detached them from
9) Rebooted rancher machines and effected cattle
10) EBS and all default rancher services were now in the green

11) Added by hand back all the rancher-ebs containers I had deleted from storage, giving them the same name. 

12) Relaunched each of the effected services (3xmariadb, 3xjoomla and some others) through stacks and the configs I had exported earlier 

Services came back up. 

13) Stopped services by hand that used EBS now that they were up again
14) Started the service by hand again

a few rounds of 13/14 and reboots of EC2 instances

Behaviour has returned to normal. 

My setup ran for a long time with no issues, so I am not sure why it happened now or kept repeating but the short of it is to delete all volumes, detatch and reattach and recreate, then relaunch the services that depended on them and the stacks come back up again. 

Sorry I have not found a way to repeat what happened, I can give full logs if you think it is necessary but I am putting it down to something weird that may have happened on EC2 or AWS when my back wasn't looking. 

Thanks for getting back to me, for me, issue is solved/closed though the reason why is not apparent.

**Comment by ivanincanada** [comment]
further issue is that rancher did launch ebs volumes again, but it created new ones instead of attaching to the old ones. so the instances came up vanilla with missing data for hdd and DB


2/6/2018 11:37:55 PMtime="2018-02-07T07:37:55Z" level=info msg=Running
2/6/2018 11:37:55 PMtime="2018-02-07T07:37:55Z" level=info msg=Starting
2/6/2018 11:37:55 PMtime="2018-02-07T07:37:55Z" level=info msg="Running on host wsadHost1(1h107) with driver rancher-ebs(1sd6)"
2/6/2018 11:37:55 PMtime="2018-02-07T07:37:55Z" level=info msg="Starting plugin for rancher-ebs"
2/7/2018 12:00:55 AMtime="2018-02-07T08:00:55Z" level=info msg=create.request name=wsad-gitlab-log-data options=map[size:50]
2/7/2018 12:01:16 AMtime="2018-02-07T08:01:16Z" level=info msg="Updating volume wsad-gitlab-log-data (1v166059) rancher-ebs:1sd6 on 1h107, state inactive => updating-inactive" err=<nil>
2/7/2018 12:01:16 AMtime="2018-02-07T08:01:16Z" level=info msg=create.response name=wsad-gitlab-log-data status=Success
2/7/2018 12:01:16 AMtime="2018-02-07T08:01:16Z" level=info msg=attach.request name=wsad-gitlab-log-data
2/7/2018 12:01:20 AMtime="2018-02-07T08:01:20Z" level=info msg=attach.response name=wsad-gitlab-log-data
2/7/2018 12:01:20 AMtime="2018-02-07T08:01:20Z" level=info msg=create.request name=wsad-gitlab-app-data options=map[size:100]
2/7/2018 12:01:45 AMtime="2018-02-07T08:01:45Z" level=error msg=create.response error="Failed volume vol-09a13d5946712e240 transition, expected end state is: available, got creating" message="Failed volume vol-09a13d5946712e240 transition, expected end state is: available, got creating" name=wsad-gitlab-app-data status=Failure
2/7/2018 12:01:50 AMtime="2018-02-07T08:01:50Z" level=info msg=attach.request name=wsad-gitlab-log-data
2/7/2018 12:01:51 AMtime="2018-02-07T08:01:51Z" level=info msg=attach.response name=wsad-gitlab-log-data
2/7/2018 12:01:51 AMtime="2018-02-07T08:01:51Z" level=info msg=create.request name=wsad-gitlab-app-data options=map[size:100]
2/7/2018 12:02:16 AMtime="2018-02-07T08:02:16Z" level=error msg=create.response error="Failed volume vol-0ad65f83d15fb090e transition, expected end state is: available, got creating" message="Failed volume vol-0ad65f83d15fb090e transition, expected end state is: available, got creating" name=wsad-gitlab-app-data status=Failure
2/7/2018 12:02:16 AMtime="2018-02-07T08:02:16Z" level=info msg=attach.request name=wsad-gitlab-log-data
2/7/2018 12:02:17 AMtime="2018-02-07T08:02:17Z" level=info msg=attach.response name=wsad-gitlab-log-data
2/7/2018 12:02:17 AMtime="2018-02-07T08:02:17Z" level=info msg=create.request name=wsad-gitlab-app-data options=map[size:100]
2/7/2018 12:02:35 AMtime="2018-02-07T08:02:35Z" level=info msg="Updating volume wsad-gitlab-app-data (1v166060) rancher-ebs:1sd6 on 1h107, state inactive => updating-inactive" err=<nil>
2/7/2018 12:02:35 AMtime="2018-02-07T08:02:35Z" level=info msg=create.response name=wsad-gitlab-app-data status=Success
2/7/2018 12:02:35 AMtime="2018-02-07T08:02:35Z" level=info msg=attach.request name=wsad-gitlab-app-data
2/7/2018 12:02:40 AMtime="2018-02-07T08:02:40Z" level=info msg=attach.response name=wsad-gitlab-app-data

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by zeroum** [comment]
Not sure if I should open a new issue or not, but:

Exactly the same problem, after a Rancher upgrade and server restart. The ebs-driver does not recognize the EBS attach and mount itself asked the OS and AWS to do.

A lengthy ebs-driver debug log is attached below. The service stack where the volume is attached is started manually, then stopped minutes later after the UI says it has errors.

Watching the AWS console, the volume was attached rapidly, and it shows up in `ls /dev/disks/by-uuid/`, but I didn't see the mount in `df`, watching it all the time. 

----

Rancher versions:
rancher/server: 1.6.28 (upgraded from 1.6.5)
rancher/agent:v1.2.11

Infrastructure Stack versions:
rancher/storage-ebs:v0.9.7
rancher/healthcheck:v0.3.8
rancher/net:v0.13.17
rancher/dns:v0.17.4
rancher/external-dns:v0.7.9
rancher/scheduler:v0.8.6
rancher/metadata:v0.10.4
rancher/network-manager:v0.7.22
  
docker info:
```
root@app-252:~# docker info 
Containers: 26
 Running: 24
 Paused: 0
 Stopped: 2
Images: 35
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 212
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-ebs
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-170-generic
Operating System: Ubuntu 14.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797GiB
Name: app-252
ID: ENC3:5IB4:KCSN:3LRW:I7KE:3UKT:KROD:XS22:MHX2:S3QV:4S4A:A2IK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Type/provider of hosts: AWS

Setup details: single node Rancher, external DB (AWS RDS MySQL 5.7.17)

Environment Template: Cattle

Debug log:

[ebs-driver.log](https://github.com/rancher/rancher/files/3627610/ebs-driver.log)
