### ISSUE TITLE
After a node is provisioned but has not joined the cluster, the node page shows "Active" node, but it's not doing anything yet

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11325]
We should add in a state "Waiting to join cluster" for the period between when a node is provisioned and when all the k8s elements are coming up. If you go to the Node page, it looks like everything is active and happy when in reality, the node is still trying to join the cluster.

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/37030019-563df5ec-2174-11e8-9def-0f2e8f0653cb.png)

Version - 2.0 master 3/6
Verified fixed
