### ISSUE TITLE
"Issuing Token Secret" field is not pre set in UI when Upgrading secrets bridge stack.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11320]
Fresh install of rancher-server v1.6.14

Have an environment with 3 hosts having secrets-bridge-v2 and secrets deployed.
Upgrade rancher-server to v1.6.15-rc3.

Click on "Upgrade Available" option for "Secret Bridge" stack.

When v0.3.0 is presented to the user , "Issuing Token Secret" field is not pre selected.

<img width="1447" alt="screen shot 2018-02-06 at 1 02 55 pm" src="https://user-images.githubusercontent.com/4266958/35884064-368473da-0b3e-11e8-8a2d-c6568f97f550.png">

But doing upgrade without selecting any secret succeeds and in API we have the right values.

**Comment by cloudnautique** [comment]
I think this is a UI issue? @vincent99

**Comment by cloudnautique** [comment]
@loganhz is this ready to test?

**Comment by deniseschannon** [comment]
@cloudnautique it will be in the next RC.

**Comment by deniseschannon** [comment]
Available in v1.6.15-rc4

**Comment by sangeethah** [comment]
Tested with rancher-server upgrade from v1.6.14 -> v1.6.15-rc5.

"Issuing Token Secret" field is pre set in UI as expected when upgrading Secret Bridge" stack.
