### ISSUE TITLE
KVM machine driver import fails

### ISSUE THREAD

**Issue by zchef2k** [rancher/rancher#11339]
**Rancher versions:**
rancher/server: Rancher 1.6.14
Single node container 

**Steps to Reproduce:**

Import any of the docker-machine-kvm binaries (from https://github.com/dhiltgen/docker-machine-kvm/releases/tag/v0.10.0) via Admin->Machine Drivers

**Results:**
Error:
`time="2018-02-07T14:54:26Z" level=error msg="Error processing event" err="Error dialing to plugin server's address(), err=dial tcp: missing address" eventId=e414333e-c7fe-469c-bc7c-1a0b94320f4b eventName="machinedriver.update;handler=goMachineService-machine" resourceId=1md15`

**Comment by vincent99** [comment]
I'm not sure it's even downloading from that error message, but none of those binaries are going to work as-is.

Machine drivers need to be named exactly`docker-machine-driver-DRIVERNAME (so `docker-machine-driver-kvm` here) for machine to find them and rancher doesn't know to remove the  distro suffix.

Typically the download is an archive that contains the normal expected filename and then the archive's name has arbitrary extra details like the version or CPU architecture.

**Comment by zchef2k** [comment]
I should have noted that I downloaded them individually, renamed them to conform to the naming convention, and they generated this error.

Further research suggests that this driver requires libvirt to be installed which I'm guessing is no-go, given the containerized delivery model of Rancher. Feel free to set me straight on that.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by Lucaber** [comment]
if anyone comes across the `Error dialing to plugin server's address(), err=dial tcp: missing address` error, make sure your plugin binary is statically linked

**Comment by tariksimsek** [comment]
> if anyone comes across the `Error dialing to plugin server's address(), err=dial tcp: missing address` error, make sure your plugin binary is statically linked

Hello Lucaber , how did you link statically?

**Comment by tariksimsek** [comment]
> I should have noted that I downloaded them individually, renamed them to conform to the naming convention, and they generated this error.
> 
> Further research suggests that this driver requires libvirt to be installed which I'm guessing is no-go, given the containerized delivery model of Rancher. Feel free to set me straight on that.

Did you solve your issue?

**Comment by mlec1** [comment]
@tariksimsek Building with `CGO_ENABLED=0` solved this problem

**Comment by blackwood821** [comment]
@mlec1 Thank you! I had a custom node driver that worked fine on rancher v2.6.3 but the exact same binary failed to import on rancher version v2.8.5. I rebuilt with `CGO_ENABLED=0` and then it imported into version v2.8.5 without issue.
