### ISSUE TITLE
healthcheck container stuck in Initializing state

### ISSUE THREAD

**Issue by lezi1022** [rancher/rancher#11335]
**Rancher versions:**
rancher/server:v1.6.10
rancher/agent:v1.2.6

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec:net:v0.11.9
network-services: network-manager:v0.7.8
scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.13.0-24-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**

**Results:**

step1:
i run this script , 
```
for i in `curl -s 169.254.169.250/latest/self/service/containers/` ; do id=$(echo $i| cut -f1 -d=) ; name=$(echo $i| cut -f2 -d=) ; echo " ---- $name --------" ; ping -c2 `curl -s curl 169.254.169.250/latest/self/service/containers/$id/primary_ip` ; done
```
we can see the healthcheck stuck container is unreachable
```
PING 10.42.45.70 (10.42.45.70) 56(84) bytes of data.
64 bytes from 10.42.45.70: icmp_seq=1 ttl=62 time=8.78 ms
64 bytes from 10.42.45.70: icmp_seq=2 ttl=62 time=8.94 ms

--- 10.42.45.70 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1008ms
```
step2:
i use nc tool to test 4500/udp, 500/udp between healthcheck stuck container and rancher server， connection is succeeded each other

step3:
i restart ipsec-router 、 ipsec、cni-driver、healthcheck container ，it still doesn't work

**Comment by superseb** [comment]
The overlay network is created using the IP's show in the `Infrastructure` -> `Hosts` view, are these all showing the correct IP? Next, the port UDP/500 and UDP/4500 need to be open between those IPs. The command/script you used, can be run inside 1 ipsec-router container to determine if you can reach all the other containers. If not, the overlay network is not functioning correctly and you should check the IPs and the opened ports between all of those IPs

**Comment by lezi1022** [comment]
i checked the IPs and the opened ports(500、4500) between all of those IPs, it's ok , and The script i used , it can reach all the other containers. seems all it's well, but health check contain still stuck in initializing state

**Comment by superseb** [comment]
What is the logging of the healthcheck container?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
