### ISSUE TITLE
rancher-nfs cannot mount with path used by named Volume

### ISSUE THREAD

**Issue by bluemalkin** [rancher/rancher#11332]
**Rancher versions:**
v1.6.12

**rancher-nfs version:**
v0.4.0

**Docker version:**
17.06.2-ce

**Operating system and kernel:**
Ubuntu 16.04.3 LTS (4.4.0)

**Type/provider of hosts:**
AWS

**Environment Template:**
Cattle

**Steps to Reproduce:**

- Create an EFS on AWS (or an NFS server).
- Launch rancher-nfs from the Catalog
- Create a service e.g. redis mapping the /data volume to the rancher-nfs

**Results:**
The /data volume is a local volume instead of nfs mounted

It appears that any VOLUME in the Dockerfile conflicts with a rancher-nfs volume using the same mount path.

This is particularly a big issue since most containers with data have a VOLUME for the mount path.

**Comment by aemneina** [comment]
@bluemalkin did you create a volume from the infractructure->storage menu? Can you also share the stack definition that uses this volume?

**Comment by bluemalkin** [comment]
@aemneina I did for the external ones. Also tried the stack only ones.

I used the examples at http://rancher.com/docs/rancher/v1.6/en/rancher-services/storage-service/rancher-nfs/

**Comment by bluemalkin** [comment]
Closing issue as I have not been able to recreate it after recreating the rancher hosts.

Suspect the hosts were caching an old EFS endpoint somewhere.
