### ISSUE TITLE
Unable to deploy host on AWS with "Use only private IP address" selected (tcp: 22/2376/9345, udp: 500/4500 open 0.0.0.0/0)

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#11347]
**Rancher versions:**
**rancher/server:**1.6.14
**rancher/agent:** 1.2.9

Infrastructure Stack versions:
healthcheck:

ipsec:
enabled by default

**network-services:**
rancher/metadata:v0.9.5
COMMAND: start.sh rancher-metadata -reload-interval-limit=1000 -subscribe

rancher/network-manager:v0.7.19
COMMAND: plugin-manager --disable-cni-setup --metadata-address 169.254.169.250

scheduler:
rancher/scheduler:v0.8.3
COMMAND: scheduler --metadata-address 169.254.169.250

**Docker version:** 
1.13.1

**Operating system and kernel:**
Ubuntu 16.04.3

**Type/provider of hosts:**
AWS

**Setup details:**
HA + External RDS

**Environment Template:**
Cattle

**Steps to Reproduce:**
Try to deploy host from UI to AWS checking "Use only private IP address"

**Results:**
Failure to deploy host. Host shortly appears in AWS console & then gets removed.
tcp: 22/2376/9345, udp: 500/4500 open 0.0.0.0/0

Using the following as a workaround:
`docker run --rm --privileged -e CATTLE_AGENT_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 https://example.com/v1/scripts/6CDA0E8E64258C8A1EF9:7814641500000:ZFsQG7FzSgfk6BT4kGX6nWeN3I`

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/11476
