### ISSUE TITLE
UUID = internal ip & port = 8080 (which is not a valid port)

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#11346]
**Rancher versions:**
**rancher/server:**1.6.14
**rancher/agent:** 1.2.9

Infrastructure Stack versions:
healthcheck:

ipsec:
enabled by default

**network-services:**
rancher/metadata:v0.9.5
COMMAND: start.sh rancher-metadata -reload-interval-limit=1000 -subscribe

rancher/network-manager:v0.7.19
COMMAND: plugin-manager --disable-cni-setup --metadata-address 169.254.169.250

scheduler:
rancher/scheduler:v0.8.3
COMMAND: scheduler --metadata-address 169.254.169.250

**Docker version:** 
1.13.1

**Operating system and kernel:**
Ubuntu 16.04.3

**Type/provider of hosts:**
AWS

**Setup details:**
HA + External RDS

**Environment Template:**
Cattle

**Steps to Reproduce:**
Deploy rancher machine from UI to AWS not checking "Use only private IP address" (as this option apparently doesn't work correctly on AWS?) 

Restart agent with the following parameters in order to force it to advertise an internal IP & therefore to use only internal network for communication (workaround for "Use only private IP address"):
`docker run --rm --privileged -e CATTLE_AGENT_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 https://example.com/v1/scripts/6CDA0E8E64258C8A1EF9:7814641500000:ZFsQG7FzSgfk6BT4kGX6nWeN3I`

**Results:**
See internal 172.16.x.x ip address in UUID & port 8080 for all servers even though another port is configured & 8080 is not used.
Expected to see UUIDs & correct port.
![screenshot from 2018-02-07 23-47-26](https://user-images.githubusercontent.com/28118190/35941302-d4ea1be0-0c62-11e8-9e4a-edcc4954b32e.png)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
