### ISSUE TITLE
Unable to re-run `docker run` command for custom hosts without deleting the node in Rancher first

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11341]
1. Add a node using docker run, but forget to check any roles.
2. Re-run docker run with the added roles.

Result: Both agent containers are up but no provisioning happens.

Expected Result: The second agent container to spin up and start the RKE process.

**Comment by aiwantaozi** [comment]
It will set the default role to work now even we don't select anything, and then return below error log, because there lack of etcd and controlplane, the rancher server will return Info
```
2018/03/12 06:42:43 [INFO] ClusterController cluster-6nssm completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
```
Even we update the role and rerun the docker command not work.

@StrongMonkey About add customer host, how the host crd beed created?

**Comment by StrongMonkey** [comment]
@aiwantaozi first you have to make sure each agent register command is idempotent, that means running the command multiple times shouldn't affect the agent and nodes. Then you have to modify the node config dynamically(which i think that's going to be hard :) ). I don't know if rke supports it or not, but you might end up modifying rke code to make it work.

**Comment by aiwantaozi** [comment]
Related PR: https://github.com/rancher/rancher/issues/11341

**Comment by soumyalj** [comment]
Tested with master. Created a custom cluster with the following steps:
1. Add a node using docker run without any roles checked
2. Re-run docker run with the added roles.

The nodes were added correctly, the cluster was active and workload creation was successful.
