### ISSUE TITLE
[Windows] Creating a service doesn't support the "User" option

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#11358]
**Rancher versions:**
rancher/server: v1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 2016
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows

**Results:**
Add service and set "User".
After a while, the following error message can be seen on rancher UI

```
Expected state running but got error: Error response from daemon: container dc3cedd55fc75867f9f6c7476900e83c4f3d777c830261452c0f71053211a554 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"ApplicationName":"","CommandLine":"c:\\windows\\system32\\cmd.exe","User":"ksd","WorkingDirectory":"C:\\","Environment":{},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":false,"ConsoleSize":[0,0]}) 
```

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
