### ISSUE TITLE
Not able to launch namespace tab when control plane changes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11356]
**Rancher versions: v2.0 built from master

Steps to reproduce the problem:

Create a RKE cluster with node1 having all roles.
Wait for cluster to get to "Active" state.
Add node2  having all roles.
Wait for cluster to get to "Active" state.
Remove node1
Wait for cluster to get to "Active" state.

After we are not able to launch the  namespace tab in UI. It times out with "500 Server Error".

Following error seen in server logs:

```
time="2018-02-08T05:14:09Z" level=error msg="Unknown error: Get https://<ip>:6443/api/v1/namespaces: dial tcp 174.138.62.246:6443: i/o timeout"
```

**Comment by zionwu** [comment]
@sangeethah , I could not follow the same steps you described: add node1-> add node2 -> remove node1.  If I reduce the number of node from 2 to 1, it always removes node2.  It seems the steps you described will cause issue and it is forbidden now.

**Comment by deniseschannon** [comment]
@zionwu could you try with increasing the node pool from 1 to 2 and then reducing it back to 1? or starting with 1 node pool of 1 node with all roles and then adding another node pool of 1 node and removing the original node pool of 1 node.

**Comment by zionwu** [comment]
@deniseschannon 
1. I increased node pool from 1 to 2, and reduced it back to 1, but the issue could not be reproduced. 
![image](https://user-images.githubusercontent.com/1213386/37327935-3f288cd2-26d3-11e8-9436-9e051252e40c.png)

The same behavior is forbidden if I clicked "Edit Cluster".  I filed an issue https://github.com/rancher/rancher/issues/11985 for this inconsistent behavior.
![image](https://user-images.githubusercontent.com/1213386/37327983-644f019e-26d3-11e8-855a-9ede476a73b9.png)

2. I can't  add a new node pool with all roles as it is forbidden:
![image](https://user-images.githubusercontent.com/1213386/37327877-f7f2d2aa-26d2-11e8-8159-daa034efcaff.png)

**Comment by deniseschannon** [comment]
@sangeethah Can you try and re-test?

**Comment by sangeethah** [comment]
@zionwu , you are allowed to delete a node  after you have have increased node pool from 1 to 2.

Can you try to select the node that was added first and delete it instead of reducing the node pool to 1?

**Comment by zionwu** [comment]
@sangeethah I followed the steps. Once I removed the node 1 there is a new node created to keep the node pool with 2 nodes. At this time the namespaces tag can be accessed.

![image](https://user-images.githubusercontent.com/1213386/37579739-fd9a62e8-2b7a-11e8-9867-ae4695edbb62.png)

**Comment by deniseschannon** [comment]
@sangeethah with the changes to node pools, let's try and reproduce it as @zionwu has been unable to reproduce

**Comment by sangeethah** [comment]
@soumyalj Can you try to see if this issue still repros with latest builds?

**Comment by soumyalj** [comment]
Tested with master from March19th build. 
Created a single node(N1) cluster with ALL roles
Increased the node pool to two 
Deleted the node N1 
Another node got provisioned as expected. 
After the cluster was active, the namespace tab was operational. New namespace creation and workload creation was successful.
