### ISSUE TITLE
创建个 Wordpress 应用，但在添加容器的时候，只在一台主机上添加！

### ISSUE THREAD

**Issue by timerlau** [rancher/rancher#11359]
*Describe your issue here*
Rancher 下有两台主机，都是 ubuntu 16.04.3 docker 17.12.0-ce
创建个 Wordpress 应用，负载均衡服务、数据库服务在一台主机上，WP服务在另一台主机上。
增加WP容器的数量，仍然只在原来的主机上增加，不会在 另一台主机上增加。
即便在主机上这是了最大资源，也不行。
想问下是我哪里设置的有问题么？还是对 Rancher 的容器不太理解。

我增加主机使用的都是默认的 CUSTOM。使用的是 Vmware 创建的虚拟机测试。

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by loganhz** [comment]
可以通过给主机设置预留资源大小，并且给容器也设置预留资源大小。这样如果主机资源不足的情况下会调度到其他机器上。
下次请用英文提交问题，有问题可以添加微信RancherLabsChina加入用户群。
