### ISSUE TITLE
[types] Cluster client ByID returns error

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#11351]
When using the management client to retrieve a cluster ByID the following error is returned. 
FATA[0000] Resource type [cluster] can not be looked up by ID
https://github.com/rancher/types/blob/master/client/management/v3/zz_generated_cluster.go#L90

**Comment by deniseschannon** [comment]
@dramich is this fixed already?

**Comment by dramich** [comment]
@deniseschannon Yes, this looks to be fixed.

**Comment by sangeethah** [comment]
Ability to return clusterClient ById is used my --add-node command which is able to provide docker run command needed to register host for a given clusterid.
