### ISSUE TITLE
Deleting a host (added using ssh details) which has the only etcd running ,continues to remains in "Active" state.  

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11353]
**Rancher versions: v2.0 built from master 

Steps to reproduce the problem:
Create RKE cluster with 2 nodes by providing ssh details.
Node1 - all roles
Node2 - worker and controlplane

Delete Node1.

I see the node still being listed in "Active" state but cluster went into "updating" state with "waiting for nodes to provision or a valid configuration".

But UI does not show delete option for this host even though host is in "active" state .
All kube containers are still present in the host  that was deleted.

Should we restrict the deletion oh host where the only etcd is running in this case ?
In this case , why would cluster go to "Updating" state when host is actually still part of cluster?

**Comment by deniseschannon** [comment]
We're no longer supporting being able to provide SSH details to add nodes into rancher. We will only be supporting `docker run` to add in nodes for 2.0.
