### ISSUE TITLE
Private registry support for logging/alerting

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11367]
We have to add private registry support for images used by alerting/logging. For that, following needs to be done:

1) Private registry should be exposed via settings (string, json blob with fields url/username/password)
2) Alerting/Logging code should check for the setting presence, and format the pod deployment spec accordingly - prepend image with registry, putting creds into secrets, etc)

**Comment by alena1108** [comment]
@aiwantaozi Private registry is already supported, via secrets. We translate it to image pull secret on the workload, you might wanna do something similar for alerting/logging.

**Comment by zionwu** [comment]
@alena1108  what do you think if we let user define the image via `/v3/settings`. For example, `  /v3/settings/alertmanager-image` and user can set its value to something like "reg.rancher.com/prometheus/alertmanager:v0.0.1". 

 I find the private registry is on project level, which may not be used by alert/logging.  We should support setting private registry on cluster level. What do you think?

**Comment by alena1108** [comment]
@zionwu I think private image should be a cluster level parameter as you can have diff registries per cluster.

Quick summary:

* Logging/alerting/pipeline system images get deployed in user clusters
* Some get deployed as daemonset

There should be 2 parts to the fix:

1) Do alert/logging imagepull secret ref population to the deployment specs assuming that the cluster level secret exists in all the user namespaces. You can derive secret name from cluster.privateRegistries for now, till we figure out how to propagate it later. You’d also have to manually create this secret in all the namespaces for testing

2) Figure out secret propagation part - dynamic secret creation in all the namespaces based on the cluster.privateRegistry param (or create the cluster level secret directly, similar to the way we create project level secret)

**Comment by deniseschannon** [comment]
@ibuildthecloud is creating the private registry setting. once it's in, we should make sure that alerting/loggin uses it when it's filled in.

**Comment by deniseschannon** [comment]
From @ibuildthecloud: If you are deploying pods and need to set a docker image you need to use this util method now image.Resolve() that will prepend with the system default private registry if needed.

**Comment by zionwu** [comment]
@deniseschannon The changes are made in this PR  https://github.com/rancher/rancher/pull/12948/files and it is merged

**Comment by ibuildthecloud** [comment]
Steps to setup Rancher with private registry (NOTE: scripts are attached to the rancher release for example https://github.com/rancher/rancher/releases/tag/v2.0.0-beta4-rc2)

1.  Run `rancher-save-images.sh` in an environment that has access to dockerhub.  This script will download all images into a file `rancher-images.tar.gz`
2. Copy file to private network (it's a big file)
3. Run `rancher-load-images.sh` in the same directory as `rancher-images.tar.gz` to load the archive into private registry
4. Change /v3/settings/system-default-registry to your private registry.

**Comment by soumyalj** [comment]
Created a private registry and used the steps above to push the images. Creating a cluster using private registry images was successful. Workload creation was also ok.

**Comment by bmdepesa** [comment]
Validated with v2.0.0-rc1. 

Custom cluster with private registry set. 
Logging & alerting are functional and images are pulled from private registry.
