### ISSUE TITLE
Cattle 1.6.14 Worker node corruption 

### ISSUE THREAD

**Issue by trauts2** [rancher/rancher#11366]
*Describe your issue here*
https://forums.rancher.com/t/troubleshooting-1-6-14-worker-issue/9379

I am not sure how to troubleshoot or even capture debug info on this.  Twice in 20 hours now we've had a rancher worker node go flakey, the containers became unhealthy and that worker needed to be removed.  It's a node in an ASG, Rancher recovers fine and puts the containers on another node.  But this is causing disruption for users.

Sorry this is a terrible ticket, I realize you don't have enough to help.  If you could help me know what info to gather for troubleshooting and diagnosis when an instance goes sour I will gather this and update the ticket.

Thanks!

Stu

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by superseb** [comment]
The host going flakey is something you can dig deeper on, when a host becomes flakey/container become unhealthy:

- What is the host status on CPU/memory/disk?
- What is system logging at that moment? (`dmesg`, `/var/log/syslog`/`/var/log/messages`)
- Is Docker responsive? (`docker ps`)

Can you share host information? (`cat /etc/os-release`, `uname -r`, `docker version`, `docker info`)

**Comment by trauts2** [comment]
Thanks for the response,

While patiently waiting for another availability event, I can share some of the info.  This is from a member of the same ASG where in 20 hours 2 boxes have gone south.   

At no time was CPU >20%.  I'll provide details of memory and disk info when this happens next, but disk and memory are monitored and did not kick off any alarms.

I'll provide system logging again when this occurs, but below are the bits that won't likely change, and dmesg output from a box which has not yet exhibited the failure.

cat /etc/os-release
~~~~
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
~~~~

uname -r
~~~~
3.10.0-693.11.6.el7.x86_64
~~~~

docker version
~~~~
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
~~~~

sudo docker info
~~~~
Containers: 17
 Running: 15
 Paused: 0
 Stopped: 2
Images: 13
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.35GiB
Name: ip-10-0-20-56.ec2.internal
ID: 6XOO:ARMB:UDBG:EV3N:TUMJ:FZRF:VEUB:YAYR:JGZJ:7M5L:OKR3:2B6X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
~~~~

[dmesg.txt](https://github.com/rancher/rancher/files/1711537/dmesg.txt)

**Comment by trauts2** [comment]
Btw, RHEL is listed as a supported/recommend instance.  But to be honest I would like to know if there is a recommended build or OS for producing the most robust deployment.  Is that RancherOS, Ubuntu etc?  Hopefully in this thread we'll determine root cause for the current availability issues.  But I'm primarily interested in creating reliable infrastructure.  So if any of the details provided in the message above look sub-optimal let me know.  I'm not afraid to rebuild these bits from scratch.

Thanks again!

Stu

**Comment by pulberg** [comment]
@trauts2 I don't remember the exact breakdown (@superseb can tell us), but last time I asked, Ubuntu was far and away the preferred OS for Rancher deployments, based on the Rancher usage stats that get sent back to RancherHQ.

I started out on RHEL7, and after fighting with storage drivers, selinux config, and being forced to buy Docker Enterprise Edition (because RHEL), I switched to Ubuntu 16.04.03 LTS and have had zero issues related to OS/Docker.

**Comment by trauts2** [comment]
Were the RHEL issues you had related to getting the cluster up and running?  Or did they result in reliability issues?  Before you made the switch did you have squirely problems as well?  And are you saying that all ended once on Ubuntu?

If yes, I'm switching over this weekend.  My confidence has been really shaken by the incidents this week, if there's a path towards stability that doesn't mean falling back from Rancher I'll be very happy.

@superseb any thoughts on the above?

Thanks for sharing your experience.

**Comment by trauts2** [comment]
@superseb Another one went down hard, this time the instance was even unavailable after the incident.  syslog and var/log/messages attached

I'm not sure I've captured the right data.  Would love suggestions for what to look at next.

Also my primary concern is to create a stable 1.6.14 cattle environment.  If RHEL 7.4 or something else about my setup is suspect I'd like to jump straight to the solution.

[journalctl.txt](https://github.com/rancher/rancher/files/1712665/journalctl.txt)

[messages.zip](https://github.com/rancher/rancher/files/1712673/messages.zip)

Thanks!

**Comment by trauts2** [comment]
Attached are the full messages, dmesg prior to the availability event and cloud-init

[system-logs.zip](https://github.com/rancher/rancher/files/1713477/system-logs.zip)

**Comment by superseb** [comment]
Can you share what exact date & time the machine was unavailable, I see a lot of stuff going on in the logs. If the machine is unavailable, what is the console screenshot in AWS showing?

**Comment by trauts2** [comment]
Hi @superseb 

![image](https://user-images.githubusercontent.com/4002664/36160050-dd41709e-10a5-11e8-93ac-ea03d436dee2.png)

My probably-uninformed hunch is that the issue has to do with our installation.  The fact that this happened on 3 separate instances rules out infrastructure, which is unlikely in AWS anyway.  While it would be great to know precisely what caused the instability, I'm most concerned with getting confirmation that our installation going forward is solid and unlikely to have any such issues going forward. 

Here is the packer file used to build the original rancher worker AMI, the one where we had the issue.  I was not at the time aware of the rancher-provided docker installation scripts, I struggled to get a working install on RHEL
```
#! /bin/sh -x

# run with packer build -var-file=$HOME/.aws/builder-box-keys.json build.json
# NOTE: Built with the following AMI
#     "ami_description": "RHEL-7.4_HVM_GA-20170808-x86_64-2-Hourly2-GP2 (ami-c998b6b2)",
#     "source_ami": "ami-c998b6b2",
sudo yum update -y

sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.21-1.el7.noarch.rpm

sudo yum install -y yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum -y install docker-ce-17.12.0.ce
```

After I discovered the Rancher-provided docker installers, I created new AMIs and am as of yesterday using these in our cluster

```
#! /bin/sh -x

# run with packer build -var-file=$HOME/.aws/builder-box-keys.json build.json
#    "ami_description": "Red Hat Enterprise Linux 7.4 (HVM), SSD Volume Type - ami-26ebbc5c",
#    "source_ami": "ami-26ebbc5c",

sudo yum update -y

curl https://releases.rancher.com/install-docker/17.12.sh | sh

sudo systemctl start docker
sudo systemctl enable docker
```

For all worker nodes, we have a launch config which looks like this:
```
#cloud-config

write_files:
  - content: |
      #!/bin/bash -x
      exec 2> /tmp/rc.local.log  # send stderr from rc.local to a log file
      exec 1>&2                  # send stdout to the same log file
      SLEEP=10
      COMMAND="sudo docker run \
        -e CATTLE_AGENT_IP=\"`curl http://169.254.169.254/latest/meta-data/local-ipv4/`\" \
        -e CATTLE_HOST_LABELS=\"customer=${customer}&role=${worker_role}&environment=${environment}&traefik_lb=true\" \
        --rm --privileged \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /var/lib/rancher:/var/lib/rancher \
        rancher/agent:${agent_version} \
        http://${ha_rancher_server_dns}/v1/scripts/${rancher_server_registration_token}"
      echo `date`
      eval $COMMAND

      while [  $? -ne 0 ] ;
      do
        echo "Didn't work.  Returned $?.  Sleeping $SLEEP";
        sleep $SLEEP;
        echo `date`
        eval $COMMAND
      done
      echo "Worker started!"    
    path: /etc/rc.local
    permissions: "0755"
    owner: root:root
```

So my main question is whether the first config is likely root cause for the instability?  Second, is the current config we're using likely to be stable?

Last, do you have a recommended installation which is none of the above, which you think would maximize stability in PROD?

Thanks!

**Comment by trauts2** [comment]
Any guidance from Rancher for producing a stable cattle environment?  What are most customers using in PROD with the least number of issues?

We are continuing to have stability issues.  Any  recommendations would be appreciated.

**Comment by aemneina** [comment]
@trauts2 we have folks running RHEL hosts successfully. There's nothing in the logs that capture the failure. I was hoping for something obvious like a `dump_stack` or core dump. Core dump might actually still be present on the system if it was created. There's some persistent nagging about not  having an [ENA driver](https://access.redhat.com/discussions/3238841) installed. Not sure if that could be related. If you have one of those hosts around, it'd be great to connect and poke around on it. you can find me on user slack user name: `ahmad`.

**Comment by aemneina** [comment]
forgot to add this kinda stood out:
```
Instance isnt passing healthcheck anymore
Feb  9 20:42:52 ip-10-0-21-113 amazon-ssm-agent: 2018-02-09 20:42:52 INFO [instanceID=i-00c77d943bca3329d] [HealthCheck] HealthCheck reporting agent health.
Feb  9 20:44:54 ip-10-0-21-113 amazon-ssm-agent: 2018-02-09 20:44:54 INFO [instanceID=i-00c77d943bca3329d] [LongRunningPluginsManager] There are no long running plugins currently getting executed - skipping their healthcheck
```

**Comment by trauts2** [comment]
Thanks for investigating Ahmad.  I can bring up 2 instances that had the
failures and give you access.  I'll connect with you via Slack in ~45 min
if that's ok.

**Comment by trauts2** [comment]
Btw I opened a support ticket with AWS, they did not believe there was an issue with the instance FWIW.  Plus this has now happened numerous times in the past 6 days, only on Rancher instances.  These boxes have nothing on them other than what I have shown in the above packer script and cloud-init.

**Comment by superseb** [comment]
@aemneina @trauts2 What's the status on this?

**Comment by trauts2** [comment]
I haven't seen this in a long time.  I consider it no longer an issue.
