### ISSUE TITLE
Cluster errors and fails to finish provisioning if I use Azure nodes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11362]
**Rancher versions:** 2.0 master 2/8

**Steps to Reproduce:**
1.  Create a RKE cluster using azure node

**Results:** Cluster fails "Failed to validate cluster: User for host (1) is not provided"
![image](https://user-images.githubusercontent.com/11514927/35990491-645f2e7e-0cc1-11e8-99e6-1fee0a3e988b.png)

**Comment by StrongMonkey** [comment]
It appears that ipAddress is missing in Azure docker-machine driver. Need to modify docker-machine code to fix this.

**Comment by tfiduccia** [comment]
No Azure in RKE
