### ISSUE TITLE
ipsec connectivity check cant keep up with a large number of nodes being added

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#11372]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9 

**Infrastructure Stack versions:**
healthcheck: v0.3.3-1
ipsec: v0.2.2 (rancher/net:v0.13.7)
network-services: v0.2.8
kubernetes (if applicable): v1.8.5-rancher4

**Docker version
17.02

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ROS 1.1.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
K8S

**Steps to Reproduce:**
Scale the number of hosts, 50 in this example. The infrastructure stacks come up one by one, but at around the 30 mark for hosts IPSec health check cant seem to come up quick enough. ipsec never gets out of initializing then gets deleted.

NPE Observed
```
e="2018-02-07T23:19:06Z" level=info msg="Peer: 9cc88469-92ad-4e7f-a06f-c804d9f16044 deleted, stopping check"
2/7/2018 3:19:27 PMtime="2018-02-07T23:19:27Z" level=info msg="new peer container: {ipsec-ipsec-32   [] [0.0.0.0:500:500/udp 0.0.0.0:4500:4500/udp] ipsec 32 ipsec 0614de6f-4965-4ce4-b609-881dcc4db4a0 map[io.rancher.container.system:true io.rancher.project.name:ipsec io.rancher.service.deployment.unit:8139bbf2-0b07-48e9-8e28-48ea6d41b8e5 io.rancher.service.requested.host.id:1070 io.rancher.sidekicks:router,connectivity-check io.rancher.network.arpsync:true io.rancher.network.macsync:true io.rancher.project_service.name:ipsec/ipsec io.rancher.scheduler.global:true io.rancher.cni.link_mtu_overhead:0 io.rancher.environment.uuid:42e6de32-9c9c-43e3-a80c-67ff08e52485 io.rancher.stack_service.name:ipsec/ipsec io.rancher.service.hash:46a7af875e9f796239e1652d545e5a4ffbba7e4c io.rancher.service.launch.config:io.rancher.service.primary.launch.config io.rancher.stack.name:ipsec] 109 e423fc2a-ed6c-4e14-91bf-46d6941eb7e8 223cddc0-bf8d-4b74-81da-53b148a1ff9a starting   0 0 0 [169.254.169.250] [ipsec.rancher.internal ipsec.ipsec.rancher.internal rancher.internal] []  4d95b8ce-38af-457a-8add-f4564e9f945a map[] true 42e6de32-9c9c-43e3-a80c-67ff08e52485 {0 0 0  0 0}}"
2/7/2018 3:19:27 PMpanic: runtime error: invalid memory address or nil pointer dereference
2/7/2018 3:19:27 PM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x692abc]
2/7/2018 3:19:27 PM
2/7/2018 3:19:27 PMgoroutine 18 [running]:
2/7/2018 3:19:27 PMgithub.com/rancher/connectivity-check/checker.(*Peer).consider(0xc4201e52c0, 0x851d58)
2/7/2018 3:19:27 PM    /go/src/github.com/rancher/connectivity-check/checker/peer.go:144 +0xdc
2/7/2018 3:19:27 PMgithub.com/rancher/connectivity-check/checker.(*Peer).Consider(0xc4201e52c0, 0x0)
2/7/2018 3:19:27 PM    /go/src/github.com/rancher/connectivity-check/checker/peer.go:164 +0x6c
2/7/2018 3:19:27 PMgithub.com/rancher/connectivity-check/checker.(*PeersWatcher).doWork(0xc4200e02d0)
2/7/2018 3:19:27 PM    /go/src/github.com/rancher/connectivity-check/checker/watcher.go:134 +0x769
2/7/2018 3:19:27 PMgithub.com/rancher/connectivity-check/checker.(*PeersWatcher).Run(0xc4200e02d0)
2/7/2018 3:19:27 PM    /go/src/github.com/rancher/connectivity-check/checker/watcher.go:159 +0xcb
2/7/2018 3:19:27 PMcreated by github.com/rancher/connectivity-check/checker.(*PeersWatcher).Start
2/7/2018 3:19:27 PM    /go/src/github.com/rancher/connectivity-check/checker/watcher.go:168 +0x77
2/7/2018 3:19:42 PMtime="2018-02-07T23:19:42Z" level=info msg="Waiting for metadata"
2/7/2018 3:19:42 PMtime="2018-02-07T23:19:42Z" level=info msg="Listening on /tmp/log.sock"Ȁ
```

**Comment by robertrbruno** [comment]
We have been seeing a similar issue with a cluster roughly this size.  We see the ipsec containers to continue to blip up and down well after we have installed new nodes.   Are there any workarounds to this issue for the time being?

**Comment by deniseschannon** [comment]
Available with `rancher/net:v0.13.10`

**Comment by sangeethah** [comment]
Following scenarios need to be validated:
1. Add 50 hosts at the same time to environment. Make sure ipsec starts successfully on all of them.
2. Test for health check containers present in "Inactive" host that gets powered down.
3. Start with 1.6.12 setup having 20 nodes. Upgrade to 1.6.15 and make sure that ipsec upgrade does not have any issues.
4. Upgrade from 1.6.12 setup having few inactive  nodes along with active nodes. Make sure ipsec upgrade works as expected.

**Comment by moelsayed** [comment]
~~1. Start with 10 hosts. Then add 50 hosts at the same time to environment. Make sure ipsec starts successfully on all of them.~~ Test case validated successfully.

**Comment by sangeethah** [comment]
Tested with latest build from 1.6 branch:

For use case ```2. Test for health check containers present in "Inactive" host that gets powered down.```

Following use case worked successfully:

1. Deploy a service that is health check enabled with scale 3.
2. Deactivate one of the hosts ,  that had 2 instances of the service .
3. Power down this host.
4. The 2 instances of the service on the inactive host gets marked as being unhealthy and gets recreated successfully in other hosts in the setup.

**Comment by moelsayed** [comment]
~~3. Start with 1.6.12 setup having 20 nodes. Upgrade to 1.6.15 and make sure that ipsec upgrade does not have any issues. Add 10 hosts at at 1 time.~~  Tested by upgrading from 1.6.12 to 1.6.15-rc6. Test case validated successfully.

~~4. Upgrade from 1.6.12 setup having few inactive nodes along with active nodes. Make sure ipsec upgrade works as expected.~~ Tested by upgrading 1.6.12 to 1.6.15-rc7 on a 10-host setup with 3 inactive hosts. Test case validated successfully.
