### ISSUE TITLE
Deleted users continues to have access to resources.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11378]
Rancher versions: v2.0.0-alpha16

Steps to reproduce the problem:
As admin user , Create a cluster - c1.
Create a standard user1 - user1.
Add user1 as "cluster-owner" for cluster c1.
Using kube config generated for user1 , add to create namespace.

As part of deleting user1 , all the clusterRoleTemplateBindings for this user does not get deleted.
Cluster1 still references cluster role bindings for user1.

Using kube config generated for user1 , we are still able to get access to existing namespaces in this cluster c1 and also able to create new namespace.

Expected behavior:
As part of deleting user1 , all the clusterRoleTemplateBindings for this user should get deleted.
Using kube config generated for user1 should not provide access to any resource in cluster c1.

**Comment by soumyalj** [comment]
Tested with master from March 1st. Still see the issue above.
As admin user , Create a cluster - c1.
Create a standard user1 - user1.
Add user1 as "cluster-owner" for cluster c1.
Using kubeconfig generated for user1 ,  create namespace.
Delete user1 from the global level by logging in as admin
As part of deleting user1 , all the clusterRoleTemplateBindings for this user do not get deleted.
Cluster1 still references cluster role bindings for user1.
Through the user1's kubeconfig we can still create a new namespace and create more pods in the namespace

**Comment by sangeethah** [comment]
Tested with latest build from 2.0 master:

When trying to access a deleted user (who was a cluster owner previously), following error message is presented:

```kubectl get pods
Error from server (InternalError): an error on the server ("{\"Cause\":null}") has prevented the request from succeeding```

Reopening this issue to see if better error message can be provided to the user.
