### ISSUE TITLE
Unable to deploy host to eu-west-3 (Paris). The zone is not available from the list.

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#11376]
**Rancher versions:**
rancher/server: 1.6.14

**Type/provider of hosts: AWS**

**Setup details:**
HA + RDS
**Environment Template: Cattle**

**Steps to Reproduce:**
Try to add host to AWS eu-west-3.
**Results:**
Zone eu-west-3 is not on the list.

**Comment by superseb** [comment]
This was added in docker/machine here: https://github.com/docker/machine/pull/4373. Not in a release yet. Labelling as UI.

**Comment by deniseschannon** [comment]
@superseb It's not only UI. It would require machine changes in Rancher. 

This doesn't look like it's in an official Docker Machine release yet. We'd need to have it released in Docker Machine, update our `rancher/machine-package` to use that version of Docker Machine, update the machine package in cattle, and after all that is done, then we could update UI. :)

**Comment by deniseschannon** [comment]
Backend has been updated for machine v0.14.0. Need UI changes to introduce this region.

**Comment by deniseschannon** [comment]
Available with `v1.6.15-rc6`

**Comment by tfiduccia** [comment]
Version - v1.6.15-rc6
Verified fixed
