### ISSUE TITLE
kubectl exec returns errors

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#11370]
When attempting to run kubectl exec an error is received:
`error: unable to upgrade connection: you must specify at least 1 of stdin, stdout, stderr`

The path that is trying to be used is:
`POST https://165.227.1.234/k8s/clusters/cluster-m2sk2/api/v1/namespaces/default/pods/nginx-7c87f569d-stdtt/exec?command=ls&container=nginx&container=nginx&stdin=true&stdout=true&tty=true`

**Comment by sangeethah** [comment]
Tested with latest 2.0 build from master:

This issue is still seen:
```
Sangeethas-MBP:santest1 sangeethahariharan1$ kubectl  exec hello1-c4548cf98-c9rcg bash
error: unable to upgrade connection: you must specify at least 1 of stdin, stdout, stderr
```

When exec option is used from UI following error seen:

```
Request URL:wss://<ip>/k8s/clusters/cluster-hd8wf/api/v1/namespaces/default/pods/hello1-c4548cf98-c9rcg/exec?container=hello1&stdout=1&stdin=1&stderr=1&tty=1&command=%2Fbin%2Fsh&command=-c&command=TERM%3Dxterm-256color%3B%20export%20TERM%3B%20%5B%20-x%20%2Fbin%2Fbash%20%5D%20%26%26%20(%5B%20-x%20%2Fusr%2Fbin%2Fscript%20%5D%20%26%26%20%2Fusr%2Fbin%2Fscript%20-q%20-c%20%22%2Fbin%2Fbash%22%20%2Fdev%2Fnull%20%7C%7C%20exec%20%2Fbin%2Fbash)%20%7C%7C%20exec%20%2Fbin%2Fsh
Request Method:GET
Status Code:400 Bad Request
```

**Comment by deniseschannon** [comment]
@ibuildthecloud had broke exec with a refactor and re-fixed it. can you re-test @sangeethah ?

**Comment by sangeethah** [comment]
Tested with latest 2.0 build from master.

Able to exec to pods successfully using ```kubectl exec``` and UI.
