### ISSUE TITLE
How to change io.rancher.container.dns.priority from 0.27

### ISSUE THREAD

**Issue by zyhnjust** [rancher/rancher#11384]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services: 0.2.7
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Hi Guys, 
Before I use rancher 1.6.10. This time I use rancher 1.6.14. 
Found the /etc/resolv.conf, search domain does not include "rancher.internal" related. That will lead to my service not work. 
I searched it is changed in R0.2.7 for network service. It mentioned that "Added ability to avoid adding rancher internal search domains if "io.rancher.container.dns.priority" is None."

How to change this property to make it work in 1.6.14? Thanks. 
I try to change it in rancher env, but did not find this attribute. 
 
https://github.com/rancher/rancher/releases/tag/v1.6.11

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by superseb** [comment]
That label was added to avoid Kubernetes components to show the error regarding search domains. This is not needed in any Cattle environment. If the domains do not get added, can you share the stack definition you are using where the domains do not get added?

**Comment by zyhnjust** [comment]
Thanks @superseb , I am using K8s template, and I referred the K8s Master via `https://kubernetes:6443`, but after upgraded to Rancher `v1.6.14`, it cannot find the master. Seems that the only way is to change it to `https://kubernetes.kubernetes.rancher.internal:6443`.

So is there a way to config it to original search domain - adding `kubernetes.rancher.internal` in `resolv.conf` ?

**Comment by superseb** [comment]
Where and how are you referring to the k8s master? If this broke something we should check it out.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
