### ISSUE TITLE
Ability to disable populating of cacerts when using external SSL termination with a well known CA

### ISSUE THREAD

**Issue by nlowe** [rancher/rancher#11388]
**Rancher versions:**
rancher/server: `v2.0.0-alpha16`
rancher/agent: N/A

**Infrastructure Stack versions:**
kubernetes (if applicable): `1.8.7-rancher1-1`

**Docker version: (`docker version`,`docker info` preferred)**
<details>
<summary>Docker Version</summary>

```
Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:11:05 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:09:37 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

</details>

<details>
<summary>Docker Info</summary>

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953GiB
Name: rancher
ID: ZN3Z:VZTN:HYNS:6GVJ:QDPE:3LC2:XS37:3RK7:X7M2:IO4Q:3LIB:2QMQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

<details>
<summary>/etc/os-release</summary>

```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

</details>

**uname -r**: `4.4.0-112-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single rancher 2.0 node, 3 master / etcd 2 worker RKE k8s cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

k8s

**Steps to Reproduce:**

1. Start Rancher 2.0 with `--http-only`
2. Create or adopt a k8s cluster
3. Download the kubeconfig that rancher generates for the added cluster
4. `kubectl get nodes`

**Results:**

This file contains a `certificate-authority-data` entry for the cluster, which causes `kubectl` to fail with `Unable to connect to the server: x509: certificate signed by unknown authority` as it does not match the certificate that rancher is actually behind. Deleting this section from the kubeconfig allows it to work again.

I started rancher with `--http-only` as I wanted to use my own PKI infrastructure and didn't see a way to do this in the 2.0 quickstart guide. I'm running rancher behind nginx with my own certificate.

**Comment by superseb** [comment]
The CA certificate data is also used when adding nodes (`--ca-checksum`). It resides in `v3/settings/cacerts`, if you want to resolve the issue for now, you can edit your cacert data in there and it should generate correctly.

**Comment by vincent99** [comment]
Http only exists to provide your own termination, not to expose directly as http.  The session cookie for the UI is marked secure (https only).

**Comment by alena1108** [comment]
Based on conversation with @vincent99:

1) `--http-only` is no longer supported in latest rancher version
2) If you want to do your own termination you still need to give us the expected cacerts if it's not a recognized CA. You will be able to set them using global setting. Custom certificate will display the default one in generated kubeconfig.

Edit option for settings will most likely be available in UI post beta, moving the milestone. @deniseschannon

**Comment by vincent99** [comment]
@alena1108 seems like there's a case missing here for doing external all termination and using a cert signed by a real CA that will already be recognized everywhere.  How do you disable the generation of the self-signed one that ends up in the cacerts setting and the return of that in generated kubeconfig files?

**Comment by dnauck** [comment]
We use the Windows WebApplicationProxy, shipped with Windows server 2016, as our only public HTTPS endpoint and expose ADFS, SSTP-VPN and all other services (with SSL Termination) with it. We also use Let's Encrypt certificates updated by some powershell scripts on this proxy. So it would be nice, if we expose the rancher-ui, to only manage SSL and certificates on the proxy and not in rancher itself.

**Comment by superseb** [comment]
Renamed this, we have docs on all situations but this case still requires cleaning of the `cacerts` in the `rancher/rancher` containers which would be nice if we didn't have to clean them.

**Comment by timgriffiths** [comment]
@superseb, Pretty sure i facing this issue as well, i am trying to use a well known CA, how do i clean the rancher container?

**Comment by ibuildthecloud** [comment]
This simplest thing at the moment is to just populate cacerts with the proper change for your cert.  That will of course work, but I understand it's more effort that really needed.  @alena1108 I see no other approach to make this work except to add an explicit argument like `--no-cacert` in which we clear the cacerts setting.

The problem is that even if the users doesn't want to give rancher the SSL certs (because it's externally terminated) we have to run SSL.  So we have to generate a cert.  So it's really hard to tell the difference between "you really want a self signed cert" or "externally terminating."

Maybe we just add an argument for `--external-ssl` in which we generate a cert for internal use but not populate the cacerts settings that impacts kubeconfig.

**Comment by ibuildthecloud** [comment]
This has impact on the HA setup, of course.  We really need to get https://github.com/rancher/cli/pull/160 working as it's getting to hard to configure the k8s yaml properly for HA.

**Comment by alena1108** [comment]
Added a setting based disabling for ca certs setting generation. @rawmind0 have to pass this flag to the rancher start in HA mode if needed

**Comment by rawmind0** [comment]
@alena1108 , updated PR https://github.com/rancher/cli/pull/160 adding `--no-cacerts` argument to rancher server, when using public ca (no cacert info provided), for tls-mode external and ingress

**Comment by deniseschannon** [comment]
To set up Rancher for HA, we're going to move away from using CLI and using a helm chart. 

We need to test the initial issue reported to see if it works with `--no-cacerts`.

**Comment by adingilloRancher** [comment]
Master 6/8/18

Followed initial steps post fix. 

Steps to Reproduce:

Start Rancher 2.0 with --http-only
Create or adopt a k8s cluster
Download the kubeconfig that rancher generates for the added cluster
kubectl get nodes

Verified ability to get nodes with remote kubectl.

**Comment by sax1johno** [comment]
> Master 6/8/18
> 
> Followed initial steps post fix.
> 
> Steps to Reproduce:
> 
> Start Rancher 2.0 with --http-only
> Create or adopt a k8s cluster
> Download the kubeconfig that rancher generates for the added cluster
> kubectl get nodes
> 
> Verified ability to get nodes with remote kubectl.
> 

--http-only flag is not recognized in v2.0.8

**Comment by superseb** [comment]
See https://rancher.com/docs/rancher/v2.x/en/installation/single-node/ 
```Option C—Bring Your Own Certificate: Signed by Recognized CA```
```
docker run -d --restart=unless-stopped \
    -p 80:80 -p 443:443 \
    -v /<CERT_DIRECTORY>/<FULL_CHAIN.pem>:/etc/rancher/ssl/cert.pem \
    -v /<CERT_DIRECTORY>/<PRIVATE_KEY.pem>:/etc/rancher/ssl/key.pem \
    rancher/rancher:latest --no-cacerts
```

**Comment by jamelseagraves** [comment]
@superseb I followed your last comment to the letter, but I still get `Unable to connect to the server: x509: certificate signed by unknown authority` when I run any `kubectl` commands. I am using the v2.1.2. I am curious if the `--no-cacerts` argument is being properly applied at runtime?

**Comment by superseb** [comment]
`--no-cacerts` will make sure `https://rancher_url/v3/settings/cacerts` is empty. What CA are you using? You might be missing an intermediate in the server certificate.

**Comment by jamelseagraves** [comment]
@superseb Okay, so I checked that and it is empty. I am using GoDaddy CA. I made sure to include the full chain in the certificate. Could my CA not be one of the recognized ones?

**Comment by jamelseagraves** [comment]
Doh! I just realized I still had the old cacert in my kubeconfig. Once I removed that, it works now!
