### ISSUE TITLE
[bug] Operation cannot be fulfilled on machinedrivers.management.cattle.io "otc"

### ISSUE THREAD

**Issue by RainingNight** [rancher/rancher#11382]
**Rancher versions:**
rancher/server: 2.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.12.0-ce, build c97c6d6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS (Xenial Xerus) 4.4.0-113-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Results:**

```bash
sudo docker run -p 8080:80 rancher/server:preview
```

Output:
E0211 07:20:29.071273       1 generic_controller.go:191] MachineDriverController otc [machine-driver-controller] failed with : Operation cannot be fulfilled on machinedrivers.management.cattle.io "otc": the object has been modified; please apply your changes to the latest version and try again

**Comment by loganhz** [comment]
Close this issue for rancher preview version. It has been fixed in rancher v2.0.4
