### ISSUE TITLE
container-crontab stops working for a stack when it is renamed

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#11398]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3-1
ipsec: 0.2.2
network-services: v0.2.8
scheduler: v0.8.3
kubernetes (if applicable):
**container-crontab: v0.3.0**

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

# uname -r
4.4.0-108-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
IBM Cloud

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External DB and LB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create a new environment and add hosts to it.
1. Deploy the `container-crontab` infrastructure stack.
1. Deploy a user stack (`my-app`) that contains a service with the `cron.schedule` label (.e.g: `cron.schedule: "@hourly"`).
1. Rename the user stack (`my-app-renamed`).

**Results:**

Up until step 3, everything works as expected (i.e.: the service that has the `cron.schedule` label will be started every hour).

From step 4 onwards, the same service will no longer start every hour, and the `container-crontab` logs will repeatedly (every 5s) print the following error message.

```
time="2018-02-13T14:49:00Z" level=error msg="Error 404 accessing /stacks/my-app path"
time="2018-02-13T14:49:05Z" level=error msg="Error 404 accessing /stacks/my-app path"
```

I believe this problem is caused by the fact that `container-crontab` relies on container labels to find stack names, and those don't change when the stack name changes.

**Comment by soumyalj** [comment]
Tested with 1.6-development master using container-crontab version 0.5.0
1. Deploy the container-crontab infrastructure stack.
2. Deploy a user stack teststack that contains a service with the cron.schedule label (0 */1 * * * *) and cron.action=restart 
3. Rename the user stack (teststack-new)
The containers of the service restarted every minute as expected.
