### ISSUE TITLE
Vault - Instance fails to get allocated if it was initially allocated to a host that went to "reconnecting" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11395]
Rancher versions: Build from 1.6 branch

Steps to Reproduce:
Have an environment with 2 hosts (say h1 and h2) with "secrets-bridge-v2" service deployed.
Bring down the host where secrets-bridge-v2-server is currently running say h1.

When host -h1 is still not gotten to "reconnecting" state , start  a new service with volume having " secrets-bridge-v2" volume driver.
When the service instance lands on h1 , it errors out since the host is actually not reachable as expected and gets to "Error" state. 
On service reconcile , instance is not able to start successfully on other hosts even after  host h1 gets to "reconnecting" and "disconnected" state.

```Failed to allocate instance [container:1i332]: Bad instance [container:1i332] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [instanceReservation: 1].```
Following the allocation error seen:

In Storage Pool UI , volume associated with this instance is still listed in "Inactive" state under the host that is currently in "disconnected" state 
 Inactive	test1_vault-token_8_d1f9f30d-5821-43d3-8daf-6481cc247312_d6913

**Comment by StrongMonkey** [comment]
@sangeethah does the service have health-check on it? if not, isn't it supposed to stay in the current host?

**Comment by sangeethah** [comment]
I did not have health check on when testing this case. But even with health check not enabled instance that have volumes in one of our volume drivers we see this issue - https://github.com/rancher/rancher/issues/10716.

**Comment by deniseschannon** [comment]
Per this comment: https://github.com/rancher/rancher/issues/10716#issuecomment-372487696, the healthcheck reasoning is not applicable.
