### ISSUE TITLE
Cannot Add new host 

### ISSUE THREAD

**Issue by SofianeB** [rancher/rancher#11397]
Everything was working until today.

**Rancher versions:**
rancher/server: stable
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: 0.0.3
ipsec: rancher/net:v0.13.7
network-services: rancher/network-manager:v0.7.19
scheduler:0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-693.17.1.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 
**Steps to Reproduce:**
docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 http://ip:8080/v1/scripts/...
**Results:**
INFO: Running Agent Registration Process, CATTLE_URL=http://ip:8080/v1
INFO: Attempting to connect to: http://ip:8080/v1
ERROR: http://ip:8080/v1 is not accessible (Failed to connect to ip port 8080: No route to host)

**Comment by superseb** [comment]
There is no route to ip. Assuming that the IP is still correct (and the host registration URL is still configured correctly, this can be due to firewall (iptables/firewalld) on the host running `rancher/agent` and/or `rancher/server`. Or even in between those hosts.

**Comment by SofianeB** [comment]
I am running all in one host, so rancher/server and rancher/agent are in the same host. 
When I run 

`docker run rancher/agent:v1.2.9` manually I got this:
Cannot connect to the Docker daemon. Is the docker daemon running on this host

**Comment by superseb** [comment]
- What IP is show in the `http://ip:8080` error? Is is the IP on eth0, docker0, other veth?
- What is configured as Host Registration URL? (`Admin` -> `Settings`)
- If you want to check manually, exec into the `rancher-agent` container and run `ping ip` and `curl http://ip:8080`

**Comment by ItsReddi** [comment]
You said that its the same host as rancher server
Did you add?
-e CATTLE_AGENT_IP=<IP_OF_RANCHER_SERVER>
see:
http://rancher.com/docs/rancher/v1.6/en/hosts/custom/#adding-hosts-to-the-same-machine-as-rancher-server

**Comment by SofianeB** [comment]
* IP on eth0
* Host Registration URL is the same as the host running rancher/server
* I can not "exec" into the rancher-agent since it is not running

I am trying the option with CATTLE_AGENT_IP @ltsReddi

**Comment by superseb** [comment]
Usually it's a local firewall blocking access, is `firewalld` running on the machine? `systemctl status firewalld` ?

**Comment by SofianeB** [comment]
● firewalld.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)

**Comment by superseb** [comment]
Can you run the agent (or any container) and trace the steps that are executed:

```
# Run agent container
docker run -ti --entrypoint bash rancher/agent:v1.2.9

# Get route to IP
ip route get IP_OF_RANCHER_SERVER

# Ping
ping IP_OF_RANCHER_SERVER

# Curl
curl IP_OF_RANCHER_SERVER
```

**Comment by SofianeB** [comment]
* ip route get IP_OF_RANCHER_SERVER returns:
IP_OF_RANCHER_SERVER via 172.17.0.1 dev eth0  src 172.17.0.3 
cache

* ping works and also curl it returns HTML.

**Comment by superseb** [comment]
Sorry, curl needs to go to the correct port and should return JSON

```
# Curl
curl IP_OF_RANCHER_SERVER:PORT
```

If you can let me take a look at the setup, ping me on Rancher Users Slack (https://slack.rancher.io)

**Comment by SofianeB** [comment]
There was no communication between containers and the host (Rancher server). 
Check with iptables if necessary. 
Maybe it can help other @superseb

**Comment by superseb** [comment]
Communication between host and container bridge network was impossible. As it worked before, the assumption is some change in iptables. 

We verified it working adding a rule to allow communication from docker0:

```
iptables -I INPUT 4 -i docker0 -j ACCEPT
```

**Comment by xgenvn** [comment]
@superseb I'm trying with PhotonOS and Rancher server/agent on same photon instance. Your solution does help, thanks a lot.

**Comment by zdYng** [comment]
My problem has been solved. The previous problem was because the firewall was not shut down, causing network congestion.

**Comment by Malika94** [comment]
i have the same problem can you help me please?

**Comment by sebma** [comment]
Related #50299
