### ISSUE TITLE
GitHub Enterprise authentication stops working and rancher redirects to public github.com

### ISSUE THREAD

**Issue by khourybrazil** [rancher/rancher#11401]
**Rancher versions:**
rancher/server: rancher/enterprise:v1.6.10
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-123-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.798GiB
Name: redactedhostname
ID: VZOU:M4LQ:JALB:6INX:CAJW:3PR7:GOFQ:ZIUJ:JCOK:YBCO:QDTH:EAYS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: redacted
Https Proxy: redacted
No Proxy: localhost,redacted
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 redacted
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.13.0-123-generic
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
The only change made was changing what users/organizations were permitted to login but it may have started before that.

**Results:**
I enabled debug logging with `insert into setting (name,value) values ('auth.service.log.level', 'DEBUG');`

On startup the log displays the following:
```
level=debug msg="Settings from db for provider github: map[api.auth.github.client.secret:**** api.github.domain: api.github.scheme:https:// api.auth.github.client.id:<REDACTED>]"
```
Attempting to login results in this log entry:
```
level=debug msg="GetRedirectURL: returning response map[redirectUrl:https://github.com/login/oauth/authorize?client_id=<redacted>&scope=read%3Aorg provider:github]"
```

Seems like it thinks `api.github.domain` isn't configured but it's present in the DB. I took a quick look at the github provider in the auth_server repo and the redirection to public github.com seems consistent with `api.github.domain` not being configured.
```
mysql> select * from setting where name='api.github.domain';
+----+-------------------+----------------------+
| id | name              | value                |
+----+-------------------+----------------------+
|  9 | api.github.domain | ghe.example.com |
+----+-------------------+----------------------+
1 row in set (0.01 sec)
```

At first I thought I ran into #10434 but the scheme appears to be reflected correctly in the debug log and database.

**Comment by superseb** [comment]
We had 2 issues regarding GitHub Enterprise, https://github.com/rancher/rancher/issues/10247 and https://github.com/rancher/rancher/issues/10434. Both UI related. Can you try v1.6.14 and see if this helps?
