### ISSUE TITLE
Add Pipeline into 2.0

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11400]
Disabled by default, Enabling will install Jenkins.
Support Github Oauth.
Support to checkout Github repository, run script based on docker image, build and publish image

Main Features:
1. Create pipeline 
2. Setup Pipeline in cluster level
3. Trigger Pipeline when submit GitHub commit
4. Push image to registry 
5. View execution details

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Pipeline in, all bugs entered separately from this issue.
