### ISSUE TITLE
Trying to add a host by establishing an ssh tunnel to the rancher server as the agent's outgoing traffic port is filtered & I'm not able to connect to Rancher url normally, but can establish ssh tunnel.

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#11405]
**Rancher versions:**
rancher/server: 1.16.15-rc4
rancher/agent: 1.2.10-rc3

**Docker version: 1.13.1**

**Operating system and kernel: Ubuntu 16.04**

**Environment Template: Cattle**

**Steps to Reproduce:**
Trying to add a host by establishing an ssh tunnel to the rancher server as the agent's outgoing traffic port is filtered & I'm not able to connect to Rancher url, but can establish ssh tunnel.
`autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -NL 8080:localhost:8080 `rancher@123.123.123.123
telnet 127.0.0.1 4444 works ok

Then trying to use this tunnel for agent/server communication:
`docker run -d -e CATTLE_AGENT_IP=321.321.321.321 --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.10-rc3 http://127.0.0.1:4444/v1/scripts/blahblahblah1:blahblahblah2:blahblahblah13`
**Results:**
"ERROR: CATTLE_URL cannot contain localhost or 127.0.0.1, please check the Host Registration URL."

Is there a way to establish an ssh tunnel & connect like that or not?

**Comment by loganhz** [comment]
127.0.0.1 or localhost is not a valid registration URL
Please check  https://github.com/rancher/rancher/pull/9376
