### ISSUE TITLE
The Beta 2.0 is due today February 14. What time (UTC) & place? :)

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#11414]
**Rancher versions:**
rancher/server: 1.6.15-rc4

**Steps to Reproduce:**
Check https://github.com/rancher/rancher/milestones
See `Due by February 14, 2018`
Check the calendar: `February 14, 2018`

**Results:**
No download link yet :(

Thanks!

**Comment by deniseschannon** [comment]
Our milestones for 2.0 have been dev complete dates and don't account for what QA or other items that might come up in the development process. 

There will be an an announcement for our Beta in github and in our forums when it's ready for public consumption.
