### ISSUE TITLE
During GKE provisioning, errors appears between when the cluster is up in GKE and it's fully registered and active in Rancher

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11410]
Provisioning a new GKE cluster (using new workflow), it will show provisioning state and status for awhile. 

<img width="328" alt="screen shot 2018-02-13 at 2 37 50 pm" src="https://user-images.githubusercontent.com/11410997/36177723-7a700f36-10cb-11e8-8d0a-f43607d6528e.png">

After the cluster is up and active in k8s, in Rancher it seems to throw an error. 

<img width="505" alt="screen shot 2018-02-13 at 2 38 48 pm" src="https://user-images.githubusercontent.com/11410997/36177783-a8324e70-10cb-11e8-8118-ac3bf8f9c456.png">

It will be stuck in `Updating` state for a bit and then when the node is registered in Rancher (the node/node stats show up), the cluster state will be `Unavailable`

<img width="429" alt="screen shot 2018-02-13 at 2 39 49 pm" src="https://user-images.githubusercontent.com/11410997/36177852-d3fd27f0-10cb-11e8-9f7b-acdc404fb4a6.png">

And then after a little bit, the cluster will be active.

**Comment by nathan-jenan-rancher** [comment]
What is the expected behavior?

**Comment by deniseschannon** [comment]
Ideally, it should go from provisioning to active, or if we have these other transitioning states, don't throw error (which shows the status as red)

**Comment by deniseschannon** [comment]
There is a new `Waiting` state that's blue instead of `Unavailable` and red when waiting for the API server to come up during provisioning.
