### ISSUE TITLE
[cli] Suggestion to update go-prompt v0.2.1

### ISSUE THREAD

**Issue by c-bata** [rancher/rancher#11421]
Hi! I'm an author of go-prompt. Thank you for using at rancher CLI.

Today I've released go-prompt v0.2.1 which includes many improvements without breaking api changes (See [CHANGELOG](https://github.com/c-bata/go-prompt/blob/master/CHANGELOG.md) for more details).

Especially v0.2.0 release includes bugfix causing the breakage of a layout on terminal.app(macOS), GNU terminal(Ubuntu). And feature of scrollbar is also supported in this version. This is useful when there are too many matched suggestions.

[![scrollbar feature](https://github.com/c-bata/assets/raw/master/go-prompt/pagination.gif)]()

I hope go-prompt helps rancher more useful.
Thanks.

**Comment by superseb** [comment]
@c-bata Thanks for the issue and the tool. We are currently overhauling the CLI for 2.0 and I notified the creator/maintainer to update vendor as soon as he starts working on the prompt part.
