### ISSUE TITLE
Feature/Bug requests: return all host through api, and let a filter do its work?

### ISSUE THREAD

**Issue by BobVanB** [rancher/rancher#11435]
**Rancher versions:**
rancher/server:v1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:46 2017
  OS/Arch:      linux/amd64
  Experimental: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`Bare-metal`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
`HA rancher, external DB`

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
`Cattle`

**Steps to Reproduce:**
1. create an environment
2. add a host
3. remove a host (or purge after)
4. Find the host through the api:
`http://rancher/v2-beta/projects/<id>/hosts?state=removed`

**Results:**
* no hosts in data field.
```
"data": [ ],
```

**Expected Results:**
Give all hosts back that ever been connected to the environment (project) and let me filter.

**Comment by vincent99** [comment]
Removed/purging/purged resources are only returned if specifically requested by ID and rows are physically removed from the table after a delay interval.  The API is not designed to store the history of the world for deriving usage stats like you're trying to do.

**Comment by BobVanB** [comment]
No response
