### ISSUE TITLE
During provisioning that uses RKE (custom/node pools), while waiting for the hosts to come up, the cluster will show "Unavailable" and "Waiting for API to be available"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#11443]
<img width="1268" alt="screen shot 2018-02-15 at 10 04 43 am" src="https://user-images.githubusercontent.com/11410997/36275598-249e17f8-1240-11e8-8091-07728194ca8a.png">

**Comment by StrongMonkey** [comment]
@deniseschannon are you complaining about the color or the error message words?

**Comment by deniseschannon** [comment]
I'm complaining that it looks like we failed at provisioning after the containers running rke components are launched and we're just waiting for them to start up. We should be still in a "provisioning" state while we wait for the api to be available.

**Comment by StrongMonkey** [comment]
what do you think @vincent99? Seems like we did this for a reason: if the cluster is unavailable then we show red alert. The transitioning is set to `yes` so i guess you add that red flag for a reason.

**Comment by deniseschannon** [comment]
There is a new Waiting state that's blue instead of Unavailable and red when waiting for the API server to come up during provisioning.
