### ISSUE TITLE
proxy and vmware vsphere provisionning

### ISSUE THREAD

**Issue by bsauvajon** [rancher/rancher#11442]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.0
ipsec: 0.1.3
network-services: 0.2.5
scheduler: 0.6.3

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian 8 (3.16.0)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vsphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I try to create a new host on vsphere infrastructure.
Rancher is configured to use a proxy to be able to download the catalogs, and the no_proxy variable has been set to ignore proxy when accessing my local urls.
During host creation, rancher sends a PUT directly to the ESXi server using the ip address instead of the fqdn, so the request is sent to the proxy, which is not allowed to access my ESXi server admin address

So, I've got this error message  :
Error in driver during machine creation: Put https://172.17.4.16:443/guestFile?id=54&token=52e9ad3d-3256-05f9-0e50-577fc1adc61654: Filtered

As it is not possible to exclude an ip range using the no_proxy variable, is there a way to make Rancher use the ESXi fqdn instead of the ip address to send this request ?

**Comment by superseb** [comment]
This seems to be hardcoded in the used VMware Go library here: https://github.com/vmware/govmomi/blob/b227a2582a9e5175fc778fc6a03b98aa14534927/guest/file_manager.go#L168. There seems to be quite some noise on IPs in NO_PROXY, you can try putting the IP mentioned in it and see if it accepts it?

**Comment by bsauvajon** [comment]
With the ip address in the no_proxy it works, but it requires to have each ESXi ip address in the variable so it is very hard to maintain.
Maybe I should open an issue in the VMware Go libray ?

**Comment by superseb** [comment]
Seems like they explicitly want an IP to avoid other problems. Possible they want to make a toggle for it but they changed it for a reason I assume. Let me know if we can help any further from our side.

**Comment by janeczku** [comment]
Theoretically, adding the subnet of the ESXi hosts to the `NO_PROXY` environment variable passed to Rancher should be enough to prevent the vSphere driver to proxy requests.

The reason this does not actually work today is that machine drivers are built with Go 1.9 whose stdlib does not support CIDR notation in the NO_PROXY environment variable.

https://github.com/rancher/machine-package/blob/master/Dockerfile.dapper#L14

To fix this, machine drivers must be compiled with Go 1.10 or higher.
