### ISSUE TITLE
Any plans to support a collection of hosts as a docker machine provider for Rancher?

### ISSUE THREAD

**Issue by dx9** [rancher/rancher#1144]
Something like this? 

1- Install RancherOS on bare metal with a service that would register with Rancher as a machine provider.
2 - Rancher would now be able to add hosts using the provider.
3 - When a host is added, the provider service would kick up a RancherVM on a provider host. The RancherVM would then register with Rancher as an environment host.

**Comment by vincent99** [comment]
@ibuildthecloud ?  This seems like a nice way to do multi-tenant-safe "shared" hosts.

**Comment by will-chan** [comment]
This is something @cjellick is working on.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
