### ISSUE TITLE
"Allocation failed: No healthy hosts meet the resource constraints: [instanceReservation: 1]" after upgrading from 1.6.11 to 1.6.14 

### ISSUE THREAD

**Issue by cloud-rocket** [rancher/rancher#11458]
I am no longer able to update stack containers after upgrading from Rancher 1.6.11 to 1.6.14

Upgrades/Rollbacks fail with the following error:
`Failed to allocate instance [container:1i137832]: Bad instance [container:1i137832] in state [erroring]: Allocation failed: No healthy hosts meet the resource constraints: [instanceReservation: 1].`

When restarting the host - everything works ok until trying to upgrade - once again same error

Any ideas?
Thanks

**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.13.5 or 0.13.7 (tried both)
network-services: 0.7.18 or 0.7.19 (tried both)
scheduler: 0.8.3  
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 52
 Running: 44
 Paused: 0
 Stopped: 8
Images: 32
Server Version: 17.09.1-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 11.56GB
 Data Space Total: 159.1GB
 Data Space Available: 147.6GB
 Metadata Space Used: 6.701MB
 Metadata Space Total: 163.6MB
 Metadata Space Available: 156.9MB
 Thin Pool Minimum Free Space: 15.91GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.77-31.58.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 30.42GiB
Name: ip-10-10-10-60
ID: VOSR:TJ3D:L5OZ:BR7D:YBKG:IZOL:GMVV:2YJI:LWGY:ZETK:RW5H:TPQG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Internal DB
Server is running on separate server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

**Results:**

**Comment by cloud-rocket** [comment]
I think I found the problem:

The host had the following labels (with no values) under `Require Container Label`:
* io.rancher.container.system
* dlpc.main_host

**Comment by barczaG** [comment]
I had the same issue. I think for new users is somewhat easy to active `Require Container label`. Maybe there should be more hint there

**Comment by sirius1024** [comment]
@cloud-rocket 
My solution is delete those labels from the hosts. And it worked.
Are we same? I'm not sure you add it or delete.
