### ISSUE TITLE
Cannot rollback a specific service in a stack thru the CLI

### ISSUE THREAD

**Issue by galioy** [rancher/rancher#11456]
**Rancher versions:**
rancher/server: v1.6.8-rc8

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-98-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I have a stack and 3 different services inside. A rollback from the UI is possible only during an active upgrade, so if I want to rollback at a later point, I can't do it from the UI. I have to do it from the CLI. 
In the CLI I try this:
```
rancher up -s my_stack --rollback my_service
```
but it responds with `FATA[0000] No such service: my_service`. If I try with:
```
rancher up -s my_stack/my_service --rollback
```
or
```
rancher up -s my_service --rollback
```
then it creates a new stack called `my_stack-my_service` or `my_service`.

Even running a simple rollback on the whole stack (`rancher up -s my_stack --rollback`) doesn't do anything.
Upgrading a stack, on the other hand, works fine.

**Comment by vincent99** [comment]
It's not in the UI because what you're trying to do doesn't exist, regardless of how you try and call it.

The rollback action is only available after calling upgrade and before finishing it.
