### ISSUE TITLE
Cli -  Provide ability to add description when creating project and clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11461]
rancher version - v1.0.0-alpha5

When creating project/cluster only name can be provided. Ability to add description/add members when creating project and clusters.

**Comment by dramich** [comment]
Cluster description was added in https://github.com/rancher/cli/pull/144

**Comment by dramich** [comment]
Available in v1.0.0-alpha12

**Comment by sangeethah** [comment]
Tested with rancher-v1.0.0-alpha13

Have the ability to add description when creating project and clusters using --description option.
