### ISSUE TITLE
Cli - Provide a way to get the default project that is currently set as part of log in.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11465]
rancher version - v1.0.0-alpha5

Currently there is no way to look up the default project that is currently set as part of log in.
We need a way to look up the  default project.

**Comment by dramich** [comment]
Run `rancher login --context`, release [here](https://github.com/rancher/cli/releases/tag/v1.0.0-alpha8)

**Comment by sangeethah** [comment]
Tested with rancher-v1.0.0-alpha8
```rancher login --context ``` provides info about the default project.
