### ISSUE TITLE
Cli - Should have the ability to get kubeconfig for a cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11464]
rancher cli version - v1.0.0-alpha5

Currently we support kubectl (as a passthrough) as a command . It would also be good to have the ability to get kube config for a cluster which can then be used with ```./rancher kubectl ```commands.

**Comment by deniseschannon** [comment]
@dramich Now that this is available in the API (https://github.com/rancher/rancher/issues/12156), we should be able to retrieve it for CLI.

**Comment by dramich** [comment]
This is available in https://github.com/rancher/cli/releases/tag/v1.0.0-alpha9

**Comment by sangeethah** [comment]
Tested with rancher-v1.0.0-alpha9
```rancher clusters kf <cluster-id>``` provides kubeconfig for the cluster.
