### ISSUE TITLE
cli - cluster <add-node> command does not provide any role option to be selected.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11460]
rancher version - v1.0.0-alpha5

cluster <add-node> command does not provide any role option to be selected .
Without this , there is no role added to the docker run command provided. 
We should also default it to always have “worker” role when no role is specified.

**Comment by dramich** [comment]
Running `cluster add-node --help` will show the role flags available. If no role is specified it runs as a `worker` which is the same behaviour that the UI exhibits.

**Comment by deniseschannon** [comment]
Available with v1.0.0-alpha7

**Comment by sangeethah** [comment]
Tested with v1.0.0-alpha7
Have the ability to pick roles for adding hosts.
