### ISSUE TITLE
Trying to deploy a new AWS host with Use only private ip address selected always fails.

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#11476]
rancher/server: 1.6.10 / 1.6.14 / 1.16.15-rc4
Docker 1.13.1
Ubuntu 16.04.3
Cattle

**Steps to Reproduce:**
Try to deploy a new AWS host with "Use only private ip address selected"
**Results:**
Always fails.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
