### ISSUE TITLE
Cannot bump node count for K8s clusters

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#11475]
Latest rancher/server:master.

Create a cluster on DO with say 3 master/etcd nodes and 5 worker nodes.

Now try to bump up worker node count or etcd node count.

It does not work. Instead all nodes are deleted and the same number of nodes are recreated. And the resulting cluster is completely broken.

**Comment by soumyalj** [comment]
Also, tested by creating 4 other clusters where the etcd nodes and worker nodes were incremented[Through edit cluster].  Did not see any issues.

**Comment by deniseschannon** [comment]
Tested with master 3/1

k8s clusters created from node pools only allows incrementing nodes from the node pools within "edit cluster". 

When bumping up nodes, only new nodes are created. 

Any issues with a resulting cluster not being able to go back to active is RKE related.
