### ISSUE TITLE
Community Catalog App page for Cloudfare DNS crashes the browser

### ISSUE THREAD

**Issue by levensailor** [rancher/rancher#11480]
clientside: Uncaught Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction

**Rancher versions:**
rancher/server: 2.0
rancher/agent: 2.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by vincent99** [comment]
None of the catalog works in the current preview.
