### ISSUE TITLE
Validation failed in API: nodes

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#11484]
I am using Rancher 2.0 preview and when I try to set up a node using dashes in the node name, it fails with error: Validation failed in API: nodes.

**Comment by rulfauzi** [comment]
some case here come whit ,Validation failed in API: requestedHostname

**Comment by adm-cw5626** [comment]
Had the same issue today, now trying to build cluster and adding custom nodes (ubuntu 16.04LTS with docker running on Azure) and the cluster keeps on saying provisioning

**Comment by loganhz** [comment]
Close the issue for rancher 2.0 preview version. Now you can name node with  `-` in rancher 2.0
