### ISSUE TITLE
AWS NAT Gateway - healthchecks start to fail

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#11489]
**Rancher versions:**
rancher/server: 1.6.15-rc4
rancher/agent: 1.2.9-rc3

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.2.3
network-services: 0.2.9
scheduler: 0.8.3

**Docker version: 1.3.1**

**Operating system and kernel: Ubuntu 16.04.3**

**Type/provider of hosts: AWS**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
One instance in HA setup: 
Rancher server with port 4444 behind Classic Load Balancer with https cert installed + RDS. 
All policies for websocket proxy were applied to LB & working ok (without NAT Gateway).
```
aws elb create-load-balancer-policy --load-balancer-name mys-classic-lb --policy-name my-ProxyProtocol-policy --policy-type-name ProxyProtocolPolicyType --policy-attributes AttributeName=ProxyProtocol,AttributeValue=true
aws elb set-load-balancer-policies-for-backend-server --load-balancer-name my-classic-lb --instance-port 4444 --policy-names my-ProxyProtocol-policy
aws elb describe-load-balancers --load-balancer-name my-classic-lb
```

**Environment Template: Cattle**

**Steps to Reproduce:**
```
VPC: 172.31.0.0/16
availability zone: eu-central-1c
2 subnets:
172.31.0.0/20
172.128.0.0/20

```
1) Deploy 2 hosts in the same environment to the same subnet 172.31.0.0/20 with Rancher->AWS
2) Assign Elastic IP for each one instead of auto assigned one
3) Deploy NAT Gateway to the same VPC, same availability zone, but different (public) subnet: 172.31.128.0/20
4) Deploy 
Network Load Balancer 1
Network Load Balancer 2 
into the same availability zone & same (public) subnet as NAT Gateway: 172.31.128.0/20
5) Create a target group for each port needed for the services to be accessible on each instance: 
```
target group: "service1-22" tcp 22
target group: "service2-22" tcp 22
target group: "service1-80" tcp 80
target group: "service2-80" tcp 80
target group: "service1-443" tcp 443
target group: "service2-443" tcp 443
```
& configure corresponding Network Gateway to use them as listeners
6) Add instances to Registered targets
7) Add route 53 aliases for each load balancer:
service1.example.com -> Network Load Balancer 1
service2.example.com -> Network Load Balancer 2
8) Test that each service is externally available but is using it's own server external ip for outside access which was automatically assigned to at when it started (Elastic IP was assigned)
9) Rancher-agent was started with the following command:
`docker run -d -e CATTLE_AGENT_IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4) --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.10-rc3 https://my-classic-lb.example.com/v1/scripts/blahblahblah1:blahblahblah12:blahblahblah3`
10) In order for all instances/hosts to send all outgoing requests through NAT Gateway (which is my goal) replace Internet Gateway with NAT Gateway in the routing table of "private" subnet (where both instances/hosts & rancher server are deployed). 
This is done according to AWS docs: https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html

**Results:**
All outgoing traffic indeed starts to go though NAT Gateway & I'm able to use service1 & service2 from outside.

BUT!
All healthcheck containers turn yellow
All ipsec containers turn red
Some app containers turn red
Rancher Load balancer containers (haproxy) turn yellow

Restarting containers doesn't help.

What could be the problem?

Logs from healthcheck container from instance/host 1:
```
2/21/2018 12:48:51 AMtime="2018-02-20T21:48:51Z" level=error msg="Failed to report status a143f076-51fe-468e-9981-2a50ba01758d_39386386-266d-4603-aa10-0145123e2858_2=DOWN: Bad response from [https://my-classic-lb.example.com/v1/serviceevents], statusCode [409]. Status [409 Conflict]. Body: [{\"id\":\"f1b50bdd-e03b-464e-8df6-704d3ed96870\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}]"
2/21/2018 12:48:51 AMtime="2018-02-20T21:48:51Z" level=error msg="Failed to report status a143f076-51fe-468e-9981-2a50ba01758d_0ea2739d-05c4-4e2f-b115-72f49b1a74ab_1=DOWN: Bad response from [https://my-classic-lb.example.com/v1/serviceevents], statusCode [409]. Status [409 Conflict]. Body: [{\"id\":\"09727531-edb0-49d5-9e0c-9c1e914cecd1\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":409,\"code\":\"Conflict\",\"message\":\"Conflict\",\"detail\":null,\"baseType\":\"error\"}]"
```

Logs from ipsec-1 container container from instance/host 1:
```
Refer to router sidekick for logs
2/21/2018 1:04:53 AMmkfifo: cannot create fifo 'f': File exists
```

Logs from ipsec sidekick 1 (ipse-ipsec-router-1) from instance/host 1 (external ip=111.222.333.441):
```
2/21/2018 12:51:13 AMtime="2018-02-20T21:51:13Z" level=error msg="samonitor: error initiating missing SA child-111.222.333.442: Timeout waiting for message response"
2/21/2018 12:51:28 AMtime="2018-02-20T21:51:28Z" level=error msg="samonitor: error initiating missing SA child-111.222.333.443: Timeout waiting for message response"
```
   
Logs from ipsec sidekick 2 (ipsec-connectivity-check-1) from instance/host 1():
```
2/20/2018 4:32:35 AMtime="2018-02-20T01:32:35Z" level=error msg="Peer(3258b8a2-7d6b-434f-b05a-d6484c46102d, 10.42.70.24): became unreachable"
2/20/2018 4:32:41 AMtime="2018-02-20T01:32:41Z" level=error msg="Peer(e4a21025-67a2-4a09-9239-48b6c1f490a6, 10.42.35.86): became unreachable"
2/20/2018 4:32:41 AMtime="2018-02-20T01:32:41Z" level=error msg="Peer(ac27bc6f-b4b2-4402-828c-ee8c405bded3, 10.42.163.68): became unreachable"
2/20/2018 4:38:52 AMpanic: runtime error: invalid memory address or nil pointer dereference
2/20/2018 4:38:52 AM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x692abc]
2/20/2018 4:38:52 AM
2/20/2018 4:38:52 AMgoroutine 18 [running]:
2/20/2018 4:38:52 AMgithub.com/rancher/connectivity-check/checker.(*Peer).consider(0xc4201808a0, 0x851d58)
2/20/2018 4:38:52 AM  /go/src/github.com/rancher/connectivity-check/checker/peer.go:144 +0xdc
2/20/2018 4:38:52 AMgithub.com/rancher/connectivity-check/checker.(*Peer).Consider(0xc4201808a0, 0x0)
2/20/2018 4:38:52 AM  /go/src/github.com/rancher/connectivity-check/checker/peer.go:164 +0x6c
2/20/2018 4:38:52 AMgithub.com/rancher/connectivity-check/checker.(*PeersWatcher).doWork(0xc4200ec2d0)
2/20/2018 4:38:52 AM  /go/src/github.com/rancher/connectivity-check/checker/watcher.go:134 +0x769
2/20/2018 4:38:52 AMgithub.com/rancher/connectivity-check/checker.(*PeersWatcher).Run(0xc4200ec2d0)
2/20/2018 4:38:52 AM  /go/src/github.com/rancher/connectivity-check/checker/watcher.go:159 +0xcb
2/20/2018 4:38:52 AMcreated by github.com/rancher/connectivity-check/checker.(*PeersWatcher).Start
2/20/2018 4:38:52 AM  /go/src/github.com/rancher/connectivity-check/checker/watcher.go:168 +0x77
2/20/2018 10:24:27 AMtime="2018-02-20T07:24:27Z" level=error msg="Peer(a2969a2b-acb0-4ab0-ab80-a0f6901d3b22, 10.42.114.210): became unreachable"
2/20/2018 6:29:27 PMtime="2018-02-20T15:29:27Z" level=error msg="Peer(3258b8a2-7d6b-434f-b05a-d6484c46102d, 10.42.70.24): became unreachable"
2/20/2018 6:37:19 PMtime="2018-02-20T15:37:19Z" level=error msg="Peer(a2969a2b-acb0-4ab0-ab80-a0f6901d3b22, 10.42.114.210): became unreachable"
2/20/2018 6:37:19 PMtime="2018-02-20T15:37:19Z" level=error msg="Peer(ac27bc6f-b4b2-4402-828c-ee8c405bded3, 10.42.163.68): became unreachable"
2/20/2018 7:56:33 PMtime="2018-02-20T16:56:33Z" level=error msg="Peer(a2969a2b-acb0-4ab0-ab80-a0f6901d3b22, 10.42.114.210): became unreachable"
2/20/2018 8:26:11 PMtime="2018-02-20T17:26:11Z" level=error msg="Peer(3258b8a2-7d6b-434f-b05a-d6484c46102d, 10.42.70.24): became unreachable"
2/21/2018 12:48:11 AMtime="2018-02-20T21:48:11Z" level=error msg="Peer(a2969a2b-acb0-4ab0-ab80-a0f6901d3b22, 10.42.114.210): became unreachable"
2/21/2018 12:48:12 AMtime="2018-02-20T21:48:12Z" level=error msg="Peer(3258b8a2-7d6b-434f-b05a-d6484c46102d, 10.42.70.24): became unreachable"
2/21/2018 12:48:13 AMtime="2018-02-20T21:48:13Z" level=error msg="Peer(ac27bc6f-b4b2-4402-828c-ee8c405bded3, 10.42.163.68): became unreachable"
```

**Comment by vainkop** [comment]
I can see this behavior happening when hosts switch to local ips instead of public.
I've redeployed rancher-agents with:
`CATTLE_AGENT_IP=$(curl -s http://169.254.169.254/latest/meta-data/**local**-ipv4)`
& then swithed my apps, healchcheck & ipsec containers healthchecks to tcp healthchecks instead of http 1.1 200 & it;s all green now. Weird.

**Comment by abprohorov** [comment]
same here!
