### ISSUE TITLE
What does this mean:

### ISSUE THREAD

**Issue by jbsiii** [rancher/rancher#11485]
*Describe your issue here*

I keep getting this very unhelpful message when trying to add an application to a pod with only changing the pod name.  Once it starts happening, it seems the only way to get rid of it is to restart the cluster.

	
Validation failed in API: name

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha16` UI: `v2.0.20` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by loganhz** [comment]
Close this issue for rancher preview version. User is not allowed to edit pod name in rancher `v2.0.4`

**Comment by jbsiii** [comment]
Agreed.  No longer an issue.
