### ISSUE TITLE
[Pipeline] page in waiting mode v1.6.14

### ISSUE THREAD

**Issue by Coopyrightdmin** [rancher/rancher#11483]
*Describe your issue here*

Hi, 

I have included Pipeline on top of an existing stack where jenkins and gitlab are already running. Everything is up and running however, when navigating to the Pipeline UI tab, the screen is in waiting mode as described by issue #10738.

I use docker-compose/rancher-compose to start my stack:
- pipeline v0.1.1
- pipeline-ui v1.0.1
- jenkins-slave v1.0.0

Thanks for your support.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`container.ports`|

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
