### ISSUE TITLE
Upgrading with start before stopping stops container before new container is healthy

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#11487]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a stack with a service running `nginx` with a healthcheck HTTP on port 80 with path /
1. Upgrade service with `Start before Stopping` selected and break the healthcheck (change to port 81)

**Results:**
1. New container gets started, never goes healthy and old container will be stopped.

Happening since v1.6.11

Possibly related: https://github.com/rancher/cattle/commit/635592506c88e9742b519c8980dd8d0805540afd

**Comment by sangeethah** [comment]
Tested with latest build form 1.6 branch.

Existing containers dont go to "stopped" state anymore when upgrading with incorrect health check config parameters , but they get to "unhealthy" state which is not expected. This issue is tracked in - 
https://github.com/rancher/rancher/issues/12080
