### ISSUE TITLE
Azure AKS - Create unique resource group name for user

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11492]
**Rancher versions:** 2.0 master 2/20

**Issue:**
Resource Group is a required field.  The Azure requirements are that it must exist, name must be unique and it must not be in use by any other cluster. 

**Results:**
Let's create a unique resource group name for user and enter it automatically in the Resource Group field.

**Comment by nathan-jenan-rancher** [comment]
The 3 use cases for this are:

1.
- User starts creating an AKS cluster
- User specifies resource group that exists and has a AKS cluster in it
- Rancher display error message that user must use a different name

2.
- User starts creating an AKS cluster
- User specifies resource group that exists and does not have an AKS cluster in it
- Cluster creates successfully

3.
- User starts creating an AKS cluster
- User specifies resource group that does not exist
- Rancher creates resource group
- Cluster creates successfully

**Comment by soumyalj** [comment]
Tested  with master from March 2nd
1. Scenario1 - Cluster creation and workload creation was successful

**Comment by ebr** [comment]
tested on `v2.0.0-alpha21`: Scenario 3 seems to be working as expected

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
All three scenarios have passed.
