### ISSUE TITLE
Rancher stakcs not compatible with Docker-Compose v2

### ISSUE THREAD

**Issue by philippeboyd** [rancher/rancher#11497]
**Rancher versions:**
rancher/server: 1.6.14

Linked to #6188 but with recent version.

[Documentation](http://rancher.com/docs/rancher/latest/en/cattle/rancher-compose/) says 
> The Rancher Compose tool works just like the popular Docker Compose and supports the V1 and V2 versions of docker-compose.yml files.

Howver, while adding a new stack and pasting docker-compose, I get

>  Error (yaml: unmarshal errors: line 1: cannot unmarshal !!str `2.3` into config.RawService)

```
version: '2.3'

services:
  mongodb:
     ......
```

**Comment by vincent99** [comment]
We support only `version: '2'`, and limited compatibility of pieces of newer versions.  Not 2.1+/3.

**Comment by larssb** [comment]
Allow to jump in on this....as I would like to know what the plans are for supporting version 2.1+ 

Thank you very much.
