### ISSUE TITLE
[err-msg] Method not allowed

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#11505]
**Rancher versions:**
1.6.5+

**Symptom:**
This error is displayed in response to access controls.  For example, read-only user tries to restart a container. 

The UI shows the message: `Method not allowed.`

Its not really hinting at missing user permissions.

**Expected behavior:**
The message indicate what action has been prohibited and why.

**Comment by vincent99** [comment]
~[#1990](https://github.com/rancher/rancher/issues/1990)~ -> https://github.com/rancher/rancher/issues/11165 , this will be in 2.x but not going to happen in 1.x (though resource actions _are_ already dynamic, so restart shouldn't even be shown...)
