### ISSUE TITLE
[err-msg] Validation failed in API: imageUUID

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#11503]
**Rancher versions:**
1.6.5+

**Symptom:**
This error is displayed when docker image is invalid or unavailable. 

![image](https://user-images.githubusercontent.com/11086008/36452410-391cf534-1649-11e8-9cf0-9ad4ee72c7b0.png)

This is ambiguous and confusing.

**Expected behavior:**
The error message clearly indicates whether the docker image is a valid image string, or whether the image is not available for use (and why - e.g. DNS failure on docker pull, no such image in registry, registry access issue, image corruption, etc.)

**Comment by leodotcloud** [comment]
Proposed changes:
- https://github.com/rancher/agent/blob/v1.6/core/image/image.go#L103: Need to read the error message from stderr, instead of stdout.
- To be continued

**Comment by StrongMonkey** [comment]
@leodotcloud Agent fix is available.

**Comment by sangeethah** [comment]
Following is presented to the user when invalid image is entered:

<img width="1494" alt="screen shot 2018-04-10 at 5 52 04 pm" src="https://user-images.githubusercontent.com/4266958/38590739-ff2fea0a-3ce7-11e8-9fe1-d1133c19b9df.png">

**Comment by sangeethah** [comment]
If the format of the image provided is incorrect, then user is presented with following error message:
<img width="1527" alt="screen shot 2018-04-10 at 5 55 36 pm" src="https://user-images.githubusercontent.com/4266958/38590836-80f7754e-3ce8-11e8-9db8-1348c7df8fdc.png">
