### ISSUE TITLE
Ability to reset internal k8s certificate for existing environments from UI

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#11504]
Internal certificate to be used by service `kubernetes-kubernetes`, aka kube-apiserver, is created by this call (https://github.com/rancher/kubernetes-package/blob/v1.6/package/entry.sh#L24) in the entrypoint script. This certificate is generated by Cattle, along with the sans (Subject Alternative Name) specified for the service (as example: https://github.com/rancher/rancher-catalog/blob/v1.6-release/infra-templates/k8s/41/rancher-compose.yml#L231). Once the certificate is created and stored, it will not be regenerated (for instance, when a new san is added). It would be nice to make this possible through the UI.

Possible workaround for now is running a database query to remove the certificate manually. In case for this to work, all k8s stack/service containers need to be restarted.

```
# Store the current cert
select * from data where name = 'service.v3.7.kubernetes.cert';
# Delete the row
delete from data where name = 'service.v3.7.kubernetes.cert';
```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
