### ISSUE TITLE
[err-msg] Failed to allocate instance ... needs host with label

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#11507]
**Rancher versions:**
1.6.5+

**Symptom:**
This error is displayed when a container with a host affinity can not be started, but occurs even if the issue is not the host does not have a label, but other constraints can not be satisfied (but not limited to):
* Port conflicts
* Container name conflicts
* Unsatisfied sidekick dependencies
* etc.

For example, in the example (screenshot) below, even though the error was due to non available port on host, the end user sees it as "needs host with label"

<img width="584" alt="image 2" src="https://user-images.githubusercontent.com/11086008/36452999-6146c27c-164b-11e8-81bd-e347f29f46e4.png">

**Expected behavior:**
The message indicates a difference in a host not existing versus the specific constraint that can not be satisfied for the given host label affinity. E.g. "No hosts with label X exist" vs "Port 80 is already in use on all hosts with label X"

**Comment by leodotcloud** [comment]
@jambajaar Discussing with @StrongMonkey, this issue has been addressed already (v1.6.8).

**Comment by sangeethah** [comment]
With latest 1.6 build from master:

Following error messages are presented:
1.test6 - service deployed with  host label affinity that could  be satisfied but port mapping that cannot be satisfied. In this case user is presented with error message relating to  portReservation not being met with as expected.

2. test5 - service deployed with  host label affinity that could not be satisfied along with a port map.
In this case user is presented with the error message about both host label affinity not met with and existence of a portReservation . We could make further improvements to not list the existence of a portReservation constraint in this case.

<img width="1128" alt="screen shot 2018-04-12 at 5 18 06 pm" src="https://user-images.githubusercontent.com/4266958/38710553-df0786a4-3e75-11e8-80fc-936dcc7baa37.png">
