### ISSUE TITLE
etcd/controlplane nodes fail to register for custom cluster

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11508]
**Rancher versions:** 2.0 master 2/20

**Steps to Reproduce:**
1.  Create a custom cluster and add a couple of nodes

**Results:**  Cluster get stuck in provisioning - Waiting for etcd and controlplane nodes to be registered.
![image](https://user-images.githubusercontent.com/11514927/36453114-2bbc201c-1654-11e8-820e-1db3eb1de53b.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/21
Verified fixed

**Comment by patrik1972** [comment]
I try to set up a new cluster in v2.0.0-beta1 and get the same problem? 
	
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Waiting for etcd and controlplane nodes to be registered

**Comment by superseb** [comment]
@patrik1972 Please file a new issue with the logging of the `rancher/server` and `rancher/agent` container, and the steps you took to setup your cluster.
