### ISSUE TITLE
[err-msg] yaml: unmarshal ...

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#11515]
**Rancher versions:**
1.6.5+

**Symptom:**
These errors are seen under numerous circumstances. From using an unsupported docker compose version to malformed yaml

**Expected behavior:**
This message should indicate exactly what the problem may be E.g. "Docker compose version 3 is not supported. Only docker-compose v1 and v2 are supported. Please check the version identifier at the top of your docker-compose." or "yaml arrays not supported."

**Comment by dermeister0** [comment]
Example:

```
time="2018-03-07T03:21:43Z" level=error msg="Could not parse config for project my-project : yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `3` into config.RawService" 
time="2018-03-07T03:21:43Z" level=fatal msg="Failed to read project: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `3` into config.RawService" 
```

**Comment by sangeethah** [comment]
<img width="1070" alt="screen shot 2018-04-09 at 11 46 17 am" src="https://user-images.githubusercontent.com/4266958/38516292-a64c6bb8-3beb-11e8-89b3-cde35a4abcb7.png">
