### ISSUE TITLE
"Add Cluster Member"  page - user list is not populated in dropdown.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11517]
Rancher server - Build from master Feb 20

Steps to reproduce the problem:
As admin user,
Create few users.
Create a cluster. 
Go to "Add Cluster Member"  page .
User list is not populated in dropdown.

<img width="1359" alt="screen shot 2018-02-20 at 4 40 28 pm" src="https://user-images.githubusercontent.com/4266958/36457091-0d609b94-165d-11e8-9caf-a0000e8b2043.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified fixed
