### ISSUE TITLE
[err-msg] Expected state running but got [error | stopped | something-else ] ...

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#11512]
**Rancher versions:**
1.6.5+

**Symptom:**
This error can occur whenever a container fails to start. It can be due to a failed docker pull, but also when a container exits immediately either due to runtime failure or improper container image. 

For e.g. Expected state running but got error: 
`Error response from daemon: error unmarshalling content: unexpected end of JSON input`
This error is of little value and only creates confusion.

**Expected behavior:**
The message should indicate exactly what went wrong. E.g. "container failed to start because the image could not be pulled due to incorrect credentials" or "The container exited immediately upon start. Check the logs for more information."

**Comment by leodotcloud** [comment]
https://github.com/rancher/cattle/blob/v0.183.45/code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java#L201

Need to check if its possible to retrieve any failure message of the instances from the db and propagate in the message.

**Comment by sangeethah** [comment]
Tested with latest build for 1.6 from master:

When trying to deploy a service with invalid image name , user is presented with the following message:

```
Activating (Container should have been running but is in error state. Check logs for more information.: Error response from daemon: pull access denied for <image-name>, repository does not exist or may require 'docker login')
```

When trying to deploy a service with image name that requires credentials (and we do not have them configured ) , user is presented with the following message:


```
 Activating (Container should have been running but is in error state. Check logs for more information.: Error response from daemon: unauthorized: access to the requested resource is not authorized)
```

**Comment by sangeethah** [comment]
<img width="1143" alt="screen shot 2018-04-10 at 2 57 13 pm" src="https://user-images.githubusercontent.com/4266958/38585661-801824c0-3ccf-11e8-8895-5b183b0a0b50.png">
