### ISSUE TITLE
Deleting the node with all 3 roles in a custom cluster adds the node back as a worker node

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11521]
**Rancher versions:**
rancher/server:2.0 master

Steps to Reproduce:

1. Create a custom cluster with one node having all roles(control, etcd, worker) and another with worker node
2. Once the cluster has fully provisioned, go to the "Nodes list" page
3. Delete the node with all the roles

The node gets deleted and gets added back as a worker node

<img width="1269" alt="screen shot 2018-02-20 at 5 24 46 pm" src="https://user-images.githubusercontent.com/18536626/36458295-02c36332-1663-11e8-8d31-bbcddfcd0264.png">

Deletion of the node which is the only control plane in the cluster should not be allowed.

**Comment by Overv** [comment]
It appears that deleting any node from just the control panel results in almost instant recreation as worker node. The control panel delete action seems to not actually delete the node from the Kubernetes cluster, just the machine entry.

**Comment by deniseschannon** [comment]
Unable to reproduce with master 3/5. @soumyalj can you re-test too?

**Comment by deniseschannon** [comment]
Note: This cannot be the last node in the cluster

**Comment by soumyalj** [comment]
This issue is related to https://github.com/rancher/rancher/issues/10976
