### ISSUE TITLE
Rancher Kubernetes Ingress Load Balancer Module cannot route to External Name services

### ISSUE THREAD

**Issue by cyphrsonic** [rancher/rancher#11527]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.11.9
network-services: v0.9.4
scheduler: v0.8.2
kubernetes (if applicable): v1.8.5-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Custom based on Kubernetes Template
**Steps to Reproduce:**

1. Create a Valid Kubernetes Ingress following doucmentation using a service name with an external name service type: http://rancher.com/docs/rancher/latest/en/kubernetes/ingress/ (I used a host based route, but simple shows the same error)
2. Check Rancher infra stack for balancer rules, no rules will be created

**Results:**
Check Rancher infra stack for rules, no rules will be created for services with an external name service.

**Comment by cyphrsonic** [comment]
It appears I misattributed this - it appears to actually be external names that Rancher ignores. I was trying to use a single ingress namespace so that I could have one giant load balancer, rather than running a seperate one for each namespace, but it appears that the load balancer won't route that traffic.

**Comment by loganhz** [comment]
ingress and service should be in the same namespace.

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
