### ISSUE TITLE
Azure ACS - no matter how many nodes I request, I only ever get 1 node

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11528]
**Rancher versions:** 2.0 master 2/21

**Steps to Reproduce:**
1.  Create a azure container service cluster with a node count of 3
2.  Wait for it to activate

**Results:**  There is only 1 node.  If you edit, count is showing three, but in azure and in the main cluster page you can see only 1 node is added.

**Comment by soumyalj** [comment]
Tested with master from March 2nd . Created two node and three node Azure container service clusters. Clusters were created successfully with the appropriate number of nodes.
