### ISSUE TITLE
Deleting last node causes node to come back in invalid (bad) pool

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11520]
**Rancher versions:** 2.0 master 2/20

**Steps to Reproduce:**
1.  Create a cluster (any kind) with 1 node
2.  After the cluster has fully provisioned, go to the Nodes list page
3.  Delete the node

**Results:**  The node is removed and then comes back in an invalid pool (bad pool)

**Comment by deniseschannon** [comment]
I'm unable to reproduce in the latest master (3/1)

Created a DO cluster with 1 node.
Waited until the cluster was active.
Deleted the node. 

The original node doesn't get fully removed and a new node is spun up but it never actually gets setup because the etcd info has been lost.

**Comment by deniseschannon** [comment]
@tfiduccia I don't think nodes are going back to invalid pools. What I described is still happening, but it seems that eventually you are left with 1 node in removing state.

**Comment by tfiduccia** [comment]
Can't delete last node in cluster anymore
