### ISSUE TITLE
network fail

### ISSUE THREAD

**Issue by ItgLvb** [rancher/rancher#11525]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
vxlan:
network-services: v0.7.19
scheduler:v0.8.3
kubernetes (if applicable): v1.8.5-rancher4

**Docker version: docker-17.06.2-ce**

**Operating system and kernel: Centos 7.4 kernel-3.10.0-693.11.1.el7.x86_64**

**Type/provider of hosts: Bare-metal**

**Setup details: HA rancher, external DB**

**Environment Template: Kubernetes**

**Steps to Reproduce:
Create 2 kubernetes environments:
1. (prod) Many nodes, Services with External IPS. (all nodes in one network area - 10.0.0.0/24)
2. (develop) Single node (node in different area - 10.0.14.0/24, but can see nodes in prod env)
Shutdown node in second develop environment. This step will kill all endpoints in prod environment.
**

**Results:
All endpoints in prod environment does not work. Requests to External IPS fail with timeout error.
**

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
