### ISSUE TITLE
rancher server stops responding and gets to bad state when host that has the control plane gets deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11537]
Rancher server - Build from master  - feb 21

Steps to reproduce the problem:
1. Create a RKE cluster with Digital Ocean driver with node pool of size 1 having all roles.
2. Wait for cluster to get to active state.
3. Change the size of node pool to 3.
4. Wait for cluster to get to active state.
5. Delete the node that was created in step1.

After this  rancher server stops responding and we see a lot of logs similar to the following logs:

```
E0221 20:48:48.658142       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:126: Failed to list *v1.Job: Get https://<ip>:6443/apis/batch/v1/jobs?resourceVersion=0: failed to find session for client m-707e7325e538
E0221 20:48:49.618566       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:126: Failed to list *v1.Role: Get https://<ip>:6443/apis/rbac.authorization.k8s.io/v1/roles?resourceVersion=0: failed to find session for client m-707e7325e538
E0221 20:48:49.637530       1 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:126: Failed to list *v1.Node: Get https://<ip>:6443/api/v1/nodes?resourceVersion=0: failed to find session for client m-707e7325e538
````

Even attempting to stop/delete the rancher-server container fails at this point:

```
root@ip-172-31-9-120:/home/ubuntu# docker rm -f 2bf
Error response from daemon: Could not kill running container 2bfbfd369f45d3f8df81930bb0d97b9b0ecc9210f185d0786b99563256eaff00, cannot remove - Cannot kill container 2bfbfd369f45d3f8df81930bb0d97b9b0ecc9210f185d0786b99563256eaff00: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown
root@ip-172-31-9-120:/home/ubuntu# 
```

Once we reboot the docker daemon ,and  restart the stopped rancher server container , it continues to be bad state and above logs are seen .

**Comment by soumyalj** [comment]
Tested with master from March 5th.  Followed the steps below:

1. Create a RKE cluster with Digital Ocean driver with node pool of size 1 having all roles.
2. Wait for cluster to get to active state.
3. Change the size of node pool to 3.
4. Wait for cluster to get to active state.
5. Delete the node that was created in step1.

Cluster was created successfully. Workload deployment was ok.
