### ISSUE TITLE
Bug: All Catalog entries added to Node Drivers list.

### ISSUE THREAD

**Issue by ianmjones** [rancher/rancher#11538]
**Rancher versions:**
rancher/server:preview (v2.0.0 alpha16)
rancher/agent:v2.0.2

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 45
 Running: 20
 Paused: 0
 Stopped: 25
Images: 17
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.19-coreos
Operating System: Container Linux by CoreOS 1632.3.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.929GiB
Name: localhost
ID: RG33:PUQD:QHC3:SEFW:OUX5:CY5H:KQCT:FVCF:SUUI:MDPD:MOEF:FXS7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.14.19-coreos

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
local VMWare Fusion 8.5.10 (on macOS 10.12.6)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, used container method for adding same host running rancher server as worker/etcd/management node.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes as this Rancher 2.0 preview.

**Steps to Reproduce:**
1. Setup "dev" cluster without adding a node, use container method to add same server as node. Provisioned ok and looking good.
1. Enable Library and Community Catalogs from global "Catalogs" area.
1. For good measure add custom (currently only configured for Rancher 1.6.x) catalog. https://github.com/ianmjones/rancher-catalog.git
1. Check catalog entries available for adding to Default project on cluster in "Catalog Apps".
1. Check global "Node Drivers" area...

**Results:**
Did not expect *all* catalog entries to be added to Node Drivers...

<img width="1392" alt="rancher node drivers" src="https://user-images.githubusercontent.com/4710/36531686-a02413e8-17b6-11e8-9527-925920a775a8.png">

**Comment by superseb** [comment]
This should be resolved, let me know if you run into it again on the latest version.
