### ISSUE TITLE
Pods stuck in ContainerCreating state (Failed create pod sandbox)

### ISSUE THREAD

**Issue by tushar-ayla** [rancher/rancher#11536]
**Rancher versions:**
rancher/server:
rancher/agent: rancher/agent:v1.2.9

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: docker: rancher/net:holder / rancher/net:v0.13.7
network-services: rancher/network-manager:v0.7.19 / rancher/net:v0.13.7
scheduler: rancher/k8s:v1.8.5-rancher4
kubernetes (if applicable): rancher/k8s:v1.8.5-rancher4

**Docker version: 1.13.1**

**Operating system and kernel: (16.04.1 LTS (Xenial Xerus), 4.4.0-91-generic**

**Type/provider of hosts: Bare-metal**

**Setup details: 1 master (internal DB) + 1 node**

**Environment Template: Kubernetes**

--------------------------

I create kubernetes  cluster using rancher and wanted to verify the setup by creating nginx pods. But on executing the deployment and pods are created but stuck in ContianerCreating state. I'm able to create nginx container on the node by clicking '+Add Container' button on 'Hosts' page on Racher UI.

Any help on this is highly appreciated.

--------------------------

Below is the response from 'kubectl get pods' & 'kubectl describe pods' commands.

**[node:mylabs]$ kubectl get pods**

NAME                                READY     STATUS              RESTARTS   AGE
nginx-75f4785b7-m6kcl               0/1       ContainerCreating   0          2h
nginx-75f4785b7-pqfsm               0/1       ContainerCreating   0          2h
nginx-75f4785b7-stlw6               0/1       ContainerCreating   0          2h

**[node:mylabs]$ kubectl describe pods**

Name:           nginx-75f4785b7-m6kcl
Namespace:      default
Node:           localhost.localdomain/
Start Time:     Wed, 21 Feb 2018 14:45:16 -0800
Labels:         app=nginx
                pod-template-hash=319034163
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"nginx-75f4785b7","uid":"e3183347-1758-11e8-862e-0200da73d294","a...
Status:         Pending
IP:             
Controlled By:  ReplicaSet/nginx-75f4785b7
Containers:
  nginx:
    Container ID:   
    Image:          nginx
    Image ID:       
    Port:           80/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rzdcs (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-rzdcs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-rzdcs
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                 From                            Message
  ----     ------                  ----                ----                            -------
  Warning  FailedCreatePodSandBox  22m (x140 over 2h)  kubelet, localhost.localdomain  Failed create pod sandbox.
  Warning  FailedSync              1m (x161 over 2h)   kubelet, localhost.localdomain  Error syncing pod

**Comment by superseb** [comment]
The kubelet on the node should log whats going on with getting that image and container ready, can you check?

**Comment by grozeille** [comment]
I'm trying to run a single node Rancher 2.0 in docker-machine, I have the following error log on the kubelet:

Error adding network: open /run/flannel/subnet.env: no such file or directory

(and various errors with the same "no such file or directory")

But the file does exist on the host:

docker@default:~$ ls /run/flannel/subnet.env
/run/flannel/subnet.env

So I guess it's not mounted or the kubelet is not able to access it from its docker image ?

**Comment by superseb** [comment]
@grozeille This is an issue filed on 1.6, please submit a new issue with the info from the issue template so we can investigate if you experience problems.

**Comment by davidbIQ** [comment]
if you could add link to that would be helpful as this is that comes up in a google search
