### ISSUE TITLE
Question about management of old containers

### ISSUE THREAD

**Issue by Anonymous-Coward** [rancher/rancher#11539]
Rancher version 1.6.14

This more of a question than a problem/bug report - I could not find the answer by just studying the documentation.

After

rancher-compose up --pull --force-upgrade -c

Is a rollback possible?

If yes, how many old container versions does rancher keep, if you always use --force-upgrade?

My need/my idea: upgrade from CI/CD, without a need to confirm, but don't keep old containers around forever.

**Comment by vincent99** [comment]
Force upgrade means to launch new containers even if the definition of them hasn't changed.  It's not directly related to rollback.  For any upgrade the service stops old containers, starts new ones (the exact order of that depending on other options), and goes into `upgraded` state.  At that point the old containers are all still there but stopped, and you either finish the upgrade (which deletes the old containers) or rollback (which starts the old ones back up and deletes the new ones).  There is no explicit history of the last n-configs kept (in 1.x; in 2.0 I think we will have this).

**Comment by Anonymous-Coward** [comment]
So essentially the old containers will be removed eventually, by the janitor, even if nobody confirms a forced update, if there are any old container versions. Right?

**Comment by vincent99** [comment]
No, the old containers stay until you confirm the upgrade.  And (re)scheduling of the running containers in response to new hosts or failures is limited while in "upgraded".  Upgrades need to be "finished".

Again "force" only decides if new containers are launched even when no part of the definition yaml/json has changed.  There is  no difference (or knowledge) that the service has been "force" upgraded or not.

**Comment by Anonymous-Coward** [comment]
Thanks.
