### ISSUE TITLE
Editing nodes in GKE, Azure ACS and imported cluster fails with "Requested hostname is required" error

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11532]
**Rancher versions:**
rancher/server:2.0 master

**Steps to Reproduce:**
1. Create Azure ACS cluster, GKE or imported cluster 
2. Edit the nodes by adding a description or custom name
3. Edit and save fails with 
"Requested Host name is" is required

<img width="958" alt="screen shot 2018-02-21 at 2 09 01 pm" src="https://user-images.githubusercontent.com/18536626/36508176-cd5c88c8-1710-11e8-81e0-a726519a29c5.png">

**Comment by soumyalj** [comment]
I can still see the issue in Master from March 22nd build

**Comment by StrongMonkey** [comment]
Name and description are updatable in API. Appears to be a UI bug? @vincent99

**Comment by loganhz** [comment]
@StrongMonkey  The `requestedHostname` is required in `/v3/schemas/node`

Can you remove the required field in the schema ? UI will validate the data according to the schema

**Comment by zionwu** [comment]
There are 2 approaches to fix this issue:
1.  remove the required tag for requestedHostname field.
2. set the requestedHostname for GKE in nodesyncer.

@StrongMonkey  which approach do you prefer?

**Comment by zionwu** [comment]
I have tested the 2 approaches and both work. I think the second one is a better one as it is better to keep required tag for  requestedHostname.

**Comment by soumyalj** [comment]
Tested with master from March 28th build using the below steps:
1. Create  GKE, imported cluster or Azure cluster
2. Edit the nodes by adding a description or custom name

The custom names/description were edited and saved correctly 

<img width="1044" alt="screen shot 2018-03-28 at 9 59 39 pm" src="https://user-images.githubusercontent.com/18536626/38070980-7fd50272-32d3-11e8-8873-6c5eb54bf2f4.png">
