### ISSUE TITLE
Cluster provisioning using DO fails with " Failed to bring up Control Plane: Failed to verify healthcheck: " error

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11546]
Rancher versions: Build from master - Feb 22

Steps to reproduce the problem:
Create a cluster using Digital Ocean provider.
Cluster fails with the following error:

```[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-api] on host [<ip>]: Get https://localhost:6443/healthz: Failed to dial ssh using address [<ip>:]: dial tcp <ip>:0: getsockopt: connection refused```

**Comment by deniseschannon** [comment]
DO clusters seems to be working in master now. @soumyalj Can you please verify?

**Comment by soumyalj** [comment]
Tested with Feb 27 master build. Creation of digital ocean clusters is successful.
