### ISSUE TITLE
Container can not ping other containers on different hosts on CentOS 7

### ISSUE THREAD

**Issue by hjianhao** [rancher/rancher#1154]
I will give you the detail info of my environment for the issue.

I got four VM allocated from OpenStack, their IPs are 10.0.2.62, 10.0.2.63, 10.0.2.64, 10.0.2.65 they can communicate with each other.
The host 10.0.2.62 has another IP 192.168.3.76, which I can connect from outside. When I had login-ed to 10.0.2.62, I can login to other hosts using ssh.

I ran the Rancher server on 10.0.2.62(192.168.3.76), so I can using the Rancher UI with browsers. I ran the agents on 10.0.2.63 ,10.0.2.64 and 10.0.2.65

I ran mysql container on 10.0.2.63, no port map, set MYSQL_ROOT_PASSOWRD=pass
I ran wordpress container on 10.0.2.65, map 8090(public) to 80(private), set WORDPRESS_DB_HOST=10.42.17.174:3306 and WORDPRESS_DB_PASSWORD=pass, add Link to 10.0.2.63:mysql

The snapshot as following.

I can ping the host which run the mysql container from wordpress container.
```
[root@host-10-0-2-65 ~]# docker exec -ti 4eb07eec7c6d ping 10.0.2.63

PING 10.0.2.63 (10.0.2.63): 56 data bytes

64 bytes from 10.0.2.63: icmp_seq=0 ttl=63 time=1.213 ms

64 bytes from 10.0.2.63: icmp_seq=1 ttl=63 time=0.595 ms

64 bytes from 10.0.2.63: icmp_seq=2 ttl=63 time=0.452 ms
```

But I can not ping the mysql container from the wordpress container.
```
[root@host-10-0-2-65 ~]# docker exec -ti 4eb07eec7c6d ping 10.42.17.174

PING 10.42.17.174 (10.42.17.174): 56 data bytes

^C--- 10.42.17.174 ping statistics ---

12 packets transmitted, 0 packets received, 100% packet loss
```

other detail info :
every host run with the same CentOS version
```
[root@host-10-0-2-64 docker]# rpm -q centos-release
centos-release-7-1.1503.el7.centos.2.7.x86_64
```

kernel version:
```
[root@host-10-0-2-64 docker]# uname -a

Linux host-10-0-2-64 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Docker version
```
[root@host-10-0-2-64 docker]# docker version

Client version: 1.6.1

Client API version: 1.18

Go version (client): go1.4.2

Git commit (client): 97cd073

OS/Arch (client): linux/amd64

Server version: 1.6.2

Server API version: 1.18

Go version (server): go1.4.2

Git commit (server): 7c8fca2

OS/Arch (server): linux/amd64
```

Rancer Server version is v0.22.0-rc1
```
[root@host-10-0-2-62 etc]# docker ps

CONTAINER ID        IMAGE                        COMMAND                CREATED             STATUS              PORTS                              NAMES

5d6d4f57719a        rancher/server:v0.22.0-rc1   "/usr/bin/s6-svscan    3 hours ago         Up 3 hours          3306/tcp, 0.0.0.0:8080->8080/tcp   compassionate_brattain
```

Rancher agent version is v0.7.8
```
[root@host-10-0-2-64 docker]# docker ps

CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                          NAMES

f49d8ca52d33        rancher/agent-instance:v0.3.1   "/etc/init.d/agent-i   13 minutes ago      Up 13 minutes       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   866c71b9-0ce7-4e8d-b199-ffa68ddbf4d2

2fd8b22e6b53        rancher/agent:v0.7.8            "/run.sh run"          About an hour ago   Up About an hour                                                   rancher-agent
```

**Comment by deniseschannon** [comment]
I tried looking at the info that you've sent. Can you also provide what the `docker ps` for 10.0.063 and 10.0.2.65?

Regarding this issue with the other issues that you recently filed. Is this setup trying to also use the proxy at the same time?

**Comment by deniseschannon** [comment]
I've just formatted your issue to make it easier to read with fenced code blocks.

Also, I know it's not very easy for you, but we've been continually making changes. Latest is now v0.23.0-rc6. I still have never been able to reproduce your situation.

**Comment by hjianhao** [comment]
It seems strange. I try to reproduce the issue on my home using vagrant to create three VM, on for rancher server, the others are hosts, it works fine. But in production environment, I allocate 3 VM from Open Stack, containers still can not ping each other on different hosts.

**Comment by deniseschannon** [comment]
Based on the other issues that you've filed, do you think it's related to your reverse proxy issues?

**Comment by hjianhao** [comment]
Nothing about proxy. Without proxy , the issue still exists. Proxy is for access ui through Internet. :)

**Comment by cloudnautique** [comment]
@hjianhao do you have the following ports opened up on the VMs:

UDP: 500, 4500
TCP: 9345,  9346

Also, do the IPTABLEs rules allow communications? Is your route table setup properly?

**Comment by cloudnautique** [comment]
If you are running the newer Beta release v0.24.0 you only need the UDP ports open.

**Comment by deniseschannon** [comment]
@hjianhao Could you try creating services instead of individual containers? I wonder if that will help? The docs outline how to create the service.

Also, we highly recommend upgrading to at least Beta as we've made a lot of bug fixes in the last couple of weeks.

http://rancher.docs.rancher.com/docs/quick-start-guide/#create-a-multi-container-application
