### ISSUE TITLE
Unable to Create Cluster on Private AWS Subnet using Rancher 2.0 on AWS Ubuntu 16.04 ami-66506c1c 

### ISSUE THREAD

**Issue by SRomero321** [rancher/rancher#11545]
**Rancher versions:**
rancher/server: 2.0 Preview
rancher/agent:  2.0 Preview

**Docker version: (`docker version`,`docker info` preferred)**
https://releases.rancher.com/install-docker/17.03.sh 

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 ami-66506c1c 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
1. I have 3 Public Subnets and 3 Private Subnets.
2. Rancher is setup on a private Subnet, I use port forwarding via a Bastion in the Public Subnet to access the UI. That seems to work with no issue.
3. The AMI I am using is ami-66506c1c
4. The Security Groups I have opened on Rancher Server are 80, 443 and 22.
5. NACLS I have opened are 80, 443, and 22.
6. I have an IGW and NGW on the VPC.
7. Internet is accessible from all nodes.

**Steps to Reproduce:**

Deploy Rancher on a private subnet, use private ips only and use AWS Ubuntu 16.04 ami-66506c1c, I get the errors below.

**Results:**

![af22ea7f523ec469293811d2d010a89d59913909](https://user-images.githubusercontent.com/25870240/36554590-b1a48456-17cd-11e8-9b0a-965c55ccbadd.png)

2018-02-22 08:26:12.721194 I | mvcc: store.index: compact 832
2018-02-22 08:26:12.721803 I | mvcc: finished scheduled compaction at 832 (took 118.609µs)
time=“2018-02-22T08:26:26Z” level=info msg="Running cluster events cleanup"
time=“2018-02-22T08:26:26Z” level=info msg="Done running cluster events cleanup"
time=“2018-02-22T08:26:26Z” level=info msg="MachineController cluster-v9jnp/machine-5zgn2 completed with dropped err: [machine-controller] failed with : Error"
time=“2018-02-22T08:26:26Z” level=info msg="MachineController cluster-v9jnp/machine-hgk9w completed with dropped err: [machine-controller] failed with : Error"
time=“2018-02-22T08:26:26Z” level=info msg="MachineController cluster-v9jnp/machine-jdccd completed with dropped err: [machine-controller] failed with : Error"
time=“2018-02-22T08:26:26Z” level=info msg="ClusterController cluster-v9jnp completed with dropped err: [cluster-provisioner-controller] failed with : waiting for nodes to provision or a valid configuration"
time=“2018-02-22T08:26:26Z” level=info msg="ClusterController cluster-v9jnp completed with dropped err: [cluster-provisioner-controller] failed with : waiting for nodes to provision or a valid configuration"
2018-02-22 08:31:12.725629 I | mvcc: store.index: compact 833
2018-02-22 08:31:12.726253 I | mvcc: finished scheduled compaction at 833 (took 108.977µs)
2018-02-22 08:36:12.753386 I | mvcc: store.index: compact 834
2018-02-22 08:36:12.753970 I | mvcc: finished scheduled compaction at 834 (took 105.592µs)
2018-02-22 08:41:12.765836 I | mvcc: store.index: compact 835
2018-02-22 08:41:12.766425 I | mvcc: finished scheduled compaction at 835 (took 115.346µs)
2018-02-22 08:46:12.770123 I | mvcc: store.index: compact 836
2018-02-22 08:46:12.770702 I | mvcc: finished scheduled compaction at 836 (took 110.207µs)
2018-02-22 08:51:12.774521 I | mvcc: store.index: compact 837
2018-02-22 08:51:12.775119 I | mvcc: finished scheduled compaction at 837 (took 112.876µs)
2018-02-22 08:56:12.779572 I | mvcc: store.index: compact 838
2018-02-22 08:56:12.780157 I | mvcc: finished scheduled compaction at 838 (took 108.668µs)
2018-02-22 09:01:12.783852 I | mvcc: store.index: compact 839
2018-02-22 09:01:12.784221 I | mvcc: finished scheduled compaction at 839 (took 107.527µs)
2018-02-22 09:06:12.787619 I | mvcc: store.index: compact 840
2018-02-22 09:06:12.788205 I | mvcc: finished scheduled compaction at 840 (took 108.169µs)
2018-02-22 09:11:12.791817 I | mvcc: store.index: compact 841

Another error set:

2018-02-21 03:51:12.614092 I | mvcc: store.index: compact 2378
2018-02-21 03:51:12.614540 I | mvcc: finished scheduled compaction at 2378 (took 143.025µs)
time=“2018-02-21T03:56:06Z” level=info msg="stdout: Installing Docker…"
2018-02-21 03:56:12.617191 I | mvcc: store.index: compact 2379
2018-02-21 03:56:12.617645 I | mvcc: finished scheduled compaction at 2379 (took 156.842µs)
time=“2018-02-21T03:59:41Z” level=info msg="stdout: Error getting SSH command to check if the daemon is up: ssh command error:"
time=“2018-02-21T03:59:41Z” level=info msg="stdout: command : sudo docker version"
time=“2018-02-21T03:59:41Z” level=info msg="stdout: err : exit status 1"
time=“2018-02-21T03:59:41Z” level=info msg="stdout: output : sudo: docker: command not found"
time=“2018-02-21T03:59:41Z” level=info msg="stdout: "
time=“2018-02-21T03:59:44Z” level=info msg="stdout: Error getting SSH command to check if the daemon is up: ssh command error:"
time=“2018-02-21T03:59:44Z” level=info msg="stdout: command : sudo docker version"
time=“2018-02-21T03:59:44Z” level=info msg="stdout: err : exit status 1"
time=“2018-02-21T03:59:44Z” level=info msg="stdout: output : sudo: docker: command not found"
time=“2018-02-21T03:59:44Z” level=info msg="stdout: "
time=“2018-02-21T03:59:48Z” level=info msg="stdout: Error getting SSH command to check if the daemon is up: ssh command error:"
time=“2018-02-21T03:59:48Z” level=info msg="stdout: command : sudo docker version"
time=“2018-02-21T03:59:48Z” level=info msg="stdout: err : exit status 1"
time=“2018-02-21T03:59:48Z” level=info msg="stdout: output : sudo: docker: command not found"
time=“2018-02-21T03:59:48Z” level=info msg="stdout: "

**Comment by loganhz** [comment]
Can you try it on v2.0.4, please? Please find the port requirements via https://rancher.com/docs/rancher/v2.x/en/installation/references/

**Comment by hdiongithub** [comment]
I had the same problem on v2.0.6 for EC2 with Ubuntu. It is not possible to setup a clusternode with private IP only (checked flag in node template) in any kind of AWS subnetwork. With the unchecked flag a public IP is created and it works.

For nodes with private IP the last logs I received are: 
Installing Docker…"
Error getting SSH command to check if the daemon is up: ssh command error:
2018/07/19 07:35:28 [INFO] stdout: command : sudo docker version
2018/07/19 07:35:28 [INFO] stdout: err     : exit status 1
2018/07/19 07:35:28 [INFO] stdout: output  : sudo: docker: command not found

On the ranger server I found an interesting detail in  
/var/lib/rancher/management-state/node/nodes/hdic1/machines/hdic/config.json
"Driver": {
...
"PrivateIPOnly": true,
"UsePrivateIP": false,
...
}
Here it seems to me that docker-machine's --amazonec2-use-private-address was not set.
Do I have a way to override the docker-machine flag e.g. via ranger cli? Until now I have not found it. 

Since the public IP is created with EC2 instance and it is used to access port 6443 I have no chance to adapt the security group automatically to theses new IPs and to leave port 6443 open for all is no solution.

I use ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180627 (ami-de8fb135).

**Comment by superseb** [comment]
Seeing the error, the machine can't get to `https://releases.rancher.com/install-docker/17.03.sh` to install Docker and further steps will fail.

Please file a new issue with the recent version used so we can investigate of this needs further help.
