### ISSUE TITLE
How to integrate our own private cloud with rancher?

### ISSUE THREAD

**Issue by hjianhao** [rancher/rancher#1155]
On add host UI, rancher let user select some public cloud and custom linux host. 

We need add our private cloud support at this functions' UI for add host quickly. 

Is there any method to add the provision UI and process for our own private cloud without modifying the rancher server's code directly?

**Comment by deniseschannon** [comment]
Please follow this google group thread: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rancherio/yiQtenvvrbE/v4f8tfF6VTAJ
