### ISSUE TITLE
How to customize the network solution for rancher?

### ISSUE THREAD

**Issue by hjianhao** [rancher/rancher#1156]
We had our own solution for containers, so we need customize the rancher's create container process.  We need insert the create bridge and IP allocation steps and assign the IP to container.

How we can achieve this, should we modify the rancher server's code, or we can insert the steps by modifying some configuration?

**Comment by deniseschannon** [comment]
Please follow the google group's thread for more information. https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rancherio/gdw9f7iJsWQ/Ehs4vFDCQcwJ

**Comment by hjianhao** [comment]
Our use case is that : 

1. Our production require the VM and container on the same net. 
2. We have a service to assign the IP for container dynamically or  statically. and add the container's hostname and the container's ip on local DNS server.
3. We need add a bridge on each host running the container and when an container started, we will create veth pair, one attached the bridge, the other attached the container in it's namespace.
4. So our requirement's is that 
    a. add a new choice on network choice.
    b. customize the container create steps : 
         i. create container.
         ii. call the IP assignment service to allocate IP
         iii. call connect the bridge to container.
         iv. do the rest container starting step.

Do you have the plan to support such customization? :)

**Comment by feliksik** [comment]
All network related issues are of interest to me; I don't have in-depth knowledge of the docker networking plugin system yet, but I'd like to follow the progress of @hjianhao  and Rancher.
