### ISSUE TITLE
Notifier fields in error messages should match field names in UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11567]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Go to Add Notifier
2.  Click on OK without entering any info in fields

**Results:**  Names in error messages for Slack don't match field names.
Slack:
![image](https://user-images.githubusercontent.com/11514927/36577527-11579d60-1815-11e8-97c8-59e09d8077a0.png)

**Comment by vimniky** [comment]
Fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified fixed
