### ISSUE TITLE
In Add Notifier, Name field is required but missing * by field name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11568]
**Rancher versions:** 2.0 master 2/22

**Issues:**

- [ ] Name field is required but not marked as required - the * is missing.
![image](https://user-images.githubusercontent.com/11514927/36577661-d1a909d2-1815-11e8-856d-352e1d8773c1.png)

**Comment by vimniky** [comment]
Fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
