### ISSUE TITLE
Clicking on Test in Notifiers with no info gives back ok response

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11566]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Go to Add Notifier
2.  Click on Test

**Results:**  Returns OK! even thou, no info is filled out.  If required fields are not filled out should not give OK.

**Comment by vimniky** [comment]
@zionwu Will goona fix this issue

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/26
Verified fixed
