### ISSUE TITLE
Alerts are not specific for the cluster or project they were created in

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11576]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Create a alert in a cluster
2.  Switch cluster and go to alert list page
3.  Create a alert in a project
4.  Switch projects

**Results:**  Can see alerts in wrong cluster/projects

**Comment by vimniky** [comment]
This will be fixed as new PR is merged.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/26
Verified fixed
