### ISSUE TITLE
Nodes not showing up in node drop-down for alerts

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11577]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Create a GKE or ACS (azure) cluster
2.  Go to Add Alert
3.  Select Node
4.  Click on the drop-down

**Results:**  No nodes showing up in list

**Comment by vimniky** [comment]
Fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified fixed
