### ISSUE TITLE
Pre-created alerts for Clusters & Project are in twice

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11575]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Go to Alerts list page for clusters or projects

**Results:**  The pre-created alerts are showing up twice.

**Comment by vimniky** [comment]
I can't reproduce this issue. can you take a screenshot ?

**Comment by tfiduccia** [comment]
Cluster - 
![image](https://user-images.githubusercontent.com/11514927/36624683-792208b2-18cf-11e8-8121-632ee1af6d4c.png)

Project -
![image](https://user-images.githubusercontent.com/11514927/36624684-8a0b9b66-18cf-11e8-935e-7000d66643e5.png)

This is a fresh build from rancher/server:master

**Comment by vimniky** [comment]
Sorry, there's some filtering bug and this will be fixed by next PR.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/26
Verified fixed
