### ISSUE TITLE
Remove Channel from Add Alert

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11579]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Go to Add Alert
2.  In the "Alert to" section, select a slack notifier

**Results:**  A channel field becomes available.  Remove this field, since it is already in the notifier and it's in the webhook itself, asking again is confusing.

**Comment by vimniky** [comment]
Hi @tfiduccia. This field is there so that users can override it. We have discussed this will Will.

**Comment by zionwu** [comment]
@tfiduccia the filed is the recipient. For slack, the webhook can send messages to any channel in the org, so user may want to change the channel. For email, user can change the recipient email address, while still using the same stmp configuration.

**Comment by tfiduccia** [comment]
@zionwu - talked to vincent last night about it and yeah he explained.  Just confusing that it's so many places but I guess it makes sense.
