### ISSUE TITLE
In slack notifier default channel should not be required

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11570]
**Rancher versions:** 2.0 master 2/22

**Results:**  Since the webhook is already pointing to a channel, the default channel should not be required.

**Comment by zionwu** [comment]
@tfiduccia There are several reasons we have the default channel:
1. over time user might forget which channel the webhook pointing to, so we can keep this info for the user.
2. Actually, the webhook can send messages to any channel in the org, here we provide a chance for the admin to point to another channel.
3. In the add alert page,  users can see the default recipient of the notifier. to make it consistent with other notifiers, we should have a default recipient for the slack notifier.

**Comment by tfiduccia** [comment]
ok.
