### ISSUE TITLE
Clear errors and reset when changing type of notifiers

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11572]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Go to Add notifier
2.  Click on Add without filling out any info
3.  Change from slack to email notifier

**Results:**  Errors from Slack are still showing.  Clear the errors when switching types of notifiers.

**Comment by vimniky** [comment]
fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified fixed
