### ISSUE TITLE
pipeline page goes to 404 page while cluster is setting up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11589]
**Rancher versions:** 2.0 master 2/23

**Steps to Reproduce:**
1.  Create a cluster
2.  While the cluster is provisioning go to the Pipeline page

**Results:**  404 page comes up.  Once the cluster is active and fully provisioned the page works fine.
![image](https://user-images.githubusercontent.com/11514927/36609651-d4fbab92-188a-11e8-939b-c4bd83ad7cf7.png)

**Comment by biblesyme** [comment]
Should I hide the Pipeline tab when the cluster is provisioning? @vincent99

**Comment by vincent99** [comment]
Yes, or show a page that says it's unavailable

**Comment by biblesyme** [comment]
@vincent99 Is there a component I can use to show this warning?

**Comment by vincent99** [comment]
Just transitioning away is probably fine for now... like https://github.com/rancher/ui/blob/master/app/authenticated/cluster/ns/index/route.js#L8-L12

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
