### ISSUE TITLE
[webhook-service] Webhook upgrade deletes "Drain Timeout"

### ISSUE THREAD

**Issue by ItsReddi** [rancher/rancher#11588]
Reproduce:
1. Configure a service with drain timeout
2. setup a webhook, upgrading that service
3. trigger the webhook

Expected: Service upgraded, and drain timeout still set and used

Behavior: Drain timeout is set to 0 and draintimeout is not even used 1 time

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/10524
