### ISSUE TITLE
Secondary sort for Notifiers and Alerts field should always be Name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11581]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Go to Notifiers or Alerts page
2.  Add a bunch of notifiers and alerts
3.  Sort by anything other and Name

**Results:**  The secondary sort order should be Name.  So if you sort by Type in Notifiers, there should be a secondary sort by Name so it appears alphabetically.  Same with Alerts.  If I sort by state, the secondary sort should be Name field.  This would make it consistent with how the rest of the rancher list pages work.

**Comment by vimniky** [comment]
I switched the notifier fields' order And not name will be de primary sort key.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
