### ISSUE TITLE
Alert's Fixed table header is not set properly and list is overwriting into it

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11580]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Go to alerts page
2.  Create a bunch of alerts until you get a scrollbar
3.  Scroll to bottom of list

**Results:**  The list is bleeding into the table header
![image](https://user-images.githubusercontent.com/11514927/36579263-624b4438-181f-11e8-98c5-3a680d86a962.png)

**Comment by vimniky** [comment]
fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Verified fixed
