### ISSUE TITLE
Port 9345 still in docs but not clearly documented

### ISSUE THREAD

**Issue by HariSekhon** [rancher/rancher#11585]
Rancher 1.6 still has ports referencing 9345 in the following 2 docs although they are not clearly documented:

http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/

http://rancher.com/installing-rancher-single-container-high-availability/

Ticket #1246 says these were supposed to be removed.

Either docs should state explicitly what these ports are required for or remove them as per #1246?

**Comment by superseb** [comment]
There have been major design changes since the issue you pointed out (which applies to pre 1.0). The current docs are what you want to use, and they point out that 9345 is needed between the hosts running `rancher/server` container.

Let me know if you have any other questions

**Comment by HariSekhon** [comment]
@superseb 

Thanks for the reply.

Could someone update the doc with a description of why that port is needed?
