### ISSUE TITLE
[rancher-dns] Request to add "only-local/prefer-local" zones to DNS server

### ISSUE THREAD

**Issue by beatcracker** [rancher/rancher#11593]
This should work the same way the load balancer label does: depending on the client that is asking, return the address of the container on the same host (if available).

Example:  I have stacks `frontend` and `backend`, both scaled to multiple hosts. `frontend` talks to `backend` but I'd like to avoid cross-host networking. Currently this is impossible, since if I tell `frontend` stack to talk to `service.backend` container, it will use round-robin and randomly use containers from all hosts.

So I'd like to have an option to specify DNS name as `service.backend.only-local` and always get the address of the container on the same host.

Related discussions:

* [Is it possible to link to containers on same host](https://forums.rancher.com/t/is-it-possible-to-link-to-containers-on-same-host/1221)
* [Ping container running on specific host](https://forums.rancher.com/t/ping-container-running-on-specific-host/6172)

**Comment by beatcracker** [comment]
Workaround: [fabiomontefuscolo/rancher-dns-gen](https://github.com/fabiomontefuscolo/rancher-dns-gen)

> There is a small diference from native DNS service. **Instead do a round-robin when there are multiples containers for a single name, this service deliver an IP for a container in the same host.**

**Comment by kamushadenes** [comment]
@beatcracker How you managed to make rancher actually use it? When I add the resolving server, it is commented out. Docs state that the rancher-dns is used anyway and non-local queries are forwarded to the specified resolving server. That sucks.

How can I take rancher-dns out of the way so I can use rancher-dns-gen?

**Comment by beatcracker** [comment]
@kamushadenes 

> How you managed to make rancher actually use it?

I made it work, but I don't remember exactly how (I'll try to dig it up later). The thing is, that this did't solve the problem. `rancher-dns-gen` allows you to access container like this: `some-service.RancherHostName`. But it means that you need to know what host your container runs on. I've tried to script this using metadata and it kinda-worked, but was too hacky.

So I've ended up using sidekicks. 

I had a look at [rancher-dns](https://github.com/rancher/rancher-dns) code and while I couldn't patch it myself, it didn't look like it would be hard to add this functionality. I guess that the Rancher team is too busy with  2.0 to add new stuff to 1.6.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
