### ISSUE TITLE
Invalid Date / Grabbing Logs EOF / Logs disconnected

### ISSUE THREAD

**Issue by DACRepair** [rancher/rancher#11592]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec: v0.13.7
network-services: NM v0.7.19 Meta v0.9.5
scheduler: v0.8.3
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
Docker Version:
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

Docker Info:
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.796GiB
Name: HLV-Cattle0
ID: xxxxxxxxxxxxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Kernel 4.4.0-116-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Self Hosted, VMWare VM's

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Multi node, external DB (apt-get install mysql-server on rancher0 + config ), no HA

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle (default from fresh install template)

**Steps to Reproduce:**
Installed from fresh, 3 hosts (VM's):
- Rancher0
- Cattle0
- Cattle1

All of them fresh OS installs, then docker is installed (via the "Rancher Compatable Versions" script)
Add new stack
Add new service, named it test, image ubuntu:latest (though I ran into the issue with Debian:latest as well, I originally ran into it when installing traefik)
Once container is running, open logs on the service container.
**Results:**
Logs are immediately disconnected. there is one line in the box:
`Invalid Date Invalid Dategrabbing logs: EOF`

**Comment by DACRepair** [comment]
On a side note, I have checked the time syncro as previous posts have mentioned. the enviro they are running in I have AD NTP running and all hosts are connected and synced.

**Comment by DACRepair** [comment]
quick update: I have been fooling around, I restarted the rancher agent and looked for errors and saw none. I did however reload a container on that box from the UI, and the logs worked one time. After that it stopped working again. When that happened, the agent sent this to the agent log:
`time="2018-02-23T21:37:27Z" level=error msg="Error with the container log scanner." error="context canceled"
`
and then it truncated the log.

**Comment by superseb** [comment]
This is an error that Docker throws when tailing a log file that is empty, references: https://github.com/moby/moby/issues/35370 and https://github.com/moby/moby/pull/36305. As it's recently merged, it will be available in a next Docker version
