### ISSUE TITLE
All secrets(available for all namespaces) are not displayed in a namespace "X" once a secret is created in the namespace "X" 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11601]
**Rancher versions:**
rancher/server:2.0 build from master

**Steps to Reproduce:**
1. Create secret "secret1" which is available for all namespaces within the Default project
2. Create a namespace "testnamespace" 
kubectl get secret will display 
```
kubectl get secrets --namespace testnamespace
NAME                  TYPE                                  DATA      AGE
default-token-n6f7d   kubernetes.io/service-account-token   3         8m
secret1               Opaque                                1         8m
```
3. Create a secret "secret2" in the namespace "testnamespace"
```
$ kubectl get secrets --namespace testnamespace
NAME                  TYPE                                  DATA      AGE
default-token-n6f7d   kubernetes.io/service-account-token   3         8m
secret1               Opaque                                1         8m
secret2               Opaque                                1         4m
```
4. Create another secret3 which is available to all namespaces within the Default project
5. kubectl get secret for testnamespace does not display all the secrets which should be available to all namespaces. (secret3 is not displayed)
```
soumyas-MBP:kubectl soumya$ kubectl get secret --namespace testnamespace
NAME                  TYPE                                  DATA      AGE
default-token-n6f7d   kubernetes.io/service-account-token   3         54m
secret1               Opaque                                1         54m
secret2               Opaque                                1         50m
```

**Comment by soumyalj** [comment]
Tested with master from Feb 27. Once a secret for all namespace is created, kubectl does not show the secret in any namespace.

**Comment by kinarashah** [comment]
Tested with fresh setup from upstream/master feb 27, unable to reproduce this issue.

**Comment by soumyalj** [comment]
Tested with master from Feb 28. Tried the above usecase and it is functional. All secrets(available for all namespaces) are displayed correctly in a namespace "X" once a secret is created in the namespace "X" .
