### ISSUE TITLE
Alerts don't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11608]
**Rancher versions:** 2.0 master 2/23

**Steps to Reproduce:**
1.  Create a notifier that send a notification to slack
2.  Create a alert on a node with mem usage over 5%
3.  Create a workload with 20 count on that node

**Results:**  Never get alert sent to me.  I've tried CPU as well and i never got a notification.

**Comment by zionwu** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/1213386/36627278-52c52224-197b-11e8-8b95-4d6449cfd4ed.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/26
