### ISSUE TITLE
Wrong VM Size values for AzureUSGovernmentCloud

### ISSUE THREAD

**Issue by chriswastaken** [rancher/rancher#11609]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: n/a

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: n/a 
scheduler: n/a
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
n/a

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
n/a

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure - AzureUSGovernmentCloud

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Try to create a docker-machine in RancherUI and received an error when trying to select a vm size with "premium storage". 

**Results:**
Choosing Standard_DS1 returns error: 
The requested VM size Standard_DS1 is not available in the current region. The sizes available in the current region are: Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A5,Standard_A4,Standard_A6,Standard_A7,Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_D1_v2,Standard_D2_v2,Standard_D3_v2,Standard_D4_v2,Standard_D5_v2,Standard_D11_v2,Standard_D12_v2,Standard_D13_v2,Standard_D14_v2,Standard_D15_v2,Standard_D2_v2_Promo,Standard_D3_v2_Promo,Standard_D4_v2_Promo,Standard_D5_v2_Promo,Standard_D11_v2_Promo,Standard_D12_v2_Promo,Standard_D13_v2_Promo,Standard_D14_v2_Promo,Standard_F1,Standard_F2,Standard_F4,Standard_F8,Standard_F16,Standard_A1_v2,Standard_A2m_v2,Standard_A2_v2,Standard_A4m_v2,Standard_A4_v2,Standard_A8m_v2,Standard_A8_v2,Standard_DS1_v2,Standard_DS2_v2,Standard_DS3_v2,Standard_DS4_v2,Standard_DS5_v2,Standard_DS11_v2,Standard_DS12_v2,Standard_DS13-2_v2,Standard_DS13-4_v2,Standard_DS13_v2,Standard_DS14-4_v2,Standard_DS14-8_v2,Standard_DS14_v2,Standard_DS15_v2,Standard_DS2_v2_Promo,Standard_DS3_v2_Promo,Standard_DS4_v2_Promo,Standard_DS5_v2_Promo,Standard_DS11_v2_Promo,Standard_DS12_v2_Promo,Standard_DS13_v2_Promo,Standard_DS14_v2_Promo,Standard_F1s,Standard_F2s,Standard_F4s,Standard_F8s,Standard_F16s,Standard_D2_v3,Standard_D4_v3,Standard_D8_v3,Standard_D16_v3,Standard_D32_v3,Standard_D64_v3,Standard_D2s_v3,Standard_D4s_v3,Standard_D8s_v3,Standard_D16s_v3,Standard_D32s_v3,Standard_D64s_v3,Standard_E2_v3,Standard_E4_v3,Standard_E8_v3,Standard_E16_v3,Standard_E32_v3,Standard_E64_v3,Standard_E2s_v3,Standard_E4s_v3,Standard_E8s_v3,Standard_E16s_v3,Standard_E32-8s_v3,Standard_E32-16s_v3,Standard_E32s_v3,Standard_E64-16s_v3,Standard_E64-32s_v3,Standard_E64s_v3

Choosing Standard_D1_v2 returns this error:

 Message="Addition of a VM with managed disks to non-managed Availability Set or addition of a VM with blob based disks to managed Availability Set is not supported. Please create an Availability Set with 'Aligned' SKU in order to add a VM with managed disks to it."

**Comment by superseb** [comment]
Are you saying that the default is causing issues but selecting something else does work? So the default (and possibly the sizes) that are displayed should be changed?

**Comment by chriswastaken** [comment]
The first result of choosing a size that is not available in AzureUSGovernmentCloud but is available in AzurePublic throws an expected error. The expected error in this case is "Sorry, Standard_DS1 is not available here. Try these <output>." Standard_DS1 is a VM Size with premium (SSD) storage. Hence the "S".

The second result of choosing a size that is available in both AzureUSGovernmentCloud and AzurePublic results in another expected error. The expected error in this case is "Sorry, Standard_D1_v2 is available, but trying to add it to your Availability Set has failed because it has standard disks." 

I suspect this is due to small differences in the offerings and that it might just need to be updated to reflect AzureGov sizes from the UI. My hope is that we're able to change the sizes in the UI to those shown above when selecting the AzureGov endpoint. That way I'll be able to select a vm size with a premium disk and (hopefully) be able to add it to the availability set.

Let me know if that make sense and thanks for your time!

**Comment by chriswastaken** [comment]
Hey Sebastiaan, any way we might be able to get this updated? @superseb

**Comment by superseb** [comment]
Changing the available sizes to ```Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A5,Standard_A4,Standard_A6,Standard_A7,Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_D1_v2,Standard_D2_v2,Standard_D3_v2,Standard_D4_v2,Standard_D5_v2,Standard_D11_v2,Standard_D12_v2,Standard_D13_v2,Standard_D14_v2,Standard_D15_v2,Standard_D2_v2_Promo,Standard_D3_v2_Promo,Standard_D4_v2_Promo,Standard_D5_v2_Promo,Standard_D11_v2_Promo,Standard_D12_v2_Promo,Standard_D13_v2_Promo,Standard_D14_v2_Promo,Standard_F1,Standard_F2,Standard_F4,Standard_F8,Standard_F16,Standard_A1_v2,Standard_A2m_v2,Standard_A2_v2,Standard_A4m_v2,Standard_A4_v2,Standard_A8m_v2,Standard_A8_v2,Standard_DS1_v2,Standard_DS2_v2,Standard_DS3_v2,Standard_DS4_v2,Standard_DS5_v2,Standard_DS11_v2,Standard_DS12_v2,Standard_DS13-2_v2,Standard_DS13-4_v2,Standard_DS13_v2,Standard_DS14-4_v2,Standard_DS148_v2,Standard_DS14_v2,Standard_DS15_v2,Standard_DS2_v2_Promo,Standard_DS3_v2_Promo,Standard_DS4_v2_Promo,Standard_DS5_v2_Promo,Standard_DS11_v2_Promo,Standard_DS12_v2_Promo,Standard_DS13_v2_Promo,Standard_DS14_v2_Promo,Standard_F1s,Standard_F2s,Standard_F4s,Standard_F8s,Standard_F16s,Standard_D2_v3,Standard_D4_v3,Standard_D8_v3,Standard_D16_v3,Standard_D32_v3,Standard_D64_v3,Standard_D2s_v3,Standard_D4s_v3,Standard_D8s_v3,Standard_D16s_v3,Standard_D32s_v3,Standard_D64s_v3,Standard_E2_v3,Standard_E4_v3,Standard_E8_v3,Standard_E16_v3,Standard_E32_v3,Standard_E64_v3,Standard_E2s_v3,Standard_E4s_v3,Standard_E8s_v3,Standard_E16s_v3,Standard_E32-8s_v3,Standard_E32-16s_v3,Standard_E32s_v3,Standard_E64-16s_v3,Standard_E64-32s_v3,Standard_E64s_v3```

should be sufficient for now?

**Comment by chriswastaken** [comment]
Absolutely.

**Comment by RelativityChris** [comment]
Ping.

**Comment by tfiduccia** [comment]
@superseb - the standard_DS1 is no longer in the list.  But I'm not sure the correct sizes were added.  Can you verify?

**Comment by loganhz** [comment]
https://azure.microsoft.com/en-us/global-infrastructure/services/

Here is the mapping for VM sizes in different region.

**Comment by tfiduccia** [comment]
@loganhz All sizes below D aren't showing up in the list?  E, F and such isn't showing up.  I don't see that in the list?

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/40400549-2bdc1b10-5e75-11e8-9c27-866af02fc057.png)

**Comment by loganhz** [comment]
Hi @tfiduccia , I have added a new field `VM Type`. You can change it to show E and F.

![image](https://user-images.githubusercontent.com/21168270/40404245-5fe37fb6-5e89-11e8-8b29-481869d0c12a.png)

**Comment by tfiduccia** [comment]
Version - v1.6.18-rc2
Verified fixed
