### ISSUE TITLE
Editing the secret to change the secret key creates another key 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11607]
**Rancher versions:**
rancher/server: 2.0 build from master(Feb 23)

**Steps to Reproduce:**
1. Create secrets in the UI in the "Default" project
2. Edit the secrets and change the key. 

After edit, another key is created as displayed in the UI below:
<img width="1342" alt="screen shot 2018-02-23 at 4 11 27 pm" src="https://user-images.githubusercontent.com/18536626/36622783-4aa16584-18b4-11e8-8a1e-e9adcbc63aee.png">

**Comment by soumyalj** [comment]
Editing the name of the secret using UI is also lost after page refresh.

**Comment by kinarashah** [comment]
@tfiduccia It seems like this issue is prolly with ui, since 
- on editing key, data received already has appended key 
- for edit secret name, sync doesn't get called

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/36849549-5326bdb8-1d9f-11e8-90e9-df58a46efc73.png)

![image](https://user-images.githubusercontent.com/21168270/36849587-634c6f44-1d9f-11e8-8c31-5fb88b38096b.png)

UI is sending the correct name and data.
It looks like this is a backend issue.

**Comment by deniseschannon** [comment]
The fix of being able to remove keys in a map in norman is in master. This should be fixed.

**Comment by soumyalj** [comment]
Tested with v2.0.0-beta4-rc4. 
1. Create secrets in the UI  available for all namespaces or for a single namespace
2. Edit the secrets and change the key.
After editing the secret key, other keys were not created.
