### ISSUE TITLE
Secret used in the workload is not reflected in the API / UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11613]
**Rancher versions:**
rancher/server:2.0 build with master(Feb 23)

**Steps to Reproduce:**
1. Create a secret in UI in the default project
2. Create a workload by using the secret created in step 1
The secret used in the workload is not reflected in the API and not displayed in the UI too
<img width="1108" alt="screen shot 2018-02-23 at 5 23 59 pm" src="https://user-images.githubusercontent.com/18536626/36623921-6160b392-18be-11e8-8cc4-b7e3efdac09b.png">

**Comment by vincent99** [comment]
Nothing about using secrets works yet.  This is vestigial UI from preview1.

**Comment by westlywright** [comment]
Secrets have been added to the environment variables accordion as a part of the environment from ui.

**Comment by vincent99** [comment]
It should be part of the environment variable section, just like it is on create.  There shouldn't be a secrets section of details anymore, they're either in env or volumes.

**Comment by tfiduccia** [comment]
@soumyalj - I can't seem to get the workloads to create.  Maybe something I'm doing wrong.  Can you check this?
