### ISSUE TITLE
Azure AD doesnt use the Admin fields to authenticate with

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#11614]
**Rancher versions:**
rancher/server: v1.6.14

**Steps to Reproduce:**
- authenticate with bogus admin credentials
- put valid user credentials under 'test and enable' user account

**Results:**
- Azure AD is enabled and user account is used for admin bindings and group searches.

**Comment by loganhz** [comment]
@vincent99 I think this is a backend issue?
UI shows `enabled` as backend returns `20X` in this case.

**Comment by superseb** [comment]
I believe the admin credentials are not used, so they are not needed. @aemneina can clarify on this case.

**Comment by loganhz** [comment]
@aemneina Can I remove admin credentials from UI side?

**Comment by vincent99** [comment]
I'm inclined believe that they are not tested during enabling auth, but don't think it's correct that it's not used at all (e.g. for determining the groups a user is a member of when using an account API key).

**Comment by prachidamle** [comment]
@vincent99 @loganhz we can remove the Admin credentials field from UI. Azure provider uses an Azure assigned accessToken and refreshToken pair to grab the user's groups - we store these tokens in the account table when the user logs in using his password. Anytime later we need to access the user's groups/details these tokens suffice. If the accessToken has expired, refreshToken helps get a new pair of these tokens that is then stored with the account.

Thus even while using API keys, the tokens stored with the account are used  and admin creds are not needed.

**Comment by prachidamle** [comment]
I will test out the API keys usecase and confirm my understanding noted above.

**Comment by prachidamle** [comment]
Yes tested with  api keys against 1.6, confirmed that AzureAD provider does not need admin creds for any backend functionality

**Comment by sangeethah** [comment]
Tested with v1.6.19-rc5.

While enabling Azure AD auth , user is not asked to enter admin credentials anymore.

<img width="1299" alt="screen shot 2018-07-13 at 5 44 25 pm" src="https://user-images.githubusercontent.com/4266958/42719025-74e9f242-86c4-11e8-9a55-de2487afee8a.png">

Verify all the existing functionalities continues to work as expected.
