### ISSUE TITLE
rancher/kubernetes-agent:v0.6.6 does't work

### ISSUE THREAD

**Issue by loverto** [rancher/rancher#11626]
*Describe your issue here*

Expected state running but got error: Error response from daemon: connection error: desc = "transport: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`stack.index`|

![image](https://user-images.githubusercontent.com/3992018/36652034-21a413ea-1ae7-11e8-860f-fd3b2630644d.png)

**Comment by superseb** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

This does sound like either a problem with the Docker daemon, or possible version mismatch?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
