### ISSUE TITLE
Refresh repository doesn't work

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11628]
**Rancher versions:**
rancher/server: v2.0.0_223

**Steps to Reproduce:**
1. Setup Pipeline at the cluster level
2. Click `Add Pipeline` at project level
3. Click `Refresh repository` on the right of the filed `Repository`.

**Results:**
The `Repository` is still empty, nothing can be selected.

**Expected Results:**
The list of User `Repository` shows up.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
