### ISSUE TITLE
Clone Pipeline failed

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11629]
**Rancher versions:**
2.0 master 2/26

**Steps to Reproduce:**
1. Create a Pipeline
2. Click `clone` in the action dropdown-list of Pipeline table
3. Give a name to the cloned Pipeline and click `add`.

**Results:**
UI shows error
![image](https://user-images.githubusercontent.com/9334435/36657424-8ebab25c-1b07-11e8-8922-3053d678eb91.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
