### ISSUE TITLE
DefaultPodsecurity set for cluster is not functional.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11622]
Rancher server - 2.0 built from master

Steps to reproduce the problem:

Create a policy mytest1 with privileged flag not set.
Create a cluster  with defaultPodsecurity to mytest1.
Deployed workload in namespace in "Default" project with privileged set to true.
pods get deployed successfully. 
This should have failed to get deployed.

**Comment by nathan-jenan-rancher** [comment]
Fixed in:
https://github.com/rancher/rancher/pull/11606

**Comment by sangeethah** [comment]
Tested with Rancher server build from Mar 5.

Create a policy mytest1 with volume policy set to "*".
Create a cluster with defaultPodsecurity to mytest1.
Deployed workload in "Default" namespace in "Default" project with privileged set to true.
pods deployment fails with error - ```pods "testwithpriv-98844575c-" is forbidden: unable to validate against any pod security policy: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed], Deployment does not have minimum availability., ReplicaSet "testwithpriv-98844575c" has timed out progressing.```

Deployed workload in "Default" namespace in "Default" project without  privileged flag set to true.
Pods get deployed as expected.

**Comment by sangeethah** [comment]
Other related issues are tracked in:
https://github.com/rancher/rancher/issues/11971
https://github.com/rancher/rancher/issues/11973
