### ISSUE TITLE
UI - Error when trying to login into a github enabled server as user with valid access.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11639]
Rancher versions: Build from master

Steps to reproduce the problem:
Enable github authentication.
Have Allow any valid Users” / ” Restrict access to only Authorized Users and Organizations” with a user added option enabled.

Error encountered  when trying to login into a github enabled server as user with valid access.

**Comment by westlywright** [comment]
To who ever tests, this will need to be tested on a fresh setup as the original bug caused an error in the users db.

**Comment by galal-hussein** [comment]
Verified that this issue doesn't happen anymore with latest master
