### ISSUE TITLE
The column of Last Activity is changed after entered the detail page of Pipeline.

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11631]
**Rancher versions:**
2.0 master 2/26

**Steps to Reproduce:**

1. Create any Pipeline
2. Click `Run Once` in the action dropdown-list of the created Pipeline.
3. Return to the Pipeline list Page
4. Refresh Page through reload button of the browser.
5. Here you will see the sequence of Last Activity is `#1`.
6. Click the name of the created Pipeline to enter the details Page of the Pipeline.
7. Go back to the Pipeline list Page

**Results:** 
The column of Last Activity become `N/A`.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
