### ISSUE TITLE
Dropdown menu closes constantly

### ISSUE THREAD

**Issue by blar** [rancher/rancher#11634]
rancher/server: v1.6.14

**Steps to Reproduce:**
Hover over the navigation to open a down drop menu.

**Results:**
Dropdown menu closes constantly, because the menu is updated by javascript in random intervals.

![rancher](https://user-images.githubusercontent.com/111508/36690466-acc53832-1b32-11e8-9e70-07bb042350f7.gif)

Tested with Safari, Chrome and Firefox on MacOS

**Comment by rafal-prasal** [comment]
hello

steps to reproduce
\1 activate a stack with ~10-15 constantly failing services in it, like running in service/container command which does not exist
\2 try to reach menu STACK/Catalog/ADMIN 
\3 menu for switching environments works ok

it seems that Websocket communication resets too many parts of the interface. It definitely should not touch menu everytime new message about failing/restarting service is comming in.

Thank you in advance

Rafal

**Comment by ryanwalls** [comment]
+1.  This is really frustrating.  Anytime we are debugging our cluster because of instability in the latest rancher server release, we can't click the dropdown menus.

**Comment by tfiduccia** [comment]
Version - v1.6.22-rc2
Verified fixed
