### ISSUE TITLE
UI - "One or more "Targets" are required error presented to user when trying to add DNS record.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11638]
Rancher version - 2.0 build from master

Steps to reproduce the problem:
Create few workloads.
Go to "Service Discovery" tab and use "Add Record" option to add new DNS entry,
use " One or more workloads" option and select one of the workloads and click on "create" option.

Following error message is presented to the user:

<img width="1601" alt="screen shot 2018-02-26 at 12 34 43 pm" src="https://user-images.githubusercontent.com/4266958/36693893-778e9c44-1af1-11e8-9a69-cd1a82f12409.png">

**Comment by sangeethah** [comment]
Same issue is also seen when trying to add  DNS entry with "Another DNS record's value" option.

**Comment by tfiduccia** [comment]
This has been resolved as of last night.  Please retest.

**Comment by sangeethah** [comment]
This issue is not seen anymore when testing with server build from Mar 1.
