### ISSUE TITLE
Accidentally removed warning radio option in Add Alert

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11637]
**Rancher versions:** 2.0 master 2/26

**Steps to Reproduce:**
1. Go to Add Alert page

**Results:**  We accidentally removed the Warning radio option that was next to Normal.  Can you please put it back in?

**Comment by vimniky** [comment]
I have added it back.

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/26
Verified fixed
