### ISSUE TITLE
Pipeline UI Improvement

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11630]
**Rancher versions:**
2.0 master 2/26

- [x]  Have no information here to show the branch conditions like `Only the branches` or `Everything but` or  `All the branches`.
![image](https://user-images.githubusercontent.com/9334435/36658374-39be07e6-1b0b-11e8-9ced-2d953609a30f.png)

- [x] Remove redundant `}` in the UI
![image](https://user-images.githubusercontent.com/9334435/36658364-2e76ed08-1b0b-11e8-981d-992f6eb36966.png)

- [x] The sequence of Last Activity is larger than what it is.

- [x] update the text so that it shows "GitHub" instead of "GITHUB"
<img width="196" alt="screen shot 2018-02-26 at 10 13 45 am" src="https://user-images.githubusercontent.com/9334435/36706469-ea5cdc28-1ba4-11e8-9a35-20e2ea7dd292.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
