### ISSUE TITLE
Users cannot create Apikeys.

### ISSUE THREAD

**Issue by hibooboo2** [rancher/rancher#1163]
Users cannot create an api key for their account in the api. Admin can, users cannot.

To duplicate, make an account, then create an apikey for that account. Now use that apikey to auth as that user and try to make an apikey you cannot. you get a 405.

**Comment by sangeethah** [comment]
Tested with build from master - Dec 4.
Turned local auth on.
Create an account of type "user".
When logged in as this user and created apikey using http://<rancher ip>:8080/v1/apikeys.
Able to  log in to http://<rancher ip>:8080/v1/ using the keys that was created.

@hibooboo2 , could you please confirm if these steps validate the fix provided?

**Comment by hibooboo2** [comment]
That sounds correct. Just confirm that the headers that show the account id have the account id for the user that was supposed to create the apikey and not an environment unless you are using the apikey to access an environment that the user has access too.

**Comment by sangeethah** [comment]
When I access http://:8080/v1/ using the keys that was created , I can confirm that I am logged in as the user for which the keys was created.
