### ISSUE TITLE
UI - Not able to list Certificates in "Certificates" view, UI hangs. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11640]
Rancher Server - 2.0 build from master

Steps to reproduce the problem:
From project view , create a certificate.
Once user is brought back to list view , refresh this page.
UI hangs.

Relaunch project page and try to access "Cetificates" tab.

UI hangs even after the certificate is listed.

**Comment by sangeethah** [comment]
Tested with latest build from master.
This issue is not seen anymore.

**Comment by tkuther** [comment]
This happens to me in 2.0.0-beta2.

1. Create 1 or more namespace scoped certificates using kubectl
2. Try to list them in certificates view, I see following error in javascript console:
certificate.js:83
```
Uncaught TypeError: Cannot read property 'substr' of undefined
    at a.<anonymous> (certificate.js:83)
    at fe.Wt.get (ember-metal.js:2904)
    at te (ember-metal.js:2270)
    at n.compute (references.js:162)
    at n.value (references.js:38)
    at t.e.value (runtime.js:228)
    at e.initialize (reference.js:369)
    at e.peek (reference.js:343)
    at runtime.js:934
    at e.evaluate (runtime.js:73)
```
3. Delete certificate(s) using kubectl
4. View is fine again
