### ISSUE TITLE
Private registry images are not pulled successully

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11642]
**Rancher versions:**
rancher/server:master from Feb26 build

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Steps to Reproduce:**
1. From the rancher UI, add quay private registry and docker registry
2. Deploy a workload and use an image from the private registry

**Results:**
The image is not pulled successfully and the workload is deployed

<img width="1281" alt="screen shot 2018-02-26 at 2 08 42 pm" src="https://user-images.githubusercontent.com/18536626/36698388-93920e32-1afe-11e8-876e-bcf9b564bf90.png">

**Comment by soumyalj** [comment]
Tested with master. Private registry image is still not pulled. The pod is not deployed:
```
20m        21m         4         testquay-57d658f587-vzbqz     Pod          spec.containers{testquay}     Warning   Failed                  kubelet, soumyadotesting1   Failed to pull image "quay.io/xyz/testubuntu": rpc error: code = Unknown desc = Error: Status 403 trying to pull repository xyz/testubuntu: "{\"error\": \"Permission Denied\"}"
6m         21m         69        testquay-57d658f587-vzbqz     Pod                                        Warning   FailedSync              kubelet, soumyadotesting1   Error syncing pod
19m        21m         6         testquay-57d658f587-vzbqz     Pod          spec.containers{testquay}     Normal    BackOff                 kubelet, soumyadotesting1   Back-off pulling image "quay.io/xyz/testubuntu"
```

**Comment by soumyalj** [comment]
Tested with master from Feb 28. 
1. Create a cluster
2.From the rancher UI, add quay private registry and docker registry
3. Deploy a workload and use an image from the private registry

The image is pulled successfully and the workload gets deployed.

**Comment by mhermosi** [comment]
> Tested with master from Feb 28.
> 
> 1. Create a cluster
>    2.From the rancher UI, add quay private registry and docker registry
> 2. Deploy a workload and use an image from the private registry
> 
> The image is pulled successfully and the workload gets deployed.

Hi @soumyalj,

can you put an example of the quay or private registry?

I have created a Registry Credential resource on my project namespace

let's say name XXX with address: reg.internal.mydomain.com username and password set,

then I try the pod with the following:
```
image: https://reg.internal.mydomain.com/myimagebasename/myimage-app-name:version (does not work)

image: reg.internal.mydomain.com/myimagebasename/myimage-app-name:version (does not work)

image: reg.internal.mydomain.com:443/myimagebasename/myimage-app-name:version (does not work)

image: my-regcred-name/my-namespace/myimagebasename/myimage-app-name:version (does not work)
```

so not sure what to do.. I am running tail on my docker registry pod. and there is no attempt to connect from rancher when deploying my pods.

if I issue the command ``` #docker login --username=myuser https://reg.internal.mydomain.com``` login happens and I see in the logs the corresponding logs
