### ISSUE TITLE
Ingress - "308 Permanent Redirect" error when creating a ingress with rule having no requested host

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11646]
Server version - 2.0 build from master

Create an Ingress with rule having no requested host.

When access the ingress url (with no hostname passed) , we "308 Permanent Redirect" error.
```
Sangeethas-MBP:testwget sangeethahariharan1$ wget http://<host-ip>/name.html
--2018-02-26 14:19:39--  http://<host-ip>/name.html
Connecting to 159.65.160.243:80... connected.
HTTP request sent, awaiting response... 308 Permanent Redirect
2018-02-26 14:19:39 ERROR 308: Permanent Redirect.

Sangeethas-MBP:testwget sangeethahariharan1$ 
```

**Comment by alena1108** [comment]
@kinarashah check if a) ingress got programmed correctly b) if yes, how nginx controller should handle it.

**Comment by orangedeng** [comment]
I think this is by designed. refer to `https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/configmap.md#http-redirect-code`

**Comment by orangedeng** [comment]
@sangeethah If you try that page in your browser, you will see your browser will get 308 code response and redirect to the current location. 308 code is not a error response by it definition.

I think curl supports redirect code with specific flags `-L, --location` and wget supports this after v1.19.3-release with gnu version.

**Comment by sangeethah** [comment]
@orangedeng When I use the browser , I see the request getting redirected to ```https``` , Is this expected ?

**Comment by orangedeng** [comment]
@sangeethah Yes, it is expected. That is what the nginx ingress controller choose to use.
