### ISSUE TITLE
Pipeline forcing me to re-add Github info even thou I'm already authenticated

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11656]
**Rancher versions:** 2.0 master 2/26

**Steps to Reproduce:**
1.  Go to Global/Security/Authentication
2.  Enable Github
3.  Go to Pipeline

**Results:**  Forcing me to input all the github information again.  Shouldn't have to do that, since I'm authenticated through Github.

**Comment by biblesyme** [comment]
We will add an option to re-use the GitHub information in Global/Security/Authentication.
But, the user still has to authenticate it once again, cause we need to gain more permissions for Pipeline.

**Comment by biblesyme** [comment]
@lvuch @vincent99 Could you help me design what the UX should be if we add this Option in the Authentication Page of Pipeline? I can't image how it looks like.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
