### ISSUE TITLE
Write basic instructions for Rancher 2.0 offline installation 

### ISSUE THREAD

**Issue by amitshlo** [rancher/rancher#11654]
If possible, It would be great to have basic instructions for how to install Rancher 2.0 in a place with no internet connection.
Maybe just something basic at first, so we will at least know where to start.
You could publish a list of images and tags used, and explain if it's enough to upload all of them to the same private registry.

**Comment by loganhz** [comment]
The documentation link for offline installation is https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-installation/
