### ISSUE TITLE
Ingress - "503 Service Temporarily Unavailable" when providing targets from other namespace (other than were ingress is created).

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11651]
Steps to reproduce the problem:
Create a project with 2 namespaces , n1 and n2.
Create ingress in n1 with targets pointing to workloads in n2.

Accessing ingress url  results in "503 Service Temporarily Unavailable".

```
Sangeethas-MBP:testwget sangeethahariharan1$ wget --header="host: hello.com" http:<ip>//name.html
--2018-02-26 14:27:57--  http://<ip>/name.html
Connecting to 159.65.160.243:80... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2018-02-26 14:27:57 ERROR 503: Service Temporarily Unavailable.

Sangeethas-MBP:testwget sangeethahariharan1$ 
```

Should we not allow for creating rules with targets from different namespace ?

**Comment by alena1108** [comment]
@sangeethah this is ingress limitation. Ingress controller would look only in services in the same namespace. UI should filter out only services from the same NS

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/3
Verified fixed
