### ISSUE TITLE
Vultr Cloud - Shell closing fast and no Stats but stats from the Machine showing. Rancher is ignoring the vultr's watch

### ISSUE THREAD

**Issue by MichelDiz** [rancher/rancher#11657]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3 
ipsec: rancher/net:holder
network-services: metadata:v0.9.5 network-manager:v0.7.19
scheduler: scheduler:v0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
Rancher Agent
```
[root@vultr ~]# docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```
Rancher Server
```
[rancher@rancheros-01 ~]$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
[root@vultr ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

vultr

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher OS Local => CentOS Rancher agent on Vultr Cloud.
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

Random Stetps.

Seems like https://github.com/rancher/rancher/issues/10770

I can't use Logs or Shell. But all works fine. Without Shell I can't do any log or test.

Currently I already know how to solve this problem. But it seems to me something new. I updated the instance of the vultr to the correct TimeZone with my machine. So far so good, I've been using Rancher for over 24 hours. By the time it started to give out expired.

I already rebooted the machine. I have already restarted my machine. Clean all possible caches. I have already updated the dates of all forms in all machines. Everything is correct. But Rancher has a deporting behavior in CentOS. You can see in the LOGs below.

In the log Rancher reports it is 2018-02-27T00: 12: 09Z but when I ask the system "date" it returns me Mon Feb 26 21:12:12 -03 2018.

Obvious there is a huge disparity of time there. But I'm sure the clock on the machine is correct. Rancher can not upgrade according to TimeZone's machine on the vultr.

Rancher is ignoring the vultr's watch.

**Results:**

```shell
time="2018-02-27T00:06:23Z" level=error msg="Couldn't find container for id." error="token is expired" id=21518258b3b974f29f2ed50654acb6a175c666ca84ee21e2a4fa34f120d712b3
time="2018-02-27T00:08:13Z" level=error msg="checking aliyun cloud provider error after 2 attempts, last error: Get http://100.100.100.200/latest/meta-data/zone-id: dial tcp 100.100.100.200:80: i/o timeout"
time="2018-02-27T00:12:02Z" level=error msg="Couldn't find container for id." error="token is expired" id=6757330a2e8f6fac560bb6f598fe3d034e99d945a5e5abeb1002dafdfdaf39e5
time="2018-02-27T00:12:04Z" level=error msg="Couldn't find container for id." error="token is expired" id=6757330a2e8f6fac560bb6f598fe3d034e99d945a5e5abeb1002dafdfdaf39e5
time="2018-02-27T00:12:06Z" level=error msg="Couldn't find container for id." error="token is expired" id=6757330a2e8f6fac560bb6f598fe3d034e99d945a5e5abeb1002dafdfdaf39e5
2018/02/27 00:12:07 "token is expired"
goroutine 874 [running]:
github.com/rancher/agent/service/hostapi/app/common.CheckError(0xf44600, 0xc420166b00, 0x2)
	/go/src/github.com/rancher/agent/service/hostapi/app/common/error.go:14 +0x89
github.com/rancher/agent/service/hostapi/auth.GetAndCheckToken(0xc4200a4039, 0x3f4, 0xa76257, 0x5)
	/go/src/github.com/rancher/agent/service/hostapi/auth/auth.go:49 +0x227
github.com/rancher/agent/service/hostapi/exec.(*Handler).Handle(0xf98c28, 0xc4200a4000, 0x24, 0xc4200a4029, 0x404, 0xc4201becc0, 0xc42042a120)
	/go/src/github.com/rancher/agent/service/hostapi/exec/exec.go:35 +0x129
created by github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend.connectToProxyWS
	/go/src/github.com/rancher/agent/vendor/github.com/rancher/websocket-proxy/backend/backend.go:82 +0xa30

E0227 00:12:07.914187    1218 error.go:23] %q
%s
 token is expired
time="2018-02-27T00:12:09Z" level=error msg="Couldn't find container for id." error="token is expired" id=6757330a2e8f6fac560bb6f598fe3d034e99d945a5e5abeb1002dafdfdaf39e5

```

```bash
[root@vultr ~]# date
Seg Fev 26 21:12:12 -03 2018
[root@vultr ~]#

```

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
