### ISSUE TITLE
Failed or inconsistent image activations with valid dockerfile

### ISSUE THREAD

**Issue by dx9** [rancher/rancher#11667]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

Image builds fail in unexpected ways due to Dockerfile truncation. Can manifest as an activation failure or as a successful activation with an inconsistent image.

The issue affects hosts with docker versions 17.06.0 through 17.11.0.

This Dockerfile will cause an inconsistent image to be deployed: https://gist.githubusercontent.com/dx9/227f13379e109b27cfbf002dcddb2db1/raw/6859cbf5d704ffe46ba10c780fce7015bf6ff7e3/Dockerfile.nginx-php7.2-fpm

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
