### ISSUE TITLE
Pipeline fails when set Pipeline with branch condition `Everything but`.

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11665]
***Steps to reproduce***
1. Add a Pipeline with branch condition `Everything but`.
2. Click `Run Once` in the action menus.

***Results***
Pipeline failed in the first step, fail to checkout branch.

**Comment by biblesyme** [comment]
Before run Pipeline with `Everything but`, ask the user for a branch. And if user select CRON trigger, they can just select `Only the branch`

**Comment by tfiduccia** [comment]
Version - v2.0.0-alpha18
