### ISSUE TITLE
Users cannot be added to the cluster through "edit cluster" option

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11660]
**Rancher versions:**
rancher/server:2.0 master from Feb 23rd build

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Steps to Reproduce:**
1. As admin, create a cluster "cluster1" through add cluster
2. Create user1 at the global level
3. Add user1 as owner or member to the cluster by editing the "cluster1" and clicking on member roles.
4. Click on Save 

**Results:**
The user does not get added to the cluster with the assigned role.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/3
Verified fixed
