### ISSUE TITLE
Cluster stuck in "updating" state when adding 1 node with "all" roles and 2 worker nodes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11661]
Rancher versions: v2.0 build from master

Steps to reproduce the problem:
Create a cluster using DO machines using the following configuration:

<img width="1303" alt="screen shot 2018-02-26 at 5 34 13 pm" src="https://user-images.githubusercontent.com/4266958/36705784-c4898890-1b1b-11e8-97da-ffff141d904d.png">
 
Cluster stuck in "updating" state with following error message - 
"[network] Port check for ports: [**:2379, **:2380] failed on host: [**]"

Then node with all roles got to active state , but the worker nodes are stuck in “Registering” state

**Comment by galal-hussein** [comment]
@sangeethah I tried with the latest master with the same configuration and i can't reproduce, i also tried setting the rancher server in AWS and can't reproduce as well.

**Comment by soumyalj** [comment]
Tested with master from March 2nd. Creating a cluster with above configuration was successful.
Creation of pods after cluster creation was ok too.
