### ISSUE TITLE
rancher健康检查

### ISSUE THREAD

**Issue by quguiliang** [rancher/rancher#11662]
*Describe your issue here*
rancher的健康检查是否只能检测TCP或者HTTP。如果上层应用没有开放TCP或者HTTP，如何进行健康检查？

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by superseb** [comment]
No, at this moment we only have HTTP and TCP healthchecks. We have this issue open for supporting commands in healthchecks. https://github.com/rancher/rancher/issues/5790
