### ISSUE TITLE
Rancher 2.0 RKE on Azure create 1 NSG per VM

### ISSUE THREAD

**Issue by Kishijoten** [rancher/rancher#11674]
Hello,

Trying out the RKE deployment on Azure and noticed that there is 1 Network Security Group per VM. Which is a very granular way of protection but the complexity of managing those when you increase the size of the cluster isn't appealing.
Also, unless it's very needed of course, it is considered as best practice by Microsoft to attach the NSG to the subnet that where the VMs NICs are attached which would be a lot easier to manager when scaling.

Microsoft best practices for Networking on Azure:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/best-practices-network-security.md

Cheers.

(I'm following rancher very closely as it's an awesome project 👍 )

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha16` UI: `v2.0.20` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by tfiduccia** [comment]
@Kishijoten - We no longer offer Azure through RKE.  We now offer Azure Container Service, the acs creates a single security group per cluster.

**Comment by TimBobkov** [comment]
I have use Rancher 2.0.0 release and have the same problems - I have create cluster in Azure (not AKS) and Rancher create NSG per machine and not create main NSG (which I set at Azure config during deploying). As a result LoadBalancer have not work until I create main NSG and services have been unavailable until I change NSG for each machine manually. So please improve script for deploying cluster without using AKS.

The reason I don't use AKS - AKS is very unstable. I have got 3 inaccessible clusters with this service and data loss. So I don't want to use AKS.

**Comment by CRuppert** [comment]
Is this really the case @tfiduccia ? 
AKS is still in super early access and isn't widely available! Are you really saying that you guys don't support the Azure clusters anymore, only AKS? It still shows prominently in the UI and stuff. 

As it is, it prevents any LBs from working out of the box, at least that's been my experience so far. 
This appears to be a bug as in the Node templates you can't set NSG, and in the Cluster config, NSG appears to be respected for everything but nodes.

**Comment by tfiduccia** [comment]
@CRuppert - That comment was from March.  Azure on RKE has been added back into the 2.0 product.

**Comment by CRuppert** [comment]
Ah! Cool! Thank you, @tfiduccia that makes me feel much better. I *think* i might have a workaround, or it was a fever dream. If so I will post back here.

**Comment by mitchellmaler** [comment]
@CRuppert @tfiduccia My workaround was to modify docker-machine so I can specify the nsg to create/attach to the provisioned VMs. Since rancher doesn't have UI for it I just use a different resource group per cluster and have an environment variable set in the rancher container to use the new docker-machine option and custom built the container replacing the built-in docker-machine with my modified one.

I raised a pull request a pull request for docker-machine but it has not been touched. https://github.com/docker/machine/pull/4486

**Comment by CRuppert** [comment]
@mitchellmaler  I saw that PR sitting there, and was hoping it would be accepted.  This project has a lots of unanswered approved PRs.
Right now all of this is giving me pause about hitching our infra to Rancher.  I like the concept. I just wish it was a little more ready. :(

**Comment by bigredthelogger** [comment]
Has this been corrected as of yet?

**Comment by tfiduccia** [comment]
@bigredthelogger - no this has not been resolved.  Each VM creates it's own NSG.

**Comment by bigredthelogger** [comment]
Thanks. I hope that this is something that is implemented, as I would require this in order to use Rancher.

**Comment by mitchellmaler** [comment]
@bigredthelogger This issue is actually with Docker Machine. Currently the code defaults to creating a nsg for each vm and you can't provide an existing one to attach too. I actually created a PR (as a start) to add a flag and env var to set the provisioned vms nsg to a named one instead of letting it create on automatically. docker/machine#4486

**Comment by bigredthelogger** [comment]
@mitchellmaler thanks for this. I hope that they accept your PR as this would be a great feature.

**Comment by aiyengar2** [comment]
https://github.com/rancher/machine/pull/77 should facilitate creating one NSG that is attached to all nodes in a node template

**Comment by soumyalj** [comment]
Tested with master-head(1afaa4768)
Azure node template supports NSG field. 

- NSG field empty
 1. Create azure node template with NSG field empty. 
 2. Create azure cluster with the template. 
 3.   One NSG per VM was created and cluster was active and functional

- Provide NSG name(non existing) in the NSG field
 1. Create azure node template with a NSG name(non existing) in the NSG field
 2. Create azure cluster with the template. 
 3. Only one NSG was created per node pool using  the template
 4. Create multiple clusters using the same node template. The nodes will use the same NSG.
