### ISSUE TITLE
Edit Custom cluster shows all drivers nodes instead of only custom code

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11671]
**Rancher versions:** 2.0 master 2/26

**Steps to Reproduce:**
1.  Create a custom cluster
2.  Edit custom cluster

**Results:**  All node driver are showing up in Edit.
![image](https://user-images.githubusercontent.com/11514927/36713798-8bb8d0da-1b4c-11e8-8b73-5a10988cecf1.png)

**Comment by loganhz** [comment]
@vincent99 how to distinguish custom cluster from the cluster created by node driver?

**Comment by tfiduccia** [comment]
Version 2.0 master 3/26
Verified fixed
