### ISSUE TITLE
Support yaml file for pipeline

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#11675]
1. support export a yaml file from existing pipeline
2. support create a pipeline by importing a yaml file.
3. support create a pipeline by specifiy a repos that contains the yaml file.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Importing yaml that I just exported doesn't work
![image](https://user-images.githubusercontent.com/11514927/37626415-35fe3bac-2b8d-11e8-9576-59f036bef0c4.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Export and import from the UI is working.  What are the requirements for the repo.  I added the exported yaml file to my repro.  But when I click on Import Pipeline from Respository, it says No Pipeline Found
 
![image](https://user-images.githubusercontent.com/11514927/37938846-a85988b4-3114-11e8-8e6b-5b40f1164ed8.png)

**Comment by biblesyme** [comment]
@tfiduccia you need a file named `.pipeline.yml` in the root path of your repo.

**Comment by tfiduccia** [comment]
@biblesyme - we export a file called pipeline-name.yaml.  So shouldn't we support yaml extension as well?

**Comment by biblesyme** [comment]
Yes, I thought we should support it so that user can directly use the exported file in their repository. @gitlawr How do you think of it?

**Comment by gitlawr** [comment]
I think we should export with file name `.pipeline.yml`. It is hard to choose a unique file to import from repo given arbitrary filename without prior knowledge

**Comment by gitlawr** [comment]
ok, we'll export `pipeline-${name}.yaml`, and look for `.pipeline.yaml` in the repo.
Users need to do renaming if they want to put exported pipeline file to the repo.

**Comment by gitlawr** [comment]
ok

**Comment by gitlawr** [comment]
@tfiduccia both formats are supported now

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
