### ISSUE TITLE
Automated Rancher 1.6 Deployment - oneclick

### ISSUE THREAD

**Issue by obriensystems** [rancher/rancher#11680]
**Rancher versions:**
rancher/server: 1.6.10, 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12 and 17.03
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2, Azure VM, GCE VM, Openstack VM, VMware workstation 14/fusion10 VM
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node colocated 
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**

**Results:**

https://jira.onap.org/browse/OOM-715
https://gerrit.onap.org/r/#/c/32019/
https://jira.onap.org/browse/OOM-710

**Comment by superseb** [comment]
Are you running into something or are you sharing this for others? If the latter, please create a forum post to explain people how to use it. If you are running into a bug or something else, please let me know what exactly so we can investigate.
