### ISSUE TITLE
External DNS service using service name

### ISSUE THREAD

**Issue by pythiancastaneda** [rancher/rancher#11697]
Hello 

In my Kubernetes environment,  I’m trying to use the Route53 external DNS service to create records for services based on the service name in route53. 

Is there’s a way I can get it to use the kubernetes raw ingress name instead the rancher with the prefix: "default-rancherlb-elb-" 
o.e:

My ingress name is kubernetes is x-y-z-1
In Rancher, this gets turned into default-rancherlb-x-y-z-1 and that is the entry added in route53.

**Rancher versions:**
rancher/server: 1.6.14

**Infrastructure Stack versions:**
route53: external-dns:v0.7.9

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal with Route53 zone

```
$ kubectl get ing
NAME      HOSTS     ADDRESS         PORTS     AGE
kuard     *         192.168.1.158   80        18h
```

![screenshot from 2018-02-26 19-32-56](https://user-images.githubusercontent.com/3359197/36752061-8c364634-1bc7-11e8-909c-c9aa28c1fb4c.png)

![screenshot from 2018-02-26 19-33-33](https://user-images.githubusercontent.com/3359197/36752127-bec06a12-1bc7-11e8-8725-bbe9f4af9c2d.png)

Thanks in advance

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
