### ISSUE TITLE
Username for github users is blank

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#11691]
Rancher server: master at 27 Feb

Steps to reproduce:

- Enable github authentication
- allow for any valid user
- try to login with any github user
- go to users tab

the github user's username is blank and only user's id appear in the api:

```
{
"actions": {
"setpassword": "…/v3/users/user-qrm7p?action=setpassword"
},
"baseType": "user",
"created": "2018-02-27T19:07:50Z",
"createdTS": 1519758470000,
"creatorId": null,
"description": "",
"id": "user-qrm7p",
"labels": {
.....
},
"links": {
.....
},
"principalIds": [ 2 items
"github_user://22842255",
"local://user-qrm7p"
],
"type": "user",
"uuid": "81807fa4-1bf1-11e8-bf24-0242ac110002"
}
```

**Comment by cjellick** [comment]
the user.username field won't be set in the api with the github username. That field is only for the "local" username. Display in the UI should be based off of the principals api. Assigning over to @westlywright

**Comment by cjellick** [comment]
This requires me to first implement get-principal-by-id. co-assigning to me

**Comment by cjellick** [comment]
I now set user.name to the GH login name if the Gh account doesnt have a display name. user.username will continue to be unset because that is just the rancher local user login name and should not be set in the case of a GH user

**Comment by cjellick** [comment]
I guess i will assign this over to just @westlywright so that he can do the bit of integrating principal

**Comment by galal-hussein** [comment]
@vincent99 @westlywright I am still seeing blank username in the members list:

<img width="1240" alt="screen shot 2018-03-03 at 3 55 56 pm" src="https://user-images.githubusercontent.com/3309968/36935097-742ef388-1efb-11e8-8026-6ac3bf846e67.png">

i am using user `rancheruser`

**Comment by westlywright** [comment]
@galal-hussein I've just talked to craig about this and without making a call to the principal search api for every user (who could have multiple principal ids) from UI the `username` field will be blank and show `None` in the api. But we found an issue where the display name is not being set so he is looking into that. I'm assigning this back over to him.

**Comment by cjellick** [comment]
Fixed. Display name will be set. username will not, per previous comments

**Comment by galal-hussein** [comment]
I can verify that i can see the display name for the users with the latest master
