### ISSUE TITLE
Not able to add github users to list of authorized users and organizations

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#11695]
Rancher server: master Feb 27

steps to reproduce:

- enable github authentication
- choose `Restrict access to only Authorized Users and Organizations`
- add any github user

results:

```
Principal not found: undefined
```
can't see any server logs as well

**Comment by cjellick** [comment]
was not able to reproduce exactly. only way i could get this error message was if the entered username was not in github. @galal-hussein is going to retest and close if he cannot repro. if he can, we'll do a screen share to nail it down

**Comment by galal-hussein** [comment]
@cjellick I am not able to reproduce with the latest master, i can add users normally and login normally, thanks!
