### ISSUE TITLE
Pipeline menu shows up across clusters that shouldn't have it.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11693]
**Rancher versions:** 2.0 master 2/27

**Steps to Reproduce:**
1.  Create two cluster
2.  Add Pipeline to one of the clusters
3.  Go to the Default project and see that Pipeline shows up in workloads section
4.  Switch using drop-down menu to Default project of other cluster (the one where pipeline is not authenticated)

**Results:**  The Pipeline menu shows up.  If you click on the cluster in drop-down then click on the project, the pipeline menu goes away.  Then if you switch straight to the default project that is supposed to have pipeline, it's not there.  Basically showing pipeline logic is set up if you select the cluster first.  It should work if I click on project.

**Comment by biblesyme** [comment]
@vincent99  I need to do an async request to see if Pipeline is deployed in a certain Cluster before User enter, I am not sure where the logic I should put in. 

I tried 
`services/pipeline`
```
import Service from '@ember/service';
import { inject as service } from '@ember/service';


export default Service.extend({
  globalStore: service(),
  scope: service(),
  deploy: false,
  isReady(clusterId) {
    let requestClusterId = clusterId||this.get('scope').currentCluster.id;
    this.set('deploy', false);
    return this.get('globalStore').find('clusterPipeline', `${requestClusterId}:${requestClusterId}`)
      .then((res)=>{
        this.set('deploy', res.deploy);
      }).catch((res)=>{
        this.set('deploy', false);
      })
  },
});

```
`authenticated/project/route.js`
```
model(params, transition) {
    return get(this, 'globalStore').find('project', params.project_id).then((project) => {
      return get(this,'scope').startSwitchToProject(project).then(() => {
        return PromiseAll([
          this.loadSchemas('clusterStore'),
          this.loadSchemas('store'),
        ]).then(() => {
          return PromiseAll([
            this.preload('namespace','clusterStore'),
            this.preload('pod'),
            this.preload('workload'),
            this.preload('dnsRecord'),
            this.preload('secret'),
            this.preload('service'),
            this.preload('namespacedSecret'),
            this.get('pipeline').isReady(project.clusterId),
          ]).then(() => {
            return EmberObject.create({
              project,
            });
          })
        });
      });
    }).catch((err) => {
      return this.loadingError(err, transition);
    });
  },
```
`components/containers-header/component.js`
```
 pipelineDeploy: function(){
    return this.get('pipeline.deploy');
  }.property('pipeline.deploy'),
```

**Comment by vincent99** [comment]
Wasn't there a separate issue to show it all the time and explain why it's not available in this project if it's not on?  Then you could just do this check on the pipeline route.

**Comment by tfiduccia** [comment]
Version - this was more about actual created pipelines showing up across cluster.  This was fixed so I'm going to close this.
