### ISSUE TITLE
Rollback/Pause/Upgrade actions for workload of deployment kind

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11692]
Kubernetes deployment supports upgrade/rollback/pause actions; we should enable those actions in our API as well on the workload. Following needs to be covered:

* the actions should be enabled on workload of type deployment only
* we should figure out if all the required fields are enabled in the API, and follow up with the UI on what fields need to be populated.

**Comment by deniseschannon** [comment]
This seems related: https://github.com/rancher/rancher/issues/11052

**Comment by kinarashah** [comment]
@vincent99 just wanted to let you know PR for actions on deployment type got merged, would need ui to be updated accordingly

**Comment by loganhz** [comment]
@kinarashah what's the payload for `rollback` should UI send?
I tried this but it doesn't work. 

```
{
     revision:1
}
```

Server returns `Error updating workload deployment:default:aa by rollback`.

**Comment by loganhz** [comment]
@kinarashah for the `pause` action, if I paused a workload how to `resume` it?  I didn't find the action to resume.

**Comment by kinarashah** [comment]
@loganhz The way I tested rollback was - 
`curl https://localhost:8443/v3/project/local:project-l7pjm/workloads/deployment:default:test?action=upgrade -X POST -d '{"revision":1}'` 

Right now, if you just make call to pause again, it'll resume it. Would you prefer a separate action for resume?

**Comment by vincent99** [comment]
What is the upgrade action/why is it needed?

For rollback, similar stuff as with pause/unpause:
 - Action need to show up on `deployment`, not `workload`.
 - Workload schema describes the input as `rollback`, but there's no schema for that
 - Should only be returned in the actions map if there are revisions to roll back to (unless totally impractical)

**Comment by alena1108** [comment]
Couple more things:

* reflect the pause field as a top field in deployment/workload api
* investigate what the upgarde field is. If it does the same thing as update, hide the upgrade.
* pausing already paused one unpauses it

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified added & working
