### ISSUE TITLE
Pipeline should always exist

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11700]
**Rancher versions:** 2.0 master 2/26

**Comment:**  We don't normally add/remove pages.  Pipeline page should always exist and just if you are not authenticated, it should say with a link to the configuration page.

**Comment by biblesyme** [comment]
@vincent99 Is there any example I could follow?

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/1
Verified fixed
