### ISSUE TITLE
Support Generic Machine drivers in UI

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1170]
Rancher API already supports all drivers in Machine other than GCE.  For non-1st class drivers, we should have a simple drop-down to select these generic drivers with a set of unordered form inputs to add them.

**Comment by aruneli** [comment]
This is broken in 0.40.0 and @vincent99 has the fix in next build.

**Comment by aruneli** [comment]
```
Component 	Version
Rancher 	v0.40.0-rc2
Cattle 	v0.96.0
User Interface 	v0.54.0
Rancher Compose 	beta/latest
```

verified that generic drivers are able to make calls to machine now.
