### ISSUE TITLE
Pipeline UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11702]
**Rancher versions:** 2.0 master 2/27

**Results:**

- [x] Activate image should be play not a +:
![image](https://user-images.githubusercontent.com/11514927/36757764-a2a3031e-1bcf-11e8-8d25-9ef33bd226db.png)

- [x] Add Pipeline button should not have + in front and the button should all be dark blue
![image](https://user-images.githubusercontent.com/11514927/36757796-b3399828-1bcf-11e8-8298-71ef37c63c49.png)

- [x] Activate in menu should be play button
![image](https://user-images.githubusercontent.com/11514927/36757844-ccf7468e-1bcf-11e8-8057-523531efb21e.png)

- [x] Add Pipeline - Add Repository page the text is all the same color and size.  It needs some designing.
![image](https://user-images.githubusercontent.com/11514927/36758105-9e8ab730-1bd0-11e8-9a6d-70e2a0d589da.png)

- [x] Add Pipeline - everything is dimmed and I can't tell what I can and cannot click on
![image](https://user-images.githubusercontent.com/11514927/36758138-bb8cbd92-1bd0-11e8-93dd-d1e1e11a0084.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/1677

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/28
Verified fixed
