### ISSUE TITLE
Not able to add DO node templates from "Add Template" option.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11717]
Rancher server version - Build from master

Steps to reproduce the problem:
Create a DO template using "Add Template" option.
DO template creation fails with following error:

<img width="898" alt="screen shot 2018-02-27 at 3 12 40 pm" src="https://user-images.githubusercontent.com/4266958/36760696-b8f4f28e-1bd0-11e8-8943-e179b51d0990.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/1
