### ISSUE TITLE
Add a "description" or "info" parameter to Rancher API parameters

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1171]
Support the ability to add a "description" for each parameter of the Rancher API.  For example:

Under, a machine driver, there's a string parameter called "accessToken".  It'd be nice to add a "description" for this parameter so the UI can display it as a helper text for the form input.

**Comment by vincent99** [comment]
This isn't well documented or really used at all, but the API UI supports a collection that cattle sends called `typeDocumentation` with descriptions for each resource and field.  These could be shown in the regular UI too.

**Comment by will-chan** [comment]
This has been added.
