### ISSUE TITLE
RKE node list page is broken (Missing + - to change node amount & headers that separate type.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11710]
**Rancher versions:** 2.0 master 2/27

**Steps to Reproduce:**
1.  Setup DO RKE cluster with 1 all and 2 worker nodes
2.  Go to node list page

**Results:**  Missing a bunch of stuffs
![image](https://user-images.githubusercontent.com/11514927/36760026-900dc4bc-1bd6-11e8-93c6-7a720a9ae922.png)

**Comment by vincent99** [comment]
![image](https://user-images.githubusercontent.com/753917/36919994-75366304-1e1c-11e8-869e-95f27c488ded.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/2
Verified fixed
