### ISSUE TITLE
Performance - takes a long time to see catalog templates after enabling

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11723]
**Rancher versions:** 2.0 master 2/27

**Steps to Reproduce:**
1.  Enable Helm catalogs
2.  Go to Projects/Catalog and try to see the templates

**Results:**  It takes a really long time for the templates to load.

**Comment by StrongMonkey** [comment]
should be much better now. would need less than 10 seconds to load all the templates now.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/28
Verified better
