### ISSUE TITLE
As a cluster member, when adding another user, UI is stuck in saving state

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11720]
**Rancher versions:**
rancher/server: master from feb 27 

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Steps to Reproduce:**
 1. As admin user ,  create cluster - C1.   
2. Create user1, user2
3. Add  user1 to this cluster as   "Cluster Member" role.   
4. Create a project P1.   
5. Login as user1 and add user2 to the cluster.

Addition of user2 fails as expected, but the UI is stuck in "Saving" state.

<img width="744" alt="screen shot 2018-02-27 at 5 24 12 pm" src="https://user-images.githubusercontent.com/18536626/36764787-122624ce-1be3-11e8-8be5-8534b89d0058.png">

<img width="589" alt="screen shot 2018-02-27 at 5 25 01 pm" src="https://user-images.githubusercontent.com/18536626/36764808-2c175556-1be3-11e8-97bd-e7119fd8264a.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/3
Not fixed, same error.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/4
Still not fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Still broken

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
