### ISSUE TITLE
Defaults missing from customize schema for Active Directory Authentication

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11729]
**Rancher versions:** 2.0 master 2/27

**Steps to Reproduce:**
1.  Try to setup Active Directory authentication

**Results:** Customize Schema section is missing all the defaults

**Comment by cjellick** [comment]
i added the defaults to the schema, so @westlywright will need to reflect that in the UI. but i also need to change the action handler to populate the defaults if they are not passed in. So, im keeping myself assigned in addition to assing to wes

**Comment by cjellick** [comment]
Ok, I've added logic to set the defaults in the action if they are not set. UI just needs to properly display the defaults to be on par with the 1.6 UI

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Verified fixed
