### ISSUE TITLE
Embedded logging won't setup and is throwing errors

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11736]
**Rancher versions:** 2.0 master 2/27

**Steps to Reproduce:**
1.  go to logging
2.  Try to enable Embedded Elasticsearch

**Results:**  Errors saying failed to deploy elasticsearch & failed to deploy Kibana
![image](https://user-images.githubusercontent.com/11514927/36778889-5e2b70e8-1c2b-11e8-833d-8367575211c9.png)

**Comment by tfiduccia** [comment]
@zionwu - this says resolved and merged but I still can't get it to work?  Is this supposed to be resolved and sent back to test?

**Comment by tfiduccia** [comment]
2.0 master 3/11
I am still seeing this error.  I upped my mem to 8.  Embedded doesn't even try to setup before i get the error.
![image](https://user-images.githubusercontent.com/11514927/37267810-c878ca7e-257f-11e8-8f31-61b3f1ca53c8.png)

**Comment by aiwantaozi** [comment]
Hi @tfiduccia the related PR not merge yet. https://github.com/rancher/rancher/pull/11940

**Comment by aiwantaozi** [comment]
@tfiduccia The PR is merged, could you help test it?

**Comment by tfiduccia** [comment]
Version: 2.0 master 3/19
Verified fixed
