### ISSUE TITLE
Configurable range for NodePort workload ports

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11732]
Currently UI hardcodes node port range to 30000/32767 as that's the default node port range on k8s. It should be made configurable, either via global setting, or per cluster.

**Comment by vincent99** [comment]
@alena1108 Where are the API fields to set?

**Comment by alena1108** [comment]
@vincent99 Source port for port of kind=HostPort/NodePort

**Comment by vincent99** [comment]
I mean the field to get/set the allowed nodeport range for the cluster.

**Comment by alena1108** [comment]
@vincent99 `--service-node-port-range` is an extra argument that you can pass to rke cluster to configure this range. We can either display it as a special field in the UI, and then convert to extra args on rke config, or define this field explicitly on rke config. For the second way, api changes will be needed.

**Comment by vincent99** [comment]
I'd rather be able to get and set them as real fields than parsing them out of arbitrary string extra args...

**Comment by deniseschannon** [comment]
Backend is in for rke,  how would this work for cloud clusters or imported ones?

**Comment by vincent99** [comment]
We have no control of it for imported

**Comment by LinAnt** [comment]
I think it would be nice if the Cluster Administrators would be able to disable NodePorts altogether. Maybe it could come with this change?

**Comment by loganhz** [comment]
Added an `Node Port Range` field in cluster options.

When you specify a listening port for a workload node port in a cluster with `Node Port Range` defined,  you can only input the port in the range.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/27
Verified fixed
