### ISSUE TITLE
Containers are getting deployed in hosts that are in "reconnecting" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1173]
Tested with server version - v0.24.0-rc1

Had a server with health check enabled and scale 5 where 3 instances of the service was running on host1.
Stopped host1.

I see the host is in "reconnecting" state and all 3 instances were identified as being unhealthy.
For 2 of the instances , we were able to deploy 2 more instances in other hosts.
But 1 of instances was attempted to start in the host that is in "reconnecting" state.
This instance is stuck in "starting" state forever and service is degraded.

**Comment by sjwoodr** [comment]
Observe the same here.

**Comment by deniseschannon** [comment]
Just hit this myself while testing out the web example in https://github.com/rancher/rancher/issues/2194

**Comment by cusspvz** [comment]
+1

**Comment by Rucknar** [comment]
+1 on this issue, seen it a number of times now.

**Comment by cusspvz** [comment]
This is high priority for us. :)

**Comment by deniseschannon** [comment]
Easiest way to test this issue:

Steps:
1. Have a reconnecting host.
2. Create a service with a global scale.

Result: Service will be stuck in activating as it picks up the "reconnecting" host to schedule a container. This is not a flapping host so the host was never in "active" state. There is no way to recover (even removing the host, stopping/starting the service) keeps the service in activating. 

Expected Result: Service will not be scheduled to reconnecting host.

**Comment by ibuildthecloud** [comment]
@deniseschannon Hasn't this been address on master now?

**Comment by deniseschannon** [comment]
Verified with build master in the use case that I described above.
