### ISSUE TITLE
server redirect to wrong port for https

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#11738]
**Rancher versions:**
Rancher versions: 2.0 master 2/28

**Steps to Reproduce:**
1. run command ` docker run -d --restart=unless-stopped -p 9090:80 -p 8443:443 rancher/server:master`
2. visit http://127.0.0.1:9090/ in the browser.

**Results:**
It redirects to https://127.0.0.1:9443, which is the wrong port.  The correct rediect url is https://127.0.0.1:8443

**Comment by vincent99** [comment]
There is no way for the server to know what port you mapped 443 to and redirect to it.  

Realistically the redirect is only useful if using the standard ports, nobody is going to seek out a non-standard http port just to be redirected to the https one.
