### ISSUE TITLE
Testing email notifier keeps connecting and disconnecting but never send mail

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11735]
**Rancher versions:** 2.0 master 2/27

**Steps to Reproduce:**
1.  Go to Add Notifier
2.  Create an email notifier and click on Test

**Results:**  Stays in testing and if you look at mail server logs you will see a bunch of connecting/disconnecting hits.  This will continue until I delete the cluster.  Should only connect/disconnect once.  Also it never send the email.

**Comment by zionwu** [comment]
1. stays in testing because when the config is invalid, there is not timeout for dial func. We should set 30s timeout for Dial func. 
2. The email is not sent because it is treated as spam. For now I will just  validate if the config if valid but not sending a email.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/2
Verified fixed
