### ISSUE TITLE
Loadbalancer looses label when edited in UI

### ISSUE THREAD

**Issue by evermind-micw** [rancher/rancher#11739]
**Rancher versions:**
Rancher | v1.6.12
Cattle | v0.183.30
User Interface | v1.6.30
Rancher CLI | v0.6.5
Rancher Compose | v0.12.5

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
1. Create an LB with label "io.rancher.container.requested_ip=10.42.255.1"
- the LB is created with the requested IP
- the API shows that the label exists
2. Click on "upgrade"
- the UI does not show the label anymore
- after saving the changes, the label disappears and the IP is randomly selected

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
