### ISSUE TITLE
key can not be removed from map in norman

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#11740]
**Rancher versions:**
2.0 master 02/28

**Steps to Reproduce:**
In rancher/types, if a field is declared as map[string]string, and we use REST API to edit this field, it can only add new key, but can not remove existing key.
For example, 
logging_types.go:
```
type LoggingCommonSpec struct {
    ...
    OutputTags          map[string]string `json:"outputTags,omitempty"`
        ...
}
```
Use the link https://ip:port/v3/projectlogging to create a new projectLogging and then edit  `outputTags`, existing key can not be removed.

**Comment by kinarashah** [comment]
Seeing similar issue with secret data, https://github.com/rancher/rancher/issues/11607

**Comment by zionwu** [comment]
Verified fix on master 04/24
