### ISSUE TITLE
All AD users are logged in as admin user

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#11742]
rancher server: master at Feb 28

Steps to reproduce:

- Enable AD authentication with admin user (user1)
- Select `Allow any valid Users`
- Log out and try to login with any other authorized user

Results:

the user will be logged in as admin user, and if you navigate to users tab then you will find only admin user there.

**Comment by cjellick** [comment]
Resolved and committed, but not moving to to-test because AD is not fully enabled in the UI

**Comment by deniseschannon** [comment]
AD is now enabled in master again.

**Comment by galal-hussein** [comment]
Rancher version: master at Mar 15

I was able to verify that AD users login with different usernames and not as admin users
