### ISSUE TITLE
Untranslated label for default Workload type in "Deploy Workload" page sometimes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11748]
Rancher server - 2.0 build from master - Feb 28

Steps to reproduce the problem:
Deploy a workload.
Incorrect label for default Workload type in "Deploy Workload" page.

<img width="1036" alt="screen shot 2018-02-28 at 11 01 20 am" src="https://user-images.githubusercontent.com/4266958/36807074-cbdb513a-1c76-11e8-8dfb-535553ed8f5a.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/1
Verified fixed
