### ISSUE TITLE
Failed to add AD users to authorized list

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#11743]
Rancher version: master at Feb 28th

Steps to reproduce:

- Enable AD authentication
- Select `Allow members of Environments, plus Authorized Users and Organizations`
OR
- Select `Restrict access to only Authorized Users and Organizations`
- Try to add any AD user

Results:

the user is not added to the list and i am getting this UI error:
```
Principal not found: undefined
```
No errors reported in the server's logs

**Comment by cjellick** [comment]
Can you please provide the exact value you are inputting for step "Try to add any AD user"?
also the exact set of values you used for setting up AD. I cant try to repro without these details

**Comment by cjellick** [comment]
Resolved and committed, but not moving to to-test because AD is not fully enabled in the UI

**Comment by deniseschannon** [comment]
AD is now available in the UI in master

**Comment by galal-hussein** [comment]
Rancher version: master at March 15th

I was able to verify that i can add AD users to authorization list and login with these users normally
