### ISSUE TITLE
Allow non-local users to set a local username and password

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11747]
**Rancher versions:** 2.0 master 2/28

**Steps to Reproduce:**
1.  Authenticate using github
2.  Log in as a github user
3.  Go to User page and edit the Github user

**Results:**  I can't add a username.  I should be able to add one if one hasn't been set already

**Comment by westlywright** [comment]
Kicking over to @cjellick as this requires some changes/discussion on the backend.

**Comment by cjellick** [comment]
WOuld need to be able to add both username and password. This would allow the user to login with the local creds in addtion to the external auth provider
