### ISSUE TITLE
io.rancher.network.per_host_subnet.subnet ignored and using ip from second host

### ISSUE THREAD

**Issue by kolorafa** [rancher/rancher#11741]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent:1.2.9

**Infrastructure Stack versions:**
healthcheck:
per host subnet:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

Containers: 12                                                                                                                                                                            
 Running: 11                                                                                                                                                                              
 Paused: 0                                                                                                                                                                               
 Stopped: 1                                                                                                                                                                            
Images: 34                                                                                                                                                                                
Server Version: 1.13.1                                                                                                                                                                    
Storage Driver: aufs                                                                                                                                                                        
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 423
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: pending
 NodeID: 3vpb93042z3jxlyjk8gbdqy2k
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 ClusterID: 
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 0
  Heartbeat Tick: 0
  Election Tick: 0
 Dispatcher:
  Heartbeat Period: Less than a second
 CA Configuration:
  Expiry Duration: Less than a second
 Node Address: 172.16.234.178
 Manager Addresses:
  0.0.0.0:2377
  172.16.234.178:2377
  172.16.234.183:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.755 GiB
Name: server01
ID: W57U:QEWR:FSRN:IVLZ:AVVN:AKEP:JMZW:D5KW:FCWM:RTCF:4JZC:JWLS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-116-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle (changed to use Per Host Subnet)

**Steps to Reproduce:**
Added host01 with io.rancher.network.per_host_subnet.subnet=10.41.1.0/24
Added host02 with io.rancher.network.per_host_subnet.subnet=10.41.2.0/24

**Results:**
restarted host02 - all fine
restarted host01 - containers gets IP like 10.41.2.X but should get 10.41.1.X

Removing host01 and readding doesn't fix the problem.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
