### ISSUE TITLE
addremoveservicelinkinput.name (As Name for Service link) should have validChars set

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1174]
build from master - June 11th (afternoon)
Steps:
1.  Create a service with a Service link
2.  For the As Name put in "é space *&)"

results:
Allows you to create

Expected:
As Name should be a valid DNS label which should only allow characters equal to: a-z 0-9.-_

**Comment by deniseschannon** [comment]
Added to #680 to consolidate issues. Same concept.
