### ISSUE TITLE
Alerts don't seem to work on RKE or AKS

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11756]
**Rancher versions:** 2.0 master 2/28

**Steps to Reproduce:**
1.  Setup a Azure (AKS) cluster and an EC2 RKE cluster
2.  Create an alert that will fail and should fire

**Results:**  Alert never fires

**Comment by zionwu** [comment]
Currently, we use NodePort Service for alertmanager and make api call to it. 
1. RKE on EC2 is using internal ip for the node, so the api call fails.
2. NodePort Service also does not work in AKS.

We should use clusterdialer API instead of the NodePort service approach.

**Comment by tfiduccia** [comment]
Version - master 2.0 3/26
Verified fixed
