### ISSUE TITLE
UI - Certificates that are scoped to namespace are not being listed in "Add Ingress" view

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11753]
Rancher versions: 2.0 Build from master
Steps to Reproduce:
From project view:
 Create Certificate -"test1" with Available to all namespaces in this project.
 Create Certificate -"test2" with "Available to a single namespace" - Default.

From Load Balancing tab , launch "Add Ingress" page.

In SSL/TLS certificates section:
Certificates drop down shows only "test1". namespace scoped certificate is not displayed.
Expected Behavior:
Namespace scoped certificate should also be  displayed.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/1
Verified fixed
