### ISSUE TITLE
Project Name should list allowable characters instead of telling me what I got wrong

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1175]
build from master - June 11th (afternoon)
Steps:
1.  Create a project with a name that includes a space and a _

Results:
The error message tells me one character at a time which one is invalid

Expected:
For consistency and actual ease of use, we should give them the list of allowable characters which should be a valid DNS label equal to a-z 0-9 . - _

**Comment by vincent99** [comment]
How about I tell you all the bad characters at once...

![image](https://cloud.githubusercontent.com/assets/753917/13718306/058fe24a-e7a6-11e5-9fcb-d7a4b9d3fa6e.png)

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
