### ISSUE TITLE
Shouldn't allow spaces in username

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11754]
**Rancher versions:** 2.0 master 2/28

**Steps to Reproduce:**
1.  Create a user and have their username be "A B"

**Results:**  Allows spaces in username

**Comment by cjellick** [comment]
@vincent99 can you give your two cents on this?
I believe you mentioned previously that we should not restrict this field to the typical basic ascii because of internationalization.
There is no technical reason on the backend to restrict " ", but I'll do it if you want.

**Comment by vincent99** [comment]
I don't see any reason to restrict the charset of the username, unless they're indexed somewhere (which would mean a-z lowercase 0-9 and hyphen only)...

**Comment by cjellick** [comment]
ok, will go with that. Assigning back over to @tfiduccia for QA consideration
