### ISSUE TITLE
Expose dns name for port in the UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11761]
For every workload port created from the UI, we create a corresponding k8s service which name = workload.name by default. The service gets created per port type - NodePort, LoadBalancer or clusterIP. The bug is - if user creates multiple ports of diff type, one of the services will fail to create due to name conflict. We should let user specify dns name for the port he creates; and only if not specified, it will get defaulted to workload.name. API already has support for it.

**Comment by vincent99** [comment]
Maybe we can just automatically create random names for each port and not show it, like catalog app namespaces.

**Comment by alena1108** [comment]
@vincent99 can we create random names on per:

* type, not per individual ports (we create one service per type, with multiple ports)
* only for LB/NodePort ports. I think clusterIP port should have the name = workload.name, so it can be easily resolvable internally.

Also when you say `random generation` - do you think it should be done in the UI, or API?

**Comment by alena1108** [comment]
@loganhz I'm going to cover it on the API side

**Comment by sangeethah** [comment]
@alena1108 Tested with latest build from master.

Creates all types of port mapping on a single workload. All of them get created successfully and all of them are functional.


<img width="1155" alt="screen shot 2018-04-17 at 6 01 49 pm" src="https://user-images.githubusercontent.com/4266958/38906130-8c118984-4269-11e8-8b98-82ddb664d3fc.png">



<img width="1170" alt="screen shot 2018-04-17 at 5 59 38 pm" src="https://user-images.githubusercontent.com/4266958/38906074-4747c584-4269-11e8-8360-0b21b765526a.png">

**Comment by alena1108** [comment]
@sangeethah that should be sufficient enough. Update/remove/recreate can be tested as an extra
