### ISSUE TITLE
Project Name doesn't allow _ or .

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1176]
build from master - June 11th (afternoon)
Steps:
1.  Create a project and name it Project_1.1

Results:
Won't let me create, because it thinks the underscore and period are unacceptable.

Expected:
They should be allowed as they are a valid DNS label

**Comment by will-chan** [comment]
I assume Tani meant Stacks as it was called Projects before.

**Comment by vincent99** [comment]
The names of both stack and project are used in hostnames so `_` is not really valid, and they are expected to be a single label so no `.`.
