### ISSUE TITLE
Ingress controller is not able to reach containers  cross host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11777]
Rancher versions: build from master

Steps to reproduce the problem:
1. Cluster with  2 DO hosts.
2. Create a workload with scale 3.
3. Create Ingress with target as the above workload.

4. When accessing ingress url from host1 , traffic gets directed to only 2 pods which are present in host1.
5. When accessing  ingress url from host2 , traffic gets directed to only 1 pod (which is different from the 2 pods from step 4)  which are present in host2.

**Comment by galal-hussein** [comment]
I checked cross host communication and it wasn't broken, however pinging pods from ingress controller doesn't work, after deleting the default network policy i can no longer see the problem

**Comment by leodotcloud** [comment]
Root cause: The underlying k8s network policy has a default deny when a policy is configured and everything that's allowed needs to be whitelisted. Currently only pods from the same project are whitelisted. Hence any other traffic is denied.

**Comment by leodotcloud** [comment]
Once I have the fix, will make a PR against: https://github.com/rancher/rancher/issues/11726

**Comment by sangeethah** [comment]
Rancher server version - 2.0 build from master

Setup - Cluster with 3 DO nodes
Steps to reproduce the problem:
Create a workload of type daemonset.
Create an Ingress with rule pointing to this workload.
Ingress is functional from all the 3 node ip address and is able to reach all 3 targets.
