### ISSUE TITLE
Repeated errors relating to podSecurityPolicy.extensions not found.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11773]
Rancher server version - Build from master - Feb 28

Steps to reproduce the problem:
Create  a pod security policy - p1.
Create a Digital Ocean cluster with default pod security policy set to p1.

Server logs show the following errors repeatedly.

```
E0301 00:57:29.079529       1 generic_controller.go:200] ClusterController cluster-wjcdt [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "mytest1" not found
E0301 00:57:44.111030       1 generic_controller.go:200] ClusterController cluster-wjcdt [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "mytest1" not found
E0301 00:58:14.514672       1 generic_controller.go:200] ClusterController cluster-wjcdt [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "mytest1" not found
E0301 00:58:44.125705       1 generic_controller.go:200] ClusterController cluster-wjcdt [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "mytest1" not found
```

**Comment by deniseschannon** [comment]
Now that PSPs can be enabled in a DO cluster, does this error still exist?

**Comment by sangeethah** [comment]
Tested with  build from Mar 5.

Create a PSP - test1.
I had enabled PSP and assigned a default PSP to "test"

Repeated errors seen in the logs:

```
E0305 21:40:29.247156       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:40:29.248475       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:40:29.249001       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:42:47.856237       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:42:47.861286       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:42:47.864785       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:42:47.865253 

```
E0305 21:40:29.247156       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:40:29.248475       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:40:29.249001       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:42:47.856237       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:42:47.861286       1 generic_controller.go:200] ClusterController cluster-d88vq [ClusterSyncHandler] failed with : podSecurityPolicy.extensions "test1" not found
E0305 21:42:47.864785 

```

**Comment by sangeethah** [comment]
Tested with latest build from master.

This error is not seen in logs.
