### ISSUE TITLE
Pod/Node event doesn't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11771]
**Rancher versions:** 2.0 master 2/28

**Steps to Reproduce:**
1.  Create a cluster
2.  Create a notifier
3.  Create a alert that fires on Pod event
4.  Create a workload with pod = 10

**Results:**  No alert.  Same thing with Node event.  I can't seem to get the alert to fire.  I wonder if it's because I'm not specifying a specific node, so nothing gets put in the nodetarget on POST

**Comment by zionwu** [comment]
Checked with Darren, we don't record any cluster events right now because of scaling issues. I will watch event in cluster side instead of clusterevent in management side.

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/36876785-b4d39534-1df1-11e8-92d3-2699a0b47903.png)

![image](https://user-images.githubusercontent.com/1213386/36876788-ba67d582-1df1-11e8-82b3-58b43be833e6.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/2
Verified fixed
