### ISSUE TITLE
Change Rancher Server path to a custom path

### ISSUE THREAD

**Issue by L30Bola** [rancher/rancher#11775]
I'd like to serve my Rancher web interface could be served on a custom path, like example.com/rancher, instead of serving it on example.com:8080/.

I've tried setting up a reverse proxy with Apache, using some mod_rewrite rules and some mod_substitute rules (not necessarily together), but failed.

**Comment by vincent99** [comment]
This is not currently possible, but easy to implement because the UI is 100% static files, and is not likely to be added.  Sharing unrelated applications on the same origin is a bad idea for security because you are likely leaking cookies one way or the other.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
