### ISSUE TITLE
NodePort PublicEndpoints are not accessible from outside the cluster

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#11776]
**Rancher versions:** 2.0 master 28/02

**Steps to Reproduce:**
- Create a NodePort workload

**Results:**
A service is created with a random nodeport. Port is open on hosts, but inaccessible externally. It's however accessible from inside the host. This is tested on DO hosts with no external firewall.

**Comment by alena1108** [comment]
Well, given that the service was programmed correctly on k8s, seems like rancher job is done properly. So might be some bug  on rke?

**Comment by moelsayed** [comment]
When creating a cluster with `flannel` network plugin, the NodePort workload works as expected. The issue seems to be related to network policies.

**Comment by moelsayed** [comment]
Possible root cause: https://github.com/rancher/rancher/issues/11777

**Comment by leodotcloud** [comment]
Root cause: The underlying k8s network policy has a default deny when a policy is configured and everything that's allowed needs to be whitelisted. Currently only pods from the same project are whitelisted. Hence any other traffic is denied.

**Comment by leodotcloud** [comment]
Once I have the fix, will make a PR against: https://github.com/rancher/rancher/issues/11726

**Comment by moelsayed** [comment]
Tested using master 14/03. 
I was able to create a cluster on DO with default network plugin. I created a NodePort workload and was able to access it on all cluster nodes.
