### ISSUE TITLE
Warning showing up for Normal event alert

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11778]
**Rancher versions:** 2.0 master 2/28

**Steps to Reproduce:**
1.  Create a Normal Event alert on node

**Results:**  Warning showing up in dev tools
![image](https://user-images.githubusercontent.com/11514927/36820901-8461c4f6-1cad-11e8-8164-fbd0246bf30a.png)

**Comment by zionwu** [comment]
This warning will not affect the functionality.  It is due to that targetEvent has a field named `type`. I will change this field name latter.

**Comment by vimniky** [comment]
The `targetWorkload` also has a `type` field, which also needs to be changed even though it doesn't cause a warning by accident.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
