### ISSUE TITLE
Project level alerts are not working

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11782]
**Rancher versions:** 2.0 master 2/28

**Steps to Reproduce:**
1.  Create a notifier
2.  Create a project level against a workload that has a bad image associated

**Results:**  Alert never fires

**Comment by zionwu** [comment]
The format of id of the resource is `deployment:cattle-alerting:alertmanager"`, which is different from  Backend's assumption. Backend will change to follow the actual format.

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/36841110-468d5980-1d82-11e8-8f08-27059ba98a4c.png)

![image](https://user-images.githubusercontent.com/1213386/36841115-4aa206a6-1d82-11e8-8a07-de03da471dd3.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/2
Verified fixed
