### ISSUE TITLE
publish image step cannot be saved correctly

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#11788]
**Rancher versions:** master 3/1

**Steps to Reproduce:**
1. Dockerfile Path is set but gave validation notification `"Dockerfile Path" is required!`
![image](https://user-images.githubusercontent.com/5697937/36838443-20d4f764-1d7a-11e8-8b51-ad88af43d655.png)
2.
Input as the following:
![image](https://user-images.githubusercontent.com/5697937/36838521-5c9177c8-1d7a-11e8-89a2-ff82c71464dd.png)
click `cancel` and edit this step again, got:
![image](https://user-images.githubusercontent.com/5697937/36838614-9d6d9e5c-1d7a-11e8-838c-987c069559af.png)

**Comment by cloudnautique** [comment]
I saw the save feature working in latest UI update.

**Comment by deniseschannon** [comment]
since @cloudnautique says it's working, i'm going to close this.
