### ISSUE TITLE
Add ability to set interface for Flannel network provider for RKE 

### ISSUE THREAD

**Issue by terrada3** [rancher/rancher#11780]
**Rancher versions:**
rancher/server:v2.0.0-alpha16
rancher/agent:rancher/agent:v2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
 
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Our cloud(IIJ GIO P2)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Open "Clusters" -> Click "Add Cluster" button -> Click "Create a Cluster" -> Open "Cusomize" area.
 
**Results:**
![image](https://user-images.githubusercontent.com/4397382/36825873-16b11484-1d4d-11e8-9c60-4e099046206c.png)

Text fields for options of network plugins are not implemented. 
On RKE(CLI), we can specify detail setting of network plugin like below.

- Flannel
  - flannel_image: Flannel daemon Docker image
  - flannel_cni_image: Flannel CNI binary installer Docker image
  - flannel_iface: Interface to use for inter-host communication
......

We are looking forward to GA release.
Thanks.

**Comment by vincent99** [comment]
Image options are intentionally not shown. The registry option below changes the source of all the images and in future releases the version of all the components will be a separate single option for k8s version.  If you want to customize 30 images separately you will need to run rke manually.

The interface should be added though.

**Comment by deniseschannon** [comment]
@moelsayed I think we'll need to expose the interface for flannel in Rancher to be able to set anything related to networking for cross host communication. 

We should see if there are other fields like that for other networking types that should be able to be set.

**Comment by alena1108** [comment]
After discussing it with @vincent99 and @deniseschannon, here is the resolution:

1) Introduce extra strongly typed fields to cluster:

* AwsCloudProvider
* AzureCloudProvider
* CalicoNetworkProvider
* FlannelNetworkProvider
* CanalNetworkProvider

each type will have a set of non-generic fields

2) These fields will be set by the UI. Somewhere on RKE side, we can extract data from these fields, and place them under corresponding generic fields - networkProvider, cloudProvider. This way we don't have to change rke internals + don't have to change rke standalone config representation.

**Comment by alena1108** [comment]
@vincent99 backend/api is in, so UI can start integrating.

**Comment by hameno** [comment]
We also need to be able to set the network cidr to be able to use a different network than 10.42.x.x since we already use that space internally...
(using canal)

**Comment by galal-hussein** [comment]
@loganhz you added flannel network provider but you didn't add Iface: https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/rke_types.go#L407

**Comment by loganhz** [comment]
@galal-hussein I passed {iface: “eth1”}. The whole payload is https://user-images.githubusercontent.com/21168270/38543647-b0a9200a-3cd7-11e8-834e-ba7234a970ed.png

**Comment by galal-hussein** [comment]
@loganhz i think its a problem in types, i didn't add the yaml or json annotation, i will add a fix for that

**Comment by tfiduccia** [comment]
@galal-hussein - the support for Flannel is in and iface is being posted and is being saved in API.  But I'm not if there is other implementation that Alena was talking about?

**Comment by deniseschannon** [comment]
based on @tfiduccia comment, I believe the ability to set the interface for flannel networking is in and working as expected.

**Comment by micw** [comment]
Seems not to work. I created a cluster with flannel_iface set. It's populated to the API:
"network": {
"options": {
"flannelBackendType": "vxlan",
"flannelIface": "wg0"
},
"plugin": "flannel",
"type": "/v3/schemas/networkConfig"
},

But the flannel-containers do use the default interface (eth0).

Probably related to https://github.com/rancher/rancher/issues/15133#issuecomment-444190598

**Comment by micw** [comment]
Actually it works this way on rancher: https://github.com/rancher/rancher/issues/14721#issuecomment-417913067 - this should probably be documented somewhere
