### ISSUE TITLE
Certificate error causes silent haproxy reload failures

### ISSUE THREAD

**Issue by dannykopping** [rancher/rancher#11790]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent:

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.7.8
scheduler: rancher/scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.09.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ uname -r
4.9.0-5-amd64

$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Upload a certificate with mismatching public/private keys
- Modify haproxy rules in loadbalancer
- Save loadbalancer changes

**Results:**
- Haproxy fails to restart, no visual feedback or alerts
- Details only visible in loadbalancer logs after service instance restart

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
