### ISSUE TITLE
[v2.0.0-alpha16] unable to read client-cert ( minikube )

### ISSUE THREAD

**Issue by lakano** [rancher/rancher#11798]
**Rancher versions:**
rancher/server: 2.0.0-alpha16
rancher/agent: 

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.8.0 / minikube v0.25

**Docker version: (`docker version`,`docker info` preferred)** 17.12.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** macOS High Sierra

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Trying Rancher 2 with minikube

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
minikube start 
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview

**Results:**
Rancher 2 ask the profile, I put the ~/.kube/config ( after renamed to .yml to be permit to select it )
The file is correctly read, but the state stay to "provisioning" with this big red warning:

  | invalid configuration: [unable to read  client-cert /Users/guillaume/.minikube/client.crt for golf due to open  /Users/guillaume/.minikube/client.crt: no such file or directory, unable  to read client-key /Users/guillaume/.minikube/client.key for golf due  to open /Users/guillaume/.minikube/client.key: no such file or  directory, unable to read certificate-authority  /Users/guillaume/.minikube/ca.crt for golf due to open  /Users/guillaume/.minikube/ca.crt: no such file or directory]

As the config file point to external cert files, I suppose Rancher can't have access to theses files. So how to fix that please?

**Comment by vincent99** [comment]
Yes the config file needs to be self-contained and include the keys.  The "give us your kubeconfig file" mode is going to be gone in the next preview because of situations like this (and Google GKE configs execute a shell command to get the keys), so you will run a kubectl command we give you instead.

**Comment by lakano** [comment]
Thanks @vincent99 !
So, currently, is there a temporary solution to include my keys inside the config.yml file, or may be you could give me the kubectl command to use please?

**Comment by vincent99** [comment]
cluster -> `certificate-authority-data:` base64 encoded contents of ca.crt
user -> `client-certificate-data:` base64 encoded contents of client.crt
user -> `client-key-data:` base64-encoded contents of client.key

**Comment by lakano** [comment]
Thanks!

**Comment by lakano** [comment]
A simple script to help to translate easily the ~/kube/config to the base64 data format:
```
#!/bin/bash
MKPATH="$HOME/.minikube/"
MK=$(echo $MKPATH | sed 's/\//\\\//g')
CA=$(base64 -w 0 "${MKPATH}ca.crt" | sed 's/\//\\\//g')
CRT=$(base64 -w 0 "${MKPATH}client.crt" | sed 's/\//\\\//g')
KEY=$(base64 -w 0 "${MKPATH}client.key" | sed 's/\//\\\//g')
cat ~/.kube/config | sed "s/: ${MK}ca\.crt/-data: ${CA}/g" | sed "s/: ${MK}client\.crt/-data: ${CRT}/g" | sed "s/: ${MK}client\.key/-data: ${KEY}/g"

```

**Comment by shamsher31** [comment]
This worked for me. 

Run the following command
```cli
kubectl config view --flatten
```
Copy the output and replace it with `~/.kube/config`. (Considering you have only minikube cluster)
