### ISSUE TITLE
workloads showing up in Service Discover list

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11805]
**Rancher versions:**  2.0 master 3/1

**Steps to Reproduce:**
1.  Create a workload
2. Wait for it to become active
3.  Go to Service Discovery

**Results:**  Workloads showing up on Service Discovery page
![image](https://user-images.githubusercontent.com/11514927/36866003-573a848a-1d4e-11e8-8087-f6b74f5b67d5.png)

**Comment by loganhz** [comment]
The type of them is `dnsRecord` and `kubectl get svc` can list them. 
I guess it is not an issue ? @vincent99

**Comment by vincent99** [comment]
Workloads create a service which has a DNS record.  They should maybe not be editable/removable, but they should be there.. this page shows you all the names which are resolvable from within that namespace.
