### ISSUE TITLE
Zookeeper logging endpoint is not set correctly

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#11818]
**Rancher versions:** 2.0 master 1/03

**Steps to Reproduce:**
- Try to create a logging target for Kafka
- Choose zookeeper endpoint type.
- Configure the endpoint and Save.
**Results:**
The UI shows the error:
```
Validation failed in API: one of the target must set
```

**Comment by aiwantaozi** [comment]
@moelsayed Hi, this part used to have bug, the fix just merge several minutes ago. The latest one should fixed. thank you

**Comment by zionwu** [comment]
https://github.com/rancher/rancher/issues/11818

**Comment by moelsayed** [comment]
Confirmed fix with master 453bc7731.
