### ISSUE TITLE
Kafka logging target is not working

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#11820]
**Rancher versions:** 2.0 master 1/03

**Steps to Reproduce:**
- Deploy kafka based on this [guide](https://devops.profitbricks.com/tutorials/install-and-configure-apache-kafka-on-ubuntu-1604-1/)
- Chose broker endpoint
- Add one endpoint
- Add topic "rancher-server"
**Results:**
- List messages on the kafka server under this topic. No log messages are sent.

**Comment by aiwantaozi** [comment]
Hi @moelsayed ,  it have some problem with the endpoint type zookeeper, but the broker one worked. And I just submit a PR to fix the zookeeper endpoint not work problem. Thank you for you help.

If the broker for you also not work, double check whether you change this with the kafka, feel free to talk with me.
have you update the server config file /opt/Kafka/kafka_2.10-0.10.0.1/config/server.properties,
if you want you access the kafka from the outside network, need to update the config:
```
listeners=PLAINTEXT://ip or domain:9092
advertised.listeners=PLAINTEXT://ip or domain:9092
zookeeper.connect=ip or domain:2181
```
And use the command to test whether it work expected.
```
sudo /opt/Kafka/kafka_2.10-0.10.0.1/bin/kafka-console-producer.sh --broker-list ip or domain:9092 --topic testing

sudo /opt/Kafka/kafka_2.10-0.10.0.1/bin/kafka-console-consumer.sh --zookeeper ip or domain:2181 --topic testing --from-beginning
```

**Comment by moelsayed** [comment]
@aiwantaozi thank you for the configuration.

Tested with master 05/03. Both Zookeeper and kafka broker end points are working.
