### ISSUE TITLE
Health check should destroy unhealthy instances after a configurable time. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1182]
Server version - V0.23.0-rc1

Steps to reproduce the problem:

Create a service with health check enabled .
Start the service.

Make one of the containers unhealthy (I trigger this by removing the health check uri file from the container) .

As soon as the container is marked "unhealthy", we delete the  container immediately.

Ideally there should be a configurable wait time that can be provided for the service , after which is when a unhealthy container gets deleted.

**Comment by lucacri** [comment]
+1 on this, it would be very helpful to be able to delete a container in case of failed health check

**Comment by alena1108** [comment]
@lucacri in the next release of rancher, we are going to add support for health check actions. In addition to default one - recreate unhealthy container - there will be "none" action. If this action is chosen, we are going to do nothing but just reporting the container as unhealthy. So the user can inspect the container to see why the failure happened, remove it manually, and its removal will trigger container re-create.

Here is more details:

https://github.com/rancher/rancher/issues/3076

Hope that would be helpful to support your use case.

**Comment by lucacri** [comment]
Thank you Alena! That should work :-)

**Comment by alena1108** [comment]
Closing this issue as we have 3 health check strategies now that can support various use cases:

* recreate on failure. The old container gets removed, and the new one gets recreated right away
* recreate on quorum. Only when quorum of healthy instances is reached, recreate the unhealthy containers
* noop. Just report the health check failure, and let user deal with it manually (in case some debugging is needed before removing the unhealthy ones)
