### ISSUE TITLE
Authorized Github user can't create a node pool

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#11823]
Rancher server: master at Mar 1st

Steps To reproduce:

- i enabled GH authentication
- selected "Allow any valid user"
- logged in with a github user (that is not the admin)
- tried to create a new DO cluster

I am getting the following error message:
```
nodepools.management.cattle.io is forbidden: User "user-xgvf9" cannot create nodepools.management.cattle.io in the namespace "cluster-sfcl5"
```

**Comment by cjellick** [comment]
Fixed (I think)

**Comment by galal-hussein** [comment]
Rancher version: master at March 2nd

I was able to create a DO cluster with a logged in github user normally, i am not getting the error anymore
