### ISSUE TITLE
Can't edit ingress load balancer

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11837]
**Rancher versions:** 2.0 master 3/1

**Steps to Reproduce:**
1.  Create an ingress load balancer
2.  Edit and add a description

**Results:**  Error - "the server does not allow this method on the requested resource"
![image](https://user-images.githubusercontent.com/11514927/36876027-27cfde6c-1d70-11e8-8a75-844526128149.png)

**Comment by sangeethah** [comment]
Tested with master build from Mar2.

Able to edit ingress rules successfully.
