### ISSUE TITLE
[Windows] Windows host in rancher/server:v1.6-development failed to add

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#11846]
**Rancher versions:**
rancher/server:  v1.6-development
rancher/agent:  rancher/agent-windows:v0.2.0-rc5

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 2016
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows

**Results:**
Windows host in rancher/server:v1.6-development failed to add
Error message:
```
PS C:\Users\Administrator> $obj |& "C:\Program Files\rancher\startup.ps1"
VERBOSE: Loading module from path 'C:\program files\rancher\rancher-tools.psm1'.
VERBOSE: Importing function 'Add-DebugContent'.
VERBOSE: Importing function 'Add-LogContent'.
VERBOSE: Importing function 'Get-DownloadList'.
VERBOSE: Importing function 'Get-DownloadListByTarget'.
VERBOSE: Importing function 'Get-RancherBasicAuth'.
VERBOSE: Importing function 'Get-RancherBinary'.
VERBOSE: Importing function 'Get-RancherComponentList'.
VERBOSE: Importing function 'Get-RancherLabel'.
VERBOSE: Importing function 'Register-Node'.
VERBOSE: Importing function 'Start-RancherComponent'.
VERBOSE: Importing function 'Stop-RancherComponent'.
VERBOSE: Importing function 'Test-RancherComponent'.
VERBOSE: Importing function 'Test-RancherNetwork'.
VERBOSE: Importing function 'Update-Binaries'.
{"id":"9b733154-616b-4310-8f83-4ff000bde32a","type":"error","links":{},"actions":{},"status":404,"code":"Not Found","mes
sage":"Not Found","detail":null,"baseType":"error"}
Get error while running startup.ps1
```

**Comment by deniseschannon** [comment]
@kingsd041 Does this work today in 1.6.15?

**Comment by kingsd041** [comment]
@deniseschannon Hosts can be added in v1.6.15 but still fail in v1.6-development

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
