### ISSUE TITLE
Workload UI doesn't show existing `default` namespace in the namespace dropdown menu

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#11842]
**Rancher versions:** 2.0 master 01/30

When you try to create a new workload on a fresh setup, the namespace dropdown menu is empty. 

The `default` namespace is only shown if you create a new namespace, deploy workload to it, and try to deploy a new workload.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/4
I can't reproduce this in the newest build.  Can you recheck please

**Comment by moelsayed** [comment]
The issue happens when creating workloads in a non-default Project, which doesn't have a default namespace, so this is expected. It was an incorrect report. Closing the issue now.
