### ISSUE TITLE
Cannot add users to a project or cluster as they are not listed in the users list

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11840]
**Rancher versions:**
rancher/server: Master from Mar 1

**Steps to Reproduce:**
1.  Create a cluster C1 and a standard user "usertest". Ensure "usertest" is in the list of users at the global level
<img width="807" alt="screen shot 2018-03-01 at 4 27 39 pm" src="https://user-images.githubusercontent.com/18536626/36877124-7eb1da30-1d6d-11e8-9bbe-a36e26912e03.png">

2.  Create project P1 and add user1 to this project or do edit on the default project to add a user
"usertest" is not listed in the project and hence cannot add users to a project

<img width="683" alt="screen shot 2018-03-01 at 4 28 20 pm" src="https://user-images.githubusercontent.com/18536626/36877151-95e6e0f6-1d6d-11e8-9d33-643b1671fe09.png">

**Comment by tfiduccia** [comment]
The same thing is happening in Clusters.  It's the same control.

**Comment by tfiduccia** [comment]
Removed the drop-down arrow so the Name field is no longer a drop-down.  You have to type to see users.
