### ISSUE TITLE
Network Agent Containers do not have any labels

### ISSUE THREAD

**Issue by usmanismail** [rancher/rancher#1185]
I seem to remember network agent containers had labels to indicate they were system containers. In the latest build they do not seem to have any labels at all.

**Comment by vincent99** [comment]
Are you sure you're not confused with the labels on the host agent, `rancher/agent`?  As opposed to `rancher/agent-instance`, which would be the network agents.  The host agent has a label on it so that native-docker knows not to import them.

**Comment by usmanismail** [comment]
I mean agent-instance, See screen shot below. 
The UI does not show any labels for this container nor does the API.

![screen shot 2015-06-12 at 2 16 30 pm](https://cloud.githubusercontent.com/assets/204682/8136908/af1c5304-110d-11e5-82bf-064d90f15b83.png)

**Comment by deniseschannon** [comment]
My understand is that we've never had any labels on the network agent container. Other containers that are started might have labels of kind "system", but we've never had them on the network agent/LB agents. @vincent99 correct me if I'm wrong.

**Comment by vincent99** [comment]
That's correct AFAIK. Containers do have a field `systemContainer` describing what kind they are which is set for lb/network/etc agents.  That pre-dates labels though, and it still works.. the UI uses that to show e.g. network agents as gray text.

**Comment by usmanismail** [comment]
On version v0.21.5-rc1 there was definitely a label ```"io.rancher.container.system": "LoadBalancerAgent"``` as I remember integrating it for my [article](http://rancher.com/implementing-service-monitoring-in-rancher-with-prometheus/) . Its not a big deal if they are gone but it was one of @sheng-liang  requirements to be able to differentiate load/metrics generated by system containers vs user launched containers. This is more difficult to do without a system label.

**Comment by deniseschannon** [comment]
I see the confusion. The labels on the container are still there if you do a `docker inspect`, but they do not show up in the UI. I don't believe the labels have ever showed up in the UI for network agent/lb agent.

**Comment by usmanismail** [comment]
I can check labels on the native container using docker inspect later tonight but the system label is missing in the API for containers/[ID] too which normally has everything you would find in inspect. I am fairly certain that I saw it in the API earlier but I may be wrong about that.

**Comment by vincent99** [comment]
Sounds like the API only shows labels on the container, while `docker inspect` also includes labels that are on the image.  Seems like we should pull those into the API too.  @cjellick @ibuildthecloud ?

**Comment by cjellick** [comment]
@usmanismail @vincent99 This is a bit confusing, but the labels are available on the container via the 'labels' link on the container.

Currently, the labels attribute contains the labels that the user specified when the container was created. The labels link contains all labels that were reported on the docker inspect. Here's sample output from my local setup:

```
curl http://localhost:8080/v1/projects/1a5/containers/1i2/instancelabels
...
{
"type": "collection",
"resourceType": "label",
"links": {
"self": "…/v1/projects/1a5/containers/1i2/instancelabels",
},
"createTypes": { },
"actions": { },
"data": [ 3 items
{
"id": "1l1",
"type": "label",
"links": {
"self": "…/v1/projects/1a5/labels/1l1",
"account": "…/v1/projects/1a5/labels/1l1/account",
"hosts": "…/v1/projects/1a5/labels/1l1/hosts",
"instances": "…/v1/projects/1a5/labels/1l1/instances",
},
"actions": {
"remove": "…/v1/projects/1a5/labels/1l1/?action=remove",
},
"name": null,
"state": "created",
"accountId": "1a5",
"created": "2015-06-15T16:27:01Z",
"createdTS": 1434385621000,
"description": null,
"key": "io.rancher.container.system",
"kind": "label",
"removed": null,
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"uuid": "6f5aa9df-9af8-4a5d-b1cd-5008773695a4",
"value": "NetworkAgent",
},
...
}
```


@vincent99 @ibuildthecloud that behavior is by design, but is it the right design? Or should we override the labels attribute with everything that was reported in the inspect (in addition to creating the label resources that are available through the link).

@usmanismail is having access to the labels via the link sufficient for your short term needs?

**Comment by usmanismail** [comment]
Should be fine. Thx

**Comment by ibuildthecloud** [comment]
@cjellick.  We should keep the two in sync.  I think this is a bug.

**Comment by vincent99** [comment]
@cjellick I'm not sure why labels need a collection link and their own resource when they're embedded in the body.  I could see if there was additional metadata like where that label came from or something but as-is they seem redundant.

**Comment by cjellick** [comment]
Fixed. network agents now have labels in UI

**Comment by sangeethah** [comment]
With rancher server version - v1.2.0-pre3 , UI displays all the labels for Network Agent container:

<img width="1464" alt="screen shot 2016-10-03 at 4 36 05 pm" src="https://cloud.githubusercontent.com/assets/4266958/19057811/87b63a34-8987-11e6-94a9-26c99c8fb8fd.png">
