### ISSUE TITLE
Resource Status in Kubernetes UI shows incorrect information

### ISSUE THREAD

**Issue by tboemker-bkfs** [rancher/rancher#11858]
**Rancher versions:**
rancher/server: 1.6.12 
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: not used
network-services:
scheduler:
kubernetes (if applicable): k8s:v1.8.3-rancher3

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6-cs8
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   880bc7e
 Built:        Wed Feb  8 14:37:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6-cs8
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   880bc7e
 Built:        Wed Feb  8 14:37:51 2017
 OS/Arch:      linux/amd64

Containers: 45
 Running: 41
 Paused: 0
 Stopped: 4
Images: 106
Server Version: 1.12.6-cs8
Storage Driver: devicemapper
 Pool Name: docker-253:2-67108928-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 26.82 GB
 Data Space Total: 107.4 GB
 Data Space Available: 79.99 GB
 Metadata Space Used: 36.46 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.111 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 13.7 GiB
Name: app1-dev450.elxdc.com
ID: M2FX:UIWK:R6PH:2VUL:F427:4IM7:TPQI:DM7T:HIGE:NIRE:DI2L:FJIM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 com.elynx.vlan=app
Cluster Store: consul://localhost:8500
Cluster Advertise: 10.86.250.10:2376
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

uname -r:
3.10.0-693.17.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single-node rancher with 8 workers

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Run more than 15 pods.

**Results:**
The Resource Status statistics and pie report only the first 15 pods. If there were more pods and some of them had errors, statistics showing 15 running and none with errors would be very misleading!
![snip1](https://user-images.githubusercontent.com/26487373/36900135-0ee8c262-1df0-11e8-97a9-54828e5df20b.png)
![snip2](https://user-images.githubusercontent.com/26487373/36900136-12355fca-1df0-11e8-909a-79e995f069d6.png)

**Comment by superseb** [comment]
This was an upstream issue in kubernetes dashboard and fixed in v1.8 and higher. (https://github.com/kubernetes/dashboard/pull/2598)

This is included in newer versions of Rancher, or you can manually update the dashboard but on Rancher versions older than v1.6.13 it will be reset by addons-starter when it's restarted due to https://github.com/rancher/rancher/issues/10045
