### ISSUE TITLE
Still shows a specfic branch when a pipeline is set to run for all branches

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#11854]
**Rancher versions:** master 3/2

**Steps to Reproduce:**
1. save a pipeline with `only branch:master`
2. edit the pipeline and change to `all branches`, click save
**Results:**
I can still see a `master` in the pipeline info
![image](https://user-images.githubusercontent.com/5697937/36889781-700ef584-1e36-11e8-8782-26766edbd3f5.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/2
Verified fixed - all three options are showing properly
