### ISSUE TITLE
not able to pass character "-" for spec port range in docker compose yml

### ISSUE THREAD

**Issue by PpAaLlMmEeRr** [rancher/rancher#11857]
Rancher Version:
v1.6.14
Docker Version:
Docker version 17.12.0-ce, build c97c6d6
OS and where are the hosts located? (cloud, bare metal, etc):
centos7

Steps to Reproduce:
from rancher web ui, add a stack process,  try to use docker-compose.yml to make stack failed.
validation failed by line : - "6000-6020:26080"

Results:
not able to create stack by below yml content.
yml content: 
version: '2'
services:
  hub:
    image: elgalu/selenium
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false
      - TZ=Asia/Shanghai
  chromeDebug:
    image: elgalu/selenium
    depends_on:
      - hub
    ports:
      # noVNC: See what's going on by hitting http://0.0.0.0:6080 in your browser
      #  port range to expose, assign 20 port for debug node
      - "6000-6020:26080"
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{`{{CONTAINER_IP}}`}}
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - MAX_INSTANCES=1
      - MAX_SESSIONS=1
      - VIDEO=false
      - GRID=false
      - CHROME=true
      - FIREFOX=false
      - TZ=Asia/Shanghai

**Comment by deniseschannon** [comment]
Port Ranges are not supported in Rancher: https://github.com/rancher/rancher/issues/1673
