### ISSUE TITLE
Display only supported docker versions in the UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11864]
**Rancher versions:**
rancher/server: Master from March 1st 

**Steps to Reproduce:**
1. Create a node template and choose engine options and click on Docker install URL
The dropdown displays many docker versions which are not supported

<img width="1013" alt="screen shot 2018-03-02 at 9 49 28 am" src="https://user-images.githubusercontent.com/18536626/36913604-5a498462-1dff-11e8-849e-33db29a58a2f.png">

Only the docker versions that are supported should be displayed in the UI

**Comment by loganhz** [comment]
@soumyalj May I have the list of docker versions which are not supported?

**Comment by deniseschannon** [comment]
@loganhz Supported Docker Versions are 
```* v1.12.x
* v1.13.x
* v17.03.x```

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified fixed
