### ISSUE TITLE
NodePort workload gets an incorrect IP assigned in the UI

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#11863]
**Rancher versions:** master 02/03

**Steps to Reproduce:**
- Create one DO cluster with multiple nodes
- Create a second DO cluster
- On the second cluster, create a workload with NodePort

**Results:**
In the UI, the workload address provided sometimes points to an address on a host on the second first cluster.

**Comment by vincent99** [comment]
Also fixed with #11865

**Comment by moelsayed** [comment]
Confirmed fixed.
