### ISSUE TITLE
Logging page info showing across clusters

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11876]
**Rancher versions:** 2.0 master 3/2

**Steps to Reproduce:**
1.  Create two clusters
2.  Setup logging on one cluster
3.  Go to second cluster logging page

**Results:**  Logging info from first cluster is showing up in second cluster.  Should be cluster specific.

**Comment by vimniky** [comment]
@aiwantaozi and I are working on this issue.

**Comment by aiwantaozi** [comment]
Just create PR, will update after merged.

**Comment by aiwantaozi** [comment]
@vimniky I have update the backend PR, and find that UI part could not show the related config, UI are not match with the response data, please check.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/6
Verified fixed
