### ISSUE TITLE
Count set when deploying Stateful set is not taking effect.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11870]
Rancher versions: Build from master Mar 2

Steps to reproduce the problem:
Create a Workload of type Stateful set and set  the pod count to 2.
Workload gets created successfully , but there is only 1 pod that gets deployed.

**Comment by alena1108** [comment]
@sangeethah seems to work now, could you retest

**Comment by sangeethah** [comment]
Tested with latest build from master.

Count set when deploying Stateful set  takes effect.
