### ISSUE TITLE
Embedded logging never sets up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11877]
**Rancher versions:**  2.0 master 3/2

**Steps to Reproduce:**
1.  Create a cluster with 4 CPU and 8G of Ram
2.  Try to enable embedded logging

**Results:** Elasticsearch and Kibana failed to deploy
![image](https://user-images.githubusercontent.com/11514927/36920469-019dcb56-1e1e-11e8-9be1-b13e9b5e1c43.png)

**Comment by aiwantaozi** [comment]
Just create PR, will update after merged.

**Comment by aiwantaozi** [comment]
@tfiduccia The PR is merged, could you help test it?

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Verified fixed
