### ISSUE TITLE
Can't view workloads as project members/owner

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#11889]
Steps to reproduce:

- enable github auth
- add `user1` to authorization list
- login with user1
- login as admin and create a cluster then add `user1` as a member or owner to default project
- try to create a new workload with user1

results:

np workloads are created by this member

**Comment by galal-hussein** [comment]
I can see the workloads being created if i logged in with the admin user, but can't see them with the owners or members of the same project

**Comment by cjellick** [comment]
@sangeethah I assigned to you since you'll be testing the related issue, but feel free to reassign to @galal-hussein.

**Comment by sangeethah** [comment]
Will has @galal-hussein test the user case in GH auth setup.
I will test same use cases around local auth enabled setup.

**Comment by galal-hussein** [comment]
@cjellick i was able to see created workload with project members and owners, however i can see them with 0 pods:

<img width="846" alt="screen shot 2018-03-03 at 3 51 41 pm" src="https://user-images.githubusercontent.com/3309968/36935057-e6211602-1efa-11e8-9567-98744227d6da.png">

**Comment by sangeethah** [comment]
@galal-hussein , Wanted to confrm that it is not a refresh issue 
 which is tracked here - https://github.com/rancher/rancher/issues/11595

**Comment by sangeethah** [comment]
Closing this issue since the issue with namespace list is not seen anymore. New issue is tracked in
 in https://github.com/rancher/rancher/issues/11910.
