### ISSUE TITLE
Should not allow for deletion of certificates when it is in use by ingress.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11888]
Rancher versions: Server build from master

Steps to reproduce the problem:
Create a certificate C1.
Create workload - wl1.
Create ingress having rules that point to wl1 with requested host having certificate -C1.
Ingress url works as expected when accessed requested host headers.

Delete certificate - C1.

Ingress url with requested host headers stops working.

We should not allow for deletion of certificates when it is in use by ingress.

**Comment by orangedeng** [comment]
I can create a ingress with non-exist secret in Kubernetes. It means that we are allow to delete a secret even this secret is used by ingress.
I don't think we should to validate it while Kubernetes does not validate it.

**Comment by sangeethah** [comment]
@orangedeng Why do we not want to prevent deletion of certificates from our side , if they are still in use by ingress ? The equivalent test would be to see if kubernetes allows for ingress creation using certificates that are non existent ?

**Comment by orangedeng** [comment]
For now, certificates in rancher will be deployed into cluster as secret when it is used by ingress. So the equivalent test would be if an secret can be delete or not if it is used by ingress. The result is *yes*.
```
V_YCYXDENG-MC0:~ dengyuxing$ kubectl --kubeconfig ./doconfig get secret
NAME                        TYPE                                  DATA      AGE
default-token-8kcmc         kubernetes.io/service-account-token   3         5m
netes-default-token-t9ljw   kubernetes.io/service-account-token   3         5m
test-key                    kubernetes.io/tls                     2         2m
V_YCYXDENG-MC0:~ dengyuxing$ kubectl --kubeconfig ./doconfig get ingress
NAME      HOSTS     ADDRESS   PORTS     AGE
test      *                   80, 443   12s
V_YCYXDENG-MC0:~ dengyuxing$ kubectl --kubeconfig ./doconfig delete secret test-key
secret "test-key" deleted
V_YCYXDENG-MC0:~ dengyuxing$ kubectl --kubeconfig ./doconfig describe ingress
Name:             test
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<none>)
TLS:
  test-key terminates 
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     
        /coo   ingress-3c414ef4eac29d9d8be2f93f2d4497fc:80 (<none>)
Annotations:
  state:  {"Ly9jb28vODA=":"deployment:default:test","dGVzdC1rZXk=":"project-vq7xr:test-key"}
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  55s   nginx-ingress-controller  Ingress default/test
  Normal  UPDATE  7s    nginx-ingress-controller  Ingress default/test
```

**Comment by alena1108** [comment]
@sangeethah vanilla k8s doesn't care. You can specify non-existing secret when creating ingress, or delete valid secret when it is still being referenced by ingress.

So the real question here is - whether we want to add this extra layer of validation on our api side.

**Comment by alena1108** [comment]
@deniseschannon @sangeethah the decision is for now to not add any extra validation on Rancher side for dependent resources, if k8s doesn't support it. This rule applies for any resource using the dependencies, not just ingress. There are a couple of reasons:

1) User would want to be able to recreate the dependent resource w/o modifying all the resources referencing it, first.
2) The validation call on Rancher API can be expensive given that we have to execute extra queries to fetch the underlying resource.

Moved the milestone.

**Comment by orangedeng** [comment]
@sangeethah As we discussed, we don't have a practical way to implement it. And also, there is a use case for not preventing the removal that 1 certificate used by 100 ingress. I don't think it should be a bug and need fixed immediately.
