### ISSUE TITLE
Pod security policies do not work correctly for non-default namespaces/projects

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#11887]
When creating a different new project/namespace in a cluster, pod security policies do not bind correctly, and instead all pods created in that project/namespace create with no pod security policy bound (and therefore fail to create).

Steps to reproduce:
1. Create cluster with pod security policy enabled
2. Create new project and namespace in the cluster 
3. assign a pod security policy to the newly created project
4. deploy a pod in the new project
5. pod creation will fail

**Comment by sangeethah** [comment]
Tested with 2.0 build from master .

Pod security policies work as expected for non-default namespaces and projects when default PSP is set at cluster/project level.
