### ISSUE TITLE
kubelet not woking.

### ISSUE THREAD

**Issue by rc452860** [rancher/rancher#11897]
**Rancher versions:**
rancher/server:
rancher/agent:v1.2.9

**Infrastructure Stack versions:**
kubernetes (if applicable):rancher/k8s:v1.8.5-rancher4

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.12.1-ce, build 7390fc6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04 amd64 kernel 4.4.0-87-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes custom template follow https://www.cnrancher.com/kubernetes-installation/
**Results:**
kubelet (Expected state running but got error: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate")

**Comment by rc452860** [comment]
![image](https://user-images.githubusercontent.com/3949222/36929392-e9d0b3e6-1eca-11e8-939d-d439685d483d.png)

**Comment by rohajda** [comment]
I am facing same issue on oracle enterprise linux with 3 nodes - 1 master and two slaves. Both slaves installation failing on error above

**Comment by rc452860** [comment]
I don't know what's wrong.I follow document on VM Ware and Aliyun, VMware and Aliyun use same Linux system ubuntu 16.04 but Aliyun is normal, VM Ware installation has the error

**Comment by jph** [comment]
Same. CentOS 7 for me.

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:15:20 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:17:54 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by EricVS** [comment]
Hi, 

Although Rancher supports Docker CE/EE version 17.12.x ([Rancher Docs](http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions), Kubernetes does not [Kubernetes CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md), not even in 1.9 (which still mentions that validated Docker versions are the same as for 1.8.

I ran into the same issue on CentOS 7. The highest version I got it to work without issues is 17.09.1-ce. 
I'd suggest you downgrade to that version and give it another try.

Kind regards, 

Eric V.

**Comment by superseb** [comment]
This (breaking) change went into 17.12.1, 17.12.0 should work fine but as stated by @EricVS the currently supported Docker versions for Kubernetes are 1.12,1.13 and 17.03. (http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions)

**Comment by rafaelgaspar** [comment]
Docker 17.12.1 is now the default for CoreOS Stable channel, and I couldn't find anyway to downgrade it, so I'm not able to bring new nodes up in my cluster, is this being worked on?

**Comment by zommarin** [comment]
There is a way to downgrade Docker on CoreOS, but you will get a old version (1.12).

See: https://coreos.com/blog/toward-docker-17-in-container-linux
