### ISSUE TITLE
Can it be possible to commit image directly from the web interface ?

### ISSUE THREAD

**Issue by mib4fun** [rancher/rancher#1189]
Hello devops !

This is really an awesome interface ;D.
I've been in using it for few month, it rocks !

I wonder if there is a way for me to commit the docker image from the web interface ?

thanks

**Comment by deniseschannon** [comment]
Currently, there is no way to commit the docker image from the web interface. I've added it as an enhancement request. Thanks!

**Comment by Volkanugr** [comment]
any progress ? 👍

**Comment by will-chan** [comment]
What do you want to be able to do here?  Is this different than just pushing the image directly from the docker client to DockerHub or any registry you want?

**Comment by will-chan** [comment]
Closing this and will re-open if this feature is something we'd consider.  Right now, we have no plans to allow users to distribute Docker images from Rancher.
