### ISSUE TITLE
Can't login with group's members

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#11908]
Rancher server: master at March 3rd

steps to reproduce:

- Enable github authentication
- Select ` Allow members of Environments, plus Authorized Users and Organizations`
- Create a new cluster
- Add github group to cluster members
- Try to login with one of this group's members

Results:

the user will be unauthorized and can't login to rancher server

**Comment by will-chan** [comment]
@galal-hussein adding individual users work right?

**Comment by galal-hussein** [comment]
@will-chan yes it does

**Comment by galal-hussein** [comment]
Verified with latest master build, i was able to add a group to a cluster/project and login with a member of github group
