### ISSUE TITLE
User name is empty in member list in  Edit cluster/Project view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11900]
Rancher versions:  2.0 build from master

Steps to reproduce the problem:
Create a user   say user1.
Scenario 1:
Add "user1" as "cluster owner"/"cluster member by using" the Members->"Add Memebers" option for cluster.
Go to Cluster Edit view and see the member list. Username in the member list is empty.

<img width="1101" alt="screen shot 2018-03-02 at 9 43 58 pm" src="https://user-images.githubusercontent.com/4266958/36931039-d8f029ca-1e62-11e8-9e57-07c2d983063a.png">

Scenario 2:
Add "user1" as "project owner"/"project member by using" the Members->"Add Memebers" option for project.
Go to Project Edit view and see the member list. Username in the member list is empty.

<img width="1101" alt="screen shot 2018-03-02 at 9 13 10 pm" src="https://user-images.githubusercontent.com/4266958/36931033-a835ea40-1e62-11e8-8086-cca4bf9a9123.png">

**Comment by westlywright** [comment]
I belive this was a result of a missing api that is now in place. tested on latest (03-04-18 12:50:37AM) server:master and the api was now present for local users and names showed correctly

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/4
Verified fixed
