### ISSUE TITLE
Edit view for workload of type "cronjob" shows the workload type as deployment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11915]
**Rancher versions: Build from Mar 3

Steps to reproduce the problem:
Create a workload of type "cronjob" .
Edit this workload.
In Edit view for workload of type "cronjob" shows the workload type as deployment.
Also schedule details of this workload is not presented to the user.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/4
Verified fixed
