### ISSUE TITLE
Attempting to edit  entries (that were auto created as part of ingress/workload creation)  in "Service Discovery" page results in error page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11911]
Rancher versions: 2.0 build from Mar 3

**Steps to Reproduce:**
Create some workloads.
Create some ingress.
Service discovery view lists all DNS entries relating to the above created workloads and ingress.

Attempting to edit any of these entries results in error page:
<img width="637" alt="screen shot 2018-03-03 at 12 47 54 pm" src="https://user-images.githubusercontent.com/4266958/36939181-b165b74c-1ee1-11e8-8037-ca4e07a88fc8.png">
 
Should we even show "Edit"/"Delete" option for these entries?

**Comment by sangeethah** [comment]
@alena1108 Should we even show "Edit"/"Delete" option for these entries?

**Comment by vincent99** [comment]
Editing DNS entries in general was broken.  Whether you should be edit these or not is a separate problem (and up to the presence of the update/remove links as far as the UI is concerned)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/4
Verified fixed
