### ISSUE TITLE
Ingress not functional when creating ingress rules with service targets pointing to DNS entries created for workloads.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11912]
Rancher versions: 2.0 Build from master -Mar 3

Steps to reproduce the problem:
Create few workloads.
This results in service discovery entries created.
Create Ingress that has service rules that point to these  service discovery entries.
Ingress is not functional.
When accessing ingress url , we get a "503 Service Temporarily Unavailable"

Should we even allow for creating ingress rules with these  service targets ?
If this should not be allowed , 
1. API should error out in this case.
2. UI should not show them as options.

Currently auto created service discovery entries for workloads and other ingresses are shown when attempting to create service ingress rules.

**Comment by alena1108** [comment]
@sangeethah the port on the service should match the port on ingress (https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource). If you haven't specified any ports for the workload, the service that we auto generate, would have port 42. Ingress won't find the targets for this port. Try creating the workload with port 80 exposed (internal). Then you'll get the service with 80:80, and the ingress should work. If that works, you can open a low priority ticket for the UI, so we can may be filter out services based on the ports picked, so we only show the ones having the same port exposed.

**Comment by sangeethah** [comment]
@alena1108 When workloads are created with port type "Internal Cluster Ip" (80:80) and DNS entries for this service is used as service targets to Ingress , ingress directs traffic to the workload pods as expected.
