### ISSUE TITLE
Stack upgrade repeat forever for some custom template

### ISSUE THREAD

**Issue by rtau-t24** [rancher/rancher#11939]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3-1
ipsec: 0.2.2
network-services: v0.2.8
scheduler: v0.8.3
kubernetes (if applicable): None

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:21:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ cat /etc/os-release 
NAME=Boot2Docker
VERSION=17.09.1-ce
ID=boot2docker
ID_LIKE=tcl
VERSION_ID=17.09.1-ce
PRETTY_NAME="Boot2Docker 17.09.1-ce (TCL 7.2); HEAD : e7de9ae - Fri Dec  8 19:41:36 UTC 2017"
ANSI_COLOR="1;34"
HOME_URL="http://boot2docker.io"
SUPPORT_URL="https://github.com/boot2docker/boot2docker"
BUG_REPORT_URL="https://github.com/boot2docker/boot2docker/issues"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware ESXi 5.5

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher using external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a new Cattle environment, we have added the component 'network-policy-manager', version v0.0.2 as well
2. Add 2 hosts to the environment
3. Add the catalog containing the template you want
4. Launch the template
5. Upgrade the template to the same version
6. Wait for all the services to finish upgrade and the stack upgrade progress to complete

**Results:**
We would expect the upgrade could complete, the stack will, after all the services finish upgrade, shows the button "Finish Upgrade".

However, what we see is the individual service start to upgrade and finish, but the stack never shows finish upgrade but all the services redo the upgrade after a while.

**Comment by rtau-t24** [comment]
I've created a catalog containing the template and related materials to reproduce the issue: https://github.com/rtau-t24/rancher-test

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
