### ISSUE TITLE
User can use pre-can environment variables in Pipeline

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11934]
**Rancher versions:**
2.0 master 05/3

User can use pre-can environment variables in Pipeline

**Comment by gitlawr** [comment]
pre-defined environment variables:
```
CICD_GIT_COMMIT
CICD_GIT_REPO_NAME
CICD_GIT_BRANCH
CICD_GIT_URL
CICD_PIPELINE_ID
CICD_PIPELINE_NAME
CICD_TRIGGER_TYPE
CICD_EXECUTION_ID
CICD_EXECUTION_SEQUENCE
```

**Comment by gitlawr** [comment]
Works in the backend but is dependent on https://github.com/rancher/rancher/issues/12265 to show variable list in the UI when enters a `$` in the config.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
