### ISSUE TITLE
User can use their own GitHub account to create Pipeline

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11933]
**Rancher versions:**
2.0 master 05/3

**Steps to Reproduce:**

1. Enable Pipeline
2. Create a new user as admin
3. Login with the newly created user
4. Create a Pipeline

**Results:**
The first step used the GitHub account from the one who enables the Pipeline.

**Expected Results:**
The newly created user should log in to his own GitHub account.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/20
Verified fixed
