### ISSUE TITLE
Balancer Service detail page and Load Balancer detail page significantly different

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1193]
build from master - June 12th
Steps;
1.  Create a load balancer and go to details page
2.  Create a Service Balancer and go to details page

Results:
Although they both have most of the same data, the Balancer Service details page does not contain the description or the config information.
![image](https://cloud.githubusercontent.com/assets/11514927/8135350/92ba1da8-10eb-11e5-81de-a12ce9d6e48c.png)

Expected:
Config information should be there and the look of the details should be similar
![image](https://cloud.githubusercontent.com/assets/11514927/8135346/87049312-10eb-11e5-8c3c-e0dffe3c7afd.png)

**Comment by deniseschannon** [comment]
This is no longer valid with the new UI as well as the fact that standalone load balancers were removed.
