### ISSUE TITLE
Github account is not deleted after disable Pipeline.

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#11946]
**Rancher versions:**
2.0 master 05/3

**Steps to Reproduce:**
1. Enbale Pipeline
2. Disable Pipeline

**Results:**
Access `/v3/sourcecodecredentials`, the GitHub user still there.

**Comment by gitlawr** [comment]
Didn't reproduce with master 3/19. I wonder if it is caused by stale data?

**Comment by biblesyme** [comment]
Verified with master 3/19. Maybe it caused by stale data.
