### ISSUE TITLE
Logging configuration is not isolated per Cluster/Project

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#11948]
**Rancher versions:** master  05/03
**Steps to Reproduce:**
-  Create one cluster
- create 2 projects
- on project 1, configure kafka based logging target. Add a custom value
**Results:**
- on project 2, if you try to configure logging, you will find that the same configuration for project 1 is already set. Updating project 2 will reflect on project 1 as well.

**Comment by moelsayed** [comment]
@aiwantaozi It seems the issue is there across clusters as well. If I create two clusters, the configuration from one cluster is reflected in the second cluster.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/6
Verified fixed
