### ISSUE TITLE
Workload shows 0 pod count as soon as it gets when new namespace is also created as part of workload creation until a manual refresh

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11957]
**Rancher versions: rancher server build from Mar 5

Steps to reproduce the problem:
Create a Workload and as part of workload creation use "add a new namespace" option to add a new namespace.
When user is brought back to workload list view where pod count for workload is shown as 0.
<img width="1370" alt="screen shot 2018-03-05 at 10 18 02 am" src="https://user-images.githubusercontent.com/4266958/36992101-afb24112-205e-11e8-82bc-638c3c7e8b48.png">

On manual refresh , able to see the pods for the workload.

**Comment by vincent99** [comment]
There's no change events for the pod, workload, or namespace sent in this case.

**Comment by sangeethah** [comment]
Tested with build from master - Mar 6

Workload shows correct pod count as soon as it gets created when new namespace is also created as part of workload .
