### ISSUE TITLE
Upstream K8S Bug: State of workload doesn't reflect state of pods

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11956]
**Rancher versions:** 2.0 master 3/4

**Steps to Reproduce:**
1.  Deploy a wordpress catalog app but don't add any configuration

**Results:**  The workload says active but the pods are in error.  Would be nice if the workload reflected the state of the pods.
![image](https://user-images.githubusercontent.com/11514927/36990491-1cf6b80e-2062-11e8-812b-0873cd913675.png)

**Comment by alena1108** [comment]
https://github.com/kubernetes/kubernetes/issues/61205

@ibuildthecloud we can add a temporary fix on our side by adding an exception in https://github.com/rancher/types/blob/master/status/status.go to read `unavailablereplicas` for deployment, in addition to relying on conditions. Or we can wait for the official fix

**Comment by deniseschannon** [comment]
@alena1108 let's wait for official fix

**Comment by deniseschannon** [comment]
@guangbochen can you make sure all the templates in `https://github.com/rancher/charts` are using `apiVersion: apps/v1beta1` instead of `apiVersion: extensions/v1beta1`? otherwise there will be this error.

**Comment by tfiduccia** [comment]
@deniseschannon - The bug I'm actually trying to report is that the containers status and workload status don't actually correspond.  Wordpress is just the easiest way to show this.  This is still an issue.

![image](https://user-images.githubusercontent.com/11514927/39209544-e7655f4e-47ba-11e8-8d30-80b0d15cd5cc.png)

**Comment by alena1108** [comment]
@guangbochen @StrongMonkey if you do view catalog App in API, the `notes` field still shows `apiVersion: extensions/v1beta1` for wordpress-mariadb (see full value here). How does this note get generated? Is it possible that helm overrides the api field?

**Comment by StrongMonkey** [comment]
@alena1108 i believe @guangbochen already updated that in this commit https://github.com/rancher/charts/commit/8873fa40bfcd635e87f8bdb4433e4166081da48d. Also i don't think helm overrides api version. Can you check if your charts is updated to date?

**Comment by deniseschannon** [comment]
Unable to reproduce with v2.0.0. It's now showing `updating`. @tfiduccia can you test too?

<img width="1263" alt="screen shot 2018-05-09 at 1 40 58 pm" src="https://user-images.githubusercontent.com/11410997/39838588-a5a1b35c-538e-11e8-870d-0cfe35b27d2c.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/10
Verified fixed
