### ISSUE TITLE
Line up Amazon Security Group "Learn more" text with Standard & Custom

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1195]
Build from Master

the Learn more text is aligned with the Radio buttons instead of text.

Results:
![image](https://cloud.githubusercontent.com/assets/11514927/8137652/96544520-10f9-11e5-8550-5088b43464ac.png)

Expected:
Move the learn more text to the right and under Standard:

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/515

**Comment by tfiduccia** [comment]
Version - master 3/8
Not fixed - this is not currently on master - maybe not merged yet?

**Comment by lvuch** [comment]
![screen shot 2016-03-09 at 3 03 14 pm](https://cloud.githubusercontent.com/assets/3013118/13652219/1f722ae6-e608-11e5-83a5-f6a2ecf2eb57.png)
It should look like this now. @vincent99 is this merged?

**Comment by tfiduccia** [comment]
That looks the same just a different background color for rancher-machine.  Is that was fixed for this.  Because this bug was saying the Learn more text should aline with the Standard/Custom text not the radio button.

**Comment by lvuch** [comment]
Sorry read that wrong...was looking at alignment to "security group" now resolved in https://github.com/rancher/ui/pull/520

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
