### ISSUE TITLE
System account user for cluster is showing up as blank row in edit cluster

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11955]
**Rancher versions:** 2.0 master 3/4

**Steps to Reproduce:**
1.  Create a cluster
2. Edit cluster

**Results:**  the created system account for that cluster is showing up as a blank line.
![image](https://user-images.githubusercontent.com/11514927/36989587-56a64518-205f-11e8-9ea8-56df6c89aff6.png)

**Comment by deniseschannon** [comment]
We are filtering out system account user in the API now so it shouldn't exist in the UI.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/6
Verified fixed
