### ISSUE TITLE
number of pods not showing up in catalog app page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11953]
**Rancher versions:** 2.0 master 3/5

**Steps to Reproduce:**
1.  Deploy Wordpress application
2. Wait
3.  Go to Catalog apps

**Results:**  The number of pods deployed and active aren't showing up
![image](https://user-images.githubusercontent.com/11514927/36988180-7693584c-205b-11e8-9c4d-cf9150f24595.png)

**Comment by deniseschannon** [comment]
Is that what the bar is supposed to show?

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Verified fixed
