### ISSUE TITLE
Websocket error after refreshing UI 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11961]
**Rancher versions:**
rancher/server: Master from March 5th

**Steps to Reproduce:**
1. Create few clusters using DO template
2. From the cluster list page refresh the UI

It results in websocket error and the nodecount shows zero
<img width="1647" alt="screen shot 2018-03-05 at 11 53 24 am" src="https://user-images.githubusercontent.com/18536626/36997113-750cbfba-206d-11e8-89ed-35d1cbab1206.png">

**Comment by deniseschannon** [comment]
Without a valid cert, Google will drop the websocket connection on the browser side. You will need to close your window/tab  or restart the browser (not just refresh).

**Comment by deniseschannon** [comment]
@soumyalj could you test with setting up with a valid cert and see if you still hit this issue?

**Comment by soumyalj** [comment]
With the websocket issue we see the cluster going to "Unavailable" State frequently with the below error:
<img width="1649" alt="screen shot 2018-04-17 at 11 31 28 am" src="https://user-images.githubusercontent.com/18536626/38890643-df6217e4-4236-11e8-8b3d-a9c28b9a3b8d.png">

**Comment by deniseschannon** [comment]
@soumyalj this is a different websocket error, so we should open a new issue for this one.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
