### ISSUE TITLE
UI shows public endpoints with internal IP addresses for aws instances.

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#11969]
**Rancher versions:** master 05/03

**Steps to Reproduce:**
- Create a nodeport/hostport workload. 
- show it's address in the UI. 
**Results:**
- The UI generated address:port URL uses the internal IP address for the instance.

**Comment by alena1108** [comment]
Happens because no externalIP is being set in node.status.addresses; otherwise UI/controllers would pick this ip address for the public endpoint. I believe this issue would be resolved for AWS once RKE support for cloud providers is in - the cloud provider should register the node with both addresses. Re-test once the feature is in.

**Comment by alena1108** [comment]
@deniseschannon public endpoints fix rancher/types#350 will fix only the case when cloudProvider=aws is passed to the cluster. Only in this case node.status.addresses.externalIP will get populated for k8s node, and rancher will back populate this info.

For RKE cluster w/o cloud provider, we might need to add special handling to figure out external IP. Perhaps from annotations passed to the node by rke?

**Comment by ibuildthecloud** [comment]
@alena1108 I would say we look for the rke annotation for public.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Create a cluster with Amazon EC2 driver.
Nodes that gets registered for this cluster has both public and private ip set.

Public endpoint url for nodeport (Every node) has the public ip address as expected.
Public endpoint url for hostport (Nodes running a pod) still has private ip address of the node.

```
"publicEndpoints": [
"addresses": [
"172.31.1.78"
],
"allNodes": false,
"ingressId": null,
"nodeId": "c-wmtrg:m-mjzbv",
"podId": null,
"port": 9080,
"protocol": "TCP",
"serviceId": null
},
]
```

**Comment by sangeethah** [comment]
Tested with latest build from master.

Public endpoint url for hostport (Nodes running a pod) has public ip address now.
