### ISSUE TITLE
User create roles not listed under custom roles when adding users.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11974]
**Rancher versions: Build from Mar 5

Steps to reproduce the problem:

1.As admin user , create a role - say role1.

2. Create user and choose "custom" option.

role1 created in step1 is not presented in the list of custom roles.

**Comment by westlywright** [comment]
Per @cjellick `creating a user should not show any user-defined roles. those roles only apply to cluster and project assignment. not user creation`
