### ISSUE TITLE
 Useful error message must be displayed when an image is specified from a registry that is not in the required namespace

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11979]
**Rancher versions:**
rancher/server: Master from march 5

**Steps to Reproduce:**
1. Create a cluster and a namespace "test" in the cluster
2. Create a quay registry "myregistry" in the namespace "test"
3. Deploy a workload in the namespace "default" by specifying an image from "myregistry" 

The image pull fails and workload creation fails as the registry is in the namespace "test".
An error message should be displayed providing the reason.
The current message displayed is : ```Deployment does not have minimum availability., ReplicaSet "myregtestag-6c85c7fc6" has timed out progressing.```

**Comment by alena1108** [comment]
@soumyalj thats k8s message, we just propagate it. Closing for now.

**Comment by bhouse1273** [comment]
FWIW, the 2.0 QuickStart demonstrates this issue.  Are there additional preparatory steps prior to the QuickStart "deploy a workload" section that have not been mentioned?  Apparently, the "Nginx" image is not found under default conditions.

**Comment by deniseschannon** [comment]
@bhouse1273 thanks for the report. we'll fix it shortly in our quick start guide. it should say `nginx`
