### ISSUE TITLE
Unknow Link

### ISSUE THREAD

**Issue by vimniky** [rancher/rancher#11988]
Steps to reproduce:

- Go to cluster -> project -> workload
- Click into the edit page of a workload
- Click the `Service Log` section

<img width="652" alt="screen shot 2018-03-06 at 14 55 37" src="https://user-images.githubusercontent.com/11426875/37018209-7aafb904-214e-11e8-89bb-d7ac658360b5.png">

**Comment by loganhz** [comment]
fixed in https://github.com/rancher/rancher/issues/11834
