### ISSUE TITLE
When I run pipeline, looks like it's doing nothing for a couple minutes before cloning

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11983]
**Rancher versions:** 2.0 master 3/5

**Steps to Reproduce:**
1.  Create a simple repo to publish
2.  Run it manually once

**Results:**  For about 2 or 3 minutes it just sits there.  Looks like a bug, but eventually it starts cloning.

**Comment by gitlawr** [comment]
It may take some time to set up an agent/pull images before running the clone step. We should consider how to make it more user-friendly.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/28
Verified fixed
