### ISSUE TITLE
Role field in cluster/project member list shows id instead of name 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11980]
Rancher versions: v2.0.0-alpha17

Steps to reproduce the problem:
Create a custom role.
Assign a user with this custom role to cluster/project.
In member list view , role id is used instead of role name

<img width="1212" alt="screen shot 2018-03-05 at 9 29 53 pm" src="https://user-images.githubusercontent.com/4266958/37015659-5e9aecfc-20bd-11e8-906f-0573895a29a1.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/6
Verified fixed
