### ISSUE TITLE
Service DNS entries pointing with workloads from other namespaces do not resolve.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11986]
**Rancher versions: Build from mar 5 night

Steps to reproduce the problem:
Create workload say "test11" in namespace - "test1"
Create service record - "mytest11" using "One or more workloads" option in "default" namespace poniting to "test1"in namespace - "test1".

From containers within namespace "default" , not able to resolve DNS record - mytest11.

**Comment by alena1108** [comment]
@sangeethah thats a k8s limitation. When create service endpoints based on service selector, only pods from the same namespace are being picked. @vincent99 perhaps we can filter out only workloads from the same namespace for workload based services, in the UI

**Comment by sangeethah** [comment]
Tested with latest build from master.

Only workloads from the same namespace get listed when trying to create a DNS record that resolves to "One or more workloads"
