### ISSUE TITLE
Can't access public repository

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11982]
**Rancher versions:** 2.0 master 3/5

**Steps to Reproduce:**
1.  Sign up to Github for PIpeline
2. Try to add a public repository (that doesn't belong to you) by typing it in

**Results:**  When I leave the drop-down it goes blank.  Should be able to add a github public repository

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/28
Not fixed - I still cannot add public repositories that aren't mine.

**Comment by gitlawr** [comment]
@tfiduccia I can go with a public repo like https://github.com/docker/docker.git,
Can you tell me what goes wrong in your test?

**Comment by gitlawr** [comment]
@biblesyme When I input the public repo and leave the drop-down it goes blank. I have to click in the dropdown to valid the input. Can we avoid that?

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/28
Verified fixed - have to click on url before what I typed to ensure it gets added.
