### ISSUE TITLE
Not allowed to create namespace for users who are added with custom role having all access to namespace to a project.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11981]
**Rancher versions: v2.0.0-alpha17

Steps to reproduce the problem:
1. Created a custom Role by granting all access to namespace,pod and deployment.
2. Added a standard user with this custom role to an existing project.
3. Log in to rancher-server as this user
4. Able to see existing namespace in the project.
5. Try to create a new namespace in this project. Fails with error message - "namespaces is forbidden: User "user-bpjl9" cannot create namespaces at the cluster scope"

Custom Role:
<img width="1222" alt="screen shot 2018-03-05 at 9 44 56 pm" src="https://user-images.githubusercontent.com/4266958/37015960-d0da45be-20be-11e8-870e-9898387060a2.png">

Name space creation fails with following error message:
<img width="1255" alt="screen shot 2018-03-05 at 9 42 37 pm" src="https://user-images.githubusercontent.com/4266958/37015976-e14fb82a-20be-11e8-9e11-1d38516c0655.png">

**Comment by cjellick** [comment]
Note that this fix is *not* in alpha17. Its only in master
Per @deniseschannon, we are not going to do a new alpha just for this fix, but if we have other fixes that necessitate a new alpha, this will be included.

**Comment by sangeethah** [comment]
Tested with latest build from master.
This issue is not seen anymore.
User is able to  create namespace successfully.
