### ISSUE TITLE
How to cancel the checked "retain ip"

### ISSUE THREAD

**Issue by zzabc007** [rancher/rancher#11999]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.12.0-ce, build c97c6d6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux release 7.4.1708 (Core)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:**
Can not cancel retain ip on or off of container.

**Comment by loganhz** [comment]
It's not supported. You can clone the service and unselect the retain ip. Then you can delete the old service.
