### ISSUE TITLE
When editing host, stats continue to run after I leave edit screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1199]
Steps:
1.  Create an EC2 machine
2.  Edit EC2 machine
3.  Save edits

Results
Stats continue to run in the background and it created three websocket calls that seem to continue to run, even if I leave host page.

Expected:
Stats shouldn't run at all for edit?  At the very least they should stop when I leave edit screen.

**Comment by vincent99** [comment]
The old host-api does not appear to have closed websockets properly.  The new proxy one does close, so this might have solved itself.

I also went through all the socket client code and made some changes to prevent messages from coming through after a socket was supposed to be closed.

And I changed the "subscribe" socket (the one that keeps everything in the UI up to date, not for the graphs) to watch the "ping" messages and re-connect if it doesn't see a ping for 11 seconds (when it should have gotten 2 by then).

**Comment by tfiduccia** [comment]
Socket still being left open when I click on Edit.  Seems like it's opening two and only closing one.

**Comment by vincent99** [comment]
This should get at least partially better with #1432

**Comment by vincent99** [comment]
How about now?

**Comment by tfiduccia** [comment]
Version - master jan 07
Verified fixed
