### ISSUE TITLE
Clusters, apps/workloads can get stuck in deleting (waiting on foregroundDeletion)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11991]
**Rancher versions:** v2.0.0-alpha17

**Steps to Reproduce:**
1.  Create a custom cluster
2.  Try to add a couple of nodes that have 16.04 version of ubuntu from DO
3.  When nodes are stuck in adding kubernetes delete cluster

**Results:** Custom Cluster stuck in removing state.
![image](https://user-images.githubusercontent.com/11514927/37021944-96cb9e66-20de-11e8-9136-0eb3dd2de265.png)

**Comment by StrongMonkey** [comment]
we didn't fix the root cause of this garbage collector bug. Need to discuss with darren as this needs change from k8s upstream.

**Comment by benyanke** [comment]
Not sure what the current status of this is, but thought it would be worth mentioning that it still occurs for me.
![image](https://user-images.githubusercontent.com/4274911/38509335-3b21e862-3be7-11e8-8839-b663553f17ea.png)

How I got here:

1) Added node 2 to the cluster
2) Realized I configured the VM incorrectly, and deleted the VM
3) AFTER deleting the VM, I deleted it using the rancher console
4) state stuck in screenshot above for 12+ hours (I assume stuck indefinitely).

Would it have been better for me to remove the node from rancher before deleting the VM? Also, is there any way in the short term, before the root cause is fixed, to fix this without destroying and rebuilding the entire cluster?

**Comment by fkollmann** [comment]
How can I remove the node manually?

**Comment by yoke88** [comment]
try below procedures:
* ` kubectl delete node nodename`
*  in UI ,select the node ,then click edit, choose view in API ,then click delete button and using API to delete the node.
* then clean the node .

**Comment by jevin36** [comment]
@yoke88 that didnt help me, cause the nodes weren t initialized in the first place and kubernetes didn t know about them

what I did on a my single node instance with the embedded etcd (not HA rancher !!!!) was:
1. docker exec into the rancher container
2. kill the rancher process

**Comment by stefanvangastel** [comment]
Having the same issue with deleting **workloads** from Rancher 2.0.4 UI on custom offline on-prem cluster:

`Deployment does not have minimum availability; waiting on foregroundDeletion`

Running `kubectl delete deploy/faultyworkload -n mynamespace` does remove the workload / deployment.

**Comment by alena1108** [comment]
@StrongMonkey the last time I've seen it happening was on @tfiduccia setup, for cluster object. K8s vendor is v1.10.5. But looks like it happens for both types of objects:

* management cluster layer - CRDs created on the rancher side
* user cluster layer - k8s "native" objects

Here is the cluster object stuck in finalizer snippet.

```
{
    "apiVersion": "management.cattle.io/v3",
    "kind": "Cluster",
    "metadata": {
        "annotations": {
            "authz.management.cattle.io/creator-role-bindings": "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}",
            "field.cattle.io/creatorId": "user-6shtq",
            "lifecycle.cattle.io/create.cluster-agent-controller-cleanup": "true",
            "lifecycle.cattle.io/create.cluster-provisioner-controller": "true",
            "lifecycle.cattle.io/create.cluster-scoped-gc": "true"
        },
        "clusterName": "",
        "creationTimestamp": "2018-07-17T18:26:30Z",
        "deletionGracePeriodSeconds": 0,
        "deletionTimestamp": "2018-07-17T18:46:42Z",
        **"finalizers": [
            "foregroundDeletion"
        ],**
        "generation": 2,
        "name": "c-g2bt6",
        "namespace": "",
        "resourceVersion": "7058",
        "selfLink": "/apis/management.cattle.io/v3/clusters/c-g2bt6",
        "uid": "ed2a7092-89ee-11e8-8cc0-0242ac110002"
    },
```

The cluster doesn't seem to have any objects referencing it via OwnerReference, but we need to double check on that.

Current workaround is (apply with caution, only when the object is really stuck, and after ensuring that all the objects referencing the removing one, are really removed): 

* connect to cluster using kubectl (if the object is on the management layer, login to rancher docker container, and run kubectl)
* kubectl edit <resource name>
* remove the foregroundDeletion line, and save changes

**Comment by miclefebvre** [comment]
@StrongMonkey refering to this issue: https://github.com/rancher/rancher/issues/14760

Restarting the Rancher Server deleted the Catalog App but all pods created with the Catalog App stayed stuck.
I then saw that all pods stucked where on the same worker node, so I removed the node and then all the pods were removed.

I'm sure the problem is not with my node because there were other pods on this node that were working perfectly.

**Comment by stieler-it** [comment]
I had a a stuck node that even was displayed although it's pool wasn't visible any more. Restarting Rancher server fixed it.

**Comment by moelsayed** [comment]
Tested using v2.0.7-rc5:
- Deleted a cluster while nodes are being added.
- Deleted nodes and deleted the clusters while the node is being deleted. 
- Deleted a cluster after removing the nodes VMs
 I was able to delete resources (clusters, nodes, workloads) successfully.

**Comment by timfallmk** [comment]
Have the node removal issue with `v2.0.6`. Updated to `v2.0.7` and issue remains.

**Comment by frekele** [comment]
I have a similar issue. https://github.com/rancher/rancher/issues/15039

**Comment by workXMH** [comment]
Have the app removal issue with v2.0.6

**Comment by moelsayed** [comment]
@timfallmk Can you please provide steps to reproduce the issue after the upgrade ?
@workXMH Can you please try with v2.0.7 ?

**Comment by aaronchilcott** [comment]
I experienced this issue myself and I was able to fix the symptom (cluster not disappearing from the rancher GUI) by ensuring the cluster was completely removed from kubernetes, and then restarting the docker container for rancher. eg. `docker restart <rancher container name>`

I'm uncertain if this has been mentioned in previous comments, apologies if doubling up.
