### ISSUE TITLE
Unable to provision clusters using custom registry for RKE

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11990]
**Rancher versions:**
rancher/server: Master from March 5th

**Steps to Reproduce:**
1. Push all images required for cluster creation to quay registry. 
2. Create a custom cluster by clicking on custom registry and provide URL, username and password.
Cluster creation fails . The images get pulled as `quay.io/alpine:latest` and not as "quay.io/soumyalj/alpine:latest"
```
Can't pull Docker image [quay.io/alpine:latest] for host [159.65.225.97]: Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n
```

<img width="1261" alt="screen shot 2018-03-05 at 11 09 09 pm" src="https://user-images.githubusercontent.com/18536626/37018721-3db6274c-20ca-11e8-8b93-8a01925736a1.png">

**Comment by alena1108** [comment]
@soumyalj we only append registry url to the private image name; user name does not get appended. If private registry url provided to cluster was quay.io, then things work as expected.

**Comment by alena1108** [comment]
The resolution: we should provide a way to change the namespace for system images used by cluster provisioning. It can be done by modifying `k8s-version-to-images` setting.

**Comment by deniseschannon** [comment]
After internal discussion, we expect users to have a private registry where they can mirror our `rancher` repo with all images (like what is expected in 1.6). 

This means we cannot test with quay.io, but will need to test with a different private registry.

**Comment by deniseschannon** [comment]
This means we'd have to get a private registry that can support `<private-registry>/rancher/<images>`.

**Comment by soumyalj** [comment]
Used v2.0.0-rc1. Created a private registry pushed the images required for cluster creation into the registry. Creating a cluster using private registry images was successful. Workload creation was also ok.
