### ISSUE TITLE
[Windows] When I restart the container, the container's ip will change

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#11998]
**Rancher versions:**
rancher/server: v1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 2-16
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
All
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. Create a service, view the IP of the container is "192.168.15.200"
2. Restart this container and view the container IP
**Results:**
Container IP has changed

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
