### ISSUE TITLE
container-crontab fails if service names contains capital letters

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12001]
container-crontab v0.3.0 and up

In this line (https://github.com/rancher/container-crontab/blob/v0.4.0/cron/cron.go#L133) we compare servicename, where one comes from metadata client (which returns lowercase) and the other one comes from the labels with the stack/service name. This is not equal, and cron schedule will never be activated.

**Comment by soumyalj** [comment]
Tested using v1.6-development build with Rancher Container Cron catalog v0.5.0 . Created a cron job for a service with name having all Capital letters and both small and caps (TESTCAPS and also tEStCAps). Used the below labels:
```
cron.schedule=0 */1 * * * *
cron.action=restart
```
All the containers restarted every minute
