### ISSUE TITLE
[API] When PSP is enabled for a cluster and no default PSPT is set , users will not be able to deploy pods in projects with no default PSPT.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12009]
**Rancher versions: v2.0.0-alpha17

Steps to reproduce the problem:

Scenario 1:
Create a cluster with PSP enabled but do not set any Default Pod Security Policy.
Create project without setting Default Pod Security Policy.

User will not be able to deploy any pods with the error - ```pods "hello1-65d4cc4cfc-" is forbidden: no providers available to validate pod request, Deployment does not have minimum availability., ReplicaSet "hello1-65d4cc4cfc" has timed out progressing.```

Should we not allow for PSP to be enabled without having a default pod security policy set?

Scenario 2:
Create a cluster without enabling PSP.
Create project setting Default Pod Security Policy. This is allowed at this point. 
But PSP does not take effect since PSP is not enabled at the cluster level.

Should API error out in this case , since PSP is not enabled at the cluster level?

Scenario 3: This is the workflow that is not very intuitive.
1. Create a cluster without enabling PSP.
2. Created few projects without setting  Default Pod Security Policy. 
3. Created a project with Default Pod Security Policy.   
When I saw that the PSP did not take effect , I edited the cluster and enabled PSP (without setting Default Pod Security Policy).
This resulted in the Default PSP take effect for the project as expected.

But after this , i am not able to deploy pods to any of the existing projects from step 2.

**Comment by deniseschannon** [comment]
This is now enforced in the UI, where you cannot enable PSPs without a default set. 

This needs to be fixed in the API to avoid.
