### ISSUE TITLE
Resources dropdown should use begins with instead of contains match to search the dropdown list.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12003]
Rancher Server - v2.0.0-alpha17

Steps to reproduce the problem:
Create custom role by using "Add Role" option
In the "Add Role" page,  In Resource field in "Grant Resources" section - type p.
I expected all the resources that started with "p" to show up .
Currently all resource names having any "p" is presented to the user.

<img width="1198" alt="screen shot 2018-03-06 at 8 19 10 am" src="https://user-images.githubusercontent.com/4266958/37044082-62a7adbc-2117-11e8-8295-82c3666daca7.png">

**Comment by vimniky** [comment]
@vincent99 should we change the search algorithm from `contains` to `strict match` or we can support both and add a prop to let the searchable-component user decide which one to use?

**Comment by vincent99** [comment]
I don't know that I agree it should be starts with; if you type in "Volume" you'd probably like to see "PersistentVolumeClaims".

**Comment by vimniky** [comment]
Updated

**Comment by vincent99** [comment]
Changed to prioritize things starting with the one of the search terms first

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Verified fixed
