### ISSUE TITLE
Search in Github auth page is only doing a exact match instead of list

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12004]
**Rancher versions:** v2.0.3-rc3

**Steps to Reproduce:**
1.  Authenticate using Gihtub
2.  Search for a user

**Results:**  I never get a list of "like" users and only get an exact match.  Which kinda makes the search useless.  The drop-down never has more then 1 user which makes it seem like a bug.

**Comment by cjellick** [comment]
backend of improved search is in but the UI needs a fix in the search dropdown. assigning ove to @vincent99

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/6
Verified fixed
