### ISSUE TITLE
Do not provide option to edit/delete Ingress DNS entries.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12012]
**Rancher versions:**  v2.0.0-alpha17

Steps to reproduce the problem:
Create workload.
Create Ingress having rules pointing to workload.
After this we will see Ingress entries relating to rule auto created in Service Discovery list view.

We should not provide edit/delete options for these entries.

**Comment by tfiduccia** [comment]
version - 2.0 master 3/9
Verified fixed
