### ISSUE TITLE
[Windows]Support Rancher ECR in Winodws Environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#12018]
Support Rancher ECR Runs in Windows environment.
1. Adding CROSS build for Rancher ECR and build a image base on microsoft/nanoserver
2. Adding new catalog entry for Rancher ECR Windows version

**Comment by kingsd041** [comment]
Tested with Rancher/server:v1.6.15-rc5.
Rancher ECR has been supported in the windows environment.
Test passed.
