### ISSUE TITLE
When adding DNS entry of type -"Alias of another DNS record's value" , target drop down says - "select a workload"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12011]
Rancher version - v2.0.0-alpha17
Add DNS entry of type -"Alias of another DNS record's value" .
Target drop down says - "select a workload". This should be changed to "Select a DNS entry".

<img width="1317" alt="screen shot 2018-03-06 at 3 46 24 pm" src="https://user-images.githubusercontent.com/4266958/37065433-b094861a-2155-11e8-8829-1586e9a2c5af.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/6
Verified fixed
