### ISSUE TITLE
github username not populated in the top right corner , it appears after a manual refresh.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12020]
**Rancher versions: v2.0.0-alpha18

Steps to reproduce the problem:
Enable github and provide access to few users.
Log in as any github user whi has access to the setup.
github username not populated in the top right corner , it appears after a manual refresh.
<img width="656" alt="screen shot 2018-03-06 at 11 20 34 pm" src="https://user-images.githubusercontent.com/4266958/37078722-38d6da20-2195-11e8-852a-02667f768063.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/11
The field is still not updating until I refresh it. When I log into github or out.  It's keeping the previous name in there and when I refresh it switches.

**Comment by tfiduccia** [comment]
Shows local user icon still until refresh.  After refresh it showing github icon
![image](https://user-images.githubusercontent.com/11514927/37685756-ddc10792-2c51-11e8-97df-53d459eff4c7.png)
![image](https://user-images.githubusercontent.com/11514927/37685776-f21f92bc-2c51-11e8-98ce-ad6c94c094e1.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
