### ISSUE TITLE
vSphere node template ui shows variable tokens and not field labels. Not functional.

### ISSUE THREAD

**Issue by segfault** [rancher/rancher#12042]
**Rancher versions:**
rancher/server:v2.0.0-alpha21
rancher/agent:v2.0.3

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.4
 Git commit:    fc4de447b5
 Built: Tue Feb 13 15:28:01 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   fc4de447b5
  Built:        Tue Feb 13 15:28:34 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux haruko 4.15.6-1-ARCH #1 SMP PREEMPT Sun Feb 25 12:53:23 UTC 2018 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Base-metal & vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node tancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Run the current preview and attempt to setup a node template for vSphere. It looks like a ui template is not being processed and tokens are being left on the page.

**Results:**
All fields show tokens like `**%nodeDriver.vmwarevspheree.vcenter.label%**`
Attempting to fill out the fields based on the token names and submitting results in `Validation failed in API: vmwarevsphereConfig` which may be due to incorrect input on my part but I have no idea what field is wrong.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/11
Verified fixed
