### ISSUE TITLE
failed to run Kubelet: mountpoint for cpu not found on Amazon Linux

### ISSUE THREAD

**Issue by ma642** [rancher/rancher#12045]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck:v0.2.3
ipsec:v0.11.2
network-services:v0.6.6
scheduler: /
kubernetes (if applicable):v1.8.5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
I have 2 servers, one installed the rancher server, and another act as node.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
After created a new environment from kubernetes, I add custom host.  All things were ok but the service in kubernetes stack failed of the error : failed to run Kubelet: mountpoint for cpu not found  

Full log is:
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/lib/docker/devicemapper/mnt/957bbe314490ae28d7f0040e12c730262527d15a17243a09f3d1b888a93d1a03 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/lib/docker/devicemapper/mnt/957bbe314490ae28d7f0040e12c730262527d15a17243a09f3d1b888a93d1a03 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/lib/docker/devicemapper/mnt/957bbe314490ae28d7f0040e12c730262527d15a17243a09f3d1b888a93d1a03
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/lib/docker/devicemapper/mnt/57d8444577564c0c94b2edfdbe9172afee6a65a99026437934dc21ded2deb768 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/lib/docker/devicemapper/mnt/57d8444577564c0c94b2edfdbe9172afee6a65a99026437934dc21ded2deb768 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/lib/docker/devicemapper/mnt/57d8444577564c0c94b2edfdbe9172afee6a65a99026437934dc21ded2deb768
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/lib/docker/devicemapper/mnt/20ee0c3255e43731dd5596c4404ce5c10f3f8b7403397090626b1bc2134ae13d '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/lib/docker/devicemapper/mnt/20ee0c3255e43731dd5596c4404ce5c10f3f8b7403397090626b1bc2134ae13d '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/lib/docker/devicemapper/mnt/20ee0c3255e43731dd5596c4404ce5c10f3f8b7403397090626b1bc2134ae13d
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/lib/docker/devicemapper '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/lib/docker/devicemapper '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/lib/docker/devicemapper
2018/3/8 8:13:49+ for i in '$(DOCKER_API_VERSION=1.22 ./docker info 2>&1  | grep -i '\''docker root dir'\'' | cut -f2 -d:)' /var/lib/docker /run /var/run
2018/3/8 8:13:49++ tac /proc/mounts
2018/3/8 8:13:49++ grep '^/run/'
2018/3/8 8:13:49++ awk '{print $2}'
2018/3/8 8:13:49+ for i in '$(DOCKER_API_VERSION=1.22 ./docker info 2>&1  | grep -i '\''docker root dir'\'' | cut -f2 -d:)' /var/lib/docker /run /var/run
2018/3/8 8:13:49++ tac /proc/mounts
2018/3/8 8:13:49++ awk '{print $2}'
2018/3/8 8:13:49++ grep '^/var/run/'
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/c70f00825c71 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/c70f00825c71 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/c70f00825c71
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/a802dbba6d07 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/a802dbba6d07 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/a802dbba6d07
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/002ad2137864 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/002ad2137864 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/002ad2137864
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/2b52bc53cbf9 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/2b52bc53cbf9 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/2b52bc53cbf9
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/0b3b07376df1 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/0b3b07376df1 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/0b3b07376df1
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/4e3836f331bb '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/4e3836f331bb '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/4e3836f331bb
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/b787b0dedb90 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/b787b0dedb90 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/b787b0dedb90
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/ebd573230baf '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/ebd573230baf '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/ebd573230baf
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/6bc62a2a5d94 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/6bc62a2a5d94 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/6bc62a2a5d94
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/4fcdafcf21d9 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/4fcdafcf21d9 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/4fcdafcf21d9
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/c2366e5653bf '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/c2366e5653bf '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/c2366e5653bf
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/bf8ea0042842 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/bf8ea0042842 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/bf8ea0042842
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/34dafa62cef7 '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/34dafa62cef7 '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/34dafa62cef7
2018/3/8 8:13:49+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/default '!=' /var/run/nscd ']'
2018/3/8 8:13:49+ '[' /var/run/docker/netns/default '!=' /run/nscd ']'
2018/3/8 8:13:49+ umount /var/run/docker/netns/default
2018/3/8 8:13:49+ mount --rbind /host/dev /dev
2018/3/8 8:13:49+ mount -o rw,remount /sys/fs/cgroup
2018/3/8 8:13:49+ for i in '/sys/fs/cgroup/*'
2018/3/8 8:13:49+ '[' -d '/sys/fs/cgroup/*' ']'
2018/3/8 8:13:49++ hostname --fqdn
2018/3/8 8:13:49+ FQDN=ip-10-0-0-174.cn-north-1.compute.internal
2018/3/8 8:13:49+ '[' kubelet == kubelet ']'
2018/3/8 8:13:49++ docker info
2018/3/8 8:13:49++ grep -i 'cgroup driver'
2018/3/8 8:13:49++ awk '{print $3}'
2018/3/8 8:13:49 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
2018/3/8 8:13:49+ CGROUPDRIVER=cgroupfs
2018/3/8 8:13:49+ '[' rancher == azure ']'
2018/3/8 8:13:49+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --allow-privileged=true --register-node=true --cloud-provider=rancher --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --fail-swap-on=false --cluster-domain=cluster.local --network-plugin=cni --cni-conf-dir=/etc/cni/managed.d --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --cgroup-driver=cgroupfs --hostname-override ip-10-0-0-174.cn-north-1.compute.internal
2018/3/8 8:13:49I0308 12:13:49.994953   23294 feature_gate.go:156] feature gates: map[]
2018/3/8 8:13:49I0308 12:13:49.995243   23294 controller.go:114] kubelet config controller: starting controller
2018/3/8 8:13:49I0308 12:13:49.995255   23294 controller.go:118] kubelet config controller: validating combination of defaults and flags
2018/3/8 8:13:49I0308 12:13:49.998158   23294 client.go:75] Connecting to docker on unix:///var/run/docker.sock
2018/3/8 8:13:49I0308 12:13:49.998182   23294 client.go:95] Start docker client with request timeout=2m0s
2018/3/8 8:13:50I0308 12:13:50.003810   23294 feature_gate.go:156] feature gates: map[]
2018/3/8 8:13:55error: failed to run Kubelet: mountpoint for cpu not found

**Results:**
kubelet can not start.

**Comment by superseb** [comment]
Sounds like https://github.com/rancher/rancher/issues/10015, can you check the comment in there to see if it's the same?

**Comment by ma642** [comment]
@superseb I had checked #10015 before, and modified the volume mapping to /cgroup:/sys/fs/cgroup:ro. This is a new issue.

**Comment by ma642** [comment]
@superseb I check #10015 again and find this issue is my cause that use the '/sys/fs/cgroup:/sys/fs/cgroup:ro' (it's boot2docker's mapping). All services work fine after using right mapping (/cgroup:/sys/fs/cgroup:ro). 

Thanks for your comment.
