### ISSUE TITLE
User get access to /admin/* without permission

### ISSUE THREAD

**Issue by sgeigenmueller** [rancher/rancher#12044]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 15
 Running: 14
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.51GiB
ID: 3FX6:5D3H:GIZT:ELT3:KP5X:SFSN:KQID:TOYT:HE7D:A4VW:F2GQ:KY4V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-693.11.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Working in Rancher GUI
If you create a new local user with normale "user" rights and log in with this user, you can just type in the URI to /admin/settings etc. and get access! In Setting now you are able to change them also the advance settings. Changes are accepted.
 
**Results:**
Unauthorized access to Rachner Settings without Admin right.

**Comment by vincent99** [comment]
The UI is 100% static/client-side, so you can attempt to load any "page" you want.  The API calls that actually get the data to show will either return nothing, just the part you are supposed to have access to, or an error, depending on what it is.

The settings page in particular tries to load `/v2-beta/settings/api.host`, which will return 404 for a regular user.  If you're seeing the page load then you probably are an admin and don't know it.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
