### ISSUE TITLE
Standard User is not able to create/look up PSP.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12049]
Server version - v2.0.0-alpha21
Steps to reproduce the problem:

Scenario 1:
As standard user , try to create a PSP . It fails with following errors:
"podsecuritypolicytemplates.management.cattle.io is forbidden: User "user-68xfl" cannot create podsecuritypolicytemplates.management.cattle.io at the cluster scope"

Should standard users be given to ability to create PSP ?

Scenario 2:
As admin , Create a PSP.
When logged in as standard user , User is not able to see the PSP created by admin.

Should standard users be given to ability to see the PSP created admin?

Currently we have PSP as a global resource. Should there  be  a way to have them scoped to cluster?

**Comment by deniseschannon** [comment]
Standard user will not be able to create PSPs as these are global resources. This is intentionally done. We will be adding a "Manage PSPs" global role that can be added to the standard user permissions if a user needs those perms.

Standard users should be able to automatically use PSPs and should be part of the "Create new Cluster" global role.

**Comment by sangeethah** [comment]
Tested with latest build from master

Standard user is able to list all the PSP templates created by admin user for that cluster.
He is not allowed to create/update/delete PSP templates.

User created with "Manage PSP template" role is able to CRUD PSP templates.
