### ISSUE TITLE
Project Member list is empty for cluster owners.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12040]
Rancher versions: v2.0.0-alpha19

**Steps to Reproduce:**

Rancher server version - v2.0.0-alpha19

Steps to reproduce the problem:
As admin , Create DO cluster c1 and assign "user1" as "owner" of this cluster.
Add few projects in c1.

Log in as user1.
He is able to see the projects under c1.
In Edit project view , member list for project is shown.
<img width="1365" alt="screen shot 2018-03-07 at 3 48 09 pm" src="https://user-images.githubusercontent.com/4266958/37125009-7efd7f7e-221f-11e8-81e3-1c09a4a4d665.png">

But member list is empty in project's Member tab.

<img width="1345" alt="screen shot 2018-03-07 at 3 47 15 pm" src="https://user-images.githubusercontent.com/4266958/37124999-78f56538-221f-11e8-836d-a2ecac4a57a1.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
