### ISSUE TITLE
Two Manage & View Volumes added as Built-In role

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12052]
**Rancher versions:** 2.0 master 3/8

**Steps to Reproduce:**
1.  Setup Rancher
2.  Go to Security/Roles

**Results:**  There are two Built-In View Volume and two built-in Manage Volumes roles.   Should only have 1.

![image](https://user-images.githubusercontent.com/11514927/37177728-81f9d150-22dd-11e8-9814-0c9a76ee880a.png)

![image](https://user-images.githubusercontent.com/11514927/37177743-93bc511a-22dd-11e8-8650-5e7da9e8acec.png)

**Comment by cjellick** [comment]
Im not sure of the wording we are going to use around volumes but there are two roles bc there is one for projects (managing the usage of pvcs) and one for clusters (managing the CRUD of PVs). @vincent99 should I change the naming of one of these two roles?
Also, i fee that this roles page would benefit from somehow grouping based on project vs cluster roles.

Co-assigning @vincent99

**Comment by vincent99** [comment]
I would probably say "Manage Storage" for the cluster one, since that includes PVs and StorageClasses

**Comment by cjellick** [comment]
Changed the name to "Manage Storage".
The second "View volumes" has been dropped (bc we decided it was not needed).
@vincent99 I'm going to leave this assigned to you as opposed to send to QA so that you can decide if you want to make some visual indicator of project vs cluster role templates

**Comment by deniseschannon** [comment]
@tfiduccia i only see one now.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/27
Verified fixed
