### ISSUE TITLE
Standard user is not allowed to create custom roles.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12051]
Server version - v2.0.0-alpha21
Steps to reproduce the problem:

Scenario 1:
As standard user , try to create custom role . 
It fails with following errors:
```roletemplates.management.cattle.io is forbidden: User "user-rwk2h" cannot create roletemplates.management.cattle.io at the cluster scope```

Standard users should be allowed to create custom roles.

**Comment by cjellick** [comment]
This is intended behavior. But will bring it up in a dicussion where we holistically reevaluate all of our auth related intended behaviors.
For the discussion, can you supply a use case where you think a standard users should be able to create custom roles?

**Comment by sangeethah** [comment]
@cjellick , Standard user can create a cluster and become the cluster owner. In this case , we would also expect for him to be able to create custom roles that he need to assign for clusters/projects ?

**Comment by vincent99** [comment]
Role templates are a global resource and have a separate user permission to allow or not allow a user to manipulate.  A cluster owner can map people in their cluster to the roles that are available, but not necessarily define custom roles that the rest of the world would see/use.

**Comment by sangeethah** [comment]
Standard Users can be allowed to create custom roles that need not be necessarily seen by other users ?

**Comment by deniseschannon** [comment]
Based on discussion, this will remain the same as roles are a global resource. If an admin wants to provide a "Standard User" with the ability to create roles, they would need to create a custom role with the following permissions:

Perms that are associated with standard user:
-> Create New Clusters 
-> Use Catalogs
-> Login Access 

In addition, they would need to add the `Manage Roles` permission.

**Comment by sangeethah** [comment]
Tested with latest build from master.

1. As admin user:
 Created a user with following Custom global permissions :
 Create New Clusters
 Use Catalogs
 Login Access
 Manage Roles

2. When logged in as this user , he is allowed to create custom roles  and able to add members to cluster/project with this custom role.
