### ISSUE TITLE
Starting Balancer Service after stopping gives degraded status instead of activating

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1205]
build from master - June 12th
Steps:
1.  Create a service, balancer service, alias and external service
2.  Start all services
3.  Stop all services
4.  Start all services

Results:
All the services first time, say activating.  The second time you start, all of them give a activating status except the Service Balancer, it's status says degraded.

Expected:
Should be giving a status of activating, not degraded.

**Comment by deniseschannon** [comment]
Tried to repro on v0.49.0-rc1. There seems to be some kind of pause between activating and active state where it ends up in degraded state. But majority of time it was "Activating". 

Not sure if we can do anything to prevent the "Degraded" state but going to have @alena1108 look into it.

**Comment by alena1108** [comment]
@deniseschannon the pause is because we are waiting for the initial health check reports. Once its reported as healthy, LB service gets updated with the Active state.

**Comment by tfiduccia** [comment]
ok
