### ISSUE TITLE
2.0 Feedback - Issue with CAPITALS in Name Prefix

### ISSUE THREAD

**Issue by ispyinternet** [rancher/rancher#12061]
**Rancher versions:**
rancher/server: PREVIEW

Putting CAPITALS in the name prefix prevents the cluster from being able to register (DNS issue reported). The UX should warn and prevent.

Here is the reported error:

```
Failed to deploy addon execute job: Job.batch "rke-network-plugin-deploy-job" is invalid: spec.template.spec.nodeName: Invalid value: "CONTROL1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by deniseschannon** [comment]
I believe for cluster creation, we now automatically take any capital letters and lowercase them when creating clusters.

@tfiduccia can you confirm?

**Comment by tfiduccia** [comment]
This is in the Node Name for RKE.  All Node names in Node pool need to be lower-case (cause kubernetes).  Will forward to dev.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
