### ISSUE TITLE
Problems running Rancher Server on t2.micro.. Memory?

### ISSUE THREAD

**Issue by aschrijver** [rancher/rancher#12069]
**Rancher versions:**
rancher/server: `v1.6.14`
rancher/agent: `v1.2.9`

**Infrastructure Stack versions:**
healthcheck: `v0.3.3`
ipsec: `v0.13.7`
network-services: `v0.7.19`
scheduler: `v0.8.3`
kubernetes (if applicable): `N/A`

**Docker version: (`docker version`,`docker info` preferred)**

Both on the rancher-server and host instance:

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:21:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Both on the rancher-server and host instance RancherOS `v1.2.0` is installed: `4.9.78-rancher2`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

rancher-server: `t2.micro` with Elastic IP `ip-1`
- container running `nignx` version `1.13.9` with SSL termination, forwarding `admin.example.com` to rancher-server on port `8080`
- container running `rancher-server` with internal DB

custom host: `t2.micro with Elastic IP `ip-2`
- container running `rancher-active-proxy` ([github](https://github.com/adi90x/rancher-active-proxy)) for ports 80 and 448
- container running `rancher-agent` registered to server like this:
```
  sudo docker run -e CATTLE_AGENT_IP="ip-2"  --rm --privileged \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.9 \
    https://admin.example.com/v1/scripts/09...etcetera
```

- Both the rancher-server and the host instances are attached to the same Virtual Private Cloud in AWS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

The Admin UI is functional and mostly works, but a whole number of errors occur, that seem to be related:

- Navigating to Community Catalogs --> rancher-server contain becomes unresponsive, needs restart
- Deleting a stack --> sometimes works, sometimes idem as above
- Installing Community Stacks (tried Postgres, Gitlab, Gogs) --> containers stay in Initializing state (keep restarting). No clear clues in the logs

Some of the errors I encountered described here: https://github.com/rancher/rancher/issues/11926#issuecomment-372021979

----

Having typed all the above suddenly I am wondering if it is even possible to run rancher-server on a `t2.micro` memory-wise.. maybe not :(

`top` shows `VSZ = 3145m (316%)` for the Java process running rancher, and just checked `t2.micro` is just 1GB of memory.. but [minimum requirements for rancher server](http://rancher.com/docs/rancher/v1.2/en/installing-rancher/installing-server/) are 1GB as well it states

**Comment by vincent99** [comment]
1gb is _for the server container_.  A 1gb VM is already a little below this, but if you're going to try and do anything else with the VM like run it as an agent and run containers on it you definitely need a bigger instance.

Also t2.* "burstable" CPU, which means they are fast while you have credits, then completely unusable if you run out.  Check the metric for CPU credit balance in the AWS dashboard.  micro is going to have a very small share and all the startup, installation, initial setup of the container, etc could have eaten much of it and be making things worse.

**Comment by aschrijver** [comment]
Thank you @vincent99 !!
Rancher server on the micro is the only thing that will run there, but I will move it to a bigger instance.
I didn't know the baseline performance was _that_ bad after you run out of credits? Guess I'll have to give Jeff more $$ dough then :)

**Comment by JohnDavidLarsen** [comment]
I have found that I can run rancher 2.0 on t2.micro if I don't use custom. I setup the server master on a micro, then I use the Amazon EC2 templates and set it to t2.micro  (t2.micro option did not exist previously, it does now).  Seems to work fine a bit slow. I left the AMI field blank it choose ami-927185ef for us-east-1

That said, it works best if you seperate controlplanes, etc, and workers as different nodes.
This of course will pass your Free 750 hours a month in a few days.
