### ISSUE TITLE
[Windows] Import docker-compose does not specify "network_mode", container will use NAT network by default

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#12060]
**Rancher versions:**
rancher/server: v1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 2016
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
ALL
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows

**Results:**
If you do not specify "network_mode: transparent" when importing docker-compose, the container uses NAT network by default.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
