### ISSUE TITLE
2.0 Feedback - IAM Role Rejected

### ISSUE THREAD

**Issue by ispyinternet** [rancher/rancher#12063]
**Rancher versions:**
rancher/server: Preview

I have an IAM Role (created by cloudformation): DevelopmentServer-DevelopmentServerRole-I1ROHVLK1XTL

But I'm unable to launch a cluster using it:

```
1 generic_controller.go:200] NodeController cluster-llmkh/m-2hrmq [node-controller] failed with : Error creating machine: Error in driver during machine creation: Error launching instance: InvalidParameterValue: Value (DevelopmentServer-DevelopmentServerRole-I1ROHVLK1XTL) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
```

Also must add, that while running through various mistakes and having to keep trying again, the issue of not being able to re-use Name Prefixes is quite annoying! Said error:

```
1 generic_controller.go:200] NodeController cluster-2wfkf/m-n6ng2 [node-controller] failed with : Error with pre-create check: "There is already a keypair with the name etcd1.  Please either remove that keypair or use a different machine name."
```

**Comment by deniseschannon** [comment]
The second error is actually a Docker Machine error, where Docker Machine doesnt' allow you to provision new nodes if a keypair already exists. 

But we should look into why you can't use a specific IAM role to launch a node using Amazon EC2.

**Comment by aiwantaozi** [comment]
Hi @ispyinternet , as noted in the AWS IAM documentation, you are running against the eventual consistency nature of the IAM service.
https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_general.html#troubleshoot_general_eventual-consistency

As a service that is accessed through computers in data centers around the world, IAM uses a distributed computing model called eventual consistency. Any change that you make in IAM (or other AWS services) takes time to become visible from all possible endpoints. Include the EC2.

**Comment by deniseschannon** [comment]
@soumyalj can you try launching an EC2 instance with a valid IAM profile?

**Comment by soumyalj** [comment]
Tested with master from March 22nd build. Launched EC2 instance with valid IAM template and created a custom cluster using the instance. Cluster creation was successful 
Also, created clusters using valid IAM node template. Cluster and workload creation succeeded fine.
<img width="1325" alt="screen shot 2018-03-22 at 1 45 52 pm" src="https://user-images.githubusercontent.com/18536626/37797559-632b9c4a-2dd7-11e8-8be1-2348461149f1.png">
