### ISSUE TITLE
The memory counter in the cluster view doesn't aggregate the total available memory

### ISSUE THREAD

**Issue by pipoe2h** [rancher/rancher#12062]
*Describe your issue here*

The "cluster view" doesn't aggregate the total available memory. The other counters like CPU and Pods are okay, but the memory one no.

If you take a look to the "nodes view" you can see the right resources per node.

![image](https://user-images.githubusercontent.com/17649319/37204676-13ccce3e-2392-11e8-9d2e-f58cccd1ec54.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha21` UI: `v2.0.25` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by pipoe2h** [comment]
Looks like once you have deployed the first workload, the counter is updated and it's showing now the total amount of memory.

PS. The previous counter is coming from a fresh installed 2.0

**Comment by alena1108** [comment]
Tried for GKE cluster on the latest master, couldn't reproduce. @pipoe2h what type of cluster have you used? 

@sangeethah @soumyalj could you keep an eye on this issue as you do a lot of cluster provisioning?

**Comment by pipoe2h** [comment]
This issue happens when you provision from the Rancher UI using the custom endpoint.

**Comment by soumyalj** [comment]
Tested with master from April 3rd. Created a custom cluster. Clusterview does aggregate the total available memory. [Note: There are no pods deployed on etcd node and it is not included in the total memory calculation]

<img width="1293" alt="screen shot 2018-04-03 at 11 31 32 am" src="https://user-images.githubusercontent.com/18536626/38268309-9e4db240-3732-11e8-8410-1a2acf68838c.png">
<img width="1246" alt="screen shot 2018-04-03 at 11 31 18 am" src="https://user-images.githubusercontent.com/18536626/38268318-a1e86c10-3732-11e8-9fa3-4143432f049b.png">
