### ISSUE TITLE
Wildcard Matching in URI Field Rancher LB (HaProxy).

### ISSUE THREAD

**Issue by parin921996** [rancher/rancher#12078]
**Rancher versions:**
rancher/server: v1.6.12
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
LoadBalancer : rancher/lb-service-haproxy:v0.7.15

**Docker version: (`docker version`,`docker info` preferred)**
Docker Version : 17.06.2

**Steps to Reproduce:**
Currently adding Wildcards or Regex in URI field for rancher LB are matched as String. So we can not route using `abc.com/uri1/*/updateinfo` .

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
