### ISSUE TITLE
catalog's with a forward slash in the name breaks functionality

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#12070]
**Rancher versions:**
rancher/server: v1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Steps to Reproduce:**
- add an environment specific catalog with a name containing a `/` 
- navigate to that catalog, no images load, cant deploy from catalog
- attempts to delete the catalog also fail

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by sorx00** [comment]
How I can remove broken catalog? Is there any workaround to solve the problem?
