### ISSUE TITLE
OTC and Softlayer don't have images for their node drivers

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12074]
**Rancher versions:** 2.0 master 3/11

**Steps to Reproduce:**
1.  Enable all node drivers
2.  Go to Add Templates

**Results:**  OTC and SoftLayer don't have images for their drivers
![image](https://user-images.githubusercontent.com/11514927/37266599-729ed6ae-2578-11e8-9bef-60266d67c0f6.png)

**Comment by loganhz** [comment]
Hi @lvuch , Can I have the icons for OTC and Softlayer, please?

**Comment by vincent99** [comment]
Needs to show the generic docker-machine icon when there's no specific one.  Users can add arbitrary other drivers, we can't have icons for all of them.

**Comment by tfiduccia** [comment]
The Generic image is good.  But can we please use the name of the driver instead of Generic for the text.  It's confusing if you have more than 1.
![image](https://user-images.githubusercontent.com/11514927/37626874-04b3b746-2b8f-11e8-92d3-21469593c4d2.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/21
Verified fixed
