### ISSUE TITLE
 Secure kubelet port by no longer allowing anonymous requests 

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12079]
Secure the kubelet port from unauthenticated access

Related:
https://github.com/rancher/rancher.github.io/pull/998
https://github.com/rancher/rke/issues/409
https://kubernetes.io/docs/admin/kubelet-authentication-authorization/

**Comment by moelsayed** [comment]
Tested with rc-6:
- Port 10250 access is restricted. This is the https endpoint for kubelet.
- Ports 10255 and 4194 are not restricted. There is no clear way in the docs to restrict access to them from kubelet side. 

I discussed this with @superseb, and he is trying to find a way to switch heapster to use the https endpoint and close 10255.

**Comment by deniseschannon** [comment]
Created a separate issue for the read only ports: https://github.com/rancher/rancher/issues/12142
