### ISSUE TITLE
Rancher routing breaks when rancher-agent stops on host (with healthchecks)

### ISSUE THREAD

**Issue by siosphere** [rancher/rancher#12072]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.12.0-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7 - 3.10.0-693.11.6.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher 3 server nodes, 3 agent nodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Spin up an HA Rancher environment, and create a web server service that runs on every host, with a healthcheck.
Kill the rancher-agent on one of the hosts.
Traffic is still attempted to be routed to the webserver service on the host where rancher-agent is not running anymore. This causes a lot of issues (timeout issues mainly)

**Results:**
When rancher-agent is no longer reporting on a node (such as if it crashed, or was stopped) even when the server has health-checks setup, traffic is still attempting to be routed to the failed host. I think this is due to the other infrastructure services still running properly on the host, just the rancher-agent node failed, however accessing the service leads to a timeout.

**Comment by vincent99** [comment]
The agent is not involved in the data plane into, between, or out of containers*.  The containers are still in rotation because they are still running and the healthchecks (which are not performed by the agent) are still passing.

*: Except logs/she'll through the

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
