### ISSUE TITLE
vultr node driver options don't show up.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12076]
**Rancher versions:** 2.0 master 3/11

**Steps to Reproduce:**
1.  Activate otc or add vultr machine drivers
2.  Go to add template and click on them

**Results:**  No options showing up

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/37270809-33d3491c-260b-11e8-9f82-ab7cf30a0ab7.png)

This is a backend issue. Current workaround is refreshing browser.

When I enabled a node driver, a `resource.change` event with type `dynamicSchema` will be sent to frontend. It should be `schema`.

Also in the resourceFields, the default value is `{defaultInt: null, defaultString '2'}` which is wrong. It should be `int`, `bool` or `string`.

**Comment by ArthurEth** [comment]
is this the same reason why enabling the openstack node-driver and trying to add an openstack node template shows up as blank?

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
