### ISSUE TITLE
Support for MariaDB 10.3

### ISSUE THREAD

**Issue by dzer** [rancher/rancher#12087]
Rancher versions:
rancher/server:stable

Results:
Reason: liquibase.exception.DatabaseException: Error executing SQL ALTER TABLE cattle.environment ADD system BIT NOT NULL DEFAULT 0: (conn:1331) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BIT NOT NULL DEFAULT 0' at line 1
Query is : ALTER TABLE cattle.environment ADD system BIT NOT NULL DEFAULT 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DBDiscoveryFactory': Unsatisfied dependency expressed through field 'discovery': Error creating bean with name 'DBDiscovery' defined in io.cattle.platform.app.SystemServicesConfig: Unsatisfied dependency expressed through method 'DBDiscovery' parameter 0: Error creating bean with name 'liquibaseCore' defined in io.cattle.platform.app.SystemConfig: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/core-100.xml::dump1::Rancher (generated):

Mariadb 10.3  ` system`  is reserved fields

**Comment by superseb** [comment]
Seems to be related to explicit use of `ADD COLUMN` vs just `ADD`. Have to check changelog of MariaDB 10.3 and check Liquibase.

10.3 is in beta at the moment, not suitable for use in production. Thanks for the heads-up, I can add some docs when it goes GA.

**Comment by ohze** [comment]
@superseb 10.3 is a [stable release now](https://mariadb.org/mariadb-10-3-7-now-available/)

**Comment by ToeiRei** [comment]
Same issue on
```
root@a1580bda6507:/# mysqld --version
/usr/sbin/mysqld  Ver 8.0.12 for Linux on x86_64 (MySQL Community Server - GPL)
```
just tried with mysql:latest

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
