### ISSUE TITLE
Wrong node count after cancel `Edit cluster` 

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12086]
**Rancher versions:**
rancher/server:master 03/13

**Steps to Reproduce:**
1. Go to the Nodes tag, click "Edit Cluster".
2. Increase the node count for the node pool from 1 to 2.
3. Click Cancel button.
4. UI shows the node count is 2. If go to "Edit Cluster" page, the node count is also 2.

**Results:**
![image](https://user-images.githubusercontent.com/1213386/37326477-49f08648-26cd-11e8-8cfc-073f07d25e48.png)
![image](https://user-images.githubusercontent.com/1213386/37326483-50694e6a-26cd-11e8-8c94-421d002a84eb.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Verified fixed
