### ISSUE TITLE
waiting for etcd and controlplane nodes to be registered

### ISSUE THREAD

**Issue by Justluckyg** [rancher/rancher#12088]
Im getting the error below when trying to create a custom cluster.
`

waiting for etcd and controlplane nodes to be registered
--

`

Server: ubuntu 16.04
Client: same

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `dev` UI: `v2.0.26` |
|Access|`local` |
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
Can you share the complete logging from the `rancher/server` container?

**Comment by Justluckyg** [comment]
hi @superseb 

Here:

`E0313 12:24:29.649075       1 generic_controller.go:200] ProjectController cluster-sv25x/project-mkhh7 [mgmt-project-rbac-remove] failed with : Operation cannot be fulfilled on projects.management.cattle.io "project-mkhh7": the object has been modified; please apply your changes to the latest version and try again
E0313 12:24:29.672010       1 generic_controller.go:200] ClusterRoleTemplateBindingController cluster-sv25x/creator [mgmt-auth-crtb-controller] failed with : couldn't create role cluster-owner: roles.rbac.authorization.k8s.io "cluster-owner" already exists
E0313 12:24:29.672816       1 generic_controller.go:200] ProjectController cluster-sv25x/project-mkhh7 [mgmt-project-rbac-remove] failed with : Operation cannot be fulfilled on projects.management.cattle.io "project-mkhh7": the object has been modified; please apply your changes to the latest version and try again
E0313 12:24:29.674055       1 generic_controller.go:200] ClusterController cluster-sv25x [cluster-provisioner-controller] failed with : Operation cannot be fulfilled on clusters.management.cattle.io "cluster-sv25x": the object has been modified; please apply your changes to the latest version and try again, [cluster-agent-controller] failed with : Operation cannot be fulfilled on clusters.management.cattle.io "cluster-sv25x": the object has been modified; please apply your changes to the latest version and try again
E0313 12:24:29.699285       1 generic_controller.go:200] ClusterRoleTemplateBindingController cluster-sv25x/creator [mgmt-auth-crtb-controller] failed with : Operation cannot be fulfilled on roles.rbac.authorization.k8s.io "cluster-owner": the object has been modified; please apply your changes to the latest version and try again
E0313 12:24:29.702982       1 generic_controller.go:200] ProjectRoleTemplateBindingController project-mkhh7/creator [mgmt-auth-prtb-controller] failed with : Operation cannot be fulfilled on projectroletemplatebindings.management.cattle.io "creator": the object has been modified; please apply your changes to the latest version and try again
E0313 12:24:29.704629       1 generic_controller.go:200] ClusterController cluster-sv25x [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered, [cluster-stats] failed with : Operation cannot be fulfilled on clusters.management.cattle.io "cluster-sv25x": the object has been modified; please apply your changes to the latest version and try again
E0313 12:24:29.706718       1 generic_controller.go:200] ClusterController cluster-sv25x [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered, [cluster-stats] failed with : Operation cannot be fulfilled on clusters.management.cattle.io "cluster-sv25x": the object has been modified; please apply your changes to the latest version and try again
2018/03/13 12:24:29 [INFO] ClusterController cluster-sv25x completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
2018/03/13 12:24:30 [INFO] ClusterController cluster-sv25x completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
2018-03-13 12:31:40.854942 I | mvcc: store.index: compact 2650
2018-03-13 12:31:40.987719 I | mvcc: finished scheduled compaction at 2650 (took 131.352975ms)
2018-03-13 12:36:40.860258 I | mvcc: store.index: compact 3101
2018-03-13 12:36:40.863109 I | mvcc: finished scheduled compaction at 3101 (took 1.501934ms)
2018-03-13 12:41:40.865636 I | mvcc: store.index: compact 3552
2018-03-13 12:41:40.868355 I | mvcc: finished scheduled compaction at 3552 (took 1.312172ms)`

**Comment by superseb** [comment]
I need the complete logging, at least the part where the node was added to see what part of the provisioning went right and what went wrong.

**Comment by superseb** [comment]
Thanks, it does not seem that the node you are trying to add is able to reach the rancher/server container. What is the logging of the `rancher/agent` container on the host you are trying to add?

**Comment by Justluckyg** [comment]
@superseb 
Here from the client:

`
ERROR: https://172.16.100.9/v3/settings/cacerts does not match b7f8226da43af99d08a1ff068d563abd7ec56e48ee930b65613565de738c173a
`

**Comment by superseb** [comment]
Hmm, this should be good out of the box. Do you have a loadbalancer/proxy with SSL/TLS termination or are you bind mounting certs into the `rancher/server` container?

If not, can you check that you correctly copy-pasted the command from the UI?

**Comment by Justluckyg** [comment]
I didnt do anything of sort. I used the command from rancher's quick start up for the server and for the client I used the docker run command given when creating the cluster from web ui. @superseb

**Comment by superseb** [comment]
Ok, can you share what command you used? It should be

```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview
```

And possibly `docker pull rancher/server:preview` as your reported version seems to be `dev` and it should say `v2.0.0-alpha21`. 

Otherwise, use

```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:v2.0.0-alpha21
```

**Comment by Justluckyg** [comment]
@superseb i used `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview`

But i also tried other tags available in the dockerhub, i tried latest, v1.6.12 etc...

**Comment by arthurzinck** [comment]
same here :+1:

**Comment by superseb** [comment]
Running `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview` or `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:v2.0.0-alpha21` should say `v2.0.0-alpha21` in the bottom left. 

Then for debugging the cert issue, you can see what is being returned when you exec into the container that is ran on the host that you want to add.

```
# First, to see if what gets returned here (should start with `-----BEGIN CERTIFICATE-----`):
curl --insecure -s -fL https://172.16.100.9/v3/settings/cacerts | jq -r .value

# Then the checksum
curl --insecure -s -fL https://172.16.100.9/v3/settings/cacerts | jq -r .value | sha256sum  | awk '{print $1}'
```

**Comment by arthurzinck** [comment]
Yes I am getting : 
```bash
root@worker1:/# curl --insecure -s -fL https://192.168.99.1/v3/settings/cacerts | jq -r .value
-----BEGIN CERTIFICATE-----
MIIC7jCCAdagAwIBAgIBADANBgkqhkiG9w0BAQsFADAoMRIwEAYDVQQKEwl0aGUt
cmFuY2gxEjAQBgNVBAMTCWNhdHRsZS1jYTAeFw0xODAzMTIxMzUyMTNaFw0yODAz
MDkxMzUyMTNaMCgxEjAQBgNVBAoTCXRoZS1yYW5jaDESMBAGA1UEAxMJY2F0dGxl
LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1gVb4BRbrnJm+L1G
8BdWHSvs7bnnCAlwOl1H5iEHpZ8JZ9+4MOfycBg6RFmDOE2nFNeTtmuBSQA67tZE
RvGW5ddh1E2rXIRe7t7t3694kohxWhprVZBAbsnIoa+v1EvtYaJCGQPUwZLkI6D6
sUeknGU/kufATfd4+BiWD5l053r7eA6yTXl6llm5gMpE6RTKysYChwDafl1eUeRs
FHY78QcEbJm8PJskasZywfrhTeqmOjP2kwXrsRyxo3oiP4MScgMcFEUf01BklptT
Rjm0J9n9w00g8dySuh9bwdyOm+ucz1sqAicId810Hwi3joC+fsefkFsuoN7ICANM
32zP5QIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAN
BgkqhkiG9w0BAQsFAAOCAQEAg7d1VzW09PODhsq2Ze+OTy6iDAgTGKI/xxUu9bck
Cf5ey5eSNuTzf5TfYJ49Zy/N36nt9qrrQxWES1E91Il0NWD4McZCynZiImdDBe3f
klIs+CPuEoMIibx84z7Z0qwPpZysUNpXVCzC0EHfb87m6PEU51MTpR+bpDa0Jsm9
0CImCDC8OrK2e6wO3moMvcED1nKLY1j8isnu7773PkxA9q2cFi/LayhiHZp68LWu
UEODG5Uf7D5c5zL9L+MoPiCvLteN99yGwgN+d4WobmX/H/cWg+X7mmThG3OX1097
EAN7AYUHLLdYBG598rPWSdY3/f9fklkJBTQUdU2FO5s2FQ==
-----END CERTIFICATE-----
root@worker1:/# curl --insecure -s -fL https://192.168.99.1/v3/settings/cacerts | jq -r .value | sha256sum  | awk '{print $1}'
43d795ff172df682b615b462cc68f75a85c390c17655946fe5f7cd9a67069e45
```
But it is the same 
```bash
docker run -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock --net=host rancher/agent:v2.0.3 --server https://192.168.99.1 --token v6bwcqslffzf6w4rjmgkx7869f5x9wxn2kbmrxnchq2s2mprjrw7qd --ca-checksum 43d795ff172df682b615b462cc68f75a85c390c17655946fe5f7cd9a67069e45 --worker```

**Comment by StrongMonkey** [comment]
@arthurzinck from your command you only have one node registered as worker.You might need to check etcd and control plane boxes when you copy and paste docker run command.

**Comment by deniseschannon** [comment]
You need to make sure you check off for etcd and control plane when adding custom hosts if it's the first one.

**Comment by Justluckyg** [comment]
this is my logs on the rancher server:
http://pasteall.org/874140/bash

this is what i executed in client:
`root@ip-172-16-100-6:/home/ubuntu# docker run -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock --net=host rancher/agent:v2.0.3 --server https://172.16.100.4 --token 49cc7nvlvpzzztvthrqpcxvrw24pznb4vv5f8fk7btmxrznh9gb748 --ca-checksum 6d0fced96e457fd5c64a49d0576363109bc9b4e3f5ee15e81fe1a1f3d46fa7c3 --etcd --controlplane --worker`

@superseb @deniseschannon

**Comment by Justluckyg** [comment]
ill close out this issue as im able to resolve the problem already, thanks!

**Comment by ipochi** [comment]
@Justluckyg what was your resolution ?
I am getting the same error message for ec2 instances , creating a cluster from web-ui
I have 1 master node for control plane and etcd
3 worker nodes.

**Comment by chauhanr** [comment]
I am getting the same issue @Justluckyg can you please share how did you resolve the issue

**Comment by potter-the-cat** [comment]
In the *Cluster* area, you can add a new Node. If you click on `Nodes` you can then add a machine. Checking the boxes for `etcd` and `control` when in the Cluster > Node area resolved this issue for me.

**Comment by avestuk** [comment]
@chauhanr @sofiane-soufi  I got this error when I attempted to add a cluster and didn't run the displayed command on my node before clicking done. You need to run the command that Rancher generates on the nodes in the cluster. 

![image](https://user-images.githubusercontent.com/28152118/40980683-f5cbc87a-68d0-11e8-84e3-56485235ca00.png)

**Comment by leetskil** [comment]
does not work for me either 

docker version: 17.03.2-ce
ubuntu 16.04 
rancher 2.0 (stable version)

**Comment by joehoeller** [comment]
I just get this:
```
docker logs 672662bd1a38
INFO: Arguments: --server https://localhost --token REDACTED --ca-checksum e0c3ef324b82a58eabb0799ab339deb85a88a4096790ae4afb86ebd0961f7397 --etcd --controlplane --worker
INFO: Environment: CATTLE_ADDRESS=192.168.0.16 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=thebeast CATTLE_ROLE=,etcd,worker,controlplane CATTLE_SERVER=https://localhost CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 208.59.247.45 nameserver 208.59.247.46
INFO: https://localhost/ping is accessible
INFO: localhost resolves to 127.0.0.1
INFO: Value from https://localhost/v3/settings/cacerts is an x509 certificate
time="2020-02-23T17:38:12Z" level=info msg="Rancher agent version v2.3.5 is starting"
time="2020-02-23T17:38:12Z" level=info msg="Option customConfig=map[address:192.168.0.16 internalAddress: label:map[] roles:[etcd worker controlplane] taints:[]]"
time="2020-02-23T17:38:12Z" level=info msg="Option etcd=true"
time="2020-02-23T17:38:12Z" level=info msg="Option controlPlane=true"
time="2020-02-23T17:38:12Z" level=info msg="Option worker=true"
time="2020-02-23T17:38:12Z" level=info msg="Option requestedHostname=thebeast"
time="2020-02-23T17:38:12Z" level=info msg="Listening on /tmp/log.sock"
time="2020-02-23T17:38:12Z" level=info msg="Connecting to wss://localhost/v3/connect/register with token fn2bv47q7sstg92ts9d24rjxg47hjbjl8b9kxhjmpkw6h4w8z9s6pv"
time="2020-02-23T17:38:12Z" level=info msg="Connecting to proxy" url="wss://localhost/v3/connect/register"
time="2020-02-23T17:38:12Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
```

**Comment by joehoeller** [comment]
I cherry picked the Docker Logs so it wouldnt be some massive thread:

```
2020/02/25 03:05:09 [ERROR] ProjectRoleTemplateBindingController p-zh248/creator-project-owner [mgmt-auth-prtb-controller] failed with : clusterroles.rbac.authorization.k8s.io "c-xbsfg-clustermember" already exists
```

```
67 resource_quota_controller.go:437] failed to sync resource monitors: [couldn't start monitor for resource "management.cattle.io/v3, Resource=projectalertgroups": unable to monitor quota for resource "management.cattle.io/v3, Resource=projectalertgroups", couldn't start monitor for resource "management.cattle.io/v3, Resource=clusterroletemplatebindings": unable to monitor quota for resource "management.cattle.io/v3, Resource=clusterroletemplatebindings", couldn't start monitor for resource "project.cattle.io/v3, Resource=apps": unable to monitor quota for resource "project.cattle.io/v3, Resource=apps", couldn't start monitor for resource "project.cattle.io/v3, Resource=apprevisions":
```

```
E0225 03:01:57.372323      67 prometheus.go:138] failed to register depth metric certificate: duplicate metrics collector registration attempted
E0225 03:01:57.372356      67 prometheus.go:150] failed to register adds metric certificate: duplicate metrics collector registration attempted
E0225 03:01:57.372412      67 prometheus.go:162] failed to register latency metric certificate: duplicate metrics collector registration attempted
E0225 03:01:57.372461      67 prometheus.go:174] failed to register work_duration metric certificate: duplicate metrics collector registration attempted
E0225 03:01:57.372497      67 prometheus.go:189] failed to register unfinished_work_seconds metric certificate: duplicate metrics collector registration attempted
E0225 03:01:57.372523      67 prometheus.go:202] failed to register longest_running_processor_microseconds metric certificate: duplicate metrics collector registration attempted
E0225 03:01:57.372570      67 prometheus.go:214] failed to register retries metric certificate: duplicate metrics collector registration attempted
E0225 03:01:57.375591      67 resource_quota_controller.go:437] failed to sync resource monitors: [couldn't start monitor for resource "helm.cattle.io/v1, Resource=helmcharts": unable to monitor quota for resource "helm.cattle.io/v1, Resource=helmcharts", couldn't start monitor for resource "management.cattle.io/v3,
```

```
2020/02/25 03:01:55 [ERROR] SettingController rke-metadata-config [rke-metadata-handler] failed with : namespaces "cattle-global-data" not found
```

```
time="2020-02-25T03:01:42.679753595Z" level=info msg="Starting helm.cattle.io/v1, Kind=HelmChart controller"
2020/02/25 03:01:42 [INFO] Creating CRD sourcecodeproviderconfigs.project.cattle.io
W0225 03:01:42.923499      67 lease.go:222] Resetting endpoints for master service "kubernetes" to [172.17.0.2]
2020/02/25 03:01:42 [INFO] Creating CRD clusteralertrules.management.cattle.io
2020/02/25 03:01:43 http: TLS handshake error from 127.0.0.1:43902: EOF
2020/02/25 03:01:43 http: TLS handshake error from 127.0.0.1:43898: EOF
2020/02/25 03:01:43 http: TLS handshake error from 127.0.0.1:43900: EOF
2020/02/25 03:01:43 http: TLS handshake error from 127.0.0.1:43916: EOF
```

```
67 prometheus.go:138] failed to register depth metric helm.cattle.io/v1, Kind=HelmChart: descriptor Desc{fqName: "helm.cattle.io/v1, Kind=HelmChart_depth", help: "(Deprecated) Current depth of workqueue: helm.cattle.io/v1, Kind=HelmChart", constLabels: {}, variableLabels: []} is invalid: "helm.cattle.io/v1, Kind=HelmChart_depth" is not a valid metric name
```

```
67 prometheus.go:202] failed to register longest_running_processor_microseconds metric k3s.cattle.io/v1, Kind=ListenerConfig: descriptor Desc{fqName: "k3s.cattle.io/v1, Kind=ListenerConfig_longest_running_processor_microseconds", help: "(Deprecated) How many microseconds has the longest running processor for k3s.cattle.io/v1, Kind=ListenerConfig been running.", constLabels: {}, variableLabels: []} is invalid: "k3s.cattle.io/v1, Kind=ListenerConfig_longest_running_processor_microseconds" is not a valid metric name
E0225 03:01:41.064526      67 prometheus.go:214] failed to register retries metric k3s.cattle.io/v1, Kind=ListenerConfig: descriptor Desc{fqName: "k3s.cattle.io/v1, Kind=ListenerConfig_retries", help: "(Deprecated) Total number of retries handled by workqueue: k3s.cattle.io/v1, Kind=ListenerConfig", constLabels: {}, variableLabels: []} is invalid: "k3s.cattle.io/v1, Kind=ListenerConfig_retries" is not a valid metric name
time="2020-02-25T03:01:41.565234922Z" level=info msg="Starting k3s.cattle.io/v1, Kind=Addon controller"
time="2020-02-25T03:01:41.665492553Z" level=info msg="Starting k3s.cattle.io/v1, Kind=ListenerConfig controller"
time="2020-02-25T03:01:41.665571141Z" level=error msg="Update cert unable to convert string to cert: Unable to split cert into two parts"
time="2020-02-25T03:01:41.665952376Z" level=info msg="Node token is available at /var/lib/rancher/k3s/server/node-token"
time="2020-02-25T03:01:41.665972614Z" level=info msg="To join node to cluster: k3s agent -s https://172.17.0.2:6443 -t ${NODE_TOKEN}"
```

```
2020/02/25 03:02:57 http: TLS handshake error from 127.0.0.1:44706: EOF
2020/02/25 03:02:57 [INFO] Catalog-cache removed 2 entries from disk
```


```
2020/02/25 03:01:36 [INFO] Listening on /tmp/log.sock
2020/02/25 03:01:36 [INFO] Running etcd --data-dir=management-state/etcd
2020-02-25 03:01:36.722970 W | pkg/flags: unrecognized environment variable ETCD_URL_arm64=https://github.com/etcd-io/etcd/releases/download/v3.3.14/etcd-v3.3.14-linux-arm64.tar.gz
2020-02-25 03:01:36.723003 W | pkg/flags: unrecognized environment variable ETCD_URL_amd64=https://github.com/etcd-io/etcd/releases/download/v3.3.14/etcd-v3.3.14-linux-amd64.tar.gz
2020-02-25 03:01:36.723008 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=amd64
2020-02-25 03:01:36.723013 W | pkg/flags: unrecognized environment variable ETCD_URL=ETCD_URL_amd64
```

**Comment by gp187** [comment]
+1 Please open issue

**Comment by sadhugit** [comment]
> Does anyone know the fix? I just get this:
> **_Rancher UI:_**
> ![Screenshot from 2020-02-23 12-21-46](https://user-images.githubusercontent.com/5199900/75117457-20b2cc00-5637-11ea-8a8d-0744296ecf3d.png)
> 
> **_Docker Logs:_**
> 
> ```
> docker logs 672662bd1a38
> INFO: Arguments: --server https://localhost --token REDACTED --ca-checksum e0c3ef324b82a58eabb0799ab339deb85a88a4096790ae4afb86ebd0961f7397 --etcd --controlplane --worker
> INFO: Environment: CATTLE_ADDRESS=192.168.0.16 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=thebeast CATTLE_ROLE=,etcd,worker,controlplane CATTLE_SERVER=https://localhost CATTLE_TOKEN=REDACTED
> INFO: Using resolv.conf: nameserver 208.59.247.45 nameserver 208.59.247.46
> INFO: https://localhost/ping is accessible
> INFO: localhost resolves to 127.0.0.1
> INFO: Value from https://localhost/v3/settings/cacerts is an x509 certificate
> time="2020-02-23T17:38:12Z" level=info msg="Rancher agent version v2.3.5 is starting"
> time="2020-02-23T17:38:12Z" level=info msg="Option customConfig=map[address:192.168.0.16 internalAddress: label:map[] roles:[etcd worker controlplane] taints:[]]"
> time="2020-02-23T17:38:12Z" level=info msg="Option etcd=true"
> time="2020-02-23T17:38:12Z" level=info msg="Option controlPlane=true"
> time="2020-02-23T17:38:12Z" level=info msg="Option worker=true"
> time="2020-02-23T17:38:12Z" level=info msg="Option requestedHostname=thebeast"
> time="2020-02-23T17:38:12Z" level=info msg="Listening on /tmp/log.sock"
> time="2020-02-23T17:38:12Z" level=info msg="Connecting to wss://localhost/v3/connect/register with token fn2bv47q7sstg92ts9d24rjxg47hjbjl8b9kxhjmpkw6h4w8z9s6pv"
> time="2020-02-23T17:38:12Z" level=info msg="Connecting to proxy" url="wss://localhost/v3/connect/register"
> time="2020-02-23T17:38:12Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
> ```

 you need to   follow below steps:
1 Edit the cluster and select the etc,controlplane and workernode  
2. Copy the Command  displayed in  that page which is like " sudo docker run -d --privileged --restart=unless-stopped --net=host -v  ........ --etcd --controlplane --worker "
3.Login to your node 
4. Run the above copied  command and  go  the Rancher edit cluster page  and click on "Save" button

**Comment by joehoeller** [comment]
you have to expose the host to the k8 cluster, and check etcd and control plane in gui prior to deployment.

**Comment by cky-thinker** [comment]
if first create clusters,you should choose all roles: etcd  controlplane worker
![image](https://user-images.githubusercontent.com/19356170/120165129-d652ce80-c22d-11eb-8983-101c3079d131.png)

generated command like:
"xxxx --etcd --controlplane --worker"

it's work for me
