### ISSUE TITLE
Upgrading with new healthcheck gets existing containers to unhealthy state since the new health check configs get applied to existing containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12080]
**Rancher versions: Build from 1.6 branch

Steps to reproduce the problem:

1. Create a stack with a service running nginx with a healthcheck on port 80.
2. Upgrade service with Start before Stopping selected and break the healthcheck (change to port 81)

Existing containers get to "unhealthy" state since the new incorrect healthcheck configs seems to be get applied to them.

Expected behavior:
Existing containers should continue to remain "healthy" state .

**Comment by alena1108** [comment]
The issue is applicable to any upgrade; not just when start before stopping is used.

**Comment by sangeethah** [comment]
Tested with latest build from 1.6 branch and health check version - rancher/healthcheck:v0.3.4

**Comment by sangeethah** [comment]
Tested with v1.6.15-rc6.
Upgrading with new health check parameters (incorrect) does not result in existing containers to get unhealthy state anymore.
