### ISSUE TITLE
Adding a health check - can not save workload

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#12081]
**Rancher versions:**
rancher/server: v2.0.0-alpha21
rancher/agent: v2.0.3

**Infrastructure Stack versions:**
kubernetes (if applicable): RKE - custom nodes

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4
4.13.0-1011-azure

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**Steps to Reproduce:**
- Create a workload in a brand-new project and namespace
- **Add a healthcheck:** `HTTP request returns a successful status (2xx or 3xx)`
- Hit "Save"

**Results:**
"Saving" spins indefinitely and never actually saves. Nothing appears in the Rancher server logs.

**Expected Results**
Should save the workload.

This only happens if a Healthcheck is added.
All other settings being equal, without the healthcheck, the workload is saved as expected.

**Comment by vincent99** [comment]
Fixed in master already, if you add a separate liveness check it will work for now.
