### ISSUE TITLE
When api keys for SA of region is disabled , all existing environment links to this region gets removed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12082]
**Rancher versions: Server build from 1.6 branch

**Steps to Reproduce:**
Region1 - with 3 environments - test1region1, test2region1, test3region1
Region2 - with 3 environments - test1region2, test2region2, test3region2

LB in test1region1 linked to targets in  test1region2
Instance in test2region1 linked to instances in  test2region2
LB and instances work as expected.
Deactivate SA keys for region1

Try to create LB in test3region1 linked to targets in   test3region2

LB gets created successfully . But it is not able to reach targets in region2 since there is no link created from test3region2 to test3region1. This is as expected.

But I also see that the previously created LB and links cross regions stop working.
This is because of the links between test2region2 to test2region1 and test1region2 to test1region1 is removed. This link is needed for network policy to allow for traffic cross region.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
