### ISSUE TITLE
Offer rke v1.9.x in Rancher

### ISSUE THREAD

**Issue by smiller171** [rancher/rancher#12091]
Please add support for RKE v1.9.x. I want to be able to spin up 1.9.x kubernetes clusters. RKE supports it, but it doesn't appear to be supported in the Rancher 2.0 preview.

**Rancher versions:**
rancher/server: v2.0.0-alpha21
rancher/agent: v2.0.3

**Comment by deniseschannon** [comment]
Rancher 2.0 will support 1.9.x after Beta is released. There are some breaking API changes that require work in Rancher 2.0 to get it fixed, but its' on our roadmap before GA.

**Comment by alena1108** [comment]
We are going to split things into 2 independent stages:

1) enable 1.9 version for clusters rancher provisions.
2) update k8s dependency from 1.8 to 1.9 for rancher/types/norman/rke.

**Comment by alena1108** [comment]
@sangeethah could you validate the first part of the issue? Make sure 1.9 can be picked as an option for rke cluster, and k8s 1.9 version gets deployed, and things like workload work on it?

And once validated, pass it back to me; will get it to fully resolved once we agree on a timing to switch to k8s 1.9 as a vendor too.

**Comment by soumyalj** [comment]
Tested with master. Launched RKE clusters clusters with K8s v1.9.4-rancher1-1 and v1.9.5-rancher1-1  successfully. Creation of workloads in the clusters also worked fine.

**Comment by alena1108** [comment]
Created a separate issue for tracking rancher code base k8s vendor update https://github.com/rancher/rancher/issues/12335; closing this issue as rke 1.9 provisioning part was verified.
