### ISSUE TITLE
Healthcheck, Scheduler and IPSec services are all stuck in "initializing" state

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#12094]
**Rancher versions:**
rancher/server: v1.6.15-rc1
rancher/agent:

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Rancher OS  v1.1.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Create rancher/server, register the host
- Delete rancher/server, delete all containers on the host
- Create rancher/server again, reregister the same host again
- All the above mentioned infra stacks are stuck in "initializing"

**Results:**
- All the infra stacks should be active and green.

**Comment by kinarashah** [comment]
#12095

**Comment by leodotcloud** [comment]
Closing this in favor of https://github.com/rancher/rancher/issues/12094
