### ISSUE TITLE
Rancher `v1.6.14` Cattle

### ISSUE THREAD

**Issue by icarobdo** [rancher/rancher#12092]
*Describe your issue here*

221/5000
Dear, I'm using version 1.6.14 of the rancher and after uploading some containers in different stacks, the hosts are not subdividing the stacks as they were in previous versions. Anyone else with the same problem?
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`host.containers`|

**Comment by loganhz** [comment]
It looks good in v1.6.22

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
