### ISSUE TITLE
Schema of custom node driver can not be registered successfully

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#12102]
rancher/server: master 13/03

The node driver added through API or UI is not working.
The driver schema can not be registered to `schema` correctly.

We have to added the node driver in rancher server source code to make it work.

https://github.com/rancher/rancher/blob/master/app/machinedriver_data.go

**Comment by aiwantaozi** [comment]
Related fix PR: https://github.com/rancher/rancher/pull/12213

I use aliyun driver to test:
https://docker-machine-drivers.oss-cn-beijing.aliyuncs.com/docker-machine-driver-aliyunecs_linux-amd64.tgz, it could add schema to path "/v3/schemas/aliyunecs.linux-amd64config", is this OK for UI. 

Note: vultr machine driver have another issue cause it fail to add, please do not use it to test is issue,
https://github.com/janeczku/docker-machine-vultr/releases/download/v1.4.0/docker-machine-driver-vultr-Linux-x86_64

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
