### ISSUE TITLE
[Feature Request] Add the ability to prepend Custom Registry on agents

### ISSUE THREAD

**Issue by furkilic** [rancher/rancher#12105]
Whenever you add a host on Rancher, add the ability to specify a custom registry which will be prepend to every image pulled from the agent.

Exemple :
My registry is myregistry.com
Add a env variable like PREPEND_CUSTOM_REGISTRY whenever we register a host:
- sudo docker run ... -e PREPEND_CUSTOM_REGISTRY=myregistry.com ... rancher/agent:xyz
Whenever agent need to pull an image, rancher/healthcheck:xyz for example,  it will pull myregistry.com/rancher/healthcheck:xyz

Thanks in advance

Furkilic

**Comment by superseb** [comment]
This is already present and documented here: http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/no-internet-access/#using-a-private-registry

Let me know if that doesn't work for you.

**Comment by furkilic** [comment]
Wanted the feature at the agent level not server level. 

But still I guess your solution will work for most cases. 

Thanks a lot.
