### ISSUE TITLE
[windows] Run 'rancher --host 1h13 docker ps' to get wrong result

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#12100]
**Rancher versions:**
rancher/server: v1.6.14
rancher/cli: v0.6.8-rc4

**Docker version: (`docker version`,`docker info` preferred)**
```
PS C:\Users\Administrator> docker version
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
windows 2016
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
windows
**Steps to Reproduce:**

**Results:**
I have a windows environment and I want to execute some docker commands with rancher CLI. Unfortunately, it failed
Here is my operation record
```
root@ip-172-31-35-76:~/rancher-v0.6.8-rc4# ./rancher hosts
ID        HOSTNAME          STATE     CONTAINERS   IP               LABELS    DETAIL
1h13      EC2AMAZ-SOK7AM2   active    2            x.x.x.x

root@ip-172-31-35-76:~/rancher-v0.6.8-rc4# ./rancher --host 1h13 docker ps
error during connect: Get http://%2Ftmp%2Fdocker-sock470415277/v1.18/containers/json: EOF
```

**Comment by orangedeng** [comment]
Windows server has supported docker since v1.12.2 and docker api version since v1.24.
And the Rancher CLI Use a trick to get the docker api version from with docker version which `12` of v1.12.2 plus 12 to `24` of v1.24. 
When it comes to Docker CE and EE, v1.12.2 become 17.06 and the api version is not equal to v1.30 as 17.06 api version.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
