### ISSUE TITLE
Kubernetes cluster without requestheader-client-ca-file

### ISSUE THREAD

**Issue by giovannicandido** [rancher/rancher#12111]
**Rancher versions:**
rancher/server: 1.6.x
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.8

**Docker version: (`docker version`,`docker info` preferred)**

17.03-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Virtual Machines

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes 
Rancher lb disabled
RBAC enabled

**Steps to Reproduce:**

I'm trying to deploy ha proxy Ingress voyeger https://appscode.com/products/voyager/

Installed using helm:

```
helm install stable/voyager --name voyager-operator --namespace kube-system
```

**Results:**

Pod fail to deploy with log:

> Error: cluster doesn't provide requestheader-client-ca-file

The information I found about are:

Minikube discussion: https://github.com/kubernetes/minikube/issues/1404

https://v1-8.docs.kubernetes.io/docs/reference/generated/kube-apiserver/

But I don't fully understand way this is necessary, something related with security.

What can be done in rancher installation, and how to set this flag?

**Comment by pdiaz** [comment]
Having same issue on rancher 1.6.16 with Kubernetes 1.9.5

**Comment by mauri870** [comment]
Having a similiar problem when deploying the [kubernetes-incubator/metrics-server](https://github.com/kubernetes-incubator/metrics-server).

I'm using rancher 1.6.17 and kubernetes 1.10.

Solved upgrading the kubernetes service under `Infraestructure Stacks > Kubernetes` with the aditional flag `--requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem` in the kube-apiserver command.

**Comment by kfiles** [comment]
@mauri870 Could you please explain more how you added args to the apiserver using the template? Using Rancher 1.6.20 and the latest Kubernetes template (1.11.1-rancher1-3-1), I don't see any config field for the kube-api-server. The only field in the template I see for adding args is the "Additional Kubelet Flags" field, which won't help me as it doesn't apply to the API server.

**Comment by dangpf** [comment]
@mauri870 I have the same problem,Rancher 1.6.21 and k8s 1.10.5, I don't see any config field for the kube-apiserver,Can't find where to add flag `--requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem`

**Comment by mauri870** [comment]
@dangpf Upgrade the kubernetes service and append the flag in the `command` field.

![screenshot_1538049146](https://user-images.githubusercontent.com/10168637/46144253-c1c70880-c232-11e8-9905-439a9227409f.png)

**Comment by dangpf** [comment]
@mauri870 Thank you very much, the problem has been solved.

**Comment by deniseschannon** [comment]
In the catalog template, we will add a field to introduce additional args to the `kube-api-server` like we do for the kubelet.

**Comment by dangpf** [comment]
@mauri870 hello, I have installed the service catalog,One of the apiserver container logs is reporting an error
![image](https://user-images.githubusercontent.com/13655991/46932229-4ada9e00-d081-11e8-9cb3-9509272faf01.png)
![image](https://user-images.githubusercontent.com/13655991/46932305-b58bd980-d081-11e8-8a7c-c313de511d12.png)
`2018/10/15 下午1:54:01I1015 05:54:01.224393       1 round_trippers.go:405] POST https://10.43.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews 201 Created in 14 milliseconds
2018/10/15 下午1:54:01I1015 05:54:01.224476       1 round_trippers.go:411] Response Headers:
2018/10/15 下午1:54:01I1015 05:54:01.224497       1 round_trippers.go:414]     Content-Type: application/json
2018/10/15 下午1:54:01I1015 05:54:01.224517       1 round_trippers.go:414]     Content-Length: 427
2018/10/15 下午1:54:01I1015 05:54:01.224537       1 round_trippers.go:414]     Date: Mon, 15 Oct 2018 05:54:01 GMT
2018/10/15 下午1:54:01I1015 05:54:01.226762       1 request.go:897] Response Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"nonResourceAttributes":{"path":"/apis/servicecatalog.k8s.io/v1beta1","verb":"get"},"user":"system:anonymous","group":["system:unauthenticated"]},"status":{"allowed":true,"reason":"allowed by ClusterRoleBinding \"system:discovery\" of ClusterRole \"system:discovery\" to Group \"system:unauthenticated\""}}
2018/10/15 下午1:54:01I1015 05:54:01.226884       1 handler.go:143] service-catalog-apiserver: GET "/apis/servicecatalog.k8s.io/v1beta1" satisfied by gorestful with webservice /apis/servicecatalog.k8s.io/v1beta1
2018/10/15 下午1:54:01I1015 05:54:01.227059       1 wrap.go:42] GET /apis/servicecatalog.k8s.io/v1beta1?timeout=32s: (17.575607ms) 200 [[service-catalog/v0.1.33 (linux/amd64) kubernetes/621d4e2/service-catalog-controller-discovery] 10.42.204.33:43526]
2018/10/15 下午1:54:01I1015 05:54:01.305924       1 authorization.go:73] Forbidden: "/apis/servicecatalog.k8s.io/v1beta1/servicebrokers?limit=500&resourceVersion=0", Reason: ""
2018/10/15 下午1:54:01I1015 05:54:01.305976       1 wrap.go:42] GET /apis/servicecatalog.k8s.io/v1beta1/servicebrokers?limit=500&resourceVersion=0: (170.719μs) 403 [[service-catalog/v0.1.33 (linux/amd64) kubernetes/621d4e2/shared-informers] 10.42.204.33:43526]
2018/10/15 下午1:54:01I1015 05:54:01.507577       1 authorization.go:73] Forbidden: "/apis/servicecatalog.k8s.io/v1beta1/serviceclasses?limit=500&resourceVersion=0", Reason: ""
2018/10/15 下午1:54:01I1015 05:54:01.507647       1 wrap.go:42] GET /apis/servicecatalog.k8s.io/v1beta1/serviceclasses?limit=500&resourceVersion=0: (223.003μs) 403 [[service-catalog/v0.1.33 (linux/amd64) kubernetes/621d4e2/shared-informers] 10.42.204.33:43526]
2018/10/15 下午1:54:01I1015 05:54:01.603426       1 authorization.go:73] Forbidden: "/apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers?limit=500&resourceVersion=0", Reason: ""
2018/10/15 下午1:54:01I1015 05:54:01.603480       1 wrap.go:42] GET /apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers?limit=500&resourceVersion=0: (195.919μs) 403 [[kube-controller-manager/v1.10.5 (linux/amd64) kubernetes/2e2ec65/generic-garbage-collector] 10.42.204.33:43526]
2018/10/15 下午1:54:01I1015 05:54:01.603673       1 authorization.go:73] Forbidden: "/apis/servicecatalog.k8s.io/v1beta1/serviceclasses?limit=500&resourceVersion=0", Reason: ""
2018/10/15 下午1:54:01I1015 05:54:01.603704       1 wrap.go:42] GET /apis/servicecatalog.k8s.io/v1beta1/serviceclasses?limit=500&resourceVersion=0: (93.531μs) 403 [[kube-controller-manager/v1.10.5 (linux/amd64) kubernetes/2e2ec65/generic-garbage-collector] 10.42.204.33:43526]
2018/10/15 下午1:54:01I1015 05:54:01.603805       1 authorization.go:73] Forbidden: "/apis/servicecatalog.k8s.io/v1beta1/serviceplans?limit=500&resourceVersion=0", Reason: ""
2018/10/15 下午1:54:01I1015 05:54:01.603831       1 wrap.go:42] GET /apis/servicecatalog.k8s.io/v1beta1/serviceplans?limit=500&resourceVersion=0: (76.421μs) 403 [[kube-controller-manager/v1.10.5 (linux/amd64) kubernetes/2e2ec65/generic-garbage-collector] 10.42.204.33:43526]
2018/10/15 下午1:54:01I1015 05:54:01.603928       1 authorization.go:73] Forbidden: "/apis/servicecatalog.k8s.io/v1beta1/servicebrokers?limit=500&resourceVersion=0", Reason: ""
2018/10/15 下午1:54:01I1015 05:54:01.603955       1 wrap.go:42] GET /apis/servicecatalog.k8s.io/v1beta1/servicebrokers?limit=500&resourceVersion=0: (77.947μs) 403 [[kube-controller-manager/v1.10.5 (linux/amd64) kubernetes/2e2ec65/generic-garbage-collector] 10.42.204.33:43526]
2018/10/15 下午1:54:01I1015 05:54:01.604070       1 request.go:897] Request Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"verb":"list","group":"servicecatalog.k8s.io","version":"v1beta1","resource":"clusterserviceclasses"},"user":"system:anonymous","group":["system:unauthenticated"]},"status":{"allowed":false}}
2018/10/15 下午1:54:01I1015 05:54:01.604136       1 round_trippers.go:386] curl -k -v -XPOST  -H "User-Agent: service-catalog/v0.1.33 (linux/amd64) kubernetes/621d4e2" -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXRhbG9nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNlcnZpY2UtY2F0YWxvZy1hcGlzZXJ2ZXItdG9rZW4td3dqNHciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2VydmljZS1jYXRhbG9nLWFwaXNlcnZlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImI4ZTM1OTJhLWMzMzYtMTFlOC1iYjJjLTAyMTU3MjlkZWRkNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYXRhbG9nOnNlcnZpY2UtY2F0YWxvZy1hcGlzZXJ2ZXIifQ.Rz06OYffi9ru6aLbi8CXZeHVcKAkztwnnNTQmi9aUH_YCYH00UjKUTTciyLb1iNmMKHSwTR4OR9EqBt88vhy-1kooEyB8tQ_0o4pJMml0HK61yKGn6_shMy2qAREmLzy-quQSG3B8Lvqy9ulDPjOub4jU_aK_X8D63ENiigKWIWnRXah-OLEvWgow4rpkm7F5oXWsUOYFYuDE36_-KGpk4bQzSSyyY8QEpWNhKPT6hCzBMZsIDHq2qQM8qhktWPDVn4-ET_9vRMe2KYTv6VPbeXkifiO28kC54tYWqDMYF39hSD1YPdK3j6NxBqZJ_U-yP3CediiCownZn2WL1vizw" 'https://10.43.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews'
2018/10/15 下午1:54:01I1015 05:54:01.604425       1 authorization.go:73] Forbidden: "/apis/servicecatalog.k8s.io/v1beta1/serviceinstances?limit=500&resourceVersion=0", Reason: ""
2018/10/15 下午1:54:01I1015 05:54:01.604482       1 wrap.go:42] GET /apis/servicecatalog.k8s.io/v1beta1/serviceinstances?limit=500&resourceVersion=0: (225.724μs) 403 [[kube-controller-manager/v1.10.5 (linux/amd64) kubernetes/2e2ec65/generic-garbage-collector] 10.42.204.33:43526]
`
How to solve this problem?

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.26-rc1`

**Comment by superseb** [comment]
Current situation:

* Deploy kubernetes environment with RBAC enabled
* Open UI CLI and try to install voyager via Helm:

```
helm init
helm install stable/voyager --name voyager-operator --namespace kube-system
```
* See pod fail to start with the error
```
kubectl -n kube-system logs -l app=voyager
I0107 21:39:40.085495       1 logs.go:19] cluster doesn't provide requestheader-client-ca-file
```

To validate:
* Deploy/upgrade kubernetes environment with RBAC enabled and `--requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem` in the `Additional Kubernetes API server Flags`
* Open UI CLI and try to install voyager via Helm (you have to delete the old install if you are upgrading)

```
helm init
helm install stable/voyager --name voyager-operator --namespace kube-system
```
* Check if it works

```
kubectl -n kube-system logs -l app=voyager
```

**Comment by soumyalj** [comment]
Reproduced the issue with Rancher 1.6.17 with K8s 1.9.5-rancher1-3. 
Voyager operator fails to start with the below error:
```
I0108 00:15:42.605116       1 logs.go:19] FLAG: --v="3"
I0108 00:15:42.605170       1 logs.go:19] FLAG: --vmodule=""
I0108 00:15:42.610751       1 http.go:97] [Running http server provider...]
I0108 00:15:42.812494       1 run.go:21] [Starting voyager...]
Error: cluster doesn't provide requestheader-client-ca-file

```
