### ISSUE TITLE
Missing fields when create a storageClass

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#12116]
rancher/server:master 03/14

`allowVolumeExpansion` and `parameters` of `storageClass` are not populated in rancher API.
UI sent the `allowVolumeExpansion` and `parameters` to backend for creating a `storageClass`.
But rancher server doesn't populate them.

**Comment by vincent99** [comment]
The name is the ID so it's not going to be updateable.  Disable the field in edit

**Comment by zionwu** [comment]
`parameters` is present in lastet master.
I can't see `allowVolumeExpansion` field in the UI, and @loganhz found the code related to allowVolumeExpansion is commented. @vincent99  do we still need this field?

**Comment by vincent99** [comment]
As far as I remember volume expansion is alpha and off by default and there's no obvious way to tell if it's on to show the option, so I commented it out.

**Comment by loganhz** [comment]
Version - 2.0 master 3/29
Verified fixed

**Comment by walkafwalka** [comment]
Are there plans to add this option?
