### ISSUE TITLE
Ipsec container disappears when a lot of stacks are deployed.

### ISSUE THREAD

**Issue by denniss17** [rancher/rancher#12119]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.6.14

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.2.2
network-services: 0.2.8
scheduler: 0.8.3
kubernetes (if applicable): none

**Docker version: (`docker version`,`docker info` preferred)** 
Docker version 17.12.0-ce, build c97c6d6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher with 3 hosts, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy a lot of stacks on the hosts.

**Results:**
 On a certain moment, the ipsec container (in our case `ipsec-ipsec-5` of the ipsec stack on one of the hosts disappears. `ipsec-ipsec-connectivity-check-5` and `ipsec-ipsec-router-5` remain, but can't be restarted due to missing dependencies. When restarting the entire ipsec service, these last too also disappear. 

As a result, the third host is labeled as "disconnected" and any container on the host can not be reached.

These are the remaining stacks on the disconnected host:
![image](https://user-images.githubusercontent.com/2470115/37452950-7f8c8e54-2836-11e8-8dcd-1a6efad24efb.png)

Our only fix currently is to completely restart the host and re-add it as an host in rancher. Luckily we have a salt state for this, but its not nice to have to do this any time one of the hosts fails

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
