### ISSUE TITLE
Cleanup script for cluster re-import

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12126]
We have to come up with the set of steps that has to be taken if user wants to re-import cluster that used to be registered with any rancher installation before. A couple of existing issues - there might be more

1) Default namespace continues to be assigned to its original project, and don't get deregistered to the new cluster default project. Perhaps we have to cleanup `field.cattle.io/projectId` annotation

2) Cattle agent cleanup

**Comment by moelsayed** [comment]
After a discussion with Alena, I will be removing the following as clean up:
```
cleanup annotations that:
* start with `field.cattle.io`
* start with `lifecycle.cattle.io`
* start with `cattle.io`

cleanup finalizers:
* starting with controller.cattle.io

cleanup labels
* starting with field.cattle.io

so in other words, annotations/labels/finalizers having cattle.io in the name

Remove cattle-system namespace
```
I will test this and see if it will work/cause problems.

**Comment by deniseschannon** [comment]
Let's plan on documenting this first before working on the script (after it's been tested and working).

**Comment by deniseschannon** [comment]
We'll use https://github.com/rancher/rancher/issues/12387 as documentation issue and this issue for the script

**Comment by deniseschannon** [comment]
CLosing in favor of #12387. We want to have the ability to reimport clusters.
