### ISSUE TITLE
When I try to add a new host called "aercloud", is not added

### ISSUE THREAD

**Issue by angelbulasglober** [rancher/rancher#12125]
I'm trying to add a new host called "aercloud" but is not added, when i try with any other name (for example aercloud-1 or anything) it works without any issue.

Is there an exception or reservation for the "aercloud" name or something like that?

Thank you.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`localauth` |
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by angelbulasglober** [comment]
Hi, any comment about this?

**Comment by superseb** [comment]
Can you share the log when it is not added? The logs from directly after running the `docker run` command and the complete output of `docker logs rancher-agent`.

**Comment by angelbulasglober** [comment]
Hi, here are the logs and the images
[logs.txt](https://github.com/rancher/rancher/files/1831443/logs.txt)
![logs1](https://user-images.githubusercontent.com/37418472/37686066-84326158-2c5b-11e8-938f-61e785a8d207.jpg)

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
