### ISSUE TITLE
agent image does not appear to have jq?

### ISSUE THREAD

**Issue by allaryin** [rancher/rancher#12127]
Attempting to import an existing simple k8s cluster that was initialized via kubeadm, the agent fails on a CA checksum mismatch. Further investigation shows that while it IS receiving a json response from the rancher server, its attempt to jq the value out of it fails:

```
+ temp=/tmp/tmp.O26WP2NxyS
+ jq -r .value
+ curl --insecure -s -fL https://rancher.fqdn/v3/settings/cacerts
+ cat /tmp/tmp.O26WP2NxyS
++ awk '{print $1}'
++ sha256sum /tmp/tmp.O26WP2NxyS
+ '[' e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 '!=' 13fc588ae88e671c13d6cec0c8ac6139770363667503c117a1ee597c0b43eb86 ']'
+ rm -f /tmp/tmp.O26WP2NxyS
+ error https://rancher.fqdn/v3/settings/cacerts does not match 13fc588ae88e671c13d6cec0c8ac6139770363667503c117a1ee597c0b43eb86
``` 

`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` being the sha256 sum of an empty string.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha21` UI: `v2.0.25` Agent: `v2.0.3` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by superseb** [comment]
Let us know if you still encounter problems.
