### ISSUE TITLE
Cloud provider support for RKE cluster

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12123]
Some k8s features - LoadBalancer service, volumes - are backed up by certain cloud provider functionality. In order to enable it, we have to register k8s nodes with cloud provider option - aws, gce, etc. The fix has to be done on rke side as well as rancher.

https://github.com/rancher/rke/issues/102

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/19
Verified fixed.
