### ISSUE TITLE
rancher cli ignores environmental variables

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#12121]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

Using also:
```
$ rancher --version
rancher version v0.6.7
```

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: 0.13.7
network-services: (network-manager: v0.7.19/metadata: v0.9.5)
scheduler: v0.8.3
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
```
ubuntu@ip-10-0-1-151:~$ sudo docker info
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1052-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: ip-10-0-1-151
ID: R6UL:T6HX:JJ6K:CBNW:WE7N:YN4I:XIZX:XWUM:Q7GU:EHLQ:R2IH:GZA6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
ubuntu@ip-10-0-1-151:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

``` 
ubuntu@ip-10-0-1-151:~$ uname -r
4.4.0-1052-aws
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
**AWS**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 Rancher Master / 1 Rancher Host / External DB (RDS) for the master

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a `docker-compose.yml` that includes services using environmental variables in the form of:

```
myservice:
    image: someimage
    environment:
       - ENV_VAR1
       - ENV_VAR2
```
 
run 

`rancher stack create --start -f docker-compose.yml -r rancher-compose.yml  my-stack-name`
 
**Results:**

The stack is created by the service in the exported `docker-compose.yml` has **no** environmental variables at all.

**Comment by superseb** [comment]
`rancher up` can handle both new stacks and upgrades, and is able to use the environment variables in an environment. Is this something you can use or are you stuck to `rancher stack create` ?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
