### ISSUE TITLE
Node pool get removed when adding a new node pool 

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12133]
**Rancher versions:**
rancher/server:master 03/16

**Steps to Reproduce:**
1. Create a cluster with one node with all roles.
2. After the cluster is active, Go to "Edit Cluster" and add a node pool of one node with worker role. Click "Save".
![image](https://user-images.githubusercontent.com/1213386/37501941-77a8ce66-290b-11e8-8af0-4cd75e691b9f.png)

**Results:**
The first node pool is removed and second node pool is added.  The first one should not be removed.

![image](https://user-images.githubusercontent.com/1213386/37501839-04a4fe44-290b-11e8-9125-27af95701718.png)

The following API requests are observed:
1.  Put request to the original nodepool
![image](https://user-images.githubusercontent.com/1213386/37502018-d5470952-290b-11e8-9adb-4e20afd5b5e0.png)

2. Post request to v3/nodepool
![image](https://user-images.githubusercontent.com/1213386/37502024-dcdf66f0-290b-11e8-8e24-ff0f3ef50a40.png)

3. Delete request to the original nodepool
![image](https://user-images.githubusercontent.com/1213386/37502033-e4f44810-290b-11e8-9052-4ebb84db1800.png)

I think UI only need to call Put request on nodepool.

**Comment by tfiduccia** [comment]
Version - 2.0  master 3/26
Verified fixed
