### ISSUE TITLE
Error when removing deleted EBS volumes(dangling) from the host

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12135]
**Rancher versions:**
rancher/server: v1.6.15-rc7

**Steps to Reproduce:**
1. Create a rancher setup with v1.6.14 . 
2. Launch EBS catalog and create env/stack scoped and container scoped EBS volumes and services to use these volumes
3. Upgrade rancher to v1.6.15-rc7 and create services to use EBS volumes
4. Upgrade EBS driver and create env/stack scoped and container scoped EBS volumes and services to use these volumes
5. Delete the stack with container scoped volumes
6. Upgrade all services in the environment.
For every host in this environment:
Clean up docker references.
docker volume rm $(docker volume ls -q -f dangling=true)

The following error is seen : 
```
sudo docker volume rm $(sudo docker volume ls -q -f dangling=true)

percontainerafterebsupg_percontvolume_1_7dce8bd0-629f-439d-a5a0-180b19fcb3fe_d9a30
percontainerafterebsupg_percontvolume_2_40a45ed2-afa8-4aea-ad3e-05401f923154_1dfff
percontainerafterranupg_percontvolume_2_980aa6de-242d-4d2e-be43-93fb53a7bc3a_46791
percontainerp1_percontvolume_1_1956d2ed-6d0b-4fbd-954d-1287fa4c0521_8eab5
percontainerp1_percontvolume_2_ad76001e-26dd-4d1e-af6c-906aaa31c984_72766
percontainerp2_percontvolume_1_0483af1d-5b9c-4559-bdc2-ee749544f98e_2f616
Error response from daemon: Error while removing volume percontainerp3_percontvolume_1_873d8b92-0ead-498f-a50e-f947a4502784_d0b15: remove percontainerp3_percontvolume_1_873d8b92-0ead-498f-a50e-f947a4502784_d0b15: VolumeDriver.Remove: Failed to delete volume vol-0717272337768524e, current state: in-use is not available. Should retry
Error response from daemon: Error while removing volume percontainerp3_percontvolume_2_32bb2c85-ce5d-4de6-a548-b0b791f3fe14_418ad: remove percontainerp3_percontvolume_2_32bb2c85-ce5d-4de6-a548-b0b791f3fe14_418ad: VolumeDriver.Remove: Failed to delete volume vol-0ffcd152a1fc1fb76, current state: in-use is not available. Should retry

```
After docker restart on the host, the above error is not seen

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
