### ISSUE TITLE
AD with TLS doesn't work

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#12131]
**Rancher versions:**
rancher/server: master at March 15th

steps to reproduce

- try to enable AD authentication with TLS and provide the certificate as an option

result:

I am getting the following error in the UI:
```
TestAndApply Error
error creating connection
```
server logs:
```
2018/03/16 00:43:35 [ERROR] API error response 500 for POST /v3/activeDirectoryConfigs/activedirectory?action=testAndApply. Cause: Error creating ssl connection: LDAP Result Code 200 "": x509: certificate signed by unknown authority
```

**Comment by cjellick** [comment]
@galal-hussein is this meant to represent the usecase where you could not properly paste in a certificate or the usecase where you were trying to enable TLS on a site with an expired certificate?
If its the paste issue, please assign to @westlywright. If its the expired certificate issue, can you retest against a site with a non-expired cert?

**Comment by galal-hussein** [comment]
@cjellick this is the paste issue, where i did paste the certificate but its being sent incorrectly to the API, i will assign to @westlywright

**Comment by westlywright** [comment]
rancher/rancher#1739

**Comment by galal-hussein** [comment]
Rancher server: master at March 20th

I was able to verify that rancher server can be configured with AD TLS
