### ISSUE TITLE
Unsupported Docker versions for rancher 2.0 needs to be error state for nodes using RKE.

### ISSUE THREAD

**Issue by PatrickHuetter** [rancher/rancher#12147]
**Rancher versions:**
rancher/server: 2.0 preview alpha 21
rancher/agent: 2.0.3

**Steps to Reproduce:**
Create a new custom cluster and start the agent on one of your hosts (using etcd and control roles).
The agent starts without errors but hangs while connecting via websocket to rancher (no new log messages after the following one):
```
time="2018-03-18T11:48:41Z" level=info msg="Connecting to proxy" url="wss://rancher.mydomain.com/v3/connect"
```
Rancher says that ```Cluster must have at least one etcd plane host```, so it seems like RKE doesn't get executed.

**Results:**
You can't setup a kubernetes cluster with rancher.

**Comment by pcjacobse** [comment]
I had the same issue, be sure to check if your docker version is supported, or check the allow unsupported docker versions during creation of the cluster.

**Comment by superseb** [comment]
First place to check is the logging of the `rancher/server` container, what does it say after the node has been added? This will also show you if @pcjacobse 's comment is the cause.

**Comment by PatrickHuetter** [comment]
@pcjacobse You were right! I don't know wether it's possible but it would be fine if this kind of error message would also occur within the agent logs.

@superseb so as we can see, @pcjacobse comment is correct. I have to downgrade the docker version or check unsupported docker versions while cluster creation in the rancher UI.
```
2018/03/19 12:47:22 [INFO] cluster [cluster-6l27f] provisioning: Building Kubernetes cluster
2018/03/19 12:47:22 [INFO] cluster [cluster-6l27f] provisioning: [dialer] Setup tunnel for host [195.201.41.250]
2018/03/19 12:47:22 [ERROR] cluster [cluster-6l27f] provisioning: Failed to set up SSH tunneling for host [195.201.41.250]: Unsupported Docker version found [17.12.1-ce], supported versions are [1.12.6 1.13.1 17.03.2]
2018/03/19 12:47:22 [ERROR] cluster [cluster-6l27f] provisioning: Removing host [xxx.201.x1.250] from node lists
E0319 12:47:22.705048       1 generic_controller.go:200] ClusterController cluster-6l27f [cluster-provisioner-controller] failed with : Cluster must have at least one etcd plane host, [cluster-stats] failed with : Operation cannot be fulfilled on clusters.management.cattle.io "cluster-6l27f": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by deniseschannon** [comment]
Verified with master 3/26. If trying ot use a host that has an invalid Docker version, RKE errors out:

<img width="551" alt="screen shot 2018-03-26 at 2 29 59 pm" src="https://user-images.githubusercontent.com/11410997/37934163-35af3c3a-3102-11e8-88dc-7a148db1b342.png">
