### ISSUE TITLE
Upgrade will start container even through not set

### ISSUE THREAD

**Issue by mxschmitt** [rancher/rancher#12149]
In this Rancher and in earlier versions the issue exists, that when you try to upgrade a service and the service is stopped, the containers go through the following states:

```
stopped => started => stopped => new ones created => new ones started
```

expected:

```
new ones created => new ones started
```
And yep, the checkbox in the upgrade dialog is not ticked:

![image](https://user-images.githubusercontent.com/17984549/37586905-0b277846-2b5e-11e8-94d2-5377034cf06c.png)

Best regards

Max

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.15` Cattle: `v0.183.45` UI: `v1.6.42` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by guewen** [comment]
@mxschmitt Hi, did you find a workaround for this issue?

**Comment by mxschmitt** [comment]
@guewen Nope, I tried to reproduce it in the current release (1.6.20) and the same issue is reproduceable.
The states are when you try to upgrade a stopped container:
- stopped (initial state)
- started
- stopped
- new one created
- new one started

it should be:
- new one created
- new one started

Best regards

Max

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
