### ISSUE TITLE
 Look into securing Ports 10255 and 4194 for k8s/heapster

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12142]
In kubernetes, Ports 10255 and 4194 are not restricted. There is no clear way in the docs to restrict access to them from kubelet side.

http://rancher.com/docs/rancher/v1.6/en/kubernetes/security/

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
