### ISSUE TITLE
Bot running inside of Rancher stack not able to connect to websocket

### ISSUE THREAD

**Issue by Zelle97** [rancher/rancher#12144]
**Rancher versions:**
rancher/server: stable
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.7
network-services: v0.7.19
scheduler: v0.8.3

**Docker version: **
17.12.1-ce

**Operating system and kernel: **
Debian GNU/Linux 9 (stretch)

**Type/provider of hosts: **
Bare-metal

**Setup details: **
rancher server and agent running on the same host

**Environment Template:**
Cattle

**Steps to Reproduce:**
Tricky, websockets as is works ( can confirm because applications sends heartbeats to a websocket and they work Example: * )but its easy to reporoduce with my personal catalog if you setup the bot yourself ( which again needs some preparation )

*Example: 
` Received DEBUG event from Discord.js! info=[ws] [connection] Sending a heartbeat
 Received DEBUG event from Discord.js! info=[ws] [connection] Heartbeat acknowledged, latency of 115ms
`

**Results:**

Error: 

` open=function onOpen() {
      listener.call(this, new OpenEvent(this));
   }, message=function onMessage(data) {
     listener.call(this, new MessageEvent(data, this));
   }, close=function onClose(code, message) {
      listener.call(this, new CloseEvent(code, message, this));
    }, error=function onError(error) {
      listener.call(this, new ErrorEvent(error, this));
    }, _eventsCount=4, _maxListeners=undefined, readyState=3, protocol=, _binaryType=nodebuffer, _finalize=function () { [native code] }, _closeFrameReceived=false, _closeFrameSent=false, _closeMessage=, _closeTimer=null, _finalized=true, _closeCode=1006, , _isServer=false, _receiver=null, _sender=null, _socket=null, _error=null, url=wss://eu-west210.discord.gg/?v=3&encoding=json, _req=null, type=error, message=connect ETIMEDOUT 176.227.219.8:443, errno=ETIMEDOUT, code=ETIMEDOUT, syscall=connect, address=176.227.219.8, port=443
`

I am aware this is kind of a specific Issue, so any help is appreciated!

**Comment by vincent99** [comment]
Rancher starts regular docker containers and is not involved in the data path out of them except for routing the 10.42.0.0/16 managed network.  You are not providing any evidence to think this problem had anything to do with running in Rancher specifically (e.g.  the same thing works on the same host as Docker run directly) and lots of people run lots of things that use websockets successfully (including us, running Rancher in Rancher).

My guess would be you have an MTU wrong somewhere and only tiny frames like a heartbeat make it through.

**Comment by Zelle97** [comment]
@vincent99 thanks for the help!

I already thought it might not be connected to rancher specifically. Thanks for the advice.
I could not reporduce this while running my container locally. Could you give me some advice setting the MTU size for my container managed by rancher?

**Comment by Zelle97** [comment]
I could confirm it has nothing to do with rancher. Closing this Issue.
