### ISSUE TITLE
Site Access in AD revertsback to last restart

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#12150]
**Rancher versions: 1.6.15

**Docker version:17.03.2-ce

**Operating system and kernel: RancherOS v1.2.0

**Setup details: single node internal DB

**Environment Template: Cattle

**Steps to Reproduce:  Upgrade DB from Previous Versions.

My Site Access Looks like this in the DB

28 | api.auth.ldap.allowed.identities                   | ldap_user:CN=5610,OU=Standard,OU=Users,OU=Users,OU=example=intern,DC=example,DC=com

36 | api.auth.allowed.identities                        | ldap_user:CN=5610,OU=Standard,OU=Users,OU=Users,OU=example,DC=intern,DC=example,DC=com

When I change something in the site access https://rancherserver/admin/access/activedirectory

Then it get writen to ID 36, but after restart ID 36 is again the excapt copy of ID 28.

What can I DO?

**Comment by superseb** [comment]
Sounds like https://github.com/rancher/rancher/issues/10756, can you share from what version you upgraded and since when it started happening?

**Comment by Toonix** [comment]
Not sure but looks like I fixed it with this 

update setting set value="" where name="api.auth.ldap.allowed.identities";

Still testing everything, but at least it dosn't revert back to the old settings now.

**Comment by Toonix** [comment]
Had to change this too

update setting set value="" where name="api.auth.ldap.access.mode";

Now the method and the users / groups stays how I set them in the gui.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
