### ISSUE TITLE
Question: default values for Health check

### ISSUE THREAD

**Issue by dsteegen** [rancher/rancher#12152]
Hello,

Is it possible to specify the default values for the following health check properties:

```
initializing_timeout: 
reinitializing_timeout: 
interval: 
response_timeout: 
healthy_threshold: 
unhealthy_threshold: 
strategy: 
```

I have been looking all over the Rancher documentation but could not find the answer. Maybe this can be included in a newer version of the docs.

Thanks in advance!

**Comment by vincent99** [comment]
No; the default is that there is no healthcheck, and the defaults once you turn it on in are in the UI code and not configurable.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
