### ISSUE TITLE
Cloning of workloads doesn't work

### ISSUE THREAD

**Issue by PatrickHuetter** [rancher/rancher#12153]
**Rancher versions:**
rancher/server: 2.0 alpha 21

**Steps to Reproduce:**
Create a workload, click on the 3 dots on the right side of the service and on "clone" in the UI.

**Results:**
Nothing happens. No view change in the UI. It's not possible to clone a service / workload.

**Comment by tfiduccia** [comment]
@PatrickHuetter - clone has not yet been implemented.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified added
