### ISSUE TITLE
API - Should not be allowed to enable PSP for a project when PSP is not enabled at the cluster level.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12155]
Rancher versions: 2.0 build from master

Steps to reproduce the problem:
Create a cluster without enabling PSP.
Create project setting Default Pod Security Policy. This is allowed at this point.
But PSP does not take effect since PSP is not enabled at the cluster level.

API should not allow for PSP to set a project level in this case.

**Comment by rmweir** [comment]
closing in favor of https://github.com/rancher/rancher/issues/21548
