### ISSUE TITLE
Not use private IP address when add host use Azure driver 

### ISSUE THREAD

**Issue by akking** [rancher/rancher#12168]
**Rancher versions:**
rancher/server: 1.6.15

**Steps to Reproduce:**
Add a host through UI, select Azure. Check "Use Private IP to Connect" and select Public IP with "None". The host is provisioned successfully but the IP address reported is "52.173.253.208" which I don't where is come from. 

**Results:**
healthcheck service fails, ipsec flaps. And log from ipsec-ipsec-router shows: 
> samonitor: expected SA for host: 52.173.253.208, but not found

**Comment by akking** [comment]
No very sure it's Rancher gets the wrong IP address from Docker Machine Azure driver or Rancher not uses the private IP. Some guide of where I can find the source code to these part is greatly appreciated. Thanks.

**Comment by CMoH** [comment]
Seems related to https://github.com/rancher/rancher/issues/3746 - anyway, looks like a workaround.

**Comment by CMoH** [comment]
I am using rancher-1.6.12 at the moment. I've looked at the release notes up until 1.6.17, but I didn't see anything about it getting fixed so far. Or has it?

**Comment by CMoH** [comment]
@akking Apparently the rancher agent gets that public IP address by using a my-ip service, so it's actually whatever azure uses as gateway for your host.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
