### ISSUE TITLE
Error showing catalog detail page when the user lacks manage workload permission

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#12166]
**Rancher versions:**
master 3/19

**Steps to Reproduce:**
1. Add a new user A as a standard user
2. Go to project member page, Add the user as a member in `default` project with all roles in custom except `Manage Workloads`
3. Log in as the user A, Go to `Catalog Apps` page, click any of the catalogs

**Results:**
![image](https://user-images.githubusercontent.com/5697937/37640947-b6150ce2-2c52-11e8-9a49-6d5635cc87d6.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
