### ISSUE TITLE
piping data through websocket proxy breaks it, redirecting seems fine

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#12165]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9
rancher cli: v0.6.7

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 - 4.4.0-1049
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aws

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher ha

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
1. have a mysql server container
2. import data by executing: `cat load_dept_emp.dump |  rancher exec dbtest/db mysql` 

**Workaround**
1. running the import through `rancher exec dbtest/db < employees.sql` seems to work fine.

**Results:**
Cli outputs:
```
ERRO[0000] Failed to handle connection: websocket: bad handshake 
ERRO[0000] Failed to handle connection: websocket: bad handshake 
error during connect: Get http://%2Ftmp%2Fdocker-sock741380369/v1.24/containers/65ad3716384fda32bbaf147cc85fb056c7cc747787a4b12a00eb7a01f79dbc7c/json: read unix @->/tmp/docker-sock741380369: read: connection reset by peer
```

Websocket-proxy goes unresponsive. [Thread dump from hurt websocket-proxy](https://gist.github.com/aemneina/52a498d21388f1bddbc0417c1eb78eee)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
