### ISSUE TITLE
Worker node is stuck in registering state for a custom cluster 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12164]
**Rancher versions:**
rancher/server: Master build from March 19th

**Steps to Reproduce:**
1. Create a custom cluster with 3 nodes (Used Digital ocean hosts)
 N1 - Control node
 N2 - etcd node
 N3 - Worker node

Node N3 is stuck in registering state as below:

<img width="1272" alt="screen shot 2018-03-19 at 4 39 50 pm" src="https://user-images.githubusercontent.com/18536626/37627954-2f0b12c8-2b94-11e8-822e-e58ffe619853.png">

Server logs do not show cluster update for node N3

**Comment by moelsayed** [comment]
Tested using current master, custom cluster was created with no problems.

**Comment by moelsayed** [comment]
I tried to reproduce several times with no issues. I suspect networking issues in DO in your case. Please re-assign to me if you are able to successfully reproduce it.
