### ISSUE TITLE
UI - Do not show "Default Pod Security Policy" for cluster and "Pod Security Policy" for projects for clusters other than RKE clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12161]
Rancher versions: 2.0 build from master

Pod Security Policy is supported only for  Amazon EC2, Digital Ocean and Custom clusters.
Do not show "Default Pod Security Policy" for cluster and "Pod Security Policy" for projects for clusters other than RKE clusters.

**Comment by loganhz** [comment]
Removed `Default Pod Security Policy` when creating `Azure AKS` and ``Google GKE` clusters.

Removed `Pod Security Policy` in project new/edit pages of `none` rke clusters.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
