### ISSUE TITLE
Powered OFF node in custom cluster should not be in active state

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12176]
**Rancher versions:**
rancher/server: Master from March 20

**Steps to Reproduce:**
1. Create a 3 node custom cluster with ALL roles on each node using digital ocean hosts
2. Wait for the cluster to become active 
3. Power OFF one of the nodes(N1)

After a node is powered OFF, the cluster is in "Unavailable" state but the node(in nodes tab) is still in active state. 
<img width="1310" alt="screen shot 2018-03-20 at 3 20 55 pm" src="https://user-images.githubusercontent.com/18536626/37685870-5844b1a8-2c52-11e8-9a7d-a47f45cc67c0.png">

<img width="1272" alt="screen shot 2018-03-20 at 3 21 04 pm" src="https://user-images.githubusercontent.com/18536626/37685878-6066f36e-2c52-11e8-8820-3d87a7120f5c.png">

**Comment by StrongMonkey** [comment]
Darren mentioned that if the cluster goes unavailable we can just let ui to mark all its nodes to unknown.

**Comment by vincent99** [comment]
Why is the cluster unavailable with one node down in the first place?

I can easily change the displayed state for the nodes, but if it's not a real state then the CLI has to replicate the same behavior and a state shown in both won't exist in the API/docs.

**Comment by cjellick** [comment]
Important/really bad part is that taking out one control plane node (when there are multiple) causes the cluster to go to unavailable.
@soumyalj can you ellaborate? are you losing the entire control plane or are there other control plane nodes?

**Comment by cjellick** [comment]
Only cases that should cause clsuer to go to unavailabe: lost quorom or no cp nodes

**Comment by cjellick** [comment]
@soumyalj basically, we nee this broken down into what specific cases causes it. Does the role of the node make a difference? Does the total number of nodes with that role make a difference?

**Comment by cjellick** [comment]
@mrajashree to validate

**Comment by mrajashree** [comment]
rancher/rancher:master
Created a custom cluster with all roles on all 3 nodes.
Powered off one host
The message about cluster being unavailable was only for about a minute. The cluster got updated and showed the node as `Inactive`, and the cluster was available again
<img width="1440" alt="screen shot 2018-09-12 at 4 39 10 pm" src="https://user-images.githubusercontent.com/10672776/45460211-f5d9ef80-b6b0-11e8-8464-7a953cd59e61.png">
<img width="1438" alt="screen shot 2018-09-12 at 4 39 41 pm" src="https://user-images.githubusercontent.com/10672776/45460215-f7a3b300-b6b0-11e8-9f21-e50da66d39b8.png">

**Comment by mrajashree** [comment]
<img width="1423" alt="screen shot 2018-09-13 at 1 10 51 pm" src="https://user-images.githubusercontent.com/10672776/45513103-a0581e00-b756-11e8-9c7f-de7c3d02e795.png">
<img width="1374" alt="screen shot 2018-09-13 at 1 11 09 pm" src="https://user-images.githubusercontent.com/10672776/45513106-a221e180-b756-11e8-8367-de32bbf36642.png">

With a custom DO cluster I don't see cluster unavailable for even a minute and the node is not in active state once powered off

**Comment by mrajashree** [comment]
@soumyalj is going to take a look again as per slack converation

**Comment by soumyalj** [comment]
Tested the use case few times with rancher v2.1.0-rc3. 
1. Create a 3 node custom cluster with ALL roles on each node using digital ocean hosts
2. Wait for the cluster to become active
3. Power OFF one of the nodes(N1)
After the node was turned off , cluster was still active, the powered off node was in "Unavailable" state as expected.
<img width="1257" alt="screen shot 2018-09-20 at 2 05 19 pm" src="https://user-images.githubusercontent.com/18536626/45846982-44554280-bcde-11e8-8d4a-d6d1ee9a7304.png">

Also, for the issue @tfiduccia mentioned above, the clusters(GKE, AKS, DO) got deleted immediately, no nodes were displayed as active.
