### ISSUE TITLE
Show/Hide CLI page for Kubernetes

### ISSUE THREAD

**Issue by jinhong-** [rancher/rancher#12179]
v1.6.14
CLI Page shows for all users, regardless of role assigned. This would mean that even if RBAC has been configured, user can still download CLI config to gain full access to the k8 cluster. Is there any way to hide the CLI page for specific roles?

Also, setting user to Read Only will cause a 503 error on url {host}/kubernetes/version, which prevents the page from loading the Dashboard UI link

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
