### ISSUE TITLE
Create new k8s builds due to subPath regression in Kubernetes 1.8.9 and 1.9.4

### ISSUE THREAD

**Issue by obriensystems** [rancher/rancher#12178]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: ?

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aws/azure/openstack
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single 
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
install 1.6.13 or 1.6.14 after friday 16 march 2018, before we ran k8s 1.8.5, after we run 1.8.9
only 1.6.12 under docker 1.12 under 1.8.3 is unchanged since the 1.6.15 release

**Results:**
https://jira.onap.org/browse/OOM-813
Error: failed to prepare subPath for volumeMount "aai-data-router-model-v8" of container "aai-data-router"

onap          aai-resources-9f95b9b6d-qrhs5                  0/2       CreateContainerConfigError        0          27m

**Comment by superseb** [comment]
This is due to a regression in k8s: https://github.com/kubernetes/kubernetes/issues/61076. We are currently running tests on the new builds. (1.8.10 and 1.9.5)

**Comment by obriensystems** [comment]
hi, a question about the upgrade of 1.6.14, 1.6.13 - from 1.8.5 to 1.8.9 
Could we get these previously working versions working
This came in when you guys released 1.6.15
thank you
/michael

**Comment by deniseschannon** [comment]
We've already released k8s 1.8.10 which fixes this regression which is available for v1.6.14 and 1.6.13.

**Comment by obriensystems** [comment]
Testing 1.6.14 now
Q: why do we change the k8s version for released versions - essentially we have run through 3 versions of 1.6.14 over 7 days (1.8.5, 1.8.9 and 1.8.10) - would only expect this version traffic for the tip 1.6.15.

Just trying to keep a project with 100's of developer going.
/michael

**Comment by obriensystems** [comment]
In the interest of collaboration between onap.org and rancher could we get a liason for ONAP - I am meeting Fred tomorrow.
The onap project does a lot of testing and development around the rancher installation of kubernetes - I thing it would be a good thing if the projects worked together.

Feel free to join the OOM meeting for ONAP at 1000 EDT GMT-5 every Wed at

https://wiki.onap.org/display/DW/ONAP+Operations+Manager+Project
https://zoom.us/j/118908904
We would like to meet members of your team
/michael

**Comment by vincent99** [comment]
Updates are often timed to correspond with Rancher releases, but Kubernetes is a catalog item that has its own lifecycle separate from the server releases.

In this case 1.8.5 was a routine update that was already going out, 1.8.9 was for a [serious vulnerability](https://github.com/kubernetes/kubernetes/issues/60813), and 1.8.10 for a major regression that the fix in 1.8.9 caused.  Your installed copy is not automatically upgraded, so someone in your environment is upgrading them.  Which is a good thing, unless you like arbitrary host filesystem access from pods.

**Comment by obriensystems** [comment]
We install the system daily and hourly in our CD system.  Hence why we picked the change up.

It is just that we control the version of Docker to match the version of kubernetes server installed.  We also control the version of helm based on what rancher installs.  The only thing that varies now is the kubernetes version - I would expect that if a new version is needed it is only for later rancher versions.  For example the 10250 port for crypto miners that is fixed in 1.10 would not usually be backported
