### ISSUE TITLE
Standard users cannot list pipelines

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#12180]
**Rancher versions:**
master 3/21

**Steps to Reproduce:**
1. Enable pipeline in the cluster
2. Add a standard user A
3. set the user to be the owner of the cluster and the project
4. Log in as user A and go to pipeline list pages

**Results:**
The page shows `Pipeline is not enabled` though it is enabled actually.
![image](https://user-images.githubusercontent.com/5697937/37698021-7143ae06-2d1b-11e8-9f82-cf5873fd11eb.png)

**Comment by biblesyme** [comment]
<img width="1436" alt="screen shot 2018-03-21 at 15 28 14" src="https://user-images.githubusercontent.com/9334435/37698223-94a8a828-2d1c-11e8-8ab3-16510b940c15.png">


the standard user has no access to the `clusterPipeline`
