### ISSUE TITLE
Unable to upgrade/edit load balancer (haproxy) config from rancher UI

### ISSUE THREAD

**Issue by leibowitz** [rancher/rancher#12183]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: haproxy rancher/healthcheck:v0.3.3
ipsec: rancher/net:v0.13.7 - rancher/net:holder
network-services: rancher/network-manager:v0.7.19 - rancher/metadata:v0.9.5
scheduler: rancher/scheduler:v0.8.3
kubernetes (if applicable): using cattle

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.1.3 (4.9.75)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS (ami-72613d08 - us-east-1)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
N/A

**Results:**
I have a rancher high availability cluster running on our production environment. This has been running for a while since the last OS/rancher upgrade (few months). 

We do releases frequently, which involves pushing a new stack and updating our load balancer rules every so often.

This has always worked on the same server (same setup), without any problems. 

Today I could not update the load balancer config from the UI. The error was:
```Validation failed in API: instanceId```

Inspecting the request/response revealed that the PUT request on `/v2-beta/projects/[projectid]/loadbalancerservices/[serviceid]` was failing with 504, where the content of the request included the `instanceId` of the load balancer (haproxy) service itself. For some strange reason, one of the `instanceId` in the request was wrong.

The instanceIds of haproxy (load balancer service) running on each hosts (3 hosts) were:
- 1i2554
- 1i2775
- 1i2834

The request included 1i2554, 1i2775, and 1i2832 (that one did not exist anywhere)

All the content of each services looked OK (ip address, name of services, rules, etc), but just the instanceId of the 3rd haproxy service was strange (with the 2 digit difference)

Looking at the load balancer service was showing only 3 running instances (with the listed instanceIds). And all the results from all the endpoints in rancher API (stacks, services, instances) were always returning the same correct ids. 

No idea where the incorrect 1i2832 is coming from.

The rules in haproxy are definitely correct - since they are running fine. And doing a simple upgrade without changing the config is still returning the same error.

After about an hour (without doing anything), doing exactly the same operation worked fine. None of the load balancer instanceIds have changed.

Any ideas as to what might have caused this?

**Comment by leibowitz** [comment]
Same problem appears again, out of the blue. Really annoying, and no idea how to fix it other than wait a couple of hours and pray...

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by SergioMBS** [comment]
This issue is still happening, really annoying as all you want to do is change the LB config

**Comment by konvergence** [comment]
Hi,
When I get sometime this issue, I do the following steps:
- create a new stack"loadbalancer2"  and disable "start" options in the advanced options
- copy/paste docker-compose.yml and rancher-compose-yml from the old "loadbalancer" to the new stack "loadbalancer2"
- stop the old stack "loadbalancer"
- start the stack "loadbalancer2"

**Comment by ibox4real** [comment]
I have been able to get it working if i restart the lb services.

**Comment by mjaverto** [comment]
I had a similar issue that was not a load balancer. I just restarted the service. After restarting I was successful in upgrading.

**Comment by ryanvin** [comment]
I solved this problem by using rancher api. 
im my case:
- service_id: 1s110
- instanceids: li1949

in service page, click View in API, GET /v2-beta/projects/1a5/services/1s110，in publicEndpoints, instanceId is 1i1937, which is wrong
```json
publicEndpoints": [
{
"type": "publicEndpoint",
"hostId": "1h1",
"instanceId": "1i1937",
"ipAddress": "xxx.xxx.xxx.xxx",
"port": xxx,
"serviceId": "1s110"
}
], 
```
so the validation failed, cause GET /v2-beta/projects/1a5/instances/1i1937 returns empty.

then i clik edit button, and change publiEndpoints-instanceid to li1949, submit my put request and return to service page in rancher, I can update service now.
