### ISSUE TITLE
Admins should be able to create and control Node Templates

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#12186]
In a lot of enterprise environments allocation of resources is controlled by an operations group.  They are responsible for setting up and maintaining all the underlying infrastructure in the cloud, managing costs, etc...

Users of envionments (developers, qa, sec...) might not know and maybe should not need to know the details required to set up a node template.

As a Global Admin I want to set up node templates with  "Automation User" credentials and allow my Cluster Admins to use the templates when starting/stopping/sizing clusters.

I don't want users or cluster admins using personal cloud provider credentials in templates to create or modify clusters, because all that will break if a user changes jobs or leaves the company and I deprovision their cloud provider account.    

**Rancher versions:**
rancher/server: v2.0.0-alpha21

**Comment by Overv** [comment]
We would also really like to have this feature to set up templates as admin for our users to apply.

**Comment by billabongrob** [comment]
With 2-3 admins of the environment, it would be nice to share the node templates between team members.  This would help avoid confusion.

**Comment by gillarda** [comment]
As other users suggested, this feature would be very appreciated in environments where multiple administrators manage clusters for various teams or customers.

**Comment by DJAyth** [comment]
Very much interested in this.

**Comment by mattskipton** [comment]
We would really like this feature as well

**Comment by okunc** [comment]
+1

**Comment by yuliujin** [comment]
We would like to have this feature as well.

**Comment by JonathanParrilla** [comment]
+1

**Comment by cloudnautique** [comment]
This issue will be used to track allowing an Rancher admin to administer all node templates. Today when a user leaves Rancher, no one can administer the cluster created from that template. The sharing component will be addressed in #22467 for the 2.4 timeframe.

**Comment by cjellick** [comment]
@rmweir im taking wes off this. please make sure there is a ui issue for it

**Comment by rmweir** [comment]
Suggested scenarios to test:

1. Node template Migration:
Node templates created from prior to this feature should be cloned into cattle-global-nt namespace, with an ID that includes the creator user id and old node template name. Old node template should then be deleted.

2. When a user creates a node template they should be able to view it. (Should contain annotation indicating that role bindings have been created for owner)

3. After creating a node template, it should have a field call "principalId" viewable from API.

4. Non-admin users cannot see node templates created by other non-admin users or admins.

5. Admin should be able to edit and delete node templates created by others.

6. Admin should be able to change cloud credential on node template and successfully provision cluster with it.

7. If a node template is created in a namespace that is not "cattle-global-nt" it will be migrated as described in scenario 1.

**Comment by jiaqiluo** [comment]
The feature enhancement is validated in Rancher:v2.3-head 61a741de8, it works as expected, and the detailed tests and results are recorded in the test plan.

**Comment by nlowe** [comment]
@jiaqiluo I'm a bit confused, is this in 2.3? I see #23728 from 3 days ago that revers the PR this was merged in.

**Comment by rmweir** [comment]
@nlowe, a PR was made to revert this for a release I believe, and then that subsequent PR was reverted. Should be in now.
