### ISSUE TITLE
Rancher api answer service state "Removed" when docker state is "Removal in progress"

### ISSUE THREAD

**Issue by JeremyBesson** [rancher/rancher#12188]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent:  1.2.6 

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.11.9
network-services: v0.7.8
scheduler: v0.8.2 

**Docker version:**
```
Containers: 242
 Running: 193
 Paused: 0
 Stopped: 49
Images: 522
Server Version: 17.09.1-ce
Storage Driver: devicemapper
 Pool Name: docker-252:1-262148-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 117.3GB
 Data Space Total: 322.1GB
 Data Space Available: 204.8GB
 Metadata Space Used: 173.2MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 1.974GB
 Thin Pool Minimum Free Space: 32.21GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 125.8GiB
Name: ns379720.ip-178-33-123.eu
ID: DZJP:JE2I:MWKD:MNVD:2II6:U3ZB:XJKQ:YY3Q:53R7:NJXV:ZMDU:G3N6
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel:**
Ubuntu 16.04.3 LTS

**Type/provider of hosts:**
Bare-metal

**Setup details:**
single node rancher

**Environment Template:**
Cattle

**Steps to Reproduce:**
I discover this problem with a poor performance single node server. 
On this server when I remove a service from rancher API it's take a very long time until the container is fully deleted.
I wanted to manage this state inside my application with Rancher API calls to get service sate.
Rancher API answer state "removing" just after I ask to delete the service which is good.
But when the container is really being deleted (Docker state: "Removal in progress") the rancher API answer state "removed" while this is not true.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
