### ISSUE TITLE
Confusing error messages for pod errors.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#12185]
Rancher displays error message "Deployment does not have minimum availability." instead of something like Image Not Found.

In Kubernetes, `kubectl get pods` shows `ImagePullBackOff`  this is a better short status message than what rancher is showing.  

```shell
kubectl --insecure-skip-tls-verify=true get pods                            
NAME                    READY     STATUS             RESTARTS   AGE
test-77766ff85d-4tttp   0/1       ImagePullBackOff   0          7m
```

It would be even better if I can see the Events list from `kubectl describe pods` somewhere when I drill into the pod/container screen (This screen would be a good place for that). 

![image](https://user-images.githubusercontent.com/5324639/37717426-86554f02-2cee-11e8-8828-6db5825931eb.png)

```shell
kubectl --insecure-skip-tls-verify=true describe pods test-77766ff85d-4tttp
...
Events:
  Type     Reason                 Age               From                            Message
  ----     ------                 ----              ----                            -------
  Normal   Scheduled              6m                default-scheduler               Successfully assigned test-77766ff85d-4tttp to jgreat-demo2-cluster3
  Normal   SuccessfulMountVolume  6m                kubelet, jgreat-demo2-cluster3  MountVolume.SetUp succeeded for volume "default-token-nxzr8"
  Normal   Pulling                4m (x4 over 6m)   kubelet, jgreat-demo2-cluster3  pulling image "jgreat/2048:imagenotfound"
  Warning  Failed                 4m (x4 over 6m)   kubelet, jgreat-demo2-cluster3  Failed to pull image "jgreat/2048:imagenotfound": rpc error: code = Unknown desc = Error response from daemon: manifest for jgreat/2048:imagenotfound not found
  Normal   BackOff                4m (x6 over 6m)   kubelet, jgreat-demo2-cluster3  Back-off pulling image "jgreat/2048:imagenotfound"
  Warning  FailedSync             1m (x24 over 6m)  kubelet, jgreat-demo2-cluster3  Error syncing pod
```

**Rancher versions:**
rancher/server: v2.0.0-alpha21

**Steps to Reproduce:**
Try to create a workload with an invalid image

**Results:**
![image](https://user-images.githubusercontent.com/5324639/37717904-8054951c-2cef-11e8-8d0b-6900b1602d62.png)

**Comment by alena1108** [comment]
@jgreat we currently just proxy whatever information k8s sets on the deployment. Kubectl does extra calls- it displays the events for the pods in addition to fetching the deployment object.

@vincent99 do you think it would make sense to fetch cluster events for the pod, and display it in the UI?

**Comment by loganhz** [comment]
Events section is already in.

Close in favor of https://github.com/rancher/rancher/issues/16245
