### ISSUE TITLE
add Q&A for helm catalog

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#12197]
Feature:
User can define a custom questions.yml under the root directory of a helm chart, like https://github.com/StrongMonkey/rancher-charts/blob/master/charts/kube-lego/questions.yml. The format will follow [1.6 style](http://rancher.com/docs/rancher/v1.6/en/catalog/private-catalog/#questions-in-the-rancher-composeyml). Both api and ui are able to display those options to end users.

Example of how api looks like:
![screenshot from 2018-03-21 15-29-08](https://user-images.githubusercontent.com/9203378/37740922-b4e0bfae-2d1c-11e8-9dfb-2526fe52c94e.png)

UI: to be finished, should look up the questions field to decide if questions should be shown.

Current questions only allow string type. questions.yml need to be added into the root directory, same level with readme.md and values.yml.

https://github.com/StrongMonkey/rancher-charts contains a chart with a questions.yml as an example.

**Comment by deniseschannon** [comment]
Handing over to UI as API is available.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
