### ISSUE TITLE
Secrets (Environment From) variables are not saving on new workloads

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#12190]
**Rancher versions:**
rancher/server: master  as of 3/20

**Steps to Reproduce:**
1. Ensure you have at least 1 existing secret created
2. Navigate to the Launch Workload page
3. Open the environment variables accordion and select the `Add From Source` button
4.  Select a secret from the source dropdown
5. Select All or a key from the key dropdown
6. *Optionally* Select a prefix or add an alias for the key respectively 
7. Launch the workload

**Results:**
The `container.environmentFrom` param returns null with zero errors. Seems like the data is just not saving.

**Comment by soumyalj** [comment]
Tested with master from March 22nd build. Created secrets from the Resources tab.
Created workload with the steps above. Workload creation was successful and  in the API, `container.environmentFrom` parameter was populated correctly with the secret chosen
<img width="537" alt="screen shot 2018-03-22 at 2 47 20 pm" src="https://user-images.githubusercontent.com/18536626/37800482-239b80be-2de0-11e8-833a-e834c76ee405.png">
