### ISSUE TITLE
rancher/container-crontab support for time zones

### ISSUE THREAD

**Issue by AndrewSav** [rancher/rancher#12192]
rancher/container-crontab seems to accept schedules in UTC only. 
[Some people suggest](https://github.com/gliderlabs/docker-alpine/issues/136#issuecomment-341172222) that having tzdata installed in the container helps with that.

I did not try setting TZ, but doing [cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime](https://github.com/gliderlabs/docker-alpine/issues/136#issuecomment-341172222) in the container after tzdata is installed, does change the zone.

Is there something I'm overlooking? Can tzdata and an "official" way to change the time zone be included? Can this be added to the documentation?

**Comment by Yiivgeny** [comment]
+1

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
