### ISSUE TITLE
UI - Only 1 endpoint link shown in UI for workloads created with publish on "every node".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12196]
Rancher versions: 2.0 Build from master

Setup - Cluster with 3 nodes

**Steps to Reproduce:**

Create a work load withe following port option:

<img width="1296" alt="screen shot 2018-03-21 at 3 04 25 pm" src="https://user-images.githubusercontent.com/4266958/37740514-44c37910-2d1b-11e8-82b8-45edb3206bbe.png">

Only 1 port on one of the hosts  is shown in the UI 

<img width="1274" alt="screen shot 2018-03-21 at 3 20 32 pm" src="https://user-images.githubusercontent.com/4266958/37740564-6c812c7c-2d1b-11e8-94de-41868a8c2805.png">

**Comment by vincent99** [comment]
This is intentional.  It's a single link to get you to that port, not an exhaustive list of all 100 ways you _could_ get to it.
