### ISSUE TITLE
Allow or block adding certificate key other than RSA key

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12207]
**Rancher versions:**
rancher/server: v2.0.0-alpha21

Cloudflare origin certificates are given to the user in `PKCS#8 encoded data` starting with `-----BEGIN PRIVATE KEY-----` instead of `-----BEGIN PRIVATE RSA KEY-----`. When adding these certs, this results in an error only visible through the API call/return.

We should block invalid formats or make it compatible to use other formats than RSA key.

**Comment by kinarashah** [comment]
@superseb on adding an invalid format, UI does show `Validation failed in API: certs` and cert doesn't get created, so we are blocking it. Am I understanding it right or you expected something different?

**Comment by kinarashah** [comment]
@vincent99 The only thing that is missing is the msg to user on what failed. 
I see request response as ```{"actionLinks":{},"baseType":"error","code":"InvalidBodyContent","fieldName":"certs","links":{},"message":"failed to parse key, not valid pem format","status":422,"type":"error"}
``` 
but message is not shown in UI.

**Comment by superseb** [comment]
The reason my request got through was the namespace was not ready and the API didn't respond appropriately (?) as it went into `Saving`. My first request would be to detect the header and allow both keys, this means certificates from systems that hand out the pretty common PKCS8 (Like LetsEncrypt and CloudFlare Origin) can easily be used. Instead of asking to convert before submitting.

**Comment by superseb** [comment]
Version: master 4/23

Trying to save a certificate key starting with `-----BEGIN PRIVATE KEY-----` results in `Private Key is invalid. Please make sure it is a RSA key.`

<img width="716" alt="screen shot 2018-04-23 at 16 16 25" src="https://user-images.githubusercontent.com/2620179/39132346-ee7ec224-4711-11e8-942e-3b78a26761f1.png">

**Comment by ttftw** [comment]
This still seems to be an issue in current release.  Cloudflare certs are throwing this error.

**Comment by ray65536** [comment]
+1
Still not fixed in latest release

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/14383, this will be possible in the next release, v2.0.7.
