### ISSUE TITLE
When removing existing target from LB service/Service Alias , the removed target takes a while(when in "removing" state) to disappear from UI 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1220]
Server Version - V0.24.0-rc4

Steps to reproduce the problem:

Add Lb services/ Service Alias with 2 targets test1 and test2.
Activate service.
Remove one target - test2.
When we are brought back to the list service view , notice that the UI shows both the targets test1 and test2 as being linked to the service.
During this time , the state of the "service_consume_map" is in "removing" state.

After few seconds , the target gets removed from the UI.

**Comment by vincent99** [comment]
What is the problem with this?  `removing` isn't removed, they're still linked.

**Comment by sangeethah** [comment]
should we be showing the status "removing" to indicate that it is in the process of being removed? To the user it seems like , the action of having removed the target has not be acknowledged.
