### ISSUE TITLE
 Path /var/lib/kubelet is mounted on / but it is not a shared mount.

### ISSUE THREAD

**Issue by HuiAz** [rancher/rancher#12205]
*Describe your issue here*
centos7 , Docker version 1.12.6

[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [192.168.115.102]: Error response from daemon: linux mounts: Path /var/lib/kubelet is mounted on / but it is not a shared mount.
--
and I have edit /etc/systemd/system/multi-user.target.wants/docker.service and set MountFlags= (no value) , I still have the same issue.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha21` UI: `v2.0.25` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
Can you try setting `MountFlags=shared`?

**Comment by ibuildthecloud** [comment]
The simplest way to test this is to run Rancher 2.0 and use b2d as a custom host.

**Comment by SaiDoFan** [comment]
@HuiAz  Have you solved the problem? I got the same issue

**Comment by sangeethah** [comment]
When I tried to bring up a rhel 7.5 cluster with native docker and selinux enabled , I get the same error
``[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [172.16.100.108]: Error response from daemon: linux mounts: Path /var/lib/rancher is mounted on / but it is not a shared mount.```

**Comment by sangeethah** [comment]
Tested with latest build from master 
```rancher/server      master              1e1b97f08975        2 hours ago         785 MB```

Tried to  bring up a rhel 7.5 cluster with native docker and selinux enabled , I get the same error:
```
2018/04/20 00:51:20 [INFO] cluster [c-h6x7x] provisioning: [workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [172.16.100.244]: Error response from daemon: linux mounts: Path /var/lib/kubelet is mounted on / but it is not a shared mount.
```

**Comment by sangeethah** [comment]
Tested with latest builf from master 
Tried to bring up a rhel 7.5 cluster with native docker and selinux enabled , I get the following error now
- https://github.com/rancher/rancher/issues/12953

**Comment by jbalonso** [comment]
I made only slight progress since I muttered about this issue over in #12384--I'm still facing the shared-mount issue. My setup (now):
* vSphere provider (using vSphere 6.0.0 and ESXi 5.1.0, with hope to upgrade soon)
* `rancher/server:master` with hash `a80ca3ea4ad3` (extended by custom `Dockerfile` to add internal CA certificates via `update-ca-certificates`)
* `boot2docker.iso` from url `https://github.com/boot2docker/boot2docker/releases/download/v17.03.2-ce/boot2docker.iso`
* Kubernetes version `v1.10.1-rancher1`
* Network Provider: `Canal`

Now, I'm getting:
```
[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [192.168.195.144]: Error response from daemon: linux mounts: Path /mnt/sda1/var/lib/docker is mounted on /mnt/sda1 but it is not a shared or slave mount.
```

Which is _technically_ a different error message from this issue, but it smells deeply like the same issue.

Substituting Kubernetes version `1.9.7-rancher1` does not work around the issue, but using https://github.com/gaui/boot2docker-rootfs-mount-fix/releases/download/17.03.2-ce/boot2docker.iso as an alternate b2d URL does work around the issue.

**Comment by sangeethah** [comment]
Tested with v2.0.0-beta4-rc2.

Create a custom cluster with rhel 7.5 hosts with native docker (1.13) with selinux enabled having following configuration:

1 control node
1 etcd node
3 woker nodes

Cluster gets to "Active" state. All nodes in the cluster get to "active" state.
Able to deploy workloads and ingress successfully in the clusters.

**Comment by nrh387** [comment]
anyone tell me how to resolve this issue? I have run into the same issue when using the rancher 2.0

**Comment by nrh387** [comment]
![image](https://user-images.githubusercontent.com/19149590/39403694-861ca6b8-4bb4-11e8-9cd9-c2a14f6116f9.png)
anyone could help?

**Comment by krishofmans** [comment]
@nrh387 is this using the latest beta4? I used to have this issue but it's been fixed in the last beta.

**Comment by nrh387** [comment]
Yes, i used the sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview to get it yesterday. So i think this is the latest version for rancher 2.0.

**Comment by superseb** [comment]
If you still experience issues, please make sure you are testing on `v2.0.0-rc3` shown in the bottom left of the UI.

If you are using that and still see the error, please file an issue with the following info:

- OS used (`cat /etc/os-release` and `uname -r`)
- Docker used (`docker info` and `docker version`)

**Comment by nrh387** [comment]
@superseb I checked the version is v.2.0.0-rc3
![image](https://user-images.githubusercontent.com/19149590/39465344-6d7a3ef2-4d55-11e8-87b3-c103d69eb4da.png)
OS is 3.13.0-86-generic
Here is the docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: iZ947ei2rr7Z
ID: YDG7:CKNZ:SEUJ:XHKY:N6CT:5HQF:NOPL:KSL7:PQSC:BL24:N6VF:ZNQP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://20bh91iy.mirror.aliyuncs.com
Live Restore Enabled: false
Here is docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:11:13 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:11:13 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by nrh387** [comment]
here is more information of OS info
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by superseb** [comment]
@nrh387 Quick workaround is running `mount --make-rshared /` on the host, and then `docker start kubelet` should work.

Rest of the info is partly here https://github.com/moby/moby/issues/19625 and here https://github.com/kubernetes/kubernetes/issues/61058. As far as I could find it's because it's not using systemd, so setting the flags there won't help.

**Comment by nrh387** [comment]
@superseb Hello, it looks the mount shared problem have been skipped, and the host is suspending on the status "Waiting to register with Kubernetes" and here is the docker logs on the rancher server
2018/05/02 01:40:40 [ERROR] error updating ns default status: Operation cannot be fulfilled on namespaces "default": the object has been modified; please apply your changes to the latest version and try again
E0502 01:40:40.362725       1 generic_controller.go:204] ClusterRoleTemplateBindingController c-76wdh/user-khzht-admin [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
2018/05/02 01:40:40 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-zdqz4 to namespace=default
2018/05/02 01:40:40 [INFO] projectSyncer: createDefaultNetworkPolicy: successfully created default network policy for project: project-zdqz4
2018/05/02 01:40:41 [ERROR] error updating ns cattle-system status: Operation cannot be fulfilled on namespaces "cattle-system": the object has been modified; # please apply your changes to the latest version and try again
2018/05/02 01:41:14 [INFO] Handling backend connection request [c-76wdh]
 2018-05-02 01:45:55.619766 I | mvcc: store.index: compact 412734
2018-05-02 01:45:55.623947 I | mvcc: finished scheduled compaction at 412734 (took 3.662457ms)

**Comment by LonghronShen** [comment]
The problem still exists on Rancher 2.0.2 on Ubuntu 18.04+Docker 18.05.0-ce

**Comment by superseb** [comment]
It should be a different error, caused by https://github.com/moby/moby/issues/37032. You shouldn't use Docker 18.05 because of this bug. Other versions should be fine. Track Ubuntu 18.04 support here: https://github.com/rancher/rancher/issues/13888

**Comment by LonghronShen** [comment]
Oh thanks for the message~

**Comment by zukokolkka** [comment]
Facing the same issue on Rancher 2.0.2 + Ubuntu 16.04 + Docker 17.03.2
![image](https://user-images.githubusercontent.com/7433083/41667864-a99af812-74b6-11e8-9c22-f873604cbf41.png)

**Comment by superseb** [comment]
Please create a new issue with the information requested in the template (OS, kernel, `docker info`)
