### ISSUE TITLE
Able to add same users multiple times using same roles to cluster/project.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12218]
Rancher server version - 2.0 build from master

Steps to reproduce the problem:

We are allowed to add the same user to a cluster/project using the same role multiple times.

<img width="1412" alt="screen shot 2018-03-22 at 12 59 53 pm" src="https://user-images.githubusercontent.com/4266958/37795210-1353e48a-2dd1-11e8-8036-c48a31719df6.png">

Can we prevent duplicate entries from getting saved ?

**Comment by cjellick** [comment]
I dont think we are going to prevent this. This is just how auth works in kubernetes

**Comment by deniseschannon** [comment]
@sangeetha can we just confirm that if you delete one of the duplicate users, they still have permissions until all of them are deleted?
