### ISSUE TITLE
Importing pipeline from YAML results in error

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#12211]
* Exported yaml file from one project
* went to workloads tab
* pipelines
* import from YAML
* clicked import

Resulting error:
```
Pipeline.management.cattle.io "pipeline-dbnrw" is invalid: metadata.namespace: Required value```

**Comment by biblesyme** [comment]
@cloudnautique  Are you using the latest master?
I believe this should be fixed in the PR https://github.com/rancher/ui/pull/1748.

This was caused by some mismatch in API call.

**Comment by cloudnautique** [comment]
This was against master at 9am pst 3/22. Will check again

**Comment by cloudnautique** [comment]
Works now

**Comment by cloudnautique** [comment]
This is working now. I was able to export, copy, paste into a new pipeline.
