### ISSUE TITLE
Pipeline Golang pre-canned image should be configured

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#12210]
When using `golang` pre-canned image in a "run a script" step the `go test` command should work on a standard project. I believe the GOPATH is set to something else and the vendor directory is not being traversed.

**Comment by gitlawr** [comment]
@cloudnautique In golang image default GOPATH is `/go`, to make it happen we need the workspace to be mounted at sth like `/go/src/github.com/rancher/rancher` in the container. We're using the Kubernetes plugins and it has no configuration for custom workspace right now. What do you think if we provide the pre-canned scripts as
```
mkdir -p /go/src/github.com/rancher
ln -s `pwd` /go/src/github.com/rancher/rancher
cd /go/src/github.com/rancher/rancher
go test
```

**Comment by cloudnautique** [comment]
Can you add volumes to containers? If so, you could create teh volume in the clone container and then if you can do volumes from... get it in the right spot for the Golang image. 

Otherwise, yeah, the workaround above works fine. If we can dynamically generate the mkdir / ln so that they generate the path from the github repo that would be great.

**Comment by gitlawr** [comment]
We can add volumes to containers and set workingdir for each container, but the agent will take it as root workspace, create subdir and do the job in it. And the `ws` annotation does work well in this context. So the workaround seems to be the best shot.

**Comment by deniseschannon** [comment]
@bmdepesa can you ask @cloudnautique how this needs to be tested?

**Comment by cloudnautique** [comment]
This is working. I'll sync with @bmdepesa

**Comment by bmdepesa** [comment]
Validated against master 4/23. 

Pre-canned script worked.
