### ISSUE TITLE
As a standard user trying to access github auth option , UI hangs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12227]
Rancher versions: Build form master

As a standard user trying to access github auth option using Security/Authentication , UI hangs.

<img width="1395" alt="screen shot 2018-03-22 at 4 01 37 pm" src="https://user-images.githubusercontent.com/4266958/37803089-55398d5a-2dea-11e8-8ba2-9abcf2b58eb7.png">

When trying to access "AD Auth" , user is brought back to log in page.

**Comment by loganhz** [comment]
Hided the `Authentication` page for the users who has no permission to access it.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
