### ISSUE TITLE
In Cluster Edit page , current user is shown as "owner" of the cluster irrespective of his role.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12222]
Rancher versions: Build from master

**Steps to Reproduce:**
Create a cluster as admin.
Add a user  say - "test1"as cluster member.
Log in as test1 and go to "Edit Cluster" page .

Current user is shown as "owner" of the cluster irrespective of his role.

<img width="1329" alt="screen shot 2018-03-22 at 3 39 12 pm" src="https://user-images.githubusercontent.com/4266958/37802460-c64be6b2-2de7-11e8-917f-0722c322a7d9.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
