### ISSUE TITLE
Can not edit pipeline after I create it

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#12229]
As title. 
Step to reproduce
1. Create a pipeline as needed.
2. Save it

I should find a edit button in the pipeline action list and edit it.

**Comment by biblesyme** [comment]
@orangedeng  Are you using the latest master?
I believe this should be fixed in the PR https://github.com/rancher/ui/pull/1748.

This was caused by some mismatch in API call.

**Comment by orangedeng** [comment]
Tested, already fixed.
