### ISSUE TITLE
Overlap in Access key in "Api &Keys" page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12223]
Rancher versions: Build from master.

This happens after I use generateKubeconfig for cluster which creates this access key.

<img width="1286" alt="screen shot 2018-03-22 at 3 44 48 pm" src="https://user-images.githubusercontent.com/4266958/37802529-1dc06882-2de8-11e8-907b-1226708cb94f.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed
