### ISSUE TITLE
project member cannot use volumes

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#12231]
A project member should be able to view/list all the Persistent Volumes and StorageClasses in the cluster and Create/Read/Update/Delete persistent volume claims in their project(s).

**Comment by sangeethah** [comment]
Tested with latest 2.0 build from master

Project member is not able to list  Persistent Volumes and StorageClasses in the cluster.

**Comment by sangeethah** [comment]
Tested with latest build from master.

A project member/project owner is able to list Persistent Volumes and StorageClasses in the cluster and Create/Read/Update/Delete persistent volume claims in their project.

They are also able to deploy workloads using the volumes created from PVClaims.
