### ISSUE TITLE
crontab doesn't run on sidekick container until Finished upgrade is ran

### ISSUE THREAD

**Issue by santachago** [rancher/rancher#12248]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent:v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.7
network-services: v0.7.19
scheduler: v0.8.3
kubernetes (if applicable):
container-crontab: V0.5.0

**Docker version: (`docker version`,`docker info` preferred)**
`$ docker info
Containers: 28
 Running: 25
 Paused: 0
 Stopped: 3
Images: 74
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-secrets
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.14GiB
Name: 1.rancher01
ID: 42LA:ZCRY:GBKO:UVON:7ZQK:KLMV:JBYR:B5EC:3WQU:D7KW:YWBB:IVVJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
`
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`$ uname -r
4.4.0-103-generic

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-Metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher - External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Use this docker-compose to create a stack, after creating it upgrade it.
```version: '2'
services:
  apache2:
    image: httpd:2.4
    tty: true
    restart: always
    labels:
      io.rancher.sidekicks: cron
  cron:
    image: php:7.0-fpm
    stdin_open: true
    tty: true
    command: su -s /bin/bash -c "echo hello" www-data
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      cron.restart_timeout: 600
      cron.schedule: '0 * * * * ?'
```

**Results:**
Currently after the upgrade process is done without finishing the upgrade (removing old containers) cron doesn't run anymore. Not in the old container nor in the new one.

**Comment by stieler-it** [comment]
This seems to be the exact behavior the [documentation](https://github.com/rancher/container-crontab) states: "If the service is in any other mode then Active, then the job is disabled." Finished Upgrade is not Active.

**Comment by loganhz** [comment]
Please check https://github.com/rancher/container-crontab#rancher-mode
