### ISSUE TITLE
Connects to existing AWS host shouldn't fail.

### ISSUE THREAD

**Issue by vicary** [rancher/rancher#12243]
**Rancher versions:**
rancher/server: v1.6.14 (stable)
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.85-38.58.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 489.2MiB
Name: ip-172-31-24-116
ID: MI5H:ATRF:AXEX:GXPC:3FWJ:WGNI:GU6R:NRJK:ZYG2:U5M2:XSWL:UGQN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

$ uname -r
4.9.85-38.58.amzn1.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Using default setup on a separate rancher server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle (default)

**Steps to Reproduce:**
Click on add host, copy the connecting script and execute on the AWS host via SSH.

**Results:**
rancher/agent keep restarting, log repeats the following segment
```
Found container ID: 153bcb21b5b18f46603462ea2a10ea35af156a29cb2f0764a98fe67a5d194494
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
Checking root: /host/run/docker/runtime-runc/moby
time="2018-03-23T07:52:05Z" level=fatal msg="Failed to find state.json"
```

According to #10502 we've met the versions of `rancher/server`, `rancher/agent` and `docker` and it shouldn't fail.

**Side note**: we have another dedicated server did connect with the difference of one minor version as `docker v17.12.1-ce`.

**Comment by superseb** [comment]
Seems to be something going on with the 17.12.0 Docker build from AWS. What OS is your dedicated server running? Workaround for now is `yum downgrade docker` to get `17.09`, which also saves you from many issues in `17.12.0`.

**Comment by vicary** [comment]
The dedicated host has CentOS Linux 7 (3.10.0) installed. Downgrading docker did work, thank you.

Though I may need to upgrade docker pass `17.12.1-ce` in the future because of a docker bug.

--tl;dr--

I am currently having 502 Bad Gateway when running nginx reverse proxy in swarm mode, see jwilder/nginx-proxy#516, which in turn leads to moby/moby#24789 and moby/moby#25698.

I suspect it was somehow related to high localhost traffic which causes kernel panics moby/moby#5618; People references it to one of the many possible causes [as a kernel bug](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1065434#yui_3_10_3_1_1401948176063_2050) where other distros should have similar issues.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
