### ISSUE TITLE
Rancher Logging should collect RKE Kubernetes component logs

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#12255]
RKE issue rancher/rke#412 adds logging support for Kubernetes components into an easily extractable place.  Rancher Logging should now add support for capturing these logs, and specifying which index these should be routed to. 

The capturing of these logs should be handled at the cluster level, and not at the project level.

**Comment by soumyalj** [comment]
Tested with master from March 30 build. 
Create a cluster using Rancher UI
Install elastic search on a machine (M1)
From the Tools -> logging tab in the UI(cluster level), choose elasticsearch/embedded elastic search and use the machine M1 as the endpoint and save.
Deploy workloads in the cluster and observe elastic search for any logs
There was no index created for the cluster in elastic search
```

# curl 'x.y.z.a:9200/_cat/indices?v'
health status index                       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .monitoring-es-6-2018.03.30 a-ZM6W0hS5awNM5Vh-vm-Q   1   0       1359            4    762.9kb        762.9kb

```

**Comment by soumyalj** [comment]
Tested with master from April 3rd. Steps below:

1. Create a cluster using Rancher UI
2. Install elastic search on a machine (M1)
3. From the Tools -> logging tab in the UI(cluster level), choose elasticsearch/embedded elastic search and use the machine M1 as the endpoint and save.
4. Deploy workloads in the cluster and observe elastic search for any logs
An index was created for the cluster(custombugtestcluster) in elastic search:
```
curl http://165.227.23.245:9200/_cat/indices?v
health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .monitoring-es-6-2018.04.03     Uw58nHYrSLmxrRVIlgagDg   1   0       1031           55    802.5kb        802.5kb
yellow open   custombugtestcluster-2018.04.03 2WH6RGZkQ56Us9lkcoaKkQ   5   1     574023            0    227.2mb        227.2mb
```
Also, used Embedded elasticsearch(includes Kibana) to view the logs. Here is the logs displayed for some of the components in Kibana
<img width="1201" alt="screen shot 2018-04-03 at 3 24 59 pm" src="https://user-images.githubusercontent.com/18536626/38278996-38fff5e4-3753-11e8-9b52-123fa5d4b2ce.png">

**Comment by gkTim** [comment]
@soumyalj Have you done anything special?
I have setup the embedded elastic search on the cluster but it seems nothings gets logged into the elasticsearch instance.
Do I need to add something to the deployment config to make it log into elasticsearch?

**Comment by PeterGrace** [comment]
@gkTim not sure if you solved this issue already, but in my case I was using CentOS7 for my nodes, which by default starts docker using the 'journald' logging driver.  Change it to json-file and the logs will be consumed.
