### ISSUE TITLE
[cli] login is not user friendly

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#12252]
Currently login requires a cacert, indexes by 0 for projects and asks for a default project if there is only 1. 

It should be easier to login.

**Comment by dramich** [comment]
This is available in https://github.com/rancher/cli/releases/tag/v1.0.0-alpha9

**Comment by sangeethah** [comment]
Tested with rancher-v1.0.0-alpha9
When there is only 1 cluster with 1 project , then user is not prompted for setting default project and existing project is set as default.

When there is more than 1 project, log in prompts user to set default project. project list indexes starts from 1.
