### ISSUE TITLE
DO cluster stuck in "removing" state(waiting on controller.cattle.io/cluster-provisioner-controller) for ever

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12254]
**Rancher versions: Build from master

**Steps to Reproduce:**

I had a cluster that was stuck in "updating" state because of this issue - #12220. 

When I tried to remove this cluster , It gets stuck in "removing" state for the same reason "waiting on controller.cattle.io/cluster-provisioner-controller"

<img width="1359" alt="screen shot 2018-03-23 at 12 25 43 pm" src="https://user-images.githubusercontent.com/4266958/37851058-b52ec0bc-2e9a-11e8-86b4-236fbb93b162.png">

**Comment by sangeethah** [comment]
[log.zip](https://github.com/rancher/rancher/files/1843385/log.zip)

**Comment by StrongMonkey** [comment]
We should probably wait to see if the cluster is really stuck at deleting. For cluster that is provisioned with DO we will try to remove digital ocean hosts before we remove the cluster and that's probably why it stuck at cluster-provisioner-controller for a while.

**Comment by alena1108** [comment]
There were a couple of issues fixed on RKE side for connections not timing out. That theoretically could have caused cluster being stuck in Removing state:

rancher/rke#446
rancher/rke#445

@sangeethah if this issue happens again, could you include rancher logs from the moment cluster.remove command was issued? To see if what @StrongMonkey suspects happens.

**Comment by sangeethah** [comment]
This issue is not reproducible anymore when testing with latest build from master.
