### ISSUE TITLE
URL parser is not working as expect for a management resource whose name has prefix "cluster"

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12265]
**Rancher versions:**
rancher/server:master 03/26

**Steps to reproduce**
The `shell` link of `cluster` resource:
`https://localhost:8443/v3/clusters/local/shell` returns
```
{
"actions": { },
"baseType": "error",
"code": "NotFound",
"links": { },
"message": "failed to find schema shell",
"status": 404,
"type": "error"
}
```

In this line: `https://github.com/rancher/norman/blob/master/parse/parse.go#L144`
For example `/v3/clusterPipelines` matches prefix for both versionpath `/v3/cluster` for clusterschemas and `/v3` for managementschemas
So `/v3/clusterPipelines/id/somelink` does not go to the right place.

**Comment by zionwu** [comment]
cc @gitlawr

**Comment by deniseschannon** [comment]
@zionwu Can you test this to see if it's working? @ibuildthecloud thinks it might be fixed now.

**Comment by gitlawr** [comment]
Verified in master 4/7
