### ISSUE TITLE
invalid dynamic driver name

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#12269]
**Rancher versions:**
rancher/server: 2.0
rancher/agent:

**Steps to Reproduce:**
1. use machine driver 
url: https://github.com/janeczku/docker-machine-vultr/releases/download/v1.3.0/docker-machine-driver-vultr-Linux-x86_64
checksum: 877a5e2fb402cb0a6510bba7b9b40d5b
2. get the error
E0326 08:13:35.287601       1 generic_controller.go:204] NodeDriverController nodedriver-x6tbr [node-driver-controller] failed with : DynamicSchema.management.cattle.io "vultr-Linux-x86config" is invalid: metadata.name: Invalid value: "vultr-Linux-x86config": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by StrongMonkey** [comment]
the correct schemaName should be `driverName+Config`.

**Comment by StrongMonkey** [comment]
Something is probably wrong in parsing the driver name. This is how we parse the driver name https://github.com/rancher/rancher/blob/b5e08e00dd88336da569716b40b5a539e96f7723/pkg/controllers/management/nodedriver/dynamic_driver.go#L239-L242

**Comment by aiwantaozi** [comment]
The node driver name is driverName = strings.Split(path.Base(u.Path), "_")[0] , and some of them include upper case, for example ```vultr-Linux-x86_64 ``` in https://github.com/janeczku/docker-machine-vultr/releases/download/v1.3.0/docker-machine-driver-vultr-Linux-x86_64, when we use is in object name of dynamic schema, it return invalid, added a PR to lower case the driver name, could you help review, thank you. https://github.com/rancher/rancher/pull/12270/commits/9df8d53f4acc0173fd8662f213b354a4a0ecb7e6

**Comment by StrongMonkey** [comment]
@vincent99 can you point out what might be the correct format for a third party docker machine driver? the parse code didn't change in 1.6 so I suspect that there might be a format for the driver url.

**Comment by vincent99** [comment]
The URL is arbitrary, but the binary that we end up with has to be `docker-machine-driver-NAME`, where `NAME` is what you would use everywhere in docker-machine.  e.g.  `docker-machine create -d NAME --NAME-size=2gb foo`. That naming scheme is how machine knows what binary to call.  I don't know that those all _have to be_ lowercase or a certain character set, but the standard ones all certainly are.

Normally the downloads are archives that are named `docker-machine-driver-NAME-Linux-x86_64.tar.gz` or similar, and inside is the actual binary properly named for use.  @janeczku seems to have stopped doing that at 1.3 for some reason.

**Comment by aiwantaozi** [comment]
k8s object name need lowercase, event the we the machine driver we download include uppercase in the docker-machine-driver-NAME, we rename them to lowercase when we copy the binary to the bin directory we use, so the binary, k8s object name, are all lowercase.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
