### ISSUE TITLE
Incomplete docker-composer.yml render the backend useless

### ISSUE THREAD

**Issue by blar** [rancher/rancher#12264]
**Rancher versions:**
rancher/server: 1.6.15

**Steps to Reproduce:**
$ docker run --rm -p 8080:8080 rancher/server

Add a new stack with the following docker-composer.yml

    version: '2'
    services:
        smtp:
            image: rancher/external-service

**Results:**

The service is not visible in the stack and cannot be removed. After some clicks the complete web interface of rancher is corrupted do to an error in javascript. Maybe you are able to remove the entire environment to recover to a healthy state.

<img width="1202" alt="screenshot 2018-03-24 18 47 04" src="https://user-images.githubusercontent.com/111508/37867078-d731d57e-2f93-11e8-8261-cbec46ea1e0c.png">

**Comment by loganhz** [comment]
Please try v1.6.22. It's fixed now.

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
