### ISSUE TITLE
UI - Rancher v2 apikeys font/spacing issue

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#12274]
**Rancher versions:**
rancher/server: v2, alpha21

**Docker version: (`docker version`,`docker info` preferred)**
17.03.02

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.03

Spacing issues in display, also, this font in v2 seems too wide, would prefer the font from Rancher v1.6.x or some other Powerline fonts.

![screen shot 2018-03-26 at 10 58 17 am](https://user-images.githubusercontent.com/11069351/37918381-7faec0f6-30e6-11e8-95e3-54ca9cceca64.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
