### ISSUE TITLE
[2.0.0-alpha23] Segmentation violation when creating custom cluster

### ISSUE THREAD

**Issue by bjornmagnusson** [rancher/rancher#12272]
**Rancher versions:**
rancher/server: v2.0.0-alpha23
rancher/agent: v2.0.0-alpha23

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.9.5

**Docker version: (`docker version`,`docker info` preferred)**
docker info
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 3.702 GiB
Name: se-nm-cirrus-rke
ID: BFUC:COHW:AKSO:ODQT:A63I:NH75:HJKA:UQWA:JRG4:N47F:HNMO:HBL3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

uname -r
3.10.0-693.21.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Virtual Machine using libvirt

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, custom RKE

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Add Custom Cluster
Select roles etcd/control/worker
Network: flannel
Kubernetes version: 1.8.4 / 1.9.5

**Results:**
2018/03/26 12:27:16 [INFO] ClusterController cluster-grjdg completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
2018/03/26 12:27:16 [INFO] Provisioning cluster [cluster-grjdg]
2018/03/26 12:27:16 [INFO] Creating cluster [cluster-grjdg]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17f4ac1]

goroutine 1520443 [running]:
github.com/rancher/rancher/vendor/github.com/docker/distribution/reference.SplitHostname(0x0, 0x0, 0x4ba209a, 0x1d, 0x4ba2043, 0x1d)
        /go/src/github.com/rancher/rancher/vendor/github.com/docker/distribution/reference/reference.go:183 +0xd1
github.com/rancher/rancher/vendor/github.com/docker/distribution/reference.TrimNamed(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/docker/distribution/reference/reference.go:323 +0x39
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterKubernetesImageVersion(0xc43554a500, 0xa38c240, 0xc44b19e960)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:87 +0x2c2
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterDefaults(0xc43554a500, 0xa38c240, 0xc44b19e960)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:76 +0x438
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.ParseCluster(0xa38c240, 0xc44b19e960, 0xc44142bc00, 0x0, 0x0, 0xc42848d590, 0x2e, 0xc427c58bb0, 0xc427c58bc0, 0xc4361f07c0, ...)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:135 +0x173
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0xa38c240, 0xc44b19e960, 0xc44142bc00, 0xc427c58bb0, 0xc427c58bc0, 0xc4361f07c0, 0x0, 0xc42848d590, 0x2e, 0x0, ...)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:49 +0x104
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Create(0xc420c64060, 0xa38c240, 0xc44b19e960, 0xc4361f04a0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:134 +0x28c
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Create(0xc42012a080, 0xa38c240, 0xc434aff200, 0xc4361f04a0, 0xc42012a080, 0x4e123fb40cf8c05b, 0x116298ef75e79d6b)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:45 +0x6d
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Create_Handler(0x4830620, 0xc42012a080, 0xa38c240, 0xc434aff200, 0xc45f8162a0, 0x0, 0x0, 0x0, 0x5597247e2132778a, 0x90e2c85c74b7f453)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:546 +0x276
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4209f8160, 0xa39f220, 0xc44f81f380, 0xc460fe1b80, 0xc420c64210, 0xa330ea0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x96e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4209f8160, 0xa39f220, 0xc44f81f380, 0xc460fe1b80, 0x0)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1528
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc45e46ad80, 0xc4209f8160, 0xa39f220, 0xc44f81f380, 0xc460fe1b80)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1

**Comment by superseb** [comment]
Can you provide complete logging from the `rancher/server` container when this happens?

**Comment by bjornmagnusson** [comment]
I am not seeing this issue anymore, since upgrade to 2.0.0-beta. Currently on beta3. Works fine.

**Comment by superseb** [comment]
Ok thanks, let us know if you see it again and please capture all logs.
