### ISSUE TITLE
Nodes get stuck in "Registering" state sometimes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12276]
Rancher versions: Build from master - Mar 25

Steps to reproduce the problem:
I sometimes get provisioning errors when trying to install DO cluster with 1 node. 

<img width="1289" alt="screen shot 2018-03-26 at 10 18 22 am" src="https://user-images.githubusercontent.com/4266958/37921573-11153276-30df-11e8-9556-4927065e58f8.png">

I also see the same case were host get stuck in "waiting to register with Kubernetes" state when adding more worker nodes to a an existing 1 node cluster. In this case , the host got provisioned eventually after may be 1/2 hour.

But in the case of fresh install , it never recovered.

**Comment by soumyalj** [comment]
Observed the same issue for a three node cluster with all three nodes on each of them. 
One of the nodes came up fine. Other 2 nodes were stuck in registering state. RKE reported that cluster built successfully but the nodes are stuck in registering state.

<img width="1260" alt="screen shot 2018-03-27 at 4 01 46 pm" src="https://user-images.githubusercontent.com/18536626/37999548-3470649e-31d8-11e8-8b4d-c91a8cae2e70.png">

Server logs
```
E0327 22:24:55.030331       1 generic_controller.go:204] ProjectRoleTemplateBindingController project-9tngq/creator [cluster-prtb-sync] failed with : couldn't ensure roles: couldn't create role project-owner: Post https://104.131.31.165:6443/apis/rbac.authorization.k8s.io/v1/clusterroles: Failed to dial ssh using address [104.131.31.165:22]: ssh: handshake failed: EOF
E0327 22:24:55.304442       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1beta1.CronJob: Get https://104.131.31.165:6443/apis/batch/v1beta1/watch/cronjobs?resourceVersion=1&timeoutSeconds=586: Failed to dial ssh using address [104.131.31.165:22]: ssh: handshake failed: read tcp 172.17.0.2:60574->104.131.31.165:22: read: connection reset by peer
E0327 22:24:56.844830       1 generic_controller.go:204] ClusterRoleTemplateBindingController cluster-5nzdm/user-h4cmj-admin [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
E0327 22:24:56.920822       1 generic_controller.go:204] RoleTemplateController project-owner [cluster-roletemplate-sync] failed with : couldn't ensure roles: couldn't create role project-owner: clusterroles.rbac.authorization.k8s.io "project-owner" already exists
2018/03/27 22:24:56 [ERROR] error updating ns ingress-nginx status: Operation cannot be fulfilled on namespaces "ingress-nginx": the object has been modified; please apply your changes to the latest version and try again
E0327 22:24:56.935181       1 generic_controller.go:204] RoleTemplateController cluster-owner [cluster-roletemplate-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
2018/03/27 22:24:57 [ERROR] error updating ns kube-system status: Operation cannot be fulfilled on namespaces "kube-system": the object has been modified; please apply your changes to the latest version and try again
2018/03/27 22:24:57 [INFO] Successfully created default network policy for project: project-9tngq
2018/03/27 22:24:57 [INFO] adding label field.cattle.io/projectId=project-9tngq to namespace=default
2018/03/27 22:24:57 [ERROR] error updating ns cattle-system status: Operation cannot be fulfilled on namespaces "cattle-system": the object has been modified; please apply your changes to the latest version and try again



```

**Comment by alena1108** [comment]
@sangeethah @soumyalj can we retest this bug on the latest, given the refactoring around cluster provisioning? Please reassign it back to me if the issue still present.

**Comment by soumyalj** [comment]
Tested with master from April 17th build. Created a single node cluster with all roles and 3 node cluster with all roles on each of them . Clusters got deployed successfully and workloads were created fine.

**Comment by nrh387** [comment]
I run into the same issue Nodes get stuck in "Registering" with the rancher 2.0 rc3
The OS is the Linux iZ947ei2rr7Z 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
The docker version 
Docker version 17.03.2-ce, build f5ec1e2

here is logs from rancher server
2018/05/02 06:07:22 [INFO] projectSyncer: createDefaultNetworkPolicy: successfully created default network policy for project: project-bprsm
2018/05/02 06:07:23 [ERROR] error updating ns kube-system status: Operation cannot be fulfilled on namespaces "kube-system": the object has been modified; please apply your changes to the latest version and try again
E0502 06:07:23.145874       1 generic_controller.go:204] ClusterRoleTemplateBindingController c-dktfr/user-jb6md-admin [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
E0502 06:07:23.152693       1 generic_controller.go:204] ProjectRoleTemplateBindingController project-bprsm/creator [cluster-prtb-sync] failed with : couldn't create role project-owner-promoted: clusterroles.rbac.authorization.k8s.io "project-owner-promoted" already exists
2018/05/02 06:07:23 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-bprsm to namespace=default
2018/05/02 06:07:24 [ERROR] error updating ns cattle-system status: Operation cannot be fulfilled on namespaces "cattle-system": the object has been modified; please apply your changes to the latest version and try again
2018/05/02 06:07:26 [INFO] Handling backend connection request [c-dktfr]
E0502 06:08:15.692414       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.NodeStatus
 2018-05-02 06:09:49.739968 I | mvcc: store.index: compact 22565
2018-05-02 06:09:49.742531 I | mvcc: finished scheduled compaction at 22565 (took 1.513305ms)

**Comment by nrh387** [comment]
This issue could be reproduced on the v2.0-GA version too.

2018/05/02 09:26:51 [ERROR] error updating ns cattle-system status: Operation cannot be fulfilled on namespaces "cattle-system": the object has been modified; please apply your changes to the latest version and try again
2018/05/02 09:27:26 [INFO] Handling backend connection request [c-r5vp8]
 2018-05-02 09:27:45.444790 I | mvcc: store.index: compact 1568
2018-05-02 09:27:45.447570 I | mvcc: finished scheduled compaction at 1568 (took 1.763441ms)
dynamicschemas.management.cattle.io "nodetemplateconfig" already exists   2018-05-02 09:32:45.451900 I | mvcc: store.index: compact 2332
2018-05-02 09:32:45.454570 I | mvcc: finished scheduled compaction at 2332 (took 2.040325ms)

**Comment by MihaiASSECO** [comment]
Does anyone have a solution to this issue?
V'been trying to deploy a new worker node (CentOS) in the environment and it keeps getting stuck in this Registering status even after a system reboot.

**Comment by majidaldo** [comment]
i got this problem. i'm following the current instructions (and i had a rancher2  working from a few weeks ago).

**Comment by deniseschannon** [comment]
Can you please cereate a new issue with more details of how you are creating your node. The specific use case for this issue was already fixed and closed and it's unclear that your use case is exactly the same.

Details about how you created your node would be ideal:

Assuming node templates, which provider, how many nodes and what roles. Or if you're adding additional nodes to an existing cluster, how is your cluster set up and how are you adding additional nodes.

**Comment by majidaldo** [comment]
i do have connectivity to my host. something is strange with the etcd process. when i try to add a node:
"[network] Port check for ports: [172.31.53.11:2379, 172.31.53.11:2380] failed on host: [172.31.32.26]"

on that node, i can netcat fine into those ports on the host. however, i can't do so inside a container.

**Comment by MihaiASSECO** [comment]
Hi Denise,
Followed your advice and opened a new issue. The error message looks the same, but not sure if it's the same issue.
Thanks in advance to anyone that can help me get this sorted out!

**Comment by majidaldo** [comment]
I cleared my iptables to get things to connect. I don't know if the rancher installer messed with my iptables.

**Comment by majidaldo** [comment]
also, clear the directories metioned in the Cluster Remove section of the RKE readme.

**Comment by admiralspark** [comment]
Hello. 

I'm running into the same issue, I didn't bother with any of these fixes mentioned here. 

If you parse through the API, you'll find that the cluster information doesn't populate properly if you have a single etcd server and you add a second node with the "worker" role only. 

A reboot of the Node while it is stuck Registering brings up the services correctly and will properly register the Node at that time.
