### ISSUE TITLE
Rancher Kubernetes and Stacks

### ISSUE THREAD

**Issue by klinux** [rancher/rancher#12271]
Hi,
I have a doubot about the kubernetes environment, when I create the environment, if I create a Stack on rancher ui, the containers don't appear in kubernetes dashboard, once kubernetes configured I have to create my containers only with kubectl or kubernete dashboard? The stacks that I've created works with kubernetes engine or not?

Thank you

**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Comment by superseb** [comment]
No, the functionality from Rancher (Cattle) is used to deploy/upgrade Kubernetes. From there on out, you can schedule your containers using the built-in kubectl shell, remote kubectl with the generated config or through the Kubernetes Dashboard.
