### ISSUE TITLE
vSphere Node Template - 2.0 alpha21

### ISSUE THREAD

**Issue by rarean** [rancher/rancher#12273]
**Rancher versions:**
rancher/server: 2.0-alpha21

**Node Template: vSphere**
Configuration window not displaying correctly

**Steps to Reproduce:**
* Use docker [rancher/server:preview](https://hub.docker.com/r/rancher/server/tags/) and start normal instance
* Navigate to setup new cluster with vSphere
* Add required *Node Template* 
* The popup configuration window will provide options for vSphere

**Issue**
Screen shot attached shows issue where form labels appear as though they are variables. Furthermore, i had to reduce screen resolution (zoom out) to 50% before the form would appear correctly in Firefox & Chrome. 

**Results:**
![image](https://user-images.githubusercontent.com/3702244/37910594-8829803a-30d3-11e8-8a45-e1739c455291.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed.  This has been fixed in newest build.
