### ISSUE TITLE
Stack creation using api: Error (yaml: found unexpected ':')

### ISSUE THREAD

**Issue by pariminaresh** [rancher/rancher#12282]
**Rancher versions:**
rancher/server: v1.6.6
rancher/agent:

**API**: /v2-beta/projects/${PROJECT_ID}/stacks

**Steps to Reproduce:**
      - Read compose file contents as strings, docker_compose.yml and rancher_compose.yml. Since the API documentation says the fields dockerCompose and rancherCompose are of 'string' type.
      - Pass the data to the API to create a stack in rancher

**Pseudo code**
     - docker_compose = readYaml ('docker_compose.yml') //e.g: [version:2, services:[Webserver:[image:image_repo/php54, stdin_open:true, tty:true]]]
       rancher_compose = readYaml('rancher_compose.yml') //e.g: [version:2, services:[Webserver:[scale:1, start_on_create:true]]]
      
       curl -u <accesskey>:<secretkey> -X POST -H 'Content-Type: application/json' -d '{ "description": "test stack using api", "name": "test","dockerCompose": $docker_compose, "rancherCompose": $rancher_compose }' http://<rancher_host>:8080/v2-beta/projects/<project_id>/stacks

**Results:**
   The stack is getting created in rancher server but with an error as **Error (yaml: found unexpected ':')**.
  - **View in API** link show as "transitioning": "error",
                                        "transitioningMessage": "yaml: found unexpected ':'",
  

Please let me know whats wrong here.And when I tried passing yaml contents as a json string it works.So I wonder if something to do with yaml string representation.

Your help is appreciated.Thanks

**Comment by pariminaresh** [comment]
The problem is with yaml formatting to a string type and looks like 'readYaml' is not giving the proper yaml string, something like:  "version: '2'\nservices:\n  Webserver:\n    image: jnj.artifactrepo-dev.jnj.com/httpd24:php54\n    stdin_open: true".

My question now is whats the best way to do this programmatically, to be compatible with the rancher api?

**Comment by pariminaresh** [comment]
This is a tricky part to go with yaml string. So just converted that to a json string and that solves the issue of loading compose file data.Though the stack(created using api) goes to a 'Unhealthy' state instead of 'Active'.Surprisingly the same stack is getting created in Active state when tried from Rancher UI.

I'm wondering whats wrong with the API here.Please let me know if anyone else see same behaviour.

Appreciate your help.Thanks

**Comment by pariminaresh** [comment]
@vincent99 Thanks.

readYaml reads it fine and returns a 'List' representation of yaml.And as you said it can't be directly used in as a yaml string and need to convert it to be compatible with the API.In my case, I felt it is easier to load json string out of that.

As I mentioned, it is creating the stack fine but with 'Unhealthy' state and manual start pulling that to 'Active' state. What could be the reason for this behavior? is it something expected?

**Comment by loganhz** [comment]
I guess you can check what UI sends to backend in chrome dev tool.

![image](https://user-images.githubusercontent.com/21168270/46566134-7061fc00-c94b-11e8-8dfd-60291cbf1a46.png)

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
