### ISSUE TITLE
cleanup tokens when user is deleted

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#12287]
we cleanup GRBs, CRTB, PRTB when a user is deleted, but not tokens. We need to clean up tokens.

Otherwise, when you try to use a deleted user's token, you get
```
error from server (InternalError): an error on the server ("{\"Cause\":null}") has prevented the request from succeeding
```

related
https://github.com/rancher/rancher/issues/11379
https://github.com/rancher/rancher/issues/11079
we should see if we can figure out why the message is so awful

**Comment by sangeethah** [comment]
Tested with latest build from master:

When a deleted user tries to access cluster using kubectl , he presented with a more readable error message:

```
Sangeethas-MBP:~ sangeethahariharan1$ kubectl get namespaces
error: You must be logged in to the server (the server has asked for the client to provide credentials (get namespaces))
Sangeethas-MBP:~ sangeethahariharan1$ kubectl get nodes
error: You must be logged in to the server (the server has asked for the client to provide credentials (get nodes))
Sangeethas-MBP:~ sangeethahariharan1$ kubectl get pods
error: You must be logged in to the server (the server has asked for the client to provide credentials (get pods))
Sangeethas-MBP:~ sangeethahariharan1$ 

```

Scenario mentioned in this issue - https://github.com/rancher/rancher/issues/11378 results in user being presented with the above message.
