### ISSUE TITLE
Unable to use kube-ctl because of missing CA certificate in RKE cluster

### ISSUE THREAD

**Issue by mysim1** [rancher/rancher#12283]
**Rancher server version -** 
DockerHub: master (26 march 2018)

**Rancher agent version -**
DockerHub: master (26 March 2018)

**Steps to reproduce the problem:**
- Create a PKE Cluster
- Add Worker, Etcd, Controlplane node(s)
- Navigate to Cluster Dashboard
- Click Launch kubectl
- Execute random kubectl command

**User is presented with this error message:**
```error: unable to read certificate-authority /etc/kubernetes/ssl/ca.pem for Default due to open /etc/kubernetes/ssl/ca.pem: no such file or directory```

**Docker version: (`17.03.2`)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Default RKE

**Results:**
I did find out the specific pem file is missing.

**Comment by ibuildthecloud** [comment]
Fix here: https://github.com/rancher/rancher/pull/12285/commits/cfadad1a2a17eac60df147978580ea79db3688dd

**Comment by deniseschannon** [comment]
Tested with latest master (5pm at 3/26).
