### ISSUE TITLE
Add support for deploying a cluster via PKS

### ISSUE THREAD

**Issue by JasonMorgan** [rancher/rancher#12286]
**Rancher versions:**
rancher/server:preview

**Environment Template: Kubernetes

I'd like to add a tile to the Rancher 2.0 UI that would allow me to spin up clusters via [PKS](https://pivotal.io/platform/pivotal-container-service). I'd be happy to work on a PR for it if someone could point me in the right direction.

**Comment by superseb** [comment]
Hosted k8s integration happens in https://github.com/rancher/kontainer-engine, it needs a Golang library and a little kontainer-engine glue.

**Comment by JasonMorgan** [comment]
Way OBE at this point.
