### ISSUE TITLE
Editing a secret by changing the key or adding a new key/value pair is not reflected in the workload

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12290]
**Rancher versions:**
rancher/server: Master from March 26th build
rancher/agent:

**Steps to Reproduce:**
1. Create a secret by providing test=value as key/value pair
2. Create a workload to use the secret created in the env variables(add from source) option 
3. Once the workload is created, view the key/value pair in the shell of the workload(by typing env)
4. Edit the secret to change the key and also add another key/value pair

The workload does not reflect the edited key and also the new key/value pair

**Comment by alena1108** [comment]
Changing the key not being reflected on k8s side, is tracked in the separate issue:
https://github.com/rancher/rancher/issues/11607

New key being added and/or existing value being modified, gets reflected in the pod in about ~1 min. That is expected as per 

https://kubernetes.io/docs/concepts/configuration/secret/
```
Mounted Secrets are updated automatically

When a secret being already consumed in a volume is updated, projected keys are eventually updated as well. Kubelet is checking whether the mounted secret is fresh on every periodic sync. However, it is using its local ttl-based cache for getting the current value of the secret. As a result, the total delay from the moment when the secret is updated to the moment when new keys are projected to the pod can be as long as kubelet sync period + ttl of secrets cache in kubelet.
```

@soumyalj please validate the above.

**Comment by soumyalj** [comment]
@alena1108 : When a new key is added to the secret, it gets updated in the pod after around a minute. This is true only for workloads using secret as volume. 
If a workload is deployed with secret as an environment variable, change in the secret is not updated
