### ISSUE TITLE
Secret deletion is not reflected in the workload

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12293]
Rancher versions:
rancher/server: Master from March 26th build

Steps to Reproduce:

1. Create a secret by providing test=value as key/value pair
2. Create a workload to use the secret created in the env variables(add from source) option
3. Once the workload is created, view the key/value pair in the shell of the workload(by typing env)
4. Delete the secret

The workload still shows the key/value pair associated with the secret. Is this the expected behavior ?

**Comment by alena1108** [comment]
@soumyalj yes, it's expected. K8s doesn't delete the references from the parent object when the child object is gone. It is a generic issue, not just secret specific. You can file it as a generic one, where we can capture all the possible situations, and later on decide whether we want to do something about it on rancher side.
