### ISSUE TITLE
[Pipeline] 

### ISSUE THREAD

**Issue by coolyrat** [rancher/rancher#12300]
**Rancher versions:**
rancher/server: rancher/server:v1.6.14
rancher/agent: rancher/agent:v1.2.9

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec:  rancher/net:v0.13.7   rancher/net:holder
network-services: rancher/network-manager:v0.7.19    rancher/metadata:v0.9.5
scheduler: rancher/scheduler:v0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
[root@mycentos ~]# docker info
Containers: 33
 Running: 28
 Paused: 0
 Stopped: 5
Images: 46
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.15.3-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853 GiB
Name: mycentos
ID: ZGVD:LBJU:PIJE:YDW4:CZMO:GGNM:BPXS:M7MZ:WC6J:U7BZ:UEJ7:HTB6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://127.0.0.1:8118
Https Proxy: http://127.0.0.1:8118
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 harbor.eekui.group:8090
 127.0.0.0/8
Registry Mirrors:
 https://nlucozp2.mirror.aliyuncs.com
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
[root@mycentos ~]# uname -r
4.15.3-1.el7.elrepo.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Aliyun ECS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. install rancher pipeline from the app store
2. wait for all services is active
3. click pipeline from the menu

**Results:**
a blank page, open chrome developer tools and saw 2 assert error.

GET http://rancher.xxx.xxx:8080/r/projects/1a5/pipeline-ui/assets/vendor-f35e8de8c7972ef94cb146fb35f4ff41.js net::ERR_CONTENT_LENGTH_MISMATCH
---

GET http://rancher.xxx.xxx:8080/r/projects/1a5/pipeline-ui/assets/ui-22ca4c4e587549b97fbf624a8a990a3d.js net::ERR_CONTENT_LENGTH_MISMATCH

**Comment by coolyrat** [comment]
it seems the asserts are loading for too long, and chrome crash during the loading

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
