### ISSUE TITLE
Feature Request: Ability to edit yml files prior to launch from catalog

### ISSUE THREAD

**Issue by levensailor** [rancher/rancher#12301]
Maybe change "Preview" verbiage to "Staged"

Component | Version
-- | --
Rancher | v1.6.14
Cattle | v0.183.37
User Interface | v1.6.37
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
