### ISSUE TITLE
read-only role should be at the same level as member/owner for projects

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12318]
<img width="659" alt="screen shot 2018-03-27 at 3 45 52 pm" src="https://user-images.githubusercontent.com/11410997/37999037-f53548aa-31d5-11e8-8802-72388cc1534f.png">

We should add Read Only out of the "Custom" section and under "Member".

**Comment by tfiduccia** [comment]
This needs to be added to:

Add Cluster/Edit Cluster (Roles drop-down) & Add Member from cluster menu
Add Project/Edit Project (Roles drop-down)

**Comment by westlywright** [comment]
@tfiduccia I'll fix the project/edit project but `read-only` role has a project context so adding to the Cluster roles would not do anything afaik

**Comment by deniseschannon** [comment]
@westlywright - You are correct, it's only related to project.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/3
Verified fixed
