### ISSUE TITLE
[cli] Add inspect command

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#12315]
add `inspect` command, see 1.6 for example.

**Comment by dramich** [comment]
Available in v1.0.0-alpha13

**Comment by soumyalj** [comment]
Tested with master, `inspect` command works for few of the resources like cluster, ingress, node.
The below issues have been logged for` inspect` command
https://github.com/rancher/rancher/issues/12831
https://github.com/rancher/rancher/issues/12847
