### ISSUE TITLE
[cli] Use kubeconfig with kubectl

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#12316]
When running `rancher kubectl` the command should use the kubeconfig for the current cluster to execute the command and not rely on the local kubeconfig file.

**Comment by deniseschannon** [comment]
Available with v1.0.0-alpha11

**Comment by sangeethah** [comment]
Tested with v1.0.0-alpha11.
```rancher kubectl``` command can be used to execute kubectl commands for the current cluster.
