### ISSUE TITLE
LB and backend service, within the same stack, cant communicate using network policy (allow - within stack)

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#12323]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3-1
ipsec: v0.2.2
network-services: v0.2.8
scheduler: v0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
- enable network policy
- configure network policy to use 'within service'
- create a stack containing a backend service (httpd for example) and a LB fronting it

**Results:**
LB throws 503 errors, cant reach the backend service.

**Note**
this works fine if the policy is set to allow communication between linked services.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
