### ISSUE TITLE
Allow unsupported docker version fails on coreos

### ISSUE THREAD

**Issue by marufbd** [rancher/rancher#12329]
**Rancher versions:**
rancher/server:preview
rancher/agent: agent:v2.0.0-alpha23

**Infrastructure Stack versions:**
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
*Master*
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:10:31 2018
 OS/Arch:       linux/amd64

*Custom Node*
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:10:31 2018
 OS/Arch:       linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
*Master*
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.4.0
VERSION_ID=1688.4.0
BUILD_ID=2018-03-27-0319
PRETTY_NAME="Container Linux by CoreOS 1688.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

*Custom Node*
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.4.0
VERSION_ID=1688.4.0
BUILD_ID=2018-03-27-0319
PRETTY_NAME="Container Linux by CoreOS 1688.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Digital Ocean

**Steps to Reproduce:**
On Master run:
`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview`
- Accessed web ui from my browser at: https://myserverdomain.com
- Added a custom cluster from the web ui
- Copied custom node docker run code from web ui

`docker run -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock --net=host rancher/agent:v2.0.0-alpha23 --server https://myserverdomain.com --token rzzsslq5nfp84sm7gfwpp88zjd6dxhhnhf9p82jf4s8gml6lphwn5d --ca-checksum 3c5736ddf12ac9bddc607ca36ba8ddff104ad6ec2f4b2e34d369d38e32e5af73 --etcd --controlplane
`
**Results:**
Master logs:

2018/03/28 12:45:53 [INFO] Provisioning cluster [cluster-2dwff]
2018/03/28 12:45:53 [INFO] Creating cluster [cluster-2dwff]
2018/03/28 12:45:53 [INFO] cluster [cluster-2dwff] provisioning: Building Kubernetes cluster
2018/03/28 12:45:53 [INFO] cluster [cluster-2dwff] provisioning: [dialer] Setup tunnel for host [159.65.94.161]
2018/03/28 12:45:53 [ERROR] cluster [cluster-2dwff] provisioning: Unsupported Docker version found [17.12.1-ce], supported versions are [1.12.6 1.13.1 17.03.2]
2018/03/28 12:45:53 [INFO] cluster [cluster-2dwff] provisioning: [network] Deploying port listener containers
2018/03/28 12:45:55 [INFO] cluster [cluster-2dwff] provisioning: [network] Successfully pulled image [alpine:latest] on host [159.65.94.161]
2018/03/28 12:45:55 [INFO] cluster [cluster-2dwff] provisioning: [network] Successfully started [rke-etcd-port-listener] container on host [159.65.94.161]
2018/03/28 12:45:55 [INFO] cluster [cluster-2dwff] provisioning: [network] Successfully started [rke-cp-port-listener] container on host [159.65.94.161]
2018/03/28 12:45:55 [INFO] cluster [cluster-2dwff] provisioning: [network] Port listener containers deployed successfully
2018/03/28 12:45:55 [INFO] cluster [cluster-2dwff] provisioning: [network] Running control plane -> etcd port checks
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [network] Successfully started [rke-port-checker] container on host [159.65.94.161]
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [network] Running control plane -> worker port checks
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [network] Successfully started [rke-port-checker] container on host [159.65.94.161]
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [network] Running workers -> control plane port checks
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [network] Removing port listener containers
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [remove/rke-etcd-port-listener] Successfully removed container on host [159.65.94.161]
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [remove/rke-cp-port-listener] Successfully removed container on host [159.65.94.161]
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [network] Port listener containers removed successfully
2018/03/28 12:45:56 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Attempting to recover certificates from backup on host [159.65.94.161]
2018/03/28 12:45:57 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Successfully started [cert-fetcher] container on host [159.65.94.161]
2018/03/28 12:45:57 [INFO] cluster [cluster-2dwff] provisioning: [certificates] No Certificate backup found on host [159.65.94.161]
2018/03/28 12:45:57 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Generating CA kubernetes certificates
2018/03/28 12:45:58 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Generating Kubernetes API server certificates
2018/03/28 12:45:59 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Generating Kube Controller certificates
2018/03/28 12:45:59 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Generating Kube Scheduler certificates
2018/03/28 12:46:00 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Generating Kube Proxy certificates
2018/03/28 12:46:00 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Generating Node certificate
2018/03/28 12:46:01 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Generating admin certificates and kubeconfig
2018/03/28 12:46:01 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Generating etcd-159.65.94.161 certificate and key
2018/03/28 12:46:01 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Temporarily saving certs to control host [159.65.94.161]
2018/03/28 12:46:04 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Successfully pulled image [rancher/rke-cert-deployer:v0.1.1] on host [159.65.94.161]
2018/03/28 12:46:09 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Saved certs to control host [159.65.94.161]
2018/03/28 12:46:09 [INFO] cluster [cluster-2dwff] provisioning: [reconcile] Reconciling cluster state
2018/03/28 12:46:09 [INFO] cluster [cluster-2dwff] provisioning: [reconcile] This is newly generated cluster
2018/03/28 12:46:09 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Deploying kubernetes certificates to Cluster nodes
2018/03/28 12:46:14 [INFO] cluster [cluster-2dwff] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-058615682/kube_config_cluster.yml]
2018/03/28 12:46:14 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Successfully deployed kubernetes certificates to Cluster nodes
2018/03/28 12:46:14 [INFO] cluster [cluster-2dwff] provisioning: Pre-pulling kubernetes images
2018/03/28 12:46:14 [INFO] cluster [cluster-2dwff] provisioning: Kubernetes images pulled successfully
2018/03/28 12:46:14 [INFO] cluster [cluster-2dwff] provisioning: [etcd] Building up Etcd Plane..
2018/03/28 12:46:19 [INFO] cluster [cluster-2dwff] provisioning: [etcd] Successfully pulled image [rancher/coreos-etcd:v3.0.17] on host [159.65.94.161]
2018/03/28 12:46:19 [INFO] cluster [cluster-2dwff] provisioning: [etcd] Successfully started [etcd] container on host [159.65.94.161]
2018/03/28 12:46:20 [INFO] cluster [cluster-2dwff] provisioning: [etcd] Successfully started [rke-log-linker] container on host [159.65.94.161]
2018/03/28 12:46:20 [INFO] cluster [cluster-2dwff] provisioning: [remove/rke-log-linker] Successfully removed container on host [159.65.94.161]
2018/03/28 12:46:20 [INFO] cluster [cluster-2dwff] provisioning: [etcd] Successfully started Etcd Plane..
2018/03/28 12:46:20 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Building up Controller Plane..
2018/03/28 12:46:22 [INFO] cluster [cluster-2dwff] provisioning: [sidekick] Successfully pulled image [rancher/rke-service-sidekick:v0.1.0] on host [159.65.94.161]
2018/03/28 12:47:21 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Successfully pulled image [docker.io/rancher/k8s:v1.9.5-rancher1-1] on host [159.65.94.161]
2018/03/28 12:47:21 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Successfully started [kube-apiserver] container on host [159.65.94.161]
2018/03/28 12:47:21 [INFO] cluster [cluster-2dwff] provisioning: [healthcheck] Start Healthcheck on service [kube-apiserver] on host [159.65.94.161]
2018/03/28 12:47:32 [INFO] cluster [cluster-2dwff] provisioning: [healthcheck] service [kube-apiserver] on host [159.65.94.161] is healthy
2018/03/28 12:47:32 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Successfully started [rke-log-linker] container on host [159.65.94.161]
2018/03/28 12:47:33 [INFO] cluster [cluster-2dwff] provisioning: [remove/rke-log-linker] Successfully removed container on host [159.65.94.161]
2018/03/28 12:47:33 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Successfully started [kube-controller-manager] container on host [159.65.94.161]
2018/03/28 12:47:33 [INFO] cluster [cluster-2dwff] provisioning: [healthcheck] Start Healthcheck on service [kube-controller-manager] on host [159.65.94.161]
2018/03/28 12:47:38 [INFO] cluster [cluster-2dwff] provisioning: [healthcheck] service [kube-controller-manager] on host [159.65.94.161] is healthy
2018/03/28 12:47:38 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Successfully started [rke-log-linker] container on host [159.65.94.161]
2018/03/28 12:47:38 [INFO] cluster [cluster-2dwff] provisioning: [remove/rke-log-linker] Successfully removed container on host [159.65.94.161]
2018/03/28 12:47:38 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Successfully started [kube-scheduler] container on host [159.65.94.161]
2018/03/28 12:47:38 [INFO] cluster [cluster-2dwff] provisioning: [healthcheck] Start Healthcheck on service [kube-scheduler] on host [159.65.94.161]
2018/03/28 12:47:43 [INFO] cluster [cluster-2dwff] provisioning: [healthcheck] service [kube-scheduler] on host [159.65.94.161] is healthy
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Successfully started [rke-log-linker] container on host [159.65.94.161]
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [remove/rke-log-linker] Successfully removed container on host [159.65.94.161]
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [controlplane] Successfully started Controller Plane..
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [authz] Creating rke-job-deployer ServiceAccount
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [authz] rke-job-deployer ServiceAccount created successfully
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [authz] Creating system:node ClusterRoleBinding
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [authz] system:node ClusterRoleBinding created successfully
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Save kubernetes certificates as secrets
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [certificates] Successfully saved certificates as kubernetes secret [k8s-certs]
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [state] Saving cluster state to Kubernetes
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [state] Successfully Saved cluster state to Kubernetes ConfigMap: cluster-state
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [worker] Building up Worker Plane..
2018/03/28 12:47:44 [INFO] cluster [cluster-2dwff] provisioning: [sidekick] Sidekick container already created on host [159.65.94.161]
E0328 12:47:44.720382       1 generic_controller.go:204] ClusterController cluster-2dwff [cluster-provisioner-controller] failed with : [workerPlane] Failed to bring up Worker Plane: Failed to create [kubelet] container on host [159.65.94.161]: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate"
2018/03/28 12:47:44 [INFO] ClusterController cluster-2dwff completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 30s
2018/03/28 12:47:45 [INFO] ClusterController cluster-2dwff completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 30s

**Comment by superseb** [comment]
It's because of Docker 17.12.1, see https://github.com/rancher/rancher/issues/11897 for more info. Let me know if this does not solve your issue.
