### ISSUE TITLE
Upgrade to 1.6.15 failing

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#12324]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: rancher/healthcheck:v0.3.3

**Infrastructure Stack versions:**
healthcheck:
ipsec: rancher/net:v0.13.7
network-services: rancher/network-manager:v0.7.19

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack, KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Upgrade from v1.6.13 to v1.6.14 was ok, to v1.6.15 it failing on IPSec infra stack deployment/upgrade

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle v0.183.37

**Steps to Reproduce:**
v1.6.13 upgrade server to v1.6.15, than upgrade infrastructure components.

**Results:**

- all agents disconnects, after attempt to put them back or add new hosts ipsec failing with this errors:

```
rancher-ui_1  | 2018-03-27 11:14:11,710 ERROR [9cd55eb9-fb94-41e5-b57d-113b43a265af:112650328] [instance:1659967] [instance.start] [] [cutorService-27] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=111206]: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/rancher-entrypoint.sh\": stat /rancher-entrypoint.sh: no such file or directory": unknown
rancher-ui_1  | 2018-03-27 11:14:11,734 ERROR [:] [] [] [] [cutorService-27] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.activate.reply;agent=111206]: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/rancher-entrypoint.sh\": stat /rancher-entrypoint.sh: no such file or directory": unknown
rancher-ui_1  | 2018-03-27 11:14:38,094 ERROR [89c10978-9408-4389-a449-65b56b87d124:112649731] [service:423] [service.activate] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got error: Couldn't bring up network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
```

**Comment by superseb** [comment]
What RHEL7 exactly and what kernel? (`uname -r`)

Also `docker info` would be helpful here. When did you upgrade to 17.12.1 and from what version?

**Comment by VAdamec** [comment]
Red Hat Enterprise Linux Server release 7.4 (Maipo)
kernel 3.10.0-693.17.1.el7.x86_64

docker info
```
Containers: 22
 Running: 22
 Paused: 0
 Stopped: 0
Images: 498
Server Version: 17.12.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: RedHat Linux Server 7.4
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 31.26GiB
Name: rancher-host-0001
ID: OWAA:XXX:XXX:XXX:XXXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://proxy:3128
HTTPS Proxy: http://proxy:3128
No Proxy: localhost,127.0.0.1,169.254.169.254,example.com
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by superseb** [comment]
- When did you upgrade to 17.12.1 and from what version?
- `all agents disconnects`. What is in the log of the `rancher-agent` container in this case?
- How are you adding them back?

**Comment by VAdamec** [comment]
Prev version was 17.05.0.ce, upgrade was done a day or two before. When server was upgraded I start infrastructure stack upgrade, that leads to rancher-agent upgrade process, but that finished in loop. Rancher upgrade container try to remove rancher-agent, which wasn't running (already removed during process). I try to restart docker service on affected agents and add them back as a new one, but this leads to rancher-entrypoint.sh issue. Also completely new hosts was not able to be added.

**Comment by MadMax411** [comment]
We found a solution: We have to create a new rancher environment. In the new environment exists a new version of vxlan. Create all stacks (copy&paste stack config) in the new environment and it works.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
