### ISSUE TITLE
What's the best way to upgrade Rancher throughout builds ? 

### ISSUE THREAD

**Issue by mikekuzak** [rancher/rancher#12328]
When pulling a new version of the alpha of Rancher 2.0  I'm losing the Rancher config and any Kubernetes cluster. Is there a correct way of upgrading Rancher ?

**Comment by superseb** [comment]
Version 2 is currently in Tech Preview / alpha, we don't test any upgrade scenario in this stage. The state is currently stored in `/var/lib/rancher`, but as said, we don't guarantee running new versions against this state.

Of course this is included/tested when the product matures.
