### ISSUE TITLE
Putting user in member drop-down causes all user and system account info to show up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12338]
**Rancher versions:** 2.0 master 3/28

**Steps to Reproduce:**
1.  Add cluster or Project
2.  Add Member (from Add cluster, edit Cluster, Add project, Edit project or from Add Member pages)
3.  In Name drop-down, type in user

**Results:**  Everyone in your list shows up and System Account information shows up
![image](https://user-images.githubusercontent.com/11514927/38058958-9973d300-3299-11e8-8ea3-bf8940eea6b8.png)

**Comment by loganhz** [comment]
The list is from server side. UI sends the request to `/v3/principals?action=search`. Server returns the search result.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/20
Can no longer reproduce.
