### ISSUE TITLE
UI Issues - Cluster list page and dashboard

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12331]
**Rancher versions:** 2.0 master 3/28

**Results:**

Cluster List page  (Global/Clusters) - 
![image](https://user-images.githubusercontent.com/11514927/38051197-68fced22-3282-11e8-8991-da2123f0bc43.png)

- [x] Remove Pods column 

- [x] Add Column called Version & make it the kubernetes version of the cluster.  Put Version column after Provider.

Cluster Dashboard Page - 
![image](https://user-images.githubusercontent.com/11514927/38051265-a27be8aa-3282-11e8-8823-53f6bf44268e.png)

- [x] Add blue info bar  (should go below title and above graphs - like in the node detail page).  Include - Provider, Version (kubernetes version), Nodes (amount of nodes) info in that order.  
Example of a blue info bar from nodes - 
![image](https://user-images.githubusercontent.com/11514927/38051376-ef644f36-3282-11e8-8539-0d4da30f787f.png)

**Comment by biblesyme** [comment]
@vincent99 I can't find any key to match the `Verions(kubernetes version)` from the `/v3/clusters`. Where I can get it?

**Comment by vincent99** [comment]
There's one somewhere in the rke/also/gkeConfig, but that won't help for imported.  @deniseschannon can someone add a readonly field on cluster that actually reads it from the cluster?

**Comment by vincent99** [comment]
@ibuildthecloud is adding the version info as `cluster`->`version`, you'll want `gitCommit`

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified fixed
