### ISSUE TITLE
Migrate rancher code base to k8s 1.9 vendor 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12335]
Currently rancher uses k8s 1.8 as a vendor dependency. We might wanna switch to 1.9 at some point. Following projects will need an upgrade:

- [ ] rancher/types
- [ ] rancher/norman
- [ ] rancher/rke
- [ ] rancher/rancher

**Comment by loganhz** [comment]
Now we are using k8s 1.12 as the vendor. Close it as it has been addressed.
