### ISSUE TITLE
A question about how to inject host environment into container

### ISSUE THREAD

**Issue by zyf0330** [rancher/rancher#12345]
I have a question.
We know `docker run -e` can inject environment of host into container, so is there any way to use this feature in rancher?
By metadata, container can read labels of host. But label must be set manually. If I use rancher-cli to create host, `--label` still is read from local machine not target host. So is there any convenient way to read host environment without adjusting code in container to support rancher metadata?
Thanks.

**Comment by vincent99** [comment]
No; this is not part of the remote API and is done by the Docker CLI using your shell's environment.. The environment of the Docker daemon (or Rancher agent) would not generally have much of interest to read.

**Comment by zyf0330** [comment]
Thanks for your reply.
Then, is there way to set label convenient according to host environment?

**Comment by vincent99** [comment]
Other than metadata, no.
