### ISSUE TITLE
Workload UI Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12341]
**Rancher versions:**2.0 master 2/28

**Results:**
- [x] Add/Edit and Details pages - Put Labels and Annotations into 1 accordion.  Call it "Labels & Annotations"
![image](https://user-images.githubusercontent.com/11514927/38061722-598b68d2-32a5-11e8-9727-cc7d174ceb89.png)

- [x] Details - Add a Pod list that shows all pods in the workload.  In table include Status, Name, Image, IP Address.  Accordion should be on top of all others and default to open.

- [x] Details - Remove Selector section from blue info box 
![image](https://user-images.githubusercontent.com/11514927/38063077-1d6acff8-32ac-11e8-876b-cc4a0669816f.png)

- [x] Details - Make blue info box 1 box with two lines of info, instead of two separate boxes
![image](https://user-images.githubusercontent.com/11514927/38063099-383796ae-32ac-11e8-9ee8-7c1e9c7bd873.png)

- [x] Details - Change order of blue info box to - Namespace, Image, Type, Scale, Created
![image](https://user-images.githubusercontent.com/11514927/38063124-554f7162-32ac-11e8-80b0-a2bdd5297c6e.png)

- [x] Details - Daemon Set workload should show "1 per node" text instead of scale buttons
![image](https://user-images.githubusercontent.com/11514927/38063163-89fb7e24-32ac-11e8-9d62-6983030fc51c.png)

- [x] Details - Volume information is missing
![image](https://user-images.githubusercontent.com/11514927/38063187-a120c334-32ac-11e8-8f3a-c7e227916cbe.png)

- [x] Details - Workload type is not a human readable string.  Should be using a translation key.
deployment: Deployment
replicaSet; Replica Set
statefulSet: Stateful Set
daemonSet: Daemon Set
replicationController: Replication Controller
job: Job
cronJob: Cron Job
pod: Standalone Pod
![image](https://user-images.githubusercontent.com/11514927/38063202-b522051e-32ac-11e8-8102-7ddf4b047289.png)

- [x] Details - If you have more than 1 environment variable, the info moves out of the table
![image](https://user-images.githubusercontent.com/11514927/38063246-f16b2370-32ac-11e8-99e7-67ecd8666cab.png)

- [x] Details - Remove Kind from Labels
![image](https://user-images.githubusercontent.com/11514927/38063359-8d5d63ba-32ad-11e8-9dc0-56d28c38b8fb.png)

- [x] Details - Change so Annotations is in table like Labels
![image](https://user-images.githubusercontent.com/11514927/38063334-705d455a-32ad-11e8-9643-aa8b66bf68a6.png)

**Comment by biblesyme** [comment]
@vincent99 
About the first modification, after these two combinations:
1. Do we adopt the detail info in the `Labels`?
2. Do the `Configured` hint need to become two different hint like `Labels Configured/Not Configured` and `Annotations Configured/Not Configured`?

**Comment by vincent99** [comment]
@biblesyme 
1. Yes, the detail translation from Labels is fine
2. I don't think any of those hints work right now, so you could probably add a separate task to make them all do something.  For this one just counting up the number of annotations+labels and saying `5 Configured` would work

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
