### ISSUE TITLE
Pipeline auth page logs me out if I'm not admin

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12348]
**Rancher versions:** 2.0 master 3/28

**Steps to Reproduce:**
1.  Create a local standard user
2.  Create a DO cluster and add standard user as cluster owner
3.  Log in as standard user
4.  Try to go to Pipeline page to authenticate

**Results:**  Logs you out of rancher and takes you back to Login page

**Comment by deniseschannon** [comment]
Related: https://github.com/rancher/rancher/issues/12180

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/5
Verified fixed
