### ISSUE TITLE
Not able to set PSP at project level.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12343]
Rancher server version - Build from master

Steps to reproduce the problem:
Create PSP1 which disallows for privilege containers.
Create PSP2 which allows for privilege containers.
Create a cluster with PSP enabled and default set to "PSP1".
Create a project in this cluster by setting its PSP to "PSP2".

PSP is not getting saved for projects

When trying to open the project in detail view we dont see the PSP set for it.

UI call made:
```
{type: "project", name: "mytestp", clusterId: "cluster-hgbtt",…}
clusterId
:
"cluster-hgbtt"
id
:
""
name
:
"mytestp"
podSecurityPolicyTemplateId
:
"allowpriv"
type
:
"project"
```

In api 
```
"name": "mytestp",
"namespaceId": null,
"podSecurityPolicyTemplateId": "",
"state": "active",
```

**Comment by sangeethah** [comment]
Should UI be using setPodSecurityPolicy instead ? When i use this action from apiui , it gets parse error and never completes -- "waiting for response" ..but I see psp being set for the project.

**Comment by deniseschannon** [comment]
@sangeethah This issue will be related to https://github.com/rancher/rancher/issues/12160

Basically, only users with specific privileges to be able to change the PSP of a project will be able to change the PSPT from the default PSP that is set. That role/ability to change the PSP has not been created yet.

**Comment by sangeethah** [comment]
@deniseschannon This issue happens when trying as an admin. This is relating to having to use  setPodSecurityPolicy now which is not being used by UI

**Comment by nathan-jenan-rancher** [comment]
@vincent99 or someone needs to update the UI to invoke the setPodSecurityPolicy method.

There are also permission that need to be updated in the backend, but I think that is a separate issue than just modifying the UI to make the right API calls.

**Comment by loganhz** [comment]
@nathan-jenan-rancher what's the payload for `setPodSecurityPolicy` ?

**Comment by loganhz** [comment]
ah, I found it. `podSecurityPolicyTemplateId`

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
UI is Posting the PSP and it's set in the API after creation.
