### ISSUE TITLE
AD Authentication UI Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12359]
**Rancher versions:** 2.0 master 3/29

**Steps to Reproduce:**
1.  Go to AD authentication page

**Results:**

- [x] Update boxes to new accordion style boxes

- [x] Customize Schema should be closed by default, other two section should be open

- [x] Move Certification section into top box and only show if TLS is checked.  Section should show up right below host name line.

- [x] Add text to bottom of certificate section that say "If needed, enter a CA certificate"

- [x] Example is wrong inside certificate field, should be public certificate not private key.

- [x] Title of section should be CA Certificate

- [x] Authenticate text is not centered in button
![image](https://user-images.githubusercontent.com/11514927/38118111-79a561b8-336d-11e8-84d1-3dec9783c22a.png)

Authenticated Page Issues:
- [ ] User Name and info not showing up in top right corner
![image](https://user-images.githubusercontent.com/11514927/38118148-b7332a24-336d-11e8-8684-acfa6aaba06c.png)

- [x] Edit button is disabled

- [x] Light grey line und Authentication text that shouldn't be there
![image](https://user-images.githubusercontent.com/11514927/38106162-0845992c-3343-11e8-98fe-7315fc41ef31.png)

- [x] Change sections into new style boxes

**Comment by westlywright** [comment]
User Name identity info is due to a back end issue that is referenced.

**Comment by westlywright** [comment]
@tfiduccia I'm a little confused by the last checkbox, are you asking to have AD Info after successful enabled to be in accordion boxes as well?

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
