### ISSUE TITLE
failed with "waiting for server-url setting to be set"

### ISSUE THREAD

**Issue by qitianbiao** [rancher/rancher#12350]
**Rancher versions:** 
rancher/server: 2.0 latest, dockerhub tag:master
rancher/agent: 2.0 latest, dockerhub tag:master

** Problems:**
I add a node with the role of etcd+controlplane+worker into a new cluster. The node changes status to active in GUI, but the cluster is keeping "Installing" with error messeage "waiting for server-url setting to be set", it doesn't go well after a long time. Following is the master log.

** Master logs:**
......
2018/03/29 06:48:41 [INFO] Syncing ProjectNetworkPolicyController Controller Done
2018/03/29 06:48:41 [INFO] Syncing PipelineController Controller Done
2018/03/29 06:48:41 [INFO] Syncing PipelineExecutionController Controller Done
2018/03/29 06:48:41 [INFO] Syncing PipelineExecutionLogController Controller Done
2018/03/29 06:48:41 [INFO] Syncing NamespaceController Controller Done
2018/03/29 06:48:41 [INFO] Syncing PodSecurityPolicyTemplateController Controller Done
2018/03/29 06:48:41 [INFO] Syncing PodSecurityPolicyController Controller Done
2018/03/29 06:48:41 [INFO] Syncing ClusterComposeConfigController Controller Done
2018/03/29 06:48:41 [INFO] Syncing ProjectController Controller Done
2018/03/29 06:48:41 [INFO] Syncing StatefulSetController Controller Done
2018/03/29 06:48:41 [INFO] Syncing IngressController Controller Done
2018/03/29 06:48:41 [INFO] Syncing SecretController Controller Done
2018/03/29 06:48:41 [INFO] Syncing ProjectAlertController Controller Done
2018/03/29 06:48:41 [INFO] Syncing EndpointsController Controller Done
2018/03/29 06:48:41 [INFO] Syncing AppController Controller Done
2018/03/29 06:48:41 [INFO] Syncing ClusterController Controller Done
2018/03/29 06:48:41 [INFO] Syncing ReplicationControllerController Controller Done
2018/03/29 06:48:41 [INFO] Syncing ProjectLoggingController Controller Done
2018/03/29 06:48:41 [INFO] Syncing SecretController Controller Done
2018/03/29 06:48:41 [INFO] Syncing NamespaceController Controller Done
2018/03/29 06:48:41 [INFO] Syncing RoleBindingController Controller Done
E0329 06:48:41.531831       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
2018/03/29 06:48:41 [INFO] Syncing DeploymentController Controller Done
2018/03/29 06:48:41 [INFO] Syncing DaemonSetController Controller Done
2018/03/29 06:48:41 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"cluster-xkvgz:m-8a47b6d4ab32","address":"172.16.92.162","port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-kq7pl"},{"nodeName":"cluster-xkvgz:m-8a47b6d4ab32","address":"172.16.92.162","port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-kq7pl"}]]
2018/03/29 06:48:41 [INFO] Updating node [node162] with public endpoints [[{"nodeName":"cluster-xkvgz:m-8a47b6d4ab32","address":"172.16.92.162","port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-kq7pl"},{"nodeName":"cluster-xkvgz:m-8a47b6d4ab32","address":"172.16.92.162","port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-kq7pl"}]]
2018/03/29 06:48:41 [ERROR] error updating ns kube-public status: Operation cannot be fulfilled on namespaces "kube-public": the object has been modified; please apply your changes to the latest version and try again
2018/03/29 06:48:41 [ERROR] error updating ns default status: Operation cannot be fulfilled on namespaces "default": the object has been modified; please apply your changes to the latest version and try again
2018/03/29 06:48:41 [ERROR] error updating ns kube-system status: Operation cannot be fulfilled on namespaces "kube-system": the object has been modified; please apply your changes to the latest version and try again
2018/03/29 06:48:41 [ERROR] error updating ns ingress-nginx status: Operation cannot be fulfilled on namespaces "ingress-nginx": the object has been modified; please apply your changes to the latest version and try again
2018/03/29 06:48:42 [INFO] Copying secret [default-token-554sc] into namespace [default]
2018/03/29 06:48:42 [INFO] Updating pod [ingress-nginx/nginx-ingress-controller-kq7pl] with public endpoints [[{"nodeName":"cluster-xkvgz:m-8a47b6d4ab32","address":"172.16.92.162","port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-kq7pl"},{"nodeName":"cluster-xkvgz:m-8a47b6d4ab32","address":"172.16.92.162","port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-kq7pl"}]]
E0329 06:48:41.837107       1 generic_controller.go:204] ClusterRoleTemplateBindingController cluster-xkvgz/user-jkvd6-admin [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
2018/03/29 06:48:42 [INFO] Copying secret [default-token-554sc] into namespace [default]
2018/03/29 06:48:42 [INFO] Successfully created default network policy for project: project-rbvvl
E0329 06:48:42.479189       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:42.490484       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:42.501639       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:42.517633       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:42.530744       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:42.554096       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
2018/03/29 06:48:42 [INFO] adding label field.cattle.io/projectId=project-rbvvl to namespace=default
E0329 06:48:42.611787       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:42.623728       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:42.633537       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:43.007656       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:43.022671       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:43.034506       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:50.583084       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:50.591852       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:52.701261       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:52.711470       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:48:56.662544       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:02.709352       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:02.737395       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:11.911048       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:12.859548       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:12.903362       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:14.294105       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:23.046230       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:23.055232       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:23.062709       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:26.911044       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
E0329 06:49:33.121211       1 generic_controller.go:204] ClusterController cluster-xkvgz [cluster-deploy] failed with : waiting for server-url setting to be set
......

**Comment by vincent99** [comment]
As it says, the `server-url` setting has to be set.  The UI prompts for this on first login.

**Comment by qitianbiao** [comment]
hmm, I saw it last version but not in this version, I mean, the UI didn't prompt me to input server-url address after logging and default password changed. Is there any other way to configure the server-url, like editing some configuration file?

**Comment by qitianbiao** [comment]
I use following command with CATTLE_SERVER_URL environment setting to resolve the problem: 
# docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_SERVER_URL=172.16.92.161 rancher/server:master

**Comment by cjellick** [comment]
The image `rancher/server:master` doesnt exist
