### ISSUE TITLE
When PSPT associated with cluster is deleted , PSP continues to be associated with namespace resultng in pod deployment failures.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12367]
Steps to reproduce the problem:

Created PSP - psp1
Created PSP - psp2
Create a cluster with default PSP set to psp1.
Deploy workloads in projects created for these clusters.
Delete psp1.

Even after psp1 is deleted , all namespaces in the cluster continue to the have rolebinding for psp1.
Pod deployments fails with error message - "
Pods "hello2-7bf95886c7-" is forbidden: no providers available to validate pod request, Deployment does not have minimum availability.".

**Comment by deniseschannon** [comment]
@nathan-jenan-rancher I don't think we should be able to successfully delete any PSPs that are associated with any existing cluster/projects. It should error out and say that it's still associated with which cluster/projects.

**Comment by sangeethah** [comment]
Tested with latest build from master:
```rancher/server      master              1e1b97f08975        2 hours ago  ```

Created PSP - psp1
Created PSP - psp2
Create a cluster with default PSP set to psp1.
Deploy workloads in default project of this cluster.

Delete psp1.

Note - In UI , I don't see the delete option. I will log a different issue to track this.
I used the "View in Api" UI and used the "delete" option to delete psp1.

Deletion of psp1 succeeds.

I am still able to reproduce the issue seen in this bug and existing namespace still have psp1 assigned to it.

**Comment by sangeethah** [comment]
I was trying to delete a PSP that was not associated with cluster by mistake.
When I tried to delete a PSP that was associated with cluster , I see the following error as expected
```
{
"actions": { },
"baseType": "error",
"code": "ServerError",
"links": { },
"message": "PSPT is assigned to one or more clusters, remove PSPT from those clusters before deleting",
"status": 500,
"type": "error"
}
```
