### ISSUE TITLE
If I disable then reauthenticate as a different AD user, it adds to the admin list instead of replacing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12362]
**Rancher versions:** 2.0 master 3/29

**Steps to Reproduce:**
1.  Authenticate in AD as testuser1
2.  Disable and then re-authenticate as testuser2

**Results:**  Adds testuser2 and keeps testuser1 as default admin.  Should replace not add users as admin.

**Comments:** here is picture of API showing that it just keeps adding users
![image](https://user-images.githubusercontent.com/11514927/38276287-54516f12-3749-11e8-9704-2bd954dae344.png)

**Comment by deniseschannon** [comment]
@cjellick The question is what should happen when you disable an auth provider? 

If we don't log the user out with that principal and re-log them in with their local user, this issue occurs.

**Comment by deniseschannon** [comment]
Spoke with @cjellick and when you re-enable auth, if there is an existing principal for that external provider being authenticated, it should be replaced with the new principal information.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/19
Verified fixed
