### ISSUE TITLE
[cli] Cli - Provide ability to add members to project and clusters

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#12361]
Need to be able to add members at the project and cluster level

**Comment by dramich** [comment]
Available in v1.0.0-alpha13

**Comment by adingilloRancher** [comment]
Verified Fix
Master 4/19/2018

**Comment by adingilloRancher** [comment]
Master 4/19/18
Verified Fix

Added members/owner to cluster and projects via new CLI commands. 
Verified added user had correct access based on role via UI.
