### ISSUE TITLE
AD auth - User information is not showing up correctly in list

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12374]
**Rancher versions:** 2.0 master 3/29

**Steps to Reproduce:**
1.  Enable AD authentication
2.  Change from Allow any, to Allow members of Cluster... or to Restrict access options
3.  Add your admin user (Mine is called testuser2)

**Results:**  Test User2 with activedirectory_user? under it is showing up.  It should actually show username with First Name Last Name below it.
**2.0 image**
![image](https://user-images.githubusercontent.com/11514927/38118494-eb0cd762-336f-11e8-9cf1-c66107c50744.png)

**1.6 image**
![image](https://user-images.githubusercontent.com/11514927/38118512-f63ec6ae-336f-11e8-8b9d-b7af1f285232.png)

**Comment by westlywright** [comment]
@tfiduccia @vincent99 there was a bug that was causing the type text to show up for AD users, which is what was observed above. I've changed that. The design changed a bit with 2.0 though so I'm not sure were want to fall back to the username/display name showing in the second img. Currently we use displayName and fall back to loginName in the first field and the field below always shows the users type. Do we want to change this design to the 1.6 design or keep it the way it is now (attached below). 

![image](https://user-images.githubusercontent.com/858614/38511178-25353078-3bdc-11e8-9fef-886e01ebf4fc.png)

**Comment by tfiduccia** [comment]
@westlywright - talked to Vincent and he said can we do something like "Test User2 (testuser2)" + "User"

Especially since Name can be anything.  Seems like the actual login name would be more important?

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/30
Verified fixed
