### ISSUE TITLE
AD auth - automatically add admin user to authorized users and Orgs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12373]
**Rancher versions:** 2.0 master 3/29

**Steps to Reproduce:**
1.  Enable AD authentication
2.  Change from Allow any, to Allow members of Cluster... or to Restrict access options

**Results:**  Admin user is not automatically added to list.  We should that.

**Comment by cjellick** [comment]
@wes in @mrajashree's analysis, she has found that the UI is not passing the current user in the allowedIdentities array for AD but it _is_ passing it for GH. My take is that the UI should be consistently sending or not sending it. Can you review this comment and let me know if the UI needs to change. Re-co-assinging you
https://github.com/rancher/rancher/pull/12596#issuecomment-379939700

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/23
Verified fixed
