### ISSUE TITLE
Export support for workload/service/namespace

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12371]
We should add export action on:

- [x] workload
- [x] service
- [x] namespace

the output will be generated yml file that you can feed to kubectl apply

Here is the corresponding action on the k8s side:

`https://192.168.99.100:8443/api/v1/namespaces/default/services?export=true`

You can check what calls kubectl does to fetch the similar info, too. Here is the example of the call:

`kubectl get all --export=true -o yaml --namespace=default -v 9` 

* service.export should return yml representation of the service
* workload.export should return yml representation of the workload
* namespace.export should return yml representation of workload/service resources in that particular namespace

**Comment by gitlawr** [comment]
Actually It has been implemented by https://github.com/rancher/rancher/commit/0d531668e0702e3e01ff3d7c77c0b4b45214b0f3
For example querying
```
https://localhost:8443/v3/project/local:project-mjzw6/dnsRecords/default:kubernetes/yaml?export=true
```
 with `Accept: application/yaml`
you can get the yaml representation of the service

The exception above is the `namespace` resource, it is in `cluster.cattle.io` group(together with PV and storageClass) so it does not benefit from the `yaml` Formatter( it filters resources in `project.cattle.io` group and in user clusters)
@ibuildthecloud Is it the supposed way that we don't provide yaml for the `namespace` resource?

**Comment by alena1108** [comment]
@gitlawr we still have to do the namespace, but not in a `native` k8s way, where only the namespace object itself is being exported (that was probably the reason why export for it was disabled). We should instead combine all the namespaced objects.

**Comment by orangedeng** [comment]
I test it in workload side and it does not work as excepted.

**Comment by orangedeng** [comment]
Export yaml link has been set in api so UI needs to have this button/link too. I think we can show the yaml and have a copy button to `copy to clipboard`. @deniseschannon @vincent99

**Comment by orangedeng** [comment]
I tested it with 4/24 master build and it is ok.

**Comment by bmdepesa** [comment]
rancher/rancher:master 5/15

Working okay.
