### ISSUE TITLE
AD auth - groups and users not being added in title text when I save

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12378]
**Rancher versions:** 2.0 master 3/29

**Steps to Reproduce:**
1.  Authenticate using AD
2.  Switch to Allow members of Clusters... or Restrict access option
2.  Add  a user and a group

**Results:**  The text at the top still says no groups and no users.  It should say 1 group and 1 user.
![image](https://user-images.githubusercontent.com/11514927/38119064-dee3430a-3373-11e8-878e-925cca6aa1a4.png)
![image](https://user-images.githubusercontent.com/11514927/38119057-d7284674-3373-11e8-9927-c1c4f6b13563.png)

**Comment by westlywright** [comment]
@tfiduccia you're totally right, sorry about that. Will assign back when merged.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/23
Verified fixed
