### ISSUE TITLE
When there are multiple "not equal to" rules specified for any field(host label/container name/container label,service name), only one of them is honored. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1238]
Server version - V0.23.0-rc5

Steps to reproduce the problem:
Have host1 with label say - name1=value1
Have host2 with label say - name1=value2
Have host3 with no label

Create a service with 2 scheduling rule set as follows:

host must not have label name1=value1
host must not have label name1=value2

When the service is started , I see containers being deployed in host1 which has label "name1=value1".

Seem like only 1rule was even accepted by the server . I see only this label being programed for the service:

Affinity	io.rancher.scheduler.affinity:host_label_ne	test1=value2

**Comment by sangeethah** [comment]
Scheduling rules entered:
![screen shot 2015-06-15 at 2 29 51 pm](https://cloud.githubusercontent.com/assets/4266958/8171336/f97a6d36-136b-11e5-9eeb-3e0d719e9051.png)

Scheduling rules saved:

![screen shot 2015-06-15 at 2 34 14 pm](https://cloud.githubusercontent.com/assets/4266958/8171339/fea039a8-136b-11e5-9d84-b609baa9c67c.png)

**Comment by vincent99** [comment]
It has nothing to do with "not equal" or host labels specifically.  Any two rules that map to the same key overwrite each other, they need to be combined into a comma-separated list.

**Comment by tfiduccia** [comment]
it's comma separated, but still putting container on host that it should not:
![image](https://cloud.githubusercontent.com/assets/11514927/8348243/e8b005ea-1ac5-11e5-9e1d-390144498c4b.png)
![image](https://cloud.githubusercontent.com/assets/11514927/8348245/f65f8742-1ac5-11e5-8a4f-5a3e0245f6d3.png)

**Comment by prachidamle** [comment]
I could not reproduce this with 3 hosts - 
host1 label name = test1
host2 label name=test2
host3 no labels

Started containers with host_label_ne name=test1,name=test2
They all started on host3.

**Comment by deniseschannon** [comment]
Verified with v0.63.0-rc1 that this is no longer an issue.
