### ISSUE TITLE
Add functionality so that Rancher knows that a cluster is already imported into Rancher when attempting to re-import

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12387]
**Rancher versions: 2.0 build from master

steps to reproduce the problem:
Create a imported cluster using an existing gke cluster.
Create another imported cluster using the same existing gke cluster.

I see the following logs repeatedly in logs:

```
2018/03/30 00:44:00 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w3d6] with public endpoints [[{"nodeName":"cluster-nscq2:machine-h9glf","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w5qr] with public endpoints [[{"nodeName":"cluster-wm7bt:machine-m8pbk","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-n66r] with public endpoints [[{"nodeName":"cluster-nscq2:machine-5jsh6","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w3d6] with public endpoints [[{"nodeName":"cluster-wm7bt:machine-zdkgl","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w5qr] with public endpoints [[{"nodeName":"cluster-nscq2:machine-5bc22","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-n66r] with public endpoints [[{"nodeName":"cluster-wm7bt:machine-98sn7","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w3d6] with public endpoints [[{"nodeName":"cluster-nscq2:machine-h9glf","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w5qr] with public endpoints [[{"nodeName":"cluster-wm7bt:machine-m8pbk","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-n66r] with public endpoints [[{"nodeName":"cluster-wm7bt:machine-98sn7","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w3d6] with public endpoints [[{"nodeName":"cluster-wm7bt:machine-zdkgl","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w5qr] with public endpoints [[{"nodeName":"cluster-nscq2:machine-5bc22","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-n66r] with public endpoints [[{"nodeName":"cluster-nscq2:machine-5jsh6","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w3d6] with public endpoints [[{"nodeName":"cluster-nscq2:machine-h9glf","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
2018/03/30 00:44:01 [INFO] Updating node [gke-sangee-cluster-1-default-pool-fb113a80-w5qr] with public endpoints [[{"nodeName":"cluster-wm7bt:machine-m8pbk","port":32493,"protocol":"TCP","serviceName":"kube-system:default-http-backend"}]]
```

Even after deleting one of the  imported clusters , I continue to see these logs.

**Comment by alena1108** [comment]
@sangeethah we don't support importing the same cluster twice. You can open a doc issue so we can explicitly state it for the user.

**Comment by sangeethah** [comment]
@deniseschannon I have made this issue as a doc issue to get this limitation documented

**Comment by deniseschannon** [comment]
@alena1108 Do we just need to clean up the clusters in order to be able to re-import again?

**Comment by alena1108** [comment]
@deniseschannon yes

**Comment by deniseschannon** [comment]
From @moelsayed in #12126, After a discussion with Alena, I will be removing the following as clean up:
```
cleanup annotations that:
* start with `field.cattle.io`
* start with `lifecycle.cattle.io`
* start with `cattle.io`

cleanup finalizers:
* starting with controller.cattle.io

cleanup labels
* starting with field.cattle.io

so in other words, annotations/labels/finalizers having cattle.io in the name

Remove cattle-system namespace
```
I will test this and see if it will work/cause problems.

**Comment by moelsayed** [comment]
I tested the following scenario several times:
- Create an rke cluster.
- Create several namespaces and workloads
- import the cluster in rancher 2.0.0. After a successful import, the namespaces are shown without a project:
![screenshot from 2018-05-12 03 54 24](https://user-images.githubusercontent.com/4588065/39952621-2139d900-559b-11e8-8166-09d37599675d.png)

- Next, I created several projects and moved the namespaces to them. I also created a new namespace on rancher with it's own namespace and work load:

![screenshot from 2018-05-12 03 59 56](https://user-images.githubusercontent.com/4588065/39952629-65fd3442-559b-11e8-959e-fc1c14b60900.png)

- I removed the cluster from rancher and re-imported it again.
- Re-import was successful, all workloads were worked as expected, but I noticed the following issues:
![screenshot from 2018-05-12 04 07 09](https://user-images.githubusercontent.com/4588065/39952641-95d794a0-559b-11e8-8b65-4668f1ac6638.png)
   - Namespaces are imported without a project, but they still retain the same "groups" as they were before cluster was removed.
   - Default namespace is no longer shown under the default Project
   - The Default Project in the re-imported cluster doesn't have a Default namespace 
- After re-import, I was able to create new projects, move namespaces to them, access workloads and create new workloads successfully. 

I think this is an accepted behavior except for the missing default namespace under the default project after re-import.

**Comment by deniseschannon** [comment]
After speaking with @ibuildthecloud, we should prevent users from being able to reimport a cluster that is already in Rancher. 

Rancher should maintain some ID on the cluster so that if the cluster has been attempted to be re-imported again, Rancher would know now to add it in.
