### ISSUE TITLE
404 page for pending PVC

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12389]
**Rancher versions:**
rancher/server 03/30

**Steps to Reproduce:**
1. Go to the "Catalog App"  and launch the "artifactory" app.
2. This app contains 2 volume using PVC, but there is not any PV or Storage Class created, so the status is "pending".
3. Click the "Claim Name"
![image](https://user-images.githubusercontent.com/1213386/38131883-56593a58-343b-11e8-8b36-9111147eea82.png)

4. It redirects to the 404 error pages.
![image](https://user-images.githubusercontent.com/1213386/38131891-623e2d60-343b-11e8-8ae0-cabfc0e56396.png)

**Comment by tfiduccia** [comment]
@zionwu - I can't reproduce this as the artifactory catalog doesn't create volumes anymore?  Can you see if you can reproduce?

**Comment by zionwu** [comment]
@tfiduccia It is fixed by Logan now.  
Verified fix on master 04/11.

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/38654194-a680bdbc-3e40-11e8-948c-217e36e5675f.png)
