### ISSUE TITLE
add 3 nodes with RKE，and  it only shows one node in the Nodes interface

### ISSUE THREAD

**Issue by lucas1993ch** [rancher/rancher#12386]
*Describe your issue here*

I create k8s cluster with [Custom] ,which meas RKE？
and then,I want to add three nodes ,the first node as etcd ,controlplane,and the rest as worker
But howerer I try to execute the command ：

docker run -d --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock --net=host rancher/agent:v2.0.0-alpha24 --server https://my-rancher-server-ip --token 8nlvspbnm6dzh5zcpn2jl4rd5cxblb2lhhfrj8xchmwlknzxnb6jt6 --ca-checksum 36e921659cb053ead57a85bf411f72658fa93ee93ba831444d2bc9550b79b2c4 --worker

I can't add worker node. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha24` UI: `v2.0.28` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
Can you try this using the latest release (`v2.0.0-beta1`) and report back if it doesn't? Thanks
