### ISSUE TITLE
UI - Create project errors with "There must be at least one member with the Owner role."

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12393]
Rancher server version 
Steps to reproduce the problem:
Create a cluster.
Create a project.

<img width="943" alt="screen shot 2018-03-30 at 10 57 44 am" src="https://user-images.githubusercontent.com/4266958/38147960-50a4fb4c-3409-11e8-9837-0bc1d972644e.png">

Project gets created successfully.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
