### ISSUE TITLE
Node related network policy does not get programmed and Ingress is not able to reach cross host targets. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12392]
Rancher server version - Build from master

Steps to reproduce the problem:
Create a cluster with 1 node having all roles and 2 node with "worker" roles.
Create Ingress pointing to workload of scale 3.

Ingress is able to reach only pods that are in the same host. 

Notice that only 1 network policy gets created for default namespace .
There is no node related network policies created.

> kubectl get netpol
NAME         POD-SELECTOR   AGE
np-default   <none>         9m
>

Following errors seen in logs:
```
2018/03/30 17:13:57 [ERROR] netpolMgr: program: error updating network policy err=Put https://104.131.100.82:6443/apis/networking.k8s.io/v1/namespaces/ingress-nginx/networkpolicies/hp-nginx-ingress-controller-mm2nn: Failed to dial ssh using address [104.131.100.82:22]: ssh: handshake failed: read tcp 172.17.0.2:42316->104.131.100.82:22: read: connection reset by peer
```

**Comment by leodotcloud** [comment]
@sangeethah I couldn't see this issue on my setup and also I think you also didn't encounter this again. Please check to see if you can hit it again.

**Comment by sangeethah** [comment]
Have not seen this issue when testing with latest builds from master for sometime now.
