### ISSUE TITLE
Logged In AD Principal does not contain `me` parameter

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#12396]
**Rancher versions:**
rancher/server: Master @8am 03-30-18

**Steps to Reproduce:**
1. Turn on AD auth
2. Login as a known AD User

**Results:**
The principal that belongs to this user does not contain a `me` parameter, which the UI uses for identity info. Locally auth'd users, when logged in, do show the correct me param. 

ref: rancher/rancher#12359

**Comment by westlywright** [comment]
@cjellick @deniseschannon i started with a fresh rancher install and enabled ad auth. I see the `me` property now but its always coming back false for all principal in the collection.

**Comment by deniseschannon** [comment]
Verified this is working with 4/3 build at 12pm.
