### ISSUE TITLE
Not able to provision cluster with version v1.10

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12398]
Rancher server version - Build from master

Steps to reproduce the problem:

Create a DO cluster with 3 nodes:
```
1 node - Control
1 node - Etcd
1 node - Worker
```

Cluster fails to provision with following errors:

```
  | [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [104.131.55.75]: Get https://localhost:6443/healthz: Failed to dial to localhost:6443: ssh: rejected: connect failed (Connection refused)
```

**Comment by gaui** [comment]
I had the same problem with 1.9 and 1.10, server master Docker image 3e056e3fe86f

**Comment by sangeethah** [comment]
Tested with latest build from master - 5a55651e2c08

Able to provision cluster successfully using k8s v1.10.
