### ISSUE TITLE
Default networkpolicy not getting created for namespaces preventing connectivity between containers with in the same namespace. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12403]
Rancher versions: Build from master
**Steps to Reproduce:**
Create a cluster with 3 nodes ( 1 node all roles , 2 nodes - worker)
Create namespaces in Default project.

Sometime we see the network policies get created as expected.
But most of the time , default networkpolicy fails to get created.

```
$ ./kubectl get netpol -n testhello4
NAME       POD-SELECTOR   AGE
hn-nodes   <none>         2s
```

In such cases , pod containers are not able to talk to any other container.

**Comment by sangeethah** [comment]
Tested with latest build from master.

Default networkpolicy gets created everytime namespaces get created.
```
$ ./kubectl get netpol -n test7
NAME         POD-SELECTOR   AGE
hn-nodes     <none>         14s
np-default   <none>         14s
```

**Comment by alwinmarkcf** [comment]
Ist because I mess around with  networkplolicies. Those hn-nodes and np-default Policies are created by Rancher or are those general Kubernetes Policies?
