### ISSUE TITLE
Can not provide the kubeconfig file when creating an import cluster

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12408]
**Rancher versions:**
rancher/server 04/02

**Steps to Reproduce:**
1. Click "Add Cluster"
2. Choose "Import" and click "Create"
3. It jumps to the following page and I can't provide the kubeconfig file for the import cluster.
![image](https://user-images.githubusercontent.com/1213386/38185536-29422e4c-3681-11e8-9616-e2ec7d93c44f.png)

**Comment by vincent99** [comment]
Importing a config was intentionally removed.  Common sources of configs like minikube and gke are not usable on their own because they refer to external files or executables.

**Comment by zionwu** [comment]
Do we still support import an existing cluster?  How can I import an existing cluster?

**Comment by deniseschannon** [comment]
@zionwu it looks like you're having some weird issue with import UI screen. I am able to see the kubectl apply commands

<img width="1305" alt="screen shot 2018-04-02 at 2 15 01 pm" src="https://user-images.githubusercontent.com/11410997/38216641-458c0164-3680-11e8-807e-ce9133c669d2.png">

**Comment by zionwu** [comment]
Yes, it is working on rancher/server:master 04/03
