### ISSUE TITLE
Can not create hostPath Persistent Volume

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12410]
**Rancher versions:**
rancher/server 04/02 

**Steps to Reproduce:**
1. Create a host path PV as follows:
![image](https://user-images.githubusercontent.com/1213386/38192095-ee97fd7c-369d-11e8-9186-ea455c9aaf89.png)

2. Error message "Validation failed in API: PersistentVolume "test" is invalid: spec.hostPath.type: Unsupported value: "hostPathVolumeSource": supported values: , BlockDevice, CharDevice, Directory, DirectoryOrCreate, File, FileOrCreate, Socket"

3. I checked the schema, the hostPathVolumeSource have a field `type`, UI is passing "hostPathVolumeSource" for it, which is wrong.

![image](https://user-images.githubusercontent.com/1213386/38192161-386869d2-369e-11e8-95f8-499be827bfe2.png)

**Comment by vincent99** [comment]
This is the API, it's supposed to map their `type` to `kind`and should accept null/empty string.

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/38464125-dcf6730e-3b3a-11e8-9f52-508134a0d2fa.png)

The schemas already map type to kind. However, the creation API does not do the mapping and passing type to k8s api. It is a bug of norman Framework. I will check if I can fix it in Norman.

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/38466558-86c1f828-3b5d-11e8-9e80-8585d7f2bc3f.png)

The schemas of hostPathVolumeSource already maps `type` to `kind`. And I add `""` to the options and as the default value. However,  UI is still not passing the kind field to backend.  And backend is treating `type: "hostPathVolumeSource"` as kind, which may be a bug in norman framework.

![image](https://user-images.githubusercontent.com/1213386/38466581-f4ad0cf6-3b5d-11e8-98ff-fa986c10f8bd.png)

**Comment by zionwu** [comment]
verified fix on master 04/12.

**Comment by huanga** [comment]
Just deployed a `rancher/server:v2.0.0beta3` local cluster with Kubernetes `v1.8.10-rancher1-1` on bare metal, and I am still seeing this issue.

https://youtu.be/KQIQatJcG5g

```[rancher@tianyi ~]$ docker ps | grep rancher/server
5bf45bc8b016        rancher/server:v2.0.0-beta3                                                                                               "rancher --http-li..."   14 minutes ago      Up 14 minutes       0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   competent_babbage```

Is this fix supposed to be in Beta3 or will it be pushed in a later release?

**Comment by akurach** [comment]
same thing on 
```
root@photon-McvsypWQ7 [ ~ ]# docker ps | grep rancher/server
27c4d93bf4a6        rancher/server:preview
```

**Comment by mloc** [comment]
Confirmed happening on beta3, deployed yesterday.

**Comment by huanga** [comment]
Petition for reopening this ticket please.

**Comment by vincent99** [comment]
This did not make it into beta3, but is in master.

**Comment by huanga** [comment]
Confirmed to work in Master, pulled as of 10 minutes prior to this message.
