### ISSUE TITLE
Worker/etcd nodes stuck in registering state in a custom cluster 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12415]
**Rancher versions:**
rancher/server:Master

**Steps to Reproduce:**
1. Create a custom cluster with 1 etcd node, 1 control node and 3 workers
etcd and cluster node come up fine. Worker nodes are stuck in registering state

Server logs:
```
2018/04/02 17:26:02 [INFO] cluster [cluster-6z6xg] provisioning: [addons] Setting up user addons
2018/04/02 17:26:02 [INFO] cluster [cluster-6z6xg] provisioning: [addons] no user addons defined
2018/04/02 17:26:02 [INFO] cluster [cluster-6z6xg] provisioning: Finished building Kubernetes cluster successfully
2018/04/02 17:26:02 [INFO] Provisioned cluster [cluster-6z6xg]
2018/04/02 17:26:05 [INFO] Handling backend connection request.
2018/04/02 17:26:15 [INFO] Handling backend connection request.
E0402 17:26:24.958664       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v1.NamespaceStatus
E0402 17:26:24.967222       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v1beta2.DaemonSetStatus
E0402 17:26:24.974648       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v1beta2.StatefulSetStatus
2018/04/02 17:26:25 [ERROR] Failed to update cluster [cluster-6z6xg]: Operation cannot be fulfilled on clusters.management.cattle.io "cluster-6z6xg": the object has been modified; please apply your changes to the latest version and try again
2018/04/02 17:26:25 [INFO] Handling backend connection request.
2018/04/02 17:26:25 [INFO] Handling backend connection request.
2018/04/02 17:26:26 [INFO] Handling backend connection request.
2018/04/02 17:26:36 [INFO] Handling backend connection request.
2018/04/02 17:26:46 [INFO] Handling backend connection request.
2018/04/02 17:26:56 [INFO] Handling backend connection request.
2018/04/02 17:27:06 [INFO] Handling backend connection request.
2018/04/02 17:27:16 [INFO] Handling backend connection request.
2018/04/02 17:27:26 [INFO] Handling backend connection request.
2018/04/02 17:27:36 [INFO] Handling backend connection request.
2018/04/02 17:27:46 [INFO] Handling backend connection request.

```

**Comment by sangeethah** [comment]
I see similar issue issue with etcd node stuck in registering state as well in a 8 node cluster with following setup:

2 control nodes
3 etcd nodes
3 worker nodes

only 1 etc node got to "Active" state and other 2 are stuck in "registering" state "waiting to register with Kubernetes" .Worker nodes are also stuck in the same state.

**Comment by soumyalj** [comment]
Tested with master from April 2nd build. 
Created a custom cluster with 1 etcd node, 1 control node and 3 workers
All worker nodes came up fine and cluster was active.
Workload and ingress creation was successful

**Comment by tlitovsk** [comment]
sorry bu its still there
2018/07/07 20:36:15 [INFO] cluster [c-6q7q9] provisioning: [reconcile] host [178.128.62.159] is active master on the cluster
2018/07/07 20:36:15 [INFO] cluster [c-6q7q9] provisioning: [reconcile] Reconciled cluster state successfully
2018/07/07 20:36:15 [INFO] cluster [c-6q7q9] provisioning: [certificates] Deploying kubernetes certificates to Cluster nodes
E0707 20:36:16.109606       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v1beta1.CronJobStatus
E0707 20:36:16.160708       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v1.ReplicationControllerStatus
E0707 20:36:16.162401       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v1beta2.StatefulSetStatus
