### ISSUE TITLE
Cluster shows active even thou I deleted it on provider side

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12419]
**Rancher versions:** 2.0 master 4/2

**Steps to Reproduce:**
1.  Create a Cluster (I used GKE)
2.  Delete the cluster on the provider side (I went to gke and deleted from there)

**Results:**  Cluster still shows active.  Should do check to make sure we can still communicate with cluster and if we can't, change state.
![image](https://user-images.githubusercontent.com/11514927/38212779-da6eceae-3673-11e8-9211-c8ea70d33e24.png)

**Comment by orangedeng** [comment]
Can not reproduce the issue. 
I am using rancher/server:master 4/9

**Comment by deniseschannon** [comment]
@tfiduccia can you try again?

**Comment by tfiduccia** [comment]
So the Cluster shows unavailable, but the nodes (which have been deleted), still show active now.  Shouldn't the nodes also show unavailable?

![image](https://user-images.githubusercontent.com/11514927/39149188-30f48a72-46f3-11e8-816e-4d2c411f35b1.png)

**Comment by tfiduccia** [comment]
closing in favor of #12176
