### ISSUE TITLE
Daily MySQL Bin logs are bigger than expected and growing

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#12412]
Rancher 1.6.5 +

Binary logs are typically ~15% of the DB size.  What we are seeing for our daily bin logs is 2-3X the DB size.

It seems like Rancher writes a lot of event logs.  Also, that it is 4-5 tables that are very chatty.  These tables grow quite a bit but get pruned at the EOD.  But all the chattiness gets logged anyways.

In MySQL/InnoDB, there is no way to selectively ignore certain tables within a database.  It can only be done at a DB level.

Possible to move these chatty tables to their own database, so that this bloat problem can be decoupled and the *chatty_tables_db* can be ignored in backups.  I think this would be beneficial for all deployments.  This also seems to be the standard way of addressing this problem in the MySQL community.

~~Naturally,~~ would this will imply code changes, to have a coherent view across these two DBs?

> Per conversation with a DBA, it would not require a code change if intermediate views were used.

What can be done?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
