### ISSUE TITLE
AD Auth - Local users created after authenticating can't be used in Add members

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12418]
**Rancher versions:** 2.0 master 4/2

**Steps to Reproduce:**
1.  Before authenticating create two local users (localuser1 & localuser2)
2.  Create a cluster and add both local users
3.  Authenticate using AD
4.  Add another local user (localuser3)
5.  Try to add the new local user (localuser3) to the cluster or to a project

**Results:**  New Local user (localuser3) is not available.

**Comment:**  Found that if I refresh my browser, the user will show up.

**Comment by deniseschannon** [comment]
Root cause: #11868

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/5
Verified fixed
