### ISSUE TITLE
If you set AD to Allow Members of.... or Restrict and add user, user cannot log in first time

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12426]
**Rancher versions:** 2.0 master 2/4

**Steps to Reproduce:**
1.  Create rancher server
2. Authenticate using AD
3. Select Allow members of Clusters, Projects... option and Add a user
4.  Try to log in as that user
5.  Try again

**Results:**  Login fails first time.  After that first try, user can always log in.  Tried with multiple accounts and always got the same result.
![image](https://user-images.githubusercontent.com/11514927/38265882-fe024702-372b-11e8-868d-11935eb4d85b.png)

Logs:
```
2018/04/03 17:48:48 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding globalrolebinding-4d74p
2018/04/03 17:48:48 [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: Operation cannot be fulfilled on users.management.cattle.io "user-4nb8t": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by deniseschannon** [comment]
Unable to reproduce with master 4/3

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/5
Verified fixed
