### ISSUE TITLE
Add cluster capabilities to reflect cloud provider specific features

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12422]
We should add Capabilities on cluster to reflect if features like:
* LoadBalancer service
* Ingress controller 
  - ingress provider
  - whether custom default backend is supported
* Does provider support scaling node pools (Custom/Imported does not)

are supported on a particular cluster. Some features are driven by the cloud provider

**Comment by vincent99** [comment]
clusterip port range...

**Comment by sangeethah** [comment]
Tested with master build from Nov 26:
For a DO cluster we have the following capabilities set:

```
"capabilities": {
"ingressCapabilities": [
{
"customDefaultBackend": false,
"ingressProvider": "Nginx",
"type": "/v3/schemas/ingressCapabilities"
}
],
"loadBalancerCapabilities": {
"enabled": false,
"healthCheckSupported": false,
"type": "/v3/schemas/loadBalancerCapabilities"
},
"nodePoolScalingSupported": true,
"nodePortRange": "30000-32767",
"type": "/v3/schemas/capabilities"
},
```

**Comment by sangeethah** [comment]
@mrajashree For imported clusters , we have loadBalancerCapabilities set to "false". This is something we do not know for sure. Should we not set this to "false" for imported clusters ?


Related issue -  https://github.com/rancher/rancher/issues/16785

Related UI issues:
https://github.com/rancher/rancher/issues/16783 
https://github.com/rancher/rancher/issues/16784

**Comment by alena1108** [comment]
@mrajashree we should distinguish between something we don't know vs we know is disabled for sure.

**Comment by alena1108** [comment]
@galal-hussein we should change the value type to *bool here https://github.com/rancher/types/blob/8eb7ef24c5221eae478e657060b2a1b061389aad/apis/management.cattle.io/v3/cluster_types.go#L224

so the UI would hide the LB tab only when the value is set to false explicitly.

**Comment by sangeethah** [comment]
Tested with latest build from master - Feb 7:

For imported clusters ( tested on "local" cluster on a HA setup):

Imported cluster's capabilities does not have `enabled` field . 
```
"loadBalancerCapabilities": {
"healthCheckSupported": false,
"type": "/v3/schemas/loadBalancerCapabilities"
},
```

@galal-hussein Is this how you expect to see in the api ?

Even with this setting , we see the "Load Balancing" option not presented as an option in "port mapping" drop down when user creates a workload.

Once you confirm that this expected behavior in API , i will log  a UI issue to make the necessary changes.

**Comment by galal-hussein** [comment]
@sangeethah this should be the expected behavior:

- Imported clusters: `enabled` field is not set, therefor its nil and will not be seen
- Azure/AWS clusters: `enabled` field is set to true
- Other clusters: `enabled` field is set to false

**Comment by sangeethah** [comment]
Logged UI issue for making the LB option to be shown for Imported clusters - https://github.com/rancher/rancher/issues/17941
