### ISSUE TITLE
Changing site access from allow any valid users to Allow members of cluster/projects/authorized users/orgs forces me to add an authorized user

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12427]
Master 4/2

Enable AD with "Allow any valid users"
Go to Settings and decide  to switch to "Allow members of clusters/projects, plus auth users/orgs"
Try to Save

<img width="1218" alt="screen shot 2018-04-02 at 3 59 04 pm" src="https://user-images.githubusercontent.com/11410997/38220397-cb8dd388-368e-11e8-91fe-9ee239352b5a.png">

Result: It's forcing me to add at least one authorized entry. 

Expected Result: This shouldn't be required as i only want anyone who's a cluster/project member

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/6
Verified fixed
