### ISSUE TITLE
Cluster stuck in "Removing" state - "waiting on mgmt-cluster-rbac-remove"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12424]
Rancher server - Build from master

Steps to reproduce the problem:
Create a cluster with custom host having multiple nodes .All nodes in this cluster did not get to "active" sate.

I might have deleted few of the custom nodes in this cluster (outside of rancher server).
Tried to delete this cluster.

It gets stuck in "Removing" state forever.

<img width="1248" alt="screen shot 2018-04-02 at 2 41 05 pm" src="https://user-images.githubusercontent.com/4266958/38217949-fc522690-3684-11e8-8d59-59cdde7807db.png">

**Comment by deniseschannon** [comment]
@sangeethah with all the changes in the last bit, have you seen this?  if not, can we close?

**Comment by sangeethah** [comment]
This issue is not seen when testing with master builds.
