### ISSUE TITLE
For AD, if I click on Use a Local user, I get a double login.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12428]
**Rancher versions:** 2.0 master 4/2

**Steps to Reproduce:**
1.  Authenticate in AD
2.  Log out
3.  Click on Active Directory
4.  Click on Use a Local User

**Results:**  Two of everything shows up
![image](https://user-images.githubusercontent.com/11514927/38220469-2f1eccc2-368f-11e8-8f04-fc76658c4c54.png)

**Comment by vincent99** [comment]
The buttons have different text now

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
