### ISSUE TITLE
AD Auth - AD setup fails when password(s) contains special characters

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#12421]
**Rancher versions:**
rancher/server: v2, alpha24

**Docker version: (`docker version`,`docker info` preferred)**
17.03.02-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS
4.13.0-32-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vmware

**Steps to Reproduce:**
Configure AD Auth, ensure svc acct password contains special chars, and ensure domain user acct has special chars.  In this case, it is a combo of `@`, `$`, and `#`

**Results:**
Error in browser
![screen shot 2018-04-02 at 3 25 35 pm](https://user-images.githubusercontent.com/11069351/38214411-264ff65c-368a-11e8-9c09-1a69a990b6b9.png)

Error in server log - 

```2018/04/02 20:25:33 [ERROR] API error response 401 for POST /v3/activeDirectoryConfigs/activedirectory?action=testAndApply. Cause: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580```

I know the error says "Invalid Credentials", but that is erroneous, we went through this earlier in v1.6.x - 

#9815

**Comment by bolak2** [comment]
Trying to get notifications

**Comment by bolak2** [comment]
Trying to get notifications

**Comment by deniseschannon** [comment]
Can we just confirm that special characters work in username or passwords (either service account or actual users)?

**Comment by pulberg** [comment]
@deniseschannon -

Confirmation of svc acct/password - 

```
ldapsearch \
>     -x -H ldap://ldaplb.rjf.com \
>     -D "svcacct" \
>     -W \
>     -b "dc=rjf,dc=com" "cn=Phillip Ulberg"\
>     -s sub "(cn=*)" cn mail sn
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <dc=rjf,dc=com> with scope subtree
# filter: cn=Phillip Ulberg
# requesting: -s sub (cn=*) cn mail sn
#

# Phillip Ulberg, Users, rjf.com
dn: CN=Phillip Ulberg,CN=Users,DC=rjf,DC=com
cn: Phillip Ulberg
sn: Ulberg
mail: Phillip.Ulberg@RaymondJames.com

# search reference
ref: ldap://DomainDnsZones.rjf.com/DC=DomainDnsZones,DC=rjf,DC=com

# search result
search: 2
result: 0 Success
```

Confirmation of AD username/password - 

```
ldapwhoami -vvv -h ldaplb.rjf.com -p 389 -D "Phillip Ulberg" -x -W
ldap_initialize( ldap://ldaplb.rjf.com:389 )
Enter LDAP Password:
u:RJF\pulberg
Result: Success (0)
```

**Comment by pulberg** [comment]
I think we found the issue, for the field "Default Domain" we were entering "rjf.com" instead of just "rjf"

AD Auth seems to be working now.  Sorry for the goose chase, maybe some form field validation or better error massages would help in this situation.

**Comment by pulberg** [comment]
@deniseschannon We have verified that the AD setup/config is **working**, closing this.
