### ISSUE TITLE
RKE doesn't if I changed docker data dir

### ISSUE THREAD

**Issue by xlogin** [rancher/rancher#12437]
*Describe your issue here*

I have updated the docker setting with `-data-root=/data/docker`

kubelet (Failed to allocate instance [container:1i699]: Bad instance [container:1i699] in state [error]: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/data/docker", bind mount source: "/data/docker", propagation: "rprivate")
--

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`stack.index`|

**Comment by tao12345666333** [comment]
Same issue.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
