### ISSUE TITLE
Delay in default namespace population during workload deployment 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12432]
**Rancher versions:**
rancher/server: Master

**Steps to Reproduce:**
1. Create a cluster (single node/multinode)
2. Once the cluster is active, deploy a workload 
While deploying the workload, default namespace is not populated in the namespace dropdown for a minute. It gets populated after a minute or so with refresh.

```
> kubectl get namespace
NAME            STATUS    AGE
cattle-system   Active    7m
default         Active    9m
ingress-nginx   Active    7m
kube-public     Active    9m
kube-system     Active    9m
> kubectl describe namespace default
Name:         default
Labels:       field.cattle.io/projectId=project-dtftx
Annotations:  cattle.io/status={"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2018-04-02T23:54:57Z"}]}
              field.cattle.io/projectId=cluster-ltkv4:project-dtftx
              lifecycle.cattle.io/create.namespace-auth=true

```
The annotation corresponds to the right cluster/project

**Comment by orangedeng** [comment]
After I create a new cluster, I reproduce this problem and I get following error from chrome console.
<img width="1002" alt="2018-04-04 3 23 16" src="https://user-images.githubusercontent.com/15376837/38294243-c89cb574-381c-11e8-996b-99bebcaed946.png">

I see default namespace has annotation already. So, is it possible that this error from UI cause the problem? @vincent99

**Comment by orangedeng** [comment]
@soumyalj And I can not reproduce this problem every time. I test it with rancher/server:master in 4/4 and DO cluster.

**Comment by vincent99** [comment]
When you're using a cert that is not recognized by the browser it eventually randomly decides it's not going to open any more connections until you say yes it's ok.

So you're not connected to the websocket for change events, and therefore don't hear that the namespace was created.

**Comment by orangedeng** [comment]
@vincent99 @alena1108 I run out of move for this. Could you have a look for it?
I think it is a ui issue because namespace and project data from backend is as expected.

**Comment by loganhz** [comment]
UI doesn't create the websocket connection to the new added cluster.
UI should connect to `/v3/clusters/cluster-${cluster_id}/subscribe`  once the cluster is `active`

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
