### ISSUE TITLE
kubectl client version for 1.8.10 cluster is 1.8.9

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12443]
Rancher server version - Build from master

Steps to reproduce the problem:
Create a cluster with Custom hosts using 1 control node , 1 etcd node and few worker nodes.
Once cluster is provisioned successfully , check for version:

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.9-rancher1", GitCommit:"68595e18f25e24125244e9966b1e5468a98c1cd4", GitTreeState:"clean", BuildDate:"2018-03-13T04:51:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-rancher1", GitCommit:"66aaf7681d4a74778ffae722d1f0f0f42c80a984", GitTreeState:"clean", BuildDate:"2018-03-20T16:02:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by deniseschannon** [comment]
From @ibuildthecloud: The kubectl client is packaged in rancher/agent. We will leave it as 1.8.x and doesn't need to match the exact versions of k8s on the server side.
