### ISSUE TITLE
Catalog Apps - add required or not required variables 

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12446]
Rancher versions: 2.0 master 04/03
Steps to Reproduce:

1. add https://github.com/guangbochen/rancher-catalog.git to the global catalog - branch:2.0
2. Go to Default project
3. Go to Catalog Apps and select wordpress

Expected Results: showing required(*) vs not required variables in the Configuration Options
![image](https://user-images.githubusercontent.com/4569037/38233893-b90a0612-374e-11e8-9540-de5d8c0164ee.png)

Add the required parameter to the questions.yml for frontend logic handling.
```questions:
- variable: wordpressUsername
  default: "user"
  description: "User of the application"
  type: string
  required: true
```

**Comment by guangbochen** [comment]
@StrongMonkey ^^ will use the required parameter for the questions.yml file

**Comment by StrongMonkey** [comment]
@guangbochen i believe this is also supported master.  Can you verify that if it is working in master?

**Comment by guangbochen** [comment]
Version rancher/master 04/03
verified fixed.
