### ISSUE TITLE
[cli] Feature Request: Create official rancher-cli image

### ISSUE THREAD

**Issue by spawnia** [rancher/rancher#12447]
I would like to use Rancher CLI in Gitlab CI and require an image where it is installed. I have used https://hub.docker.com/r/monostream/rancher-cli/ for a while, but now the repository has been deleted. While the image is fairly trivial to build, many people seem to have had the same problem, as evidenced by [this search](https://github.com/search?utf8=%E2%9C%93&q=rancher-cli&type=).

Could you put up an official image for `rancher-cli` at Docker Hub? It should be fairly simple, you can use https://github.com/blar/docker-rancher-cli as a template. Many users would profit from having an up-to-date, properly tagged image to use.

**Comment by superseb** [comment]
Can you check https://hub.docker.com/r/rancher/cli/tags/ and tell me if it's not sufficient?

**Comment by spawnia** [comment]
This looks great. However, i am missing a clear link from the CLI Readme to Docker, most projects use a badge for this. Also, can i view the Dockerfile you are using to build this container somewhere?

Thank you

**Comment by superseb** [comment]
Dockerfile can be found here: https://github.com/rancher/cli/blob/v1.6/package/Dockerfile
