### ISSUE TITLE
Catalog Apps  - variable name deos not show up

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12445]
**Rancher versions: 2.0 master  04/03**
Steps to Reproduce:
1. add https://github.com/guangbochen/rancher-catalog.git to the global catalog - branch:2.0
2. Go to Default project
3. Go to Catalog Apps and select wordpress

Variables in Configuration Options section is missing

![image](https://user-images.githubusercontent.com/4569037/38233468-4046fc36-374d-11e8-89a1-55e37f4fc8a3.png)

**Comment by westlywright** [comment]
2 part update. I'm adding fallback logic to use the questions variable as the label IF the question label doesn't exist. @StrongMonkey is updating the backend to add labels back end.

**Comment by StrongMonkey** [comment]
@guangbochen you can use `label` as your friendly name for your question. They should show up in UI.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/3
Verified fixed
