### ISSUE TITLE
Catalog Apps - upgrade error and the pod is not update properly

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12448]
Rancher versions: 2.0 master 04/03
Steps to Reproduce:
1. add https://github.com/guangbochen/rancher-catalog.git to the global catalog - branch:2.0
2. Go to Default project
3. Go to Catalog Apps and select memcached
4. Install version 2.0.2
5. Click on Upgrade available button and upgrade to the version 2.0.3

Results: upgrade failed and error message is shown
![image](https://user-images.githubusercontent.com/4569037/38234326-225b66dc-3750-11e8-99b3-45f22a24643e.png)

6. click edit Memcached app on catalog page and upgrade the template version 2.0.3 showing success but the pod is not upgraded to the new version.

**Comment by StrongMonkey** [comment]
You should really try upgrade action. Since there is no UI for upgrade and rollback yet, upgrading in UI is just a `put` which take no effect. 
Upgrade: post `templateVersionId` as input, which points to the version id user wants to upgrade
Rollback: post `revision` as input, which points to the revision id.

**Comment by guangbochen** [comment]
I tried with helm cli and I found it will encounter a `PodDisruptionBudget updates are forbidden` issue with StatefulSet app, for example like the Memcached app in our catalog, which returns

> Error: UPGRADE FAILED: StatefulSet.apps "mem1-memcached" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"chart":"memcached-2.0.3", "heritage":"Tiller", "release":"mem1", "app":"mem1-memcached"}: `selector` does not match template `labels` && PodDisruptionBudget.policy "mem1-memcached" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden.

Reference: https://github.com/kubernetes/kubernetes/issues/45398

should we return a proper error message from the tiller instead of a general message like upgrade error which is not debugging friendly?

**Comment by guangbochen** [comment]
verified fixed master 04/23, close issue.
