### ISSUE TITLE
Lower case error on registretion new github CI

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#12457]
**Rancher versions:**
rancher/server: v.2.0.0-alpha24
rancher/agent: v.2.0.0-alpha24

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux node-1 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
custome
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s
**Steps to Reproduce:**
- Create rancher server 2.0
- add 3 nodes
- add github CI (create OAuth App)
- Configure Rancher Pipeline to use your GitHub for authentication

**Results:**

SourceCodeCredential.management.cattle.io "cluster-sjp9l-github-Negashev" is invalid: metadata.name: Invalid value: "cluster-sjp9l-github-Negashev": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

![screenshot 69](https://user-images.githubusercontent.com/4653589/38242293-e05c20ca-374d-11e8-825f-45ef86b074a0.png)

**Comment by bmdepesa** [comment]
Validated on master 4/21. 

Created a github account with uppercase letters. Enabled github oauth with no errors.
