### ISSUE TITLE
No way to execute shell for sidekicks

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12454]
**Rancher versions:** 2.0 master 4/2

**Steps to Reproduce:**
1.  Create a workload
2.  Add a sidekick
3.  Try to execute the shell for the sidekick.

**Results:**  No way to execute shell

**Comment by orangedeng** [comment]
The equivalent command for kubectl is `kubectl exec -c <container name> <pod name> <command>`. I think we should support exec shell for sidekick.

**Comment by orangedeng** [comment]
For now, we use k8s proxy to expose the shell and we can specify the container of pod we connect to. The link is like following and you can see **container=test1** in the url parameters. 
```
wss://35.192.114.20/k8s/clusters/cluster-xh9zs/api/v1/namespaces/default/pods/test1-5fc66849d6-69n49/exec?container=test1&stdout=1&stdin=1&stderr=1&tty=1&command=%2Fbin%2Fsh&command=-c&command=TERM%3Dxterm-256color%3B%20export%20TERM%3B%20%5B%20-x%20%2Fbin%2Fbash%20%5D%20%26%26%20(%5B%20-x%20%2Fusr%2Fbin%2Fscript%20%5D%20%26%26%20%2Fusr%2Fbin%2Fscript%20-q%20-c%20%22%2Fbin%2Fbash%22%20%2Fdev%2Fnull%20%7C%7C%20exec%20%2Fbin%2Fbash)%20%7C%7C%20exec%20%2Fbin%2Fsh
```

**Comment by orangedeng** [comment]
/cc
@vincent99

**Comment by vincent99** [comment]
I asked for the issue.  The API is there, there's just no UI to call it.

**Comment by vincent99** [comment]
@loganhz Can you add a dropdown to the shell for the container name if there's more than one in the workload; default to the first container when first opened

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified fixed
