### ISSUE TITLE
Can't create node.js shell script step in Pipeline

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12451]
**Rancher versions:** 2.0 master 4/2

**Steps to Reproduce:**
1.  Create a pipeline
2.  Edit step 2 and select node.js option, put ./build.js as script
3.  Click on Save
4.  Click on step 2 again

**Results:**  the options for node.js has changed back to custom.  If I change it back and save the pipeline and then edit the pipeline/step2, it also is changed back to custom.  Should stay on the node.js option

**Comment by biblesyme** [comment]
Cause we don't save the environment option in API so that it just a quick setting button. May be we should change a component to show these options?

**Comment by biblesyme** [comment]
![image](https://user-images.githubusercontent.com/9334435/38287847-94a02958-37ff-11e8-9ac4-43d89374fa74.png)
@vincent99 How about we change to this?

**Comment by vincent99** [comment]
I don't know why you couldn't just map it backwards from a matching image back to the option.  A separate dropdown is confusing (what's custom going to pick?), Changing the dropdown already in the image picker would be better but these are all less obvious than it was before.

**Comment by vincent99** [comment]
On create you look at the file in the repo to decide the image for the step... On edit, look at the step and if the image is one of the ones you have special options for, select that, otherwise custom.

**Comment by biblesyme** [comment]
Ok, that's doable.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified fixed
