### ISSUE TITLE
Provide info about use of "--address X.X.X.X --internal-address X.X.X.X" for custom register url

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12466]
Rancher versions: Build from master

Provide info about use of "--address X.X.X.X --internal-address X.X.X.X" for custom register url in "Add /Edit cluster" page of a custom cluster.

**Comment by loganhz** [comment]
@vincent99 what should we do for this issue? Add two input to let user input the IP. And update the command line automatically like 1.6?

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
