### ISSUE TITLE
Catalog Apps - show deployed revisions and rollback

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12460]
Rancher versions: 2.0 master 04/03
Add deployed revisions and rollback feature to the catalog apps.

Steps to Reproduce:
1. add https://github.com/guangbochen/rancher-catalog.git to the global catalog - branch:2.0
2. Go to the default project
3. Go to Catalog Apps and select WordPress
4. Install version 0.8.10

Expected Results: need to add a button for rollback from the drop-down and be able to view the release versions.
![image](https://user-images.githubusercontent.com/4569037/38260133-61737c80-3799-11e8-9b11-3f06a687579e.png)

**Comment by StrongMonkey** [comment]
duplicate of https://github.com/rancher/rancher/issues/12448

**Comment by StrongMonkey** [comment]
This appears to be a operation issue. @guangbochen ^ Only when you rollback or upgrade to an incompatible template.

**Comment by deniseschannon** [comment]
@guangbochen can you try with a compatible template?

**Comment by guangbochen** [comment]
yes, rollback and upgrade work fine with a compatible template, but for incompatible template we can to use `kubectl patch` or `kubectl apply --force`  for a strategic merge path,  @StrongMonkey can we verify using `kubectl path` in the rollback feature.

**Comment by StrongMonkey** [comment]
@guangbochen i am thinking we shouldn't support upgrade if template are incompatible to upgrade. Raising an error should be good enough. `kubectl apply --force` is not what we want as it deletes the old resource. `kubectl patch` would probably skip the incompatible fields which means swallowing errors.

**Comment by guangbochen** [comment]
Raising an error seems looks fair enough and verified added error message master 04/26.

**Comment by guangbochen** [comment]
Raising an error seems looks fair enough and verified added error message master 04/26.
