### ISSUE TITLE
Catalog Apps - add rancher-charts to the global catalog page and set helm stable disabled on default

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12461]
add [rancher-charts](https://github.com/rancher/rancher-charts/) to the global catalog page and set helm stable disabled on default

![image](https://user-images.githubusercontent.com/4569037/38260224-9a8cccd8-3799-11e8-8be3-0a0cccf12bc8.png)

**Comment by deniseschannon** [comment]
@StrongMonkey before making any changes, talk to @ibuildthecloud about what we want the default behavior to be

**Comment by guangbochen** [comment]
rancher/charts is added on default on master 04/23, close this issue.
