### ISSUE TITLE
Validate Docker 18.03

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12462]
Validate latest Docker stable: 18.03.0

**Comment by rafaelgaspar** [comment]
Using version Docker version 18.03.0-ce, build 0520e24, on CoreOS alpha, fails with:

```
Found container ID: 415a4528bef4bff2abcefd8d8fbdfe82b481ee4bac23feee5428e27d3c75806f
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
time="2018-04-09T19:57:25Z" level=fatal msg="Failed to find state.json"
```

The same issue happens with latest stable version of CoreOS, with Docker version 17.12.1-ce, build 7390fc6.

**Comment by soumyalj** [comment]
Tested v1.6.17-rc1 (Cattle) using docker 18.03 on RHEL 7.3, RHEL 7.4 and Ubuntu 16.04. Tests ran successfully.
