### ISSUE TITLE
Unable to add Ingress when removing second rule

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12478]
Rancher versions: 2.0

Steps to Reproduce:
Add Ingress
Fill out all fields for first rule (Request Host, Path, Target, Port)
Add second rule.
Remove second rule.
Click Save.

Other information:
For some reason this only occurs if there is any information in the path field. If that value is empty, I am unable to save new rule after performing the listed steps. 

Results:
<img width="1365" alt="screen shot 2018-04-03 at 3 33 55 pm" src="https://user-images.githubusercontent.com/38012481/38279339-b48605a4-3754-11e8-8a6f-e9c4e6497d4e.png">

Unable to save new rule. Error message states port is still required.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified fixed
