### ISSUE TITLE
Auth AD - after authenticating, Add/Edit cluster showing principalIDs instead of username

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12476]
**Rancher versions:** 2.0 master 4/3

**Steps to Reproduce:**
1.  Create a rancher server
2.  Add a couple of local users
3.  Create a cluster and add users
4.  Authenticate using Active Directory
5.  Edit cluster and look at members

**Results:**
Before authenticating with AD
![image](https://user-images.githubusercontent.com/11514927/38277268-af93f5f4-374c-11e8-802a-f9a4690ccfe2.png)

After authenticating with AD
![image](https://user-images.githubusercontent.com/11514927/38277330-e4ddcd0c-374c-11e8-85d4-5cc39c722af1.png)

**Comment by deniseschannon** [comment]
Root Cause: https://github.com/rancher/rancher/issues/11868

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/5
Verified fixed
