### ISSUE TITLE
GKE is using private ip instead of public for public endpoints

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12470]
**Rancher versions:** 2.0 master 4/3

**Steps to Reproduce:**
1.  Setup a GKE cluster
2.  Create a nginx workload and add a port

**Results:**  Public endpoint is using private ip instead of public

**Comment by deniseschannon** [comment]
Similar Issue: https://github.com/rancher/rancher/issues/11969

**Comment by alena1108** [comment]
@vincent99 we would need a UI fix on top of backend fixes, to read node.externalIpAddress first, and if empty, fallback to node.ipAddress

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/3
Verified fixed
