### ISSUE TITLE
Links for workloads with exposed ports are not functional for AWS driver machine clusters

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12473]
**Rancher versions:**
rancher/server: Master

**Steps to Reproduce:**
1. Create a cluster with AWS driver machine(AWS node template)
2. Create a workload using nginx image with container exposed port(80) and random source port
Once the workload is created, click on the link with the random source port.
The link is not accessible. 

<img width="1273" alt="screen shot 2018-04-03 at 2 09 40 pm" src="https://user-images.githubusercontent.com/18536626/38276053-aee6a89e-3748-11e8-941c-a7310d38e0dd.png">

The cluster nodes have internal IPs set and hence the link is not accessible.

<img width="1255" alt="screen shot 2018-04-03 at 2 14 21 pm" src="https://user-images.githubusercontent.com/18536626/38276291-5da362c8-3749-11e8-88e7-347e37676ce0.png">

[Note: In DO cluster the public IP is set on the nodes and the link is functional and displays the standard "Welcome to nginx" page]

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/11969.
