### ISSUE TITLE
Provisioning fails when server is running on local cluster

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#12485]
**Rancher versions:**
rancher/server: rancher 2.0 master 03/04

**Steps to Reproduce:**
- Create a k8s cluster using rke with AWS nodes
- Deploy rancher using this [manifest](https://github.com/rancher/rke/blob/master/rancher-minimal.yml)
- Try to create a DO cluster, single node all roles
**Results:**
Cluster provisioning fails with the following error on the UI:
```
 [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [104.131.101.68]: Get https://localhost:6443/healthz: can not build dialer to cluster-sfttr:m-7k44g 
```

**Comment by deniseschannon** [comment]
As @moelsayed was using AWS clusters, this should work. 

@soumyalj can you test as this is similar to the HA path but using AWS as the nodes.

**Comment by soumyalj** [comment]
Tested with rke version v0.1.6-rc3. Created a 2.0 HA cluster(local cluster) using AWS hosts with master build
Cluster came up successfully. kubectl was functional. Another digital ocean cluster was created successfully too.

**Comment by feffi** [comment]
running on vsphere i got the same behaviour when using custom CA and cert. Without certs, it seems ok. Have not tried spanning master/worker/etcd in different node pools yet.
