### ISSUE TITLE
Catalog Apps - show advanced options as open on default

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12487]
Rancher versions: 2.0 master 04/03
Steps to Reproduce:
1. add https://github.com/guangbochen/rancher-catalog.git to the global catalog - branch:2.0
2. Go to the Default project
3. Go to Catalog Apps and select WordPress

Currently, the advanced options only include the namespace and it is preferred to show by default.

![image](https://user-images.githubusercontent.com/4569037/38286268-1b6b75ea-37f7-11e8-8a28-46360f135fd8.png)

Expected Results: 
![image](https://user-images.githubusercontent.com/4569037/38286295-3b89e578-37f7-11e8-8097-fd3534673952.png)

**Comment by vincent99** [comment]
It is intentionally hidden because a new namespace is created for each app by default and we do not expect most users to need to change it.
