### ISSUE TITLE
gke in provision state shows failed message before becoming active

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12480]
**Rancher versions:** 2.0 master 4/3

**Steps to Reproduce:**
1.  Setup GKE cluster

**Results:**  Before it becomes active it always shows a red provisioning message that says "Failed to configure serviceAccountToken".  This makes it look like my cluster failed to provision when really it just hasn't finished yet.
![image](https://user-images.githubusercontent.com/11514927/38281035-793781e0-375d-11e8-97b0-5d8354cbf772.png)

**Comment by davecore82** [comment]
I also just saw this issue. My GKE cluster deployed through Rancher 2.0 showed "Failed to configure serviceAccountToken" for approx. 2-4 minutes, enough time to search the web and find this bug and wait a couple minutes to see that it did complete successfully in the end.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/18
Verified fixed.
