### ISSUE TITLE
union containers in kafka cluster by number on separeted hosts

### ISSUE THREAD

**Issue by legeech** [rancher/rancher#12489]
**Rancher versions:**
rancher/server: v1.6.15
rancher/agent: v1.2.10

**Infrastructure Stack versions:**
healthcheck:v0.3.6
ipsec:v0.13.11
network-services:v0.7.20
scheduler:v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.12.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 178
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: dockertest
ID: K35Z:MIRX:ICLW:UF6S:AYLO:YL2E:HHCZ:5VWK:GAAM:D2Y4:C2IK:J5EZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vmware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher , internal DB 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
i have 3 hosts
1. install kafka cluster from Catalog
2. so i have 9 containers (3-broker,3-volume,3-conf)
3. BUT all of them randomly start at hosts

**Results:**

the problem is if one of host is fall down in kafka cluster work only one broker because second broker lose data from dead host
example:
host1 have - broker1 - volume2 -conf3
host2 have - broker3 - volume1 -conf2
host3 have - broker2 - volume3 -conf1

i cant understand how to config shedulling service (and may be host labels) to make this 
host1 have - broker1 - volume1 -conf1
host2 have - broker2 - volume2 -conf2
host3 have - broker3 - volume3 -conf3
etc (if extend cluster to fourth host)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
