### ISSUE TITLE
Ability to disable check for 'RSA key missing NULL parameters' when connecting securely to AD/LDAP

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12494]
When a certificate is not created according to RFC (`The RFC is clear that the Parameters in an AlgorithmIdentifer for an RSA public key must be NULL.`) and you are connecting securely to LDAP/AD, it will fail with the error:

```
Error creating ssl connection: LDAP Result Code 200 "": tls: failed to parse certificate from server: x509: RSA key missing NULL parameters
```

Option 1 is to fix the certificate by re-creating it according RFC, this request is for disabling/ignoring this check.

Related:
https://github.com/golang/go/commit/59aeac20c0412442848982a9287b4bab66c25682
https://github.com/elazarl/goproxy/issues/188

**Comment by mssalvadk** [comment]
Hi - I'm new to Go and trying to test the Go Ldap and hit this x509 RSA error.  Please share how to disable this check.  Thank you! ;)

**Comment by superseb** [comment]
This is an enhancement request to disable the check as it's not possible as of today. The best way to fix this is to re-generate and apply a newly generated certificate that is valid according to RFC.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
