### ISSUE TITLE
Unable to add custom DO node with uppercase characters

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12499]
Rancher versions: 2.0

Steps to Reproduce:
Create a new droplet in DO with a name containing uppercase characters
Attempt to add node to a custom cluster

Results:
<img width="1284" alt="screen shot 2018-04-04 at 12 07 21 pm" src="https://user-images.githubusercontent.com/38012481/38328834-c6a6dcca-3800-11e8-825f-4d3d1d53181f.png">

Unable to add node due to uppercase characters.

**Comment by deniseschannon** [comment]
@alena1108 is there anything we can do when custom has uppercase letters?

**Comment by alena1108** [comment]
@deniseschannon the issue should be fixed in the latest.

**Comment by adingilloRancher** [comment]
Master 4/17/18
Verified Fix.
