### ISSUE TITLE
Stuck @ management server UI - must authenticate

### ISSUE THREAD

**Issue by mysim1** [rancher/rancher#12492]
**Rancher versions:**
rancher/server: master (3 april 2018)
rancher/agent: master (3 april 2018)

After running 1 day and my API / Key expired. I get stuck when attempt to login on management server.

![photo5920340542267436112](https://user-images.githubusercontent.com/795626/38301267-5c581060-37ff-11e8-802b-0666c71eb3cd.jpg)

**Comment by guruvan** [comment]
Had this issue running from a master build from yesterday 
Restarted the server container which had no effect
Stopped the rancher/server container, created a data container, upgraded to rancher/server:v2.0.0-alpha26, started the new container 

I saw this in the logs of the new server which may or may not be related:
  ```
  2018/04/04 16:30:36 [ERROR] API error response 401 for POST /v3-public/localProviders/local?action=login. Cause: crypto/bcrypt: hashedPassword is not the hash of the given password
  ```
Upgraded Server presented a normal login screen with no error.

**Comment by deniseschannon** [comment]
This is fixed in the latest release, which is why we don't recommend users to use master as it's easy for things to be broken.

**Comment by soakes** [comment]
Hi there,

I am getting the exact same thing if I build the cluster via rke.  

I am using this: 

https://raw.githubusercontent.com/rancher/rke/master/rancher-minimal-passthrough.yml

With the respected bits changed (node info+fqdn).

Any ideas?

Kind Regards
