### ISSUE TITLE
Feature request - service locality 

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#12491]
The current rancher DNS implementation doesn't take into consideration locality.

Let's say we have a NATS cluster deployed globally. I would want the clients to subscribe through the local NATS instances rather than a random one, which could be located anywhere in the infrastructure. 

This is especially important for data flow and latency.

The DNS search should be taking into account the concept of a region/datacenter when resolving hostnames.

* search in stack.region.rancher.internal
* search in service.stack.region.rancher.internal
* search in stack.rancher.internal
* search in service.stack.rancher.internal
* search in rancher.internal

The region should really be set on a host-per-host basis. Maybe it could be a new rancher label?

Any thoughts?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
