### ISSUE TITLE
Supporting TLSv1.2 for MySQL over SSL in v1.6.x

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#12504]
**Rancher versions:** 
rancher/server: tested on v1.6.15
rancher/agent:

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External DB

Currently, support for TLSv1.2 in mysql is only available in MySQL enterprise edition 5.7.10+. This is because the community edition is compiled against yaSSL while the enterprise edition is compiled against OpenSSL. More details [here](https://dev.mysql.com/doc/refman/5.7/en/ssl-libraries.html)

Percona MySQL distribution provides support for TLSv1.2, but the database client library used internally doesn't, most likely because it's linked against Oracle's MySQL client library.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
