### ISSUE TITLE
When control node changes , not able to launch kubectl shell or connect to cluster using kubeconfig.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12509]
Rancher versions: v2.0.0-alpha26

**Steps to Reproduce:**

DO cluster with 1 control node , 1 etcd node and 2 worker nodes.
Wait for cluster to start successfully and get to "active" state.

Delete  control node.
This results in new control node being added to the cluster.
Wait for the cluster to get back to "Active" state.

We are able to deploy workflow on existing and new namespaces.

But we are not able to launch kubectl , it gets stuck in "Connecting" state .

Also not able to connect using remote kubectl using the generated kubeconfig file.

```
LaviniapleWatch:~ sangeethahariharan$ ./kubectl get nodes
Error from server (InternalError): an error on the server ("Error: 'EOF'\nTrying to reach: 'https://104.236.12.30:6443/api'") has prevented the request from succeeding
LaviniapleWatch:~ sangeethahariharan$ 
```

**Comment by soumyalj** [comment]
Tested with master from April 15th.  Tried with the steps above. Still see the same issue:
Launching kubectl through UI is stuck in "Connecting State"
<img width="1371" alt="screen shot 2018-04-15 at 9 02 48 pm" src="https://user-images.githubusercontent.com/18536626/38789632-69bfd676-40f0-11e8-9a84-6aa6f9a245f2.png">
Not able to connect through remote kubectl:
```
soumyas-MBP:~ soumya$ kubectl get pod
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods)
soumyas-MBP:~ soumya$ kubectl get node
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
soumyas-MBP:~ soumya$ 



```

**Comment by soumyalj** [comment]
Tested with master from April 16th. 
Create a DO cluster with 1 control node , 1 etcd node and 2 worker nodes.
1. Wait for cluster to start successfully and get to "active" state.
2. Delete control node.
This results in new control node being added to the cluster.
Wait for the cluster to get back to "Active" state.
Once the cluster was active, kubectl got launched successfully. Connecting to remote kubectl was also worked. Creating new workloads was also fine. 

<img width="1177" alt="screen shot 2018-04-16 at 1 44 50 pm" src="https://user-images.githubusercontent.com/18536626/38834132-61334704-417c-11e8-9ab3-27b9929206f8.png">

**Comment by michalmikolajczyk** [comment]
Rancher 2.0.6
I am experiencing the very same issue. The cluster seems to work but unreachable via kubectl.
```
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
```

**Comment by michalmikolajczyk** [comment]
also workloads are unreachable via shell
