### ISSUE TITLE
When there control node is powered down , node continues to be shown as being in "active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12511]
**Rancher versions: v2.0.0-alpha26

Steps to reproduce the problem:

Create a DO cluster with 1 control node , 1 etcd node and few worker nodes.
Wait for cluster to get to active state.

Power down the control node from DO console.

Control node continues to be shown as being in "active" state.

Is there a way to show the status as being "Unavailable" in this case  like we do for worker nodes ?

**Comment by deniseschannon** [comment]
Per @ibuildthecloud, this should be done in the UI, where when the cluster is unavailable (control node goes down), the nodes should be marked as Unavailable.

**Comment by vincent99** [comment]
#12176

**Comment by sangeethah** [comment]
Keeping this reopen, to test the specific use case of bringing down the control node.

**Comment by sangeethah** [comment]
Tested with latest build from master:

setup - Custom cluster with AWS nodes -  1 control node - n1 , 1 etcd node -n2 and 3 worker nodes .
Add a new control node - n2.

Power off / Delete control node - n1 from AWS console.

As soon as the control node gets deleted from the AWS console , it gets to "Unavailable" state in rancher UI . At this state , I am still able to continue to deploy new pods for something .In this case Cluster is also in Active state .But after a while , cluster gets to "updating" state and it gets stuck there forever .
Even when I have another control node in the plane , I dont see the cluster using the new control plane and get to active state .

**Comment by soumyalj** [comment]
Tested with Master from April 18. 
Created a custom cluster using AWS hosts:
N1 control node, N2 etcd node and N3, N4 - worker nodes
After the cluster is active, add another node N5 - control node
Delete N1. The node goes to "Unavailable" state as expected.
The cluster is active and workload creation is successful. kubectl is functional through UI and remote
```
soumya$ kubectl get node
NAME               STATUS     ROLES          AGE       VERSION
ip-172-31-16-128   Ready      controlplane   20m       v1.8.10-rancher1
ip-172-31-17-178   Ready      etcd           2h        v1.8.10-rancher1
ip-172-31-18-124   NotReady   controlplane   1h        v1.8.10-rancher1
ip-172-31-26-233   Ready      etcd           31m       v1.8.10-rancher1
ip-172-31-28-99    Ready      worker         2h        v1.8.10-rancher1
ip-172-31-31-107   Ready      worker         2h        v1.8.10-rancher1

```
