### ISSUE TITLE
configMap not available as option to use in deployments.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12513]
Rancher versions: v2.0.0-alpha27

**Steps to Reproduce:**

Created a config name for a namespace.

<img width="1113" alt="screen shot 2018-04-04 at 8 23 23 pm" src="https://user-images.githubusercontent.com/4266958/38345838-341daf28-3846-11e8-9524-942d194f3b7a.png">

When creating a pod in this namespace , "Add from Source" does not have Config Map option enabled.

<img width="1119" alt="screen shot 2018-04-04 at 8 27 52 pm" src="https://user-images.githubusercontent.com/4266958/38345927-ade2fbec-3846-11e8-94bb-696c38b7658e.png">

For volume , there is no "use a config map" option.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
