### ISSUE TITLE
Allowed to create ingress with same rules (host and path) pointing to different workloads which are not functional.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12514]
Rancher versions: v2.0.0-alpha27

**Steps to Reproduce:**

Create Ingress1 with host - "test.com" and  path "/name.html" pointing to workload - "wl1" in namespace - "ns1"

When accessing ingress url using  host - "test.com" and  path "/name.html" , traffic gets directed to "wl1" as expected.

Create Ingress2 with host - "test.com" and  path "/name.html" pointing to workload - "wl2" in namespace - "ns2"

When accessing ingress url using  host - "test.com" and  path "/name.html" , traffic gets directed to only "wl1".

What should be expected here ?  If this is the expected behavior , can we prevent users from creating conflicting ingress rules that have the same rules but different targets?

Note - When  Ingress1 gets deleted, then ingress URL directs traffic to "wl2".

**Comment by alena1108** [comment]
@sangeethah lets keep this issue open till we figure out the strategy for hostname/path validation. RKE ingress controller is a global LB. It means that *all* rules in cluster (cross diff namespaces) have to be unique as they get programmed to the same ingress.

similar issue: https://github.com/rancher/rancher/issues/11800
