### ISSUE TITLE
Release rancher 2 with different latest/stable/enterprise stream tags or container names

### ISSUE THREAD

**Issue by skyscooby** [rancher/rancher#12527]
Noticed this isn't the case with rancher/server:preview so wanted to call it out..

When rancher 2 ships existing 1.6 incompatible installations could pull new packages if 
server/agent stream isn't either tagged differently or new docker image names are used..

like 
rancher/server:latest-v2
rancher/server:stable-v2
rancher/server:enterprise-v2
rancher/agent:latest-v2

or 
rancher/server-v2:latest
rancher/server-v2:stable
rancher/server-v2:enterprise
rancher/agent-v2:latest

Just wanted to ensure it's being considered

**Comment by ibuildthecloud** [comment]
Naming things, it's hard 😀

We've thought of this and haven't come to a conclusion.  The one thing that's for sure is that rancher/server: latest will stay 1.6 as we don't want to accidently break the huge amount of deployments or there.

**Comment by deniseschannon** [comment]
When we start tagging GA releases, we will be going with `rancher/rancher:v2.0.0` and `rancher/rancher-agent:v2.0.0`
