### ISSUE TITLE
Implement remaining docker-machine flags for Digitalocean droplets

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12521]
**Rancher versions:**
rancher/server: v1.6 / v2.0

- Ability to add tags to machines (useful when using in combination with a loadbalancer/firewall)
```
--digitalocean-tags: Comma-separated list of tags to apply to the Droplet
```

- Ability to enable monitoring
```
--digitalocean-monitoring: Enable monitoring for the droplet.
```

**Comment by loganhz** [comment]
There is no `monitoring` field in 2.0 `/v3/schemas/digitaloceanconfig`

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Tag are working
Still no monitoring info in API so that isn't working.  Sending over to Daishan

**Comment by aiwantaozi** [comment]
Darrent updates the docker-machine version to 0.14.0 this version include the digitalocean driver flag --digitalocean-monitoring. 
![image](https://user-images.githubusercontent.com/5936271/39105076-2685d210-46e6-11e8-824c-de1f4875e669.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/23
Verified fixed - monitoring is now available and works for DO RKE.
