### ISSUE TITLE
[2.0.0-beta1] Cluster provisioning issue. invalid mount config

### ISSUE THREAD

**Issue by mikekuzak** [rancher/rancher#12520]
HI All,

Getting an issue provisioning the Kubernetes Cluster with new Rancher Beta. This did work with the latest Alpha-24

This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

[workerPlane] Failed to bring up Worker Plane: Failed to create [kubelet] container on host [10.132.194.37]: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate"

Regards
---
| Useful | Info |
| :-- | :-- |

Kubernetes 1.9.5, coreos is on 1688.5.3 and docker is on 17.12.1-ce and etcd on 3.1.12
|Versions|Rancher `v2.0.0-beta1` UI: `v2.0.33` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by superseb** [comment]
This is a Docker 17.12.1 (and up) specific error, and was broken before beta. Docker 17.12.0 should work, but only up to 17.03.2 is supported from a Kubernetes point of view. Let me know if using a different Docker version doesn't solve this.

**Comment by mikekuzak** [comment]
Yes confirmed, Thank you!
