### ISSUE TITLE
AD Authentication fails if IP or Hostname is used for domain controller address

### ISSUE THREAD

**Issue by junkiebev** [rancher/rancher#12528]
Setting up AD using the hostname of a domain controller fails - The hostname isn't known because it uses the google DNS service (rather than the DNS service of the host machine) for lookups.

Setting up AD using the IP of a domain controller fails - The certificate issues doesn't validate because the presented certificate doesn't contain any IP Subject Alternative Names.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta1` UI: `v2.0.33` |
|Access|`local` `admin`|
|Route|`global-admin.security.authentication.localauth`|

**Comment by vincent99** [comment]
The server is a regular container that uses whatever DNS is configured on the daemon/for specified in `docker run ... rancher/server`.  So if you need to resolve names that aren't in there, you need to change the config of the daemon or container.

**Comment by vincent99** [comment]
And SSL to the IP is supposed to fail.  The cert isn't for the IP.

**Comment by junkiebev** [comment]
The command I used to run the container
`sudo docker run -d -p 80:80 -p 443:443 rancher/server:preview`
The server resolves the domain controller correctly using nslookup/ping/whatever

The error was that 8.8.8.8:53 had no record for controller.mycompany.com which is expected - it is an internal hostname

**Comment by cjellick** [comment]
Were those commands ran form inside the rancher/server container or on the host? 
If they were not run from inside the container, can you exec into it and do the same?

**Comment by junkiebev** [comment]
The above was from the host OS

This is inside the container

```
root@6402ca521767:/var/lib/rancher# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

search mycompany.com

nameserver 8.8.8.8
nameserver 8.8.4.4
```

```
root@6402ca521767:/var/lib/rancher# nslookup controller.mycompany.com
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find controller.mycompany.com: NXDOMAIN

```

systemd-resolve isn't on there - I can

**Comment by cjellick** [comment]
Your host has a dns resolver running at 127.0.0.1:53. That is allowing your host to resolve that domain, but the rancher/server container doesnt see that resolver.
It is the host's localhost IP and docker is filtering it out when constructing the resolv.conf for the container. Here's how docker explains it in their documentation, which covers the exact scenario you are hitting.
> Regarding DNS settings, in the absence of the --dns=IP_ADDRESS..., --dns-search=DOMAIN..., or --dns-opt=OPTION... options, Docker makes each container’s /etc/resolv.conf look like the /etc/resolv.conf of the host machine (where the docker daemon runs). When creating the container’s /etc/resolv.conf, the daemon filters out all localhost IP address nameserver entries from the host’s original file.
> Filtering is necessary because all localhost addresses on the host are unreachable from the container’s network.
...
> Note: If you need access to a host’s localhost resolver, you must modify your DNS service on the host to listen on a non-localhost address that is reachable from within the container.

https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/

So, you'll probably want to review that docker documentation and find a setup that works for you. If you are just kicking the tires on rancher 2.0, you could just add `--net=host` to run the container in the host's network namespace.
