### ISSUE TITLE
[1.6] Documentation missing / incomplete for proxy protocol

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#12523]
According to #1677 it is supported to run rancher behind a reverse proxy that uses the proxy protocol.

According to the documentation this is possible: https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#enabling-proxy-protocol

However there is no mention of how to enable it on the rancher server. When using the proxy protocol connections should always only be accepted from trusted IPs otherwise it is a SECURITY risk.
Based on that fact one would expect there is an option to:
- Enable / disable proxy protocol support on the rancher side.
- Configure which source IPs are trusted.

There is no mention in the documentation anywhere to configure the options above.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
