### ISSUE TITLE
When standard user tries to create a cluster using a DO nodetemplate gets a forbidden message for nodepool creation in cluster namespace.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12532]
Rancher server version - v2.0.0-alpha28

Steps to reproduce the problem:
As a standard user , create a cluster.
As part of creating cluster , create a DO template.
User is presented with this error message:

<img width="1077" alt="screen shot 2018-04-05 at 11 50 02 am" src="https://user-images.githubusercontent.com/4266958/38385739-8f5b4720-38c7-11e8-97a3-0a02a6c274e6.png">

By trying to create again succeeds.

**Comment by kinarashah** [comment]
@sangeethah 
1) Created a standard user as an admin. 
2) Logged in as standard user. 
3) Created node template 

I am unable to reproduce, am I missing anything? (or might have been fixed, could you confirm)

**Comment by sangeethah** [comment]
This issue reproduces consistently in my setup.

Tested with v2.0.0-beta3-rc1 and showed it to @kinarashah .

**Comment by cjellick** [comment]
Backend fixed. @vincent99 can you now change to waiting on this condition on the cluster before creating the nodepool? `InitialRolesPopulated`

**Comment by sangeethah** [comment]
Tested with latest build from mater.

This issue is not seen anymore.

**Comment by soumyalj** [comment]
Observed this issue in v2.0.0. Created a cluster as a standard user and the error was seen. When clicked on create twice, the cluster got created.

**Comment by soumyalj** [comment]
Observed this issue in 2.0.1-rc6 too. This issue is not just for initial(first) logins.

**Comment by loganhz** [comment]
It looks like standard users still can not create any kind of clusters in rancher/rancher:master (`custom`, `import`, `node driver`).

If you are trying a local setup, you can almost reproduce it every time.  

UI already waits for `InitialRolesPopulated` condition but it doesn't help.

After UI detected `InitialRolesPopulated` condition, UI has to wait for another 4 or 5 seconds. Then `POST` `/v3/nodepool` will return `201` instead of `403`.

**Comment by deniseschannon** [comment]
@cjellick it sounds like we need to investigate this for v2.0.3 if no standard user can create clusters

**Comment by sangeethah** [comment]
Tested with latest build from master
Not able to reproduce the issue when trying to create DO cluster multiple times.
Able to create custom and import clusters as well.
Importing of cluster fails which is tracked in https://github.com/rancher/rancher/issues/14030
