### ISSUE TITLE
Limited AWS IAM policy

### ISSUE THREAD

**Issue by sigginet** [rancher/rancher#12530]
I had an issue with launching Kubernetes on AWS.
@ibuildthecloud helped me figure out some of the rules needed through a docker machine issue.

This is the IAM policy that I ended up using, it worked properly for me to launch a server
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "TheseActionsDontSupportResourceLevelPermissions",
            "Effect": "Allow",
            "Action": [
                "ec2:CreateKeyPair",
                "ec2:DeleteKeyPair",
                "ec2:ImportKeyPair",
                "ec2:Describe*",
                "ec2:CreateTags",
                "ec2:CreateSecurityGroup",
                "ec2:AuthorizeSecurityGroupIngress",
                "iam:PassRole"
            ],
            "Resource": "*"
        },
        {
            "Sid": "ThisActionsSupportResourceLevelPermissions",
            "Effect": "Allow",
            "Action": [
                "ec2:RunInstances"
            ],
            "Resource": [
                "arn:aws:ec2:eu-west-1::image/ami-*",
                "arn:aws:ec2:eu-west-1:%YOUR_AWS_ACCOUNT_ID%:instance/*",
                "arn:aws:ec2:eu-west-1:%YOUR_AWS_ACCOUNT_ID%:key-pair/*",
                "arn:aws:ec2:eu-west-1:%YOUR_AWS_ACCOUNT_ID%:network-interface/*",
                "arn:aws:ec2:eu-west-1:%YOUR_AWS_ACCOUNT_ID%:placement-group/*",
                "arn:aws:ec2:eu-west-1:%YOUR_AWS_ACCOUNT_ID%:security-group/*",
                "arn:aws:ec2:eu-west-1:%YOUR_AWS_ACCOUNT_ID%:subnet/*",
                "arn:aws:ec2:eu-west-1:%YOUR_AWS_ACCOUNT_ID%:volume/*"
            ]
        },
        {
            "Sid": "TheseActionsSupportResourceLevelPermissions",
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances",
                "ec2:StopInstances",
                "ec2:StartInstances",
                "ec2:RebootInstances"
            ],
            "Resource": [
                "arn:aws:ec2:eu-west-1:%YOUR_AWS_ACCOUNT_ID%:instance/*"
            ]
        }
    ]
}
```

**Rancher versions:**
rancher/server: 2.0-beta1
rancher/agent: 2.0-beta1

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

**Results:**

**Comment by loganhz** [comment]
Thanks for your update! Close it as it is not an issue.

**Comment by neilfrndes** [comment]
I added these AWS managed policies to the rancher user to deploy a cluster with AWS:
AmazonEC2FullAccess
IAMFullAccess
ElasticLoadBalancingFullAccess
AmazonSNSFullAccess
AWSDeepRacerCloudFormationAccessPolicy
EKS-Admin -> https://docs.aws.amazon.com/eks/latest/userguide/EKS_IAM_user_policies.html
