### ISSUE TITLE
Container stuck in starting state when created with nfs volume driver

### ISSUE THREAD

**Issue by nrgiroux** [rancher/rancher#12531]
Hi,

I am using rancher-nfs from the catalog, starting a service either from the UI or from rancher-compose with simple parameters (from the docs' examples).

Server and hosts running on RancherOS.
I can't see what is (I'm doing) wrong.

Could you help me please. 
Thanks

Component | Version
-- | --
Rancher | v1.6.14
Cattle | v0.183.37
User Interface | v1.6.37
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5
storage-nfs | v0.8.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel:**
cat /etc/os-release
NAME="RancherOS"
VERSION=v1.2.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.2.0
PRETTY_NAME="RancherOS v1.2.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
uname -r : 4.9.78-rancher2

**Type/provider of hosts:** VirtualBox

**Setup details:** single node rancher, internal DB

**Environment Template:** Cattle

**Steps to Reproduce:**
From the UI:
Infrastructure/Storage -> Storage Drivers (rancher-nfs) Add Volume
Name: volume1 -> Create

Stacks/User -> Add Service
Name: vol1, 
Volumes tab:
 +Add Volume: vol1:/mnt/vol1

**Results:**
vol1 stuck in 'Starting' state for always.

**Comment by StrongMonkey** [comment]
@nrgiroux can you grab the log from nfs-driver to see if you have successfully created and attached the volume? if volume failed to attach the container may get stuck in a look.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
