### ISSUE TITLE
kontainer-engine needs ability to add tags to clusters

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12533]
talk to @ibuildthecloud about it :)

**Comment by nathan-jenan-rancher** [comment]
Add tags to resources in the various cloud provides so they can be tied back to their rancher clusters.

In GKE:
Label on the GKE cluster

In AKS:
Tag on the AKS cluster

In EKS
Tag on the cloud formation resources (EKS cluster does not have a field that can be tagged)

**Comment by soumyalj** [comment]
Created EKS cluster on beta4-rc3. displayName could be observed in the AWS cloudformation portal  for the associated cluster. The displayName is seen in the Tags section

<img width="1273" alt="screen shot 2018-04-25 at 10 49 38 am" src="https://user-images.githubusercontent.com/18536626/39263254-7b1ef0c2-4876-11e8-82be-ddfbac25169d.png">
