### ISSUE TITLE
Improve logging when adding worker when there is no etcd/controlplane node present

### ISSUE THREAD

**Issue by gwiersma** [rancher/rancher#12548]
**Rancher versions:**
rancher/server: v2.0.0-beta1
rancher/agent: agent:v2.0.0-beta1 

**Docker version:**
Server Version: 17.03.2-ce

**Operating system and kernel:**
Ubuntu 16.04.4 LTS (Xenial Xerus)"
4.13.0-38-generic

**Type/provider of hosts:** 
VMware vSphere 

**Setup details:** 
1 master
3 workers

**Steps to Reproduce:**
- Create new cluster
- Add custom worker only node
- copy and paste custom docker run command on the worker node
- agent container starts, but can not register with master
**Results:**
Docker Logs output (worker):

```
time="2018-04-06T09:59:44Z" level=info msg="Option worker=true"
time="2018-04-06T09:59:44Z" level=info msg="Option requestedHostname=worker02"
time="2018-04-06T09:59:44Z" level=info msg="Option customConfig=map[address:172.30.55.22 internalAddress: roles:[worker]]"
time="2018-04-06T09:59:44Z" level=info msg="Option etcd=false"
time="2018-04-06T09:59:44Z" level=info msg="Option controlPlane=false"
time="2018-04-06T09:59:44Z" level=info msg="Connecting to wss://master01.<domain>/v3/connect/register with token zgbp6fr46ncqvxjbk2z76jtc4l2lmpfkb4krq6hj7mdfnwvb6bfpr6"
time="2018-04-06T09:59:44Z" level=info msg="Connecting to proxy" url="wss://master01.<domain>/v3/connect/register"
time="2018-04-06T10:20:45Z" level=info msg="Error while getting agent config: invalid response 500: secrets \"c-cluster-lwvm6\" not found"
time="2018-04-06T10:20:50Z" level=info msg="Error while getting agent config: invalid response 500: secrets \"c-cluster-lwvm6\" not found"
```

**Comment by cuseinovic** [comment]
Hi,

You don't need to have at least 1 etcd and 1 controlplane ?
You can't have just 3 workers.

**Comment by gwiersma** [comment]
@cuseinovic Fixed. Could be a improvement for the dashboard when creating a new cluster.

**Comment by cuseinovic** [comment]
@gwiersma Your welcome :) 
Indeed, it will be great to know in the Dashboard the number of etcd, controlplane, workers like in rancher 1.6

**Comment by ipeevski** [comment]
I ran into the same problem. From the comments, I can't work out what is the solution - do I need separate nodes for etcd / control? In the latest version, there are checkboxes for them and looks like you can create an agent to do all three - that's what I was trying to do, but still get the same error message. What can I try next?

**Comment by timmo001** [comment]
I'm getting the same issue as @ipeevski 
I spin up the server, add a cluster with custom as I am installing on baremetal, check all three boxes, copy the docker command and I still get the same error message:

`"Error while getting agent config: invalid response 500: secrets \"c-cluster-p65j5\" not found"`

**Comment by ipeevski** [comment]
I  think after installing kubernetes on the underlying machine, it started working for me ...

**Comment by superseb** [comment]
Please share complete logging of the `rancher/server` and `rancher/agent` container when this happens.

**Comment by mrWinston** [comment]
Hi! 
Having the same problem here when trying to create a new cluster. here's the output from the agent:
```
time="2018-04-11T13:39:49Z" level=info msg="Option worker=true"
time="2018-04-11T13:39:49Z" level=info msg="Option requestedHostname=*********"
time="2018-04-11T13:39:49Z" level=info msg="Option customConfig=map[address:******** internalAddress: roles:[etcd worker controlplane]]"
time="2018-04-11T13:39:49Z" level=info msg="Option etcd=true"
time="2018-04-11T13:39:49Z" level=info msg="Option controlPlane=true"
time="2018-04-11T13:39:49Z" level=info msg="Connecting to wss://rancher.********/v3/connect/register with token tlpbmlz4sknzqlfbx44kdbs9264rd7rwv9qktngqr6gdkk5j6sbrjt"
time="2018-04-11T13:39:49Z" level=info msg="Connecting to proxy" url="wss://rancher.********/v3/connect/register"
time="2018-04-11T13:39:49Z" level=info msg="Error while getting agent config: invalid response 500: secrets \"c-cluster-jjqnx\" not found"
time="2018-04-11T13:39:54Z" level=info msg="Error while getting agent config: invalid response 500: secrets \"c-cluster-jjqnx\" not found"
time="2018-04-11T13:39:59Z" level=info msg="Error while getting agent config: invalid response 500: secrets \"c-cluster-jjqnx\" not found"
time="2018-04-11T13:40:04Z" level=info msg="Error while getting agent config: invalid response 500: secrets \"c-cluster-jjqnx\" not found"
time="2018-04-11T13:40:09Z" level=info msg="Error while getting agent config: invalid response 500: secrets \"c-cluster-jjqnx\" not found"
```

And here are the logs from the rancher master:
```
E0411 13:34:11.318478       1 tokens_controller.go:259] error synchronizing serviceaccount project-j7grp/default: secrets "default-token-nd4bn" is forbidden: unable to create new content in namespace project-j7grp because it is being terminated.
E0411 13:34:11.330094       1 tokens_controller.go:259] error synchronizing serviceaccount project-j7grp/default: secrets "default-token-hzcg5" is forbidden: unable to create new content in namespace project-j7grp because it is being terminated.
E0411 13:34:11.346113       1 tokens_controller.go:259] error synchronizing serviceaccount project-j7grp/default: secrets "default-token-h74zj" is forbidden: unable to create new content in namespace project-j7grp because it is being terminated.
2018/04/11 13:34:58 [INFO] Handling backend connection request.
2018/04/11 13:35:33 [INFO] Handling backend connection request.
2018/04/11 13:36:36 [INFO] Handling backend connection request.
2018-04-11 13:37:58.212861 I | mvcc: store.index: compact 21591
2018-04-11 13:37:58.214008 I | mvcc: finished scheduled compaction at 21591 (took 694.774µs)
2018/04/11 13:39:49 [INFO] Handling backend connection request.
``` 

I'm kinda lost. Anyone got any idea how to proceed?

**Comment by StrongMonkey** [comment]
I have made a pr to show better error message when agent failed to register. Can you check if you are still seeing that error message `time="2018-04-11T13:40:09Z" level=info msg="Error while getting agent config: invalid response 500: secrets \"c-cluster-jjqnx\" not found"` in the latest release? This might be related to an improvement fix we recently merged. (https://github.com/rancher/rancher/pull/14567)

**Comment by gwiersma** [comment]
Deployed a new cluster yesterday. I haven't seen any errors.

**Comment by superseb** [comment]
Re-opening to validate the fix in https://github.com/rancher/rancher/pull/15257

**Comment by jiaqiluo** [comment]
Improvement is validated on Rancher:master 1/4
Steps:

- Create a new custom cluster
- Add one worker only node
- copy and paste custom docker run command on the worker node
- agent container starts, check its log

Result:
see the following message in the log:
```
time="2019-01-04T21:32:01Z" level=info msg="waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
```

**Comment by bobycloud** [comment]
I have the same error yet and lost a couple of hours but still no solution.
`waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first`
