### ISSUE TITLE
Port Mapping doesn't change when editted.

### ISSUE THREAD

**Issue by trickytibo** [rancher/rancher#12546]
When I changed port mapping passing from "Every Node" to "LoadBalancer", no changing appears. Random port previously allocated still there and new ones are not.  

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta1` UI: `v2.0.33` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by loganhz** [comment]
This is a backend issue. UI just shows what `publicEndpoints` field has. It should be updated.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/38464512-7e9d17ca-3b41-11e8-9aa6-63bf8a3ee16c.png)

**Comment by zionwu** [comment]
Following logs can be found:
```
2018/04/11 07:02:54 [WARNING] Service [ng/default] already exists but with diff type. Expected type [LoadBalancer], actual type [NodePort]
2018/04/11 07:02:54 [WARNING] Service [ng/default] already exists but with diff type. Expected type [LoadBalancer], actual type [NodePort]

```

**Comment by sangeethah** [comment]
@alena1108 @zionwu , I am still able to reproduce this issue:

Had a custom AWS cluster with provider set to "aws".

Created a workload with  port having - "Every Node" set.
Edited workload and changed it  to - "Load Balancer" (providing source port).
Once the workload gets upgraded , public endpoint still point to the random port that was assigned for every node and no public endpoint for Loadbalancer.


```
"publicEndpoints": [
{
"allNodes": true,
"ingressId": null,
"nodeId": null,
"podId": null,
"port": 32480,
"protocol": "TCP",
"serviceId": null
}
],
```

Container port shows the port updated to "LoadBalancer".

```
"ports": [
{
"containerPort": 80,
"kind": "LoadBalancer",
"name": "tcp80",
"protocol": "TCP",
"sourcePort": 80,
"type": "/v3/project/schemas/containerPort"
}
],
```

**Comment by alena1108** [comment]
@sangeethah can you please file a separate issue for LB not being programmed on GKE. There is some RBAC issue that we have to track separately

**Comment by sangeethah** [comment]
@alena1108 This was tested with AWS provider.

**Comment by sangeethah** [comment]
Will retest with latest build that has the fix.

**Comment by sangeethah** [comment]
Tested with latest build from master.

Created a workload with port having - "Every Node" set.
Edited workload and changed it to - "Load Balancer" (providing source port).
Once the workload gets upgraded , public endpoint  now point to the LB port and it is functional is redirecting traffic to the workload when accessed.
