### ISSUE TITLE
scaleway template form not show

### ISSUE THREAD

**Issue by cheluskin** [rancher/rancher#12544]
I add the scaleway 1.3 driver and when creating template, form was not displayed, where the settings for scaleway are entered. Only label SCALEWAY OPTIONS. If you relogin after installing the driver, then everything is fine
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta1` UI: `v2.0.33` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/38464660-fdb3c926-3b43-11e8-84a6-41d239582d47.png)
Backend sends a `dynamicSchema` update via websocket when we enable a node driver.
The type should be `schema` instead of `dynamicSchema`.

**Comment by tfiduccia** [comment]
I still have to refresh the template page to see the options show up.  This isn't just for scaleway but for all node drivers I install.

**Comment by tfiduccia** [comment]
@loganhz - I still have to refresh browser to see the options.
Steps:
1.  Add Node Driver
2. Download URL - https://github.com/scaleway/docker-machine-driver-scaleway/releases/download/v1.3/docker-machine-driver-scaleway_1.3_linux_amd64.tar.gz
3. Create & Wait for it to be active
4.  Go to Node Templates (not from Cluster page but from under user preferences menu)
5.  Add Template and select Scaleway

Scaleway options don't show up.  If I refresh the browser and get back into Add Template the options are there.

**Comment by loganhz** [comment]
Thanks. I have fixed it in add cluster page. I will fix the add template page today

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/19
Verified fixed
