### ISSUE TITLE
Add local cluster: Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host

### ISSUE THREAD

**Issue by IsNull** [rancher/rancher#12545]
**Rancher versions:**
rancher/server: rancher2-beta-1
rancher/agent: rancher2-beta-1

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): rke 10

**Docker version: **

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 4.726 GiB
Name: node-1
ID: MTS4:IJFT:7Y5N:5SCA:CLR7:B4DI:BNL4:XG44:5KLI:2KQ4:U5DY:KKYR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel:**
Ubuntu 16 (4.4.0-119-generic)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Local VM (proxmox), Baremetal install

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
-

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
-

**Steps to Reproduce:**

The target is to add a local cluster, single node.

1. Start rancher-server on `node-0`
2. In dashboard, Add new Cluster, Type "Custom", v1.10.0
3. Execute the command on another node `node-1`
3. Cluster bootstrap begins...

**Results:**
After a while, the cluster can not be bootstrapped and shows error:
```
Failed to bring up Control Plane: Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [10.7.1.21]. Response code: [403], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/healthz\"","reason":"Forbidden","details":{},"code":403}
```

**Comment by superseb** [comment]
Can you share complete logs of `etcd` and `kube-apiserver`? Were those host re-used between clusters?

**Comment by IsNull** [comment]
>Can you share complete logs of etcd and kube-apiserver? 

I'm happy to bring you any logs I have, but I do not know where to get them from.

> Were those host re-used between clusters?

I have two nodes [node0, node1], both have the same specs (VM with Ubuntu16, Docker 17.03).
I created them with the intent to try out rancher 2.

I always start the `rancher-server:preview` on node0, and the rancher agent on node1.

Between my experiments I always stopped and removed existing docker containers on both nodes. 
So I don't assume there is any state left from rancher / agents.

**Comment by superseb** [comment]
`docker logs --tail=all etcd` and `docker logs --tail=all kube-apiserver` on `node1`.

You can use this script (https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d) to clean a node, it will remove Docker containers and volumes, and all paths that are used to store kubernetes config files/certs, or etcd data.

**Comment by IsNull** [comment]
nice, I will clean node1 and try it again. If it fails again, I will bring the logs.

**Comment by IsNull** [comment]
And it works. 😄 So it was all due to not cleaning up the mounted volumes from previous experiments.

Thank you for the fast response!
