### ISSUE TITLE
Remove the "Untested Docker version" warning on the hosts with docker version 18.03.0-ce

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12559]
**Rancher versions:**
rancher/server: master

1. Create a setup with docker version 18.03.0-ce
The hosts come up with warning "Untested Docker version"

This docker version has been tested and the warning label can be removed

**Comment by loganhz** [comment]
We need to change `supported.docker.range` and `newest.docker.version` in backend.
https://github.com/rancher/cattle/blob/v1.6/code/packaging/app-config/src/main/resources/META-INF/cattle/api-server/defaults.properties#L103-L104

**Comment by loganhz** [comment]
@soumyalj Do we support `18.01.0-ce` and `18.02.0-ce` in 1.6?

**Comment by soumyalj** [comment]
Tested with rancher v1.6.17-rc2 using Docker 18.03. Warning label " Untested Docker version " has been removed.
<img width="282" alt="screen shot 2018-04-10 at 4 04 01 pm" src="https://user-images.githubusercontent.com/18536626/38588153-30bafefc-3cd9-11e8-8bd1-77a0d24b5cbf.png">
