### ISSUE TITLE
AD Auth: Unable to login as user with special characters in name.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12553]
Steps:
Setup AD auth with users that contain special characters in their name.

EX:
Special character in username:
test(san)&abc: Password1

Attempt to login as user with characters in name.

Results:
"Server error while authenticating"
![screen shot 2018-04-06 at 9 17 53 am](https://user-images.githubusercontent.com/38012481/38432149-695c489e-397b-11e8-9e56-743784e388cc.png)

**Comment by kinarashah** [comment]
The linked issue wasn't exactly a duplicate and was closed by the user, opening this for testing purpose.

**Comment by adingilloRancher** [comment]
Verified Fix.

Master build 4/13/2018
