### ISSUE TITLE
Error 500 when loading the community catalog or upgrading a stack

### ISSUE THREAD

**Issue by damienfa** [rancher/rancher#12561]
**Rancher versions:**
Rancher | v1.6.14
Cattle | v0.183.37
User Interface | v1.6.37
Rancher CLI | v0.6.7
Rancher Compose | v0.12.5

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:
network-services: ???
scheduler: :v0.8.3
**Docker version:** v17.06.2-ce

**Operating system and kernel:** RancherOS v1.1.3 , 4.9.75-rancher

**Type/provider of hosts:** Linode 

**Setup details:** single node rancher, internal DB

**Environment Template:** Cattle

**Steps to Reproduce:**
When I go to "Catalog > Community" or "Catalog > all", I've got an error 500 (see screenshot)
It doesn't happen when I go to "Catalog > MyPrivateCatalog" or "Catalog > Library"
`http://<my-rancher-ui-domain>/v1-catalog/templates?category_ne=system&rancherVersion=v1.6.14`

It also happens when I try to click on "up-to-date" on a specific stack (but the ajax call that fails is the same).

**Results:**

I've got a nice error 500 on the UI.
![image](https://user-images.githubusercontent.com/3252640/38457194-8350db30-3a8d-11e8-97db-02617efe8cc4.png)

And from API (/v1-catalog/templates?category_ne=system&rancherVersion=v1.6.14),
I've got : 
```
{
"id": "3681{...}454",
"type": "error",
"links": { },
"actions": { },
"status": 500,
"code": "Internal Server Error",
"message": "Internal Server Error",
"detail": null,
"baseType": "error"
}
```

**Comment by damienfa** [comment]
Mhh. the problem has just disappeared once I reboot the server...

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
It will be great if you can upload the server log
