### ISSUE TITLE
Project scoped secret/certificates/registries continues to be present in the namespace after it has been moved to a different project. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12568]
**Rancher versions: Latest build from master
**Steps to Reproduce:**
Create a cluster with project -"test1" with namespaces  "hello1" and "hello2".
Create project scoped secret/certificates/registries.

Using kubectl , able to see all the above created project scoped resources as secrets.

Move "hello2" namespace to a different project.

Using kubectl ,  we are still able to see all the above created project scoped resources as secrets.

Expected behavior:
Since "hello2" is not part of the project - "test1" anymore , this namespace should not have access to any of the above created secrets.

**Comment by kinarashah** [comment]
Not only are the secrets still available in the old project, secrets specific to that namespace don't get the updated projectID.

**Comment by sangeethah** [comment]
Tested with v2.0.0-beta4-rc1

Existing project scoped secret/certificates/registries are not present in the namespace after it has been moved to a different project.

If the new project it is moved to has   project scoped secret/certificates/registries , the namespace now has these secrets.
