### ISSUE TITLE
Not able to launch kubectl shell (from ui) as cluster member/project owner/project member/read only user.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12569]
**Rancher versions: Build from master  

**Steps to Reproduce:**

Create a cluster with few projects p1 and p2.
Create standard users  - test1 , test2.

Assign test1 as project owner of p1.
Assign test2 as project member of p2.

When logged in as user test1 or test2 , Not able to launch kubectl.

It hangs in "connecting" state.

**Comment by deniseschannon** [comment]
From https://github.com/rancher/rancher/issues/12746 : 

 As cluster member/ project member/ project owner/read only user  , user is  not able to launch kubectl shell.

**Comment by cjellick** [comment]
Also, completely broke for "local" cluster, which we might want a separate issue for. This would be "local" cluster you get when deploying in HA mode

**Comment by sangeethah** [comment]
Tested with latest build from master:
As cluster member/ project member/ project owner/read only user , user is able to launch kubectl shell.

kubectl shell issue for local cluster is tracked in https://github.com/rancher/rancher/issues/12838
