### ISSUE TITLE
rancher ruby gem

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#1256]
Hello,

I'm wondering if building out a rancher gem to consume the API much the way that rancher-compose works has ever been discussed?  I'm working on a ruby app and it would need to talk with a rancher server and instead if going to comand line or run rancher compose, it would be cool to have a gem.

just an idea i have.

**Comment by deniseschannon** [comment]
There hasn't been any discussion on this, but seems like a neat idea. If enough users request it, we could add it to the roadmap.

**Comment by akurkin** [comment]
hey @deniseschannon and @jwhitcraft checkout https://github.com/akurkin/rancher-api - I've built some basic functionality that I use, which include:
- i.e. creating new machine via rancher api with digital ocean provider
- executing remote shell commands (i.e. for running rake tasks/migrations remotely)
- some basic querying of instances / machines / services

Of course there're still lots of improvements to be made, but I use it and it worked quite well so far

**Comment by jwhitcraft** [comment]
@akurkin, Awesome, I'll check it out and if i need anything, i'll issue some PR's

**Comment by jwhitcraft** [comment]
@deniseschannon and @akurkin,

After trying to hack on akurkin/rancher-api , I found it to be limiting in what it could do since rancher doesn't return json in a format that that [her](http://her-rb.org) is expecting.

So started this gem over the weekend, https://github.com/jwhitcraft/rancher.rb which is done in the same style as github did their Octokit.rb gem.

It's still very much a work in progress.

**Comment by akurkin** [comment]
@jwhitcraft what endpoint are you referring to?

**Comment by jwhitcraft** [comment]
@akurkin, I am trying to work with loadBalancers and their configs.

**Comment by will-chan** [comment]
Closing this as there hasn't been any activity on this.  It is also something that we would welcome as a separate project outside of Rancher.

**Comment by jwhitcraft** [comment]
@will-chan, i've already got one kinda started that is linked above.
