### ISSUE TITLE
Can't unassign a namespace from a project

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#12564]
**Rancher versions:**
rancher/server: 4/8-master
rancher/agent: n/a

**Steps to Reproduce:**
1. Deploy k8s cluster in Rancher with DO cluster
2. create a namespace and assign to a project
3. move the new namespace out of the project and assign to `none` project

**Results:**
Don't have any error message for it but the operation fails.

**Comment by gtirloni** [comment]
Reproduced on Rancher v2.0.0-beta4-rc2

**Comment by soumyalj** [comment]
Tested with rancher version v2.0.0-rc3. Moving the namespace out of the project and assigning to none project is functional. 

Issue related to this feature is tracked here https://github.com/rancher/rancher/issues/13193
