### ISSUE TITLE
Feature Request: Ability to choose Træfik as a default k8s ingress

### ISSUE THREAD

**Issue by gaui** [rancher/rancher#12563]
**Rancher versions:**
rancher/server: 2.0

Træfik is great and provides multiple backends (also Kubernetes). It would be awesome if you could be able to choose Træfik as a k8s ingress in Rancher 2.0, instead of the default one, so people can continue to use Træfik. We are running a seperate Docker Swarm utilising Træfik as our LB and service mesh and would love to keep using it - until we migrate everything to Rancher + k8s.

https://traefik.io

**Comment by gaui** [comment]
Would also be cool to consider to support https://istio.io too.

**Comment by LinAnt** [comment]
Istio recently received its first LTS release (0.8.0). 1.0.0 is expected later this year.

**Comment by brianmori** [comment]
Hi, for info Istio 1.0.0 has been released yesterday.
I am trying to setup it

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/14007
