### ISSUE TITLE
Management User Namespace Doesn't Be Cleaned After User Deleted

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#12576]
Step to reproduce

1. create a new user
2. login new user
3. ```docker exec``` into rancher server container and run ```kubectl get ns``` and set the new user namespace
4. login admin
5. delete user
6. check ```kubectl get ns``` again and see user namespace again

excepted result
related user namespace should be deleted after user has been deleted

**Comment by sangeethah** [comment]
Tested latest build from master:

created a new user and assigned the user to as a member to existing cluster
login as new user
docker exec into rancher server container and run kubectl get ns. There is a new namespace that is created for the user.

Delete user.
After user gets deleted , namespace associated with this user is deleted from the Management cluster.
