### ISSUE TITLE
Rancher 2.0 beta add node two times

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#12577]
**Rancher versions:**
rancher/server:  2.0.0-beta2
rancher/agent:  2.0.0-beta2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

v1.9.5-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)**

 17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 16.04.3 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

Add a host with multiple card ,the nodes panel shows two nodes with the same name ,one is active,and another is registering. the two same nodes show the same ip.

**Results:**

**Comment by dnauck** [comment]
I had this issue with 2.0 alpha24 when the node hostname had some upper case letters, e.g. `ClusterNode-1`.

Then the Rancher 2 UI shows, after adding this node, two new nodes:

- `ClusterNode-1` - not reachable
- `clusternode-1` - ok

**Comment by yoke88** [comment]
the problem node name of mine is LabManager.

发件人: Daniel Nauck
发送时间: 4月10日星期二 15:00
主题: Re: [rancher/rancher] Rancher 2.0 beta add node two times (#12577)
收件人: rancher/rancher
抄送: yoke88, Author


I had this issue with 2.0 alpha24 when the node hostname had some upper case letters, e.g. ClusterNode-1.
Then the Rancher 2 UI shows, after adding this node, two new nodes:
ClusterNode-1 - not reachable clusternode-1 - ok
―

**Comment by superseb** [comment]
@dnauck That is tracked in https://github.com/rancher/rancher/issues/12499.

**Comment by superseb** [comment]
@yoke88 Can you share a screenshot of the `Nodes` view?

**Comment by yoke88** [comment]
i do not known why i can not upload pictures, i tried multie times ,but not success, i will try again
________________________________

**Comment by aiwantaozi** [comment]
@yoke88 about showing two nodes, add custom node and run command two times, but reproduce failed. Could you tell how we can reproduce it?

**Comment by superseb** [comment]
@ts-mini Different issue, I think that is covered by https://github.com/rancher/rancher/issues/12594

**Comment by yoke88** [comment]
[?像]

i  do not known how to reproduce it ,but i encounter this problem in beta1 and beta2 ,each time i will destroy the whole env by delete all dockers . and reregister the hosts.

ceph1 has two net card, 192.168.235.x and 10.0.1.x, LabManager1 has two network card 192.168.235.x and 172.18.1.10, LabManager1 act as a router
________________________________

**Comment by aiwantaozi** [comment]
@yoke88 thanks for your report, we will fix it ASAP.

**Comment by soumyalj** [comment]
Tested with master from April 18. Created clusters using AWS and DO cloud provider/custom nodes with uppercase and combination of uppercase and lowercase letters. The nodes were added successfully and did not get added twice. Workload creation on the clusters worked ok.
