### ISSUE TITLE
Kubelet restarts constantly on RHEL 7.3 and RHEL 7.4 set ups with Docker 1.12.6 and Kubernetes v1.10.0-rancher1-1

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12587]
**Rancher versions:**
rancher/server: v1.6.17-rc1

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** RHEL 7.3 and 7.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes v1.10.0

**Steps to Reproduce:**
1. Create a Kubernetes setup on RHEL7.3 or RHEL 7.4
2. Kubelet restarts constantly and fails to go to running state

Kubernetes infra stack is in degraded state.

**Comment by moelsayed** [comment]
Kubelet crashes with the error:
```
F0410 00:21:33.501593   28895 kubelet.go:1339] Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory
```
Issue seems specific to docker 1.12.x. We have seen it several times: #6181, #7252. I am not sure why exactly it's regressing. 

The original problem is related to kubelet's built in cadvisor. The upstream cadivsor seems to have changed inotify library several times causing this. More details are in these issue:
https://github.com/google/cadvisor/issues/1461
https://github.com/kubernetes/kubernetes/issues/32728
https://github.com/google/cadvisor/issues/1890
https://github.com/google/cadvisor/issues/1708


 #144 provides the advised work around needed to avoid this until upstream is fixed.

**Comment by moelsayed** [comment]
Docker version `1.13` and `17.03` are also affected.

**Comment by soumyalj** [comment]
Tested with rancher v1.6.17-rc2
1. Create a Kubernetes setup on RHEL7.3 or RHEL 7.4 
Kubelet came up successfully. Kubernetes infra stack was active
