### ISSUE TITLE
UI: tls secret using wildcard certificate causes Javascript errors (UI hangs)

### ISSUE THREAD

**Issue by tkuther** [rancher/rancher#12584]
**Rancher versions:**
rancher/server: 2.0.0-beta2
rancher/agent: 2.0.0-beta2

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes 1.10-rancher-1

**Steps to Reproduce:**
1. `kubectl create secret tls ...` with a wildcard certificate
2. Try to list certificates in Project -> Resources -> Certificates

**Results:**
Javascript error:
```
Uncaught TypeError: Cannot read property 'substr' of undefined
    at a.<anonymous> (certificate.js:83)
    at fe.Wt.get (ember-metal.js:2904)
    at te (ember-metal.js:2270)
    at n.compute (references.js:162)
    at n.value (references.js:38)
    at t.e.value (runtime.js:228)
    at e.initialize (reference.js:369)
    at e.peek (reference.js:343)
    at runtime.js:934
    at e.evaluate (runtime.js:73)
```
UI "hangs"

The certificate has `Subject: CN=*.kube.domain.com`. It's from letsencrypt.

**Comment by vincent99** [comment]
Changed the UI to not explode, but I think the `cn` field is still going to be empty and should be fixed in the API.

**Comment by vincent99** [comment]
@tkuther Do you mind posting the certificate that caused this (just the public part); Other wildcard certs seem to be fine and that will save me the effort of getting a Let'sEncrypt wildcard to see if it's related to that.

**Comment by tkuther** [comment]
@vincent99 No problem, if it helps.
[cert1.txt](https://github.com/rancher/rancher/files/1893435/cert1.txt)

I'll try with one of our GlobalSign wildcards.

**Comment by tfiduccia** [comment]
Version - v2.0.0-beta4-rc4
Verified fixed
