### ISSUE TITLE
Local node path volume doesn't work

### ISSUE THREAD

**Issue by benyanke** [rancher/rancher#12585]
Running the latest server beta on ubuntu hosts, using the node clients specified by the GUI.

The three workers are Ubuntu guests on a KVM box. For simplicity sake, I have a mount on all three VMs to the same directory on the KVM host, allowing all three nodes to share files in a specific directory. The effect is more-or-less identical to an NFS mount on all nodes in a bigger environment.

However, when adding a persistent volume, I receive the following error:

```
Validation failed in API: PersistentVolume "shared-vol" is invalid: spec.hostPath.type: Unsupported value: "hostPathVolumeSource": supported values: , BlockDevice, CharDevice, Directory, DirectoryOrCreate, File, FileOrCreate, Socket
```

Configuration is below in screenshot:
![image](https://user-images.githubusercontent.com/4274911/38509975-237f2718-3be9-11e8-96f4-f98b01ce1258.png)

**Comment by deniseschannon** [comment]
@zionwu This looks like a duplicate of https://github.com/rancher/rancher/issues/12410?

**Comment by benyanke** [comment]
That is correct
