### ISSUE TITLE
[Azure] vnet in another resource group

### ISSUE THREAD

**Issue by Coopyrightdmin** [rancher/rancher#12582]
Dears,

I am trying to generate hosts in Azure that refer to an existing vnet.
1) When this vnet is part of the resource group A where I create some vms, everything runs fine.
2) When the vnet is part of another resource group B which the Application Id has been authorized to, then a new vnet is created within the resource group A instead of using the existing one from resource group B.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.16` Cattle: `v0.183.46` UI: `v1.6.42` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Comment by bigredthelogger** [comment]
I noticed the same result.

**Comment by superseb** [comment]
This should work by prefixing the resource group name in front of the configured vnet like `myrg:myvnet`.
