### ISSUE TITLE
Add support for adding arbitrary groups via the UI

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#12597]
1.6.14 +

Currently, there is no way to add arbitrary groups (groups that the currently logged in user is not a part of) to Rancher from the UI while using SAML access controls. Rancher will see the arbitrary group as a user. This feature will need API parity, and should support the full DN when adding groups. 

*  Expected behavior: Adding a arbitrary Active Directory group to an environment's Access Control list from the UI results in a group being added that gives all of the members of that group access to an environment
*  Actual behavior: Adding a arbitrary Active Directory group to an environment's Access Control list from the UI results in the __group__ being interpreted __as a user__

This functionality should work in all places where a user can be authorized for an environment, namely:

*  The access control page for an individual environment
*  The admin access control page

Validation of LDAP groups is not required for our use case, as the SAML assertion must be used for the group information.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
