### ISSUE TITLE
Git Auth - Local user has access to cluster when removed from project.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12595]
Steps:
Add Git Auth
Create local user accounts.
Set access to "Allow members of Clusters, Projects, plus Authorized Users and Organizations"
Assign local user to a project (I added them as a member). 
Remove local user to project.

Results:
Local user is still able to login and view cluster/project after being removed.

**Comment by deniseschannon** [comment]
Local users are separate from Github and will still have access, where we need changes in the UI to describe what "Restricted" mode looks like. 

I think it falls under this umbrella: 
https://github.com/rancher/rancher/issues/12031

**Comment by adingilloRancher** [comment]
Not a bug, local user had full admin access.
