### ISSUE TITLE
Fix nodeSyncer to sync the node by nodeAddress if can't be found by name

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12594]
When AWS is passed as cloudProvider to k8s cluster start, hostnameOverride is not respected. Rancher relying on node.name == hostname, breaks node sync logic. We should search by externalIp/internalIP if node can't be located by its name

**Comment by sangeethah** [comment]
Able to add cluster with cloud provider set to AWS.
We have 1 issues where extra worker nodes show up in the cluster which is tracked in https://github.com/rancher/rancher/issues/12702
