### ISSUE TITLE
Improve on-screen documentation for configuring vSphere clusters

### ISSUE THREAD

**Issue by jbalonso** [rancher/rancher#12591]
**Rancher versions:**
rancher/server: preview `8b58d90842b4`

**Details**

I pitched in on a Slack question here: https://rancher-users.slack.com/archives/C3ASABBD1/p1523298091000576, but I've found it challenging to use the vSphere cluster type from the scant documentation available online.

In particular, it would help if "host" was explained as `$clusterName/$hostName` and "data store" was explained as `$dataStoreClusterName/$dataStoreName` (ok, this camel-case pseudo-notation is wretched, so use judgment).

I understand that `docker-machine` is running under the hood, but iterating to discover the above was time-consuming and shouldn't be an oral tradition. I'm not a vSphere guru (it's not our primary infrastructure), so it's possible that our vSphere config doesn't have clean defaults, but the "'/' for cluster" help text doesn't... help.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/18
Verified fixed
