### ISSUE TITLE
The command console of a pod can not be open

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#12604]
*when open command console of a pod , the ui hang and no response,and we can see errors in chrome developer console like this:*

``` text
Uncaught Error: The intl string context variable 'instanceName' was not provided to the string '命令行‘{instanceName}’
```
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta2` UI: `v2.0.34` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by vincent99** [comment]
This sounds like a translation key that's outdated.. in the meantime you can switch to English and it should work.

**Comment by yoke88** [comment]
yes ,changed language to english ,it works .
________________________________

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/ui/pull/1824

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/23
Verified fixed
