### ISSUE TITLE
Feature request: Be able to close log viewer with Esc key

### ISSUE THREAD

**Issue by perlun** [rancher/rancher#12607]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: rancher/agent:v1.2.9

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.7.19
scheduler: rancher/scheduler:v0.8.3
kubernetes (if applicable): Not applicable

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal, hosted on AWS.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher w/ external DB.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle.

**Steps to Reproduce:**
Open the log viewer for a container.

**Results:**
The log view opens. But, you must press the Close button with the mouse to close it. It feels like it untuitively "should" work to press Esc to close the log viewer. What do you think? If you point me at the right file in the web UI, I might be able to submit a PR.

Thanks for a great tool! 👍 👍 👍

**Comment by superseb** [comment]
I can see this working for most of the popups we use (logs/shell/kubectl/kubeconfig). Just not sure if this can be implemented cleanly. The UI code lives in https://github.com/rancher/ui, branch `1.6-dev` for 1.6

**Comment by vincent99** [comment]
Logs yes, shell no (you need the escape key)

**Comment by perlun** [comment]
Agree @vincent99, but the shell can already be closed by Ctrl-D so that's easy. 😉

**Comment by perlun** [comment]
@deniseschannon Will this go into 2.0 only, not 1.6?

**Comment by deniseschannon** [comment]
@perlun yes, currently only in 2.0.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
