### ISSUE TITLE
No transitioning state when workloads are getting upgraded.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12602]
**Rancher versions: Build from master
**Steps to Reproduce:**
Create a cluster.
Create a workload.
Upgrade workload using any of the 1 options:
Add a sidekick.
Edit workload and change image name.

When upgrade is in progress , workload state continues to be in "active" state.

There should be transitioning state that indicates that upgrade is in progress.

**Comment by sangeethah** [comment]
Tested with latest build from master:

We see the workload state get to "updating" state from upgrade is in progress. Once done it gets to "active" state.

@kinarashah workload gets to "active" state as soon as the new pods get created. They do not wait for the older pods to get removed. Do we want to be in "updating" state until the older pods get removed too ?

**Comment by kinarashah** [comment]
@sangeethah yes, I think so - it stays in `updating` state till all its pods are in ready state. Deleting previous ones should not affect the running workload, right?

**Comment by alena1108** [comment]
@sangeethah it should go to active after the upgraded pods are ready. Cleanup part has no affect on the RC state - that's the default k8s behavior. Closing the issue.
