### ISSUE TITLE
Failed to validate cluster: Cluster can't have duplicate node: 10.0.2.15

### ISSUE THREAD

**Issue by jossion12** [rancher/rancher#12605]
**Rancher versions:**
rancher/server:Release v2.0.0-beta2
rancher/agent:Release v2.0.0-beta2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):V1.8.10-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 53
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 197
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.765 GiB
Name: rancher-node5
ID: ZVRD:PD46:3TUE:6XXB:3DN4:MUBO:RPNJ:TMD7:GVMM:OOCP:YCS6:CA4L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://ee31c587.m.daocloud.io
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-119-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
one rancher server , two rancher agent

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. I use vagrant start up 3 node, echo have 4G memory
2. Start server
    sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:v2.0.0-beta2
3. Use default to start cluster, use kubernetes 1.8, add 2 nodes.
4. after download the image , the UI show 
"This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Failed to validate cluster: Cluster can't have duplicate node: 10.0.2.15"

**Results:**
after setup the cluster in local vagrant environment , the ui show 
"Failed to validate cluster: Cluster can't have duplicate node: 10.0.2.15"

**Comment by reidlai** [comment]
+1

**Comment by carcinoma** [comment]
+1

**Comment by alogoc** [comment]
+1

**Comment by superseb** [comment]
Vagrant adds a NAT adapter with the same IP which is autodetected and causes conflicts. You can add a host and add `--address ip_of_eth1` and `--internal-address ip_of_eth1`. You can't make it work with just the NAT adapter as it can't be used to unique identify the node.

**Comment by ccimpoi** [comment]
You need to add --address 192.168.99.100 --internal-address 192.168.99.100 to the docker run command that initiates the node. Rancher 2.0 (PRD ready) has this option in the UI.

**Comment by jossion12** [comment]
@ccimpoi @superseb ,sorry for reply later, i try as your suggest, the UI show below:"Failed to apply the ServiceAccount needed for job execution: Post https://192.168.53.7:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: x509: certificate is valid for 10.0.2.15, 127.0.0.1, 10.43.0.1, not 192.168.53.7"

**Comment by jossion12** [comment]
@ccimpoi @superseb ,sorry for reply later, i try as your suggest, the UI show below:"Failed to apply the ServiceAccount needed for job execution: Post https://192.168.53.7:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: x509: certificate is valid for 10.0.2.15, 127.0.0.1, 10.43.0.1, not 192.168.53.7"

**Comment by kirek007** [comment]
+1, I faced exactly same issue. 
By default node will use IP of first adapter. I solved it using `--address` and `--internal-address` parameters. 
But it looks that part of script that creating certificates ignoring those parameters.

**Comment by Dock1100** [comment]
+1

**Comment by Rednjak** [comment]
+1. Did somebody find a solution for this issue?

**Comment by loganhz** [comment]
Can you try to run the clean up script on agent node https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d

And try to add it again with `--address ip_of_eth1` and `--internal-address ip_of_eth1`

**Comment by Sheshagiri** [comment]
@loganhz after running the cleanup script. I don't see the issue. 👍

**Comment by loganhz** [comment]
Thanks for the update! 

Please let us know in a comment if you can still reproduce the issue after trying  https://github.com/rancher/rancher/issues/12605#issuecomment-432983240 , and we'll reopen it

**Comment by suikast42** [comment]
> Facing the same issue: x509: certificate is valid for 10.0.2.15, 127.0.0.1, 10.43.0.1, not 192.168.53.7

Me too with the latest stable build today

**Comment by suikast42** [comment]
> x509: certificate is valid for 10.0.2.15, 127.0.0.1, 10.43.0.1

It works after droping the virtualbox image and recreate it. ;-)
