### ISSUE TITLE
Unable to upgrade from rancher server 1.6.14 to 1.6.16 / liquibase Change Set db/core-124.xml::dump1::kinara (generated) failed

### ISSUE THREAD

**Issue by typia** [rancher/rancher#12606]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.29

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.7
network-services: v0.9.5 / v0.7.19
scheduler: v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 18.03.0-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian 8 Jessie / 3.16.0-4-amd64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware VM
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I tried to upgrade rancher server from 1.6.14 to 1.6.16, logs for rancher server container was stuck on migrating DB for more than 30 minutes.
I tried to stop rancher server et launch it again and now rancher server keeps restarting.
Rollback to 1.6.14 works
**Results:**
Rancher server 1.6.16 (and 1.6.15) keeps restarting / logs attached 
[rancher-error-log.txt](https://github.com/rancher/rancher/files/1893827/rancher-error-log.txt)

**Comment by noogen** [comment]
Not sure if related but 1.6.16 doesn't seem to list 18.03 docker as supported version (it stop at 17.12).

**Comment by superseb** [comment]
To be clear, the error in the log is when you started the old `rancher/server` container again? Not when you started the upgraded container?

**Comment by typia** [comment]
Nope, it's when I start the upgraded.
I can start it in 1.4 but not after.
Here's my script to launch rancher : 

```
docker stop rancher-server && docker stop nginx-rancher
docker rm rancher-server && docker rm nginx-rancher
docker pull rancher/server:stable


docker run -d --restart=always --name rancher-server \
-v /etc/localtime:/etc/localtime \
rancher/server:v1.6.14 \
--db-host xxx.xxx.xxx.xxx --db-port 3306 --db-user rancher --db-pass pass --db-name rancher \

docker run -d --restart=always -p 80:80 -p 443:443 --name nginx-rancher \
-v /home/noveladmin/nginx_rancher/conf_nginx:/etc/nginx/conf.d \
-v /home/noveladmin/nginx_rancher/certs:/etc/ssl/certs \
--link rancher-server \
nginx:latest
```

**Comment by superseb** [comment]
When you rollback to 1.6.14, did you also rollback the database to how it was in 1.6.14?

**Comment by typia** [comment]
Unfortunately not.
I was not able to restore it entirely.
I only restored tables DATABASECHANGELOG and DATABASECHANGELOGLOCK

DATABASECHANGELOG
--




DATABASECHANGELOG
--

**Comment by typia** [comment]
Ok,
I tried to export a backup from my database, but it's 13 Gigs !
What can I truncate to reduce it ?

**Comment by typia** [comment]
Ok, manage to revert to a snapshot with the old database but now when I try to upgrade it's stuck on Starting DB migration for about 10 minutes now..

**Comment by superseb** [comment]
Such a large DB can take a while, we implemented fixes to bring down the DB size in v1.6.16. Can you check what queries are being run in the query log or using `SHOW FULL PROCESSLIST;` ?

**Comment by typia** [comment]
Hi @superseb 
Thanks for your help.
I tried again to upgrade to 1.6.16

First I restored my db to snapshot from 1.6.14 then started rancher 1.6.16
As you said, I saw my db reduced drastically going from 13Gb to 2Gb but it crashed when trying to maintain audit_log table ([rancher.log](https://github.com/rancher/rancher/files/1931998/rancher.log))


I truncated audit_log and 1.6 managed to start but then crashed again ([rancher-2.log](https://github.com/rancher/rancher/files/1931997/rancher-2.log))

I don't know how to fix at this point


Thanks

**Comment by superseb** [comment]
Those error seem to indicate short timeout settings on the DB, or generally load on the DB causing queries not to finish in time. What are the timeouts configured on the DB, and what are hosts specs for the DB and the host running rancher/server?

**Comment by typia** [comment]
Both Hosts are VMs, Debian 8.10 hosts 
DB host has 4vcpu and 8Gb Ram It runs mariaDB directly (was from a container first)
Here's the [my.cnf](https://github.com/rancher/rancher/files/1932162/my.cnf.txt) for the DB server

Rancher Server has 2vcpu and 2Gb Ram 

Let me know if you need any other information and thanks again

**Comment by typia** [comment]
hi @superseb sorry to bother you with that issue.
Are the timeout settings too low ? Those are the default ones.
Many thanks

**Comment by typia** [comment]
Hi guys,
a little update.
It has nothing to with timeouts, there are corrupted data on my db.
Anytime I try to dump, either with phpmyadmin or mysqldump, it crashes at the same line in audit_log, giving  27MB file.
I tried to truncate audit_the try again and now it give 2.7Gigs file but crashes in a line in instance_table.

I suspect there will be a few others.

Please, could you tell me which tables are safe to truncate ?

Many thanks

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
