### ISSUE TITLE
Deploy workload volumes not working

### ISSUE THREAD

**Issue by marufbd** [rancher/rancher#12601]
**Rancher versions:**
rancher/server: v2.0.0-beta2

I've a persistent volume and claim already created and bound in my cluster.

Trying to deploy a simple nginx container workload, but through the ui under volumes drop down does nothing.

So i am using the api to add the volume which gives me this error:

**HTTP Request**
`HTTP/1.1 PUT /v3/project/cluster-sgr7s:project-22ztw/workloads/deployment:default:nginx
Host: cmd.bd-cast.com
Accept: application/json
Content-Type: application/json
Content-Length: 2795

{
"annotations": { },
"containers": [
{
"allowPrivilegeEscalation": false,
"image": "nginx",
"imagePullPolicy": "Always",
"initContainer": false,
"name": "nginx",
"ports": [
{
"containerPort": 80,
"kind": "HostPort",
"name": "tcp80",
"protocol": "TCP",
"sourcePort": 8080,
"type": "/v3/project/schemas/containerPort"
}
],
"privileged": false,
"readOnly": false,
"resources": {
"limits": {
"cpu": "0",
"memory": "0",
"nvidia.com/gpu": "0"
},
"requests": {
"nvidia.com/gpu": "0"
},
"type": "/v3/project/schemas/resourceRequirements"
},
"runAsNonRoot": false,
"stdin": true,
"stdinOnce": false,
"terminationMessagePath": "/dev/termination-log",
"terminationMessagePolicy": "File",
"tty": true,
"type": "/v3/project/schemas/container"
}
],
"created": "2018-04-10T00:01:25Z",
"creatorId": null,
"deploymentConfig": {
"maxSurge": 1,
"maxUnavailable": 0,
"minReadySeconds": 0,
"progressDeadlineSeconds": 600,
"revisionHistoryLimit": 10
},
"deploymentStatus": {
"availableReplicas": 1,
"conditions": [ 2 items
{
"lastTransitionTime": "2018-04-10T00:01:29Z",
"lastTransitionTimeTS": 1523318489000,
"lastUpdateTime": "2018-04-10T00:01:29Z",
"lastUpdateTimeTS": 1523318489000,
"message": "Deployment has minimum availability.",
"reason": "MinimumReplicasAvailable",
"status": "True",
"type": "Available"
},
{
"lastTransitionTime": "2018-04-10T00:01:25Z",
"lastTransitionTimeTS": 1523318485000,
"lastUpdateTime": "2018-04-10T00:01:29Z",
"lastUpdateTimeTS": 1523318489000,
"message": "ReplicaSet \"nginx-677b5949d4\" has successfully progressed.",
"reason": "NewReplicaSetAvailable",
"status": "True",
"type": "Progressing"
}
],
"observedGeneration": 2,
"readyReplicas": 1,
"replicas": 1,
"type": "/v3/project/schemas/deploymentStatus",
"unavailableReplicas": 0,
"updatedReplicas": 1
},
"dnsPolicy": "ClusterFirst",
"gids": [ ],
"hostAliases": [ ],
"hostIPC": false,
"hostNetwork": false,
"hostPID": false,
"imagePullSecrets": [
{
"name": "dockerhub-kaisho",
"type": "/v3/project/schemas/localObjectReference"
}
],
"labels": {
"workload.user.cattle.io/workloadselector": "deployment-default-nginx"
},
"name": "nginx",
"namespaceId": "default",
"nodeId": "",
"ownerReferences": [ ],
"paused": false,
"projectId": "cluster-sgr7s:project-22ztw",
"publicEndpoints": [ ],
"restartPolicy": "Always",
"scale": 1,
"schedulerName": "default-scheduler",
"scheduling": {
"node": {
"nodeId": null,
"requireAll": [
"kubernetes.io/hostname = k8s-cdn-edge-fra1"
]
}
},
"selector": {
"matchLabels": {
"workload.user.cattle.io/workloadselector": "deployment-default-nginx"
},
"type": "/v3/project/schemas/labelSelector"
},
"state": "active",
"terminationGracePeriodSeconds": 30,
"transitioning": "no",
"transitioningMessage": "",
"uuid": "4f5d0f3c-3c52-11e8-ade0-3e0953a5a53e",
"volumes": [
{
"name": "task-pv-storage",
"persistentVolumeClaim": {
"claimName": "pvc-nginx"
}
}
],
"workloadAnnotations": {
"deployment.kubernetes.io/revision": "1",
"field.cattle.io/creatorId": "user-n5vgz"
},
"workloadLabels": {
"workload.user.cattle.io/workloadselector": "deployment-default-nginx"
}
}`

**HTTP Response**
`HTTP/1.1 422
date: Tue, 10 Apr 2018 00:04:11 GMT
x-api-schemas: https://cmd.bd-cast.com/v3/project/cluster-sgr7s:project-22ztw/schemas
content-type: application/json
content-length: 218
expires: Wed 24 Feb 1982 18:42:00 GMT

{
"actions": { },
"baseType": "error",
"code": "Invalid",
"links": { },
"message": "Deployment.apps \"nginx\" is invalid: spec.template.spec.volumes[0].persistentVolumeClaim.claimName: Required value",
"status": 422,
"type": "error"
}`

Although this simple pod yaml works with kubectl:
```
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pvc-nginx
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
  nodeSelector:
    kubernetes.io/hostname: k8s-cdn-edge-fra1
```

**Comment by marufbd** [comment]
Figured out the volumes dropdown menu works in microsoft edge but not in chrome.

**Comment by mloc** [comment]
This is still an issue surely, if it doesn't work in Chrome?

**Comment by yelizariev** [comment]
I have the similar: I click *Add Volume*, it shows *drop down* menu. When any of the shown options nothing happens
