### ISSUE TITLE
[suggestion] make a better web terminal experience

### ISSUE THREAD

**Issue by corn13read** [rancher/rancher#1260]
I just did the demo for flocker with their web terminal and it's amazing(the terminal), I believe they're using Guacamole https://github.com/glyptodon/

It looks and feels like a legitimate terminal.

![screenshot56](https://cloud.githubusercontent.com/assets/11197133/8215669/61b856a8-14e6-11e5-8e37-7874aa27596b.png)

![screenshot57](https://cloud.githubusercontent.com/assets/11197133/8215668/61b7cbc0-14e6-11e5-82d8-bcb32c9d9be0.png)

**Comment by jas99** [comment]
@deniseschannon Hi thr any update on this;

And it will be great if we can login directly in host also in addition to containers.

Jas99

**Comment by vincent99** [comment]
The interface available to communicate with is a TTY.. A graphical VNC/RDP project like Giacamole doesn't make any sense here, it's for communicating with the graphical console of a host, like we do with VM support (but with NoVNC).
