### ISSUE TITLE
Shibboleth (Ping Federator) - Display name not shown for current user in Edit environment view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12617]
**Rancher versions:** 1.6.17-rc2

**Steps to Reproduce:**
Enable Shibboleth (Ping Federator)  auth.
As admin user , log in to the server.
Go to edit environment page and notice that Display name not shown for current user  in the access control list.

<img width="1297" alt="screen shot 2018-04-10 at 2 00 02 pm" src="https://user-images.githubusercontent.com/4266958/38583326-7ee21438-3cc7-11e8-8d36-40b957ea3b64.png">

Note: It is seen for other members added to the list.

**Comment by mrajashree** [comment]
<img width="1394" alt="screen shot 2018-04-10 at 10 41 11 pm" src="https://user-images.githubusercontent.com/10672776/38598196-4dc08116-3d10-11e8-881d-387b6ab64c39.png">
This has always been the case, this is also reproducible on 1.6.12 setup

**Comment by sangeethah** [comment]
This issue is seen with groups also:

<img width="1377" alt="screen shot 2018-04-11 at 1 46 47 pm" src="https://user-images.githubusercontent.com/4266958/38642467-0c38e92a-3d8f-11e8-9c56-5f27cf718715.png">
