### ISSUE TITLE
improper pre-canned golang scripts in pipeline

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#12623]
**Rancher versions:**
master 4/11

Case 1:
1. Click add a new pipeline,
2. Choose a golang repo, e.g. `https://github.com/gitlawr/goexample.git`, click `Add`
3. Check pre-canned scripts in build step:
```
mkdir -p /go/src/github.com/gitlawr/goexample
ln -s `pwd` /go/src/github.com/gitlawr/goexample
cd /go/src/github.com/gitlawr/goexample
go test
```
it cannot run successfully with fail message:
```
06:06:21 + go test
06:06:21 can't load package: package github.com/gitlawr/goexample: no Go files in /go/src/github.com/gitlawr/goexample
```
Expected scripts are:
```
mkdir -p /go/src/github.com/gitlawr
ln -s `pwd` /go/src/github.com/gitlawr/goexample
cd /go/src/github.com/gitlawr/goexample
go test
```

Case 2:
1. Click add a new pipeline,
2. Choose a golang repo, e.g. `https://github.com/gitlawr/goexample.git`, click `Add`
3. Click Cancel and do not save the pipeline.
4. Repeat 1&2, and check the script in build step
I see duplicate scripts:
![image](https://user-images.githubusercontent.com/5697937/38596469-537ca426-3d84-11e8-9cef-ce315b56646a.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
