### ISSUE TITLE
Browser Back button is not working on service detail page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1262]
Server version - V0.24.0

Steps to reproduce the problem:
From project list view , click on any service to launch the service detail page.
From service detail page , click on the browser's Back button.
Nothing happens.

Expected Behavior:
We should be brought back to the Project list view.

**Comment by vincent99** [comment]
There's an internal transition from "index of a service" to "the containers tab of a service" that is getting put into the history but shouldn't be.  So when you go back it goes back to "index of a service", which sends you right back to where you were.

**Comment by tfiduccia** [comment]
v0.27.0-rc1 (ui latest v0.32.0)
Verified fixed
