### ISSUE TITLE
Import k8s Resource From YAML

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#12627]
There are two different level to import k8s yaml.
- [ ] cluster level import yaml
- [ ] project level import yaml

When we import yaml in cluster, it should work as `kubectl apply -f`.
When we import yaml in project, we should provide a namespace for it. it should work as `kubectl apply -f -n <namespace>`

**Comment by bmdepesa** [comment]
rancher/rancher:master 5/16. 

This is working.
