### ISSUE TITLE
Ability to use Bitbucket in Pipeline

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#12625]
Add support for using Bitbucket in Pipeline

**Comment by techcto** [comment]
Is there a blueprint to help work on this?  I imagine it is very similar to how Git works. I would be willing to help.

**Comment by billabongrob** [comment]
Would like the ability to utilize this with on-prem bitbucket instances as well.

**Comment by dsargent3220** [comment]
We would also like on prem Bitbucket as well.

**Comment by rootwuj** [comment]
Version -2.2 master 11/30
Verified fixed

**Comment by francesco2013** [comment]
Looking forward to it. We really would love to create a pipeline and automate the deployments through our bitbucket repositories.
