### ISSUE TITLE
GKE Service Account Should Have compute.viewer privilege

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#12620]
1. Want to create a gke cluster
2. Create a service account for GKE with three IAM roles
3. Input service and click next

result:
<img width="1276" alt="2018-04-11 10 17 27" src="https://user-images.githubusercontent.com/15376837/38593086-373237b6-3d72-11e8-81af-f16e2cdbd109.png">

**Comment by tfiduccia** [comment]
@orangedeng - I was never able to reproduce this.  Can you see if it's fixed for you?

**Comment by orangedeng** [comment]
It is really odd that I can only reproduce this problem when I create service account in Chinese preference. And new it is fixed.
