### ISSUE TITLE
Node with multiple network card cause Kubernets cluster unaccess

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#12628]
*Node with multiple network card cause Kubernets cluster unaccess*

Rancher 2.0 UI show the error like this.
``` text
Failed to communicate with API server: Get https://192.168.235.14:6443/api/v1/componentstatuses: waiting for cluster agent to connect
```

And the node 192.168.235.14 has two ip address ,one is 10.0.1.14

![2](https://user-images.githubusercontent.com/3146226/38605193-34d86570-3da5-11e8-9756-94bf733db4fc.JPG)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta2` UI: `v2.0.34` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by yoke88** [comment]
![3](https://user-images.githubusercontent.com/3146226/38605253-5722af46-3da5-11e8-9c91-16e6e58d3d17.JPG)

**Comment by leifg** [comment]
What was the solution? Experiencing the same problem.

**Comment by BrianChristie** [comment]
Also experiencing this issue. We are using Flannel networking on AWS. Happy to provide any logs or troubleshooting steps that may be useful.

**Comment by yoke88** [comment]
this issue was caused by typo of of netconfig , i have typed 'netmask' to 'netmark' so the netmask changed from 24 to 16, and the gererated route table is wrong.
