### ISSUE TITLE
preview: can't start Rancher Server on DO droplet

### ISSUE THREAD

**Issue by utrack** [rancher/rancher#12636]
**Rancher versions:**
rancher/server: v2.0.0-b2
rancher/agent: ---

**Infrastructure Stack versions:**

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 17.10

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher server w/o any cluster

**Steps to Reproduce:**
I've created DO droplet, installed Docker 17.03.1 and ran
`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview`

**Results:**
Container startup is stuck at:
```
2018/04/11 15:35:52 [INFO] Creating serviceaccounts-manage
2018/04/11 15:35:52 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding globalrolebinding-mf2nm
2018/04/11 15:35:52 [INFO] Creating node driver amazonec2
2018/04/11 15:35:53 [INFO] Creating node driver azure
2018/04/11 15:35:53 [INFO] Creating node driver digitalocean
2018/04/11 15:35:53 [INFO] Creating node driver exoscale
2018/04/11 15:35:53 [INFO] Creating node driver openstack
2018/04/11 15:35:53 [INFO] Creating node driver otc
2018/04/11 15:35:53 [INFO] Creating node driver packet
2018/04/11 15:35:53 [INFO] Creating node driver rackspace
2018/04/11 15:35:53 [INFO] Creating node driver softlayer
2018/04/11 15:35:53 [INFO] uploading amazonec2Config to node schema
2018/04/11 15:35:53 [INFO] Creating node driver vmwarevsphere
2018/04/11 15:35:53 [INFO] uploading amazonec2Config to node schema
2018/04/11 15:35:53 [INFO] uploading azureConfig to node schema
2018/04/11 15:35:53 [INFO] uploading azureConfig to node schema
2018/04/11 15:35:53 [INFO] uploading digitaloceanConfig to node schema
2018/04/11 15:35:53 [INFO] uploading digitaloceanConfig to node schema
2018/04/11 15:35:53 [INFO] uploading vmwarevsphereConfig to node schema
2018/04/11 15:35:53 [INFO] uploading vmwarevsphereConfig to node schema
WARNING: 2018/04/11 15:36:06 grpc: addrConn.transportMonitor didn't get server preface after waiting. Closing the new transport now.
```
Stuck at this for ~20min+.

**Comment by superseb** [comment]
That logging does not say it's stuck or waiting on anything. It should say `Listening on` before. Did you try to visit the IP of the host with the ports opened?

**Comment by utrack** [comment]
Oops! My bad, I've forgot about DO's own FW. Works after opening ports.
