### ISSUE TITLE
Support configure java heap size for embedded ES

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12631]
User can configure the java heap size (Xmx, Xms) for the embedded ES target

**Comment by bmdepesa** [comment]
Blocked from testing by - https://github.com/rancher/rancher/issues/13043. Will re-test once resolved.

**Comment by bmdepesa** [comment]
Validated against rancher/rancher:master 4/26

As container is using +UseCGroupMemoryLimitForHeap, checked that memory limit & request settings for pod are updated when updated through the UI.
