### ISSUE TITLE
Create Alert successfully without selecting the node 

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12634]
**Rancher versions:**
rancher/server:master 04/11

**Steps to Reproduce:**
1. Create an Alert, choose Node, do not choose a node target.
2. Click Save.

![image](https://user-images.githubusercontent.com/1213386/38623519-72056ff0-3dd8-11e8-9bf6-6c0fd29df325.png)

![image](https://user-images.githubusercontent.com/1213386/38623540-7d7d92ea-3dd8-11e8-89ff-d45a8356239d.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified fixed
