### ISSUE TITLE
Shibboleth (Ping Federator) - "Internal Server Error" presented when user is denied access.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12645]
Rancher server version - 1.6 build from master

Steps to reproduce the problem:
Enable Shibboleth (Ping Federator)  auth and set access control to ""Allow members of Environment,plus Authorized Users and Organization".

Log in as a user (with valid password) who does not have access.

User is presented with "Internal Server Error"  message:

<img width="651" alt="screen shot 2018-04-11 at 1 03 55 pm" src="https://user-images.githubusercontent.com/4266958/38640530-67224846-3d89-11e8-9144-da0b1327a5ed.png">

Server logs:
```
time="2018-04-11T20:03:04Z" level=error msg="HandleSAMLPost: Error doing POST /v1/token: Bad response statusCode [403]. Status [403 Forbidden]. Body: [baseType=error, message=Your account does not have access, code=AuthError] from [http:/<ip>/v1/token], data: map[givenName:[Test] memberOf:[CN=testgroup1,CN=Users,DC=tad,DC=rancher,DC=io] sAMAccountName:[testuser3] displayName:[Test User3]]" 
time="2018-04-11T20:03:04Z" level=error msg="GetSamlAuthToken failed to Get token from cattle with error Bad response statusCode [403]. Status [403 Forbidden]. Body: [baseType=error, message=Your account does not have access, code=AuthError] from [http://<ip>/v1/token]" 
```

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
