### ISSUE TITLE
Proxy server returning different error codes for missing resource

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#12649]
Rancher/server:master

Sending a request to `<serverURL>/v3/projects/foo` returns a 400
Sending a request to `<serverURL>/v3/projects/foo:` returns a 500
Sending a request to `<serverURL>/v3/projects/foo:bar` returns a 404

All three versions of an invalid resource ID should return a 404

This is seen on multiple endpoints that require a colon in the ID.

**Comment by alena1108** [comment]
@dramich @ibuildthecloud those are the errors thrown by k8s:

* namespace is not passed for namespaced resource - 400 "Bad Request" `Namespace parameter required` 
* name is not passed in - 500 "Server error" `resource name may not be empty`
* invalid namespace/name are passed - 404 not found is returned. 

Not sure if we should override the default k8s behavior.

**Comment by alena1108** [comment]
after chatting with @ibuildthecloud we are going to override the default k8s behavior by:

*  if we know the object is namespaced and namespace == "" || name == "" we should just throw a 404 without talking to k8s
* if the object is not namespaced and contains ":" we should also throw 404

**Comment by dramich** [comment]
This issue is fixed for me.

**Comment by sangeethah** [comment]
Tested with latest build from master

Sending a request to <serverURL>/v3/projects/foo returns a 404
Sending a request to <serverURL>/v3/projects/foo: returns a 404
Sending a request to <serverURL>/v3/projects/foo:bar returns a 404
