### ISSUE TITLE
Discord/custom notification support for in 2.0

### ISSUE THREAD

**Issue by WoLfulus** [rancher/rancher#12648]
It would be nice to add support for Discord notifications or at least some kind of custom/generic, easy to integrate service for notifications.

**Comment by zionwu** [comment]
@WoLfulus 2.0 is using Prometheus AlertManager for alerting.  Discord is not supported by AlertManager.

To achieve custom notification, you can use the webhook notifier. You can create a micro service that provide a webhook and send your custom notification. AlertManager will post the following data to the webhook:

```
{
  "version": "4",
  "groupKey": <string>,    // key identifying the group of alerts (e.g. to deduplicate)
  "status": "<resolved|firing>",
  "receiver": <string>,
  "groupLabels": <object>,
  "commonLabels": <object>,
  "commonAnnotations": <object>,
  "externalURL": <string>,  // backlink to the Alertmanager.
  "alerts": [
    {
      "labels": <object>,
      "annotations": <object>,
      "startsAt": "<rfc3339>",
      "endsAt": "<rfc3339>"
    },
    ...
  ]
}
```

**Comment by westonmyers** [comment]
How about [this](https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook)?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15041
