### ISSUE TITLE
DNS resolution fails after moving system namespaces to a project

### ISSUE THREAD

**Issue by JonnyBGod** [rancher/rancher#12641]
**Rancher versions:**
rancher/server: 2.0.0-beta2
rancher/agent:

**Infrastructure Stack versions:**
network-services: Cannal
kubernetes (if applicable): v1.10.0-rancher1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS (ami-43a15f3e)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
Setup a Cluster
Create project Admin
Move system namespaces to Admin project
kubectl run  dnstest --image=alpine:latest --command sleep 36000
kubectl exec -it dnstest-5dbb477bcb-xhcbx  -- nslookup google.com

**Results:**
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'google.com': Try again

**Comment by alena1108** [comment]
@vincent99 I've put a fix to disallow moving certain namespaces to a project. UI handles the error well on namespace.edit, but on namespace.Move the dialog just spins forever

**Comment by ibuildthecloud** [comment]
@alena1108 Have to support this, we can't not allow moving system namespaces to a project.
