### ISSUE TITLE
UI - Iogin page has untranslated string

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12642]
Rancher-server version  - v2.0.0-beta3-rc1

I was presented with this message , when I tried to access rancher-server after a period of inactivity:

<img width="1179" alt="screen shot 2018-04-11 at 11 24 51 am" src="https://user-images.githubusercontent.com/4266958/38635716-0ee94a7a-3d7b-11e8-9d66-217f69d60789.png">

**Comment by loganhz** [comment]
It looks like a network issue as it says `Error loading language: en-us`. Is there anything we can do ? @vincent99

**Comment by vincent99** [comment]
I'm guessing your laptop was closed, then session expiry timer hit, laptop opened and the logout trigger fired before the network is up.
