### ISSUE TITLE
Missing translation for node roles sometimes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12643]
Rancher server version - v2.0.0-beta3-rc1

Steps to reproduce the problem:
I am not sure if these steps will reproduce this issue always.

Create a custom cluster.
Have registration url in few hosts.
Go to the node list view and wait for nodes to show up in this page.

<img width="1192" alt="screen shot 2018-04-11 at 11 53 39 am" src="https://user-images.githubusercontent.com/4266958/38637098-0c901ae8-3d7f-11e8-8685-ce15f0ba8ce2.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
