### ISSUE TITLE
username & Password should not be required for email notifier

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12654]
**Rancher versions:** 2.0 master 4/11

**Steps to Reproduce:**
1.  Go to Notifier
2.  Go to Email
3.  Try to create email notifier without username/password

**Results:**  Username and password are required fields.  They should not be.

**Comment by vincent99** [comment]
Yes; the `From` header of the email does not necessarily have any relationship with who you authenticated as.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/23
Verified fixed
