### ISSUE TITLE
Service image docker:stable is truncated to stable

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#12658]
**Rancher versions:**
rancher/server: 1.6.16

**Infrastructure Stack versions:**
scheduler: CATTLE

**Steps to Reproduce:**

Create a service with `docker:stable` as image
![service_creation](https://user-images.githubusercontent.com/1558372/38671506-e887338e-3e4b-11e8-8d5a-f9e68e19dc88.png)

**Results:**

The service is unhealthy because the image that is pulled is: `stable`

![service_issue](https://user-images.githubusercontent.com/1558372/38671500-e55f3a44-3e4b-11e8-8c13-56416337ce04.png)

**Comment by superseb** [comment]
It's because we append `docker:` and strip it again. Workaround is to use `docker:docker:stable` as described here: https://github.com/rancher/rancher/issues/2801#issuecomment-266104541

**Comment by jean-francois-labbe** [comment]
Thanks for the answer.

@superseb do you have an idea why my services that were working yesterday are now unable to start `Expected state running but got error: Image [docker] failed to pull: Pulling from library/docker` error
