### ISSUE TITLE
Can't bring up menu for sidecar

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12656]
**Rancher versions:** 2.0 master 4/11

**Steps to Reproduce:**
1.  Create a workload
2.  Add a sidecar
3.  Hover over the sidecar circle

**Results:**  It only shows the menu for the pod, no menu for sidecar

**Comment by loganhz** [comment]
@vincent99 I guess it is by design.

**Comment by vincent99** [comment]
There's no detail page for the containers of the pod but we still need a way to be able to see logs/exec into them and such..

**Comment by loganhz** [comment]
We need to change something in norman first. Please see the comment https://github.com/rancher/ui/pull/2073#discussion_r204128908

**Comment by loganhz** [comment]
Backend still not in. Not sure if anyone is working on the backend stuff.

**Comment by deniseschannon** [comment]
@alena1108 this seems like something in the API needs to be updated so that @loganhz can implement it.

**Comment by loganhz** [comment]
In pod detail page, added `exec` and `logs` actions in each tab of the container.

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/4
Verified fixed
