### ISSUE TITLE
Real-time stat aggregation 

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1265]
Rancher currently supports real time stats such as cpu/memory/disk by either host or container.  We need to extend and aggregate this to view this across:

- service - show container stats
- hosts - we already show host stat but should return aggregated container stats
- environments - show host stats (API is /projects)
- host tags - achieved by environments.  UI can parse this.
- projects - show container stats (API is /environments)

**Comment by wlan0** [comment]
**Specs for Real-time stat aggregation**

1. Provide Stat Link for 
- [ ] Services
- [ ] Hosts
- [ ] Environments
- [ ] Host Tags
- [ ] Projects

2. Update Stat Json Format to
```json
{
  "token": "adlfnsfnnkjdsnfejkfenfn.sdofndsoifjdskfnkesdfmksfmoidsfkdsnflkdsnfndsklnflksdnf",
  "urls": {
    "host-uuid" : [
      "ws://url:port/v1/stat/containerId",
      "ws://url:port/v1/stat",
    ]
  } 
}
```

3. Update Response format (in host-api) of existing stats to support aggregated logs. The new format should be able to represent the stat for a set of containers/set of hosts or a mixture of the previous two types.

Format:

```json
//TBD
```

4. Update Web proxy to support multiplexing of stats from multiple containers/container-host mixtures

**Comment by vincent99** [comment]
@wlan0 Host tag will be done in the UI if you can provide a stream of all the host stats for a project. So 
 - Per-container stats on {service, host, environment*, project*}
 - And per-host stats on project*.
    - (this means project will have 2 kinds of stats, so.. `hostStats` and `containerStats`?)

*: Words as defined in the API, not as displayed in the UI.

**Comment by will-chan** [comment]
- Adding stat support to environment, services, projects, hosts
- Add support for multi-node JSON format.

**Comment by will-chan** [comment]
- PR on Host-API and Cattle changes with new JSON format
- PR on stats links.
- Next milestone - integration with web-proxy to aggregate stats.

**Comment by will-chan** [comment]
PR is in, waiting for UI support.

**Comment by cjellick** [comment]
To officially document, per @wlan0, @will-chan decided that stats for an "environment" were out of scope for this.

/containerstats on host, instance, and service
/hoststats on host and project

Words as defined in the API, not as displayed in the UI.

**Comment by cjellick** [comment]
The question arose as to whether stopped containers should be inlcuded (so that if they go from stopped to running, their stats show up).

The consensus seems to be that yes, stopped containers should be included.
