### ISSUE TITLE
No Happens Options For Normal/Warning Node Alerts

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12664]
Steps:
Create a cluster,
Add an alert
Select Normal/Warning for "When A" option.

Results:
There are no options for "Happens" criteria. 

![screen shot 2018-04-11 at 3 28 51 pm](https://user-images.githubusercontent.com/38012481/38687422-8720b450-3e2b-11e8-84e4-70e6821b3e86.png)

**Comment by vincent99** [comment]
There are no criteria; it's when an event happens/occurs, send it somewhere.

**Comment by adingilloRancher** [comment]
Got it, I'll close this out then. 

Thanks.
