### ISSUE TITLE
agent (re)register on reboot

### ISSUE THREAD

**Issue by schmurfy** [rancher/rancher#12661]
**Rancher versions:**
rancher/server: 1.6.16
rancher/agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.09.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancheros 1.3.0 (pxe)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
BAre-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
two node rancher with one server with both agent & server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
- install & start rancher server
- install rancher agent on the server's machine, I added `-e CATTLE_AGENT_IP=1.2.3.4` to help rancher detect use correct address
- install rancher agent on the second host (I defined CATTLE_AGENT_IP too just to be sure)
- the two hosts are shown on the dashboard
- reboot the second host

**Results:**
The dashboard now show 3 hosts, the first one where rancher server runs and the second server displayed twice, each time I restart I get one more clone of the server...

How are agents recognized ? Do I need to do something to make sure the agent is recognized as the same server and not a new one ? (which is till somehow connected to the other clones, if I delete one all disappear)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
