### ISSUE TITLE
Support DNS roundrobin and cname

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1266]
Add DNS support for roundrobin of IPs and cname record support.

**Comment by vincent99** [comment]
rancherio/rancher-dns#5

**Comment by jwhitcraft** [comment]
:+1: This is awesome! Can't wait to try it out!

**Comment by will-chan** [comment]
Add Rancher API support and configuring the DNS server

**Comment by sangeethah** [comment]
Tested with server version - v0.29.0-rc1

Cname support is provided as part of External Services created with host name.
Created an external service using hostname pointing to an external site.
Create a service with link to this external service.
From the containers of this service , able to access the external site using the external link name.

Roundrobin support for DNS resolution is actually random order now.
Created a DNS service.
Created a service S2.
Created a service S1 which has links to S2  as "servlink" and DNS service as "dnslink".
From the containers of service S1 , dig on both "servlink"  and "dnslink" return the resolved addresslists in random order.

Closing this issue.
