### ISSUE TITLE
Creating Azure cluster : stuck in "Waiting to register with Kubernetes" state

### ISSUE THREAD

**Issue by wehappyfew** [rancher/rancher#12660]
I am trying to launch a kubernetes cluster on Azure.
I created a template with the necessary credentials in Rancher and started the creation of 5 nodes.
Now, in the Nodes tab, I see this:

![rancher](https://user-images.githubusercontent.com/4679365/38680985-49ce714c-3e70-11e8-882e-46765af0d9ff.PNG)

It is stuck in this state for quite some time now.

Any ideas?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta2` UI: `v2.0.34` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
Can you get the logging of the `rancher/server` container and possibly the logging of the `rancher/agent` container (if exists) on one of those servers?

**Comment by wehappyfew** [comment]
Ok..false alarm ! It took a loong time but I see all nodes active now.

**Comment by deniseschannon** [comment]
@wehappyfew Yes, when testing Azure clusters, we noticed that Azure is sometimes slow in responding or starting up.
