### ISSUE TITLE
[cli] rancher 2

### ISSUE THREAD

**Issue by amin-mir** [rancher/rancher#12668]
I am using rancher version 2. How can I get a token to login to my rancher server using rancher CLI?
`rancher login` seems to require a token flag, but I don't know where to get the token from.

**Comment by MotoAK** [comment]
Login to the Web UI. Click on the user icon top right, then click API & Keys. Then click Add Key. Fill out the appropriate values for your new key and click Create. On the next screen you will see various key secrets. Copy the Bearer Token. Then in the CLI use the "rancher login" command with the server URL and the "--token" option with the Bearer Token output. This will should configure the command and allow you to interact with the Rancher Server API.

**Comment by amin-mir** [comment]
Thanks man. It's working now. There is, however, one thing. I don't seem to be able to delete the keys I create for some reason. I get `no token store available`.
