### ISSUE TITLE
Environment variables in pipeline steps do not persist after saving pipeline

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12670]
**Rancher versions:**
rancher/server: master - 4/12/18 - 338cbfda0504

**Steps to Reproduce:**
Create a pipeline
Edit/create a step to include an environment variable and value.
Save step
Before saving pipeline, edit/view step - ENV variables should display
Save pipeline
Edit/view step from above - Env variables should display as entered

**Results:**
Actual: No environment variables are saved

Payload on saving:
`{"triggerWebhookPr":false,"triggerWebhookPush":false,"annotations":{"lifecycle.cattle.io/create.pipeline-controller_cluster-4jr8j":"true"},"baseType":"pipeline","created":"2018-04-12T17:18:06Z","createdTS":1523553486000,"creatorId":"user-5m67g","id":"project-l7lwd:pipeline-rt7fw","labels":{"pipeline.management.cattle.io/cron":"false"},"name":"1","namespaceId":null,"nextRun":4,"pipelineState":"active","projectId":"cluster-4jr8j:project-l7lwd","sourceCodeCredential":{"avatarUrl":"https://avatars2.githubusercontent.com/u/21316915?v=4","clusterId":"cluster-4jr8j","created":"2018-04-11T22:10:12Z","createdTS":1523484612000,"creatorId":null,"htmlUrl":"https://github.com/bmdepesa","loginName":"bmdepesa","name":"cluster-4jr8j-github-bmdepesa","sourceCodeType":"github","state":"active","status":{"type":"/v3/schemas/sourceCodeCredentialStatus"},"transitioning":"no","transitioningMessage":"","type":"/v3/schemas/sourceCodeCredential","userId":"user-5m67g","uuid":"1acf850d-3dd5-11e8-a3d2-0242ac110002"},"stages":[{"name":"clone","steps":[{"timeout":0,"sourceCodeConfig":{"branch":"master","branchCondition":"only","sourceCodeCredentialId":"user-5m67g:cluster-4jr8j-github-bmdepesa","type":"/v3/schemas/sourceCodeConfig","url":"https://github.com/bmdepesa/pipeline-example.git"},"type":"/v3/schemas/step"}],"type":"/v3/schemas/stage"},{"name":"build","steps":[{"timeout":0,"runScriptConfig":{"isShell":true,"image":"node:latest","shellScript":"npm install","type":"/v3/schemas/runScriptConfig"},"type":"/v3/schemas/step"}],"type":"/v3/schemas/stage"},{"name":"test","steps":[{"type":"task","runScriptConfig":{"isShell":false,"command":"npm test","env":{"SERVER":"nodeserver"},"image":"node:latest","shellScript":"npm install","type":"/v3/schemas/runScriptConfig"},"shellScript":""}],"type":"/v3/schemas/stage"}],"state":"active","transitioning":"no","transitioningMessage":"","type":"pipeline","uuid":"7741da8b-3e75-11e8-a316-0242ac110002","lastExecutionId":"project-l7lwd:pipeline-rt7fw-3","lastRunState":"Fail","lastStarted":"2018-04-12T17:19:05Z"}`

Viewing step with env variables:
<img width="949" alt="screen shot 2018-04-12 at 10 53 52 am" src="https://user-images.githubusercontent.com/21316915/38694972-e2d7371a-3e3f-11e8-9ec1-d8a5c242e36d.png">

Viewing step after saving pipeline:
<img width="959" alt="screen shot 2018-04-12 at 10 54 15 am" src="https://user-images.githubusercontent.com/21316915/38694973-e2effb74-3e3f-11e8-93f1-81e5a96f7700.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
