### ISSUE TITLE
have to manually provide registry secret in 2.0

### ISSUE THREAD

**Issue by allaryin** [rancher/rancher#12675]
Stood up a fresh 2.0 beta environment yesterday. Have a private docker registry (internal Gitlab). Images fail to automatically pull correct credentials.

4 hosts, all on the same subnet and all running near bare-bones Xenial installs. 1 is rancher, 1 is k8s etcd/control, and 2 are workers. RKE. 1.8.10-rancher1. Docker 17.03.2-ce.

Created a Registry entry in UI open to all namespaces in the default project.
kubectl create -f pod.yml that uses several containers from the private registry.
Get 403 errors trying to pull images.
Verified that docker login with same credentials from command line of worker node in question functions correctly.

After trying several different users, passwords, and tokens, eventually explicitly added the created secret as a imagePullSecret to the yml allowed the containers to pull.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta2` UI: `v2.0.34` |
|Access|`` `admin`|
|Route|`authenticated.project.dns.index`|

**Comment by kinarashah** [comment]
@allaryin Hi, since you're using kubectl directly - pods will get created without `imagePullSecrets` set. If you do it via Rancher, like creating a workload with those images, we'll fetch matching secrets from registries and set `imagePullSecrets` for you. Hope that helps!

**Comment by allaryin** [comment]
I had created this ticket on the recommendation of one of the developers in Slack, and I had brought it up as an issue because this is a different behavior from 1.6 - where creating a pod via kubectl does automatically discover the pull secrets that you configure the registry in the UI.
