### ISSUE TITLE
Empty "Logs" field for Slack Alerts

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12679]
Steps:
Create a new cluster.
Add slack notifier. 
Create a new workload for your cluster.
Create an alert for your project for when a Pod restarts 2 times in 5 minutes. 
Restart your host to meet the criteria and trigger the alert.

Results:
Alert is sent, but there is an empty value of "logs". 

<img width="1304" alt="screen shot 2018-04-12 at 1 52 14 pm" src="https://user-images.githubusercontent.com/38012481/38703675-c2c992f6-3e58-11e8-901d-d139f555a180.png">

**Comment by zionwu** [comment]
@adingilloRancher  we captured the error message from the condition of the pod.  I will remove the Logs field if the message is empty.

**Comment by adingilloRancher** [comment]
Verified fix master 4/17/2018
