### ISSUE TITLE
Changing step type doesn't reset UI validation for save button

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12676]
**Rancher versions:**
rancher/server: master 4/12/18 - 338cbfda0504

**Steps to Reproduce:**
Create a pipeline
Add a step with type 'publish an image' - Save button is enabled with default settings
Change option 'Registry' under 'Image' to 'custom' -- Save button should be disabled
Change step type to 'run a script' - Save button should be enabled

**Results:**
Actual - Save button is disabled, though options for 'run a script' are valid

Save button disabled after selecting 'custom' registry:
<img width="960" alt="screen shot 2018-04-12 at 12 08 12 pm" src="https://user-images.githubusercontent.com/21316915/38698670-bf6ff2d4-3e4a-11e8-8bca-d1d975361b38.png">

Save button still disabled after changing step type to `run a script` with valid options:
<img width="961" alt="screen shot 2018-04-12 at 12 08 23 pm" src="https://user-images.githubusercontent.com/21316915/38698671-bf8d19ea-3e4a-11e8-99b6-7e4f84aa3cf8.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
