### ISSUE TITLE
Add PVC hang in UI

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#12685]
I have configured Glusterfs and successfully create a pv if using the default volume access mode,but when i creating a new glusterfs volume using another access mode. for example ,i uncheck 'single node read-write' , then check 'Many nodes read-write' only , and mount this volume to /test5 ,when click the upgrading button ,the UI hangs.

``` bash
# proviously the pc i created using default access mode
ubuntu@LabManager1:/usr/share/heketi$ kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS         AGE
test1     Bound     pvc-dd7e679e-3e16-11e8-896e-0010181a3f56   11G        RWO            gluster-replicate2   20h
test4     Bound     pvc-108cdaf8-3ec0-11e8-8caf-0010181a3f56   11G        RWO            gluster-replicate2   13m

```

![e1](https://user-images.githubusercontent.com/3146226/38713709-179dc2e6-3f05-11e8-86c8-53e4679193f4.jpg)

![e2](https://user-images.githubusercontent.com/3146226/38713726-377a6876-3f05-11e8-9218-1af0ae130e6d.jpg)

### Another problem 
there is no method to validate your storage class validation. and no ui to show the pvc you created . for example ,if the password of heketi is wrong ,the pvc will be failed , and the UI does not show such errors or fails.

``` bash
ubuntu@LabManager1:~$ kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS         AGE
test1     Bound     pvc-dd7e679e-3e16-11e8-896e-0010181a3f56   11G        RWO            gluster-replicate2   19h
test2     Pending                                                                        gluster-replicate2   6m
test3     Pending                                                                        gluster-replicate2   3m
ubuntu@LabManager1:~$ kubectl describe pvc test2
Name:          test2
Namespace:     default
StorageClass:  gluster-replicate2
Status:        Pending
Volume:
Labels:        <none>
Annotations:   field.cattle.io/creatorId=user-l5glg
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/glusterfs
Finalizers:    []
Capacity:
Access Modes:
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  1m (x26 over 7m)  persistentvolume-controller  Failed to provision volume with StorageClass "gluster-replicate2": create volume error: error creating volume signature is invalid

```
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta2` UI: `v2.0.34` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by StrongMonkey** [comment]
@yoke88 can you go back to see what's the exact error of 422 conflict? backend is giving you a 422 error which shows that something might not be updatable and UI is probably not handling that well.

**Comment by yoke88** [comment]
maybe the ui can not just select "many node read-write" only , it must select all the above

the env of mine has destroyed, so i can not get the info

**Comment by deniseschannon** [comment]
@loganhz we should fix so that the UI isn't hanging for when it returns 422

**Comment by yoke88** [comment]
With UI 2.0.38, just select "manay nodes read-write", then mount it to a pod , when click upgrade, it
will hang there.

![default](https://user-images.githubusercontent.com/3146226/39282943-3a851992-493e-11e8-996f-832144dd4912.JPG)

![default](https://user-images.githubusercontent.com/3146226/39283007-8bdef510-493e-11e8-9763-f3431d5de444.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/30
Verified fixed
