### ISSUE TITLE
Node dashboard not reporting system resource usage. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12683]
Steps:
Create a new DO cluster with one node as dedicated worker.
SSH into worker host.
Perform stress test. 
 apt install stress
stress --vm-bytes $(awk '/MemFree/{printf "%d\n", $2 * 0.9;}' < /proc/meminfo)k --vm-keep -m 1

Results:
Dashboard consistently sits at 0% memory usage.
CPU does not update either. 

![screen shot 2018-04-12 at 2 50 11 pm](https://user-images.githubusercontent.com/38012481/38706641-c0fb8808-3e62-11e8-8ebb-239ff3c989fa.png)

**Comment by vincent99** [comment]
The dials are allocatable memory(/cu/pod count) vs how much is reserved by current Workloads, which is the info used for scheduling new pods.  It is not a live view of actual usage of the node.

**Comment by adingilloRancher** [comment]
Not an issue.
