### ISSUE TITLE
Rancher 2 - Ubuntu - /var/lib/kubelet is mounted on / but it is not a shared mount 

### ISSUE THREAD

**Issue by ybelot** [rancher/rancher#12687]
Hello all,

i'm testing rancher 2 and i recognize that i'm pretty noob.
i'm experiencing some issues when deploying cluste on Vcenter.
Rancher has been deployed on a Ubuntu 16.04 vm.
When i deploy a cluster on vmware, i have this issue : 

[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [192.168.59.104]: Error response from daemon: linux mounts: Path /var/lib/kubelet is mounted on / but it is not a shared mount

Before this , i tried with a Centos vm but still the same issue.
In my template i use Boot2docker 17.03.CE

i also tried to manually mount inside nodes  : 
sudo mount --make-shared /var/lib/kubelet
sudo mount --make-shared /var/lib/kubelet

i've seen some replys there but i don't know where to begin and how to solve it.
Thanks for your help

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta2` UI: `v2.0.34` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by wanshaoyuan** [comment]
Hi,Try to configure docker.service parameters "MountFlags=shared".
Refer to this issue
https://github.com/rancher/rke/issues/264

**Comment by ybelot** [comment]
Thanks, i tried this but that did not solve the issue
I tried also with blank parameter "MountFlags="

There is my service config (in my Rancher vm (ubuntu 16.04)
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target docker.socket firewalld.service
Wants=network-online.target
Requires=docker.socket

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd://
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s
MountFlags=shared

[Install]
WantedBy=multi-user.target

**Comment by nitram2k** [comment]
I had the same issue, it works when using:

https://github.com/boot2docker/boot2docker/releases/tag/v17.03.2-ce

and when spinning up the boot2docker nodes, issue this command inside those:

mount --make-shared /

this fixes this issue for me :)

**Comment by ybelot** [comment]
Thanks Nitram2k

it works !!!

**Comment by gaui** [comment]
@nitram2k How do you exec this inside the boot2docker nodes? Do I have to SSH into them, or is it possible to run this from Rancher?

**Comment by ybelot** [comment]
Simply ssh to your b2d nodes using ssh docker@x.x.x.x  
password is "tcuser"

regards

**Comment by gaui** [comment]
@ybelot so if I provision 100 nodes, I have to SSH into 100 nodes? Uhhh... that's not acceptable.

**Comment by gaui** [comment]
@wanshaoyuan Please reopen this. I'm having this problem, 2.0.0 beta3 with Boot2Docker 17.03.2. This is clearly a problem that needs to be addressed. People should not be forced to issue some mount command on the nodes.

**Comment by superseb** [comment]
The fix for this is already in the master branch

**Comment by gaui** [comment]
@superseb Can you link me to the commit?

**Comment by superseb** [comment]
https://github.com/rancher/rancher/commit/d62c1a9972f922fab1ca6cdad44aae19791df623

**Comment by gaui** [comment]
@superseb Confirmed `/var/lib/kubelet` works fine, but now I'm getting the same for `/var/lib/docker`:

```
[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [192.168.176.101]: Error response from daemon: linux mounts: Path /mnt/sda1/var/lib/docker is mounted on /mnt/sda1 but it is not a shared or slave mount.
```

**Comment by cw1427** [comment]
after run: mount --make-shared /  and  restart docker service. it resolved.
