### ISSUE TITLE
rancher 2.0 down

### ISSUE THREAD

**Issue by zhangalex** [rancher/rancher#12684]
**Rancher versions:**
rancher/server: 2.0
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12129b1]

goroutine 11142 [running]:
github.com/rancher/rancher/vendor/github.com/docker/distribution/reference.SplitHostname(0x0, 0x0, 0x0, 0x0, 0x4c97a9c, 0x19)
	/go/src/github.com/rancher/rancher/vendor/github.com/docker/distribution/reference/reference.go:183 +0xd1
github.com/rancher/rancher/vendor/github.com/docker/distribution/reference.TrimNamed(0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/docker/distribution/reference/reference.go:323 +0x39
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterKubernetesImageVersion(0xc425871c00, 0xa5321c0, 0xc423b3c8d0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:96 +0x2c2
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterDefaults(0xc425871c00, 0xa5321c0, 0xc423b3c8d0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:85 +0x4b4
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.ParseCluster(0xa5321c0, 0xc423b3c8d0, 0xc423333600, 0x0, 0x0, 0xc429f4d890, 0x2e, 0xc427a5cc50, 0xc427a5cc70, 0xc42a379680, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:146 +0x15f
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0xa5321c0, 0xc423b3c8d0, 0xc423333600, 0xc427a5cc50, 0xc427a5cc70, 0xc42a379680, 0x0, 0xc429f4d890, 0x2e, 0x0, ...)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:60 +0x104
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Create(0xc420f9e810, 0xa5321c0, 0xc423b3c8d0, 0xc42a379100, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:137 +0x248
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Create(0xc420fec0a0, 0xa5321c0, 0xc423b3c6f0, 0xc42a379100, 0xc420fec0a0, 0xc427b5a340, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:45 +0x6d
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Create_Handler(0x49246c0, 0xc420fec0a0, 0xa5321c0, 0xc423b3c6f0, 0xc420b311f0, 0x0, 0x0, 0x0, 0x433d64, 0xc42aa6b800)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:546 +0x276
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4207d6dc0, 0xa546f80, 0xc427cc7800, 0xc42bf2de00, 0xc420f9ec00, 0xa4d64a0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x96e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4207d6dc0, 0xa546f80, 0xc427cc7800, 0xc42bf2de00, 0x0)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1528
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc428f04140, 0xc4207d6dc0, 0xa546f80, 0xc427cc7800, 0xc42bf2de00)
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1

**Comment by superseb** [comment]
Can you supply the steps to reproduce and complete `rancher/server` logging?

**Comment by JulienFauvel** [comment]
Hey, I have the same error.
It only happens when creating a new cluster with a private docker registry

I am running docker 17.03 on a Debian 9

Steps to reproduces :
* Create a custom cluster
* Set a docker registry (mine looks like "https://docker.entreprise.io/")
* Click the create button
* Run the docker run command
* It crashes

Here is the stacktrace when creating the cluster
```
2018/04/25 09:31:12 [INFO] Handling backend connection request.
2018/04/25 09:31:12 [INFO] Provisioning cluster [cluster-mdcjr]
2018/04/25 09:31:12 [INFO] Creating cluster [cluster-mdcjr]
2018-04-25 09:31:12.535659 I | mvcc: store.index: compact 1640
2018-04-25 09:31:12.537209 I | mvcc: finished scheduled compaction at 1640 (took 1.16531ms)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12129b1]
goroutine 96626 [running]:
github.com/rancher/rancher/vendor/github.com/docker/distribution/reference.SplitHostname(0x0, 0x0, 0x0, 0x0, 0x4c97a9c, 0x19)
        /go/src/github.com/rancher/rancher/vendor/github.com/docker/distribution/reference/reference.go:183 +0xd1
github.com/rancher/rancher/vendor/github.com/docker/distribution/reference.TrimNamed(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/docker/distribution/reference/reference.go:323 +0x39
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterKubernetesImageVersion(0xc42bf0b800, 0xa5321c0, 0xc43c0295c0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:96 +0x2c2
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterDefaults(0xc42bf0b800, 0xa5321c0, 0xc43c0295c0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:85 +0x4b4
github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.ParseCluster(0xa5321c0, 0xc43c0295c0, 0xc422e09080, 0x0, 0x0, 0xc427026f00, 0x2e, 0xc42c291340, 0xc42c291350, 0xc424f72ee0, ...)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/cluster.go:146 +0x15f
github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd.ClusterUp(0xa5321c0, 0xc43c0295c0, 0xc422e09080, 0xc42c291340, 0xc42c291350, 0xc424f72ee0, 0x0, 0xc427026f00, 0x2e, 0x0, ...)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cmd/up.go:60 +0x104
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke.(*Driver).Create(0xc4207b93e0, 0xa5321c0, 0xc43c0295c0, 0xc424f728e0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go:137 +0x248
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types.(*GrpcServer).Create(0xc420413100, 0xa5321c0, 0xc43c029500, 0xc424f728e0, 0xc420413100, 0x0, 0x53f8051a1b79c758)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_server.go:45 +0x6d
github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types._Driver_Create_Handler(0x49246c0, 0xc420413100, 0xa5321c0, 0xc43c029500, 0xc42cbb3490, 0x0, 0x0, 0x0, 0xc42006a000, 0x7fe11073f6c8)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/drivers.pb.go:546 +0x276
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42033c000, 0xa546f80, 0xc43ba98480, 0xc428f332c0, 0xc4207b9bc0, 0xa4d64a0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:921 +0x96e
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42033c000, 0xa546f80, 0xc43ba98480, 0xc428f332c0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:1143 +0x1528
github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc425169c30, 0xc42033c000, 0xa546f80, 0xc43ba98480, 0xc428f332c0)
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/rancher/rancher/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/rancher/rancher/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

**Comment by deniseschannon** [comment]
@JulienFauvel What rancher server version are you running?

**Comment by JulienFauvel** [comment]
@deniseschannon 
I do believe it's the latest rancher/server:preview 

Version : v2.0.0-beta3 on the web UI

**Comment by zhangalex** [comment]
It likely that v2.0.0 has already fixed this issue.
