### ISSUE TITLE
2.0.0-beta3 cluster provisioning fails

### ISSUE THREAD

**Issue by toddpovilaitis** [rancher/rancher#12688]
*Describe your issue here*

Just discovered Rancher less than 24 hours ago.  Installed 2.0.0-beta2 using the command:
$docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview
Setup a cluster, added workloads.  Works great.

Tonight, I provisioned two new nodes from the same template.  Installed 2.0.0-beta3 using the same command that delivered beta2 yesterday:
$docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview
Cluster setup hangs on Provisioning

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta3` UI: `v2.0.35` |
|Access|`local` `admin`|
|Route|`global-admin.settings.advanced`|

**Comment by superseb** [comment]
Can you supply the steps you took and what it is hanging on? And what template did you create? Are those fresh nodes or are you re-using them, as previously used nodes contain data that breaks stuff.

Logging from the `rancher/server` and `rancher/agent` containers helps also.

**Comment by toddpovilaitis** [comment]
I created an Ubuntu 16.04.4 VM template on ESXi 6.0 u3 with the following modifications:

$ sudo apt update && sudo apt upgrade
$ sudo apt purge lxd lxd-client
$ sudo snap install lxd
$ sudo apt install zfsutils-linux


·         Originally created the template for use with conjure-up

I provisioned new VM nodes from this template.  Then added docker-ce and rancher:

$sudo apt remove docker docker-engine docker.io
$sudo apt update
$sudo apt install apt-transport-https ca-certificates curl software-properties-common
$curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
$sudo apt-key fingerprint 0EBFCD88
$sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
$sudo apt update
$apt-cache madison docker-ce
$sudo apt install docker-ce=17.03.2~ce-0~ubuntu-xenial
$sudo usermod -aG docker $USER
$docker run hello-world
$sudo systemctl enable docker
$docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview

From here, I just followed the QuickStart guide (https://rancher.com/docs/rancher/v2.0/en/quick-start-guide/) to create a new cluster.
Worked yesterday with 2.0.0-beta2.  Doesn’t work today with 2.0.0-beta3

I’ve attached the rancher/server log to this message.  Hope this helps…

**Comment by superseb** [comment]
Can you provide the full `rancher/server` log after you first started it and tried to add a node? This log does not seem to show any cluster creation or adding a node.

**Comment by toddpovilaitis** [comment]
HI Sebastian,

That IS the full log for rancher/server, 2.0.0-beta3.  Rancher Create Cluster hangs on Provisioning the cluster.

I see what you are asking for in the rancher/server log that I have for my other VM, 2.0.0-beta2.  But this is as far as the log for 2.0.0-beta3 goes.

To verify this is not a fluke, I tried 2.0.0-beta3 again today on a new VM provisioned exactly as the others.  Same result.  Rancher Create Cluster hangs on Provisioning the cluster.

Screenshot and abridged log attached.

NOTE:  In both cases, 2.0.0-beta2 (works) and 2.0.0-beta3 (doesn’t work), I am using the Custom Cluster option and deploying directly to a VM using the default settings.  There is no integration with vSphere or a cloud provider.

**Comment by superseb** [comment]
Screenshots are not coming through when replying using email. Can you also share the complete logging of the launched `rancher/agent` container?

**Comment by toddpovilaitis** [comment]
![image](https://user-images.githubusercontent.com/30504704/38759395-9802f990-3f2a-11e8-8735-0c5a5b383cd0.png)

The only container beta3 creates is the rancher/server.  So i have no rancher/agent log to offer:

todd@ubs-1604-02:~$ 
todd@ubs-1604-02:~$ 
todd@ubs-1604-02:~$ docker container ls
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
4ac66cbded15        rancher/server:preview   "rancher --http-li..."   4 hours ago         Up 4 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   stupefied_ardinghelli
todd@ubs-1604-02:~$ 
todd@ubs-1604-02:~$ 
todd@ubs-1604-02:~$ 

By comparison, beta2 has so many containers that I needed to filter the list to find the rancher/agent:

todd@ubs-1604-06:~$ 
todd@ubs-1604-06:~$ 
todd@ubs-1604-06:~$ docker container ls | grep "rancher/agent"
f0a0c60ecc89        rancher/agent@sha256:03c97cbb90c78b9cfd95a4717b32c51347d09453d6717c7b659085adec885742                                     "run.sh"                 35 hours ago        Up 35 hours                                                    k8s_cluster-register_cattle-cluster-agent-cf8648c69-bld2w_cattle-system_df4a51c6-3e39-11e8-a7b4-005056ba5031_0
6d285084f92c        rancher/agent@sha256:03c97cbb90c78b9cfd95a4717b32c51347d09453d6717c7b659085adec885742                                     "run.sh"                 35 hours ago        Up 35 hours                                                    k8s_agent_cattle-node-agent-lzbkz_cattle-system_df544665-3e39-11e8-a7b4-005056ba5031_0
todd@ubs-1604-06:~$ 
todd@ubs-1604-06:~$ 
todd@ubs-1604-06:~$

**Comment by toddpovilaitis** [comment]
![image](https://user-images.githubusercontent.com/30504704/38759395-9802f990-3f2a-11e8-8735-0c5a5b383cd0.png)

The only container beta3 creates is the rancher/server.  So i have no rancher/agent log to offer:

todd@ubs-1604-02:~$ 
todd@ubs-1604-02:~$ 
todd@ubs-1604-02:~$ docker container ls
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
4ac66cbded15        rancher/server:preview   "rancher --http-li..."   4 hours ago         Up 4 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   stupefied_ardinghelli
todd@ubs-1604-02:~$ 
todd@ubs-1604-02:~$ 
todd@ubs-1604-02:~$ 

By comparison, beta2 has so many containers that I needed to filter the list to find the rancher/agent:

todd@ubs-1604-06:~$ 
todd@ubs-1604-06:~$ 
todd@ubs-1604-06:~$ docker container ls | grep "rancher/agent"
f0a0c60ecc89        rancher/agent@sha256:03c97cbb90c78b9cfd95a4717b32c51347d09453d6717c7b659085adec885742                                     "run.sh"                 35 hours ago        Up 35 hours                                                    k8s_cluster-register_cattle-cluster-agent-cf8648c69-bld2w_cattle-system_df4a51c6-3e39-11e8-a7b4-005056ba5031_0
6d285084f92c        rancher/agent@sha256:03c97cbb90c78b9cfd95a4717b32c51347d09453d6717c7b659085adec885742                                     "run.sh"                 35 hours ago        Up 35 hours                                                    k8s_agent_cattle-node-agent-lzbkz_cattle-system_df544665-3e39-11e8-a7b4-005056ba5031_0
todd@ubs-1604-06:~$ 
todd@ubs-1604-06:~$ 
todd@ubs-1604-06:~$

**Comment by superseb** [comment]
Running `rancher/server` seems fine, you created a cluster which is waiting for nodes to register. When creating the cluster (or if you use `Edit Cluster` after), you get a `docker run` command to execute on the nodes you want to add. This runs the `rancher/agent` container. I would like to see the logging of that container after you run the command to add it. 

When using `Custom` cluster, you need to add nodes by running the `docker run` command. If you use Node Drivers, host will be created using the driver and added to the cluster.

The output you are showing is from a node that was added using `docker run`. When it has successfully joined the cluster, it will create pods to run the `rancher/agent` container and remove the initial one created by the `docker run` command.

**Comment by toddpovilaitis** [comment]
Oh, of course! You are referring to the docker command that Rancher prominently displays, offers a copy -to-clipboard option, and states I need to run it on one or more nodes.  That command!

In that case, 2.0.0-beta3 Custom cluster provisioning is working just fine.  I now have a two node cluster up and running on 2.0.0-beta3 and will adding another node shortly.

I must remember not to try out new things at 3AM and forget how I got it to work in the first place.  My apologies for being a little slow to catch on.

On the other hand, maybe there's an opportunity here to add clarity to the dialog on that last cluster creation screen.  Currently it says:

_"Run this command on one or more existing machines already running a supported version of Docker"_

For whatever reason, I was under the impression Rancher would provision the first node on its own.  Then, if I wanted to add additional nodes to the cluster, I would need to run this command only on them.  Perhaps the instructions might look something like this:

_"When creating a Custom cluster, all nodes are added to the cluster by running the following command, including the first node.  To add additional nodes to the cluster, simply run this command on one or more existing machines already running a supported version of Docker"_

**Comment by CollinChaffin** [comment]
Couldn't agree more.  +1 to fix wording.  Even though this is old and closed - it STILL applies on latest build today.  It is absolutely unclear in the wording, and the roughly four-word help pages on each Rancher operation are frankly a joke on such a complex product.  So for anyone else expecting this web management GUI to actually be doing something at the end of the 1st node wizard - the wording is missing the fact that it is NOT - and is self service awaiting you to run the command yourself! :)
