### ISSUE TITLE
insufficient pods

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#12690]
I run into issue with too many pods on one server. RAM and CPU is ok since that are small pods not taking many resources.
Because of this i wan't to increase the max-pod option. See https://prefetch.net/blog/2018/02/10/the-kubernetes-110-pod-limit-per-node/

I know i could reach this goal with forking my own docker image for kubelet but i think there should be an option todo that while installing kubernetes env.

Do i miss this ore is there nothing?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`service.containers`|

**Comment by superseb** [comment]
There is a additional kubelet flags variable in the catalog item for k8s: https://github.com/rancher/rancher-catalog/blob/v1.6-release/infra-templates/k8s/44/docker-compose.yml.tpl#L42

This will be applied to the kubelet parameters. Let me know if you encounter problems using this.

**Comment by danielschlegel** [comment]
Thanks!

**Comment by Angelinsky7** [comment]
@superseb how can we do the same in rancher v2 ? thanks !
