### ISSUE TITLE
Add script to reset default admin password

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#12697]
In rancher 2.0. Please lose/forget/screwup the default password. There should be a script or small program in the reancher/server image that lets them easily reset it.

**Comment by cjellick** [comment]
Example usage:
```
docker exec e4c211d6de16 reset-password
New passowrd for default admin user (user-r42hp):
nDQaFWlacYBLUaDdfpFY
```

**Comment by adingilloRancher** [comment]
Verified built-in. 
Reset local  admin PW.
Reset local admin PW with github.
Reset local admin PW with AD.

Was able to login as admin user after change.

**Comment by soumyalj** [comment]
This works on a 2.0 HA cluster

**Comment by soumyalj** [comment]
Tested with 2.0.1-rc3 on HA cluster with external etcd. The password reset works, 
```
root@soumyaextetcdhost3:~# sudo docker exec d5bf13dd4621 reset-password
W0518 16:32:15.679842     449 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
New password for default admin user (user-zqtc7):
kagDkTWMsSsEZPrHRCE

```
An issue to track the warning here: https://github.com/rancher/rancher/issues/13601

**Comment by vikas027** [comment]
Whoever lands here and is confused which container to exec in, this is another way of doing this.

This saved me in Rancher v2.2.1
```
$ kubectl -n cattle-system exec $(kubectl -n cattle-system get pods | grep ^rancher | head -n 1 | awk '{ print $1 }') reset-password
New password for default admin user (user-jr7kv):
UdS-R1txdd3ssf32okXG
```

**Comment by cjellick** [comment]
Link to it in the docs as well: https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-reset-the-admin-password

**Comment by Fawadio** [comment]
what if the port is different

**Comment by jmingov** [comment]
@vikas027 proposed command works, but be careful because atleast in v2.6 as the first match can be the `rancher-webhook-XXXXXXX-XXXXX` pod and it will not work, you ll get a command not found error like:

` OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "reset-password": executable file not found in $PATH: unknown`

Best,
j

**Comment by vikas027** [comment]
> @vikas027 proposed command works, but be careful because atleast in v2.6 as the first match can be the `rancher-webhook-XXXXXXX-XXXXX` pod and it will not work, you ll get a command not found error like:

Yeah, looks like things have changed a bit in later versions of Rancher.

**Comment by wrossmann** [comment]
A far more succinct kubectl command:

```
kubectl exec -n cattle-system deploy/rancher -- reset-password
```

**Comment by idc77** [comment]
doesn't work
