### ISSUE TITLE
Enhance Cluster Driver so that it can be pluggable like Node Drivers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12698]
Add ability to activate/de-activate/add/remove cluster drivers like we do for node drivers.

**Comment by loganhz** [comment]
Hi @nathan-jenan-rancher , please assign this issue to me when backend is ready. Thanks a lot!

**Comment by nathan-jenan-rancher** [comment]
The way kontainer-engine drivers work has been changed.

All drivers must first be created as part of the `kontainerDrivers` CRD.  This contains information like their status, if they are built in or not, and the url to download the driver binary.

Once a driver has been added, and it is active, the binary is downloaded and put in a directory (builtin drivers are not downloaded and have their own special startup logic). It is also started briefly to query the `GetCreateOptions` method on the driver.  This information is used to populate the schema of the driver.  The driver flags that have been set in the driver are converted into the dynamic schema and added to the cluster resource.  This schema can be most easily found by looking at the resources fields on the cluster schema.  This driver schema contains all the information and fields that were previously in the various driver configs hard coded in the rancher/types library off of the cluster object.

Once a driver is active and its schema has been added it functions as it did previously.  No existing UI code should need to change to accommodate the existing drivers.

When the new drivers are called in the various operations (create, update, remove, etc), the driver is started and listens on a randomly assigned port.  The rancher GRPC client will connect as it normally does, and the request will process.

We have an example external driver located here: https://github.com/rancher/kontainer-engine-example-driver/

This is just the GKE driver, but packaged so as to allow it to be used as an external driver.

Here is an example kontainer-engine CRD for testing with that driver in Rancher API form:
```
{
    "active": true,
    "baseType": "kontainerDriver",
    "builtIn": false,
    "desirdUrl": "https://github.com/rancher/kontainer-engine-example-driver/releases/download/v0.1.0/kontainer-engine-example-driver-darwin",
    "dynamicSchema": true,
    "name": "exampleKontainerEngineDriver"
}
```

**Comment by guangbochen** [comment]
@nathan-jenan-rancher the kontainer-engine CRD seems missing field for the logo, or should we put it in somewhere else?

**Comment by vincent99** [comment]
Logos would go in the UI plugin for the provider.  But this is missing fields for where to get the UI, the expected checksum of the driver, `desirdUrl`is spelled wrong, and`dynamicSchema`doesn't sound like a field that should be exposed.  Basically they should look like nice drivers except for the type.

**Comment by cjellick** [comment]
UI issue: https://github.com/rancher/rancher/issues/15101

**Comment by gitlawr** [comment]
Here are some feedbacks using the driver framework:
1. It would be nice if the driver can define some password type options for cloud provider credentials and they are not exposed in cluster API.
2. It would be nice if transition status can be shown in the UI during provisioning.

**Comment by nathan-jenan-rancher** [comment]
> 1. It would be nice if the driver can define some password type options for cloud provider credentials and they are not exposed in cluster API.
We should already be doing this.  I'm not sure if it made it into the example driver but adding a `password: true` field to the driver create options in kontainer-engine will create a field on the schema that will be hidden, like this:
```
	driverFlag.Options["client-secret"] = &types.Flag{
 		Type:  types.StringType,		 		Type:     types.StringType,
 		Usage: "Client secret associated with the client-id",		 		Password: true,
 		Usage:    "Client secret associated with the client-id",
 	}		 	}
```

> 2. It would be nice if transition status can be shown in the UI during provisioning.
We should be sending the same transition status we were before but I'll double check.  We may need a generic enhancement to how we communicate this info in Rancher

**Comment by soumyalj** [comment]
Tested with master from Nov 30 build. Created GKE, AKS, EKS clusters . Clusters were functional and passed the regular test runs.
The following issue was filed for GKE cluster https://github.com/rancher/rancher/issues/16807

**Comment by soumyalj** [comment]
Tested with master build from Feb 13/14. Used the example cluster driver v0.2.1.
https://github.com/rancher/kontainer-engine-driver-example/releases
Added cluster driver and created a cluster successfully. Cluster was created successfully.
Other user cases were tested. Pluggable cluster driver feature is functional
