### ISSUE TITLE
UI Validation Errors in 'Publish Image' step configuration

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12694]
**Rancher versions:**
rancher/server: master 4/12/18 - 338cbfda0504

**Steps to Reproduce:**
Create a pipeline
Add a step with type 'publish an image'

**Results:**
Validation error "'Image Tag' is required!" is displayed when 'Repository' is empty - error saying Repository is required should be displayed instead

Validation error "'Image Tag' is required!" is displayed when 'Repository' and 'Tag' are empty - both errors should display

Validation error "'Image Tag' is required!" is displayed when 'Build Context' is empty

Default text in Build Context field displays "Dockerfile path" instead of "Build Context" when text is erased from the field

**Comment by biblesyme** [comment]
Changed Validation error "'Image Tag' is required!" to "Image is required".
Changed `Tag` to an optional filed. Cause the `Tag` can be empty, its default value is `latest`.
