### ISSUE TITLE
When running a pipeline for the first time from the 'Run Once' menu item in the pipeline details page, the page becomes unresponsive

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12695]
**Rancher versions:**
rancher/server: master 4/12/18 - 338cbfda0504

**Steps to Reproduce:**
Create a pipeline with some steps
Go to the pipeline details page
Execute the pipeline by clicking 'Run Once' from the menu

**Results:**
The page becomes unresponsive and nothing is updated on the screen. User must refresh the page for activity details to display.

Page after clicking 'Run Once':
<img width="1256" alt="screen shot 2018-04-13 at 9 09 58 am" src="https://user-images.githubusercontent.com/21316915/38745803-807d3e78-3efa-11e8-81b0-da48180c4a0d.png">

Browser console errors:
<img width="1499" alt="screen shot 2018-04-12 at 1 39 00 pm" src="https://user-images.githubusercontent.com/21316915/38745747-55754522-3efa-11e8-8d2a-2555834ea120.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Still a bug - Getting same errors and page is unresponsive.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/18
Verified fixed
