### ISSUE TITLE
Implement --label for agent

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12691]
**Rancher versions:**
rancher/server: v2.0.0-beta3
rancher/agent: v2.0.0-beta3

**Steps to Reproduce:**

- Create custom cluster
- Add label to command resulting in command ending with `--label key=value`
- Add node using the command

**Results:**
- Labels are not used

**Comment by aiwantaozi** [comment]
@superseb the label should work, I have tested it, where you add the label, the label should not add as the last, because of the last command params, not the docker params, my command looks like below

```
sudo docker run --label rancher.io.user="tester"  -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:master --server https://192.168.1.106:8443 --token xxxx --ca-checksum xxx --etcd --controlplane --worker
```

**Comment by superseb** [comment]
@aiwantaozi Thanks, makes sense. I will rename so the UI can put the label param in the correct place.

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/39512693-71ac4874-4e24-11e8-9cad-0e88aa2f1351.png)

UI is putting the label in the wrong place.

**Comment by vincent99** [comment]
What?  No.. these are labels to be given to the agent container to then add to the **node**, just like in 1.x.  They are not labels to assign to the agent container itself, why would anybody want that?

**Comment by vincent99** [comment]
@ibuildthecloud I don't think support for parsing the lablels was ever added to the agent.

**Comment by mholttech** [comment]
will this be fixed on 2.0.1?

**Comment by soumyalj** [comment]
Tested with master.
1. Created a custom cluster
2. Added an node with --labels 
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:master --server https://a.b.c.d --token abc --ca-checksum def --etcd --controlplane --worker --label test=value

```
3. The node was added without the labels

<img width="624" alt="screen shot 2018-06-08 at 11 25 53 am" src="https://user-images.githubusercontent.com/18536626/41174396-e1f185e8-6b0e-11e8-91ad-ba0304a61973.png">





Label was not seen in the UI or in kubectl describe node
```
> kubectl describe node soumyacustombugtest-01
Name:               soumyacustombugtest-01
Roles:              controlplane,etcd,worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=soumyacustombugtest-01
                    node-role.kubernetes.io/controlplane=true
                    node-role.kubernetes.io/etcd=true
                    node-role.kubernetes.io/worker=true

```

**Comment by sangeethah** [comment]
Tested with latest build from master:

Able to add host labels using  "--label" parameter in the host registration command.
