### ISSUE TITLE
acme-domain doesn't work with beta3 tech preview

### ISSUE THREAD

**Issue by bilalyasar** [rancher/rancher#12709]
currently latest tech preview doesn’t work with acme-domain

it just stucks
just create new machine from ec2 or gke and execute following command
`wget https://releases.rancher.com/install-docker/17.03.2.sh -O - | sh`
`docker run -d -p 80:80 -p 443:443 rancher/server:preview --acme-domain mycustomdomain.com`

**Comment by bilalyasar** [comment]
yes, i opened all ports 80 and 443

**Comment by bilalyasar** [comment]
@superseb any update on this?
you can easily reproduce it?

**Comment by gregkeys** [comment]
Im getting a similar result, whenever I add the --acme-domain flag I get a bunch of these in my logs 
`E0511 00:43:57.955986       1 generic_controller.go:204] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set`

**Comment by superseb** [comment]
@gregkeys Those are unrelated to Let's Encrypt integration.

Requirements for `--acme-domain` are:

- Given domain should have a internet resolvable IP address
- Port 80 on that IP address should be open to the world

Let me know if you are still experiencing issues.
