### ISSUE TITLE
As rancher/k8s:v1.10.0-rancher1-2 had released, when rancher/server:preview support v1.10.0-rancher1-2

### ISSUE THREAD

**Issue by yuanjinyong** [rancher/rancher#12708]
As rancher/k8s:v1.10.0-rancher1-2 had released, when rancher/server:preview support v1.10.0-rancher1-2.

github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go now is

const (
	K8sV18  = "v1.8.10-rancher1-1"
	K8sV19  = "v1.9.5-rancher1-1"
	K8sV110 = "v1.10.0-rancher1-1"
)

I just want the version that had fixed the following error:
Failed to start container manager: inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory

**Comment by deniseschannon** [comment]
This is already available in v2.0.0-beta3, which should be the preview tag. This can be found for any cluster using node pools or custom nodes. It's under "cluster options" when creating a cluster.
