### ISSUE TITLE
EBS - Volumes get created in a different zone ,when they get created using PVC created from EBS object store.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12704]
**Rancher versions: Build from master

**Steps to Reproduce:**
Create a custom cluster with cloud provider set to AWS.
Create a storage class using "Amazon EBS Disk" as provider.

Deploy a workload using volumes that gets created  using "Add new PVC " option from Storage object.

Workload is not able to start successfully and fails with this error - ```No nodes are available that match all of the predicates: NoVolumeZoneConflict (1).```

Volumes get created successfully in AWS side but gets created in a different zone as compared to where the AWS hosts's zone.

In my case , hosts are in "us-east-2a". Volumes get created in "us-east-2b".

This issue is not seen when I created a PVC from Storage object. And then deploy a workload with volumes using "Use an existing PVC"

**Comment by sangeethah** [comment]
This issue also reproduces when creating  PVC using and then deploying a workload with volumes using "Use an existing PVC".

**Comment by alena1108** [comment]
@kinarashah could you see if it's the same root cause as https://github.com/kubernetes/kubernetes/issues/54370, and is there any way to workaround it?

**Comment by yves-vogl** [comment]
How do you workaround this?

**Comment by loganhz** [comment]
Set volumeBindingMode: WaitForFirstConsumer in your storage class. it will work fine then.

https://github.com/kubernetes/kubernetes/issues/49906#issuecomment-533414857

Close in favor of https://github.com/rancher/rancher/issues/24082
