### ISSUE TITLE
Extra node gets created which is stuck in "registering" state when cluster has provider set to "aws".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12702]
Rancher versions: Build from master

Steps to reproduce the problem:
Create a custom cluster with cloud provider set to "aws".
Register 1 node to this cluster with all roles.

When cluster gets to "Active" state , there are 2 nodes being listed for this cluster.

1 node with "all" roles is stuck  in "registering" state.
1 node with "worker" role which is in "active" state.

This issue is also reproducible when creating cluster with "Amazon EC2" provider with provider set to "aws".

**Comment by sangeethah** [comment]
Tested with latest build from master.
Create a custom cluster with cloud provider set to "aws".
Register 3 node to this cluster with all roles.

When cluster gets to "Active" state , there are 2 nodes being listed for this cluster.
3  node with "all" roles is stuck in "active" state.
3 node with "worker" role which is in "active" state.

We still see an extra "worker" node getting added as a node to cluster.

**Comment by sangeethah** [comment]
Tested with latest build from master.
Create a custom cluster with cloud provider set to "aws".
Register 3 node to this cluster with all roles.
There are no extra worker nodes getting  created. 
All 3 nodes get to "active" state and cluster gets to "active" state.

**Comment by shirgaveranjeet** [comment]
I am still facing this issue 
![capture](https://user-images.githubusercontent.com/24538452/39513078-60ae10ec-4df3-11e8-971a-1b38ca32621a.PNG)

**Comment by zhming0** [comment]
I am experiencing the same issue too. 
brand new cluster with provider set as AWS. Met all requirement of prerequisite.

The first etcd node stuck in `registering` state. 
The rancher agent logs on the etcd node shows:

```
time="2019-08-10T13:11:53Z" level=info msg="Connecting to wss://XXXX.XXX.XX/v3/connect with token XXXXXXXXXXXXXXXXXXXXXXx"
time="2019-08-10T13:11:53Z" level=info msg="Connecting to proxy" url="wss://XXXX.XXX.XX/v3/connect"
time="2019-08-10T13:11:54Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-08-10T13:11:54Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

**Comment by satomic** [comment]
- I met the problem that the all node ( one `control/etcd` role and two `worker` roles ) stuck with `Waiting to register with Kubernetes`.
- and based on the info from above @zhming0 , I try to udpate cluster's cloud provider config para from `aws` to  `none`
- the `control/etcd` role become `active` almost as soon as I update the cloud provider with `none`
- and the two `worker` roles look like try their best to registe them to rancher, but with some other error `[container runtime status check may not have completed yet., Missing node capacity for resources: ephemeral-storage]` come


`

**Comment by satomic** [comment]
version `master-head` has no such problem even you config the cloud provider with `Amazon`, maybe you can have a try... @zhming0 
![image](https://user-images.githubusercontent.com/9782493/64276577-e9623d00-cf7a-11e9-9737-7fe23239c457.png)
