### ISSUE TITLE
Rancher2 - Load balance requests between pods with session affinity if needed

### ISSUE THREAD

**Issue by linuxidefix** [rancher/rancher#12719]
*Problem*
I would like to load balance the traffic between my pod instances with session affinity.

By default, the sessionAffinity is set to _none_ that means requests are randomly redirected to pods.
Which causes problems with no stateless web applications as a session is lost when request is redirected to a wrong pod.
![racnher2-conf-workload-screenshot-35 195 31 53-2018-04-16-01-47-09](https://user-images.githubusercontent.com/836182/38784858-89f7f2d4-4118-11e8-93eb-6c527e100ba4.png)

As I am using Google Cloud I am enable to modify the loadbalancer service's yaml and set sessionAffinity to ClientIP and it worked. With 2 different ips , requests are loadbalanced between my pods and stick to the same node for the configured amount of time.

![rancher2-loadbalancer-siteconf](https://user-images.githubusercontent.com/836182/38784867-a9811054-4118-11e8-8a6c-01f21632e3dc.png)

test values:
```
 sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 30
  type: LoadBalancer
```
*How to reproduce*

- Create a pod with at least 2 instances of it.
- Choose "loadbalancer"
- Run a lot a requests and check that traffic does not always go to the same instance.

- Or if you use Google Cloud platform:  kubernetes engine > "Discovery & load balancing" and check the yaml generated file by RKE.

Maybe I am doing it wrong.
It would be nice to propose this option (with a timeout) or activate it by default.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta3` UI: `v2.0.35` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by alena1108** [comment]
We are going to address it by letting user to create LB service explicitly via Services tab. Enabling LB port via workloads will not carry any extra options, as its intent was the most basic configuration. Going to keep track of this issue in https://github.com/rancher/rancher/issues/15070
