### ISSUE TITLE
Rancher Compose Config Variable Mgmt

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1271]
Rancher needs to be able to support a way to define variables in the compose template itself so they can be replaced with user-specified values when the service is created and started.  This will allow Rancher compose templates to be re-usable with having to duplicate them.

**Comment by pwFoo** [comment]
Great feature to deploy services from one template with different passwords, ...

**Comment by aruneli** [comment]
This is not working in below release. Referencing #1868 
```
Component 	Version
Rancher 	v0.41.0-rc1
Cattle 	v0.99.0
User Interface 	v0.55.0
Rancher Compose 	beta/latest
```

**Comment by aruneli** [comment]
Verified in compose release v0.4.1-rc2
