### ISSUE TITLE
Where is the full doc ?

### ISSUE THREAD

**Issue by meandus** [rancher/rancher#12715]
Hi

For a begineer there is nothing clear !
What is a sidecar? What is a workload ? Where are container ? Where is the full doc ?
Why there are a lot of difference between alpha and beta ? Why is there nothing about kubernetes in the doc ? Kubectl get pods ... nothing ...
Why rancher catalog is seen as empty ...same for communtiy. Impossible to import a yaml because button is disabled ...

Remy

**Comment by vincent99** [comment]
You're looking at a beta.  Docs are in progress.  Things are broken and bring worked on.  Kubernetes has its own documentation.

**Comment by superseb** [comment]
Till the docs are there you can also ask questions in the [forums](https://forums.rancher.com/)
