### ISSUE TITLE
[question/feature_request] Is it possible to test LDAP settings without disabling authentication?

### ISSUE THREAD

**Issue by ocelotsloth** [rancher/rancher#12716]
**Rancher versions:**
rancher/server: v1.6.9

While trying to work out an issue with our LDAP configuration, there does not appear to be any way to test it out (or even access the menu) without first disabling access control all together.

Is there a way to check these settings without opening up the interface for anybody to gain access? If not, can we get some kind of LDAP test page which is separate from the running configuration?

**Comment by vincent99** [comment]
In 1.x, only AD has the option to edit while enabled.  This is unlikely to change,  LDAP is still in Java and storing two configs isonly in the Golang auth service.  An easy way to test a config is with a new empty server container.  You can also actually edit the config in the API without testing, if you're feeling lucky or after verifying it with a separate server.

In 2.0, local is always on so you can't disable everything, and all drivers support edit.  But LDAP is not going to be in 2.0.0.
