### ISSUE TITLE
Load balancer auto guess service port from conatiner

### ISSUE THREAD

**Issue by codejamninja** [rancher/rancher#12717]
It would be nice if the load balancer would automatically guess the port of the service from the container instead of just using port 80

**Comment by alena1108** [comment]
@codejamninja container can expose more than one port, so we have to be explicit about it. Plus it's k8s standard behavior.

**Comment by deniseschannon** [comment]
@codejamninja Rancher 2.0 is based on Kubernetes (k8s). 

https://rancher.com/what-is-rancher/overview/

As this is standard k8s practice, we won't be changing this.
