### ISSUE TITLE
Force unhealthy state in short lived container if command returns code = 1

### ISSUE THREAD

**Issue by phackwer** [rancher/rancher#12727]
Hi! I've setup my container to run a small script that exits with code 1 in case it fails to run. Problem is that it's not marking the "upgrade" as failed. Basically, this container is a copy of the application container, but with super user in DB so it can run migrations. I call a script custom made that dumps the DB, and them run migrations. If it fails on running migrations, it restores the DB from the dumped database, and at the end stores it in an Azure Storage Container. Problem is that, in some cases, migrations may fail, but the only way to know it is by opening the container logs and check it manually. We wanted to mark the upgrade as failed and trigger that visually in rancher. Why can't rancher see that the command failed?

**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 Ubuntu 16.04.3 LTS (with KVM) (4.13.0)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, separate docker host, DB in Azure MySQL DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a container and set it to run a command that should exit with code = 1

**Results:**
Rancher should mark the container as failed, as the command exited with code <> 0

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
