### ISSUE TITLE
rancher add host not showing on UI

### ISSUE THREAD

**Issue by corn1ng** [rancher/rancher#12726]
Docker version 18.03.0-ce, build 0520e24

**Comment by superseb** [comment]
Can you supply the info requested in the issue template? At least the used `rancher/server` image.

**Comment by corn1ng** [comment]
sorry, the info of rancher is 
[
    {
        "Id": "sha256:3241b497d181f04d1215d3bcc92b68ba2b66f5b02cf3c020a80f5b40a3bfb6de",
        "RepoTags": [
            "rancher/server:stable"
        ],
        "RepoDigests": [
            "rancher/server@sha256:4119159ed0f5a53c79af5d0eaa4c7de31c42bd411eac4756f8e2ce56fb37b43a"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-04-05T19:38:27.248096351Z",
        "Container": "effd3589f1223b71cecae6009f0a98f17e9cbb1e162ed3a50cb892a797fae42d",
        "ContainerConfig": {
            "Hostname": "02285a6d2a7c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "DEBIAN_FRONTEND=noninteractive",
                "CATTLE_HOME=/var/lib/cattle",
                "CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8",
                "CATTLE_DB_CATTLE_DATABASE=mysql",
                "CATTLE_USE_LOCAL_ARTIFACTS=true",
                "no_proxy=localhost,127.0.0.1,localaddress,.localdomain.com",
                "S6_SERVICE_DIR=/service",
                "CATTLE_HOST_API_PROXY_MODE=embedded",
                "CATTLE_RANCHER_SERVER_VERSION=v1.6.16",
                "DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/1.6.42",
                "CATTLE_CATTLE_VERSION=v0.183.46",
                "CATTLE_RANCHER_CLI_VERSION=v0.6.8",
                "CATTLE_RANCHER_COMPOSE_VERSION=v0.12.5",
                "DEFAULT_CATTLE_CATALOG_URL={\"catalogs\":{\"community\":{\"url\":\"https://git.rancher.io/community-catalog.git\",\"branch\":\"master\"},\"library\":{\"url\":\"https://git.rancher.io/rancher-catalog.git\",\"branch\":\"${RELEASE}\"}}}",
                "DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz",
                "DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-darwin-amd64-v0.12.5.tar.gz",
                "DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-windows-386-v0.12.5.zip",
                "DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v0.6.8/rancher-linux-amd64-v0.6.8.tar.gz",
                "DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v0.6.8/rancher-darwin-amd64-v0.6.8.tar.gz",
                "DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v0.6.8/rancher-windows-386-v0.6.8.zip",
                "DEFAULT_CATTLE_API_UI_JS_URL=/api-ui/ui.min.js",
                "DEFAULT_CATTLE_API_UI_CSS_URL=/api-ui/ui.min.css",
                "DEFAULT_CATTLE_MACHINE_EXECUTE=true",
                "DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true",
                "DEFAULT_CATTLE_CATALOG_EXECUTE=true",
                "DEFAULT_CATTLE_AUTH_SERVICE_EXECUTE=true",
                "DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true",
                "DEFAULT_CATTLE_SECRETS_API_EXECUTE=true",
                "CATTLE_RANCHER_SERVER_IMAGE=rancher/server"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/usr/bin/s6-svscan\" \"/service\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:b10268c22a892d5d2ca02f46ee7f10365fef5de1382cfec166a9bd4267289f45",
            "Volumes": {
                "/var/lib/cattle": {},
                "/var/lib/mysql": {},
                "/var/log/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/entry"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "17.12.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "02285a6d2a7c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "DEBIAN_FRONTEND=noninteractive",
                "CATTLE_HOME=/var/lib/cattle",
                "CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8",
                "CATTLE_DB_CATTLE_DATABASE=mysql",
                "CATTLE_USE_LOCAL_ARTIFACTS=true",
                "no_proxy=localhost,127.0.0.1,localaddress,.localdomain.com",
                "S6_SERVICE_DIR=/service",
                "CATTLE_HOST_API_PROXY_MODE=embedded",
                "CATTLE_RANCHER_SERVER_VERSION=v1.6.16",
                "DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/1.6.42",
                "CATTLE_CATTLE_VERSION=v0.183.46",
                "CATTLE_RANCHER_CLI_VERSION=v0.6.8",
                "CATTLE_RANCHER_COMPOSE_VERSION=v0.12.5",
                "DEFAULT_CATTLE_CATALOG_URL={\"catalogs\":{\"community\":{\"url\":\"https://git.rancher.io/community-catalog.git\",\"branch\":\"master\"},\"library\":{\"url\":\"https://git.rancher.io/rancher-catalog.git\",\"branch\":\"${RELEASE}\"}}}",
                "DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz",
                "DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-darwin-amd64-v0.12.5.tar.gz",
                "DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-windows-386-v0.12.5.zip",
                "DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v0.6.8/rancher-linux-amd64-v0.6.8.tar.gz",
                "DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v0.6.8/rancher-darwin-amd64-v0.6.8.tar.gz",
                "DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v0.6.8/rancher-windows-386-v0.6.8.zip",
                "DEFAULT_CATTLE_API_UI_JS_URL=/api-ui/ui.min.js",
                "DEFAULT_CATTLE_API_UI_CSS_URL=/api-ui/ui.min.css",
                "DEFAULT_CATTLE_MACHINE_EXECUTE=true",
                "DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true",
                "DEFAULT_CATTLE_CATALOG_EXECUTE=true",
                "DEFAULT_CATTLE_AUTH_SERVICE_EXECUTE=true",
                "DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true",
                "DEFAULT_CATTLE_SECRETS_API_EXECUTE=true",
                "CATTLE_RANCHER_SERVER_IMAGE=rancher/server"
            ],
            "Cmd": [
                "/usr/bin/s6-svscan",
                "/service"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:b10268c22a892d5d2ca02f46ee7f10365fef5de1382cfec166a9bd4267289f45",
            "Volumes": {
                "/var/lib/cattle": {},
                "/var/lib/mysql": {},
                "/var/log/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/entry"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1086540193,
        "VirtualSize": 1086540193,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/02beec06d07615765d74566c07e941c6239b3ef4959029b74ec9c4317f3e659e/diff:/var/lib/docker/overlay2/cad27c8d736496e7f205c298a2b1493987c7ad65ddc69fa11646a08c93a1cffe/diff:/var/lib/docker/overlay2/bede30424b0845356ed35db95f2616b52e1bde534f8bea9e3640e905a1336b4d/diff:/var/lib/docker/overlay2/7bfbddaea15e0f579a6869ed4278de3f838bf3f68deb5213eef64df1051fdb3a/diff:/var/lib/docker/overlay2/ddf547c4be7dc9ce21b2da9f9f2a77a1eff1e519336f5fb1fa438226cad9101e/diff:/var/lib/docker/overlay2/8be7700bf846336ade64cd08b8a0c5828bd803f82396d768c9a974f55bcbec33/diff:/var/lib/docker/overlay2/b92b3c2beabb56da08c2c0f44f2bdf4a4fd887e0cae3a8c27773dcb97f574fad/diff:/var/lib/docker/overlay2/761eddf50e10e9177c205e265d9d8e5cffb42c27c393800d229522d020d1a1e8/diff:/var/lib/docker/overlay2/47537896feebc193181d57ab3773a71e76204068f8e2bc4f0b78dcd0b75b7293/diff:/var/lib/docker/overlay2/c302d411cad6457379027e599b780fc95b940298369e5d4a964465f2c44d42ef/diff:/var/lib/docker/overlay2/1ab2bbe1436e8168d481013e3c087a37b68b9edb2edf739f722736398179618f/diff:/var/lib/docker/overlay2/becfb3ad74be1cdaaeea2f40fe9d2bfcc6f5095ce54cc02f4418d89467a8f641/diff:/var/lib/docker/overlay2/ab894edeab0ab89eb9a439257d0401a1568fa9b79fb7eb1d30966cfa8201f51f/diff:/var/lib/docker/overlay2/12ad87de1998d667b0c742e5df17f9611efaf91a9f69060b3469b1fe3e06a407/diff:/var/lib/docker/overlay2/f90d6149ed429858549c8021ad46d3fe36476ca03a993279bdd7b7c96cf13ec1/diff:/var/lib/docker/overlay2/cfc6016cbd51d3efecf871ccc9e51e15c0f7dd256811c4f5cb1c12e7d4b27a47/diff:/var/lib/docker/overlay2/f9a2fad0d7169c9a8427511b1ffa2b043825cb9c094d2934021089806476cd85/diff:/var/lib/docker/overlay2/1debd105827f1f1743f1997642cbdb893ac63d05baa43698de3a189f008f9249/diff:/var/lib/docker/overlay2/9fcd175e444dda80c7ac1c81ce3e6b74d0b49cfff4dfc974936ec0bcd5e02282/diff:/var/lib/docker/overlay2/cd5356e027e6a77cea7bb4347cc4dc03f3e1d58026fc7c356f14949e8ea77c16/diff",
                "MergedDir": "/var/lib/docker/overlay2/264a1abe1012207e9e24cc2a610b393f278600fd62a654ecd52caa3b5e739b9d/merged",
                "UpperDir": "/var/lib/docker/overlay2/264a1abe1012207e9e24cc2a610b393f278600fd62a654ecd52caa3b5e739b9d/diff",
                "WorkDir": "/var/lib/docker/overlay2/264a1abe1012207e9e24cc2a610b393f278600fd62a654ecd52caa3b5e739b9d/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:c47d9b229ca4eaf5d3b85b6fa7f794d00910a42634dd0fd5107a9a937b13b20f",
                "sha256:bf59e7acf5c4eefb6b27e7973a8afa6214f7a6da99c20a94195665ab52d442b2",
                "sha256:48daf661d621ef19b6df743b9fcfcb50044ba34d0b8b5161f4061dba49902e9b",
                "sha256:4e1e6ac5b9d6cde7dabfdaa6a0e8f5a8986c4f8bb63689085fdfaca0ccae698d",
                "sha256:7fb9ba64f896b3a7001af9604a44243cfa663c84e414cd298ee8bc754feb5aa1",
                "sha256:a0374ccb2717cea9cbea4fbdccddb5bdfebdea8079cae7ad1bc0f4bd2cc86b6d",
                "sha256:5f0af07aaa9892f6448fe416d97ee10d44429a5b9443a9ab7aa6456438d92440",
                "sha256:26451ab2c5aa0cd4014381af641cd55e6b271b417fb626bb96aa7ffef6ebf419",
                "sha256:f2b2049b3d11712f89ddf615fb1c41be7a080ca417caefa3e8d2c8688ea5afa5",
                "sha256:fadf1fad35886b8ab2482e1f7341f4012f0bb7fb2b3828b8fe706c26994f20e2",
                "sha256:a043c4b98f6259a75ec45a345da45a2589d43c0c3dad05bcfa90b53a2ca292cd",
                "sha256:989ab7dea3b3b22a60bcbe6f4e1c6a1ccc3880fe3a55df5f283f2e830c1a3a19",
                "sha256:a323a92602a5e8d2c9c53fea33ee635bf037981a8dcb724c5c56009951e1a77e",
                "sha256:b9638ccdd8f0b381a623c94a9f4bc7dbce3f56c27e82feae8b3369fa32fef280",
                "sha256:1b16cbee134565187457316080cd52ccfbe533f1182df70d9f40670c88108ab9",
                "sha256:5963c00251d94d1b6e476dffe0e66aeecc96ae6fc7ba64f2e15044fd89958001",
                "sha256:670314255c4070a493b0b808f6aa2f8c0c50e25ab167936d12956ddb702f2401",
                "sha256:134fd99bdc00cee81a1078e4269b1a5a01b44228fcef8fd0a78e721f5df11856",
                "sha256:8319abae0b99dce35dde529fae386c00c0c4770b71bfe8c548ba48e14ebeb79b",
                "sha256:5d789a1d5536161b5af1990afed0425ac8374f50437a0f4110e04ada0a4d2f58",
                "sha256:358126012918e9c33e9142f198d90d64bd5b77187b00cbd7cd43253d8b2cf8d3"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by superseb** [comment]
Support for `18.03` was added in `v1.6.17` but I don't think there are any breaking changes in between. What does `docker logs rancher-agent` say on the host you are trying to add?

**Comment by corn1ng** [comment]
Sorry, i am new in docker.
the log of rancher-agent has an error below.
ERROR: DNS Checking loopback IP address 127.0.0.0/8, localhost or ::1 configured as the DNS server on the host file /etc/resolv.conf, can’t accept it

**Comment by superseb** [comment]
Ok, the description on how to fix that is here: https://rancher.com/docs/rancher/v1.6/en/faqs/agents/#reference-to-localhost-present-in-etcresolvconf

**Comment by corn1ng** [comment]
Thanks, sir
I found solution in https://github.com/rancher/rancher/issues/10371
