### ISSUE TITLE
Catalog - Catalogs is updated with the latest commit but the Catalog Apps chart is not showing the latest one.

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12722]
Rancher versions: 2.0 master 04/16
Steps to Reproduce:
1. add custom catalog e.g., https://github.com/guangbochen/rancher-catalog.git - branch: 2.0
2. Go to Catalog Apps and select the WordPress chart
4. modify the Q&A of the Wordpress chart and push the commit
5. The catalog is updated, but the v3/templates only includes the old chart and templates.

Expected Results: showing the latest version after modifying the chart

**Comment by vincent99** [comment]
Resyncing is currently intentionally disabled in the backend because the way it is implemented cna cause etcd to chew up RAM and become unresponsive.

**Comment by guangbochen** [comment]
Version - 2.0 master 04/19
Verified fixed.
