### ISSUE TITLE
Fail to create cluster using DO

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12725]
**Rancher versions:**
rancher/server:master 04/16

**Steps to Reproduce:**
1. Run rancher server on DO.
2. Add Cluster using DO with 2 nodes, one with etcd and control role, another with worker role.
![image](https://user-images.githubusercontent.com/1213386/38803436-d007f470-41a1-11e8-819a-c7c6fb5b73c4.png)

3. The cluster stuck in provisioning with error message: 
`[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [206.189.86.208]: Get https://localhost:6443/healthz: can not build dialer to 1c-d6vg2:m-g69nn`
![image](https://user-images.githubusercontent.com/1213386/38803470-ea9040a4-41a1-11e8-9be8-9c15baa20aa3.png)

**Results:**

**Comment by feffi** [comment]
running on vsphere i got the same behaviour when using custom CA and cert. Without certs, it seems ok. Have not tried spanning master/worker/etcd in different node pools yet.
