### ISSUE TITLE
How I can reset host nodes ?

### ISSUE THREAD

**Issue by eportico** [rancher/rancher#12723]
I use host in previous rancher versions for testing. Now, I can't reuse them for new rancher version. I'm reset hosts removing dockers.

service docker stop
rm -rf /var/lib/docker/* 
rm -rf /var/lib/rancher/*
service docker start

but In rancher 2.0 when I add hosts, the cluster is waiting provisioning forever

This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
[remove/rke-log-linker] Successfully removed container on host [172.25.1.59]

**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by superseb** [comment]
This will be documented, for now you can use:

```
#!/bin/sh
docker rm -f $(docker ps -qa)
docker volume rm $(docker volume ls -q)
cleanupdirs="/var/lib/etcd /etc/kubernetes /etc/cni /opt/cni /var/lib/cni /var/run/calico"
for dir in $cleanupdirs; do
  echo "Removing $dir"
  rm -rf $dir
done
```

https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d

**Comment by eportico** [comment]
Work! Thanks.
