### ISSUE TITLE
Event triggers

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1273]
Rancher needs to support the notion of allowing users to specify "triggers" based on Rancher events (i.e. container start, host add, host label, etc) for launching services and containers.  For example:
- on "host add", please start a container under this service (this is already achieved by our global policy). 
- when a health checks hits a certain threshold, please start a new container.
- when a volume has been requested, please start a container from the volume service to be launched on this host.

**Comment by vincent99** [comment]
@will-chan Isn't this the same as #52?

**Comment by will-chan** [comment]
Using #52 to track this.
