### ISSUE TITLE
Delete button is inactive after selecting clusters/node templates for deletion

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12735]
**Rancher versions:**
rancher/server: master 4/16 (id: ff5e95255ecf)

**Steps to Reproduce:**
Create any type of cluster(s)
Delete button should be inactive
In the Global > Clusters list, select the checkbox of some number of clusters.
Delete button should become active
Click the delete button above.

Also occurs in Node Templates

**Results:**
Delete button is inactive, and the cursor changes to the 'inactive' cursor. Clusters can still be deleted from their context menus. 

<img width="629" alt="screen shot 2018-04-16 at 9 37 14 am" src="https://user-images.githubusercontent.com/21316915/38823099-513f399c-415a-11e8-9094-8598888a1794.png">

**Comment by bmdepesa** [comment]
Same issue is occuring with Node Templates.

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/ui/pull/1822

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/17
Verified fixed
