### ISSUE TITLE
Cannot provision GCE cluster - Invalid value for field "cluster.name"

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12734]
**Rancher versions:**
rancher/server: master 4/16 (id: ff5e95255ecf)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE

**Steps to Reproduce:**
Create GCE cluster in Rancher UI

**Results:**
On provisioning, receive an error: 

> Googleapi: Error 400: Invalid value for field "cluster.name": "1c-gkbfv". Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,38}[a-z0-9])?)' (only alphanumerics and '-' allowed, must start with a letter and end with an alphanumeric, and must be no longer than 40 characters)., badRequest

Logs: 
>2018/04/16 16:22:33 [INFO] Provisioning cluster [1c-gkbfv]
2018/04/16 16:22:33 [INFO] Creating cluster [1c-gkbfv]
E0416 16:22:33.708594       1 generic_controller.go:204] ClusterRoleTemplateBindingController 1c-gkbfv/creator [mgmt-auth-crtb-controller] failed with : couldn't create role cluster-owner: roles.rbac.authorization.k8s.io "cluster-owner" already exists
2018/04/16 16:23:03 [INFO] Provisioning cluster [1c-gkbfv]
2018/04/16 16:23:03 [INFO] Creating cluster [1c-gkbfv]
2018/04/16 16:24:03 [INFO] Provisioning cluster [1c-gkbfv]
2018/04/16 16:24:03 [INFO] Creating cluster [1c-gkbfv]
2018-04-16 16:25:12.014441 I | mvcc: store.index: compact 903469
2018-04-16 16:25:12.030861 I | mvcc: finished scheduled compaction at 903469 (took 7.853184ms)
2018/04/16 16:26:07 [INFO] Provisioning cluster [1c-gkbfv]
2018/04/16 16:26:07 [INFO] Creating cluster [1c-gkbfv]
2018-04-16 16:30:12.028009 I | mvcc: store.index: compact 904663
2018-04-16 16:30:12.034746 I | mvcc: finished scheduled compaction at 904663 (took 4.490106ms)
2018/04/16 16:30:15 [INFO] Provisioning cluster [1c-gkbfv]
2018/04/16 16:30:15 [INFO] Creating cluster [1c-gkbfv]

UI:
<img width="1280" alt="screen shot 2018-04-16 at 9 30 20 am" src="https://user-images.githubusercontent.com/21316915/38822723-2aaea70a-4159-11e8-8ad3-6e95811020ad.png">

**Comment by tfiduccia** [comment]
It's working on newest version of master

**Comment by bmdepesa** [comment]
Confirmed working on master 4/17 (id - 6e9ea1f99c18)

**Comment by kaizer1** [comment]
So there is no answer to this question ???? Actually, there is such a mistake and how to create a name is not clear
 [-los-wefsde209883-7]  - not working 
[a-sakdjhfkjashdf-29837498] - not working 
[a-b-5] - not working 

ALL NOT WORKING!!! All you need to specify is a normal example.
