### ISSUE TITLE
Add collect "Audit Log" in 2.0

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12733]
In 1.x, we have "Audit Log" in the admin tab that tracks what API calls each user makes. 

We should add something similar to 2.0

**Comment by chrisurwin** [comment]
We should enhance what we have in 1.x to enable events to be forwarded to/stored in an external store as long term audit is a requirement for enterprises.

**Comment by aiwantaozi** [comment]
related gist: https://gist.github.com/aiwantaozi/9e55c083525d5c58b8f722b528076c89

**Comment by aiwantaozi** [comment]
need UI help for:
1. add audit log config under global level security tab, the page similar to cluster level logging, but change embedd logging to mysql
2. in add cluster, is the global logging is enable and the provider is rke, then enable the audit log config by default and add the audit log config to the api server in api

```
{
    "type": "cluster",
    "googleKubernetesEngineConfig": null,
    "name": "mytest",
    "rancherKubernetesEngineConfig": {
        ...
        "services": {
            "type": "rkeConfigServices",
            "kubeApi": {
                "extra_args": {
                    "audit-log-path": "/var/lib/rancher/k8s/auditlog/kube-apiserver-audit.log",
                    "audit-policy-file": /opt/rke/audit-log-policy.yml
                },
            },
            ...
        }
    }
}
```

**Comment by aiwantaozi** [comment]
Update this feature if for collect rancher api level audit log, latest doc is https://gist.github.com/aiwantaozi/bebee6c3f17b05d4552dc78cf7cd430c

**Comment by aiwantaozi** [comment]
https://github.com/aiwantaozi/docs/commit/420539926ad7d1b45113a28c1d9f593ee806953c

**Comment by adingilloRancher** [comment]
Master 6/8

Completed test pass
