### ISSUE TITLE
Pipeline failing to connect to Jenkins on GCE/AWS cluster

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12741]
**Rancher versions:**
rancher/server: master 4/16 (id: ff5e95255ecf)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE/AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher

**Steps to Reproduce:**
Create cluster in GCE
Enable pipeline
Create a pipeline in project
Execute pipeline

**Results:**
Pipeline execution fails with:
>fail to connect Jenkins: Get http://10.27.250.250:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Logs: 
>2018/04/16 17:22:22 [INFO] Updating service [jenkins] with public endpoints [[{"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true}]]
2018/04/16 17:22:22 [INFO] Updating service [jenkins-agent] with public endpoints [[{"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true}]]
2018/04/16 17:22:22 [INFO] Updating workload [cattle-pipeline/jenkins] with public endpoints [[{"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true},{"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true}]]
2018/04/16 17:22:22 [INFO] Updating workload [cattle-pipeline/jenkins] with public endpoints [[{"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true},{"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true}]]
2018/04/16 17:22:22 [INFO] Updating pod [cattle-pipeline/jenkins-546b98c749-hvkzg] with public endpoints [[{"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true},{"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true}]]
2018/04/16 17:22:22 [INFO] Updating workload [cattle-pipeline/jenkins] with public endpoints [[{"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true},{"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true}]]
2018/04/16 17:22:22 [INFO] Updating pod [cattle-pipeline/jenkins-546b98c749-hvkzg] with public endpoints [[{"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true},{"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true}]]
2018/04/16 17:22:22 [INFO] Updating workload [cattle-pipeline/jenkins] with public endpoints [[{"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true},{"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true}]]
2018/04/16 17:22:22 [INFO] Updating node [gke-brandon-cluster1-default-pool-e076901c-c2ps] with public endpoints [[{"nodeName":"1c-7xzzb:machine-57whc","addresses":["35.197.9.57"],"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true},{"nodeName":"1c-7xzzb:machine-57whc","addresses":["35.197.9.57"],"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true},{"nodeName":"1c-7xzzb:machine-57whc","addresses":["35.197.9.57"],"port":32462,"protocol":"TCP","serviceName":"kube-system:default-http-backend","allNodes":true}]]
2018/04/16 17:22:23 [INFO] Updating node [gke-brandon-cluster1-default-pool-e076901c-38hl] with public endpoints [[{"nodeName":"1c-7xzzb:machine-t8xfv","addresses":["35.203.143.140"],"port":32462,"protocol":"TCP","serviceName":"kube-system:default-http-backend","allNodes":true},{"nodeName":"1c-7xzzb:machine-t8xfv","addresses":["35.203.143.140"],"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true},{"nodeName":"1c-7xzzb:machine-t8xfv","addresses":["35.203.143.140"],"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true}]]
2018/04/16 17:22:30 [INFO] Updating node [gke-brandon-cluster1-default-pool-e076901c-qn4x] with public endpoints [[{"nodeName":"1c-7xzzb:machine-t2p2k","addresses":["35.203.131.87"],"port":32462,"protocol":"TCP","serviceName":"kube-system:default-http-backend","allNodes":true},{"nodeName":"1c-7xzzb:machine-t2p2k","addresses":["35.203.131.87"],"port":32441,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins","allNodes":true},{"nodeName":"1c-7xzzb:machine-t2p2k","addresses":["35.203.131.87"],"port":32722,"protocol":"TCP","serviceName":"cattle-pipeline:jenkins-agent","allNodes":true}]]
2018/04/16 17:22:56 [ERROR] Error get Jenkins engine - fail to connect Jenkins: Get http://10.27.250.250:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2018/04/16 17:23:00 [ERROR] Error get Jenkins engine - fail to connect Jenkins: Get http://10.27.250.250:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2018/04/16 17:23:00 [ERROR] Error get Jenkins engine - fail to connect Jenkins: Get http://10.27.250.250:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2018/04/16 17:23:00 [ERROR] Error update pipeline execution - Operation cannot be fulfilled on pipelineexecutions.management.cattle.io "1p-krwtt-1": the object has been modified; please apply your changes to the latest version and try again
2018/04/16 17:23:15 [ERROR] Error get Jenkins engine - fail to connect Jenkins: Get http://10.27.250.250:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E0416 17:24:39.996886       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.NodeStatus

<img width="1279" alt="screen shot 2018-04-16 at 10 26 26 am" src="https://user-images.githubusercontent.com/21316915/38825231-a82c0806-4160-11e8-9cf2-68939583a2af.png">

**Comment by bmdepesa** [comment]
This is also occurring on AWS clusters, with the same errors.

**Comment by bmdepesa** [comment]
I checked after 30m and the pipeline was able to execute. Is there some time required to copy credentials over?

**Comment by bmdepesa** [comment]
When I have seen this, the jenkins pod is pending and not ready. Closing.

**Comment by gitlawr** [comment]
I'm hitting this in new DO cluster now. Jenkins is up but the connection is failed. Will look into it.

**Comment by gitlawr** [comment]
It happens when `cattle-pipeline` is moved to a project (or other cases that `cattle-pipeline` & `cattle-system` lives in different projects)
The connection relys on agent in `cattle-system`, and the traffic is blocked by networkpolicy.
Closing as it is a different issue.
