### ISSUE TITLE
Service leader election

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1274]
Support the notion of supporting a "leader" container within a service.

**Comment by digitalLumberjack** [comment]
We should be able to generate a specific DNS entry for the leader. 

I have an issue today with the MogoDB HA where i am unable to detect the master from the fqdn of the service.

**Comment by will-chan** [comment]
We now have a notion of a create_index per service that can be referenced as a leader of a service.  If the leader goes down, you can simply pick the next number in sequence.
