### ISSUE TITLE
Rancher CLI

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1275]
Extend current rancher-compose CLI to a generic rancher CLI that can also make common Rancher API calls (crud hosts, crud services, etc).

**Comment by adamkdean** [comment]
Do we know when this might be available? This'll make deploying/upgrading with CI much easier

**Comment by flaccid** [comment]
+1

**Comment by faddat** [comment]
This is the right path :).

**Comment by flaccid** [comment]
Well not necessarily. @ibuildthecloud has already done the CLI client https://github.com/rancherio/cattle-cli which also gives a cattle module for use in your python codes. I'm just working this out now - it needs a bit more doc/examples.

A rancher CLI made in golang is ideal but it would just be a cli tool. When not using a rancher library for X language, the CLI tool does need to have some helper-like actions in it so you can use it in shell scripts arbitrarily e.g. get containers with this specific label and stop/remove them.

**Comment by adamkdean** [comment]
http://i.imgur.com/wZdIoGB.gif

**Comment by will-chan** [comment]
Closing issue.  All bugs should be filed separately.
