### ISSUE TITLE
Add API error codes that clearly indicate the different ways authentication has failed

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#12752]
These varying error codes will let the UI react and inform the user differently depending on the situation.
Probably need to coordinate with @vincent99 on what scenarios he cares about.

**Comment by deniseschannon** [comment]
From: https://github.com/rancher/rancher/issues/11214

- [ ] No password in field error message should say "Current Password required" and should be left justified.
![image](https://user-images.githubusercontent.com/11514927/35537554-d95771d0-0507-11e8-8783-7d5fc654d412.png)

- [ ] Incorrect password error message should be "Invalid Current Password" (Capitalize the first letter of each word) and should be left justified
![image](https://user-images.githubusercontent.com/11514927/35537624-1d08e486-0508-11e8-89f4-3f6cc375a4bd.png)
