### ISSUE TITLE
Rancher multi-node support

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1276]
Document how to run Rancher in a multi-node setup.  This also requires a multi-node support for go-machine-service and the api proxy.

**Comment by will-chan** [comment]
- Working on SSL for the web-proxy for single node
- Working on multi-node Rancher + web-proxy

**Comment by cloudnautique** [comment]
SSL mode for single node is documented.

Not a show stopper, but #1420 will make configuration more simple in multinode setup.

**Comment by will-chan** [comment]
Add documentation for multi-node setup.
