### ISSUE TITLE
flexvolume UI improve

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#12768]
**Rancher versions:**
rancher/server: 2.0
rancher/agent:

1. add clusterID and projectID, since the clusterName and projectName could use duplicated name, the final structure will look like
for volume:
{
"flexVolume": {
"driver": "cattle.io/log-aggregator",
"fsType": "ext4",
"options": {
"clusterID": "1c-xtpbh",
"clusterName": "t2",
"containerName": "mycontainerName1",
"format": "/^\\[(?<logtime>[^\\]]*)\\] (?<name>[^ ]*) (?<title>[^ ]*) (?<id>\\d*)$/",
"namespace": "newns",
"projectID": "project-2n2xq",
"projectName": "default",
"volumeName": "myVolumeName1",
"workloadName": "myworkloadName1"
},
"readOnly": false,
"type": "/v3/project/schemas/flexVolumeSource"
},
"name": "to be replace",
"type": "/v3/project/schemas/volume"
}

for volume mount:
"volumeMounts": [
{
"mountPath": "/var/flex",
"name": "to be replace",
"readOnly": false,
"type": "/v3/project/schemas/volumeMount"
}
]

2. change the format description to "Select your log format or input a regular expression could parse your log, the regular expression could test here", the link for the here is  http://fluentular.herokuapp.com/

3. not use container's log
"The path to your container's log directory.“ -> "Your log path inside the container"
"The format of your container's log." -> "The format of your log."

4. add more note.

"We will deploy a flexvolume driver to create a volume and mount the log to the host." -> "We will deploy a flexvolume driver to create a volume and mount the log to the host, this feature support on GKE cluster now.

**Comment by bmdepesa** [comment]
Validated on rancher/rancher:master 4/26. 

UI improvements are displayed correctly.
