### ISSUE TITLE
"Expand All" breaks Pod details page

### ISSUE THREAD

**Issue by crucksasaurus** [rancher/rancher#12772]
Clicking on the "Expand All" link seems to break the UI on the Pod details page.

Steps to reproduce:
1) Go to cluster
2) View workloads
3) Click on the green circle to view a pod
4) Click on "Expand All"
5) No other items work on the page; refresh to correct issue.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta1` UI: `v2.0.33` |
|Access|`local` `admin`|
|Route|`container`|

**Comment by tfiduccia** [comment]
@crucksasaurus - I can't reproduce this issue.  Can you please let me know if you have sidekicks or have filled out any of the info for the sections that are below the expand all.

**Comment by superseb** [comment]
Let us know if this still happens.
