### ISSUE TITLE
vSphere node template edit

### ISSUE THREAD

**Issue by gstorme** [rancher/rancher#12771]
**Rancher versions:**
rancher/server: v2.0.0-beta3

I created a vSphere node template, but I'm unable to edit the properties of it, is it possible to edit these after creation?

![image](https://user-images.githubusercontent.com/3859276/38869070-b6316628-4249-11e8-926a-ecaf5eba297b.png)

Also, the memory specs shown under the Size column is wrong. I specified 512 MB but it is shown as 512 GiB.

**Comment by tfiduccia** [comment]
@gstorme - version - 2.0 master 4/17.  Although edit wasn't available in beta.  It is now available in the newest master build.
