### ISSUE TITLE
cattle: cannot use pre-existing docker bridge network 

### ISSUE THREAD

**Issue by alexmtv** [rancher/rancher#12775]
**Rancher versions:**
rancher/server:v1.6.7
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:v0.3.0
ipsec:net:v0.1.3
network-services:v0.2.5
scheduler:v0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux 7 (Core), 3.10.0-693.11.1.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Virtual Environment 5.1-49
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 	v0.183.5
**Steps to Reproduce:**

1. docker network create my-net
2. create new stack with docker compose:
version: '2'
services:
  some-container:
    image: some-image
    networks:
      - somenet
networks:
  somenet:
    external:
      name: my-net

**Results:**
Rancher creates container with default network (10.42.x.x) without bridge

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
