### ISSUE TITLE
Events not logged in Splunk

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12774]
Version: Master 4/16/2018

Steps:
Deployed Splunk trial version
Added splunk endpoint and token

![screen shot 2018-04-17 at 8 34 26 am](https://user-images.githubusercontent.com/38012481/38880275-28c51e44-421a-11e8-9cdd-4fece914a23e.png)

Test curl
curl -k  https://input-prd-p-nm884bf46ds4.cloud.splunk.com:8088/services/collector/event -H "Authorization: Splunk ee6b789f-7032-4296-83cb-df3238e89147" -d '{"event": "hello world"}'

Result:
Unable to see any events in splunk. Able to reach my endpoint and token with test curl.

**Comment by aiwantaozi** [comment]
Hi @adingilloRancher The URL for your address should be https://input-prd-p-nm884bf46ds4.cloud.splunk.com:8088 , not need /services/collector/event, could you try?

**Comment by adingilloRancher** [comment]
@aiwantaozi I initially tried that URL and did not see any events logged in Splunk.

**Comment by adingilloRancher** [comment]
Master 4/24/18

Verified events logged in splunk
