### ISSUE TITLE
Config maps & Secrets not showing up in details page for workload

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12781]
**Rancher versions:** 2.0 master 4/17

**Steps to Reproduce:**
1.  Create a config map & Secret 
2.  In the environment variable section, add from source the config map and secret
3.  Launch and wait for it to become active
4. Click on workload and expand environment variable section

**Results:**  Config map & Secret not showing up.

**Comment by loganhz** [comment]
Added a Environments From Sources section
![image](https://user-images.githubusercontent.com/21168270/38912047-b2ea4270-4305-11e8-8467-b4e1a98312f6.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/18
Verified fixed
