### ISSUE TITLE
Cloud Provider Fixes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12787]
[ ] - For clusters using the Azure node driver, add in cloud provider support so that if you select it it would create a section of key value pairs that is already populated with keys from here: 
https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/rke_types.go#L331

[ ] For custom cluster, we should add in selections for the node drivers that we know about so it should look something like 

```
[ ] none
[ ] Amazon - this would populate it as `aws` (as it does with the EC2 driver)
[ ] Azure - selecting this would show key value pairs from the same azure list so that it shows up the keys and the user would have to do the values
[ ] Other - this shows what "generic" shows today
```

[ ] Add somewhere next to Cloud Provider with a link to "read more" and linking to https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/

**Comment by tfiduccia** [comment]
@deniseschannon What should the default be for this? None?

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/19
Verified fixed
