### ISSUE TITLE
Some agents goes down when one master goes down (HA 3 nodes)

### ISSUE THREAD

**Issue by anamornom** [rancher/rancher#12780]
**Rancher versions:**
rancher/server: rancher/server:stable
rancher/agent: rancher/agent:stable

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.6
ipsec:  rancher/net:v0.13.11
network-services:
          rancher/metadata:v0.10.2
          rancher/network-manager:v0.7.20
scheduler: 0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.12.6, build 1512168
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
OL7 - 4.1.12-103.7.3.el7uek.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, 3 masters
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Follow this installation guide: https://rancher.com/docs/rancher/latest/en/installing-rancher/installing-server/#multi-nodes
**Results:**
When I finish the process all seems to be ok. Rancher show the three nodes in the High availability menu (inside admin tab). I register hosts in environments without problem but when a master goes down some of rancher agents appear like dissconected. If I start again the master, the agents reconnect again.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
