### ISSUE TITLE
Docker volume and snapshots

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1278]
- Support Docker 1.7 support for volume plugins.
- Support creating snapshots of docker data volumes
- Support backing up snapshots to object store (S3) or NFS
- Support restoring data volumes from object store

**Comment by will-chan** [comment]
- Completed S3 test cases.
- Add more error-handling
- Improve locking so it doesn't lock on the backup/restore of the snapshot
- Add documentation
- Targe completion 7/8

**Comment by will-chan** [comment]
- CLI cleanup
- Remove locking on backup/restore
- Documentation

**Comment by will-chan** [comment]
* Indexing completed so can query by name
* Removed lock on backup/restore
* Removed Object store CLI requirements
* Add NFS support
* Add driver after starting volume service
* update CLI to latest
* Add packaging support

**Comment by will-chan** [comment]
* CLI is complete
* Static linking is done.  Need to be able to complete the packaging of rancher volume.
* Adding NFS driver
* Improve driver framework to allow adding additional drivers.
* Restructure code directory.

**Comment by will-chan** [comment]
* Code restructuring and documentation complete.
* NFS driver and driver framework (PR for next week)

**Comment by will-chan** [comment]
- NFS driver + generic volume driver framework done
- generic snapshot and backup framework  (PR)
- add packaging (PR)

**Comment by deniseschannon** [comment]
generic snapshot and backup framework done
add packaging (PR)

**Comment by will-chan** [comment]
- Start integration with Rancher to expose it via Rancher API

**Comment by will-chan** [comment]
- EBS Driver
