### ISSUE TITLE
Set state to Pending for the Load Balancer service till address is set

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12786]
Load Balancer service should become active only when it's addresses are populated by external cloud provider

**Comment by sangeethah** [comment]
Tested with latest build from master.

When Load balancer is created for a workload in a cluster that does not support this service ( like Digital Ocean provider) , service gets stuck in "Pending" state forever.

When Load balancer is created for a workload in a cluster  supports this service ( like aws cloud provider) , service gets to "active" state and load balancer is functional.
