### ISSUE TITLE
Warning Event Alerts Not Triggered

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12793]
**Rancher versions:**
Master 4/17/2018

Steps:
Create a cluster.
Add a warning alert for any type of event.
Create a workload that would trigger alert (Deployment etc.)

Results:
Alert is not triggered for "Warning". I was able to receive alerts for "Normal" events however.

**Comment by zionwu** [comment]
@adingilloRancher, I can't reproduce this issue on GKE:

I created an alert for warning pod:
![image](https://user-images.githubusercontent.com/1213386/38979222-29bd522a-43ec-11e8-9f3f-44e366a2ed1d.png)

I created a deployment with wrong image:
![image](https://user-images.githubusercontent.com/1213386/38979309-5bacbb54-43ec-11e8-8322-c278636e0f73.png)

Use kubectl get event can see there is warning event for pod:
![image](https://user-images.githubusercontent.com/1213386/38979360-7d9db7ae-43ec-11e8-9d74-de6632982a48.png)

And  the alert is triggered:
![image](https://user-images.githubusercontent.com/1213386/38979383-8e824828-43ec-11e8-9dbb-03da257aabc8.png)

![image](https://user-images.githubusercontent.com/1213386/38979390-93414922-43ec-11e8-8bb6-7a0579ff12fb.png)

**Comment by adingilloRancher** [comment]
Closing issue.
