### ISSUE TITLE
UI: Memory gauge in cluster dashboard is differs from cluster overview

### ISSUE THREAD

**Issue by dnauck** [rancher/rancher#12795]
**Rancher versions:**
rancher/server: v2.0.0-beta3
rancher/agent: v2.0.0-beta3

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.0-rancher1

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="RancherOS"
VERSION=v1.3.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.3.0
PRETTY_NAME="RancherOS v1.3.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

VMWare VMs

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher 2 Beta quickstart setup + 3 worker/etcd/controller nodes

**Steps to Reproduce:**

The cluster has 3 nodes a 8 GB RAM, as shown in the cluster list.

![image](https://user-images.githubusercontent.com/97584/38898694-061e9164-4296-11e8-88f5-2762ba28273a.png)

But the cluster dashboard shows only 7,7 GB ram (from one node?!)

![image](https://user-images.githubusercontent.com/97584/38898713-1516ddfc-4296-11e8-975c-ed5ed98e68b4.png)

**Comment by tfiduccia** [comment]
version 2.0 master 4/17
This is a bug.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/19
Verified fixed
