### ISSUE TITLE
Can't change docker registration once I entered one successfully

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12807]
**Rancher versions:** 2.0 master 4/17

**Steps to Reproduce:**
1.  Create a pipeline and register into docker in the publish section
2. Create another pipeline and go to publish section

**Results:**  Since I'm already registered, it doesn't show that option anymore, but if I want to send to a different registry I can't do that.  We should make it so that they can switch (maybe have a button to bring back?)

**Comment by biblesyme** [comment]
It works now, I am not sure what's wrong before, maybe something wrong with the registry module. But it should work fine now.
