### ISSUE TITLE
Weird white bar on command(shell) section of Build step for pipeline

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12801]
**Rancher versions:** 2.0 master 4/17

**Steps to Reproduce:**
1.  Click on Add Pipeline
2.  Add Repository and click on Add
3.  Click on Build "run a script" box

**Results:**Weird white line under line 1 and it looks like I have two shells terminals now.
![image](https://user-images.githubusercontent.com/11514927/38903195-9cc7680e-4258-11e8-8f0a-c66658578305.png)

**Comment by biblesyme** [comment]
@tfiduccia Can't reproduce it, could you more specify? Are you using the Chrome? Does it shows every time you open this page?

**Comment by tfiduccia** [comment]
@biblesyme - Yes I'm using Chrome on a Mac and it appears every time I open this page.

**Comment by biblesyme** [comment]
Ok, thanks,  @tfiduccia Have it disappeared now? I never saw this wired bar.

**Comment by tfiduccia** [comment]
@biblesyme  - yep, vincent changed it back to input-text-files.
