### ISSUE TITLE
EC2 instances that do not have the AWS cloud provider set will not be able to determine the public IP address 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12813]
Per @alena1108 from #11969 ```* Happens because no externalIP is being set in node.status.addresses; otherwise UI/controllers would pick the internal ip address for the public endpoint.

```

For RKE cluster w/o cloud provider, we might need to add special handling to figure out external IP. Perhaps from annotations passed to the node by rke.

**Comment by sangeethah** [comment]
Testes with latest build from master:

When creating Cluster with "Amazon EC2" drivers , nodes that get created have both address and internalAddress.
