### ISSUE TITLE
Agent Registration with SSL fails

### ISSUE THREAD

**Issue by sunnywader** [rancher/rancher#12812]
**Rancher versions:**
rancher/server: 1.6.16
rancher/agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: default
ipsec: default
network-services: default
scheduler: default
kubernetes (if applicable): default

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2.-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal, same linux version
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2 Nodes one has server other has agent
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
I am new to Rancher and linux certificates. Trying to run agent registration with SSL under V. 1.6.16, which is server:stable.

Keep getting this error:
INFO: Running Agent Registration Process, CATTLE_URL=https://<host-name>:8080/v1
INFO: Attempting to connect to: https://<host-name>:8080/v1
ERROR: https://<host-name>:8080/v1 is not accessible (server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none)

So here is the setup after reading several posts on same subject.
- This is CentOS 7
- Start command line: docker run -d --restart=unless-stopped -p 8080:8080 -v /etc/ssl/certs/rancher.crt:/var/lib/rancher/etc/ssl/ca.crt rancher/server
- Agent URL - docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.10 https://svdcpm1008:8080/v1/scripts/E1F56B5F232AD97E7EDA:1514678400000:hXq0nkYhxFxGgAIwwezSm7WpBc
- So created a self signed certificate with a self created random key and put it under /etc/ssl/certs/rancher.crt, CN used was hostname, which happens to be - svdcpm1008.nms.fnc.fujitsu.com (also tried just svdcpm1008)
- Did not do any of the update-ca-trust stuff, not yet, so certificate file has just one certificate
- Copied same file to agent host - /var/lib/rancher/etc/ssl/.
- Access Control is turned on (local)

Get the above error with agent registration URL with https, with http it goes through

Have looked at all kinds of documentation and specifically - https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/, I am new to linux certificates and hate them :) some questions:

- Prereq is CA certificate in PEM format, I am assuming this is self generated singular certificate with .crt extension (.pem not required, do I have to change extension)
- Prereq is signed by CA for Rancher Server, what is that, where is this so called certificate, what is command line to sign my certificate with this certificate
- An instance of NGINX server...to terminate... I just started server using above command line did not install anything else, do I have to (I did try adding --name=rancher-server to command line did not help)
- I do not see any directory /var/lib/rancher on my server host, find that weird
- I do see /var/lib/cattle/logs inside the container, is this where server log file are
- Sometimes I see a file host.key in one of the sub-directories, is this file needed for above registration, why is it generated

Any help appreciated.
thanks.
**Results:**
ERROR: https://<host-name>:8080/v1 is not accessible (server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none)

**Comment by hkeio** [comment]
I'm having the same problem. Running host and agent on a digital ocean droplet (installed with RancherOS 1.3.0, got 1.2.0 installed but upgraded to 1.4.0). Is there any workaround to get this fixed?

```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.32-rancher2
Operating System: RancherOS v1.4.0
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.855GiB
Name: lingdata-rancheros1
ID: ICDH:O6MY:6FCR:U572:OFKC:VDBY:EVBX:VBUQ:PBAX:YY45:6KDL:NO3V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by FlippingBinary** [comment]
I'm new to Rancher and ran into this problem with the current release of RancherOS as found on the releases download page (1.5.5). If anyone stumbles across this issue trying to find a solution, try connecting to Rancher server using http instead of https. I was surprised to discover the Rancher server actually responds to both protocols on the same port. After making the connection, you should be able to install Let's Encrypt and get a proper certificate.
