### ISSUE TITLE
Etcd service is abnormal after deleting one node

### ISSUE THREAD

**Issue by 694982827** [rancher/rancher#12810]
**Rancher versions:v1.6.17**
rancher/server:v1.6.17
rancher/agent:v1.2.10

**Infrastructure Stack versions:**
network-services:vxlan
kubernetes (if applicable):rancher/k8s:v1.10.0-rancher1-2

**Docker version: 17.03.2-ce**

**Operating system and kernel:ubuntu16.04,4.4.0-87-generic,,
**Type/provider of hosts: XenServer7.2**

**Environment Template: Kubernetes**

**Steps to Reproduce:**
When I add two nodes to rancher and everything is ok. 
Then I delete one node from Rancher UI 
**Results:**
the etced service  create containers constantly.
![image](https://user-images.githubusercontent.com/14134883/38910966-bfebf664-42fe-11e8-8901-cc83948066e8.png)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
