### ISSUE TITLE
Can't remove deployed catalog app when template is removed from catalog

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#12820]
**Rancher versions:**
rancher/server:2.0.0-beta3
rancher/agent:

Steps to reproduce:
Deploy an application from a catalog
remove the chart from the catalog and let it refresh
In the catalog app try to delete the deployed application.

The item gets stuck in a removing state:
![image](https://user-images.githubusercontent.com/13744596/38930201-fbb38402-4306-11e8-9875-10a670752f0b.png)

and the logs will show and error
```E0418 11:22:17.900592       1 generic_controller.go:204] AppController project-pn78j/wordpress-tg5rus [helm-controller] failed with : templateversions.management.cattle.io "helm-kubernetes-wordpress-1.0.2" not found```

The item never gets removed

**Comment by deniseschannon** [comment]
@chrisurwin Updated catalog backend and frontend was just added into master on the evening of 4/17. 

@guangbochen can you confirm if this is working now?

**Comment by guangbochen** [comment]
Version - 2.0 master 04/19
Verified fixed.

**Comment by lovedigit** [comment]
I am facing the same issue on v2.1.1 trying to remove wordpress catalog app.

**Comment by deniseschannon** [comment]
@lovedigit do you have any logs in your Rancher server when trying to remove it?

How are you trying to remove it? Are you removing the app, namespace or workload in the namespace?

**Comment by lovedigit** [comment]
I removed the wordpress catalog as well as the wordpress namesapce afterwards, when the pod created by catalog app didn't remove itself.
![capture](https://user-images.githubusercontent.com/12512448/47862353-f07c6400-de1a-11e8-9799-530420224073.PNG)

Now all pods on that namespace is stuck at "removing" state, since more than 24 hours now.
