### ISSUE TITLE
Unable to cancel YAML Workload edit

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12827]
**Rancher versions:**
Master 4/17/2018

Steps:
Create a cluster.
Create a workload
For new workload, select "View/Edit YAML"
Select Cancel

Results:
Does not cancel edit. Throws console error.

<img width="453" alt="screen shot 2018-04-18 at 9 54 22 am" src="https://user-images.githubusercontent.com/38012481/38946556-a7f02054-42ee-11e8-93d3-c593ad24a63a.png">

**Comment by biblesyme** [comment]
This should have been fixed in Master 4/18/2018

**Comment by adingilloRancher** [comment]
Build 
v2.0.0-rc1

Verified fix.
