### ISSUE TITLE
Setting Readiness Check back to "None" doesn't change the Liveness Check back to "None"

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#12823]
When deploying a workload if you change the Health Check to something besides "None" and then set it back to "None" the hidden liveness check doesn't get set back to "None".

**Rancher versions:**
2.0.0-beta3

**Steps to Reproduce:**

1. Go to Deploy Workload
1. Expand Health Check
1. Select Readiness Check: HTTPS request returns a successful status (2xx or 3xx)
1. Don't fill out the HTTPS check details (or fill it out incorrectly)
1. Click Launch
1. This reports an error (since we didn't fill out the HTTPS check details)
1. Change Readiness Check back to "None"
1. Click Launch
1. This errors with `spec.template.spec.containers[0].livenessProbe: Required value: must specify a handler type`
1. Click `Define a separate liveness check`
1. You will notice that the liveness check did not get set back to "None" when the Readiness Check was set back to none  

![image](https://user-images.githubusercontent.com/5324639/38942119-a1f0b984-42f3-11e8-8e4a-6b266825fc06.png)

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed
