### ISSUE TITLE
Rancher 2.0 and terraform interference on metadata

### ISSUE THREAD

**Issue by tholcman** [rancher/rancher#12821]
**Rancher versions:**
rancher/server: preview 2.0 Image: sha256:3cb94c58896a5dd73654df77b27952768a2f9ec2f09a8df52c0fb795a665e423

**Infrastructure Stack versions:**
kubernetes (if applicable): GKE 1.9.4-gke.1 imported
terraform: 0.11.7

**Story:**
We are managing some of our resources with terraform `google_container_cluster` `kubernetes_namespace` `kubernetes_secret` (passed to TF from vault) Mostly resources which developers shouldn't change but just use or public facing stuff. When we import cluster and assign namespace to project it adds `metadata`, on next `terraform plan/apply` it wants to remove those data. **For these resources we really need IaC approach**, no metter if terraform or other, but TF preferred.

```
  ~ kubernetes_namespace.awesome_team
      metadata.0.annotations.%:                                         "3" => "0"
      metadata.0.annotations.cattle.io/status:                          "{\"Conditions\":[{\"Type\":\"InitialRolesPopulated\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2018-04-17T19:49:20Z\"}]}" => ""
      metadata.0.annotations.field.cattle.io/projectId:                 "cluster-fg4ph:project-wqqq7" => ""
      metadata.0.annotations.lifecycle.cattle.io/create.namespace-auth: "true" => ""
      metadata.0.labels.%:                                              "2" => "1"
      metadata.0.labels.field.cattle.io/projectId:                      "project-wqqq7" => ""

  ~ kubernetes_service.service_public
      metadata.0.annotations.%:                                         "1" => "0"
      metadata.0.annotations.field.cattle.io/publicEndpoints:           "[{\"addresses\":[\"1.2.3.4\"],\"port\":2345,\"protocol\":\"TCP\",\"serviceName\":\"ns:service-public\",\"allNodes\":false}]" => ""
```

I have couple of questions in mind
- how much does R2 rely on changing existing resources
- are these metadata dynamic or can we hardcode them to TF? as bonus we might have Projects-Namespaces structure as code
- do you plan to have R2 terraform provider

**Steps to Reproduce:**
- create kubernetes namespace with terraform
- import cluster into R2
- assign namespace to project
- run terraform plan

**Results:**
- terraform wants to remove rancher's metadata from namespace

As bonus small bug: scaling deployment in ui cause to recreate whole deployment and so also all containers

**Comment by cloudnautique** [comment]
Asking upstream if they have any thoughts on this. To answer your questions:

Rancher allows you to import and mange 100% of the cluster. So its possible that Rancher could change all sorts of things. I believe we are assigning these things dynamically, and they are generated IDs (project-wqqq7 is an id). We do plan to have a provider to support Rancher 2 concepts. Still, we would like to find a way for the native K8s provider and Rancher to co-exist.

**Comment by guglez** [comment]
Any workarounds available?

**Comment by jeffb4** [comment]
Found a workaround:

```
resource "kubernetes_namespace" "myns" {
  metadata {
    annotations = {
      "cattle.io/status" = "placeholder"
      "lifecycle.cattle.io/create.namespace-auth" = "placeholder"
    }
    name = "myns"
  }
  lifecycle {
    ignore_changes = [
      metadata[0].annotations["cattle.io/status"],
      metadata[0].annotations["lifecycle.cattle.io/create.namespace-auth"]
    ]
  }
}
```

This works in terraform `0.12.5` although I have no reason to think it won't work `>=0.12.0`

**Comment by alexbde** [comment]
Thank you for the workaround! Just a hint: IntelliJ IDEA's inspection warning can be avoided using `metadata.0.annotations["..."]` instead of `metadata[0].annotations["..."]`.

**Comment by arusso** [comment]
This is still an issue, please do not close this as stale.

**Comment by command-tab** [comment]
!stale

**Comment by command-tab** [comment]
Still an issue

**Comment by command-tab** [comment]
The issue still remains.

**Comment by command-tab** [comment]
Was this resolved? I’m not sure why this issue was closed.

**Comment by jeffb4** [comment]
Poorly tuned stale bot, looks like

**Comment by ivan-penchev** [comment]
Bump still isse

**Comment by amithkk** [comment]
Still an issue
