### ISSUE TITLE
k8s issue with rbac with non admin users in 1.6

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#12822]
In 1.6, k8s environment with I have three users:
leouser1(Member)
leouser2(Read-Only)
leouser3(Restricted)

- when I login as leouser2, I see kubernetes in "Setting up Kubernetes" state though I have a valid running cluster
- when I login as leouser3, I see kubernetes but when I access dashboard I see errors `User "leouser3" cannot list blah blah blah`

**Comment by deniseschannon** [comment]
> when I login as leouser2, I see kubernetes in "Setting up Kubernetes" state though I have a valid running cluster

This is expected as users won't have access to the k8s API. If you want to set up readonly users in k8s, you need to turn on k8s RBAC and then use read only roles for k8s. 

> when I login as leouser3, I see kubernetes but when I access dashboard I see errors User "leouser3" cannot list blah blah blah

This sounds like k8s RBAC is already turned on. If so, restricted users are not automatically given any privileges and you'd need to set up the RBAC for those users through k8s.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
