### ISSUE TITLE
Unable to get workload sub types by ID

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#12837]
Version: rancher/server:master

if you access `v3/projects/<project-id>/daemonsets` you are able to see all available `daemonsets` but trying to access `v3/projects/<project-id>/daemonsets/<daemonset-id>` it returns the error `404 "failed to find resource by id"`.

I would expect it to return the proper resource when accessing that endpoint. 

This affects all workload types.

**Comment by dramich** [comment]
Using master this looks good to me.

**Comment by soumyalj** [comment]
Tested using master from April 23rd. Accessing resources daemonsets, cronjobs, statefulsets return the correct resource when accessed. 
v3/projects/<project-id>/deployments/<deployment-id>
v3/projects/<project-id>/daemonsets/<daemonset-id>
v3/projects/<project-id>/cronjobs/<cronjob-id>
v3/projects/<project-id>/statefulsets/<statefulset-id>
