### ISSUE TITLE
Remove PSPT from namespace when removed from project

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#12833]
When a namespace is removed from a project and not assigned to another project, it keeps the existing project PSP that had been assigned to it previously.

When a namespace is removed from a project, it should have its project PSP removed ~and have the cluster default PSPT assigned to it~.

**Comment by sangeethah** [comment]
Tested with latest build from master.

When a namespace is removed from a project and not assigned to another project, all the existing PSP related rolebindings get deleted from the namespace.
Trying to deploy pods to this namespace using kubectl fails with following error as expected 
```forbidden: unable to validate against any
        pod security policy: []'```
