### ISSUE TITLE
Selecting a specific key doesn't show up in Environment From Sources in workload details

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12843]
**Rancher versions:** 2.0 master 4/18

**Steps to Reproduce:**
1.  Create a config or secret
2.  Create a workload and add it to the environment section and change Key from All to the specific key
3.  Launch workload
4.  Go to workload details

**Results:**  The Key is not showing up
![image](https://user-images.githubusercontent.com/11514927/38963131-4ae68d30-4325-11e8-83d4-7538c980b8af.png)

**Comment by loganhz** [comment]
UI sends `sourceKey` field to backend. But backend doesn't populate this field. It was working few days ago.

![image](https://user-images.githubusercontent.com/21168270/38977030-a4d29f44-43e5-11e8-8a1c-22461b91f5cd.png)
![image](https://user-images.githubusercontent.com/21168270/38977065-c2105542-43e5-11e8-8934-c6b4d9049d64.png)

**Comment by tfiduccia** [comment]
@logan - this was being saved to the API yesterday and still wasn't showing up.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/26
Verified fixed
