### ISSUE TITLE
EC2 machine fails to start when using the same name for nodepool in 2 different clusters due to already existing keypair error. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12844]
Rancher server version - Build from master

Steps to reproduce the problem:
Created a EC2 cluster with nodepool name -santest1 and scale 3.
Wait for the cluster to get to active state.

Created another EC2 cluster with same nodepool name -santest1 and scale 3.

All the machines in this cluster fail to get provisioned with this error
```
"Error with pre-create check: "There is already a keypair with the name santest3. Please either remove that keypair or use a different machine name."; Timeout waiting for ssh key"
```

There is a constant attempt made to create machines which fails.

**Comment by StrongMonkey** [comment]
@sangeethah fix was merged into docker-machine, let me know if you are still seeing it.

**Comment by sangeethah** [comment]
Tested with latest build from master
Steps to reproduce the problem:
Created a EC2 cluster with nodepool name -santest1 and scale 3.
Wait for the cluster to get to active state.

Created another EC2 cluster with same nodepool name -santest1 and scale 3.
Wait for the cluster to get to active state.

All the machines in this cluster are able to start successfully.
