### ISSUE TITLE
Logging - flush interval has no effect

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12859]
**Rancher versions:**
rancher/server: master 4/18

**Steps to Reproduce:**
Enable a logging target
Set the flush interval to 120 seconds - Log events should only be written to target every 120s

**Results:**
Log events continue to be written as they occur

**Comment by bmdepesa** [comment]
This is proving difficult to test without project logging working (https://github.com/rancher/rancher/issues/13039). 

At cluster level, large amount of log entries cause buffer size limit to be reached before flush_interval, causing logs to be written before interval can be reached. Will re-test once project level logging is working again.

**Comment by aiwantaozi** [comment]
You could use the latest version, it should fix, related issue: The related framework issue is https://github.com/rancher/rancher/issues/13021

**Comment by bmdepesa** [comment]
Validated against rancher/rancher:master

Flush_interval appears to be working. Raised flush_interval value and logs appeared with a delay according to the value.
