### ISSUE TITLE
Unable to upgrade workload portmapping type

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#12855]
**Rancher versions:**
master 4/19, imported cluster

**Steps to Reproduce:**
1. deploy a nginx deployment with:
![image](https://user-images.githubusercontent.com/5697937/38971528-35b8bb96-43ce-11e8-98db-473fc5392141.png)
2. `Edit` the ngx workload, change port mapping configuration to:
![image](https://user-images.githubusercontent.com/5697937/38971554-569cc4c4-43ce-11e8-9564-20c3dfb81a4e.png)

**Results:**
No link available for the workload, the service type is still ClusterIP
Got logs in rancher/server:
```
2018/04/19 04:31:03 [INFO] Creating [myapp/ngx] service of type [ClusterIP] with ports [[{80tcp02 TCP 80 {0 80 } 0}]] for workload deployment:myapp:ngx
2018/04/19 04:31:44 [WARNING] Service [ngx/myapp] already exists but with diff type. Expected type [NodePort], actual type [ClusterIP]
```

**Comment by adingilloRancher** [comment]
Master 4/23/18
Verified ability to upgrade port mapping
