### ISSUE TITLE
Can not upgrade catalog app

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#12852]
rancher/server:master 04/18

Steps to reproduce:

1. Deploy a catalog app.
2. Update the catalog app.

Results:
 
The id of the app is wrong.

![image](https://user-images.githubusercontent.com/21168270/38969597-a5616138-43c3-11e8-9eaa-b481a81c2f57.png)

**Comment by StrongMonkey** [comment]
fix is in master now

**Comment by loganhz** [comment]
Version - 2.0 master 4/19
Verified fixed
