### ISSUE TITLE
Rancher 2.0 deploy moodle helm in app catelog just show cancel button

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#12858]
*Rancher 2.0 deploy moodle helm in app catelog just show cancel button*

![default](https://user-images.githubusercontent.com/3146226/38977427-f8dfeb86-43e6-11e8-820d-3f1fbc1d95a3.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta3` UI: `v2.0.35` |
|Access|`local` `admin`|
|Route|`catalog-tab.launch`|

**Comment by deniseschannon** [comment]
@loganhz With the changes in helm, can you check if this is still an issue?

**Comment by loganhz** [comment]
Version - 2.0 master 4/19
Verified fixed
