### ISSUE TITLE
v2.0.0-beta3 - Can't select UDP/TCP in syslog configuration

### ISSUE THREAD

**Issue by gtirloni** [rancher/rancher#12868]
**Steps to Reproduce:**

 * Tools > Logging > Syslog Configuration
 * Click on dropbox to select protocol (UDP or TCP)
 * Try to click either option, none is selected (or it stays in UDP, the initial value)

**Comment by vimniky** [comment]
@gtirloni I follow the step, but I can't reproduce this issue, can you provide more context?

**Comment by vimniky** [comment]
@gtirloni I follow the step, but I can't reproduce this issue, can you provide more context?

**Comment by vimniky** [comment]
@gtirloni I don't have this issue! thought I'm no using 2.0-beta3, can you update to the latest version?

**Comment by gtirloni** [comment]
@vimniky Hi, I tested just now with a fresh install of 2.0.0-beta4-rc2 and I still see the issue. I'm using Chrome 66.0.3359.117 and Firefox 59.0.2 on Linux. I don't see any errors on the JS console.

I don't know if this matters but I'm testing on an imported cluster. So I only followed these steps: spin up the Rancher container, login and change password, add imported cluster, went to the cluster's Tools -> Logging -> syslog, enter IP/hostname, click on the dropdown and select TCP but nothing gets selected.

**Comment by vimniky** [comment]
@gtirloni Sorry for the late. It's really weird. I'd try to test it again on an imported cluster thanks!

**Comment by vimniky** [comment]
@gtirloni I have just tested it on an imported cluster and still can't reproduce this issue. I think it may be because you are on a Linux machine(I haven't used any fantasy stuff that can cause incompatible). I don't have a Linux machine at hand, can you visit your Rancher UI on Windows or Mac to see whether this issue still happens? Thanks!

**Comment by gtirloni** [comment]
Just tested on v2.0.0 GA now and the issue seems gone. Thanks for all the help!
