### ISSUE TITLE
Logging - Syslog log severity level has no effect

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12860]
**Rancher versions:**
rancher/server: master 4/18

**Steps to Reproduce:**
Enable logging with syslog target
Change logging severity level and save - Only log events that match the severity level should be written

**Results:**
All log events are still written regardless of severity (Emergency, Alert, Critical, Error, Warning, Notice, Info, Debug)

**Comment by aiwantaozi** [comment]
Hi, if you config the different format in the syslog server, may some config like below, and you select a severity in the UI, for example, you select the notice, fluentd will add notice severity to each log, and in your syslog server, the log will only write to the notice and the level under notice (notice, Info  and debug). Is this match your test? 
*.debug /var/log/mydebug
*.info /var/log/myinfo
*.notice /var/log/mynotice
*.warning /var/log/mywarning
*.err /var/log/myerror
*.crit /var/log/mycrit
*.alert /var/log/myalert
*.emerg /var/log/myemerg

**Comment by bmdepesa** [comment]
Validated on rancher/rancher:master 4/26. 

This was an error with my syslog configuration.
