### ISSUE TITLE
Adding nodes to cluster with internal IP is set as annotation, but not reflected in pod deployment 

### ISSUE THREAD

**Issue by mysim1** [rancher/rancher#12864]
**Rancher versions:**
rancher/server: master 4/18

**Steps to Reproduce:**
work with nodes that have 4 different locations, 4 different ip's. 4 vpn connections to 1 vpn network
built Custom cluster
add nodes with public and internal ip address provided

**Results:**
Deploying more than 1 pod, forcing deployment to other nodes will make the workload useless. Since it's using the primary IP of those nodes, which are not available in the network.  It should use the provided internal IP. because nodes should are accessible in VPN network)

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.10 template

**Comment by mysim1** [comment]
Cloud version of this problem is at:
https://github.com/rancher/rancher/issues/12945

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/43379483-4e3c20c8-93ff-11e8-9cba-88009f3f3aae.png)

Now you can set internal IP and public IP before adding the node.

Do you mean the network between nodes are using public IP instead of private IP in your cluster even you have specified `--address` and `--internal-address`?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by Darkeye9** [comment]
I have this problem right now with rancher 2.1.1. Checked by pinging from one pod to a service scheduled on another node and I could see the ping content being encapsualted and sent throught the Public Address IP.
