### ISSUE TITLE
v2.0.0-beta3 - Cluster stuck at provisioning state

### ISSUE THREAD

**Issue by adalga** [rancher/rancher#12869]
**Rancher versions:**
rancher/server: v2.0.0-beta3 
rancher/agent: v2.0.0-beta3 

**Infrastructure Stack versions:**
network-services: weave 2.1.2
kubernetes (if applicable): v1.8.7-rancher1

**Docker version: (`docker version`,`docker info` preferred)** 
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
Ubuntu 16.04 - 4.13.0-38-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 nodes bare metal cluster

**Steps to Reproduce:**

[cluster.yml.txt](https://github.com/rancher/rancher/files/1928023/cluster.yml.txt)
./rke up // create kubernetes cluster
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview // run rancher v2.0.0-beta3
import cluster you created above

**Results:**
It stucks at Provisionint state and gives an error like
Waiting for API to be available; .. HTTP2 has been expilicitly disabled. Failed to download OpenAPI (the server has asked for the client to provide credentials), falling back to swagger error: You must be logged in to the server (Unauthorized)

cattle-node-agent logs like 
Connecting to wss://10.0.0.40/v3/connect with token ...
Failed to connect to proxy error=websocket: bad handshake

**Comment by deniseschannon** [comment]
@adalga It seems like you are trying to import the cluster that is also running rancher? Is that correct?

In the future, we are supporting creating a k8s cluster and deploy a k8s yaml to start Rancher as a deployment.

**Comment by adalga** [comment]
I created my cluster with rke but there is no rancher running. I imported it via generated yaml from rancher ui.

**Comment by wzrdtales** [comment]
@deniseschannon I do have the same issues, but I do not import anything I have rancher running independently and the server is provisioned through the **custom** setup in the rancher ui. But I get the same error

![image](https://user-images.githubusercontent.com/1786821/39426432-19420dc2-4c80-11e8-92c8-ed703a70f8ef.png)

The api server logs from the node are the following

```
I0430 12:09:39.330776       1 logs.go:49] http: TLS handshake error from 192.168.100.2:8754: remote error: tls: bad certificate
I0430 12:09:39.377667       1 logs.go:49] http: TLS handshake error from 10.233.64.56:40058: remote error: tls: bad certificate
I0430 12:09:39.391185       1 logs.go:49] http: TLS handshake error from 10.233.64.56:40060: remote error: tls: bad certificate
I0430 12:09:40.343348       1 logs.go:49] http: TLS handshake error from 192.168.100.2:8764: remote error: tls: bad certificate
I0430 12:09:40.391988       1 logs.go:49] http: TLS handshake error from 10.233.64.56:40068: remote error: tls: bad certificate
I0430 12:09:40.406117       1 logs.go:49] http: TLS handshake error from 10.233.64.56:40070: remote error: tls: bad certificate
E0430 12:09:41.072377       1 authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, square/go-jose: error in cryptographic primitive]]
E0430 12:09:41.084424       1 authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, square/go-jose: error in cryptographic primitive]]
E0430 12:09:41.099373       1 authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, square/go-jose: error in cryptographic primitive]]
I0430 12:09:41.349837       1 logs.go:49] http: TLS handshake error from 192.168.100.2:8770: remote error: tls: bad certificate
I0430 12:09:41.405054       1 logs.go:49] http: TLS handshake error from 10.233.64.56:40074: remote error: tls: bad certificate
I0430 12:09:41.421067       1 logs.go:49] http: TLS handshake error from 10.233.64.56:40076: remote error: tls: bad certificate
```

**Comment by wzrdtales** [comment]
But I am on the latest version not beta3, so still an issue

**Comment by superseb** [comment]
Is this a setup from scratch (no upgrades/no used machines)? Are the hosts you are adding been added before and if so, did you clean the hosts properly so it doesn't re-use wrong configuration? (https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d)

**Comment by wzrdtales** [comment]
It is a testing setup with a few vms, rancher running in standalone on one of the vms, I will try your cleanup script on the host node and will let you know if it changes anything.

**Comment by superseb** [comment]
@adalga Please report back so we can investigate.

**Comment by adalga** [comment]
As I said I created my cluster with rke. Then I tried to import my existent cluster via generated yaml from rancher ui. Nothing has changed yet.

**Comment by willmao** [comment]
similar issue,the kube config was generated by rancher ui, jenkins use kubectl with the config file to deploy workload on my cluster, SOMETIMES kubectl can not authorized correctly

error log:

failed to execute process [ kubectl -n i3 get pods -l app=product-service,release=20180906231233 -o go-template --template={{range .items}}{{range .status.containerStatuses}}{{.ready}},{{end}};{{end}} ]. return code 1. error:  error: You must be logged in to the server (Unauthorized)

test command `kubectl get nodes` for 10 times, nodes list can be displayed correctly

I don't know why the kubectl can not authorized correctly.

rancher version: 2.0.8
k8s version: 1.11.1

@superseb

**Comment by superseb** [comment]
This is an old issue and a different problem, please create a new issue following https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions and the issue template to supply all the info needed so we can run tests on it.
