### ISSUE TITLE
rancher/agent:latest is not rancher/agent:v1.2.10

### ISSUE THREAD

**Issue by rafaelgaspar** [rancher/rancher#12871]
**Rancher versions:**
rancher/server: v1.6.17
rancher/agent: v1.2.8(latest, doesn't work) v1.2.10(works)

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 18.03.0-ce, build 0520e24, also tested on 17.12.1-ce.

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.0.0
VERSION_ID=1745.0.0
BUILD_ID=2018-04-11-2324
PRETTY_NAME="Container Linux by CoreOS 1745.0.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

```
$ uname -r
4.15.15-coreos
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE

**Steps to Reproduce:**

```
$ docker pull rancher/agent:latest
latest: Pulling from rancher/agent
Digest: sha256:e5a9cd17ceb29eab2749428a6ed49a85f3457d080d76ea9ec3c6d943e1cbf313
Status: Image is up to date for rancher/agent:latest

$ docker pull rancher/agent:v1.2.10
v1.2.10: Pulling from rancher/agent
Digest: sha256:5618f36cdb6c6fe25baa3e72977f3a226d43ffd1d74dda6a8860e32b73a1e171
Status: Image is up to date for rancher/agent:v1.2.10

$docker pull rancher/agent:v1.2.9
v1.2.9: Pulling from rancher/agent
Digest: sha256:c21255ac4d94ffbc7b523f870f2aea5189b68fa3d642800adb4774aab4748e66
Status: Image is up to date for rancher/agent:v1.2.9

$ docker pull rancher/agent:v1.2.8
v1.2.8: Pulling from rancher/agent
Digest: sha256:e5a9cd17ceb29eab2749428a6ed49a85f3457d080d76ea9ec3c6d943e1cbf313
Status: Downloaded newer image for rancher/agent:v1.2.8
```

So, as you can see `rancher/agent:latest` is actually `rancher/agent:v1.2.8`, and since `rancher/agent:v1.2.8` doesn't boot on Docker 17.12.1-ce or Docker 18.03.0-ce the agent won't boot unless I specify the version manually.

**Results:**

```
Found container ID: 415a4528bef4bff2abcefd8d8fbdfe82b481ee4bac23feee5428e27d3c75806f
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
time="2018-04-09T19:57:25Z" level=fatal msg="Failed to find state.json"
```

**Comment by deniseschannon** [comment]
We don't recommned ever using the `latest` tag for agent as each Rancher server is specifically compatible with a specific version of Rancher agent. Relying on latest can get you into situations where the server will not work with agent. 

WIth that being said, I've updated the `latest` tag for rancher agent.
