### ISSUE TITLE
Docker v1.11.2

### ISSUE THREAD

**Issue by vojtasvoboda** [rancher/rancher#12870]
I'm just curious, is there some special reason why Rancher does not support Docker v1.11.2? There is just support for:
- Docker 1.10.3
- Docker 1.12.3-1.12.6

I'm leaving Docker Cloud and looking for a different tool for managing containers, but Docker Cloud had created nodes with Docker v1.11.2 and Rancher gives me `Unsupported Docker version` :-( Is there some Rancher version I could install?

Thanks a lot, guys

**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

1.11.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

AWS EC2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Docker

**Comment by deniseschannon** [comment]
I believe there were known issues in v1.11.x that made it less stable than other versions, but it's been awhile. 

For installing Docker, we have some install scripts that work well, where you can replace it with what version you want to install. We use these in our product to set a specific version of Docker when creating hosts using our UI. It's in the "Advanced Options" section. 

https://github.com/rancher/install-docker

```
curl https://releases.rancher.com/install-docker/<version>3.sh | sh```

I'm not sure how that works for upgrading Docker, but just wanted to give you the options. 

Let me know if you need any other help!
