### ISSUE TITLE
Changed IP, services not starting anymore

### ISSUE THREAD

**Issue by auras** [rancher/rancher#12883]
I'm running a rancher server and host on the same bare metal machine. My machine got a new IP and after restarting it it will no longer start most of the services. Most of the services are trying to connect to the old ip address.

I changed the ip address that the agent connects to but the support services haven't changed their ip address.

I see these in the logs:

```
19/04/2018 17:49:12time="2018-04-19T15:49:12Z" level=fatal msg="Failed to subscribeGet http://172.16.20.22:8080/v2-beta: dial tcp 172.16.20.22:8080: getsockopt: no route to host"
19/04/2018 17:49:19time="2018-04-19T15:49:19Z" level=info msg="Subscribing to events"
```

What can I do?

**Comment by superseb** [comment]
You will need to delete the infrastructure containers to be re-created with the correct Rancher URL/IP. See https://github.com/rancher/rancher/issues/9307

Let me know if that doesn't solve your issue.
