### ISSUE TITLE
Editing a workload doesn't reflect changes for at least ports exposed

### ISSUE THREAD

**Issue by josmo** [rancher/rancher#12884]
Steps-
1. Create nginx workload with random port and container port 80. -> works on the random port
2. Edit the workload and change or remove the port
3. Upgrade
Expected - port changed or removed
Actual - original random port remains exposed

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta3` UI: `v2.0.35` |
|Access|`` `admin`|
|Route|`containers.index`|

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/19
This seems to be fixed in the latest master.  Port was removed and I can't access any longer.
