### ISSUE TITLE
Unable to create stateful event bug. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12889]
**Rancher versions:**
Master 4/17/18

Steps:
Create a new cluster.
Attempt to add an alert for statefulset events. 

Result:
Unable to save. 
![screen shot 2018-04-19 at 1 43 29 pm](https://user-images.githubusercontent.com/38012481/39017282-afdfa94e-43d7-11e8-893b-35ab8e2c1ba7.png)

Response:
{  
   "actionLinks":{  
   },
   "baseType":"error",
   "code":"InvalidFormat",
   "fieldName":"targetEvent",
   "links":{  
   },
   "message":"resourceKind=InvalidOption 422:",
   "status":422,
   "type":"error"
}

**Comment by zionwu** [comment]
This bug is due to the backend PR for issue #12790 and #12789 is merged but the corresponding UI PR is still not merged. Once the UI PR is merged this bug will be fixed.

**Comment by adingilloRancher** [comment]
Master 4/20/18

Verified Fix
