### ISSUE TITLE
Make None default for all Cloud providers

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12887]
**Rancher versions:** 2.0 master 4/19

**Steps to Reproduce:**
1.  Go to Add Cluster
2.  Open Cluster Options

**Results:**  make sure None is default for Cloud providers for all RKE providers.

**Comment by deniseschannon** [comment]
We should also confirm that if you start a cluster with one of the options, when you start a new cluster, it's defaulted to none again.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/24
Verified fixed
