### ISSUE TITLE
Unable to create Daemonset event alert. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12888]
**Rancher versions:**
Master 4/17/18

Steps:
Create a new cluster.
Attempt to add a new alert for Daemonset events. 

Results:
Unable to save.

![screen shot 2018-04-19 at 1 23 02 pm](https://user-images.githubusercontent.com/38012481/39017121-3d707528-43d7-11e8-88fa-1adc104fd92c.png)

Response:
{  
   "actionLinks":{  

   },
   "baseType":"error",
   "code":"InvalidFormat",
   "fieldName":"targetEvent",
   "links":{  

   },
   "message":"resourceKind=InvalidOption 422:",
   "status":422,
   "type":"error"
}

**Comment by zionwu** [comment]
@adingilloRancher  This bug is due to the backend PR for issue https://github.com/rancher/rancher/issues/12790 and https://github.com/rancher/rancher/issues/12789 is merged but the corresponding UI PR is still not merged.   Once the UI PR is merged this bug will be fixed.

**Comment by adingilloRancher** [comment]
Master 4/20/18
Verified Fix
