### ISSUE TITLE
If service account password is blank, Testing button just spins and no error thrown

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12885]
**Rancher versions:** 2.0 master 4/19

**Steps to Reproduce:**
1.  Go to Authentication page
2.  Select Active Directory
3.  Fill out all info but leave Service Account Password blank
4.  Click on Authenticate

**Results:** Nothing happens, button just continues to spin and says "Testing"

**Comment by deniseschannon** [comment]
Duplicate: https://github.com/rancher/rancher/issues/12538
