### ISSUE TITLE
Cloud Provider's netResourceGroup is being posted but not returned by API

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12890]
**Rancher versions:** 2.0 master 4/19

**Steps to Reproduce:**
1.  Create a cluster and select Azure
2.  Fill out all cloud provider info

**Results:** netResourceGroup is being posted but not returned by API

**Comment by alena1108** [comment]
@vincent99 by some reason UI shows 2 parameters - `netResourceGroup` and `vnetResourceGroup` - and only the second one is valid and exposed via `/v3/schemas/azureCloudProvider` API

![image](https://user-images.githubusercontent.com/1562176/39027947-2fed1c1c-4409-11e8-85cd-d5a6b4cc96cb.png)

Not sure what can be a reason for that?

**Comment by vincent99** [comment]
There's a list in the UI, presumably from before they were showing up in the schema properly..

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/27
Verified fixed
