### ISSUE TITLE
[cli] ssh does not allow user to be specified or args to be passed through

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#12897]
A user can not be specified to if the default user set on the node is not the correct user the node can't be accessed through ssh. 

No args are being passed through to the ssh call

**Comment by dramich** [comment]
Available in v1.0.0-alpha14

**Comment by bmdepesa** [comment]
Validated against v1.0.0-alpha14. 

All 3 methods for SSH login are working:

ssh
ssh user@node
ssh -l user node
