### ISSUE TITLE
Building/running behind a NTLM Proxy

### ISSUE THREAD

**Issue by josephwinston** [rancher/rancher#129]
I'm more than willing to provide a set of patches to allow rancher to build and run behind an NTLM proxy.   I attempted to just update the Vagrantfile, but of course that was't enough.

Adding support in the Vagrantfile is straightforward using <http://tmatilai.github.io/vagrant-proxyconf/>.  The OS host could have something like CNTLM running but that begs how the configuration for CNTLM will be done.  Then there is the docker issues of running behind a proxy.

Is this even worth fighting this issues and making a generic patch?

**Comment by vincent99** [comment]
@josephwinston Is this still relevant?  With the current releases no internet connection is needed unless you are using an authentication method on the internet (i.e. public GitHub) or public cloud docker-machine providers.

**Comment by josephwinston** [comment]
Close and if it still exists, I’ll re-open
