### ISSUE TITLE
statefulset icon issue

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/rancher#12908]
**Rancher versions:**
rancher/server:v2.0.0-beta3
rancher/agent:v2.0.0-beta3

**Infrastructure Stack versions:**
healthcheck: OK!
ipsec: OK!
network-services: OK!
scheduler: OK!
kubernetes (if applicable): OK!

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2 ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
16.04.4 LTS (Xenial Xerus)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualMachine by Proxmox VE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1.create a statefulset app, choose pod num 1;
2.edit the app in workloads page;

**Results:**
In the Deploy Workload page, u can found that the icon of the statefulset changed to the scalable type
![image](https://user-images.githubusercontent.com/23303886/39042493-89f77b26-44bd-11e8-980d-d80eb27925fb.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/23
Verified fixed
