### ISSUE TITLE
Removing a Notifier that is attached to active Alerts doesn't warn

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#12914]
**Rancher versions:**
rancher/server: master 20/4

Currently a Notifier can be removed without warning even though it is associated with Active alerts.

At a minimum it should alert the user that there are active alerts associated and prompt for confirmation, preferably it would show the associated alerts and not allow removal until the alerts are deactivated.

**Comment by tfiduccia** [comment]
@vincent99 - Not sure this is what we really want to do.  After you try to delete it brings up one of those popups saying you can't delete it.  Kinda makes it look like an error.

![image](https://user-images.githubusercontent.com/11514927/39335203-f016422c-4966-11e8-9b53-b5e80695e918.png)

Can you review and tell me if there is something else we can be doing?

**Comment by vincent99** [comment]
I asked for it this way as the least-bad compromise.. the normal behavior of disabling button won't give you any information for why you can't delete it, and this at least preserves the ability to do bulk actions.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/24
Chatted with Vincent - Verified fixed.
