### ISSUE TITLE
3 app in kube-system namespace have problems after the cluster deployed

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/rancher#12912]
**Rancher versions:**
rancher/server:v2.0.0-beta3
rancher/agent:v2.0.0-beta3

**Infrastructure Stack versions:**
healthcheck:OK!
ipsec:OK!
network-services:OK!
scheduler:OK!
kubernetes (if applicable):OK!

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2 ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
16.04.4 LTS (Xenial Xerus)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualMachine by Proxmox VE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1.create a cluster:
1). choose customer type(using virtual machine as all nodes);
2). using(1.8.x 1.9.x 1.10.x)k8s (whatever the k8s version is,  whatever the network plugin is);
3). 1 master，2nodes, and 2 nodes r etcd+control+worker;
4). w8 cluster creation finished 

2.step into cluster > namespace > move all (including kube-system) to the default project like this:
![image](https://user-images.githubusercontent.com/23303886/39048302-8e2527cc-44cf-11e8-9185-cffcc7f2d612.png)

3.back to the default project 's workload page, results are:

**Results:**
1.The workloads page shows that 3 app in kube-system namespace are active+unavailable status:
![image](https://user-images.githubusercontent.com/23303886/39047761-b1d58a74-44cd-11e8-96f0-940562b6d30a.png)

2.The 3 app's container exited on system:
![image](https://user-images.githubusercontent.com/23303886/39047998-8be05f32-44ce-11e8-9da8-31a4eb5a401e.png)

and cannot be restart:
![image](https://user-images.githubusercontent.com/23303886/39048019-a7f4d70c-44ce-11e8-926e-6da617ea9805.png)

3.logs for each one here:
1)rke-ingress-controller-deploy-job:
image:
![image](https://user-images.githubusercontent.com/23303886/39047824-e890ce8e-44cd-11e8-9c64-8c68ad438a44.png)

text:
namespace "ingress-nginx" created
configmap "nginx-configuration" created
configmap "tcp-services" created
configmap "udp-services" created
serviceaccount "nginx-ingress-serviceaccount" created
clusterrole.rbac.authorization.k8s.io "nginx-ingress-clusterrole" created
role.rbac.authorization.k8s.io "nginx-ingress-role" created
rolebinding.rbac.authorization.k8s.io "nginx-ingress-role-nisa-binding" created
clusterrolebinding.rbac.authorization.k8s.io "nginx-ingress-clusterrole-nisa-binding" created
daemonset.extensions "nginx-ingress-controller" created
deployment.extensions "default-http-backend" created
service "default-http-backend" created

2)rke-kubedns-addon-deploy-job:
image:
![image](https://user-images.githubusercontent.com/23303886/39047875-15c9d602-44ce-11e8-9936-77a183a840a3.png)

text:
deployment.apps "kube-dns-autoscaler" created
serviceaccount "kube-dns-autoscaler" created
clusterrole.rbac.authorization.k8s.io "system:kube-dns-autoscaler" created
clusterrolebinding.rbac.authorization.k8s.io "system:kube-dns-autoscaler" created
serviceaccount "kube-dns" created
deployment.extensions "kube-dns" created
service "kube-dns" created

3)rke-network-plugin-deploy-job:
image:
![image](https://user-images.githubusercontent.com/23303886/39047915-3c24d2e8-44ce-11e8-8a60-00557ac04a67.png)

text:
clusterrolebinding.rbac.authorization.k8s.io "flannel" created
clusterrole.rbac.authorization.k8s.io "flannel" created
configmap "kube-flannel-cfg" created
daemonset.extensions "kube-flannel" created
serviceaccount "flannel" created

**Comment by cjellick** [comment]
I _believe_ this bug and fix https://github.com/rancher/rancher/issues/12872  should fix this as well.

**Comment by sangeethah** [comment]
Tested with master build - ```91a916874851        rancher/rancher:master ```

Able to reproduce this issue.

**Comment by sangeethah** [comment]
Tested with v2.0.0-rc3

This issue is not seen anymore.
