### ISSUE TITLE
multi-cluster projects

### ISSUE THREAD

**Issue by tomdavidson** [rancher/rancher#12919]
Projects are a collection of k8s namespaces and rancher users/groups. It would be great if the namespaces could exist on multiple clusters but at least in the UI projects have a child relationship with clusters. Should the project - cluster relationship be decoupled?

Thanks

**Comment by vincent99** [comment]
TL; DR: No.

This is roughly the first thing everybody says when they find out about projects, and we get why it _sounds_ like a useful thing, but if you actually try to work out what it would do it doesn't actually makes sense.

For example, when you add a workload, which cluster does it go to?  Sure we can have a choice in the UI; what about in `kubectl apply`?  And it just gets worse from there..

**Comment by tomdavidson** [comment]
Thanks for the quick reply. 

K8S federation just uses --context. Does not seem that impossible/crazy given that rancher is a single control plane for multiple clusters.

If the 'project' construct  is the R&D portion of the value chain, then I have workloads that run on different clusters that is the same code and has the same users but with rancher projects coupled to clusters I will need to have multiple rancher projects for the same project.

Just idea.
