### ISSUE TITLE
Opening Projects/Namespaces when cluster is in provisioning state shows 503

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12915]
Version: master 4/20

- Create custom cluster
- Open `Projects/Namespaces`

503 is shown
```
ClusterUnavailable (503)
ClusterUnavailable 503: cluster not found
```

**Comment by loganhz** [comment]
@vincent99  As the cluster is not ready, so we cannot do `get(this, 'clusterStore').findAll('namespace')`. Should we hide `Projects/Namespaces` menu if cluster is provisioning?

**Comment by tfiduccia** [comment]
@loganhz - we don't normally hide the menu option.  We just have it go back to the cluster dashboard until it's ready.

**Comment by tfiduccia** [comment]
Version - v2.0.0-beta4-rc4
Verified fixed
