### ISSUE TITLE
Validate added catalog answers

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12917]
Version: master 4/20

When adding wordpress template, and using answer like `mariadb` = `blabla,`, the UI accepts it and starts deploying while the `rancher/server` loggins shows:

```
E0420 10:27:26.903522       1 generic_controller.go:204] AppController project-z8dsh/wordpress [helm-controller] failed with : helm template failed. Error: failed parsing --set data: key "mariadb" has no value (cannot end with ,)
```

**Comment by vincent99** [comment]
The UI has no way to know what that variable is going to be used for our what characters it should be allowed to end with...
