### ISSUE TITLE
Delete option not presented in UI for PSPT.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12926]
**Rancher versions: Build from master
**Steps to Reproduce:**
Go to Global->Security->Pod Security Policy
Create a new PSP template.
Notice that user is not presented with "Delete" option.

<img width="1331" alt="screen shot 2018-04-20 at 9 50 10 am" src="https://user-images.githubusercontent.com/4266958/39063533-404544f0-4480-11e8-947f-491d940b5cda.png">

**Comment by vincent99** [comment]
This is an API bug; Listing individual PSPs returns the `remove` link but getting the collection does not.

**Comment by sangeethah** [comment]
Tested with latest build from master.
Delete option is presented for PSP entries that are not in use in UI and able to delete them using this option.
