### ISSUE TITLE
Service Discovery - DNS not resolving alias to hostname 

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12923]
**Rancher versions:**
rancher/server: master 4/19

**Steps to Reproduce:**
Create DNS record resolving to hostname
Create DNS record type alias with target of first record
Dig / Ping alias record - Should resolve to hostname of first record

**Results:**
Fails to resolve

<img width="1274" alt="screen shot 2018-04-20 at 9 11 24 am" src="https://user-images.githubusercontent.com/21316915/39061973-f30e904c-447a-11e8-8449-9cda4a19b8ce.png">

**Comment by ystyle** [comment]
the same issue .

i create a workload ,name is nginx,  then scala to 3 pod, and turn back to 1
run `ping nginx` in other pod , the nginx dns record ip is erros,
and i add a nginx-serivce to the same workload or alias a other name , the dns record is right

**Comment by bmdepesa** [comment]
Tested against rancher/rancher:2.0.0-rc2

Not working. 

Created a DNS record 'externalhost' of type `hostname` to `google.com`
Created a DNS record 'hostalias' of type `alias` to first record 'externalhost'.
Ping/dig  'hostalias' (ping hostalias, dig hostalias.default.svc.cluster.local +short) - Should resolve to google.com, but does not resolve to anything.

**Comment by bmdepesa** [comment]
Validated on master 5/8. 

Aliases to hostnames are resolving correctly.
