### ISSUE TITLE
Failure to start containers - "Error response from daemon: grpc: the connection is unavailable"

### ISSUE THREAD

**Issue by akire0124** [rancher/rancher#12935]
**Rancher versions:**
rancher/server:v1.6.14
rancher/agent:v1.2.9

**Infrastructure Stack versions:**
healthcheck:5
ipsec:15
network-services:26
scheduler:10
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.4 (4.9.40)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher
External DB

**Environment Template:**
Cattle

**Steps to Reproduce:**
3 of our servers have a label and we have a service that is only supposed to deploy containers on hosts with that label. One server got hot and we attempted to move some of the containers off of that server onto another one of the labelled servers. The containers kept failing to start on that server with this error "Error response from daemon: grpc: the connection is unavailable". 

It was also failing to load up on the other two labelled servers, so we eventually had to throw the label on a 4th server in order to stabilize. 

**Results:**
These are the logs from the first server that it tried to load the containers on. 
time="2018-04-20T17:55:55Z" level=info msg="Received event: Name: storage.volume.activate, Event Id: d05622b4-a77c-4888-a081-537ab62910a7, Resource Id: 1vspm15142"
time="2018-04-20T17:55:55Z" level=info msg="Reply: d05622b4-a77c-4888-a081-537ab62910a7, storage.volume.activate, 1vspm15142:volumeStoragePoolMap"
time="2018-04-20T17:55:55Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 3a6c824a-f97a-4be9-bbda-e5baf6e7ea66, Resource Id: 1ihm12700"
time="2018-04-20T17:55:55Z" level=error msg="Error processing event" err="Error response from daemon: grpc: the connection is unavailable" eventId=3a6c824a-f97a-4be9-bbda-e5baf6e7ea66 eventName=compute.instance.activate resourceId=1ihm12700
time="2018-04-20T17:55:55Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: d79805b9-1edd-458e-8077-e0f151999b9c, Resource Id: 1ihm12700"
time="2018-04-20T17:55:56Z" level=error msg="Error processing event" err="Error response from daemon: grpc: the connection is unavailable" eventId=d79805b9-1edd-458e-8077-e0f151999b9c eventName=compute.instance.activate resourceId=1ihm12700
time="2018-04-20T17:55:56Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 803aa1f3-0c40-499b-b42a-3889f3bf1efe, Resource Id: 1ihm12700"
time="2018-04-20T17:55:56Z" level=error msg="Error processing event" err="Error response from daemon: grpc: the connection is unavailable" eventId=803aa1f3-0c40-499b-b42a-3889f3bf1efe eventName=compute.instance.activate resourceId=1ihm12700
time="2018-04-20T17:55:56Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 5321d530-e753-4b79-9724-3c74d56d5f61, Resource Id: 1ihm12700"

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
