### ISSUE TITLE
Container linking not working (sometimes)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1294]
v0.24.0

Steps to Reproduce:
1. Have 2 hosts
2. Create a container A on Host 1
3. Create a container B on Host 2 (linked from advanced networking to container A on host 1)

Result: It doesn't appear that the links on the containers are working. When I click on "Edit" on container B, it shows "This container has no links."

This is not a consistent issue. Sometimes the links go through, sometimes they don't.

I was able to reproduce creating new containers on Host 2 linking  to the same container A on host 1. It works about 40% of the time, doesn't work 60%?

**Comment by deniseschannon** [comment]
@vincent99 I don't think it's a UI thing, but wanted to confirm with the master of UI first. :)

**Comment by alena1108** [comment]
Tried to reproduce it. The links are created in the DB, I can see them when look at the instance using API, but UI container.edit screen doesn't show them. Here is the DB output:

mysql> select * from instance_link;
+----+------+------------+--------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+-----------+-------------+--------------------+------------------------+
| id | name | account_id | kind         | uuid                                 | description | state  | created             | removed | remove_time | data | link_name | instance_id | target_instance_id | service_consume_map_id |
+----+------+------------+--------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+-----------+-------------+--------------------+------------------------+
|  1 | NULL |          5 | instanceLink | 5cc0334c-686b-44e8-8e6f-ead7aa28a671 | NULL        | active | 2015-06-19 20:09:50 | NULL    | NULL        | {}   | tt        |           7 |                  6 |                   NULL |
|  2 | NULL |          5 | instanceLink | 1f1c64fb-5656-4c46-86d8-17f172edcb6a | NULL        | active | 2015-06-19 20:16:53 | NULL    | NULL        | {}   | tata      |           8 |                  6 |                   NULL |
+----+------+------------+--------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+-----------+-------------+--------------------+------------------------+
2 rows in set (0.00 sec)

**Comment by deniseschannon** [comment]
@vincent99 it looks as if it's being set, so you'll have to take a look in the UI.

**Comment by vincent99** [comment]
Yes I see them coming back from the API call too, UI bug.

**Comment by pwFoo** [comment]
Maybe the same problem. So I post it here first.

I have one RancherOS Host with local running agent. 
During create a project an service (mysql db, apache webserver, db linked to webserver as "mysql") "networking" takes a long time, but finally the containers are running. 
I changed the link from "mysql" to "127.0.0.1" (only dns names or also ip addresses are ok?!). Now container stays in networking state forever.

**Comment by deniseschannon** [comment]
@pwFoo The one I reported is a UI bug, which is not related to your issue.

We've created a separate issue that reports what you are seeing. Rancher only allows dns names for the name of a link, but we don't do accurate validation. https://github.com/rancherio/rancher/issues/1315

**Comment by deniseschannon** [comment]
This is most likely related to https://github.com/rancher/rancher/issues/1389

**Comment by deniseschannon** [comment]
Closed in favor of #1389
