### ISSUE TITLE
Unable to set node agent ip to Public instead of Private

### ISSUE THREAD

**Issue by bernardmaltais** [rancher/rancher#12945]
I tried the “-e CATTLE_AGENT_IP=<assigned public ip>” method to force the agent to use the Public IP assigned by the cloud provider (like AWS, Azure or Google) instead of the Private IP but it does not appear to work. Is this a supported feature of v2.0 or something that is no longer available?

Needed to allow nodes to communicate when private networks are not routable and only Public is.

Right now nodes on Azure can't communicate with nodes on GCP or AWS apparently due to the fact that they try to exchange over the private IP. I might be wrong and perhaps the issue of communication is elsewhere.

I made sure allow any any was configured in my security profiles on each cloud so that tcp ports block was not part of the problem.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta3` UI: `v2.0.35` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
The parameter to set the IP is `--address`, and `--internal-address` if you want to set the internal address separately.

Let me know if this doesn't work.

**Comment by adrianog** [comment]
Did you eventually solve this?

**Comment by taina0407** [comment]
@superseb These settings doesn't work.
In my cluster, I'm mixing on premise nodes and EC2 nodes.
On premise node with --address for public option (these nodes has public IP directly assigned)
On EC2 nodes with both --address and --internal-address option

All nodes are up , pods are deploy and running. But weird problem is that pods from this node cannot resolve DNS to services from other nodes, and cannot ping ether

All nodes:
![nodes](https://user-images.githubusercontent.com/5900860/77900334-1e800500-72a8-11ea-8afc-eb1404a3f2b8.png)

Pods are deployed to EC2 nodes:
![pods](https://user-images.githubusercontent.com/5900860/77900339-1e800500-72a8-11ea-8141-6a4cc3f7f3f9.png)

DNS troubleshooting:
![dns_test](https://user-images.githubusercontent.com/5900860/77900549-6b63db80-72a8-11ea-9a4d-35fdc4e95096.png)
