### ISSUE TITLE
Limit container's cpu usage in Rancher 1.6.17 (Cattle)

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#12957]
**Rancher versions:**
rancher/server: 1.6.17
**Docker version: (`docker version`,`docker info` preferred)**
1.13.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Try to set a limit on a container CPU usage in UI.
Smth like:
https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler
`--cpus=<value>`
`Specify how much of the available CPU resources a container can use. For instance, if the host machine has two CPUs and you set --cpus="1.5", the container is guaranteed at most one and a half of the CPUs. This is the equivalent of setting --cpu-period="100000" and --cpu-quota="150000". Available in Docker 1.13 and higher.`

**Results:**
Unable to find those options. Only CPU pinning & mCPU reservation can be set.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
