### ISSUE TITLE
awslog tag can't witch docker-compose but works from rancher-ui

### ISSUE THREAD

**Issue by intrasenze-app** [rancher/rancher#12954]
**Rancher versions:**
rancher/server: stable  1.6.16
rancher/agent:

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec:
network-services:
scheduler:0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17032
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aws
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
![image](https://user-images.githubusercontent.com/23076082/39080513-a183a8b4-4562-11e8-8248-329a3cbf9472.png)

setup from rancher ui , tag works.

but if we use rancher-cli
rancher --env ${RANCHER_ENV} up -d \
  --stack ${RANCHER_STACK} \
  --rancher-file ${RANCHER_COMPOSE_FILE} \
  --file ${DOCKER_COMPOSE_FILE} \
  --force-upgrade

![image](https://user-images.githubusercontent.com/23076082/39080517-ce1618f8-4562-11e8-9a1a-d78003f019f5.png)

lost the value of log tags 

**Results:**

**Comment by intrasenze-app** [comment]
cc @henry-zhang

**Comment by superseb** [comment]
It is interpreted as template, you can use `# notemplating` on top of the file to skip the templating as described here: https://rancher.com/docs/rancher/v1.6/en/cli/variable-interpolation/#escaping-double-brackets

Let me know if this doesn't solve the issue.

**Comment by henry-zhang** [comment]
not works , rancher cli drop the "# notemplating" to rancher-server
