### ISSUE TITLE
Not being able to reset default storage class

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12966]
Rancher versions: 2.0 master 04/23

Steps to Reproduce:
1. go to the storage class page
2. create a new storage class and set as a default
3. unset the default storage class is not working(either on the edit page) and a user can set more than one default storage class

![image](https://user-images.githubusercontent.com/4569037/39105744-2baf8a52-46ea-11e8-914f-a2ea533f0e53.png)

![image](https://user-images.githubusercontent.com/4569037/39105756-35b6e1bc-46ea-11e8-86e5-f8fea4bfc290.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/24
Verified fixed
