### ISSUE TITLE
Adding ldap authentication with group search base doesn't work as expected

### ISSUE THREAD

**Issue by mdferoz** [rancher/rancher#12962]
**Rancher versions:**
rancher/server: rancher/server:v2.0.0-beta3
rancher/agent: rancher/agent:v2.0.0-beta3

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

# uname -r
4.9.68.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Custom, vsphere VMs

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
K8S

**Steps to Reproduce:**
Try to configure LDAP/Acitve directory auth and provide a group search base as aprt of the config. This is the same working config as of our rancher 1.6.x environment. So, once the ldap config is validated by using simple user credentials and clicking on authenticate, the screen saves the config but it will show group search base as null. I tried searching for a group name, which was working in Rancher 2.0, Beta1 but seems to be broken in this beta3.

**Results:**

**Comment by vincent99** [comment]
https://github.com/rancher/ui/pull/1821

**Comment by tfiduccia** [comment]
Version - v2.0.0
Verified this is working.
