### ISSUE TITLE
How can i add ingress annotations in rancher 2.0?

### ISSUE THREAD

**Issue by yinfxs** [rancher/rancher#12967]
**Rancher versions:**
rancher/server:v2.0.0-beta3
rancher/agent:v2.0.0-beta3

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-693.2.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by gkTim** [comment]
Hi,

here is the documentation for annotations:
https://github.com/rancher/ingress-nginx/blob/master/docs/user-guide/annotations.md

**Comment by yinfxs** [comment]
thanks!

**Comment by dga26** [comment]
hi 

new url https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/, i loose too much time learning rancher ... if this can help someone ;)

**Comment by damendieta** [comment]
Hello to everyone.

I'm trying to use  nginx.ingress.kubernetes.io/from-to-www-redirect but it doesn't work.

I have tried.

![imagen](https://user-images.githubusercontent.com/4511272/80063304-3f302900-84fb-11ea-85e2-60ca8958c7bd.png)

And

![imagen](https://user-images.githubusercontent.com/4511272/80063373-6a1a7d00-84fb-11ea-89cc-6bd24e88e7f5.png)

None of them works. Does anyone got the www redirect working in Rancher 2.3.5?
