### ISSUE TITLE
catalog apps has create repeated pod in the ui because of  incorrect id

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12972]
Rancher versions: 2.0 master 04/23

Catalog apps has create repeated pod in the UI because of  incorrect id returned by the websocket.

Steps to Reproduce:
1. Go to Catalog Apps and install the MySQL chart
2. Go to the `Workloads` page, and the pods are showing with a repeated name
![image](https://user-images.githubusercontent.com/4569037/39117413-6b4bb2e2-4719-11e8-9fa2-7fdecac4699e.png)

`https://192.168.99.100/v3/project/c-k8nxx:project-52hgx/workloads/deployment:deployment:mysql-s8f8zh:mysql-s8f8zh-mysql`

**Comment by StrongMonkey** [comment]
@guangbochen not able to reproduce it. Can you retest?
