### ISSUE TITLE
Rancher metadata - container start date

### ISSUE THREAD

**Issue by AndresCas123** [rancher/rancher#12975]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Docker version: 17.12.1-ce
**Operating system and kernel: Ubuntu 16.04

Does the rancher container metadata have a field which I could use to know the actual date it started up?

Thanks!

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
