### ISSUE TITLE
When Host is stuck in "Removing" state , global service is stuck in "updating-active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1297]
Server version - V0.25.0-rc1

Have a Global service defined , so that we have containers running in all hosts.
Remove one of the host that is unreachable ( in my case the host was powered down).
This results in host being stuck in "removing" state and container in "stopping" state.

Service is stuck in "updating-active" .

Host eventually gets to "Removed" state after a while. 

At this point , I see the service is back to "active" state.

Should we expect that service to be not stuck in "updating-active" state when the instance is actually in "stopping" state ?

**Comment by alena1108** [comment]
@sangeethah, that should be fixed, could you please retest against the latest.

**Comment by sangeethah** [comment]
Tested with Server version - v0.47.0-rc1

Have a Global service defined , so that we have containers running in all hosts.
Remove one of the host that is unreachable ( in my case the host was powered down).
Host gets removed immediately and the global services scales down.
