### ISSUE TITLE
null is display for namespace when editing workload

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12973]
**Rancher versions:**
rancher/server:master 04/23

**Steps to Reproduce:**
1. Create a GKE cluster
2. Move namespace `cattle-system` to project `Default`
3. Edit the workload `cattle-cluster-agent`. The namespace is null:
![image](https://user-images.githubusercontent.com/1213386/39126797-e1db5036-4735-11e8-9700-f888c525f5bf.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/24
Verified fixed
