### ISSUE TITLE
How to fix Loadbalancer after deleting a linked Service

### ISSUE THREAD

**Issue by appinteractive** [rancher/rancher#12978]
**Rancher versions:**
1.6.14

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Create Service A & B
- Create Loadbalancer
- Configure Service A & B in Loadbalancer
- Delete Service B
- Try to Update Loadbalancer

**Results:**
Error Message: 'Validation failed in API: domain must be set'
**I can't edit the Loadbalanacer anymore!**

**Comment by AbhimanyuG** [comment]
Were you able to find a workaround for this?

**Comment by appinteractive** [comment]
yeah, recreating the lb from scratch ☹️

**Comment by AbhimanyuG** [comment]
ouch

**Comment by vloiseau06** [comment]
I had the same problem, I just remove stickiness config (set it to none), validate one time, and then set again the stickiness config. The error message disappear.

**Comment by appinteractive** [comment]
Thanks @vloiseau06 will try it the next time. Could save my day 😅

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by ws6** [comment]
+1 
this needs be addressed for high availibility
