### ISSUE TITLE
Can save Config map without Key, but UI shows it as required

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12991]
**Rancher versions:** 2.0 master 4/23

**Steps to Reproduce:**
1.  Add Config Map
2.  Save without adding a key

**Results:**  Config map saves even thou UI shows it as required.  Should Key be a required field?

**Comment by tfiduccia** [comment]
If the key is not required.  Then the red * should not be by the field name.

**Comment by loganhz** [comment]
As it is using the `form-key-value` component, if the `key` is empty, UI will drop the key-value pair and will not pass it to backend.

The behavior is the same with secret, dns, annotation, health check, flex-volume, engine options, host aliases of workload networking form, workload environments, alerting, logging,  RKE cloud-provider parameters.

I'm not sure what should we do for it.
