### ISSUE TITLE
As project owner/member , Editing cluster(non custom) results in generating agent command stuck in "loading" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12992]
**Rancher versions: Build from master
**Steps to Reproduce:**

Create a DO cluster and assign user - "test1" as owner/member to a project in this cluster.
When logged in as test1 , edit cluster.
Editing cluster(non custom) results in generating agent command stuck in "loading" state forever.

<img width="1345" alt="screen shot 2018-04-23 at 12 23 39 pm" src="https://user-images.githubusercontent.com/4266958/39149020-ac17baea-46f2-11e8-8ead-e6954143e072.png">

Also trying to "save" any changes , results in the same page being shown when there is actually a 403 error encountered.
```message
:
"clusters.management.cattle.io "c-rgrhr" is forbidden: User "u-4g9jc" cannot update clusters.management.cattle.io at the cluster scope"```

**Comment by sangeethah** [comment]
@loganhz  Trying to "save" any changes , results in the same page being shown when there is actually a 403 error encountered. Why is UI , not showing error message in this case ?
I have tracked this issue as well in this ticket.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/25
Verified fixed
