### ISSUE TITLE
Duplicate project entries in project/namespaces list view after adding namespace.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13005]
**Rancher versions:**  Build from master

**Steps to Reproduce:**

Create a project. 
Create a namespace.
When user is brought back to project/namespace list view , there is duplicate entries for project

<img width="1256" alt="screen shot 2018-04-23 at 4 39 54 pm" src="https://user-images.githubusercontent.com/4266958/39158448-fe38ddbe-4714-11e8-89cc-60687f7eadf9.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/24
Verified fixed
