### ISSUE TITLE
Unable to receive test email for email notifier 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13001]
**Rancher versions:**
Master 4/23/2018

Steps:
Create a new cluster.
Add a new email notifier. (smtp.office365.com 587 @rancher.com email account PW needs to be an app password)
Click test.

Results:
Test email is not received.
(Verified that emails are coming in with active alerts however.)

**Comment by zionwu** [comment]
@adingilloRancher  please refer to this issue https://github.com/rancher/rancher/issues/12618
>The Test button will not send out an email. It will just validate if the smtp config is valid or not by only calling the smtp auth API. The reason why we don't send out an email is that the test message is usually treated as spam by email provider.

**Comment by deniseschannon** [comment]
Sounds like a duplicate of #12618 and can be validated with the UI fix.

**Comment by adingilloRancher** [comment]
Closing issue.
