### ISSUE TITLE
Ingress update to a new workload doesn't work

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#13008]
Steps to reproduce:

1) Create 2 workloads.
2) Create ingress pointing to workload1
3) Update workload to point to workload2

Bug: ingress continues pointing to workload1. Happens because we store the workload ids in `ingress.cattle.io` annotation, and norman framework prohibits them from updates:

https://github.com/rancher/norman/blob/ff8494997727211e27971b50fc4cba243224f390/types/convert/merge/merge.go#L43

**Comment by sangeethah** [comment]
Tested with latest build from master:
Able to update Ingress to point to a new workload successfully.
But following 2 issues seen:

https://github.com/rancher/rancher/issues/13037
https://github.com/rancher/rancher/issues/13038
