### ISSUE TITLE
When namespace is moved between projects , it is not reflected in the project's deployment - namespace drop down list , unless UI is refreshed manually. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13009]
**Rancher versions: v2.0.0-beta4-rc1
**Steps to Reproduce:**
Create a cluster with 2 projects.
Test1  with "hello1" namespace
Test2  with "hello2" namespace

Move "hello1" namespace to Test2.
 
Go to "Test1" project and deploy a new workload. namespace drop down will still show "hello1".
Go to "Test2" project and deploy a new workload. namespace drop down will still not show "hello1"(only "hello2" shown).

Seems like we are missing events relating to namespace move.

**Comment by loganhz** [comment]
This should be fixed in https://github.com/rancher/ui/pull/1844
The root cause is the same with https://github.com/rancher/rancher/issues/12973

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/26
Verified fixed
