### ISSUE TITLE
Secrets list in workload deployment page includes tokens/certificates and registry entries.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13006]
**Rancher versions:rancher/server:v2.0.0-beta4-rc1

**Steps to Reproduce:**

Created a project scoped registry/certificate/secret.
Deploying a workload using "Inject Values From Another Resource" - choosing secrets , registry, certificate and secret get listed under "project"  and in "Namespace" we have a token listed.

<img width="1312" alt="screen shot 2018-04-23 at 4 51 56 pm" src="https://user-images.githubusercontent.com/4266958/39158793-de17e49c-4716-11e8-96f8-54859fa7ec53.png">

**Comment by loganhz** [comment]
@sangeethah how about the workload volumes section ==> add volume ==> use a secret.

Do we need to remove tokens/certificates/registry entries as well?

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/24
Verified fixed
