### ISSUE TITLE
UI Load balancer in two places, both 'service' and 'infrastructure'

### ISSUE THREAD

**Issue by keyscores** [rancher/rancher#1301]
As a user, I'm not always sure where to edit Load Balancer configs. You have it as both a service and as an infrastructure component.
I'm agnostic as to where it should be located, maybe leaning toward 'service'.
I think the user would prefer 'only one obvious way to do this'

**Comment by vincent99** [comment]
While I don't disagree, they are different things.  

The service tab has "load balancer services" that run `$scale` containers on automatically selected hosts to balance requests to 1 or more other **services** (which are then, in turn, made up of containers.)

The infrastructure tab has "load balancers" that runs container(s) on manually selected host(s) to balance requests to one or more other **containers**.

(And there's also "load balancer configs", which define part of a load balancer and can be reused.  These are particularly confusing and complicated and are going to be removed)

**Comment by sangeethah** [comment]
There are couple of issues about not allowing LB instances that are created as part of service to be updated from the LB view #947 , #946

**Comment by keyscores** [comment]
@vincent99 
I understand now. As feedback, it's not intuitive that this is the case.
Is it fair to say that the infrastructure tab allows you to have a more granular setting to a LB?  If so, then it is a special type of service.
Lastly, what % of the time do you think people will use this granular mode in the UI? I anticipate one would use the API or cli for this. So you may have the chance to simplify the UI without affecting many users.

**Comment by deniseschannon** [comment]
As of v0.28.0, there is no LB/LBConfig tabs under Infrastructure. This should clear up the confusion.
