### ISSUE TITLE
gce cluster workload "Group by Node" view alignment bad

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#13018]
Create a gce cluster, deploy some workload (or update the cattle-system, kube-system namespace to default project), then use the "Group by Node"
![image.png](https://images.zenhubusercontent.com/59bc85feb0222d5de477f15d/0433578b-61ec-499f-a8ca-1fa892881a4e)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/25
Verified fixed
