### ISSUE TITLE
Pipeline run info does not disappear though it is completed

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#13013]
**Rancher versions:**
master 4/24

**Steps to Reproduce:**
1. add a DO cluster
2. enable pipeline
3. run pipelines
**Results:**
Sometimes the run info does not disappear even if the pipeline is succeed.
![image](https://user-images.githubusercontent.com/5697937/39164252-12b3cb40-47b1-11e8-98ec-346316370145.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master 5/11 

I was not able to reproduce this. Executed ~20 pipeline runs, all went to successful and did not appear as still running.
