### ISSUE TITLE
The monitoring side can not do what you can do with ZABBIX

### ISSUE THREAD

**Issue by ares2017** [rancher/rancher#13019]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.16` Cattle: `v0.183.46` UI: `v1.6.42` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`containers.index`|

**Comment by vincent99** [comment]
This is not a constructive or actionable issue.  It is not zabbix, and there is an infinite set of possible things either cannot do.
