### ISSUE TITLE
API v3 Documentation

### ISSUE THREAD

**Issue by MarcErdmann** [rancher/rancher#13020]
Some important applications of mine rely on the Rancher API v2. In Rancher 2.0 API v2 seems to be completely replaced by API v3. Unfortunately I can not find a documentation of it. 
Will there be a documentation? If yes, when is the documentation scheduled?
In API v2 I was able to add a server to the cluster by making a POST request with a config as the payload to */projects/<projectID>/machines*. Is this possible in API v3 too?

**Comment by vincent99** [comment]
The UI is 100% static client-side HTML/JS, and the CLI is just an API client.  Anything they do can be by definition done through the API directly.

There will be docs eventually, but the documentation for the API is entirely generated from the API schema and frankly adds little to no value versus just going to the API in a browser and clicking around.  All the basic style, structure, authentication is the same as v1/v2-beta.  Specific types and their fields are essentially completely different.

You do not directly add individual nodes (machines) in 2.0.  Clusters managed by us (i.e. not things like Azure AKS) have one or more Node Pools, which have a quantity, roles and point to a Node Template.  The Node Template contains the API keys, region, instance size, etc for the node.

So from scratch:
  - Create Node Template (`/v3/nodeTemplates`)
  - Create Cluster (`/v3/clusters`)
  - Create Node Pool (`/v3/nodePools`) with quantity, cluster=(above), nodeTemplate=(above)

Once you have a cluster and pool, to add or remove nodes you just change the `quantity` field.

**Comment by MarcErdmann** [comment]
Thanks!
