### ISSUE TITLE
duplicate project show after create project

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#13027]
rancher/server:master 4/24

Reproduce steps:
1. create a cluster and get into the projects/namespaces menu
2. create a new project
3. click the `Add namespace` button in the project list to create a new namespace for the project.
4. I get 2 project with the same name

<img width="1298" alt="2018-04-24 5 28 41" src="https://user-images.githubusercontent.com/15376837/39178913-896a6ce2-47e5-11e8-8b91-7829ceac3fc8.png">

**Comment by loganhz** [comment]
Duplicated https://github.com/rancher/rancher/issues/13005
