### ISSUE TITLE
When there are 2 service links with same link name , only 1 of them is considered.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1302]
Server version - V0.25.0-rc1

Steps to reproduce the problem:
Create service S1.
Create service S2.
Create service S3.
Link S2 and S3 to service S1 with same link name - say "linkme"

Only one of the service link is programmed , usually the second service with the same service link is accepted.

Expected Behavior:
We should be able to link both S2 and S3 with the same link name.
If we cannot support this , API should error out with meaningful error message.

**Comment by vincent99** [comment]
This is impossible with the current API (link name is the key of the map), and just a bad idea in the new API (array of service+name pairs).  Can we just not allow duplicate names?

Problems on both sides:
  - With duplicate names: Which one wins?  Both?  Which environment variables get set?
  - Without: But what if you provide an "as name" that's the same as a linked service's actual name?  Or you rename a service after the fact?

**Comment by alena1108** [comment]
Now you can pass duplicated name for 2 diff services, so closing this bug. 

@vincent99 if there are 2 duplicated name, both services are going to "win". The name would resolve to instances of both services. No cross-services-link name validation is done at this point - I'm letting user to control it. We can add validation later on per request.

**Comment by sangeethah** [comment]
Tested with server version - V0.27.0-rc3
I am able to have a service linked to 2 services with same link name . Both service links get saved.
DNS resolution on the link name , resolves to containers from both the services.
