### ISSUE TITLE
[Rancher Catalog] When trying to deploy second heml app UI hangs.

### ISSUE THREAD

**Issue by ihardzeenka** [rancher/rancher#13032]
**Rancher versions:** 2.0:preview

1) I have created Project. 
2) Associated it with existing namespace
3) Added my Git repo with Helm charts: https://github.com/ibagomel/helm-charts
4) Deployed Zookeper.
5) When I'm trying to get into Catalog Apps to deploy Kafka UI just hangs.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/24
This is a bug, although they may be using the wrong version, we should not be hanging the application.
![image](https://user-images.githubusercontent.com/11514927/39215787-02e227f8-47ce-11e8-894b-fc24c2d00e71.png)

**Comment by tfiduccia** [comment]
Version - v2.0.0-beta4-rc4
Verified fixed
