### ISSUE TITLE
Remove "Default: latest boot2docker image" reference from vSphere Node Driver

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#13031]
We shoud remove the reference to boot2docker in the vSphere Node Driver.  boot2docker is just not recommended to use. This reference confuses our users and causes support headaches. 

If we want to provide a hint, we should encourage one of the flavors we test, like Ubuntu or RHEL.

**Rancher versions:**
1.6.x and 2.0.x

1.6
![image](https://user-images.githubusercontent.com/5324639/39194164-10a42a6c-47ab-11e8-8ab9-f6a0e3e5e6db.png)

2.0
![image](https://user-images.githubusercontent.com/5324639/39194502-e6d1f2b8-47ab-11e8-8da0-20d7735b141f.png)

**Comment by vincent99** [comment]
That _is_ the default, and have you ever used the vsphere driver?  Show me an Ubuntu or RHEL ISO URL that works with it.

**Comment by janeczku** [comment]
@vincent99 @jgreat RancherOS works with the vsphere docker-machine provider.

**Comment by olljanat** [comment]
I can confirm that this is now corrected on v2.0.3-rc1 version.

**Comment by adingilloRancher** [comment]
Setting is still referencing boot2docker

![screen shot 2018-06-27 at 1 02 09 pm](https://user-images.githubusercontent.com/38012481/41996640-614966b2-7a0a-11e8-80ad-34f4c753301c.png)

**Comment by olljanat** [comment]
@adingilloRancher I noticed same and found another reference to it.
It should be fixed on PR rancher/rancher#14092 which is waiting for approval

**Comment by vincent99** [comment]
@adingilloRancher The PR above is merged now

**Comment by adingilloRancher** [comment]
Master 6/28 Validated setting is correct
