### ISSUE TITLE
Ingress doesn't work on GKE

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#13035]
If you start GKE cluster with ingress enabled (there is an option that we are going to set in Rancher GKE driver), ingress controller will start, and it will take care of programming ingresses to Google LB.

Bug: when you create ingress pointing to workload in Rancher, the ingress won't get programmed. Happens because in the background Rancher creates a service of type ClusterIP for ingress workload(s), and Google LB can reach only services of NodePort type as it's a Global LB.

Solution: create NodePort service instead of ClusterIP

Things to test once fixed:

* make sure ingress with workload targets work on RKE
* test ingress create/update
* test ingress on GKE

**Comment by soumyalj** [comment]
Tested with v2.0.0-beta4-rc3.
Tested ingress on RKE cluster using Digital ocean hosts
Created a GKE cluster. Created a nginx workload and an ingress pointing to the workload.
Using the endpoint presented in the API, I was able to reach the targets.
Ex: wget --header='host: foo.bar.com' http://IP:80/name.html
