### ISSUE TITLE
Docs: External DNS and LB

### ISSUE THREAD

**Issue by keyscores** [rancher/rancher#1303]
I'm not sure what the best practice is for LB and DNS set up. 
I'm having a situation where the LB is being moved from one host to another, and this will break my app DNS patterns. 
I don't see any docs on this. What's the best practice today to point app.website.com to the LB

**Comment by deniseschannon** [comment]
@alena1108 Could you give him some best practice advice? In our next latest release, I believe we have enhanced our load balancer service to help his use case.

**Comment by alena1108** [comment]
@keyscores could you share your app DNS patters: 1) Is app.website.com and external service, or service registered within cattle? 2) Is app.website.com is the service that should be behind the load balancer, or service accessing some other services that are behind the load balancer?

If for example your app.website.com has 2 backend services, and you need to balance between them, your application can look like this in Rancher:

* 2 services - backend1 and backend2 - will represent the backend services of your App.
* Load Balancer service with backend1 and backend2 registered as LB targets. Lets name it "lb_app"
* Application service - the service your users will be accessing. Add link from this service to the Load balancer service. Each instance of the LB service now can be resolved to each instance of the Application service through Rancher DNS. You just have to configure your application to redirect the traffic to "lb_app" (name of the Lb service) via environment variable. You don't have to worry about the ip address of the lb instance behind "lb_app", or the host name - all your application needs to know is the lb service name.

Now all traffic coming to your application service, will get forwarded to the load balancer service, and load balancer service will redistribute the load between backend1 and backend2.

**Comment by vincent99** [comment]
I think what he's looking for is really scheduling rules on lbservices or the route53 integration we've talked about.  To actually use the load balancer from the outside world you need a public DNS entry that contains the IP addresses of the hosts that are running the lbservice containers.  And it needs to update somehow when one of the containers does and is started on another host with a different IP.

**Comment by keyscores** [comment]
@vincent99 Yes that that's exactly the issue. 
Suppose I have a public dns record pointing to ip 5.5.5.5 and that's the node where the load balancer is initially at.  Then suppose that Rancher, for any reason, degrades that service and it needs to be provisioned on ip 4.4.4.4 . What happens then? My DNS service (cloudflare) doesn't have health checks like route53. And even if it idid, Rancher creates new nodes through Digital Ocean api, and I will not have a choice of IP of the machines.

**Comment by keyscores** [comment]
I suggest you take a look at how Tutum is addressing this with 'endpoints' . It may not be infinitely scalable, but It does solve the issue of not caring what IP my loadbalancer is on.

**Comment by alena1108** [comment]
As we are going to keep track of "Public DNS Integration" feature in its own ticket -https://github.com/rancher/rancher/issues/1675 - closing the current one for now
