### ISSUE TITLE
Local Helm can't list deployed releases by Rancher

### ISSUE THREAD

**Issue by ihardzeenka** [rancher/rancher#13030]
Rancher 2.0:preview

**Steps to Reproduce:**
Deploy any app from Catalog

**Results:**
Go to your host where you have helm installed.
Try to do helm ls --all
Result will be empty.

**Explanation:**
It is happening because Rancher store tiller config map in namespace which was specified from UI to deploy app.
But it should store tiller config in kube-system to make it visible.

**Comment by StrongMonkey** [comment]
@ihardzeenka we don't use tiller in the latest build. Instead, we track the release info in rancher which you should be able to rollback the release you previously deployed.
