### ISSUE TITLE
 IO1 Incorrect option in AWS EBS PV Storage Class 

### ISSUE THREAD

**Issue by ts-mini** [rancher/rancher#13033]
**Rancher versions:**
rancher/server: master
rancher/agent: master

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 21
 Running: 18
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1054-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.508 GiB
Name: control-1.production.internalspectrumcluster.com
ID: O6YT:OG2K:GQ46:MNCY:DRVY:NFZK:CYHQ:AJIV:IOM5:H6GT:CCGS:U3EV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Steps to Reproduce:**
Create a storage class of IO1 on aws, set IOPS per gb to a value, attempt to provision a volume
**Results:**

pv_controller.go:1433] failed to provision volume for claim "mongodb/datadir-mongo-mongodb-replicaset-0" with StorageClass "highio": invalid option "opsePerGB" for volume plugin kubernetes.io/aws-ebs

```
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      field.cattle.io/creatorId: user-n4v8z
    creationTimestamp: 2018-04-24T17:00:40Z
    name: highio
    namespace: ""
    resourceVersion: "677218"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/highio
    uid: 04995da6-47e1-11e8-9d35-0a1b327227ee
  parameters:
    encrypted: "false"
    opsePerGB: "10"
    type: io1
  provisioner: kubernetes.io/aws-ebs
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
parameters show opsePerGB when it should be iopsPerGB
https://kubernetes.io/docs/concepts/storage/storage-classes/#aws

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/30
Verified fixed
