### ISSUE TITLE
When 2 labels with same key different values are provided for host, it does not get picked by scheduler for either of the values. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1304]
Server Version - V0.25.0-rc1

Steps to reproduce the problem:

Had a host with label -> name1=value1
Edited host and added another label -> name1=value2.
Labels showed up as name1=value1,value2.

When I try to create services with scheduling policy that requires host name to have labels name1=value1 / name1=value , containers dont get deployed in this host.

**Comment by sonchang** [comment]
Hi @vincent99 
Do we just merge labels for the scheduling rules or for all labels?  Within cattle right now, we just accept the merged values for the scheduling rule labels.  For all other labels, if they have the same key, they just overwrite each other just like in docker

**Comment by vincent99** [comment]
I currently comma-separated merge all things that become labels.

**Comment by sonchang** [comment]
I just checked and only the scheduling labels should be merging label values.  All others will just overwrite.  So labels:
foo=bar
foo=bat

will just be: foo=bat

**Comment by sangeethah** [comment]
Tested with Server Version - V0.27.0-rc4, when host is edited and a new label with same name but a different value is added , only the current value that is added is saved.

Closing this issue.
