### ISSUE TITLE
can not add volume in UI

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#13048]
*I can not choose any option in the choose volume menu*

![default](https://user-images.githubusercontent.com/3146226/39219933-51ac1d5c-4860-11e8-9a08-c273ff6361f9.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `master` UI: `v2.0.36` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by heww** [comment]
+1， the save issue

**Comment by heww** [comment]
that maybe issue from UI because my server works ok yesterday and it no upgrade, only the ui is update for it access the new version from releases.rancher.com

**Comment by yoke88** [comment]
using the lastest master buid ,the problem gone.
________________________________

**Comment by heww** [comment]
@yoke88 which lastest master build, ui repo or rancher repo ? thanks!

**Comment by yoke88** [comment]
UI 2.0.37 , pull the lastest rancher/server:master
________________________________

**Comment by heww** [comment]
en, add a secret works well, but add Registry Credentials not works.

**Comment by vincent99** [comment]
This is related to devices with touch events vs not.

**Comment by yoke88** [comment]
I have tried using chrome 66.0.3359.117 ,and IE 11.371.16299.0, no touch screens used.

**Comment by Tuckie** [comment]
Same problem running beta4. When connecting on a laptop with a touchscreen the selector is not working. Disabling touch events api in chrome://flags/ gets the dropdown working for me.

**Comment by vincent99** [comment]
This was fixed after beta4.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/30
Not fixed

**Comment by tfiduccia** [comment]
Verified fixed in v2.0.0
