### ISSUE TITLE
event Alerts don't mute

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13040]
**Rancher versions:** 2.0 master 4/24

**Steps to Reproduce:**
1.  Create a notifier
2.  Create an Event Alert that will fire when a Pod event happens
3.  Mute the Alert
4.  Create workload that has at least 1 pod

**Results:**  Alert fires.  Event alerts should not fire if they are muted.

**Comment by zionwu** [comment]
@tfiduccia , I followed the same steps but can't reproduce the issue.

1. created an alert 
![image](https://user-images.githubusercontent.com/1213386/39306941-19531e3a-4994-11e8-8605-858e7770f8e4.png)

2. created a workload with 1 pod, alert is fired:
![image](https://user-images.githubusercontent.com/1213386/39306988-33c7efb6-4994-11e8-9d30-f1e3586950f0.png)

3. muted the alert and created another workload with 1 pod. Alert is not fired.

Is  the `Alert Name` and `Target` field in the second alert the same as the first alert?
Is there multiple event alerts are created?

**Comment by tfiduccia** [comment]
@zionwu - 
1.  Not sure what you mean by that.  But I muted all alerts.  The alert fired and unmuted (the status said alerting)
2.  I did have multiple alerts and all were muted.
3.  I only changed the initial wait time to 5 second.

**Comment by tfiduccia** [comment]
@zionwu - I can no longer reproduce this.
