### ISSUE TITLE
beta would not come up, languages not rendered

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#13059]
**Rancher versions:**
rancher/server: >= 2.0beta2

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
hetzner

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Steps to Reproduce:**
`sudo docker run -d --name rancher2 --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:v2.0.0-bet3 --acme-domain yourdomain.com' 

**Results:**
yourdomain.com
<img width="832" alt="bildschirmfoto 2018-04-25 um 09 31 28" src="https://user-images.githubusercontent.com/1597621/39231962-113a78ac-486c-11e8-8485-f0864a18d34d.png">

**Comment by tfiduccia** [comment]
@exocode - I cannot reproduce your issue.  This looks like the rancher server is no longer available.  Have you tried to ssh into your server?

**Comment by exocode** [comment]
I close it, I deleted the whole server and started from scratch
