### ISSUE TITLE
Worker node stuck in "unavailable state" - with error "Runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13052]
**Rancher versions: v2.0.0-beta4-rc2

**Steps to Reproduce:**

Creates a DO cluster with following configuration:

3 etcd , 2 control and 3 worker nodes.

Cluster gets to "active" state. 

But one of the worker nodes get stuck in "unavailable state" - with error "Runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"

**Comment by sangeethah** [comment]
@moelsayed mentioned that this host had a very high load average ~ 13.

**Comment by moelsayed** [comment]
I haven't been able to reproduce this. As far as I can see on the host, load is constantly increasing, it spent several hours pulling and extracting the addon images, and they are failing to start due to the load. 

I tried to restart docker on the host but it didn't start back, load remained very high. I think this is a broken instance on DO, not a product issue.

**Comment by sangeethah** [comment]
I see the same behavior again with Ec2 instances this time.
All worker nodes stuck in "Registering" state 

<img width="1248" alt="screen shot 2018-04-25 at 10 13 51 am" src="https://user-images.githubusercontent.com/4266958/39261470-6cd39054-4871-11e8-9271-35eb669b3378.png">

docker hangs on this machine and has 100% cpu usage
```
top - 17:03:10 up 22 min,  1 user,  load average: 0.93, 0.62, 0.45
Tasks: 142 total,   1 running, 141 sleeping,   0 stopped,   0 zombie
%Cpu(s): 19.6 us,  4.3 sy,  0.2 ni, 74.8 id,  0.6 wa,  0.0 hi,  0.0 si,  0.5 st
KiB Mem :  4045212 total,  1501832 free,   404376 used,  2139004 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3276192 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                           
10274 root      20   0  755692 156268  27484 S 100.0  3.9   9:20.19 dockerd  
```

**Comment by deniseschannon** [comment]
@sangeethah with the changes we made between v2.0.0-beta4-rc3 and v2.0.0-beta4-rc4, i think this should be fixed. can you please verify?

**Comment by sangeethah** [comment]
Tested with v2.0.0-beta4-rc4

This issue is not seen any more.
