### ISSUE TITLE
Add label options to loadBalancerService

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1305]
Should be able to set scheduling options and labels on load balancer services.

**Comment by deniseschannon** [comment]
labels are not working on load balancer services (#1325)

**Comment by rschmukler** [comment]
Also environment variables would be nice!

**Comment by vincent99** [comment]
@rschmukler what would you do with environment variables on a balancer?

**Comment by qrpike** [comment]
Is this closed or still a WIP?

**Comment by rschmukler** [comment]
@vincent99 sorry on the delay, the environment variables would be useful if you are using something like  [jwilder/nginx-proxy](http://github.com/jwilder/nginx-proxy) to handle mapping `VHOST`s.

So for example:

Node-1 has `nginx-proxy` listening on `80` -> uses environment variable to forward to appropriate load balancer (say you have a load balancer for each service running on a node) which then forwards to the appropriate service.

**Comment by vincent99** [comment]
So you can do that if you run `nginx-proxy` as a (regular) Service.  But "Load Balancer Services" are specifically running our agent image with haproxy in it, and it does not respond to any environment variables.

Separately, we are working on Host header and Request URI-based targeting as first-class options in #544.

**Comment by rschmukler** [comment]
@vincent99 that looks good to me. Right now I am just running nginx-proxy and then have a super simple haproxy running on the same machine (with env variable), which then forwards to the load balancer.

The environment variables are actually parsed by the `nginx-proxy` image (which is monitoring the docker socket), so there isn't any responding to environment variables required, if it is present `nginx-proxy` will just pick up on it and take care of the appropriate networking.

#544 will address my use-case fully, so big +1 for that - right now everything is more or less a hack around it anyway.

**Comment by Kelindar** [comment]
+1 on the scheduling, we would need this to run on every host for a particular label as well.

**Comment by vincent99** [comment]
Setting custom labels + scheduling rules + internal-only balancing is in the UI in this week's release... Global scale ("run on every host that matches") is not, but not for any great reason.  It probably works in compose/the API though.

**Comment by Kelindar** [comment]
Nice. Would be good to have *global scale* in the UI as well.

**Comment by ibuildthecloud** [comment]
@alena1108 All scheduling rules already apply to LB through API and compose, right?

**Comment by vincent99** [comment]
QA tested scheduling LBs already before I did the UI work, but I didn't think to ask about global.

**Comment by vincent99** [comment]
Global is in the next build now too.

**Comment by deniseschannon** [comment]
Verified with v0.30.0-rc2
