### ISSUE TITLE
Feature Request : Helm answer file support edit the value.yaml

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#13064]
*when deploy a helm using app catelog , it 's easy to using UI to complete the complex task, but when feed the answer , Deeply nested data structures can be difficult to express in the UI*

for example , how to express the below data to ingress.annotations? it is easy to directly edit the yaml files.

``` text
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - user1"

```
![default](https://user-images.githubusercontent.com/3146226/39236189-b34e0f12-48aa-11e8-9034-ef91490ccb1f.JPG)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `master` UI: `v2.0.37` |
|Access|`local` `admin`|
|Route|`catalog-tab.launch`|

**Comment by yoke88** [comment]
**And The duplicated items when update items.**

![default](https://user-images.githubusercontent.com/3146226/39282527-4835a2e8-493c-11e8-8806-03bbf9fa18e1.png)

**Comment by yoke88** [comment]
**Deployed Helm app has no name displayed just "/"**

![default](https://user-images.githubusercontent.com/3146226/39282639-cf868294-493c-11e8-805d-cca86965484b.JPG)

![default](https://user-images.githubusercontent.com/3146226/39282656-e7a469cc-493c-11e8-9e32-9421667835a0.JPG)

**Comment by yoke88** [comment]
i can delete the duplicated item with API, but can not do it just using UI

**Comment by loganhz** [comment]
@StrongMonkey Can you fix the issue that UI can not remove answer via `upgrade` action, please?

**Comment by deniseschannon** [comment]
@loganhz it seems that the original poster says he can do it with API, so wouldn't this be a UI issue?

**Comment by tfiduccia** [comment]
@deniseschannon - So we fixed the delete on upgrade, but didn't address his original issue?  Which was how to add multiple ingress.annotations through the UI?

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified Edit as YAML button, no duplicates and that you can delete them.
Verified fixed
