### ISSUE TITLE
[Load Balancer] Problem with dot and dash in subdomain

### ISSUE THREAD

**Issue by BlackDark** [rancher/rancher#13062]
Hi,
i have a problem with the load balancer in creating routing rules for nearly identical domains.
They only differ in the usage of dot and dash.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/9947112/39235108-4b4ceb3e-4875-11e8-84a2-d3409508137a.png)

The problem is that both address now point to the upper rule.
After checking the haproxy.cfg i found those entries:

```
acl 80_restya_sparks_rd_corpintra_net__host hdr(host) -i restya-sparks.rd.corpintra.net
acl 80_restya_sparks_rd_corpintra_net__host hdr(host) -i restya-sparks.rd.corpintra.net:80
use_backend 80_restya_sparks_rd_corpintra_net_ if 80_restya_sparks_rd_corpintra_net__host

acl 80_restya_sparks_rd_corpintra_net__host hdr(host) -i restya.sparks.rd.corpintra.net
acl 80_restya_sparks_rd_corpintra_net__host hdr(host) -i restya.sparks.rd.corpintra.net:80
use_backend 80_restya_sparks_rd_corpintra_net_ if 80_restya_sparks_rd_corpintra_net__host

backend 80_restya_sparks_rd_corpintra_net_
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_proto
mode http
server 79b6465c3881a1fe6876e68d5d76a1d8db16a703 10.42.161.2:80
```
It seems that the load balancer doesn't differ between subdomain dot and dash?

**Rancher versions:**
rancher/server: v1.6.16
rancher/agent: v1.2.10

**Infrastructure Stack versions:**
healthcheck: v0.3.6
ipsec: v.0.13.11
network-services: v.0.10.2 (metadata), v0.7.20 (network-manager)
scheduler: v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-79-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Virtual machine (bare-metal?)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Create LB with 2 longer subdomain structures which only differ in the last domain in regards of dot and dash. See screenshot.
Both domains should point to the service of the upper rule.

**Results:**

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
