### ISSUE TITLE
Logging elasticssearch with HTTPS

### ISSUE THREAD

**Issue by OBenned** [rancher/rancher#13065]
Hello.

Would it be possible to add the possibility to switch on and off FLUENT_ELASTICSEARCH_SSL_VERIFY with the built-in fluentd logging?
This is since there would be many times where you use self-signed certs for the elassticscluster

This is for rancher 2.0

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/10

SSL_VERIFY can be disabled for elasticsearch.

Setup ES cluster
Enabled TLS on transport / http layers with self-signed cert
Enable SSL verify = unable to connect
Disable SSL verify = connection successful
