### ISSUE TITLE
Network Problem for Mysql Charts

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#13060]
Version: rancher/server:master 4/24
Step:
1. Create a DO cluster
2. Launch a mysql Charts from library
![屏幕快照 2018-04-25 下午4.17.38.png](https://images.zenhubusercontent.com/59c9bf65b0222d5de4791a2d/3738c22c-e03c-43ee-b602-73252884c850)

Result
After deploy a mysql charts, canal network brokes
![屏幕快照 2018-04-25 下午4.23.17.png](https://images.zenhubusercontent.com/59c9bf65b0222d5de4791a2d/a6ee7288-6c06-4537-a124-2c03b4cccc76)

**Comment by leodotcloud** [comment]
https://github.com/projectcalico/libcalico-go/issues/770

**Comment by guangbochen** [comment]
canal verified fixed on master 04/26

**Comment by kingsd041** [comment]
calico verified fixed on master 04/26
Close it.
