### ISSUE TITLE
k8s 1.10 does not work with ec2 and aws cloud provider because we are unable to add EC2 tags when using node driver

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13069]
Version: master 4/25
UI: v2.0.37

No option to add EC2 tags when creating a node.

As k8s 1.10 will be the default, we should consider setting the necessary tag to the instance by default. (Key: `kubernetes.io/cluster/$CLUSTERID` Value: `owned`)

**Comment by superseb** [comment]
When the ClusterID tag is not set, `kubelet` will fail (logging below). So ability to add tags will be required when using k8s 1.10.

Even better when we can add it/suggest it by default in the UI.

```
I0425 21:00:17.630005   14102 aws.go:1026] Building AWS cloudprovider
I0425 21:00:17.630031   14102 aws.go:988] Zone not specified in configuration file; querying AWS metadata service
E0425 21:00:17.816642   14102 tags.go:94] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
F0425 21:00:17.816676   14102 server.go:233] failed to run Kubelet: could not init cloud provider "aws": AWS cloud failed to find ClusterID
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/26
Verified fixed

**Comment by deniseschannon** [comment]
Reopening as we should have a backend fix as well for docker-machine if users use API.

**Comment by deniseschannon** [comment]
This should be tested in the API or CLI as the UI is working but we need to confirm it still works with API and *not* explicitly setting any tags.

**Comment by sangeethah** [comment]
Tested with latest build from master
Able to create a cluster successfully using  "Amazon EC2" setting provider to "Amazon" (having iamInstanceProfile set in the node template) with following configurations:

1. node1 - control 
2. node2 - etcd 
3.node3 - worker.

All nodes (including worker) get to "active" state.
Able to deploy workloads successfully.
Able to create LB (L4 Balancer) successfully for the workloads.

**Comment by DevOpsRoot** [comment]
I've tried with the v2.0.0-beta4.. the problem does not seem solved with the same configuration as you ! @sangeethah 

There is no more master tag ?

```
I0430 06:57:33.794050   10295 aws.go:988] Zone not specified in configuration file; querying AWS metadata service
E0430 06:57:34.019081   10295 tags.go:94] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
F0430 06:57:34.019192   10295 server.go:233] failed to run Kubelet: could not init cloud provider "aws": AWS cloud failed to find ClusterID
```

**Comment by DevOpsRoot** [comment]
I have add tags after the deployment and i get a this error : 

```[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [10.11.6.119]. Response code: [500], response body: [+]ping ok [-]etcd failed: reason withheld [+]poststarthook/generic-apiserver-start-informers ok [+]poststarthook/start-apiextensions-informers ok [+]poststarthook/start-apiextensions-controllers ok [+]poststarthook/bootstrap-controller ok [+]poststarthook/rbac/bootstrap-roles ok [+]poststarthook/ca-registration ok [+]poststarthook/start-kube-apiserver-informers ok [+]poststarthook/start-kube-aggregator-informers ok [+]poststarthook/apiservice-registration-controller ok [+]poststarthook/apiservice-status-available-controller ok [+]poststarthook/apiservice-openapi-controller ok [+]poststarthook/kube-apiserver-autoregistration ok [+]autoregister-completion ok healthz check failed```

**Comment by DevOpsRoot** [comment]
@superseb, do you know what is going on ?

**Comment by ballerabdude** [comment]
This issue is fixed. The latest version is 2.0.0-rc3. That’s currently the preview docker tag.

- Abdul Hagi
________________________________

**Comment by superseb** [comment]
@DevOpsRoot When using the Amazon EC2 node driver/node templates, the ClusterID tag should be set automatically when using `rancher/rancher:v2.0.0-rc3`. If you are using Custom nodes (using `docker run`), then you should set the tags on the nodes yourself.
