### ISSUE TITLE
Failed to get kubernetes node

### ISSUE THREAD

**Issue by MouadMimouni** [rancher/rancher#13061]
Rancher versions: v2.0.0-beta3
Docker version: 17.03.2
Operating system and kernel: Ubuntu 16.04
Type/provider of hosts: (Virtual machine Vmware)
-----
Hello everybody,
I set up a Docker server to test the new version of Rancher, my server is set up on a vmware virtual machine with 4 GB of RAM and a version of Docker 17.03.2, trying to launch a cluster in Custom I have the following error: "Failed to get kubernetes node [DR-VM]:" DR-VM "not found", knowing that DR-VM is the name of my Docker server.
Thanks for your help.

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/12499

Workaround is to use lowercase only, or test using `v2.0.0-beta4-rc3` which is still in testing phase.
