### ISSUE TITLE
Unable to see full logs of a step

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#13068]
**Rancher versions:**
master 4_25

**Steps to Reproduce:**
1. Add a `run a script` step with following scripts
```
for page in $(seq 1 100)
do
        echo $page
        sleep 1
done
```
run the pipeline
**Results:**
When the pipeline is running, I'm not able to see the full content of previous printed logs.
![image](https://user-images.githubusercontent.com/5697937/39239001-4ca11324-48b2-11e8-9380-a75443124d92.png)

**Comment by gitlawr** [comment]
because Jenkins trims the logs in the API
![image](https://user-images.githubusercontent.com/5697937/39239714-4e9f0f4e-48b4-11e8-83f0-2e361273f45c.png)

**Comment by gitlawr** [comment]
Related Jenkins plugin code: 
```
https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/pipeline-stage-view-2.10/rest-api/src/main/java/com/cloudbees/workflow/rest/external/FlowNodeLogExt.java#L116
```

**Comment by bmdepesa** [comment]
Validated on rancher/rancher:master 4/27. 

I was able to see the full execution log for the jenkins job.
