### ISSUE TITLE
SSH never becomes "available" for hosts in clusters from multiple templates

### ISSUE THREAD

**Issue by zchef2k** [rancher/rancher#13078]
rancher/server:master (4/24/2018)

vsphere (ESXi) 6.5.0
any kubernetes version

**Steps to Reproduce:**
Deploy a cluster made up of hosts from a single node template, it succeeds.

Create one or more additional node templates and deploy a cluster made up of hosts from one or more of those templates. Only hosts from one template make it past the "Waiting for SSH" step, even though all hosts have valid networking. 

Remove  hosts from **_any_** combination of templates so that only one template remains. Deploy a cluster, it succeeds.

**Comment by zchef2k** [comment]
Well, using rancher/server:v2.0.0-beta4-rc4, (with the original 17.03-ce b2d image, not the mount 'fix' version floating around), I am able to deploy a cluster using more than one node template.

![image](https://user-images.githubusercontent.com/743910/39269453-da2bd8a8-48a0-11e8-98dd-b42c0a1fc840.png)

I'm not sure where this leaves you with the AWS or DO driver....

**Comment by StrongMonkey** [comment]
for aws, i think using different region would fail because `[network] Port check for ports: [172.20.0.153:2380, 172.20.0.153:2379] failed on host: [1.2.3.4]`  port check would fail.

**Comment by galal-hussein** [comment]
@StrongMonkey yes we do, if internal address is not set, then we use public address

**Comment by loganhz** [comment]
I can not reproduce this issue in v2.1.0 with two node templates in different regions.
