### ISSUE TITLE
Cluster name should be required and unique

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13075]
Version: master 4/25

Although technically not required, we should make Cluster Name required and unique. It's a better user experience for:

- Users to be warned when accidentally creating a cluster with the same name (this can also happen with multiple users/admins)
- Users to not be confused when multiple clusters with the same name exists (2 Users creating cluster named `A` and unknown which is which, apart from specific settings maybe)
- Users to find their cluster by name instead of the ID (which they may forget/close browser/end of day)
- Using automation, you get an error when creating the "same" cluster again (same being the same name, with the drawbacks mentioned above)

**Comment by vincent99** [comment]
This really should be enforced in the API if we're going to do it.  The UI isn't going to be involved in "automation".

**Comment by tfiduccia** [comment]
API needs to take care of this.  We have put in a fix in UI in meantime.

**Comment by loganhz** [comment]
Reverted the UI change. Please add the validation in backend.

**Comment by sangeethah** [comment]
Tested with latest build from master.
When trying to create cluster with a cluster name that is already associated with another cluster, API fails with error message - "Validation failed in API: Cluster name is not unique"

```
{"actionLinks":{},"baseType":"error","code":"NotUnique","fieldName":"Cluster name","links":{},"message":"","status":422,"type":"error"}
```
When trying to create cluster with no name, API fails with error message - "Validation failed in API: Cluster name is required"

```
{"actionLinks":{},"baseType":"error","code":"MissingRequired","fieldName":"Cluster name","links":{},"message":"","status":422,"type":"error"}
```
