### ISSUE TITLE
Add OS details in Nodes view

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13071]
In v1.6, we have a `Infrastructure` -> `Hosts` view showing us:

- Host OS
- Host kernel
- Docker version

This makes it easy to spot differences in OS/kernel/Docker when troubleshooting a cluster.

```
"os": {
"dockerVersion": "17.3.2",
"kernelVersion": "4.4.0-119-generic",
"operatingSystem": "Ubuntu 16.04.4 LTS"
}
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/25
Verified fixed

**Comment by superseb** [comment]
This was added in the Node view and not in the Nodes view.

To emphasize why this is important to have:

- Easily see OS in a cluster (possibly problems related to OS)
- Easily see kernel in a cluster (possibly upgraded and activated on reboot, can be source of many issues)
- Easily see Docker version (Could also be upgraded, can be source of many issues)

In 1.6 a great amount of issues was discovered just by checking the Hosts view and seeing those variables.

**Comment by loganhz** [comment]
Docker version has been added in node list view. it's already a very busy table. 
@vincent99 should we add OS and kernel info in node list view? If yes, where should we put them?
