### ISSUE TITLE
Search in Clusters view should search in Name by default

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13073]
Version: master 4/25

When using Search in Clusters view, all attributes are searched instead of just Name. For quick filtering it should default to Name, and have a toggle or an extended/advanced search for selectable/all attributes

<img width="1435" alt="screen shot 2018-04-25 at 16 00 25" src="https://user-images.githubusercontent.com/2620179/39250785-f7c56ea0-48a1-11e8-8400-fb96722f2a94.png">

**Comment by superseb** [comment]
It's a generated Node ID if I remember correctly, it can be found by looking up the cluster info in the API.

**Comment by loganhz** [comment]
Please reopen it if you think it's still a problem. Thanks
