### ISSUE TITLE
Ingress not functional in Amazon EKS cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13086]
**Rancher versions:**
rancher/server: v2.0.0-beta4-rc3

**Steps to Reproduce:**
1. Create a Amazon EKS cluster 
2. Create a workload with nginx image
3. Create an ingress pointing to the workload

Accessing the ingress from any of the node IPs does not resolve to the desired targets

```
wget --header='host: foo.bar.com' http://nodeip:80/name.html
--2018-04-25 11:41:48--  http://nodeip/name.html
Connecting to nodeip:80... 
```
If the Amazon creates its own resource for the ingress, then the right endpoint should be provided to access the ingress.

**Comment by deniseschannon** [comment]
@dramich it seems that ingress might be only WIP in EKS even as of GA, so we just need to monitor when it's working in EKS to add in integration

**Comment by superseb** [comment]
See https://docs.google.com/document/d/1h6nfuE2DWTLsnJCHdJ7jq5lYVLW_tWOlDtUVNL5OGs8/

```
AWS Subproject: aws alb ingress controller based on CoreOS alb ingress controller

Summary:
AWS is endorsing and actively contributing to CoreOS’ alb-ingress-controller as the preferred Ingress controller for ALBs as an Ingress load balancer for workloads running on EC2 hosted k8s clusters.

Motivation:
We want to extend a popular implementation of the Ingress controller to better utilize existing and planned ALB functionality to reduce barriers to adoption for customers with ingress-based k8s workloads on EC2.

The main benefits of the CoreOS implementation include direct management of AWS resources directly, faster exposure to new features by contributors both from AWS and the community, and use of L7 routing functionality of ALB, that eliminates the need for customers to manage their own routing solution and enables simpler application deployments.

It is expected to be used on Kubernetes clusters on EC2 and on EKS.
```

**Comment by cjellick** [comment]
TODOs:
1. investigate what is causing this. Is this our problem or the providers? Determine if it should be documented.
2. Determine if this could be solved by cluster capabilities?

**Comment by StrongMonkey** [comment]
I think this is still WIP.
There is no official documentation about how ingress controller is deployed when you created a EKS cluster. Also when you create a EKS cluster, there is no ingress controller deployed by default. To get ingress working, you have to deploy nginx-ingress or other third party ingress controller like alb and elb.

**Comment by cjellick** [comment]
Cluster capabilities feature will ultimately address this, but for 2.1, we'd like a warning that tells the user that they would need to deploy their own ingress controller.

**Comment by cjellick** [comment]
Moving this out of the release. We'll open a separate UI issue for the note/warning.

**Comment by westlywright** [comment]
warning ticket tracked at: rancher/rancher#15496

**Comment by michalmikolajczyk** [comment]
One use case we have, is to deploy multiple feature branches, which works well with RKE-provisioned clusters, which have a working Ingress controller – we simply point a wildcard domain to the cluster `*.example.com`, then create ingresses for the environments with hostnames `123-feature.example.com`.

I followed @superseb's comment https://github.com/rancher/rancher/issues/13086#issuecomment-398777390 directing to this _AWS ALB Ingress Controller for Kubernetes_ https://github.com/kubernetes-sigs/aws-alb-ingress-controller, further documented here https://aws.amazon.com/blogs/apn/coreos-and-ticketmaster-collaborate-to-bring-aws-application-load-balancer-support-to-kubernetes/

Another article by https://medium.com/@dmaas/amazon-eks-ingress-guide-8ec2ec940a70 pointed to the Helm chart for that ALB https://github.com/helm/charts/tree/master/incubator/aws-alb-ingress-controller

So… **any plans on supporting this with Rancher?** Seems like the plan was to release with `2.2`, and there are more open Issues around the same problem for other providers e.g. #13088

**Comment by cjellick** [comment]
I don't think this will make it into v2.2.0. Unfortunately, we  don't have the bandwidth for it in this cycle

**Comment by michalmikolajczyk** [comment]
Managed to obtain a working, possibly cross-platform solution for this – the Helm chart Nginx Ingress Controller https://hub.helm.sh/charts/stable/nginx-ingress

That controller works by using the cloud provider to deploy an ELB (layer 4 classic-type load balancer) on AWS, exposes the ports 80 and 443 to it, and then handles the routing on the cluster-side, which is controllable from Rancher's projects _Load Balancing_ view. 

Tested with an EKS cluster, worked well out of the box.

**Comment by jpd-dds** [comment]
@michalmikolajczyk can you provide more details on how to do this?

**Comment by michalmikolajczyk** [comment]
@jpd-dds hey, yeah, I basically installed the Helm chart "Nginx Ingress Controller", into the `System` project, on my EKS cluster. I did so using Rancher UI:

_System_ project --> Catalogue Apps --> Launch --> _Nginx-ingress_

It installed into its own namespace `nginx-ingress`, but I initially tried with another Helm chart, Traefic Ingress Controller, and there the recommendation was to install into the `kube-system` namespace.

After installing, I would just normally start deploying Ingress LBs, using Rancher UI. Just like on a standard cluster, which has an Ingress Controller :)
