### ISSUE TITLE
Fully Automatable 2.0 Setup

### ISSUE THREAD

**Issue by eedwards-sk** [rancher/rancher#13080]
## Summary:

When provisioning a rancher stack, I would like to fully automate the first-time setup procedure for the UI/admin.

Currently, thanks to #12947 I can get past the admin password prompt by resetting the password first.

However, it still asks me for the server URL.

I want to be able to do ALL of the steps that currently require a UI through automation: https://rancher.com/docs/rancher/v2.0/en/quick-start-guide/

Requiring any explicit UI interaction is very un-friendly to devops-oriented workflows.

Thanks!

## Details:
**Rancher versions:**
rancher/server: docker image rancher/server:v2.0.0-beta4-rc3
rancher/agent: n/a

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:	18.04.0-ce
 API version:	1.37
 Go version:	go1.9.2
 Git commit:	3d479c0
 Built:	Tue Apr 10 18:14:11 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.04.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	3d479c0
  Built:	Tue Apr 10 18:23:35 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-boot2docker
Operating System: Boot2Docker 18.04.0-ce (TCL 8.2.1); HEAD : b8a34c0 - Wed Apr 11 17:00:55 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.6MiB
Name: rancher-master
ID: UHCV:NCYY:TNUG:YCXT:DT4G:3SHH:WDMF:U2LE:MAAM:4ZE7:AYCK:5NAK
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME=Boot2Docker
VERSION=18.04.0-ce
ID=boot2docker
ID_LIKE=tcl
VERSION_ID=18.04.0-ce
PRETTY_NAME="Boot2Docker 18.04.0-ce (TCL 8.2.1); HEAD : b8a34c0 - Wed Apr 11 17:00:55 UTC 2018"
ANSI_COLOR="1;34"
HOME_URL="http://boot2docker.io"
SUPPORT_URL="https://github.com/boot2docker/boot2docker"
BUG_REPORT_URL="https://github.com/boot2docker/boot2docker/issues"
```
```
4.9.93-boot2docker
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox / docker-machine

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Just starting up a single admin node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
2.0, so Kubernetes?

**Steps to Reproduce:**
Create new docker-machine
Start a rancher server
`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:v2.0.0-beta4-rc3`

**Comment by eedwards-sk** [comment]
Hi @superseb 

I really appreciate you providing that gist.

I still believe this should be logged as a feature request or similar, for at least documenting these APIs

I don't believe having to MITM capture web traces, to figure out the api, is an acceptable solution for a product designed around CI/CD/automation.

Thanks again.

**Comment by superseb** [comment]
The product is in beta, docs will follow shortly. These will probably not address your request for docs on API yet, but in the mean time you can use this method.
