### ISSUE TITLE
internal load balancer

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1308]
Is it possible to create a load balancer that does not bind to the public ports on a machine but instead is just used for routing internal requests? I would like to put a load balancer in front of an internal service and have other services talk to said service via the load balancer and not directly to those services.

**Comment by deniseschannon** [comment]
Currently, this is not supported, but I've added it as an enhancement request.

**Comment by defunctzombie** [comment]
Just to add a bit more clarification to this. It would be similar to how regular services are launched where I don't specify any `PORTS` in the config for the service. These services just make themselves available on their overlay network IP:PORT

**Comment by nguyenvanhau** [comment]
+1

**Comment by alena1108** [comment]
you would still need to define the ports as even internally LB has to be configured to listen on the specific ones. Its just we should give a choice whether to publish them or not.

**Comment by vincent99** [comment]
This is in the next release.  In compose.yml the internal ports go in `expose:`.

**Comment by vincent99** [comment]
(Preexisting-dup of #1433)

**Comment by defunctzombie** [comment]
:+1: 

Will docs be added accordingly once released?

**Comment by deniseschannon** [comment]
@defunctzombie Yes,we aim to add in docs on the updated features before we tag a new latest release.

**Comment by vincent99** [comment]
Yes; basically you set the listening ports in `expose` instead of `ports` for compose, or there's a drop down in the UI.
