### ISSUE TITLE
Cattle should respect x-forwarded-{host,proto}

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1309]
Amazon ELB does not appear to have a way to send `X-API-Request-URL: https://full.url/of/the/request`.  We should just support the standard headers so it's possible to put Rancher behind ELB (with appropriate`api.redirect.ui.path` and `api.allow.client.override` set).

Ping @ibuildthecloud @cloudnautique (via @stefanfoulis)

**Comment by cjellick** [comment]
For the record, @ibuildthecloud said in slack that x-forwarded-{host,proto} should either jsut be always on or at least defaulted to on.

Any opinion on this before I implemented like that  @vincent99 or @cloudnautique?

**Comment by cjellick** [comment]
Unfortunate (re)discovery: AWS ELB does not support web-sockets, so we cannot put Rancher behind and ELB without seriously hindering functionality.

**Comment by cjellick** [comment]
We now support Host, X-Forwarded-Port, and X-Forwarded-Proto, but ELB does not support websockets, which we make heavy use of.

To get rancher working behind an ELB, we need to support the Proxy protocol. See #1677

**Comment by sangeethah** [comment]
Tested with rancher/server:v0.31.0-rc1

Able to bring up a rancher-server with SSL behind Nginx as https reverse proxy.
Following are the steps followed:

```
docker run -d --restart=always --name=rancher-server -e "CATTLE_API_ALLOW_CLIENT_OVERRIDE=true" rancher/server:v0.31.0-rc1
mkdir /root/nginx

docker run -d -p 80:80 -p 443:443 -v /root/nginx/ssl:/etc/nginx/ssl/:ro -v /root/nginx/rancher.io.conf:/etc/nginx/conf.d/rancher.io.conf:ro --link='rancher-server' nginx

nginx confifuration used:

upstream rancher {
    server rancher-server:8080;
}

server {
    listen 443 ssl;
    server_name <servername>;
    ssl_certificate /etc/nginx/ssl/rancher.io.bundled.crt;
    ssl_certificate_key /etc/nginx/ssl/rancher.io.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name <servername>;
    return 301 https://$server_name$request_uri;
}
```
Able to add custom hosts , Digital Ocean hosts to rancher server successfully.
Able to view host stats.
Able to view container logs and also exec shell.
Basic sanity checks to make sure that the connectivity between containers from different hosts work.
