### ISSUE TITLE
Config Map & Secret Volume is not displaying properly in workload details page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13090]
**Rancher versions:** v2.0.0-beta4-rc4

**Steps to Reproduce:**
1.  Create a config map and a secret
2.  Create a workload and add two volumes (one using the config map and one using the secret)
3.  Go to the workload details page and view the volume section

**Results:**  Volume section is not displaying the config & secret information properly.  Config map is missing all the config map information.  Secret is showing a drop-down radio button options that I can change.
![image](https://user-images.githubusercontent.com/11514927/39269598-3363096e-4888-11e8-8457-bf240b892f09.png)

**Comment by loganhz** [comment]
UI sends the project level secret Id to backend, but server populated a namespace level secret.

![image](https://user-images.githubusercontent.com/21168270/39286290-ab8bdfde-494f-11e8-9ca1-ec18174f40c7.png)

![image](https://user-images.githubusercontent.com/21168270/39286325-d1334894-494f-11e8-9e86-897a75015d69.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/26
Verified fixed
