### ISSUE TITLE
Active Directory login with domain name prefixed is not working

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#13109]
**Rancher versions:**
Rancher master

**Steps to reproduce**
1. While configuring AD, leave Default Login Domain field empty
2. For service account and 'your username' fields, provide the usernames prefixed with domain name

**Expected**
AD should be configured

**Actual**
Error is thrown
<img width="1437" alt="screen shot 2018-04-25 at 6 07 19 pm" src="https://user-images.githubusercontent.com/10672776/39280575-f7ffc5ba-48b4-11e8-82ec-5d58b2b96be6.png">
The code panics too

Same error is seen if auth is setup, and you try to login by providing username prefixed with domain name

**Comment by adingilloRancher** [comment]
missed adding domain to service account user name. verified.
