### ISSUE TITLE
[cli] Add catalog command

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#13101]
Catalog will require three pieces, working with the catalog, working with the templates and finally working with apps that get created from the templates. 

catalog: add, list, delete

**Comment by ibuildthecloud** [comment]
I believe we use the term rollback in the UI and API, not revert.  Let me if it's not.  We should be consistent.

**Comment by dramich** [comment]
Available in v2.0.1-rc1

**Comment by sangeethah** [comment]
Tested with v2.0.1-rc1

Able to add/delete and list catalogs using ```rancher catalog``` commands.
