### ISSUE TITLE
Rancher healthchecks cause high CPU

### ISSUE THREAD

**Issue by dindurthy** [rancher/rancher#13107]
**Rancher versions:**
rancher/server: 1.6.15
rancher/agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck:  0.3.6
ipsec: 0.13.11 (router)
network-services: 0.7.20
scheduler: 0.8.3
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 183
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-1013-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-172-21-84-206
ID: L7ZS:7P6G:5H6P:PK2P:B7C2:6SWH:4YZ4:PN7C:JABI:5NGB:7OLM:BTYQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-1013-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher + External Aurora RDS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
* Create a rancher LB with 200 ports exposed, mapped to 200 ports on a single service
* Setup a healthcheck on the single service resembling this:
```
  app:
    scale: 6
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 3000
      unhealthy_threshold: 3
      initializing_timeout: 100000
      interval: 2000
      strategy: recreateOnQuorum
      request_line: GET "/health" "HTTP/1.1"
```

**Results:**
We observe extremely high CPU.  It's very dramatic:
![screen shot 2018-04-25 at 4 47 11 pm](https://user-images.githubusercontent.com/14302694/39278506-5c78c7e2-48a8-11e8-92b4-463b6fb7f3fc.png)

Logging the healthcheck route shows it logs hundreds of times a second.  Seems like the health check is scaling with the number of ports.  Not sure why that would be.  We don't see this on other services scaled similarly on the same number of hosts with only one port load balanced.  We're stuck with this number of ports exposed for now.

Increasing the check interval to 5 minutes substantially reduces this load, but upgrades take forever.  Strangely, containers can be marked healthy even if the interval is several times greater than the initialization_timeout.  I can see the health route getting hit several times a second even with such a long check interval.  With an interval of 5 minutes and an initializing timeout of ~2 minutes, containers start successfully ~50% of the time, with the remainder starting and stopping a few times before they lift successfully.  Those containers that do lift tend to lift promptly, within ~30s of the container starting, while the others timeout, stop, and reinitialize.  Extending the initialization timeout to 5 minutes didn't seem to affect the success rate.  It ends up taking 30mins-1hr to upgrade this one service with 6-8 containers.

We've tried a few things.  We've tried upgrading without healthchecks, but we've noticed loadbalancer configuration loads inconsistently as service upgrades roll through.  That is, we've seen new containers load without the haproxy backends updating until the upgrade is finalized.  Doesn't happen every time.  That's why we tried to apply the healthchecks, but we've struggled getting the service upgraded thereafter.

Pertinent info, we have about 30 nodes altogether.  We have the metadata service pinned:
```
    cpu_period: 100000
    cpu_quota: 20000
```
Refresh interval has been adjusted:
```
-reload-interval-limit=5000
```
UDP 500 and 450 is opened between all applications hosts; i.e. all hosts with the healthcheck service.  I can curl to the health routes successfully from all healthcheck containers when new containers are stuck initializing.

Any advice would be appreciated.  We have lots of logs -- hard for me to say what would be pertinent.  At this point, we can't deploy updates to this particular service.

**Comment by cloudnautique** [comment]
Is the metadata refresh interval set to the default, or has that been adjusted as well?

**Comment by dindurthy** [comment]
Ah yes, it has been.
```
-reload-interval-limit=5000
```
Updating the original post too.

**Comment by vincent99** [comment]
Each port is a different "backend" in haproxy and each backend's targets have independent healthchecks... it doesn't matter that they happen to point to the same service.

**Comment by dindurthy** [comment]
That comports, and I see it in the `haproxy.cfg`.  But is there a way to turn off the `option httpchk`?  Naively, I understand something else, probably the healthcheck service, is also healthchecking a target service, since services without lbs also successfully healthcheck.  So, is there a way to preserve the healthcheck checks and disable the lb backend checks?  We essentially can't use the healthchecks as is and haven't been, so I see us only gaining if we have one and not the other.  Ideally, all we want is the haproxy.cfg updated and reloaded when something else successfully healthchecks the service.  We don't want that reiterated in the backend configurations.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
