### ISSUE TITLE
Vsphere (datacenter not found error in precheck)

### ISSUE THREAD

**Issue by jagadeeshops** [rancher/rancher#13112]
**Rancher versions:**
rancher/server master and preview tags

**Infrastructure Stack versions:**
vsphere provisioning

**Docker version: (`docker version`,`docker info` preferred)**
1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vsphere 
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
multi node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes
**Steps to Reproduce:**
Run ranncher server container with preview tag
**Results:**
Failes in the precheck itself.

Says "precheck failes.  datacenter "datacenter name" not found."

But that datacenter is available when i check from vcenter.  Same datacenter i used in terraform and its creating machines there.

**Comment by superseb** [comment]
Can you share what config you entered in Rancher and what you are using in Terraform? You can remove any sensitive info but please keep the format so we can investigate.

**Comment by jagadeeshops** [comment]
I created a node template with the following details.
Vcenter server: <server name>
port: 443 => default value
username: <username>
password: <password>
Instance options (all defaults)

datacenter: saas
pool: samplepool
network: <some network>
datastore: <some datastore>

After this i created cluster with one node having all components.

Then checked the node status:

Got the below  error:

Error with pre-create check: "datacenter 'saas' not found"; Timeout waiting for ssh key
--

![image](https://user-images.githubusercontent.com/10154286/39433635-fe77e17c-4cb3-11e8-8f92-46536492209f.png)

**Comment by superseb** [comment]
I've seen reports on machine with some of the following causes:

- Datacenter is in a folder
- Datacenter is in folder(s) with spaces in the name
- No permission on folder in the tree where the datacenter is located

Looking through the code, I also see the vendor of `vmware/govmomi` is pretty outdated in `docker/machine` so I will take a look if that can be updated upstream.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue in rancher 2.1.5, and we'll reopen it

**Comment by hwasp** [comment]
Hi,

I am facing similar issue in 2.1.8. I have a datastore inside a folder with spaces and it is not able to find it. If I move the datastore to the root (no spaces) it works. I have tried in 2.2.0 and it work smoothly. Could you please confirm if you have fixed that in 2.1.8?
