### ISSUE TITLE
Ability to specify custom cloud config format (i.e. gcfg for vSphere/Openstack)

### ISSUE THREAD

**Issue by straffalli** [rancher/rancher#13115]
**Rancher versions:**
rancher/server or rancher/rancher: **v2.0.0-beta4**
rancher/agent or rancher/rancher-agent: **v2.0.0-beta4**

**Infrastructure Stack versions:**
network provider: Flannel
kubernetes (if applicable): v1.9.5-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Tue Apr  3 05:31:26 2018
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Tue Apr  3 05:31:26 2018
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Custom host provisionning on VMware (not done through rancher).

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Kubernetes cluster built with custom provider: 5 nodes (3 control planes/etcd and 2 workers)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
In the cluster configuration options for custom provider, I filled information on Cloud provider (for vSphere Storage):

![image](https://user-images.githubusercontent.com/14125085/39302403-c9a2106c-4952-11e8-9204-8b63f07cd185.png)

This configuration has been tested in another Kubernetes cluster built with Kubespray and works perfectly.

Start adding controle plane node.

**Results:**

When starting to add node to the cluster (control plane), the _**kube-apiserver**_ does not start and complains with the following error:

```
+ echo kube-apiserver --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --admission-control=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --storage-backend=etcd3 --cloud-provider=vsphere --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem --cloud-config=/etc/kubernetes/cloud-config.json --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --insecure-port=0 --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem --allow-privileged=true --service-cluster-ip-range=10.43.0.0/16 --insecure-bind-address=127.0.0.1 --secure-port=6443 --etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem --etcd-servers=https://<REDACTED>:2379,https://<REDACTED>:2379,https://<REDACTED>:2379 --etcd-prefix=/registry
+ grep -q cloud-provider=azure
+ '[' kube-apiserver = kubelet ']'
+ exec kube-apiserver --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --admission-control=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --storage-backend=etcd3 --cloud-provider=vsphere --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem --cloud-config=/etc/kubernetes/cloud-config.json --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --insecure-port=0 --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem --allow-privileged=true --service-cluster-ip-range=10.43.0.0/16 --insecure-bind-address=127.0.0.1 --secure-port=6443 --etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem --etcd-servers=https://<REDACTED>:2379,https://<REDACTED>:2379,https://<REDACTED>:2379 --etcd-prefix=/registry
I0426 10:46:48.966028       1 server.go:121] Version: v1.9.5
I0426 10:46:48.966927       1 cloudprovider.go:59] --external-hostname was not specified. Trying to get it from the cloud provider.
Error: error setting the external host value: "vsphere" cloud provider could not be initialized: could not init cloud provider "vsphere": 1:1: illegal character U+007B '{' 
```

The cloud config file /etc/kubernetes/cloud-config.json is JSON formatted:

```
 {

"vsphere_datacenter": "<redacted>",

"vsphere_datastore": "<redacted>",

"vsphere_insecure": <redacted>,

"vsphere_password": "<redacted>",

"vsphere_scsi_controller_type": "<redacted>",

"vsphere_user": "<redacted>",

"vsphere_vcenter_ip": "<redacted>",

"vsphere_vcenter_port": <redacted>,

"vsphere_working_dir": "<redacted>"
}
 ```
I tried to replace this file, with the appropriate format present in my other cluster. It looks like this:

```
[Global]
user = "<redacted>"
password = "<redacted>"
port = <redacted>
insecure-flag = <redacted>

datacenters = "<redacted>"


[VirtualCenter "<redacted>"]


[Workspace]
server = "<redacted>"
datacenter = "<redacted>"
folder = "<redacted>"
default-datastore = "<redacted>"


[Disk]
scsicontrollertype = <redacted>
```
And now the kube-apiserver container start working. So I think the JSON format is not supported for vsphere cloud provider. Would it be possible to fix this?

**Comment by alexandrem** [comment]
We have the exact same bug for the Openstack provider plugin.

The resulting cloud config file in JSON breaks the Kubernetes+openstack integration.

**Comment by alexandrem** [comment]
Anyone working on this at the moment?

I can help writing the fix if someone is willing to provide hints and guideline for the patch.

**Comment by tjtelan** [comment]
I think I found possibly found where fix should go.

The place where the cloud config is generated by Rancher is initiated here:
https://github.com/rancher/rancher/blob/master/pkg/librke/rke.go#L52

Which leads us to rke, where the custom config is generated as json here:
https://github.com/rancher/rke/blob/master/cluster/cluster.go#L184
https://github.com/rancher/rke/blob/master/cluster/cluster.go#L392

**Comment by kort3z** [comment]
The bug is still existing.
Rancher 2.0.2 with vsphere cloud provider. Same error in kubelet logs.
Someone has a workaround in the meantime?

**Comment by superseb** [comment]
As long as this issue is open, it is not fixed. This PR (https://github.com/rancher/rancher/issues/13115) has a discussion on the implementation for this issue.

**Comment by deniseschannon** [comment]
@galal-hussein can you put an example of how someone would be able to use the custom cloud provider support?

**Comment by deniseschannon** [comment]
Assigning over to UI.

**Comment by deniseschannon** [comment]
@loganhz Due to the complexity of the other cloud providers, we should make the change for custom option for cloud provider along with your cluster options PR (https://github.com/rancher/ui/pull/1951)

If you select custom, I'd like it to not give any of the name or key/value options, but instead have text that says `Please edit the YAML to add in cloud provider.` I'll give you a docs reference PR to add in at a later time. 

Ping me on slack if that doesn't make sense.

**Comment by loganhz** [comment]
Added. Please let me know once the link for docs is ready. Now it works with YAML. But user has to look at the API schema to figure out what fields can be used here.

**Comment by LinAnt** [comment]
I found an issue with the new vsphere cloud-config format. The insecure flag needs to be an int {0,1} instead of a bool.

https://github.com/kubernetes-incubator/kubespray/blob/master/docs/vsphere.md
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html

**Comment by sangeethah** [comment]
Tested with latest build from master

Able to specify custom cloud config  for vsphere cloud provider using the "Edit as Yaml" option in "Cluster Options" when provisioning cluster.  Custom cloud config gets as a multiline string in ```cloud_provider``` section in ```customCloudProvider:``` field .

Example for custom cloud config  for vsphere:

```
cloud_provider:
  name: vsphere
  # Note the pipe as this is what indicates a multiline string
  customCloudProvider: |-
    [Global]
    user = "<user>"
    password = "<password>"        
    port = "443"
    insecure-flag = "1" #set to 1 if the vCenter uses a self-signed cert
    datacenters = "<datacenter>"
        
    [VirtualCenter "<ip>"]
    user = "<user>"
    password = "<password>"
    [Workspace]
    server = "<ip>
        datacenter = "HE-FMT"
        folder = "<name>"
        default-datastore = "kubernetes" #Datastore to use for provisioning volumes using storage classes/dynamic provisioning
    [Disk]
        scsicontrollertype = pvscsi
```

**Comment by sangeethah** [comment]
We should also be able to use the vsphere specific cloud provider ```vsphereCloudProvider``` settings in cluster.yml :

```
cloud_provider:
  name: vsphere
  vsphereCloudProvider:
    global:
      user: <user>
      password: <password>
      port: 443
      insecure-flag: 1
    virtual_center:
      <ip>:
        user: <user>
        password: <pass>
    workspace:
      server: <ip>
      datacenter: <dc>
      folder: <foldername>
      default-datastore: <datastore>
    disk:
      scsicontrollertype: pvscsi
```

**Comment by spawnia** [comment]
@sangeethah How about that second example you posted? Is that now possible? What is the preferred way of doing it?

**Comment by deniseschannon** [comment]
We are using RKE to launch kubernetes and the cloud provider support of how to indicate your yamls are located here: 
https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/
