### ISSUE TITLE
Creating namespace through workload causing 409 if namespace already exist

### ISSUE THREAD

**Issue by gtirloni** [rancher/rancher#13119]
**Rancher versions:**
v2.0.0-beta4-rc2

**Infrastructure Stack versions:**
kubernetes 1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
Docker 17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM/Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
kubernetes cluster created with kubeadm and imported into Rancher

**Steps to Reproduce:**
1. Import cluster
2. Deploy nginx using kubectl in the `default` namespace (`kubectl run nginx --image=nginx`)
3. In Rancher, create a project named `Test`
4. Go to Workloads -> Deploy
5. Enter `nginx` for name and `default` for namespace (there's no dropdown because the project has no namespaces)
6. Deploy the Workload

**Results:**
1. "Saving..." button stays like that forever
2. Server returns "409 Conflict"

Request:

```
accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 67
content-type: application/json
Cookie: __utmz=156774499.1524491818.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); R_USERNAME=admin; __utma=156774499.857237349.1524491818.1524590554.1524670960.5; CSRF=0145a04xxx; R_SESS=token-h4x9t:7pfdstxc2wq2vm789w6gh8rxxxx8rn24gqdfwvq6sdxztzr4jbzwdxxx
Host: hostname
Origin: https://hostname
Pragma: no-cache
Referer: https://hostname/p/c-n8mjd:p-lc2c4/workloads/run
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
x-api-action-links: actionLinks
x-api-csrf: 0145a04b8f
x-api-no-challenge: true
```
Response:

```
Content-Length: 150
Content-Type: application/json
Date: Thu, 26 Apr 2018 14:47:13 GMT
Expires: Wed 24 Feb 1982 18:42:00 GMT
Set-Cookie: CSRF=0145a04b8f; Path=/
X-Api-Schemas: https://hostname/v3/cluster/c-n8mjd/schemas
```

Request Payload:

```
{type: "namespace", name: "default", projectId: "c-n8mjd:p-lc2c4"}
name
:
"default"
projectId
:
"c-n8mjd:p-lc2c4"
type
:
"namespace"
```

**Comment by gtirloni** [comment]
It doesn't seem necessary that there is a deployment with the same name. It seems the issue is the existing namespace itself.

**Comment by gtirloni** [comment]
While adding a certificate the issue doesn't happen. The UI correctly shows an error `"namespaces "default" already exists`

**Comment by tfiduccia** [comment]
Steps:
1.  Create a new project
2.  Go to workload for that project
3.  Add workload & click on "Add to a New Namespace"
4.  enter Default & try to Launch workload

REsults:  the Launch just spins and nothing gets created.  We should really do the check to make sure it's not a duplicate namespace and show the proper error.
