### ISSUE TITLE
Observed delay of ~1 minute in dns links to become accessible when one of the services that is linked to the DNS service was stopped.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1312]
Server version - V0.25.0-rc2

Steps to reproduce the problem:
set up - service1 linked to a DNS service with name  -"mydns" - which is linked to 2 services. - s1 and s2

From container in service1 , I am able to access containers in s1 and s2 using "mydns" .
I tried stopping/destroying instances in service s1 and s2 .
The DNS resolved to right set of containers as expected.

I stopped service - s1. When I did dig on "mydns" , I see it resolve to containers in s2 as expected.
But when I tried to access mydns using http://mydns:80 , It did not respond.

When i tried to ping to the address from dig list , ping timed out.
But after a minute or so , the ping started working.

I was able to access mydns link using http://mydns:80 without any issue.

**Comment by alena1108** [comment]
@sangeethah can't reproduce this on the latest. Could you retry, and if it happens again, give me the ip address of the setup?

**Comment by sangeethah** [comment]
Closing this issue. I have not seen this delay for sometime now.
