### ISSUE TITLE
Dropped service.remove events from k8s-agent can result in duplicated service entries

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#13123]
Steps to reproduce:

* Create k8s environment
* Create k8s service using kubectl. Wait till k8s-agent propagates the service to rancher (you can list it by name in the DB)
* Stop `k8s-agent` service (Infrastructure stacks -> Kubernetes -> k8s-agent service stop)
* remove k8s service using kubectl.
* Start `k8s-agent` service
* recreate the k8s service

Bug: service with duplicated name gets created in rancher. It happens because there was no service.remove event due to k8s agent being down (stop/start is just one way of putting it down, but there can be other reasons like network being down, etc). And when next create event comes to rancher for the service having the same name, but diff external id, we create the duplicate.

The fix should go to this file: https://github.com/rancher/cattle/blob/597aacb15d649d9b43494ef82ac74b3c4c10f5aa/code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalServiceEventCreate.java

On create/update event, first check if there is a service in the stack, having the same name, and kind=kubernetesService. Then validate its external id. If different, remove the old record and create a new one.

**Comment by soumyalj** [comment]
Tested with v1.6.18-rc1 using the below steps:

1. Create k8s environment
2. Create k8s service using kubectl. Wait till k8s-agent propagates the service to rancher (you can list it by name in the DB)
3. Stop k8s-agent service (Infrastructure stacks -> Kubernetes -> k8s-agent service stop)
4. remove k8s service using kubectl.
5. Start k8s-agent service
6. recreate the k8s service

When the service is recreated, there are no duplicate entries in the database. 
But, creating an ingress pointing to this recreated service, does not get programmed. Ingress is not functional.

**Comment by mattmattox** [comment]
## Workaround

### Delete all duplicate services

```
SET FOREIGN_KEY_CHECKS=0;
select id, name, created, removed, remove_time from service where removed IS NOT NULL AND remove_time IS NOT NULL ORDER BY name;
select id, description, created, end_time, event_type, service_id from service_log where service_id in (select id from service where removed IS NOT NULL AND remove_time IS NOT NULL);
DELETE from service_log where service_id in (select id from service where removed IS NOT NULL AND remove_time IS NOT NULL);
DELETE from service where removed IS NOT NULL AND remove_time IS NOT NULL;
select id, name, created, removed, remove_time from service where removed IS NOT NULL AND remove_time IS NOT NULL;
SET FOREIGN_KEY_CHECKS=1;
```

### Delete duplicate services by app
example app = k8test1


```
example app = k8test1
SET FOREIGN_KEY_CHECKS=0;
select id, name, created, removed, remove_time from service where name like "k8test1" AND removed IS NOT NULL AND remove_time IS NOT NULL ORDER BY name;
select id, description, created, end_time, event_type, service_id from service_log where service_id in (select id from service where name like "k8test1" AND removed IS NOT NULL AND remove_time IS NOT NULL);
DELETE from service_log where service_id in (select id from service where name like "k8test1" AND removed IS NOT NULL AND remove_time IS NOT NULL);
DELETE from service where name like "k8test1" AND removed IS NOT NULL AND remove_time IS NOT NULL;
select id, name, created, removed, remove_time from service where name like "k8test1" AND removed IS NOT NULL AND remove_time IS NOT NULL;
SET FOREIGN_KEY_CHECKS=1;
```
