### ISSUE TITLE
support generating x(n)ip.io domains for ingress

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#13124]
Give the ability for the user to specify that they would like an generated domain to use for there ingress rule.  This works around the fact that in development most apps do not have a DNS name to use.  This is only useful for development and production should provide a proper domain.  The x(n)ip domain will not be HA because it will point to a specific node which may go away.  Additionally this will only work with ingress controllers that populate IP addresses.  ALB, for example, does not give an IP, but a hostname.

**Comment by deniseschannon** [comment]
To test without the UI fixes, when you create an ingress rule, in the hostname just put in `xip.io`.

**Comment by sangeethah** [comment]
Tested with latest build from master.

When creating ingress rules with hostname set to xip.io , able to reach workloads using the generated endpoint urls .
Issues found when testing this feature will be tracked in different issues:
https://github.com/rancher/rancher/issues/13175
