### ISSUE TITLE
Mounting in only the cacerts.pem file should update cacerts value in API

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13126]
When only mounting in the cacerts file at `/etc/rancher/ssl/cacerts.pem` in the container, the `cacerts` value at `/v3/settings/cacerts` should be updated with the contents of that file.

Usecase for external termination and not having to update the API value manually.

**Comment by bmdepesa** [comment]
Mounted a cacerts file when starting server - updated contents were reflected in /v3/settings/cacerts.

```
docker run -v /home/ubuntu/state:/var/lib/rancher -v /root/cacert.pem:/etc/rancher/ssl/cacerts.pem -d -p 80:80 -p 443:443 --restart=unless-stopped rancher/rancher:v2.0.0-rc4
```

I did not check external termination use case.

**Comment by sangeethah** [comment]
Tested with v2.0.0

Started rancher server by providing only cacerts.pem file. /v3/settings/cacerts gets updated automatically with this info.

Able to start an nginx instance in front of rancher server for SSL termination.
Able to access rancher server and deploy clusters successfully.
