### ISSUE TITLE
Setting up 2.0 Cluster, Can't Set Admin Password

### ISSUE THREAD

**Issue by scottadair** [rancher/rancher#13128]
**Rancher versions:**
rancher 2.0rc1, deployed on RKE

Trying to setup the cluster, but can't set an admin password. Nothing jumps out in the logs

![image](https://user-images.githubusercontent.com/583279/39329639-f625d104-496c-11e8-9f4c-005d8b2e6e0b.png)

**Comment by ts-mini** [comment]
You didn't include a full screenshot - but I've only seen this error if you're not connect w/ https.

**Comment by vincent99** [comment]
SSL, either directly to the container or through a proxy, is required.  The UI session cookie has the `secure` flag set and is only transmitted over SSL.

**Comment by tfiduccia** [comment]
@scottadair - not sure if you saw the comments.  please connect through https.  Will close, if you are using ssl and still have problem.  Please reopen.
