### ISSUE TITLE
Failed to access LB rules even though correct rules were programmed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1313]
Server version - V0.25.0-rc1

Create a LB service linked to a service -S1 with scale 3.
I was able to access the Lb rules successfully.
Scaled down the service to 1.
After this , i am not able to access the LB rule: 

Get the following error:
Sangeethas-MBP:testwgets sangeethahariharan1$ wget http://146.148.82.227:7777/name.html
--2015-06-19 21:21:05--  http://146.148.82.227:7777/name.html
Connecting to 146.148.82.227:7777... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2015-06-19 21:21:05 ERROR 503: Service Unavailable.

I see that the rules are being programmed correctly in /etc/haproxy/haproxy.cfg file , but still LB rules are not accessible.
From the LB Agent , When I tried to ping to the contaier Ip address the LB rule resolves to , I am not able to ping.

There seems to be problems with network connectivity between the LB agent and the container.

**Comment by sangeethah** [comment]
I see this issue when testing with server version - V0.27.0-rc1

Created LB rule for a service with scale 3.

When LB rules was accessed , traffic was redirected to only 2 of the 3 instances. I see the ha proxy configuration includes all the 3 instances.
The reason why the traffic was not directed was because the instances are not reachable from  LB Agent:

```
backend fc5f2bfc-f6f2-43b4-ae1e-e5c92a6e1fad_-319266029_backend
        mode http
        balance roundrobin
        timeout check 5000
        option httpchk GET /name.html HTTP/1.0
        server 70b33dd5-8e06-43a1-833a-713d6cda122a 10.42.250.9:80 check port 80 inter 4000 rise 4 fall 5
        server d9e7e968-5343-4978-a734-e2accf5c10bc 10.42.106.5:80 check port 80 inter 4000 rise 4 fall 5
        server 5ca94e04-f338-49a8-83af-714745bd8b5c 10.42.107.8:80 check port 80 inter 4000 rise 4 fall 5

root@22c9938146dd:/# ping 10.42.107.8
PING 10.42.107.8 (10.42.107.8) 56(84) bytes of data.
^C
--- 10.42.107.8 ping statistics ---
16 packets transmitted, 0 received, 100% packet loss, time 15118ms

root@22c9938146dd:/# 
```

**Comment by alena1108** [comment]
I believe this issue should be gone by now; could you test, @sangeethah?

**Comment by sangeethah** [comment]
We have not been seeing this issue for sometime now.Closing this issue.
