### ISSUE TITLE
Attempting to update Ingress-nginx daemon set , does not result in daemon set pods getting recreated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13146]
Rancher server version -  v2.0.0-rc1
Create a rke cluster
Move ingress-nginx namespace into default project
Update nginx-ingress-controller workload and add a new environment variable .
This update does not result in existing pods getting destroyed and recreated.

**Comment by orangedeng** [comment]
The nginx ingress controller daemon set use `updateStrategy:OnDelete`. It means only delete old pods will update configuration. looking for more information to know why.

**Comment by orangedeng** [comment]
It seems that standard nginx controller does not have the updateStrategy setting in its deployment. I think it is added by RKE. @galal-hussein Do you have any ideas?

**Comment by orangedeng** [comment]
@sangeethah After I Discuss it with Hussein about it. We set the `updateStrategy:OnDelete` for the ingress-controller daemon set on purpose. For now, we need to delete pods of this daemon set after we update the daemon set configuration.

**Comment by sangeethah** [comment]
When pods belonging to  nginx-ingress-controller workload is deleted , the they get recreated with the new configuration that was set as part of upgrade.
