### ISSUE TITLE
Not able to launch container shell - stuck in "connecting" state 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13149]
**Rancher versions: Build from master - Apr 26
**Steps to Reproduce:**
Create a cluster with "Amazon Ec2" with provider set to "amazon" with 2 nodes ( having all roles).
Deploy workloads.

Try to exec into the container.
Sometimes I am able to get to the container shell. 
But most of the time UI hangs in "connecting" state.

**Comment by haisum** [comment]
I am also having same issue. I am using local RKE cluster. This is the error in web console:

WebSocket connection to 'wss://192.168.112.179:8443/v3/clusters/c-2d4p2?shell=true' failed: Error during WebSocket handshake: Unexpected response code: 500

**Comment by smalenfant** [comment]
I have the same problem. I believe this was working on 2.0.0 (before upgrade). Currently running 2.0.2.

**Comment by deniseschannon** [comment]
@sangeethah Are you still having this issue with the latest updates in Rancher?

**Comment by sangeethah** [comment]
This issue is not seen anymore when testing with latest rancher server builds from master.
