### ISSUE TITLE
Can't set extra_hosts from UI

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#13154]
**Rancher versions:** 
rancher/server or rancher/rancher: 1.6.16
rancher/agent or rancher/rancher-agent: 1.2.10 

**Infrastructure Stack versions:**
healthcheck: v0.3.6
ipsec: v0.13.11
network-services: metadata:v0.10.2 network-manager:v0.7.20
scheduler: v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)** 17.09.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** ROS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Proxmox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Up rancher

**Results:** Can't set extra_hosts from UI

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
