### ISSUE TITLE
Catalog automatically converts a numbered string into number instead of keeping it as string

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#13158]
**Rancher versions:**
rancher/server or rancher/rancher:  master 04/27

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS  4.4.0-1052-aws
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. Launch a wordpress Charts from https://github.com/guangbochen/charts.git
2. `WordPress Password` input `111111` ,Launch.
**Results:**
Failed to launch, error log:
```
Helm template failed. Error: render error in "wordpress/charts/mariadb/templates/secrets.yaml": template: wordpress/charts/mariadb/templates/secrets.yaml:19:49: executing "wordpress/charts/mariadb/templates/secrets.yaml" at <b64enc>: wrong type for value; expected string; got float64 : exit status 1
```

**Comment by galal-hussein** [comment]
rancher/rancher:master at july 26th

I was able to confirm that string fields remain strings even if i input digits values, i was able to run wordpress catalog after using `111111` as wordpress password

**Comment by wyattjsmith1** [comment]
What can we do if we have a catalog that requires non-string parameters? For example, Gitlab accepts boolean parameters https://gitlab.com/charts/gitlab/blob/master/doc/installation/command-line-options.md. Many other Helm charts require this as well. I opened #14711, but that seems to point at this issue. Is there anything I can do about this?

**Comment by cjellick** [comment]
We've had to reopen this because the fix has the potential to do more harm than good.

**Comment by cjellick** [comment]
Maybe related: https://github.com/rancher/rancher/issues/14608

**Comment by cjellick** [comment]
Here is the solution we are thinking of:
- Add valuesYaml field to app that overrides the one built into the template if set
- Apply Rancher catalog answers directly on to the values.yaml instead of trying to use set/set-string for them
- Somehow provide a (per answer) choice of set vs set-string for vanilla helm templates, like a map for the value with an explicit auto/string option, or a magic prefix (`string:1234`) to trigger set-string

**Comment by cjellick** [comment]
Related https://github.com/rancher/rancher/issues/14551

**Comment by materemias** [comment]
#17346 is related, some charts need a non-string `true` to work. without this nodeAffinity cannot be set on most charts if launched from Rancher.

**Comment by kingsd041** [comment]
Version: master 2.2 (2/15/19)  Image ID: 28aca35e09a1
Confirmed fix.  
***Test Case :***
1.  go to the v3/xxx/apps api  e.g https://192.168.99.1:8443/v3/project/local:p-7kf6b/apps/
2. create a new app with posting custom `valuesYaml` file to the api
![image](https://user-images.githubusercontent.com/4569037/51668196-a0b5cf00-1ffc-11e9-979e-f6326086f3bf.png)
3. deploy the app and confirm the user-supplied `valuesYaml` value will override the default values.

**Comment by kingsd041** [comment]
Reopen issue

@loganhz 
Launch WordPress from Catalog, `WordPress Password` and `MariaDB Password` Enter the int type password, Ex: `111111`. Wordpress will fail to start and prompt `Pod has unbound immediate PersistentVolumeClaims`

If I use a string type password, I can successfully launch it. I try to use `111111` as the password to launch wordpress in `Edit as YAML`, which works well.

**Comment by kingsd041** [comment]
Version: master 2.2 (2/18/19)  Image ID: 46f4b03ba30e
Confirmed fix. Use the int type as the password on the UI to successfully launch WordPress

WordPress API:
```
valuesYaml": "---\n  defaultImage: true\n  image: \n    repository: \"bitnami/wordpress\"\n    tag: \"4.9.8-debian-9\"\n  mariadb: \n    image: \n      repository: \"bitnami/mariadb\"\n      tag: \"10.1.35-debian-9\"\n    enabled: true\n    db: \n      name: \"wordpress\"\n      user: \"wordpress\"\n    mariadbPassword: \"1111111\"\n    master: \n      persistence: \n        enabled: false\n        size: \"8Gi\"\n        storageClass: \"\"\n        existingClaim: \"\"\n  wordpressUsername: \"hailong\"\n  wordpressPassword: \"1111111\"\n  wordpressEmail: \"user@example.com\"\n  externalDatabase: \n    host: \"\"\n    user: \"\"\n    password: \"\"\n    database: \"\"\n    port: \"3306\"\n  persistence: \n    enabled: false\n    size: \"10Gi\"\n    storageClass: \"\"\n  ingress: \n    enabled: true\n    hosts: \n      - \n        name: \"xip.io\"\n  serviceType: \"NodePort\"\n  nodePorts: \n    http: \"\"\n    https: \"\""
}
```

**Comment by marcusianlevine** [comment]
While this issue is resolved from the UI, I'm experiencing the same issue using the CLI. 

When I try to add an annotation whose value is an integer, it is automatically converted to an integer even if I wrap it in quotes

Should I open a separate ticket for the equivalent CLI parsing issue?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/22532
Put it into 2.3.
