### ISSUE TITLE
Projects/namespaces listers are presenting the other way around

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13155]
Version: 2.0.0-rc1

Go to `Projects/Namespaces` and use the listers to present data differently, Grouped Projects/Namespaces and List Namespaces.

Result: Grouped Projects/Namespaces shows List Namespaces and List Namespaces shows Grouped Projects/Namespaces

**Comment by loganhz** [comment]
Fix in https://github.com/rancher/ui/pull/1859

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/30
Verified fixed
