### ISSUE TITLE
Added worker node doesn't run cloud-config-deployer

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13157]
Version: v2.0.0-rc1

- Create cluster with cloud provider configured
- Add node with etcd + control (gets cloud-config-deployer and comes up fine)
- Add node with worker

Results:

kubelet won't start, because it does not run cloud-config-deployer

```
F0427 13:10:44.651541    2493 plugins.go:102] Couldn't open cloud provider configuration /etc/kubernetes/cloud-config.json: &os.PathError{Op:"open", Path:"/etc/kubernetes/cloud-config.json", Err:0x2}
``` 

Work around:
```touch /etc/kubernetes/cloud-config.json && docker restart kubelet```

**Comment by sangeethah** [comment]
Tested with latest build from master
Able to create a cluster successfully using  "Amazon EC2" setting provider to "Amazon" (having iamInstanceProfile set in the node template) with following configurations:

1. node1 - control 
2. node2 - etcd 
3.node3 - worker.

All nodes (including worker) get to "active" state.

Able to deploy workloads successfully.
Able to create LB (L4 Balancer) successfully for the workloads.
