### ISSUE TITLE
Delete the catalog app, the corresponding namespace is not deleted in kubernetes

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#13159]
**Rancher versions:**  master 04/27

**Docker version: (`docker version`,`docker info` preferred)** 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04.4 LTS 4.4.0-1052-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**Steps to Reproduce:**
1. Launch a MySQL Charts from the library
2. Delete MySQL in catalog apps
**Results:**
Kubernetes did not remove this MySQL namespace

**Comment by StrongMonkey** [comment]
We have concerns that the namespace might be used by other apps so it is not safe to delete. We should add logic to check if the namespace is not used or referenced by any of the resources(apps), that needs some work.

**Comment by frenchtoasters** [comment]
I just happened to notice that when a chart deployed from a catalog creates namespaces that do *not* get put under a project in the cluster it will delete them when the chart is removed.

**Comment by slassh** [comment]
so how are we supposed to clean up those ns ? because even when you try to delete them manually , they stuck at `Terminating` status and the only way to make them disappear is to change their definitions by deleting `kubernetes` finalizers !
Is it a clean way to do it or I did something wrong ?

**Comment by janeczku** [comment]
When deploying an app you can either deploy it in an existing namespace or create a new one.
In the latter case there is a reasonable expectation that the namespace is removed along with all other resources created by the app.
