### ISSUE TITLE
Update default args for kube system components on cluster creation

### ISSUE THREAD

**Issue by kfiles** [rancher/rancher#13162]
**Rancher versions:**
rancher/server 2.0rc1

**Infrastructure Stack versions:**
kubernetes: 1.10.1

**Docker version: **
18.03.1

**Operating system and kernel: **
boot2docker, kernel 4.9.93

**Type/provider of hosts: **
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single master, single worker node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes

**Steps to Reproduce:**
Istio installation requires up-to-date k8s args for kube-apiserver and kube-controller-manager. Unfortunately, Rancher creates a k8s cluster with some of the latest args missing. These include:

kube-apiserver: admission-control needs "MutatingAdmissionWebhook,ValidatingAdmissionWebhook" appended to current methods

kube-controller-manager: 
  cluster-signing-cert-file=/etc/kubernetes/ssl/kube-ca.pem
  cluster-signing-key-file=/etc/kubernetes/ssl/kube-ca-key.pem

According to the recommended k8s setup, these should all be default settings.

See https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use for recommended k8s AdmissionControllers
See https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/ for recommended TLS setup

It would be helpful for Rancher to update its default launcher params to include these default values.

**Results:**

**Comment by sebastien-prudhomme** [comment]
@superseb No news on that issue?

**Comment by superseb** [comment]
I'm submitting this today

**Comment by kfiles** [comment]
@superseb is there a new pull request which supercedes PR #412?

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/14517
