### ISSUE TITLE
On EC2, rancher-nodes security group should open 80, 443, and NodePort ports

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#13177]
**Rancher versions:** 
rancher/server or rancher/rancher: v2.0.0-rc3

I think there's a problem with how we configure the default security group "rancher-nodes" on EC2. We don't open 80, 443, and 30000-32767. As a result we can create RKE clusters successfully but no workloads work.

We need to allow 80, 443, and 30000-32767 in rancher-nodes security group.

**Comment by sangeethah** [comment]
Tested with v2.0.0-rc4

port 80 and 443 are open in the default "rancher-nodes" SG that created when deploying EC2 Amazon cluster using a template that chooses to use  "rancher-nodes" SG .

Node port ranges are not opened up which is as expected.
