### ISSUE TITLE
Custom Cluster: etcd nodes not deleting properly

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13179]
**Rancher versions:**
v2.0.0-rc3

Steps:
Create a custom cluster, at least one extra node with etcd role. 
Delete etcd node. 

Results:
etcd node is still associated to cluster. 

<img width="510" alt="screen shot 2018-04-27 at 5 44 32 pm" src="https://user-images.githubusercontent.com/38012481/39389978-0fdfd988-4a43-11e8-919d-4f0162219709.png">
<img width="1396" alt="screen shot 2018-04-27 at 5 44 45 pm" src="https://user-images.githubusercontent.com/38012481/39389979-0ff4172c-4a43-11e8-8ade-de5582baba2c.png">

**Comment by adingilloRancher** [comment]
More details. Added 3 nodes. One etcd, one controller, one worker. Waited until cluster was active. Added second etcd node.  After second etcd node was active, deleted first etcd node from the cluster.

**Comment by galal-hussein** [comment]
@adingilloRancher I will try to reproduce with the latest master

**Comment by galal-hussein** [comment]
@adingilloRancher followed the steps:
- create custom cluster with 3 nodes 1 etcd 1 control 1 worker
- add another etcd
- remove the original etcd

I wasn't able to reproduce, can you post the rancher server logs from this incident

**Comment by galal-hussein** [comment]
@adingilloRancher I checked the logs of rancher server, and i can see that the etcd node removed successfully from the etcd cluster:
```
2018/04/28 00:42:06 [INFO] cluster [c-nbk7k] provisioning: [remove/etcd] Removing member [etcd-austinEtcd] from etcd cluster
2018/04/28 00:42:06 [INFO] cluster [c-nbk7k] provisioning: [remove/etcd] Successfully removed member [etcd-austinEtcd] from etcd cluster
```
However rke failed to cordon and delete the node from k8s:
```
2018/04/28 00:42:06 [INFO] cluster [c-nbk7k] provisioning: [hosts] Cordoning host [206.189.165.104]
2018/04/28 00:42:13 [INFO] cluster [c-nbk7k] provisioning: [hosts] Deleting host [206.189.165.104] from the cluster
2018/04/28 00:42:13 [ERROR] cluster [c-nbk7k] provisioning: Failed to delete etcd node 206.189.165.104 from cluster

```

**Comment by galal-hussein** [comment]
@adingilloRancher I added a PR to display more logs about the delete k8s node problems, however i wasn't able to reproduce after several retries.

**Comment by adingilloRancher** [comment]
Master 5/11/18.

Verified etcd node is successfully removed.
