### ISSUE TITLE
How to delpoy the stack （from Rancher Stroe） to Specific Hosts

### ISSUE THREAD

**Issue by zwh6611** [rancher/rancher#13187]
*Describe your issue here*

How to delpoy the stack （from Rancher Stroe） to Specific Hosts.

I have no way to edit the label. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.17` Cattle: `v0.183.49` UI: `v1.6.42` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.launch`|

**Comment by loganhz** [comment]
There is no stack level scheduling rule. You need to config it in each service. In the scheduling section of a service, you can choose the host which you want to use
