### ISSUE TITLE
failed to find plugin "rancher-bridge"

### ISSUE THREAD

**Issue by mujianxin6** [rancher/rancher#13186]
*Couldn't bring up network: failed to find plugin "rancher-bridge"*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.5` Cattle: `v0.182.1` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|

containers

gogs-db-1 | 无 | client | 10.0.0.6:5000/mysql:8.0 | n/a
-- | -- | -- | -- | --

logs

9 AM | ERROR | service.activate.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
-- | -- | -- | -- | --
11:52:19 AM | ERROR | service.activate.wait.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:51:42 AM | INFO | service.instance.create | Creating extra service instance |  
11:51:41 AM | INFO | service.activate.wait (38 sec) | Waiting for instances to start |  
11:51:40 AM | INFO | service.activate (39 sec) | Activating service |  
11:51:40 AM | ERROR | service.instance.delete | Removing bad service instance: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:51:40 AM | INFO | service.activate.info | Requested: 1, Created: 0, Unhealthy: 0, Bad: 1, Incomplete: 0 |  
11:50:34 AM | ERROR | service.activate.wait.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:50:34 AM | ERROR | service.activate.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:49:57 AM | INFO | service.instance.create | Creating extra service instance |  
11:49:56 AM | INFO | service.activate.wait (38 sec) | Waiting for instances to start |  
11:49:55 AM | INFO | service.activate.info | Requested: 1, Created: 0, Unhealthy: 0, Bad: 1, Incomplete: 0 |  
11:49:55 AM | INFO | service.activate (39 sec) | Activating service |  
11:49:55 AM | ERROR | service.instance.delete | Removing bad service instance: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:49:22 AM | ERROR | service.activate.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:49:22 AM | ERROR | service.activate.wait.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:48:41 AM | INFO | service.activate.wait (41 sec) | Waiting for instances to start |  
11:48:41 AM | INFO | service.instance.create | Creating extra service instance |  
11:48:41 AM | ERROR | service.instance.delete | Removing bad service instance: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:48:40 AM | INFO | service.activate.info | Requested: 1, Created: 0, Unhealthy: 0, Bad: 1, Incomplete: 0 |  
11:48:40 AM | INFO | service.activate (42 sec) | Activating service |  
11:48:24 AM | ERROR | service.activate.wait.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:48:24 AM | ERROR | service.activate.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:47:41 AM | INFO | service.activate.wait (43 sec) | Waiting for instances to start |  
11:47:41 AM | ERROR | service.instance.delete | Removing bad service instance: Timeout getting IP address |  
11:47:41 AM | INFO | service.instance.create | Creating extra service instance |  
11:47:40 AM | INFO | service.activate (44 sec) | Activating service |  
11:47:40 AM | INFO | service.activate.info | Requested: 1, Created: 0, Unhealthy: 0, Bad: 1, Incomplete: 0 |  
11:47:27 AM | ERROR | service.activate.wait.exception | Expected state running but got error: Timeout getting IP address |  
11:47:27 AM | ERROR | service.activate.exception | Expected state running but got error: Timeout getting IP address |  
11:47:25 AM | INFO | service.activate.wait (2 sec) | Waiting for instances to start |  
11:47:25 AM | INFO | service.activate.info | Requested: 1, Created: 1, Unhealthy: 0, Bad: 0, Incomplete: 0 |  
11:47:25 AM | INFO | service.activate (2 sec) | Activating service |  
11:47:11 AM | INFO | service.activate.exception | Waiting: container starting [container:1i37] |  
11:47:11 AM | INFO | service.activate.wait.exception | Waiting: container starting [container:1i37] |  
11:46:26 AM | INFO | service.activate.wait (45 sec) | Waiting for instances to start |  
11:46:26 AM | INFO | service.activate.info | Requested: 1, Created: 1, Unhealthy: 0, Bad: 0, Incomplete: 0 |  
11:46:25 AM | INFO | service.activate (46 sec) | Activating service |  
11:46:18 AM | INFO | service.activate.exception | Waiting: container starting [container:1i37] |  
11:46:18 AM | INFO | service.activate.wait.exception | Waiting: container starting [container:1i37] |  
11:45:27 AM | INFO | service.instance.create | Creating extra service instance |  
11:45:27 AM | INFO | service.activate.wait (51 sec) | Waiting for instances to start |  
11:45:26 AM | INFO | service.activate.info | Requested: 1, Created: 0, Unhealthy: 0, Bad: 1, Incomplete: 0 |  
11:45:26 AM | ERROR | service.instance.delete | Removing bad service instance: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:45:25 AM | INFO | service.activate (53 sec) | Activating service |  
11:45:11 AM | ERROR | service.activate.exception | Waiting: container stopping [container:1i28]: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:45:11 AM | ERROR | service.activate.wait.exception | Waiting: container stopping [container:1i28]: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:44:25 AM | INFO | service.activate.wait (46 sec) | Waiting for instances to start |  
11:44:25 AM | INFO | service.activate.info | Requested: 1, Created: 1, Unhealthy: 0, Bad: 0, Incomplete: 0 |  
11:44:25 AM | INFO | service.activate (46 sec) | Activating service |  
11:44:17 AM | INFO | service.activate.exception | Waiting: container starting [container:1i28] |  
11:44:17 AM | INFO | service.activate.wait.exception | Waiting: container starting [container:1i28] |  
11:43:27 AM | INFO | service.instance.create | Creating extra service instance |  
11:43:27 AM | INFO | service.activate.wait (50 sec) | Waiting for instances to start |  
11:43:26 AM | ERROR | service.instance.delete | Removing bad service instance: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:43:25 AM | INFO | service.activate.info | Requested: 1, Created: 0, Unhealthy: 0, Bad: 1, Incomplete: 0 |  
11:43:25 AM | INFO | service.activate (52 sec) | Activating service |  
11:43:18 AM | ERROR | service.activate.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:43:18 AM | ERROR | service.activate.wait.exception | Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin] |  
11:42:56 AM | INFO | service.activate.wait (22 sec) | Waiting for instances to start |  
11:42:56 AM | INFO | service.activate.info | Requested: 1, Created: 1, Unhealthy: 0, Bad: 0, Incomplete: 0 |  
11:42:55 AM | INFO | service.activate (23 sec) | Activating service |  
11:42:40 AM | INFO | service.activate.exception | Waiting: container starting [container:1i21] |  
11:42:40 AM | INFO | service.activate.wait.exception | Waiting: container starting [container:1i21] |  
11:41:54 AM | INFO | service.instance.create | Creating extra service instance |  
11:41:54 AM | INFO | service.activate.wait (46 sec) | Waiting for instances to start |  
11:41:54 AM | INFO | service.activate.info | Requested: 1, Created: 0, Unhealthy: 0, Bad: 0, Incomplete: 0 |  
11:41:54 AM | INFO | service.activate (46 sec) | Activating service

**Comment by superseb** [comment]
Can you check the steps in this comment? https://github.com/rancher/rancher/issues/8383#issuecomment-314937769

**Comment by superseb** [comment]
Let us know if you still need help.
