### ISSUE TITLE
Scaling of nodes is not supported for AKS clusters

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13199]
**Rancher versions:**
rancher/rancher:v2.0.0-rc3

Create Amazon EKS or Azure container service clusters
Scale up/down of the nodes is not supported for these clusters.

**Comment by nathan-jenan-rancher** [comment]
Breaking out a separate issue for EKS:  https://github.com/rancher/rancher/issues/13596

**Comment by soumyalj** [comment]
Tested with master build. Created an AKS cluster with three nodes. Edited the cluster and scaled up the nodes to 5. Scale up was successful. The cluster was active and creation of workloads was also functional. Scale down also was functional.
