### ISSUE TITLE
UI does not show the correct node scheduling setting

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#13194]
*The yaml of deployment shows the correct node scheduling setting ,but it is wrong in UI*

The correct setting:

![default](https://user-images.githubusercontent.com/3146226/39402712-a07baa2e-4b99-11e8-83d9-247252499828.JPG)

The UI should show "Run all pods for this workload on a specific node",but now it is wrong

![default](https://user-images.githubusercontent.com/3146226/39402718-fbea4e92-4b99-11e8-8f62-a0c1f4fc45e2.JPG)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `master` UI: `v2.0.38` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by yoke88** [comment]
And I can not set the rolling-update strategy to "Kill ALL pods, then start new" in UI, there will be  a 422 error.

```json
{"actionLinks":{},"baseType":"error","code":"Invalid","links":{},"message":"Deployment.apps \"elasticsearch\" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'","status":422,"type":"error"}

```

When i manually edit the deployment YAML file like this to change the rollupdate strategy to Recreate. after i create the deployment , goto UI and view the YAML of this deployment. it show the correct setting.

![default](https://user-images.githubusercontent.com/3146226/39403067-b7b56dd8-4ba3-11e8-8295-aa0a22f1edf6.JPG)

But if you want to edit the deployment on the UI, the UI shows wrong settings like below screenshot
the correct one should be ' Kill ALL pods, then start new'

![default](https://user-images.githubusercontent.com/3146226/39403076-ed043f14-4ba3-11e8-835c-24496bc0a102.JPG)

**Comment by tfiduccia** [comment]
Scheduling is being set by UI.  API issue as it's not being returned.  

Moving Scaling strategy to another bug.

**Comment by alena1108** [comment]
@loganhz I've fixed API part when nodeName from k8s wasn't translated back to scheduling/nodeId. After the fix, you'd see:

```
"scheduling": {
"node": {
"nodeId": "machine-wnjhc"
}
},
```

but seems like one more fix is required from the UI side - displaying user friendly host name on edit. Steps to repro:

* Create workload, schedule it on specific node.
* Edit workload. The UI shows the ` Run all pods for this workload on a specific node` radio button checked, but there is no node name displayed

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Verified fixed
