### ISSUE TITLE
Setting Memory Limit doesn't work 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1319]
v0.25.0-rc1

Steps to Reproduce
1. Create a container with a Memory Limit.

Result: Container doesn't start and throws error:
```
Message : 42897f7e-61cb-4009-8301-7620e51654be : 500 Server Error: Internal Server Error ("You should always set the Memory limit when using Memoryswap limit, see usage.")
```

**Comment by cjellick** [comment]
Assigning to vince. He said he could/would fix this in the UI.

**Comment by defunctzombie** [comment]
Still broken in v0.30.0

**Comment by silviupanaite** [comment]
Still broken in Rancher v0.32.0

**Comment by deniseschannon** [comment]
v0.37.0-rc1 Verified that memory limit is being set.
