### ISSUE TITLE
AKS - unable to connect cluster with Kubectl after AKS Upgrade : clusterRole.rbac.authorization.k8s.io "admin" not found

### ISSUE THREAD

**Issue by david-maumenee** [rancher/rancher#13196]
**Rancher versions:**
rancher/server or rancher/rancher: `v2.0.0-rc3` (docker tag `preview`)
rancher/agent or rancher/rancher-agent : `v2.0.0-rc3`

**Infrastructure Stack versions:**
kubernetes (Azure AKS): `1.8.1` => `1.9.6`

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:40 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:16:13 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
cat /etc/os-release :
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

uname -r :
4.4.0-1055-aws
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Rancher server on AWS

**Steps to Reproduce:**
Create an Azure Container Service cluster
Upgrade the cluster via Azure Console https://docs.microsoft.com/fr-fr/azure/aks/upgrade-cluster
check the AKS cluster name generated via Azure Console

in my case : 
- resource-group : rancher2-aks 
- cluster name in azure : c-dtsbn

*All sub commands are launched in Azure Web Console*
```
az aks get-credentials --resource-group rancher2-aks --name c-dtsbn

kubectl get nodes
NAME                     STATUS    ROLES     AGE       VERSION
aks-rancher-14199006-0   Ready     agent     23h       v1.8.1
aks-rancher-14199006-1   Ready     agent     23h       v1.8.1
aks-rancher-14199006-2   Ready     agent     23h       v1.8.1

az aks get-upgrades --resource-group rancher2-aks --name c-dtsbn --output table
Name     ResourceGroup    MasterVersion    NodePoolVersion    Upgrades
-------  ---------------  ---------------  -----------------  --------------------------------------------------------
default  rancher2-AKS     1.8.1            1.8.1              1.8.2, 1.8.6, 1.8.7, 1.8.10, 1.8.11, 1.9.1, 1.9.2, 1.9.6

az aks upgrade --resource-group rancher2-aks --name c-dtsbn --kubernetes-version 1.9.6
```
The entire process take about 30 minutes

*Commands launched in Azure Web Console*
```
kubectl get nodes
NAME                     STATUS    ROLES     AGE       VERSION
aks-rancher-14199006-0   Ready     agent     21m       v1.9.6
aks-rancher-14199006-1   Ready     agent     9m        v1.9.6
aks-rancher-14199006-3   Ready     agent     32m       v1.9.6
```

**Results:**
After the upgrade, unable to connect via Rancher Kubectl
```
E0429 07:27:03.632153       1 generic_controller.go:204] ProjectRoleTemplateBindingController project-bgdn2/creator [cluster-prtb-sync] failed with : clusterRole.rbac.authorization.k8s.io "admin" not found
E0429 07:27:03.638287       1 generic_controller.go:204] RoleTemplateController project-owner [cluster-roletemplate-sync] failed with : clusterRole.rbac.authorization.k8s.io "admin" not found
```

**Error:** 
clusterRole.rbac.authorization.k8s.io "admin" not found

**Comment by cjellick** [comment]
It seems that in 1.9, kubernetes made a change such that it does not create its built in roles if RBAC is off. But I was not able to reproduce this in 1.10, so the behavior seems limited to 1.9.
We observed this problem in minikube, but hadn't observed it in AKS because I don't think we upgraded the cluster to 1.9.

To work around, the easiest fix is to just create these built in roles manually. You could do so by downloading tand unzipping the attached file and running 
```
kubectl apply -f clusterroles.yaml
```
I havent thoroughly tested this yet, but I believe it should work
[clusterroles.zip](https://github.com/rancher/rancher/files/1958869/clusterroles.zip)

**Comment by david-maumenee** [comment]
I apply clusterroles.yaml

The clusterRole "admin" was successfully created
```
kubectl apply -f clusterroles.yaml
clusterrole "admin" created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
clusterrole "cluster-admin" configured
clusterrole "edit" created
clusterrole "view" created

kubectl get clusterRole
NAME                                AGE
admin                               9m
cluster-admin                       2d
cluster-owner                       2d
edit                                9m
project-bgdn2-namespaces-edit       2d
project-bgdn2-namespaces-readonly   2d
project-owner                       2d
project-owner-promoted              2d
view                                9m
```

**But I'm still unable to connect to the cluster via kubectl embedded in Rancher.**
There is no more error in Rancher Server Log.

But an error in my browser
```WebSocket connection to 'wss://35.xxx.11.yy/v3/clusters/c-dtsbn?shell=true' failed: Error during WebSocket handshake: Unexpected response code: 404```

**Comment by dnauck** [comment]
I've also the `clusterRole.rbac.authorization.k8s.io "admin" not found`message with the default AKS cluster during cluster provisioning (the only AKS 1.8.1 k8n version from the rancher ui). So its not only 1.9.

**Comment by soumyalj** [comment]
Reopened this issue. Related to this issue 
https://github.com/rancher/rancher/issues/13921

**Comment by nathan-jenan-rancher** [comment]
Unable to reproduce.  @soumyalj if you see this issue again please preserve the environment so we can investigate the root cause.

**Comment by soumyalj** [comment]
Tested with master.
1. Create a AKS cluster with k8sv1.8.10 on Azure portal
2. Import the AKS cluster to rancher
After import, kubectl shell launched successfully from rancher
Creation of pods succeeded.
Remote kubectl also worked
3. Upgraded K8s on Azure portal to v1.9.9
Upgrade succeeded. After uograde, kubectl shell launched successfully from rancher
Remote kubectl also worked
<img width="1534" alt="screen shot 2018-07-30 at 1 27 10 pm" src="https://user-images.githubusercontent.com/18536626/43421685-4ba31374-93fc-11e8-91f7-580779773548.png">
