### ISSUE TITLE
intermittent 403 

### ISSUE THREAD

**Issue by ballerabdude** [rancher/rancher#13197]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0-rc3
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Not sure how to reproduce this but it seems to fix its self If I wait a couple of minutes.

**Results:**
![image](https://user-images.githubusercontent.com/7660642/39408100-541d5db6-4b9f-11e8-9b74-9df13711fb68.png)

![image](https://user-images.githubusercontent.com/7660642/39410244-0de178c2-4bc3-11e8-9ce3-5abe70bb6e78.png)

When this issue is up I get 403 from all rancher endpoints. I was getting this error when I was using an AD user and the default admin user.

**Comment by loganhz** [comment]
hi @ballerabdude , I can not reproduce this issue.  Can you try `v2.0.4`, please?

**Comment by loganhz** [comment]
Close this issue for rc version. Please re-open it if you still see this issue in v2.0.4
