### ISSUE TITLE
Can't provisionning K8S Cluster with rancher:preview

### ISSUE THREAD

**Issue by mathieu-gilloots** [rancher/rancher#13192]
**Rancher versions:**
rancher/server or rancher/rancher: preview
rancher/agent or rancher/rancher-agent: preview

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): not provisionned
rancher/rke-tools:v0.1.4

**Docker version: (`docker version`,`docker info` preferred)**
17.09.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancher os

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
K8S

**Steps to Reproduce:**
I try to create a K8s cluster with rancher 2 (preview).
Everything goes goods, but at the provisionning step, i'm stuck with healtcheck on kublet.
I'm on AWS, and my node template is : 
Rancher OS Latest
Require spot instance.

**Results:**
```
2018/04/28 16:49:17 [INFO] cluster [c-tvlsj] provisioning: [worker] Building up Worker Plane..
2018/04/28 16:49:17 [INFO] cluster [c-tvlsj] provisioning: [sidekick] Sidekick container already created on host []
2018/04/28 16:49:17 [INFO] cluster [c-tvlsj] provisioning: [sidekick] Sidekick container already created on host []
2018/04/28 16:49:17 [INFO] cluster [c-tvlsj] provisioning: [sidekick] Sidekick container already created on host []
2018/04/28 16:49:17 [INFO] cluster [c-tvlsj] provisioning: [healthcheck] Start Healthcheck on service [kubelet] on host []
2018/04/28 16:49:17 [INFO] cluster [c-tvlsj] provisioning: [healthcheck] Start Healthcheck on service [kubelet] on host []
2018/04/28 16:49:17 [INFO] cluster [c-tvlsj] provisioning: [healthcheck] Start Healthcheck on service [kubelet] on host []
2018/04/28 16:50:07 [ERROR] cluster [c-tvlsj] provisioning: [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host []: Get https://localhost:10250/healthz: dial tcp [::1]:10250: getsockopt: connection refused

```

**Comment by mathieu-gilloots** [comment]
Update : It's working when I didn't check the "Amazon" Checkbox in Cloud Provider at the creation of my Cluster in the UI.

**Comment by sra** [comment]
I see this exact problem also if you check the Amazon cloud provider when creating the cluster. Otherwise it comes up and registers ok. This is with v2.0.0-beta4

**Comment by deniseschannon** [comment]
This should be fixed in `rancher/rancher:v2.0.0-rc3`.

**Comment by sra** [comment]
I do have an IAM role set there that we use with other versions of rancher - maybe it doesn't have all the permissions required?

**Comment by superseb** [comment]
Let us know if this is still happening on the latest version.
