### ISSUE TITLE
Rancher 2.0 node install doesn't support http proxy

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13206]
**Rancher versions:**
rancher/server:preview

**Infrastructure Stack versions:**
defaults

**Docker version: (`docker version`,`docker info` preferred)**
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Simple topology with 1 master and 1 worker.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Create a cluster.
Create a provider node template (e.g openstack)
Provisioning will never complete and fail.

**Results:**
The initial bash script to install docker never completes because it's not aware of http proxy in target provider node environment.

```
cloud-u+ 16527  0.0  0.0 113132  1568 pts/0    Ss+  15:15   0:00  |       \_ bash -c if ! type docker; then curl -sSL https://releases.rancher.com/install-docker/17.03.sh | sh -; fi
cloud-u+ 16550  0.0  0.0 256556  3492 pts/0    S+   15:15   0:00  |           \_ curl -sSL https://releases.rancher.com/install-docker/17.03.sh
```

I have not seen anywhere to define this.
We seem to only be able to define it at the docker engine level, but we don't reach that point.

**Comment by alexandrem** [comment]
So this is actually a problem with how docker-machine provisions the nodes.

It doesn't take into consideration http proxy env vars for the ssh commands it sends. From a quick skim through the code there doesn't seem to be a way to make it work, which is quite surprising since docker-machine has been around quite some time.

**Comment by alexandrem** [comment]
Workaround for me is to fork the 17.03.sh install script and add my proxy information in it, then provide this script with a URL somewhere.

Curious to know if there's a better way.

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/30408
