### ISSUE TITLE
Rancher Agent doesn't work with CentOS/RHEL 6

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1320]
v0.25.0-rc1

Docker 1.6.2
CentOS/RHEL 6

Fresh install, rancher agent doesn't start.

There are no logs from the rancher agent containers.

**Comment by amondnet** [comment]
+1

**Comment by deniseschannon** [comment]
With Docker 1.8, Docker only supports CentOS 7 so Rancher will not be supporting CentOS 6.

https://docs.docker.com/installation/centos/
https://github.com/docker/docker/issues/14365
