### ISSUE TITLE
Can provision k8s cluster on AWS, but it's not available to manage

### ISSUE THREAD

**Issue by vojtasvoboda** [rancher/rancher#13200]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0-beta3
rancher/agent or rancher/rancher-agent:
Rancher user intarface: v2.0.35

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
AWS EC2 t2.medium, eu-central-1a

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, internal DB. Default setup.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes.

**Steps to Reproduce:**
1. Install Rancher
2. Create Kubernetes nodes on AWS - one master and one worker.

**Results:**
EC2 are successfully created, but Rancher shows error: `[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [35.158.243.106]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: getsockopt: connection refused.`

<img width="1255" alt="snimek obrazovky 2018-04-30 v 10 59 18" src="https://user-images.githubusercontent.com/374917/39420671-e6b0d042-4c65-11e8-8f20-480f17a835df.png">

**Comment by phynias** [comment]
running into this issue as well. i followed this page (https://rancher.com/docs/rancher/latest/en/kubernetes/providers/) to make sure i have all the permissions needed and i still get this error.

**Comment by superseb** [comment]
Best way to determine whats going on is to onto the host (download keys in the options menu of the host) and run `docker logs kubelet`

**Comment by phynias** [comment]
not seeing anything in the logs that is jumping out at me. logs are pretty big so i didn't want to dump it all here but will if needed.
one thing i did notice is that the url it is trying to hit is https://localhost:6443/healthz
when i curl that it comes back with an ssl error and won't continue unless i add "-k" (insecure). might this be happening when rancher is checking the url?

**Comment by superseb** [comment]
That's fine, the check uses the internally generated certificates to validate. If you can share the `kubelet` logs, that would help.

**Comment by phynias** [comment]
[kube.log](https://github.com/rancher/rancher/files/1972766/kube.log)

**Comment by phynias** [comment]
also just noticed my error is slightly different.
[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [18.144.32.100]: Get https://localhost:6443/healthz: **can not build dialer to c-zgx7x:m-bqxzt**

**Comment by phynias** [comment]
anythingi the log that could help me out this this ?

**Comment by superseb** [comment]
Cannot build dialer is usually:

* Ports 80/443 not reachable from created node to `rancher/rancher` container
* Invalid certificate configuration (if not using default self signed certificates or Let's Encrypt)

First 100 lines of the `rancher/rancher-agent` container will help here.

**Comment by phynias** [comment]
so i hopped on each of my rancher servers running rancher/rancher-agent and this is all that is in their logs.
 
```
time="2018-05-02T20:37:57Z" level=info msg="Option controlPlane=false"
time="2018-05-02T20:37:57Z" level=info msg="Option worker=false"
time="2018-05-02T20:37:57Z" level=info msg="Option requestedHostname=192.168.199.146"
time="2018-05-02T20:37:57Z" level=info msg="Option customConfig=map[address:192.168.199.146 internalAddress: roles:[]]"
time="2018-05-02T20:37:57Z" level=info msg="Option etcd=false"
time="2018-05-02T20:37:57Z" level=info msg="Connecting to wss://rancher.mydomain.com/v3/connect with token bqzv4sjpm5rfcc6rgpzkf8lvsq7vk2cwdzxfsflrlg9xfzfvtxlhbc"
time="2018-05-02T20:37:57Z" level=info msg="Connecting to proxy" url="wss://rancher.mydomain.com/v3/connect"
time="2018-05-02T20:37:57Z" level=info msg="Starting plan monitor"
time="2018-05-05T02:08:02Z" level=error msg="Failed to connect to proxy" error="websocket: close 1006 unexpected EOF"
time="2018-05-05T02:08:12Z" level=info msg="Connecting to wss://rancher.mydomain.com/v3/connect with token bqzv4sjpm5rfcc6rgpzkf8lvsq7vk2cwdzxfsflrlg9xfzfvtxlhbc"
time="2018-05-05T02:08:12Z" level=info msg="Connecting to proxy" url="wss://rancher.mydomain.com/v3/connect"
time="2018-05-05T02:08:12Z" level=info msg="Starting plan monitor"
```

i then curled the urls it was trying to hit and it was able to connect. came back with 'failed authentication', but was able to connect.

the load balancer in front of rancher is wide open on ports 80/443 and as for the cert is a cert i got through letsencrypt and comes up perfectly valid when i visit the site.

**Comment by superseb** [comment]
If the error is `Failed to check https://localhost:10250/healthz for service [kubelet]`, please post `docker logs --tail=all kubelet` as that will reveal why kubelet can't start/is unreachable.

@phynias For using provider, please check https://rancher.com/docs/rancher/v2.x/en/concepts/clusters/cloud-providers/#amazon

**Comment by cyrilbkr** [comment]
ok after setting up iam profil for aws it work ! thanks

**Comment by phynias** [comment]
ok, so i had the IAM already and it wasn't working. so today i decided to create a new policy and role  and suddenly it works. it is the same as what i had before but it works for some reason....

one thing i am confused by is a message that shows up under the nodes. not sure what it means.

<img width="677" alt="screen shot 2018-05-11 at 12 00 08 pm" src="https://user-images.githubusercontent.com/10147213/39942015-1ef444f6-5513-11e8-8e17-44b95d099d05.png">


the 
"failure-domain.beta.kubernetes.io/region=us-west-1 "

**Comment by superseb** [comment]
Those are labels automatically by Kubernetes when nodes are in AWS to provide failure-domain information.

**Comment by hichichachac** [comment]
> If the error is `Failed to check https://localhost:10250/healthz for service [kubelet]`, please post `docker logs --tail=all kubelet` as that will reveal why kubelet can't start/is unreachable.
> 
> @phynias For using provider, please check https://rancher.com/docs/rancher/v2.x/en/concepts/clusters/cloud-providers/#amazon

Hi superseb,

Please help me, this is log in my host:
I0914 08:52:29.846206   27791 server.go:755] Started kubelet
E0914 08:52:29.846808   27791 kubelet.go:1282] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
I0914 08:52:29.847124   27791 server.go:129] Starting to listen on 0.0.0.0:10250
I0914 08:52:29.848427   27791 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
I0914 08:52:29.848452   27791 status_manager.go:140] Starting to sync pod status with apiserver
I0914 08:52:29.848477   27791 kubelet.go:1773] Starting kubelet main sync loop.
I0914 08:52:29.848504   27791 kubelet.go:1790] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
I0914 08:52:29.849005   27791 container_manager_linux.go:425] [ContainerManager]: Discovered runtime cgroups name: /system.slice/docker.service
E0914 08:52:29.849138   27791 container_manager_linux.go:583] [ContainerManager]: Fail to get rootfs information unable to find data for container /
I0914 08:52:29.849176   27791 volume_manager.go:245] The desired_state_of_world populator starts
I0914 08:52:29.849184   27791 volume_manager.go:247] Starting Kubelet Volume Manager
I0914 08:52:29.850902   27791 server.go:299] Adding debug handlers to kubelet server.
W0914 08:52:29.851692   27791 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
E0914 08:52:29.851951   27791 kubelet.go:2121] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
F0914 08:52:29.853852   27791 server.go:141] tls: failed to find any PEM data in certificate input
 
Tks.

**Comment by superseb** [comment]
@hichichachac Please file a new issue with the requested info and read https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions, so we can investigate and reproduce. This is a closed issue.

**Comment by hichichachac** [comment]
> @hichichachac Please file a new issue with the requested info and read https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions, so we can investigate and reproduce. This is a closed issue.

Okie @superseb , thanks for help me.
