### ISSUE TITLE
Update strategy not being return from API

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13213]
**Rancher versions:** 2.0 master 4/30

**Steps to Reproduce:**
1.  Create a workload and set the Scaling/Upgrade Policy to Kill All pods, then start new

**Results:**  UI is sending strategy = "Recreate" but API is not sending back or saving.

![default](https://user-images.githubusercontent.com/3146226/39403076-ed043f14-4ba3-11e8-835c-24496bc0a102.JPG)

**Comment by tahoward** [comment]
@tfiduccia 
I'm not sure if this is related but it appears setting scaling policy to `Rolling: stop old pods, then start new` on a new workload via UI does not persist and appears to revert to `Rolling: start new pods, then stop old`.

**Comment by alena1108** [comment]
@loganhz put a PR for api, so Recreate is present now, when set on Create:

```
"deploymentConfig": {
"minReadySeconds": 0,
"progressDeadlineSeconds": 600,
"revisionHistoryLimit": 10,
"strategy": "Recreate"
},
```

 but corresponding Radio button is not checked in the UI on edit. Could you check on this UI issue?

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Verified fixed - both issues.
