### ISSUE TITLE
Failure to increase the scale of workload with node scheduling set to a specific node

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13217]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.0-rc4

**Steps to Reproduce:**
1. Create a GKE cluster 
2.Create a workload of scale 1 with node scheduling set to a specific node like: 
![screen shot 2018-04-30 at 6 24 34 pm](https://user-images.githubusercontent.com/18536626/39457618-d80c1e0a-4ca3-11e8-8fb8-2f999cd05a1b.png)

3. Workload comes up correctly
4. Increase the scale of the workload

Pods do not scale. It fails with the error below
![screen shot 2018-04-30 at 6 27 40 pm](https://user-images.githubusercontent.com/18536626/39457658-347b7e56-4ca4-11e8-99fc-0d6ea759e5c1.png)

**Comment by soumyalj** [comment]
Tested with master. 
1. Created a GKE cluster. 
2. Create a workload of scale 1 with node scheduling set to a specific node 
3. Increase the scale of the workload by 1
When the scale is increased by 1, it creates two pods and one is stuck in pending state

<img width="1216" alt="screen shot 2018-05-11 at 3 41 05 pm" src="https://user-images.githubusercontent.com/18536626/39949766-c0c5d786-5531-11e8-9765-bb9dbb1920be.png">

**Comment by StrongMonkey** [comment]
@vincent99 @loganhz on the second edit, request is sent with an empty scheduling rule. 
![screenshot from 2018-05-14 14-11-43](https://user-images.githubusercontent.com/9203378/40023769-00e4a9a4-5781-11e8-8b77-8e2ca6b205fd.png)

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/40037440-df3f26ca-583f-11e8-9ea4-9e4b66d676d8.png)

@StrongMonkey 

When you create the workload, UI sends node id like `$c-ghzbb:m-0c14d660cb02` to backend.
But server populates it as `m-0c14d660cb02`.

So when you scale it, UI sends the `scheduling:{node: { nodeId: "m-0c14d660cb02"}` to backend.

Server will drop the `nodeId` field of  `scheduling.node`

I guess we need to fix it by populating `nodeId` in the format of `${cluster-id}:${node-id}`

**Comment by StrongMonkey** [comment]
@loganhz i see the problem now. Thanks

**Comment by bmdepesa** [comment]
rancher/rancher:master 5/15

On GKE cluster, deployed workload with node scheduling set to run all pods on a specific node, scaled up to 5 pods and scaled down with no issues.
