### ISSUE TITLE
Need more information of a Container starting up

### ISSUE THREAD

**Issue by screwgoth** [rancher/rancher#1321]
From the WebUI : 
Rancher : v0.24.0
Cattle : v0.56.0
User Interface : v0.28.0

On my single Amazon EC2 host, I Added an official MySQL (latest) container , with no other config than an environment variable to set the DB password (MYSQL_ROOT_PASSWORD).
Not only did the Container never start, but the status only showed "Starting" in the "CONTAINERS" tab and "Networking" in the "HOSTS" tab.
(See attached image)

Some more information like boot logs or boot console, time taken since Container was started, etc. would be helpful 

![rancher - containers tab - mysql](https://cloud.githubusercontent.com/assets/153628/8355337/4c33e234-1b6c-11e5-9cd4-b8d8523aa244.png)
![rancher - hosts tab - mysql](https://cloud.githubusercontent.com/assets/153628/8355338/4c3b307a-1b6c-11e5-924b-e21e5e372ff1.png)

**Comment by screwgoth** [comment]
Oops Sorry, closed by mistake. Re-opening

**Comment by vincent99** [comment]
There is additional info shown in the container details screen when available.
