### ISSUE TITLE
Error when increasing the scale of a workload using volume claim

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13220]
**Rancher versions:**
rancher/rancher: v2.0.0-rc4

**Steps to Reproduce:**
1. Create a GKE cluster
2. Create a disk of 10G or higher in GCE portal
3. Create a volume "vol1" a the cluster level
4. Create a persistent volume claim using the volume "vol1"
5. Create a workload using the volume claim and the workload gets created successfully
6. Increase the scale of the workload

Workload is stuck in updating state and the pod is in "unavailable" state

![screen shot 2018-04-30 at 10 15 37 pm](https://user-images.githubusercontent.com/18536626/39462115-17a759ec-4cc4-11e8-9d6d-d575d3915e02.png)

```
Events:
  Type     Reason                 Age   From                                             Message
  ----     ------                 ----  ----                                             -------
  Normal   Scheduled              35s   default-scheduler                                Successfully assigned test1-7bcc48cf6f-77bp2 to gke-c-fmgdm-default-pool-dc5f299c-l3jl
  Warning  FailedAttachVolume     35s   attachdetach-controller                          Multi-Attach error for volume "testvol" Volume is already exclusively attached to onenode and can't be attached to another
  Normal   SuccessfulMountVolume  35s   kubelet, gke-c-fmgdm-default-pool-dc5f299c-l3jl  MountVolume.SetUp succeeded for volume "default-token-r5hxb"


```

The pod gets scheduled to a different host and the above error is seen

**Comment by StrongMonkey** [comment]
This is not a rancher bug as k8s is not that smart to schedule pod to the same host if pvc is singleNodeRW. Unless we add a scheduling rule to schedule pod to when deployment is using a singleNodeRW pv, but this needs to be discussed.

**Comment by soumyalj** [comment]
I see the same issue in Amazon EKS cluster also.

**Comment by StrongMonkey** [comment]
@soumyalj @alena1108 i don't think it is fixable as k8s scheduler is not that smart to schedule pods into the same host if using singleNodeReadWrite. You should be able to add schedule rules to one host and then scale the deployment.
