### ISSUE TITLE
Using Reset to Default when editing Settings removes the setting

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13225]
Version: v2.0.0-rc5

Go into Settings, choose Edit on a setting and click `Reset to Default`. The value is "reset", but actually the key is removed from the API entirely. For example, resetting `server-url` results in:

```
{
"actions": { },
"baseType": "error",
"code": "NotFound",
"links": { },
"message": "settings.management.cattle.io \"server-url\" not found",
"status": 404,
"type": "error"
}
```

This particular example will also break accessing the UI because the setting is missing. Workaround for now is to go to `https://localhost/v3/settings` and create the setting back using `Create` on the top right. Or restart `rancher/rancher` container.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/3
Verified fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/8
Verified fixed
