### ISSUE TITLE
xip.io Ingress rules don't work in GKE

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13223]
**Rancher versions:** v2.0.0

**Steps to Reproduce:**
1.  Create a nginx workload
2.  Create an ingress service and use the xip.io option to point to the nginx workload

**Results:**  404 page for all ports returned.  I didn't have open-compute-nodes network tag on my machines, should I have to have that?

**Comment by guangbochen** [comment]
@StrongMonkey ingress didn't work in the GKE now for both master and v2.0

**Comment by loganhz** [comment]
It works if the ServiceType is `NodePort`. We need to change it in charts.

**Comment by deniseschannon** [comment]
@guangbochen have you updated the charts?

@tfiduccia can we re-test?

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/16
Verified fixed - was able to get the nginx up after waiting 10 mins.
