### ISSUE TITLE
GKE Cluster provision error

### ISSUE THREAD

**Issue by KingsDevelopment** [rancher/rancher#13224]
**Rancher versions:**
rancher/rancher:2.0.0-rc5

    Component | Version
    Rancher | master
    User Interface | v2.0.41
    Helm | dev
    Machine | dev

**Docker version: (`docker version`,`docker info` preferred)**

    Client:
    Version:	18.04.0-ce
    API version:	1.37
    Go version:	go1.9.4
    Git commit:	3d479c0
    Built:	Tue Apr 10 18:24:33 2018
    OS/Arch:	linux/amd64
    Experimental:	false
    Orchestrator:	swarm

    Server:
    Engine:
    Version:	18.04.0-ce
    API version:	1.37 (minimum version 1.12)
    Go version:	go1.9.4
    Git commit:	3d479c0
    Built:	Tue Apr 10 18:22:45 2018
    OS/Arch:	linux/amd64
    Experimental:	false

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GKE

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create GKE Service account
2. Create GKE Cluster with any configuration
3. Watch your console (:

**Results:**

    2018/05/01 08:27:28 [INFO] Provisioning cluster [c-lh2bj]
    2018/05/01 08:27:28 [INFO] Creating cluster [c-lh2bj]
    E0501 08:27:30.883393       1 generic_controller.go:204] ClusterController c-lh2bj recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:153
    /usr/local/go/src/runtime/asm_amd64.s:509
    /usr/local/go/src/runtime/panic.go:491
    /usr/local/go/src/runtime/panic.go:63
    /usr/local/go/src/runtime/signal_unix.go:367
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_client.go:39
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_client.go:38
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/cluster/cluster.go:151
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/cluster/cluster.go:79
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/service/service.go:201
    /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/driver.go:22
    /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:225
    /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:105
    /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:147
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:149
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:132
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:123
    /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:146
    /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:142
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:19
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:158
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:57
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:40
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:49
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_controller.go:122
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:250
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:190
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:178
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:170
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
    /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
    /usr/local/go/src/runtime/asm_amd64.s:2337

**Comment by snupa** [comment]
I've had the same issue with the same error outputted to me. For me, it was the missing permissions for the service account. Maybe double check them and try again?

**Comment by sixcorners** [comment]
I too get a nil pointer error.
![image](https://user-images.githubusercontent.com/585501/39696155-6c291076-51b2-11e8-954d-3f94ee4367d0.png)
does that look correct permissions wise?

**Comment by loganhz** [comment]
Please try it with v2.1.0

Document is here https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/gke/#create-a-service-account

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
