### ISSUE TITLE
Validate Ubuntu 18.04 Bionic Beaver

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13222]
New LTS release with Docker 17.12.1 via package `docker.io` in apt repository and 18.06 (latest Docker stable)

**Comment by dbsanfte** [comment]
I can confirm the existing Docker install scripts don't work on 18.04 (ie, https://releases.rancher.com/install-docker/17.06.sh)

**Comment by soumyalj** [comment]
On AWS Ubuntu 18.04 bionic server with Docker 17.12.1, validation tests succeeded for v1.6.19-rc2
There is a separate issue for https://github.com/rancher/rancher/issues/14297
