### ISSUE TITLE
Please add option to ec2 provider to provision with private ip only

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#1322]
Rancher is awesome, but I am unable to use it until I can provision hosts in EC2 VPC with private IPs only.

The option already exists on the driver `--amazonec2-private-address-only`. Exposing this as a checkbox in the VPC/Subnet section should be a good place for this.

Thanks for the awesome product, can't wait to see what you come up with next.

**Comment by flaccid** [comment]
Was this one implemented in v0.28.0 ?

**Comment by vincent99** [comment]
Yup, thanks @flaccid

**Comment by flaccid** [comment]
Cool thought so was just checking so maybe this is good to close now?

**Comment by deniseschannon** [comment]
Verified Fixed in v0.30.0-rc2. The UI has the option and it's set in the logs in the docker-machine command.
