### ISSUE TITLE
workload Ingress UI not deleting rules as expected

### ISSUE THREAD

**Issue by smiller393** [rancher/rancher#13241]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0 RC3
rancher/agent or rancher/rancher-agent: 2.0 RC3

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10

**Docker version: (`docker version`,`docker info` preferred)**
docker 17.03
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal vm
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8
**Steps to Reproduce:**
When editing the rules of an ingress I noticed that rules weren't being deleted even after removing them and saving as seen in the screen shots below.

After removing the default rule:
<img width="1346" alt="screen shot 2018-05-02 at 12 18 58 am" src="https://user-images.githubusercontent.com/1131609/39505242-fd70fdc2-4d9e-11e8-9963-df1caaa1bf42.png">

Going back to the list of load balencers, two defaults are shown that match:
<img width="723" alt="screen shot 2018-05-02 at 12 16 33 am" src="https://user-images.githubusercontent.com/1131609/39505286-38815bdc-4d9f-11e8-8e27-12ce3c79bd5e.png">

When I go back into the ingress i see this again:
<img width="1338" alt="screen shot 2018-05-02 at 12 19 26 am" src="https://user-images.githubusercontent.com/1131609/39505322-6b55dd08-4d9f-11e8-85ad-f90b55aa1c41.png">

It seems to always force you to have a default rule, so possibly the UI should not allow you to remove a default rule on the edit ingress view.

**Comment by tfiduccia** [comment]
Version - v2.0.0
Could be related to https://github.com/rancher/rancher/issues/13238?

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/8
Verified fixed
