### ISSUE TITLE
rancher-agent should error out if configured cacerts is not equal to retrieved certificate

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13244]
**Rancher versions:**
rancher/rancher: v2.0.0
rancher/rancher-agent: v2.0.0

Agent should error out if cacerts does not match as it can cause issues later on.
 
```    
if [ "$(sha256sum $temp | awk '{print $1}')" != $CATTLE_CA_CHECKSUM ]; then
        rm -f $temp
        warn $CATTLE_SERVER/v3/settings/cacerts does not match $CATTLE_CA_CHECKSUM
```

**Comment by sangeethah** [comment]
Tested with latest build from master:

Start rancher-server with self signed certs.
Edit cacerts settings to make the ca-cert invalid.

Create a custom cluster.
Add a node to the cluster.

Rancher agent reports the following error but it constantly keeps restarting.

```
ERROR: Configured cacerts checksum (9a67a40ea60817029b02c46d94f88966dbc5a4cfc02fa551bd9e3b2fc2bfed18) does not match given --ca-checksum (a3ae58ed228acbdb9989b0d4017139cae079c345545fc796fff4323d539d1f43)
ERROR: Please check if the correct certificate is configured at https://206.189.238.40/v3/settings/cacerts
```

agent register command does have ```--restart=unless-stopped``` .

**Comment by corentin59** [comment]
Reproduced on rancher/rancher-agent:master

> ERROR: Configured cacerts checksum (XXX) does not match given --ca-checksum (XXX)
ERROR: Please check if the correct certificate is configured at https://rancher.docker.xxx.lan/v3/settings/cacerts

**Comment by deniseschannon** [comment]
@sangeethah this is the correct behavior. It's restarting due to the restart policy, but the error is in the logs, which indicates the issue and why it's restarting.
