### ISSUE TITLE
Rancher agent cannot authenticate with ECR during upgrade.

### ISSUE THREAD

**Issue by waarg** [rancher/rancher#13246]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.14
rancher/agent or rancher/rancher-agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 0.2.3
network-services: 0.2.9
scheduler: 0.8.3-1
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**  
17.09.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
3.10.0-693.21.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** 
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
Rancher HA external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** 
Cattle

**Steps to Reproduce:**

Set AWS ECR as default registry and pre-populate ECR with Rancher images. Use ecr-updater catalog item to manage ECR authentication within Rancher and ecr-credential-helper for ECR authentication on the host (for manual pulls). Upgrade Rancher from 1.6.14 > 1.6.16. When the agent goes to upgrade from 1.2.9 to 1.2.10 it fails to pull from ECR with an ECR authentication error. All pulls successfully authenticate with ECR except this in-place agent upgrade. A workaround is to volume mount the ECR credential helper and its config into the agent container however have been advised by @chrisurwin that this may interfere with the agent and to raise this as an issue.

**Comment by deniseschannon** [comment]
This is actually by design. We never intended to have the agent upgrade be able to pull credentials from a registry to grab images. 

We will document best practices on how to prepare for an upgrade if you are using a registry that requires credentials. We recommend using a catalog item that will help pull all the necessary images that your hosts will need prior to the upgrade.

**Comment by soumyalj** [comment]
Tested with pre-pull images on rancher v1.6.18-rc3. Set the default registry to a private registry. Launched the catalog pre-pull images specifying the required agent image. The agent image was pre-pulled on all the hosts.
