### ISSUE TITLE
yaml create ceph-pv  ok ,but web add cephfs-pv ceph-secret can't send to the back end (master)

### ISSUE THREAD

**Issue by huangyanhong** [rancher/rancher#13247]
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**   17.09.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** centos 7.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** ceph

**Setup details:  single node rancher(master)

**Environment Template:  Kubernetes

**Steps to Reproduce:** create cephfs-pv on the web , config Secret :ceph-secret ,saved，Secret show blank  when look over the ceph-pv info,
F12 debug WEB , web does't’ send Secret to the back end. 

**Results:**

**Comment by loganhz** [comment]
Did you create the secret from UI. The secret must have `kubernetes.io/rbd` field for Ceph. https://github.com/rancher/rancher/issues/13198#issuecomment-391299025

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/42141097-50fd64b6-7dd9-11e8-8fdd-2d716c3c3257.png)

Secret is populated correctly for Ceph
