### ISSUE TITLE
Get error if I try to create ingress service with two .xip.io rules

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13240]
**Rancher versions:** v2.0.0

**Steps to Reproduce:**
1.  Create two workloads
2.  Add Ingress and add two rules, each one should have xip.io option selected & point to one of the two workloads
3.  Save

**Results:** Error - "Validation failed in API: Ingress.extensions "test" is invalid: spec.rules[0].http.backend.serviceName: Required value"
![image](https://user-images.githubusercontent.com/11514927/39499963-2653d446-4d66-11e8-8d7a-81f0ebb6d796.png)

Dev tools error: ember-fetch.js:471 POST https://35.188.23.177/v3/projects/c-f26k7:project-84cjt/ingress 422 (Unprocessable Entity)

**Comment by sangeethah** [comment]
same as  - https://github.com/rancher/rancher/issues/13185

**Comment by loganhz** [comment]
The payload looks good. I guess we should fix it in backend

same as - #13185

**Comment by loganhz** [comment]
fixed in 13185
