### ISSUE TITLE
Cluster stuck in "removing" state - "Removing host [<ip>] from node lists; waiting on foregroundDeletion"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13259]
**Rancher versions: v2.0.0
**Steps to Reproduce:**
Had  few custom clusters with AWS nodes in "active" state.
Deleted all the AWS nodes (from AWS console).
After some time , deleted all the clusters from rancher server

One of the cluster got stuck in "removing" state forever with status - "Removing host [<ip>] from node lists; waiting on foregroundDeletion"

**Comment by cjellick** [comment]
@StrongMonkey is this fixed?  Did we switch everything to background deletion?

**Comment by StrongMonkey** [comment]
@cjellick we have to change our delete policy to background deletion so it shouldn't block deletion anymore. Deplicate of https://github.com/rancher/rancher/issues/11991.

**Comment by sangeethah** [comment]
Tested with latest build from master.

Had custom clusters with AWS nodes in "active" state.
Deleted all the AWS nodes (from AWS console).
After some time , deleted the clusters from rancher server
Cluster got removed successfully.
Not able to reproduce the issue were the cluster is stuck in "removing" state.
