### ISSUE TITLE
Private Label (ui-pl) doesn't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13257]
**Rancher versions:** v2.0.0

**Steps to Reproduce:**
1.  Go to settings
2.  Change the ui-pl to something else

**Results:** Nothing changes, everything in UI still displays Rancher.

**Comment by dramich** [comment]
The setting is available at `/v3/settings/ui-pl`, needs UI work.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/26
Verified fixed
