### ISSUE TITLE
deploy cluster with kubernetes 1.10.1 rancher1 needs a restart of docker

### ISSUE THREAD

**Issue by gabx** [rancher/rancher#13255]
With Rancher 2 UI, deploy a cluster, all default options.
Each new created node will throw this error:
`Failed to start [rke-etcd-port-listener] container on host [10.52.11.179]: Error response from daemon: driver failed programming external connectivity on endpoint rke-etcd-port-listener (05fcbf41923cc36c3acc1e1266b89c952791dfcae668ce06d9bd8b678cdf8e4d): (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 2380 -j DNAT --to-destination 172.17.0.2:1337 ! -i docker0: iptables: No chain/target/match by that name. (exit status 1))`

I need to run `# systemctl restart docker` on each node to get rid of this error.

Installing with **kubernetes 1.10.0 rancher1-1** does not produce this error and the cluster is created as expected.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by tfiduccia** [comment]
@gabx  - I cannot reproduce this error in v2.0.0.  Can you tell me what type of cluster you are deploying?

**Comment by superseb** [comment]
Needs more info, the only difference is the upstream hyperkube image that should trigger the behavior. Can you share:

OS info (`cat /etc/os-release`, `uname -r`)
Docker info (`docker info` and `docker version`)

Docker daemon logging when it happens could be helpful as well.

**Comment by gabx** [comment]
```C
NAME=Fedora
VERSION="27 (Cloud Edition)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Cloud Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Cloud Edition"
VARIANT_ID=cloud
```
**kernel 4.15.14-300.fc27.x86_64**

```C
Containers: 21
 Running: 19
 Paused: 0
 Stopped: 2
Images: 10
Server Version: 17.12.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.11.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.15.14-300.fc27.x86_64
Operating System: Fedora 27 (Cloud Edition)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.821GiB
Name: control2
ID: PIZ7:KA2Z:SPZW:PO7W:TIYP:V6V3:BRZH:XNIU:7NI5:ORTQ:HFGZ:GQTU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```C
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:12:17 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:14:50 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by gabx** [comment]
Again this error with rancher 2.0.2, rke v0.1.8-rc7. Restarting docker will not change anything this time. Not sure where this issue comes from, but I guess bad iptables settings.

**Comment by superseb** [comment]
This is not reproducible. Please provide us with the cloud image you are using and the modification you have done (exact steps) so we can create the same situation as you are in, and run tests. I just tested on Fedora Atomic 28 with built-in Docker and Fedora Atomic 28 with Docker CE and both provision fine using `rke up`.

**Comment by gabx** [comment]
This issue comes randomly on my machines. No idea why I sometimes need to restart docker. 
Close this issue if you feel it, as I can't tell you more.

**Comment by superseb** [comment]
I can run more tests if you can supply the requested info above. And possibly what workloads you are running or what is happening on the cluster, basically anything that helps reproducing.

**Comment by bobo325** [comment]
saw your title at first sight ,I have solved my problem ,thank you very much!
