### ISSUE TITLE
If only 1 template in drop-down, default to that template

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13256]
**Rancher versions:** v2.0.0

**Steps to Reproduce:**
1.  Create a AWS node tempalte
2.  Go to Add cluster and select AWS

**Results:**  The drop-down for Template in the Node Pools section is "Choose a Template", it would be nice to have it default to the only template that is available.
![image](https://user-images.githubusercontent.com/11514927/39545357-cf80c656-4e05-11e8-94c2-cb7fb4ecde35.png)

**Comment by tfiduccia** [comment]
@loganhz - you did this only for AWS.  Can you please do for all RKE cluster types?  Maybe a solution that is generic instead of specific so it will work for node drivers that customer add as well.

**Comment by loganhz** [comment]
Hi @tfiduccia , I can not reproduce this issue. 
It works for Azure and vSphere as well.

**Comment by tfiduccia** [comment]
hmmm... that is weird.  It wasn't working before, but seems to be working now.  I will close.
