### ISSUE TITLE
Editing openstack template, all values disappear 

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13254]
**Rancher versions:** v2.0.0

**Steps to Reproduce:**
1.  Activate the openstack node driver
2.  Add template and fill out all openstack values
3.  Edit template

**Results:**  All the values are not longer showing up.  Also getting a error in dev console when I click edit for the template - component.js:53 Uncaught TypeError: Cannot read property 'set' of null

**Comment by dahendel** [comment]
I am having the same issue with a custom machine [driver](https://github.com/dahendel/docker-machine-driver-cloudstack/releases/download/v1.0.5/docker-machine-driver-cloudstack_Linux.amd64). Same steps to reproduce except import the custom driver.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/8
Verified fixed
