### ISSUE TITLE
Warn users when selecting Cloud Provider in Cluster Options

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13267]
**Rancher versions:**
rancher/rancher: v2.0.0

We need to put a warning on `Cloud Provider` in Cluster Options, as it is confusing users to select Amazon when using EC2 instances in a custom cluster for instance. The current warning is around cloud config that can break, but it needs to point out that without the prerequisites in place, the cluster will fail to come up.

We can also put the warning in the `Add Node` page, where it will list what is needed before adding the host.

In case of Amazon:

- IAM role on the instances
- Tagging resources with ClusterID

**Comment by loganhz** [comment]
It will be great if someone can help to list all of the detailed warning messages we need to add for cloud provider.

**Comment by deniseschannon** [comment]
@superseb could you help with what you think would be helpful?

**Comment by superseb** [comment]
Something like this would be sufficient:
```
Warning:
Configuring a Cloud Provider in your cluster without configuring the prerequisites will cause your cluster to not provision correctly. Prerequisites needed for supported cloud providers can be found in the Rancher documentation on Cloud Providers.
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Verified added.
