### ISSUE TITLE
No way to sort by Project when Grouped Project/Namespace

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13261]
**Rancher versions:** v2.0.0

**Steps to Reproduce:**
1.  Go to Project/Namespaces
2.  Add a bunch of projects
3.  Make sure Grouped Project/Namespace sorting is set

**Results:**  There is no way to group by Project Name.
![image](https://user-images.githubusercontent.com/11514927/39553873-8d4cf1fa-4e24-11e8-8605-3ed18bb84d51.png)

**Comment by tfiduccia** [comment]
@loganhz - I'm not sure what you did.  Can you please explain.  Everything looks the same.

**Comment by loganhz** [comment]
Hi @tfiduccia , now they are sorted by project name.

The order is

1. Projects (sort by project name) which have namespaces,.
2. `Not in a project` group.
3. Projects  (sort by project name) with no namespace.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Verified fixed
