### ISSUE TITLE
Node Templates - When creating a cluster or a running cluster

### ISSUE THREAD

**Issue by f1gjam** [rancher/rancher#13262]
Cannot removed templates, which are no longer needed, and or editing an existing template

See screen shot below.

Ideally you want to be able to copy a template (so you don't have to re-enter all of the details) and or edit an existing one. You should also be able to remove templates.

Imagine I wanted to make three clusters, all on vSphere, having to enter this information over and over again is just annoying. I should be able to create a vSphere node template and then when creating a cluster use those templates.

**Rancher versions:**
Rancher 2.o

**Infrastructure Stack versions:**
vSphere 6.5

**Steps to Reproduce:**

<img width="1225" alt="screen shot 2018-05-03 at 00 35 41" src="https://user-images.githubusercontent.com/3368330/39554306-f985bb82-4e69-11e8-88d7-cd5a08e8278f.png">

**Comment by tfiduccia** [comment]
Version - v2.0.0 - Edit & removing is available.

Edit & removing templates cannot be done from the Add/Edit Cluster.  It has to be done in the Node Template list page itself.  Which is accessible from clicking on User drop-down on top right.
![image](https://user-images.githubusercontent.com/11514927/39554523-27354260-4e28-11e8-868b-a4186bce3a08.png)

We currently do not have clone ability in v2.0.0 but there are plans to add it in future.

**Comment by alexandrem** [comment]
We're also very interested in this feature.

There are 2 improvements I can think of:
- global templates that all users can see and borrow from (created by rancher operator previously with admin access)
- live edition of a template (without losing the values) that creates a new template when using a different name

Users could easily start with a template and customize a few thing for their project.

Should we create separate issues for those?

**Comment by dan-and** [comment]
Global Templates would be extremely helpful.

**Comment by frenchtoasters** [comment]
I will also second what @alexandrem mentioned with the global and live templates. I would also suggest the following:

* Option when scaling up a node in a cluster to edit the template for the node that is scaled up, creating a new template in the process. The name could be `nodeX-template` 

In an environment where you are required to use static ip's you have to create a template for each node if you want Rancher to deploy/manage the nodes. Which also makes scaling up of nodes a cluster breaking event almost as you would have two nodes with the same roles and same IP's but different names. 

The ability to *at least* clone a template from the `Node Template` view would really help with this.

**Comment by loganhz** [comment]
For static IP issue, there is an enhancement for vSphere in https://github.com/rancher/rancher/issues/15817 

For global template issue, it will be covered in https://github.com/rancher/rancher/issues/12186

Clone node template feature is already in v2.1.1

Please submit a new issue if it is not covered. Thanks a lot !
