### ISSUE TITLE
external-lb F5 doesn't work with V5 v12+

### ISSUE THREAD

**Issue by JohnDavidLarsen** [rancher/rancher#13269]
**Rancher versions:**
rancher/server or rancher/rancher:  1.6.x

**Infrastructure Stack versions:**
rancher-cattle: 1.6.14
rancher/external-lb:v0.3.4

**Steps to Reproduce:**
using an F5 and rancher\external-lb to manage the F5, you can create new pools just fine.
If you scale up or down a service or make a change of any type, it tries to call the F5 and gets the error

{"code":400,"message":"0107028c:3: The source (::) and destination (123.123.123.123) addresses for virtual server (/Common/VS1) must be be the same type (IPv4 or IPv6).","errorStack":[]}

See https://devcentral.f5.com/questions/script-to-modify-virtual-servers-default-pool

Comment made 30-Aug-2016 by Dave Gibbs 2

In v12 we have had to change our PUT method to a PATCH which resolved this issue.

It seems the F5 most recent 1.6 external-lb is still trying to make a PUT call.
I think the most recent version of https://github.com/scottdware/go-bigip fixes this, as it seems to make PATCH calls, but I'm not positive. Likely simple recompiling external-lb to use the most recent version of scottdware/go-bigip should fix the issue.. Hopefully.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by patrick0057** [comment]
When evacuating a host, it isn't removed from load balancer as expected.  Please test this when applying the new patch.

**Comment by alena1108** [comment]
`rancher/external-lb:v0.3.5` has go-bigip vendor updated and can be used in the new catalog item.

**Comment by alena1108** [comment]
@prachidamle could you please provide instructions to qa on how to test

**Comment by patrick0057** [comment]
@prachidamle During testing we were not able to start the container after the upgrade to 0.3.5.  We even tried to deploy to a new stack instead of upgrading but we had the same results.  Once we reverted to the old version the container would start up once again.  There was nothing in the external-lb container logs and nothing that seemed relevant in the rancher/server logs.

**Comment by rawmind0** [comment]
Testing image `rancher/external-lb:v0.3.5`, executing `external-lb` with provider `f5_BigIP` results a segmentation fault. 

```
# /usr/bin/external-lb -provider=f5_BigIP
Segmentation fault
```

**Comment by alena1108** [comment]
@patrick0057 @rawmind0 go build arguments were off after upgrading to go 1.10.3; fixed in https://github.com/rancher/external-lb/pull/32; the fix is available in v0.3.6 release

**Comment by rawmind0** [comment]
@alena1108 image `rancher/external-lb:v0.3.6` is running fine.

**Comment by rawmind0** [comment]
Merged community-catalog PR updating package, https://github.com/rancher/community-catalog/pull/829

**Comment by alena1108** [comment]
Reopening as it seems to be the miscommunication, and the original issue is not addressed with the bigip update. On the bigip side - even on master - the put is used in place of patch: https://github.com/scottdware/go-bigip/blob/master/ltm.go#L1818

Marking the issue with `has-dependency` flag; have to figure out the steps forward as the problem in not in the external-lb code not being up to date, but in the library itself.

**Comment by rawmind0** [comment]
Opened and issue on library provider repo, https://github.com/scottdware/go-bigip/issues/80

**Comment by alena1108** [comment]
Clearing up the milestone as the fix is not mapped to any rancher release. Once fixed in the upstream, we'll just ship the fix in the catalog.

**Comment by deniseschannon** [comment]
It seems that this issue has been released with a new catalog item. If there are still issues, please re-open. @rawmind0 @patrick0057
