### ISSUE TITLE
[v2.0GA] When removing a node from cluster some containers still stay

### ISSUE THREAD

**Issue by mikekuzak** [rancher/rancher#13266]
Hi 

After removing a node from a Cluster via the UI I still see some container running, shouldn't they also be removed ? 

ab19b7fea26e        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint."   20 hours ago        Up 20 hours                             kube-proxy
d3b223f3ab5e        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint."   20 hours ago        Up 20 hours                             kubelet
576e4b318a67        rancher/rke-tools:v0.1.4             "nginx-proxy CP_HOSTS"   20 hours ago        Up 20 hours                             nginx-proxy
7bdd28ef8368        rancher/coreos-etcd:v3.1.12          "/usr/local/bin/etcd "   20 hours ago        Up 21 seconds                           etcd

Trying to re-register the same node back seems to fail: 

This cluster is currently Updating.
Failed to get kubernetes node [my-coreos03]: "my-coreos03" not found

Tried something else also. Stopped the remaining containers, removed them, Re-registered node. Now etcd is complaining: 

2018-05-03 10:44:12.592769 E | etcdserver: the member has been permanently removed from the cluster
2018-05-03 10:44:12.592782 I | etcdserver: the data-dir used by this member must be removed.

It looks to me the delete Node command in the UI is not doing the full job. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by loganhz** [comment]
Can you try v2.1.0, please?
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
