### ISSUE TITLE
Warn if logging target is no longer reachable

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13268]
**Rancher versions:**
rancher/agent:v2.0.0

**Steps to Reproduce:**
- Configure logging target (ElasticSearch)
- Shutdown ElasticSearch

**Results:**
- No indication that it's not able to forward logs.

**Comment by bmdepesa** [comment]
Is this warning supposed to appear on the logging configuration page? 

rancher/rancher:master 5/15

I configured logging to ElasticSearch
Verified logs were being transported correctly.
Disabled ElasticSearch (removed ES instance), while leaving rancher logging configuration untouched.

There is no warning on the logging configuration page, or the cluster dashboard after ~10 minutes.

**Comment by aiwantaozi** [comment]
@n313893254 Hi Qingyang, this on need UI integrate to show the warning, for elasticsearch, kafka, syslog, these three targets warning may like embedded, could you check?

**Comment by n313893254** [comment]
sure

**Comment by bmdepesa** [comment]
rancher/rancher:master 

Warning that logging target is unreachable is displayed correctly.
