### ISSUE TITLE
The node registering is stuck  

### ISSUE THREAD

**Issue by nrh387** [rancher/rancher#13264]
**Rancher versions:**
OS is 3.13.0-86-generic
Here is the docker info
Containers: 1
Running: 1
Paused: 0
Stopped: 0
Images: 15
Server Version: 17.03.2-ce
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 83
Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
apparmor
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: iZ947ei2rr7Z
ID: YDG7:CKNZ:SEUJ:XHKY:N6CT:5HQF:NOPL:KSL7:PQSC:BL24:N6VF:ZNQP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Registry Mirrors:
https://20bh91iy.mirror.aliyuncs.com
Live Restore Enabled: false
Here is docker version
Client:
Version: 17.03.2-ce
API version: 1.27
Go version: go1.7.5
Git commit: f5ec1e2
Built: Tue Jun 27 03:11:13 2017
OS/Arch: linux/amd64

Server:
Version: 17.03.2-ce
API version: 1.27 (minimum version 1.12)
Go version: go1.7.5
Git commit: f5ec1e2
Built: Tue Jun 27 03:11:13 2017
OS/Arch: linux/amd64
Experimental: false

**Steps to Reproduce:**
Register the node
**Results:**

018-05-02 14:07:45.941063 I | mvcc: finished scheduled compaction at 27142 (took 1.0263ms)
2018-05-02 14:12:45.949664 I | mvcc: store.index: compact 27591
2018-05-02 14:12:45.951784 I | mvcc: finished scheduled compaction at 27591 (took 1.335084ms)
2018/05/02 14:13:01 [INFO] Running cluster events cleanup
2018/05/02 14:13:01 [INFO] Done running cluster events cleanup
2018-05-02 14:17:45.957071 I | mvcc: store.index: compact 28041
2018-05-02 14:17:45.959180 I | mvcc: finished scheduled compaction at 28041 (took 1.417434ms)
2018-05-02 14:22:45.966659 I | mvcc: store.index: compact 28491
2018-05-02 14:22:45.969029 I | mvcc: finished scheduled compaction at 28491 (took 1.670694ms)
2018-05-02 14:27:45.973162 I | mvcc: store.index: compact 28940
2018-05-02 14:27:45.975911 I | mvcc: finished scheduled compaction at 28940 (took 1.895037ms)
2018-05-02 14:32:45.980541 I | mvcc: store.index: compact 29391
2018-05-02 14:32:45.984405 I | mvcc: finished scheduled compaction at 29391 (took 2.197185ms)
E0502 14:36:08.868731       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.869164       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.869318       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.869428       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.869901       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.870165       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.870276       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.870390       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.870631       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.871926       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872030       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872105       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872168       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872373       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872487       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872555       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872656       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872756       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872837       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.872990       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.873982       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.874061       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.874124       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.874189       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.874389       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.873993       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.875067       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.875126       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.875301       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.875477       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.875644       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.875669       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.876163       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.876582       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.876635       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.877049       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.877346       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.877788       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:08.877928       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:12.230387       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:12.231265       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0502 14:36:12.231645       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2018-05-02 14:37:45.988485 I | mvcc: store.index: compact 29839
2018-05-02 14:37:45.991061 I | mvcc: finished scheduled compaction at 29839 (took 1.608393ms)
2018-05-02 14:42:45.997821 I | mvcc: store.index: compact 30290
2018-05-02 14:42:46.000508 I | mvcc: finished scheduled compaction at 30290 (took 1.812457ms)
2018-05-02 14:47:46.015732 I | mvcc: store.index: compact 30738
2018-05-02 14:47:46.018491 I | mvcc: finished scheduled compaction at 30738 (took 1.452145ms)
2018-05-02 14:52:46.024687 I | mvcc: store.index: compact 31187
2018-05-02 14:52:46.027032 I | mvcc: finished scheduled compaction at 31187 (took 1.280105ms)
2018-05-02 14:57:46.032121 I | mvcc: store.index: compact 31637
2018-05-02 14:57:46.034324 I | mvcc: finished scheduled compaction at 31637 (took 1.406307ms)
2018-05-02 15:02:46.039690 I | mvcc: store.index: compact 32088
2018-05-02 15:02:46.042262 I | mvcc: finished scheduled compaction at 32088 (took 1.488394ms)
2018-05-02 15:07:46.048731 I | mvcc: store.index: compact 32538
2018-05-02 15:07:46.051981 I | mvcc: finished scheduled compaction at 32538 (took 2.347678ms)
2018-05-02 15:12:46.057430 I | mvcc: store.index: compact 32987
2018-05-02 15:12:46.060309 I | mvcc: finished scheduled compaction at 32987 (took 1.880923ms)
2018/05/02 15:13:01 [INFO] Running cluster events cleanup
2018/05/02 15:13:01 [INFO] Done running cluster events cleanup

**Comment by nrh387** [comment]
More information about this issue

2018/05/03 01:23:18 [ERROR] error updating ns default status: Operation cannot be fulfilled on namespaces "default": the object has been modified; please apply your changes to the latest version and try again
2018/05/03 01:23:18 [ERROR] error updating ns ingress-nginx status: Operation cannot be fulfilled on namespaces "ingress-nginx": the object has been modified; please apply your changes to the latest version and try again
2018/05/03 01:23:18 [INFO] projectSyncer: createDefaultNetworkPolicy: successfully created default network policy for project: project-t49cx
E0503 01:23:18.716643       1 generic_controller.go:204] ClusterRoleTemplateBindingController c-9jhkh/creator [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
E0503 01:23:18.840323       1 generic_controller.go:204] ProjectRoleTemplateBindingController project-t49cx/creator [cluster-prtb-sync] failed with : couldn't create role project-owner-promoted: clusterroles.rbac.authorization.k8s.io "project-owner-promoted" already exists
2018/05/03 01:23:18 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-t49cx to namespace=default
2018/05/03 01:23:19 [ERROR] error updating ns cattle-system status: Operation cannot be fulfilled on namespaces "cattle-system": the object has been modified; please apply your changes to the latest version and try again
2018/05/03 01:23:22 [INFO] Handling backend connection request [c-9jhkh]
E0503 01:26:00.575297       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.NodeStatus

**Comment by nrh387** [comment]
The rancher version is V2.0.0 GA

**Comment by nrh387** [comment]
The Node is the Ali Cloud ECS

**Comment by wanshaoyuan** [comment]
This problem is solved because the hostname has uppercase characters

**Comment by nrh387** [comment]
Thanks so much
