### ISSUE TITLE
Project Quota

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#13277]
Support the ability to set resource quotas at a project level.  The quota limits can be by:

- Memory
- CPU
- Storage

**Comment by alena1108** [comment]
The feature flow:

1) Admin creates project with `resourceQuota` field. Field would define the limits for the following resources:

````
Pods                   string `json:"pods,omitempty"`
Services               string `json:"services,omitempty"`
ReplicationControllers string `json:"replicationControllers,omitempty"`
Secrets                string `json:"secrets,omitempty"`
ConfigMaps             string `json:"configMaps,omitempty"`
PersistentVolumeClaims string `json:"persistentVolumeClaims,omitempty"`
ServicesNodePorts      string `json:"servicesNodePorts,omitempty"`
ServicesLoadBalancers  string `json:"servicesLoadBalancers,omitempty"`
RequestsCPU            string `json:"requestsCpu,omitempty"`
RequestsMemory         string `json:"requestsMemory,omitempty"`
RequestsStorage        string `json:"requestsStorage,omitempty"`
LimitsCPU              string `json:"limitsCpu,omitempty"`
LimitsMemory           string `json:"limitsMemory,omitempty"`
````


2) Every namespace created in that project, would require `defaultResourceQuota` parameter to be set (same format as `project.resourceQuota`). 

* If no  `defaultResourceQuota` is set by the user on the namespace, we'd try to inherit the parameter from `project. defaultNamespaceResourceQuota`. If that parameter is nil, the error would be thrown.
* If `namespace.defaultResourceQuota` + all other namespaces' defaultResourceQuota in the namespace exceeds `project.resourceQuota`, the error would be thrown.

3) There will be a controller listening for namespace create/update event, and it would create resourceQuota in the namespace with the limits defined in `namespace.defaultResourceQuota`.

**Comment by vincent99** [comment]
Is there a null/0/"I don't care about this feature" value to disable the whole thing?  I don't want to require users who aren't using quotas everywhere.  What if I want quotas but only on certain parts (e.g. I don't care how many ConfigMaps you make, go nuts).

How can specifying it on namespace even be really required?  Does something stop me from doing `kubectl create namespace foo` with no quota defined?  

`{Requests/Limits}{CPU/Memory/Storage}`:
  - I would think the primary thing an operator of a cluster is concerned with is setting an upper bound on how much physical resource user projects can each consume.. RAM, CPU, Storage.  I'm not sure that's what's actually happening here (and I don't think k8s even supports actual storage limits).
  - So how do these work?  You're limiting how high I can set those fields on individual workloads?
  - But what if they're not set at all,  then I usually get unlimited ceiling.  Are they now required if resource quotas is on?
  - As a human I'd think that this is saying "This namespace in aggregate can use a maximum of 10GB of RAM".   Is that what it's doing?
  - If it's just saying "each pod is individually limited to X GB of RAM" with no regard for others, that's not very intuitive or useful to reason about how much hardware this namespace can actually take up (which is then LimitsMemory*Pods, I guess, but I didn't know I actually cared about the pod limit until now?)

**Comment by alena1108** [comment]
@vincent99 

>> Is there a null/0/"I don't care about this feature"

Then you just don't set the `project.resourceQuota` field, or set it to nil

>> How can specifying it on namespace even be really required? Does something stop me from doing kubectl create namespace foo with no quota defined

The idea was to enforce the namespace to have a resource quota, because its absence = unlimited. I'm going to rework the current implementation a bit though to enforce RQ on a natively created namespace. Instead of setting a field on the namespace - that can be potentially modified natively - I'm going to introduce a `resourceQuotaBinding` CRD that has to be granted to the namespace explicitly via Rancher UI/API. By default, the namespace would get default resource quota on creation with 0/0/0/0 limit.


>> I would think the primary thing an operator of a cluster is concerned with is setting an upper bound on how much physical resource user projects can each consume.. RAM, CPU, Storage. I'm not sure that's what's actually happening here (and I don't think k8s even supports actual storage limits).


All the `limits` are "inherited" from the actual resource quota definition on k8s; storage is one of the resources:

https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota


>> So how do these work? You're limiting how high I can set those fields on individual workloads? But what if they're not set at all, then I usually get unlimited ceiling. Are they now required if resource quotas is on?

Once CPU/Memory limits are set via quota, every workload created in the namespace, **is required* to have CPU/Memory reservation defined in the spec, otherwise the workload creation fails - default k8s behavior.

>> As a human I'd think that this is saying "This namespace in aggregate can use a maximum of 10GB of RAM". Is that what it's doing?

correct

**Comment by alena1108** [comment]
Here is the redesigned approach to project level resource quota, based on discussion with @will-chan and @cjellick:

* Cluster admin/owner defines a resource quota on a project, which will act as an upper bound for all namespaces' resources created in this project, combined)
* Cluster admin/owner creates one or more **resourceQuotaTemplate** (a new CRD, same type as of `project.resourceQuota` field). The template would like a small/medium/large offerings that user would need to pick when create a namespace. There is `isDefault` flag that can be defined on the template.
* User creates a namespace, and passes `resourceQuotaTemplateId` as a field (optional). If the field is not set, and the project has `resourceQuota` defined, the namespace would get default template id assigned. This rule applies to the namespaces created natively.
* The controller will watch namespace create/update events, would validate resource quota limits derived from `namespace.resourceQuotaTemplateId` by checking if it's within `project.resourceQuota` limit.
* Once cluster admin enables `resourceQuota` on a project level, all resource quotas created natively, will be cleaned up.
* All resources created in the namespace that fall under constraints defined in the resource quota, would be validated against the quota. 
* If CPU/Memory request/limit is defined in the quota, all containers created in the corresponding namespace, need to have requested or/and limit values set https://kubernetes.io/docs/concepts/policy/resource-quotas/#requests-vs-limits

**Comment by alena1108** [comment]
backend is in, now need a UI

**Comment by deniseschannon** [comment]
@soumyalj this is now ready for testing through the API

**Comment by alena1108** [comment]
@soumyalj APIs are updated in master, and can be validated using our automation

**Comment by alena1108** [comment]
a note - storage quota `requests.ephemeral-storage` is not enabled as it's still in alpha feature in k8s. For storage we have `requests.storage` support

**Comment by soumyalj** [comment]
Tested with master from Sep 13. Resource quota is supported at the project level for memory, cpu, storage and is functional.  New issues are being filed related to this feature. Hence closing this issue.
