### ISSUE TITLE
Hardening initial setup

### ISSUE THREAD

**Issue by MarkMangoba** [rancher/rancher#13271]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0

Security concerns:
My colleague @RamJett and I are deploying Rancher as a possibility of deploying k8s in our org.  

We do have a security concern that the setup allows anyone to access the admin UI after the docker image is initially run.  We would like to request some hardening feature, whether its some way to use a bcrypt (or other secure method) to harden the initial setup process.

**Comment by cjellick** [comment]
Not sure if this would meet your needs, but you can script a password reset to occur after starting up the server:
```
$ docker run -d -p 80:80 -p 443:443 rancher/rancher
9f63a0e4d334aa569fb1dd6694c3c1a5a53e6177f1fbcd11a6dee31439d69725
$ docker exec 9f6 reset-password
New password for default admin user (user-grfcx):
dro5lbM-1bni6E6d8wct
```

**Comment by RamJett** [comment]
As a follow up on this. My scenario is that I'm deploy initially with some ansible playbooks. I used the option above from @cjellick to set a password and that is fine, but then the UI, first person to visit is asked to [Save URL] then let directly in still without a password. It would be nice to lock with the password, and not let it go further in the UI without that password.

**Comment by loganhz** [comment]
Please try https://github.com/rancher/rancher/issues/15477#issuecomment-419804309
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
