### ISSUE TITLE
IPSec Service constantly showing unhealthy containers

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#13272]
**Please make sure you read #13559 and #13176 before commenting on this issue, as that existing/fixed bug is being misidentified in this open issue.**

**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.19

**Infrastructure Stack versions:**
healthcheck: v0.3.6
ipsec: v0.13.11
network-services: v0.7.20
scheduler: v0.8.3

**Docker version: (`docker version`,`docker info` preferred)** 

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:10:31 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:10:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA Rancher External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Place about 50-60 hosts across 3 AWS regions such as North Virginia, Sydney, Germany, and Ireland, and put them under production load.

Add a new host to trigger an IPSec Reconcile

**Results:**

IPSec net:holder containers are constantly flapping between "Active" and "Unhealthy" when in a normal state.

When a new host is added, all of the IPSec net:holder containers fall to "Unhealthy" and causes the "Initializing" net:holder container on the new host to fail to stay up.

I suspect the issue comes from this hardcoded timeout of 1 second, which would be fine if I was in one region, however I'm not:

https://github.com/rancher/connectivity-check/blob/26dc5edb27437b80c5cbe3ee4731bddf3abaa2c7/utils/utils.go#L17

**Expected:**

IPSec net:holder containers should not flap health states under these conditions, should allow for a constant to be set to increase the desired timeout for IPSec connectivity checks.

**Comment by leodotcloud** [comment]
Related cattle changes: https://github.com/rancher/rancher/issues/13122

**Comment by ryanwalls** [comment]
@leodotcloud We are experiencing this as well on 1.6.17.  

![image](https://user-images.githubusercontent.com/842653/39718263-fe6e00be-51f2-11e8-8edb-891993bc6844.png)

**Comment by evertonpaiva** [comment]
Same issue here, version **1.6.16**.

![captura de tela de 2018-05-07 15-38-49](https://user-images.githubusercontent.com/378542/39718508-dfb6dc76-520c-11e8-8492-9138b1c7231e.png)

**Comment by schuylr** [comment]
@ryanwalls @evertonpaiva is this constant state or did this only happen during a host coming up? That looks like an issue with cross-host communication on UDP ports 500/4500, not to be confused with the issue I'm having.

**Comment by leodotcloud** [comment]
@evertonpaiva This issue is tracking the problem when a new host is added. Do you see the ipsec containers getting recreated? If it's just healthcheck becoming unhealthy, then it's a different issue.

**Comment by schuylr** [comment]
My issue is two-fold: when a new host is added and for when there are no new hosts being added, containers will randomly drop to Unhealthy and back to Healthy again (due to random timeouts or something else)

However, any constant state of Unhealthy for any one or all of the IPSec holder containers does not describe this particular issue. My best advice to solve a constant unhealthy state would be to check if any host has UDP ports 500/4500 blocked between other hosts, or a networking failure on one of the hosts due to OOM errors or the like.

**Comment by leodotcloud** [comment]
Thanks for your pointers @schuylr.

Also, @schuylr I have a fix for this issue, please ping me on Slack [https://slack.rancher.io] if you would like to try it out before the actual release is out.

**Comment by ryanwalls** [comment]
@leodotcloud We would like to try your solution if it is publicly available.  Our cluster running 1.6.17 is failing 2 or 3 times a week because ipsec stops working.  See #13559.

**Comment by schuylr** [comment]
@ryanwalls Go to the IPSec Infrastructure stack and upgrade the "IPSec" service. Under "Which Services", deselect "IPSec" and select "connectivity-check". Use this image: `rancher/net:v0.13.12` then click "Upgrade"

**Comment by tsublette** [comment]
@leodotcloud and @superseb this results in production being down for 10-15 minutes every time it happens. We are a cloud based simulation company where simulations can run for days in batch jobs. If steps in the simulation complete while in this state, they fail and customers could lose days of processing time. So... happy customers in jeopardy. Do you all have an estimate of when a release will be available with these fixes?  - Thanks

**Comment by ryanwalls** [comment]
Thanks @schuylr.  Did 0.13.12 fix your issue?

**Comment by schuylr** [comment]
For clarity, this is the issue I'm experiencing. The "Unhealthy" shows across IPSec containers randomly between checks, and I do **not see all IPSec containers showing Unhealthy all at once.**

![screenshot from 2018-05-24 09-33-01](https://user-images.githubusercontent.com/12628715/40488767-82416170-5f35-11e8-97e2-cae2d6db5672.png)

**Comment by ryanwalls** [comment]
Thanks @schuylr!

**Comment by schuylr** [comment]
Update with v1.6.18, with what seems to be an attempted fix at the above issue:

- I noticed that a new IPSec has been released with the `PEER_CONNECTION_TIMEOUT` and `CONNECTIVITY_CHECK_INTERVAL` environment vars per [this commit](https://github.com/rancher/connectivity-check/commit/b79cd284a1898083644f1ae7903a187fe9cfe0cc)

- I tried utilizing these environment variables with `5000` and `10000` as values, respectively. I've also tried `5000` and `5000`.

- When upgrading the connectivity container to `v0.13.13` with these environment variables, `curl localhost/connectivity` hangs indefinitely on the connectivity and `net:holder` containers.

- Therefore, **all** of the IPSec containers go to "Unhealthy"

Pinging @leodotcloud per his request in Slack

**Comment by sayhell** [comment]
Any update?

**Comment by bascht** [comment]
Any hints appreciated. Came here via #14221 but updating all the containers in the ipsec stack to v0.13.13 didn't make a difference: 
![screenshot-2018-06-30-025910-816x447](https://user-images.githubusercontent.com/51264/42119914-1d592bea-7c12-11e8-8ddf-4293f1d08396.png)

I don't see any segfaults in my log, so I think I can exclude both the other mentioned issues. 
Would more logs / debug info help out here? What keywords / metrics should I look for?

**Comment by JonathanParrilla** [comment]
I am having the same issue. IPSec works just fine if I launch a single host in an environment, but when I add another host or hosts, IPSec goes into an unhealthy state and stays there.

**Comment by joantune** [comment]
Same here - any idea how this can be solved? can we just downgrade the infrastructure and/or IPsec stack(s) to some version?

**Comment by leodotcloud** [comment]
I am working on this issue: `https://github.com/rancher/rancher/issues/13891` to remove the dependency of successful peer checks during upgrade.

**Comment by schuylr** [comment]
Can confirm that v1.6.20 solves this issue after upgrading the IPSec infra stack - closing!
