### ISSUE TITLE
Better guidance on configuring Azure Cloud Provider

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13274]
**Rancher versions:**
rancher/rancher: v2.0.0

Today it's a huge list with no clue what is required and what not. Maybe start with the required options and make an advanced section.

**Comment by JasonvanBrackel** [comment]
Here's the configuration information for the provider itself.
https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-provider-config.md

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/12

Descriptions have been added to Azure Cloud Provider fields.

However, only 
```
cloud
tenantId
aadClientId
aadClientSecret
subscriptionId
```

are required for the Azure cloud provider to work correctly when Rancher is provisioning the nodes. This should be noted on these fields.  @galal-hussein can you confirm?

**Comment by galal-hussein** [comment]
@bmdepesa from my testing, i can set up a cluster with Azure cloud provider with only these 4 parameters:
```
tenantId
aadClientId
aadClientSecret
subscriptionId
```

**Comment by westlywright** [comment]
I've added the four that @galal-hussein tested with as required fields, so they have the required filed asterisks now

**Comment by JasonvanBrackel** [comment]
aadClientSecret should be treated like a password.  It is in other parts of the system, but was not here as of 2.0.2

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/19

The four required fields are noted. Opened #14066 for aadClientSecret enhancement.
