### ISSUE TITLE
Minor UI bugs 'Ports' should be 'Environmental Variables' on Pod page

### ISSUE THREAD

**Issue by pjpritch** [rancher/rancher#13275]
Note that in this image (bottom), Ports appears twice.  The second section should read as 'Environmental Variables'

![image](https://user-images.githubusercontent.com/162036/39601369-aaea6528-4eef-11e8-9434-d3283051e7e7.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`container`|

**Comment by tfiduccia** [comment]
Version - v2.0.0
There are two ports sections in the Pod details page.  Looks like the second one is just mis-named Pod and should be environment variables.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/8
Verified fixed
