### ISSUE TITLE
AD - User unable to login with comma in name. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13280]
**Rancher versions:**
V2

Steps:
Enable AD Auth
Set Site Access to "Restrict Access to only Authorized Users and Organizations" 
Add a user that has a comma in their name (EX Name: Test, User).
Click Save.
Login as newly added users.

Results:
User is unable to login.

![screen shot 2018-05-03 at 2 40 48 pm](https://user-images.githubusercontent.com/38012481/39604207-fe6a81c0-4edf-11e8-9ee6-3e838ae21f2a.png)

**Comment by mrajashree** [comment]
Unable to reproduce. The password of that particular user must've changed.

**Comment by adingilloRancher** [comment]
Validated ability to login with user that contains comma.
