### ISSUE TITLE
2.0 UI, Add Secret. Requires namespace if you choose single, then switch back

### ISSUE THREAD

**Issue by JohnDavidLarsen** [rancher/rancher#13289]
**Rancher versions:**
rancher/rancher: 2.0.0

**Steps to Reproduce:**
Add Secret
Fill in Name
Choose "Available to a single namespace"
Choose "Available to all namespaces in this project"

Enter Key and Value, 
Choose Save

Error:  "Namespace" is required

This error doesn't show up if you leave it to "Available to all namespaces in this project" initially.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/8
Verified fixed
