### ISSUE TITLE
Missing instructions in cluster creation

### ISSUE THREAD

**Issue by edqallen** [rancher/rancher#13288]
*Describe your issue here*
When creating a vSphere cluster, The "Cluster Options" section contains the warning

>  "Using a cloud provider without passing a cloud provider config could cause your cluster to not provision correctly. It is recomendded that you add a cloud provider config before you create a cluster."

However, there is no indication on how to go about adding a "cloud provider config."

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.new`|

**Comment by superseb** [comment]
This is now covered: https://rancher.com/docs/rancher/v2.x/en/concepts/clusters/cloud-providers/
