### ISSUE TITLE
Owner of cluster sees all host options when attempting to edit a pre-existing cluster. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13284]
**Rancher versions:**
V2

Steps:
Create a new cluster.
Add AD authentication.
Assign AD user to cluster as an owner.
Login as added AD user.
Edit cluster.

Results:
Owner sees multiple host options after initially loading page.  
After selecting any host option, user can then see all cluster options to edit. 
User should not see host options. 

![screen shot 2018-05-03 at 3 26 38 pm](https://user-images.githubusercontent.com/38012481/39606392-0fad76a4-4eea-11e8-8921-c738bf32dcb0.png)

![screen shot 2018-05-03 at 3 26 44 pm](https://user-images.githubusercontent.com/38012481/39606396-12780692-4eea-11e8-8dac-0bf8181a773a.png)

**Comment by loganhz** [comment]
Root cause is the same with https://github.com/rancher/rancher/issues/12038

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/12038
