### ISSUE TITLE
For Pipelines, index.docker.io is not an option in the Registry drop-down so I lose that if click on it 

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13286]
**Rancher versions:** 2.0 master 5/3

**Steps to Reproduce:**
1.  Create a pipeline
2.  Click on Publish step
3.  Click on drop-down for Repository

**Results:**  Only Custom in there, and the index.docker.io options is not.  So I lose if I click on Custom and cannot get it back.  Also if Custom & index.docker.io are options.  The Custom option should not be in parens (Custom).  If index.docker.io (Custom) is the only option, it should not be a drop-down at all.

![image](https://user-images.githubusercontent.com/11514927/39608447-6c361d3e-4ef6-11e8-8090-c1fdf8ad81fe.png)

**Comment by biblesyme** [comment]
@tfiduccia This is just a placeholder there if you don't actually create the registry. You don't need to select it.

**Comment by tfiduccia** [comment]
Version - 2.0 master 6/25
Verified fixed

**Comment by tfiduccia** [comment]
@biblesyme - The options should be there all the time in the drop-down.  Since you have made it a default, when I click on the drop-down, I expect to see it there and selected.

**Comment by deniseschannon** [comment]
@gitlawr @loganhz is this still a valid use case with the new refactored pipeline?

**Comment by loganhz** [comment]
Close it as it is not an issue in new pipeline
