### ISSUE TITLE
Make Repository the default field when I get into Add Pipeline

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13287]
**Rancher versions:** 2.0 master 5/3

**Steps to Reproduce:**
1. Go to Add Pipeline

**Results:**  Make Repository the default field, so when I get in my cursor is already in this field.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/10
Not fixed.  My cursor is not automatically going to Repository field when I click on Add Pipeline

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/12

The repositories field is the default field with cursor focused on page load.
