### ISSUE TITLE
Learn More links go to Navigation section instead of documentation section

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1328]
v0.25.0-rc2
Steps:
1.  Create new environment
2.  Switch to that environment
3.  Click on Learn more links

Results:
The links take to the navigation section and looks like it takes me to same place.  I have to scroll down to bottom to see the actual help text.

Expected:
Should actually go to associated help text.  So either it should drop down or maybe the navigation section should be removed so you are taken directly to text that is associated to link.

**Comment by deniseschannon** [comment]
Yep, this is a known issue after moving from having the docs from github to rancher. I believe @vincent99 has made the fix in the UI and just needs to go into a release.

**Comment by tfiduccia** [comment]
v0.27.0-rc1 (ui latest v0.32.0)
Navigation fixed
