### ISSUE TITLE
Rancher CLI ignores upgrade_strategy in rancher-compose.yml

### ISSUE THREAD

**Issue by ThomasDonath** [rancher/rancher#13295]
We want to use the in-service-upgrade strategy and stop the old container after successfully launched new one.
Found in doc (https://rancher.com/docs/rancher/latest/en/cattle/upgrading/) "Starting New Containers Before Stopping Old Containers" and tried. 
But as we use rancher instead of rancher-compose it doesnt work.

Is it a bug or a missing feature? When will rancher cli support this option?

Thanks in advance, best regards
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`openldap` |
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by ThomasDonath** [comment]
is already filed in#9144

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
