### ISSUE TITLE
Navigation section doesn't work after going to documentation from Learn more page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1329]
v0.25.0-rc1
Steps:
1.  Create new environment
2.  Switch to that environment
3.  Click on Learn More link for host or services from Welcome page
4.  Click on any Navigation link on documents page

Results:
Nothing happens, it just stays on the Adding you host or Adding your Services page.

Expectation:
If Navigation links to other pages are there, they should work.

**Comment by deniseschannon** [comment]
@vincent99 The links need to be redirected to rancher.docs.rancher.com/xxx/xxx. In v0.26.0-rc1, it's still referring to github.

**Comment by vincent99** [comment]
ah ok.. yeah that's in this week's release

**Comment by tfiduccia** [comment]
Links are redirected and navigation is working
