### ISSUE TITLE
Upgrade RKE to use the latest ingress-nginx 1.16.x

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#13294]
We should upgrade RKE ingress-nginx image to the latest release: https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.14.0

**Comment by orangedeng** [comment]
https://github.com/rancher/ingress-nginx has new tag `nginx-0.14.0-rancher1`

**Comment by orangedeng** [comment]
New Ingress tag for us is nginx-0.16.2-rancher1. @deniseschannon Could you help to create and push the new docker image for this tag in https://github.com/rancher/ingress-nginx? And I can have someone to review my types PR https://github.com/rancher/types/pull/418.

**Comment by alena1108** [comment]
We had to revert the fix for this issue due to https://github.com/rancher/rancher/issues/14660. The revert pr: https://github.com/rancher/types/pull/513.

**Comment by deniseschannon** [comment]
The build for the previous image wasn't built correctly. Please re-run validation to confirm that ingress is not having any issues.

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/25

Automation tests for ingress all passed.
