### ISSUE TITLE
emptyDir volumes Not added to initContainer from GUI

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#13290]
**Rancher versions:**
rancher/rancher: v2.0.0

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher 2.0 aws k8s cluster,
tested with single node, 2 nodes and 3 nodes, the result was the same on each

**Steps to Reproduce:**
1. add a new cluster (we used aws)
1. Deploy nginx to default namespace
1. Add emptDir volume to deployment, with mount path to /tmp
1. Add sidecar using alpine image 
1. select initContainer for the sidecar
1. add volume using existing vol1 created when deploying nginx
1. add mountPath of /tmp
1. add `touch /tmp/test.txt` as command in initContainer
1. exec shell into nginx container, `cd /tmp` then `ls` observe there is no test.txt
1. click edit Yaml option, observe that the volumeMount is missing from the initContainer node in the yaml

**Results:**
This is the resulting yaml: [bug_report.txt](https://github.com/rancher/rancher/files/1973163/bug_report.txt)

This is the expected result: [expected_result.txt](https://github.com/rancher/rancher/files/1973176/expected_result.txt)

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Verified fixed
