### ISSUE TITLE
the project authority management question 

### ISSUE THREAD

**Issue by huangyanhong** [rancher/rancher#13293]
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

docker 17 

centos 7.3 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

single node rancher 

Kubernetes 1.8.4

**Steps to Reproduce:**

1 new user developer 
2 add developer k8s-cluster  
Name | Role |   |  
-- | -- | -- | --
admin | cluster-owner |  
developer2 | cluster-member |  
developer1 | cluster-member |  
developer | cluster-member

3  add developer project owner

Default Admin ( admin )本地用户 | Project Owner | Yesterday at 2:58 PM |  
-- | -- | -- | --
  | developer ( developer )本地用户 | Project Owner | 1:41

4 developer enter rancher 
 enter dev-test project 
deploy app OK，first day 

but the second day when I enter dev-test project 
deploy app not OK. show errors below：
deployments.apps is forbidden: User "u-hxf6r" cannot create deployments.apps in the namespace "dev-test": clusterrole.rbac.authorization.k8s.io "p-87xb9-namespaces-edit" not found  

--

**Results:**
delete the developer in the cluster and project ,then add the user developer in the cluster and project again ,will can deploy app ok

**Comment by loganhz** [comment]
Hi @huangyanhong, I can not reproduce your issue. It should be working in latest version. Can you try v2.0.4, please?

**Comment by loganhz** [comment]
Please feel free to re-open it if you still see this issue.

**Comment by huangyanhong** [comment]
rancher 2.20 have the same questions
