### ISSUE TITLE
Active directory search while adding members is slow due to "contains" search 

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#13300]
**Rancher versions:**
rancher/master

After AD is configured, when adding a member to a cluster, ldap queries having the filter `(sAMAccountName=*username*)` are sent.
Because of this 'contains' search, some ldap queries take a long time (~1.5 minutes) to return.
Meanwhile in the UI there are no users listed, making it look like adding members isn't working.
When the same query is tried with "begins with" search instead of "contains", it returns within seconds.
So the search query can be modified to search for entries that begin with the 'username'.

Also adding filters on last name and first name

**Comment by mrajashree** [comment]
@sangeethah As a part of the fix, all user and group attributes under Customize schema, that have a default value, are now required

**Comment by sangeethah** [comment]
@adingilloRancher When validating this fix , please add new test cases for this search feature to existing test plan.

**Comment by adingilloRancher** [comment]
Unable to authenticate AD. Internal server error:

2018/05/09 17:38:45 [ERROR] API error response 500 for POST /v3/activeDirectoryConfigs/activedirectory?action=testAndApply. Cause: server returned error for search dc=tad,dc=rancher,dc=io (&(objectClass=group)(|(distinguishedName=CN=subgroup1,OU=Groups,DC=tad,DC=rancher,DC=io)(distinguishedName=CN=group\, name,CN=Users,DC=tad,DC=rancher,DC=io)(distinguishedName=CN=CN-ITS-EP-ITx-021-SCMApprovers,OU=Security,OU=IDM,OU=Groups,DC=tad,DC=rancher,DC=io)(distinguishedName=CN=testgroup1,CN=Users,DC=tad,DC=rancher,DC=io))): LDAP Result Code 201 "": ldap: invalid characters for escape in filter: LDAP Result Code 201 "": ldap: invalid characters for escape in filter

**Comment by adingilloRancher** [comment]
Validate ability to search for users with "begins" instead of "contains".
Performed search by account name.
Performed search by first name.
Performed search by last name.
Validated ability to search for users by all three methods on cluster/project/site levels.
