### ISSUE TITLE
Cluster creation procedure for Azure does not create NSG

### ISSUE THREAD

**Issue by TimBobkov** [rancher/rancher#13309]
**Rancher versions:**
rancher/rancher: 2.0.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu Server 16.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher 2.0

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create Azure cluster (without using AKS) in new resource group.
1. Add service with type "LoadBalancer".
1. Wait till load balancer ant external IP are created in Azure.
1. Try to access service through external IP.

**Results:**
When cluster is deployed there is no Network Security Group (even if you set it in cluster config). Without this NSG services can't obtain external IPs. After manual creating of NSG service obtain external IP very fast. So please add creating of NSG to deploy script for Azure.

**Comment by TimBobkov** [comment]
Additional investigation result that I can't access services through LoadBalancer because each VM has it own NSG. So until I change NSG for each VM manually the LoadBalancer not work properly.

**Comment by loganhz** [comment]
Please try to config cloud provider in Cluster Options https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/azure/

![image](https://user-images.githubusercontent.com/21168270/47263794-f29d1380-d53a-11e8-88a5-eb2a2f96e0e5.png)
