### ISSUE TITLE
Rancher Logging does not take custom Docker root dir into account

### ISSUE THREAD

**Issue by smiller393** [rancher/rancher#13304]
Due to server storage restrictions, my team needs to store anything large on our servers in `/app`, including the docker installation and `/var/log` directories, and then symlink to them from the original location. This seems to cause issues when enabling cluster logging in rancher. I dug into the issue, and saw the following logs for the fluentd container on my agent for each of my containers:

1: `2018-05-04 19:51:34 +0000 [warn]: #0 /var/lib/rancher/rke/log/kubelet_2512018f1c0e124fe6356cb915db9973ec5e24f2a0e77536274f661d9335706c.log unreadable. It is excluded and would be examined next time.`

AND

2: `2018-05-04 20:09:10 +0000 [warn]: #0 /var/log/containers/redis-7bd4689f65-q8w7r_default_redis-6272889bf0dfdc2609c1d05a8fd53115fc4352e6fbfb9409f343488889422759.log unreadable. It is excluded and would be examined next time.`

After seeing this I went into the container and dug down to see why it was not able to read the file. For example 2 above, the end symlink was trying to point to `/app/docker/containers`.... (the correct location on my host of the docker install/log location). The issue with this is that `/app/docker/containers` is not bind mounted for the fluentd container, only `/var/lib/docker` is bind mounted.

My proposed fix is to add the docker root dir, found from running `docker info`, as a bind mount when spinning up the fluentd container. 

Thoughts?

**Rancher versions:**
2.0.0

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10

**Docker version: (`docker version`,`docker info` preferred)**
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single server with 3 agents on a single cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8

**Steps to Reproduce:**
on your agent: 
- Install docker
- move the docker installation to another dir 
- sym link /var/lib/docker to your new location
- start rancher agent as normal on that machine and add it to your cluster
- configure cluster logging in rancher UI to send to a valid kafka endpoint (other methods may work as well not sure if this matters)
- view logs of fluentd container started on the agent 

**Results:**

**Comment by adingilloRancher** [comment]
Attempted with new build, v2.0.3-rc1. Associated error messages are still present. 

Followed repo steps:
Install docker
move the docker installation to another dir
sym link /var/lib/docker to your new location
start rancher agent as normal on that machine and add it to your cluster
configure cluster logging in rancher UI to send to a valid kafka endpoint (other methods may work as well not sure if this matters)
view logs of fluentd container started on the agent

<img width="1656" alt="screen shot 2018-06-20 at 2 23 30 pm" src="https://user-images.githubusercontent.com/38012481/41685615-dd182c4e-7495-11e8-9c4f-84a4c08fe6fe.png">

**Comment by jiuchongxiao** [comment]
i have the same issue.

my fluentd container had the warn.
2018-06-22 06:58:46 +0000 [warn]: #0 /var/log/containers/fluentd-whpx4_cattle-logging_fluentd-c913ecb0b58544438444c39aa1e8b64c39862abd97a0eb6ffb6354d3e8e86209.log unreadable. It is excluded and would be examined next time

i think it is the start rancher user has no privilege to read and write the director, so i use root user give the privilege to the common user, but it did not work.


i update my docker container position when i started it (--graph=/ultrapower/docker).the detail as below
![image](https://user-images.githubusercontent.com/13093730/41766945-ef86af08-763a-11e8-8a79-a854a244721a.png)

did it because my update docker position? how to sove it?

@adingilloRancher i have the same issue, did you solve it ?

**Comment by adingilloRancher** [comment]
Master 8/2

Attempted steps to reproduce again.
Did not see associated errors in logging.
Validated kafka logging was seen as expected.

**Comment by huangxu-finogeeks** [comment]
Hi, Is this problem solved? I've found this problem too, and I have set my docker root dir to /mnt/data/docker, but i can't still see my logs in ES, the ES is running normally , and rancher UI shows saved, i can't see any error in rancher UI. How can I fix it? my rancher version is 2.0.8. It seems that you have add a new parameter in rancher UI？Which version? I can't see it in 2.0.8. Thanks

**Comment by Kralor-Guldan** [comment]
This issue should not be closed, when /var/lib/docker is symlinked, it breaks logging.

**Comment by deniseschannon** [comment]
@Kralor-Guldan can you make a new issue instead of commenting on this one?

**Comment by matthax** [comment]
@evannorstrand and @deniseschannon I've filed a new issue to reflect the most up-to-date information on the issue. I also see #20494 which may be related had a suggestion to check that the dockerRoot was set and I did confirm the value was taken into account as part of the configuration.
