### ISSUE TITLE
Provisioning stuck on  Failed to apply the ServiceAccount needed for job execution

### ISSUE THREAD

**Issue by pythiancastaneda** [rancher/rancher#13307]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/rancher
rancher/agent or rancher/rancher-agent: rancher/rancher-agent:v2.0.0 

I am trying to deploy a single node cluster on premises using a Rancher server hosted in AWS. The provisioning of the cluster fails with the following error: 

Failed to apply the ServiceAccount needed for job execution: Post https://187.232.x.x:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: net/http: TLS handshake timeout

**Infrastructure Stack versions:**

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 and RancherOS 1.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Rancher server - AWS
Cluster - on premises
**Steps to Reproduce:**

Execute the docker snippet to deploy the server:
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.0 --server https://18.232.94.x --token 5fs69bzft9nlzgx75b2kmw5kx94nlsvs9nxq7v58rjzscxhredactedr --ca-checksum 4985b87b817d5ecb3844bbf8cf7e2c7e7a09c6f0f5da8eeaa2eredactedefcdc8 --address 187.232.x.x --internal-address 192.168.1.166 --etcd --controlplane --worker

**Results:**
The on premises cluster never is provisioned. 

Some of the logs on the kube-apiserver container
```
I0505 05:45:15.556691       1 trace.go:76] Trace[1199782090]: "Get /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/system::leader-locking-kube-controller-manager" (started: 2018-05-05 05:45:15.018490716 +0000 UTC m=+8.419104775) (total time: 538.157123ms):
Trace[1199782090]: [538.157123ms] [538.152762ms] END
I0505 05:45:15.674750       1 storage_rbac.go:249] created role.rbac.authorization.k8s.io/system::leader-locking-kube-controller-manager in kube-system
I0505 05:45:16.165374       1 storage_rbac.go:249] created role.rbac.authorization.k8s.io/system::leader-locking-kube-scheduler in kube-system
I0505 05:45:16.617579       1 storage_rbac.go:249] created role.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public
I0505 05:45:17.063821       1 controller.go:537] quota admission added evaluator for: {rbac.authorization.k8s.io rolebindings}
I0505 05:45:17.066296       1 storage_rbac.go:279] created rolebinding.rbac.authorization.k8s.io/system::leader-locking-kube-controller-manager in kube-system
I0505 05:45:17.438543       1 storage_rbac.go:279] created rolebinding.rbac.authorization.k8s.io/system::leader-locking-kube-scheduler in kube-system
I0505 05:45:17.965526       1 storage_rbac.go:279] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-system
I0505 05:45:18.441277       1 storage_rbac.go:279] created rolebinding.rbac.authorization.k8s.io/system:controller:cloud-provider in kube-system
I0505 05:45:18.446237       1 storage_rbac.go:279] created rolebinding.rbac.authorization.k8s.io/system:controller:token-cleaner in kube-system
I0505 05:45:18.451549       1 storage_rbac.go:279] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public
I0505 05:45:24.687453       1 controller.go:537] quota admission added evaluator for: { serviceaccounts}
I0505 05:45:25.341834       1 trace.go:76] Trace[1926197334]: "GuaranteedUpdate etcd3: *core.ServiceAccount" (started: 2018-05-05 05:45:24.74643099 +0000 UTC m=+18.147045043) (total time: 595.37626ms):
Trace[1926197334]: [595.331553ms] [595.099876ms] Transaction committed
I0505 05:45:25.341999       1 trace.go:76] Trace[237232291]: "Update /api/v1/namespaces/kube-system/serviceaccounts/namespace-controller" (started: 2018-05-05 05:45:24.74636641 +0000 UTC m=+18.146980470) (total time: 595.614916ms):
Trace[237232291]: [595.547642ms] [595.506414ms] Object stored in database
I0505 05:45:25.343200       1 trace.go:76] Trace[1537699932]: "Get /api/v1/namespaces/kube-system/secrets/namespace-controller-token-7x2m5" (started: 2018-05-05 05:45:24.747595302 +0000 UTC m=+18.148209354) (total time: 595.588036ms):
Trace[1537699932]: [595.554631ms] [595.550255ms] About to write a response
I0505 05:45:25.344821       1 trace.go:76] Trace[2049848883]: "Create /apis/authentication.k8s.io/v1/tokenreviews" (started: 2018-05-05 05:45:24.745619873 +0000 UTC m=+18.146233924) (total time: 599.187625ms):
Trace[2049848883]: [599.027484ms] [598.910805ms] Object stored in database
I0505 05:48:43.996342       1 logs.go:49] http: TLS handshake error from 192.168.1.166:36771: EOF
```

**Comment by garjunan** [comment]
+1 i am also facing same issue on Google Cloud when i use as custom VM.

**Comment by kdealer** [comment]
Whats the state of this bug?

**Comment by superseb** [comment]
Two cases where I have seen this is:

- Cluster nodes are re-used and not cleaned, leaving old files which interfere with the cluster provisioning process. Proper cleaning of nodes is described here: https://rancher.com/docs/rancher/v2.x/en/faq/cleaning-cluster-nodes/
- There is a network configuration which is preventing the cluster creation to complete. First, the ports need to be opened according to https://rancher.com/docs/rancher/v2.x/en/installation/references/. (in this case, especially 6443). Or there is a proxy present and it needs to configured accordingly.

If there is a scenario that I can run to reproduce the bug, please describe it in a comment.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
