### ISSUE TITLE
Rancher 2 on CoreOs

### ISSUE THREAD

**Issue by sinqinc** [rancher/rancher#13301]
We are currently using Rancher on a CoreOs cluster. We would like to know if Rancher 2 is still working on CoreOs ?

thank you

**Comment by tahoward** [comment]
I'm running Rancher 2.0 on CoreOS without too much difficulty:
```
    - name: rancher.service
      enable: true
      contents: |
        [Unit]
        Description=Rancher service for docker management
        After=docker.service
        After=srv-docker-rancher.mount
        Requires=docker.service
        Requires=srv-docker-rancher.mount
        
        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStartPre=-/usr/bin/docker kill rancher
        ExecStartPre=-/usr/bin/docker rm rancher
        ExecStartPre=/usr/bin/docker pull rancher/server:preview
        ExecStart=/usr/bin/docker run -d --restart=unless-stopped --name rancher -p 8080:80 -p 8443:443 -v /srv/docker/rancher/server:/var/lib/rancher rancher/server:preview
        ExecStartPost=/usr/bin/bash /etc/rancher/agent-launch.sh
        ExecStop=/usr/bin/docker stop -t 2 rancher
        
        [Install]
        WantedBy=multi-user.target
```

Preferably, systemd unit would not launch instance in daemon mode. However, there appears to be bad exit code on `stop` that puts the service in a irrecoverable state until restarting docker. Daemon mode appears to work around the issue. Not sure if this is isolated to Rancher 2.0.

**Comment by alexandrem** [comment]
Perhaps it was the original question intent, but I was also wondering if rancher v2 can provision coreos nodes to create cluster (master  and worker nodes).

Something I have yet to try out. Curious to hear about others doing this.

**Comment by tahoward** [comment]
I'd think the answer is yes. I currently run rancher server on CoreOS and bootstrap the node it's running on as a compute node in a cluster running all three kubernetes roles for my lab.

**Comment by sinqinc** [comment]
Thanks @tahoward .I will check it Out. I hope to have an official support since I will not take any chance in our production cluster.

**Comment by superseb** [comment]
Supported OS are: 
Ubuntu 16.04 (64-bit)
Red Hat Enterprise Linux 7.5 (64-bit)
RancherOS 1.4.0 (64-bit)

Any OS with Docker should work fine though, you can always reach out for options with support.
