### ISSUE TITLE
Cannot create volume claim using storage class with AKS cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13305]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0

**Steps to Reproduce:**
1. Create Azure container service cluster 
2. Create a storage class with azure disk
3. Use the storage class and create volume claim 

The volume claim is stuck in pending state
![screen shot 2018-05-04 at 1 57 27 pm](https://user-images.githubusercontent.com/18536626/39652628-1b709250-4fa3-11e8-9f72-929c47381648.png)

**Comment by nathan-jenan-rancher** [comment]
Was only able to reproduce under these specific circumstances.
1) Create an AKS cluster via the azure portal
2) import the cluster into rancher
3) create a storage class with a `shared` type 
4) create a persistent volume claim with that storage class
5) claim will remain pending forever and not become bound

**Comment by cjellick** [comment]
Based on @nathan-jenan-rancher's assessment that this only occurs in one specific scenario and knowing other flakiness issues we've hit in AKS, moving out of the release.

**Comment by emmanuelcini** [comment]
anyone know of a fix for this?
