### ISSUE TITLE
DNS inside container not resolving rancher 2.0

### ISSUE THREAD

**Issue by thdxr** [rancher/rancher#13306]
I'm using Rancher 2.0 and installed on a baremetal host.  Any containers I launch via Rancher cannot resolve DNS.  Any containers I launch straight through docker are fine. Any ideas?

**Comment by thdxr** [comment]
This was eventually solved by a combination of setting docker daemon.json and /etc/resolv.conf to point to Google DNS

**Comment by courcelm** [comment]
I also have DNS issue on bare metal hosts with Ubuntu server 16.04 LTS. In my case, it can resolve intermittently. If I do an apt-get update, the same hostname can succeed and fail. @thdxr Did you had intermittent issues?

**Comment by useafterfree** [comment]
I had a similar issue, got the resolver fixed, but I had to force Ipv4 to my Dockerfile (my LAN blocks IPv6):

```
ENV IPV4="-o Acquire::ForceIPv4=true"
RUN apt-get $IPV4 update
```

**Comment by superseb** [comment]
Please open a new issue with info on your setup if you still encounter problems.
