### ISSUE TITLE
Can't use NFS as persistent storage

### ISSUE THREAD

**Issue by rpelissi** [rancher/rancher#13319]
Hi,
I am trying to use an NFS share for persistent storage. I have make sure it is writable and accessible. But everytime I deploy a workload using the volume, I got this error message:

I0506 18:07:22.164449       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"labms", Name:"emby", UID:"60e24e20-5138-11e8-a46b-bac507c4c848", APIVersion:"v1", ResourceVersion:"127960", FieldPath:""}): type: 'Warning' reason: 'VolumeMismatch' Cannot bind to requested volume "embyvol01": incompatible accessMode

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.storage.persistent-volumes.index`|

**Comment by loganhz** [comment]
This UI issue has been fixed. Please try `rancher/rancher:v2.0.4`
