### ISSUE TITLE
Support adding containers to LB Service

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1331]
Current LB service only allows other services are targets.  We should be able to allow "normal" containers to be targets as well.

* We can support directly linking to a container.
* We can support auto converting a container to a service before linking.

If we support the second case, we should support being able to adding a container directly to a service.

**Comment by alena1108** [comment]
@will-chan support for selectors should add this functionality, slightly indirectly though. If LB service has Web service as a target, standalone instance can register itself to the web service, which will in turn add it to list of targets on LB.

**Comment by alena1108** [comment]
Also there is a way to register container to the LB by wrapping the container ip to the external service, and linking this service to the load balancer.

**Comment by alena1108** [comment]
@will-chan resolving based on the discussion with you and @ibuildthecloud - one of 2 workarounds above should be sufficient to solve the use case.
