### ISSUE TITLE
Can't remove persistent storage

### ISSUE THREAD

**Issue by rpelissi** [rancher/rancher#13318]
I have a NFS persistent storage that was once assigned to a work flow. I have remove it from the workflow and re deploy it without the volume. Now when I try to remove the persistent storage I can't and this message in the logs:

I0506 18:33:51.232021       1 graph_builder.go:570] add [v1/PersistentVolume, namespace: , name: embyvol01, uid: 1cba9170-5076-11e8-a46b-bac507c4c848] to the attemptToDelete, because it's waiting for its dependents to be deleted

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.storage.persistent-volumes.index`|

**Comment by loganhz** [comment]
Now UI doesn't allow to remove PV with `Bound` state. You need to remove the PVC first. You can find the PVC in workloads ==> volumes tab.

![image](https://user-images.githubusercontent.com/21168270/43381607-c2f24c82-9407-11e8-8452-c3860ebdc768.png)
