### ISSUE TITLE
Controller Manager & Scheduler unhealthy

### ISSUE THREAD

**Issue by mholttech** [rancher/rancher#13311]
**Rancher versions:**
Rancher v2.0

**Infrastructure Stack versions:**
kubernetes: 1.10.2

**Docker version:** 
17.12.1-ce

**Operating system and kernel:**
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS deployed using BootKube via https://github.com/poseidon/typhoon/

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Install Rancher 2.0 on top of this deployed kubernetes and go to the Clusters Tab

**Results:**
Controller Manager & Scheduler show as unhealthy.

When running ``kubectl get cs`` it returns:
````
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused
etcd-1               Healthy     {"health":"true"}
etcd-0               Healthy     {"health":"true"}
etcd-2               Healthy     {"health":"true"}
````

When running ``kubectl get pods -n kube-system`` it shows that the scheduler and controller-manager pods are in a running state.

When running ``kubectl describe pods -n kube-system kube-controller-manager-xxx-xxx`` everything also shows as running.

This appears to be an incompatibility with ``kubectl get cs`` and the way that BootKube is deploying the services.  This has been discussed in kubernetes upstream for a few years now at https://github.com/kubernetes/kubernetes/issues/19570 but there doesn't seem to be a fix or workaround for it.

Based on my initial testing Rancher still appears to be working properly on top of this despite the "failed" healthchecks.  Perhaps another method of checking the health of these services needs to be considered to work around this known issue.

**Comment by advancingu** [comment]
Also seeing this behavior with nodes created by Rancher on AWS EC2 using current stable RancherOS AMI.

**Comment by thbiela** [comment]
I have also this issue with nodes created at hetzner. Are there any news?

**Comment by superseb** [comment]
The issue mentioned here is that certain setups (mentioned BootKube but also AKS has this issue) don't show the correct health for components through componentstatuses endpoint.

There is no functional impact, only the status is not according reality. If you see issues with your custom cluster or cluster created via Rancher which is not AKS, file a new issue with the steps to reproduce.

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/11496
