### ISSUE TITLE
Global permissions for new LDAP/AD users

### ISSUE THREAD

**Issue by hameno** [rancher/rancher#13326]
**Rancher versions:**
rancher/rancher: 2.0.0

It is currently not possible to specify the global permissions for new LDAP/AD users. We need to be able to specify the roles for new users.

Can we also hide global sections where users have no access to? Like settings, users, node drivers etc? Especially users should never be shown to unprivileged users.

**Comment by tfiduccia** [comment]
@hameno - To specify global permission, after the user has logged in you can go to Users and edit their account to have global.

There is a plan to hide menu items that users don't have access to in the future.

**Comment by hameno** [comment]
Yes, but I would need to do that for every user, I'd rather spend my time with fun stuff :)

**Comment by cjellick** [comment]
@hameno just curious: what global permission would you want to give to users by default?

**Comment by hameno** [comment]
@cjellick Just Login access, we don't want everyone to be able to create clusters.

**Comment by cjellick** [comment]
Makes sense. Making that default role configurable is definitely on our list of sooner-than-later todos

**Comment by deniseschannon** [comment]
Closing in favor of the issue that allows you to configure the default user role: https://github.com/rancher/rancher/issues/12737
