### ISSUE TITLE
workload app icon link failed

### ISSUE THREAD

**Issue by LGTH** [rancher/rancher#13324]
*Describe your issue here*
When I used Kubernetes to deploy nginx sucessful, then back to the workloads ui page( Group by Namespace/workload), I click the Nginx icon link，I want to look the container info, but the result is the 
 page's main area is blank, and click other navigation bar , there is no response.
I look the rancher-server:v2.0.0-beta4 logs, use command  `docker logs -f contrain-id`, there has no another messages when I did it above, What is the problem?Someone can help?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta4` UI: `v2.0.38` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by loganhz** [comment]
Hi, @LGTH 
I can not reproduce this issue. 
Can you try again on `rancher/rancher:v2.0.0`, please?
If you can reproduce it, can you provide the chrome console as well?
Thanks

**Comment by LGTH** [comment]
I try to reproduce it  in chrome version: 66.0.3359.139  - 64bit ,  and my os is win10x64
When I open the chrome console, it shows message error below:
`Socket connecting (id=1, url=wss://192.168.109.130/v3/subscribe...)
socket.js:233 Socket opened (state=connecting, id=1)
subscribe.js:267 Cluster Subscribe connected (sockId=1)
missing-message.js:13 Translation not found: locale='zh-hans', key='modalWechat.wechat'.
e.default @ missing-message.js:13
extend-ember-route.js:37 Set previous route to global-admin.clusters.index Array(0)
socket.js:60 Socket connecting (id=2, url=wss://192.168.109.130/v3/clusters/c-pwczm/subscribe...)
socket.js:60 Socket connecting (id=3, url=wss://192.168.109.130/v3/projects/c-pwczm:project-8lqp2/subscribe...)
socket.js:233 Socket opened (state=connecting, id=2)
subscribe.js:267  Subscribe connected (sockId=2)
socket.js:233 Socket opened (state=connecting, id=3)
subscribe.js:267 Project Subscribe connected (sockId=3)
extend-ember-route.js:37 Set previous route to global-admin.clusters.index Array(0)
extend-ember-route.js:37 Set previous route to global-admin.clusters.index Array(0)
extend-ember-route.js:37 Set previous route to global-admin.clusters.index Array(0)
extend-ember-route.js:37 Set previous route to containers.index ["c-pwczm:project-8lqp2"]
core.js:41 Uncaught Error: The intl string context variable 'type' was not provided to the string '{type}: {name}'
    at a.format (core.js:41)
    at a.format (format-message.js:22)
    at a.formatMessage (intl.js:84)
    at a.format (t.js:74)
    at a.compute (-format-base.js:92)
    at n.compute (references.js:336)
    at n.value (references.js:38)
    at t.compute (reference.js:323)
    at t.e.value (reference.js:292)
    at e.initialize (reference.js:369)`

But, I find that  the chrome that visit other rancher-server host(not the above host) is ok .

**Comment by loganhz** [comment]
@LGTH Thanks. The log is very helpful.  It's a translation issue.

This issue has been fixed in https://github.com/rancher/ui/commit/da262abb3306faa211b718dcd41a98d08f81c35f.

https://github.com/rancher/ui/blob/master/translations/zh-hans.yaml#L1066
