### ISSUE TITLE
“Host Aliases” not work in Rancher 2.0

### ISSUE THREAD

**Issue by k4124k** [rancher/rancher#13328]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.0
rancher/agent or rancher/rancher-agent:v2.0.0

**Infrastructure Stack versions:**
healthcheck:OK
ipsec:OK
network-services:OK
scheduler:OK
kubernetes (if applicable):OK

**Docker version: (`docker version`,`docker info` preferred)**
1.13.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.4 
3.10.0-693.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Esxi
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes v1.10.1-rancher2
**Steps to Reproduce:**
1.login
2.Deploy Workload
3.Networking
    Add Host Aliases ,eg:
<img width="1367" alt="qq20180507-153611 2x" src="https://user-images.githubusercontent.com/970355/39690407-91f3da5c-520c-11e8-8650-c57b5709b88a.png">
4. Launch

**Results:**
"Host Aliases" not add!
<img width="1392" alt="qq20180507-153927 2x" src="https://user-images.githubusercontent.com/970355/39690486-e054c670-520c-11e8-9955-322470b48c86.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/8
Verified fixed
