### ISSUE TITLE
Fix Openstack cloud provider integration

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13338]
The latest version of RKE generates a bad cloud config file for Kubernetes which blocks creation of clusters when defined in the cluster yaml.

The generated config is named `cloud-config.json` with a json format, but Kubernetes openstack provider expects a text INI config.

Rancher server latest version is also impacted. It's impossible to deploy a cluster when a user defines the openstack cloud provider key/value variables.

I believe the work to fix this can be summarized as:

- [ ] Add fix in RKE to generate correct cloud.conf when provider name is "openstack"
- [ ] Bump the RKE docker image

I'm not sure if there are any other missing obvious steps.

**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0-beta4 or latest "preview"
rancher/rke: 0.1.6

**Related Issues**

#13115

**Comment by superseb** [comment]
Not completely following why we need another issue besides https://github.com/rancher/rancher/issues/13115 ?

Thinking about implementation, I would say making the output type configurable and let people configure the output needer for their cloudprovider. But @galal-hussein already had ideas on this I believe?

**Comment by superseb** [comment]
Ok I think we can use #13115 to track this, I don't see any added value for this issue at the moment. Let me know if you think I'm wrong.
