### ISSUE TITLE
Add options for vSphere node template

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13347]
**Rancher versions:**
rancher/rancher: v2.0.0

```
EnvVar: "VSPHERE_CFGPARAM",
Name:   "vmwarevsphere-cfgparam",
Usage:  "vSphere vm configuration parameters (used for guestinfo)",
```

```
EnvVar: "VSPHERE_CLOUDINIT",
Name:   "vmwarevsphere-cloudinit",
Usage:  "vSphere cloud-init url to set in the guestinfo",
```

```
EnvVar: "VSPHERE_FOLDER",
Name:   "vmwarevsphere-folder",
Usage:  "vSphere folder for the docker VM. This folder must already exist in the datacenter.",
```

```
--vmwarevsphere-cloudinit http://my_host/cloud-config.yml
--vmwarevsphere-cfgparam "guestinfo.hostname=myrancherhost"
--vmwarevsphere-cfgparam "guestinfo.interface.0.name=eth0"
--vmwarevsphere-cfgparam "guestinfo.interface.0.ip.0.address=10.0.0.111/24"
--vmwarevsphere-cfgparam "guestinfo.interface.0.route.0.gateway=10.0.0.1"
--vmwaresphere-folder /folder
```

**Comment by vincent99** [comment]
Few of the `cfgparams` are useful in a template, you're not going to be able to set the node IPs with it without making one template per node.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14 - this has been verified in the UI.  I do not have a VSphere account so I can't say if it's actually working in the backend.

**Comment by adingilloRancher** [comment]
Sat down with Vincent and verified parameters are getting passed to host during provisioning. 

Example:
```
2018/05/22 19:30:34 [INFO] stdout: (ipnode1) Setting guestinfo.interface.0.name to eth0
2018/05/22 19:30:34 [INFO] stdout: (ipnode1) Setting guestinfo.interface.0.ip.0.address to 10.20.10.3
2018/05/22 19:30:34 [INFO] stdout: (ipnode1) Setting guestinfo.interface.0.route.0.gateway to 10.20.11.254
```

**Comment by adingilloRancher** [comment]
Verified folder path and cloudinit are passed down when declared.

2018/05/22 19:49:07 [DEBUG] create cmd [create -d vmwarevsphere --engine-install-url https://releases.rancher.com/install-docker/17.03.2.sh --vmwarevsphere-vcenter esxi01.tempe.rancherlabs.com --vmwarevsphere-cpu-count 2 --vmwarevsphere-username austin --vmwarevsphere-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v17.03.2-ce/boot2docker.iso --vmwarevsphere-cloudinit http://testing/test --vmwarevsphere-vcenter-port 443 --vmwarevsphere-memory-size 2048 --vmwarevsphere-password jHmAtxrAaB4tmX3ERRMf --vmwarevsphere-disk-size 20000 --vmwarevsphere-folder /testing]
