### ISSUE TITLE
Admin first login : must authenticate

### ISSUE THREAD

**Issue by corentin59** [rancher/rancher#13344]
**Rancher versions:**
rancher/rancher:v2.0.0

**Docker version:**
 17.03.2-ce

**Operating system and kernel:**
Ubuntu

**Type/provider of hosts:**
VM / Proxmox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA with RKE, 3 nodes with same version of docker

**Environment Template:**

See attached file
[3-node.txt](https://github.com/rancher/rancher/files/1983114/3-node.txt)
FQDN are valid

**Steps to Reproduce:**
./rke up --config 3-node.yml

**Results:**
INFO[0075] Finished building Kubernetes cluster successfully

When I try to connect on the rancher admin (ingress), I can't update password : must authenticate
![auth-rancher](https://user-images.githubusercontent.com/2035983/39748016-3b6adef8-52af-11e8-8607-8046528250a8.png)

**Comment by superseb** [comment]
I've seen this when nodes are re-used and not cleaned, can you clean the nodes according to https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d

**Comment by corentin59** [comment]
Sorry, no change after play script on each servers

> Removing /var/lib/etcd
Removing /etc/kubernetes
Removing /etc/cni
Removing /opt/cni
Removing /var/lib/cni
Removing /var/run/calico

@superseb : your rancher/rancher version ?

**Comment by corentin59** [comment]
I try with this setup : https://github.com/rancher/rancher/blob/master/rke-templates/3-node-passthrough.yml

I try with only one host.

**Comment by corentin59** [comment]
Same problem after new clean and 1 host in rules.

**Comment by superseb** [comment]
Other scenario this happens is if the UI is visited over an HTTP link instead of the required HTTPS, usually caused by loadbalancer/proxy misconfiguration.

**Comment by ssebbass** [comment]
Same issue here, with the same template.

**Comment by corentin59** [comment]
I try today, with certicate template.

**Comment by corentin59** [comment]
Ok, I use 3-node-certificate.yml, now... I have same problem than #13342

**Comment by corentin59** [comment]
Problem fixed !

**Comment by harutyundermenjyan** [comment]
I got the message `"Must Authenticate"` after restoration of the ETCDs as well
and now cant login to my existing cluster.
