### ISSUE TITLE
can't connect node to the cluster

### ISSUE THREAD

**Issue by fedya** [rancher/rancher#13343]
**Rancher versions:**
rancher/server:v2.0.0
**rancher/rancher-agent:v2.0.0**

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
**18.03.1-ce**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
_NAME="OpenMandriva Lx"
VERSION="4.0 (Nitrogen)"_
**4.9.0-desktop-0.rc4.1omv**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
internal db
**Steps to Reproduce:**
1. `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher`
2. add node 

`docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.0 --server https://lmyhost.ch:8443 --token tokensnsnsnsnsn --ca-checksum 1223456dfdgsgsg --worker`

```
-----BEGIN CERTIFICATE-----
MIIC7jCCAdagAwIBAgIBADANBgkqhkiG9w0BAQsFADAoMRIwEAYDVQQKEwl0aGUt
cmFuY2gxEjAQBgNVBAMTCWNhdHRsZS1jYTAeFw0xODA1MDcxMjMxMjFaFw0yODA1
MDQxMjMxMjFaMCgxEjAQBgNVBAoTCXRoZS1yYW5jaDESMBAGA1UEAxMJY2F0dGxl
LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+3MaK2Adizmv4dKe
bAWDLNbYOAdKLhYl8hZhwADHFETXphHpIXyBQe9eU59Ma68wJyQuYajXAsHAskPK
EzmZIzI6rsAGBPTL/IFb2f+KQRd3Zd6dFmSkxIKU/l5/czY1UKgZ51WYaSb/Fx9b
2XfnpUUC9yGPwfLYrB631opjhqX8NGFDlNsGdNgPZ9jd+GdI9LAwI9lMU3RfnznA
ZyatnND959Oloj7J7R+Ea6BwxLGOTFIYzwHzq6HKlc0rsg5lzhW0qswyFGvsh3rr
0mIa0+Uf9jCHVR88FoHQUd2IKDaccD0F4VZQBAuVh5SrnGyLBMerDQY9VyLN6+dg
n/pyDQIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAN
BgkqhkiG9w0BAQsFAAOCAQEANGmxExZeC1Wna45p2mQF3BuJSXI5osZr4uo4Cz43
aX2iFgJkq2H4Ok/HeQdu/2sX4CUOLLcg8iW8lYrr/Y35GFvJLZlhsK8QpT+ZTCc6
PTN/G1h80oK7BfEFWEu44TzLWpNb/cgYWPkuZxx9Yj1YrRst1t7RTQ3+RQ2IMO+h
arGL7ZjaC/bYAFt9cd3dyigi/lNlBPqBrHyA6wrk9Pf09vV85oly8ZJT1ejejcMm
B9WsK58z1HDWKHUsGfgue1KDgUG4YMxDWh+mQigAug3HMSg/Gbpd9Kl4t2S94wIg
KNwmGvhObHaya6W87jMnLl0vzM2B65/ybJ9VrF+VFzLzJQ==
-----END CERTIFICATE-----
time="2018-05-08T07:47:27Z" level=info msg="Option worker=true"
time="2018-05-08T07:47:27Z" level=info msg="Option requestedHostname=cbuilder"
time="2018-05-08T07:47:27Z" level=info msg="Option customConfig=map[address:11.0.0.57 internalAddress: roles:[worker]]"
time="2018-05-08T07:47:27Z" level=info msg="Option etcd=false"
time="2018-05-08T07:47:27Z" level=info msg="Option controlPlane=false"
time="2018-05-08T07:47:27Z" level=info msg="Connecting to wss://myhost.ch:8443/v3/connect/register with token q5f2lzwlhvqx84njpj6hs4lswf9h8"
time="2018-05-08T07:47:27Z" level=info msg="Connecting to proxy" url="wss://myhost.ch:8443/v3/connect/register"
time="2018-05-08T07:47:27Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-05-08T07:47:27Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-05-08T07:47:37Z" level=info msg="Connecting to wss://myhost.ch:8443/v3/connect/register with token q5f2lzwlhvqx84njpj6hs4ls"
time="2018-05-08T07:47:37Z" level=info msg="Connecting to proxy" url="wss://myhost.ch:8443/v3/connect/register"
time="2018-05-08T07:47:40Z" level=info msg="Starting plan monitor
```

**Results:**

**Comment by superseb** [comment]
What is running at `8443` in front of `rancher/rancher`?

**Comment by fedya** [comment]
@superseb 
nothing it's just a portforwarding from 8443 to rancher-server:443

**Comment by mristok** [comment]
I am having the same problem after successfully deploying ha behind ext lb (https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install-external-lb/). The Rancher web UI is responsive and accessible, and the cacert is correct (Global > Settings > cacerts). How I cannot connect rancher/rancher-agent:v2.0.2 as noted above

**Comment by loganhz** [comment]
I can not reproduce this issue in v2.1.1.

Can you try the following in v2.1.1, please?

1. Create a new rancher server
2. Set the server-url in UI to `https://lmyhost.ch:8443`
3. Add a custom cluster and run the command in UI to add the node

FYI, there is a server-url issue so update it might not work.
https://github.com/rancher/rancher/issues/14731
