### ISSUE TITLE
Should not be allowed to delete node templates that are in use by clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13354]
**Rancher versions: Build from master
**Steps to Reproduce:**

Create a DO cluster using DO node template , say t1.
Once cluster is active , delete t1.
Try to scale up  existing node pools / delete nodes from node pool.
New nodes get stuck in "Initializing" - ```Nodetemplates.management.cattle.io "nt-l5fw7" not found```.

**Comment by tfiduccia** [comment]
Do we want to prevent them from removing node templates or just simply have better messaging on Delete Template and on Scaling?

**Comment by sangeethah** [comment]
Tested with latest build from master:
We are not allowed to delete node templates that are still in use by clusters.
UI does not show delete option for these node templates.
When trying to delete  node templates that are still in use by clusters using API , we get the following error:
```
{
"baseType": "error",
"code": "MethodNotAllow",
"message": "Template is in use by a node pool.",
"status": 405,
"type": "error"
}
```
