### ISSUE TITLE
Error with kops AWS clusters on actual rancher version

### ISSUE THREAD

**Issue by iBat** [rancher/rancher#13355]
**Rancher versions:**
rancher/rancher:latest

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.9.3

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.115-k8s

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Steps from https://rancher.com/checking-rancher-2-0-kops-aws-clusters/

**Results:**
When I use image rancher/server:v2.0.0-alpha7 (as in blog post) - all fine. I'm getting working installation. But when I try switch to actual image rancher/rancher - any latest or stable, I'm getting error in rancher pod
```2018/05/08 15:04:21 [INFO] Listening on /tmp/log.sock
2018/05/08 15:04:21 [INFO] Activating driver gke
2018/05/08 15:04:21 [INFO] Activating driver gke done
2018/05/08 15:04:21 [INFO] Activating driver aks
2018/05/08 15:04:21 [INFO] Activating driver aks done
2018/05/08 15:04:21 [INFO] Activating driver eks
2018/05/08 15:04:21 [INFO] Activating driver eks done
2018/05/08 15:04:21 [INFO] Activating driver import
2018/05/08 15:04:21 [INFO] Activating driver import done
2018/05/08 15:04:21 [INFO] Activating driver rke
2018/05/08 15:04:21 [INFO] Activating driver rke done
I0508 15:04:21.787104       1 http.go:105] HTTP2 has been explicitly disabled
2018/05/08 15:04:21 [FATAL] namespaces "cattle-system" is forbidden: User "system:serviceaccount:default:default" cannot get namespaces in the namespace "cattle-system"```

**Comment by cloudnautique** [comment]
Hello, that blog post is out of date and will be deprecated.

 You can still use Kops to deploy your cluster following their documentation for AWS deployments. Once you have a running Kops cluster, you can follow our HA installation instructions: 

https://rancher.com/docs/rancher/v2.x/en/installation/server-installation/ha-server-install/#get-yaml-template

In the YAML, I would copy out the add on section that defines the Rancher deployment with certificates.

**Comment by wwyhy** [comment]
@thomasbergmann 

I met this issue too. Have you solved this issue? 

Thanks!

**Comment by wwyhy** [comment]
ERROR log:


2018/07/31 02:02:34 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-60-77.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-60-77.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-200-60-77.ap-southeast-1.compute.internal": must be no more than 63 characters
2018/07/31 02:02:34 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal": must be no more than 63 characters
2018/07/31 02:02:34 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal": must be no more than 63 characters
2018/07/31 02:02:34 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/07/31 02:02:35 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-60-77.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-60-77.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-20-60-77.ap-southeast-1.compute.internal": must be no more than 63 characters
2018/07/31 02:02:35 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal": must be no more than 63 characters
2018/07/31 02:02:35 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal": must be no more than 63 characters
2018/07/31 02:02:37 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/07/31 02:02:37 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-20-79-84.ap-southeast-1.compute.internal": must be no more than 63 characters
2018/07/31 02:02:37 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-60-77.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-60-77.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-20-60-77.ap-southeast-1.compute.internal": must be no more than 63 characters
2018/07/31 02:02:37 [ERROR] PodController kube-system/etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-10-20-99-174.ap-southeast-1.compute.internal": must be no more than 63 characters

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue in v2.1.5, and we'll reopen it
