### ISSUE TITLE
[DYNAMIC RBAC] Project Owner/Member - Not able to see node list when "Run all pods for this workload on a specific node"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13356]
**Rancher versions: 2.0 build from master
**Steps to Reproduce:**
As admin user , Create a cluster.
Add a standard user - test1 as project member/owner of the "default" project.

Log in as "test1".
Deploy workload by choosing -  "Run all pods for this workload on a specific node" option. 
Node listed is not presented to the user , since Project Owner/Member do not have the ability to list nodes.
Should we allow for Project Owner/Member to be able to list the nodes (but continue to restrict all other actions on the nodes)?

**Comment by cjellick** [comment]
@ibuildthecloud your opinion? seems like there will be a growing list of things that dont quite work if you're a project member who cannot see nodes?

**Comment by ibuildthecloud** [comment]
I don't see the problem.... I can't see the nodes, but I can see the pods grouped by node name, right?

**Comment by cjellick** [comment]
I think the problem is that dropdown of nodes is empty when choosing the "Run all pods for this workload on a specific node"

**Comment by cjellick** [comment]
Let's revisit as part of dynamic rbac

**Comment by cjellick** [comment]
Simply removing because of dynamic rbac wont be sufficient because this will still result in a bad user experieence. We need to make it clear _why_ that option isnt available

**Comment by abelnieva** [comment]
do we have plans to fix this issue ?
