### ISSUE TITLE
ingress load-balancing not working when server and worker are on the same host

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/rancher#13351]
**Rancher versions:**
rancher/rancher: 2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.1-rancher1

**Docker version: 17.03.2-ce, build f5ec1e2

**Operating system and kernel: 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux

**Type/provider of hosts: Bare-metal

**Setup details: single node rancher

**Environment Template: Kubernetes

**Steps to Reproduce:**

Install rancher server on host
Create cluster
Add node (same host than the server) with etcd/control/worker
Create Workload -> my-app as nginx container
Create Load Balancer -> my-app-ingress for my-app:80 (Automatically generate a .xip.io hostname AND Specify a hostname to use)

**Results:**

The xip.io url is never generated for the ingress and is always : xip.io > my-app
if you use the "Specify a hostname to use" option and make sure the dns point to the host ip you always point to the server ui login page...

**Expected Results:**

The xip.io url should be generated correcly : my-app-ingress.default.<HOST-IP>.xip.io > my-app
When going to the my-app-ingress.default.<HOST-IP>.xip.io url we should get the correct web page (the my-app nginx default page)

**Comment by Angelinsky7** [comment]
i know that my Debian host is not "supported" but with 2 different hosts (same exact config) it's working

**Comment by andreastoermer** [comment]
Same on supported CentOs7. I've got the same problem :)

**Comment by MatteoJoliveau** [comment]
Same, got it on both Docker on Windows and a clean GCE CentOS 7 instance.
/cc @nanomad

**Comment by vincent99** [comment]
The ingress controller runs on port 80 and 443.  The server normally uses the same ports.  If you run the server container and then use the same host as a node in a cluster, the ports are already in use and the ingress controller can't run.

Bind the server container to a different port (`-p 8443:443` or similar, there is no point binding 80 since nobody will seek out the insecure port just to be redirected).

**Comment by Angelinsky7** [comment]
it seems to me that i tried that... (but not sure anymore) and it seems that this should work but the issue was that the url was never created nevertheless (maybe because it was the same ip)
and i'm not really sure that you can rebind the port so easily it seems to me that others services are expecting rancher service to be on the 443 externally...

but i'll try it and will come back if needed.
thanks for the support

**Comment by nanomad** [comment]
Yes, I did just test and it doesn't work
