### ISSUE TITLE
`default backend - 404` when using the `Specify a hostname to use` ingress option with AWS ALB.

### ISSUE THREAD

**Issue by geokhoury** [rancher/rancher#13350]
**Rancher versions:**
rancher/rancher:preview

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.1-rancher1

**Docker version:  Version:** 17.06.2-ce

**Operating system and kernel:**

NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"

4.9.78-rancher2

**Type/provider of hosts:** AWS EC2 cluster.

**Setup details:** 

- Single node rancher.
- Internal DB (running on own node in the same cluster).
- CloudFlare used for DNS setup, SSL termination setup on DNS level.

**Steps to Reproduce:**

1. Setup an AWS layer 7 load-balancer, follow steps on [Configure Amazon ALB](https://rancher.com/docs/rancher/v2.x/en/installation/load-balancing-config/config-amazon-alb/).
2. Create a `workload` on a provisioned cluster (I have a cluster provisioned on top of EC2) with the `nginx` image workload.
3. Expose port `80` as a nodeport, then map it by adding ingress rules in the `Load Balancing` tab. Check the issue details below to understand how different entries yield different results.

**Results:**

1. When I use the `Automatically generate a .xip.io hostname` option ( addresses like `nginx.default.XXX.XXX.XXX.XXX.xip.io`) everything works just fine. Pods are reachable and everything seems to be running correctly. I can see the `NGINX default page`. _This tells me it is not an issue with ports, security groups or other service related issues._

2. When I use the `Specify a hostname to use` option, (addresses like `some-service.dev.domain.com`) yield a `404`.  I get a page with the error `default backend - 404`.

3. **HOWEVER**, when I use the `Use as the default backend` and set it to the `nginx` service then the address in `2.` above works just fine with the _default backend_. I can reach the pod correctly.

_To me it sounds like Rancher, or any component in between is having trouble figuring out the `Host` value in the HTTP headers._

**Questions:**

1. What is the issue with the load balanced setup described above?
2. How can I debug this issue? I can’t figure out where to look. Pod logs seem to be fine. When I use option `1.` above, I can even see access logs when I use `xip.io` **or** when I set any service as the `default backend`.

**Comment by sangeethah** [comment]
@geokhoury 
```When I use the Specify a hostname to use option, (addresses like some-service.dev.domain.com) yield a 404. I get a page with the error default backend - 404.```

For this case , how are you accessing the Ingress url ? Is it using http:// or https:// ? 
If you are using "https://" to access , there needs to be certificates provided for the hostname in the ingress.
We have an issue to track the issue that user should not be presented with https url in cases where certificates are not provided - https://github.com/rancher/rancher/issues/13218

If you are using "http://" , Could you let us know if the hostname is being passed as a header in the request?

**Comment by geokhoury** [comment]
@sangeethah I also think this is related to the problem. Currently, we have SSL termination enabled on CloudFlare on the domain level. I also added a self-signed certificate to the AWS ALB for the HTTPS listener.

When I try adding it on Rancher, I get complaints about the key. The error states 
`Private Key is invalid. Please make sure it is a RSA key.` I am certain it is an RSA key, and also the first and last line of the key also denote that this is an RSA key. Any ideas?

`If you are using "http://" , Could you let us know if the hostname is being passed as a header in the request?` 

Regarding this, I have tried to verify, it looks like the hostname is being passed as a value in the HTTP header, I am not sure how to make sure it gets to Rancher though. How can I verify this on Rancher?

**Comment by sangeethah** [comment]
```When I try adding it on Rancher, I get complaints about the key. The error states
Private Key is invalid. Please make sure it is a RSA key. I am certain it is an RSA key, and also the first and last line of the key also denote that this is an RSA key. Any ideas?```

@geokhoury This is a UI issue that prevents certs from being added -
 https://github.com/rancher/rancher/issues/13156

**Comment by sangeethah** [comment]
In this case , Even if hostname is passed correctly using headers when accessing ingress url, but if there is no certificate set for the hostname , accessing "https://" is not going to to work . We expect "https://" access to work only when there is a certificate tied to it.
