### ISSUE TITLE
Unable to create new DO cluster with Rancher Up

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13353]
**Rancher versions:**
Master 5/8/2018

Steps:
Create a new DO cluster 
Perform rancher inspect --format yaml (cluster)
Take yaml file and save locally
Edit yaml file, change ID field to unique value. 
Login to your rancher server through rancher CLI.
Perform rancher up -g -f (yaml file)

Results:
Should provision new DO cluster.

**Comment by deniseschannon** [comment]
Available with Rancher CLI v2.0.2-rc1

**Comment by adingilloRancher** [comment]
@StrongMonkey Exported yaml from cluster. Attempted rancher up with exported yaml after deleting cluster that was in use. (So name would still be unique.) Did not see new cluster start on rancher server.

**Comment by StrongMonkey** [comment]
@adingilloRancher what's the error when it failed to run `rancher up`? i was managed to do it and new cluster was started up. But you have to have at least one active cluster to get cli working. (So instead of deleting cluster i rename the yaml)

**Comment by StrongMonkey** [comment]
It appears to be a bug in cli that if you don't have a cluster(or project) then you can't do `rancher up`. Will fix that

**Comment by adingilloRancher** [comment]
Validated with Rancher CLI v2.0.2-rc1. Able to create DO cluster Closing issue.
