### ISSUE TITLE
Aurora + SSL as the db backing for rancher

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#13363]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.17

**Steps to Reproduce:**
1. deploy AWS Aurora RDS instance following instructions from: https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#mysql-ssl

using the RDS CA bundle https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem mapped to /var/lib/rancher/etc/ssl/ca.crt

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
