### ISSUE TITLE
[rancher-compose]: Create stuck in loop checking for stack

### ISSUE THREAD

**Issue by khusseini** [rancher/rancher#13367]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.10
rancher/agent or rancher/rancher-agent:1.2.6

**Infrastructure Stack versions:**
healthcheck:0.3.3
ipsec:0.1.4
network-services:0.2.6
scheduler:0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 63
 Running: 58
 Paused: 0
 Stopped: 5
Images: 55
Server Version: 17.09.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.11-coreos
Operating System: Container Linux by CoreOS 1576.5.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.81GiB
Name: dpcore
ID: W5L6:KOBH:YNFK:LADC:CN5U:GKF2:LRX7:42QF:3CPM:XQ47:GAG3:KO6J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

I have a problem with creating a stack using rancher-compose. For some reason it gets stuck just looking up the stack in different API URL requests and then just stops with the following error message:

```
time="2018-05-09T03:18:39+02:00" level=info msg="Creating stack snip-deprod" 
time="2018-05-09T03:18:39+02:00" level=error msg="Failed to open project snip-deprod: Can not create a stack, check API key [snip] for [https://snip.snip.de/v1]" 
time="2018-05-09T03:18:39+02:00" level=fatal msg="Failed to read project: Can not create a stack, check API key [snip] for [https://snip.snip.de/v1]" 
```

the two `level=info` messages keep appearing between API calls. I cannot post the whole log in here because it contains sensitive information and its about 2.5MB of data I need sweep through. I'll need free some time to clean them. However between the info messages there are a bunch of API calls which return a huge JSON response. 

I'd like to get this working, so I don't have to always go in the UI and create stacks by hand.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
