### ISSUE TITLE
Adding Private Helm catalogs should allow for auth

### ISSUE THREAD

**Issue by josmo** [rancher/rancher#13371]
When adding private repos that contain a Helm Catalog the state is stuck in "refreshed" and the catalog items never show up in the option to launch a catalog item.

I would expect to have some authentication options for private catalogs to be able to be used.

Also, it looks like it's assumes a git repo (needing a default branch) however I believe it could also just be a web server (like s3 with packages published with index)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`global-admin.catalog`|

**Comment by aemneina** [comment]
I believe auth works today if you use `https://user:password@git.repo.com` or ssh keys, it would be nice to either obfuscate the user/pass in the url or surface fields where users can provide credentials.

**Comment by josmo** [comment]
Thanks @aemneina I totally found that out.

**Comment by frenchtoasters** [comment]
I had this issue with a hosted git instance using a self signed cert as well. I resolved it by just using `http://gitlab.instance.site` instead of `https://gitlab.instance.site`

**Comment by rustymunkey** [comment]
I would like to address this issue, as i stumbled upon it while trying to add a private helm repository to rancher 2.0.8.

The workaround with adding username:passwort to the repository url works only for getting the index.yaml of the repository. Thus the catalog is added and the entries are displayed.
However, the index.yaml contains the download URL for the charts without any authentication information. Rancher then tries to download the files, gets a HTTP 401 error and fails silently:

Rancher says:

`2018/09/05 15:45:09 [DEBUG] Fetching file https://artifactory.mycompany.com/helm-repository/sample-0.1.2.tgz`
`2018/09/05 15:45:09 [DEBUG] REST UPDATE apis/management.cattle.io/v3//catalogs/art`

The helm repo (artifactory in our case) says:

`20180905154509|0|REQUEST|10.0.0.1|non_authenticated_user|GET|/helm-repository/sample-0.1.2.tgz|HTTP/1.1|401|0`

This leads to a situation where the catalog is populated, but the catalog entries are missing any details and cannot be installed.

Adding a basic auth functionality to the catalogs would solve this issue with private helm repositories.

**Comment by codejamninja** [comment]
👍

**Comment by govinda-attal** [comment]
This feature will be a fantastic one!

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/49569551-3757ff00-f96f-11e8-8a29-161b3ca10771.png)

Rancher will support HTTP, HTTPS, Git in 2.2. User can use add private catalog from a private git repo or a private http/https server.

**Comment by rootwuj** [comment]
Rancher 2.2 supports the private catalog has been tested.
The test function points are as follows:
1. Add private catalog at global/cluster/project level
2. Add private catalog from a private git repo or a private http/https server
3. Edit or delete the private catalog
4. Verify the launch application
5. Verify update private catalog
6. Verify the public catalog function

**Comment by pdschandler** [comment]
Will this change be making it's way to RancherOS so that custom OS services can live in a private repo?

**Comment by gabrielcalderon** [comment]
There's still not way of adding ssh-keys for git repos?
