### ISSUE TITLE
Can not deploy rancher to a Kops AWS cluster in ap-southeast-2

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#13370]
**Rancher versions:**
rancher/rancher: v2.0.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Kops AWS HA

**Steps to Reproduce:**
```
  export NODE_SIZE=${NODE_SIZE:-m5.large}
  export MASTER_SIZE=${MASTER_SIZE:-m3.medium}
  export ZONES=${ZONES:-"ap-southeast-2a,ap-southeast-2b,ap-southeast-2c"}
  export KOPS_STATE_STORE="s3://my-kops-clusters"

  kops create cluster k8s-prod.mycluser.com \
  --node-count 2 \
  --node-volume-size 100 \
  --zones $ZONES \
  --node-size $NODE_SIZE \
  --master-size $MASTER_SIZE \
  --master-zones $ZONES \
  --master-volume-size 100 \
  --networking canal \
  --cloud aws \
  --dns private \
  --dns-zone ABCDEFG1234 \
  --vpc vpc-123456780 \
  --ssh-public-key ~/.ssh/k8s-prod.mycluser.com.pub \
  --kubernetes-version 1.10.1
```
kubectl create -f [rancher_yml.txt](https://github.com/rancher/rancher/files/1986296/rancher_yml.txt)

**Results:**
The kubernetes cluster validates; however rancher never comes online
the logs for the rancher pod has a bunch of these 

`PodController kube-system/etcd-server-events-ip-12-0-110-141.ap-southeast-2.compute.internal [podHandler] failed with : Pod "etcd-server-events-ip-12-0-110-141.ap-southeast-2.compute.internal" is invalid: metadata.labels: Invalid value: "etcd-server-events-ip-12-0-110-141.ap-southeast-2.compute.internal": must be no more than 63 characters`

as well as these 
` 1 generic_controller.go:204] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set`

NOTE: i tried a private kops cluster as well as a public cluster, as well as using the gossip protocol

**Comment by mattparkes** [comment]
m5s aren't available in ap-southeast-2a (but are in b and c). Since the first node is never created, rancher doesn't seem to make any more nodes and doesn't really tell you anything.

You'll probably have more luck with m4s (or only deploying to b and c).

**Comment by mattparkes** [comment]
This report should probably be changed (or a new one created) to address this exact issue.

**Comment by cloudnautique** [comment]
The error is saying it can't label the pod with "etcd-server-events-ip-12-0-110-141.ap-southeast-2.compute.internal" that is a 67 character string and it needs to be something <64 characters. I would attempt to shorten the host name.

The second error can be ignored in the Cluster Controller.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13355
