### ISSUE TITLE
Cannot create nfs persistent volume

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#13375]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node ranche
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. Launch the nfs-provisioner from catalog apps using the default settings
2. Add a volume from workflows-volumes, select nfs-provisioner for Storage Class
**Results:**
The volume status has always been "Pending"
```
root@ip-172-31-43-111:~# kubectl get pvc
NAME                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
test                   Pending                                                                        nfs-provisioner   36s
```
```
root@ip-172-31-43-111:~# kubectl describe pvc test
Name:          test
Namespace:     default
StorageClass:  nfs-provisioner
Status:        Pending
Volume:
Labels:        <none>
Annotations:   field.cattle.io/creatorId=user-qdr85
               volume.beta.kubernetes.io/storage-provisioner=rancher.io/nfs-provisioner
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type    Reason                Age               From                         Message
  ----    ------                ----              ----                         -------
  Normal  ExternalProvisioning  4s (x11 over 2m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "rancher.io/nfs-provisioner" or manually created by system administrator
```

**Comment by BalaBalaYi** [comment]
Same issue. 
But deploy nfs manually is fine, just practiced.

**Comment by kingsd041** [comment]
Tested with rancher-server version- v2.0.0 with nfs-provisioner version-0.1.0
Test passed.
