### ISSUE TITLE
how to pass the additional argument as part of the helm chart catalog install 2.0.  

### ISSUE THREAD

**Issue by senpx** [rancher/rancher#13372]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent:2.0

<img width="1470" alt="screen shot 2018-05-08 at 16 57 01" src="https://user-images.githubusercontent.com/32806443/39795685-ba540c60-5306-11e8-928f-b83b3db42d08.png">

<img width="1602" alt="screen shot 2018-05-08 at 16 46 56" src="https://user-images.githubusercontent.com/32806443/39795731-2564f384-5307-11e8-8bd1-f06e93759270.png">

Hi,
Do we have documentation the add the helm catalog in 2.0? how to customize the catalog page or pass the argument as part of the helm chart catalog install 2.0.  Do i need to update the anything in our Helm chart? do we have any examples and steps?  Please find the attached screenshot for the issue. can some assist me to proceed further? thanks in advance.

**Comment by guangbochen** [comment]
hi @senpx, please bear with us and we will have the catalog documentation quite soon.

**Comment by guangbochen** [comment]
Hi @Angelinsky7, there are currently two ways, the first one is you can specify values use the `Add Answer`  button to change it, for values with nested layer in the `values.yaml` you can use `foo.bar.joo` to specify it.
![image](https://user-images.githubusercontent.com/4569037/40031512-98bb743c-5822-11e8-8c83-7bb075b5ed7e.png)
the second way is to use rancher `questions.yml` to design your questions UI (values.yaml is always required), it currently support `boolean, string, enum, password, int`, u can reference an example from the [rancher-charts](https://github.com/rancher/charts).

**Comment by senpx** [comment]
@guangbochen did you release  catalog documentation ? thanks in advance.

**Comment by guangbochen** [comment]
hi @senpx, the [rancher/charts](https://github.com/rancher/charts) repo now has the fundamental documentation for the catalog apps, let us know if u have any specific questions in regards to the chart development, and we will add more examples in the future, thanks.

**Comment by webdirol** [comment]
Hi! Can you please tell me how to specify node labels for pod assignment by values using the Add Answer button? E.g. having defined a node label: test.xyz-ok = true
How is this to define in Rancher Helm Answer Questions. See for example...
![nodeselector_2](https://user-images.githubusercontent.com/14794694/43358860-be23c930-9298-11e8-9f9f-fd27a0838de9.png)
