### ISSUE TITLE
Launch kubectl has E0509 return sometimes.

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/rancher#13373]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0
rancher/agent or rancher/rancher-agent: v2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2 ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos7.2
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
virtual machine
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes RKE 1.10.1-rancher2
**Steps to Reproduce:**

Launch kubectl in the Cluster web page.

**Results:**
Sometimes it turns good, just like normal. U can use the kubectl on the page.

But sometimes it just keep connecting:
![image](https://user-images.githubusercontent.com/23303886/39796993-58d2f5a6-538c-11e8-827b-78ebbcb56f15.png)

The logs of kubelet container:
normal:
I0509 05:06:38.168847    4970 server.go:796] GET /exec/cattle-system/cattle-node-agent-2j984/agent?command=kubectl-shell.sh&command=kubectl-shell-user-hmsfh%3A8bdrxwjnzbwbqjn46chjc5vp9jb5rr8vct4r66m2mrs4snq6k6sv5j&command=c-n9z8r&error=1&input=1&output=1&tty=1: (19.217303ms) 302 [[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36] 10.255.83.133:26378]

unormal(with e0509 return):
I0509 05:06:59.201359    4970 server.go:796] GET /metrics/cadvisor: (234.406459ms) 200 [[Prometheus/2.2.1] 10.255.83.132:46858]
E0509 05:07:06.447068    4970 exec.go:127] Exec session 5e31ab29b1356a166644c5488cc47d4e7a994e63ee21530b9e065858850e806e in container ce9e9d6d5c627c78103924d1c241011e42ddd865dd18ad7b1ca3b9ef07ec667d terminated but process still running!
I0509 05:07:06.447163    4970 server.go:796] GET /cri/exec/uDO7G-20: (5m25.873407785s) 0 [[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36] 10.255.83.132:56350]

**Comment by loganhz** [comment]
I can not reproduce this issue.
It might be related to https://github.com/rancher/rancher/issues/13529#issuecomment-389684136
Please let us know in a comment if you can still reproduce the issue in v2.1.1, and we'll reopen it
