### ISSUE TITLE
Azure AKS UI is missing Azure supported versions

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#13387]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): azureaks

**Docker version: (`docker version`,`docker info` preferred)**
N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AKS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher on docker

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
Select the Azure AKS Node Driver.  Select the Kubernetes Version Dropdown

**Results:**
1.8.1 is the only option available.
![image](https://user-images.githubusercontent.com/942110/39829174-64487484-5372-11e8-8ff8-5ec77eef78ec.png)

Azure currently supports all of these versions.
![image](https://user-images.githubusercontent.com/942110/39829221-980eb332-5372-11e8-8fc1-4d1849f2f548.png)

**Comment by nathan-jenan-rancher** [comment]
new endpoint at `/v3/aksVersions`

http method: POST

example request body:
```
{
	"clientId": "<CLIENT ID>",
	"clientSecret": "<CLIENT SECRET>,
	"subscriptionId": "<SUB ID>",
	"tenantId": "<TENANT ID>",
	
	"region": "eastus"
}
```

**Comment by soumyalj** [comment]
Tested with v2.0.3 . All K8s versions are displayed when we try to create an AKS cluster
The api call returns the below:
```
["1.6.6","1.6.9","1.6.11","1.6.12","1.6.13","1.7.0","1.7.1","1.7.2","1.7.4","1.7.5","1.7.7","1.7.9","1.7.10","1.7.12","1.7.13","1.7.14","1.7.15","1.7.16","1.8.0","1.8.1","1.8.2","1.8.4","1.8.6","1.8.7","1.8.8","1.8.9","1.8.10","1.8.11","1.8.12","1.8.13","1.9.0","1.9.1","1.9.2","1.9.3","1.9.4","1.9.5","1.9.6","1.9.7","1.9.8","1.10.0","1.10.1","1.10.2","1.10.3","1.10.4"]


```

**Comment by soumyalj** [comment]
Tested with rancher v2.0.3-rc2. AKS cluster creation screen in rancher UI displays the k8s versions supported by Azure:
<img width="452" alt="screen shot 2018-06-21 at 1 55 01 pm" src="https://user-images.githubusercontent.com/18536626/41745261-3aa949cc-755b-11e8-9a96-81596bb83111.png">
API call returns the below list:
```

["1.7.7","1.7.9","1.7.12","1.7.15","1.7.16","1.8.1","1.8.2","1.8.6","1.8.7","1.8.10","1.8.11","1.9.1","1.9.2","1.9.6","1.10.3"]

```
