### ISSUE TITLE
LDAPS auth broken on upgrade to 1.6.17

### ISSUE THREAD

**Issue by hdep** [rancher/rancher#13384]
**Rancher versions:**
rancher/server 1.6.17

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian 8 - 3.16.0-6-amd64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWARE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher HA with external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
- stop old rancher/server container,
- sudo docker pull docker-public.recette.local/rancher/server:stable
- sudo docker run -d --restart=unless-stopped -p 8080:8080 -p 9345:9345 -v /root/ac.crt:/var/lib/rancher/etc/ssl/ca.crt  docker-public.recette.local/rancher/server:stable --db-host dbserver --db-port 3306 --db-user rancher --db-pass password --db-name rancher 
- try  to login

**Results:**

Webui show :  

> Error communicating with authentication provider
Container logs : 

```
time="2018-05-09T13:36:46Z" level=info msg="Now generating Ldap token"
time="2018-05-09T13:36:46Z" level=error msg="GetToken failed with error: Error creating ssl connection: LDAP Result Code 200 \"\": x509: certificate is not valid for any names, but wanted to match ad1.domain.local"
2018-05-09 13:36:46,327 ERROR [:] [] [] [] [p1020391880-141] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500, message: Error creating ssl connection: LDAP Result Code 200 "": x509: certificate is not valid for any names, but wanted to match ad1.domain.local

```

LDAP auth was working like a charm with 1.6.16, the certificates didn't change on AD side so I don't get what's wrong here. The certificate CN on AD side is *.domain.local

should be working.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
