### ISSUE TITLE
Worker nodes randomly become inactive

### ISSUE THREAD

**Issue by MariusDieckmann** [rancher/rancher#13382]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
NAME="RancherOS"
VERSION=v1.3.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.3.0
PRETTY_NAME="RancherOS v1.3.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 14
 Running: 11
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.80-rancher
Operating System: RancherOS v1.3.0
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.42 GiB
Name: kubeworker-4.novalocal
ID: 3EF3:B22K:3QQ3:TWH4:J6J5:5E22:7ZI4:YUFY:LS36:KR7V:SOEG:SI5W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.80-rancher
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, installed via VM
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Provision VMs in Openstack with RancherOS 1.3.0, same error occured with Ubuntu 16.04
Install and add custom cluster using the docker command presented in the interface. Deploy cluster, wait.
[dockerpslog.log](https://github.com/rancher/rancher/files/1987679/dockerpslog.log)

**Node system information**

Architecture | amd64
-- | --
Docker Version | 17.3.2
Kernel Version | 4.9.80-rancher
Kubelet Version | v1.10.1
Kube Proxy Version | v1.10.1
Operating System Image | Debian GNU/Linux 9 (stretch)
Operating System | linux

**Results:**
Individual worker nodes seem to stop working with error message: Kubelet stopped posting node status.
The information placed above is directly taken from one of these nodes. The error only occurs occasionally and with no apparent reason. They become active again after some time.
The nodes remain inactive in this state for a couple of minutes, maybe up to 10.
For further details like logs from single docker container on inactive nodes just ask.

Thank in advance
Marius

**Comment by weslleycamilo** [comment]
The same issue here..

**Comment by superseb** [comment]
Kubelet sends Ready or NotReady events, `kubelet` log is what would be helpful. As well as the specifications of the nodes that are in the cluster, and the ones that are reporting bad status.

**Comment by MariusDieckmann** [comment]
In our case this issue was based on issues with the underlaying network infrastructure, we fixed it by fixing our routers. Here is what i think made this problem occur. The TCP heartbeat connection from the kubelet became unroutable and was stuck. The kubelet however has a long timeout on this connection and will only try to reconnect after 15 minutes, in the meanwhile the kubelet will be reported unavailable. There is a fix available in 1.11 which will be backported to older versions according to this: https://github.com/kubernetes/kubernetes/pull/63492

You can verfify this by checking for how long the kubelet becomes inactive. If its 15 minutes then this could be your problem.

**Comment by superseb** [comment]
This is fixed in v1.10.3 and v1.11.0
