### ISSUE TITLE
Removing catalog doesn't remove the catalog-controller cache

### ISSUE THREAD

**Issue by chocopowwwa** [rancher/rancher#13380]
**Rancher versions:**
rancher/rancher:  2.0
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
- Add custom helm chart to rancher-global catalog
- check the cluster `project->catalog-apps` that the chart sucess fully imported
- Remove the custom helm chart from rancher-global
- Recheck the `project->catalog-apps`
**Results:**
- catalog item persist, unless i remove it manually from ```/var/lib/rancher/management-state/catalog-controller/cache```

**Comment by seanly** [comment]
+1

**Comment by gregkeys** [comment]
I noticed this too, would be great to even have a simple clear cache button to clean things up

**Comment by StrongMonkey** [comment]
We keep the cache to improve the performance when syncing catalog repository. The issue that templates not being deleted might be related to https://github.com/rancher/rancher/issues/15212, which is fixed in 2.0.8.

**Comment by loganhz** [comment]
Please check https://github.com/rancher/rancher/issues/13380#issuecomment-418436004

**Comment by Remigius2011** [comment]
my cache (on v2.1.3) has grown to 7.9G - is this really necessary?

**Comment by gregkeys** [comment]
i still have items in the cache that were removed long ago. (August 2018)

**Comment by Remigius2011** [comment]
I wouldn't mind to just rimraf everything, but I don't know about the consequences.

**Comment by gregkeys** [comment]
I would love to have a clear cache button.

**Comment by Remigius2011** [comment]
I would love not to need a clear cache button, but for the moment being I would be quite happy with a qualified answer on what parts of the cache's content can safely be deleted.

**Comment by Envikia** [comment]
I just upgraded to 2.1.6 and also suffering in this problem too.
The size of the cache has growth to 8.6GB, it is also prolonging my daily backup of Rancher.

Looking for a good solution in Rancher or procedures to housekeep unnecessary files.

**Comment by erikwilson** [comment]
This should be fixed as part of rancher/rancher/issues/14322 PR (https://github.com/rancher/rancher/pull/17596).

We remove controller-cache on start-up and use a catalog-cache directory now. There is a cache cleaning mechanism to remove items not associated with a catalog. That logic triggers on startup, once an hour, and debounces catalog changes to clean up a minute later.

**Comment by erikwilson** [comment]
To test this change it is best to start with Rancher server v2.1.6:
- Observe size of `management-state/catalog-controller`
- Enable several unique catalogs
- Observe size of `management-state/catalog-controller`
- Disable catalogs
- Observe size of `management-state/catalog-controller`

Upgrade to Rancher master:
- Contents of `management-state/catalog-controller` will be removed
- New cache is created at `management-state/catalog-cache`
- Observe size of `management-state/catalog-cache`
- Enable several unique catalogs
- Observe size of `management-state/catalog-cache`
- Disable catalogs
- After a few minutes after no catalog changes (~1m) old cache entries will be removed
- Observe size of `management-state/catalog-cache`

**Comment by cjellick** [comment]
@sangeethah  as this is related to the helm fixes, I assigned directly to @bmdepesa

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/25
HA setup

* Reproduced original issue
* Upgrade to rancher/rancher:master
* `management-state/catalog-controller` is removed
* `management-state/catalog-cache` is present
* Enabled several catalogs and observed size of cache
* Removed catalogs and saw the cache size decrease as entries were removed

**Comment by dradux** [comment]
fyi, I had a rancher v2.1.6, catalog-cache was 28g, upgraded to v2.3.3 and cache is now 47mb (nothing other than the upgrade performed).

**Comment by cjellick** [comment]
w00t!
