### ISSUE TITLE
[Question] how to stop/restart a workload

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/rancher#13389]
Rancher versions:
rancher/rancher: 2.0.0

How can we pause, stop or restart a workload in rancher 2...
How can we scale to 0 a workload like that when we destroy faulting pod kubernetes doesn't try to recreate it directly... (like the old `kubectl stop`)

i know that i can save my workload into a file, destroy it and then recreate-it but it seems to me sad not to have those functionalities ... even if i'm pretty sure that they seem necessary now because i'm testing rancher2/kubernetes and won't be important in a prod environment

I've got an example that might be production relevant :
In longhorn the recommended steps to recover a volume is to stop the pod using it : https://github.com/rancher/longhorn/issues/63#issuecomment-387807856 but if we cannot really stop it because directly after deleting a pod, it's recreated (and faulty because the old pod still exist and the new one cannot attach/mount the volume) how can we recover a volume ???

Thanks for you amazing work...

**Comment by manwegit** [comment]
Using kubectl or kubernetes dashboard it's possible to scale deployment to 0.
```kubectl scale --replicas=0 deployment DEP_NAME -n CORRECT_NAMSPACE ```
[cheatsheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#scaling-resources)

**Comment by Angelinsky7** [comment]
@manwegit thanks for you answer
Yes i know that but i wanted to know how to do it directly in the ui...
(or more why can't we do it directly in the ui ???)
We could use the +/- menu but it's minimum value is 1... should be 0 no ?

**Comment by Angelinsky7** [comment]
Just tried that in the ui (live edititing html and removing the disabled="" attribute of the "-" button of the workfload... and it's working !!!

**Comment by Angelinsky7** [comment]
Found out that those parameters already exist :

Scale Max : https://github.com/rancher/ui/blob/30c40fa9219ee5def63c999bd6b3951bc816e7a1/app/models/workload.js#L84
and
Scale Min : https://github.com/rancher/ui/blob/30c40fa9219ee5def63c999bd6b3951bc816e7a1/app/models/workload.js#L95

but how can we change it from the ui ???

**Comment by stevenmunro** [comment]
I also have this question. How do we restart a workload?

**Comment by genachka** [comment]
+1 In previous Rancher version, it was easy to Restart and Stop. Need this feature in 2.0 please.
![previous_rancher](https://user-images.githubusercontent.com/7947294/40269390-dde59ac0-5b4b-11e8-873f-1b36a2f5e2f7.png)

**Comment by vincent99** [comment]
There is no stop/start/restart in k8s.  There's the scale (replicas), deleting individual pods, and upgrade strategy (depending on what kind of workload).

`scaleMin` and Max are vestigial code in the UI left over from 1.x; they do not exist in the 2.0 API so they have no relevance.

The minimum in the scale input could be changed to 0 so they you can do "stop".

**Comment by Angelinsky7** [comment]
+1 for the minimum scale input to 0
but why couldn't we have : 

1. a stop/pause button that set the scale to 0.
2. a resume button that set the scale back to the original value (before the stop/pause)
3. a restart button that set the scale to 0m then to the original value when all the pods are stopped

Could be great, no ?

**Comment by gjongenelen** [comment]
IMHO I think that is a bad idea, or at least a wrong name for the button. What it really would do is just recreate the pods, and not restart them. 
If necessary I restart pods by killing the foreground process in the pod. This will force a restart.

**Comment by Angelinsky7** [comment]
i understand, but it seems to me (but i'm certainly mistaken) that in rancher v1, docker, docker-compose and swarm it's the actual behaviour (restarting only kill the container and restart it)
i know we could argue that's not exactly the same thing... but your solution implies the knowledge of what is happening inside the container, no ? and this seems to me a worst idea.

**Comment by gjongenelen** [comment]
Yes, you will need to know the foreground process. So I agree with you that my solution is not a solution for Rancher. But I think we have to accept that the restart-function as we know it in Rancher1.x will not be introduced in Rancher2.x due to the k8s philosophy.

**Comment by manwegit** [comment]
Actually there is "Pause orchestration" option for deployment workloads. BUT I think it's a bit broken still. Pausing does nothing for the pods, but resume terminates and starts new pods.
So if you wan't to refresh your pods (e.g. scale to 0 and back up repolicas) that will do it.

**Comment by genachka** [comment]
To me this is about simplification within the GUI. If I wanted to go searching for foreground process I'd use the CLI. If in the docs it details what the actions for Pause, Resume, Restart are actually doing behind the scenes then that's good enough for me and I will pick the appropriate one. And so I will know that when I click on Restart it's actually behind the scenes doing a scale to 0 and then to the original scale, and in essence recreates them, etc. If it helps, call it Recreate and document that clearly (the docs for 2.0 are still in very bad shape IMHO with little detail and examples for almost everything). In the end I want to save time without going through multiple steps.

**Comment by Angelinsky7** [comment]
... and somewhat hide kubernetes "complexity" to the user... isn't one of the main goal of rancher ?

**Comment by Angelinsky7** [comment]
@vincent99 thanks for your insight
i understand that this is really a "big" problem that doesn't have a simple solution but your answer comfort me in the idea that rancher should really solve it, don't you think ?

**Comment by matthax** [comment]
It seems to me that a nice intermediate solution might be the "Redeploy" option. We've had a few incidents that have caused containers to act up and there's not an easy way to force them to redeploy since, technically, they are working correctly as reported by their health statuses.

**Comment by blackholegalaxy** [comment]
@vincent99 The fact is, as stated by @Angelinsky7, Rancher main purpose is to me to abstract kubernetes complexity and requirements. I don't really "care" what it's doing under the cover but Rancher should definitely offer an option to (like in 1.x) start, stop, restart a workload (old service) or entire namespace (old stack). 

I understand there is Kubernetes under rancher. But as said again: I don't want to have to master kubernetes to use rancher. Or what is the point to use Rancher?

Rancher refers too much to kubectl or other native kubernetes stuff I definitely don't want to have to use. The less I use kubeCtl, the more Rancher is accomplishing its abstraction goal.

**Comment by vincent99** [comment]
"Rancher [2.x] is enterprise management for Kubernetes."  It is not a PaaS in which we pretend the underlying k8s does not exist.  You need to be familiar with k8s concepts and we add value _around_  them (e.g. access control and managing rbac across multiple clusters, logging, etc).  If you don't want to use k8s, you're not going to want to use Rancher 2.0.

While we can provide a shortcut for redeploying new containers for a workload (by twiddling a label for you), Stop and Restart are simply not concepts that exist.

**Comment by karllhughes** [comment]
So I want to use the REST API to update containers upon deploy. Is the best way to do this really to scale each to zero, then scale back up to N? There's got to be a way to do this with zero downtime, right?

**Comment by PicoCreator** [comment]
How bout an alternative label such as "recreate" or "redeploy" - currently we are hacking around this, by creating an environment variable called `UPGRADE_FLAG`, and smashing the keyboard with a new value to trigger "restarts" - not ideal, but it works for our use.

**Comment by PicoCreator** [comment]
@karllhughes - a work around using the rancher CLI would be as followed. `./rancher kubectl set env ds test --namespace "test" -e DEPLOY_ID="$(date +%s)"`

**Comment by vincent99** [comment]
Adding a redeploy action to the UI and on edit workload that sets `cattle.io/timestamp` annotation to the current time.  The rest above (start/stop/restart) does not exist as I said and will not be addressed.

**Comment by tfiduccia** [comment]
Version 2.1 master
Verified fixed
