### ISSUE TITLE
AKS Cluster Name validation returns "name" field which is confusing

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#13393]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
N/A

**Docker version: (`docker version`,`docker info` preferred)**
N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure AKS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node on Docker

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
Type in a "Cluster Name" with a space in it.
![image](https://user-images.githubusercontent.com/942110/39834389-a41d9fd0-5381-11e8-90d6-33a8d8e59c43.png)

**Results:**
This error is logged to the console
```2018/05/09 17:29:49 [ERROR] API error response 422 for POST /v3/cluster. Cause: InvalidFormat 422: invalid value azure test cluster: a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')```

This error is created at the bottom.
![image](https://user-images.githubusercontent.com/942110/39834476-eedabb2a-5381-11e8-93a3-01878e84eb64.png)

**Comment by vincent99** [comment]
This shouldn't be getting sent to the API in the first place, UI validation of `dnsLabel` fields isn't working right.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Verified fixed
