### ISSUE TITLE
Service Discovery services are not removed when I remove catalog app

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13391]
**Rancher versions:** 2.0 master 5/9

**Steps to Reproduce:**
1.  From the Helm catalog deploy Anchore catalog app
2.  Wait for it to become fully active
3.  Remove the app

**Results:**  Workloads get deleted but the Service Discovery services don't delete
![image](https://user-images.githubusercontent.com/11514927/39832132-43d485c2-537b-11e8-99bd-0888ab16f5cb.png)

**Comment by StrongMonkey** [comment]
@tfiduccia i didn't reproduce. When i create Anchore app and delete it, everything is cleaned up. Can you please re-verify this?

**Comment by sangeethah** [comment]
Tested with latest build from master - Jun/13.

When anchore-engine app (from Helm) is deployed and then deleted , all workload and service discovery entries get deleted as expected.
