### ISSUE TITLE
Azure AKS Support - missing basic DNS prefix, virtual network and subnet

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#13395]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
N/A

**Docker version: (`docker version`,`docker info` preferred)**
N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure AKS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 
A number of options are not available to users provisioning Azure AKS Clusters.

From Basics DNS prefix is not available.
![image](https://user-images.githubusercontent.com/942110/39838469-58e1efa0-538e-11e8-85d0-478dc6fa87a4.png)

From Networking
No ability to join an existing vnet
![image](https://user-images.githubusercontent.com/942110/39838552-8d4c0924-538e-11e8-97fd-9c57b86cccf4.png)

From Monitoring
No ability to turn on Azure-Native monitoring
![image](https://user-images.githubusercontent.com/942110/39838631-c6b83b6a-538e-11e8-9e0f-bcf4acd5f5da.png)

From Tagging
No ability to create custom tags
![image](https://user-images.githubusercontent.com/942110/39838673-e22e04b0-538e-11e8-9967-311019361f59.png)

**Comment by westlywright** [comment]
@deniseschannon I'm going to expose the DNS Label to the UI because this already exists in the config but @nathan-jenan-rancher said we'd need updates to the api to support the remaining three.

**Comment by tfiduccia** [comment]
@deniseschannon - send to Nathan?

**Comment by deniseschannon** [comment]
Update as of 6/14
- [ ] DNS Prefix - Backend in, UI in?
- [ ] Join existing Resource Group - backend in, maybe add note UI to indicate if it's new or existing with notes on if existing AKS cluster is in resource group a new one will be created. needs testing
- [ ] join existing vnet - missing backend
- [ ] ability to turn on Azure-Native monitoring - missing backend
- [ ] ability to create custom tags - missing backend

**Comment by soumyalj** [comment]
DNS prefix has been verified. Virtual network and subnet fields are not exposed in UI.

**Comment by deniseschannon** [comment]
Update as of 6/17
- [x] DNS Prefix - Backend in, UI in

- [ ] Join existing Resource Group - backend in, UI -  add note to indicate it can be a new or existing resouce group, but a new one will be created if an AKS cluster is in an existing resource group as AKS only allows 1 AKS cluster per resource group. 
- [ ] join existing vnet - backend in, need UI


- [ ] ability to turn on Azure-Native monitoring - missing backend
- [ ] ability to create custom tags - - backend in, need UI

**Comment by deniseschannon** [comment]
I'm moving the azure-native monitoring and custom tags to another Issue: https://github.com/rancher/rancher/issues/14045

**Comment by westlywright** [comment]
I've added the note about resource groups as an info tooltip and vnet/subnet are under the networking radio now.

**Comment by deniseschannon** [comment]
@bmdepesa when testing the virtual network/subnet, can you see if those options exist for all k8s versions or only certain ones?

**Comment by nathan-jenan-rancher** [comment]
Looks like we are being affected by this change in the azure SDK.

https://github.com/Azure/azure-rest-api-specs/pull/2669

**Comment by soumyalj** [comment]
Tested with master build. Created EKS cluster with Virtual Network and subnet set. 
[The Virtual Network must exist within the Resource Group you are using for this cluster]
 AKS cluster was created successfully and was functional . DNS prefix added was also verified.
Clusters with different K8s versions and different regions were also deployed (1.9.6 and v1.10.3)

<img width="871" alt="screen shot 2018-06-21 at 4 07 31 pm" src="https://user-images.githubusercontent.com/18536626/41749771-3beaab20-756d-11e8-8bf2-b425b07ec408.png">
<img width="884" alt="screen shot 2018-06-21 at 4 08 19 pm" src="https://user-images.githubusercontent.com/18536626/41749804-589aad06-756d-11e8-8edd-cc5b772fadd5.png">

**Comment by mitchellmaler** [comment]
@soumyalj does this mean if the vnet is in a different resource group it wont work? Right now out vnet vpn back to corporate is in a different resource group but any AKS cluster we create will not be in the same.
