### ISSUE TITLE
Add Ingress won't allow "default" namespace

### ISSUE THREAD

**Issue by tboemker-bkfs** [rancher/rancher#13394]
I clicked on Workloads, then Add Ingress (under Load Balancing). In the Namespace field, I tried to choose default as an existing namespace, but it did't exist, so I tried to enter default as a new namespace. When I pressed Save, I saw this error:

namespaces "default" already exists.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`ingresses.run`|

**Comment by loganhz** [comment]
Hi @tboemker-bkfs , I can not reproduce this issue. 
Can you check if the `default` namespace is in another project ?

**Comment by tboemker-bkfs** [comment]
The default namespace was not in any project. (I don't know how that came to be.) With the default namespace in the Default project, the issue is resolved.

Thanks.
