### ISSUE TITLE
no way to remove template of adding-cluster of ec2

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#13404]
*Describe your issue here*

When the first time to create a cluster of ec2, I have to create a new node template. But later, I cannot find a way to delete the created templates.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.new`|

**Comment by tfiduccia** [comment]
@zhaoyao91 - To delete/edit a template you have to go to the right and click on the admin drop-down - there you will find the Node Templates option that will take you to the list and allow you delete.

![image](https://user-images.githubusercontent.com/11514927/39895694-039badf6-5460-11e8-9772-fbbbc8a7b12e.png)
