### ISSUE TITLE
Feature request:workload Deploy support adding serviceAccount

### ISSUE THREAD

**Issue by luzhongming** [rancher/rancher#13408]
*Describe your issue here*
currently rancher2.0 doesnt support setting serviceaccount when deploy workloads

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by loganhz** [comment]
@vincent99 will we support adding serviceAccount for workloads via UI?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/12754
