### ISSUE TITLE
Allow only external IP when registering custom node 

### ISSUE THREAD

**Issue by webts** [rancher/rancher#13403]
rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent: v2.0.0
Docker version 17.03.2-ce
Ubuntu 16.04.3 LTS

Currently when deploying rancher agent with `--address <external-ip>` flag on a host behind NAT InternalIP is still registered and preferred. This causes issues when other nodes are not on the same internal network.

is it / would it be possible to flag preferred IP or exclude specific host networks?

**Comment by loganhz** [comment]
Can you try `--internal-address 1.2.3.4`, please?

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
