### ISSUE TITLE
Alerts fire for actions that happened when it was muted then activated

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13414]
**Rancher versions:** 2.0 master 5/10

**Steps to Reproduce:**
1.  Create a pod alert
2.  Fire pod alert at least once
3.  Mute alert
4.  Create a couple of workloads (wait until they are active)
5.  Go back and unmute alert

**Results:**  Alert fires for pods that were created while alert was muted.  Alert should only fire for actions that happen when it's unmuted.

**Comment by zionwu** [comment]
@tfiduccia  
As I mentioned in this issue https://github.com/rancher/rancher/issues/13413, the alert is based on the condition but not the action.   

When the alert is muted,  it is still in alerting state, meaning that the condition is met. It will become active in 5 mins if during this 5 mins the condition is not observed.  If the condition is observed, the state is still alerting. So when alert is unmuted, it will still send out notification.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/15
Verified fixed
