### ISSUE TITLE
After alert fires, state should return to active and not stay on alerting

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13413]
**Rancher versions:** 2.0 master 5/10

**Steps to Reproduce:**
1.  Create a pod alert
2.  Create a workload so it fires

**Results:**  After the alert fires, the alert in the cluster alerts list always stays in Alerting and never goes back to active.
![image](https://user-images.githubusercontent.com/11514927/39887199-77dd14f8-5446-11e8-94fc-e3b3e327fd64.png)

**Comment by zionwu** [comment]
This is duplicate of issue https://github.com/rancher/rancher/issues/12922.

The event watcher received event even though no new event is created.

**Comment by zionwu** [comment]
@tfiduccia I can not reproduce this issue:
1. I created a alert for pod event.
![image](https://user-images.githubusercontent.com/1213386/39918280-93189524-5542-11e8-9aec-088eee5647bd.png)

2. I created a deployment workload
![image](https://user-images.githubusercontent.com/1213386/39918296-9dcc2dbe-5542-11e8-9a40-0542f70fded5.png)

3. I received two alerts and the alert became active.
![image](https://user-images.githubusercontent.com/1213386/39918309-a3b06114-5542-11e8-8c82-e44396be98ce.png)

If there is other pod creating or updating or restarting,  it may also trigger an event creation/update in k8s, so the alert will stay active.

Can you re-test and use `kubectl get event` to check if there is any pod getting updated/created?

**Comment by loganhz** [comment]
This issue is for 2.0.0. It should be fixed in master.

**Comment by tfiduccia** [comment]
Version - 2.2 master 2/28
I checked. The alert activated.  But the State for the Alert stays in "Alerting".   It doesn't change back to just Active.  There are no other pods being created or updating.
![image](https://user-images.githubusercontent.com/11514927/51867708-66547680-2309-11e9-9676-c7216c759927.png)

**Comment by aiwantaozi** [comment]
Hi Tani, these is a resolve time, after the resolve time if no new alert coming, the statue will back to active, the resolve time is 5 mins

**Comment by loganhz** [comment]
@aiwantaozi Could you provide the detailed test steps, please? So QA team can verify it

**Comment by tfiduccia** [comment]
@loganhz & @aiwantaozi - I tested and just wanted to make sure.  I'll close.  Thanks.
Verified fixed
