### ISSUE TITLE
Internal IP only option does not work - AWS

### ISSUE THREAD

**Issue by renantmagalhaes** [rancher/rancher#13416]
**Rancher versions:**
rancher/rancher 2.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-1052-aws
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Create a New Node Template
Select the option:  Use only private IP address under Instance Tab
Deploy a new cluster
**Results:**
```
2018/05/10 19:24:01 [INFO] stdout: Running pre-create checks...
2018/05/10 19:24:01 [INFO] stdout: Creating machine...
2018/05/10 19:24:01 [INFO] stdout: (worker-internal-1) Launching instance...
2018/05/10 19:24:27 [INFO] stdout: Waiting for machine to be running, this may take a few minutes...
2018/05/10 19:24:27 [INFO] stdout: Detecting operating system of created instance...
2018/05/10 19:24:27 [INFO] stdout: Waiting for SSH to be available...
2018/05/10 19:24:50 [INFO] stdout: Detecting the provisioner...
2018/05/10 19:24:50 [INFO] stdout: Provisioning with ubuntu(systemd)...
E0510 19:28:13.829915       1 generic_controller.go:204] ClusterRoleTemplateBindingController c-l8k6w/creator [mgmt-auth-crtb-controller] failed with : couldn't create role cluster-owner: roles.rbac.authorization.k8s.io "cluster-owner" already exists
2018-05-10 19:28:43.541003 I | mvcc: store.index: compact 39329
2018-05-10 19:28:43.543001 I | mvcc: finished scheduled compaction at 39329 (took 1.247482ms)
2018-05-10 19:33:43.545388 I | mvcc: store.index: compact 39863
2018-05-10 19:33:43.547086 I | mvcc: finished scheduled compaction at 39863 (took 847.483µs)
2018/05/10 19:33:57 [INFO] Running cluster events cleanup
2018/05/10 19:33:57 [INFO] Done running cluster events cleanup
```
Connecting via SSH in directly in the instance i dont see any process about rancher .. kubernetes .. or docker

Cluster is never created, and stays in this form forever.

I'm trying to achieve the same result as creating a custom cluster, with is the master and server communicate at internal ip only. Then i will expose my services using  ELB.

This way i will achieve a more secure enviroment, since i will not expose any port to 0.0.0.0

**Comment by tfiduccia** [comment]
@renantmagalhaes - For this to work your rancher server has to be in the same vpc as your cluster.  If not rancher cannot ssh into the machines.

**Comment by renantmagalhaes** [comment]
Hello !

Hi all ! I'm stuck in deploying an enviroment using internal ip only in AWS ... i already done it using a old VPC .. but when i try to reproduce in a fresh new VPC the master shows
```INFO] stdout: Provisioning with ubuntu(systemd)``` 
I'm using the same VPC and the same SG but only exposing all INBOUND all traffic to the SG and the internal IP Range ... if i choose to make a default cluster using public ips and default rancher-node Security group it works .... seems to be a AWS configuration becouse it worked in a old VPC .... but i cannot be sure!!

I can reach the cluster via SSH from the master

**Comment by renantmagalhaes** [comment]
I find that was my VPC config after all messing with the deploy.

Tks

**Comment by shitalp** [comment]
Hi renantmagalhaes,
Can u  please tell me what u did. I am facing same issue.

**Comment by renantmagalhaes** [comment]
> Hi renantmagalhaes,
> Can u please tell me what u did. I am facing same issue.

Hi @shitalp that was too long ago, i dont remember what happened there, i`m using EKS now on my kubernetes deployments. But check VPC and subnet rules together with the security groups, its probably something silly that`s messing you environment.

**Comment by Caldas** [comment]
Hey @renantmagalhaes I'm also facing same issue here where my cluster creation stuck at `Provisioning with ubuntu(systemd)...` when I'm using the option to create using only private IP.

I've my security group open to all ports incoming and outgoing and VPC is the aws default one.

Do you have any tips?

**Comment by renantmagalhaes** [comment]
@Caldas, My tip is:
First use a brand new VPC with public only subnets, inside this subnets make sure the table route are open to all internal traffic, and put all ports incoming and outgoing traffic, if this works, you can start closing more and more your settings
