### ISSUE TITLE
[cli] --wait-timeout does not work

### ISSUE THREAD

**Issue by rv-cdiaz** [rancher/rancher#13417]
**Rancher versions:**
rancher/server or rancher/rancher:
v1.6.16
Cli Version v0.6.8

**Steps to Reproduce:**
rancher --wait --wait-timeout 60 --wait-state active up --stack rancher-api --pull -d --force-upgrade --batch-size 2 --interval 1000

**Results:**
I purposefully am deploying a stack with a bad health check trying to make this command timeout after 60 seconds. A usual deployments completes in 10-20 seconds. I have tried twice and waited a full 10 minutes as well. I have also tried removing the timeout to just settle for 10 minutes. This command is not timing out. Maybe this is conflicting with the state?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
