### ISSUE TITLE
Can not remove answer when upgrade catalog app

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13411]
rancher/rancher:master

Steps to reproduce:

If users deployed a catalog of Helm stable with some custom answers in Rancher.
Then users can not remove any answers when upgrade the app.

UI can not remove answer via `upgrade` action.

**Comment by StrongMonkey** [comment]
@loganhz Does posting a different answer field work now? I believe we don't prevent deleting answers so if you want to delete them you just post a different map.

**Comment by loganhz** [comment]
Hi @StrongMonkey , it doesn't work in rancher/rancher:master. 
I'm using artifactory app from Helm Incubator. 

Note:
UI is using the `upgrade` action if you upgrade catalog app in UI.

![image](https://user-images.githubusercontent.com/21168270/40569632-eb389942-60b5-11e8-99e0-279b26d29a1f.png)
![image](https://user-images.githubusercontent.com/21168270/40569673-4e63e62a-60b6-11e8-9f5b-85b0de23220a.png)

**Comment by sangeethah** [comment]
Tested with latest build from master.

Able to remove answers when upgrading an application.
The removed answers are not present in the application anymore (in the API as well).
