### ISSUE TITLE
Can't click on menu options for Pods

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13419]
**Rancher versions:** 2.0 master 5/10

**Steps to Reproduce:**
1.  Create a workload, wait for it to become active
2.  Hover over pod
3.  Click on menu
4.  Now try to click on one of the menu options

**Results:**  As soon I try to get to get to the menu, it disappears.  The drop-down is too low as well.
![image](https://user-images.githubusercontent.com/11514927/39895859-c0489018-5460-11e8-94e7-949941d71904.png)

**Comment by loganhz** [comment]
another dropdown issue might be related https://github.com/rancher/rancher/issues/13453

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/15
Verified fixed
