### ISSUE TITLE
Ability to mark RoleTemplates as "protected" or "hidden"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#13418]
Ability to mark RoleTemplates as "protected" or "hidden" so only global admins can see them or assign them to a user.

Note: We cannot actually delete the role because we ensure it exists when we start rancher. We would just recreate it if it was deleted upon a restart/upgrade.

**Comment by vincent99** [comment]
There's already a `hidden` field, but it's only used to hide things in the UI and not enforced by anything now.

**Comment by nathan-jenan-rancher** [comment]
Note as this feature was implemented when a role is marked "disabled" then no user, not even global admin, will be able to assign it to a user.

**Comment by deniseschannon** [comment]
The API has added ability to set whether or not any role is "enabled" or not with a setting: `enable: true`.

**Comment by deniseschannon** [comment]
UI is in master but not in v2.0.1-rc2

**Comment by sangeethah** [comment]
@vincent99 @westlywright I don't see UI have support for the enabled flag when testing with latest master builds.

**Comment by sangeethah** [comment]
Tested with latest build from master.
We have the ability to lock build-in role templates using edit option now. 
1 related issue  - https://github.com/rancher/rancher/issues/13600
