### ISSUE TITLE
[RFE] provide the ability to set host entries in resolv.conf for infra stacks

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#13428]
Having an issue where one environment is deployed in a datacenter that cant resolve the rancher servers fqdn. DNS servers are outside of control. If agents were deployed with `--add-host` helps with getting the agent up and running and connecting back to the server. The issue then moves to the infrastructure stacks.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
