### ISSUE TITLE
Unable to create cluster using Rackspace node driver

### ISSUE THREAD

**Issue by gravityforall** [rancher/rancher#13427]
**Rancher versions:**
CATTLE_UI_VERSION = 2.0.41
CATTLE_CLI_VERSION = v2.0.0
CATTLE_SERVER_VERSION = v2.0.0
CATTLE_AGENT_IMAGE = rancher/rancher-agent:v2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-119-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Rackspace/OpenStack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
1. Enable Rackspace node driver
2. Click 'Add Cluster'
3. Select Rackspace driver
4. Enter 'Name Prefix'
5. Click 'Add Node Template'
6. Fill out form and click 'Create'

**Results:**
Error message 'Name is required'

<img width="1440" alt="screen shot 2018-05-10 at 6 42 54 pm" src="https://user-images.githubusercontent.com/1358859/39902879-2d752902-5485-11e8-82dd-9fc417960385.png">

<img width="1440" alt="screen shot 2018-05-10 at 6 42 35 pm" src="https://user-images.githubusercontent.com/1358859/39902883-30c3a354-5485-11e8-8959-4721f63d7994.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Verified fixed
