### ISSUE TITLE
Tls timeout error when import a exists cluster to rancher

### ISSUE THREAD

**Issue by hyr0403** [rancher/rancher#13429]
*Describe your issue here*
Found many error about TLS handshake timeout
rancher v2.0.0
action: import a exists k8s cluster

192.168.254.1 is k8s cluster IP
Please help

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`global-admin.clusters.index`|
![image](https://user-images.githubusercontent.com/11485468/39907299-68a7c24c-551a-11e8-90ad-f3f1583a7f36.png)

E0511 03:43:30.759562       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1beta2.StatefulSet: Get https://192.168.254.1:443/apis/apps/v1beta2/watch/statefulsets?resourceVersion=101104&timeoutSeconds=471: net/http: TLS handshake timeout
E0511 03:43:30.854789       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.ClusterRoleBinding: Get https://192.168.254.1:443/apis/rbac.authorization.k8s.io/v1/watch/clusterrolebindings?resourceVersion=167510&timeoutSeconds=442: net/http: TLS handshake timeout
E0511 03:43:30.901074       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1beta1.Ingress: Get https://192.168.254.1:443/apis/extensions/v1beta1/watch/ingresses?resourceVersion=1&timeoutSeconds=312: net/http: TLS handshake timeout
E0511 03:43:30.948119       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1beta1.CronJob: Get https://192.168.254.1:443/apis/batch/v1beta1/watch/cronjobs?resourceVersion=1&timeoutSeconds=349: net/http: TLS handshake timeout
E0511 03:43:30.995012       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1beta1.PodSecurityPolicy: Get https://192.168.254.1:443/apis/extensions/v1beta1/watch/podsecuritypolicies?resourceVersion=1&timeoutSeconds=571: net/http: TLS handshake timeout
E0511 03:43:31.042563       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1beta2.DaemonSet: Get https://192.168.254.1:443/apis/apps/v1beta2/watch/daemonsets?resourceVersion=172265&timeoutSeconds=339: net/http: TLS handshake timeout
E0511 03:43:31.090375       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1beta2.Deployment: Get https://192.168.254.1:443/apis/apps/v1beta2/watch/deployments?resourceVersion=172174&timeoutSeconds=327: net/http: TLS handshake timeout
E0511 03:43:31.186482       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Secret: Get https://192.168.254.1:443/api/v1/watch/secrets?resourceVersion=172130&timeoutSeconds=540: net/http: TLS handshake timeout
E0511 03:43:31.234791       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.ClusterRole: Get https://192.168.254.1:443/apis/rbac.authorization.k8s.io/v1/watch/clusterroles?resourceVersion=167503&timeoutSeconds=440: net/http: TLS handshake timeout
E0511 03:43:31.280441       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Endpoints: Get https://192.168.254.1:443/api/v1/watch/endpoints?resourceVersion=172303&timeoutSeconds=386: net/http: TLS handshake timeout
E0511 03:43:31.329789       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1beta2.ReplicaSet: Get https://192.168.254.1:443/apis/apps/v1beta2/watch/replicasets?resourceVersion=172173&timeoutSeconds=429: net/http: TLS handshake timeout
E0511 03:43:31.382771       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Event: Get https://192.168.254.1:443/api/v1/watch/events?resourceVersion=172303&timeoutSeconds=404: net/http: TLS handshake timeout
E0511 03:43:31.427791       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Node: Get https://192.168.254.1:443/api/v1/watch/nodes?resourceVersion=172300&timeoutSeconds=389: net/http: TLS handshake timeout
E0511 03:43:31.477488       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Pod: Get https://192.168.254.1:443/api/v1/watch/pods?resourceVersion=172268&timeoutSeconds=410: net/http: TLS handshake timeout
E0511 03:43:31.522896       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.ReplicationController: Get https://192.168.254.1:443/api/v1/watch/replicationcontrollers?resourceVersion=81552&timeoutSeconds=321: net/http: TLS handshake timeout
E0511 03:43:31.570099       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.RoleBinding: Get https://192.168.254.1:443/apis/rbac.authorization.k8s.io/v1/watch/rolebindings?resourceVersion=161503&timeoutSeconds=565: net/http: TLS handshake timeout
E0511 03:43:31.617061       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Namespace: Get https://192.168.254.1:443/api/v1/watch/namespaces?resourceVersion=161508&timeoutSeconds=382: net/http: TLS handshake timeout
E0511 03:43:31.664423       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Service: Get https://192.168.254.1:443/api/v1/watch/services?resourceVersion=104180&timeoutSeconds=520: net/http: TLS handshake timeout
E0511 03:43:31.711791       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.ServiceAccount: Get https://192.168.254.1:443/api/v1/watch/serviceaccounts?resourceVersion=161504&timeoutSeconds=448: net/http: TLS handshake timeout
E0511 03:43:31.758388       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Job: Get https://192.168.254.1:443/apis/batch/v1/watch/jobs?resourceVersion=1&timeoutSeconds=412: net/http: TLS handshake timeout
E0511 03:43:31.805905       1 reflector.go:315] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:129: Failed to watch *v1.Role: Get https://192.168.254.1:443/apis/rbac.authorization.k8s.io/v1/watch/roles?resourceVersion=83550&timeoutSeconds=443: net/http: TLS handshake timeout
E0511 03:43:31.856303       1 generic_controller.go:204] ClusterAlertController c-fvnr8/clusteralert-controllermanager [cluster-alert-deployer] failed with : Delete https://192.168.254.1:443/api/v1/namespaces/cattle-alerting: net/http: TLS handshake timeout
E0511 03:43:31.856526       1 generic_controller.go:204] ProjectAlertController project-mhms4/projectalert-workload [project-alert-deployer] failed with : Delete https://192.168.254.1:443/api/v1/namespaces/cattle-alerting: net/http: TLS handshake timeout
E0511 03:43:31.857319       1 generic_controller.go:204] ProjectRoleTemplateBindingController project-mhms4/creator [cluster-prtb-sync] failed with : Post https://192.168.254.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: program: error updating network policy err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: handleHostNetwork: error programming hostNetwork network policy for ns=default err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: program: error updating network policy err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/np-nginx-rac-nodeport: net/http: TLS handshake timeout
E0511 03:43:31.857407       1 generic_controller.go:204] ClusterAlertController c-fvnr8/clusteralert-scheduler [cluster-alert-deployer] failed with : Delete https://192.168.254.1:443/api/v1/namespaces/cattle-alerting: net/http: TLS handshake timeout
E0511 03:43:31.857540       1 generic_controller.go:204] ClusterAlertController c-fvnr8/clusteralert-node-mem [cluster-alert-deployer] failed with : Delete https://192.168.254.1:443/api/v1/namespaces/cattle-alerting: net/http: TLS handshake timeout
E0511 03:43:31.857603       1 generic_controller.go:204] ClusterAlertController c-fvnr8/clusteralert-etcd [cluster-alert-deployer] failed with : Delete https://192.168.254.1:443/api/v1/namespaces/cattle-alerting: net/http: TLS handshake timeout
E0511 03:43:31.857762       1 generic_controller.go:204] ClusterRoleTemplateBindingController c-fvnr8/creator [cluster-crtb-sync] failed with : couldn't ensure cluster bindings &{{} {ClusterRoleTemplateBinding management.cattle.io/v3} {creator  c-fvnr8 /apis/management.cattle.io/v3/namespaces/c-fvnr8/clusterroletemplatebindings/creator 3a1a2543-54cd-11e8-b70a-02420afefe02 1082524 0 2018-05-11 03:41:45 +0000 UTC <nil> <nil> map[] map[authz.management.cattle.io/creator-owner-binding:true lifecycle.cattle.io/create.mgmt-auth-crtb-controller:true] [] nil [controller.cattle.io/mgmt-auth-crtb-controller clusterscoped.controller.cattle.io/cluster-crtb-sync_c-fvnr8] } user-mjqx6    c-fvnr8 cluster-owner}: Post https://192.168.254.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: net/http: TLS handshake timeout
E0511 03:43:31.858220       1 generic_controller.go:204] ProjectController c-fvnr8/project-mhms4 [project-namespace-auth] failed with : Post https://192.168.254.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles: net/http: TLS handshake timeout
E0511 03:43:31.858347       1 generic_controller.go:204] ClusterRoleTemplateBindingController c-fvnr8/user-qzx7b-admin [cluster-crtb-sync] failed with : couldn't ensure cluster bindings &{{} {ClusterRoleTemplateBinding management.cattle.io/v3} {user-qzx7b-admin  c-fvnr8 /apis/management.cattle.io/v3/namespaces/c-fvnr8/clusterroletemplatebindings/user-qzx7b-admin 6109c128-54cd-11e8-b70a-02420afefe02 1082635 0 2018-05-11 03:42:50 +0000 UTC <nil> <nil> map[] map[lifecycle.cattle.io/create.mgmt-auth-crtb-controller:true] [] nil [controller.cattle.io/mgmt-auth-crtb-controller clusterscoped.controller.cattle.io/cluster-crtb-sync_c-fvnr8] } user-qzx7b    c-fvnr8 cluster-owner}: Post https://192.168.254.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: net/http: TLS handshake timeout
E0511 03:43:31.858504       1 generic_controller.go:204] ClusterAlertController c-fvnr8/clusteralert-deploment-event [cluster-alert-deployer] failed with : Delete https://192.168.254.1:443/api/v1/namespaces/cattle-alerting: net/http: TLS handshake timeout
E0511 03:43:31.858682       1 generic_controller.go:204] ServiceController default/nginx-rac-nodeport [serviceHandler] failed with : Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/np-nginx-rac-nodeport: net/http: TLS handshake timeout
E0511 03:43:31.858758       1 generic_controller.go:204] NodeController kaka-3 [nodesEndpointsController] failed with : Put https://192.168.254.1:443/api/v1/nodes/kaka-3: net/http: TLS handshake timeout
E0511 03:43:31.858898       1 generic_controller.go:204] NodeController kaka-2 [nodesEndpointsController] failed with : Put https://192.168.254.1:443/api/v1/nodes/kaka-2: net/http: TLS handshake timeout
E0511 03:43:31.859153       1 generic_controller.go:204] NodeController kaka-1 [nodesEndpointsController] failed with : Put https://192.168.254.1:443/api/v1/nodes/kaka-1: net/http: TLS handshake timeout
E0511 03:43:31.860138       1 generic_controller.go:204] ClusterPipelineController c-fvnr8/c-fvnr8 [cluster-pipeline-syncer] failed with : Delete https://192.168.254.1:443/api/v1/namespaces/cattle-pipeline: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: program: error updating network policy err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: handleHostNetwork: error programming hostNetwork network policy for ns=default err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: program: error updating network policy err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: handleHostNetwork: error programming hostNetwork network policy for ns=default err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: program: error updating network policy err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: handleHostNetwork: error programming hostNetwork network policy for ns=default err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: program: error updating network policy err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:31 [ERROR] netpolMgr: handleHostNetwork: error programming hostNetwork network policy for ns=default err=Put https://192.168.254.1:443/apis/networking.k8s.io/v1/namespaces/default/networkpolicies/hn-nodes: net/http: TLS handshake timeout
2018/05/11 03:43:32 [INFO] Updating node [kaka-3] with public endpoints [[{"nodeName":"c-fvnr8:machine-f6dx2","addresses":["10.201.108.2"],"port":32201,"protocol":"TCP","serviceName":"default:nginx-rac-nodeport","allNodes":true}]]
2018/05/11 03:43:32 [INFO] Updating node [kaka-2] with public endpoints [[{"nodeName":"c-fvnr8:machine-ddfjv","addresses":["10.201.107.2"],"port":32201,"protocol":"TCP","serviceName":"default:nginx-rac-nodeport","allNodes":true}]]
2018/05/11 03:43:32 [INFO] Updating node [kaka-1] with public endpoints [[{"nodeName":"c-fvnr8:machine-dqhcc","addresses":["10.201.106.2"],"port":32201,"protocol":"TCP","serviceName":"default:nginx-rac-nodeport","allNodes":true}]]
2018/05/11 03:43:36 [INFO] Updating node [kaka-3] with public endpoints [[{"nodeName":"c-fvnr8:machine-f6dx2","addresses":["10.201.108.2"],"port":32201,"protocol":"TCP","serviceName":"default:nginx-rac-nodeport","allNodes":true}]]
2018/05/11 03:43:36 [INFO] Updating node [kaka-2] with public endpoints [[{"nodeName":"c-fvnr8:machine-ddfjv","addresses":["10.201.107.2"],"port":32201,"protocol":"TCP","serviceName":"default:nginx-rac-nodeport","allNodes":true}]]
2018/05/11 03:43:36 [INFO] Updating node [kaka-1] with public endpoints [[{"nodeName":"c-fvnr8:machine-dqhcc","addresses":["10.201.106.2"],"port":32201,"protocol":"TCP","serviceName":"default:nginx-rac-nodeport","allNodes":true}]]
E0511 03:44:48.809116       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.AlertStatus

**Comment by loganhz** [comment]
Can you try the latest Rancher version, please?

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
