### ISSUE TITLE
Ability to add same user multiple times to site access and cluster.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13422]
**Rancher versions:**
Master 5/10/18

Steps:
Enable AD Auth.
Set site access to "Allow members of Clusters, Projects, plus Authorized Users and Organizations"
Add a user as to authorized user list.
Add same member. 

Results:
![screen shot 2018-05-10 at 3 08 09 pm](https://user-images.githubusercontent.com/38012481/39896781-6cdfb11e-5464-11e8-95ff-b61ab876b86b.png)

Note: This also occurs at the cluster level .
![screen shot 2018-05-10 at 3 09 45 pm](https://user-images.githubusercontent.com/38012481/39896785-71120480-5464-11e8-8234-f28b9f51807a.png)

**Comment by deniseschannon** [comment]
@mrajashree could you see if this can be fixed generically? or will it be per auth provider?

**Comment by adingilloRancher** [comment]
This is still occurring on the cluster and project level.

**Comment by cjellick** [comment]
In my opinion, it it is not a bug at the project and cluster level. It follows the k8s paradigm for roles and role bindings. It is what k8s users are familiar with. A user can be assigned multiple roles in a project or cluster. Their permissions are the union of all the roles theyve been assigned.

**Comment by adingilloRancher** [comment]
Per @cjellick  and @tfiduccia . Not a bug.
