### ISSUE TITLE
Ingress doesn't work with kubernetes service as type 'ClusterIP' across projects

### ISSUE THREAD

**Issue by wmolyneux** [rancher/rancher#13436]
Given I have an Traefik deployed as an ingress controller looking at all namespaces in Kubernetes. When I have multiple Rancher projects with namespaces containing services in them, of type 'ClusterIP', they will not route via Traefik. If i set the services to be of type 'NodePort' then they are accessible via Traefik. If i leave them of type 'ClusterIP' and move the namespace containing the service into the same project that Traefik is deployed then they are also reachable via Traefik.

Rancher version is: v2.0.0

**Comment by gaui** [comment]
How did you manage to switch out the nginx ingress on Rancher for Træfik? I'm unable to do so.

**Comment by wmolyneux** [comment]
I have deployed Traefik as a DaemonSet in Kubernetes and configured it to use the Kubernetes backend which allows it to be an Ingress Controller

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
