### ISSUE TITLE
Wrong requested memory api report

### ISSUE THREAD

**Issue by sasah** [rancher/rancher#13437]
**Rancher versions:**
rancher/rancher: v2.0.0
rancher/rancher-agent: v2.0.0

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**

>  docker version
> Client:
>  Version:      17.03.2-ce
>  API version:  1.27
>  Go version:   go1.7.5
>  Git commit:   f5ec1e2
>  Built:        Tue Jun 27 03:35:14 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.03.2-ce
>  API version:  1.27 (minimum version 1.12)
>  Go version:   go1.7.5
>  Git commit:   f5ec1e2
>  Built:        Tue Jun 27 03:35:14 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

> docker version
> Client:
>  Version:      17.03.2-ce
>  API version:  1.27
>  Go version:   go1.7.5
>  Git commit:   f5ec1e2
>  Built:        Tue Jun 27 03:35:14 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.03.2-ce
>  API version:  1.27 (minimum version 1.12)
>  Go version:   go1.7.5
>  Git commit:   f5ec1e2
>  Built:        Tue Jun 27 03:35:14 2017
>  OS/Arch:      linux/amd64
>  Experimental: false
> root@farm10:~# docker info
> Containers: 22
>  Running: 11
>  Paused: 0
>  Stopped: 11
> Images: 17
> Server Version: 17.03.2-ce
> Storage Driver: overlay2
>  Backing Filesystem: xfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
> runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
> init version: 949e6fa
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.4.0-124-generic
> Operating System: Ubuntu 16.04.4 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 7.7 GiB
> Name: farm10
> ID: QB5Z:UBIT:HT5G:J3MV:M4SM:ICZC:GHS2:ASNA:DRJJ:QI5Z:T245:NVDD
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

> root@farm10:~# cat /etc/os-release
> NAME="Ubuntu"
> VERSION="16.04.4 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.4 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial

> root@farm10:~# uname -r
> 4.4.0-124-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

```
> kubectl describe node farm10
Name:               farm10
Roles:              worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=farm10
                    node-role.kubernetes.io/worker=true
Annotations:        field.cattle.io/publicEndpoints=[{"nodeName":"c-9v24l:m-4e04d70146e1","addresses":["xxx"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-t7wzx","allNodes":false},...
                    flannel.alpha.coreos.com/backend-data={"VtepMAC":"7e:85:e4:bd:f9:2b"}
                    flannel.alpha.coreos.com/backend-type=vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager=true
                    flannel.alpha.coreos.com/public-ip=xxx
                    node.alpha.kubernetes.io/ttl=0
                    rke.cattle.io/external-ip=xxx
                    rke.cattle.io/internal-ip=xxx
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             <none>
CreationTimestamp:  Fri, 11 May 2018 12:49:16 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Fri, 11 May 2018 16:09:35 +0000   Fri, 11 May 2018 15:36:50 +0000   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Fri, 11 May 2018 16:09:35 +0000   Fri, 11 May 2018 15:36:50 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 11 May 2018 16:09:35 +0000   Fri, 11 May 2018 15:36:50 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 11 May 2018 16:09:35 +0000   Fri, 11 May 2018 12:49:16 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Fri, 11 May 2018 16:09:35 +0000   Fri, 11 May 2018 15:37:00 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  xxx
  Hostname:    farm10
Capacity:
 cpu:                4
 ephemeral-storage:  975256792Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             8073540Ki
 pods:               110
Allocatable:
 cpu:                4
 ephemeral-storage:  898796658020
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             7971140Ki
 pods:               110
System Info:
 Machine ID:                 8c859f2bde9e41155bca40d2d85aebb5
 System UUID:                05D00CAE-FD16-11E6-A198-98EECB615123
 Boot ID:                    74ea4cb1-afa7-4191-ad9c-230cf84ae5db
 Kernel Version:             4.4.0-124-generic
 OS Image:                   Ubuntu 16.04.4 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://17.3.2
 Kubelet Version:            v1.10.1
 Kube-Proxy Version:         v1.10.1
PodCIDR:                     10.42.2.0/24
ExternalID:                  farm10
Non-terminated Pods:         (3 in total)
  Namespace                  Name                              CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                              ------------  ----------  ---------------  -------------
  cattle-system              cattle-node-agent-f2d78           0 (0%)        0 (0%)      0 (0%)           0 (0%)
  ingress-nginx              nginx-ingress-controller-t7wzx    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                canal-r9bb9                       250m (6%)     0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  250m (6%)     0 (0%)      0 (0%)           0 (0%)
Events:
  Type     Reason                   Age                From                Message
  ----     ------                   ----               ----                -------
  Normal   Starting                 32m                kubelet, farm10     Starting kubelet.
  Normal   NodeHasSufficientDisk    32m (x2 over 32m)  kubelet, farm10     Node farm10 status is now: NodeHasSufficientDisk
  Normal   NodeHasSufficientMemory  32m (x2 over 32m)  kubelet, farm10     Node farm10 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    32m (x2 over 32m)  kubelet, farm10     Node farm10 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     32m                kubelet, farm10     Node farm10 status is now: NodeHasSufficientPID
  Warning  Rebooted                 32m                kubelet, farm10     Node farm10 has been rebooted, boot id: 74ea4cb1-afa7-4191-ad9c-230cf84ae5db
  Normal   NodeNotReady             32m                kubelet, farm10     Node farm10 status is now: NodeNotReady
  Normal   Starting                 32m                kube-proxy, farm10  Starting kube-proxy.
  Normal   NodeAllocatableEnforced  32m                kubelet, farm10     Updated Node Allocatable limit across pods
  Normal   NodeReady                32m                kubelet, farm10     Node farm10 status is now: NodeReady
>

```

> CPU Requests  CPU Limits  Memory Requests  Memory Limits
>   ------------  ----------  ---------------  -------------
>   250m (6%)     0 (0%)      0 (0%)           0 (0%)

**Results:**

View in API:

https://host/v3/nodes/c-9v24l:m-4e04d70146e1

> {
> "actions": { },
> "allocatable": {
> "cpu": "4",
> "ephemeral-storage": "898796658020",
> "hugepages-1Gi": "0",
> "hugepages-2Mi": "0",
> "memory": "7971140Ki",
> "pods": "110"
> },
> "annotations": {
> "flannel.alpha.coreos.com/backend-data": "{\"VtepMAC\":\"7e:85:e4:bd:f9:2b\"}",
> "flannel.alpha.coreos.com/backend-type": "vxlan",
> "flannel.alpha.coreos.com/kube-subnet-manager": "true",
> "flannel.alpha.coreos.com/public-ip": "xxx",
> "node.alpha.kubernetes.io/ttl": "0",
> "rke.cattle.io/external-ip": "xxx",
> "rke.cattle.io/internal-ip": "xxx",
> "volumes.kubernetes.io/controller-managed-attach-detach": "true"
> },
> "baseType": "node",
> "capacity": {
> "cpu": "4",
> "ephemeral-storage": "975256792Ki",
> "hugepages-1Gi": "0",
> "hugepages-2Mi": "0",
> "memory": "8073540Ki",
> "pods": "110"
> },
> "clusterId": "c-9v24l",
> "conditions": [ 8 items
> {
> "status": "True",
> "type": "Initialized"
> },
> {
> "message": "registered with kubernetes",
> "status": "True",
> "type": "Registered"
> },
> {
> "status": "True",
> "type": "Provisioned"
> },
> {
> "lastHeartbeatTime": "2018-05-11T15:37:10Z",
> "lastHeartbeatTimeTS": 1526053030000,
> "lastTransitionTime": "2018-05-11T15:36:50Z",
> "lastTransitionTimeTS": 1526053010000,
> "message": "kubelet has sufficient disk space available",
> "reason": "KubeletHasSufficientDisk",
> "status": "False",
> "type": "OutOfDisk"
> },
> {
> "lastHeartbeatTime": "2018-05-11T15:37:10Z",
> "lastHeartbeatTimeTS": 1526053030000,
> "lastTransitionTime": "2018-05-11T15:36:50Z",
> "lastTransitionTimeTS": 1526053010000,
> "message": "kubelet has sufficient memory available",
> "reason": "KubeletHasSufficientMemory",
> "status": "False",
> "type": "MemoryPressure"
> },
> {
> "lastHeartbeatTime": "2018-05-11T15:37:10Z",
> "lastHeartbeatTimeTS": 1526053030000,
> "lastTransitionTime": "2018-05-11T15:36:50Z",
> "lastTransitionTimeTS": 1526053010000,
> "message": "kubelet has no disk pressure",
> "reason": "KubeletHasNoDiskPressure",
> "status": "False",
> "type": "DiskPressure"
> },
> {
> "lastHeartbeatTime": "2018-05-11T15:37:10Z",
> "lastHeartbeatTimeTS": 1526053030000,
> "lastTransitionTime": "2018-05-11T12:49:16Z",
> "lastTransitionTimeTS": 1526042956000,
> "message": "kubelet has sufficient PID available",
> "reason": "KubeletHasSufficientPID",
> "status": "False",
> "type": "PIDPressure"
> },
> {
> "lastHeartbeatTime": "2018-05-11T15:37:10Z",
> "lastHeartbeatTimeTS": 1526053030000,
> "lastTransitionTime": "2018-05-11T15:37:00Z",
> "lastTransitionTimeTS": 1526053020000,
> "message": "kubelet is posting ready status",
> "reason": "KubeletReady",
> "status": "True",
> "type": "Ready"
> }
> ],
> "controlPlane": false,
> "created": "2018-05-11T12:48:54Z",
> "createdTS": 1526042934000,
> "creatorId": null,
> "customConfig": {
> "address": "xxx",
> "type": "/v3/schemas/customConfig"
> },
> "dockerInfo": {
> "debug": false,
> "experimentalBuild": false,
> "type": "/v3/schemas/dockerInfo"
> },
> "etcd": false,
> "externalIpAddress": "xxx",
> "hostname": "farm10",
> "id": "c-9v24l:m-4e04d70146e1",
> "imported": true,
> "info": {
> "cpu": {
> "count": 4
> },
> "kubernetes": {
> "kubeProxyVersion": "v1.10.1",
> "kubeletVersion": "v1.10.1"
> },
> "memory": {
> "memTotalKiB": 8073540
> },
> "os": {
> "dockerVersion": "17.3.2",
> "kernelVersion": "4.4.0-124-generic",
> "operatingSystem": "Ubuntu 16.04.4 LTS"
> }
> },
> "ipAddress": "xxx",
> "labels": {
> "beta.kubernetes.io/arch": "amd64",
> "beta.kubernetes.io/os": "linux",
> "kubernetes.io/hostname": "farm10",
> "node-role.kubernetes.io/worker": "true"
> },
> "limits": {
> "cpu": "1500m",
> "memory": "3500M"
> },
> "links": {
> "remove": "…/v3/nodes/c-9v24l:m-4e04d70146e1",
> "self": "…/v3/nodes/c-9v24l:m-4e04d70146e1",
> "update": "…/v3/nodes/c-9v24l:m-4e04d70146e1"
> },
> "name": "",
> "namespaceId": null,
> "nodeName": "farm10",
> "nodePoolId": "",
> "nodeTemplateId": null,
> "podCidr": "10.42.2.0/24",
> "publicEndpoints": [ 2 items
> {
> "addresses": [
> "xxx"
> ],
> "allNodes": false,
> "ingressId": null,
> "nodeId": "c-9v24l:m-4e04d70146e1",
> "podId": null,
> "port": 80,
> "protocol": "TCP",
> "serviceId": null
> },
> {
> "addresses": [
> "xxx"
> ],
> "allNodes": false,
> "ingressId": null,
> "nodeId": "c-9v24l:m-4e04d70146e1",
> "podId": null,
> "port": 443,
> "protocol": "TCP",
> "serviceId": null
> }
> ],
> "requested": {
> "cpu": "250m",
> "memory": "3500M",
> "pods": "3"
> },
> "requestedHostname": "farm10",
> "sshUser": "root",
> "state": "active",
> "transitioning": "no",
> "transitioningMessage": "",
> "type": "node",
> "unschedulable": false,
> "uuid": "a9d92c18-5519-11e8-9aab-0242ac110003",
> "worker": true
> }

> "requested": {
> "cpu": "250m",
> "memory": "3500M",
> "pods": "3"
> },
> 

Why: "memory": "**3500M**" ?

**Comment by niranjan94** [comment]
I can confirm this error on my clusters too. 

<img width="426" alt="screen shot 2018-05-13 at 3 35 19 pm" src="https://user-images.githubusercontent.com/2404372/39966076-544a907c-56c3-11e8-860e-97bb4c38273e.png">

The CPU & Memory stats are stuck at the above value. 

---

**Additional info:**

**Node:** `Rancher OS v1.3.0`
**rancher/rancher:** `v2.0.0`
**rancher/rancher-agent:** `v2.0.0`
**kubernetes:** `v1.10.1`

**Comment by gkTim** [comment]
On my system it is also stucked to this value. I have DO Droplets and rancher OS 1.2.0.

**Comment by superseb** [comment]
The stats are requested resources, not actual usage on the machine. Pods requested resources.

If this is not working properly, please provide data to reproduce so we can investigate.

**Comment by gkTim** [comment]
Okay, good to know. Then it's working as expected.
It is planed to add the actual usage on the ui?

**Comment by superseb** [comment]
See here: https://github.com/rancher/rancher/issues/14230

Closing this, let me know if there is still a problem here.
