### ISSUE TITLE
Add unique user ID attribute to AD configuration

### ISSUE THREAD

**Issue by simpss** [rancher/rancher#13434]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
AD Authentication configured. Everything else doesn't come into play here.

**Steps to Reproduce:**
Set up AD authentication. Currently there is no way to use name/email as login, but keep track of the user, including permissions, with an AD unique ID. Rancher should allow the administrator to configure a unique ID attribute, that will be used to actually keep track of the user.

**Results:**
As there is currently no way to specify a unique user ID attribute, permissions are re-used when there is a naming clash with account names and permissions are not re-used when the identifying property is changed.

use-cases:
- user is named "jane.doe", marries and the `sAMAccountName` is changed to "jane.smith". For rancher, this looks like a new account, although `objectGUID` property stays the same. All permissions are lost.
- user is named "jane.doe", leaves the company. 4 years later another "Jane Doe" joins the company and their new account `sAMAccountName` attribute is "jane.doe". All permissions are re-used and the new "jane.doe" has access to more than they should, although it's a different object in AD.
- user is named "jane.doe", leaves the company. 4 years later joins again on a new contract. A new account is created, `sAMAccountName` "jane.doe", different `objectGUID`. The user will re-gain old permissions, that they shouldn't have.

Obviously, one could set up the `loginAttribute` to be `objectGUID` instead of `sAMAccountName`, but that will mean the users need to know their `objectGUID` to log in, which is not optimal. 

So, the `loginAttribute` is only unique in any given time, but is not guaranteed to be unique over the lifetime of the service.

An example on how Atlassian has sorted this can be seen here: https://confluence.atlassian.com/adminjiraserver071/connecting-to-an-ldap-directory-802592350.html
The property in question is "User Unique ID Attribute"

**Comment by cjellick** [comment]
Thanks for the bug report. I agree with what you've said. We currently use the the distinguished name, but that can change in some scenarios.

Important note for when we address: we need to support upgrades. So the code will need to be intelligent about when to look for objectGUID vs DN.

**Comment by cjellick** [comment]
We worked on making this configurable but ran into a number of problems making it backwards compatible. If see more requests for this, we'll revisit and possibly try a different solution, but we're going to move it out of the 2.1 release.
One possible future "compromise" solution that avoids the backwards compatibility issue may be to have a mechanism for "resolving" changes to a DN (ie updating the DN we have recorded for a particular user).

**Comment by nlowe** [comment]
We just got bit ***hard*** by this. Our company is going through a re-org and all of my developers and administrators got moved to a different OU in Active directory, changing the distinguished name. I can't get back into rancher as a server administrator to elevate any of my administrators back to server administrators.

**Comment by simpss** [comment]
> We worked on making this configurable but ran into a number of problems making it backwards compatible.

Instead of making it fully backwards compatible, I'd propose making a one-time migration script that gets executed during startup/update process and overwrites the lookup values to ObjectGUID.

**Comment by vincent99** [comment]
Automatically completely breaking the ability to rollback to the previous version is not really an option for us.

I'm not sure why this can't be an opt-in change though where you choose to make it overwrite what a previous version expects.  Or write/read a new field that will be ignored by previous versions.

**Comment by simpss** [comment]
How about just having an optional configuration option like atlassian does(User Unique ID Attribute)? It would default to "sAMAcoountName" like now, but it would be optionally configurable to any other AD attribute? If the config option has not been set, it would behave as it does right now.

The transition would then look up the previous value from "User Unique ID Attribute" and map the new values to a new field in the DB. In case of a rollback it would automatically fall back to the old field as it knows nothing about the new field. Does that make sense?
