### ISSUE TITLE
rancher2.0 dns resolve issue

### ISSUE THREAD

**Issue by xjiahai** [rancher/rancher#13435]
*Describe your issue here*
In busybox, when I try to use DNS, it doesn't work.
It says can not find host

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.edit`|

**Comment by loganhz** [comment]
@xjiahai please describe your issue in English here. What's the steps to reproduce your issue?

**Comment by loganhz** [comment]
@xjiahai I guess you are using an invalid dns name. I will add the validation in next version `2.0.1`.
Please reopen it if you still see the issue in 2.0.1 and provide the reproduce steps to us.
Thanks
