### ISSUE TITLE
support auth for rancher/agent during upgrade

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#13440]
Rancher 1.6 doesn't support upgrading `rancher/agent` if it requires auth. 

Steps to reproduce:
1. launch rancher server by specifying rancher/agent to a auth-required repo
2. `rancher/agent` stuck at upgrading saying auth required.

Expected:
1. successfully upgrade.

**Comment by deniseschannon** [comment]
This won't be supported natively, but you can set up your private registry and pre-pull these images with these steps: 

https://rancher.com/docs/rancher/v1.6/en/upgrading/#upgrading-rancher-when-using-private-registry-with-authentication
