### ISSUE TITLE
If Github is inaccessible, we don't timeout in timely manner

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1344]
v0.25.0-rc1

Tried to connect to my Github enterprise account for authorization in Rancher.  The Enterprise VM was down so it didn't connect and now I can't get back into my account.  It eventually gave me a error page:
![image](https://cloud.githubusercontent.com/assets/11514927/8385049/50c106e0-1bfa-11e5-9ad3-2cd20e167c38.png)

Expected:
The wait for the error page was forever, and at some point it should stop trying to log in and allow me back into the UI.

**Comment by will-chan** [comment]
The UI should time out now.  Please retest.

**Comment by tfiduccia** [comment]
Version - master 3/8
Verified fixed
