### ISSUE TITLE
Project level catalog support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#13444]
Today catalogs are supported only on Global level in Rancher 2.0. Similar to 1.6, we have to implement it on a project level.

**Comment by cjellick** [comment]
Needs further UI discussion before goes much further forward. Ping @lvuch @westlywright

**Comment by alena1108** [comment]
Can be tested once rbac is resolved

**Comment by cjellick** [comment]
I see #16316 has been moved to test. Per @alena1108's last comment, moving this one to-test

**Comment by jiaqiluo** [comment]
The first pass of all test cases is finished, and issues/bugs are tracked with separate tickets.
This ticket is closed.

**Comment by cjellick** [comment]
related: https://github.com/rancher/rancher/issues/14990
