### ISSUE TITLE
Pod has unbound PersistentVolumeClaims (repeated 7 times)

### ISSUE THREAD

**Issue by Itiho** [rancher/rancher#13442]
**Rancher versions:**
rancher/rancher:master
rancher/rancher-agent:master

**Infrastructure Stack versions:**
rancher/hyperkube:v1.10.1-rancher2
--

**Docker version: (`docker version`,`docker info` preferred)**
18.3.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Boot2Docker 18.3.1-ce

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernates

**Steps to Reproduce:**
-Configure Storage class to provisioner Ceph RBD
-Configure Workload (new or edit) 
--Enter "name" 
--Add a new persistente volume (Claim)
--Select ceph class
--Define Button
--Enter "mount Point"
--Launch or Upgrade button.

**Results:**
The POD status is "Scheduling" and show error "Pod has unbound PersistentVolumeClaims (repeated 7 times)"

**Comment by MichelDiz** [comment]
Me too

**Comment by kaushikCanada** [comment]
I have been running Rancher 2.0 in my Linode mahcine. None of the Catalog Apps are working and always giving this error. Please how to fix it? I have tried many way to deploy and kubectl works fine, but catalog is not working.

Thanks,
Love Rancher btw :)

**Comment by MichelDiz** [comment]
It's working for me with the nfs-provisioner in catalog.

**Comment by Itiho** [comment]
Olá @MichelDiz . Não achei seu contato no seu perfil. Estou testando várias soluções para volumes persistenstes. Como você configurou o NFS? você usa vários compartilhamentos NFS ou um apenas para todos os namespaces? Tentei usar storage class para o NFS mas não achei na listagem do rancher.

**Comment by kaushikCanada** [comment]
Hi.
Thank you. Will this work without nfs? Like just from local disk?

**Comment by MichelDiz** [comment]
@kaushikCanada Not sure if will work without the NFS server. Go to Catalog and run the "nfs-provisioner" before run any app.

@Itiho Eu ainda estou explorando o Rancher 2.0, eu acabei de sair do Rancher 1.X - Funcionou como eu disse, apaguei o Wordpress que levantei para teste. Rodei o nfs-provisioner, e levantei novamente o Wordpress e Voilà tudo funcionando. Só tenho problemas agora com IP, como estou usando um virtualbox com Photon WMware. Eu tenho de ver o que fazer quanto a isso. Mas que apareceu tudo funcionando, apareceu. Os volumes funcionaram.

**Comment by MichelDiz** [comment]
@kaushikCanada In that case open a new issue in the github from that app you're using.
but first, pick up an app from the catalog and see if it works.

If it works, it is not related to that issue. It seems to me an application problem. If neither of the catalog app works, then open a more detailed Issue here on the Rancher.

**Comment by kaushikCanada** [comment]
I have been trying to launch mysql containera fr a while and it is giving
this output. I will keep trying. One thing is that the nfs provisioner
worked and is active.. but other apps are not working. Let me see.

**Comment by exocode** [comment]
same here with Rancer 2.0.4 and Mongodb-replicaset (catalog library version)

**Comment by flyte** [comment]
Same with Rancher 2.0.5 and postgresql (helm library version)

**Comment by CRuppert** [comment]
same here with anything.
Rancher 2.0.5  Azure Disk Storage class
To add some value: 
Volumes are apparently being created, but when viewed are marked Pending. Similar to described here: https://github.com/rancher/rancher/issues/13305

**Comment by sh0umik** [comment]
I am having the same issue with AES EBS. I can not even attach an existing claimed volume !! 
I have watched all the Rancher Training videos on Youtube :D but none of them shows live dynamic EBS volume provisioning , All the demo includes NFS Provisioning.

However NFS Provisioning works perfect !!

**Comment by sh0umik** [comment]
#update 

The Problem with AWS EBS solved by changing the cluster cloud provider settings to Amazon. I think its necessary for Dynamic Provisioning of Storage, but its not written in 2.0 docs ..

**Comment by CRuppert** [comment]
@sh0umik if you change it, does it still respect the auth values from the template to build out the VMs? I found that the radio options seem reversed. It seems like if you select Azure or AWS (depending on) all of those fields from what amount to be settings in the host templates show.. it's *very* odd to me.

**Comment by sh0umik** [comment]
@CRuppert no it seems fine.. however the template should change the default user from ubuntu to `rancher`

**Comment by geruetzel** [comment]
2.0.8 - none of the apps are working

**Comment by kaushikCanada** [comment]
How are people going to production with rancher if nothing is going to work.

**Comment by kamushadenes** [comment]
Same here trying to deploy cockroachdb (or anything, really), using Gluster

**Comment by loganhz** [comment]
Thanks for your report!
We will investigate it soon

**Comment by kaushikCanada** [comment]
I have faced this before while deployng rancher.

**Comment by gregkeys** [comment]
our problem was that we didn't have a storage class defined, once that was done it started working

**Comment by kaushikCanada** [comment]
Can u give a screenshot maybe pls

**Comment by loganhz** [comment]
Hi, all.

It will be very easy for the charts from `Library` catalog as Rancher will maintain them. What you need is just making sure there is a storage class in your cluster. 

But for Helm Incubator, sometimes you might meet some problems.

First, make sure you have a storage class installed and make sure there is a default storage class. If you don't have one, an easy way is deploying `nfs-provisioner` in Library catalog.

![image](https://user-images.githubusercontent.com/21168270/46651158-bf20c780-cbd1-11e8-84c7-b59ba928c12a.png)

Second, for instance, if you want to deploy `Patroni` from Helm Incubator. cc @daya 

1. Deploy `Patroni` in catalog without any answers and just click `Launch`
2. In workload detail page of patroni, you can see a pod failed when scheduling.
![image](https://user-images.githubusercontent.com/21168270/46651507-db713400-cbd2-11e8-9350-705fb2004227.png)
3. Now you can click the pod and go to the pod detail page to see the `Events` section to find out why k8s can not schedule the pod.
![image](https://user-images.githubusercontent.com/21168270/46651568-0a87a580-cbd3-11e8-9dd8-456887fc497e.png)
4. As it says `pod has unbound PersistentVolumeClaims (repeated 2 times)`, so it must be something wrong with PVC. So go to the PVC list page now. And you can find a PVC is in `Pending` state. So there is something wrong with it.
![image](https://user-images.githubusercontent.com/21168270/46651634-3f93f800-cbd3-11e8-9dbc-85bf1b137387.png)
5. Click the `pending` pvc, it will take you to the pvc detail page. Click `Events` and you can find out what is going on.
![image](https://user-images.githubusercontent.com/21168270/46651791-baf5a980-cbd3-11e8-8ca7-b993f0113457.png)
6. As it says `no persistent volumes available for this claim and no storage class is set`,  so I guess there is something wrong in the YAML of the PVC. So I clicked the `View YAML` to check it out.
![image](https://user-images.githubusercontent.com/21168270/46652042-71598e80-cbd4-11e8-82e1-fe988a6d9aad.png)
7. Yes, I find the `storageClass` is empty. So K8S can not provision the PV for you automatically.  Why it is empty? I guess I missed some required filed for the app. So I removed the app and try to deploy it again. Check the `Detailed Description` of this App. And I found there is a answer we might need to set.
![image](https://user-images.githubusercontent.com/21168270/46652333-5cc9c600-cbd5-11e8-9a27-b56dbbf07701.png)
8. Add the answer to try if it will help and click `Launch`.  (there is some bug in the charts with etcd mode. Etcd has fixed that issue https://github.com/helm/charts/pull/2864/files. But patroni doesn't update etcd yet https://github.com/helm/charts/blob/master/incubator/patroni/requirements.yaml. So we need to turn off etcd and use zookeeper) 
![image](https://user-images.githubusercontent.com/21168270/46654258-fba4f100-cbda-11e8-8b8e-e28a13cc8f55.png)
9. Wait a bit and everything just works well!
![image](https://user-images.githubusercontent.com/21168270/46654395-53435c80-cbdb-11e8-9357-41eb7a618da5.png)

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by Gops123** [comment]
I have the exact same issue trying elasticsearch helm chart on bare-metal (RHEL 7.6) 3 node cluster

the message I get is
Pod has unbound PersistentVolumeClaims (repeated 3 times)

**Comment by aa-aahmed** [comment]
fresh install, i am deploying nfs provision-er app and i am getting same error as before. any suggestions

![image](https://user-images.githubusercontent.com/46661426/58865661-4d663280-86fa-11e9-8ef7-5e837859f328.png)

**Comment by yhyddr** [comment]
> fresh install 2.2.3, just for testing I deployed nfs-provisioner so it can create storage class, but rancher is even complaining about that.
> ![image](https://user-images.githubusercontent.com/46661426/58865661-4d663280-86fa-11e9-8ef7-5e837859f328.png)

you need to have PV for nfs-provisioer
