### ISSUE TITLE
Not able to clear contents of cacerts in HA setup .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13449]
**Rancher versions: v2.0.1-rc1

Brought up a rancher HA setup with 2 rancher-server instances ( setting replica to 2 for rancher/rancher container).

In this case I have  used  "Certificate Signed By A Recognized Certificate Authority" .  I would have to clear the auto generated certs  (because of https://github.com/rancher/rancher/issues/11388) .

When I try to clear cacerts from settings option , it always gets regenerated.

**Comment by deniseschannon** [comment]
@sangeethah can you re-test with the new HA?

**Comment by sangeethah** [comment]
Since this issue is addressed now - https://github.com/rancher/rancher/issues/11388 and we have ```--no-cacerts``` flag to tell rancher to not generate certs in setups which uses "Certificate Signed By A Recognized Certificate Authority" , the issue mentioned in the bug is obsolete.
