### ISSUE TITLE
Cannot get config for Kubernetes as regular user

### ISSUE THREAD

**Issue by trettstadtglei** [rancher/rancher#13454]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec:0.13.11
network-services: 0.7.20
scheduler: 0.8.3
kubernetes (if applicable): v1.10.0-rancher1-2

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.78-rancher2
Operating System: RancherOS v1.2.0
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: ip-172-31-31-72.eu-central-1.compute.internal
ID: 43O5:UG7A:6HDJ:LU6F:X3ML:VM4J:MMFS:2A3T:RRU6:CROX:TNA6:6VFO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.2.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.2.0
PRETTY_NAME="RancherOS v1.2.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher, external DB on AWS RDS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

1. Create Kubernetes environment with cloud provider aws, and RBAC enabled
2. Add hosts
3. Enable authentication with Azure AD
4. Add cluster role binding for developer group in AD and cluster role "view".
5. Add group to new environment as Owner, Member, Restricted or Read-Only
6. Log in as one of the users in the developer group.

**Results:**
UI stuck in "Waiting for Kubernetes API" and the following error message in the logs of the rancher server:
level=error msg="Error looking up token." error="HTTP error: 405 Method Not Allowed, 405"

**Comment by trettstadtglei** [comment]
This is kind of a blocker for me because only me as an administrator can work with Kubernetes right now and I really need other users to have access, too. Isn't there any workaround?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
