### ISSUE TITLE
missing color/icon in pipeline execution step status

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#13459]
**Rancher versions:**
master 5/12

**Steps to Reproduce:**
1. run a pipeline
**Results:**
In the stap status on the left, the color is missing(used to be green on success) and an empty box replaces original icon(a tick on success)
![image](https://user-images.githubusercontent.com/5697937/39963831-1ed482fa-56a9-11e8-9ca6-531babc27912.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/18
icons still missing

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/12

The icons and colors are displaying correctly when the pipeline is executed.
