### ISSUE TITLE
How to get `project` and `cluster` name or id of a container?

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#13451]
I want to logspout container logs into some other places. To properly group the logs, I have to extract out the basic information of a container, such as container id, workload id(or name), project id(or name), cluster id(or name) ...

By inspecting the container, I found useful Labels:

![image](https://user-images.githubusercontent.com/3808838/39953277-9cfc2df6-55da-11e8-8083-1ba654835983.png)

That answers some questions, but it does not tell about the `project` and `cluster`.

Among all, `project` is important as it plays as an middle layer of the hierarchy.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by zhaoyao91** [comment]
coud `namespace_id` or `project_id` be added into the container labels?

**Comment by loganhz** [comment]
In 1.6, I can get it from metadata service. How about 2.0?

**Comment by loganhz** [comment]
The project and cluster info will be pushed to your remote logging target
