### ISSUE TITLE
CrashLoopBackOff: Back-off 

### ISSUE THREAD

**Issue by kaushikCanada** [rancher/rancher#13457]
*CrashLoopBackOff: Back-off 20s restarting failed container=mysql-mysql pod=mysql-mysql-54746f9675-4m94v_default(73c7ba9b-5641-11e8-b98a-aa6755e81c4d)*

Getting this when deploying any app from catalog. just following basic steps. Have an nfs provisioner. So what could be the issue please. I love Rancher 2.0.

Please tell me what you need and i will provide for you.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`container`|

**Comment by kaushikCanada** [comment]
Unavailable  
Containers with unready status: [mysql-mysql]

happens for kube dashboard too.

**Comment by aemneina** [comment]
Provide the logs from the mysql pod(s), maybe a describe on the pod/service as well.

**Comment by kaushikCanada** [comment]
how to i get see the logs generated by the pod please? i will do a describe
and paste for you.

Thanks,
Kaushik

**Comment by kaushikCanada** [comment]
On staring a mysql catalog app i get the following in logs


Initializing database
mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 22 - Invalid argument)
2018-05-20T01:31:53.676211Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-05-20T01:31:53.680050Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
2018-05-20T01:31:53.680087Z 0 [ERROR] Aborting


on starting a dashboard i get the following:

2018/05/20 01:33:40 Starting overwatch
2018/05/20 01:33:40 Using in-cluster config to connect to apiserver
2018/05/20 01:33:40 Using service account token for csrf signing
2018/05/20 01:33:40 No request provided. Skipping authorization
2018/05/20 01:33:40 Successful initial request to the apiserver, version: v1.10.1
2018/05/20 01:33:40 Generating JWE encryption key
2018/05/20 01:33:40 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/05/20 01:33:40 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/05/20 01:33:40 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: unexpected object: &Secret{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Data:map[string][]byte{},Type:,StringData:map[string]string{},}
2018/05/20 01:33:42 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2018/05/20 01:33:42 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/05/20 01:33:42 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2018/05/20 01:33:44 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2018/05/20 01:33:44 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/05/20 01:33:44 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2018/05/20 01:33:45 Storing encryption key in a secret
panic: secrets is forbidden: User "system:serviceaccount:default:kubernetes-dashboard" cannot create secrets in the namespace "kube-system"
goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc4200a8f00)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:131 +0x2d3
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.NewRSAKeyHolder(0x1a7ee00, 0xc4204204e0, 0xc4204204e0, 0x127b962)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:170 +0x83
main.initAuthManager(0x1a7e300, 0xc4200ef800, 0xc42056fc68, 0x1)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:183 +0x12f
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:101 +0x28c

Please suggest what to do.

**Comment by superseb** [comment]
Please try the latest version (v2.0.6) and let us know if you still encounter issues.
