### ISSUE TITLE
Can not select upgrade for workloads and english language if window is small

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13453]
rancher/rancher:master 05/11

Steps to reproduce,

1. Make the window size small

Results:

1. can not select english language.
2. can not select upgrade for workloads.

![image](https://user-images.githubusercontent.com/21168270/39955854-aafa067a-5608-11e8-8e27-7c285bc039bf.png)
![image](https://user-images.githubusercontent.com/21168270/39955859-b70c4acc-5608-11e8-93a0-2968eda83b4c.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/17
Verified fixed
