### ISSUE TITLE
environment can't  config correctly

### ISSUE THREAD

**Issue by lezi1022** [rancher/rancher#13468]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.10
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
configure environment from ui
path.repo=/data/snapshot

**Results:**
step in container and run env, i can't find path.repo enviroment

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/40029040-e3bde734-5814-11e8-9b04-d858fd233a68.png)
![image](https://user-images.githubusercontent.com/21168270/40029051-f8c4c1fc-5814-11e8-8e35-eb5221cac57d.png)
@lezi1022 I can not reproduce your issue. It should be working well. 

Please reopen it if you are still suffering this issue in latest stable version.

**Comment by lezi1022** [comment]
my rancher server is v1.6.10, it doesn't work 

![image](https://user-images.githubusercontent.com/6735666/40031930-92a8b2e2-5824-11e8-9d00-45171bc2ab6b.png)


![image](https://user-images.githubusercontent.com/6735666/40031904-832669c2-5824-11e8-97cb-07344aa95fbb.png)

**Comment by loganhz** [comment]
Can you upgrade to 1.6.17 and try again?
