### ISSUE TITLE
Elasticsearch index in Cluster Logging is wrong

### ISSUE THREAD

**Issue by jungju** [rancher/rancher#13465]
rancher/rancher: 2.0.1-rc1

Elasticsearch index in Cluster Logging is wrong.
![image](https://user-images.githubusercontent.com/809189/39988495-71eb7ac6-57a2-11e8-92b9-ab3522eeea1b.png)

Actually, it is as follows.
```
xxxxx-2018.05.14
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Can we verify that this format is correct and fix please.

**Comment by bmdepesa** [comment]
rancher/rancher:master 

Index format is correct.
