### ISSUE TITLE
It can not be modified from project logging page

### ISSUE THREAD

**Issue by jungju** [rancher/rancher#13464]
rancher/rancher: 2.0.1-rc1

It can not be modified from project logging page.
URL : https://{RANCHER-DOMAIN}/p/{.......}/logging?targetType=elasticsearch
Error : "Id" contains an invalid character: :

![image](https://user-images.githubusercontent.com/809189/39988117-8119eea2-57a1-11e8-8c7f-e35a6ed07e1a.png)

**Comment by tfiduccia** [comment]
@jungju - I entered https://endpoint.com:443/p/logging?targetType=elasticsearch and logging saved for me.  Since you didn't pull the whole address, could it be something else?

**Comment by jungju** [comment]
@tfiduccia 
It will be saved for the first time. It should not be saved after this.

**Comment by tfiduccia** [comment]
@jungju - I went back to the page and it still continued to save and I didn't get the error.  Can you please provide more information like:
1.  What did the original information look like.
2.  What did you change when you modified it and saved.
3.  Can you please provide complete information (I will use endpoint.com:443 so you don't have to provide your domain).

**Comment by jungju** [comment]
@tfiduccia 
The projectId is specified as dnslabel.
An error occurs in _validate.validateDnsLabel.

key : Id
val:  project-fcq4m:pl-8wlqd
= "Id" contains an invalid character: :

![image](https://user-images.githubusercontent.com/809189/40095944-7c452540-5909-11e8-861c-148199de8da6.png)

**Comment by vincent99** [comment]
This was caused by fixing validation of `dnsLabel` fields to actually validate, and is already addressed in master by special-casing `id` for validation.  They claim to be `dnsLabel`s but are sometimes `<namespace>:<a dns label>`, which does not pass the validation because it shouldn't, that's not a valid dns label.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/15
Verified fixed
