### ISSUE TITLE
Wrong label on environment section

### ISSUE THREAD

**Issue by gjongenelen** [rancher/rancher#13469]
**Rancher versions:**
rancher/server or rancher/rancher:2.0
rancher/agent or rancher/rancher-agent:2.0
UI version: v2.0.41

In the pod view the label for environment variables is incorrect. It is showing up as "ports".
![screen shot 2018-05-14 at 14 14 42](https://user-images.githubusercontent.com/5789343/39999396-520db12e-5789-11e8-8261-2fca6aec2d69.png)

**Comment by tfiduccia** [comment]
@gjongenelen - this has already been fixed in master and will be available in 2.0.1
