### ISSUE TITLE
don't delete catalog app

### ISSUE THREAD

**Issue by seanly** [rancher/rancher#13471]
**Rancher versions:**
rancher/server or rancher/rancher:2.0.0
rancher/agent or rancher/rancher-agent: 2.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cenots7.4.1708
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vm
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
use my catalog charts
![image](https://user-images.githubusercontent.com/232069/40009359-5acbd35e-57d4-11e8-8838-a53d4b5f773a.png)

**Comment by tfiduccia** [comment]
@seanly - I don't understand what the problem is here.  Are you saying your catalog apps don't delete when you try to remove them, or that we are automatically deleting your apps?

**Comment by seanly** [comment]
@tfiduccia Please note #13490  that this issue will trigger a log explosion.
