### ISSUE TITLE
GitHub team members not recognized as Cluster Owners

### ISSUE THREAD

**Issue by mimizone** [rancher/rancher#13478]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0

**Infrastructure Stack versions:**
network-services: canal
kubernetes (if applicable): rancher/hyperkube:v1.10.1

**Docker version:**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4
4.4.0-116-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1 - import a RKE cluster (bare metal deployment in my case)
2 - setup Github authentication
3 - create a team in the GitHub organization on GitHub.com
4 - add a user to that team on GitHub.com that is not the current admin of the cluster
5 - add the team as a member of the cluster, with the owner role
6 - login with the user part of that team
7 - try a `kubectl get ns` in the embedded shell in the Rancher UI

**Results:**
The user is not allowed to do anything at the cluster scope level
```
> kubectl get ns
Error from server (InternalError): an error on the server ("{\"Code\":{\"Code\":\"ServerError\",\"Status\":500},\"Message\":\"Forbidden 403: clusters.management.cattle.io \\\"c-lg6vv\\\" is forbidden: User \\\"user-q2kvc\\\" cannot get clusters.management.cattle.io at the cluster scope\",\"Cause\":null,\"FieldName\":\"\"}") has prevented the request from succeeding (get namespaces)
```
In order to fix this, I currently have to add explicitly the user by its GitHub username as a member/owner of the cluster.

**Comment by mimizone** [comment]
The same happens with the kubeconfig. It's actually the main way we use the clusters. The shell is nice for a quick test for new users.

**Comment by frankh** [comment]
Having this issue as well, it seems roles granted through github organisations aren't propagated to kubectl permissions

**Comment by mimizone** [comment]
any update on this by any chance? is that something that you think can be fixed? or shall we not use nested teams at all ever?

**Comment by cjellick** [comment]
Im fairly certain this is the same as https://github.com/rancher/rancher/issues/13778
Which has been verified fixed and will be in v2.0.3

**Comment by rancherdev** [comment]
Tested with v2.0.3-rc5

Steps to Reproduce:
1. Created a DO cluster.
2.  Enable github auth.
3.  Add a github org (having user say user1) as cluster owner of this DO cluster.
4.  Log in as user1 ( who is part of the github org)
5.  Using kubectl shell in Rancher UI for listing namespace succeeds.

```
> kubectl get ns
NAME            STATUS    AGE
cattle-system   Active    24m
default         Active    25m
ingress-nginx   Active    24m
kube-public     Active    25m
kube-system     Active    25m
>
```
5. Using kubeconfig for this user , able to list namespaces and create resources using remote kubectl. 

@mimizone @frankh  This fix will be available in v2.0.3 release.

**Comment by sangeethah** [comment]
Tested with v2.0.3-rc5

Steps to Reproduce:

Created a DO cluster.
Enable github auth.
Add a github org (having user say user1) as cluster owner of this DO cluster.
Log in as user1 ( who is part of the github org)
Using kubectl shell in Rancher UI for listing namespace succeeds.
> kubectl get ns
NAME            STATUS    AGE
cattle-system   Active    24m
default         Active    25m
ingress-nginx   Active    24m
kube-public     Active    25m
kube-system     Active    25m
>
Using kubeconfig for this user , able to list namespaces and create resources using remote kubectl.
@mimizone @frankh This fix will be available in v2.0.3 release.

**Comment by mimizone** [comment]
I've deployed 2.0.4 and still have the problem.
Is there something to do on existing users?

**Comment by mimizone** [comment]
my bad, the team has to be also in the list in the GitHub configuration in rancher to make it work.
Seems to be working for me now.
