### ISSUE TITLE
Selected namespaces are not cleared across operations

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#13476]
**Rancher versions:** 2.0.0

**Steps to Reproduce:**
- Deploy a rancher 2.0.0 setup.
- Create a cluster
- Create two projects
- In project-1, create 2 namespaces
- Select 1 namespace from project-1 and move it to project-2
- Select the second namespace from project-1 and try to move it to project-2

**Results:**

The move namespace dialog in the last step will show 2 namespaces instead of 1. To clear the selected namespaces, the page needs to be refreshed.

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/16
Verified fixed.  The first namespace was actually still selected but the checkmark wasn't showing.  Fixed that checkmark.  We do not automatically uncheck anything in app after action, just in case user wants to do another action.
