### ISSUE TITLE
Service automatically goes to degraded with OS=Ubuntu in scheduler

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1348]
v0.25.0-rc1
Steps:
1.  Create a service
    - Always run one instance of this container on every host
    - In scheduler add a rule where host must have: Key = OS & Value = Ubuntu
2.  Start service

Results:
Service automatically goes to degraded status

Expected:
Service to try and start

**Comment by alena1108** [comment]
@sonchang Son, do you see any potential problems with the keys @tfiduccia defined? @tfiduccia Tani, if there is any error in the rancher log defining why service goes to degraded state (most likely meaning instance failed to start)? If so, could you please attach it to the bug.

**Comment by tfiduccia** [comment]
I looked in the logs and there wasn't anything in there.  But here is my IP http://104.197.16.135:8080/ and I opened it up to all github users and added rancherio to the environment.

**Comment by tfiduccia** [comment]
While I was looking at containers, I noticed that if I used Ubuntu or UBUNTU, I was having a problem with creating the container.  I went back and looked at host and this seems to be the problem.  If the Value is Ubuntu or UBUNTU (with any kind of capitalization) the service will auto-degrade and the container will not create.

**Comment by tfiduccia** [comment]
v0.27.0-rc4
Verified fixed
