### ISSUE TITLE
Standard User can not create cluster

### ISSUE THREAD

**Issue by gravityforall** [rancher/rancher#13483]
**Rancher versions:**
CATTLE_UI_VERSION = 2.0.41
CATTLE_CLI_VERSION = v2.0.0
CATTLE_SERVER_VERSION = v2.0.0
CATTLE_AGENT_IMAGE = rancher/rancher-agent:v2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-119-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Rackspace/OpenStack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
1. Leave the 'Cluster Name' field blank when creating a new cluster
<img width="1128" alt="screen shot 2018-05-14 at 1 46 25 pm" src="https://user-images.githubusercontent.com/1358859/40017098-f67d9bb8-577d-11e8-83e1-24b1d55c3284.png">

**Results:**
Error 'User XXX cannot create node pools...'
<img width="1130" alt="screen shot 2018-05-14 at 1 46 46 pm" src="https://user-images.githubusercontent.com/1358859/40017693-be9165e8-577f-11e8-995b-19d232b53104.png">

**Comment by tfiduccia** [comment]
@gravityforall - Ryan, this is a bad error message.  This is because you don't have Cluster Name.  Which is a required field.

**Comment by loganhz** [comment]
I can reproduce this issue in master 05/14

1. create a Standard User `user1`
2. login as this user `user1`
3. create a RKE cluster with DO node driver
4. Input cluster name and select other fields
5. Click create. The request for creating `nodepool` gets `403` with the similar error message.

I think this is a backend issue.  It looks like we can do nothing from UI side.

**Comment by deniseschannon** [comment]
@prachidamle i thought we made the cluster name required in https://github.com/rancher/rancher/issues/13075

**Comment by prachidamle** [comment]
@deniseschannon @loganhz yes, clusterName is now a required field and has to be unique as well

**Comment by loganhz** [comment]
@deniseschannon @prachidamle  Standard user still can not create cluster with master 06/10. 
It's not a cluster name issue.  Maybe we should rename the issue.

`clusterregistrationtokens.management.cattle.io is forbidden: User "u-c9qrf" cannot create clusterregistrationtokens.management.cattle.io in the namespace "c-98wgj"`

**Comment by loganhz** [comment]
If standard users create a `custom` or `import` cluster
POST `https://localhost/v3/clusterregistrationtoken` returns 403.

If standard users create a cluster with node driver

POST `https://localhost/v3/nodepool` returns 403

![image](https://user-images.githubusercontent.com/21168270/41197536-9a64cd20-6c94-11e8-964a-7be2a33cce07.png)

**Comment by loganhz** [comment]
Duplicated with https://github.com/rancher/rancher/issues/12532

**Comment by prachidamle** [comment]
The error message has been fixed to indicate that clusterName is a required field, as seen below:
<img width="1349" alt="screen shot 2018-06-10 at 6 02 32 am" src="https://user-images.githubusercontent.com/1470602/41201828-56162be8-6c74-11e8-833c-5fa3d8f10b02.png">
