### ISSUE TITLE
"Command line is not complete" logs seen in agent logs

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13486]
rancher-server : Build from master

Setup:
Add a custom cluster.
Add a host (with all roles) to custom cluster.

Agent log has the following lines:
```
Command line is not complete. Try option "help"
Command line is not complete. Try option "help"
```

**Comment by adingilloRancher** [comment]
`Command line is not complete. Try option "help"`
Message was not logged during provisioning on agent.
