### ISSUE TITLE
cannot specified port while add service discovery in ui

### ISSUE THREAD

**Issue by vincentchen** [rancher/rancher#13494]
**Rancher versions:**  2.0.0
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
The port is random ,as a result ,maybe not the real  port of services .

**Comment by loganhz** [comment]
Please read https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

```
For headless services that define selectors, the endpoints controller creates Endpoints records in the API, and modifies the DNS configuration to return A records (addresses) that point directly to the Pods backing the Service.
```
