### ISSUE TITLE
Issue when creating Standard_D2_v2 AKS cluster on Azure

### ISSUE THREAD

**Issue by IanMoroney** [rancher/rancher#13497]
**Rancher versions:**
rancher/rancher:stable

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: AKS**

**Setup details: single node rancher **

**Environment Template: Kubernetes**

**Steps to Reproduce:**
Create Azure container cluster and choose machine size as Standard_D2_v2 
**Results:**

 docker-compose logs -f --tail 1000:

rancher_server_1  | 2018/05/15 08:23:43 [INFO] Provisioning cluster [c-qgjqs]
rancher_server_1  | 2018/05/15 08:23:43 [INFO] Creating cluster [c-qgjqs]
rancher_server_1  | E0515 08:23:44.369067       1 generic_controller.go:204] ClusterController c-qgjqs recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:153
rancher_server_1  | /usr/local/go/src/runtime/asm_amd64.s:509
rancher_server_1  | /usr/local/go/src/runtime/panic.go:491
rancher_server_1  | /usr/local/go/src/runtime/panic.go:63
rancher_server_1  | /usr/local/go/src/runtime/signal_unix.go:367
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_client.go:39
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/types/rpc_client.go:38
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/cluster/cluster.go:151
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/cluster/cluster.go:79
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/kontainer-engine/service/service.go:201
rancher_server_1  | /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/driver.go:22
rancher_server_1  | /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:225
rancher_server_1  | /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:105
rancher_server_1  | /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:147
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:149
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:132
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:123
rancher_server_1  | /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:146
rancher_server_1  | /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterprovisioner/provisioner.go:142
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:19
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:158
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:57
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/lifecycle/object.go:40
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_lifecycle_adapter.go:49
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_cluster_controller.go:122
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:250
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:190
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:178
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:170
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
rancher_server_1  | /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
rancher_server_1  | /usr/local/go/src/runtime/asm_amd64.s:2337

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13497
