### ISSUE TITLE
The workloads name starts with a number and the UI does not show port information

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#13498]
**Rancher versions:**
rancher/rancher: master
rancher/rancher-agent: master

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 LTS
 4.4.0-21-generic #37-Ubuntu SMP Mon Apr

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware Fusion 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
Deploy a workloads and set its name to 123test，Configuring port mapping，select nodeport ,UI does not show port information, Service Discovery has no relevant records . as the picture shows:

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/20707603/40046989-d5c8af1e-5860-11e8-9d06-760562ab4410.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/20707603/40047599-7cc17f8e-5862-11e8-9ef2-68ebc112dfd9.png">

<img width="940" alt="image" src="https://user-images.githubusercontent.com/20707603/40047741-dab07d98-5862-11e8-8666-473014e689eb.png">

**Rancher server logs:**

E0515 09:10:08.032607       1 generic_controller.go:204] DeploymentController demo/123test [workloadServiceGenerationController] failed with : Service "123test-nodeport" is invalid: metadata.name: Invalid value: "123test-nodeport": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
2018/05/15 09:10:08 [INFO] Creating [demo/123test-nodeport] service of type [NodePort] with ports [[{80tcp01 TCP 80 {0 80 } 0}]] for workload deployment:demo:123test

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/15
This is indeed a bug

**Comment by alena1108** [comment]
The fix would be to enforce workload name to be a valid dns as we automatically create a service for it

**Comment by sangeethah** [comment]
Tested with latest build from master.

We are not allowed to create a workload with name that start with numeric values.
User is presented with following error message:

```
Validation failed in API: name InvalidFormat 422: invalid value 345gg: a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```
