### ISSUE TITLE
The deployment of the catalog app error caused the log to jump, and rancher restarted.

### ISSUE THREAD

**Issue by seanly** [rancher/rancher#13490]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos7.4.1804
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vm
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
![image](https://user-images.githubusercontent.com/232069/40027601-5bfeb79e-580d-11e8-89eb-7893a9d308f8.png)

**Comment by cjellick** [comment]
I'm sorry, but I think you're discription of the problem is insufficient for us to know whats going on.
That said, I see "no space left on device" as the last log line. Possible you ran out of disk space?

**Comment by seanly** [comment]
@cjellick which node ? rancher server？ 
is this?
![image](https://user-images.githubusercontent.com/232069/40028107-c0e97020-580f-11e8-8e11-5e50e090fcb0.png)

**Comment by seanly** [comment]
#13471 This error occurred one night when rancher went down and logged a lot of logs.

![image](https://user-images.githubusercontent.com/232069/40028556-0ceb9dd4-5812-11e8-83a9-405c939f9242.png)

**Comment by loganhz** [comment]
@seanly Can you provide the reproduce steps for both https://github.com/rancher/rancher/issues/13490 and https://github.com/rancher/rancher/issues/13471, please?

**Comment by seanly** [comment]
when use `https://github.com/seanly/dsky-charts' deploy dsky-jenkins charts.

Here are the configuration parameters： 
![image](https://user-images.githubusercontent.com/232069/40031546-bf3f5a38-5822-11e8-985a-1b38b1c0e801.png)

The following is the deployment exception tip：
![image](https://user-images.githubusercontent.com/232069/40031598-000118e0-5823-11e8-9529-09eaeb366ea6.png)


Here is the log of the rancher service：
![image](https://user-images.githubusercontent.com/232069/40031617-246922d6-5823-11e8-9780-c25129bc7624.png)

The lack of disk space is that the log is constantly duplicated .

**Comment by seanly** [comment]
The logs are growing fast @cjellick @loganhz 

![image](https://user-images.githubusercontent.com/232069/40032021-df4b15c2-5824-11e8-8305-5a87af4e9de4.png)

![image](https://user-images.githubusercontent.com/232069/40032028-e3fe5d54-5824-11e8-80dc-ae12931b07dc.png)

**Comment by seanly** [comment]
when restart rancher server ,log result : 

![image](https://user-images.githubusercontent.com/232069/40033388-ca891980-582a-11e8-98d7-06dc46c787df.png)
