### ISSUE TITLE
Scheduler config display error 

### ISSUE THREAD

**Issue by lezi1022** [rancher/rancher#13492]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.10
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
config scheduler here 
![image](https://user-images.githubusercontent.com/6735666/40032456-cedff8b8-5826-11e8-947c-9ec772ff0ddd.png)

as a result
![image](https://user-images.githubusercontent.com/6735666/40032425-ad6091fc-5826-11e8-9608-3cce227efa3f.png)

**Results:**

**Comment by tfiduccia** [comment]
Version - v1.6.22-rc2
Verified fixed
