### ISSUE TITLE
Error communicating with authentication provider  after upgrade to 1.6.17

### ISSUE THREAD

**Issue by Ima8** [rancher/rancher#13496]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent:

![image](https://user-images.githubusercontent.com/9165089/40042836-e5a2a66a-584c-11e8-90a1-1328f437f9f5.png)

**Comment by superseb** [comment]
From what version did you upgrade? What is in the `rancher/server` logs?
