### ISSUE TITLE
Rancher Ingress Controller NGINX adjust client_max_body_size

### ISSUE THREAD

**Issue by philipp1992** [rancher/rancher#13501]
**Rancher versions:**
rancher/server or rancher/rancher: 2.x
rancher/agent or rancher/rancher-agent: 2.x

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Create a new layer 7 ingress rule

**Results:**
Nginx config looks like the following:

            port_in_redirect off;

            set $proxy_upstream_name "default-ingress-c72176393b499234d9f516d9818b6b45-9000";

            set $namespace      "default";
            set $ingress_name   "minio";
            set $service_name   "";

            client_max_body_size                    "1m";

Expected results:
Client_max_body_size 0m

Hi,

is there a way to adjust the client_max_body_size when creating a new ingress rule for the default ingress controller in rancher?

Kind regards,
Philipp

**Comment by zanderson-aim** [comment]
I had the same problem, you probably need to be looking here: https://github.com/rancher/ingress-nginx/blob/master/docs/user-guide/configmap.md#proxy-body-size

I ended up adding proxy-body-size to the configmap and it worked

**Comment by btaens** [comment]
Just add the following annotation to the loadbalancer: nginx.ingress.kubernetes.io/proxy-body-size=0
This will allow a request body of any size, or set it to a specific size to not allow anything larger than that.

**Comment by TehTotalPwnage** [comment]
As others have mentioned already, you can use the `nginx.ingress.kubernetes.io/proxy-body-size` annotation to adjust the maximum body size.

I'm going to close up this issue since it seems resolved. Let me know if you still have problems.

**Comment by junkiebev** [comment]
> I had the same problem, you probably need to be looking here: https://github.com/rancher/ingress-nginx/blob/master/docs/user-guide/configmap.md#proxy-body-size
> I ended up adding proxy-body-size to the configmap and it worked
> or here if you want to use the annotations: https://github.com/rancher/ingress-nginx/blob/master/docs/user-guide/annotations.md

@zanderson-aim - both of those links are broken FYI

**Comment by travnewmatic** [comment]
indeed those links are dead, but i was able to use kubernetes documentation elsewhere at https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md and https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md#proxy-body-size
