### ISSUE TITLE
Node template options for openstack are gone

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13507]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.1-rc1

**Docker version: (`docker version`,`docker info` preferred)** 17.3.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** centos 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

1) Add a cluster
2) Select openstack provider
3) Add Node Template

or

1) global "Node Templates"
2) Add Template
3) Select "openstack"

**Results:**
The dialog box to enter openstack options is empty and don't have any fields.

This is a regression from v2.0.0

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/15
This has indeed regressed - error in dev console:
opcode-compiler.js:291 Uncaught Error: Compile Error: api-field is not a helper

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/16
Verified fixed
