### ISSUE TITLE
spinnaker deployment - timed out progressing

### ISSUE THREAD

**Issue by MarkMangoba** [rancher/rancher#13503]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 1.10

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian 9

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Install spinnaker - 

**Results:**
I've been unsuccessful deploying spinnaker, at most I get:  ReplicaSet "spinnaker-minio-5f6bd88584" has timed out progressing.
<img width="706" alt="screen shot 2018-05-15 at 6 42 40 am" src="https://user-images.githubusercontent.com/17626251/40060352-379e5cd0-580b-11e8-9ec0-ae7672cf3c80.png">

**Comment by loganhz** [comment]
`ReplicaSet "spinnaker-minio-5f6bd88584" has timed out progressing` is a very generic error log.
You need to look at into the events section in pod detail page or `kubectl`

Please make sure 

1. Your cluster has enough resources.
2. You have pre-created some PV for spinnaker. (spinnaker requires three PV)
3. The PVC which required by spinnaker is bound. (You can find it via workloads=> volumes)
4. Go through all of the red workloads and look at the pods of it. Look at the events sections to find out why the pods can not run. 

![image](https://user-images.githubusercontent.com/21168270/43383534-e0c49d68-940d-11e8-9f25-c369459d3b9a.png)
