### ISSUE TITLE
Unable to create RKE cluster on Azure

### ISSUE THREAD

**Issue by IanMoroney** [rancher/rancher#13500]
**Rancher versions:**
rancher/rancher:stable

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.1-rancher1

**Type/provider of hosts: RKE on Azure **

**Setup details: single node rancher **

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Deploy a new cluster and choose "Azure" as the provider.
Select Cloud provider as "Azure" under Cluster Options.

**Results:**
Machines in Azure get created
Cluster stuck in "Provisioning" state.
Cluster provisioning cycles through its healthchecks, but fails at:

[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [hostiphere]: Get https://localhost:6443/healthz: can not build dialer to c-rzh2m:m-x9sxp

**Comment by superseb** [comment]
The message `can not build dialer` usually means the created host is not able to reach the configured `server-url` in Rancher. Can you verify it is reachable for the host created?

**Comment by IanMoroney** [comment]
the URL is a publicly facing URL so it should be contactable yep

**Comment by IanMoroney** [comment]
actually this may be a firewall restriction. What port is it trying to communicate over?

**Comment by superseb** [comment]
The launched `rancher/rancher-agent` will contact Rancher on the configured `server-url` which can be found in Settings or in the API `/v3/

**Comment by IanMoroney** [comment]
Added an any/any rule for the 3 IP's of the nodes and still got the same
error. The URL is correct

**Comment by superseb** [comment]
Okay, if network is all taken care of, is the configuration of the cloud provider done according to the docs: https://rancher.com/docs/rancher/v2.x/en/concepts/clusters/cloud-providers/#azure

Easiest way to test is to not enable Cloud Provider functionality in Kubernetes for now.

**Comment by superseb** [comment]
Just ran some more tests, can only conclude network configuration. I get other errors when cloud provider is configured incorrectly. Is the `server-url` directly to the `rancher/rancher` container or is there something in between? Does the host running `rancher/rancher` have a static IP that needs additional firewall rules?

**Comment by IanMoroney** [comment]
Will check and let you know

**Comment by IanMoroney** [comment]
Couldn't get it working at all so i've abandoned rancher.
Publishing directly into kubernetes works perfectly on an AKS cluster created through the portal.

**Comment by superseb** [comment]
Ok let me know if you need help
