### ISSUE TITLE
Rancher docs needs remove steps/process

### ISSUE THREAD

**Issue by CalvinHartwell** [rancher/rancher#13502]
Hi all, 

I'd like to see a list of steps for removing Rancher cleanly from a kubernetes cluster so I can reinstall it from scratch. From what I understand these steps do not exist yet. 

A common issue is when we do not enable running containers with root privileges when we run Rancher:

```
Exit status 1, namespace "cattle-system" configured serviceaccount "cattle" unchanged clusterrolebinding "cattle" configured secret "cattle-credentials-d17753e" unchanged deployment "cattle-cluster-agent" unchanged The DaemonSet "cattle-node-agent" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```

Even after removing the Rancher container and re-deploying with the permissions corrected, the issue still exists, but if I was able to clean up everything rancher related, it would fix the issue. 

Cheers,

- Calvin

**Comment by deniseschannon** [comment]
@moelsayed Before @MBishop17 can work on docs, can you figure out what needs to be cleaned up when launching rancher in a k8s cluster, what to do to remove the rancher deployment to clean up the k8s cluster.

**Comment by moelsayed** [comment]
@CalvinHartwell Just a small clarification. You are having the this issue with cluster running the rancher server or an imported cluster ?

**Comment by deniseschannon** [comment]
@moelsayed i think this is the cluster that is running rancher server (not a cluster being added into rancher), so should be related to #13505

**Comment by moelsayed** [comment]
@deniseschannon Yes, that's correct.

**Comment by deniseschannon** [comment]
Let's close this one and use #13505.
