### ISSUE TITLE
Pod create alert fires more than once

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13517]
**Rancher versions:** 2.0 master 5/15

**Steps to Reproduce:**
1.  Create an Pod alert associated to a slack notifier
2.  Create a workload

**Results:**  I get two alerts for the pod.  Since the pod only creates once, I probably should not be getting two.
![image](https://user-images.githubusercontent.com/11514927/40088411-e39fd52c-585b-11e8-9bfa-dd796df4148e.png)

**Comment by tfiduccia** [comment]
Actually it sent it three times?  Two came at 4:18, then another one came at 4:23.  Five minutes later.

![image](https://user-images.githubusercontent.com/11514927/40088642-c1c7b5fe-585c-11e8-81a2-4d32acf5e2df.png)

**Comment by tfiduccia** [comment]
Ok, I looked at show more and saw they are firing for different reasons.  This is a strange alert, cause it's not consistent.  Can you please tell me what the expectation for Pod alerts are?  Currently it's very confusing.

**Comment by zionwu** [comment]
@tfiduccia , for the pod event alert, we are watching all k8s event of type pod. If an event is created or updated, an alert will be triggered. 

If you create a pod, there is several events created in k8s:
![image](https://user-images.githubusercontent.com/1213386/40093432-cbe29cf0-58f4-11e8-8624-587fee1952cc.png)

**Comment by tfiduccia** [comment]
@zionwu - I see.... so the issue I'm seeing is that for every pod created.  Sometimes I receive 2 alerts, sometimes 3 or sometimes just 1 for each pod.  Is that something we can fix?  Seems like I should be getting 6 for pod create?  And can we fix that or is there some sort of "bunching" when multiple alerts are fired for same thing?

**Comment by zionwu** [comment]
@tfiduccia , you are correct. Alert manager will group the alerts that with the same id. 

There are two parameters.
>group_wait: 
>How long to initially wait to send a notification for a group of alerts. Allows to wait for an inhibiting alert to arrive or collect more initial alerts for the same group. (Usually ~0s to few minutes.)

> group_interval
> How long to wait before sending a notification about new alerts that are added to a group of alerts for which an initial notification has already been sent. (Usually ~5m or more.)

The group_wait is the `Initial Wait` in advanced options and its default value is 3 min.
The group_interval is not configurable from UI and its default is 5 mins.

I think the fix is to set group_wait and group_interval to short interval like 1s for pod event alert.

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/15

Was able to see all pod alerts successfully. Editing the interval times allowed to see the alerts quicker.
