### ISSUE TITLE
After rancher upgrade, ingress in GKE cluster does not point to new targets once workload is scaled up

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13514]
**Rancher versions:**
 rancher/rancher: Upgrade from v2.0.0 to v2.0.1-rc1

**Steps to Reproduce:**
1. Create a GKE cluster in Rancher v2.00
2. Create workload with scale 2 and ingress pointing to the workload. The ingress points to all the pods in the workload
3. Upgrade the rancher server to v2.0.1-rc1
4. Increase the scale of the workload.

The ingress does not point to all the new pods in the workload. 
Targets the ingress points to, is obtained using: 
wget --header='host: myingress.default.1.2.3.4xip.io' http://1.2.3.4/name.html

**Comment by gwiersma** [comment]
Problem does also exists on Rancher v2.0.0 without the v2.0.1-rc1 update.

**Comment by deniseschannon** [comment]
@gwiersma did you wait for the ingress to be up before testing? there is a known issue where it takes awhile before the ingress is available.

**Comment by StrongMonkey** [comment]
@soumyalj  i didn't reproduce your issue, but going though your gke ingress in your setup, it is getting stuck and seems to be routing stuff that is in cache. (I delete all your pods and restarted them, all the container name get changed but http response is still the same). I deleted the old ingress and started a new one and it is working. Let me know if you reproduced it again, i can spend time digging into it to see if there is anything that is not probably configed or we are not following GKE's best practice in how to use ingress.

**Comment by gwiersma** [comment]
@deniseschannon Yes i did. The steps i executed: 

- Start deployment
- Create ingress and point to the specific workload
- Tested the ingress controller successfully
- Scaled my workload from 5 replicas to 10 replicas
- 10 new pods are scheduled and the 5 old pods are being removed
- When all of the 10 new pods are available and the 5 old pods are removed, the Ingress controller responds with a 503. 
- After deleting the current ingress controller and creating a new ingress controller that points to the same workload, it works. 

So it seems that the ingress controller does not dynamically scales the backend workloads.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.0.0 to v2.0.1-rc2. Tested with the steps above. This time, when the workload scaled up, the ingress was able to get the updated set of pods. It takes 3 to 5 minutes for the ingress to get the update.
