### ISSUE TITLE
Ability to import a previously imported cluster (that has been deleted from Rancher)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#13512]
Upon importing a cluster that was previously in Rancher (but now deleted/removed from Rancher), we need to:

1. Associate Default namespace to the newly created Default project
2. Clear the project ID annotation on existing namespaces for project IDs that don't exist

**Comment by cjellick** [comment]
you make it sound soooo simple :scream_cat:

**Comment by vincent99** [comment]
Suggestion: Store the UUID of the project instead of `authz.management.cattle.io/default-project=true`, so you know if it's created for _this_ project instead of _some_ project.

**Comment by alena1108** [comment]
We have to cleanup cattle-system namespace too

**Comment by cjellick** [comment]
promoting to p0 since this is tied to cluster cleanup logic

**Comment by sangeethah** [comment]
Tested with latest build from master.
We are able to import a previously imported cluster back successfully.
Default namespace gets back to "Default" project and all namespaces under "System" project get back to "System" project.

Details of testing done can be found in - https://github.com/rancher/rancher/issues/14848 and https://github.com/rancher/rancher/issues/14207
