### ISSUE TITLE
Add support for host initilization scripts

### ISSUE THREAD

**Issue by usmanismail** [rancher/rancher#1351]
A number of docker monitoring solutions, NewRlic, SysDig and Ruxit require commands (or agents) to be run on the host instead of in a container. If we launch hosts through Rancher there is no way to run initialization commands on the host. The eventual ideal is to have cloud init support but that my be blocked [Docker machine issue 124](https://github.com/docker/machine/issues/124) but is there something possible in the interim? Rancher does have the ssh keys for the machines so should be able to run arbitrary commands which can be specified in the service configuration.

**Comment by vincent99** [comment]
You can basically do this with your own global service (1.x) / daemonset (2.0) in the environment/project.  Or some machine drivers do have cloud-init support (e.g. vsphere).  I don't think inventing a new ansible/puppet/chef to deploy stuff on to the host, handle updating them when the definition changes, etc is a good idea.
