### ISSUE TITLE
[rancher/cli] Install catalog (Helm) chart from local file system

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#13518]
**Rancher versions:**
rancher/rancher

A common workflow for developing Helm charts is to `helm install ./stable/mychart` since Rancher is replicating a lot of this functionality with catalog and a tiller'less setup, this functionality should be added.

**Comment by deniseschannon** [comment]
Available with CLI v2.0.1-rc4 and Rancher v2.0.1-rc3

**Comment by adingilloRancher** [comment]
@StrongMonkey 

Chart.yaml file not found in directory when installing from local file. 

![screen shot 2018-05-18 at 2 00 50 pm](https://user-images.githubusercontent.com/38012481/40257698-ffcb9ca0-5aa3-11e8-98b2-735a6609cace.png)

**Comment by deniseschannon** [comment]
available with CLI v2.0.1-rc5

**Comment by adingilloRancher** [comment]
v2.0.1-rc5

Verified ability to install app via local chart file.
