### ISSUE TITLE
Email notifier broken cause host can't have . in it

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13516]
**Rancher versions:** 2.0 master 5/15

**Steps to Reproduce:**
1.  Create an email notifier
2.  Click on Test or Add

**Results:**  Can't Test or Add notifier cause it says "." is invalid character for host.  The type for this field should be hostname instead of dnsLabel.  dnsLabel is only for 1 part of host name.

![image](https://user-images.githubusercontent.com/11514927/40086948-5edcb036-5855-11e8-9937-ff42ca981daf.png)

**Comment by zionwu** [comment]
@vincent99 @loganhz , I just find this is a UI issue.

When click `Save`, there is not any request sent. So the error is from UI.
![image](https://user-images.githubusercontent.com/1213386/40214486-9c87391c-5a8d-11e8-9f5f-6b49a78f6bfd.png)

I made the API call from htmlUI and it succeed. 

With regards to the `dnsLabel` tag in norman for host field, I find out its validation method is `validation.IsDNS1123Subdomain`, which is https://github.com/rancher/norman/blob/master/vendor/k8s.io/apimachinery/pkg/util/validation/validation.go#L134. So the `dnsLabel` validation works fine work hostname.

**Comment by loganhz** [comment]
There is a UI side validation for dnsLabel.

https://github.com/rancher/ember-api-store/blob/master/addon/utils/validate.js#L157

**Comment by vincent99** [comment]
Then the `dnsLabel` validation in the API is wrong.  A `hostname` is a series of `dnsLabel`s separated by dots.  a `dnsLabel` cannot contain a dot.

**Comment by vincent99** [comment]
```
Appendix 1 - Domain Name Syntax Specification

   The preferred syntax of domain names is given by the following BNF
   rules.  Adherence to this syntax will result in fewer problems with
   many applications that use domain names (e.g., mail, TELNET).  Note
   that some applications described in [14] use domain names containing
   binary information and hence do not follow this syntax.

      <domain> ::=  <subdomain> | " "

      <subdomain> ::=  <label> | <subdomain> "." <label>

      <label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]

      <ldh-str> ::= <let-dig-hyp> | <let-dig-hyp> <ldh-str>

      <let-dig-hyp> ::= <let-dig> | "-"

      <let-dig> ::= <letter> | <digit>

      <letter> ::= any one of the 52 alphabetic characters A through Z
      in upper case and a through z in lower case

      <digit> ::= any one of the ten digits 0 through 9
```

https://tools.ietf.org/html/rfc882.html

**Comment by deniseschannon** [comment]
Fixed in master 5/18

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/18
Verified fixed
