### ISSUE TITLE
add namespace to the catalog.yml

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#13519]
**Rancher versions:** 2.0 master 05/16

For few charts like kubernetes-dashboard and istio, deploy to a fixed namespace like kube-system and istio-system is required, should add support to define the namespace field in the catalog.yaml for chart deployment namespace specification.
```
namespace: kube-system
```
![image](https://user-images.githubusercontent.com/4569037/40091298-66dbc710-58e9-11e8-9f78-7c4b441817e7.png)

**Comment by guangbochen** [comment]
@StrongMonkey can we add 1. create namespace if not exist, 2. move the namespace to the current project if does not belongs to any project.

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/19

To test:
Fork rancher/charts catalog
In some chart (I used `wordpress`) Add `namespace: wp-foo` to `questions.yaml` or `catalog.yaml`
Add custom catalog
Add chart from custom catalog

The namespace field should be as specified, and unable to customize. If the namespace does not exist, it is created and moved to the current project. 

If the namespace exists, it should use it correctly.

**Result**
New namespace is created and moved to project
Existing namespace does not work. 

Deploy chart to required namespace, then delete, but keep the namespace. 
Deploy the chart again and it gives error `namespaces "wp-foo" already exists`

<img width="1315" alt="screen shot 2018-06-19 at 2 14 35 pm" src="https://user-images.githubusercontent.com/21316915/41624780-7feeb9e0-73cb-11e8-81bc-578fee20bfca.png">

**Comment by guangbochen** [comment]
@loganhz can you please help to address the `namespaces` already exists case, probably need to check if the namespace exists or not, if yes make it deploy to existing namespace, even though the namespace might end up in a different project (for now we just consider it as a cluster level app).

**Comment by bmdepesa** [comment]
v2.0.3-rc1

If namespace exists in the current project, the chart will deploy correctly. 

If the namespace exists outside the project, the chart is added to the catalog app list in the project but no containers are deployed and `namespaceId` is `null` in the API. 

<img width="951" alt="screen shot 2018-06-20 at 9 58 04 am" src="https://user-images.githubusercontent.com/21316915/41673051-7ee6a01c-7470-11e8-809a-c196c9148e2a.png">
<img width="223" alt="screen shot 2018-06-20 at 9 58 13 am" src="https://user-images.githubusercontent.com/21316915/41673055-83f056f2-7470-11e8-92ca-b62936fa3ac4.png">

**Comment by bmdepesa** [comment]
Additionally, 

If the required namespace exists in another project, the workloads will be deployed to the project where the namespace already exists, even though the catalog app is listed in the original project: 
```
Cluster - test
    Project - Default
    Project - test
        namespace: wp-foo
```

Deploy app with required namespace `wp-foo` in `Default` project, while namespace exists in `test` project. The app shows in `Default` catalog apps, but workloads are deployed `test` project under `wp-foo` namespace. No catalog apps are shown in `test` project.

**Comment by loganhz** [comment]
I guess we can do noting from UI side.

Maybe server should return `400` with a proper error message like `namespace already exists in another project`.

**Comment by guangbochen** [comment]
This is expected behavior as the `namespace` is unique in the cluster level, and a pre-defined namespace is designed for apps like `kubernetes-dashboard` that is unique in the cluster level, for apps like wordpress is not necessary to set namespace in the yaml file, because they can easily modify or using existing namespace in the catalog UI.

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/28

Validation added when namespace exists outside of the current project. Error is displayed correctly.
