### ISSUE TITLE
Rancher 1.6.17, Windows agent wont get added successfully. "registration failed. err: Get /scripts/api.crt: unsupported protocol scheme"

### ISSUE THREAD

**Issue by vishnuvpotti** [rancher/rancher#13520]
**Rancher versions:** 
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: rancher/agent-windows:v0.2.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
PS C:\program files\rancher> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.2-ee-10
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1794.amd64fre.rs1_release.171008-1615)
Operating System: Windows Server 2016 Standard

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1) Installed rancher server 1.6.17
2) Created Windows environment in Rancher.
3) clicked on Add host icon.
4) Executed the Step2 : Get-WindowsFeature -Name "RemoteAccess","Routing" | Install-WindowsFeature
5) Provided 192.168.0.0 as unique subnet value
6) Provided 192.168.0.1 as router IP.
7) Copied script from Step 7 and executed on the windows agents.

**Results:**
**I am seeing error as seen below in powershell window when executed for first time.**
PS C:\Windows\system32> $obj |& "C:\Program Files\rancher\startup.ps1"
VERBOSE: Loading module from path 'C:\program files\rancher\rancher-tools.psm1'.
VERBOSE: Importing function 'Add-DebugContent'.
VERBOSE: Importing function 'Add-LogContent'.
VERBOSE: Importing function 'Get-DownloadList'.
VERBOSE: Importing function 'Get-DownloadListByTarget'.
VERBOSE: Importing function 'Get-RancherBasicAuth'.
VERBOSE: Importing function 'Get-RancherBinary'.
VERBOSE: Importing function 'Get-RancherComponentList'.
VERBOSE: Importing function 'Get-RancherLabel'.
VERBOSE: Importing function 'Register-Node'.
VERBOSE: Importing function 'Start-RancherComponent'.
VERBOSE: Importing function 'Stop-RancherComponent'.
VERBOSE: Importing function 'Test-RancherComponent'.
VERBOSE: Importing function 'Test-RancherNetwork'.
VERBOSE: Importing function 'Update-Binaries'.
checking per-host-subnet update
VERBOSE: Importing function 'Add-DebugContent'.
VERBOSE: Importing function 'Add-LogContent'.
VERBOSE: Importing function 'Get-DownloadList'.
VERBOSE: Importing function 'Get-DownloadListByTarget'.
VERBOSE: Importing function 'Get-RancherBasicAuth'.
VERBOSE: Importing function 'Get-RancherBinary'.
VERBOSE: Importing function 'Get-RancherComponentList'.
VERBOSE: Importing function 'Get-RancherLabel'.
VERBOSE: Importing function 'Register-Node'.
VERBOSE: Importing function 'Start-RancherComponent'.
VERBOSE: Importing function 'Stop-RancherComponent'.
VERBOSE: Importing function 'Test-RancherComponent'.
VERBOSE: Importing function 'Test-RancherNetwork'.
VERBOSE: Importing function 'Update-Binaries'.
You cannot call a method on a null-valued expression.
Get error while running startup.ps1

**I re-executed the script and see the below error.**
PS C:\program files\rancher> $obj |& "C:\Program Files\rancher\startup.ps1"
VERBOSE: Importing function 'Add-DebugContent'.
VERBOSE: Importing function 'Add-LogContent'.
VERBOSE: Importing function 'Get-DownloadList'.
VERBOSE: Importing function 'Get-DownloadListByTarget'.
VERBOSE: Importing function 'Get-RancherBasicAuth'.
VERBOSE: Importing function 'Get-RancherBinary'.
VERBOSE: Importing function 'Get-RancherComponentList'.
VERBOSE: Importing function 'Get-RancherLabel'.
VERBOSE: Importing function 'Register-Node'.
VERBOSE: Importing function 'Start-RancherComponent'.
VERBOSE: Importing function 'Stop-RancherComponent'.
VERBOSE: Importing function 'Test-RancherComponent'.
VERBOSE: Importing function 'Test-RancherNetwork'.
VERBOSE: Importing function 'Update-Binaries'.
checking per-host-subnet update
version of per-host-subnet is the same, do nothing
checking agent update
start-service : Failed to start service 'Rancher Agent (rancher-agent)'.
At C:\program files\rancher\startup_agent.ps1:13 char:1
+ start-service rancher-agent
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service]
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

start agent success
create or update agent success
create or update agent success

**I checked the eventviewer.**  **It has the following error**

> "The following information was included with the event: 
> registration failed. err: Get /scripts/api.crt: unsupported protocol scheme ""
> The specified image file did not contain a resource section"

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
