### ISSUE TITLE
Can't authenticate with service account token or x509 client cert

### ISSUE THREAD

**Issue by agasbzj** [rancher/rancher#13525]
First I created a service account and got the service account's token in the secret. Then I put the token in the HTTP Authorization header and call the kubernetes' http api but the result always be
```json
{
    "type": "error",
    "status": "401",
    "message": "must authenticate"
}
```
And if I use the x509 client cert to authenticate, it fails too.
I deployed a kubernetes dashboard, and I used the same token to login, that works.
But if I use the token in the kubeconfig file which is provided in rancher ui (kubeconfig-u-xxxxx:xxxxxxxx), it works.

I wanna know how the rancher generated the token  (kubeconfig-u-xxxxx:xxxxxxxx), and why I failed to authenticate with myself service account token?

**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Comment by agasbzj** [comment]
I found out something. It seems the rancher uses a nginx proxy to the apiserver, and access to the apiserver has only one way: to use rancher's user token, that's why we can't be authenticated directly by the api server. The api server can be access internal only, and since api server is not deployed in kubernetes, so we still need a way to config apiserver.

**Comment by agasbzj** [comment]
Ok I got the solution. Just visit https://host:6443 works perfectly.

**Comment by advancingu** [comment]
@agasbzj I'm facing the exact same issue but I don't understand what you mean with your solution. Do you mean visiting that URL with your browser? What do you have running on that port?
My goal is to use a cluster ServiceAccount with token credentials and I don't want to use a global Rancher user for this task.

**Comment by agasbzj** [comment]
@advancingu Let's say if the url in kubeconfig file that rancher offers you in the rancher's console is **https://111.222.121.122/k8s/clusters/c-xxxx**, just use the address **https://111.222.121.122:6443**, that's the apiserver's address. Then you can use the service account token in your http request to communicate with apiserver.

**Comment by advancingu** [comment]
@agasbzj So if I understand you right, in your example `111.222.121.122` is the Rancher instance IP and you exposed `rancher/rancher` container port `6443` to the outside?

**Comment by agasbzj** [comment]
@advancingu No, it's the apiserver's ip, not rancher's.

**Comment by advancingu** [comment]
Had to go via `View in API` on the Rancher cluster dashboard to get the API server's IP but this worked perfectly in the end. Thanks a lot!
