### ISSUE TITLE
Cant import yaml using full yaml file with '---' in the content.

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/rancher#13523]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Steps to Reproduce:**
When you import yaml in project, ucan't  import a yml file with '---'. It stuck in "saving".

![image](https://user-images.githubusercontent.com/23303886/40100643-404c010e-5917-11e8-9e12-25610eb699e1.png)

If you want to import a yaml like this:
apiVersion: v1
kind: Service
xxx
'---'
apiVersion: v1
kind: Service
xxx

You need to import it twice with out the '---'.

**Comment by jeicoo** [comment]
i experienced this as well. looking forward for this issue to be fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 6/4
Verified fixed
