### ISSUE TITLE
Node Scheduling can't be removed

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#13527]
When you set a node Scheduling, you can't remove it.

Automatically pick nodes for each pod matching scheduling rules:
Can't be removed form a deployment
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/16
Now when I switch to a specific node back to Automatically pick nodes, it never finishes the edit.  The new pod is stuck in pending and the old pod stays active.
![image](https://user-images.githubusercontent.com/11514927/40136117-da001446-58fb-11e8-9883-8ffc0722f265.png)

**Comment by sangeethah** [comment]
Tested with v2.0.3-rc1

This issue is still reproducible.

When I remove the node scheduling rule as part of upgrade ,I dont see pods getting recreated.
Also when I view the workload details, the node scheduling rules are still present.

**Comment by sangeethah** [comment]
Tested with v2.0.3-rc2

Create a workload with node scheduling enabled ( Run all pods for this workload on a specific node or Automatically pick nodes for each pod matching scheduling rules ).
Edit  workload and remove the node scheduling rule.
Workload upgrade succeeds and pods get recreated as expected.
Node scheduling rules get removed in the workload after upgrade as expected.
