### ISSUE TITLE
Reuse ssh keys for Digital Ocean 

### ISSUE THREAD

**Issue by usmanismail** [rancher/rancher#1352]
The digital ocean integration does not allow us to re-use ssh keys when launching hosts. This ends up creating lots of orphan ssh keys in digital ocean.

**Comment by vincent99** [comment]
We're just using docker-machine.  Some drivers clean up after themselves better than others.

**Comment by usmanismail** [comment]
I put in a [pull request](https://github.com/docker/machine/pull/1438) to add the ssh key parameter to the driver. If and when it gets merged then you can update Rancher UI to specify the key ID.

**Comment by deniseschannon** [comment]
@usmanismail Great! When it gets merged, please let us know.

**Comment by vincent99** [comment]
It does not appear there is any interest in merging this upstream.. if you get it please reopen.

**Comment by STRML** [comment]
Merged in https://github.com/docker/machine/pull/3144

**Comment by juanluisbaptiste** [comment]
Hi,

As the upstream missing feature has been merged a couple weeks ago, is there anyone working on this from rancher side ?

**Comment by vincent99** [comment]
This doesn't actually help is at all because the container running machine won't have the private key, which will be needed to SSH to the host and install Docker and the Rancher agent.
