### ISSUE TITLE
Supporting incremental build

### ISSUE THREAD

**Issue by Overv** [rancher/rancher#13528]
Right now Rancher is built by launching a docker container and performing many steps like `go fmt` and running tests. Is there any way to build Rancher more quickly for development purposes?

**Comment by ibuildthecloud** [comment]
@Overv It's really just a go app, nothing special.  The `Makefile` is just for reproducible build, but Rancher developers don't run that for dev.  So just clone Rancher to the proper directory in your go path (`go get -d github.com/rancher/rancher`) and then run `go build -i` in `github.com/rancher/rancher`.

There is one build tag `-tags k8s` this is whether or not you want to embed k8s into Rancher (which is how `docker run ...` works).  For development we typically don't turn that on (and builds will be much faster).  So the short dev workflows is basically.

```shell
# to build
go get -d github.com/rancher/rancher
cd $GOPATH/github.com/rancher/rancher
go build -i

# to run
KUBECONFIG=${HOME}/.kube/config ./rancher
```

Right now we are using go 1.9, but I suspect 1.10 will work fine.  We are going to switch to 1.10 soonish.

If you want to build the docker images then do
```
./scripts/build && ./scripts/package
```
