### ISSUE TITLE
CLI - Workload not being deployed for app install with multiple projects. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13537]
**Rancher versions:**
v2.0.1-rc2: Consistency Changes

Steps:
Create a new cluster.
VIA CLI, install app to default project (mongodb).
Create a new project for cluster.
Switch to new project via CLI.
install app to new project with CLI (mongodb).

Results:
App is listed as active in catalog apps. However, there are no workloads/pods deployed for apps.

This behavior is not seen if adding a new app via UI.

Update: This is because the namespace is already in use when attempting to add a new app in a separate project.  The CLI is not creating a unique namespace if the default is already in use. 

![screen shot 2018-05-16 at 1 07 38 pm](https://user-images.githubusercontent.com/38012481/40141236-2fdea77a-590a-11e8-9b03-ed5256493c5c.png)

![screen shot 2018-05-16 at 1 07 43 pm](https://user-images.githubusercontent.com/38012481/40141243-34d8e83a-590a-11e8-8321-c01ff3e6b5e6.png)

**Comment by deniseschannon** [comment]
Available with CLI v2.0.1-rc3

**Comment by adingilloRancher** [comment]
Verified ability to install same app across multiple projects.
