### ISSUE TITLE
LoadBalancer stuck in Pending

### ISSUE THREAD

**Issue by frkr** [rancher/rancher#13538]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.1-rc1
rancher/agent or rancher/rancher-agent: 

**Docker versions:**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system**
AMI Rancher HVM on amazon

1) Run a Rancher on machine 1

```
docker run -d -p 80:80 -p 443:443 \
--restart=unless-stopped \
--name=rancher \
rancher/rancher:v2.0.1-rc1 \
--acme-domain rancher.teste.work
```

2) Connect a second machine to rancher especifyng the external IP
```
--address 107.23.32.149
```

3) Make a Deploy of "tutum/hello-world" and use LoadBalance on layer 4

The kubernetes will presents this status:

```
> kubectl get all
NAME         AGE
deploy/www   11m

NAME                AGE
rs/www-758c6c99d8   11m

NAME                      READY     STATUS    RESTARTS   AGE
po/www-758c6c99d8-zhbfn   1/1       Running   0          11m

NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
svc/kubernetes         ClusterIP      10.43.0.1       <none>        443/TCP        23m
svc/www                ClusterIP      None            <none>        80/TCP         11m
svc/www-loadbalancer   LoadBalancer   10.43.150.131   <pending>     80:32419/TCP   11m
```

**Comment by Rambou** [comment]
Same issue here also.

**Comment by superseb** [comment]
Sounds like https://rancher.com/docs/rancher/v2.x/en/faq/technical/#why-is-my-layer-4-load-balancer-in-pending-state , did you configure a cloud provider or running a service that can fulfil the request for type `LoadBalancer` ?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by suikast42** [comment]
> I am having this issue; there's precious little information in the https://rancher.com/docs/rancher/v2.x/en/faq/technical/#why-is-my-layer-4-load-balancer-in-pending-state link if you're not using a cloud provider. What LoadBalancer options are available for an on-premises Rancherv2.0/K8s cluster?

Did you solve  the problem ?

**Comment by ssirag** [comment]
Yes, I've installed MetalLB load balancer for on-premise, and it works with the LoadBalancer type.

https://metallb.universe.tf/installation/

**Comment by tomclark** [comment]
> Yes, I've installed MetalLB load balancer for on-premise, and it works with the LoadBalancer type.
> 
> https://metallb.universe.tf/installation/

You sir, are a gentleman and a scholar. Two days I've spent trying to figure out WTF. Two days! I fail at Google. :-(

Thank you to the kind people at MetalLB too, obviously.
