### ISSUE TITLE
[rancher/agent] agents websocket can't connect to rancher server via proxy

### ISSUE THREAD

**Issue by attrib** [rancher/rancher#13531]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.14. and 1.6.17 (tested this before and after upgrade)
rancher/agent or rancher/rancher-agent: 1.6.9 and 1.6.10 (tested this before and after upgrade)

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 0.13.11
network-services: 0.10.2
scheduler: 0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
18.03.0-ce 

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 9 (4.9.0) 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Host <-> Proxy <-> Rancher Server

* Create an environment with one host
* Start host like this: `docker run -e CATTLE_AGENT_IP="x.y.y.x" -e http_proxy="http://proxy:3128" -e HTTP_PROXY="http://proxy:3128" -e HTTPS_PROXY="http://proxy:3128" -e https_proxy="http://proxy:3128" -e no_proxy=127.0.0.1 -e NO_PROXY=127.0.0.1 -e CATTLE_DETECT_CLOUD_PROVIDER=false --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.10 https://rancher.example.com/v1/scripts/xxx:xxx:xxx`

**Results:**

It connects fine at the beginning but hangs later. Rancher UI always shows the host as  reconnecting.

As seen in the log below, normal requests are connecting fine via proxy and can download all configs. But the websocket has a timeout, which is the same result as I would connect to an URL without an proxy. So it seems it doesn't use the http_proxy setting like the other requests do. Is there any workaround for this or any other magic variable to set for the websocket to use the proxy setting?

Also the IP (`y.y.y.y:443`) which is shown on the error message is the IP of `rancher.example.com`. With curl the proxy ip is shown and not the IP of the server, but not sure what rancher agent is outputting here. Just as a note that this is also the reason why I think, the websocket is ignoring the proxy settings.

Rancher agent logs:
```
INFO: Starting agent for F8AADE348AF8965031DB
INFO: Access Key: F8AADE348AF8965031DB
INFO: Config URL: https://rancher.example.com/v1
INFO: Storage URL: https://rancher.example.com/v1
INFO: API URL: https://rancher.example.com/v1
INFO: IP: x.y.y.x
INFO: Port:
INFO: Required Image: rancher/agent:v1.2.10
INFO: Current Image: rancher/agent:v1.2.10
INFO: Using image rancher/agent:v1.2.10
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
INFO: Downloading agent https://rancher.example.com/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading https://rancher.example.com/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-<subtracted>/apply.sh
INFO: Sending configscripts applied 1-<subtracted>
INFO: Updating pyagent
INFO: Downloading https://rancher.example.com/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-<subtracted>/apply.sh
INFO: Updating host-api
INFO: Downloading https://rancher.example.com/v1//configcontent//host-api current=1-<subtracted>
INFO: Already up to date
INFO: Sending host-api applied 1-<subtracted>
INFO: Updating python-agent
INFO: Downloading https://rancher.example.com/v1//configcontent//python-agent current=1-<subtracted>
INFO: Already up to date
INFO: Sending python-agent applied 1-<subtracted>
INFO: Sending pyagent applied 1-<subtracted>
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/agent
INFO: Updating host-config
INFO: Downloading https://rancher.example.com/v1//configcontent//host-config current=host-config-1-<subtracted>
INFO: Already up to date
INFO: Sending host-config applied 1-<subtracted>
time="2018-05-16T13:37:47Z" level=info msg="Launching agent"
time="2018-05-16T13:37:47Z" level=info msg="Listening for events on https://rancher.example.com/v1"
time="2018-05-16T13:37:47Z" level=info msg="launching hostapi"
time="2018-05-16T13:37:47Z" level=info msg="Serialize compute requests: false, driver: overlay2"
time="2018-05-16T13:37:47Z" level=info msg="Initializing event router" workerCount=250
time="2018-05-16T13:37:47Z" level=info msg="Starting event router."
time="2018-05-16T13:37:47Z" level=info msg="Connecting to proxy." url="wss://rancher.example.com/v1/connectbackend?token=<subtracted>"
time="2018-05-16T13:38:17Z" level=error msg="Error subscribing to events: dial tcp y.y.y.y:443: i/o timeout" subscribeUrl="wss://rancher.example.com/v1/subscribe?eventNames=compute.instance.activate&eventNames=compute.instance.force.stop&eventNames=compute.instance.inspect&eventNames=compute.instance.remove&eventNames=storage.image.activate&eventNames=compute.instance.deactivate&eventNames=compute.instance.pull&eventNames=storage.volume.activate&eventNames=storage.volume.remove&eventNames=ping&eventNames=config.update"
time="2018-05-16T13:38:17Z" level=fatal msg="Exiting. Error: Error encountered while running event router: dial tcp y.y.y.y:443: i/o timeout"
```

**Comment by cjellick** [comment]
What proxy are you using? Are you sure it supports webhooks? Is it configured properly to allow long-lived connections? When I've seen this problem in the past, that has been the typical cause. This has been tested and verified as working in the past and we have other users successfully deployed in this mode.

**Comment by attrib** [comment]
Thx for the answer, I'm still in contact with the customer as the rancher hosts are inside the customer network, while the rancher server is inside our network. So I do not have direct access to the proxy.

Any ideas how I could test websockets on the cli on the host server to test if its a proxy problem or if the proxy is not used in that case correctly?

**Comment by cjellick** [comment]
Hm. Our cli doesn’t utilize websockets. Later today I’ll see if we have any diagnostic scripts, but I’m not sure that we do.

On May 22, 2018, at 3:43 AM, Karl Fritsche <notifications@github.com<mailto:notifications@github.com>> wrote:


Thx for the answer, I'm still in contact with the customer as the rancher hosts are inside the customer network, while the rancher server is inside our network. So I do not have direct access to the proxy.

Any ideas how I could test websockets on the cli on the host server to test if its a proxy problem or if the proxy is not used in that case correctly?

**Comment by attrib** [comment]
Closing this issue, our customer now opened the firewall for our IP. They didn't wanted to change anything on their proxy.
