### ISSUE TITLE
Service port is exposed when creating an ingress point to it

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#13545]
I'm not sure if this the desired behavior but the service port should not be exposed when creating 
an ingress to it.

* Ingress
![selection_062](https://user-images.githubusercontent.com/3356468/40150786-caf28f5e-59b6-11e8-8b65-254e67fb43f7.png)

* Workload
![selection_061](https://user-images.githubusercontent.com/3356468/40150789-cd2ec4cc-59b6-11e8-87f8-48fbd4b35a68.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`containers.index`|

**Comment by loganhz** [comment]
Duplicated of https://github.com/rancher/rancher/issues/13717

Please see https://github.com/rancher/rancher/issues/13717#issuecomment-392113145
