### ISSUE TITLE
Longhorn app from Rancher library not properly deleted. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13541]
**Rancher versions:**
Master 5/16/18

Steps:
Create a new cluster.
In default project > Catalog Apps => Add Longhorn.
Delete longhorn from catalog apps. 

Results:
All associated workloads are deleted, minus one.

![screen shot 2018-05-16 at 2 56 10 pm](https://user-images.githubusercontent.com/38012481/40146142-4f106caa-5919-11e8-87f0-68e39f0a7555.png)

Associated logging error 
`E0516 21:56:07.105223       1 generic_controller.go:204] AppController project-4nt9g/longhorn-7esry9 [helm-controller] failed with : failed to remove finalizer on project-4nt9g:longhorn-7esry9`

**Comment by StrongMonkey** [comment]
longhorn-felexvolume-driver is not directly launched by helm charts, so we are not deleting it. Need to think about it.
