### ISSUE TITLE
Health check set host header unable to save

### ISSUE THREAD

**Issue by pobear** [rancher/rancher#13547]
Health check set host header unable to save. And set addtional header the same
edit deployment by kubectl edit,  add  httpHeaders
```      livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: notice.ay.jzb.com
            path: /status/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: django
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: notice.ay.jzb.com
            path: /status/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
```

Health check can't parse params
![default](https://user-images.githubusercontent.com/1791637/40153740-ca2cc1aa-59bd-11e8-81e6-8a3badddf3ae.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/17
The UI is posting the httpHeaders, but the API is not returning it.  If this is an invalid format we should let the user know.

**Comment by san4io** [comment]
v2.1rc3 have same issue.

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/issues/16853
