### ISSUE TITLE
Purge Host/Container should clean up database

### ISSUE THREAD

**Issue by sepiroth887** [rancher/rancher#1355]
Got a couple issues with node cleanup in Rancher. 

If for whatever reason I deactivate a host and purge it, the DB still holds references to it. This prevented me from adding a host on the same machine (same IP, same hostname) back to the cluster. 

It seems to manifest itself as ping timeouts from agent to server. 

Is it possible to clear purged machines from the DB?

**Comment by ibuildthecloud** [comment]
Can you share the version you are running?  Just click the cow in the upper left of the UI.  When you deleted the host from the UI was it in a "reconnecting" state?

**Comment by sepiroth887** [comment]
CATTLE_RANCHER_SERVER_IMAGE=v0.24.0
DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/0.28.0

The host was indeed in reconnecting state. It got a bit messed up while experimenting with SSL termination, and the agent got a bit confuses as to where to find the server. Figured turning it on and off again would be a good idea. Didn't expect state to get in the way though :D

**Comment by sepiroth887** [comment]
I should probably mention a few changes to the DB were done via the API : 

change websocket protocol to wss instead of ws and change api.host setting so it doesn't include the protocol (http/https) 

The agent was started with the protocol being implicit but even then it would register, then ping timeout and reregister over and over again. I have nginx in front of it rewriting http://{rancherURI} to https://{rancherURI} and I can see the register and wss connections succeeding fine.

**Comment by sepiroth887** [comment]
Looks like my main issue (ping timeout) was related to Nginx after all. However i notices DB bloat (got like 10 hosts and the DB is already 600+ mb in size... ) which seems to come from event storage. Is this eventually cleaned up?

**Comment by ibuildthecloud** [comment]
@sepiroth887 We have some other known issue with deleting hosts that weren't fixed until v0.26.0, but glad to hear you resolved your issue.

Honestly, our database can get massive quickly.  There's a couple tables that grow fast and we don't purge them.  We should and we should create an issue for that to make sure we get that done soon.  

@deniseschannon Is there an existing issue for the DB size?

**Comment by deniseschannon** [comment]
Created a new issue for database cleanup. #1525. Closing this issue in favor of that one.
