### ISSUE TITLE
Cluster in unavailable state shows green components and counter/gauges

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13555]
**Rancher versions:**
rancher/rancher: master 05/17
rancher/rancher-agent: master 05/17

Steps to reproduce:
- Create a custom cluster and one host
- Destroy host on the cloud provider

Result:
<img width="1270" alt="screen shot 2018-05-17 at 12 39 12" src="https://user-images.githubusercontent.com/2620179/40172669-9c4b59ba-59cf-11e8-922a-7e28d55f6de8.png">

Even with the banner, the components and gauges should go to Unknown as this is misleading.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
