### ISSUE TITLE
Some issues about aliyun driver

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#13550]
**Rancher versions:** 
rancher/server or rancher/rancher: 
v2.0.1-rc1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Aliyun
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

1. The Security Group drop-down box should show the security group name for easy lookup
![image](https://user-images.githubusercontent.com/19684717/40155497-a7431370-59c6-11e8-86d4-f8d522773d31.png)

2. We should support custom mirroring, otherwise I have not been able to create clusters using rancheros
3. If the Available Zone is not empty in the template and vpc and vswitch are empty, adding a cluster fails
```
2018/05/16 05:29:06 [INFO] Generating and uploading node config test1
E0516 05:29:21.837480       1 generic_controller.go:204] NodeController c-q58q5/m-p6q7g [node-controller] failed with : Error setting machine configuration from flags provided: test1 | aliyunecs driver requires both the --aliyunecs-vpc-id and --aliyunecs-vswitch-id for Virtual Private Cloud
```
4. Modify aliyun node template, all the drop-down box values become the default value
5. Private Address Only is set to x.x.x.x when I add a template. Using this template to launch the cluster, I see that the instance's IP is randomly assigned.
6. I think we should cancel the privateAddressOnly option, because after setting true, the instance cannot access the public network and cannot pull the image.
7. In Aliyun template, I don't know how to use "Route CIDR". I tested setting Route CIDR to "x.x.x.x/x" and pvc and vswitch are empty. Failed to add a cluster using this template
```
2018/05/17 01:57:46 [INFO] Generating and uploading node config hailong-test-cidr1
E0517 01:58:01.891051       1 generic_controller.go:204] NodeController c-q6kvt/m-9jw2v [node-controller] failed with : Error setting machine configuration from flags provided: hailong-test-cidr1 | aliyunecs driver requires both the --aliyunecs-vpc-id and --aliyunecs-vswitch-id for Virtual Private Cloud
```
8. After adding the aliyun template and setting the Available Zone and VPC, all VSwitches are displayed in the VSwitch drop-down box. This is wrong because each vswitch belongs to only one Available Zone
![image](https://user-images.githubusercontent.com/19684717/40158016-d012808e-59d4-11e8-9873-d9c60aeee090.png)

![image](https://user-images.githubusercontent.com/19684717/40158120-538133e8-59d5-11e8-9bb0-7579b3f89ee8.png)
9. Like the above problem, different Available Zone will have different templates. Not all templates should be displayed in the Instance Type drop-down box
10. "Available Zone" should be placed on the right side of "Region"

**Comment by orangedeng** [comment]
I will check for 7 and 3

**Comment by kingsd041** [comment]
`4. Modify aliyun node template, all the drop-down box values become the default value` has not been fixed, I can't close this issue yet

**Comment by deniseschannon** [comment]
@loganhz can you look at this? ^^ do you have the PR that would fix it?

@kingsd041 It might not have made it into 2.0.1/2 due to timing.

**Comment by kingsd041** [comment]
Tested with rancher/rancher:master 06/11
`4. Modify aliyun node template, all the drop-down box values become the default value` has been fixed, I will close this issue
