### ISSUE TITLE
2.0.0: kubectl version in Launch kubectl does not match cluster

### ISSUE THREAD

**Issue by bjornmagnusson** [rancher/rancher#13554]
kubectl version when launched from UI does not match the version of the cluster.
Expected output:
> kubectl version --short
Client Version: v1.9.7
Server Version: v1.9.7

Actual:
# Run kubectl commands inside here
# e.g. kubectl get all
> kubectl version --short
Client Version: v1.8.9-rancher1
Server Version: v1.9.7

**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0
rancher/agent or rancher/rancher-agent: v2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.9-rancher1", GitCommit:"68595e18f25e24125244e9966b1e5468a98c1cd4", GitTreeState:"clean", BuildDate:"2018-03-13T04:51:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Docker version: (`docker version`,`docker info` preferred)**
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64
 Experimental:    true

docker info
Containers: 40
 Running: 26
 Paused: 0
 Stopped: 14
Images: 26
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 7.639 GiB
Name: se-centos-bjma-k8s
ID: BFUC:COHW:AKSO:ODQT:A63I:NH75:HJKA:UQWA:JRG4:N47F:HNMO:HBL3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 151
 Goroutines: 151
 System Time: 2018-05-17T12:33:10.308006117+02:00
 EventsListeners: 0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

uname -r
3.10.0-693.21.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal / VM. Custom cluster used

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by superseb** [comment]
Yes the kubectl shell is a static version, I think having multiple versions will be hard to maintain and it should be compatible. Seeing the compatibility described [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew), we should at least upgrade to 1.9 to be compatible for 1.8, 1.9, 1.10.

**Comment by superseb** [comment]
When 1.11 releases, 1.8 will be out of support. In that case we can directly upgrade to kubectl 1.10

**Comment by Itiho** [comment]
#13925

**Comment by deniseschannon** [comment]
We have upgraded kubectl version in the shell to be v1.9.8.

**Comment by adingilloRancher** [comment]
Master 6/27/18

Verified version 1.9.8 is present.

**Comment by Itiho** [comment]
1.9 no have top command
