### ISSUE TITLE
More descriptive label for IAM profile when creating EC2 nodes

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13553]
Users get confused what to put in `IAM Profile` when creating EC2 node. (name vs ARN)

This can be made more clear by changing it to `IAM Instance Profile Name` and a placeholder.

**Comment by tfiduccia** [comment]
@westlywright - The title was changed but no suggested text in the field (I assume that is what he means by placeholder)
![image](https://user-images.githubusercontent.com/11514927/40385402-5292f55e-5dbb-11e8-8514-5568f12e1db1.png)

**Comment by superseb** [comment]
This was resolved in https://github.com/rancher/ui/pull/1925 and shipped in v2.0.1/v2.0.2

<img width="689" alt="screen shot 2018-05-29 at 13 04 44" src="https://user-images.githubusercontent.com/2620179/40655229-fff6bfac-6340-11e8-918b-e601f9ada800.png">
