### ISSUE TITLE
Azure AKS UI Display Client Secret in clear

### ISSUE THREAD

**Issue by david-maumenee** [rancher/rancher#13551]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0

**Steps to Reproduce:**
Add Azure Container Service Cluster during a demo.

**Results:**
Everyone can see our client secret :-(
![rancher2-aks-secret](https://user-images.githubusercontent.com/4135760/40162156-4c5c5c2c-59b3-11e8-8b69-3f3ee55df406.PNG)

**Workaround:**
Edit the html content with browser devtool to set the field type to "password"

**Comment by superseb** [comment]
This is fixed in https://github.com/rancher/ui/commit/7a3aea72b3ad89d8b68cea13aa9034a0d99d919c and will be in v2.0.1
