### ISSUE TITLE
Running `rancher start` starts all containers in all stacks [cli] 

### ISSUE THREAD

**Issue by aaronkjones** [rancher/rancher#13566]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.8

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.13.7
network-services: 0.9.5
scheduler: 0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.09.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS (4.4.0)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
exec `rancher start`

**Results:**
All containers in all stacks are started.
It should probably print its usage like `docker start` does:

```
docker start
"docker start" requires at least 1 argument.
See 'docker start --help'.

Usage:  docker start [OPTIONS] CONTAINER [CONTAINER...] [flags]

Start one or more stopped containers
```

Or, the usage should be updated to read something like
```
start, activate   Start or activate service, container, host, stack **(Starts all containers when no argument given)**
```

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
