### ISSUE TITLE
ability to filter what's being sent for collection to logs

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#13561]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
N/A

**Docker version: (`docker version`,`docker info` preferred)**
N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
N/A

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
N/A

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
[Splunk licensing model](https://www.splunk.com/en_us/software/pricing.html) is billed per ingested GB, per month.  The shear volume of data that is forwarded to splunk will put an undue financial hardship on anyone trying to ingest data coming from Rancher.  There needs to be a pre-send filtering ability to make this useful.

**Results:**

**Comment by loganhz** [comment]
We are going to add a fluentd app in catalog. So user can deploy the fluentd via catalog and configure the filtering rules.

**Comment by kingsd041** [comment]
Fluentd still can't work, wait for me to verify https://github.com/rancher/charts/issues/117 and then close this issue

**Comment by kingsd041** [comment]
Version: master 2.2 (2/2/19) 
Confirmed fix. 
@JasonvanBrackel  We add a `fluentd` app to the catalog to solve your needs.
