### ISSUE TITLE
Splunk Logging Integration (HTTP Event Collector) cannot communicate over HTTPS

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#13560]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
N/A

**Docker version: (`docker version`,`docker info` preferred)**
N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
N/A

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
N/A

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
The Splunk integration communicates over by being forwarded from fluentd via the Splunk HTTP Event Collector.  In order to communicate to the Splunk HTTP Event Collector over https, the sender must be able to validate the certificate chain of the https endpoint receiving the data.  This does not appear to be possible in Rancher today.

**Results:**

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/10

Setup Splunk and enabled SSL on HTTP Event Collector
Enabled Splunk logging over SSL on Rancher

Logs were pushed to Splunk successfully.
