### ISSUE TITLE
[cli] Wait for namespace to be ready

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#13567]
When deploying an app it creates a namespace, this namespace may not be ready when attempting to launch the app. The cli should wait for the namespace to be ready before proceeding.

**Comment by deniseschannon** [comment]
Available with 2.0.1-rc4

**Comment by bmdepesa** [comment]
2.0.1-rc4

Installed several apps, and saw the namespace being created before app was launched. No errors when creating apps.
