### ISSUE TITLE
Issue with Active Directory authentication and server custom port

### ISSUE THREAD

**Issue by bigbrozer** [rancher/rancher#13570]
Hi !

I'm currently switching from Rancher 1.6 to 2.0 (great work by the way !!). When configuring back the AD authentication, I need to set port 3268 instead of the default 389. I can successfully test the connection using the **Authenticate** button but in the UI I'm still seeing the port 389 and if I click **Save** this is that port which override the custom one...

Set a custom port:

![set_ad_custom_port](https://user-images.githubusercontent.com/218972/40199503-fef85a14-5a19-11e8-89ae-a6debd8c0c02.jpg)

**Authenticate**, but still see something different:

![ad_custom_port_revert](https://user-images.githubusercontent.com/218972/40199504-ff1740a0-5a19-11e8-839c-f2471a023d4f.jpg)

When saving, authentication does not work...

Thanks !

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`global-admin.security.authentication.activedirectory`|

**Comment by vincent99** [comment]
Fixed, but this is just a display problem unless you toggled TLS or something similar after entering the port;  The "if you toggle TLS and the port was 389/636 you probably want the other one now" logic was just always setting it back to 389 if TLS is off, and that's firing for display but it would normally have already been saved correctly.  Before fixing I was still able to save a non-standard port (and then it displayed wrong).

**Comment by bigbrozer** [comment]
Many thanks ! Sorry, my bad, seems there was a some troubles with DNS and AD at time of testing :-( I confirm this is a display problem. Things are working properly :-)

**Comment by tfiduccia** [comment]
@bigbrozer - this has been fixed and will be in next release.  Let me know if you have other problems.
