### ISSUE TITLE
Powering down host in rke cluster , does not result in the node state being reflected in the local kubernetes cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13578]
Rancher server version - v2.0.1-rc2

Steps to reproduce the problem:

Created a 3 node(all roles) HA cluster setup.
Local cluster synced to rancher server as expected with 3 nodes.
Create DO cluster and provision few workloads.

Using RKE , take etcd snapshot.
Power down 2 of the nodes (to simulate etcd quorum loss)
This results in rancher-server being unreachable.

Using RKE , do etcd recover snapshot.
Kubernetes cluster recovers as expected at this point.
But the powered down nodes continue to be listed in "Ready" state when viewing them using ```kubetcl get nodes``` command.

Since the hosts never go to unready state , rancher server that was in one of the powered down nodes nerver got to move to another node.

Only after Using RKE  to remove the 2 nodes that were powered down , the nodes get to deleted from the cluster and rancher-server fails over.

We should not have to remove the nodes from RKE, for rancher-server fails over to happen.

**Comment by deniseschannon** [comment]
This is an issue with k8s where after being restored, it's not recognizing the powered down nodes as powered down and they remain in `Ready` state. 

A workaround for now is to remove those nodes to trigger the fail over to move rancher server to another node.
