### ISSUE TITLE
Can not edit upgrade policy for workload

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13584]
Rancher versions:
rancher/rancher:v2.0.1-rc2

Steps:

1. Create a workload with upgrade strategy `Rolling: start new pods, then stop old`
2. Upgrade the workload and change the strategy to `Kill ALL pods, then start new`

Results:

Upgrade failed with error `Validation failed in API: Deployment.apps "abcd" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'`

**Comment by prachidamle** [comment]
As mentioned in https://github.com/kubernetes/kubernetes/issues/24198 this error is not seen when updating the k8s deployment resource with: 
`
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: nil
`

**Comment by sangeethah** [comment]
Tested with latest build from master

Able to edit upgrade policy for workload when upgrading workloads.
