### ISSUE TITLE
Memory usage reported in Rancher UI is totally off

### ISSUE THREAD

**Issue by tkuther** [rancher/rancher#13583]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.1-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 @ 4.4.0-87-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
ESX

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
rke custom nodes

**Steps to Reproduce:**
* Login in to Rancher
* View memory usage of the cluster, or that of single nodes in nodes tab
* compare to prometheus stats, docker stats output, top, vmstat, etc on nodes

**Results:**
Rancher shows:
![mem_rancher](https://user-images.githubusercontent.com/63717/40228469-a8374b22-5a91-11e8-8afa-5c6dea763c2f.png)
Data from Prometheus:
![mem_prometheus_grafana](https://user-images.githubusercontent.com/63717/40228521-bcaac480-5a91-11e8-9c8c-421fd299257a.png)
The prometheus data matches the one reported from "docker stats" on the node, e.g. for that gitlab instance:
```
CONTAINER ID        NAME                                                                                        CPU %               MEM USAGE / LIMIT     MEM %
3dd3ede638bb        k8s_gitlab_gitlab-6dcd58f588-7lxr6_gitlab-external_5ab3e7bc-52f5-11e8-bf25-005056a8606f_0   3.76%               10.37GiB / 54.87GiB   18.89%
```

**Comment by tkuther** [comment]
It seems Rancher shows the total requested memory (like "kubectl describe nodes"), not the actual node memory usage.

This might be pretty misleading if most pods run unlimited.

**Comment by tfiduccia** [comment]
Workloads in general don't automatically reserve memory, which is why you probably don't see it going up.  But I just verified that this is working how it's supposed to.  When creating a workload, you can force memory reservation under Advanced options - Security & Host Config section.
![image](https://user-images.githubusercontent.com/11514927/40518514-eb4ec5c4-5f6f-11e8-94d4-c357d1ea96cd.png)

**Comment by hameno** [comment]
Please consider improving this. It is pretty much useless now. You simply cannot see the real state of the cluster. It also counts NoSchedule master nodes and does not reflect the real usage.

**Comment by tkuther** [comment]
I've seen nodes go (b)OOM because workloads got scheduled to them which they actually couldn't handle. I'm not sure if this is intended behaviour, but in the end it made me monitor pods more closely and define proper memory resource requests for nearly all of them. That's perfectly fine, and the cluster runs pretty stable now.

Just some rancher-internal things don't do that, like fluentd which seems quite memory hungry for a log shipper, and cattle-node-agent which seem to leak memory in an almost linear fashion.
