### ISSUE TITLE
Accessing the Kubernetes Dashboard in Rancher 2.0

### ISSUE THREAD

**Issue by fbotha-stratuscloud** [rancher/rancher#13586]
##### Environment

Heapster version: 0.2.9
Dashboard version: 0.6.3
Rancher version: 2.0.0
Kubernetes version: v1.10.1-rancher1
Operating system: Ubuntu 16.04 LTS

##### Steps to reproduce
Deploy heapster using kubernetes helm chart in Rancher 2.0 Catalog Apps
Deploy kubernetes-dashboard using kubernetes helm chart in Rancher 2.0 Catalog Apps
Run kubectl proxy
Access http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

##### Observed result
Rancher 2.0 returns 404 - The page you were looking for doesn't exist!

##### Expected result
Expected to see the Kubernetes Dashboard

##### Comments
Haven't been able to get the Kubernetes Dashboard working on Rancher 2.0.
Any assistance would be appreciated.

**Comment by fbotha-stratuscloud** [comment]
Also tried accessing http://localhost:8001/k8s/clusters/c-cdlfs/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy

Which results in a {"type":"error","status":"401","message":"must authenticate"}

**Comment by StrongMonkey** [comment]
@fbotha-stratuscloud can you try https://rancher-url/k8s/clusters/c-cdlfs/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/ ?

**Comment by haisum** [comment]
@StrongMonkey  URL you gave works but now I can't login with kube config from Rancher, it says Authentication failed. Please try again.

![image](https://user-images.githubusercontent.com/911409/40311544-1f92524a-5cde-11e8-83fa-438a8bdab12c.png)

**Comment by mion00** [comment]
I had the same problem as @haisum.
According to the [dashboard docs](https://github.com/kubernetes/dashboard/wiki/Access-control#kubeconfig) only options available using `authentication-mode` flag are supported via kubeconfig file. This flag only supports basic auth and token. According to the generated kubeconfig file, I imagine that rancher configures with k8s with TLS certificates authentication.

**Comment by haisum** [comment]
I was able to login by generating tokens as described in https://stackoverflow.com/questions/46664104/how-to-sign-in-kubernetes-dashboard

**Comment by fbotha-stratuscloud** [comment]
Thanks for all the feedback, managed to get this working using the below configuration on Rancher 2.0 Catalog Apps.

Rancher Version: `v2.0.0`
Kubernetes Dashboard Helm Chart Version: `v0.5.3`
Kubernetes Dashboard Version: `v1.8.1`

Parameter | Description | Default
-- | -- | --
image.repository | Repository for container image | gcr.io/google_containers/kubernetes-dashboard-amd64
image.tag | Image tag | v1.8.1
image.pullPolicy | Image pull policy | IfNotPresent
extraArgs | Additional container arguments | []
nodeSelector | node labels for pod assignment | {}
service.externalPort | Dashboard internal port | 80
service.internalPort | Dashboard external port | 80
ingress.annotations | Specify ingress class | kubernetes.io/ingress.class:   nginx
ingress.enabled | Enable ingress controller resource | false
ingress.hosts[0] | Dashboard Hostnames | kubernetes-dashboard.local
ingress.tls | Ingress TLS configuration | []
Resources | Pod resource requests & limits | limits: {cpu:   100m, memory: 50Mi}, requests: {cpu: 100m, memory: 50Mi}
rbac.create | Create & use RBAC resources | true
rbac.serviceAccountName | ServiceAccount kubernetes-dashboard   will use (ignored if rbac.create=true) | default

From Kubernetes Dashboard Helm Chart Version: `v0.6.0` onwards ssl has been enabled by default inside the kubernetes dashboard container thus causing `http: TLS handshake error from x.x.x.x:xxx: tls: first record does not look like a TLS handshake` errors.

**Comment by afgane** [comment]
Did you do the launch using just the Rancher catalog app UI? From the Helm Stable catalog? Other than trying different chart versions, I don't see any config options and once launched, I get the following error in the container logs:
```
2018/06/06 04:12:12 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2018/06/06 04:12:12 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
panic: secrets is forbidden: User "system:serviceaccount:kubernetes-dashboard:default" cannot create secrets in the namespace "kube-system"
```

**Comment by smazurov** [comment]
@afgane i was able to bypass this by adding `kube-system` namespace into my project where I was trying to deploy `kubernetes-dashboard`. It seems like `kube-system` namespace for dashboard is required according to this: https://github.com/kubernetes/dashboard/issues/2655

**Comment by Coopyrightdmin** [comment]
Hi,
Installing dashboard from the catalog in the kube-system namespace then, following @superseb process presently works fine: https://gist.github.com/superseb/3a9c0d2e4a60afa3689badb1297e2a44#step-4-create-serviceaccount-and-token-to-login

**Comment by superseb** [comment]
The dashboard has been removed from our catalog because it wasn't working as it should (out of the box). We'll be introducing it again when it does work. In the meantime, there are alternatives mentioned in this issue.

Let me know if you are still experiencing issues.

**Comment by JingangLi** [comment]
@superseb 
I follow the Rancher guide to install the last verison of Rancher 

Component | Version
-- | --
Rancher | v2.0.6
User Interface | v2.0.61
Helm | v2.8.0-rancher3
Machine | v0.14.0-rancher4-1

I can find the kubernetes dashboard in catalog apps from helm now. Does it means it works now, as you mentined dashbaord has been removed because it wasn`t working as it should.

Rgds,
Jingang

**Comment by micw** [comment]
Another option is to deploy the dashboard along with an admin-privileged role (https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges). This means that anyone who has dashboard access can do everything in the cluster which might be ok for some environments.
If the dashboard is not exposed externally, it can be reached via https://YOUR-RANCHER-SERVER/k8s/clusters/c-CLUSTER-ID/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ and can be accessed by all rancher users that are allowed to access this cluster.
