### ISSUE TITLE
[Feature Request] SSH Access to specific node just like kubectl access

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#13587]
Hello, 

I was needing access to a specific node and thought it would be useful to have an option on a node to ssh into it just like when I click the kubectl button for the cluster. This would make managing the node a bit easier than having to download the keys for each node to ssh into them.

**Comment by loganhz** [comment]
Please try `rancher ssh`. Please let me know if you still want to ssh to the node in UI. 

```
 ./rancher ssh --help
SSH into a node

For any nodes created through Rancher using docker-machine,
you can SSH into the node. This is not supported for any custom nodes.

Examples:
  # SSH into a node by ID/name
  $ rancher ssh nodeFoo

  # SSH into a node by name but specify the username to use
  $ rancher ssh -l user1 nodeFoo

  # SSH into a node by specifying user and node using the @ syntax while adding a command to run
  $ rancher ssh user1@nodeFoo env

Usage:
  rancher ssh [NODE_ID/NODE_NAME]
```
