### ISSUE TITLE
Docker image 2.0.x

### ISSUE THREAD

**Issue by wormen** [rancher/rancher#13588]
when in `hub.docker.com` will image for version 2.x ?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/releases/tag/v2.0.0

```Versions
NOTE - Image Name Changes: Please note that as of v2.0.0, our images will be rancher/rancher and rancher/rancher-agent. If you are using v1.6, please continue to use rancher/server and rancher/agent.

rancher/rancher:v2.0.0
rancher/rancher-agent:v2.0.0```

**Comment by wormen** [comment]
![image](https://user-images.githubusercontent.com/8462339/40262520-ea4aaad4-5b42-11e8-9003-cdb40733ea9b.png)

![image](https://user-images.githubusercontent.com/8462339/40262521-ede035e2-5b42-11e8-802d-64269fcc8938.png)

**Comment by vincent99** [comment]
Again, 2.0 is now in `rancher/rancher`, not `rancher/server`.  `rancher/server` and its `latest` and `stable` tags will continue to be for 1.x.
