### ISSUE TITLE
Amazone only region us-west-2 support EKS

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#13598]
Now we could only use Amazone EKS on region us-west-2, this may block our feature to let user change region @nathan-jenan-rancher

**Comment by nathan-jenan-rancher** [comment]
Currently EKS is not available outside the us-west-2 region, we will need to wait for AWS to add support for other regions before we can incorporate this into Rancher.  Should leave this open to track.

**Comment by go** [comment]
EKS has released GA on us-east and us-west region. Any update for this issue to support multi region deployment?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13857

**Comment by akabdog** [comment]
actually #13857 fixes the S3 bucket templates but there is still a problem with supporting the regions:
when selecting region us-east-1 in rancher the EKS cluster actually shows up in us-west-2.
I'm running master released today, version f67b3e7

**Comment by superseb** [comment]
see https://github.com/rancher/rancher/issues/14064

**Comment by superseb** [comment]
In v2.0.3, we will support the two regions EKS is supported in when GA. When new regions are announced, we can follow up with new issues as keeping this open doesn't really add any value as we wait till AWS announces new regions.
