### ISSUE TITLE
Scaling of nodes is not supported in EKS cloud container service

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#13596]
Right now scaling of EKS nodes is not supported.

This is not straightforward to implement because the worker nodes are controlled via a cloud formation stack that is spun up as the final step of provisioning the EKS cluster (`https://amazon-eks.s3-us-west-2.amazonaws.com/1.7.10/0.1/nodegroup_cloudformation.yml`).

In order to modify the number of nodes, we'll need to either find a way to either
1) modify the cloud formation stack to include more nodes and then update it (not sure if updating a stack is possible)
2) add an additional stack with the correct number of nodes and then assign it to Kubernetes, then unassigned the old nodes (might lose workloads or cause other problems if we do it this way)
3) rework the code to spin up 1 stack for each node so they can be controlled easier

Also we currently use the stack definitions that AWS hosts, we would need to host our own definitions if we went this route or possibly rework the code to include the stack definitions (if possible).

**Comment by akabdog** [comment]
FYI, manual workaround of changing the ASG in AWS UI seems to work for now.

**Comment by nathan-jenan-rancher** [comment]
This will be address in the node pools as a first class resource issue:
https://github.com/rancher/rancher/issues/17095

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/15773

**Comment by sergiomacedo** [comment]
> FYI, manual workaround of changing the ASG in AWS UI seems to work for now.

If this can be done via AWS UI, can't it be passed to it via Rancher UI by editing the cluster once again?
