### ISSUE TITLE
[Question/Feature Request] Support for Windows 2016 in rancher 2.0 version

### ISSUE THREAD

**Issue by rammaram06** [rancher/rancher#13599]
Hi,

We are planning to use rancher to setup kubernetes cluster in our environment, our environment is mostly windows servers. I don't see any where about windows support, does rancher 2.x support windows? If not when can we expect rancher to support windows? Thanks for your help!

**Comment by superseb** [comment]
Windows support is planned for 2.1, see https://github.com/rancher/rancher/wiki/Rancher-2.1. More details will become available when we have them.
