### ISSUE TITLE
Ability to import docker for mac cluster

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#13590]
**Rancher versions:**

- CATTLE_SERVER_VERSION = v2.0.0
- CATTLE_AGENT_IMAGE = rancher/rancher-agent:v2.0.0

**Docker version: (`docker version`,`docker info` preferred)** `18.05.0-ce`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** `4.9.87-linuxkit-aufs`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** `Docker for Mac Kubernetes`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** `Single node Rancher`

**Steps to Reproduce:**

- Stand up Rancher server
- Update Rancher to use the public IP for Docker for Mac (192.168.53.x)
- Enable Kubernetes on Docker for Mac
- In Rancher, click Import cluster
- Apply the Rancher generated manifest to the cluster
- Check pod logs

**Results:**

After examining the pod logs for the Rancher components, it looks like they try to use `localhost` to connect to the Rancher server, even after updating the connection URL inside Rancher.

How do you tell Rancher server to use the public IP of the Docker for Mac cluster instead of localhost when importing a cluster into Rancher?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14358
