### ISSUE TITLE
[Feature Request] Shared Node Templates

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#13591]
#I would like to be able to share node templates between the other admin users that are managing the clusters. Right now it seems like it is per user. We are having to share a single admin account to be able to provision new clusters with the same config.

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/12186

**Comment by mitchellmaler** [comment]
Nice! Missed that one. I'll follow that issue.
