### ISSUE TITLE
Github organisation retrival bug

### ISSUE THREAD

**Issue by moimael** [rancher/rancher#1359]
Hi,

When I want to edit a rancher environment, I get a display error when retrieving my Github organization. The error is : TypeError: e is undefined

Check the attached image : 

![edit_org](https://cloud.githubusercontent.com/assets/1479859/8405842/c10b7b92-1e57-11e5-83e8-6b9b6f60c691.png)

**Comment by deniseschannon** [comment]
@hibooboo2 can you take a look at this? This looks similar to #1354

**Comment by deniseschannon** [comment]
@moimael We've recently added LDAP into Rancher as of v0.34.0, and changed the API for authentication to be more generic. I haven't been able to reproduce this issue. If you still have it, please re-open.
