### ISSUE TITLE
Unable to create custom GCE cluster with public IP defined

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13604]
**Rancher versions:**
v2.0.1.-rc3

**Steps to Reproduce:**
Create a new custom cluster with GCE hosts.
When adding nodes to rancher on GCE hosts, add external and internal IP address of host. 

**Results:**
Unable to provision cluster.

`Failed to apply the ServiceAccount needed for job execution: Post https://35.197.58.208:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: net/http: TLS handshake timeout`

**Comment by deniseschannon** [comment]
@adingilloRancher how are you adding the external/internal IP address in your docker command?

**Comment by adingilloRancher** [comment]
Sample command used

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.1-rc5 --server https://206.189.163.236 --token kvw47zccc4jqjmkc5dtgz7j7fh2tdq9d5hn4z5zdfdhnh7nj2sw845 --ca-checksum a8e31d874da3cc1e0191a1d48d800edaaeb9696010758cec23c5a6a08692ec17 --address 192.168.1.1 --internal-address 10.20.10.6 --worker

**Comment by StrongMonkey** [comment]
@adingilloRancher i was managed to get this working. The steps i took:
1. create a gce instance. Create a custom cluster in rancher.
2. Specify the public ip and private ip, paste the command to gce instance and execute.
3. Cluster was created successfully.

Are you testing with the same step? can you please re-verify the bug in the latest release?

**Comment by adingilloRancher** [comment]
Master 6/15/18

Not able to reproduce in latest release.
