### ISSUE TITLE
We have 19 pods deployed but None show in the Workload Tab, 

### ISSUE THREAD

**Issue by kanwarb** [rancher/rancher#13606]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by tkuther** [comment]
Objects in namespaces that aren't assigned to a project don't show up anywhere in the UI. You'd need to move those namespaces to a project.

**Comment by superseb** [comment]
Let us know if that doesn't explain the behavior you are seeing.
