### ISSUE TITLE
Warning seen when admin user password is reset on HA cluster with external etcd

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13601]
**Rancher versions:**
rancher/rancher: v2.0.1-rc3

1. Create a HA cluster with external etcd
2. Reset the password using the command
"docker exec abc reset-password"

A warning is seen as below:
```
root@soumyaextetcdhost3:~# sudo docker exec d5bf13dd4621 reset-password
W0518 16:32:15.679842     449 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
New password for default admin user (user-zqtc7):
kagDkTWMsSsEZPrHRCE

```
Please clarify if this warning is ok or will be fixed.

**Comment by cjellick** [comment]
nothing we can do about this warning
