### ISSUE TITLE
Rancher 2.0 Agent fails to recognize private CA signed certificate

### ISSUE THREAD

**Issue by etlweather** [rancher/rancher#13615]
**Rancher versions:** 
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

I started Rancher v2 with the 3 bind mount for the certs as covered in the instructions [Option B—Bring Your Own Certificate: Self-Signed](https://rancher.com/docs/rancher/v2.x/en/installation/single-node-install/)

Rancher server starts fine, and https validates properly.

I then create a cluster (using custom provider - just a Ubuntu Linux OS on a VM). I copy the command to run which has a cert checksum and so forth.

The Agent however does not start. The logs shows:

 1. It complains that the https://rancher.exmplae.com/v3/settings/cacerts does not match `checksum`.
 2. Then it logs `Failed to connect to proxy - x509 certificate signed by unknown authority".

Point 1 does not make sense - why would Rancher provide a command with an incorrect checksum for the CA cert? Does not seem to be a big problem as it continues right through and I can also remove the parameter in the command that provides the checksum.

Point 2 makes sense as it's my own internal CA. How do I provide the CA cert to the Agent?

**Comment by etlweather** [comment]
Well, I actually just got over this one stop... If I add `-v cacert.pem:/etc/ssl/certs/ca-certificates.crt` to the agent, that got it past the first problem...

But now it has `Failed to connect to proxy - websocket: bad handshake`

**Comment by etlweather** [comment]
Well I have it working... despite this error. The documentation should be updated.

**Comment by superseb** [comment]
What is the content of `/3/settings/cacerts` vs the cacerts.pem mounted in the container? What is the internal CA made of, 1 root, 1/more than 1/no intermediates? I just ran the docs example again with self signed certs and validates in one run without additional mounts. If you can share your config I can try to reproduce.

**Comment by etlweather** [comment]
Both the mounted pem file and the result of the API call give the same certificate (only difference is the pem file has a `\n` at the end and not particularily shown in the JSON of the API.

`cacerts` is the root ca cert.  
`cert.pem` is the server's cert + intermediate ca cert

**Comment by etlweather** [comment]
Now that's not a self-signed certificate generated by Rancher's install - it's a certificate signed by my private CA.

**Comment by superseb** [comment]
Can you share the structure of the files (headers/footers and order) to reproduce as it does not reproduce on my set of self signed certificates.

**Comment by etlweather** [comment]
Started Rancher 2.0 with this command:

```
docker run -d -p 80:80 -p 443:443 \
   -v /etc/rancher/cert.pem:/etc/rancher/ssl/cert.pem \
   -v /etc/rancher/key.pem:/etc/rancher/ssl/key.pem \
   -v /etc/rancher/cacerts.pem:/etc/rancher/ssl/cacerts.pem \
   -v /container-data/rancher:/var/lib/rancher \
   --restart=unless-stopped \
   rancher/rancher
```
   

`cat /etc/rancher/cert.pem`: (first is Rancher's cert, then is intermediate CA).

```
-----BEGIN CERTIFICATE-----
MIIGyDCCBLCgAwIBAgICEEAwDQYJKoZIhvcNAQELBQAwgbkxCzAJBgNVBAYTAlVT
...
F49WaecBXAFY50vuXg+120Neq2a9RfwctTjpO+k7BmxIHmKwGSZPVimvYJvqQvRa
xcxEphiiSY3I+0O0
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIGUjCCBDqgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgbUxCzAJBgNVBAYTAlVT
...
NbvBgFweGJQ7Bh97dXzFYq0MNv5FvAktTD8fDcsTaZ6SU2sWxiz5toMnp7kFqryE
0Kr/g8YgjzIbXoragkczjcMldpxkajrzTKm3ZxkyBQ67LJo7pbg=
-----END CERTIFICATE-----

```

`cat /etc/rancher/cacerts.pem`: (Root CA cert)

```
-----BEGIN CERTIFICATE-----
MIIGUjCCBDqgAwIBAgIJAOEPiXeyY0upMA0GCSqGSIb3DQEBCwUAMIG1MQswCQYD
...
TrdppeAYt31Tg6kC3+fZrPSIYOiPdZFnhpUFghOdb6Y4EQ+8S6c=
-----END CERTIFICATE-----

```

----

To make the agent start up properly, I started it with this command:

```
sudo docker run -d --privileged --restart=unless-stopped --net=host \
     -v /etc/rancher/ssl:/etc/ssl/certs \
     -v /etc/kubernetes:/etc/kubernetes \
     -v /var/run:/var/run \
     rancher/rancher-agent:v2.0.0 \
        --server https://rancher2.example.org \
        --token hc4szrhnfxbs8glpmzg4p9vv6rw2ntsqrsg976brvm7wd2xbjpzwmt \
        --ca-checksum 9d7adfca7beebd24c1843cef9f1587150cf01d26e08abc9de645b89cdac65c96 \
        --etcd --controlplane --worker
```

`cat /etc/rancher/ssl/ca-certificates.crt`: (That's the only file in `/etc/rancher/ssl`)

```
-----BEGIN CERTIFICATE-----
MIIGUjCCBDqgAwIBAgIJAOEPiXeyY0upMA0GCSqGSIb3DQEBCwUAMIG1MQswCQYD
...
TrdppeAYt31Tg6kC3+fZrPSIYOiPdZFnhpUFghOdb6Y4EQ+8S6c=
-----END CERTIFICATE-----
`

The API response:

```
{"actions":{},"baseType":"setting","created":"2018-05-20T19:34:18Z","createdTS":1526844858000,"creatorId":null,"customized":true,"default":"","id":"cacerts","links":{"remove":"https://rancher2.service.flag.org/v3/settings/cacerts","self":"https://rancher2.service.flag.org/v3/settings/cacerts","update":"https://rancher2.service.flag.org/v3/settings/cacerts"},"name":"cacerts","type":"setting","uuid":"c987e216-5c64-11e8-81fd-0242ac110002","value":"-----BEGIN CERTIFICATE-----\nMIIGUjCCBDqgAwIBAgIJAOEPiXeyY0upMA0GCSqGSIb3DQEBCwUAMIG1MQswCQYD  ...   \nTrdppeAYt31Tg6kC3+fZrPSIYOiPdZFnhpUFghOdb6Y4EQ+8S6c=\n-----END CERTIFICATE-----"}

```

Now in copy/pasting all this, I noticed that on the Rancher server, the PEM files have an extra LF at the end... Maybe that's why the checksum does not work.

**Comment by etlweather** [comment]
OK, I removed the extra blank line at the end of the files, restarted Rancher. That screwed up the connection with the node, but not a problem. I recreated the node agent and it's working normally!

Amazing what an extra LF can do!

**Comment by m451** [comment]
It seems this is happening to me too.  Altought this is closed I'd think that many will run into this issue since many SSL tools add that exta LF at the end of a PEM file. This should NOT cause the issue that was described here. Thus: could we please consider this a bug? Normal behaviour should be to NOT include anything character after the `-----END CERTIFICATE-----` line for the checksum.

**Comment by leetskil** [comment]
@etlweather how did you create the cert.pem key.pem cacerts.pem ? sorry for the noobish question

**Comment by 120dev** [comment]
`docker run -d -p 80:80 -p 443:443 rancher/rancher:latest --acme-domain <DOMAINE>` :)

**Comment by sanzenwin** [comment]
> OK, I removed the extra blank line at the end of the files, restarted Rancher. That screwed up the connection with the node, but not a problem. I recreated the node agent and it's working normally!
> 
> Amazing what an extra LF can do!

Nice
