### ISSUE TITLE
`Run all pods for this workload on a specific node` resets on edit

### ISSUE THREAD

**Issue by ttftw** [rancher/rancher#13616]
rancher/server or rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent: 2.0

When I edit a workload that was explicitly scheduled to run in a specific node, the edit form resets the 'node schedule' back to auto.  I would expect if I tell the workload to run on a specific node, then when I edit the workload to do an upgrade, it still runs on that specific node.

![image](https://user-images.githubusercontent.com/22228023/40284117-a1b9802a-5c4f-11e8-815c-c942e011f54a.png)

**Comment by tfiduccia** [comment]
@ttftw - This has been fixed in the latest version.  Either v2.0.1 or v2.0.2 will have the fix in it.
