### ISSUE TITLE
Ingress in GKE/DO cluster does not point to new targets once workload is scaled up

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13611]
**Rancher versions:**
rancher/rancher: v2.0.1-rc4

Steps:

1. Create a 3 node GKE cluster in Rancher v2.0.0 
2. Create a daemonset workload and ingress pointing to the workload. The ingress points to all the pods in the workload
3. Upgrade the rancher server to v2.0.1-rc4
4. Add a node to the cluster, the daemonset workload scales up too.
5. The ingress does not point to all the new pods in the daemonset workload.

The same issue is seen for both digital ocean custom and  driver machine clusters

**Comment by sangeethah** [comment]
Related issue - https://github.com/rancher/rancher/issues/13514

**Comment by alena1108** [comment]
Can't reproduce the issue with DO cluster on 2.0.1. Scaled up daemon set multiple times; ingress gets the update. Asked qa to provide the setup whenever the issue happens again (to determine whether it's a rancher upgrade problem, or some race condition in the code)

**Comment by sangeethah** [comment]
When this issue was seen , ingress corrects itself at some point and was able to reach all the pods as expected.

**Comment by soumyalj** [comment]
Tested with v2.0.1-rc6. Still see this issue on imported rke cluster.

**Comment by sangeethah** [comment]
@alena1108 I am still able to reproduce this issue 

Steps:

Create a 3 node DO cluster in fresh install of Rancher v2.0.2
Create a deployment workload of scale 2 and ingress pointing to the workload. The ingress points to all the pods in the workload as expected.
Upgrade the rancher server to v2.0.3-rc2.
After rancher-server upgrade , ingress was still functional.

Scale up deployment to 3. This results in upgrade and all existing pods get recreated.
After this ingress is not able to route traffic to any of the pods.

Accessing ingress  results in 503 service unavailable:

```
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.13.8</center>
</body>
</html>
```

**Comment by soumyalj** [comment]
See the same issue for GKE cluster. Ingress does not point to any targets after scaling up the deployment. 
```
LAPTOP-6CQEFUBT:testwget soumya$ wget http://35.241.4.12/name.html
--2018-06-20 22:24:39--  http://35.241.4.12/name.html
Connecting to 35.241.4.12:80... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2018-06-20 22:24:39 ERROR 502: Bad Gateway.
```

**Comment by alena1108** [comment]
@soumyalj @sangeethah put an attempted fix to workaround the issue, still not sure about the underlying root cause. Please retest and see if the attempted fix worked
