### ISSUE TITLE
Error: 'waiting for cluster agent to connect'\nTrying to reach: 'https://45.77.246.5:6443/api

### ISSUE THREAD

**Issue by ystyle** [rancher/rancher#13613]
**Rancher versions:**
rancher/server or rancher/rancher:r ancher/rancher
rancher/agent or rancher/rancher-agent: rancher/rancher-agent

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancher : ubuntu 16.04
k8s master: centos 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 
disabled firewalld on rancher and k8s master node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
install rancher by quick-start-guide , add an Cluster named `developer`, add a k8s master node 
**Results:**
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Waiting for API to be available; exit status 1, W0519 05:14:23.758741 11362 factory_object_mapping.go:423] Failed to download OpenAPI (an error on the server ("Error: 'waiting for cluster agent to connect'\nTrying to reach: 'https://45.77.246.5:6443/swagger-2.0.0.pb-v1'") has prevented the request from succeeding), falling back to swagger Error from server (InternalError): an error on the server ("Error: 'waiting for cluster agent to connect'\nTrying to reach: 'https://45.77.246.5:6443/api'") has prevented the request from succeeding
```

I see a similar issues #12512 , I test a many  version of rancher on rancher node ( ubuntu 16.04) , 
cleanup env by [cleanup.sh](https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d) script,  Previously only used single node （ubuntu 16.04）, Now a single node can still work，
bug i add  a new node as k8s master ， The above error has occurred

**Comment by kevin-thorpe** [comment]
I have the exact same problem. Only differences are that I'm all on CentOS 7 in KVM, Kubernetes 1.11.0

**Comment by loganhz** [comment]
Thanks for the report.
CentOS is not officially supported by Rancher. But it should work well.

You can find the supported OS via https://rancher.com/docs/rancher/v2.x/en/installation/requirements/

Can you try it in v2.1.1, please? Please make sure it is a clean node with required port open and proper kernel version such as `Linux version 3.10.0-862.3.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Mon May 21 23:36:36 UTC 2018`

I can add a k8s cluster with CentOS 7.5 nodes successfully in v2.1.1

```
[root@ip-172-31-1-128 centos]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
[root@ip-172-31-1-128 centos]# uname -r
3.10.0-862.3.2.el7.x86_64
[root@ip-172-31-1-128 centos]#
```

What I did is following:

1. Start Rancher Server on ubuntu
2. Create a CentOS 7 instance in AWS console. You can find it in AWS marketplace. The ami is `CentOS Linux 7 x86_64 HVM EBS ENA 1805_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-77ec9308.4 (ami-8e0205f2)`
3. Open all ports
4. ssh to the node, install docker and disable selinux and disable swap
5. Add a custom cluster in Rancher UI and select all roles.
6. Run the command on the CentOS node to add it into the cluster.
7. Everything works well.

![image](https://user-images.githubusercontent.com/21168270/47265251-ad3b0f00-d557-11e8-913b-3e963dcae2f8.png)
