### ISSUE TITLE
Cattle pipeline not working on Rancher 2.0

### ISSUE THREAD

**Issue by lbtoma** [rancher/rancher#13629]
*Describe your issue here*

jenkins-config container can't download some plugins:

Some plugins failed to download! Not downloaded: kubernetes
Not downloaded: timestamper
Not downloaded: workflow-job
Not downloaded: workflow-aggregator
Not downloaded: credentials-binding
Not downloaded: git
Not downloaded: timestamper
Not downloaded: workflow-aggregator
Not downloaded: kubernetes
Not downloaded: workflow-job
Not downloaded: git
Not downloaded: credentials-binding

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`container`|

**Comment by wenjiasen** [comment]
I also encountered this problem. how can I solve it?
```
_container_name_:  jenkins-config
_image_name_:  rancher/jenkins-jenkins@sha256:5fe6e370c222fe58d04e1559df035e683e87a769420836d9772b161894802fbf
_namespace_:  cattle-pipeline
_pod_name_:  jenkins-697c88b7b6-ssw7g
_pod_uid_:  e7a0c438-7454-11e8-9c1e-00163e062b16
_source_:  stderr
_time_:  2018-06-20T07:50:07.357268892Z
content:  
Some plugins failed to download! Not downloaded: credentials-binding
Not downloaded: pipeline-stage-step
Not downloaded: matrix-project
Not downloaded: momentjs
```

**Comment by lbtoma** [comment]
It seems that you must upgrade the Rancher, the 2.0's CI is not working properly. I didn't solve this problem, I depoy the Jenkins CI by myself instead.

**Comment by gitlawr** [comment]
Starting from 2.1.0, necessary plugins are packed in the image to avoid any network issue downloading plugins and help relief of airgap installation.
