### ISSUE TITLE
Add the ability to speak to Juju controller or JaaS for provisioning CDK clusters (Ubuntu)

### ISSUE THREAD

**Issue by CalvinHartwell** [rancher/rancher#13624]
Hi all,

I'm looking to create an issue here to add the ability to Rancher to make it talk to Juju for spinning up new Kubernetes Cluster's based on Canonical's Distribution. 

**Rancher versions:** 2.X 
server 

**Infrastructure Stack versions:**
N/A

**Docker version: (`docker version`,`docker info` preferred)** N/A (latets)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04+

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** All

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** All

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** All

**Steps to Reproduce:**

Install Rancher and attempt to provision new cluster. 

**Results:**

Rancher should be able to speak to Juju to spin up new Kubernetes clusters based on Canonical's Kubernetes distribution (CDK).

**Comment by CalvinHartwell** [comment]
Please assign this task to me and I will work on it in early June.

**Comment by deniseschannon** [comment]
@CalvinHartwell I'm going to close this issue but if you are still trying to add a "cluster driver", we've added support for pluggable ones and here is an example: 

Cluster Drivers in Rancher: https://rancher.com/docs/rancher/v2.x/en/admin-settings/drivers/cluster-drivers/

Cluster Driver
https://github.com/rancher-plugins/kontainer-engine-driver-example

Custom UI
https://github.com/rancher-plugins/ui-cluster-driver-skel
