### ISSUE TITLE
[Pipeline] Repository will automatically been reset randomlly

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#13628]
When I click on the clone step, even if I didn't save the step (by clicking cancel), the step would be reset as random repo.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.1-rc5` UI: `v2.0.45` |
|Access|`local` `admin`|
|Route|`authenticated.project.pipeline.pipelines`|

**Comment by loganhz** [comment]
fixed
