### ISSUE TITLE
After the new node is added by RKE, there will be two identical ones in the rancher management UI.

### ISSUE THREAD

**Issue by SaiDoFan** [rancher/rancher#13635]
**RKE version:**
rke version v0.1.6
**Docker version: (`docker version`,`docker info` preferred)**
docker 1.13.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS7.5
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM
**cluster.yml file:**

**Steps to Reproduce:**
rke up --config 
**Results:**
![1526644055205](https://user-images.githubusercontent.com/37398738/40233292-fcf081fe-5ad4-11e8-9b88-e6cd2040180c.jpg)
After the new node is added by RKE, there will be two identical ones in the rancher management UI.

**Comment by loganhz** [comment]
@SaiDoFan I guess you have cloned your VM ?

**Comment by loganhz** [comment]
Duplicated of https://github.com/rancher/rancher/issues/14011
