### ISSUE TITLE
UI - Not able to get the cluster/project downloads when clicking on global when there are lot of clusters/projects.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13633]
**Rancher versions: v2.0.1-rc5
**Steps to Reproduce:**
Create few clusters and few projects under each of these clusters.
Once the number of projects across all clusters exceeds a certain number that can be shown in the page , clicking on "global" stops presenting any project entries.

<img width="1392" alt="screen shot 2018-05-21 at 3 55 34 pm" src="https://user-images.githubusercontent.com/4266958/40333874-9bbe6030-5d0f-11e8-880e-e49d5276fb5b.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/22
Verified fixed
