### ISSUE TITLE
[Question/Feature Request] TCP & UDP Support for Load Balancer 

### ISSUE THREAD

**Issue by BrainP4in** [rancher/rancher#13632]
Hi,
is there a plan to add Tcp or Udp to the Load Balancer for Rancher 2.X? 
Would be a nice interface to not only balance web traffic but for routing of other applications.

Thanks for your time
Maxi

**Comment by etlweather** [comment]
I'm looking for the same. Found this (but not tried yet):

https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service

**Comment by BrainP4in** [comment]
This works 😃, tried that a while ago, but it would be nice if it gets integration for Rancher.

**Comment by loganhz** [comment]
Thanks for the report and workaround !

Close in favor of https://github.com/rancher/rancher/issues/14744 and https://github.com/rancher/rancher/issues/11179
