### ISSUE TITLE
Pipeline only works manually

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#13630]
Even if I configured it with branch master and the first build trigger (when there is new commit), the pipeline is not triggered when I push commits to master. Only manually trigger has works.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.1-rc5` UI: `v2.0.45` |
|Access|`local` `admin`|
|Route|`authenticated.project.pipeline.pipeline`|

**Comment by tfiduccia** [comment]
@zhaoyao91 - I have tried this on v2.0.2 and cannot reproduce your problem.  I created a pipeline that would be triggered by a commit and it triggered.  Can you upgrade to 2.0.2 and see if you can reproduce.  If you still can't get your pipeline to work, please let me know.

**Comment by chux0519** [comment]
You can check your repo( github / gitlab ) setting, make sure the webhook is correctlly triggered(it may failed when git server can not reach your rancher server).
