### ISSUE TITLE
When a container from a service that is volume mounted to another service is deleted , it continues to be mounted on the service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1363]
Server version - V0.25.0-rc2

Steps to reproduce the problem:
Create service1 which has data volumes mounted from service2 withs scale 3.
Delete one of the instances from service2.
Container from service1 which had the deleted instance mounted , continues to have this instance mounted.

There is a new instance -test495383_test110075_test738467_1 that was created when existing instance - test495383_test110075_test738467_1 was deleted.

Expected Behavior:

Should we expect this newly created instance to be volume mounted for the test495383_test110075_1?
Or should we delete the existing test495383_test110075_1 in service 1 and create a new instance in service1 and mount the newly created instance - test495383_test110075_test738467_1 ?

```
mysql> select id,external_id,name,state from instance where name like "%test110075%";                                                                                                                           
+-----+------------------------------------------------------------------+------------------------------------+---------+
| id  | external_id                                                      | name                               | state   |
+-----+------------------------------------------------------------------+------------------------------------+---------+
| 521 | 842b80a848261aab65e8f223c93dcc26daaa438a934d2524dddcf6ab02d84bb0 | test495383_test110075_test738467_1 | purged  |
| 522 | af6d7452caf86e257f7744b7cbbd13d2af3827aaa27d835a08228e51d20de9fb | test495383_test110075_1            | running |
| 523 | 7a20c22e903ab61d280f023dc0785d02ea7e155acefafc5e5314fd13b263190f | test495383_test110075_test738467_2 | running |
| 524 | 96038f584e730b7356ec54e6379224dfb67304a581075dc7022f3db1a0604ab6 | test495383_test110075_2            | running |
| 525 | 9e6c09a09dada3a1fdba8f38fc790ba50ae2785668588e7e814d9e379c3059bb | test495383_test110075_test738467_3 | running |
| 526 | 11dd44d8c7a26dfd36ad52bd8ca035efb7d6bab0863f25bce90e8e432b39fb59 | test495383_test110075_3            | running |
| 527 | 85d4b7335c653a709203c3137471a19c10d9f988a3bbba369e718f574a3d0000 | test495383_test110075_test738467_1 | running |
+-----+------------------------------------------------------------------+------------------------------------+---------+
```

**Comment by alena1108** [comment]
>Should we expect this newly created instance to be volume mounted for the test495383_test110075_1? 

Yes, we should. The container using volume of destroyed instance, should get recreated along with the destroyed instance replacement.

**Comment by sangeethah** [comment]
Tested with server version - V0.27.0-rc3

When instances that are data volumed by other services is deleted , I see the existing deployment unit having this instance being deleted and new deployment unit being created.

mysql> select id,name,state from instance where name like "%test898298%";
+-----+-----------------------------------+---------+
| id  | name                              | state   |
+-----+-----------------------------------+---------+
| 381 | test134772_test898298_test42667_1 | purged  |
| 382 | test134772_test898298_1           | purged  |
| 383 | test134772_test898298_test42667_2 | running |
| 384 | test134772_test898298_2           | running |
| 385 | test134772_test898298_test42667_3 | running |
| 386 | test134772_test898298_3           | running |
| 387 | test134772_test898298_test42667_1 | running |
| 388 | test134772_test898298_1           | running |
+-----+-----------------------------------+---------+
8 rows in set (0.00 sec)
