### ISSUE TITLE
Users who have Project-level permissions cannot create or access Pipelines.

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#13643]
It looks like you have to have Cluster level access to view and create Pipelines but if that is the case, can a user inadvertently impact other projects since they now have access at the cluster level? 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by gitlawr** [comment]
Pipelines are in project scope so project members should be able to view and use it.

Current workaround in 2.0.0
Create a role that has just: Get, List, and Watch for the `ClusterPipelines` resource.
Edit the Cluster
Assign the user or group to JUST the new clusterpipeline role.

**Comment by gitlawr** [comment]
The pipeline setup is to configure the OAuth application. On setup, it goes the authentication workflow for current user so as to check the config is valid. For other users, they still need to do a login and authorize the App.

**Comment by bmdepesa** [comment]
@gitlawr I understand the authentication workflow is required for any user who did not configure the pipeline. In this case, there is still an issue where the user has to authenticate, then close the dialog, and re-open the add repository dialog to see the available repositories. 

The repositories should be displayed immediately upon authorization, as it is when configuring the pipeline.

**Comment by bmdepesa** [comment]
rancher/rancher:master 

Repositories are displaying correctly.
