### ISSUE TITLE
Per Project/Service permissions

### ISSUE THREAD

**Issue by sepiroth887** [rancher/rancher#1364]
I love how permissions per environment work with github integration. Would it be possible to expand this to allow more granular permissions no Project and Service level? 

Also it would be great to allow View/Start/Stop permissions without Delete being possible.

**Comment by deniseschannon** [comment]
It's a feature that will be coming up in our 1.0 GA release. You can refer to #1338. The feature will be fleshed out in the upcoming weeks.

**Comment by will-chan** [comment]
Using #1338 to track this feature as this is really a full RBAC implementation.
