### ISSUE TITLE
Rancher AD Access Control Question

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#13648]
I have added the AD integration to Rancher but anywhere where I want to add a member to a project or cluster but it only pulls down my groups. I am confused how we are going to manage users. Should I be able to search any other AD user in that dropdown and add them as a member? I also noticed that under the users page even after I logged in there isn't one generated for my AD account which I also thought could be odd but it also could make sense that since I logged in as AD and not as a local account.

**Comment by deniseschannon** [comment]
What version of Rancher are you using? 

@mitchellmaler If you are the local admin and enable/log in using your AD account, there is one user account created and linked to the 2 principals (local admin and your AD login) associated with your user. You will only see the single user account in the accounts page. 

Can you share a screenshot of how your user search and group search base? 

<img width="1230" alt="screen shot 2018-05-23 at 9 28 41 am" src="https://user-images.githubusercontent.com/11410997/40438004-bee95d28-5e6b-11e8-8533-7b48337dc237.png">

**Comment by mrajashree** [comment]
@mitchellmaler Along with the user and group search bases, can you also share if you are experiencing this with a fresh setup of 2.0.1 or upgrade?

**Comment by mitchellmaler** [comment]
Version 2.0.1 (just ugraded)

Ah that makes sense. I tested with another user and it did create an account for them. I was thinking it wasn't working since I was expecting an account for my user. 

---

The user and group search base is the basic 'dc=domain,dc=comany,dc=net' which seems to be working. It is able to find my account and it also lists my groups. 

After messing around the the member adding for a cluster or project I think I figured out the issues. Right now the dropdown only returns "Group Group". If I then try to search anything in the text box nothing ever returns even if I search a "Name" of a user or their samAccountName. However I figured out finally how to get it work, if I start the search with "user or user-" since each rancher user account key starts with that it then returns the list of users created.

This makes me think the search logic on that text field is not searching on name and id but only on ID and the dropdown is not also showing a list of users but only my loaded groups.

As a user/admin I would expect the dropdown to show first a list of users or maybe new users as well with some groups (most of the time I wont be part of the group i would add to a project/cluster so my groups isn't the best). Then if I search for any users name, user id, or ad group (not just my own) it would return those so I can link it.

**Comment by mrajashree** [comment]
@mitchellmaler Thanks. The dropdown like you said, is only supposed to list the groups that the user is a part of. You can search and add users/groups via the search text box. To understand why user search isn't working for you, can you share your User Search Field attribute?
Also while searching for AD users, were you logged in as the Default Admin (Local user) or the Active Directory admin?

**Comment by mitchellmaler** [comment]
I tested it with a logged in AD user with Administrator access. When searching in the text box it never returns anything unless I type in 'user-'.

Search Field: (&(objectClass=user)(extensionAttribute15=LDAP))

**Comment by mrajashree** [comment]
@mitchellmaler In the User Search Attribute field, only attribute names should be entered. It can't accept LDAP filters. 
In 2.0.1 while setting up AD, you'll see under `Customize Schema` that the Search Attribute for User has three fields `sAMAccountName|sn|givenName`. So when you enter anything in the text box for searching, we can query your AD server and find that user by sAMAccountName or last or first name. So to be able to search users by their sAMAccountName or first name, please edit this field and change it to `sAMAccountName` or `sAMAccountName|sn|givenName`. The only way to edit right now is via disabling re-enabling AD auth,  but the edit AD config option will be coming soon.

**Comment by mitchellmaler** [comment]
@mrajashree Thanks that fixed the issue! I guess I was a bit confused with what to put in that field but it makes more sense now.
