### ISSUE TITLE
Add a search fitler field for user and group search in AD auth provider

### ISSUE THREAD

**Issue by CalvinHartwell** [rancher/rancher#13656]
**Rancher versions:**
rancher/rancher: 2.0.0 GA/2.0.1

**Infrastructure Stack versions:** Canonical Kubernetes (k8s 1.10 and etcdv3)
kubernetes (if applicable): 1.10

**Docker version: (`docker version`,`docker info` preferred)**
```
ubuntu@unckc-prd-node1:~$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 
**Steps to Reproduce:**
Setup AD in 2.0.0, but we cannot see all the groups, only a subset of about 30 groups (there should be a couple thousand). However, the authentication is working. 

Upgrade to 2.0.1 and it appears to be working, but after disable AD and try to make a change, we are thrown an error that the DN is wrong, even though it is the same as before, IE:

```
match of:
	'(&(objectCategory=group)(|(cn=BU*)(cn=PRJ*))'
: LDAP Result Code 34 "Invalid DN Syntax": 0000208F: NameErr: DSID-031001F7, problem 2006 (BAD_NAME), data 8349, best match of:
	'(&(objectCategory=group)(|(cn=BU*)(cn=PRJ*))'
```

I cannot provide the full error as it is contains sensitive information. The customer has support subscriptions for Rancher 2.X and will be willing to work over a video share. 

**Results:**

The authentication is not working, we are given an error that the DN is wrong but the DN is actually correct. It seems that the recent changes in 2.0.1 release have broken this. 

One thing we did not try, but it seems like it may work is: 
1) Deploy Rancher 2.0 GA and configure AD, test it works. 
2) Upgrade to Rancher 2.0.1 release and leave AD configuration as before, test it works. 

Cheers,

- Calvin

**Comment by CalvinHartwell** [comment]
The exception is thrown by either the getPrincipal or getGroupPrincipals methods, I believe, still looking.

**Comment by cjellick** [comment]
@CalvinHartwell thanks for the great analysis.

The `groupSearchBase` field is only intended to work as a base DN, it is not intended to work as a filter. 

I think your first suggestion of adding an explicit filter field is a good enhancement.

**Comment by CalvinHartwell** [comment]
@cjellick yeah I figured, but it seemed to work as a filter in the last release so we were confused about what was happening after upgrade. Either way, I think a filter would be a nice addition.

**Comment by CalvinHartwell** [comment]
Thanks @cjellick @mrajashree !

**Comment by carolynhu** [comment]
We add a two customized fields `UserSearchQuery` and `GroupSearchQuery` in `Custom Schema` section.
I've tested it using customized user and group search query. Like when I config the AD auth.
I set `UserSearchQuery`=`(|(userPrincipalName=testuser13@xxx)(userPrincipalName=testuser14@xxx))` and `GroupSearchQuery`=`(|(distinguishedName=CN=testgroup1,CN=Users,xxx)(distinguishedName=CN=testgroup2,CN=Users,xxx))`

Then when you do the search in like Add Cluster, add member part, it will only display those users and groups filtered by the above query
<img width="1216" alt="screen shot 2018-08-16 at 3 30 41 pm" src="https://user-images.githubusercontent.com/29208297/44238653-7e28ab80-a16a-11e8-8fd6-d89c8dae7e1f.png">

**Comment by sangeethah** [comment]
Tested with v2.1.0-rc1.

When AD authentication is enabled , there is a "Search Filter" field option that is presented for User and Groups in "Customize Schema" section.

User has the option to set these fields when AD auth is enabled. When these filters are set , this filter gets applied to the list of users/groups that get searched when attempting to add users to site access list/add members to cluster/projects.

Note - There is no validation done on these "Search Filter" fields. If they are not a valid AD search syntax , the list of users/group presented will be empty.

Example Search Filter fields tested with:

"Group Search Filter"  - ```(|(cn=finalgroup1)(cn=finalgroup2))```
"User Search Filter" - ```
(|(memberOf=CN=finalgroup1,CN=Users,DC=testad,DC=rancher,DC=io)(memberOf=CN=finalgroup2,CN=Users,DC=testad,DC=rancher,DC=io))
```
