### ISSUE TITLE
Bridged network mode public port doesn't bind to 0.0.0.0

### ISSUE THREAD

**Issue by sepiroth887** [rancher/rancher#1365]
I noticed that when using the bridge network mode to avoid the managed network stack any port bindings  are limited to the bridge only. I.e if I have a container with IP 172.17.0.28 and -p 8080:8080 then it seems the port is bound to 172.17.0.28:8080 but not 0.0.0.0 as would be the docker default. 

Is this by design? Is there a way to ensure a port is bound to all interfaces?

**Comment by ibuildthecloud** [comment]
@sepiroth887 When you talk about listening on 172.17.0.28 how do you see this?  What indicates that it is on 172.17.0.28:8080?  While investigating this issue I believe I found a regression.  For bridge network it seems we aren't setting the ports at all.  This means that we never publish the ports.

@deniseschannon We need to add this to our next milestone.

**Comment by sepiroth887** [comment]
I did a docker inspect on the container. Just noticed that netstat doesn't actually report the IP bound to anything. Guessing this is hidden in network namespaces. IPTables doesn't show anything either.

**Comment by cjellick** [comment]
Will investigate and address as part of #53

**Comment by cjellick** [comment]
This is fixed. Steps to test:
1. Create an `nginx` container with port 8888 (or whatever) of the host mapped to port 80 of the container
2. `curl http://<host ip>:8888`

**Comment by deniseschannon** [comment]
Verified with v0.61.0-rc3 and steps provided by @cjellick.
