### ISSUE TITLE
rancher ui

### ISSUE THREAD

**Issue by leapmotor10214** [rancher/rancher#13659]
*Describe your issue here*
I want to add Add Certificate,but happen error
 the error is "Private Key is invalid. Please make sure it is a RSA key."

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/13156, fixed in v2.0.1
