### ISSUE TITLE
Create Advanced Cluster Options section

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13658]
At the moment we have 3 options that are more advanced when creating a cluster:

- etcd Heartbeat Interval
- etcd Election Timeout
- Cloud Provider

Especially cloud provider (even with the warning) confuses users, as this implies the cloud provider of the nodes while its actually the Kubernetes cloud provider. By moving these settings to Advanced Cluster Options and make it collapsed, it won't confuse users and can still be used by advanced users. Even with the warning/docs link or even renaming the option, this will always be confusing.

**Comment by westlywright** [comment]
This will be resolved by rancher/rancher#1938

**Comment by deniseschannon** [comment]
@loganhz can we move cloud provider to advanced options section?

**Comment by sangeethah** [comment]
Tested with latest build from master:

Following options are not present in "Cluster Option"
etcd Heartbeat Interval
etcd Election Timeout

Cloud Provider  option is still presernt , but if user chooses to do "Custom" , they are presented with following message - "Please edit the YAML to add in cloud provider. Read more about cloud provider."

There is an "Edit as Yaml" option , where the user has the ability to set any advanced RKE configurations.
