### ISSUE TITLE
Rancher2 deployed helm template cannot removed anymore

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#13653]
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.12.1-ce, build 7390fc6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Steps to Reproduce:**
go to templates. Deploy some templates (openebs, mongodb,..). Try to remove it.

**Results:**
Helm templates stuck in removing

<img width="716" alt="bildschirmfoto 2018-05-23 um 00 02 23" src="https://user-images.githubusercontent.com/1597621/40408080-a9a25ee2-5e66-11e8-9a00-fcf14da134a2.png">

**Comment by tfiduccia** [comment]
@exocode - I am unable to reproduce your issues in v2.0.2.  Can you please tell me:
1.  What type of cluster are your using
2.  What version of rancher do you have deployed
3.  Do the catalog apps get fully deployed before you try and delete them, or are they in some in-between state?

**Comment by exocode** [comment]
- Cluster was created with Rancher2
- Rancher 2.0.1-rc5
- They stucked in the middle of the startup process, after trying to add parameters
( ingress-nginx / `controller.nodeSelector={role=edge}` )

**Comment by exocode** [comment]
I am closing this, because with 2.0.2 it did not happen anymore...
