### ISSUE TITLE
Can't enable github auth provider

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#13665]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.1

**Steps to Reproduce:**
Simply attempt to turn on github authentication

**Results:**
Get an error message: 
GitHub is not configured

The cause is that on the the PUT to set the "allowedPrincipalsIds" field on the config, the enabled field is being sent with a value of `false`, which immediately disables github.

**Comment by deniseschannon** [comment]
Verified with master 5/23
