### ISSUE TITLE
Rancher dont delete old workers nodes on webui after kops scaling 

### ISSUE THREAD

**Issue by cyrilbkr** [rancher/rancher#13664]
Hi
Rancher 2.0.0 dont delete the old workers nodes on the webui after a kops scaling on AWS. 

$ kubectl get nodes
NAME                                       STATUS    ROLES     AGE       VERSION
ip-xxxx.eu-west-1.compute.internal   Ready     node      5h        v1.10.1
ip-xxxx.eu-west-1.compute.internal   Ready     node      5h        v1.10.1
ip-xxxx.eu-west-1.compute.internal    Ready     master    5h        v1.10.1
ip-xxxx.eu-west-1.compute.internal    Ready     node      5h        v1.10.1

![capture du 2018-05-23 17-12-37](https://user-images.githubusercontent.com/31832102/40433668-d0fa6e58-5eac-11e8-9018-3e6a291e7fd4.png)

**Comment by tfiduccia** [comment]
@cyrilbkr - This was resolved in v2.0.1

**Comment by cyrilbkr** [comment]
Thanks
