### ISSUE TITLE
Message 'Cluster must have at least one etcd plane host' is shown when provisioning is in back-off

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13660]
Version: master 5/23

Reproduce:
- Launch `rancher/rancher` container, create custom cluster
- Add 3 nodes simultaneously using `docker run`
- Dialer fail to build (sometimes 1, sometimes 2, sometimes all 3 and sometimes it works straight away)

Results:
Cluster showing `Cluster must have at least one etcd plane host` while it had 3 nodes that failed to build a dialer, and cluster provisioning is in back-off. 2 minutes later it retries and succeeds. Should be a better error/guidance on this situation.

```
2018/05/23 13:24:15 [INFO] Provisioning cluster [c-ql7k5]
2018/05/23 13:24:15 [INFO] Creating cluster [c-ql7k5]
2018/05/23 13:24:15 [INFO] cluster [c-ql7k5] provisioning: Building Kubernetes cluster
2018/05/23 13:24:15 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [174.138.4.161]
2018/05/23 13:24:15 [ERROR] cluster [c-ql7k5] provisioning: Failed to set up SSH tunneling for host [174.138.4.161]: Can't establish dialer connection: can not build dialer to c-ql7k5:m-17d116eb2661
2018/05/23 13:24:15 [ERROR] cluster [c-ql7k5] provisioning: Removing host [174.138.4.161] from node lists
2018/05/23 13:24:15 [ERROR] cluster [c-ql7k5] provisioning: Cluster must have at least one etcd plane host
2018/05/23 13:24:17 [INFO] Provisioning cluster [c-ql7k5]
2018/05/23 13:24:17 [INFO] Creating cluster [c-ql7k5]
2018/05/23 13:24:17 [ERROR] Cluster c-ql7k5 previously failed to create
2018/05/23 13:24:17 [INFO] cluster [c-ql7k5] provisioning: Building Kubernetes cluster
2018/05/23 13:24:17 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [174.138.4.161]
2018/05/23 13:24:17 [ERROR] cluster [c-ql7k5] provisioning: Failed to set up SSH tunneling for host [174.138.4.161]: Can't establish dialer connection: can not build dialer to c-ql7k5:m-17d116eb2661
2018/05/23 13:24:17 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [174.138.8.161]
2018/05/23 13:24:17 [ERROR] cluster [c-ql7k5] provisioning: Failed to set up SSH tunneling for host [174.138.8.161]: Can't establish dialer connection: can not build dialer to c-ql7k5:m-482ddc906650
2018/05/23 13:24:17 [ERROR] cluster [c-ql7k5] provisioning: Removing host [174.138.4.161] from node lists
2018/05/23 13:24:17 [ERROR] cluster [c-ql7k5] provisioning: Removing host [174.138.8.161] from node lists
2018/05/23 13:24:17 [ERROR] cluster [c-ql7k5] provisioning: Cluster must have at least one etcd plane host
2018/05/23 13:24:21 [INFO] Provisioning cluster [c-ql7k5]
2018/05/23 13:24:21 [INFO] Creating cluster [c-ql7k5]
2018/05/23 13:24:21 [ERROR] Cluster c-ql7k5 previously failed to create
2018/05/23 13:24:21 [INFO] cluster [c-ql7k5] provisioning: Building Kubernetes cluster
2018/05/23 13:24:21 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [174.138.4.161]
2018/05/23 13:24:21 [ERROR] cluster [c-ql7k5] provisioning: Failed to set up SSH tunneling for host [174.138.4.161]: Can't establish dialer connection: can not build dialer to c-ql7k5:m-17d116eb2661
2018/05/23 13:24:21 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [174.138.8.161]
2018/05/23 13:24:21 [ERROR] cluster [c-ql7k5] provisioning: Failed to set up SSH tunneling for host [174.138.8.161]: Can't establish dialer connection: can not build dialer to c-ql7k5:m-482ddc906650
2018/05/23 13:24:21 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [159.65.200.241]
2018/05/23 13:24:21 [ERROR] cluster [c-ql7k5] provisioning: Failed to set up SSH tunneling for host [159.65.200.241]: Can't establish dialer connection: can not build dialer to c-ql7k5:m-8bee21c33917
2018/05/23 13:24:21 [ERROR] cluster [c-ql7k5] provisioning: Removing host [174.138.4.161] from node lists
2018/05/23 13:24:21 [ERROR] cluster [c-ql7k5] provisioning: Removing host [174.138.8.161] from node lists
2018/05/23 13:24:21 [ERROR] cluster [c-ql7k5] provisioning: Removing host [159.65.200.241] from node lists
2018/05/23 13:24:21 [ERROR] cluster [c-ql7k5] provisioning: Cluster must have at least one etcd plane host
2018/05/23 13:24:25 [INFO] Handling backend connection request [m-17d116eb2661]
2018/05/23 13:24:27 [INFO] Handling backend connection request [m-482ddc906650]
2018/05/23 13:24:31 [INFO] Handling backend connection request [m-8bee21c33917]
2018/05/23 13:26:21 [INFO] Provisioning cluster [c-ql7k5]
2018/05/23 13:26:21 [INFO] Creating cluster [c-ql7k5]
2018/05/23 13:26:21 [ERROR] Cluster c-ql7k5 previously failed to create
2018/05/23 13:26:21 [INFO] cluster [c-ql7k5] provisioning: Building Kubernetes cluster
2018/05/23 13:26:21 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [174.138.4.161]
2018/05/23 13:26:21 [ERROR] cluster [c-ql7k5] provisioning: Unsupported Docker version found [18.03.1-ce], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x]
2018/05/23 13:26:21 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [174.138.8.161]
2018/05/23 13:26:21 [ERROR] cluster [c-ql7k5] provisioning: Unsupported Docker version found [18.03.1-ce], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x]
2018/05/23 13:26:21 [INFO] cluster [c-ql7k5] provisioning: [dialer] Setup tunnel for host [159.65.200.241]
2018/05/23 13:26:21 [ERROR] cluster [c-ql7k5] provisioning: Unsupported Docker version found [18.03.1-ce], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x]
2018/05/23 13:26:21 [INFO] cluster [c-ql7k5] provisioning: [network] Deploying port listener containers
etc...
```

**Comment by cjellick** [comment]
@nathan-jenan-rancher to validate

**Comment by nathan-jenan-rancher** [comment]
Test plan:
Steps:
1. start rancher with
```
docker run -d --restart=unless-stopped \
-p 80:80 -p 443:443 \
rancher/rancher:master
```
2. create a digital ocean droplet with ubuntu 16
3. create a custom cluster in rancher
4. select etcd, control plane, and worker checkboxes, copy docker command
5. run docker command from 4 on droplet from 2
6. monitor cluster in rancher UI, verify that the message `Cluster must have at least one etcd plane host` appears when node is added
7. repeat until error message in 6 appears

--------

Tested the above steps and confirmed error message was changed

**Comment by nathan-jenan-rancher** [comment]
Generic back off messaging will be handled in this issue:
https://github.com/rancher/rancher/issues/15584

**Comment by rshiva777** [comment]
I am trying to deploy rancher cluster in AWS Enviroment. I create the pre-requisites.

Issue: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) 
Logs: I am facing the below error logs:

2019/12/11 13:48:38 [INFO] stdout: Checking connection to Docker...
2019/12/11 13:48:38 [INFO] Checking connection to Docker...
2019/12/11 13:48:39 [INFO] stdout: Docker is up and running!
2019/12/11 13:48:39 [INFO] Docker is up and running!
2019/12/11 13:48:52 [INFO] Provisioning node awstest21 done
2019/12/11 13:48:52 [INFO] Generating and uploading node config awstest21
2019/12/11 13:48:52 [INFO] Provisioning cluster [c-bbqrd]
2019/12/11 13:48:52 [INFO] Creating cluster [c-bbqrd]
2019/12/11 13:48:57 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10580
2019/12/11 13:48:57 [INFO] cluster [c-bbqrd] provisioning: Initiating Kubernetes cluster
2019/12/11 13:48:57 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating CA kubernetes certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Service account token key
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Controller certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Scheduler certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Proxy certificates
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Node certificate
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating admin certificates and kubeconfig
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server proxy client certificates
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating etcd-172.31.30.0 certificate and key
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: Successfully Deployed state file at [management-state/rke/rke-395003924/cluster.rkestate]
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: Building Kubernetes cluster
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: [dialer] Setup tunnel for host [13.234.110.198]
2019/12/11 13:49:00 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Failed to set up SSH tunneling for host [13.234.110.118]: Can't establish dialer connection: can not build dialer to c-bbqrd:m-7kbsp
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Removing host [13.234.110.198] from node lists
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [13.234.110.198]
2019/12/11 13:49:00 [ERROR] ClusterController c-bbqrd [cluster-provisioner-controller] failed with : Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [13.234.110.118]

Can anyone please help how to solve the issue
