### ISSUE TITLE
Layer-4 Load Balancer option should only be shown if supported or user should be warned

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13661]
Version: master 5/23

When adding Layer-4 Load Balancer, if there is no cloud provider set or no controller present that can satisfy `type: LoadBalancer`, it should not be possible to create it, or there should be a warning shown.

At the moment the resource will be stuck in `Pending` state, never to be able to complete.

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/

```
When creating a service, you have the option of automatically creating 
a cloud network load balancer. This provides an externally-accessible IP
 address that sends traffic to the correct port on your cluster 
nodes provided your cluster runs in a supported environment 
and is configured with the correct cloud load balancer provider package.
```

**Comment by klinux** [comment]
Yes, this is a good thing, I lost some minutes trying to understanding why the Layer-4 was pending. I expected that Rancher 2.0 create a instance of ha-proxy like Rancher 1.6.X.

Thank you

**Comment by pasikarkkainen** [comment]
Having haproxy LB in Rancher 2.0 would be nice indeed!

**Comment by alena1108** [comment]
@superseb this issue should be covered as a part of https://github.com/rancher/rancher/issues/12422. There should be a capability L4 LB set on the cluster, based on which UI/client will know whether lb is enabled.

**Comment by alena1108** [comment]
Closing in favor of capabilities issue

**Comment by ItsReddi** [comment]
Just wondering, i created a l4 loadbalancer exposed ports 9000 9000. 
Well it stays in pending, but it is working like expected.

If i scale up/down the desired pods, the traffic is routed to them or not.
Well that should not be working?
