### ISSUE TITLE
Private registries not working on rancher/rancher:v2.0.1

### ISSUE THREAD

**Issue by jotolo** [rancher/rancher#13676]
rancher/rancher:v2.0.1
rancher/agent or rancher/rancher-agent:v2.0.1

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 39
 Running: 23
 Paused: 0
 Stopped: 16
Images: 23
Server Version: 18.06.0-ce-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.78GiB
Name: clrouter
ID: SK5B:IZPJ:DAAY:57VX:Y5NL:CWM7:O27B:IL6H:UF2R:A3XL:TRJ6:HQDD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 nexus.yzag.office
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu18.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
 internal DB

Added a new private registry. The private registry is a nexus 3 registry. When I tried to create workload the system doesn't pull the image from the registry. My credentials work with docker pull command in the server, but for some reason is not working in the workload creation.

**Comment by gkTim** [comment]
Do you have added:

`imagePullSecrets:
      - name: <your-registry-name>`

to your kubernetes yaml?

**Comment by soumyalj** [comment]
Tested with v2.0.1-rc6 using quay private registry. Creating a workload using an image from private registry works.

**Comment by jotolo** [comment]
@gkTim where can I locate this kubernetes yaml. I'm quite new using rancher. I tried with version 2.0.0 and 2.0.1 without results.

**Comment by tfiduccia** [comment]
@jotolo - I was also able to deploy a workload from a private registry.  Are you sure you included the foldername/image?

**Comment by jotolo** [comment]
@tfiduccia I create a registry named nexus in one of my nodes. My registry URL is: https://nexus.myoffice.net/repository/docker/ so, I added nexus.myoffice.net/repository/docker/ in the address and I added the username and password for this registry. After that I created a workload using both options, for example: nexus/postgres and nexus.myoffice.net/postgres and nothing. No image was pulled. Am I missing something?

**Comment by gkTim** [comment]
@jotolo Have a look at this example:
https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/configure-pod-container/private-reg-pod.yaml

**Comment by soumyalj** [comment]
@jtolo: If registry is "nexus.myoffice.net/repository/docker", and image name is "testxyz" then image name should be provided as ```nexus.myoffice.net/repository/docker/testxyz``` in the workload.
Could you give this a try?

**Comment by jotolo** [comment]
Not working. I tried with a postgres image I have in this registry. I used `nexus.fec.uh.cu/repository/docker/postgres:9.6 `as the address and nothing. This is the response from the UI.
`ReplicaSet "postgres-95cb74dff" has timed out progressing.; Deployment does not have minimum availability.`
Also I tried to set my registry as the default registry and nothing. I will redeploy all my rancher node and see if something is missing here. Please, let me know if someone notice something missing here.

**Comment by jotolo** [comment]
Hi guys, I solved the problem following this [link](https://github.com/docker/libnetwork/issues/779). The problem was a configuration in my VPN. I follow @netsuso solution in the issue. It worked like charm.
Thanks for the help.

**Comment by nico2610** [comment]
Hi guys, I have the same problem than @jotolo . I debugged with people on slack and it seems there is no kubernetes secret created when I add registry via the Rancher UI. I created one manually following the documentation https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod 

I referenced it in my pod definition : 

```
  imagePullSecrets:
    - name: myregistrykey
```

It works good as workaround but my registries are not present in the Rancher UI.

Note : it worked perfectly in Rancher 1.6 , without workaround.

**Comment by johncclayton** [comment]
I've got the same issue with private repos.  The result in my deployment is that the container / pod reports ImagePullBackOff and (obviously) doesn't progress further.

**Comment by linsomniac** [comment]
I'm in the same boat, I want to test deploying a small sample container that I'm able to run locally on my workstation, but I can't seem to get it to login to the private registry.  I set up the registry using the docker documentation for basic auth, I have a LetsEncrypt SSL cert on it via my haproxy load balancer.

I entered the credentials in the Resources->Registries page, and on my workstation I can do "docker login" to it and push the image.  When I connect via a broswer and request /v1/_catalog, I can see the repository.  But in the haproxy logs I see that it is trying to request "GET /v2/" and getting a 401 (authorization failed) status code.  Looks like it is then trying to get "/v1/_ping" and getting a 404, then finally trying to get "/v1/repositories/COMPANY/PROJECT/images" and also getting a 404.

Is configuring Rancher to use a private repo documented anywhere?  Am I supposed to be using some other mechanism to deploy my own test app to Rancher?

I'm really lost here, and I'm rather inexperienced with Docker/Kubernetes, and the logging is telling me very little.

**Comment by johncclayton** [comment]
Hi

The Rancher 2.0 system doesn't appear to sync secrets so well.  You can try
to create one in the UI, you do so by;
  - picking the namespace (left most menu, usually Default)
  - now the top most menu changes and you have the choice to enter
Resources, specify a "registry" resource and fill in the username/password

Now you'll need to use that secret in the YML file you are deploying with.
Here's a sample:

   spec:
      imagePullSecrets:
        - name: test-sec

      containers:
      - name: "whatever-name"
        image: "privaterepo/image-name:version"

Some info on secrets :
https://kubernetes-v1-4.github.io/docs/user-guide/kubectl/kubectl_create_secret_docker-registry/

A tip from me: I also had the same problem and decided to learn kubernetes
and kubectl - which helped immensely (I used the Pluralsight beginners
Kubernetes course).

Hope this helps.

John Clayton
CTO
E: johnc@filewave.com
A: St. Gallerstr 1, 9500 Wil, St Gallen
<https://maps.google.com/?q=St.%20Gallestr%201%2C%209500%20Wil%2C%20St%20Gallen>
W: https://www.filewave.com

**Comment by m1k3ga** [comment]
I had the same issue with Google Container registry (GCR).
The problem was in front of the keyboard ;)

I solved it in the following way:
"Resources" - "Registries" - "Add Registry"
Name="gcr"
Address/Custom="gcr.io"
Username="oauth2accesstoken"
Password="<CURRENT_OAUTH_TOKEN_FROM_YOUR_SERVICE_ACCOUNT>"

Then you can deploy a workload with image : gcr.io/<GCP_PROJECT_ID>/http:2.4 (from the private GCR registry).

When you show the yml file for that workload it shows:
```
      imagePullSecrets:
      - name: gcr
```

So, the GCR works with OAuth authentication

**Comment by nico2610** [comment]
@m1k3ga which version of rancher do you use exactly ?

**Comment by m1k3ga** [comment]
I'm running version 2.0.2 of rancher (as of yesterday it was "latest" ;).

**Comment by linsomniac** [comment]
I'm also running v2.0.2

**Comment by nico2610** [comment]
I retested this morning with v2.0.2 version. This is my current conclusion : 

* The workaround creating docker-registry secret and using imagePullSecrets in the pod definition works. But nothing is integrated in Rancher : secret and registry are not visible in the UI
* If I add a registry in the Rancher UI, I can use it ONLY if a deploy a Workload with the UI. If I specify my private registry "myregsitry.com:5000/myimage:tag" in the field "Docker Image", it works. The workload is created and the image correctly pulled. However, I can't find the registry created in the Rancher UI through the Kubernetes API. Does it mean that this component is only created in the Rancher config ?

To conlude, for the moment, I prefer the first solution because the integration with Kubernetes is better. The best solution will be as with Rancher 1.6 : defining repository in the Rancher UI for all namespace and using it with specify imagePullSecrets.

**Comment by deniseschannon** [comment]
@soumyalj we shoudl test that private registies using custom registries is working. 

When @kinarashah was looking into per @cloudnautique's request, it was working as expected.

**Comment by kinarashah** [comment]
@cloudnautique mentioned - on viewing YAML of a workload, its `imagePullSecrets` had secret's URL instead of `name`, would like to confirm this as well for custom registries.

**Comment by soumyalj** [comment]
Tested with master. Created a private registry in docker with credentials. Pushed an image.
The image was pulled correctly from the private registry in rancher and the pods started successfully.
The workload YAML had the registry name in `imagePullSecrets`
```
    spec:
      affinity: {}
      containers:
      - image: soumyanewtest.rancher.space:5000/testuser/mynginx
        imagePullPolicy: Always
        name: myregtest
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: myregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30



```

**Comment by phlegx** [comment]
@soumyalj @deniseschannon  In which version is/was this fixed? Mean was the fix already released? I'm currently on `v2.0.6` and there this problem still persist. There is actually no `imagePullSecrets` in my workload YAML.

**Comment by geertschuring** [comment]
I've just tested this on 2.0.8 and it works. I've added Registry Credentials and then add the workload, both through the web UI.

**Comment by cianiandreadev** [comment]
For me the update from @phlegx worked. I deleted the workload and recreated it after adding my docker repository and it worked.

**Comment by ainiml** [comment]
what if you started `registry:2` without using any password.

how do you get Rancher 2.x to use the private registry without a username and password?

**Comment by ebuildy** [comment]
Where is the logic that patch "imagePullSecrets" ?

It likes Rancher magic
