### ISSUE TITLE
After AD is configured, if user logs in as Default local user, site access control list shows blank entries for AD principals

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#13675]
This mostly will be true for other auth providers too, but users who reported this were using AD

**Comment by vincent99** [comment]
They're not blank anymore, but we can't really show the correct thing without support in the API for looking up things the current user can't see.

**Comment by sangeethah** [comment]
@mrajashree Tested with latest build from master

When logged in as local admin user for a rancher server setup that is AD auth enabled, UI now lists the AD users added to the access list , but is not able to show the login name

<img width="1314" alt="screen shot 2018-06-11 at 10 45 34 am" src="https://user-images.githubusercontent.com/4266958/41248074-aed60942-6d64-11e8-99bd-d56739f3f0e5.png">

Following errors seen in logs:
```
2018/06/11 17:40:49 [ERROR] Unknown error: user.management.cattle.io "CN=testgroup3,CN=Users,DC=tad,DC=rancher,DC=io" not found
2018/06/11 17:40:49 [ERROR] Unknown error: user.management.cattle.io "CN=Test User1,CN=Users,DC=tad,DC=rancher,DC=io" not found
```

**Comment by deniseschannon** [comment]
@sangeethah This is by design. 

@vincent99 can chime in too.

**Comment by westlywright** [comment]
I really think this should be closed. The UI works is working by design. The root of the problem is that we're logging into a new auth provider and trying to fetch principal search results from a different provider which we can't do, as of yet anyway.

**Comment by deniseschannon** [comment]
This is as expected as when you log in as a local account credentials you will not be able to have access to the external providers. If you want to see those names, rancher expects you to log in as a member of the external provider.  

This is documented here:

https://rancher.com/docs/rancher/v2.x/en/concepts/global-configuration/authentication/
