### ISSUE TITLE
Remove - icon showing up outside Site Access box

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13673]
**Rancher versions:** v2.0.2

**Steps to Reproduce:**
1.  Authenticate with github
2.  Hover hover your User

**Results:**  The remove icon is showing up outside the Site Access box
![image](https://user-images.githubusercontent.com/11514927/40446475-33074be4-5e84-11e8-8ac6-d36de9456822.png)

**Comment by adingilloRancher** [comment]
Master 6/7/1

Remove icon is in correct location.
