### ISSUE TITLE
rancher/rancher:v2.0.0 install server  [catalog] failed with : Get https://git.rancher.io/charts/index.yaml

### ISSUE THREAD

**Issue by Dayinruoxi** [rancher/rancher#13679]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/rancher:2.0.0
rancher/agent or rancher/rancher-agent:

**Docker version: (`docker version`,`docker info` preferred)**
docker version 17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
system centos7.2 1511

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 
i install rancher 2.0.0  Inability to access Web pages  
docker logs containerID  can see this 
![image](https://user-images.githubusercontent.com/25928777/40463177-3fabc98e-5f46-11e8-9bf3-263d64734bcb.png)

**Comment by loganhz** [comment]
This log has been removed. Please try v2.0.4
