### ISSUE TITLE
Local user showing up in github auth list

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13672]
**Rancher versions:** v2.0.2

**Steps to Reproduce:**
1.  Authenticate with github

**Results:**  Local user also showing up in auth list
![image](https://user-images.githubusercontent.com/11514927/40446389-e7f09746-5e83-11e8-9bd3-b46f358e6f10.png)

**Comment by loganhz** [comment]
I cannot reproduce this issue in v2.1.3. It should be fixed.

**Comment by tfiduccia** [comment]
Version - 2.2 master 2/28
Verified fixed
