### ISSUE TITLE
Rancher-NFS [v0.5.0] (rancher/storage-nfs:v0.9.1) socket file not found at /var/run/rancher/storage/rancher-nfs.sock

### ISSUE THREAD

**Issue by royerhq** [rancher/rancher#13671]
**Rancher versions:**
rancher/server: 1.6.17
rancher/agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck:  v0.3.6
ipsec: v0.2.3
network-services: v0.2.9
scheduler:v0.8.3-1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux release 7.3.1611 (Core)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS and VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA, RDS DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1) Create a Rancher Environment
2) Create an EFS host in AWS 
3) Deploy an EC2 instances into the Rancher Environment with Access to the EFS Share
4) Deploy NFS Stack with the default host pointing to the EFS host
5) Create an NFS share in a different network outside AWS. 
6) Create a Volume (VolumeX)  through the Rancher UI  that points to the new NFS share
7) Create a VM that has access to the newly create NFS share and deploy the server to the Rancher Env
8) Wait for all cattle stacks and NFS stack to start
9) Deploy a container using Volume (VolumeX) with  driver rancher-nfs 

**Results:**
Container will fail at startup because of missing nfs socket. 

**Expected Results:**
Once the NFS stack is loaded for the first time on that server the nfs socket needs to be created/initialized regardless if the default storage host is reachable or not.  Once initialized, containers should be able to mount volumes that are reachable from that server.

This has been working fine since rancher 1.6.5 and its currently working on rancher 1.6.10. Upgrading to Rancher 1.6.17 broke the expected behavior.

**Comment by edwinallenz** [comment]
I'm getting the same issue over Rancher OS.
The nfs-driver shares the volume `/var/run` with the host, but when I check the folder in the host
![image](https://user-images.githubusercontent.com/205552/40816656-51a4f3b6-650b-11e8-8a62-7e0dfb47b978.png)
but when I look for the file inside the host it just list `rancher-ebs.sock` file
![image](https://user-images.githubusercontent.com/205552/40816705-9f6dcad2-650b-11e8-925f-aa04062b22ae.png)
Rancher version is `v1.6.15`

**Comment by khcjump** [comment]
I'm getting same issue 

environment version 1 <==connection fail
server :1.6.16
rancher/agent:v1.2.10
rancher/storage-nfs:v0.9.1

environment  version 2 <==NFS connection is success
server: 1.6.14
rancher/agent:v1.2.9
rancher/storage-nfs:v0.8.5

and firewall setting same, are close firewall service test

**Comment by edwinallenz** [comment]
@khcjump my error was because I was using AWS EFS as file system and the hosts where unable to access de NSF because the security group rules wasen't set correctly. The issues was basicly with open port rules over the VPC.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by rockoo** [comment]
I'm having the same issue. v2.1 is, IMHO, completely useless. From confusing UI to weird intermittent bugs i.e. socket issues to unstable deploys. I was looking forward to using monitoring, alarms, etc. but returned back to 1.6

**Comment by mjaverto** [comment]
For me this was caused because the security group on my rancher NFS AWS EFS mount wasn't allowing traffic from the rancher EC2 instance and thus threw this error.

It was obvious after reviewing logs of container `rancher/storage-nfs`

**Comment by diegoyanezbastidas** [comment]
good in production time xD
