### ISSUE TITLE
Stuck on "Waiting to register with Kubernetes"

### ISSUE THREAD

**Issue by YangKeao** [rancher/rancher#13689]
After add a node, the state of it stuck on "Waiting to register with Kubernetes". Though it has registered if I use `docker logs` to see the `kubelet` log.
And I can also deploy a new workload. (Aha I deploy a wordpress and it works well.

I cannot see any information about the nodes and cluster because the cluster has only this node.

I have checked every port required is open and the wss works well too.

---
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by YangKeao** [comment]
Any information can be provided if needed~

**Comment by superseb** [comment]
- Are you creating a custom cluster or adding using node drivers?
- Can you share a screenshot of the Nodes view of the cluster?
- Are you adding the same node running `rancher/rancher` to a cluster?

**Comment by YangKeao** [comment]
I'm adding a custom cluster on bare metal. 
Yes, I run the cluster on the same machine which run rancher/rancher

**Comment by YangKeao** [comment]
![screenshot from 2018-05-24 20-58-24](https://user-images.githubusercontent.com/5244316/40487069-a21dbb50-5f95-11e8-9a65-df4cd56a19a3.png)

**Comment by superseb** [comment]
What is the `docker run` command you executed? What is in the output of `docker logs` of the `rancher/rancher-agent` container?

**Comment by YangKeao** [comment]
I use
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.2 --server https://172.20.1.49:32443 --token 8lnxlf6lpff26pvpmzqkp7kthrldqdp869zk267765ffjsrcmpph7g --ca-checksum bb2cc902f9f211252a25ee8b373fc8f6e9d7fc767eda6cd79c95f308f0152d11 --address 172.20.1.49 --internal-address 172.20.1.49 --etcd --controlplane --worker
```
The log of it is
```
-----BEGIN CERTIFICATE-----
MIIC7jCCAdagAwIBAgIBADANBgkqhkiG9w0BAQsFADAoMRIwEAYDVQQKEwl0aGUt
cmFuY2gxEjAQBgNVBAMTCWNhdHRsZS1jYTAeFw0xODA1MjQxMTU4MDlaFw0yODA1
MjExMTU4MDlaMCgxEjAQBgNVBAoTCXRoZS1yYW5jaDESMBAGA1UEAxMJY2F0dGxl
LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApuZ+4UI9PWvwTL7Z
Yt1QktTvAHikHFIhA6U1fDNdx6IEAR+A0ctpOPz52Af3PwF7FrYMTSknGzS+ZNM8
eaztPNWRMZIEyqpCwM7wMkjYoeSXi571UbncwKVnMc9z7Xncji+yJaQlhUmXi0aK
AQXNCY3edW1Iy5uh2l1//Rbf8xPkwLOhh/1NjRWecjOTwCAExoz09SCHwyyL72oA
Bew7pDaG9M8SkRvhSYn70R29QOAftjDxQxjYR7wmkBXs+zU8Ritz/gxGJE8idueF
M7bZADoK49JK6tVRxTCzD8YFr7h156q1jarU4PmnDDesr6hJT2rQcMfPY2RDGSZO
CiNqJwIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAN
BgkqhkiG9w0BAQsFAAOCAQEAKL0OGH1LhI+Dzkc1t/BDQZo1MKcAqP7U0T8XWV0l
5TL1S+WpuCRZ5/WULA2NkkJul+ZoUn/lwHrCxwKnyNv1rDpZTM4hvlH7zde/qtRj
VXEsLjD3MjhHWWoYxJrjy9sG4++Gh6kII2yqUy3XpLQW4ilwCDxFftstcFC6tlIf
tGrOx8iDcYSPX0gvIdm0jMWGK+djjzxFFq6w2nkC80BCTn7TBOBmpOqsyvP43aiQ
/KCUOfZkQ6dES3rgMnzH5krdGfLZgzrj4dSxLtu49tOOXZED4ZHCUnSj/zPxnk+F
ynMoaSkTmJGNFOdxe9p8QS8mNk67uJpUpBBKMda01Tn/Pw==
-----END CERTIFICATE-----
time="2018-05-24T11:59:35Z" level=info msg="Option customConfig=map[address:172.20.1.49 internalAddress:172.20.1.49 roles:[etcd worker controlplane]]"
time="2018-05-24T11:59:35Z" level=info msg="Option etcd=true"
time="2018-05-24T11:59:35Z" level=info msg="Option controlPlane=true"
time="2018-05-24T11:59:35Z" level=info msg="Option worker=true"
time="2018-05-24T11:59:35Z" level=info msg="Option requestedHostname=QSC-IDC-DB"
time="2018-05-24T11:59:35Z" level=info msg="Connecting to wss://172.20.1.49:32443/v3/connect/register with token 8lnxlf6lpff26pvpmzqkp7kthrldqdp869zk267765ffjsrcmpph7g"
time="2018-05-24T11:59:35Z" level=info msg="Connecting to proxy" url="wss://172.20.1.49:32443/v3/connect/register"
time="2018-05-24T11:59:35Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-05-24T11:59:35Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-05-24T11:59:45Z" level=info msg="Connecting to wss://172.20.1.49:32443/v3/connect/register with token 8lnxlf6lpff26pvpmzqkp7kthrldqdp869zk267765ffjsrcmpph7g"
time="2018-05-24T11:59:45Z" level=info msg="Connecting to proxy" url="wss://172.20.1.49:32443/v3/connect/register"
time="2018-05-24T11:59:45Z" level=info msg="Starting plan monitor"
time="2018-05-24T12:27:50Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"
time="2018-05-24T12:27:55Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"
time="2018-05-24T12:28:00Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"
time="2018-05-24T12:28:05Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"
time="2018-05-24T12:28:10Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"
time="2018-05-24T12:28:15Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"
```

Wow maybe `node.management.cattle.io \"m-0e802de111f5\" not found` is the key part ~~

**Comment by superseb** [comment]
Can you describe how to get into this situation from scratch? From machine setup to running `rancher/rancher` to creating cluster and adding a node and what moment what happens exactly.

**Comment by YangKeao** [comment]
I run `docker run -d --restart=unless-stopped -p 32080:80 -p 32443:443 rancher/rancher` on my server and login into the UI, set password and create a cluster.

I choose to `custom` and use canal as a network provider and press next. Then I input the ip address and get the commond. Copy the commond and paste it into the shell.

Then it works well, starting up kubernetes and a lot of containers. Finally everything seems to work well except the `Waiting to register to kubernetes` problem.

**Comment by YangKeao** [comment]
And if I run `kubectl get nodes` I can find the node.

**Comment by YangKeao** [comment]
Dive into the kubelet output I find `I0525 05:13:06.849828   24419 kubelet_node_status.go:85] Successfully registered node qsc-idc-db
`

**Comment by portfield-slash** [comment]
I encountered the same issue.
After deleting all Docker images on worker, registering with the UI solved the problem.
But I don't know the cause.The procedure I did is the same as you.

■Delete Command
sudo docker rmi -f $(sudo docker images -qa)

All Docker images are deleted.

■Rancher
【Component】　【Version】
Rancher　　　　　  v2.0.2
RancherUI                 v2.0.48

■Master &Worker
【Component】　【Version】
OS                            CentOS Linux 7
Kubelet　　　          v1.10.1
KubeProxy　　　　 v1.10.1
Docker                      v17.3.2

**Comment by YangKeao** [comment]
@portfield-slash Aha, I have tried. But it's still registering. :(

**Comment by YangKeao** [comment]
Any process on this issue?

**Comment by superseb** [comment]
I can't reproduce.

- Ubuntu 16.04 droplet with Docker 17.03.2
- docker run -d --restart=unless-stopped -p 32080:80 -p 32443:443 rancher/rancher
- Custom cluster, docker run with IP and roles specified
- Working  cluster
- Even rebooted the node, still working

So if you can supply more info on everything that is being used, we can isolate where this is going wrong. Also:

```
time="2018-05-24T11:59:45Z" level=info msg="Starting plan monitor"
time="2018-05-24T12:27:50Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"
```

There is an half hour delay in the logs, what is happening in between? If you reproduce, does it always take half an hour to show?

**Comment by psevestre** [comment]
I´m also stuck on the same problem.

Nodes:
2x Ubuntu 16.04.4 LTS
Docker: 17.03.2-ce

Rancher agent: v2.0.2
Rancher server: v2.0.2
Server logs chows the following message:

2018/06/07 20:12:46 [ERROR] cluster [c-hr9zr] provisioning: [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [172.20.0.230]. Response code: [403], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/healthz\"","reason":"Forbidden","details":{},"code":403}

**Comment by superseb** [comment]
That's a totally different error, please find the issue related to this or file a new one. 

@YangKeao Anything you can provide to reproduce?

**Comment by YangKeao** [comment]
If there is other messages I can provide, you can ask me~

**Comment by superseb** [comment]
Basically all the info requested in the issue template:

```
**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Host specification (CPU/mem)**
```

Any system logging like `dmesg`, `/var/log/syslog` or `/var/log/messages` from the moment you are adding the node.

**Comment by develar** [comment]
Yeach... Rancher2  is not yet ready for easy setup :( 

I have encounter numerous issues trying to setup but finally decided to use only supported Docker version and Ubuntu 16. Ok. First worker node and control plane (dedicated node required since for some unclear reason control plane uses 443 port) were added successfully. Now I have unclear error "Deployment does not have minimum availability" and decided to add new working nodes...

And both VM on Vultr or Scaleway stuck now with this error.

```
{"status":"Status: Downloaded newer image for rancher/hyperkube:v1.10.3-rancher2"}
time="2018-07-03T07:18:41Z" level=info msg="Starting plan monitor"
time="2018-07-03T07:18:41Z" level=error msg="Failed to connect to proxy" error="websocket: close 1006 unexpected EOF"
time="2018-07-03T07:18:51Z" level=info msg="Connecting to wss://163.172.191.100/v3/connect with token vh6c82cnqlc4zgkcxnrhfhffwdf9bt9cmx6nt5p5pf97nrschkphzh"
time="2018-07-03T07:18:51Z" level=info msg="Connecting to proxy" url="wss://163.172.191.100/v3/connect"
time="2018-07-03T07:18:52Z" level=info msg="Starting plan monitor"
```

**Docker version: (`docker version`,`docker info` preferred)**

Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-127-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.1 MiB
Name: rancher-small-worker-3
ID: YHRK:HDJR:FBSU:OSDI:67IZ:BI5B:3XQG:SK6Z:3PAA:H7N5:ICDX:PLFU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

---- Server 2 ----

Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95 GiB
Name: rancher-small-worker-2
ID: SCPG:7TW6:LZBT:4ING:VKXH:YQ5I:5XWV:CA2R:SQWP:H66H:YWXW:FIQL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-119-generic

-- Server 2 ---
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-127-generic


**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Server 1:  Scaleway VC1S (2gb ram)
Server 2: Vultr (1gb ram).


---

Rancher is awesome. Clear UI, kubernetes under the hood (the only reason why I decided to use Rancher — not UI, but numerous swam issues like "overlay doesn't work across nodes"). But it seems for now not yet provide smooth experience and not possible to setup cluster in several hours if you are not professional sysadmin :(

**Comment by superseb** [comment]
This issue is regarding ```time="2018-05-24T12:28:10Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"```, please file an issue for your problem as it is not the same.

You say you are stuck in an error, while there isn't any. Please describe all the steps (or docs) you have followed so we can reproduce. Following the docs (or quickstart https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/) it states minimum of 4GB. Next to that, the cheaper hoster tend to have kernels with the minimum of kernel modules which breaks networking components of k8s. Also following the quickstart, starting out with one node with all roles helps to begin with, also to isolate problems as I'm not following what you did with the nodes and the roles.

**Comment by develar** [comment]
Thanks for a quick response. Both nodes had last log message "Starting plan monitor".

> it states minimum of 4GB

For Rancher server I have node with 4GB, but for workers (small, only http simple router) I don't see for what 4gb can be required.

> Next to that, the cheaper hoster tend to have kernels with the minimum of kernel modules which breaks networking components of k8s

Thanks. It seems Vultr 5$ and Scaleway VC1S are not supported by Rancher. Scaleway START1-S / START1-M works (registered successfully).

> Please describe all the steps (or docs) you have followed so we can reproduce

As far I see you can simply try to add worker node on Vultr 5$ / Scaleway VC1S (ams).

(I fully understand that audience of these small servers for home/not huge company production site maybe not interested for you, but I think it will be better if not support, but at least detect such failures and inform user).

**Comment by superseb** [comment]
As described on https://rancher.com/docs/rancher/v2.x/en/tasks/clusters/creating-a-cluster/create-cluster-custom/, the recommendation for small clusters is 2 vCPU and 4GB RAM, also because the k8s components need to run and take a chunk of the system.

We have an open issue regarding incomplete kernels here: https://github.com/rancher/rancher/issues/10499

As this is far offtopic, @YangKeao if you can provide information requested in https://github.com/rancher/rancher/issues/13689#issuecomment-396901983, we can investigate further.

**Comment by vinitkumargoel** [comment]
> I can't reproduce.
> 
> * Ubuntu 16.04 droplet with Docker 17.03.2
> * docker run -d --restart=unless-stopped -p 32080:80 -p 32443:443 rancher/rancher
> * Custom cluster, docker run with IP and roles specified
> * Working  cluster
> * Even rebooted the node, still working
> 
> So if you can supply more info on everything that is being used, we can isolate where this is going wrong. Also:
> 
> ```
> time="2018-05-24T11:59:45Z" level=info msg="Starting plan monitor"
> time="2018-05-24T12:27:50Z" level=info msg="Error while getting agent config: invalid response 500: node.management.cattle.io \"m-0e802de111f5\" not found"
> ```
> There is an half hour delay in the logs, what is happening in between? If you reproduce, does it always take half an hour to show?

I am getting issue every time can we get a solution for this soon

**Comment by alfieyfc** [comment]
I'm stuck in a similar situation and believe that I've reproduced the issue.

At first, I had 2core2gb local KVM virtual machines. When running the Node Run Command provided in Rancher UI:
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.5 --server https://172.20.3.13:8443 --token zw58zqr8f8v8qsthprn7kc4dgrp6tj9hpl2jk86l8lklk8dmfqkvsv --ca-checksum 1c96c8817d767c3a34e8868e557edc1d27d8b2b3ceea1397c98757f95c34c13f --worker
```
I get the "Waiting to register with Kubernetes" message and stuck.
![image](https://user-images.githubusercontent.com/41598103/52685233-fccc9d00-2f83-11e9-9174-9137f94cde47.png)

Not sure if this helps but here's everything from the "View in API" tab:
```
{
"baseType": "node",
"clusterId": "c-w2zdl",
"conditions": [ 3 items
{
"status": "True",
"type": "Initialized"
},
{
"message": "waiting to register with Kubernetes",
"status": "Unknown",
"type": "Registered"
},
{
"status": "True",
"type": "Provisioned"
}
],
"controlPlane": false,
"created": "2019-02-11T06:03:13Z",
"createdTS": 1549864993000,
"creatorId": null,
"customConfig": {
"address": "192.168.122.133",
"type": "/v3/schemas/customConfig"
},
"dockerInfo": {
"debug": false,
"experimentalBuild": false,
"type": "/v3/schemas/dockerInfo"
},
"etcd": false,
"id": "c-w2zdl:m-5947d2c8ab82",
"imported": true,
"info": {
"cpu": {
"count": 0
},
"kubernetes": {
"kubeProxyVersion": "",
"kubeletVersion": ""
},
"memory": {
"memTotalKiB": 0
},
"os": {
"dockerVersion": "",
"kernelVersion": "",
"operatingSystem": ""
}
},
"ipAddress": "192.168.122.133",
"links": {
"remove": "…/v3/nodes/c-w2zdl:m-5947d2c8ab82",
"self": "…/v3/nodes/c-w2zdl:m-5947d2c8ab82",
"update": "…/v3/nodes/c-w2zdl:m-5947d2c8ab82"
},
"name": "",
"namespaceId": null,
"nodePoolId": "",
"nodeTemplateId": null,
"requestedHostname": "rke-test-n1",
"sshUser": "root",
"state": "registering",
"transitioning": "yes",
"transitioningMessage": "waiting to register with Kubernetes",
"type": "node",
"unschedulable": false,
"uuid": "b739a6c0-2dc2-11e9-ad2c-0242ac110002",
"worker": true
}
```

Heading to the machine `rke-test-n1`, `docker logs` for the `rancher/rancher-agent` container repeatedly shows:
```
time="2019-02-13T03:32:37Z" level=info msg="Connecting to wss://172.20.3.13:8443/v3/connect with token zw58zqr8f8v8qsthprn7kc4dgrp6tj9hpl2jk86l8lklk8dmfqkvsv"
time="2019-02-13T03:32:37Z" level=info msg="Connecting to proxy" url="wss://172.20.3.13:8443/v3/connect"
time="2019-02-13T03:33:00Z" level=info msg="Starting plan monitor"
time="2019-02-13T03:33:10Z" level=error msg="Failed to connect to proxy" error="read tcp 192.168.122.133:34638->172.20.3.13:8443: i/o timeout"
```
![image](https://user-images.githubusercontent.com/41598103/52685403-8ed4a580-2f84-11e9-98f7-29a0dc2fe1da.png)

---

Referring to @superseb's [comment](https://github.com/rancher/rancher/issues/13689#issuecomment-402111346)
> the recommendation for small clusters is 2 vCPU and 4GB RAM

I later shutdown the workers (`rke-test-n1` and `rke-test-n2`) and upgraded the specs in KVM to 2core4gb for both of them, then reboot. `docker ps` shows the containers restarted into a freshly UP status, yet the logs still remains as before.
![image](https://user-images.githubusercontent.com/41598103/52687821-8f723980-2f8e-11e9-858a-16aa56ce4a88.png)

---

Requested info from issue template (for worker nodes):
**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
> cat /etc/os-release
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
> uname -r
```
3.10.0-862.14.4.el7.x86_64
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM

**Host specification (CPU/mem)**
2 Cores, 4096MiB

---
ps. the Master VM (2 Cores, 2048MiB) works fine and `kubectl get nodes` also shows `rke-test-m1` is `Ready`
![image](https://user-images.githubusercontent.com/41598103/52688441-78811680-2f91-11e9-874f-b296fc9f5f7a.png)

**Comment by cjellick** [comment]
Can you ping 172.20.3.13 from that host? Seems like different networks?

**Comment by alfieyfc** [comment]
Yes, I can. `172.20.3.13` is the Host Desktop Machine running KVM. 

This is CLI terminal logged into `rke-test-n1` (`192.168.122.133`)
![image](https://user-images.githubusercontent.com/41598103/52689128-1249c300-2f94-11e9-9f0b-d537c4e56ab1.png)

**Comment by MikePadge** [comment]
I appear to have just run into the same problem?
I have 4 physical machines
1 - Rancher/Server
3 - Nodes in 1 cluster

Adding the first node to the cluster is fine, but adding any additional nodes to the same cluster fail. "Waiting to register with Kubernetes" 

RancherOS v1.5.0
Rancher v2.1.6
Docker 18.06.1-ce, build e68fc7a

Error From Rancher Server UI:
This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready. 
[network] Host [10.10.0.6] is not able to connect to the following ports: [10.10.0.7:2379, 10.10.0.8:2379, 10.10.0.8:2380, 10.10.0.6:2379]. Please check network policies and firewall rules

![screen shot 2019-02-21 at 1 34 38 am](https://user-images.githubusercontent.com/22322602/53151579-2f285c80-3579-11e9-9b8b-d1d0dc5175ce.png)

Is 2379 only listening on ipV6 here in RancherOS? 
I ran 
`sudo iptables -A INPUT -i eth0 -p tcp --dport 2379 --src 10.10.0.0/24 -j ACCEPT
sudo iptables-save `

But it doesn't appear to persist between reboots, so I'm thinking this could be the problem. 
Will report back.

**Comment by steve-todorov** [comment]
I also encountered this issue. In our logs we were getting:
```
time="2019-02-27T22:31:26Z" level=info msg="Connecting to wss://my-domain.com/v3/connect with token thetoken"
time="2019-02-27T22:31:26Z" level=info msg="Connecting to proxy" url="wss://my-domain.com/v3/connect"
time="2019-02-27T22:31:33Z" level=info msg="Starting plan monitor"
time="2019-02-27T22:31:43Z" level=error msg="Failed to connect to proxy" error="read tcp 1.2.3.4:42974->PUBLIC_IP:443: i/o timeout"
```

@MikePadge's comment is actually in the right direction. I temporarily added a rule in our firewall at the machine with the `PUBLIC_IP` which accepted `all` connections from `1.2.3.4` and everything worked just fine. It took me quite a while to get to the bottom of this, but after enabling firewall logs I noticed:
```
kernel: [819391.191072] IN=cloud OUT= MAC=ABCD SRC=1.2.3.4 DST=PUBLIC_IP LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=7025 DF PROTO=TCP SPT=36516 DPT=6443 WINDOW=29200 RES=0x00 SYN URGP=0
```
These logs were appearing exactly when the log complaining of not being able to connect to `443` did.
Once I've opened the port `6443` (**DPT=6443**) to be accessible from `1.2.3.0/24` things started working just fine.

**Comment by linbingdouzhe** [comment]
just wait some times.....it will be ok

**Comment by ZoroRe** [comment]
Disable selinux, firewalld. try it:
[root@centos7vm ~]# sestatus
SELinux status: enabled
于是关闭selinux(setenforce 0 在我的centos7.6上不起作用)
[root@centos7vm ~]# vim /etc/selinux/config
change  "SELINUX=enforcing" to "SELINUX=disabled"
[root@centos7vm ~]# sestatus
SELinux status: disabled
[root@centos7vm ~]# systemctl stop firewalld
[root@centos7vm ~]# systemctl disable firewalld
[root@centos7vm ~]# vim /etc/fstab
#/dev/mapper/centos-swap swap swap defaults 0 0
[root@centos7vm ~]# reboot

**Comment by JensJI** [comment]
I experienced the same issue.

At first I tried stopping and starting the docker worker container, but the error message kept appearing.

Then I deleted the whole cluster, created it again, and instead of starting the worker with the docker command and _then_ clicking the "Done" button I clicked "Done" and then started the worker with the docker command.

I don't know if it has anything to do with that, but this time it did actually work, so thought I would mention it.

**Comment by ArthurDassier** [comment]
> 
> 
> I appear to have just run into the same problem?
> I have 4 physical machines
> 1 - Rancher/Server
> 3 - Nodes in 1 cluster
> 
> Adding the first node to the cluster is fine, but adding any additional nodes to the same cluster fail. "Waiting to register with Kubernetes"
> 
> RancherOS v1.5.0
> Rancher v2.1.6
> Docker 18.06.1-ce, build e68fc7a
> 
> Error From Rancher Server UI:
> This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.
> [network] Host [10.10.0.6] is not able to connect to the following ports: [10.10.0.7:2379, 10.10.0.8:2379, 10.10.0.8:2380, 10.10.0.6:2379]. Please check network policies and firewall rules
> 
> ![screen shot 2019-02-21 at 1 34 38 am](https://user-images.githubusercontent.com/22322602/53151579-2f285c80-3579-11e9-9b8b-d1d0dc5175ce.png)
> 
> Is 2379 only listening on ipV6 here in RancherOS?
> I ran
> `sudo iptables -A INPUT -i eth0 -p tcp --dport 2379 --src 10.10.0.0/24 -j ACCEPT sudo iptables-save `
> 
> But it doesn't appear to persist between reboots, so I'm thinking this could be the problem.
> Will report back.

I managed to reproduce and solved it by stopping and disabling firewalld on host and on node.
2380 & 2379 are the ones which cause problems.

**Comment by Kuri-su** [comment]
yes..... just.... wait a moment.....

**Comment by paranoid945** [comment]
I could give you some hint, maybe your rancher server have **more than one network card** and you specified the wrong ip address from the very beginning?

**Comment by priyankak1212** [comment]
Hi, I am trying setup kubernetes cluster using custom nodes by Rancher UI. But only one node is getting registered successfully. After running docker command on worker node, that node is not getting registered and not reflected on Rancher UI kube custer.

**Comment by ArthurDassier** [comment]
> Hi, I am trying setup kubernetes cluster using custom nodes by Rancher UI. But only one node is getting registered successfully. After running docker command on worker node, that node is not getting registered and not reflected on Rancher UI kube custer.
> Can anyone help me out for this issue?
> 

Hi, are you sure that no firewall is forbidding the access to required ports ?

**Comment by priyankak1212** [comment]
> > Hi, I am trying setup kubernetes cluster using custom nodes by Rancher UI. But only one node is getting registered successfully. After running docker command on worker node, that node is not getting registered and not reflected on Rancher UI kube custer.
> > Can anyone help me out for this issue?
> 
> Hi, are you sure that no firewall is forbidding the access to required ports ?
> 
> Had the problem once but it was above my VM, on the load balancer side or on nsx I can't remember

Hi, I have kept firewall stop and disable.Still facing same issue.
