### ISSUE TITLE
Port Requirements in Docs Deleted

### ISSUE THREAD

**Issue by datosh** [rancher/rancher#13687]
Hey, 

I am currently deploying Rancher 2.0 in AWS, and need to configure some security groups so that machines can talk to each other.
The Rancher Docs container a nice table of required ports for etc/control & worker nodes.
Link: https://rancher.com/docs/rancher/v2.0/en/quick-start-guide/#port-requirements

This seems to have been deleted. Is there another source where I can find this information?
I found another [issue](https://github.com/rancher/rke/issues/212) in rancher/rke where a list of ports is presented, but this differs from the list I have copied from Rancher Docs, as well as a link to [k8s docs](https://kubernetes.io/docs/tasks/tools/install-kubeadm/#check-required-ports) with yet another port listing.

Is there a definitive list of ports that Rancher needs to deploy K8s? Please bring it back in the Rancher 2.0 docs!

**Comment by datosh** [comment]
I also found a dead link in Rancher's EC2 Cluster Setup. 
When you create a new template to specify how to spawn new nodes via EC2, there section about security groups has a link to
https://rancher.com/docs/rancher/v2.x/en/hosts/amazon/#required-ports-for-rancher-to-work
to learn more about ports. Which is a dead link.

**Comment by deniseschannon** [comment]
We've moved and updated the ports requirements to this location: https://rancher.com/docs/rancher/v2.x/en/installation/references/

We've also updated the product so that the link goes to the same place.
