### ISSUE TITLE
Clone of a workload clones the selector-labels

### ISSUE THREAD

**Issue by Crokoking** [rancher/rancher#13683]
**Rancher versions:**
rancher/server or rancher/rancher:2.0.0

**Kubernetes version**
1.10.2-gke.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE/GKE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
GKE Cluster created by Rancher

**Steps to Reproduce:**
Create a workload (tested: StatefulSet).
Clone the workload with a new name without changing anything else.

**Results:**
Checking the YAML shows that both workloads have the same workload-selector-labels. 
This means stuff like ingress via workload directs traffic to both workloads. You can already see it when cloning - there is a label cloned along. But deleting that leads to an error-message.

**Comment by loganhz** [comment]
Fixed in v2.0.4
