### ISSUE TITLE
Add etcd backup/restore to Rancher API

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#13688]
Rancher versions:
rancher/rancher: 2.02

RKE has the option to create regular etcd-backups. Like in Rancher1.x this option needs to be available via ui if creating a custom cluster.

regards,
strowi

**Comment by massimo-cannavo** [comment]
This is probably a high priority issue. So far I have given the following **workaround**:

```
root@massimo-server:~# docker container inspect etcd 
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/lib/etcd",
                "Destination": "/var/lib/rancher/etcd",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/kubernetes",
                "Destination": "/etc/kubernetes",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
            }
```
rancher-server (1st etcd node)
```
root@massimo-server:~# docker container ls | grep etcd
b1104ede768f        rancher/coreos-etcd:v3.2.18                                                                                               "/usr/local/bin/et..."   2 minutes ago       Up 2 minutes                                                   etcd 

root@massimo-server:~# docker container exec --interactive --tty etcd sh 
/ # mkdir -p /etc/kubernetes/snapshots 

/ # etcdctl snapshot save /etc/kubernetes/snapshots/massimo-server-etcd-snapshot-2018-08-27-16-20-27
Snapshot saved at /etc/kubernetes/snapshots/massimo-server-etcd-snapshot-2018-08-27-16-20-27 

/ # etcdctl --write-out=table snapshot status /etc/kubernetes/snapshots/massimo-server-etcd-snapshot-2018-08-27-16-20-27
+----------+----------+------------+------------+
|   HASH   | REVISION | TOTAL KEYS | TOTAL SIZE |
+----------+----------+------------+------------+
| f5a2b2bf |     2821 |       1562 |     4.7 MB |
+----------+----------+------------+------------+

/ # exit
root@massimo-server:~# cd /etc/kubernetes/snapshots/ 

root@massimo-server:/etc/kubernetes/snapshots# ls -l
total 4552
-rw-r--r-- 1 root root 4657184 Aug 27 16:21 massimo-server-etcd-snapshot-2018-08-27-16-20-27
```

**It would be nice to not have to use the workaround mentioned above but instead add the option in the UI.**

**Comment by martcastaldo** [comment]
@massimo-cannavo I take it that you need to install etcdctl onto one of the master nodes to get this to work?

**Comment by massimo-cannavo** [comment]
@martcastaldo no you should not need to install anything. Inside of the **etcd** container the etcdctl binary should be available.

**Comment by alena1108** [comment]
Also when designing restore api, think about restoring from external link as an option

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rke/issues/705 and https://github.com/rancher/rancher/issues/16123#issuecomment-430469984

In term of backup and restore, if there is an option to change server-url in restore time that would be great

**Comment by panho66** [comment]
Agree with @loganhz.  On premise infrastructure which may not able automate everything. Sometime applications  have  dependency to firewall  rules which not be changed easily. For worker node, it may have NAT IP in firewall VPN between two parties. So the idea case is backup, change server-url  and restore only master then upgrade new master with different version. If everything is ok, move 1 worker node at a time to new master  or back to old master.  (Cleanup worker before moving between new and old master is a manual step and not well documented :(  )

**Comment by matthax** [comment]
@massimo-cannavo How were you able to restore from this snapshot?
I have a similar process but the recovery fails, provided some more info in #16574

**Comment by firasalkafri** [comment]
Take a look at this: https://github.com/Salalem/rancher-s3-backup

**Comment by appacea** [comment]
Hi. I have a cluster in which the etcd+control plane server changed ip and I need to create a new server and then restore the etcd.

I managed to backup the etcd using the method described by @massimo-cannavo but now I'm not sure how to restore that file.

Has anyone successfully restored an etcd backup within the rancher/coreos-etcd:v3.1.12 container?

**Comment by moelsayed** [comment]
@sangeethah @westlywright All the API components are in master now. UI is up.
