### ISSUE TITLE
catalog page support displaying endpoint point properly

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#13694]
Rancher version 2.0 master 05/24

Steps to Reproduce:

1. Go to Catalog Apps and deploy the Prometheus chart (or app with multiple endpoints)

![image](https://user-images.githubusercontent.com/4569037/40495926-144f143e-5fab-11e8-8806-95e7ea929879.png)
the way to display endpoints are not user-friendly and service name is missing, 
so service and ingress for the same app components should go to the same block with it service name, for example like:
```
Grafana: 31745/tcp, 80/http        |    Prometheus: 30732/tcp, 80/http
serviceGraph: 31745/tcp, 80/http   |     Zipkin: 30732/tcp, 80/http
```

**Comment by loganhz** [comment]
@vincent99 do you agree this design? I have fixed the style issue with `ellipsis`. I think user can go to the app detail page to see the all endpoints.

**Comment by vincent99** [comment]
Yes I think showing a limited set of ports on the app with ellipsis is good, you can't show an unlimited number of endpoints and have a decently lined up display of multiple applications.

**Comment by guangbochen** [comment]
using ellipsis is good, but @vincent99 @loganhz here are two main concerns, 
1. we got to know which server the port belongs to when have multiple service in one chart, e.g, a Prometheus chart may contains Grafana, Prometheus and Alertmannager.
2. should we use a label to specify whether an endpoint should appears on the catalog landing page, e.g, `catalog-endpoint: true`

**Comment by loganhz** [comment]
There are too many endpoints for some app. We need to add a particular field in `publicEndpoint` to let UI know if we should show the port in app list page.

**Comment by adingilloRancher** [comment]
Master 6/18/18

Validated endpoints added within app
