### ISSUE TITLE
Rancher 2 is unable to create Gluster PersistentVolume

### ISSUE THREAD

**Issue by linkvt** [rancher/rancher#13690]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Steps to Reproduce:**
1. Create a new PersistentVolume
2. Select the "Gluster Volume" as Volume Plugin
![grafik](https://user-images.githubusercontent.com/3075401/40487750-6889510e-5f65-11e8-837c-a194677fd5b3.png)

**Results:**
The UI says you should enter an IP, but in reality it expects a Kubernetes `Endpoints` name.

The kubelet log prints the following error when using an address directly:
![grafik](https://user-images.githubusercontent.com/3075401/40487911-cf843766-5f65-11e8-9f12-fe23f46c2cdf.png)

The corresponding code of glusterfs can be found here: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/glusterfs.go#L154-L158

**Workaround:**
I got it working by creating a `Endpoints` pointing to my three GlusterFS servers (specify port 1, it is ignored anyways) in the matching namespace and using the name of this `Endpoints` in the input field.

**Comment by tfiduccia** [comment]
@logan - is this just a problem with the example text or do we need to change the "type" of the field as well?

**Comment by linkvt** [comment]
Of course I'm not the expert, but I think it is not only a UI bug, because:
- the `Endpoints` has to be created somewhere in Kubernetes, because the GlusterFS library needs them
- I can't create the `Endpoints` anywhere else in the UI, so I can't just reference them in that field
- the `PersistentVolume` is bound to a cluster, but AFAIK the `Endpoints` need to be assigned to the namespace in which I create my `PersistentVolumeClaim` - so that can't happen at `PersistentVolume` creation but at the `PVC` creation (unsure about that)

Please correct me if I'm wrong as I'm also just learning the concepts.

**Comment by loganhz** [comment]
Updated the placeholder.  I guess it is what we can do from UI side now.

**Comment by tfiduccia** [comment]
Version - 2.0 master 6/4
Verified fixed - UI now allow texts and it's being passed to the API and API response has it as well.
