### ISSUE TITLE
Please add custom path for yaml for Helm

### ISSUE THREAD

**Issue by patsevanton** [rancher/rancher#13695]
**Rancher versions:**
rancher/rancher: 2.0.2
rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux release 7.4.1708 (Core) 
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
https://xx.xx.xx.xx/g/catalog
Add Catalog
URL https://github.com/microservices-demo/microservices-demo.git
Install helm-chart for Sock Shop
**Results:**
Can`t install helm-chart for Sock Shop

```
2018/05/24 16:04:49 [ERROR] Unknown error: resource name may not be empty
2018/05/24 16:05:24 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-gjnlg to namespace=helm-chart-7cpfv7
E0524 16:05:24.404542       1 generic_controller.go:204] AppController project-gjnlg/helm-chart-7cpfv7 [helm-controller] failed with : helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: nginx-ingress
: exit status 1
E0524 16:05:24.565321       1 generic_controller.go:204] AppController project-gjnlg/helm-chart-7cpfv7 [helm-controller] failed with : helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: nginx-ingress
: exit status 1
E0524 16:05:24.894619       1 generic_controller.go:204] AppController project-gjnlg/helm-chart-7cpfv7 [helm-controller] failed with : helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: nginx-ingress
: exit status 1

```

**Comment by tfiduccia** [comment]
@StrongMonkey - Is this something we should fix or just a problem in his requirements.yaml?

**Comment by patsevanton** [comment]
If you have time you should fix.
Thank you

**Comment by patsevanton** [comment]
I try to install helm from
https://github.com/daemonza/testapi


And get error:

```
E0525 08:03:06.618106       1 generic_controller.go:204] AppController project-gjnlg/testapi-chart [helm-controller] failed with : failed to remove finalizer on project-gjnlg:testapi-chart
2018/05/25 08:03:12 [ERROR] Unknown error: resource name may not be empty
2018/05/25 08:03:13 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-gjnlg to namespace=testapi-chart-ng12sl
service "testapi-chart-ng12sl-tes" created
deployment "testapi-chart-ng12sl-tes" created
service "testapi-chart-ng12sl-tes" labeled
deployment "testapi-chart-ng12sl-tes" labeled
service "testapi-chart-ng12sl-tes" unchanged
deployment "testapi-chart-ng12sl-tes" unchanged
service "testapi-chart-ng12sl-tes" not labeled
deployment "testapi-chart-ng12sl-tes" not labeled
```

**Comment by StrongMonkey** [comment]
Hi @patsevanton, Looks like you are missing the dependency chart in your catalog. https://docs.helm.sh/developing_charts/#the-chart-file-structure Here is the structure of a helm chart.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
