### ISSUE TITLE
After upgrading Rancher from 2.0.0 to 2.0.2 many Projects lost the link to the Namespace.

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#13699]
After upgrading Rancher from 2.0.0 to 2.0.2 many Projects lost the link to the Namespace.
The namespace is still there, including the workloads, but the Project comes up empty.
Can't manually link the Namespace to the Project, since the ns don't show up in Rancher GUI (should show under 'Not in a Project'), but only show up in kubectl

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by tfiduccia** [comment]
@dxxxxxg - Quick questions - 
1.  Was v2.0.0 a fresh install?  Or was it upgraded from a previous alpha release?
2.  What type of cluster did you create and how many?
3.  How many projects/namespaces would you say you had?

**Comment by dxxxxxg** [comment]
It was an upgrade from 2.0GA to 2.0.2.
RKE clusters were created.
28 projects and each has 1 namespace

from the customer:
"Maybe the issue has something to do with some kind of cache?
When the issue was happening there where even some extra malformed project names, eg ""te"", ""chd"", ""autolm""
And there were no workloads in the projects with 'missing' namespaces.

After fully clearing all cookies and cache on the browser everything is looking good.
All namespaces and workloads are showing up fine.

Sorry for the quick report. Will keep an eye on this and update if anythign similar happens again."

**Comment by cjellick** [comment]
This one had me really worried! Glad to hear it was only a UI caching issue. Thanks for the report and the follow up/

**Comment by vincent99** [comment]
That doesn't really add up, the UI doesn't make up namespaces and hide others...

**Comment by dawidmalina** [comment]
I had similar issue during testing rancher v.2.0.2 with my custom kubernetes cluster. I've added project and assigned some newly created test namespaces to this project and after few seconds ui showed me project with empty namespaces (but of course namespaces were there on the k8s cluster). What is even more funny that when i was trying add same namespaces to project again i was notified that namesapces already exist.

**Comment by tfiduccia** [comment]
@dawidmalina - did they show up after a refresh of your browser?

**Comment by dawidmalina** [comment]
No, they not. But I will double check this.

**Comment by dawidmalina** [comment]
I'm not able to reproduce this issue anymore but in the meantime my cluster was upgraded to kubernetes 1.10 (maybe this fixed the problem somehow).

**Comment by superseb** [comment]
Let us know if we need to investigate.
