### ISSUE TITLE
support && logic for show_if conditions in catalog questions 

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#13693]
Rancher version 2.0 master 05/24

Steps to Reproduce:
1. Go to Catalog Apps and Grafana chart

Results: conditional questions is not showing as expected

![image](https://user-images.githubusercontent.com/4569037/40495449-d3251374-5fa9-11e8-8541-36d7fca93506.png)
Variable `NodePort Number` should be hidden when the ingress is enabled, but it is showing because the `service.type` is equal to NodePort, should add && logic for this
![image](https://user-images.githubusercontent.com/4569037/40495267-6bca93fc-5fa9-11e8-8e9a-6824d812a360.png)

Also, we need to support  && logic in show_if: "ingress.enabled=false&&abc.enabled=true"

**Comment by vincent99** [comment]
You're just going to end up with a Turing-complete programming language for conditionals here, one step at a time.  Next step is going to be `||`, and then you need grouping parenthesis to mix and and or, then casting, etc.

**Comment by vincent99** [comment]
Note that the support added is only for exactly `&&`s, so you can do `a == 1 && b == 2 && c == 3` but no `||`, grouping, etc (yet)

**Comment by tfiduccia** [comment]
Version - 2.0 master 6/4
Verified fixed.

**Comment by mostafahussein** [comment]
@vincent99 Do you know the ETA for adding the support of OR condition `||` ?

**Comment by codejamninja** [comment]
`!=` would also be useful
