### ISSUE TITLE
Changing server-url requires hard refresh on nodeCommand

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13708]
Version: master 5/25

Reproduce:
- Launch `rancher/rancher`, set up server-url to be value X (some IP)
- Create custom cluster, see the `docker run` command being created/shown
- Change `server-url` via Settings
- Go to `Edit Cluster` and see the old value in the `docker run` command

If you hard refresh the page, the command is regenerated.

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/18

The run command is being updated without requiring a hard refresh.
