### ISSUE TITLE
Ability to configure catalog sources on start

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13700]
Ability to disable catalog sources and configure catalog sources on start for airgapped setups, the logs will show unnecessary logging while it can be known it will not be able to reach outside.

For configuring catalogs it also helps if you can do it on start, instead of another API call to add a new one.

- Disable on start
- Configurable on start

**Comment by loganhz** [comment]
Linked to https://github.com/rancher/rancher/issues/15486

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/13700
