### ISSUE TITLE
Enable project only user access to pipelines if setup by a cluster level user

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13705]
**Rancher versions:** v2.0.2

**Steps to Reproduce:**
1.  As admin enable Pipeline on cluster level
2. Add a user that only has access to the default project
3.  Log in as user and go to pipelines page to add pipeline

**Results:**  Can't add pipelines

**Comment by deniseschannon** [comment]
Duplicate https://github.com/rancher/rancher/issues/13643
