### ISSUE TITLE
User might wrongly delete the system level namespaces in the UI

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13710]
rancher/rancher:v2.0.2

In namespaces page, user might wrongly delete the system level namespaces in the UI such as kube-system, cattle-system and nginx-ingress. Is there anything we can do?

**Comment by westlywright** [comment]
We already warn the user when they are about to delete something, Is there a reason that the confirmation modal does not alleviate this issue?

**Comment by loganhz** [comment]
@seanly Please reopen it if you think the popup warning can not fix it.
