### ISSUE TITLE
Specify the nodes for nginx ingress

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13711]
rancher/rancher:v2.0.2

Some users just want to expose their services to internet on some particular nodes.
Now ingress controllers are running on all nodes. 
How can I specify the nodes for nginx ingress ?

**Comment by alena1108** [comment]
Currently nginx ingress controller deployment configuration are not supported. RKE deploys it on every node as a daemon set - we've just picked the most popular deployment model. @galal-hussein @moelsayed please confirm. We might enable configuration change in the future, so lets keep this ticket open.

**Comment by pulberg** [comment]
I'll add my request for this also, I've needed this in 1.x for over 2yrs, and will need this in v2.  I am blocked from running Rancher in Production (and from purchasing a support contract) until I can set affinity for LB/Ingress to only run on specific "worker/compute" nodes.

**Comment by moelsayed** [comment]
@alena1108 We deploy on all nodes by default, but we also allow using node selector configuration to run it on specific nodes: https://github.com/rancher/rke/blob/master/cluster.yml#L172-L190

We just need to enable this configuration from rancher side. 

@pulberg for now, you can deploy your cluster with the above configuration example using RKE and import it in Rancher 2.0. It should work with no problems and you will be able to specify nodes to run ingress using node labels.

**Comment by alexandrem** [comment]
Labels alone are not enough. You usually want to add taints and explicit tolerations on the ingress controller daemonsets to only have the ingress workloads running on those dedicated LB nodes and not mix with other container apps.

Right now, RKE doesn't support adding taints neither, so you have to do it post-provisioning, but it's not perfect neither because of Scheduling/Executing pods eviction rules.

**Comment by Leen15** [comment]
This is a very big issue compared to rancher1.
We are using rancher 1 with 20 servers and we have different load balancers (one for every host) so we can configure what nodes are exposed and what services are available for every host. It's a big problem for us (and a security issue too) that we cant select where a specific workload should be exposed.

**Comment by loganhz** [comment]
Now you can set node_selector in cluster options via YAML  https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/ingress-controllers/

The issue for supporting taints in RKE and UI will be tracked in https://github.com/rancher/rancher/issues/13972
