### ISSUE TITLE
More information in pod detail page

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13714]
rancher/rancher:v2.0.0

If the pod doesn't work well, user will need to use `kubectl describe pod` to check it out.
In pod detail page, the information is very limited if I want to find out why my pods can not be started.
Can we show the `kubectl describe pod` results in UI?

**Comment by Itiho** [comment]
![captura de tela de 2018-05-28 07-40-11](https://user-images.githubusercontent.com/7440821/40612916-696e8e4e-624a-11e8-9e43-3da424d4e65e.png)

The context menu is the best local for this. I understand that this function would be interesting for all kinde (deployment, pod, container, ingress, pvc, storageclass, service, cluster, nodes...).

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/41188367-aa9e7ffc-6bee-11e8-9b8f-b92fed30d8dc.png)

Added events list in pod detail page and workload detail page.

We will think about how to improve it for other resources.

**Comment by loganhz** [comment]
Events section has been added it pod detail page
