### ISSUE TITLE
Cannot enable/disable helm charts due to existing helm chart in custom

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#13724]
**Rancher versions:**
Rancher 2.0.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@rancher2-ubuntu-2gb

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hetzner

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
- Deploy Rancher `sudo docker run -d --name rancher2 --restart=unless-stopped -v /rancher/rancherdata:/var/lib/rancher -p 80:80 -p 443:443 rancher/rancher:v2.0.2 --acme-domain rancher.your-domain.com`
- Go to Global
- Go to Catalogs
- Try to enable / disable Helm Stable

**Results:**

![2018-05-25 11 53 59](https://user-images.githubusercontent.com/1597621/40538559-5d65315a-6012-11e8-97c2-e3cedb020d1b.gif)

**Comment by deniseschannon** [comment]
Can you try deleting the custom catalog (labeled) `helm` and then try it again?

As release noted, the helm catalog from v2.0.0 was originally pointing to an internal one and in v2.0.1, we changed it to point to the k8s repo. So upon upgrades, there is a custom catalog labeled `helm` that is the same name as stable.

**Comment by deniseschannon** [comment]
Regardless, even if there is a catalog called `helm` we should be able to still work. @loganhz can oyu take a look?

**Comment by westlywright** [comment]
@deniseschannon  I believe this is an API issue. The API sends back a 409 Conflict (correct) when you add the custom catalog in the video and then try to enable the helm stable catalog. This is due to the duplicate id's for the helm and custom added helm from the video. Helm Incubator works in this case without issue because the id's do not match. Tested on master.

**Comment by exocode** [comment]
yes, after deleting the entry it worked. Thank you!

**Comment by deniseschannon** [comment]
@loganhz we need to fix that you can't enable/disable when you have another entry that would use the same name/ID. 

But it sounds like a backend issue.

**Comment by StrongMonkey** [comment]
@deniseschannon does that mean that we should allow duplicate catalog names in the global level?

**Comment by deniseschannon** [comment]
i don't think we should allow duplicate names. @StrongMonkey can you work with @loganhz to figure it out? basically, if you have a catalog named `library` and whatever the name is used for the easy enable links (i dunno what they are) in the custom list, then it seems you can't enable/disable these options.

<img width="1281" alt="screen shot 2018-06-14 at 4 41 18 pm" src="https://user-images.githubusercontent.com/11410997/41443448-cd955f2e-6ff1-11e8-8275-d597b98a244e.png">

**Comment by vincent99** [comment]
I don't understand what you want it to do; the name is unique, that name is taken, so you can't enable it.  Disabling the button entirely is just going to give you no information why you can't click it.  Showing a tooltip on it is basically exactly the same as the error that's already displayed.  And all of this is only a concern for 99% of people because we had to make a one-time change to the URL that was shipped wrong in 2.0.0.

**Comment by deniseschannon** [comment]
Okay, I re-looked at the UI. 

Is there a way to make an error message for the UI that would be displayed to indicate that it's cause of the custom catalog with the same name? Like under where the enable/disable buttons are for those catalogs?

It would be for `library`, `helm` and `helm-incubator`

**Comment by deniseschannon** [comment]
It obviously wasn't clear originally that they couldn't disable/enable cause there was a custom catalog already with the same name.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
