### ISSUE TITLE
Cluster doesn't create

### ISSUE THREAD

**Issue by smollsmit** [rancher/rancher#13726]
**Rancher versions:**
rancher/rancher:2.0.2

**Docker version: 17.12

**Operating system and kernel: ubuntu 16.04

**Type/provider of hosts: vSphere

**Environment Template: Kubernetes

**Steps to Reproduce:**
1. Add cluster -> vSphere -> Create vSphere template -> Create: 
  - State of cluster creation's step is Provisioning
  - Virtual machine create successfully but IP address doesn't bind
  - in properties of VMs I see warning like this: This type of network adapter is not supported by {0}Other Linux (64-bit)

Environment: 
 - vCenter 6.5
  - image - boot2docker 17.03/18.04

**Results:**
Cluster doesn't create

**Comment by janeczku** [comment]
@smollsmit The vSphere node driver now default using RancherOS for VMs. Could you check with the latest Rancher 2.x release if you are still seeing the issue?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
