### ISSUE TITLE
An error occurred when saving with 'Import Pipeline From Repository' from Pipeline.

### ISSUE THREAD

**Issue by jungju** [rancher/rancher#13722]
rancher/rancher:v2.0.2

An error occurred when saving with 'Import Pipeline From Repository'
(Note that the syntax of the contents of the yaml file is incorrect.)

![image](https://user-images.githubusercontent.com/809189/40528051-5e7e775a-602a-11e8-9678-cf19238cb698.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/11

The error is handled gracefully and a message is displayed explaining that the yaml in the file is incorrect.
