### ISSUE TITLE
Port conflicts are not considered when global flags are set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1372]
Server version - V0.25.0-rc2

Steps to reproduce the problem:
Have 2 hosts with label say "name1=value1"
Add a global service with no scheduling which has port mapping , in my case 8080->80.
Start service.
1container gets deployed in each of the host.

Add another global service with no scheduling which has port mapping , in my case 8080->80.
Start service.
1 container gets deployed in each of the host even though port 8080 on the host is already being used by other containers.

Add another global service with scheduling set to "host must have label name1=value1" which has port mapping , in my case 8080->80.
Start service.
1 container gets deployed in each of the host even though port 8080 on the host is already being used by other containers.

Should we expect containers to not be deployed for global services when there is a port conflict?

 
```
-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 8080 -j DNAT --to-destination 10.42.207.207:80
-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 8080 -j DNAT --to-destination 10.42.106.150:80
-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 8080 -j DNAT --to-destination 10.42.161.106:80
```

**Comment by sangeethah** [comment]
This same issue is seen with LB services.
We are allowed to activate multiple LB services with same source port with global scheduling.

This results in multiple LB agent with the same ports being configured on the same host.
Only one LB service is functional.

We should be able to prevent launching LB Agents on hosts where there is a port conflict.

**Comment by kaos** [comment]
+1
This bit me the other day.. Not too hard, but still ;)
