### ISSUE TITLE
Helm chart parsing values not correctly

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#13723]
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.12.1-ce, build 7390fc6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hetzner

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node Rancher

**Steps to Reproduce:**
go to templates. Deploy ingress-nginx. Try to add a controller.nodeSelector
Result should be "role=edge"
My approaches:

- "role"="edge"
- "role":"edge"
- role=edge
- {"role"="edge"}
- ["role"="edge"]
- ["role":"edge"]

**Results:**
ERROR:

```
Kubectl apply failed. Error: Error from server (Invalid): 
error when applying patch: {"spec":{"clusterIP":""}} to: &{0xc4214c43c0 0xc420439570 nginx-ingress-ftssa nginx-ingress-ftssa-controller /tmp/app-template929640075 0xc421214cd8 0xc421214d40 843963 false} for: "/tmp/app-template929640075": 
Service "nginx-ingress-ftssa-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable Error from server (Invalid): 
error when applying patch: {"spec":{"clusterIP":""}} to: &{0xc4214c4600 0xc420172f50 nginx-ingress-ftssa nginx-ingress-ftssa-default-backend /tmp/app-template929640075 0xc421214df0 0xc421214e48 843966 false} for: "/tmp/app-template929640075": Service "nginx-ingress-ftssa-default-backend" is invalid: spec.clusterIP: Invalid value: "": 
field is immutable error validating "/tmp/app-template929640075": 
error validating data: 
ValidationError(DaemonSet.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "string", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false : exit status 1
```

__ValidationError(DaemonSet.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "string", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false : exit status 1__

**Comment by seanly** [comment]
controller.nodeSelector.role=edge

**Comment by seanly** [comment]
Master.NodeSelector.jenkins\.io/env=test, when labes is jenkins.io/env=test
don't use Master.NodeSelector."jenkins\.io/env"=test
**Rancher does not use helm, only helm syntax**

**Comment by exocode** [comment]
Thank you very much, that worked!
