### ISSUE TITLE
View in API "Show Request" error - SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#13732]
**Rancher versions:**
v2.0.2

**Docker version: (`docker version`,`docker info` preferred)**
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node Rancher

**Steps to Reproduce:**
Go into any cluster and project, select "workloads", on the right of any workload select the ellipsis and click on "view in api".    

Once the api info has come up, select the "edit" button in the top right, in the edit window select the "show request" button.

**Results:**
SyntaxError: Unexpected end of JSON input

**Comment by vincent99** [comment]
`1.1.5` is published, APIs will need to point to/package it..

**Comment by loganhz** [comment]
PR for norman https://github.com/rancher/norman/pull/177/

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/26
Verified fixed
