### ISSUE TITLE
"Server aborted the SSL handshake" error when accessing ingress rules with no request host .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13735]
Rancher server version - Build from master.

Steps to reproduce the problem:
Deploy workload1.
Create a ingress with rule having no host but only path for workload1.

When accessing ingress ip without passing any host header it directs traffic to pods of workload1 as expected.
But when I access ingress ip by passing any host header , i get "Server aborted the SSL handshake" error.

```
$ curl -L --insecure http://<ip>/service2.html
default-19090-b6998697b-9w88z
$ curl -L --insecure  --header 'Host: hello.com' http://<ip>/service2.html
curl: (35) Server aborted the SSL handshake
$ 
```

**Comment by orangedeng** [comment]
we don't except or use `Host` header when an host name is not set in an ingress rule.
I think the appropriate case should be accessing `https://<ip>/service2.html`. 

When an ingress rule is set without host name, ingress-controller will configure nginx to upgrade all http request to `https://$host$URI` with 308 redirect code. So when you add `hello.com` to the `Host` header to the request, it will redirect you to `https://hello.com/service2.html`. I think that is why `Server aborted the SSL handshake` comes up.

**Comment by sangeethah** [comment]
@orangedeng , Ingress gets created with "*" for host , which would mean allow for any host header (including no header) ?

```
$ kubectl get ingress  -n test1
NAME      HOSTS     ADDRESS            PORTS     AGE
testme    *         18.218.177.25...   80        11m
```

When we try to create ingress (without host) , I am able to access the ingress with any host header.

```
spec:
 rules:
 -  http:
     paths:
     - path: /name.html
       backend:
         serviceName: k8test249
         servicePort: 80
```

**Comment by sangeethah** [comment]
@orangedeng When ipaddress resolves to the hostname , we are able to access the Ingress url as expected.
