### ISSUE TITLE
Error creating machine: Error in driver during machine creation: not supported (vCenter only)

### ISSUE THREAD

**Issue by landloos** [rancher/rancher#13738]
Pretty new to Rancher but I cant get it to create a new node (creating new cluster) using Vsphere 6.7. It creates the VM and then fails with a " NodeController c-htmck/m-x9twd [node-controller] failed with : Error creating machine: Error in driver during machine creation: not supported (vCenter only)"

2018/05/27 01:32:14 [INFO] stdout: Creating CA: management-state/node/nodes/test1/certs/ca.pem
2018/05/27 01:32:15 [INFO] stdout: Creating client certificate: management-state/node/nodes/test1/certs/cert.pem
2018/05/27 01:32:16 [INFO] stdout: Running pre-create checks...
2018/05/27 01:32:17 [INFO] stdout: Creating machine...
2018/05/27 01:32:17 [INFO] stdout: (test1) Image cache directory does not exist, creating it at management-state/node/nodes/test1/cache...
2018/05/27 01:32:17 [INFO] stdout: (test1) Downloading management-state/node/nodes/test1/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros.iso...
2018/05/27 01:32:26 [INFO] stdout: (test1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2018/05/27 01:32:26 [INFO] stdout: (test1) Generating SSH Keypair...
2018/05/27 01:32:29 [INFO] stdout: (test1) Creating VM...
2018/05/27 01:32:29 [INFO] stdout: (test1) Uploading Boot2docker ISO ...
2018/05/27 01:32:43 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2018/05/27 01:32:43 [INFO] stdout:
2018/05/27 01:32:43 [INFO] Generating and uploading node config test1
E0527 01:32:43.641542       1 generic_controller.go:204] NodeController c-htmck/m-x9twd [node-controller] failed with : Error creating machine: Error in driver during machine creation: not supported (vCenter only)
2018/05/27 01:32:43 [INFO] NodeController c-htmck/m-x9twd completed with dropped err: [node-controller] failed with : Error
2018/05/27 01:32:44 [INFO] NodeController c-htmck/m-x9twd completed with dropped err: [node-controller] failed with : Error
2018-05-27 01:32:59.870981 I | mvcc: store.index: compact 503805
2018-05-27 01:32:59.873562 I | mvcc: finished scheduled compaction at 503805 (took 1.930844ms)
 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by Itiho** [comment]
Use rancheer OS for vmware image: https://github.com/rancher/os/releases/download/v1.4.0-rc2/rancheros-vmware.iso

The default image need internet connection for vmware tools download. 
The rancheros-vmware.iso image have vmware tools include in iso.

**Comment by landloos** [comment]
I did try that image and it makes no difference. I still get the same error:

2018/05/27 23:42:36 [INFO] stdout: Creating CA: management-state/node/nodes/kub-man1/certs/ca.pem
2018/05/27 23:42:36 [INFO] stdout: Creating CA: management-state/node/nodes/kub-work2/certs/ca.pem
2018/05/27 23:42:37 [INFO] stdout: Creating CA: management-state/node/nodes/kub-work1/certs/ca.pem
2018/05/27 23:42:38 [INFO] stdout: Creating client certificate: management-state/node/nodes/kub-man1/certs/cert.pem
2018/05/27 23:42:38 [INFO] stdout: Creating client certificate: management-state/node/nodes/kub-work2/certs/cert.pem
2018/05/27 23:42:39 [INFO] stdout: Creating client certificate: management-state/node/nodes/kub-work1/certs/cert.pem
2018/05/27 23:42:39 [INFO] stdout: Running pre-create checks...
2018/05/27 23:42:41 [INFO] stdout: Running pre-create checks...
2018/05/27 23:42:42 [INFO] stdout: Running pre-create checks...
2018/05/27 23:42:42 [INFO] stdout: Creating machine...
2018/05/27 23:42:42 [INFO] stdout: (kub-man1) Image cache directory does not exist, creating it at management-state/node/nodes/kub-man1/cache...
2018/05/27 23:42:42 [INFO] stdout: (kub-man1) Downloading management-state/node/nodes/kub-man1/cache/boot2docker.iso from https://github.com/rancher/os/releases/download/v1.4.0-rc2/rancheros-vmware.iso...
2018/05/27 23:42:43 [INFO] stdout: Creating machine...
2018/05/27 23:42:43 [INFO] stdout: (kub-work1) Image cache directory does not exist, creating it at management-state/node/nodes/kub-work1/cache...
2018/05/27 23:42:43 [INFO] stdout: (kub-work1) Downloading management-state/node/nodes/kub-work1/cache/boot2docker.iso from https://github.com/rancher/os/releases/download/v1.4.0-rc2/rancheros-vmware.iso...
2018/05/27 23:42:43 [INFO] stdout: Creating machine...
2018/05/27 23:42:43 [INFO] stdout: (kub-work2) Image cache directory does not exist, creating it at management-state/node/nodes/kub-work2/cache...
2018/05/27 23:42:43 [INFO] stdout: (kub-work2) Downloading management-state/node/nodes/kub-work2/cache/boot2docker.iso from https://github.com/rancher/os/releases/download/v1.4.0-rc2/rancheros-vmware.iso...
2018-05-27 23:43:01.617351 I | mvcc: store.index: compact 623444
2018-05-27 23:43:01.619974 I | mvcc: finished scheduled compaction at 623444 (took 1.987294ms)
2018-05-27 23:43:19.196584 W | wal: sync duration of 2.304582558s, expected less than 1s
2018/05/27 23:43:20 [INFO] stdout: (kub-man1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2018/05/27 23:43:21 [INFO] stdout: (kub-man1) Generating SSH Keypair...
2018/05/27 23:43:24 [INFO] stdout: (kub-man1) Creating VM...
2018/05/27 23:43:25 [INFO] stdout: (kub-man1) Uploading Boot2docker ISO ...
2018/05/27 23:43:39 [INFO] stdout: (kub-work2) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2018/05/27 23:43:40 [INFO] stdout: (kub-work2) Generating SSH Keypair...
2018/05/27 23:43:43 [INFO] stdout: (kub-work2) Creating VM...
2018/05/27 23:43:44 [INFO] stdout: (kub-work2) Uploading Boot2docker ISO ...
2018/05/27 23:43:44 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2018/05/27 23:43:44 [INFO] stdout:
2018/05/27 23:43:48 [INFO] Generating and uploading node config kub-man1
E0527 23:43:48.415541       1 generic_controller.go:204] NodeController c-gwdfc/m-lx8vd [node-controller] failed with : Error creating machine: Error in driver during machine creation: not supported (vCenter only)
2018/05/27 23:43:48 [INFO] NodeController c-gwdfc/m-lx8vd completed with dropped err: [node-controller] failed with : Error
2018/05/27 23:43:48 [INFO] NodeController c-gwdfc/m-lx8vd completed with dropped err: [node-controller] failed with : Error
2018/05/27 23:43:52 [INFO] stdout: (kub-work1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2018/05/27 23:43:53 [INFO] stdout: (kub-work1) Generating SSH Keypair...
2018/05/27 23:43:56 [INFO] stdout: (kub-work1) Creating VM...
2018/05/27 23:43:57 [INFO] stdout: (kub-work1) Uploading Boot2docker ISO ...
2018/05/27 23:44:01 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2018/05/27 23:44:01 [INFO] stdout:
2018/05/27 23:44:02 [INFO] Generating and uploading node config kub-work2
E0527 23:44:02.635638       1 generic_controller.go:204] NodeController c-gwdfc/m-lztq5 [node-controller] failed with : Error creating machine: Error in driver during machine creation: not supported (vCenter only)
2018/05/27 23:44:02 [INFO] NodeController c-gwdfc/m-lztq5 completed with dropped err: [node-controller] failed with : Error
2018/05/27 23:44:03 [INFO] NodeController c-gwdfc/m-lztq5 completed with dropped err: [node-controller] failed with : Error
2018/05/27 23:44:15 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2018/05/27 23:44:15 [INFO] stdout:
2018/05/27 23:44:16 [INFO] Generating and uploading node config kub-work1
**E0527 23:44:16.163667       1 generic_controller.go:204] NodeController c-gwdfc/m-mlqts [node-controller] failed with : Error creating machine: Error in driver during machine creation: not supported (vCenter only)**
2018/05/27 23:44:16 [INFO] NodeController c-gwdfc/m-mlqts completed with dropped err: [node-controller] failed with : Error
2018/05/27 23:44:17 [INFO] NodeController c-gwdfc/m-mlqts completed with dropped err: [node-controller] failed with : Error

**Comment by Itiho** [comment]
In vSphere 6.5 works for me. You trie use boot2docker.iso instead rancheros? I no have vSphere 6.7 to test.

**Comment by landloos** [comment]
yeah, I tried the standard one that the vsphere node driver is configured for by default:

https://github.com/boot2docker/boot2docker/releases/download/v17.03.2-ce/boot2docker.iso

That doesnt work either. Same error.

**Comment by vincent99** [comment]
I don't think this has anything to do with the ISO being used, but with using one of the options for the driver that just isn't supported for ESXi vs vCenter.

**Comment by loganhz** [comment]
Thanks for the report.
Can you submit your issue to https://github.com/rancher/os/issues if you can still reproduce the issue, please?
