### ISSUE TITLE
New container started with host tag did not create required 

### ISSUE THREAD

**Issue by smw355** [rancher/rancher#1373]
Using the custom host feature in the UI, I deployed a host using the Docker script and included  two host labels, the second of which was "monitored=true".  I already had two services with Global.true scheduling settings. One of the two services was restrained based on requiring the host tag "monitored=true".

When the host came up, only the service that was not looking for the tag started. The second service didn't start, even though the tag was present on the new host.  When I later started a host using the machine integration using the tag, the service started on that host, and the service also started on the host I added earlier.

**Comment by deniseschannon** [comment]
neither @sangeethah or @sonchang have been able to reproduce. whenever they add hosts using the custom host command, the container starts.

@smw355 if it happens again, please share your setup so @sonchang could take a look.

**Comment by sonchang** [comment]
I just tried to reproduce this but wasn't able to.  Both my global services started up on the newly provisioned host.  Shouldn't matter but what was the other label besides "monitored=true"?
Also, if you can include the compose files for the 2 global services, I'm wondering whether there might be anything in them that could be important.  Thanks!

**Comment by deniseschannon** [comment]
@smw355 Closing as no one was able ot reproduce. If you see it again, please re-open.
