### ISSUE TITLE
Rancher NFS Not Compatible

### ISSUE THREAD

**Issue by Ayman250** [rancher/rancher#13731]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 0.13.11
network-services: 0.10.2
scheduler:
kubernetes (if applicable): 1.95

I'm running the rancher-openstack image on an openstack deployment and I'm trying to spin up Rancher NFS. I see a Not-Compatible in the catalog list and I am wondering what I'm missing or what some common causes there are for seeing. I actually see it for all of the storage catalogs. 

Thank you.

**Comment by cjellick** [comment]
Its the fact that you are in a kubernetes environment. The ones marked as not compatible can only be used in cattle environments. Feel free to reopen if this doesnt fully answer your question.

**Comment by Ayman250** [comment]
Thanks a lot for the help! In that case, what is the best way to use NFS with Kubernetes. Sorry I am new to this and I'm having trouble finding working examples withe Rancher and Kubernetes and NFS.

**Comment by cjellick** [comment]
If you're using v1.6, I think just following this example is going to be your best bet:
https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs
