### ISSUE TITLE
Rancher NFS - I/O errors between managed and host network

### ISSUE THREAD

**Issue by gregori-goossens** [rancher/rancher#13741]
**Rancher versions:**
rancher/server : 1.6.14 or 1.6.16 (maybe 1.6.17 not tested)
rancher/agent or rancher/rancher-agent:

**Operating system and kernel:**
Rancher OS (see setup detail)

**Type/provider of hosts:**
Bare-metal (ovh cloud)

**Summary**

- Nfs Server in docker nfs 4 run with a “managed” network (ip like 10.42.x.x).
- Rancher Driver (rancher : 1.6.14 & rancher-nfs 0.8.5 or Rancher 1.6.16 & rancher-nfs 0.9) run with “host” network.
- Stack with rancher nfs volume as usual.

Every thing works fine if i have rancher volume nfs mounted only on 1 host, if a launch stack with rancher nfs volume on another host, i experiencing i/o errors on read alternatively and randomly on each stack.

**Setup details:**

1. Server 1 : Rancher Server
Type : bare metal
Os : Rancher v1.0.4 or v1.3.0
DB : external mariadb in docker

2. Server 2 : Rancher Data
Type : bare metal
Os : Rancher v1.0.4 or v1.3.0 (with Kernel headers) or Ubuntu 16.04
Rancher agent
NFS Server in docker using “managed” network and fixed ip (10.42.x.x)

3. Server 3 : Rancher HOST 01
Type : bare metal
Os : Rancher v1.0.4 or v1.3.0
Rancher agent
Simple stack : App01 with alpine and nginx : with Rancher NFS Volume mounted

4. Server 4 : Rancher HOST 02
Type : bare metal
Os : Rancher v1.0.4 or v1.3.0
Rancher agent
Simple stack : App02 with alpine and nginx : with Rancher NFS Volume mounted

**Steps to Reproduce:**
connect to shell on App01 and App02 read single line file content on each in loop and get i/o errors randomly.

**Environment Template:**
Cattle

**Results:**
I/O errors on reading in multiple rancher nfs volume mounted on multiple host when Nfs server run in docker with managed network and rancher-nfs driver use host network.

**Important:**

If i run NFS Server docker with “host” network and target Rancher Data real ip in rancher driver it seems to work well.

Is there somebody have the same issue ?

Thanks.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
