### ISSUE TITLE
DNSimple rancher/external-dns:v0.7.11 fails to fetch the current dns record state/list.

### ISSUE THREAD

**Issue by mrrooijen** [rancher/rancher#13747]
I've just upgraded to the latest external-dns image (**rancher/external-dns:v0.7.11**) so that I can make use of the new DNSimple API. Since then, it continuously tries to add records that already exist, which fail with http 400. This also prevents new records from being added as they're added in batches, and if there's one duplicate then the entire operation fails.

Looking at the debug logs, without knowing the internals, it seems that it performs 4 main operations:

1. Fetch the current record state/list from DNSimple
2. Diff it against the desired state (determined locally)
3. Remove records from DNSimple based on the diff (if any)
4. Add records to DNSimple based on the diff (if any)

When looking at the debug logs it appears that the first operation, where it collects the current record state/list from DNSimple, is empty when it shouldn't be. This leads to the "add operation" to add all records.

Debug Logs:

    5/28/2018 2:42:15 PM time="2018-05-28T14:42:15Z" level=debug msg="DNS records from provider: map[]"
    5/28/2018 2:42:15 PM time="2018-05-28T14:42:15Z" level=debug msg="No DNS records to remove"
    5/28/2018 2:42:15 PM time="2018-05-28T14:42:15Z" level=debug msg="DNS records to add: [{server logs {server.logs.example.com. [1.2.3.4] A 60}} {server metrics {server.metrics.example.com. [1.2.3.4] A 60}} {server logdrain {server.logdrain.example.com. [1.2.3.4 1.2.3.4 1.2.3.4 1.2.3.4 1.2.3.4 1.2.3.4 1.2.3.4] A 60}} {  {external-dns-1128abef-fac3-4184-a7ed-eda630209c84.example.com. [server.logdrain.example.com. server.logs.example.com. server.metrics.example.com.] TXT 60}}]"

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
