### ISSUE TITLE
HostPort with explicit HostIP ignored?

### ISSUE THREAD

**Issue by XA21X** [rancher/rancher#13743]
**Rancher versions:**
rancher/rancher: 2.0.2

**Docker version:**
18.03.1-ce

**Operating system and kernel:**
NixOS 18.03 (Linux 4.14.41)

**Type/provider of hosts:**
Bare-Metal (on Intel NUC)

**Setup details:**
Single Node Rancher

**IP addresses**:
* 10.0.10.10/24 (Primary, used by Rancher & Rancher Agent)
* 10.0.10.13/24 (Aliased, intended for workload A)
* 10.0.10.14/24 (Aliased, intended for workload B)

**Environment Template:**
Kubernetes

**Steps to Reproduce:**
* Deploy rancher `docker run -d --restart=unless-stopped -p 10.0.10.10:80:80 -p 10.0.10.10:443:443 -v /var/volumes/rancher:/var/lib/rancher rancher/rancher:v2.0.2`
* Create custom cluster and deploy agent on the same host.
* Deploy workload using HostPort with explicit host IP i.e mapping 10.0.10.13:8443 -> 8443.

**Results:**
* Rancher web interface is only accessible at 10.0.10.10 (expected).
* Service at 10.0.10.13:8443 is *also* accessible at *every* IP alias i.e. 10.0.10.10, 10.0.10.14, 127.0.0.1.
* Using *View in API* reveals that `containers[].ports[].hostIP` is correctly set to 10.0.10.13 but `publicEndpoints[].addresses[]` is set to 10.0.10.10 instead.

I am trying to setup various workloads with potentially *common* ports at different IP addresses on the same network interface / host, aiming to effectively use the single node as a multiple virtual servers. A previous installation running rancher v1.6.x handles this use case correctly.

After a little bit of digging, the [convertHostPortToEndpoint](https://github.com/rancher/rancher/blob/438fbc0562841e0e2da9035692dc0fd2966a0d91/pkg/controllers/user/endpoints/endpoints.go#L217) resolves the node IP instead of using what could (/should?) have been provided in `p.HostIP`, explaining the `publicEndpoints`, but I've yet to figure out why the service is exposed at *every* IP - as if it was set to 0.0.0.0.

**Comment by orangedeng** [comment]
@deniseschannon It is a Kubernetes and network plugin issue.
Kubernetes issue https://github.com/kubernetes/kubernetes/issues/65976 and 
Flanneld issue https://github.com/coreos/flannel/issues/1019.

I can fix it in the public endpoint side. But since those issues are not fixed, specifying host ip will still not work as excepted.

**Comment by galal-hussein** [comment]
@orangedeng i am still seeing the node address specified in the public endpoints instead of the what i specified in the workload settings:

![pub-endpoints](https://user-images.githubusercontent.com/3309968/43804834-b8458ffa-9a9d-11e8-94e6-c157ce0a5791.png)

**Comment by orangedeng** [comment]
@galal-hussein I test with the master build 8/8. 
1. Create workload with host port 
<img width="1337" alt="2018-08-08 3 24 48" src="https://user-images.githubusercontent.com/15376837/43822706-76080636-9b1f-11e8-9884-50e562229fa4.png">

2. After deploy success, I got public endpoint with the address I configure.
<img width="844" alt="2018-08-08 3 25 53" src="https://user-images.githubusercontent.com/15376837/43822710-79767d70-9b1f-11e8-92af-41008656be33.png">

**Comment by galal-hussein** [comment]
rancher/rancher:master at Aug 10th

i was able to confirm that public endpoints are configured with the defined hostport and endpoint:
```
"publicEndpoints": [
{
"addresses": [
"172.1.1.3"
],
"allNodes": false,
"ingressId": null,
"nodeId": "c-4zfrs:m-w7qgk",
"podId": null,
"port": 8080,
"protocol": "TCP",
"serviceId": null
}
],
```
