### ISSUE TITLE
Creating a deployement with kubectl, with correct field.cattle.io/ports annotation does not result in the service being automatically created

### ISSUE THREAD

**Issue by lonewulf** [rancher/rancher#13740]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
kubernetes: 1.10.1-rancher2-1

**Steps to Reproduce:**

deploy.yml:

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-nginx
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-nginx
  replicas: 3
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"nginx","kind":"ClusterIP","name":"80tcp02","protocol":"TCP","sourcePort":0}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-nginx
    spec:
      containers:
        image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: 80tcp02
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-registry

kubectl apply -f deploy.yml

**Results:**
deployment is created, but the 'nginx' service is not

Expected result:
When creating a deployment from the UI, a matching service is created and is automatically re-created if deleted, we should expect the same behavior when a deployment is created from kubectl with correct annotations.

**Comment by lonewulf** [comment]
OK, found that if you have the field.cattle.io/creatorId annotation set, then it has the same behavior as creating a workload with the UI.

I think another annotation should be used as it is quite confusing atm, for ex. it should be something along "field.cattle.io/cattleManaged: true"

**Comment by vincent99** [comment]
`*.cattle.io` annotations are internal implementation details and not a public interface.

If you want the behavior of our API/UI/CLI, use them.

If you use kubernetes's API/kubectl then you get normal kubernetes behavior, where you define services as separate resources.

**Comment by lonewulf** [comment]
I certainly would use the CLI if it was possible to create workloads with it... until then I'm stuck with kubectl and trying to have a consistent behavior between the UI and what I have as a command line.

Regards,
