### ISSUE TITLE
Can't see host created with API in UI

### ISSUE THREAD

**Issue by cnzg** [rancher/rancher#1374]
Rancher server machine is 192.168.3.74, version is v0.25.0, Docker version is 1.6.2

i created a host with CLI API in UI, the Docker version of this host is 1.7.0, but i cannot see it in Rancher UI.

Environment detail information:

1) Rancher Server:

ubuntu@ubuntu:~$ sudo docker version
[sudo] password for ubuntu:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
ubuntu@ubuntu:~$ sudo docker ps
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                          NAMES
4d5ad05bb0d6        mysql:latest                    "/entrypoint.sh mysq   24 minutes ago      Up 24 minutes       3306/tcp                                       8d6da055-3b0f-45b4-a781-9157c7dd7d07
017969c53536        mysql:latest                    "/entrypoint.sh mysq   About an hour ago   Up About an hour    3306/tcp                                       wordpressdb
6e9ad70761f6        rancher/agent-instance:v0.3.1   "/etc/init.d/agent-i   About an hour ago   Up About an hour    0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   c6550dc2-58ec-4a18-b269-3b2dc965a449
5a450d1d925c        rancher/agent:v0.7.9            "/run.sh run"          5 hours ago         Up 5 hours                                                         rancher-agent
ca2ad55ba33a        rancher/server:latest           "/usr/bin/s6-svscan    5 hours ago         Up 5 hours          3306/tcp, 0.0.0.0:8080->8080/tcp               happy_poitras
ubuntu@ubuntu:~$

2) Rancher Agent:
ubuntu@ubuntu:~$ sudo docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
28a5bde45f0f        rancher/agent:v0.7.9   "/run.sh run"       18 minutes ago      Up 18 minutes                           rancher-agent
ubuntu@ubuntu:~$
ubuntu@ubuntu:~$
ubuntu@ubuntu:~$ sudo docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

**Comment by cnzg** [comment]
Oh, after 12 hours, this moring, the created host display in Rancher UI.

Why need such a long time?

**Comment by deniseschannon** [comment]
Did you try to refresh the browser after adding the host? It usually only takes 1-2 minutes after the rancher/agent container is running before showing up in the UI. 

It sounds as if you had to log back into the UI and the screen refreshed and the host appeared. 

Could you try to reproduce and after the rancher/agent container has started, refresh the UI to see if it still isn't working?

**Comment by deniseschannon** [comment]
@cnzg If you are still having issues, please re-open.
