### ISSUE TITLE
Add the ability to manage workloads to the rancher CLI

### ISSUE THREAD

**Issue by lonewulf** [rancher/rancher#13748]
**Rancher versions:**
rancher/cli: 2.0.1

As I was told in issue #13740    that if I want to have a consistent behavior between UI and using a CLI client, I should stick to the Rancher CLI to create workloads, it would be really wonderful to add their management to the Rancher CLI.

Kind Regards,

**Comment by etlweather** [comment]
What can one do with `rancher-cli`? Doesn't seem much per what I can find in `rancher help`.

But conversely, I don't seem to have trouble creating all the objects with `kubectl` - created workloads, services and ingress.

**Comment by JasonvanBrackel** [comment]
A user watching this issue requested that we tackle reload when we attack this enhancement.
