### ISSUE TITLE
Add/Generate the swagger definition of the Rancher v3 API

### ISSUE THREAD

**Issue by lonewulf** [rancher/rancher#13749]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

Most of API managers needs to have a proper definition of an API to be able to properly publish it, and interacting programmatically with it is really easier with a swagger definition. Is that something that can happen in a near future ?

Regards,

**Comment by bostrowski13** [comment]
I would find swagger documentation for this very useful as well.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/12925
