### ISSUE TITLE
Metrics server should be deployable as an addon and working on every Rancher deployed cluster

### ISSUE THREAD

**Issue by lonewulf** [rancher/rancher#13745]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

metrics-server should be an add-on, and kubelet and apiserver configured in manner that allows the metrics server and thus HPA to work on a rancher deployed cluster

**Comment by JasonvanBrackel** [comment]
@lonewulf While this is being worked on, you can get metrics-server working on rancher 2.0
https://github.com/JasonvanBrackel/metrics-server-on-rancher-2.0.2

**Comment by lonewulf** [comment]
@JasonvanBrackel Thanks, that's exactly the thing I ended doing yesterday :)

**Comment by Itiho** [comment]
I get error:

Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)

**Comment by deniseschannon** [comment]
We're going to add this add-on as an option for RKE managed clusters, where by default, it will be turned on and you will have the option to disable it.

**Comment by galal-hussein** [comment]
rancher/rancher:master at july 23rd

I was able to confirm that metrics server has been deployed successfully to every cluster created:
```
# Run kubectl commands inside here
# e.g. kubectl get all
> kubectl top nodes
NAME      CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
rke-do1   87m          4%        1635Mi          42%
rke-do2   102m         5%        1504Mi          39%
rke-do3   125m         6%        1596Mi          41%
> kubectl top pods --all-namespaces
NAMESPACE       NAME                                    CPU(cores)   MEMORY(bytes)
cattle-system   cattle-cluster-agent-5d8d4b5c6f-476wf   0m           15Mi
cattle-system   cattle-node-agent-7tnwc                 6m           28Mi
cattle-system   cattle-node-agent-qtq99                 0m           11Mi
cattle-system   cattle-node-agent-tjfl9                 0m           11Mi
default         nginx-4gjps                             0m           1Mi
default         nginx-5fzl7                             0m           1Mi
default         nginx-6qbcf                             0m           1Mi
ingress-nginx   default-http-backend-797c5bc547-74zmd   0m           2Mi
ingress-nginx   nginx-ingress-controller-cm26n          2m           43Mi
kube-system     canal-68bkz                             19m          45Mi
kube-system     canal-8q9sj                             12m          46Mi
kube-system     canal-ndvjp                             14m          45Mi
kube-system     kube-dns-7588d5b5f5-fnsjj               0m           22Mi
kube-system     kube-dns-autoscaler-5db9bbb766-gtswl    0m           5Mi
kube-system     metrics-server-97bc649d5-v6grf          0m           12Mi
```

**Comment by fellipecm** [comment]
Hi, I have created a cluster using RKE v0.1.9-rc9 and Rancher Server v2.0.7-rc2, should I be able to see the metrics on this version or it has not been released yet? Thanks!
$ kubectl --kubeconfig=kube_config_rancher-cluster.yml get hpa/site
NAME      REFERENCE         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
site      Deployment/site   <unknown> / 20%   2         5         2          16m

**Comment by qasim9641** [comment]
Hi I have deployed the Kubernetes cluster using latest rke v0.1.9 .The metric server gets deployed successfully .Kubectl top nodes and kubectl top pods command works fine.But when I open up the kubernetes dashboard then I am not able to see the metrics on Dashboard like CPU usages .When I look at the logs of the Kubernetes dashboard pod I am seeing following messages 

No metric client provided. Skipping metrics
2018/09/24 02:34:59 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds
