### ISSUE TITLE
添加机器时候 --lable 不生效

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#13750]
添加机器的时候,虽然选择了添加标签,但是添加完后的机器并没有标签

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/12691
