### ISSUE TITLE
Rancher doesn't recreate nodes that become unreachable and go away

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13756]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.2

**Infrastructure Stack versions:**
kubernetes (if applicable): 10.1

**Docker version: (`docker version`,`docker info` preferred)** 17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** centos-7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher

**Steps to Reproduce:**

Create a cluster using the Rancher Kubernetes Engine. e.g Openstack

Create node pools with 3 types of roles; e.g

2x master
3x etcd
3x worker

When cluster is ready, delete a cloud VM, e.g `worker1`

The node `worker1` is marked as unhealthy in Rancher after a few seconds.
The node `worker1` is eventually removed from Kubernetes and all its pods evicted after the default timeout (about 5 mins).

**Results:**

The missing node `worker1` is not reprovisioned automatically by Rancher.
There is no reconciliation loop in place to watch over Kubernetes node objects that are unhealthy or missing to replace them.

**Comment by sangeethah** [comment]
@alexandrem Currently the nodes in "Unavailable" state do not automatically get deleted from the node pool and so new node provisioning does not get triggered.

Once the node that is in "unavailable" state gets deleted from rancher-ui , new node will get auto provisioned.

**Comment by alexandrem** [comment]
@sangeethah Yes I'm aware.

Sorry if this issue sounded like a bug at first, but it's really more to have design spec discussed and implement it.

I was surprised it wasn't already in the Rancher V2 release, since I believe everything should be in place in the core to support this (correct me if I'm wrong).

**Comment by deniseschannon** [comment]
@alexandrem I'm going to close this in favor of https://github.com/rancher/rancher/issues/15737
