### ISSUE TITLE
Make splunk HEC index configurable

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13755]
This is currently not configurable and defaults to `main`: https://github.com/brycied00d/fluent-plugin-splunk-http-eventcollector/blob/master/lib/fluent/plugin/out_splunk-http-eventcollector.rb#L49

**Comment by aiwantaozi** [comment]
In Splunk hec, when you generate the token, it will ask what index for this token, when you use this token it will send to the index you config in the Splunk, if want change to another index, you could edit index list in Splunk or use another token. The index is stick to token.
![image](https://user-images.githubusercontent.com/5936271/41139725-113d976c-6b1c-11e8-95a3-eec964479fcb.png)

**Comment by aiwantaozi** [comment]
And we change the plugin to https://github.com/fluent/fluent-plugin-splunk make sure we can support splunk ssl.

**Comment by orangedeng** [comment]
@superseb Is that good enough to solve your problem?

**Comment by deniseschannon** [comment]
@orangedeng @aiwantaozi From my understanding, you can have one token with multiple indexes, so we should be able to set the index for the token.

**Comment by aiwantaozi** [comment]
@deniseschannon  You could the above picture from Splunk config, a token with multiple indexes are allowed, and will config the default one in Splunk. If user not set the index in Rancher, will send to the default, is user set the index in Rancher(the index should in the allowed list) will send to the user set one.

**Comment by deniseschannon** [comment]
If you have a token with multiple indexes, how/where can i set which index to use in Rancher? The issue is to be able to select another index for that token. 

<img width="1286" alt="screen shot 2018-06-14 at 4 13 11 pm" src="https://user-images.githubusercontent.com/11410997/41442820-012186c8-6fee-11e8-9339-7b4386aa7d53.png">

**Comment by bmdepesa** [comment]
rancher/rancher:v2.0.3-rc1

I was able to configure the HEC index. 

Deployed splunk -- created token with 3 indexes (history, main, summary)
Configured logging to 'history'
Saw logs in history index
Configured logging to 'main' index
Saw logs forwarded to maain index.
