### ISSUE TITLE
Rancher UI javascript crash when loading custom Catalog stack

### ISSUE THREAD

**Issue by dbsanfte** [rancher/rancher#13754]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: 0.13.11
network-services: 0.10.2
scheduler: 0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS (4.13.0)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Custom (Azure)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA x4 nodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Create a custom Rancher catalog entry with the following YMLs:

https://gist.github.com/dbsanfte/31bc4c24d36b39bb73f0aa8adaad83ee

**Results:**

There is a race condition in the stack creation whereby as it's created from the catalog entry, often no services will be shown (although the services/containers will start up fine). Attempting to view them will generate a javascript error on the Rancher page and from then on, that environment will not be viewable without going in as another user and deleting the wonky catalog stack.

Chrome dev tools view below:

https://imgur.com/a/jBfhxJ7

**Comment by dbsanfte** [comment]
@tfiduccia 

This is a v1.6 bug

**Comment by tfiduccia** [comment]
@dbsanfte - thanks for seeing that!  So used to marking thing 2.0, my fingers were on automatic.

**Comment by dbsanfte** [comment]
Here is the stack object as seen from the API view, when in the Rancher UI it can't be expanded and no services are visible. 

`{
"id": "1st1059",
"type": "stack",
"links": {
"self": "…/v2-beta/projects/1a8013/stacks/1st1059",
"account": "…/v2-beta/projects/1a8013/stacks/1st1059/account",
"hosts": "…/v2-beta/projects/1a8013/stacks/1st1059/hosts",
"instances": "…/v2-beta/projects/1a8013/stacks/1st1059/instances",
"scheduledUpgrades": "…/v2-beta/projects/1a8013/stacks/1st1059/scheduledupgrades",
"secrets": "…/v2-beta/projects/1a8013/stacks/1st1059/secrets",
"services": "…/v2-beta/projects/1a8013/stacks/1st1059/services",
"volumeTemplates": "…/v2-beta/projects/1a8013/stacks/1st1059/volumetemplates",
"volumes": "…/v2-beta/projects/1a8013/stacks/1st1059/volumes",
"composeConfig": "…/v2-beta/projects/1a8013/stacks/1st1059/composeconfig"
},
"actions": {
"deactivateservices": "…/v2-beta/projects/1a8013/stacks/1st1059/?action=deactivateservices",
"activateservices": "…/v2-beta/projects/1a8013/stacks/1st1059/?action=activateservices",
"upgrade": "…/v2-beta/projects/1a8013/stacks/1st1059/?action=upgrade",
"addoutputs": "…/v2-beta/projects/1a8013/stacks/1st1059/?action=addoutputs",
"update": "…/v2-beta/projects/1a8013/stacks/1st1059/?action=update",
"exportconfig": "…/v2-beta/projects/1a8013/stacks/1st1059/?action=exportconfig",
"remove": "…/v2-beta/projects/1a8013/stacks/1st1059/?action=remove"
},
"baseType": "stack",
"name": "logstash",
"state": "active",
"accountId": "1a8013",
"answers": null,
"binding": null,
"created": "2018-05-20T11:21:29Z",
"createdTS": 1526815289000,
"description": null,
"dockerCompose": "version: '2'\nservices:\n  logstash-collector-config:\n    image: rancher/logstash-config:v0.2.0\n    links:\n    - redis:redis\n    labels:\n      io.rancher.scheduler.global: 'true'\n      io.rancher.container.hostname_override: container_name\n  elasticsearch:\n    image: rancher/external-service\n  logstash-collector:\n    image: docker.elastic.co/logstash/logstash:6.2.3\n    stdin_open: true\n    tty: true\n    links:\n    - redis:redis\n    volumes_from:\n    - logstash-collector-config\n    ports:\n    - 5000:5000/udp\n    - 6000:6000/tcp\n    command:\n    - /bin/bash\n    - -c\n    - logstash-plugin install logstash-output-datadog_logs && logstash -f /etc/logstash\n    labels:\n      io.rancher.sidekicks: logstash-collector-config\n      io.rancher.container.hostname_override: container_name\n      io.rancher.scheduler.affinity:host_label_ne: load_balancer=true\n      io.rancher.scheduler.global: 'true'\n  logstash-indexer:\n    image: docker.elastic.co/logstash/logstash:6.2.3\n    stdin_open: true\n    tty: true\n    links:\n    - redis:redis\n    - elasticsearch:elasticsearch\n    volumes_from:\n    - logstash-indexer-config\n    command:\n    - /bin/bash\n    - -c\n    - logstash-plugin install logstash-output-datadog_logs && logstash -f /etc/logstash\n    labels:\n      io.rancher.sidekicks: logstash-indexer-config\n      io.rancher.container.hostname_override: container_name\n      io.rancher.scheduler.affinity:host_label_ne: load_balancer=true\n  redis:\n    image: redis:3.2.6-alpine\n    stdin_open: true\n    tty: true\n    labels:\n      io.rancher.container.hostname_override: container_name\n      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}\n      io.rancher.scheduler.affinity:host_label_ne: load_balancer=true\n  logstash-indexer-config:\n    image: rancher/logstash-config:v0.2.0\n    links:\n    - redis:redis\n    - elasticsearch:elasticsearch\n    labels:\n      io.rancher.container.hostname_override: container_name\n",
"environment": { },
"externalId": "catalog://cardano:logstash:0",
"group": null,
"healthState": "healthy",
"kind": "stack",
"outputs": null,
"previousEnvironment": null,
"previousExternalId": null,
"rancherCompose": ".catalog:\n  name: logstash\n  version: v2.0.0\n  description: Logstash stack for Cardano backend environments\n  minimum_rancher_version: v1.6.0\n  maximum_rancher_version: v99.99.99\n\nversion: '2'\nservices:\n  logstash-collector-config:\n    metadata:\n      logstash: &id001\n        inputs: |-\n          udp {\n            port => 5000\n            codec => \"json\"\n          }\n          tcp {\n            port => 6000\n            codec => \"json\"\n          }\n        outputs: |-\n          redis {\n            host => \"redis.rancher.internal\"\n            port => \"6379\"\n            data_type => \"list\"\n            key => \"logstash\"\n          }\n    start_on_create: true\n  logstash-collector:\n    metadata:\n      logstash: *id001\n    start_on_create: true\n  logstash-indexer:\n    metadata:\n      logstash: &id002\n        filters: |-\n          if [short_message] =~ /^\\s*$$/ {\n            drop { }\n          }\n          mutate {\n            gsub => [\n                \"short_message\", \"\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]\", \"\",\n                \"short_message\", \"\\[\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{3}Z\\]\", \"\"\n            ]\n          }\n        inputs: |-\n          redis {\n            host => \"redis.rancher.internal\"\n            port => \"6379\"\n            data_type => \"list\"\n            key => \"logstash\"\n          }\n        outputs: |-\n          elasticsearch {\n            hosts => [\"api.address:9200\"]\n          }\n          stdout {\n            codec => rubydebug\n          }\n          datadog_logs {\n            api_key => \"asdf1234567890\"\n          }\n    scale: 2\n    start_on_create: true\n  redis:\n    scale: 1\n    start_on_create: true\n  logstash-indexer-config:\n    metadata:\n      logstash: *id002\n    scale: 2\n    start_on_create: true\n",
"removed": null,
"serviceIds": [ 4 items
"1s1502",
"1s1503",
"1s1504",
"1s1505"
],
"startOnCreate": true,
"system": false,
"templates": null,
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"uuid": "aab8e10b-bdb4-4133-ac8d-562b71289067"
}`

**Comment by tfiduccia** [comment]
Version - v1.6.22-rc2
Verified fixed - the service details page no longer blows up.
But @dbsanfte - since it's not pointing to anything in the yaml, there is no external hostname information.
![image](https://user-images.githubusercontent.com/11514927/44693986-fff8be80-aa1f-11e8-937e-ea995e0ac1d4.png)
