### ISSUE TITLE
rancher-agent keep killing nginx-proxy making rancher and all containers on the host unreachable - installation of rancher-rancher and cluster on same host 

### ISSUE THREAD

**Issue by 3pns** [rancher/rancher#13757]
**Rancher versions:**
rancher/server or rancher/rancher: stable
rancher/agent or rancher/rancher-agent: 2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build 2360430

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.14.42-coreos

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-Metal at OVH
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
jwilder/nginx-proxy installed with docker-compose
rancher is served via nginx-proxy

**Steps to Reproduce:**
create fresh CoreOs install
launch nginx-proxy with docker compose

> version: "2.1"
> 
> services:
>   nginx-proxy:
>     image: jwilder/nginx-proxy:latest
>     container_name: nginx-proxy
>     environment:
>       ENABLE_IPV6: "true"
>     ports:
>      - "80:80"
>      - "443:443"
>     volumes:
>       - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:ro'
>       - '/home/docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro'
>       - '/home/docker/nginx-proxy/conf.d:/etc/nginx/conf.d:rw'
>       - '/home/docker/nginx-proxy/proxy.conf:/etc/nginx/proxy.conf:rw'
>       - '/home/docker/nginx-proxy/html:/usr/share/nginx/html:rw'
>       - '/var/run/docker.sock:/tmp/docker.sock:ro'
>     network_mode: bridge
>     restart: always
>   letsencrypt-nginx-proxy-companion:
>     image: jrcs/letsencrypt-nginx-proxy-companion:latest
>     container_name: letsencrypt-nginx-proxy-companion
>     volumes_from:
>       - nginx-proxy
>     volumes:
>       - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:rw'
>       - '/var/run/docker.sock:/var/run/docker.sock:ro'
>       - '/home/docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw'
>     network_mode: bridge

launch rancher with docker-compose

> version: "2.1"
> 
> services:
>   rancher-rancher:
>     image: rancher/rancher:stable
>     container_name: rancher-rancher
>     ports:
>       - "80"
>       - "443"
>     environment:
>       VIRTUAL_PORT: 80
>       VIRTUAL_HOST: rancher.MyDomain.com
>       LETSENCRYPT_HOST: MyDomain.com
>       LETSENCRYPT_EMAIL: MyEmail@gmail.com
>     volumes:
>       - '/home/docker/rancher-rancher/rancher:/var/lib/rancher:rw'
>       - '/home/docker/rancher-rancher/log:/var/log:rw'
>     network_mode: "bridge"

Create a cluster in the GUI, copy the command to launch rancher-agent with all the 3 options ticked
executed the command on the host which is the same host where nginx-proxy and rancher-rancher are being launched 

> sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.0 --server https://MyServer.com --token MyToken --ca-checksum MyChecksum --etcd --controlplane --worker

the commands executed by rancher agent ends up killing nginx-proxy after few second which results in rancher being unavailable and the cluster provisioning being halted and all the container

I thought at first nginx-proxy must be crashing for whatever reason, but I was able to get the following error by relaunching nginx-proxy several time and returning to the gui ( cf screenshot )
![rancher-killer](https://user-images.githubusercontent.com/8484338/40667436-bdbe17bc-6394-11e8-8bba-56924b23aabe.png)

Why is the agent killing my nginx-proxy container ? Everytime I restart the nginx-proxy container, the rancher-agent restart the provisioning process and rekill the nginx-proxy container. It is not written in the documentation that rancher 2.0 is supposed to interact/kill other containers already present in the host. It means rancher can messed up a production server with other containers already launched.

After a while rancher is serving itself with I suppose it's own web server but doesn't work, impossible to login, the refresh button refresh the page and always show the same page

![screen shot 2018-05-29 at 11 16 21 pm](https://user-images.githubusercontent.com/8484338/40668242-8fb910e0-6396-11e8-8ad3-afa9da70f56c.png)

**Comment by superseb** [comment]
`nginx-proxy` is internally used by `rke` to setup the cluster, try calling it `my-nginx-proxy` and let me know how that goes.

**Comment by 3pns** [comment]
Thank you, I changed the name of my nginx-proxy container to my-custom-nginx-proxy and now it works. I was able to finish the provisioning and my-custom-nginx-proxy is not killed anymore.
May I suggest you change  the name of the nginx-proxy container used by rke as other people will encounter that problem.

**Comment by loganhz** [comment]
Cool! Thanks
