### ISSUE TITLE
Requires the ability to force an ongoing pipeline stop

### ISSUE THREAD

**Issue by jungju** [rancher/rancher#13752]
rancher/rancher:2.0.2

Requires the ability to force an ongoing pipeline stop.
Waiting for executables to be online is not stopped when a wrong image or bug occurs.

![image](https://user-images.githubusercontent.com/809189/40644054-fce0bd4c-635c-11e8-86da-b844f5502740.png)

**Comment by tfiduccia** [comment]
@aiwantaozi - I have noticed this as well.  There isn't a way to manually stop if I don't set it up properly.  I have to wait for timeouts.

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/5

Pipeline execution can be stopped, and the status is changed to `Aborted`
