### ISSUE TITLE
Name should be first in list for User list

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13764]
**Rancher versions:** 2.0 master 5/29

**Steps to Reproduce:**
1.  Go to User list page

**Results:**  ID is first and probably not the most useful field to see.  Make Name field first.
![image](https://user-images.githubusercontent.com/11514927/40685468-3170ddbc-6349-11e8-9816-5d4deb6a732a.png)

**Comment by sangeethah** [comment]
Tested with latest build from master:

"Name" is the first field in the Users list followed by id and "local Username"
