### ISSUE TITLE
kube-proxy cannot support IPVS with default RKE configuration

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13769]
Currently kube-proxy deployed by Rancher via RKE can only work in iptables or userspace modes, but not IPVS even though the feature gate is enabled by default since 1.10

The reason is that the kube-proxy container process doesn't have the `/lib/modules` host volume mounted, which is required to load the module (kube-proxy does a modprobe on `ip_vs` at start time and falls back to previous modes when it fails).

This is related to how the docker container is built in RKE `BuildKubeProxyProcess` function.

First approach to solve this would be to add the missing volume of `/lib/modules` as read-only mount in that function.

The second approach would be to not bootstrap the kube-proxy process in RKE but rather deploy it as a daemonset to the cluster via addon jobs. I personally would prefer this approach, since I believe it's the correct way to deploy it on most platforms. I don't see any advantages of having it being orchestrated statically outside of Kubernetes.

We can use the following base manifest as a reference:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/kube-proxy/kube-proxy-ds.yaml

Ideas?

**Comment by rdegez** [comment]
I would say that this issue is specific to RKE and not Rancher 2.0 ?

But everything you said remains true whatsoever, and I'm having the exact same issue with a RKE (v0.17) deployed cluster (i.e. kube-proxy not using ipvs whereas it should be the default since 1.10).

Cheers,

**Comment by alexandrem** [comment]
@rdegez Indeed this must be fixed in RKE repository.

However I believe the issue must be tracked here, since this is a meta repository that should encompass all issues that end users can face with Rancher.

**Comment by alexandrem** [comment]
This being said, I'm not sure this kube-proxy mode can be parameterized with the Rancher API right now (rancherKubernernetesEngine) and no way to change it in the UI neither.

Perhaps an opportunity to discuss adding this.

Also I suppose it would make a good default for Rancher clusters with release 1.10+

**Comment by prachidamle** [comment]
Currently see the following error in kube-proxy container logs:
```
W1028 21:20:18.394612    7537 server.go:216] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I1028 21:20:18.394649    7537 feature_gate.go:216] feature gates: &{map[]}
W1028 21:20:18.397319    7537 proxier.go:500] Failed to read file /lib/modules/4.4.0-1092-aws/modules.builtin with error open /lib/modules/4.4.0-1092-aws/modules.builtin: no such file or directory. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1028 21:20:18.398245    7537 proxier.go:513] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1028 21:20:18.398988    7537 proxier.go:513] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1028 21:20:18.399689    7537 proxier.go:513] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1028 21:20:18.400405    7537 proxier.go:513] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1028 21:20:18.401072    7537 proxier.go:513] Failed to load kernel module nf_conntrack_ipv4 with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1028 21:20:18.406726    7537 server_others.go:249] Flag proxy-mode="" unknown, assuming iptables proxy
I1028 21:20:18.417393    7537 server_others.go:143] Using iptables Proxier.
```

**Comment by prachidamle** [comment]
@alexandrem you can pass the proxy-mode parameter under `extra_args` for the `kubeproxy` service in the cluster.yml file while creating a cluster in the UI.

In the "Edit As Yaml" option in UI, add this under services:
```
    kubeproxy:
      extra_args:
        proxy-mode: ipvs
```

**Comment by ulm0** [comment]
@prachidamle that's not enough though, 'cause you still need the kernel modules. I'm currently using this config to achieve the ipvs behaviour:

```yaml
services:
  kubeproxy:
    extra_args:
      proxy-mode: ipvs
    extra_binds:
      - "/lib/modules:/lib/modules:ro"
```

You need to load `ip_vs`, `ip_vs_rr`, `ip_vs_wrr`, `ip_vs_sh`,`nf_conntrack_ipv4` modules beforehand.

**Comment by soumyalj** [comment]
Tested with v2.3.3-head with UI index latest-2.3
Created a DO RKE cluster with specifying kubeproxy config as below in cluster.yml file
```
    kubeproxy:
      extra_args:
        proxy-mode: ipvs
```
The cluster creation succeeded and cluster was functional. 
Docker inspect on the kubeproxy container on each of the hosts indicated the `proxy-mode:ipvs` as below
```
"Id": "ba7baee5768dec39e1b7b8ff58a3c3393c850b280c7bb3566a78af11a4345301",
        "Created": "2019-10-30T23:28:19.83651983Z",
        "Path": "/opt/rke-tools/entrypoint.sh",
        "Args": [
            "kube-proxy",
            "--cluster-cidr=10.42.0.0/16",
            "--hostname-override=test",
            "--kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml",
            "--v=2",
            "--healthz-bind-address=127.0.0.1",
            "--proxy-mode=ipvs"
```
Created nginx workloads and ping from each of the pod's IP to the cluster IP succeeded
Ping from each of the pods to other pods on different hosts was also successful. 

Creation of cluster using RKE standalone tool with kubeproxy mode set to ipvs was also tested. 
Cluster got created successfully and the kubeproxy container had the setting `proxy-mode = ipvs`

**Comment by prachidamle** [comment]
@ulm0 yes there is already a fix to bind-mount the volume coming in 2.3.3. My comment was about how to enable ipvs mode from Rancher UI while creating cluster in addition to this fix.

**Comment by Aisuko** [comment]
@soumyalj Hi, thanks for your comment. But I have a consider on there, I used rke==0.3.2 updated my cluster with the `proxy-mode = ipvs` parameter, but I didn't saw any role on worker nodes. So, I believe it was not working, so, what could we do?

```
[root@cont-32-rdc ~]# ipvsadm -l
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
```

**Comment by Aisuko** [comment]
> @soumyalj Hi, thanks for your comment. But I have a consider on here, I used rke==0.3.2 updated my cluster with the `proxy-mode = ipvs` parameter, but I didn't saw any role on worker nodes. So, Is there has any other thing I need to do?
> 
> ```
> [root@cont-32-rdc ~]# ipvsadm -l
> IP Virtual Server version 1.2.1 (size=4096)
> Prot LocalAddress:Port Scheduler Flags
>   -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
> ```

Finally, I followed @ulm0 solution, It seems worker for me.

```
ip addr

171: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 7e:79:a9:34:20:dc brd ff:ff:ff:ff:ff:ff
    inet 10.43.239.13/32 brd 10.43.239.13 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.45.167/32 brd 10.43.45.167 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.155.51/32 brd 10.43.155.51 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.87.60/32 brd 10.43.87.60 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.187.3/32 brd 10.43.187.3 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.65.194/32 brd 10.43.65.194 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.0.1/32 brd 10.43.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.47.236/32 brd 10.43.47.236 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.25.101/32 brd 10.43.25.101 scope global kube-ipvs0
       valid_lft forever preferred_lft forever

ipvsadm -Ln

TCP  10.43.187.41:443 rr
  -> 10.42.3.11:443               Masq    1      0          0
TCP  10.43.213.72:80 rr
TCP  10.43.232.194:80 rr
  -> 10.42.2.22:8888              Masq    1      0          0
TCP  10.43.239.13:80 rr
  -> 10.42.2.57:8090              Masq    1      0          0
TCP  10.43.243.120:80 rr
  -> 10.42.3.30:80                Masq    1      0          0
TCP  127.0.0.1:31364 rr
TCP  127.0.0.1:31923 rr
  -> 10.42.1.22:80                Masq    1      0          0
TCP  127.0.0.1:32760 rr
  -> 10.42.1.40:3000              Masq    1      0          0
TCP  172.17.0.1:31923 rr
  -> 10.42.1.22:80                Masq    1      0          0
UDP  10.43.0.10:53 rr
  -> 10.42.2.40:53                Masq    1      0          24
```

**Comment by ntcong** [comment]
Just add ipvs is not enough
```
E1105 02:58:17.277641  120955 server_others.go:259] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs_sh ip_vs_rr ip_vs_wrr]
```
kube-proxy do start with ipvs but it will fail back to iptables

**Comment by prachidamle** [comment]
@ntcong the fix to this issue will bind mount the required /lib/modules.

**Comment by kenperkins** [comment]
@soumyalj I think this should be considered for re-opening.

Because kube-proxy falls back to ip tables, I believe your test was invalid. Here's the logs from my kube-proxy with the same configuration, but without the mount mentioned by @ulm0:

```
W0506 19:21:27.159753   15477 proxier.go:513] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
E0506 19:21:27.188407   15477 server_others.go:259] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh]
I0506 19:21:27.188430   15477 server_others.go:266] Can't use ipvs proxier, trying iptables proxier
I0506 19:21:27.190084   15477 server_others.go:143] Using iptables Proxier.
```

**Comment by 20988902** [comment]
> 
> 
> @soumyalj I think this should be considered for re-opening.
> 
> Because kube-proxy falls back to ip tables, I believe your test was invalid. Here's the logs from my kube-proxy with the same configuration, but without the mount mentioned by @ulm0:
> 
> ```
> W0506 19:21:27.159753   15477 proxier.go:513] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
> E0506 19:21:27.188407   15477 server_others.go:259] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh]
> I0506 19:21:27.188430   15477 server_others.go:266] Can't use ipvs proxier, trying iptables proxier
> I0506 19:21:27.190084   15477 server_others.go:143] Using iptables Proxier.
> ```

I think you can executing shell commands manually like this on each node:
# modprobe ip_vs
# modprobe ip_vs_rr
# modprobe ip_vs_wrr
# modprobe ip_vs_sh

then restart kube-proxy
# docker restart kube-proxy

check the interface, if you can see "kube-ipvs0", that is success.
# ip add|grep ipvs
# ipvsadm -Ln
