### ISSUE TITLE
[Pipeline] Unable to add pipeline for repo in GitHub Enterprise

### ISSUE THREAD

**Issue by debourge** [rancher/rancher#13762]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 
network-services: 
scheduler: 0.8.3
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
18.03.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-127-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM in vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- [x] Setup OAuth for GitHub enterprise
- [x] Create a new pipeline and select a repo, from GitHub Enterprise
- [ ] Add build steps and click 'Add'

**Results:**
At this point I receive an error stating that a POST to http://api.github.com/<my-org>/<my-repo> can not be reached. Even though during the setup process, it had the correct github enterprise url.

**Comment by loganhz** [comment]
This issue has been fixed. Please try again
