### ISSUE TITLE
Shell control label in pipeline is not translated

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13768]
**Rancher versions:** 2.0 master 5/29

**Steps to Reproduce:**
1.  Go to Edit Step page in Pipeline
2.  Select run a script for Step Type

**Results:**  Notice the shell label text is not translated
![image](https://user-images.githubusercontent.com/11514927/40688906-c4429260-6354-11e8-81d2-f1a9ac675ca3.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/12

The shell label is translated and appearing correctly.
