### ISSUE TITLE
Ship Kubernetes audit logs to various targets, e.g., ELK, Splunk, syslog, Kafka.

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#13763]
Kubernetes has an audit log but it is not assessable from Rancher.  Add the ability to ship Kubernetes audit log to various targets, e.g., ELK, Splunk, syslog, Kafka.

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`` `admin`|
|Route|`authenticated.cluster.logging.logging`|

**Comment by paynejacob** [comment]
closing in favor of https://github.com/rancher/rancher/issues/31437

**Comment by emmeowzing** [comment]
I can second this one. Right now, I can't think of the right approach to scrape the logged audit events from the nodes besides writing my own DaemonSet Helm chart that just wraps tools that tail those logs and sends them to one of these targets.

**Comment by MKlimuszka** [comment]
Closing as stale.
