### ISSUE TITLE
The services wont start it creates all sorts of containers everywhere... I had to delete 70 of them at one point

### ISSUE THREAD

**Issue by turnupdigital** [rancher/rancher#13777]
*Describe your issue  Add at least one host
 Waiting for a host to be active
 Creating Kubernetes system stack
 Starting services
 Waiting for Kubernetes APIhere*

Its juts stuck...

Both Kubernetes and Mesos when I tried it where up and down... actually, cattle might have been working ok but the main reason I got rancher was to deploy Mesos... its not what I thought it was though. I cant get the thing to get back to a stable state

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.17` Cattle: `v0.183.49` UI: `v1.6.42` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.dashboard`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
