### ISSUE TITLE
Not able to access logs/exec into one of the pods of a daemon set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13771]
**Rancher versions: Build from master
**Steps to Reproduce:**
Created a custom cluster using rancher server with following configurations:
3 control nodes
3 etcd nodes
3 worked nodes

Ports opened for the nodes -
[Ports.xlsx](https://github.com/rancher/rancher/files/2052331/Ports.xlsx)

Deployed daemonset .
Not able to access logs/exec into one of the pods of a daemon set (out of 6 pods).

**Comment by galal-hussein** [comment]
@sangeethah kubectl exec/logs works by accessing kubelet port 10250 from the control node, and since we have kubelet on control node and they are schedulable, they need to be opened as well, ports (10250-10256)

**Comment by sangeethah** [comment]
@galal-hussein , After allowing inbound traffic to 10250 on control nodes from the all control nodes , log and exec containers for the pods deployed in all control nodes work as expected.
