### ISSUE TITLE
Edit container name isn't persistent

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#1377]
Edit container name in UI isn't persistent.

After reinstall rancher server / agent all containers use id instead of name. After edit container name und restart the container the new name is lost and replaced by the ID (not docker id, seems like Rancher container id: "a221bcbe-ffea-47ef-a27a-3d66afaeae69").

**Comment by cjellick** [comment]
Hi @pwFoo.

The rancher container name is only stored in the rancher database. By default, the rancher database is run inside the rancher/server container and reinstalling rancher/server means the database is lost. This is why you are losing the names. I believe we have docs for run the database outside of the rancher/server container (which should be done when running rancher for production), but I don't know the link the offhand. I'll respond later today with docs explaining that setup.

That said, with the addition of labels to docker, we can start giving containers user-friendly names. I've opened issue #1399 to track this.

**Comment by deniseschannon** [comment]
@pwFoo @cjellick Here's the link to how to set up an external database. http://rancher.docs.rancher.com/docs/installing-rancher/installing-server/#using-an-external-database

**Comment by pwFoo** [comment]
Hi and thanks @deniseschannon, but no need for an external database. If needed for persistent data I prefer an data only container ;)
I hope rancher container name will synced with the docker container name (docker ... --name=<NAME>).

**Comment by deniseschannon** [comment]
Since @cjellick opened #1399, I'll close this issue.

@pwFoo Please follow #1399 to see progress on the naming of containers.
