### ISSUE TITLE
Add support for PKCS#8-encoded private keys

### ISSUE THREAD

**Issue by MarkMangoba** [rancher/rancher#13779]
Rancher | v2.0.2
User Interface | v2.0.48

I've upgraded our version of Rancher and still having the issue of "Private Key is invalid" when trying to add a certificate.

**Comment by jadsonlourenco** [comment]
Temp solution: https://forums.rancher.com/t/adding-certificates-fail-with-private-key-is-invalid-solved/10585

**Comment by superseb** [comment]
When adding support for PKCS8 when mounting certificates for Rancher, I was already modifying the API for certs. See https://github.com/rancher/rancher/pull/14384 and https://github.com/rancher/rancher/issues/14383.
