### ISSUE TITLE
rancher 2.0.2 pipeline 无法成功

### ISSUE THREAD

**Issue by DevinXin** [rancher/rancher#13776]
*Describe your issue here*
pipeline 设置github账户的时候，会自动安装 rancher/jenkins 镜像，但是这个镜像一直启动不成功，报有些模块无法下载。 已确认防火墙关闭 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by loganhz** [comment]
Please describe your issue in English next time. 
We cannot help with current information you provided.  

You can find us via weChat by searching `RancherLabsChina` if you want to use Chinese.
