### ISSUE TITLE
Module rbd not found in directory /lib/modules/4.13.0-36-generic

### ISSUE THREAD

**Issue by adalga** [rancher/rancher#13774]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)** 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04 - 4.13.0-36-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:** 
I created a custom cluster via rancher 2.0.2. Then I created a ceph-rbd storage class and pvc. Then I created a workload which uses this pvc. 

**Results:**
FATAL: Module rbd not found in directory /lib/modules/4.13.0-36-generic

**Comment by rdissauer** [comment]
@adalga did you solve the problem? I have same issues with ceph-rbd and rancher v2.0.8

**Comment by adalga** [comment]
No. I am using ceph-fuse instead of ceph-rbd. I know the solution though. Check https://github.com/rancher/rke/issues/362

**Comment by sergii-bond** [comment]
@adalga following your reference, how exactly have you added /lib/modules to kubelet mounts for it to work ?

**Comment by sergii-bond** [comment]
Thank you. I found that per [this enhancement](https://github.com/rancher/rancher/issues/13076), the bind-mount can be added via `extra_binds` in cluster config yaml in rancher UI.

```
  kubelet: 
    extra_binds: 
      - "/lib/modules:/lib/modules"
```

After saving the changes the cluster updates kubelets containers. Now the result of `docker inspect <your_kubelet_container>` should have /lib/modules under Binds. After these changes the message `FATAL: Module rbd not found in directory ...` doesn't exist anymore.

**Comment by loganhz** [comment]
Thanks all!

Please see https://github.com/rancher/rancher/issues/13774#issuecomment-421633426 if you have the same issue.

**Comment by watersoona** [comment]
@sergii-bond 
I added kubelet binds config。
create deployments with pvc failed。

```

Warning | FailedMount | MountVolume.WaitForAttach failed for volume "pvc-18338be1-a141-11e9-96aa-5254c0a81b20" : rbd: map failed exit status 2, rbd output: modinfo: ERROR: could not get modinfo from 'rbd': Exec format error modprobe: ERROR: could not insert 'rbd': Exec format error rbd: failed to load rbd kernel module (1) rbd: sysfs write failed In some cases useful info is found in syslog - try "dmesg \| tail" or so. rbd: map failed: (2) No such file or directory | 9 minutes ago
-- | -- | -- | --
Warning | FailedMount | Unable to mount volumes for pod "test-77fcb66f95-nf2jb_default(184b84ab-a141-11e9-96aa-5254c0a81b20)": timeout expired waiting for volumes to attach or mount for pod "default"/"test-77fcb66f95-nf2jb". list of unmounted volumes=[test]. list of unattached volumes=[test default-token-jw2b4]

```

**Comment by sergii-bond** [comment]
@watersoona I think the key string to search solution for is "rbd: sysfs write failed". One of the claimed solutions I can find is following [this link](https://forum.proxmox.com/threads/mapping-image-fails-with-error-rbd-sysfs-write-failed.51070/). Hope it is helpful.

**Comment by watersoona** [comment]
> @watersoona I think the key string to search solution for is "rbd: sysfs write failed". One of the claimed solutions I can find is following [this link](https://forum.proxmox.com/threads/mapping-image-fails-with-error-rbd-sysfs-write-failed.51070/). Hope it is helpful.

thanks，it works !
