### ISSUE TITLE
It should be 'Environment Variables' rather than 'Ports' in pod detail view

### ISSUE THREAD

**Issue by NG85** [rancher/rancher#13772]
**Rancher versions:**
rancher/rancher:v2.0.0
rancher/rancher-agent:v2.0.0

**Infrastructure Stack versions:**
kubernetes:rancher/hyperkube:v1.10.1-rancher2

**Steps to Reproduce:**
1. [Workloads] Click on one workload to navigate to its detail view.
2. [Workload] Click on one pod to navigate to its pod view.

**Results:**
[Pod:XXX]There are two 'Ports' categories as shown in attached snapshot.
![snapshot](https://user-images.githubusercontent.com/36187521/40699893-87b38aa6-6409-11e8-8402-76d2855bbd07.png)

**Comment by tfiduccia** [comment]
@NG85 - This has already been fixed in the latest release.  Please update to 2.0.2
