### ISSUE TITLE
Update embedded fluentd to v1.x Kibana and Elasticsearch to 6.2.x

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#13784]
**Rancher versions:**
2.0.2

**Infrastructure Stack versions:**
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

Kubernetes:
Provider **Google GKE**
Version **v1.10.2-gke.1** 

**Steps to Reproduce:**

Install at cluster level an embedded cattle-logging system. 

**Results:**

It spawns versions 0.1.7 of fluentd, 5.6.4 of kibana and 5.6.2 of Elasticsearch. We for example need latest 6.2.x features of elasticsearch and kibana.

Is there any reason you chose to use outdated versions?

**Comment by loganhz** [comment]
Embedded EFK has been removed in 2.1
