### ISSUE TITLE
[CLI] 1.6 rancher cli will still pull from cli.json even if environmental variables are set, breaking some calls

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#13787]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 0.6.9

**Steps to Reproduce:**
use rancher config to generate cli.json file, use environmental variables for other environment. `rancher catalog ls <using environment credentials for a different deployment>` will fail with error forbidden.

**Comment by deniseschannon** [comment]
I have been unable to reproduce.

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
