### ISSUE TITLE
Ability to specify various options while using GKE

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#13789]
Many of the options that are available in google console are missing in Rancher UI.

- Private/Public Cluster

<img width="1302" alt="screen shot 2018-05-30 at 11 56 52 pm" src="https://user-images.githubusercontent.com/19392926/40766828-9b08c7fe-6465-11e8-9cd1-100e278d8773.png">

**Comment by leodotcloud** [comment]
In fact many other options available in Google Console are not available in the Rancher UI.

**Comment by vincent99** [comment]
Some of them were added after 2.0 was mostly done and will probably come later (e.g. multiple node pools), some we're just not going to expose in our UI because they're madness, and most require backend support before I can show them.  But the zone is literally the first node option.

**Comment by nathan-jenan-rancher** [comment]
Here is the (current) list of options available in GKE but not currently supported in our UI
```
node image
automatic node upgrades
automatic node repair
legacy authorization
stackdriver logging
stackdriver monitoring
labels
additional zones
basic authentication
client certificate
autoscaling
preemtible nodes
boot disk type
local ssd disks (per node)
maximum number of nodes per pool
vpc-native
network
master authorized networks
network policy
mainenance window
kubernetes node labels
node taints
kubernetes dashboard
http load balancing
project access
access scopes
```

**Comment by nathan-jenan-rancher** [comment]
Met with @vincent99 and determined that these are some "low hanging fruit" that could be implemented fairly easily.

1. legacy authorization
2. stackdriver logging
3. stackdriver monitoring
4. network policy
5. kubernetes dashboard
6. http load balancing
7. basic authentication
8. client certificate
9. labels
10. mainenance window
11. vpc-native
12. Automatically create secondary ranges
13. Master authorized networks

**Comment by nathan-jenan-rancher** [comment]
The following items:
- basic authentication
- client certificate
- labels
- vpc-native
- Automatically create secondary ranges
- Master authorized networks
- maximum number of nodes per pool

Are being moved to their own issue https://github.com/rancher/rancher/issues/14634 because they require more complex logic than originally thought.

**Comment by nathan-jenan-rancher** [comment]
Merged and ready for backend testing.

**Comment by nathan-jenan-rancher** [comment]
The implementation of these options must be changed to avoid the `disabledX` naming convention. Need to add support to kontainer-engine for bool pointer options.

**Comment by nathan-jenan-rancher** [comment]
Options added for this issue are:
```
enableHorizontalPodAutoscaling
enableHttpLoadBalancing
enableNetworkPolicyConfig
enableStackdriverLogging
enableStackdriverMonitoring
```

They all exist on the `googleKubernetesEngineConfig` off of the cluster resource. If the field is omitted, it should be enabled in the GKE cluster.  It should only be disabled if explicitly set to `false`.

**Comment by soumyalj** [comment]
Tested with v2.0.7-rc2. The following options were  tried in the below cases:
```
enableHttpLoadBalancing
enableHorizontalPodAutoscaling
enableStackdriverLogging
enableStackdriverMonitoring

```
The options set were verified on GCE console and https://developers.google.com/apis-explorer
1. All options were set to false and GKE cluster was created through API
2. All options were set to true and GKE cluster was created through API
When  enableHorizontalPodAutoscaling was set to true, presence of heapster pod was verified

```
> kubectl get pod --all-namespaces
NAMESPACE       NAME                                                READY     STATUS    RESTARTS   AGE
cattle-system   cattle-cluster-agent-5474d4f65-p499p                1/1       Running   0          30m
cattle-system   cattle-node-agent-fms74                             1/1       Running   0          30m
cattle-system   cattle-node-agent-hg4jd                             1/1       Running   0          30m
cattle-system   cattle-node-agent-tqp24                             1/1       Running   0          30m
default         wk1-kq6qw                                           1/1       Running   0          8m
default         wk1-rz4vf                                           1/1       Running   0          8m
default         wk1-sn47f                                           1/1       Running   0          8m
kube-system     event-exporter-v0.2.1-5f5b89fcc8-vsrwj              2/2       Running   0          31m
kube-system     fluentd-gcp-scaler-7c5db745fc-j7rks                 1/1       Running   0          31m
kube-system     fluentd-gcp-v3.0.0-2vm4h                            2/2       Running   0          26m
kube-system     fluentd-gcp-v3.0.0-kcrpv                            2/2       Running   0          27m
kube-system     fluentd-gcp-v3.0.0-pwnrd                            2/2       Running   0          29m
kube-system     heapster-v1.5.3-858d4c8488-6b4tl                    3/3       Running   0          30m
kube-system     kube-dns-788979dc8f-bp4x2                           4/4       Running   0          29m
kube-system     kube-dns-788979dc8f-n2z65                           4/4       Running   0          31m
kube-system     kube-dns-autoscaler-79b4b844b9-xwqbs                1/1       Running   0          31m
kube-system     kube-proxy-gke-c-t5vnx-default-pool-d496aecd-7nmd   1/1       Running   0          31m
kube-system     kube-proxy-gke-c-t5vnx-default-pool-d496aecd-95kz   1/1       Running   0          31m
kube-system     kube-proxy-gke-c-t5vnx-default-pool-d496aecd-jfp9   1/1       Running   0          30m
kube-system     l7-default-backend-5d5b9874d5-rwmcc                 1/1       Running   0          31m
kube-system     metrics-server-v0.2.1-7486f5bd67-ngj5m              2/2       Running   0          29m
>

```

3. If the options are not explicity set, they are enabled by default
