### ISSUE TITLE
Custom Helm Repository without absolute urls doesnt work

### ISSUE THREAD

**Issue by mgolisch** [rancher/rancher#13788]
**Rancher versions: 2.0.2**

**Steps to Reproduce:**
Add helm Repo with index.yaml containing non absolute urls like :  http://charts-broken.mgolisch.eu/index.yaml

**Results:**
When trying to launch a catalog app it just displays a spinning circle and the version dropdown is empty.

**Comment by lagrianitis** [comment]
I can verify if I will a private helm repository, rancher cannot unpack the Readme.md and version (showing a spinning icon), and as a result I cannot deploy the service

**Comment by kirrbr** [comment]
I have the same issue. Any good news on this issue?

**Comment by loganhz** [comment]
Thanks for the report.

Workaround is via https://github.com/helm/chartmuseum/issues/170#issuecomment-425097536
Close in favor of https://github.com/rancher/rancher/issues/14905 and https://github.com/rancher/rancher/issues/13371
