### ISSUE TITLE
drop-down arrow is grey and hard to see

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13780]
**Rancher versions:** 2.0 master 5/29

**Steps to Reproduce:**
1.  log into rancher

**Results:**  The drop-down arrow for the user is light grey and hard to see.
![image](https://user-images.githubusercontent.com/11514927/40738142-9a0aa20a-63f7-11e8-8e30-77d38304bb6a.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/1970

**Comment by tfiduccia** [comment]
Version - 2.0 master 6/25
Verified fixed
