### ISSUE TITLE
Use cluster elasticsearch pod as project logging target

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#13785]
**Rancher versions:**
2.0.2

**Infrastructure Stack versions:**
Google Cloud Kubernetes 1.10 cluster

**Steps to Reproduce:**

We tried to install 6.2.4 version of elasticsearch. It works, and is ready to accept connexions. But we cannot use this elasticsearch endpoint, within our cluster project, as target for Rancher 2 project logging target. 

Service is up and running:
![image](https://user-images.githubusercontent.com/11064123/40753125-981aa1ea-6440-11e8-86ae-a4820865a48d.png)

But rancher can't reach it:

![image](https://user-images.githubusercontent.com/11064123/40752976-f278cb9a-643f-11e8-8e05-0c34aaff85d5.png)

![image](https://user-images.githubusercontent.com/11064123/40753006-1a6424e2-6440-11e8-81b2-19169f0d1d14.png)

![image](https://user-images.githubusercontent.com/11064123/40753023-2cfb696c-6440-11e8-9db3-bfb111acab90.png)

Even pointing the direct cluster ip doesn't work:

![image](https://user-images.githubusercontent.com/11064123/40753222-0c9ec91a-6441-11e8-914e-7578310d4587.png)

Exposing the service through Google Interface, and defining a clusterIP mapping on port 9200 didn't help.

![image](https://user-images.githubusercontent.com/11064123/40753444-2d13f570-6442-11e8-91a8-fabf6c867982.png)

![image](https://user-images.githubusercontent.com/11064123/40753433-19806124-6442-11e8-8fc9-e61778620707.png)

Please note I can easily ping the service from another service using both clusterIp, svc.cluster.local address.

**Comment by soluty** [comment]
same problem，dial  ip timeout， had you solve this？

**Comment by blackholegalaxy** [comment]
no. still no answer from rancher team @superseb @deniseschannon

**Comment by aiwantaozi** [comment]
It throws could not be accessed error because of the ip cluster ip, not reachable from the internet, we will update this part to allow cluster ip. Now, you could try each of below:

1. open elasticsearch as nodeport

2. edit crd and configmap
    2.1 workround to go to rancher server container, and edit the logging related crd
 kubectl edit ```kubectl edit clusterloggings.management.cattle.io``` change the elastic endpoint
    2.2 go the system project configmap, edit configmap cluster-logging or project-logging

**Comment by kingsd041** [comment]
Version: master 2.2 (2/12/19) Image id: 0b7f6d65a156
Confirmed fix.
In the master version, you can use svc name to connect to the elasticsearch, just like `http://efk-elasticsearch.efk.svc.cluster.local:9200`

Thank you for your feedback @blackholegalaxy
