### ISSUE TITLE
[DOC] provide information/documentation regarding rancher cli’s --format output.

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#13781]
It appears not all columns are usable in format output
---
rancher cli version v0.6.8
‘rancher ps –c’ (list of containers) dumps the output with different values, in columns
# rancher ps -c
ID NAME IMAGE STATE HOST IP DOCKER DETAIL

However, same comamnd with the ‘- - format’ option cannot be used against all the column values and works only for a few… and dumps an error
for example:
rancher ps -c --format '{{.ID}},{{.Container.Name}},{{.Container.Image}},{{.Container.State}}'
FATA[0000] template: :1:40: executing "" at <.Container.Image>: can't evaluate field Image in type client.Container
however it works for few variables for ex:
rancher ps -c --format '{{.ID}},{{.Container.Name}},{{.Container.State}}'

The rancher documentation examples are not very clear and does not illustrate the supported options.
Also this example is for lising containers, similarly the listing of hosts/catalog/services also has similar issues.... is there a list of all supported variables that work with the --format option, or a read me that i can refer to?

**Comment by deniseschannon** [comment]
Please use the API docs for each object to find the resource fields which are the fields that can be called using `--format`. this has also been added to the docs:

https://rancher.com/docs/rancher/v1.6/en/cli/commands/#using-the---format-option
