### ISSUE TITLE
Kubernetes  :::: error: couldn't read version from server

### ISSUE THREAD

**Issue by loknath2390** [rancher/rancher#13791]
Hi Team,

While executing the command "kubectl get nodes" im getting below error::

[root@server:~] #kubectl get nodes
error: couldn't read version from server: an error on the server has prevented the request from succeeding

Please help me to close this issue.

**Comment by superseb** [comment]
There are no steps to reproduce this issue, please provide them. Best guess for now to retrieve some cause is using `kubectl -v9 get nodes` to see the actual response.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
