### ISSUE TITLE
pipeline doesn't trigger for pull request option

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13799]
**Rancher versions:** 2.0 master 5/31

**Steps to Reproduce:**
1.  Create a pipeline that will trigger when a new pull request is created
2.  Create a pull request for that repository

**Results:**  Nothing happens.  Sitting at awaiting PR

**Comment by tfiduccia** [comment]
@gitlawr - I did another pull and it worked the second time.  I think the problem is that I was running a bunch of different pipelines one after the other.  So after a few have triggered, it stops working.  Seem others are having problems also with the pipelines triggering randomly.

**Comment by gitlawr** [comment]
I'm not able to reproduce this. Do the pipelines use different repos? Is the pipeline run before missing this trigger? Might be irrelevant but want to get more info here.  Would also be nice if there's response info of this PR event in Github repo webhook settings.

**Comment by gitlawr** [comment]
One possibility is that the webhooks in the repo exceed the limit, the webhook creation is done in controller loop so you should be able to see similar logs in rancher server as follows:
```
{"message":"Validation Failed","errors":[
{"resource":"Hook","code":"custom","message":"The \"push\" event cannot have more than 20 hooks"},
{"resource":"Hook","code":"custom","message":"The \"pull_request\" event cannot have more than 20 hooks"}],
"documentation_url":"https://developer.github.com/v3/repos/hooks/#create-a-hook"}
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
This is related to the pipeline creating two webhooks.  so I'm closing this in favor of #14218
