### ISSUE TITLE
Feature request: backup / restore etcd in the UI like we can do with rke on the CLI

### ISSUE THREAD

**Issue by jomeier** [rancher/rancher#13797]
Hi,

it would be great if we could create a (periodic) snapshot from any etcd cluster in the rancher web UI like we can do it with rke on the command line.

This shouldn't be to complicated because rke currently can do that.

What do you think about that?

Best regards,

Josef

**Comment by superseb** [comment]
Thanks, it is requested here: https://github.com/rancher/rancher/issues/13688
