### ISSUE TITLE
GitHub oAuth - TestAndApply Error server error while authenticating: Post https://github.com/login/oauth/access_token: dial tcp: lookup github.com on 10.43.0.10:53: read udp 10.42.0.2:52737->10.43.0.10:53: i/o timeout

### ISSUE THREAD

**Issue by pjweder** [rancher/rancher#13790]
**Rancher versions: 2.0**

**Infrastructure Stack versions: rke version v0.1.7**

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18.04 LTS - 4.15.0-22-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
ESXi 6.0

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Steps to Reproduce:**
After initial Setup I tried using GitHub Authentication. 

**Results:**
Recieved this error:

TestAndApply Error
server error while authenticating: Post https://github.com/login/oauth/access_token: dial tcp: lookup github.com on 10.43.0.10:53: read udp 10.42.0.2:35952->10.43.0.10:53: i/o timeout

I am seeing that the Rancher Hosts are trying to talk to 10.43.0.10 on our Firewall.

Authentication with GitHub doesn't work.

**Comment by pjweder** [comment]
Yes, that did it! Great! Thank you very much.

**Comment by ahmadalli** [comment]
how about centos 7? @superseb
