### ISSUE TITLE
Load balancers not always created, restarting controller-manager required

### ISSUE THREAD

**Issue by tabossert** [rancher/rancher#13802]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.17
rancher/agent or rancher/rancher-agent: v1.2.10

**Infrastructure Stack versions:**
healthcheck: v0.3.6
ipsec: v0.13.11
network-services: v0.7.20
scheduler: v1.10.0-rancher1-2
kubernetes (if applicable): v1.10.0-rancher1-2

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.13.1, build 092cba3

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Kernel:
4.4.0-1052-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node, External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Deploy Kubernetes service with AWS internal load balancer annotations

apiVersion: v1
kind: Service
metadata:
  name: application-server-service
  labels:
    app: application-server-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::<account_id>:server-certificate/<cert_name>"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-<sg-id>"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8000
  selector:
    app: application-server
  type: LoadBalancer

**Results:**
If controller-manager container has not been restarted recently it sometimes does not create the load balancer in AWS and leaves service in pending state.  If I restart the controller-manager container it immediately sees the new ELB service config and finishes the setup.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
