### ISSUE TITLE
Setting host.api forces http

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#1380]
When running in an SSL setup the rancher setting `host.api` must be set to a space in order for Rancher to use https scheme. If it is set to a domain name or ip address it always defaults to http.

**Comment by cloudnautique** [comment]
More context, the URL returned in the registration URL for servers is http without this setting.

**Comment by cjellick** [comment]
edit: the setting @cloudnautique is referring to is `api.host` not `host.api`

**Comment by cloudnautique** [comment]
sorry about that @cjellick.

**Comment by cjellick** [comment]
@cloudnautique , it looks like you can explicitly set that setting to `https://<your domain>` and it will work.
So, not sure that this is even a bug anymore. Just depends if that behavior is acceptable.

**Comment by cjellick** [comment]
ping @ibuildthecloud: the setting works if you set it as https://foo.rancher.io (vs just foo.rancher.io). Is that a sufficient solution?

**Comment by cloudnautique** [comment]
Ah, well that will work. Just need documentation in the UI. The way it reads now it's just domain or ip. The UI should also allow setting the scheme.

**Comment by cjellick** [comment]
After discussing with @ibuildthecloud, we decided that we ***do not*** want to support putting the protocol in api.host. Working on a more comprehensive fix.

**Comment by cjellick** [comment]
After discussing ***again*** with @ibuildthecloud, we decided the exact opposite of what I said in the previous comment. 

So, ***specifying the protocol in the host.api/Host Registration setting is the canonical way to indicate the protocol that should be used.***

The UI has been updated to indicate this.

**Comment by cjellick** [comment]
@ibuildthecloud This is done. Setting host.api to " " is no longer the right thing to do.
I removed that bit from the documentation. Assigning to you in case you have any scripts or environments that need updated.

**Comment by cloudnautique** [comment]
@sangeethah @will-chan @cjellick I'm good closing this issue. Thanks.
