### ISSUE TITLE
When upgrading Kubernetes with "aws" provider  to v1.10.3 , kubelets fails to start because of the required cluster Id tag not being present.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13807]
Rancher server version  - Fresh install of 1.6.17 with K8s environment.
Upgrade to 1.6.18.
Upgrade Ipsec stack.
Upgrade Kubernetes stack to v1.10.3

kubelets fails to start because of the required cluster Id tag not being present.

Few things we noticed in @soumyalj's setup , when upgrading kubernetes  to v1.10.3:

1. new kubelets were in "stopped" state , but the service got to "upgraded" state.
2. Even when addon-starter service was stuck in "upgrading" state , UI shows option to "Finish Upgrade".
3. Even after the tag -```kubernetes.io/cluster/CLUSTERID=owned ```were added to the host , the kubelets did not recover on it own since they were in stopped state. 

We had to do "Finish Upgrade" which resulted in the getting all the services to get upgraded successfully.

**Comment by deniseschannon** [comment]
This is added as a note in the readme for upgrading to the k8s 1.10 templates as well as in the release notes discussing the latest infrastructure k8s 1.10 version.
