### ISSUE TITLE
Add openLDAP as a auth provider in 2.0

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#13814]

**Comment by cjellick** [comment]
Things I want to call out of testing:
- setting/using the loginDomain
- special characters in names and entered into user searches
- the UserEnabledBitMask bit in the advanced config actually being set (you might need a special setup to test this)

**Comment by sangeethah** [comment]
Tested with latest build from master:

OpenLdap is available as auth provider and able to enable OpenLdap provider successfully.
Issues found when testing this feature are tracked as separate bugs . The few that remain to be addressed - 
https://github.com/rancher/rancher/issues/14080
https://github.com/rancher/rancher/issues/14245
