### ISSUE TITLE
Add FreeIPA as an auth provider to 2.0 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#13815]

**Comment by cjellick** [comment]
Things I want to call out of testing:

setting/using the loginDomain
special characters in names and entered into user searches
the UserEnabledBitMask bit in the advanced config actually being set (you might need a special setup to test this)

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/3

Went through authentication test plan. Found no outstanding issues. 

Also verified that TLS connection works for both self signed certs (passing in CA cert), and recognized CA (without passing in CA cert).
