### ISSUE TITLE
API doesn't support pagination

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#13817]
**Rancher versions:** 2.0.2

**Steps to Reproduce:**
Create/import a cluster with over 1000 nodes 
**Results:**

The UI list of nodes doesn't show more that 1000 nodes. Kubectl and the API UI view show a full list of nodes.

**Comment by vincent99** [comment]
This is not a UI problem, the API doesn't say there's more to load.

The maximum (and default) `limit` is 1000.  If there is more than 1000 records in the response then the API needs to return a `next` link in the `pagination` map so the client knows there are more pages.  It does not ever seem to do so, I don't think it was ever implemented.

e.g. I created 1500 secrets, and the response to `GET /v3/project/<id>/secrets` is:

```javascript
{
  "type": "collection",
  …
  "pagination": {
    "limit": 1000
  },
  …
  "data": [ … 1000 items … ]
}
```

**Comment by vincent99** [comment]
Protip: run in browser console to create a bunch of secrets: 

```javascript
var names = [];
for ( let i = 1 ; i <= 1500 ; i++ ) {
  names.push('s-'+Util.strPad(i,4,'0'));
}

async.eachLimit(names, 5, (name, cb) => {
  s.createRecord({type: 'secret', name: name}).save().finally(cb)
});
```

**Comment by dramich** [comment]
This is available in master

**Comment by adingilloRancher** [comment]
Created 1.5k secrets as expected. API looks fine with changes. However, there is a new issue. When attempting to select the default project a generic error is thrown. There's nothing in the console listed, or in the rancher logs associated to this when seen. 

![screen shot 2018-06-27 at 2 58 35 pm](https://user-images.githubusercontent.com/38012481/42001995-9c9680fa-7a1a-11e8-8e7f-82fef2a77de5.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
