### ISSUE TITLE
Ability to specify extra environment variables for k8s components

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13816]
Add `extra_env` similar to `extra_args`, to supply needed environment variables for k8s components

**Comment by matthax** [comment]
This would be extremely useful, I've been trying to use some new gated features to no avail.

**Comment by smiller393** [comment]
Sorry I made the duplicate, this issue didn't come up in my search. Would love to be able to add flags to each kubelet.

**Comment by bmdepesa** [comment]
rke 0.1.8-rc2

I am able to see environment variables on k8 components specified through RKE

**Comment by lyn716** [comment]
Why Provision ec2 need add `extra_args` for kubelet manually?
If not I could find logs of kubelet: --cloud-config="",
and cause "NoCredentialProviders: no valid providers in chain "
