### ISSUE TITLE
rancer web access error

### ISSUE THREAD

**Issue by leapmotor10214** [rancher/rancher#13812]
**Rancher versions:** 
rancher/server or rancher/rancher: rancher version latest
rancher/agent or rancher/rancher-agent: rancher version latest

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

access rancer ui hapen error

error info :

*%growl.webSocket.connecting.title%*
*%growl.webSocket.connecting.warning%*

**Comment by loganhz** [comment]
Duplicated of https://github.com/rancher/rancher/issues/11961
