### ISSUE TITLE
Invalid Target Settings on Ingress Creation

### ISSUE THREAD

**Issue by tdiscuit** [rancher/rancher#13823]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/rancher:v2.0.2
rancher/agent or rancher/rancher-agent: rancher-rancher-agent:v2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
- Kubelet Version v1.10.1
- Kube Proxy Version v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-122-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
RKE

**Steps to Reproduce:**
1. Go to any project and click on the `Load Balancing` tab. 
2. Click on `Add Ingress`
3. Leave the name blank, but define your target workload and port (in my case, the target workload was `frontend` and port was `80`).
4. Click `Save`

**Results:**
When the L7 ingress is created, a name is auto-generated (in my case, `i-lcvhx`) but the target isn't correct. I see `i-lcvhx.n-qn4rn.<NODE-IP>.xip.io > n-qn4rn:ingress-558cf96ae6a9e643a480f1b3a6dfd981`. If I go to view the ingress settings, I see the target is set to `Choose a Service...` and the port is `42`

If you use `Specify a hostname to use` instead of xip, it still does the same thing. A couple times when I did this, it would keep the correct port setting, but the target workload was never right and I'd have to go and edit the L7 ingress which would then be fine.

**Comment by loganhz** [comment]
This issue has been fixed. Now ingress name is a required field.
