### ISSUE TITLE
Rancher 2.0.1 with CoreOS Image provisioned nodes docker service is disabled

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#13827]
We are using CoreOS to run our cluster and deployed the upgrade operator to manage automated OS updates without causing issues to the cluster. The issuesis when the server is provisioned the docker service is not enabled. This causes issues where when the server is restarted the docker daemon is not started automatically. Should docker-machine or even rancher be enabling the docker service when it is provisioned?

**Comment by deniseschannon** [comment]
CoreOS has automatic docker version upgrades which has been prone to issues with Rancher.

How are you running your Rancher server container? Make sure to include `--restart=unless-stopped` so the container is restarted when Docker is restarted.
