### ISSUE TITLE
Workload Rollback - Selected Revision does not properly reflect older revision. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13820]
Rancher Version: 
Master 6/1/18

Steps:
Create a new cluster.
Create a new deployment workload. 
Upgrade workload. (Change docker image to nginx)
Perform second upgrade. (Change docker image to jenkins) 
Perform third upgrade. (Change docker image to mongodb)
Perform a rollback.
Perform second rollback, select same revision. 

Results: 
Selected revision cycles through other revisions. That revision should rollback to mongoDB image. 

![screen shot 2018-06-01 at 11 15 29 am](https://user-images.githubusercontent.com/38012481/40856541-2024bf4c-658d-11e8-8641-1ac82fc29080.png)

![screen shot 2018-06-01 at 11 13 02 am](https://user-images.githubusercontent.com/38012481/40856446-c8501b86-658c-11e8-85b9-cf8c8dc253b1.png)
![screen shot 2018-06-01 at 11 12 36 am](https://user-images.githubusercontent.com/38012481/40856450-cb39914c-658c-11e8-9910-8f6d3506c5cd.png)

**Comment by kinarashah** [comment]
@loganz https://github.com/rancher/types/blob/master/client/project/v3/zz_generated_deployment_rollback_input.go 

``` curl -u $token --insecure https://localhost:8443/v3/project/local:project-w442z/workloads/deployment:default:test?action=rollback -H "Content-Type: application/json" -X POST -d '{"replicaSetId":"replicaset:default:test-ccb68bf8c"}' ```

**Comment by loganhz** [comment]
Updated the parameter in UI

@kinarashah I think we should use `id` instead of `replicaSetId` for the action parameters.
As we might support other kind resource.

**Comment by kinarashah** [comment]
@loganhz Hm, I think just id could be confusing.. but `revisionId` makes more sense. 
Since we pass the id of the revision we rollback to, and this id is available under `/revisions` for any resource we'd support rollback for. So the value should not be `0`,`1` as before, but id of the replicaset in this case ie `replicaset:default:test-ccb68bf8c`.. does this sound good?

**Comment by loganhz** [comment]
sounds good

**Comment by alena1108** [comment]
@kinarashah @loganhz revisionId is fine. Can we track it separately as it's not a high priority?

**Comment by adingilloRancher** [comment]
Master 6/7/18

Validated UI sends correct revisionID.
