### ISSUE TITLE
validate k8s v1.10.3

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#13825]
[ ] - validate fresh install
[ ] - validate upgrade from k8s v1.10.1 to k8s v1.10.3.

**Comment by soumyalj** [comment]
1. Validated freshinstall of k8s v1.10.3-rancher2-1
2. Upgraded from K8s V1.10-1-rancher1 to v1.10.3-rancher2-1. Upgrade test was successful
3. Upgraded from K8s V1.10-1-rancher2-1 to v1.10.3-rancher2-1. Upgrade test was successful

Automation tests were also run for each case.
