### ISSUE TITLE
Scheduling using service name, users have no way to know they have to type "Project/"

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1382]
v0.26.0-rc1
1.  Create a service in Default project named Service1
2.  Create another service (or a container), and in scheduler 
     - Condition = must 
     - Field = service with the name
     - Value = (type in Service1)

Results:
Could not find placement.   This is because the Value field requires "Default/Service1" to be entered.

Comments:
It is not intuitive that the project name needs to be added and there is no check to help user realize why their service (or container) failed to find placement.

Expected:
Even a error message if no "project/" is found before create would be nice.  Or just place it according to rule if no project name is found.

**Comment by vincent99** [comment]
The UI also lowercases everything in the dropdown and only shows the unique values now.

**Comment by sonchang** [comment]
I've updated the allocator to automatically prepend this now.  Unfortunately, what's currently in master only does this if the service is referencing itself.  There's a pending PR that needs to get merged that does it for any service within the stack.

**Comment by deniseschannon** [comment]
@sonchang what happens when https://github.com/rancher/rancher/issues/1577 is added?

**Comment by sonchang** [comment]
The PR still doesn't preclude people from explicitly entering the stack name + service name for a different stack.  I guess once #1577 is added, I can add additional logic to lookup other services from other stacks and prepend the stack name if found.  And have the current stack as the preference if duplicate service names are found across stacks.

**Comment by deniseschannon** [comment]
Verified Fixed v0.30.0-rc2

The original scenario was tested. Add service with service name without the stack/. Service was started on correct host. Logged 1642 to adapt to cross stack linking.
