### ISSUE TITLE
Can you make ingress-nginx as the loadbalance ?

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#13826]
now the nginx-ingress support tcp/udp services.

can you make a UI to config the configmap ,

or let the ingress-controller as a loadbalance provider?

**Comment by junkiebev** [comment]
IDK if it is of use, but I use a UDP forwarder which I wrote (it uses netcat to establish a persistent tunnel) with a bunch of my stuff (mainly GELF). https://hub.docker.com/r/jeffkolb/udp-proxy/

Just schedule it to deploy on a specific server and you should be all good. I generally link it to a service (in this example, the service is linked as glog-container) and use the target glog-container.rancher.internal

There may be a smarter way to do it but this seems to be pretty effective.

**Comment by superseb** [comment]
merging into https://github.com/rancher/rancher/issues/14744
