### ISSUE TITLE
Adding "catalog refresh" to CLI 2.x

### ISSUE THREAD

**Issue by dorzheh** [rancher/rancher#13834]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: v2.0.2-rc1

Adding "catalog refresh" to the CLI would be very appreciated.
For example in catalog.go:

```
cli.Command{
	Name:        "refresh",
	Usage:       "Refresh a catalog",
	Description: "\nRefresh a catalog",
	ArgsUsage:   "[CATALOG_NAME/CATALOG_ID]",
	Action:      catalogRefresh,
},

```

and 

```
func catalogRefresh(ctx *cli.Context) error {
	if len(ctx.Args()) < 1 {
		return cli.ShowSubcommandHelp(ctx)
	}

	c, err := GetClient(ctx)
	if err != nil {
		return err
	}

	for _, arg := range ctx.Args() {
		resource, err := Lookup(c, arg, "catalog")
		if err != nil {
			return err
		}

		catalog, err := c.ManagementClient.Catalog.ByID(resource.ID)
		if err != nil {
			return err
		}

		err = c.ManagementClient.Catalog.ActionRefresh(catalog)
		if err != nil {
			return err
		}
	}
	return nil
}
```

**Comment by liao-bo** [comment]
which rancher CLI version include the new function? Now my CI/CD must delete and add new chart git to refresh the chart ,when the chart code update.

**Comment by loganhz** [comment]
@gitlawr Please review the PR https://github.com/rancher/cli/pull/210

**Comment by benzman81** [comment]
we now need this feature, too, as we deploy charts for CI/CD. Those do not show up without catalog refresh :-/

**Comment by benzman81** [comment]
just found a workaround installing a helm chart from a local folder. couldn't find anything in documenation about it, but might help someone as long as this is not implemented, too.

`rancher app install ./example example-app`

**Comment by vincent99** [comment]
There's always been a refresh button in the API and UI.  This is just adding calling it to the CLI.

**Comment by jiaqiluo** [comment]
@dawidmalina 
If you are using v2.0.x or v2.1.x, there is no `Refresh` option for the catalog.

This is what I see on rancher:master
<img width="1327" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52153985-4e4a6300-2639-11e9-8ebd-060ff2c53077.png">

**Comment by sneumann** [comment]
Please note a follow-up issue #22717 where the refresh is not available for project scope catalogs.
Yours, Steffen
