### ISSUE TITLE
"Cluster not available" shown in UI if worker node reboots

### ISSUE THREAD

**Issue by jomeier** [rancher/rancher#13830]
Hi,

what is the reason for rancher 2 UI to decide, when a cluster gets unavailable? 

I created a test cluster with rke consisting of three nodes: one with etcd and control, two nodes which are workers. Rancher 2 latest runs on a different server (not on this cluster).

Than I tried to simulate destruction of nodes by rebooting them.

If I reboot the 1st worker, rancher UI is fine and tells me after a few seconds, that this node is not available. 

If I reboot the 2nd worker, rancher UI tells me - in a big wide square - that my cluster is not available. I not even can "launch a kubectl" console in the UI because it's blocked. 

I assumed, that rebooting workers shouldn't make the whole cluster unavailable. 

It's intersting, that during both reboots I can access the cluster's API on a linux shell with kubectl. Only rancher UI acts strange.

Greetz,

Josef

**Comment by etlweather** [comment]
Related: 
 - https://github.com/rancher/rancher/issues/13706
 - https://forums.rancher.com/t/need-for-rancher-ha-impact-if-down
 - https://forums.rancher.com/t/solved-ha-failover-not-working/10408/3

**Comment by jomeier** [comment]
This is a rather big issue because in my opinion it prevents Rancher to be used in production where HA is necessary.

How big are the chances that this one will be fixed soon ?

**Comment by etlweather** [comment]
I definitely second you on that - a worker node being down shouldn't cause any problem on the orchestration system - it's a WORKER node... Something is odd there in the architecture.

**Comment by soumyalj** [comment]
@jomeier : Tested with Rancher 2.0.2. Created a custom cluster with nodes as :
N1: etcd, control
N2, N3 - Worker

Rebooted N2 and then N3. The nodes went to unavailable state but became active after the reboot cycle as expected. The cluster was active and functional.
Also, powered OFF and powered ON the nodes. Did not see the issue mentioned above.

The same test was repeated for a cluster using Digital Ocean Cloud provider. 
The cluster was active after worker node reboots  and Power OFF/ON

Can you please let us know if there are any specific steps you performed?
Can you provide us details on the setup/cluster details?

**Comment by jomeier** [comment]
@soumyalj Thanks a lot for trying that. 

I will try this setup at work (with corporate proxy) and in an environment without the corporate proxy. I saw this effect several times. Maybe I configured something in the wrong way. It would be great, if the fault would be on my side. 

I'll investigate and leave a message here.

**Comment by cjellick** [comment]
@jomeier any update on this? Since, we weren't able to reproduce, if we don't hear back in the next few days, we'll probably try to repro one more time and close if we cant.

**Comment by cjellick** [comment]
@soumyalj or @galal-hussein can you monitor this, see if we hear back, and if not, try to repro again?

**Comment by etlweather** [comment]
I used to have this problem myself. I'll test it again in a day or two. I have the latest 2.0.7 installed.

**Comment by etlweather** [comment]
I don't see this as a problem anymore, at least on 2.0.7. I killed a node that only has worker role and it did not disrupt the cluster, nor Rancher UI. Everything continued working, unlike before.

**Comment by soumyalj** [comment]
Tested with master. Created custom cluster as below:
N1: etcd, control
N2, N3: Worker
Rebooted N2 and N3. Cluster was active and functional

Powered OFF N2/N3. The nodes went to unavailable state, cluster was still active.
Powered ON N2/N3. The nodes went to active state and cluster was active and functional.
