### ISSUE TITLE
Provide method of adding flags to kubelet creation

### ISSUE THREAD

**Issue by smiller393** [rancher/rancher#13835]
**Rancher versions:**
2.0.0

Currently, there doesn't seem to be a way of adding flags on to the creation of each kubelet when using rancher.  There are times when this is necesary to enable certain features of k8. One example is [Mount Propagation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation), as it is a pre-req for getting storageOS up and running. Another use-case would be enabling feature gates to try out k8 features that are in alpha.

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/13816
