### ISSUE TITLE
	Failed to create [rke-etcd-port-listener] container on host [11.239.169.15]: Error response from daemon: -e RequestedIP or --ip not set

### ISSUE THREAD

**Issue by yongbuyanqiDK** [rancher/rancher#13845]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
What OS and Docker version are you using here? And what is the exact error message you are getting?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
