### ISSUE TITLE
boolean answers always have quotes for false and no quotes for true in answers.yaml

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13843]
**Rancher versions:** 2.0 master 6/4

**Steps to Reproduce:**
1.  Create a answers.yaml where it has defaults to "true", true, "false", false
2.  Add helm chart to rancher catalog
3.  Open the catalog app and look at the answers.yaml

**Results:**  true never has quotes and false always has quotes.  Is there a reason for this?
![image](https://user-images.githubusercontent.com/11514927/40951957-32b0e02a-682e-11e8-8266-3b44d0a19bd9.png)

**Comment by deniseschannon** [comment]
@loganhz is this UI or backend/

**Comment by sangeethah** [comment]
Tested with latest build from master:

<img width="1258" alt="screen shot 2018-06-12 at 2 41 57 pm" src="https://user-images.githubusercontent.com/4266958/41318894-cd848af4-6e4e-11e8-894b-eb53d42b4ed0.png">

<img width="1292" alt="screen shot 2018-06-12 at 2 42 06 pm" src="https://user-images.githubusercontent.com/4266958/41318906-d5b40f92-6e4e-11e8-8dfa-1899250f0386.png">

There is no quotes for True/False.
