### ISSUE TITLE
Trying to contribute to Rancher 2: documentation about build process and onboarding needed

### ISSUE THREAD

**Issue by jomeier** [rancher/rancher#13841]
Hi,

I'm trying to better understand how Rancher works internally. My approach is to enhance the Rancher 2 API to achieve that and check, if I find my newly generated API endpoint in the web browser. I tried to add something to schema.go as described in the Rancher architecture document (Appendix A).

I downloaded the go package rancher/types locally and made modifications to it . I installed it with

```go install -a```

And recompiled the rancher/rancher project. But I don't see my API endpoint in the web browser.

It seems that the compile process happens completely in a docker container. How do I get the build process to take my modified rancher/types package into account which was created by me outside of the docker container ?

This problem leads me to a general question: Do you have internal documentation about Rancher's build process you could share with us? I find it rather hard to get into the build process and code. I'm pretty sure this would give the project a boost because more people from the community could help in fixing bugs.

What do you think about that?

**Comment by cjellick** [comment]
unofficial documentation. no official support. your mileage may vary...but here's an extremely brief start:
https://github.com/rancher/rancher/wiki/Rancher-2.0---Adding-new-CRDs
https://github.com/rancher/rancher/wiki/Running-and-debugging-Rancher-2.0-from-an-IDE

What that first article doesn't say is that after making modifications to the types or schema fils in rancher/types, you need to run `go generate` to regenerate the code. Then, you have to get those changes into the vendored directory in rancher/rancher (one way or another).

See if that gets you any further and then circle back.

**Comment by jomeier** [comment]
Yes. Documentation about the build process could be enhanced ;-) 

Simply copying the folder rancher/types into rancher/rancher/vendor/github.com/rancher/types doesn't seem to work. I'm getting lot's of errors compiling rancher/rancher. 

How do I get the modified rancher/types into rancher/rancher/vendor the go way ?

**Comment by jomeier** [comment]
I used

govendor update github.com/rancher/types +external

to update rancher/rancher/vendor/github.com/rancher/types

Now I see my newly created endpoint in the browser. Thats great.

What can I do with that now? As far as I understood this mechanisms are used to control kubernetes clusters by calling their API. To get life behind my new rancher API endpoint I must define CRD resources in kubernetes. The Rancher API acts as a wrapper where I get automatically created code stubs with hooks after

go generate 

which are triggered by kubernetes events. I can fill this hooks with my custom code to perform tasks on clusters.

Is this correct?

**Comment by jomeier** [comment]
Another question: is my assumption correct, that the generated code stubs in the rancher/types project serve as an adapter from the rancher API to the Kubernetes API and that this adapter code is not intended to be modified by us?

**Comment by cjellick** [comment]
There are several things you get from the generated code:
- friendly structs and controllers for integrating your CRD into k8s. By this I mean that the vanilla k8s client code only gives you map[string]interface for CRDs and we put a little bit of a framework around writing controllers
- Rancher API client code so that if you expose your CRD through the rancher api, you have a go client for interacting with it.

None of the generated code should be modified.

I realize you are really getting information piecemeal and are probably stumbling through. Hopefully, sometime soon I or someone else can do a blog, webcast, or even just rough documentation explaining how to do what you're attempting to end-to-end.

Follow up question: are you basically planning to patch Rancher with the changes for your CRD(s)? I'd just like to understand the usecase a bit better to see if longer term there is anything we can do to make this better.

**Comment by jomeier** [comment]
Von meinem iPhone gesendet

**Comment by jomeier** [comment]
Thx for your answers. I’d like to better understand how rancher works so we at least could fix some bugs or enhance it on our own and assist in getting it suitable for our company.

For example: ar

You could get far more helping hands for this project if the most basic build process steps and architecures would be documented a little bit more.

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/13933
