### ISSUE TITLE
Unable to communicate between hosts in windows overlay

### ISSUE THREAD

**Issue by warroyo** [rancher/rancher#13840]
**Rancher versions:**
rancher server `1.6.17`

I am running windows server 2016 with docker `17.06.2-ee-12`

I have two hosts registered in a windows environment, I followed the steps exactly form the documentation. the hosts connect as expected however the overlay only works on individual hosts, not between the hosts. below is a screenshot of what the environment hosts look like.

![image](https://user-images.githubusercontent.com/616621/40943574-da4bb30c-680e-11e8-9c86-4c33baae2c43.png)

for example I cannot ping between the `testing-1` container and `testing-2` using the 192.168.x.x addresses or the dns names. communication between the hosts is open and windows firewall is off. both hosts have the agent and per-host-subnet service running. I have gone through the troubleshooting steps in the docs and everything looks correct.

here is what my `ipconfig` looks like:
host 1:
![image](https://user-images.githubusercontent.com/616621/40943673-380b0b32-680f-11e8-97d3-b7c061715720.png)

host2: 
![image](https://user-images.githubusercontent.com/616621/40943688-5254acfa-680f-11e8-9739-d685aef97e6e.png)

also here is the route table from inside of one of the containers. I see that it is routing requests form `192.168.2.0` to `10.4.24.174` which is the other host so this seems correct.

![image](https://user-images.githubusercontent.com/616621/40944979-0e06f896-6814-11e8-9a04-4832d7fd940c.png)

Is there something else I need to be configuring?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
