### ISSUE TITLE
vSphere integration does not set VM IP

### ISSUE THREAD

**Issue by frenchtoasters** [rancher/rancher#13855]
**Rancher versions:**
rancher/rancher:v2.0.2

**Docker version: 17.03.2-ce**

**Operating system and kernel: 4.4.74-boot2docker**

**Type/provider of hosts: vSphere**

**Setup details: single node**

**Environment Template: Kubernetes**

**Steps to Reproduce:**
1. Normal vSphere deployment up to adding node
2. Create template for node and set `Configuration Parameters used for guestinfo` as so
guestinfo.ipAddress => 172.2.0.5
3. Select all in one node

**Results:**
The VM is deployed as expected however the additional guestinfo configuration does not run. The gui says that it is reconfiguring the VM in both Rancher and vSphere. However after the VM is up the ipaddress is never set on any interface.

**Comment by superseb** [comment]
I've seen this work using:

```
guestinfo.interface.0.ip.0.address
guestinfo.interface.0.name
guestinfo.interface.0.route.0.gateway
```

Can you try this?

**Comment by frenchtoasters** [comment]
I just tried that and still got the same results. I did notice thought that the IPv6 address shows up for the eth0 adapter.

Here are the settings im using 
```
guestinfo.interface.0.ip.0.address => 172.1.5.215
guestinfo.interface.0.name => eth0
guestinfo.interface.0.route.0.gateway => 172.1.5.1
```

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15817
