### ISSUE TITLE
Make EKS GA work

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13857]
GA Today: https://aws.amazon.com/blogs/aws/amazon-eks-now-generally-available/

Go SDK: https://github.com/aws/aws-sdk-go/tree/master/service/eks

Currently, the following error is shown when creating EKS:

```
Error creating stack: error creating master: ValidationError: S3 error: The specified key does not exist. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html status code: 400, request id: X
--
```

**Comment by weslleycamilo** [comment]
I just got the same issue and I've been troubleshooting since then.

**Comment by izuolan** [comment]
A temporary solution: First create a cluster in the EKS console, then open Rancher dashboard add cluster, select import cluster, now you can manage the EKS cluster in Rancher.

This does not solve the problem. Please keep your attention.

**Comment by rv-cdiaz** [comment]
Having the same issue with rancher 2.02. Error creating stack: error creating master: ValidationError: S3 error: The specified key does not exist. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html status code: 400

**Comment by Lazy-Y** [comment]
I have the same issue. No idea what is going on... It is the same on 2.0.0.

**Comment by deniseschannon** [comment]
The formation templates that we were relying on for when we started with Amazon eks beta support were removed when eks went GA, we are updating to use the formation templates available as of Amazon eks GA.

**Comment by Lazy-Y** [comment]
@deniseschannon do you know when the update will be available? Thanks

**Comment by soumyalj** [comment]
Tested with master. Created EKS cluster successfully. Workload creation also succeeded.

**Comment by Lazy-Y** [comment]
@soumyalj which version of rancher did you use? I keep getting this error.
`Error creating stack: error creating master: ValidationError: S3 error: The specified key does not exist. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html status code: 400, request id: X
`

**Comment by derekssmith** [comment]
I am getting this error also, please let me know if there is a solution.

**Comment by soumyalj** [comment]
@Lazy-Y : This was tested on master build.

**Comment by derekssmith** [comment]
@soumyalj Is master different than what is in the v2.0.2 docker image?  I just installed this a few days ago, and can't get past this error.  

![image](https://user-images.githubusercontent.com/14862993/41611432-cbad3a0e-73bd-11e8-93cf-17d9058f6d6b.png)

**Comment by superseb** [comment]
`master` is a development build used for internal testing. This issue is marked for milestone v2.0.3, which is the next release.
