### ISSUE TITLE
[ feature] add Target Groups for AWS

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#13859]
it would be incredibly useful to have nodes on aws automatically added to Target Groups for use with ALB and NLB, perhaps add it to the node templates?

**Comment by deniseschannon** [comment]
We provision the nodes through docker-machine, but they don't have this ability.

**Comment by gregkeys** [comment]
@deniseschannon so are you saying it's impossible?

**Comment by vincent99** [comment]
Nothing is "impossible", but the docker-machine driver does not have that functionality and we do not intend to add it.

You do not _have_ to use the node drivers, you can e.g. make a custom cluster and ASG that ties to a target group and runs the custom add node command in its cloud-init.
