### ISSUE TITLE
Container logs returning Invalid Date if Console is set to Interactive & TTY

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1385]
v0.26.0-rc1
Steps:
1.  Create a container, image = hello-world and make sure console is set to Interactive & TTY
2.  View logs of container

Results:
7/2/2015 3:34:56 PM  Hello from Docker.
Invalid Date Invalid Date  This message shows that your installation appears to be working correctly.
Invalid Date Invalid Date
Invalid Date Invalid Date  To generate this message, Docker took the following steps:
.... (etc)

Expected:
7/2/2015 3:38:24 PM  Hello from Docker.
7/2/2015 3:38:24 PM  This message shows that your installation appears to be working correctly.
7/2/2015 3:38:24 PM
7/2/2015 3:38:24 PM  To generate this message, Docker took the following steps:

**Comment by vincent99** [comment]
@cjellick Are you doing any processing of the data in the host proxy for log messages?  I'm pretty sure this "used to work".  Only the first frame I'm getting now contains the prefix that tells me which stream it's for:

![image](https://cloud.githubusercontent.com/assets/753917/8535939/7d7dbe0a-23ff-11e5-9f62-57aafecff30e.png)

(I end up pulling off "20" from the date as the prefix, and trying to parse "15-07-06" as a date...)

**Comment by ebuildy** [comment]
Hello, 

I am still getting this "Invalid Date", version 0.35:

![Rancher invalide date error]
(https://beemapp.s3-eu-west-1.amazonaws.com/88681eac-a7f3-4c6b-9ce7-887fac7f247f.jpg)

**Comment by sangeethah** [comment]
Tested with build from master - Oct 8

Able to see valid date in container logs for container launched with "hello-world" image.

<img width="1097" alt="screen shot 2015-10-09 at 10 21 09 am" src="https://cloud.githubusercontent.com/assets/4266958/10400773/a3b89738-6e6f-11e5-8884-fbd646e5d0d8.png">

**Comment by ebuildy** [comment]
I am still getting "Invalid Date" ;-(

Rancher	v0.40.0
Cattle	v0.97.0
User Interface	v0.54.0
Rancher Compose	beta/latest

Images example:

- prom/prometheus

**Comment by deniseschannon** [comment]
This will be in the next release.
