### ISSUE TITLE
Launched catalog apps UI overlap when many exposed endpoints

### ISSUE THREAD

**Issue by afgane** [rancher/rancher#13863]
**Rancher versions:**
rancher/rancher: 2.0.2
rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
docker info
Containers: 91
 Running: 41
 Paused: 0
 Stopped: 50
Images: 27
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 415
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-124-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.67 GiB
Name: cc2
ID: UBFP:7ZX3:6IQ7:23EU:JSTR:KCF5:PCH3:HVH7:4Y5R:F45B:ZAGO:GIOV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# uname -r
4.4.0-124-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
K8S

**Steps to Reproduce:**
Deploy a catalog app with many endpoints.

**Results:**
![image](https://user-images.githubusercontent.com/338642/41015734-929fdc52-6919-11e8-8ba9-aaf458479b2d.png)

Doesn't look like that layout overlap is expected.

**Comment by loganhz** [comment]
Thanks @afgane 
This is duplicated with https://github.com/rancher/rancher/issues/13694
It's fixed in our dev version now. It will be out in `2.0.3`
