### ISSUE TITLE
Cannot add  Persistent Volume with Local Node Disk plugin

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13864]
rancher/rancher:master 06/06

Steps to reproduce:

1. Create a PV
2. Select `Local Node Disk`
3. Input `path` and click `save`

![image](https://user-images.githubusercontent.com/21168270/41015917-f5867a0a-697e-11e8-97f3-784b8ab097a9.png)

**Comment by loganhz** [comment]
I guess we need to add the `nodeAffinity` for PV in schema. https://kubernetes.io/docs/concepts/storage/volumes/#local

**Comment by jvthanh** [comment]
which's rancher version will be resolve this issues?

**Comment by cgebe** [comment]
Also encountered this issue - its not possible to create a PV on local storage via the web interface.

**Comment by StrongMonkey** [comment]
@loganhz NodeAffinity schema is there, it is just a little bit complicated to use :)
try posting:
```
{
	"type": "persistentVolume",
	"accessModes": ["ReadWriteOnce"],
	"name": "local",
	"local": {
		"type": "localVolumeSource",
		"path": "/var"
	},
	"capacity": {
		"storage": "10Gi"
	},
	"nodeAffinity": {
		"required": [{
			"matchExpressions": [{
				"key": "kubernetes.io/hostname",
				"values": "ubuntu1",
				"operator": "In"
			}]
		}]
	}
}
```
That should give you a local volume.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Verified fixed

**Comment by pmc-sstaehle** [comment]
Unfortunately I'm experiecing this error on a clean install on a custom vServer on v2.0.8.
Cannot confirm the fixing of the error...

**Steps to Reproduce:**
Rancher->Storage->Add Persistent Volume:

Name: rancher-volume
Capacity: 10 GiB
Volume Plugin: Local Node Disk
Path: /opt/rancher-volume
Access Modes: Single Node Read-Write

**Result:**
Validation failed in API: PersistentVolume "mytestvolume1" is invalid: metadata.annotations: Required value: Local volume requires node affinity


Can you please addvice me what to do?

**Comment by loganhz** [comment]
@pmc-sstaehle  Please try the following steps. It works for me.

1. Edit the node to add a label such as node=my-node.

![image](https://user-images.githubusercontent.com/21168270/45402330-b77c0a80-b687-11e8-8ce1-15d08820e0c6.png)

2. Create a local node disk pv and add node affinity in `Customize` section.

![image](https://user-images.githubusercontent.com/21168270/45402297-8a2f5c80-b687-11e8-9da8-7a2a08069f6b.png)

**Comment by pmc-sstaehle** [comment]
Thank you @loganhz,
it's working for me now!

**Comment by razcakappa** [comment]
@loganhz I tried like you posted but no luck. Do I need to restart the node or something after setting annotation parameters?
I'm having the same issue which @pmc-sstaehle has. Using V2.08 
However still the problem exists. Any suggestions?

**Comment by loganhz** [comment]
@razcakappa No, I don't need to restart the node.

Did you set the label to your node?
Can you provide the screenshot of `pod list` section in workload detail page, please?
And the screenshot of `events` section in the pod detail page.
