### ISSUE TITLE
Can not create iscsi PV in UI

### ISSUE THREAD

**Issue by alec-lu** [rancher/rancher#13865]
*Describe your issue here*

Name处填入 iqn.2005-10.acc.freenas

保存的时候提示如下
"Name"包含an invalid character:.

我尝试多种组合，都有这个提示，请问该如何解决呢

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`authenticated.project.config-maps.index`|

**Comment by loganhz** [comment]
```
      targetPortal: 10.0.2.15:3260
      portals: ['10.0.2.16:3260', '10.0.2.17:3260']
      iqn: iqn.2001-04.com.example:storage.kube.sys1.xyz
      lun: 0
      fsType: ext4
      readOnly: true
```
Please read

https://github.com/kubernetes/examples/blob/master/staging/volumes/iscsi

If it says initiatorName is invalid. You need to wait for our next release.  I have fixed it in UI side. 
https://github.com/rancher/ui/pull/1949/commits/a7723b3a664b67c4c4fe9cb49c31d92124c54fba

Please describe your issue in English next time. Thanks.
