### ISSUE TITLE
Rancher 2.0 GUI not reporting CPU or Memory Usage on nodes

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#13860]
Rancher versions:
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

Infrastructure Stack versions:
kubernetes (if applicable): 1.10.1

Docker version: (docker version,docker info preferred)
Server Version: 17.03.2-ce

Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Linux version 4.14.32-rancher2 (gcc version 7.3.0 (GCC)) #1 SMP Fri May 11 11:30:31 UTC 2018

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
AWS

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
HA rancher 3 nodes using m5.xlarge ec2 instances

Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
Kubernetes

Steps to Reproduce:
setup cluster, deploy a bunch of services

Results:
Rancher Stats are not accurate, only showing 9% cpu usage, and 0% memory usage for 243 pods
![rancher2_cpu](https://user-images.githubusercontent.com/3282427/41004747-d56958be-68cf-11e8-9e38-ba14af702e14.png)

When looking at aws cpu metrics and top it clearly shows different metrics
![rancher_top_cpu](https://user-images.githubusercontent.com/3282427/41004745-d538990e-68cf-11e8-9baf-57ade1b40a37.png)
![rancher_aws_cpu](https://user-images.githubusercontent.com/3282427/41004746-d54f9910-68cf-11e8-85b9-83958401599c.png)

**Comment by alexey-kruchenok** [comment]
Expiriencing same issue, and thats lead to orchestration problem as one node is overload while other is underload

**Comment by matthax** [comment]
The dashboard is an average across the entire cluster.

**Comment by tkuther** [comment]
the next ones who fell for it...

#13583

**Comment by Shaggy84675** [comment]
I have this problem too. There is only a few pods, but still it shows same cpu and memory values. I tried restart host, cluster, recreate, nothing worked.

![obrazek](https://user-images.githubusercontent.com/1374803/41497212-2b2e7a84-7151-11e8-821d-e318d1f08a64.png)

**Comment by matthewhartstonge** [comment]
The values reported are the Kubernetes "resource requests" not the expected 'combined live values' across nodes from within the cluster.

See: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container

**Comment by marcominetti** [comment]
Is anyone delving into this at Rancher?

**Comment by superseb** [comment]
This is being changed to show `reserved` instead of `used`. Is there an issue with showing the reserved metrics?

**Comment by marcominetti** [comment]
Got it... have you any feature planned to show live usage without deploying something like prometheus/grapana?

**Comment by loganhz** [comment]
UI has been changed to `reserved`. It will be in `v2.0.7`. 

For the live usage feature, it will be tracked in https://github.com/rancher/rancher/issues/14230.

![image](https://user-images.githubusercontent.com/21168270/43384076-804cc184-940f-11e8-876b-3a1741bea3f0.png)
