### ISSUE TITLE
[Rancher CLI] - FATA[0004] Failed to get rancher catalog client http://dev.rancher.test.net/v1/projects/1a3213 Bad response statusCode [404]. Status [404 Not Found]

### ISSUE THREAD

**Issue by royerhq** [rancher/rancher#13877]
**Rancher versions:**
rancher/server: 1.6.17 and 1.6.15

**Rancher CLI versions:**
v0.6.4 (testing and working)
v0.6.8 (not working)
v0.6.9 (not working)

**Steps to Reproduce:**
1) Create a Rancher Environment
2) Create an Environment API Key
3) Configure Rancher CLI to use the Environment API End points along with the corresponding key:pair
4) run  either command  
`rancher catalog ls` or `rancher stacks ls`  (this commands fails for all its options)

**Results:**
```
FATA[0005] Failed to get rancher catalog client http://dev.rancher.test.net/v1/projects/1a3213 Bad response statusCode [404]. Status [404 Not Found]. Body: [404 page not found
] from [http://dev.rancher.test.net/v1-catalog/projects/1a3213] 
```

**Expected Behavior**
Depending on the options used the commands should either return a list, deploy catalog or interact with a stack

**Work Around**
Change the Rancher URL from the Environment API endpoint to an Account API endpoint
and then runt he following command like this 
`rancher catalog install library:route53:v0.6.0-rancher1 --name route53`

NOTE
That the syntax located [here ](https://rancher.com/docs/rancher/v1.6/en/cli/commands/#rancher-catalog-reference) 
will not work with my work around

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
