### ISSUE TITLE
Rancher docker container How to choose a network policy?

### ISSUE THREAD

**Issue by yinjingjiu** [rancher/rancher#13871]
I created three network policy,want a container to use one of them. how to deal with?

**Comment by yinjingjiu** [comment]
how to deal with? id=1n11
{
"id": "1n11",
"type": "network",
"links": {
"self": "…/v2-beta/projects/1a5/networks/1n11",
"account": "…/v2-beta/projects/1a5/networks/1n11/account",
"ipAddresses": "…/v2-beta/projects/1a5/networks/1n11/ipaddresses",
"networkDriver": "…/v2-beta/projects/1a5/networks/1n11/networkdriver",
"subnets": "…/v2-beta/projects/1a5/networks/1n11/subnets"
},
"actions": {
"update": "…/v2-beta/projects/1a5/networks/1n11/?action=update",
"deactivate": "…/v2-beta/projects/1a5/networks/1n11/?action=deactivate"
},
"baseType": "network",
"name": "network-policy-deny",
"state": "active",
"accountId": "1a5",
"created": "2018-06-06T09:12:26Z",
"createdTS": 1528276346000,
"defaultPolicyAction": "deny",
"description": "network policy deny",
"dns": [ ],
"dnsSearch": [ ],
"hostPorts": false,
"kind": "network",
"metadata": {
"cniConfig": {
"10-rancher.conf": {
"bridge": "docker0",
"bridgeSubnet": "10.42.0.0/16",
"hairpinMode": false,
"hostNat": true,
"ipam": {
"isDebugLevel": "false",
"logToFile": "/var/log/rancher-cni.log",
"subnetPrefixSize": "/16",
"type": "rancher-cni-ipam"
},
"isDebugLevel": "false",
"isDefaultGateway": true,
"linkMTUOverhead": 98,
"logToFile": "/var/log/rancher-cni.log",
"mtu": 1500,
"name": "rancher-cni-network",
"promiscMode": true,
"type": "rancher-bridge"
}
}
},
"networkDriverId": "1nd1",
"policy": [ ],
"removed": null,
"subnets": [ ],
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"uuid": "7dbda6b8-cb02-423c-884f-67fa7daf7634"
}

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
