### ISSUE TITLE
General workloads are being scheduled on nodes explicitly tagged for etcd and control only

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#13874]
nodes that are explicitly tagged as "etcd" and "control" are being sent workload as if they were also "worker nodes"; how do you specify "only" so that no general purpose workloads are sent to those explicitly tagges as "etcd" and/or "control"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by cjellick** [comment]
This is a known bug and is actively being addressed
https://github.com/rancher/rancher/issues/13524

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/issues/13524
