### ISSUE TITLE
multiple private registry issue

### ISSUE THREAD

**Issue by alexey-kruchenok** [rancher/rancher#13872]
**Rancher versions:**
rancher/rancher 2.0.2

**Docker version: (`docker version`,`docker info` preferred)**
17.3.2
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos 7.5
**Type/provider of hosts: **
Bare-metal
**Setup details: ()**
single node rancher
**Steps to Reproduce:**
We have two private registry, lets call it gitlab-external and gitlab-internal, 
When you start deploying service with image from one repo, than clone/update service 
ImagePullSecrets not changed, even if you new image lies in different registry

imagePullSecrets:
  - name: gitlab-external -- this keep point to registry used when workload created, need to check which registry/secret need to be used after each upgrade if image is changed

**Results:**

**Comment by moelsayed** [comment]
Confirmed fixed using the latest master:
- Created a new cluster
- Created 2 private registry resources in the default name project.
- Created a new workload with an image from private registry 1.
   - Cloned the workload and changed the image to private registry 2.
   - Updated the original workload and changed the image to private registry 2.

In both cases the workload was updated and deployed successfully. ImagePull secret was updated accordingly.
