### ISSUE TITLE
Cluster not available, but curl works from container

### ISSUE THREAD

**Issue by smalenfant** [rancher/rancher#13875]
My cluster shows "not available". etcd was complaining about time sync so I resolved that.

Then, it still showed unavailable. Can't figure out why rancher complains about the server not being reachable.

```
E0606 17:38:26.868733       1 generic_controller.go:204] ClusterController c-qvjq6 [cluster-agent-controller] failed with : could not contact server: Get https://10.22.250.162:6443/version: waiting for cluster agent to connect
```

```
$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
96f44ed082ce        rancher/rancher:v2.0.2   "rancher --http-li..."   17 hours ago        Up 7 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   trusting_meninsky
$ docker exec -it trusting_meninsky bash
# curl https://10.22.250.162:6443/version -k
{
  "major": "1",
  "minor": "10",
  "gitVersion": "v1.10.1",
  "gitCommit": "d4ab47518836c750f9949b9e0d387f20fb92260b",
  "gitTreeState": "clean",
  "buildDate": "2018-04-12T14:14:26Z",
  "goVersion": "go1.9.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 1.1.1 and 1.3.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Just happened, unsure I can reproduce

**Results:**
Cluster Not Available.

**Comment by JasonvanBrackel** [comment]
@smalenfant What is the host name of the Rancher Server.  That is if you Navigate to Global > Settings > server-url.  What is the value? Is that value resolvable from within the Kubernetes cluster being managed?  If it is not the cluster-agent will be unable to connect to the rancher server.  This can also occur if 443 is not available outbound from the cluster-agent to the Rancher Server

**Comment by JasonvanBrackel** [comment]
Issue turned out to be certificates chain of trust issue.

**Comment by smalenfant** [comment]
Was using a wildcard certificate, although was provisioned properly, openssl check failed.

I got a normal certificate and cluster got restored. @JasonvanBrackel should we re-open and change the title?

**Comment by smalenfant** [comment]
Some details regarding the wildcard certificate. Also, part of this, any intermediate certificate doesn't seem to be sent back as well. Might be multiple issues.

```
$ openssl s_client -servername master.rancher.cdn1.coxlab.net -connect master.rancher.cdn1.coxlab.net:443
CONNECTED(00000003)
depth=0 CN = *.rancher.cdn1.coxlab.net
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.rancher.cdn1.coxlab.net
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=*.rancher.cdn1.coxlab.net
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
```

**Comment by wernergillmer** [comment]
Seem to be having the same problem. Was working fine for weeks, and it just broke this morning. We cannot unfortunately change our wildcard certificate as easily as it's issued by our security department.

There seems to be a bit of a error loop. Our cattle server complains: 

```
018/08/20 09:06:59 [ERROR] CatalogController gitlab [catalog] failed with : failed to update templates. Multiple error occurred: [etcdserver: request is too large]
2018/08/20 09:10:45 [ERROR] ClusterController c-zslh4 [cluster-agent-controller] failed with : could not contact server: Get https://10.165.210.245:6443/version?timeout=30s: waiting for cluster agent to connect
2018/08/20 09:10:46 [ERROR] ClusterController c-qfjnh [cluster-agent-controller] failed with : could not contact server: Get https://10.165.211.15:6443/version?timeout=30s: waiting for cluster agent to connect
2018/08/20 09:10:46 [ERROR] ClusterController c-xx8zq [cluster-agent-controller] failed with : could not contact server: Get https://10.165.214.82:6443/version?timeout=30s: waiting for cluster agent to connect
2018/08/20 09:10:46 [ERROR] ClusterController c-9l9dg [cluster-agent-controller] failed with : could not contact server: Get https://10.165.210.247:6443/version?timeout=30s: waiting for cluster agent to connect
2018/08/20 09:10:46 [ERROR] ClusterController c-l5zmr [cluster-agent-controller] failed with : could not contact server: Get https://10.165.211.11:6443/version?timeout=30s: waiting for cluster agent to connect
2018/08/20 09:10:46 [ERROR] ClusterController c-rx2wg [cluster-agent-controller] failed with : could not contact server: Get https://10.165.211.22:6443/version?timeout=30s: waiting for cluster agent to connect
2018/08/20 09:10:46 [ERROR] ClusterController c-v7rm2 [cluster-agent-controller] failed with : could not contact server: Get https://10.165.214.62:6443/version?timeout=30s: waiting for cluster agent to connect
2018/08/20 09:10:46 [ERROR] ClusterController c-t7s5g [cluster-agent-controller] failed with : could not contact server: Get https://10.165.214.40:6443/version?timeout=30s: waiting for cluster agent to connect
```

however they are up, I can reach them with curl but have to use --insecure flag. Looking however at the cattle agents, they are stop and starting the whole time as, they cannot reach the cattle server :-/

**Comment by JasonvanBrackel** [comment]
@superseb thoughts here?  New issue or do we reopen this?

**Comment by superseb** [comment]
As it's pretty old, file a new issue with the template filled out and logs from the k8s components and especially rancher agent (why can't they connect)
