### ISSUE TITLE
After authenticating, screen flashes 4 times

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1387]
v0.26.0-rc1
Steps:
1. Go to Access Control
2. Authenticate with GitHub

Results:
another window pops up
then the main screen flashes an additional 3 times

**Comment by vincent99** [comment]
It's no longer a popular, but I think there's still time much flashing after turning auto on.

**Comment by tfiduccia** [comment]
No more flashing, just one wait screen (which is acceptable).  Closing
