### ISSUE TITLE
KubeDNS dns hostname resolution does not work in ingress nginx (load balancer)

### ISSUE THREAD

**Issue by btaens** [rancher/rancher#13876]
**Rancher versions:**
rancher/rancher:2.0.2
rancher/rancher-agent:2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec: -
network-services: -
scheduler: -
kubernetes: 1.10.1

**Docker version:**
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.2
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:25 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Operating system and kernel:**
4.14.32-rancher2

**Type/provider of hosts:**
Bare-metal

**Setup details:**
Single node, internal DB

**Environment Template:**
Kubernetes

**Steps to Reproduce:**
1. Create a simple pod with no authentication, say a static html page.
    Give it a ClusterIP service (at port 80). Name it: no-auth-service in namespace no-auth-ns
1. Create a second pod with basic authentication.
    Also give it a ClusterIP service (at port 80). Name it: auth-service in namespace auth-ns
1. Create a load balancer pointing to the first.
1. Give the load balancer the following annotation: 
    nginx.ingress.kubernetes.io/auth-url=http://auth-service.auth-ns.svc.cluster.local

Upon navigating to the hostname of our load balancer, the basic authentication of our auth-service
should pop up, and after authenticating, the static page of our first service should load.
**Results:**
We are greeted with a 503 service temporarily unavailable error, as ingress nginx could not find the authentication endpoint, as it does not receive DNS resolution from KubeDNS.

ingress-nginx is also the only service without the environment variables pointing to our Kubernetes services. It's nameserver seems to be pointing at the network router, instead of KubeDNS.

The example does work perfectly if the service's IP address endpoint is provided to the annotation, demonstrating that the functionality itself works.

In the container (nginx ingress controller) however, dns hostname resolution doesn't work at all, ping doesn't recognize any of the hostnames. In every other container, it works perfectly.

This makes things problematic, as in order to point at a service currently in annotations and such is to provide the service's endpoint IP, which may change.

**Comment by nabeelio** [comment]
I'm getting the same error, heh, I'm also using the same service name. Though I'm getting a 502 back.

```
[error] 50#50: *706 auth-svc could not be resolved (2: Server failure), client: 70.114.197.89, server: _, request: "GET /config/api/v1/apps HTTP/1.1", subrequest: "/_external-auth-L2NvbmZpZw", host: "10.240.1.10"
[error] 50#50: *706 auth request unexpected status: 502 while sending to client, client: 70.114.197.89, server: _, request: "GET /config/api/v1/apps HTTP/1.1", host: "10.240.1.10"
```

**Comment by nabeelio** [comment]
FYI I filed a report above, using the full FQDN should work - I tested that out, and my service is in the default namespace, and it appears to have worked.

**Comment by digitalassembly** [comment]
I'm having the same issue, tried to use in one my services to point to another internal service and NGINX logs shows that it can't resolve the name. 

type: ExternalName
  externalName: k8smain-pentaho.k8smain.svc.cluster.local

**Comment by digitalassembly** [comment]
For my specific case using External Names, I was able to get it working by updating my service definition to “Alias of another DNS record’s value” and point it to my existing service which seems to tell NGINX the cluster IP instead the FQDN

<img width="928" alt="screen shot 2019-02-19 at 3 32 59 pm" src="https://user-images.githubusercontent.com/11076880/52992265-b1bafa00-345b-11e9-8b7a-bda7b5ca4497.png">

**Comment by loganhz** [comment]
Close in favor of https://github.com/kubernetes/ingress-nginx/issues/3426

**Comment by ppodolsky** [comment]
> Close in favor of [kubernetes/ingress-nginx#3426](https://github.com/kubernetes/ingress-nginx/issues/3426)

Excuse me, could you provide a little bit more details? Did you close this issue in favor of another closed and unresolved issue?

**Comment by vmitris** [comment]
This is still reproducing with k8s.gcr.io/ingress-nginx/controller:v0.41.2. For requests coming from within clusters where $host is a FQDN all the requests cannot be resolved. If hardcoded static IP is used it works fine but this is not a solution as there are multiple scenarios when IP is not known at deployment time.

Please reopen it as it seems there is no solution yet
