### ISSUE TITLE
nodes are not deleted/cleaned up from cluster when they are still being provisioned

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#13882]
2.0
AWS EC2

Create node tmpl (t2.medium), while the nodes are being provisioned, delete them. This is not cleaning up the nodes.

**Comment by loganhz** [comment]
I can reproduced the same issue with Aliyun ECS

**Comment by StrongMonkey** [comment]
duplicate https://github.com/rancher/rancher/issues/11277

**Comment by StrongMonkey** [comment]
@leodotcloud i couldn't reproduce the issue. The nodes are controlled by nodepool so if you delete a node it will immediately creates a same node. But there is a known issue that you can't delete node when it is provisioning.(11277)

**Comment by deniseschannon** [comment]
@leodotcloud the node pool will always have whatever was set, but are you saying they aren't being cleaned up in the backend?

**Comment by sangeethah** [comment]
@adingilloRancher Can you see if you are able to reproduce this issue with latest master build ?

**Comment by leodotcloud** [comment]
@deniseschannon yes they were not being cleaned up.

**Comment by adingilloRancher** [comment]
Master 8/6

Ec2 instances were deleted properly when removing nodes during provisioning.
