### ISSUE TITLE
Rancher 2/0 install hangs

### ISSUE THREAD

**Issue by sahina** [rancher/rancher#13880]
**Rancher versions:**
rancher/rancher: 2.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal Mac OSX

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Default Cattle

**Steps to Reproduce:**
`docker run -p 80:80 -p 443:443 rancher/rancher`

**Results:**
Install fails

```
...
2018/06/06 21:55:03 [INFO] Creating node driver openstack
2018/06/06 21:55:03 [INFO] Creating node driver otc
2018/06/06 21:55:03 [INFO] Creating node driver packet
2018/06/06 21:55:03 [INFO] Creating node driver rackspace
2018/06/06 21:55:03 [INFO] Creating node driver softlayer
2018/06/06 21:55:03 [INFO] Creating node driver aliyunecs
2018/06/06 21:55:03 [INFO] Creating node driver vmwarevsphere
2018/06/06 21:55:03 [INFO] uploading amazonec2Config to node schema
2018/06/06 21:55:03 [INFO] uploading amazonec2Config to node schema
2018/06/06 21:55:03 [INFO] uploading azureConfig to node schema
2018/06/06 21:55:03 [INFO] uploading azureConfig to node schema
2018/06/06 21:55:03 [INFO] uploading digitaloceanConfig to node schema
2018/06/06 21:55:03 [INFO] uploading digitaloceanConfig to node schema
2018/06/06 21:55:03 [INFO] uploading vmwarevsphereConfig to node schema
2018/06/06 21:55:03 [INFO] uploading vmwarevsphereConfig to node schema
2018/06/06 21:55:17 [INFO] traversing files and generating templates
2018/06/06 21:55:22 [INFO] Updating catalog library
2018/06/06 21:55:22 [INFO] Creating template library-mariadb
2018/06/06 21:55:22 [INFO] Creating template library-memcached
2018/06/06 21:55:22 [INFO] Creating template library-mysql
2018/06/06 21:55:22 [INFO] Creating template library-wordpress
2018/06/06 21:55:23 [INFO] Creating template library-etcd-operator
2018/06/06 21:55:23 [INFO] Creating template library-grafana
2018/06/06 21:55:23 [INFO] Creating template library-magento
2018/06/06 21:55:23 [INFO] Creating template library-mongodb
2018/06/06 21:55:23 [INFO] Creating template library-mongodb-replicaset
2018/06/06 21:55:23 [INFO] Creating template library-prometheus
2018/06/06 21:55:23 [INFO] Creating template library-redis
2018/06/06 21:55:23 [INFO] Creating template library-longhorn
2018/06/06 21:55:23 [INFO] Creating template library-nfs-provisioner
2018-06-06 21:57:20.681141 W | wal: sync duration of 4.481194507s, expected less than 1s
```

**Comment by superseb** [comment]
There is nothing indicating it has failed, the sync duration is higher, usually because the machine it is running on is not fast enough CPU/memory/disk. Are you using Docker for Mac or an actual bare metal machine? What are the specs of virtual machine in Docker for Mac or the machine it's running on?

Full logs would be helpful too, does the container stop/crash?

**Comment by sahina** [comment]
It just hangs. I left it alone for hours but no movement... I am on 2017 Mac with 16GB RAM with Intel Corei7 CPU.

**Comment by sahina** [comment]
Closing this as docker version should be 17.03 recommended by Rancher 2.0
