### ISSUE TITLE
Can't create second PV on NFS

### ISSUE THREAD

**Issue by gjongenelen** [rancher/rancher#13887]
**Rancher versions:**
rancher/rancher: 2.0.2

**Docker version: (`docker version`,`docker info` preferred)**
18.3.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 1.4.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 

**Steps to Reproduce:**
Create first PV and PVC. Mount that in a workload.
Now create second PV and PVC, as soon as you mount the PVC in a workload the pod is stuck on scheduling with error: **Persistentvolumeclaim "web" not found**

The output of kubectl get pv:
```
NAME       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM               STORAGECLASS   REASON    AGE
mysql-01   100Gi      RWX            Retain           Bound     database/mysql-01                            37m
web        100Gi      RWX            Retain           Bound     web/web                                      14m
```
I also tried manually setting the claimName to web/web, because the workload is in another namespace. But still not found.

**Comment by loganhz** [comment]
hi @gjongenelen , the PVC should be in the same namespace with workload. 
Can you check that, please?
We have made a UI fix to filter out the PVC not in the same namespace with workload. But it is not released yet.

Thanks

**Comment by gjongenelen** [comment]
Thank you, but I found out that there is another problem, preventing the pod from starting. The container is now stuck in creating-state.

In the logs of  kubelet:
E0608 07:26:47.155085    1576 summary.go:102] Failed to get system container stats for "/docker/6c3d70a4de08156eebe0fdd1014faaa816dea447ab30f7e9663ca506ce923fca": failed to get cgroup stats for "/docker/6c3d70a4de08156eebe0fdd1014faaa816dea447ab30f7e9663ca506ce923fca": failed to get container info for "/docker/6c3d70a4de08156eebe0fdd1014faaa816dea447ab30f7e9663ca506ce923fca": unknown container "/docker/6c3d70a4de08156eebe0fdd1014faaa816dea447ab30f7e9663ca506ce923fca"
E0608 07:26:49.585167    1576 mount_linux.go:148] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs _ipaddress_:/data/export/web-01 /opt/rke/var/lib/kubelet/pods/40b96314-6aed-11e8-a041-12a68b5af8fd/volumes/kubernetes.io~nfs/web-01
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.

**Comment by loganhz** [comment]
Can you try this https://backdrift.org/fixing-rpc-statd-running-required-remote-locking, please? 

Please create a new issue with reproduce steps if you still can reproduce it. Thanks!
