### ISSUE TITLE
Error in log  (in console 	Waiting for etcd and controlplane nodes to be registered)

### ISSUE THREAD

**Issue by publicocean0** [rancher/rancher#13889]
**Rancher versions:**
latest 
I have just installed racher for trying a demo.
I created a custom cluster. Then i have this error. 

```
2018/06/07 15:39:26 [INFO] Creating node driver packet
2018/06/07 15:39:26 [INFO] Creating node driver rackspace
2018/06/07 15:39:26 [INFO] Creating node driver softlayer
2018/06/07 15:39:26 [INFO] Creating node driver aliyunecs
2018/06/07 15:39:26 [INFO] Creating node driver vmwarevsphere
E0607 15:39:26.952676       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.ClusterRegistrationTokenStatus
2018/06/07 15:39:27 [INFO] uploading digitaloceanConfig to node schema
2018/06/07 15:39:27 [INFO] uploading digitaloceanConfig to node schema
2018/06/07 15:39:27 [INFO] uploading vmwarevsphereConfig to node schema
2018/06/07 15:39:27 [INFO] uploading vmwarevsphereConfig to node schema
2018/06/07 15:39:27 [INFO] uploading amazonec2Config to node schema
2018/06/07 15:39:27 [INFO] uploading amazonec2Config to node schema
2018/06/07 15:39:27 [INFO] uploading azureConfig to node schema
2018/06/07 15:39:27 [INFO] uploading azureConfig to node schema
E0607 15:39:31.087155       1 core.go:70] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail.
E0607 15:39:34.781042       1 certificates.go:48] Failed to start certificate controller: error reading CA cert file "/etc/kubernetes/ca/ca.pem": open /etc/kubernetes/ca/ca.pem: no such file or directory
E0607 15:40:07.119787       1 generic_controller.go:204] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 213.136.95.11:53: read udp 172.17.0.2:46748->213.136.95.11:53: i/o timeout
E0607 15:40:47.179494       1 generic_controller.go:204] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 213.136.95.11:53: read udp 172.17.0.2:45928->213.136.95.11:53: i/o timeout
E0607 15:41:27.238953       1 generic_controller.go:204] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 213.136.95.11:53: read udp 172.17.0.2:35903->213.136.95.11:53: i/o timeout
E0607 15:42:07.286625       1 generic_controller.go:204] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 213.136.95.11:53: read udp 172.17.0.2:39323->213.136.95.11:53: i/o timeout
2018/06/07 15:42:33 [INFO] traversing files and generating templates
2018/06/07 15:42:37 [INFO] Updating catalog library
2018/06/07 15:42:37 [INFO] Creating template library-etcd-operator
2018/06/07 15:42:37 [INFO] Creating template library-memcached
2018/06/07 15:42:37 [INFO] Creating template library-mongodb
2018/06/07 15:42:38 [INFO] Creating template library-prometheus
2018/06/07 15:42:38 [INFO] Creating template library-redis
2018/06/07 15:42:38 [INFO] Creating template library-wordpress
2018/06/07 15:42:38 [INFO] Creating template library-nfs-provisioner
2018/06/07 15:42:38 [INFO] Creating template library-grafana
2018/06/07 15:42:38 [INFO] Creating template library-magento
2018/06/07 15:42:38 [INFO] Creating template library-mariadb
2018/06/07 15:42:39 [INFO] Creating template library-mongodb-replicaset
2018/06/07 15:42:39 [INFO] Creating template library-mysql
2018/06/07 15:42:39 [INFO] Creating template library-longhorn
E0607 15:44:27.179455       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.ComposeStatus


```

**Comment by superseb** [comment]
Except for the network connectivity errors (your container doesn't seem to be able to reach outside, at least your configured DNS server `213.136.95.11`) there is nothing indicating what's wrong here. The more steps you can provide, the better we can help.

What kind of cluster are you creating, what host/Docker are you using? What is in the `rancher/rancher-agent` logs of the node you are trying to add?

**Comment by publicocean0** [comment]
i removed all rancher container and re tryed not adding no node to cluster . 
in log i see
```
E0607 15:44:27.179455       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.ComposeStatus
E0607 15:49:06.192548       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.AlertStatus
2
.....
2018/06/07 16:04:05 [INFO] ClusterController c-hlkpm completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
```
I made few steps :I created a custom cluster.
I flagged this node is control, etcd, worker. 
The cluster remains in state provisioning with message "

Waiting for etcd and controlplane nodes to be registered

" 

This behaviour does not seams related to add additional nodes. 

Sorry for understanding .... etcd is key/value db ... i can suppose a kind of ldap server for cluster. Worker i image if i can deploy services directly in this node and control is the manager of cluster. 
If i flag all i suppose all in contained in rancher contaniner.

**Comment by publicocean0** [comment]
with new agent with ipv4 
# sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.2 --server https://173.212.226.125 --token ng2bmc246xbwgxt9zbt4pcw4jvqsg5jxhpqs5hnsqqkmzqs9xnzwrj --ca-checksum 83b13caaf9f98ed072485fdc4ce5f8629f91bda708ff2a43b603b5a357c5311d --etcd --controlplane --worker
d11525f5bd547c188a072c4c469d11a9b7333a3e4b779e70d4272a72aad02d7d

i have new errors in the log 

Found container ID: 8c00a5b8c1ecf4f5f5767d8e0adc440518f5f6443afd5a167e39008d6249dd7d
Checking root: /host/run/runc
Checking root: /host/var/run/runc
Checking root: /host/run/docker/execdriver/native
Checking root: /host/var/run/docker/execdriver/native
Checking root: /host/run/docker/runtime-runc/moby
Checking file: 175c8a2ce3324808d7004f05db6ccf7cc113cab43bbeecf04391e01f327a48cb
Checking file: 683c3c98e1b48d75f1ce640e06e851b1b9b4a679794a103673f4b1832f177dd9
Checking file: 8c00a5b8c1ecf4f5f5767d8e0adc440518f5f6443afd5a167e39008d6249dd7d
Found state.json: 8c00a5b8c1ecf4f5f5767d8e0adc440518f5f6443afd5a167e39008d6249dd7d
time="2018-06-07T16:39:43Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/25659/ns/mnt -F -- /var/lib/docker/devicemapper/mnt/938bc94343af56c2b5858950ce4f0aa0ff7a0cc381cc4762a292d47b5bb4e00e/rootfs/usr/bin/share-mnt --stage2 /var/lib/kubelet /var/lib/rancher -- norun]" 
Error response from daemon: {"message":"No such container: kubelet"}

**Comment by publicocean0** [comment]
I removed all ... and i remade all with ipv4...now it seams deploy other container but now remains in 

[pre-deploy] Pulling image [rancher/hyperkube:v1.10.1-rancher2] on host [173.212.226.125]
--

**Comment by superseb** [comment]
The error in that container is not relevant for this case, the logging from the other `rancher/rancher-agent` container contains the actual logging of the process. If it's stuck on `Pulling image`, what is the state of the host with IP `173.212.226.125`? Can you manually pull the image? What are the specifications of the machines you are using?

**Comment by publicocean0** [comment]
Now i see in console other 3 containers 
f32099e79ba4        rancher/rke-tools:v0.1.8             "nc -kl -p 1337 -e e…"   10 minutes ago      Up 10 minutes       80/tcp, 0.0.0.0:10250->1337/tcp            rke-worker-port-listener
cc40a304ea5f        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint…"   12 minutes ago      Up About a minute                                              kube-apiserver
80b35d287687        rancher/coreos-etcd:v3.1.12          "/usr/local/bin/etcd…"   12 minutes ago      Up 12 minutes                                                  etcd

**Comment by superseb** [comment]
What are the specs of the machine you are running on?

**Comment by publicocean0** [comment]
CentOS Linux release 7.5.1804 (Core)

**Comment by superseb** [comment]
You need to specify what you are executing exactly, `lanched rancher with the ip of second nic` can be anything, are you passing parameters or what are you launching?

**Comment by publicocean0** [comment]
i solved adding --net br0 to rancher

**Comment by superseb** [comment]
Those events are unrelated, the variables for MongoDB to use persistence are described here: https://github.com/rancher/charts/tree/master/charts/mongodb/v2.0.1

If you can share the setup of the host and Docker (which is not default), I can see if we can make the install process better.

**Comment by publicocean0** [comment]
Ok. 
Another little bug i see sometimes removing catalog apps remains a volume in removing state. I dont know if exist a way for forcely removal.
Testing mongodb and passing servicePort as answer ... there is a error ```
{
"actions": {
"rollback": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b?action=rollback",
"upgrade": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b?action=upgrade"
},
"annotations": {
"lifecycle.cattle.io/create.helm-controller_c-h8r9x": "true"
},
"answers": {
"persistence.existingClaim": "mongodb",
"service.nodePort": "27017",
"service.type": "ClusterIP"
},
"appRevisionId": "apprevision-rpmkx",
"baseType": "app",
"conditions": [
{
"lastUpdateTime": "2018-06-08T09:09:57Z",
"message": "Kubectl apply failed. Error: The Service \"mongodb-eul84b-mongodb\" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'\n: exit status 1",
"reason": "Error",
"status": "False",
"type": "Installed"
}
],
"created": "2018-06-08T09:01:29Z",
"createdTS": 1528448489000,
"creatorId": "user-255cm",
"externalId": "catalog://?catalog=helm&template=mongodb&version=2.0.9",
"id": "project-dg4qn:mongodb-eul84b",
"lastAppliedTemplate": "---\n# Source: mongodb/templates/secrets.yaml\napiVersion: v1\nkind: Secret\nmetadata:\n  name: mongodb-eul84b-mongodb\n  labels:\n    app: mongodb\n    chart: \"mongodb-2.0.9\"\n    release: \"mongodb-eul84b\"\n    heritage: \"Tiller\"\ntype: Opaque\ndata:\n  mongodb-root-password: \"blY5Tmp6aWU0cQ==\"\n\n---\n# Source: mongodb/templates/svc.yaml\napiVersion: v1\nkind: Service\nmetadata:\n  name: mongodb-eul84b-mongodb\n  labels:\n    app: mongodb\n    chart: \"mongodb-2.0.9\"\n    release: \"mongodb-eul84b\"\n    heritage: \"Tiller\"\nspec:\n  type: ClusterIP\n  ports:\n  - name: mongodb\n    port: 27017\n    targetPort: mongodb\n    nodePort: 27017\n  selector:\n    app: mongodb\n    release: \"mongodb-eul84b\"\n\n---\n# Source: mongodb/templates/deployment.yaml\napiVersion: extensions/v1beta1\nkind: Deployment\nmetadata:\n  name: mongodb-eul84b-mongodb\n  labels:\n    app: mongodb\n    chart: \"mongodb-2.0.9\"\n    release: \"mongodb-eul84b\"\n    heritage: \"Tiller\"\nspec:\n  template:\n    metadata:\n      labels:\n        app: mongodb\n        release: \"mongodb-eul84b\"\n    spec:\n      containers:\n      - name: mongodb-eul84b-mongodb\n        image: docker.io/bitnami/mongodb:3.6.5\n        imagePullPolicy: \"IfNotPresent\"\n        env:\n        - name: MONGODB_ROOT_PASSWORD\n          valueFrom:\n            secretKeyRef:\n              name: mongodb-eul84b-mongodb\n              key: mongodb-root-password\n        - name: MONGODB_USERNAME\n          value: \"\"\n        - name: MONGODB_DATABASE\n          value: \"\"\n        - name: MONGODB_EXTRA_FLAGS\n          value: \n        ports:\n        - name: mongodb\n          containerPort: 27017\n        livenessProbe:\n          exec:\n            command:\n            - mongo\n            - --eval\n            - \"db.adminCommand('ping')\"\n          failureThreshold: 6\n          initialDelaySeconds: 30\n          periodSeconds: 10\n          successThreshold: 1\n          timeoutSeconds: 5\n          \n        readinessProbe:\n          exec:\n            command:\n            - mongo\n            - --eval\n            - \"db.adminCommand('ping')\"\n          failureThreshold: 6\n          initialDelaySeconds: 5\n          periodSeconds: 10\n          successThreshold: 1\n          timeoutSeconds: 5\n          \n        volumeMounts:\n        - name: data\n          mountPath: /bitnami/mongodb\n        resources:\n          requests:\n            cpu: 100m\n            memory: 256Mi\n          \n      volumes:\n      - name: data\n        persistentVolumeClaim:\n          claimName: mongodb\n---\n# Source: mongodb/templates/pvc.yaml",
"links": {
"remove": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b",
"revision": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b/revision",
"self": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b",
"update": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b"
},
"name": "mongodb-eul84b",
"namespaceId": null,
"notes": "---\n# Source: mongodb/templates/NOTES.txt\n\n\n** Please be patient while the chart is being deployed **\n\nMongoDB can be accessed via port 27017 on the following DNS name from within your cluster:\n\n    mongodb-eul84b-mongodb.mongodb-eul84b.svc.cluster.local\n\nTo get the root password run:\n\n    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace mongodb-eul84b mongodb-eul84b-mongodb -o jsonpath=\"{.data.mongodb-root-password}\" | base64 --decode)\n\nTo connect to your database run the following command:\n\n    kubectl run mongodb-eul84b-mongodb-client --rm --tty -i --image bitnami/mongodb --command -- mongo --host mongodb-eul84b-mongodb -p $MONGODB_ROOT_PASSWORD\n\nTo connect to your database from outside the cluster execute the following commands:\n\n    export POD_NAME=$(kubectl get pods --namespace mongodb-eul84b -l \"app=mongodb\" -o jsonpath=\"{.items[0].metadata.name}\")\n    kubectl port-forward --namespace mongodb-eul84b $POD_NAME 27017:27017 &\n    mongo --host 127.0.0.1 -p $MONGODB_ROOT_PASSWORD",
"projectId": "c-h8r9x:project-dg4qn",
"prune": false,
"state": "installing",
"targetNamespace": "mongodb-eul84b",
"transitioning": "error",
"transitioningMessage": "Kubectl apply failed. Error: The Service \"mongodb-eul84b-mongodb\" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'\n: exit status 1",
"type": "app",
"uuid": "88814f9b-6afa-11e8-af18-0242c0a80001"
} 
```

**Comment by superseb** [comment]
Can you file a new issue with the steps you've taken and when the error shows? This is not about the initial problem anymore. If you can share host configuration as requested before, I can take a look at making the install better. Apart from the latest post I don't see an actual bug here yet.

**Comment by publicocean0** [comment]
Ok sorry i didnt share "share host configuration". If you want i can pass admin user for entering.

**Comment by superseb** [comment]
Ok, I'm on Rancher Users Slack (https://slack.rancher.io). Let me close this and create a new one if I find something on the host.
