### ISSUE TITLE
GKE ingress goes to active state even when the publicEndpoints are not populated in the API

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13881]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.2

**Steps to Reproduce:**
1. Create a GKE cluster
2. Create workloads and ingress pointing to the workloads

The publicEndpoints of the ingress gets populated after around 2mins, but the ingress state shows active immediately after it is created. It should show pending .

**Comment by alena1108** [comment]
@StrongMonkey yes. We can do it in Transform, on the API layer.

**Comment by cjellick** [comment]
@nathan-jenan-rancher to validate

**Comment by nathan-jenan-rancher** [comment]
Re-tested the issue.  I have found the following:
1) The ingress does not go to active until the IP address has been populated, *however*
2) The workload is still not available for a few more minutes because DNS has not populated

**Comment by soumyalj** [comment]
@cjellick : Is this supposed to be status/to-test ? From your comments u were suggesting to find a mechanism to tell when GKE has successfully programmed the ingress. There is no PR for this implementation. 

This is my observation so far after testing on master:
The ingress is in "intializing" state until the public endpoints are populated as expected. 
But it goes to active state immediately right after public endpoints are populated, but the ingress is not functional yet. 
Before the ingress is functional, the annotation is as below:
```
ingress.kubernetes.io/backends": "{\"k8s-be-30586--3a4dda6f5a667f47\":\"Unknown\",\"k8s-be-31853--3a4dda6f5a667f47\":\"Unknown\"}",
```
After the ingress is functional, the annotation is as below:
```
"ingress.kubernetes.io/backends": "{\"k8s-be-30586--3a4dda6f5a667f47\":\"HEALTHY\",\"k8s-be-31853--3a4dda6f5a667f47\":\"HEALTHY\"}",

```
