### ISSUE TITLE
Service links exist but aren't showing up in UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1389]
v0.26.0-rc1
Steps:
1.  Have two Environments (Default and Dev)
2.  Add host to both
3.  Create two services in each Environment
4.  Go to Default and edit one service and link it to the other
5.  Go to Dev and edit on service and link it to the other

Results:
The link won't show up in Dev environment, if you refresh the page, it will show up.  But if you go back to Default it won't show up there anymore.  Refresh and links will show up on Default but won't on Dev.

Expected:
Links should show up for all environments at same time

**Comment by vincent99** [comment]
@tfiduccia I think this is the continuing saga of websocket disconnects?

**Comment by deniseschannon** [comment]
@vincent99 Nope, this is reproducible on my setup. It's something to do with the fact that there are 2 environments.

In my case, the link didn't show up any time I edit and added the link until I refresh.

**Comment by deniseschannon** [comment]
@vincent99 This actually happens on create if you have 2 environments. The service links don't show up.

**Comment by cjellick** [comment]
Reported in IRC:
```
tommmied
On page reload for stacks,  sometimes the service links are not properly labeled on the services and causes cloning/edits of that service to lose them after an update
```

**Comment by deniseschannon** [comment]
This still exists in the reskin.

**Comment by kaos** [comment]
+1

I've seen this as well for a while now.

haven't debugged the actual traffic.. but here's what I see:

We have several environments (3). The default environment that is selected when you log in doesn't have any services in it (only containers), and an empty default stack.

When I select another environment that does have services, it doesn't load the service links properly in the GUI:
<img width="1267" alt="screen shot 2015-11-30 at 08 47 47" src="https://cloud.githubusercontent.com/assets/72965/11466347/92482dfc-9740-11e5-88b6-0e46489c927c.png">

After a page reload, it shows up nicely:
<img width="1260" alt="screen shot 2015-11-30 at 08 48 46" src="https://cloud.githubusercontent.com/assets/72965/11466366/aed0f350-9740-11e5-93b8-911e644c5f62.png">

@vincent99, as @deniseschannon has reported this as reproducible, I defer any further debugging unless you ask for it.. :)

**Comment by tfiduccia** [comment]
Adding this to the next milestone.  Customers are hitting it, can we get this fixed?

**Comment by vincent99** [comment]
Ok I was previously trying to solve a similar but different problem with new links to not show up sometimes depending on the order and timing of the change events.. If you do what this issue *actually* says, the problem is the mapping of service links is loaded once and not reset when switching environments so it's wrong until you reload.  So that's an easy change (https://github.com/rancher/ui/pull/428)

**Comment by deniseschannon** [comment]
I'll see if it fixes the use case that I've seen in the next RC.

**Comment by will-chan** [comment]
Most anticipated fix for 2016!

**Comment by deniseschannon** [comment]
Verified with v0.55.0-rc3. My use case (how I run training/demos) seems to not have the previous issues with linking. :)

**Comment by tfiduccia** [comment]
version - master 01/19
Verified fixed
