### ISSUE TITLE
Ability to turn on PSPs for a cluster after cluster creation

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#13895]
RKE supports modifying an existing cluster to turn on pod security policies; we could/should bubble this up to the UI level.

**Comment by JasonvanBrackel** [comment]
@cjellick You can edit the cluster > cluster options > Enable Pod Secrity Policy > Select a Policy

Or am I missing something here.

**Comment by JasonvanBrackel** [comment]
Actually it appears that it doesn't work.  It enforce PSPs, but the default selected PSP is not created on the managed cluster so clusters can no longer be deployed.

**Comment by loganhz** [comment]
It's supported in UI now

![image](https://user-images.githubusercontent.com/21168270/46067450-68ff5d80-c1a9-11e8-8f6d-a9dd9f6a5361.png)
