### ISSUE TITLE
Can't add a new node on the cluster

### ISSUE THREAD

**Issue by matheus666matheus** [rancher/rancher#13893]
**Docker version: (docker version,docker info preferred)**

Version: 17.03.2-ce
API version: 1.27
Go version: go1.7.5
Git commit: f5ec1e2
Built: Tue Jun 27 02:21:36 2017
OS/Arch: linux/amd64

Server:
Version: 17.03.2-ce
API version: 1.27 (minimum version 1.12)
Go version: go1.7.5
Git commit: f5ec1e2
Built: Tue Jun 27 02:21:36 2017
OS/Arch: linux/amd64
Experimental: false

**Operating system and kernel: (cat /etc/os-release, uname -r preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

Hi guys,

When I try to add a new node on the cluster I get this error in the web interface:

**[network] Port check for ports: [10.1.1.32:2379, 10.1.1.32:2380] failed on host: [10.1.1.66]**

And this message is looping on container rancher/rancher:

2018/06/07 18:30:48 [INFO] Provisioning cluster [c-lvm5p]
2018/06/07 18:30:48 [INFO] Updating cluster [c-lvm5p]
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: Building Kubernetes cluster
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [dialer] Setup tunnel for host [10.1.1.66]
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [dialer] Setup tunnel for host [10.1.1.32]
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [state] Found local kube config file, trying to get state from cluster
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [state] Fetching cluster state from Kubernetes
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [state] Successfully Fetched cluster state to Kubernetes ConfigMap: cluster-state
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [certificates] Getting Cluster certificates from Kubernetes
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [certificates] Successfully fetched Cluster certificates from Kubernetes
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [network] Deploying port listener containers
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [network] Port listener containers deployed successfully
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [network] Running etcd <-> etcd port checks
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [network] Successfully started [rke-port-checker] container on host [10.1.1.66]
2018/06/07 18:30:48 [INFO] cluster [c-lvm5p] provisioning: [network] Successfully started [rke-port-checker] container on host [10.1.1.32]
2018/06/07 18:30:48 [INFO] ClusterController c-lvm5p completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 10m0s
2018/06/07 18:30:49 [INFO] ClusterController c-lvm5p completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 10m0s
2018/06/07 18:31:06 [INFO] ClusterController c-lvm5p completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 10m0s

Where 10.1.1.32 is my host with the rancher server and 10.1.1.66 is the one that I am trying to add. Firewalld is down on both nodes. I know I need to provide more information to get help here...which log files I need to inspect?

**Comment by matheus666matheus** [comment]
The kubelet container log is displaying this:

I0607 18:47:35.851491   14639 kuberuntime_manager.go:513] Container {Name:nginx-ingress-controller Image:rancher/nginx-ingress-controller:0.10.2-rancher3 Command:[] Args:[/nginx-ingress-controller --default-backend-service=$(POD_NAMESPACE)/default-http-backend --configmap=$(POD_NAMESPACE)/nginx-configuration --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services --udp-services-configmap=$(POD_NAMESPACE)/udp-services --annotations-prefix=nginx.ingress.kubernetes.io] WorkingDir: Ports:[{Name:http HostPort:80 ContainerPort:80 Protocol:TCP HostIP:} {Name:https HostPort:443 ContainerPort:443 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:POD_NAME Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.name,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {Name:POD_NAMESPACE Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:nginx-ingress-serviceaccount-token-tw855 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:10254,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:10,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:10254,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
I0607 18:47:35.851755   14639 kuberuntime_manager.go:757] checking backoff for container "nginx-ingress-controller" in pod "nginx-ingress-controller-zj4nn_ingress-nginx(dc3e5131-69af-11e8-b5fa-00259093feb4)"
I0607 18:47:35.852083   14639 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=nginx-ingress-controller pod=nginx-ingress-controller-zj4nn_ingress-nginx(dc3e5131-69af-11e8-b5fa-00259093feb4)
E0607 18:47:35.852161   14639 pod_workers.go:186] Error syncing pod dc3e5131-69af-11e8-b5fa-00259093feb4 ("nginx-ingress-controller-zj4nn_ingress-nginx(dc3e5131-69af-11e8-b5fa-00259093feb4)"), skipping: failed to "StartContainer" for "nginx-ingress-controller" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=nginx-ingress-controller pod=nginx-ingress-controller-zj4nn_ingress-nginx(dc3e5131-69af-11e8-b5fa-00259093feb4)"

**Comment by OBenned** [comment]
afaik you should not turn off your firewall, since docker will take care of this for you, can you try to turn it on adn then deploy again?

**Comment by matheus666matheus** [comment]
I redeploy it on Ubuntu 18.04...
