### ISSUE TITLE
did you specify the right host or port?

### ISSUE THREAD

**Issue by haidisenlin** [rancher/rancher#13899]
*Describe your issue here*
I copy  kubeconfig content to my computer,and installed the kubel ,but when I connect to the server it shows "The connection to the server 192.168.38.150 was refused - did you specify the right host or port?"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by superseb** [comment]
Where did you copy it to? It needs to be either in `~/.kube/config` or you can specify it using `kubectl --kubeconfig /path/to/kubeconfig`

Is `192.168.38.150` the IP you set up for the host running the `rancher/rancher` container?

**Comment by haidisenlin** [comment]
I know  why this problem happened .I use the sock5 proxy to download the images. all of the ip's  are represented
