### ISSUE TITLE
FlexVolume plugin directory not bind mounted in kubelet

### ISSUE THREAD

**Issue by sinqinc** [rancher/rancher#13897]
I try to use a FlexVolume plugin in a new Rancher 2 Cluster. I wasn't able to deploy a workload using a volume that use the FlexVolume driver. The driver wasn't found by the kubelet. The path defined by the flag --volume-plugin-dir is /var/lib/kubelet/volumeplugins but the kubelet seems to bind mount /opt/rke/kubelet instead.

Is this a normal beaviour ? How can I modify the --volume-plugin-dir or add the mount in the kubelet (RKE) container created by Rancher ?

Thank you

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by TehTotalPwnage** [comment]
This issue should be fixed in rancher/rke#800 and be made available in the next release. The kubelet should bind mount `/var/lib/kubelet/volumeplugins` instead.

Let me know if the issue still persists in the next release :slightly_smiling_face:

**Comment by MrAmbiG** [comment]
kubelet, 10.216.55.125  Error: failed to start container "upgrade-ipam": Error response from daemon: error while creating mount source path '/var/lib/cni/networks': mkdir /var/lib/cni: read-only file system
The above logs are from calico pod from kube-system namespace. It seems the issue still persists.
