### ISSUE TITLE
Clone have some bug

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#13905]
If you clone a workload, the workload's lable and annomation that created by system will clone togother, then will cause bug,  because of the  app lable is same .

if I remove the lable called catte-* , then can't create the work load

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by loganhz** [comment]
Fixed in v2.0.4
