### ISSUE TITLE
Provide lock functionality for "local" cluster in HA mode

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#13907]
In a 2.0 HA install setup, it's very easy to accidentally modify the "local" cluster. I know this is like shooting on self in the foot. But can we provide a safety lock?

**Comment by deniseschannon** [comment]
With HA, you have the ability to hide the local cluster:

https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#import-local-cluster
