### ISSUE TITLE
mongodb :Forbidden: may not be used when `type` is 'ClusterIP'\n: exit status

### ISSUE THREAD

**Issue by publicocean0** [rancher/rancher#13903]
**Rancher versions:**
rancher/server or rancher/rancher:last version
rancher/agent or rancher/rancher-agent:last version

**Docker version: 
`docker info
Containers: 23
 Running: 21
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 18.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-39453059-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 5.543GB
 Data Space Total: 107.4GB
 Data Space Available: 101.8GB
 Metadata Space Used: 8.319MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.139GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 10
Total Memory: 48.98GiB
Name: master
ID: UDWD:S5F7:7S2W:Y6EJ:X33H:7IEN:SPQW:IE7D:IO57:V4UT:SDMC:PTC4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

**Operating system and kernel:
`NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
`
**Type/provider of hosts: VPS

**Setup details: single node rancher

**Environment Template: Kubernetes

**Steps to Reproduce:
add mongodb catalog template 
adding servicePort 27027

> {
> "actions": {
> "rollback": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b?action=rollback",
> "upgrade": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b?action=upgrade"
> },
> "annotations": {
> "lifecycle.cattle.io/create.helm-controller_c-h8r9x": "true"
> },
> "answers": {
> "persistence.existingClaim": "mongodb",
> "service.nodePort": "27017",
> "service.type": "ClusterIP"
> },
> "appRevisionId": "apprevision-rpmkx",
> "baseType": "app",
> "conditions": [
> {
> "lastUpdateTime": "2018-06-08T09:09:57Z",
> "message": "Kubectl apply failed. Error: The Service \"mongodb-eul84b-mongodb\" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'\n: exit status 1",
> "reason": "Error",
> "status": "False",
> "type": "Installed"
> }
> ],
> "created": "2018-06-08T09:01:29Z",
> "createdTS": 1528448489000,
> "creatorId": "user-255cm",
> "externalId": "catalog://?catalog=helm&template=mongodb&version=2.0.9",
> "id": "project-dg4qn:mongodb-eul84b",
> "lastAppliedTemplate": "---\n# Source: mongodb/templates/secrets.yaml\napiVersion: v1\nkind: Secret\nmetadata:\n  name: mongodb-eul84b-mongodb\n  labels:\n    app: mongodb\n    chart: \"mongodb-2.0.9\"\n    release: \"mongodb-eul84b\"\n    heritage: \"Tiller\"\ntype: Opaque\ndata:\n  mongodb-root-password: \"blY5Tmp6aWU0cQ==\"\n\n---\n# Source: mongodb/templates/svc.yaml\napiVersion: v1\nkind: Service\nmetadata:\n  name: mongodb-eul84b-mongodb\n  labels:\n    app: mongodb\n    chart: \"mongodb-2.0.9\"\n    release: \"mongodb-eul84b\"\n    heritage: \"Tiller\"\nspec:\n  type: ClusterIP\n  ports:\n  - name: mongodb\n    port: 27017\n    targetPort: mongodb\n    nodePort: 27017\n  selector:\n    app: mongodb\n    release: \"mongodb-eul84b\"\n\n---\n# Source: mongodb/templates/deployment.yaml\napiVersion: extensions/v1beta1\nkind: Deployment\nmetadata:\n  name: mongodb-eul84b-mongodb\n  labels:\n    app: mongodb\n    chart: \"mongodb-2.0.9\"\n    release: \"mongodb-eul84b\"\n    heritage: \"Tiller\"\nspec:\n  template:\n    metadata:\n      labels:\n        app: mongodb\n        release: \"mongodb-eul84b\"\n    spec:\n      containers:\n      - name: mongodb-eul84b-mongodb\n        image: docker.io/bitnami/mongodb:3.6.5\n        imagePullPolicy: \"IfNotPresent\"\n        env:\n        - name: MONGODB_ROOT_PASSWORD\n          valueFrom:\n            secretKeyRef:\n              name: mongodb-eul84b-mongodb\n              key: mongodb-root-password\n        - name: MONGODB_USERNAME\n          value: \"\"\n        - name: MONGODB_DATABASE\n          value: \"\"\n        - name: MONGODB_EXTRA_FLAGS\n          value: \n        ports:\n        - name: mongodb\n          containerPort: 27017\n        livenessProbe:\n          exec:\n            command:\n            - mongo\n            - --eval\n            - \"db.adminCommand('ping')\"\n          failureThreshold: 6\n          initialDelaySeconds: 30\n          periodSeconds: 10\n          successThreshold: 1\n          timeoutSeconds: 5\n          \n        readinessProbe:\n          exec:\n            command:\n            - mongo\n            - --eval\n            - \"db.adminCommand('ping')\"\n          failureThreshold: 6\n          initialDelaySeconds: 5\n          periodSeconds: 10\n          successThreshold: 1\n          timeoutSeconds: 5\n          \n        volumeMounts:\n        - name: data\n          mountPath: /bitnami/mongodb\n        resources:\n          requests:\n            cpu: 100m\n            memory: 256Mi\n          \n      volumes:\n      - name: data\n        persistentVolumeClaim:\n          claimName: mongodb\n---\n# Source: mongodb/templates/pvc.yaml",
> "links": {
> "remove": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b",
> "revision": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b/revision",
> "self": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b",
> "update": "…/v3/project/c-h8r9x:project-dg4qn/apps/project-dg4qn:mongodb-eul84b"
> },
> "name": "mongodb-eul84b",
> "namespaceId": null,
> "notes": "---\n# Source: mongodb/templates/NOTES.txt\n\n\n** Please be patient while the chart is being deployed **\n\nMongoDB can be accessed via port 27017 on the following DNS name from within your cluster:\n\n    mongodb-eul84b-mongodb.mongodb-eul84b.svc.cluster.local\n\nTo get the root password run:\n\n    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace mongodb-eul84b mongodb-eul84b-mongodb -o jsonpath=\"{.data.mongodb-root-password}\" | base64 --decode)\n\nTo connect to your database run the following command:\n\n    kubectl run mongodb-eul84b-mongodb-client --rm --tty -i --image bitnami/mongodb --command -- mongo --host mongodb-eul84b-mongodb -p $MONGODB_ROOT_PASSWORD\n\nTo connect to your database from outside the cluster execute the following commands:\n\n    export POD_NAME=$(kubectl get pods --namespace mongodb-eul84b -l \"app=mongodb\" -o jsonpath=\"{.items[0].metadata.name}\")\n    kubectl port-forward --namespace mongodb-eul84b $POD_NAME 27017:27017 &\n    mongo --host 127.0.0.1 -p $MONGODB_ROOT_PASSWORD",
> "projectId": "c-h8r9x:project-dg4qn",
> "prune": false,
> "state": "installing",
> "targetNamespace": "mongodb-eul84b",
> "transitioning": "error",
> "transitioningMessage": "Kubectl apply failed. Error: The Service \"mongodb-eul84b-mongodb\" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'\n: exit status 1",
> "type": "app",
> "uuid": "88814f9b-6afa-11e8-af18-0242c0a80001"
> }

**Comment by loganhz** [comment]
This issue has been fixed in rancher/charts

By the way, the default service node port range is from 30000 to 32767.  27017 is invalid if you didn't change the default node port range.
