### ISSUE TITLE
graph doesn't reload if you refresh the page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1390]
v0.26.0-rc1
Steps:
1.  Add Services to Project
2.  Click on Project name
3.  Click on Graph icon
4.  Hit your refresh icon for browser

Results:
Graph doesn't reload, just returns a blank page

Expected:
Graph should reload

**Comment by deniseschannon** [comment]
@tfiduccia 

I believe the graph reloads, but would like you to verify as well. I used v0.49.0-rc1.

**Comment by tfiduccia** [comment]
No longer reproducable
