### ISSUE TITLE
when agent connectioning  ranchar server Error,how to solved it ?

### ISSUE THREAD

**Issue by JustDoItQz** [rancher/rancher#13902]
INFO: Running Agent Registration Process, CATTLE_URL=https://192.168.88.128:8080/v1
INFO: Attempting to connect to: https://192.168.88.128:8080/v1
ERROR: https://192.168.88.128:8080/v1 is not accessible (Connection timed out after 15002 milliseconds)
ERROR: https://192.168.88.128:8080/v1 is not accessible (Connection timed out after 15001 milliseconds)

**Comment by TehTotalPwnage** [comment]
That log doesn't have enough information to indicate the source of the issue. It could be an issue in Rancher, an issue with networking, or anything else.

We'd love to help you out, but we need more information. Which version of Rancher are you running? Are you running on a single node or multiple nodes? Which operating system are you running off of?

Could you describe your issue using this issue template? That way, we'll have the information we need to debug your problem. Thanks!
```
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
```

**Comment by superseb** [comment]
Let us know if you can provide more information to trouble shoot
