### ISSUE TITLE
new feature - add alert/monitoring on persistent volumes (disk full)

### ISSUE THREAD

**Issue by publicocean0** [rancher/rancher#13916]
i saw there are many alerts for ram and cpu but no one for disks , volumes

**Comment by LinAnt** [comment]
This would be a really good enhancement, we are looking into alternatives to achieve this at the moment.

**Comment by loganhz** [comment]
link to https://github.com/rancher/rancher/issues/14230

**Comment by aiyengar2** [comment]
While we don't have support for this feature in the old Monitoring solution, the new Rancher Monitoring / Alerting in Rancher 2.5 (see https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/) supports Grafana Dashboards and Alerts (e.g. `KubePersistentVolumeFillingUp`) on Persistent Volumes by default.

Closing this issue.
