### ISSUE TITLE
Issues with using vCenter node driver

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#13911]
TBD

**Comment by aemneina** [comment]
document permissions for non admin users, most likely the same perms as: https://www.koding.com/docs/terraform/providers/vsphere/index.html/

**Comment by deniseschannon** [comment]
As we've documented it, I'm going to close this issue. 

https://rancher.com/docs/rancher/v2.x/en/tasks/clusters/creating-a-cluster/create-cluster-vsphere/
