### ISSUE TITLE
wrong ca-cert in kubeconfig file  on  rancher ui  dashboard

### ISSUE THREAD

**Issue by itcam** [rancher/rancher#13927]
on rancher UI ---> cluster dashboard   
  in  kubeconfig file ,the ca cert  was wrong with  parameter certificate-authority-data :

**Comment by itcam** [comment]
and I  cannot execute any command  in the  termina

**Comment by superseb** [comment]
We need some more info on how you set up Rancher. If you are using certificates signed by a recognized CA, you'll need to clear them as described here: https://rancher.com/docs/rancher/v2.x/en/installation/single-node-install/#option-c-bring-your-own-certificate-signed-by-recognized-ca

**Comment by itcam** [comment]
I used Self-Signed Cert: , but the CA cert on dashboard  not correct , i download it and put in  .kube/config  I got some error , when I change it to the right CA base64 number , It's ok , NOw ,how can I change the ca cert  in kubeconfig template  on dashaboard

**Comment by itcam** [comment]
![1528685889325](https://user-images.githubusercontent.com/26832982/41210812-69d34a1a-6d66-11e8-929e-6ac00a744ebc.jpg)

**Comment by stefanfritsch** [comment]
Hi,

I have the same problem. I create the cluster by using add custom cluster and running the 

```sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.6 ...```

command on the server.

The string looks like

```IJAO&#43;/ve&#43;/ve&#43;/vRZtJ```

with html replacements like `&#43;`

Thanks,
Stefan

**Comment by loganhz** [comment]
Please follow https://rancher.com/docs/rancher/v2.x/en/installation/single-node/ `Option C-Bring Your Own Certificate: Signed by Recognized CA`

The certificate files must be in PEM format.

```
docker run -d --restart=unless-stopped \
	-p 80:80 -p 443:443 \
	-v /<CERT_DIRECTORY>/<FULL_CHAIN.pem>:/etc/rancher/ssl/cert.pem \
	-v /<CERT_DIRECTORY>/<PRIVATE_KEY.pem>:/etc/rancher/ssl/key.pem \
	rancher/rancher:latest --no-cacerts
```

Can you create a new issue and supply more info on your setup if you still met the same issue?(basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

**Comment by useltmann** [comment]
@loganhz i was applying this to my existing rancher-installation and now my nodes are unable to connect to rancher. logs give me
```
TLS handshake error from 172.18.85.126:34042: remote error: tls: bad certificate
```
appearently this is because the certificate with which the nodes were registered are not valid anymore. Any suggestions how to fix this without deleting the whole cluster?

**Comment by useltmann** [comment]
@loganhz i was applying this to my existing rancher-installation and now my nodes are unable to connect to rancher. logs give me
```
TLS handshake error from 172.18.85.126:34042: remote error: tls: bad certificate
```
appearently this is because the certificate with which the nodes were registered are not valid anymore. Any suggestions how to fix this without deleting the whole cluster?

**Comment by loganhz** [comment]
@useltmann maybe it is related to https://github.com/rancher/rancher/issues/14731?
