### ISSUE TITLE
add 1 worker ,but get 2 record on rancher UI 

### ISSUE THREAD

**Issue by itcam** [rancher/rancher#13926]
I install rancher with rke ,the I update the cluster.yml to add a worker host,but I get 2 record  on rancher UI

**Comment by itcam** [comment]
![image](https://user-images.githubusercontent.com/26832982/41211015-782cf4c0-6d67-11e8-8a6b-fefbf7effa5a.png)

**Comment by loganhz** [comment]
duplicated of https://github.com/rancher/rancher/issues/14011
