### ISSUE TITLE
rancher log terminal disconnect

### ISSUE THREAD

**Issue by lezi1022** [rancher/rancher#13922]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
![image](https://user-images.githubusercontent.com/6735666/41187224-741e7ff2-6bd7-11e8-8224-fccc9e4af2a5.png)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
