### ISSUE TITLE
kubectl shell is stuck in "Connecting" state for imported AKS cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13921]
**Rancher versions:**
rancher/rancher:master

**Steps to Reproduce:**
1. Create a AKS cluster on Azure portal
2. Import the AKS cluster to rancher

After import, kubectl shell is stuck in "connecting" state
exec shell into user pods is stuck in "connecting" state
View logs from user pods also fails

Note: Remote kubectl is functional

**Comment by nathan-jenan-rancher** [comment]
I'm noticing errors from the [rbac handler_base line 151](https://github.com/rancher/rancher/blob/76f5b36b4b4b25d5e10fff6d6bd3fadcd605056b/pkg/controllers/user/rbac/handler_base.go#L151).  This might be what's causing the issues.

**Comment by nathan-jenan-rancher** [comment]
Unable to reproduce.  @soumyalj if you see this issue again please preserve the environment so we can investigate the root cause.

**Comment by soumyalj** [comment]
Tested with master. 
1. Create a AKS cluster on Azure portal
2. Import the AKS cluster to rancher
After import, kubectl shell launched successfully from rancher
Creation of pods succeeded.
Remote kubectl also worked
