### ISSUE TITLE
Unable to add traefik to rancher2

### ISSUE THREAD

**Issue by alexey-kruchenok** [rancher/rancher#13924]
Trying to add Traefik to Rancher2, as described in app description in helm catalog:

NOTE: Operators will typically wish to install this component into the kube-system namespace where that namespace's default service account will ensure adequate privileges to watch Ingress resources cluster-wide.

There is no way to do this, rancher not show kube-system as available namespace from dropdown list, when i type kube-system in namespace field, i got error message: namespaces "kube-system" already exists.

When i add Traefik to different namespace it won't launch properly and not work.

**Rancher versions:**
rancher/rancher 2.0.2
single node rancher
Kubernetes

**Comment by dnauck** [comment]
As a workaround, set `rbac.enabled=true` and then you can install the helm into its own namespace, e.g. `traefik` 

This is working for me without problems.

But you're right, you cannot choose namespaces that are not associated with your current project in rancher.

**Comment by etlweather** [comment]
I tried similar, installing it in the `kube-system` namespace by manually doing it through `kubectl apply` and it would never start any Traefik pods. I briefly [mentioned this here](https://forums.rancher.com/t/is-rancher-2-0-ready-for-primetime/10622/3?u=etlweather).

I'll have to try @dnauck 's workaround.

**Comment by tahoward** [comment]
I'm not having much luck getting traefik running either. Tried installing via catalog and I get a running pod but the 'Load Balancing' and 'Service Discovery' resources associated with traefik just sit at a pending state.

@dnauck I gave passing `rbac.enabled=true` as well with no change. (Assuming the "Answers" section of the catalog app form is correct location to populate this in.)

**Comment by dnauck** [comment]
I'm using the stable helm charts (you need to activate them in the rancher 2 catalog settings) with the following options:

https://gist.github.com/dnauck/0fc60f7241ee006199fb6a0130d76cba

**Comment by tahoward** [comment]
@dnauck Thank you! That got me quite a bit further but the pod is now complaining about port availability... How are you adding traefik listening on 80/443 when Rancher installs nginx-ingress on those ports by default? Is it safe to remove the default ingress service without breaking Rancher?

**Comment by dnauck** [comment]
@tahoward just remove the `ingress-nginx` namespace, it will remove everything. Then the traefik install works.

**Comment by tahoward** [comment]
@dnauck Not sure if this is Rancher or an issue with traefik helm template... I'm using dns-01 challenge type with the following options:
```
acme.challengeType=dns-01
acme.dnsProvider.name=cloudflare
acme.dnsProvider.cloudflare={"CLOUDFLARE_EMAIL":"email@domain.tld","CLOUDFLARE_API_KEY":"some_key"}
```
This results in the following error from kubectl:
`Kubectl apply failed. Error: Error from server (BadRequest): error when creating \"/tmp/app-template649676696\": Deployment in version \"v1beta1\" cannot be handled as a Deployment: v1beta1.Deployment: Spec: v1beta1.DeploymentSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: Env: []v1.EnvVar: v1.EnvVar: ValueFrom: Name: ReadString: expects \" or n, but found 0, error found in #10 byte of ...|[{\"name\":0,\"valueFro|..., bigger context ...|configfile=/config/traefik.toml\"],\"env\":[{\"name\":0,\"valueFrom\":{\"secretKeyRef\":{\"key\":0,\"name\":\"ingr|...\n: exit status 1`

The pretty formatted section it appears to complain about is here:
```
        env:
          - name: 0 #Guessing this line would be culprit
            valueFrom:
              secretKeyRef:
                name: ingress-traefik-dnsprovider-config
                key: 0
          - name: 1
            valueFrom:
              secretKeyRef:
                name: ingress-traefik-dnsprovider-config
                key: 1
```

**Comment by tahoward** [comment]
Ok, the `{}` symbol was misleading. I tried this with success:
```
acme.dnsProvider.cloudflare.CLOUDFLARE_API_KEY=key
acme.dnsProvider.cloudflare.CLOUDFLARE_EMAIL=email@domain.tld
```

**Comment by tahoward** [comment]
@dnauck Ok got the pod running but it appears the loadbalancer service just sits at pending still... Here are my settings:
```
dashboard.enabled=true
dashboard.domain=traefik.domain.tld
dashboard.auth.basic.admin=$apr1$some_pass
rbac.enabled=true
service.nodePorts.http=80
service.nodePorts.https=443
deployment.hostPort.httpEnabled=true
deployment.hostPort.httpsEnabled=true
ssl.enabled=true
ssl.enforced=true
acme.enabled=true
acme.email=email@domain.tld
acme.staging=true
acme.logging=true
acme.persistence.enabled=true
acme.persistence.size=1Gi
acme.persistence.existingClaim=acme
acme.challengeType=dns-01
acme.dnsProvider.name=cloudflare
acme.dnsProvider.cloudflare.CLOUDFLARE_EMAIL=email@domain.tld
acme.dnsProvider.cloudflare.CLOUDFLARE_API_KEY=some_api_key
```

**Comment by dnauck** [comment]
@tahoward do you mean the L4 LoadBalancer Service? That is also pending for me. But the normal L7 HTTP LoadBalancer/Ingress works fine.

**Comment by tahoward** [comment]
@dnauck Yes, can confirm traefik dashboard is working along with ingress routing even though L4 is pending. Thanks for your help!

**Comment by etlweather** [comment]
In terms of removing the `nginx-ingress`, you can disable it when creating your cluster by modifying the cluster's config in yaml:

```
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "none"
```

**Comment by superseb** [comment]
Thanks @etlweather , the docs on ingress controller can also be found here: https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/ingress-controllers/

We have https://github.com/rancher/rancher/issues/14007 open for additional providers.
