### ISSUE TITLE
400 null error when accessing /meta/proxy when logged in as an user from authentication provider which is a member of lots of groups

### ISSUE THREAD

**Issue by jrodonnell** [rancher/rancher#13920]
**Rancher versions:** 2.0
rancher/server or rancher/rancher: rancher/rancher

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.1

**Docker version: (`docker version`,`docker info` preferred)** 17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA via RKE

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Private GitHub authentication enabled, logged in via private GitHub and account has Administrator privileges
2. Add EC2 Template, copy & paste keys, click 'Authenticate and Select Network'

**Results:**
400: null error message.

### **Output to dev console:**
     General:
       Request URL: https://$RANCHER_FQDN/meta/proxy/ec2.us-west-2.amazonaws.com/
       Request Method: POST
       Status Code: 400 
       Remote Address: x.x.x.x:443
       Referrer Policy: no-referrer-when-downgrade

     Response Headers:
       content-length: 0
       content-type: text/plain; charset=utf-8
       date: Fri, 08 Jun 2018 21:07:46 GMT
       server: nginx/1.13.8
       status: 400
       strict-transport-security: max-age=15724800; includeSubDomains;

     Request Headers:
       :authority: $RANCHER_FQDN
       :method: POST
       :path: /meta/proxy/ec2.us-west-2.amazonaws.com/
       :scheme: https
       accept: */*
       accept-encoding: gzip, deflate, br
       accept-language: en-US,en;q=0.9
       content-length: 38
       content-type: rancher:application/x-www-form-urlencoded; charset=UTF-8
       cookie: CSRF=xxxxxxxxxx; R_SESS=token-jt9qx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
       origin: https://$RANCHER_FQDN
       referer: https://$RANCHER_FQDN/g/clusters/add?provider=amazonec2
       user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
       x-amz-content-sha256: xxxxxxxxxxxxxxxx
       x-amz-date: 20180608T210745Z
       x-amz-user-agent: aws-sdk-js/2.1.27
       x-api-auth-header: AWS4-HMAC-SHA256 Credential=$ACCESS_KEY/20180608/us-west-2/ec2/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=xxxxxxxxxxxx
       x-api-headers-restrict: Content-Length

     Request Payload:
       Action=DescribeVpcs&Version=2015-03-01

**Additional Notes:**
- Private GitHub is backed by Active Directory for authentication.
- Local admin account and other teammates logged in via GitHub can use the same AWS keys without issue.
- I have tried deleting all OAuth tokens and authorizations and retrying to no avail.
- Tore down and rebuilt Rancher instance, same problem.
- Removed the apostrophe from my name in GitHub, no change.
- Clearing browser cookies and cache also made no difference.

**Comment by superseb** [comment]
Reproduced on master 10/16 using Azure AD authentication, and using a non-admin user from an authentication provider to create a node template or EKS. Basically a call to `/meta/proxy/x` returns 400 where it does work for admins and local users.

**Comment by superseb** [comment]
This was reproduced using Azure AD authentication and reported using GitHub authentication. This does not seem to reproduce when using AD authentication

**Comment by superseb** [comment]
* Enable AzureAD with the admin user
* Add Cluster -> `From nodes in an infrastructure provider` -> EC2 -> Add Node Template
* Fill in Access key and Secret key -> Authenticate & Configure Nodes
* Pick AZ and subnet -> Select a security group
* Standard -> Set Instance Options
* Don't create, Click Cancel
* Logout and login as an user from AzureAD
* Try to do the same steps from Add Cluster, after filling in Access and Secret key and clicking Authenticate & Configure Nodes, it should show 400: null.

**Comment by mrajashree** [comment]
I have tried this with GH and Azure AD, but haven't been able to repro.

**Comment by mrajashree** [comment]
Seems to be because of AWS API header length max size getting exceeded by a header that has all user groups

**Comment by sangeethah** [comment]
Tested with master build from Nov 16.

Had Azure AD auth enabled with site access set to "Allow any valid user".

Log in as a user who is part of ~1000 groups.

Try to create EC2 node template.
Node template creation succeeded.

Also user is able to access clusters and project have access to one of the 1000 groups the user belongs to.
