### ISSUE TITLE
Can't create custom cluster on docker 18

### ISSUE THREAD

**Issue by erfanio** [rancher/rancher#13930]
**Rancher versions:**
rancher/rancher: latest
rancher/rancher-agent: v2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.947GiB
Name: toy
ID: G3CK:DUG4:KMOT:2D4X:7CQB:GSK4:67IE:MRO5:KF2C:KJ7T:YBQI:MLN5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.15.0-20-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Single VPS directly

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Create a custom cluster with 
`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.2 --server https://localhost --token xxx --ca-checksum xxx --etcd --controlplane --worker`

**Results:**
In the system logs keep getting
`Handler for POST /v1.24/containers/kubelet/start returned error: linux mounts: Could not find source mount of /var/lib/docker`
the UI it says
`[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [149.28.170.66]: Error response from daemon: linux mounts: Could not find source mount of /var/lib/docker`

**Comment by erfanio** [comment]
I've verified this on Arch Linux and Ubuntu. Same error with Docker 18.05.0-ce

Can't repro on Ubuntu and Docker 17.03.2-ce

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13888#issuecomment-396175861
