### ISSUE TITLE
Stuck on creating new host

### ISSUE THREAD

**Issue by brancusi** [rancher/rancher#1393]
Hi,

Trying to create a host on digitalocean and/or ec2.

Gets stuck on: "Waiting for agent connection"

Any ideas?

Thanks

**Comment by haswalt** [comment]
What version of rancher server? Where is the server running?

I'm assuming that this is an issue with the agent connecting to the web socket on the server

**Comment by bezelga** [comment]
I am having the same issue:

I am running the server in using boot2docker in my local machine.

It hangs forever on "Waiting for agent connection" 

Rancher	v0.25.0
Cattle	v0.58.0
User Interface	v0.29.0
Rancher Compose	latest

**Comment by bezelga** [comment]
tried running using Vagrant and:

signal: segmentation fault (core dumped)

**Comment by cjellick** [comment]
Hi @brancusi and @bezelga.
Can you provide a few more details?
1. Can you give us the output from: `docker logs --tail=500 rancher-agent`
2. Do you have a vanilla rancher setup where you just started rancher/server and then started rancher/agent or is your setup more complex involving load balancers or reverse proxies?

**Comment by bezelga** [comment]
@cjellick I can give more details between today and tomorrow.

For now I can answer this:

2) Vanilla rancher. without proxies nor reverse proxies.

I could successfully bring things up installing Rancher on Digital Ocean in ubuntu 14.04

:)

**Comment by keithricker** [comment]
Same thing here, running locally on boot2docker

**Comment by deniseschannon** [comment]
@keithricker  Can you give us the output from: `docker logs --tail=500 rancher-agent`? Did you change anything in your host registration set up?

**Comment by luiscape** [comment]
Hi folks, I'm afraid I am getting the same issue here, but trying to deploy / configure a new host on Digital Ocean. Here is my `docker logs -- tail=500` of my rancher container: 

```
time="2015-07-31T21:16:38Z" level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="ws://45.55.192.14/v1/subscribe?eventNames=physicalhost.create%3Bhandler%3DgoMachineService&eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService&eventNames=physicalhost.remove%3Bhandler%3DgoMachineService&eventNames=ping%3Bhandler%3DgoMachineService" 
time="2015-07-31T21:16:38Z" level=error msg="Unable to start EventRouter" Err="websocket: bad handshake" 
time="2015-07-31T21:16:38Z" level=info msg="Exiting go-machine-service..." 
time="2015-07-31T21:16:39Z" level=info msg="Setting log level" logLevel=info 
time="2015-07-31T21:16:39Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-07-31T21:16:39Z" level=info msg="Initializing event router" workerCount=10
``` 

On my case no new droplets were created on Digital Ocean.

**Comment by cjellick** [comment]
@luiscape How do you have things configured such that you have rancher running on port 80 as opposed to 8080? Are you using a proxy in front rancher?

If so, that could potentially be causing problems. If you are, what kind of proxy?

**Comment by luiscape** [comment]
Hi @cjellick thanks for getting back to me -- appreciated!

I'm using a `nginx` proxy that sends all the traffic from / to :8080. Is that causing issues?

**Comment by cjellick** [comment]
Well, we just fixed a number of proxy related bugs in this weeks release, so it could very well be related to that. Later today we'll be tagging this release as latest in Docker Hub.

Would you be willing to share your nginx configuration? Feel free to remove any sensitive bits like IPs, but imparticularly interested in what headers you're setting and how you're forwarding the request.

**Comment by luiscape** [comment]
Hi @cjellick, I think this is the relevant bit: 

```
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /var/www/rolltime-server;

        server_name 45.55.192.14;

        location / {

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header HOST $http_host;
            proxy_set_header X-NginX-Proxy true;

            proxy_pass http://127.0.0.1:8080/;
            proxy_redirect off;
       }
}
```

**Comment by luiscape** [comment]
Hi @cjellick, I changed the `nginx` configuration and got rid of the reverse proxy. It didn't work immediately after the change. But I installed a new docker container with Rancher on the same server and it did seem to connect with Digital Ocean without issues. Let me know if I can provide some more information.

**Comment by boedy** [comment]
I ran into this error myself, but this had to do with me overlooking this part in the documentation:

> The IP of the machine will need to be public and accessible from the internet in order for Rancher to work.

**Comment by deniseschannon** [comment]
If anyone is still having this issue, please re-open a new ticket.

**Comment by ericvolp12** [comment]
This is an issue with Websocket connections.

You need to add the following fields into your reverse proxy config inside the server block:
```
location / {
                proxy_pass <ip of server and port>
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
}
```
