### ISSUE TITLE
Add more documentation for developers of Rancher 2

### ISSUE THREAD

**Issue by jomeier** [rancher/rancher#13933]
I'd love to contribute to this project but reverse engineering through the code is horrible :-) The Rancher 2 architecture document is a minimal starting point for getting a feeling how the API might work.

The last days I worked on documentation and a few scripts which enable me to remote debug Rancher 2 from a GO IDE. I created a pull request for that:

https://github.com/rancher/rancher/pull/13932

Please please please create more documentation about how Rancher 2 works, how we can contribute to fix bugs and enhance it. Maybe it's also a good idea to create a Slack channel for Rancher Developers.

This project is awesome and we want to get our hands on it. Give us more documentation, please :-) !

Josef

**Comment by jomeier** [comment]
In the mean time I try to add documentation in this place:

https://github.com/jomeier/rancher-2.x-development/tree/master/debugging

**Comment by superseb** [comment]
Thanks for the PR. Docs reside in https://github.com/rancher/docs and won't be added in this repository. Slack developers channel is `#developers`. Parts of running/debugging should be in https://github.com/rancher/rancher/wiki/Running-and-debugging-Rancher-2.0-from-an-IDE I believe.

For the content, ping @cjellick @ibuildthecloud @alena1108

**Comment by jomeier** [comment]
@superseb 
Thanks for your response. To be honest that's not the answer I was hoping for :-)

As far as I know, rancher/docs is for user documentation only. The content in the wiki is super old and rather unstructured.

Where can we add scripts which are used for debugging? Some of them are also in my PR and they, in my opinion, belong into this repository.

Thanks for the advice about the developers channel. I was eager to read about rancher's development secrets but the last entry is from May 21th :-(

But I don't give up and will contact the team members like you suggested.

**Comment by cjellick** [comment]
@maxkorp can you open a corresponding issue in the docs repo

**Comment by loganhz** [comment]
closed in favor of https://github.com/rancher/docs/issues/927
