### ISSUE TITLE
Launch kubectl security issues

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#13938]
Currently found UI Launch kubectl This is connected to the cattle-node-agent pod perform kubectl command, but because this pod is a privileged pod, need kube-apiserver permission privileged pod exec permissions, remove the DenyEscalatingExec parameters, If these containers are compromised, An attacker can easily compromise the underlying host. Given that particular pods require privileged access, can you make some changes to Launch kubectl?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13612
