### ISSUE TITLE
rancher pipeline

### ISSUE THREAD

**Issue by ycwmuyi** [rancher/rancher#13935]
*Describe your issue here*
k8s + rancher2.0  pipeline only support gitbub？
I can not add gitlab,have any other way to add gitlab for pipeline 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/12608
