### ISSUE TITLE
all nodes is not active

### ISSUE THREAD

**Issue by Fisher-Joe** [rancher/rancher#13939]
**Rancher versions:**
rancher/server or rancher/rancher:2.0.2
rancher/agent or rancher/rancher-agent:2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.31.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubunut 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-v
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
![image](https://user-images.githubusercontent.com/12068896/41220946-612a0118-6d95-11e8-9901-c0e535775283.png)

![image](https://user-images.githubusercontent.com/12068896/41220988-8023a600-6d95-11e8-84ec-67d41d292205.png)

**Comment by massimo-cannavo** [comment]
Looks like a networking issue. Do you by chance have a firewall enabled like iptables? Can you check your established connections?

netstat -an | grep ESTABLISHED

**Comment by aemneina** [comment]
probably doesnt hurt to share rancher server logs @Fisher-Joe

**Comment by Fisher-Joe** [comment]
I reinstall them and wait a long time , they are ok.

**Comment by quqonlik** [comment]
I have the same issue . Node is not active. Does reinstalling cluster resolves the issue? I'm not running firewalld or selinux on CentOS7 vm box

**Comment by JyotiVashisth** [comment]
I have the same issue, reinstalling rancher did not help.

**Comment by nishit93-hub** [comment]
Hi all,

I have the Same issue. 2 nodes are not active. Please guide me how should i resolve this
![Screenshot from 2020-12-17 21-47-44](https://user-images.githubusercontent.com/64061293/102513903-d2812480-40b1-11eb-81d8-dfc388512cd3.png)
