### ISSUE TITLE
kubelets not restarted if Azure cloud-provider is updated

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#13945]
**Rancher versions:**
rancher/rancher: v2.0.2

**Steps to Reproduce:**
In GUI, Edit the Cluster and Update Azure Cloud-Provider setting.
Save changes.
The new config gets written, but the kubelets don't get restarted to pick up the changes in the config.

**Comment by jgreat** [comment]
Workaround:  SSH into the nodes and restart the kubelet container.

```
docker restart kubelet
```

**Comment by bmdepesa** [comment]
Currently blocked from testing by #14097

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/20

Kubelet is not restarted when cloud-config is updated. 

Created Azure cluster with cloud provider
Updated cloud config
Cluster is updated, and new cloud-config is written; but kubelet is not restarted. 

`sudo docker ps` on the Azure node shows kubelet as been created 15 minutes ago and up for 15 minutes. After running `sudo docker restart <kubelet>`, `docker ps` shows created 15 minutes ago and up for some seconds.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.0.3-rc2

Kubelet gets restarted after updating cloud-config
