### ISSUE TITLE
Notify users that Elasticsearch endpoint has to be an URL

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13943]
Version: 6/11

Elasticsearch endpoint is using URL parsing, but is not notifying users when a non URL is entered in the field, only on Save/Submit.

<img width="689" alt="screen shot 2018-06-11 at 21 55 32" src="https://user-images.githubusercontent.com/2620179/41253994-53be273e-6dc2-11e8-894b-34d87e900146.png">

**Comment by aiwantaozi** [comment]
@n313893254 Can we check when user input the endpoint url?

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
