### ISSUE TITLE
[cli] kubectl not found in docker image

### ISSUE THREAD

**Issue by zhangyelong** [rancher/rancher#13949]
**Rancher versions:**
rancher/cli: v2.0.2-rc1

**Steps to Reproduce:**
```
docker run --rm -it -v <PATH_TO_CONFIG>:/root/.rancher/cli2.json rancher/cli kubectl
```
**Results:**
FATA[0000] kubectl is required to be set in your path to use this command. See https://kubernetes.io/docs/tasks/tools/install-kubectl/ for more info. Error: exec: "kubectl": executable file not found in $PATH

**Comment by massimo-cannavo** [comment]
I had the same issue and this worked for me.

wget https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubectl

```
docker run -it \
  -v /root/.rancher/cli2.json:/root/.rancher/cli2.json \
  -v /root/kubectl:/usr/local/bin/kubectl \
  rancher/cli:v2.0.2-rc1  kubectl
```

Basically kubectl is missing from the docker image and therefore fails.

https://github.com/rancher/cli/blob/master/cmd/kubectl.go#L28

**Comment by fabn** [comment]
Any news on this? It's pretty useless to have a rancher/cli2 image without kubectl

**Comment by fabn** [comment]
There are a lot of attempts to have this: https://hub.docker.com/search?q=rancher-cli-k8s&type=image but having an official one **is** the way.
