### ISSUE TITLE
Azure cloud-provider requires extra permissions to use AzureFiles 

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#13947]
Not sure this is truly an issue with Rancher, seems like the cloud-provider should do this for you, but I know our users are going to trip over this.

To dynamically configure AzureFiles volumes, the provider/controller needs permissions to create a secret to store the share credentials in the namespace the pvc was created in.

```
kubectl create clusterrole system:azure-cloud-provider --verb=get,create --resource=secrets
kubectl create clusterrolebinding system:azure-cloud-provider --clusterrole=system:azure-cloud-provider --serviceaccount=kube-system:persistent-volume-binder
```

Related issues:
https://github.com/kubernetes/kubernetes/issues/59543

Related documentation:
The storageClass docs sort of mention that this is required as a side note.
https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file

**Rancher versions:**
rancher/rancher: v2.0.2

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/docs/issues/928
