### ISSUE TITLE
Manage data only containers via Rancher UI

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#1395]
Would be great do simplify the data only container usage and also add data only container to services.

With the rancher ui we can add volumes and also volumes from an existing container.
What do you think about a additional checkbox "make persistent" next to the "volumes" ? In the background a data only container could be created with the name "<container-name>Storage" for example? It would make storage and app container creation to one step via rancher ui.

A auto created data only container should also added to the "volumes from" dropdown to reuse with other containers.

**Comment by cjellick** [comment]
@will-chan Can you review and let me know if this is a feature we want to add?

**Comment by cjellick** [comment]
With the newly added docker and rancher volume APIs, the implementation of this might shift away from a data only container and to simply creating a volume.

**Comment by pwFoo** [comment]
Is it a convoy plugin (VFS, DM) based solution? 
Waiting for such a integration in Rancher / RancherOS ;)

**Comment by cjellick** [comment]
@pwFoo yes, it would be a convoy plugin based solution.
Currently, we have glusterfs + convoy integration with rancher. nfs is next.

**Comment by pwFoo** [comment]
But what is about a single host (RancherOS) / local storage solution? No need for glusterfs, just local, persistent storage ;)
Convoy support all needed features (dm, vfs, backup & restore).

In the future a ceph backend could be needed, but no prio at the moment.

**Comment by pwFoo** [comment]
Hi @cjellick 
any information about a convoy vfs / dm implementation?
To prepare my first (production) environment local persistent storage is needed. 
So if there is a timeline a release date would be great to know :)

**Comment by cjellick** [comment]
WIP PRs are in @pwFoo:
https://github.com/rancher/convoy-agent/pull/14
https://github.com/rancher/rancher-catalog/pull/63
Need a little refinement, but generally looking good.

Should be out pretty soon. This week or next at the latest.

**Comment by will-chan** [comment]
We have new volume implementations since 1.2.x.  If this does not solve what you want, please reopen.
