### ISSUE TITLE
 it’s not possible to select a container if they are several

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rancher#13951]
it’s not possible to select a container if they are several, instead it selects one of them automatically. So we can't select another one and execute a shell for instance.
<img width="1271" alt="screen shot 2018-06-12 at 4 39 38 pm" src="https://user-images.githubusercontent.com/16855630/41294469-2b36b144-6e69-11e8-98b4-c874247e2b58.png">

V2.0.2

**Comment by superseb** [comment]
You can select `Execute Shell` and then switch to other containers on top of the new window.

<img width="306" alt="screen shot 2018-06-12 at 16 14 44" src="https://user-images.githubusercontent.com/2620179/41295845-d4c7b554-6e5b-11e8-8c5f-6ccbd5b35185.png">

**Comment by harutyundermenjyan** [comment]
I've tried it but the doesn't open the window you've mentioned in order to switch
<img width="1237" alt="screen shot 2018-06-12 at 6 35 20 pm" src="https://user-images.githubusercontent.com/16855630/41297196-adc1aa8c-6e6f-11e8-8471-98391c9187b1.png">
<img width="1276" alt="screen shot 2018-06-12 at 6 36 56 pm" src="https://user-images.githubusercontent.com/16855630/41297198-adec2aaa-6e6f-11e8-9788-a4c736c8ca3e.png">

**Comment by harutyundermenjyan** [comment]
https://github.com/rancher/rancher/issues/13958
