### ISSUE TITLE
aws node stuck in "Removing"

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#13968]
Version: 2.0.2

Create AWS node template with private IP so that it cannot be reached by the rancher/server. Launch an instance in a cluster. This node would be stuck in "Waiting for SSH". Now delete the node pool followed by deleted of the node. Then it's stuck in "Removing".

<img width="599" alt="screen shot 2018-06-12 at 10 57 15 pm" src="https://user-images.githubusercontent.com/19392926/41332751-003761a2-6e94-11e8-9f22-c39dedee1649.png">

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13668
