### ISSUE TITLE
Increased timeouts, dropped connections and response time during deployment changes

### ISSUE THREAD

**Issue by tachu** [rancher/rancher#13964]
**Rancher versions:**
Rancher server 1.6.16
rancher/lb-service-haproxy:v0.9.1

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.6
ipsec:
network-services: rancher/net:v0.13.11
rancher/network-manager:v0.7.20
scheduler:
rancher/agent:v1.2.10
kubernetes (if applicable): 1.8

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 19
 Running: 19
 Paused: 0
 Stopped: 0
Images: 46
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 264
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.769 GiB
Name: csra-lb1-2
ID: 2ZIQ:E7ZK:4EAX:JRNE:KHVC:T6FQ:WMX7:2B2R:HH44:PUPG:MGCW:OGAF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: opscrowdstar
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-109-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
BareMetal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher 
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Setup LB ingress type haproxy
setup deployment with container running web application that echo's a value via php
setup load testing via siege, ab or loader.io to hit ingress endpoint

do any of the following

Delete 1 web container from replicaset
scale up replica set
scale down replica set 

**Results:**
increased timeouts and dropped connections during deployment changes

Expected result:
No dropped connections or timeouts 

as a test we have done the following:

go into haproxy container

restart haproxy several time with no dropped connections
restarted haproxy to remove one container from pool (equivalent to scale down) with no dropped connections
restarted haproxy to add the container back to the pool(equivalent scale up) no dropped connections or timeouts

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
