### ISSUE TITLE
Rancher/ONAP collaboration: increase --max-pods kublet config via rancher agent config - via automated docker param

### ISSUE THREAD

**Issue by obriensystems** [rancher/rancher#13962]
**Rancher versions:**
rancher/server or rancher/rancher:
1.6.14
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
1.8.10

**Docker version: (`docker version`,`docker info` preferred)**
17.03
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
any (openstack, aws, azure)
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
https://git.onap.org/logging-analytics/tree/deploy/rancher/oom_rancher_setup.sh

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes
**Steps to Reproduce:**
attempt to deploy more than 110 pods
**Results:**
init state on remaining pods

see details - we need an automated way to pass in the max-pods parameter so we can retrofit the rancher installation script to handle a single node deployment of ONAP (currently over 200 pods)
https://jira.onap.org/browse/OOM-1138

Note: this is after a discussion with your C* suite executives on 20180612 on increasing onap/rancher collaboration
https://jira.onap.org/browse/OOM-1138
We hit the 110 kubernetes default pod limit a couple months ago - although we recommend clustering we should have an option to run a cluster node with more than 110 pods - we currently have 210 - when we reach 300+ on a 3 node system we will need this.

Work with Rancher labs to enable the --max-pods kubelet config for when we reach 300+ per 3 node cluster

The setting is on the kublet - I spend about 10 min researching how to add this as a config option to the rancher-agent docker - but could not find a way to pass in the parameter
https://lists.onap.org/pipermail/onap-discuss/2018-June/010246.html
https://github.com/kubernetes/kubernetes/issues/23349

**Comment by obriensystems** [comment]
https://lists.onap.org/pipermail/onap-discuss/2018-June/010282.html

**Comment by obriensystems** [comment]
{noformat}
kubectl describe node

Capacity:
 cpu:     16
 memory:  125827328Ki
 pods:    110
Allocatable:
 cpu:     16
 memory:  125724928Ki
 pods:    110

{noformat}

**Comment by superseb** [comment]
Anything else needed on this?

**Comment by obriensystems** [comment]
(+) procedure
https://wiki.onap.org/display/DW/Cloud+Native+Deployment#CloudNativeDeployment-Changemax-podsfromdefault110podlimit
Manual procedure: change the kubernetes template (1pt2) before using it to create an environment (1a7)

add --max-pods=500 to the "Additional Kubelet Flags" box on the v1.10.13 version of the kubernetes template from the "Manage Environments" dropdown on the left of the 8880 rancher console.
