### ISSUE TITLE
Why isn't the org rancher?

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#1396]
@rancher I was wondering if you would be willing to transfer ownership of your account (@rancher) to the Rancher Labs team building the Rancher open source project?  I see your account was opened January of 2014 and has no public activity.  We would greatly appreciate being able to use the @rancher account for Rancher Labs.  Please contact me at darren@rancher.com  Thanks so much!

**Comment by thaJeztah** [comment]
:+1: that would be really awesome, thanks in advance for considering, @rancher!

**Comment by deniseschannon** [comment]
+1

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/8602617/11ad372a-2628-11e5-84b2-3f724d4b6da3.png)

**Comment by thaJeztah** [comment]
Oh, wow, thanks so much to "the person previously known as @rancher"!

**Comment by vincent99** [comment]
@thaJeztah Thank the GitHub inactive accounts policy :smile:

**Comment by thaJeztah** [comment]
Ah, whatever worked then :+1:  thanks @GitHub
