### ISSUE TITLE
Rancher server leaves lots of docker-machine defunct child processes

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13971]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Docker version: (`docker version`,`docker info` preferred)** 17.03

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

Add openstack provider and create clusters.

**Results:**

We have tons of defunct processes for docker-machine in our enterprise environment.

I only have very few users and very few clusters being created so far, yet it goes crazy.

I believe this happens each time docker-machine encounters some HTTP errors from openstack apis, which could come from either bad config from the user, quota issues when creating resources, or temporary network glitches.

```
root@cattle-f88b55866-gdpll:/var/lib/rancher# uptime
 15:08:35 up 9 days,  1:54,  0 users,  load average: 0.03, 0.19, 0.25
root@cattle-f88b55866-gdpll:/var/lib/rancher# ps auxw | grep docker-machine | grep defunct | wc -l
14324
root@cattle-f88b55866-gdpll:/var/lib/rancher# ps auxx | head
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  8.2  7.6 4046380 2343560 ?     Ssl  Jun11 227:45 rancher --http-listen-port=80 --https-listen-port=443 --no-cacerts
root        30  0.0  0.0      0     0 ?        Z    Jun11   0:00 [git-remote-http] <defunct>
root        32  0.0  0.0      0     0 ?        Z    Jun11   0:00 [git-remote-http] <defunct>
root        51  0.0  0.0      0     0 ?        Z    Jun11   0:00 [docker-machine] <defunct>
root        56  0.0  0.0      0     0 ?        Z    Jun11   0:00 [docker-machine] <defunct>
root        66  0.0  0.0      0     0 ?        Z    Jun11   0:00 [docker-machine] <defunct>
root        73  0.0  0.0      0     0 ?        Z    Jun11   0:00 [docker-machine] <defunct>
root       120  0.0  0.0      0     0 ?        Z    Jun11   0:00 [docker-machine] <defunct>
root       134  0.0  0.0      0     0 ?        Z    Jun11   0:00 [docker-machine] <defunct>
```

Almost 15k is enormous for just 9 days.
Obviously this becomes a problem as we get near the max pid limits in the container:

```
root@cattle-f88b55866-gdpll:/var/lib/rancher# sysctl kernel.pid_max
kernel.pid_max = 32768
```

**Comment by alexandrem** [comment]
Actually the `uptime` above is a syscall to the underlying host.

In reality, this container and rancher process has only been running for 2 days as shown in the ps.

**Comment by superseb** [comment]
Sounds like re-introduced behavior from https://github.com/rancher/rancher/issues/12365

**Comment by deniseschannon** [comment]
@alexandrem let me know if you are still hitting these in a more recent releases.
