### ISSUE TITLE
No way to add taints to nodes

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13972]
Background:

There doesn't seem to be any way to add taints in Rancher or RKE at the moment.

Ideally, we should be allowed to define this in the node template.

If someone wants to create dedicated load balancer (e.g ingress controllers) nodes, then we can't mark those nodes with taints and use tolerations for specific workloads. 

This becomes a pain because you have to do this afterwards with `kubectl`, but you needlessly need to change taints to NoExecute to evict some containers that have been scheduled automatically to the nodes, where it should have been prevented at creation time.

Expected:

- [x] Support taints for node pool
- [x] Support taints for node template
- [x] Support taints for node
- [x] Support taints when adding custom node
- [x] Show taints in node list
- [x] Support adding tolerations when enable istio and monitoring for workloads

**Comment by ekristen** [comment]
Please add this. I too would have the need to restrict what runs on what workers, not being able to do taints from within Rancher or the Node Templates makes this more difficult to manage.

**Comment by ekristen** [comment]
@deniseschannon since you removed 2.0 version does that mean this isn't coming anytime soon?

**Comment by vincent99** [comment]
It means nothing.  We're going through issues and removing the `version/2.0` label while doing so because (it's no longer 2.0 and) that's now the implied default instead of labeling both 1.x and 2.x.

**Comment by garyhuang123** [comment]
I'm using vsphere providers in Rancher 2.2.1. Every time when i upgrade a node, i need to re-taint the node. It should be allowed to specify taints on nodetemplate. Mark this up!

**Comment by loganhz** [comment]
The following stuff will be added in 2.3. Please let me know if we missed some requirements.

- Support taints for node pool
- Support taints for node
- Support taints when adding custom node
- Show taints in node list
- Support adding tolerations when enable istio and monitoring for workloads

**Comment by ekristen** [comment]
@loganhz those sound great! Thanks for the hard work.

**Comment by sangeethah** [comment]
Tracking validation for  - `Support adding tolerations when enable istio and monitoring for workloads` - https://github.com/rancher/rancher/issues/21487#issuecomment-527530723 and https://github.com/rancher/rancher/issues/22606

**Comment by sowmyav27** [comment]
Verified on `master-head` the following scenarios.
The basic tests cases are working fine.
Any specific issue has been logged as a bug and is being tracked separately.

- Support taints for node pool
- Support taints for node template
- Support taints for node
- Support taints when adding custom node
- Show taints in node list
