### ISSUE TITLE
Creating a cluster using Import returns empty cluster screen

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13976]
Version: master 6/13

Steps to reproduce:
1. Create cluster
1. Choose Import

Result:

<img width="842" alt="screen shot 2018-06-13 at 18 15 36" src="https://user-images.githubusercontent.com/2620179/41364110-f0ebbef8-6f35-11e8-8521-ad9120b6c9bd.png">

**Comment by loganhz** [comment]
Fixed  in https://github.com/rancher/ui/pull/1943
Please try `rancherrancher/master`

**Comment by superseb** [comment]
Version: master 6/19

Screen with command correctly shows after creating cluster type Imported
