### ISSUE TITLE
Add sticky session example for Rancher ingress

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13974]
Rancher HA documented as of today doesn't work if you increase the replica count of the Rancher server deployment.

I'm not sure if this is entirely supported, but I would expect the Rancher server to be stateless and work well if there's more than one instance running (although I'm not quite sure for the docker-machine provisioning, I hope there's some leader election in place).

As soon as we increase the replica count, Rancher UI sessions will show errors as you navigate from page to page or with the auto-refresh. I believe the agent components will also constantly lose their secure websocket connection to the server URL.

This can easily be solved via some sticky session attributes to the nginx ingress provided as an example.

New annotations to add:
```
nginx.ingress.kubernetes.io/affinity: "cookie"
nginx.ingress.kubernetes.io/session-cookie-name: "route"
nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
```

Current doc: https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/

**Comment by superseb** [comment]
This can be merged into https://github.com/rancher/rancher/issues/13292, where running multiple instances is fixed and docs/examples will be updated when testing is complete.
