### ISSUE TITLE
Users can temporarily see node templates from other users/groups

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13978]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** centos-7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA Rancher

**Authentication**: Active Directory

**Steps to Reproduce:**

Authenticate with an Active Directory user in Rancher UI.

Click around the UI pages and go to the Rancher UI "Node Templates"

Or

Go to the cluster creation page in the node pools section, and open the "Template" dropdown.

**Results:**

From time to time, after loading the node templates page you can see the list of all node templates created by other users. Refreshing the page will fix it and show only those that you have permissions to see.

It also happens in the cluster creation node pools "Template" dropdown, where all templates in the system will be listed.

It's not possible to view the node template api object using your current Rancher UI session token however.

If the user selects a node template that he doesn't own, then creation of the cluster will fail with "nodepools.management.cattle.io" permission error.

This creates confusion to some end users who see their cluster create requests failing with a cryptic error message if they selected a bad template.

**Comment by jannylund** [comment]
I see the same issue. (same rancher version, standalone host on aws/ec2/ubuntu and local users)

**Comment by loganhz** [comment]
I can reproduce this issue in v2.0.4

Steps:

1. Login as admin.
2. Create a admin user  `user1`.
3. Login as user1 in a new bowser window.
4. Go to note templates page for both `admin` and `user1`.
5. Create a new node template in `admin` account.

Results:

You will be able to see the newly created node template is showing for both `admin` and `user1`.
If you refresh your bowers, it will only show in `admin` account.

Reason:

Server publishes the newly created node template to UI via websocket.  This is wrong as it is not created by `user1`. Server should not push it to UI.

**Comment by cjellick** [comment]
Thanks for the analysis @loganhz. Will get it fixed

@jannylund you're request is captured here: https://github.com/rancher/rancher/issues/12186

**Comment by nathan-jenan-rancher** [comment]
me to validate

**Comment by nathan-jenan-rancher** [comment]
Test steps taken:
1. Started rancher with `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master`.
2. Created admin user `user1`
3. Opened a separate browser window and logged in as `user1`
4. Navigated both browser windows to the node template tab
5. As `user1`, created a new node template
6. As `admin`, created a new node template
7. Verified that neither user could see the other's node template at any time
