### ISSUE TITLE
Ability to configure cluster CIDR for service/pods

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13988]
There is no way at the moment in the Rancher UI to configure cluster networking details, such as the cluster service cidr, pod cidr and kube dns service ip.

It is possible to do this via the API, but it would be nice to expose this in the UI as well.

**Comment by superseb** [comment]
It can be done in the API and using RKE and importing that cluster as of today, for next releases it's covered in https://github.com/rancher/rancher/issues/13076
