### ISSUE TITLE
Ability to create private clusters in GKE

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#13980]
Add the ability to create private clusters in GKE.  Need to be able to specify the master IP range as well when private cluster is selected.

**Comment by jiaqiluo** [comment]
Rancher got the private cluster provisioned successfully, but Rancher cannot connect to the cluster with the following error message showing. Do I need to run Rancher in the same VPC as the private cluster?  
<img width="1400" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52821959-9e7be900-306d-11e9-93f0-96346fcc5c4e.png">

**Comment by fyery-chen** [comment]
@jiaqiluo you should install rancher in the same VPC and zone with the cluster, and you should enable master authorized network to add a cidr block rancher server belongs to.

**Comment by jiaqiluo** [comment]
The feature is validated on Rancher: master 2/14

Steps:
- create a VPC on Google Cloud
- install Rancher in the VM running in the VPC
- added a GKE private cluster from Rancher UI

Result:
- the GKE private cluster is provisioned successfully  in Google Cloud 
- Rancher shows the status of the cluster properly and can access to the cluster
