### ISSUE TITLE
Cloud provider name is not a mandatory field

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13985]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2

**Cloud provider:** openstack

The "Cloud Provider Name" field that appears in the "Custom" cloud provider in "Cluster Options" is not mandatory, but we can enter the ful key/value pairs in the form below.

If you leave this empty by mistake, then the provisioning will succeed but the kubelet will have the `--cloud-provider= ` parameter empty. A cloud-config file will be generated on disk. 

What this means is that the kubelet is not registered with the cloud provider, although the end user will believe it is during the creation.

This should be a mandatory field in the Rancher UI and also validated in the API for the `rancherKubernetesEngine` `cloudProvider`.

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13115 and https://github.com/loganhz/ui/commit/dd966e3e619c4ac6a161b70bc0e9ec9c964f71de, this will be removed in the next release.
