### ISSUE TITLE
[2.0] Question about domain proxy

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#13997]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: as deployed

Hello. I have a question about LB proxy like at 1.6 version.
How to deploy an LB on a single port, where I can request on different domains and it will point to different services like it was on 1.6 version? For now, every endpoint listens on its own port.

**Comment by loganhz** [comment]
duplicated of https://github.com/rancher/rancher/issues/13711

now rancher supports node selector. Please see https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/ingress-controllers/

**Comment by clicman** [comment]
@loganhz But it creates random ports on front ip even I create all targets on single lb.
But I suppose to get one public port for all targets

**Comment by loganhz** [comment]
Hi @clicman, please look at the issue https://github.com/rancher/rancher/issues/13717
We will track the random ports issue there.
Please feel free to leave your comment in that issue.
Close this issue.
