### ISSUE TITLE
Use rancher container name as docker container name on host

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1399]
The actual name of docker containers on hosts is currently the rancher UUID. Now that we have docker labels, we can store the rancher UUID in a label and name the docker container with the same name the user gave it in rancher (with some caveats, see below).

Caveat: we still need to ensure uniqueness because docker requires name uniqueness. So, the implementation will need to make a "best effort" to match the name.

This was originally enumerated as a feature in the native-docker meta-issue but was not implemented in the original implementation and was never broken out into its own issue.

**Comment by pwFoo** [comment]
Container name should be used as rancher instance name. Console created container should be imported to Rancher and named by "docker --name" param.
So it should be simple to work with rancher and also native docker via console.

**Comment by gordontyler** [comment]
This makes it less easy to use rancher and the docker CLI interchangeably. For example, I would use Rancher to start some persistent containers running services (e.g. zookeeper and kafka), but while testing I would use the docker CLI to run my test app with links to the service containers. Having to query docker to see what the UUIDs are for the service containers to use in the --link option is awkward

**Comment by cicerocomp** [comment]
follow :+1:

**Comment by xaka** [comment]
I'll buy you :beers: and :chocolate_bar: guys, please implement and send you mailing address! Isn't it matter of passing an extra parameter to Docker API?

**Comment by thaJeztah** [comment]
Alternatively, store the rancher name in a label; note that work is started in docker to support mutable labels on containers, which would allow renaming the container in Rancher and updating the label on the container; https://github.com/docker/docker/issues/15496#issuecomment-167045503

**Comment by asciifaceman** [comment]
+1 this will be a hard requirement for my team to deploy Rancher wide-band

**Comment by vsangal** [comment]
+1

**Comment by yamaszone** [comment]
+1

**Comment by ibuildthecloud** [comment]
As a compromise right now we can name containers as `r-{name}`.  So if the name in rancher is foo, a `docker ps` would show the container r-foo.  The reason we are doing the `r-` prefix is to protect ourselves from conflicts between `/etc/hosts` and our DNS management.  Given the Docker version and the networking mode, Docker will edit `/etc/hosts` in the container.  It is possible that we get a name in `/etc/hosts` that overrides a name in our DNS.  Using the `r-` prefix will work around this.  Hopefully this is an acceptable compromise.

**Comment by asciifaceman** [comment]
That's absolutely fine for me. We just need something predictable :)
Thank you rancher team

**Comment by bibby** [comment]
Upgraded containers still get a uuid assigned.
I wasn't expecting the new containers to take on the predictable name (as it is taken), but might be worth mentioning.

**Comment by cjellick** [comment]
Yes, if the predictable name is taken, we just fall back to the uuid.

When you say upgraded containers, you mean you performed a stack upgrade?

**Comment by bibby** [comment]
That's correct, @ccjellick; a. stack upgrade to force-pull an image I was iterating on.
Specifically, an [nginx-proxy](https://github.com/jwilder/nginx-proxy) that reloads a specific container name, for which there is [an issue for that](https://github.com/jwilder/docker-gen).

It seems that as a general pattern, where ever possible, that container names shouldn't matter -- *until they do*.

For my case above, a _sticky_ name might have worked. But I have no clue how something like that would affect some other composed stack. As more patterns built around labels become prevalent, this may become less of an issue.

To be clear, I have no immediate needl just joining the discussion. Thanks!

**Comment by goffinf** [comment]
I also need to link containers using --link. I note here the workaround mentioned by Darren but I can't find an explanation of how to implement it. Can someone please explain how I can set a container name albeit with a 'r-' prefix ?

I can see the io.rancher.container.name in docker inspect, but that does not work when using docker run --link <cont-name>:alias  AFAICT ?

**Comment by deniseschannon** [comment]
If you are using v1.1.0, we automatically have prefaced the names of any containers started in Rancher with `r-`

**Comment by fenchu** [comment]
Using jenkins pipelines with docker-compose internally for testing, but I'm unable to get this to work in prod where we have rancher, due to rancher-compose not honoring container_name tag. Please make sure rancher-compose supports docker-compose, otherwhise there will be lots of issues with other orchestration software.

https://github.com/rancher/rancher/issues/6791
