### ISSUE TITLE
Receiver Hook Feature

### ISSUE THREAD

**Issue by alexwiedermann** [rancher/rancher#13991]
This built-in feature from rancher 1.6 do not exist anymore in rancher 2.0.2 (present latest).

**Comment by manueldelreal** [comment]
I second this. For what I'm doing setting up a separate solution to upgrade the workloads every time an image change happens on the docker registry seems like overkill, having the receiver webhooks functionality back would be ideal just to set one per workload and forget it

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13475
