### ISSUE TITLE
Missing documentation for TCP port 2376 inbound rule

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13990]
The Rancher documentation lacks mention of the required inbound TCP port 2376 that is needed to provision nodes using the `rancherKubernetesEngine` on different providers (e.g openstack).

Not opening this will prevent the Rancher server dial connection to the remote docker daemon.

**Comment by alexandrem** [comment]
It should be added here https://rancher.com/docs/rancher/v2.x/en/installation/references/

**Comment by superseb** [comment]
This is being fixed in https://github.com/rancher/docs/issues/267
