### ISSUE TITLE
2 nodes with same hostname bug

### ISSUE THREAD

**Issue by Razikus** [rancher/rancher#13999]
Rancher versions : 2.02
Docker version: (docker version,docker info preferred) 17.03.2-ce
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
4.9.0-6-amd64
same hostname

**Steps to Reproduce:**
1. Create custom cluster
2. Make sure that your nodes have same /etc/hostname
3. Add first node with role ALL and hostname example (ip 192.168.0.1)
4. Add second node with role WORKER and hostname example (ip 192.168.0.2)

**Results:**
There will be node example with ip 192.168.0.1 (first node) and role WORKER. Cluster will be **active**!

**Comment by antoniojtorres** [comment]
+1 - Using bare metal servers that come with the same hostname from image caused this as well, once I edited the host file and rebooted, I was able to add a second custom node without issue.

**Comment by FinlayDaG33k** [comment]
@antoniojtorres that seems to be a working band-aid.
For those using `RancherOS` this can be done using `sudo ros config set hostname <hostname>` followed by a reboot.

**Comment by galal-hussein** [comment]
@Razikus kubernetes can't have duplicate node names, you can however append the option `--node-name` to the registration command to include the node name, for example:
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:master --server https://x.x.x.x --token xxxxxx --ca-checksum xxxxx --etcd --controlplane --worker --node-name <node-name>
```
@loganhz i am assigning the issue to you so that the option can be included to the UI like the `Public Address` and `Internale Address`

**Comment by soumyalj** [comment]
Tested with master. The UI has option to add node name in advanced options.
Deployed nodes 3 which have the same hostnames. Created custom cluster using these nodes, and used --node-name option with names other than the real hostnames. The cluster got created successfully with all the nodes in active state
![screen shot 2018-09-06 at 2 23 39 pm](https://user-images.githubusercontent.com/18536626/45185877-7e9fe980-b1e0-11e8-852e-7f84f4d2dbe7.png)

In Kubernetes, each node has to have a unique name. Hence using --node-name option allows adding different names to the nodes even though all the nodes have the same hostname.
