### ISSUE TITLE
No HTTPS support

### ISSUE THREAD

**Issue by vad** [rancher/rancher#140]
I'm running rancher server using `docker run -d --name rancher -p 8080 rancher/server` behind an nginx HTTPS proxy, and the /static/ page loads forever. The HTML is:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Rancher</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=694">
    <link rel="icon" href="//cdn.rancher.io/ui/0.8.19/favicon.ico">
    <link rel="stylesheet" href="//cdn.rancher.io/ui/0.8.19/assets/vendor.css">
    <link rel="stylesheet" href="//cdn.rancher.io/ss-gizmo/ss-gizmo.css">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//cdn.rancher.io/ui/0.8.19/assets/ui.css" title="ui">
    <style type="text/css" title="dynamic-css"></style>
    <base href="/static/">
    <script src="//cdn.rancher.io/ui/0.8.19/assets/vendor.js"></script>
  </head>
  <body>
    <script src="//cdn.rancher.io/ui/0.8.19/assets/ui.js"></script>
  </body>
</html>
```

but the CDN doesn't work on HTTPS:

```
curl --connect-timeout 10 https://cdn.rancher.io/ui/0.8.19/assets/ui.js
curl: (28) Connection timed out after 10001 milliseconds
```

**Comment by vincent99** [comment]
Not terribly nice of Google Cloud Storage to not respond at all, but it would be a cert mismatch even if they did.

I will switch the switch the URLs to `//storage.googleapis.com/cdn.rancher.io/...` for the next release.  Not as nice looking, but they will load over SSL (and plain).

There will likely be additional issues, like insecure content warnings when looking at hosts or containers as it connects to `ws://` URLs.  We should address this in #109, and further provide a way to configure a cert so you don't have to proxy through nginx.

**Comment by vad** [comment]
Thank you :)

**Comment by deniseschannon** [comment]
@vad If this is still an issue, please re-open. Otherwise, it looks as if @vincent99's merge has made it to the latest release.

**Comment by defunctzombie** [comment]
I believe this is still an issue because some ajax calls are still trying to access HTTP content when loaded on an HTTP page.

**Comment by vincent99** [comment]
(FWIW, it's now releases.rancher.com and SSL on that instead of the Google URL)

The links contained in API responses are absolute and still being sent back with `http://` in them, so just proxying it isn't enough.  As soon as the UI follows a link it's loading insecure content.

There is a setting you can enable that will allow your nginx to send a header to adjust the URLs in the response, @cloudnautique can give you more info and will be documenting it.  The latest UI will automatically do `wss://` instead of `ws://` if loaded over `https://`, and you'd probably want to setup [rancherio/host-proxy](https://www.github.com/rancherio/host-proxy) with SSL (versus putting a valid cert on every host).

**Comment by cloudnautique** [comment]
@defunctzombie, rough guide:

The server container needs to be launched with the following variables:

```
"CATTLE_API_UI_INDEX=https://releases.rancher.com/ui/latest/static/index.html"
"CATTLE_API_REDIRECT_UI_PATH=https://<domain>/static/"
"CATTLE_API_ALLOW_CLIENT_OVERRIDE=true"
```

This was done by linking the nginx container to the rancher/server container named rancher-server.
NGINX:
```
server {
  listen 8080;
  server_name ssl-test.rancher.io;

  ssl on;
  ssl_certificate  /etc/ssl/cert/<cert>.crt;
  ssl_certificate_key  /etc/ssl/cert/<key>.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;


  location / {
        proxy_set_header X-API-request-url $scheme://$host:$server_port$request_uri;
	proxy_set_header Host $host:$server_port;
  	proxy_pass http://rancher-server:8080;
  }

  location /v1/subscribe {
        proxy_set_header X-API-request-url $scheme://$host:$server_port$request_uri;
	proxy_set_header Host $host:$server_port;
  	proxy_pass http://rancher-server:8080;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
  }

}
```

This works for the UI and API. The agents can then register via https. The last piece of the puzzle is the logs, stats, and console to the host. As @vincent99 mentioned, the host proxy is your best bet right now.

**Comment by defunctzombie** [comment]
Thanks for the detailed guide! I will give that a go.

**Comment by will-chan** [comment]
I imagine this work may include UI fixes as well but it's certainly related to the proxy support we are developing right now.

#777

**Comment by stefanfoulis** [comment]
I setup SSL termination with a second nginx container as described above by @cloudnautique (I can post a ready-to-use docker-compose configuration for it, if someone is interested).
After launching the setup, I can access the web UI ok, at it seems to be using the correct https urls everywhere.

But looking at the logs I still get some errors related to http/https:

```
time="2015-06-20T21:46:25Z" level=error msg="Unable to create EventRouter" Err="Get http://my-rancher.mydomain.com/v1: dial tcp 1.2.3.4:80: connection refused"
time="2015-06-20T21:46:25Z" level=info msg="Exiting go-machine-service..."
```
The IP (``1.2.3.4`` in the example) is the IP of my rancher master node. I believe it should be trying to access it over https on port 443 instead.
(cc @vincent99 )

**Comment by cloudnautique** [comment]
The current work around for that is to visit the api:

https://my-rancher.mydomain.com/v1/settings/api.host (easier to go through the UI api as it handles auth for you)

Edit the setting, and set the value to a space " "
We will be fixing this for real, but for the time being thats the workaround.

**Comment by cloudnautique** [comment]
A known issue is that host stats, logs and console do not work in SSL yet. I'll be working with our new proxy and post something about how to get those working soon!

**Comment by stefanfoulis** [comment]
@cloudnautique I get a basic auth prompt when accessing that url (but I'm already logged in over github auth)

**Comment by cloudnautique** [comment]
@stefanfoulis you need to use api keys, or in the UI go to the API page (under your user) and click the api link and adjust the url.

**Comment by stefanfoulis** [comment]
@cloudnautique thanks, basic auth worked now. But I get a api 404 error for that url.

**Comment by stefanfoulis** [comment]
I ended up just editing the setting directly in the database (and restarting the container).

Now I'm getting this error in the logs:

```
2015-06-20 23:03:27,039 WARN  [:] [] [] [] [qtp862633345-48] [i.g.i.g.r.handler.CSRFCookieHandler ] Request's CSRF header did not match cookie
```

**Comment by sepiroth887** [comment]
Is there a workaround to get stats & logs working over regular ws ? Is it possible to have nginx proxy pass without ssl termination for the paths used ?

**Comment by sepiroth887** [comment]
To answer my question partially. including /v1/stats the /v1/subscribe section of nginx conf allows stats to work. But still no joy on logs or shell. 

Using tshark I see tons of FIN pakets coming in but only a 101 response that doesn't seem to be answered by rancher?

**Comment by sepiroth887** [comment]
I found out why console/shell and stats don't work i think.

`time="2015-06-26T16:08:25Z" level="info" msg="Connecting to proxy." url="wss://https://{myrancherURL}/v1/connectbackend?token=token"`

if reported by the agent. 

/v1/settings/api.host shows https://{myrancherURL} but if I change it to {myrancherURL} and v1/settings/host.api.proxy.scheme to wss it works. 

However it prevents new agents from connecting at all which is a bit of a blocker... Any idea when and how this will be fixed?

**Comment by cjellick** [comment]
A shame this one slipped through the cracks, re-reported in #1580. Working on a comprehensive SSL fix.

**Comment by cjellick** [comment]
Fixed. 
Now, in the Host Registration screen, a user can specify the protocol and host they want to use (ie, "https:://my.rancherservrer.com").
And a slew of other SSL related configuration issues were addressed to further improve support.

**Comment by sangeethah** [comment]
Tested with rancher/server:v0.31.0-rc1 

Able to bring up a rancher-server with SSL behind Nginx as https reverse proxy.
Following are the steps followed:

```
docker run -d --restart=always --name=rancher-server -e "CATTLE_API_ALLOW_CLIENT_OVERRIDE=true" rancher/server:v0.31.0-rc1
mkdir /root/nginx

docker run -d -p 80:80 -p 443:443 -v /root/nginx/ssl:/etc/nginx/ssl/:ro -v /root/nginx/rancher.io.conf:/etc/nginx/conf.d/rancher.io.conf:ro --link='rancher-server' nginx

nginx confifuration used:

upstream rancher {
    server rancher-server:8080;
}

server {
    listen 443 ssl;
    server_name <servername>;
    ssl_certificate /etc/nginx/ssl/rancher.io.bundled.crt;
    ssl_certificate_key /etc/nginx/ssl/rancher.io.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name <servername>;
    return 301 https://$server_name$request_uri;
}

```
Able to add custom hosts , Digital Ocean hosts to rancher server successfully.
Able to view host stats.
Able to view container logs and also exec shell.
Basic sanity checks to make sure that the connectivity between containers from different hosts work.

**Comment by bertofer** [comment]
Hi @sangeethah , can you please tell me which command did you run to add custom hosts?

I have the server configured behind SSL with nginx, as described in this issue, but now I would like to add the same host the server is running on as a rancher-agent. Tried the default command but not working.

Any ideas?

Thanks

**Comment by bertofer** [comment]
Forget about it, I had the SSL wrong, not the bundle one! It works like a charm now!
