### ISSUE TITLE
Persistent storage service in Rancher 2.0

### ISSUE THREAD

**Issue by Razikus** [rancher/rancher#14002]
Rancher versions : 2.02
Docker version: (docker version,docker info preferred) 17.03.2-ce
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
4.9.0-6-amd64
Persistent registry
Persistent data

Steps to Reproduce:
1. Nexus repository running on cluster
2. After rebooting - it's gone

Results:
Not persistent registry inside node after reboot

How can i add volume that will be accessible from 3 different nodes?
I saw that there is something like Longhorn, but i can't make it work, and i can't any tutorial how to connect Longhorn with rancher 2.0

**Comment by superseb** [comment]
Longhorn is currently in alpha, you can try it but it is not production ready. All information on Longhorn and roadmap can be found at https://github.com/rancher/longhorn and https://github.com/rancher/longhorn/wiki/Roadmap. There is no default storage as we cannot know what the user wants to use (existing storage solution) or something deployed for the user (which can be Longhorn in the future).

Most common storage users use is NFS, this can be used via `nfs-provisioner` (https://github.com/kubernetes-incubator/external-storage/tree/master/nfs) where a server is setup in the cluster, or using the `nfs-client-provisioner` (https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client) which can be used if you already have a NFS server running. 

Examples to run these on Rancher 2 are https://gist.github.com/superseb/b64da0562bb20bcd10ff933617c8b6a8 and https://gist.github.com/superseb/0e128fefd1dcc31982bc8dbdc9bbf6e4
