### ISSUE TITLE
Can't start mariadb with persistent volume

### ISSUE THREAD

**Issue by matheus666matheus** [rancher/rancher#14005]
**Rancher versions:**

rancher 2.0

**Docker version: (`docker version`,`docker info` preferred)**

Containers: 58
 Running: 38
 Paused: 0
 Stopped: 20
Images: 22
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-23-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.69GiB
Name: s3798
ID: FF7A:263Y:7NTU:PFUD:QSQX:J5RM:BT4Q:ULXV:QQWV:OIDE:U52F:POPH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node, internal DB

**Steps to Reproduce:**

Try do deploy any app on the Catalog Apps section with a persistent volume.  

**Results:**

Volume state is pending forever and app display:

Workload mariadb: ReplicaSet "mariadb-787dff4dc7" has timed out progressing.; Deployment does not have minimum availability.

**Comment by loganhz** [comment]
hi @matheus666matheus 

You need to have a storage class in your cluster.
Then you can use it as the default storage class to provision your volume dynamically 

Please try

1. Deploy `nfs-provisioner` from Library catalog first (for storage class)
2. Deploy `mariadb` from Library catalog

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
