### ISSUE TITLE
Private registry in rancher

### ISSUE THREAD

**Issue by RRadziejewski** [rancher/rancher#14001]
Rancher versions : 2.02
Docker version: (docker version,docker info preferred) 17.03.2-ce
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
4.9.0-6-amd64
Virtualbox
Rancher in Rancher
Steps to Reproduce:
1.Create rancher and add privateregistry :
![chrome_2018-06-14_15-27-51](https://user-images.githubusercontent.com/32438378/41415066-ea61a914-6fe7-11e8-9ce2-680e6822af9d.png)
Results:
I want to achieve something like this: i want to deploy by a registry name not by via it's full ip adress. Is it somehow possible ?
![chrome_2018-06-14_15-28-38](https://user-images.githubusercontent.com/32438378/41415101-00e85f52-6fe8-11e8-96c1-b584461e5654.png)

**Comment by RRadziejewski** [comment]
Is there any option to achieve this ?

**Comment by cloudnautique** [comment]
If I understand you correctly.. you want to just type rancher in the name field and have it figure things out? Kind of a convention over configuration thing. If that is the case, no not possible today. Name and image are the 2 main bits of info required.  Similar to the kubectl command below

```# Start a single instance of nginx.
kubectl run nginx --image=nginx```

**Comment by RRadziejewski** [comment]
Solved my problem by docker mirroring to my nexus repository , thank you.
Can be closed
