### ISSUE TITLE
Duplicated node name on Rancher UI

### ISSUE THREAD

**Issue by luzhongming** [rancher/rancher#14011]
*Describe your issue here*
k8s version 1.9.8 imported cluster

Adding a new node to my k8s cluster but 3 duplicated node name appear on Rancher UI
![888](https://user-images.githubusercontent.com/29879821/41454304-7b1b895c-70ab-11e8-96ef-2c7ab58c08f6.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
Can you supply some more info like what kind of cluster you imported? And was the import okay, and did it only happen when adding a new node? And how did you add a new node?

**Comment by luzhongming** [comment]
cluster kind：baremetal cluster.
Imported cluster woking fine before adding new nodes.
only happen when adding a new node.
manaully creating a new node and registering with kubernetes master.

**Comment by superseb** [comment]
What kind of cluster, what tool/software are you using to create the cluster (or what instructions)?

And what command to registering it.

**Comment by luzhongming** [comment]
binary installed on CentOS7.4 and managed by systemd for both kubernetes server and nodes.

registering kubelet to k8s master by adding "--register-node=true --kubeconfig=/data/certs/kubeconfig" while starting kubelet.

**Comment by superseb** [comment]
What is the kubeconfig used? And what is the output of `kubectl get nodes` from the bare metal cluster?

**Comment by luzhongming** [comment]
The sure thing is the kubeconfig i am using working well. The output of the kubectl get node as following,nodes ready and show ok in my k8s cluster
![image](https://user-images.githubusercontent.com/29879821/41692216-8db31104-7531-11e8-967e-436fd4ff69f7.png)
 BUT Rancher UI shows 3 nodes for 10.10.113.80 and 10.10.150.225
![image](https://user-images.githubusercontent.com/29879821/41692270-dea7a246-7531-11e8-82a5-18451a64b4b1.png)
FYI,the two new added nodes kubernetes version are 1.9.8 while other nodes version 1.9.7

**Comment by carolynhu** [comment]
@luzhongming 
I cannot reproduce your issue. My steps as follows:

1. create a cluster in GKE
2. resize the node-pool size to be 4 using this command:
`gcloud container clusters resize carolyn-cluster-3 --node-pool default-pool --size 4`
Then on UI, there shows no duplicate nodes, here is what is showing in UI:
<img width="1243" alt="screen shot 2018-07-26 at 1 59 41 pm" src="https://user-images.githubusercontent.com/29208297/43288278-32fd1c48-90dc-11e8-83aa-3de1431af08d.png">
I tested on both rancher/rancher:v2.0.6 and rancher/rancher:v2.0.2
Is there anything different between your steps and mine? Please point it out. Thanks

**Comment by carolynhu** [comment]
@luzhongming Since I cannot reproduce your issue at the stage, I will move it `to-test`. If we can the same issue happens again. We will reopen it.

**Comment by soumyalj** [comment]
Tested with v2.0.6 and master. 
1. Created GKE and RKE imported clusters.
2. Added more worker nodes.
Duplicated node names were not displayed in UI. Could not reproduce this issue.

**Comment by apigban** [comment]
was this solved? 

I have deployed this on baremetal. Created the cluster using rke and added the node using rke.

Here's the rke output: https://pastebin.com/raw/5tFHRd2i

I ran into this issue just now, I'm using rke to add a node to my cluster:
`./rke up --update-only -config rancher-cluster/rancher-cluster.yaml`
I added the address, port and role to the rancher-cluster.yaml: 
![image](https://user-images.githubusercontent.com/2720851/56900874-f096ad00-6aa7-11e9-9792-f316616c67f8.png)


and got 2 entries for the new node:
![image](https://user-images.githubusercontent.com/2720851/56900568-2dae6f80-6aa7-11e9-9fd3-372fcf8ad221.png)

kubectl get nodes -o wide
![image](https://user-images.githubusercontent.com/2720851/56901002-2cca0d80-6aa8-11e9-9f3b-3393003719da.png)

**Comment by ivanovpavel1983** [comment]
Hello. Have the same issue. k8s - 1.17.3, rancher 2.3.5 (((
Try to add worker node with kubelet 1.17.2 and 1.17.3 - the result the same ((

![image](https://user-images.githubusercontent.com/5180093/74513518-cb323d00-4f1b-11ea-91cb-6eedfaca955f.png)

**Comment by ivanovpavel1983** [comment]
I tried to add another server - the result is the same.

**Comment by ivanovpavel1983** [comment]
I tried to add node with k8s 1.16.4. It is ok.
![image](https://user-images.githubusercontent.com/5180093/74526802-350b1080-4f35-11ea-9e4c-61224114f23a.png)
