### ISSUE TITLE
Bug: execute shell should make it possible to run as root

### ISSUE THREAD

**Issue by perlun** [rancher/rancher#14014]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/server:stable (1.6.17)
rancher/agent or rancher/rancher-agent: rancher/agent:v1.2.10

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.6
ipsec: rancher/net:v0.13.11
network-services: rancher/network-manager:v0.7.20
scheduler: rancher/scheduler:v0.8.3
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-128-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
[    0.000000] DMI: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 04/14/2014

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher w/ External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Deploy an app with a Dockerfile that creates and sets the `USER` to a custom, non-privileged user. Like this:

```
RUN addgroup --gid 1234 ecraft
RUN adduser \
  --system \
  --uid 1234 \
  --ingroup ecraft \
  ecraft
USER ecraft:ecraft
``` 
1. Use the "Execute Shell" function in the Rancher web interface.

**Results:**
The shell will be running as the `ecraft:ecraft` user in this case. While this is reasonable, it is not optimal since it means that superuser activities will be very limited. We could work around this by setting a `su` password for the `root` account but I don't really like that approach since it's less secure. Simply put, security flaws in the application should _never_ allow privilege escalation so the less potential loopholes there are, the better.

We have a workaround for now, where we can log on to the server and run an alias which roughly does the following:

```shell
dexec()
{
  [ $# -lt 2 ] && echo "usage: dexec CONTAINERNAME COMMAND [args..]" \
               && return 1
  local container_pid="$(dpid "$1")"
  shift
  as_sudo nsenter -m -u -i -n -p -r -t "${container_pid}" bash -c "$*"
}
```

This approach means that we will enter the container as root. I don't know how the "execute shell" works in Rancher 1.6, but if you are currently doing something like:

```shell
docker exec -it r-stack-and-service-name-1-18c5af57 /bin/bash
```

...it might not be technically more complex than adding the `-u` parameter, like this:

```shell
docker exec -u root -it r-stack-and-service-name-1-18c5af57 /bin/bash
```

Of course, that's completely ignoring the security implications which must certainly be considered for this kind of change. Maybe the easiest way for now would be to feature-flag this (if we make the change), to at least be able to opt-out from "root mode" or something like this.

If you point me to the appropriate code in the Rancher codebase, I might be able to submit a PR for this. But I want to discuss it with you first to avoid spending time on it if you have already discussed this in the past and dismissed the idea.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
