### ISSUE TITLE
Deployment does not have minimum availability

### ISSUE THREAD

**Issue by maryxu** [rancher/rancher#14013]
when I'm deploying prometheus from catalogs in Rancher2. there are 5 pods creating. But for alertmanager and prometheus server these two pods, they can't be created successfully. The error is:
 ReplicaSet "prometheus-alertmanager-7468c987d8" has timed out progressing.; Deployment does not have minimum availability

Please help to take a look and guide. thanks a lot!
![image](https://user-images.githubusercontent.com/13269986/41455181-d36ac53e-70ae-11e8-9241-dc3bd4e0a3c8.png)
![image](https://user-images.githubusercontent.com/13269986/41460199-6f93f7e6-70be-11e8-9dd4-be496f8b9a50.png)

**Comment by loganhz** [comment]
Can you provide more info like using `kubectl describe pod`, please ?

**Comment by loganhz** [comment]
@maryxu this is not a pod of prometheus
Please provide the pods of prometheus-alertmanager

**Comment by maryxu** [comment]
You can close this issue now, thanks.


Mary Xu,

**Comment by binarymist** [comment]
How did you fix this @maryxu?

**Comment by Ismail-Ham** [comment]
Any Fix ?

**Comment by sunliusi** [comment]
any solution?

**Comment by iqido-systems** [comment]
I have this problem on fresh system too

**Comment by lytao** [comment]
For those who is asking for solution:

It is clearly displayed in `kubectl describe pod <pod_name>`:
```
Events:
  Type     Reason                 Age               From                  Message
  ----     ------                 ----              ----                  -------
  Warning  FailedScheduling       6m (x2 over 6m)   default-scheduler     pod has unbound PersistentVolumeClaims (repeated 7 times)
```

You need persistent volume in k8s cluster!
