### ISSUE TITLE
Trying to create a cluster with dots in its name silently fails for importing a cluster

### ISSUE THREAD

**Issue by mattparkes** [rancher/rancher#14010]
**Rancher versions:**
2.0.2

In Rancher 2.0.0 or 2.0.1 (I can't remember which) we created several rancher clusters with dots in their names (fqdns), and imported existing Kubernetes clusters.

In Rancher 2.0.2, that doesn't work and when you click the Create button whilst having a name containing dots, it just does ...nothing.

An error message would be very helpful!

**Comment by prachidamle** [comment]
With latest master 06/19, creating a cluster with dot in name fails with an error message.

Screenshot:

<img width="1349" alt="screen shot 2018-06-10 at 6 02 32 am" src="https://user-images.githubusercontent.com/1470602/41616054-cb5ca708-73b1-11e8-9936-eae2202d51eb.png">

**Comment by deniseschannon** [comment]
Actually, it seems that import doesn't do anything if there is a `.` in the cluster name.

**Comment by prachidamle** [comment]
Don't see any API request being sent when importing the cluster having a dot in its name. Seems like an UI issue

**Comment by soumyalj** [comment]
Tested with v2.0.3-rc1. Created custom cluster with a dot in the name. An error message was displayed that dot is not allowed in the cluster name. 
<img width="1288" alt="screen shot 2018-06-20 at 10 55 45 am" src="https://user-images.githubusercontent.com/18536626/41675796-836f6274-7478-11e8-8d93-0f28a9526152.png">

Also tried with AWS, DO and custom clusters. An error message is displayed as expected.

<img width="1259" alt="screen shot 2018-06-20 at 10 51 27 am" src="https://user-images.githubusercontent.com/18536626/41675831-9db45e28-7478-11e8-92a8-363d10a7e851.png">

<img width="1396" alt="screen shot 2018-06-20 at 10 43 38 am" src="https://user-images.githubusercontent.com/18536626/41675873-be8e9442-7478-11e8-8e3f-e130d719a79a.png">

<img width="1523" alt="screen shot 2018-06-20 at 10 58 13 am" src="https://user-images.githubusercontent.com/18536626/41675907-db4b104c-7478-11e8-8f44-911b8c110395.png">
