### ISSUE TITLE
When deleting catalog app, namespace isn't deleted

### ISSUE THREAD

**Issue by divyangjp** [rancher/rancher#14012]
When catalog app is deployed, rancher creates separate namespace for it.
Deleting catalog app deletes all other resources related to that app except namespace created for that app.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` |
|Route|`authenticated.project.ns.index`|

**Comment by loganhz** [comment]
@guangbochen @StrongMonkey Can we remove the namespace?

**Comment by StrongMonkey** [comment]
duplicate of https://github.com/rancher/rancher/issues/14012
