### ISSUE TITLE
Container created on network mode host instead of managed

### ISSUE THREAD

**Issue by TBigjohn** [rancher/rancher#14016]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.15
rancher/agent or rancher/rancher-agent: 

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 18.03.1-ce, build 9ee9f40

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu

Hi, I have 3 containers deployed on Rancher on network mode Managed so they receive an IP address from Rancher. I am launching an Hyperledger command ( composer network start ) from a different host, this command connect to one of my container and it try to create a new container (4th). My issue is that this last container is created with network mode host so it cannot communicate with the 3 manually created before.

The container who receive the connection has an env variable named CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE, this env var is read by my process but apparently considered as a network name, not as a mode ....

On the docker side, if a try a "docker network ls", I see that the 3 first container are all linked to the same network named "none" ....

Can somebody help ?
Thanks

**Comment by superseb** [comment]
Container with host networking can reach containers on the overlay network by IP, but that's not very dynamic and requires retrieving the correct IP but can be done. If you want a container launched via Docker to join the managed network, you can add a label to it as described here:https://rancher.com/docs/rancher/v1.6/en/rancher-services/networking/#containers-created-with-the-docker-cli

```
For any containers launched through the Docker CLI, an extra label --label io.rancher.container.network=true can be used to launch the container into the managed network.
```

**Comment by TBigjohn** [comment]
Additional info on the same issue : https://github.com/hyperledger/composer/issues/4129
Thanks to superseb, I will investigate this and come back to you.

**Comment by TBigjohn** [comment]
@superseb  The point is that I am not using Docker CLI (not directly) I am launching an Hyperledger composer command so I don't see yet how to pass this --label option ....

**Comment by TBigjohn** [comment]
I tried the same thing with all container on network mode "host", but not working because containers can communicate with each other .... Any idea around ?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
