### ISSUE TITLE
Cloned workload with Port Mapping doesn't create associated Service Discovery

### ISSUE THREAD

**Issue by alexey-kruchenok** [rancher/rancher#14018]
**Rancher versions:**
rancher/rancher 2.0.2
docker 17.3.2
"kubeProxyVersion": "v1.10.1",
"kubeletVersion": "v1.10.1"

** Description of the probem **

We create workload of Wordpress server listening under 80 port, with some connection to db and volumes. After we configured workload, we cloned them 2 times, adjusting environment variables and volume mapping in cloned workload.

After cloning we expect to have 3 different wordpress workload available under service discovery, but we have only first one. So new cloned workload not appears under service discovery tab.

If we try to add manual record to service discovery, we got confusing situation, at UI we have record pointing to different workload, but it actually all record mapped to the first one , and first workload called all time when we call something by name listed in service disocvery.
wordrpress-1.web.svc.cluster.local - original
wordrpress-2.web.svc.cluster.local - cloned, wordrpress-1.web.svc.cluster.local  called 
wordrpress-3web.svc.cluster.local - cloned, wordrpress-1.web.svc.cluster.local  called

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
This is not resolved.  Second workload doesn't create if I clone when I have a port specified.  Steps:
1.  Create wp1 - image: wordpress, Port mapping - container port=80 As a NodePort on Random
2. After it's done, clone wp1 and only change the name to wp2

No wp2 service discovery is created.

**Comment by tfiduccia** [comment]
In #14034 we deleted labels for cloning, but we it didn't resolve this issue.  Sending to Vincent.

**Comment by vincent99** [comment]
It's the name/dnsName on the port on the container in the workload that's still points to the old service name.  Remove now on clone.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Verified fixed
