### ISSUE TITLE
websocket-proxy keeps connections in CLOSE_WAIT

### ISSUE THREAD

**Issue by fdevaux** [rancher/rancher#14015]
**Rancher versions:**
rancher/server or rancher/rancher: `rancher/server:v1.6.18`
rancher/agent or rancher/rancher-agent: `rancher/agent:v1.2.10`

**Infrastructure Stack versions:**
healthcheck: `rancher/healthcheck:v0.3.6`
ipsec: `rancher/net:v0.13.13`
network-services: `rancher/metadata:v0.10.2`, `rancher/network-manager:v0.7.20`
scheduler: 
kubernetes (if applicable): `rancher/k8s:v1.10.3-rancher1-1`

**Docker version: (`docker version`,`docker info` preferred)**

```
Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   276fd32
 Built:        Fri Jun 23 20:13:39 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.4"
ID="ol"
VERSION_ID="7.4"
PRETTY_NAME="Oracle Linux Server 7.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.4

# uname -a
Linux buffalobill.novalocal 4.1.12-94.3.9.el7uek.x86_64 #2 SMP Fri Jul 14 20:09:40 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Openstack VMs (KVM)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher with internal DB.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

We are using Rancher to run Jenkins builds using [jenkinsci/kubernetes-plugin](https://github.com/jenkinsci/kubernetes-plugin). The plugin talks to the kube-apiserver via the websocket-proxy on the rancher server (i.e. via https://rancher_server:8080/r/projects/1a7/kubernetes:6443) to create/get/delete pods.

Functionally this works fine. However on the rancher server we're seeing the connections from Jenkins stick around in in `CLOSE_WAIT` state and the proxied connections with the kube-apiserver in `ESTABLISHED` state.

This keeps on going (connections go into the thousands) until eventually we see a flurry of these errors in rancher-server:

```
time="2018-06-14T16:02:01Z" level=info msg="Shutting down backend 69ad7c6e-6333-446d-5151-0b04c3b61ca3. Connection closed because: websocket: close 1006 unexpected EOF."
time="2018-06-14T16:02:01Z" level=info msg="Removed backend. Key: 69ad7c6e-6333-446d-5151-0b04c3b61ca3. Session ID 6d195a2f-0a66-4769-949b-808ee72428d3 ."
time="2018-06-14T16:02:07Z" level=info msg="Handling backend connection request."
time="2018-06-14T16:02:07Z" level=info msg="Registering backend for host 69ad7c6e-6333-446d-5151-0b04c3b61ca3 with session ID 6e74a8be-3e5b-4855-b189-ba7e2a4b0cc9."
time="2018-06-14T16:02:07Z" level=info msg="Shutting down backend fc87c2b6-a801-499c-6f71-27b3a9b28874. Connection closed because: websocket: close 1006 unexpected EOF."
time="2018-06-14T16:02:07Z" level=info msg="Removed backend. Key: fc87c2b6-a801-499c-6f71-27b3a9b28874. Session ID be92cae3-9faf-46ca-8b59-477d5f0e2e4c ."
time="2018-06-14T16:02:13Z" level=info msg="Handling backend connection request."
```

At this point all the connections are closed and the API is unavailable for  a few seconds.

**Results:**

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
