### ISSUE TITLE
Catalog refresh status is not visible

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14020]
Version: master 6/15

1. Enable Helm Stable
1. See logging in `rancher/rancher` container `Fetching file` and `Creating template`
1. Don't see any status in the UI, is it being updated while catalog items are not visible in catalogs view.

Expected results:
Helm Stable is currently being refreshed.

Not sure if its 100% UI or that API needs work too.

**Comment by superseb** [comment]
Another use-case, when using self signed certificates and the CA is not added, the logging is:
```
2018/07/25 14:55:32 [ERROR] CatalogController x [catalog] failed with : Get https://x/index.yaml: x509: certificate signed by unknown authority                                                                                                                                             
```
But the UI shows `Refreshed` in Red, but no error while it's available in the API.

```
conditions": [
{
"lastUpdateTime": "2018-07-25T14:47:00Z",
"message": "Get https://x/index.yaml: x509: certificate signed by unknown authority",
"reason": "Error",
"status": "False",
"type": "Refreshed"
}
],
"transitioningMessage": "Get https://x/index.yaml: x509: certificate signed by unknown authority",
```

**Comment by tfiduccia** [comment]
@loganhz - where is this message supposed to show up in the UI?  I don't see it anywhere?

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/44697834-26fed100-aab0-11e8-8d29-abb56186f902.png)

@tfiduccia in the catalog list page

**Comment by tfiduccia** [comment]
@loganhz - the original issue was talking about Helm Stable.  Which is not an added catalog.  It's above that and a button you set to Enable.

**Comment by loganhz** [comment]
Updated. I will submit a PR for it. Thanks!

![image](https://user-images.githubusercontent.com/21168270/45348303-e4c1ad80-b5e0-11e8-9e11-8b7ea3b8306a.png)

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/11
Verified fixed
