### ISSUE TITLE
When Catalog App is upgraded , the status of the application remains as "active" during the upgrade process and also when upgrade is completed the "Removed" pod is not removed until manually refreshed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14028]
**Rancher versions: Build from master
**Steps to Reproduce:**
Deploy any app from catalog.
Upgrade the app.
When app is being upgraded , there is no status change to reflect the state that it is upgrading.

Once upgrade is done, the removed (older instance) continues to be present in the UI.

<img width="635" alt="screen shot 2018-06-15 at 12 37 38 pm" src="https://user-images.githubusercontent.com/4266958/41487608-388681bc-709e-11e8-85dd-4da97b03df31.png">

Once refreshed it is removed.
 
<img width="637" alt="screen shot 2018-06-15 at 12 38 14 pm" src="https://user-images.githubusercontent.com/4266958/41487612-3b95f914-709e-11e8-9018-dac2aa418280.png">

**Comment by StrongMonkey** [comment]
The state of the app is derived from the workload state inside app. Can you verify if workload is active? Also this kind of reflection is done in API level so UI won't be able to know this dynamically.

**Comment by deniseschannon** [comment]
@StrongMonkey is there nothing that we can send to the UI when it's complete so UI can refresh automatically?

**Comment by loganhz** [comment]
Please check if it is only happens for catalog.

I guess workloads and pods in UI can not update automatically either.
