### ISSUE TITLE
[cli] first rancher login doesn't create any cli2.json credential file

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#14022]
CLI 2.0.1
Windows 10 and
macOS latest

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

As stated in the CLI readme, I expect the CLI, at first `rancher login` to generate a `cli2.json` file or ask for credentials. 

But running the command only throws a fatal error:

```
$ rancher login https://rancher.example.com
FATA[0000] token flag is required
```

I even tried to define a path for the non existent cli2.json:

```
$ rancher login https://rancher.example.com -t ~/.rancher/cli2.json
FATA[0000] invalid token
```

How to then first generate the credential file? What if the content of this file if the CLI doesn't manage to create it by itself? Because right now it's almost impossible to login using CLI...

Quoting the readme:

`Rancher CLI pulls this information from a JSON file, cli2.json, which is created the first time you run rancher login`: obviously this doesn't work at all.

**Comment by dramich** [comment]
The --token flag is required when you run login.

**Comment by deniseschannon** [comment]
@blackholegalaxy In the UI, if you click on your avatar from the upper right hand corner, you can go to API & Keys. When you create an API key, it will provide a bearer token which can be used for the login.

**Comment by blackholegalaxy** [comment]
@deniseschannon thanks it worked. That piece of information is missing in the doc (the fact we must use the full bearer-token at first login).

**Comment by deniseschannon** [comment]
@blackholegalaxy which doc are you referring to? i can ask our team to update it but not sure where you are looking.

**Comment by blackholegalaxy** [comment]
Nor the readme of the CLI neither the rancher 2.0 docs states that. So the best first place where to put it is on the Rancher CLI Readme

**Comment by blackholegalaxy** [comment]
This can be closed, but documentation should be updated.
