### ISSUE TITLE
Cloned workload results in incorrect ingress routing

### ISSUE THREAD

**Issue by rubenmch** [rancher/rancher#14034]
rancher/rancher: 2.0.2
Single node rancher
Provider: DigitalOcean (1 etcd/control node, 3 worker nodes)

**Steps to Reproduce:**
1. Created **workload1** in default namespace
2. Created **ingress1** in default namespace (host: ingress1.default.167.99.200.200.xip.io, target: workload1, port: 15200)
2. Cloned workload1 to create **workload2**
3. Created **ingress2** in default namespace (host: ingress2.default.167.99.200.200.xip.io, target: workload2, port: 15200)

Note:  workload1 and workload2 use the same docker image but with different environment variables so they return different content

**Results:**
- Browsing http://ingress1.default.167.99.200.200.xip.io randomly returns content from workload1 or workload2
- Browsing http://ingress2.default.167.99.200.200.xip.io also randomly returns content from workload1 or workload2

Note: links are just examples, not working.

If I create workload3 from scratch without cloning workload1 then the ingress works as expected.

**Comment by vincent99** [comment]
@loganhz or @westlywright I pressing there's one or more labels/annotations that need to be removed on clone.  Please consult with @alena1108.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
