### ISSUE TITLE
ipv6 Support

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1403]
Currently, Rancher doesn't support ipv6, but if enough users request it, we'll prioritize it. Currently, most people have asked out of curiosity.

Originally part of #1376.

**Comment by moimael** [comment]
It would be great for sure, but I think #544 is higher priority and would lesser the need to have ipv6 for now.

**Comment by stresler** [comment]
This is something I'd greatly like to see.  I know there are upstream considerations as well https://github.com/docker/docker/issues/13481  But this is pretty important in our hosting model because we'd much rather offer additional IPv6 to clients than additional IPv4.

**Comment by fentas** [comment]
I have an sql instance for `rancher/server` with ipv6.
If I replace (`CATTLE_DB_CATTLE_MYSQL_HOST`)  the currently working ipv4 with ipv6 it won't work.
Logs show:
```logs
[...]
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not connect to 2001:4860 : Invalid argument or cannot assign requested address)
[...]
```
It seems it does not recognize the whole address instead using only the first two blocks.
Do I have to tell it's an ipv6 or is it not supported?

**Comment by deniseschannon** [comment]
At this time, ipv6 is not supported.

**Comment by fatrix** [comment]
Is IPv6 support expected in the future and if yes by when?

**Comment by stresler** [comment]
I think it is safe to say, 'sometime after Docker supports ipv6.

https://github.com/docker/docker/issues/13481

https://github.com/docker/docker/issues/18297

**Comment by pboos** [comment]
Docker supports ipv6. It just starts with ipv4 by default. But easy to run it with ipv6 support.
https://docs.docker.com/v1.5/articles/networking/#ipv6

So I think it is about time to start working on this ;-).

Even better would be if one can use his own ipv6 subnet so that containers can be accessible from everywhere. Reason? So I can ssh in to a container (if ssh setup in the container) directly without having to go over the UI or the host system. Of course this would probably be off by default. So that only those who should be public are public.

**Comment by demarant** [comment]
+1
Having an ipv6 for each container accessible from    outside would be great for numerous usecases.

**Comment by iqidos** [comment]
I need ipv6 support very much

**Comment by stresler** [comment]
Linking to the same issue I linked to above, @pboos. The documentation gives you a way to assign an ipv6 address, but that doesn't make IPv6 usable. [IPv6 is not practically usable for production machines #13481](https://github.com/docker/docker/issues/13481)

**Comment by ShakataGaNai** [comment]
Having IPv6 support internally would be wonderful. However, I'd wager an easy way to setup IPv6 for just front end container(s) would be sufficient stopgap for most people. 

While personally I love using IPv6 as much as possible, as long as my front end (HAproxy, Nginx, whatever) can handle the IPv6 connections... I don't care if it gets passed to the backend app servers over IPv4.

**Comment by hwinkel** [comment]
ipv6 is required for a asia based deployment soon. Is there anything on the roadmap. At least we need to provide IPv6 based external services and IPv6 based hosts. The overlay for know could remain as IPv4

**Comment by julianxhokaxhiu** [comment]
+1 my whole Docker stack is fully IPv6 operational, only Rancher is not :) Looking forward into this!

**Comment by rvion** [comment]
+1 It would ease my job

**Comment by nealf** [comment]
Unfortunately, IPv6 is a hard requirement for us, otherwise Rancher was looking promising!

**Comment by gjongenelen** [comment]
IPv6 is getting more and more important for us too. We really need IPv6 support in our rancher-environment.

**Comment by feffi** [comment]
+2

**Comment by pasientskyhosting-docker-hub** [comment]
+1

**Comment by LennardWesterveld** [comment]
Can some one from the "rancher" team tell us when this will be implemented? (time window)

**Comment by fflo** [comment]
what's the current status about IPv6 support?
I think supporting IPv6 is a basic requirement making professional business, today.

**Comment by dominictayloruk** [comment]
+1

**Comment by techninja1008** [comment]
+1

**Comment by lkm** [comment]
+1

**Comment by alphayax** [comment]
+1

**Comment by fflo** [comment]
This ticket is open since Juli 2015!
Are there any news on this topic?

**Comment by raymatos** [comment]
Hard requirement here as we build APIs for iOS apps.

https://developer.apple.com/news/?id=05042016a

**Comment by gjongenelen** [comment]
I agree that this feature is mandatory. But as long as it isn't implemented, you could use CloudFlare in front of your main inbound. This was our solution to pass the app-store checks for IPv6.

**Comment by techninja1008** [comment]
This has almost been open for 2 years, yet it seems that no progress is being made. Any news?

**Comment by fflo** [comment]
what's the reason why this important issue is treated in an inadequate manner?

Without full support for IPv6 there is no future for Rancher. Never saddle a dead horse!

**Comment by bradjones1** [comment]
I'm just going to chime in here to say, every open source project has its priorities, and clearly Rancher's paid engineers are busy on other issues they've prioritized over this. I myself am an open-source user of Rancher and appreciate the support they do give non-paid users, but commenting in an increasingly impatient tone on a GitHub ticket isn't the way to get a feature completed. If this functionality is so business-critical, I would encourage you to reach out and ask about how you can either contribute the code and tests yourself, or become a paid customer and voice your preferences via that channel.

**Comment by vincent99** [comment]
Every year for the last 10 years has been the year you "have to have IPv6", and  "everybody" "needs" it right now.  But in reality adoption is still heavily skewed towards cellular carriers, where it's largely invisible.  Cloud provider support is spotty, and almost universally dual-stack.  Amazon and Azure both just added support within the last few months.  Google (of all people) doesn't support it at all.

Few-to-no customers or serious prospects I'm aware of have even *asked* about it, let alone had a requirement for it.  Including many in IP-constrained countries.  And there are plenty of other things they are asking for.

**Comment by skhameneh** [comment]
@vincent99 that's only because hosts restrict IPv4 addresses now; this wasn't an issue years ago, it is now.

Search engines are starting to use IPv6 support for rankings, hosts are moving away from handing out more than one IPv4, and there are claims of it being an upcoming requirement in some countries.  There's a reason it's been pushed so hard, the message is being sent before it's a service-halting requirement.

**Comment by miguelpeixe** [comment]
+1

**Comment by dominictayloruk** [comment]
[https://www.youtube.com/watch?v=v26BAlfWBm8](https://www.youtube.com/watch?v=v26BAlfWBm8)

**Comment by robertpearce** [comment]
have just moved our environment over to v6, just rancher holding things up now.

**Comment by wzrdtales** [comment]
Also looking forward to it. Here in germany you don't even get real IPv4 anymore at most ISPs if you don't explicitly ask for it. You get your horrible dual stack light by default, which screws up just everything that requires low latency.

Apart from that we definitely **need** to support IPv6 for customers! The current solution is an IPv6 terminator, that forwards everything as IPv4 traffic to rancher. It would be great if this wouldn't be necessary anymore, as this is just another unneeded hop.

**Comment by candlerb** [comment]
"Native" docker has supported IPv6 for a while, on the default bridge: https://docs.docker.com/engine/userguide/networking/default_network/ipv6/

**Comment by fflo** [comment]
why is there no progress adding IPv6 support to Rancher?

**Comment by vincent99** [comment]
As I've said before, because `{people that want ipv6} ∩ {customers and potential customers} ≈ ∅` and companies don't run on thumbs-up emojis.

(and TIL you can react to your own comments... classy.)

**Comment by bradjones1** [comment]
Another note to everyone who pokes and prods this issue: If it's that important/critical to you, pay Rancher to implement this. Or, contribute the code yourself, I'm sure they'll entertain a PR. But in the meantime, vocal impatience and outright hostility to the maintainers is a clear path to frustration with the open-source user base and a poor way to show your appreciation for what is by all accounts a great product.

**Comment by wzrdtales** [comment]
@vincent99 
> {people that want ipv6} ∩ {customers and potential customers} ≈ ∅

Hardy depends on the country though. http://ipv6-test.com/stats/. In countries like germany is a greater demand as ISPs stop providing *real* IPv4. But as stated above, take your time there is no need for heavy pressure on this. Everyone can just setup an IPv6 terminator as we do, yes it is a workaround, but it works.

**Comment by vincent99** [comment]
The availability certainly varies per country, but (non-emoji) demand for it doesn't really.  The two major countries higher than the US on that list are Germany and Japan, and we have customers (and employees, even) in both.  At least one of which is a major telecom company that presumably gives out v6 addresses to their phones.

**Comment by protometa** [comment]
There may never be an urgent need for a particular product to support ipv6. They will just be left behind the times. Emoji support is very good for any brand, especialy the life of an open source project. It sends the message that you are ahead of the curve and up to the challenge of adapting to new technology. That translates to :moneybag: in the end.

**Comment by bradjones1** [comment]
Does the Rancher 2.x transition to using K8s change this dynamic?

**Comment by vincent99** [comment]
AFAIK k8s 1.8 doesn't support ipv6, so it mostly gives you a new much larger open-source  community to direct indignance at...  There seems to be some work going on to add support now.

 (Backed by again Google of all people, which still hasn't thought of it as a priority for years, despite having infinite resources, their own public cloud, and other departments talking about how important it is.)

**Comment by jheredianet** [comment]
Please suport IPv6

**Comment by telmich** [comment]
Ping. We are running IPv6 only networks and it would be nice to be able to run rancher on it, too.

**Comment by vincent99** [comment]
K8s 1.9+ has [alpha IPv6-only support](https://github.com/kubernetes/features/issues/508), with various caveats and limitations.  Nobody I'm aware of has tried it, we don't do anything to intentionally break it but there are probably issues with linking in the UI or accepting v6 addresses in validators if someone wants to try it and make specific issues.

Dual-stack, which is what most people really want, is still [far away](https://github.com/kubernetes/features/issues/563).

Support in 1.x is not ever going to happen at this point, short of a customer sponsoring major development of it.  Which as I've said, there's never been any interest in.

**Comment by wzrdtales** [comment]
@vincent99 Well basically people only need to be able to configure the loadbalancer, everything else is not important and wouldn't need to be able to accept ipv6. What kubernetes is doing here is shooting well beyond that. But I understand the problem you've got. For us, we setup on the dedicated loadbalancers we have in place a manually configured ipv6 one, that forwards basically everything to the rancher one, which is not ideal, but it works.

**Comment by telmich** [comment]
Does this mean ipv6 only setup are now fully supported?

**Comment by deniseschannon** [comment]
No, I've closed this issue as this was for Rancher v1.6. With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by cdrfun** [comment]
Has Rancher 2.0 IPv6 Support? If not, why not map the issue to Rancher 2.0 or create a new issue for 2.0 and link it here?

**Comment by vincent99** [comment]
@cdrfun We've [already covered this](https://github.com/rancher/rancher/issues/1403#issuecomment-384490184).  Unless you have a Rancher-specific issue with it, which I asked for separate issues for, we're just deploying Kubernetes.  Development of support for ipv6 is up to the k8s community.

**Comment by coderenwoxing** [comment]
hello, every one, does rancher support IPv6 now？
thanks

**Comment by wzrdtales** [comment]
@coderenwoxing 2.x kind of. It works for endpoints, but is not necessarily supported. If you only need ipv6 at your ingress it will work without worries. Metallb has ipv6 support as well should you work on premise.

**Comment by roedie** [comment]
But, what if you want to do egress IPv6? Is this possible or is it still a no-go area?

Dual stack is nice to have, but I wouldn't mind NAT-ing 6 to 4 if a container needs to connect to an IPv4 host somewhere om the internet.

**Comment by sep76** [comment]
Hello, is there any news on ipv6  for rancher ?  ipv4 is only on a DC wide SIIT-DC.

**Comment by telmich** [comment]
Hello,

we are running IPv6 only data centers in Switzerland and are quite interested in running rancher. 

However we have been shocked to discover it does not natively support IPv6 at the moment. Is there any chance to add IPv6 support or may we ask what is the effort required to add IPv6 support?

**Comment by sep76** [comment]
seems rancher have made a new issue,  https://github.com/rancher/rancher/issues/27808 Probably of interest to everyone following this one.
