### ISSUE TITLE
Workload pods created in non worker nodes

### ISSUE THREAD

**Issue by rubenmch** [rancher/rancher#14035]
rancher/rancher: 2.0.2
Single node rancher
Provider: DigitalOcean (1 etcd/control node, 3 worker nodes)

Steps to Reproduce:

- Added a **DigitalOcean** cluster with **1 etcd/control node** and **3 worker only nodes**, only the worker nodes are allowed in the firewall of an external database
- Created **workload1**, **workload2** and **workload3** in the default environment, pods were created in the worker nodes and have access to the external database
- Created **workload4**, the pod was created in the **etcd/control** node and doesn't have access to the external database

Results:

**workload4 not working** because the pod was created in the etcd/control node

I'm new to kubernetes so maybe I'm misunderstanding how it should work. I thought workload pods were only started on worker nodes.

Also, how many etcd and/or control nodes are recommended for a small cluster? should all worker nodes be also control nodes?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13524.

It's all about what kind of HA you are expecting, 3 etcd nodes gives you 1 fault tolerant. To make control HA you need at least 2, and as many as you want for HA. Workers basically the same, as this relates to workloads and not vital components to the cluster.
