### ISSUE TITLE
Unhealthy controller manager and scheduler after leaving it running overnight

### ISSUE THREAD

**Issue by rubenmch** [rancher/rancher#14036]
rancher/rancher: 2.0.2 single node
provider: Digital Ocean (1 etcd/control node, 3 worker nodes, all 1GB Ram 1 vcpu 25GB disk, ubuntu 16.04 x64)

**Steps to Reproduce:**

- Created a Digital Ocean cluster with 1 etcd/control node, 3 worker nodes, all 1GB Ram 1 vcpu 25GB disk, ubuntu 16.04 x6
- Deployed rabbitmq-ha from the helm catalog
- Added an ingress for rabbitmq-ha, tested and everything was working ok
- Left it running overnight
- In the morning the cluster said Controller Manager and Scheduler are unhealthy and new workloads aren't deployed
- After rebooting the etcd/control node the Controller Manager and Scheduler are no longer unhealthy but now a message saying Alert: Component etcd-0 is unhealthy appeared.
- In the agent and server logs were multiple Timeout messages
- While the controller and scheduler were marked as unhealthy I was able to access healthz from the etcd/control node

**Comment by superseb** [comment]
The docs state that starting with a small cluster requires 2 vCPUs and 4GB RAM, you should provision it uses these specifications and try again. For the next time, please include the logging generated by the cluster components so we can take a look what is happening in your cluster.

**Comment by rubenmch** [comment]
You're right, I thought that requirement was for the rancher server but the documentation clearly states that it's for the nodes.

I upgraded to the 2cpu 4gb drops and increased the etcd/control nodes to 3 nodes and it hasn't happened again.

**Comment by rubenmch** [comment]
@apricote You can try upgrading to rancher 2.0.4. Rancher 2.0.2 used control nodes as worker nodes to schedule workload pods. That could cause the etcd/control node to run out of memory.
I'm currently using 3 all purpose (etcd/control/worker) nodes and haven't had the issue again.

**Comment by apricote** [comment]
Upgrade is scheduled for next week.

**Comment by hadifarnoud** [comment]
@apricote I restarted all the worker nodes. it worked. no idea when this will happen again

**Comment by Mroch-Cn** [comment]
the  same issue

**Comment by valerioleo** [comment]
![image](https://user-images.githubusercontent.com/13155741/59566576-e03b9100-9059-11e9-9ba6-9b28cc34fddd.png)

I keep having the same issue, although it is not an "overnight" one, but it can happen without (apparent) reason. Another problem I face is that I couldn't find a way to restart the unhealthy parts (Controller Manager and Scheduler). I always had to recreate a whole new cluster, do you know if it is possible to restart the unhealthy components only?

**Comment by Mapiac** [comment]
Can this be re-opened? I am curious why it was closed with no resolution?

**Comment by jwuman** [comment]
I did restart the etcd container on each host that has the unhealthy error and that clears the alert.

**Comment by matfiz** [comment]
I have faced the same issue, all min requirements are met. The only solution for me was to reboot each host. There is also no rule - the Scheduler can become unhealthy overnight, or in the middle of the day. Is there a way to restart it automatically when it becomes unhealthy?

![Image 2019-09-12 at 9 33 21 AM](https://user-images.githubusercontent.com/244515/64763562-8f481580-d540-11e9-89fa-dc5b693915ac.png)
