### ISSUE TITLE
Unable to create EKS cluster

### ISSUE THREAD

**Issue by Lazy-Y** [rancher/rancher#14033]
**Rancher versions:**
rancher/server or rancher/rancher:2.0.2
rancher/agent or rancher/rancher-agent:

I got this error when I trying to create EKS Cluster:
`Error creating stack: error creating master: ValidationError: S3 error: The specified key does not exist. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html status code: 400, request id: ccf012e3-71cd-11e8-9df2-7d17fe3b135d
--`
anyone has idea?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13857
