### ISSUE TITLE
kublet  uodate k1.10 error

### ISSUE THREAD

**Issue by zhangjd0411** [rancher/rancher#14040]
*Describe your issue here*
kubernetes upgrade v1.10 error

kubelet upgrade error
Upgrading (Container should have been running but is in error state. Check logs for more information.: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate")

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.17` Cattle: `v0.183.49` UI: `v1.6.42` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`service.containers`|

**Comment by superseb** [comment]
What version are you upgrading from, what OS and kernel are you using and what Docker version are you running (`cat /etc/os-release`, `uname -r`, `docker info`)

**Comment by legolas-zeng** [comment]
I have the same problem,my os infomation is -- 
```
cat /etc/os-release ----- CentOS Linux release 7.5.1804 (Core)
uname -r ----- 3.10.0-693.el7.x86_64
docker info -----
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.64GiB
Name: k8s-node1
ID: 4GNG:JLRV:ZCZC:BYXY:KZ2D:ZGZF:SOLN:7EHD:J3AS:MXHT:INQ4:MADW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://2065c27d.m.daocloud.io/
Live Restore Enabled: false

```

**Comment by till** [comment]
Reporting the same issue:

```
# cat /etc/os-release 
NAME="RancherOS"
VERSION=v1.4.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.0
PRETTY_NAME="RancherOS v1.4.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
# uname -r
4.14.32-rancher2
# docker info
Containers: 23
 Running: 22
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.32-rancher2
Operating System: RancherOS v1.4.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.685GiB
Name: destruction
ID: OYSG:N4E5:DYVV:7CCG:CZO6:AMGT:L5Q5:4CIP:YYRN:WOMR:L6J4:7VBM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by till** [comment]
To add to my previous comment, this is a brand new install:

 - downloaded RancherOS yesterday
 - single node install
 - installed rancher server first
 - added the same host to it
 - created a new environment with Kubernetes template

cc @superseb

**Comment by till** [comment]
Ok, did `ros engine enable docker-17.12.1-ce` which bricked my ssh-login (I think). 😠 

Finally I fixed the above by going into rancher-server, finding the kubelet service and _upgrading_ it. On the upgrade screen, go to volumes changed `rprivate` to `rshared` for `/var/lib/docker`.

Happy to test a new release, etc. later. But now kubelet starts and along all necessary containers that have been waiting for it.

**Comment by till** [comment]
Related: https://github.com/moby/moby/pull/36055

**Comment by superseb** [comment]
`latest` and `stable` can be the same when `latest` gets promoted to stable. In this case with `v1.6.18`. The supported Docker versions for k8s are 1.11,1.12,1.13 and 17.03 and does not include 18.03 at the moment.

**Comment by till** [comment]
@superseb Yep, it seems that kubernetes  like `ros engine enable` didn't help. Is there a page that lists all the dependencies required when I setup an environment with Kubernetes? I want to extend my cloud-init so it starts with the correct docker, version etc..

I will start from scratch since I can't log in anymore to change it again.

**Comment by till** [comment]
https://rancher.com/docs/rancher/v1.6/en/hosts/ < I also found this page after extensive Google-fu.

@superseb Thank you! Should I open a feature request for "don't install kubernetes on host that runs unsupported version"?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
