### ISSUE TITLE
Creating ingress for GKE in rancher UI does not work correctly

### ISSUE THREAD

**Issue by m1k3ga** [rancher/rancher#14042]
**Rancher versions:**
rancher/server or rancher/rancher:2.0.2
rancher/agent or rancher/rancher-agent:2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):1.10.4-gke.0

**Docker version: (`docker version`,`docker info` preferred)** Docker version 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Rancher server: 4.13.0-1019-gcp
Nodes: 4.14.22+

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**: GCE, GKE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Rancher instance (via GCE), 2 nodes in GKE cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Catlle

**Steps to Reproduce:**
When uploading a service deployment yaml, a workload gets geployed. It is visible with correct values in "Service Discovery" (with cluster ip and external ip) as well as in "Load Balancing" (L4 Balancer).
Then i tried to do the same by using rancher UI solely by adding an "Ingress" (Load Balancing) or "Record" (Service Discovery). I tried several combinations of the parameters with no success

**Results:**
I get an "L7 Ingress" in Load Balancing and a service at port 42 (?) instead of 8080, but nothing like the working yaml file when uploaded.

So my question is: How does the Service Discovery and the Load Balancing work in rancher UI to get the same result (with external IP, L4 Balancer, correct port)?

**Comment by m1k3ga** [comment]
A manual deployment via rancher UI creates a service entry. But i can't expose this service with a public IP within the Load Balancing section. 
For me, it seems the rancher UI and the yaml files are not interchangeable, since yaml files have more features to configure.

**Comment by Lazy-Y** [comment]
I also got the same issue.

**Comment by deniseschannon** [comment]
Ports need to be open on your nodes on the GKE side as well as when the ingress is created, it'll take awhile to get created in GKE.
