### ISSUE TITLE
Upgrading Deployment with HostPort results in infinite pod fail/restart loop

### ISSUE THREAD

**Issue by nathanweeks** [rancher/rancher#14048]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.2
rancher/agent or rancher/rancher-agent: v2.0.2

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.4.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Steps to Reproduce:**

1. Deploy Workload menu
2. Use HostPort to map some "Publish the container port" to some "On listening port"
3. Use "Node Scheduling" to run workload on a specific node (this was a multi-node deployment, though I suspect a single-node deployment would have the same issue)
4. Launch
5. Edit the deployed workload
6. Change something (e.g., set an environment variable), then click "Upgrade"

**Results:**

Pods will fail & be restarted in an infinite loop, rapidly filling up the relevant portion of the Rancher UI. 

```
$ kubectl describe  pods  <POD_NAME> --namespace=<NAMESPACE>
...
Events:
  Type     Reason            Age   From                            Message
  ----     ------            ----  ----                            -------
  Warning  PodFitsHostPorts  57s   kubelet, <HOST_NAME>  Predicate PodFitsHostPorts failed
```

**Comment by vincent99** [comment]
There's nowhere to do a rolling update in that situation because that's the only host eligible and the port is already in use.  Use the `Recreate` upgrade strategy instead.

**Comment by nathanweeks** [comment]
I can understand why it wouldn't make sense to do that. But a suggestion would be to consider adding a check in the UI to keep someone (especially noobs) from shooting themselves in the foot...

**Comment by vincent99** [comment]
That's not really very practical, there's an endless supply of guns lying around.

For example you could do the same with host labels instead of a specific node, or no selector at all but there's only one node, or that port is in use by an external process, or all the other nodes are already full, or you reserved more than half of the cpu/memory of the node for that container, etc.
