### ISSUE TITLE
Azure AKS Support - missing azure-native monitoring and custom tags

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14045]
From Monitoring
No ability to turn on Azure-Native monitoring
![image](https://user-images.githubusercontent.com/942110/39838631-c6b83b6a-538e-11e8-9e0f-bcf4acd5f5da.png)

From Tagging
No ability to create custom tags
![image](https://user-images.githubusercontent.com/942110/39838673-e22e04b0-538e-11e8-9967-311019361f59.png)

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/issues/15697
