### ISSUE TITLE
Incorrect ipaddress injected to Ingress address.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14056]
**Rancher versions: Build from master
Steps to Reproduce:

Create a cluster with ingress node selector set

"nodeSelector": {
"test1": "ingress"
},
Add node (h1) to the set up without the ingress node selector label.

Deploy workload.
Create ingress pointing to this workload.
Ingress gets created successfully and gets to "active" state.

At this point, there is no ipaddress injected to ingress as expected  when examining ingress as:
```> kubectl get ingress  -o wide```

When I add a new host (h2)  to the cluster with ingress node selector label , then the existing ingress and the new ingress have ip address of both h1 and h2. 
Expected Behavior:
Ingress should have only h2 ipaddress in this case.

**Comment by orangedeng** [comment]
Might duplicate issue to https://github.com/rancher/rancher/issues/14052

**Comment by orangedeng** [comment]
@deniseschannon I think we have solved this issue in https://github.com/rancher/rancher/issues/14052.

**Comment by galal-hussein** [comment]
rancher/rancher:master at Aug 1st

I followed the same @sangeethah 's  steps  and i was able to see only the address of the second node to appear correctly.
