### ISSUE TITLE
[CLI] mem_limit breaking cli

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#14059]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.14
rancher/agent or rancher/cli: v0.6.9

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Suse Linux 12 - 4.4.114-94.11 (4309ff9) x86_64 x86_64 x86_64 GNU/Linux

**Steps to Reproduce:**
create stack with the following contents:
```
version: '2'
services:
  web: 
    mem_limit: 268435456000
    image: nginx
```
**Results:**
1. cli errors out, following error logged:
```
ERRO[0002] Failed Creating web : json: cannot unmarshal number 2.68435456E11 into Go value of type int64
ERRO[0002] Failed to start: web : json: cannot unmarshal number 2.68435456E11 into Go value of type int64
FATA[0002] json: cannot unmarshal number 2.68435456E11 into Go value of type int64 
````

**Comment by StrongMonkey** [comment]
@aemneina Can we collect the cli output by adding two things?
1. add `export RANCHER_CLIENT_DEBUG`
2. add --debug flag. Example: `rancher --debug up`

**Comment by deniseschannon** [comment]
Confirmed with the end user that was having this issue that v0.6.11-rc2 has fixed the issue.
