### ISSUE TITLE
Host field should be mandatory in SSL section of Add ingress page

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#14051]
- Select cluster, project, namespace
- Add an Ingress
- In SSL section, there is a Host field. If I use a STAR/Wildcard certificate, the Host needs to be specified. This field should be made mandatory.

Without this, the ingress wouldn't work. And it becomes very difficult to debug as well.

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed
