### ISSUE TITLE
Start rancher without sll?!?

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#14063]
**Rancher versions:**
rancher/rancher : 2.0.2

**Docker version: 17.12

**Operating system and kernel: rancheros 1.4.0

**Setup details: single node rancher 

Hi, I've tried to set up a rancher/rancher on my RancherOS but I don't want a domain for this server, and I don't know how to start rancher without the need to generate a SSL certificate. I've already tried --http-only but it says: Incorrect Usage. flag provided but not defined: -http-only

What is going wrong?

**Comment by superseb** [comment]
From the docs: https://rancher.com/docs/rancher/v2.x/en/installation/single-node-install/#2-choose-an-ssl-option-and-install-rancher

```For security purposes, SSL (Secure Sockets Layer) is required when using Rancher. SSL secures all Rancher network communication, like when you login or interact with a cluster.```

Automatically generated certificates is built in, and don't need any additional parameters. https://rancher.com/docs/rancher/v2.x/en/installation/single-node-install/#option-a-default-self-signed-certificate

**Comment by MSandro** [comment]
Thank you very much, but why do I get this message on adding the agent??

This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Data does not contain any valid RSA or ECDSA certificates

**Comment by rcdailey** [comment]
@superseb It makes perfect sense to disable SSL when behind a reverse proxy; the proxy provides SSL while the internal services are unencrypted. Why waste CPU cycles on 2 layers of encryption? At the very least, can I disable HTTPS redirect on port 80?
