### ISSUE TITLE
EKS bugs for v2.0.3

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14064]
Version: master 6/19

- Regions should be limited to `us-east-1` and `us-west-2`
- After entering Region, Access Key and Secret Key the button is `Next: Authenticate  & select a network` which is false, because you can select `Instance Type`, Min and Max ASG size

<img width="1269" alt="screen shot 2018-06-19 at 16 00 11" src="https://user-images.githubusercontent.com/2620179/41601908-df906804-73d9-11e8-8869-7c8423abbc1e.png">

**Comment by deniseschannon** [comment]
Please test that the different regions launch different AMIs, as well as the fact that the instance type and ASG group sizes work correctly.

**Comment by deniseschannon** [comment]
@westlywright it looks like the remaining open item is that ASG min and max size isn't being passed through with the UI.

**Comment by superseb** [comment]
Creating EKS via Rancher:
* Clicking "Next: Authenticate & configure nodes" shows the wrong loading message in that button (`Loading Availablility Zone and VPC info from EC2...`)
* When Cloudformation fails (ROLLBACK_COMPLETE), it keeps retrying but will never get out of the loop because the initiated stack is in ROLLBACK_COMPLETE and cant be re-submitted. In my case, VPC limit reached, deleted a VPC to create room, but it never recovered.
* Provisioning status is not shown in UI, container logs shows steps (Bringing up vpc, Creating service role, creating EKS cluster) but this is not shown in UI. As EKS can take a long time to provision, feedback is wanted.
* We create a VPC using cloudformation and subnet in each availability zone, and use all these subnets in the creation of an EKS cluster. Sometimes (most of the time in us-east-1) this fails because there is no capacity in one of those AZ's (so 1 subnet cannot be used). As we automatically use all subnets, if AWS has no EKS capacity in every AZ, you cant use Rancher to provision EKS. The error shown is `"http response code was: 400"`, which is also not helpful. Region us-east-1 didnt have capacity when testing so havent tested this region.
* Instance type works, Min/max asg size works
* Creating `LoadBalancer` works as ELB
* Ingress does not work as ingress seems to be WIP for EKS
* Delete cluster initiates removal of used resources but they task is only kicked off and not validated.

Import EKS as Imported cluster:
* Tested using setting up EKS manually with worker nodes, ran the import command and cluster was green. Can do the same as when it was created using EKS integration

**Comment by westlywright** [comment]
I've made changes to the ui text that will go into the next build.

**Comment by soumyalj** [comment]
Tested with rancher v2.0.3-rc2. 
Regions are limited to us-east-1 and us-west-2
The button correctly reads as "Authenticate and configure nodes"

<img width="1482" alt="screen shot 2018-06-21 at 1 41 13 pm" src="https://user-images.githubusercontent.com/18536626/41744552-f07ee516-7558-11e8-959a-6a6e6d01164e.png">

Tested for different instance types(Ex:m3.large, m4.large etc) and different ASGs 2, 3
<img width="1323" alt="screen shot 2018-06-21 at 2 04 52 pm" src="https://user-images.githubusercontent.com/18536626/41745556-27ab72c2-755c-11e8-86e8-d8ad2aa11259.png">
