### ISSUE TITLE
rancher2.0 how to enabled logging

### ISSUE THREAD

**Issue by jiuchongxiao** [rancher/rancher#14060]
rancher2.0 how to enabled fluentd logging?

**Comment by jiuchongxiao** [comment]
@deniseschannon  can you help me?

**Comment by superseb** [comment]
Pinging people directly within a day is not really nice. In your Cluster you can enable logging via Tools -> Logging and pick an option, hit Save to enable. In your Project, you can enable logging via Resources -> Logging.
