### ISSUE TITLE
EKS provisioning " No node instance role returned in output: <nil> "

### ISSUE THREAD

**Issue by akabdog** [rancher/rancher#14079]
**Rancher versions:**
rancher/server or rancher/rancher: master (f67b3e7)
rancher/agent or rancher/rancher-agent:

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Deployed rancher from master today, single instance in docker
`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher --name rancher rancher/rancher:master`

**Steps to Reproduce:**
Create cluster in us-west-2 with min1 max6 worker nodes in the UI
**Results:**
Attempting to provision for some time, then receive error in the UI
` No node instance role returned in output: <nil> `
No additional errors in docker logs.
In AWS I see the EKS clusters.
Not sure if its useful but in cloudtrail I see:
```
create role : c-pbnt7-eks-service-role-AWSServiceRoleForAmazonEK-11MSKIG79RP18
attach policy AmazonEKSServicePolicy to ^
get role: ^
list attached role policies: ^
list role policies: ^
get role: ^
EC2 keypair create
createStack:  "templateURL": "https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/amazon-eks-nodegroup.yaml" ,         "stackName": "c-pbnt7-eks-worker-nodes"
create SG: c-pbnt7-eks-worker-nodes-NodeSecurityGroup-WSZNDZ04F43H
attach role policy: AmazonEKS_CNI_Policy to c-pbnt7-eks-worker-nodes-NodeInstanceRole-249ULB4WI63M
attach role policy: AmazonEC2ContainerRegistryReadOnly to c-pbnt7-eks-worker-nodes-NodeInstanceRole-249ULB4WI63M
attach role policy: AmazonEKSWorkerNodePolicy to c-pbnt7-eks-worker-nodes-NodeInstanceRole-249ULB4WI63M
create Role: c-pbnt7-eks-worker-nodes-NodeInstanceRole-249ULB4WI63M
get role: c-pbnt7-eks-worker-nodes-NodeInstanceRole-249ULB4WI63M
list role policies: c-pbnt7-eks-worker-nodes-NodeInstanceRole-249ULB4WI63M
create instance profile: c-pbnt7-eks-worker-nodes-NodeInstanceProfile-5U8XVHLN411I
add role: c-pbnt7-eks-worker-nodes-NodeInstanceRole-249ULB4WI63M to c-pbnt7-eks-worker-nodes-NodeInstanceProfile-5U8XVHLN411I
delete role: c-pbnt7-eks-worker-nodes-NodeInstanceRole-249ULB4WI63M
```

**Comment by superseb** [comment]
It tries to retrieve `NodeInstanceRole` from the outputs of the Cloudformation Stack, what is the state of that Stack and what is in the Output and Events of the Stack

**Comment by akabdog** [comment]
Looks like:
```
22:24:46 UTC-0700 | CREATE_FAILED | AWS::AutoScaling::LaunchConfiguration | NodeLaunchConfig | AMI  cannot be described (Service: AmazonAutoScaling; Status Code: 400;  Error Code: ValidationError; Request ID:  68ed7171-7513-11e8-b4f3-25b804be4664)
```
In parameters it says "NodeImageId = ami-e09b0098" 
What image should we be using? Based on https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html the "Amazon EKS-optimized AMI ID" is ami-73a6e20b

thanks for the help

**Comment by superseb** [comment]
Those have been configured in the code, can you try `v2.0.3-rc2` to make sure you are not using old code?

**Comment by akabdog** [comment]
v2.0.3-rc2 works, thanks!
