### ISSUE TITLE
Rancher Custom Cluster specify to not install nginix ingress

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#14074]
Hello, 

We are using rancher 2.0.2 and I was wondering if there was an option to not install the nginix ingress when creating a custom cluster using the rancher agent install.

**Comment by superseb** [comment]
When using RKE, this can be done using:

```
ingress:
  provider: none
```

In the next release we have https://github.com/rancher/rancher/issues/13076, where you can specify that in the UI.

**Comment by develar** [comment]
Interesting, that it doesn't work (`provider: none`). Will try new release :)

**Comment by develar** [comment]
Ok, I found a way:

```
ingress: 
  node_selector: 
    boo: "foo"
  provider: "none"
```

As no nodes with "boo: foo", nginx controller is not active on any node :)

**Comment by superseb** [comment]
It's on cluster creation. It will be disabled but not removed if you run in through Edit Cluster, I have opened https://github.com/rancher/rancher/issues/14386 for this. You can manually remove the ingress using `kubectl delete ds,deploy,pod,svc -n ingress-nginx --all` and `kubectl delete ns ingress-nginx`.
