### ISSUE TITLE
Invalid Client ID results in 404 in GitHub. After closing the pop-up, nothing changes in Rancher

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1407]
v0.25.0

1. Attempt Access control with an invalid client ID.

Result: 404 in GitHub. If I close the pop-up, the button still remains inactive and "Waiting to hear back from Github". 

Expected Result: If it's a 404, we should know that it means invalid client ID and provide feedback to user.

**Comment by vincent99** [comment]
Not sure this is still relevant, it's not a popular anymore

**Comment by tfiduccia** [comment]
Are you saying you won't fix?  Because it still does same thing.

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
