### ISSUE TITLE
EKS targeted availability zone does not currently have sufficient capacity to support the cluster

### ISSUE THREAD

**Issue by andrvin** [rancher/rancher#14093]
**Rancher versions:**
v2.0.3-rc1

**Steps to Reproduce:**
Create EKS cluster in us-east-1 Available Zone.

**Results:**
Rancher pending in provisioning state with the error "Error posting cluster: http response code was: 400"

It seems that now us-east-1c Available Zone on AWS is not available to use in EKS cluster.
When I try to create EKS cluster manually I get an error:
"UnsupportedAvailabilityZoneException
Cannot create cluster 'production-test' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d"

Is there any workaround of this issue?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/14064, `master` and `rc` tagged images are for internal testing.

**Comment by josenobile** [comment]
This bug still happening.
