### ISSUE TITLE
Can not update name for registry, config map and secret

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#14094]
rancher/rancher:master 06/19

Steps to reproduce:

1. Create a registry/config map/secret.
2. Edit the name for registry/config map/secret.
3. Refresh the browser

Results:

UI still shows the old name.

**Comment by loganhz** [comment]
UI sends the new name to backend. But backend doesn't populate it.

**Comment by kinarashah** [comment]
@loganhz k8s doesn't allow editing names of these resources, name in schema is set to `update: false` and and when I try editing after viewing in API - I can't edit name. Guess we need to restrict update from UI, like name of a workload?

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
