### ISSUE TITLE
Helm and Machine links and versions should be correct

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14103]
Version: v2.0.3-rc1

Links and versions are incorrect for Helm and Machine in the Version screen.

<img width="523" alt="screen shot 2018-06-20 at 20 01 16" src="https://user-images.githubusercontent.com/2620179/41676113-e3e821c6-74c4-11e8-803e-7731cf0eb584.png">

**Comment by sangeethah** [comment]
Tested with v2.0.5-rc1.

Helm and Machine links shows correct versions:

```
Helm | v2.8.0-rancher3
Machine | v0.14.0-rancher4-1

```
