### ISSUE TITLE
Support http:// for GitHub Enterprise

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1410]
We currently assume https:// for talking to the GitHub Enterprise endpoint, but when you install GHE it defaults to http://.

Requires rancherio/cattle#657

**Comment by deniseschannon** [comment]
@vincent99 Now that rancher/cattle#657 has been merged, could we add this in? Just stumbled upon it while trying to test GHE.

**Comment by tfiduccia** [comment]
Version - master 3/17
Does not work.... I check the box and add http://ghe.rancher.io/ into the Enterprise Host* field and it's directing to https://http//ghe.rancher.io//login/oauth/

**Comment by tfiduccia** [comment]
Version - master 3/22
Not fixed.  Still sending to https://

**Comment by tfiduccia** [comment]
Version - 3/23
Verified fixed
