### ISSUE TITLE
How to start a container with a command?

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#14108]
## NOT A ISSUE | JUST A QUESTION ## 

**Rancher versions:**
rancher/rancher: 2.0.0

**Question:**
I'm not sure if I'm just too stupid, but here's a quick question: How/where can I start a container with command? I can't find a input field to enter a command.

Thank you very much!

Sorry for asking this here, but I don't know where elese I could get support for rancher.

**Comment by StrongMonkey** [comment]
There is a show advanced option link on the bottom left.
![screenshot from 2018-06-20 14-47-46](https://user-images.githubusercontent.com/9203378/41686454-fd42c9e0-7498-11e8-8d28-39c5971b4d01.png)

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/tree/master#support-discussion-and-community also you can join forum, rancher slack channel or freenode to discuss more.
