### ISSUE TITLE
Pipeline not using custom registry, keeps defaulting to dockerhub

### ISSUE THREAD

**Issue by dshakey** [rancher/rancher#14113]
**Rancher versions:** v2.0.2
rancher/server or rancher/rancher:  latest
rancher/agent or rancher/rancher-agent: v2.0.2

creating new pipeline to push to private docker registry not working.  you can see from log below it is using Registry: https://index.docker.io/v1/ and times out after 30mins.

**Steps to Reproduce:**
my pipeline pulls from my enterprise github, runs npm install and then tries to push to our private docker reg.
i have created custom docker registry in registry section and added password, this is selected in the pipeline but still using index.docker.io

error log

22:13:58 [Rancher_Pipeline_p-fmjs5-4] Running shell script
22:13:59 + /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
22:13:59 + /usr/local/bin/dockerd -g /var/lib/docker
22:14:00 + /usr/local/bin/docker version
22:14:00 Client:
22:14:00  Version:	17.12.0-ce
22:14:00  API version:	1.35
22:14:00  Go version:	go1.9.2
22:14:00  Git commit:	c97c6d6
22:14:00  Built:	Wed Dec 27 20:05:38 2017
22:14:00  OS/Arch:	linux/amd64
22:14:00 
22:14:00 Server:
22:14:00  Engine:
22:14:00   Version:	17.12.0-ce
22:14:00   API version:	1.35 (minimum version 1.12)
22:14:00   Go version:	go1.9.2
22:14:00   Git commit:	c97c6d6
22:14:00   Built:	Wed Dec 27 20:12:29 2017
22:14:00   OS/Arch:	linux/amd64
22:14:00   Experimental:	false
22:14:00 + /usr/local/bin/docker info
22:14:00 Containers: 0
22:14:00  Running: 0
22:14:00  Paused: 0
22:14:00  Stopped: 0
22:14:00 Images: 0
22:14:00 Server Version: 17.12.0-ce
22:14:00 Storage Driver: overlay2
22:14:00  Backing Filesystem: extfs
22:14:00  Supports d_type: true
22:14:00  Native Overlay Diff: false
22:14:00 Logging Driver: json-file
22:14:00 Cgroup Driver: cgroupfs
22:14:00 Plugins:
22:14:00  Volume: local
22:14:00  Network: bridge host macvlan null overlay
22:14:00  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
22:14:00 Swarm: inactive
22:14:00 Runtimes: runc
22:14:00 Default Runtime: runc
22:14:00 Init Binary: docker-init
22:14:00 containerd version: 89623f28b87a6004d4b785663257362d1658a729
22:14:00 runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
22:14:00 init version: 949e6fa
22:14:00 Security Options:
22:14:00  seccomp
22:14:00   Profile: default
22:14:00 Kernel Version: 3.10.0-514.26.2.el7.x86_64
22:14:00 Operating System: Alpine Linux v3.7 (containerized)
22:14:00 OSType: linux
22:14:00 Architecture: x86_64
22:14:00 CPUs: 3
22:14:00 Total Memory: 7.632GiB
22:14:00 Name: jenkins-slave-d8x47-297mv
22:14:00 ID: RH6Q:XIME:ZL5Z:JIIW:XIX4:J53I:5ZR2:6ZT2:MAHU:CJDH:FYN7:CE4P
22:14:00 Docker Root Dir: /var/lib/docker
22:14:00 Debug Mode (client): false
22:14:00 Debug Mode (server): false
**22:14:00 Registry: https://index.docker.io/v1/**
22:14:00 Labels:
22:14:00 Experimental: false
22:14:00 Insecure Registries:
22:14:00  127.0.0.0/8
22:14:00 Live Restore Enabled: false
22:14:00 
22:14:00 WARNING: bridge-nf-call-iptables is disabled
22:14:00 WARNING: bridge-nf-call-ip6tables is disabled
22:14:00 + /usr/local/bin/docker build --rm=true -f ./Dockerfile -t 00000000 . --pull=true --label org.label-schema.build-date=2018-06-20T22:14:00Z --label org.label-schema.vcs-ref=00000000 --label org.label-schema.vcs-url=
22:14:00 Sending build context to Docker daemon  587.3kB

22:14:00 Step 1/8 : FROM node:10.4.1-alpine
22:14:01 10.4.1-alpine: Pulling from library/node
22:14:01 ff3a5c916c92: Pulling fs layer
22:14:01 733d7e405ae2: Pulling fs layer
22:14:01 11af24c7e2f5: Pulling fs layer
22:14:02 11af24c7e2f5: Verifying Checksum
22:14:02 11af24c7e2f5: Download complete
22:14:02 ff3a5c916c92: Verifying Checksum
22:14:02 ff3a5c916c92: Download complete
22:14:02 ff3a5c916c92: Pull complete
22:14:04 733d7e405ae2: Verifying Checksum
22:14:04 733d7e405ae2: Download complete
22:14:06 733d7e405ae2: Pull complete
22:14:06 11af24c7e2f5: Pull complete
22:14:06 Digest: sha256:665c69f05591a87e07ee41cfc00c148311be90df4a2670c8031ed9e2bff0fff3
22:14:06 Status: Downloaded newer image for node:10.4.1-alpine
22:14:06  ---> 1a27bb341f3f
22:14:06 Step 2/8 : WORKDIR /usr/app
22:14:07 Removing intermediate container 090e5c3599d9
22:14:07  ---> 1de0e51a56bb
22:14:07 Step 3/8 : COPY package.json .
22:14:08  ---> 07bb03aefc4c
22:14:08 Step 4/8 : RUN npm install --quiet
22:14:08  ---> Running in d5f9b316723c
22:34:45 EXITCODE   0[91mnpm[0m[91m ERR! code ECONNRESET
22:34:45 [0m[91mnpm[0m[91m [0m[91mERR! errno ECONNRESET
22:34:45 npm [0m[91mERR! network request to https://registry.npmjs.org/concat failed, reason: read ECONNRESET
22:34:45 npm ERR! network This is a problem related to network connectivity.
22:34:45 npm ERR! network In most cases you are behind a proxy or have bad network settings.
22:34:45 npm ERR! network 
22:34:45 npm ERR! network If you are behind a proxy, please make sure that the
22:34:45 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
22:34:45 [0m[91m
22:34:45 [0m[91mnpm ERR! A complete log of this run can be found in:
22:34:45 npm ERR!     /root/.npm/_logs/2018-06-20T22_34_44_140Z-debug.log
22:34:45 [0mThe command '/bin/sh -c npm install --quiet' returned a non-zero code: 1
22:34:45 time="2018-06-20T22:34:44Z" level=fatal msg="exit status 1"

**Comment by loganhz** [comment]
Please try it in 2.1.1.
