### ISSUE TITLE
Elasticsearch plugin is red

### ISSUE THREAD

**Issue by yangtea** [rancher/rancher#14117]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.logging.logging`|

**Comment by yangtea** [comment]
![image](https://user-images.githubusercontent.com/24996565/41690476-5d1ca32e-7528-11e8-8fec-772d324d6abb.png)

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
