### ISSUE TITLE
Data loss on rancher 1.6

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#14125]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.15
rancher/agent or rancher/rancher-agent: 1.6.15

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

17.12.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

CentOS 7.5 - 4.4.138-1.el7.elrepo.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher HA with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Setup:
* 3 x rancher agents (hostA, hostB, hostC)
* 1 x service (serviceA) with a scale of 2 and a scheduling affinity of io.rancher.scheduler.affinity:container_label_ne:io.rancher.stack_service.name=$${stack_name}/$${service_name}
* healthcheck strategy is set to *none*.
* sidekick service for holding the actual data (serviceA-data)

Suppose the the service's containers are currently deployed on hostA and hostB. When hostB is put under maintenance, the host is deactivated and subsequently rebooted.

Given the service's strategy is set to *none*, I'd expect the instance to go unhealthy but not to be re-deployed anywhere else. Also, I'd expect that when hostB comes back up, rancher will just resume from there by starting the service instance that it was previously deployed. However, we found that rancher actually did re-schedule the service instance on hostC, thus with a brand new data volume got created! On top of that, we noticed that when we reactivated hostB, rancher actually deactivated and deleted the previous volume on hostB resulting in data loss!

We had a similar problem with an another service having a scale of 3. The only difference is that rancher could not re-schedule the service on any host because of the hard scheduling label. What we noticed is that the service instance didn't have any host (blank) under the service details. When we re-activated the host, the service instance got re-scheduled on it but rancher deactivated and deleted the previous volume! Data loss again!

**Results:**

Data loss...

**Comment by flopezlasanta** [comment]
+1

**Comment by Hitesh-Agrawal** [comment]
+1 , this is fruastrating , can someone review this ASAP.

**Comment by silviupanaite** [comment]
+1

**Comment by cjellick** [comment]
Health checks and general service reconciliation are not one-in-the-same. A health check is an explicit TCP/HTTP call to a container that ensures it responds as expected in an expected amount of time. Service reconciliation ensures that a service is always running at the prescribed scale. Service reconciliation is automatic and can be triggered by many different events. In your case @m4ce, reconciliation is being triggered by the server reboot.

@m4ce I see that you've commented on or opened a number of different issues in the area of local volume management. There may be a fundamental gap between your expectations of how Rancher should handle local volumes and what it is actually designed for. Rancher makes no guarantees about maintaining local volumes during service scheduling/rescheduling. Rancher prioritizes service scale and state over local volume management. It offloads volume data management to storage drivers designed specifically for that purpose. In other words, the only way to guarantee volume data is not lost is to use a storage driver like NFS or EBS. Another option is to use a data plane that is tolerant of failures. For example, Kubernetes uses etcd as it datastore. When Rancher deploys Kubernetes, the etcd service has a scale of 3 and uses local volumes. If an instance of that service is lost, it can be started on any eligible host and get a new volume. But, etcd can use a quorum to resolve this and bring the new instance of the service up-to-date.

**Comment by m4ce** [comment]
Thanks @cjellick - we will re-evaluate our options then.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
