### ISSUE TITLE
All Infrastructure stacks do not get upgraded on a Rancher Master/Agent upgrade

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#14122]
**Rancher versions:**
rancher/server v1.6.14 and v1.6.18

**Docker version:**
```
# docker info
Containers: 17
 Running: 17
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.3.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.637GiB
Name: ip-X-X-X-X.ap-southeast-2.compute.internal
ID: OGSD:GTTB:BJIF:IDBM:YFID:KJ4V:BYKY:OWJH:UMN2:7UFC:LG3Q:FY7N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
# 
# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel:*
```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# uname -r
3.10.0-862.3.2.el7.x86_64
#
```

**Type/provider of hosts:**
AWS

**Setup details:**
HA Rancher with External Aurora DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install Rancher v1.6.14, set the value `upgrade.manager=all` in Advanced Settings

**Results:**
If I am reading this [link](https://rancher.com/docs/rancher/v1.6/en/upgrading/#infrastructure-services) correctly, all infrastructure stacks should have been upgraded, but only below stacks were upgraded
- healthcheck
- ipsec
- scheduler

Below infrastructure stacks were not upgraded 
- ebs
- network-services

![2018-06-21_12-57-48](https://user-images.githubusercontent.com/6998650/41695531-b76b1804-7552-11e8-9a09-a700a7fbe4a1.png)

**Comment by superseb** [comment]
Is this when upgrading from v1.6.14 to v1.6.18? What are the stack versions when you start the upgrade, and what if it is finished?

What version gets offered when you click `Upgrade available`?

Do you have `rancher/server` logging of the time of upgrade?

**Comment by vikas027** [comment]
Hello @superseb ,
> Is this when upgrading from `v1.6.14` to `v1.6.18`?
> What are the stack versions when you start the upgrade, and what if it is finished?
> What version gets offered when you click Upgrade available?
Yes, this was when upgrading from `v1.6.14` to `v1.6.18`. I don't have the stacks version as of now but they are all defaults which comes with `v1.6.14` and `v1.6.18`.

> Do you have rancher/server logging of the time of upgrade?
Nope, I don't have the logs with me but this should be easily reproducible. No?

**Comment by superseb** [comment]
Does not reproduce on v1.6.14 upgrade to v1.6.18. Can you supply the versions? Based on that I can request API output to see what is going wrong.

**Comment by vikas027** [comment]
Okay, I will note down the versions in another upgrade.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
