### ISSUE TITLE
Googapi error "project 'x' has no network named "default"., badRequest

### ISSUE THREAD

**Issue by ryangood** [rancher/rancher#14127]
**Rancher versions:**
rancher/rancher

**Docker version: 17.03.2-ce**

**Operating system and kernel: cos - 4.14.22+**

**Type/provider of hosts: GKE**

**Setup details: single node rancher**

**Environment Template: Kubernetes**

**Steps to Reproduce:** 
_With a GKE cluster that has a non-standard vpc setup._

- Click the 'Add Cluster' in Rancher. 
- Select GKE. 
- Upon completion of details click 'Save'.

 

**Results: You will be presented with this error:**

> Googleapi: Error 400: project "_X_" has no network named "default"., badRequest

**Comment by ryangood** [comment]
This might be a feature request I guess. The ability to choose the network for the cluster.

**Comment by anthonysiano** [comment]
Agreed.  Makes it impossible to use with a Shared VPC model.

**Comment by amandeepsadioura** [comment]
please enable IAM Service Account Credentials API in gcp.
It worked for me.

**Comment by deniseschannon** [comment]
@tfiduccia can we request what network to use when creating a cluster?

**Comment by tfiduccia** [comment]
@deniseschannon - yes we allow the network to be chosen now.  We have added it as a drop-down in the Cluster Options section for GKE
![image](https://user-images.githubusercontent.com/11514927/55992235-f21b4500-5c60-11e9-9578-caf7274b4f86.png)
