### ISSUE TITLE
Rancher 2 on Docker Desktop – default backend - 404

### ISSUE THREAD

**Issue by scriptjs** [rancher/rancher#14120]
**Rancher versions:**
rancher/server or rancher/rancher: latest/stable

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): Kubernetes: v1.10.3

**Docker version: (`docker version`,`docker info` preferred)**
Version 18.05.0-ce-mac67
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
MacOS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Docker for Desktop
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Helm chart
**Steps to Reproduce:**
https://rancher.com/blog/2018/2018-05-18-how-to-run-rancher-2-0-on-your-desktop
**Results:**
Following instructions does not result in an accessible Rancher at https://rancher.localhost
default backend - 404
This tutorial is promoted on the site and newsletter but does not work as advertised with FQDN set using hosts file.

**Comment by jgreat** [comment]
Checked the blog instructions for installs on Windows and Mac. Everything came up clean and was accessible. 

Both these tests were on clean "Factory Reset" versions of docker-for-desktop. If you're trying to do this on existing installs YMMV.

**Comment by javiergithub** [comment]
Jason Greathouse:
Many tks for the post, i can install everything but when i log to rancher the cluster creation hang with "Waiting for API to be available"
