### ISSUE TITLE
what port the rancher tools logging use?

### ISSUE THREAD

**Issue by jiuchongxiao** [rancher/rancher#14123]
is the port 24444?

kubectl logs -n cattle-logging fluentd-49xxd fluentd -f

i see the pod log of  fluentd-xx.
 <system>
    rpc_endpoint "127.0.0.1:24444"
  </system>

does it right?

**Comment by cloudnautique** [comment]
This is just an exporter of logs. That rpc endpoint is a management endpoint for fluentd, and is not meant for the end user. If you want to collect logs, you need to configure a target at either the cluster or project level in Rancher. We are not providing a user interface to view and interact with the logs.
