### ISSUE TITLE
Rancher 2 : Periodic unavailability from a node

### ISSUE THREAD

**Issue by jdall** [rancher/rancher#14124]
Having setup a k8s cluster based on bare-metal/VM systems running RancherOSv1.4, we are occasionally seeing an "Unavailable" state on a node - the state stays on for a few seconds, then changes back to active. 

It's always the same node (master1) that shows this state. And the hostname gets changed to "rancher" while the "Unavailable" state is present.

The first time we created a cluster (on the same resources) it was another node (master3) that had this issue.

Looking into the logs from the node, we find no indication of any problem.

Please find attached two screenshots - the first one showing the cluster in the normal state and the second one showing it in the problem state.
![screenshot-rancher-2018-06-21-08-50-35](https://user-images.githubusercontent.com/1101392/41702991-30e9dc5e-7532-11e8-9091-6d8f66b4e9f4.png)
![screenshot-rancher-2018-06-21-08-50-23](https://user-images.githubusercontent.com/1101392/41702990-30ce8ff8-7532-11e8-82a2-507570b875ad.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.alert.index`|

**Comment by JannikZed** [comment]
I don't know, if my problem is realted to this one: 
We have alerting enabled, for example for etcd cluster. Occasionally we receive an alert email, that the etcd cluster is not running:
```
Alert Name: Alert for etcd
Severity: critical
Cluster Name: triebwork-k8s1-hetzner
Logs: HTTP probe failed with statuscode: 503
```
We have a three node etcd cluster and kubernetes is running smoothly, so I don't think that this could really be an issue.

**Comment by sn00p** [comment]
What's your cluster size? We have this problem too. 
After setting up like 50 pods under rancher command orchestration plane got completely broken with
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request
WebUI is not working. Dataplane is ok. 

It is related to huge etcd IO both disk and network. 
In log files you could find different warnings like 
`2018-06-26 15:32:18.996666 W | etcdserver: apply entries took too long [144.25025ms for 1 entries]
2018-06-26 15:32:18.996702 W | etcdserver: avoid queries with large range/delete range!
2018-06-26 15:32:20.138193 W | etcdserver: apply entries took too long [112.467284ms for 1 entries]
2018-06-26 15:32:20.138221 W | etcdserver: avoid queries with large range/delete range!
2018-06-26 15:32:21.991739 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 22.998049ms)
2018-06-26 15:32:21.991776 W | etcdserver: server is likely overloaded
2018-06-26 15:32:21.991784 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 23.056418ms)
2018-06-26 15:32:21.991793 W | etcdserver: server is likely overloaded
2018-06-26 15:32:24.259214 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 17.035168ms)
2018-06-26 15:32:24.259650 W | etcdserver: server is likely overloaded
`

**Comment by JannikZed** [comment]
Our cluster consists of three etcd nodes, one control and three workers and one rancher server. They are mixed in two different data centers of the same provider.  I’m not available this week, but I will also carefully select logs, when our nodes go offline/unavailable or when we get alert messages from rancher. From the first look, you seem to have the same issue than we have Artem

________________________________

**Comment by sn00p** [comment]
I found only one issue so far 
#13650 

Right now my Rancher is not working only dataplane.  
It's not possible to use UI or kubectl.

**Comment by galal-hussein** [comment]
@jdall on the unavailable node can you post the output of the following command:
```
docker logs etcd
docker logs kubelet
mount
```

**Comment by jdall** [comment]
Thanks, but the issue is no longer present - it helped upgrading to the next ranger version, when that was released.

**Comment by francesco2013** [comment]
This exact same thing just happened to me with version 2.1.5. One node since few days become unavailable without any clear or logged down reason. 

I have now upgraded to 2.1.6. Let's see if this fixes it as I hope. Tomorrow I will be able to see if something happened.
