### ISSUE TITLE
"Service Discovery" gets not updated when a new exposed deployment is available

### ISSUE THREAD

**Issue by m1k3ga** [rancher/rancher#14128]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.4

**Docker version: (`docker version`,`docker info` preferred)**
Node: 17.03.2-ce, build f5ec1e2
Rancher server: 17.03.2-ce, build f5ec1e2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 4.14.22+

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** GCE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher with one-node cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Deploy a workload, then a service.
Go to "Workloads" - "Service Discovery"
Then delete the service (via kubectl delete svc <SERVICE>)

**Results:**
The Load Balancing entry is correctly updated (removed), but the entry in "Service Discovery" is still there. (Even when you click around the tabs).

It gets updated when i go to the global name space and then select my cluster in the corresponding name space.

**Comment by loganhz** [comment]
Thanks for your feedback. This issue has been fixed in `v2.0.4`
