### ISSUE TITLE
rancher-lb remove no-tlsv10 options

### ISSUE THREAD

**Issue by 1026524749** [rancher/rancher#14126]
*Describe your issue here*
how to remove no-tlsv10 from haproxy.cfg ？
I remove it from haproxy.cfg and haproxy_new.cfg,
but when i restart container ,haproxy and haproxy_new.cfg was edited。

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
