### ISSUE TITLE
After rancher upgrade, scaling up a workload creates new pods as part of scale up

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#14136]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.2 to v2.0.3-rc2 

**Steps to Reproduce:**
1. Create a cluster in v2.0.2. 
2. Create workloads wk1 with scale 2
3. Upgrade rancher to v2.0.3-rc2
4. Scale up the workload from 2 to 3

Three new pods are created and the original two are removed. 
New pods are created and the old ones are deleted. 
<img width="1341" alt="screen shot 2018-06-21 at 1 07 05 pm" src="https://user-images.githubusercontent.com/18536626/41742835-0955f93a-7554-11e8-928e-bca55a56a1fd.png">

**Comment by alena1108** [comment]
@StrongMonkey happens because in 2.0.3 we started adding affinity with empty value on update:

```
"spec": {
                "affinity": {},
                "containers": [
                    {
```

If inserting affinity is absolutely necessary fix, then we should document the fact that any update for workload created prior to 2.0.3, will result in pods recreation.

**Comment by deniseschannon** [comment]
This is a design change that we need to implement to be able to change scheduling rules on workloads, so we will release note it.

**Comment by xiaoluhong** [comment]
@deniseschannon  Hi. Rancher v2.0.5、v2.0.6,  There are similar problems when configuring multiple environment variables.
