### ISSUE TITLE
Unable to create persistent volume on Azure manged disk

### ISSUE THREAD

**Issue by ngschroeder** [rancher/rancher#14130]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent:

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 17
 Running: 14
 Paused: 0
 Stopped: 3
Images: 10
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 105
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1013-azure
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.784 GiB
Name: xxxx
ID: BB4S:2LDC:6R24:F4WE:VYDG:FM2F:XQ2Q:VCQZ:XKGI:T3NB:FRGR:ZJJR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Attempt to create a PV using the managed disk Storage Class instructions here:

https://gist.github.com/jgreat/a0b57ddcdc1dc1d9aaef52d6dd4c9c6a

... then deploy MongoDB from the catalog.

**Results:**
The volume for the workload gets stuck in the "pending" state.  kube-controller-manager log produces this error indicating the Azure API version in the request is bad.

```
I0619 07:11:45.595352       1 pv_controller.go:1433] failed to provision volume for claim "default/testvolume" with StorageClass "test-storage": disk.DisksClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2016-04-30-preview' is invalid. The supported versions are '2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
I0619 07:11:45.595525       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"testvolume", UID:"240585c4-733a-11e8-8ab7-000d3a1bd2dc", APIVersion:"v1", ResourceVersion:"25209", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "test-storage": disk.DisksClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2016-04-30-preview' is invalid. The supported versions are '2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

**Comment by ngschroeder** [comment]
We discovered this failed when using the Standard D2 v2 size VM for the cluster, but when we switched to Standard D2s v3, it worked.

**Comment by superseb** [comment]
Thanks, I created https://github.com/rancher/docs/issues/544 to have this in the documentation.
