### ISSUE TITLE
change default networking to flannel

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14147]
- [x] ~update default in UI - @loganhz~ https://github.com/rancher/ui/pull/1998
  - [ ] update default in RKE - @galal-hussein 
  - [ ] update docs and add docs on how to turn on project isolation with canal.  - @MBishop17

**Comment by dnauck** [comment]
Can you please explain why the default is changed? Has canal issues?

**Comment by sheng-liang** [comment]
Most users don't care about network isolation. They like the simplicity of Flannel. Rancher's project-level network isolation caught some users by surprise. Users who want project-level isolation or more advanced network policy can always set the network option to Canal when they create an RKE cluster.

**Comment by deniseschannon** [comment]
Closing this as we are not going to be defaulting to flannel. Instead we will be changing the default to canal but removing the network policies that we add. 

there will be an option to add the network policy to enforce project isolation, which is being tracked here: https://github.com/rancher/rancher/issues/14462
