### ISSUE TITLE
After rancher sever upgrade to v2.0.3-rc2 , when cluster gets updated (control node addition) , pods from the control nodes get evicted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14145]
Rancher server version upgraded from 2.0.2 -> 2.0.3-rc2

Steps to reproduce the problem:
Fresh install of v2.0.2.
Create an RKE cluster with 1 control node/ 1 worker node and 1 etcd node.
Once cluster is created, deploy few workloads.

Upgrade to 2.0.3-rc2

Add 1 more control node to the cluster.

This results in rke rebuilding the cluster after which the existing control node becomes un schedulable and all the existing pods get evicted and recreated in other worker nodes.

```
> kubectl get events | grep kil
52m         52m          1         hellon-67bf578688-nfr4v.153a529089c2c8c9     Pod          spec.containers{hellon}     Normal    Killing                   kubelet, sangeeupgc1       Killing container with id docker://hellon:Need to kill Pod
52m         52m          1         test1dep-65d48dfc75-pprxf.153a529095eb9c5c   Pod          spec.containers{test1dep}   Normal    Killing                   kubelet, sangeeupgc1       Killing container with id docker://test1dep:Need to kill Pod
52m         52m          1         test1ds-lxdsb.153a52909c6f0d52               Pod          spec.containers{test1ds}    Normal    Killing                   kubelet, sangeeupgc1       Killing container with id docker://test1ds:Need to kill Pod
```

**Comment by deniseschannon** [comment]
@sangeethah can we also test these combos after upgrade?
```
add controlplane role to worker
add etcd to controlplane/worker
add worker to controlplane/etcd
```

**Comment by sangeethah** [comment]
Tetsted the same scenario by upgrading from v2.0.0 -> v2.0.3-rc3

Existing pods in the control plane are not getting evacuated and new pods ( as part of new workloads) is not going to the exiting control nodes as expected.

On upgrades of  existing workloads , all pods get recreated on the worker nodes as expected and get evacuated from the control plane.

1 issue relating to daemon set tracked in - https://github.com/rancher/rancher/issues/14151
