### ISSUE TITLE
Hosts view should be able to display full container name when hovering over it .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1415]
Currently , there is no way for me to know which container that is part of a service is being deployed in a particular host:

<img width="907" alt="screen shot 2015-07-07 at 1 41 43 pm" src="https://cloud.githubusercontent.com/assets/4266958/8556789/2c2c6fe2-24ae-11e5-9e3e-0f269b7c85e9.png">

Can we allow for showing the full container name when hovering over the container name or  anyother action?

**Comment by demarant** [comment]
long container names issue also described in #3406

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed/added
