### ISSUE TITLE
[rancher-catalog] Prometheus package typo

### ISSUE THREAD

**Issue by stiks** [rancher/rancher#14155]
**Rancher versions:**
rancher/server: 2.0+

**Steps to Reproduce:**
Install Prometheus from Library. Select Grafana Persistent Volume Enabled: true. And click create.

**Results:**
It'll be stuck on creation because it's using `grafana.persistence.storageClass: longhorn` instead of `grafana.persistentVolume.storageClass: longhorn`

Longhorn storage class here is just an example

**Comment by guangbochen** [comment]
@stiks can you please refresh the catalog by clicking the refresh button in the catalog page, the value name is correct for the templates, thanks.
