### ISSUE TITLE
  Error "Namespace required" on new PV claim (cloned deployment)

### ISSUE THREAD

**Issue by jannylund** [rancher/rancher#14156]
<img width="1277" alt="screenshot 2018-06-22 12 45 29" src="https://user-images.githubusercontent.com/121457/41770906-2e016486-761c-11e8-8832-3b68f91c1c55.png">
**Rancher versions:**
rancher/rancher: v2.0.2

**Docker version: (`docker version`,`docker info` preferred)** 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.4.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher

**Steps to Reproduce:**
- Configure a default storage class and validate creating volume work nicely.
- Create a new deployment with a new volume claim -> this works well.
- Clone the deployment.
- Change to new namespace (non-existing)
- Delete the volume config and add a new one.

**Results:**
Error: "Namespace is required" pops up on clicking Define.

**Workarounds:**
This is probably a corner case, since we got at least these three workarounds.

1. Clone deployment without volume, then edit and add.
2. Create volume before and select it instead of add on the fly.
3. Create namespace before.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
