### ISSUE TITLE
Horizontal Pod Autoscaler Support

### ISSUE THREAD

**Issue by Itiho** [rancher/rancher#14159]
**Rancher versions:**
rancher/rancher: 2.0.2

In workloads/run deploy include option to autoscale PODs.

To work this is necessary deploy metrics-server in default cluster deploy

**Comment by eduardo-matos** [comment]
+1

**Comment by josenobile** [comment]
It will be useful include in the UI an interface to manage Horizontal Pod Autoscaling. 
For example:
https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/horitzontal-pod-autoscaler/

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#creating-the-autoscaler-declaratively

**Comment by loganhz** [comment]
Hi @sangeethah @bmdepesa 
This feature is not going to be in alpha1.  
We will work on it in December.

**Comment by deniseschannon** [comment]
Duplicate: Closing in favor of https://github.com/rancher/rancher/issues/19084
