### ISSUE TITLE
AKS Vnet in different resource group  (2.0.3 new feature issue)

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#14164]
Right now in 2.0.3 (RC) it assumes the custom vnet is in the same resource group that AKS is being deployed. For our corporate use case our vnet with the VPN back to our corp network is in a different resource group which is created by our cloud management team and cannot be moved to another resource group. Using the Azure portal you can specify the resource group that the vnet is part of but in rancher it is just assuming to be in the same.

Can this feature be expanded to include a optional vnet resource group field?

**Comment by nxf5025** [comment]
Hit this same issue today as well. Need to connect to an existing vnet instead of creating a new one.

**Comment by bmdepesa** [comment]
Currently blocked from testing by #14290

**Comment by bmdepesa** [comment]
Needs UI work -- vnet field is not present in cluster configuration.

**Comment by mitchellmaler** [comment]
Just to make sure, we will also be able to set the Subnet along with the Vnet?

**Comment by deniseschannon** [comment]
Yes, we're assuming that the vnet/subnet can come from a different resource group from the AKS cluster, but vnet/subnet are tied together with 1 resource group.

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/2

The cluster is getting created in the correct resource group with a vnet/subnet in a separate resource group correctly, but there are two small issues with the UI.

The help text below the virtual network field is no longer correct, as we can now provide the vnet resource group. 

The text below the virtual network resource group field is not being replaced. 

<img width="1412" alt="screen shot 2018-07-02 at 3 31 53 pm" src="https://user-images.githubusercontent.com/21316915/42189704-646c75f2-7e0e-11e8-8df6-e4062323d124.png">

**Comment by mitchellmaler** [comment]
@deniseschannon Perfect!

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
virtual network being pass and returned by API
Verified added
