### ISSUE TITLE
Rancher CLI - Unable to export cluster yml.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14160]
**CLI versions:**
v2.0.2-rc2

Unable to perform export on a cluster to retrieve yml file. Need to be able to export yml this way to utilize it for rancher up.

**Comment by StrongMonkey** [comment]
@dramich need you export code for cli to get this issue done.

**Comment by dramich** [comment]
Available with  v2.0.3-rc1. This adds `rancher cluster export` and unhides `rancher up`

**Comment by adingilloRancher** [comment]
Tested on v2.0.3-rc1. 

Created new cluster via UI. Confirmed ability to perform rancher cluster export <name> and retrieve yml via CLI.
