### ISSUE TITLE
iSCSI volumes fail to connect when different versions of open-iscsi installed on node and kubelet container

### ISSUE THREAD

**Issue by kmova** [rancher/rancher#14161]
**Rancher versions:**
Rancher Server:  v2.0.2 
```
rancher/rancher     latest              88526c7bea4e        4 weeks ago         521MB
```
The nodes had the following version of kubelet. rancher/hyperkube:v1.10.1-rancher2

**Infrastructure Stack versions:**
Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Docker version: (`docker version`,`docker info` preferred)**
```
root@worker3 ~ # docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@worker3 ~ # 
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux worker3 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hetzner

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Rancher Server. 
Kubernetes Cluster 3 node master, 4 node workers

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
- Add Hetzner node driver to Rancher ( https://github.com/mxschmitt/ui-driver-hetzner)
- Create Kubernetes cluster of 3 master + 4 worker nodes
- Install OpenEBS (via the Kubernetes helm chart)
- Apply the OpenEBS Storage Classes via rancher cli
  `rancher kubectl apply -f https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-storageclasses.yaml`
- Run the mongo stateful set
 `https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/mongodb/mongo-statefulset.yml` 

**Results:**
- The mongo0 pod remains in ContainerCreating state. The error shows:
```
iscsiadm: Could not login to [iface: default, target: iqn.2016-09.com.openebs.jiva:pvc-767b47cb-7492-11e8-9e87-9600000bf699, portal: 10.43.104.50,3260].
iscsiadm: initiator reported error (12 - iSCSI driver not found. Please make sure it is loaded, and retry the operation)
iscsiadm: Could not log into all portals
```

After analysis, found that different versions of `open-iscsi` are installed on the node and the kubelet container. 
  * kubelet has `open-iscsi/stable,now 2.0.874-3~deb9u1 amd64 [installed]`
  * node has `open-iscsi/xenial-updates,xenial-updates,now 2.0.873+git0.3b4b4500-14ubuntu3.4 amd64 [installed]`

As a workaround I removed the open-iscsi from the node, and the volumes got connected.

**Comment by adampl** [comment]
This error also happens with OpenEBS depolyed directly via Operator:
https://github.com/openebs/openebs#installation-and-getting-started

**Comment by BalaBalaYi** [comment]
I think this issue is related with:
1. https://github.com/openebs/openebs/issues/1688
2. https://github.com/openebs/openebs/issues/2243

For self testing:
Using rancher v2.1.1 deploy openebs(0.6) by catalog app. Creating a pos with pvc failed with:
![image](https://user-images.githubusercontent.com/23303886/49067023-cf623400-f25d-11e8-8e30-e5692cc164b1.png)


I upgraded the cluster with the suggestion according to the above [issue](https://github.com/openebs/openebs/issues/2243):  
kubelet:
    extra_binds:
      - "/etc/iscsi:/etc/iscsi"
      - "/sbin/iscsiadm:/sbin/iscsiadm"
      - "/lib/modules"
And everything goes fine.

**Comment by loganhz** [comment]
Thanks!
Please try https://github.com/rancher/rancher/issues/14161#issuecomment-441962949

**Comment by jparklab** [comment]
FYI, Binding /sbin/iscsiadm can fail when iscsiadm on the host depends on additional shared libraries. (e.g. host is bionic and container is built on xenial)
