### ISSUE TITLE
Include host info in the containers list view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1416]
Currently containers list view does not have information about the host on which container is running. 
Can this info be included in the  containers list view?

**Comment by vincent99** [comment]
This was added a while ago..

![image](https://cloud.githubusercontent.com/assets/753917/13799750/a024b038-eadf-11e5-8850-ab51d7c03dc5.png)

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
