### ISSUE TITLE
Create a container to cleanup cloud providers

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#14169]
Currently cloud providers are manually cleaned up which leaves unused resources for long periods of time. 

Create a container (the cleaner) that can cleanup cloud providers based off tags on resources. As an example if a droplet in DO has a tag of `keep` then allow that droplet to stay. Any other droplet would be removed when the cleaner was ran. 

Initial version could just work with DO and expand from there. 

- [ ] DO
- [ ] Google
- [ ] AWS
- [ ] Azure

**Comment by cjellick** [comment]
bills handling this
