### ISSUE TITLE
Asking for Password when changing LDAP Account Role

### ISSUE THREAD

**Issue by jbmcfarlin31** [rancher/rancher#14162]
I believe this is to be a bug, but whenever you go to change an account that was created via LDAP login from "Standard" to "Administrator" (or Custom), there are two fields labled "New Password" and "Confirm Password" that are marked with red asterisks indicated they are required. However, if you click "Save" without putting any password in, it saves the user anyway. 

**Steps to Reproduce:**
1) Sign into the Rancher UI
2) Click on "Global" > Users
3) Click on the user you want to edit that was created from LDAP
4) Click "Edit"
5) Password fields are presented, along with roles. Change the account type from Standard to Administrator
6) Click Save

**Expected Behavior:**
Not sure... maybe not submission since those fields are required? Not really sure what the expected behavior is supposed to be.

**Results:**
Successful save of the user.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`` `admin`|
|Route|`global-admin.accounts.edit`|

**Comment by tfiduccia** [comment]
Password is not required field on this page.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
