### ISSUE TITLE
There was an error validating certificates for host <ip>:2376: i/o timeout

### ISSUE THREAD

**Issue by akabdog** [rancher/rancher#14173]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.3-rc2
rancher/agent or rancher/rancher-agent: rancherOS on ec2

**Docker version: (`docker version`,`docker info` preferred)** 
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancherOS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
EC2
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes
**Steps to Reproduce:**
* Create an SG in EC2:
** Allow port 22 from the rancher host (no other ports per docs https://rancher.com/docs/rancher/v2.x/en/installation/references/ )
** Allow all traffic from itself
e.g. 
![image](https://user-images.githubusercontent.com/8573988/41799900-092547f2-7628-11e8-8f8c-47d78a8de1bb.png)

**Results:**
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "<ip>:2376": dial tcp <ip>:2376: i/o timeout

**Workaround:**
Allow 2379 from the rancher server:
![image](https://user-images.githubusercontent.com/8573988/41799933-33273330-7628-11e8-82b3-3eaa7684fefa.png)
I can proxy port 22 using the ssh bastion option but I can't proxy 2379. I'm deploying to a NAT subnet that is outside of my rancher server so I have no way to access port 2379. This means that requiring this port is a real show stopper for me, and the docs seem to have no mention of this requirement https://rancher.com/docs/rancher/v2.x/en/installation/references/
thanks for the help!

**Comment by lynic** [comment]
Met the same problem and I don't know why.

**Comment by loganhz** [comment]
Can you try it in v2.1.1, please?
Please check the port requirements in https://rancher.com/docs/rancher/v2.x/en/installation/references/

This image might also be helpful.

https://user-images.githubusercontent.com/15922119/44715367-ec993200-aab7-11e8-83f1-5c7dfefabbb9.png

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by jrwhetse** [comment]
its 2022, and I've had a rancher 2.5.16 rke downstream cluster running for months. Just went to add a new node, and now receiving this error. I cannot express the pure amount of frustration I have with mysterious errors popping up. Trying to debug what is going on when a downstream cluster node is spinning up is god awful. The node spins up and down before you have a chance to inspet what is actually happening. I have to try to take an image of the image before it shutsdown so i can then spin it up separately so I can then debug what the h is going on. Why does this have to be so difficult? What am I missing? Are the steps that happen during node provision documented anywhere?
