### ISSUE TITLE
rancher and aws eks - general questions

### ISSUE THREAD

**Issue by y0y0z** [rancher/rancher#14179]
**Rancher versions:**
2.0.3

**Docker version:**
17.03 installed by
```bash
$ curl https://releases.rancher.com/install-docker/17.03.sh | sh
```

**Operating system and kernel:**
rancher server nodes:

```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
```bash
$ uname -r
4.4.0-1060-aws
```

**Type/provider of hosts:**
aws

**Setup details:**
ha rancher with an external alb

# questions
1. using rancher with aws eks. consider this: span up 3 couchbase pods, how do i access one container web ui in order to connect all the couchbase container instances into a cluster?
    - when placing a `layer-4 load balancer` for the container web ui port, each time the web ui refreshed, the request is being served by a different container instance. eliminating the ability to access a single container in order to connect the containers into a cluster.
    - placed an ingress rule, yet it doesn't modify the security-group which is attached to the eks ec2 instances, to make the ec2 accessible to the public.
2. any idea why the `xip.io` is not working?
3. how do i integrate rancher with route53? is [rancher/external-dns](https://github.com/rancher/external-dns) enough?

**please share your wisdom :)**

**Comment by longwuyuan** [comment]
https://kubernetes.io/blog/2016/08/create-couchbase-cluster-using-kubernetes/

layer4 load balancer needs to point to exposed service ports. check kubernetes.io for kubectl expose <app> commands. different containers is what loadbalancing is. so if you may want to google for sticky sessions in kubernetes and scale = 1

xip.io works for me and many others

there is ablog on rancher.com to use route53

**Comment by loganhz** [comment]
Thanks for the report.
Please see https://github.com/rancher/rancher/issues/14179#issuecomment-399690098 and try it in v2.1.1

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
