### ISSUE TITLE
Show namespace information in POD information UI

### ISSUE THREAD

**Issue by Itiho** [rancher/rancher#14181]
**Rancher versions:**
rancher/rancher: 2.0.3

Go to workaloads-->deployment-->POD.

Include Namespace Information
![captura de tela de 2018-06-23 10-12-31](https://user-images.githubusercontent.com/7440821/41810579-fb0a0e62-76ce-11e8-9183-68f60308c4d7.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
