### ISSUE TITLE
helm charts are not getting updated

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#14186]
*Problem 1:*
- Create a custom helm catalog (with two versions say: v0.0.6 and v0.0.7)
- Push a new version to the git repo (say v0.0.8)

Expect the new version to show up in the UI, but it's failing with the following error:
```
E0624 00:09:48.870659       1 generic_controller.go:204] CatalogController demo [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template demo-python-app: templates.management.cattle.io "demo-python-app" already exists]
```

*Problem 2:*
- Deleting and creating the same repo with a different name and different contents is somehow caching the versions from the previous one.

**Comment by galal-hussein** [comment]
Tested with the latest master, i can see the catalog being updated after i push new changed to the helm git.
