### ISSUE TITLE
Rancher stack entirely unhealthy

### ISSUE THREAD

**Issue by jeff1evesque** [rancher/rancher#14182]
**Rancher versions:**
rancher/server or rancher/rancher: rancher version v0.6.9
rancher/agent or rancher/rancher-agent: current `stable` version

```bash
/home/ubuntu# docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                          PORTS                              NAMES
b824bb809d6d        rancher/agent:stable    "/run.sh run"            39 hours ago        Restarting (1) 52 seconds ago                                      rancher-agent
d7e4f5d9aa7a        rancher/server:stable   "/usr/bin/entry /usr…"   39 hours ago        Up 38 hours                     3306/tcp, 0.0.0.0:8080->8080/tcp   rancher
```

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.6
ipsec:
  - cni-driver, rancher/net:v0.13.13
  - ipsec, rancher/net:holder
network-services:
  - metadata + 1 sidekick, rancher/metadata:v0.10.2
  - network-manager: rancher/network-manager:v0.7.20
scheduler: rancher/scheduler:v0.8.3

![all-stacks](https://user-images.githubusercontent.com/2907085/41811335-be795086-76db-11e8-8eef-468288d9118d.PNG)

**Note:** the `cni-driver` is `active` in the `ipsec` stack.

**Docker version: (`docker version`,`docker info` preferred)**

18.03.0-ce, build 0520e24

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```bash
/home/ubuntu# uname -r
3.13.0-149-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Provider: AWS, behind single EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Standard `docker-compose.yml`, with corresponding `rancher-compose.yml`, kicked off by a single [`install_rancher`](https://github.com/jeff1evesque/machine-learning/blob/0c91389cbf26a99f1f683d3f294c17adaf30b488/install_rancher) install script, which streamlines the installation of docker, rancher agent/server, and fires up a rancher stack, defined by the corresponding `xxx-compose.yml` files.

**Steps to Reproduce:**

Simply run the [`install_rancher`](https://github.com/jeff1evesque/machine-learning/blob/0c91389cbf26a99f1f683d3f294c17adaf30b488/install_rancher) bash script in an Ubuntu machine.

**Results:**

The rancher server installs, and I can access rancher in the browser:

![image](https://user-images.githubusercontent.com/2907085/41811283-92f9caf4-76da-11e8-8fb0-62b8ab672ba5.png)

However, all the containers are [unhealthy](https://github.com/jeff1evesque/machine-learning/issues/3271#issuecomment-399686230). I've attained the logs for the [rancher agent](https://github.com/jeff1evesque/machine-learning/issues/3271#issuecomment-399679767) and the [rancher server](https://github.com/jeff1evesque/machine-learning/issues/3271#issuecomment-399686230). Are those useful?

**Comment by superseb** [comment]
Previous reply on Slack:

```
As pointed out before, the `rancher/agent` version is coupled with the `rancher/server` version. When automating adding hosts, you can retrieve the the agent image needed for that version instead of hardcoding it in the scripts. If using an older version of the agent and a newer version of Docker, you can run into the issue, most probably: https://github.com/rancher/rancher/issues/10502
```

There are no host added to the environment (as mentioned in the notification bar above), so the state of stacks/services is irrelevant.

- Use the agent version coupled with your `rancher/server` version as described in each release note: https://github.com/rancher/rancher/releases/tag/v1.6.18 to make sure hosts are added to an environment.
- Then troubleshoot further if it doesn't already solve it.

**Comment by jeff1evesque** [comment]
@superseb, would you happen to know if there is a formal constraint on the rancher-cli? I don't see anything in there [release notes](https://github.com/rancher/cli/releases), and wondering if this could potentially impact my installation process.

**Comment by superseb** [comment]
The mentioned `Versions` are tested/supported, for instance for v1.6.18:

```
Versions
rancher/server:v1.6.18
rancher/agent:v1.2.10
rancher/win-agent:v0.2.0
rancher/lb-service-haproxy:v0.9.1
rancher-v0.6.10
rancher-compose-v0.12.5
```

Let me know if there is an actual bug here so I can re-open.
