### ISSUE TITLE
Automatically deleted nodes should be removed from Rancher

### ISSUE THREAD

**Issue by jacobwgillespie** [rancher/rancher#14184]
**Environment:**

rancher/rancher: v2.0.3
rancher/rancher-agent: v2.0.3
OS: RancherOS v1.4.0
Cluster type: custom
Cloud provider: AWS

**Problem:**

If nodes are removed in Kubernetes, they are not removed from the Rancher server / UI.  For instance, if your cluster is configured with the AWS cloud provider and an instance is terminated, Kubernetes will automatically detect this and remove the node.  This leaves the node in the Rancher UI as "unavailable".

This is especially affected by cluster-level autoscaling where worker nodes are scaled up/down.

**Expected behavior:**

If a node is removed in Kubernetes, Rancher also removes the node from the cluster node list.

**Comment by loganhz** [comment]
I can reproduce this issue in v2.0.6

1. Add a cluster with 2 nodes
2. Remove a node by kubectl
3. Rancher UI still shows 2 nodes with available state

**Comment by frekele** [comment]
I have a similar issue. https://github.com/rancher/rancher/issues/15039

**Comment by cjellick** [comment]
@StrongMonkey or @alena1108 can you explain why this behaves this way?

**Comment by Gambler13** [comment]
Any progress on this?
I deleted a node with kubectl, now it is marked as unavailable in the Rancher UI.
Is there a way to clean up nodes manually from Rancher?

**Comment by jnicholls** [comment]
What is the workaround for removing a node from Rancher 2's state? We have custom clusters that have auto-scaling groups for ephemeral workloads, so nodes come and go. We can do deliberate node cleanup or garbage collection, but just need to understand the right ways to do this. The Rancher UI has no way to "delete" a node that is `Unavailable`, so what should we do in the meantime? Modify the state in the rancher cluster directly? Are nodes of custom clusters represented in the rancher etcd store as CRDs like clusters/users/projects/etc. are? I haven't been able to locate anything of the sort, so I am assuming not.

**Comment by daxmc99** [comment]
Hi @jnicholls,
This issue is currently being addressed but for right now there a few options. You should be able to click on the ellipsis next to the node and delete it for custom clusters (where you would normally view it in the API). You can also send the DELETE request via curl to the rancher API if you are looking for a more automated solution. 
Let me know if that works for you.

**Comment by jnicholls** [comment]
Hey @daxmc99, just to follow-up here in the GitHub issue, yes this works perfectly. Thanks! For those that are curious, there is a CRD `Node` and an api resource `nodes` under the `management.cattle.io` api group. These resources are namespaced under particular managed cluster namespaces in the Rancher cluster. This is another way to delete nodes for custom clusters, straight through the Rancher clusters' kube-apiserver, e.g. via kubectl.

For example, to list the nodes in the Rancher/local cluster: `kubectl -n local get nodes.management.cattle.io`

**Comment by daxmc99** [comment]
## Testing: This was fixed as part of https://github.com/rancher/rancher/pull/20375. #

 The spirit of this fix is that `kubectl get nodes` should accurately reflect the state of the cluster and Rancher should respect `kubectl delete node` in the UI. 

Possible ways to test:
1. Spin up custom cluster without cloudprovider
2. `kubectl delete node`
3. Ensure a node has been removed from Rancher UI and kubernetes node list
------
1. Spin up custom cluster with cloud provider
2. Destroy node in cloud provider console
3. Kubernetes should no longer list the node via `kubectl get nodes`
4. Ensure node is removed from Rancher UI

**Comment by sangeethah** [comment]
Rancher Server version - Latest build from master - `5144aa85`

Scenario 1:

Create a custom cluster(no cloud provider) with following node configuration with nodes from AWS:
2 control nodes - c1,c2
3 worker nodes - w1, w2,w3
3 etcd nodes - e1, e2, e3

1. From AWS console , stop one of the worker nodes say w1.
This node gets to "Unavailable" state in rancher server UI as expected and it is in "Not Ready" state when monitoring node list from kubectl command.
Delete the node from cluster using kubectl command.
This results in node getting removed from cluster in rancher server side as expected.
Cluster get to "updating" state when node gets removed and then get backs to "active" state eventually.

2. Delete one of etcd nodes from cluster using kubectl command.
This results in the etcd node getting removed from cluster in rancher server side as expected.
Cluster get to "updating" state when node gets removed and then get backs to "active" state eventually.

3. Delete one of control nodes from cluster using kubectl command.
This results in the control node getting removed from cluster in rancher server side as expected.
Cluster get to "updating" state when node gets removed and then get backs to "active" state eventually.

Scenario 2:

Create a custom cluster with AWS  cloud provider using following node configuration with nodes from AWS:

2 control nodes - c1,c2
3 worker nodes - w1, w2,w3
3 etcd nodes - e1, e2, e3


1. Terminate one of worker nodes from AWS console.
This results in the worker node getting removed from cluster in rancher server side as expected.
Cluster get to "updating" state when node gets removed and then get backs to "active" state eventually.

2. Terminate one of etcd nodes from AWS console.
This results in the etcd node getting removed from cluster in rancher server side as expected.
Cluster get to "updating" state when node gets removed and then get backs to "active" state eventually.

3. Terminate one of control nodes from AWS console.
This results in the control node getting removed from cluster in rancher server side as expected.
Cluster get to "updating" state when node gets removed and then get backs to "active" state eventually.

Related issue logged - https://github.com/rancher/rancher/issues/21299

**Comment by cjellick** [comment]
Does this comment represent a bug or other action that needs to be taken (other than bug 21299)?

**Comment by sangeethah** [comment]
@cjellick  The comment describes all the scenarios that were tested for validating the fix so far.
Related issue  is tracked in a different bug -#21299 .
