### ISSUE TITLE
Improve mobile user experience docs.rancher.com

### ISSUE THREAD

**Issue by scriptjs** [rancher/rancher#14192]
Hi. I don't wish to complain, but in my opinion the documentation on the site has a poor user experience. I am bringing this to your attention not as criticism, but in hopes this can be evaluated and potentially changed for the future. I understand it takes time and a great deal of work to create and present it.

Specifically, the amount of information you can read per page is very limited and this is only compounded by an excessively large header and fonts.

The mobile experience is poor. The site takes too long to load, even with a fast internet connection and newer device, the navigation is slow, and being confronted with the same large image at the top of each page is frustrating for scanning for information and context.

There are several tools available for packaging documentation that could be used to good effect that you could choose. Alternatively, I would encourage you to break from the design of your site to make the documentation more readable and consumable for users and their devices.

**Comment by superseb** [comment]
Amount of documentation is being worked on, see open PRs here: https://github.com/rancher/docs/pulls

We can take a look at mobile experience.

**Comment by scriptjs** [comment]
@superseb The available documentation is an issue, but not the reason for filing this issue. As you have pointed out, the available documentation is covered by other issues. I have read about the progress and timetable for producing it. This issue is specific to the experience of consuming it, via web or mobile which is poor and I hope will be assigned and reviewed for improvements.

**Comment by deniseschannon** [comment]
We are actively working on the layout and feel of the site. In the next couple of days, you should see definitive changes on the website. 

We will be focusing on the website before moving to change the mobile site experience.

**Comment by scriptjs** [comment]
@deniseschannon Awesome! Look forward to the improvements and thank you for taking action.

**Comment by deniseschannon** [comment]
@scriptjs We've updated the look and feel of the documentation. Please feel free to open any additional issues at our docs repo; https://github.com/rancher/docs

**Comment by scriptjs** [comment]
@deniseschannon Thank you for these efforts. They are appreciated.
