### ISSUE TITLE
Rancher V3 API Documentation

### ISSUE THREAD

**Issue by andreyderma** [rancher/rancher#14190]
Where i can find rancher v3 API documentation?

**Comment by twillert** [comment]
Hi @andreyderma 
I am also looking for this. Did you ever find the v3 documentation?

**Comment by bostrowski13** [comment]
glad i'm not the only one who can't find this.  It's nowhere in their Rancher 2.0 documentation.

**Comment by bostrowski13** [comment]
https://cdn2.hubspot.net/hubfs/468859/Rancher%202.0%20Architecture%20-%20Doc%20v1.0.pdf i

check the section on the v3 API

**Comment by chickenbeef** [comment]
Also read through the documentation posted above and didn't find anything too helpful on the v3 API.

Still unsure of what the actual endpoints to hit are, the operations (POST/GET etc) or the parameters accepted in the body.

Is there maybe some draft documentation that can be shared with us by any chance? At the moment we're just taking a stab in the dark.

**Comment by bostrowski13** [comment]
found out that the v3 api documentation that we're all looking for isn't published yet.  dont have a date either.

**Comment by andreyderma** [comment]
@twillert 
Depends on case your are looking for, what im looking was, i wanna update image deployment through API rancher from my CI/CD server, in my case i solved using kubernetes API directly.

Example:
{RANCHER_CLUSTER_SERVER}/apis/apps/v1/namespaces/{namespace}/deployments/{name}

Find all kubernetes API documentation on following page:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/docs/issues/934
