### ISSUE TITLE
[cli] flag provided but not defined: -url

### ISSUE THREAD

**Issue by ospfranco** [rancher/rancher#14199]
**Rancher versions:**
cli version 2.0

Operating system and kernel: mac os x high sierra

**Steps to Reproduce:**

When using the latest CLI version passing the `--url` flag returns this error

`flag provided but not defined: -url`

ex: 

SERVICES="$(rancher --url $RANCHER_URL --access-key $RANCHER_KEY --secret-key $RANCHER_SECRET ps | grep :staging | awk '{print $1}')"

**Comment by pascal-enz** [comment]
I am experiencing the same issue with version 2.0.2 on Windows and Linux.

It works if I only call "rancher --url...". However, as soon as I add any prefix like a full path or ./ (required in PowerShell) I get this error.

I reverted back to 0.6.9 and it works fine.

**Comment by deniseschannon** [comment]
Any CLI version that's tagged as `v2.x` is made for [Rancher 2.0, where as CLI versions `v0.x` is for Rancher v1.x.

These are 2 different server products, so please make sure to use the download link inside Rancher.
