### ISSUE TITLE
Rancher etcd recurring snapshots consume a lot of disk space  

### ISSUE THREAD

**Issue by sn00p** [rancher/rancher#14196]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.3
rancher/agent or rancher/rancher-agent: 2.0.3

I've set up rancher cluster according to official docs from 
https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/

Also recurring snapshots were enabled according to 
https://rancher.com/docs/rancher/v2.x/en/installation/backups-and-restoration/ha-backup-and-restoration/

Snapshots are creating 
...
-rw-r--r--. 1 root root 149332000 Jun 24 14:19 2018-06-24T21:19:47Z_etcd
-rw-r--r--. 1 root root 150732832 Jun 24 14:24 2018-06-24T21:24:47Z_etcd
-rw-r--r--. 1 root root 152309792 Jun 24 14:29 2018-06-24T21:29:47Z_etcd
-rw-r--r--. 1 root root 152309792 Jun 24 14:34 2018-06-24T21:34:47Z_etcd

The problem is that it each snapshot is not compressed, location of backup is not configurable and snapshots require a lot of disk space in configuration stated in documentation. 

Though I have only one cluster under rancher control each snapshot takes 150 Mb each 5 min in /opt/
directory. 
This operation also could render cluster unstable because of heavy IO during backup operations as I have multiply etcd health checks failure.  

Compressed file is 6 times smaller
-rw-r--r--. 1 root root  25497612 Jun 24 14:39 2018-06-24T21:39:47Z_etcd.gz

Also some checks could be added to rotation logic. EG alert for admin to notify about disk space is ok.

**Comment by deniseschannon** [comment]
You can change the values for etcd snapshot: 

```
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 5m0s # time increment between shapshots
    retention: 24h # time increment before snapshot purge
```

You can change how often it should snapshot to a longer interval and retention to shorter. You do not need to follow what's in the docs.

**Comment by sn00p** [comment]
I know I could change values. But snapshots are not compressed and it could be a real problem with any values  choosen.
Also this problem with etcd turned out to another one one. 
#14124 
Not sure why my cluster has so heavy IO in orchestration plane. It's not big only three nodes with 50 pods.

**Comment by superseb** [comment]
The root cause for the large snapshots is etcd being large. If you can supply your info in https://github.com/rancher/rancher/issues/14322, we can investigate this.
