### ISSUE TITLE
how could I run rancher without docker images

### ISSUE THREAD

**Issue by qingfengming** [rancher/rancher#14195]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0 +
rancher/agent or rancher/rancher-agent:v2.0+

I want to change some code,and debug. I don't know how to do,but I think if I can run code directly（Ubuntu/CentOS），things will be easier。
Any suggestions or methods will be grateful.

**Comment by superseb** [comment]
This page shows to run it into our preferred IDE Goland: https://github.com/rancher/rancher/wiki/Running-and-debugging-Rancher-2.0-from-an-IDE

Building and packaging is done in Docker but can easily be done by yourself if wanted: https://github.com/rancher/rancher/blob/master/scripts/build-server
