### ISSUE TITLE
Sidekick containers (from secondary launch config) get deployed in different hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1419]
Server version - v0.26.0-rc1
Steps to reproduce the problem:

Service with following
launchConfig:
    launch_config_service = {
        "imageUuid": SSH_IMAGE_UUID,
        "ports": [expose_port+":22/tcp"],
        "name" = "Pri"}

secondaryLaunchConfigs:
    launch_config_consumed_service = {
        "imageUuid": WEB_IMAGE_UUID,
        "name" = "Sec"}

scale 2:

When service is activated , I see that the 2 containers for primary launch config gets deployed in 2 different hosts with 2 different "io.rancher.service.deployment.unit" labels.

The 2 containers for the secondary launch config are not placed in the same hosts as the primary containers even though they are associated with the same "io.rancher.service.deployment.unit"  as the primary containers.

**Comment by sonchang** [comment]
The reason this happened was for one of the deployment units, the secondary launch config (without the port constraint) started up first.  Since there are no constraints at this point, it was launched on the same host as one of the other deployment units.  When the primary service started, there was a port conflict and so the soft affinity rule used to schedule instances within a deployment unit together was dropped.

<img width="921" alt="screen shot 2015-07-07 at 2 21 36 pm" src="https://cloud.githubusercontent.com/assets/8651231/8557814/9d4076be-24b4-11e5-8239-4795b61b968e.png">

**Comment by sonchang** [comment]
You can see the bottom one has a firstRunningTS: 1436301462000.
While the one at the top that has the port constraint has a TS: 1436301467000 (so this started up 5 seconds later).

**Comment by will-chan** [comment]
How do we fix this given the sidekick containers must be launched first and doesn't have the port conflicts.  Do we need an API to ask the scheduler that would reply with a host given all possible constraints?

**Comment by sangeethah** [comment]
Making this is a blocker issue to address the following use case:

Set up has3 hosts:
Create a Service with 1 secondary launch config and  primary launch config has anti affinity rule to itself - "labels": {
"io.rancher.scheduler.affinity:container_label_ne": "io.rancher.project_service.name=${project_name}/${service_name}"
} and a scale of 3.

Only 3 containers get launched and they get launched in 3 different host and the 4th container never gets launched since the anti-affiity rule is applied to containers from both primary and secondary launch configs.

**Comment by sangeethah** [comment]
Tested with server version - V0.27.0-rc3

Set up has 3 hosts:
Create a Service with 1 secondary launch config and primary launch config has anti affinity rule to itself - 
        "labels": {
            'io.rancher.scheduler.affinity:container_label_ne':
                "io.rancher.stack_service.name" +
                "=${stack_name}/${service_name}"
        }

When the service is started , I see that  anti-affinity being applied correctly to the containers in the primary launch config.

When exposed ports are used for services with sidekick , we expect anti-affinity scheduling to be provided explicitly.

**Comment by ashhb444** [comment]
@sangeethah hello, can you guide me how and where to set the following parameters:

launch_config = {"imageUuid": WEB_IMAGE_UUID,
                     'memoryReservation': 5000000,
                     'milliCpuReservation': 500}

are these parameters are part of compose file (yml)? 

Need your help.

Thanks
