### ISSUE TITLE
Switching scaling/upgrade policy from Rolling to Recreate throws error.

### ISSUE THREAD

**Issue by jannylund** [rancher/rancher#14191]
**Rancher versions:**
rancher/rancher: v2.0.2

**Description:**
Switching to `Recreate` policy doesn't remove the Rollingupdate configuration.

**Steps to Reproduce:**
- Create a deployment. It will default to RollingUpdate
- Edit deployment, select `Kill ALL pods, then start new`

**Results:**
- Error: `Validation failed in API: Deployment.apps "foo" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'`

**Workaround:**
Edit yaml and remove `strategy.rollingUpdate`

**Comment by loganhz** [comment]
Thanks for your feedback. 
This issue has been fixed in 2.0.3
Related issue is https://github.com/rancher/rancher/issues/13584
