### ISSUE TITLE
Can't turn off pull_image

### ISSUE THREAD

**Issue by wiredaem0n** [rancher/rancher#14193]
**Rancher versions:**
rancher/server: v1.6.18
rancher/agent or rancher/rancher-agent: v1.2.10

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7 Linux 3.10.0-693.2.2.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
   Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
   Single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
   CAttle
**Steps to Reproduce:**
   Simply creating a service that references a local image not found on docker.hub. 
   Tried both:
   - unchecking the box "Always pull image before creating.
   - setting label io.rancher.container.pull_image: never

In any case, trying to use docker-compose.yml and the only option is to set label io.rancher.container.pull_image: never but does not work.  

**Results:**
Container should have been running but is in error state. Check logs for more information.: Image [index.docker.io/local/grr-lzd] failed to pull: repository docker.io/local/grr-lzd not found: does not exist or no pull access

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
