### ISSUE TITLE
Add registry and credentials using api ? 

### ISSUE THREAD

**Issue by iojanis** [rancher/rancher#14198]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: - 
ipsec: - 
network-services: - 
scheduler: - 
kubernetes (if applicable): - 

*Docker version: (`docker version`,`docker info` preferred)*
18.03.0-ce
*Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)*
Ubuntu
*Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)*
-
*Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)*
-
*Environment Template: (Cattle/Kubernetes/Swarm/Mesos)*
-
*Steps to Reproduce:*
-
*Results:*
-

I need to add the registry and their credentials over the api... But although it's possible using 1.4, the 1.6 api (v1 and v2-beta) doesn't have the CREATE UPDATE or DELETE options.

Is there any other possibility?

**Comment by loganhz** [comment]
Create registry `POST` `/v2-beta/projects/${env_id}/registry` with payload `{"type":"registry","serverAddress":"myregistry.com"}`

Create registry credential `POST` `/v2-beta/projects/${env_id}/registrycredential` with payload `{"type":"registryCredential","registryId":"${the_created_registry_id}","email":"not-really@required.anymore","publicValue":"admin","secretValue":"password"}`

**Comment by loganhz** [comment]
Please try to create it via UI and in Chrome dev tool you can find the detailed request.
