### ISSUE TITLE
HAProxy LB 503 Returned After Container For A Service Restarts by itself (not recreates)

### ISSUE THREAD

**Issue by mjaverto** [rancher/rancher#14200]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.18
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: v0.3.6
ipsec: v0.13.13
network-services: v0.7.20 
scheduler: v0.8.3
kubernetes (if applicable): N/A
rancher/lb-service-haproxy:v0.9.1

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:13:43 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:20:43 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.80-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher with external MySQL

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. With a service that a Rancher LB (Haproxy) is routing to, cause an unhandled exception in the container that causes the container to crash and restart for that service. (Note restart, not recreate). 
2. After the container restarts, it is ready to accept connections to the host OS. It is passing rancher healthchecks, yet HAProxy returns a 503.

**The only way to fix is to:**
1. Delete the container that restarted and when a new container comes up for the service it'll be routable again.
2. Delete / recreate any other container for any service that the HAProxy instance is routing to.

**Short term solution:** 

1. Create a "fake" service in the stack with a healthcheck that will never pass
2. Create a "fake" route for HAProxy that routes to this fake service.

This continuously cycles containers because of a failing health check. When the container for this "fake" service go down to recreate and a new one is created, it refreshes/reloads HAProxy and then it can route again to the container that was restarted after an unhandled exception. 

Is there a way to force HAProxy to reload at some interval?

**Comment by mjaverto** [comment]
I've reviewed the following issues but none seem to be the same as this or were marked as resolved.
https://github.com/rancher/rancher/issues/7024
https://github.com/rancher/rancher/issues/10652
https://github.com/rancher/rancher/issues/10206
https://github.com/rancher/rancher/issues/8441
https://github.com/rancher/rancher/issues/8015

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
