### ISSUE TITLE
Rancher does not taint masters by default leading to unexpected workloads being scheduled on masters

### ISSUE THREAD

**Issue by nlowe** [rancher/rancher#14203]
**Rancher versions:**
rancher/server or rancher/rancher: `rancher/rancher` `v2.0.2`
rancher/agent or rancher/rancher-agent: `rancher/agent` `v2.0.2`

**Infrastructure Stack versions:**
kubernetes (if applicable): `v1.10.1-rancher2-1`

**Docker version: (`docker version`,`docker info` preferred)**

<details>

<summary>Docker Version</summary>

```bash
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

</details>

<details>

<summary>Docker Info</summary>

```bash
Containers: 36
 Running: 26
 Paused: 0
 Stopped: 10
Images: 16
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-128-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: master-01
ID: EQI5:BUWE:4L3T:HC6M:TR56:SZ6I:UMLK:WFQC:6QKE:I4RB:KTAO:VUDX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```ini
# /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

uname: `4.4.0-128-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal vSphere VM's

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node / internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

k8s

**Steps to Reproduce:**

Create a cluster in the rancher interface. Copy the docker adoption command for master nodes with the roles `Control` and `etcd` selected and execute on the master nodes. Copy the docker adoption command for the worker nodes with the role `Worker` selected and execute on the worker nodes. The rancher interface correctly identifies master and worker nodes.

**Results:**

**Expected**: Non-infrastructure pods are not scheduled on master nodes
**Actual**: Master nodes have no taints and thus are not excluded by default from scheduling. Additionally, infrastructure pods like `cattle-agent`, `canal`, and `nginx-ingress-controller` do not have any taint tolerations, which means correcting this requires a decent amount of manual effort.

## Notes

I expect my master nodes to only run the minimum required workloads like the cattle agent, my cni overlay, and maybe my ingress controller. However, as I start deploying applications, k8s schedules pods on my masters in addition to my workers. Inspecting the masters shows that they do not have any taints, and the required infrastructure pods do not have any tolerations. Unless I'm missing something, the difference between `Control` and `Worker` nodes in the rancher UI is purely superficial. This would be painful to correct manually, rancher should do this for you.

**Comment by superseb** [comment]
This has been changed in v2.0.3, see https://github.com/rancher/rancher/issues/13524

**Comment by nlowe** [comment]
Thanks, I didn't see that one when I was looking through existing issues.
