### ISSUE TITLE
Not able to import an existing GKE Cluster

### ISSUE THREAD

**Issue by ryangood** [rancher/rancher#14208]
**Rancher versions:**
rancher/rancher: 2.0.3

**Infrastructure Stack versions:**
kubernetes (if applicable): tried 1.8, 1.9, and 1.10

**Type/provider of hosts: GKE**

**Setup details: single node rancher**

**Environment Template: Kubernetes**

**Steps to Reproduce: Follow directions to import cluster. This includes the latest update about cluster-admin role.**

**Results: The workloads will deploy to the cluster, but the cluster does not show up in Rancher.**

**Comment by ryangood** [comment]
![screen shot 2018-06-25 at 3 30 24 pm](https://user-images.githubusercontent.com/1762152/41871363-b7fa96ae-788c-11e8-8d14-21c1eb457af5.png)
![screen shot 2018-06-25 at 3 30 32 pm](https://user-images.githubusercontent.com/1762152/41871364-b80c3198-788c-11e8-89ab-75557bb9780c.png)

**Comment by superseb** [comment]
Are the hosts able to connec to the host running the `rancher/rancher` container? What is in the logging of either of the pods, as those will log connections back to the host running the `rancher/rancher` container.

**Comment by deniseschannon** [comment]
@ryangood did you make sure to follow the pre-requisistes that are now required in importing a GKE cluster? 

http://rancher.com/docs/rancher/v2.x/en/tasks/clusters/import-cluster/

**Comment by ryangood** [comment]
turned out to be a firewall issue.
