### ISSUE TITLE
Properly handle ejecting/removing a user cluster from rancher

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#14207]
We need a process whereby a user cluster can be cleanly removed or ejected from a rancher setup. The specific observed issue is that the cattle-system namespace does not get cleanly removed. If you try to delete that namespace, objects get stuck in pending state because their finalizers that rancher added are not being removed.

A couple implementation thoughts:
- we need to investigate if this can be done cleanly from the rancher UI. In my mind, ideally if a user removes a cluster from rancher, rancher should be able to clean it up before doing the final disconnect.
- whehther or not the above is possible, we need a script that would run outside of rancher to do the same type of cleanup. If rancher goes away (intentionally or unintentionaly), we need to give users a way to bring their clusters back to a pre-rancher state.

**Comment by rossedman** [comment]
Will add these pieces to this as well:
- If a deletion of `cattle-system` happens it forever stays in a `Terminating` state
- Once this has happened, other k8s objects will start to do the same thing

**Comment by cjellick** [comment]
note to self: the idea is that we would get this version of the logic working and solid and then use it as a guide to the independent-script path.
Independent script is needed for scenarios where rancher goes away first and you have "orphaned" clusters you need to recover

**Comment by dramich** [comment]
The solution for this is to create a job that runs in the user cluster and cleans up. 

To start, rancher server will create a `clusterRole`, `clusterRoleBinding`, `serviceAccount` and `job` in the user cluster that is being removed. These are all tied together with an `ownerReference` back to the `job`. The job will run the agent image with an env var that is specific to cleanup duty. Starting with the version this is released in (2.1 at this point) the cleanup will perform more cleanup. 

Starting in 2.1 the label `cattle.io/creator=norman' will be added to every resource in a cluster that is created by norman. Prior to 2.1 there is not a deterministic way to tell if we created anything or simply updated it to add our info. 

All versions:
Remove the cattle-system namespace. 
Cleanup all other namespaces - remove finalizers, annotations and labels

2.1+
Remove roles, roleBindings, clusterRoles and clusterRoleBindings that rancher created

**Comment by sangeethah** [comment]
Tested with latest build from master:

Imported an existing rke cluster.
Create few projects with namespaces and deployed workloads in them.
Gave project member / cluster member access to few users.

Deleted the imported cluster from rancher.

1. cattle-system namespace was deleted.
2. For other namespaces that were created from rancher UI - There are no finalizers, annotations and labels in them.
There is 1 label - "cattle.io/creator=norman"  that continues to be present. Should this be deleted as well ?

```
MacBook-Pro-3:rke19 sangeethahariharan$ kubectl describe namespaces default
Name:         default
Labels:       <none>
Annotations:  <none>
Status:       Active

No resource quota.

No resource limits.
MacBook-Pro-3:rke19 sangeethahariharan$ kubectl describe namespaces mystep1-ns1
^[[AName:         mystep1-ns1
Labels:       cattle.io/creator=norman
Annotations:  <none>
Status:       Active

No resource quota.

No resource limits.
MacBook-Pro-3:rke19 sangeethahariharan$ kubectl describe namespaces mystep1-ns1
Name:         mystep1-ns1
Labels:       cattle.io/creator=norman
Annotations:  <none>
Status:       Active

No resource quota.

No resource limits.
MacBook-Pro-3:rke19 sangeethahariharan$ kubectl describe namespaces mystep1-ns2
Name:         mystep1-ns2
Labels:       cattle.io/creator=norman
Annotations:  <none>
Status:       Active

No resource quota.

No resource limits.
MacBook-Pro-3:rke19 sangeethahariharan$ kubectl get namespaces
NAME            STATUS    AGE
default         Active    36m
ingress-nginx   Active    35m
kube-public     Active    36m
kube-system     Active    36m
mynewtest       Active    25m
mystep1-ns1     Active    24m
mystep1-ns2     Active    24m
mytest123       Active    27m
MacBook-Pro-3:rke19 sangeethahariharan$ 
```
There were lot of roleBindings that were created when namespaces were created using Rancher. 
All these roleBindings were removed.

The roles, roleBindings, clusterRoles and clusterRoleBindings that are currently present in the cluster were exactly the ones that were present in the cluster before it was imported to rancher.

**Comment by sangeethah** [comment]
Tested with 2.0.8 build.

Imported an existing rke cluster.
Create few projects with namespaces and deployed workloads in them.
Gave project member / cluster member access to few users.

Upgraded to latest master build.
Deleted the imported cluster from rancher.

1.cattle-system namespace was deleted.
2. For other namespaces that were created from rancher UI - There are no finalizers, annotations and labels in them.
There is 1 annotaion - "field.cattle.io/resourceQuotaTemplateId" that continues to be present. Should this be deleted as well ?

```
Name:         mydefault1
Labels:       <none>
Annotations:  field.cattle.io/resourceQuotaTemplateId=
Status:       Active
```
roles, roleBindings, clusterRoles and clusterRoleBindings that rancher created continue to be present in this case.

**Comment by dramich** [comment]
The additional annotation has been added to master.

**Comment by sangeethah** [comment]
Tested by upgrading from v2.0.8 having a custom cluster to v2.1-rc1.
After deletion of custom cluster , there are no annotations  relating to cattle that is left behind including -```field.cattle.io/resourceQuotaTemplateId=``` .
