### ISSUE TITLE
Pipeline Pull Request event is firing for all "actions"

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14216]
**Rancher versions:** 2.0 master 6/25

**Steps to Reproduce:**
1.  Create a pipeline with trigger on new PR
2.  Create a PR - pipeline is triggered
3.  Label the PR as a duplicate - pipeline is triggered

**Results:**  Basically there are many "actions" related to the Pull Request webhook.  It should only fire when on commits for PR (like initial, rename, edit PR) 
![image](https://user-images.githubusercontent.com/11514927/41880674-4a50037a-7894-11e8-8d5e-7e30767e4ad4.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/5

Pipeline is not being triggered for adding/removing labels, editing name, or assigning / un-assigning.
