### ISSUE TITLE
Cloned pipeline's webhooks don't get deleted

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14219]
**Rancher versions:** 2.0 master 6/26

**Steps to Reproduce:**
1.  Create a pipeline that automatically builds on git commit
2.  Clone that pipeline
3.  In pipeline list page.  Check both pipelines and click on delete button

**Results:**  Both pipelines delete, but if you go to webhook page in github, only 1 deleted.   Looks like cloned pipeline webhooks, don't delete?

**Comment by gitlawr** [comment]
Close this as we don't have clone action for pipeline now.
