### ISSUE TITLE
503 service unavailable body

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1421]
The current load balancers return a html/text body for 5xx gateway errors. It would be nicer to return no body (just the status code in the http response). This helps avoid ugly pages (white page is at least nicer for the user). It also avoids breaking any parsing assumptions for load balancers in front of APIs that might break when they expected a json or other API response and got something that wasn't that.

<img width="409" alt="screen shot 2015-07-07 at 2 56 10 pm" src="https://cloud.githubusercontent.com/assets/84792/8558454/257b442e-24b9-11e5-840a-2a9cb352290f.png">

Separate issue is one of customizing the error pages but that is more high level and easily punted.

**Comment by alena1108** [comment]
Removed the UI tag; purely haproxy configuration.

**Comment by alena1108** [comment]
As its a part of more generic enhancement (https://github.com/rancher/rancher/issues/1871), going to keep track of it there
