### ISSUE TITLE
Load Balancer service always shows as Pending under Load Balancing tab

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#14211]
Steps to reproduce:

* provision GKE cluster
* create a workload with the port of type Load Balancer (L4)
* wait till public endpoint gets populated on the workload
* switch to Load Balancing tab. The LB service created for the workload, gets displayed there (along with ingresses that can be created directly from that tab)

Bug: the Load Balancer service under `Load Balancing` tab always shows as Pending. If you view it via Rancher APIs, its state is Active, Transitioning=No

**Comment by alena1108** [comment]
Also noticed that we the title says Pod, for both ingresses and lbs
<img width="852" alt="screen shot 2018-06-25 at 1 46 54 pm" src="https://user-images.githubusercontent.com/1562176/41874949-42bca4c6-787e-11e8-8496-5bac9f5aac63.png">

**Comment by alena1108** [comment]
@loganhz feel free to reassign to me with label api for ui if you find it's an api issue.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/41890311-99c6380e-7941-11e8-810b-3629e707fbd1.png)
hi @alena1108 , fixed the group by issue.

But I can not recreate the `pending` issue.

**Comment by alena1108** [comment]
@sangeethah could you validate that the both issues mentioned in the bug, are resolved

**Comment by soumyalj** [comment]
Tested with master.
Created a workload with port of type L4 loadbalancer.
Once the public endpoint was populated, the loadbalancer service showed as active and was functional
Also, the title showed the namespace as expected .
![screen shot 2018-08-02 at 10 23 56 am](https://user-images.githubusercontent.com/18536626/43600285-0c1cfdce-963f-11e8-913c-acac8aeec3eb.png)
API info below
```
"selector": {
"workload.user.cattle.io/workloadselector": "deployment-default-workload1"
},
"sessionAffinity": "None",
"state": "active",
"targetWorkloadIds": [
"deployment:default:workload1"
],
"transitioning": "no",

```

**Comment by mrfelton** [comment]
If I set one of the ports for a workload to L4 LoadBalancer no loadbalancer gets created at all and I don't get an external IP address

**Comment by Med-All** [comment]
Same problem here. Is there any documentation or tutorial how to set this up for an example Wordpress app launched from the Helm Charts?
