### ISSUE TITLE
[cli] 

### ISSUE THREAD

**Issue by palbiez** [rancher/rancher#14223]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.3
rancher/agent or rancher/rancher-agent: v2.0.3

**Docker version: (`docker version`,`docker info` preferred)** 
Containers: 23
 Running: 11
 Paused: 0
 Stopped: 12
Images: 34
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 255
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
Kernel Version: 4.4.0-128-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.55 GiB
Name: rancher
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Experimental: false
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS kernel 4.4.0-128-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Multinode rancher with 1 Master and 3 Workernodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
If we use the command `rancher kubectl` we get the message 
`FATA[0000] kubectl is required to be set in your path to use this command. See https://kubernetes.io/docs/tasks/tools/install-kubectl/ for more info. Error: exec: "kubectl": executable file not found in $PATH`
but we don't know in which container we can add the config file. Because if we add config at ~/.kube/config we still get this error message.
Can you please tell us the containername where we should add config file.

**Comment by loganhz** [comment]
Here is the docs for rancher cli https://rancher.com/docs/rancher/v2.x/en/cli/

If you want to use `kubectl`, please download it and config it. You can follow the k8s document https://kubernetes.io/docs/tasks/tools/install-kubectl/
