### ISSUE TITLE
Add "Clone" feature to role UI

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#14229]
It seems like a common use case for creating custom roles is to want to create one that is _very_ similar to one of our builtin roles, but with one less or one extra grant. The concrete example I have is wanting to create a Project Member or Project Owner role minus the "Create Namespace" grant.

We would make this much easier to accomplish if we had a "Clone" button that when clicked would open up the Add Role page prepopulated from the the role that you are cloning.

**Comment by cjellick** [comment]
Derived from https://forums.rancher.com/t/custom-roles-and-role-precedence/10909

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/2
Verified fixed
