### ISSUE TITLE
Inherited external roles note displayed properly in the UI

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#14228]
Loook at this screen shot for project-member:
This role inherits from the kubernetes role "edit". You can see in the inherit section that a row was created but the box is empty; the word "edit" is not displayed. This is probably because that role "edit" _does not_ have an entry in /v3/roletemplates. This is intentional as it is an "external" role managed by kubernetes, not rancher, but I think the UI probably isnt accounting for this scenario.

![project-member](https://user-images.githubusercontent.com/2473240/41927345-d55fefe2-7926-11e8-93b9-c53219cb05f0.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/20
Verified fixed.  Inherited role is now showing.
