### ISSUE TITLE
Changing Project to Stack for host scheduling

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1422]
By changing "project" to "stack", we'll need to update the scheduling label keys to use stack instead of project. 

`io.rancher.project.name` -> `io.rancher.stack.name`

`io.rancher.project_service.name` -> `io.rancher.stack_service.name`

${project_name} ->  ${stack_name}

**Comment by will-chan** [comment]
- Add support for old rules.

**Comment by sangeethah** [comment]
Tested with server version - V0.27.0-rc4

Containers that are part of service now have io.rancher.stack.name and io.rancher.stack_service.name label. Affinity rules to service names now reference  " io.rancher.stack_service.name". 

We have 1 issue - https://github.com/rancher/rancher/issues/1532 to track removing io.rancher.project.name and io.rancher.project_service.name.
Closing this issue.
