### ISSUE TITLE
Azure - UK West & UK South (Regions not showing on Rancher v2.0.2 - v2.0.4)

### ISSUE THREAD

**Issue by fbotha-stratuscloud** [rancher/rancher#14225]
**Rancher versions:**
rancher/rancher: v2.0.2 & v2.0.4
rancher/rancher-agent: v2.0.2 & v2.0.4

The below regions are not showing on the Rancher Deployment Dashboard for Azure.

Europe | UK West | Cardiff
Europe | UK South | London

https://azure.microsoft.com/en-us/global-infrastructure/locations/

**Comment by tfiduccia** [comment]
version 2.0 master 7/1 : Not finished 
Added to RKE but not to Azure Kubernetes Service.  We should change this so it's pulling from the same list?

**Comment by tfiduccia** [comment]
Version 2.0 master 7/1 - AKS is in separate issue. This is resolved for Azure RKE.
Verified fixed
