### ISSUE TITLE
EKS targeted availability zone does not currently have sufficient capacity to support the cluster

### ISSUE THREAD

**Issue by andrvin** [rancher/rancher#14224]
Rancher versions:
v2.0.3

Steps to Reproduce:
Create EKS cluster in us-east-1 Available Zone.

Results:
Rancher pending in provisioning state with the error "Error creating cluster: 400 {"clusterName":"c-z2h8f","validZones":["us-east-1a","us-east-1b","us-east-1d"],"message":"Cannot create cluster 'c-z2h8f' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d"}"

It seems that now us-east-1c Available Zone on AWS is not available to use in EKS cluster.
When I try to create EKS cluster manually I get an error:
"UnsupportedAvailabilityZoneException
Cannot create cluster 'production-test' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d"

Is there any workaround of this issue?

**Comment by superseb** [comment]
Not at the moment, making it more configurable and robust is covered in https://github.com/rancher/rancher/issues/13910
