### ISSUE TITLE
EKS Form Needs to Validate Min/Max ASG Size

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rancher#14238]
**Rancher versions:**
rancher/rancher:v2.0.4

**Steps to Reproduce:**

1. Add cluster
2. Select Amazon EKS
3. Enter Cluster Name, Access Key & Secret Key
4. Go to the next page
5. Enter 0 for Minimum & Maximum ASG Size (also tried 1 for min and 0 for max)
6. Create

**Results:**

Error parsing state: minimum nodes must be greater than 0

**Comment by massimo-cannavo** [comment]
![cool-form](https://user-images.githubusercontent.com/34786681/41941148-f619c090-794f-11e8-8e11-29407079141e.png)

**Comment by massimo-cannavo** [comment]
@n313893254 awesome thanks for the fix.

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/29

When trying to enter 0 for min/max size, the form will be automatically set to have sizes of "1". 

It is still possible to have a maximum size less than the minimum size. When this happens, the screen moves to the next page and gives an error, `Error parsing state: maximum nodes cannot be less than minimum nodes`. 

This validation should be handled at the node configuration screen, like the first validation.

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/2

The scenario with max asg size being greater than the min asg size is being validated correctly and the cluster is unable to create until corrected.

**Comment by massimo-cannavo** [comment]
I noticed that if you clear out the values and click create, the form does not validate. Can you also make it validate on click event handler? Just to make the validation more robust.

**Comment by bmdepesa** [comment]
I was able to reproduce this. 

If the min/max fields are empty instead of containing a value, there is no validation and the cluster fails to create.

**Comment by massimo-cannavo** [comment]
@bmdepesa thanks, I know it's not a high priority item but I just wanted to be a good samaritan.

**Comment by vincent99** [comment]
Validation happens on submit, not as you're typing.  It sounds like your problem now is that the fields aren't actually marked required, so empty is perfectly valid.

**Comment by massimo-cannavo** [comment]
@vincent99 Okay no problem, I will close the ticket for now. Thank you.
