### ISSUE TITLE
Editing Cluster from View in API results in JSON errors

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#14237]
**Rancher versions:**
rancher/rancher:v2.0.4

**Steps**
1. from Clusters page, click view in API
1. Edit in the API UI
1. Change a field like defaultPodSecurityPolicy
1. Click show request

**Results**
User is presented with with JSON validation errors caused by the *config types (azure) it seems as though those options are represented as strings and not null objects.

**Comment by loganhz** [comment]
duplicated with https://github.com/rancher/rancher/issues/13732
