### ISSUE TITLE
Deploy Prometheus Metrics Server Adapter to Support HPA in Cluster

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#14231]
Here is the [repo](https://github.com/kubernetes-incubator/custom-metrics-apiserver)  for Kubernetes custom metrics server. It is based on the metrics server and extension api-server. So it requires following changes if I want to support it in RKE:

- Enable API aggregation layer in RKE cluster, it requires to add related parameters to API server.
- Deploy the Prometheus metrics server adapter with those

As reference, GKE enable the API aggregation layer by default. With command `kubectl get -n kube-system configmap extension-apiserver-authentication `, you can see these configmap data has been set. It means that these authentication data can be used by extension api-server directly. Here is the document for [extension api-server](https://kubernetes.io/docs/tasks/access-kubernetes-api/setup-extension-api-server/).

For the Prometheus metrics server, here is the [repo](https://github.com/DirectXMan12/k8s-prometheus-adapter). It will fetch metrics from prometheus and push them to k8s metrics api as custom metrics. And then HPA controller(native k8s) could use those metrics as reference to scale workloads.

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/19084

**Comment by loganhz** [comment]
Blocked by https://github.com/rancher/rancher/issues/14231

**Comment by deniseschannon** [comment]
@aiyengar2 As part of monitoring v2, do we deploy this adapter?

**Comment by aiyengar2** [comment]
@deniseschannon yes, it’s packaged in
