### ISSUE TITLE
Authentication errors missing required field "code"

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#14235]
From the [rancher api spec](https://github.com/rancher/api-spec/blob/master/specification.md#errors), errors MUST contain type, status, and code, but auth failures (like if you supply a bad, missing, or expired token) look like:
```
{
  "type": "error",
  "status": "401",
  "message": "must authenticate"
}
```

**Comment by cjellick** [comment]
This breaks stuff in the python library we use for tests

**Comment by cbron** [comment]
We checked and this is still the case, though a fix would be ideal its not an active problem.
