### ISSUE TITLE
[network] Host [192.168.x.y] is not able to connect to the following ports: [192.168.x.y:2379]. Please check network policies and firewall rules

### ISSUE THREAD

**Issue by jdall** [rancher/rancher#14249]
Having destroyed a Rancher 2 test cluster and completely cleaned all the baremetal/vm in-house nodes, I'm seeing the following message when provisioning the first node as etcd and control:

[network] Host [192.168.x.y] is not able to connect to the following ports: [192.168.x.y:2379]. Please check network policies and firewall rules.

This error started appearing in Rancher v2.0.3 - prior to that version, I did not have that issue.

The cluster nodes are running RancherOS v1.4.0.

This issue makes it impossible for me to set up a new cluster, so if someone has a clue what is going on, I would highly appreciate some feedback.

Thanks

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
The logic didn't change, the error message did to make it more clear what's going on. Apparently host `192.168.x.y` can't contact itself on `192.168.x.y:2379` due to host firewall rules or something else occupying it.

As said before, the logic was always there, only the error text changed.

**Comment by jdall** [comment]
Thanks , @superseb.

Are you sure nothing has changed in the logic? Prior v2.0.3, the cluster nodes entered the running state, while now they stay in the registering state.

On the node, the following containers are running:
```
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
24beadc3d015        rancher/hyperkube:v1.10.3-rancher2   "/opt/rke/entrypoi..."   41 minutes ago      Up 49 seconds                           kube-apiserver
2d785b733e06        rancher/coreos-etcd:v3.1.12          "/usr/local/bin/et..."   41 minutes ago      Up 41 minutes                           etcd
0d98f491f22c        rancher/rancher-agent:v2.0.4         "run.sh -- share-r..."   43 minutes ago      Up 43 minutes                           share-mnt
aba8836c1be6        rancher/rancher-agent:v2.0.4         "run.sh --server h..."   43 minutes ago      Up 43 minutes                           sleepy_wright
```
but doing a "telnet localhost 2379" on the cluster node results in:
telnet: can't connect to remote host (127.0.0.1): Connection timed out
So it can't be a firewall issue. 
Somehow, something must be wrong with the etcd container.

After further checking, it appears that several certs are missing from the /etc/kubernetes/ssl folder, so maybe that's the issue?

As only the ranger-server version has changed (the nodes are the same and has been running ros v1.4.0 from the beginning), it is reasonable to think that something has in fact changed in how rancher 2 provisions cluster nodes.

**Comment by superseb** [comment]
Did you clean the hosts that you are trying to re-use? This can conflict with new installations.

Also, can you provide the logs from the `rancher/rancher` container as that will show the provisioning process and helps to reproduce.

**Comment by jdall** [comment]
Yes, I did a complete clean of the nodes, according to a forum posting I found (I changed it slightly because I found it didn't clean out everything):
```
docker rm -f $(docker ps -qa)
docker rmi $(docker images -a -q)
docker volume rm -f $(docker volume ls -q)
sudo -s
cleanupdirs="/var/lib/etcd /etc/kubernetes /etc/cni /opt/cni /var/lib/cni /var/run/calico"
for dir in $cleanupdirs; do
  echo "Removing $dir"
  rm -rf $dir
done
exit
```
Also, to rule out any conflicts with previous versions of Rancher, I re-provisioned the system running the rancher-server and installed v2.0.4 on it.

After creating a new cluster and adding one etcd / control node to it, the rancher/rancher container log (attached) shows several "remote error: tls: bad certificate" messages.

[rancher-server_docker-ce-17.log](https://github.com/rancher/rancher/files/2141137/rancher-server_docker-ce-17.log)

**Comment by superseb** [comment]
The `tls: bad certificate` are already in the logs, even without creating the cluster. Are you using one or two hosts? Seeing the errors even before cluster creation means that there is still something on that host, possibly processes that are not in a container (if `docker rm` succeeds at least)

**Comment by jdall** [comment]
I'm debugging this using only one cluster node. 

The node is running RancherOS v1.4.0. Below is a view of the processes running on it:
```
PID   USER     COMMAND
    1 root     system-dockerd --exec-root /var/run/system-docker --storage-driver overlay2 --log-opt max-file=2 --log-opt max-size=25m --group root --graph /var/lib/system-doc
    2 root     [kthreadd]
    4 root     [kworker/0:0H]
    6 root     [mm_percpu_wq]
    7 root     [ksoftirqd/0]
    8 root     [rcu_sched]
    9 root     [rcu_bh]
   10 root     [migration/0]
   11 root     [watchdog/0]
   12 root     [cpuhp/0]
   13 root     [kdevtmpfs]
   14 root     [netns]
   15 root     [khungtaskd]
   16 root     [oom_reaper]
   17 root     [writeback]
   18 root     [kcompactd0]
   19 root     [ksmd]
   20 root     [khugepaged]
   21 root     [crypto]
   22 root     [kintegrityd]
   23 root     [kblockd]
   24 root     [ata_sff]
   25 root     [md]
   26 root     [edac-poller]
   27 root     [devfreq_wq]
   28 root     [watchdogd]
   31 root     [kauditd]
   32 root     [kswapd0]
   33 root     [ecryptfs-kthrea]
   50 root     [kthrotld]
   51 root     [acpi_thermal_pm]
   52 root     [scsi_eh_0]
   53 root     [scsi_tmf_0]
   54 root     [scsi_eh_1]
   55 root     [scsi_tmf_1]
   56 root     [scsi_eh_2]
   57 root     [scsi_tmf_2]
   64 root     [ipv6_addrconf]
   77 root     [charger_manager]
   81 root     [kworker/0:1H]
   84 root     [jbd2/sda1-8]
   85 root     [ext4-rsv-conver]
  300 root     [udevd]
  302 root     [udevd]
  304 root     [udevd]
  305 root     [udevd]
  306 root     [udevd]
  307 root     [udevd]
  308 root     [udevd]
  310 root     [udevd]
  311 root     [udevd]
  312 root     [udevd]
  313 root     [udevd]
  368 root     [dhcpcd]
  386 root     [dhcpcd-run-hook]
  411 root     [dhcpcd-run-hook]
  426 root     [ros]
  434 root     system-docker-containerd -l unix:///var/run/system-docker/libcontainerd/system-docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/r
  694 root     system-docker-containerd-shim fc5e77d6046b3204432662b5e67e9e92c3ad378f3da82a0b9798b29fcbb74e21 /var/run/system-docker/libcontainerd/fc5e77d6046b3204432662b5e67e
  711 root     container-crontab
  715 root     system-docker-containerd-shim 33a681aca2df53818acc9f716754f66fc49b332f849a03308cf570afc98b1832 /var/run/system-docker/libcontainerd/33a681aca2df53818acc9f716754
  732 root     /usr/sbin/acpid -f
  777 root     [kworker/0:0]
  799 root     system-docker-containerd-shim bd77b5ff8c3ac8956b11965a6105b343e09c8fb2f99b67f0c7ccf6edcc4cb8f2 /var/run/system-docker/libcontainerd/bd77b5ff8c3ac8956b11965a6105
  815 root     udevd
  828 root     system-docker-containerd-shim 65f694596a29282f80f1a6dd6945c76101f2314e521946346ac5aa32b269e6a7 /var/run/system-docker/libcontainerd/65f694596a29282f80f1a6dd6945
  844 root     netconf
  882 root     system-docker-containerd-shim cd33757e517d486a65909b1dd6bbc7dbfcf11aee93ac9e29caeabbcdf710a020 /var/run/system-docker/libcontainerd/cd33757e517d486a65909b1dd6bb
  898 root     ntpd --nofork -g
  966 root     dhcpcd -MA4 -w --debug eth0
 1076 root     system-docker-containerd-shim 79ddf67306ffc86bbcafcbaa55ebdfbe003d523c8a857ba30102578ba8cbb9a1 /var/run/system-docker/libcontainerd/79ddf67306ffc86bbcafcbaa55eb
 1092 root     rsyslogd -n
 1110 root     system-docker-containerd-shim 3f4e52562c309f50a126e77240e2ce71a6d08d8ee73c2c1910c25e8ac4142519 /var/run/system-docker/libcontainerd/3f4e52562c309f50a126e77240e2
 1126 root     respawn -f /etc/respawn.conf
 1165 root     /usr/sbin/sshd -D
 1166 root     /sbin/agetty --noclear tty1 linux
 1168 root     /sbin/agetty --noclear tty2 linux
 1170 root     /sbin/agetty --noclear tty3 linux
 1172 root     /sbin/agetty --noclear tty4 linux
 1174 root     /sbin/agetty --noclear tty5 linux
 1176 root     /sbin/agetty --noclear tty6 linux
 1263 root     [iscsi_eh]
 1352 root     docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/9a0ce6a35f0e3bef7204dd638eecebfa1a30100283
 1367 root     kube-apiserver --secure-port=6443 --storage-backend=etcd3 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --kubelet-client-certificate=/etc/kubernetes/ssl/kube
 1731 root     [kworker/u2:2]
 1732 root     [kworker/u2:3]
 1850 root     sleep 2
 1851 rancher  ps
 2942 root     sshd: rancher [priv]
 2944 rancher  sshd: rancher@pts/0
 2945 rancher  -bash
13679 root     [kworker/u2:0]
28036 root     system-docker-containerd-shim d84d12b46781ab1051196a0eec8687c7b065ce6b2f2a3bcaf2ee83a629ad223b /var/run/system-docker/libcontainerd/d84d12b46781ab1051196a0eec86
28052 root     system-docker-runc exec -- 3f4e52562c309f50a126e77240e2ce71a6d08d8ee73c2c1910c25e8ac4142519 env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bi
28084 root     dockerd --log-opt max-file=2 --log-opt max-size=25m --group docker --host unix:///var/run/docker.sock
28105 root     docker-containerd --config /var/run/docker/containerd/containerd.toml
28275 root     [kworker/u2:1]
28289 root     docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/72e0cdd2add49e6d38f23b73d23c86cdeff7d6106c
28304 root     agent
28351 root     docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/b650dd83bda5923b891e0449fec066e2c50f623599
28366 root     {share-root.sh} /bin/bash /usr/bin/share-root.sh /opt/rke/var/lib/kubelet /var/lib/rancher
29548 root     docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/9246dd7d6e14e2e270d2c4ca96660b000a7b605d80
29563 root     /usr/local/bin/etcd --peer-client-cert-auth --client-cert-auth --initial-advertise-peer-urls=https://192.168.1.170:2380 --peer-trusted-ca-file=/etc/kubernetes/s
30704 root     [kworker/0:1]
```
I'm still a noob in using RancherOS, so I can't tell whether there is something unusual about that list. Maybe you or someone else can tell if there is something out of the ordinary?

The only thing that I have touched, is changing the hostname, enabling of the iscsi service, and switching the docker engine version to the newest one supported by Rancher 2.

**Comment by superseb** [comment]
- Clean the host
- Reboot the host
- Check processes (shouldn't be any other than system)
- Check containers (shouldn't be any)
- Check `rancher/rancher` log so it doesn't log any `tls: bad certificate`
- Create custom cluster
- Add node using `docker run`

If it doesn't work, post `rancher/rancher` logging from start to end.

**Comment by jdall** [comment]
Instead of cleaning the host, I decided to reinstall RancherOS on it - that solved the issue. Then, comparing the state of the freshly installed node with one that I cleaned and rebooted, I found that some more folders needed to be removed. 

After also removing /opt/rke it appears to be working - /opt/rke holds the certs, so that explains the bad-cert issue.

I found that if not rebooting before removing the folders, some were not removed due to device or resource busy, so the steps should be:
- Clean docker on the host
- Reboot the host
- Clean folders on the host

I've attached my two scripts for cleaning the hosts.

I don't recall seeing it mentioned in the Rancher docs that a node should be clean before including it in the cluster - maybe this quite important information could be included.

[rancher_clean-dirs.sh](https://github.com/rancher/rancher/files/2144217/rancher_clean-dirs.sh.txt)
[rancher_clean-docker.sh](https://github.com/rancher/rancher/files/2144218/rancher_clean-docker.sh.txt)

Thanks for all your help, @superseb

**Comment by MPRian** [comment]
> Also, can you provide the logs from the `rancher/rancher` container as that will show the provisioning process and helps to reproduce.

How to get logs from the `rancher/rancher` ? Im facing same problem. Thank you

**Comment by ravikanth1980** [comment]
> * `rancher/rancher` log



> The `tls: bad certificate` are already in the logs, even without creating the cluster. Are you using one or two hosts? Seeing the errors even before cluster creation means that there is still something on that host, possibly processes that are not in a container (if `docker rm` succeeds at least)

I am facing following issue :FATA[0054] [[network] Host [18.207.150.236] is not able to connect to the following ports: [107.20.28.5:2379, 107.20.28.5:2380, 18.207.150.236:2380, 18.207.150.236:2379]. Please check network policies and firewall rules]
root@rke-server:/usr/local/bin#

**Comment by k0m0r3by** [comment]
I have this issue in my rancher 2.5.9
"This cluster is currently Updating.
[[network] Host [10.81.75.222] is not able to connect to the following ports: [10.81.75.221:2379, 10.81.75.221:2380]. Please check network policies and firewall rules]"
 my firewall is disable, i have 6 worker nodes and 1 etcd/control plane, i need 2 more etcd/controlplane 
but i can't add

**Comment by neil-re** [comment]
Same issue here, even after cleanup

**Comment by EtachGu** [comment]
> I get the same issue, "localhost:2379]. Please check network policies and firewall rules]"

I changed  “localhost” to host IP ”192.168.x.x",  the problem was solved.

**Comment by blackwood821** [comment]
I'm running into this as well. I see the following in the `rancher/rancher` log:

```
2022/11/17 21:40:53 [ERROR] error syncing 'c-jpmvb': handler cluster-provisioner-controller: [[network] Host [10.10.50.53] is not able to connect to the following ports: [10.10.50.44:2379]. Please check network policies and firewall rules], requeuing
```

On the `etcd` node I see the following in the `rancher/rancher-agent` log:

```
time="2022-11-17T21:43:37Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
```

```
root@etcd-1:~# docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                                    NAMES
fc1271911505   rancher/rke-tools:v0.1.80      "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes   80/tcp, 0.0.0.0:2379->1337/tcp, 0.0.0.0:2380->1337/tcp   rke-etcd-port-listener
769cab67921d   rancher/rancher-agent:v2.6.3   "run.sh --server htt…"   6 minutes ago   Up 6 minutes                                                            dreamy_tharp
```

```
root@etcd-1:~# docker ps -a
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS                     PORTS                                                    NAMES
fc1271911505   rancher/rke-tools:v0.1.80      "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes               80/tcp, 0.0.0.0:2379->1337/tcp, 0.0.0.0:2380->1337/tcp   rke-etcd-port-listener
7ebbf672af59   rancher/rke-tools:v0.1.80      "/docker-entrypoint.…"   6 minutes ago   Exited (0) 5 minutes ago                                                            cluster-state-deployer
769cab67921d   rancher/rancher-agent:v2.6.3   "run.sh --server htt…"   6 minutes ago   Up 6 minutes                                                                        dreamy_tharp```

I understand that the control plane can't reach `etcd` since there is no `etcd` container running on the `etcd` node but I don't know why the `etcd` container never gets created.

The control plane node can ping the `etcd` node.

Any help is much appreciated.

**Comment by blackwood821** [comment]
Turns out when this worked a few months ago when I created a cluster it's because at the time https://releases.rancher.com/install-docker/20.10.sh installed Docker version `20.10.12` but now it's been updated to install version `20.10.17` and for some reason for `20.10.17` I have to add the `iptables` engine option to the node template and set it to `false` and then I don't get the error.

**Comment by 0478yhl** [comment]
> Yes, I did a complete clean of the nodes, according to a forum posting I found (I changed it slightly because I found it didn't clean out everything):
> 
> ```
> docker rm -f $(docker ps -qa)
> docker rmi $(docker images -a -q)
> docker volume rm -f $(docker volume ls -q)
> sudo -s
> cleanupdirs="/var/lib/etcd /etc/kubernetes /etc/cni /opt/cni /var/lib/cni /var/run/calico"
> for dir in $cleanupdirs; do
>   echo "Removing $dir"
>   rm -rf $dir
> done
> exit
> ```
> 
> Also, to rule out any conflicts with previous versions of Rancher, I re-provisioned the system running the rancher-server and installed v2.0.4 on it.
> 
> After creating a new cluster and adding one etcd / control node to it, the rancher/rancher container log (attached) shows several "remote error: tls: bad certificate" messages.
> 
> [rancher-server_docker-ce-17.log](https://github.com/rancher/rancher/files/2141137/rancher-server_docker-ce-17.log)

**Comment by 0478yhl** [comment]
Believe me, restart the linux server and do it again with the shutdown port detection parameter.
