### ISSUE TITLE
Rancher LB in infrastructure stack cant target other services in the infrastructure stack space

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#14242]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.14

**Steps to Reproduce:**
1. create a infrastructure stack with services
2. add a load balancer, try to select a target that exists in the infrastructure stack space

**Results:**
only services that exist in the user stacks are present. Looks like the UI filters out infra services.

**Comment by deniseschannon** [comment]
@loganhz do we purposely prevent this?

**Comment by loganhz** [comment]
@deniseschannon yes

https://github.com/rancher/ui/blob/1.6-dev/app/services/all-services.js#L10

I can remove it if you want.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
