### ISSUE TITLE
Can not pull from own local registry

### ISSUE THREAD

**Issue by o0zonko0o** [rancher/rancher#14248]
rancher 2.0
rancher/rancher
rancher/rancher-agent

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 

Docker version: 1.13.1

Operating system and kernel: 3.10.0-862.3.2.el7.x86_64

Type/provider of hosts: Bare-metal

Setup details: multi node rancher

Environment Template: Kubernetes

Steps to Reproduce:
setup a bare-metal rancher 2.0 cluster
setup a docker registry v2 with ssl and basic auth on an external host of the cluster (registry is a not a part of the cluster)
push a test image to you registry
create a deployement with you test image

Results:
error pull back image

docker logs registry:
time="2018-06-27T09:29:52Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential" go.version=go1.7.6 http.request.host="10.66.222.65:5000" http.request.id=fa302eb9-d56b-44ca-bdeb-56e23c858eeb http.request.method=GET http.request.remoteaddr="10.66.222.31:47468" http.request.uri="/v2/" http.request.useragent="docker/1.13.1 go/go1.9.4 kernel/3.10.0-862.3.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=89b612ab-4836-4bb4-8877-74fb59089ec9 version=v2.6.2
10.66.222.31 - - [27/Jun/2018:09:29:52 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.13.1 go/go1.9.4 kernel/3.10.0-862.3.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
2018/06/27 09:29:52 http: TLS handshake error from 10.66.222.31:47470: tls: first record does not look like a TLS handshake
10.66.222.31 - - [27/Jun/2018:09:29:52 +0000] "GET /v1/_ping HTTP/1.1" 404 19 "" "docker/1.13.1 go/go1.9.4 kernel/3.10.0-862.3.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
10.66.222.31 - - [27/Jun/2018:09:29:52 +0000] "GET /v1/repositories/mng/images HTTP/1.1" 404 19 "" "docker/1.13.1 go/go1.9.4 kernel/3.10.0-862.3.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"

deployement:
![image](https://user-images.githubusercontent.com/11685382/41966530-a41348a6-79ff-11e8-90a8-74f6550ac5c2.png)

registry:
![image](https://user-images.githubusercontent.com/11685382/42019301-1bf7f140-7ab5-11e8-91ac-8932f6a3bd2f.png)

**Comment by longwuyuan** [comment]
i did not even know that  docker client honored that type of registry name

**Comment by longwuyuan** [comment]
You can change rancher default registry

**Comment by o0zonko0o** [comment]
the default rancher registry can't use basic auth

**Comment by kc004** [comment]
@o0zonko0o Hi did you create a secret file for pulling an image? 
You can create secret using this command. 

`kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>`

**Comment by o0zonko0o** [comment]
no i didn't. how to use it ?

**Comment by kc004** [comment]
I did it using Kubernetes CLI. Actually, i don't know how it can set up using Rancher UI.

**Comment by o0zonko0o** [comment]
![image](https://user-images.githubusercontent.com/11685382/42035454-3fcff648-7ae3-11e8-97c2-30f860a57538.png)

its a dockercfg instead of dockerconfigjson

does it can be the cause of my error "invalid authorization credential"?

**Comment by o0zonko0o** [comment]
It finally work by "magic".

I have follow the advice of someone who tell me to add the crédencial then delete my cluster and create new one add again crédencial.

if you are in my case carefull to corp proxy. if you can't manage your proxy you will need to tell docker to use the proxy for rancher and all rancher node but you will need to remove proxy information and restart docker on each node to join your private local registry.
