### ISSUE TITLE
Helm/stable catalog experience

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#14241]
Today turning on helm/stable catalog(or incubator) is a bad user experience. It takes 10-15 minutes to load all the template and create them in database. To improve this, we add:

1. Create them one by one. User don't have to wait for all the templates.
2. Add a status to show the progress when pull charts.

**Comment by guangbochen** [comment]
verified on master 06/30 using custom and incubator catalog repository, close it.
