### ISSUE TITLE
Scheduler does not restart after ping timeout

### ISSUE THREAD

**Issue by mithrandi** [rancher/rancher#14246]
Every now and then, the Scheduler service in our Rancher environment exits with:

```
26/06/2018 09:19:18time="2018-06-26T07:19:18Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2018-06-26 07:19:03.733296969 +0000 UTC. Closing connection."
26/06/2018 09:19:18time="2018-06-26T07:19:18Z" level=error msg="Exiting scheduler with error: <nil>"
```

I suspect this is due to the Rancher server responding too slowly.

However, the real problem is that the scheduler does not restart after this, until someone manually clicks the "start" button on the container. This causes any other services with scheduling rules (published ports etc.) to fail to start in the meantime, of course. As far as I can tell, the container is set to auto-restart, so I don't really understand why this is happening or how to debug further.

**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 0.2.3
network-services: 0.2.9
scheduler: 0.8.3-1
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:28 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:22 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```
Containers: 67
 Running: 52
 Paused: 0
 Stopped: 15
Images: 630
Server Version: 17.06.2-ce
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.4GiB
Name: scarlet
ID: KXMQ:YZ4F:RBKR:HQGF:QICW:6KWJ:NTFT:5PWX:D5IH:6P7D:E3PU:D2XP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
4.9.0-6-amd64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Comment by eici** [comment]
Same Issue with us:
```
time="2018-06-29T16:12:37Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2018-06-29 16:12:22.966261201 +0000 UTC. Closing connection." 
time="2018-06-29T16:12:37Z" level=error msg="Exiting scheduler with error: <nil>"
```

After that the Scheduler completely lost it:
`time="2018-07-02T14:49:13Z" level=warning msg="Error in sending external host event. err: Post http://192.168.1.50:8080/v2-beta/externalhostevents: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"`

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
