### ISSUE TITLE
Update all default alerts recipients (N/A) with the newly created notifier

### ISSUE THREAD

**Issue by percenuage** [rancher/rancher#14250]
### Current behavior
When you add a notifier like _slack_, all default (predefined) alerts recipients are `N/A` (on clusters and projects views).

![alert](https://user-images.githubusercontent.com/6691104/41967136-36de7de4-7a01-11e8-8eaf-5dafbd4f6e97.PNG)

![alert-2](https://user-images.githubusercontent.com/6691104/41967899-10d85064-7a03-11e8-82e9-f229ae90b2e6.png)

### Desired behavior

When you add a notifier like _slack_, all default (predefined) alerts recipients should be defined according to the newly created notifier (on clusters and projects views).

![notifier](https://user-images.githubusercontent.com/6691104/41967872-fe0b69ee-7a02-11e8-865e-5c4ed2671b61.PNG)

![alert-after](https://user-images.githubusercontent.com/6691104/41967530-1aa0170e-7a02-11e8-84da-5c21deed1ae6.PNG)

![alert-after](https://user-images.githubusercontent.com/6691104/41967894-0cf5082a-7a03-11e8-81ab-6e500a00e438.PNG)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by deniseschannon** [comment]
@percenuage I think with the introduction of alert groups, this might be solved for you in v2.2.

Let me know if i'm mistaken.
