### ISSUE TITLE
iscsi persistent volume requires secret even when no auth is selected

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#14255]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.4

**Steps to Reproduce:**

- create a persistent volume of type iSCSI Target
- fill in required fields
  - IQN is a required field but not indicated as such
- fill in IQN and target portal
- leave chap discovery and auth set to No
- save

**Results:**
`spec.iscsi.secretRef.name: Required value`

**Comment by loganhz** [comment]
Can you try to use kubectl, please? It's a k8s limitation. User has to config it.

`spec.volumes[0].iscsi.secretRef: Required value`
