### ISSUE TITLE
[cli] local helm chart install fails

### ISSUE THREAD

**Issue by lopf** [rancher/rancher#14251]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.4
rancher/cli: 2.0.3-rc1

**Infrastructure Stack versions:**
kubernetes: 1.10

**Operating system and kernel: Rancher CLI on macOS**

**Setup details: single node**

**Environment Template: Kubernetes CDK**

**Steps to Reproduce:**

Create a project and be owner of it. Login through rancher via cli and select the project.

`git clone https://github.com/kubernetes/charts.git`
`./rancher-v2.0.3-rc1/rancher app install charts/incubator/kafka kafkatest`

The choice of the kafka chart was inspired by #13518

**Results:**
A namespace and rolebindings are generated, rancher logs:
`2018/06/27 11:03:19 [INFO] Creating roleBinding User user-xx57p Role project-owner
2018/06/27 11:03:19 [INFO] Creating roleBinding User user-xx57p Role admin
2018/06/27 11:03:19 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-tzbc9 to namespace=kafka-6yn3n
2018/06/27 11:03:20 [ERROR] Unknown error: templateversions.management.cattle.io "--" not found`

Rancher CLI client log:
`FATA[0002] Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=templateversions.management.cattle.io "--" not found] from [https://rancher.fqdn.com/v3/projects/c-89gxk:p-tzbc9/app]`

**Comment by StrongMonkey** [comment]
@lopf thanks for reporting, it is a regression bug and we will a quick fix.

**Comment by adingilloRancher** [comment]
Master 6/28/18 Installed local chart.

Error message was not seen during install
