### ISSUE TITLE
FreeIPA - User login id does not always appear next to user name when adding to authorization access list

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14257]
**Rancher versions:**
rancher/rancher:master 6/26

**Steps to Reproduce:**
Enable authentication through FreeIPA
Change site access mode to restricted or only authorized users
Add users to access list

**Results:**
Some users will not have the login id next to their names in the list. 

After first noticing, I saw a few users who did not have the id. After refreshing, only one user correctly had the id next to their name.

<img width="1520" alt="screen shot 2018-06-26 at 1 52 11 pm" src="https://user-images.githubusercontent.com/21316915/41986837-39b9927a-79ec-11e8-92d1-a81653f63c87.png">
<img width="1455" alt="screen shot 2018-06-26 at 2 00 34 pm" src="https://user-images.githubusercontent.com/21316915/41986838-39ccd092-79ec-11e8-97dd-e33c7dbb0c54.png">

**Comment by westlywright** [comment]
see https://github.com/rancher/rancher/issues/14245#issuecomment-400870648

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/2

I was not able to reproduce the incorrect behavior. Login ids are displaying correctly next to the user name.
