### ISSUE TITLE
Add cluster option to open Node Port range in AWS

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#14259]
When I deploy a cluster using AWS EC2 cloud provider, the default security group rules don't open the node port range. We need to add an option when creating the cluster to allow/disallow this range to be added to the security group.

**Comment by deniseschannon** [comment]
This was already changed in 2.0.3.

**Comment by deniseschannon** [comment]
One caveat: If you have an existing `rancher-nodes` security group, it won't change it.
