### ISSUE TITLE
liveliness check "start checking after" cannot be changed

### ISSUE THREAD

**Issue by dcardamo** [rancher/rancher#14252]
**Rancher versions:**
rancher/server or rancher/rancher:  2.0.4
rancher/agent or rancher/rancher-agent:  2.0.4

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 115
 Running: 86
 Paused: 0
 Stopped: 29
Images: 18
Server Version: 17.03.2-ce
Storage Driver: zfs
 Zpool: bpool
 Zpool Health: ONLINE
 Parent Dataset: bpool/docker
 Space Used By Parent: 1971122400
 Space Available: 104323904705280
 Parent Quota: no
 Compression: lz4
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-128-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 377.8 GiB
Name: titan
ID: QWKU:GTNJ:GDXZ:KHLW:J2ON:FJU5:ZTRN:ZHMR:UXSP:U7EP:ZIOT:ROHZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 jupiter:6000
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ uname -r
4.4.0-128-generic
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes

**Steps to Reproduce:**
1.  Go to a pod that is running and have a liveliness check defined.   Mine is:
  - Command:  /bin/false
  - start checking after:  700 seconds
2.  While the pod is running, change the "start checking after" field to a different number like 1000
3.  Click "Upgrade"
4.  Edit the pod again and look at the liveliness check.  It will be the same as before.

The way I work around this is to remove the liveliness check, upgrade, then edit and put it back in the way I want it changed.

**Comment by loganhz** [comment]
I guess only newly created pods after you upgrade the workload will have the new  `start checking after` value.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
