### ISSUE TITLE
Cluster has kube-dns very sloow after rancher update do 2.0.3

### ISSUE THREAD

**Issue by Itiho** [rancher/rancher#14261]
**Rancher versions:**
 rancher/rancher: 2.0.3

kubectl exec busybox-756576c555-vhmvc time nslookup kube-dns.kube-system.svc.cluster.local
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local
Name:      kube-dns.kube-system.svc.cluster.local
Address 1: 10.43.0.10
real    0m 40.03s
user    0m 0.00s
sys     0m 0.00s

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
