### ISSUE TITLE
UI Suggestion: default "Cloud Provider" to AWS when creating an AWS EC2 cluster

### ISSUE THREAD

**Issue by gregbacchus** [rancher/rancher#14268]
**Rancher versions:**
rancher/rancher: 2.0.2

When creating some new clusters, I have forgotten to open the "Cluster Options" and select "Cloud Provider: AWS". This prompted me to think that making this the default option may be easier for forgetful people such as myself.

**Comment by superseb** [comment]
We can't assume people that are using EC2 nodes want to use the k8s cloud provider. K8s cloud provider is needed when you want to automatically use cloud resources when creating k8s resources (LB/storage for instance) and require specific requirements (https://rancher.com/docs/rancher/v2.x/en/concepts/clusters/cloud-providers/#amazon) which will only break the cluster if people are unaware.

Let me know if you don't agree or if I'm missing the use case.
