### ISSUE TITLE
Add London region to Rackspace

### ISSUE THREAD

**Issue by rydn** [rancher/rancher#1426]
I cant see London(LON) as one of the available options when trying to create a new host using Rackspace.

**Comment by deniseschannon** [comment]
@wlan0 Can you confirm that this is just a UI change?

**Comment by vincent99** [comment]
It is

**Comment by tfiduccia** [comment]
v0.27.0-rc1 (ui latest - 0.32.0)
Verified fixed

@rydn - fix will be in the next build v0.27.0-rc2
