### ISSUE TITLE
Cannot scale statefulset from Rancher UI

### ISSUE THREAD

**Issue by andymelichar** [rancher/rancher#14279]
**Rancher versions:**
rancher/rancher:v2.04

**Docker version: (`docker version`,`docker info` preferred)**
17.3.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Kernel Version 4.4.0-127-generic
Operating System Ubuntu 16.04.4 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DigitalOcean

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 node cluster, built on DO from rancher UI
Longhorn 0.1.0 installed via Catalog

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. `kubectl create -f https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/tutorials/stateful-application/web.yaml`
2. Statefulset application is created and replicated across 2 pods
3. From Rancher UI, go to the web app and click "+" next to scale in an attempt to scale up to 3 pods, receive error "Error updating scale
Validation failed in API: StatefulSet.apps "web" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden."
![try-to-scale](https://user-images.githubusercontent.com/357100/42037477-7eb821fa-7ab6-11e8-9faf-82ca97bdc477.PNG)
4. Scale the app via kubectl
![scale-cmd-line](https://user-images.githubusercontent.com/357100/42037527-9b497562-7ab6-11e8-8cf9-d0c5a411c9ee.PNG)
5. Pods provision and UI is updated correctly to reflect the newly scaled app
![scaled-in-ui](https://user-images.githubusercontent.com/357100/42037549-ab6d083c-7ab6-11e8-90a1-d811146b79ab.PNG)

**Results:**
Unable to scale from UI if using a statefulset, must scale from cmdline
Additionally, the scale number is not adjusted after the API error. With 2 active pods, when you click "+" the scale number is set to 3, but then the API error is received and the scaling does not happen. The current scale count stays at 3 until you refresh the page.

**Comment by loganhz** [comment]
Thanks for your report!
Close in favor of https://github.com/rancher/rancher/issues/15519
