### ISSUE TITLE
Memory leak of rancher-agent and rancher-nfs

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#14276]
**Rancher versions:**
- rancher/server:v1.6.17
- rancher/agent:v1.2.10

**Infrastructure Stack versions:**
- healthcheck:v0.3.6
- network-services:v0.7.20
- scheduler:v0.8.3
- storage-nfs:v0.9.1

**Docker version: (`docker version`,`docker info` preferred)**
- 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
- ubuntu 16.04.4 (kernel: 4.4.0-87-generic)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
- Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- HA rancher,  external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
- Cattle

**Steps to Reproduce:**

Test 1：
1. Check the memory usage of the agent container on this host, using 20M memory；
2. Create an stack and run 10 services, run one container per service. 
3. Configure the wrong health check port for the service，make the service keep rebuilding(This is our expected result);
4. After a few hours, check the memory usage of the agent container and the memory usage does not exceed 80M；

Test 2：
1. Based on test 1, create a second stack, run 10 services, 1 container per service, and configure the rancher-nfs volume for the service;
2. Configure the wrong health check port for the service，make the service keep rebuilding(This is our expected result);
3. After a few hours, check the memory usage of the agent container, memory usage increased from 80M to 350M；

**Results:**

The host only runs 50 containers, run the `netstat -apn` command to check the number of connections: 

<img width="610" alt="image" src="https://user-images.githubusercontent.com/20707603/42024628-39f6d91e-7af5-11e8-80c2-6cad5ac7f944.png">

Attachments are collected by `netstat -apn`
[netstat.dump.zip](https://github.com/rancher/rancher/files/2144523/netstat.dump.zip)

**Comment by cjellick** [comment]
while testing this, can you try some failure scenarios where you delete the rancher socket file, try to do some volume related stuff, and then recreate it?
I dont even know exactly what scenarios to try, but the fix is going to keep a connection open and around for the life of the rancher agent, so I want to make sure we dont get into a scenario where we are in a perpetual error state because the connection has "gone bad." @StrongMonkey please assist in coming up with scenarios to test this

**Comment by soumyalj** [comment]
Reproduced the issue with rancher v1.6.18. 
1. create a second stack, run 10 services, 1 container per service, and configure the rancher-nfs volume for the service;
2. Configure the wrong health check port for the service，make the service keep rebuilding(This is our expected result);

After a few hours, check the memory usage of the agent container, memory usage increased from 37M to 380M as shown below

![screen shot 2018-07-13 at 11 52 40 am](https://user-images.githubusercontent.com/18536626/42708864-60d6f786-8693-11e8-9275-0b50e5291040.png)

 Tested with v1.6.19-rc6 with the same steps. The memory usage of the agent container did not increase rapidly as in the other case. It was around 47MB
<img width="1183" alt="1619rc5 agent memory monitor" src="https://user-images.githubusercontent.com/18536626/42709075-14cb486e-8694-11e8-8686-b8040162692d.png">
