### ISSUE TITLE
Updating workload with clusterIP port doesn't set clusterIP on the service

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#14271]
Steps to reproduce:

1) Create a workload with no ports assigned. By default, Rancher would create a headless cluster ip service with service.name=workload.name and ClusterIP=None
2) Update workload with cluster ip port. Service should get converted to regular, non-headless service, where clusterIP != None.

Bug: clusterIP remains None

**Comment by sangeethah** [comment]
Tested with latest build from master

1. Create a workload with no ports assigned. By default, Rancher would create a headless cluster ip service with service.name=workload.name and ClusterIP=None
2. Update workload with cluster ip port. Service now has a clusterIp set as expected.
