### ISSUE TITLE
network-policy-manager ignores ports configuration

### ISSUE THREAD

**Issue by jacoelho** [rancher/rancher#14277]
**Rancher versions:**
rancher/agent:v1.2.9
rancher/network-policy-manager:v0.2.4

**Infrastructure Stack versions:**
rancher/healthcheck:v0.3.3
rancher/net:v0.13.7
rancher/scheduler:v0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
Client:
Version: 1.10.3
API version: 1.22
Go version: go1.5.3
Git commit: 20f81dd
Built: Thu Mar 10 21:49:11 2016
OS/Arch: linux/amd64

Server:
Version: 17.06.2-ce
API version: 1.30
Go version: go1.8.3
Git commit: cec0b72
Built: Tue Sep 5 19:59:19 2017
OS/Arch: linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.9.78-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

Set default policy to deny:
```
"defaultPolicyAction": "deny",
```

Set network policies:
```
"policy": [

    {
        "type": "networkPolicyRule",
        "action": "allow",
        "from": {
            "type": "networkPolicyRuleMember",
            "selector": "com.rancher.service=app"
        },
        "ports": [
            "6380"
        ],
        "to": {
            "type": "networkPolicyRuleMember",
            "selector": "com.rancher.service=db"
        }
    }
]
```

**Results:**

network-policy-manager running in debug mode:
```
28/06/2018 11:03:30time="2018-06-28T10:03:30Z" level=debug msg="Policy: []metadata.NetworkPolicyRule{metadata.NetworkPolicyRule{From:(*metadata.NetworkPolicyRuleMember)(0xc42028d480), 
To:(*metadata.NetworkPolicyRuleMember)(0xc42028d490), Ports:[]string{\"6380\"}, Within:\"\", Between:(*metadata.NetworkPolicyRuleBetween)(nil), Action:\"allow\"}}"
28/06/2018 11:03:30time="2018-06-28T10:03:30Z" level=debug msg="validating rule: (*policy.NetworkPolicyRule)(0xc42034c320){NetworkPolicyRule:
(metadata.NetworkPolicyRule){From:(*metadata.NetworkPolicyRuleMember)(0xc42028d480){Selector:(string)com.rancher.service=app} To:(*metadata.NetworkPolicyRuleMember)(
    0xc42028d490){Selector:(string)com.rancher.service=db} Ports:([]string)[6380] Within:(string) Between:(*metadata.NetworkPolicyRuleBetween)<nil> Action:(string)allow}}"
```

iptables rules are created:

```
Chain CATTLE_NETWORK_POLICY (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere             match-set RNCH-S-3308273598065079164 src
RETURN     all  --  anywhere             anywhere             match-set RNCH-S-9363986724208910864 src
RETURN     all  --  anywhere             anywhere             match-set RNCH-S-17252670097841251797 src
RETURN     all  --  anywhere             anywhere             match-set RNCH-S-2845480634040578369 src
RETURN     all  --  anywhere             anywhere             match-set RNCH-S-13647065898704439585 src
RETURN     all  --  anywhere             anywhere             match-set RNCH-S-15242666270991449833 src
DROP       all  --  anywhere             anywhere             match-set RNCH-U-10594850245288165044 dst
```

However ipset type:
```
# ipset -L|grep Type
Type: hash:net
Type: hash:ip
Type: hash:ip
Type: hash:ip
Type: hash:ip
Type: hash:ip
Type: hash:ip
Type: hash:ip
```

Connections between hosts `app` and `db` port `6380` are not possible.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
