### ISSUE TITLE
"User Member Attribute" stay empty after configuring AD auth provider

### ISSUE THREAD

**Issue by bigbrozer** [rancher/rancher#14275]
Hi,

After configuring AD auth provider, the field "User Member Attribute" stay empty even if I set it to `memberOf` (which should be the value to find user groups is part of, I guess...).

![2018-06-28 10_58_16-clipboard](https://user-images.githubusercontent.com/218972/42024439-7e79dba0-7ac2-11e8-849c-317a7122de0f.jpg)

When adding users / groups to the members of clusters / projects / global sections, I'm not able to see my groups by clicking on the "down arrow" right to the search field. I can add users / groups anyway but during login, it seems Rancher is not able to authenticate users without adding them explicitly (groups are ignored)...

![2018-06-28 11_02_06-clipboard](https://user-images.githubusercontent.com/218972/42024588-de754bca-7ac2-11e8-9f68-f62bbb6ee452.jpg)

Thanks.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`` `admin`|
|Route|`global-admin.security.authentication.activedirectory`|

**Comment by aemneina** [comment]
Did you try to use that groups dropdown as the local admin, or an active directory user? If you didnt try logging out, then logging in with AD user, can you confirm if that works for you?

**Comment by bigbrozer** [comment]
I have tested using an AD user. Also tested with a colleague (because my AD account is "linked" to the local "admin" account after AD auth provider configuration), but he experienced the same issue... Groups are ignored and he is not able to list his groups.

Let me know if I can provide debug logs (and how to enable it). I had a look to the "cattle-system" pods (I'm using HA installation) but see nothing relevant... I can see `activedirectory_user` and `activedirectory_group` for RoleBindings being created when assigned to cluster members (for example).

**Comment by bigbrozer** [comment]
I have investigated a bit more and found a possible root cause for the issue. I had set the field **Default Login Domain** when configuring the AD auth provider. I have removed the value and then used the form `DOMAIN\username` to logon in Rancher.

Now, I'm able to see my groups and users that log in have now proper permissions.

**Comment by loganhz** [comment]
Thanks for the report

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
