### ISSUE TITLE
Give the admin user that is turning on an auth provider the option to either associate to current user or create a new user

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#14273]
See https://github.com/rancher/rancher/issues/13684

Here's the most relevant excerpt that captures this feature:

The Rancher user who is signed in was already an admin (because they can write auth config). The external auth account they used to test the config (Github or AD principal ID) is then associated with their current Rancher user (which is often the "Default Admin", but not necessarily). In accordance with the law of conservation of users, no new users are created or destroyed during access control configuration in <= 2.0.2.

We discussed a future release having an option presented to the user for whether to:

Add the principal of the tested external account to the current Rancher User, or
Create a new Rancher user with admin rolebinding for the tested external account principal (and then switch to it, I guess?)
I still think the former is what most people would want and should do, but the option at least makes it more clear what is happening and then you can have a choice. The latter is going to have new and exciting edge cases to handle (e.g. what if there's already a Rancher user using that principal ID?)

**Comment by sboulkour** [comment]
In the mean time, is there a way to detach my personal extern principal from default admin account ??

**Comment by vincent99** [comment]
View the user in api and edit the principal issue array.

**Comment by sboulkour** [comment]
Woohoo ! Thanks @vincent99, I fixed it with your tip :)
