### ISSUE TITLE
Rancher 2 Orphaned Cluster

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#14289]
Hello, we have an orphaned cluster in rancher which the nodes have actually been rebuilt with a new name, etc. Is there a way to force delete a cluster without it waiting for a connection else I think the only way to delete it will be manually from the etcd side and was hoping for some guidance. Thanks!

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
