### ISSUE TITLE
FreeIpa - Logging in with a user in 1000 groups makes login slow

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14287]
**Rancher versions:**
rancher/rancher:master 6/28

**Steps to Reproduce:**
Enable FreeIpa authentication in Rancher server
Create a user in FreeIpa who is in 1000 groups
Log out
Log in with the user who is in 1000 groups

**Results:**
Login takes 2.5 minutes to complete

<img width="1304" alt="screen shot 2018-06-28 at 11 21 41 am" src="https://user-images.githubusercontent.com/21316915/42054167-84c463f8-7ac8-11e8-9ed2-32536da05f3a.png">

**Comment by deniseschannon** [comment]
Available in v2.0.5-rc2

**Comment by bmdepesa** [comment]
rancher/rancher:v2.0.5-rc2

Login is much faster w/ a user in 1000 groups. Went from 2.5m to ~15seconds
