### ISSUE TITLE
Log agent version on startup

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14292]
Log agent version on startup, helps identifying version when checking logs/debugging etc

**Comment by adingilloRancher** [comment]
Master 6/29/18

`Austins-MBP:austinmasterallroles1 adingillo$ docker logs 4b3
2018/06/27 16:16:29 [INFO] Rancher version e7c4eee is starting
2018/06/27 16:16:29 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil>}`

Validated version is seen in logs.
