### ISSUE TITLE
GKE Cluster Options that require api endpoints

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#14298]
This is a list of GKE options that we do not currently implement (at the cluster level).  These are those options that require a special endpoint to be created so that the appropriate options can be displayed to the user on the UI.

1. additional zones
2. network
3. project access
4. maximum number of nodes per pool

**Comment by phpjob** [comment]
Hey @nathan-jenan-rancher,

Does the following error message, "GCE metadata" instance / zone "not defined", have any connection with this? At cluster level -> storage -> persistent volume
Unfortunately, I do not understand how to include the metadata (https://cloud.google.com/compute/docs/storing-retrieving-metadata#default).

Is there a documentation on how to integrate the gce persistent disk as volume over the Kubernetes interface?

**Comment by jiaqiluo** [comment]
The feature is validated on Rancher: master 2/15
The following aresa are tested to make sure they are set and show properly on both Rancher and Google Could:
* additional zones
* network
* maximum number of nodes per pool
-------
The bugs found during the validation are tracked by separate issues:
- https://github.com/rancher/rancher/issues/18069

---------
@fyery-chen  Could you show me where to check the `project access` on Google Cloud? 
This is the UI in Rancher: 
<img width="1433" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52878974-41d70780-311b-11e9-9f74-7c7bc7c44402.png">

**Comment by fyery-chen** [comment]
@jiaqiluo 
First, you should find the instance group showing in the node pool.
Then, you can access the instance group to check out the instances.
Last, selecting an instance and checkout the details of it, you can see that 
![image](https://user-images.githubusercontent.com/6060442/52926836-81e3f780-3372-11e9-9000-c58355cff011.png)

**Comment by jiaqiluo** [comment]
Met this issue while validating the project access feature
https://github.com/rancher/rancher/issues/18226

**Comment by jiaqiluo** [comment]
The bug #18226 is fixed and validated on Rancher: master 2/20
