### ISSUE TITLE
GKE options for node pool

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#14299]
This is a list of items that we need to implement along with the ability to specify node pools in GKE.  We also need to figure out why node pools are not displaying correctly with GKE (and possible AKS, EKS, and import).

Items that do not need api endpoints:
1. kubernetes node labels
2. Automatic node upgrade
3. automatic node repair
4. Preemtible nodes
5. Node taints
6. Local ssd disk
7. Boot disk size
8. autoscaling

Items that require special api endpoints to display options to the user:
1. Node image - moved to https://github.com/rancher/rancher/issues/16411
2. Service account/access scopes

**Comment by cjellick** [comment]
is this part of first-class node pools @nathan-jenan-rancher ?
