### ISSUE TITLE
Improve error message when EKS cluster fails to be created

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14291]
**Rancher versions:**
rancher/rancher:master 6/29

**Steps to Reproduce:**
Create an EKS cluster with a user who does not have the correct IAM roles

**Results:**
Cluster fails to provision. UI displays an error `Error creating stack: stack failed to create: reason unknown`

Console shows a call to `.../v3/cluster/c-nqmx9/namespaces?limit=-1&sort=name` failing with: 
```
{"actionLinks":{},"baseType":"error","code":"ClusterUnavailable","links":{},"message":"ClusterUnavailable 503: cluster not found","status":503,"type":"error"}
```

```
API: iam:CreateRole User: arn:aws:iam::605812595337:user/brandon is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::605812595337:role/c-nqmx9-eks-service-role-AWSServiceRoleForAmazonEK-1P4C17ULGFEOA
```

**Comment by superseb** [comment]
Rewritten title to cover catching errors when cluster is created, for instance (from https://github.com/rancher/rancher/issues/15205)

```
Parameter validation failed: parameter value sg-x,sg-x for parameter name ClusterControlPlaneSecurityGroup does not exist. Rollback requested by user.
```

**Comment by maxkorp** [comment]
The issue was twofold. First, we changed our error message string for bad http response codes, so our check for clusterConflicts (cluster already exists) was being missed. Second, we were only getting error reasons from VPCs, so other failures would just show up as `reason unknown`

The fix is here: https://github.com/rancher/kontainer-engine/pull/87

**Comment by jiaqiluo** [comment]
Failed in validation.

Rancher:master on 11/28

Steps:
Add a Amazon EKS cluster with a wrong IAM role

Result:

Failed to provision the cluster, the UI show the error: 
```
Error creating stack: stack failed to create: reason unknown
```

![screenshot](https://user-images.githubusercontent.com/6218999/49184809-870a4b00-f31d-11e8-83bd-26a02626e85f.png)

Rancher's log shows this error:
```
[ERROR] ClusterController c-wpsbk [cluster-provisioner-controller] failed with : error creating stack: stack failed to create: reason unknown
W1128 21:53:07.945215       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Event ended with: The resourceVersion for the provided watch is too old.
```


Also, it is wired that the EKS cluster is active on AWS console even thought the IAM role is invalid.

(see the cluster named "eks"  )
<img width="1593" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49184907-bfaa2480-f31d-11e8-89fe-53b6d9134231.png">

**Comment by maxkorp** [comment]
Gah, the way we intercept these errors has completely changed again. Looking into it.

**Comment by maxkorp** [comment]
So talking to @jiaqiluo it was tested with an invalid AMI not an invalid IAM role
When I did the same thing, it showed me the error in the UI however.

**Comment by maxkorp** [comment]
Was able to repro what @jiaqiluo found, although that is a separate issue from this one. He's writing that up in a new ticket.

**Comment by maxkorp** [comment]
Yeah when i submitted the fix for the IAM role issue, it functioned by also including far more error sources than before. I'd say this should be closed.

**Comment by maxkorp** [comment]
New ticket for the AMI issue is here: https://github.com/rancher/rancher/issues/16786. It's related to this, but it feels like a second round of improvements rather than part of this one explicitly.

**Comment by jiaqiluo** [comment]
Close since it is out of date (see above comments for details).
