### ISSUE TITLE
Rancher 2.0: OpenVPN connection is not established properly 

### ISSUE THREAD

**Issue by kc004** [rancher/rancher#14303]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent: 

**Infrastructure Stack versions:**
kubernetes (if applicable):  1.10.1

**Docker version: (`docker version`,`docker info` preferred)** 17.3.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** OS Ubuntu 16.04 & Kernel 4.15-4.17

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
Launch OpenVPN from Rancher catalogue and generate OpenVPN key to access the cluster. Try to connect the cluster using that key and you'll be received a new IP address.  

**Problem**
The issue is i am not able to call kubernetes services locally using VPN and also my internet is stopped working after connecting to VPN. 

Here are some routes logs:

**With VPN connection**
/ # nslookup google.com
  DNS request timed out.
      timeout was 2 seconds.
  Server:  UnKnown
  Address:  10.43.0.10 {{{ kube-dns IP address}}

  DNS request timed out.
      timeout was 2 seconds.

**Without VPN connection**
/ # nslookup google.com
  Server:  UnKnown
  Address:  192.168.0.1

  Non-authoritative answer:
  Name:    google.com
  Addresses:  2404:6800:4009:809::200e
            216.58.203.206

**In Kubernetes OpenVPN pod console**
/ # nslookup google.com
**nslookup: can't resolve '(null)': Name does not resolve**
Name:      google.com
Address 1: 173.194.66.101 qo-in-f101.1e100.net
Address 2: 173.194.66.100 qo-in-f100.1e100.net
Address 3: 173.194.66.113 qo-in-f113.1e100.net
Address 4: 173.194.66.102 qo-in-f102.1e100.net
Address 5: 173.194.66.139 qo-in-f139.1e100.net
Address 6: 173.194.66.138 qo-in-f138.1e100.net
Address 7: 2607:f8b0:400d:c01::8b qo-in-x8b.1e100.net

/ # nslookup kubernetes.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve
Name:      kubernetes.default.svc.cluster.local
Address 1: 10.43.0.1 kubernetes.default.svc.cluster.local

It can resolve my service DNS and give my IP address of that service but not able to find nameserver as kube-dns.kube-system.svc.cluster.local

**Route of OpenVPN pod console**
/ # iproute
default via 169.254.1.1 dev eth0 
10.240.0.0/16 via 10.240.0.2 dev tun0 
10.240.0.2 dev tun0  src 10.240.0.1 
169.254.1.1 dev eth0

**Comment by longwuyuan** [comment]
(1) You should ask this in #openvpn community.
(2) VPN fundamentals are ignored I think. Data above does not show anything whatsoever about the public ipaddress which will be exit gateway for the vpn-clients. I don't even know how to do that from inside a openvpn pod. Who will handle the client packets and send them out through a public-ipaddress. What is the DNS server that will provide name to ip lookups for hte clients. etc. These questions you need to clarify from the community/forums of openvpn.

Otherwise someone else may comment and help you solve this problem. Good luck

**Comment by blackholegalaxy** [comment]
The problem is not only about openvpn since kube-dns doesn't seem to resolve any domain name

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue in v2.1.5, and we'll reopen it.

**Comment by kc004** [comment]
I solved it by IP forwarding in the container. 
Step to solve this problem:
1. Check the OpenVPN deployment where it is deployed (Host)
2. Go to that Host and find OpenVPN docker image.
3. Execute this command to on IP forwarding in OpenVPN docker container.
`nsenter -t $(docker inspect --format '{{.State.Pid}}' $CONTAINER_NAME) -n sysctl -w net.ipv4.ip_forward=1`
