### ISSUE TITLE
pipeline jenkins plugins download failed

### ISSUE THREAD

**Issue by MutterCai** [rancher/rancher#14301]
rancher2
After setting the pipeline, jenkins pod init failed.
plugins download failed...
wget plugins url get 404...

 Analyzing war...
Registering preinstalled plugins...
Downloading plugins...
Downloading plugin: kubernetes from https://updates.jenkins.io/download/plugins/kubernetes/1.1.4/kubernetes.hpi
Downloading plugin: timestamper from https://updates.jenkins.io/download/plugins/timestamper/1.8.9/timestamper.hpi
Downloading plugin: workflow-job from https://updates.jenkins.io/download/plugins/workflow-job/2.17/workflow-job.hpi
Downloading plugin: workflow-aggregator from https://updates.jenkins.io/download/plugins/workflow-aggregator/2.5/workflow-aggregator.hpi
Downloading plugin: credentials-binding from https://updates.jenkins.io/download/plugins/credentials-binding/1.13/credentials-binding.hpi
Downloading plugin: git from https://updates.jenkins.io/download/plugins/git/3.6.4/git.hpi
Downloading plugin: kubernetes-plugin from https://updates.jenkins.io/download/plugins/kubernetes-plugin/1.1.4/kubernetes-plugin.hpi
Downloading plugin: workflow-job-plugin from https://updates.jenkins.io/download/plugins/workflow-job-plugin/2.17/workflow-job-plugin.hpi
Downloading plugin: credentials-binding-plugin from https://updates.jenkins.io/download/plugins/credentials-binding-plugin/1.13/credentials-binding-plugin.hpi
Downloading plugin: timestamper-plugin from https://updates.jenkins.io/download/plugins/timestamper-plugin/1.8.9/timestamper-plugin.hpi
Downloading plugin: git-plugin from https://updates.jenkins.io/download/plugins/git-plugin/3.6.4/git-plugin.hpi
Downloading plugin: workflow-aggregator-plugin from https://updates.jenkins.io/download/plugins/workflow-aggregator-plugin/2.5/workflow-aggregator-plugin.hpi
Failed to download plugin: kubernetes or kubernetes-plugin
Failed to download plugin: workflow-job or workflow-job-plugin
Failed to download plugin: timestamper or timestamper-plugin
Failed to download plugin: credentials-binding or credentials-binding-plugin
Failed to download plugin: git or git-plugin
Failed to download plugin: workflow-aggregator or workflow-aggregator-plugin
WAR bundled plugins:
Installed plugins:
*:
Some plugins failed to download! Not downloaded: kubernetes
Not downloaded: workflow-job
Not downloaded: timestamper
Not downloaded: credentials-binding
Not downloaded: git
Not downloaded: workflow-aggregator

**Comment by orangedeng** [comment]
I try to download those plugins with VPN. It was ok. Seems like it is because of the GFW.

**Comment by gitlawr** [comment]
Are you getting 404 when trying:

**Comment by MutterCai** [comment]
These are not downloadable：
Downloading plugin: kubernetes-plugin from https://updates.jenkins.io/download/plugins/kubernetes-plugin/1.1.4/kubernetes-plugin.hpi
Downloading plugin: workflow-job-plugin from https://updates.jenkins.io/download/plugins/workflow-job-plugin/2.17/workflow-job-plugin.hpi
Downloading plugin: credentials-binding-plugin from https://updates.jenkins.io/download/plugins/credentials-binding-plugin/1.13/credentials-binding-plugin.hpi
Downloading plugin: timestamper-plugin from https://updates.jenkins.io/download/plugins/timestamper-plugin/1.8.9/timestamper-plugin.hpi
Downloading plugin: git-plugin from https://updates.jenkins.io/download/plugins/git-plugin/3.6.4/git-plugin.hpi
Downloading plugin: workflow-aggregator-plugin from https://updates.jenkins.io/download/plugins/workflow-aggregator-plugin/2.5/workflow-aggregator-plugin.hpi

**Comment by orangedeng** [comment]
Not an issue, closed

**Comment by scheleaap** [comment]
I'm encountering this issue on my local machine and on Travis CI since a few days. Before, it always used to work.

https://travis-ci.org/scheleaap/jenkins-automation

**Comment by qingfengming** [comment]
I get this problem too, try to add a http/https_proxy ,doesn'twork; so sad ....

**Comment by scheleaap** [comment]
In my case, it turned out I was to blame after all: I was using incorrect proxy settings. It's working fine now: https://travis-ci.org/depositsolutions/jenkins-automation
