### ISSUE TITLE
Import HA cluster in Rancher UI:  cannot validate certificate because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by gabx** [rancher/rancher#14304]
**Rancher versions:**
rancher/server or rancher/rancher: rancher version v0.6.7

**Docker version: (`docker version`,`docker info` preferred)**

> Containers: 2
>  Running: 1
>  Paused: 0
>  Stopped: 1
> Images: 2
> Server Version: 18.03.1-ce
> Storage Driver: btrfs
>  Build Version: Btrfs v4.11.1
>  Library Version: 102
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.16.16-200.fc27.x86_64
> Operating System: Fedora 27 (Cloud Edition)
> OSType: linux
> Architecture: x86_64
> CPUs: 8
> Total Memory: 17.63GiB
> Name: dahlia
> ID: PIZ7:KA2Z:SPZW:PO7W:TIYP:V6V3:BRZH:XNIU:7NI5:ORTQ:HFGZ:GQTU
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: fals

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

> 4.16.16-200.fc27.x86_64

> NAME=Fedora
> VERSION="27 (Cloud Edition)"
> ID=fedora
> VERSION_ID=27
> PRETTY_NAME="Fedora 27 (Cloud Edition)"
> ANSI_COLOR="0;34"
> CPE_NAME="cpe:/o:fedoraproject:fedora:27"
> HOME_URL="https://fedoraproject.org/"
> SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_BUGZILLA_PRODUCT="Fedora"
> REDHAT_BUGZILLA_PRODUCT_VERSION=27
> REDHAT_SUPPORT_PRODUCT="Fedora"
> REDHAT_SUPPORT_PRODUCT_VERSION=27
> PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
> VARIANT="Cloud Edition"
> VARIANT_ID=cloud

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

> Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

> HA rancher

**Steps to Reproduce:**
Follows official [Rancher instructions](https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install-external-lb/)  to install HA server with external Lb.
After running `rke up --config rancher-cluster.yml`, cluster installation was successful. Connect to rancher UI, then `add cluster > import`. Run `kubectl apply -f https://83.166.150.131:10443/v3/import/wd7876kzhd82tmg7bdtlk6kq7f24l942wf648j9nll4qq5lszlrd9l.yaml`

**Results:**
Above command returns error:

> Unable to connect to the server: x509: cannot validate certificate for 83.166.150.131 because it doesn't contain any IP SANs

**Comment by superseb** [comment]
Following the official instructions ends up in visiting the Rancher UI at `https://<FQDN>` (no port, default 443), where is `https://83.166.150.131:10443` coming from? What URL are you using to visit the UI, what are you configuring as `server-url` when you first login to Rancher?

**Comment by gabx** [comment]
`https://83.166.150.131:10443` is the URL of Rancher UI. When I first login, I let this URL like that

**Comment by superseb** [comment]
Why are you not using your FQDN as chosen when following the instructions?
Why are you exposing `10443` on the outside while the instructions say to expose `80` and `443`

**Comment by gabx** [comment]
I am using these ports as I have already nginx Lb on 80 and 443. I start the container this way:
`docker run -d --restart=unless-stopped -e JAVA_OPTS="-Xms2048m -Xmx2048m" -p 10080:80 -p 10443:443 -v /etc/pki/tls/cert/TTH-CA-cert.pem:/etc/rancher/ssl/cacerts.pem rancher/rancher:latest`
And why not use IP instaed of FQDN? It shall be the same, no?

**Comment by superseb** [comment]
Rancher HA is using RKE to built a k8s cluster to run Rancher on. That means that `rancher/rancher` is launched onto the k8s cluster built by RKE. So if you follow the instructions closely, you can visit your chosen FQDN in the instructions to access the Rancher UI.

From there on, you can start working with Rancher. Why are you running a single install Rancher next to it on custom ports and connecting to it?

If you have got Rancher setup using HA (that means no single install `docker run`, but visiting the launched `rancher/rancher` container inside the built k8s cluster by RKE by visiting `https://<YOUR_CHOSEN_FQND>` and work with Rancher from there.

It's unclear to me what you are trying to achieve, and leaving out these details in issues don't help with resolving them.

**Comment by gabx** [comment]
i am not the only one with issues when importing HA cluster in Rancher UI. No one on the Slack could gimme am answer and everyone is messed with the cert story as the doc is not clear. 
I did everything correct following the doc. I didn't run ONE `docker` run. I only use rke binary on the API server. This server is not part of the cluster. It is here just to run Rancher server and Nginx Loadbalancer.
I was supposed to import the cluster with the command you provide, but it failed. So please try to imagine your doc is very incomplete and very complicated. A lot of user complain about the lack of clarity. Stop suggesting I do everything wrong and tell me why I have this issue. 
How shall the SAN part of the cert looks like?

**Comment by superseb** [comment]
That's the problem, the HA cluster docs are for running a highly available cluster with Rancher running on it. Like I described above. That means that you get a k8s cluster with Rancher server (`rancher/rancher`) running on top of it, which is shown as `local` (Imported) in the UI. From there on, you can start using Rancher to:

- Create new clusters using Custom
- Create new clusters using Node Drivers (EC2/DigitalOcean) etc
- Create hosted clusters (AKS/EKS/GKE)
- Import existing clusters (those can be any running k8s cluster, but obviously not the cluster it is running one, as that is already available as `local` (Imported).

Further discussed on Slack.

**Comment by gabx** [comment]
After the talk on Slack, it seems I didn't follow in an academic way the official documentation and messed between Kubernetes cluster and Rancher cluster. This is probably the root of my issue. I will be back after a new try. Thank you for your prompt answer.
