### ISSUE TITLE
Validate k8s 1.10.5 for v1.6

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14307]
Validate k8s 1.10.5 for v1.6

**Comment by sangeethah** [comment]
Automated K8s run succeeded on the following configurations with k8s 1.10.5 using rancher server - v1.6.19-rc2.

1. ROS  with docker 17.03
2. ROS  with docker 1.12
3. Ubuntu 16.04 with docker 1.13
4. RHEL 7.5 with native docker 1.12
5. RHEL 7.5 with native docker 1.13 -- Need to look into some failure . Mostly test case related.
6. RHEL 7.5 with native docker 17.03
