### ISSUE TITLE
Validate k8s 1.10.5 for v2.0

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14308]
Validate k8s 1.10.5 for v2.0

**Comment by deniseschannon** [comment]
rancher/hyperkube:v1.10.5-rancher1`is available

**Comment by sangeethah** [comment]
@soumyalj Could you make sure that upgrades from k8s 1.10.3 to 1.10.5 works on fresh install of rancher server version v2.0.5?

Also Test upgrade from v2.0.4 -> v2.0.5 and then upgrade k8s from 1.10.3 to 1.10.5.

**Comment by soumyalj** [comment]
Upgrades from k8s1.10.3 to v1.10.5 was successful. Workloads/ingress created before and after upgrade in a cluster were functional.
Also, upgrade from  v2.0.4 -> v2.0.5 and then upgrade k8s from 1.10.3 to 1.10.5 was successful.
