### ISSUE TITLE
Helm Catalog Refuses to Execute Pre-Hooks from Chart

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rancher#14316]
**Rancher versions:**
rancher/rancher:v2.0.4

**Steps to Reproduce:**

1. Create local Helm repo

```
helm init --local-repo-url 159.89.139.111 --service-account tiller \
  --tiller-namespace tiller-world
```

2. Extract Helm chart

```
unzip nginx.zip
```

3. Package the chart

```
helm package nginx
```

4. Server the chart

```
helm serve --address 159.89.139.111:8879
```

5. Add custom catalog & deploy **nginx chart**

**Results:**

The **pre-install** hook does not get executed, it is supposed to sleep for 2 minutes. All of the containers are deployed without the sleep being executed.

**Note:** the pre hooks are not executed through **Rancher UI**, if I use helm from the command line then it works and sleeps for 2 minutes.

**Helm CLI** process:

Repeat steps 1-3

Using the link below, I followed 

"**Example:** Deploy Tiller in a namespace, restricted to deploying resources only in that namespace"

https://github.com/kubernetes/helm/blob/master/docs/rbac.md

```
helm install nginx/ --tiller-namespace tiller-world --namespace tiller-world
```

**Summary:**

- The pre hooks seem to work when using **helm** install from cli. 
- The pre hooks fail to execute when using **Rancher UI Catalog** (custom catalog)

**Comment by massimo-cannavo** [comment]
[nginx.zip](https://github.com/rancher/rancher/files/2150892/nginx.zip)

**Comment by massimo-cannavo** [comment]
https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md

**Comment by hdiongithub** [comment]
I have a similar problem with the pre-delete hook annoation for a job. This job is executed immediately after installation from catalog. Helm from commandline works as expected. So it seems to me that the helm hook annotations ("helm.sh/hook") are ignored. 

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "api-gw-helm-config.fullname" . }}-pre-delete-job
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:

**Comment by cjellick** [comment]
@StrongMonkey we should also be able to write a validation test that exercises pre/post hooks

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
