### ISSUE TITLE
Unsuccessful attempt to add Azure Container Service shows blank error in UI

### ISSUE THREAD

**Issue by andymelichar** [rancher/rancher#14310]
**Rancher versions:**
rancher/rancher: 2.0.4

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS (Xenial Xerus) 4.4.0-128-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Attempting to add Azure containers service

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Standalone Rancher running in docker

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
1. Spin up a standalone Rancher docker install
2. Attempt to add an Azure Container Service cluster
3. Fill in the required details and click "Next: Authenticate and Configure Nodes"
4. If the request to Azure is unsuccessful, a blank error message is shown:
![acs-blank-error](https://user-images.githubusercontent.com/357100/42102906-5ef76954-7b95-11e8-8a45-2e97484f01a1.PNG)
5. You have to go into console/chrome developer tools to see the error actually being returned by Azure. Underlying error in this instance is a permission error from Azure (likely because I'm on a Trial Account?)

```error: "failed to get orchestrators: containerservice.ContainerServicesClient#ListOrchestrators: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '[redacted]' with object id '[redacted]' does not have authorization to perform action 'Microsoft.ContainerService/locations/orchestrators/read' over scope '/subscriptions/[redacted]'.```

**Results:**
Cannot troubleshoot ACS credential failure without having to debug through console/developer tools.

**Comment by codedevote** [comment]
I am having the same problem. I created a service principal as documented here https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#pre-create-a-new-sp. Trying to setup an AKS cluster using the credentials of the created ServicePrincipal also leads to blank error in rancher UI. Using developer console I can see the same error as @andymelichar. 
Nevertheless, following the instructions on how to create a ServicePrincipal linked from the docs at https://rancher.com/docs/rancher/v2.x/en/tasks/clusters/creating-a-cluster/create-cluster-azure-container-service/ I was able to create a SP that worked.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/12
Not fixed
![image](https://user-images.githubusercontent.com/11514927/42659765-18764bdc-85de-11e8-9445-dd7dbe3bd2ce.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/17
Still broken, same thing

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Still broken - same thing

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
