### ISSUE TITLE
load balancing  413 Request Entity Too Large

### ISSUE THREAD

**Issue by alanxie1129** [rancher/rancher#14323]
**Rancher versions:**
2.02
rancher/server or rancher/rancher:
rancher/server 
rancher/agent or rancher/rancher-agent:
rancher/rancher-agent
**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
18.03.1-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos7 3.10.0-862.3.3.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1.create new load balancing of the upload file service 
2.upload file up to 4M 
3.413 Request Entity Too Large
**Results:**

**Comment by superseb** [comment]
- Open kubectl
- Run the following patch to the NGINX configmap
```
kubectl patch configmap nginx-configuration -n ingress-nginx -p '{"data":{"proxy-body-size":"0"}}'
```
- Wait for NGINX to update the configmap
```
kubectl logs -n ingress-nginx -l app=ingress-nginx | grep UPDATE | grep ConfigMap
```
- Try uploading it again

Let me know if it doesn't work.

**Comment by superseb** [comment]
If you want to change it per ingress you can add the following annotation when creating the Ingress:

```
nginx.ingress.kubernetes.io/proxy-body-size: 0
```

**Comment by pensiero** [comment]
Thanks @superseb 
Do you think this should be reported on the documentation?

**Comment by Remigius2011** [comment]
@superseb while the `kubectl patch configmap` command worked immediately (thanks!), it would imho be nice to be able to update a running ingress to avoid downtime on the occurrence of such problems (tried to edit an ingress on v2.1.1 without success).

**Comment by dmastag** [comment]
Curious that using this on the per ingress still doesn't help my gitlab instance to upload the artifacts

```
nginx.ingress.kubernetes.io/proxy-body-size: 500m
```

![image](https://user-images.githubusercontent.com/5745805/48875691-fe774080-ee2c-11e8-8892-500af1d95389.png)

**Comment by dmastag** [comment]
On myside using the setup from kubectl from @superseb is not working
`kubectl patch configmap nginx-configuration -n ingress-nginx -p '{"data":{"proxy-body-size":"0"}}'`

I am trying to upload 300MB of artifacts on gitlab.

**Comment by Remigius2011** [comment]
@dmastag in addition to the `nginx` configuration, there may be other locations that influence the maximum upload size, like:

* `git` parameter `http.postBuffer` client config, see e.g. https://stackoverflow.com/questions/2702731/git-fails-when-pushing-commit-to-github
* `gitlab` config, see e.g. https://gitlab.com/gitlab-org/gitlab-ce/issues/14841 or https://github.com/sameersbn/docker-gitlab/issues/1726#issuecomment-423429587

it may be possible to identify the exact root cause depending on the exact error message, but I think at least the errors resulting from limitations on `nginx` and `gitlab` are identical (HTTP status code 413). btw, I would reccomend to set a high but reasonnable maximum instead of an unlimited upload size.

**Comment by Legym** [comment]
I know this is old, but in case anyone runs into this, you can add this in the UI

Workloads > Load balancing > (Select your Ingress) > Labels & Annoations

<img width="1326" alt="Screen Shot 2019-11-21 at 3 15 59 AM" src="https://user-images.githubusercontent.com/4462368/69319546-606bb100-0c0d-11ea-891d-fcb0ac572e8a.png">

**Comment by kungfu71186** [comment]
> 
> 
> I know this is old, but in case anyone runs into this, you can add this in the UI
> 
> Workloads > Load balancing > (Select your Ingress) > Labels & Annoations
> 
> <img alt="Screen Shot 2019-11-21 at 3 15 59 AM" width="1326" src="https://user-images.githubusercontent.com/4462368/69319546-606bb100-0c0d-11ea-891d-fcb0ac572e8a.png">

Can't believe I had to dig this deep to find this.

**Comment by BhautikChudasama** [comment]
Can anyone explain why 0? and If I set it to `0` it's working?
ℹ️ http://nginx.org/en/docs/syntax.html measurement units
