### ISSUE TITLE
Create Cluster on Azure: How to add more disks for storage (e.g. for rook) ?

### ISSUE THREAD

**Issue by jomeier** [rancher/rancher#14326]
Hello,

how can I add more disks to VMs which are created by Rancher 2 on Azure?

I like to have additional disks for storage (e.g. for rook.io) which are used exclusively used as raw block device for performance reasons.

I'm pretty sure that the reason is easy. Maybe some rke configuration or an entry in the node template?

Thanks a lot and best regards,

Josef

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`authenticated.node-templates`|

**Comment by jomeier** [comment]
For sure I could create a disk on Azure manually. My question was more about how I can do that only with rancher.

**Comment by tfiduccia** [comment]
@jomeier - We do not have a way to create disks or even add them.  We rely on docker machine and they do not have options for disks.  You can enter a docker issue for this?
