### ISSUE TITLE
Show nodes in pods list

### ISSUE THREAD

**Issue by Leen15** [rancher/rancher#14321]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.4

**Steps to Reproduce:**
Open a workload and check Pods panel

**Results:**
I cannot see on what node every pod is running.
Is it possible to add a Node column?

![image](https://user-images.githubusercontent.com/3629071/42126851-a3a5f666-7c8e-11e8-848c-2afd627e8003.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
