### ISSUE TITLE
Azure Dv3 series are not supported

### ISSUE THREAD

**Issue by gochist** [rancher/rancher#14320]
**Rancher versions:**
rancher/rancher:2.0.4

**Steps to Reproduce:**
1. "Add Node Template" 
2. Select Microsoft Azure
3. Drop down "Instance > Size" input box.

**Results:**
No Dv3 Series VMs can be selected

**Comment by vincent99** [comment]
https://azure.microsoft.com/en-us/blog/introducing-the-new-dv3-and-ev3-vm-sizes/

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/12
Verified fixed
