### ISSUE TITLE
Create Custom cluster - GUI usability problem

### ISSUE THREAD

**Issue by AlSeKr** [rancher/rancher#14325]
rancher/rancher 2.0.2
rancher/agent

Bare-metal, single node rancher (though not relevant)

When creating custom cluster, it's not clear that the command in the top of the screen depends on check-marks for node roles that are below. As a new user I tried to create cluster several times and waited it to come up before realized that I need to check roles first and only then to copy a command above them.
I'd suggest to move check boxes above command, or otherwise move them to the same frame with command to group them together.

Thanks.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/17
Verified fixed

**Comment by AlSeKr** [comment]
Thank you.
What version should get the fix? 2.0.7?

**Comment by tfiduccia** [comment]
@AlSeKr - yep 2.0.7 should have it in.
