### ISSUE TITLE
rancher2 allows change in configmap name, but change isn't propagated

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#14327]
**Rancher versions:**
2.0.4

**Steps to Reproduce:**

- create a configmap called `foo-map`
- deploy a workload that uses `foo-map`
- after deployment, edit `foo-map` and change its name to `bar-map`
- edit the workload, changing `foo-map` to `bar-map`

**Results:**
- the workload redeploys, but fails to start. k8s reports `CreateContainerConfigError`
- `describe` the pod and see that k8s reports: `Error: configmaps "bar-map" not found`
- `kubectl get configmaps` shows that it is still defined as `foo-map`

**Comment by loganhz** [comment]
Thanks for your report. Fixed in https://github.com/rancher/rancher/issues/14094
