### ISSUE TITLE
Ingress is unable to find services running in other namespaces.

### ISSUE THREAD

**Issue by rajboruah** [rancher/rancher#14335]
Rancher versions: 2.0.2
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
healthcheck: 
ipsec: 
network-services: 
scheduler: 
kubernetes (if applicable): 1.10

**Docker version: (`docker version`,`docker info` preferred)**: 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**: Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**: VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**: Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**

I have installed k8s (1.10) using rancher 2.0. This is what the ingress yaml while installing the cluster to expose the rancher dashboard:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: cattle-system
  name: cattle-ingress-http
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"      # Enable ssl-passthrough to backend.
spec:
  rules:
  - host: myservice.com
    http:
      paths:
      - backend:
          serviceName: cattle-service
          servicePort: 443

This works fine. But when I add one more service into ingress by editing the active ingress by 'kubectl edit ingress cattle-ingress-http -n cattle-system':

  - host: myservice-grafana.com
    http:
      paths:
      - backend:
          serviceName: kube-prometheus-grafana
          servicePort: 80
		  
This new ingress rule does not work. I get "503 Service Temporarily Unavailable" when I hit http://myservice-grafana.com. The ingress pod logs shows:

$kubectl logs nginx-ingress-controller-cmcz6 -n ingress-nginx
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    154a606-dirty
  Build:      154a606
  Repository: git@github.com:rancher/ingress-nginx.git
-------------------------------------------------------------------------------

I0702 07:05:09.472942       5 main.go:181] Creating API client for https://10.43.0.1:443
I0702 07:05:09.502494       5 main.go:193] Running in Kubernetes Cluster version v1.10 (v1.10.1) - git (clean) commit d4ab47518836c750f9949b9e0d387f20fb92260b - platform linux/amd64
I0702 07:05:09.505446       5 main.go:84] validated ingress-nginx/default-http-backend as the default backend
I0702 07:05:10.248658       5 stat_collector.go:77] starting new nginx stats collector for Ingress controller running in namespace  (class nginx)
I0702 07:05:10.252827       5 stat_collector.go:78] collector extracting information from port 18080
I0702 07:05:10.269484       5 nginx.go:244] starting Ingress controller
I0702 07:05:11.381434       5 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cattle-system", Name:"cattle-ingress-http", UID:"6525b6b3-792e-11e8-b914-00155d7a541c", APIVersion:"extensions", ResourceVersion:"855783", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress cattle-system/cattle-ingress-http
I0702 07:05:11.482128       5 store.go:613] running initial sync of secrets
I0702 07:05:11.483792       5 nginx.go:665] starting TLS proxy for SSL passthrough
I0702 07:05:11.484021       5 nginx.go:266] starting NGINX process...
W0702 07:05:11.484796       5 controller.go:666] error obtaining service endpoints: error getting service cattle-system/kube-prometheus-grafana from the cache: service cattle-system/kube-prometheus-grafana was not found

The service account 'nginx-ingress-serviceaccount' has clusterrole binding and so ingress should not have any issue
in accessing services running in another namespace. (kube-prometheus-grafana is running in namespace 'monitoring' and ingress is running in namespace 'cattle-system'). Moreover, why is the ingress looking for kube-prometheus-grafana inside the namespace 'cattle-system' ?

nginx-ingress-controller image that rancher pulls in is 'rancher/nginx-ingress-controller:0.10.2-rancher3'(image id: docker-pullable://rancher/nginx-ingress-controller@sha256:58944b175505087dfa7afc444577d1933fd3bf1f1f668ef57b9eaaa8b36f59ce)

**Results:**
Hit http://myservice-grafana.com:
"503 Service Temporarily Unavailable"

**Comment by loganhz** [comment]
Thanks for your report.

This is a K8S limitation.  Please check https://github.com/kubernetes/kubernetes/issues/17088#issuecomment-156287304
