### ISSUE TITLE
Feature: Cluster Templates

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#14337]
Revive the environment template idea from 1.x.  Reusable cluster templates for 2.0 clusters. Could be implemented like node templates, but would be nice if they could be configured and shared by global admins for use by other cluster creators.

* RKE Cluster Options - network provider, K8s version, psp...
* Cloud Provider config
* Defined Node Pools/Node Templates.

Could be expanded to include default workloads/helm catalogs.

**Rancher versions:**
rancher/rancher:2.0.x

**Comment by janeczku** [comment]
Related/Depends #889043

**Comment by westlywright** [comment]
UI MVP for this is available in master.

**Comment by sangeethah** [comment]
This feature is available in latest master build.
Major workflows that are available as part of this feature are tracked in following issues:

https://github.com/rancher/rancher/issues/20370
https://github.com/rancher/rancher/issues/20371
https://github.com/rancher/rancher/issues/20417
https://github.com/rancher/rancher/issues/20418
https://github.com/rancher/rancher/issues/20420

Bugs found when testing this feature are tracked as separate issues.
