### ISSUE TITLE
Service record page is not showing corresponding data

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#14332]
**Rancher versions:**
rancher/rancher:master 7/2

**Steps to Reproduce:**
Create a project `b`,
Add namespace `c1`,`c2` to the project
Deploy a deployment named `ngx` in `c1` ns
Deploy a deployment named `ngx2` in `c2` ns
![image](https://user-images.githubusercontent.com/5697937/42158260-88af01be-7e22-11e8-83c0-92f92d73551f.png)

**Results:**
In `Service Discovery` page, edit `ngx2` service, it shows c1 ns with empty workload target
![image](https://user-images.githubusercontent.com/5697937/42158350-c051726e-7e22-11e8-92dd-3b538d16932b.png)
While editing `ngx` in c1 ns it looks good
![image](https://user-images.githubusercontent.com/5697937/42158412-edeac9e6-7e22-11e8-8ade-94495169a79b.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
