### ISSUE TITLE
OpenLDAP looks like it connects even when all info is wrong

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14339]
**Rancher versions:** 2.0 master 7/2

**Steps to Reproduce:**
1.  Put in all bad info in the openLDAP screen
2.  Authenticate with OpenLDAP

**Results:**  Looks like I logged in successfully.  But I really did not.
![image](https://user-images.githubusercontent.com/11514927/42181501-eda574a0-7def-11e8-9e67-459ef099c1f7.png)

**Comment by sangeethah** [comment]
Rancher server logs has the following error that shows up:
```2018/07/02 19:23:19 [ERROR] Unknown error: Error creating connection: LDAP Result Code 200 "": dial tcp 1.1.1.1:389: i/o timeout```

If you are still in the openldap provisioning page , we see the following error:

```TestAndApply Error
Error creating connection: LDAP Result Code 200 "": dial tcp 1.1.1.1:389: i/o timeout```

**Comment by carolynhu** [comment]
UI screenshot for this bug
<img width="908" alt="screen shot 2018-07-03 at 10 45 42 am" src="https://user-images.githubusercontent.com/29208297/42235990-56e82246-7eae-11e8-81e6-0fad56a9063a.png">

**Comment by westlywright** [comment]
I too am able to see that the auth failed with bad info but I think I might know what Tani is seeing. The ui briefly flashes, if there was a JS error the ui would probably stay on the "authorized" ui and not fall back to the "input" ui. I'll take this and fix the ui so it doesn't flash and won't get stuck.

**Comment by tfiduccia** [comment]
@carolynhu - was able to show Wes what I was seeing and that there is no error showing for me.  You have to put in a IP address that is the proper format (like 1.1.1.1) but invalid.  If you do that and fill in the rest of the info properly, it will success.  which it shouldn't

**Comment by westlywright** [comment]
the ui has been updated to prevent showing the `enabled` ui while the call is pending

**Comment by sangeethah** [comment]
Tested with Rancher server version - v2.0.5-rc3
Steps to Reproduce:
Put in all bad info in the openLDAP screen - (Hostname or IP Address - 1.1.1.1)
Authenticate with OpenLDAP 

After about ~1 minute , user is presented with the following error message:

<img width="1309" alt="screen shot 2018-07-05 at 12 06 32 pm" src="https://user-images.githubusercontent.com/4266958/42342790-fa608186-804b-11e8-96cd-903830535b34.png">

**Comment by lq13583** [comment]
I am having same issue now, why it is closed?

**Comment by tfiduccia** [comment]
@lq13583 - This issue is closed because this particular bug was fixed.  I have replicated the steps from this issue in our current version and cannot reproduce the bug.
Can you please open a new issue with your particular steps to reproduce, there must be something else that is going.  Mainly which field in the ldap screen is incorrect?
