### ISSUE TITLE
Install rancher 2.0 HA failed in the  beginning

### ISSUE THREAD

**Issue by kingsqv** [rancher/rancher#14331]
**Rancher versions:**
rke  any version

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

centos 7.4

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
nodes:
  - address: 172.16.5.55 # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [controlplane,etcd,worker] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file
  - address: 172.16.5.56
    user: root
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
  - address: 172.16.5.57
    user: root
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa

**Results:**
 ./rke_linux-amd64 up --config 3-node-externalssl-recognizedca.yml
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [172.16.5.57]
WARN[0000] Failed to set up SSH tunneling for host [172.16.5.57]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to /var/run/docker.sock: ssh: rejected: administratively prohibited (open failed)
INFO[0000] [dialer] Setup tunnel for host [172.16.5.55]
WARN[0000] Failed to set up SSH tunneling for host [172.16.5.55]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to /var/run/docker.sock: ssh: rejected: administratively prohibited (open failed)
INFO[0000] [dialer] Setup tunnel for host [172.16.5.56]
WARN[0000] Failed to set up SSH tunneling for host [172.16.5.56]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to /var/run/docker.sock: ssh: rejected: administratively prohibited (open failed)
WARN[0000] Removing host [172.16.5.57] from node lists
WARN[0000] Removing host [172.16.5.55] from node lists
WARN[0000] Removing host [172.16.5.56] from node lists
FATA[0000] Cluster must have at least one etcd plane host

**Comment by superseb** [comment]
Please follow https://rancher.com/docs/rancher/v2.x/en/installation/troubleshooting-ha/ssh-tunneling/, as you are using CentOS, you can't use root.

```
en using RedHat/CentOS as operating system, you cannot use the user root to connect to the nodes because of Bugzilla #1527565. You will need to add a separate user and configure it to access the Docker socket. See Manage Docker as a non-root user how to set this up properly.
```

Let me know if it doesn't solve your issue.
