### ISSUE TITLE
Typo in VMWare vSphere Volume provisioner

### ISSUE THREAD

**Issue by spawnia** [rancher/rancher#14333]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

vSphere with ESXI 6.0.0

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Cluster with v1.10.3-rancher2-1

Using a custom cloud provider config for vSphere

**Steps to Reproduce:**

Create storage class, choosing VMWare vSphere Volume as a provisioner

**Results:**

Storage class gets created, but has a type in the provisioner config. **vpshere -> vsphere**

```
> kubectl describe sc rancher
Name:               rancher
IsDefaultClass:     No
Annotations:        field.cattle.io/creatorId=user-72klr
Provisioner:        kubernetes.io/vpshere-volume
Parameters:         diskformat=thin
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed
