### ISSUE TITLE
When openLdap is disabled, allowedPrincipalIds and accessMode do not get cleared for the authprovider resulting is not being able to enable openLdap provider again.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14346]
**Rancher versions: Build from master

**Steps to Reproduce:**
Enable openLdap and have site access set to "Allow members of Clusters, Projects, plus Authorized Users and Organizations" / "Restrict access to only Authorized Users and Organizations" and allow few users in this list - say user1 and user2.

Disable  openLdap.
Enable openLdap and provide a valid user other than user1/user2 to "Test and enable authentication".

User is presented with "Permission denied" error message.

**Comment by deniseschannon** [comment]
I think this would probably be for all auth providers.

**Comment by deniseschannon** [comment]
This will be fixed by when we disable auth, we should be clearing out all allowed identities.

**Comment by deniseschannon** [comment]
We made a fix for https://github.com/rancher/rancher/issues/14071, which was saving the site access when you edit, but that change is also being applied to when someone disables auth and during enable, it's trying to find the saved access list. At that point, we should default to "allow all"

**Comment by cjellick** [comment]
@vincent99 agreed that disabling will RESET THE ENTIRE PROVIDER. and this will be handled by the backend

**Comment by cjellick** [comment]
wont make it into 2.0.5

**Comment by deniseschannon** [comment]
We'll use this one to track the UI fix so that when you disable/enable, site access defaults to the "allow all" and another ticket will be tracked to the fact that we don't reset the auth provider during disable.

**Comment by cjellick** [comment]
ticket for tracking auth provider reset https://github.com/rancher/rancher/issues/14363

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/5
Verified fixed
