### ISSUE TITLE
Shouldn't be able remove all users in restricted mode

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14347]
**Rancher versions:** 2.0 master 7/1

**Steps to Reproduce:**
1.  Authenticate using OpenLDAP
2.  Switch to restricted option
3.  All Authorized Users and Organization
4.  Save

**Results:**  Should not be able to remove the admin user from list.

**Comment by deniseschannon** [comment]
@tfiduccia can this happen with other auth providers? is it openldap specific?

**Comment by tfiduccia** [comment]
This needs be fixed in the Allow members of Clusters, Projects, plus Authorized Users and Org as well

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/9
Verified fixed
