### ISSUE TITLE
Set ssl-protocols

### ISSUE THREAD

**Issue by Leen15** [rancher/rancher#14340]
Hi would like to change the ssl-protocols setting but I found only that this should be changed in "ConfigMap".
How this should be done? Where I can change the current configMap for nginx-ingress?

Thanks

**Comment by superseb** [comment]
You can make it work in 2 ways:

Interactively:
```
kubectl edit configmap nginx-configuration -n ingress-nginx
```
Add the following:
```
data:
  ssl-protocols: TLSv1
```

Or via patch:

```
kubectl patch configmap nginx-configuration -n ingress-nginx -p '{"data": { "ssl-protocols": "TLSv1" } }' --type='merge'
```

Let me know if it doesn't work for you.

**Comment by Leen15** [comment]
Hi @superseb , I already tried the first command. 
When I edit this, it tells "configmap/nginx-configuration edited" 
Should nginx works immediately with the new config? Or I have to recreate pods or other stuff?
