### ISSUE TITLE
New Links needed in Rancher with name changes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1434]
Docs are moving to a new rancher.com address.

**Adding First Host:**
Old Link: `http://rancherio.github.io/rancher/docs/infrastructure/hosts/`
New Link: `http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/`

**Adding First Service:**
Old Link: `http://rancherio.github.io/rancher/docs/services/projects/adding-services/
New Link: `http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-services/`

**Amazon EC2 Ports**
Old Link: `https://rancherio.github.io/rancher/docs/infrastructure/hosts/amazon/#EC2Ports`
New Ling: `https://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/amazon/#EC2Ports`

**Comment by tfiduccia** [comment]
Is there a reason why we used https: for the port and non-https for the others?  Seems like it should just be http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/amazon/#EC2Ports.

**Comment by deniseschannon** [comment]
@vincent99 The link that Tani mentions needs to be http:// not https://. Sorry for the poor copy and paste.

**Comment by deniseschannon** [comment]
v0.27.0-rc4: Verified Fixed.
