### ISSUE TITLE
OpenLDAP - "unable to fetch user info" instead of auth info showing in restrict access

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14343]
**Rancher versions:** 2.0 master 7/2

**Steps to Reproduce:**
1.  Enter valid information into LDAP
2.  Authenticate with OpenLDAP
3.  Switch to Restrict access to only Authorized Users and Organizations

**Results:**  Unable to fetch user info is showing up as first user instead of the user information that I logged in with.
![image](https://user-images.githubusercontent.com/11514927/42189161-e906b7da-7e0b-11e8-92ca-0df5ee677566.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Verified fixed

**Comment by drewboswell** [comment]
This is not fixed, I have the same problem now. It appears to be an impersonation problem.

https://github.com/rancher/rancher/issues/16313

**Comment by BrassM0nkeyy** [comment]
Having a similar problem but with a adding a private org

**Comment by dongde** [comment]
“Unable to fetch user info”
Has anyone encountered this problem?

**Comment by jensenbox** [comment]
Still having this issue myself

**Comment by alexey-pelykh** [comment]
Same here
