### ISSUE TITLE
Pods can't resolve Services in Rancher 2.0 cluster.

### ISSUE THREAD

**Issue by portfield-slash** [rancher/rancher#14357]
**Rancher versions:**
rancher/rancher:latest(2018-06-14: v2.0.2)
rancher/rancher-agent:v2.0.2

**Infrastructure Stack versions:**
healthcheck:?
ipsec:?
network-services:flannel
scheduler:?
kubernetes (if applicable):v1.10.1-rancher2

**Docker version: (`docker version`,`docker info` preferred)**
■Master(etcd,Control,Worker)、Node(Worker)
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
■Master(etcd,Control,Worker)、Node(Worker)
3.10.0-327.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
RancherUI

1．[Workloads]-[Deploy]
2．I entered each item.

Workload Type：Stateful set of 1 pod
Port Mapping：Node Port,Cluser IP
Node Scheduling：Run all pods for this workload on a specific node（select Node(Worker)）
Health Check：None
Volumes：Add 1 volume
Command：`/sbin/init`
Privileged：Yes: container has full access to the host

3．Launch
4．`kubectl exec -it test-0 /bin/bash` on the Node.
5．`nslookup test` in the pod.

**Results:**
Error Message.

`;; connection timed out; no servers could be reached`

Do I need to set up on Rancher?
I stopped the firewall and ran it.

---

`kubectl get ep kube-dns --namespace=kube-system`

	NAME       ENDPOINTS                       AGE
	kube-dns   10.42.0.107:53,10.42.0.107:53   8d

---	

`kubectl get svc --namespace=kube-system`

	NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
	kube-dns   ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP   8d

---

`kubectl get pods --namespace=kube-system`

	NAME                                      READY     STATUS      RESTARTS   AGE
	kube-dns-5ccb66df65-kn7vd                 3/3       Running     21         8d
	kube-dns-autoscaler-6c4b786f5-z2ttf       1/1       Running     7          8d
	kube-flannel-2zz7c                        2/2       Running     16         8d
	kube-flannel-h6xmk                        2/2       Running     14         8d
	rke-ingress-controller-deploy-job-p8p9n   0/1       Completed   0          8d
	rke-kubedns-addon-deploy-job-nlsqk        0/1       Completed   0          8d
	rke-network-plugin-deploy-job-rmbwr       0/1       Completed   0          8d

---

`# cat /etc/resolv.conf`

	nameserver 10.43.0.10
	search default.svc.cluster.local svc.cluster.local cluster.local
	options ndots:5

---

`kubectl get svc`

	NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)      AGE
	test                ClusterIP   10.43.189.169   <none>        3306/TCP     1d

Other services are omitted.

---

**Comment by superseb** [comment]
There are a lot of restarts in the `kube-system` pods. Some pointers:

- `3.10.0-327.el7.x86_64` is a really bad kernel for running Docker. Supported OS is 7.5 with a proper kernel to run Docker.
- Are you running `firewalld`? Try turning it off and see if it improves.
- What nameservers are configured on the nodes added to the cluster (`cat /etc/resolv.conf`)

**Comment by portfield-slash** [comment]
@superseb 

Thank you for your quick response.
I stopped the firewall and ran it. I will upgrade to CentOS 7.5 and try again.
This is the nameserver set on the node.

	cat /etc/resolv.conf
	# Generated by NetworkManager
	nameserver 192.168.AAA.BBB

I masked `IP address`.

**Comment by portfield-slash** [comment]
@superseb

After setting the IP address(10.42.0.107) of endpoints in `resolve.conf`, name resolution succeeded.
Am I using the wrong way?The version of CentOS is intact.

`# cat /etc/resolv.conf`

	nameserver 10.43.0.10
	nameserver 10.42.0.107
	search default.svc.cluster.local svc.cluster.local cluster.local
	options ndots:5

---

`# nslookup test`

	;; reply from unexpected source: 10.42.0.107#53, expected 10.43.0.10#53
	Server:         10.42.0.107
	Address:        10.42.0.107#53

	Non-authoritative answer:
	Name:   test.default.svc.cluster.local
	Address: 10.43.189.169

**Comment by superseb** [comment]
Can you let us know if this still happens so we can continue investigating?

**Comment by portfield-slash** [comment]
It is closed and there is no problem.
Thank you for your advice.

**Comment by mdkhvn** [comment]
@superseb 
hi, i have same issue and my cluster info is :
i have 3 node : 1master node (control plane and etcd) 2 worker node
rancher: 2.4.4
kubernetes 1.17.11
Operating system is debian 10.5 with kernel 4.19.0-6-cloud-amd64
docker 18.9.1
my container cant connect to other container from network overlay hosted on other node
