### ISSUE TITLE
AKS cluster goes to "Unavailable" state intermittently

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#14354]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.4/v2.0.5

**Steps to Reproduce:**
1. Create an AKS cluster 
AKS cluster goes to "Unavailable" state intermittently and fixes itself eventually
<img width="1227" alt="screen shot 2018-07-02 at 9 46 28 pm" src="https://user-images.githubusercontent.com/18536626/42199844-8865c1b6-7e45-11e8-8e20-6f51a208d70c.png">

This happens before upgrade in v2.0.4 and also in v2.0.5-rc2 after upgrade.

**Comment by cjellick** [comment]
I think this is due to flakiness in AKS

**Comment by kvaes** [comment]
+1 Experiencing the same.

his cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.

Failed to communicate with API server: Get https://c-cspg-kvaes-test-ranch-be7a25-master-8e905666.hcp.westeurope.azmk8s.io:443/api/v1/componentstatuses?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)


Though when you click open up that API url, it'll respond.

**Comment by tonyyates** [comment]
Also experienced the same issue on v2.1.0 with two separate new clusters one on AWS ECS and one on Digital Ocean both created by Rancher.

**Comment by JasonvanBrackel** [comment]
@cjellick from a UI perspective these timeouts actually gray-out and block it. So even if we can't fix AKS, we should address the UX around this.

**Comment by vincent99** [comment]
Unavailable means it's... not available, so the UI had to disable everything that requires talking to the actual cluster.

**Comment by JasonvanBrackel** [comment]
I'm not being clear enough.  It's blocked as in, stuck on the loading indicator and I can't navigate off of it without a back button  It feels broken as in there's a rancher problem not an AKS problem and not indication to the user what is happening.  It's bad UX.

**Comment by vincent99** [comment]
Is there an error in the browser console?

**Comment by JasonvanBrackel** [comment]
Eventually, you'll get the red timeout box.  But well beyond a point that is reasonable.  

I would suggest instead of a generic loading after 5 seconds include a message along the lines of 

"Gathering information from <place we're dependent on>, this is taking longer than expected."

That way the user understands what is happening and that it's not normal rancher behavior.

**Comment by vincent99** [comment]
This issue is for the cluster going unavailable intermittently, which is seemingly reflecting the state of communication with specifically EKS.

What you're talking about is a separate problem where given a cluster (probably of any kind) that is unavailable (for whatever reason), you can click something that is making a request to that cluster and it doesn't respond because nobody's home, (which is why it's marked unavailable in the first place).

Please make a separate issue, with steps or a screencast or something because I still don't know what you're doing to get into that state.  But the solution is going to be to identify and stop making that request, not add text justifying it.

**Comment by Vashiru** [comment]
> Also experienced the same issue on v2.1.0 with two separate new clusters one on AWS ECS and one on Digital Ocean both created by Rancher.

Can confirm, just experienced the same issue on 2.1.0. The workaround of stopping `k8s_agent_cattle-node-agent-XXX_cattle-system_XXXX` manually mentioned here: https://github.com/rancher/rancher/issues/15319#issuecomment-427644418 still works

**Comment by janeczku** [comment]
For reference an upstream fix that addresses watch errors caused by closing of underlying connection:  https://github.com/kubernetes/kubernetes/pull/67817

**Comment by cjellick** [comment]
im going to carve this into two separate issues. This one will remain specifically for AKS clusters because in that case, we have no control over the API timing out. To address that, in v2.1 we added retry logic ot the component status check here:
https://github.com/rancher/rancher/pull/15698/files#diff-e71f5d636ea301a313752bdf624f1a82R94

The AKS API simply has random time outs, so the best we can do is retry.

The other non-AKS instances reported here appera to all be related to RKE provisioned clusters. For those, I have opened this issue: https://github.com/rancher/rancher/issues/16649
and we should root cause the underlying issue in the API server and see if it is something that we can fix.

If you are experiencing this problem, but your cluster ISNT an Azure Kubernetes Service cluster, please refer to https://github.com/rancher/rancher/issues/16649

**Comment by lud97x** [comment]
hello @cjellick ,
I have a ticket open with the Azure support about this issue. They ask for the api call name and their configuration used by rancher ui. Where can I get theses informations?

**Comment by janeczku** [comment]
@lud97x The timeout error messages in the UI as well as in the Rancher server log would have the full API URL that was invoked by Rancher. Usually those are read requests, ie a get or watch.

**Comment by cjellick** [comment]
We are working with the Azure team to investigate and resolve this. But, the investigation is largely on their end at this point. When/if they come back with things we should change on our end, we will make those changes

**Comment by mhermosi** [comment]
I am running a custom cluster, (actually have 2 clusters) on Proxmox VE using KVM nodes first cluster is fine.
Second cluster started failing after I decided to rename all the node servers.

Rancher: 2.1.2
Provider; Custom v1.11.3
Docker-ce: 18.09
# of nodes: 6
OS: Linux ... 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 18.04.1 LTS)

**Comment by digeler** [comment]
I am from MSFT and i dont think there is an issue with the CP(control plane).
i can easly repro the behavior : with 2.1.5
from cattle log ; 
2019/01/22 13:25:05 [INFO] Error on LIST daemonSets: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/apis/apps/v1beta2/daemonsets?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2019/01/22 13:25:05 [INFO] Error on LIST statefulSets: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/apis/apps/v1beta2/statefulsets?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2019/01/22 13:25:05 [INFO] Error on LIST replicationControllers: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/api/v1/replicationcontrollers?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2019/01/22 13:25:05 [INFO] Error on LIST cronJobs: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/apis/batch/v1beta1/cronjobs?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2019/01/22 13:25:05 [INFO] Error on LIST jobs: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/apis/batch/v1/jobs?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2019/01/22 13:25:05 [INFO] Error on LIST replicaSets: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/apis/apps/v1beta2/replicasets?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2019/01/22 13:25:05 [INFO] Error on LIST deployments: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/apis/apps/v1beta2/deployments?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2019/01/22 13:25:05 [INFO] Error on LIST services: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/api/v1/services?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2019/01/22 13:25:05 [INFO] Error on LIST persistentVolumeClaims: Get https://tvnet-2010bea5.hcp.northeurope.azmk8s.io:443/api/v1/persistentvolumeclaims?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
Client.Timeout exceeded while awaiting headers2019-01-22 13:27:33.662679 I | mvcc: store.index: compact 4333
2019-01-22 13:27:33.664875 I | mvcc: finished scheduled compaction at 4333 (took 873.606µs)
E0122 13:28:37.124706       8 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
2019-01-22 13:32:33.700406 I | mvcc: store.index: compact 4661
2019-01-22 13:32:33.702219 I | mvcc: finished scheduled compaction at 4661 (took 839.107µs)


inside the same docker container i run the same query and it runs without any issue : 
curl -v -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://tvnet-2010bea5.hcp.northeurope.azm8s.io/apis/apps/v1beta2/replicasets?timeout=30s

if running not silently i get  
curl -S  -H "Authorization: Bearer $KUBE_TOKEN" https://tvnet-2010bea5.hcp.northeurope.azmk8s.io/apis/apps/v1beta2/replicasets?timeout=30s
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

is there a way we can tell cattle to use for testing insecure to see if this behavior continue.
mean while ill check with backend team on our side.

**Comment by jiaqiluo** [comment]
The same abnormal behavior exists on rancher: master 1/31

**Comment by JasonvanBrackel** [comment]
@cjellick Any update on this from MS?

**Comment by mikenorgate** [comment]
@JasonvanBrackel @cjellick I currently have a support request open with Microsoft for this issue. @digeler who commented above is the support engineer that has been investigating and has told me that he is able to connect rancher and azure engineers if needed

**Comment by cjellick** [comment]
We are actively working with azure engineers. 

Working theory now is that an LB that Rancher is hitting does not consistently send RST packets when appropriate and that we can address/mitigate by configuring our clients and proxies differently. Will update this ticket if significant developments come in.

**Comment by cjellick** [comment]
We've made some tweaks to improve timeouts and keep-alives in our clients. I don't think they will 100% resolve this issue. But, I wanted to get them in and QAd to ensure they are non-harmful and to see if they make improvements for some of our AKS users.

**Comment by mikenorgate** [comment]
@cjellick what release will this be in? I'd be really happy to test this and see if it resolves our issues

**Comment by cjellick** [comment]
@mikenorgate First release it will land in is actually building right now: `v2.2.0-rc2`. Note that RCs have no garauntees and absolutely should not be ran in production, but if you have a non-prod setup you could test this in, we would love your feedback.
One question: do you spin up AKS clusters in rancher or direclty in AKS and then import them? Those two use cases have very different network flows

**Comment by mikenorgate** [comment]
Currently we spin the clusters up in rancher. Which use case would you expect things to be better in?

**Comment by cjellick** [comment]
that one, the one you are doing.

**Comment by mikenorgate** [comment]
I've been testing it the last couple of days and it seems fixed, everything is as response as expected

**Comment by soumyalj** [comment]
Tested with master from Feb 25 for a day. 
1. Created 3 node AKS cluster. 
2. Created few workloads, secrets, namespaces etc and navigated to different tabs. 

 Cluster did not go to "Unavailable" state. It was in actibe state.
Automation runs were fine and completed in a reasonable time.
