### ISSUE TITLE
visual indication if websocket connection failed to establish

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1435]
Sometimes the client side websocket connection fails to establish. The user sees spinning indicators that will never resolve and a manual page refresh is required. It would be nice to get a visual indicator that real-time updates are not available and also possibly fall back to polling for updates.

**Comment by cjellick** [comment]
Thans @defunctzombie. Good suggestion. @vincent99 any thoughts on this?

FYI, we are aware of the websocket connection issues and are working to fix that. So hopefully, you'll see these connection issues much less often.

For reference (and our own cross-referencing) here's the issue where we are working on the websocket connection issue: #1432

**Comment by vincent99** [comment]
I don't think this is particularly relevant anymore now that the sockets all go to WebSocket-proxy instead of individual hosts...
