### ISSUE TITLE
How to deploy a cluster with OpenStack cloud provider

### ISSUE THREAD

**Issue by rootdeep** [rancher/rancher#14355]
I  try to deploy a k8s cluster  with OpenStack cloud provider  by using  rancher2.0, but I don't find the correct way.

In my environment, the rancher server is running on a VM , and this VM is created by OpenStack.

Is there any instruction for me to follow up?

**Comment by balleddog** [comment]
You can do this by configuring kubelet's ``extra_args`` fields in RKE's cluster.yml

It looks like this: 
``    extra_args: {"feature-gates": "ReadOnlyAPIDataVolumes=false", "cgroups-per-qos": "false", "cloud-provider": "openstack", "cloud-config": "/etc/kubernetes/cloud-config", "volume-plugin-dir": "/var/lib/kubelet/volumeplugins" } ``

The ``/etc/kubernetes/cloud-config`` file should be placed on every OpenStack nodes in advance

This file looks like following:
[Global]
auth-url="http://10.109.0.220:5000/v3"&nbsp
username="xxx"  
password="xxx"  
region="xxx"  
tenant-id="xxx"  
domain-name="xxx"

**Comment by alexandrem** [comment]
The recommendation above is not really practicable.

Rancher v2.0.4 has new types definition for the openstack cloud provider that you can use in yaml either via the API or the Rancher UI:

https://github.com/rancher/types/blob/db9e09126d92700b192043e3f5ad094142dc094b/apis/management.cattle.io/v3/rke_types.go#L349

There are still some things to be solved to have this working correctly though: 14197

**Comment by deniseschannon** [comment]
In v2.0.5 (aiming to ship before end of this week), we've fixed the openstack issue in the UI where the yaml is being malformed. The correct  way you'd want to do it is to alter your cluster options and edit the yaml and add in the cloud provider information based on this: 

https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/#openstack

**Comment by rootdeep** [comment]
I am also confused about the step to use the openstack provider. As shown in picture 
![image](https://user-images.githubusercontent.com/28667591/42251390-9ea42d76-7f69-11e8-832f-d7a22e3f9f8c.png)
After I selected the OpenStack  at first step when adding a cluster,  do I  need  to select the custom button and fill something  in cluster option , or  only use the note template instead of custom option?

**Comment by rootdeep** [comment]
@alexandrem  Where is a yaml  passed from ? Is the node template on UI  the yaml input ?

**Comment by alexandrem** [comment]
@rootdeep 
In the cluster add/edit page, there's the cluster options section and there is a Edit Yaml button to toggle the yaml mode.

**Comment by rootdeep** [comment]
@alexandrem  Thanks for your patience. But I  don't find the Edit Yaml button on Rancher Server UI . The rancher server version I am using is  v2.02




![image](https://user-images.githubusercontent.com/28667591/42254472-5f80f0ba-7f79-11e8-97e0-7bb0bf685f3d.png)

As you can see from above add cluster page , I don't find a Edit Yaml button in cluster options section.

**Comment by mitchellmaler** [comment]
@rootdeep The edit yaml was added in Rancher 2.0.4. You will need to upgrade to gain access to that functionality.

**Comment by deniseschannon** [comment]
@rootdeep The openstack cloud provider is giong to get malformed in v2.0.4 but will be fixed in v2.0.5.

I've assigned @JasonvanBrackel to help give better tutorial steps on how to enable different cloud providers in the documentation.

**Comment by loganhz** [comment]
Please see the doc https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/openstack/

**Comment by patriziobassi** [comment]
Hi, i'm quite new to rancher but, with 2.2.4 single install i don't have the openstack icon to be selected as provider for a brand cluster.Was It removed?

**Comment by senk** [comment]
@patriziobassi you can enable the openstack node driver via tools -> drivers -> node drivers -> openstack

**Comment by patriziobassi** [comment]
found it, thanks. i could deploy some machines but i'm failing with userdata (i need to inject proxy parameters). infact it looks like docker-machine needs a local file, which means i need to login the rancher container (i'm using single standalone install), put a file and feed the template with absolute path. Problem is that
a) rancher complains about no such file/directory. where does it expect the file? i put an absolute path "/postdeploy"
b) if i use docker-machine cmd line (bypassing rancher) it doesn't fail but it doesn't apply cloud-init userdata (i just did a runcmd: touch /file". using the same user data in Openstack Horizon guy worked perfectly.

any hint?
