### ISSUE TITLE
Upgrading a service does not work as expected

### ISSUE THREAD

**Issue by majkiee** [rancher/rancher#14361]
We just deployed a new setup of rancher V1.6.18 running behind a nginx proxy with ssl termination.
Everything is working fine except when we try to upgrade a service.
Most of the time the progress starts spinning with "upgrading" and then it switches to "upgraded" but nothing actually happend. It did not stop or start any new containers or applied any of the changes to our settings. If we manually delete the containers after we finish the upgrade, everything will start up correctly with the new version and settings.

I checked the logs on the rancher server and can't see anything when upgrading a stack.

The weird thing is that sometimes it upgrades just fine and sometimes it just upgrades one of the containers and the rest when you press finish upgrade.

Our database is hosted on AWS but the server is running on a different host, could timeouts or delays to the database cause issues like this?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.18` Cattle: `v0.183.52` UI: `v1.6.43` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by majkiee** [comment]
It also seems to work 70% of the time in chrome but safari will always just change status to upgraded without doing anything

**Comment by superseb** [comment]
Can you provide steps to reproduce, what stack definition and what steps are you taking? Does it happen for all stacks or just some? Since when did it start happening?

**Comment by balleddog** [comment]
We have experienced this issue couple times too. =
One way to reproduce: If you try to delete containers several times during a service upgrade, the service will end up with state **Upgraded** but it actually did not. A workaround from us is to click finish upgrade button and the service would continue its journey to real "upgraded" state

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
