### ISSUE TITLE
Service for NodePort is not created or updated

### ISSUE THREAD

**Issue by dnauck** [rancher/rancher#14366]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.3
rancher/agent or rancher/rancher-agent: 2.0.3

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.3-rancher2-1

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

custom cluster/rke on ubuntu

**Steps to Reproduce:**

add a new workload, e.g. `atmoz/sftp` and create a new port mapping for port 22:
Type: NodePort
Protocol: TCP
Listening Port: 22001

**Results:**

The required service is not created by rancher.

You can also create a NodePort for port 22 with a random listening port, then rancher creates a service. Then change the NodePort to 22001 on the workload. Result is that rancher does not update the service.

I would expect that i can use every high port as node port, when specified by hand and not only the port range 30000/32767 that is used for random ports.

**Comment by vincent99** [comment]
NodePorts can only be in the range defined for the cluster (which defaults to 30000-32767).  You can change the range on the cluster if you want, and you can choose any available port within that range instead or random.  But you can't pick a number outside of the range and use that as a NodePort.

**Comment by vincent99** [comment]
The UI should prevent you from putting in an out-of-range port, but it needs to [know what the range is first](https://github.com/rancher/rancher/issues/12422#issuecomment-402310902).

**Comment by loganhz** [comment]
This issue will be fixed with https://github.com/rancher/rancher/issues/15105
