### ISSUE TITLE
Service Discovery not being populated until refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14367]
**Rancher versions:** 2.0 master 7/3

**Steps to Reproduce:**
1.  Add a workload
2. Go to service discovery and wait

**Results:**  Service Discovery for workload won't show up until I refresh

**Comment by dnauck** [comment]
This happens also for the namespace view; e.g. if you delete a namespace -> its shown until you hit F5/Reload in the browser.

**Comment by loganhz** [comment]
Server sends the data with type `service` which should be `dnsRecord`. We need to fix it in backend.

**Comment by loganhz** [comment]
Added it to v2.0.5. Please move to v2.0.6 if it is not a critical issue.

**Comment by alena1108** [comment]
@orangedeng there was a fix to resolve this issue https://github.com/rancher/rancher/pull/13770, and it was validated back then. Could you check whether it regressed, or something else is going on

**Comment by orangedeng** [comment]
I can not reproduce this issue with 7/11 master. The service for workload will be automatically created without refresh.

**Comment by alena1108** [comment]
@orangedeng i couldn't either, but the issue was seen on QA setups multiple times (I saw it myself on @sangeethah setup). Could you coordinate with @loganhz to get the details of his setup, and look at it

**Comment by loganhz** [comment]
@orangedeng 

Please try:

1. docker run -d -p 80:80 -p 443:443 rancher/rancher:master --add-local=true
2. create a workload
3. go to service discovery tab

**Comment by orangedeng** [comment]
Tested in my local setup with master build, still can't.

**Comment by loganhz** [comment]
I can not reproduce it with master 07/18.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Same steps and still can reproduce.  If I create a workload, when I go to the Service Discovery tab it doesn't show up until I refresh browser.

This is not fixed.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/8
Verified fixed
