### ISSUE TITLE
Rancher shows weird red error box in UI with no actual message while starting

### ISSUE THREAD

**Issue by JanoschDeurer** [rancher/rancher#14360]
**Rancher versions:**
rancher/rancher:latest

**Docker version:**
Containers: 65
 Running: 23
 Paused: 0
 Stopped: 42
Images: 20
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-22-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.9GiB
Name: rancher-master-test
ID: QXXI:LRXT:VB3S:RKND:GMVM:EJT3:2XZX:CCYF:HMVU:534E:6VVY:6A2X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

4.15.0-22-generic

**Type/provider of hosts:**
Hetzner

**Setup details:**
Single node rancher
internal DB

**Environment Template:**
Kubernetes

**Steps to Reproduce:**
unknown

**Results:**
Rancher needed a long time to start, and while doing so it showed a weird red error box in UI with no actual message while starting:

![rancher-screenshot](https://user-images.githubusercontent.com/10299326/42219600-c24ae4b0-7ecc-11e8-8c23-1170e7b47fed.png)

While it eventually worked, this was rather confusing and therefore it would be a nice addition if it could show a better error in that situation.

**Comment by superseb** [comment]
Can you supply any logging that shows what was taking so long?

Keep in mind that we recommend at least 4GB, and 2 vCPUs.

**Comment by JonasT** [comment]
Couldn't it still show a useful error message like "Sorry, still booting" or something, no matter how much time it takes to boot up?

**Comment by superseb** [comment]
Yes, that's why I'm requesting logs to make sure we fix it in the right way. I can't reproduce it atm.

**Comment by JanoschDeurer** [comment]
I think it is pretty probable that we run into this because we had not enough RAM. I'll attach the log file anyway.

[log.zip](https://github.com/rancher/rancher/files/2159840/log.zip)

**Comment by vincent99** [comment]
That is a screen that mostly exists only for dev, because when running the UI locally against a remote server it may be unreachable.  That is not "supposed" to happen in a normal install when the server is also the one serving up the UI, but it's possible if the server  managed to return the static UI files but can't manage toround to the API call to get auth config.

**Comment by loganhz** [comment]
A user met the same issue yesterday. Please try to disable the cache in your browser. 

For chrome, you can find it via `dev tools` => `network` => `Disable cache`

![image](https://user-images.githubusercontent.com/21168270/43816708-b5d28e88-9b08-11e8-96a8-ee9d2e2ba128.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/8
Verified fixed
