### ISSUE TITLE
Lose project level secret in volume information when edit workload

### ISSUE THREAD

**Issue by dnauck** [rancher/rancher#14368]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.3
rancher/agent or rancher/rancher-agent: 2.0.3

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.3-rancher2-1

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

custom cluster/rke on ubuntu

**Steps to Reproduce:**

Everything via rancher-ui:

1.) create a new namespace, e.g. `secret-test`
2.) create a new secret, e.g. `test-secret` with some key/values (only for the test namespace)
3.) create a new workload as stateful set with 1 replica, e.g. `secret-test-app` with docker image `busybox`
4.) create a sidecar for `secret-test-app` as standard container with docker image `busybox`; add a volume ("Use a secret") with name `test-secret-volume` and the previously created secret `test-secret` to the sidecar and mount it to `/some/path``

**Results:**

Old pods are deleted, but now new are created.
The rancher-ui is missing to link the created volume with the secret.
Edit the sidecar does not show any volume; also adding it again has the same result.

Resulting YAML:
```
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-abcdef
  creationTimestamp: 2018-07-03T19:14:44Z
  generation: 2
  labels:
    workload.user.cattle.io/workloadselector: statefulSet-secret-test-secret-test-app
  name: secret-test-app
  namespace: secret-test
  resourceVersion: "6513049"
  selfLink: /apis/apps/v1beta2/namespaces/secret-test/statefulsets/secret-test-app
  uid: 5827a467-7ef5-11e8-be8b-005056a739a9
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-secret-test-secret-test-app
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-secret-test-secret-test-app
    spec:
      affinity: {}
      containers:
      - image: busybox
        imagePullPolicy: Always
        name: secret-test-app
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      - image: busybox
        imagePullPolicy: Always
        name: secret-test-app-sidecar
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /some/path
          name: test-secret-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentRevision: secret-test-app-6b595f7dd8
  observedGeneration: 2
  replicas: 1
  updateRevision: secret-test-app-7bd7fc694c
```

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/3
Basically - sidecar is not automatically filling in proper information for volume.  So it gets lost if you save.  Steps to reproduce:
1.  create a secret
2.  Add a workload & in Volumes Add a secret & select secret
3.  Add a sidecar to workload
4.  Expand Volume section

Result - Secret is missing from drop-down
![image](https://user-images.githubusercontent.com/11514927/42247277-ee90b7a4-7ed4-11e8-93ba-7c751adf1727.png)

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/42254837-51312924-7f7b-11e8-9f69-c63c4347cf35.png)
![image](https://user-images.githubusercontent.com/21168270/42254903-a4ab87a2-7f7b-11e8-855a-85e9e2fc4a3a.png)

UI sends the project level secret `project-zzw8b:mysecret` to backend. But backend populated it as `default:mysecret`. 

The `default:mysecret` doesn't exist at all. So UI can not find it in edit page.

**Comment by cjellick** [comment]
https://github.com/rancher/ui/pull/2143

**Comment by soumyalj** [comment]
Tested with v2.0.7-rc5. 
1. create a secret
2. Add a workload & in Volumes Add a secret & select secret
3. Add a sidecar to workload
Expand Volume section. The volume section showed the secret as expected.
<img width="1147" alt="screen shot 2018-08-10 at 11 15 15 am" src="https://user-images.githubusercontent.com/18536626/43974220-b6ef8ef6-9c8e-11e8-9491-d14084a004c6.png">

After the sidecar was added, editing the sidecar showed the  secret in the volume section.
The volume mount had the secret added correctly .
