### ISSUE TITLE
hosts are not listed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1437]
Server Version - v0.27.0-rc1

Installed rancher server.
Installed 3 hosts.

Hosts dont show up in the "Infrastructure/hosts" view.

DB shows all 3 hosts in active state.

**Comment by vincent99** [comment]
An empty host breaks the host list screen..

**Comment by tfiduccia** [comment]
v0.27.0-rc1 (ui latest v0.32.0)
Verified fixed
