### ISSUE TITLE
Domain use the CloudFlare CDN to ingress

### ISSUE THREAD

**Issue by alanxie1129** [rancher/rancher#14377]
Rancher versions:
2.02
rancher/server or rancher/rancher:
rancher/server
rancher/agent or rancher/rancher-agent:
rancher/rancher-agent
Infrastructure Stack versions:
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

Docker version: (docker version,docker info preferred)
18.03.1-ce
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
centos7 3.10.0-862.3.3.el7.x86_64
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
DO
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)

Steps to Reproduce:
1.the Domain use the CloudFlare CDN
the ingress can not work
522 (Origin Connection Time-out)

**Comment by TehTotalPwnage** [comment]
Hmm, Cloudflare shouldn't be interfering with Ingress, considering that Ingress just listens on the normal HTTP and HTTPS ports.

Does Rancher and the Ingress work without CloudFlare? Is the `rancher/rancher` container and the `rancher/rancher-agent` container running on the same system? What does your Ingress configuration look like?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
