### ISSUE TITLE
Can't get Resource Group tooltip go away for Azure KS

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14379]
**Rancher versions:** 2.0 master 7/3

**Steps to Reproduce:**
1.  Go through the auth step in Create Cluster - Azure KS
2.  Click on the tool tip for Resource Group
3.  Now click anywhere else

**Results:**  Tooltip won't go away

**Comment by westlywright** [comment]
@tfiduccia can you retest on latest? I followed your directions but I see the tooltip working correctly. If you still see it happening I may need more info. The only way I can think that this would happen is if there was a JS error on the page, which I don't see either.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/9
Verified fixed
