### ISSUE TITLE
Rebooted worker node having non persisted `/etc` never comes back online

### ISSUE THREAD

**Issue by Murf** [rancher/rancher#14376]
Rancher versions: 2.0 master July 2
vCenter 6.7
ESXi 6.7

Setup details: single node rancher run as docker container

**Steps to Reproduce:**

1) Create a cluster with the vSphere template, edit yaml and and add CloudProvider details for vCenter
2) Create a Node Template with 2GB and 2 vCPU
3) Add 1 etcd, 1 control, 3 workers
4) wait for cluster to be online
5) reboot a worker node

**Results:**

Worker node never comes back online in Rancher cluster

**Comment by Murf** [comment]
rancherOS per the template.



[rancher@workernode2 ~]$ docker ps -a
CONTAINER ID        IMAGE                                                                                                      COMMAND                  CREATED             STATUS                          PORTS               NAMES
fd1d19d6ad0b        rancher/coreos-flannel-cni@sha256:3cf93562b936004cbe13ed7d22d1b13a273ac2b5092f87264eb77ac9c009e47f         "/install-cni.sh"        44 hours ago        Exited (255) 44 hours ago                           k8s_install-cni_kube-flannel-7r96x_kube-system_0035ac70-7eb0-11e8-943e-005056bbcda1_0
c84642925258        rancher/nginx-ingress-controller@sha256:58944b175505087dfa7afc444577d1933fd3bf1f1f668ef57b9eaaa8b36f59ce   "/usr/bin/dumb-ini..."   45 hours ago        Exited (255) 44 hours ago                           k8s_nginx-ingress-controller_nginx-ingress-controller-6psf6_ingress-nginx_002c8480-7eb0-11e8-943e-005056bbcda1_0
fcd6d269844b        rancher/coreos-flannel@sha256:93952a105b4576e8f09ab8c4e00483131b862c24180b0b7d342fb360bbe44f3d             "/opt/bin/flanneld..."   45 hours ago        Exited (255) 44 hours ago                           k8s_kube-flannel_kube-flannel-7r96x_kube-system_0035ac70-7eb0-11e8-943e-005056bbcda1_0
d5473e613685        5477f1a509b9                                                                                               "run.sh"                 45 hours ago        Exited (2) 44 hours ago                             k8s_agent_cattle-node-agent-8r5mj_cattle-system_002e2e8a-7eb0-11e8-943e-005056bbcda1_0
6af61f4445b9        51eebeddb033                                                                                               "sh -c 'sysctl -w ..."   45 hours ago        Exited (0) 45 hours ago                             k8s_sysctl_nginx-ingress-controller-6psf6_ingress-nginx_002c8480-7eb0-11e8-943e-005056bbcda1_0
042ff5e6d778        rancher/pause-amd64:3.1                                                                                    "/pause"                 45 hours ago        Exited (0) 44 hours ago                             k8s_POD_kube-flannel-7r96x_kube-system_0035ac70-7eb0-11e8-943e-005056bbcda1_0
0a653551912e        rancher/pause-amd64:3.1                                                                                    "/pause"                 45 hours ago        Exited (0) 44 hours ago                             k8s_POD_cattle-node-agent-8r5mj_cattle-system_002e2e8a-7eb0-11e8-943e-005056bbcda1_0
a8f0b27a8d57        rancher/pause-amd64:3.1                                                                                    "/pause"                 45 hours ago        Exited (0) 44 hours ago                             k8s_POD_nginx-ingress-controller-6psf6_ingress-nginx_002c8480-7eb0-11e8-943e-005056bbcda1_0
cc696c0d0d3e        rancher/hyperkube:v1.10.5-rancher1                                                                         "/opt/rke/entrypoi..."   45 hours ago        Restarting (255) 15 hours ago                       kube-proxy
f87335b4b343        rancher/rke-tools:v0.1.10                                                                                  "nginx-proxy CP_HO..."   45 hours ago        Up 44 hours                                         nginx-proxy
b3b4ffef8e60        rancher/hyperkube:v1.10.5-rancher1                                                                         "/opt/rke/entrypoi..."   45 hours ago        Exited (255) 44 hours ago                           kubelet
47f456fe7250        rancher/rancher-agent:master                                                                               "run.sh -- share-r..."   45 hours ago        Exited (137) 44 hours ago                           share-mnt
e580828f566a        rancher/rke-tools:v0.1.10                                                                                  "/bin/bash"              45 hours ago        Exited (0) 44 hours ago                             service-sidekick




[rancher@workernode2 ~]$ docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
rancher/rancher-agent              master              5477f1a509b9        2 days ago          296 MB
rancher/hyperkube                  v1.10.5-rancher1    ec897787d958        5 days ago          976 MB
rancher/rke-tools                  v0.1.10             51eebeddb033        2 weeks ago         124 MB
rancher/nginx-ingress-controller   0.10.2-rancher3     66e10c24a484        2 months ago        203 MB
rancher/pause-amd64                3.1                 da86e6ba6ca1        6 months ago        742 kB
rancher/coreos-flannel             v0.9.1              2b736d06ca4c        7 months ago        51.3 MB
rancher/coreos-flannel-cni         v0.2.0              7252edf978c0        10 months ago       49.8 MB

**Comment by bmdepesa** [comment]
I was able to reproduce this with an ec2 cluster running RancherOS 1.4 & Docker 17.0.3. 

Restarted worker node, and it failed to re-register. 

kubelet logs: 
```
E0705 18:26:16.882397    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23"
E0705 18:26:16.882528    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99"
I0705 18:26:20.407451    2474 kube_docker_client.go:345] Pulling image "sangeetha/testclient:latest": "a3ed95caeb02: Extracting [==================================================>]      32B/32B"
I0705 18:26:23.723552    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:26:23.723614    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:26:23.723832    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:26:24.950798    2474 kubelet_node_status.go:437] Using node IP: "172.31.0.65"
E0705 18:26:26.898990    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23"
E0705 18:26:26.899022    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99"
I0705 18:26:27.630273    2474 kube_docker_client.go:348] Stop pulling image "sangeetha/testclient:latest": "Status: Downloaded newer image for sangeetha/testclient:latest"
I0705 18:26:27.942668    2474 kubelet.go:1906] SyncLoop (PLEG): "testclient-p8mvt_default(e241dcda-8080-11e8-806e-0268a95106de)", event: &pleg.PodLifecycleEvent{ID:"e241dcda-8080-11e8-806e-0268a95106de", Type:"ContainerStarted", Data:"499987cd82a9bb7170ad0fc43ad8630cf011c4568e65596ffe8d8159fc85d84a"}
I0705 18:26:34.986890    2474 kubelet_node_status.go:437] Using node IP: "172.31.0.65"
E0705 18:26:36.913320    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23"
E0705 18:26:36.913351    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99"
I0705 18:26:44.996090    2474 kubelet_node_status.go:437] Using node IP: "172.31.0.65"
E0705 18:26:46.929032    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23"
E0705 18:26:46.929064    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99"
I0705 18:26:52.702783    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:26:52.702883    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:26:52.703314    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:26:55.007921    2474 kubelet_node_status.go:437] Using node IP: "172.31.0.65"
E0705 18:26:56.944344    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23"
E0705 18:26:56.944375    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99"
I0705 18:27:00.009925    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:00.010006    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:00.010230    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:05.017379    2474 kubelet_node_status.go:437] Using node IP: "172.31.0.65"
E0705 18:27:06.958825    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23"
E0705 18:27:06.958860    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99"
I0705 18:27:10.018875    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:10.019036    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:10.019168    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:15.019240    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:15.019339    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:15.019356    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0705 18:27:15.043522    2474 kubelet_node_status.go:437] Using node IP: "172.31.0.65"
E0705 18:27:16.972263    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99/docker/66d117d256e30613c1f0db97902b6f69c273f28b86cd524b1a3ce43760b3db23"
E0705 18:27:16.972297    2474 summary.go:102] Failed to get system container stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get cgroup stats for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": failed to get container info for "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99": unknown container "/docker/14d60d599ae12bb7a76c36064fcdd1ddb358f3cd5db88aa7ac72b9d23720ba99"
I0705 18:27:20.020878    2474 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
```

**Comment by galal-hussein** [comment]
After checking the issue i think Rancher ignore the prefix path for `/etc/kubernetes`  for some reason, this only happens with the worker nodes that are being deployed using the rancher agent and not rke, when inspecting the kubelet component:
```
            {
                "Type": "bind",
                "Source": "/etc/kubernetes",
                "Destination": "/etc/kubernetes",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
.........
            {
                "Type": "bind",
                "Source": "/opt/rke/etc/ceph",
                "Destination": "/etc/ceph",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
```
you can see that prefix path is being used for /etc/ceph but not for /etc/kubernetes, also i can see the certificates being deployed in /etc/kubernetes probably for the same reason:
```
[root@hgalal-worker1 ~]# ls /etc/kubernetes/ssl/
certs                    kube-node-key.pem        kube-proxy-key.pem       kubecfg-kube-node.yaml
kube-ca.pem              kube-node.pem            kube-proxy.pem           kubecfg-kube-proxy.yaml
```

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/6

Worker node was able to provision. 
Rebooted ec2 instance and the node went to unavailable (kubelet stopped posting status).
After a few minutes the node was able to reconnect to Rancher server. 
Deployed a workload and saw it scheduled to the worker node.

**Comment by galal-hussein** [comment]
A problem will happen with ROS worker nodes when Rancher 2.0.4 upgraded to 2.0.5, kubelet and kubeproxy bind mounts will be updated to point to /opt/rke/etc/kubernetes/ instead of /etc/kubernetes where certificates exist, and this will cause both services to break, as a workaround to this problem the following can be done on worker nodes:
```
mkdir -p /opt/rke/etc/kubernetes
cp -r /etc/kubernetes/* /opt/rke/etc/kubernetes/
docker restart kubelet
docker restart kube-proxy
```

**Comment by dhirenshumsher** [comment]
still happening, fresh rancher 2.1.1 single node installation

` [INFO] Handling backend connection request [c-mtsv7:m-4e85d16a18cc]
[INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF`

I guess it was triggered when i changed/added label in the node.

**Comment by jralmaraz** [comment]
Same happens to me when I restart a dev rancher cluster overnight. I need to delete and re-create only the worker nodes.

**Comment by renperez** [comment]
we are having the same issue when using ALB. 
time="2019-04-02T04:28:31Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-04-02T04:28:31Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

04/02 04:19:18 [INFO] Stopping cluster agent for c-rfvfd
2019/04/02 04:19:18 [INFO] Shutting down NamespaceController controller
2019/04/02 04:19:18 [INFO] Shutting down RoleController controller
2019/04/02 04:19:18 [INFO] Shutting down ClusterRoleBindingController controller
2019/04/02 04:19:18 [INFO] Shutting down ClusterRoleController controller
2019/04/02 04:19:18 [INFO] Shutting down ServiceController controller
2019/04/02 04:19:18 [INFO] Shutting down RoleBindingController controller
2019/04/02 04:19:46 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/04/02 04:21:03 [INFO] Handling backend connection request [c-mmwl5]

**Comment by huegelc** [comment]
Same issue here when upgrading fron 2.2.4 to 2.2.8

**Comment by HansAarneLiblik** [comment]
This issue is still present with 2.5.7

**Comment by bmdepesa** [comment]
@HansAarneLiblik can you provide some details about your environment and what steps were taken when this occurred?

**Comment by HansAarneLiblik** [comment]
I have a VM that I'm using as a node for my cluster in vCenter that has `/opt/local` as persistent storage.

I configured my cluster to use `/opt/local/docker` as Docker Root Dir (instead of `/var/lib/docker`)

a) I also added `prefix_root: /opt/local/rke` to YAML configuration when creating cluster (See image below)
b) I changed rancher-agent docker command (`sudo docker run [...] -v /opt/local/rke/etc/kubernetes:/etc/kubernetes [...]`)

When I start my cluster everything works. When I redeploy it, nodes are unable to start

```
> docker logs kubelet
> [...]
F0405 13:30:32.138498   12121 server.go:257] unable to load client CA file /etc/kubernetes/ssl/kube-ca.pem: open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000126001, 0xc00065e1c0, 0xac, 0x1b2)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x70ea520, 0xc000000003, 0x0, 0x0, 0xc000b46690, 0x6f551a6, 0x9, 0x101, 0x411b00)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x70ea520, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc00064ad40, 0x1, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).print(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:714
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatal(...)
[...]
```

![image](https://user-images.githubusercontent.com/5418540/113659827-8df2b680-96ab-11eb-9ed9-fd30e247ec79.png)
