### ISSUE TITLE
Dynamic environment variables

### ISSUE THREAD

**Issue by teodor-pripoae** [rancher/rancher#1438]
Hi,

I'm trying to setup an etcd cluster managed by rancher on each rancher-os server. The problem is that etcd needs a variable (ETCD_NAME) to be different on each server.

Currently if I deploy etcd instances on each node using the option to run the service on every node in the cluster, I can setup only static environment variables.

How can I set for example: 

```yaml
environment:
  ETCD_NAME=$$hostname
```

**Comment by alena1108** [comment]
@teodor-pripoae we are currently working on the feature that will enable support for that:

https://github.com/rancher/rancher/issues/1271

And here is more doc: https://github.com/sonchang/cattle/wiki/Rancher-Packaging-and-Catalog

**Comment by alena1108** [comment]
Closing the ticket as we are going to keep track of the metadata feature in its own ticket mentioned above.
