### ISSUE TITLE
Check if Edit Cluster options are valid to change in a cluster

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14386]
Edit Cluster allows to change the options visible in the UI and the `Edit as YAML`  feature but we need to validate that only the options that can be successfully changed are visible/can be used.

- Changing network provider
- Changing/disabling ingress controller
- Adding/removing k8s cloud provider config

**Comment by develar** [comment]
> You can manually remove the ingress using kubectl delete ds,deploy,pod,svc -n ingress-nginx --all and kubectl delete ns ingress-nginx.

Is it not better to implement this logic? Or it will be done sometime later as part UI for this task? And for now just help users to understand that some options cannot be edited after creation.

**Comment by superseb** [comment]
That is exactly where this issue is opened for.

**Comment by vincent99** [comment]
We can disable editing the network provider, and the cloud config (but I think editing that is supposed to actually work).  There is no special control for ingress.

For Edit as YAML or the API in general the backend should really be doing validation that you can't change the parts we don't want to let you edit.  The UI is not an enforcement mechanism, and I don't want to parse and compare YAML to decide if you've changed something in the UI through the YAML editor.

**Comment by develar** [comment]
> The UI is not an enforcement mechanism

In case of "raw editing of YAML" yes. Anyway for me the only reason why raw editing is required, it is lack of this functionality in UI.

> backend should really be doing validation

as in case of "Import YAML" for cluster (kubectl apply).

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Verified fixed
