### ISSUE TITLE
vSphere doesn't work

### ISSUE THREAD

**Issue by NataShare** [rancher/rancher#14381]
*Describe your issue here*

Error with pre-create check: "Post https://172.16.23.230:443/sdk: dial tcp 172.16.23.230:443: getsockopt: connection refused"; Timeout waiting for ssh key
--

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.edit`|

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
