### ISSUE TITLE
Assign Namespace to a Rancher project

### ISSUE THREAD

**Issue by chucky2305** [rancher/rancher#14382]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.2

**Steps to Reproduce:**
When deploying an application to rancher, we want to assign it to a project. How can this be done? I could not find any documentation on this yet. I hope it can be done using a certain kubernetes labels syntax.

Kind regards
Chucky

**Comment by superseb** [comment]
Best way to interact with your cluster is to use the Rancher CLI, you can easily create projects and namespaces with it and associate a namespace with a project.

If this doesn't help I need a bit more info on your use case.

**Comment by chucky2305** [comment]
Hello @superseb. Thanks for your quick answer. 
Asking the same question in the fabulous rancher slack channel i got the solution. Hopefully i can help other with this:

By adding an **ANNOTATION** (not Label) to your namespace like so, rancher will put it in the desired project. Here you can see a extract of my helm chart for the namespace. The last two lines are important here:

``
---
# Create Namespace for Feature
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
annotations: 
   field.cattle.io/projectId: c-sqc8w:project-2bmmx
``

with `kubectl` you can do the same:

`kubectl annotate namespace mynamespace field.cattle.io/projectId=c-sqc8w:project-2bmmx`

This issue can be closed i guess.

**Comment by papanito** [comment]
@chucky2305 you say 
> ... extract of my helm chart for the namespace
does this mean you have a dedicated helm-chart for namespaces or the yaml file is part of your helm-chart for your app?

**Comment by papanito** [comment]
Found the problem: https://github.com/helm/helm/issues/3179

**Comment by oocx** [comment]
This should be in the official rancher documentation about projects and namespaces (https://rancher.com/docs/rancher/v2.x/en/project-admin/). The documentation often only shows how something can be done via the UI. I don't want people to manually change configuration via the UI. All config should be in source control.

@chucky2305 Thanks for sharing your solution here!

**Comment by gopakumarce** [comment]
Does rancher recommend configuring cluster via the rancher clis or can we just directly use kubectl apply -f ? Is there a strong recommendation on racher for one Vs the other ?

**Comment by creiche** [comment]
I also would like to know the proper way to manage projects via kubectl or rancher CLI.  

- Creating Projects via YAML or CLI
- Creating and assigning namespaces via YAML or CLI
- Deleting Projects via YAML or CLI

**Comment by nce** [comment]
Has anyone figured out a way to do this by now?

**Comment by lachnerd** [comment]
i would be interested too...

Right now with Rancher 2.5.7 i am getting this:
```
ValidationError(Namespace): unknown field "annotations" in io.k8s.api.core.v1.Namespace;
```

**Comment by lachnerd** [comment]
> i would be interested too...
> 
> Right now with Rancher 2.5.7 i am getting this:
> 
> ```
> ValidationError(Namespace): unknown field "annotations" in io.k8s.api.core.v1.Namespace;
> ```

ah ok got wrong intendation, this works:

```
# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: <namespace>
  annotations: 
    field.cattle.io/projectId: <project-id>
```
