### ISSUE TITLE
kubernetes ingress controller not updating node ip's

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#14380]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.18

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.3-rancher3

**Environment details**
1. large number of ingresses aggregated on specific hosts

**Steps to Reproduce:**
1. deploy ingress
2. query ingress for details on node ip's

**Results:**
Ingress never displays node ip's even though ingress containers are up.

**Comment by aemneina** [comment]
**Workaround**
- restarting the ingress controller gets the node ip's populated again.

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.6.19-rc2 and K8s version - v1.10.5-rancher1-1 using rancher-ingress-controller - rancher/lb-service-rancher:v0.9.4.

Created 100 ingress in 1 host. 
All the ingress entries have ipaddress injected.
Created 100 more ingress in same host. 
All the ingress entries have ipaddress injected as expected.
