### ISSUE TITLE
services created over rancher are corrupt.

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#14388]
Rancher creates the services automatically but somehow this wasn't the case. When creating one over the Rancher Web it didn't create correctly.

I had to copy one from a working services and change it to my openldap.

kind: Service
metadata:
  name: openldap-nodeport
  namespace: openldap
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: openldap
    uid: 39b34128-7f6c-11e8-8652-005056816ffc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 389tcp01
    nodePort: 30389
    port: 389
    protocol: TCP
    targetPort: 389
  selector:
    workload.user.cattle.io/workloadselector: deployment-openldap-openldap
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`` `admin`|
|Route|`ingresses.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup, please? So we can use it to reproduce the issue.
 (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Thanks

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
