### ISSUE TITLE
The namespace of the service displays the wrong name

### ISSUE THREAD

**Issue by wenjiasen** [rancher/rancher#14396]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/16320597/42310367-d462e84e-806d-11e8-910e-458f46d22d6f.png)

![image](https://user-images.githubusercontent.com/16320597/42310516-35f267e2-806e-11e8-9ce7-3e6acd73f1a7.png)

# Run kubectl commands inside here
# e.g. kubectl get all
> kubectl --namespace test-space get services
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
report-center   ClusterIP   10.43.185.232   <none>        80/TCP    1h
> kubectl --namespace cattle-pipeline  get services
NAME      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)              AGE
jenkins   ClusterIP   10.43.16.165   <none>        8080/TCP,50000/TCP   7d
>
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by superseb** [comment]
Thanks.

Fixed in https://github.com/rancher/rancher/issues/14332, will be in the next release.
