### ISSUE TITLE
Rancher ui-index and custom UI assets

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#14392]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.5-rc2

I'm not sure to understand how the `ui-index` setting works and how to host the UI asset files outside of the Rancher server build.

I read the documentation in the Rancher UI project and tried to have the custom assets served with a `/latest2` URI path from the same base server url, which was working, then changed the `ui-index` value in the Rancher server but it wouldn't do anything.

The UI assets were still being served by the Rancher server and not the remote path when loading my `https://<rancher url>/` .

Perhaps the feature is broken or I don't have the correct workflow.

Bundling the new assets in a custom Rancher server build works.

**Comment by vincent99** [comment]
I don't think support was ever added in the server to actually do anything with the setting.

**Comment by alexandrem** [comment]
I suppose it wouldn't be that hard to implement.

Would need to have some design discussion about the expected behavior for this feature.

**Comment by loganhz** [comment]
There is a backend check if the rancher version starts with `v`, the `ui-index` will be ignored.

The workaround is setting `CATTLE_SERVER_VERSION`

```
docker run -d -e CATTLE_SERVER_VERSION=dev -p 80:80 -p 443:443 rancher/rancher:v2.0.0
```

**Comment by cjellick** [comment]
@orangedeng @loganhz can this be sent to test now? no additional changes needed, right?

**Comment by loganhz** [comment]
Yes, please assign it to the QA team

**Comment by cjellick** [comment]
Had to revert the fix. Sending back to dev

**Comment by cjellick** [comment]
when verifying this, you must test that on an RC, the javascript is served up from a local file inside rancher server and not the CDN. That is what broke in alpha

**Comment by loganhz** [comment]
I will validate it once we have a rc build

**Comment by cjellick** [comment]
@loganhz to validate

**Comment by loganhz** [comment]
Validated in v2.2.0-rc2

Case 1:

1. Start rancher/rancher:v2.2.0-rc2
2. Validate it is using the UI assets inside rancher server

Case 2:

1. Start rancher/rancher:v2.2.0-rc2
2. Edit ui-index and set it to `https://releases.rancher.com/ui/latest2/index.html`
3. Validate it is using the UI assets from the cdn

Case 3:

1. Start rancher/rancher:v2.2.0-rc2
2. Edit ui-index and set it to `https://releases.rancher.com/ui/latest2/index.html`
3. Validate it is using the UI assets from the cdn
4. Edit ui-index to local
5. Validate it is using the UI assets inside rancher server

Case 4:

1. Start rancher/rancher:v2.2.0-rc2
2. Edit ui-index and set it to `https://releases.rancher.com/ui/latest2/index.html`
3. Validate it is using the UI assets from the cdn
4. Restart rancher server
5. Validate it is using the UI assets from the cdn

Case 5:

1. Start rancher/rancher:v2.1.6
2. Upgrade it to rancher/rancher:v2.2.0-rc2
3. Validate it is using the UI assets inside rancher server
