### ISSUE TITLE
Parameters binding and templates of Rancher Stack?

### ISSUE THREAD

**Issue by peterpobe** [rancher/rancher#14395]
**Rancher versions:**
2.0

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

What is meaning of parameters **_binding_** and **_templates_** in Rancher Stack?
https://rancher.com/docs/rancher/v1.6/en/api/v2-beta/api-resources/stack/

Can you guys give me example data of Stack with templates and binding?

Thanks

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
