### ISSUE TITLE
Cannot delete Catalog App: Waiting on foregroundDeletion

### ISSUE THREAD

**Issue by azbpa** [rancher/rancher#14397]
**Issue:**
I cannot remove  a Catalog App from Rancher. 

It's status is *Removing* but nothing happens. 

When trying to request the deletion again nothing changes. 

On the details page no resources are listed and transitioning message is: *Waiting on foregroundDeletion*

**Rancher versions:**
rancher/rancher: 2.0.4
rancher/rancher-agent: 2.0.4

**Steps to Reproduce:**
1. Add a Custom Catalog: https://github.com/storageos/helm-chart.git
2. Deploy Catalog App "StorageOS" with
    - csi.enable=true
    - cluster.join=*comma separated list of nodes*
3. Wait until Catalog App is provisioned successfully
4. Delete Catalog App

**Results:**
Empty Catalog App with error message: *Waiting on foregroundDeletion*

**Comment by superseb** [comment]
We have this open for investigation: https://github.com/rancher/rancher/issues/14394, closing as duplicate.
