### ISSUE TITLE
Default project has non-confirming ID

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#14400]
The default project that is auto-created when a cluster is created has an ID that starts with "project-" instead of "p-", like all other projects.

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/16

The default project now has a prefix of `p-`, rather than `project-`

**Comment by soumyalj** [comment]
Tested with fresh install of master. Default project has id prefix set to 'p-'.
But on an upgrade from v2.0.6 to master, the prefix for default project id is still `project-`
![screen shot 2018-08-02 at 9 55 56 pm](https://user-images.githubusercontent.com/18536626/43624928-12908328-969f-11e8-8073-27bbd82f28e3.png)

![screen shot 2018-08-02 at 9 56 23 pm](https://user-images.githubusercontent.com/18536626/43624941-1da8921e-969f-11e8-8987-a6427f7c6d2e.png)

**Comment by vincent99** [comment]
The ID of an existing project is not going to be changed, this only affects the creation of a new one.

**Comment by deniseschannon** [comment]
@vincent99 is correct, on upgrade we will not be changing the IDs of the project.
