### ISSUE TITLE
When trying to enable openLDAP using ip address that does not connect to LDAP port successfully , it takes about 1 minute to report error. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14405]
**Rancher versions:v2.0.5-rc3
**Steps to Reproduce:**

Try to enable openLDAP authentication by providing a ip address that does not connect to LDAP port , like 1.1.1.1

It takes about 1 minute for connection error to be reported. 

Expected Behavior:
We should be able to report connection errors sooner than having to wait for 1 minute by making connection timeout a configurable parameter.

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/5

Validated that connection timeout works correctly for FreeIPA. v2.0.5-rc2 saw that an invalid host was taking ~1m to time out. On master, defaults to 5000ms and the error came in ~5s. Changed to 1000ms and 10000ms and saw the error being reported in those timeframes.

**Comment by adingilloRancher** [comment]
master 7/5

Tested with AD

rc-3  default timeout 
![screen shot 2018-07-05 at 1 33 22 pm](https://user-images.githubusercontent.com/38012481/42346804-a6314714-8058-11e8-989c-058c13a33723.png)

Master timeout
Left default value to 5000 ms. Changed to 10000ms second attempt. 1000ms final attempt.
![screen shot 2018-07-05 at 1 40 23 pm](https://user-images.githubusercontent.com/38012481/42346906-fc6230a8-8058-11e8-93f2-824f55c0902b.png)

**Comment by sangeethah** [comment]
Tested with rancher/rancher:master 7/5

Validated that "Server Connection Timeout" works correctly for openLDAP.  When trying to enable openLDAP using ip address that does not connect to LDAP port successfully , it takes ~ 5 secs to report error.

When "Server Connection Timeout" is set to a different value , then we see the error report after "Server Connection Timeout" is elapsed.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/5
Verified fixed
