### ISSUE TITLE
Decouple group search from authentication protocol

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#14404]
Our auth providers conflating user/group lookup with authentication. This creates a problem when the the authentication protocol does not have a built-in function for looking up users.
So for example, with SAML-based auth providers, we effectively dont support user or group searching. It would be helpful to the user if we decoupled these two so that an admin could still enable a SAML based provider, but, for example, configure an LDAP server as the place to search for users or groups.

**Comment by cjellick** [comment]
Fully decoupling might be overkill. We might just need to add explicit lookup and search configuration for saml specifically.

**Comment by cloudnautique** [comment]
Initial requirements:
- Existing SAML users can add an AD/LDAP configuration to support group search.
- New SAML users can optionally pass the AD/LDAP configuration for group searching.
- Authentication is only conducted by the SAML provider.
- If needed an administrator needs to describe how to link the SAML groups to AD/LDAP groups.
- Rancher admins and membership assignment roles should be able to search groups against the AD/LDAP configuration.

Acceptance:
- Needs to work with AD and OpenLDAP initially. 
- Users who have never before logged into Rancher via SAML should be able to access clusters and projects based on their group assignments.
- A user with a membership assignment role, should be able to assign access to a group they are not a member of.
- When entering a group into the box, search and autocomplete should be available in the text box.
- Terraform Provider needs to be able to handle the added configuration.

**Comment by cjellick** [comment]
reqs and accepatance loo good @cloudnautique. Once question:

> Terraform Provider needs to be able to handle the added configuration.

Is this your  line in the sand for engineering (Dev _and_ QA) officially taking over the Terraform Provider and fully supporting it?

cc @sangeethah @deniseschannon

**Comment by deniseschannon** [comment]
We will first work on getting Ping/OpenLDAP working before implementing other providers.

**Comment by mrajashree** [comment]
ADFS could also be good to start with since it for sure only uses AD whereas Ping supports AD and openldap both
