### ISSUE TITLE
Healthcheck is not working properly when in Upgraded state

### ISSUE THREAD

**Issue by balleddog** [rancher/rancher#14419]
**Rancher versions:**
rancher/server:v1.6.15
rancher/agent:v1.2.10

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.6
ipsec: 0.2.3
network-services: v0.2.9
scheduler: v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Aliyun ECS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher + Aliyun RDS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a multi-container service(in my case nginx) with HTTP healthcheck enabled
2. After the service became active, trigger a service upgrade, wait until status **Upgraded** and there should be equal number of running and stopped containers
3. Login to the host where one of running containers dwells and run ``docker kill -s SIGTERM/SIGKILL`` against it

**Results:**
Expected result is the terminated/killed container to be recreated
However I can do this repeatedly util all of the running containers are stopped.

And then there would be no more healthy containers of that service which obviously lead to total service unavailability.

In our production environment, the ``docker kill``  command is actually kernel OOM kill signal. We left a service **upgraded** status for about a week and leaky memory cause kernel shot our containers to death one by one.  Yes, sad story...

We suppose healthcheck service should do something in this scenario
![screen shot 2018-07-06 at 12 10 05 pm](https://user-images.githubusercontent.com/8732997/42359638-be0d863c-8115-11e8-98e0-4b09bca6c30e.png)

**Comment by balleddog** [comment]
@leodotcloud ping

**Comment by leodotcloud** [comment]
What is the state of the ipsec stack? The healthcheck DOWN events for user services are dropped if IPSec stack is one of the upgrading states.

**Comment by balleddog** [comment]
IPSec stack was definitely in active state. This issue happened in our one of the biggest environment and an upgrading IPSec stack would be disastrous

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
