### ISSUE TITLE
Azure kubernetes integration rancher 2.1

### ISSUE THREAD

**Issue by Joelgullander** [rancher/rancher#14410]
Ive just installed rancher and integrated with my azure kubernetes. When i create a nginx workspace i cant figure out how to browse to hit, if im clicking the port icon on the service it takes me to a local IP : 10.xx.xx 

Is this a known issue or can anyone guide me how to solve it?

**Comment by loganhz** [comment]
You can use https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer to expose it.
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
