### ISSUE TITLE
Service discovery records created by user are resolving to incorrect IP

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14414]
**Rancher versions:**
rancher/rancher:master 7/5

**Steps to Reproduce:**
In a cluster, create a service discovery record pointing to one of: External IP, Workload, Selector, Alias

**Results:**
The record shows a "Cluster IP" underneath, and resolves to that IP incorrectly. 

Record of type hostname appears to work correctly.
DNS records created when a workload is deployed are correct.

<img width="1450" alt="screen shot 2018-07-05 at 3 44 55 pm" src="https://user-images.githubusercontent.com/21316915/42351822-d38ebde6-806b-11e8-8f30-b9fa685c4eb4.png">

DNS record payload:
```javascript
{
  "type": "dnsRecord",
  "ipAddresses": [
    "4.4.4.4"
  ],
  "namespace": {
    "actionLinks": {},
    "annotations": {
      "cattle.io/status": "{\"Conditions\":[{\"Type\":\"InitialRolesPopulated\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2018-07-05T22:05:29Z\"}]}",
      "lifecycle.cattle.io/create.namespace-auth": "true"
    },
    "baseType": "namespace",
    "created": "2018-07-05T22:05:26Z",
    "createdTS": 1530828326000,
    "creatorId": "user-5drf6",
    "id": "test-46602",
    "labels": {
      "field.cattle.io/projectId": "p-lj2fl"
    },
    "links": {
      "remove": "https://brandon.rancher.space/v3/cluster/c-d7h54/namespaces/test-46602",
      "self": "https://brandon.rancher.space/v3/cluster/c-d7h54/namespaces/test-46602",
      "update": "https://brandon.rancher.space/v3/cluster/c-d7h54/namespaces/test-46602",
      "yaml": "https://brandon.rancher.space/v3/cluster/c-d7h54/namespaces/test-46602/yaml"
    },
    "name": "test-46602",
    "projectId": "c-d7h54:p-lj2fl",
    "state": "active",
    "transitioning": "no",
    "transitioningMessage": "",
    "type": "namespace",
    "uuid": "85c8f383-809f-11e8-a9e7-02432b19a672"
  },
  "name": "testext",
  "selector": null,
  "hostname": null,
  "targetDnsRecordIds": null,
  "targetWorkloadIds": null,
  "clusterIp": null,
  "namespaceId": "test-46602"
}
```

**Comment by vincent99** [comment]
I think there's something more to this (editing an existing record and changing its type?), just creating a external IP and resolving it seems to work fine to me and an IP entry shouldn't have a cluster IP at all.

(Also please `<json> | jq` in issues, it's hard to read 1k of json on one line)

**Comment by bmdepesa** [comment]
For me: creating a record pointing to an external IP still resolves to the cluster IP displayed: 

<img width="759" alt="screen shot 2018-07-05 at 4 18 38 pm" src="https://user-images.githubusercontent.com/21316915/42352404-2d00fcf6-806f-11e8-8314-9c5c74419fdb.png">
<img width="1470" alt="screen shot 2018-07-05 at 4 18 45 pm" src="https://user-images.githubusercontent.com/21316915/42352405-2d181a76-806f-11e8-86c9-b85204a953cf.png">

**Comment by alena1108** [comment]
The reason for the issue that ClusterIP=None (automatically injected by Rancher API for dnsRecords), is not being set on k8s side. Can't reproduce for k8s 1.8 clusters; happens for 1.10 ones. Must be something to do with the client that we use, will update the bug once figured.

**Comment by sangeethah** [comment]
Tested with latest build fro master
All existing automation runs for service Discovery succeeds.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.0.5-rc4

Service discovery records are resolving to the correct addresses.
