### ISSUE TITLE
Clicking on "start" button on the service does nothing.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1441]
Server Version - v0.27.0-rc1

Create a service.
Click on "Start" button for the service , from the Stacks list view.
Nothing happens.
Able to start the service from the "start" option in the dropdown menu.

**Comment by tfiduccia** [comment]
This is true for all services (including balancer, alias and external).

**Comment by tfiduccia** [comment]
v0.27.0-rc1 (ui latest v0.32.0)
Verified fixed
