### ISSUE TITLE
Rancher 2 - Multiple IP on one node

### ISSUE THREAD

**Issue by wizarden1** [rancher/rancher#14428]
**Rancher versions:**
rancher/rancher: 2.0.4
rancher/rancher-agent: v2.0.4

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.3

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 44
 Running: 34
 Paused: 0
 Stopped: 10
Images: 18
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.17.3-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.62GiB
Name: k8master.localdomain
ID: F4OI:3LGX:WLJN:723R:U6WC:XZ5G:2QHP:JDWT:IJPJ:3CVR:3ECX:HHDV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux 7 (Core) - 4.17.3-1.el7.elrepo.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-R VM in OVH Dedicated Server

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 Node, 1 Management Server, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
- Add multiple IP on host
- On Node only one IP visible
- On HostPort if I set - ip, base IP used

**Results:**
- working on all ip-s even if set specific
- not possible to set more than one server with specified port and different ip
- only last started server respond on that port

**Comment by nosovk** [comment]
What do you mean by saying multiple ip? You add virtual interfaces with different ip addresses to one host? Or you add additional ip to one interface? Could you post 'ip address' output?

**Comment by wizarden1** [comment]
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:00:00:f7:f2:47 brd ff:ff:ff:ff:ff:ff
    inet 178.x.x.208/32 brd 178.x.x.208 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet 178.x.x.209/32 brd 178.x.x.209 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet 178.x.x.210/32 brd 178.x.x.210 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet 178.x.x.211/32 brd 178.x.x.211 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever

**Comment by nosovk** [comment]
The same issue is https://github.com/rancher/rancher/issues/14550
it seems that hostip binding not working.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14550

**Comment by MSandro** [comment]
Is there any workaround curently? With docker I am able to access my second IP but why not with rancher??

**Comment by micw** [comment]
@MSandro I documented my workaround to make the 2nd IP usable to non-k8s services:
https://github.com/rancher/rancher/issues/14550#issuecomment-473803868
