### ISSUE TITLE
Rancher v2 - Unable to activate ELK logging on imported GKE cluster

### ISSUE THREAD

**Issue by nuxsmin** [rancher/rancher#14425]
**Rancher versions:**
Component | Version
Rancher | v2.0.2
User Interface | v2.0.48
Helm | dev
Machine | dev

rancher/rancher-agent:v2.0.2

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable): 1.9.7-gke.0

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.9.2
 Git commit:   f5ec1e2
 Built:        Thu Apr 19 11:46:43 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   f5ec1e2
 Built:        Thu Apr 19 11:46:43 2018
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

BUILD_ID=10323.75.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=58f1195f1c24ee272ffc7b913c268b781483fff1
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=65
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=65
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node / internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
 
N/A

**Steps to Reproduce:**

Activate cluster ELK logging to external Elasticsearch instance.

**Results:**

E0706 10:06:38.269537       1 generic_controller.go:204] ClusterLoggingController c-d4qlh/cl-r8qsd [cluster-logging-controller] failed with : configmaps "cluster-logging" is forbidden: unable to create new content in namespace cattle-logging because it is being terminated.

---

Thanks for your great work!! :wink:

**Comment by nuxsmin** [comment]
A side note: fluentd and log-aggregator pods were created but the latter is failing when deploying. No logs are being logged in the stackdriver logging console.

![captura_139](https://user-images.githubusercontent.com/1775774/42379819-57ed4dee-812c-11e8-8e9a-bcee9467ab48.jpg)

**Comment by cloudnautique** [comment]
@nuxsmin can you find one of the pods and do  `kubectl describe pod log-aggregator-<podid> -n cattle-logging`

**Comment by nuxsmin** [comment]
Sure..

```
Name:           log-aggregator-jwvhm
Namespace:      cattle-logging
Node:           gke-cluster-labs-default-pool-b926016f-019g/10.154.0.3
Start Time:     Fri, 06 Jul 2018 12:11:11 +0200
Labels:         controller-revision-hash=3557263256
                k8s-app=log-aggregator
                pod-template-generation=1
Annotations:    <none>
Status:         Running
IP:             10.8.0.18
Controlled By:  DaemonSet/log-aggregator
Containers:
  log-aggregator:
    Container ID:   docker://a85c229995e807748a7967faec3c9c6c6f1c89765371262cc08504cb848a7a53
    Image:          rancher/log-aggregator:v0.1.3
    Image ID:       docker-pullable://rancher/log-aggregator@sha256:ccfb330256fd9f830c32ad56970113086d2a9ce6cd8167428a587f7d0aec69b5
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec': mkdir /usr/libexec/kubernetes: read-only file system
      Exit Code:    128
      Started:      Sat, 07 Jul 2018 01:40:58 +0200
      Finished:     Sat, 07 Jul 2018 01:40:58 +0200
    Ready:          False
    Restart Count:  163
    Environment:    <none>
    Mounts:
      /flexmnt from flexvolume-driver (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from log-aggregator-token-9qb9c (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  flexvolume-driver:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    HostPathType:  
  log-aggregator-token-9qb9c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  log-aggregator-token-9qb9c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:
  Type     Reason   Age                  From                                                  Message
  ----     ------   ----                 ----                                                  -------
  Warning  BackOff  3m (x3571 over 13h)  kubelet, gke-cluster-labs-default-pool-b926016f-019g  Back-off restarting failed container
```
It seems a directory creation issue: 

`error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec': mkdir /usr/libexec/kubernetes: read-only file system`

**Comment by nuxsmin** [comment]
Do I need to create the host directory?

`@gke-cluster-labs-default-pool-b926016f-019g ~ $ ls /usr/libexec/kubernetes/kubelet-plugins/volume/exec
ls: cannot access '/usr/libexec/kubernetes/kubelet-plugins/volume/exec': No such file or directory`

**Comment by bradjones1** [comment]
Sounds similar to https://github.com/rook/rook/issues/1120, just referencing if there's anything useful there. Appears `/usr` is read-only in CoreOS?

**Comment by bradjones1** [comment]
@nuxsmin Me as well, similar setup... hadn't dug that deep but I appreciate your additional workup. Any thoughts on which direction we should go with this? I imagine it would be a rather straightforward PR, if we can community-contribute it without having to wait for Rancher.

**Comment by nuxsmin** [comment]
@bradjones1 that is the key since it points to `--volume-plugin-dir=/home/kubernetes/flexvolume`. It seems that `loggingconfig.GoogleKubernetesEngine` value hasn't been set in `etcd` so it returns the default value.

Editing the DaemonSet did the trick!

Thanks!

**Comment by nuxsmin** [comment]
Unfortunately, though the pods have been deployed successfully, it seems that something is wrong since it does not send any log to ELK. I've tried to disable then enable the ELK logging (after undeploying all the stuff up) and this message is logged in Rancher log:

`2018/07/25 11:26:18 [ERROR] error updating ns cattle-logging status: Operation cannot be fulfilled on namespaces "cattle-logging": the object has been modified; please apply your changes to the latest version and try again`

Pods are up now, though, the volume path needs to be fixed:

![captura_166](https://user-images.githubusercontent.com/1775774/43198635-a725ad1a-900f-11e8-9016-23c5b64e8f0d.jpg)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15664

For imported GKE cluster, please change it to `/home/kubernetes/flexvolume`
For imported RKE cluster, pease change it to `/var/lib/kubelet/volumeplugins`

![image](https://user-images.githubusercontent.com/21168270/46595641-f2008800-cb0b-11e8-9d23-484969f6489e.png)

**Comment by doog33k** [comment]
thanks @loganhz  , 
you made my day .
