### ISSUE TITLE
Rancher2 restart after --acme-domain cause cluster failures

### ISSUE THREAD

**Issue by Treenity** [rancher/rancher#14427]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

** Provider **
AWS EC2
Nodes : 
* 1 etcd (private)
* 1 control (public)
* 1 worker (public)

**Steps to Reproduce:**
* Install rancher-server(without acme-domain) with persistent etcd mount
* Set server-url to internal IP
* Point DNS to rancher-server
* stop and restart rancher with --acme-domain to mydomain.domain.com

**Results:**
Rancher could not communicate with nodes anymore, kubectl give me a x509 error, and cant contact cluster if i set --insecure-skip-tls-verify

**Simplified**
if i create a rancher-server with --acme-domain, and set server-url to internal IP, then pods get a certificat problem : 
`time="2018-07-06T16:03:20Z" level=error msg="Failed to connect to proxy" error="x509: cannot validate certificate for 10.0.3.27 because it doesn't contain any IP SANs"`

** Expected result: **
Get Rancher UI with LE cert.
Cluster to work as before. LE certificat have nothing to do with internal RKE communications, certs for kubernetes/RKE have to be different from the Rancher front cert when server-url is internal

**Comment by apricote** [comment]
We experienced a similar issue. During initial setup, we included the `--acme-domain` flag, but during the update process (as it was not mentioned in the docs, and honestly, we forgot) we did not include it, resulting in a broken cluster.

Also, restarting Rancher with the flag did not solve it, we had to recreate the cluster.

**Comment by loganhz** [comment]
not sure if it is related to https://github.com/rancher/rancher/issues/14731

**Comment by superseb** [comment]
Yes, this will be solved when https://github.com/rancher/rancher/issues/14731 is solved. Only part that will not be solved is setting a different server-url vs the configured `--acme-domain` as it will contain that FQDN or IP address.

As of today, it needs manual interaction to fix when something regarding server-url or certificates in front happen.
