### ISSUE TITLE
Users should be warned if adding node with non-persistent `/etc` to a custom cluster

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14437]
Kubernetes certificates are stored in `/etc/kubernetes`.

If the node OS does not have persistent storage on `/etc`, the data in `/etc` will be gone and the node can no longer join the cluster. Users should be warned and instructed to prevent this from happening.

Applicable to:
- Custom cluster (so not applicable when using node drivers/templates)
- Known Node OS having this issue: RancherOS, CoreOS, Boot2Docker

To fix:

Replace:
```
-v /etc/kubernetes:/etc/kubernetes
```
With:
RancherOS / CoreOS
```
-v /opt/rke/etc/kubernetes:/etc/kubernetes
```
Boot2Docker
```
-v /mnt/sda1/rke:/etc/kubernetes
```

Follow up on https://github.com/rancher/rancher/issues/14376

**Comment by StrongMonkey** [comment]
This should be closed as we design `/etc/kubernetes` to be an ephemeral location and every agent restart will write certs to it. It should restart without no problem even with `/etc/kubernetes` by adding this [fix](https://github.com/rancher/rancher/pull/14486)
