### ISSUE TITLE
Rancher UI • Spelling error "namesapce" instead of "namespace" in workoad

### ISSUE THREAD

**Issue by percenuage** [rancher/rancher#14433]
Spelling error "namesapce" instead of "namespace" in workoad management (v2.0.4)

![rancher-ui](https://user-images.githubusercontent.com/6691104/42394285-e3c14d8e-8159-11e8-84cc-c6c46d6e7dfc.PNG)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`workload`|

**Comment by superseb** [comment]
Thanks for reporting, this should be fixed in the next version.

https://github.com/rancher/ui/pull/2020
