### ISSUE TITLE
AD: Remove the retrieval of multiple user search attributes during login

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#14438]
During AD login, the user attributes that the query asks for, include all of those provided by default in UserSearchField: `sAMAccountName|sn|givenName`.
We don't need all these attributes to be fetched during login, and can rely on the UserLoginAttribute.

**Comment by adingilloRancher** [comment]
master 8/3

Tested all three access levels for groups and users. Had ability to login as expected.
