### ISSUE TITLE
Slow download speed unlike vanilla Docker

### ISSUE THREAD

**Issue by trustfather** [rancher/rancher#14446]
**Rancher versions:**
Rancher | v2.0.4
User Interface | v2.0.53
Helm | dev
Machine | dev

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes v1.10.3

**Docker version: (`docker version`,`docker info` preferred)**
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Deploy new workload of "nextcloud" image.
upload file of 1 GB.
download it from a computer in another computer but in same network
Download speed is slow
.
Hello everyone, I want to use rancher to host my nextcloud.
My problem is that downloads are very slow on it. even in local network (while my LAN is in gigabit)
rancher machine (where all is installed) is powerful.. 16GB DDR4 + 8T 2.20Ghz + Gigabit connections.

I tried it with docker and it's very fast.

Rancher 2 : Download speed is 150KB/s
Docker : Download Speed is 12MB/s

It is however the same configuration, I only open port 80 I do nothing else as configuration.

On the other hand if I download from the same machine (where there is Rancher) then the download is very fast.
Note that the upload speed is very fast. it is only the download that is impacted . I don't use ingress

I don't know what to do to debug more. Ideas?

**Comment by superseb** [comment]
Please provide steps that we can run to reproduce. What image are you testing with, how are you exposing it, how are you testing (directly to the node, is the pod on the same node or is it going cross-node), what network provider did you choose

**Comment by trustfather** [comment]
**Please provide steps that we can run to reproduce :** 
Deploy new workload of "nextcloud" image.
expose port 80
connect to IPOFPOD:80 and then create new user and upload file of 1 GB into webui
download it from a computer but in same network
Download speed is slow

If you do the same thing but from an empty docker (no rancher or kubernetes) the speed is very fast

i'm testing it directly to the node

what is network provider ?

**Comment by superseb** [comment]
How are you exposing it, we can only reproduce and verify if there is a bug if you provide exact steps. There are 4 options to expose a port in a workload.

Does the node you are testing against run the pod? Or do you have only 1 node?

Network provider is what is defined when you create a cluster, if you didn't select any its Canal by default.
