### ISSUE TITLE
wrong cluster name showed by rancher ui

### ISSUE THREAD

**Issue by willmao** [rancher/rancher#14445]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04.4
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
ha k8s setup with rke
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
prepare a cluster.yml with rancher as useraddon for rke and setup cluster_name to `dev`, run `rke up`
**Results:**

the rke generated `kube_config_cluster.yml` shows the cluster name to be `dev`, but the rancher ui show the cluster name to be `local`

**Comment by vincent99** [comment]
When the Rancher container is running as a workload in a cluster, that cluster is automatically imported and always called `local`.

**Comment by willmao** [comment]
thx, i also notice that the `kubectl` show the cluster as `local`.
