### ISSUE TITLE
Scaling up App on vCenter cluster can't add shared vSan storage to other worker nodes

### ISSUE THREAD

**Issue by Murf** [rancher/rancher#14444]
Rancher versions: 2.0 master July 7
vCenter 6.7
ESXi 6.7

Setup details: single node rancher run as docker container

Steps to Reproduce:

Create a cluster with the vSphere template, edit yaml and and add CloudProvider details for vCenter
Create a Node Template with 2GB and 2 vCPU
Add 3 etcd, 3 control, 3 workers
Wait for cluster to be online
vMotion nodes so workers are on different ESXi hosts
Create a mysql workload from catalog Apps and assign persisted storage on vSan
Wait for App to be online
scale up app from 1 pod to 2
Results:

in vCenter, when Rancher tries to reconfigure another worker node to add vSan volume to the VM it has error:

Status: Failed to add disk 'scsi0:1'.
Error Stack:
File system specific implementation of OpenFile[file] failed
File system specific implementation of OpenFile[file] failed
File system specific implementation of OpenFile[file] failed
[...]
Failed to lock the file
Cannot open the disk '/vmfs/volumes/vsan:52e178f37733d363-4bd144458634c437/ae3c405b-1254-71a6-cbe9-0cc47a7edcd8/kubernetes-dynamic-pvc-4315955f-819c-11e8-9f44-005056bb7f95.vmdk' or one of the snapshot disks it depends on. 
Failed to power on 'scsi0:1'. 
Failed to add disk 'scsi0:1'.

**Comment by LinAnt** [comment]
All vSphere volumes are RWO, there is no way provisioning shared vSphere volumes. This is a limitation with the current implementation of VCP.

**Comment by loganhz** [comment]
Please see https://github.com/rancher/rancher/issues/14444#issuecomment-412770234
