### ISSUE TITLE
2.0.5 release notes: correct command `rancher cluster export`

### ISSUE THREAD

**Issue by develar** [rancher/rancher#14447]
In the https://github.com/rancher/rancher/releases/tag/v2.0.5 stated as `rancher export`, but actually command `rancher cluster export`

**Comment by develar** [comment]
Yeach... and "allows the export of a managed Kubernetes cluster as a YAML definition file." doesn't actually do what promised, only cluster definition is exported, but not the whole cluster...

**Comment by superseb** [comment]
Thanks, I updated it.
