### ISSUE TITLE
[CLI] rancher 2 CLI select project by name at login, non interactive

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#14448]
**Rancher versions:**
Rancher CLI 2
Rancher 2.0.4

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA with multiple projects

**Steps to Reproduce:**

when trying to login on rancher, when there are multiple projects, the CLI ask us to enter, interactively, the project:
```
$ rancher login https://orchestrator.example.com -t token
NUMBER    CLUSTER NAME    PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         example-inc   c-kmxs4:p-np8qm   default
2         example-inc   c-kmxs4:p-w246f   another
Select a Project:
```

We can only select project using that number index. Trying to use the name or project ID fails.

There is no non-interactive way to setup the project.

Within a CI, where new environment is created on each run, we always do "first login" because we have no cli2.json file when booting environment. We tried the context flag, with no success:

```
$ rancher login https://orchestrator.example.com -t token --context another
FATA[0000] no configuration found, run `login`

$ rancher login https://orchestrator.example.com -t token --context c-kmxs4:p-w246f
FATA[0000] no configuration found, run `login`
```

So I guess the context flag is not usable at first login.

**Problem**

The fact is it prevents us to create a CD using the CLI because we have no way to provide the answer through CI runners. We could do `echo 1 | rancher login ...` but doing so we have to know the index instead of project name/id.

Knowing the index, instead of name/ID is really a bad thing, since adding more projects can make the index change. So it's not reliable. And even if the project name remains the same, we would have to reconfigure our CI variables with new index each time a project is added.

Is there any way to provide the project as an argument directly winting the login command, non-interactively and using name/id of the project we want to use?

Or even better, allow us, at project selection, to enter the project id or name.

**Comment by n3or** [comment]
I ran in the same problem. But it is possible to create the cli2.json itself programmatically which did the trick for me:

`#/bin/bash

mkdir ~/.rancher
echo "{
  \"Servers\":
  {
    \"rancherDefault\":
    {
      \"accessKey\":\"$ACCESS_KEY\",
      \"secretKey\":\"$SECRET_KEY\",
      \"tokenKey\":\"$ACCESS_KEY:$SECRET_KEY\",
      \"url\":\"$ENDPOINT\",
      \"project\":\"$PROJECT_ID\",
      \"cacert\":\"\"
    }
  },
  \"CurrentServer\":\"rancherDefault\"
}" > ~/.rancher/cli2.json
`

You still need the context for the login, but then it worked for me.

Though it would be really great to have a real fix for this.

**Comment by felixschul** [comment]
Hi @n3or,

Thanks for the great solution. I thing writing the cli2.json file is actually a very clean solution. I put this into a separate image so it will not clutter up the CI file so much: https://github.com/ambient-innovation/rancher2-upgrade

In case of gitlab CI it can look like this: 

```
deploy:
  stage: deploy
  image: ambientinnovation/rancher2-upgrade:v1.0.0
  variables:
    GIT_STRATEGY: none
  only:
    - develop
  script:
    - /usr/local/bin/docker-entrypoint.sh # Creates the cli2.json with authentication data
    - /usr/local/bin/upgrade.sh default website # Triggers the actual upgrade
```

I am glad for all annotations or contributions to this. Thanks again for pointing to this solution.

**Comment by deniseschannon** [comment]
Available with v2.0.4-rc2

**Comment by blackholegalaxy** [comment]
Thanks @deniseschannon will give it a try today!

**Comment by soumyalj** [comment]
Tested using CLI rancher-v2.0.4-rc2 on master. The setup had two clusters. 
Selecting the project using `--context project id` during login works .
```
rancher-v2.0.4-rc2 soumya$ ./rancher login https://142.93.10.210/ --token token-wsw6j:h9cx6xlswt2s8kw7nhlxlpr28wcsslj67x7xvlt927dszmv7pzp9b8 --context c-9d2g8:p-nltqt

```
Accessing resources(nodes/workloads) from the project was done correctly.

Selecting the project using project id does not work, which is tracked here:

https://github.com/rancher/rancher/issues/14897

**Comment by GitRon** [comment]
Hi @soumyalj 

when I try your piece of code I'll always get this error:

`time="2018-11-08T07:49:41Z" level=fatal msg="no configuration found, run `login`"`

Any ideas what I might be doing wrong?

Best

**Comment by GitRon** [comment]
When is it planned to get the version `2.0.4` to dockerhub? Thanks :)
