### ISSUE TITLE
Exclude unschedulable nodes from cluster dashboard

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14459]
Version: master 9/7

Dashboard is showing resources that cannot be used (without tolerations). Possibly needs a note about workers.

**Comment by alena1108** [comment]
We should include only worker nodes not having unschedulable label set, to the dashboard capacity calculation

**Comment by vincent99** [comment]
@loganhz Can you change this to use the cluster.{requested,allocatable}` instead of looping over the nodes

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Verified fixed
