### ISSUE TITLE
Don't process container event if host is removed

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1445]
@ibuildthecloud and @cloudnautique observed a large number (20k+) of unprocessed `ContainEventCreate`s in the load test environment. The number of events was likely a normal side effect of the things Bill was doing while setting up the environment. But now that the environment is stable, those 20k processes are still stuck because of a bug that cause ContainerEventCreates to hang if the associated host is removed.

The fix is to not process the event if the associated host is removed.

**Comment by cjellick** [comment]
Fix isn't merged yet, but will be soon, So, @sangeethah I can't think of a good automated and reproducable validation test  that we could write for this.  However, our load test environment has roughly 25 thousands such containerEvents, so it will be a good test bed for this fix. Think that will suffice?

**Comment by sangeethah** [comment]
Since this issue was reported from load test environment , it would be sufficient if we can validate this issue in the same set up.

**Comment by cloudnautique** [comment]
Verified in loadtest.
