### ISSUE TITLE
More container details in Workload/Pod views

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14458]
- Show containers as expandable list in Workload under Pods list
- Show difference between container and init container
- Move container details to top and show headers inidicating what is what (container details vs pod details)

**Comment by davidnuzik** [comment]
@loganhz could you help me identify what I am to test regarding initcontainer and actual container? I think I got the rest correct.

- Show containers as expandable list in Workload under Pods list
This makes sense I can see a Containers section and we can see more than one under the pod:
![image](https://user-images.githubusercontent.com/45179589/50713891-d7b74700-1033-11e9-9d09-26980a847f6c.png)

- Show difference between container and init container
??? I can see when we are first creating the container the state is Unavailable and there is subtext mentioning creating container. Is this sufficient and what I need to test?
![image](https://user-images.githubusercontent.com/45179589/50713954-1b11b580-1034-11e9-918c-11fa8fbd74cb.png)

- Move container details to top and show headers indicating what is what (container details vs pod details)
I think this is around the information we have at the top:
![image](https://user-images.githubusercontent.com/45179589/50713990-41375580-1034-11e9-9a92-299b28c5a67b.png)

Many thanks!

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/7/19)
Confirmed feature:
- Show containers as expandable list in Workload under Pods list
There is now a "Containers" section under the Pods detail page that you can expand to see a list of containers.
- Show difference between container and init container
When you view pod details page you can now see subtext under the name of the container. It will show "Init Container" if the container is an init container now.
Also, if you view the container details at the top there is a section that will mention "initContainer:" (Yes/No)
- Move container details to top and show headers indicating what is what (container details vs pod details)
Container details are now at the top with relevant information.
