### ISSUE TITLE
Show response from externalIpServiceController in UI

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14457]
Version: master 7/9

Add DNS record pointing to IP `127.0.0.2`, gets added successfully.

`rancher/rancher` logs:

```
2018/07/09 08:53:08 [INFO] Creating endpoints for external ip service [default/blaat]: [{[{127.0.0.2  <nil> nil}] [] [{default 42 TCP}]}]
2018/07/09 08:53:08 [ERROR] ServiceController default/blaat [externalIpServiceController] failed with : Endpoints "blaat" is invalid: subsets[0].addresses[0].ip: Invalid value: "127.0.0.2": may not be in the loopback range (127.0.0.0/8)
```

**Comment by soumyalj** [comment]
Tested with master build from Sep 6th. Added a DNS record with 127.0.0.2 in the UI. DNS entry failed to get added with the below error as expected
![screen shot 2018-09-06 at 4 43 45 pm](https://user-images.githubusercontent.com/18536626/45190681-0f33f500-b1f4-11e8-9112-b42da108e144.png)

Server logs : 
```
2018/09/06 22:57:31 [ERROR] Unknown error: 127.0.0.2 may not be in the loopback range (127.0.0.0/8)
```
