### ISSUE TITLE
Need version bump of k8s dashboard to prevent k8s dashboard issues #2723

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#14451]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.18
rancher/agent or rancher/rancher-agent:

**Steps to Reproduce:**
1. current dashboard image of kubernetes-dashboard-amd64:v1.8.0 is susceptible to the excessive logging bug [#2723](https://github.com/kubernetes/dashboard/issues/2723) when the kube api server restarts

**workaround:**
1.  restart or delete (to clear up logs) the dashboard container.

**Comment by deniseschannon** [comment]
@moelsayed can you investigate what version of dashboard we could use with k8s 1.10.5?

**Comment by moelsayed** [comment]
@deniseschannon v1.10.5 is using the latest dashboard [1.8.3](https://github.com/rancher/kubernetes-package/blob/k8s-v1.10/package/addons-update.sh#L76). Upstream issue suggests that the fix might not be complete yet. 

I will check and see if we can reduce the logs using the logging configuration we have.

**Comment by moelsayed** [comment]
Our default setup doesn't seem to generate a lot of logs. I tested with Rancher v1.6.18, kubernetes v1.10.5 and dashboard v1.8.3.
