### ISSUE TITLE
Support Keyless tags for syslog

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#14465]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.5
rancher/agent or rancher/rancher-agent:

Users using the Syslog interface to cloud based log aggregators need to be able to specify a Token in the structured data section without a key.

**Comment by cloudnautique** [comment]
This needs to be keyless.. no `token` key. please see: 
https://help.sumologic.com/Send-Data/Sources/02Sources-for-Hosted-Collectors/Cloud-Syslog-Source

step 9.

**Comment by cloudnautique** [comment]
You can sign up for a free trial without CC on Sumo, please make sure it works before closing.

**Comment by aiwantaozi** [comment]
I have tested in sumologic

**Comment by cloudnautique** [comment]
No logs are getting to sumologic.

**Comment by aiwantaozi** [comment]
Not input program field will make it throw error when transmitting log, improve to not throw error when no program field.

**Comment by cloudnautique** [comment]
Able connect into SumoLogic with the cloud syslog target.
