### ISSUE TITLE
Enabling audit logging for Kubernetes

### ISSUE THREAD

**Issue by manwanth** [rancher/rancher#14468]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.15
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**  
17.03.2.ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**  
Red Hat Enterprise Linux 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** 
AZURE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
HA ranche and  external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

**Results:**

I want enable audit logging for Kubernetes, but I could not find kube-apiserver. I want to know how to enable audit logging.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
