### ISSUE TITLE
Nodes in AWS cluster don't appear with right hostname

### ISSUE THREAD

**Issue by Leen15** [rancher/rancher#14460]
Hi, I'm using rancher 2.0.5 and  I created a cluster with "Amazon EC2" provider.
It works, but on node list all names are with format "ip-XX-XX-XX" instead of the right hostname that I put during the cluster creation (suffix -> "nodes").
![image](https://user-images.githubusercontent.com/3629071/42449716-032cdea2-8382-11e8-9f9e-4482adada8c2.png)

As you can see from the screenshot the hostname is correct in edit mode:
![image](https://user-images.githubusercontent.com/3629071/42449720-07c7a046-8382-11e8-8f35-7949f8c54d25.png)

**Comment by loganhz** [comment]
Can you try it in v2.1.0, please?
I can not reproduce this issue in v2.1.0

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
