### ISSUE TITLE
Openstack cinder volume creation fails

### ISSUE THREAD

**Issue by OberstHorst** [rancher/rancher#14461]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.5
rancher/agent or rancher/rancher-agent: 2.0.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.5

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
Deploy with Openstack cloud provider, create cinder storage class, create pv/pvc and mount it to container in pod. Happens both in GUI and with kubectl

**Results:**
PV creation fails with error:
 I0709 15:19:51.934040       1 cinder_util.go:213] Error creating cinder volume: failed to create a 30 GB volume: Resource not found
I0709 15:19:51.934076       1 pv_controller.go:1433] failed to provision volume for claim "default/fff" with StorageClass "gold": failed to create a 30 GB volume: Resource not found

**Comment by mecossa** [comment]
Facing similar issue, Cluster created on Openstack working fine, but if I try to use cinder as permanent storage deployment fails...

/etc/kubernetes/cloud-config: no such file

**Comment by mecossa** [comment]
kubectl get pvc --all-namespaces
NAMESPACE   NAME      STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mariadb     mariadb   Pending                                       test           5m
> kubectl describe  pvc mariadb -n mariadb
Name:          mariadb
Namespace:     mariadb
StorageClass:  test
Status:        Pending
Volume:
Labels:        app=mariadb
               chart=mariadb-3.0.3
               heritage=Tiller
               io.cattle.field/appId=mariadb
               release=mariadb
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"mariadb","chart":"mariadb-3.0.3","heritage":"Tiller","r...
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/cinder
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  0s (x26 over 5m)  persistentvolume-controller  Failed to provision volume with StorageClass "test": OpenStack cloud provider was not initialized properly : stat /etc/kubernetes/cloud-config: no such file or directory

**Comment by dommgifer** [comment]
In Rancher UI ,
1 .Edit your cluster 
2. In cluster options , use "Edit as YAML"
3.  add cloud_provier in yaml:
cloud_provider: 
  name: "openstack"
  openstack_cloud_provider: 
    block_storage: 
      bs-version: "v2"
      ignore-volume-az: false
      trust-device-path: false
    global: 
      auth-url: "XXXXXX"
      domain-name: "XXXX"
      password: "XXXX"
      tenant-id: "XXX"
      username: "XXX"

**Comment by loganhz** [comment]
Please try it in v2.1.1 and follow the doc to config openstack cloud provider https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/openstack/

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
