### ISSUE TITLE
Certificate details not shown when created using cert-manager

### ISSUE THREAD

**Issue by mrmurb** [rancher/rancher#14467]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.5

**Steps to Reproduce:**
Create _cert-manager_ from Helm, using Catalog.
Setup `Issuer` or `ClusterIssuer`.
Create `Certificate`, expect to be generated sucessfully.

**Results:**
`Certificate` is shown in Rancher UI. But missing fields:
- Algorithm
- Issuer
- Serial Number
- Fingerprint

_Valid Beginning_ and _Expires_ are filled, but with invalid data. [Screenshot](https://i.imgur.com/IlMN4IE.png)

**Comment by TehTotalPwnage** [comment]
Duplicate of #14423.
