### ISSUE TITLE
Agents should use internal addresses to communicate with the server

### ISSUE THREAD

**Issue by tobowers** [rancher/rancher#1446]
Hiyo!

We have our rancher boxes sitting in a private subnet, with an ELB in a public subnet TCP proxying traffic to the rancher server.  

I cannot specify the internal address for the agents to connect to. If I do, the agent starts up and then deletes itself. If I use the public-facing url in agent creation, the agent successfully connects.

Our setup is

ELB -> nginx container -> rancher-server container

I'd like the agents to connect to the rancher-server container on port 8080 (but have UI traffic flow across the ELB)

**Comment by ibuildthecloud** [comment]
@tobowers Have you tried setting the "Host Registration" (upper right in UI) to the private IP?  This should work, if it doesn't we can fix.  So you should be able to access the UI through whatever user but then set the "Host Registration" to private and then agents will talk to the ip:port tuple.

**Comment by ibuildthecloud** [comment]
@tobowers Based on another thread I see your doing api.host=" ".  Again this *should* work, but obviously something is wrong.  Sorry the SSL setup is so hacky right now.

If you copy and paste the `sudo docker run...` from the UI and then replace `http://public_ip/...` with `http://private_ip/` I would think it would work.  Can you share any output from the agent containers.  The original `sudo docker run` container doesn't get delete so you should be able to get the docker logs from it.

**Comment by tobowers** [comment]
@ibuildthecloud ok that worked... maybe I missed that part in the docs, anyways... thank you!
