### ISSUE TITLE
Catalog apps deployment status is not reflect on the catalog apps page correctly

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#14476]
Rancher versions: 2.0 master 10/07
Steps to Reproduce:
1. Install a catalog from the catalog apps
2. Even after the catalog app is installed successfully, the status is always showing as `Deploying`
3. need to refresh the browser to get the updated status (should be a WebSocket issue)

Results: Should reflect the correct status to `Active`
![image](https://user-images.githubusercontent.com/4569037/42499783-41576108-8462-11e8-9448-5c5d88130ab4.png)

**Comment by ekristen** [comment]
I am seeing this version on 2.0.6.

**Comment by alena1108** [comment]
Should be fixed once we start populating the state in the controller (as a part of multi cluster app upgrade feature @kinarashah is working on)

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master 2/8

Steps:
- launch one catalog app 
- check the `catalog apps` page to track the status of the newly launched app
- repeat the above two steps several times

Result:
The status of the app switches from `Deploying` to `Active` as soon as the workloads are active, and I don't have to refresh the page to see the change.

**Comment by alena1108** [comment]
To elaborate on the impact of the fix a little more. Before the fix, an app state calculation was performed on the api layer. For every app returned by the api, there were several extra calls made to get all the app's workloads. Based on that data, the app state was calculated dynamically. That all could resulted in apps.list API call slowness.

With the fix, the app state is being calculated internally, by the background controllers, and set on the app object in the etcd DB. This way, when app.list call is made, there is no need for the extra workload.list calls.
