### ISSUE TITLE
unable to install rancher/rancher:2.0.4

### ISSUE THREAD

**Issue by dongfo** [rancher/rancher#14473]
**Rancher versions:**
rancher/rancher: V2.0.4
centos :7.4
docker-ce: 18.05

2018/07/10 01:15:10 [INFO] Starting catalog controller
2018/07/10 01:15:10 [INFO] Starting management controllers
2018/07/10 01:15:10 [INFO] Syncing SecretController Controller
2018/07/10 01:15:10 [INFO] Syncing PodSecurityPolicyTemplateProjectBindingController Controller
2018/07/10 01:15:10 [INFO] Syncing RoleController Controller
2018/07/10 01:15:10 [INFO] Syncing NamespaceController Controller
2018/07/10 01:15:10 [INFO] Syncing ClusterEventController Controller
2018/07/10 01:15:10 [INFO] Syncing ProjectController Controller
2018/07/10 01:15:10 [INFO] Syncing RoleTemplateController Controller
2018/07/10 01:15:10 [INFO] Syncing ClusterController Controller
2018/07/10 01:15:10 [INFO] Syncing GlobalRoleController Controller
2018/07/10 01:15:10 [INFO] Syncing ProjectRoleTemplateBindingController Controller
2018/07/10 01:15:10 [INFO] Syncing ClusterRoleTemplateBindingController Controller
2018/07/10 01:15:10 [INFO] Syncing GlobalRoleBindingController Controller
2018/07/10 01:15:10 [INFO] Syncing ProjectAlertController Controller
2018/07/10 01:15:10 [INFO] Syncing TokenController Controller
2018/07/10 01:15:10 [INFO] Syncing PodSecurityPolicyTemplateController Controller
2018/07/10 01:15:10 [INFO] Syncing ComposeConfigController Controller
2018/07/10 01:15:10 [INFO] Syncing DynamicSchemaController Controller
2018/07/10 01:15:10 [INFO] Syncing NodeDriverController Controller
2018/07/10 01:15:10 [INFO] Syncing NodePoolController Controller
2018/07/10 01:15:10 [INFO] Syncing UserController Controller
2018/07/10 01:15:10 [INFO] Syncing TemplateController Controller
2018/07/10 01:15:10 [INFO] Syncing TemplateVersionController Controller
2018/07/10 01:15:10 [INFO] Syncing TemplateContentController Controller
2018/07/10 01:15:10 [INFO] Syncing CatalogController Controller
2018/07/10 01:15:10 [INFO] Syncing NodeController Controller
2018/07/10 01:15:10 [INFO] Syncing ClusterRoleBindingController Controller
2018/07/10 01:15:10 [INFO] Syncing RoleBindingController Controller
2018/07/10 01:15:10 [INFO] Syncing ClusterRoleController Controller
2018/07/10 01:15:10 [INFO] Syncing SecretController Controller Done
2018/07/10 01:15:10 [INFO] Syncing RoleController Controller Done
2018/07/10 01:15:10 [INFO] Syncing NamespaceController Controller Done
2018/07/10 01:15:10 [INFO] Syncing RoleTemplateController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ProjectRoleTemplateBindingController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ClusterRoleTemplateBindingController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ClusterEventController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ProjectController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ClusterController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ProjectAlertController Controller Done
2018/07/10 01:15:10 [INFO] Syncing TokenController Controller Done
2018/07/10 01:15:10 [INFO] Syncing DynamicSchemaController Controller Done
2018/07/10 01:15:10 [INFO] Syncing NodeDriverController Controller Done
E0710 01:15:10.653763       1 core.go:70] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail.
2018/07/10 01:15:10 [INFO] Syncing UserController Controller Done
2018/07/10 01:15:10 [INFO] Syncing NodeController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ClusterRoleBindingController Controller Done
2018/07/10 01:15:10 [INFO] Syncing RoleBindingController Controller Done
2018/07/10 01:15:10 [INFO] Syncing PodSecurityPolicyTemplateProjectBindingController Controller Done
2018/07/10 01:15:10 [INFO] Syncing GlobalRoleController Controller Done
2018/07/10 01:15:10 [INFO] Syncing GlobalRoleBindingController Controller Done
2018/07/10 01:15:10 [INFO] Syncing PodSecurityPolicyTemplateController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ComposeConfigController Controller Done
2018/07/10 01:15:10 [INFO] Syncing NodePoolController Controller Done
2018/07/10 01:15:10 [INFO] Syncing TemplateController Controller Done
2018/07/10 01:15:10 [INFO] Syncing TemplateContentController Controller Done
2018/07/10 01:15:10 [INFO] Syncing TemplateVersionController Controller Done
2018/07/10 01:15:10 [INFO] Syncing CatalogController Controller Done
2018/07/10 01:15:10 [INFO] Syncing ClusterRoleController Controller Done
2018/07/10 01:15:10 [INFO] Reconciling GlobalRoles
2018/07/10 01:15:10 [INFO] Reconciling RoleTemplates
2018/07/10 01:15:11 [INFO] Rancher startup complete
2018/07/10 01:15:18 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:36505->10.236.158.106:53: i/o timeout
2018/07/10 01:15:26 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:33640->10.236.158.106:53: i/o timeout
2018/07/10 01:15:34 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:59618->10.236.158.106:53: i/o timeout
2018/07/10 01:15:42 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:40641->10.236.158.106:53: i/o timeout
2018/07/10 01:15:50 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.114:53: read udp 172.17.0.2:40782->10.236.158.114:53: i/o timeout
2018/07/10 01:15:59 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.114:53: read udp 172.17.0.2:40124->10.236.158.114:53: i/o timeout
2018/07/10 01:16:07 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:59976->10.236.158.106:53: i/o timeout
2018/07/10 01:16:15 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:39321->10.236.158.106:53: i/o timeout
2018/07/10 01:16:23 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:51583->10.236.158.106:53: i/o timeout
2018/07/10 01:16:31 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.114:53: read udp 172.17.0.2:40567->10.236.158.114:53: i/o timeout
2018/07/10 01:16:39 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:36540->10.236.158.106:53: i/o timeout
2018/07/10 01:16:47 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.114:53: read udp 172.17.0.2:35737->10.236.158.114:53: i/o timeout
2018/07/10 01:16:55 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:48758->10.236.158.106:53: i/o timeout
2018/07/10 01:17:03 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.114:53: read udp 172.17.0.2:60379->10.236.158.114:53: i/o timeout
2018/07/10 01:17:11 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:38646->10.236.158.106:53: i/o timeout
2018/07/10 01:17:19 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:44510->10.236.158.106:53: i/o timeout
2018/07/10 01:17:27 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:43903->10.236.158.106:53: i/o timeout
2018/07/10 01:17:35 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:44014->10.236.158.106:53: i/o timeout
2018/07/10 01:17:43 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:55844->10.236.158.106:53: i/o timeout
2018/07/10 01:17:51 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.236.158.106:53: read udp 172.17.0.2:35139->10.236.158.106:53: i/o timeout

**Comment by superseb** [comment]
Rancher is starting fine, it's connecting to our chart repo to get the catalog apps. You can change that when logging into the UI.

```2018/07/10 01:15:11 [INFO] Rancher startup complete
```
We have https://github.com/rancher/rancher/issues/13700 open to be able to change this behavior.

Let me know if it doesn't solve it for you.
