### ISSUE TITLE
Add keepalive message to connection between host-api and websocket-proxy

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1447]
@cloudnautique and @ibuildthecloud discovered that nginx has a 60 second connection timeout by default and that when nginx is placed infront of the websocket proxy, this causes the ws connection between host-api and wsp to die every 62 seconds.

Need to add a keep alive message (maybe just a simple ws ping) to prevent this.

**Comment by cjellick** [comment]
Ah! I missed assigning this one over, but it was fixed as part of the SSL proxy changes.

**Comment by sangeethah** [comment]
Tested with server version - rancher/server:v0.31.0-rc1 in a SSL enabled rancher server setup behind nginx reverse proxy.
 
There is no reconnects happening for the websocket connection between rancher server and agent anymore.
