### ISSUE TITLE
On AD auth enabled setups upgraded from 2.0.4 "Nested Group Membership" does not show up as option until manually refreshed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14489]
**Rancher versions:** v2.0.6-rc1

Steps to reproduce the problem:
Started with fresh install of 2.0.4 and enabled AD auth on.
Enable site Access for group that had nested level.
Upgraded to 2.0.6-rc1.
Log in AD admin user and click on "Security/Authentication" to get to AD auth page. Click on "Edit".
Notice that under "Customize Schema" page ,"Nested Group Membership" option does not exist at all.

I see the NestedGroupMembershipEnabled flag set to "false" in api (v2/authcofig) and only users from the nested group at first level in the site access list are able to get access to rancher-server.

I had to do a manual refresh on this page , to see the Nested Group Membership" option show up and it has the "Search only direct group memberships" enabled as expected.

**Comment by adingilloRancher** [comment]
Not able to reproduce in 2.0.6-rc2.

Performed upgrade and immediately navigated to "Security/Authentication". Selected edit and opened scheme section. "Nested Group Membership" was present on my first hit. Did not need to refresh page in order to see the option.
