### ISSUE TITLE
Nested group search for AD and LDAP needs to be turned off by default

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#14482]
Since introducing nested group search for Active Directory, we've seen multiple users run into problems where the search just does not work for them. The AD servers cannot handle the recursive query.

In v2.0.5, we introduced the `NestedGroupMembershipEnabled` flag for both AD and OpenLDAP so that users could turn the feature off, but we defaulted it to On (field set to true).
Based on the issues we've seen, we want to turn it off by default (field set to false) so that users must opt-in to using it.

Changing the default causes some complications for upgrades that we nee to be aware of and test. Active Directory and LDAP must be handled differently:

### AD
Because the AD provider existed before the NestedGroupMembershipEnabled was introduced, the field can have three different values: true, false, or nil. Setups that are upgrading from anything before v2.0.5 will have the field set to nil. We currently interpret a value of nil the same as a value of true, meaning the feature is on. This must change such that a nil value is interpreted the same as a value of false. Additionally, the api default (set in authn_types.go) should be changed from true to false so that all new installs have the feature turned off by default.
We will say in the release notes that the behavior for upgrading users is changing such that the feature will be off and if they want it on, they must explicitly turn it on.

### LDAP
OpenLDAP has the NestedGroupMembershipEnabled field, but it cannot have a nil value. It can only be true or false. So, the only thing we need to change for OpenLDAP is the api default value. It should be changed from true to false. 
We will say in the release notes that if upgrading users want to turn the feature off, they must explicitly do so.

FreeIPA does not expose this flag and no changes are needed because it returns recursive groups automatically.

**Comment by sangeethah** [comment]
@mrajashree  for AD setups:
```
We will say in the release notes that the behavior for upgrading users is changing such that the feature will be off and if they want it on, they must explicitly turn it on.
```
I started with fresh install of 2.0.5 and enabled AD auth on (with default setting that has NestedGroupMembershipEnabled flag enabled). 
Upgraded to 2.0.6-rc1.
I see the NestedGroupMembershipEnabled flag still enabled in this case and allowed users in the site access list from the nested group (for multiple levels) are able to get access to rancher-server. 

In this case , we expect  NestedGroupMembershipEnabled flag to be disabled?

**Comment by mrajashree** [comment]
@sangeethah 
Scenario 1: Sounds correct. For fresh install of 2.0.5, we expect the NestedGroupMembershipEnabled  to still be `true` even after upgrade, so nested users will still be given access after upgrade. If the admin wants to disable it, then the admin can login as local admin and edit the AD config

Scenario 2: That is the expected behavior

**Comment by sangeethah** [comment]
Scenario 3:
Started with fresh install of 2.0.5 and enabled AD auth on (with NestedGroupMembershipEnabled flag disabled). Enable site Access for group that had nested level.
Upgraded to 2.0.6-rc1.
I see the NestedGroupMembershipEnabled flag remains disabled.

**Comment by adingilloRancher** [comment]
AD 2.06-rc2 fresh install. Nested groups disabled by default.  Validated nested users are unable to login.

**Comment by sangeethah** [comment]
On fresh install of v2.0.6 , openLdap has Nested groups disabled by default.
