### ISSUE TITLE
Blank certificate-authority-data on Kubeconfig file

### ISSUE THREAD

**Issue by lbtoma** [rancher/rancher#14488]
Rancher is writing the certificate-authority-data key even if the deployment was done with certificate signed by recognized CA. If not perceived, this cause some problems while using the Python Kubernetes lib.

apiVersion: v1
kind: Config
clusters:
- name: "something"
  cluster:
    server: "https://rancher.myname.com/k8s/clusters/something"
    api-version: v1
    certificate-authority-data: ""

users:
- name: "something"
  user:
    token: "something"

contexts:
- name: "somethingr"
  context:
    user: "something"
    cluster: "something"

current-context: "something"

In the Python Traceback:

kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected key certificate-authority-data in kube-config/clusters[name=something]/cluster

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by bmdepesa** [comment]
rancher/rancher:master 7/16

When using a certificate signed by a recognized CA, the certificate-authority-data field is not included in the generated kubeconfig.

I also verified that the generated kubeconfig can still be used.
