### ISSUE TITLE
Helm not installed in kubectl container - bash: helm: command not found

### ISSUE THREAD

**Issue by cgebe** [rancher/rancher#14496]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.5
rancher/agent or rancher/rancher-agent: 2.0.5

**Steps to reproduce:**

1. Setup a custom cluster.
2. Open kubectl via the webinterface.
3. Enter any helm command

**Expected result:**

That helm is installed in the started kubectl container

**Comment by jgreat** [comment]
Helm charts applied through Rancher are processed by the Rancher server and then remotely applied to the worker clusters. There is no tiller on the worker cluster or helm cli installed in the in browser interface.

To use helm charts you have a couple of options.  

You can enable or add chart repositories in the Global -> Charts menu. Then install charts with the GUI or `rancher` CLI interfaces.
 or
You can download the `kubeconfig` file to your desktop/workstation and use the `helm` CLI to install tiller on your worker cluster.

**Comment by cgebe** [comment]
@jgreat thanks for the clarification
I come from kubeadm, kops and looked into rancher recently due to the kubernetes switch. The work with kubeadm, kops can be tedious and rancher provides excellent extensions. Anyway, i currently don't see the surplus of the helm catalog, since it is usual to apply own settings to the charts via customized `values.yaml` files in order to persist the final state of a service in a system and also allow easy re-deployments across clusters, instead of applying changes after the deployment in the webinterface. The editing of the `values.yaml` is not possible via the webinterface (only a preview), so if i want to deploy my own charts i do either add my private chart repo or circumvent rancher. Are there plans to tighten the helm integration? e.g. a way to edit the `values.yaml`, before and after deploying a chart from the catalog. What is the actual use case of the helm catalog?

**Comment by tibers** [comment]
https://rancher.com/docs/rancher/v1.6/en/kubernetes/addons/ This was a feature at one point which is why I'm sad. I used 1.6 and then came back in 2 and expected this to Just Work. Can we please get it plunked back in there?

**Comment by deniseschannon** [comment]
@cgebe with the v2.2, there is tighter integration and you can apply your values.yml through the UI or through a yaml file. 

The expectation is if you have a custom helm chart to add it into rancher and use our catalog service to launch the templates. The benefit is that you can have a more customized helm chart with added files in order to leverage the Rancher UI to share applications for an easier UX. 

Here are some docs:

https://rancher.com/docs/rancher/v2.x/en/catalog/
https://rancher.com/docs/rancher/v2.x/en/catalog/custom/

@tibers Is there a specific reason why you need it?

**Comment by josenobile** [comment]
Hello, 

I have a use case, I want to install https://github.com/submariner-io/submariner

Steps:
1. helm repo add submariner-latest https://releases.rancher.com/submariner-charts/latest -> Using Rancher UI
2. kubectl -n kube-system create serviceaccount tiller -> Done
3. kubectl create clusterrolebinding tiller \
  --clusterrole=cluster-admin \
  --serviceaccount=kube-system:tiller -> Done
4. helm init --service-account tiller -> Any other way to accomplish this step Using Rancher to install Rancher Submariner?
