### ISSUE TITLE
[Feature] Add an option to whitelist registries

### ISSUE THREAD

**Issue by LinAnt** [rancher/rancher#14494]
I would like to lock down some of my clusters. It would be really neat if one could provide a list of trusted registries per cluster, where an admin can specify exactly which registries are allowed to be used inside the cluster.

It looks to be a feature in Rancher 1.6: https://rancher.com/docs/rancher/v1.6/en/environments/registries/

**Comment by dnoland1** [comment]
Customer requested this today and would want the option to blacklist and/or whitelist registries either globally (all clusters), or per cluster.

Using the ImagePolicyWebhook Admission Controller may be a possible workaround - https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#imagepolicywebhook

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/23753
