### ISSUE TITLE
Two error message for single field in Add External Service

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1449]
Steps:
1.  Go to Add External Service page
2.  Put in a Name
3.  Click on Create

Results:
Two error messages:
![image](https://cloud.githubusercontent.com/assets/11514927/8601516/58aeb3da-2621-11e5-8893-16820e6ba2f9.png)

Expected:
Should really only have 1 error message, since they are both related to the Adding an External IP

**Comment by deniseschannon** [comment]
v0.27.0-rc4: Verified Fixed
