### ISSUE TITLE
add catalog relevant configmap resources to the catalog detail page

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#14491]
Rancher versions: 2.0 master 07/11

Steps to Reproduce:
1. deploy an app like Kafka from the catalog page which contains some ConfigMap resources.
2. should add its ConfigMap resources to the catalog details page for each deployed app.

Results: Add the ConfigMap resources to the catalog detail page.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/31
Verified fixed
