### ISSUE TITLE
Slack notifier doesn't allow private channels

### ISSUE THREAD

**Issue by adampl** [rancher/rancher#14495]
**Rancher versions:**
Rancher v2.0.0
User Interface v2.0.41

**Setup details:**
Single node

**Steps to Reproduce:**
1. Create a private channel on Slack and an incoming webhook
1. In Rancher, go to: Tools, Notifiers, Add Notifier
1. Enter webhook URL
1. Click Test
1. Enter channel name
1. Click Test

**Results:**
The first time test fails with the following validation message:
> "Default Recipient" is required

The second time the error says:
> http status code is not 200

**Expected results:**
The Default Recipient field should be optional, as Slack Webhook API will send the message to the default channel of the webhook if the _channel_ field is not specified. In case of private channels the _channel_ API field must not exist or be empty, otherwise the webhook returns a `channel_not_found` error. As a result, it's not possible to use private channels, though Slack API allows it.

**Comment by jiaqiluo** [comment]
@adampl I tried your steps on v2.0.0 and it works on my setup.  For the `Default Recipient (Channel)` filed, do you put an `#` in front of the channel name?  For example, `#test` will work, but `test` will fail and return `http status code is not 200`.
