### ISSUE TITLE
[cli] container command is concatenated instead of replaced when using multiple --file options in rancher up

### ISSUE THREAD

**Issue by sunbit** [rancher/rancher#14490]
After upgrading from rancher 1.5.10 to 1.6.18, using the bundled client for each one i noticed a difference on how the `--file` option of `rancher up` is applied. For sections like `image` and `port` it works as expected, replacing and adding respectively. But what i found is that if in the extra compose files you try to overwrite the `command` you end up with a concatenation of both commands, which fails. I use this a lot for image development and debug purposes and with this version of rancher i can't use it anymore.

See the "Steps to reproduce" section for details on how to reproduce this issue, Thank you.

**Rancher versions:**
rancher/server: 1.6.18
rancher/agent: 1.2.10
client: v0.6.10 (downloaded from the rancher ui)

**Docker version: (`docker version`,`docker info` preferred)**

Containers: 53
 Running: 48
 Paused: 0
 Stopped: 5
Images: 584
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.17.4-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.47GiB
Name: turing
ID: HONL:PYQB:OOIV:3FQK:32M6:HFLV:LVCG:JVTF:G5YO:U7VF:P3E7:EZ7S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: **
4.17.4-1-ARCH

**Type/provider of hosts: **
Bare-metal

**Setup details: **
single-node rancher

**Environment Template: **
Cattle

**Steps to Reproduce:**
Using the following files:

docker-compose.yaml
```version: '2'
services:
  dummy:
    image: ubuntu
    command: ls
    tty: true
```
docker-compose-extra.yaml
```version: '2'
services:
  dummy:
    command: bash
```
and run

`rancher up -f docker-compose.yaml -f docker-compose-extra.yaml`

**Results:**

Looking at the `dummy`service container command in the ui, it has `ls,bash` instead of the expected  `bash` alone

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
