### ISSUE TITLE
AD with TLS doesn't login with certain certificates

### ISSUE THREAD

**Issue by phertweck** [rancher/rancher#14502]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.4 (also tested in 2.0.2)

**Steps to Reproduce:**
We want to configure Rancher to authenticate against our AD. We've configured our AD accordingly (it's the same configuration we use for other services). When testing the connection we receive "authentication failure".

**Results:**
Receiving "authentication failure" and the log entry:

[ERROR] API error response 401 for POST /v3/activeDirectoryConfigs/activedirectory?action=testAndApply. Cause: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580

We rechecked the credentials. They are correct and for other services they are working.

**Comment by mrajashree** [comment]
@phertweck Can you please share debug logs? Are the login domains for both, the user who's logging in and the service account user being provided?

**Comment by mrajashree** [comment]
@phertweck sure! https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-enable-debug-logging

Also, can you run these ldapsearch commands:
`ldapsearch -H <ldap://server> -x -D "<defaultLoginDomain>\<serviceAccountUsername>" -W -b "<UserSearchBase>" -s sub "(&(sAMAccountName=<testuserWhoIsLoggingin>)(objectClass=person))"`

and
`ldapsearch -H <ldap://server> -x -D "<defaultLoginDomain>\<testuserWhoIsLoggingin>" -W -b "<UserSearchBase>" -s sub "(&(sAMAccountName=<testuserWhoIsLoggingin>)(objectClass=person))"`

You'll have to replace all the necessary fields with your AD server fields...thanks!

**Comment by phertweck** [comment]
We managed to configure the AD without TLS. Removing the default login domain and only entering the user name did the trick.

Now we want to secure the authentication by enabling TLS. Our server has a self signed certificate. We provide the CA pem file through the UI, but receive the following error:
`Error creating ssl connection: LDAP Result Code 200 "": read tcp 10.X.X.X:38392->10.X.X.X:636: read: connection reset by peer` In the debug log there is no other message.

When we try to use ldap search using TLS and providing the CA (
 `env LDAPTLS_CACERT=cert.pem ldapsearch -H <ldaps://server> -x -D "<defaultLoginDomain>\<serviceAccountUsername>" -W -b "<UserSearchBase>" -s sub "(&(sAMAccountName=<testuserWhoIsLoggingin>)(objectClass=person))"`) it works.

**Comment by Nephelo** [comment]
Hello,

I've a similar problem on rancher 2.0.4. Leaving the default domain empty and specifing the service username in the service account field as well as in the test user field works. If I try to add an other user to the test user field I get an authentication failure.

Logs:
`[DEBUG] configApplyInput &{{{ } {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{ } {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } activeDirectoryConfig true unrestricted []} [LDAP_IP] 389 false   SERVICE_USERNAME SERVICE_PASSWORD 2 DC=home,DC=DOMAIN,DC=TLD sAMAccountName|sn|givenName sAMAccountName person name userAccountControl  sAMAccountName group name distinguishedName distinguishedName member 5000} USERNAME MY_PW true}`
`2018/07/12 21:06:16 [DEBUG] Now generating Ldap token`
`2018/07/12 21:06:16 [DEBUG] Now creating Ldap connection`
`2018/07/12 21:06:16 [DEBUG] Binding username password`
`2018/07/12 21:06:16 [ERROR] API error response 401 for POST /v3/activeDirectoryConfigs/activedirectory?action=testAndApply. Cause: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839`

Running this ldap search returns the USERNAME object:
`ldapsearch -H ldap://AD-IP -x -D "SERVICE_USERNAME" -W -b "DC=home,DC=DOMAIN,DC=TLD" -s sub "(&(sAMAccountName=USERNAME)(objectClass=person))"
`

**Comment by cjellick** [comment]
I think @phertweck's TLS issue is ultimately the same issue we saw here in 1.6.x:
https://github.com/rancher/rancher/issues/10008

The fix was to upgrade go to 1.10

**Comment by deniseschannon** [comment]
@phertweck would you be willing to test out a RC as we don't have an auth server with the same level of certs?

**Comment by phertweck** [comment]
@deniseschannon Yes, sure. What's the tag of the image I should test?

**Comment by deniseschannon** [comment]
@phertweck the fix that we had merged in to bump the go version has introduced some issues and we've had to revert that fix. 

we need to do more investigation at it looks like there is a bug in golang 1.10.3 that has been fixed in golang 1.11, which is not released yet.

**Comment by phertweck** [comment]
Thank you for this information.

Will golang 1.11 only fix the cert issue or will this also affect the "Invalid Credentials" issue, which also appears without TLS?

**Comment by deniseschannon** [comment]
@phertweck My understanding was that that the invalid credentials only appears with TLS? Are you saying it appears without TLS?

**Comment by phertweck** [comment]
@deniseschannon I think there are two problems.

1. Connecting to AD **without** TLS: I used a service account to connect to AD. Testing the login with the service account is working, but testing it with an other user account is not working. I think that's the same effect @Nephelo is facing.

2. Connecting to AD **with** TLS it is directly failing.

Please let me know if you need further information.

**Comment by deniseschannon** [comment]
@Nephelo @phertweck I filed https://github.com/rancher/rancher/issues/15116

to address the first issue. I'm going to rename this issue to track the connecting AD with TLS since the history in this ticket has been around this issue.

**Comment by alena1108** [comment]
golang is bumped up to v1.11 in rancher 2.1, marking as resolved

**Comment by alena1108** [comment]
@sangeethah nothing specific to test, lets just make sure our validation test passes

**Comment by deniseschannon** [comment]
@phertweck would you be able to test using v2.1.0-rc1 to test that you are able to enable AD authentication with your certificate type?

**Comment by deniseschannon** [comment]
Thanks @phertweck!
