### ISSUE TITLE
creating a cluster in Rancher V2.0.4 fails pulling rancher/rke-tools:v0.1.10

### ISSUE THREAD

**Issue by grcann101** [rancher/rancher#14506]
*Describe your issue here*

creating a cluster in Rancher V2.0.4 fails:

Can't pull Docker image [rancher/rke-tools:v0.1.10] for host [18.184.173.73]: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
--
using Rancher AMI: ami-1686b3fd

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
The Docker daemon is telling you it can't reach `registry-1.docker.io`. Can you run `docker pull rancher/rke-tools:v0.1.10` on the machine? Are your security groups setup correctly that it can reach out? Maybe some hick up to DockerHub happened.

I just ran `docker pull rancher/rke-tools:v0.1.10` without issues to confirm the image is present.

**Comment by superseb** [comment]
Don't think we've hit a bug here, but please let me know if you think it is.

**Comment by grcann101** [comment]
I can pull the image from a standard AMI in the same security group without problems, however , this is not working for ami-1686b3fd  (from the aws ami list) which is used in eu-central-1 Frankfurt. This has worked successfully a couple of weeks ago. The rancher os was updated to docker 18.03.1-ce recently 11july18 . Can you create a cluster from the Rancher V2 GUI with this AMI ?
