### ISSUE TITLE
Rancher 2.0 use API from postman

### ISSUE THREAD

**Issue by dommgifer** [rancher/rancher#14505]
**Rancher versions:**
rancher/rancher: 2.0.5

**Result**
Try to send login API by postman, but got error message: "Invalid CSRF token","status":422.

But sometimes,  login success and return token, and then use this token to create cluster,
got same error message:  "Invalid CSRF token","status":422,

Does anyone have any ideas on this?
Thanks!

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/1681#issuecomment-400865472
