### ISSUE TITLE
is there any way to find admin password

### ISSUE THREAD

**Issue by lezi1022** [rancher/rancher#14501]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
unfortunately i forgot admin password, it there any way to find password?

**Results:**

**Comment by superseb** [comment]
Please see this FAQ entry: https://rancher.com/docs/rancher/v1.6/en/faqs/troubleshooting/#help-i-turned-on-access-controldocsrancherv16enconfigurationaccess-control-and-can-no-longer-access-rancher-how-do-i-reset-rancher-to-disable-access-control

**Comment by lezi1022** [comment]
![image](https://user-images.githubusercontent.com/6735666/42624639-6eb87122-85f8-11e8-93c6-c67ca6f0996a.png)

hi,  no api.security.enabled 、api.auth.provider.configured field available

**Comment by superseb** [comment]
What admin password are you referring to? What auth have you got enabled? What is the login screen showing (screenshot)?
