### ISSUE TITLE
Catalog empty with rke deployment with rancher

### ISSUE THREAD

**Issue by Pingbo** [rancher/rancher#14509]
Getting the error "There are no compatible templates." after rolling out a HA Cluster with RKE. Also tried to activate Library, Helm and Helm Incubator but nothing changed.
With an "external" Rancher on native Docker it's working perfectly.

Environment 
OS: Ubuntu 16.04
Docker Version: 18.03.1-ce (also tested with 17.12)
rke Version: 1.8.0 (also tested with 1.7.0)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`catalog-tab.index`|

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/14579
