### ISSUE TITLE
Error messages for Balancer Service are confusing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1450]
![image](https://cloud.githubusercontent.com/assets/11514927/8601591/c24470a0-2621-11e5-8b4d-7069b0f440ce.png)

"sourcePort" is required = Listening Port is required

"Choose one or more targets to send traffic to" & "Service and port are required on each target" - overlap each other.  They both alway come up if I'm missing target source or port.  So there should probably just be the one, or associated each error to a specific field instead of both.

**Comment by vincent99** [comment]
Some new fields are marked required in the API now, so they're getting double-checked.  I moved the specific checks above the generic API validation now and don't call the API validation unless there are no errors.  So you will see just the friendlier-messages, but not necessarily all the errors that are wrong all at once.

**Comment by deniseschannon** [comment]
v0.27.0-rc4 - Verified Fixed that only friendly messages appear.
