### ISSUE TITLE
Failed to communicate with API server: Get https://xxx.xxx.xxx:6443/api/v1/componentstatuses: tunnel disconnect 

### ISSUE THREAD

**Issue by yinfxs** [rancher/rancher#14507]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.2
rancher/agent or rancher/rancher-agent:v2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:Flannel
scheduler:
kubernetes (if applicable):v1.10.1-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-693.2.2.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Aliyun ECS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
Cluster getting to "Unavailable" state:
![image](https://user-images.githubusercontent.com/6890643/42628458-c777c7cc-8602-11e8-9cb2-b1d1469383da.png)

kube-apiserver logs:
![image](https://user-images.githubusercontent.com/6890643/42628464-ccdb6eb2-8602-11e8-8b25-0aceb1a468b6.png)

**Comment by orangedeng** [comment]
Try to use the newest Rancher to test it. I use v2.0.5 and can not reproduce this issue.

**Comment by yinfxs** [comment]
我用的是2.0.2的版本，aliyun ecs driver是Inactive状态

**Comment by gitzhang** [comment]
@yinfxs 你的问题解决了吗？我遇到了一样的问题

**Comment by yinfxs** [comment]
@gitzhang 没有，这问题出现不止一次了，每次不是重启rancher-server就是重启节点，好郁闷…

**Comment by frewillems** [comment]
I am experiencing the same issue. The cluster is stable for about 2 weeks, after that this issue start to appear. I had this 3 times now on 3 different clusters.
