### ISSUE TITLE
Drop k8s 1.8 for cluster creation

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14517]
As k8s has dropped support for k8s 1.8 and Rancher is introducing support for K8s 1.11, we shuold drop k8s 1.8 support as well.

**Comment by superseb** [comment]
Please remove the hardcoded admission controllers for 1.8 in RKE, so that the 1.9/1.10/1.11 get the defaults.

**Comment by soumyalj** [comment]
The following were validated:
1. For fresh install of master ensure no k8sv1.8 versions are displayed 
<img width="446" alt="screen shot 2018-08-07 at 10 39 28 am" src="https://user-images.githubusercontent.com/18536626/43794248-8d8368b6-9a32-11e8-97fe-8f6ce8d283ec.png">
2. Verify no other k8sv1.8 versions(other than the k8s version the cluster is on) are displayed after upgrade to master
<img width="422" alt="screen shot 2018-08-07 at 10 39 43 am" src="https://user-images.githubusercontent.com/18536626/43794269-97dc695c-9a32-11e8-9a7c-f5f676985f9d.png">

3. Verify cluster with k8sv1.8 still works after upgrade
  a. Edit and add more nodes
  b. Edit and add another member
