### ISSUE TITLE
Upgrade button disappear

### ISSUE THREAD

**Issue by wargamez** [rancher/rancher#14519]
Today I experienced a thing upgrading from 1.6.17 to 1.6.18, when in one of my environments I had Ubuntu 16.04 docker hosts that had the wrong HTTP proxy url set for docker itself (ref: https://docs.docker.com/config/daemon/systemd/#custom-docker-daemon-options). When trying to upgrade ipsec (It was showing that there was an upgrade available in the UI after upgrade to 1.6.18) I tried, but it failed due to the wrong proxy stuff. However on rollback of ipsec, the yellow upgrade available message disappeared  and is no longer showing. I'm fooled into thinking I'm running the latest version of ipsec, which it is not :(

**Comment by aemneina** [comment]
Do you have the 'up to date' button showing on the ipsec stack? Can you share a screen shot?

**Comment by wargamez** [comment]
The button was there, but after the fail and rollback it is gone.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
