### ISSUE TITLE
changed workload type after cloning are ignored

### ISSUE THREAD

**Issue by testaccount888** [rancher/rancher#14511]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4
rancher/agent or rancher/rancher-agent: v2.0.4

**Type/provider of hosts:
Profitbricks VM´s

**Setup details:
HA rancher (3 Master Nodes)

**Environment Template: 
Kubernetes

**Steps to Reproduce:**
1. clone a workload with workload type "Scalable deployment"
2. delete original workload
3. change cloned workload type from "Scalable deployment" to "Run one pod on each node"
4. deploy workload

**Results:**
actual -> cloned workload is deployed as "Scalable deployment"
expected -> cloned workload is deployed as "Run one pod on each node"

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/26
Verified fixed
