### ISSUE TITLE
Question: Why do the ipsec containers have a healthcheck configured, but Rancher is configured to do nothing if it fails? (1.6.18) 

### ISSUE THREAD

**Issue by dbsanfte** [rancher/rancher#14510]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.18
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 0.2.4
network-services: 0.2.9
scheduler: 0.8.3-1
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS (4.15.0) (Azure)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Hit Upgrade on the ipsec infrastructure stack and check the Healthcheck tab.

**Results:**

A Healthcheck is configured for ipsec but the action specified for Rancher if the healthcheck fails is "do nothing".

I have seen ipsec containers on hosts become "Unhealthy" and get stuck in that state, with Rancher not doing anything about them, breaking an entire host. I found if I deleted the container and let Rancher recreate it, it would resolve and the ipsec container would become healthy.

I investigated and found that while there is a Healthcheck configured for this service, there is no action specified to resolve unhealthy containers.

Is there a reason for this? 

What might the side effects be of enabling "Recreate" on the ipsec healthcheck?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
