### ISSUE TITLE
Ability to disable default nginx ingress controller

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14516]
Add in the UI option to be able to turn off the default nginx ingress controller.

Backend work needed: If the nginx ingress controller is deployed through RKE and later updated/changed to remove the ingress controller, we do not clean up the ingress controller. 
This is tracked in RKE: https://github.com/rancher/rke/issues/771

**Comment by alena1108** [comment]
UI work is tracked in another ticket. This bug is to keep track of backend/api changes.

**Comment by galal-hussein** [comment]
rancher/rancher:master at july 31th

I was able to test the disable of ingress controller, i can see ingress pods being removed:
```
2018/07/31 19:37:45 [INFO] cluster [c-scw8h] provisioning: [addons] KubeDNS deployed successfully..
2018/07/31 19:37:45 [INFO] cluster [c-scw8h] provisioning: [ingress] removing installed ingress controller
2018/07/31 19:37:52 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [null]
2018/07/31 19:38:40 [INFO] cluster [c-scw8h] provisioning: [ingress] ingress controller removed successfully
2018/07/31 19:38:40 [INFO] cluster [c-scw8h] provisioning: [addons] Setting up user addons
2018/07/31 19:38:40 [INFO] cluster [c-scw8h] provisioning: [addons] no user addons defined
2018/07/31 19:38:40 [INFO] cluster [c-scw8h] provisioning: Finished building Kubernetes cluster successfully
```
