### ISSUE TITLE
wss failed

### ISSUE THREAD

**Issue by xyjwsj** [rancher/rancher#14525]
*Describe your issue here*

time="2018-07-13T07:52:06Z" level=info msg="Connecting to proxy" url="wss://10.1.129.197/v3/connect/register"
time="2018-07-13T07:52:06Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-07-13T07:52:06Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

**Comment by superseb** [comment]
On initial connect, these messages will be logged as well. Can you provide the info requested in the template so there is something we can investigate? Also, the full log of the agent?

**Comment by xyjwsj** [comment]
time="2018-07-13T07:55:52Z" level=info msg="waiting for node to register"
time="2018-07-13T07:55:54Z" level=info msg="waiting for node to register"
time="2018-07-13T07:55:56Z" level=info msg="waiting for node to register"
time="2018-07-13T07:55:58Z" level=info msg="waiting for node to register"
time="2018-07-13T07:56:00Z" level=info msg="waiting for node to register"
time="2018-07-13T07:56:02Z" level=info msg="waiting for node to register"
time="2018-07-13T07:56:04Z" level=info msg="waiting for node to register"
time="2018-07-13T07:56:06Z" level=info msg="waiting for node to register"
time="2018-07-13T07:56:08Z" level=info msg="waiting for node to register"
time="2018-07-13T07:56:10Z" level=info msg="waiting for node to register"
time="2018-07-13T07:56:12Z" level=info msg="waiting for node to register"
time="2018-07-13T07:56:14Z" level=info msg="waiting for node to register"

the container always waiting for node to register

**Comment by superseb** [comment]
This usually means that the cluster does not have a node with the etcd and controlplane role, if you are only adding a single node you have to tick all the roles.

Again, I can only guess, it helps if you provide the exact steps you are taking.

**Comment by superseb** [comment]
Let us know if you need help on this.
