### ISSUE TITLE
Browser terminal error on % character

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#14524]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Client-side: Firefox and Chrome, on Linux

**Steps to Reproduce:**

Open a terminal for a pod and enter `%`. The character is not sent to the remote process and the following error is logged on the web browser (Chrome output shown, same backtrace on Firefox):

```
Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at y.<anonymous> (component.js:108)
    at y.e.emit (EventEmitter.js:49)
    at y.handler (xterm.js:1432)
    at y.keyPress (xterm.js:1240)
    at HTMLTextAreaElement.<anonymous> (xterm.js:368)
```

A search of the `xterm.js` issue queue came up empty. Perhaps this is either A) a new bug or B) something unique in Rancher's implementation?

**Comment by bradjones1** [comment]
FWIW this also appears to error when reading a `%` character to the browser, e.g., from a file on the pod using `cat`.

**Comment by superseb** [comment]
Can you share what versions you are using (Linux/Chrome/Firefox)?

**Comment by bradjones1** [comment]
Firefox `60.0.2`
Chrome `67.0.3396.99`
```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

**Comment by vincent99** [comment]
This was fixed in https://github.com/rancher/ui/pull/2003 for 2.0.6.

**Comment by bradjones1** [comment]
@vincent99 Thanks... didn't realize there was a separate repo for the UI.

**Comment by vincent99** [comment]
Most things have their own individual repos, but issues all go here in rancher/rancher except for very standalone things (e.g. rancheros).
