### ISSUE TITLE
Rancher doesn't connect to locally installed elasticsearch server

### ISSUE THREAD

**Issue by angheladrianclaudiu** [rancher/rancher#14529]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4
rancher/agent or rancher/rancher-agent: v2.0.4

**Docker version:**
17.3.2
**Operating system and kernel:**
Ubuntu 16.04 4.4.0-127-generic
**Type/provider of hosts: **
Digital Ocean and AWS
**Setup details:**
Single node Rancher with 4GB RAM
**Environment Template:**
Kubernetes
**Steps to Reproduce:**
Installed Elasticsearch and Kibana as 2 separate Docker containers running on the same server as Rancher (Rancher is also started as a Docker container)
**Results:**
I am trying to connect to Elasticsearch via Docker Gateway http://172.18.0.1:9200, I can save the configuration, but Rancher tells me that the url is unreachable:

  | Url 172.18.0.1:9200 unreachable, error: dial tcp 172.18.0.1:9200: i/o timeout |  
Also, I couldn't find any docs regarding Elasticsearch setup on website: https://rancher.com/docs/rancher/v2.x/en/tasks/logging/

Any idea how to make it collect logs and send them to elasticsearch?

**Comment by kaybinwong** [comment]
same to me, bug?

**Comment by soluty** [comment]
same to me, @angheladrianclaudiu  has you solve this?

**Comment by loganhz** [comment]
Thanks for the report

It will be fixed in 2.2 with https://github.com/rancher/rancher/issues/13785

You can find the workaround for this issue via https://github.com/rancher/rancher/issues/13785#issuecomment-428205996
