### ISSUE TITLE
RAM and CPU increases in 4-5h to almost 100%

### ISSUE THREAD

**Issue by angheladrianclaudiu** [rancher/rancher#14526]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4
rancher/agent or rancher/rancher-agent: v2.0.4

**Docker version:**
17.3.2
**Operating system and kernel:**
Ubuntu 16.04 4.4.0-127-generic
**Type/provider of hosts: **
Digital Ocean and AWS
**Setup details:**
Single node Rancher with 4GB RAM
**Environment Template:**
Kubernetes
**Steps to Reproduce:**
Installed Rancher with this command:
docker run -d --restart=unless-stopped -p 8080:80 --name rancher-server rancher/rancher
Just use the provisioned Kubernetes cluster normally with pod deployments done from Spinnaker.
**Results:**
RAM and CPU increases in 4-5h to almost 100%
See the link: https://postimg.cc/image/mgvkglvsb/
Any idea why?

**Comment by superseb** [comment]
Thanks for the report, merging into https://github.com/rancher/rancher/issues/14356
