### ISSUE TITLE
Browser gets stuck while Viewing huge logs using rancher's "view logs" operation.

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#14535]
**Rancher versions:**
rancher/rancher:v2.0.4
rancher/rancher-agent:v2.0.4

**Infrastructure Stack versions:**
kubernetes:v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
````bash
Containers: 23
 Running: 20
 Paused: 0
 Stopped: 3
Images: 16
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /app/var_lib_docker/aufs
 Backing Filesystem: extfs
 Dirs: 153
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: k8s-worker0-testlink
ID: Z5OF:24ZF:FRHZ:EGTN:5F2U:R4PB:H4EU:BCUX:DMP2:EIBX:C2YK:X2OW
Docker Root Dir: /app/var_lib_docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://8jijd8fz.mirror.aliyuncs.com
Live Restore Enabled: false

WARNING: No swap limit support
````
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-116-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
If a pod produces many many logs, then use the rancher's view logs operation.
**Results:**
My browser gets stuck.  All I can do is closing the rancher web page forcibly.

**Comment by oskapt** [comment]
Rancher v1 handled this differently. When viewing logs through the browser, it would start at some reasonable number of lines back from the current position (100? 500?). Rancher v2 appears to show _all_ logs from the start of the container (or at least from the start of the available logs). For long-running or chatty containers, this can result in megabytes of garbage data being streamed to the browser.  I propose that this be classified as a bug in v2.

**Comment by loganhz** [comment]
Both of Rancher 1.6 and 2.0 show last 500 lines. https://github.com/rancher/ui/blob/master/app/components/container-logs/component.js#L11

**Comment by deniseschannon** [comment]
@loganhz is this a change that was recently added? is there a reason why v2.0.4 would be hitting this?

**Comment by westlywright** [comment]
@deniseschannon @loganhz we're still passing the `tailLines` flag to the cluster api on https://github.com/rancher/ui/blob/master/app/components/container-logs/component.js#L97

**Comment by loganhz** [comment]
I guess if container generates thousands of logs in few minutes, then it might be a problem.

The following is the comment from Vince.
```
Yes, but if you're getting that much you want to stop the scrolling and read some of it.. but if you drop a line off the top when a new one comes in to the bottom then any given line keeps sliding up and you can't read them
1.x never limited it and I don't know of any complaints.. if we had to do something about it, I'd probably want to do sliding-window rendering, where you keep all the text in memory but only render a fixed number of lines that are visible on the screen and change what those lines are based on the scroll position.  (but that requires fixed-height lines so you'd have to turn that mode on when it got to x,000 lines and disable line-wrapping)
```

**Comment by loganhz** [comment]
Steps to reproduce

1. Create a workload with image `liuyan/producelog:v3`
2. View the log of the pod.

**Comment by happyyangyuan** [comment]
@loganhz Thanks for your image. My safari still gets stuck due to fast log printing.

**Comment by loganhz** [comment]
@happyyangyuan it's not released. It will be out in 2.1

**Comment by loganhz** [comment]
Given the same backend, I can reproduce this issue with old UI but can not reproduce it with the current UI on my laptop. I guess it is much better now. 

@happyyangyuan It will be great if you can try `rancher/rancher:master` and deploy the workload with image `liuyan/producelog:v3`.

**Comment by rootwuj** [comment]
Version -2.1 master 9/4
Verified fixed

**Comment by eltomjan** [comment]
In case someone wants complete (RAW) logs or different # of rows, this bookmarklet can help from POD page (asks for number of lines and get RAW data this windows reads, enter is "unlimitted", but in fact big number works better):
javascript:t=prompt('Tail ?');t=(t?'&tailLines='+t:'');window.open('https://10.58.24.60/k8s/clusters/'+location.href.split(':')[1].split('/')[4]+'/api/v1/namespaces/web/pods/'+location.href.split(':')[3]+'/log?follow=false'+t)

**Comment by eltomjan** [comment]
In case someone wants complete (RAW) logs or different # of rows, this bookmarklet can help from POD page (asks for number of lines and get RAW data this windows reads, enter is "unlimitted", but in fact big number works better):
var t=prompt('Tail ?');t=(t?'&tailLines='+t:'');window.open(location.origin+'/k8s/clusters/'+location.href.split(':')[1].split('/')[4]+'/api/v1/namespaces/web/pods/'+location.href.split(':')[3]+'/log?follow=false'+t)

**Comment by eltomjan** [comment]
And for coloring of open ANSI text use this bookmarklet:
javascript:var oReq = new XMLHttpRequest();oReq.open("GET", "https"+"://raw.githubusercontent.com/drudru/ansi_up/master/ansi_up.js", true);oReq.onloadend = function (oEvent) {new Function(oReq.responseText)();var el=document.getElementsByTagName("PRE")[0];el.innerHTML=(new AnsiUp).ansi_to_html(el.innerText);};oReq.send();undefined

**Comment by eltomjan** [comment]
For newer Rancher there is different path and bookmarklet must be activated from particular container page.
javascript:t=prompt('Tail ?');t=(t?'&tailLines='+t:'');window.open('https://10.58.24.60/k8s/clusters/'+location.href.split(':')[1].split('/')[4]+'/api/v1/namespaces/fission-function/pods/'+location.href.split(':')[3].replace(/(.+)\/(.+)\//g,'$1/log?$2=')+'&follow=false'+t)
