### ISSUE TITLE
Secret name cannot be changed using rancher 

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#14534]
**Rancher versions:**
rancher/rancher:v2.0.4
rancher/rancher-agent:v2.0.4

**Infrastructure Stack versions:**
kubernetes:v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
````bash
Containers: 23
 Running: 20
 Paused: 0
 Stopped: 3
Images: 16
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /app/var_lib_docker/aufs
 Backing Filesystem: extfs
 Dirs: 153
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: k8s-worker0-testlink
ID: Z5OF:24ZF:FRHZ:EGTN:5F2U:R4PB:H4EU:BCUX:DMP2:EIBX:C2YK:X2OW
Docker Root Dir: /app/var_lib_docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://8jijd8fz.mirror.aliyuncs.com
Live Restore Enabled: false

WARNING: No swap limit support
````
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-116-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Edit any secret no matter it is used by workloads or not, rancher prompts a success on renaming. But I refresh the rancher web page, the old name is back.
**Results:**
I cannot change the secret name using rancher ui.

**Comment by happyyangyuan** [comment]
A trick way is to add a new secret and then delete the old one.

**Comment by superseb** [comment]
Editing the name is blocked in v2.0.6.
