### ISSUE TITLE
Rancher-generated labels must not be cloned when cloning a workload.

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#14537]
**Rancher versions:**
rancher/rancher:v2.0.4
rancher/rancher-agent:v2.0.4

**Steps to Reproduce:**
Use rancher UI's workload "Clone" operation, the rancher-generated labels are all cloned which is not I expected:
````
workload.user.cattle.io/workloadselector
etc.
````
**Results:**
Mixed labels for different workloads.

**Comment by superseb** [comment]
Fixed in v2.0.5: https://github.com/rancher/rancher/issues/14034
