### ISSUE TITLE
Workload scaling operation removes the workload's old pods .

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#14533]
**Rancher versions:**
rancher/rancher:v2.0.4
rancher/rancher-agent:v2.0.4

**Infrastructure Stack versions:**
kubernetes:v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
````bash
Containers: 23
 Running: 20
 Paused: 0
 Stopped: 3
Images: 16
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /app/var_lib_docker/aufs
 Backing Filesystem: extfs
 Dirs: 153
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: k8s-worker0-testlink
ID: Z5OF:24ZF:FRHZ:EGTN:5F2U:R4PB:H4EU:BCUX:DMP2:EIBX:C2YK:X2OW
Docker Root Dir: /app/var_lib_docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://8jijd8fz.mirror.aliyuncs.com
Live Restore Enabled: false

WARNING: No swap limit support
````
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-116-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
<img width="1245" alt="scalingworkloadcausespodremoved" src="https://user-images.githubusercontent.com/9134975/42693890-25802680-86e3-11e8-82f1-866f65b257aa.png">

**Results:**
Old pods are all removed! Shown as above.

**Comment by superseb** [comment]
Are the pods created using the UI or `kubectl`?

**Comment by happyyangyuan** [comment]
Pods are created using UI of Rancher.

**Comment by superseb** [comment]
Probably hitting https://github.com/rancher/rancher/issues/14171, can you try v2.0.6 and see if you still encounter it? Let me know so I can re-open if it's still a bug.

**Comment by happyyangyuan** [comment]
I just found out that workload's default imagePullPolicy is 'Always' and this causes the issue. It is solved after I change the imagePullPolicy to 'IfNotPresent'.
