### ISSUE TITLE
Appending words to the tail of the configmap's key field causes the old key been over written!

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#14536]
**Rancher versions:**
rancher/rancher:v2.0.4
rancher/rancher-agent:v2.0.4

**Steps to Reproduce:**
Edit the configmap, and paste a word at the end of the configmap key field 
**Results:**
The old key is over written instead of appended!

**Comment by superseb** [comment]
Can you describe in more detail what steps you are executing (steps to reproduce), what you are expecting and what you are seeing instead? As asked in the template or https://rancher.com/docs/rancher/v2.x/en/faq/contributing/#bugs-issues-or-questions

**Comment by happyyangyuan** [comment]
<img width="1242" alt="paste words at the end of the key" src="https://user-images.githubusercontent.com/9134975/42696603-450f363c-86eb-11e8-846f-77e168cc0406.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
