### ISSUE TITLE
translation 

### ISSUE THREAD

**Issue by vanackgpro** [rancher/rancher#14531]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4
rancher/agent or rancher/rancher-agent: v2.0.4

Replace french translation of delete "supprimmer" by "supprimer"

![image](https://user-images.githubusercontent.com/33347202/42693426-5c0658ca-86af-11e8-8272-b956fc855fe0.png)

**Comment by superseb** [comment]
Thanks for your report, would you mind filing a suggestion at http://translate.rancher.com/. This is where the translations are kept, and are synced periodically.
