### ISSUE TITLE
ipsec container flapping in a set up with large number of hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14546]
**Rancher versions: v1.6.19-rc5 ( upgraded from fresh install of v1.6.18 with 30 hosts)

**Steps to Reproduce:**
Fresh install of v1.6.18 with 30 hosts.
Deployed 300 health check enabled instances.
Upgraded to v1.6.19-rc5 .
Upgrade all the infra stack including ipsec.
Added 5 more hosts.

After a while , I see that ipsec containers keep flapping from becoming "healthy"->"unhealthy"

**Comment by leodotcloud** [comment]
May be related: https://github.com/rancher/rancher/issues/8505

Notes:
- there is a lot of network traffic from the node and the rancher/server
- metadata is constantly reloading, the version is changing every second
- may be the failing healthchecks trigger the metadata reload and that's adding fuel to the fire?

**Comment by leodotcloud** [comment]
@kinarashah @alena1108 is it possible to do some kind of rate limiting to prevent the fast metadata version updates on cattle side for flapping ipsec healthchecks?

**Comment by sangeethah** [comment]
Fresh install of v1.6.18 with 30 hosts.
Deployed 300 health check enabled instances.
Upgraded to v1.6.19-rc5 .
Upgrade all the infra stack including ipsec.
Added 5 more hosts.
Did not see ipsec containers becoming "unhealthy". 
Monitored the setup for 4 -5 hours.
At this point, ipsec.service.enable.healthcheck is disabled.
Make ipsec.service.enable.healthcheck  enabled by setting it to "true.
Will be leaving the setup around for 12 hours and check if there were no DOWN events reported for ipsec instances.
