### ISSUE TITLE
Flannel CNI always fail if node not in the masterplane subnet

### ISSUE THREAD

**Issue by alexey-kruchenok** [rancher/rancher#14545]
**Rancher versions:**
rancher/rancher: 2.0.6
**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos 7.5
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Baremetal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Cluster with masterplane on AWS Frankfurt
1 - node on AWS Frankfurt (working)
1- node on AWS Oregon (fail)
1- node on Hetzner (fail)
**Steps to Reproduce:**
Create cluster on aws in selected region with Flannel CNI, 
make security group open to the world, 
add masterplane+etcd node, add worker node at same region.
Add any daemonset workload - like busybox:1.28.4-musl, so far everything fine. 
Add node from different AWS region or from different cloud provider.
**Results:**

Nodes from other regions  started and added to the cluster without any sign of errors, but when workload is deployed, it crashes right after deploymebt.

When i look into  Flannel pod, i found that it exited with message:

I0714 00:07:23.812548       1 main.go:474] Determining IP address of default interface
I0714 00:07:23.813108       1 main.go:487] Using interface with name eth0 and address 172.31.8.205
I0714 00:07:23.813129       1 main.go:504] Defaulting external address to interface address (172.31.8.205)
E0714 00:07:53.814714       1 main.go:231] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-v24df': Get https://10.43.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-v24df: dial tcp 10.43.0.1:443: i/o timeout

And daemonset workload keep crashing on this node.

**Comment by alexey-kruchenok** [comment]
Looks like kube-proxy not working properly

+ echo kube-proxy --v=2 --healthz-bind-address=0.0.0.0 --cluster-cidr=10.42.0.0/16 --hostname-override=ip-172-31-8-205 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml
+ grep -q cloud-provider=azure
+ '[' kube-proxy = kubelet ']'
+ exec kube-proxy --v=2 --healthz-bind-address=0.0.0.0 --cluster-cidr=10.42.0.0/16 --hostname-override=ip-172-31-8-205 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml
I0713 23:41:41.393800   30648 flags.go:27] FLAG: --allow-verification-with-non-compliant-keys="false"
I0713 23:41:41.393845   30648 flags.go:27] FLAG: --alsologtostderr="false"
I0713 23:41:41.393851   30648 flags.go:27] FLAG: --application-metrics-count-limit="100"
I0713 23:41:41.393856   30648 flags.go:27] FLAG: --azure-container-registry-config=""
I0713 23:41:41.393863   30648 flags.go:27] FLAG: --bind-address="0.0.0.0"
I0713 23:41:41.393870   30648 flags.go:27] FLAG: --boot-id-file="/proc/sys/kernel/random/boot_id"
I0713 23:41:41.393879   30648 flags.go:27] FLAG: --cleanup="false"
I0713 23:41:41.393886   30648 flags.go:27] FLAG: --cleanup-iptables="false"
I0713 23:41:41.393891   30648 flags.go:27] FLAG: --cleanup-ipvs="true"
I0713 23:41:41.393895   30648 flags.go:27] FLAG: --cloud-provider-gce-lb-src-cidrs="130.211.0.0/22,209.85.152.0/22,209.85.204.0/22,35.191.0.0/16"
I0713 23:41:41.393915   30648 flags.go:27] FLAG: --cluster-cidr="10.42.0.0/16"
I0713 23:41:41.393920   30648 flags.go:27] FLAG: --config=""
I0713 23:41:41.393926   30648 flags.go:27] FLAG: --config-sync-period="15m0s"
I0713 23:41:41.393933   30648 flags.go:27] FLAG: --conntrack-max="0"
I0713 23:41:41.393950   30648 flags.go:27] FLAG: --conntrack-max-per-core="32768"
I0713 23:41:41.393955   30648 flags.go:27] FLAG: --conntrack-min="131072"
I0713 23:41:41.393959   30648 flags.go:27] FLAG: --conntrack-tcp-timeout-close-wait="1h0m0s"
I0713 23:41:41.393964   30648 flags.go:27] FLAG: --conntrack-tcp-timeout-established="24h0m0s"
I0713 23:41:41.393969   30648 flags.go:27] FLAG: --container-hints="/etc/cadvisor/container_hints.json"
I0713 23:41:41.393974   30648 flags.go:27] FLAG: --containerd="unix:///var/run/containerd.sock"
I0713 23:41:41.393980   30648 flags.go:27] FLAG: --default-not-ready-toleration-seconds="300"
I0713 23:41:41.393985   30648 flags.go:27] FLAG: --default-unreachable-toleration-seconds="300"
I0713 23:41:41.393991   30648 flags.go:27] FLAG: --docker="unix:///var/run/docker.sock"
I0713 23:41:41.393996   30648 flags.go:27] FLAG: --docker-env-metadata-whitelist=""
I0713 23:41:41.394002   30648 flags.go:27] FLAG: --docker-only="false"
I0713 23:41:41.394006   30648 flags.go:27] FLAG: --docker-root="/var/lib/docker"
I0713 23:41:41.394011   30648 flags.go:27] FLAG: --docker-tls="false"
I0713 23:41:41.394017   30648 flags.go:27] FLAG: --docker-tls-ca="ca.pem"
I0713 23:41:41.394021   30648 flags.go:27] FLAG: --docker-tls-cert="cert.pem"
I0713 23:41:41.394026   30648 flags.go:27] FLAG: --docker-tls-key="key.pem"
I0713 23:41:41.394031   30648 flags.go:27] FLAG: --enable-load-reader="false"
I0713 23:41:41.394035   30648 flags.go:27] FLAG: --event-storage-age-limit="default=0"
I0713 23:41:41.394041   30648 flags.go:27] FLAG: --event-storage-event-limit="default=0"
I0713 23:41:41.394051   30648 flags.go:27] FLAG: --feature-gates=""
I0713 23:41:41.394064   30648 flags.go:27] FLAG: --global-housekeeping-interval="1m0s"
I0713 23:41:41.394069   30648 flags.go:27] FLAG: --google-json-key=""
I0713 23:41:41.394073   30648 flags.go:27] FLAG: --healthz-bind-address="0.0.0.0"
I0713 23:41:41.394079   30648 flags.go:27] FLAG: --healthz-port="10256"
I0713 23:41:41.394083   30648 flags.go:27] FLAG: --help="false"
I0713 23:41:41.394088   30648 flags.go:27] FLAG: --hostname-override="ip-172-31-8-205"
I0713 23:41:41.394093   30648 flags.go:27] FLAG: --housekeeping-interval="10s"
I0713 23:41:41.394097   30648 flags.go:27] FLAG: --iptables-masquerade-bit="14"
I0713 23:41:41.394102   30648 flags.go:27] FLAG: --iptables-min-sync-period="0s"
I0713 23:41:41.394106   30648 flags.go:27] FLAG: --iptables-sync-period="30s"
I0713 23:41:41.394112   30648 flags.go:27] FLAG: --ipvs-min-sync-period="0s"
I0713 23:41:41.394116   30648 flags.go:27] FLAG: --ipvs-scheduler=""
I0713 23:41:41.394120   30648 flags.go:27] FLAG: --ipvs-sync-period="30s"
I0713 23:41:41.394124   30648 flags.go:27] FLAG: --ir-data-source="influxdb"
I0713 23:41:41.394129   30648 flags.go:27] FLAG: --ir-dbname="k8s"
I0713 23:41:41.394133   30648 flags.go:27] FLAG: --ir-hawkular=""
I0713 23:41:41.394137   30648 flags.go:27] FLAG: --ir-influxdb-host="localhost:8080/api/v1/namespaces/kube-system/services/monitoring-influxdb:api/proxy"
I0713 23:41:41.394143   30648 flags.go:27] FLAG: --ir-namespace-only="false"
I0713 23:41:41.394147   30648 flags.go:27] FLAG: --ir-password="root"
I0713 23:41:41.394151   30648 flags.go:27] FLAG: --ir-percentile="90"
I0713 23:41:41.394155   30648 flags.go:27] FLAG: --ir-user="root"
I0713 23:41:41.394160   30648 flags.go:27] FLAG: --kube-api-burst="10"
I0713 23:41:41.394164   30648 flags.go:27] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0713 23:41:41.394169   30648 flags.go:27] FLAG: --kube-api-qps="5"
I0713 23:41:41.394176   30648 flags.go:27] FLAG: --kubeconfig="/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml"
I0713 23:41:41.394181   30648 flags.go:27] FLAG: --log-backtrace-at=":0"
I0713 23:41:41.394188   30648 flags.go:27] FLAG: --log-cadvisor-usage="false"
I0713 23:41:41.394192   30648 flags.go:27] FLAG: --log-dir=""
I0713 23:41:41.394197   30648 flags.go:27] FLAG: --log-flush-frequency="5s"
I0713 23:41:41.394201   30648 flags.go:27] FLAG: --loglevel="1"
I0713 23:41:41.394205   30648 flags.go:27] FLAG: --logtostderr="true"
I0713 23:41:41.394209   30648 flags.go:27] FLAG: --machine-id-file="/etc/machine-id,/var/lib/dbus/machine-id"
I0713 23:41:41.394215   30648 flags.go:27] FLAG: --masquerade-all="false"
I0713 23:41:41.394219   30648 flags.go:27] FLAG: --master=""
I0713 23:41:41.394223   30648 flags.go:27] FLAG: --metrics-bind-address="127.0.0.1:10249"
I0713 23:41:41.394227   30648 flags.go:27] FLAG: --nodeport-addresses="[]"
I0713 23:41:41.394239   30648 flags.go:27] FLAG: --oom-score-adj="-999"
I0713 23:41:41.394243   30648 flags.go:27] FLAG: --profiling="false"
I0713 23:41:41.394248   30648 flags.go:27] FLAG: --proxy-mode=""
I0713 23:41:41.394254   30648 flags.go:27] FLAG: --proxy-port-range=""
I0713 23:41:41.394261   30648 flags.go:27] FLAG: --resource-container="/kube-proxy"
I0713 23:41:41.394266   30648 flags.go:27] FLAG: --stderrthreshold="2"
I0713 23:41:41.394270   30648 flags.go:27] FLAG: --storage-driver-buffer-duration="1m0s"
I0713 23:41:41.394275   30648 flags.go:27] FLAG: --storage-driver-db="cadvisor"
I0713 23:41:41.394279   30648 flags.go:27] FLAG: --storage-driver-host="localhost:8086"
I0713 23:41:41.394283   30648 flags.go:27] FLAG: --storage-driver-password="root"
I0713 23:41:41.394288   30648 flags.go:27] FLAG: --storage-driver-secure="false"
I0713 23:41:41.394292   30648 flags.go:27] FLAG: --storage-driver-table="stats"
I0713 23:41:41.394296   30648 flags.go:27] FLAG: --storage-driver-user="root"
I0713 23:41:41.394300   30648 flags.go:27] FLAG: --udp-timeout="250ms"
I0713 23:41:41.394305   30648 flags.go:27] FLAG: --v="2"
I0713 23:41:41.394309   30648 flags.go:27] FLAG: --version="false"
I0713 23:41:41.394317   30648 flags.go:27] FLAG: --vmodule=""
I0713 23:41:41.394322   30648 flags.go:27] FLAG: --write-config-to=""
W0713 23:41:41.394402   30648 server.go:195] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I0713 23:41:41.394814   30648 feature_gate.go:226] feature gates: &{{} map[]}
I0713 23:41:41.406619   30648 iptables.go:198] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
time="2018-07-13T23:41:41Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.0-862.3.2.el7.x86_64/modules.dep.bin'\nmodprobe: WARNING: Module ip_vs not found in directory /lib/modules/3.10.0-862.3.2.el7.x86_64`, error: exit status 1"
time="2018-07-13T23:41:41Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."
W0713 23:41:41.423333   30648 server_others.go:290] Can't use ipvs proxier, trying iptables proxier
I0713 23:41:41.424433   30648 server_others.go:140] Using iptables Proxier.
W0713 23:41:41.430606   30648 server.go:601] Failed to retrieve node info: Get https://127.0.0.1:6443/api/v1/nodes/ip-172-31-8-205: dial tcp 127.0.0.1:6443: getsockopt: connection refused
W0713 23:41:41.430677   30648 proxier.go:306] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
I0713 23:41:41.430767   30648 server_others.go:174] Tearing down inactive rules.
I0713 23:41:41.481495   30648 server.go:444] Version: v1.10.3
I0713 23:41:41.495414   30648 server.go:470] Running in resource-only container "/kube-proxy"
I0713 23:41:41.501107   30648 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0713 23:41:41.501157   30648 conntrack.go:52] Setting nf_conntrack_max to 131072
I0713 23:41:41.501733   30648 mount_linux.go:196] Detected OS without systemd
I0713 23:41:41.501892   30648 conntrack.go:83] Setting conntrack hashsize to 32768
I0713 23:41:41.505576   30648 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0713 23:41:41.505623   30648 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0713 23:41:41.506017   30648 config.go:102] Starting endpoints config controller
I0713 23:41:41.506038   30648 controller_utils.go:1019] Waiting for caches to sync for endpoints config controller
I0713 23:41:41.506059   30648 config.go:202] Starting service config controller
I0713 23:41:41.506064   30648 controller_utils.go:1019] Waiting for caches to sync for service config controller
E0713 23:41:41.507694   30648 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Endpoints: Get https://127.0.0.1:6443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: getsockopt: connection refused
E0713 23:41:41.507750   30648 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Service: Get https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: getsockopt: connection refused
E0713 23:41:41.507941   30648 event.go:209] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: dial tcp 127.0.0.1:6443: getsockopt: connection refused' (may retry after sleeping)
I0713 23:41:43.206261   30648 controller_utils.go:1026] Caches are synced for service config controller
I0713 23:41:43.206332   30648 proxier.go:623] Not syncing iptables until Services and Endpoints have been received from master
I0713 23:41:43.406290   30648 controller_utils.go:1026] Caches are synced for endpoints config controller
I0713 23:41:43.406428   30648 service.go:310] Adding new service port "intranet-webapp/ingress-19874b2f859873394f4f3150d7a90ff0:" at 10.43.91.160:8080/TCP
I0713 23:41:43.406453   30648 service.go:310] Adding new service port "kube-system/kube-dns:dns" at 10.43.0.10:53/UDP
I0713 23:41:43.406467   30648 service.go:310] Adding new service port "kube-system/kube-dns:dns-tcp" at 10.43.0.10:53/TCP
I0713 23:41:43.406477   30648 service.go:310] Adding new service port "default/kubernetes:https" at 10.43.0.1:443/TCP
I0713 23:41:43.406489   30648 service.go:310] Adding new service port "ingress-nginx/default-http-backend:" at 10.43.83.237:80/TCP
I0713 23:41:43.406499   30648 service.go:310] Adding new service port "intranet-webapp/kassa:8080tcp02" at 10.43.213.213:8080/TCP
I0713 23:41:43.406562   30648 proxier.go:637] Stale udp service kube-system/kube-dns:dns -> 10.43.0.10
I0713 23:41:43.449450   30648 proxier.go:1372] Opened local port "nodePort for intranet-webapp/ingress-19874b2f859873394f4f3150d7a90ff0:" (:32493/tcp)
E0714 00:22:38.989124   30648 proxier.go:1285] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 70 failed
)
I0714 00:22:38.989156   30648 proxier.go:1287] Closing local ports after iptables-restore failure

**Comment by GoWebProd** [comment]
any news? I have same problem

```
I0901 22:22:17.455244       1 main.go:474] Determining IP address of default interface
I0901 22:22:17.456007       1 main.go:487] Using interface with name eth0 and address 185.143.172.235
I0901 22:22:17.456037       1 main.go:504] Defaulting external address to interface address (185.143.172.235)
E0901 22:22:47.461760       1 main.go:231] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-x6zkx': Get https://10.43.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-x6zkx: dial tcp 10.43.0.1:443: i/o timeout
```
