### ISSUE TITLE
Don't write to host volumes without my knowledge/permission.

### ISSUE THREAD

**Issue by MicahZoltu** [rancher/rancher#14547]
**Rancher versions:**
rancher/server or rancher/rancher: `d41d39f8dd65`
rancher/agent or rancher/rancher-agent: `3571bad91a6b` `2.0.6`

**Infrastructure Stack versions:**
healthcheck: ?
ipsec: ?
network-services: ?
scheduler: ?
kubernetes (if applicable): ?

**Docker version: (`docker version`,`docker info` preferred)**
`18.03.1-ce`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Defaults (following tutorial)

**Steps to Reproduce:**
Follow the steps from documentation to install Rancher single server.

**Results:**
Rancher agent wants a mount to `/etc/kubernetes`.  If you change this to point somewhere else it doesn't work.  This is because the other rancher containers that are started also point at this directory and write to it.  This means docker containers are writing things to disk on my host without my knowledge.  What else do they write to disk?  Where else do they write it?

A big selling point of Docker is that my host remains in a pristine state.  I have all of my docker volume mounts in one folder so it is easy to keep track of where my persisted files are at and when I want to reset a host back to a pristine state I just do
```
docker container rm -f `docker container list -aq`
rm -rf /path/to/docker-volumes
```
However, with Rancher writing files all over my local disk this doesn't actually put me back to a pristine state, and in fact I don't know what state my host is in because Rancher is writing files that I don't know about.

Rancher should be using `--volumes-from` if it wants multiple containers to share disk, and if persistence is desired it should be part of a volume mount in a command that I manually run, not something that is automatically mounted.  When I tried redirecting the `/etc/kubernetes` volume mount found in the agent run command setup failed.

**Comment by MicahZoltu** [comment]
Ugh, just found a bunch more stuff in `/var/lib`.  I'm probably going to have to nuke this whole box to get it clean.

**Comment by nosovk** [comment]
```
docker rm -f $(docker ps -qa)
docker volume rm $(docker volume ls -q)
cleanupdirs="/var/lib/etcd /etc/kubernetes /etc/cni /opt/cni /var/lib/cni /var/run/calico"
for dir in $cleanupdirs; do
  echo "Removing $dir"
  sudo rm -rf $dir
done
```

Yob can't avoid system pollution running kubernetis :(
You directly use unsafe params to allow writing from docker to yours system.

**Comment by MicahZoltu** [comment]
Ugh, is Kubernetes the one that is doing this, not rancher?  I generally don't mind giving `:ro` access to docker containers to the host, for example `/var/docker.sock:/var/docker.sock:ro` so it can manage things.

If this is a Kebernetes thing, does that mean Rancher 1.6 doesn't have this problem?

**Comment by superseb** [comment]
You can find all changes done to the system in https://github.com/rancher/docs/pull/430. Probably we can make the `/etc/kubernetes` part variable and recognize a Docker volume, but if the goal is to have everything in Docker volumes you will see that other containers (i.e. CNI pods) also mount host volumes which are out of our control.

**Comment by MicahZoltu** [comment]
What is the reason for having all of the volumes spread out across the OS?  Why not put them all into a single location that the user can specify when they spin up?  For example, if I start the agent with
```
docker container run ... -v /my/path/rancher:/var/rancher --name rancher-agent rancher/rancher-agent
```
the agent can then launch its containers behind the scenes with
```
docker container run ... --volumes-from rancher-agent --name rancher-kubernetes rancher/kubernetes
```
This way, `rancher-kubernetes` will get `/var/rancher` from `rancher-agent`, thus inheriting its mount point and the two will share a volume.  It can then (inside the docker image) have a sym link from `/var/kubernetes` to `/var/rancher/kubernetes` (or `/etc/cni` to `/var/rancher/cni` or whatever it needs).

Such a strategy would allow me (the user) to specify where I want the entire Rancher system to put things on disk when I launch `rancher-agent`, even though `rancher-agent` is launching containers later that will actually write things to disk.

Alternatively, a not quite as good solution (IMO) but still better than current would be to make it so the user mounts all of the current directories to rancher-agent, then each of the Rancher system containers rancher-agent spins up would `--volumes-from rancher-agent` thus getting the mount points as they are.  The nice part about this solution is that it is probably less engineering work as you wouldn't need to modify any of the system images, just change the docker commands that the agent issues to launch system containers.  The rancher-agent launch command that is presented to the user can default to the set of paths being used now including `/var/lib/etcd`, `/etc/kubernetes`, `/etc/cni`, etc. but this gives end-users a path to redirect all of that to known locations, and it also informs the new user about what locations on disk are going to be touched.

----

With the current strategy, as a user I am afraid that even if I get a list of paths today, a future update will add new paths without me knowing it.  This fear stems from the fact that (at the moment) Rancher does put things on my disk automatically, which suggests that in the future it may put more things on my disk without my knowledge.  Also, in my experience once the number of paths that some tool/system uses exceeds about 3 or 4 it quickly becomes difficult to track all of the files on disk (particularly if the development team is more than a few people).

**Comment by MicahZoltu** [comment]
Hmm, thanks for the detailed response.

Perhaps my problem is that I don't really _want_ to run Kubernetes, I just want a Rancher 1.6 or Docker Cloud style docker container management UI.  Kubernetes is this big behemoth of a thing that I don't understand nor have the time/inclination to understand when all I want is a place to start/stop/upgrade my containers and monitor basic host and container performance metrics.

Am I correct in believing that the plan is, long term, to sunset 1.6 and the Rancher line will continue forward with Kubernetes?  Maybe I should just rollback to 1.6, with its simpler system and hope that the Kubernetes exuberance dies off.  😛

**Comment by vincent99** [comment]
2.0 is all kubernetes.  1.6 will have maintenance releases through May of 2019 as needed.

**Comment by superseb** [comment]
Documentation is now up https://rancher.com/docs/rancher/v2.x/en/installation/removing-rancher/cleaning-cluster-nodes/, let us know if you have any other questions.
