### ISSUE TITLE
Rancher 2.0.6 leaves lots of defunct processes

### ISSUE THREAD

**Issue by tboemker-bkfs** [rancher/rancher#14553]
On the machine running the rancher server, I see lots of zombie processes:

0 Z root       396 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root       930 16659  0  80   0 -     0 do_exi 05:56 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1097 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1215 16659  0  80   0 -     0 do_exi 09:23 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1258 16659  0  80   0 -     0 do_exi 02:33 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1601 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1626 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1670 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1742 16659  0  80   0 -     0 do_exi 06:01 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1796 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      1951 16659  0  80   0 -     0 do_exi 09:27 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      2335 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      2345 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      2409 16659  0  80   0 -     0 do_exi 06:06 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      2475 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      2670 16659  0  80   0 -     0 do_exi 09:32 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      3086 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      3431 16659  0  80   0 -     0 do_exi 09:37 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      3481 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>
0 Z root      3760 16659  0  80   0 -     0 do_exi Jul15 ?        00:00:00 [git-remote-http] <defunct>

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13858
