### ISSUE TITLE
Doc Topics: From Rancher 1.6 to 2.0

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#14559]
Rancher 1.6 uses Cattle as the orchestration platform for docker containers. Services can be created via Rancher UI or via compose files. 

With the release of Rancher 2.0, we shifted to Kubernetes as the base orchestration platform for docker containers. Kubernetes uses its own yaml specs for deploying services and pods(containers) that is different from the docker compose syntax.

Here is list of features we should document about to ease the transition from Cattle to Rancher 2.0:

- [x] Checklist for migration of a 1.6 setup to 2.0 
- [x] Concepts of Stack, Service  - How to map Cattle's Stack and service design to k8s world and launch a simple service
- [x] Exposing your service publicly - How to publicly expose your Service using port mapping in 1.6 and its equivalent 2.0 method
- [x] Monitoring a service using healthchecks - How to add TCP/HTTP healthchecks in Rancher 2.0
- [x] Scheduling rules for placement of service containers - How to find equivalence in 2.0 for scheduling your containers using host affinity/anti-affinity and other 1.6 scheduling labels
- [x] Global Service - How to launch a global service in 2.0
- [x] Service Discovery: Rancher internal DNS - How to discover services, use external_name/alias in 2.0
- [x] LoadBalancing - How to achieve TCP/HTTP load balancing and configure hostname/path based routing in 2.0
- [ ] Secrets - How to manage and use secrets in 2.0
- [ ] Storage - How to configure storage with Rancher 2.0 on Kubernetes
- [ ] Rancher metadata - What can be alternative solutions to rancher 1.6 metadata in rancher 2.0
- [ ] Environment management - What is the equivalence in 2.0 to creating and managing 1.6 environments 
- [ ] External DNS integration- Alternative ways in 2.0 to integrate with external DNS providers supported by Rancher 1.6 
- [ ] Differences in Upgrade procedure for applications deployed on Rancher

**Comment by jgreat** [comment]
Are we still working on tools to convert 1.6 Catalogs to Helm charts?

**Comment by prachidamle** [comment]
@jgreat No. That is more of a k8s yaml->helm.
This ticket is to help move from docker compose to k8s yaml. If that is addressed then converting the k8s yaml to helm might already be supported in some way today?

**Comment by naisanza** [comment]
If I remembered correctly, was that tool to convert a 1.6 config (docker+rancher compose) to 2.x ever created?

**Comment by alena1108** [comment]
@naisanza here is the tool: https://github.com/rancher/migration-tools

**Comment by deniseschannon** [comment]
Closing for now.
