### ISSUE TITLE
Unable to create Azure VM

### ISSUE THREAD

**Issue by jgzurano** [rancher/rancher#14555]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.18
rancher/agent or rancher/rancher-agent: v1.2.10

**Docker version:** 1.12.6

**Operating system and kernel:** Ubuntu 16.04.4 LTS 4.13.0

**Type/provider of hosts:** Azure

**Setup details:** HA rancher, external DB

**Environment Template:** Kubernetes

**Steps to Reproduce:**

1 - Infrastructure - Add Host with these settings:
   - Provider: Azure
   - Environment: AzurePublicCloud
   - Region: Central US
   - Image: canonical:UbuntuServer:16.04.0-LTS:latest
   - VM Size: Standard_DS5_v2 (16 cores, 56gb RAM)

**Results**

``Error in driver during machine creation: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="Unable to create the VM 'kube-test' in availability set 'elk1-kube-avset' because the requested size Standard_DS5_v2 is not available in the current hardware cluster. The available sizes are: Standard_DS1,Standard_DS2,Standard_DS3,Standard_DS4,Standard_DS11,Standard_DS12,Standard_DS13,Standard_DS14.\r\nRead more on VM resizing strategy at `https://aka.ms/azure-resizevm."``
 
**Note:**
I'm able to launch Standard_DS5_v2 vms within the same region using the azure portal panel.
The same happens with Standard_D8s_v3 (8 cores, 32gb RAM) or Standard_D16s_v3 (16 cores, 64gb RAM)

**Comment by superseb** [comment]
The Docker Machine driver creates an availability set to create the virtual machines. This is different than creating an instance through the portal. Azure is saying it doesn't have enough capacity to launch it in an Availability Set (at least not the instance you are requesting). See https://docs.docker.com/machine/drivers/azure/#notes for the Machine driver.

I don't think this is a bug as Azure is replying that it has no capacity, let me know if you think there is something wrong in the integration.
