### ISSUE TITLE
Modify ui context url path - rancher 2.0

### ISSUE THREAD

**Issue by Amos-85** [rancher/rancher#14563]
I read rancher 2.0 documentation and didn't find any way how to change the rancher ui context path url.
I would like to work with nginx in front of rancher in ha mode and be able to work with sub path like:  **example.mydomain.com/rancher**

Is this feature will be available in next close releases?

**Comment by vincent99** [comment]
No; use a different subdomain.  The UI is entirely static files so supporting this is difficult, and running more than one sensitive application on the same domain is a bad idea in general.  A compromise of any one of them can allow attack on all of them since you are defeating protection against XSS, CSRF, reading cookies across domains, etc.

**Comment by xjantoth** [comment]
Hi @vincent99,

we as the company invested quite a few months to incorporate rancher to our on-prem solution. The final step was integrating Rancher web ui with Apache. We have no other choice except using subpaths. Would you please consider to develop this feature ?

**Comment by vincent99** [comment]
As I've described, this is a bad idea and we have no plans to support it.

(How have you had it running for months if you have no other choice?)

You can possibly make it work on your own with a [custom build](https://github.com/rancher/ui/#hosting-remotely) of the UI for the right base URL and probably a bunch of rewrites to map the API call URLs.

**Comment by xjantoth** [comment]
Well, @vincent99 we did not use apache for development cause this is the one of the final steps of course. I would not even dream that it is not possible to run rancher at some context path. I understand that a subdomain would solve the situation however, it is not acceptable for our on-prem customers. And we got like several thousands installations by now.
