### ISSUE TITLE
Etcd DR mode is started with an incorrect endpoint.

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#14564]
**Rancher versions:** v1.6.19-rc4

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.5/1.11.0

**Steps to Reproduce:**
Run etcd in disaster recovery mode.
**Results:**
Etcd entrypoint will get stuck in a loop and keeps crashing.

**Comment by soumyalj** [comment]
Tested with v1.6.19-rc6 (rancher/etcd:v2.3.7-15) . 
Tested DR scenarios on a 3 node setup.
etcd recovered successfully and was in running state. Data was recovered successfully.
