### ISSUE TITLE
Cannot reach pod's ClusterIP

### ISSUE THREAD

**Issue by kpolszewski** [rancher/rancher#14569]
**Rancher versions:**
rancher/rancher:latest (2.0.6)
rancher/rancher-agent:2.0.6

**Infrastructure Stack versions:**
healthcheck: -
ipsec: -
network-services: flannel
scheduler: - 
kubernetes (if applicable): hyperkube:v1.10.1-rancher2

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.1
  Git commit:	7390fc6
  Built:	Wed Feb 28 17:46:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

4.15.0-23-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
some openstack service in private cloud

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, multiple workers(slave-1, slave-2, slave-3)
internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Deployed following on slave-1:
Scalable deployment of 1 pod
Port Mapping: ClusterIP (9999, same as container)
Run on specific node: slave-1
Others: default or irrelevant(I guess)
Namespace/servicename: somenamespace/someservice

2. Deployed anything with telnet+nslookup on slave-2:
Scalable deployment of 1 pod

3. Tried nslookup of slave-1's service on slave2:
/ # nslookup someservice.somenamespace.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      someservice.somenamespace.svc.cluster.local
Address 1: 10.42.3.19

4. Tried telnet of slave-1's service ClusterIP on slave2:
/ # telnet someservice.somenamespace.svc.cluster.local 9999
telnet: can't connect to remote host (10.42.3.19): Operation timed out

**Extra info:**
>  kubectl get ep kube-dns --namespace=kube-system

```NAME       ENDPOINTS                   AGE
kube-dns   10.42.0.4:53,10.42.0.4:53   59d
```

> kubectl get svc --namespace=kube-system

```NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP   59d
```

> kubectl get pods --namespace=kube-system

```NAME                                  READY     STATUS    RESTARTS   AGE
canal-fbj4b                           3/3       Running   9          41d
canal-g6dtv                           3/3       Running   0          4d
canal-gdmvl                           3/3       Running   6          41d
canal-lnzpg                           3/3       Running   3          41d
kube-dns-7dfdc4897f-nl5jt             3/3       Running   1310       59d
kube-dns-autoscaler-6c4b786f5-pfg5s   1/1       Running   7          59d
```

Resolv.conf within slave-2 container:

> cat /etc/resolv.conf

```nameserver 10.43.0.10
search somenamespace.svc.cluster.local svc.cluster.local cluster.local openstacklocal
```

On all nodes:

> ufw status

```
Status: inactive
```

**Results:**
Unable to reach ClusterIP. I've tried many things, but no success.

**Comment by loganhz** [comment]
Can you try it in v2.1.1, please?
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
