### ISSUE TITLE
Enhance EKS driver

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#14566]
Add these additional features if requested:

> 1. Amazon suggests using a reusable service role for creating clusters.  Right now we are creating a new service role for each EKS cluster we spin up.  We could change Rancher to use an existing role that the user specifics, or have Rancher only create the service role if it doesn't exist (or both).

Yes, we should be able to use an existing cluster service role. 

> 2. We are currently bypassing heptio authentication.  Do we want to investigate either integrating AWS's EKS authentication system into Rancher?

Not as of now

> 3. We create a new VPC/Subnet for each EKS cluster.  Can we allow the user to specify a VPC or Subnet? There are some specific requirements around what VPCs and Subnets should look like. Can we have Rancher automatically update a VPC or Subnet if it is not configured correctly?

Yes, we should give flexibility to VPC/subnet. We should not automatically update a VPC/Subnet, but we should document what are the VPC/subnet requirements. 

> 4. Specifying security groups have the same problems as specifying VPCs and subnets (and may be required if specifying a VPC/subnet.

We should give the ability to let them  select their own, but document on what needs to happen for security group.

> 5. Right now all VPCs are exposed to the public internet by default, maybe add an option to not do this.

Yes, let's add this option when we create VPC, but not if they are using an existing one. 

> 6. We don't support modifying existing clusters at all right now. Looks like EKS clusters can't be modified (which means we can't change VPC, subnet, security groups, or even k8s version), but VPCs/subnets and worker nodes can.

Hold off on this for now. 

> 7. Amazon says to not use root credentials when creating an EKS cluster, might be a good idea to remind the user of this or check and fail if root credentials are supplied.

Add a note in the UI for this

> 8. DNS propagation takes a few minutes when exposing a pod with a layer-4 LB.  We should see if there is a way to show this to the user (healthchecks?)

File a separate issue for this. We have this issue for all k8s managed providers. 

> 9. Our deletion process leaves a lot of resources dangling.  When we delete VPCs it is often blocked because of network interfaces and LBs.  Can we have rancher automatically find and delete these resources so that the VPC is deleted successfully?

No, we should only delete the nodes themselves and put a note reminding the users that these network related resources are not deleted and need to be cleaned up themselves. 

----------

Further details from talking with @vincent99 
```
1. Vince will lookup the roles from the UI (no new api endpoint needed).  If a role gets passed in, eks driver will use it, otherwise create a new one.  We will need to modify EKS driver to support this.
3. For the UI piece Vince will make a API call to list Virtual Networks and Subnets.  If no network is passed in we will create one.
4. For the UI piece Vince will make a API call to list security groups.  If no security group is passed in we will create one. Document requirements for security groups.
5. Just checkbox/boolean option. Would not be applicable if using existing virtual network.
7. Vince will add note about root credentials or see if we can check. No backend work needed.
9. Vince says we already do this.
```
For hosting the templates we will vendor them inside kontainer-engine so we don't have to make an http call.

**Comment by deniseschannon** [comment]
@westlywright i've created this issue for the UI: https://github.com/rancher/rancher/issues/14622

@soumyalj this is ready for backend testing

**Comment by soumyalj** [comment]
Tested with master using API. Created VPC, subnets, security group in AWS and used in the config as below
```
{
        "maximumNodes": 3,
        "minimumNodes": 1,
        "type": "amazonElasticContainerServiceConfig",
        "accessKey": "YOUR ACCESS KEY",
        "secretKey": "YOUR SECRET KEY",
        "region": "us-west-2",
        "instanceType": "m4.large",
        "virtualNetwork": "yourVirtualNetwork",
        "subnets": ["subnet1", "subnet2"],
        "securityGroups": ["securityGroup1"],
        "serviceRole": "serviceRole1"
    }

```
The cluster gets created without any nodes. kubectl cannot be launched.

**Comment by nathan-jenan-rancher** [comment]
This issue adds support for the following options in EKS:

```
virtualNetwork
subnets
securityGroups
serviceRole
```

**Comment by soumyalj** [comment]
Tested with master build using API. Tested with custom Virtual network, subnets, securitygroups, servicerole. Creation of EKS cluster was successful. Creation of workloads, L4lbs was successful.
kubectl on rancher UI and remote kubectl was functional.

Support for UI is tracked in this issue:
https://github.com/rancher/rancher/issues/14622
