### ISSUE TITLE
Edit Node, Error "Requested Hostname" contains an invalid character: . (dot)

### ISSUE THREAD

**Issue by seanly** [rancher/rancher#14571]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7.2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
1.8.13-qcloud

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

Edit Node in rancher, change name, or update node label: 
![image](https://user-images.githubusercontent.com/232069/42794066-999383d6-89af-11e8-94db-239bcf6c5cf6.png)

**Results:**

![image](https://user-images.githubusercontent.com/232069/42793999-47c8cf98-89af-11e8-924f-4ef238c3917e.png)

**Comment by loganhz** [comment]
If user has a node with an IP as hostname such as 10.10.1.17.
Then user can not edit the node at all.

The schema of `requestedHostname` field is `dnsLabel`.  I guess we should change it to `string` in backend.

**Comment by alena1108** [comment]
@loganhz string type might not work, because dnsLabel is used to validate the non-ip host name on norman side as the node name has to be RFC1123 compliant (`"^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

**Comment by insekticid** [comment]
Same problem here, Kubernetes installed via RKE

![image](https://user-images.githubusercontent.com/177340/44785592-b6c87c00-ab91-11e8-87a3-38fab676b0db.png)

**Comment by kblackard-meshify** [comment]
Same issue.  Amazon EKS Provider

Auto populated Hostname: ip-###-###-###-###.us-region-#.compute.internal

**Comment by sangeethah** [comment]
Tested with latest build from master.

Scenario 1:
Import a RKE cluster with a node which has an IP as hostname.
Edit the node to add some labels.
Click Save.
Able to save successfully.

Scenario 2:
Add a custom cluster . 
Add AWS nodes which has hostname with a format similar to ip-172-31-0-26
Edit the node to add some labels.
Click Save.
Able to save successfully.
