### ISSUE TITLE
[go-rancher] API doesn't expose "clusterregistrationtokens" endpoint

### ISSUE THREAD

**Issue by headcr4sh** [rancher/rancher#14578]
Since this is an issue with the Golang Rancher API, I left out most of the fields concerning my Rancher setup, because they just don`t make sense..

**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: N/A
rancher/go-rancher: git-commit 5d4e55e3f5de872bd5136d538139fffad238ad3a

**Steps to Reproduce:**
I am trying to use the Golang Rancher API v3 (Rancher 2.0.x) to create a new Kubernetes Cluster and afterwards I want to create "ClusterRegistrationToken". Unfortunately, the (Golang!) API doesn't seem to offer the functionality to work with ClusterRegistrationTokens...

```go
package main

import (
	fmt
	rancher "github.com/rancher/go-rancher/v3"
)
func main() {
	client := rancher.NewRancherClient(&rancher.ClientOpts{
		Url: "http://localhost:8080/v3/",
		AccessKey: "my_access_key",
		SecretKey: "my_secret_key",
	})
	///// ISSUE BEGIN
	token, err := client.ClusterRegistrationToken.Create(&rancher.ClusterRegistrationToken{
		clusterId: "ID of my cluster",	
	})
	///// ISSUE END
	if err != nil {
		panic(fmt.Errorf("creation of cluster registration token failed: %v", err))
	}
	fmt.Printf("Token created: %v\n", token)
}
```

**Results:**

Code won't compile. Obviously...
... there is no (obvious?) way to interact with ClusterRegistrationToken objects.

The documentation for the Golang API is very minimal and I could really need a pointer into the right direction here. Maybe I am totally overlooking something here...

**Comment by superseb** [comment]
Thanks for the report.

go-rancher is not the library for API binding for Rancher 2.x, the repositories are described here: https://rancher.com/docs/rancher/v2.x/en/faq/contributing/

I'll put in a note in the go-rancher repo to point to the 2.x repo.

**Comment by headcr4sh** [comment]
@superseb Thanks for the pointer. *That* I would never have guessed.... :-)
