### ISSUE TITLE
rancher2.0.2  to many docker.sock connections

### ISSUE THREAD

**Issue by itcam** [rancher/rancher#14575]
**docker has error log like:**
`root@worker05~#systemctl status docker -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2018-06-30 18:17:27 CST; 2 weeks 2 days ago
     Docs: https://docs.docker.com
 Main PID: 11837 (dockerd)
    Tasks: 425
   Memory: 4.3G
   CGroup: /system.slice/docker.service
           ├─  830 docker-containerd-shim 8eaa793fb5c8f835b43f712c9c1002017758ecb45cf47d4809be5b10f1edf668 /var/run/docker/libcontainerd/8eaa793fb5c8f835b43f712c9c1002017758ecb45cf47d4809be5b10f1edf668 docker-runc
           ├─ 2636 docker-containerd-shim 99fb7e4b759a09730f17679a3e77d338c4ad043554e579310c6cc1177191fa44 /var/run/docker/libcontainerd/99fb7e4b759a09730f17679a3e77d338c4ad043554e579310c6cc1177191fa44 docker-runc
           ├─ 3067 docker-containerd-shim a126c21dcab82472487d0ab0b6909d3b607afa86e15b0279da92292a84a81068 /var/run/docker/libcontainerd/a126c21dcab82472487d0ab0b6909d3b607afa86e15b0279da92292a84a81068 docker-runc
           ├─ 3178 docker-containerd-shim 319842a72f726d5edb38879fb268ac660fea3d2d6309572774b38a1c31a9fc09 /var/run/docker/libcontainerd/319842a72f726d5edb38879fb268ac660fea3d2d6309572774b38a1c31a9fc09 docker-runc
           ├─ 4244 docker-containerd-shim 34e67b826fd8e9760a6506b2182dba21ac6792c01027fc4d63ba65e53ce3c04e /var/run/docker/libcontainerd/34e67b826fd8e9760a6506b2182dba21ac6792c01027fc4d63ba65e53ce3c04e docker-runc
           ├─ 4787 docker-containerd-shim 319842a72f726d5edb38879fb268ac660fea3d2d6309572774b38a1c31a9fc09 /var/run/docker/libcontainerd/319842a72f726d5edb38879fb268ac660fea3d2d6309572774b38a1c31a9fc09 docker-runc
           ├─ 5296 docker-containerd-shim 49a5b9a02a81ef6c58839b2f8b581209460f87980db1230ed77e64256b49967e /var/run/docker/libcontainerd/49a5b9a02a81ef6c58839b2f8b581209460f87980db1230ed77e64256b49967e docker-runc
           ├─ 5335 docker-containerd-shim 86c36038b8fb3c12c4a97180360edc6d0c416d93fab1680d43d7924e76de3d4f /var/run/docker/libcontainerd/86c36038b8fb3c12c4a97180360edc6d0c416d93fab1680d43d7924e76de3d4f docker-runc
           ├─ 5447 docker-containerd-shim 2b28a1cb1a38e24ed6e1424122613379dabf0ee58a205975a8836ec5e22cb71a /var/run/docker/libcontainerd/2b28a1cb1a38e24ed6e1424122613379dabf0ee58a205975a8836ec5e22cb71a docker-runc
           ├─ 5965 docker-containerd-shim 069283c5e2d8a30eeab063d31ead795a554759c4b36f727db8a26d2832baae28 /var/run/docker/libcontainerd/069283c5e2d8a30eeab063d31ead795a554759c4b36f727db8a26d2832baae28 docker-runc
           ├─ 5988 docker-containerd-shim 06d25901802aa22e097fef4b01000a01922438d6620d511f1c14998f8dadf723 /var/run/docker/libcontainerd/06d25901802aa22e097fef4b01000a01922438d6620d511f1c14998f8dadf723 docker-runc
           ├─ 5993 docker-containerd-shim d938c5ddbe261c11c3fc78a675c25015d7a92b68afc7167107fa0c745ec49a66 /var/run/docker/libcontainerd/d938c5ddbe261c11c3fc78a675c25015d7a92b68afc7167107fa0c745ec49a66 docker-runc
           ├─ 6073 docker-containerd-shim 6824a665404d685721f3d8b0b5e5c259d305697f9ec5ed3940840a71347a9660 /var/run/docker/libcontainerd/6824a665404d685721f3d8b0b5e5c259d305697f9ec5ed3940840a71347a9660 docker-runc
           ├─ 8523 docker-containerd-shim db9c4b12179703432a81e094aebd8e5620cead61b440507e868fec0ba378c361 /var/run/docker/libcontainerd/db9c4b12179703432a81e094aebd8e5620cead61b440507e868fec0ba378c361 docker-runc
           ├─ 9298 docker-containerd-shim a0c57e83413e363d2588ac0d88cc7b48b98db9d42d9bc704e2a26dcfea030514 /var/run/docker/libcontainerd/a0c57e83413e363d2588ac0d88cc7b48b98db9d42d9bc704e2a26dcfea030514 docker-runc
           ├─11837 /usr/bin/dockerd
           ├─11845 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
           ├─13265 docker-containerd-shim 73eaa19938c4395c22de59c6b427c03cddd59b1e909b85600ead2d2087d3902f /var/run/docker/libcontainerd/73eaa19938c4395c22de59c6b427c03cddd59b1e909b85600ead2d2087d3902f docker-runc
           ├─14238 docker-containerd-shim 209df189c941226b9b09774d99e9462d6381147ff7ec2108fa792bb88605e745 /var/run/docker/libcontainerd/209df189c941226b9b09774d99e9462d6381147ff7ec2108fa792bb88605e745 docker-runc
           ├─15705 docker-containerd-shim a546471fe4052475cf6903b135677c36896882c81cc4240165bdfca948c41e6c /var/run/docker/libcontainerd/a546471fe4052475cf6903b135677c36896882c81cc4240165bdfca948c41e6c docker-runc
           ├─15771 docker-containerd-shim c72cdd82835ef60cece8ab5d9a5bca01299e8f151dbf6e03057ef6423cbb5265 /var/run/docker/libcontainerd/c72cdd82835ef60cece8ab5d9a5bca01299e8f151dbf6e03057ef6423cbb5265 docker-runc
           ├─19737 docker-containerd-shim 3af9f32345ffaa7e46ec8b7687a7316b329ad30811e249512efaba642c3da042 /var/run/docker/libcontainerd/3af9f32345ffaa7e46ec8b7687a7316b329ad30811e249512efaba642c3da042 docker-runc
           ├─20030 docker-containerd-shim e253628de3473a2fc4ed77b23352b36e3deebe99cc97377c0361ce31bbc12323 /var/run/docker/libcontainerd/e253628de3473a2fc4ed77b23352b36e3deebe99cc97377c0361ce31bbc12323 docker-runc
           ├─20713 docker-containerd-shim 51dbc4c61264e33058de8a1fb42b2341db3dddd91e1e1946bf1d0657c19dde4a /var/run/docker/libcontainerd/51dbc4c61264e33058de8a1fb42b2341db3dddd91e1e1946bf1d0657c19dde4a docker-runc
           ├─20813 docker-containerd-shim c6c9f821870c4d5322cb4a6f81d0ca1776b5b38a37033b0e3584ad96a5fe0e1b /var/run/docker/libcontainerd/c6c9f821870c4d5322cb4a6f81d0ca1776b5b38a37033b0e3584ad96a5fe0e1b docker-runc
           ├─25559 docker-containerd-shim 31b4fe4203786333e0b3e2e8c52d127ecb0cedb4128e8949f4c859077b15c07c /var/run/docker/libcontainerd/31b4fe4203786333e0b3e2e8c52d127ecb0cedb4128e8949f4c859077b15c07c docker-runc
           ├─25804 docker-containerd-shim 563f369543a4f409a0ec361503c4465a2128f3e1b909316f4d2f60ec3a1fdc6e /var/run/docker/libcontainerd/563f369543a4f409a0ec361503c4465a2128f3e1b909316f4d2f60ec3a1fdc6e docker-runc
           ├─27787 docker-containerd-shim 3be8849e7b9d9b3a2e71a14814bd02231354e11dbe9e54501e45d349c7cab13e /var/run/docker/libcontainerd/3be8849e7b9d9b3a2e71a14814bd02231354e11dbe9e54501e45d349c7cab13e docker-runc
           ├─27881 docker-containerd-shim c14d4ff4385952508149f266dda7637d4ecb1a08bbf384476d2ec97657226d4f /var/run/docker/libcontainerd/c14d4ff4385952508149f266dda7637d4ecb1a08bbf384476d2ec97657226d4f docker-runc
           ├─30357 docker-containerd-shim 179d58d61dd8c905b86cc7a13253d56abf1335584f925508d172297b004f8926 /var/run/docker/libcontainerd/179d58d61dd8c905b86cc7a13253d56abf1335584f925508d172297b004f8926 docker-runc
           ├─30434 docker-containerd-shim 209df189c941226b9b09774d99e9462d6381147ff7ec2108fa792bb88605e745 /var/run/docker/libcontainerd/209df189c941226b9b09774d99e9462d6381147ff7ec2108fa792bb88605e745 docker-runc
           ├─32202 docker-containerd-shim c0911530d64af40c520e8aeb8cf23866ead909ed9d92fd6654f243229bb46762 /var/run/docker/libcontainerd/c0911530d64af40c520e8aeb8cf23866ead909ed9d92fd6654f243229bb46762 docker-runc
           └─32272 docker-containerd-shim 1f22e88ee3f4d65feb4783215402643ae499c28ffcf3d45128642a180c0a6069 /var/run/docker/libcontainerd/1f22e88ee3f4d65feb4783215402643ae499c28ffcf3d45128642a180c0a6069 docker-runc

Jul 17 15:25:31 worker05 dockerd[11837]: time="2018-07-17T15:25:31.494498908+08:00" level=error msg="Handler for POST /v1.24/containers/0e9879aa911bc2770ca37730f1ff4f7f4da6ba6ff4136a16217873d1cb762576/start returned error: Container already started"
Jul 17 15:25:31 worker05 dockerd[11837]: time="2018-07-17T15:25:31.501368838+08:00" level=error msg="Handler for POST /v1.24/containers/49a5b9a02a81ef6c58839b2f8b581209460f87980db1230ed77e64256b49967e/start returned error: Container already started"
Jul 17 15:25:31 worker05 dockerd[11837]: time="2018-07-17T15:25:31.510532314+08:00" level=error msg="Handler for POST /v1.24/containers/86c36038b8fb3c12c4a97180360edc6d0c416d93fab1680d43d7924e76de3d4f/start returned error: Container already started"
Jul 17 15:25:31 worker05 dockerd[11837]: time="2018-07-17T15:25:31.517455169+08:00" level=error msg="Handler for POST /v1.24/containers/2b28a1cb1a38e24ed6e1424122613379dabf0ee58a205975a8836ec5e22cb71a/start returned error: Container already started"
Jul 17 15:25:31 worker05 dockerd[11837]: time="2018-07-17T15:25:31.900665276+08:00" level=error msg="Handler for POST /v1.24/containers/kubelet/start returned error: Container already started"
Jul 17 15:27:32 worker05 dockerd[11837]: time="2018-07-17T15:27:32.215231041+08:00" level=error msg="Handler for POST /v1.24/containers/49a5b9a02a81ef6c58839b2f8b581209460f87980db1230ed77e64256b49967e/start returned error: Container already started"
Jul 17 15:27:32 worker05 dockerd[11837]: time="2018-07-17T15:27:32.219868897+08:00" level=error msg="Handler for POST /v1.24/containers/86c36038b8fb3c12c4a97180360edc6d0c416d93fab1680d43d7924e76de3d4f/start returned error: Container already started"
Jul 17 15:27:32 worker05 dockerd[11837]: time="2018-07-17T15:27:32.226702205+08:00" level=error msg="Handler for POST /v1.24/containers/2b28a1cb1a38e24ed6e1424122613379dabf0ee58a205975a8836ec5e22cb71a/start returned error: Container already started"
Jul 17 15:27:32 worker05 dockerd[11837]: time="2018-07-17T15:27:32.230416651+08:00" level=error msg="Handler for POST /v1.24/containers/0e9879aa911bc2770ca37730f1ff4f7f4da6ba6ff4136a16217873d1cb762576/start returned error: Container already started"
Jul 17 15:27:32 worker05 dockerd[11837]: time="2018-07-17T15:27:32.630173824+08:00" level=error msg="Handler for POST /v1.24/containers/kubelet/start returned error: Container already started"

`

**### netstat -x |grep docker.sock |wc -l
72492**

**Comment by itcam** [comment]
CentOS Linux release 7.5.1804 (Core)

Containers: 32
 Running: 29
 Paused: 0
 Stopped: 3
Images: 35
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.3.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: bh-rancher2-k8s-worker05
ID: SBDQ:D6MU:FFA3:7J5W:TPCJ:V27U:IMK5:BDQW:AASI:GSCK:7BTK:NADL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by superseb** [comment]
fixed in https://github.com/rancher/rancher/issues/13913 and https://github.com/rancher/rancher/pull/14523.

Please edit your original issue if you want to add info to minimize triggers.

**Comment by itcam** [comment]
has it fixed by 2.0.6  or . 2.0.4 ?

**Comment by itcam** [comment]
@superseb has it fixed by 2.0.6 or . 2.0.4 ?
