### ISSUE TITLE
workload detail ui jump exception

### ISSUE THREAD

**Issue by seanly** [rancher/rancher#14572]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

delete this pod in after page(image1),  when pod state update, and removing to removed, this page auto jump to workload list(image2)

(image1, workload detail)
![image](https://user-images.githubusercontent.com/232069/42794442-5ce0eff8-89b1-11e8-83db-446b1ff96c29.png)

(image2: workload list)
![image](https://user-images.githubusercontent.com/232069/42794521-d331a4c2-89b1-11e8-83e3-635821a62fa9.png)

**Results:**

**Comment by seanly** [comment]
The problem is exactly the same， when execute shell, and click "close shell"

**Comment by loganhz** [comment]
Steps to reproduce

1. go to workload detail page
2. go to pod A detail page in pod list
3. go back to workload detail page now
4. remove pod A from workload detail page.
5. page jumps to workload list page

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Verified fixed
