### ISSUE TITLE
x in upper right to close logs overlay doesn't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1457]
v0.27.0-rc1
Steps:
1.  Create a service or a container
2.  Click on View Logs for container/service container
3.  Click on x in upper right of overlay to close

Results:
Nothing happens

Expected:
Close overlay

**Comment by tfiduccia** [comment]
This seems to be the only overlay that actually has that x in the upper right corner of the overly.  The execute shell and edit overlays do not have this.  Maybe it should be removed for consistency or added to the other overlays.

**Comment by vincent99** [comment]
Yes these should have all been removed.

**Comment by tfiduccia** [comment]
v0.27.0-rc1 (ui latest v0.32.0)
Verified fixed
