### ISSUE TITLE
Kubeconfig improvements

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14576]
Discuss the following options:

- Make the generated kubeconfig collapsed by default, and option to expand if needed (especially with ca data you have to scroll down to the other instructions)
- Move all the instructions text to one place, adding what just happened (we generated a kubeconfig for you which can be used with kubectl to interact with your cluster or something along the lines)
- Make two options presentable, copy to clipboard and download file. With an option to expand the kubeconfig if user really wants to.

**Comment by nlowe** [comment]
Something I'd like to add (and I can make a separate issue if needed): I'd love to see the ability to download a merged kubeconfig of all clusters I have access to on the Global page, with the current context set to either the last used / viewed cluster or with instructions on how to set the context for users who don't know how. It'd greatly simplify things for administrators who have to manage multiple clusters.

**Comment by superseb** [comment]
@nlowe thats covered in https://github.com/rancher/rancher/issues/13853
