### ISSUE TITLE
The statefulset controller cannot get the domain name for a single pod through the headless service.

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#14588]
Rancher versions: 2.0 master 07/18
Steps to Reproduce:
1. Go to the Workloads page and create a statefulset app like `nginx`
2. Click launch and check the serviceName of the generate YAML, the serviceName is empty and it should contains the correct service name
3. A single pod cannot get a domain name

Expected Results: Add serviceName to the deployed statefulset YAML.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/4
Verified fixed
