### ISSUE TITLE
Users without global permissions can see all other users

### ISSUE THREAD

**Issue by madddi** [rancher/rancher#14582]
**Rancher versions:**
rancher/server or rancher/rancher: `v2.0.4`
rancher/agent or rancher/rancher-agent: `v2.0.4`

**Steps to Reproduce:**
1. Create a new user without any permissions (only "Login Access")
2. Login as the new user
3. Select the users tab

**Results:** You can see all users known to Rancher.

For mutli-tenancy environments it'd be nice if this wasn't the case. Is this intended behaviour?

**Comment by dverbeek84** [comment]
Maybe the Global view should be removed for this kind of users.
The UI should adopt the user role.

**Comment by madddi** [comment]
@dverbeek84 Thanks. Is this something I should do or something which has to be changed in Rancher?

**Comment by deniseschannon** [comment]
Unable to reproduce with v2.2.1. 

I only see myself with adding with login access only.
