### ISSUE TITLE
Add ability to access SSH keys to EKS driver

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#14598]
The SSH private key to access the machine is created and not saved, worker instances cannot be accessed. Would be nice to have it configurable and/or being able to download the key.

**Comment by jiaqiluo** [comment]
The feature is validated on Rancher: master version f6c16893

Steps:
- provision an EKS from Ranch, and during the configuration, choose a key pair from the drop-down list
 
Result:
- the EKS cluster is up
- check the instances in AWS console and confirm that the key pair name is the same as I chose.

**Comment by sjensenihi** [comment]
Is there any documentation on where this keypair dropdown list is during provisioning? I didn't see it for AWS EKS deployment.

**Comment by daxmc99** [comment]
This feature is not available in v2.2 and will be available in v2.3

**Comment by mshivanna** [comment]
whats the timeline for 2.3 release @daxmc99 ?
