### ISSUE TITLE
When upgrading K8s from 1.10 to 1.11 , addon containers get stuck in "Initializing" state and get recreated multiple times before they  get upgraded successfully.  

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14594]
**Rancher versions:** v1.6.19-rc6
**Steps to Reproduce:**

Create a kubernetes environment (defaults to v1.10).
Upgrade kubernetes to v1.11

As part of upgrading , addon containers get stuck in "Initializing" state and get recreated multiple times before they  get upgraded successfully.

**Comment by sangeethah** [comment]
This issue seems happens only on smaller hosts - (AWS instance type t2.small - > 2.4 GHz).

I dont see this happen when testing on hosts is more cpu ( AWS instance type t2.medium- > 2*2.4 GHz).

**Comment by deniseschannon** [comment]
Needs to use bigger hosts to prevent this.
