### ISSUE TITLE
getting these daily `The system component etcd is not running`

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#14595]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4

I'm getting these alerts from our RKE cluster almost every hour
```
The system component etcd is not running
Alert Name: Alert for etcd
Severity: critical
Cluster Name: control
Logs: Get https://140.0.32.206:2379/health: net/http: TLS handshake timeout
The system component etcd is not running
Alert Name: Alert for etcd
Severity: critical
Cluster Name: control
Logs: HTTP probe failed with statuscode: 503
```

![alerts](https://user-images.githubusercontent.com/3282427/42847158-f35ea97a-89cf-11e8-9947-4d30e30d7194.png)

**Comment by superseb** [comment]
Please provide info to reproduce in https://github.com/rancher/rancher/issues/14630
