### ISSUE TITLE
While adding machine/host, showing multiple of same machine/host while bootstrapping

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1459]
v0.27.0-rc1
Steps:
1.  Add an EC2 machine/host

Results:  I only added one, but it shows up multiple times once it hits bootstrapping stage.
![image](https://cloud.githubusercontent.com/assets/11514927/8603478/597fa2d6-262d-11e5-918f-78121f6d4820.png)

Expected: Shouldn't show more than one.

comment:
Saw error being thrown in Network: Uncaught TypeError: Cannot read property 'sortBy' of undefined

**Comment by deniseschannon** [comment]
@tfiduccia Have you seen this occur again? I haven't seen this..

**Comment by tfiduccia** [comment]
I have not seen this lately.  I will close
