### ISSUE TITLE
Rancher V2.0.6 Unable to create new cluster or import cluster

### ISSUE THREAD

**Issue by grcann101** [rancher/rancher#14604]
**Rancher versions:**
 rancher/rancher: V2.0.6
The problem is that I cannot create a new cluster using the AMI’s in the Rancher list 
Also a cluster cannot be imported.

The rancher node and cluster environment keep crashing:
NAMESPACE       NAME                                      READY     STATUS             RESTARTS   AGE
cattle-system   cattle-549fdf55b7-2qqk4                   1/1       Running            0          21h
cattle-system   cattle-cluster-agent-7cd65d8c75-drhpc     0/1       CrashLoopBackOff   260        21h
cattle-system   cattle-node-agent-48n4x                   0/1       CrashLoopBackOff   259        21h
cattle-system   cattle-node-agent-82fdt                   0/1       CrashLoopBackOff   259        21h
cattle-system   cattle-node-agent-s9j22                   0/1       CrashLoopBackOff   260        21h
ingress-nginx   default-http-backend-564b9b6c5b-dn4w6     1/1       Running            0          21h
ingress-nginx   nginx-ingress-controller-2d2wn            1/1       Running            0          21h
ingress-nginx   nginx-ingress-controller-ccfx9            1/1       Running            0          21h
ingress-nginx   nginx-ingress-controller-l67jd            1/1       Running            0          21h
kube-system     canal-hdd2m                               3/3       Running            0          21h
kube-system     canal-j6l7m                               3/3       Running            0          21h
kube-system     canal-lv6cg                               3/3       Running            0          21h
kube-system     kube-dns-5ccb66df65-9gmjr                 3/3       Running            0          21h
kube-system     kube-dns-autoscaler-6c4b786f5-b8th8       1/1       Running            0          21h
kube-system     rke-ingress-controller-deploy-job-cf9pn   0/1       Completed          0          21h
kube-system     rke-kubedns-addon-deploy-job-kggw5        0/1       Completed          0          21h
kube-system     rke-network-plugin-deploy-job-86hg2       0/1       Completed          0          21h
kube-system     rke-user-addon-deploy-job-vjh4q           0/1       Completed          0          21h

The node agent is reporting :
kubectl --kubeconfig=kube_config_rancher-cluster-tls.yaml logs cattle-node-agent-48n4x -n cattle-system
ERROR: Failed to pull the cacert from the rancher server settings at https://rancher.?????.cloud/v3/settings/cacerts

I can see the cert from my PC but not from any of the nodes using the below command from10562
curl --insecure -s -fL https://rancher.??????.cloud/v3/settings/cacerts

The cert is self signed.

Rancher HA and node AMI ami-bc386557 , same with ami-1686b3fd

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred) 17.03.2-CE
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** AWS Rancher OS 1.3 64bit
rancheros-v1.3.0-hvm-1 (ami-bc386557)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
HA

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** 
Kubernetes  setup via RKE

**Steps to Reproduce:**
setup AWS HA environment 
run the RKE up with self signed certs.
create cluster from the GUI.

**Results:**

**Comment by grcann101** [comment]
The ????? is a mask to redact the address as this is public. 
The curl returns : Could not resolve host: 
The host can be resolved externally !

**Comment by grcann101** [comment]
logging of  of cattle-549fdf55b7-2qqk4


2018/07/17 11:12:58 [INFO] cluster [c-7rwbr] provisioning: [certificates] Successfully deployed kubernetes certificates to Cluster nodes
2018/07/17 11:12:58 [INFO] cluster [c-7rwbr] provisioning: Pre-pulling kubernetes images
2018/07/17 11:12:58 [INFO] cluster [c-7rwbr] provisioning: [pre-deploy] Pulling image [rancher/hyperkube:v1.10.5-rancher1] on host [18.185.184.93]
2018/07/17 11:13:22 [INFO] cluster [c-7rwbr] provisioning: [pre-deploy] Successfully pulled image [rancher/hyperkube:v1.10.5-rancher1] on host [18.185.184.93]
2018/07/17 11:13:22 [INFO] cluster [c-7rwbr] provisioning: Kubernetes images pulled successfully
2018/07/17 11:13:22 [INFO] cluster [c-7rwbr] provisioning: [etcd] Building up etcd plane..
2018/07/17 11:13:22 [INFO] cluster [c-7rwbr] provisioning: [etcd] Pulling image [rancher/coreos-etcd:v3.1.12] on host [18.185.184.93]
2018/07/17 11:13:28 [INFO] cluster [c-7rwbr] provisioning: [etcd] Successfully pulled image [rancher/coreos-etcd:v3.1.12] on host [18.185.184.93]
2018/07/17 11:13:29 [INFO] cluster [c-7rwbr] provisioning: [etcd] Successfully started [etcd] container on host [18.185.184.93]
2018/07/17 11:13:29 [INFO] cluster [c-7rwbr] provisioning: [etcd] Successfully started [rke-log-linker] container on host [18.185.184.93]
2018/07/17 11:13:29 [INFO] cluster [c-7rwbr] provisioning: [remove/rke-log-linker] Successfully removed container on host [18.185.184.93]
2018/07/17 11:13:29 [INFO] cluster [c-7rwbr] provisioning: [etcd] Successfully started etcd plane..
2018/07/17 11:13:29 [INFO] cluster [c-7rwbr] provisioning: [controlplane] Building up Controller Plane..
2018/07/17 11:13:30 [INFO] cluster [c-7rwbr] provisioning: [controlplane] Successfully started [kube-apiserver] container on host [18.185.184.93]
2018/07/17 11:13:30 [INFO] cluster [c-7rwbr] provisioning: [healthcheck] Start Healthcheck on service [kube-apiserver] on host [18.185.184.93]
2018/07/17 11:14:20 [ERROR] cluster [c-7rwbr] provisioning: [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [18.185.184.93]: Get https://localhost:6443/healthz: can not build dialer to c-7rwbr:m-888x7, log: I0717 11:13:43.048059       1 storage_rbac.go:279] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public
2018/07/17 11:14:50 [INFO] Provisioning cluster [c-7rwbr]


I would appreciate any suggestions on resolving this.

**Comment by grcann101** [comment]
I missed out a TLS handshake error:
provisioning: [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [18.185.184.93]: Get https://localhost:6443/healthz: can not build dialer to c-7rwbr:m-888x7, log: I0717 11:15:22.008404       1 logs.go:49] http: **TLS handshake error from** 172.20.41.95:33851: EOF

**Comment by superseb** [comment]
The container in the pod is not able to resolve your hostname, `cat /etc/resolv.conf` will show what DNS server it is trying to use to resolve it.

**Comment by grcann101** [comment]
The public route53 A record was missing , I have recreated it and this issue has been resolved.
