### ISSUE TITLE
k8-etcd-recovery: rancher2 + agent

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#14602]
**Rancher versions:** 
rancher/rancher: v2.0.5
rancher/rancher-agent: v2.0.5 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** singe node

**Steps to Reproduce:**
- Single-Node Rancher2
- create kubernetes-cluster and add nodes via rancher-agent cmd
- destroy kubernetes etcd/kill etcd-nodes (not the rancher2-etcd)

**Results:**
How can you recover the kubernetes cluster? There should be at least some docs in the troubleshooting-section for this case, like with rancher1.x.

regards,
Roman

**Comment by deniseschannon** [comment]
There are now backup/restore abilities for user clusters in v2.2 and there are docs on how to handle it:

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/backing-up-etcd/
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/restoring-etcd/
