### ISSUE TITLE
images's time is UTC , and system is CST,then how fix?

### ISSUE THREAD

**Issue by SaiDoFan** [rancher/rancher#14601]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.4
rancher/agent or rancher/rancher-agent:v2.0.4

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: 1.13.1

**Operating system and kernel: CentOS7.5

**Setup details:  HA rancher

rancher/hyperkube:v1.10.1-rancher2
--

The image rancher/hyperkube:v1.10.1-rancher2 time is UTC,and system time is CST how to fix?

**Comment by loganhz** [comment]
Please see https://rancher.com/docs/rke/v0.1.x/en/config-options/services/services-extras/#extra-binds
