### ISSUE TITLE
Rancher 1.6.18 - kubelet

### ISSUE THREAD

**Issue by zetneteork** [rancher/rancher#14607]
All kubernetes stack run fine except kubelet.
`rancher/k8s:v1.10.3-rancher1-1`

```
kubelet (Container should have been running but is in error state. Check logs for more information.: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate") 
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.18` Cattle: `v0.183.52` UI: `v1.6.43` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`stack.index`|
|OS|RancherOS: `v1.4.0`|
|Docker|18.03.1-ce, build 9ee9f40|

**Comment by superseb** [comment]
What Docker version are you running?

**Comment by zetneteork** [comment]
Command of kubelet
```
kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --register-node=true --cloud-provider=rancher --allow-privileged=true --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --fail-swap-on=false --cluster-domain=cluster.local --network-plugin=cni --cni-conf-dir=/etc/cni/managed.d --anonymous-auth=false --volume-plugin-dir=/var/lib/kubelet/volumeplugins --client-ca-file=/etc/kubernetes/ssl/ca.pem --pod-infra-container-image=rancher/pause-amd64:3.0 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

**Comment by zetneteork** [comment]
RancherOS: `v1.4.0`
Docker version 18.03.1-ce, build 9ee9f40

**Comment by superseb** [comment]
Can you try using a supported version of Docker? 

```sudo ros engine switch docker-17.03.2-ce```

If you have Docker data you want to preserve, read the release notes before executing the command.

**Comment by zetneteork** [comment]
Oh, Kubernetes requires lower version that that.
https://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions

Would be Docker 17.03.3-ce capable to run k8s 1.10-3?

**Comment by superseb** [comment]
Docker 17.03.2 is the latest supported version, which you can switch to using the command mentioned above. Because you are switching between major versions it might give issues with your Docker data root dir, so better check the release notes between them for incompatibility. Or make a backup.

**Comment by superseb** [comment]
Let me know if this doesn't solve it.
