### ISSUE TITLE
Metadata locked up

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#14611]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.18
rancher/agent or rancher/rancher-agent: v1.2.10

**Infrastructure Stack versions:**
network-services:
- network-services-metadata-26                                 rancher/metadata:v0.10.2
- network-services-metadata-dns-26                        rancher/dns:v0.17.3
- network-services-network-manager-18                rancher/network-manager:v0.7.20

**Steps to Reproduce:**
NA

**Results:**
- noticed metadata stopped logging ~4 days back
- ipsec was reporting unhealthy because 2 hosts had been removed within that past 4 day window
- so cross host functionality worked and the overlay network still worked.

**Comment by aemneina** [comment]
[metadata go routine dump](https://gist.github.com/aemneina/1eb1db4398da67576d3a69c05280855c)

**Comment by alena1108** [comment]
@aemneina is there a way to fetch the information from the cattle side to check if the metadata update was pushed via config item, for this very host? Here is the way to fetch it:

1) Find out the agent id for the problematic host: `select agent_id from host where id=<host_id>`
2) Fetch config item status for the affected agent:

`select * from config_item_status where agent_id=<agent_id>`
