### ISSUE TITLE
Validate k8s 1.11.1 for 2.0 and make as default k8s version

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14613]
https://github.com/kubernetes/kubernetes/releases/tag/v1.11.1

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md

**Comment by moelsayed** [comment]
I ran kubernetes conformance tests on latest RKE master build with `rancher/hyperkube:v1.11.1-rancher1`. We passed the tests with 0 failures.

**Comment by deniseschannon** [comment]
k8s v1.11.x will be the default version in v2.0.7

**Comment by adampl** [comment]
Is it possible to hack into Rancher 2.0.6 and enable Kubernetes 1.11.1?

The image is already available: https://hub.docker.com/r/rancher/hyperkube/tags/ but I don't know how to  "load" it into Rancher.

**Comment by soumyalj** [comment]
Validated fresh install of k8s v1.11.1-rancher1-1 on master. Automation tests succeeded

**Comment by soumyalj** [comment]
Upgraded from v2.0.6 with k8s v1.10.5 to master. Then upgraded to v1.11.1-rancher1-1. Upgrade succeeded and automation tests succeeded on the upgraded setup.
