### ISSUE TITLE
RAM usage not being correctly reported

### ISSUE THREAD

**Issue by fabiorauber** [rancher/rancher#14610]
**Rancher versions:**
rancher/rancher: v2.0.6
rancher/rancher-agent: v2.0.6

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.3-rancher2-1

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Thu Jun 14 08:36:44 2018
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Thu Jun 14 08:36:44 2018
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.7.0
VERSION_ID=1745.7.0
BUILD_ID=2018-06-14-0909
PRETTY_NAME="Container Linux by CoreOS 1745.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

uname -r: 4.14.48-coreos-r2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
XenServer

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

Create cluster, add workers and add worloads. Watch RAM usage in Rancher dashboard.

**Results:**

RAM Usage is not being reported correctly. Rancher dashboard for one host, for instance, is reporting "0% Memory - 0.1 of 15.6 GiB used" but "free" command shows a different scenario:
```
$ free -h
             total       used       free     shared    buffers     cached
Mem:           15G        14G       1.4G       115M       1.5G       6.0G
-/+ buffers/cache:       6.9G       8.8G
```

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/12683, it will be changed to say `reserved` in the next release.
