### ISSUE TITLE
Validate k8s 1.11.1 for 1.6

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14614]
https://github.com/kubernetes/kubernetes/releases/tag/v1.11.1

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md

**Comment by soumyalj** [comment]
K8s Automation runs  k8s:v1.11.1-rancher1-1 succeeded with no new issues on the following configurations:

Ubuntu 16.04 hosts
Rhel 7.5 , native docker 1.12 with selinux enabled
Rhel 7.5 , native docker 1.13 with selinux enabled
RancherOS v1.3.0 with 17.03.2-ce

P1 tests for RBAC enabled K8s setup and K8s setup with cloud provider set to AWS succeeded.
