### ISSUE TITLE
Key and Value not available when I try to add a scheduling rule

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1461]
v0.27.0-rc1
Steps:
1.  Go to the Add a service or container page
2.  Click on Advanced and go to the Scheduling tab
3.  Click on + to add a scheduling rule

Results:  The fields to add a key and value are missing
![image](https://cloud.githubusercontent.com/assets/11514927/8604201/db32b6fc-2631-11e5-9eb5-908845396f73.png)

Expected:
Fields should be there so I can enter a rule.

**Comment by deniseschannon** [comment]
v0.27.0-rc4 - Verified Fixed
