### ISSUE TITLE
Catalog apps UI return cannot read property 'displayName' of undefined 

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#14629]
Rancher versions: 2.0 master 07/19
Steps to Reproduce:
1. Go to the Catalog page and view details of any app
2. the Catalog UI returns cannot read property 'displayName' of undefined 

![image](https://user-images.githubusercontent.com/4569037/42919514-e9c91faa-8b44-11e8-816b-6e38e5316bd5.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Verified fixed
