### ISSUE TITLE
[cli] Which Rancher CLI version for Rancher 1.6.x?

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#14624]
Which Rancher CLI version am I supposed to use with my old Rancher 1.6.x instances?

I guess its 0.6.10 but can't be sure since the version number assignments make no sense at all.

**Comment by superseb** [comment]
Each release lists all the coupled components, e.g.: https://github.com/rancher/rancher/releases/tag/v1.6.18

Also there is a download link in the UI to the CLI.
