### ISSUE TITLE
Allow scaling workloads to zero

### ISSUE THREAD

**Issue by Crokoking** [rancher/rancher#14627]
**Rancher versions:**
rancher/rancher: 2.0.6

Since kubernetes doesn't have the concept of "stopping" a workload, but does support scaling it to zero pods, this should be supported by rancher. 

The limitation currently seems to just be implemented in the UI. Removing the "disabled" property of the minus button makes scaling to zero work without issues. 
If the point if the UI limitation is to prevent accidental service downtime, there should be an option to turn this off. Alternatively rancher could pop up a warning before scaling to zero.

**Comment by Crokoking** [comment]
Submitted a pull-request https://github.com/rancher/ui/pull/2064

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Not fixed - UI still goes back to 1 when I try to enter 0 on create/edit of workload

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/26
Verified fixed
