### ISSUE TITLE
UI for adding new fields from EKS driver

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14622]
UI for https://github.com/rancher/rancher/issues/14566

**Comment by nathan-jenan-rancher** [comment]
The following options should be supported on the UI (already added in backend).
- Ability to specify a ServiceRole (need to query AWS to get the list of roles) (no service role passed in means the backend creates a new one automatically)
- Add a note in the UI that they should not use Root credentials to create the EKS cluster
- Ability to specify a VirtualNetwork, Subnet, and Security Group (need to query AWS to get lists) (all should be passed in together or validation will fail)

ServiceRole, VirtualNetwork, Subnet, and Security group options have all been added to the EKS config on cluster.

**Comment by tfiduccia** [comment]
Missing the service group section after vpc/subnet
![image](https://user-images.githubusercontent.com/11514927/43551032-5ce41652-959a-11e8-9738-3fbc9a4eae69.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/8
Verified fixed
