### ISSUE TITLE
UI to turn off monitoring for RKE cluster on create/update

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#14625]
We deploy metrics server by default on rke cluster to support monitoring. API allows disabling this option; we should add a UI support.

https://github.com/rancher/rancher/issues/13745

**Comment by loganhz** [comment]
hi @alena1108 

How to enable/disable it in API?

I guess setting `rkeConfig.monitoring.provider` to `metrics-server` is for on and `none` is for off.

@vincent99 

is that OK if we add two dropdowns in cluster options? One for monitoring with `none` and `metrics-server` options and one for ingress with `none` and `nginx`?

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
