### ISSUE TITLE
Cloning a container you just created give an error page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1462]
v0.27.0-rc1
Steps:
1.  Create a container using hello-world as image
2.  Wait for container to automatically stop
3.  Go to menu and try to clone container

Results: Error page pops up
![image](https://cloud.githubusercontent.com/assets/11514927/8604498/cac748bc-2633-11e5-930a-e2ab332cb96c.png)

Expected:
No error

Comment:  after you reload application and go back to try again, the clone option will work.

**Comment by deniseschannon** [comment]
v0.27.0-rc4 - Verified Fixed.
