### ISSUE TITLE
Access host label in rancher-compose.yml

### ISSUE THREAD

**Issue by stepman0** [rancher/rancher#14637]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6

I build a custom catalog for my stack, which contains docker-compose.yml and rancher-compose.yml. Some parameters of my stack need to be defined by user, this I realize with questions. -> works!

BUT: Some parameters of my stack must be set depending on the host it runs on. 
I assigned a custom labels to my host, maybe "my.hostname=box1". 

I try to access this value in rancher-compose.yml --> ideally as default answer for one of my questions. It tried to enter ${my.hostname} or $${my.hostname}, both did not work

Is this possible? If yes - how? If not - is there any way to pass host-specific parameters to a container?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
