### ISSUE TITLE
Project Owner role user does not see namespaces he create with kubectl

### ISSUE THREAD

**Issue by wernergillmer** [rancher/rancher#14635]
**Rancher versions:**
2.0.6
**Infrastructure Stack versions:**
kubernetes : 1.10.1
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
**Setup details: (HA rancher)**
**Environment Template: (Kubernetes)**
**Steps to Reproduce:**

Create a user (let's call it bob) in the rancher UI under Global with Custom Role and that is set to "login only".
Go to a cluster, create a project, add the user bob under the project, not the cluster. User is able to create namespaces in the project in the rancher UI, but with kubectl user bob cannot see the namespaces, and get's a rbac error 

```
Error from server (Forbidden): namespaces is forbidden: User "u-kwd9p" cannot list namespaces at the cluster scope
```

Using my admin account I can see namespaces created in the UI under a project gets a label similar to 

```
field.cattle.io/projectId=p-mpdpz
```

How can I configure a user so that he is a owner of a project, which works well in the rancher UI, but also works as expected with kubectl, which most of my users will be using.

**Results:**

**Comment by deniseschannon** [comment]
The project owner dhould be able to view specific namespaces when using 
```
kubectl get namespaces <name>
```

But they will not be able to use the general "get all namespaces" as kubectl is unable to distinguish between which namespaces you have permissions to versus not. 

 ```
# this command will not work unless you have cluster level permissions
$ kubectl get namespaces
```

**Comment by wernergillmer** [comment]
Indeed, a user can see the namespace, but my question is more, he cannot list the namespaces in his project. For example, the below snippet, the project is called `pop`, to get the namespaces he created in the rancher UI does not work. So currently the only way a user can view the namespaces in his project is to login to the rancher UI.

If he indeed does know the namespace name, in his project, he can get that namespace.

```
➜  kubectl get namespaces pop
No resources found.
Error from server (NotFound): namespaces "pop" not found

➜ kubectl get namespaces pop1
NAME      STATUS    AGE
pop1      Active    18h

```

So how does a Project Owner role user, that create namespaces view them with kubectl?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15254
