### ISSUE TITLE
deploy spring cloud stream app error

### ISSUE THREAD

**Issue by xyjwsj** [rancher/rancher#14632]
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-07-19T09:47:49Z
  generateName: user-fieldvalue-dau-fieldvaluedata-bf78b88db-
  labels:
    pod-template-hash: "693464486"
    role: spring-app
    spring-app-id: user-fieldvalue-dau-fieldvaluedata
    spring-deployment-id: user-fieldvalue-dau-fieldvaluedata
    spring-group-id: user-fieldvalue-dau
  name: user-fieldvalue-dau-fieldvaluedata-bf78b88db-lt45f
  namespace: stream
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: user-fieldvalue-dau-fieldvaluedata-bf78b88db
    uid: cc779ada-8b38-11e8-bb68-000c2933ee2c
  resourceVersion: "644019"
  selfLink: /api/v1/namespaces/stream/pods/user-fieldvalue-dau-fieldvaluedata-bf78b88db-lt45f
  uid: cc7c05d5-8b38-11e8-bb68-000c2933ee2c
spec:
  containers:
  - args:
    - --spring.metrics.export.triggers.application.includes=integration**
    - --spring.cloud.dataflow.stream.app.label=fieldValueData
    - --spring.cloud.stream.metrics.key=user-fieldvalue-dau.fieldValueData.${spring.cloud.application.guid}
    - --spring.cloud.stream.bindings.input.group=user-fieldvalue-dau
    - --access.fieldValue.field-name=uid
    - --spring.cloud.stream.metrics.properties=spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*
    - --access.fieldValue.groups=productId
    - --spring.cloud.dataflow.stream.name=user-fieldvalue-dau
    - --access.fieldValue.name=dau
    - --spring.cloud.dataflow.stream.app.type=sink
    - --spring.cloud.stream.bindings.input.destination=usercollection.filterdata
    env:
    - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
      value: 10.1.129.197:9093
    - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
      value: 10.1.129.197:2181
    - name: SPRING_CLOUD_APPLICATION_GUID
      value: ${HOSTNAME}
    - name: SPRING_CLOUD_APPLICATION_GROUP
      value: user-fieldvalue-dau
    image: ccr.ccs.tencentyun.com/huaihudong/field_value_counter_stream
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 2
    name: user-fieldvalue-dau-fieldvaluedata
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /info
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-sb5wq
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: ndc-68sfx
  nodeName: k8s-slave
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-sb5wq
    secret:
      defaultMode: 420
      secretName: default-token-sb5wq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-07-19T09:47:50Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-07-19T09:47:50Z
    message: 'containers with unready status: [user-fieldvalue-dau-fieldvaluedata]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-07-19T09:47:50Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9816b6418165a88df5ffa410b9d8f9f52cd768ccad5c023a9eaaecad03a89eb8
    image: ccr.ccs.tencentyun.com/huaihudong/field_value_counter_stream:latest
    imageID: docker-pullable://ccr.ccs.tencentyun.com/huaihudong/field_value_counter_stream@sha256:ff308d355a02aec5e2d7494c753f2d113199dcbbe6892d42bbcb8c61f7b4cd42
    lastState:
      terminated:
        containerID: docker://9816b6418165a88df5ffa410b9d8f9f52cd768ccad5c023a9eaaecad03a89eb8
        exitCode: 127
        finishedAt: 2018-07-19T09:54:02Z
        message: 'OCI runtime create failed: container_linux.go:348: starting container
          process caused "exec: \"--spring.metrics.export.triggers.application.includes=integration**\":
          executable file not found in $PATH": unknown'
        reason: ContainerCannotRun
        startedAt: 2018-07-19T09:54:02Z
    name: user-fieldvalue-dau-fieldvaluedata
    ready: false
    restartCount: 6
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=user-fieldvalue-dau-fieldvaluedata
          pod=user-fieldvalue-dau-fieldvaluedata-bf78b88db-lt45f_stream(cc7c05d5-8b38-11e8-bb68-000c2933ee2c)
        reason: CrashLoopBackOff
  hostIP: 10.1.1.22
  phase: Running
  podIP: 10.42.1.90
  qosClass: BestEffort
  startTime: 2018-07-19T09:47:50Z

这个yml部署时候直接报错

Failed | Error: failed to start container "user-fieldvalue-dau-fieldvaluedata": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--spring.metrics.export.triggers.application.includes=integration**\": executable file not found in $PATH": unknown

**Comment by loganhz** [comment]
This is not a rancher issue. You need to check your application. Please see https://stackoverflow.com/questions/27158840/docker-executable-file-not-found-in-path and you can find more via google. Please describe your issue in English next time. Thanks
