### ISSUE TITLE
Add UI for additional GKE Options

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#14639]
Add UI support for the additional GKE options added in https://github.com/rancher/rancher/issues/13789

The options are:
1. legacy authorization
2. stackdriver logging
3. stackdriver monitoring
5. kubernetes dashboard
6. http load balancing
10. mainenance window

**Comment by westlywright** [comment]
I'm marking this resolved as the pr is open but pending because the backend changes are pending merge as well.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/8
Verified added
