### ISSUE TITLE
AKS Advanced Network Config Misses essential network options

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/rancher#14633]
Rancher v2 / current

![image](https://user-images.githubusercontent.com/83597/42938554-9583fe32-8b4a-11e8-94a9-114ca523181b.png)

1) Failure to allow control over the K8 service range on an existing network will cause all deployments to fail as the default range is huge and will overlap other ranges.

2) Http Application routing isn't always desirable, the ability to kill it is important.

**Comment by loganhz** [comment]
Fixed in [rancher/kontainer-engine#107](https://github.com/rancher/kontainer-engine/pull/107)
Close in favor of #15697
