### ISSUE TITLE
Openstack Floating IP routing issues [2.0.6] (is not able to connect to the following ports: 2379)

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#14638]
**Rancher versions:**
2.0.6

I have provisioned a rancher cluster and one openstack node using the driver (docker-machine) and setup a floating ip pool. The floating ip pool is setup and rancher can connect to the node but when it runs the port check locally it uses the floating ip instead of the private (local) ip. These nodes routing to itself using the floating ip does not work so this check will never work in my case. Can the initial port check on the host to itself use the private ip?

**Comment by alexandrem** [comment]
> These nodes routing to itself using the floating ip does not work so this check will never work in my case.

What do you mean? It usually works. If you have bridging involved then ensure to have hairpin enabled on the VM virtual interface.
