### ISSUE TITLE
Error while trying to join a coreos host to the rancher cluster

### ISSUE THREAD

**Issue by su7970** [rancher/rancher#14648]
I am new to Rancher and was just trying out stuff. Till yesterday I was able to add a coreos host to rancher cluster but today when I tried it popped a error and I am unable to identify the cause. 

I Brought up a Centos host with latest Rancher2 in it.
and tried to add a PXE booted coreOS host by running the add host command from the cluster i created in the rancher server.

It was not able to add the coreos host to the cluster and the error 

This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

[controlPlane] Failed to bring up Control Plane: Failed to create [kube-apiserver] container on host [10.2.0.99]: Error: No such image: rancher/hyperkube:v1.10.5-rancher1

**Comment by superseb** [comment]
What Rancher version are you using and what CoreOS version and Docker version? Can you run `docker pull rancher/hyperkube:v1.10.5-rancher1` on the host?

Please use the issue template to supply the needed information.

**Comment by superseb** [comment]
Let us know if we can help on this.
