### ISSUE TITLE
Add tiller back

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#14642]
Add tiller back to launch rancher catalog apps.

**Comment by cjellick** [comment]
@StrongMonkey please add a more detailed description that QA can understand in order to write a test plan

**Comment by cjellick** [comment]
We should be able to write a validation test that at least exercises a basic usecase for helm/tiller

**Comment by StrongMonkey** [comment]
This issue address https://github.com/rancher/rancher/issues/14316.
We switched to use tiller as the backend to deploy charts. We should be able to verify:
1. Users are still able to launch app
2. Users can get proper error message when failed to deploy (due to permission)
3. Rbac still works.
4. Everything functions.
5. Pre/post/ect hooks are able to execute. (go to helm doc and check how a pre/post hook is defined in the chart.

**Comment by StrongMonkey** [comment]
Also we should be able to verify that upgrade path works.
1. Create an app in 2.0.8.
2. Upgrade server to 2.1.
3. Upgrade apps created previously, upgrade should work.

**Comment by tfiduccia** [comment]
I have tested that Apps still deploy & I can add custom catalog and deploy app from there.

**Comment by cjellick** [comment]
@guangbochen to validate

**Comment by guangbochen** [comment]
Validate on the latest rancher:master with RKE and GKE clusters.

New Release Test:
1. validate the latest charts from the rancher `library` catalog can be deployed to the RKE and GKE cluster in the rancher:master build(will tag to v2.1).

Upgrade test:
1. Create a WordPress in 2.0.8.
2. Upgrade server to rancher:master 09/21.
3. Upgrade apps created previously, upgrade should work.
