### ISSUE TITLE
rancher/calico logs eating disk space

### ISSUE THREAD

**Issue by sirwolfgang** [rancher/rancher#14647]
**Rancher versions:**
rancher/server or rancher/rancher: `v2.0.4`
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version:** `17.03.2-ce`
**Operating system and kernel:** `Ubuntu 16.04.2 LTS, 4.4.0-1020-aws`
**Type/provider of hosts:** `AWS`
**Setup details:** `single node rancher`
**Environment Template:**` Kubernetes`
**Steps to Reproduce:**

**Results:**
After being notifed by an alert, I become aware of an impending diskspace problem with our cluster. 

![image](https://user-images.githubusercontent.com/722517/42974528-818e6cce-8b6c-11e8-8e2a-a37cc76286a6.png)

```bash
$ du -shc * | grep G
9.9G	f1751a5db2cac27aacfdb3257acab30c6d81601075992506e768c72c6ba83445
11G	total

$ du -shc * | grep G
10G	f1751a5db2cac27aacfdb3257acab30c6d81601075992506e768c72c6ba83445-json.log
10G	total

$ docker ps -a | grep f1751a
f1751a5db2ca        rancher/calico-node@sha256:21d581d7356f2dba648f2905502a38fd4ae325fd079d377bcf94028bcfa577a3                               "start_runit"            7 days ago          Up 7 days                                         k8s_calico-node_canal-zv5r7_kube-system_dce4cbe4-8574-11e8-a396-0a49d488ea2e_0
```

I am currently unsure of the best way to handle this issue moving forward. It seems to me that there should be a mechanism handling the log rotation, but as it stands now I expect my cluster to go down as the disk space gets maxed out.

**Comment by taariq** [comment]
@sirwolfgang no log rotation tools? Really?

**Comment by sirwolfgang** [comment]
Looks like the containers are rotated after a week.

**Comment by bradjones1** [comment]
@sirwolfgang Do you mean the logs are rotated or the containers are? I am experiencing this myself but the container has been up 2 weeks, which seems right to me but it's longer than one week, and the logs are eating disk, similar to your experience.

**Comment by sirwolfgang** [comment]
@bradjones1 The containers, I ended up expanding my hard disk storage a fair amount. Seems to be fine atm.

**Comment by Xat59** [comment]
Hi guys,

I have exactly the same issue. There is a long term solution ? How to reduce log retention of those containers ?
