### ISSUE TITLE
Add UI for drain 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#14643]
Drain action already shows up in UI, just need to set the input. 

- to call `drain` from API, the input would look like - 
```
curl -u $token --insecure -H 'Content-Type: application/json' https://localhost:8443/v3/nodes/local:machine-k6ct9?action=drain-X POST -d '{"deleteLocalData":"true","force":"false","gracePeriod":"-1","ignoreDaemonSets":"true","timeout":"20"
``` 

- when `draining` is ongoing, it can be stopped using `stopDrain` action 

- Information about the params and default values - 
```
type NodeDrainInput struct {
	// Drain node even if there are pods not managed by a ReplicationController, Job, or DaemonSet
	// Drain will not proceed without Force set to true if there are such pods
	Force bool `json:"force,omitempty"`
	// If there are DaemonSet-managed pods, drain will not proceed without IgnoreDaemonSets set to true
	// (even when set to true, kubectl won't delete pods - so setting default to true)
	IgnoreDaemonSets bool `json:"ignoreDaemonSets,omitempty" norman:"default=true"`
	// Continue even if there are pods using emptyDir
	DeleteLocalData bool `json:"deleteLocalData,omitempty"`
	//Period of time in seconds given to each pod to terminate gracefully.
	// If negative, the default value specified in the pod will be used
	GracePeriod int `json:"gracePeriod,omitempty" norman:"default=-1"`
	// Time to wait (in seconds) before giving up for one try
	Timeout int `json:"timeout" norman:"min=1,max=10800,default=60"`
}
``` 

https://github.com/rancher/rancher/issues/14265

**Comment by loganhz** [comment]
Hi @kinarashah Please let me know once backend is ready

**Comment by kinarashah** [comment]
@loganhz  backend should now be available in master

**Comment by loganhz** [comment]
@kinarashah Created a PR for adding drain and stop drain action in UI

But it looks like `stopDrain` doesn't show in API for a draining node. 
![321534915619_ pic_hd](https://user-images.githubusercontent.com/21168270/44444372-19a89900-a60f-11e8-9177-54457d6a4586.jpg)

**Comment by kinarashah** [comment]
Thanks @loganhz, I'll look into it

**Comment by loganhz** [comment]
@kinarashah  StopDrain is already in the rancher/rancher:master. But it becomes `Cordoned` after `StopDrain`.

**Comment by kinarashah** [comment]
Yeah, @loganhz this is expected, since drain also cordons the node. I'd add it to our docs

**Comment by tfiduccia** [comment]
@loganhz @kinarashah - Once I Stop Drain, it is still Cordoned.  Shouldn't it also be Uncordoned when I stop the drain so it reverts to being just "Active"?

**Comment by kinarashah** [comment]
@tfiduccia  it is k8s behavior that when you stop an ongoing drain process, the node still remains into cordoned state. I agree this can be new to someone who isn't acquainted to k8s, but we'll need to document it

**Comment by tfiduccia** [comment]
Version - 2.1 master 8/30
Verified fixed
