### ISSUE TITLE
Test around workload updates specifically labels/annotations

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14641]
We are making some changes to accommodate Rio, that may have impact on updates. 

There are some workload API updates and updates on labels/annotations that need to be checked for regressions.

**Comment by sangeethah** [comment]
@adingilloRancher Can you test use cases specific to  workload API updates and updates on labels/annotations to make sure no regressions are seen?

**Comment by galal-hussein** [comment]
rancher/rancher:master at July 25th

I tested creating/deleting/updating workloads and tried updating labels and annotations for workloads and changing scale as well, all seems to be working fine.

**Comment by deniseschannon** [comment]
@galal-hussein can you try with an upgraded scenario as well?

**Comment by galal-hussein** [comment]
@deniseschannon upgrades are broken because of the bug https://github.com/rancher/rancher/issues/14733

**Comment by galal-hussein** [comment]
@deniseschannon i was able to test upgraded scenario and confirm that label/annotations works as expected with workloads.
