### ISSUE TITLE
Unable to scale number of pods / replicas in a workload to 0 via Rancher UI

### ISSUE THREAD

**Issue by Nessex** [rancher/rancher#14654]
Rancher versions:
v2.0.6

Infrastructure Stack versions:
Kubernetes 1.9.6

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
AWS EC2

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
Single Node Rancher

Steps to Reproduce:
    Create a workload (anything will do)
    Set the number of pods/replicas to > 0 if it isn't already
    Try to edit the workload back to 0 pods/replicas via the rancher Edit Workload UI

Results:
    UI automatically changes the 0 you typed into a 1, and forbids submitting a value of 0. Particularly confusing when it changes as you click Update.

This seems to be an arbitrary restriction, the number of pods/replicas can be set to 0 by editing the deployment through kubectl and deploying initially with 0 replicas also works just fine, with the workload appearing in rancher correctly.

Our intended workflow (Continuous Delivery) is to leave a old version of a helm chart deployed when we do a blue/green deployment, however the old version should be scaled down to 0 until we know we need it.

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/14627
