### ISSUE TITLE
[Feature] Rancher 2 & Clusters Templates

### ISSUE THREAD

**Issue by Coopyrightdmin** [rancher/rancher#14655]
Hi,

I am not aware about any feature request process but two missing features will be highly appreciated when setting up clusters in future releases.

1. **Template sharing between users** when having same authorizations. Presently, 2 admins can see the same cluster but cannot edit a common cluster template
2.  **Templates copie**s: especially when having to create multiple machines configurations from the same provider

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`` `admin`|
|Route|`authenticated.node-templates`|

**Comment by superseb** [comment]
Does https://github.com/rancher/rancher/issues/14337 and https://github.com/rancher/rancher/issues/12186 cover this?

**Comment by Coopyrightdmin** [comment]
Hi @superseb, basically yes. 
We would like to reuse (edit/copy) and share templates between users with admin priviledges

**Comment by superseb** [comment]
Ok thanks, lets use those issues and add your requests if there is something missing.
