### ISSUE TITLE
维护部署后，Pods疯狂增加

### ISSUE THREAD

**Issue by gitzhang** [rancher/rancher#14653]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.3` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`containers.index`|

![image](https://user-images.githubusercontent.com/2832192/42984706-8ada360a-8c20-11e8-8e96-f94cb75451f2.png)

**Comment by loganhz** [comment]
It looks like there is no space left on your dick. Please re-submit your issue in English if there is space left on your node. Thanks
