### ISSUE TITLE
transitioningMessage contains twice the logline

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14658]
Version: master 7/20

transitioningMessage is duplicated

<img width="1303" alt="screen shot 2018-07-20 at 13 11 45" src="https://user-images.githubusercontent.com/2620179/42999582-9df8102e-8c1e-11e8-869c-c8c1d4a0d141.png">

```
"state": "provisioning",
"transitioning": "error",
"transitioningMessage": "[pre-deploy] Pulling image [rancher/hyperkube:v1.10.5-rancher1] on host [x]; [pre-deploy] Pulling image [rancher/hyperkube:v1.10.5-rancher1] on host [x]",
"type": "cluster",
```

**Comment by galal-hussein** [comment]
rancher/rancher:master at july 25th

I was able to confirm that transition messages are not duplicated:
```
state": "updating",
"transitioning": "yes",
"transitioningMessage": "[hosts] Cordoning host [x.x.x.x]",
```
