### ISSUE TITLE
Unable to edit target labels of ClusterIP Service created outside Rancher 2.0

### ISSUE THREAD

**Issue by mattparkes** [rancher/rancher#14650]
**Rancher versions:**
v2.0.6

**Infrastructure Stack versions:**
Kubernetes 1.9.6

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Steps to Reproduce:**

1. Create a Kubernetes Service outside of Rancher and apply with `kubectl apply -f service.yaml`
2. Run `kubectl get service` and note that it is of type ClusterIP and has an IP Address assigned
2. Edit the Service under **Workloads > Service Discovery**
3. Ensure "_The set of pods which match a selector_" is checked and adjust any of the labels (either an existing one or add a new one)

**Results:**

`Validation failed in API: Service "myservice" is invalid: spec.clusterIP: Invalid value: "None": field is immutable`

It kooks like Rancher is trying to set the ClusterIP to None, rather than just leaving it alone.

**Comment by loganhz** [comment]
It looks like the `clusterIP` field will always be set to `None` in backend.

@vincent99 Do we need to fix it?

**Comment by mattparkes** [comment]
I ended up just doing my a dead basic UI with React to solve my problem and had to handle this myself anyway.

It looks like Rancher is re-sending the entire document (via PUT or POST), rather than doing a PATCH and only sending the changed parts.

**Comment by vincent99** [comment]
> It looks like Rancher is re-sending the entire document (via PUT or POST), rather than doing a PATCH and only sending the changed parts.

This is true, but not relevant.. PUTting something the API gave you back to itself should always be valid.

**Comment by orangedeng** [comment]
As @alena1108 suggest, we should distinguish create and update operation for dns record. Only init clusterIp to None/empty when creating dns record. We should not change cluster ip when updating dns record.

**Comment by alena1108** [comment]
@carolynhu to validate

**Comment by carolynhu** [comment]
Steps to validate this issue:
1. Create a service `my-nginx`: `kubectl --kubeconfig  kube.config create -f service.yaml`
Which is `ClusterIP` type:
➜  rancher git:(master) kubectl --kubeconfig kube.config get service
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP      10.43.0.1      <none>        443/TCP        1h
my-nginx     ClusterIP      10.43.83.132   <none>        80/TCP         5s
2. Go to UI, under `Workloads`-> `Service Discovery` section, 
<img width="969" alt="screen shot 2018-09-13 at 1 05 09 pm" src="https://user-images.githubusercontent.com/29208297/45512785-adc0d880-b755-11e8-8375-bd4cb72f0341.png">

Edit this service, like add one more Lable, foo==bar.
<img width="977" alt="screen shot 2018-09-13 at 1 06 02 pm" src="https://user-images.githubusercontent.com/29208297/45512839-d1841e80-b755-11e8-9c34-8b4b9714aca4.png">

Return 200 code, Update successfully.
