### ISSUE TITLE
Cordon host triggers Node alert

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14659]
When you Cordon a node in the UI, you get the following alert:

```
Alert: Node seb-rancheragent-0-all is not active.
```

Output of `kubectl get nodes`:
```
seb-rancheragent-0-all   Ready,SchedulingDisabled   controlplane,etcd,worker   6m        v1.10.5
```

**Comment by aiwantaozi** [comment]
![image](https://user-images.githubusercontent.com/5936271/43246188-6ef59cd2-90e3-11e8-930e-70840fe2c80d.png)
@superseb Do you mean here? If so, we need UI to help fix it.

**Comment by superseb** [comment]
Yes

**Comment by aiwantaozi** [comment]
![image](https://user-images.githubusercontent.com/5936271/43246707-0e059fba-90e5-11e8-9a61-d664c81deaec.png)

I see the node is under cordoned state, may UI need show this state @deniseschannon could you help get UI part to check this issue?

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
