### ISSUE TITLE
take out embedded target from logging and add fluentd target

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#14651]
1. take out embedded log target now
2. comment to let user use catalog as a normal es in release note
3. test them

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/14

Validated basic unsecured logging to fluentd

Todo (requires secured forward input plugin): 
* shared auth key
* basic auth
* tls

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc4

Requires Secure Forward Input plugin for auth options. 

The following all work correctly:
* Shared auth key
* Basic auth
* TLS
* Multiple targets
