### ISSUE TITLE
[ipsec] New logic for connectivity check

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#14666]
Rancher: 1.6.*

IPSec itself has Dead Peer Detection enabled which would reinitiate the tunnel with the dead peer. We could use this logic to expose it's health state.

This would make the peer checking logic redundant currently used in connectivity checker.

But we need to move the http server for exposing the healthstate inside the ipsec-router itself as we need access to the strongswan socket to query for the tunnels state.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
