### ISSUE TITLE
Suddenly Failed Github authentication

### ISSUE THREAD

**Issue by argha0977** [rancher/rancher#14661]
I have a fully configured Rancher and some applications are running in production environment. But few days ago when I tried to login to my rancher shown an error message **Internal Server Error**.  After searching in google I didn't find any solve, I restarted the rancher service. After that when I am trying to login to the rancher in my browser Github authentication is not working and behaving as if a new rancher instance. No environments are showing. 
Please help me how to get back my environments?
Thanks in advance.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.waiting`|

**Comment by superseb** [comment]
Probably hitting https://github.com/rancher/rancher/issues/11553, can you check? It is really time to upgrade.

**Comment by superseb** [comment]
Closing as stale.
