### ISSUE TITLE
Switching to new environment cause network error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1466]
v0.27.0-rc1
1.  Create a new environment
2.  Switch to that environment from the manage environments page

Results:  Network error is being thrown in dev tools
WebSocket connection to 'ws://130.211.172.121:8080/v1/subscribe?eventNames=resource.change&include=hosts&include=instances&include=instance&include=loadBalancerConfig&include=loadBalancerTargets&include=loadBalancerListeners&include=instanceLinks&include=ipAddresses&projectId=1a9' failed: Invalid frame header

Expected:
No error

**Comment by vincent99** [comment]
This is just a side effect of the socket closing...
