### ISSUE TITLE
NGINX ingress 0.16.2 won't start due to mkdir: permission denied

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14660]
Version: master 7/20

```
> kubectl logs -n ingress-nginx nginx-ingress-controller-628cq
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    154a606-dirty
  Build:      154a606
  Repository: git@github.com:rancher/ingress-nginx.git
-------------------------------------------------------------------------------

F0720 11:35:29.916520       6 main.go:64] mkdir /ingress-controller/ssl: permission denied
```

Probably needs a definition update according to https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.16.2:

```
Breaking changes:

Running as user requires an update in the deployment manifest.

  securityContext:
    capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    # www-data -> 33
    runAsUser: 33
Note: the deploy guide contains this change

```

**Comment by sangeethah** [comment]
All automation tests relating to ingress reports failure.

**Comment by galal-hussein** [comment]
i can still see the problem after adding the security context to the template, using the official image for ingress nginx worker correctly:
```
system_images:
    ingress: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.16.2
```
our image is broken for some reason `rancher/nginx-ingress-controller:0.16.2-rancher1`

**Comment by deniseschannon** [comment]
Reverted to the previous nginx ingress controller version to fix master. 

@sangeethah we can close this if master is working and will track testing the latest nginx ingress image with #13294

**Comment by orangedeng** [comment]
@alena1108 @deniseschannon  I am use `tag-and-build.sh` to build the [ingress-nginx](https://github.com/rancher/ingress-nginx) with tag `0.16.2-rancher1`.
This is the image I build `reg.cnrancher.com/orstar/nginx-ingress-controller:0.16.2-rancher1`. I tested it in v2.0.6 by updating the ingress image and delete the daemon set pod and it works.
And I tested `rancher/nginx-ingress-controller:0.16.2-rancher1` and got the same errors in this issue.
I would like to check what is wrong while we are building this image.

**Comment by orangedeng** [comment]
As I noticed the build info in `rancher/nginx-ingress-controller:0.16.2-rancher1` and `reg.cnrancher.com/orstar/nginx-ingress-controller:0.16.2-rancher1`. It is unusual that we have following build info.
```
  Release:    154a606-dirty
  Build:      154a606
```
My build info is
```
  Release:    0.16.2-rancher1
  Build:      d36d4cc
```

**Comment by alena1108** [comment]
@orangedeng @deniseschannon I've initially built it using dapper. Rebuilt it using tag-and-build.sh and re-pushed.

**Comment by deniseschannon** [comment]
@orangedeng can you re-test with the updated image and then if it's working, make a new PR to add in the image again?

**Comment by deniseschannon** [comment]
@bmdepesa can we run automation to confirm that the updated ingress controller is not hitting this issue?

**Comment by bmdepesa** [comment]
Running on master now -- will update this comment with results when it's completed.
