### ISSUE TITLE
Region Option for Azure node template is unavailable

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#14677]
**Rancher versions:**
master 7/21

**Steps to Reproduce:**
1. Add a nodetemplate and choose Azure provider

**Results:**
1. No options found in Region dropdown.
2. When I switch `Environment` from the default to `AzureGermanCloud`, I see error in console:
![image](https://user-images.githubusercontent.com/5697937/43034855-ecab5408-8d16-11e8-95bc-c212c6c175c1.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/26
Verified fixed
