### ISSUE TITLE
v2 HA install is not highly available

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#14670]
**Rancher versions:**

2.0.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

qemu virtualized nodes under Proxmox VE 5.2.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Followed [these instructions](https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/)

**Results:**

After following the above, I have a working v2 installation with RKE. It works fine until I try to do anything HA with it. If I shut down one of the nodes, I can no longer reach the WebUI, (I get a 503 from the ingress controller), and none of the workloads restart on the other nodes.  CPU utilization on the remaining two nodes goes to 100% and load begins to climb. The machines become sluggish.

If I power the downed node back up, everything starts working again. During the outage, workloads on the other two nodes continue to function, but the cluster behaves as though it needs all three to be online in order to work. I'm unable to talk to the cluster with `kubectl`, either directly or through the load balancer - requests to `:6443` time out.

I have two separate RKE/Rancher v2 installations that show the same behavior.

Has anyone tested that the HA instructions result in something that is actually HA? Can the instructions include steps for testing HA and expected results? What do you recommend for troubleshooting this, since I can't talk to the cluster unless all three nodes are online?

**Comment by leodotcloud** [comment]
@oskapt The answer in this SO question gives more explanation about rescheduling of Pod in k8s: https://stackoverflow.com/questions/41926177/kubernetes-rescheduling-of-pods-after-a-node-becomes-unreachable

**Comment by oskapt** [comment]
hi, guys. thanks for responding. i suppose i was just lucky in always choosing the node where the rancher pod was running, and i didn't realize i needed to wait 6+ minutes for the pod to relaunch.

i don't want to get into a discussion about redefining "highly available" to be "eventually available," but i do think it's worth pointing out that a multi-minute outage of a critical component is not HA.

it might be worthwhile to frame expectations in the referenced installation guide, since every other system that purports to be HA can almost instantly survive the destruction of one of its nodes. it's okay that Rancher v2 cannot do so yet, or that you're hampered by k8s not handling failovers in a timely fashion. being clear about that will prevent users like myself shooting nodes in the head and then wondering why everything collapsed.

keep up the good work, though. rancher is still, hands-down, the most awesome thing in the space.
