### ISSUE TITLE
ho to cleanup single node-setup

### ISSUE THREAD

**Issue by XzenTorXz** [rancher/rancher#14678]
**Rancher versions:** rancher/rancher:2.0.6 docker image

**Docker version: (`docker version`,`docker info` preferred)** 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04.4 LTS

**Steps to Reproduce:**
- create cluster add a node (same machine)
- remove docker containers + images + volumes + network
- reinstall ranger

**Results:**
some very weird behavior:
- cant use "default" namespace for workloads
- sometimes you just get an empty error (red box with no message) when creating a workload

how do you completely remove rancher from a system ? I have to reset the whole server to get it working again.

**Comment by superseb** [comment]
Can you follow the steps described in https://github.com/rancher/docs/pull/430

**Comment by XzenTorXz** [comment]
thank you, now it works like expected
