### ISSUE TITLE
Non-standard location for '/var/lib/kubelet/volumeplugins' in RancherOS is causing FlexVolume plugins to be unusabe (rook.io / Longhorn)

### ISSUE THREAD

**Issue by Iodun** [rancher/rancher#14675]
**Rancher versions:**
rancher/rancher:latest (2.0.6)

When deploying a cluster with RancherOS, RKE will deploy Kubelet without bind-mount of **/var/lib/kubelet**, because **/opt/rke/var/lib/kubelet/** is used instead.

Nevertheless Kubelet will get executed with **--volume-plugin-dir=/var/lib/kubelet/volumeplugins** and therefore FlexVolume plugins like **rook.io** and **Longhorn** don't work.

`kubelet --hostname-override=worker1 --cadvisor-port=0 --enforce-node-allocatable= --cni-conf-dir=/etc/cni/net.d --anonymous-auth=false --cluster-domain=cluster.local --read-only-port=0 --cni-bin-dir=/opt/cni/bin --cluster-dns=10.43.0.10 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --pod-infra-container-image=rancher/pause-amd64:3.0 --v=2 --address=0.0.0.0 --cgroups-per-qos=True --network-plugin=cni --resolv-conf=/etc/resolv.conf --allow-privileged=true --volume-plugin-dir=/var/lib/kubelet/volumeplugins --cloud-provider= --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --fail-swap-on=false --root-dir=/opt/rke/var/lib/kubelet --cgroup-driver=cgroupfs`

**How to fix:**
Run Kubelet with **--volume-plugin-dir=/opt/rke/var/lib/kubelet/volumeplugins** on RancherOS based Rancher 2.0 cluster.

**Similar / related issues:**
https://github.com/rancher/rke/issues/662
https://github.com/rancher/rancher/issues/13897
https://github.com/rancher/rke/pull/627

@sangeethah

**Comment by superseb** [comment]
This should be fixed in https://github.com/rancher/rke/pull/800 and in the next release. Let me know if you think it won't be solved.

**Comment by Iodun** [comment]
Thanks for pointing me to this PR.
I wasn't sure if persistence is actually required or not.
So essentially your plan is to fix it the same way that logging has been fixed.
The volume plugins are simply recreated on each reboot.

Can't this one also be closed now?
https://github.com/rancher/rancher/issues/13897
