### ISSUE TITLE
OpenLDAP user is related to the admin account

### ISSUE THREAD

**Issue by rfer** [rancher/rancher#14676]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.0.6

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Steps to Reproduce:**

1 - Setup OpenLDAP authentication and login with any LDAP user.
2 - Go to user preferences 

**Results:**

The account details for all users shows up as being the admin account, for which one can even attempt to change the password (see image).

![image](https://user-images.githubusercontent.com/25161/43034049-950a6bfc-8ccc-11e8-9832-68919b2b866e.png)

**Comment by vincent99** [comment]
It _is_ the admin account and you _can_ change the local password.  When you test and turn on a new form of auth the principal in that provider is associated with the account you're currently logged in as.
