### ISSUE TITLE
Ipsec containers on the host do not report as being unhealthy when ipsec.service.enable.healthcheck flag is turned on from off when host are still in disconnected state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14685]
Rancher server version - v1.9.18-rc8

steps to reproduce the problem:
Power down hosts.
Wait for the host to get to "reconnecting" and then "disconnected" state.
Ipsec container on the disconnected state continues to be reported as "healthy" which is as expected since ipsec.service.enable.healthcheck flag is turned off.

When hosts are still in powered down state , change the ipsec.service.enable.healthcheck flag is turned on.

Notice that the ipsec container on the disconnected host continues to reported as being in "healthy" state. 

Expected Behavior:
ipsec container on the disconnected host should report the ipsec state as being "uhealthy".

**Comment by kinarashah** [comment]
Since the hosts were already powered down when the flag was off, we missed the service events. And new ones are sent only when there's a change in the report status by the health check service. 
We should just document this.
