### ISSUE TITLE
jenkins deployment does not have minimum availability.

### ISSUE THREAD

**Issue by lanmingle** [rancher/rancher#14681]
cattle-pipeline：

jenkins deployment does not have minimum availability.

I didn't do anything.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.61` |
|Access|`` `admin`|
|Route|`containers.index`|

**Comment by lanmingle** [comment]
我已经知道这个问题是为什么了，因为 Jenkins 下载插件时无法下载。

个人建议：为了不影响使用，建议把插件一起打包在 docker 镜像中。

临时解决方法：

把 cattle-pipeline 移动到项目中，选这那个项目，选到配置映射，编辑 Jenkins 的配置映射，去掉初始化脚本 ：

``` bash
mkdir -p /var/jenkins_home/init.groovy.d
cp /var/jenkins_config/init.groovy /var/jenkins_home/init.groovy.d
cp -n /var/jenkins_config/config.xml /var/jenkins_home;
cp /var/jenkins_config/plugins.txt /var/jenkins_home;
rm -rf /usr/share/jenkins/ref/plugins/*.lock
/usr/local/bin/install-plugins.sh `echo $(cat /var/jenkins_home/plugins.txt)`;
```

删掉后：

``` bash
mkdir -p /var/jenkins_home/init.groovy.d
cp /var/jenkins_config/init.groovy /var/jenkins_home/init.groovy.d
cp -n /var/jenkins_config/config.xml /var/jenkins_home;
rm -rf /usr/share/jenkins/ref/plugins/*.lock
```

修改了配置后需要重新部署 pod ,把原来的 pod 删掉，即可。

接下来就是把这个 Jenkins 映射出来（端口或者域名），登录进入，下载这几个必须的插件即可：

```
kubernetes:1.1.4
timestamper:1.8.9
workflow-aggregator:2.5
workflow-job:2.17
credentials-binding:1.13
git:3.6.4
```

解决提示：#14091

**Comment by iwin4aids** [comment]
> 我已经知道这个问题是为什么了，因为 Jenkins 下载插件时无法下载。
> 
> 个人建议：为了不影响使用，建议把插件一起打包在 docker 镜像中。
> 
> 临时解决方法：
> 
> 把 cattle-pipeline 移动到项目中，选这那个项目，选到配置映射，编辑 Jenkins 的配置映射，去掉初始化脚本 ：
> 
> ```shell
> mkdir -p /var/jenkins_home/init.groovy.d
> cp /var/jenkins_config/init.groovy /var/jenkins_home/init.groovy.d
> cp -n /var/jenkins_config/config.xml /var/jenkins_home;
> cp /var/jenkins_config/plugins.txt /var/jenkins_home;
> rm -rf /usr/share/jenkins/ref/plugins/*.lock
> /usr/local/bin/install-plugins.sh `echo $(cat /var/jenkins_home/plugins.txt)`;
> ```
> 
> 删掉后：
> 
> ```shell
> mkdir -p /var/jenkins_home/init.groovy.d
> cp /var/jenkins_config/init.groovy /var/jenkins_home/init.groovy.d
> cp -n /var/jenkins_config/config.xml /var/jenkins_home;
> rm -rf /usr/share/jenkins/ref/plugins/*.lock
> ```
> 
> 修改了配置后需要重新部署 pod ,把原来的 pod 删掉，即可。
> 
> 接下来就是把这个 Jenkins 映射出来（端口或者域名），登录进入（账号密码可以在密文中查看），下载这几个必须的插件即可（忽略相关版本）：
> 
> 提示：
> 
> 需要把 Jenkins 插件更新地址修改为：https://updates.jenkins.io/2.107/update-center.json
> 
> ```
> kubernetes:1.1.4
> timestamper:1.8.9
> workflow-aggregator:2.5
> workflow-job:2.17
> credentials-binding:1.13
> git:3.6.4
> ```
> 解决提示：#14091
> 
> 试验了一下，觉得还是没有必要用这个 pipeline 了，这样的话出现问题很容易。

官方既然提供了offline-installer为什么不考虑把jenkins插件一起给打包到pipeline-jenkins-server中呢？搞不懂，还搞这么麻烦～～哎
