### ISSUE TITLE
Kubernetes api, scheduler, auth, kubernetes-agent cannot find rancher metadata

### ISSUE THREAD

**Issue by Teeina** [rancher/rancher#14688]
**Rancher versions:**
rancher/rancher: v 1.6.14

**Infrastructure Stack versions:**
healthcheck: 2
ipsec: 2
network-services: 2
scheduler: 
kubernetes (if applicable): rancher/k8s:v1.8.10-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04 4.13.0-36-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Set up rancher environment
Add kubernetes host

**Results:**
All the status of containers inside kubernetes except kubelet, kubectld and proxy are unhealthy and they are keep restarting. For the logs inside these containers, it always looping:
+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
Waiting for metadata
+ echo Waiting for metadata
+ sleep 1
+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
Waiting for metadata
+ echo Waiting for metadata
+ sleep 1

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
