### ISSUE TITLE
Empty configuration map values are removed by Rancher UI when editing, causing future deployments to fail

### ISSUE THREAD

**Issue by advancingu** [rancher/rancher#14689]
**Rancher versions:**
rancher/rancher: 2.0.2

**Steps to Reproduce:**
1. Upload a configuration map from a definition file (i.e. `KEY=abc` format) to cluster with `kubectl` where a configuration map key is defined with empty value (i.e. `KEY=`) and where another non-empty key is defined.
2. Open the configuration map overview in Rancher and note that both keys are shown for the given configuration map.
2. Edit this configuration map in Rancher.

**Results:**
* Upon editing, all empty keys are deleted.

Expected:
* Keys with empty values shall remain. The reason is that such definitions are valid in Kubernetes and that they can be referenced by deployment configurations. When a key is deleted completely by the Rancher UI and then the configuration map is saved, any containers that reference the key it will now fail to deploy.

Notes: I removed all infrastructure items as this appears to be a UI only issue.

**Comment by loganhz** [comment]
Fixed. Thanks for your report!

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
