### ISSUE TITLE
Show more info/add more checks in agent

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14691]
Add in checks for common issues:

- Firewall/ACL blocking connecting to server-url
- Unable to resolve configured server-url

**Comment by moelsayed** [comment]
Tested with master 08/06, all the following checks are working as expected:

-    Print all given arguments (redacted token)
-    Print all environment variables (redacted token)
-    Print resolv.conf nameserver entries
 -   Warn when loopback address found in resolv.conf
 -   Accessibility check to $CATTLE_SERVER/ping
 -   Check if retrieved cacerts is an actual certificate
