### ISSUE TITLE
can't change name of certificates

### ISSUE THREAD

**Issue by char-iot** [rancher/rancher#14693]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.4
rancher/agent or rancher/rancher-agent:v2.0.4

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
v17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16 lts 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere | vCenter

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
add certs and then edit them to change their names, after refresh names remain the same.

**Results:**
sometimes when names doesn't match, then ingress won't force redirect.

**Comment by loganhz** [comment]
k8s doesn't allow to update cert name. Rancher UI will not allow user to edit it. Thanks

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/26
Verified fixed

**Comment by char-iot** [comment]
thanks a lot
