### ISSUE TITLE
Azure Sizes Standard_Ax_v2

### ISSUE THREAD

**Issue by Flowman** [rancher/rancher#14692]
**Rancher versions:**
rancher/rancher: 2.0.6

Noticed that all Azure Standard_Ax_v2 machines are missing in the azure template. It would be nice to add them in as they have updated hardware and better pricing.

**Comment by loganhz** [comment]
Added.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#av2-series

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/26
Verified fixed
