### ISSUE TITLE
Add an option to hide the footer so that users cannot file an issue or access forums or Slack 

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#14698]
Remove this 
![image](https://user-images.githubusercontent.com/5438983/43101352-08b0d198-8e7d-11e8-8798-576bb90cfa6d.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by deniseschannon** [comment]
@vincent99 has mentioned this was possible using the `ui-pl` setting. By using a private label, it's supposed to hide these things.

**Comment by tfiduccia** [comment]
@dxxxxxg, this is indeed correct.  If there is anything other than Rancher in the ui-pl in the settings page, the Help & docs, Forums, Slack, File an issue links go away.  Closing this issue.
![image](https://user-images.githubusercontent.com/11514927/45060028-1ff93500-b053-11e8-8fd4-dc129c76dc72.png)
