### ISSUE TITLE
Upgrade strategy for Alert/Logging/Pipeline system images

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#14696]
Currently any updates for  Alert/Logging/Pipeline images result in update for existing list https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/k8s_defaults.go#L321

As a result, the changes will apply for any newly created system stack, but the existing ones won't get upgraded. We should think of the upgrade strategy, and implement something in line with:

```
AlertVersionToSystemImages map[string]AlertSystemImages // key is the version
AlertSystemImages
DefaultAlertVersion string
```
When introduce a new image, new key gets added to the AlertVersionToSystemImages, and DefaultAlertVersion gets bumped up.

Whenever rancher gets upgraded to the types, there should be a code to figure out whether the version for existing pipeline/logging/alert stack differs from the DefaultAlertVersion, and the upgrade should be performed if so.

Or may be you don't even need the `AlertVersionToSystemImages`, and we can just bump up the `DefaultAlertVersion` when the new image is introduce to signal that the upgrade needs to be performed. Up to you.

**Comment by aiwantaozi** [comment]
Hi @alena1108 Lawrence and I think can we do this:
1.  We may not need AlertVersionToSystemImages now, just bump up to the default version.
2. After rancher server upgrade, we will watch project resource, get system project, in sync function, check if the system project existed then check the system image (alert/logging/pipeline) version, upgrade system images to the default configured version. 
3. The code may like https://github.com/rancher/rancher/blob/master/pkg/controllers/management/auth/project_cluster_handler.go#L130 but in userContext not managementContext.

How do you think?

**Comment by alena1108** [comment]
@aiwantaozi that sounds good, but could you elaborate on `check the system image (alert/logging/pipeline) version`  - are you going to: a) store the version somewhere on the object? And then access the object.version to figure out the current version and compare it with the default or b) you are going to check every system image of pipeline/log/alert? Looks like a) is better aligned with the solution you are proposing when only default version is stored.

Also do you think we should introduce separate default versions for pipeline, logging, alerting?

**Comment by aiwantaozi** [comment]
Hi, we may simple store a default version like current, and change the struct to map, and let the alert/logging/pipeline image version have same struct. Do u think we need card to store the image version, look like we it’s won’t edit by user and we don’t need controller for it. And because we need to get these system workload, so we need add some labels for them.

For separate alerting/logging/pipeline image version, we may flat them to a map.

**Comment by gitlawr** [comment]
We can add version annotations to system namespace on deployment for comparison. And I think one default version for all components is probably enough?

**Comment by alena1108** [comment]
@gitlawr `We can add version annotations to system namespace on deployment for comparison` - sounds good. Make sure you handle the upgrade for the namespaces that were created prior to 2.0.7, the ones that don't have annotation.

`And I think one default version for all components is probably enough?` - what will happen if only alert images got changed? Would you run pipeline/logging upgrade given that the version got changed?

**Comment by gitlawr** [comment]
when version is not match, we still check the image version and do upgrade when image version is changed(in this case no upgrade is needed). After that, update annotation to the new version.

**Comment by aiwantaozi** [comment]
Pre test:
We will automatically upgrade the system image for user when user upgrade the server to new version.
You could see the latest tools system image version under 
https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/k8s_defaults.go#L58

Some test case:
1. Alert/Logging/Pipeline use the old version and upgrade to new rancher server, the tools images should be upgraded, and Alert/Logging/Pipeline could work well (could change the image in system workload to make the old version different from the latest version)
2.  1. Alert/Logging/Pipeline already use the latest version and upgrade to new rancher server, the tools images should not be upgraded, and Alert/Logging/Pipeline could work well

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc7

Start with rancher/rancher:v2.0.8
* Added alerts
* Added logging (one embedded, one syslog)
* Added pipelines

Upgraded to rancher/rancher:v2.1.0-rc7
* systemImageVersion annotation is present on System project
* Images are updated
* Alerts function correctly 
* Embedded logging target containers were removed successfully
* Syslog logging target still functioning
* Pipeline functions after re-authorizing (due to refactor)

Upgrade to rancher/rancher:master (no change to images)
* systemImageVersions annotations do not change
* Images are not updated
