### ISSUE TITLE
three submenu broken into two main menu and reusing Stack multiple times

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1470]
v0.27.0-rc-1

Couple of issue with the menu bar on top:
1.  There are only three submenus - seems excessive to have two main menus
2.  Application main menu only has Stacks submenu, which is the only submenu that goes to Stacks page.

Results:
Seems bulky

**Comment by vincent99** [comment]
There will be more sections to go under both top-level tabs soon.
