### ISSUE TITLE
Rancher v1.6 rancher/metadata:v0.10.2 does work correctly with RHEL 7.5 SE Linux

### ISSUE THREAD

**Issue by FFock** [rancher/rancher#14719]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.18
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck:
ipsec: rancher/net:v0.13.13
network-services: rancher/metadata:v0.10.2
scheduler: rancher/scheduler:v0.8.3

**Docker version:**
Containers: 62
 Running: 57
 Paused: 0
 Stopped: 5
Images: 30
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 5eda6f6fd0c2884c2c8e78a6e7119e8d0ecedb77 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-862.9.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.5 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
...

**Operating system and kernel: **
3.10.0-862.9.1.el7.x86_64

**Type/provider of hosts: **
T-Systems Private vCloud (VMWare)

**Setup details: **
single node rancher, external DB

**Environment Template: **
Cattle (Kubernetes is affected too)

**Steps to Reproduce:**
Create a new environment for a Rancher with a internal certificate (Intranet, custom). Add a single host. IPSec network is not working because Metadata is not available. This is because the metadata container is not using the CA provided to the host OS in /var/lib/rancher.
Workaround: Change Volume mount options of the  rancher/metadata:v0.10.2 container to:
/var/lib/rancher:/var/lib/rancher:z

**Results:**
IPSec connectivity is not available in the environment unless rancher/metadata:v0.10.2 is upgraded with /var/lib/rancher:/var/lib/rancher:z volume mount.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
