### ISSUE TITLE
Make volumeId as a required field when create AWS EBS PV

### ISSUE THREAD

**Issue by khainguyen95** [rancher/rancher#14714]
*Describe your issue here*

I try to add news Persistent Volume but got an error.
```
persistentvolumes "test" is forbidden: error querying AWS EBS volume : Invalid format for AWS volume ()
```
what is my problem here?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.storage.persistent-volumes.new`|

**Comment by michalmikolajczyk** [comment]
It is possible to create a PVC directly from project level by requesting a new PV – Rancher manages to create the volume on AWS.

The error reported seems to apply only to trying to create a new PV from the Volumes view on cluster level.

**Comment by vincent99** [comment]
What is an issue?  Creating a PV directly means you are pointing at an existing volume in EBS.

You need a cluster that has the Amazon cloud provider configured properly, a volume id that exists, and (to do anything useful with it, if not on add) a node that is in the same zone.

**Comment by ekristen** [comment]
Oh I see. @vincent99 can we make volume ID required and make it a little more clear that the EBS volume must first exist? 

Can I also ask why it requires it to first be created vs create for you? Just curious on the reasoning.
