### ISSUE TITLE
Certificate SANs not stored correctly

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14718]
Version: master 7/24

subjectAlternativeNames on certificates is not correctly being handled by the mapper, it should be stored as List.

This needs a change in types and in the UI.

**Comment by superseb** [comment]
Create certificate with alt names:
```
docker run -v $PWD/certs:/certs -e SSL_SUBJECT="rancher.yourdomain.com" -e SSL_DNS="rancher.yourdomain.com,rancher2.yourdomain.com" -e SSL_IP="127.0.0.2,127.0.0.3" paulczar/omgwtfssl
```

To reproduce the bug:
Add key and cert, open the added certificate in the UI and see no alt names showed in the certificate detail view.

To validate the fix:
Add key and cert, open the added certificate in the UI and see the alt names shown in the certificate detail view.

**Comment by cjellick** [comment]
@dramich to validate

**Comment by dramich** [comment]
Following @superseb's instructions above, prior to the fix only one domain shows under the `Domain Names` section in the UI. 

After the fix all domains show in the UI and in the `subjectAlternativeNames` in the API.
