### ISSUE TITLE
Namespace gets created with an invalid resourceQuotaTemplateId

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#14723]
**Rancher versions:**
rancher/server or rancher/rancher:master

**Steps to Reproduce:**
1. Create a namespace in API and provide an invalid resourceQuotaTemplateID
Namespace gets created without any errors. Validation for a valid resourceQuotaTemplateID should exist.
<img width="1212" alt="screen shot 2018-07-24 at 11 15 52 am" src="https://user-images.githubusercontent.com/18536626/43157844-ff253f4a-8f32-11e8-9f37-3171e2fd4bc0.png">

**Comment by alena1108** [comment]
No longer applicable given the refactor https://github.com/rancher/rancher/pull/15219 getting rid of resource quota template concept; closing the issue
