### ISSUE TITLE
How to change flannel and node IP when using two interface on one of the node

### ISSUE THREAD

**Issue by Sh4d1** [rancher/rancher#14721]
**Rancher versions:**
rancher/rancher:latest
rancher/agent:v2.0.6

**Docker version: (`docker version`,`docker info` preferred)**
18.06

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian 9 - 4.9.0-7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Baremetal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
I'm creating a two nodes cluster with rancher. Both are Debian 9, running Docker 18.06. 
One of the nodes have 2 interfaces: enp1s0 and enp1s0:0. 
I'm joining the nodes with the IP from enp1s0:0 (with `--address` and `--internal-address`
). 
From the rancher dashboard I see both IP (from enp1s0 and enp1s0:0) but when I run `kubectl get pods --all-namespaces -owide`,  I see only the IP from enp1s0. 
Also canal cannot start:
On the node with 2 IPs:
```
I0724 15:39:06.530336       1 main.go:487] Using interface with name enp1s0 and address x.x.x.x (IP of enp1s0)
I0724 15:39:06.530900       1 main.go:504] Defaulting external address to interface address (x.x.x.x)
```
On the other node: 
```
E0724 16:10:45.498057       1 main.go:231] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/canal-x8ctb': Get https://10.43.0.1:443/api/v1/namespaces/kube-system/pods/canal-x8ctb: dial tcp 10.43.0.1:443: i/o timeout
```
I have a timeout because it tries to connect to the IP linked to enp1s0 and not to the one linked to esnp1s0:0 (The first one is banned in Russia).

So I'm trying to understand why canal is selecting the IP from enp1s0 instead of the one from enp1s0:0. 

Any idea?

**Comment by dwitzig** [comment]
try setting the canal interface when you deploy the cluster 
```
      network:
        plugin: "canal"
        canal_network_provider:
          iface: "enp1s0:0"
```
when deploying cluster click `Cluster Options` > `Edit as YAML`

**Comment by Sh4d1** [comment]
@dwitzig I think I tried that but the thing is that only one server has this interface. So if I set it there it won't work on the other servers

**Comment by deniseschannon** [comment]
Using the advanced options for your cluster, you can set the specific interface to be used:

https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/#network-plug-in-options
