### ISSUE TITLE
Implement rancher 2.0 terraform provider

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#14729]

**Comment by deniseschannon** [comment]
https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/amazon-aws-qs/

**Comment by rawmind0** [comment]
WIP... https://github.com/rawmind0/terraform-provider-rancher2

**Comment by rawmind0** [comment]
Version to test and review... https://github.com/rancher/terraform-provider-rancher2

**Comment by cjellick** [comment]
@cloudnautique ive moved this out of the v2.2 mileston. up to you to track separately

**Comment by cloudnautique** [comment]
The provider is available for use:
https://github.com/rancher/terraform-provider-rancher2#using-the-provider

We are working with Hashicorp to get the provider into the main provider organization, but that will take some time.
