### ISSUE TITLE
Can't find nodes when IP changed.

### ISSUE THREAD

**Issue by miclefebvre** [rancher/rancher#14720]
**Rancher versions: 2.0.4**

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Steps to Reproduce:**
* Create a new vSphere cluster with Rancher
* Stop the VMs of the cluster
* Start the VMs of the cluster with new IP adresses for each nodes
* I assume it would do the same thing with other type of cluster (custom ...)

**Results:**
Rancher mark our cluster as unavailable. 

**Expected behavior:**
There should be a way to update the node IP adresses from within Rancher so that our cluster stay usable.

**Comment by miclefebvre** [comment]
Some forum users that reported the problem : 

https://forums.rancher.com/t/update-node-ip-adresses/11232
https://forums.rancher.com/t/change-external-ip-of-aws-node/10889

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14102
