### ISSUE TITLE
Symlinks for RKE containers not created for worker only nodes in Custom clusters

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#14734]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.6
rancher/agent or rancher/rancher-agent: v2.0.6

Custom cluster worker nodes provisioned in AWS with Rancher OS v1.4.0 are not getting the /var/lib/rancher/rke/logs symlinks populated for kubelet logs. These should be linked for collection by log collectors.

**Comment by superseb** [comment]
Applies to worker only nodes in custom clusters on any OS, not just RancherOS. My test was on Ubuntu 16.04.

**Comment by cjellick** [comment]
@maxkorp to validate

**Comment by maxkorp** [comment]
Confirmed fixed on 1.19, broken on 1.18	
Steps:

1. Spin up 2 instances on AWS and install docker
2. spin up new cluster in RKE pointed to the nodes, with one only having worker role
3. SSH in to worker only node and run `ls -l /var/lib/rancher/rke/log`, 

Expect 4 entries.
