### ISSUE TITLE
Remove "Built-In" column on global roles page

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14739]
rancher/rancher:master 7/24

We should remove the "Built-In" column on the global roles page. 

Global roles do not have a "built-in" field in the API (so none are checked as being built-in), and we do not allow creation of new global roles; so the field does not have a purpose and might lead to confusion with users.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/26
Verified fixed
