### ISSUE TITLE
Modal background gets stuck

### ISSUE THREAD

**Issue by richburdon** [rancher/rancher#1473]
The grayed out modal background got stuck after clicking on the Rancher logo, but the "about" dialog doesn't show. JS error below:

Uncaught TypeError: Cannot read property 'slideDown' of undefined [ui.js:23]

**Comment by vincent99** [comment]
@richburdon What version of rancher is this in?  (I realize it would be easier to know that if you could see the about screen...)  I think this was fixed in the current `-rc` release.

**Comment by richburdon** [comment]
Rancher	v0.25.0
Cattle	v0.58.0
User Interface	v0.29.0
Rancher Compose	latest

**Comment by deniseschannon** [comment]
I haven't been able to reproduce on my v0.25.0 setup. @richburdon if you see it again, please reopen.
