### ISSUE TITLE
Add Keycloak as an auth provider 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14730]

**Comment by tookko** [comment]
Is this a duplicate of https://github.com/rancher/rancher/issues/10053 or integrating via a Keycloak specific protocol?

**Comment by alena1108** [comment]
UI should be in as well

**Comment by carolynhu** [comment]
@sangeethah groups related information updated in the set-up docs, please follow it to test group functionalities.

**Comment by tookko** [comment]
Does this support SSO also in case login against Keycloak was done with OIDC, or only when it was done using SAML?

**Comment by carolynhu** [comment]
@tookko We are currently only support SAML protocol.

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/12

Groups can be added to restricted access modes and function properly.
