### ISSUE TITLE
Locked roles are no longer displayed in UI

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14736]
rancher/rancher:master 7/24

Create a cluster or project role
Lock the role
The role is removed from the list of roles. It is viewable in the API, but is no longer shown in the UI w/ the locked state. (Edit: this is the roles list, not when adding a member to a cluster/project)

This also applies to built-in roles.

**Comment by loganhz** [comment]
Hi @vincent99

Is it by design? I looks like the locked role is filtered out .

https://github.com/rancher/ui/blob/master/lib/shared/addon/role-template/service.js#L30

**Comment by deniseschannon** [comment]
@bmdepesa when you say it's not in the UI, what section are you referrring to?

locked roles should be hidden when trying to add clusters/project members to clusters or projects. 

They should be displayed on the list of roles for admins or those who can manage roles.

**Comment by bmdepesa** [comment]
I am referring to the roles list for Global, Cluster, Project roles (not when adding members to cluster/project). 

If you edit a role to lock it, it is immediately removed from the roles list.

**Comment by deniseschannon** [comment]
This looks like a bug from the refactor from changing to one list for all roles to a couple of pages for roles.

**Comment by deniseschannon** [comment]
@loganhz we shouldn't be filtering these out.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
