### ISSUE TITLE
NodeTemplates may be shown to other users

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#14743]
**Rancher versions:**
master 7/25

**Steps to Reproduce:**
1. Log in as user A, go to node templates page.
2. Open another browser and log in as user B.
3. As the user B, go to node templates page and create a template.
 For example, choose Azure and fill in `Subscription ID/client ID/ client Secret/Name` with arbitrary text.

**Results:**
In the first browser as user A, I can see the newly created template pops up.

**Comment by gitlawr** [comment]
The resource is pushed via websocket stream. The `watch` behavior of proxy store is different from `list` in this case.

**Comment by loganhz** [comment]
duplicated of https://github.com/rancher/rancher/issues/13978
