### ISSUE TITLE
Health check parameters - option httpchk and  timeout check are incorrectly programmed in haproxy.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1474]
Server version - V0.27.0-rc1

Steps to reproduce the problem:

Created LB service for 2 services that have health check enabled.

Health check parameters for "option httpchk" and  "timeout check" in HA proxy configuration for the 2 services are the same , even though they were configured with different set of values.

```
test/health-new1:

        "healthCheck": {
            "interval": 4000,
            "responseTimeout": 5000,
            "healthyThreshold": 4,
            "unhealthyThreshold": 5,
            "requestLine": "GET /name.html HTTP/1.0",
            "port": 80
        },

test/health-new4:

        "healthCheck": {
            "interval": 6000,
            "responseTimeout": 7000,
            "healthyThreshold": 6,
            "unhealthyThreshold": 7,
            "requestLine": "GET /service1.html HTTP/1.0",
            "port": 80
        },

frontend fc5f2bfc-f6f2-43b4-ae1e-e5c92a6e1fad_frontend
        bind 10.42.203.95:80
        mode http
        acl -319266029_host hdr_end(host) -i www.new1.com
        acl -319266029_path path_beg -i /service2.html
    	use_backend fc5f2bfc-f6f2-43b4-ae1e-e5c92a6e1fad_-319266029_backend if -319266029_host -319266029_path
        acl -290636878_host hdr_end(host) -i www.new2.com
        acl -290636878_path path_beg -i /service2.html
    	use_backend fc5f2bfc-f6f2-43b4-ae1e-e5c92a6e1fad_-290636878_backend if -290636878_host -290636878_path

backend fc5f2bfc-f6f2-43b4-ae1e-e5c92a6e1fad_-319266029_backend
        mode http
        balance roundrobin
        timeout check 5000
        option httpchk GET /name.html HTTP/1.0
        server 70b33dd5-8e06-43a1-833a-713d6cda122a 10.42.250.9:80 check port 80 inter 4000 rise 4 fall 5
        server d9e7e968-5343-4978-a734-e2accf5c10bc 10.42.106.5:80 check port 80 inter 4000 rise 4 fall 5
        server 5ca94e04-f338-49a8-83af-714745bd8b5c 10.42.107.8:80 check port 80 inter 4000 rise 4 fall 5

backend fc5f2bfc-f6f2-43b4-ae1e-e5c92a6e1fad_-290636878_backend
        mode http
        balance roundrobin
        timeout check 5000
        option httpchk GET /name.html HTTP/1.0
        server 4c0fdd89-b84e-4b0e-89f8-47d022a63d5d 10.42.255.101:80 check port 80 inter 6000 rise 6 fall 7
        server e4518100-9da7-4e73-984c-b2f167f4915f 10.42.21.126:80 check port 80 inter 6000 rise 6 fall 7
        server 1cf1a935-0f66-436e-b92b-92650868e555 10.42.49.40:80 check port 80 inter 6000 rise 6 fall 7

```

**Comment by sangeethah** [comment]
Tested with build from master:

I am now able to see correct values being programmed for option httpchk and timeout check in haproxy when health check is enabled for the targets added to LB services.

**Comment by obenziane2** [comment]
I was wondering how you would add the health checks from the GUI for lb , rancher server v.1.2.2 ?

**Comment by vincent99** [comment]
@obenziane2 if you're just talking about adding a health check in general, they go on the service that is being targeted.  There's a tab when defining/upgrading the service to set the healthcheck and it doesn't require that a balancer is being used.  When the service is the target for a balancer it automatically users the health check.

The health check for the balancer containers themselves is automatically set and handled by Rancher.

**Comment by obenziane2** [comment]
@vincent99 thanks for your reply!

I'm more into the HAproxy backends health checks. Currently the LB does create a health check on the backends and i was wondering if there is a way to include it into the "custom haproxy.cfg" or somewhere else ?

backend 3002_myservice_rancher_demo_domain_com_
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_proto
mode http
server 10.42.193.125 10.42.193.125:3000

Thanks,


<img width="1366" alt="screen shot 2016-12-27 at 7 22 35 am" src="https://cloud.githubusercontent.com/assets/11947294/21502521/478f04e8-cc05-11e6-9745-e664772b6f7e.png">

**Comment by vincent99** [comment]
You define the health check on **services**, and if a service is the target of a balancer then the its health check will be used by haproxy to decide if it should be in rotation too.

![image](https://cloud.githubusercontent.com/assets/753917/21505289/1bb8b4c2-cc23-11e6-8a06-7daf50a494b7.png)

But if you really want, you can give the backend a name (click "Show custom backend name") and then add arbitrary config for it:

 
![image](https://cloud.githubusercontent.com/assets/753917/21505332/880bfd8c-cc23-11e6-8596-fbbfb3a68511.png)
