### ISSUE TITLE
How to reset authentication mode?

### ISSUE THREAD

**Issue by sdillen** [rancher/rancher#14748]
**Rancher versions:**
rancher/rancher: 2.0.6

I added our LDAP in the authentication tab and used the site access mode "Restrict access to only Authorized Users and Organizations". The Problem is that the group scheme was wrong. I can´t login with the local user or with the ldap user. How can i reset the authentication mode back to local?

**Comment by aemneina** [comment]
@sdillen When you first deploy rancher, you should have been prompted for a local admin password. Use that on the login page by selecting `use a local user` link. Let me know if that works.

**Comment by sdillen** [comment]
@aemneina I tryed to log in with the local admin by selecting the  `use a local user` link. I also reset the local admin password with the `reset-password` function on cli. I only get the message "Logging in failed: Check credentials, or your account may not be authorized to log in." when i try to log in with the local admin.

**Comment by superseb** [comment]
Does this reproduce on latest versions?

**Comment by Nold360** [comment]
I have the same issue on 2.1.0 (updated from 2.0.8). Server "lost" it's local admin after LDAP integration. Today i somehow can't login with LDAP anymore either. 

I guess I'll have to redeploy the server..

**Comment by stefa975** [comment]
This is still a problem in v2.1.1. If you lose your ldap login, you can't login with a local user.

**Comment by superseb** [comment]
I guess this is related to https://github.com/rancher/rancher/issues/15113? If so, it's fixed in v2.1.2

**Comment by stefa975** [comment]
Yes, that's correct.

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/issues/15113
