### ISSUE TITLE
rancher/rancher-agent:2.0.2 exited with 137

### ISSUE THREAD

**Issue by o0zonko0o** [rancher/rancher#14747]
rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes

**Docker version: (`docker version`,`docker info` preferred)**

Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-862.3.2.el7.x86_64
Type/provider of hosts: Bare-metal

Setup details:  HA rancher

Environment Template: Kubernetes

Steps to Reproduce:
Spam interface by clicking faste to switch to see a workload to an other.

**Results:**
container rancher/rancher-agent:2.0.2 exited(137)

How can i restart the agent without rebuild the entire cluster?

**Comment by alena1108** [comment]
@o0zonko0o can you try upgrading to the latest stable release of rancher - `2.1.1` at the moment of this comment - and see if you still hit the problem?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
