### ISSUE TITLE
When will rancher2.0 support Jenkins

### ISSUE THREAD

**Issue by shaocongcong** [rancher/rancher#14742]
When will rancher2.0 support Jenkins?

**Comment by shaocongcong** [comment]
Or when did Jenkins support the rancher2.0 plugin?

**Comment by loganhz** [comment]
What kind of jenkins plugin do you what? Can you describe your requirements in detail?
You can use `kubectl` or `kubernetes` jenkins plugin.

**Comment by superseb** [comment]
Let us know if you need any other information

**Comment by blueapple168** [comment]
use jenkins to built & deploy the  docker image to the kubernetes cluster deployed via rancher?
what can I do?

**Comment by leetomlee123** [comment]
i am use jenkins build and push image to harbor,but i dont know how to create container in rancher 2.+,jenkins rancher plugin look like not work
