### ISSUE TITLE
"The reply url specified in the request does not match the reply urls configured for the application" shown when configuring Azure AD authentication

### ISSUE THREAD

**Issue by hyouhaku** [rancher/rancher#14741]
Hi all, 

I've followed the instruction for configuring Azure AD authentication however I keep getting following error from microsoft login page:

`AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application`

When I created the app registration I already filled in reply URL which exactly matches our rancher login page: https://rancher.xxxx.com, and I triple checked it after, configuration seems to be correct. I've tried both https://rancher.xxxx.com and https://rancher.xxxx.com/, nothing worked

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.5` UI: `v2.0.60` |
|Access|`local` `admin`|
|Route|`global-admin.security.authentication.azuread`|

**Comment by xibix-fp** [comment]
We are also facing the same issue in our installation. Any advise would be recommended.

regards,
Fabian

**Comment by robeastham** [comment]
I have this too.

**Comment by astaicu** [comment]
Same issue here

**Comment by Tiiinky** [comment]
same issue with rancher v2.0.4
any updates on that issue?

**Comment by superseb** [comment]
Can you try using `https://rancher.xxxx.com/verify-auth-azure` as Reply URL in the App Registration and let me know if that works? It took around 2 minutes after saving the Reply URL before it was actually applied.

**Comment by Tiiinky** [comment]
I can confirm that this works!
I think it would be great if you could update the documentation at: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad/

**Comment by superseb** [comment]
Will update docs and fix the UI showing the proper Reply URL when configuring Azure AD

**Comment by dramich** [comment]
@westlywright Can we update the message to display `rancherUrl` (server/path) and also mention that it can take up to 5 min for the url to propagate through Azure?

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/27
Verified fixed
