### ISSUE TITLE
Rancher UI Error: Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by chrisenytc** [rancher/rancher#14740]
I am facing a critical issue with the Rancher UI. When accessing the workload details page, I can't edit anything or see the data in the bottom sections because the console shows an "Uncaught TypeError: Cannot read property 'data' of undefined" and every button stops working and no action happens.

**Note**: After some tests, I saw that this seems to happen only when you have secrets on your namespace.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`workload`|

<img width="1437" alt="screen shot 2018-07-24 at 5 23 48 pm" src="https://user-images.githubusercontent.com/2570702/43164098-9f603ea0-8f66-11e8-8088-ffdd1e5e53d7.png">

**Comment by loganhz** [comment]
UI sends correct `secretId` such as `project-w2vlp:aaaaa` to backend.
But server didn't populate it correctly. Server populated it as `default:aaaaa`

Payload from UI
![image](https://user-images.githubusercontent.com/21168270/43195364-7199ec74-9037-11e8-8e1e-6d19d22ee980.png)

Populated by Server
![image](https://user-images.githubusercontent.com/21168270/43195432-a5ff0bd4-9037-11e8-9f06-e40ee8d704d2.png)

**Comment by kinarashah** [comment]
@loganhz we'd need ui to update and send `secretName` instead of `secretId`

**Comment by loganhz** [comment]
Done

**Comment by loganhz** [comment]
PR is not merged yet

**Comment by cjellick** [comment]
https://github.com/rancher/ui/pull/2143

**Comment by soumyalj** [comment]
Tested with v2.0.7-rc5. Created workloads with secrets. Edited workloads/secrets. Did not see this issue. Secrets were functional, UI did not have issues.
