### ISSUE TITLE
rancher/server:1.6.19 refers to -rc1 version of agent image, actual release version unavailable

### ISSUE THREAD

**Issue by bghinkle** [rancher/rancher#14754]
**Rancher versions:**
rancher/server:v1.6.19
rancher/agent:v1.6.12-rc1

**Steps to Reproduce:**
Upgrade to Rancher 1.6.19. 

**Results:**
Although the release notes for this version refer to an agent image of 1.2.11, no such image appears on Docker Hub. Instead, Rancher is configured to use a release candidate Docker image of rancher/agent:v1.2.11-rc1.

It appears that the version was bumped to -rc1 while testing a new logging package and perhaps never updated to the final version after testing? See https://github.com/rancher/rancher/blob/v1.6.19/agent/Dockerfile#L7

**Comment by deniseschannon** [comment]
@bhinkle-work thanks for the report. we missed un-RCing the agent and will release a v1.6.20 shortly with this fix.

**Comment by deniseschannon** [comment]
@bghinkle We've released v1.6.20 that has agent:v1.2.11 packaged in it.
