### ISSUE TITLE
Full Backup/Restore Clean Server - Rancher 2.0.X

### ISSUE THREAD

**Issue by jniltinho** [rancher/rancher#14757]
rancher/rancher: 2.0.6
rancher/rancher-agent: 2.0.6

When you will have a full backup tool for the Rancher 2 Web Server Manager with bakup and restore, in the documentation, the backup procedure does not provide a restore after adding a clean server.

**Comment by aemneina** [comment]
Hi @jniltinho have you taken a look here: https://rancher.com/docs/rke/v0.1.x/en/installation/etcd-snapshots ?

**Comment by jniltinho** [comment]
Hi @aemneina :-(

I would like the option for single node, full server backup.
1 Server Web Manager + (1 Node All + 3 Nodes Work)
Total 5 Servers

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13688
