### ISSUE TITLE
System Project - Pods belonging to namespace under system project is not able to communicate with pods in other projects.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14769]
**Rancher versions: 2.0 Build from master
**Steps to Reproduce:**
Create a DO cluster with 3 nodes using default network (canal).
Deploy a workload WL1 in "Default" Project.
Deploy a new workload WLS1 in an existing namespace - "ingress-nginx".
Deploy a new workload WLS2 in new namespace created under "system" project.
Containers from  workloads WLS1 and WLS2 are not able to ping containers in "Default" project using its 10.42.x.x ipaddress.

But containers in  "Default" project is able ping containers in  WLS1 and  WLS2 successfully.

**Comment by bmdepesa** [comment]
rancher/rancher:master 8/6

Pods in projects are able to communicate with pods in System project namespaces.

Created a workload (W1) in default project
Created a namespace under System project
Add workload (W2) to new namespace in System project.
From workload (W1), can ping workload W2 in System project.
