### ISSUE TITLE
Catalog app stuck

### ISSUE THREAD

**Issue by miclefebvre** [rancher/rancher#14760]
**Rancher versions: 2.0.6**

**Infrastructure Stack versions:**
kubernetes (if applicable): RKL

**Type/provider of hosts: vSphere**

**Setup details: single node rancher**

**Steps to Reproduce:**
* Start a catalog app that couldn't complete the install (Example: prometheus)
* Delete the catalog app

**Results:**
The catalog app stay there forever.

There seems to have a couple of people that had this problem:

https://forums.rancher.com/t/catalogapp-stuck/11260
https://forums.rancher.com/t/redis-remove-stuck/10500

**Comment by StrongMonkey** [comment]
Hi @miclefebvre, you can try the following workround https://github.com/rancher/rancher/issues/11991#issuecomment-405750756.
We are try to root-cause this issue right now.

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/11991
