### ISSUE TITLE
Using Git repository (ending in .git) with self signed certificates as Catalog source won't work out of the box

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14766]
When configuring self signed certificates for the Catalog, it only works when using HTTPS repositories as we can influence Golang source of certificates by mounting the directory containing the CA cert and pointing to it using `-e SSL_CERT_DIR=/directory`.

But for Git based repository (ending in `.git`), we use the `git` binary in the container. As this Git client uses either the OS ca root store, or a config file that points to the cacert(s), this won't work out of the box.

Solutions can be:
- Automatically update OS ca root store based on a path where users can mount certificates (1.6 approach)
- Move away from using `git` binary and use a Golang based project like https://github.com/src-d/go-git

Current workarounds are:
- Copy certificate to `/usr/local/share/ca-certificates/rancher.crt` and run `update-ca-certificates` in the container
- Point git config to the cacerts directory using `git config --system http.sslCAPath /path/to/cacerts`

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/13371

**Comment by pmcanseco** [comment]
Can the error message displayed by the UI be updated to say something about certificate verification failing? Right now it just shows a 404 message which is misleading.
