### ISSUE TITLE
Create new user through REST API generate a user not able to log in

### ISSUE THREAD

**Issue by gioppoluca** [rancher/rancher#14779]
**Rancher versions:** 
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 18.06.0-ce, build 0ffa825

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Use the “/v3/users” API to create a new user.
API call similar to this one:
curl -u “{CATTLE_ACCESS_KEY}:{CATTLE_SECRET_KEY}”
-X POST
-H ‘Accept: application/json’
-H ‘Content-Type: application/json’
-d ‘{“description”:“testing user”, “me”:false, “mustChangePassword”:false, “name”:“test”, “password”:“testpasswd”, “principalIds”:[], “username”:“test”}’
‘https://tst-kubemaster.pochdp.csi.it/v3/users 2’

HTTP/1.1 POST /v3/users
Host: tst-kubemaster.pochdp.csi.it
Accept: application/json
Content-Type: application/json
Content-Length: 142

{

"description": "testing user",
"me": false,
"mustChangePassword": false,
"name": "test",
"password": "testpasswd",
"principalIds": [ ],
"username": "test"

}
**Results:**
User created, when trying to log in with this new user the UI return an error " e is undefined " .
No chance to log in.
This affects automation.
Thanks

**Comment by superseb** [comment]
I don't think anything changed in between versions, did your call work on previous versions? I've always used https://gist.github.com/superseb/cad9b87c844f166b9c9bf97f5dea1609 and that never failed.

Let me know if you think there is a bug.
