### ISSUE TITLE
Custom cluster created as Imported when selecting it after selecting other provider

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14775]
Version: master 7/26

Steps to reproduce:

1. Start Rancher
1. Add Cluster
1. Select Amazon EC2
1. Select Custom
1. Next
1. Done

Results:

Cluster shows as Imported. Any node that is added will fail with `Failed to find system images for version`

Workaround:

Refresh the page when on the `g/clusters/add?provider=custom` page.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
