### ISSUE TITLE
Assign network policy only after system project labels get propagated 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#14777]
rancher 2.0 7/26

saw that `nginx-ingress` is added to system project later - by that time network policy for its pod is already created. 
sample debug log to illustrate,  
```
2018/07/26 05:14:00 [INFO] pod nginx-ingress-controller-dp8p7 in ingress-nginx
2018/07/26 05:14:00 [INFO] entered
2018/07/26 05:14:00 [INFO] creating
2018/07/26 05:14:00 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-lkm5b to namespace=default
2018/07/26 05:14:00 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-m46rn to namespace=kube-public
2018/07/26 05:14:00 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=project-m46rn to namespace=ingress-nginx
2018/07/26 05:14:02 [INFO] pod nginx-ingress-controller-dp8p7 in ingress-nginx
2018/07/26 05:14:02 [INFO] entered
2018/07/26 05:14:02 [INFO] retuning cuz system namespace
```

**Comment by kinarashah** [comment]
I've added logic to delete the existing network policies for system namespaces, but it gets called only on sync, so they would still be present. 

But everything should work fine, those network policy shouldn't affect expected behavior.

**Comment by bmdepesa** [comment]
rancher/rancher:master 8/6

There is no isolation of System project, and the network policies are removed with everything continuing to function correctly.
