### ISSUE TITLE
Rancher UI: Statefulset workload is being created as a scalable deployment

### ISSUE THREAD

**Issue by chrisenytc** [rancher/rancher#14774]
I am creating a stateful set of 1 pod on rancher 2.0.6, but when I launch it, the workload is created as a scalable deployment.

<img width="1161" alt="screen shot 2018-07-26 at 2 49 29 am" src="https://user-images.githubusercontent.com/2570702/43243800-b0268898-907e-11e8-89d9-94b425ea5233.png">

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`containers.run`|

**Comment by carolynhu** [comment]
Hi @chrisenytc, can you post some details in API? Is it showing `deploymentConfig` in api? like:
```
deploymentConfig": {
"maxSurge": 1,
"maxUnavailable": 0,
"minReadySeconds": 0,
"progressDeadlineSeconds": 600,
"revisionHistoryLimit": 10,
"strategy": "RollingUpdate"
},
```

**Comment by loganhz** [comment]
Hi @chrisenytc 
I guess it is duplicated of https://github.com/rancher/rancher/issues/14511
The fix will be in `v2.0.7`

Please reopen it if you have other reproduce steps.
Thanks.

**Comment by chrisenytc** [comment]
@carolynhu It shows exactly that.

**Comment by carolynhu** [comment]
@chrisenytc ok, would you mind to post the details of how to reproduce your issue? Thank you~
