### ISSUE TITLE
Revise project level resource quota for storage 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#14771]
Since project level resource quota was introduced, there were some changes done to resource quota on k8s side. Revise the https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota to see if/how we can enable resource quota for storage.

**Comment by alena1108** [comment]
Currently we support:

> requests.storage
> persistentvolumeclaims

`requests.ephemeral-storage` is still in alpha on kubernetes side, so we'll wait for it to become official till we put it in.

**Comment by jacob-ray** [comment]
Would it be possible to allow requests.storage per class at the project level as detailed here?
https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota

**Comment by jacob-ray** [comment]
Would it be possible to allow requests.storage per class at the project level as detailed here?
https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota

**Comment by mchnwzrd** [comment]
Would it be possible to allow requests.storage per class at the project level as detailed here?
https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota

**Comment by mchnwzrd** [comment]
@AntonSmolkov thanks for the reply!  We are currently using that, but I'd love to see being able to set requests.storage based upon the storage class:

<storage-class-name>.storageclass.storage.k8s.io/requests.storage
see:  https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota

Example issue we run into:  we have 2 classes -- NFS (slow) and FlexOS (fast).  We'd like to be able to assign a project/namespaces X amount of NFS and X amount of FlexOS.  As it stands (unless I'm gaping on something) any class used counts towards one quota.
