### ISSUE TITLE
Logging using fluentd docker plugin

### ISSUE THREAD

**Issue by gioppoluca** [rancher/rancher#14778]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 18.06.0-ce, build 0ffa825

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
The environment has been deployed to send logs to an external elasticsearch server.
All is configured and works as expected, but the setting read the logs from the files in _/var/log/containers/*.log_ 

This is the fluentd container setting:
```
<source>
  @type  tail
  path  /var/lib/rancher/rke/log/*.log
  pos_file  /fluentd/log/fluentd-rke-logging.pos
  time_format  %Y-%m-%dT%H:%M:%S
  tag  rke.*
  format  json
  read_from_head  true
</source>

<filter rke.**>
  @type record_transformer
  enable_ruby true  
  <record>
    tag ${tag}
    log_type k8s_infrastructure_container 
    driver rke
    component ${tag_suffix[6].split("_")[0]}
    container_id ${tag_suffix[6].split(".")[0]}
  </record>
</filter>

<source>
   @type  tail
   path  /var/log/containers/*.log
   pos_file  /fluentd/log/fluentd-cluster-logging.pos
   time_format  %Y-%m-%dT%H:%M:%S
   tag  cluster.*
   format  json
   read_from_head  true
</source>

<filter  cluster.**>
   @type  kubernetes_metadata
   merge_json_log  true
   preserve_json_log  true
</filter>

<filter cluster.**>
  @type record_transformer
  <record>
    tag ${tag}
    log_type k8s_normal_container 
    </record>
</filter>

<match  cluster.** rke.** cluster-custom.**> 
    
    @type elasticsearch
    include_tag_key  true
    hosts http://tst-shared.pochdp.csi.it:9200    
    logstash_format true
    logstash_prefix "sdptools"
    logstash_dateformat  %Y-%m-%d
    type_name  "container_log"

    <buffer>
      @type file
      path /fluentd/etc/buffer/cluster.buffer
      flush_interval 3s
      </buffer> 

    disable_retry_limit
    num_threads 8
    slow_flush_log_threshold 40.0
</match>
```
Since is possible to set the docker daemon to use directly the fluentd plugin if we manage to have an option asking "are you using the fluentd plugin?" so that we can have this settings in the fluentd (with proper configuration).  this could help not to write to file system any logs, better performances.

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
```

**Comment by CaptEmulation** [comment]
I've gotten fluentd container logging working in rancher 1.6 using a block like:
```
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
```
where the host also has a fluentd container running that is opened on port 24224.  What I can't figure out is how to be able to close port 24224 and be able to set the logging driver to go to the private network address of a rancher deployed fluentd container.

**Comment by deniseschannon** [comment]
In 2.2, we now enable custom fluentd logging, which can be found in step 4 when enabling logging: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/logging/
