### ISSUE TITLE
UI for being able to select whether or not you want network policies for RKE clusters using canal networking

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14787]
1. This is only for RKE clusters and selecting canal, you should have the option to enable network policies, which creates project isolation so that projects can't talk to each other.  By default, it isn't enabled.

2. When editing RKE clusters, you should not be able to change network providers, but if you have canal selected, you should be able to enable/disable network policies. 

Please make sure to make a note or tooltip of what network policies does.

**Comment by loganhz** [comment]
hi @kinarashah , what is the parameter for enabling/disabling network policies?

**Comment by kinarashah** [comment]
Hi @loganhz, the field is called `enableNetworkPolicy` in cluster spec

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30 
UI is in, backend is not functioning.  Entered bug #14851
