### ISSUE TITLE
Nodes resource is listed twice in cluster & node role templates

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14784]
rancher/rancher:master 7/25 (also reproduced in 2.0.5)

The nodes resource is listed twice in cluster owner/member & manage nodes / view nodes role templates. 

Navigate to Security > Roles via the navigation menu
View the cluster member role
The `nodes` resource is listed twice

![Screen Shot 2018-07-25 at 1.40.32 PM.png](https://images.zenhubusercontent.com/5819732de40e5714b16f83de/7b577ad3-cd24-4c63-9a27-dc1be97d8ebf)

The api for these roles shows the following:
```
{  
   "apiGroups":[  
      "management.cattle.io"
   ],
   "resources":[   
      "nodes",
      "nodepools"
   ],
   "type":"/v3/schemas/policyRule",
   "verbs":[  
      "get",
      "list",
      "watch"
   ]
},
{  
   "apiGroups":[  
      "*"
   ],
   "resources":[  
      "nodes"
   ],
   "type":"/v3/schemas/policyRule",
   "verbs":[  
      "get",
      "list",
      "watch"
   ]
},
```

**Comment by carolynhu** [comment]
I've tested this issue. I think this should be an UI issue.
Here is what in addRoleTemplate for Cluster Member.
```
rb.addRoleTemplate("Cluster Member", "cluster-member", "cluster", true, false, false).
		addRule().apiGroups("management.cattle.io").resources("clusterroletemplatebindings").verbs("get", "list", "watch").
		addRule().apiGroups("management.cattle.io").resources("projects").verbs("create").
		addRule().apiGroups("management.cattle.io").resources("nodes", "nodepools").verbs("get", "list", "watch").
                 ...
                 ...
```
After I delete "nodes", before the "nodepools". The UI shows nodepools
<img width="1215" alt="screen shot 2018-07-26 at 2 45 41 pm" src="https://user-images.githubusercontent.com/29208297/43290317-9df57f4e-90e2-11e8-89e0-10c0924d9496.png">

**Comment by dramich** [comment]
This should be fixed in the UI. Node and nodepools are the only resource we send over with two resources listed so the UI is only grabbing the first value.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
