### ISSUE TITLE
Incorrect text when viewing role template and cluster/project creator default is set to true

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14782]
Incorrect text when viewing role template and cluster/project creator default is set to true
rancher/rancher:master 7/25

The text displayed for the project/cluster creator default role field set to true is incorrect when viewing a role template. 

Create a role w/ cluster creator default set to true.
View the role (not edit)
The text displayed is for a locked binding `New bindings are not allowed to use this role`
The text should be `Default role for new cluster creation'

Incorrect text when viewing:
![Screen Shot 2018-07-25 at 1.27.48 PM.png](https://images.zenhubusercontent.com/5819732de40e5714b16f83de/b28010c1-541a-43c8-8d2b-b58ecbb3dce8)

Correct text when creating/editing:
![Screen Shot 2018-07-25 at 1.28.23 PM.png](https://images.zenhubusercontent.com/5819732de40e5714b16f83de/da13178a-4f67-4d61-b78c-27265da47996)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
