### ISSUE TITLE
Clicking a global role name in the global roles list leads to a 404

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14783]
rancher/rancher:master 7/25

Clicking a global role name in the global roles list leads to a 404 error message.
Navigate to Security > Roles from the navigation mentu.
Click on the "Global" tab.
Click on a role name in the list to view the role.
User is presented with a 404. 

The error message suggests it is searching for the role in role templates instead of global roles.

![Screen Shot 2018-07-25 at 1.37.59 PM.png](https://images.zenhubusercontent.com/5819732de40e5714b16f83de/99d7a4f6-73df-4130-8ef1-50906a0d6210)

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
