### ISSUE TITLE
Ping Federate - Assigned users of clusters are listed as unknown.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14799]
**Rancher versions:**
Master 7/26

**Steps to Reproduce:**
Enable ping federate
Create a new cluster.
Assign a user as a member of new cluster. 

**Results:**
User is listed as "Unknown".

![screen shot 2018-07-26 at 2 18 04 pm](https://user-images.githubusercontent.com/38012481/43290048-a81a624c-90e1-11e8-9d82-6eeaa6cbc518.png)

**Comment by westlywright** [comment]
@adingilloRancher I think this may have been a backend bug that was fixed. Can you test with latest? 
<img width="1321" alt="screenshot 2018-07-31 12 24 38" src="https://user-images.githubusercontent.com/858614/43482152-beccaad4-94bc-11e8-8140-da03820e7fa0.png">

**Comment by adingilloRancher** [comment]
Master 8/2

User is correctly listed.
