### ISSUE TITLE
Alert for workload "less than 100% available" always fires

### ISSUE THREAD

**Issue by adampl** [rancher/rancher#14790]
**Rancher versions:**
2.0.6 (stable)

**Docker version:**
18.06.0 CE

**Operating system and kernel:**
Ubuntu Server 16.04.5 LTS, 4.4.0-130-generic

**Type/provider of hosts:**
Bare-metal

**Setup details:**
Single node, internal DB

**Steps to Reproduce:**
1. Click _Add Alert_
1. Select _Workload_ and pick some healthy workload
1. Slide _Is less than_ to _100% available_
1. Optionally choose a notifier
1. Save and wait a moment

**Results:**
The alert state changes to _Alerting_ (and an alert is sent if a notifier was set).
Example Slack notification:
![image](https://user-images.githubusercontent.com/6024937/43284234-75c76d5a-911b-11e8-87b2-9907ad20523e.png)

**Expected results:**
The alert should fire only if there is less than 100% replicas, not less than or equal.

I suspect it may also be the case with 1/2 and 50%, and might be caused by wrong comparison operator.

**Comment by carolynhu** [comment]
Verified on latest master as build of 9/17
Create a slack notifier, add a alert for a healthy workload. Choose condition for 50% and 100%. Not post alert to my slack channel.
<img width="1031" alt="screen shot 2018-09-17 at 12 56 05 pm" src="https://user-images.githubusercontent.com/29208297/45646764-1f13ca80-ba79-11e8-8773-5db4d40f3c33.png">
