### ISSUE TITLE
Execute Docker API/CLI commands against multiple containers

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#148]
Rancher UI already supports limited capabilities of being able to execute commands against multiple containers (i.e run, stop, state change commands) but does not support this via API/CLI.

Rancher should support CLI/API capability to do a best effort execution of Docker commands (run, exec, etc.) against multiple containers.  It can support executing (exact or reg exp match):
- by host
- by cluster
- by name
- by label
- by multiple container IDs
- by service (once Service Discovery feature has been implemented)

**Comment by swaroopkundeti** [comment]
+1

**Comment by gavinhodge** [comment]
+1

Even just making it possible to execute a single command via the API would make the rancher-compose equivalent of `docker-compose exec` feasible.
