### ISSUE TITLE
"Rancher" text is hardcoded

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14800]
**Rancher versions:** 2.0 master 7/26

- [x] /security/authentication/azuread page -  "your Rancher server"
![image](https://user-images.githubusercontent.com/11514927/43289262-46e67116-90df-11e8-849d-45808f45d00c.png)

- [x] /security/authentication/ping - "Rancher API Host"
![image](https://user-images.githubusercontent.com/11514927/43289360-9207d770-90df-11e8-9721-2034706e9e8c.png)

- [x] /catalog - Example text for Git "/github.com/rancher/charts.git
![image](https://user-images.githubusercontent.com/11514927/43289618-5fbbcae6-90e0-11e8-89a5-7931cbcc6625.png)

- [x] /settings/advanced - server-url text "Default Rancher install url"
![image](https://user-images.githubusercontent.com/11514927/43289709-a6266d74-90e0-11e8-8093-65fdb5d2dd24.png)

- [ ] /node-templates - Step 3 for Amazon EC2 "rancher-nodes"
![image](https://user-images.githubusercontent.com/11514927/43289928-4e2a84a6-90e1-11e8-9897-8b08e3827b0d.png)

**Comment by loganhz** [comment]
For the last one `rancher-nodes`, I think the default security group name `rancher-nodes` is hardcode in backend. It might be confusing if only UI changed it to `{appname}-nodes`.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/1
Verified fixed
