### ISSUE TITLE
Ping Federate - Authorized Group users unable to login.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14806]
**Rancher versions:**
Master 7/26

**Steps to Reproduce:**
Enable ping federate.
Site site access to "Allow members of Clusters, Projects, plus Authorized Users and Organization"
Add testgroup1 as authorized users. (CN=testgroup1)
In a new session, attempt to login as a member of authorized group.

**Results:**
Member of group (testuser2) is unable to login.

![screen shot 2018-07-26 at 3 39 59 pm](https://user-images.githubusercontent.com/38012481/43292488-5f834090-90ea-11e8-9964-67af01f91a61.png)

**Comment by mrajashree** [comment]
@adingilloRancher Why is the testgroup1 being seen as a user here? Did you add it from the dropdown or by typing it in the search bar? Because only the former will work

**Comment by mrajashree** [comment]
@adingilloRancher Unable to reproduce this, as per the screenshot the group is added via search bar and not the dropdown, when added via dropdown group membership is working

**Comment by adingilloRancher** [comment]
Master 7/27

Unable to reproduce on latest build.
