### ISSUE TITLE
Can restore container that failed to find placement

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1480]
v0.27.0-rc1
Steps:
1.  create a container that will "Fail to find placement"
2.  Click on it's menu and select Restore

Results:
The container will move out of "Removed" state and go into a "Stopped" state.  It will also lose it "failed to find placement" message, if you try to restart it.

Expected:
Should we be able to restore and reset a container that will not find placement because of no hosts or rule?

**Comment by vincent99** [comment]
This shouldn't be relevant anymore with the addition of the `error` state a while ago.

**Comment by ibuildthecloud** [comment]
Restore should be dropped from the API

**Comment by vincent99** [comment]
Error doesn't have restore enabled so I think this is fine now

**Comment by tfiduccia** [comment]
Version - master 3.20
Verified fixed
