### ISSUE TITLE
Security section missing title bar at top

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14802]
**Rancher versions:** 2.0 master 7/26

**Steps to Reproduce:**
1.  Go to Global/Security - then anything under that drop-down

**Results:**  There is title bar at the top of any of those pages.  So if you go to Pod Security Policies, there is no way to know what page you are actually on
Roles
![image](https://user-images.githubusercontent.com/11514927/43291617-010cbee0-90e7-11e8-8964-8b53daa6cce2.png)

Pod Security Policies
![image](https://user-images.githubusercontent.com/11514927/43291609-f94e70d6-90e6-11e8-936a-ea3104af567b.png)

Authentication
![image](https://user-images.githubusercontent.com/11514927/43291642-0e9ee330-90e7-11e8-8206-35a1f10f9e32.png)

Example of correct title bar:
![image](https://user-images.githubusercontent.com/11514927/43291653-17200c50-90e7-11e8-8c2e-b5641df356ad.png)

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/43301156-fbb9a11a-9195-11e8-8d0c-4d5bba3a9a3a.png)

@vincent99 

Added title bar for psp and Authentication

It doesn't look good if we add the title bar for Roles as there is already three tabs in the page.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Verified fixed
