### ISSUE TITLE
container launching on host label that was not satisfied

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#14817]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.14-patch2-rc1

When launching a stack with a host label that was not satisfied, I added the host label then deleted the stack. I recreated the stack and received the same error on the stack, but the container was launching on the host with the label. A few moments later, the error disappeared as if all was fine.

**Comment by soumyalj** [comment]
Tested with v1.6.14-patch2-rc1. Tested with the above steps. Added a new stack using "Add stack" in UI. Did not see any errors. Containers were deployed correctly as per the scheduling rule after the host label was added. The issue was not reproduced.
