### ISSUE TITLE
Block/warn when disabling/deleting last/Default admin user

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14818]
Version: master 7/27

Steps to reproduce:

1. Start `rancher/rancher`
1. Login and set admin password
1. Open `Users` and delete Default Admin

Results:
User shows Removing, after refresh you are prompted to login again.

We should warn or block deleting the default and/or last available admin user. If we decide to allow deleting the Default Admin user, we should change `reset-password` not to rely on the `bootstrapping=admin-user` label.

**Comment by liao-bo** [comment]
@superseb if i have disabling last/Default admin user in rancher2.0.8，how can i enable the admin account?Please help me .

**Comment by cjellick** [comment]
@liao-bo are you saying you deleted the default admin user and you want to get it back?
Do you have any other users that are admins?

**Comment by cjellick** [comment]
As discussed, fix will be to prevent users from deleting themselves and to add a cli tool to re-add admin user if it is deleted

**Comment by liao-bo** [comment]
@cjellick i have resolve the issue #15306, thank you.

**Comment by sangeethah** [comment]
Closing this issue  since ensure-default-admin is now available.
