### ISSUE TITLE
Scale up unexpected behaviour from Rancher UI with pods created by kubectl

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#14810]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6 

**Infrastructure Stack versions:**
kubernetes (if applicable):  v1.10.5

**Docker version: (`docker version`,`docker info` preferred)** 1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Steps to Reproduce:**
1) create deployment/pods/serviice/ingress 
    kubectl create -f deployment-nginx.yaml
   Three pods created
   NAME                     READY     STATUS    RESTARTS   AGE
   nginx-6bfb654d7c-8v8wj   1/1       Running   0          38s
   nginx-6bfb654d7c-js27r   1/1       Running   0          38s
   nginx-6bfb654d7c-vcq86   1/1       Running   0          38s

2) scale up from Rancher UI
   1 pod created the original 3 pods deleted and recreated

   NAME                    READY     STATUS    RESTARTS   AGE
   nginx-f8768bc6c-2mcms   1/1       Running   0          34s
   nginx-f8768bc6c-btgtj   1/1       Running   0          46s
   nginx-f8768bc6c-tv9gd   1/1       Running   0          46s
   nginx-f8768bc6c-txps9   1/1       Running   0          35s

3) scale up from Rancher UI again
    1 pod created the original 4 pods untouched

    NAME                    READY     STATUS    RESTARTS   AGE
    nginx-f8768bc6c-2mcms   1/1       Running   0          55s
    nginx-f8768bc6c-btgtj   1/1       Running   0          1m
   nginx-f8768bc6c-tv9gd   1/1       Running   0          1m
   nginx-f8768bc6c-txps9   1/1       Running   0          56s
   nginx-f8768bc6c-vnsg7   1/1       Running   0          14s

**Results:**
It may not be a problem for stateless application but definitely a problem for statefull application as 
HTTP session lost.

This does not happen if workload created in Rancher UI.

**Comment by loganhz** [comment]
Duplicated of https://github.com/rancher/rancher/issues/13655

Please see https://github.com/rancher/rancher/issues/13655#issuecomment-393591662
