### ISSUE TITLE
Add ability to clone for cluster and project alerts in UI

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14811]

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/30
Project cloning is throwing error and hanging
ember-metal.js:3007 Uncaught n {stack: "Error: Property set failed: object in path "model.…s.rancher.com/ui/latest2/assets/vendor.js:1720:9)", description: undefined, fileName: undefined, lineNumber: undefined, message: "Property set failed: object in path "model.targetPod" could not be found or was destroyed.", …}

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/31
Verified fixed
