### ISSUE TITLE
Creating 'workload' results in 'Unsupported value: "Never"'

### ISSUE THREAD

**Issue by jungju** [rancher/rancher#14813]
**Rancher versions:**
rancher/rancher:2.0.6

After creation of 'Job', deployment is not created in UI.
```
error message
Validation failed in API: Deployment.apps "ddd" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"
```

'restartPolicy' does not seem to be initialized.

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/ui/pull/2065. It will be in `2.0.7`
Now you can change it to `Always` via `Show advanced options` -> `Command` -> `Auto Restart`

**Comment by loganhz** [comment]
Thanks for your report!
