### ISSUE TITLE
Fluentd cannot ship logs to external ES endpoint v6.x using https

### ISSUE THREAD

**Issue by canhnt** [rancher/rancher#14815]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.0.6

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
1.13.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ uname -r
3.10.0-862.3.3.el7.x86_64
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Configure Rancher to ship logs to an external ElasticSearch v6.2.4 at e.g. https://my-elastic.example.com
**Results:**
Fluentd pods in the `cattle-logging` namspace produce error message that they cannot ship logs:
```
2018-07-27 12:25:02 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-07-27 12:25:02 +0000 chunk="571fa32fc95aedb61f2d2690566e0b01" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="
Can not reach Elasticsearch cluster ({:host=>\"6103ee9cbbc843f3b0abb2f9fcdb5da3.elastic.example.org\", :port=>443, :scheme=>\"https\", :user=>\"elastic\", :password=>\"obfuscated\"})!"
```

**Fix**
Add the line `ssl_version TLSv1_2` to the `cluster.conf` in the `cluster-logging` config map:
```
    <match  cluster.** rke.** cluster-custom.**>

        @type elasticsearch
        include_tag_key  true

        hosts https://usr:password@https://my-elastic.example.com
        logstash_format true
        ...

        ssl_version TLSv1_2
        ssl_verify false 
```
Then fluentd pods can send logs to the ES endpoint.

**Comment by loganhz** [comment]
close in favor of https://github.com/rancher/rancher/issues/16042
