### ISSUE TITLE
adding members with multiple custom roles add's multiple users to cluster preventing login

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#14822]
**Rancher versions:**
rancher/rancher: 2.0.6

**Steps to Reproduce:**
1. using AD auth add member with custom roles
2. select multiple roles
3. save settings

**Results:**
1. multiple members are added, 1 per role added
2. user can no longer login via the UI

**Comment by aemneina** [comment]
Error responses:
- UI returns: Server error while authenticating
- Cattle error log: `[ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: can't find unique user for principal activedirectory_user:XXXXX`

**Comment by prachidamle** [comment]
Root cause of this issue should be same as https://github.com/rancher/rancher/issues/14697
Duplicate user records getting created due to cache lookup by multiple threads at same time.

@aemneina In the server logs do you see following statements in quick succession?
```
Creating user for principal
```

**Comment by aemneina** [comment]
that does seem to be the case. I can share logs directly with you if you're interested in more logs.
```
2018/07/27 18:47:27 [INFO] Creating user for principal activedirectory_user://XXXX
2018/07/27 18:47:27 [INFO] Creating user for principal activedirectory_user://XXXX
2018/07/27 18:47:27 [INFO] Creating globalRoleBinding for user-k2z5b
2018/07/27 18:47:27 [INFO] Creating user for principal activedirectory_user://XXXX
2018/07/27 18:47:27 [INFO] Creating user for principal activedirectory_user://XXXX
2018/07/27 18:47:27 [INFO] [mgmt-auth-crtb-controller] Creating clusterRoleBinding for membership in cluster local for subject user-k2z5b
```
2018/07/27 18:47:27 [INFO] Creating globalRoleBinding for user-b6q5g
2018/07/27 18:47:27 [INFO] Creating globalRoleBinding for user-phr5b
2018/07/27 18:47:27 [INFO] Creating globalRoleBinding for user-2dk66````

**Comment by carolynhu** [comment]
@aemneina Which user cannot login, the admin user that enabled the auth or the new added member user?

**Comment by aemneina** [comment]
@carolynhu the newly added user.

**Comment by carolynhu** [comment]
The current status of this issue:
When using the latest build of master 7/27, the newly added user can login. But UI still showing multiple roles per user.
<img width="1123" alt="screen shot 2018-07-27 at 4 30 56 pm" src="https://user-images.githubusercontent.com/29208297/43350263-a5f5cefa-91ba-11e8-9c2c-ec41c3133ac5.png">

Another issue we found that:
Go to edit cluster, user cannot add a new user. The save isn't working. Like here, testuser2 cannot be added.
<img width="1130" alt="screen shot 2018-07-27 at 4 34 43 pm" src="https://user-images.githubusercontent.com/29208297/43350319-0c785f9e-91bb-11e8-8ec7-37f45fdf23fd.png">

**Comment by carolynhu** [comment]
With v2.0.6 build:
Enable AD auth, make `testautoadmin` as the admin User. Then, add `testuser1` and `testuser2` with multiple roles. The UI displays those roles in multiple lines.
<img width="1267" alt="screen shot 2018-07-30 at 11 35 10 am" src="https://user-images.githubusercontent.com/29208297/43416270-ab1c9b1e-93ec-11e8-9254-362a7041f7ce.png">
`testuser1` can login, but `testuser4` cannot login

**Comment by adingilloRancher** [comment]
Master 8/6

This has been resolved. User is only listed once under cluster when added with custom roles. Blocked from being added multiple times.
