### ISSUE TITLE
When moving a namespace that has workloads with host ports/node ports to "system" projects , network policies relating to  host ports/node ports are not getting cleared.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14825]
Rancher versions: Build from master
**Steps to Reproduce:**
Create workloads with host port  and node ports in namespace that is not part of "System" project. 
Move this namespace to "System" project.
After the move, all existing network policies relating to host port  and node ports in this namespace continue to be present in the namespace.
Only hn-nodes  and np-default network policies get deleted.

Expected behavior:
After the move, all existing network policies relating to host port  and node ports in this namespace should get deleted.

**Comment by bmdepesa** [comment]
rancher/rancher:master 8/6

Network policies are getting removed when moving namespace to System project. 

Created a namespace in Default project, containing a workload with a nodeport.
`kubectl get networkpolicies --all-namespaces` shows network policies for the created namespace and workload.
Move the created namespace to the System project.
`kubectl get networkpolicies --all-namespaces` shows no network policies for the namespace or workload moved to the System project.
