### ISSUE TITLE
Provide dropdown of all available services when using "service with the name" option.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1482]
Server version - V0.27.0-rc1

Steps to reproduce the problem:
Create a service with scheduling set to host must have a "service with the name" option.

There is no dropdown available with all available services to pick from.
 
<img width="1082" alt="screen shot 2015-07-09 at 5 09 36 pm" src="https://cloud.githubusercontent.com/assets/4266958/8609693/6a930aba-265d-11e5-8c80-238e5bd2a925.png">

**Comment by vincent99** [comment]
#1482, labels changed.

**Comment by tfiduccia** [comment]
Failed - still no drop-down

**Comment by vincent99** [comment]
Labels changed some more... note that it only looks for the new label (`stack_service`) so you'll need some newly-created services.

**Comment by deniseschannon** [comment]
v0.27.0-rc4: Verified Fixed with new services.
