### ISSUE TITLE
When moving a namespace that has workloads with host ports/node ports from "system" projects , network policies relating to host ports/node ports do not get created resulting in the node ports/host ports not working.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14826]
**Rancher versions:** Build from master
**Steps to Reproduce:**
Create workloads with host port  and node ports in namespace that is part of "System" project. 
Move this namespace out of  "System" project.
After the move,  network policies relating to host port  and node ports are not getting created in the namespace . This results in host port  and node ports not be accessible anymore.

Expected Behavior:
After the move,  network policies relating to host port  and node ports should get created in this namespace and host port  and node ports should continue to be accessible.

**Comment by bmdepesa** [comment]
rancher/rancher:master 8/6

Network policies are being created when moving out of System project. 

Created a namespace in System project, containing a workload with a nodeport. 
`kubectl get networkpolicies --all-namespaces` should show no network policies for the new namespace in the System project.
Move the created namespace to the Default project.
`kubectl get networkpolicies --all-namespaces` shows network policies for the namespace and workload which was moved.
