### ISSUE TITLE
rancher proxy don't work as expected

### ISSUE THREAD

**Issue by Wing924** [rancher/rancher#14839]
**Rancher versions:**
rancher/rancher:stable
rancher/rancher-agent:v2.0.6

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.10.5

**Docker version: (`docker version`,`docker info` preferred)**
1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux release 7.5.1804 (Core)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
```bash
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -e http_proxy="http://my-proxy:8080" \
  -e https_proxy="http://my-proxy:8080" \
  -e no_proxy="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,100.0.0.0/8" \
  rancher/rancher:stable
```

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Create cluster -> add hosts -> create

**Results:**

Got those errors during provisioning.
```
2018/07/30 05:43:01 [INFO] cluster [c-lrt75] provisioning: [healthcheck] service [kube-apiserver] on host [100.72.117.92] is healthy
2018/07/30 05:43:34 [ERROR] cluster [c-lrt75] provisioning: Failed to apply the ServiceAccount needed for job execution: Post https://100.72.117.91:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: Forbidden
2018/07/30 05:45:17 [INFO] cluster [c-lrt75] provisioning: [authz] Creating rke-job-deployer ServiceAccount
2018/07/30 05:45:42 [ERROR] cluster [c-lrt75] provisioning: Failed to apply the ServiceAccount needed for job execution: Post https://100.72.117.91:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: Forbidden
```
If I don't set the proxy when I run `rancher/rancher:stable`, all works fine (catalog don't work because my servers are behind proxy).

https://rancher.com/docs/rancher/v2.x/en/installation/proxy-configuration/
> The example below is based on a local network range of 10.0.0.0/8

It seems that Go's http client don't support ip range based no_proxy.
https://golang.org/src/net/http/transport.go

**Comment by loganhz** [comment]
Hi @Wing924 

Can you try the following command with upper case `HTTP_PROXY` env, please?

```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -e HTTP_PROXY="http://10.0.0.1:3128" \
  -e HTTPS_PROXY="http://10.0.0.1:3128" \
  -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8" \
  rancher/rancher:latest
```

Please see https://rancher.com/docs/rancher/v2.x/en/installation/proxy-configuration/

**Comment by Wing924** [comment]
@loganhz It works! Thank you. Anyway, I expected both lower case and upper case work.
