### ISSUE TITLE
RANCHER cattle error

### ISSUE THREAD

**Issue by itssivashankar** [rancher/rancher#14838]
while building Rancher ui(cattle) i am getting an  #Error connecting to proxy
and 
[ember-intl] cannot read path "/home/dev/ui/tmp/translation_reducer-input_base_path-CsIIuVWh.tmp/__addon__pipeline/ja-jp.yaml"
[ember-intl] cannot read path "/home/dev/ui/tmp/translation_reducer-input_base_path-CsIIuVWh.tmp/__addon__alert/ja-jp.yaml"

**Comment by loganhz** [comment]
I guess it is a random issue.

Can you try `./scripts/update-dependencies` and `./scripts/build-static -s`?

**Comment by itssivashankar** [comment]
I to build the RANCHER ui(cattle) with same command  # ./scripts/update-dependencies.
But while starting RANCHER ui(cattle) using  // yarn start  command i am getting the same error
#Error connecting to proxy
and
[ember-intl] cannot read path "/home/dev/ui/tmp/translation_reducer-input_base_path-CsIIuVWh.tmp/__addon__pipeline/ja-jp.yaml"
[ember-intl] cannot read path "/home/dev/ui/tmp/translation_reducer-input_base_path-CsIIuVWh.tmp/__addon__alert/ja-jp.yaml"

**Comment by loganhz** [comment]
Not sure if it is related to node version. Please try to remove the `/home/dev/ui/tmp/` folder and try again. 
![image](https://user-images.githubusercontent.com/21168270/47360989-73a70700-d703-11e8-964e-362af7d02d7d.png)

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
