### ISSUE TITLE
Nginx Ingress Prometheus Endpoints for Scraping [v2]

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#14834]
Is there a way to customize the out of box nginx ingress to expose port 10254 and deploy a service that way it can be monitored with Prometheus?

**Comment by loganhz** [comment]
link to https://github.com/rancher/rancher/issues/14230

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14230
