### ISSUE TITLE
Containers fail to deploy when using "service with the name" option.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1483]
Server version - V0.27.0-rc1

Steps to reproduce the problem:
Create a service with scheduling rule host must have "service with the name" for "test/health-new4"
The containers are created with "io.rancher.project_service.name" label. But we have started using "io.rancher.stack_service.name" for containers. This prevents containers from finding any host.

Container that was spawned that could not find placement:

<img width="1127" alt="screen shot 2015-07-09 at 5 19 34 pm" src="https://cloud.githubusercontent.com/assets/4266958/8609830/341c06c4-265f-11e5-93fe-aa473bf4b48b.png">

Labels on container from service - "test/health-new4"

<img width="1100" alt="screen shot 2015-07-09 at 5 30 38 pm" src="https://cloud.githubusercontent.com/assets/4266958/8609906/4006e188-2660-11e5-806a-bb24334abcba.png">

**Comment by vincent99** [comment]
https://github.com/rancher/cattle/pull/665 did not make into the release so the backend doesn't know what to do with `io.rancher.project_service.name`..  Should be fixed in the backend next build, and I also changed the label that the UI uses.

**Comment by sangeethah** [comment]
Tested with latest UI:
UI still uses - "io.rancher.project_service.name=default/testanti" as value for labels.
Reopening this issue to fix this.

**Comment by vincent99** [comment]
Changed the labels the UI creates.

**Comment by sangeethah** [comment]
Tested with server version - v0.27.0-rc4
We are able to deploy containers for a service successfully when using scheduler options - "host must have service with the name" option.
Following affinity rule created for the server has referrence to "stack" and not "project" as expected.
Affinity - io.rancher.scheduler.affinity:container_label - io.rancher.stack_service.name=default/test1234
