### ISSUE TITLE
rancher-agent-bootstrap uses hardcoded dns instead of host provided

### ISSUE THREAD

**Issue by doreplado** [rancher/rancher#14849]
**Rancher versions:**
rancher/server:1.6.20
rancher/agent or rancher/rancher-agent: N/A

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
18.06 from Rancher Install Dialog in AWS Provisioner 

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Setup Rancher Server 1.20 with a registration URL on a Private DNS Zone 
2. Try to provision a new Host using AWS provider using: ami-b04847cf
3. In advanced, select 18.06.sh for install URL

**Results:**
You'll receive an error once it gets to provisioning the agent: ""Failed to find rancher-agent container" because the rancher-agent-bootstrap uses 8.8.8.8 / 8.8.4.4 for DNS instead of host provided DNS and thus won't be able to resolve any private zones.

**Comment by superseb** [comment]
The agent does not hardcode anything, Ubuntu 18.04 uses systemd-resolved which has an IP from the loopback range in `/etc/resolv.conf`, and Docker automatically picks Google's DNS if it finds unreachable addresses in `/etc/resolv.conf`. Resolutions are mentioned here https://github.com/rancher/rancher/issues/10249, https://github.com/rancher/rancher/issues/13888 and soon in the docs here: https://github.com/rancher/rancher.github.io/pull/1040/files

**Comment by doreplado** [comment]
@superseb could you provide some background on "unreachable" addresses? Here's the scenario:

Docker hosts resolv.conf 

```
 cat /etc/resolv.conf 
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "systemd-resolve --status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
search ec2.internal
```

The address is reachable - 

```
ubuntu@rancher-test:~$ nc -tvvz 127.0.0.53 53
Connection to 127.0.0.53 53 port [tcp/domain] succeeded!
ubuntu@rancher-test:~$ nc -tuvz 127.0.0.53 53
Connection to 127.0.0.53 53 port [udp/domain] succeeded!
```

The Resolution works as well:

```
ubuntu@rancher-test:~$ nslookup 
> server 127.0.0.53
Default server: 127.0.0.53
Address: 127.0.0.53#53
> rancher.infra.<ourdomain>.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   rancher.infra.<ourdomain>.com
Address: 10.200.99.52
> 
```

And the output from the bootstrap container (replacing the actual domain with <ourdomain>):
```
...
ERROR: http://rancher.infra.<ourdomain>:8080/v1 is not accessible (Could not resolve host: rancher.infra.<ourdomain>.com)
ERROR: http://rancher.infra.<ourdomain>.com:8080/v1 is not accessible (Could not resolve host: rancher.infra.<ourdomain>.com)
ERROR: http://rancher.infra.<ourdomain>.com:8080/v1 is not accessible (Could not resolve host: rancher.infra.<ourdomain>.com)
...
```

Also this is not an issue for Ubuntu 16.04, just Ubuntu 18.04
Does this mean Rancher 1.6.x isn't supported on Ubuntu 18.04 with Private DNS Zones?
