### ISSUE TITLE
Ability to create Workloads, ingress, services configuration via helm/yml that match whats gets created in the UI

### ISSUE THREAD

**Issue by josmo** [rancher/rancher#14843]
There's no simple way to re-create the items in a similar way to the Rancher UI other then creating them and trying to reverse the config out while figuring out what matters and what doesn't.  It would be great to have a tool/documents on what is the similar way of creating workloads/ingress/services, etc that ends up with the same configs

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`` `admin`|
|Route|`ingresses.index`|

**Comment by deniseschannon** [comment]
After you create something in the UI, you can look at "View/Edit YAML" of what you've created.
