### ISSUE TITLE
I can't acess the kubectl shell

### ISSUE THREAD

**Issue by matheus666matheus** [rancher/rancher#14846]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.6
rancher/agent or rancher/rancher-agent: v1.10.5

**Docker version: (`docker version`,`docker info` preferred)**

Containers: 55
 Running: 25
 Paused: 0
 Stopped: 30
Images: 29
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 286
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.68 GiB
Name: s3797
ID: 4E36:GBM2:NYXK:GREB:X6GK:4PJT:ZPQY:N6JR:AYDD:7YPG:4CSQ:BKKW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA rancher

**Steps to Reproduce:**

I follow the steps of this tutorial:
https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/

**Results:**

**After this, I can't acess the kubectl shell.**  The "connecting" status is displayed, 
and the connection is never established.

I can acess any other shell.

I am able to acess the cluster outside rancher, with the kubectl CLI + config file.

**Comment by superseb** [comment]
It tries to shell into a pod in the cluster. Can you check:

- `kubectl get pods -n cattle-system`
- `kubectl logs -n cattle-system -l app=cattle-agent`

**Comment by matheus666matheus** [comment]
**kubectl get pods -n cattle-system**

NAME                                    READY     STATUS             RESTARTS   AGE
cattle-859b6cdc6b-g5jbc                 1/1       Running            0          3d
cattle-cluster-agent-6874857578-g2cgf   0/1       CrashLoopBackOff   1074       3d
cattle-node-agent-fxjb6                 0/1       CrashLoopBackOff   1074       3d
cattle-node-agent-jmlct                 0/1       CrashLoopBackOff   1074       3d
cattle-node-agent-xh2jn                 0/1       CrashLoopBackOff   1076       3d


**ERROR: Failed to pull the cacert from the rancher server settings at** https://rancher.corenmg.gov.br/v3/settings/cacerts

**Comment by matheus666matheus** [comment]
I did not set the dns...just put the name resolution to the external LB on /etc/hosts....any problem?

**Comment by stefanfritsch** [comment]
@superseb related but not really a new issue:

How do I change that URL? 

Looking at the yaml of the cattle-agent it seems hardcoded in an environment variable. But where's the value from?

Thanks,
Stefan

**Comment by superseb** [comment]
https://rancher.com/docs/rancher/v2.x/en/admin-settings/server-url/

**Comment by stefanfritsch** [comment]
I'd changed that already but when I kill the pods they're still recreated with the old one.

**Comment by superseb** [comment]
Ok let me run some tests on it. For now you can edit the DaemonSet to make the change

```
kubectl edit ds cattle-cluster-agent -n cattle-system
kubectl edit ds cattle-node-agent -n cattle-system
```

**Comment by stefanfritsch** [comment]
Hi,

thanks for your patience and help. :)

Unfortunately there is no ds cattle-cluster-agent:

```
~# kubectl get ds -n cattle-system
NAME                DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
cattle-node-agent   1         1         0         1            0           <none>          11d
```

And while I've edited the conf for the cattle-node-agent when I kill the node-agent pod it still shows the old URL after it comes back online (and into the crash loop). Do I have to reboot the daemonset (sorry if that's a stupid question)? Or cattle? Is there some specific order to restarting the services?

Thanks again,
Stefan
