### ISSUE TITLE
Add helm values.yaml support

### ISSUE THREAD

**Issue by Flowman** [rancher/rancher#14844]
**Rancher versions:**
rancher/rancher: 2.0.6

I have an issue where I'm trying to change the configuration for https://github.com/helm/charts/tree/master/stable/percona-xtradb-cluster. 

There is a value called configFiles with the value of:
```
configFiles:
  node.cnf: |+
    [mysqld]
    datadir=/var/lib/mysql
    default_storage_engine=InnoDB
    binlog_format=ROW
    innodb_flush_log_at_trx_commit  = 0
    innodb_flush_method             = O_DIRECT
    innodb_file_per_table           = 1
    innodb_autoinc_lock_mode=2
    bind_address = 0.0.0.0
    wsrep_slave_threads=2
    wsrep_cluster_address=gcomm://
    wsrep_provider=/usr/lib/galera3/libgalera_smm.so
    wsrep_cluster_name=galera
    wsrep_sst_method=xtrabackup-v2
```
There is no way of adding this to the 'add answer' at the moment as it bugs out on the format.

It would be nice if we could edit the values.yaml when we are creating from the catalog. Maybe add one more button 'add values.yaml' or something.

**Comment by scottcressi** [comment]
+1

Can we make this a priority?  I am paying for support and this feature is critical.  With pure helm you can use the -f flag to specify a values.yaml from outside the chart folder being deployed file as to not have to touch said chart repo.  This values.yaml would override the one in the chart folder, I shouldn't have to specify a question.yaml (which is also in a different format) inside the chart folder, thus modifying a potential public fork.  The forks should have the potential to always be pristine.

**Comment by deniseschannon** [comment]
In master today, we've added the ability to edit the catalog answers as a yaml file and you can add in your own values. I believe this would solve your request. 

<img width="1291" alt="screen shot 2018-08-29 at 12 02 59 pm" src="https://user-images.githubusercontent.com/11410997/44809413-7d890f80-ab83-11e8-86a0-e22269a9a141.png">

**Comment by deniseschannon** [comment]
This is the `values.yaml` file in the helm chart repo, but you can see that you can add more lines at the bottom of when you can edit the yaml.  

<img width="1359" alt="screen shot 2018-08-29 at 12 03 34 pm" src="https://user-images.githubusercontent.com/11410997/44809476-a7423680-ab83-11e8-9693-a68f498c7f58.png">

**Comment by deniseschannon** [comment]
@loganhz can you comment on his question?

**Comment by loganhz** [comment]
If you click `Edit as YAML`, you can input or upload a YAML format text. It will convert the YAML to key/value in Rancher UI. Rancher UI still pass it as key/value pairs to Rancher server.

Example

![image](https://user-images.githubusercontent.com/21168270/44824423-06618300-ac38-11e8-889a-cd6658dc6e58.png)

![image](https://user-images.githubusercontent.com/21168270/44824464-3e68c600-ac38-11e8-9953-f758318af357.png)

**Comment by scottcressi** [comment]
Excellent, thank you!

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/4
Verified fixed
