### ISSUE TITLE
health check issue in rancher 

### ISSUE THREAD

**Issue by bibin-skaria** [rancher/rancher#14842]
Hi,
I recently started using rancher. I ran EKS in which was successful, later when i tried to launch k8s in direct digital ocean or EC2 it showing this issue.

	"[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [54.184.95.108]: Get https://localhost:6443/healthz: can not build dialer to c-pgpsr:m-mgjfc, log: I0730 10:08:17.005398 1 storage_rbac.go:279] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public"

please help me to resolve this issue 

i used "sudo docker run -d --restart=unless-stopped -p 8080:80 -p 4443:443 rancher/rancher
" to install rancher in my local machine. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
Please see https://github.com/rancher/rancher/issues/12657#issuecomment-391362566 and see what caues the issue

**Comment by bibin-skaria** [comment]
still showing same issue 
i reinstalled rancher "sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher"

**Comment by superseb** [comment]
The comment shows 3 steps you can check to determine where it's failing. It does not say to reinstall Rancher.

If you check the 3 steps (1. Check connectivity from added host to Rancher, 2. check rancher/rancher-agent logging, 3. check LB/proxy configuration), you can determine where it is failing.

**Comment by dgabrysch** [comment]
Got the same issue - isn't it a problem with rancher trying to access the health endpoint of the kube-apiserver which has a self signed cert?

**Comment by janeczku** [comment]
@dgabrysch make sure you are not hitting this bug with your self-signed cert: https://github.com/rancher/rancher/issues/13831

**Comment by dgabrysch** [comment]
@janeczku checked that :)

**Comment by dgabrysch** [comment]
Actually it doesn't even work when I do not provide own certs and simply start the rancher server without any cert options.

**Comment by twillert** [comment]
Hi @bibin-skaria,
did you manage to resolve this issue or find a workaround for it? I am having same problem here :(

/ Thomas

**Comment by superseb** [comment]
If it doesn't work with the default certificates, there is either a network connectivity issue (Agent cannot reach configured `server-url` using TCP/443) or a proxy configuration blocking the communication. The steps to check are also listed above and it helps diagnosing issues if they are followed and if the output if provided.
