### ISSUE TITLE
Cannot start a single host install folowing the quickstart

### ISSUE THREAD

**Issue by schmurfy** [rancher/rancher#14840]
**Rancher versions:**
rancher/rancher: latest
rancher/rancher-agent: v2.0.6

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Steps to Reproduce:**
- install rancher on rancheros
- go into the webadmin, "Add Cluster", select "Custom" and set a name, click "Next"
- check "etcd", "Control Plane", set internal and public address
- copy & paste the command on  host where rancher is running, click "Save"

After some time doing the provisioning I get that:

`[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [169.254.249.57]: Get https://localhost:6443/healthz: dial tcp [::1]:6443: getsockopt: connection refused, log: Unable to find suitable network address.error='unable to select an IP from default routes.'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.`

I have no clue how to set the `AdvertiseAddress` or `BindAddress` the error is mentioning.

**Comment by superseb** [comment]
The error is on the host you are trying to add, can you supply more information on that host? Also, if the IP is not masked in your output, your machine has an interface with a link local address which gets picked up as default route apparently (which is wrong configuration). (https://en.wikipedia.org/wiki/Link-local_address)

What host are you trying to add (OS/image/Docker)? What is the output of `ip route`, `ip route get 8.8.8.8` and `ip addr show` on the host you are trying to add?

**Comment by schmurfy** [comment]
That host is a rancheros running a slightly modified version of it to add zfs.
The host where rancher is running is the same one I am trying to add to the cluster.

```
$ ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 98:f2:b3:3f:e7:10 brd ff:ff:ff:ff:ff:ff
    inet 169.254.249.57/24 brd 169.254.249.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::9af2:b3ff:fe3f:e710/64 scope link
       valid_lft forever preferred_lft forever

6: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:43:f2:a1:f8 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:43ff:fef2:a1f8/64 scope link
       valid_lft forever preferred_lft forever
8: veth40fe5f8@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether 12:e5:4d:d5:b0:a2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::10e5:4dff:fed5:b0a2/64 scope link
       valid_lft forever preferred_lft forever
```

```
$ ip route
default via 169.254.249.3 dev eth0 src 169.254.249.57 metric 202
169.254.249.0/24 dev eth0 proto kernel scope link src 169.254.249.57 metric 202
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
```

```
$ ip r get 8.8.8.8
8.8.8.8 via 169.254.249.3 dev eth0 src 169.254.249.57
    cache
```

```
$ ping -c 5 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=122 time=1.640 ms
64 bytes from 8.8.8.8: seq=1 ttl=122 time=1.589 ms
64 bytes from 8.8.8.8: seq=2 ttl=122 time=1.604 ms
64 bytes from 8.8.8.8: seq=3 ttl=122 time=1.605 ms
64 bytes from 8.8.8.8: seq=4 ttl=122 time=1.609 ms

--- 8.8.8.8 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 1.589/1.609/1.640 ms

```

**Comment by schmurfy** [comment]
no idea ?:(

**Comment by superseb** [comment]
Where are you running this from? The range configured is not for use, and seeing the error, Kubernetes does not accept this range either to use, and errors out because it can't find a valid IP. Best way to solve this is to pick a valid network range, configure this on your node and run it again.

**Comment by schmurfy** [comment]
What you call a "valid" range is highly subjective, they are not routable in public space true but we have our own space in a datacenter and we use this range for internal addressing, if this is what is causing the issue you should really consider the usage of people not using public hosting as I know for a fact that we are not the only one to do this.

I suppose I will just stick with rancher v1 which is working fine, I tried rancher v2 to see what was changed.

**Comment by vincent99** [comment]
"We" are not the ones deciding this, it's [part of kubernetes](https://github.com/kubernetes/kubernetes/blob/3a3d6564b6ef5810988abb26782bc571b6bec31f/staging/src/k8s.io/api/core/v1/generated.proto#L940).

169.254/16 is reserved by RFC 3927 for link-local addressing, which are self-configuring, dynamic, short-lived and not appropriate for the public identity of a node.

Yes you can make up whatever IPs you want, but if you're going to ignore standards  you shouldn't be surprised that it sometimes has consequences.

1.x has no check for this, but only appears fine because you happened to not pick 169.254.169/24 and nobody's plugged in a laptop that happened to pick an address in use and trigger the conflict resolution protocol, yet.

**Comment by schmurfy** [comment]
Ok fine, that's really disappointing but I will stick with rancher v1.
We can argue for a while on what we should or should not use but it will lead nowhere, we did not pick the ranges we uses at random and since it never exits our own datacenter cabinet there is no risk of conflict with anything else.
I now understand the rancher project is not reponsible for that choice so let's just close this, I just hate when softwares makes dubious checks like these to "protect" the user against his will...
