### ISSUE TITLE
Reimporting cluster breaks outbound traffic in cluster

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#14848]
Master as of 7/30.

With system project in master there is potential to break a cluster if it's imported twice. 

Create a standalone cluster.
Import into rancher
Detete cluster
Import again

This will cause all pods to no longer be able to talk out of the cluster to the internet

**Comment by alena1108** [comment]
@dramich I thought it got addressed by cleaning up rancher project annotations?

**Comment by sangeethah** [comment]
Tested with latest rancher-server build from master

Create a standalone RKE cluster.
Import into rancher
Created few projects and workloads.
Deteted cluster
Import again.

Import fails with following errors:

```
MacBook-Pro-3:rke19 sangeethahariharan$ curl --insecure -sfL https://206.81.5.129/v3/import/ns9qmg7nbkb74j54vw4mwpt8fkzphs5q9jf2hxjhgksq7w6v5wj9dm.yaml | kubectl --kubeconfig ./kube_config_cluster.yml apply -f -
namespace "cattle-system" configured
clusterrolebinding "cattle-admin-binding" created
clusterrole "cattle-admin" created
Error from server (Forbidden): error when creating "STDIN": serviceaccounts "cattle" is forbidden: unable to create new content in namespace cattle-system because it is being terminated
Error from server (Forbidden): error when creating "STDIN": secrets "cattle-credentials-6428410" is forbidden: unable to create new content in namespace cattle-system because it is being terminated
Error from server (Forbidden): error when creating "STDIN": deployments.extensions "cattle-cluster-agent" is forbidden: unable to create new content in namespace cattle-system because it is being terminated
Error from server (Forbidden): error when creating "STDIN": daemonsets.extensions "cattle-node-agent" is forbidden: unable to create new content in namespace cattle-system because it is being terminated
MacBook-Pro-3:rke19 sangeethahariharan$ 
```

**Comment by dramich** [comment]
The errors seen were a result of the node in the cluster going down. The cluster died so k8s was not able to delete the cattle-system namespace due to the pods that were scheduled to the node being stuck. After removing the node from the cluster the cattle-system namespace was deleted and the cluster was able to be reimported. 

The cleanup performed as expected by cleaning up all objects that it was able to.

**Comment by sangeethah** [comment]
When all the nodes in the cluster was in "Active" state . The issue seen above was not encountered.

Create a standalone RKE cluster.
Import into rancher
Created few projects and workloads.
Deteted cluster from rancher.
Import again.

Able to create new pods in "default" namespace which have access to internet.
Able to exec into existing pods and reach google.com .
MacBook-Pro-3:rke19 sangeethahariharan$ kubectl exec -it mystep1-testsd1-fpslh -n mystep1-ns1  bash 
root@mystep1-testsd1-fpslh:/# 
root@mystep1-testsd1-fpslh:/# ping google.com
PING google.com (172.217.5.14): 48 data bytes
56 bytes from 172.217.5.14: icmp_seq=0 ttl=43 time=19.097 ms
56 bytes from 172.217.5.14: icmp_seq=1 ttl=43 time=19.160 ms
^C--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 19.097/19.129/19.160/0.032 ms
root@mystep1-testsd1-fpslh:/#
