### ISSUE TITLE
Moving namespaces between projects doesn't move catalog entry

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#14845]
**Rancher versions:**
rancher/rancher: v2.0.6
**Steps to Reproduce:**
Have to projects, deploy a catalog item to a namespace in a project
Move the namespace to a different project

**Results:**
The workloads appear in the new project, but the App entry still appears as an entry in the old project, the App entry should move with the namespace.

**Comment by superseb** [comment]
It's also possible to delete the namespace that is created for an app without warning.

**Comment by StrongMonkey** [comment]
App is designed to be live in a project. It is a project-level resource. To make it movable we have to change app to be a cluster-level resource(like namespace) and make it assignable to projects.

**Comment by cjellick** [comment]
@chrisurwin from your perspective is preventing the namespace from moving in this scenario be sufficent or do you have an explicit need to be able to create an app in project A and move it to project B?
I'm not even 100% sure that is feasible, just want to know our options

**Comment by StrongMonkey** [comment]
@cjellick to be able to achieve this we need to add a separate controller to clone app across projects. This is to say, delete the old one(remove finalizers first to make sure it doesn't really remove), create a new one. Just want you to know the design detail to see if you are comfortable with it.

**Comment by cjellick** [comment]
@StrongMonkey a couple follow up questions:
- how would this be initiated? Would the user move the app which would cause the namespace to follow or would moving the namespace cause the app to follow?
- can the app really be safely moved via create and delete? The ID of the app would change, could that have any consequences?

My thoughts:
If moving the app by deleting and recreating it is "safe" from the backend perspective, then we should:
1. Have an explicit "move" action on the app resource
2. Prevent moving a namespace that is associated with an app. Like, trying to move the namespace should result in an error that says "This namespace was created by Application-Foo. You must move the app to the desired project to cause this namespace to move" (will have to wordsmith that one a bit)

@chrisurwin seem like a decent approach?
@vincent99 care to sanity check me on that from a usability perspective?

**Comment by chrisurwin** [comment]
@cjellick 
What if the app is deployed to an already existing namespace and doesn't create it?
What if there are other apps/pods running in the same namespace?
When you say delete and recreate, I'm assuming that's just the association, not the actual pods?

**Comment by StrongMonkey** [comment]
@chrisurwin is there a real use case to move app across projects? If not, Can we just go Craig's No.2 approach which adds validation to prevent namespace being moved if  it is used by an app?

**Comment by StrongMonkey** [comment]
@cjellick validation is added through api level in those two pr linked above.

**Comment by StrongMonkey** [comment]
@cjellick PRs were updated and ready to review.

**Comment by cjellick** [comment]
CLI needs updated to address this, as does the UI

**Comment by cjellick** [comment]
Backend in, needs UI

**Comment by cjellick** [comment]
Assigned @dramich because he put in the CLI fix

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/12
Can still move namespaces without error showing up.

**Comment by StrongMonkey** [comment]
@tfiduccia there is no move action in app. The correct step to verify this is to:
1. Create an app. Waiting for it to be active.
2. Go to the namespace associated with the app. The namespace should not have move action, as it is not allowed to be moved since it is currently used by an app.

**Comment by cjellick** [comment]
CLI is also impacted by this change and will need tested.

**Comment by cjellick** [comment]
Reviewing the comments on this issue, I see that we never clearly defined what the final solution was.

The original problem was that when you moved a namespace to a different project, if it was associated to an app, the app DID NOT move.This left the system in a funky state where the namesapce was in one project, but its associated app was in another.

The fix is to remove the ability to move an namespace if that namespace is associated to an app. The UI should completely drop the move option from the namespace in this case (because the API dropped the corresponding action).

I am going to put this one in merged-but-not ready to test until the CLI is updated and merged

**Comment by westlywright** [comment]
@cjellick i was able to verify that the UI does not show the `Move` action for a namespace with an app running. `Move` does exist for a namespace without an app.

**Comment by cjellick** [comment]
OK, I'm moving back to test

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
Verified fixed

**Comment by andfilipe1** [comment]
I think what makes sense is to take the project field and leave it as it happens in k8s, separated by namespace.
