### ISSUE TITLE
UI Issues for Project Quota

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14859]
**Rancher versions:** 2.0 master 7/30

**Steps to Reproduce:**

- [x] Should only be allow to enter 1 of each item
![image](https://user-images.githubusercontent.com/11514927/43424691-0f601e6c-9405-11e8-9066-ff4ef12bb537.png)

- [x] Resource Quota column has nothing in it if it's using default.  Should probably have something like default there.
![image](https://user-images.githubusercontent.com/11514927/43425551-cb5d6c6c-9407-11e8-9756-1ff5711d302b.png)

- [x] Change the text in namespace edit for the Quota Template from "Use the default quota template...." to "Use default template"
![image](https://user-images.githubusercontent.com/11514927/43426294-18016706-940a-11e8-8150-dce1324901f8.png)

- [x] Created column no longer functioning
![image](https://user-images.githubusercontent.com/11514927/43426286-0f46a540-940a-11e8-8e70-4202463cefa3.png)

- [x] Quota template drop-down is order by date of creation instead of alphabetic
![image](https://user-images.githubusercontent.com/11514927/43426369-5367c902-940a-11e8-8be9-3904bf038434.png)

- [x] "Storage Reservation" & "Persistent Volume Claims" Resource type is not supported this version, needs to be taken out of list
![image](https://user-images.githubusercontent.com/11514927/43427875-6dd4e5d0-9410-11e8-9e98-34b3748bef5f.png)

**Comment by loganhz** [comment]
Hi @tfiduccia , do we still need to hide  "Storage Reservation" & "Persistent Volume Claims" ?

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/29
Verified fixed
