### ISSUE TITLE
2.0.6 Unschedulable nodes not running Deamonset

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#14852]
Hello, 

I am trying to get my daemonset to deploy to my master nodes but the pods in the daemonset are skipping the nodes with the unschedulable taint. I thought daemonsets ignored this taint?

**Comment by superseb** [comment]
Taints applied to nodes are described here: https://rancher.com/docs/rke/v0.1.x/en/config-options/nodes/#kubernetes-roles

Tolerations for DaemonSets are described here: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#how-daemon-pods-are-scheduled
