### ISSUE TITLE
enableNetworkPolicy not being returned by API for RKE Canal clusters 

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14851]
**Rancher versions:** 2.0 master 7/30

**Steps to Reproduce:**
1.  Create a RKE cluster with the Network Provider = Canal and Project Network Isolation = true

**Results:**  The Project Network policy gets set in the UI but not returned by API.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/2

Network policy is being return but it's always false.  Posting - true, returning "false"

**Comment by kinarashah** [comment]
We should also test for upgraded canal clusters, spec should show `true`.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/8
UI and API are fixed.  Needs to be tested with upgrade.  Sending to Soumya.

**Comment by adingilloRancher** [comment]
v2.0.7-rc3

Canal network policy reflects true for post upgrade.
