### ISSUE TITLE
Can't create pods in project with limits

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14854]
**Rancher versions:** 2.0 master 7/30

**Steps to Reproduce:**
1.  Create a project with a pod limit that 8
2.  Go to project and try to create a workload with 1 pod

**Results:**  Fails.
Pods "wrkld1-fc5d74c46-5r65z" is forbidden: failed quota: default-gfgvj: must specify limits.cpu,limits.memory,requests.cpu,requests.memory; Deployment does not have minimum availability.

**Comment by soumyalj** [comment]
Tested with master, 
Create a project with resource quota for CPU and Pods.
Create a workload with just pods 

Error pops up in UI saying "CPU limit" is required
<img width="1289" alt="screen shot 2018-09-14 at 12 13 12 pm" src="https://user-images.githubusercontent.com/18536626/45570444-a2ce7c80-b817-11e8-97c7-0d0fe103d793.png">

Can we add more information to the error message saying "CPU limit is required as resource quota is enforced on the project"

**Comment by cjellick** [comment]
Change to the error message is not a UI issue

**Comment by cjellick** [comment]
Nope, i'm wrong. this vlidation is in the UI

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
Verified fixed
