### ISSUE TITLE
"Rancher API Host field" text field missing for Ping and MS

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14850]
**Rancher versions:** 2.0 master 7/30

**Steps to Reproduce:**
1.  Go to Ping or Microsoft authentication

**Results:**  The Rancher API host field text field is missing
![image](https://user-images.githubusercontent.com/11514927/43418443-c414fb74-93f2-11e8-9dd1-72f444fa48ef.png)

**Comment by adingilloRancher** [comment]
Also, fields sp cert, sp key, and metadata content are missing as of today.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/31
Verified fixed
