### ISSUE TITLE
Rancher 1.6.20 shows unsupported version for Docker 18.06.0

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#14856]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.20
rancher/agent or rancher/rancher-agent: 1.2.11

The release notes state that 18.06 has been tested, but it shows up as an untested version inside Rancher for the hosts.

**Comment by soumyalj** [comment]
Reproduced the issue in v1.6.21. 
Deployed rancher server  v1.6.22-rc3 with docker v18.06 hosts. The hosts do not show up as "Untested Docker version".
<img width="830" alt="screen shot 2018-09-04 at 10 51 54 am" src="https://user-images.githubusercontent.com/18536626/45048369-946eac80-b030-11e8-8af9-aea10627ffe2.png">

**Comment by stefanlasiewski** [comment]
Is this bug fixed in 1.6.22 , or 1.6.23? It's not mentioned in the 1.6.22 release notes under "Major Bug Fixes" at https://github.com/rancher/rancher/releases/tag/v1.6.22 .

**Comment by vincent99** [comment]
Backend support was in 20, and updating the setting the UI reads from to show it as supported in 22.  Release notes do not list every issue.
