### ISSUE TITLE
Helm Charts Error messages with Patroni

### ISSUE THREAD

**Issue by webdirol** [rancher/rancher#14861]
When using the Catalog App "patroni" there are always Error messages when showing the page.

The two errors are:

Invalid catalog app version in patroni
Invalid Version: 0.5

Invalid catalog app version in patroni
Invalid Version: 0.6

Here is a screenshot:
![rancher 35](https://user-images.githubusercontent.com/14794694/43433020-de060d92-9475-11e8-988c-2d94e81a87e2.png)

**Comment by loganhz** [comment]
Hi @vincent99 , can we remove the error messages?

**Comment by matheus666matheus** [comment]
Same problem... my patroni workload is "Scheduling" forever

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/2
Verified fixed - error message resolved.

**Comment by matheus666matheus** [comment]
The fix doesn't work for me. Facing the same problem:

Invalid catalog app version in patroni
Invalid Version: 0.5

Invalid catalog app version in patroni
Invalid Version: 0.6

**Comment by loganhz** [comment]
The fix will be in 2.0.7
