### ISSUE TITLE
L4 Balancer Pending

### ISSUE THREAD

**Issue by chengxingyao** [rancher/rancher#14862]
<img width="381" alt="qq20180731-101016 2x" src="https://user-images.githubusercontent.com/10667374/43433464-0aa63fd2-94aa-11e8-8b76-6b22cd0b5afa.png">

**Comment by loganhz** [comment]
Hi @chengxingyao , does your cluster support cloud provider?

**Comment by superseb** [comment]
https://rancher.com/docs/rancher/v2.x/en/faq/technical/#why-is-my-layer-4-load-balancer-in-pending-state

**Comment by wzrdtales** [comment]
@superseb Is this on the roadmap of rancher to provide a scheduling of an bare metal l4 loadbalancer. I.e. spawning ha proxy?

**Comment by superseb** [comment]
@wzrdtales That is covered in https://github.com/rancher/rancher/issues/11179

**Comment by loganhz** [comment]
Please check https://rancher.com/docs/rancher/v2.x/en/faq/technical/#why-is-my-layer-4-load-balancer-in-pending-state
