### ISSUE TITLE
Helm Charts with complex values per Add Answer

### ISSUE THREAD

**Issue by webdirol** [rancher/rancher#14860]
Hello,
could somebody please tell me how to define values per "Add Answer" in Helm Charts for complex Keys like "nodeSelector", "affinity" or "tolerations" ?

First I set a label "backlw" = "true" in Nodes, see...

![rancher 34](https://user-images.githubusercontent.com/14794694/43432348-b3c34c96-9472-11e8-90e8-2b139bd1e7a8.png)

I want that Pods only can run on Node that have this label "backlw" = "true".

I tried it as mentioned in following issue page with: 
nodeSelector.backlw = true
https://github.com/rancher/rancher/issues/13723

I tested it with the Helm Charts "partoni" and "kube2iam" and I tried also many different formats, but nothing worked. See here some pics...

![rancher 32](https://user-images.githubusercontent.com/14794694/43432586-e9cae438-9473-11e8-810f-b74fd9630afc.png)
![rancher 33](https://user-images.githubusercontent.com/14794694/43432591-f4499e04-9473-11e8-8082-033fa56c94f1.png)
![rancher 30](https://user-images.githubusercontent.com/14794694/43432597-fe86e17e-9473-11e8-84e1-6fe9d7834043.png)
![rancher 31](https://user-images.githubusercontent.com/14794694/43432599-03fae89e-9474-11e8-80d8-0108203e5c90.png)

Do somebody know a solution for that?

Many thanks in advance!

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/46583175-03eb1800-ca85-11e8-9ade-d599fc3d0843.png)

This works in v2.1.0
