### ISSUE TITLE
[Feature request] list pods on node

### ISSUE THREAD

**Issue by tobru** [rancher/rancher#14868]
**Rancher versions:**
v2.0.6

There is currently no view available which lists all Pods running on a node (except using the kubectl cli). I would expect that when I navigate to "Nodes" and click on a node for the detail view that I get a list of Pods which are currently running on this node, next to all the other information currently displayed. On this list I would expect to se

Mandatory:

* Pod name
* Namespace the Pod belongs to
* Pod status

Optional:

* CPU Requests
* CPU Limits
* Memory Requests
* Memory Limits

**Comment by KaelBaldwin** [comment]
I know it's a little different, but there is the "group by node" option in each projects workload tab.

I only bring this up, because I wanted the same thing you are asking for, and then saw the group by node option and that was good enough for me.

But I would also use the view you are describing if it was added.

**Comment by tobru** [comment]
Yeah, that's a nice feature, but doesn't really solve my feature request. @KaelBaldwin did you create a GitHub issue in the past for that? If yes, we could link it here.

**Comment by loganhz** [comment]
https://github.com/rancher/rancher/issues/11024

**Comment by loganhz** [comment]
There is no Rancher API to get the pods list of a node now.
@vincent99 Can we use the k8s API directly for it? Or we will add it in Rancher?

**Comment by vincent99** [comment]
No, that's ugly and won't live update (and polling it is even uglier).

You can possibly fix whatever reason `hasMany` didn't work.  And really the API should have an actual field for `nodeId` instead of (ab)using `nodeName`.

But we don't need two issues for this.

**Comment by tobru** [comment]
Thanks for discussing this and pointing me to the already existing issue.

> Can we use the k8s API directly for it?

The Kubernetes API could be used, but I'm not familiar with the Rancher internals...

**Comment by KaelBaldwin** [comment]
sorry @tobru, I did not

**Comment by Leen15** [comment]
Any update here?
