### ISSUE TITLE
The 'rancher/rancher' link on the 'rancher/rancher' dockerhub page is broken

### ISSUE THREAD

**Issue by sdanieru** [rancher/rancher#14873]
On this page:
https://hub.docker.com/r/rancher/rancher/

The 'rancher/rancher' link is broken. It's trying to go to:

https://github.com/rancherio/rancher/tree/master/rancher

which doesn't exist. Maybe you want it to link here:

https://github.com/rancher/rancher

**Comment by deniseschannon** [comment]
@sdanieru Thanks! I've updated it to go to here: https://github.com/rancher/rancher/tree/master
