### ISSUE TITLE
Keycloak UI should clearly tell the user the protocol we support, i.e. SAML

### ISSUE THREAD

**Issue by carolynhu** [rancher/rancher#14874]
Keycloak UI should say we support `SAML` protocol (since keycloak allows two protocols: `OpenID` and `SAML`), like what we did for FreeIPA:
 
<img width="220" alt="screen shot 2018-07-31 at 2 07 19 pm" src="https://user-images.githubusercontent.com/29208297/43487314-23999022-94cb-11e8-8572-7b35dc1a91f2.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/27
Verified fixed
