### ISSUE TITLE
Add network policies for Calico plugin for RKE clusters 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#14879]
Test existing network policies with calico, and figure out what modifications are required to get it working correctly.

gzrancher/rancher#11175

**Comment by leodotcloud** [comment]
https://github.com/rancher/rancher/issues/14085

**Comment by kinarashah** [comment]
Closing this issue, PRs to add PNP for Calico tracked and tested in https://github.com/rancher/rancher/issues/31338.
