### ISSUE TITLE
Color for Purging is blue, should probably be red

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1487]
v0.27.0-rc1
Steps:
1.  Create multiple containers
2.  Delete containers and wait (so remove turns to purge on it's own)

Results:
Purge color is blue, same as restoring

Expected:
Purge color should probably red

**Comment by tfiduccia** [comment]
the blue purge is across the application, not just for containers.

**Comment by vincent99** [comment]
Icons and colors were fairly inconsistent and all over the code before.. moved the default set of icons and colors for each state to a single place and there's now just a few overrides for things that need specific icons/colors.

You can view the default list here: https://github.com/vincent99/ui/blob/d321ae4b80be0371dc036f1669f47f1eb07316f0/app/mixins/cattle-transitioning-resource.js

I also made all the transitioning-ey ones the blue color (despite this issue).  Sometimes they were black, sometimes red before.  Now anything that is in a transitioning type state (starting, stopping, removing, purging, etc... largely the ones ending in `ing`) will be blue, and things that aren't transitioning will be the other colors but never blue.  This makes transitioning things stand out more to make it easier to spot what's changing, I think.

**Comment by tfiduccia** [comment]
v0.27.0-rc4
Verified fixed
