### ISSUE TITLE
HA - RKE Cluster does not notice downtime of cattle node

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#14872]
The HA Deployment of rancher does not work to completion. I noticed that if the node currently running the cattle pod goes down, the whole cluster dies and for some reason kubernetes does not schedule a redeployment or detects that this service died. The only fix to this is to manually step into kubectl and delete the cattle container.

Is there anything I miss here? Or is this due to missing livenessProbes in the rke example config?

**Comment by superseb** [comment]
This is covered in this issue: https://github.com/rancher/rancher/issues/14670

liveness/readiness are being added soon, as I'm adding proxy support as well.

If you want do decrease the response times on node failure/pod eviction you can use https://gist.github.com/superseb/a9925c465b42bc5001b94c4ec241265a

**Comment by wzrdtales** [comment]
ahh thanks :)
