### ISSUE TITLE
Active cluster information not being reported for telemetry

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14887]
**Rancher versions:** 2.0 master 7/31

**Steps to Reproduce:**
1. Opt-in for telemetry
2.  Add a cluster, project, namespace and workload

**Results:**  All active cluster info is 0.
![image](https://user-images.githubusercontent.com/11514927/43494383-68342f46-94e7-11e8-971b-64cf33741282.png)

**Comment by StrongMonkey** [comment]
@tfiduccia I am not able to reproduce it. I created a DO cluster and enable telemetry, i was able to fetch the info.
![screenshot from 2018-08-03 16-08-50](https://user-images.githubusercontent.com/9203378/43669431-cb1a04b2-9737-11e8-8b10-4d5dc3ccc373.png)

**Comment by StrongMonkey** [comment]
What kind of cluster were you trying with when you saw this?

**Comment by cjellick** [comment]
moving out of this release

**Comment by tfiduccia** [comment]
Version - 2.0 master 9/4
Verified fixed
