### ISSUE TITLE
If screen is resized, the Save/Close for API Key Created Overlay is off the page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1488]
v0.27.0-rc1
Steps:
1.  resize screen so it's smaller
2.  Add API Key

Results:
![image](https://cloud.githubusercontent.com/assets/11514927/8626284/d8ed6802-26f8-11e5-8298-091e7fa3d553.png)

Expected:
The Save/Close buttons shouldn't fall outside of overlay

**Comment by deniseschannon** [comment]
#1629 fixes this with more scrolling.

Verified v0.31.0-rc4
