### ISSUE TITLE
Control node-role taint missing on nodes after cluster initialization

### ISSUE THREAD

**Issue by ASCIIDuck** [rancher/rancher#14896]
**Rancher versions:** 
rancher/server or rancher/rancher: 2.0.4 
rancher/agent or rancher/rancher-agent: 2.0.4

**Infrastructure Stack versions:**

kubernetes (if applicable): v1.10.3

**Docker version: (`docker version`,`docker info` preferred)**
Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.5, kernel 4.4.0-131-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

1. Create a Kubernetes new cluster
2. Get the command to add a new node with the roles "etcd" and "control"
3. Register 3 nodes with that command at once
4. Register a 4th node with just the worker role

**Results:**

After the cluster is initialized and all the nodes are finished, all three nodes at the etcd taint but only one had the control taint.

```
$ kubectl get nodes -o json | jq ' .items[].spec| {"name": .externalID, "taints": [(.taints // [])[].key]}'
{
  "name": "tst-k8s-01",
  "taints": [
    "node-role.kubernetes.io/etcd"
  ]
}
{
  "name": "tst-k8s-02",
  "taints": [
    "node-role.kubernetes.io/controlplane",
    "node-role.kubernetes.io/etcd"
  ]
}
{
  "name": "tst-k8s-03",
  "taints": [
    "node-role.kubernetes.io/etcd"
  ]
}
{
  "name": "tst-k8s-bm-01",
  "taints": []
}
```
![image](https://user-images.githubusercontent.com/771709/43553112-031f3ab6-95b3-11e8-907a-004c5f9b42cf.png)

**Comment by galal-hussein** [comment]
rancher/rancher:master at August 3rd

I was able to test this case, and i can see both annotation present on etcd and controlplane:
```
> kubectl get nodes -o json | jq ' .items[]| {"name": .metadata.name, "taints": [(.spec.taints // [])[].key]}'
{
  "name": "hgalal-rk-do-worker1",
  "taints": []
}
{
  "name": "hgalal-rke-do1",
  "taints": [
    "node-role.kubernetes.io/controlplane",
    "node-role.kubernetes.io/etcd"
  ]
}
{
  "name": "hgalal-rke-do2",
  "taints": [
    "node-role.kubernetes.io/controlplane",
    "node-role.kubernetes.io/etcd"
  ]
}
{
  "name": "hgalal-rke-do3",
  "taints": [
    "node-role.kubernetes.io/controlplane",
    "node-role.kubernetes.io/etcd"
  ]
}
{
  "name": "hgalal-rke-do4",
  "taints": [
    "node-role.kubernetes.io/controlplane",
    "node-role.kubernetes.io/etcd"
  ]
}
{
  "name": "hgalal-rke-do5",
  "taints": [
    "node-role.kubernetes.io/controlplane",
    "node-role.kubernetes.io/etcd"
  ]
}
```
