### ISSUE TITLE
Not able to load Edit Balancer page for LB services created in previous release.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1489]
Server version- v0.27.0-rc1

Had Lb service created when in v0.26.0-rc1.
Upgraded server to  v0.27.0-rc1.
Tried to edit existing LB service.
UI is stuck in loading state.

**Comment by sangeethah** [comment]
Tested with latest UI build , I am able to now launch the "Edit" page but the targets that were present are not shown anymore.

**Comment by will-chan** [comment]
Changing this to wontfix as the rules still work.

**Comment by vincent99** [comment]
I'm going to claim "wontfix" on this one.. The target ports moved from being on the listener to the serviceLink in this release, so I don't look at where the old ports were and there appears to be no targets.  The user can fairly easily re-add the targets when they want to edit the balancer, and until then it will continue to work, vs supporting a check of ports in both places indefinitely..
