### ISSUE TITLE
Entering proper information for PingFed auth brings up another rancher modal & doesn't authenticate

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14892]
**Rancher versions:** 2.0 master 8/1

**Steps to Reproduce:**
1.  Enter all info for PingFed with properly formatted info
2.  CLick on Auth

**Results:**  Another modal pops up with Rancher on it
![image](https://user-images.githubusercontent.com/11514927/43549543-bfd3b13c-9595-11e8-95aa-4afd2ca7ee0b.png)

**Comment by mrajashree** [comment]
@tfiduccia The popup should open, but whenever I have tried it has always authenticated. So I'm not sure how it didn't turn on auth in your case, I'm not able to repro this

**Comment by tfiduccia** [comment]
Rajashree - put in Key, Cert & XML that are properly formatted but wrong credentials.  You will see it for sure then.

**Comment by mrajashree** [comment]
@tfiduccia When I entered wrong creds, the popup remains and displays this message from Ping
<img width="1440" alt="screen shot 2018-08-02 at 2 10 53 pm" src="https://user-images.githubusercontent.com/10672776/43611397-d93d2720-965d-11e8-9842-9b8298082b7c.png">

**Comment by mrajashree** [comment]
Closing this after an offline discussion with @tfiduccia
