### ISSUE TITLE
Close/Save buttons on API Key Created overlay basically do same thing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1490]
v0.27.0-rc1

Since once you click on the Add API Key button the API key is already created, there is really no reason to have a Close button.  The fact that clicking Close will not save the Name/description is not intuitive and seems like a moot point.

Expected:
Just have the Save button.  If they don't want the name/description, they can remove it manually.

**Comment by vincent99** [comment]
Ok, changed to one button that says either Close or Save.

**Comment by deniseschannon** [comment]
v0.27.0-rc4 - verified fixed.
