### ISSUE TITLE
Using helm to upgrade the app, the container has become more

### ISSUE THREAD

**Issue by wenjiasen** [rancher/rancher#14903]
*Describe your issue here*
Using helm to upgrade the app, the container has become more
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` `admin`|
|Route|`workload`|

![image](https://user-images.githubusercontent.com/16320597/43566592-86d6f6ec-9661-11e8-9afe-e17c175a8ba4.png)
![image](https://user-images.githubusercontent.com/16320597/43566646-bcd305d8-9661-11e8-92d5-0a38f5ab0e3d.png)

**Comment by loganhz** [comment]
@wenjiasen Can you provide the reproduce steps, please?

**Comment by wenjiasen** [comment]
Both use RancherUI

**Comment by loganhz** [comment]
The new version app has two containers in the pod. The old version has one in the pod.
Please check your catalog item yaml.  The pod contains two containers obviously in the new version.

**Comment by wenjiasen** [comment]
I can be sure that only one container is defined in my depoly.

**Comment by wenjiasen** [comment]
So the solution is to close the issue?😑

**Comment by loganhz** [comment]
Can you provide the YAML for the workload?

**Comment by loganhz** [comment]
Or the catalog git URL.

**Comment by wenjiasen** [comment]
I have redeployed, maybe I will try to reproduce this error later.

**Comment by wenjiasen** [comment]
i can't reproduce this error! close it. tks.
