### ISSUE TITLE
Import AWS EKS stack into Rancher v2?

### ISSUE THREAD

**Issue by fmunteanu** [rancher/rancher#14909]
I'm reading your documentation how to deploy an EKS cluster:
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/

We prefer to create our own EKS cluster with Terraform or Cloudformation, so we can automate the process with Buildbot. Once the cluster created, how do we import it into Rancher?

I see the Custom option available. I have 3 EC2 instances and the EKS service functional, as part of a CloudFormation stack.

![Custom](https://image.ibb.co/i06cQe/Screen_Shot_2018_08_02_at_12_01_11_PM.png)

**Comment by superseb** [comment]
It shows Import existing cluster above custom. It's also described here: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/imported-clusters/

Let me know if this doesn't answer your question.
