### ISSUE TITLE
catalog app deletion doesn't cleanup the associated namespace

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#14913]
v2.0.6

Launch any catalog app and let the UI create a namespace. After the app is deployed successfully, delete the app. Now looking at the namespaces, the namespace that was created for the app was not cleaned up.

May be provide a popup while deleting the app or provide a checkbox during the app creation to delete the ns when the app is deleted.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/13159

We most likely will never delete the namespace as there is no way to tell that other workloads might be deployed in the namespace
