### ISSUE TITLE
Unable to edit server-url under settings from UI 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#14926]
rancher/rancher: master 08/02 

No option to edit, but can do so from API. 

<img width="1680" alt="screen shot 2018-08-02 at 5 43 03 pm" src="https://user-images.githubusercontent.com/16870565/43618124-8f6cab16-967b-11e8-857d-d5f4aeb222fe.png">

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/8
Verified fixed
