### ISSUE TITLE
Not able to use rancher compose for creating LB service/DNS service/Ext Service/Service with links.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1493]
Server version - V0.27.0-rc1

Steps to reproduce the problem:
Create LB service/DNS service/Ext Service/Service with links.
Use "View Config" option to get the docker-compose.yml and rancher-compose.yml for the services.
rancher-compose

Using the above generated  docker-compose.yml and rancher-compose.yml with rancher-compose fails with statusCode [422] for http://<ipaddress>:8080/v1/services/1s839/?action=setservicelinks,

**Comment by leonkyneur** [comment]
occurring for me on v0.27.0-rc3

rancher-compose version v0.1.3

**Comment by deniseschannon** [comment]
Fixed in Rancher v0.28.0. Must be used with Rancher Compose v0.2.1
