### ISSUE TITLE
Unable to Upgrade Catalog or Recreate Workload After deleting a Workload created by a Catalog

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#14937]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6

In an attempt to troubleshoot a problem I wanted to stop a workload much like I'm used to being able to stop a stack in Rancher 1.6. I attempted to pause orchestration, but the POD continued to run. So I deleted the POD and it was recreated, I believe this to be a bug and opened a ticket https://github.com/rancher/rancher/issues/14935.

When that did not work, I deleted the workload. This worked. However the catalog entry then showed 0 resources. After I was done troubleshooting I wanted me workload back.

I proceeded to upgrade the Catalog entry, changing values in the answers, but the workload didn't return. Any modification of the catalog I tried resulted in no change, the workload was still missing. In the end I had to re-create the catalog. 

**Steps to Reproduce:**
1. Deploy Catalog
2. Pause Orchestration on Workload
3. Delete Workload
4. Upgrade Catalog (nothing happens)

**Expected:** The ability to stop/remove workloads and re-create them when needed from the deployed catalog. The benefit of the catalog is having the configuration of everything saved, should something go wrong being able to recreate from it is very important.

**Comment by loganhz** [comment]
Please see https://github.com/rancher/rancher/issues/14935#issuecomment-410296084
