### ISSUE TITLE
Saving Ingress in Rancher UI removes spec > tls > secretName

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#14934]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6:

Rancher removes the `secretName` from the `tls` section of the `spec` definition of an ingress rule when saving via the UI. This causes a problem with trying to use cert-manager. If you edit the ingress rule to add the TLS spec information and then go back and make a change by adding the labels or annotations, the secretName gets removed which results in cert-manager failing to procure certificates.

Related to https://github.com/rancher/rancher/issues/14924

**Reproducing:**
1. Add Ingress Rule to Load Balancers (the contents do not matter)
2. Edit the YAML and add the below TLS information to the spec section
3. Go back and edit the Ingress rule, you do not have to change anything and just click save.
4. View the YAML and the TLS section still exists but the secretName is gone.

```yaml
spec:
  tls:
  - hosts:
     - testing.com
    secretName: some-secret
```

**Expected:** Rancher should not remove anything.

**Comment by roccolangeweg** [comment]
+1 - also experiencing this issue.

Also, Rancher keeps using Self-signed Certificate when using a Cluster Issuer annotation even though the CRTs have been created, so I have to manually move stuff around to finally have SSL working.

**Comment by ekristen** [comment]
@roccolangeweg I have cert-manager as ClusterIssuer working from the Rancher Chart Library ... what issues are experiencing beyond the one outline here?

**Comment by kinarashah** [comment]
@ekristen 
was this secret of type `kubernetes.io/tls` ? was it available to all namespaces or just a single namespace?

**Comment by ekristen** [comment]
I didn't create the secret, the cert-manager creates the secret it just wants to know the secret name.

It gets created in the namespace the ingress is created, the type is indeed `kubernetes.io/tls` they do not appear in the Rancher UI.

```
Name:         cert-manager-jenkins
Namespace:    jenkins
Labels:       certmanager.k8s.io/certificate-name=cert-manager-jenkins
Annotations:  certmanager.k8s.io/alt-names=jenkins.example.com
              certmanager.k8s.io/common-name=jenkins.example.com
              certmanager.k8s.io/issuer-kind=ClusterIssuer
              certmanager.k8s.io/issuer-name=letsencrypt-prod

Type:  kubernetes.io/tls

Data
====
tls.crt:  3814 bytes
tls.key:  1679 bytes
```

**Comment by kinarashah** [comment]
Hi @ekristen, thank you for quick reply, have submitted a fix for this issue. 
But I think it should up in Rancher UI under `certificates`, let me know if doesn't, that'd be another thing to fix.

**Comment by ekristen** [comment]
@kinarashah yes that’s right it does show up there, I actually have another bug open on certificates not being shown properly in the UI https://github.com/rancher/rancher/issues/14921

**Comment by cjellick** [comment]
@mrajashree to validate

**Comment by mrajashree** [comment]
Steps to repro:
1. Start rancher/rancher:v2.0.8 
2. Launch grafana app
3. Clicked **View/Edit YAML** for the ingress and added the example snippet
```
spec:
  tls:
  - hosts:
     - testing.com
    secretName: some-secret
```
4. Clicked on **Save**,  and then clicked on view YAML again, the secretName was not retained
<img width="261" alt="screen shot 2018-09-12 at 12 38 59 pm" src="https://user-images.githubusercontent.com/10672776/45449172-4a697480-b689-11e8-9790-e507f7ee5a8d.png">

Steps to validate it's fixed:
1. Start rancher/rancher:master
2. Launch grafana app
3. Clicked on **View/Edit YAML** for the ingress and added the same example snippet
4. Clicked on **Save**, and then clicked on view YAML again, the secretName was retained
<img width="412" alt="screen shot 2018-09-12 at 12 40 39 pm" src="https://user-images.githubusercontent.com/10672776/45449302-a502d080-b689-11e8-84e1-9a649f59b59d.png">

**Comment by jonaskello** [comment]
@ekristen About your comment:

> I think it would also be good to add an option to the UI to tell rancher to automatically create a secretName if one doesn’t exist or indicate this should be a TLS endpoint without having to specify a cert manually.

I think this is a really good idea too. Did you file a separate issue for this?

**Comment by ekristen** [comment]
https://github.com/rancher/rancher/issues/17467

**Comment by parksquare** [comment]
I'm seeing this problem in Rancher v2.3.4, has the fix regressed?
