### ISSUE TITLE
[cli] rancher/cli docker image requires login to be ran first before using login command

### ISSUE THREAD

**Issue by FinlayDaG33k** [rancher/rancher#14947]
Hii there,

I'm trying to set up a ci/cd pipeline using Gitlab(.com) and Rancher.
I am currently at the stage of trying to deploy my app to the Rancher server (using the `rancher/cli` docker image), when I came across this error:
Rancher wants me to run the `login` command before running the `login` command...
![Well, that's quite a predicament](https://i.imgur.com/veZGkpD.png)

Running the dedicated Windows binary works but, running the `rancher/cli` image on my workstation (using ` docker run -rm -it rancher/cli login --name "$RANCHER_NAME" -t "$RANCHER_TOKEN" --context "$RANCHER_CONTEXT" "$RANCHER_URL"`) gave me the same issue (so it probably is something with the docker image):
![hmm...](https://i.imgur.com/OsHmHOg.png)

I wonder if anybody else came across this and especially if this can be fixed soon as it prevents me from continuing 😭

**Comment by FinlayDaG33k** [comment]
This issue was fixed by making the container download and install the latest binary.
Please update the image to use the latest binary please :3 (I unfortunately do not know how to, else I would have made a PR)

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/14448
