### ISSUE TITLE
[rfe] ability to define the docker bridge cidr in AKS

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#14949]
**Rancher versions:**
rancher/rancher: 2.0.6

**Use case:**
The default docker bridge subnet 172.17.x.x conflicts with some preexisting networks sometimes. Connecting an AKS cluster VNET to on premises resources could surface this conflict. The ability to change this appears to be present for [Azure AKS advanced networking config](https://docs.microsoft.com/en-us/azure/aks/networking-overview), would like for rancher to surface that option when creating AKS clusters.

**Comment by deniseschannon** [comment]
Previously @nathan-jenan-rancher had investigated if this was possible through the API and couldn't find a field to update, but it may be available now.

**Comment by deniseschannon** [comment]
@thxCode Could you check if this is available in the AKS API and if not, please comment with that information.

**Comment by thxCode** [comment]
It's configurable now.

<img width="759" alt="screen shot 2018-11-16 at 07 49 05 1" src="https://user-images.githubusercontent.com/3394724/48589115-03437c80-e975-11e8-81d6-d8ae4137791d.png">

**Comment by thxCode** [comment]
@loganhz, on `master` branch rancher, `kontainer-engine` has provided an option `docker-bridge-cidr`(dockerBridgeCIDR) to support Docker Bridge CIDR defination in AKS. https://github.com/rancher/rancher/blob/94beacf49092cc8e3c14242d1af8fe3a120ce653/vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go#L219-L222 
https://github.com/rancher/rancher/blob/94beacf49092cc8e3c14242d1af8fe3a120ce653/vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go#L274
I think UI can patch this.

**Comment by n313893254** [comment]
@loganhz on `master` branch, it had defined `dockerBridgeCidr `.

https://github.com/rancher/ui/blob/d7961211cffc6d00b11a627c8a2636223dcc5389/lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs#L316-L334

I think it had solved.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/7/19)
Validated UI. Validated azureKubernetesServiceConfig for AKS provider. To test you need to pick "Advanced" radio button under Networking in Nodes section.
dnsServiceIP, dockerBridgerCidr, networkPolicy, podCidr, serviceCidr, subnet, etc were all validated. The UI will also warn you if you attempt to overlap virtualnetwork CIDR (subnet) and docker bridge address (dockerBridgerCidr)
![image](https://user-images.githubusercontent.com/45179589/52438713-25155100-2ad7-11e9-84d2-f00f673d2037.png)

Screenshot of this area:
![image](https://user-images.githubusercontent.com/45179589/52438638-fe571a80-2ad6-11e9-9769-4e8f720871a3.png)

HTTP/API were validated.
