### ISSUE TITLE
Socket should send events from that moment forward.

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#14946]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.x

When the UI socket connects it gets the history of all events. In projects with a lot of pods, or other objects the events fill the buffer and the user gets a "backed up reader" error. When looking at the frames coming over on the socket, we see that events are coming for everything in the project. When a user has 3-4k pods this overwhelms the ui. If the UI is able to render, it continuously tries to open a new socket and fails.

**Comment by deniseschannon** [comment]
Please reopen if we see this again. There have been fixes across that @vincent99 thinks might have fixed this/
