### ISSUE TITLE
Traceback when starting agent

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#1494]
Getting the following when attempting to start v0.7.9 of the agent. I'm more or less following the quick-start guide. I've spun up a VM in RancherOS, forwarded port 8080 into the VM and have used a number of IP addresses to spin up the agent. So far I've tried 10.0.2.15, 192.168.59.103, 172.17.0.2... I've confirmed before runs that I can ping and curl the API endpoints on those IPs, and furthermore, the agent seems to also indicate that it can access the API. The guest is RancherOS 0.33. Here's what I get:

INFO: Running Agent Registration Process, CATTLE_URL=http://10.0.2.15:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.7.0
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.7.0
INFO: docker version: Server API version: 1.19
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): 851c91a
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 6
INFO: docker info: Images: 51
INFO: docker info: Storage Driver: overlay
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.19.8-ckt1-rancher
INFO: docker info: Operating System: <unknown>
INFO: docker info: CPUs: 1
INFO: docker info: Total Memory: 999.5 MiB
INFO: docker info: Name: rancher
INFO: docker info: ID: S5RS:MFG3:NAES:QUQD:V42O:CR76:RYVP:LM6E:T4GS:E5XB:Z3H4:Z2
HQ
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://10.0.2.15:8080/v1
INFO: http://10.0.2.15:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 34, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 604, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 623, in _from_env

    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 309, in _load_sch
emas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 258, in _get_resp
onse
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477,
in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465,
in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573,
in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415,
in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connect
ion timed out'))

My only deviation from the quick-start that I'm aware of is my use of localhost, but I think I'm using the correct IP from the agent, and it does seem like the agent finds the server. It would be helpful here to know which connection is failing rather than getting a cryptic error just after the agent says that the endpoint is accessible.

Thanks.

**Comment by deniseschannon** [comment]
When changing the different IPs of how to connect the agent, you'll need to make sure the host registration (an option that was selected when you first clicked "Add Host") is set to the same IP. If you need to change the host registration, you can find the option by clicking on the upper right icon and it's listed under "Administration". 

In your case, you will need to set the host registration to `10.0.2.15:8080` and get a new command on how to add the host. I was able to reproduce what you had earlier using 127.0.0.1:8080 as my host registration, but when I updated the host registration to `10.0.2.15:8080`, my agent was able to register fine.

If you are using the same RancherOS instance (like localhost) to launch the agent, you'll need to also add the environment variable `-e CATTLE_AGENT_IP=10.0.2.15` so that the correct IP is used for the host. http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#samehost

**Comment by deniseschannon** [comment]
@ndarilek I'm going to close this issue, but if the solution doesn't work, please feel free to reopen.
