### ISSUE TITLE
Ability to set the default for RKE settings

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14948]
Currently, whenever you create a cluster with node pools or a custom cluster, RKE is defaulted to a certain set of settings. We need to introduce the ability to set what the default should be for any cluster. 

Note: Any user could still change the cluster options, but this would allow admins to set their preferences for a RKE clusters and prevent users from accidentally forgetting to change the settings from Rancher's defaults. .

**Comment by alena1108** [comment]
The API is in; UI support is tracked in another ticket.

**Comment by sangeethah** [comment]
@kinarashah , I had the following questions relating to this feature

1. cluster-defaults settings does not have many of the cluster options that is being presented in UI currently other than dockerRootDir, EnableNetworkPolicy. We need to include all these options.

<img width="1227" alt="screen shot 2018-08-27 at 11 49 44 am" src="https://user-images.githubusercontent.com/4266958/44679307-77fac080-a9ef-11e8-9b09-77f4cb7d1a52.png">
 
2. appliedEnableNetworkPolicy, failedSpec, appliedSpec needs to be removed from the cluster-defaults settings.

**Comment by sangeethah** [comment]
Related issue - https://github.com/rancher/rancher/issues/15256

**Comment by alena1108** [comment]
Issue is related to configurable RKE template feature that got moved from 2.1 to 2.2

**Comment by deniseschannon** [comment]
This can be achieved with RKE templates and enforcement to use templates.
