### ISSUE TITLE
Node removing - waiting on foregroundDeletion

### ISSUE THREAD

**Issue by msztorc** [rancher/rancher#14944]
Initially, node stuck during deleting - finally DO droplet was deleted after trying to power cycle in DigitalOcean GUI, but now node stuck in Rancher on status: waiting on foregroundDeletion. 

"state": "removing",
"transitioning": "error",
"transitioningMessage": "waiting on foregroundDeletion",

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/11991

**Comment by msztorc** [comment]
node was purged after Rancher restarted
