### ISSUE TITLE
Rancher Custom build binary 

### ISSUE THREAD

**Issue by itssivashankar** [rancher/rancher#14954]
Hi,
I cloned the rancher source code from **https://github.com/rancher/rancher/** 
using make command in source directory, I have build rancher successfully and obtained binaries 
1)Rancher 
2)Agent
while executing Rancher binary in path **../bin/rancher**  it shows error like,

2018-08-04 16:37:26.131221 I | mvcc: store.index: compact 15993
2018-08-04 16:37:26.132963 I | mvcc: finished scheduled compaction at 15993 (took 1.117614ms)
2018-08-04 16:42:26.186752 I | mvcc: store.index: compact 16322
2018-08-04 16:42:26.188669 I | mvcc: finished scheduled compaction at 16322 (took 1.181088ms)
2018/08/04 16:42:52 [ERROR] NodeDriverController **digitalocean** [node-driver-controller] failed with : Driver "digitalocean" not found. Do you have the plugin binary accessible in your PATH?
2018/08/04 16:42:52 [ERROR] NodeDriverController **amazonec2** [node-driver-controller] failed with : Driver "amazonec2" not found. Do you have the plugin binary accessible in your PATH?
2018/08/04 16:42:52 [ERROR] **NodeDriverController** azure [node-driver-controller] failed with : Driver "azure" not found. Do you have the plugin binary accessible in your PATH?

please tell me what is the reason for those error appeared above????

**Comment by StrongMonkey** [comment]
@itssivashankar you need `docker-machine` on the PATH. Go to the dockerfile and fetch all the necessary binary on your PATH before running it.
