### ISSUE TITLE
Pause Orchestration invalid

### ISSUE THREAD

**Issue by yl-yue** [rancher/rancher#14953]
*Describe your issue here*

As if the container were stopped running in 1.6.
Only services can be deleted in 2.0.
Pause Orchestration invalid.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.5` UI: `v2.0.60` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by vincent99** [comment]
#14935
