### ISSUE TITLE
etcd certificate can't be retrieved when using self signed certificates

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14965]
**Rancher versions:**
rancher/server: v1.6.20

etcd containers try to get the certificate from the API (`CATTLE_URL`) but fails to do so when `CATTLE_URL` is pointing to an endpoint with a self signed certificate. The container does not run `update-rancher-ssl` to add the mounted certificate to the OS store.

**Comment by galal-hussein** [comment]
rancher/server: v1.6.20 with latest catalog
etcd image: rancher/etcd:v2.3.7-17

etcd started correctly without any problems, also i was able to test upgrade scenarios from previous versions to the latest
