### ISSUE TITLE
Don't drop catalog app parameters that are not in questions.yml

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14964]
Version: master 8/6

When app parameters are not present in `questions.yml`, they are dropped on submit and never get applied. In this way, we need to add all possible options to the `questions.yml` and update it every time. Better way is to allow parameters that are not in `questions.yml`

**Comment by tfiduccia** [comment]
@superseb - Can you verify this please, or send/tell which catalog app I can use?

**Comment by superseb** [comment]
Ran the case mentioned in https://github.com/rancher/charts/issues/22. 

1. Install EFK catalog app
1. Add `fluent-bit.metrics.enabled: 'true'` to the YAML

In v2.0.8: no additional service for metrics is deployed
In master: additional service for metrics is deployed
