### ISSUE TITLE
Add tolerations to fluentd and log aggregator DaemonSets

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14963]
Version: master 8/6

Fluentd and log-aggregator don't get scheduled to etcd and controlplane nodes due to missing tolerations.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc1

`fluentd` and `log-aggregator` pods have tolerations set correctly, and are scheduled on etcd and controlplane nodes:

```
Tolerations:     node-role.kubernetes.io/controlplane=true:NoSchedule
                 node-role.kubernetes.io/etcd=true:NoExecute
                 node-role.kubernetes.io/master:NoSchedule
```
