### ISSUE TITLE
EKS - Allow for custom Role ARN, VPC, Subnets, and Security Groups

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#14969]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6

For Rancher 2.0 to work for our enterprise we'll need the ability to specify the following on creation of EKS:
- Role ARN
- VPC
- Subnets
- Security Groups

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/14566
