### ISSUE TITLE
Backed up reader needs ability to catch up

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#14978]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.x

When loading a lot of events and the buffer fills, the connection is dropped. If a subscriber then tries to reload, they end up in a loop  trying to load events that will never complete and overloads the server. The reader needs an opportunity to catch up on the events before dropping the connection.

This is most commonly seen in scenarios described: #14946 where the UI subscribes to event streams that overfill the buffer when a lot of resources are within a project(ie. 3500 pods or so) and the UI will try and create new socket connections almost every second trying to the stream.

A partial fix is to allow some window for the buffer to catch up on events. This would allow the UI to keep the same socket and load a large number of events. A more complete solution would be to address the event windowing in 14946.

**Comment by cjellick** [comment]
The end-user summary is that this is a performance enhancement but not a full fix for loading a lot of pods (or other resources) at once. @cloudnautique was hitting a wall where the UI would fail to load at around 3500 pods.
@cloudnautique has tested the fix premerge. @soumyalj I don't think we need additional functional testing for this beyond that. Just a simple verification that UI continues to load and the changes continue to be streamed.

**Comment by soumyalj** [comment]
Tested with v2.0.7-rc1. Created 7000 pods on a setup with 100 hosts. The UI was a little slow beyond 5000 pods but no UI crashes.
