### ISSUE TITLE
can't create internal lb in aks

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#14970]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.6

**Steps to Reproduce:**
1. have an AKS cluster provisioned within rancher
2. deploy a workload with type l4 lb
3. add annotation `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`

**Results:**
The lb created gets an external ip address. If I were to create the same via service definition found [here](https://docs.microsoft.com/en-us/azure/aks/internal-lb) it works

**Comment by alena1108** [comment]
@aemneina annotations that are set on the workload, are getting applied to the workload, not to the LB service that we create based on ports information. The LB service created via workload is minimalistic, and we want to keep it this way. We are planning to add support for more elaborate LB service parameters by letting user create LB service in the UI explicitly, via Services tab. We are going to keep track of this in https://github.com/rancher/rancher/issues/15070
