### ISSUE TITLE
Identity Api /  Auth Configuration Api

### ISSUE THREAD

**Issue by hibooboo2** [rancher/rancher#1497]
We need a way to manage the different Authorization Provider Integrations in an abstract way. The Identity Api will provide a way to verify that an Identity Exists in the Scope of the currently configured AuthConfiguration(s). Here is the initial design: 

2 Endpoints:

* **/v1/identity**
    * Query for an Identity **GET** {?query=String}
        * Returns A list of identities (Can be empty. Should never return  404.) 
        * **name=** exact matches on login name only. **all=** general search
    * Check Identity **ExternalID** {identity}
        * Returns 200 if the identity is valid 404 otherwise

* **/v1/authconfig**
    * This is where you manage authorization providers
    * Can perform CRUD on the AuthConfig

* **/v1/token** 
    * **identities** *Array of identities for this token.*
    * **accountId** *Account id for user the token goes with.*
    * **user** *identity for the user this token goes with.*

Resource Types:
* **identity** *Used as members of the site or a project.*
    * **ID** *Unique identifier for this identity*
    * **NAME** *Name for this identity meant for users to see.*
    * **KIND** *Identity Type Used to differentiate between any type. EX: a Ldap user vs a Github Org*
    * **IDENTITYPICTURE** *Link to a picture representing this identity if one exists.*

* **{Any Authorization IntegrationType}**
    * **FIELDS** *Any number of fields that are specific the the configuration of this Authorization type.*
    * **ENABLED** *Indicating If this Authorization Method is in use or not.*

* **AuthConfig**
    * **ENABLED** *Determines if Authorization is on or off.*
    * **FIELDS** *Field for each Authorization IntegrationType that exists*
    * **PROVIDER** *Currently Enabled Provider*

* **projectMember** *Resource unchanged*
    * **role** *Role of this member*
    * **ExternalId** *Externalid from an identity*
    * **ExternalIdType** *Kind from the identity used for the ExternalId*

**Comment by ibuildthecloud** [comment]
Why is project member changed?  You need to make sure this is backwards compatible and you can upgrade.

**Comment by hibooboo2** [comment]
Because other wise duplicating logic.

**Comment by ibuildthecloud** [comment]
In 5 words or less...

**Comment by ibuildthecloud** [comment]
Just give serious consideration to the fact that you need to support upgrade w/o a data migration.

**Comment by hibooboo2** [comment]
Not until ga i thought that is why i want to make this change now to make it easier to manage the api.

**Comment by hibooboo2** [comment]
Better Api For Ga.

**Comment by ibuildthecloud** [comment]
No, I'm telling you we need to support it now.  We aren't supporting API compatibility but we are supporting upgrades.  But if the upgrade means read data, change data, write back in new format.  That is not good.  That is extremely error prone and a testing nightmare.

So I'm telling you you have to support upgrades so be careful about your data structures.  I don't understand why existing project APIs need to change.

**Comment by hibooboo2** [comment]
Hmm Ill Look Into It. Relax.

**Comment by hibooboo2** [comment]
identity is phantom proxy

**Comment by hibooboo2** [comment]
to member
