### ISSUE TITLE
Auto restart set to never after deploying a Job workload

### ISSUE THREAD

**Issue by dsargent3220** [rancher/rancher#14972]
**Rancher versions:**
rancher/rancher: 2.0.6

**Steps to Reproduce:**
1.  deploy hello-wrld image as a "job"
2.  deploy any other image as a Scalable Deployment

**Results:**
When attempting to deploy the second workload as a Scalable Deployment, the default has changed to "job" which was the last thing we deployed, that's OK, perhaps, not the most productive, but understood.  
The deployment fails with the error:
  Validation failed in API: Deployment.apps "ubuntu" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"

The "Auto Restart" value is set to Never, the value that "Job" set it to, and switching the "Workload Type" back to Scalable deployment does not set "Auto Restart" back to "Always"

**Expected Behavior**
I would expect that changing the selection in "Workload Type"  would also change the value of "Auto Restart" to the appropriate value.

**Comment by dsargent3220** [comment]
I checked this in 2.0.7 and it appears to be fixed to me.

**Comment by deniseschannon** [comment]
Thanks for the update @dsargent3220!
