### ISSUE TITLE
Nodes templates access 

### ISSUE THREAD

**Issue by sorinjulean** [rancher/rancher#14984]
*Nodes templates can't be viewed / modified / used by other users*

Although users have administrator access can't view / modify / use templates created by other users.
Also a user with role having Node Template list, get, and watch access can't  view / modify / use templates created by other users

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.3` and `v2.0.6` |
|Access|`` `admin`|

**Comment by martcastaldo** [comment]
I have the same issue, Administrators should have like 'god' access to view everything within any cluster within the Rancher sphere. I tried to create a role with Node Template list, get, and watch access doesnt make a difference

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/12186
