### ISSUE TITLE
Support OAuth2/ODIC Login Providers

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#14989]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6

I believe it would be great benefit to start supporting OAuth2 preferably with OIDC Connect standard. This would allow for a far greater range of authentication providers to be use, including but not limited to Okta, OneLogin, Auth0, and there are several OpenSource projects that implement OAuth2/OIDC Connect that could also be used, ie Hyda, Keycloak, AnvilConnect.

Thanks!

**Comment by ekristen** [comment]
I've implemented OAuth2 and OIDC Connect multiple times, if you need additional information to make this a reality, I'll gladly help.

**Comment by lukasmrtvy** [comment]
Maybe would be enough to implement support for https://github.com/dexidp/dex

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/10053
