### ISSUE TITLE
If run only one pods on specific node, reboot will cause something

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#14985]
IF create a workload with this config, and only deploy one pod, use the hostport .
<img width="611" alt="image" src="https://user-images.githubusercontent.com/11401602/43773373-1b34351a-9a78-11e8-8024-2cc7d0297aa3.png">
When recreate the pod, it will persist start more and more pods until someone start success. 
<img width="281" alt="image" src="https://user-images.githubusercontent.com/11401602/43773323-f3099292-9a77-11e8-93d3-26da5c849014.png">

and the system won't clean the failed pods . 

Type deployment and deamonset have the same problem.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`` `admin`|
|Route|`containers.run`|

**Comment by xrain0610** [comment]
Type deployment and deamonset have the same problem.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/43814273-19742b8e-9afc-11e8-9262-aa5589c5b052.png)

Please select `stop old pods, then start new` in upgrade policy section as you are using hostPort.

K8s doesn't clean it up. You can find some script to remove the failed pod.

We will support bulk delete in worklaod detail page. So you can select all and remove the failed pod in one go from the UI

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
