### ISSUE TITLE
Unable to deploy a custom app via Rancher catalog

### ISSUE THREAD

**Issue by hrishipx** [rancher/rancher#14983]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/rancher
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.10.x

**Docker version: (`docker version`,`docker info` preferred)**
17.06 ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 

**Steps to Reproduce:**

I added a catalog app via the Rancher GUI . 
https://github.com/infracloudio/helm. 
This has the `questions.yml` and the `app-readme.md` as required in the documentation as well. 
Verified that the keys in the `questions.yml` match those in the `values.yaml`

This is the condition that fails. the `if empty (.kvdb)` never evaluates to `false` although i have the `kvdb` value set via the GUI / rancher cli app --set command
```
            {{- if empty (.kvdb) -}}
                {{- if eq $internalKVDB false -}}
                  "{{ required "A valid ETCD url in the format etcd:http://<your-etcd-endpoint> is required. Verify that the key is correct and there isnt any typo in specifying that, also ensure it is accessible from all node of your kubernetes cluster" .kvdb }}"
                {{- end -}}
              {{- else -}}
              "-k", 
              "{{ regexReplaceAllLiteral "(;)" .kvdb "," }}",                  
              {{- end -}}
```

My catalog installation fails when i use the GUI or the rancher cli with a specific condtion, but this passes when i use regular `helm install` and pass it the `values.yaml` to deploy on the created cluster via rancher. 

**Results:**

**Comment by deniseschannon** [comment]
What version of Rancher was tested using this?

**Comment by StrongMonkey** [comment]
@hrishipx Do other variables get rendered? What does your answer in rancher api look like?

**Comment by hrishipx** [comment]
The Rancher server version was

**Comment by StrongMonkey** [comment]
@hrishipx Would you be willing to try rancher v2.0.8 to see if that helps? From rancher v2.0.7 we bumped helm version from v2.8.0 to v2.9.1.

**Comment by harsh-px** [comment]
@hrishipx We can close this issue as this has been verified as working on 2.0.8.

**Comment by deniseschannon** [comment]
Thanks for the update @harsh-px!
