### ISSUE TITLE
Error creating ssl connection: LDAP Result Code 200 "": x509: certificate signed by unknown authority" while implementing AD authentication using TLS.

### ISSUE THREAD

**Issue by manwanth** [rancher/rancher#14988]
**Rancher versions:**
rancher/server or rancher/rancher: v.1.6.18
rancher/agent or rancher/rancher-agent: 

**Infrastructure Stack versions:**
healthcheck: v0.3.6
ipsec: v.0.2.4
network-services: v.0.2.9
scheduler: v1.10.3-rancher1-1
kubernetes (if applicable): v1.10

**Docker version: (`docker version`,`docker info` preferred)**  17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** : 3.10.0-862.9.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** : VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** :  external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** : Kubernetes

**Steps to Reproduce:** 
Rancher server started with AD CA certiface and certificate added successfully into keystore. But getting below error while configuring AD authentication using TLS.

**Results:**
Error creating ssl connection: LDAP Result Code 200 "": x509: certificate signed by unknown authority

**Comment by massimo-cannavo** [comment]
This is a certificate issue and you need to mount the cert inside of the **rancher/server** container.

```
root@massimo-1-6:~/tools/rancher# docker container ls | grep rancher/server
3d4d6eff6706        rancher/server:v1.6.18            "/usr/bin/entry /u..."   36 minutes ago      Up 36 minutes       3306/tcp, 0.0.0.0:8080->8080/tcp   rancher_rancher-server_1
```

In my case it's **rancher_rancher-server_1**

```
root@massimo-1-6:~/tools/rancher# docker container exec \
  --interactive --tty rancher_rancher-server_1 bash
```

Okay now that you are in the container, we need to import the cert. This is done using the
**update-ca-certificates** tool.

```
root@3d4d6eff6706:/# cd /usr/local/share/ca-certificates/
root@3d4d6eff6706:/# vi ad-ca.crt
~
~
~
root@3d4d6eff6706:/usr/local/share/ca-certificates# update-ca-certificates
Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
```

After that you should be good to go.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
