### ISSUE TITLE
RancherCLI hangs when services have circular links

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1498]
If I have a compose template with:

app1:
   ...
   links:
     - app2

app2:
   ...
   links:
     - app1

This will hang.

**Comment by deniseschannon** [comment]
Verified Fixed with Master Build 752bc89

**Comment by djmaze** [comment]
So what does this mean? Does Rancher support circular links now? 

I am curious because Docker does not support this with links (yet).

**Comment by deniseschannon** [comment]
yes, rancher-compose supports circular links.
