### ISSUE TITLE
System namespaces not listed under "System" project post upgrade

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14995]
**Rancher versions:**
v2.0.7-rc2

**Steps to Reproduce:**
Create a 2.0.6 rancher server
Create a new cluster on 2.0.6
Upgrade server from 2.0.6 -> 2.0.7-rc2

**Results:**

Associated system namespaces are not added to system project post upgrade.

<img width="1664" alt="screen shot 2018-08-07 at 4 30 57 pm" src="https://user-images.githubusercontent.com/38012481/43807906-53fa2a94-9a5f-11e8-9db9-c3188d81e0f6.png">

**Comment by soumyalj** [comment]
The same was observed in my setups too for both DO and AWS clusters

**Comment by kinarashah** [comment]
@soumyalj Yes, I'm able to reproduce it, and I'm trying to understand how was it working before.

**Comment by adingilloRancher** [comment]
v2.0.7.-rc3

System namespaces are now seen under system project post upgrade.
