### ISSUE TITLE
Fluentd custom configmap gets overwritten

### ISSUE THREAD

**Issue by ts-mini** [rancher/rancher#14999]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.0.6
**Docker version: (`docker version`,`docker info` preferred)**
Containers: 15
 Running: 13
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1061-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69 GiB
Name: control-12.production.internalspectrumcluster.com
ID: ITIB:JDZW:F3VS:HWME:MY4Y:6AOR:5XPH:QUYM:V2TT:YM24:SKF7:TCEP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

Scenario:
I've got custom project logging turned on, pointing to an elasticsearch cluster.  The elasticsearch cluster is seeing my json log as a string, not an object. This is due to the fluentd config.  Applying this block lets fluentd see it as an object, and thus elasticsearch will properly index it.

The important bit:
```
<filter c-v498n:p-2vcqh.var.log.containers.workers**>\n  @type parser \n  format json\n  key_name log \n  reserve_data true \n</filter>
```
The whole configmap
```
apiVersion: v1
data:
  project.conf: "\n<source>\n   @type  tail\n   path  /var/log/containers/*.log\n
    \  pos_file  /fluentd/log/fluentd-project-c-v498n:p-2vcqh-logging.pos\n   time_format
    \ %Y-%m-%dT%H:%M:%S\n   tag  c-v498n:p-2vcqh.*\n   format  json\n   read_from_head
    \ true\n</source>\n\n<filter  c-v498n:p-2vcqh.**>\n   @type  kubernetes_metadata\n
    \  merge_json_log  true\n   preserve_json_log  true\n</filter>\n\n<filter c-v498n:p-2vcqh.**>\n
    \ @type record_transformer\n  enable_ruby  true\n  <record>\n    tag ${tag}\n
    \   namespace ${record[\"kubernetes\"][\"namespace_name\"]}\n    projectID c-v498n:p-2vcqh\n
    \ </record>\n</filter>\n\n<filter c-v498n:p-2vcqh.**>\n  @type grep\n  <regexp>\n
    \   key namespace\n    pattern (primer-stg)\n  </regexp>\n</filter>\n\n<filter
    c-v498n:p-2vcqh.**>\n  @type record_transformer\n  remove_keys namespace\n</filter>\n<filter c-v498n:p-2vcqh.var.log.containers.workers**>\n  @type parser \n  format json\n  key_name log \n  reserve_data true \n</filter>\n\n<match
    \ c-v498n:p-2vcqh.** project-custom.c-v498n:p-2vcqh.**> \n    \n    @type elasticsearch\n
    \   include_tag_key  true\n    hosts https://search-stg-cluster-es-kxjubiuqj3tyecuki7g6iiecfq.us-west-2.es.amazonaws.com:443
    \   \n    logstash_prefix \"saas-stg-stg\"\n    logstash_format true\n    logstash_dateformat
    \ %Y-%m-%d\n    type_name  \"container_log\"\n\n    \n    ssl_verify false\n\n
    \   \n    \n    <buffer>\n      @type file\n      path /fluentd/etc/buffer/project.c-v498n_p-2vcqh.buffer\n
    \     flush_interval 5s\n      </buffer> \n\n    disable_retry_limit\n    num_threads
    8\n    slow_flush_log_threshold 40.0\n</match>\n"
kind: ConfigMap
metadata:
  labels:
    logging-level: project
  name: project-logging
  namespace: cattle-logging
```
When I apply the aforementioned config, it works for a while, but it seems like at midnight - a default configmap is applied overwriting my changes.

**Comment by ts-mini** [comment]
The goal for me here is to not reinvent the wheel, and utilize the solid underpinning of the fluentd config - just adding my own custom block where I need to (and have it persist).  Am I missing something? Or is this not a feature yet.  Thx

**Comment by aiwantaozi** [comment]
@ts-mini Thanks, this isn't a bug, it will reconcile in an interval, reconcile the make current state to the desired state. We will consider the feature let you input your fluentd config. Thank you so much.

**Comment by aiwantaozi** [comment]
The let user could input config is tracked in this issue https://github.com/rancher/rancher/issues/15558
