### ISSUE TITLE
Multi-container (aka "pods", "services") upload/deploy from file

### ISSUE THREAD

**Issue by brianclements** [rancher/rancher#15]
I know everything is in early stages, but I figured I'd submit something anyway so that there's a place to discuss this particular topic.

I tend to have apps/stacks that spread out over many containers. I'll have a couple volume containers, one container for my configuration and dynamic run-time content that also is a hub for all my volume containers, and then any number of application containers that `--volumes-from` all the others via my configuration container to share sockets amongst other things. All together they form a "stack" or a "service". Some can be 6-10 containers in number, with webs of shared volumes and links between them. Fig has been my normal method of keeping track of everything so far. It's been very nice to see the entire stack in one file and be able to edit it's deploy from the same location. So far this has been single host, but I feel like you've solved most of the multihost networking issues in Rancher already, and thus being able to deploy services in various host configurations is possible.

Instead of entering single containers one by one, I think it would be nice to use either YAML or JSON files to specify a suite or "pod" of containers and be able to upload it from the web UI all at once. Better still, if you could incorporate fleet-like logic within that file to have certain containers "follow" others or be "global" etc., that would be ideal so that I could do things like have my webapp be on the same host as my database because I like to use unix sockets between them, or have them NOT be on the same host for fault-tolerance etc. Is such a feature planned for Rancher?

My hold up on many docker-based web interfaces (actually, every single one I've tried) is that they require manual entry one-by-one which just does not work for complex container situations. I like the strategy you're taking with Rancher all around, and I think if you can make suites of containers the core element as services, rather then individual containers, you will really get an upper leg on the web-ui docker world (which is really elementary ATM).

Thanks for your work here, I'm enjoying using rancher!

**Comment by albertrdixon** [comment]
Checking in on this thread. It would be nice to be able to save configuration (say: write current state to a fig.yml?) or upload a fig.yml and have it provision.

**Comment by ibuildthecloud** [comment]
@brianclements @albertrdixon Curious for your feedback on this one.  There's two level of support for fig.  The first is that we just take a template and deploy the containers as described.  The second part is that we actually save the fig template and then allow you to continue to do life-cycle operations on the containers like start/stop/delete based on the template.  The second part is more tricky.  What level of support were you looking for?

**Comment by brianclements** [comment]
Sorry I've been MIA, I'll try and get you a good fig.yml for testing as soon as I'm able. 

Regarding your question. I'm trying to think of the differences (in the current fig spec) between life-cycle operations that are fig.yml aware (your second proposition), and not (your first proposition). The only things I can think of are rancher remembering things like ENV vars, volumes, links etc., so you don't have to enter them again, is that correct? So in a fig.yml aware life-cycle usage pattern, I could potentially tell a container to restart itself, and it rancher would know to go to it's saved fig.yml and redo all the volume dependencies, but in a "template" method, I'd have to upload the same file again to get that information in there; does that sound about right?

If my understanding is correct, then I think investing that time upfront to make your second proposition happen is worth it IMHO. That supports the usage pattern that makes most sense to me: I design a stack/group in a fig.yml, and just restart/add/remove containers for various life-cycle needs as I go, but always in the context of what I've setup originally in that entire fig.yml. Perhaps with different env vars, but usually with 95% of the details being the same.

I also think that internally, trying to reconcile an instantiated and running "template" with a new one that you upload could be crazy to try to match up and only get worse in time (is this 10 container stack that's running compatible with the 12 container stack you just uploaded? What are the differences? Must we check every container on every host and guess where they got implemented? which is which?) whereas making changes to one that is already running and accounted for internally seems more robust (in stack with ID ABC123, restarting container A uses the same volumes and options as before, with optionally different ENV vars, we know the host, we know the container; done).

**Comment by albertrdixon** [comment]
Agree w/ @brianclements here. I'm thinking "provisioning template" support would be something along the lines of AWS Cloudformation. (Of course if you all could expand on the fig features that would also be great :) maybe something along the lines of [crane](https://github.com/michaelsauter/crane) with groups and what not)

The other use case I have in mind is: having everything running on rancher server 1, then wanting to migrate to rancher server 2 for whatever reason, so save state and upload on new machine.

**Comment by deniseschannon** [comment]
With the release of `rancher-compose` with Rancher, this is possible today.
