### ISSUE TITLE
TCP public endpoint is not created for workload with an ingress pointing to it for AWS and DO clusters

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15003]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.7-rc2

**Steps to Reproduce:**
1. Create a fresh install 3 node cluster (one role each) with  v2.0.7-rc2
2. Create a nginx workload and ingress pointing to it

The TCP public endpoint is not created for the workload.
The  TCP public endpoint link is not created on the workload (w.r.t the ingress associated)

This worked in rancher v2.0.6
```
publicEndpoints": [ 2 items
{
"addresses": [
"1ade"
],
"allNodes": true,
"ingressId": "default:ingress1",
"nodeId": null,
"path": "/name.html",
"podId": null,
"port": 443,
"protocol": "HTTPS",
"serviceId": "default:ingress-db1873c28fc62dee94bae42cd8dd441c"
},
{
"addresses": [
"1bcd"
],
"allNodes": true,
"ingressId": "default:ingress1",
"nodeId": null,
"path": "/name.html",
"podId": null,
"port": 80,
"protocol": "HTTP",
"serviceId": "default:ingress-db1873c28fc62dee94bae42cd8dd441c"
}
]
```
<img width="1380" alt="screen shot 2018-08-08 at 11 37 24 am" src="https://user-images.githubusercontent.com/18536626/43857198-7512347e-9aff-11e8-8172-5cc850a8784b.png">

**Comment by kinarashah** [comment]
@soumyalj we changed the type of service pointing to ingress as clusterIP and not nodePort anymore. Thus, this looks as expected behavior. 

Related issue - https://github.com/rancher/rancher/issues/13717 
(Also, confirmed with @galal-hussein since he tested it)

**Comment by soumyalj** [comment]
This is as expected and closing.
