### ISSUE TITLE
Workloads not deployed

### ISSUE THREAD

**Issue by Nephelo** [rancher/rancher#15006]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.06

**Docker version: (`docker version`,`docker info` preferred)**
`17.03.2-ce`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`Ubuntu 16.04.5 LTS (Xenial Xerus)``4.4.0-131-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Steps to Reproduce:**
* New Rancher installation with one node on same host as rancher-server
* Deploy workload with one container

**Results:**
* Pod not scheduled
* `Lauch kubectl` only shows black window without promt

**Comment by ekristen** [comment]
What instructions did you follow for the one-node? Does your cluster show healthy?

**Comment by Nephelo** [comment]
Thank you for the fast answer.

I used [this](https://rancher.com/docs/rancher/v2.x/en/installation/single-node-install/) instruction. I started the server using `sudo docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 --name rancher-server -v /mnt/rancher-server:/var/lib/rancher rancher/rancher:stable
` where `/mnt/rancher-server` is a NFS mount. The node was added through the rancher UI.

Yes, the cluster shows healthy. I use a nginx reverse proxy infront of the rancher server with the following configuration

```
upstream rancher {
  server X.X.X.X:8080;
}

server {
  listen 443 ssl http2;

  ssl_certificate     /XXX/fullchain.pem;
  ssl_certificate_key /XXX/privkey.pem;
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers         HIGH:!aNULL:!MD5;
  server_name         rancher.mydomain.com;

  location / {
    proxy_pass http://rancher;

    proxy_set_header X-Forwarded-Host     $host;
    proxy_set_header X-Forwarded-Server   $host;
    proxy_set_header X-Real-IP            $remote_addr;
    proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto    $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Port     $server_port;
    proxy_set_header Host                 $http_host;

    proxy_redirect  off;
    proxy_buffering off;

    proxy_http_version 1.1;
    proxy_set_header Upgrade    $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```

The agent connected to the rancher server through `rancher.mydomain.com`.

**Comment by superseb** [comment]
Is it not scheduled or is it not updating due to the broken websockets? If kubectl also does not work, there is something wrong. What does the browser developer tools show regarding network connections when you open kubectl?

And please use the example NGINX configuration before changing anything to make sure it's not in the configuration: https://rancher.com/docs/rancher/v2.x/en/installation/single-node-install-external-lb/#example-nginx-configuration

**Comment by Nephelo** [comment]
I didn't see any failing request.

Since it was a new installation on a VM, I reinstalled it on a new Debian VM and now it's working. Maybe there was an issue during the setup.
