### ISSUE TITLE
After node addition, the ingress targets cannot be reached using the new node's IP

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15000]
**Rancher versions:**
rancher/server or rancher/rancher: Upgrade from v2.0.6 to v2.0.7-rc2

**Steps to Reproduce:**
1. Create a 3 node(one role on each) DO/AWS cluster in v2.0.6. 
2. Create a workload and an ingress pointing to the workload. Verify that you can reach the ingress targets using the worker node's IP
Ex: wget http://NodeIP/name.html
3. Upgrade from v2.0.6 to v2.0.7-rc2
4. Add another worker node

After adding another worker node, the ingress targets cannot be reached using the new node's IP.
Also, the link on the workloads disappear.

<img width="1568" alt="screen shot 2018-08-08 at 10 27 26 am" src="https://user-images.githubusercontent.com/18536626/43853685-b2665e86-9af5-11e8-8d5a-6479d2bb5c3f.png">

**Comment by kinarashah** [comment]
Unable to reproduce, 

created a 2.0.6 setup with RKE node and existing ingress pointing to workloads. 
upgraded to master. 
added a new worker node. 
used `wget --no-check-certificate https://newnodeip/name.html` 
able to get pods. 

Will try again a few times.

**Comment by kinarashah** [comment]
Issue is with rc2, since flag for canal isn't enabled and we don't create network policy for the new worker node.

Tested with master, works as expected.

**Comment by soumyalj** [comment]
Tested with v2.0.7-rc5 using the same steps. After adding another worker node, the ingress targets could be reached using the new node's IP for DO cluster
For AWS cluster, after adding one of the worker node, it was observed that the CIDR was not programmed in the network policy for that node. Ingress targets could not be reached using that node IP.
Other two nodes were added and it was programmed correctly and ingress was functional
