### ISSUE TITLE
Amazon EBS Storage Class fails to create persistent volume

### ISSUE THREAD

**Issue by quick691fr** [rancher/rancher#15005]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.0.6

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 22
 Running: 12
 Paused: 0
 Stopped: 10
Images: 8
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.32-rancher2
Operating System: RancherOS v1.4.0
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853 GiB
Name: ctrl1
ID: XLHF:F4B4:ACP7:6643:YHMG:YQ3O:IFFA:5B46:MEDG:NQXG:XBGT:R4RT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=amazonec2
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.4.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.0
PRETTY_NAME="RancherOS v1.4.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

4.14.32-rancher2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
1 cluster Bare-metal  and 1 cluster AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
Create a Bare-metal cluster
Create an AWS cluster
Create an Amazon EBS storage class on the AWS Cluster let say name "amazon-ebs"
Go to AWS Cluster workload / volume
Create a new volume with Storage class "amazon-ebs" created previously

**Results:**
Volume is "pending" state and never created in AWS

Here are the logs from the container trying to create the volume :

E0808 19:09:19.255429       1 aws_ebs.go:464] Provision failed: **Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead**
I0808 19:09:19.255553       1 pv_controller.go:1433] failed to provision volume for claim "default/test" with StorageClass "test-ebs": Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead
I0808 19:09:19.255683       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"92607720-9b3b-11e8-9a72-023b6bbc4294", APIVersion:"v1", ResourceVersion:"8771", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "test-ebs": Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead

**Comment by quick691fr** [comment]
I guess the problem come from the dual cluster and storage class is trying to GetCloudProvider on the first cluster which is Bare-metal instead of the one used when created the storage class

**Comment by deniseschannon** [comment]
Did you make sure to enable the Amazon cloud provider when creating the cluster? The cloud provider is required to be enabled in order to use EBS.
