### ISSUE TITLE
rancher: How to deploy Kubernetes YAML files?

### ISSUE THREAD

**Issue by muhlba91** [rancher/rancher#15017]
Hi,

I was looking through the documentation and quite a few examples now but haven't found any information how I can **deploy/import Kubernetes YAML (resource) YAML** files in **Rancher 2**.

What I want to achieve is like with Rancher 1.6 writing those files (in 1.6 it's docker-compose files) and then deploy those files using any **CLI** tool to get them into the cluster/Rancher and, hence, it would be nice having some similar tool like rancher-compose for Rancher 2 and Kubernetes YAML files (or any accessible and documented API endpoint).

Is there any **CLI offered by Rancher** itself or do I have to deploy those files directly in/with Kubernetes and let Rancher pick them up?

Thanks! :)

**Comment by massimo-cannavo** [comment]
**Rancher CLI**

```
root@massimo-server:~# rancher login --token $RANCHER_TOKEN \
  https://massimo.do.rancher.space

INFO[0000] Only 1 project available: Default
INFO[0000] Saving config to /root/.rancher/cli2.json

root@massimo-server:~# rancher kubectl create -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: webapp
      image: massimocannavo/webapp
EOF

pod/webapp created

root@massimo-server:~# rancher ps
NAMESPACE   NAME      TYPE      STATE     IMAGE                   SCALE
default     webapp    Pod       running   massimocannavo/webapp   Standalone
```
The Rancher CLI tool allows you to manage your cluster. You can deploy kubernetes resources or deploy Rancher Catalog Apps. You can download Rancher CLI from the UI by clicking on **Download CLI** at the bottom of the page.

**kubectl**
```
root@massimo-server:~# mkdir -p ~/.kube
root@massimo-server:~# vim ~/.kube/config
~
~
~
root@massimo-server:~# kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
webapp    1/1       Running   0          10m
```
This is the same approach as using Rancher CLI but you are directly using the kubectl binary. The config for kubectl can be fetched by going to Global > Cluster > **Kubeconfig file** You can also launch kubectl from the UI by going to Global > Cluster > **Launch kubectl**.

**Comment by muhlba91** [comment]
Thank you for providing this information and example! Now everything is clear. :)
