### ISSUE TITLE
Hovering over stickiness tab makes it seem like it's click-able

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1501]
v0.27.0-rc3

Steps to Reproduce:
1. Add a load balancer service.
2. Hover over stickiness

Result: Since the stickiness used to be a tab in previous versions, if you hover, it looks as if you can click on it.

Expected Result: Now that there are no tabs, we need to eliminate the ability to hover.

**Comment by vincent99** [comment]
It is still clickable, but there's only one tab now...  I'd change it but it would require a decent amount of change to look right and expect we'll add at least one more tab in the very near future for things like SSL termination.
