### ISSUE TITLE
rancher stuck in update loop with k8s 1.11

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#15018]
Steps to repro:
1. creating a manager cluster running k8s 1.11 and deploy rancher onto it.
2. turn on debug logs so that you can see the continual update via: `docker exec -ti <container_id> loglevel --set debug`
3. add a cluster and wait for it to be active and healthy

Actual
Observe that when you go into the cluster in the UI and navigate through various parts of the cluster-specific menu, the menu disappears. THis is caused by the UI rerendering the menu everytime the cluster has changed
Observe that you continually see in the logs that the cluster is updating

Expected:
No continual updates

**Comment by galal-hussein** [comment]
rancher/rancher:master on rke kubernetes 1.11

i followed steps described by @cjellick and i don't see update logs continuously appearing in the logs when debug log is on
