### ISSUE TITLE
Rancher 2.0.6 cannot add registry due to regex issue

### ISSUE THREAD

**Issue by dgabrysch** [rancher/rancher#15013]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.0.6?

**Steps to Reproduce:**

Adding this here: 

![image](https://user-images.githubusercontent.com/20701762/43882463-03a3c382-9bb0-11e8-835a-eac86a76713b.png)

**Results:**
As seen in picture.

Isn't that a normal DNS entry? Am I missing something here?

**Comment by vincent99** [comment]
This should be fixed for 2.0.7 already, but the error is with the name field, not the address.  It has to be all lowercase.

(The UI normally does that for you but isn't because the type of the fields in the API was changed to one it doesn't recognize.)

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/27
Verified fixed
