### ISSUE TITLE
SIEMonster issue. Container running but it is in error state.

### ISSUE THREAD

**Issue by LalithMinfy** [rancher/rancher#15015]
*Describe your issue here*

    Hi,

     I am facing the issue with SIEMonster installtion.please find the below error and please help me to fix this issue.

siemonster (Container should have been running but is in error state. Check logs for more information.: ImageActivate: failed to activate image) 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.21` Cattle: `v0.183.60` UI: `v1.6.45` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by superseb** [comment]
SIEMonster creates a product based on Rancher, we can't help with SIEMonster issues here. Check SIEMonster docs here: https://kb.siemonster.com/help.

If you have trouble running a stack/service on Rancher itself, please share what you are trying to launch and we can take a look.

**Comment by LalithMinfy** [comment]
I am trying to implement SIEMonster tool with 5 nodes. First i have launched Rancher instance and i have added remaining four instances into rancher server. But stack is not able to activating all docker containers. Due to this issue , I we are unable to complete this installation.Please help me.

**Comment by shishir2019** [comment]
Hi SuperSeb,

**Comment by shishir2019** [comment]
I am not sure if i can re-open this issue. But i am facing the issue deploying stack in rancher. See below details. Hope you can help:

**Comment by shishir2019** [comment]
Rancher Version:
v1.6.17

CoreOS Version:
4.19.25-coreos

Application Stack:
Siemonster V3

Hosts:
makara, capricorn, proteus, kraken, tiamat

Issue:
When deploying Siemonster V3 Stack in Rancher, below services have error activating:

es-data-node1 + 1 Sidekick (Failed to allocate instance [container:1i10855]: Bad instance [container:1i10855] in state [error]: Allocation failed: Host must satisfy resource constraints: [instanceReservation: 1]. needs host with label kraken: 1, needs host with label kraken: 1)

es-data-node2 + 1 Sidekick (Failed to allocate instance [container:1i10857]: Bad instance [container:1i10857] in state [error]: Allocation failed: Host must satisfy resource constraints: [instanceReservation: 1]. needs host with label tiamat: 1, needs host with label tiamat: 1)

logstash-collector (Failed to allocate instance [container:1i10860]: Bad instance [container:1i10860] in state [error]: Allocation failed: Host must satisfy resource constraints: [1516:1516/tcp, 1516:1516/udp, 3520:3520/tcp, 3521:3521/tcp, 3522:3522/tcp, 3524:3524/tcp, 3525:3525/tcp, 3526:3526/tcp, 3527:3527/tcp, 3528:3528/tcp portReservation]. needs host with label proteus: 1)

logstash-indexer-exporter (Failed to allocate instance [container:1i10861]: Bad instance [container:1i10861] in state [error]: Allocation failed: needs host with label capricorn: 1)
