### ISSUE TITLE
ConfigMap/Secret a key with empty value is automatically removed

### ISSUE THREAD

**Issue by chanjarster** [rancher/rancher#15010]
**Rancher version：2.0.6**

I tried to change mtu in ConfigMap `namepace: kube-system, name: canal-config` and then deleted Pods in Workload `namespace: kube-system, name: canal` to make it restart. 

And then, container `kube-flannel` in pod `canal-*` reported a error: `Couldn't find key canal_iface in ConfigMap kube-system/canal-config`

The problem cause by Rancher automatically removed key which has an empty value, and in this case the key is `canal_iface`.

The RKE [canal config map template](https://github.com/rancher/rke/blob/master/templates/canal.go#L158) generate key `canal_iface` with an empty value by default, so when I change this ConfigMap and save it, it will lost.

I think a a key with empty value in ConfigMap or Secret should be allowed.

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/ui/pull/2101
It will be in v2.0.7
Thanks for your report!
