### ISSUE TITLE
rancher version filter did not work in the catalog apps

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#15014]
Rancher versions: v2.0.7

Steps to Reproduce:

1. Add a custom catalog with a chart that contains `rancher_version: v2.0.8` in its questions.yml file
2. Go to `Catalog Apps` page and filter the app by name
3. The app which contains the `rancher_version: v2.0.7` is still showing up

Results: The app with  `rancher_version: v2.0.8` is not expected to show up.

**Comment by StrongMonkey** [comment]
`RancherVersion` is only a thing for templateVersion. And for filter, try to remove `category_ne` filter and apply again.

**Comment by guangbochen** [comment]
In Rancher 1.6.x, the catalog apps are filtered by the back-end using `. minimum_rancher_version` instead of front-end @vincent99.

So I think we need to add version filtering in Rancher 2.0 ASAP, @deniseschannon @StrongMonkey, e.g. `Kubernetes dashboard` will only show up in 2.0.7 as it requires to use `System Project` .

**Comment by alena1108** [comment]
That sounds like the missing feature, not a bug

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/18469
