### ISSUE TITLE
Ability to Enable Ingress SSL Without a Certificate

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#15021]
When adding/editing an Ingress on a Rancher 2.0 K8s cluster, the Rancher UI currently requires an SSL/TLS Certificate be specified in order to enable TLS termination of the ingress being created. The Rancher UI should be able to allow you to enable TLS termination of an ingress without a certificate being specified.

We should be able to enable TLS termination in the Rancher UI without specifying a TLS certificate, which will have the nginx-controller default to using it's default certificate. This can be useful for:
1. Setting a wildcard default certificate to simplify certificate management
2. Having a Layer 7 Load Balancer in front of your workloads that terminates/offloads SSL with your own specified certificate and re-encrypts traffic to the default certificate at the nginx-controller, for example for upstream authentication but requiring SSL during the entire data path

**Comment by dsargent3220** [comment]
This would be awesome.  We  have a wildcard cert on the nginx ingress controller and at this time have to edit the yaml of every ingress controller to enable TLS termination.  This would simplify the process for our developers a ton.

**Comment by dsargent3220** [comment]
Do we know when this might make it into a scheduled release?  This would seriously help our developers and simply our documentation.

**Comment by Oats87** [comment]
Half of the battle (setting the default ingress certificate) can be achieved using RKE: https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/ingress-controllers/#configuring-an-nginx-default-certificate

We are simply looking for a checkbox to enable/disable TLS without having to specify a certificate for each ingress.

**Comment by dsargent3220** [comment]
Alternatively, if a checkbox is too hard (as an interface paradigm) , adding the NGINX cert in the SSL/TLS drop down would also be a good fix.  This would allow the user to select the default cert, in the background the YAML would go from
  tls:
  - hosts:
    - hello.apps.ad.selinc.com
    secretName: c-xg67d

TO
  tls:
  - hosts:
    - hello.apps.ad.selinc.com

**Comment by alena1108** [comment]
@dsargent3220 an alternative option of specifying an nginx certificate may in fact be harder because of a secret's permissions - user deploying ingress might not have an access to a certificate used by ingress controller. We will explore the option of check box in the UI/API to disable passing the secret name

**Comment by alena1108** [comment]
@westlywright in TLS section for ingress, we might: 

* either add one more option to the Certificate drop down list  - "use default ingress controller certificate". When chosen, don't set certificateId in ingressTLS object
* or add a checkbox driving the similar behavior. 

We should also think about displaying a note once the option to use a default certificate is chosen - that it would work only when ingress controller has a default certificate set. In the future, we can add "Ingress has a default certificate set" to the cluster capabilities on the API side, so the UI could be more deterministic, and get rid of that note.

**Comment by Oats87** [comment]
@alena1108 

If there is not a default ingress controller certificate set, the nginx ingress controller actually self-signs one on initialization; thus it should be possible to use the default certificate whether one was actually specified or not. A use case for this would be a re-encrypt at the load balancer, which doesn't necessarily care about the validity of the ingress controller's cert but still needs to be encrypted to the ingress controller.

**Comment by tfiduccia** [comment]
Version - 2.2. master 10/29
Verified fixed
