### ISSUE TITLE
Azure+Rancher: Cloning Rancher-made Azure hosts boots NSG/Route Table/Users off of subnet

### ISSUE THREAD

**Issue by solpon** [rancher/rancher#15025]
rancher/rancher [Cattle Orchestration Environment Template]
rancher version: v1.5.9

**Steps to Reproduce:**
Create an Azure host through rancher GUI.
Clone the previously created host on rancher GUI. (Cloned host uses same Subnet and Subnet Prefix CIDR normally)

**Results:**
The subnet of the Azure VPN you pointed to will have all attachments removed(NSG, Route Table, and Users) which causes all instances in the subnet to lost networking capabilities.
Through Powershell/Azure resources GUI, you have to manually attach the removed elements back to the subnet to resume processing normally.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
