### ISSUE TITLE
LB agent keeps restarting.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1502]
Server version - Build from master - Jul 8

When executing LB service related test cases, 1 of the LB agents keeps restarting.

docker inspect shows that it is missing CATTLE_AGENT_INSTANCE_AUTH env variable

```
    "Config": {
        "Hostname": "b670c9fc3f1b",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {},
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "CATTLE_CONFIG_URL=http://latest.rancher.io/v1",
            "HOME=/",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/etc/init.d/agent-instance-startup",
            "init"
        ],
        "Image": "rancher/agent-instance:v0.3.1",
        "Volumes": {},
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "02:89:26:da:3b:d2",
        "OnBuild": null,
        "Labels": {
            "io.rancher.container.ip": "10.42.72.178/16",
            "io.rancher.container.system": "LoadBalancerAgent",
            "io.rancher.container.uuid": "39bae6c1-0d16-4643-8054-35908aabcf51",
            "io.rancher.project.name": "test911026",
            "io.rancher.project_service.name": "test911026/LB-test749321/io.rancher.service.primary.launch.config",
            "io.rancher.scheduler.affinity:container_label_soft": "io.rancher.service.deployment.unit=11fb2258-c69c-4ad3-bfca-47f48aa2cb10",
            "io.rancher.service.deployment.unit": "11fb2258-c69c-4ad3-bfca-47f48aa2cb10",
            "io.rancher.service.launch.config": "io.rancher.service.primary.launch.config",
            "io.rancher.stack.name": "test911026",
            "io.rancher.stack_service.name": "test911026/LB-test749321/io.rancher.service.primary.launch.config"
        }
    }
 ```

**Comment by alena1108** [comment]
Comment from @ibuildthecloud on the issue:

There is the container http://latest.rancher.io/v1/projects/1a5/containers/1i13361 that got created in test that is a LB Agent but there is no CATTLE_AGENT_INSTANCE_AUTH set in the environment variables of the container (not you won't see that in cattle, but only docker inspect)

ibuildthecloud [10:46 AM]
so the lb agent is just constantly restarting

**Comment by sangeethah** [comment]
This issue is again seen when running automation runs . I see 2 LB instances from different services which keep restarting:

docker inspect shows missing CATTLE_AGENT_INSTANCE_AUTH env variable

        "Env": [
            "CATTLE_CONFIG_URL=http://latest.rancher.io/v1",
            "HOME=/",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],

**Comment by sangeethah** [comment]
This issue has not been encountered when running validation tests for sometime now. Closing this issue.
