### ISSUE TITLE
NetworkPolicies are not deleted when Namespace is removed from Project

### ISSUE THREAD

**Issue by chanjarster** [rancher/rancher#15029]
**Rancher versions:**
rancher/server or rancher/rancher: latest
rancher/agent or rancher/rancher-agent: v2.0.6

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Steps to Reproduce:**
1. create a namespace: `kubectl create namespace np-test`
1. Open Rancher web ui and move namespace `np-test` to a Project
1. found NetworkPolicies are created for `np-test`: `kubectl -n np-test get networkpolicy`
   ```
   NAME         POD-SELECTOR   AGE
   hn-nodes     <none>         45m
   np-default   <none>         45m
   ```
1. Open Rancher web ui and move namespace `np-test` to **None**

**Results:**

NetworkPolicies still exists: `kubectl -n np-test get networkpolicy`
```
NAME         POD-SELECTOR   AGE
hn-nodes     <none>         45m
np-default   <none>         45m
```

**Comment by sangeethah** [comment]
Tested with latest build from master.

1. Create a cluster with "Project Network Isolation" enabled.
2. Create a namespace : kubectl create namespace test1
3. Open Rancher web ui and move namespace test1 to a Project
NetworkPolicies get created for this namespace.
4. Open Rancher web ui and move namespace test1 to None.
NetworkPolicies get deleted from the namespace as expected.
