### ISSUE TITLE
docker 18.03.0-ce 无法接入Kubernetes

### ISSUE THREAD

**Issue by wenchongyang** [rancher/rancher#15028]
*Describe your issue here*

主要问题：docker 18.03.0-ce 无法接入Kubernetes
操作步骤：1、添加docker ce主机 ，在主机列表能显示该主机，但是无法接入Kubernetes，在cli和Kubernetes节点都无法查找该主机。
错误日志：
1、rancher-agent：2018/8/10 上午8:53:21time="2018-08-10T00:53:21Z" level=error msg="Error processing event" err="Error response from daemon: invalid mount config: must use either propagation mode \"rslave\" or \"rshared\" when mount source is within the daemon root, daemon root: \"/var/lib/docker\", bind mount source: \"/var/lib/docker\", propagation: \"rprivate\"" eventId=82d860c6-97d3-4fdb-85e2-ea3f173deb99 eventName=compute.instance.activate resourceId=1ihm1774
2、 kubernetes-proxy-5 ：Try `iptables-restore -h' or 'iptables-restore --help' for more information.
3、  Error (Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate")

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.20` Cattle: `v0.183.60` UI: `v1.6.45` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`container.ports`|

**Comment by superseb** [comment]
Docker 18.03 is not a supported version for running Kubernetes, see release notes (https://github.com/rancher/rancher/releases/tag/v1.6.20):

```
Note: Kubernetes 1.11/1.10/1.9/1.8 supports Docker 1.12.6, 1.13.1 and 17.03.2.
```
