### ISSUE TITLE
Add Bitbucket support as an option in the Pipeline tool feature

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#15023]
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`` `admin`|
|Route|`authenticated.cluster.pipeline.settings`|

**Comment by dxxxxxg** [comment]
![image](https://user-images.githubusercontent.com/5438983/43913574-4068c86c-9bba-11e8-9048-8e6a803f9528.png)

**Comment by dsargent3220** [comment]
We would also very much like this.  Please make sure it works with BitBucket server hosted on prem.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/12625
