### ISSUE TITLE
Unsupported docker version / Rancher 1.6.21 / Docker 18.06.0-ce

### ISSUE THREAD

**Issue by Pea13** [rancher/rancher#15032]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.21
rancher/agent or rancher/rancher-agent: 1.2.11

**Infrastructure Stack versions:**
healthcheck: 0.3.8
ipsec:0.2.5
network-services:0.2.10
scheduler: 0.8.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 35
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.654GiB
Name: dev01
ID: RP4X:DMNP:BS4O:QR5X:LGZ7:IBHW:ZG5U:P6W7:4MAJ:YTTU:VVMW:IXPA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
4.9.0-7-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OVH VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher / external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Upgrade docker to the latest version (18.06.0-ce)

**Results:**
Rancher tells me :  Untested Docker version
But in the release note of rancher 1.6.21, this version of Docker is supported.

Any ideas why I get this warning ?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/14856
