### ISSUE TITLE
HAProxy config matching order

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#1503]
Rancher	v0.27.0-rc3
Cattle	v0.62.0
User Interface	v0.33.0
Rancher Compose	latest

When targets are added with Host name balancing, the targets are not always placed in a preferable order in the haproxy.cfg. 

```
# haproxy.cfg
acl host_api hdr_end(host) -i api.example.com
acl host_api_v2 hdr_end(host) -i v2.api.example.com
acl host_web hdr_end(host) -i example.com
```

A request with ```Host: v2.api.example.com``` would be routed to ```host_api```, not ```host_api_v2``` like it should because ```host_api``` matches first.

I propose that you allow an order/priority selector in the LB config screen.

**Comment by vincent99** [comment]
Wouldn't ordering the hosts (and paths) by descending length be sufficient?  That would make the most specific match first.

**Comment by vincent99** [comment]
@alena1108 Does the string compare for the host header default to exact match or substring?

According to this issue it must be substring or suffix...  But I think if we want "this host or a sub domain of it" you have to regular expression matches to do word boundaries and ensure that you don't mismatch `something.example.com` as part of `thing.example.com`.

**Comment by willseward** [comment]
We should just be able to change the hdr all directive to ```hdr(host)``` instead of ```hdr_end(host)```

**Comment by vincent99** [comment]
Ah yes the `_end` means suffix.   This should be exact match.  We can add an optional `*.example.com` feature if you want to include subdomains that will add a rule for `hdr_end(host) .example.com` plus `hdr(host) example.com`.

**Comment by alena1108** [comment]
@vincent99 yes, host name should be an exact match. @willseward thanks for catching it + the fix!

**Comment by sangeethah** [comment]
Tested with build from master:

host name is now exact match. If i have LB target with host "abc" , then only when host header is "abc" , I am able to access the LB services.

When host header is set to anything other than "abc" like "abcx" or "xabc" , i get "503 Service Unavailable" .

**Comment by willseward** [comment]
Y'all are awesome thanks!!
