### ISSUE TITLE
Error retrieving kubelet metrics

### ISSUE THREAD

**Issue by SaiDoFan** [rancher/rancher#15030]
**Rancher versions:**
rancher/server or rancher/rancher:2.4.0
rancher/agent or rancher/rancher-agent:2.4.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):1.10.1-rc2

**Docker version: 1.13.1

**Operating system and kernel: CentOS7.5

**Type/provider of hosts: KVM

**Setup details: HA-rancher

**Environment Template: Kubernetes
**Reference from**
[https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#error-retrieving-kubelet-metrics]
"""
Error retrieving kubelet metrics
Should the Prometheus /targets page show kubelet targets, but not able to successfully scrape the metrics, then most likely it is a problem with the authentication and authorization setup of the kubelets.

As described in the prerequisites section, in order to retrieve metrics from the kubelet token authentication and authorization must be enabled. Some Kubernetes setup tools do not enable this by default.

Authentication problem
The Prometheus /targets page will show the kubelet job with the error 403 Unauthorized, when token authentication is not enabled. Ensure, that the --authentication-token-webhook=true flag is enabled on all kubelet configurations.

Authorization problem
The Prometheus /targets page will show the kubelet job with the error 401 Unauthorized, when token authorization is not enabled. Ensure that the --authorization-mode=Webhook flag is enabled on all kubelet configurations.
"""

**Results:**
![wx20180810-112849](https://user-images.githubusercontent.com/37398738/43937501-9cd01796-9c90-11e8-992c-950145720189.png)

I'm supposed to change kubelet config according to official instructions, but I don't know how to change the cluster deployed by rancher？？？？
i want to help.

**Comment by deniseschannon** [comment]
With the latest integration of Prometheus and monitoring in Rancher 2.2, can you try that?
