### ISSUE TITLE
[zookeeper] Unable to use rancher-ebs for zookeeper volumes

### ISSUE THREAD

**Issue by saubi1993** [rancher/rancher#15031]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.9
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)** 
17.06.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 Ubuntu 16.04.2 LTS (4.4.0)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Just select rancher-ebs as volume driver
**Results:**
Error comes while cluster starts: Size is not mentioned for rancher-ebs volumes.
There should be a way to specify zookeeper volumes size

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
