### ISSUE TITLE
Account Used for Testing AD Connection (and other external auth) is Linked to Default Admin

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#15037]
When a user enables external authentication on the platform the external test account is automatically linked to the default admin.  This design is potentially dangerous

The presumption that the AD test account is the default admin moving forward is flawed, confusing (if you don't read the docs) and potentially dangerous.

Most other systems that can link to an auth system have separate functionality for testing a connection  vs. assignment of a user to a powerful admin account.  A user who doesn't read the documentation may create an unintended security issue, that may go unnoticed as it's the intended design of the system.

**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent:2.0.6

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Virtual Machine

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/ad/

**Results:**
https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/
The local Default Admin is linked to the account that is used to test authentidation

**Comment by carolynhu** [comment]
@JasonvanBrackel I am not quite understanding what do you mean by `linked to` Default Admin. When I fill out all the required fields and enable auth, if success, it will make the AD user as current login user.

**Comment by JasonvanBrackel** [comment]
@carolynhu Here's a new cluster and the local Default Admin user.

![screenshot from 2018-08-13 22-23-47](https://user-images.githubusercontent.com/942110/44068355-9847de8e-9f47-11e8-95e7-ebbfc90e4699.png)

Here's the corresponding information from the API

![screenshot from 2018-08-13 22-24-49](https://user-images.githubusercontent.com/942110/44068389-b704d084-9f47-11e8-8052-0e7d7b21653a.png)

If I connect this platform to my github user.

![screenshot from 2018-08-13 22-27-46](https://user-images.githubusercontent.com/942110/44068482-2c54544a-9f48-11e8-96d5-84467161e4ad.png)

I log out and log back in.

I click on the View In API for the Default Admin account.

You'll notice that the princpalIds for the Default Admin account are the local id for the Default Admin account and the github id for the user used to setup github authentication.  This is consistent in Active Directory as well.

![screenshot from 2018-08-13 22-31-41](https://user-images.githubusercontent.com/942110/44068582-bdc2888e-9f48-11e8-86fa-d32b61c032ae.png)

**Comment by happyyangyuan** [comment]
@JasonvanBrackel Please refer to rancher2.x official doc for  [External Authentication Configuration and Principal Users](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/#external-authentication-configuration-and-principal-users)：

`
"Rancher associates the external principal with the local principal. These two users share the local principal’s user ID."
`
`
"Because the external principal and the local principal share an ID, no unique object for the external principal displays on the Users page."
`

**Comment by JasonvanBrackel** [comment]
@happyyangyuan I'm quite aware of the functionality. My problem is not that it's potentially confusing, but potentially dangerous.  See my original note. The system assigns an admin level of functionality by side effect.

> When a user enables external authentication on the platform the external test account is automatically linked to the default admin. This design is potentially dangerous
> 
> The presumption that the AD test account is the default admin moving forward is flawed, confusing (if you don't read the docs) and potentially dangerous.
> 
> Most other systems that can link to an auth system have separate functionality for testing a connection vs. assignment of a user to a powerful admin account. A user who doesn't read the documentation may create an unintended security issue, that may go unnoticed as it's the intended design of the system.

**Comment by vincent99** [comment]
While I agree it could be made more clear on the screen or maaybe optional, I don't think the functionality is wrong here.  The cases where the the user who setup auth is the same person as the external auth account they're using to test far outnumber people using some other account and might not want this.

If you don't tie the current user's local identity to the one that they authenticate with at the time it's setup, there is (currently) no way to do that later.  So the next time they login with their AD (or whatever) account, they see nothing and wonder where all their stuff went.

**Comment by JasonvanBrackel** [comment]
@vincent99, I hear you and I completely get the problem not doing this would introduce.  I think this is fixable with a UI change.  Just needs to be clear to the user *exactly* what's about to happen when they link to the auth provider.

**Comment by zhasaan** [comment]
Well a user account that is used to test the AD/OpenLDAP authentication gets the Admin profile associated to it, so what that means the "Kubectl Config" file for this user to connect to Rancher cluster is has the same  contents (username, token, etc.) and this user has "Admin" privileges without knowing and can potentially make damage.

**Comment by MetalJacx** [comment]
Out of all the SAML connections Rancher has been the most confusing to me. I would like to see the functionality of importing. Where after creating the SAML connection, a import function shows up on the user page. I can then type in the SAML user's username and will create a local account that ties to the external account.
The issue I am experiencing is the access control not working and every SAML user is logging in as the user who initially created the SAML Authentication.

**Comment by maggieliu** [comment]
Request is to add a UI with warning msg and update associated docs with a similar warning.

**Comment by izaac** [comment]
Validated the new banner appears in 

- Rancher `v2.4-head (06/23/2020)` commit id: 46f7940dd
- Rancher `master-head (06/23/2020)` commit id: 744202bd9

![Screen Shot 2020-06-23 at 10 43 30 AM](https://user-images.githubusercontent.com/27659/85442817-70ea5e00-b545-11ea-9e43-e4355e74138a.png)

I clicked in all the cloud options and the banner is visible. I also checked the dark mode theme.
