### ISSUE TITLE
rancher server and tricky NAT

### ISSUE THREAD

**Issue by fedya** [rancher/rancher#15045]
**Rancher versions:**
rancher/server or rancher/rancher:latest
rancher/agent or rancher/rancher-agent:latest

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Openmandriva 4.0
4.18.0-desktop-0.rc7.1omv4000

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
just default

**Steps to Reproduce:**
i have a rancher server behind DSL modem, with an addr **10.87.57.123**
but modem forwarding all incoming traffic to such machine.
When i trying to deploy worker node to it i got

```
2018/08/11 17:23:08 [error] 18#18: *1 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.123:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
**Results:**

```

Looks like worker node trying to access server via eth0 interface ip, that is wrong i think
right address should be via name my-server.com

**Comment by fedya** [comment]
```
2018/08/11 17:38:44 [error] 14#14: *261 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2018/08/11 17:38:44 [error] 14#14: *263 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2018/08/11 17:38:44 [error] 15#15: *264 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2018/08/11 17:38:45 [error] 14#14: *267 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2018/08/11 17:38:45 [error] 14#14: *269 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2018/08/11 17:38:45 [error] 14#14: *271 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2018/08/11 17:38:47 [error] 14#14: *273 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2018/08/11 17:38:47 [error] 14#14: *275 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2018/08/11 17:38:47 [error] 14#14: *277 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.87.57.21:6443", bytes from/to client:0/0, bytes from/to upstream:0/0

```

**Comment by fedya** [comment]
@loganhz version is 2.0.7

**Comment by arvanus** [comment]
Any news on this?
I'm getting the same problem, with the remote node trying to access the master node thru local address:

{"log":"2021/10/18 18:11:48 [error] 12#12: *3951 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: \"192.168.1.90:6443\", bytes from/to client:0/0, bytes from/to upstream:0/0\n","stream":"stderr","time":"2021-10-18T18:11:48.373875Z"}


{"log":"E1018 18:11:48.450307  795884 kubelet.go:2291] \"Error getting node\" err=\"node \\\"srvpedido-fisjpi\\\" not found\"\n","stream":"stderr","time":"2021-10-18T18:11:48.4504126Z"}
{"log":"E1018 18:11:48.550781  795884 kubelet.go:2291] \"Error getting node\" err=\"node \\\"srvpedido-fisjpi\\\" not found\"\n","stream":"stderr","time":"2021-10-18T18:11:48.5508913Z"}
{"log":"E1018 18:11:48.651323  795884 kubelet.go:2291] \"Error getting node\" err=\"node \\\"srvpedido-fisjpi\\\" not found\"\n","stream":"stderr","time":"2021-10-18T18:11:48.651428Z"}
