### ISSUE TITLE
kubectl get statefulsets/X fails

### ISSUE THREAD

**Issue by tboemker-bkfs** [rancher/rancher#15046]
$ kubectl describe statefulsets/my-statefulset
error: no kind "GetOptions" is registered for version "apps/v1"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by loganhz** [comment]
Please see https://github.com/kubernetes/kubernetes/issues/59867
