### ISSUE TITLE
rancher fails to spawn hosts on digital ocean

### ISSUE THREAD

**Issue by jottr** [rancher/rancher#1504]
I am running rancher server on a small digital ocean instance.
Trying to add new hosts fails with: `fork/exec /usr/bin/docker-machine: cannot allocate memory`

For the host config I use a 1GB instance. 
Not sure if this docker issue is relevant: https://github.com/docker/docker/issues/8539

**Comment by ibuildthecloud** [comment]
You need to run the server on an instance of at least 1GB.  Is this a 512mb?  As we start optimizing the server soon we hope the memory footprint will go down, but right now 512 isn't feasible.

**Comment by jottr** [comment]
@ibuildthecloud yes I used the small instance first. 
After I upgraded the server instance to 1GB, above error went away.
But even then I am observing complete crashes of the docker image which runs the rancher server, when creating new rancher hosts. 
Will try to reproduce and post a new issue.
