### ISSUE TITLE
MS Teams and/or xMatters Alert or Customize Webhook from Alert

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15041]
My company uses Microsoft Teams for chat and xMatters for alert management and it would be awesome to support that as an alert from Rancher Server. Now I understand it uses AlertManager under the hood so maybe it would be better to allow us to customize the webhook being sent out that way we don't have to create a middleware service to ingest and spit out the apps compatible json payload so it can work.

**Comment by loganhz** [comment]
link to https://github.com/rancher/rancher/issues/15802
