### ISSUE TITLE
Rancher doesn't remove exited containers

### ISSUE THREAD

**Issue by tboemker-bkfs** [rancher/rancher#15047]
$ docker ps -a | grep Exited
b204663372da        rancher/pause-amd64:3.1              "/pause"                 7 days ago          Exited (137) 5 days ago                             k8s_POD_notification-service-f6cc7d66b-lcz7j_default_02d90521-9755-11e8-8c88-005056815d94_0
0278d21d5cb9        51eebeddb033                         "sh -c 'sysctl -w ..."   8 days ago          Exited (0) 8 days ago                               k8s_sysctl_nginx-ingress-controller-jfdpv_ingress-nginx_151e3f57-94e7-11e8-b256-005056815d94_11
59f64b54d263        2b736d06ca4c                         "/opt/bin/flanneld..."   8 days ago          Exited (137) 8 days ago                             k8s_kube-flannel_canal-wkm9b_kube-system_151e4506-94e7-11e8-b256-005056815d94_12
384aa985d463        66e10c24a484                         "/usr/bin/dumb-ini..."   8 days ago          Exited (137) 8 days ago                             k8s_nginx-ingress-controller_nginx-ingress-controller-jfdpv_ingress-nginx_151e3f57-94e7-11e8-b256-005056815d94_10
a9cb072e4982        482f47df27e2                         "/install-cni.sh"        8 days ago          Exited (0) 8 days ago                               k8s_install-cni_canal-wkm9b_kube-system_151e4506-94e7-11e8-b256-005056815d94_10
80577a475e0b        3571bad91a6b                         "run.sh"                 8 days ago          Exited (2) 8 days ago                               k8s_agent_cattle-node-agent-w4ppm_cattle-system_15209512-94e7-11e8-b256-005056815d94_10
d7e5fb1492ec        d94b64ac210d                         "start_runit"            8 days ago          Exited (0) 8 days ago                               k8s_calico-node_canal-wkm9b_kube-system_151e4506-94e7-11e8-b256-005056815d94_10
46efa3429632        rancher/pause-amd64:3.1              "/pause"                 8 days ago          Exited (0) 8 days ago                               k8s_POD_cattle-node-agent-w4ppm_cattle-system_15209512-94e7-11e8-b256-005056815d94_10
4c1b2948b4f7        rancher/pause-amd64:3.1              "/pause"                 8 days ago          Exited (0) 8 days ago                               k8s_POD_nginx-ingress-controller-jfdpv_ingress-nginx_151e3f57-94e7-11e8-b256-005056815d94_10
88ff9cfb2e6b        rancher/pause-amd64:3.1              "/pause"                 8 days ago          Exited (0) 8 days ago                               k8s_POD_canal-wkm9b_kube-system_151e4506-94e7-11e8-b256-005056815d94_10
522759cfb152        rancher/rancher-agent:v2.0.6         "run.sh -- share-r..."   11 days ago         Exited (0) 8 days ago                               share-mnt

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by vincent99** [comment]
This is standard kubernetes behavior.  https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
