### ISSUE TITLE
TLS handshake error shown when opening embedded kubectl shell

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15056]
**Rancher versions:**
rancher/rancher:v2.0.7

**Steps to Reproduce:**
* Create custom cluster
* Add nodes
* Open embedded kubectl shell

**Results:**
Log will show

```
2018/08/13 10:20:27 [INFO] 2018/08/13 10:20:27 http: TLS handshake error from host:port: remote error: tls: unknown certificate authority
```

**Comment by m0sh1x2** [comment]
Is your traffic going through CloudFlare's Reverse Proxy?

**Comment by cjellick** [comment]
@superseb is the feature still functional? Is this just a logging issue?

**Comment by superseb** [comment]
Yes it works, it's just to clean up the log.
