### ISSUE TITLE
R2: AWS - Key Cleanup

### ISSUE THREAD

**Issue by benyanke** [rancher/rancher#15058]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node master for testing purposes

**Steps to Reproduce:**
 - Create a new cluster of EC2 nodes with IAM keys.
 - Delete nodes
 - Look at list of key pairs 

**Results:**
Note that key pairs of old nodes are still there. This, of course, will lead to a large buildup of keys after a while.

These keys should (I assume?) deleted after the nodes are deleted, given that they are no longer needed after the node is gone.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13977
