### ISSUE TITLE
rancher container stuck at stopping container

### ISSUE THREAD

**Issue by bluejedi** [rancher/rancher#15055]
*Describe your issue here*
today i wan to clear my dev env host, so i check about 7 running container to delete them, bust they stuck at stopping, i have tried to restart the docker service manually in host but i lost my container

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`containers.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
