### ISSUE TITLE
API UI return parseerror

### ISSUE THREAD

**Issue by fyery-chen** [rancher/rancher#15054]
when I access the api to exec the action of rollback apprevision via the link:
```
HTTP/1.1 POST /v3/project/local:project-cbrjz/apps/project-cbrjz:wordpress?action=rollback
Host: xx.xx.xx.xx
Accept: application/json
Content-Type: application/json
Content-Length: 34

{
"revisionId": "apprevision-6pl7j"
}
```
Then return parseerror
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Results:**
![image](https://user-images.githubusercontent.com/6060442/44010592-fae66766-9ee5-11e8-8c0d-5552d4b1d16c.png)

**Comment by cjellick** [comment]
@fyery-chen What does the prefix [File issue] mean? What is its purpose?
