### ISSUE TITLE
R2: Duplicate Node Template

### ISSUE THREAD

**Issue by benyanke** [rancher/rancher#15059]
It would be very useful to be able to duplicate a node template. 

My usecase: I'd like to be able to make one node template, then duplicate it twice to change a single setting (for example - node size).

Currently you have to create two node templates manually.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/44501572-60a29700-a6c0-11e8-97f2-58cca6bccf24.png)
User can clone a node template in v2.0.7
