### ISSUE TITLE
Rancher node stuck in "waiting to register with Kubernetes"

### ISSUE THREAD

**Issue by abbcdfin** [rancher/rancher#15057]
**Rancher versions:**
rancher/rancher: v2.0.6
rancher/rancher-agent: v2.0.6

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-105-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
ECS on AliYun

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with etcd/controlplane/worker node running on one ECS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Created a cluster with custom node following the instrustions in https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/

**Results:**
The cluster became active successfully, however, the node is stuck in "Waiting to register with kubernetes".

Checked the log of kubelet container, the log said "Successfully registered node ..."
[kubelet.log](https://github.com/rancher/rancher/files/2283073/kubelet.log)

**Comment by loganhz** [comment]
Can you go to the nodes page and look at the state of the node, please?

Is there any container failed to start up on that node? 

![image](https://user-images.githubusercontent.com/21168270/44390764-aba59880-a560-11e8-9aee-26968f3dd7d3.png)

**Comment by abbcdfin** [comment]
Sorry for having not updated in time, got distracted by something else.

![screenshot_2018-09-11_19-58-20](https://user-images.githubusercontent.com/28372305/45358817-36783100-b5fd-11e8-8355-4a2c1fd2b020.png)

**Comment by loganhz** [comment]
@abbcdfin the node name contains uppercase which is invalid. 

![image](https://user-images.githubusercontent.com/21168270/45401147-daa3bb80-b681-11e8-9f38-7d126f80f0dc.png)

**Comment by abbcdfin** [comment]
@loganhz Thanks for the reply, I did not find the proper way to change the node name, so I change the host name of the virtual machine. After that, I ran into #13314. Deleted the cluster and rebuilt one, it started working. 

Thanks for the help. But I am a bit worried if rancher 2.0 is really ready for production environment?

**Comment by seirian** [comment]
I solved it by the way below.
I hope it will help.
Both the Manager and Worker node servers have been applied.

**firewall-cmd --zone=public --add-port=6443/tcp --permanent
firewall-cmd --reload**
