### ISSUE TITLE
Scaling down vSphere worker pool results in loss of persistent volumes

### ISSUE THREAD

**Issue by LinAnt** [rancher/rancher#15065]
**Rancher versions:**
rancher/rancher:v2.0.7

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.5

**Docker version: (`docker version`,`docker info` preferred)**
17.3.x
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 1.4-vmware
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single and HA

**Steps to Reproduce:**
We noticed persistent volumes get deleted if you delete or recreate a node where a pod with bound volumes are running. Is this the intended behaviour?
**Results:**

If you want to keep you persistent volumes you have to drain the node and then delete it. If a node crashes you have no way of doing this.

If this is not the intended behaviour we should get a warning when deleting nodes with attached volumes.

**Comment by janeczku** [comment]
Reproduced in v2.0.7.

**Steps to Reproduce:**
1. Create a cluster with the vSphere infrastructure provider, while also enabling the vSphere cloud provider.
2. Create a workload with a persistent volume claim (using the vSphere storage class)
3. In the UI Cluster->Nodes, either scale down the worker pool using the `+-` button or delete the node where the workload is running via Context-Menu->Delete.

**Results:**
The node is deleted. The VMDKs attached to the node providing the persistent volumes are also deleted causing loss of persistent data.

**Expected result:**
The node is drained before deleting it at the cloud provider side. That way any VMDK currently attached to the host would have been detached and not deleted.

**Comment by LinAnt** [comment]
This is probably the reason behind all of this: https://github.com/kubernetes/kubernetes/issues/67900

**Comment by loganhz** [comment]
As kubernetes/kubernetes#67900 has been closed. Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by skyscooby** [comment]
Is this going to be fixed? Has your vSphere team at Rancher never been hit with this problem? It seems like a pretty major one that would deserve a bit more attention given it's ramifications on data loss and been untended to in a year...

If you are going to put a fancy +/- button on the UI, with one click and no confirmation or warning.. that implies that a seamless and safe operation is going to occur and Rancher has the responsibility to make it work correctly. Today this is catastrophic in scale down operations.

This is a Rancher issue more than a Vsphere one. If you read the In-Tree Vsphere Cloud docs here (which is what rancher sets up as documented so I understand): https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/high-availability.html#node-vm-failure. It says that the mode of operation on node failure should expects to transition the disks attached to the failed node in a shutdown state.. and is expecting them to remain attached to the failed node. It can some time for the migration to happen but ranchers vsphere orchestration is deleting the node before this is confirmed or verified as being complete and in turn it is triggering vpshere to delete all volumes still attached to it when deleted..

A few options to address might include:

an option in vsphere clusters to simply power off machines on scale down and power them on on scale up if they already exist only creating a new node when it hasn't been created yet..
for rancher OS provisioned clusters you know how many disks are part of the OS.. you could count the disks attached to the VM through the API and wait to delete it until only the OS disk(s) are left.
an option to disable the +/- button for vsphere clusters when the cloud provisioner is enabled.

**Comment by skyscooby** [comment]
This clearly has nothing to do with https://github.com/kubernetes/kubernetes/issues/67900 as that has been fixed since 1.11 and this still happens on 1.17 clusters with rancher 2.4.5
