### ISSUE TITLE
 Refactor base user access to have less permissions

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#15061]
The lowest privileged global role currently available is "User Base".
It should be changed to:
- not allow list/watch/get of principals
- not allow list/watch/get of users
- But a user assigned this role still needs to be able to see him/herself at /v3/users?me=true and /v3/users/<your user id>

Additionally, the normal "User" role should not be able to list/watch/get users. But as with user base, a user with the role should be able to him/herself at /v3/users?me=true and /v3/users/<your user id>

**Comment by cjellick** [comment]
To reword this from a end-user perspective:

If the default global role is set to "User login", then users should only be able to log in and do nothing else. Importantly, they should not be able to search/view/list rancher users or "principals" (users and groups) that come from the auth provider (ie github, AD).
A user who assigned the just the "User login" global role in this fashion and then is added to a project should be able to fully utilize the project for deploying/managing workloads, but because they cannot see principals and other users, when they go to the Members page for the project, they should see a degraded view because that page relies on loading the user/principal's details. Consequently, a user added with this role won't be able to properly add users to projects/clusters through the UI, but that is the point

**Comment by soumyalj** [comment]
@cjellick : Here are the use cases for this feature. Please review and let us know if we missed something. 

Provide AD auth and set the default user role as “User Base”

1. Add testuser2 as a cluster owner
    1. Verify that he cannot add users at cluster level 
    2. Verify member tab view only has “testuser2”
    3. Verify he cannot search other users 
2.  Add testuser2 as a project owner
    1. Verify that he cannot add users at project level
    2. Verify member tab view only has “testuser2”
    3. Verify he cannot search other users 
3. Login as a user "testuser3" who is not added as a member to a cluster.
    1. Verify the user "testuser3" cannot see any of the clusters
    2. When logged in as an admin, the user "testuser3" should be in the users list
4. Upgrade scenario:
       After upgrade from v2.0.7 to v2.0.8-rc verify that the “User Base” works as described above.

Note: With local auth,  we choose the role user gets created with explicitly and not rely on the default Global role set and there is no “User Base” role set

**Comment by soumyalj** [comment]
Tested with rancher v2.0.8-rc2 and "User Base" role is functional as detailed above.
