### ISSUE TITLE
Last error is displayed on the newly opened dialog

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1507]
Steps to reproduce:

1) Open "Add service" dialog. Put invalid name, click "Create". Error message gets displayed - everything works fine at this point.
2) Close the dialog, and open it again. Although no invalid name is populated this time, the last error message is still displayed. 

![screen shot 2015-07-13 at 10 17 51 am](https://cloud.githubusercontent.com/assets/1562176/8655765/32f10902-2948-11e5-9628-4375ace536f0.png)

**Comment by vincent99** [comment]
Dup of #1476.
