### ISSUE TITLE
Ingress controller does not pickup updated certificate

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#15073]
**Rancher versions:**
rancher/rancher: v2.0.6

**Steps to Reproduce:**
1. Manually create a new SSL certificate in "Resources/Certificates"
2. Create a new ingress rule with SSL enabled and point to a workload
3. Update a new certificate

**Results:**
Rancher ingress controller **does not** pick up the new cert

**Expected:**
Rancher ingress controller should pick up the new cert and reload itself.

**Comment by alena1108** [comment]
@orangedeng could you check if it's the issue on our side, or nginx ingress controller doesn't react to certificate changes

**Comment by orangedeng** [comment]
It seems like it is a nginx ingress controller issue. I am reproducing this issue. After changed the SSL cert, nginx ingress do not got the secret change event immediately. Let comments here to let you know we are working on it. @alena1108 @truongdo

**Comment by orangedeng** [comment]
tested with v2.0.8 and `rancher/nginx-ingress-controller:0.16.2-rancher1`, this issues didn't come up again.

**Comment by alena1108** [comment]
@carolynhu to validate

**Comment by carolynhu** [comment]
Steps to reproduce this issue:
1. Add a workload `myworkload`
2. Create a certificate `mycert` under Resources/Certificates, with 1 year expire time and domain name is `abc.com`
3. Add an ingress `myingress` with SSL certificates enabled, choose `mycert` as the certificate.
4. Update `mycert` with a 2 years expire time and domain name is `xyz.com`
5. Check `myingress`, now it's certificate's domain name change from `abc.com` to `xyz.com`, which means it chooses the updated certificate.

**Comment by h3d-thanhpv** [comment]
I see this bug again in rancher/server:v2.1.1
I edited my certificate, it updated expire time, but when I access from browser, it use old certificate, with expire time in 10 days. 
Please help me.
