### ISSUE TITLE
UI: Importing 2 Existing Clusters Concurrently Causes 2nd Imported Cluster to Skip Route 

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#15072]
**Rancher versions:** v2.0.7
rancher/server or rancher/rancher: rancher/rancher:latest
rancher/agent or rancher/rancher-agent: n/a

**Docker version: (`docker version`,`docker info` preferred)** 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** RancherVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Import an existing cluster
2. Follow the steps on the next screen to begin the import.
3. Before Rancher completes the first import, create a second imported cluster

**Results:**

Rancher UI redirects to the clusters screen instead of presenting the steps to begin the import. User can navigate to the `Edit` screen, but the import steps won't work. Only option is to delete/recreate the second imported cluster.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/29
Verified fixed
