### ISSUE TITLE
Running Single node instance if etcd takes longer then 10 seconds Rancher can't start

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#15077]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.x

**Infrastructure Stack versions:**
If etcd in a stand alone Docker container takes longer then the hard coded 10 second timeout in the k8s api server then the container will enter a crash loop. 

We need to ensure that etcd comes up before starting kubernetes.

**Comment by cloudnautique** [comment]
addressed by #15078

**Comment by deniseschannon** [comment]
Available in v2.0.8-rc1

**Comment by cloudnautique** [comment]
Verified with customer that they were able to start Rancher server with this fix.
