### ISSUE TITLE
How to create container with value - Privilege:true

### ISSUE THREAD

**Issue by csilaser** [rancher/rancher#15088]
HI there ,
I 'm having a container that had some privilege issue, and got this error :
"Failed to get D-Bus connection: Operation not permitted"

I succeeded with fixing it, by changing on the YAML file those  2 values : 
`          allowPrivilegeEscalation: false
          privileged: false`

Now, I commited the container to an image, and I expect that when creating a new container from this image, those values will stay on **true ** , but it's on "false"

Do you know how can I change on the **image** itself, or creating a container that will be create already with those values as "true "

Thanks in advance,
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`` |
|Route|`containers.index`|

**Comment by vincent99** [comment]
That is not how containers work. The image stores only the files and a few very specific  bits of metadata (like what entrypoint/command to run by default). Everything else about a specific container using that image is only a property of that one container (/workload).

For `--privileged` specifically, what you're suggesting would be the immediate end of DockerHub.  Any arbitrary `docker run some-image` could have full control over your computer and do whatever it wants.

**Comment by csilaser** [comment]
OK Vincent, thanks for your informative reply.

It's just taking some more time to create 50-60 containers, and then go one by one and change this value

thanks !
