### ISSUE TITLE
Editing a LB service to add another service to an existing host/path config, does not result in haproxy config reflecting this change.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1508]
Server version - V0.27.0-rc3

Steps to reproduce the problem:
Had LB service with following configuration except for the last entry:

<img width="779" alt="screen shot 2015-07-13 at 10 48 32 am" src="https://cloud.githubusercontent.com/assets/4266958/8656498/c4177a70-294c-11e5-9033-325d1da4f7f6.png">

Edited LB service and added the last entry -host- www.abc1.com path-/service2.html target service-lb1:

I don't see the the instance from lb1, being included to -host- www.abc1.com path-/service2.html  in haproxy config:

<img width="798" alt="screen shot 2015-07-13 at 10 52 17 am" src="https://cloud.githubusercontent.com/assets/4266958/8656579/40de2356-294d-11e5-9ef4-f5cdba36a37d.png">

```
mysql> select * from service_consume_map;                                                                                            
+----+------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+---------------------------------------------------------------------------------------+------------+---------------------+------------+
| id | name | kind              | uuid                                 | description | state   | created             | removed             | remove_time         | data                                                                                  | service_id | consumed_service_id | account_id |
+----+------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+---------------------------------------------------------------------------------------+------------+---------------------+------------+
|  1 | NULL | serviceConsumeMap | 143d4861-d004-4427-ad0c-ed1605dd494b | NULL        | removed | 2015-07-13 17:07:17 | 2015-07-13 17:10:02 | 2015-07-13 17:11:02 | {"fields":{"ports":["80:www.abc.con/service1.html"]}}                                 |          5 |                   2 |          5 |
|  2 | NULL | serviceConsumeMap | 778c9977-48f4-46c4-b7e3-77e45295c86d | NULL        | removed | 2015-07-13 17:07:17 | 2015-07-13 17:09:56 | 2015-07-13 17:10:56 | {"fields":{"ports":["80:www.abc.com/service2.html"]}}                                 |          5 |                   3 |          5 |
|  3 | NULL | serviceConsumeMap | 9b916a92-7d75-45f9-a73a-28860e41b1bc | NULL        | removed | 2015-07-13 17:07:17 | 2015-07-13 17:09:56 | 2015-07-13 17:10:56 | {"fields":{"ports":["80:/name.html"]}}                                                |          5 |                   4 |          5 |
|  4 | NULL | serviceConsumeMap | 4e3bf305-9a9c-4330-bcd9-ca66103d9eaf | NULL        | removed | 2015-07-13 17:15:33 | 2015-07-13 17:21:26 | 2015-07-13 17:22:26 | {"fields":{"ports":["80:www.abc.com/service1.html"]}}                                 |          9 |                   6 |          5 |
|  5 | NULL | serviceConsumeMap | e1440a65-236a-404c-8c56-de214f7cfe11 | NULL        | active  | 2015-07-13 17:15:33 | NULL                | NULL                | {"fields":{"ports":["80:www.abc1.com/service2.html"]}}                                |          9 |                   7 |          5 |
|  6 | NULL | serviceConsumeMap | 7bbaa7a4-a8f0-4d7b-8cac-515acb3180c2 | NULL        | active  | 2015-07-13 17:15:33 | NULL                | NULL                | {"fields":{"ports":["80:/name.html"]}}                                                |          9 |                   8 |          5 |
|  7 | NULL | serviceConsumeMap | 11bee694-ed1f-4ee3-8cd3-d750c92f8bcd | NULL        | active  | 2015-07-13 17:21:26 | NULL                | NULL                | {"fields":{"ports":["80:www.abc.com/service1.html","80:www.abc1.com/service2.html"]}} |          9 |                   6 |          5 |
+----+------+-------------------+--------------------------------------+-------------+---------+---------------------+---------------------+---------------------+---------------------------------------------------------------------------------------+------------+---------------------+------------+
```

<img width="1000" alt="screen shot 2015-07-13 at 10 52 49 am" src="https://cloud.githubusercontent.com/assets/4266958/8656603/5760a13a-294d-11e5-9315-9e116ffb2edd.png">

**Comment by alena1108** [comment]
The root cause of the issue is - when the same target service is modified with new port information, service link gets recreated (old one gets removed, new one gets created). When that happens, corresponding lb targets is scheduled for removal by serviceLink.remove operation, and gets readded by serviceLink.create. Looks like target gets never re-added as in the DB I only see it being removed.

Easy steps to reproduce:

1) Create service1 with scale1.
2) Register it for the load balancer with host=abc and service1
3) Edit the load balancer by adding host=abc1 and service1.

**Comment by sangeethah** [comment]
Simpler use case that breaks:

Create LB service with host -test1 for service S1.
Service S1 had 2 containers associated with it.

Edit LB service and add host -test2 for service S1.

After this , there is only 1 instance associated with backend relating to acl - test1 and test2.

<img width="753" alt="screen shot 2015-07-13 at 11 45 25 am" src="https://cloud.githubusercontent.com/assets/4266958/8657822/c7d1d446-2954-11e5-85d9-90c3bbadce01.png">

**Comment by sangeethah** [comment]
Similar issue is also seen in the following use case:

Create LB service with host -test1 for service S1.
Service S1 had 2 containers associated with it.

Edit LB service and edit host to test2 for service S1.

After this , there is only 1 instance associated with backend relating to acl - test2.

**Comment by sangeethah** [comment]
Tested with build from master:

Editing an existing LB service and adding more hosts/editing the existing host for a service results in haproxy being configured as expected.
