### ISSUE TITLE
Rancher 2.0.7 cli --rke-config kubernetes_version variable being ignored on cluster creation

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15083]
We are automating creating the cluster using rancher cli and noticed that if we set the kubernetes version in the rke-config using the kubernetes_version variable and not set the k8s-version option to the create command it overwrites to the default. I expected it to use the value in the rke-config file but it seems to be ignoring that and only accepts it if I provide the --k8s-version.

**Comment by deniseschannon** [comment]
Are you sure it was overriding the default and it wasn't the fact that you weren't specifying a "supported" kubernetes version for a RKE cluster? In older versions of RKE, if the version wasn't on the list of supported ones, it would have been overridden. 

https://rancher.com/docs/rke/latest/en/config-options/#kubernetes-version
