### ISSUE TITLE
Feature: Authentication via Cloudflare Access

### ISSUE THREAD

**Issue by dhbaird** [rancher/rancher#15080]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.4
rancher/agent or rancher/rancher-agent: n/a

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Cloudflare provides an authentication and authorization framework called "Cloudflare Access" which I would like to use in front of Rancher. If this is already possible (or will never be done, as a deliberate design choice), a pointer would be greatly appreciated!

It's based on JWT and more info is here:

https://developers.cloudflare.com/access/setting-up-access/validate-jwt-tokens/

Thanks!

**Comment by lucasmellos** [comment]
Does anyone has an update on this? @deniseschannon @dhbaird

**Comment by jonathon2nd** [comment]
Protecting Rancher UI with ZT auth would be nice.

**Comment by jonathon2nd** [comment]
What release will this go out with? :smile:

**Comment by luc122c** [comment]
Is this the feature? https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/jwt-authentication
