### ISSUE TITLE
Users should be warned/instructed when interacting with System project resources

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15081]
System project contains all the namespaces that are running the vital resources in a cluster. When interacting with the System project, the user should be warned it's operating in the System project, and that any chance can harm the working of the cluster.

**Comment by loganhz** [comment]
It shows a warning in system project.

It shows a warning when user trying to remove system project in cluster level.

It shows a warning when user trying to remove namespaces under system project in cluster level.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/27
@loganhz - I don't see a warning in the delete for project/namespaces?  I went to the cluster, then the Project/Namespaces page.  Clicked on delete for the system project and the cattle-system namespace.  No warning in the delete modal?
![image](https://user-images.githubusercontent.com/11514927/44677041-cdcc6a00-a9e9-11e8-8660-fe0e878aee9b.png)
![image](https://user-images.githubusercontent.com/11514927/44677053-d4f37800-a9e9-11e8-8f0b-68e5457be58c.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/29
Verified fixed
