### ISSUE TITLE
UX Change: Unable to see annotation on Load Balacer Rules Unless they're edited

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#15096]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.0.7

**Steps to Reproduce:**
Create an Load Balancer (ingress) rule

View rule in the UI

**Results:**
Annotations are not shown unless you edit the ingress rule.
![image](https://user-images.githubusercontent.com/942110/44219603-7e18b380-a14a-11e8-8b9f-b5a086baa92c.png)

Edit Mode
![image](https://user-images.githubusercontent.com/942110/44219638-9688ce00-a14a-11e8-8179-489d2e8f5152.png)

**Comment by tfiduccia** [comment]
Version - 2.2 master 10/24
Verified fixed
