### ISSUE TITLE
Storage Classes created in Kubectl cannot be set as default in the UI

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#15097]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.07

**Steps to Reproduce:**
Create a storage class
![image](https://user-images.githubusercontent.com/942110/44220366-66422f00-a14c-11e8-85ea-10a4461dc2e2.png)

Go to the storage class 
![image](https://user-images.githubusercontent.com/942110/44220380-75c17800-a14c-11e8-8808-5bf4ac2bb528.png)
in the UI attempt to set as default

**Results:**
Default is not set
![image](https://user-images.githubusercontent.com/942110/44220415-8a9e0b80-a14c-11e8-949f-31fd1b727e21.png)

**Comment by dmastag** [comment]
I have the same problem on v2.1.0 using nfs-client

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/7/19)
Confirmed fix. Followed steps to reproduce and the storage class now can be set as default in the UI. Validated HTTP.
