### ISSUE TITLE
Incorrect heading on detail pages for Persistent Volume Claims

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#15091]
**Rancher versions:**
v2.0.7

**Steps to Reproduce:**

1. In a project, navigate to Workloads->Volumes
2. Create a new volume claim by clicking "Add volume"
3. On Workloads->Volumes click on the *Claim Name* of the volume

**Expected:**
Heading of persistent volume claim detail page is "Persistent Volume Claim: `<name of pvc>`".

**Actual:**
Heading is "Persistent Volume: `<name of pvc>`".

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/27
Verified fixed
