### ISSUE TITLE
HTTP_PROXY variable can't exclude intra-node traffic

### ISSUE THREAD

**Issue by animale66** [rancher/rancher#15094]
**Rancher versions:**
rancher/server or rancher/rancher: 2.06
rancher/agent or rancher/rancher-agent: 2.06

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.10

**Docker version: (`docker version`,`docker info` preferred)** 
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Oracle Linux Server"
VERSION="7.5"
ID="ol"
VERSION_ID="7.5"
PRETTY_NAME="Oracle Linux Server 7.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.5
4.1.12-124.17.2.el7uek.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Custom (Oracle Linux 7.5 VMs with Docker 17.03 installed on them)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Hello, 

The problem that we're having with Rancher is that the software is running on our local corporate intranet and is unable to communicate to the outside world without including 'docker run -e HTTP_PROXY <proxy>' when we start rancher/rancher.

As you know, rancher 2.06 has no proxy settings within the web interface, this is the only way for us to import new machine drivers and the like from rancher.com or wherever.  It'll also be necessary for us to connect to Azure nodes or any outside provider if we need them.

However, our proxy server doesn't allow us to 'bounce back' traffic to the internal nodes.  So what happens is, we deploy rancher/server and our first attempt to join a node fails as rancher/server can't communicate with the agent on port 6443.

We can work around this problem by using a docker run command like this:
docker run --name rancherserver -d -p 80:80 -p 443:443 **-e NO_PROXY=10.112.71.128** -e HTTP_PROXY=http://fqdnofproxy.com:8080 -e HTTPS_PROXY=http://fqdnofproxy.com:8080 -e CATTLE_SYSTEM_DEFAULT_REGISTRY=fqdnofregistry.com:4443 fqdnofregistry.com:4443/rancher/rancher:v2.0.6

This enables the rancher/agent at 10.112.71.128 to join, but effectively means the size of our cluster (and they're constituent members) must be determined when we launch rancher/rancer.

For reference, the NO_PROXY variable does not honor wildcards, so if I do NO_PROXY=*.company.com then that is not an effective workaround. 

I would suggest any one of the following changes to rancher/server:

* HTTPS traffic for 6443 (or similar ports) between rancher/rancher and rancher/agent do not honor a proxy.  I would imagine that the rancher/rancher and rancher/agent components are all on the same VLAN in even the larger deployments, but could be wrong. 
* HTTPS traffic for intranode traffic be configurable as a proxy within the web interface
* Configure NO_PROXY to honor domain name wild entries.

**Comment by alexandrem** [comment]
We are using Rancher on-prem with a corporate proxy and it works.

Most applications and libraries understand the no proxy environment variable settings with CIDR and dns suffixes.

You must define your NO_PROXY variable in the following manner:

`HTTP_PROXY=127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,169.254.0.0/16,.company.com`

Note the dot notation `.company.com` instead of wildcard.

For Rancher on Kubernetes, it means adding the env variables in the cattle server deployment. I use a mix of lowercase and uppercase variants to ensure all components understand it.

Having said that, I believe there are some problems with external node drivers such as EKS/AKS and proxy, but that's another story.

**Comment by animale66** [comment]
Alexandre, you're a saint and a gentleman. 

Works great now!
