### ISSUE TITLE
Dropdowns should go upward when there's no room to go downward

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1509]
![image](https://cloud.githubusercontent.com/assets/753917/8658114/b4aface2-2956-11e5-97fa-9b94fb615bca.png)

![image](https://cloud.githubusercontent.com/assets/753917/8658112/ac258df8-2956-11e5-9540-002d693eaf8d.png)

**Comment by deniseschannon** [comment]
Verified Fixed with v0.31.0-rc4

**Comment by deniseschannon** [comment]
Only broken on dropdown icons in hosts/containers.

**Comment by vincent99** [comment]
Pre-dup of #1923
