### ISSUE TITLE
Pod Security Policy UI ListBoxes Should Be Checkboxes

### ISSUE THREAD

**Issue by bradld** [rancher/rancher#15095]
**Rancher versions:**
rancher/rancher: v2.0.7

Currently the Rancher Pod Security Policy page has multi-select listboxes for selecting multiple items.  These make it difficult to navigate the page and select items, would prefer to see these converted into checkboxes.

**Comment by loganhz** [comment]
I guess you need to click the pod security policy name to navigate to detail page.

All the tables have the same behavior now.
