### ISSUE TITLE
Display events for persistent volumes and volume claims in the UI

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#15090]
**Rancher versions:**
v2.0.7

When UI users need to troubleshoot issues with volumes or PVCs stuck in pending, they currently have to revert to performing kubectl commands in order to inspect the corresponding events as they are not surfaced in the UI PVC/PV detail pages.

**Proposal:**
Add resource events list to in the PVC/PV detail pages. See pod detail page https://github.com/rancher/rancher/issues/13714#issuecomment-395943529.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/27
Verified fixed
