### ISSUE TITLE
HA user controller refactoring

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#15100]
We need to push all user cluster controllers down to the cluster agent in order to reduce the memory consumption of rancher management server. Here are a list of things that needs to be done.

- [ ] Pushing all controllers down to cluster agent. ( todo: figure out which is required to stay in management plane. Current foundout: rbac, healthcheckSyncer)

- [ ] Push all project-scoped CRDs from management plane to user cluster. (projectAlert, projectLogging, projectPipeline, Catalog app etc)

- [ ] Change proxy store to use the right client for those CRDs that were pushed.

- [ ] Figure out what is the minimal set of rbac rule we gave to cluster agent so that it only has limited privileges to execute the controller.

The final goal is to push all user controllers and project-scoped CRDs down to user cluster, so that their life cycle is strictly tied to the user cluster itself, not rancher management control plane. This should improve the scaling capability of rancher cluster size, and also the real HA solution can be better to implement based on the user controller refactoring.

**Comment by dramich** [comment]
The scope of this was narrowed to only move controllers that don't need to talk to the management plane. This was done to avoid the above issues with RBAC and permissions talking back to management and to also create a starting point for further enhancements to the controllers. 

The current plan is to not move CRDs to the user cluster and optimize existing controllers. 

New issue for this work is captured [here](https://github.com/rancher/rancher/issues/16168)
