### ISSUE TITLE
Catalog doesn't back off when getting forbidden error from Server

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#15103]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.7 / 2.0.8-rc1

**Infrastructure Stack versions:**
This error loop caused the container to hit 125% CPU and several GB of RAM according to Docker stats.

The error slightly cleaned up:
```
installing Kubectl apply failed. Error: Error from server (Forbidden): error when retrieving current configuration of:
...
 cannot get podsecuritypolicies.extensions at the cluster scope : exit status 1
```

This was the prometheus app, and Pod security policies were not turned on in this particular cluster.

Seems like we should have some kind of back off logic in these types of scenarios. Observing the application the error message was updating almost every second or so.

**Comment by StrongMonkey** [comment]
This is a general problem because the error we run into has some random string generated on each run (for catalog it is a temp file path), and the error is saved into database. This will cause controller to force update and ignoring backoff logic. Need to address that in the framework if possible.

**Comment by StrongMonkey** [comment]
The fix addresses two issues:
1. The error returned has random string. Those message have been sanitized.
2. Move lastAppliedTemplates to app revision. Since the applied template could have random string generated per run(for example mysql chart could have root passwd as a random generated string).

**Comment by bmdepesa** [comment]
rancher/rancher:v2.0.8-rc2

1. Launched an app with invalid permissions (invalid port on mysql)
Error message was sanitized and followed backoff.

2. Launched an app from a normal user (project member) w/ restricted permissions (user could not create pods). 
Error message was sanitized and followed backoff. 

In both cases, CPU & memory usage did not inflate.
