### ISSUE TITLE
Add UI support for project-level catalog

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#15104]

**Comment by hiscal2015** [comment]
project-level catalog is a very important feature, and can you also support authenticated git address or helm repo?

**Comment by superseb** [comment]
Auth for catalogs is tracked in https://github.com/rancher/rancher/issues/13371

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/18)
This new feature was validated in the UI. Testing was focusing on validating that we can have unique catalogs at global, cluster, and project levels and all the new UI elements including the new add catalog modal with the scope option. The app catalog was tested and HTTP was validated; general testing around catalogs and apps occurred in all relevant areas. A new test plan was created. One or more issues were entered and we are still fine-tuning this.
