### ISSUE TITLE
Add support for cluster level catalog

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#15106]

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/18)
This new feature was validated in the UI. Testing was focusing on validating that we can have unique catalogs at global, cluster, and project levels and all the new UI elements including the new add catalog modal with the scope option. The app catalog was tested and HTTP was validated; general testing around catalogs and apps occurred in all relevant areas. A new test plan was created. One or more issues were entered and we are still fine-tuning this.
