### ISSUE TITLE
Add UI for RKE settings default

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#15111]
https://github.com/rancher/rancher/issues/14948

**Comment by kinarashah** [comment]
@westlywright backend for this is in master

**Comment by tfiduccia** [comment]
In UI, on settings page - new setting added called cluster-defaults.  Waiting for #15256 to be fixed before validating UI.

**Comment by kinarashah** [comment]
@westlywright the pr got merged, ui would need to be updated to read from schema defaults for RKE fields

**Comment by alena1108** [comment]
Issue is related to configurable RKE template feature that got moved from 2.1 to 2.2
