### ISSUE TITLE
Should not show secondary launch configs when using "service with name" option in scheduler. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1511]
Server version - v0.27.0-rc3

Currently we show secondary launch configs as accepted values when using "service with name" option in scheduler. 

<img width="846" alt="screen shot 2015-07-13 at 12 11 52 pm" src="https://cloud.githubusercontent.com/assets/4266958/8658622/e2c81a26-2959-11e5-9e1a-7bb1064535f4.png">

We should not allow for the secondary launch configs to be referenced  by services outside of the service in which it is declared.

**Comment by vincent99** [comment]
@sonchang or @alena1108 Is this still relevant?  I thought I saw we removed the `io.rancher.service.primary.launch.config` labels.

**Comment by sonchang** [comment]
How are these values being queried?

**Comment by vincent99** [comment]
I just pull the sercive name labels from all the existing containers.

**Comment by sonchang** [comment]
The containers will still have those labels.  My changes was just to make it more convenient for the user when they specify the allocation affinity rules.

**Comment by westlywright** [comment]
This doesn't seem to happen anymore. Can you retest @tfiduccia?

**Comment by tfiduccia** [comment]
Sangeetha can you verify?

**Comment by sangeethah** [comment]
@westlywright , I am still able to reproduce this issue where sidekick containers are being presented in the service name drop down:

Following are the steps:

Created a service with "hello" and sidekick service - "sk" in "Default" stack.

"service with name" option in scheduler shows "Default/hello/sk" as one of the values to select in the dropdown.

<img width="1113" alt="screen shot 2016-03-16 at 10 44 41 am" src="https://cloud.githubusercontent.com/assets/4266958/13823049/48acb11c-eb65-11e5-99c4-228214f69bcf.png">

**Comment by vincent99** [comment]
@sangeethah I don't see a problem with this, they're valid services with valid labels that can be scheduled against.. The original problem was showing a bunch of ugly `io.rancher.service.primary.launch.config`s.

**Comment by sangeethah** [comment]
@vincent99 , since the host for primary service and its sidekick service are the same , there will not be a need to explicitly include sidekick services in the host scheduling for  "service with name" ? 
If i pick the sidekick service to schedule on a host with "service with name" option , service containers get deployed in the correct hosts as expected, so it is not a problem including sidekick services in the dropdown list.
