### ISSUE TITLE
When setting up Ceph Filesystem persistent volume values of secret aren't stored

### ISSUE THREAD

**Issue by jnk0** [rancher/rancher#15114]
**Rancher versions:**
rancher/server or rancher/rancher: latest (v2.0.7)
rancher/agent or rancher/rancher-agent: v2.0.7

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.11.1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
oVirt / RHEV

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Steps to Reproduce:**

1. Try to add persistent volume (PV) and choose 'Ceph Filesystem' as volume plugin.
2. Enter name, monitors, path and secret (name and optionally namespace) and username
3. Save

**Results:**
Values of fields name and namespace of secret aren't saved.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/29
Verified fixed
