### ISSUE TITLE
AD Login fails with "Invalid Credentials"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#15116]
Continuation from #14502 
@phertweck filed the original issue, but using the original issue to track the comments regarding AD with TLS and issues with certain certs

Connecting to AD without TLS: I used a service account to connect to AD. Testing the login with the service account is working, but testing it with an other user account is not working. I think that's the same effect @Nephelo is facing.

**Comment by deniseschannon** [comment]
@phertwerk @Nephelo
When trying to login with a different user name, is the "Default Login Domain" the correct domain. 

From the docs, ``` When you configure this field with the NetBIOS name of your AD domain, usernames entered without a domain (e.g. “jdoe”) will automatically be converted to a slashed, NetBIOS logon (e.g. “LOGIN_DOMAIN\jdoe”) when binding to the AD server. If your users authenticate with the UPN (e.g. “jdoe@acme.com”) as username then this field must be left empty.
```

Can you try adding the domain in front of the username that you want to authenticate with to see if that solves the issue? 

Also, what version of Rancher are you running? I know we've released a couple of versions since the ticket was originally filed.

**Comment by Nephelo** [comment]
@deniseschannon Thank you for your response. I'm running Rancher 2.0.7.

For the User Search Base I added `DC=my,DC=domain,DC=de` and provided a service account (without domain). Using the service account in the test section works.

When testing an other user I tried to enter the following: `myuser`,`my.domain.de\myuser` and `myuser@my.domain.de` without success.

**Comment by phertweck** [comment]
I've also tried it with Rancher 2.0.6 with the same effect.

**Comment by mrajashree** [comment]
Hi @phertweck I see in the original issue you had left this comment https://github.com/rancher/rancher/issues/14502#issuecomment-404502991 where it seems you got it to work?
```
We managed to configure the AD without TLS. Removing the default login domain and only entering the user name did the trick.
```
So were you using the service account when this worked or was it a normal user?
If it only worked for service account and not for the other user, can you please try this query for the other user
```
ldapsearch -H ldap://server -x -D "loginDomain\testUsername" -W -b "UserSearchBase" -s sub "(&(sAMAccountName=testusername)(objectClass=person))"
```

**Comment by mrajashree** [comment]
@Nephelo from the  example you gave, this `my.domain.de\myuser` format doesn't look right for logging in, can you try using `my\myuser`
@phertweck If we refer to the same example, User Search Base: DC=my,DC=domain,DC=de, then if you're trying to login by providing login domain as prefix, then the username should be my\myuser and not my.domain.de\myuser

**Comment by phertweck** [comment]
@mrajashree Thank you for the explanation. Using `my` as default login domain did the trick (now using 2.0.8). So it was a configuration mistake on my side.

For further reference: I just noticed that there's a description in the [docs](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/ad/) how to configure AD.

**Comment by mrajashree** [comment]
@phertweck that's great. 
Closing this issue, feel free to open a new issue if there are other problems with auth

**Comment by creatica-soft** [comment]
From another server:

ldapsearch -h ads-dctl01-lata.a.local -p 389 -W -D 'CN=StrongviewProd-Ldap,OU=Service Accounts,DC=A,DC=local' -x -b 'DC=A,DC=local'
Enter LDAP Password:
ldap_bind: Invalid credentials (49)
        additional info: 80090308: LdapErr: DSID-0C090446, comment: AcceptSecurityContext error, data 52e, v2580

The same error is seen in appserver.log of Message Studio.

So there must be something wrong with StrongviewProd-Ldap account or the password in the password vault is not correct.
