### ISSUE TITLE
Feature Request: Choose Availability Zone for EKS

### ISSUE THREAD

**Issue by siosphere** [rancher/rancher#15119]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.6
rancher/agent or rancher/rancher-agent: -

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

When setting up a new cluster in AWS it allows you to choose region, but not availability zones of the nodes. I was unable to setup an EKS cluster through the UI as AWS returned an error that there was not enough capacity in the given AZ. With no option to change the AZ I had to create the cluster directly in AWS and then import it into Rancher.

**Comment by guangbochen** [comment]
EKS is currently only supported in the US East (N. Virginia) US West (Oregon) regions, and you can select both of them in rancher as below, each AZ only allows maximum 3 clusters, and it is the AWS limitation. 
![snip20180820_1](https://user-images.githubusercontent.com/4569037/44318937-8aaf4b80-a46b-11e8-8f76-bd4a30f26476.png)
And for the node templates, you can define as many as you like in different regions.
![image](https://user-images.githubusercontent.com/4569037/44319080-46707b00-a46c-11e8-80ee-08d17bee7c74.png)
