### ISSUE TITLE
Importing cluster in v2.0.7 is failing with `unknown user anonymous` error

### ISSUE THREAD

**Issue by s1113950** [rancher/rancher#15121]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.7
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): `v1.10.2-gke.3`

**Docker version: (`docker version`,`docker info` preferred)**
`Docker version 18.06.0-ce, build 0ffa825`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`uname -r`: `4.4.0-122-generic` Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Ran `sudo docker run -d --privileged --restart=unless-stopped -p 8080:80 -p 443:443 rancher/rancher:latest` on the node and then set the Rancher Server URL to the `server` url here in `kubectl config view`
```
- cluster:
    certificate-authority-data: REDACTED
    server: https://XXXXXXXX
  name: XXXXX
```

**Results:**
I went to the `import cluster` button in rancher here: https://127.0.0.1:8081/g/clusters/add?provider=import
and it told me to run this `kubectl` command to import my cluster:
`kubectl apply -f https://XXXXXXXX/v3/import/BIGLONGSTRING.yaml

The apply command wasn't working so I went to the yaml url and found this:
```
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "forbidden: User \"system:anonymous\" cannot get path \"/v3/import/BIGLONGSTRING.yaml\": Unknown user \"system:anonymous\"",
"reason": "Forbidden",
"details": {},
"code": 403
}
```

**Comment by superseb** [comment]
How is the cluster created that you are trying to import?

**Comment by s1113950** [comment]
It is one from GKE

**Comment by s1113950** [comment]
I had the correct permissions to access it because I was able to create a new cluster in GKE using rancher, just not import the existing cluster

**Comment by deniseschannon** [comment]
@s1113950 If you are still facing issues with a more modern version, please open a new issue.
