### ISSUE TITLE
Using "container with name" scheduling option fails when container name has capital letters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1512]
Server version - V0.27.0-rc3

I had an environment with name - "TEST" and server with name - test123

When I tried to deploy a service with scheduling policy  host must have "container with name" - "TEST_test123_1" , it gets created with following affinity rule:

Affinity	io.rancher.scheduler.affinity:container	test_test123_1 

Since container name was changed to lower case , placement fails.

**Comment by sonchang** [comment]
@vincent99 Did we want to make the check for container names case insensitive too?  I only made the checks for host labels and container labels case insensitive (not container names)

**Comment by vincent99** [comment]
Yes I think those should be insensitive too.

**Comment by sonchang** [comment]
Fixed in release after  rancher/server:v0.27.0-rc4

**Comment by sangeethah** [comment]
Tested with build from master:
Affinity scheduling policy host must have "container with name" is case insensitive now.
