### ISSUE TITLE
Start_once container starts more than once

### ISSUE THREAD

**Issue by sebastianwahn** [rancher/rancher#15130]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.20
rancher/agent or rancher/rancher-agent: v1.2.10
Cattle:  v0.183.60
User Interface: v1.6.45
Rancher CLI: v0.6.11
Rancher Compose: v0.12.5

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.7
network-services: v0.7.19
scheduler: v0.8.2
-kubernetes (if applicable):-

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 18
 Running: 18
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.47-56.37.amzn1.x86_64
Operating System: Amazon Linux AMI 2018.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.792GiB
Name: ip-10-0-3-60
ID: 2W52:Z6JZ:L7EH:7CIM:R67N:D6MH:STVW:FLBZ:AXI2:GFB4:OSUB:OOTE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.14.47-56.37.amzn1.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external db (RDS)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Setup a container marked as start_once.

docker-compose snippet:
```
  installer:
    image: alpine:3.8 # does not matter
    stdin_open: true
    command:
    - echo "runs" # or any other command
    tty: true
    labels:
      io.rancher.container.pull_image: 'always'
      io.rancher.container.start_once: 'true'
```
rancher-compose snippet:
```
installer:
    scale: 1
    start_on_create: true
```

**Results:**
The container will run exactly every 1 hour and 15 minutes.

I added a bash script which creates logfiles when the installing (of the installer container) started and ended. This will produce the following logfiles:

```
-rw-r--r--    1 root     root            83 Aug 17 18:12 installer_run_2018-08-17_18:04:55.log
-rw-r--r--    1 root     root            83 Aug 17 19:27 installer_run_2018-08-17_19:20:04.log
-rw-r--r--    1 root     root            83 Aug 17 20:42 installer_run_2018-08-17_20:34:58.log
-rw-r--r--    1 root     root            83 Aug 17 21:57 installer_run_2018-08-17_21:50:02.log
-rw-r--r--    1 root     root            83 Aug 17 23:12 installer_run_2018-08-17_23:05:03.log
-rw-r--r--    1 root     root            83 Aug 18 00:28 installer_run_2018-08-18_00:20:05.log
-rw-r--r--    1 root     root            83 Aug 18 01:43 installer_run_2018-08-18_01:35:15.log
-rw-r--r--    1 root     root            83 Aug 18 02:57 installer_run_2018-08-18_02:50:09.log
-rw-r--r--    1 root     root            83 Aug 18 04:12 installer_run_2018-08-18_04:05:19.log
-rw-r--r--    1 root     root            83 Aug 18 05:27 installer_run_2018-08-18_05:20:12.log
-rw-r--r--    1 root     root            83 Aug 18 06:43 installer_run_2018-08-18_06:35:22.log
-rw-r--r--    1 root     root            83 Aug 18 07:58 installer_run_2018-08-18_07:50:17.log
-rw-r--r--    1 root     root            83 Aug 18 09:13 installer_run_2018-08-18_09:05:18.log
```

Another container I recently set up also marked as start_once but also sheduled with the rancher-cron has the same behaviour.

**Comment by sebastianwahn** [comment]
@vincent99 I'm sorry, i might added to little information here.

I have a _second_ container (called backup, to backup stuff) which is indeed sheduled with rancher-cron (this is the one referenced as "another container"). The cron should only run at 21:00 (label: `cron.schedule: "0 0 21 * * *"`). But in fact, it runs also whenever it wants.

To sum it up:
* one container *without* rancher-cron
* one container *with* rancher-cron

My backup container has these logs entries:

```
-rw-r--r-- 1 root root   77 Aug 17 19:19 backup_run_2018-08-17_19:19:56.log
-rw-r--r-- 1 root root   77 Aug 17 20:34 backup_run_2018-08-17_20:34:58.log
-rw-r--r-- 1 root root   77 Aug 17 21:00 backup_run_2018-08-17_21:00:00.log  <---- the only valid one
-rw-r--r-- 1 root root   77 Aug 17 21:50 backup_run_2018-08-17_21:50:01.log
-rw-r--r-- 1 root root   77 Aug 17 23:05 backup_run_2018-08-17_23:05:03.log
-rw-r--r-- 1 root root   77 Aug 18 00:20 backup_run_2018-08-18_00:20:05.log
-rw-r--r-- 1 root root   77 Aug 18 01:35 backup_run_2018-08-18_01:35:07.log
-rw-r--r-- 1 root root   77 Aug 18 02:50 backup_run_2018-08-18_02:50:09.log
-rw-r--r-- 1 root root   77 Aug 18 04:05 backup_run_2018-08-18_04:05:10.log
-rw-r--r-- 1 root root   77 Aug 18 05:20 backup_run_2018-08-18_05:20:21.log
-rw-r--r-- 1 root root   77 Aug 18 06:35 backup_run_2018-08-18_06:35:14.log
-rw-r--r-- 1 root root   77 Aug 18 07:50 backup_run_2018-08-18_07:50:24.log
-rw-r--r-- 1 root root   77 Aug 18 09:05 backup_run_2018-08-18_09:05:17.log
```

But in fact, it should only run at 21:00 (according to the shedule).

Im aware of the fact, that start-once does imply I can manually start those containers. Although I don't do it manually.

**Comment by sebastianwahn** [comment]
Some further observations:

My second backup container has since yesterday a explicit label: 1.0.1 as version instead of the implicit latest label. Now it does not run every 1h 15m anymore.

Have to check if it gets triggered when it should run via the cron-schedule. 

Maybe the start_once feature somehow checks every 1h 15min if there is a new latest and runs in any case?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
