### ISSUE TITLE
Setting up anti-affinity for service with scheduling rule - host mush not have service with name=env name/service name does not work.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1513]
Server version - V0.27.0-rc1

Steps to reproduce the problem:
Create service with  scheduling rule - host mush not have service with name set to itself by using the format env name/service name.
Containers of the service does not honor the anti-affinity rule set.

**Comment by will-chan** [comment]
We need to minimally support past affinity rules with stack/service syntax.

**Comment by sangeethah** [comment]
Tested with Server version - V0.27.0-rc4

We are able to set anti-affinity for services with scheduling rule set as "host must not have service with name=env name/service name"
