### ISSUE TITLE
how can i upgrade the  service by the rest api ?

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#15137]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.20` Cattle: `v0.183.60` UI: `v1.6.45` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by xaka** [comment]
Take a look at https://github.com/etlweather/gaucho. It's great example of how to use available REST API for various purposes.

**Comment by superseb** [comment]
Best way is to use the Rancher CLI, but there are some API examples here: https://forums.rancher.com/t/upgrade-rancher-service-using-rest-api/1459/13
