### ISSUE TITLE
[2.0][AWS] Rancher server tries to connect to the cluster using Public IP instead of Private IP

### ISSUE THREAD

**Issue by niranjan94** [rancher/rancher#15138]
**Rancher versions:**
rancher/server or rancher/rancher: `2.0.7`
rancher/agent or rancher/rancher-agent: `2.0.7`

**Infrastructure Stack versions:**
kubernetes : `v1.11.1`
provider: `AWS EC2`

**Docker version:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel:** 
`Linux ip-172-10-1-100.ap-southeast-1.compute.internal 4.14.32-rancher2 #1 SMP Fri May 11 11:30:31 UTC 2018 x86_64 GNU/Linux`

**Type/provider of hosts:** `AWS`

**Setup details:** `single node rancher`

---

**Description:**

- By default the `rancher-nodes` security group created by Rancher during cluster creation has public access for port `6443`. 
- We restricted it to be accessible within the VPC only (ie. would require access via the VPC-level private IP address)
- But once the change is done, Rancher server displays an error:

	 ```
	could not contact server: Get https://<public-ip>:6443/version
    ```
- _**As you can see, rancher server tries to use the public IP to connect. How can we make rancher to use the private IP instead ?**_

**Comment by loganhz** [comment]
Can you try to set the `server-url` to the private IP of Rancher server?

You can edit it via global -> settings ->server-url

**Comment by jhughes2112** [comment]
For what it's worth, I'd like to see each cluster be given a server-url override.  That way you could set multiple IPs that should be used to connect with Rancher, and take advantage of multi-cloud management where traffic is routed through the cheapest interface first.  Changing the server-url as you suggested forces ALL clusters to use the private IP, in which case you can't manage an external cluster, right?
