### ISSUE TITLE
give a kubectl access to project for a user

### ISSUE THREAD

**Issue by csilaser** [rancher/rancher#15139]
Hi, hope it's the right place, and I'll be thankfull for any clue for a solution.
I created a project on Rancher, and I want to give a user to access onl this project with **kubectl**

which config file should i give the user ?

for example, this is my config file, but it's for the whole cluster : 

`  apiVersion: v1
kind: Config
clusters:
 name: "bla-ros-cluster"
  cluster:
    server: "https://bla-ros-mgr.cisco.com/k8s/clusters/c-6vvkt"
    api-version: v1
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akNDQ\
      WRhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFvTVJJd0VBWURWUVFLRXdsMGFHVXQKY\
    21GdVkyZ3hFakFRQmdOVkJBTVRDV05oZEhSc1pTMWpZVEFlRncweE9EQTRNRGN4TWpJd01qVmFGd  zB5T0RBNApNRFF4TWpJd01qVmFNQ2d4RWpBUUJnTlZCQW9UQ1hSb1pTMXlZVzVqYURFU01CQUdBM\QTJxU28vdFNTRWhQdFJwRHEKNnM1Rlgxa3VIYzVUZk50K2Jic3hsOENTeFdUdjk3VmxzY\
XhvK2l4b2FtM2VZRnJNdTRub2ltRVlmaSt1cjdSWgpLaHRlbnhrWllYbHQyS0xhclo0Z2tFMEZDT\
TkY1M0JWWTc2TFRxSXFOVm1mL25mUnVHc2cxCjBIR\1BUHdJS1cxdGhGYlg2MGdTUkFacEdBRGpMMEZZSzdEQVhQWkhDeDVTa2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="

users:
- name: "user-kws56n"
  user:
    token: "kubeconfig-user-kws56n:nkffdf5rstjmrxkjqwxjwt8ccmsvqnhzpvqrdk69hmpdg8z66g97rc"

contexts:
- name: "bla-ros-cluster"
  context:
    user: "user-kws56n"
    cluster: "bla-ros-cluster"

current-context: "bla-ros-cluster" `

so how am I giving the kubeconfig file **for a project** 
also, for the user I created (that needs to use the project), i can see only the Token (and it's very long), and not the CA....

sorry for the mess, I'm lost here
Thanks in advance !

**Comment by deniseschannon** [comment]
If that user logs in, they will be able to get their own kubeconfig file for the projects they are part of.
