### ISSUE TITLE
Create cluster fails while trying to verify candidate authority certificate "kube-ca"

### ISSUE THREAD

**Issue by tboemker-bkfs** [rancher/rancher#15136]
Attempt to create cluster fails:
[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [10.86.241.12]. Response code: [401], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401} , log: E0819 18:51:55.129928 1 authentication.go:62] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority, x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-ca")]; exit status 1, error: You must be logged in to the server (the server has asked for the client to provide credentials)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.7` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
Please provide steps to reproduce, see https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions

What kind of cluster, what kind of nodes? Are nodes re-used? If so, are the locations mentioned in https://rancher.com/docs/rancher/v2.x/en/faq/cleaning-cluster-nodes/ cleaned before re-using?

**Comment by superseb** [comment]
Let us know if we can help investigate.
