### ISSUE TITLE
Rancher should allow you to backup/restore etcd in worker clusters

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#15149]
RKE currently provides the `rke etcd` utilities to allow snapshot-save and snapshot-restore operations against clusters it manages. However, Rancher currently does not support snapshot/restore of etcd within it's UI.

We should provide a UI/ability to take snapshots/restore snapshots (and configure etcd-snapshot cron) in worker clusters, which would help users define better disaster-recovery solutions for using Rancher with their Kubernetes clusters.

**Comment by alena1108** [comment]
Closing in favor of existing issue https://github.com/rancher/rancher/issues/13688

**Comment by firasalkafri** [comment]
Take a look at this: https://github.com/Salalem/rancher-s3-backup
