### ISSUE TITLE
nginx-ingress : public and private network with HA

### ISSUE THREAD

**Issue by corentin59** [rancher/rancher#15140]
**Rancher versions:**
rancher/rancher:v2.0.7

**Infrastructure Stack versions:**
network-services: canal (with option canal_iface: eth0)
provider: on premise

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
Ubuntu
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
On-Premise - OVH - With private network
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Cluster build with RKE in HA.

**Steps to Reproduce:**
I have 3 nodes (controlplance, etcd, worker) :

- Node 1 - eth0 (private  - 172.16.20.1) and eth1 (public, ipfailover 188.165.xxx.xxx)
- Node 2 - eth0 (private - 172.16.20.2)
- Node 3 - eth0 (private - 172.16.20.3)

**Results:**
My cluster is up, rancher ui respond on 443 and 80 without default backend and ssl issues). All pods are in Running state.

My problem is on the node1, the nginx-ingress bind all eth on the host.

![image](https://user-images.githubusercontent.com/2035983/44333504-42922800-a46f-11e8-81a5-b34baf43d230.png)

If I check the configuration of nginx :
![image](https://user-images.githubusercontent.com/2035983/44333639-aa487300-a46f-11e8-83a5-6826d9b14777.png)

Listen is applied on all eth, in my case eth0 and eth1. But the eth1 is a public eth and I want install another lb on the eth1 (public interface). In the nginx doc, no key for bind only one interface nginx.ingress.kubernetes.io/*.

Any idea ?
Thx !

**Comment by corentin59** [comment]
Similar to #15138 ?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13828
