### ISSUE TITLE
Error while getting agent config: invalid response 504:

### ISSUE THREAD

**Issue by digitalassembly** [rancher/rancher#15143]
**Rancher versions:**
rancher/rancher:2.0.6
rancher/agent or rancher/rancher-agent:

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
UBUNTU 16.04.4 LTS (Xenial Xerus)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS  EC2 c5.large

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher with 3 nodes

**Steps to Reproduce:**
I was using rancher 2.0.6 on HA setup using RKE on AWS (3 nodes, all roles). I had 1 extra cluster setup and several pods running perfectly for couple of weeks. However, after a recent update on my private catalog app, rancher UI just became unavailable with 500 or 503 errors. Below are the details how it happened:

1. I deployed a custom catalog with some YAML modifications and due to parsing error it started showing lot of errors on rancher UI
2. few minutes later, rancher UI was down, giving 503 or 500 errors
3. I restarted one of the rancher server nodes as I couldn't ssh to it
4. after restart, checking the kubelet logs for the restarted node, it showed that it had just installed rancher version 2.0.7 (probably because when I setup RKE, I used tag : latest)
5. I decided to then restart the other 2 nodes, which eventually also got updated to 2.0.7
6. I still can't access RANCHER UI, the k8s_agent_cattle-node-agent container on all nodes shows

**Results:**
time="2018-08-20T12:27:30Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-08-20T12:27:30Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-08-20T12:27:40Z" level=info msg="Connecting to wss://rancher-prod.test.xxx.com/v3/connect with token gp28bsqbrr7wmn2rzblrqzl5jgbg25rx5j4z76fs64bqk4cd8lk8jc"
time="2018-08-20T12:27:40Z" level=info msg="Connecting to proxy" url="wss://rancher-prod.test.xxx.com/v3/connect"
time="2018-08-20T12:27:40Z" level=info msg="Starting plan monitor"
time="2018-08-20T12:30:10Z" level=info msg="Error while getting agent config: invalid response 504: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.13.8</center>\r\n</body>\r\n</html>\r\n"
time="2018-08-20T12:38:45Z" level=info msg="Error while getting agent config: invalid response 504: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.13.8</center>\r\n</body>\r\n</html>\r\n"

Thanks

**Comment by superseb** [comment]
Can you share the YAML that triggered the situation? Looks like a machine ran out of memory, then it also upgraded after. Possibly hitting https://github.com/rancher/rancher/issues/15146

**Comment by superseb** [comment]
Let me know if you can provide the requested information and check the options in https://github.com/rancher/rancher/issues/15146
