### ISSUE TITLE
Upgrade from 2.0.6 to 2.0.7 breaks cluster when kubernetes system components like kube-system are located in a project

### ISSUE THREAD

**Issue by ajfriesen** [rancher/rancher#15146]
**Rancher versions:**
rancher/rancher:v2.0.7

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.5

**Docker version: (`docker version`,`docker info` preferred)**
```ubuntu@ip-172-22-1-115:~$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
docker info
Containers: 23
 Running: 14
 Paused: 0
 Stopped: 9
Images: 15
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1065-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: ip-172-22-1-115
ID: VQXR:ABN6:TM6O:OXKO:TZO4:653A:UONV:4XCV:S2V3:7TM2:HT2S:VTRC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
uname -r
4.4.0-1065-aws
```

**Type/provider of hosts:**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

* HA Rancher with default ingress enabled
* NLB as entrypoint

**Environment Template:**

Kubernetes

**Steps to Reproduce:**

We had a Rancher cluster with v2.0.6.
The config had rancher/rancher:latest in the cluster.yaml and did a automatic upgrade. (Our fault!)

After the update cluster A did work fine.
Cluster B did not work and had network issues.

Reason:
Someone did move some system components to a project which is not the default.
Because only then you can get more information about the system components via the rancher 2 UI.
This is not possible when the components do not have a project.

**Results:**
The upgrade from 2.0.6 to 2.0.7 did create a System project on Cluster A.
The Cluster B on the other hand did not not move the components to the System project, because there where in another project.

**Comment by krishofmans** [comment]
Also ran into this issue, as we used to already have a "System" like project to view some internal details more easily. Moving or turning of network isolation fixes things.

**Comment by kinarashah** [comment]
Hi @ajfriesen, 
thank you @niranjan94 and @krishofmans, your analysis is correct. 

In 2.0.7, we introduced the concept of System Project, and one of the reasons for this was that you mentioned (you need to have system namespaces in a project for debugging through UI). 

This also means that now, network policies won't be created "only" for System Project namespaces. But since your system namespaces were already a part of project, they will behave identical to any other normal project and traffic would be blocked. 

Workaround - move these namespaces to System Project manually. 
Or for users who don't want network isolation at all, you can edit the cluster and turn `Project Network Isolation` off. 

We'll add some more info in docs for upgrade.

**Comment by loganhz** [comment]
Please see https://github.com/rancher/rancher/issues/15146#issuecomment-424251395

**Comment by mpasdziernik** [comment]
Just installed a fresh 2.1.1 and created a cluster of type "custom" with project network isolation enabled and canal. DNS was not reachable from pods. After moving namespaces to system project as mentioned above it worked.

**Comment by Angelinsky7** [comment]
Hi @superseb, 
i'm sorry but i do not understand what i need to do to have 'Project Network Isolation enabled' and my pods reaching themselves inside the same project... If i activate the settings, for example, the Wordpress Helm from Library is unable to access the myql database though the 'service discovery'.
Could please, guide me, or tell me what i should do, to have the settings enable and the pods working.
Thanks a lot for you support

**Comment by Angelinsky7** [comment]
sorry for the noise, after reinstalling everything, it's working normally... i should have some bad config.
