### ISSUE TITLE
Cluster provisioning stuck on nodes waiting to register with Kubernetes

### ISSUE THREAD

**Issue by tboemker2** [rancher/rancher#15144]
I created a cluster and added six nodes: three with all roles and three workers. Two of the nodes with all roles are stuck in the Registering state with the message Waiting to register with Kubernetes.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.7` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
Can you supply the info requested in the template and the steps to reproduce (Were the nodes added at the same time, or directly after, in what order were they added, what is in the logging of the `rancher/rancher` and `rancher/rancher-agent` containers?)

**Comment by Toxicable** [comment]
Im having the same issue, slightly different environment though.
1 system (bare metal)
server - `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --name=rancher rancher/rancher`
agent - `sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes --name=rancher-worker -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://serveraddress --token sometoken --ca-checksum somechecksum --worker`

To reproduce: 
- start server 
- make custer, select custom
- copy agent command and run on same system
- wait for "waiting for node to register" message

Under Nodes on the server I see "Registering" "Waiting to register with Kubernetes" for the agent i've deployed. So it's definately connected to the server

agent logs:
```
INFO: Arguments: --server https://serveraddress --token REDACTED --ca-checksum somechecksum --worker
INFO: Environment: CATTLE_ADDRESS=someaddress CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=somename CATTLE_ROLE=,worker CATTLE_SERVER=https://serveraddress CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: ...
WARN: Loopback address found in /etc/resolv.conf, please refer to the documentation how to configure your cluster to resolve DNS properly
INFO: https://serveraddress/ping is accessible
INFO: Value from https://serveraddress/v3/settings/cacerts is an x509 certificate
time="2018-09-11T20:45:58Z" level=info msg="Rancher agent version v2.0.8 is starting"
time="2018-09-11T20:45:58Z" level=info msg="Option controlPlane=false"
time="2018-09-11T20:45:58Z" level=info msg="Option worker=true"
time="2018-09-11T20:45:58Z" level=info msg="Option requestedHostname=stratus"
time="2018-09-11T20:45:58Z" level=info msg="Option customConfig=map[address:someipaddress internalAddress: roles:[worker] label:map[]]"
time="2018-09-11T20:45:58Z" level=info msg="Option etcd=false"
time="2018-09-11T20:45:58Z" level=info msg="Listening on /tmp/log.sock"
time="2018-09-11T20:45:58Z" level=info msg="Connecting to wss://serveraddress/v3/connect/register with token sometoken"
time="2018-09-11T20:45:58Z" level=info msg="Connecting to proxy" url="wss://serveraddress/v3/connect/register"
time="2018-09-11T20:45:58Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-09-11T20:45:58Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-09-11T20:46:08Z" level=info msg="Connecting to wss://serveraddress/v3/connect/register with token sometoken"
time="2018-09-11T20:46:08Z" level=info msg="Connecting to proxy" url="wss://serveraddress/v3/connect/register"
time="2018-09-11T20:46:08Z" level=info msg="waiting for node to register"
time="2018-09-11T20:46:10Z" level=info msg="waiting for node to register"
time="2018-09-11T20:46:12Z" level=info msg="waiting for node to register"
time="2018-09-11T20:46:14Z" level=info msg="waiting for node to register"
... repeated over ag over
```

**Comment by superseb** [comment]
A cluster needs at least one etcd and one controlplane node before workers gets provisioned. We have an issue on better guidance for that.

**Comment by Toxicable** [comment]
@superseb Ah righto, I will look into those thanks

**Comment by Toxicable** [comment]
Ah, yeah I just looked over the guide again and I missed the part: 
>From Node Role, select all the roles: etcd, Control, and Worker.

https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/

After adding those extra roles in it worked straight away

**Comment by tboemker-bkfs** [comment]
I created all of the nodes immediately after creating the cluster, using these commands in this order:

DOCKER_HOST=app1:2376 DOCKER_TLS_VERIFY=1 docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://util1 --token 2qt877cbjhc9swr2fh8p6ql6sv25kz6cgg8l6kd5wv7fdq68mttt94 --ca-checksum c75353e5b1c467670900f9f4860606aef997bd06ffd1e6555150775ccac3a21c --worker --etcd --controlplane
4730f1463ff97a03a36826433f6be42a775ae36233a65771cbfd9a8a58e5e973

DOCKER_HOST=app2:2376 DOCKER_TLS_VERIFY=1 docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://util1 --token 2qt877cbjhc9swr2fh8p6ql6sv25kz6cgg8l6kd5wv7fdq68mttt94 --ca-checksum c75353e5b1c467670900f9f4860606aef997bd06ffd1e6555150775ccac3a21c --worker --etcd --controlplane
0f8b47703f1b96661cb34ae1d7bed22970a198980d8a904942c845d92efdb16c

DOCKER_HOST=app3:2376 DOCKER_TLS_VERIFY=1 docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://util1 --token 2qt877cbjhc9swr2fh8p6ql6sv25kz6cgg8l6kd5wv7fdq68mttt94 --ca-checksum c75353e5b1c467670900f9f4860606aef997bd06ffd1e6555150775ccac3a21c --worker --etcd --controlplane
6f454a6f506b303f46b457c28cccf3045084c9d507efdd11c66ce2a4da1c906f

DOCKER_HOST=app4:2376 DOCKER_TLS_VERIFY=1 docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://util1 --token 2qt877cbjhc9swr2fh8p6ql6sv25kz6cgg8l6kd5wv7fdq68mttt94 --ca-checksum c75353e5b1c467670900f9f4860606aef997bd06ffd1e6555150775ccac3a21c --worker
192f3d01910c763833fb27930991e25b3bb800c03ae1546b65d88e8b29dc433f

DOCKER_HOST=jasper1:2376 DOCKER_TLS_VERIFY=1 docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://util1 --token 2qt877cbjhc9swr2fh8p6ql6sv25kz6cgg8l6kd5wv7fdq68mttt94 --ca-checksum c75353e5b1c467670900f9f4860606aef997bd06ffd1e6555150775ccac3a21c --worker
c4017593749c0e72767e17c331d2ad1bbc684083c4ea9d797ebd7a6d6800e363

DOCKER_HOST=jasper2:2376 DOCKER_TLS_VERIFY=1 docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://util1 --token 2qt877cbjhc9swr2fh8p6ql6sv25kz6cgg8l6kd5wv7fdq68mttt94 --ca-checksum c75353e5b1c467670900f9f4860606aef997bd06ffd1e6555150775ccac3a21c --worker
043a744d10057304df8161e02fa1f5459285f7ea4c816f4f2aa83a4f8916eb34

In this case, I did not allow any time between one command and the next. That matters; I've found that if I allow two minutes or so in between, the issue usually does not occur.

Hosts app2-dev400 and app3-dev400 are stuck at "Waiting to register with Kubernetes." The other hosts are all Active.

The attached logs.zip contains the output of "docker ps" for each host and the logs from each container.
[logs.zip](https://github.com/rancher/rancher/files/2375489/logs.zip)
