### ISSUE TITLE
Rancher 1.6: Best Practice when the IP Address/Network Environment changes often?

### ISSUE THREAD

**Issue by gallexme** [rancher/rancher#15157]
**Rancher versions:**
rancher/server: 1.6.17
rancher/agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.6
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.7.20
scheduler: rancher/scheduler:v0.8.3
**Docker version: (`docker version`,`docker info` preferred)**
docker-ce=18.03.0~ce-0~ubuntu 
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.5 LTS (Xenial Xerus)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher-server/rancher-agent on same machine
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
1. install rancher-server and agent like single Node guide
2. starts some stacks to see if working
3. change ip of machine 
4. change host registration url in webui of rancher
5. change registration url in agent: sudo docker run       --rm     --privileged     -v /var/run/docker.sock:/var/run/docker.sock     -v /var/lib/rancher:/var/lib/rancher     rancher/agent:v1.2.10 http://NEW_IP:8080/

**Results:**
All stacks repeatedly restart and the ui shows: Timeout getting IP address after some minutes and then restarts them again

**Comment by superseb** [comment]
It doesn't automatically re-create needed services as of today, see https://github.com/rancher/rancher/issues/9307. 

Workaround steps are described here: https://gist.github.com/superseb/f44d51cc42c7e5a0049d393d6d2563e7

Using a DNS name and LB is still recommended.

Let me know if you run into issues.

**Comment by gallexme** [comment]
cant use a DNS Name as it will be a dedicated server moving between companies physicly, where the DNS record might not beeing able to be set(big less dynamic companies dns entries are very strict and often need weeks for changes)

also the systems are airgapped so no internet access etc maybe 1-3 pcs got access to that server

how would i go about setting up a loadbalancer on that single node machine so that it and rancher server & agent survives  ip changes, any infos?

**Comment by superseb** [comment]
It's the same problem with the LB on the same node, as the DNS to the LB will also be incorrect when the IP changes. This is in general an unsupported scenario, if you can explain a bit more what you are trying to accomplish, we can give better advice. Rancher is not a tool that needs to be moved around company locations, it's setup using DNS/LB once and then hosts get registered to it and containers can be orchestrated.

The scenario you are pointing out is applicable to any application you want to make available, where the IP is changing and there is no DNS that can be configured.

**Comment by gallexme** [comment]
@superseb 
Scenario is:
Airgapped Rancher 1.6 with changing IPAddresses(cause its moved between IT infrastructure physicly, like for dev purposes its inside companies network, and while meetings/exhibitions cause its in a isolated network for showing purposes etc)

We preconfigure those Rancher Servers "here", send them to Research Partners were they have to be integrated into their IT Infrastructure, but they cant have the same IP Address as they had it "here", as wew cant guarantee that the research partners have exactly this IP Address reserved for those Servers,

so we have to have/find a way to change IP Addresses in Rancher so that Rancher comes up with the new IP after System Reboots,

as the Servers arent always in a company network were u allowed to set DNS Records for those Servers
DNS wont work :/ also the DNS name would then be to be changeable as there might be multiple of those in the same network
