### ISSUE TITLE
Replace ranchers nginx ingress

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#15159]
Just a short question:

Since you're forking the official nginx-ingress, the question arises, did you made any changes to it? I would guess you did, since the rancher delivered version is not quite up to date. If there are changes made, what do they impact?

**Comment by wzrdtales** [comment]
Asking since the latest one has some additions to make nginx better monitorable.
See
https://github.com/kubernetes/ingress-nginx/commit/1542a12764b32cb026a62a35e9160583fbc97dc2#diff-fba9ab9a671472f9de07ebbe5cacf938

**Comment by superseb** [comment]
The source can be found here, including the commits that have been done and the relation to the issue that was solved: https://github.com/rancher/ingress-nginx/commits/nginx-0.16.x-fix

We always ship with a complete set of versions that are tested, and those can be a few versions behind latest. I've created https://github.com/rancher/rancher/issues/15163 for updating it to the latest in the next full release.
