### ISSUE TITLE
Rancher becomes inaccessible after running for a couple days

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#15151]
**Rancher versions:**
rancher/rancher: v2.0.4

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Results:**
After some time 502 errors are thrown, eventually the rancher console fails until we stop/start the container. Kubectl also fails with 502.

I have logs to share directly.

**Comment by alena1108** [comment]
@aemneina can we get the logs and the details of the setup - how many clusters/nodes, how much CPU/RAM the master node has, what is the number of user workloads running

**Comment by alena1108** [comment]
@aemneina can we also check if there is some sort of lb/firewall/proxy in between the management server and the user clusters. Something that might be impacting the connections, and expose their leak.

**Comment by aemneina** [comment]
Do you have anything fronting your rancher server, say firewall appliance, reverse proxy, load balancer…
Rancher is running behind nginx (running on same machine, not in container)

How many clusters are managed by this rancher, pods per cluster if you have it:
8 Clusters, about 100 pods per cluster

Can we track connections on the rancher server? Using `cat /proc/net/nf_conntrack | wc -l` or `conntrack -L | wc -l`
We can work on setting some tracking up.

We’d like to enable debug mode logging on the system [0]. possibly after a restart
We can look at enabling after restart

Allow for the lock up to happen one more time and collect a goroutine dump. [1]
This is less sure, we really don't want to have the lock up happen. We've been periodically restarting to hopefully prevent this.

**Comment by pjmazenot** [comment]
I don't know if it's related but I had the same issue sometimes since 2.0.2 because of the auto update. Some containers would stay blocked with an old version while the new one was trying to run (eg. agent 2.0.6 and 2.0.8).

Restarting docker or the node allowed the container to refresh properly. I didn't have the issue since completing the last update.

**Comment by aemneina** [comment]
I also have a goroutine dump from when the server stops responding.

**Comment by alena1108** [comment]
@aemneina qa hit an issue with somewhat similar symptoms
We root caused it as the maximum number of open files for the rancher-server container being set too low (1024). You can see that number by running `ulimit -a` from inside the container. Typical number is ~1,000,000. The qa were installing docker via `snap` which we think was changing that setting. Can you what the number is its a docker daemon setting, just to see if you might be hitting the same thing
