### ISSUE TITLE
Refactor Ldap-based Auth

### ISSUE THREAD

**Issue by carolynhu** [rancher/rancher#15164]
Since AD and OpenLdap/FreeIpa are both ldap-based auth, they shares some common code. When I implemented OpenLdap/FreeIpa, I applied some good suggestions about coding styles and naming patterns, etc. I want to make AD also follow them, what I mainly want to do is:
1. don't use string concatenation for query string
2. passing ldapv2.Conn down, do not create a ldap connection for every function 
3. extract common function: i.e. ldap.AttributesToPrincipal()
4. simplify some code path, i.e. delete userRecord() function in AD, by moving result.Entries piece of code up into loginUser() func, and then directly call getPrincipalsFromSearchResult() func
5. simplify the ldap.GetGroupSearchAttributes() and ldap.GetUserSearchAttributes() func by only passing one parameter, i.e. config *v3.ActiveDirectoryConfig
6. delete some unnecessary functions: 
(1) ldap.EscapeLDAPSearchFilter in ldap_util.go file, we can use what exists in ldap library, i.e. ldapv2.EscapeFilter 
(2) delete getUserSearchAttributes() func and getGroupSearchAttributes() func, I add them because previously I want to make FreeIpaConfig can call those functions by converting FreeIpaConfig's value into LdapConfig based on OpenLdap implementation, now we do not need to do it. We can pass LdapConfig directly

What need to be tested:
After this refactor, we should make sure all the AD and OpenLdap/FreeIpa Auth works as it is.

**Comment by cjellick** [comment]
@carolynhu can you add a better description of what this is, why we're doing it, and what would need to be tested?

**Comment by carolynhu** [comment]
my uniqueid issue https://github.com/rancher/rancher/issues/13434 rely on this refactor so I move it to 2.1

**Comment by carolynhu** [comment]
@sangeethah For testing this issue, you only need to make sure ldap-based auth (i.e. AD, OpenLdap/FreeIpa) works as it is by run jenkins jobs, I will create OpenLdap and FreeIPA jobs for you.

**Comment by carolynhu** [comment]
@sangeethah @bmdepesa I've created AD, OpenLdap and FreeIpa Jenkins Jobs with the latest master build. Please run them to verify this issue.

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/7

All automated tests are passing for AD, OpenLDAP, and FreeIPA.
