### ISSUE TITLE
Validate k8s 1.11.2 - Default version in 1.6.22

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#15161]

**Comment by soumyalj** [comment]
K8s Automation runs k8s:v1.11.2-rancher1-2 succeeded with no new issues on the following configurations:

docker-1.12.x - RancherOS	
docker-1.12.x - rhel-7.3  - native - aws	
docker-1.12.x - rhel-7.3  - upstream - aws	
docker-1.12.x - rhel-7.4  - native - aws		
docker-1.12.x - ubuntu 14.04		 
￼docker-1.12.x - ubuntu 16.04-aws	
docker-1.13.x - rhel-7.4  - native - aws	￼		 
￼docker-17.03.x - RancherOS	
docker-17.03.x - rhel-7.4  - upstream - aws

P1 tests for RBAC enabled K8s setup and K8s setup with cloud provider set to AWS succeeded.
