### ISSUE TITLE
`helm template --notes` does not also specify setValues causing catalog app deployment to fail if catalog template uses "required"

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#15167]
With helm chart templates that have `{{required "Value is Required" .Values.exampleval }}`in them, Rancher will fail to deploy the helm chart when it tries to generate notes, as it does not call `helm template --notes` with the setValues properly.

On this line: https://github.com/rancher/rancher/blob/master/pkg/controllers/user/helm/common.go#L191 setValues appended to the command

whereas here: https://github.com/rancher/rancher/blob/master/pkg/controllers/user/helm/common.go#L206 it is not

**Comment by sangeethah** [comment]
Able to reproduce this issue when deploying "5-bigip-ctlr" app from catalog -https://github.com/F5Networks/charts.git. App fails to deploy and is stuck in "Installing" state with error - ```Installing
Helm template --notes failed. Error: render error in "f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml": template: f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml:5:4: executing "f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml" at <required "BIG-IP url...>: error calling required: BIG-IP url not specified - add to Values or pass with `--set` : exit status 1```

With v2.0.8-rc4, Able to deploy "5-bigip-ctlr" app from catalog -https://github.com/F5Networks/charts.git successfully.
