### ISSUE TITLE
503 every hour on some projects

### ISSUE THREAD

**Issue by firaskafri** [rancher/rancher#15179]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.0.7

**Infrastructure Stack versions:**
kubernetes (if applicable):  v1.11.1 

**Steps to Reproduce:**

The projects were setup a week ago and worked perfectly since then, for the last 24 hours two projects out of 5 have been systematically going 503 every hour. cabot logs show 503 at the 37th minute of every hour then back again with no interference in 60 mins

**Comment by LiamMartens** [comment]
Experiencing a similar issue where it stops working after a day or so and starts returning 503 errors on the ingress. The service works correctly and I can usually get it to work again by re-adding the ingress rules. I would very much like to see this issue resolved and if any input is necessary I would be happy to help.

**Comment by firasalkafri** [comment]
@LiamMartens Any updates with the issue from your side?

**Comment by LiamMartens** [comment]
@firasalkafri I was able to work around it by manually creating a service with a query on label using kubectl and using this service in the ingress.

**Comment by deniseschannon** [comment]
@firaskafri @LiamMartens Let me know if you are still having issues on a modern version of Rancher as a lot has changed since v2.0.7.
