### ISSUE TITLE
Azure AD UI should hide URL options by default

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#15175]
`Endpoint`, `Graph Endpoint`, `Token Endpoint`, and `Auth Endpoint` are all standard URLs that almost everyone wants to be the defaults (with the given application ID in the URL).  So the UI should hide them and just generate what they want by default.

```
Endpoints
(x) Standard
( ) China *
( ) Custom (same 4 input options as now)
```

*: if we know these, @loganhz ?

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/27
Not fixed - issues:

- [ ] Too much space between the radio options
![image](https://user-images.githubusercontent.com/11514927/44676651-bb9dfc00-a9e8-11e8-804b-e3e2f688cc95.png)

- [ ] Endpoint options are supposed to be hidden unless you pick custom
![image](https://user-images.githubusercontent.com/11514927/44676687-d83a3400-a9e8-11e8-83fc-29a603096550.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/29
Verified fixed
