### ISSUE TITLE
rancher 2.0  rancher/rancher can support istio 1.0.0

### ISSUE THREAD

**Issue by damozhiying** [rancher/rancher#15183]
Automatic injection not working in my Rancher env
https://github.com/istio/istio/issues/8096

**Comment by david-maumenee** [comment]
Yes it works ! see https://github.com/rancher/rancher/issues/15182

**Comment by superseb** [comment]
https://github.com/rancher/rancher/issues/15182 / https://github.com/rancher/rancher/issues/14032
