### ISSUE TITLE
EKS - Unable to select subnets

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#15184]
**Rancher versions:**
2.0.7

**Steps to Reproduce:**
1. Create EKS cluster
2. Select Custom: Choose from your existing VPC and Subnets

**Results:**
Unable to click on "Next: Select Subnets"

![image](https://user-images.githubusercontent.com/5138838/44469804-4a300900-a5f6-11e8-8e42-16b4a7142646.png)

**Comment by superseb** [comment]
Can you check if you are hitting https://github.com/rancher/rancher/issues/15008

**Comment by nxf5025** [comment]
Ah yes confirmed that is the exact issue I am facing. Thanks!

**Comment by superseb** [comment]
Thanks, this will be fixed in the next release: https://github.com/rancher/rancher/issues/15008
