### ISSUE TITLE
derive a way to get rke version a server is using

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#15192]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent:

I see from my server log it launches this tool to get rke on it:
`Successfully pulled image [rancher/rke-tools:v0.1.13] on host`
not at all sure what version rke its using or if that tool is pinned down to a specific rke version. halp!

**Comment by deniseschannon** [comment]
As rancher relies heavily on rke, having an easy way to know what version of rke is being used in rancher is necessary

**Comment by sangeethah** [comment]
With latest build from master:
We have a new settings - rke-version which currently gives the latest rke commit.

With Release builds , this should be set to rke version.
