### ISSUE TITLE
Can't reset UI password

### ISSUE THREAD

**Issue by Dani-D** [rancher/rancher#15190]
I want to reset the initially set UI password.
I tried those two possibilities, that both don't worked out..

Unable to find the following values to reset via temporary mysql auth deactivation:

```
mysql> update setting set value="false" where name="api.security.enabled";
mysql> update setting set value="" where name="api.auth.provider.configured";
```

Unable to access this builtin function:
`docker exec -it <rancher-server-container-id> password-reset`

Error-Output:
```
[rancher@Cluster-Master-Cloud-01 ~]$ docker exec -it 406e25c8db39 reset-password
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"reset-password\": executable file not found in $PATH"
```

Is there any other way to reset the UI initially set password?
Thank you for your support.

**Comment by superseb** [comment]
You are mixing 1.6 and 2.x commands, are you sure the container with id `406e25c8db39` is using the `rancher/rancher` (2.x) and not the `rancher/server` (1.6) image?
