### ISSUE TITLE
Rancher Launched Kubernetes with weave network plugin?

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#15194]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.7

Hi, 

Since RKE supports weave plugin, and Rancher 2.0 relies on RKE for "Rancher Launched Kubernetes", is this correct? But I can't see weave network support from Rancher 2.0 UI by creating custom cluster, why?

![networkprovider](https://user-images.githubusercontent.com/15604715/44502626-ecb6bd80-a6c4-11e8-904e-4fd1721186dc.jpg)

**Comment by superseb** [comment]
See https://rancher.com/docs/rancher/v2.x/en/faq/#will-rancher-v2-0-support-calico-contiv-contrail-flannel-weave-net-etc-for-embedded-and-imported-kubernetes, those three are currently supported.

Regarding support in Rancher 2.x, see https://github.com/rancher/rancher/issues/12909
