### ISSUE TITLE
Please Help running rancher agents on ARM CPU RockPro64

### ISSUE THREAD

**Issue by justinengland** [rancher/rancher#15204]
**Rancher versions:**
rancher/rancher:
rancher/rancher-agent:

Versions can be found if needed but most of the tools were custom compiled to get rancher to work at all

**Infrastructure Stack versions:**
healthcheck: 
ipsec: 
network-services: 
scheduler: 
kubernetes (if applicable): 

#####################

**Docker version: (`docker version`,`docker info` preferred)**
root@rockpro64:~# docker version
Client:
Version:           18.06.1-ce
API version:       1.38
Go version:        go1.10.3
Git commit:        e68fc7a
Built:             Tue Aug 21 17:32:42 2018
OS/Arch:           linux/arm64
Experimental:      false

Server:
Engine:
 Version:          18.06.1-ce
 API version:      1.38 (minimum version 1.12)
 Go version:       go1.10.3
 Git commit:       e68fc7a
 Built:            Tue Aug 21 17:30:47 2018
 OS/Arch:          linux/arm64
 Experimental:     false
root@rockpro64:~# docker info
Containers: 22
Running: 10
Paused: 0
Stopped: 12
Images: 12
Server Version: 18.06.1-ce
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
seccomp
 Profile: default
Kernel Version: 4.4.132-1075-rockchip-ayufan-ga83beded8524
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: aarch64
CPUs: 6
Total Memory: 3.785GiB
Name: rockpro64
ID: XXXXXXXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
oot@rockpro64:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@rockpro64:~# uname -r
4.4.132-1075-rockchip-ayufan-ga83beded8524

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Baremetal RockPro64

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher 2.0
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes  and Cattle 
**Steps to Reproduce:**
Install Docker on Rockpro 64 and try to attach to rancher as a node

Followed this thread to see if we could use the community answers. https://github.com/rancher/rancher/issues/4703 Did not work because of a JVM error in docker

Following the instructions here
https://gist.github.com/ags131/7bdde11c932ef7a54f44c6decbfd88b8

We get to the portion where the node is seen by rancher but running kubectl apply -f config.yaml does not work. 

**Results:**

rancher 1.6 docker error is

root@rockpro64:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@rockpro64:~#
root@rockpro64:~# uname -r
4.4.132-1075-rockchip-ayufan-ga83beded8524
https://github.com/rancher/rancher/issues/4703
https://gist.github.com/ags131/7bdde11c932ef7a54f44c6decbfd88b8
Step 6/41 : RUN java -version
---> Running in 6597cac55028
/bin/sh: 1: java: not found
The command '/bin/sh -c java -version' returned a non-zero code: 127

rancher 2.0 error is

The node never shows up as registered after executing the kubectl command.

**Comment by superseb** [comment]
Probably the best way to get support on a community gists is to respond to the gist with your errors. We can't provide support on that.

For 1.6, it won't be added (https://github.com/rancher/rancher/issues/4703). And for 2.x we have https://github.com/rancher/rancher/issues/15180 open to decide if and when ARM support will be provided.

I think the output you are sending is incomplete, as I see `uname -r` output and then a `docker build` step (Seeing the output from 1.6) and nothing from 2.x.

If there is any blocking code in 2.x that prevents you from getting further, let me know.
