### ISSUE TITLE
AKS - VM size list is not up to date 

### ISSUE THREAD

**Issue by david-maumenee** [rancher/rancher#15200]
**Rancher versions:**
2.0.7

**Steps to Reproduce:**
In Rancher 2, create a new AKS cluster and display the VM size list.
Check in the Azure Portal the VM size avalaible in the AKS creation UI

**Results:**
The VM list displayed in Rancher UI doesn't match the list displayed in Azure Portal, for exemple **B2s**

**Feature request**
It will be great if Rancher UI could display the actual VM Size list corresponding to the location via an Azure API call.

**Comment by bmartin13** [comment]
I second this... especially since changing the VM size after provisioning is not supported.

**Comment by superseb** [comment]
This should be fixed in v2.1: https://github.com/rancher/rancher/issues/15412
