### ISSUE TITLE
Add link in EC2 AMI option to point to AMIs for RancherOS

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1520]
It would be nice to add a link in the EC2 screen to allow people to quickly link to the RancherOS AMIs so that they could use them. 

Currently, we only list AMIs in our README in the os repo.

Link: 
https://github.com/rancher/os/blob/master/README.md/#user-content-amazon

Also: examples in text boxes should recommend RancherOS AMI instead of ubuntu and the ssh username as "rancher".

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
Link has been added
