### ISSUE TITLE
No system workloads show in web UI when not using default port 80/443

### ISSUE THREAD

**Issue by lizhiyong2000** [rancher/rancher#15215]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent:v2.0.7

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.12.1-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1、docker run --restart=unless-stopped -d -p 9080:80 -p 9443:443 rancher/rancher:v2.0.7
2、Add cluster for current host pc
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
No system workloads show in web UI, when run with docker run --restart=unless-stopped -d -p 80:80 -p 443:443 rancher/rancher:v2.0.7, the system workloads appear.

**Comment by superseb** [comment]
I can't reproduce this, can you describe what image you are using, what network situation and can you share screenshots of what is shown?

<img width="360" alt="screen shot 2018-08-24 at 10 06 33" src="https://user-images.githubusercontent.com/2620179/44572940-95c4ed00-a785-11e8-9548-71b492ce412c.png">
<img width="518" alt="screen shot 2018-08-24 at 10 06 47" src="https://user-images.githubusercontent.com/2620179/44572946-98274700-a785-11e8-983e-0f592cc479f6.png">

**Comment by lizhiyong2000** [comment]
I have switched to the default port already, so there were no screenshot any more, but the phenomenon is when select system in the cluster, no workloads show.

I have already provided the image I used, but I think the version does not matter, I have tried multiple version such as  v2.0.4, v2,0.5, v2.0.6, v2.0.7 and v2.0.8.rc4, and I use a single same Ubuntu 18.04 pc to run the server and the cluster agent.
When the problem occurs, if I deploy  something by a yaml file, I can't choose the defult namespace from the  existed namspaces list, the default namesapce does not appear in the list.

**Comment by superseb** [comment]
The `System` project is only shown in v2.0.7. The system namespaces are attached to the `System` project, so deploying something in the `System` project is limited to the attached namespaces (or newly created if you want to). The `default` namespace is in the `Default` project, so you need to be in the `Default` project if you want to use the `default` namespace.

If you have exact steps to reproduce the issue, please put them here so I can use them to reproduce the issue.

**Comment by lizhiyong2000** [comment]
Today this problem came to me again, and finally I found where the problem came from, It was because that the namespace system doesn't belong to the project system, after  moving the system namespace to the project system, the workloads showed.
