### ISSUE TITLE
Delete catalog doesn't delete template and template version

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#15212]
**Rancher versions:**
ancher/rancher:v2.0.7

**Steps to Reproduce:**
Delete a catalog.

**Results:**
The templates and templateVersions are not deleted.

**Comment by sangeethah** [comment]
Tested with v2.0.8-rc5

1. Add 1 cluster to the setup.

2. From Global option , add a custom catalog.

3. Go to any project with in the cluster and try to launch any application from this catalog. All templates from the added catalog are presented.

4. Delete this catalog.

5. Go to any project within the cluster and list all the catalog entries by going to "Catalog Apps" ->launch option . Templates that were present in the deleted catalog is not listed anymore.


When testing the same use case in 2.0.7, even after the custom catalog was deleted ,  templates that were present in the deleted catalog is still listed in step 5.
