### ISSUE TITLE
Cluster can't connect due to `does not look like an x509 certificate`

### ISSUE THREAD

**Issue by stefanfritsch** [rancher/rancher#15222]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.0.7

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.5-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
See below

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: Bare-metal**

**Setup details: HA-rancher with external cluster**

**Steps to Reproduce:**

1. Create custom cluster on bare-metal servers from an existing rancher.
2. Reboot rancher
3. Cluster is unavailable

**Results:**

Cluster is unavailable. Its status remains at `waiting for cluster agent to connect`.

`docker logs` of `rancher/rancher-agent:v2.0.7`:

```INFO: Arguments: --server https://kubernetes.stablab.de --token REDACTED --ca-checksum REDACTED --no-register --only-write-certsINFO: Environment: CATTLE_ADDRESS=159.69.91.228 CATTLE_AGENT_CONNECT=true CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=kubernetes-3 CATTLE_SERVER=https://kubernetes.stablab.de CATTLE_TOKEN=REDACTED CATTLE_WRITE_CERT_ONLY=trueINFO: Using resolv.conf: nameserver 213.133.100.100 nameserver 213.133.98.98 nameserver 213.133.99.99INFO: https://kubernetes.stablab.de/ping is accessibleERROR: Value from https://kubernetes.stablab.de/v3/settings/cacerts does not look like an x509 certificate (unable to load certificate 139785535807936:error:0906D06C:PEM routines:PEM_read_bio:no start line:../crypto/pem/pem_lib.c:691:Expecting: TRUSTED CERTIFICATE)```

**Note:**

1. The cluster of the ha-rancher installation itself comes back online as expected.
1. I had no end of trouble because I had to change the URL of the rancher installation and the change wasn't properly propagated. I don't know if this is related.
2. As mentioned elsewhere as well, the kube-config file I get from the UI does not have the proper certificates as well. It's full of HTML characters like `&#43;`

## Docker version

For rancher:

```
Containers: 143
 Running: 68
 Paused: 0
 Stopped: 75
Images: 69
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.81 GiB
Name: se-august
ID: WULV:N6MH:ZNUO:NK7V:TXUH:2QOH:PAU4:ODZP:V27R:X5BD:N3KK:JM5F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: stefanfritsch
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by superseb** [comment]
Can you describe the steps to reproduce in more detail? Both first steps are not accurate enough to know what is being done. See https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions

```
Create custom cluster on bare-metal servers from an existing rancher.
Reboot rancher
```

How is `rancher/rancher` started? Is the cacerts file passed to the container? What is it's contents? The logline just below what you pasted shows the retrieved value, can you share that as well?

**Comment by stefanfritsch** [comment]
Hi,

**EDIT:** There seems to be a bug in Rancher2, but the actual error is down to an error on my part. I had to change the URL of rancher and issue a new cacert. When I did that I forgot to base64 encode. 

I changed the URL and the cacert in the UI in the global settings but this change constantly reverts back to the wrong certificate. I.e. I change cacerts in the UI, everything works for a few hours and then it resets to the old (broken) certificate.

I don't know if you remember but we already talked about the issue with the ineffective settings page in Rancher2 a few weeks ago. At that time it was about the wrong URL. If you change the server-url setting it doesn't work. You have to edit the cattle-node-agent daemonset (and cattle-cluster-agent) manually.

Regarding the steps to reproduce, I should have been more specific but it's actually more or less complete - I just hadn't remembered the part about the broken certificate:

1. The rancher installation is a  ha-rancher cluster and it's setup following your guide on a ha-installation [here](https://rancher.com/docs/rancher/v2.x/en/installation/ha/) using a self-signed certificate but without base64 encoding it.
2. Fix the certificate via the UI.
2. Create custom cluster on bare-metal servers from an existing rancher: I opened the UI, clicked "add cluster", selected "custom cluster", left everything on default and ran the resulting command with all roles enabled on all nodes:

```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.7 --server https://kubernetes.stablab.de --token [...] --ca-checksum […] --etcd --controlplane --worker
```

3. This worked fine until the ha-rancher cluster had to be restarted. Now it reports the error with the certificate and the certificate is broken. I assume because the certificate was OK when the cluster was created but had reverted to its broken state by the time of the restart.

The rest of the error is here:
```
ERROR: Retrieved cacerts:
╔╔
  ║ 0E1
       0H��╗  ═╚U╝═╗DE10═╚U

Some-State1!0═╚U╝
180719112857Z21180625112857Z0E1
                               0     ═╚U╝═╗DE10═╚U

Some-State1!0═╚U╝
╔╔╔║ ╚�╔ 0�╔dgits Pty Ltd0�╔"0
╗�╔╔ �%\�V\�Y�R�����`��4_�D[�
��a���}|�}/�Ɉ����G╔�
                    ��x��#
                          ��A��F0���TEIY�:\fS�1G:��5═�^═��/�P� �r�����Kj
╔╔
  ║ ╚�╔╔ �DF�ʈ�F�Շ*@�╔z�_�)u|M�ܴ9*l��║s��(╚};6�%%�-O�s��݀�h����ڛ�V0J5��B
                                                                      sc,L�m�o$n��3�;W�?�3�0Et(t�4����|��w%��5����C�����l�\�M��$f ӔP��K�4���G}�J�����{�u��0��o�z�!0═╚╔�FDwn�R�_�Z�Y8�║(�:#]g¦�,�║����═-'�}i��t���U��Jڙ�
Md9�,����P�޷��>n
```

**Comment by superseb** [comment]
For changing certificates we have https://github.com/rancher/rancher/issues/14731 open, for changing the cacerts value I created https://github.com/rancher/rancher/issues/15273.

Let me know if that does not cover the reported issue.
