### ISSUE TITLE
Secure internal registries

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#15226]
The internal registry is accessed via nodeport now.
For security, we should:
1. add the proxy to make sure it is only accessible to the cluster nodes in insecure mode.
2. add authentication.
3. add TLS support with self-signed certs.

**Comment by gitlawr** [comment]
cc @cloudnautique

**Comment by cjellick** [comment]
@cloudnautique looks like this is awaiting your review?

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/5

Pipeline is using proxy to connect to registry, using the authentication, and generated certs.
