### ISSUE TITLE
Change from default Self-signed certificate to Signed certificate

### ISSUE THREAD

**Issue by sobbspt** [rancher/rancher#15223]
**Rancher versions:** 2.0.6
rancher/rancher
rancher/rancher-agent

**Infrastructure Stack versions:**
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: 18.06.1-ce**

**Operating system and kernel: 3.10.0-862.9.1.el7.x86_64**

**Type/provider of hosts: Bare-metal**

**Setup details: single node rancher, internal DB**

**Environment Template: Kubernetes**

**Steps to Reproduce:**

1. Start rancher with default Self-signed certificate
```
sudo docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 --name rancher2-nossl \
  -v /data/rancher:/var/lib/rancher \
  rancher/rancher:v2.0.6
```
2. Create cluster
3. Add node to the cluster
4. Stop Rancher
5. Start Rancher with Signed certificate 
```
sudo docker run -d --restart=unless-stopped \
    -p 80:80 -p 443:443 --name rancher2-ssl \
    -v /data/rancher:/var/lib/rancher \
    -v /data/cert.pem:/etc/rancher/ssl/cert.pem \
    -v /data/key.pem:/etc/rancher/ssl/key.pem \
    rancher/rancher:v2.0.6 --no-cacerts
```
**Results:**
Found error log on Rancher server

```
2018/08/24 08:53:17 [INFO] 2018/08/24 08:53:17 http: TLS handshake error from <<NODE_IP>>: remote error: tls: bad certificate
```

How to update Rancher certificate from Self-signed certificate to Signed certificate ?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/14731
