### ISSUE TITLE
Can I retrieve my rancher agent

### ISSUE THREAD

**Issue by memwey** [rancher/rancher#15224]
Hi,
I carelessly delete all the data in my rancher server. Nodes are not on the server baremetal so they are still providing service. Is there any way I can set up a new rancher server and get the nodes back?

**Comment by superseb** [comment]
Not sure what version you are on. For 1.6, all state is in the MySQL database and can only be rebuild using this state. The only way to get information back to rebuild if you don't have the database is to manually inspect the containers and retrieve configured details (environment variables etc).

For 2.x, all state is in etcd. If this state is lost, you can use the same approach (inspect the containers). Possibly there is a backup/state on the other etcd nodes (if you have more than 1).

**Comment by memwey** [comment]
I'm using rancher 2.x
I import the kubernetes cluster with "From my own existing nodes" and get them back. But it seems that I'm no longer able to add note through rancher.
