### ISSUE TITLE
change the rancher/nginx-ingress-controller default port

### ISSUE THREAD

**Issue by damozhiying** [rancher/rancher#15225]
hi:
     i had change the rancher/nginx-ingress-controller workload the http/https port (9080/9081),
and create a ingress for workload xxx,  when i reques the http://ip:9080/  show success ,  but the workload 
external endpoint show 80,not change to 9080,how to change the workload show correct endpoint

**Comment by loganhz** [comment]
Please try the following steps.

1. Change the ingress ports by editing the nginx-ingress-controller DaemonSet.

```
kubectl edit daemonset nginx-ingress-controller -n ingress-nginx
```

2. Scroll down to the section that looks like this:
```
     containers:
      - args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx-configuration
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
        - --annotations-prefix=nginx.ingress.kubernetes.io
```

3. Add two lines after "- /nginex-ingress-controller" modifying the ports as you see fit.

```
        - --http-port=8080
        - --https-port=8443        
```

4. Save changes to your config then delete your ingress-nginx pods
