### ISSUE TITLE
the curated Catalog App Prometheus fails to launch with "failed parsing --set data: key ..."

### ISSUE THREAD

**Issue by sdanieru** [rancher/rancher#15232]
Hello,
My first attempt to launch an app via the Catalog. Upon attempting to launch the 'curated' app Prometheus, the launch fails with the error: 

`Helm template failed. Error: failed parsing --set data: key "Frableaz5" has no value (cannot end with ,) : exit status 1`

Since I'm new to deploying apps from the Catalog, perhaps I'm missing a prerequisite, or are others getting the same failure?

**Rancher version**
rancher/rancher:v2.0.7

**Docker version: (`docker version`,`docker info` preferred)**
docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-131-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Attempt to install 'Prometheus' from the curated Catalog App

**Results:**
`Helm template failed. Error: failed parsing --set data: key "Frableaz5" has no value (cannot end with ,) : exit status 1`

**Comment by stieler-it** [comment]
When trying to install a completely different chart I had the impression that using a value with comma "," fails - I think helm uses comma as separator between values so Rancher would have to escape it.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14551
