### ISSUE TITLE
Project Permissions - AKS - Not functioning

### ISSUE THREAD

**Issue by billabongrob** [rancher/rancher#15230]
**Rancher versions:**
2.0.7

**Infrastructure Stack versions:**
AKS v1.11.2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure AKS

**Steps to Reproduce:**
Running Active Directory for authentication.  Deploy an AKS cluster via Rancher 2.x.  Deploy a project, deploy a workload.  Add a user to the Members of the project, Member or Owner.  

**Results:**
Expected:  Added owner or member can see individual workloads.  
Actual:  They cannot see deployed workloads.

![screen shot 2018-08-24 at 1 03 01 pm](https://user-images.githubusercontent.com/8441943/44600318-8bfbb380-a79e-11e8-922a-42f50e8f050a.png)

![screen shot 2018-08-24 at 1 04 58 pm](https://user-images.githubusercontent.com/8441943/44600374-b8afcb00-a79e-11e8-9978-f103b8b30ca0.png)

**Comment by maxkorp** [comment]
Confirmed.

**Comment by cjellick** [comment]
@dramich to validate

**Comment by dramich** [comment]
Steps to repro:
Run rancher server v2.0.7
Add a local and AKS cluster
Create a new user user1
Create workloads in both clusters
Add user1 as a member to both projects
Login as user1
user1 can see workloads in local cluster but not the AKS cluster


Validated on master 9/12/18
user1 is able to see and deploy workloads in AKS cluster
