### ISSUE TITLE
Error configuring LDAP for JumpCloud

### ISSUE THREAD

**Issue by andrewwyatt** [rancher/rancher#15249]
When configuring Rancher 2.0.8 to use JumpCloud LDAP for authentication, it errors out.  The same configuration and authentication user account works fine when applied to Rancher 1.x.

**Rancher versions:**

```
rancher/rancher: 2.0.8
rancher/rancher-agent: 2.0.8
```

**Infrastructure Stack versions:**

```
kubernetes (if applicable): v1.11.2-rancher1
```

**Docker version: (`docker version`,`docker info` preferred)**

```
$ sudo docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-74.git6e3bb8e.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      6e3bb8e/1.13.1
 Built:           Tue Aug 21 15:23:37 2018
 OS/Arch:         linux/amd64

$ sudo docker info
Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-74.git6e3bb8e.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      6e3bb8e/1.13.1
 Built:           Tue Aug 21 15:23:37 2018
 OS/Arch:         linux/amd64
 Experimental:    false
Containers: 47
 Running: 30
 Paused: 0
 Stopped: 17
Images: 17
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 5eda6f6fd0c2884c2c8e78a6e7119e8d0ecedb77 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 7.639 GiB
Name: cdc0004.lab.fewt.com
ID: 6UYK:C6QC:EHFF:BVNR:FWKI:7CKG:NOOG:GCZO:ZE4M:CMG2:BIHC:MT43
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -r
3.10.0-862.11.6.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Custom, deployed to managed VMWare VMs.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single server Rancher, multiple agents.  Internal DB.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

K8s

**Steps to Reproduce:**

```
Select Global
Select Security -> Authentication
Select OpenLDAP (or FreeIPA)

Hostname: ldap.jumpcloud.com
Port: 636 TLS
Add the SSL Certificate: Run 'echo -n | openssl s_client -connect ldap.jumpcloud.com:636 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/jumpcloud.chain.pem' and attach
DN: uid={USER},ou=Users,o={GID},dc=jumpcloud,dc=com
Search Base: ou=Users,o={GID},dc=jumpcloud,dc=com
```

Test by using an LDAP user.

**Results:**

A 'Error (undefined - undefined)' message occurs, and a 'TestAndApply Error' popup appears on screen.  The configuration does not save, as it does not authenticate.

**More Information:**

The JumpCloud LDAP documentation can be found here if needed: https://support.jumpcloud.com/customer/portal/articles/2439911-using-jumpcloud-s-ldap-as-a-service

**Comment by superseb** [comment]
I have configured JumpCloud successfully before. You don't need the cert as its a certificate from a recognized CA but it shouldn't hurt the process either. Did you grant BIND privileges to both users that are configured (Service Account and test user)? Can you share debug logging from the `rancher/rancher` container when you enable authentication? (https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-enable-debug-logging)

**Comment by andrewwyatt** [comment]
> I have configured JumpCloud successfully before. You don't need the cert as its a certificate from a recognized CA but it shouldn't hurt the process either. Did you grant BIND privileges to both users that are configured (Service Account and test user)? Can you share debug logging from the `rancher/rancher` container when you enable authentication? (https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-enable-debug-logging)

That was the problem, I was testing authentication using a non-bound account.
