### ISSUE TITLE
cattle-cluster-agent https://localhost:20443/ping is not accessible

### ISSUE THREAD

**Issue by BDataAndy** [rancher/rancher#15242]
INFO: Environment: CATTLE_ADDRESS=10.1.0.101 CATTLE_CA_CHECKSUM=255e3dccaf6b103d93ac296301b16650ecf94277c73919be75bbb4d638021c7a CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-7547d7dd49-8qrm8 CATTLE_SERVER=https://localhost:20443
INFO: Using resolv.conf: nameserver 10.96.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
ERROR: https://localhost:20443/ping is not accessible (Failed to connect to localhost port 20443: Connection refused)

**Comment by loganhz** [comment]
Close as inactive

**Comment by dhiruLeo** [comment]
i am trying to import a minikube cluster to rancher and cattle-cluster-agent pod getting crashloopbackoff error ...and getting the same error when in check the logs of those pods ...

**Comment by sureshsankaran** [comment]
@dhiruLeo  
am facing same issue. Any workaround or fixes ?

**Comment by beolson001** [comment]
I also have this issue. Any workaround or fixes ?

**Comment by shiyangtao** [comment]
I also have this problem

**Comment by AndriyKalashnykov** [comment]
Same issue when deployed on GKE with rancher-agent:v2.4.2:
---------
INFO: Environment: CATTLE_ADDRESS=10.60.6.7 CATTLE_CA_CHECKSUM=19fe270bb4288bb634806dd750943559ca0d45b8596b416f7017f407f53aa825 CATTLE_CLUSTER=true CATTLE_FEATURES=dashboard=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-754994b956-hqclv CATTLE_SERVER=https://localhost
INFO: Using resolv.conf: nameserver 10.64.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local c.kube-testing-262302.internal google.internal options ndots:5
ERROR: https://localhost/ping is not accessible (Failed to connect to localhost port 443: Connection refused)

**Comment by souravb11** [comment]
Same issue with localhost.

**Comment by nagarajuch304** [comment]
Same issue for my case also 
![image](https://github.com/rancher/rancher/assets/99852945/3b3a4db8-14bc-48bd-9885-7641f3d81811)
