### ISSUE TITLE
Changing setting "engine-iso-url" does not apply

### ISSUE THREAD

**Issue by sybnex** [rancher/rancher#15247]
**Rancher versions:**
2.0.7

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Red Hat Enterprise Linux Server 7.5 (Maipo)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Steps to Reproduce:**
- Change the setting engine-iso-url to a custom one 
- build new cluster with vSphere Driver

**Results:**
Rancher still tries to download the image from the internet:
```
2018/08/27 10:25:38 [INFO] stdout: (xxxx-3) Image cache directory does not exist, creating it at management-state/node/nodes/xxxx-3/cache...
2018/08/27 10:25:38 [INFO] stdout: (xxxx-3) Downloading management-state/node/nodes/xxxx-3/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros-vmware.iso...
2018/08/27 10:25:41 [INFO] stdout: (xxxx-3) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
```
Instead of the configured one. I tried HTTP as well as HTTPS on non-standard ports (e.g. 8080/8443)
Rancher would be able to get the iso from the Internet, vSphere wouldn't.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue in Rancher 2.3, and we'll reopen it
