### ISSUE TITLE
[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck

### ISSUE THREAD

**Issue by Dani-D** [rancher/rancher#15241]
`./rke_linux-amd64 up`

fails with:

`FATA[0062] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check http://localhost:10252/healthz for service [kube-controller-manager] on host [IP]: Get http://localhost:10252/healthz: Unable to access the service on localhost:10252. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: E0826 04:08:39.922556       1 memcache.go:138] couldn't get current server API group list; will keep using cached value. (Get https://127.0.0.1:6443/apis?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)) `

Can anyone think of a solution to this kind of problem?
Thanks a lot :)

**Comment by superseb** [comment]
Can you file issues in the rke repository here: https://github.com/rancher/rke/issues/new and fill in the requested info in the template?

In this case, adding the output of `docker ps -a` on that host will help as well.
