### ISSUE TITLE
Database grows quickly as we don't clean purge a couple of tables

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1525]
Need to make performance enhancements to purge tables when appropriate as database gets massive quickly due to lack of cleanup.

First issue on this: #1355

**Comment by cusspvz** [comment]
+1
We are experiencing issues because there are tables (events, processes and related with those) which spare some GB each.

**Comment by deniseschannon** [comment]
We have added (a couple of releases ago) for Rancher to clean up the `events` and `process_instances` table. @cusspvz You might need the cleanup to occur more frequently. 

http://docs.rancher.com/rancher/faqs/troubleshooting/#rancher-server-database-is-growing-too-quickly

**Comment by cusspvz** [comment]
Thanks @deniseschannon 
cc @fernandoneto

**Comment by baillieny** [comment]
Can you please confirm if the settings here http://docs.rancher.com/rancher/faqs/troubleshooting/#rancher-server-database-is-growing-too-quickly work in Rancher v1.1.3?
We have had our Rancher server running for over 2 weeks now but there are still events from when the server was started in the following tables:

container_event, ervice_event and process_instance

Thanks for your help

**Comment by deniseschannon** [comment]
Yes, the settings still workin in v1.1.3. It doesn't completely remove all the contents in the database, but cleans up anything older than a specific time frame.
