### ISSUE TITLE
Enable a way to see workloads launched in a namespace that don't belong to a project

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#15254]
As a Rancher user, I would come across many applications on github etc which provide Kubernetes manifest(yaml) files to try out on a cluster. When I do `kubectl apply -f` against those files, various namespaces are created, workloads are launched, ingress objects are created to access them. But when I go into the Rancher UI, there is no way to see any of the stuff created in the previous step unless I create a project and move the namespace that belongs to the application under that project.

On a related note, this [issue](https://github.com/rancher/rancher/issues/15139) brings up an important point on how to specify that a namespace belongs a project in kubernetes manifest files?

I tried adding a label: `field.cattle.io/projectId: p-abcde` on a Namespace object, but that did not place the namespace in that project.

Random thoughts: Create a "Not in Project" option in the dropdown menu and list the workloads there?

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/16493 as its either of the described ways.

**Comment by leodotcloud** [comment]
Totally forgot that I had created this issue in the past :)
