### ISSUE TITLE
Project network isolation works only with service of type ClusterIP

### ISSUE THREAD

**Issue by david-maumenee** [rancher/rancher#15250]
**Rancher versions:**
rancher/server v2.0.8
rancher/agent v2.0.8

**Infrastructure Stack versions:**
network-services: **Canal with project network isolation enable**
kubernetes (if applicable):v1.11.2

**Docker version: 17.3.2

**Operating system and kernel: ** ubuntu 16.04

**Type/provider of hosts: ** RKE with Custom privder on VirtualBox (init with Vagrant) and RKE on EC2

**Steps to Reproduce:**
Create a cluster with RKE and select "Canal with project network isolation enable"
Deploy two workload into two differents projects and namespaces (n1 & n2)
I use ehazlett/docker-demo and check the /ping endpoint with ```wget -qO- http://docker-demo:8080/ping``` from the shell inside the container

Add a service of type **ClusterIP** : isolation is **OK**.
In namespace n1 docker-demo.n2 is resolved with ping but  ```wget -qO- http://docker-demo.n2:8080/ping``` fail.

Delete the service an deploy a new one of type **NodePort** or **Loadbalancer** : isolation is **KO**
In namespace n1, the pod can access to the other projet in namespace n2  ```wget -qO- http://docker-demo.n2:8080/ping```.

**Expected Results:**
With Network isolation enable, regardless of service type, the access via **service-name.namespace** shouldn't be able from another project.
Service of type NodePort or LoadBalancer will remain accessible from any namespace but only with the same URL that is used to access the pod from outside the cluster

**Comment by vincent99** [comment]
The point of isolation is to prevent direct access between pods (which each have a cluster IP even if you don't make a service at all) that have ports open that they do not intend to publish to the outside world.

Once you are explicitly publishing services to public IPs, they are accessible like any other public  resource on the internet.

Lack of a DNS record would not make it less accessible, and what you're asking for is just not what k8s does.

**Comment by loganhz** [comment]
Please see https://github.com/rancher/rancher/issues/15250#issuecomment-416276206
