### ISSUE TITLE
CPU and RAM missing from GKE on cluster list page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15272]
**Rancher versions:** 2.0 master 8/27

**Steps to Reproduce:**
1.  Setup a GKE cluster

**Results:**  On the cluster list page, the CPU and RAM information is missing?  It's on the main cluster page so I know it's available somewhere and I swear it used to be there.
![image](https://user-images.githubusercontent.com/11514927/44742626-2b79b880-aab5-11e8-999b-35565f8c9592.png)

**Comment by westlywright** [comment]
@tfiduccia we no longer have this info at the global level (cluster level has access to all nodes and the front end does its own parsing for the info in the gauges which vince says is not all the info). I've created another issue to track the backend change. I'm going to move this out of a milestone until we have a target for backend change.

**Comment by shinebayar-g** [comment]
![image](https://user-images.githubusercontent.com/3091558/47258333-69e78e80-d4cc-11e8-9bc2-3ec43ce5e317.png)
Is it fixed in 2.1.1?

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed
