### ISSUE TITLE
Feature Request: Support for Logging to AWS Elasticsearch Service

### ISSUE THREAD

**Issue by kylegoch** [rancher/rancher#15275]
Rancher currently supports sending to Elasticsearch, however due to the nature of AWS Elasticsearch Service it cant be used currently.

AWS ES requires that requests be signed before sent to Elasticsearch Service. Using the AWS SDK for Go you can sign the requests:
https://docs.aws.amazon.com/sdk-for-go/api/service/elasticsearchservice/

**Comment by guangbochen** [comment]
@aiwantaozi FYI

**Comment by paynejacob** [comment]
With logging v2 introduced in rancher 2.5, aws eleasticsearch is a supported output.

https://rancher.com/docs/rancher/v2.x/en/logging/v2.5/
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/aws_elasticsearch/
