### ISSUE TITLE
Duplicated healthcheck host entries in the DB

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15284]
Found the issue during the debugging on the customer side. The healtcheck instance host map table has the entries having duplicated host_id/instance_id. And it causes some other places in the code - expecting to see only one entry - to break.

**Comment by kinarashah** [comment]
@superseb Haven't been able to reproduce this issue. Best guess is that there's some locking issue which caused duplicate entries to be created. 
Since I couldn't reproduce the root cause, I've put in a PR to remove duplicate entries and avoiding errors like these - 
```
[c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception org.jooq.exception.InvalidResultException: Cursor returned more than one result
``` 
Let me know if we can get some extra information/steps to reproduce or if you still see Exceptions for duplicates, that'd be helpful

**Comment by sangeethah** [comment]
Tested with v1.6.22-rc3 with HA setup.

Had a setup with 3 hosts.
Deployed many health check enabled instances.

Powered down one of the host. This would result in this host being removed from the healthcheck_instance_host_map for all the health check enabled instances.

Powered on this host again. This would result in the same host being added back to the healthcheck_instance_host_map for all the health check enabled instances.

Did the above steps multiple times and did not not see the issue of having duplicate host entries for the same instance in healthcheck_instance_host_map.

Also tried restarting the management servers few times when host was powered down and then powered on hosts.

**Comment by Tejeev** [comment]
## Workaround:

1. In the Rancher MySQL database, find all the duplicates by checking column 3 for entries with more than a count of 1 in the return from the following query:
`select host_id,healthcheck_instance_id,count(*) from healthcheck_instance_host_map where removed is null group by host_id,healthcheck_instance_id order by 3;`
2. For each healthcheck_instance_id in any row with more than 1 in column 3, run the following command:
`update healthcheck_instance_host_map set state='removed', removed=now(), remove_time=now() where healthcheck_instance_id='<INSERT_HEALTHCHECK_ID>';` 
3. Wait and watch the hosts view.  The hosts should all finish reconnecting and instances should update.
