### ISSUE TITLE
Host with identical hostname as previous host will fail to register

### ISSUE THREAD

**Issue by wedtm** [rancher/rancher#1528]
First, a host is added to rancher with name `example` and then subsequently deleted and purged from Rancher. When a *different* host, with the *same* hostname tries to register the client simply repeats `ERROR: Please re-register this agent`.

**Comment by ibuildthecloud** [comment]
Hmmm.... not sure what could cause that.  Can you first try `rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state`  On the `example` host and then try to register again.

**Comment by deniseschannon** [comment]
@wedtm What version are you running? I was unable to reproduce with the latest v0.30.0.

**Comment by flaccid** [comment]
I have also replicated this problem on v0.30.0. @ibuildthecloud your commands/workaround did the trick, in particular I think wiping `/var/lib/rancher/state` as I'd already removed the containers.

**Comment by jlrigau** [comment]
I have the same issue with rancher v0.31.0. The workaround fix it.

**Comment by deniseschannon** [comment]
I've been able to reproduce with v0.31.0.

**Comment by tdensmore** [comment]
I am running into this issue as well with rancher rancher/agent:v0.8.1:

INFO: Starting agent for 3D4E669322C2384C0AD9
INFO: Access Key: 3D4E669322C2384C0AD9
INFO: Config URL: http://52.X.XX.201:8080/v1
INFO: Storage URL: http://52.X.XX.201:8080/v1
INFO: API URL: http://52.X.XX.201:8080/v1
INFO: IP: 52.X.XX.201
INFO: Port:
INFO: Required Image: rancher/agent:v0.8.1
INFO: Current Image: rancher/agent:v0.8.1
INFO: Using image rancher/agent:v0.8.1
INFO: Downloading agent http://52.X.XX.201:8080/v1/configcontent/configscripts
{"id":"b75971d8-51a3-41b0-a4d0-f989fa45703a","type":"error","links":{},"actions":{},"status":422,"code":"MissingRequired","message":null,"detail":null,"fieldName":"agentId"}
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
{"id":"dd1c2fd2-f4e6-49b6-a396-f0fedb6f6687","type":"error","links":{},"actions":{},"status":422,"code":"MissingRequired","message":null,"detail":null,"fieldName":"agentId"}ERROR: Please re-register this agent

**Comment by deniseschannon** [comment]
@tdensmore Had you removed the host from your Rancher server before trying to add another host with the same name and allow Rancher to purge it? 

I'm not sure how to reproduce this issue (using v0.35.0) as I have been able to add another host with the same name to Rancher with no issues. I can even have 2 hosts with the same name but they are coming from two different cloud providers.

**Comment by moimael** [comment]
I encountered this issue on 0.39, the workaround worked for me.

**Comment by ibuildthecloud** [comment]
@moimael What steps did you do to get into this situation?  One common thing users do that causes issues is clone VMs.  They register a host to rancher, then clone the VM and register the cloned VM.  This doesn't work because the unique ID rancher saves in `/var/lib/rancher/state` is the same for both machines.

**Comment by will-chan** [comment]
workaround exist for now.

**Comment by defunctzombie** [comment]
I am seeing this issue when I update the Host Registration Url in the rancher server UI. I previously had `http://rancher-server.example.com` and am trying to change it to `http://rancher-server.example.com:8080` but when I do this, the hosts disconnect and agent logs say the agents need to be re-registered. Is there a way I can have the agents change to a new url without having to go to each box individually and update them?

It would also be nice to have a way in the UI to see that a host has the latest "configuration" on it for such updates.

**Comment by deniseschannon** [comment]
The only way to update the rancher/agent's host URL is to go into each host and re-run the registration command.

**Comment by defunctzombie** [comment]
:(

**Comment by defunctzombie** [comment]
Would it be too much to ask to have the agent be able to handle such updates?

**Comment by LLParse** [comment]
@defunctzombie I don't see anything technically wrong with implementing a mechanism to push config updates to agents, but this is an edge case. Most users set-and-forget the Host URL.

Without changing code, you could build a catalog entry with label `io.rancher.scheduler.global: "true"` and bind mount the host docker.sock into the container. Then just execute a new registration URL and all agents should update. We also accept pull requests :)

**Comment by defunctzombie** [comment]
@LLParse interesting, I'll give that a try; thanks for the tip!
