### ISSUE TITLE
Metrics-server add-on deployment not using system-default-registry setting

### ISSUE THREAD

**Issue by stefanvangastel** [rancher/rancher#15280]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent: 2.0.8 

**Infrastructure Stack versions:**
kubernetes : 1.10.3

**Docker version: 17.3.2**

**Operating system and kernel: Ubuntu 18.04**

**Type/provider of hosts: Bare-metal on-premise**

**Setup details: Single node Rancher, on-premise offline**

**Environment Template: Kubernetes**

**Steps to Reproduce:**

Enable the 'Metrics' add-on in an existing cluster with a custom `system-default-registry` setting. 

**Results:**

Metrics server will be deployed, only it's using the default `rancher/metrics-server-amd64:v0.2.1` image instead of `my.private.registry/rancher/metrics-server-amd64:v0.2.1`.

Manualy changing the image (thank you for showing `system` project in UI!) fixes the deployment.

**Comment by superseb** [comment]
From what Rancher version to what Rancher version was upgraded? Are there any other custom cluster settings configured?

**Comment by deniseschannon** [comment]
@stefanvangastel let me know if you still have any issues when upgrading with this.
