### ISSUE TITLE
Cluster must have at least one etcd plane host after switching cloud provider

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#15281]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent: 2.08

**Docker version: (`docker version`,`docker info` preferred)** 18.03.01

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 4.4.0-130-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 2 nodes

**Results:**

By accident I switched the cloud provider to Amazon, then I tried switching it back to `None`. Then I upgraded Rancher from 2.0.4 to 2.0.8.

My cluster now shows:

	
```
This cluster is currently Updating.

Cluster must have at least one etcd plane host
```

Also launching kubectl from Rancher just shows a black screen.
How can I get rid of this / what do I need to do?

<img width="761" alt="rancher 2018-08-29 11-40-40" src="https://user-images.githubusercontent.com/7140800/44779687-6d236580-ab80-11e8-850b-f751d3dc8a38.png">

**Comment by santascsi** [comment]
Is the node with etcd running a rancher-agent container and what version is it?

**Comment by dj-hedgehog** [comment]
@santascsi No, it is not:

```
975f1b91e644        rancher/rancher:latest               "entrypoint.sh"          2 days ago          Up 2 days               0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   hungry_cray
f9623476439b        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint…"   2 days ago          Up Less than a second                                                 kubelet
5477a3a45ae7        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint…"   2 days ago          Up 8 seconds                                                          kube-controller-manager
642394af74a8        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint…"   2 days ago          Up 2 days                                                             kube-apiserver
26b24bc05337        rancher/coreos-etcd:v3.1.12          "/usr/local/bin/etcd…"   2 days ago          Up 2 days                                                             etcd
28d762d5b270        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint…"   3 months ago        Up 2 days                                                             kube-proxy
e469c6904d2e        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint…"   3 months ago        Up 2 days                                                             kube-scheduler
```

**Comment by dj-hedgehog** [comment]
@santascsi After waiting a while the cluster returned to an OK state.
The only thing I noticed was that the worker node became unresponsive. Upon checking I noticed that it spawned 1020 rancher-agents during the last 3 days.
