### ISSUE TITLE
Invalid catalog URL using gitlab public repo

### ISSUE THREAD

**Issue by lagrianitis** [rancher/rancher#15283]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.0.7

I have created a custom catalog using gitlab public repo.
`https://gitlab.test.company.org/infra/charts.git`

This repo can be cloned without auth from cattle server.
After setting the name and the repo I set it to use `master` branch

The repository has this structure:
`charts/<chart_name>/<chart_version>`

Error I receive is:
```{
"actions": {
"refresh": "…/v3/catalogs/gitlabcatalog?action=refresh"
},
"annotations": { },
"baseType": "catalog",
"branch": "master",
"conditions": [
{
"lastUpdateTime": "2018-08-29T15:38:54Z",
"message": "invalid catalog url",
"reason": "Error",
"status": "False",
"type": "Refreshed"
}
],
"created": "2018-08-29T15:38:54Z",
"createdTS": 1535557134000,
"creatorId": "user-lzd65",
"description": "",
"id": "gitlabcatalog",
"kind": "helm",
"links": {
"exportYaml": "…/v3/catalogs/gitlabcatalog/exportyaml",
"remove": "…/v3/catalogs/gitlabcatalog",
"self": "…/v3/catalogs/gitlabcatalog",
"templates": "…/v3/templates?catalogId=gitlabcatalog",
"update": "…/v3/catalogs/gitlabcatalog"
},
"name": "gitlabcatalog",
"state": "refreshed",
"transitioning": "error",
"transitioningMessage": "invalid catalog url",
"type": "catalog",
"url": "https://gitlab.test.company.org/infra/charts.git",
"uuid": "a293ebcf-aba1-11e8-86b6-00505695cf62"
}```

**Comment by superseb** [comment]
Can you run `git clone https://gitlab.test.company.org/infra/charts.git` inside the container?

**Comment by lagrianitis** [comment]
Hello @superseb Indeed the issue is SSL verification failure from inside the container. 
Running git http.sslVerify false I can work-around it.
It is weird though as in the beginning rancher api gave me an TLS error even when I loaded the CA via the Rancher UI. 
I worked around this by re-deploying cattle setting ENV  SSL_CERT DIR=etc/kubernetes/ssl/certs
The above is also fixing the elasticsearch logs integration as well.
Then the TLS error dis-appeared and start having the `invalid catalog url` error.
I believe that git is looking for ca certs in a different location 
Would be great to have the ability to set all these as part of the deployment without having to ignore verification, as parameters maybe?

**Comment by superseb** [comment]
Yes we have this issue open for that https://github.com/rancher/rancher/issues/14766, and added the option to skip SSL verification in this issue https://github.com/rancher/rancher/issues/15330.

Let me know if there is anything not solved by those two.
