### ISSUE TITLE
Set SSL_CERT_DIR to default certificate path so mounted certificates can be used to validate outgoing connections

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15291]
CA certificate when using custom CA gets mounted at `/etc/rancher/ssl/cacerts.pem`, usually that CA is also used for certificates in the infrastructure Rancher has to access (Cloud API where Docker-machine is connecting to, or a Git repository hosting catalog repos). Today you have to configure `SSL_CERT_DIR` to point to the directory while it's safe to assume that the CA that gets mounted can be trusted to validate outgoing calls from Rancher to services.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc1

SSL_CERT_DIR is configured

```
docker exec <container> env | grep SSL_CERT_DIR
SSL_CERT_DIR=/etc/rancher/ssl
```
