### ISSUE TITLE
Alerts should not be shown for host that are in "Draining"/"Drained" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15301]
**Rancher versions:** Build from master
**Steps to Reproduce:**
Create a cluster.
Deploy few workloads.
Drain a node.
On the cluster dashboard page, we see alerts for this node.

Expected Behavior:
Alerts should not be shown for host that are in "Draining"/"Drained" state.

**Comment by kinarashah** [comment]
@loganhz this looks like ui issue, similar to https://github.com/rancher/rancher/issues/14659, could you confirm?

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/4
Verified fixed.
