### ISSUE TITLE
[2.0][EC2] Add T3 instance type for AWS EC2 node template

### ISSUE THREAD

**Issue by niranjan94** [rancher/rancher#15308]
**Rancher versions:**
rancher/rancher: `v2.0.8`

**Type/provider of hosts:** `AWS EC2`

**Steps to Reproduce:**
- Add new node template
- Select AWS EC2 as driver
- Enter credentials
- Select vpc & subnet
- Select security group
- In instance type, [EC2 `T3` instance types](https://aws.amazon.com/ec2/instance-types/t3/) are unavailable in the list.

**Comment by rsilvestre** [comment]
The same here with rancher 1.6

**Comment by vincent99** [comment]
Amazon has no API to get the instance types, so they have to be manually added every time.

**Comment by rsilvestre** [comment]
By the way, are you also going to add T3 instance type on Rancher version 1.6.x ?

**Comment by tfiduccia** [comment]
@rsilvestre - I just put in a separate issue to address this.  You can track here -  #15502

**Comment by vincent99** [comment]
Need to add `r5` and `r5d` too, `{large, xlarge, 2xlarge, 4xlarge, 12xlarge, 24xlarge}`.  They're not generally available but some people have access.  https://www.ec2instances.info

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/12
r5 and r5d listed but I don't have access to that size.  But I can verify they are there and selectable.  they are passed and returned by API.
Verified fixed.

**Comment by rsilvestre** [comment]
Hi @tfiduccia, nice job. When can we expect to have in it available on rancher/server image on docherhub ?
