### ISSUE TITLE
Failed to communicate with API server

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#15310]
rancher/rancher:master 08/29

![image](https://user-images.githubusercontent.com/21168270/44839485-7b9d7a00-ac71-11e8-90bb-130bc9ea6bdc.png)

Steps to reproduce:

1. Create a cluster in Rancher. (custom, AWS t2.medium, ubuntu, 1 node with all roles)
2. Deploy a workload with image `liuyan/producelog:v3` (The image will print a lot of logs to console log)
3. View log of the pod and wait for a while (like 10s)
4. Close the view log popup.
5. View log again and wait for 10s.

Result:

Cluster will be in Unavailable state and it will never become active again.

Failed to communicate with API server: Get https://172.31.16.104:6443/api/v1/componentstatuses?timeout=30s: waiting for cluster agent to connect

Workaround:

ssh to the node and remove `k8s_agent_cattle-node-agent-56ng5_cattle-system_8ad2b841-ac28-11e8-b49b-063c344537ce_0` manually. The pod will get recreated automatically and the cluster will become `active` state.

**Comment by loganhz** [comment]
It happens since v2.0.7.

It looks good in v2.0.4, v2.0.5 and v2.0.6

**Comment by martcastaldo** [comment]
@loganhz I'm getting the same issue on 2.0.8 now :(

Here:

https://github.com/rancher/rancher/issues/15319

**Comment by martcastaldo** [comment]
@loganhz Where can I find that file?

**Comment by martcastaldo** [comment]
Cant find the mentioned file:

`find . -name "k8s_agent_cattle-*"`

Didnt find anything :(

**Comment by loganhz** [comment]
it’s a container. Try docker ps | grep

**Comment by martcastaldo** [comment]
@loganhz 

Theses are the containers that I have:

`89429589330b        rancher/rancher-agent:v2.0.8         "run.sh --server h..."   16 hours ago        Up 16 hours                                                   cranky_lalande
ef532300f684        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   18 hours ago        Restarting (255) Less than a second ago                       kube-apiserver
73564c53004c        rancher/coreos-etcd:v3.1.12          "/usr/local/bin/et..."   18 hours ago        Up 16 hours                                                   etcd
d528cc5632c1        rancher/rancher-agent:v2.0.8         "run.sh --server h..."   18 hours ago        Up 16 hours                                                   kind_meitner
6b336d13f5eb        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   19 hours ago        Up 16 hours                                                   kubelet
172ce0003c5c        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   4 weeks ago         Up 16 hours                                                   kube-proxy
6bca446e8ae7        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   4 weeks ago         Up 16 hours                                                   kube-scheduler
c1dcf9ca58a8        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   4 weeks ago         Up 16 hours                                                   kube-controller-manager
`

**Comment by martcastaldo** [comment]
@loganhz There are the containers on my host:

89429589330b        rancher/rancher-agent:v2.0.8         "run.sh --server h..."   16 hours ago        Up 16 hours                                                   cranky_lalande
ef532300f684        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   18 hours ago        Restarting (255) Less than a second ago                       kube-apiserver
73564c53004c        rancher/coreos-etcd:v3.1.12          "/usr/local/bin/et..."   18 hours ago        Up 16 hours                                                   etcd
d528cc5632c1        rancher/rancher-agent:v2.0.8         "run.sh --server h..."   18 hours ago        Up 16 hours                                                   kind_meitner
6b336d13f5eb        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   19 hours ago        Up 16 hours                                                   kubelet
172ce0003c5c        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   4 weeks ago         Up 16 hours                                                   kube-proxy
6bca446e8ae7        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   4 weeks ago         Up 16 hours                                                   kube-scheduler
c1dcf9ca58a8        rancher/hyperkube:v1.10.5-rancher1   "/opt/rke/entrypoi..."   4 weeks ago         Up 16 hours                                                   kube-controller-manager

**Comment by sangeethah** [comment]
Able to reproduce this issue when testing with v2.1.0-rc2.

Tested the following scenario with v2.1.0-rc3.

1. Create a cluster in Rancher. (custom, AWS t2.medium, ubuntu, 1 node with all roles)
2. Deploy a workload with image liuyan/producelog:v3 (The image will print a lot of logs to console log)
3. View log of the pod and wait for a while (like 30s)
Close the view log popup.
Repeat step 3 multiple times.

Cluster continues to be healthy.

**Comment by micw** [comment]
@sangeethah I had the problem with 2.1.3 today...

**Comment by TechCanuck** [comment]
2.1.5 exhibits this as well.  Every time I remove 1 node (in a 3 or 4 node cluster) this does this for quite awhile.  SSH'ing to to one of the active nodes tells me that the box is ok / healthy but the API response says otherwise.

**Comment by martcastaldo** [comment]
I'm getting the same issue on 2.0.8

**Comment by ppotaki** [comment]
> 2.1.5 exhibits this as well. Every time I remove 1 node (in a 3 or 4 node cluster) this does this for quite awhile. SSH'ing to to one of the active nodes tells me that the box is ok / healthy but the API response says otherwise.

I am getting the same issue with connection beetwen nodes in cluster. I have 2.1.5 Rancher installed.

**Comment by loganhz** [comment]
Can you file a new issue, please? It looks like your reproduce steps are different from the original steps in this issue.

**Comment by roysG** [comment]
any update?

**Comment by teachmyself** [comment]
I got this error with version 2.1.6.

**Comment by MihaiSandor** [comment]
I got this error with version 2.2.1

**Comment by Panthro** [comment]
2.2.3 same error after upgrade

**Comment by loganhz** [comment]
@Panthro @MihaiSandor @teachmyself @roysG 

I think the reproduce steps are different with the steps described in this issue. 

Could you please file a new issue with the updated reproduce steps, please?

**Comment by freeloop914** [comment]
2.2.4 with same error
but I found my root cause.
I used domain name for rancher server , 
and once the IP address change ( because my ISP gives me a floating IP , it's changed every week)
the DNS cache in agent node is not up-to-date.
so they cant communicate to rancher server.
solve it by :
systemctl restart nscd

**Comment by namebrandon** [comment]
Just wanted to jump in here and reiterate what @freeloop914 mentioned.. I had a vm running my rancher server and it crashed, so I restored it from snapshot and moved to a different esxi server where it picked up a new IP address. I had a CNAME entry in my dns server that k8s latched on to for some reason and looking at the logs of the k8s_agent-cattle-node-agent pod showed 

    ERROR: https://mycname-dns-entry/ping is not accessible (OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mycname-dns-entry:443)

Once I updated the DNS cname to point to the updated IP for that new VM, all was well again.

**Comment by christian1607** [comment]
I had the same problem in  Rancher V2.2.7, solved just deleting the agent pod
**cattle-cluster-agent-XXXXXXX-YYYYY**

**Comment by maxisam** [comment]
have this issue after upgrade to v2.5.2 from 2.4.6

**Comment by seancallaway** [comment]
Have this issue on v2.5.3, as well.

**Comment by venomone** [comment]
Same here

**Comment by virus2016** [comment]
Same here...

**Comment by hzchenkj** [comment]
v.2.5.2 same here

**Comment by hzchenkj** [comment]
v.2.5.2 same here

**Comment by maxisam** [comment]
Mine is magically fixed after 2.5.7 with v1.19.8

**Comment by aledr** [comment]
v2.5.8 also affected.

**Comment by maxisam** [comment]
I had this problem when I upgraded to 2.5.8 /1.19.10 again and it went away after I downgraded k8s version to 1.19.9. I don't know if the downgrade fixes it or just simply because I ran it again.

**Comment by nishit93-hub** [comment]
Hi, 

I am using version 2.5.8. I am also getting the same error. Please, anyone guide why getting this error. I even tried to remove the pod **k8s_agent_cattle-node-agent** but it didn't recreate automatically

**Comment by arcreigh** [comment]
Currently encountering this on 2.6

**Comment by wgqkirk** [comment]
still exists

**Comment by arcreigh** [comment]
I am noticing that this may be related to environments that use DHCP. Rancher is expecting the masters IP addresses to be what it last saw. However the servers are supposed to be ephemeral. Things should be able to be built up and destroyed at any point. I believe that there needs to be some kind of multicast traffic or some way for the servers to communicate their current address to rancher so that these communication errors don't happen.

**Comment by struggle-t** [comment]
This issue still exists on rancher v2.6.2
