### ISSUE TITLE
User with just "Login Access" can't login

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#15313]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent: v2.0.8

**Steps to Reproduce:**
- Create a user with Custom Role just Login Access
![image](https://user-images.githubusercontent.com/942110/44854103-af5aae80-ac35-11e8-97a9-249b34a946db.png)

![image](https://user-images.githubusercontent.com/942110/44854097-a9fd6400-ac35-11e8-9fb5-c08fd4434b82.png)

![image](https://user-images.githubusercontent.com/942110/44854087-a538b000-ac35-11e8-97bd-3f256941f0bb.png)

![image](https://user-images.githubusercontent.com/942110/44854073-a073fc00-ac35-11e8-93b9-9bdbe1110dec.png)

- Logout

- Attempt to Login as the user that was created

**Results:**
- Login Failed
![image](https://user-images.githubusercontent.com/942110/44854050-93570d00-ac35-11e8-93d7-7c21156c2168.png)

- Errors in the Terminal
```
2018/08/30 13:05:30 [ERROR] UserController u-bz7cg [mgmt-auth-users-controller] failed with : clusterrolebindings.rbac.authorization.k8s.io "grb-u-bz7cg-view" already exists
2018/08/30 13:05:30 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-vw2qb
2018/08/30 13:05:30 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-vw2qb for user u-bz7cg with role cattle-globalrole-user-base
2018-08-30 13:09:22.808365 I | mvcc: store.index: compact 1080627
2018-08-30 13:09:23.050180 I | mvcc: finished scheduled compaction at 1080627 (took 218.056662ms)
2018/08/30 13:09:25 [INFO] [mgmt-auth-users-controller] Deleting globalRoleBinding grb-vw2qb for user u-bz7cg
2018/08/30 13:09:25 [ERROR] GlobalRoleBindingController grb-vw2qb [mgmt-auth-grb-controller] failed with : failed to remove finalizer on :grb-vw2qb
E0830 13:12:43.084064       7 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
2018-08-30 13:14:22.847367 I | mvcc: store.index: compact 1081046
2018-08-30 13:14:23.098617 I | mvcc: finished scheduled compaction at 1081046 (took 228.281204ms)
2018/08/30 13:15:04 [ERROR] UserController u-9d6nl [mgmt-auth-users-controller] failed with : clusterrolebindings.rbac.authorization.k8s.io "grb-u-9d6nl-view" already exists
2018/08/30 13:15:04 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-9pks6
2018/08/30 13:15:04 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-9pks6 for user u-9d6nl with role cattle-globalrole-user-base
```

**Comment by sangeethah** [comment]
@JasonvanBrackel , From the screenshots you have attached , you have github auth enabled in your setup. Could you check what "Site Access" settings you have ? If you have anything set other than "Allow any valid user" ,  the newly created user will not be allowed to access rancher-server unless he was added as a member to existing clusters or to the restricted access list. 

Could you confirm if this was the case ?

**Comment by JasonvanBrackel** [comment]
@sangeethah That is true, but makes 0 sense.  

There's a logic / common sense problem here.  The user has Global scoped Login Access, but is not considered an Authorized User.   I understand that Site Access is separate from RBAC, but one should either trigger the other, or at least notify the administrator that Login Access RBAC isn't sufficient Authorization to actually give the user Login Access to Rancher.

**Comment by sangeethah** [comment]
@JasonvanBrackel Thanks. This issue you are bringing up here is also tracked in https://github.com/rancher/rancher/issues/15113.

**Comment by cjellick** [comment]
Closing in favor #15113
