### ISSUE TITLE
Ability to specify more than one security group when creating EKS for either control plane or worker nodes

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15316]
Extracted from: https://github.com/rancher/rancher/issues/15205#issuecomment-417303035

```
"This is because, this parameter is of type 'Type: AWS::EC2::SecurityGroup::Id', so it will only accept 1 securityGroup. If you try to give multiple, it will fail with:

   Invalid type for parameter Parameters[1].ParameterValue, value: ['sg-xxxxxxxx', 'sg-yyyyyyyy'], type: <class 'list'>, valid types: <class 'str'>

This does not stop you modifying this template to handle more than 1 ClusterControlPlane securityGroups. For that you will need to create multiple SecurityGroup fields/parameters and need to ensure that all the securityGroups are handled the same way as it is handled with 1 securityGroup now"
```

**Comment by deniseschannon** [comment]
Notes from: #15362

Similar to #15316 which deals with the control plane security groups... currently the CloudFormation stack that launches the EKS worker nodes creates a security group to allow communication with the cluster control plane. We should be allowed to specify multiple security groups to be automatically attached to the worker nodes along with the automatically created one.
