### ISSUE TITLE
Not able to use service name when using affinity/anti-affinity rules to service names. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1531]
Server version - V0.27.0-rc1

Steps to reproduce the problem:
Create environment - env1
Create service test1.
Create a service test2 with scheduling rule - "host must have service with name" - test1 (without passing environment name).

When this service is activated , it will be stuck in activating state forever since it is not able to find placement for the containers.

The affinity label that was created for this rule is - 
io.rancher.scheduler.affinity:container_label	io.rancher.stack_service.name=test1.

Expected Behavior:
When no environment is specified  for "io.rancher.stack_service.name" , we should be able to default it to the environment the service that is being created belongs to , "env1" in this case.

**Comment by tfiduccia** [comment]
I think this is a duplicate of #1382

**Comment by sangeethah** [comment]
Tested with build from master:

When env name in not used in "io.rancher.stack_service.name=" value for anti-affinity to itself , it works as expected.
I see the Affinity rule that gets added to the cotainers deployed has the  environment name appended to it:
io.rancher.scheduler.affinity:container_label_ne = io.rancher.stack_service.name=Default/testanti

But when env name is not used in "io.rancher.stack_service.name=" for affinity rules to some other service in the same stack it does not work . Containers fail to deploy because of bot being able to find placement.

Reopening this issue to fix this use case.

**Comment by sangeethah** [comment]
Tested with build from master:

When env name is not used in "io.rancher.stack_service.name=" for affinity rules to some other service in the same stack  , all containers get deployed in the same hosts as the containers from the affinity service.
