### ISSUE TITLE
Do not add "io.rancher.project.name" and "io.rancher.project_service.name" labels to containers

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1532]
Server Version - V0.27.0-rc4

Containers that get deployed as part of a service have "io.rancher.project.name" and "io.rancher.project_service.name" labels  in addition to the new lables -"io.rancher.stack.name" and "io.rancher.stack_service.name".

Affinity rules that get created use - io.rancher.scheduler.affinity:container_label - io.rancher.stack_service.name=< value> as expected:

Why is there a need to have "io.rancher.project.name" and "io.rancher.project_service.name" labels  for containers that are deployed  in services created in rancher server version - V0.27.0-rc4 ?
Expected Behavior:
We should not have "io.rancher.project.name" and "io.rancher.project_service.name" labels for these containers.

**Comment by sonchang** [comment]
@sangeethah The reason we include these is for services created prior to the "project"->"stack" name change.  An old service might have a scheduling rule that still uses the "io.rancher.project.name" or "io.rancher.project_service.name" labels.  If we don't inject these system labels, deployment of that service will be broken.

I can add logic to scan for scheduling rules within the service definition explicitly looking for references to the old labels.  And only inject these labels if they're referenced.  We can file this as a feature request (or modify this issue to be that feature request).  I'm guessing this wouldn't be a high priority feature though.

**Comment by vincent99** [comment]
I think it's been long enough that we can stop adding these...
