### ISSUE TITLE
Unable to run modified pipeline configuration without pushing to repository

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#15324]
rancher/rancher:master 8/30

#14282 
"Change to pipeline in repo model. we don't have to store pipeline configs in our server side if they are presented in the repo. Though we will store and run the modified version if users do modifications but don't update it to the repo."

**Steps to Reproduce:**
Enable a pipeline
Make a change to pipeline configuration
Click 'Done'

**Results:**
The options presented are to download the config without running, or to push the config to the repository. User is unable to run the edited pipeline without pushing to the repository.

**Comment by gitlawr** [comment]
We no longer store the modified version on rancher side, and the source code repository is the single source of the pipeline definition. So this is an expected behavior now. I'll update the description in the upstream issue.
