### ISSUE TITLE
apiEndpoint wrong for imported AKS cluster

### ISSUE THREAD

**Issue by bmartin13** [rancher/rancher#15322]
I have an issue with an imported AKS cluster.  After the import, the apiEndpoint for the cluster is set to an internal IP instead of the external FQDN...

"apiEndpoint": "https://10.101.0.1:443",

**Rancher versions:**
rancher/rancher:v2.0.8
rancher/rancher-agent:v2.0.8

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.7

**Comment by johannges** [comment]
I have the same Problem with an imported cluster.

how does Rancher determin the apiEndpoint when importing a kubernetes cluster?

**Comment by johannges** [comment]
if you download the yaml (https://rancher.integration.obi.de/v3/import/....yaml) rancher provides for you, you can set the external ip by adding the environment variable KUBERNETES_SERVICE_HOST with your external ip to cluster-register and agent container.

`
- name: CATTLE_K8S_MANAGED
          value: "true"
- name: CATTLE_AGENT_CONNECT
          value: "true"
- name: KUBERNETES_SERVICE_HOST
  value: "YOUR_IP"
`
