### ISSUE TITLE
Make default namespace resourcequota a required field in the UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15339]
Make default namespace resourcequota a required field in the UI when project resourcequota field is set.

**Comment by alena1108** [comment]
@loganhz I'm enforcing this requirement on the api side as well https://github.com/rancher/rancher/issues/15338

**Comment by sangeethah** [comment]
@alena1108 Additionally every resource specified in the project resource quota should also be present in the default namespace resource quota.

This restriction should also be enforced when namespace is getting created with a resource quota, such that it inherits all values from  default namespace resource quota for resources not specified.

**Comment by alena1108** [comment]
@sangeethah I'll enforce it on the api side validation. UI should be handled separately.

**Comment by loganhz** [comment]
@sangeethah @alena1108 @soumyalj 

It looks like project quota and default namespace quota is one one mapping.
Maybe we need to change the UI to something like this when create/edit project?

![image](https://user-images.githubusercontent.com/21168270/44913126-01e3ba00-ad5f-11e8-848f-3771b65b4622.png)

In create/edit namespace page, user needs to input all of the resource quota defined in the project. And user is not be able to remove  a resource quota or add a resource quota when create a namespace in the project.

![image](https://user-images.githubusercontent.com/21168270/44913898-2b054a00-ad61-11e8-91d3-161386356685.png)

**Comment by alena1108** [comment]
@loganhz I like the redesign, lets go with it

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
