### ISSUE TITLE
Redesign approach on adding catalogs

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15330]
Currently, catalogs are added with or without a branch specified and then get verified by the catalog code. The `git.IsValid` (https://github.com/rancher/rancher/blob/master/pkg/catalog/manager/manager.go#L67) function determines using `git ls-remote $URL` if it's a Git repo, and if not, treats it as a Helm HTTP repo. Problem with this approach is that you can't tell for certain that it's a valid Git repository or not. For instance, when the certificate is invalid, `git ls-remote` will error out with invalid certificate and then treats it as Helm HTTP.

Two approaches are possible here:
1. Let the user pick what catalog type is being added (name, url, checkbox Git/Helm with explanation, if git, show branch with default value `master`). The catalog code can then validate the given catalog type instead of guessing/validating.
1. Catch all possible errors in the code to try and validate the Git repository.

Possibly add an option to allow insecure repositories (skip SSL verify)

**Comment by erikwilson** [comment]
Should probably let the user pick the catalog type, for extra info this can produce errors like: `Unexpected HTTP status code 404 from [https://github.com/.../repo.git/index.yaml], expected 200`

**Comment by Kralor-Guldan** [comment]
Please add the feature to disable SSL verification. For airgap networks, this is very important.

**Comment by erikwilson** [comment]
I am not sure that it would be a great idea to have a feature to disable SSL verification, sounds like it would be too easy to misconfigure or too hard to know if something is misconfigured. A better option might be to load the certs into Rancher server so verification works, or use http catalogs if you really don't care about encryption.

**Comment by vincent99** [comment]
:+1:; an explicit mode is fine (probably with an `auto` option that maintains the current behavior for backwards compatibility).  But provide the appropriate chain so that TLS verifies, or don't use https.
