### ISSUE TITLE
Make namespace default quota required on the project when resource quota is set

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15338]
When the resource quota is set on the project, the namespace default quota should be enforced on the API level

**Comment by sangeethah** [comment]
Additionally every resource specified in the project resource quota should also be present in the default namespace resource quota.

This restriction should also be enforced when namespace is getting created with a resource quota, such that it inherits all values from default namespace resource quota for resources not specified.

**Comment by soumyalj** [comment]
Tested with master using UI.  
The namespaceDefaultResourceQuota is made mandatory  when creating a project. 
When creating a new namespace, it does ensure that we can specify the resourcequota other than the default. We can also specify "Zero" as values for the resources. 
Related issues are tracked here: 
https://github.com/rancher/rancher/issues/15501
https://github.com/rancher/rancher/issues/15503
