### ISSUE TITLE
Search for hosts, stacks and containers

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#1533]
After a while using Rancher it is very common to get a large lists of hosts and especially containers.
It is not uncommon to end up with 100s of containers, at this stage I find it very difficult to use the current containers page UI under > infrastracture > containers.

As a Rancher user I would like to have a search to find any container by its name or any of the attributes available to Rancher (host, image, labels etc).

The best would be to add this search functionality on each of the listing pages and as global search (faceted navigation) to entire Rancher so that we also solve the issue of finding Hosts, Load Balancers, Services and other "artifacts" managed by Rancher.

**Comment by smw355** [comment]
+1

**Comment by demarant** [comment]
Other very similar requests #1824  and  #2465 , seems a wanted feature

**Comment by pwFoo** [comment]
+1

**Comment by martinm82** [comment]
+1

**Comment by vincent99** [comment]
Adding to the containers screen for 1.3, once we're happy with that it will go into all the other views.

**Comment by tfiduccia** [comment]
Version - master 12/30
Verified fixed - Search is added to containers page and works on all fields.

**Comment by claflico** [comment]
@vincent99 @tfiduccia 

"Adding to the containers screen for 1.3, once we're happy with that it will go into all the other views."

Sorry to revive an old thread but any word on adding a host filter? I just search both the open and closed issues and don't see any new info.

Would like to be able to filter hosts by their labels...makes it easier when replacing hosts and need to   know what services are running on what hosts.
