### ISSUE TITLE
Rancher can't find catalog apps

### ISSUE THREAD

**Issue by tboemker-bkfs** [rancher/rancher#15349]
When I click Catalog Apps and then Launch, Rancher says, "There are no compatible templates."

I checked the Rancher server container's logs & found this:
[ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp 54.191.5.6:443: i/o timeout

I tried to access that URL from a machine that has direct access to the Internet and got a 404 Not Found.

Has that page moved? https://github.com/rancher/charts seems to have that content now.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
i/o timeout indicates you don't have an outgoing internet connection on the host that the container is running on, or there is something wrong with networking for the pod. If you run `git clone https://git.rancher.io/charts`, the repository is cloned. You can diagnose that inside the container and t ry to debug why it can't get to external locations. If you supply some more info (requested in the issue template), we can take a look at it.

**Comment by tboemker-bkfs** [comment]
Right, this machine is behind a corporate firewall, so I tried to access that URL from a machine that has a direct connection to the Internet. From that machine, I got the 404. I ran the git clone as you suggested and do not see an index.yaml.
Is there a procedure for loading catalog apps into an air-gapped installation?

**Comment by superseb** [comment]
Mirroring the charts repo, and adding it to the Catalogs is the way to get them loaded. For startup behavior, we have this open: https://github.com/rancher/rancher/issues/13700

Regarding the error, it's showing the wrong error as `git clone` fails and it falls back to using HTTP as it were a Helm repo (which needs `index.yaml`). This is going to handled in https://github.com/rancher/rancher/issues/15330.

Let me know if it doesn't work for you.
