### ISSUE TITLE
Rancher shows password field in cluster api

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#15341]
If you created a DO/EC2 cluster, the sshKey of nodes created by docker-machine will show up in cluster api.

**Comment by sangeethah** [comment]
This issue is still seen when testing with latest rancher-server builds.

**Comment by cjellick** [comment]
@mrajashree to validate

**Comment by mrajashree** [comment]
Steps to reproduce in v2.0.8
1. Create DO cluster in rancher v2.0.8
2. Click 'View in API' for cluster
SSH key is seen as per this image
<img width="623" alt="screen shot 2018-09-12 at 12 12 31 pm" src="https://user-images.githubusercontent.com/10672776/45448386-11300500-b687-11e8-86ec-90ccd076bd91.png">

Steps in master
1. Create DO cluster
2. Click 'View in API'
SSH key isn't seen anymore
<img width="561" alt="screen shot 2018-09-12 at 12 13 00 pm" src="https://user-images.githubusercontent.com/10672776/45448425-24db6b80-b687-11e8-850b-6f74a48675d1.png">

Closing as it's fixed
