### ISSUE TITLE
Not Fully Functional UI in the v0.9.1 Docker Image Release

### ISSUE THREAD

**Issue by VincenzoFerme** [rancher/rancher#1535]
Hi,

I've just downloaded the docker image I would like to use for Rancher: v0.9.1 (docker pull rancher/server:v0.9.1)

The UI does not work properly, e.g.,: I can only add custom hosts, I'm not able to specify the labels while adding the hosts. Moreover the hosts do not appear in the hosts interface after following the instruction provided in the new UI.

The image tagged with latest, works properly.

Regards

**Comment by vincent99** [comment]
Tags in the DockerHub list are not sorted by date; v0.9.1 is what Rancher looked like approximately 5 months ago.

**Comment by VincenzoFerme** [comment]
@vincent99 thank you for the fast reply. So the only up to date tag is "latest"?

**Comment by vincent99** [comment]
Until we have a "1.0" release the 2nd digit is just the week number of the year.

So the newest tag is `v0.27.0-rc4`, but there should be a final `v0.27.0` later today.  `latest` is generally the last stable release, which is currently `v0.25.0`.

**Comment by VincenzoFerme** [comment]
@vincent99 nice to know, thanks! I would suggest writing it on Docker Hub, since that way the information can be easily found.
