### ISSUE TITLE
AD login randomly goes sideways

### ISSUE THREAD

**Issue by MaxDiOrio** [rancher/rancher#15350]
Rancher 2.0.7 in a single node setup on VMWare.

We have AD authentication configured.  Every few days to a week, we are either unable to log in, or users lose their permissions, which is done through AD Group membership.

When I log in with the local admin account and go to the AD settings, you see the following in the lower right corner:
Unable to fetch user info
activedirectory_user://CN=DiOrio\, Max,OU=HQ,OU=Users,OU=Accounts,DC=inte.....

I have to edit the AD settings, re-enter the LDAP BIND account password.  Re-test the login with my domain user account.  

Then AD auth starts working again.

I see the following in the messages log:

Aug 29 10:13:11 rancher journal: 2018/08/29 14:13:11 [ERROR] API error response 401 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580

**Comment by FleischKarussel** [comment]
@MaxDiOrio 
I got the same issue on 2.0.8.
Same setup, single Rancher with AD on VMware.

[ERROR] API error response 401 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580

[ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: can't find unique user for principal activedirectory_user: <DN of User that tries to login>

[ERROR] Unknown error: user.management.cattle.io "<DN of the group that is allowed to login> not found

**Comment by cjellick** [comment]
Have either of you upgraded to v2.1.x and if so do you continue to see this problem?

**Comment by debovema** [comment]
Hello,

Using Rancher v2.1.2, the problem still exists.

**Comment by MaxDiOrio** [comment]
Since upgrading to 2.1.1 I haven't had an issue.

**Comment by debovema** [comment]
You are certainly right. My issue looks more like this one https://github.com/rancher/rancher/issues/13666.
Thanks

**Comment by cjellick** [comment]
OP hasnt seen this since 2.1.1. There were many fixes to auth from 2.0.x to 2.1.x. @debovema notes his issues is different - 13666. Closing issue.
