### ISSUE TITLE
installation in the amazon through the marketplace

### ISSUE THREAD

**Issue by GlauberF** [rancher/rancher#15355]
I do not know if anyone can help, but through the amazon marketplace I installed Rancher on RancherOS. set up at the time of installation to use the pair of keys you already had.
The problem is that now when I want to try to connect to the machine using SSH using my .pem file, I can not, he asks me for a password, but I did not register a password

**Comment by loganhz** [comment]
Thanks for your report!

Please resubmit your issue into https://github.com/rancher/os/issues

RancherOS team will reply it.

Thanks a lot.
