### ISSUE TITLE
Update rancher helm chart for HA

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#15361]
Rancher will be deployed as a deployment with a hard anti-affinity rule so that pods won't land on the same

**Comment by jgreat** [comment]
Testing:
Follow docs to build cluster and install cert-manager prerequisite.

 https://github.com/rancher/server-chart repo and checkout the `feature-rancher-ha` branch

Change to the rancher directory
```
cd rancher
```

Use the current directory to install the helm chart. Set your hostname and number of replicas

```
helm install ./ --name rancher --namespace cattle-system --set hostname=jgreat-test-1.rancher.space --set replicas=3
```

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/5

Rancher server pods are being scheduled on separate nodes.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc3
Chart cloned from rancher/server-chart:master and installed from helm using local chart

HA setup with 3 nodes and 3 replicas
Power down one node

Expected: 
* A new rancher pod does not get scheduled to an existing host

Actual: 
* The new pod is scheduled to an existing node (so now there are 2 nodes: one with 2 pods, and one with a single pod)

from @ibuildthecloud 
```
in the chart, `labelSelector` should be a child of `requiredDuringBlahBlahBlah`

there's no field named `podAffinityTerm`
```

**Comment by jgreat** [comment]
https://github.com/rancher/server-chart/pull/22

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc5
Validated with the updated chart and `replicas=3`

Pods are following affinity/anti-affinity rules in deployment correctly:

* Powered down the host containing the leader
* Leader migrated to one of the remaining hosts
* After powered-down host's pod became unknown, the new pod is created, and remains in pending

```
Warning  FailedScheduling  2m (x25 over 4m)  default-scheduler  0/3 nodes are available: 1 node(s) were not ready, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules.
```
 
* Powered up host that was turned off
* Old pod on host is terminated, and new pod is scheduled correctly.
