### ISSUE TITLE
Use websocket when subscribing to events in python-agent and go-machine-service

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1536]
We need to convert to using websocket connections in our services that subscribe to events to accommodate rancher setups behind a proxy.

**Comment by cjellick** [comment]
@sangeethah This introduces no new functionality, but the basic functionality of go-machine-service and python-agent needs regression tested.

Additionally, the ultimate goal of this change is to address the issue that @vincent99 mentions in this comment: https://github.com/rancher/rancher/issues/719#issuecomment-120995776
Specifically, that the instructions here: http://rancher.docs.rancher.com/docs/installing-rancher/installing-server/basic-ssl-config/ require you to turn off buffering and that doing so causes SSL + Github to break.

So, with that in mind, the ultimate test for this would be to setup rancher with ssl following the above instructions (ommitting the two nginx config lines related to buffering).

But, note that if you do that, you will run into this issue: https://github.com/rancher/rancher/issues/1380
Please read my comment about how you should setup host registration with https.

To give you an understanding of what changed: we changed the way we subscribe to events in those two services to better accommodate the typical https setup. Instead of http connections from those services to cattle, we use ws (websocket) connections from them to cattle.

**Comment by cjellick** [comment]
Assigning back to me. This cannot truly be tested until SSL is working 100%.

**Comment by sangeethah** [comment]
Tested with rancher/server:v0.31.0-rc1

Able to bring up a rancher-server with SSL behind Nginx as https reverse proxy.
Following are the steps followed:
```
docker run -d --restart=always --name=rancher-server -e "CATTLE_API_ALLOW_CLIENT_OVERRIDE=true" rancher/server:v0.31.0-rc1
mkdir /root/nginx

docker run -d -p 80:80 -p 443:443 -v /root/nginx/ssl:/etc/nginx/ssl/:ro -v /root/nginx/rancher.io.conf:/etc/nginx/conf.d/rancher.io.conf:ro --link='rancher-server' nginx

nginx confifuration used:

upstream rancher {
    server rancher-server:8080;
}

server {
    listen 443 ssl;
    server_name <servername>;
    ssl_certificate /etc/nginx/ssl/rancher.io.bundled.crt;
    ssl_certificate_key /etc/nginx/ssl/rancher.io.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name <servername>;
    return 301 https://$server_name$request_uri;
}
```
Able to add custom hosts , Digital Ocean hosts to rancher server successfully.
Able to view host stats.
Able to view container logs and also exec shell.
Basic sanity checks to make sure that the connectivity between containers from different hosts work.
