### ISSUE TITLE
Feature Request - EKS - Allow for multiple security groups to be attached to worker nodes

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#15362]
**Rancher versions:**
rancher/rancher: v2.0.8

**Details:**
Similar to #15316 which deals with the control plane security groups... currently the CloudFormation stack that launches the EKS worker nodes creates a security group to allow communication with the cluster control plane. We should be allowed to specify multiple security groups to be automatically attached to the worker nodes along with the automatically created one.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/15316
