### ISSUE TITLE
Set as Default for Environments doesn't show up until you refresh page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1537]
v0.27.0-rc4
Steps:
1.  Go to Environments page
2.  Click on menu for an environment and select "Set as Default login Environment"

Results:
Looks like nothing happened.  You have to refresh the page to see the checkmark take affect.

Expected:
Checkmark should show without having to refresh page.

**Comment by deniseschannon** [comment]
This is still happening in v0.47.0 (new UI).

**Comment by vincent99** [comment]
This was probably fixed by the issue that made saving user prefs actually work a while ago.

**Comment by deniseschannon** [comment]
Verified in v0.63.0 that it sets the checkmark is set on the page.
