### ISSUE TITLE
 The exposed port can not be accessed after a while, for unknown reasons. 

### ISSUE THREAD

**Issue by PeterZhai00** [rancher/rancher#15374]
**Rancher versions:**
rancher/rancher:v2.0.8
rancher/rancher-agent:v2.0.8

**Docker version: **
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-514.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
![image](https://user-images.githubusercontent.com/14885970/44966192-5a3bd700-af6c-11e8-9cc3-18212e937ede.png)
 The port that I exposed was also able to visit at the beginning.  All other namespace are normal.

**Comment by sebastiansirch** [comment]
Might be the same as https://github.com/rancher/rancher/issues/15372 ?
When you can access your port after you have deleted the network policy in your namespace, then it is the same issue, I guess.

**Comment by PeterZhai00** [comment]
Then how can we solve this problem? Our situation is the same.

**Comment by loganhz** [comment]
Can you try it in 2.1.1, please?

If you can reproduce it, can you provide the reproduce steps and the logs, please?
