### ISSUE TITLE
Node scheduling convert issue

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#15379]
rancher/rancher:v2.0.7

Steps to reproduce:
![image](https://user-images.githubusercontent.com/21168270/45017285-ce07dd80-b059-11e8-89de-8d7b31d4a564.png)

1. Go to create workload page and input a name.
2. In `Node Scheduling` section, select `Automatically pick nodes for each pod matching scheduling rules:`
3. Click `Add Custom Rule` in `Require All of` part.
4. Input `build.jenkins.master=build.opstack.xyz`
5. Click `Launch`

Results:

UI send the correct payload to backend. But server converts `build.jenkins.master=build.opstack.xyz` to `build.jenk = s.master=build.opstack.xyz`. 
![image](https://user-images.githubusercontent.com/21168270/45017311-de1fbd00-b059-11e8-824e-6fe328812f62.png)

![image](https://user-images.githubusercontent.com/21168270/45017097-3acea800-b059-11e8-989e-64ba6646747f.png)

Expected:

Server should populate it as `build.jenkins.master=build.opstack.xyz`

Reason:

I think the convert logic in backend is wrong. It replaced `jenkins` to `jenk = s`. The `in` of `jenkins` should not be converted.

**Comment by cjellick** [comment]
@dramich to validate

**Comment by dramich** [comment]
Followed @loganhz steps above to repro on 2.0.7. 
On master 9/13/18 now shows as `"build.jenkins.master = build.opstack.xyz"`.
