### ISSUE TITLE
Control and etcd host disks being filled with leftover volumes from etcd backups

### ISSUE THREAD

**Issue by jacobwgillespie** [rancher/rancher#15388]
This morning my etcd and control plane hosts all set off the `DiskPressure` alarm.  After investigating, it appears that there are lots of dangling volumes left on those hosts.  Inspecting any of the volumes looks like this:

```
[
    {
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/57c76045b136d306b51174959e06753bdba1fc56f0392b36424fd8c3f0759966/_data",
        "Name": "57c76045b136d306b51174959e06753bdba1fc56f0392b36424fd8c3f0759966",
        "Options": {},
        "Scope": "local"
    }
]
```

Listing out the files at that path shows:

```
drwxr-xr-x    2 root     root          4096 Jun 20 18:16 bin
-rwxr-xr-x    1 root     root          2943 Jun 20 18:15 cloud-provider.sh
-rwxr-xr-x    1 root     root          1658 Jun 20 18:15 entrypoint.sh
-rwxr-xr-x    1 root     root       3366656 Jun 20 18:15 rke-etcd-backup
-rwxr-xr-x    1 root     root           121 Jun 20 18:15 weave-loopback-cni.sh
```

This appears to contain etcd backups, however they are being left as dangling Docker volumes and never cleaned up.  As far as I know, I do not have any etcd backups configured.

-----

**Rancher versions:**
rancher/rancher: v2.0.3
rancher/rancher-agent: v2.0.3

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
4.14.32-rancher2
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

```
AWS
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Kubernetes, separate etcd, control, and worker hosts

**Comment by Terminator637** [comment]
I got this issue on rancher 2.1

**Comment by alena1108** [comment]
@galal-hussein

**Comment by Terminator637** [comment]
As a temporary solution, I add the following line to the crontab servers:
0 * * * * / usr / bin / docker system prune -f
to clean dangling docker entities every hour.

**Comment by deniseschannon** [comment]
With the updates around backup/restore in Rancher 2.2, pelase reopen the issue if you still hit this on a 2.2 version.
