### ISSUE TITLE
Add test button to logging endpoint

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#15380]
Add test button to logging like alert, requested from Peng, because some custom may want to save even the target is not reachable by the rancher server, but it may be could be reach by the fluentd agent, because it in the cluster.
1. Try to send one log record to the target or check whether the target is reachable.
2. Let user save the config even the target is not reachable.

**Comment by kingsd041** [comment]
Reopen this issue.
Launch syslog in the project logging, enter a non-existing `Endpoint ` and click the `Test` button. Prompt `Setting validated`

**Comment by aiwantaozi** [comment]
Syslog need to add a field to check whether use tls when send test

**Comment by kingsd041** [comment]
Version: master 2.2 (2/14/19)  Image ID: 9d5bb3a31761
Confirmed fix.
