### ISSUE TITLE
Node labels can be defined at two locations in UI

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15382]
Version: master 9/4

If you hit Advanced Options, you get the option to set Node Labels. In the bottom you have a static part where you can set Labels. This should be one place, or the bottom one needs to be hidden when advanced is clicked as they do not merge.

<img width="1273" alt="screen shot 2018-09-04 at 10 53 24" src="https://user-images.githubusercontent.com/2620179/45021141-16f76c00-b031-11e8-9cc5-964f24208b4c.png">

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
