### ISSUE TITLE
Update port, service configuration not updated

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#15384]
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**

1、Create a workload named demo ,select the nginx image and set the mapping port 8080；
2、Update the workload and modify the port to 80；
3、Switch to Service Discovery，view the yaml configuration of the demo service(not demo-nodeport)；
<img width="964" alt="image" src="https://user-images.githubusercontent.com/20707603/45022604-3c9f6800-b067-11e8-88e8-eb461a8f7d9e.png">
<img width="768" alt="image" src="https://user-images.githubusercontent.com/20707603/45022628-4923c080-b067-11e8-804f-a90a5741ab0a.png">
4、Create a new workload, login to the terminal, curl `demo` service (The result is no response);
<img width="366" alt="image" src="https://user-images.githubusercontent.com/20707603/45022858-d535e800-b067-11e8-8d2d-e02a21e42298.png">
5、Login to the host where the demo pod is located，view iptable nat rule table
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/20707603/45023498-301c0f00-b069-11e8-9aec-a1768d5798d8.png">

**Results:**

After updating the workload, the demo service configuration is not updated, and the iptable nat rule is not updated, causing the demo service to be inaccessible.

**Comment by sangeethah** [comment]
Able to reproduce this issue v2.0.8

Tested the following scenario using v2.1.0-rc3.

1. Create a workload named demo ,select the nginx image and set the mapping port 8080
2. Update the workload and modify the port to 80
3. Create a new workload, login to the terminal, curl demo service.
Able to reach demo service successfully.

<img width="1202" alt="screen shot 2018-09-19 at 11 25 51 am" src="https://user-images.githubusercontent.com/4266958/45773301-cbcb8480-bbfe-11e8-8808-1097b0579d49.png">

4. yaml configuration for the demo service points to  the correct port - 80.

<img width="1213" alt="screen shot 2018-09-19 at 11 27 23 am" src="https://user-images.githubusercontent.com/4266958/45773377-003f4080-bbff-11e8-828e-258c63ad5404.png">


NAT rules also point to correct port 80.
```
root@ip-172-31-9-171:/home/ubuntu# iptables-save | grep 10.42.0.11
-A KUBE-SEP-OETZZ3IR6TWQQZYD -s 10.42.0.11/32 -m comment --comment "default/demo-nodeport:8080tcp01" -j KUBE-MARK-MASQ
-A KUBE-SEP-OETZZ3IR6TWQQZYD -p tcp -m comment --comment "default/demo-nodeport:8080tcp01" -m tcp -j DNAT --to-destination 10.42.0.11:80
-A KUBE-SEP-VC2IFRFKB4I46JJX -s 10.42.0.11/32 -m comment --comment "default/demo:8080tcp01-demo" -j KUBE-MARK-MASQ
-A KUBE-SEP-VC2IFRFKB4I46JJX -p tcp -m comment --comment "default/demo:8080tcp01-demo" -m tcp -j DNAT --to-destination 10.42.0.11:80
```
