### ISSUE TITLE
I create a namespace and be named 'test' in project A，but i can not use the 'test' namesapce in project B

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#15381]
I create a namespace and be named 'test' in project A，but i can not use the 'test' namesapce in project B

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by vincent99** [comment]
Namespace names must be unique within a cluster.  This is a basic design constraint of kubernetes.  A project is a group of namespaces but does not change anything about their uniqueness.
