### ISSUE TITLE
Upgrading workloads (with sidecars) not working properly

### ISSUE THREAD

**Issue by qdrop17** [rancher/rancher#15387]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/rancher:stable
rancher/agent or rancher/rancher-agent: rancher/rancher-agent:v2.0.8

**Infrastructure Stack versions:**
healthcheck: (bundeled with stable rancher version)
ipsec: (bundeled with stable rancher version)
network-services: (bundeled with stable rancher version)
scheduler: (bundeled with stable rancher version)
kubernetes (if applicable): (bundeled with stable rancher version)

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 16.04: 4.4.0-134-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Digital-Ocean Droplets

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

1 rancher-server, 1 node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

1. Create a workload: 1 pod with a mongo-db and one sidecar with an application that connects to the mongo-db.
2. Upgrade either workload via UI.
3. Check if the images are pulled (like configured) and deployed.

**Results:**

The upgrade only works like 1-2 times. After that, when upgrading nothing happens.
When I pause the orchestration and resume it - the workload gets upgraded immediately.

I expect Rancher to always upgrade workloads when I trigger this. Either via UI or API.

**Comment by qdrop17** [comment]
Maybe this has to do with the following issue: https://forums.rancher.com/t/upgrade-deployment-image-with-rancher-2-0/10399/9

**Comment by loganhz** [comment]
Did you change anything such as image id when you upgrade the workload?

**Comment by qdrop17** [comment]
> Did you change anything such as image id when you upgrade the workload?

no, I basically just edit the workload und click on "Upgrade" (or send a similar request via cURL. Sometimes nothing happens after doing so and only after stopping and resuming orchestration, the services get upgraded.

**Comment by loganhz** [comment]
There is a limitation in k8s. If you don't change anything, you can not upgrade the workload even with `kubectl apply`.  So nothing will happen.

I guess the pod/deployment was not created by Rancher API (maybe it's created by helm or kubectl)  and in Rancher UI if you upgraded it,  some annotation fields would be added. It might explain why it works once.

In 2.1.1, `Redeploy` action is introduced in Rancher UI. It will trigger the upgrade every time.

**Comment by vincent99** [comment]
The way k8s works is that if nothing in the workload definition has changed then updating it does nothing.  So "working" the first time is actually one of a couple bugs where on edit we send a slight variation of the definition than what was initially saved, and this causes and update.  Subsequent times that does not happen so nothing has changed and no pods are replaced.

2.1 contains fixes for those issues where things accidentally change, and separately the UI always sets an annotation on edit to the current time, so that something has always changed and "upgrade" does what people expect.  Also there's a "Redeploy" action that does the same without having to go through edit at all.

**Comment by qdrop17** [comment]
> There is a limitation in k8s. If you don't change anything, you can not upgrade the workload even with `kubectl apply`. So nothing will happen.
> 
> I guess the pod/deployment was not created by Rancher API (maybe it's created by helm or kubectl) and in Rancher UI if you upgraded it, some annotation fields would be added. It might explain why it works once.
> 
> In 2.1.1, `Redeploy` action is introduced in Rancher UI. It will trigger the upgrade every time.

> The way k8s works is that if nothing in the workload definition has changed then updating it does nothing. So "working" the first time is actually one of a couple bugs where on edit we send a slight variation of the definition than what was initially saved, and this causes an update. Subsequent times that does not happen, so nothing has changed and no pods are replaced.
> 
> 2.1 contains fixes for those issues where things accidentally change, which would make just clicking edit->upgrade never replace pods. And separately the UI always sets an annotation on edit to the current time, so that something has always changed and "upgrade" does what people expect. Also there's a "Redeploy" action that does the same without having to go through edit at all.
> 
> If you are making requests to the API then you must set an annotation or similar yourself to ensure that something has changed.

Thank you very much for clarifying! That helped me a lot 👍 . Great stuff you're doing here!
