### ISSUE TITLE
Catalog Apps: After clone, upgrade is not possible

### ISSUE THREAD

**Issue by kohlerdominik** [rancher/rancher#15385]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.7
rancher/ui: 2.0.67

**Steps to Reproduce:**
* Click "Clone" on an existing Catalog App (no need to actually execute the clone)
* Go back to Catalog App Overview
* Click "Upgrade" on an existing Catalog App
-> clone page opens

* Hit F5 (reload page)
* Click "Upgrade"
-> upgrade page opens

**Results:**
After choosing clone of any App in the Catalog, it's no longer possible to upgrade an existing App, as clicking "Upgrade" also does the same as "Clone".

**Possible Fix:**
It may be enough to add parameter "clone=false" to the upgrade action. But i've no possibility to test right now.

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
