### ISSUE TITLE
Environment menu is cutoff on right side of browser window

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1538]
Steps:
1.  go to environment page
2.  CLick on menu for a environment

Results:  The menu is being cutoff on the right side.  This is also happening in the Environments detail page.
![image](https://cloud.githubusercontent.com/assets/11514927/8706236/942f696a-2ae3-11e5-9bbb-5cb9c2ea9cf2.png)

![image](https://cloud.githubusercontent.com/assets/11514927/8706386/5ac9b2c4-2ae4-11e5-9f22-5443f5b6f948.png)

Expected:
End of Menu should really align with right side of page instead of going off and having to scroll.

**Comment by deniseschannon** [comment]
Verified with UI v0.59.0
