### ISSUE TITLE
Update alertmanager image to avoid Pagerduty logging

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15397]
Commit 
 https://github.com/prometheus/alertmanager/commit/b62cddd807b2e2e098656611647ca726d0c2caa3#diff-4db7d0a3c6c390eca781a4477b6ba727 is included in `v0.12.0` and higher.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc7

Prometheus image has been updated to v0.15.2
