### ISSUE TITLE
With https on, you get mixed content errors in resourcedot graphs part of the API UI

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1539]
If you have ssl turned on and you try to access one of the resourcedot graphs, like:
`https://<server>/v1/resourcedefinitions/1rd!physicalhost/resourcedot`,
you get  mix content error:

```
Mixed Content: The page at 'https://<server>/v1/resourcedefinitions/1rd!physicalhost/resourcedot' was loaded over HTTPS, but requested an insecure script 'http://mdaines.github.io/viz.js/viz.js'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by vincent99** [comment]
This is technically Cattle returning HTML with that URL in it...  @cjellick https://github.com/rancher/cattle/pull/693

**Comment by cjellick** [comment]
OK, great.

**Comment by cjellick** [comment]
I'll assign this over to test when all the other ssl issues are resolved.

**Comment by sangeethah** [comment]
Tested with rancher/server:v0.31.0-rc1.
Able to access https://<domain name>/v1/resourcedefinitions/1rd!externalhandler/resourcedot  for  a rancher-server with SSL enabled behind Nginx as https reverse proxy.
