### ISSUE TITLE
implement log rotate on messages file in ranchers ingress image

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#15398]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.18
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck: v0.3.6
ipsec: v0.2.4
network-services: v0.2.9
kubernetes (if applicable):  v1.10.3-rancher1-1
ingress image: rancher/lb-service-haproxy:v0.9.1

**Steps to Reproduce:**
1. create an ingress
2. over time the `/var/log/messages` file will grow to something massive
3. ideally cull things in `/var/log`

**Comment by aemneina** [comment]
```config: "defaults\nlog 127.0.0.1:8514 local0 info\noption httplog\ntimeout client 50000\ntimeout connect 5000\ntimeout server 50000"```

haproxy logging is enabled here.

**Comment by kinarashah** [comment]
When haproxy logging is enabled, all haproxy related logs go to `var/log/haproxy`. We used to log everything else (for eg, syslog logs) as a catch all in `var/log/messages`. 
So we won't be logging anything there now onwards instead of log rotating or filtering what goes in there.
