### ISSUE TITLE
Feature Request - EKS - Create the EKS cluster with the same name as in Rancher

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#15390]
Rancher versions:
rancher/rancher: v2.0.8

Details:
The cloudformation template is being passed the unique ID of the cluster. This should instead match the given name directly in Rancher. The "ClusterName" cloudformation parameter needs updated.

**Comment by nathan-jenan-rancher** [comment]
To solve this issue technically would require a modification to kontainer-engine to change how it names and retrieves clusters.  This would be relatively straightforward for new clusters.  To ensure compatibility with existing clusters we would need to add in logic to compensate for the misnamed cluster.  I would suggest the following:
Create cluster:
```
1. Change create to be based on display name, not cluster id
```
Retrieve cluster:
```
1. Attempt to retrieve cluster based on display name. 
2. if 1 fails, attempt to retrieve based on cluster id
3. continue as normal
```
Update cluster:
```
1. attempt to retrieve cluster based on display name
2. if 1 fails, attempt to retrieve based on cluster id, set flag that cluster uses old style naming
3. continue as normal until update operation
4. if cluster uses old style naming, update based on cluster id name, else update based on display name
```
Delete cluster:
```
1. attempt to delete cluster based on display name
2. if 1 fails, attempt to delete cluster based on cluster id
```

**Comment by cjellick** [comment]
Let's resync soon on backwards compatibility @nathan-jenan-rancher. Its possible we misunderstood each other. But either way, your analysis still stands.

**Comment by nathan-jenan-rancher** [comment]
The following resources will now be explicitly passed the display name of the cluster:
- EKS cluster
- service role stack
- vpc stack
- worker nodes stack
- key pair
