### ISSUE TITLE
Add/Update Alerts to use PagerDuty v2 Events API

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15395]
Currently we post to Events API v1, which will log a warning about deprecation (annoying). Events API v2 has support for PagerDuty Common Event Format (PD-CEF) (https://v2.developer.pagerduty.com/docs/events-api-v2#pagerduty-common-event-format-pd-cef) as well.

**Comment by bmdepesa** [comment]
rancher/rancher:master 12/27

* Created PagerDuty account
* Within PagerDuty, add a new service with v2 api integration
* Created PagerDuty notifier within Rancher using integration key for PagerDuty v2 api integration service
* Notifications successfully sent to PagerDuty
* Did not see log statements regarding PagerDuty events api v1 deprecation
