### ISSUE TITLE
Configurable notifiers parameters are confusing

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15393]
Version: master 9/4

Steps to reproduce:

1. Create a notifier and configure needed parameters (For example, PagerDuty with the servicekey)
2. Create an alert and choose this Notifier, the UI shows a field to re-enter servicekey which is redundant.

I think in general we should stay away from configurable parameters on notifiers in alerts, possibly the Slack channel parameter is a good example. But to avoid any mess, maybe staying with static notifiers/alerts and coupling them is the best option.

Other issue is that the shown asterisks (`***`) are actually passed onto the UI, so you need to fill out the servicekey again with the correct value.

**Comment by aiwantaozi** [comment]
Hi, by the current design, when you add an alert, user could select default notifier and rewrite the default notifier info. For example, The page duty endpoint for all user are the same, but the Service Key is different. When user try to send multiple alert, user could configure like below:
![image](https://user-images.githubusercontent.com/5936271/45334502-9646eb80-b5ad-11e8-8345-9903b32acac1.png)

For Slack:
The Webhook for all channel is the same, user config the default channel in notifier, and could add multiple channels like below:
![image](https://user-images.githubusercontent.com/5936271/45334609-14a38d80-b5ae-11e8-9a54-98c68612d091.png)

**Comment by superseb** [comment]
Ok, this needs better guidance in the UI.

* When creating a Notifier, say that the configurable part is the default and that it can be overridden when selecting this Notifier when creating an Alert. (It only says Default for Slack and E-mail, but it needs a line saying the above for every Notifier)
* When selecting a Notifier, tell the user it is using the configured default and can be overridden.

@aiwantaozi Can you confirm that the asterisks shown for the PagerDuty Service Key (and are actually submitted and used as asterisks) is a bug? I will file a new issue for that after.

**Comment by aiwantaozi** [comment]
The asterisks not a bug, the project level user could use the notifier that the cluster admin config, but they don't have the authority to access the key. The overwrite also use for this, project user could not access the cluster level notifier, but they could use the default one or config their's

@n313893254 Could you help improve the UI side as superseb comment above?

**Comment by superseb** [comment]
Enhancements Slack:
* Rename `Default Recipient (Channel)` -> `Default Channel`
* Help text for `Default Channel` should be, `Optional. By default, notifications are sent to the default channel of the Incoming WebHook. When configuring an Alert, the channel can be overridden.`

Enhancements Email:
* Help text for `Default Recipient Address` should be, `When configuring an Alert, the recipient can be overridden.`

Enhancements PagerDuty:
* Rename `Integration Key` -> `Default Integration Key`
* Help text for `Integration Key` should be, `When configuring an Alert, the Integration Key can be overridden.`

Enhancements Notifiers view:
* Change the entered Defaults titles for Notifiers
  * Slack: `Channel: #random` -> `Default Channel: #random`
  * Email: `Address: john@localhost` -> `Default Recipient Address: john@localhost`

Enhancements Add Alerts view:
* In the Notifier dropdown, add the Type of the Notifier after the name in like `Name (Slack)`.
* Help text for Notification parameter should be `The value set in the Notifier is used by default. You can override this with another value.`

Enhancements Alerts view:
* Add/Change Recipients to Notifiers, as it shows the Notifier name and not the recipient
* Add the Type of notifier after the name or in another column

**Comment by n313893254** [comment]
@superseb 
Re Enhancements Alerts view:
- I think Recipients is better because Add Alerts view is Add Recipients.
- An alert will have many Recipients, so it will better to display like `Name (Slack)`.
![image](https://user-images.githubusercontent.com/18737885/45527640-48c9b900-b80f-11e8-9873-c1a9c0eebe59.png)

What do you think?

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/20
Everything is done except this 1 thing:

Enhancements Alerts view:
Add/Change Recipients to Notifiers, as it shows the Notifier name and not the recipient

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/24
Verified fixed
