### ISSUE TITLE
Cluster options in Edit as a Form are not all configurable in current Edit as YAML option

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15396]
Version: master 4/9

Cluster Options is switchable between `Edit as YAML` and `Edit as a Form`. Problem is that it switches as it can all be configured in the `Edit as YAML` but some of the options on the screen are Rancher only, i.e. Project Network Isolation/Docker Root Directory. The YAML is posted as `rancherKubernetesEngineConfig`, while those options live in the root. The either need to be split out so make sure it's clear its Cluster vs Rancher or we need to make it configurable at the root when choosing `Edit as YAML`.

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/29
The Edit Cluster, then View as YAML seems to have a lot more info that is unnecessary.  The Add cluster has:
![image](https://user-images.githubusercontent.com/11514927/51946307-578bc380-23de-11e9-8ae7-0b2c03988a7e.png)

The edit Cluster has:
![image](https://user-images.githubusercontent.com/11514927/51946347-6ecab100-23de-11e9-9f65-b594c400d82c.png)

I think they are supposed to match?  I asked Vincent and he said that we shouldn't show the read-only fields.

**Comment by loganhz** [comment]
Thanks @tfiduccia 
Please remove the readonly field @n313893254 . It really doesn't make sense to show them here

**Comment by tfiduccia** [comment]
Version - master 3/11
Verified fixed
