### ISSUE TITLE
Mount point info not showing for sidecar (and main pod info is showing only on workload)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15391]
**Rancher versions:** 2.1 master 9/4

**Steps to Reproduce:**
1.  Create a workload and add a volume with a mount point
2.  Add a sidecar to that workload and add another mount point
3.  Go to workload details
4.  Go to main pod and sidecar details

**Results:**  The mount point for the main pod is showing up in the workload details and the sidecar mount isn't showing up anywhere.  Mount points are specific to the pod and should show up on the pod details pages.  Also if you want to show mount points on the workload level, you should show all mount points.

**Comment by loganhz** [comment]
Volumes section has been added in the pod detail page.

**Comment by loganhz** [comment]
Fixed in Rancher 2.1
