### ISSUE TITLE
How can i create a ingress rule ?

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#15407]
I have create a workload and can be accessed by www.abc.com，how can i create ingress rule ?
I can not access  http://www.abc.com/nginx and the error code is ‘404 Not Found’

![image](https://user-images.githubusercontent.com/14210543/45068731-7b7efd80-b0fb-11e8-8015-72dc7017515a.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`ingresses.run`|

**Comment by loganhz** [comment]
You need to add an annotation for the ingress in UI.

`nginx.ingress.kubernetes.io/rewrite-target: /`

![image](https://user-images.githubusercontent.com/21168270/46580820-a2b04e00-ca5e-11e8-946e-389499d7326f.png)

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rewrite

**Comment by scndel** [comment]
@loganhz , I've found this proper config by myself but it gave me some headache.
Why annotation `nginx.ingress.kubernetes.io/rewrite-target: /`
isn't added automatically to yaml if the load balancing UI of Rancher offers a field to define the path ?
