### ISSUE TITLE
Port requirement port is wrong in doc for canal

### ISSUE THREAD

**Issue by corentin59** [rancher/rancher#15415]
Ports for canal are 8472 (VXLAN) and 9099 (healthcheck) in UDP mode

![2018-09-05 17_19_17-port requirements _ rancher labs](https://user-images.githubusercontent.com/2035983/45103366-0da0f900-b130-11e8-8b1a-87c37cbdfcda.png)

Canal doc (readme)
![2018-09-05 17_22_31-cni providers _ rancher labs](https://user-images.githubusercontent.com/2035983/45103516-5789df00-b130-11e8-81f2-29ac50ee0d1e.png)

After change 9099 in UDP mode (vs TCP), my HA cluster is up !

**Comment by superseb** [comment]
The readiness/livenessprobes are defined here: https://github.com/rancher/rke/blob/bcb6e13618f03e8b57957d89cde3232b937eeb99/templates/canal.go#L318 and are `httpGet`.

Can you link to the page where you find the the text in the screenshot as it does not show on https://github.com/projectcalico/canal/blob/master/README.md

**Comment by corentin59** [comment]
Sorry, it's not on the official canal doc, here :
https://rancher.com/docs/rancher/v2.x/en/faq/networking/cni-providers/

**Comment by superseb** [comment]
The port requirements are described here: https://rancher.com/docs/rancher/v2.x/en/installation/references/

I have created this PR (https://github.com/rancher/docs/pull/774) to make the distinction between UDP and TCP.

If you still have issues setting up the cluster based on this, let me know.
