### ISSUE TITLE
When 2 nodes were added to an existing cluster with 1 node , cluster gets stuck in "updating" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15422]
Rancher versions:  Build from master 

**Steps to Reproduce:**

Created a DO cluster with 1 node with all roles.
Once the cluster was created and got to "Active" state , Increased the node pool size to 3.
When 2 new nodes got added , cluster gets stuck in "Updating" state for a long time .

Following error message is presented to the user:
```
Failed to get kubernetes node [santestnew1]: "santestnew1" not found..https://206.81.5.129/c/c-z2pb9/nodes
```

Findings from the logs:
I see RKE cluster provisioning attempted multiple times in rancher-server.

The first run on this node succeeded, after added two more nodes, rke couldn't fetch the cluster state successfully:
```2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: Building Kubernetes cluster
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: [dialer] Setup tunnel for host [159.89.183.176]
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: [dialer] Setup tunnel for host [165.227.125.107]
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: [dialer] Setup tunnel for host [159.89.183.188]
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: [state] Found local kube config file, trying to get state from cluster
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: [reconcile] Local config is not valid, rebuilding admin config
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: [reconcile] Rebuilding and updating local kube config
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-608935080/kube_config_cluster.yml]
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-608935080/kube_config_cluster.yml]
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-608935080/kube_config_cluster.yml]
2018/09/05 01:38:10 [INFO] cluster [c-z2pb9] provisioning: [state] Fetching cluster state from Kubernetes
....
2018/09/05 01:38:40 [INFO] cluster [c-z2pb9] provisioning: Timed out waiting for kubernetes cluster to get state
```
 
Since rke couldn't reconcile the cluster, it launched etcd on the two new nodes, and we ended up with a split brain situationwhere 2 etcd clusters were provisioned

Cluster itself now has only 2 nodes (  2nd and the 3rd node) .
Also this cluster is not really functional. When i try to deploy pods , I get the following errors:

```
Error from server (ServerTimeout): error when creating "configmap.yml": No API token found for service account "default", retry after the token is automatically created and added to the service account
Error from server (ServerTimeout): error when creating "configmap.yml": No API token found for service account "default", retry after the token is automatically created and added to the service account
```

**Comment by galal-hussein** [comment]
I was able to reproduce the issue in **rke** using the following steps:

1- run `rke up` on 1 node with all roles
2- ssh to this node and stop kubeapi contianer `docker stop kube-apiserver`
3- add 2 more nodes to the cluster.yml and run `rke up` again

rke will be able to connect to all three nodes, but will not be able to fetch the **state** from k8s since kubeapi is down, so it will skip reconciliation since there is no state and will attempt to deploy components normally (NOTE: certs are fetched normally from the backup dir on hosts).

In the described above case etcd will have split brain situation, where two clusters will be created, the first node will have a cluster with 1 node, the 2nd and 3rd nodes will have a 3 node etcd cluster with node 1 down:

etcd cluster 1 on node 1
```
/ # etcdctl member list
8934fd1b0eff8b7b, started, etcd-52.56.186.77, https://52.56.186.77:2380, https://52.56.186.77:2379,https://52.56.186.77:4001
```

etcd cluster 2 on node 2,3
```
/ # etcdctl member list
59aa20e988f8760e, started, etcd-35.176.171.41, https://35.176.171.41:2380, https://35.176.171.41:2379,https://35.176.171.41:4001
8934fd1b0eff8b7b, started, etcd-52.56.186.77, https://52.56.186.77:2380, 
aa23bdb215f7b8c9, started, etcd-35.176.120.145, https://35.176.120.145:2380, https://35.176.120.145:2379,https://35.176.120.145:4001
```

so we will end up with two kubernetes clusters:
```
➜  kubectl get nodes
NAME             STATUS     ROLES     AGE       VERSION
35.176.120.145   NotReady   <none>    12m       v1.11.2
35.176.171.41    NotReady   <none>    12m       v1.11.2
```
```
➜ kubectl get nodes 
NAME           STATUS    ROLES                      AGE       VERSION
52.56.186.77   Ready     controlplane,etcd,worker   21m       v1.11.2
```

i propose we store the state on the servers as a backup like we store certificates exactly, so that if rke can't fetch it from k8s then it can fetch it from the servers.

@alena1108 @cjellick thoughts?

**Comment by alena1108** [comment]
@galal-hussein Clarification - all 3 nodes here are etcd nodes. 
Looks like bringing up the first node with etcd/master node component first, before adding the other 2 etcd nodes, will fix the situation.

**Comment by cjellick** [comment]
Heads up @alena1108  - I just moved this to review. looked like it was in the wrong column

**Comment by sangeethah** [comment]
Tested with v2.1.0-rc3

Created a  DO cluster with 1 node having all roles.
Waited for the cluster to get active.
Stopped kube-apiserver container from the node.
Added 2 more nodes to the cluster with all roles.

Nodes get stuck in Registering state - "Waiting to register with Kubernetes".
Cluster gets stuck in "Updating" state with error message - 
"[network] Host [165.227.114.239] is not able to connect to the following ports: [165.227.177.83:6443]. Please check network policies and firewall rules"

**Comment by sangeethah** [comment]
Tested with latest build from master.

Created a DO cluster with 1 node having all roles.
Waited for the cluster to get active.
Stopped kube-apiserver container from the node.
Added 2 more nodes to the cluster with all roles.

2 nodes were able to get added successfully to the cluster.
kube-apiserver that was stopped was started by RKE during the provisioning process.
