### ISSUE TITLE
Handle more error situations regarding using certs in rancher container

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15424]
With the introduction of `--no-cacerts`, we have more options to check for validity when using certificates in the container. Also, some common errors like mounting cert but not the key (or other way around) are currently not caught in the validation.

**Comment by cjellick** [comment]
@dramich to validate

**Comment by cjellick** [comment]
@prachidamle to validate

**Comment by cjellick** [comment]
(have to move dan to something else)

**Comment by prachidamle** [comment]
@superseb Would you be able to provide some steps to reproduce and validate this fix?

**Comment by superseb** [comment]
To validate:
* Generate certificates (needs Docker installed, or use what you already have)
```
curl https://gist.githubusercontent.com/superseb/b2c1d6c9baa32609a49ee117a27bc700/raw/7cb196e974e13b213ac6ec3105971dd5e21e4c66/selfsignedcert.sh | bash -s -- test.example.com
```

* Run any invalid certificate configuration, container should log the error and exit:

Mount all certificates and specify `--no-cacerts`, should fail cause of conflicting mounted cacerts.pem and `--no-cacerts`.
```
docker run -d -p 80:80 -p 443:443 -v /root/certs/cert.pem:/etc/rancher/ssl/cert.pem -v /root/certs/key.pem:/etc/rancher/ssl/key.pem -v /root/certs/ca.pem:/etc/rancher/ssl/cacerts.pem rancher/rancher:v2.2.0-rc2 --no-cacerts
```

Mount certificate and key, do not mount `cacerts.pem` and not specify `--no-cacerts`, should fail cause it needs `--no-cacerts` is there is no `cacerts.pem` mounted
```
docker run -d -p 80:80 -p 443:443 -v /root/certs/cert.pem:/etc/rancher/ssl/cert.pem -v /root/certs/key.pem:/etc/rancher/ssl/key.pem rancher/rancher:v2.2.0-rc2
```

Mount only the certificate and not the key, or mount the key and not the certificate, should fail:
```
docker run -d -p 80:80 -p 443:443 -v /root/certs/key.pem:/etc/rancher/ssl/key.pem rancher/rancher:v2.2.0-rc2
```

All the documented ways should still work, https://rancher.com/docs/rancher/v2.x/en/installation/single-node/

**Comment by prachidamle** [comment]
Validated this issue with the stes provided by @superseb 
- Launched a node and installed docker
- Generated new certs
- Test launching rancher/rancher and providing invalid cert options:
 --- Using cacerts.pem and providing --nocacerts as well
 --- Mount certificate and key, do not mount cacerts.pem and not specify --no-cacerts
 --- Mount only cert or key

Observed that the errors are thrown when cert options are not provided correctly. 
The rancher/rancher container exits by logging the errors.

**Comment by cjellick** [comment]
validate lgtm
