### ISSUE TITLE
[UI] Accessing unauthenticated URL doesn't get redirected to the same URL after login

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#15429]
Rancher v2.0.8

- Launch Ubuntu Container
- "Cmd" + Click "Execute Shell" to open the shell in a new tab/window
- Grab the URL
- Open a new incognito window and access the above URL
- Gets redirected to Login
- After login, the UI doesn't redirect back to the original URL, instead shows the Global Page.

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
