### ISSUE TITLE
Show resource usage in overall hosts view

### ISSUE THREAD

**Issue by Kelindar** [rancher/rancher#1542]
Would be nice to show the aggregate resource usage (CPU, Memory, Disk and maybe Networking) of the host machine in the "Hosts" view. Some simple and compact representation, a crude suggestion below. This would allow to quickly see which machines are overburdened.

![image](https://cloud.githubusercontent.com/assets/583116/8709695/328a5f72-2b3c-11e5-8e98-16ce182e3c0f.png)

**Comment by wlan0** [comment]
:+1:

**Comment by faddat** [comment]
This would be great, I like anything that helps rancher improve its ability to deliver complex information at a glance.

**Comment by vincent99** [comment]
Yes.. we actually have that information in the Host resources in the API already but I haven't shown it because there isn't a `resource.change` event for when it is updated...

**Comment by deniseschannon** [comment]
First, we need @ibuildthecloud to make the stats update more often. Then @vincent99 could show it in the UI.

**Comment by dkiser** [comment]
+1

**Comment by demarant** [comment]
+1
nice!
btw this was exactly what I asked in #3344 which was closed in favour of #2718
glad to see it here again!

**Comment by sshipway** [comment]
+1 -- I hadn't seen this before I created #2616 

In addition, I would like to see an Environment-level summary of capacity used shown at the top of the Hosts screen.  This could also have a 'Balance' statistic calculated by the standard deviation of the set of Host usage figures, to show how well balanced the Environment usage is.

Being able to view a graph of historical data online (one graph showing the overall Environment usage, with minor lines for individual Hosts to highlight balance issues) would be of value, too.

**Comment by djskinner** [comment]
+1 for showing the actual disk usage in the Rancher UI, a simple % disk usage would be extremely useful inrformation. The Prometheus catalog entry is good for the rest.

**Comment by will-chan** [comment]
Closing as we are adding a 2.0 UI.

**Comment by arvalaan** [comment]
Would love to know the status of this! What's the plan of UI 2.0?

**Comment by superseb** [comment]
@vincent99 Can you share if this is planned for 2.0?

**Comment by karlatkinson** [comment]
Where can i track the status of 2.0? Was looking for this feature as it seems an important missing metric.

**Comment by andrewperry** [comment]
Closed and forgotten? 2.11.1 in 2025 and no sign of disk usage.#2616 #2476
