### ISSUE TITLE
Do not show "Drain"/"Cordon" option on hosts that are in "Registering"/"Unavailable" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15430]
**Rancher versions:** Build from master
**Steps to Reproduce:**

Create a cluster with few nodes.
When worker nodes are still in "Registering"/"Unavailable" state , "Drain"/"Cordon" options are shown as options.

After nodes get to "Active" state , power down the host so they get to "Unavailable" state.
When worker nodes have "Drain"/"Cordon" options .

In both these cases , user should not be presented with "Drain"/"Cordon" option

**Comment by sangeethah** [comment]
Tested with latest build from master.

@kinarashah We dont show the Cordon and Drain option anymore for "Registering"/"Unavailable" hosts.
Can we also not show them for hosts in "Provisioning" state ?

**Comment by kinarashah** [comment]
Also need to now show drain when the node is in drained state already.

**Comment by sangeethah** [comment]
Tested with latest build from master.
"Drain"/"Cordon" option not shown on hosts that are in "Registering"/"Unavailable" state.
