### ISSUE TITLE
Only show pipeline stuff to project owners

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#15437]
Now when users use pipelines in a project, a dedicated namespace is created in the project, with a bunch of resources in it. The stuff is usually not general project members' concern, so it would be nice if these pipeline related resources are only visible to the project owners.

**Comment by gitlawr** [comment]
cc @cloudnautique

**Comment by gitlawr** [comment]
There's little difference between project members and owners from the RBAC perspective in user clusters. So we probably need to introduce some extra rules for the goal.

**Comment by cjellick** [comment]
I think this is drawing too fine a line between project member and owner. The primary difference between the two is currently 1) the ability to update or delete the project itself 2) the ability to invite other members. Making such a fine distinction (they can see _this_ namespace in the namespace, but not _that_ namespace in the project). We've typically treated members as having full access to the resources in the project (or environment in 1.6).
