### ISSUE TITLE
Make hosts interchangeable, rancher re-deploys if host goes down

### ISSUE THREAD

**Issue by faddat** [rancher/rancher#1543]
I don't know if this is the best title.  What I mean is replaceable, such as:

So google's got these new preemptible VMs.  They cost 70% less than one's average VMs.  If Rancher had a mode where it was shooting for high redundnancy with containers on one or more hosts, then one could quite likely use these intriguing gems of value from google, even in production  Storage would need to be remote to the cluster, though-- a storage pool.  Compute, Storage, Networking (cheap, cheap, cheap) by Rancher, and 100% awesome.

**Comment by vincent99** [comment]
It seems like it's possible to do this today with services and a bit of scripting:
  1. Start `rancher/server` and any persistent storage you need* on not-preemptible VMs.
  1. Write a script that runs when a preemptible VM is created that automatically registers itself into the rancher server with a label like `preemptible = yes`
  1. Create services with the scale "Always run one instance of this container on every host"  and scheduling rule like "The host must have a host label of `preemptible = yes`"
  1. The clever bit: When a new VM comes up and registers itself, Rancher will automatically start containers for those services.
  1. Write another script that runs during the shutdown signal Google sends that deactivates & deletes the host.  This will make it go away in Rancher before Google kills it a minute later.
  1. ???
  1. Profit!

*: As Ceph, GlusterFS, a NFS server container, or whatever else works for you.  We're working on a better story for persistent storage.

**Comment by faddat** [comment]
very cool!  I guess I just need to figure out how to be insanely sure that when hosts go down, new ones come up.  I can see this improving every aspect of our workflow.  If we have a *ton* of preemptible instances, easier to set and forget.

When I set up an LB in Rancher, will it pair traffic with the nearest (ping-wise) host? If so, then..... well, then I'm tickled pink and pleased as punch.

**Comment by faddat** [comment]
"Write another script that runs during the shutdown signal Google sends that deactivates & deletes the host. This will make it go away in Rancher before Google kills it a minute later"

That is where i am going to stick the gcloud command to raise up the next one.

**Comment by faddat** [comment]
This is going to be neat, I can visualize how it will work now.  Basically at least 2 application instances running at any given time, and possibly (how does one do this?) mirrored DBs, so that:

Anything something is preempted, there is at least 1 instance up and running.  Hm.  Better make that 3.  Could probably get away with 2, but who knows....
