### ISSUE TITLE
The cluster supports  custom registered address (server_url) and custom default image repository address

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#15433]
## Usage scenarios

In many large enterprises, their internal networks cannot access the Internet and can only communicate internally `(Full offline environment)`. In a hybrid cloud deployment K8S scenario ,The rancher server runs on a host with a public IP address , The internal network address of this host can communicate with other addresses on the internal network.

If the user sets the server_url to the public IP address, the host on the intranet will not be able to register to the server_url because the intranet host cannot access the server_url address (public network address) through the Internet.

## Functional Requirements

When create a new cluster, can customize the registered address so that hosts that can only communicate with the intranet can access the internal registration address.

### Usage scenarios

The default image repository has similar problems.
In a hybrid cloud scenario, the user sets the default system image repository for rancher to a local private image repository, the local private cloud deployment cluster can pull the images normally.   However, when the public cloud deploys the cluster, because the default system image repository is global, when the cluster is deployed, the image is taken from the local private image repository. Because the network fails to obtain the image, the final deployment fails.

### Functional Requirements

When create a new cluster, can customize the configuration mirror warehouse address to accommodate the needs of a hybrid cloud deployment scenario.

**Comment by loganhz** [comment]
linked to https://github.com/rancher/rancher/issues/15554

**Comment by loganhz** [comment]
Please use dns or load balancer to achieve this.
