### ISSUE TITLE
Do not show label "cattle.io/creator=norman" for hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15431]
**Rancher versions:** Build from master
**Steps to Reproduce:**

Create a  Digital Ocean cluster.
label "cattle.io/creator=norman" shows up for the nodes in the Nodes list view.

<img width="1292" alt="screen shot 2018-09-05 at 9 25 35 pm" src="https://user-images.githubusercontent.com/4266958/45135037-418d1600-b152-11e8-9125-79249ec1f9ea.png">

Can we suppress this label from being shown in the UI ?

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
