### ISSUE TITLE
How to modify the args of apiserver through the cluster created by rancher

### ISSUE THREAD

**Issue by ycyzlp** [rancher/rancher#15434]
**Rancher versions:**
rancher/rancher:v2.0.7
rancher/agent:v2.0.7

How to modify the args of apiserver through the cluster created by rancher？
For example, I want to add some in --admission-control=xxx

**Comment by superseb** [comment]
Editing Cluster Options is documented here: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file

**Comment by ycyzlp** [comment]
hi, I tested it, it could not add arg, and when I click save, the configuration disappeared.
![image](https://user-images.githubusercontent.com/3349875/45149493-43abaf00-b1fc-11e8-91c0-b5ee80aa16b4.png)

**Comment by superseb** [comment]
The docs don't state `admission-control` as a valid option for the apiserver, you need to use extras as defined here https://rancher.com/docs/rke/v0.1.x/en/config-options/services/services-extras/
