### ISSUE TITLE
Deprecate use of --management in cluster add-node

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15442]
Currently you have to pass `--management` to `rancher cluster add-node` to add the `--controlplane` label which is confusing. We also use `--controlplane` and `Control Plane` throughout docs and UI, so it should be that in the CLI as well.

**Comment by alena1108** [comment]
Can be tested with cli v2.0.7-rc2

**Comment by jiaqiluo** [comment]
Validated on cli v2.0.7-rc2

Steps:
- ran Rancher server with version: master (12/26)
- installed  and set up Rancher CLI: v2.0.7-rc2
- used the flag `controlplane` to add a control plane node to the cluster
- used the flag  `etcd` to add a etcd node to the cluster
- used the flag  `worker` to add a worker node to the cluster

Result:
The imported cluster was provisioned successfully. 
The flag works as expected.
