### ISSUE TITLE
Package updated Cloud.ca docker machine driver into Rancher as an option

### ISSUE THREAD

**Issue by pdube** [rancher/rancher#15444]
Hi,

I imported the cloud.ca docker-machine driver as a node-driver for Rancher 2.0. The machines get created correctly, docker gets installed, the images get pulled, but then the agent and server logs show that there is some address that isn't getting propagated correctly (server logs : `Failed to validate cluster: Address for host (1) is not provided`). 

I tested with Rancher v1.6 and it works as expected.

I have attached the server and agent logs below.

Has anyone seen this issue before?

Thanks!

**Rancher versions:**
rancher/rancher: v2.0.7 
rancher/agent: v2.0.7 

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.10

**Docker version: **

**Operating system and kernel:
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-104-generic

**Type/provider of hosts:**
cloud.ca

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher server

**Steps to Reproduce:**
Import custom node driver
Create k8s cluster from it
Cluster will not bootstrap correctly

**Server logs:**
```
2018/08/16 18:46:41 [INFO] [mgmt-cluster-rbac-delete] Creating namespace c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-cluster-rbac-delete] Creating Default project for cluster c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-cluster-rbac-delete] Creating System project for cluster c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Creating namespace p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Creating namespace p-kvgh4
2018/08/16 18:46:41 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Creating creator projectRoleTemplateBinding for user u-2g7dg for project p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Creating creator clusterRoleTemplateBinding for user u-2g7dg for cluster c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Creating creator projectRoleTemplateBinding for user u-2g7dg for project p-kvgh4
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Setting InitialRolesPopulated condition on project p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Creating clusterRole c-fk4w9-clusterowner
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Setting InitialRolesPopulated condition on project p-kvgh4
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Updating project p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Setting InitialRolesPopulated condition on cluster 
2018/08/16 18:46:41 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole p-kfr82-projectowner
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Creating clusterRoleBinding for membership in cluster c-fk4w9 for subject u-2g7dg
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Updating project p-kvgh4
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for membership in project p-kfr82 for subject u-2g7dg
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole p-kvgh4-projectowner
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-2g7dg with role cluster-owner in namespace 
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole c-fk4w9-clustermember
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for membership in project p-kvgh4 for subject u-2g7dg
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Updating project p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating clusterRoleBinding for membership in cluster c-fk4w9 for subject u-2g7dg
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-2g7dg with role cluster-owner in namespace 
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating clusterRoleBinding for membership in cluster c-fk4w9 for subject u-2g7dg
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Updating project p-kvgh4
2018/08/16 18:46:41 [INFO] [mgmt-project-rbac-create] Updating project p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace p-kvgh4
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-2g7dg with role project-owner in namespace 
2018/08/16 18:46:41 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-2g7dg with role cluster-owner in namespace 
2018/08/16 18:46:41 [ERROR] ProjectRoleTemplateBindingController p-kvgh4/creator-project-owner [mgmt-auth-prtb-controller] failed with : couldn't create role project-owner: roles.rbac.authorization.k8s.io "project-owner" already exists
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Updating clusterRoleBinding clusterrolebinding-9r2mt for cluster membership in cluster c-fk4w9 for subject u-2g7dg
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating role admin in namespace p-kfr82
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-2g7dg with role project-owner in namespace 
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-2g7dg with role project-owner in namespace 
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating role admin in namespace p-kvgh4
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-2g7dg with role admin in namespace 
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace p-kvgh4
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-2g7dg with role admin in namespace 
2018/08/16 18:46:41 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-2g7dg with role project-owner in namespace 
2018/08/16 18:46:41 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-fk4w9
2018/08/16 18:46:41 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-fk4w9
2018/08/16 18:46:42 [INFO] [mgmt-auth-crtb-controller] Creating clusterRoleBinding for membership in cluster c-fk4w9 for subject user-67srf
2018/08/16 18:46:42 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject user-67srf with role cluster-owner in namespace 
2018/08/16 18:46:42 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject user-67srf with role cluster-owner in namespace 
2018/08/16 18:46:42 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject user-67srf with role cluster-owner in namespace 
2018/08/16 18:46:46 [INFO] stdout: Creating CA: management-state/node/nodes/all-in-one1/certs/ca.pem
2018/08/16 18:46:47 [INFO] stdout: Creating client certificate: management-state/node/nodes/all-in-one1/certs/cert.pem
2018/08/16 18:46:47 [INFO] stdout: Running pre-create checks...
2018/08/16 18:46:47 [INFO] stdout: Creating machine...
2018/08/16 18:48:20 [INFO] stdout: Waiting for machine to be running, this may take a few minutes...
2018/08/16 18:48:20 [INFO] stdout: (all-in-one1) Getting state of the cloud.ca instance...
2018/08/16 18:48:25 [INFO] stdout: Detecting operating system of created instance...
2018/08/16 18:48:25 [INFO] stdout: Waiting for SSH to be available...
2018/08/16 18:48:37 [INFO] stdout: Detecting the provisioner...
2018/08/16 18:48:37 [INFO] stdout: Provisioning with ubuntu(systemd)...
2018/08/16 18:48:48 [INFO] stdout: Installing Docker...
2018/08/16 18:49:06 [INFO] stdout: Copying certs to the local machine directory...
2018/08/16 18:49:08 [INFO] stdout: Copying certs to the remote machine...
2018/08/16 18:49:09 [INFO] stdout: Setting Docker configuration on the remote daemon...
2018/08/16 18:49:12 [INFO] stdout: Checking connection to Docker...
2018/08/16 18:49:12 [INFO] stdout: Docker is up and running!
2018/08/16 18:49:23 [INFO] Generating and uploading node config all-in-one1
2018/08/16 18:49:23 [INFO] Provisioning cluster [c-fk4w9]
2018/08/16 18:49:23 [INFO] Creating cluster [c-fk4w9]
2018/08/16 18:49:23 [INFO] cluster [c-fk4w9] provisioning: Building Kubernetes cluster
2018/08/16 18:49:23 [ERROR] cluster [c-fk4w9] provisioning: Failed to validate cluster: Address for host (1) is not provided
2018/08/16 18:49:23 [INFO] Handling backend connection request [m-8qzqg]
2018/08/16 18:49:53 [INFO] Provisioning cluster [c-fk4w9]
2018/08/16 18:49:53 [INFO] Creating cluster [c-fk4w9]
2018/08/16 18:49:53 [ERROR] Cluster c-fk4w9 previously failed to create
2018/08/16 18:49:53 [INFO] cluster [c-fk4w9] provisioning: Building Kubernetes cluster
2018/08/16 18:49:53 [ERROR] cluster [c-fk4w9] provisioning: Failed to validate cluster: Address for host (1) is not provided
2018/08/16 18:50:53 [INFO] Provisioning cluster [c-fk4w9]
2018/08/16 18:50:53 [INFO] Creating cluster [c-fk4w9]
2018/08/16 18:50:53 [ERROR] Cluster c-fk4w9 previously failed to create
2018/08/16 18:50:53 [INFO] cluster [c-fk4w9] provisioning: Building Kubernetes cluster
2018/08/16 18:50:53 [ERROR] cluster [c-fk4w9] provisioning: Failed to validate cluster: Address for host (1) is not provided
```

**Agent logs**
```
INFO: Arguments: --server https://10.209.152.186 --token REDACTED --ca-checksum 19c679c2af0bf309219b2537ad74b506602f6b7358ed89f3f49a7e29075af1b2 -r -n m-8qzqg
INFO: Environment: CATTLE_ADDRESS=10.209.152.143 CATTLE_AGENT_CONNECT=true CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=m-8qzqg CATTLE_SERVER=https://10.209.152.186 CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 10.209.152.1 search cs19fcloud.internal
INFO: https://10.209.152.186/ping is accessible
INFO: Value from https://10.209.152.186/v3/settings/cacerts is an x509 certificate
time="2018-08-16T18:49:23Z" level=info msg="Rancher agent version v2.0.7 is starting"
time="2018-08-16T18:49:23Z" level=info msg="Listening on /tmp/log.sock"
time="2018-08-16T18:49:23Z" level=info msg="Option customConfig=map[roles:[] label:map[] address:10.209.152.143 internalAddress:]"
time="2018-08-16T18:49:23Z" level=info msg="Option etcd=false"
time="2018-08-16T18:49:23Z" level=info msg="Option controlPlane=false"
time="2018-08-16T18:49:23Z" level=info msg="Option worker=false"
time="2018-08-16T18:49:23Z" level=info msg="Option requestedHostname=m-8qzqg"
time="2018-08-16T18:49:23Z" level=info msg="Connecting to wss://10.209.152.186/v3/connect with token d2qw9pfvblh6dkn7nqggn5z4jcb2plzphxbfjhclmm6ztzdtwb69kg"
time="2018-08-16T18:49:23Z" level=info msg="Connecting to proxy" url="wss://10.209.152.186/v3/connect"
time="2018-08-16T18:49:23Z" level=info msg="Error while getting agent config: invalid response 500: Failed to validate cluster: Address for host (1) is not provided"
time="2018-08-16T18:49:28Z" level=info msg="Error while getting agent config: invalid response 500: Failed to validate cluster: Address for host (1) is not provided"
time="2018-08-16T18:49:33Z" level=info msg="Error while getting agent config: invalid response 500: Failed to validate cluster: Address for host (1) is not provided"
time="2018-08-16T18:49:38Z" level=info msg="Error while getting agent config: invalid response 500: Failed to validate cluster: Address for host (1) is not provided"
time="2018-08-16T18:49:43Z" level=info msg="Error while getting agent config: invalid response 500: Failed to validate cluster: Address for host (1) is not provided"
```

**Comment by galal-hussein** [comment]
@pdube After debugging the issue here are my findings:

- The cloud.ca docker machine driver doesn't set the base driver config field `IPAddress`.  However, it sets another variable called `PublicIP` , which Rancher doesn't use. I opened an issue with cloud ca driver repo https://github.com/cloud-ca/docker-machine-driver-cloudca/issues/10.

- There is another issue the the driver. The driver only adds 2 ports (i.e. 22, 2376) as port forwarding rules: https://github.com/cloud-ca/docker-machine-driver-cloudca/blob/master/cloudca.go#L692-L697. However, with the changes in Rancher v2.x, Kubernetes deployed by Rancher needs more ports to be opened. These ports are listed here: https://rancher.com/docs/rke/v0.1.x/en/os/#ports

**Comment by deniseschannon** [comment]
@pdube 

Could you provide the following information: 
* machine-driver URL 
* custom UI URL
* checksum

**Comment by pdube** [comment]
Hi @deniseschannon, thanks for following up. Here is the info:

* `https://github.com/cloud-ca/docker-machine-driver-cloudca/files/2446837/docker-machine-driver-cloudca_v2.0.0_linux-amd64.zip`
* `https://objects-east.cloud.ca/v1/5ef827605f884961b94881e928e7a250/ui-driver-cloudca/component.js`
* MD5 : `2a55efd6d62d5f7fd27ce877d49596f4`

Thanks!

**Comment by cjellick** [comment]
Design considerations:
- downloading at image building time vs startup time

**Comment by erikwilson** [comment]
This probably also needs a small change to the UI translation files, to add the nodeDriver displayName of cloudca as `Cloud.ca`

**Comment by erikwilson** [comment]
I encountered a few issues with testing @pdube:

- Cloud.ca logo edges are cut off:
 <img src="https://user-images.githubusercontent.com/1999874/50987698-986f7700-14c7-11e9-866a-53f0086288f1.png" width="300" />

- when changing CPU or memory in the UI for a new template the first change is not recognized

- the CPU and memory values are not populated in the CloudCa config:
```
"cloudcaConfig": {
        "additionalDiskIops": "",
        "additionalDiskOffering": "b5919e1b-df5d-47ec-9039-736238ec3656",
        "additionalDiskSizeGb": "20",
        "apiUrl": "https://api.cloud.ca/v1",
        "computeOffering": "20363b3b-7607-4f34-9ba3-0ad57bd44bc1",
        "cpuCount": "",
        "environmentName": "test_area",
        "memoryMb": "",
        "networkId": "523ef8e3-d13e-4e18-83fa-be89f19713d7",
        "rootDiskSizeInGb": "",
        "serviceCode": "compute-qc",
        "sshUser": "cca-user",
        "template": "99a900aa-7522-4bf9-8a34-dfc231209915",
        "usePrivateIp": true
    },
```
Resulting in a server error message like: `Error with pre-create check: "The CPU count and memory in MB are required because "Standard" is a custom compute offering`

- Using default template values results in a node that is never provisioned, stuck on the step `Waiting for SSH to be available...`, but I do see a running instance in Cloud.ca.

**Comment by pdube** [comment]
Hey @erikwilson,

Sorry that you hit some issues. We recently reduced our available offerings to  to a single custom sized offering, so that might have had a side effect on the driver. I will try to reproduce and report back asap

**Comment by pdube** [comment]
@erikwilson Where do you see the cut-off logo? It looks fine when I am adding a new Node Template. What should the size be?

**Comment by pdube** [comment]
`Using default template values results in a node that is never provisioned, stuck on the step Waiting for SSH to be available..., but I do see a running instance in Cloud.ca.` We don't support making nodes public right now, so unless the rancher server is in the VPC, it won't work (you could make it available after the fact though through static NAT or PFRs). We had to make it only use private IPs because of [this](https://github.com/cloud-ca/docker-machine-driver-cloudca/issues/10#issuecomment-426638459)

**Comment by pdube** [comment]
I was able to reproduce the error related to the CPU and Memory. I will fix it, build it and update the PR. Thanks for checking this out

**Comment by erikwilson** [comment]
Sounds good, thank you! I am seeing the cropped logo on the `Add Cluster` page, looks like it is set to 100x100 px, but if you can change the SVG to have a 1:1 ratio that should work well.

**Comment by pdube** [comment]
Thanks for the additional testing. 

* I will push the updated logo to the same location, so if you clear your cache it should be correct now.  It looks smaller than it was, so I assume it won't be cropped anymore.  
* For the Additional volume, it is expected to reset to 20GB when you change the disk offering. I am not able to reproduce the "clicking on Additional volume size" reset it to 10GB. I am able to use the slider to set values on all of the different offerings. I have tested on FF and Chrome
* I have tested the rest of the templates and they should work fine. For Debian, I think that the docker machine driver doesn't handle it correctly. I am thinking of just filtering it out for now.

I'll try to get it done this morning so we can wrap this up!

**Comment by erikwilson** [comment]
The logo change looks good. Maybe @westlywright or @vincent99 can comment on the issues with using `input-slider`, I am on MacOS 10.14.2 and the slider is not working in Chrome, Firefox, or Safari.

**Comment by pdube** [comment]
Thanks. I am using MacOS 10.13.6 and it's working in FF, Chrome and Safari. I have fixed the Debian template filtering and will add the URL and checksum soon™

**Comment by pdube** [comment]
* URL : `https://objects-east.cloud.ca/v1/5ef827605f884961b94881e928e7a250/ui-driver-cloudca/v2.1.2/component.js`
* Checksum : `1f25aaa44c1f7c8e7bf3517247b35d2e`

**Comment by erikwilson** [comment]
Looks like the logo has changed back to 120pt x 90pt, filtering looks good, will see if I can find a resolution for the slider issue early next week.

**Comment by erikwilson** [comment]
@pdube It looks like we are seeing different behavior due to using different versions of the UI, if you update the `ui-index` setting of Rancher server to `https://releases.rancher.com/ui/latest2/index.html` it should be possible to duplicate what I am seeing. Using a previous version 2.1.x of the UI the logo does not appear cropped and the `input-slider` works. Updated the UI to `latest2` (2.2.1) and the slider is not retaining the value and logo is cropped. There is at least one other `input-slider` in the UI that works, so not sure if a UI bug a machine driver bug yet.

**Comment by erikwilson** [comment]
Not sure if the setting is broken on a previous version or dev only, but it seems to work on master.

**Comment by pdube** [comment]
@erikwilson I had pushed the wrong svg. It is resolved now. It might be cached locally, but it is the correctly scaled image now. I am unsure of what to do for the slider. It sounds like a regression in the latest UI version? I am running rancher from the v2.1.0 image. I can try upgrading to v2.1.5, but it still sounds like something is wrong with the slider component. Thoughts?

**Comment by westlywright** [comment]
@erikwilson @pdube i've merged a PR that should fix the issue with `input-slider` but it is only in master right now so you'll have to use latest.

**Comment by cjellick** [comment]
@sangeethah we want the majority of the QA for these third-party drivers to be performed by the third-party. As this was our first one in awhile, I had @erikwilson go a bit further to ensure the framework and driver generally worked.
But I think your team should do very little validation beyond asserting that the driver is available and can be turned on.
cc @deniseschannon

**Comment by cjellick** [comment]
@dramich pretty simple validation. Confirm this driver is an option, it is off by default, can be turned on and off, and the the UI for it loads

**Comment by cjellick** [comment]
@dramich to validate

**Comment by dramich** [comment]
Validated in version v2.2.0-alpha6

Steps:
Setup HA cluster according to docs except replace version tag with v2.2.0-alpha6
In UI activate `Custom Driver` cloud.ca
Clusters > Add Cluster and validate cloud.ca is now an option 
cloud.ca options show when selected
Disable cloud.ca and verify it no longer shows in the UI

**Comment by pdube** [comment]
Thanks to everyone that worked on this 🎉
