### ISSUE TITLE
Not able to view CPU/Memory utilization for Hosts and "Execute Shell" for containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1544]
Server version - V0.27.0-rc4 

Rancher server has 3 hosts and many containers deployed in them.
Server has been up for a day now .
I am not able to view CPU/Memory utilization for Hosts and "Execute Shell" for containers.
I see the screen stuck in "connecting.." state forever.

**Comment by cjellick** [comment]
I review @sangeethah's setup and the agents were in a very weird state where their UUIDs were out of sync with what was stored in here rancher database.

The proxy was functioning normally and re-registering (re-running `docker run...rancher/agent`) fixed the issue. I suspect that recycling the environment (ie deleteting and rerunning rancher/server without migrating the data) was at fault.

@will-chan can we deprioritize this bug for now and remove it from any upcoming milestones?

**Comment by cjellick** [comment]
@sangeethah Can we close this?

**Comment by sangeethah** [comment]
Closing this issue.
