### ISSUE TITLE
Shiboleth - "Page Expired" / "Session has expired log in again" presented to user sometimes after entering valid credentials.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15451]
**Rancher versions: v1.6.22-rc3
**Steps to Reproduce:**

Have Shiboleth (Ping Federator) enabled in the setup.
Sometimes When I log in to the set up with valid credentials, I am not able to get to Rancher UI.

Sometimes I am presented  with this error:
<img width="1468" alt="screen shot 2018-09-07 at 9 52 34 am" src="https://user-images.githubusercontent.com/4266958/45238255-1c092500-b296-11e8-8129-4380daaab9f7.png">

There are other times where I am presented with this error:

<img width="1446" alt="screen shot 2018-09-05 at 9 48 43 am" src="https://user-images.githubusercontent.com/4266958/45238270-2d523180-b296-11e8-8d34-62b566babb0b.png">

In both these cases , When I quit browser completely and  then relaunch and attempt to login  , log in succeeds as expected and user is taken to rancher UI.

**Comment by aemneina** [comment]
I have logs for this @mrajashree PM me directly if you want to take a look.

**Comment by mrajashree** [comment]
The customer logs have stack trace showing some methods being called, by the line number where the method definition starts. In the latest code those methods shouldn't be called, also the line number where these methods are defined from have changed. That's why I think this was repro'd using older version at least based on logs. Requested the new logs

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher/issues/15869 UI ticket

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
