### ISSUE TITLE
Rancher breaks if the same node name appears in multiple clusters

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#15456]
If multiple clusters have hosts with the same node name, only one will successfully provision. The rest will just get stuck in an unprovisioned state.

The end result is if you have two clusters with nodes with the same hostname and you are using RKE, one of the clusters will not provision

**Comment by cjellick** [comment]
@cloudnautique and i did not coordinate and he opened https://github.com/rancher/rancher/issues/15459. I closed it as a dupcliate of this one, but here's his description:

Rancher/rancher:v2.0.x

Rancher server uses node name as a primary identifier when creating a dialer. Having a host with the same name in separate clusters can cause the dialer to be created for the wrong host. This causes provisioning of that cluster/node to halt.

To reproduce:

create a cluster with a node name 'prod-000'
create a second cluster with node name 'prod-000'
result:
node will have three containers. 2 agents and 1 share-mnt container and appear hung.

expected result:
node is provisioned to be a member of that cluster.

**Comment by cjellick** [comment]
@StrongMonkey to validate

**Comment by StrongMonkey** [comment]
Be able to verify that we are able to create two clusters with hosts that share the same hostname.
Steps:
1. Create a fresh install on rancher/rancher:master.
2. Prepare two linux hosts, set both hostname to `ubuntu`.
3. Create two custom cluster. Register each cluster with a host that has all roles.
4. Both cluster were provisioned successfully.
![screenshot_2018-09-13_15-22-07](https://user-images.githubusercontent.com/9203378/45519152-c38bc900-b768-11e8-9880-b11096831740.png)
![screenshot_2018-09-13_15-22-31](https://user-images.githubusercontent.com/9203378/45519153-c38bc900-b768-11e8-87a9-b1615316f731.png)
![screenshot_2018-09-13_15-22-48](https://user-images.githubusercontent.com/9203378/45519154-c38bc900-b768-11e8-8e15-4c6873f463ee.png)

While running v2.0.8 with the same step, it will show the following error:
![screenshot_2018-09-13_15-34-25](https://user-images.githubusercontent.com/9203378/45519559-74df2e80-b76a-11e8-9457-ae20857bd6b7.png)
