### ISSUE TITLE
Hosts with the same name can prevent cluster provisioning

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#15459]
Rancher/rancher:v2.0.x 

Rancher server uses node name as a primary identifier when creating a dialer. Having a host with the same name in separate clusters can cause the dialer to be created for the wrong host. This causes provisioning of that cluster/node to halt.

To reproduce:
1. create a cluster with a node name 'prod-000'
1. create a second cluster with node name 'prod-000'

result:
node will have three containers. 2 agents and 1 share-mnt container and appear hung.

expected result:
node is provisioned to be a member of that cluster.

**Comment by cjellick** [comment]
dupe of https://github.com/rancher/rancher/issues/15456
poor coordination on our part
