### ISSUE TITLE
[rancher-dns] 

### ISSUE THREAD

**Issue by lester65** [rancher/rancher#15458]
Rancher | v1.6.18
-- | --
Cattle | v0.183.52
User Interface | v1.6.43
Rancher CLI | v0.6.10
Rancher Compose | v0.12.5

**Infrastructure Stack versions:**

network-services: rancher/dns v0.17.3

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7 
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Application Errors unable to resolve host issue
**Results:**
Could not resolve host

**Comment by superseb** [comment]
Can you please supply the requested info from the issue template? The more information is given, the better we can look into it.

Besides that, can you share what you are running and what you run into exactly? Rancher DNS is a sidekick to metadata, can you share logging of both containers?
