### ISSUE TITLE
Remove stop from service container menu and replace with restart

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1545]
v0.27.0-rc4
Steps:
1.  Create and stop a service
2.  In the service container menu, select stop

Results:
Container stops then restarts.

Expected:
Since this is actually expected behavior, we should remove the stop and just have restart in the menu.

**Comment by vincent99** [comment]
The UI shows the actions the resource says it has, so this would be an API change

**Comment by alena1108** [comment]
As we allow services containers to be in stopped state (when restartPolicy=No) is defined, looks like this bug can be closed. As when restartPolicy=No is specified, stop woudln't result in container restart. What do you think, @vincent99?

**Comment by vincent99** [comment]
What happens if a service container with restartPolicy=yes/always and you call stop; do we start it again?
    - If we do not start it, then I agree this can be closed.
    - If we do start it again even though I just stopped it, then I still think the stop action should be removed from the API response for containers of a service with restartPolicy=yes.

**Comment by alena1108** [comment]
@vincent99 we do start it again if restartPolicy=always.

 I'm not sure there is a way to remove specific action from the object based on object's attribute. Object either has an action, or it doesn't.

**Comment by vincent99** [comment]
I think James had to do that somewhere... @hibooboo2 or @ibuildthecloud do you know how to disable actions on a resource based on custom logic/attributes of the resource?
