### ISSUE TITLE
UI: expose more meaningful information in Persistent Volumes overview

### ISSUE THREAD

**Issue by tkuther** [rancher/rancher#15450]
**Rancher versions:**
rancher/rancher: v2.0.8

Especially when dealing with dynamic PVs, it's really hard to tell which volume is what exactly:

![screenshot_20180907_130531](https://user-images.githubusercontent.com/63717/45215783-cab16380-b29e-11e8-8793-5f2f250f3c29.png)

Even the details page doesn't give more clues, other than the volume's size

![screenshot_20180907_130808](https://user-images.githubusercontent.com/63717/45215942-46131500-b29f-11e8-99b1-6c33665c7e7e.png)

The API has some more information

![screenshot_20180907_131400](https://user-images.githubusercontent.com/63717/45216171-ed904780-b29f-11e8-9723-d7874988abe0.png)

The UI should be improved to reveal the claimRef name and namespace information which is present in the API. That would make the volume identifiable without heading into the API view.

**Comment by loganhz** [comment]
Add PVC in PV list page.
Add PVC, Reclaim Policy, Created, Annotations info in PV detail page.

![image](https://user-images.githubusercontent.com/21168270/45275016-e742db00-b4ec-11e8-89e5-4ee2fa6aaa81.png)
![image](https://user-images.githubusercontent.com/21168270/45275028-f6c22400-b4ec-11e8-90db-6dbd75a94039.png)

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
