### ISSUE TITLE
Deleting the only node from a DO cluster results in the node being stuck in "Removing" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15457]
**Rancher versions: Build from master
**Steps to Reproduce:**

Create a DO cluster with 1 node having all roles.
Once the cluster gets to "Active" state , delete the node.

Node gets stuck in ""Removing" state forever."

Error seen in logs:
2018/09/07 22:33:49 [ERROR] NodeController c-bbv8m/m-sq668 [node-controller] failed with : waiting for node to be removed from cluster

**Comment by StrongMonkey** [comment]
@sangeethah This might be caused by the validation that you can't delete the last ETCD node.

**Comment by cjellick** [comment]
Since this involves going down to zero etcd nodes, which seems like a rare corner case, moving out of release
