### ISSUE TITLE
Develop a tool to provide docker-compose constructs unsupported for conversion to K8s YAML

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#15454]
This is a new requirement to help migration from Rancher 1.6 to Rancher 2.0. 
The idea is to develop a tool that would 
 a) Accept the Rancher 1.6 Docker Compose config files and 
 b) Output a list of constructs present in the config file that cannot be supported onto Rancher 2.0 without special handling or that cannot be converted to Kubernetes YAML using tools like Kompose.

This should help users to run a quick check to see if their application running on Rancher 1.6 can be migrated to 2.0 and what is lacking to do the migration.

@will-chan please review and update the requirements 
cc @alena1108

**Comment by vincent99** [comment]
What about other things like `rancher-metadata` and `service.stack.rancher.internal` assumptions that are in the image instead of the compose file?

**Comment by alena1108** [comment]
@vincent99 those are going to be documented and emphasize separately. We can also add it as a side note to the tool, something like `If your application uses rancher metadata, or relies on fqdn resolution format, it can be impacted. Please refer to <doc link> for more info`

**Comment by rawmind0** [comment]
Testing [migration-tools](https://github.com/rancher/migration-tools) and linking with migration tools docs PR, https://github.com/rancher/docs/pull/893

**Comment by alena1108** [comment]
Cleared the milestone. The tool development is not aligned with rancher releases.
