### ISSUE TITLE
Sometimes namespace gets stuck in "Activating" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15467]
**Rancher versions:** Build from master
**Steps to Reproduce:**
Had an imported RKE cluster.
Created a new project.
Created a workload in a new namespace in this project.
namespace gets stuck in "Activating" state forever.

<img width="1345" alt="screen shot 2018-09-07 at 5 08 20 pm" src="https://user-images.githubusercontent.com/4266958/45247994-ee85a100-b2c0-11e8-84d9-467f322edb74.png">

Following error seen in logs:

```
2018/09/08 00:02:36 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-zdwnv to namespace=mytest123
2018/09/08 00:02:36 [ERROR] namespaceHandler: Sync: error adding project id label to namespace err=Operation cannot be fulfilled on namespaces "mytest123": the object has been modified; please apply your changes to the latest version and try again
2018/09/08 00:02:37 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-zdwnv to namespace=mytest123
2018/09/08 00:02:37 [ERROR] error updating ns mytest123 status: Operation cannot be fulfilled on namespaces "mytest123": the object has been modified; please apply your changes to the latest version and try again
2018/09/08 00:03:03 [INFO] Creating [mytest123/mytest123w] service of type [ClusterIP] with ports [[{default TCP 42 {0 42 } 0}]] for workload deployment:mytest123:mytest123w
E0908 00:03:30.248975       6 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: json: cannot unmarshal string into Go struct field Node.status of type v3.NodeStatus
```

**Comment by sangeethah** [comment]
Tested with v2.1.0-rc1
Not able to reproduce the issue where namespace gets stuck in "Activating" state forever.

**Comment by sangeethah** [comment]
Tested with v2.1.0-rc1

Able to reproduce the issue where namespace gets stuck in "Activating" state forever when running automated runs relating to custom cluster provisioning.
```
{
"actions": {
"move": "…/v3/cluster/c-kvczg/namespaces/test-75261?action=move"
},
"annotations": {
"cattle.io/status": "{\"Conditions\":[{\"Type\":\"InitialRolesPopulated\",\"Status\":\"Unknown\",\"Message\":\"Populating initial roles\",\"LastUpdateTime\":\"\"},{\"Type\":\"ResourceQuotaInit\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2018-09-18T05:07:08Z\"}]}",
"lifecycle.cattle.io/create.namespace-auth": "true"
},
"baseType": "namespace",
"created": "2018-09-18T05:07:07Z",
"createdTS": 1537247227000,
"creatorId": "user-2v8lz",
"description": "test",
"id": "test-75261",
"labels": {
"cattle.io/creator": "norman",
"field.cattle.io/projectId": "p-lmgz5"
},
"links": {
"remove": "…/v3/cluster/c-kvczg/namespaces/test-75261",
"self": "…/v3/cluster/c-kvczg/namespaces/test-75261",
"update": "…/v3/cluster/c-kvczg/namespaces/test-75261",
"yaml": "…/v3/cluster/c-kvczg/namespaces/test-75261/yaml"
},
"name": "test-75261",
"projectId": "c-kvczg:p-lmgz5",
"state": "activating",
"transitioning": "yes",
"transitioningMessage": "Populating initial roles",
"type": "namespace",
"uuid": "b0f90a72-bb00-11e8-9760-029026ef3182"
}
```

**Comment by sangeethah** [comment]
Tested with latest build from master
Did not see the issue of namespace getting stuck in "Activating" state forever.

**Comment by phal0r** [comment]
@sangeethah 
I am facing this issue with Rancher 2.1.0. I have deployed 3 custom hosts and spin a cluster up. I could install some workloads in system project, but then creating namespaces are stuck in activating state doesn't matter in which project they are created. API view looks like this for one of the stuck namespaces:

```
{
"actions": {
"move": "…/v3/cluster/c-5rfj5/namespaces/nextcloud?action=move"
},
"annotations": {
"cattle.io/status": "{\"conditions\": [{\"type\": \"InitialRolesPopulated\", \"status\": \"Unknown\", \"message\": \"Populating initial roles\"},{\"type\": \"ResourceQuotaValidated\", \"status\": \"Unknown\", \"message\": \"Validating resource quota\"}]}"
},
"baseType": "namespace",
"created": "2018-10-08T12:35:41Z",
"createdTS": 1539002141000,
"creatorId": "user-gq6tr",
"id": "nextcloud",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"remove": "…/v3/cluster/c-5rfj5/namespaces/nextcloud",
"self": "…/v3/cluster/c-5rfj5/namespaces/nextcloud",
"update": "…/v3/cluster/c-5rfj5/namespaces/nextcloud",
"yaml": "…/v3/cluster/c-5rfj5/namespaces/nextcloud/yaml"
},
"name": "nextcloud",
"projectId": "c-5rfj5:p-5hnhn",
"resourceQuota": { },
"state": "activating",
"transitioning": "yes",
"transitioningMessage": "Populating initial roles",
"type": "namespace",
"uuid": "ab20a490-caf6-11e8-ad59-4ed6ddea6d45"
}
```

**Comment by RVN-BR** [comment]
I have the same on an imported custom (kubespray) cluster (on premises)

"actions": {
"move": "…/v3/cluster/local/namespaces/xxxxxxx-supporting-prd?action=move"
},
"annotations": {
"cattle.io/status": "{\"conditions\": [{\"type\": \"InitialRolesPopulated\", \"status\": \"Unknown\", \"message\": \"Populating initial roles\"}]}"
},
"baseType": "namespace",
"created": "2018-10-09T22:52:17Z",
"createdTS": 1539125537000,
"creatorId": "u-2226z",
"id": "xxxxxxx-supporting-prd",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"remove": "…/v3/cluster/local/namespaces/xxxxxxx-supporting-prd",
"self": "…/v3/cluster/local/namespaces/xxxxxxx-supporting-prd",
"update": "…/v3/cluster/local/namespaces/xxxxxxx-supporting-prd",
"yaml": "…/v3/cluster/local/namespaces/xxxxxxx-supporting-prd/yaml"
},
"name": "xxxxxxx-supporting-prd",
"projectId": "local:p-w6xsb",
"state": "activating",
"transitioning": "yes",
"transitioningMessage": "Populating initial roles",
"type": "namespace",
"uuid": "f890c9f5-cc15-11e8-934f-000c2908ce1e"
}

**Comment by cryptoentity** [comment]
`{
"actions": {
"move": "…/v3/cluster/local/namespaces/identity?action=move"
},
"annotations": {
"cattle.io/status": "{\"conditions\": [{\"type\": \"InitialRolesPopulated\", \"status\": \"Unknown\", \"message\": \"Populating initial roles\"}]}"
},
"baseType": "namespace",
"created": "2018-10-11T12:20:02Z",
"createdTS": 1539260402000,
"creatorId": "user-c5xx5",
"id": "identity",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"remove": "…/v3/cluster/local/namespaces/identity",
"self": "…/v3/cluster/local/namespaces/identity",
"update": "…/v3/cluster/local/namespaces/identity",
"yaml": "…/v3/cluster/local/namespaces/identity/yaml"
},
"name": "identity",
"projectId": "local:p-2cjg8",
"state": "activating",
"transitioning": "yes",
"transitioningMessage": "Populating initial roles",
"type": "namespace",
"uuid": "facd0205-cd4f-11e8-8dba-005056987f2c"
}`


We are now experiencing this behaviour after upgrading to 2.1.0 from 2.0.8.
RKE provisioned imported cluster.

**Comment by marcinbojko** [comment]
The same after moving to 2.1.0. Can create namespace with kubectl but trying to move it to any project got 502 gateway error.

**Comment by nnexai** [comment]
same problem for my imported cluster with 3 nodes:

{
"actions": {
"move": "…/v3/cluster/local/namespaces/test?action=move"
},
"annotations": {
"cattle.io/status": "{\"conditions\": [{\"type\": \"InitialRolesPopulated\", \"status\": \"Unknown\", \"message\": \"Populating initial roles\"},{\"type\": \"ResourceQuotaValidated\", \"status\": \"Unknown\", \"message\": \"Validating resource quota\"}]}"
},
"baseType": "namespace",
"created": "2018-11-06T18:32:41Z",
"createdTS": 1541529161000,
"creatorId": "user-8dzj2",
"id": "test",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"remove": "…/v3/cluster/local/namespaces/test",
"self": "…/v3/cluster/local/namespaces/test",
"update": "…/v3/cluster/local/namespaces/test",
"yaml": "…/v3/cluster/local/namespaces/test/yaml"
},
"name": "test",
"projectId": "local:p-7q9s2",
"resourceQuota": { },
"state": "activating",
"transitioning": "yes",
"transitioningMessage": "Populating initial roles",
"type": "namespace",
"uuid": "58493007-e1f2-11e8-ac98-c6e96cacb90b"
}

**Comment by superseb** [comment]
It's documented on docs.rancher.com and in the file you are editing that RKE install is only supported up to v2.0.8, you need the workaround mentioned in https://github.com/rancher/rancher/issues/16251 to make it work.

```
        # Rancher install via RKE addons is only supported up to v2.0.8
        - image: rancher/rancher:v2.1.1
```

This is a closed issue, if you have a reproducible situation using the official docs, please open a new issue.
