### ISSUE TITLE
AD FS field settings are wrapped while there is space

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15462]
Version: master 7/9

<img width="1276" alt="screen shot 2018-09-08 at 00 56 26" src="https://user-images.githubusercontent.com/2620179/45246548-409ae680-b302-11e8-9e73-ea9d79e25b5a.png">

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/11/19)
Confirmed fix. Text no longer inappropriately wraps when there is a space in any string.
I tried strings with and without spaces, changing window size, etc and the text no longer wraps oddly as seen in original issue description screenshot.
![image](https://user-images.githubusercontent.com/45179589/51046955-a7682f00-1584-11e9-98aa-a43db577f36e.png)
When the window gets too small it will appropriately wrap per character
![image](https://user-images.githubusercontent.com/45179589/51046996-bb139580-1584-11e9-8785-c351e863fd45.png)
AD FS was lighted tested as well to ensure nothing broke.
