### ISSUE TITLE
Repeated errors relating to failed upgrade system service cattle-logging:fluentd in logs when cluster gets deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15465]
Rancher Server - Build from master
Steps to reproduce the problem:
Create a DO cluster.
Add namespace and few workloads.
Delete cluster.

Repeated errors relating to failed upgrade system service cattle-logging:fluentd in logs:

```
2018/09/07 23:14:13 [ERROR] ProjectController c-k2cp5/p-f6hpd [system-image-upgrade-controller] failed with : upgrade system service p-cvzq9-pipeline:docker-registry failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/p-cvzq9-pipeline/deployments/docker-registry?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:13 [ERROR] ProjectController c-k2cp5/p-f6hpd [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:21 [ERROR] ProjectController c-k2cp5/p-48vc9 [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:21 [ERROR] ProjectController c-k2cp5/p-48vc9 [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:log-aggregator failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/log-aggregator?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:21 [ERROR] ProjectController c-k2cp5/p-4kk7s [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:log-aggregator failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/log-aggregator?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:21 [ERROR] ProjectController c-k2cp5/p-4kk7s [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:21 [ERROR] ProjectController c-k2cp5/p-f6hpd [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:21 [ERROR] ProjectController c-k2cp5/p-f6hpd [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:37 [ERROR] ProjectController c-k2cp5/p-48vc9 [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:37 [ERROR] ProjectController c-k2cp5/p-48vc9 [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:37 [ERROR] ProjectController c-k2cp5/p-4kk7s [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:37 [ERROR] ProjectController c-k2cp5/p-4kk7s [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:37 [ERROR] ProjectController c-k2cp5/p-f6hpd [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
2018/09/07 23:14:37 [ERROR] ProjectController c-k2cp5/p-f6hpd [system-image-upgrade-controller] failed with : upgrade system service cattle-logging:fluentd failed, Put https://159.89.178.163:6443/apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd?timeout=30s: cluster.management.cattle.io "c-k2cp5" not found
```

**Comment by cjellick** [comment]
Related to https://github.com/rancher/rancher/issues/15366

**Comment by alena1108** [comment]
@aiwantaozi  when reproduce the issue, could you try running rancher in docker container if you are unable to reproduce it using local build.

**Comment by aiwantaozi** [comment]
Add a cluster, and deploy catalog wordpress and letencript, delete the cluster when the catalog is not completely running, get bunch of 503 and not found error.

2018/09/13 09:40:45 [ERROR] failed on subscribe replicationController: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe namespacedCertificate: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe namespacedServiceAccountToken: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe replicationController: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe daemonSet: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe statefulSet: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe job: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe cronJob: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe deployment: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:45 [ERROR] failed on subscribe replicaSet: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:47 [ERROR] failed on subscribe replicationController: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:47 [ERROR] failed on subscribe namespacedCertificate: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:47 [ERROR] failed on subscribe namespacedServiceAccountToken: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:47 [ERROR] failed on subscribe persistentVolumeClaim: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:47 [ERROR] failed on subscribe namespacedDockerCredential: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:47 [ERROR] failed on subscribe namespacedBasicAuth: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found
2018/09/13 09:40:47 [ERROR] failed on subscribe ingress: ClusterUnavailable 503: cluster.management.cattle.io "c-75s27" not found

**Comment by sangeethah** [comment]
Tested with latest build from master.

Errors mentioned in this issue not seen in rancher server logs when cluster gets deleted.

There are other errors relating to system-image-upgrade-controller seen in logs -https://github.com/rancher/rancher/issues/15641

Closing this issue.
