### ISSUE TITLE
Launch kubectl always "Connecting..." state

### ISSUE THREAD

**Issue by yinfxs** [rancher/rancher#15469]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.8
rancher/agent or rancher/rancher-agent:v2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Aliyun ECS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**
![image](https://user-images.githubusercontent.com/6890643/45249070-61882980-b34c-11e8-99e8-06bf62c61ad5.png)

But I can run kubectl successfully on my local computer with KubeConfig

**Comment by superseb** [comment]
The embedde kubectl goes to a pod running `rancher/rancher-agent` that is scheduled to nodes. Can you check the status of those pods and logging?

```
kubectl get pods -n cattle-system
kubectl logs -n cattle-system -l app=cattle-agent
```

**Comment by yinfxs** [comment]
Thanks, but I have reinstalled rancher.
