### ISSUE TITLE
Better identifiable logo for AD FS

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15464]
Version: master 9/8

Logo should be better identifiable, like the AD/Azure AD with bigger letters.

<img width="1245" alt="screen shot 2018-09-08 at 01 17 31" src="https://user-images.githubusercontent.com/2620179/45247026-067f1400-b305-11e8-8fbb-873cbef73183.png">

**Comment by tfiduccia** [comment]
Version - 2.2 master 10/31
Verified fixed
