### ISSUE TITLE
Rancher API Host setting for AD FS can be prefilled

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15463]
Version: 9/8

When configuring AD FS, you have to enter Rancher API Host which is just the configured `server-url` so we can pre-fill that. (except when people are using a different URL than the configured `server-url`, which is also weird)

**Comment by loganhz** [comment]
@vincent99 Does it make sense to pre-fill Rancher API Host with `server-url`?

**Comment by vincent99** [comment]
Yes that seems fine

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/10/18)
Confirmed that we now auto-fill the "Rancher API Host" field under AD FS with the server-url. Also tried changing this under settings and it filled in with our custom server-url.
![image](https://user-images.githubusercontent.com/45179589/49768717-85843f80-fc9a-11e8-9d5d-a3d9281bb50a.png)
