### ISSUE TITLE
Custom provisioning of 3 nodes failed with etcd errors

### ISSUE THREAD

**Issue by phal0r** [rancher/rancher#15478]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent: 2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.11.2

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
16.04.5 LTS (Xenial Xerus)  / 
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
self-created DO nodes with UFW deactivated

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
- Start Rancher Serverv as described in  manual setup (https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/)
- set the server url to the internal ip
- provision 3 nodes (os as described above)
- create the manual deployment command in the cluster options ui of rancher with set external and internal ip

**Results:**
All nodes start and are marked active in the rancher ui, but etcd is failing to create cluster. All etc nodes fail with errors like this:
```
 rafthttp: request cluster ID mismatch (got A want B)
rafthttp: request sent was ignored (cluster ID mismatch: peer[X]=A, local=B)
```

**Comment by superseb** [comment]
Are the droplets created with private network? Is internal address set to private network and public address to public network?

Were the nodes added once after creating or were they re-used in multiple attempts, if so, were the nodes cleaned in between adding them to clusters?

**Comment by phal0r** [comment]
> Are the droplets created with private network?
Yes

>  Is internal address set to private network and public address to public network?
Yes and I can confirm from monitoring that traffic is being sent over the private network.

> Were the nodes added once after creating or were they re-used in multiple attempts, if so, were the nodes cleaned in between adding them to clusters?
We tried both, with the same errors. When reusing droplets, we deleted all containers and additionally `rm -rf`-ed `etc/kubernetes` on the droplet

The system is still running in the faulty state, if you need any runtime information, I can provide them.

And a side note: I am not to keen to provision the cluster myself, since we are running in digitalocean. But #14037 blocks us from using the digitalocean provisioner for rancher.

**Comment by phal0r** [comment]
@superseb ping. Do you need additional information?

**Comment by superseb** [comment]
Nodes need to be cleaned according to https://rancher.com/docs/rancher/v2.x/en/faq/cleaning-cluster-nodes/, can you verify it reproduces with cleaned nodes?

**Comment by phal0r** [comment]
Hi @superseb ,

in fact, I never found your tutorial to clean a node. I retried with completely new nodes and Rancher 2.1 and everything is working now. I will close this as fixed. Thanks!
