### ISSUE TITLE
Rancher 2.X Ability to specify url and Admin password on initial startup to enable automation

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15477]
I have been working on writing automation to deploy our Rancher servers using RKE HA and I have it working. The only issue is I still have to manually go into rancher to set the url and generate the admin password. I also have to manually generate a token for the user before I can run any other of my automation which uses the API to set up authentication, custom roles, etc.

If these things can be automated from rancher startup somehow that would be great.
1. Specify initial URL as part of rancher server command which is only set once and then ignored.
2. Specify admin password as an env variable (secret) which is only set once and then ignored.
3. Ability to generate/retrieve admin users token and secret to be used for automation after initial server startup to consume the API.

**Comment by superseb** [comment]
The `server-url` setting can be automated using `-e CATTLE_SERVER_URL` or using the API.

Initial password request is in https://github.com/rancher/rancher/issues/13271. Password can already be automated using the same API calls done when logging in the first time. See https://gist.github.com/superseb/c363247c879e96c982495daea1125276

Last request is also possible as shown in last gist.
