### ISSUE TITLE
Jenkins blocks Pipeline execution

### ISSUE THREAD

**Issue by kapolos** [rancher/rancher#15473]
**Rancher versions:**
rancher/rancher: `2.0.8`
rancher/rancher-agent: `2.0.8`

**Docker version: (`docker version`,`docker info` preferred)** 

`17.03.2-ce, build f5ec1e2`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

`4.4.0-130-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

K8s

**Steps to Reproduce:**

Created a pipeline, all branches, fully authorized Github app (hooks + all repos), private repository.
I tested both with "run once" and by pushing a branch, same result.

**Results:**

![image](https://user-images.githubusercontent.com/10794126/45258730-b4ea8e00-b3c5-11e8-9480-77e9918494c9.png)

```
create job error - status 403, result: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 403 No valid crumb was included in the request</title> </head> <body><h2>HTTP ERROR 403</h2> <p>Problem accessing /createItem. Reason: <pre> No valid crumb was included in the request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/> </body> </html>
```

Seems like Jenkins anti-XSS protection is kicking in? Possible related issue entry: https://issues.jenkins-ci.org/browse/JENKINS-42200

**Comment by alena1108** [comment]
@gitlawr could you check if the issue is still relevant in the refactor scope

**Comment by gitlawr** [comment]
@kapolos Thanks for the report! I'm trying to reproduce it and would like to know:
1. what kind of cluster are you using
2. How long has it been since you setup pipeline in the cluster
3. Is there any relavent logs from the Jenkins pod in cattle-pipeline namespace.

**Comment by kapolos** [comment]
Hi @gitlawr , thank you very much for taking a look!

1. I am not sure exactly what information is helpful, so I'm pasting the cluster's yaml file. If that's not covering it, please let me know and I'll be more than happy to check anything else! The k8s is a single server on bare-metal (no cloud provider).

```
addon_job_timeout: 30
authentication: 
  strategy: "x509"
bastion_host: 
  ssh_agent_auth: false
ignore_docker_version: true
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "nginx"
kubernetes_version: "v1.11.1-rancher1-1"
monitoring: 
  provider: "metrics-server"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
network: 
  plugin: "calico"
# 
#      services:
#        kube_api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube_controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api: 
    pod_security_policy: false
  kubelet: 
    fail_swap_on: false
ssh_agent_auth: false
```

2. I enabled the pipelines feature like 10 days before the report to see how the interface looks and did nothing with it initially. Then I tried to create my first pipeline the same days as the report.

3. This is the full output: https://pastebin.com/raw/ipXxX5Wk but I see two `SEVERE` and some `WARNINGS`:

```
Aug 30, 2018 3:33:18 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline: Multibranch v2.20 (workflow-multibranch)
java.io.IOException: Pipeline: Multibranch v2.20 failed to load.
- Pipeline: Job v2.17 is older than required. To fix, install v2.21 or later.
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
at hudson.PluginManager$2$1$1.run(PluginManager.java:514)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Aug 30, 2018 3:33:18 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline: Declarative v1.3.1 (pipeline-model-definition)
java.io.IOException: Pipeline: Declarative v1.3.1 failed to load.
- Pipeline: Multibranch v2.20 failed to load. Fix this plugin first.
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
at hudson.PluginManager$2$1$1.run(PluginManager.java:514)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Aug 30, 2018 3:33:18 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline v2.5 (workflow-aggregator)
java.io.IOException: Pipeline v2.5 failed to load.
- Pipeline: Multibranch v2.20 failed to load. Fix this plugin first.
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
at hudson.PluginManager$2$1$1.run(PluginManager.java:514)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

```
Sep 08, 2018 9:01:08 PM hudson.security.csrf.CrumbFilter doFilter
WARNING: Found invalid crumb e811d2c55b7752ea7c7e1b930a2c530d. Will check remaining parameters for a valid one...
Sep 08, 2018 9:01:08 PM hudson.security.csrf.CrumbFilter doFilter
WARNING: No valid crumb was included in request for /credentials/store/system/domain/_/createCredentials by admin. Returning 403.
Sep 08, 2018 9:04:37 PM hudson.security.csrf.CrumbFilter doFilter
WARNING: Found invalid crumb 54cf6627ddea8c925b9cdc8bb9124485. Will check remaining parameters for a valid one...
Sep 08, 2018 9:04:37 PM hudson.security.csrf.CrumbFilter doFilter
WARNING: No valid crumb was included in request for /createItem by admin. Returning 403.
```

**Comment by gitlawr** [comment]
@kapolos Thanks, the warning indicated that an invalid curmb is used in API calls. I got no luck reproducing it though. Could you try the following and see if it makes any difference?
1. delete the jenkins pod in `cattle-pipeline` namespace
2. wait until the new pod is ready.
3. run the pipeline again

**Comment by kapolos** [comment]
Hi @gitlawr !

Thank you! I removed the jenkins pod (via the interface/workloads) but a new one has not come up again (`cattle-pipeline` doesn't show up as a namespace any more in the workloads, it's been more than an hour). Clicking on the "Pipelines" still gets to me to the interface (I suppose it assume jenkins pod still exists) so I'm not sure how to make it come back.

Is there a way for me to trigger it manually? Or is there a place where there are logs to see why it doesn't spawn a new one?

**Comment by kapolos** [comment]
@gitlawr Thank you very much!

This is the result for running the pipeline manually:

![image](https://user-images.githubusercontent.com/10794126/45487450-08aefb80-b767-11e8-8804-b53efb2bea69.png)

The logs from Jenkins pod: https://pastebin.com/raw/USPZiHB2

The are some `SEVERE` level ones:

```
SEVERE: Failed Loading plugin Pipeline: Multibranch v2.20 (workflow-multibranch)
java.io.IOException: Pipeline: Multibranch v2.20 failed to load.
- Pipeline: Job v2.17 is older than required. To fix, install v2.21 or later.
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
at hudson.PluginManager$2$1$1.run(PluginManager.java:514)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Sep 13, 2018 12:05:30 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline: Declarative v1.3.2 (pipeline-model-definition)
java.io.IOException: Pipeline: Declarative v1.3.2 failed to load.
- Pipeline: Multibranch v2.20 failed to load. Fix this plugin first.
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
at hudson.PluginManager$2$1$1.run(PluginManager.java:514)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Sep 13, 2018 12:05:30 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline v2.5 (workflow-aggregator)
java.io.IOException: Pipeline v2.5 failed to load.
- Pipeline: Multibranch v2.20 failed to load. Fix this plugin first.
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
at hudson.PluginManager$2$1$1.run(PluginManager.java:514)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by gitlawr** [comment]
@kapolos Could you try these to check connectivity:
1. go to the cluster page
2. click `launch kubectl`
3. run `kubectl get pod -n cattle-system`
4. get the pod name of the cluster agent, it should be `cattle-cluster-agent-xxxxxx-xxxx`
5. run `kubectl -n cattle-system exec <agent-pod-name> curl jenkins.cattle-pipeline:8080`, replace <agent-pod-name> with the name you get in step 4.
And check the response.

**Comment by kapolos** [comment]
```
kubectl -n cattle-system exec cattle-cluster-agent-f65bf8445-vgnw4 curl jenkins.cattle-pipeline:8080
error: unable to upgrade connection: container not found ("cluster-register")
```

The output of `kubectl get pod -n cattle-system` was troubling because it showed:
```
NAME                                   READY     STATUS             RESTARTS   AGE
cattle-cluster-agent-f65bf8445-vgnw4   0/1       Error              4059       14d
cattle-node-agent-d4hch                0/1       CrashLoopBackOff   323        1d
cattle-node-agent-rgt72                0/1       CrashLoopBackOff   4400       15d
cattle-node-agent-s7qrb                0/1       CrashLoopBackOff   4500       15d
cattle-node-agent-xwl7m                0/1       CrashLoopBackOff   4480       15d
cattle-node-agent-zf89t                0/1       CrashLoopBackOff   4478       15d
```

I tried restarting docker on the node that cluster-agent lives, and the then I retried the exec  command but the result is the same.

I looked at the logs logs for cluster-register and it has an error like this:
``` 
INFO: Environment: CATTLE_ADDRESS=10.42.4.4 CATTLE_CA_CHECKSUM=4e644db79e0452aaf7712df36bb3f3c09d861fae69007ccc6fd9e34338e837a8 CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-f65bf8445-vgnw4 CATTLE_SERVER=https://--removed--
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
INFO: https://--removed--/ping is accessible
ERROR: Value from https://--removed--/v3/settings/cacerts does not look like an x509 certificate (unable to load certificate 140410060833216:error:0906D06C:PEM routines:PEM_read_bio:no start line:../crypto/pem/pem_lib.c:691:Expecting: TRUSTED CERTIFICATE)
ERROR: Retrieved cacerts:
```

The logs for the node-agents show the same error as well.

I then manually curled the url and it responded with this:
```
{"baseType":"setting","created":"2018-08-23T01:15:35Z","createdTS":1534986935000,"creatorId":null,"customized":false,"default":"","id":"cacerts","links":{"remove":"https://--removed--/v3/settings/cacerts","self":"https://--removed--/v3/settings/cacerts","update":"https://--removed--/v3/settings/cacerts"},"name":"cacerts","type":"setting","uuid":"09daa395-a672-11e8-921e-0242ac110002","value":""}
```

`rancher/rancher` was launched with the `--acme-domain` parameter, if that's relevant.

**Comment by gitlawr** [comment]
The connection to Jenkins relies on the agent so it makes sense when the agent is offline. I wonder if the cluster still looks healthy in rancher?
Can you describe how you set up the rancher instance and if acme-domain points to your rancher correctly

**Comment by kapolos** [comment]
The cluster appears healthy on the Dashboard but it probably isn't.

![image](https://user-images.githubusercontent.com/10794126/45499472-2b500d00-b785-11e8-9948-34500d8b1a3f.png)

Looking at the `System`, there are some red pods:

![image](https://user-images.githubusercontent.com/10794126/45499565-55093400-b785-11e8-9c08-d73d43367350.png)

And I can't connect any more to `kubectl` via the interface (the output before was form the command-line directly).

The rancher instance was setup following the instructions. I also make sure that all nodes have the recommended Docker version and pinned the package to prevent it from updating. I don't really know much about k8s so I haven't messed up with its configs outside of the Rancher interface. The only changes with kubectl I've done was to add some `yaml` files for procuring certificates from `lets-encrypt` - and then I added annotations to the Loadbalancer - nothing else at all.

The certificate is valid:
![image](https://user-images.githubusercontent.com/10794126/45499861-e4aee280-b785-11e8-9a0d-e7b24034ec7f.png)
![image](https://user-images.githubusercontent.com/10794126/45500044-5d15a380-b786-11e8-8339-92b63b5ae0da.png)

At this point, is there perhaps a way to salvage the cluster, or is it probably looking more of a "delete the cluster and start again" situation?

**Comment by gitlawr** [comment]
The kubernetes is functioning so it should be good when the agents are back.
Can you do `kubectl -n cattle-system edit deploy cattle-cluster-agent` and check if `CATTLE_CA_CHECKSUM` envrionment variable is set. If it is, try to remove it and save.

I also wonder how we can get into the invalid cacert case.
Did you bind mount any certs when you start rancher?

And regarding the origin problem, is the pipeline able to run on the cluster whose agents are good?

**Comment by gitlawr** [comment]
By the way, you mentioned that the cluster is a single server but I can see multiple node agent pods, are there multiple nodes in the cluster

**Comment by kapolos** [comment]
@gitlawr 

My apologies, I got confused with the terminology. I meant to say that Rancher is single server (and not a HA cluster). The k8s cluster has many nodes indeed. Sorry for the confusion!

Server A runs `rancher/rancher` and is a k8s node plus `etcd`/`control plane` for the k8s cluster. Servers B,C,D,E are worker nodes of the k8s cluster.

**Comment by cjellick** [comment]
So were you unable to reproduce the original problem @gitlawr

**Comment by kapolos** [comment]
I upgraded `rancher/rancher` to `v2.1.0-rc1` and everything just magically worked - both the original issue and the underlying one. Thank you!

**Comment by gitlawr** [comment]
@cjellick Yes

**Comment by kapolos** [comment]
Update: This happened again while on `2.1.3`. I updated to `2.1.4` (and removed the jenkins pod) and it was solved again.

**Comment by aaronRancher** [comment]
Reopening issue to address https://github.com/rancher/rancher/issues/25577
