### ISSUE TITLE
File logs from container should have pod metadata when sending to logging target

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#15479]
We have a container log volume to mount the log file into host for now and we will use fluentd to collect them and send them to configured target. But this kind of log don't have the pod metadata info when fluentd sending them. We should fetch the pod metadata and put them in fluentd like what we do for container stdout/stderr log.

This feature is required by our customer SAIC.
cc @pengjiang80

**Comment by aiwantaozi** [comment]
Hi, here is some info about this feature. We add more pod related info for user add collect log inside container. 

![image](https://user-images.githubusercontent.com/5936271/48880541-ee228e00-ee4b-11e8-8e05-5cdf9af8bde7.png)

Common step:
1. enable logging
2. add custom log volume to collect log inside container
3. check the log

some test case:
1. directly use the latest rancher server, the log should have the extra pod info
2. use old rancher server before have config one custom log, and then upgrade to the last rancher, the custom log should not have the extra pod info
3. use old rancher server before have config one custom log, and then upgrade to the last rancher, upgrade the old custom log related workload, the custom log should have the extra pod info

**Comment by kingsd041** [comment]
Version: master 2.2 (1/25/19) 
Confirmed fix. The test results are as follows:
```json
    "kubernetes": {
      "container_name": "tomcat-3",
      "namespace_name": "default",
      "pod_name": "tomcat-3-7c6499445f-rxnzt",
      "pod_id": "8f6e2564-206a-11e9-b10c-42010af0008c",
      "labels": {
        "pod-template-hash": "3720550019",
        "workload_user_cattle_io/workloadselector": "deployment-default-tomcat-3"
      },
      "host": "hailong-rancher-2",
      "master_url": "https://10.43.0.1:443/api",
      "namespace_id": "285716a9-205e-11e9-b65e-42010af0008c",
      "namespace_labels": {
        "field_cattle_io/projectId": "p-d26hs"
      }
    }
```
