### ISSUE TITLE
[2.0.8] Custom Project Owner Role with Disabled OOTB Owner wont let me edit a project "There must be at least one member with the Owner role."

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15475]
We have customized the owner role by creating our own that just had the Create Namespace permission removed. The issue is Rancher UI gives the error that at least one member needs to have the owner role but that role is disabled per our requirements.

**Comment by tfiduccia** [comment]
@westlywright - Need to fix in edit project as well
![image](https://user-images.githubusercontent.com/11514927/45654042-e67eeb80-ba8e-11e8-9396-7f44743f8ca6.png)

**Comment by loganhz** [comment]
The current logic is only checking if it has a owner in edit page. So it will not show the message in new project.

I guess the only thing we can do is just removing the `hasOwner` check.

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/20
Verified fixed
