### ISSUE TITLE
Add Namespace to Project from Kubernetes NS Annotation

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15474]
Could it be possible to add a new namespace to a project using the namespace specification/manifest on the kubernetes cluster side? This would allow me to not have to create the namespace using kubectl and then go to rancher ui or use the api/cli to add the namespace to the project.

**Comment by mitchellmaler** [comment]
I figured out it can be done by providing the ```field.cattle.io/projectId:``` annotation. The only issue is I wouldn't know the ids of the cluster and project without doing a lookup using the api before applying the manifest. 

Would be nice if it can be done by "cluster name:project name"

**Comment by mitchellmaler** [comment]
or even just project name without knowing the cluster id

**Comment by superseb** [comment]
The Rancher CLI provides a way to associate a namespace to a project:

```
rancher namespace associate
```
