### ISSUE TITLE
Library Catalogs cannot be completely disabled

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#15486]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.5 to master
rancher/agent or rancher/rancher-agent: v2.0.5 to master

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**

1、Manually disable Library Catalogs in the Global\catalogs；
2、Restart the rancher server container；
3、Login again to rancher ui and visit the Global\catalogs page；

**Results:**
Disabled Library Catalog will automatically reopen

**Comment by guangbochen** [comment]
@StrongMonkey because we don't keep the catalog state anywhere in the rancher, so each time restart the rancher server will recreate the `library` catalog even if it was disabled previously, should we add a setting for the `library` catalog to keep its state?

**Comment by StrongMonkey** [comment]
we can have a setting for default catalog. Moving it into next release.

**Comment by ukinau** [comment]
Hi there, we happened to be in the situation we need to fix this issue.
So I already implement it. Could someone take a look at it?

**Comment by ukinau** [comment]
Any chance to take a look at https://github.com/rancher/rancher/pull/16044 ?

**Comment by zbialik** [comment]
Any update on this? It looks like these errors are causing Rancher not to refresh out private custom-catalog. This means we can't be certain that changes made to charts in our private repo will get registered by Rancher (after running refresh Catalogs).
