### ISSUE TITLE
Add support for EKS Platform Version 2

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15487]
Introducing Amazon EKS Platform Version 2
Posted On: Aug 30, 2018

Amazon Elastic Container Service for Kubernetes (EKS) platform version eks.2 is now available. This update enables API Aggregation for EKS clusters, adding support for Horizontal Pod Auto Scaling and the Kubernetes Metrics Server.

Amazon EKS platform versions are used to refer to a specific patch version of Kubernetes, as well as the Kubernetes API server configuration. New platform versions are released to reflect when Kubernetes patch versions are released or changes are made to how EKS has configured the Kubernetes API server. All EKS clusters created before today are on PlatformVersion eks.1, and new clusters created today will be on the latest platform version (currently eks.2).

To know if your EKS cluster currently has support for a Kubernetes feature or patch, you can look at the EKS platform version in your cluster details in the EKS Console.

To learn more, see the Amazon EKS Documentation.

Visit the AWS region table to see all AWS regions where Amazon EKS is available.

https://aws.amazon.com/about-aws/whats-new/2018/08/introducing-amazon-eks-platform-version-2/

**Comment by soumyalj** [comment]
Tested with v2.1.0-rc7 . Created EKS clusters in all the regions with the updated AMIs specified in
https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
Clusters were created successfully and were functional.
Clusters created are of version 2(eks.2)
