### ISSUE TITLE
generate kubeconfig file from API using custom variables

### ISSUE THREAD

**Issue by imwower** [rancher/rancher#15480]
I can get kube/config from admin UI,
but I can't modify any of the settings, such as, the server URL, the users,
so, How can I use Rancher CLI or kubectl to auto generate a kube config file?

thanks.

**Comment by superseb** [comment]
For 2.x, you can use `./rancher cluster kubeconfig clusterid/clustername`.

For 1.x, the template for kubeconfig is in the UI so you'll have to replicate that yourself if you want to automate it.
