### ISSUE TITLE
Add support for EKS in EU-West

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#15484]
Amazon have recently announced support for EU-West within the EKS product https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-eks-available-in-ireland/

We need to add support for this region to the list of EKS options available

**Comment by synapticscrd** [comment]
Hi Team

Is this something we can hotwire in the interim? Eager to launch in EU-West over here

**Comment by aciddude** [comment]
+1 - running rancher 2.0.8 and really need to spin up EKS clusters in EU-WEST

**Comment by rsilvestre** [comment]
Agree ! +1
Top priority

**Comment by synapticscrd** [comment]
Sir

We are seeing this error on provision to Eu-West-1 after downloading the new Master image

> Error parsing state: rancher does not support region eu-west-1, no entry for ami lookup

Is this still being progressed? I am sure a number of your customers will welcome this support

**Comment by superseb** [comment]
As long as this issue is open, it is not verified that it is fixed.

**Comment by synapticscrd** [comment]
Wilco Sebastiaan

**Comment by maxkorp** [comment]
@synapticscrd backend support is being added in these PRs:

https://github.com/rancher/kontainer-engine/pull/82

https://github.com/rancher/rancher/pull/15545

**Comment by cjellick** [comment]
@maxkorp is there UI needed for this or will the new option just show up in the UI?

**Comment by cjellick** [comment]
I see you have a UI issue open for it.

**Comment by soumyalj** [comment]
Tested with rancher v2.1.0-rc3. Created EKS cluster in EU-West-1 region successfully.
Workload and Layer4 loadbalancers worked successfully.
Issue related to kubectl client / pod exec shell tracked here
https://github.com/rancher/rancher/issues/15716
