### ISSUE TITLE
[Windows] Host created, but nothing working

### ISSUE THREAD

**Issue by hellraisercenobit** [rancher/rancher#15485]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.10
rancher/agent or rancher/rancher-agent: v0.6.0
UI: v1.6.23
CLI: v0.6.4
Rancher Compose: v0.12.5

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.06.2-ee-16, build 9ef4f0a

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows Server 2016

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install Host Windows Server 2016
Add firewall exceptions UDP 500 4500
Run command lines on the host
```
docker network create -d transparent transparent

New-Item -Path 'C:\Program Files\rancher' -Type Directory
Invoke-WebRequest -UseBasicParsing 'https://github.com/rancher/agent/releases/download/v0.6.0/agent.exe' -OutFile 'C:\Program Files\rancher\agent.exe'
& 'C:\Program Files\rancher\agent.exe' -register-service http://192.168.60.63:8080/v1/scripts/D39E3A90E59468DBBA0D:1514678400000:79agbt5KwW7c6Pogw7mVh3ZdQ9g
Start-Service rancher-agent
```
Add host to rancher

**Results:**
Host is created on Rancher but not running correctly.
Impossible to create a container from UI.
Containers created from the host working well and can be manage with the API.

Should i upgrade to rancher version 2 to do that?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
