### ISSUE TITLE
"Inactive. Start" only shows up for 1/2 of the services that I stop

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1548]
v0.27.0-rc4
Steps:
1.  Create a Service, Load Balancer, External Service and a Service Alias
2.  Start all services
3.  Stop all services

Results:
The External Service and Service Alias have a Inactive. Start link showing up, but Service and Load Balancer don't that.
![image](https://cloud.githubusercontent.com/assets/11514927/8711344/e9ec8afa-2b05-11e5-9472-8a05aa83fe7d.png)

Expected:
For consistency we should either have that for all for all of them or none after initial activation.

**Comment by vincent99** [comment]
It's on stopped services that have no containers...

**Comment by deniseschannon** [comment]
@vincent99 Is this still even relevant now that we allow services with no containers?

**Comment by vincent99** [comment]
It would be, but that entire way of displaying services is going away soon... so I'm going to go with no.
