### ISSUE TITLE
UI - Not allowed to edit a cluster with 2 etcd nodes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15494]
**Rancher versions: latest build from master
**Steps to Reproduce:**
Create DO cluster with 1 node (having all roles).
Scale up the node pool to 2.
Once cluster gets to "Active" state with 2 nodes , Edit cluster and a member to it and save.

User is presented withe following message:

<img width="1196" alt="screen shot 2018-09-10 at 11 57 35 am" src="https://user-images.githubusercontent.com/4266958/45318219-15c2b500-b4f1-11e8-92c4-581dc16cea2c.png">

Should UI not being doing this check at this point ? Or should we also be enforcing this check when scaling up/down the existing nodepools ?

**Comment by westlywright** [comment]
The check occurs on the front end, we should add the same check to where ever we can change this change this.

**Comment by tfiduccia** [comment]
@loganhz @westlywright @sangeethah - On the main node page you can just click on the + or - to add specific types of nodes.  So we agreed that we would continue to the check on edit/create and force the user to fix it there.  So the behavior was correct.  I think we need to discuss this more before we just remove the check from edit.

**Comment by westlywright** [comment]
I'll roll this back and we can discuss the proper course of action.

**Comment by loganhz** [comment]
FYI Comment from @vincent99 

https://github.com/rancher/rancher/issues/11985#issuecomment-370680697

**Comment by westlywright** [comment]
@tfiduccia @vincent99 I could see how this may be confusing. One possible solution, rather than prevent the user from using an even amount of nodes for the etcd we simply display a warning about wasted resources?

**Comment by vincent99** [comment]
I think a warning on edit is fine, and it should still let you save with any number if you want to.

**Comment by westlywright** [comment]
@loganhz can you readdress this based on the discussion above?

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
Verified fixed
