### ISSUE TITLE
Error message should reference Limit field not resource type

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15493]
**Rancher versions:** 2.1 master 9/10

**Steps to Reproduce:**
1.  Create a project and have a pod project limit of 10 with default namespace limit set to 2
2.  Create a namespace and remove the pod limit
3.  Click create

**Results:**  Error message says Pods is required.  It's actually the Limit field that required.  Also all required fields should have red * next to them.  So please add this.
![image](https://user-images.githubusercontent.com/11514927/45315754-0855fc80-b4ea-11e8-8cc0-500754447f46.png)

**Comment by westlywright** [comment]
PR is open, I did not remove the reference to the resource type because that is useful in the case of multiple limit errors. 

`<resource> limit is required.`

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/11
Verified fixed
