### ISSUE TITLE
VMs not being cleaned up consistently when cluster is removed in EKS

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#15492]
@Oats87 noticed vms hanging around. Details to follow

**Comment by StrongMonkey** [comment]
Tried two times. Instances were deleted successfully. To be observed...

**Comment by Oats87** [comment]
I have a feeling this is due to EKS not actually cleaning up after itself, rather than something on Rancher's side... I could be wrong though

**Comment by superseb** [comment]
It's `kontainer-engine`'s duty to clean stuff up, it deletes EKS and removes the CloudFormation stacks (this includes the workers ASG). There could be a bug there but haven't seen it yet.

Only problem is that when Rancher is shutdown before its cleaned, it obviously won't be cleaned.

**Comment by cjellick** [comment]
Ok, I think we've done due diligence as far as considering this for v2.1. I will additionally alert QA to this potential problem so that they can ensure through out their testing of 2.1 instances are cleaned up. For the time being, I am going to move this out of the release.
