### ISSUE TITLE
ensure-default-admin not available in rancher server image.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15506]
**Rancher versions: Build from master

Make ensure-default-admin available in rancher/rancher images.

**Comment by cjellick** [comment]
@maxkorp just double checking - did you open a docs PR for this?

**Comment by maxkorp** [comment]
https://github.com/rancher/docs/issues/743

**Comment by sangeethah** [comment]
Tested with latest build from master.

ensure-default-admin is available now.

Scenario1 - Make the default admin user a regular user.
```
root@santest208now:~# docker exec ff4  ensure-default-admin
Found existing default admin user (user-kzw5v)
Existing default admin user (user-kzw5v) is already enabled
Existing default admin user (user-kzw5v) already labeled as admin
Giving existing default admin user (user-kzw5v) admin permissions
root@santest208now:~# 
```

Default admin user gets set as admin user with admin permissions.

Scenario2 - Delete default admin user (as another admin user).
New Default admin user gets created.
```
root@santest208now:~# docker exec 1f9  ensure-default-admin
New default admin user (user-fzz25):
New password for default admin user (user-fzz25):
xkAkBms5jI2TSH_9GVMJ
```

Scenario3 - Deactivate default admin user (as another admin user).
After this , default admin user continues to be in "Inactive" state

```
root@santest208now:~# docker exec 1f9  ensure-default-admin
Found existing default admin user (user-fzz25)
Enabling existing default admin user (user-fzz25)
Existing default admin user (user-fzz25) already labeled as admin
Existing default admin user (user-fzz25) is already an admin
root@santest208now:~# 
```

Reopening this issue to fix Scenario3.

**Comment by cjellick** [comment]
This one slipped through the cracks for RC1.
It is merged, but NOT in rc1.

**Comment by sangeethah** [comment]
Tested with latest build from master.

Deactivate default admin user (as another admin user).
Execute ensure-default-admin.
After this , default admin user gets to "Active" state as expected.
