### ISSUE TITLE
Add T3 AWS instance types (1.6)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15502]
**Rancher versions:** 1.6

**Results:**
Add T3 instance types in the drop-down for AWS hosts.  Also look into adding r5 and r5d too, {large, xlarge, 2xlarge, 4xlarge, 12xlarge, 24xlarge}. They're not generally available but some people have access. https://www.ec2instances.info

**Comment by deniseschannon** [comment]
@loganhz can you investigate if this is a simple UI change? or is it not supported in docker-machine yet?

**Comment by loganhz** [comment]
It's a simple UI change.

**Comment by vincent99** [comment]
Need to add `r5` and `r5d` too, `{large, xlarge, 2xlarge, 4xlarge, 12xlarge, 24xlarge}`.  They're not generally available but some people have access.  https://www.ec2instances.info

**Comment by deniseschannon** [comment]
@loganhz can you make a change in UI for 1.6 snd 2.0 to add all the instance types that are currently available?

**Comment by rsilvestre** [comment]
Hi,

When can we expect to have it in the next stable in production ?

Regards

**Comment by tfiduccia** [comment]
Version - 1.6 master 9/17
Not in build.

**Comment by tfiduccia** [comment]
Version - 1.6.22-rc5
Verified fixed

**Comment by vic-marroquin** [comment]
Hi any chance to get m5a family on rancher 1.6?
