### ISSUE TITLE
When I delete chart app, the namespace is not removed?

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15507]
**Rancher versions:** 2.1 master 9/10

**Steps to Reproduce:**
1.  Deploy catalog app
2.  Delete catalog app

**Results:**  The namespace that was created is not deleted.  Shouldn't we be deleting it?  I mean we can warn user that namespace is going away as well in the Delete Catalog App modal.

**Comment by cjellick** [comment]
This has been discussed numerous times. Was done this way intentionally to ensure rancher doesnt delete a namespace that had other items in it.
Removing from v2.2.
@StrongMonkey if you know of any other tickets that this duplicates, can you reference them here and close this as a dupe?
