### ISSUE TITLE
User shown as "Inactive" even when the deactivate api call fails.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15504]
Rancher server version - Build from master
Steps to reproduce the problem:
Log in as any user and try to deactivate yourself.
API call made to decativate fails with following error:
```
baseType:"error"
code:"InvalidAction"
message:"You cannot deactivate yourself"
status:422
type:"error"
```
But UI shows user as being in "Inactive" state.

<img width="1418" alt="screen shot 2018-09-10 at 3 28 17 pm" src="https://user-images.githubusercontent.com/4266958/45327853-2b92a300-b50e-11e8-82fb-3148d146189a.png">

Once the page is refreshed , it reflects the correct state.

**Comment by tfiduccia** [comment]
@sangeethah - can you verify this.

**Comment by sangeethah** [comment]
Tested with v2.1.0-rc1. 
When user tries to deactivate himself , he is presented with the following error message as expected:
```Error deactivating user
Validation failed in API: You cannot deactivate yourself```
