### ISSUE TITLE
Workload UI: better user experience for enforcing request cpu/memory on the workload if set by the quota on the namespace

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15508]
Kubernetes enforces request/limit for cpu/memory to be passed on the pod spec if the corresponding quota is enabled on the namespace. Not passing those values would result in error from kubernetes. Can we think of how to make it more obvious in the UI, so user enters this information for the workload before hitting save?

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
Verified fixed
