### ISSUE TITLE
Feature Request - EKS - Allow for usage of sessionToken

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#15518]
Rancher versions:
2.0.8

Details
EKS doesn't have the option to pass a sessionToken (amazonElasticContainerServiceConfig). This should be implemented the same way it's implemented for the amazonec2configs.

**Comment by alena1108** [comment]
A duplicate of https://github.com/rancher/rancher/issues/16005. Closing as resolved as the linked issue is resolved and verified.
