### ISSUE TITLE
Seperate mount volume for main container and sidecar container

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#15513]
Reproduce step:
1. enable logging
2. create a workload, add volume, select read log file from path, input log path, and save.
3. create a sidecar container, add volume, UI will show a not path volume for the sidecar, which is the volume in step2, expect show nothing, if user want to add a flexvolume log for the sidecar container, he could add a volume for it, not share the volume with the first one, because the log will mess up, if user input same path log for the main container and the sidecar.

**Comment by cjellick** [comment]
@loganhz did you assign to @aiwantaozi to test it?

**Comment by loganhz** [comment]
Yes, I have pinged her on slack.

**Comment by loganhz** [comment]
@aiwantaozi to validate

**Comment by aiwantaozi** [comment]
Verify pass.
Test step:
1. create a workload add log dir volume
2. add a sidecar container to that workload and also add a log dir volume
3. add pvc volume to that workload
4. above volume are create correct in API.
/close
