### ISSUE TITLE
Feature: Catch ctrl+w in browser shell

### ISSUE THREAD

**Issue by moenka** [rancher/rancher#15517]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.21

I'd like to emphasize that as someone who works with the cli most of the time I got used to keyboard shortcuts that speed up my work. One of those shortcuts is **Ctrl+w** which tends to delete the last written word.

When hitting the shortcut in the browser it closes the tab and I loose the connection to the shell. This is unfortunate and tedious. I know that this is a luxury problem.

Is it possible for you to implement a catch function which stops the shortcut from reaching the browser and instead is translated to the original behavior within the shell when working directly on a container through the browser?

**Comment by cjellick** [comment]
As we are focusing heavily on Rancher 2.0, features like this won't be added to 1.6

**Comment by vincent99** [comment]
This is not possible, and would be heavily abused by popups and advertisers if it were.  

There are various keys that the browser does not allow overriding and this is one of them (in some OSes, short of maybe a native extension).
