### ISSUE TITLE
Add support for VolumeClaimTemplate

### ISSUE THREAD

**Issue by yasker** [rancher/rancher#15519]
Need to add VolumeClaimTemplate support, otherwise, RWO type storage like Longhorn and EBS has no way to scale with the workload. The only way to scale them is to use VolumeClaimTemplate with StatefulSet.

https://github.com/rancher/rancher/issues/13374#issuecomment-390055140

**Comment by cjellick** [comment]
@westlywright @yasker is this truly just a UI issue?

**Comment by yasker** [comment]
Kubernetes always has the functionality as a part of StatefulSet definition. We didn't expose it to the user.

**Comment by westlywright** [comment]
There is no volume claim template support in the workload API.

**Comment by alena1108** [comment]
@westlywright let me know if API changes are needed too.

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/29
Verified fixed.
