### ISSUE TITLE
issue on loadbalancer that dosen't find services with name that are only numbers

### ISSUE THREAD

**Issue by QuentinDeSoete** [rancher/rancher#15516]
**rancher/server:**v1.6.21

**Infrastructure Stack versions:**
healthcheck:v0.3.8
ipsec:v0.13.17
network-services:v0.7.22
scheduler:v0.8.5

**Docker version:**
***Client:***
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

***Server:***
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
Operating system and kernel:**
4.4.0-134-generic
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Type/provider of hosts: Dedicated server 
Setup details: single node ranche rwith external DB)**

**Environment Template:** Cattle

**Steps to Reproduce:** I just updated my rancher from v1.3 to v1.6.21 and when I upgraded my loadbalancer the problem occured.

**Results:**
```
11/09/2018 09:44:34time="2018-09-11T07:44:34Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:36time="2018-09-11T07:44:36Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:38time="2018-09-11T07:44:38Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:40time="2018-09-11T07:44:40Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:41time="2018-09-11T07:44:41Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:44time="2018-09-11T07:44:44Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:46time="2018-09-11T07:44:46Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:48time="2018-09-11T07:44:48Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:50time="2018-09-11T07:44:50Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:50time="2018-09-11T07:44:50Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:53time="2018-09-11T07:44:53Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
11/09/2018 09:44:57time="2018-09-11T07:44:57Z" level=error msg="Failed to get lb config: Error 404 accessing /stacks/Production/services/748 path"
```

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
