### ISSUE TITLE
"?" shown for host state when agent is in "reconnecting" state

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1552]
Server version - V0.28.0-rc1

UI shows state as "?" for One of the host with state="active" and agentState="reconnecting" .
<img width="371" alt="screen shot 2015-07-15 at 5 11 16 pm" src="https://cloud.githubusercontent.com/assets/4266958/8712837/1cd864e2-2b16-11e5-8c59-1e108833f105.png">

**Comment by vincent99** [comment]
The backgroung color was missing for this state.  If you look closely you can see "RECONNECTING" in the top-left corner.  I like the question mark icon though, since we have no idea what state the host is in or if it will ever return when we're disconnected.

**Comment by deniseschannon** [comment]
Verified Fixed v0.30.0-rc2
