### ISSUE TITLE
Add Custom User and Group Search Filter Fields in Customize Schema Section

### ISSUE THREAD

**Issue by carolynhu** [rancher/rancher#15534]
We need add UI support for this issue:https://github.com/rancher/rancher/issues/13656
When we enable AD, in the customized schema section
<img width="1269" alt="screen shot 2018-09-11 at 5 22 22 pm" src="https://user-images.githubusercontent.com/29208297/45394801-6e747980-b5e7-11e8-8f16-91b7d43f1f02.png">
two extra fields need to be added, one is for user: `UserSearchFilter` and another one is for group: `GroupSearchFilter`.

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
UI is passing new fields to API
Verified fixed
