### ISSUE TITLE
EKS recommended AMIs need to be updated

### ISSUE THREAD

**Issue by maxkorp** [rancher/rancher#15531]
Per here: https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html

![screen shot 2018-09-11 at 4 27 06 pm](https://user-images.githubusercontent.com/1302526/45393179-91029480-b5df-11e8-8bed-2eb4f9fb518c.png)

There are newer recommended AMIs for us-west-2 and us-east-1

**Comment by superseb** [comment]
I don't think this can be changed, it needs eks.v2:

Important

These AMIs require the latest AWS CloudFormation worker node template. You cannot use these AMIs with a previous version of the worker node template; they will fail to join your cluster. Be sure to upgrade any existing AWS CloudFormation worker stacks with the latest template (URL shown below) before you attempt to use these AMIs.

https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2018-08-30/amazon-eks-nodegroup.yaml

https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

https://github.com/rancher/rancher/issues/15487

**Comment by nathan-jenan-rancher** [comment]
Fixed by PR https://github.com/rancher/kontainer-engine/pull/86

**Comment by soumyalj** [comment]
Tested with v2.1.0-rc7 . Created EKS clusters in all the regions with the updated AMIs specified in 
https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
Clusters were created successfully and were functional.
