### ISSUE TITLE
SAML ADFS Accepts Invalid Attributes on Form Validation

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rancher#15530]
**Rancher versions:**
rancher/rancher: **v2.0.8**

**Steps to Reproduce:**

Follow the steps to configure ADFS from the documentation

https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/microsoft-adfs/

Add the following attributes on the ADFS Authentication form

```
Display Name Field: FakeField
UID Field: FakeField
User Name Field: FakeField
Groups Field: http://schemas.xmlsoap.org/claims/Group
```

Enter login and password in the SAML redirection page.

**Results:**

User is able to login and **ADFS Authentication is enabled**. This should not be happening with invalid FakeField attributes. The validation logic should of blocked ADFS auth to be enabled with invalid attributes. SAML should return an invalid response and the form should complain with an error message and ADFS auth should be disabled.

```
root@massimo-server:~# curl -s https://massimo.do.rancher.space/v3/users/user-t6sns \
  -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" | jq
{
  "actions": {
    "setpassword": "https://massimo.do.rancher.space/v3/users/user-t6sns?action=setpassword"
  },
  "annotations": {
    "lifecycle.cattle.io/create.mgmt-auth-users-controller": "true"
  },
  "baseType": "user",
  "conditions": null,
  "created": "2018-09-11T22:42:09Z",
  "createdTS": 1536705729000,
  "creatorId": null,
  "description": "",
  "enabled": true,
  "id": "user-t6sns",
  "labels": {
    "authz.management.cattle.io/bootstrapping": "admin-user"
  },
  "links": {
    "clusterRoleTemplateBindings": "https://massimo.do.rancher.space/v3/clusterRoleTemplateBindings?userId=user-t6sns",
    "globalRoleBindings": "https://massimo.do.rancher.space/v3/globalRoleBindings?userId=user-t6sns",
    "pipelineExecutions": "https://massimo.do.rancher.space/v3/pipelineExecutions?triggerUserId=user-t6sns",
    "projectRoleTemplateBindings": "https://massimo.do.rancher.space/v3/projectRoleTemplateBindings?userId=user-t6sns",
    "remove": "https://massimo.do.rancher.space/v3/users/user-t6sns",
    "self": "https://massimo.do.rancher.space/v3/users/user-t6sns",
    "sourceCodeCredentials": "https://massimo.do.rancher.space/v3/sourceCodeCredentials?userId=user-t6sns",
    "sourceCodeRepositories": "https://massimo.do.rancher.space/v3/sourceCodeRepositories?userId=user-t6sns",
    "tokens": "https://massimo.do.rancher.space/v3/tokens?userId=user-t6sns",
    "update": "https://massimo.do.rancher.space/v3/users/user-t6sns"
  },
  "me": true,
  "mustChangePassword": false,
  "name": "Default Admin",
  "principalIds": [
    ""
  ],
  "state": "active",
  "transitioning": "no",
  "transitioningMessage": "",
  "type": "user",
  "username": "admin",
  "uuid": "eb0a05aa-b613-11e8-90e2-0242ac120002"
}
```

**Comment by massimo-cannavo** [comment]
Also there was a weird issue where the customer would get locked out from rancher when enabling ADFS auth with NameField as the value for all the form attributes except for Groups Field.

[ERROR] API error response 500 for POST /v3-public/localProviders/local?action=login. Cause: can't find unique user for principal

**Comment by vincent99** [comment]
Logging in is all the OAuth flow and does not involve those fields.  Except for maybe we should be refusing to create a user entry if there's no result for UID. The rest of the fields are for principal lookup info and I don't know how you'd distinguish "wrong" from "this user entry happens to not have that field".

**Comment by vincent99** [comment]
If you set the fields wrong so that the one that uniquely identifies users isn't unique, then you're going to have a bad time.

**Comment by sangeethah** [comment]
Tested with rancher server build from master - Nov 26.

Enable ADFS auth:
Add the following attributes on the ADFS Authentication form
```
Display Name Field: FakeField
UID Field: FakeField
User Name Field: FakeField
Groups Field: http://schemas.xmlsoap.org/claims/Group
Enter login and password in the SAML redirection page.
```

User is presented is redirected to this page with no content presented:
```https://<ip>/verify-auth?config=adfs/login?errorCode=500```

@mrajashree We should be able to present the user with some error message in this case?

Following logs are seen:
```2018/11/28 01:28:38 [ERROR] SAML: Unique ID field is not provided in SAML Response```

**Comment by sangeethah** [comment]
Reopening this issue to see if error message can be presented to the user.

**Comment by mrajashree** [comment]
The blank page being presented might require a UI change, something similar to this `https://github.com/rancher/ui/blob/master/lib/login/addon/login/controller.js#L37` but for errorCode=500?
@westlywright do you think this is right?

**Comment by cjellick** [comment]
@westlywright can you follow up on this issue

**Comment by westlywright** [comment]
Yes I'll need to make an update to the UI code

**Comment by cjellick** [comment]
im going to unassign @mrajashree then and mark as a UI issue

**Comment by sangeethah** [comment]
Tested with build from master - Feb 18

Tested with rancher server build from master - Nov 26.

Enable ADFS auth:
Add the following attributes on the ADFS Authentication form

```
Display Name Field: FakeField
UID Field: FakeField
User Name Field: FakeField
Groups Field: http://schemas.xmlsoap.org/claims/Group
Enter login and password in the SAML redirection page.
```

User it brought back to the AD auth page and presented with error message - `Invalid saml attributes` as expected.

<img width="1217" alt="screen shot 2019-02-21 at 11 26 05 am" src="https://user-images.githubusercontent.com/4266958/53196631-5f014f80-35cd-11e9-9d54-de3c88a6c7b2.png">
