### ISSUE TITLE
 "Nginx Ingress" and "Metrics Server Monitoring" disabled for RKE clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15543]
**Rancher versions:** Latest build from master

**Steps to Reproduce:**
Create a custom cluster .
In cluster option I see "Nginx Ingress" and "Metrics Server Monitoring" being disabled even though I see the default value being correctly set in cluster schema .

Also When u i try to enable "Nginx Ingress" , it disables "Metrics Server Monitoring" automatically in UI

<img width="1280" alt="screen shot 2018-09-12 at 10 20 48 am" src="https://user-images.githubusercontent.com/4266958/45442183-2b151c00-b676-11e8-9a1a-d462f10934a0.png">

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/12
Network provider default & Project Network Isolation has been resolved.  Wes asked me to move the Ingress & Metrics default issue out to another bug. #15559
