### ISSUE TITLE
Add eu-west-1 option for EKS cluster location

### ISSUE THREAD

**Issue by maxkorp** [rancher/rancher#15546]
UI component of https://github.com/rancher/rancher/issues/15484

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/12
UI option is in.  But can't create cluster with it cause it's not supported by backend?

**Comment by maxkorp** [comment]
Backend code is awaiting review here: https://github.com/rancher/rancher/pull/15545

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
Verified fixed
