### ISSUE TITLE
UI - Enable -" Even if there are DaemonSet-managed pods." by default when drain option is performed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15548]
**Rancher versions: Latest build from master

**Steps to Reproduce:**
Attempt to drain a node.

In the options presented to the user , Enable -" Even if there are DaemonSet-managed pods." by default.

<img width="982" alt="screen shot 2018-09-12 at 11 21 14 am" src="https://user-images.githubusercontent.com/4266958/45445033-04f37a00-b67e-11e8-8ccd-50813e6d2d15.png">

Without this option enabled, drain will never succeed since we have Ingress daemon set running on them.

**Comment by cjellick** [comment]
Can we also add a note that explains it is selected by default because without this option enabled, drain will never succeed since we have Ingress daemon set running on them.

Wordsmithing needed!

**Comment by kinarashah** [comment]
also just to notify, even when it's set to true, kubectl won't actually delete these pods anyway. 
we just need this to be true so kubectl starts the drain.

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/19
Verified fixed
