### ISSUE TITLE
How to customize parsing address by rancher-dns

### ISSUE THREAD

**Issue by kys1230** [rancher/rancher#15542]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.20` Cattle: `v0.183.60` UI: `v1.6.45` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

There is a container network_mode: host, and I want to customize the parsing address of rancher-dns for this container. Is that possible?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
