### ISSUE TITLE
Support proxy protocol on LB service

### ISSUE THREAD

**Issue by leonkyneur** [rancher/rancher#1554]
It would be nice to be able to configure the 'send-proxy' parameter for TCP load balanced services. This would allow supported applications to see the real address of client connections.

1. https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#5.2-send-proxy
2. http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

**Comment by schuylr** [comment]
AFAIK this would only require a `send-proxy` directive to be added to every `server` line in the `haproxy.cfg` - would this be hard to achieve? What is blocking completion of this issue?

**Comment by blackjid** [comment]
I'm not really sure, but in the latest version of rancher you can add custom configuration into the `haproxy.cfg`

![screen shot 2015-12-22 at 10 30 29 am](https://cloud.githubusercontent.com/assets/228037/11958683/27677ade-a897-11e5-8486-1e2a901c937b.png)

It is limited to the `global` and `defaults` sections... but I think (haven't tested) the `send-proxy` directive could be used in the `defaults` section... http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.2-send-proxy

**Comment by schuylr** [comment]
Hmmm... one might be able to add it to the `defaults` section using `default-server`:

```
default-server send-proxy
```

Let me test that now and report back. If so, this issue is moot!

**Comment by schuylr** [comment]
Works great! With a bit of documentation I think this issue can be closed. It's just as simple as adding `default-server send-proxy` to the `defaults` section - any server that isn't configured with proxy_protocol isn't affected by `send-proxy` being enabled, either - so a server-specific configuration isn't really necessary.

**Comment by schuylr** [comment]
I deleted my previous comment, turns out it was lingering settings from my previous hack. `send-proxy` is *not* a supported option in `default-server` as per [these docs](http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5):

>Supported in default-server: No

Thus, it is necessary to add it to each `server` line.

**Comment by blackjid** [comment]
oh, you are right...

**Comment by deniseschannon** [comment]
This should be fixed with the load balancer refactoring that is in progress.

We should be allowing configuring the backend of haproxy as soon as refactoring is complete. #2179 

Closing in favor of the refactoring issue..

**Comment by schuylr** [comment]
Thanks @deniseschannon - in that case it should also address my other raised issue #3125 so I'll close that as well.
