### ISSUE TITLE
Disallow turning on multiple auth providers

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#15544]
Need to discuss with @westlywright if he can do this without backend changes

**Comment by westlywright** [comment]
Repro:
Enable a single auth provider
All other providers are removed from the UI

**Comment by westlywright** [comment]
To test the flip-side, that is you have 2 or more enabled and we allow you to disable or edit but not add more, you'll either need to have a server that has 2 or more auth providers enabled already. If you do not have a server in this state you can do the following:
1. change the setting at `v3/settings/ui-index` part of the path that says `latest2` to `wo-multi-auth-disabled` then refresh your ui
2. enable 2 or more providers, i tested with AD+Github
3. change the setting at `v3/settings/ui-index` back to `latest2` then refresh your ui

Now only you're enabled providers will show up.

**Comment by tfiduccia** [comment]
Version 2.1 - master 9/18
Verified fixed
