### ISSUE TITLE
[rancher-dns] sysctl net.core.somaxconn

### ISSUE THREAD

**Issue by rslnx** [rancher/rancher#15553]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.18
rancher/agent or rancher/rancher-agent: v1.2.10

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:58 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:24 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
# docker info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 69
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
Kernel Version: 3.19.0-80-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797GiB
Name: ea-preprod-06
ID: XSLL:U6GH:TY3M:Y6L5:Y4J4:VO22:R5PX:IIT2:J4X3:UBAP:ORUN:O3SR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
```
# uname -r
3.19.0-80-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Deploy more than ~128 load balancers onto one host.

**Results:**
Load balancer services go offline and new load balancer services just don't start. In logs there are errors connecting (dialling) to rancher-dns service. I guess that could be 
because of net.core.somaxconn=128 in rancher-dns container.

I am still not sure it's the case – I was not able to modify somaxconn value in the container to check. Should the sysctl setting be added into dns service definition?

```
  dns:
...
    sysctls:
      net.core.somaxconn: '65535'
```

**Comment by rslnx** [comment]
@deniseschannon @alena1108 Is there any way to test change of docker-compose.yml.tpl file? I tried changing the yml.tpl file in a volume of rancher/server container and redeploying dns service but with no luck – new dns container was created with the same old yml definition (i.e. w/o sysctl setting).

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
