### ISSUE TITLE
Ingress & Metrics can't be enabled by default

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15559]
**Rancher versions:** 2.1 master 9/12

**Results:**  Can't enable the Ingress or Metrics Cluster Options by default. 
![image](https://user-images.githubusercontent.com/11514927/45456611-51e84800-b6a0-11e8-866f-2c64e6d927ea.png)

**Comment by deniseschannon** [comment]
@tfiduccia can you check if this is still an issue

**Comment by tfiduccia** [comment]
Version - v2.2.2-rc2
Verified fixed
