### ISSUE TITLE
Logging drivers advanced mode

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#15558]
Similar to the way we support advanced options in other areas of the UI, we need to support the ability for the user to specify Target output parameters that do not have UI options. Essentially, in an advanced mode, they can edit:

```
<match *>
  @type elastic
{{USER DEFINED CONFIG}}
</match>
```

This will allow users to specify TLS ciphers etc. 

It should limit the user to only providing config for the types we support, so the user doesn't accidentally try to use a type not supported in the Rancher Fluentd image.

The user should still be able to provide TLS certificates that will be installed via Rancher. The user should be told the path they can use in the configuration for the certs. It will be up to the user to configure that appropriately. Some form of validation should be performed so that certificates for other targets/projects can not be used. This validation should be done on save if possible.

**Comment by aiwantaozi** [comment]
For testing, this allows the user to input the raw fluentd config for output. You could see the @type forward, this is forward type, now we support these types, you could check the doc to see what config you could set for a different target.
elasticsearch:  https://github.com/uken/fluent-plugin-elasticsearch
splunk: https://github.com/fluent/fluent-plugin-splunk
kafka: https://github.com/fluent/fluent-plugin-kafka
syslog: https://github.com/dlackty/fluent-plugin-remote_syslog
fluentd: https://docs.fluentd.org/v1.0/articles/out_forward

**Comment by kingsd041** [comment]
This issue needs to wait for the https://github.com/rancher/rancher/issues/18476 fix before it can be verified.

**Comment by kingsd041** [comment]
Version: master 2.2 (1/28/19) 
Confirmed fix.

According to the following test cases, the advanced modes of the logging target supported by Rancher were tested, include: Elasticsearch, Splunk, Kafka, Syslog, Fluentd

In addition to https://github.com/rancher/rancher/issues/18310, other test cases have all passed the test.


- Support for configuring TLS certificate
- Make sure the correct TLS certificate can send logs
- Make sure that an error or an empty TLS certificate will get a failure message
- Use `Rry Run` to verify the format of `match`and TLS certificate
- Custom Log Fields
- If it is cluster level logging, it will verify `Include System Log`
- Only supported types supported in Rancher Fluentd images. Including: elasticsearch, splunk_hec, kafka_buffered, remote_syslog, forward
- When configuring the TLS certificate, inform the user of the configuration path of the certificate
