### ISSUE TITLE
Save server configuration

### ISSUE THREAD

**Issue by IMikkeI** [rancher/rancher#1555]
Hi,

Is there any way to save my rancher server's configuration ? The idea is to commit the image and be able to restart my server image with all my configuration (services, environment,...) restored.

Thanks for any help.

Mikke

**Comment by ebuildy** [comment]
I believe Rancher stores everything on mysql, you can create your own mysql server (via Docker) with a shared volume.

I don't have a complete example but:

https://github.com/rancher/rancher/wiki/Setup:-MySQL

**Comment by VogonogoV** [comment]
You can use an external database pretty easily

http://rancher.docs.rancher.com/docs/installing-rancher/installing-server/#using-an-external-database

**Comment by deniseschannon** [comment]
If you have an existing Rancher server already set up, you can also create a data only container and use the container to start another Rancher server. It's outlined in our upgrading docs.

http://docs.rancher.com/rancher/upgrading/

**Comment by IMikkeI** [comment]
Ok thanks for all you answer and your help.

**Comment by IMikkeI** [comment]
How can I use an external mysql database on another container to store my configuration ?

I have pulled 'mysql' container, I launched it and when I try to link rancher with this container I have a "i.c.p.a.sources.LazyJDBCSource" error.

**Comment by deniseschannon** [comment]
@IMikkeI It should be possible.

Did you log into the mysql database to create the database? Per the docs, you'll need to have it created in order for Rancher to be able to create the database schema. Also, linking the container may not be enough to access the container. 

After you launch the rancher/server container, you can look at the start of the `docker logs` of the rancher/server contianer and see if the appropriate environment variables were set for the DB. 

FYI, I updated the docs links in @VogonogoV's response so the link should work now.

**Comment by IMikkeI** [comment]
Thanks for your help, it works now. I haven't created the database.

There's something I don't understand : when do Rancher save is configuration in the database ? My db is always empty.

**Comment by deniseschannon** [comment]
@IMikkeI If your DB is always empty, then the DB must not have been configured properly. I haven't tested using a mysql container as the DB, but will try to do so soon.

**Comment by deniseschannon** [comment]
@IMikkeI I just tested this scenario out and was able to get it working and the schema was saved.

step 1: create mysql container
step 2: exec into mysql container and follow instructions to create database in mysql
```
root@containerID:/# mysql --user=root --password=<root_password_defined_on_container_creation>
mysql> CREATE DATABASE IF NOT EXISTS cattle COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';
mysql> GRANT ALL ON cattle.* TO 'cattle'@'%' IDENTIFIED BY 'cattle';
mysql> GRANT ALL ON cattle.* TO 'cattle'@'localhost' IDENTIFIED BY 'cattle';
```
step 3: launch rancher server connecting to mysql container
```
sudo docker run -d --restart=always -p 8080:8080 --link <mysql_container_name>:mysql -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle -e CATTLE_DB_CATTLE_USERNAME=root -e CATTLE_DB_CATTLE_PASSWORD=<root_password_defined_on_container_creation> rancher/server:latest
```

**Comment by IMikkeI** [comment]
I've tried to follow your instructions. I run mysql container and the rancher server. When I stop and delete the rancher container and when I restart it using the same db, all my configuration is lost. And if I check the "cattle" database on the container, it is empty.

My wish is if there's any problem on my rancher server and I have to delete it, with the help of the mysql which save the configuration, I can retrieve my server's configuration at any time.
Is it possible ?

**Comment by ebuildy** [comment]
On a fresh install and run with:

````
DOCKER_RUN		:= docker run -l io.rancher.container.network=true -tid --restart=always

$(DOCKER_RUN) 	-v ${SHARED_DATA}/data:/var/mysql/data:rw \
					--name rancher-data \
					${IMAGE_PREFIX}rancher-data

$(DOCKER_RUN) \
			--name rancher-server \
			--link rancher-data:mysql \
			-e CATTLE_DB_CATTLE_MYSQL_HOST: mysql \
            -e CATTLE_DB_CATTLE_MYSQL_PORT: 3306 \
            -e CATTLE_DB_CATTLE_MYSQL_NAME: cattle \
            -e CATTLE_DB_CATTLE_USERNAME: cattle \
            -e CATTLE_DB_CATTLE_PASSWORD: cattle \
			rancher/server
````

I got on rancher logs:

````
error: database is uninitialized and MYSQL_ROOT_PASSWORD not set
````

**Comment by ebuildy** [comment]
Followed instructions, everything runs fine!

Changed "-e CATTLE_DB_CATTLE_MYSQL_PORT: <port>" to '-e "CATTLE_DB_CATTLE_MYSQL_PORT=<port>"'

**Comment by deniseschannon** [comment]
@IMikkeI I was able to stop and delete the rancher server container and start a new container using the DB and my configuration was saved. 

When you first start up Rancher server, can you confirm that the configuration is being saved in the mysql container? Can you exec into the mysql container and see the cattle DB schema?

@ebuildy I just made the update to the docs for the typo on `:` to `=`

**Comment by IMikkeI** [comment]
When I start my server, I check the DB cattle with "show tables" and it is empty.

On the server logs, there's no error. I use a container (debian:jessie) where I have installed mysql-server (with apt-get). I've started mysql service and I have created the database following your instructions.

Rancher creates the DB schema when it starts and without any operations on the server ?

**Comment by deniseschannon** [comment]
Yes, Rancher will create the DB schema when it starts without  any operations on the server. Something in the run command is not linking to your external DB.

Can you provide the command that you used to start Rancher Server? Would you be willing to try the mysql container instructions that I listed above?

**Comment by IMikkeI** [comment]
The command to start Rancher Server :

sudo docker run -d --restart=always -p 8080:8080 --link sql:mysql -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle -e CATTLE_DB_CATTLE_USERNAME=root -e CATTLE_DB_CATTLE_PASSWORD=xxx -e CATTLE_DB_CATTLE_MYSQL_PORT=3306 rancher/server:latest

I have followed exactly the instructions that you have listed :
root@containerID:/# mysql --user=root --password=<root_password_defined_on_container_creation>
mysql> CREATE DATABASE IF NOT EXISTS cattle COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8';
mysql> GRANT ALL ON cattle.* TO 'cattle'@'%' IDENTIFIED BY 'cattle';
mysql> GRANT ALL ON cattle.* TO 'cattle'@'localhost' IDENTIFIED BY 'cattle';

In my DB, I have the database cattle created.

**Comment by ebuildy** [comment]
You create a database with user cattle/cattle, so CATTLE_DB_CATTLE_USERNAME should be cattle and password cattle as well.

**Comment by ebuildy** [comment]
I am not sure you need an external mysql server in order to save the cattle DB. As you can see on the Dockerfile:

https://github.com/rancher/rancher/blob/master/server/Dockerfile

You can mount **/var/lib/mysql**

**Comment by IMikkeI** [comment]
Same thing with cattle for user/passwd...

I'll try the mount solution, thanks

**Comment by deniseschannon** [comment]
@IMikkeI I am not sure if the command I provided will work in your set up as you have started a container and inside the container started mysql. I'm not sure how to link the my sql inside the debian:jessie container with the rancher container. In my example, I had used the mysql image and created a container and linked the two containers together.

**Comment by deniseschannon** [comment]
@IMikkeI If you're still having issues, please re-open.

**Comment by RafaelGSS** [comment]
> You can use an external database pretty easily
> 
> http://docs.rancher.com/rancher/installing-rancher/installing-server/#using-an-external-database

Is updated the link: https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#launching-rancher-server---single-container---external-database
