### ISSUE TITLE
Disallow move action for namespace if target project has quota set

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15563]
Till we put a proper implementation for resource quota on a move action as a part of https://github.com/rancher/rancher/issues/15549, we need to disallow moving the namespace to a project with resource quota set.

**Comment by cjellick** [comment]
Putting to merged, but not ready to test because the CLI needs fixed for this too. When the CLI PR is merged, will move it to test

**Comment by soumyalj** [comment]
Tested with master from Sep 14th. 
Create a project "P1" without any resource quota assigned and create a namespace "N1" in P1
Create a project P2 with resource quota assigned.
Move N1 to project P2

Move is not allowed as expected. 
Server logs:
```
2018/09/14 18:39:54 [ERROR] Unknown error: can't move namespace. Project P2 has resource quota set

```
Error message below:
<img width="1122" alt="screen shot 2018-09-14 at 11 34 22 am" src="https://user-images.githubusercontent.com/18536626/45568881-bb886380-b812-11e8-8f00-d528e478c6c8.png">

https://github.com/rancher/rancher/issues/15612
