### ISSUE TITLE
UI gets stuck in "saving" stage when creating AKS cluster with invalid docker bridge address range

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15564]
**Rancher versions:**
rancher/server or rancher/rancher:master from September 12th

**Steps to Reproduce:**
1. Create a AKS cluster with advanced options.
2. Provide an IP address instead of address range for docker bridge address
3. The UI gets stuck in "saving" stage as below

![screen shot 2018-09-12 at 11 54 07 am](https://user-images.githubusercontent.com/18536626/45460370-cd062a00-b6b1-11e8-8ff9-35e3e6524dbe.png)

Also, note that the field should be named as Docker bridge address range instead of docker bridge address.

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
Verified fixed
