### ISSUE TITLE
Execute shell closes directly after opening

### ISSUE THREAD

**Issue by zdYng** [rancher/rancher#15565]
*Describe your issue here*

When I open rancher-ui, I enter the shell interface of the container, can't get in, and always flash back.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.21` Cattle: `v0.183.60` UI: `v1.6.45` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by superseb** [comment]
Please describe more information on how to reproduce, the `Execute Shell` option shells into the container, can you run `docker exec -ti container_id sh` or `docker exec -ti container_id bash` on the command line on that host?

What Docker image are you testing with?

**Comment by superseb** [comment]
Let me know when you supply the requested info.
