### ISSUE TITLE
Network Connectivity Issues after upgrade to 2.0.8

### ISSUE THREAD

**Issue by Skater101b** [rancher/rancher#15576]
**Rancher versions:**
rancher/server or rancher/rancher:  rancher/rancher 2.0.8
rancher/agent or rancher/rancher-agent: 

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7.5

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create multiple projects with multiple namespaces.
2. Deploy a base centos container into each namespace in each project.
3. Execute Shell into the containers and ping google.com
4. Flannel network, but I reproduced it with canal too.

I would expect it to resolve for all the containers in all the namespaces in all the projects, but it does not.
**Results:**

I have a project Lab-A which has a  default namespace. I deployed two identical centos base images and one can reach externally the other can not.

Here are two base centos containers.
![centos1](https://user-images.githubusercontent.com/8505334/45506923-afdb6500-b75e-11e8-9161-a4b51273a520.png)

Now watch me ping them. (One works one does not)
![centos2](https://user-images.githubusercontent.com/8505334/45507060-0a74c100-b75f-11e8-8187-969d7e554aae.png)

We just upgraded today from 2.0.6 to 2.0.8. I did not notice this problem before. Here is what I noticed.

1. It happens with deploying multiple containers into the same namespace. Some work some don't (see example above)

2. I tried deploying containers in different namespaces within different projects in the same cluster and the problem persisted. 

3. I deployed a container in two different projects, that were deployed to the same compute host, and the problem still occurred. 

It's hit or miss. There doesn't appear to be an exact replication path. It's kind of trial and error, but it is reproducible.

When I say it can't ping google.com, what I also mean is that it can't take advantage of service discovery either.

I have noticed that I left and came back an hour later and 2 of the million containers I had that were failing before, all of a sudden worked. So I am not sure what to make of this.

**Comment by krishofmans** [comment]
Most likely this issue: https://github.com/rancher/rancher/issues/15146#issuecomment-414738661

Fixes are posted there as well

**Comment by superseb** [comment]
There is a fix mentioned here https://github.com/rancher/rancher/issues/15146#issuecomment-424251395

Possibly you are hitting this https://github.com/rancher/rancher/issues/13644

Let us if you have steps to reproduce the issue.

**Comment by Angelinsky7** [comment]
sadly i've got the exact same isssue (with a fresh install) and flushing iptable does not change anything...  i don't understand the fix that you are mentioning.
if Network Project Isolation is activated all DNS request are bloqued... but ping is working fine.

my config is 

```
Rancher | v2.1.4
User Interface | v2.1.18
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1
Kubernetes | v1.11.5-rancher1-1
```

Could someone help me, please, to understand what i need to do to have Network Project Isolation activated and kubernetes working correctly with dns resolve (and maybe the other services that cannot communicate that i don't see yet)

**Comment by deniseschannon** [comment]
If anyone is still facing issues with a 2.2 release, please open a new issue.

**Comment by JeremyBesson** [comment]
As you mention @Angelinsky7, you have a Network connectivity issue on a Rancher v2 fresh install. We face the same problem but this doesn’t seem to be solved with a new Rancher version. 

Did you find a workaround for your installation ?

**Comment by Angelinsky7** [comment]
@JeremyBesson 

Hi,
my actual configuration changed a lot but this issue seemed to come from the firewall configuration of the OS. If you totally disable it, it should work as expected... then you can find what is blocking what.
But from what i remember, it was an issue with the docker's networks (that docker created) that were not accessible from docker....
