### ISSUE TITLE
Docker not responding after cloned host

### ISSUE THREAD

**Issue by ebuildy** [rancher/rancher#1557]
I have taken a snapshot of my host A running Docker with a ranger agent, then create a new VM B from this snapshot.

On Rancher server I can see host A disconnected, and I cannot use Docker any more on host A ! Looks like an issue with network/iptable, I had to reboot the VM then everything was fine!

I am sorry to not give more details, I can see docker daemon running but got a timeout when doing a simple ***docker ps***

**Comment by ebuildy** [comment]
Same thing if I stop the rancher-agent ;-(

**Comment by ibuildthecloud** [comment]
If you ever see `docker ps` just hang.  Run `dmesg`.  If you see an output similar to

    unregister_netdevice: waiting for lo to become free. Usage count = 3

Then it's this bug https://github.com/docker/docker/issues/5618.  Unfortunately there is no solution to this issue except to restart the server.

**Comment by ibuildthecloud** [comment]
Supposedly there is a fix in Linux for this, more info at https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1403152

**Comment by ebuildy** [comment]
Ha thanks you very much.

I got this problem only after stopped a rancher-agent, maybe it's related.

**Comment by ebuildy** [comment]
It's definitively due to Rancher ;-( 

From a fresh install:

1- Add Rancher agent
2- Remove it
3- Add a new Rancher agent
4- Docker blocked ;-( reboot
5- Add a new Rancher agent ==> runs fine 

Maybe some iptable are not “cleaned" when agent is removed?

**Comment by sangeethah** [comment]
Similar issues are tracked in  #1406 and  #931 where we docker is not responding.

**Comment by ebuildy** [comment]
Thanks you, right, this is not really reliable for a production environnement ;-(
