### ISSUE TITLE
Adding tolerations to a workload via the UI does not work

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#15585]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent: 2.0.8

**Steps to Reproduce:**
Create workload
Click Node Scheduling
Show Advanced Options
Add Toleration (for example, 

- key: node-role.kubernetes.io/controlplane 
- operator: equals 
- value: true 
- seconds: 0

)
Click Upgrade or Create

**Results:**
Toleration is not added to the workload.

**Comment by lbarthelemy** [comment]
I have the same issue in my setup.

**Rancher versions:**

Rancher | v2.0.8
User Interface | v2.0.67
Helm | v2.9.1-rancher1
Machine | v0.15.0-rancher1-1

**Comment by mrigesh** [comment]
+1

**Comment by dwaynebradley** [comment]
+1

**Comment by loganhz** [comment]
UI sends the correct payload to backend. But it looks like server can not populate it correctly.

And if you deploy a workload by YAML with correct `tolerations`,  you still can not see tolerations field in API.

I guess we need to fix it in API

**Comment by kinarashah** [comment]
@loganhz in 2.1.1, I am not able to reproduce this, able to add tolerations using create/update 

```
scheduling": {
"node": {
"nodeId": null,
"requireAll": [
"node-role.kubernetes.io/controlplane = 0"
]}},
 ```

**Comment by loganhz** [comment]
@kinarashah I can reproduce it in 2.1.1. 

![image](https://user-images.githubusercontent.com/21168270/48095597-16a56800-e250-11e8-83de-88536874c671.png)
![image](https://user-images.githubusercontent.com/21168270/48095648-32107300-e250-11e8-8936-245745492e48.png)

**Comment by leodotcloud** [comment]
Looks like there is no support for Tolerations on the backend/API. I don't see the tolerations listed either in the Workload or Deployment. Same problem with the Go SDK as well.

**Comment by kinarashah** [comment]
@loganhz fixed. 
Also, UI needs to change `Equals` to `Equal` https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2733

**Comment by loganhz** [comment]
Thanks!

**Comment by loganhz** [comment]
@kinarashah UI PR is here https://github.com/rancher/ui/pull/2533

But we still need a rancher/rancher PR to update types.

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/2/19)
Confirmed fixed.
- Validated that the UI is still correctly sending scheduling information.
- Validated that the pod indeed has our Toleration settings.
- Note v2.1.5-rc3 was also tested in #17220 
![image](https://user-images.githubusercontent.com/45179589/50613875-55484f00-0e9c-11e9-9d5a-28203c97585f.png)
