### ISSUE TITLE
Dynamically pick  K8S default version picking for AKS/GKE/EKS to be most recent

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#15592]
Right now, we just hard code the version we preselect for EKS, AKS, and GKE.
We recently updated AKS from 1.8.x to 1.11.x, but not the other providers.
Ideally, we would make this version picking dynamic, but for v2.1 we should at least update the default version for the other providers.

**Comment by cjellick** [comment]
@westlywright as a small, quick fix, can you make the same update to GKE and EKS that you made to AKS? Change the default in the UI to the most recent version that the provider has

**Comment by westlywright** [comment]
`amazonElasticContainerServiceConfig` does not have a k8s version parameter
`googleKubernetesEngineConfig` uses the data we fetch from `/meta/gkeVersions`

**Comment by tfiduccia** [comment]
Version - v2.2.2-rc2
Verified fixed
