### ISSUE TITLE
Containers running in Rancher only see 1 CPU core (instead of all of them)

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#15599]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.21
rancher/agent or rancher/rancher-agent: 

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.8
ipsec: rancher/net:v0.13.17 
network-services: rancher/metadata:v0.10.4 and rancher/network-manager:v0.7.22
scheduler: rancher/scheduler:v0.8.5
kubernetes (if applicable): 

**Docker version: (`docker version`,`docker info` preferred)** 18.06.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 18.04LTS (Ubuntu 16.04LTS affected too)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1. Run a container with openjdk:11 image via a Rancher service,
2. log into shell and run:

```
cd /docker-java-home
root@6499aeaf786e:/docker-java-home# echo 'Runtime.getRuntime().availableProcessors()' | bin/jshell -q
jshell> Runtime.getRuntime().availableProcessors()
$1 ==> 1
jshell> root@6499aeaf786e:/docker-java-home#
```
It only detects a single CPU core (although the machine has 6 cores / 12 threads).

When running the same container on the same machine via command-line:
```
docker run -it openjdk:11 /bin/bash
root@2cb0cf9c57f5:/# echo 'Runtime.getRuntime().availableProcessors()' | bin/jshell -q
Sep 14, 2018 8:34:30 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
jshell> Runtime.getRuntime().availableProcessors()
$1 ==> 12
```

**Results:**

When running a container within Rancher, the number of CPUs assigned to the container is wrongly detected. I just hope this is a detection problem (and not really limiting the CPU to a single core).

**Comment by jloisel** [comment]
I think this is pretty critical since it screws any containerized java application that depends on the processor count running on Rancher v1.6.x.

**Comment by zeldigas** [comment]
The problem is that rancher sets cpu_shares for some reason to non-standard value - 2. That mislead jvm code that tries to calculate limits in cgroups.
Here is a java run with enabled tracing in rancher container:
```
java -Xlog:os*=trace Scratch
[0.001s][trace][os,container] OSContainer::init: Initializing Container Support
[0.001s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[0.001s][trace][os,container] Memory Limit is: 524288000
[0.001s][trace][os          ] active_processor_count: using static path - configured processors: 8
[0.001s][trace][os          ] active_processor_count: sched_getaffinity processor count: 8
[0.001s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
[0.001s][trace][os,container] CPU Quota is: -1
[0.001s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us
[0.001s][trace][os,container] CPU Period is: 100000
[0.001s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu,cpuacct/cpu.shares
[0.001s][trace][os,container] CPU Shares is: 2
[0.001s][trace][os,container] CPU Share count based on shares: 1
```
If I run jvm using vanilla docker, then output is different:
```
java -Xlog:os*=trace Scratch
[0.000s][trace][os,container] OSContainer::init: Initializing Container Support
[0.001s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[0.001s][trace][os,container] Memory Limit is: 9223372036854771712
[0.001s][trace][os,container] Memory Limit is: Unlimited
[0.001s][trace][os          ] active_processor_count: using static path - configured processors: 8
[0.001s][trace][os          ] active_processor_count: sched_getaffinity processor count: 8
[0.001s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
[0.001s][trace][os,container] CPU Quota is: -1
[0.001s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us
[0.001s][trace][os,container] CPU Period is: 100000
[0.001s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu,cpuacct/cpu.shares
[0.001s][trace][os,container] CPU Shares is: 1024
[0.001s][trace][os,container] OSContainer::active_processor_count: 8
```

For reference here is a cpp file from openjdk that does all calculations: https://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/hotspot/os/linux/osContainer_linux.cpp#l535

**Comment by zeldigas** [comment]
UPD: here's excerpt from referred cpp file. It shows special treat of 1024 value that is default in regular docker runs, but not in rancher
```
int OSContainer::cpu_shares() {
  GET_CONTAINER_INFO(int, cpu, "/cpu.shares",
                     "CPU Shares is: %d", "%d", shares);
  // Convert 1024 to no shares setup
  if (shares == 1024) return -1;

  return shares;
}
```

**Comment by mveroone** [comment]
So does applying `cpuShares: 1024` to services solves the issue ?

**Comment by zeldigas** [comment]
yes, this is one of the options. you can put cpu_shares: 1024 into docker compose to let jvm to fallback to default behaviour of full processors/cores utilization. In case you want to explicitly set quotas, you can go with reservations parameter in rancher-compose

**Comment by vincent99** [comment]
I don't know where the 2 is coming from (UI, API defaults, backend or agent on the host) or why we're (apparently) sending any value at all by default.

But the behavior in that code does not seem to match Docker at all.  Cpu-shares is a _relative_ number which only has meaning when compared to the sum of the rest of the containers on that host (i.e. If a container with two shares is the only thing running, that's _all_ the shares).  And it doesn't limit how many physical cores are available to the container regardless (that's cpuset).  And there is nothing special about 1024, other than it happening to be the default; it doesn't mean shares are not in use.

**Comment by zeldigas** [comment]
In fact reservations in rancher 1.6 affect shares that jvm find in cgroup files. When I set them to 4000 (` milli_cpu_reservation: 4000`), jvm finds 4096 and produce 4 cores to be used:
```
# execute shell from rancher console 
# cat /sys/fs/cgroup/cpu,cpuacct/cpu.shares
4096
```
Jvm logs
```
1/30/2019 7:58:34 PMCPU Shares is: 4096
1/30/2019 7:58:34 PMCPU Share count based on shares: 4
```

**Comment by 4admin2root** [comment]
the same issue in rancher v2.1.5

docker inspect result as follow:
            "Isolation": "",
            "CpuShares": 2,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "/kubepods/besteffort/podc7c25f30-5047-11e9-be14-0609ce0001b8",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
=======
with docker image: openjdk:8u181-jdk-alpine , availableProcessors is 1

with docker image: openjdk:8u181-jdk , availableProcessors is 8 (expected)

**Comment by deniseschannon** [comment]
@4admin2root Rancher v2.x is completely different from v1.6.x. Please file a different bug for 2.x. 

With the release of Rancher 2.0, development on v1.6 is very limited.

**Comment by vincent99** [comment]
The cores are there.  What Java chooses to do math on is up to them, shares are an entirely relative number that is meaningless in its own without knowing the total.
