### ISSUE TITLE
Creating a (stack) loadbalancer fails: Validation failed in API: stackId

### ISSUE THREAD

**Issue by sojwil** [rancher/rancher#15596]
Hi!
When creating a loadbalancer within a stack (using a selector rule), it fails with the error: "Validation failed in API: stackId". 
- I customized the default registry to an azure registry. 
- The HAproxy setting is changed to hold the full path, e.g. "lb.instance.image=docker.io/rancher/lb-service-haproxy:v0.9.3"

Any help would be great!

Regards, 
Jos

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.21` Cattle: `v0.183.60` UI: `v1.6.45` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.new-balancer`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
