### ISSUE TITLE
Add Load Balancer going to listeners tab and doesn't show stickiness until I click on it

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1559]
v0.28.0-rc1

Comments:  Somehow I got to http://104.197.36.149:8080/static/apps/add-balancer?environmentId=1e1&tab=listeners when trying to add a load balancer.  I can't reproduce it and it just randomly shows up on add.

Can we please remove all references to listeners so this is not a problem?

**Comment by tfiduccia** [comment]
this seems to happen when I add LB from the main stack page and not the details page.

**Comment by deniseschannon** [comment]
This is a duplicate of https://github.com/rancher/rancher/issues/1524, but I'll close my issue.

**Comment by tfiduccia** [comment]
v0.29.0-rc1 - verified fixed
