### ISSUE TITLE
Expose AWS EC2 Keypair in Node Template UI

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#15606]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.7

It would be very useful to expose the keypair name in the Node Template UI for AWS Nodes. Even better would be to allow using of existing, or generating a new SSH key.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/16798

**Comment by jmmckenz** [comment]
> Close in favor of #16798

16798 was closed in favor of #34729, which only addressed the duplicate Rancher generated keys.  The need for using existing keypairs in AWS is still needed (and/or exposing UserData to allow for cloudconfig)
