### ISSUE TITLE
Helm catalog can not be disabled

### ISSUE THREAD

**Issue by rdissauer** [rancher/rancher#15600]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent: v2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.11.1

**Docker version: (`docker version`,`docker info` preferred)**
17.3.2
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancheros v1.0.4
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Proxmox 5.2
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher from Helm Chart
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- Go to Global->Catalog and disable Helm Stable catalog, leave Library enabled
- go to a project of any cluster and launch a new app from catalog

**Results:**
- helm charts are still displayed in the catalog

<img width="1284" alt="grafik" src="https://user-images.githubusercontent.com/1752433/45542187-639d2d00-b811-11e8-99e6-7bf879ac1348.png">

**Comment by erikwilson** [comment]
This is should be fixed as part of rancher/rancher/issues/14322 PR (https://github.com/rancher/rancher/pull/17596).

The bug is triggered by disabling a catalog while it is updating. 

We now have checks in place if the catalog is removed to stop the update process, and also find templates with are not associated with a catalog and remove them on startup.

**Comment by erikwilson** [comment]
To test this change it is best to start with Rancher server v2.1.6:
- Enable the Helm catalog, while it is updating disable the catalog - repeat a few times
- Verify on the catalog apps page the existence of available Helm templates even though the catalog is disabled

Upgrade to Rancher master:
- CatalogTemplates and CatalogTemplateVersions not associated with a catalog will be automatically removed
- Verify on the catalog apps page that Helm templates are no longer available
- Enable the Helm catalog, while it is updating disable the catalog - repeat a few times
- Verify on the catalog apps page that no Helm templates are available

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/25

* Reproduced original issue
* Enabled helm stable catalog, disabled while updating, enabled, disabled while updating
* There were no catalog apps from the Helm repository left over
