### ISSUE TITLE
Docs for Helm need instruction to force reset helm config

### ISSUE THREAD

**Issue by longwuyuan** [rancher/rancher#15603]
**Rancher versions:**
rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.11.2

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu, RancherOS or CentOS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Any
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
```
- Do not follow docs and do a "helm init"
- Come around to following docs https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-init/
- Try to run ` helm ls` after following steps in the doc

```
**Results:**
helm ls fails
helm install fails

** Expected **
This Doc  https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-init/   could note that helm init should not have been run on the cluster prior to following the doc. If helm init was already run, then helm config has to be force reset before following doc again ;
```
helm reset --force

```

**Comment by superseb** [comment]
This is a follow up on https://github.com/rancher/rancher/issues/15597 and docs are being added at the moment.
