### ISSUE TITLE
Add Services button is white on main stack page but blue in details page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1560]
v0.28.0-rc1
Steps:
1.  go to main stack page
2.  Go to details page for a stack

Results;
notice the button is white on one page and blue on the other.

Expected:
Should probably be blue in both, but we should be consistent with our Add buttons across the application.

**Comment by vincent99** [comment]
This is (intended to be) a feature... each page has one primary blue action at the top
