### ISSUE TITLE
Editing Node Template Does Not Retain Provider API Keys

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#15608]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

## Actual Behavior

When editing a node template for AWS EC2 the UI expects the AWS Keys to be given again.

## Expected Behavior

I would expect that since Rancher is retaining the information to be able to bring up nodes that it would retain the secret key during editing. This would make editing more smooth.

**Comment by JasonvanBrackel** [comment]
Edited the title as this behavior is consistent across vendors

**Comment by vincent99** [comment]
The UI makes API calls to the provider to get the options (regions, subnets, security groups, etc) to show you and needs the keys to do it.  We don't want the API to just cough up stored keys in plaintext on request, so you need to provide them again on edit.

**Comment by ekristen** [comment]
I agree about coughing up the API keys, however I don't think this should have been closed so quickly.

There are other options.

For example, calling the API endpoints that talk to AWS can know that the secret key is known and not required it be passed in and use what's in the database and display in the UI that it will use the credentials that are stored, unless you choose to change it.

**Comment by JasonvanBrackel** [comment]
@vincent99 we have customers asking for this as well. I'm reopening @deniseschannon this is on your tracking sheet wontfix is not good enough

**Comment by ekristen** [comment]
Personally I wasn't suggesting incorporating every SDK in, but the API has to be storing the keys because since the pools can be created and scaled without re-supplying the keys.

Base on that knowledge alone I was thinking that the R2 APIs that allow for editing of the templates that are also used to retrieve AWS information could use whats already stored when calling any provider endpoints. Then again I don't know how it's implemented from a technical standpoint.

Thanks!

**Comment by deniseschannon** [comment]
With the introduction of cloud credentials in 2.2, this issue is resolved. When editing a node template, it will re-use the cloud credential that is stored.
