### ISSUE TITLE
Upgrading Doesn't Update K8s Version in Rancher GUI

### ISSUE THREAD

**Issue by john-mcgowan-wowza** [rancher/rancher#15605]
I've done this multiple times now.   I've had two clusters that where originally provisioned with k8s v 1.10.5, and I have done an upgrade to 1.11.2 using the Rancher GUI.  Both times, there have been some of the nodes that did not show up as having the new version in the rancher GUI.

In both cases, if I do a 

`kubectl get nodes`

on the cluster all the nodes are reporting as having been upgraded successfully.

the nodes are "custom" and it this particular case they are running latest rancheros.  They were provisioned via terraform and registered and from what I can tell there are no other errors or problems with the cluster other than not showing the correct version of K8s in the rancher GUI.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
Can you share more info how to reproduce? Did this happen on a v2.0.8 from scratch or was it upgraded? Is it single/HA install? How many nodes were there in the cluster, what nodes were not showing the upgraded version? Is there a relation on the nodes not showing the correct version? Does it not show the correct version in the `Nodes` view and also in the detailed view of a node?

**Comment by john-mcgowan-wowza** [comment]
@superseb 

These are all happening on a very fresh install of rancher from rancher-stable just a couple days ago.

Rancher itself is an HA install on a rke managed cluster with rancheros.


Incident One: 5 total nodes, 3 master 2 worker
I did the upgrade from 1.10 to 1.11 and  one of the masters showed the new version, both workers showed the new version, but two of the masters did not.  Did a lot of messing around there and Chris Kim from Rancher actually logged in and messed with it a little.

When we did a `shutdown r now` on the servers that were still not showing the latest version, they showed the proper version once they came back up.

Incident Two:  5 total nodes, 3 master 2 worker
Same scenario as before, going from 1.10 to 1.11, however this time the results were a little different.

Shortly after the upgrade, `kubectl get nodes` shows all servers running 1.11, however the GUI is only showing 1 of the masters as having 1.11.  the other 4 servers are showing 1.10.

Then I left it alone overnight... didn't touch anything.  And now 1 master and 1 worker are showing 1.11 and the other three servers are showing 1.10.

I still haven't touched anything with that cluster

In all cases, the detailed view and the nodes list overview values are showing the same infomation.  So on the incorrect servers that don't match what shows up in `kubectl` it's consistently wrong in the rancher GUI

**Comment by john-mcgowan-wowza** [comment]
@superseb Did I provide enough info for you on this?

**Comment by superseb** [comment]
We have reported issues on this here https://github.com/rancher/rancher/issues/15830 and here https://github.com/rancher/rancher/issues/15831 which should also cover your situation.

Let me know if you don't think they are the same.

**Comment by john-mcgowan-wowza** [comment]
They could be, but I'm not sure they are the same issue @superseb .  My issue has nothing to do with upgrading rancher itself, and it seems like both of those issues discuss going from one version of rancher to the next and then doing an upgrade.  But I could be wrong.  So maybe they all are the same situation.

it's possible that with #15830 and #15831  the rancher upgrade is a red herring.
