### ISSUE TITLE
Move button in UI changes to "Saving" and stays spinning when a namespace is moved from a project without resource quota to a project with resource quota

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15612]
**Rancher versions:**
rancher/server or rancher/rancher: Master

**Steps to Reproduce:**
1. Create a project "P1" without any resource quota assigned and create a namespace "N1" in P1
2. Create a project P2 with resource quota assigned.
3. Move N1 to project P2

An error pops up that move is not allowed as expected. But the move button changes to "Saving" and stays spinning as below.
<img width="1122" alt="screen shot 2018-09-14 at 11 34 22 am" src="https://user-images.githubusercontent.com/18536626/45568702-2be2b500-b812-11e8-8152-822be85c34e2.png">

Also, can the error displayed in red on the side be changed to something better ?

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/17
Saving fixed.
