### ISSUE TITLE
"Edit User" page for a user created with "Standard User" permission shows "custom" permission with no options enabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15614]
Rancher versions:  rancher server build from master

Steps to reproduce the problem:
Create a user with "Standard User" permission
Once user is created, choose "Edit" option.

Edit User" page for a user created with "Standard User" permission shows "custom" with "Login Access" enabled.

<img width="1298" alt="screen shot 2018-09-14 at 11 51 37 am" src="https://user-images.githubusercontent.com/4266958/45569501-8e3cb500-b814-11e8-980d-fc5dcdf3dc19.png">

**Comment by loganhz** [comment]
@sangeethah 

I guess your created a `Standard User` by an `Admin` account and tried to edit the `Standard User` user by a `Standard User` account.

This is expected as `/v3/globalRole?limit=-1&sort=name` returns empty array for a `Standard User` account.

Standard User will not be able to see the global menus once we have dynamic schema working in backend.

**Comment by cjellick** [comment]
Sending back to @sangeethah to confirm that what @loganhz described is what happened. If so, please close @sangeethah

**Comment by sangeethah** [comment]
@loganhz , yes . This is the case of creating a Standard User as an Admin account and then trying to edit the Standard User when logged in as this user.
