### ISSUE TITLE
Upgrade etcd versions in Rancher provisioned clusters based on new min. pub. guidelines

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#15618]
Kubernetes and etcd have new minimum recommended versions for production clusters:
https://discuss.kubernetes.io/t/recommended-etcd-minimum-versions-3-1-11-3-2-10-3-3-0/2637

We will need to provide an upgrade path for users to reach the new recommended minimums.

**Comment by deniseschannon** [comment]
The latest versions in the latest Rancher release (v2.2.1) follows the recommended etcd versions for k8s versions supported in the release.

All users should upgrade to the latest k8s versions.
