### ISSUE TITLE
Show errors when using loglevel and add general info on usage

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15627]
Version: master 9/16

**Steps to Reproduce:**
1. Run `loglevel --set debuga`

1. Run `loglevel --help`

**Results:**
No response while it is an invalid loglevel.

```
NAME:
   loglevel - A new cli application

USAGE:
   loglevel [global options] command [command options] [arguments...]

VERSION:
   0.0.0
```

**Comment by cjellick** [comment]
loglevel pr merged @deniseschannon or @superseb remind me to update rancher with the new version on monday!

**Comment by cjellick** [comment]
@dramich to validate

**Comment by dramich** [comment]
Validated on v2.2.0-alpha6

Steps:
Setup HA install following docs except set image tag to v2.2.0-alpha6
Exec into rancher container
Run `loglevel -h` and validate usage info
Run `loglevel --set aaa` and error is returned: 
`Error when setting loglevel: invalid log level specified (aaa)`
Confirm loglevel is still changed as expected
