### ISSUE TITLE
Service linking causes "privileged" flag to always be false

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1562]
Rancher Server: v0.25.0-rc2

If I have a docker-compose.yml with:

service1:
  ...
 
service2:
  ...
  privileged: true
  links:
  -service1:service1

If I start this, service2 will never get its privileged flag set to "true".  If I remove the link, it will work as expected. 

To reproduce this, the start order must be service1, then service2 (which is what would happen if you do a "Start all Services").  However, if I reverse the order and start service2, then service1, the privileged flag is set correctly to true.

**Comment by alena1108** [comment]
Tested on the latest Rancher/Rancher-compose, can't reproduce. Following template was used: 

service1:
  image: ubuntu:latest
  stdinOpen: true
  tty: true
  privileged: true

service2:
  image: ubuntu:latest
  stdinOpen: true
  tty: true
  privileged: true
  links:
    - service1:service1

Worked as expected, both links and privileged=true were set for service2
