### ISSUE TITLE
kubectl shell, container log and container shell is unavailable for imported cluster

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#15626]
**Rancher versions:** 2.0.8
exsiting kubernetes cluster version: 1.11.3

Hi,

I have a on-premise kubernetes cluster with version 1.11.3, and I imported it to Rancher v2.0.8, I can successfully create workloads with Rancher, and I can edit any resources like configmap, secret too, but I can't use kubectl shell, container log and container shell, they are stuck at "connecting":
![image](https://user-images.githubusercontent.com/15604715/45592525-75faa080-b9a2-11e8-947f-8b61d601bf9a.png)

![image](https://user-images.githubusercontent.com/15604715/45592527-8dd22480-b9a2-11e8-8df6-4157096f226b.png)

![image](https://user-images.githubusercontent.com/15604715/45592529-a8a49900-b9a2-11e8-9400-0b3d8cda5959.png)

And one more question, when creating the clusterrolebinding before import kubernetes cluster, there's a --user parameter, what does this "user" mean? Which user shall I use?
```
kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user [USER_ACCOUNT]
```

Thanks for the help.

**Comment by superseb** [comment]
How did you create the cluster (what tool or tutorial)?

The kubectl shell is looking up pods in the `cattle-system` namespace with label `app=cattle-agent`, can you show the output of `kubectl get pods -n cattle-system -l app=cattle-agent`? Can you also check what the developers tools in your browser replies when opening the shell?

Cluster without `cluster-admin` require a rolebinding to successfully run the resources needed to import the cluster. For instance on GKE, this is your account email address.

**Comment by hiscal2015** [comment]
@superseb 

I followed the guide below to create the cluster:
https://github.com/kelseyhightower/kubernetes-the-hard-way

```
# kubectl get pods -n cattle-system -l app=cattle-agent
NAME                      READY     STATUS    RESTARTS   AGE
cattle-node-agent-6w6xk   1/1       Running   0          8h
cattle-node-agent-h42lj   1/1       Running   0          8h
cattle-node-agent-n7cdc   1/1       Running   0          8h
```
browser replies:
![image](https://user-images.githubusercontent.com/15604715/45596194-bf6ede00-b9ea-11e8-9e54-7b76c37799c0.png)

**Comment by superseb** [comment]
Can you show `kube-apiserver` logging, and `kubelet` logging on the 3 nodes when you open the shell in the UI?

**Comment by loganhz** [comment]
Can you provide the related logs, please?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
