### ISSUE TITLE
syslog tcp logging truncated in syslog-ng

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#15631]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7

**Infrastructure Stack versions:**
kubernetes: v1.10.1

**Steps to Reproduce:**
1. enable tcp logging for syslog

note: udp configuration works, but is lossy and truncates log lines.

**Results:**
rancher server logs:
```
2018/09/16 17:20:58 [ERROR] ClusterLoggingController local/cl-svdn6 [cluster-logging-controller] failed with : Operation cannot be fulfilled on clusterloggings.management.cattle.io "cl-svdn6": the object has been modified; please apply your changes to the latest version and try again
2018/09/16 17:25:23 [WARNING] clusterlogging local:cl-svdn6 input validate failed, url 172.31.34.25:514 unreachable, error: dial tcp 172.31.34.25:514: i/o timeout
```

**Comment by aiwantaozi** [comment]
Debug with ahmad rancher os may have some compatibility issue will cluster created by rke, could not find log under /var/log/containers. And get some error like summary.go:92] Failed to get system container stats for /docker/xxxxx/docker/xxxx

**Comment by aiwantaozi** [comment]
After communicate with ahamad, long log ship to syslog-ng is truncated

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc8

* Created syslog-ng server
* Enabled logging to syslog-ng target
* Added custom log field with 2000+ character value (total of 3000 characters in log statement)

Log statement was not truncated during transport.
