### ISSUE TITLE
GenerateKubeconfig returns different ca cert to the one from created from gui

### ISSUE THREAD

**Issue by bartwalczak1** [rancher/rancher#15637]
Please let me know what sort of info is required for this 

I run:
https://rancher.eng.cloud.xxx.com/v3/clusters/c-b7qxt?action=generateKubeconfig
which according to https://github.com/rancher/rancher/pull/12172/commits/5fdca62e0e46387bed1ca8c7480339653f3046a1
should generate kubeconfig. 
Output is in json with some extra keys, but can be easily parsed and output into yaml. After pasting values for kube config, kubectl fails with:
`x509 certificate signed by unknown authority`
After comparing both certs they seem to be different...

Kube config generated via gui works!

Is there anything I'm missing? 

Thanks
-B

**Comment by vincent99** [comment]
The UI is just an API client, it has no secret knowledge or permission.  It makes the [same action request](
https://github.com/rancher/ui/blob/759500aeef9eec9169918b1eb02c329bbb905515/app/components/modal-kubeconfig/component.js#L25) and [displays](
https://github.com/rancher/ui/blob/759500aeef9eec9169918b1eb02c329bbb905515/app/components/modal-kubeconfig/template.hbs#L7) the [config field](
https://github.com/rancher/ui/blob/759500aeef9eec9169918b1eb02c329bbb905515/app/components/modal-kubeconfig/component.js#L27) of the response.

**Comment by bartwalczak1** [comment]
ok so turns out this should be POST instead of GET, which I think should be changed to GET since we are only retrieving data from rancher.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
