### ISSUE TITLE
Checkboxes are missing for Namespaces but bulk actions still exist

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15646]
**Rancher versions:** 2.1 master 9/17

**Steps to Reproduce:**
1.  Go to Project/Namespaces page

**Results:**  Checkboxes are missing but bulk actions are still there.
![image](https://user-images.githubusercontent.com/11514927/45640727-401fef80-ba68-11e8-856e-67f3f8d1bdda.png)

**Comment by cjellick** [comment]
@westlywright I think you missed assigning this to tani

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/19
Verified fixed
