### ISSUE TITLE
Implement default cpu/memory limit for workloads in a namespace

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15648]
When cpu/memory request/limits quota is defined on a namespace, every workload in a namespace has to have cpu/memory requests/limits set. Have to add a way of providing defaults on a namespace that can be used along with the resource limits, so unless user manually enters the custom limits, they should be defaulted to this value. Would have to leverage limitRange object on k8s side to support that.

**Comment by soumyalj** [comment]
Tested with master build from Feb 20. The feature of providing default cpu/memory limit for workloads in a namespace is functional. Few of the use cases tested were: 
1. Create project with resource quota, default namespace quota and default container limits defined in the UI.
2. Create workload without defining the container limits. The pod inherited the default container limits defined in step 1. It was verified in the API at the pod level.
3. Create a pod and override the default container limits .
