### ISSUE TITLE
Linking containers sometimes results in malformed env vars

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#1564]
Rancher	v0.28.0
Cattle	v0.64.0
User Interface	v0.34.0
Rancher Compose	beta/latest

Obviously these should be prefixed with "REDIS_"

```
declare -x _ENV_REDIS_DOWNLOAD_SHA1="a38755fe9a669896f7c5d8cd3ebbf76d59712002"  
declare -x _ENV_REDIS_DOWNLOAD_URL="http://download.redis.io/releases/redis-3.0.
2.tar.gz"                                                                       
declare -x _ENV_REDIS_VERSION="3.0.2"                                           
declare -x _NAME="/cattle/"                                                     
declare -x _PORT="tcp://:6379"                                                  
declare -x _PORT_6379_TCP="tcp://:6379"                                         
declare -x _PORT_6379_TCP_ADDR=""                                               
declare -x _PORT_6379_TCP_PORT="6379"                                           
declare -x _PORT_6379_TCP_PROTO="tcp" 
```

**Comment by ibuildthecloud** [comment]
Oh, that's bad.  It's because the service name is being read wrong.  @alena1108 Did we recently change something such that the service link name would be located in a different spot or possible null?

**Comment by ibuildthecloud** [comment]
@willseward Could you share your compose template?  You can export the config in the Apps->Stacks view in the UI.

**Comment by alena1108** [comment]
@ibuildthecloud not sure if thats what resulted in changed behavior, but setServiceLink APIs has been changed in the latest release. Now it accepts a list of objects of type
{
name (linkName, optional),
serviceId (required)
}

And - it was always the case - if name is not set, serviceLink ends up having NULL name, and we read the DNS name from the serviceLink.consumingService name (I specifically don't set the link name in this scenario as consuming service's name can change). We probably have to implement the same kind of logic when we form instance links, although consuming service name change won't trigger environment variables change.

**Comment by willseward** [comment]
That makes a lot of sense @alena1108. When I recreate the service and fill in the link names, everything works fine.

**Comment by sangeethah** [comment]
Tested with server version - V0.30.0-rc1

Created service links with name.
Environment variables get created with the service name.
