### ISSUE TITLE
Unsupported value is displayed in UI after editing projectquota until the browser is refreshed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15647]
Tested with v2.1.0-rc1. 

1. Create a project with resource quota {pods=20} and default namespace quota as 5
2. Create three namespaces with default resource quota
3. Edit the project resource quota to 12 (below the consumed resource quota of 15) 
Reducing the resourcequota at the project level below the namespace resource quota errors out as expected.
Example below, the usedLimit is 15 and the project resourcequota is 20.

namespaceDefaultResourceQuota": {
"limit": {
"pods": "5",
"type": "/v3/schemas/resourceQuotaLimit"
},
"type": "/v3/schemas/namespaceResourceQuota"
},
"namespaceId": null,
"podSecurityPolicyTemplateId": "",
"resourceQuota": {
"limit": {
"pods": "20",
"type": "/v3/schemas/resourceQuotaLimit"
},
"type": "/v3/schemas/projectResourceQuota",
"usedLimit": {
"pods": "15",
"type": "/v3/schemas/resourceQuotaLimit"
}
},
Edited the project resourcequota to 12 and the below error message was displayed.
<img width="1282" alt="screen shot 2018-09-17 at 11 00 19 am" src="https://user-images.githubusercontent.com/18536626/45642011-e3263880-ba6b-11e8-9e9e-755fe6349900.png">

Hit cancel and edit the projectquota again right after the above error is displayed. 
The reduced value(12) in is displayed in the UI until the browser is refreshed. 
<img width="1287" alt="screen shot 2018-09-17 at 11 41 02 am" src="https://user-images.githubusercontent.com/18536626/45642921-9728c300-ba6e-11e8-9209-a4d446f17719.png">

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/18
Verified fixed
