### ISSUE TITLE
Add text `If your cloud provider is not listed, please use the Custom option`. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#15652]
Since `Custom` shows an additional message with links to the Rancher docs on how to configure cloud providers, we should indicate that they should be using custom if they don't see their cloud provider listed. 

<img width="509" alt="screen shot 2018-09-17 at 1 43 23 pm" src="https://user-images.githubusercontent.com/11410997/45649545-749fa580-ba80-11e8-86e6-c637fb22cf2f.png">

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/20
Verified fixed
