### ISSUE TITLE
UI support for pipeline notification config

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#15666]
Related backend issue: https://github.com/rancher/rancher/issues/15665

When users edit pipeline via UI, In advanced configurations there's a notification section.
Users can choose one or multiple notifiers from the notifiers list of the cluster.
Users can choose trigger conditions, e.g., notify when the result is "Failed", "Success" or "Changed"
Users can set notification messages. Pipeline variables are available.

**Comment by loganhz** [comment]
It will be verified with https://github.com/rancher/rancher/issues/15665
