### ISSUE TITLE
Rancher doesn't re-download node driver binaries after upgrade.

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#15661]
**Rancher versions:**
rancher/rancher: master

Machine driver is not re-downloaded if rancher server is upgraded. 
```
2018/09/17 23:52:59 [ERROR] NodeDriverController aliyunecs [node-driver-controller] failed with : Driver "aliyunecs" not found. Do you have the plugin binary accessible in your PATH?
```

**Steps to Reproduce:**
1. Active aliyunecs node driver.
2. Upgrade Rancher Server.
3. The error above shows up.

**Results:**
The node driver binary should be re-downloaded.

**Comment by cjellick** [comment]
@nathan-jenan-rancher to validate

**Comment by nathan-jenan-rancher** [comment]
Steps:
1. Started rancher v2.0.8 instance
2. activated Aliyun ECS node driver
3. upgraded Rancher according to docs to `rancher:rancher/master`
4. started rancher
5. confirmed no error appears on UI or in logs related to node driver
