### ISSUE TITLE
[Documentation] Docker support

### ISSUE THREAD

**Issue by Coopyrightdmin** [rancher/rancher#15668]
Hello,
[this page](https://rancher.com/docs/rancher/v2.x/en/installation/requirements/) refers Docker 17.03.2 as the latest supported docker version. Doesn't Rancher supports the latest stable docker version - 18.03 for instance?

**Comment by superseb** [comment]
We follow the Kubernetes validated versions, see https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-are-the-supported-docker-versions-determined
