### ISSUE TITLE
can rancher 2.0 use Traefik instead of ingress as default load balancer?

### ISSUE THREAD

**Issue by imwower** [rancher/rancher#15669]
It seems that, the ingress controller does not support tcp/udp traffic,
here is the Traefik link:
[https://github.com/containous/traefik](https://github.com/containous/traefik)

**Comment by superseb** [comment]
Alternatives to the default NGINX ingress controller is covered here https://github.com/rancher/rancher/issues/14007. You are free to disable the built-in ingress controller and deploy your own, the built-in one is tested and supported.
