### ISSUE TITLE
Rancher CLI Unable to Upgrade Stack Through Jenkins CI/CD

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rancher#15675]
**Rancher versions:**
rancher/server: **v1.6.17**

**Type/provider of hosts:**
Azure

**Setup details:**
High Availability with external database configured through Azure

**Steps to Reproduce:**

Create a Jenkins job that uses rancher cli to upgrade a stack in rancher 1.6.17.
```
rancher --debug --env $environment_name up --stack ${catalog_name} \
  --force-upgrade -env-file ${answers_file_name} --rancher-file $rancher_compose_file \
  --file $docker_compose_file --pull  --interval "600000"  -d liquibase-all
```

**Results:**
```
time="2018-09-04T23:23:35-04:00" level=error msg="Failed Starting pbs-renderer : Post http://$host/v2-beta/projects/1a808/scripts/transform: EOF"
time="2018-09-04T23:23:35-04:00" level=error msg="Failed to start: pbs-renderer : Post http://$host/v2-beta/projects/1a808/scripts/transform: EOF"
time="2018-09-04T23:23:35-04:00" level=fatal msg="Post http://$host/v2-beta/projects/1a808/scripts/transform: EOF"
```

I could only post a portion of the upgrade script due to privacy and security concerns. The stack has multiples services that are upgraded one by one in the Jenkins job. Also there is a HAProxy load balancer in front of Rancher.

This is a blocker because Jenkins is unable to upgrade the stack for each of the environments in use. Dev, QA, Staging, Production and etc. From the UI you can click on upgrade and the stack gets upgraded. Through rancher cli being executed from Jenkins, the stack fails to finish the upgrade.

**Comment by dramich** [comment]
Needs additional info from user on how to reproduce the issue.

**Comment by alena1108** [comment]
Moving out as we need more info from the user on how to reproduce cc @deniseschannon
