### ISSUE TITLE
Rancher 2.0 Error creating EKS cluster under EU-WEST-1

### ISSUE THREAD

**Issue by rsilvestre** [rancher/rancher#15670]
**Rancher versions:**
rancher/server or rancher/rancher:

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.x

**Steps to Reproduce:**
Create a new Cluster AWS EKS
Select EU-WEST-1
Fill the form
Standard: Rancher generated service role
Create a new VPC
Select Nodes T3.medium

**Results:**
Under AWS Console:
It create c-dr22x cluster

Get this error in rancher
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Error creating cluster: 409 {"clusterName":"c-dr22x","message":"Cluster already exists with name: c-dr22x"}
```

**Comment by superseb** [comment]
Support for EKS in eu-west is covered in https://github.com/rancher/rancher/issues/15484, and is has not been verified/released. The 409 error is covered here https://github.com/rancher/rancher/issues/15205
