### ISSUE TITLE
Can have negative numbers in project/namespace quotas

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15673]
**Rancher versions:** 2.1 master 9/17

**Steps to Reproduce:**
1.  Enter -1 as a project or namespace quota

**Results:**  We allow negative numbers.  Which end up just being ignored.  If I have 8 as a pod quota for project and -1 as namespace.  I can put 8 pods on the namespace.  Maybe we shouldn't allow negative numbers.

**Comment by davidnuzik** [comment]
Version: master 2.2 (11/30/18)
Confirmed fixed. Cannot have negative numbers stay in the form. They will automatically change to zero. I halo tested to ensure I covered all the areas with resource limitations including in workloads (Security & Host Config section), etc. None of these resource limit/reservation forms allow negative numbers.
