### ISSUE TITLE
Ability to collect logs and other useful debug info from rancher server setup

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#15679]
- Change log level on the fly for services like kubelet. Today you have to delete the component and recreate it with extra_args to increase verbosity, at that point the issue could 'resolve' itself. Not sure if this is possible.
- rancher agents to log disk utilization, cpu utilization stats, free mem (say every 5 minutes) This would help detect memory leaks or resources starvation.

**Comment by alena1108** [comment]
> Change log level on the fly for services like kubelet. Today you have to delete the component and recreate it with extra_args to increase verbosity, at that point the issue could 'resolve' itself. Not sure if this is possible.

Log level is k8s component argument, and can't be applied w/o the restart. @moelsayed please confirm.

To summarize the initial requirements:

* Dump logs, on per cluster basis. System components we know are critical. Cgroup information (cgroup fs)
* Should be pluggable - a plugin on per k8s provider type (RKE, GKE) as rancher system components can vary.
* Run `log disk utilization, cpu utilization stats, free mem (say every 5 minutes) This would help detect memory leaks or resources starvation.` either as a part of rancher agent or a daemon set. The problem with the daemon set that it would be limited to rke clusters only.

**Comment by cjellick** [comment]
marking as p/1 for alpha1 purposes. it is not 1 p/0 for alpha1

**Comment by moelsayed** [comment]
@soumyalj This is currently implemented as the `logs` and `stats` commands in rancher/system-tools v0.1.1-rc1. To test, you should confirm that those commands work as expected. 

Notes:
- Changing component log level is not possible or supported. 
- Pulling logs currently only supports the main containerized components deployed by RKE
- Only RKE based clusters are currently supported.

**Comment by soumyalj** [comment]
Tested with system-tools version v0.1.1-rc1. 
Node stats are displayed on the terminal as below  :
```
soumyas-MacBook-Pro:systemtools soumya$ ./system-tools_darwin-amd64 stats --kubeconfig rkeconfig.yml 
INFO[0000] deploying stats collection DaemonSet [stats-collector].. 
INFO[0000] wating for DaemonSet [stats-collector] to be ready.. 
INFO[0000] stats collection DaemonSet [stats-collector] deployed successfully.. 
INFO[0000] node stats for [206.189.237.124]..           
INFO[0000] waiting for collector pod [cattle-system/stats-collector-djvpr] to be ready.. 


INFO[0005] node stats for [a.b.c.d]..           
INFO[0006] waiting for collector pod [cattle-system/stats-collector-djvpr] to be ready.. 


INFO[0011] node stats for [ab.c.d]..           
Linux 4.4.0-138-generic (stats-collector-djvpr) 	11/16/18 	_x86_64_	(2 CPU)

22:48:44        CPU     %user     %nice   %system   %iowait    %steal     %idle
22:48:45        all      2.00      0.00      4.50      0.00      0.00     93.50

22:48:44    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
22:48:45       203512   2806456   3842872     94.97     78552   2595336   5702756    140.93   1789704   1730172     24628

22:48:44     MBfsfree  MBfsused   %fsused  %ufsused     Ifree     Iused    %Iused FILESYSTEM
22:48:45        74972      4248      5.36      5.38  10187435    134485      1.30 /dev/vda1
22:48:45        74972      4248      5.36      5.38  10187435    134485      1.30 /dev/vda1
22:48:45        74972      4248      5.36      5.38  10187435    134485      1.30 /dev/vda1
22:48:45        74972      4248      5.36      5.38  10187435    134485      1.30 /dev/vda1

Average:        CPU     %user     %nice   %system   %iowait    %steal     %idle
Average:        all      2.00      0.00      4.50      0.00      0.00     93.50

Average:    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
Average:       203512   2806456   3842872     94.97     78552   2595336   5702756    140.93   1789704   1730172     24628

Summary:     MBfsfree  MBfsused   %fsused  %ufsused     Ifree     Iused    %Iused FILESYSTEM
Summary:        74972      4248      5.36      5.38  10187435    134485      1.30 /dev/vda1
Summary:        74972      4248      5.36      5.38  10187435    134485      1.30 /dev/vda1
Summary:        74972      4248      5.36      5.38  10187435    134485      1.30 /dev/vda1
Summary:        74972      4248      5.36      5.38  10187435    134485      1.30 /dev/vda1

```

Issue with log collection is filed https://github.com/rancher/rancher/issues/16609
