### ISSUE TITLE
Rancher 2.x go bindings miss dymanic drivers schema

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15685]
github.com/rancher/types is used as a go binding to talk to Rancher APIs. The bindings are static meaning that whatever dynamic schema components user enabled on a rancher server - like dynamic node driver - is not being included. That makes it hard to integrate for cases like RKE cluster provisioning where NodeTemplate/NodePool requires node driver schema presence.

Have to figure out the way to generate the go client for this case.

@rawmind0

**Comment by rawmind0** [comment]
terraform node template implementation dependent of this issue, https://github.com/rancher/rancher/issues/14729

**Comment by alena1108** [comment]
Followed up with @ibuildthecloud. For all dynamic schemas the generic client methods should be used instead of concrete ones:

https://github.com/rancher/norman/blob/master/clientbase/common.go#L331

The concrete interfaces can't be generated because there is no way in advance to figure out what drivers can be provided dynamically via pluggable interface in Rancher.

**Comment by alena1108** [comment]
@rawmind0 could you confirm that custom client way worked for you.

**Comment by rawmind0** [comment]
Sure @alena, confirmed it's working using generic client methods.

**Comment by deniseschannon** [comment]
As we are able to use the generic client methods, we are going to close this issue for now.
