### ISSUE TITLE
JFrog template fails to deploy when nginx persistence is chosen w/o ingress enabled

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15681]
Steps to reproduce:

* Choose jFrog template
* Set ` Expose app using Layer 7 Load Balancer` to false. Pick `L4 Balancer` as Nginx Service type
* Set `Enable Persistent Storage for Nginx Service` to true

![image](https://user-images.githubusercontent.com/1562176/45704536-01ec0400-bb2c-11e8-88ef-56850850f4bf.png)

Looks like it happens because this condition enables PVC creation only when ingress resource gets created:

https://github.com/rancher/charts/blob/master/charts/artifactory-ha/v0.2.2/templates/nginx-pvc.yaml#L1

We have to relax the rule and create a PVC whenever the persistence is chosen for nginx

**Comment by guangbochen** [comment]
@alena1108 the template issue in v0.2.2 is resolved and also added the latest version which will not have the issues mentioned above.

**Comment by loganhz** [comment]
@guangbochen Submitted a PR to fix it. Can you help to review it, please?

https://github.com/rancher/charts/pull/46

**Comment by guangbochen** [comment]
updated and merged, thanks.
