### ISSUE TITLE
Revise AKS kontainer-engine driver and add missing fields

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15697]
We need to get in line with what AKS has to offer in the latest version.
Most likely there will missing fields and stuff, and we have to go through AKS API and UI to see what's missing, and add it on our side

**Comment by sangeethah** [comment]
@thxCode Could you provide a list of new fields that are getting added ?

**Comment by thxCode** [comment]
@sangeethah , FYI, https://github.com/rancher/kontainer-engine/pull/107#issuecomment-452272906

**Comment by cjellick** [comment]
backend is in

**Comment by cjellick** [comment]
backend is in

**Comment by bmdepesa** [comment]
rancher/rancher:master

The following fields are functional in UI & backend:
* OS Disk size
* Enable ingress controller
* Enable Azure monitoring
* Enable network policy
* customize tags
* agent count
* kubernetes version

Currently blocked from closing by: #18027 to validate Azure AD integration

**Comment by thxCode** [comment]
I could not find the **Azure Active Directory** configuration from Azure UI, but found in `az aks create -h`: 
![image](https://user-images.githubusercontent.com/3394724/52679776-23cda380-2f71-11e9-8264-2ab47e547e31.png)

Here is a doc for the integration: https://docs.microsoft.com/en-us/azure/aks/aad-integration, but it seems so complicated.

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/18027

**Comment by sangeethah** [comment]
Azure AD integration is tracked in https://github.com/rancher/rancher/issues/18102
