### ISSUE TITLE
Edit namespace does not allow editing the resourcequota

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15690]
**Rancher versions:**
rancher/server or rancher/rancher: v2.1.0-rc2

**Steps to Reproduce:**
1. Create a cluster
2. Create project P1 with resource quota and default namespaceresourcequota
3. Create namespace N1
4. Edit namespace
The resourcequota field is greyed out. It cannot be edited
<img width="965" alt="screen shot 2018-09-18 at 1 03 01 pm" src="https://user-images.githubusercontent.com/18536626/45713189-34552b80-bb43-11e8-8844-3bc2f4af05a0.png">

The API displays the resorucequota for the namespace
```
"projectId": "c-hzvvh:p-bh4f8",
"resourceQuota": {
"limit": {
"pods": "5"
}
},

```
Editing namespace resource quota should be allowed

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/20
Verified fixed
