### ISSUE TITLE
Retrieve managed IP address from within the container

### ISSUE THREAD

**Issue by Kelindar** [rancher/rancher#1569]
Quick question: is there a way to get managed IP of the container (eg: 10.42.x.x) from within the container?

**Comment by ibuildthecloud** [comment]
Right now it's just by doing a 'ip addr show'.  We are looking at adding a meta data service similar to EC2 meta data so that you can do a simple get to get this information.  Would that work for you use case?

**Comment by Kelindar** [comment]
Yes, that's what I did yesterday. A bit ugly, but works fine:
```
ACCESS=$(ip addr show eth0 | awk '{print $2}' | grep -E -o "(10.*)" | cut -f1 -d'/')
```

My thinking exactly, a simpler HTTP metadata service would be much nicer. I've setup aerospike yesterday and it needed to broadcast it's access ip. I'll try write up an article about setting up aerospike cluster on rancher, works great now!

![image](https://cloud.githubusercontent.com/assets/583116/8761495/f8c5173e-2d4b-11e5-96e9-dea63fec94e4.png)

**Comment by ibuildthecloud** [comment]
@Kelindar.  It's in the works https://github.com/rancher/rancher-metadata
