### ISSUE TITLE
Ability to invalidate and rotate node template keys

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15696]
Today user enters the provide access key on the node template at the moment of creation, and there is no way to invalidate/rotate them. Have to add support for that, and the implementation might require key decoupling.

We should consider this issue while designing the feature as they seem to be entangled 
https://github.com/rancher/rancher/issues/12186

**Comment by sowmyav27** [comment]
with rancher:master build (02/19/2019), we have the ability to decouple the cloud credentials from other node template details. Issues found while testing this feature, have been logged separately.

[https://github.com/rancher/rancher/issues/18201](url)
[https://github.com/rancher/rancher/issues/18194](url)
[https://github.com/rancher/rancher/issues/18040](url)
[https://github.com/rancher/rancher/issues/18039](url)
