### ISSUE TITLE
Terminating Instance in AWS not reflected in Rancher 2

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#15691]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

# Expected

I would expect that the node pools monitor instances and if it is terminated in the provider that it gets reflected as such in Rancher 2 and re-provisioned by Rancher 2.

# Actual

When you terminate an EC2 instance that was provisioned as part of a node pool in Rancher 2, it just says in Active state.

**Comment by cjellick** [comment]
I believe this is the same as https://github.com/rancher/rancher/issues/14184

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/14184
