### ISSUE TITLE
Support More Alert Rules when Monitoring Tools is Enabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#15706]
Support more alert rules such as CPU/Memory usage when Monitoring Tools is Enabled

**Comment by orangedeng** [comment]
Pre-can new alerting rules
Cluster level:
ETCD leader lost: `etcd_server_has_leader{job="kube-etcd"} = 0`
ETCD leader change too frequency: `increase(etcd_server_leader_changes_seen_total{job="kube-etcd"}[1h]) > 3`
ETCD DB over size: `sum(etcd_debugging_mvcc_db_total_size_in_bytes) > 1073741824`
Node disk running full: `predict_linear(node_filesystem_free{job="node-exporter",mountpoint!~"^/etc/(?:resolv.conf|hosts|hostname)$"}[6h], 3600 * 24) < 0 and on(instance) up{job="node-exporter"} = 0`
Node high memory: `1 - sum(node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance)`
Node high cpu load: `sum(node_load1) by (instance) / count(node_cpu_seconds_total{mode="system"}) by (instance)`

Project level:
Pod memory approaching resource limits: `sum(container_memory_working_set_bytes{namespace="$namespace", pod_name=~"$instance"}) by ("$instance") / sum(label_join(kube_pod_container_resource_limits_memory_bytes{namespace="$namespace", pod=~"$instanceName"},"pod_name", "", "pod")) by (pod_name)`

Those pre-can rules should be validated and tested.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/48823867-58c8c080-ed9d-11e8-8317-ebb34d2593a7.png)

There will be a new option `Expression` for adding alert rules. 
User will be able to input an expression and it will show the metrics based on the expression. 
Then user can config the threshold and condition for the alert.

**Comment by soumyalj** [comment]
Tested with master build from Dec 7th. Tested cluster level and project level alerts and they are functional. The following issues were filed:
https://github.com/rancher/rancher/issues/16936
https://github.com/rancher/rancher/issues/16945
https://github.com/rancher/rancher/issues/16937
