### ISSUE TITLE
[2.0.8] Rebuilt master node in cluster and now has new CA cert and can never join cluster

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15701]
**Rancher versions:**
rancher/rancher: 2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CoreOS Container Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Steps to Reproduce:**
Rebuild pool node which then ended up with a different CA cert. This caused the other certs that were created to all be invalid to connect back to the other master nodes. Etcd on the node is never able to join.

**Results:**
Node does not start up and connects to masters correctly.

**Comment by superseb** [comment]
Please provide steps to reproduce as described in https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions.

How many nodes with what roles are in the cluster? Is a master node a node with only the role `Control Plane` or also others?

**Comment by mitchellmaler** [comment]
@supersub Here is a more in depth explanation on how I produced this issue.

1. Logged into Rancher Server and navigated to my clusters nodes. This cluster was built using the OpenStack driver.
2. Selected 1 of my three master (etcd & control) nodes and deleted it 
3. Rancher started provisioning a new node in it's place.
4. The node was stuck in wating to register so I decided to log into it to see what wasn't he issue 
5. I saw that etcd was restarting and it's logs said it was a x509 error. 
6. Looking at the certs on this node and compared them to an existing master the kubeca is a complete different value.
This caused the certs all to be invalid to connect to the other master servers.
I looked at the secret in kube-system in the cluster and it has the correct kubeca.
Some reason rancher is not using the original kubeca when it recreated the master node.

**Comment by mitchellmaler** [comment]
@superseb Looking in the API the cacert that rancher has for the cluster is also the original one. So why does it create a new one anyways.

**Comment by mitchellmaler** [comment]
@superseb I fixed this by downgrading to 2.0.7 and then manually deleting all certs in the /ssl directory which forced it to recreate all the certs on the new node again. This time they kubeca is the correct one.

**Comment by mitchellmaler** [comment]
@superseb I am having the same issue again but this time I just edited the cluster. The CA that is part of the cluster on rancher server ( under view in api) is not the same being deployed on the server which causes the health check to fail.

**Comment by mitchellmaler** [comment]
I tried to downgrade to rancher 2.0.7 but that didn't help. I am not sure how to get rancher to either place the correct CA or if it's possible to update the clusters ca in rancher to the newer one.

**Comment by deniseschannon** [comment]
WIth the changes for cert management in 2.2, please open a new issue if you've hit this again.
