### ISSUE TITLE
UI - Support More Alert Rules when Monitoring Tools is Enabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#15707]
UI for https://github.com/rancher/rancher/issues/15706

**Comment by loganhz** [comment]
https://github.com/rancher/rancher/issues/13916

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/14/18)
New alert features were validated. Testing was thorough and is too long to describe here, but the high level overview is: Test default rules, make custom groups and rules, test more than one recipient (notifier) per rule, test advanced options (resulted in issue #17114 being created), and various other areas. Test on both cluster and project level. Validate HTTP. Halo test. Test plan will be updated with these new features for alerting.
