### ISSUE TITLE
Real-time Metrics for Pods, Workloads, Clusters and Nodes

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#15704]
Implement the Rancher API for getting real-time metrics for Nodes, Clusters, Workloads and Pods.

**Comment by loganhz** [comment]
We will show real-time metrics for cluster/etcd/apiserver/controller-manager/scheduler/ingress-controller/fluentd/node/workload/pod/container

**Comment by jiaqiluo** [comment]
The test plan has been drafted and general tests have been finished. 
Also, bugs and changes have been tracked with their own tickets.
