### ISSUE TITLE
UI - Real-time Metrics for Pods, Workloads, Clusters and Nodes

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#15705]
UI for https://github.com/rancher/rancher/issues/15704

**Comment by cjellick** [comment]
While testing, we need to distinguish between potential alpha1 blockers and not. If you find a problem that is an alpha blocker, please add the `releases/alpha1` tag

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/10/18) and v2.0.2-alpha2
Validated new feature. This feature was thoroughly smoke tested by myself and other QA. I can confirm all of the core functionality is there. Further testing will occur throughout the v2.2 cycle and during regression testing.
