### ISSUE TITLE
In Edit Load Balancer, looks like i can delete all targets but none actually delete

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1570]
v0.28.0-rc1
Steps:
1.  Create a service Load Balancer with at least 2 targets
2.  Edit the Load balancer and delete all targets and click on Save

Results:  The save completes and it looks like I saved with no targets.  But if you go to edit you will see that nothing happened and all targets are still there.

Expected:
If you remove all targets you should get an error message that says you have to have at least one target.  It should not allow you to save and just keep whatever you deleted previously.

**Comment by alena1108** [comment]
can't reproduce it on the latest. Could you retry, Tani, and reopen if you see it again

**Comment by deniseschannon** [comment]
Couldn't reproduce with v0.30.0-rc2 (Tried with a LB that was inactive and active).
