### ISSUE TITLE
On Cluster Import: websocket: bad handshake (returns 401)

### ISSUE THREAD

**Issue by johannges** [rancher/rancher#15712]
**Rancher versions:**
rancher/rancher-agent:alle

**Infrastructure Stack versions:**

kubernetes (if applicable): v1.10.2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node behind Traefik inside docker swarm with lets encrypt

**Steps to Reproduce:**

I am trying to import a Kubernetes Cluster.

1. I had the Problem, that the APIEndpoint IP for the Kubernetes API was set to the cluster internal IP.

I Fixed it by adding the External IP of the Kubernetes API via KUBERNETES_SERVICE_HOST Env in all Container inside the Import YAML generated bei Rancher:

https://rancher.integration.???.de/v3/import/....yaml

Now I am getting:
time="2018-09-19T15:53:54Z" level=info msg="Connecting to proxy" url="wss://rancher.integration.?????/v3/connect"
time="2018-09-19T15:53:54Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-09-19T15:53:54Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

I already checked:
1. wss connection(is Reachable but returns 401) 
2. Certificates (are valid)

What are the next Steps i can do to fix this Problem?

**Comment by superseb** [comment]
What version of Traefik are you using, can you please try with 1.7.0? Also, what config are you using?

The code will log when certificates are not valid instead of bad handshake.

**Comment by f3l1x** [comment]
We fixed it by change Nginx configuration, the problem was in WebSocket configuration.

**Comment by johannges** [comment]
Same Problem for us

Thanks for the help

this issue can be closed

**Comment by derWeihnachtsmann** [comment]
> We fixed it by change Nginx configuration, the problem was in WebSocket configuration.

May I ask what did you changed?
