### ISSUE TITLE
kubectl client and workload exec shell stuck in "Connecting" state for EKS cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15716]
**Rancher versions:**
rancher/server or rancher/rancher:

**Steps to Reproduce:**
1. Create an EKS cluster.
2. Create workload and exec into the pod. It is stuck in "Connecting" state

<img width="1696" alt="screen shot 2018-09-19 at 1 29 08 pm" src="https://user-images.githubusercontent.com/18536626/45779520-186b8b80-bc10-11e8-8fe8-2c8b0058b6fc.png">

Launch the kubectl in rancher. It is stuck in "Connecting " state
<img width="1688" alt="screen shot 2018-09-19 at 1 29 26 pm" src="https://user-images.githubusercontent.com/18536626/45779578-36d18700-bc10-11e8-9229-f87e4420c931.png">

**Comment by jmirc** [comment]
I have the same issue even if the other features work like import, start a new deployment etc. Only the features opening a shell, the kubectl console or to view the log don't work.

**Comment by cjellick** [comment]
@soumyalj @jmirc how many nodes were in your cluster?

**Comment by cjellick** [comment]
@jmirc what version of rancher are you  uisng?

**Comment by soumyalj** [comment]
Tested with master.
1. Create cluster with default values.
2. Create workload and exec into the pod. It was successful
<img width="1322" alt="screen shot 2018-09-25 at 2 19 28 pm" src="https://user-images.githubusercontent.com/18536626/46043897-1a30c580-c0ce-11e8-91f5-d78ce300a711.png">

Also, launching kubectl shell successful
<img width="1368" alt="screen shot 2018-09-25 at 2 19 45 pm" src="https://user-images.githubusercontent.com/18536626/46043925-37fe2a80-c0ce-11e8-997f-04fdb8d2a97e.png">
