### ISSUE TITLE
[bug] deleting a cluster that uses node pool does not terminate nodes

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#15714]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

# Expected Behavior

When deleting a cluster that has nodes provisioned via node pools and the node drivers I would expect that rancher would clean up these nodes as part of the cluster deletion proces.

# Actual Behavior

When you delete a cluster that has nodes provisioned via node drivers. The nodes are not removed from their respective provider. They remain in place.

**Comment by cjellick** [comment]
We couldn't reproduce this with Digital Ocean. Any more details that you can provide?

**Comment by ekristen** [comment]
AWS was my provider, but I’ll try one more time just to be sure.

**Comment by ekristen** [comment]
Interesting, I've tried this two more times and it seems to be working as expected. Not sure what happened the other times, but I'm happy to consider this not an issue. I'll re-open if I run into it again.
