### ISSUE TITLE
SAML ADFS binding breaks after editing & cannot be rebound

### ISSUE THREAD

**Issue by jamesmcminn96** [rancher/rancher#15724]
**Rancher versions:**
rancher/rancher: v2.0.8
rancher/machine: v0.15.0-rancher1-1
rancher/ui: v2.0.67
rancher/helm: v2.9.1-rancher1

**Docker version:** 18.03.1-ce

**Operating system and kernel:** Amazon Linux AMI 2018.03

**Type/provider of hosts:** AWS EKS

**Setup details:** single node rancher w/ internal DB

**Environment Template:** Kubernetes

**Steps to Reproduce:**

1. Bind Rancher to AD FS for the first time following the [Rancher instructions here](https://staging.rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/microsoft-adfs/)

2. Once bound, edit any of the configuration fields and 'Save'

3. It will prompt for AD FS credentials, input the same credentials used to create the binding.

**Results:**

Relevant logs from the server:
`2018/09/20 00:17:31 [ERROR] SAML: User does not have access <nil>` this is interesting as the domain user being used to update the binding is the same one for creating the binding.

Rancher will redirect in the popup to a failed page:
![image](https://user-images.githubusercontent.com/3772113/45788638-27f5dd80-bcbf-11e8-912e-f9f2da3445e7.png)

AD FS will go into the not configured state, users will not be able to login with AD FS.
![image](https://user-images.githubusercontent.com/3772113/45788736-ace0f700-bcbf-11e8-968f-9feaab6d8958.png)

Any subsequent attempts to rebind with AD FS fail for the same reason

**Comment by cjellick** [comment]
Fixed in the UI in https://github.com/rancher/rancher/issues/15769

Should be tested as part of that

**Comment by sangeethah** [comment]
Currently the UI relating to "Edit/Disable AccessControl" is not presented properly to the user- https://github.com/rancher/rancher/issues/15845

Blocked on testing this issue until this issue gets resolved.

**Comment by sangeethah** [comment]
Tested with v2.1.0-rc7

Enable  AD FS auth.
Once enabled , go to Security->Authentication to launch the AD FS auth detail page.
Use "Edit" option to do some changes and the "Save".
Once AD FS authentication succeeds , user is brought back to the authentication page successfully.  Error reported in this issue is not seen anymore (Was able to reproduce this issue when testing with 2.0.8).
