### ISSUE TITLE
Make arp sync configurable via ipsec catalog

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#15729]
**Rancher versions:**
rancher/server:v1.6.21
rancher/network-manager:v0.7.22

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Summary of issue:**
The impact is that we experience connection errors when the stacks first starts up with the default settings arp sync settings in the network-manager. We have to edit the service and add `--arpsync-interval=SOME_LARGE_VAL` to avoid the flapping on container startup. Further this doesnt persist stack upgrades. Ideally we can make this configuration value configurable via the template.

**Comment by aemneina** [comment]
There's also the issue where arp errors in network manager seem to build up until connectivity flapping happens:

```8/21/2018 3:01:57 PMtime="2018-08-21T22:01:57Z" level=info msg="arpsync: (host) wrong ARP entry found={LinkIndex:18 Family:2 State:2 Type:1 Flags:0 IP:10.42.51.17 HardwareAddr:00:19:24:3a:27:cf}(expected: 02:3a:81:5a:85:9f) for local container, fixing it"
8/21/2018 3:02:03 PMtime="2018-08-21T22:02:03Z" level=info msg="arpsync: (host) wrong ARP entry found={LinkIndex:18 Family:2 State:4 Type:1 Flags:0 IP:10.42.51.17 HardwareAddr:00:19:24:3a:27:cf}(expected: 02:3a:81:5a:85:9f) for local container, fixing it"
8/21/2018 3:02:03 PMtime="2018-08-21T22:02:03Z" level=info msg="arpsync: (host) wrong ARP entry found={LinkIndex:18 Family:2 State:2 Type:1 Flags:0 IP:10.42.216.125 HardwareAddr:00:19:24:f1:6c:5c}(expected: 02:3a:81:04:a5:1e) for local container, fixing it"
8/21/2018 3:02:03 PMtime="2018-08-21T22:02:03Z" level=info msg="arpsync: (host) wrong ARP entry found={LinkIndex:18 Family:2 State:2 Type:1 Flags:0 IP:10.42.253.68 HardwareAddr:00:19:24:d6:b6:1f}(expected: 02:3a:81:a0:86:79) for local container, fixing it"```

**Comment by alena1108** [comment]
The support for configurable param should be already on the ipsec side; we just have to enable it in the catalog.

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.26-rc1`

**Comment by soumyalj** [comment]
Tested with rancher v1.6.26-rc1. 
In the Network services template, we do see a field for ARP sync interval and it is configurable:
<img width="401" alt="screen shot 2019-01-08 at 11 26 12 am" src="https://user-images.githubusercontent.com/18536626/50853833-43512b00-1338-11e9-9922-1b37c6cc3c01.png">

The ARP sync interval was changed to a different value and it was updated accordingly and the setup was functional.
<img width="483" alt="screen shot 2019-01-08 at 11 28 54 am" src="https://user-images.githubusercontent.com/18536626/50853952-a0e57780-1338-11e9-9676-bf5106d755c9.png">
