### ISSUE TITLE
install gitlab error [app store]

### ISSUE THREAD

**Issue by bnnd** [rancher/rancher#15723]
rancher 2.0 install gitlab-ce/ee
report error:
```
CreateContainerConfigError: failed to create subPath directory for volumeMount "data" of container "gitlab-ee-postgresql"
```

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
