### ISSUE TITLE
Upgrading workload unable to pull new image from custom repository

### ISSUE THREAD

**Issue by rmgroth** [rancher/rancher#15725]
Rancher | v2.0.8
User Interface | v2.0.67
Helm | v2.9.1-rancher1
Machine | v0.15.0-rancher1-1

Rancher is deployed in HA setup with 3 nodes built with rke
Kubernetes 1.11.1
Ubuntu 16.04.5 LTS
Kernel: 4.4.0-1065-aws
Docker: 17.3.2

Using a custom repository with basic auth defined at namespace level. When upgrading a workload to a new version, upgrade starts but new container is not able to start, viewing details in interface shows a basic auth error, eventually goes to imagePullBackOff.

yaml for workload contains a:
```
imagePullSecrets:
     - name: ndc-bsg8j
```
section as detailed as a potential fix/workaround in Issue #13339 

Deleting the workload and deploying again with new image version tag as attempted in upgrade works flawlessly

**Comment by rmgroth** [comment]
ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: Get https://<servername-redacted>/v2/<workload>/manifests/7: no basic auth credentials

This is quite a showstopper for us as we try to automate upgrading workflows in development

**Comment by alena1108** [comment]
Looks to be the same as https://github.com/rancher/rancher/issues/15994 that got resolved

**Comment by kennyjohnson2** [comment]
This bug resurfaces when using kubectl set deployment to upgrade a workflow, and then trying to upgrade again through the web UI. You can use one or the other in perpetuity, but once the kubectl command is used, the imagepullsecrets entry is removed during an upgrade done through the web UI

**Comment by jiaqiluo** [comment]
### Reproduced the issue on Rancher v2.0.8
Step:
1. Add a registry in Rancher UI.
2. Select `Available to a single namespace`
3. Deploy a workload in the same namespace with image 18.144.15.108.xip.io:443/nginx:v1
4. Check the imagePullSecrets has been added automatically
5. Upgrade the image version in the workload to 18.144.15.108.xip.io:443/nginx:v2
6. Click Upgrade

Results:

- `imagePullSecrets` is gone from the api file. 
- Docker can not pull the image on the private registry, the new pod get this error: `ImagePullBackOff: Back-off pulling image "18.144.15.108.xip.io:443/nginx:v2"`

### Validated fix on Rancher master 11/26
Redo the same steps as the above, and the workload got updated successfully.

Bug fix verified.
