### ISSUE TITLE
Need UI drop down to list supported AMIs for an EKS cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15726]
**Rancher versions:**
rancher/server or rancher/rancher: v2.1.0-rc3

Currently when creating an EKS cluster, we have to copy paste the desired AMI.
Drop down with list of supported AMIs would be useful

**Comment by cjellick** [comment]
The whole point of this field is that it is a custom AMI, allowing the user to input what they want. Not intended to be a dropdown

**Comment by cjellick** [comment]
Sending this back to you @soumyalj, just so you see it and are aware. Please close or push back with more details if you disagree

**Comment by cjellick** [comment]
correct. User needs to know what theyre doing here. The wide wide world of AMIs is open to them

**Comment by soumyalj** [comment]
Should we put a note in the UI that users have to  provide the right custom AMI that will work with template and region ? Just a thought.

**Comment by cjellick** [comment]
The current explanatory text that @westlywright showed me seems sufficient to me.
