### ISSUE TITLE
shouldn't use personal repo for pipeline examples

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15722]
**Rancher versions:** 2.1 master 9/19

**Steps to Reproduce:**
1.  Create cluster
2.  Go to default project
3.  Go to Pipelines
4.  Enable rancher/pipeline-example-go
5.  Run

**Results:**  Message says it's running from gitlawr/var_image.  Probably shouldn't be using personal repos for the examples.
![image](https://user-images.githubusercontent.com/11514927/45788425-65128f00-bc2f-11e8-9d36-3d32793cf1b9.png)

**Comment by gitlawr** [comment]
Let's do a rebase and squash to overwrite the commits messages.
But the execution list shows the committer's avatar anyway. Is there any impersonal git account to do the stuff?

**Comment by tfiduccia** [comment]
Now the message always says : Commit Message update README.md with the readme.md being a link that doesn't resolve?  This also does not seem correct.

![image](https://user-images.githubusercontent.com/11514927/45980725-a0360900-c007-11e8-89a7-e28b3965b871.png)

**Comment by tfiduccia** [comment]
Version - 2.1 master
Verified fixed
