### ISSUE TITLE
Node link in Workloads Flat List is not aligned properly

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15733]
Version: master 9/20

**Steps to Reproduce:**
1. Open Workloads, select Flat List

**Results:**
<img width="1382" alt="screen shot 2018-09-20 at 14 44 58" src="https://user-images.githubusercontent.com/2620179/45819163-fba08800-bce3-11e8-98fb-e0e6ee15e55d.png">

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/20
Verified fixed
