### ISSUE TITLE
Rancher should support self-healing node pools

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#15737]
In the case where we're leveraging an Iaas Provider, we should have an option to deploy a new healthy node to keep the node-pool node count stable.  We could possibly leverage https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler

**Comment by cjellick** [comment]
Ping @alena1108 . THis should be consdiered as part of node pool refactor

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/15738

**Comment by bmdepesa** [comment]
rancher/rancher:master-head

Feature is passing 99% of test cases - #21431 is the only issue outstanding thus far

P1 - Worker nodepool self-healing
AWS, Azure (with and without cloud provider), DO, VSphere
ETCD / Controlplane self-healing when quorum is not broken
Delay bounds
Scheduling
