### ISSUE TITLE
Add values.yaml support for Rancher CLI

### ISSUE THREAD

**Issue by canhnt** [rancher/rancher#15731]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent: 2.0.4

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.11.2

**Docker version: (`docker version`,`docker info` preferred)** 1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux 7
```
3.10.0-862.3.3.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

The current Rancher CLI only allows to install app (Helm chart) with either providing answers.yaml file or setting each param with `--set` argument. It does not support to use Helm values.yaml file as the parameter input.

Previous issue https://github.com/rancher/rancher/issues/14844 covered supporting values.yaml for UI only. However for building up CI/CD pipeline, it's convenient for users that Rancher CLI should be backward compatible with Helm values.yaml file.

It would be nice if Rancher CLI can use Helm values.yaml file directly.

**Comment by tylerstapler-wf** [comment]
This is a blocker for our internal dev workflow. We'd love to get this implemented.

**Comment by loganhz** [comment]
cli `v2.2.0-rc1` is available now

**Comment by rootwuj** [comment]
**Rancher version**: rancher/rancher:master 01/30
**RancherCLI version**: v2.2.0-rc5, v2.2.0-rc4, v2.2.0-rc3, v2.2.0-rc2, v2.2.0-rc1
Verified fixed

* This version of rancherCLI supports the `values` ​​command options
* The install, upgrade, rollback, delete commands have been verified
