### ISSUE TITLE
Cluster Graphs need key and should include memory in use as well

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#15740]
The Cluster Graph needs a Key on what the black boxes and circles mean.  There should also be a slice included for actual memory use and not just reserved.
![image](https://user-images.githubusercontent.com/942110/45836586-44077800-bcdb-11e8-8ced-7b159523a7b9.png)

**Comment by davidnuzik** [comment]
@loganhz could you link the PR for this? Or mention what I need to validate?
The black boxes have been removed in an earlier release than current of Rancher (v2.2.3 I think).

**Comment by loganhz** [comment]
@davidnuzik Yes, we have removed the black boxes and circles stuff in dashboard. 
So it's not an issue any more. Maybe we can close it?

**Comment by davidnuzik** [comment]
Thanks @loganhz yes we removed them I just wanted to double-check that this is the only thing I need to confirm.
I will close this issue; the black boxes have been removed.
Version: v2.2.4, Master (v2.3) 6/7/19.
