### ISSUE TITLE
Error processing tar file

### ISSUE THREAD

**Issue by josecelano** [rancher/rancher#15745]
Trying to upgrade a stack I am getting this error:

`Removing bad service instance: Error response from daemon: Error processing tar file(exit status 1): mkdir /xxx: no space left on device`

I am using sidekick containers for all services.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |

**Comment by cjellick** [comment]
This leads me to believe that host where that service is deployed is out of disk space. Or at least the disk that docker writes to is

**Comment by josecelano** [comment]
Yes, It was exactly that. Probably because there were a lot of unused images. Thanks.
