### ISSUE TITLE
Host gets to "reconnecting" state and then back to "active" state when there are lot of container deletes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1574]
Server version - V0.28.0

Steps to reproduce the problem:

Had set up with 3 hosts are many containers running on these hosts.
As part of cleaning up the existing set up, deleted all the existing containers. 
When the containers are being deleted and purged , I notice that the host that are in "active" state switching to "reconnecting" state . After a while , it gets back to "active" state.

Why is the host agent getting to "reconnecting" state for while there is large number of activities like purging containers ?

**Comment by ebuildy** [comment]
It could due to network latency maybe. What network did you use for the IPSec connection (public or private)?

**Comment by cjellick** [comment]
We addressed by making the host pinging less aggressive and by adding a timeout to our `docker ps` calls.

**Comment by cjellick** [comment]
Ping @ibuildthecloud

**Comment by sangeethah** [comment]
Not encountered this issue when deleting lot of containers from host. I have been able to delete the containers successfully with out the hosts getting to "reconnecting" state.
