### ISSUE TITLE
AD: Improvements to search results when "SearchFilter" is used.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15748]
1. When "memberOf" in User SearchFilter , We dont allow for searching users in the the nested groups. For example - If we have "User Search Filter" set to
```(memberOf=CN=finalgroup1,CN=Users,DC=testad,DC=rancher,DC=io)```
, only members that are members of this group will appear in the search list. If there were groups under this group , users from these nested groups will not show up in the list.

2. Searching users ( ```https://<ip>/v3/principals?action=search``` ) would always include local users who have already logged in to the setup (and a account has been created for them in rancher). These set of local users will not be filtered by "Group Search Filter" / ""User Search Filter".
Use case:
Enable AD auth with no "User Search Filter" set.
Log in to rancher-server as say "user1" (who is not member of group "test1").
Disable AD. Enable AD with "User Search Filter" set to
```(memberOf=CN=test1,CN=Users,DC=testad,DC=rancher,DC=io)```
.
Users will now be able to search for "user1" even though he is not part of group "test1".

**Comment by cjellick** [comment]
Moving out of v2.1
