### ISSUE TITLE
update nginx-ingress-controller

### ISSUE THREAD

**Issue by KaelBaldwin** [rancher/rancher#15747]
I'm noticing on rancher/rancher v2.0.7, the nginx-ingress-controller image is behind the https://github.com/kubernetes/ingress-nginx version enough that there are a lot of metrics missing when used with prometheus / grafana.

I was looking forward to be able to hook into the metrics of all the ingresses easily, but there are a ton of the metrics missing.

Wondering if we can get it caught up?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/15163

**Comment by KaelBaldwin** [comment]
thanks

**Comment by chpiter** [comment]
> thanks

I got this error too (Metrics missing)
how can i fix it
thanks a lot

**Comment by KaelBaldwin** [comment]
I ended up cheating and changing the image used to the official kubernetes one instead of rancher's. I haven't had any problems, but I suspect it could get reverted when I upgrade rancher. Not sure.

**Comment by KaelBaldwin** [comment]
So I went into the System project and edited the yaml for the nginx-ingress-controller and changed the image for the nginx-ingress-controller to "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0" there might be a newer image now though.

**Comment by chpiter** [comment]
> Fair warning, I have no idea if this will cause problems, but:
> 
> I went into the System project and edited the yaml for the nginx-ingress-controller and changed the image for the nginx-ingress-controller to "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0" there might be a newer image now though.

Got it!! 
I use rancher2.1.1, and the image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0"  is usefull !!
