### ISSUE TITLE
[docs] Please provider better/more restrictive AWS IAM policies

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#15744]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

The example IAM policies for an AWS EC2 cluster are way too permissive. For anyone seriously running R2 in AWS, these policies shouldn't be used nor should they even be promoted outside of a development setting. The essentially give free reign on all ec2 resources.

It would be nice to get a subject matter expert from Rancher who understands what permissions are actually needed to help form IAM policies that are more specific.

An example of a more restrictive policy is the one I wrote for EBS volumes on R1 EBS Volume Plugin, it limits the capabilities of the node to generate volumes and then only delete the ones it created, as well as attach and detach nodes that are under rancher's control https://github.com/rancher/rancher/issues/9343#issuecomment-319468333

So far my attempts to use R2 K8S AWS Cloud Provider and provide a more restrictive IAM policy has resulted in many things not working. I finally got node creation to work, but I am unable to get EBS volumes to work.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/docs/issues/947
