### ISSUE TITLE
[Agent/Cluster/Rancher2.0] Second node does not want to register

### ISSUE THREAD

**Issue by kubo6472** [rancher/rancher#15741]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent: v1.11.2
Docker version: https://hastebin.com/yocovejujo.makefile
Operating system and kernel: 4.14.32-rancher2
Type/provider of hosts: Bare-metal
Setup details: First node (on the rancher server) registered successfully. I know they can communicate as one other node also had no problem registering in cluster ALONE.
Environment Template: Kubernetes
Steps to Reproduce:
1. Install RancherOS on three same bare metal servers. (https://support.hp.com/sk-en/document/c03387773)
2. Download rancher/rancher from Docker Hub on the first Node
3. Open up the rancher web interface (all 3 nodes have static internal IPs)
4. Create new cluster and copy the command.
5. Run the command with ectd, control plane and worker on the first node, on the rest of the nodes run just worker. (I tried waiting for the first node to complete the process too)
Results: The second and the third node will not register.
Disclaimer : I read your documentation, but I am total begginer with docker. I tried googling what I did not understand. Thxfu.

**Comment by cjellick** [comment]
Do your hosts have the same hostname by chance?

**Comment by kubo6472** [comment]
> Do your hosts have the same hostname by chance?

they are node1, node2 and node3 respectively.

**Comment by kubo6472** [comment]
http://prntscr.com/kxohqz

**Comment by kubo6472** [comment]
Changing the hostnames resolved the issue
