### ISSUE TITLE
Rancher 2.X Automatic Rebuild after node is unavailable past timeout

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15753]
When using a node driver it is easy to rebuild a node using the UI or API by just deleting it from the pool which causes it to automatically to start provisioning a replacement. It would be awesome if I could have Rancher automatically delete/rebuild a node if it is unavailable for too long (a configurable timeout)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15737
