### ISSUE TITLE
Add telemetry to the rancher catalog apps

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#15754]
Feature Request: added telemetry to the rancher catalog apps to track its install counts of rancher `library` catalog.

Metadata:
```
appName: appname
appVersion: v0.1.0
InstalledAt: dd-mm-yy
```

**Comment by vincent99** [comment]
This is the sort of thing we [specifically](https://rancher.com/docs/rancher/v2.x/en/faq/telemetry/#what-information-is-collected) and intentionally say we don't do.  

At a minimum it needs to be limited to only the two public catalogs.  Collecting third-party app information is definitely not ok.

**Comment by guangbochen** [comment]
@vincent99 currently we only aim to collect the metrics of `library` catalog only, definitely not a third-party catalog.
