### ISSUE TITLE
Container should have been running but is in stopped state. Check logs for more information.: Timeout getting IP address

### ISSUE THREAD

**Issue by zdYng** [rancher/rancher#15755]
*Describe your issue here*

When I restart the centos7 server, the container created in the rancher fails to start and reports an error: Container should have been running but is in stopped state. Check logs for more information.: Timeout getting IP address

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.22` Cattle: `v0.183.63` UI: `v1.6.47` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
