### ISSUE TITLE
During SAML EDIT call, UI seems to clear out the allowedPrincipalIDs

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#15769]
**Rancher versions:**
rancher/rancher:master
The EDIT request for saml provider includes two calls:
1. PUT to the specific saml config (ADFS used while testing)
This first PUT request seems to have an empty allowedPrincipalIDs list even though it was set previously and had some principal in it
2. testAndEnable action
<img width="1440" alt="screen shot 2018-09-21 at 11 54 43 am" src="https://user-images.githubusercontent.com/10672776/45900785-94431080-bd95-11e8-98ab-dc295a5c7f0b.png">

The same EDIT request for AD has only one call, to testAndApply action, which includes the values from allowedPrincipalIds previously set
<img width="1440" alt="screen shot 2018-09-20 at 4 53 20 pm" src="https://user-images.githubusercontent.com/10672776/45900873-dff5ba00-bd95-11e8-8df4-57e52ac6d0e2.png">

**Comment by mrajashree** [comment]
Refs https://github.com/rancher/rancher/issues/15724

**Comment by tfiduccia** [comment]
Version - 2.1 rc7
Principals sent on Save.
Verified fixed
