### ISSUE TITLE
Add optional retry to failed host provision jobs

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#1576]
DigitalOcean doesn't always provision a host in "60 seconds," and when Rancher gives up, I'm without an ssh-key and password to event start the age manually. I believe there should be an option to retry a timed-out host connection.

**Comment by wlan0** [comment]
@willseward Can you print the error message that you see? Rancher does not have a 60second timeout imposed at any point while creating hosts.

**Comment by wlan0** [comment]
Also, can you provide all the options that you specified while creating the DO host.

**Comment by willseward** [comment]
I'm aware that Rancher does not have a 60 second timeout, but DigitalOcean claims that it can provision a host in that time. I was only jabbing.

Rancher does however have a max retry count of 60, and it frequently will reach that limit when searching for the newly provisioned host. 

I will attempt to recreate the issue, but there are no guarantees because it is solely reliant on DO's current load.

**Comment by wlan0** [comment]
@willseward Do you mean this error message "Maximum number of retries (60) exceeded"?

This message is from docker-machine, when it fails to open a SSH connection to the newly created host.

**Comment by willseward** [comment]
Yes. That is what I'm talking about.

**Comment by wlan0** [comment]
@willseward we are adding a feature to our host provisioning where we remove a host if we could not provision it for any reason, that way the user doesn't have to worry about orphaned hosts. 

You can follow that PR here - https://github.com/rancher/go-machine-service/pull/54

**Comment by flaccid** [comment]
DO seemed flakey to me at least last weekend, https://github.com/rancher/rancher/issues/1579#issuecomment-122960701.

**Comment by willseward** [comment]
@wlan0 This issue is fairly old. Do you want to close?

**Comment by deniseschannon** [comment]
@willseward I love closing issues. :) 

If you see it again, please re-open, but it sounds like it was mostly a docker-machine error and maybe something going on with DO that weekend.
