### ISSUE TITLE
[UI] Kubernetes Object YAML editor should show errors if they occur, rather than silently failing

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#15766]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Any Rancher 2.0 setup

**Steps to Reproduce:**
Click "View/Edit YAML" on any Kubernetes object from the UI, and edit it. Make a mistake which causes Kubernetes to reject your object and try to hit save

(i.e. edit a deployment and set the replicas to "x")

**Results:**
Rancher spins the save wheel, but then that's it. No response or anything from the UI telling you what went wrong.

**Comment by loganhz** [comment]
Fixed in v2.1.0
