### ISSUE TITLE
Add Pod creation time in Workload detail view

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15761]
In Workloads -> Flat List, we have Pod created time:
<img width="860" alt="screen shot 2018-09-21 at 16 18 46" src="https://user-images.githubusercontent.com/2620179/45886789-4a205600-bdba-11e8-9e19-20b26cc05a28.png">

Would be nice to have that in Workload detail view too:
<img width="1147" alt="screen shot 2018-09-21 at 16 21 14" src="https://user-images.githubusercontent.com/2620179/45886828-658b6100-bdba-11e8-9a3e-f9a70bb54d9e.png">

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed
