### ISSUE TITLE
Replace Node IP to Nodename in Pod detail view

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15762]
Currently we show Node IP in Pod detail view but would be more convenient to have `Node Name: <name>` or `Node Name: <name> (<IP>)`.

<img width="931" alt="screen shot 2018-09-21 at 16 24 29" src="https://user-images.githubusercontent.com/2620179/45887041-fc581d80-bdba-11e8-9341-f79178793aae.png">

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/2
Verified fixed
