### ISSUE TITLE
Grafana Kubernetes Plugins - Config?

### ISSUE THREAD

**Issue by LunaticZorr** [rancher/rancher#15760]
Hi,

I just installed the Kubernetes Plugins (https://grafana.com/plugins/grafana-kubernetes-app) on the Grafana Pod created with the Prometheus App from the Rancher Library, and am trying to set them up.

I've enabled the plugin, and it has to connect to the Kubernetes Cluster. It's asking for the following settings:

![Image](https://i.postimg.cc/pVSpPjbR/Capture1.jpg)

I'm not able to find out what settings to use for this to work. 

I always get the same errors:

![Image 2](https://i.postimg.cc/mDCBRPQ2/Capture2.jpg)

Any help is appreciated.

Thanks!

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by deniseschannon** [comment]
Please checkout the new monitoring feature that was introduced in v2.2.
