### ISSUE TITLE
Allow cross stack linking

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1577]
docker-compose should support the ability to link to services within (default) and across stacks.

**Comment by vincent99** [comment]
(and the UI should support it too)

Carry the +1 from @jwhitcraft in #1597.

**Comment by deniseschannon** [comment]
Will this also include load balancing? Otherwise, we need to re-open #1597.

**Comment by vincent99** [comment]
I think we can cover all the types of services in one issue...

**Comment by kaos** [comment]
+1 for this :)
