### ISSUE TITLE
Scale up/down nodes for hosted providers

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15773]
Depends on https://github.com/rancher/rancher/issues/15772

Once NodePool support for hosted providers API is in, add unified interface/API for scaling up/down nodes

**Comment by sergiomacedo** [comment]
Any idea if this will be done? It'll be bad to tell our internal clients to use both Rancher AND AWS UI when we're "selling" an integration tool...

**Comment by deniseschannon** [comment]
Closing this in favor of the node pool support added in refactored versions for EKS (available as of v2.5.0).

AKS and GKE are currently targeted for v2.5.7 (end of April).

The node pool support will be available for provisioning new hosts.
