### ISSUE TITLE
Helm annotations fail on kubernetes dashboard

### ISSUE THREAD

**Issue by nathankodilla** [rancher/rancher#15778]
**Rancher versions:**
rancher/rancher:v2.1.0-rc3

**Steps to Reproduce:**
Setting annotations in the UI does not work and causes a failure of deployment. This seems to be on multiple charts, but I have been mainly testing on the kubernetes dashboard.
![image](https://user-images.githubusercontent.com/22841858/45911816-4a364b00-bde6-11e8-9cab-f1dbfa231d6c.png)

**Results:**
This error shows in the UI:
```Failed to install app kubernetes-dashboard. Error: release kubernetes-dashboard failed: Ingress in version "v1beta1" cannot be handled as a Ingress: v1beta1.Ingress.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|irect\"":true},"labe|..., bigger context ...|","\"nginx.ingress.kubernetes.io/ssl-redirect\"":true},"labels":{"app":"kubernetes-dashboard","chart|... ; ```

**Comment by justinrush** [comment]
Can "work around" by hard coding in values.yaml

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13158
You will be able to add it in values.yaml

**Comment by jacobblock** [comment]
@nathankodilla I just figured this out myself, please try escaping the periods, e.g. ```iam\.amazonaws\.com/role: "role"```. This is working for me for metallb service.

**Comment by AdrienKuhn** [comment]
@LennardWesterveld 

I have the exact same issue on Rancher 2.2.0-rc3 with Jenkins Helm package. Escaping the period doesn't work.
Did you find a solution?
