### ISSUE TITLE
UI hangs on node-drivers page with missing permissions

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#15779]
**Rancher versions:**
rancher/rancher: 2.0.8

**Steps to Reproduce:**
Create a project inside a cluster, and a user with permission "Project Member".
On "Global"-View try clicking "Node Drivers".

**Results:**
Loading website will hang indefinitely.
It should throw an error, and the menu-item not be visible in the first place.

**Comment by loganhz** [comment]
Fixed UI hangs issue in v2.1.0. The menu item will be invisible in other release.
