### ISSUE TITLE
Node pools for hosted providers types

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15772]
Today NodePool concept in Rancher exists only for RKE clusters - it's an easy way to define the template for the nodes provisioning, and cluster scale up. Have to NodePool support for other k8s providers - AKS, EKS, GKE. If the provider has support for the NodePools - GKE does, check the rest - integrate with their NodePool APIs.

**Comment by genscape-agodfrey** [comment]
eagerly awaiting this now that aks supports node pools

**Comment by glentakahashi** [comment]
Sorry to pester, but is there any idea on where this falls on priority/is slated for work? This would be a really nice feature to have.

**Comment by Dougoc** [comment]
looking forward to this feature guys.

**Comment by jhcook** [comment]
I'm looking forward to it as well.

**Comment by deniseschannon** [comment]
Closing this in favor of the node pool support added in refactored versions for EKS (available as of v2.5.0). 

AKS and GKE are currently targeted for v2.5.7 (end of April). 

The node pool support will be available for provisioning new hosts.
