### ISSUE TITLE
[rancher-compose] rancher-compose zombie invasion!

### ISSUE THREAD

**Issue by ds0nt** [rancher/rancher#1578]
Here is a sequence of events.
1. naively run rancher-compose with mysterious scripts from @faddat
2. strange, yet successful output pours into the terminal, sans --pretty
3. the child application, frantically logging, crawls to a halt, and then fades into the background (^C)
4. now my rancher-compose children are orphaned into the labyrinth of linuxness, mysterious trails of file descriptors, and dusty /proc folders are our only hopes to determine if they succeeded, or failed in their aspirations of freaking awesome-win

TLDR
 **rancher-compose** -> outputs into terminal -> wordpress launches -> rancher-**compose tails the log forever** -> https://gist.github.com/ds0nt/0f0dd348680d92fe53dc#file-logs-L20

is there -> Exit code? webhook? callback? zombie howls? :)

I expected
1. rancher-composage
2. (remote) wordpress is launched
3.
```javascript
  childProc.on('close', function (exitcode) {
    # I don't usually exit, but when I do, 
      exitcode == statusOfWin?
      IPO() : zombieInvasion()
    
     console.log('child process exited with code ' + code)
  })
```

webserver needs to be able to rancher-compose things. Can rancher-compose do async? webhooks? what's the pattern I should be using to programmatically host apps based on these yml configs?

**Comment by ds0nt** [comment]
Here you go. there is a nodejs error:... but it happens even if I simply run the bash script

https://gist.github.com/0f0dd348680d92fe53dc

**Comment by ds0nt** [comment]
this one -> https://gist.github.com/ds0nt/0f0dd348680d92fe53dc

**Comment by ds0nt** [comment]
in particular: this line. What should I do?
https://gist.github.com/ds0nt/0f0dd348680d92fe53dc#file-logs-L20

**Comment by ds0nt** [comment]
I suspect this stuff

https://github.com/rancher/rancher-compose/blob/master/rancher/service.go#L682

```go
func (r *RancherService) pipeLogs(container *rancherClient.Container, conn *websocket.Conn) {
	defer conn.Close()

	log_name := strings.TrimPrefix(container.Name, r.context.ProjectName+"_")
	logger := r.context.LoggerFactory.Create(log_name)

	for {
		messageType, bytes, err := conn.ReadMessage()
		if messageType != websocket.TextMessage {
			continue
		}

		if err == io.EOF {
			return
		} else if err != nil {
			logrus.Errorf("Failed to read log: %v", err)
			return
		}

		if len(bytes) <= 3 {
			continue
		}

		if bytes[len(bytes)-1] != '\n' {
			bytes = append(bytes, '\n')
		}
		message := bytes[3:]

		if "01" == string(bytes[:2]) {
			logger.Out(message)
		} else {
			logger.Err(message)
		}
	}
}
```

**Comment by faddat** [comment]
Basically: 

Rancher-compose never seems to terminate after running.  Is this a ctrl-p + ctrl-q or something altogether different?

**Comment by ibuildthecloud** [comment]
When you run `rancher-compose` just add -d to not pipe logs.  Otherwise it will just pipe logs forever until you ctrl-c

**Comment by ds0nt** [comment]
Thanks, that worked. Is there any way to set a dns that would resolve to a rancher-composed container?

**Comment by ds0nt** [comment]
Also, I admire your artwork, it's absolutely fantasticly architected.

**Comment by deniseschannon** [comment]
@ds0nt Is there anything still specifically open in this issue? It's hard for me to follow.

If there is, please re-open and remind me what hte specific issue is.

**Comment by ds0nt** [comment]
it is resolved now, thanks.
