### ISSUE TITLE
Rancher API, pull and update deployment

### ISSUE THREAD

**Issue by san4io** [rancher/rancher#15781]
Hello,
I've tried to find some endpoint to trigger deployment image pull and update, but i found none.
I think it would be nice to have some kind of endpoint, where we can trigger those actions.
For example something like:
```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
https://rancher.hexito.com/v3/project/c-sp7pd:p-kqqtr/workloads/deployment:hexito:hexito/update
```
My solution for now:
1. imagePullPolicy: Always
2. I take all big json from api, add annotation like timestamp, and with every deploy, I PUT a new timestamp, that's why rancher thinks it's new config and pulls and updates deployment.

Currently deployment script look like this:
![image](https://user-images.githubusercontent.com/12079341/45921497-65c15480-bebf-11e8-9e85-00e499ede53a.png)

Use case:
**I as DevOps would like to trigger image pull and update on rancher via curl, and don't track other deployment configurations in my deploy script.** 

Explanation: If I change something in rancher via UI, i need to track down json change and update my deploy script with up to date json. With my suggestion we won't have any overhead of keeping up to date json.

Or maybe you already have solution. And I just missed something?

P.S. I know that I can get current configuration with GET, then write down script which finds dt annotation and replaces it, but you know.. Devs are so lazy.. :)

I think this kind of feature would help many people in theirs CD process.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/23053
