### ISSUE TITLE
Pipeline is not cloning repo from github

### ISSUE THREAD

**Issue by laser-dev-support** [rancher/rancher#15782]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

**Docker version: 1.13.1

**Operating system and kernel: centos7 3.10.0-862.11.6.el7.x86_64

**Type/provider of hosts: VM

**Setup details: single node rancher

**Environment Template: k8s

**Steps to Reproduce: configured github access to users and repo, I am trying to create a pipeline to push to dockerhub. I get the "timeout get build info" when trying to clone from github repo. I am trying in the default cluster project but this also happens if I do it in another project.  I tried to use also different namespaces but nothing to do. I followed every single steps listed here:
https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/

**Results:**
timeout get build info at clone stage and no other stage is executed

<img width="502" alt="screen shot 2018-09-23 at 16 55 28" src="https://user-images.githubusercontent.com/42391822/45929412-833efe80-bf51-11e8-9578-c6d2a2d6382b.png">

**Comment by gitlawr** [comment]
Thanks for the report! It would be appreciate if you can provide more info to help diagnose:
1. How do you add the cluster, custom/import or cloud provider drivers
2. Can you do a `eval 'kubectl get pod -n '{cattle-system,cattle-pipeline}';'` to check the pods
3. When a build is triggered, do you see new `jenkins-slave-xxx` pods spinning up in `cattle-pipeline` namespace
4. Do you see additional error logs besides the timeout info in rancher server container log

**Comment by laser-dev-support** [comment]
Hi sorry for the late reply

1. just followed the [https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/](instructions) to create a Custom cluster (having at the moment just 1 node for computation and 1 node for the rancher controller.
1.
```bash
> eval 'kubectl get pod -n '{cattle-system,cattle-pipeline}';'
NAME                                    READY     STATUS    RESTARTS   AGE
cattle-cluster-agent-5b876b67c6-xrj2m   1/1       Running   0          33d
cattle-node-agent-zs6zj                 1/1       Running   0          33d
NAME                      READY     STATUS    RESTARTS   AGE
jenkins-9bb5fbdbf-75qfl   1/1       Running   0          20d
```
3. Only if I do it in the default project
1. I see a long stream of errors like:
```bash
2018/10/05 02:01:21 [INFO] respData:{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
2018/10/05 02:01:21 [ERROR] PipelineController p-bw2zt/p-7dxhm [pipeline-controller] failed with : {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
2018/10/05 02:02:13 [INFO] respData:{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
2018/10/05 02:02:13 [ERROR] PipelineController p-bw2zt/p-7dxhm [pipeline-controller] failed with : {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
2018-10-05 02:04:58.357712 I | mvcc: store.index: compact 2715552
2018-10-05 02:04:58.613327 I | mvcc: finished scheduled compaction at 2715552 (took 238.228847ms)
2018-10-05 02:09:58.396169 I | mvcc: store.index: compact 2715881
2018-10-05 02:09:58.642782 I | mvcc: finished scheduled compaction at 2715881 (took 231.839548ms)
E1005 02:13:19.348687       5 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
2018-10-05 02:14:58.428724 I | mvcc: store.index: compact 2716212
2018-10-05 02:14:58.674830 I | mvcc: finished scheduled compaction at 2716212 (took 231.245339ms)
2018/10/05 02:18:53 [INFO] respData:{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
2018/10/05 02:18:53 [ERROR] PipelineController p-bw2zt/p-7dxhm [pipeline-controller] failed with : {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
2018-10-05 02:19:58.462092 I | mvcc: store.index: compact 2716541
2018-10-05 02:19:58.723241 I | mvcc: finished scheduled compaction at 2716541 (took 241.680337ms)
E1005 02:20:24.450737       5 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
2018-10-05 02:24:58.502530 I | mvcc: store.index: compact 2716872
2018-10-05 02:24:58.756304 I | mvcc: finished scheduled compaction at 2716872 (took 232.521221ms)
2018-10-05 02:29:58.544350 I | mvcc: store.index: compact 2717201
2018-10-05 02:29:58.795722 I | mvcc: finished scheduled compaction at 2717201 (took 237.044737ms)
```

it might be a problem with my configuration, but I followed the guide. Consider that I set up github authentication so that is actually working.

thanks a lot for your support

**Comment by deniseschannon** [comment]
In 2.1, we re-did pipelines. If you still have issues on a later release, please open a new issue.
