### ISSUE TITLE
prometheus-adapter deployment fails

### ISSUE THREAD

**Issue by tboemker-bkfs** [rancher/rancher#15780]
I tried to launch prometheus-adapter from Helm Stable and saw this error:
2018/09/22 17:42:41 [ERROR] AppController p-kjdsd/prometheus-adapter [helm-controller] failed with : Kubectl apply failed. Error: error: error validating "app-template": error validating data: [ValidationError(Deployment.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(Deployment.spec.template.spec.securityContext): unknown field "capabilities" in io.k8s.api.core.v1.PodSecurityContext]; if you choose to ignore these errors, turn validation off with --validate=false

Where does --validate=false go?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by alena1108** [comment]
@tboemker-bkfs could you share your helm template (omitting sensitive info of course)

**Comment by loganhz** [comment]
`capabilities` field is not valid in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#podsecuritycontext-v1-core
It looks like it is introduced in https://github.com/helm/charts/pull/7183
There is no way to set `--validate=false`
