### ISSUE TITLE
Cluster Logging: Elasticsearch: Allow tuning number of shards

### ISSUE THREAD

**Issue by nlowe** [rancher/rancher#15791]
**Rancher versions:**
rancher/server or rancher/rancher: `2.0.8`
rancher/agent or rancher/rancher-agent: `2.0.8`

**Infrastructure Stack versions:**
kubernetes (if applicable): `v1.11.2`

**Docker version: (`docker version`,`docker info` preferred)**

<details>

<summary>Version</summary>

```txt
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

</details>

<details>

<summary>Info</summary>

```txt
Containers: 53
 Running: 37
 Paused: 0
 Stopped: 16
Images: 35
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: RDV-004367
ID: 4SOE:44VI:TJ5O:BY5G:C2XP:X5HG:NLEU:VRFB:D5IJ:3JH7:WYP3:UBM5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```txt
# /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```txt
# uname -r
4.4.0-134-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-Metal (vSphere VMs)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

1. Deploy a k8s cluster
2. Enable logging to external elasticsearch

**Results:**

I noticed the following in the elasticsearch logs:

```txt
[2018-09-24T20:11:03,693][WARN ][o.e.d.c.m.MetaDataCreateIndexService] the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template
```

It would be nice to be able to specify the number of shards for the indices rancher creates directly from rancher.

**Comment by seag-rvc** [comment]
While I'm not an Elasticsearch expert I faced the same issue. I think a better option for you would be to set number of shards in index template and bump up template order to something like 100. [https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html)

```
PUT /_template/template_1
{
    "index_patterns" : ["*"],
    "order" : 100,
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "_doc" : {
            "_source" : { "enabled" : false }
        }
    }
}
```

**Comment by aiwantaozi** [comment]
Could add a template to configure the number of shards. 
Steps:
1. create a template, put it in a configmap or secret, more details here https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html
https://github.com/uken/fluent-plugin-elasticsearch#index-templates
sample:
```
{
  "mappings": {
    "_default_": {
      "_all": { "enabled": false }, 
      "_source": { "compress": true },
      "properties" : {
        "event_data": { "type": "object", "store": "no" },
        "@fields": { "type": "object", "dynamic": true, "path": "full" }, 
        "@message": { "type": "string", "index": "analyzed" },
        "@source": { "type": "string", "index": "not_analyzed" },
        "@source_host": { "type": "string", "index": "not_analyzed" },
        "@source_path": { "type": "string", "index": "not_analyzed" },
        "@tags": { "type": "string", "index": "not_analyzed" },
        "@timestamp": { "type": "date", "index": "not_analyzed" },
        "@type": { "type": "string", "index": "not_analyzed" }    
      }   
    }
  },
  "settings": {
    "index.cache.field.type" : "soft",
    "index.refresh_interval": "5s",
    "index.store.compress.stored": true,
    "index.number_of_shards": "3", 
    "index.query.default_field": "querystring", 
    "index.routing.allocation.total_shards_per_node": "2"
  }, 
  "template": "logstash-*"
}
```
2. enable logging with advance mode, under logging page, click elasticsearch -> edit as file, input configure, and template path
sample:
```
 <match *>
     @type elasticsearch
      host            logs.google.com
      port            777
      scheme          https
      path            /es/
      user            john
      password        doe
      template_name   logstash
      template_file   /var/template/template_file
</match *>
```

3. edit fluentd deployment, mount the configmap/secret included template to path configured in the step 2 template_file

**Comment by paynejacob** [comment]
With logging v2 introduced in rancher 2.5, support was added for using index templates.  In this template you can specify the number of shards.  Additionally you can configure rolling over to multiple indices.

https://rancher.com/docs/rancher/v2.x/en/logging/v2.5/
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/elasticsearch/#elasticsearch-template_name
