### ISSUE TITLE
[2.0.8] Rancher cacert changes and becomes tabbed which makes it invaild

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15794]
I am running Rancher 2.0.8 in a Kubernetes HA (3 nodes) cluster on CoreOS. I am having an issue where the Rancher servers cacerts lines get tabs and becomes invalid. I am still trying to figure out if there is a pattern in the Rancher servers logs. The rancher server pod isn't restarting so I am not sure why the cacerts gets modified.

**Comment by Oats87** [comment]
Is this an RKE all-in-one installation or Helm installation?

**Comment by mitchellmaler** [comment]
@Oats87 This is with the RKE installer with the rancher server deploy addon.

**Comment by Oats87** [comment]
@mitchellmaler What operating system are you using the call RKE? Are there tabs in the RKE cluster config file that may be getting put into place?

**Comment by mitchellmaler** [comment]
Each time I have used my MacOS laptop to run RKE up using the latest stable version 'v0.1.9'.
I haven't run RKE up since the 2.0.8 release so it must be something in the background running that changes the value. I am grabbing all the logs now (rancher and cluster) to an elk stack so seeing if I can find a pattern just waiting for it to happen again.

**Comment by superseb** [comment]
What template file did you use? Is `cacerts.pem` configured or is it started with `--no-cacerts`? Was the value of `cacerts` in Settings/API ever manually edited?

**Comment by mitchellmaler** [comment]
So I dug a little more and there was a modification to the configmap when it was applied last rke up and I can see it is actually tabbed incorrectly. So the issue is all on my side and nothing to do with Rancher.
