### ISSUE TITLE
Add host (ec2) fails 'Maximum number of retries (60) exceeded'

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#1579]
This looks like a docker-machine issue but basically I have had no luck repeatedly in adding an EC2 host, in this case Ubuntu 15.04.
Here is the server cattle debug log: https://gist.github.com/flaccid/988b6979ab61e133af42

I cannot get the agent log on the host as the process is not complete to be able to download the machine config. The instance booted fine though.

This is all fresh with v0.28.0.

![screen shot 2015-07-18 at 5 57 54 pm](https://cloud.githubusercontent.com/assets/131730/8760892/db9e2c00-2d77-11e5-99c1-1ed341356a3c.png)

**Comment by wlan0** [comment]
@flaccid This is a docker-machine error message. It means that docker-machine was not able to establish a SSH connection to your host. 

If you're using a non-standard security group, make sure that inbound traffic to port 22 is opened.

**Comment by flaccid** [comment]
Thanks @wlan0. I have a feeling that it may of been a problem with DO or network reachability at the time. TCP ingress definitely open for SSH. Closing out for now, the next day it worked ok.
