### ISSUE TITLE
Is there a way to assign an ID to compute nodes which is persistent across agent relaunches

### ISSUE THREAD

**Issue by usmanismail** [rancher/rancher#158]
The API to launch containers on a compute node requires a node id (Ih1,Ih2 and so on)  instead of names like moria, mordor etc. However, the ID is not easily available in the UI you have to click *View in API* for the node to lookup the ID. In addition the ids could change and hence scripts need to be changed to update for new ids if agents are relaunched.
   
![screen shot 2015-03-05 at 1 39 45 pm](https://cloud.githubusercontent.com/assets/204682/6511809/21659e1c-c33d-11e4-8d10-317d5914f6bd.png)

It would be good if we could do one of the following:
1) Use name as ID
2) Allow the use of name in the API instead of ID
3) Allow the user to specify the id when launching compute nodes.

This way the scripts I am writing to bring up the entire cluster in one go can reliably put the same containers on the same nodes.

**Comment by vincent99** [comment]
@usmanismail With the addition of scheduling/affinity rules a while ago you can accomplish this by putting a label on each host with `city_of_middle_earth=moria` and tell containers to go to a host with that label.

Also FYI the `1h42` IDs are in the UI path if you hover on a host link or are looking at a host, so you can see them without actually visiting the API.
