### ISSUE TITLE
Metrics server cannot be removed from existing cluster

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15800]
Version: master 9/25

**Steps to Reproduce:**
1. Create custom cluster with `Metrics Server Monitoring` enabled
1. Add nodes
1. Edit cluster and set `Metrics Server Monitoring` to disabled
1. Cluster goes into Updating state and finishes

**Results:**
Metrics server is not removed

**Comment by sangeethah** [comment]
Tested with master build from Feb 2.

1. Create DO cluster with `Metrics Server Monitoring` enabled
2. Add nodes and wait for it to become active.
3. Edit cluster and set `Metrics Server Monitoring` to disabled
4. Cluster goes into Updating state and finishes

Following message is presented to the user:
```	
This cluster is currently Updating.
[ingress] Removing installed metrics server
```

`Metrics server` gets deleted from `kube-system` namespace as expected.


There is a big delay seen in cluster getting to "updating" state which is tracked in https://github.com/rancher/rancher/issues/17865
