### ISSUE TITLE
Node not Starting with new Version of RancherOS (1.4.1)

### ISSUE THREAD

**Issue by miclefebvre** [rancher/rancher#15808]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

**Docker version: (`docker version`,`docker info` preferred)** https://releases.rancher.com/install-docker/17.03.sh

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** RancherOS 1.4.1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**VSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single Node Rancher

**Steps to Reproduce:**
Since updating to the new version of RancherOS the new nodes created with my node template are never ready even if RancherOS finished booting.

Rolling back to 1.4.0 fixed my problem.

**Comment by niusmallnan** [comment]
Hi @miclefebvre ,
1. Which ISO did you use, can you share your node template?
2. Did you set up a special cloud-config?

@kingsd041 Can you help to confirm this issue? We happen to have a vsphere setup in our office.

**Comment by miclefebvre** [comment]
The Vm ware iso.

No cloud config.

**Comment by miclefebvre** [comment]
I started a new node with the version 1.4.1 to add some info.
When RancherOS is booted, Rancher display this error and after that restart the process of redownloading the image and starting an new RancherOS


2018/09/26 20:03:51 [ERROR] NodeController c-7pj5f/m-pbgvp [node-controller] failed with : Error creating machine: Error in driver during machine creation: ServerFaultCode: The session is not authenticated.
2018/09/26 20:03:51 [INFO] NodeController c-7pj5f/m-pbgvp completed with dropped err: [node-controller] failed with : Error
2018/09/26 20:03:52 [INFO] NodeController c-7pj5f/m-pbgvp completed with dropped err: [node-controller] failed with : Error
2018-09-26 20:04:06.581271 I | mvcc: store.index: compact 7994560
2018-09-26 20:04:06.809846 I | mvcc: finished scheduled compaction at 7994560 (took 216.358325ms)
2018/09/26 20:05:53 [ERROR] NodeController c-7pj5f/m-pbgvp [node-controller] failed with : failed to remove finalizer on c-7pj5f:m-pbgvp

**Comment by rootwuj** [comment]
Hi @miclefebvre ,
I verified RancherOS 1.4.1 and created the cluster successfully according to the way you created it.

@niusmallnan This issue has not been reproduced.

**Comment by miclefebvre** [comment]
@rootwuj  If I use the exact same config but only with this line instead. It works:
"boot2dockerUrl": "https://releases.rancher.com/os/v1.4.0/rancheros-vmware.iso",

The config that is not working:
{
"amazonec2Config": null,
"annotations": { },
"baseType": "nodeTemplate",
"created": "2018-07-24T17:40:59Z",
"createdTS": 1532454059000,
"creatorId": "user-lp692",
"driver": "vmwarevsphere",
"engineEnv": { },
"engineInsecureRegistry": [ 
"containerregistry.registry.com",
],
"engineInstallURL": null,
"engineLabel": { },
"engineOpt": { },
"engineRegistryMirror": null,
"id": "user-lp692:nt-p4t9g",
"labels": { },
"links": {
"nodePools": "…/v3/nodePools?nodeTemplateId=user-lp692%3Ant-p4t9g",
"nodes": "…/v3/nodes?nodeTemplateId=user-lp692%3Ant-p4t9g",
"remove": "…/v3/nodeTemplates/user-lp692:nt-p4t9g",
"self": "…/v3/nodeTemplates/user-lp692:nt-p4t9g",
"update": "…/v3/nodeTemplates/user-lp692:nt-p4t9g"
},
"name": "vSpereWorkerMem",
"removed": null,
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "nodeTemplate",
"useInternalIpAddress": true,
"uuid": "b9ca8d8d-8f68-11e8-b67c-0242ac110002",
"vmwarevsphereConfig": {
"boot2dockerUrl": "https://releases.rancher.com/os/latest/rancheros-vmware.iso",
"cfgparam": [
"disk.enableUUID=TRUE"
],
"cloudinit": "",
"cpuCount": "4",
"datacenter": "",
"datastore": "datastore1",
"diskSize": "20000",
"folder": "",
"hostsystem": "",
"memorySize": "4096",
"network": [
"VM Network"
],
"pool": "",
"username": "myusername",
"vcenter": "192.168.0.1",
"vcenterPort": "443"
}

**Comment by kingsd041** [comment]
@miclefebvre  Hey, I re-verified it in my environment, my cluster works very well.
Here is my template configuration:
```
{
"amazonec2Config": null,
"annotations": { },
"baseType": "nodeTemplate",
"created": "2018-09-29T05:36:31Z",
"createdTS": 1538199391000,
"creatorId": "user-5hjhb",
"driver": "vmwarevsphere",
"engineEnv": { },
"engineInstallURL": null,
"engineLabel": { },
"engineOpt": { },
"engineRegistryMirror": null,
"id": "user-5hjhb:nt-t22xq",
"labels": { },
"links": {
"nodePools": "…/v3/nodePools?nodeTemplateId=user-5hjhb%3Ant-t22xq",
"nodes": "…/v3/nodes?nodeTemplateId=user-5hjhb%3Ant-t22xq",
"remove": "…/v3/nodeTemplates/user-5hjhb:nt-t22xq",
"self": "…/v3/nodeTemplates/user-5hjhb:nt-t22xq",
"update": "…/v3/nodeTemplates/user-5hjhb:nt-t22xq"
},
"name": "tem-mirror",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "nodeTemplate",
"useInternalIpAddress": true,
"uuid": "9ee2fd65-c3a9-11e8-9020-0242ac110002",
"vmwarevsphereConfig": {
"boot2dockerUrl": "http://192.168.1.69/ros/rancheros-vmware-141.iso",
"cfgparam": null,
"cloudinit": "http://192.168.1.69/ros/cloud-config.yml",
"cpuCount": "2",
"datacenter": "",
"datastore": "",
"diskSize": "20000",
"folder": "",
"hostsystem": "",
"memorySize": "3072",
"network": null,
"pool": "",
"username": "root",
"vcenter": "192.168.1.113",
"vcenterPort": "443"
}
}
```
I suspect that it may be related to `"engineInsecureRegistry": ["containerregistry.registry.com",]`, you can move the registry configuration to the cloud-config file and specify the cloudinit parameters in the template.
Just like this:
![image](https://user-images.githubusercontent.com/19684717/46241923-6728da80-c3f3-11e8-93e5-73636da3fe5c.png)

http://192.168.1.69/ros/cloud-config.yml
```
#cloud-config
rancher:
  registry_auths:
    https://index.docker.io/v1/:
      auth: dXNlcm5hbWU6cGFzc3dvcmQ=
ssh_authorized_keys:
  - ssh-rsa AAAA...
```
Reference document:
https://rancher.com/docs/os/v1.x/en/installation/configuration/private-registries/
