### ISSUE TITLE
[2.1.0-rc4] Cannot create nodes in vsphere-backed cluster, error on PUT guestFile?id=&token call

### ISSUE THREAD

**Issue by pmcanseco** [rancher/rancher#15805]
-some ip addresses and hostnames edited for anonymity-

**Rancher versions:**
rancher/server or rancher/rancher: v2.1.0-rc4 (also happens on v2.0.8)
rancher/agent or rancher/rancher-agent: N/A

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): v1.11.3-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)** 
ON THE HOST WHERE rancher/rancher:v2.1.0-rc4 IS RUNNING:
```
Containers: 54
 Running: 28
 Paused: 0
 Stopped: 26
Images: 26
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.85GiB
Name: host2
ID: T7DC:VQBM:NGYT:J2IP:P7OA:SIUR:HZBY:JC76:NCBZ:BL5D:VYYI:2H6X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://proxy.corp.com:80/
HTTPS Proxy: http://proxy.corp.com:80/
No Proxy: localhost,127.0.0.1,host1,host2,host3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 host1:5555
 host2:5000
 host3:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ uname -r
4.4.0-21-generic
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VSPHERE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

1. docker run rancher/rancher:v2.1.0-rc4  with environment variables for proxy settings.
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 \
-e HTTP_PROXY="http://proxy.corp.com:80"  \
-e HTTPS_PROXY="http://proxy.corp.com:80" \
-e NO_PROXY="localhost,127.0.0.1,0.0.0.0,192.168.0.0/16,.corp.com,*corp.com,host2" \
-e http_proxy="http://proxy.corp.com:80"  \
-e https_proxy="http://proxy.corp.com:80" \
-e no_proxy="localhost,127.0.0.1,0.0.0.0,.corp.com,*corp.com,host2" \
rancher/rancher:v2.1.0-rc4
```
2. Create cluster with vsphere as node provider
3. add node template connecting to vsphere, one node template for each three node roles
4. use rancheros as the ISO URL
5. also add proxy settings to docker options in the node template
6. create the cluster, observe one node is created in vsphere and starts booting rancherOS
7. the vm boots to rancherOS successfully
8. the rancher/rancher docker logs show the following:

```
2018/09/25 17:05:56 [INFO] stdout: (auto-rancher2-kube-1) Generating SSH Keypair...
2018/09/25 17:05:59 [INFO] stdout: (auto-rancher2-kube-1) Creating VM...
2018/09/25 17:05:59 [INFO] stdout: (auto-rancher2-kube-1) Uploading Boot2docker ISO ...
2018/09/25 17:06:15 [INFO] stdout: (auto-rancher2-kube-1) adding network: VM Network
2018/09/25 17:06:15 [INFO] stdout: (auto-rancher2-kube-1) Reconfiguring VM
2018/09/25 17:06:16 [INFO] stdout: (auto-rancher2-kube-1) Setting disk.enableUUID to TRUE
2018/09/25 17:06:21 [INFO] stdout: (auto-rancher2-kube-1) Waiting for VMware Tools to come online...
2018/09/25 17:08:09 [INFO] stdout: (auto-rancher2-kube-1) Provisioning certs and ssh keys...
2018/09/25 17:08:11 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2018/09/25 17:08:11 [INFO] stdout: 
2018/09/25 17:08:12 [INFO] Generating and uploading node config auto-rancher2-kube-1
2018/09/25 17:08:12 [ERROR] NodeController c-s444n/m-vc9pj [node-controller] failed with : Error creating machine: Error in driver during machine creation: Put https://<node-ip>:443/guestFile?id=12&token=52f0b99e-a418-3dd9-83e6-d563edb1ebc412: EOF
2018/09/25 17:08:12 [INFO] Generating and uploading node config 
2018-09-25 17:08:25.727878 I | mvcc: store.index: compact 1177
2018-09-25 17:08:25.729882 I | mvcc: finished scheduled compaction at 1177 (took 1.41921ms)
```

And the node page in the rancher/rancher webgui shows the following error:
```Error creating machine: Error in driver during machine creation: Put https://<node-ip>:443/guestFile?id=12&token=52f0b99e-a418-3dd9-83e6-d563edb1ebc412: EOF```

executing the following from within the rancher/rancher container shows that it is possible to reach the url in question, but only when ignoring the proxy AND ignoring self-signed certs:
```
/var/lib/rancher# curl https://<node-ip>:443
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to <node-ip>:443 

/var/lib/rancher# curl --noproxy "*" https://<node-ip>:443
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

/var/lib/rancher# curl --noproxy "*" -k https://<node-ip>:443
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf8">
    <meta http-equiv="refresh" content="0;URL='/ui'"/>
</head>
</html>
```

**Results:**
Cannot create any nodes in a vsphere-backed cluster. It looks like the go agent is ignoring system proxy settings when it runs the REST PUT ```https://<node-ip>:443/guestFile?id=12&token=52f0b99e-a418-3dd9-83e6-d563edb1ebc412``` command. 

Any help is greatly appreciated!

**Comment by sebastienminne** [comment]
any luck with this issue ? 
facing the exact same at the moment

**Comment by pmcanseco** [comment]
I actually got further by changing to the latest stable release at the
time. I only saw the issue specifically on 2.1.0-rc4 and not again since.
