### ISSUE TITLE
Add notifier for Microsoft Teams

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15802]
Ability to create notifier for Microsoft Teams

gzrancher/rancher#10701

gzrancher/rancher#7373

**Comment by aiwantaozi** [comment]
Now alertmanager not support microsoft teams as build in, if need we may need deploy a webhook server for it.

**Comment by se-achiu** [comment]
We are also looking to have this feature

**Comment by Tejeev** [comment]
Microsoft Teams accepts only one of:
1. A plain text blob
2. Microsoft card format

Deploying the workaround pod [0] in the Rancher cluster then adding an Ingress that points to the service that points to the pod that restructures the alert and relays it to MT introduces too much room for error and latency for something that could be a critical alert.

[0] https://github.com/idealista/prom2teams

**Comment by loganhz** [comment]
Related PRs:

https://github.com/rancher/types/pull/1076 
https://github.com/rancher/system-charts/pull/156 
https://github.com/rancher/rancher/pull/25251 
https://github.com/rancher/ui/pull/3737

**Comment by mscbpi** [comment]
> Microsoft Teams accepts only one of:
> 
> 1. A plain text blob
> 2. Microsoft card format
> 
> Deploying the workaround pod [0] in the Rancher cluster then adding an Ingress that points to the service that points to the pod that restructures the alert and relays it to MT introduces too much room for error and latency for something that could be a critical alert.
> 
> [0] https://github.com/idealista/prom2teams

Deployed prom2teams, successfully tested it by curling the service, but it does not work from rancher, it returns 500. Looks like rancher is not sending a message compatible with prom2teams (rancher 2.4)

**Comment by mscbpi** [comment]
> > Microsoft Teams accepts only one of:
> > 
> > 1. A plain text blob
> > 2. Microsoft card format
> > 
> > Deploying the workaround pod [0] in the Rancher cluster then adding an Ingress that points to the service that points to the pod that restructures the alert and relays it to MT introduces too much room for error and latency for something that could be a critical alert.
> > [0] https://github.com/idealista/prom2teams
> 
> Deployed prom2teams, successfully tested it by curling the service, but it does not work from rancher, it returns 500. Looks like rancher is not sending a message compatible with prom2teams (rancher 2.4)
> 
> `2020-05-07 14:29:55,980 - werkzeug - INFO - 10.42.7.0 - - [07/May/2020 14:29:55] "POST /v2/Connector HTTP/1.1" 500 - 2020-05-07 14:29:55,985 - werkzeug - ERROR - Error on request: Traceback (most recent call last): File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 2292, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1815, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.12.1-py3.5.egg/flask_restplus/api.py", line 583, in error_router return original_handler(e) File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.12.1-py3.5.egg/flask_restplus/api.py", line 583, in error_router return original_handler(e) File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1718, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/_compat.py", line 35, in reraise raise value File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.12.1-py3.5.egg/flask_restplus/api.py", line 325, in wrapper resp = resource(*args, **kwargs) File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/views.py", line 88, in view return self.dispatch_request(*args, **kwargs) File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.12.1-py3.5.egg/flask_restplus/resource.py", line 44, in dispatch_request resp = meth(*args, **kwargs) File "/usr/local/lib/python3.5/site-packages/prom2teams-2.5.2-py3.5.egg/prom2teams/app/versions/v2/namespace.py", line 26, in post alerts = self.schema.load(request.get_json()) File "/usr/local/lib/python3.5/site-packages/marshmallow-3.0.0rc6-py3.5.egg/marshmallow/schema.py", line 707, in load postprocess=True, File "/usr/local/lib/python3.5/site-packages/marshmallow-3.0.0rc6-py3.5.egg/marshmallow/schema.py", line 867, in _do_load raise exc marshmallow.exceptions.ValidationError: {'_schema': ['Invalid input type.']}`

Actually the test fails when configuring the notifier, but the notifier works. Do we really need an ingress or would rancher/altermanager access its ClusterIP?

**Comment by mscbpi** [comment]
> Microsoft Teams accepts only one of:
> 
> 1. A plain text blob
> 2. Microsoft card format
> 
> Deploying the workaround pod [0] in the Rancher cluster then adding an Ingress that points to the service that points to the pod that restructures the alert and relays it to MT introduces too much room for error and latency for something that could be a critical alert.
> 
> [0] https://github.com/idealista/prom2teams

We don't need ingress, we can access the prom2teams service through its clusterIP or internal dns name. However when configuring the notifier, the webhook test fails, while it works in the end when configured on alert rules.

**Comment by bmdepesa** [comment]
Tested MS Teams notifier with the build info from this comment: https://github.com/rancher/rancher/pull/27716#issuecomment-659226947

I was able to see alerts fired successfully through the MS teams notifier.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4-head f6ff6a754

* Create a cluster
* In teams, add the `Incoming Webhook` connector and retrieve the webhook URL
* Create a notifier selecting MS Teams using the webhook
* `Test` notification succeeds
* Add a cluster alert group to alert on pod events
* Deploy some pods
* Notifications are sent to MS Teams correctly

![Screen Shot 2020-07-23 at 3 40 19 PM](https://user-images.githubusercontent.com/21316915/88345723-729d7200-ccfb-11ea-9659-3b4b7912d617.png)

* Re-opening until this can be tested on master

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4-head 3e543f7c4
rancher/rancher:master-head e20f472d4

* Create a cluster
* In teams, add the `Incoming Webhook` connector and retrieve the webhook URL
* Create a notifier selecting MS Teams using the webhook
* `Test` notification succeeds
* Add a cluster alert group to alert on pod events
* Deploy some pods
* Notifications are sent to MS Teams correctly
