### ISSUE TITLE
Workloads with ownerReferences pointing to CRD do not show in UI

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#15804]
**Rancher versions:**
rancher/rancher: master on 9/24/2018

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Imported GKE `v1.10.7-gke.2` cluster. 

**Steps to Reproduce:**

1. Create a GKE cluster through `gcloud` or console.
2. Import GKE cluster.
3. Launch an Application through the GCP Application Marketplace.

Pods don't show in the default `Group By Namespace/Workload` view
![image](https://user-images.githubusercontent.com/5324639/46031268-02e9dc00-c0be-11e8-88bb-79962eef10ea.png)

Pods will show up in kubectl or in rancher workloads in the the flat list view 
![image](https://user-images.githubusercontent.com/5324639/46031307-26148b80-c0be-11e8-8d45-0122bc5b13a5.png)

**Comment by superseb** [comment]
I think I have seen this before and I think it happens because the ownerReferences is linking to a CRD resource:

```
$ kubectl get statefulset -o json | jq .items[].metadata.ownerReferences
[
  {
    "apiVersion": "app.k8s.io/v1beta1",
    "blockOwnerDeletion": true,
    "kind": "Application",
    "name": "nginx-1",
    "uid": "e90b28c8-c1cb-11e8-a76b-42010aa40fd0"
  }
]
```

**Comment by superseb** [comment]
Same behavior is seen when deploying prometheus-operator

**Comment by jiaqiluo** [comment]
### Reproduction
**Rancher version**: v2.1.1
**Type/provider of hosts**:  Imported GKE v1.10.7-gke.6 cluster
**Steps** : 
1. Create a GKE cluster through gcloud.
1. Import GKE cluster.
1. Launch Applications(nginx, prometheus, and wordpress) through the GCP Application Marketplace.

**Result**: 
Pods don't show in the default `Group By Namespace/Workload` or `Group by Workload` view, but shows in the `flat list` and `Group by Node` .

### Validation 1
**Rancher version**: v2.1.2-rc2
**Type/provider of hosts**:  Imported GKE v1.10.7-gke.6 cluster
**Steps** : 
1. Create a GKE cluster through gcloud.
1. Import GKE cluster.
1. Launch Applications(nginx, prometheus, and wordpress) through the GCP Application Marketplace.

**Result**: 
Pods show in `Group By Namespace/Workload`, `Group by Workload`,  `flat list` and `Group by Node`. 

### Validation 2
**Rancher version**: rancher/master, 10/30
**Type/provider of hosts**:  Imported GKE v1.10.7-gke.6 cluster
**Steps** : 
1. Create a GKE cluster through gcloud.
1. Import GKE cluster.
1. Launch Applications(nginx, prometheus, and wordpress) through the GCP Application Marketplace.

**Result**: 
Pods show in `Group By Namespace/Workload`, `Group by Workload`,  `flat list` and `Group by Node`.
