### ISSUE TITLE
AD Auth Fails with known good credentials

### ISSUE THREAD

**Issue by dahendel** [rancher/rancher#15807]
Unable to add Active Directory Authentication.

I can run ldapsearch from inside the rancher container and successfully search for users with the same user data I provide to rancher. When I attempt to test and save I get an Invalid Credentials error in the rancher logs. 

Error: `[ERROR] API error response 401 for POST /v3/activeDirectoryConfigs/activedirectory?action=testAndApply. Cause: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580`

The ldapsearch command (obviously generified):
`ldapsearch -h ad.dcserver.com -x -D "MYBIND_DN" -w "MYPASSWORD" -p 389 -b "dc=domain,dc=com" -s sub "sAMAccountName=dustin.hendel"`

I tried a workaround by adding the AD config through the API calls, and it added the config, but I still can't authenticate.

the api path: `rancher.my.server/v3/activeDirectoryConfigs/activedirectory`

api output:
```json
{

    "accessMode": "unrestricted",
    "actions": {
        "disable": "…/v3/activeDirectoryConfigs/activedirectory?action=disable",
        "testAndApply": "…/v3/activeDirectoryConfigs/activedirectory?action=testAndApply"
    },
    "allowedPrincipalIds": [
        "local://user-28lfc"
    ],
    "annotations": null,
    "baseType": "authConfig",
    "certificate": "",
    "connectionTimeout": 5000,
    "created": "2018-09-20T20:42:14Z",
    "createdTS": 1537476134000,
    "creatorId": null,
    "defaultLoginDomain": "domain.com",
    "enabled": true,
    "groupDNAttribute": "distinguishedName",
    "groupMemberMappingAttribute": "member",
    "groupMemberUserAttribute": "distinguishedName",
    "groupNameAttribute": "name",
    "groupObjectClass": "group",
    "groupSearchAttribute": "sAMAccountName",
    "id": "activedirectory",
    "labels": null,
    "links": {
        "self": "…/v3/activeDirectoryConfigs/activedirectory",
        "update": "…/v3/activeDirectoryConfigs/activedirectory"
    },
    "name": "activedirectory",
    "nestedGroupMembershipEnabled": true,
    "port": 389,
    "servers": [
        "dc01.domain.com"
    ],
    "serviceAccountUsername": "domain\\svc_rancherbind",
    "tls": false,
    "type": "activeDirectoryConfig",
    "userDisabledBitMask": 2,
    "userEnabledAttribute": "userAccountControl",
    "userLoginAttribute": "sAMAccountName",
    "userNameAttribute": "name",
    "userObjectClass": "person",
    "userSearchAttribute": "sAMAccountName|sn|givenName",
    "userSearchBase": "STRIPPED OUT",
    "uuid": "a7e5cfdc-bd15-11e8-98ac-005056bbd021"
}
```

I have gone through #12421 and #14369 and no luck. Also tried turning on/off recursive group search.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`` `admin`|
|Route|`global-admin.security.authentication.activedirectory`|

**Comment by mrajashree** [comment]
@dahendel Can you try changing your default login domain from `"domain.com"` to `domain`?

**Comment by dahendel** [comment]
@mrajashree I have tried that as well. Here is the debug output:
```
2018/09/25 18:46:09 [DEBUG] Now generating Ldap token
2018/09/25 18:46:09 [DEBUG] Now creating Ldap connection
2018/09/25 18:46:09 [DEBUG] Binding service account username password
2018/09/25 18:46:09 [ERROR] API error response 401 for POST /v3/activeDirectoryConfigs/activedirectory?action=testAndApply. Cause: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580
```

**Comment by mrajashree** [comment]
@dahendel I see. From the logs it looks like the service account bind failed, have you run the same ldapsearch command for the service account and seen it succeed?
```
ldapsearch -h ad.dcserver.com -x -D "MYBIND_DN" -w "MYPASSWORD" -p 389 -b "dc=domain,dc=com" -s sub "sAMAccountName=dustin.hendel"
```

**Comment by dahendel** [comment]
@mrajashree  Yes. When I run the ldap search with the same service account is succeeds. Also I removed special characters from the password with no luck.

**Comment by dahendel** [comment]
Changing the Login Attribute from name to sAMAccountName fixed the issue. Closing

**Comment by mrajashree** [comment]
That's great, from the API UI snapshot above it looked like it was already sAMAccountName though ` "userLoginAttribute": "sAMAccountName",`

**Comment by kishorkk91** [comment]
In my case everything was OK but I was using **Chrome Browser** and didnt work which is very strange, then I tried **Mozilla Firefox** and I can see my Rancher Dashboard,. Happy me. ; )

**Comment by joltcan** [comment]
Fun stuff. I was hitting the same bug today with rancher 2.10.0 in chrome, took me the whole day until I read @kishorkk91's comment above to try firefox, and I could add the AD account right away!
