### ISSUE TITLE
kubelet container kept restarting with "tls: failed to find any PEM data in certificate input"

### ISSUE THREAD

**Issue by abbcdfin** [rancher/rancher#15801]
**Rancher versions:**
rancher/rancher: v2.0.8
rancher/rancher-agent: v2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

4.4.0-21-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Followed the instructions to start rancher server;
2. Created custom cluster with default settings;
3. Run the suggested command to start the node;

**Results:**
The cluster stuck at "provisioning" with message:
	[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [192.0.16.76]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: getsockopt: connection refused, log: F0925 20:48:34.757338 13340 server.go:141] tls: failed to find any PEM data in certificate input

This actually happened on v2.1.0-rc4 as well.

Attached please find the screen shot and the kubelet container log.
![screenshot_2018-09-25_20-51-15](https://user-images.githubusercontent.com/28372305/46015492-ff2d7800-c104-11e8-93df-f1b0aa6acc0a.png)
[kubelet.20180925.log](https://github.com/rancher/rancher/files/2415258/kubelet.20180925.log)

**Comment by abbcdfin** [comment]
@superseb sorry for disturbing, just wondering if you have got a chance to look at this issue? Did I do something stupid?

**Comment by abbcdfin** [comment]
Hi @loganhz, just wondering is there any updates regarding this issue?

**Comment by loganhz** [comment]
Hi @abbcdfin , it's in the list. We will look at it. Thanks

**Comment by xiaoluhong** [comment]
This problem may be caused by self-signed certificates, which are verified by the following method：
`openssl s_client -connect 192.0.16.76:8443 -servername 192.0.16.76  -CAfile RootCA.crt`

If the word `OK` finally appears indicating that the certificate is correct, otherwise the certificate has a problem.

**Comment by abbcdfin** [comment]
Hi @xiaoluhong , thanks very much for helping. I've done the verification, there is no issue with the certificate.

**Comment by loganhz** [comment]
Similar issue https://github.com/rancher/rancher/issues/16332

**Comment by rootwuj** [comment]
@abbcdfin I did not reproduce this issue according to your description steps. I think the problem is still on the certificate. Can you provide detailed steps for certificate generation?

**Comment by KrzysztofMadejski** [comment]
Had the same issue as @moon03432 and @quqonlik : empty `/var/lib/kubelet/pki/kubelet.{crt, key}`. I deleted them and it worked.

Setup:
- Ubuntu 16.04 
- Docker version 18.09.4, build d14af54
```
759285ad2de4        rancher/rancher-agent:v2.2.0           "run.sh --server htt…"   8 minutes ago       Up 8 minutes                            zealous_goldberg
e9c770995135        rancher/hyperkube:v1.13.4-rancher1     "/opt/rke-tools/entr…"   3 hours ago         Up 40 seconds                           kubelet
c61bbeb58860        rancher/hyperkube:v1.13.4-rancher1     "/opt/rke-tools/entr…"   3 hours ago         Up 8 minutes                            kube-scheduler
73149b1a7873        rancher/hyperkube:v1.13.4-rancher1     "/opt/rke-tools/entr…"   3 hours ago         Up 8 minutes                            kube-controller-manager
e540c23bbe0b        rancher/hyperkube:v1.13.4-rancher1     "/opt/rke-tools/entr…"   3 hours ago         Up 8 minutes                            kube-apiserver
1ed235da7b12        rancher/coreos-etcd:v3.2.24-rancher1   "/usr/local/bin/etcd…"   3 hours ago         Up 8 minutes                            etcd
85d9a2e00d87        rancher/rancher-agent:v2.2.0           "run.sh --server htt…"   3 hours ago         Up 8 minutes                            mystifying_robinson
8d0b2a50b23c        rancher/rancher-agent:v2.2.0           "run.sh --server htt…"   3 hours ago         Up 1 second                             ragent

```

**Comment by deniseschannon** [comment]
If anyone is still facing this issue, please open a new issue. It seems the workaround of clearing out the directory is working.
