### ISSUE TITLE
Cannot add members to a project when another cluster owner has created the project

### ISSUE THREAD

**Issue by tuxiem** [rancher/rancher#15819]
**Rancher versions:**
rancher version: v.2.0.8

**Problem:**
When another cluster owner has created a new project, without providing members. Other cluster owners, cannot add members. Denied with forbidden.

**Steps:**
(Only produced on AD joined cluster)
Person A and Person B is a member of the AD Group clusterAdmins
clusterAdmins is a member of cluster XYZ as role cluster owner
Person A creates a new project DEV in the cluster without adding any members
Person B, tries to add members to project DEV
Person B gets message "projectroletemplatebindings.management.cattle.io is forbidden: User "B" cannot create projectroletemplatebindings.management.cattle.io in the namespace "DEV"

**Results:**
Only the creator of the project is able to add members to the project.

**Expected:**
All cluster owners should have full access to projects within the cluster.

**Comment by tfiduccia** [comment]
Version v2.2.0
I was able to reproduce this with the steps the user provided.  
1.  create cluster
2.  Add a group as owner with at least 2 users in it
3.  User 1 creates project
4.  User 2 tries to add to member to project user 1 created

This is only reproducible if the users are in a group.  If you add them individually it works fine.

**Comment by tfiduccia** [comment]
Another issue related to group access in clusters:  I can't see the default namespace when i create a workload.  So:
1.  Create cluster
2.  Add group with 2 users as owner
3.  Log in as one of those users
4.  Create workload

The default namespace is not in the list of namespaces, and it should be.

**Comment by cjellick** [comment]
> Another issue related to group access in clusters: I can't see the default namespace when i create a workload. So:

Unrelated. Can this be spun out to separate issue?

**Comment by cjellick** [comment]
This is probably because we dont have a handler that is watching projects to trigger re-evaluating all CRTBs in that project's cluster. If you restarted rancher, it might fix itself bc that forces all CRTBs to be resynced (run through all handlers)

**Comment by rmweir** [comment]
It is possible to repro this without using AD. (This worked fairly reliably for me but looked as though @dramich did not get the same behavior.) These were the steps followed:

1. create cluster
2. create 3 users: user1, user2, user3
3. separately add user1 and user2 as "Cluster Owner" to the cluster.
4. login to user1 and add a new project to the cluster
5. login to user2 and attempt to add user3 to the project as a member.

Result: should see same error as mentioned above

**Comment by mrajashree** [comment]
@rmweir I think the root cause behind this issue and https://github.com/rancher/rancher/issues/19589 is the same.
Cause: https://github.com/rancher/rancher/issues/19589#issuecomment-482755015

**Comment by rmweir** [comment]
this issue caused by the same bug as https://github.com/rancher/rancher/issues/19589

**Comment by jiaqiluo** [comment]
Following the same steps as the original issue describe,

the bug is reproduced in Rancher:v2.2.7
<img width="1232" alt="Screen Shot 2019-08-20 at 4 35 28 PM" src="https://user-images.githubusercontent.com/6218999/63392251-b6109300-c36a-11e9-8336-77872ee1f1f1.png">


the bug fix is validated in Rancher:master-head d66a45ecd

**Comment by jiaqiluo** [comment]
the bug fix is validated in Rancher:master-head d66a45ecd

Steps are the same as my previous comment, and now user2 can add another user as a project member successfully
