### ISSUE TITLE
high mysql cpu usage

### ISSUE THREAD

**Issue by phynias** [rancher/rancher#15811]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.22

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
/etc/os-release = rancher-os v0.7.1
uname -r = 4.4.24-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 HA rancher servers with external RDS with around 140 hosts connected.

The last week I have been noticing slowness in rancher and also odd behavior. For instance I would upgrade a service and it would stop the old containers and that was it. Never started new ones and showed the upgrade as finished.   

I started looking into the problems and noticed that mysql was extremely slow. Queries to the process_execution table for example, would take forever or just time out.  So I upgraded the aurora mysql instance from r3.large to r3.2xlarge and I am still seeing the same behavior. The db instance is constantly at 80% cpu usage and over. There is around 22 million rows in the process_execution table and queries are still slow. Having a r3.2xlarge for rancher seems overkill and expensive especially since it's doing no better than the large instance.   

Will gladly give any other info needed to help me figure out how to fix the odd behaviors and slowness. thanks!

<img width="1826" alt="screen shot 2018-09-25 at 4 39 26 pm" src="https://user-images.githubusercontent.com/10147213/46049271-58d07b00-c0e2-11e8-8a16-d32544dec435.png">

<img width="845" alt="screen shot 2018-09-25 at 4 33 11 pm" src="https://user-images.githubusercontent.com/10147213/46049281-5cfc9880-c0e2-11e8-9a2e-0c451bbf674a.png">

edit: forgot os version

**Comment by phynias** [comment]
other weird behavior we have noticed:
- host is turned off but still shows active in rancher.
- can not execute shell randomly. the window opens and then shuts immediately.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
