### ISSUE TITLE
Rancher 1.6:  the upgrade service in pipeline not work sometimes.

### ISSUE THREAD

**Issue by Jamlee** [rancher/rancher#15816]
**Rancher versions:**
rancher 1.6

**Infrastructure Stack versions:**
healthcheck
ipsec
network-services
scheduler

the upgrade service not work somtimes, the error is connecting timeout, Could  retry  the last upgrade step aotumaticlly  if connect timeout ?

![image](https://user-images.githubusercontent.com/5196641/46067281-0e660180-c1a9-11e8-8a1c-db7e6eab2704.png)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
