### ISSUE TITLE
Upgraded setup from 2.0.8->2.1.0-rc5 - Errors relating to remotedialer seen repeatedly in logs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15828]
**Rancher versions:**
Upgraded setup from 2.0.8->2.1.0-rc5 

**Steps to Reproduce:**

Fresh install of rancher server version 2.0.8
Created a custom cluster with 2 worker nodes and 1 node (With control plane and etcd).
Deploy few workloads/Ingress and ServiceDiscovery.

Upgrade rancher server version to 2.1.0-rc5.

After upgrade , following set of error messages keep constantly showing up in the rancher servers logs:

The errors are coming from the 2 worker nodes in the cluster.

```
2018/09/26 23:56:46 [INFO] Handling backend connection request [c-9gdq2:m-a89605a36aee]
2018/09/26 23:56:51 [INFO] Handling backend connection request [c-9gdq2:m-46cfe1444a11]
2018/09/26 23:56:56 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->54.244.61.104:5962: i/o timeout
2018/09/26 23:57:01 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->54.187.185.44:51832: i/o timeout
2018/09/26 23:57:13 [INFO] Handling backend connection request [c-9gdq2:m-46cfe1444a11
```

**Comment by maxkorp** [comment]
Took a closer look at this through yesterday and today and it seems like the problem resolves after a few minutes. Are you able to get this to occur continuously?

**Comment by cjellick** [comment]
Moving out of the release. Cannot consistently reproduce and the logs are at INFO level, which indicates that this is a recoverable situation.
