### ISSUE TITLE
EKS cluster provisioning fails with "message":"Cluster already exists with name: abcde"

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15823]
**Rancher versions:**
rancher/server or rancher/rancher: master

Steps:
1. Create a EKS cluster using AMIs with GPU support listed in 
https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
Use P2 nodes with GPU support

Cluster creation fails  with error  "Cluster already exists with name: abcde" as below:

<img width="1318" alt="screen shot 2018-09-25 at 4 59 52 pm" src="https://user-images.githubusercontent.com/18536626/46102610-99cc9c00-c183-11e8-8b37-fb24c703da2d.png">

Note that the cluster is active in AWS, but the nodes get rolled back. Ex below:
<img width="1083" alt="screen shot 2018-09-25 at 5 00 10 pm" src="https://user-images.githubusercontent.com/18536626/46102692-ca143a80-c183-11e8-94d1-332ef90bd126.png">

<img width="1380" alt="screen shot 2018-09-25 at 5 00 00 pm" src="https://user-images.githubusercontent.com/18536626/46102720-dc8e7400-c183-11e8-8eb5-8be8744c880a.png">

**Comment by maxkorp** [comment]
So it seems like Soumyas instance of the bug was due to hitting a limit on GPU nodes. 

Improved error messaging is described here: https://github.com/rancher/rancher/issues/14291

Fixed that, so post fix this should present with a more meaningful error message. The fix for that is here: https://github.com/rancher/kontainer-engine/pull/87

**Comment by soumyalj** [comment]
Tested with v2.1.0-rc7 . Created EKS clusters in all the regions with the updated AMIs specified in
https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
Clusters were created successfully and were functional.
