### ISSUE TITLE
launch kubectl terminal connecting

### ISSUE THREAD

**Issue by ibayue** [rancher/rancher#15829]
This request respose 400
![image](https://user-images.githubusercontent.com/11729209/46120182-13768f80-c241-11e8-9bfc-c87160c159d4.png)

*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by superseb** [comment]
Can you describe the steps to reproduce as described in https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions?

In this case, what kind of cluster? I also see `nginx/1.12.2`, how is it installed, with what config? Does it work without nginx?
