### ISSUE TITLE
Update default engine install for Node Templates to Docker 18.06 or later 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#15824]
Currently, we default the engine install to use Docker 17.03, but this should be updated to Docker 18.06 or later.

Not sure if this is a backend and/or UI change, so only making 1 ticket for now.

**Comment by cjellick** [comment]
note that the UI is going to add more items to the dropdown.

**Comment by jiaqiluo** [comment]
The enhancement is validation on rancher: master 1/28
Step:
- go to `Node Templates` ->  `Add Template` to add a new one for DO, Azure, EC2

Result:
1. Docker 18.06 is the default version
2. There is also old versions to choose from the dropdown list.
<img width="1225" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/51925089-8b99c100-23ab-11e9-89e6-43028fad2305.png">
