### ISSUE TITLE
Enable option to add/display new namespaces in selected project by default

### ISSUE THREAD

**Issue by easybi-mv** [rancher/rancher#15820]
**Rancher versions:**
rancher/rancher 2

**Comment by superseb** [comment]
Can you describe the steps you take and what happens and what you expect to happen so we can use that to determine how to handle/fix this?

**Comment by easybi-mv** [comment]
If namespaces are created externally (kubectl) they are not added to any of the projects. Is it possible to define default project for new namespaces?

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/15820
