### ISSUE TITLE
Upgraded setup from 2.0.8->2.1.0-rc5 - Etcd/Control nodes report v1.11.2 even after upgrading k8s version from v1.11.2 -> v1.11.3 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15830]
Rancher server version - Upgraded setup from 2.0.8->2.1.0-rc5 

**Steps to Reproduce:**

Fresh install of rancher server version 2.0.8
Created a EC2 cluster with 3 worker nodes and 1 etcd node and 1 control node.
Deploy few workloads/Ingress and ServiceDiscovery.

Upgrade rancher server version to 2.1.0-rc5.

Upgrade k8s version from v1.11.2 to v1.11.3.

After k8s upgrade is successful , k8s version on the Etcd/Control nodes continue to report v1.11.2 in rancher UI when Etcd/Control nodes continue to report v1.11.3 version when queried in kubectl.

```
> kubectl get nodes
NAME                STATUS    ROLES          AGE       VERSION
sangeeupgcontrol1   Ready     controlplane   4h        v1.11.3
sangeeupgetcd1      Ready     etcd           4h        v1.11.3
sangeeupgetcd2      Ready     etcd           4h        v1.11.3
sangeeupgetcd3      Ready     etcd           4h        v1.11.3
sangeeupgworker1    Ready     worker         4h        v1.11.3
sangeeupgworker2    Ready     worker         4h        v1.11.3
sangeeupgworker3    Ready     worker         4h        v1.11.3
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
>
```

<img width="1263" alt="screen shot 2018-09-26 at 8 31 29 pm" src="https://user-images.githubusercontent.com/4266958/46121975-36665c80-c1cb-11e8-82dc-547c6f3ca40a.png">

**Comment by kinarashah** [comment]
Haven't been able to reproduce, but adding version comparisons on node sync to reflect the updated info just in case.

**Comment by sangeethah** [comment]
Fresh install of rancher server version 2.0.8
Created a EC2 cluster with 3 worker nodes and 1 etcd node and 1 control node.
Deploy few workloads/Ingress and ServiceDiscovery.

Upgrade rancher server version to 2.1.0-rc7.

Upgrade k8s version from v1.11.2 to v1.11.3.
Once upgrade is complete,  Etcd/Control nodes report v1.11.3 version in rancher UI as expected.
