### ISSUE TITLE
Add rancher-compose to homebrew

### ISSUE THREAD

**Issue by richburdon** [rancher/rancher#1583]
Support installation/update of rancher-compose tools view Brew (OS/X), apt-get, etc.

brew install docker-compose
brew install rancher-compose

**Comment by faddat** [comment]
+1

**Comment by adamkdean** [comment]
+1

**Comment by adamkdean** [comment]
This should be fairly simple to be honest. Take a look at https://github.com/caskroom/homebrew-cask/blob/master/Casks/atom.rb

**Comment by alex88** [comment]
There you go https://github.com/Homebrew/homebrew/pull/43261

**Comment by deniseschannon** [comment]
From what I can tell, this looks like it's been merged in with the most recent version v0.4.0 due to  @alex88 contribution. Thanks!!

https://github.com/Homebrew/homebrew/pull/44207
