### ISSUE TITLE
Is it possible to install Rancher in a headless non-interactive mode?

### ISSUE THREAD

**Issue by 1605200517** [rancher/rancher#15834]
It seems like for installation, you need to go through a dialogue and this introduces an automation hurdle.

Is is possible to opt to some defaults e.g. via a parameter?

See also:

https://devops.stackexchange.com/questions/5022/what-are-the-two-project-layouts-offered-by-rancher-on-installation

I have also searched for a Puppet module, but there is only an old one from year 2016 so it can't be for Rancher 2.x.
https://forge.puppet.com/puppetlabs/rancher/scores

**Comment by superseb** [comment]
This is the same request as https://github.com/rancher/rancher/issues/14448, and is available in CLI v2.0.4.

```
Login to a Rancher server

Usage:
  rancher login [OPTIONS] [SERVERURL]

Options:
   --context value          Set the context during login
   --token value, -t value  Token from the Rancher UI
   --cacert value           Location of the CACerts to use
   --name value             Name of the Server
```
