### ISSUE TITLE
After K8s upgraded from 1.11.2 -> 1.11.3  , metrics and kubedns addons continue to be in v1.11.2 version.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15842]
Rancher server version - Upgraded setup from 2.0.8->2.1.0-rc5

Steps to Reproduce:

Fresh install of rancher server version 2.0.8
Created a EC2 cluster with 3 worker nodes and 1 etcd node and 1 control node.
Deploy few workloads/Ingress and ServiceDiscovery.

Upgrade rancher server version to 2.1.0-rc5.

Upgrade k8s version from v1.11.2 to v1.11.3.

After k8s is upgraded successfully ,  metrics and kubedns addons continue to be in v1.11.2 version.

<img width="1232" alt="screen shot 2018-09-27 at 9 49 50 am" src="https://user-images.githubusercontent.com/4266958/46164483-f04cdf80-c242-11e8-8a3b-d08ed3ca2130.png">

**Comment by galal-hussein** [comment]
@sangeethah this is not a bug at all, these are the addon deploy job, and the addon deploy job didn't get updated because the metrics server addon didn't get updated to the addon deploy job didn't run.
