### ISSUE TITLE
Alibaba Aliyun "Unsupport 'aliyunecs-slb-id' flag when the custom API endpoint is specified"

### ISSUE THREAD

**Issue by digitalassembly** [rancher/rancher#15848]
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 64 bits

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Alibaba Aliyun Driver

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Steps to Reproduce:**
- Create a Cluster
- Select Aliyun
- Enter credentials and api endpoint https://ecs.aliyuncs.com
- Select Jakarta as region, existing VPC, etc
- Check "private IP's"
- Set a LoadBalance SLB ID
- Create

**Results:**
-  rancher logs shows
"2018/09/27 23:42:10 [ERROR] NodeController c-gnfsn/m-b7vbf [node-controller] failed with : Error setting machine configuration from flags provided: Unsupport 'aliyunecs-slb-id' flag when the custom API endpoint is specified"

**Comment by deniseschannon** [comment]
This is an issue with the Aliyun Docker Machine Driver, which is built by Aliyun. We are only packaging what's available.
