### ISSUE TITLE
Creating new cluster using Aliyun generates API error 400 while allocating EIP

### ISSUE THREAD

**Issue by digitalassembly** [rancher/rancher#15847]
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 64 bits

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Alibaba Aliyun Driver

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Steps to Reproduce:**
- Create a Cluster
- Select Aliyun
- Enter credentials and api endpoint https://ecs.aliyuncs.com
- Select Jakarta as region, existing VPC, etc
- Uncheck "private IP's"
- Create

**Results:**
- Instance is in "creating process" at Aliyun console, but rancher logs shows
"EIP address "2018/09/27 23:57:31 [ERROR] NodeController c-jm8gw/m-zml6g [node-controller] failed with : Error creating machine: Error in driver during machine creation: test11 | Failed to allocate EIP address: Aliyun API Error: RequestId: A39EFCA0-D262-4F4A-A8D5-5729B1B7035E Status Code: 400 Code: UnknownError Message: The request processing has failed due to some unknown error." 
- Instance change status to "Stop".

**Comment by marcplouhinec** [comment]
Hi all, I just got the same error. I have checked with the product team responsible for EIP and we found the problem:
When calling the `AllocateEipAddress` API, we need to specify the `InternetChargeType` parameter to `PayByTraffic` when the selected region is not in Mainland China (the default value is `PayByBandwidth`).

It's possible to reproduce the bug via the OpenAPI Explorer: https://api.aliyun.com/#product=Vpc&search=eip&api=AllocateEipAddress&params={}&tab=DEMO&lang=PYTHON

**Comment by marcplouhinec** [comment]
For information I have studied the source code a little bit deeper and found that the EIP is allocated via this project: https://github.com/AliyunContainerService/docker-machine-driver-aliyunecs

This project needs to be modified in order to support the `InternetChargeType` parameter.

**Comment by marcplouhinec** [comment]
I have fixed the issue in [docker-machine-driver-aliyunecs](https://github.com/AliyunContainerService/docker-machine-driver-aliyunecs): I have added the `--aliyunecs-internet-charge-type` parameter and also modified the code that allocates the EIP in order to set `InternetChargeType` to `PayByTraffic` by default (so that the Docker Machine creation is now compatible with all regions in the world).

I guess the next steps to fix this issue are:
* Uploading the latest version of "docker-machine-driver-aliyunecs" on the OSS bucket "machine-driver.oss-cn-shanghai.aliyuncs.com"
* Changing [these two lines](https://github.com/rancher/rancher/blob/093db4788cbab4cc808437626bdac5e0ef8bad70/app/machinedriver_data.go#L41) in the Rancher project in order to use the new version of "docker-machine-driver-aliyunecs".

**Comment by runtman** [comment]
+1

**Comment by runtman** [comment]
@marcplouhinec Any idea if this issue is going to move or is it out of Rancher's control now?

**Comment by deniseschannon** [comment]
@runtman 
>Uploading the latest version of "docker-machine-driver-aliyunecs" on the OSS bucket "machine-driver.oss-cn-shanghai.aliyuncs.com"

this step is outside of Rancher's control

> Changing these two lines in the Rancher project in order to use the new version of "docker-machine-driver-aliyunecs".

When the bucket is updated, Rancher could update it's own code. Alternatively, you could try to build your own driver from what is out there and then add it as your own node driver into Rancher.

**Comment by deniseschannon** [comment]
If it gets updated in the OSS bucket, let me know and I can prioritize getting it fixed into Rancher's code.

**Comment by runtman** [comment]
I'll keep an eye on it, thank you.

**Comment by httpsOmkar** [comment]
Guys they update the driver at
https://docker-machine-aliyunecs-drivers.oss-cn-beijing.aliyuncs.com/docker-machine-driver-aliyunecs_linux-amd64.tgz we can do point to this one but this tgz is packed wrong I guess, so to workaround for this I extract it and upload to https://gitlab.com/omkar.yadav1/2321312/-/raw/master/docker-machine-driver-aliyunecs.linux-amd64?inline=false and started to using it in rancher

**Comment by kingsd041** [comment]
Version:
rancher/rancher:v2.4-head  04/10  commit id: 8439d8bde
UI: v2.4.14

Create two Aliyun ECS clusters with different `EIP Charge Type (Pay By Bandwidth or Pay By Traffic)`. The cluster can be created successfully, and all containers and pods under the system project are healthy and some workloads can be successfully created in the default project
Test passed, Close it.
