### ISSUE TITLE
Logging in as AzureAD user with lots of groups is slow

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15858]
Version: master 9/28

**Steps to Reproduce:**
1. Enable AzureAD
1. Login with an user which is in 50 groups

**Results:**
My initial test is 10 seconds for each login, but reported issue was 30 seconds every login. Possibly because more users in the groups (my test was 50 groups with one user each and logging in with that user)

**Comment by sangeethah** [comment]
Tested with latest rancher-server build from master.
Logging in as a user who belonged to 1001 groups takes about 4 secs.
Call from UI that was timed-- https://<ip>/v3-public/azureADProviders/azuread?action=login
