### ISSUE TITLE
Access Rancher failed when etcd cluster exceeded space quota

### ISSUE THREAD

**Issue by canhnt** [rancher/rancher#15856]
**Rancher versions:**
rancher/server or rancher/rancher: 2.08
rancher/agent or rancher/rancher-agent: 2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:         1.13.1
 API version:     1.26
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
```
```
3.10.0-862.3.3.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Etcd cluster used in Rancher used exceeded the default quota 2Gi, which caused etcd alarm.

Some node statuses
```
+----------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | c249094916d81053 | 3.1.12  | 2.0 GB  | false     |      5124 |   99427090 |
+----------------+------------------+---------+---------+-----------+-----------+------------+

+----------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | 3831e4754da30d70 | 3.1.12  | 2.1 GB  | false     |      5124 |   99427101 |
+----------------+------------------+---------+---------+-----------+-----------+------------+
```

Alarm list:
```
# etcdctl alarm list
2018-09-28 08:13:17.749408 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
memberID:11147802167718385938 alarm:NOSPACE
memberID:5759176974496765760 alarm:NOSPACE
memberID:15781308349306694651 alarm:NOSPACE
```
**Results:**

- Cannot login to Rancher UI
- Cannot access k8s clusters managed by Rancher via kubectl
- Cannot delete pods in Main rancher cluster, it created error
```
$ kubectl delete pod cattle-577747f999-fglpf
Error from server: etcdserver: mvcc: database space exceeded
```
- Error logs from cattle pod:
```
time="2018-09-28T07:19:59Z" level=info msg="Connecting to wss://rancher.tcloud.kpn.org/v3/connect with token xxx"
time="2018-09-28T07:19:59Z" level=info msg="Connecting to proxy" url="wss://rancher.tcloud.kpn.org/v3/connect"
time="2018-09-28T07:19:59Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-09-28T07:19:59Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

**Fix**
- Manual: compact and defrag etcd cluster 
- Long-term: Rancher-agent should bootstrap etcd with auto compact flag

**Comment by wernergillmer** [comment]
We just had this issue again, a defrag of etcd and we are back to having etcd working, but I suspect it will fill up and fail within the next couple of hours again.

**Comment by wernergillmer** [comment]
We have a rancher "control-plane"cluster, which runs cattle and that's about it. Then behind this cluster have have multiple other clusters, and only use the catalog service, or helm charts on those clusters. It's this control-plane cluster etcd that's having the issues, which is cause cattle pod to stop working, which then breaks the rancher UI and kubectl access to all other clusters.

**Comment by GregorPirolt** [comment]
> We just had this issue again, a defrag of etcd and we are back to having etcd working, but I suspect it will fill up and fail within the next couple of hours again.

@wernergillmer did you defrag the etcd data inside the rancher/rancher container or did you defrag the data with an etcdctl tool outside the container? Could you explain the steps to do this or point me to a source that descibes the steps? (I’m having the same problem here)
Thanks

**Comment by canhnt** [comment]
@GregorPirolt : You can take a look on [etcd maintenace](https://coreos.com/etcd/docs/latest/op-guide/maintenance.html)

**Comment by superseb** [comment]
There are troubleshooting docs on etcd here: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/#etcd-space-errors

**Comment by deniseschannon** [comment]
There is a separate issue to track ability to defrag etcd [https://github.com/rancher/rancher/issues/16025].

But if you know what's causing etcd to fill up, please file a new issue.

**Comment by artemus717** [comment]
Rancher 2.2.5
Docker 17.06

No use

**Comment by SchuhMichael** [comment]
> There are troubleshooting docs on etcd here: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/#etcd-space-errors

This assumes etcd runs as container on the cluster, when using this to fix a single node installation with rancher/rancher:stable, it helps to run 

`docker run --net=container:<NAME_OF_RANCHER_CONTAINER> -id --name etcd-utility rancher/rke-tools:v0.1.40`

And then use etcdctl as explained in this link, but through the etcd-utility container.

**Comment by superseb** [comment]
I may add single install etcd troubleshooting in the docs, until then you can use either of these on your own risk:

v2.2: https://gist.github.com/superseb/f223b15949c031983da2cb850f56a897
v2.1: https://gist.github.com/superseb/48037c0323147e603bc0197bd5ecb9b5

**Comment by SchuhMichael** [comment]
Great! Important to mention that ETCDCTL_API=3 is not automatically enabled in rancher/rke-tools:v0.1.40, but needed to compact and defrag. Worked for me. However, can we use this also to enable automatic compaction in single node installation with docker?
