### ISSUE TITLE
 Standard user role display error

### ISSUE THREAD

**Issue by dongjuanwinhong** [rancher/rancher#15854]
**Rancher versions:**
rancher/server or rancher/rancher:v2.1.0-rc4

**Steps to Reproduce:**
1.Administrator creates a standard user
![image](https://user-images.githubusercontent.com/39041059/46199290-42742a80-c341-11e8-86cd-3bd706153e97.png)

2.Standard user login
3.View own user roles

**Results:**
Show as a custom user,only has Login Access 
![image](https://user-images.githubusercontent.com/39041059/46199252-283a4c80-c341-11e8-995b-81b2025b2c82.png)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15107
