### ISSUE TITLE
The Registry Credentials is configured after the workload is created, resulting in the inability to pull the private image

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#15850]
**Rancher versions:**
rancher/rancher: v2.0.4 to master
 rancher/rancher-agent: v2.0.4 to master

**Steps to Reproduce:**
1. Create a workload using a private image;
2. Add the registry Credentials to the registries；

**Results:**
The workload cannot be created properly and the prompt image does not exist

<img width="894" alt="image" src="https://user-images.githubusercontent.com/20707603/46185742-dd531180-c30d-11e8-9d53-1575d7c9c996.png">
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/20707603/46185749-e6dc7980-c30d-11e8-941a-014162d43e2a.png">

3. After the registry Credentials are added, the workload can be created using the same private image

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/20707603/46185768-f8be1c80-c30d-11e8-9734-dd05c8d51c03.png">

**Comment by strowi** [comment]
seems also related to https://github.com/rancher/rancher/issues/15850

**Comment by loganhz** [comment]
Please check https://github.com/rancher/rancher/issues/13332#issuecomment-387238355
