### ISSUE TITLE
Kubectl commands returning "Unable to connect to the server: x509: certificate signed by unknown authority FATA[0006] exit status 1" error

### ISSUE THREAD

**Issue by shinebayar-g** [rancher/rancher#15860]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.11

**Docker version: (`docker version`,`docker info` preferred)** 17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04.5 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** DigitalOcean

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
I've created Ubuntu 16.04 droplet and installed docker supported version 17.03 on it.
Then I installed Rancher 2.0 on it using:
```
docker run -d --restart=unless-stopped \
  -p 127.0.0.1:8080:80 -p 127.0.0.1:8443:443 \
  -v /host/rancher:/var/lib/rancher \
  rancher/rancher:stable
```
command. Then I installed Nginx and using this config to reverse proxy Rancher web UI. I also got Lets Encrypt SSL for my domain using certbot's nginx plugin. And my final result of Nginx config is:
```
upstream rancher {
    server 127.0.0.1:8080;
}

map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

server {
    server_name rancher.erxes.io;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/rancher.erxes.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/rancher.erxes.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = rancher.erxes.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name rancher.erxes.io;
    return 404; # managed by Certbot
}
```
Now I can access Rancher web UI without problem, and created my first cluster and first deployment on it. Then I created ingress load balancer and pointed it to my service. But It wasn't clear to me that how can I know ingress IP address to point my domain. Then I found about it on documents. It said I have to create token and use bearer token to login to rancher using rancher CLI. 

**Results:**
Now I successfully logged in, but when I run ./rancher kubectl get ingress command it returns this:

```
Unable to connect to the server: x509: certificate signed by unknown authority
FATA[0005] exit status 1 
```
It seems It's using self signed certificate somewhere, how can I let it use my Let's encrypt generated certificate?

**Comment by superseb** [comment]
The docs describe how to use an external LB with SSL here: https://rancher.com/docs/rancher/v2.x/en/installation/single-node/single-node-install-external-lb/

In your case you need to disable cacerts generation using `--no-cacerts`. Let me know if that doesn't solve the issue.

**Comment by shinebayar-g** [comment]
Mhm, I've realized that I should've disabled it while running rancher. My cluster is already up. If I stop rancher 2.0 docker and start it again with `--no-cacerts` parameter, will it override old one?

**Comment by shinebayar-g** [comment]
@superseb I'm just curious that is there any downside running Rancher with  `--no-cacerts` ?
I mean I just want to make sure I'm not opening any security issues on my cluster.

**Comment by superseb** [comment]
No, this is the documented way of using Rancher with an external load balancer. All port requirements are in https://rancher.com/docs/rancher/v2.x/en/installation/references/. If you externally terminate SSL, Rancher doesn't do SSL so that's why it shouldn't generate certificates.
