### ISSUE TITLE
Available disk space is completely wrong for CentOS

### ISSUE THREAD

**Issue by moimael** [rancher/rancher#1586]
Hi,

On CentOS hosts, reported available disk space is completely wrong, for example, in a vm with 16Go of disk space, rancher report 30Go. 

I think the cause is the use of device mapper by docker on CentOS. Docker allow 3 10Go devices in device mapper but the physical disk space is only 16Go.

**Comment by deniseschannon** [comment]
@cloudnautique Can you take a look at the stats for CentOS?

**Comment by cloudnautique** [comment]
@sangeethah this should be resolved #2023.

**Comment by sangeethah** [comment]
Tested with server version - v0.39.0-rc1

Host had an Centos 7.1.1503 server with 10 GB disk space.

Added host to rancher server.

Rancher server reports correct disk space - reports 10 GiB.
