### ISSUE TITLE
If rancher is opened in a tab when auth is turned on, opening another tab and trying to login throws "Session timed out error"

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#15869]
**Rancher versions:**
rancher/server v1.6.22-rc3

**Steps to reproduce**
1. Setup SAML (PingFederate) auth  
2. Keep this rancher server tab open and open it again in a new tab  
3. Opening a new tab should log you out of the first tab  
4. Now try logging into the second tab, when I tried I got a Session timed out error  

As per discussion with @vincent99 (Please correct me if I'm wrong): This happens because when I try to login in the second tab, the login actually succeeds and cattle generates a token, but the UI from first tab sends a DELETE request to v2-beta/token, hence deleting the token generated for me, so I get logged out immediately from the second tab. This DELETE request shouldn't be done

Screenshots  
1. Trying to login on the second tab, the token is present in cookies until this call
<img width="1440" alt="screen shot 2018-09-28 at 3 07 24 pm" src="https://user-images.githubusercontent.com/10672776/46235676-519eac80-c330-11e8-9c22-ac9dce44db83.png">

2. Trying to login on the second tab, token is not present int he call after call to catalogs
<img width="1438" alt="screen shot 2018-09-28 at 3 07 30 pm" src="https://user-images.githubusercontent.com/10672776/46235862-1650ad80-c331-11e8-8026-71e9751ee933.png">

3. The reason being, on the first tab in Developer tools we can see DELETE requests to delete token being sent
<img width="1438" alt="screen shot 2018-09-28 at 3 20 15 pm" src="https://user-images.githubusercontent.com/10672776/46236065-06859900-c332-11e8-839b-c35fbfb3cb7d.png">

**Comment by skullydazed** [comment]
I'm seeing this same behavior with GitHub authentication.

**Comment by vincent99** [comment]
Yes, this has nothing to do with SAML specifically.

**Comment by vikas027** [comment]
Hello @deniseschannon / @mrajashree ,

This should not be closed, this is indeed a bug which has cropped up only after enabling SAML (Keycloak) authentication.
