### ISSUE TITLE
Add annotations field to Pod Security Policy configurations UI

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#15861]
**Rancher versions:**
rancher/rancher: 2.0.8

Some PSP functionality is configured through annotations.  For example: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor

Can we add annotations to the PSP configuration UI?

**Comment by loganhz** [comment]
@davidnuzik Please try to add it in Global level menu > Security > Pod Security Policies > Add Policy

There is a `Labels & Annotations` section in new/edit policy page.

![image](https://user-images.githubusercontent.com/21168270/50721216-c8e59880-10f6-11e9-801d-873a587ca6e0.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/7/19)
Confirmed feature.
When you now edit or create a new Pod Security Policy there is a "Labels & Annotations" section. I confirmed this is working by validating HTTP/API in the UI.
