### ISSUE TITLE
[2.0.8] Added SANs to cluster config under authentication but kube-apiserver.pem was not regenerated

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15868]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1855.4.0
VERSION_ID=1855.4.0
BUILD_ID=2018-09-11-0003
PRETTY_NAME="Container Linux by CoreOS 1855.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

4.14.67-coreos

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack

**Steps to Reproduce:**
Create cluster without the cluster config sans under authentication. Add sans to config after it has been provisioned. Rancher shows it is updating the cluster.

**Results:**
The kube-apiserver.pem on the control plane servers was not modified and does not contain the extra sans values.

**Comment by mitchellmaler** [comment]
I just tested rebuilding a control plane node and now the kube-apiserver.pem does have the sans value. So it seems to not update it if it has already been provisioned.

I would expect it to regenerate the certs and restart the api-server container one control plane node at a time.

**Comment by shubb30** [comment]
I see the same behavior when creating a cluster using RKE directly (version v0.1.15).  I presume that Rancher uses RKE under the hood to provision hosts in a provider.

**Comment by shubb30** [comment]
I tried the above workaround by adding a new node with roles `[controlplane,worker,etcd]` to the cluster.yml file, and ran `rke up` again.  I see that the node is added to the cluster fine.  

When I query the server certificate on the new host, I see that the certificate has the new SAN that I added to the cluster config.  

However, the original host did NOT get the updated certificate, and when I check the host it does not have the new SAN.  The files in `/etc/kubernetes/ssl` still have the modify time of when I created the cluster.

To fix it, I had to move all of the files from `/etc/kubernetes/ssl` into a backup directory, and then run `rke up` again.  This caused the certificates to be recreated on the host, but I still had to restart the kube-apiserver container on the host to get it to pick up the new certificates.

**Comment by micw** [comment]
This behaviour can also be seen if you deploy a multi-node-cluster on rancher node-by-node. Add node1 and it has "node1" as SAN, add node2 and it has "node1" and "node2" as SAN while node1 still has only "node1".

**Comment by leodotcloud** [comment]
Tested the following scenarios:
1) Provision a host, use cluster.yml, bring up a k8s cluster with `rke up`. Edit cluster.yml, add san entries and do `rke up` again. I see that the certificates are regenerated. (`rke version v0.2.7`)
2) v2.2.4 Rancher setup. Setup a single node cluster using Linode driver. Once cluster is up, edit cluster.yml and add san entries. The certificates are regenerated.

This original problem seems to have been fixed along the way and not an issue anymore.

**Comment by leodotcloud** [comment]
Tested the following scenarios:

1) Using rke (`rke version v0.2.7`)
  - Create a linux host
  - Bring up a cluster using `rke up`
  - Edit cluster.yml, append san entries and run `rke up`
  - The certs are regenerated and API server is restarted.

2) Using Rancher (v2.2.4)
  - Create a single node cluster using Linode Driver
  - Edit cluster.yml, append san entries and run `rke up`
  - The certs are regenerated and API server is restarted.

The original reported problem got fixed along the way and currently it's not an issue anymore.
