### ISSUE TITLE
[2.0.8] Error from server (Forbidden): pods.metrics.k8s.io is forbidden: User "u-uid" cannot list pods.metrics.k8s.io in the namespace "..."

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15866]
Metrics server is deployed to the cluster but users do not have access to listing pods metrics. Is there a permissions that is missing that I have to add to their role?

**Comment by loganhz** [comment]
Hi @mitchellmaler 

I can run `kubectl top pods` in v2.1.0. Do you mean you can not run it in `v2.0.8`?

![image](https://user-images.githubusercontent.com/21168270/46579266-95846680-ca40-11e8-86d3-a42291476db8.png)

**Comment by mitchellmaler** [comment]
@loganz in 2.0.8 as a admin i can run it. 
I created a test user and gave them project owner. That user can manage the namespaces in a project but can't run top pods for that namespace.

**Comment by mitchellmaler** [comment]
@loganhz i believe it's an issue with not adding access to metrics to the users role for their project/namespaces.  I tested creating a new role and role binding to my test user which gave them access to metrics and it work.

Rancher should be extended to add this to the role that is created to give usees access to their namespaces.

**Comment by cjellick** [comment]
@fyery-chen @orangedeng note: in the future, dont remove working and ready-for-review labels as it moves forward in the process

**Comment by bmdepesa** [comment]
rancher/rancher:master

* Reproduced original issue (user unable to list pod metrics)
* Install from master
* Add standard user as cluster owner
* Login as the new standard user
* `kubectl top pods` returns successfully
