### ISSUE TITLE
Set default instance size for nodes when creating AKS

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15864]
Change to recommended `Standard_D2_v2` instead of `Standard_A2`

**Comment by tfiduccia** [comment]
Should this be changed for RKE Azure as well?

**Comment by westlywright** [comment]
`azureConfig` schema has a default of `Standard_A2`
`azureKubernetesServiceConfig` schema does not have a default

**Comment by tfiduccia** [comment]
Version 2.1 rc9
Verified fixed - Added new bug for API change.
