### ISSUE TITLE
MongoDB replicaset from Catalog stuck on Installing.

### ISSUE THREAD

**Issue by shinebayar-g** [rancher/rancher#15878]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
I've installed MongoDB replicaset from Catalog App just fine with default options for first time. Then I deleted my MongoDB deployment from Catalog Apps and tried to install fresh new MongoDB replica set again. This time I did exactly same steps to install MongoDB replica set. But this time default options were different from first time, example:
**Name** was just `mongodb-replicaset` when first time, but it was `mongodb-replicaset-tmhsh` second time. So I changed `mongodb-replicaset-tmhsh` to `mongodb-replicaset`.
Also **Namespace** was same as name, so I changed namespace to `mongodb-replicaset`
Other default options were same like first time.
**Results:**
Now MongoDB replicaset is stuck on installing like this
![image](https://user-images.githubusercontent.com/3091558/46241482-23cb6d80-c3ed-11e8-9d4d-eb2be218bf3b.png)

Where can I find related logs and debug issue?

**EDIT:** nah I just can't install mongodb whatever name i gives, it doesn't matter. Stuck on installing.

**EDIT2:** If I actually go to application details, it gives this error:
```
Installing
Helm template failed. Error: failed parsing --set data: key map "" has no value : exit status 1
```
I selected disable authentication when creating this application.

**EDIT3:** I addressed the error.
If I select disable authentication, installation fails. (Stucks on Installing) Otherwise install will succeed.

**EDIT4:** Autogenerated passwords are creating problems:
Example error
```
Helm template failed. Error: failed parsing --set data: key "178/qJ-;O^D" has no value (cannot end with ,) : exit status 1
```
Example error2
```
Installing
Helm template failed. Error: failed parsing --set data: key "fqhc2F8IV2" has no value (cannot end with ,) : exit status 1
```

**Comment by shinebayar-g** [comment]
I had installed Redis cluster exactly same steps and it installs just fine. When installing redis second time name and namespace fields was changed to autogenerated names, I changed them back to first time defaults: redis and redis. Redis installation is just fine.

**Comment by shinebayar-g** [comment]
Can't install MongoDB from Catalog as well, same issue.

**Comment by loganhz** [comment]
Can you try it in v2.1.0, please? I can install MongoDB and MongoDB replicaset from Catalog with the default options.

**Comment by xyjwsj** [comment]
![wechatimg8867](https://user-images.githubusercontent.com/8518853/48105448-95130180-e272-11e8-8d25-17a066771df7.jpeg)
Install Mongodb error with longhorn
