### ISSUE TITLE
Failed to enable k8s Etcd Recurring Snapshots

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#15877]
**Rancher versions:**
rancher/rancher:v2.0.8

**Docker version:**
17.03.2-ce

**Operating system and kernel:**
Ubuntu 16.04.4 LTS

**Setup details:**
single node rancher

**Steps to Reproduce:**
Edit k8s cluster as yaml and save:
````yaml
services: 
  etcd: 
    snapshot: true
````

**Results:**
<img width="1265" alt="enablek8setcdsnapshotfailed" src="https://user-images.githubusercontent.com/9134975/46240520-63895980-c3db-11e8-96e3-f2888ca94e8c.png">
[etcd] Failed to bring up Etcd Plane: Failed to start [etcd-rolling-snapshots] container on host [10.3.150.91]: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/opt/rke-tools/rke-etcd-backup\": stat /opt/rke-tools/rke-etcd-backup: no such file or directory"

**Comment by happyyangyuan** [comment]
> What cluster version did you choose and what image version of `rancher/rke-tools` is present on `10.3.150.91`?
image | version
------------ | -------------
rancher/hyperkube | v1.10.5-rancher1
rancher/rke-tools | v0.1.10

**Comment by happyyangyuan** [comment]
Any progress? @loganhz @superseb

**Comment by aemneina** [comment]
running into the same issue with 2.1.1 and openstack machine driver provisioning ROS.

**Comment by moelsayed** [comment]
@happyyangyuan @aemneina Can you please check if your cluster kubernetes version is `v1.10.5-rancher1-2` or `v1.10.5-rancher1-1`. You can check in the cluster API view.

**Comment by happyyangyuan** [comment]
@moelsayed  kubernetesVersion": "v1.11.3-rancher1-1"

**Comment by alena1108** [comment]
@happyyangyuan do you also use openstack driver for hosts provisioning?

**Comment by happyyangyuan** [comment]
@alena1108 We use vmware for hosts provisioning.

**Comment by happyyangyuan** [comment]
After upgrading rancher to v2.1, as a result the rke upgrades from 0.1.10 to 0.1.15 and the problem got sovled.
