### ISSUE TITLE
Cannot modify the vSphere node template

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#15879]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent:

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere
**Steps to Reproduce:**
1. Add a vsphere node template, `Network ` setting empty.
2. Edit this template and save it
**Results:**
Cannot save, prompt:
`Validation failed in API: vmwarevsphereConfig network=NotNullable 422:`

**Comment by MaxDiOrio** [comment]
I don't see the error message, but the VMWare Network text box is empty.  Each time you put a network in and save it, the box is empty upon next view.  It does however properly create machines in the right network.

**Comment by FleischKarussel** [comment]
@MaxDiOrio 
I've got nearly the same issue with Rancher 2.1.1, no error message but same outcome.
There are no additional logs visible when saving, even with debug log enabled.

**Comment by char-iot** [comment]
@MaxDiOrio @loganhz vSphere Node Template Network field stays empty.

Tested environment: combination of ubt 1604 1804, docker 1703 1803 1806 1809, rancher v2.0.8 v2.1.1 v2.1.2

**Comment by ncc1701p** [comment]
So ive had this issue since 2.0.6  . you can modify it but sometimes it doesnt display the item you put in there after you go back and re-edit the template.

**Comment by char-iot** [comment]
@ncc1701p thx. "VM Network" does show up in API. I always thought reason that I can't create cluster is this. But since it's not. It might be related to #16549

**Comment by InboxPeter** [comment]
Same error:  vmwarevsphereConfig network=NotNullable 422 when making a new template by cloning a template that did not have a Network definition. Also can not edit a template and save with blank Network.
Rancher Versions:
Rancher	v2.2.0-alpha3
User Interface	v2.2.1
Helm	v2.10.0-rancher5
Machine	v0.15.0-rancher1-1

**Comment by loganhz** [comment]
Close in favor https://github.com/rancher/rancher/issues/18894
