### ISSUE TITLE
Service Upgrades

### ISSUE THREAD

**Issue by keyscores** [rancher/rancher#1587]
I can't seem to find any docs/information on upgrading a service. Does this feature not exist?

Ideally a service should be redeployed when the dockerhub image changes. This is the one feature that is keeping me from investing further in rancher.

Tutum is already doing this with webhooks, and it's very effective. 
Related issue: #619

**Comment by keyscores** [comment]
@richburdon Is this an issue you're having as well?

**Comment by will-chan** [comment]
@keyscores there is already a forum posting talking about how to upgrade existing services (http://forums.rancher.com/t/zero-downtime-app-upgrades/112/2).  However, this probably doesn't answer exactly what you want given you want a way to automatically detect some change, and making an API call to automatically perform the upgrade.  We will also be shipping Rancher CLI support for rolling-upgrades (#1079), but it is CLI only right now.  We will add it to Rancher API soon and from there, we can allow a way for you to post a webhook request to Rancher to execute it.

**Comment by keyscores** [comment]
Ok thanks for the update. ETA?
I think generating a URL with token to be pasted in dockerhub will be a satisfactory UX.

**Comment by rebyn** [comment]
https://github.com/rancher/cattle/pull/898 got merged. Does this mean we can try out with latest `rancher`? :)

**Comment by deniseschannon** [comment]
@keyscores With the addition of in-service upgrade https://github.com/rancher/rancher/issues/1874, you should be able to upgrade a service.
