### ISSUE TITLE
Large LDAP Database causes Rancher LDAP query timeouts

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#15870]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.X

With an LDAP Database of over 500,000 "accounts", Rancher (or the LDAP server) times out when trying to retrieve information from the LDAP server.

We must devise a way to allow Rancher to interact with super-large LDAP databases for authentication.

**Comment by alena1108** [comment]
Would require redesigning a nested group query

**Comment by sangeethah** [comment]
Tested with latest build for rancher server from master Nov 16.
Nested group functionality in Active Directory works as expected.
