### ISSUE TITLE
Member list of Cluster search function  invalid for standard users

### ISSUE THREAD

**Issue by dongjuanwinhong** [rancher/rancher#15883]
**Rancher versions:**
rancher/server or rancher/rancher:v2.1.0-rc7
rancher/agent or rancher/rancher-agent:v2.1.0-rc7

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux 7 (Core)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

Add a standard user

1. admin login
2. Add members to the cluster, give the standard user autotest1 owner permission, and give the administrator user autotest2 owner permission.
3. Standard User autotest1 login，in the page of cluster-member list ，Type B in the search input box
4. administrator User autotest2 login，in the page of cluster-member list ，Type A in the search input box

**Results:**
step 4 success，but step 3 failed

![image](https://user-images.githubusercontent.com/39041059/46255032-d58c9c00-c4ca-11e8-91d3-05c5493e2c81.png)

![image](https://user-images.githubusercontent.com/39041059/46255003-82b2e480-c4ca-11e8-8968-5fecccc1c44c.png)
![image](https://user-images.githubusercontent.com/39041059/46255025-b5f57380-c4ca-11e8-9d18-2630bdf617ad.png)

**Comment by loganhz** [comment]
I can not reproduce this issue. Can you try again in v2.1.0, please?

**Comment by dongjuanwinhong** [comment]
The problem still exits in v2.1.0
step3：
![image](https://user-images.githubusercontent.com/39041059/46591118-1ac45580-caeb-11e8-9fc9-44aeb4457a9f.png)

![image](https://user-images.githubusercontent.com/39041059/46591201-b05fe500-caeb-11e8-89b3-f329e22ed6c0.png)

**Comment by dongjuanwinhong** [comment]
![image](https://user-images.githubusercontent.com/39041059/46593546-78629d00-caff-11e8-832d-ec54c544b6a5.png)

**Comment by dongjuanwinhong** [comment]
Maybe you need add users with special character like "autotest1" "autotest2",as shown ,
![image](https://user-images.githubusercontent.com/39041059/46593846-b06adf80-cb01-11e8-9478-ae065a29dc1c.png)

![image](https://user-images.githubusercontent.com/39041059/46593855-c5e00980-cb01-11e8-8414-dad4258a2f30.png)
