### ISSUE TITLE
Rancher server has TLS 1.0 enabled

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#15885]
**Rancher versions:**
2.0.8

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-1067-aws
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, with HTTPs
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Deploy Rancher with CA issued certs, for example:
```
docker run -d --restart=unless-stopped \
    -p 80:80 -p 443:443 \
    -v /etc/letsencrypt/live/<my public hostname>/fullchain.pem:/etc/rancher/ssl/cert.pem \
    -v /etc/letsencrypt/live/<my public hostname>/privkey.pem/:/etc/rancher/ssl/key.pem \
    rancher/rancher:latest --no-cacerts
```
Check to see if TLS/1.0 is enabled by running
`openssl s_client -connect <my pubic hostname>:443 -tls1`

Should consider disabling TLS/1.0.

**Comment by tboemker-bkfs** [comment]
That would work for connections to the cluster, but what about connections to the Rancher Server UI?

**Comment by superseb** [comment]
Validation with the new defaults (TLSv1.2) which are enabled automatically:

* Using OpenSSL

Failing means seeing `error:*:SSL routines:*:SSL alert number*`  or `SSL routines:SSL3_GET_RECORD:wrong version number` on the first 2/3 lines of the output:

`openssl s_client -connect IP_OR_HOSTNAME:443 -tls1` should fail
`openssl s_client -connect IP_OR_HOSTNAME:443 -tls1_1` should fail
`openssl s_client -connect IP_OR_HOSTNAME:443 -tls1_2` should succeed

* Using https://www.ssllabs.com/ssltest/index.html

This requires a DNS name pointing to the host running the `rancher/rancher` container. Enter the DNS name, tick `Do not show the results on the boards`. When the scan finished you should only see `TLS 1.2` listed as Yes under Configuration -> Protocols. 

* Using nmap

Should only show TLSv1.2 available

```
docker run --net=host superseb/nmap --script ssl-enum-ciphers -p 443 IP_OR_HOSTNAME

Starting Nmap 7.60 ( https://nmap.org ) at 2019-02-22 01:03 UTC
Nmap scan report for X (x.x.x.x)
Host is up (0.0037s latency).

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (rsa 2048) - A
|     compressors:
|       NULL
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 3.69 seconds
```

Configuration options:
- Minimum TLS version can be configured via `CATTLE_TLS_MIN_VERSION` environment variable or via API (`/v3/settings/tls-min-version`)
- TLS ciphers can be configured via `CATTLE_TLS_CIPHERS` environment variable or via API (`/v3/settings/tls-ciphers`)

Example:
```
 docker run -d -p 80:80 -p 443:443 -e CATTLE_TLS_MIN_VERSION="1.0" -e CATTLE_TLS_CIPHERS="TLS_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
```

Wrong configurations should be logged, valid options are:
* `CATTLE_TLS_MIN_VERSION="1.0"`
* `CATTLE_TLS_MIN_VERSION="1.1"`
* `CATTLE_TLS_MIN_VERSION="1.2"`

Ciphers from https://golang.org/pkg/crypto/tls/#pkg-constants

Ciphers should be comma separated and should allow for spaces (`cipher1, cipher2`)

**Comment by soumyalj** [comment]
Tested with rancher v2.1.7-rc3
Created a rancher server with certs, configured a DNS name pointing to the rancher server. 
Verified that TLS1 and TLS1_1 are not supported.
```
~# openssl s_client -connect soumyanewtest.qa.rancher.space:443 -tls1
CONNECTED(00000003)
140270436148888:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:s3_pkt.c:1487:SSL alert number 70
140270436148888:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:656:
---
no peer certificate available
---
No client certificate CA names sent

```
```
openssl s_client -connect soumyanewtest.qa.rancher.space:443 -tls1_1
CONNECTED(00000003)
139815907042968:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 0 bytes
---
```
Verified that TLS1.2 is enabled.
```
 openssl s_client -connect soumyanewtest.qa.rancher.space:443 -tls1_2
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = *.qa.rancher.space
verify return:1
---
Certificate chain
 0 s:/CN=*.qa.rancher.space
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---

```

Using : * Using https://www.ssllabs.com/ssltest/index.html
![screen shot 2019-02-25 at 2 25 31 pm](https://user-images.githubusercontent.com/18536626/53373052-511f3780-3909-11e9-8245-474bc7d45365.png)

Using nmap
```
~# nmap --script ssl-enum-ciphers -p 443 soumyanewtest.qa.rancher.space

Starting Nmap 7.01 ( https://nmap.org ) at 2019-02-25 22:28 UTC
Nmap scan report for soumyanewtest.qa.rancher.space (134.209.6.67)
Host is up (0.0014s latency).
PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|     compressors: 
|       NULL
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 0.81 seconds




```

**Comment by dnoland1** [comment]
I also tested on https://www.ssllabs.com/ and see TLS 1.0/1.1 disabled, TLS 1.2 enabled.

**Comment by sangeethah** [comment]
Reopening to

**Comment by soumyalj** [comment]
Tested with master build from Feb 26.
Created a rancher server with certs, configured a DNS name pointing to the rancher server.
Verified that TLS1 and TLS1_1 are not supported.
```
:~/certs# openssl s_client -connect sabc.com:443 -tls1
CONNECTED(00000003)
140655354668696:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:s3_pkt.c:1487:SSL alert number 70
140655354668696:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:656:
---
no peer certificate available
---
No client certificate CA names sent


:~/certs# # openssl s_client -connect sabc.com:443 -tls1_1
CONNECTED(00000003)
140284663035544:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 0 bytes
---
```
Verified that TLS1.2 is enabled.

```
:~/certs# openssl s_client -connect sabc.com:443 -tls1_2
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = *.qa.rancher.space
verify return:1
---
Certificate chain
 0 s:/CN=*.qa.rancher.space
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
```

Using : * Using https://www.ssllabs.com/ssltest/index.html
<img width="963" alt="screen shot 2019-02-26 at 5 12 14 pm" src="https://user-images.githubusercontent.com/18536626/53458259-3a9cdd00-39ea-11e9-8370-2862d4b78610.png">
