### ISSUE TITLE
rancher 2.0 not working local dev environment

### ISSUE THREAD

**Issue by leetskil** [rancher/rancher#15886]
i'm trying to use rancher 2.0 so i that i'll could focus in version 2.0 (kurbenetes) aside from rancher 1.6 which is gonna end soon.  

i've installed and followed the instruction and provided node requirements that needed to work with rancher 2.0, but it seems it does not work for me. *bummer

local dev environment
under virtualbox

Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

rancher 2.0 `rancher/rancher:stable`

`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://192.168.1.11 --token 8h276768ltlj9v95fwbjbqqnm6htk654fz79zcmctp87xh9d2bxr5c --ca-checksum 4acac799ee17e2c488afa0219f4505e907831853607e650dd80f72806fe19895 --worker`

`This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready. Waiting for etcd and controlplane nodes to be registered`

state: provisioning `Waiting for etcd and controlplane nodes to be registered`

docker log 

sudo docker logs 6b864b5338b7
INFO: Arguments: --server https://192.168.1.11 --token REDACTED --ca-checksum 4acac799ee17e2c488afa0219f4505e907831853607e650dd80f72806fe19895 --worker
INFO: Environment: CATTLE_ADDRESS=192.168.1.11 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=The-machine-i CATTLE_ROLE=,worker CATTLE_SERVER=https://192.168.1.11 CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 192.168.1.1
INFO: https://192.168.1.11/ping is accessible
INFO: Value from https://192.168.1.11/v3/settings/cacerts is an x509 certificate
time="2018-10-01T13:06:49Z" level=info msg="Rancher agent version v2.0.8 is starting"
time="2018-10-01T13:06:49Z" level=info msg="Option customConfig=map[internalAddress: roles:[worker] label:map[] address:192.168.1.11]"
time="2018-10-01T13:06:49Z" level=info msg="Option etcd=false"
time="2018-10-01T13:06:49Z" level=info msg="Option controlPlane=false"
time="2018-10-01T13:06:49Z" level=info msg="Option worker=true"
time="2018-10-01T13:06:49Z" level=info msg="Option requestedHostname=The-machine-i"
time="2018-10-01T13:06:49Z" level=info msg="Listening on /tmp/log.sock"
time="2018-10-01T13:06:50Z" level=info msg="Connecting to wss://192.168.1.11/v3/connect/register with token 8h276768ltlj9v95fwbjbqqnm6htk654fz79zcmctp87xh9d2bxr5c"
time="2018-10-01T13:06:50Z" level=info msg="Connecting to proxy" url="wss://192.168.1.11/v3/connect/register"
time="2018-10-01T13:06:50Z" level=info msg="waiting for node to register"
time="2018-10-01T13:06:52Z" level=info msg="waiting for node to register"
time="2018-10-01T13:06:54Z" level=info msg="waiting for node to register"
time="2018-10-01T13:06:56Z" level=info msg="waiting for node to register"

other thoughts: 

is ubuntu 18.04 compatible with rancher 2.0?
is docker versions 17.03.0-ce to 18.06.1-ce  compatible with rancher 2.0?

**Comment by superseb** [comment]
The message `Waiting for etcd and controlplane nodes to be registered` means it needs an etcd and controlplane node to function. You can click the etcd and controlplane roles after you created the cluster, this will add `--etcd` and `--controlplane` to the command. When you run the command, the cluster will be provisioned.  The error message is being made more clear in https://github.com/rancher/rancher/issues/12548.

The supported OS/Docker are described in https://rancher.com/docs/rancher/v2.x/en/installation/requirements/

Let me know if it doesn't work after adding all the roles to a node.

**Comment by leetskil** [comment]
i did checked --etcd and --controlplane when in the cluster options, but still doesnt do anything.

**Comment by superseb** [comment]
The log and the command you are showing both don't show that you are using the correct roles. The flags mentioned in the previous comment get added to the command, see below:

<img width="1295" alt="screen shot 2018-10-01 at 17 40 25 copy" src="https://user-images.githubusercontent.com/2620179/46299463-ae54ce00-c5a1-11e8-876a-653a4b52e788.png">

Create a new custom cluster, choose all roles and copy the command to be executed on the node you want to add.

Make sure the node is cleaned between adding/removing them to make sure there are no conflicting files (https://rancher.com/docs/rancher/v2.x/en/faq/cleaning-cluster-nodes/) and if you are using a single node to run this, you need to start Rancher itself with different ports to make sure there is no conflict when the cluster is built: https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#running-rancher-rancher-and-rancher-rancher-agent-on-the-same-node

**Comment by leetskil** [comment]
okay got it, thank you @superseb  👍
