### ISSUE TITLE
For SAML edit we should have a cancel button

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15889]
**Rancher versions:** 2.1 - rc7

**Steps to Reproduce:**
1.  Log in using ADFS
2.  Click on Edit

**Results:**  There is only a Save button, If I want to exit edit without changing anything I have to leave page and come back.  Would be nice to have a cancel next to the save.  Make sure it's also available in other Authentication pages as well.

![image](https://user-images.githubusercontent.com/11514927/46308167-d1658a80-c56d-11e8-8c1d-93734a1d083f.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/8/19)
Confirmed enhancement. There is now a cancel button for all of the auth providers. This works for each including even if you are halfway done filling in info, or had not completed required fields. The Save button is now an "Authenticate with XYS" button as well. This appears to be functioning correctly. I have tested with a few providers (fully set up) without any issues. Cancel button works on all of them.
