### ISSUE TITLE
Remove host.api.proxy.scheme setting

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1588]
User should not have to explicitly set ws or wss. Should be able to dynamically determine it based off protocol of incoming host.

**Comment by cjellick** [comment]
Need to make sure the documentation is updated.

**Comment by cjellick** [comment]
@sangeethah we need to assign this one over to @cloudnautique to make sure he hits all the places in his scripts where he was configuring the setting.

So, once you're done validating, just assign to him.

His changes won't affect the functionality, it will just apply to scripts he uses for building specific environments for our internal use.

**Comment by sangeethah** [comment]
Tested with rancher/server:v0.31.0-rc1

Able to bring up a rancher-server with SSL behind Nginx as https reverse proxy.
Following are the steps followed:

docker run -d --restart=always --name=rancher-server -e "CATTLE_API_ALLOW_CLIENT_OVERRIDE=true" rancher/server:v0.31.0-rc1
mkdir /root/nginx

docker run -d -p 80:80 -p 443:443 -v /root/nginx/ssl:/etc/nginx/ssl/:ro -v /root/nginx/rancher.io.conf:/etc/nginx/conf.d/rancher.io.conf:ro --link='rancher-server' nginx

nginx confifuration used:

upstream rancher {
    server rancher-server:8080;
}

server {
    listen 443 ssl;
    server_name <servername>;
    ssl_certificate /etc/nginx/ssl/rancher.io.bundled.crt;
    ssl_certificate_key /etc/nginx/ssl/rancher.io.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name <servername>;
    return 301 https://$server_name$request_uri;
}

Able to add custom hosts , Digital Ocean hosts to rancher server successfully.
Able to view host stats.
Able to view container logs and also exec shell.
Basic sanity checks to make sure that the connectivity between containers from different hosts work.

**Comment by cloudnautique** [comment]
@sangeethah @cjellick @will-chan  I'm good closing this one.
