### ISSUE TITLE
is rancher 2.0 replacing rancher 1.6?

### ISSUE THREAD

**Issue by leetskil** [rancher/rancher#15882]
i have worked with rancher 1.6 cattle and i am very convenient to use rancher 1.6 cattle in production using the stable version. also i've tried rancher 2.0 a little bit confuse on the new structure in all. also in the catalog section of the rancher 2.0 (stable version)there are 3 options to use the catalog section. the first one was the old way to use the catalog but there is no list of catalogs to use, after i have installed rancher 2.0 (stable version)

where can i find a list of catalog templates for rancher 2.0?

**Comment by superseb** [comment]
The catalog options are described here https://rancher.com/docs/rancher/v2.x/en/catalog/ and our catalog lives here: https://github.com/rancher/charts

If there are not catalog apps to launch, most likely there is no internet connection to retrieve the charts/apps so they can be loaded in the UI. In this case, a local mirror of the repository mentioned above and adding it as a custom catalog should work.

**Comment by leetskil** [comment]
thank you
