### ISSUE TITLE
rancher-save-images.sh/rancher-load-images.sh don't use the rancher-images.txt file.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#15891]
**Rancher versions:**
rancher/rancher: v2.0.8

Looks like these scripts are generated and have hard-coded lists of images in them.  I would like to change them to read from the `rancher-images.txt` file and streamline the image publishing process for private registry and air gap installs.

**Comment by deniseschannon** [comment]
Re-asaigned to @bmdepesa as he is going through HA upgrade testing and will be using these scripts

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0-rc9

Used the new scripts to successfully populate a private registry with 2.0.8, 2.1.0, and custom images for airgapped HA upgrade testing.
