### ISSUE TITLE
After upgrading to v2.1.0-rc7, old Jenkins pipeline workload is not removed.

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#15899]
rancher/rancher:v2.1.0-rc7

Starting on rancher/rancher:v2.0.8
* Enable pipeline
* Upgrade to rancher/rancher:v2.1.0-rc7
* After enabling pipeline again (due to refactor), the new Jenkins workloads are created successfully in the `System` and project where pipeline is created.
* Check that old Jenkins workload is removed (due to pipeline refactor)

Expected:
* Old Jenkins workload is still present in `cattle-pipeline` in `System` project

Actual:
* Jenkins workload is not removed from `cattle-pipeline` namespace in `System` project

**Comment by alena1108** [comment]
@gitlawr do we have any finalizers on CRD resources? If so, removing them manually can be tricky as k8s won't let the removal to go through until the controller would remove them manually. If you find that everything can be removed manually, lets come up with the steps to document the cleanup process for now, and we can address auto cleanup in the next release.

**Comment by cjellick** [comment]
We will leave this as-is, add it as a known issue, and address later
