### ISSUE TITLE
Passing config map to pipeline

### ISSUE THREAD

**Issue by NickRI** [rancher/rancher#15895]
Is there any simple solution to pass secret/config/environment to build stage of the pipeline (rancher v2.0.8)? We have dependencies in the private github's repository that should be used on building stage in empty jenkins's slave environment. Or can I bypass requirement of private keys/login&password somehow?

**Comment by NickRI** [comment]
I updated config.xml in config map jenkins for envVars and Volumes but it had no results. According source code it cannot be done somehow by jenkins's configuration.

**Comment by loganhz** [comment]
Hi @NickRI 

You can passing secrets and env to the build step in v2.1.0

You can find the document via https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/configurations/

![image](https://user-images.githubusercontent.com/21168270/46578691-4afeec00-ca38-11e8-9ac7-fd39c6b12cbe.png)

**Comment by loganhz** [comment]
We still need to support passing config map to pipeline
