### ISSUE TITLE
UI bug for adding users to an environment

### ISSUE THREAD

**Issue by tobowers** [rancher/rancher#1590]
If you go to the edit environment screen before clicking through to an environment, the UI errors. It recovers after clicking through to an environment.

![ui-users-bug](https://cloud.githubusercontent.com/assets/1274/8785076/40f5b8bc-2ef3-11e5-9a2f-ba26f45d6ff8.gif)

**Comment by aruneli** [comment]
Verified it is not reproducible with latest server/cattle (please pick 0.34 release builds).
