### ISSUE TITLE
Edges of progress bar for Resource Quota always a different color

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15914]
**Rancher versions:** 2.1 rc7

**Steps to Reproduce:**
example 1:
1.  Create a new project and set a resource quota
2. Create a namespace

example 2:
1.  Create a new project and set a resource quota
2. Create a namespace and use all resource so there is nothing left
3.  Create another namespace

**Results:**
Example 1:  The front edge of the progress bar is dark blue, making it look like some resource is already being used.
![image](https://user-images.githubusercontent.com/11514927/46372229-684e4780-c63f-11e8-9540-b2ab0055acf6.png)

Example 2:  The bar is all dark blue except a little bit at the end.  Which makes it look like there is some limit left
![image](https://user-images.githubusercontent.com/11514927/46372296-9764b900-c63f-11e8-979c-f045378cbdb2.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (11/28/18)
Confirmed fixed. The bars no longer show 1% used or 1% remaining which is what resulted in the issue. Additionally performed halo testing with the resource bars by fuzzing data and much more. One or more new issues will be created and this issue will be referenced.
