### ISSUE TITLE
DNS returning google.com.localdomain.local instead of google.com

### ISSUE THREAD

**Issue by cchance27** [rancher/rancher#15918]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/rancher:2.0.8
rancher/agent or rancher/rancher-agent :rancher/rancher-agent:v2.0.8

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.11.2
Canal: Calico - v3.1.1 Flannel - v0.9.1
Kube-DNS: 1.14.10

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux 7 (Core) 3.10.0-862.14.4.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Baremetal 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node  rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Ping from inside a container to google.com

**Results:**
I'm getting 
PING google.com.testenv.local (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.047 ms

I originally thought it was firewalld messing things up i disabled firewalld, and rebooted and it seemed to work but then i had to reboot the host again and once again it's not working back to pinging and appending the local domain to fqdn's. 

Not sure if i'm missing something but after 4 hours fighting with it figured i'd open an issue.

**Comment by superseb** [comment]
This is usually caused by configured domains having a wildcard DNS record catching the request due to ndots config in pods. Let us know if you need additional help on this.
