### ISSUE TITLE
fresh install rancher 2.0 error "Your connection is not private"

### ISSUE THREAD

**Issue by leetskil** [rancher/rancher#15927]
this is what i get after installed rancher 2.0 

`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:stable`

also added the cert below in manually in google chrome still not working.

`Your connection is not private
Attackers might be trying to steal your information from 192.168.1.11 (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_INVALID
Subject: cattle

Issuer: cattle-ca

Expires on: Oct 3, 2019

Current date: Oct 3, 2018

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIINIH7E5/W7oIwDQYJKoZIhvcNAQELBQAwKDESMBAGA1UE
ChMJdGhlLXJhbmNoMRIwEAYDVQQDEwljYXR0bGUtY2EwHhcNMTgxMDAzMTQ1MDAy
WhcNMTkxMDAzMTQ1MDA1WjAlMRIwEAYDVQQKEwl0aGUtcmFuY2gxDzANBgNVBAMT
BmNhdHRsZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANrhuHL6v5ad
lvWi16owDnIkOucMsDakkL3oQBfBuClmXEU/Q30hH1uQx/ZpPoy2Hy55b1GNsIax
DwTsuhN+umcbgeP9zilfZSkp02g4Fwj8NjsOv/Q7c92p//Sd4+TGOt46sz/FLKh3
q+boVq8DXSy9PI78aD2TF7ofOveODptZglYmNoz+FwCGaeHviwD0d1SnTOjIQWUo
rQlhGIkOD3xiLFWxLJRerS/OrJoEIytTuleYFeJP0z/GAukD8TLpm3HeW99obEmN
8gxoWz1a3wE2xdVYYL/j/VpqPy321tHmQ9B8EAyLMGVGGyG2WEUZ5mvMTmdv2po1
9U+8H8K2ZZ8CAwEAAaM6MDgwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsG
AQUFBwMBMBEGA1UdEQQKMAiCAIcEwKgBCzANBgkqhkiG9w0BAQsFAAOCAQEAwDzM
7ipgbNwuF8Mls0wK2Ygs5guyHgD9u840yhHdntWq9T3Bx+LnFqt9l7ZdzmU5UjDT
9+1x7XlnCBa2RZdNi4gQx+Jo8fs+XinyGrZ7O2KMbtI7n/2k1VBg6GLMyCPotyt1
5nHYCwdWjdNWX+6Sc9OAMchJ7HcoZKjBN8fezeqJ7Hox91mjQcSfwB7HVJrQTpyd
Apat5qet/WENOfNWnbW9RpsCdIswskZB7suc0SXa7Qz+/bf6LHUZLHx5OW5XCugu
X6uPSzYBbeb59TLXs7Uz96997OOGt+6TfHXfSd53dwHHaEqMDGWbUmBqSzNFsyAh
tV8HHSwJ7hrtnqmp0Q==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIC7jCCAdagAwIBAgIBADANBgkqhkiG9w0BAQsFADAoMRIwEAYDVQQKEwl0aGUt
cmFuY2gxEjAQBgNVBAMTCWNhdHRsZS1jYTAeFw0xODEwMDExNTU4NTZaFw0yODA5
MjgxNTU4NTZaMCgxEjAQBgNVBAoTCXRoZS1yYW5jaDESMBAGA1UEAxMJY2F0dGxl
LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt0I4ZH3OLBuXs4PF
EERdlMnMIvBAviUYfiENqMkEUL5/gKquh69deehPfKlZN1Ls1ow60MZv6eoTwNO5
SCbtaD+EU4RZN4qeAJGJb05uO3ruX3xjGciw3S/hWJ0qLqaExbpQeRCdc0sotr5/
9NKSJ6yw1CHir9jE+tUe7ckSArRStRLrvisFNHasbOzkeVNexbz8UYLuv2zmoKsA
A3FwQNyP9s4ieiemIAil4GpG6kICoXG6oUOp+1p/9zwtUtF5skR+4nOjSxc6AoA9
GuRAYS/0giPMxUJHKJ7pqkYWhAIgImMap/pXruX5nVETc22pb7chkoQ4iDPkJWss
B+WsuwIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAN
BgkqhkiG9w0BAQsFAAOCAQEAXmzqE1pr9MTda0dOabHRKF4MVm6CQBChfCu2gEE8
jGhXM5ZddbLzuKW0FVR15RasnMCZHrEOqJcL0bRIprzi9luSTks6oo8uJA9g07ll
jF+Xc5dYDJ9TfuAiNtAEoubYEfGnENQrMjFjP6koeaow0vRnsMILGsYDcuDMZJUG
brM0fDkW5s6ryFSMFRzI5a62X7S3iowaX5Ub0m8y/iLsFSAQ8YU1yZn+0DyhZzPb
w33cHLe222mhAl1bFDUXEQ9t8xxhxtFbAijRt+NwLSS2gmJZMx2aK1+XlNKT/zux
GbBDweXxBP9D1Bn2yiGnuwE0+CFRNmYkS4fHMX8f3a1vFA==
-----END CERTIFICATE-----

192.168.1.11 normally uses encryption to protect your information. When Google Chrome tried to connect to 192.168.1.11 this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be 192.168.1.11, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit 192.168.1.11 right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.`

**Comment by superseb** [comment]
Rancher uses a generated self signed certificate by default, all the SSL options are described here: https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#2-choose-an-ssl-option-and-install-rancher

You can bring your own self signed certificates or ones from a recognized CA, or use the built in Lets Encrypt to have a valid certificate.

**Comment by leetskil** [comment]
yes i've tried the HTTP Proxy Configuration Single Node Installation below but the problem still persist 

`docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -e HTTP_PROXY="http://192.168.10.1:3128" \
  -e HTTPS_PROXY="http://192.168.10.1:3128" \
  -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,192.168.10.0/24,example.com" \
  rancher/rancher:latest`

**Comment by superseb** [comment]
Configuring an HTTP Proxy to configure outgoing connections from Rancher, and configuring a certificate that is used to access Rancher are not the same. Maybe you can explain what you are trying to accomplish so we can think along that idea.

**Comment by leetskil** [comment]
i'm trying to install rancher/rancher 2.0 in my local environment using ubuntu 16.04 docker 17.03.2-ce using virtual-box, when i try to install

`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:latest/stable`

the first try was successful it worked fine with the single pem certificate which is generated by default

but i've created another virtual machine same specs above installed the rancher/rancher using the script when i load the corresponding ip the is used to launch rancher server 2.0 it prompt me with the error "`Your connection is not private" and now has two pem certificates. still working around with openssl to generate certificate.

**Comment by superseb** [comment]
The actual issue is there is no link to proceed. This is a browser issue which has plenty of information on the internet. Using another browser could possibly be the quickest. Apart from that, the cert options mentioned above point you to how to create your own self signed certificates or how to use certificates from a recognized CA or built-in Lets Encrypt.
