### ISSUE TITLE
Editing GKE cluster from GCE console and incrementing the node count does not update the node count in Rancher API 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15921]
**Rancher versions:**
rancher/server or rancher/rancher: v2.1.0-rc8

**Steps to Reproduce:**
1. Create a GKE cluster in rancher with scale of 3
2. Edit the cluster in GCE console to increment the node scale to 4
3. The new node gets added to the cluster
4. Edit the GKE cluster.
The node count still shows as 3 in UI . The API also shows the same
```
googleKubernetesEngineConfig": {
"diskSizeGb": 100,
"enableAlphaFeature": false,
"enableHorizontalPodAutoscaling": true,
"enableHttpLoadBalancing": true,
"enableKubernetesDashboard": false,
"enableLegacyAbac": false,
"enableNetworkPolicyConfig": true,
"enableStackdriverLogging": true,
"enableStackdriverMonitoring": true,
"machineType": "g1-small",
"maintenanceWindow": "",
"masterVersion": "1.10.7-gke.2",
"nodeCount": 3,
"projectId": "rancher-qa",
"type": "/v3/schemas/googleKubernetesEngineConfig",
"zone": "us-central1-f"
},

```
<img width="1365" alt="screen shot 2018-10-02 at 5 02 31 pm" src="https://user-images.githubusercontent.com/18536626/46383391-01438980-c665-11e8-9f79-335e0c00d5cd.png">

**Comment by cjellick** [comment]
@soumyalj  Is the new to 2.1 or pre-existing?

**Comment by cjellick** [comment]
Non-critical. moving out of v2.1
