### ISSUE TITLE
Cluster Options ordering is putting Windows Support option as first option

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15925]
**Rancher versions:**
rancher/server or rancher/rancher: v2 master 10/3

**Results:**
<img width="1410" alt="screen shot 2018-10-03 at 10 19 20" src="https://user-images.githubusercontent.com/2620179/46399551-4fee3380-c6f8-11e8-9cd0-51f1962f77ce.png">

**Comment by tfiduccia** [comment]
Version 2.2 master 10/31
Verified fixed
