### ISSUE TITLE
Ingress not functional in GKE imported cluster (HTTP Loadbalancing enabled)

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15928]
**Rancher versions:**
rancher/server or rancher/rancher: v2.1.0-rc8 
GKE cluster version: 1.10.7-gke.2
Issue also seen in v2.0.8 with the same GKE cluster version
**Steps to Reproduce:**
1. Create a GKE cluster in GCE with the config below.

<img width="528" alt="screen shot 2018-10-03 at 10 22 27 am" src="https://user-images.githubusercontent.com/18536626/46427426-4368db80-c6f6-11e8-93cf-30435752267a.png">

Note: HTTP Loadbalancing is enabled
This is the same config that is used when a GKE cluster gets created through rancher UI
2. Create an ingress(xip.io or with ingress specifying a host name)
3. The public end points do not get populated. Ingress is not functional

Note: Ingress created on a GKE cluster(with the same config as above) created through rancher is functional

**Comment by cjellick** [comment]
This is also present in v2.0.8, so it isnt a regression, so moving it out of v2.1
