### ISSUE TITLE
Change Azure RKE size to Standard_D2_v2 

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15932]
**Rancher versions:** 2.1 rc9

**Steps to Reproduce:**
1.  Go to Node Template
2.  Add Template
3.  Select Azure

**Results:**  Under Instance the size is Standard_A2.  Recommended for AKS is Standard_D2_v2 and that was changed from UI.  But the RKE template should stay consistent with that size and that has to be done in the API.

![image](https://user-images.githubusercontent.com/11514927/46434825-9c8e3a80-c709-11e8-9a34-3f62300017f0.png)

**Comment by cjellick** [comment]
We changed this in our direct AKS integration, but not for the node template. Related: https://github.com/rancher/rancher/issues/15864

**Comment by cjellick** [comment]
Scope is too big to get into v2.1. This is driven by the defaults in the `docker-machine` azure driver, which still has the default as A2

**Comment by deniseschannon** [comment]
Seems the related issue is fixed. @tfiduccia can you re-test?

**Comment by tfiduccia** [comment]
This is not fixed.  Size still says Standard_A2.  It was only fixed in AKS and not in the node template.

**Comment by cjellick** [comment]
Propose moving out of 2.2.x and into 2.3

**Comment by cjellick** [comment]
I merged the docker machine change, but need to release it

**Comment by cjellick** [comment]
@alena1108 since you did a machine release for another fix, this will get pulled into the rc when you merge the update to rancher/rancher for the new machine version

**Comment by cjellick** [comment]
Oh, i guess you didnt do the release, logan just opened PRs in anticipation of the machine release

**Comment by cjellick** [comment]
waiting for machine to get release and pulled into rancher

**Comment by soumyalj** [comment]
Tested with master build from June 6th
Navigate to Add Azure Node template 
The template shows  default size as `Standard_D2_v2`as expected. 
After the template is created, the API shows the correct size
```
"privateIpAddress": "",
"resourceGroup": "docker-machine",
"size": "Standard_D2_v2",
"sshUser": "docker-user",
"staticPublicIp": false,
"storageType": "Standard_LRS",
"subnet": "docker-machine",
```

Created a cluster successfully using the above Azure node template and the cluster was functional
