### ISSUE TITLE
Rename my pipeline

### ISSUE THREAD

**Issue by renperez** [rancher/rancher#15933]
I'm trying to rename my existing pipeline and I could not find a way to rename it. I checked the settings, view api etc. But I don't see any edit configuration that can lead to renaming the pipeline. Please help

Version: 2.x

**Comment by loganhz** [comment]
Hi @renperez 
Thanks for your report.
We have refactored the Pipeline UX in v2.1.0. There is no pipeline name now. It is just the name of your repo. Please have a try in v2.1.0.

Close this issue due to the new pipeline UX.
