### ISSUE TITLE
Add a rolling restart to a service

### ISSUE THREAD

**Issue by Kelindar** [rancher/rancher#1593]
Would be great if we had "Rolling Restart" as well here:

![image](https://cloud.githubusercontent.com/assets/583116/8789150/dd83b460-2f37-11e5-838d-411cc2f5d047.png)

My use-case is quite simple: we have a docker container that grabs the latest code bundle from S3 and we can update the app simply by restarting the container. So if we had a rolling restart which would wait until say, a healthcheck passes, we could update the entire cluster without taking it down. Not a big deal right now as we can do it manually, but could be useful for large clusters.

**Comment by vincent99** [comment]
Coming soon... https://github.com/rancher/rancher/issues/1079

**Comment by Kelindar** [comment]
Ah nice, sorry for duplicates. I've been heavily using rancher for a couple of weeks.

**Comment by deniseschannon** [comment]
@Kelindar Please follow #1079 to get updates.
