### ISSUE TITLE
Helm fails to accept answers to value.yaml got map expected string

### ISSUE THREAD

**Issue by mristok** [rancher/rancher#15931]
**Rancher versions:**
rancher/rancher: v2.0.8

**Docker version: (`docker version`,`docker info` preferred)**
17.3.2 and 18.6.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.5 LTS
4.4.0-131-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
Select catalog app, and attempt to pass service annotations via answers to values.yaml

Example:

influxdb.service.annotations.metallb.universe.tf/address-pool=core  <- fail - got map expected string
influxdb.service.annotations.external-dns.alpha.kubernetes.io/hostname=influxdb.k8s.lab  <- fail - got map expected string

influxdb.service.annotations."metallb.universe.tf/address-pool"=core <- fail - got map expected string
influxdb.service.annotations."external-dns.alpha.kubernetes.io/hostname"=influxdb.k8s.lab  <- fail - got map expected string

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15931
