### ISSUE TITLE
unable to use Gluster PersistentVolume

### ISSUE THREAD

**Issue by imwower** [rancher/rancher#15942]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent:

I followed the example here : https://github.com/kubernetes/examples/tree/master/staging/volumes/glusterfs
to create a glusterfs-cluster, and kubectl get ep, svc is OK:

NAME                         |ENDPOINTS                                         |AGE
------------ | -------|------
|endpoints/glusterfs-cluster   |192.168.0.110:1,192.168.0.111:1,192.168.0.112:1   |2h
|endpoints/kubectl             |10.42.0.33:42                                     |2h

NAME                        |TYPE        |CLUSTER-IP      |EXTERNAL-IP  |PORT(S)   |AGE
-----|----|--- | -------|---|---
service/glusterfs-cluster   |ClusterIP   |10.43.115.190   |<none>        |1/TCP     |2h
service/kubectl             |ClusterIP  

and then I created a pv and pvc,

![41427156](https://user-images.githubusercontent.com/1744486/46489663-98146f80-c838-11e8-98af-a7ef2435c43d.png)

![41507656](https://user-images.githubusercontent.com/1744486/46489741-c72ae100-c838-11e8-9c43-334de3bc35e7.png)

 but when I deploy nginx using this pvc, the UI hangs, after remove the pvc, everything is OK,

![41596593](https://user-images.githubusercontent.com/1744486/46489803-f7727f80-c838-11e8-88a9-522030c07c27.png)
the UI:
![41634906](https://user-images.githubusercontent.com/1744486/46489848-0fe29a00-c839-11e8-9fd3-56d936144077.png)

**Comment by loganhz** [comment]
@imwower Please provide the screenshot of `Events` section for the failed pod.
Or you can use `kubectl describe pod` to find out why the pod failed to start.

**Comment by imwower** [comment]
> @imwower Please provide the screenshot of `Events` section for the failed pod.
> Or you can use `kubectl describe pod` to find out why the pod failed to start.

hi, thanks for your reply, I resolved it by add gluster hosts to the k8s node machine, and intall gluster-client on the node.

**Comment by loganhz** [comment]
Cool!
Thanks
