### ISSUE TITLE
cross environment networking

### ISSUE THREAD

**Issue by su7970** [rancher/rancher#15949]
i do not if it is a good place to ask but any help is appreciated.

i have services running on different hosts at different environment to communicate between themselves. 
Currently this communication hits my DNS server very badly(in the sense of number of dns look up queries). Is there a way to specify the ip and hostname, i tried hosts file but it gets refreshed when container restarts. 
I have been researching about network policy manager and vxlan . if anyone can throw some light on how to enable cross environment service identification/networking .

Thanks

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
