### ISSUE TITLE
Many requests (pings, schemas..) from hosts

### ISSUE THREAD

**Issue by jgato** [rancher/rancher#15941]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.2
rancher/agent or rancher/rancher-agent: v1.2.2

Hi there,

Inspecting our nginx proxy for the Rancher Server we have discovered thousands and thousands of requests from our rancher-host to the server. Our hosting provider seems not happy about that. Is it normal to have so many requests in that way?

    IP1 - - [02/Oct/2018:06:07:37 +0000] “GET /ping HTTP/1.1” 200 5 “-” “Go-http-client/1.1” “-”
    IP2 - - [02/Oct/2018:06:07:37 +0000] “GET /ping HTTP/1.1” 200 5 “-” “Go-http-client/1.1” “-”
    IP3 - - [02/Oct/2018:06:07:37 +0000] “GET /ping HTTP/1.1” 200 5 “-” “Go-http-client/1.1” “-”
    IP1 - - [02/Oct/2018:06:07:37 +0000] “GET /ping HTTP/1.1” 200 5 “-” “Go-http-client/1.1” “-”
    …
    …
    IP2 - - [02/Oct/2018:06:07:39 +0000] “GET /ping HTTP/1.1” 200 5 “-” “Go-http-client/1.1” “-”
    IP2 - - [02/Oct/2018:06:07:39 +0000] “GET /ping HTTP/1.1” 200 5 “-” “Go-http-client/1.1” “-”
    IP3 - - [02/Oct/2018:06:07:39 +0000] “GET /ping HTTP/1.1” 200 5 “-” “Go-http-client/1.1” “-”

and other similars about getting configs:

    IP1 - CF5D57E06AB1D92AABDD [02/Oct/2018:06:07:36 +0000] “POST /v2-beta/publish HTTP/1.1” 201 0 “-” “Go-http-client/1.1” “-”
    IPX - 14370E6F7C5AC2FAA3E3 [02/Oct/2018:06:07:36 +0000] “POST /v2-beta/publish HTTP/1.1” 201 0 “-” “Go-http-client/1.1” “-”
    IP3 - 2FA1FD336D8CC87560FB [02/Oct/2018:06:07:36 +0000] “POST /v2-beta/publish HTTP/1.1” 201 0 “-” “Go-http-client/1.1” “-”
    …
    …
    IP4 - 052D4E4046CF52D1E043 [02/Oct/2018:06:07:36 +0000] “POST /v2-beta/publish HTTP/1.1” 201 0 “-” “Go-http-client/1.1” “-”

or, is it maybe the rancher server who is pinging the rancher hosts?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
