### ISSUE TITLE
Validate k8s 1.12

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15956]
Run a full validation against RKE clusters deployed with k8s 1.12 to certify this version

**Comment by soumyalj** [comment]
K8s v1.12.3 has been tested on the following :
1. RancherOS v1.4.2 with 17.03.2-ce
2. Ubuntu 16.04 hosts with Docker 17.03

**Comment by sangeethah** [comment]
```
Ubuntu 16.04 - docker version 17.03 , 18.06
RHEL 7.5 - docker version 1.13 (native)
ROS 1.4.2 - docker version it comes with
SLES - 12 SP2 - docker version 17.09.1_ce
Note - The list of validated docker versions supported by 1.12 kubernetes: 1.11.1, 1.12.1, 1.13.1, 17.03, 17.06, 17.09, 18.06
```

**Comment by soumyalj** [comment]
Rancher OS comes with 18.03 by default and its not in the supported list of docker versions. Hence ROS with 17.09 will be tested.

**Comment by soumyalj** [comment]
RHEL 7.5 - docker version 1.13 (native)
