### ISSUE TITLE
Skip public endpoints updates for pods

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15958]
Originally we were planning to populate public endpoints - the ip/port accessible for public traffic - on the pods, nodes and workloads. Practice showed that having them only on workloads would make the most sense as:

* pods are treated as resources that can be recreated at any point, and noone would use it as a application entry point
* setting public endpoints on the nodes is not a scalable solution

The public endpoints population was dropped for the nodes. Have to do the same for pods. That would also contribute positively to rancher performance.

**Comment by sangeethah** [comment]
@alena1108 Can you provide details on the workflows that need to be validated for this fix ?

**Comment by alena1108** [comment]
* Create a deployment with node port service
* Check the deployment's pod via view in api
* public endpoints field should either be empty or missing

**Comment by sangeethah** [comment]
This issue reproduces in 2.1.1 where pods of the deployment created with node port have `publicEndpoints`  created.

Tested with 2.2.2 server version:
Create a deployment with node port enabled. pods belonging to the workload does bot have `publicEndpoints` .
