### ISSUE TITLE
Backport: Logging in as Azure AD user with lots of groups is slow (#15858)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#15952]
Backport of https://github.com/rancher/rancher/issues/15858

**Comment by sangeethah** [comment]
Related issue - https://github.com/rancher/rancher/issues/16118

**Comment by sangeethah** [comment]
In rancher-server version v2.1.0 ,  logging in as a user who belonged to 1001 groups took about 50 - 55 seconds.

With rancher-server version v2.1.1-rc4 , logging in as a user who belonged to 1001 groups takes about 3 -4 secs.
