### ISSUE TITLE
LDAP setup test reveals secrets in debug level.

### ISSUE THREAD

**Issue by m-wcislo** [rancher/rancher#15965]
**Rancher versions:**
rancher/rancher:v2.0.8

**Steps to Reproduce:**
While trying to test LDAP setup when configuring authentication with my LDAP creadentials seems that people with access to debug level can view my password and LDAP service account password that is being used to check the connection.

**Comment by dramich** [comment]
This was removed [in this pr](https://github.com/rancher/rancher/commit/6c117d95e5b52f7f8bd75eb66f1436f8751b9aaa#diff-a2f0a53175259a170b9b0e8c9080d694L58).
