### ISSUE TITLE
heads up kurbenetes 1.12.0 release supports docker version 18.06 external dependencies

### ISSUE THREAD

**Issue by leetskil** [rancher/rancher#15964]
what version of kurbenetes is rancher 2.0 supporting?

kurbenetes version 1.12.0 supports docker 18.06 version 

changelog outdated information issue

https://github.com/kubernetes/kubernetes/issues/69216

kurbenetes 1.12.0  changelog below

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#external-dependencies

External Dependencies
The list of validated docker versions was updated to 1.11.1, 1.12.1, 1.13.1, 17.03, 17.06, 17.09, 18.06. (#68495)

**Comment by superseb** [comment]
All changes for k8s 1.12 support are tracked here https://github.com/rancher/rancher/issues/15872. 1.12 will be experimental in v2.1

**Comment by leetskil** [comment]
thanks
