### ISSUE TITLE
-caChecksum is a mandatory parameter for rancher/rancher-agent windows images

### ISSUE THREAD

**Issue by nlowe** [rancher/rancher#15966]
**Rancher versions:**
rancher/rancher: `v2.1.0-rc10`
rancher/rancher-agent: `v2.1.0-rc8` (Can't use rc10 because no 1803-nanoserver image exists yet)

**Infrastructure Stack versions:**
kubernetes (if applicable): `v1.11.3-rancher1-1`

**Docker version: (`docker version`,`docker info` preferred)**

<details>

<summary>docker version</summary>

```txt
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

</details>

<details>

<summary>docker info</summary>

```txt
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.2-ee-16
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: worker-03
ID: 754I:Y4L6:CMHU:C524:R2UV:TEMM:4E66:PWX6:TMK4:AJVD:LCLQ:XEF6
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

</details>

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```powershell
PS C:\Users\Administrator> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17134.0 Microsoft Windows NT 10.0.17134.0
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal (vSphere VM's). Single linux master / worker node, single windows worker node.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher, cert signed by publicly trusted CA.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

1. Deploy Rancher 2.1 Using Option C of the [single node install documentation](https://rancher.com/docs/rancher/v2.x/en/installation/single-node/) (Bring Your Own Certificate: Signed by Recognized CA)
2. Create a new cluster with windows support enabled
3. Deploy a linux master
4. Attempt to deploy a windows worker

**Results:**

The node-join command that is generated for windows does not include a `-caChecksum` parameter because we are using a certificate signed by a recognized CA. However, the powershell entrypoint script marks this as a required parameter:

https://github.com/rancher/rancher/blob/ba118e9ce42bfd45666570d4968e7c966a68019b/package/windows/start.ps1#L6

If I try to provide a dummy value the image refuses to start because it can't pull the CA cert:

```txt
ERRO[0000] Can't get cattle server CA from https://ranchertest.hyland.io, exit
```

If I add the CA's root cert at `/etc/rancher/ssl/cacerts.pem` and remove `--no-cacerts` I can get the agent to start.

**Comment by thxCode** [comment]
@nlowe , I build some images include the PR https://github.com/rancher/rancher/pull/16078 changes for testing, maybe you can retry as follow:

```
# run on server
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /<CERT_DIRECTORY>/<FULL_CHAIN.pem>:/etc/rancher/ssl/cert.pem -v /<CERT_DIRECTORY>/<PRIVATE_KEY.pem>:/etc/rancher/ssl/key.pem -e "CATTLE_AGENT_IMAGE=maiwj/rancher-agent:36012ba9" -e "CATTLE_WINDOWS_AGENT_IMAGE=maiwj/rancher-agent:36012ba9-nanoserver-1803" maiwj/rancher:36012ba9 --no-cacerts
```

**Comment by rbutcher** [comment]
@thxCode I had a cluster setup in Azure using a single node with LetsEncrypt and ran into this same issue. Running the modified container you provided allowed the Windows nodes to join without issue.

I actually run this command, obviously with the correct dns name.
```
sudo docker run -d --restart=unless-stopped \
-p 80:80 -p 443:443 \
-e "CATTLE_AGENT_IMAGE=maiwj/rancher-agent:36012ba9" \
-e "CATTLE_WINDOWS_AGENT_IMAGE=maiwj/rancher-agent:36012ba9-nanoserver-1803" \
maiwj/rancher:36012ba9 --acme-domain <YOUR.DNS.NAME>
```

**Comment by thxCode** [comment]
@rbutcher , is that work or not? :)

**Comment by rbutcher** [comment]
It is working! I should have been more clear.

**Comment by nlowe** [comment]
@thxCode Sorry for the delay, other priorities came up. The patched image you pushed does indeed work. When can we expect this to land in a release?

**Comment by thxCode** [comment]
@nlowe, The patched has already merged into master via  https://github.com/rancher/rancher/pull/16078.

**Comment by JohnnyElvis** [comment]
Any ETA for RC build with the patch?

**Comment by superseb** [comment]
This is merged in master, not in release/v2.1. Milestone is marked for v2.2

**Comment by laoshancun** [comment]
before v2.2 release,this repo may help you.
[`hualv/rancher-agent:v2.1.2-nanoserver-1803`](https://hub.docker.com/r/hualv/rancher-agent/)

**Comment by cjellick** [comment]
I guess this is ready for testing @loganhz ? please assign a QA

**Comment by kingsd041** [comment]
@thxCode 
I tested based on the latest rancher-agent (rancher/rancher-agent:v2.1.5-nanoserver-1803) and still have the same error.
```
C:\Program Files\rancher\start.ps1 : Cannot process command because of one or more missing mandatory parameters: caChecksum.
+ CategoryInfo          : InvalidArgument: (:) [start.ps1], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingMandatoryParameter,start.ps1
```

**Comment by kingsd041** [comment]
@thxCode 
I tested based on the latest rancher-agent (rancher/rancher-agent:v2.1.5-nanoserver-1803) and still have the same error.
```
C:\Program Files\rancher\start.ps1 : Cannot process command because of one or more missing mandatory parameters: caChecksum.
+ CategoryInfo          : InvalidArgument: (:) [start.ps1], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingMandatoryParameter,start.ps1
```

**Comment by sonaikar** [comment]
Exact same issue faced while adding windows node into 'custom' kubentes cluster created over AWS. 

Rancher Agent: 

> rancher/rancher-agent :v2.1.3-nanoserver-1803

Windows server 1803 is launched to add into kubernetes cluster.

Error observed:
```
C:\Program Files\rancher\start.ps1 : Cannot process command because of one or more missing mandatory parameters: caChecksum.
+ CategoryInfo          : InvalidArgument: (:) [start.ps1], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingMandatoryParameter,start.ps1
```

**Comment by kingsd041** [comment]
Tested with rancher/rancher:master(03/01) with rancher/rancher-agent:v2.2.0-rc2-nanoserver-1803

Windows nodes can be successfully added in this version. If the rancher is installed according to [Option C-Bring Your Own Certificate: Signed by Recognized CA](https://rancher.com/docs/rancher/v2.x/en/installation/single-node/), the `-caChecksum` parameter will be automatically removed from the node-join command and is not required.

**Comment by sonaikar** [comment]
Rancher cluster is created using Let’s Encrypt certificate. Is letsecrypt certificate not supported or having issues for windows nodes?

**Comment by sonaikar** [comment]
I tried using rancher-agent ` 
rancher/rancher-agent:v2.2.0-rc2-nanoserver-1803` and it is able to spin up rancher node, rancher dashboard shows the windows node connected and healthy. 

But the deployment over windows node is failing with below error. 

```ErrImagePull: rpc error: code = Unknown desc = failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\docker\windowsfilter\66ef94199a612e1e98fead6e0bca4f9b1f9f51bc37967972f67aa6ce8a40d2df: The system cannot find the path specified.```
