### ISSUE TITLE
Can't import GKE Cluster

### ISSUE THREAD

**Issue by B3DTech** [rancher/rancher#15972]
Rancher 2.0.7

I'm trying to import a GKE cluster into Rancher but running into an error using the insecure method.

kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user my.accout@domain.com
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "cluster-admin-binding" already exists

kubectl apply -f https://10.85.160.67/v3/import/km7s4d89z2rsqh55jl7vkdm8bqs5r5d9vkbhwz62cvbl57s7cfkdgq.yaml
Unable to connect to the server: x509: certificate signed by unknown authority

curl --insecure -sfL https://10.85.160.67/v3/import/km7s4d89z2rsqh55jl7vkdm8bqs5r5d9vkbhwz62cvbl57s7cfkdgq.yaml | kubectl apply -f -
namespace/cattle-system configured
serviceaccount/cattle unchanged
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding configured
secret/cattle-credentials-b56c0f8 unchanged
deployment.extensions/cattle-cluster-agent unchanged
daemonset.extensions/cattle-node-agent unchanged
Error from server (Forbidden): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "cattle-admin" is forbidden: attempt to grant extra privileges: [PolicyRule{APIGroups:["*"], Resources:["*"], Verbs:["*"]} PolicyRule{NonResourceURLs:["*"], Verbs:["*"]}] user=&{max.diorio@ieeeglobalspec.com  [system:authenticated] map[user-assertion.cloud.google.com:[AF1jyJAlelOR6WFHaU3ofyHzhKF4vlKccKkav3QDmNDm1AAFrDkn7mvT/pNTKV3OSD/XtDVQuoK6c30/XH0483nWG24e0uHbgzrMdp+I4WhBi/vTKyak1QwZ1HUc05Da//pOVsNBPeCvsQhCXlxK/Y4CtW1GkMfr7oruP5OG8VAsZ4/jX2IriVcyisdpRnG89lKkbINJeI+Ke62OntZkbW9AKaKO1/eg/KSmxc7ra5IbAYDvtKB4]]} ownerrules=[PolicyRule{APIGroups:["authorization.k8s.io"], Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/openapi" "/openapi/*" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version" "/version/"], Verbs:["get"]}] ruleResolutionErrors=[]

**Comment by B3DTech** [comment]
Oops - accidentally created the binding with the wrong account.  Had to delete it and re-create it first.

**Comment by ranjeethap** [comment]
I have created with the right account and still get the same error
Error from server (Forbidden): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "cattle-admin" is forbidden: attempt to grant extra privileges: [{[*] [*] [*] [] []} {[*] [] [] [] [*]}] user=&{ranjeetha@----.com  [system:authenticated] map[user-assertion.cloud.google.com:[AKUJVpnIxXk+TeJ05eAJHO97UzInN8GJ+jvQWWXgCFEkK0EmH7WYCJRQrG+ybiVFP+1a+w45xpYhQ9knJeOJqBbb1nx2c09WWoMhHKIpLa+7ujkFQ/yr7l6dNSsoVAJlVF+gNRkJPcqPX4S+RSblb5ZgUSH/sNoMd8rmmeOcFClWJJuY9yGHtHfMJ2kZV3f4B8s0adXkpsvoe2MeJjy8CGecIjlzM3Lb5tEPjR9cKAlnpAkisMk81OgtJUQ=]]} ownerrules=[{[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]}] ruleResolutionErrors=[]
