### ISSUE TITLE
RKE cluster provisioning refactor

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15975]
Following refactoring needs to be done to address potential etcd split brain scenarios

- [x] On kontainer-engine/rancher/rke side, separate getting cluster identity information - Certificates, kubeconfig - from the Create/Update call to its own Init method. Only once Init is finished, and identity info is persisted into DB, call update on RKE
- [x] On RKE side, revamp etcd reconcile logic and explore the possibility of **not** restarting the old etcd containers when new member joins the cluster
- [x] On RKE side ensure we handle tunnel disconnect well.
- [ ] Optional - Explore possibility of having common clusterUP logic instead of separate create/update calls

**Comment by moelsayed** [comment]
Related issues fixed by these changes:
https://github.com/rancher/rancher/issues/15695
https://github.com/rancher/rancher/issues/15970

**Comment by cjellick** [comment]
marked as p/1 to represent that its in alpha1, but the testing focus needs to be "ensure it doesnt break things"

**Comment by sangeethah** [comment]
Tested existing automated RKE cluster provisioning cases and manual cases around provisioning and editing clusters.

All cases worked fine except for the ones that involved azure with cloud provider set  which is tracked in  https://github.com/rancher/rancher/issues/16893
