### ISSUE TITLE
GKE Cluster Import - websocket: bad handshake 

### ISSUE THREAD

**Issue by B3DTech** [rancher/rancher#15973]
Rancher 2.0.7

GKE Created cluster, ran the import scripts successfully.  

Cattle-node-agent comes up successfully
cattle-cluster-agent is in a CrashLoopBackOff with the following errors repeated over and over. 

We have a VPN between our office and GCloud, and I have all ports opened between our Google Cloud subnets and the rancher server in both directions.

 
E  time="2018-10-05T21:14:27Z" level=info msg="Connecting to wss://10.85.160.67/v3/connect with token km7s4d89z2rsqh55jl7vkdm8bqs5r5d9vkbhwz62cvbl57s7cfkdgq"
 
E  time="2018-10-05T21:14:27Z" level=info msg="Connecting to proxy" url="wss://10.85.160.67/v3/connect"
 
E  time="2018-10-05T21:14:27Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
 
E  time="2018-10-05T21:14:27Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
 

and 

E  INFO: Environment: CATTLE_ADDRESS=10.4.1.10 CATTLE_CA_CHECKSUM=64a3b07463dd6c9de3b93faaf5711d37468e0ef7b17528be3ca39ae7054cdb05 CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-6dc5dc59cf-5zwg6 CATTLE_SERVER=https://10.85.160.67
 
E  INFO: Using resolv.conf: nameserver 10.0.32.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local c.kubernetes-testing-212220.internal google.internal options ndots:5
 
E  ERROR: https://10.85.160.67/ping is not accessible (Failed to connect to 10.85.160.67 port 443: Connection timed out)

**Comment by bradjones1** [comment]
I likewise am running into a similar issue. If you change `CATTLE_AGENT_CONNECT` TO `false`, the agent will start and communicate with the Rancher instance to which you are importing, however it then gives messages similar to #13129, which as far as I can tell relate to cluster roles, users, etc. not being present on the target cluster.

**Comment by derekssmith** [comment]
I am having this same problem with my cluster on AWS.  It looks like my cluster auto-upgraded to 2.1.0, and after that my clusters won't communicate.  I tried changing the SSL policy on the AWS load balancer, but that didn't fix it.  Right now my production Rancher cluster is dead in the water.  I am using `kubectl` to do all the management.  Very frustrating!

**Comment by bradjones1** [comment]
@derekssmith I was trying to stand up a group of clusters and ran into similar issues; I had the luxury of starting from scratch at 2.0.8 and it worked as advertised, so as I noted at https://github.com/rancher/rancher/issues/13129#issuecomment-427682786 I am wondering if this isn't a regression on 2.1.x related to imported clusters.

**Comment by derekssmith** [comment]
@bradjones1 it might be.  If it helps we have multiple clusters across different AWS accounts.  The only cluster that is working is the RKE cluster we installed to run Rancher, all of the imported clusters are down.

**Comment by B3DTech** [comment]
OK - so quick update.  I finally got kube-dns stubDomains working.

So current status:

Cattle-cluster-agent up and running with the following logs:

INFO: Environment: `CATTLE_ADDRESS=10.4.1.9` CATTLE_CA_CHECKSUM=64a3b07463dd6c9de3b93faaf5711d37468e0ef7b17528be3ca39ae7054cdb05 CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-bcfb454c6-wnml6 CATTLE_SERVER=https://rancher.internal.domain.com

INFO: Using `resolv.conf: nameserver 10.0.32.10` search cattle-system.svc.cluster.local svc.cluster.local cluster.local c.kubernetes-testing-212220.internal google.internal options ndots:5


cattle-node-agent stuck in CrashLoopBackOff with the following:

INFO: Environment: `CATTLE_ADDRESS=172.22.1.3` CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=64a3b07463dd6c9de3b93faaf5711d37468e0ef7b17528be3ca39ae7054cdb05 CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=gke-gc-1dk8clus01-default-pool-b054e8be-tmmt CATTLE_SERVER=https://rancher.internal.domain.com

INFO: Using `resolv.conf: nameserver 169.254.169.254` search c.kubernetes-testing-212220.internal google.internal
ERROR: https://rancher.internal.domain.com/ping is not accessible (Could not resolve host: rancher.internal.domain.com)



Here's where it's interesting:

We have are using a Shared VPC in GCloud.  

In the cattle cluster agent (deployment), it is using an Alias IP that's being used for containers.  That one uses kube-dns and points to the kube-dns ClusterIP service endpoint IP.

In the cattle node agent (daemon set), it is using the worker Node IP, and is getting the 169 name server, which isn't the kube-dns service.

So it seems the Kubernetes Worker Nodes aren't able to resolve the DNS entries correctly.

**Comment by B3DTech** [comment]
This seems like it's resolved, but it doesn't feel like it is happening the right way.

I had to edit the node /etc/systemd/resolved.conf to add our name server and domain.  Once that was done and I re-initialized the cattle-node-agent containers, they resolved the host name just fine. 

The next issue - Rancher doesn't see any pre-existing workloads at all.

**Comment by superseb** [comment]
The cattle-cluster-agent runs as Deployment, the pod will use the kube-dns service IP which then uses the host kube-dns is running on as upstream. This can be configured differently as shown here: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

cattle-node-agent is a DaemonSet using the host network, meaning it uses `/etc/resolv.conf` from the host. On GCP the metadata/DNS resolves internal and external domains, but apparently not your DNS record that is not resolvable by it.

Regarding workloads, Rancher shows all workloads that belong to a project. If you have existing namespaces, you can move them into a project to make them visible. For showing workloads not in a project, we have https://github.com/rancher/rancher/issues/15254 open.

**Comment by B3DTech** [comment]
Thank you Seb - moved them into projects and everything is fine now.

Regarding the DaemonSet - we're connected via SharedVPC and a VPN.  GCP has no way of lookup up hostnames outside of itself and the internet.  And since our hostnames are on our office domain, it just won't work.  It would be great if Google would provide better options than manually editing the resolved.conf file on each node, for every cluster manually.

**Comment by bluemalkin** [comment]
Hi, I'm also getting this issue and I also use Shared VPC. 
I can curl my Rancher server from the nodes but get the same error.
What is the fix please ?

**Comment by bradjones1** [comment]
For what it's worth I have found that this was due to not following exactly the instructions for upgrading from an "add-on" or simple deployment install to the helm chart. After installing from the helm chart, all is well.

**Comment by bluemalkin** [comment]
@bradjones1  I have a fresh install of 2.1.1 using the Helm Chart actually

**Comment by bluemalkin** [comment]
@MaxDiOrio  yes I can curl/ping/telnet the RANCHER_SERVER URL (not IP) from any node - no issue.

Strangely I noticed that the wget fails on the cattle-node-agent:
```
wget -O- https://xxxx
--2018-10-25 22:41:41--  https://xxxx
Resolving xxxx
Connecting to xxxxx|:443... connected.
ERROR: cannot verify xxxxx certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Unable to locally verify the issuer's authority.
To connect to xxxxxx insecurely, use `--no-check-certificate'.
```

My SSL is a Let's Encrypt with A+ rating. Is the node agent missing some CA's ?

```
time="2018-10-25T22:40:37Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-10-25T22:40:37Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

**Comment by bluemalkin** [comment]
Raised #16305

**Comment by luizportela** [comment]
I had the same problem with my environment, the "cattle-node-agent" was not able to connect in my rancher.

In my case,  I have a VPN between AWS and GCP. My rancher is on AWS and I was trying to import a GKE Cluster. The solution for me was add in the AWS VPC route tables a new route for the gke "Pod address range" using the VPN endpoint as a destination.
