### ISSUE TITLE
Links and Load Balancing across multiple Stacks

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1597]
Currently, a service and a load balancer can only be linked to services within the same stack. This enhancement would allow linking between stacks and allowing load balancing across stacks.

**Comment by jwhitcraft** [comment]
+1 for this.

**Comment by vincent99** [comment]
Dup of #1577

**Comment by silviupanaite** [comment]
In version v.0.32 cross linking is not working for LB and stacks

**Comment by deniseschannon** [comment]
@silviupanaite When you say it's not working, what do you mean? It might be related to the issues you are having with https://github.com/rancher/rancher/issues/1771

**Comment by silviupanaite** [comment]
Yes it is and sorry for the off topic.
