### ISSUE TITLE
Panic in /go/src/github.com/rancher/rancher/pkg/node/node.go:17

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15974]
Following panic was observed in 2.0.8 for embedded logging. Even though embedded logging is no longer supported in 2.1, the same code is being used by alert logic, and has to be revised:

```
2018/10/04 18:25:22 [ERROR] ClusterLoggingController  recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:155
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:367
/go/src/github.com/rancher/rancher/pkg/node/node.go:17
/go/src/github.com/rancher/rancher/pkg/controllers/user/logging/utils/embedded.go:372
/go/src/github.com/rancher/rancher/pkg/controllers/user/logging/utils/embedded.go:372
/go/src/github.com/rancher/rancher/pkg/controllers/user/logging/utils/embedded.go:336
/go/src/github.com/rancher/rancher/pkg/controllers/user/logging/utils/embedded.go:240
/go/src/github.com/rancher/rancher/pkg/controllers/user/logging/clusterlogging.go:194
/go/src/github.com/rancher/rancher/pkg/controllers/user/logging/clusterlogging.go:165
/go/src/github.com/rancher/rancher/pkg/controllers/user/logging/clusterlogging.go:150
/go/src/github.com/rancher/rancher/pkg/controllers/user/logging/clusterlogging.go:110
```

https://github.com/rancher/rancher/issues/15945

@aiwantaozi we should switch to calling https://github.com/rancher/rancher/blob/f47f78b0d3b6ee9c5e59bb204a16a204d473661e/pkg/node/node.go#L97 or https://github.com/rancher/rancher/blob/f47f78b0d3b6ee9c5e59bb204a16a204d473661e/pkg/node/node.go#L131 and get rid of GetNodeName method

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc3

* Created Rancher server & cluster
* Created notifier
* Created several alerts (pod / workload events)
* Saw alerts being fired

Did not see any panics in logs

**Comment by sangeethah** [comment]
Reopening to test in master

**Comment by jiaqiluo** [comment]
Validated on master 11/29

Steps:

1. ran Rancher server rancher: master
2. added a DO cluster
3. created notifier 
4. created several different types of alters 
5. deployed some workloads and catalog apps

Results:
alters were being fired and no panic in logs

Fix validated.
