### ISSUE TITLE
Cluster provisioning sometimes gets  stuck in "Failed to reconcile etcd plane: Failed to create etcd client for host: client: etcd cluster is unavailable or misconfigured"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15970]
Rancher server version - v2.1.0-rc10

Steps to reproduce the problem:
Create a custom cluster with following configuration:
2 control nodes
3 etcd nodes
3 worker nodes

Cluster stuck in provisioning state forever with ""Failed to reconcile etcd plane: Failed to create etcd client for host: client: etcd cluster is unavailable or misconfigured"

**Comment by galal-hussein** [comment]
After debugging the issue, i can see rancher server shows a `tunnel disconnect` issue:
```
Failed to reconcile etcd plane: Can't stop Docker container [etcd] for host [x.x.x.x]: error during connect: Post http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/containers/etcd/stop: tunnel disconnect
```

rke fails and tries to provision the cluster again but it stuck to connect to the etcd container stopped in the previous run.

Note: i can find a lot of `tunnel disconnect` errors when adding nodes in custom clusters simultaneously

**Comment by sangeethah** [comment]
Tested with latest build from master - Nov 28.

Create a custom cluster with following configuration:
2 control nodes
3 etcd nodes
3 worker nodes

Cluster got created successfully. Tested this scenario multiple times and did not see the issue reported in the big.

**Comment by sarmak1179** [comment]
Hi,
I am seeing this issue quite often on my environment. The local cluster is setup with rke and I am adding another cluster with 3 All role nodes and additional worker nodes.
Provisioning is stuck at this message,
Failed to reconcile etcd plane: Can't stop Docker container [etcd] for host [XXX]: error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/etcd/stop?t=5: tunnel disconnect

and later with this message
This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.

Failed to reconcile etcd plane: Failed to create etcd client for host [XXX]: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp XXX:2379: connect: connection refused

This is with latest stable rancher 2.1.3
