### ISSUE TITLE
Upgrade to Rancher 2.1.0 kills Prometheus installed from Helm.

### ISSUE THREAD

**Issue by jannylund** [rancher/rancher#15986]
**Rancher versions:**
rancher/rancher: v2.1.0

**Steps to Reproduce:**
- Install Rancher 2.0.4 / 2.0.8.
- Install Prometheus from Helm through Catalog apps.
- Verify Prometheus runs nicely.
- Upgrade to Rancher 2.1.0.

**Expected Result:**
- Prometheus still runs nicely on the same version as before.

**Actual Result:**
- Catalog app was automatically upgraded to latest and Helm failed with error `Failed to install app prometheus. Error: Chart incompatible with Tiller v2.10.0-rancher4`
<img width="1186" alt="screenshot 2018-10-07 12 23 55" src="https://user-images.githubusercontent.com/121457/46580357-e3db3a80-ca2b-11e8-997a-f38dbc295168.png">

**Comment by StrongMonkey** [comment]
Looks like our tiller version doesn't correctly get resolved when comparing semantic version

**Comment by soumyalj** [comment]
Tested with master. Created GKE cluster(which has storage class enabled by default) and installed Prometheus from Helm through Catalog Apps.
Prometheus catalog was installed correctly.
<img width="1254" alt="screen shot 2018-11-21 at 10 47 03 am" src="https://user-images.githubusercontent.com/18536626/48862564-97e61a00-ed7b-11e8-820e-924ff16ad15c.png">

**Comment by ablekh** [comment]
Hmm ... I seem to experience the same issue, but with a JupyterHub chart (AKS, K8s v1.12.6). Any ideas?

**Comment by rmweir** [comment]
Hello @ablekh, can you please open a new issue for this?

**Comment by ablekh** [comment]
@rmweir Hi! Sure, I will open a new issue for this problem and link to this one for reference.
