### ISSUE TITLE
Manually triggering a pipeline does not run all stages if there are trigger rules on a stage exempting it.

### ISSUE THREAD

**Issue by KaelBaldwin** [rancher/rancher#15982]
**Rancher versions:**
rancher/rancher v2.1.0

**Steps to Reproduce:**

1. Create a pipeline connected to a remote repository I used our develop branch as the target.
2. Create a stage, while creating, click "show advanced options"
3. Add a trigger rule for "Run this rule when"
4. Select Event is Pull Request.
5. Save everything.
6. Manually run the pipeline.

**Results:**

The stage with a trigger rule was skipped.

**Expected Results**

Manually triggering a pipeline should run all stages.

This is needed so that the steps can be tested without going through the hoops of creating a branch and a Pull Request just to test the stages themselves.

Pre rancher/rancher v2.1 this was working.

**Comment by gitlawr** [comment]
There can be cases that users want pipelines to obey the rules. Say, when I set `branch=dev` condition for stage A, `branch=master` condition for stage B, I would hope not to run stage B when I manually trigger a run on branch dev.
But It would be helpful for testing if we can have an `Ignore condition rules and run all steps` option when we do a manual run.

**Comment by KaelBaldwin** [comment]
or maybe you can manually trigger it as a particular event. That might be even more useful for testing.
