### ISSUE TITLE
Health check renders edit form in read only mode.

### ISSUE THREAD

**Issue by jannylund** [rancher/rancher#15987]
**Rancher versions:**
rancher/rancher: 2.0.4 + 2.1.0

**Steps to Reproduce:**
- Create a deployment, for example jwilder/whoami
- Add a health check, for example HTTP check on port 8000.
- Click Launch / Upgrade
- Click on the workload and expand Health Check.

**Expected result:**
- Read only Readiness check is visible.
- Liveness check is either hidden or visible as readonly.

**Actual result:**
- Liveness check editable form is visible.

<img width="1445" alt="screenshot 2018-10-07 17 40 27" src="https://user-images.githubusercontent.com/121457/46582983-1a2eaf00-ca58-11e8-914c-a88b7be0956b.png">

**Comment by jannylund** [comment]
I would have expected this commit to fix this, or am I mistaken? https://github.com/rancher/ui/commit/8dcabaf5877080e9d947fed44a85a2c63458243a

**Comment by loganhz** [comment]
Thanks for your report!

Missed one line in the previous fix https://github.com/rancher/ui/blob/master/app/workload/template.hbs#L172

**Comment by tfiduccia** [comment]
Version - 2.2 master
Verified fixed
