### ISSUE TITLE
Pipelines are not being triggered by pull requests.

### ISSUE THREAD

**Issue by KaelBaldwin** [rancher/rancher#15983]
**Rancher versions:**
rancher/rancher v2.1.0

**Steps to Reproduce:**

1. Create a pipeline connected to a remote repository I used our develop branch as the target and our repository is hosted on github.
2. Create a stage, while creating, click "show advanced options"
3. Add a trigger rule for "Run this rule when"
4. Select Event is Pull Request.
5. Save everything.
6. Go to your repository in github.
7. create a pull request.

**Results:**

Creating the pull request did not trigger the pipeline at all.

**Comment by cloudnautique** [comment]
Is the rancher server accessible to the github server? Can you check the webhook history on the github webhook settings page?

**Comment by loganhz** [comment]
Hi @KaelBaldwin , 

Please try to select `Pull Request` in setting of the pipeline.

`Step 4 Select Event is Pull Request.` is for the stage. 
But user still need to set the trigger event for the whole pipeline. 

![image](https://user-images.githubusercontent.com/21168270/46573533-5a931c00-c9c9-11e8-950b-7539bd150806.png)

![image](https://user-images.githubusercontent.com/21168270/46573540-67177480-c9c9-11e8-9a76-6f49671b7bf4.png)

**Comment by KaelBaldwin** [comment]
I see awesome. I missed that, thanks.
