### ISSUE TITLE
(Rancher 2.0.4 + 2.1.0) Health check headers are ignored

### ISSUE THREAD

**Issue by jannylund** [rancher/rancher#15988]
**Rancher versions:**
rancher/rancher: 2.0.4 + 2.1.0

**Steps to Reproduce:**
- Create a deployment, for example jwilder/whoami
- Add a health check, for example HTTP check on port 8000.
- Add a Host Header and an Additional Header
- Click Launch / Upgrade

**Expected result:**
- Headers are used in health check.

**Actual result:**
- Headers disappear. They are not visible in YAML nor in readonly / edit mode.

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/13547
