### ISSUE TITLE
Failed to reconcile etcd plane

### ISSUE THREAD

**Issue by VijaySrinivas85** [rancher/rancher#15999]
Hi,

I have successfully created a cluster with 6 nodes in rancher and while trying to add a new node to the cluster I’m getting the error “Failed to reconcile etcd plane: Failed to add etcd member”
I was successful in adding 4 nodes but getting error while adding 2 nodes.

Are there any other steps that I need to follow to add the nodes?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`node`|

**Comment by VijaySrinivas85** [comment]
What kind of cluster are you creating -- Created custom cluster

what version -- Rancher v2.0

what hosts/machines are you using -- We are using Rancher OS using static IP

what hostnames are being used -- Using Local host name

Were the nodes re-used -- No, they are new nodes

what is different about the 2 nodes you are adding vs the other 4 -- 3 Nodes are worker nodes which were added successfully. 3 Nodes under etcd and control plane, out of 3 I was able to added one node successfully and the remaining 2 are giving error while trying to add the nodes.

**Comment by superseb** [comment]
Please supply the complete log from `rancher/rancher` container which shows the provisioning steps.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
