### ISSUE TITLE
 Multi-node cluster schedule failed

### ISSUE THREAD

**Issue by dongjuanwinhong** [rancher/rancher#15995]
**Rancher versions:**
rancher/server or rancher/rancher:v2.1.0
rancher/agent or rancher/rancher-agent:v2.1.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Steps to Reproduce:**

1. create cluster with 2 nodes
![image](https://user-images.githubusercontent.com/39041059/46595058-2f174b00-cb09-11e8-9954-b27a2cce5d73.png)
2.deply a service
![image](https://user-images.githubusercontent.com/39041059/46595167-b664be80-cb09-11e8-84d4-1782354a5ed8.png)
3. Execute “hostshutdown -h now” on the host dj153
![image](https://user-images.githubusercontent.com/39041059/46595379-af8a7b80-cb0a-11e8-8a14-2a5b17017f41.png)

**Results:**
This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.

Failed to communicate with API server: Get https://192.168.101.154:6443/api/v1/componentstatuses?timeout=30s: dial tcp 192.168.101.153:6443: connect: no route to host
![image](https://user-images.githubusercontent.com/39041059/46595043-19098a80-cb09-11e8-8479-4bf480cefa59.png)
![image](https://user-images.githubusercontent.com/39041059/46595379-af8a7b80-cb0a-11e8-8a14-2a5b17017f41.png)

**Comment by superseb** [comment]
This is expected, 2 nodes give you 0 fault tolerance, see https://coreos.com/etcd/docs/latest/v2/admin_guide.html#optimal-cluster-size.

We have https://github.com/rancher/rancher/issues/15075 open to provide more guidance on cluster creation and state.
