### ISSUE TITLE
External cluster rancher bootstrap fails after initial successful cluster import

### ISSUE THREAD

**Issue by krwrang** [rancher/rancher#15998]
### Rancher versions:
rancher/rancher: 2.0.8
rancher/rancher-agent: 2.0.8
rke: 0.1.9
### Infrastructure Stack versions:
kubernetes: v1.11.2-rancher1-2
### Docker version:
17.03.2-ce
Using `https://releases.rancher.com/install-docker/17.03.sh`
### Operating system and kernel:
Ubuntu 16.04.4 LTS
4.4.0-124-generic
### Type/provider of hosts:
Private on-premises OpenStack Cloud
Unless otherwise mentioned, all servers get a "public" floating ip that the control plane uses to route traffic to servers; the servers themselves do not see the floating ip's assigned to them
All servers have private ip addresses from 192.168.0.0/24 range

- Cloud 1 - Rancher Master cluster - Floating IP range: 10.133.240.0/21
- Cloud 2 - Customer cluster 1 - Floating IP range: 10.133.160.0/19
- Cloud 3 - Customer cluster 2 - Floating IP range: 10.164.128.0/19

Inter-cloud networking happens via floating ip addresses
Used OpenStack flavor: 2 core CPU, 8GB RAM, 32GB disk
[All IP addresses used in all the servers involved](https://gist.github.com/krwrang/8edf3465e3e1e9a9e4f9db8fcef34c0c)
### Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
5-node HA Rancher master cluster, created using [this rke template](https://gist.github.com/krwrang/a852ba6b6930497e1ad966d083b135c3)
Floating ip's assigned from 10.133.241.0/21 range
### Steps to Reproduce:

_Customer clusters have 3 control plane/etcd nodes, 3 edge worker nodes, and 3 worker nodes without a floating ip._

- Customer cluster 1 name: ces-es-si-os-dhn-78
- Customer cluster 2 name: ces-es-si-os-dhn-80

Customer clusters are imported as follows:
**Step 1: Initialize cluster in Rancher**
`rancher clusters create --k8s-version v1.11.2-rancher1-1 --rke-config /tmp/customer_rke_cluster.yml ces-es-si-os-dhn-78`
[/tmp/customer_rke_cluster.yml](https://gist.github.com/krwrang/b15f595eb9cd55a039e1168e4ae28244)
**Step 2: Extract registration token**
`rancher clusters add-node --etcd --management --worker ces-es-si-os-dhn-78`
**Step 3: Bootstrap Rancher nodes**
_For externally accessible nodes (etcd/control plane/edge worker)_
`docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://mastercluster --token <previously_extracted_token> --ca-checksum <previously_extracted_ca_checksum> --address <floating_ip> --internal-address <private_ip> --etcd --control-plane/--worker`
_For non-externally accessible nodes (worker)_
`docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://mastercluster --token <previously_extracted_token> --ca-checksum <previously_extracted_ca_checksum --address <private_ip> --worker`
### Results:

**_Customer cluster 1 import_**
Imports successfully, logs:
- [Master cluster, rancher/rancher](https://gist.github.com/krwrang/324714b51e68a6adecd64231a67390e9)
- [Customer cluster 1, rancher-agent](https://gist.github.com/krwrang/9509346cd23d7d2afb2c01186c6c7a87)
- [Customer cluster 1, syslog](https://gist.github.com/krwrang/5b244e5d33831f883b024316a21baae7)

**_Customer cluster 2 import_**
Control plane nodes begin Rancher bootstrap, but bootstrap does not progress. During provisioning, Rancher indicates it cannot connect to etcd ports on customer cluster 2. No port checker pods are running on customer 2 on any node; however Rancher has attempted to start port checker nodes on Customer 1.
- [Master cluster, rancher/rancher](https://gist.github.com/krwrang/0748ed88bdb9731b31eb0de836ea76e2)
- [Master cluster, docker journal](https://gist.github.com/krwrang/ed8a368b4dd7a2a06675d983d2baab4b)
- [Customer cluster 2, rancher-agent](https://gist.github.com/krwrang/1c1cb0d10e998ea630a59e008d5fa578)
- [Customer cluster 2, additional rancher-agent never present during first import](https://gist.github.com/krwrang/7cff11d8adac8feee3079d34dc01ffdf)
- [Customer cluster 2, second additional rancher-agent never present during first import](https://gist.github.com/krwrang/c572e7aaa11d1b3e19a73140dc4a4843)
- [Customer cluster 2, syslog](https://gist.github.com/krwrang/89f36cd590634ee59d5abedc8a6ba5de)
Logs from customer 1, with rke-tools -pods running as port checkers.
- [Customer cluster 1, docker ps -a, see first two rke-tool images](https://gist.github.com/krwrang/775037cffd7137b5523c74946a6d78c4)
- [Customer cluster 1, syslog](https://gist.github.com/krwrang/f94d7b0ebb6ee2916fd70f400decfc1e)
- [Customer cluster 1, docker service journal](https://gist.github.com/krwrang/2bc51bbeb7540abc6f4ab616ff8727b1)

**Comment by superseb** [comment]
Probably because you are using the same hostnames in different clusters, see https://github.com/rancher/rancher/issues/15456 and https://github.com/rancher/rancher/issues/15943.

Let me know if that doesn't solve the issue.
