### ISSUE TITLE
how to add a new node to an existing cluster?

### ISSUE THREAD

**Issue by imwower** [rancher/rancher#15993]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent:

I can only add new cluster for the UI, but each cluster only has one work-node,
how can I add new node to the existing cluster?

**Comment by loganhz** [comment]
It's in the cluster edit page. 
Please look at the doc first. https://rancher.com/docs/rancher/v2.x/en/

If you have a WeChat account. Please find us by searching `rancher2`
