### ISSUE TITLE
When "," is used in the host name, we are not able to service request with headers which has exact match/one of the host names.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1599]
Build from master:

Steps to reproduce the problem:
Create a LB service with target services having "," in  host name like "test1,test2,test3".

<img width="679" alt="screen shot 2015-07-21 at 12 40 10 pm" src="https://cloud.githubusercontent.com/assets/4266958/8812837/54262b22-2fb3-11e5-8c54-a78c0eedc732.png">

Access LB with host set to "test1"/"test2"/test3"/"test1,test2,test3" . We get "503 service unavailable"

> wget --header="host: test1" http://146.148.79.190:8080/service1.html
--2015-07-21 14:10:02--  http://146.148.79.190:8080/service1.html
Connecting to 146.148.79.190:8080... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2015-07-21 14:10:02 ERROR 503: Service Unavailable.

>wget --header="host: test1,test2,test3" http://146.148.79.190:8080/service1.html
--2015-07-21 14:10:12--  http://146.148.79.190:8080/service1.html
Connecting to 146.148.79.190:8080... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2015-07-21 14:10:13 ERROR 503: Service Unavailable.

**Comment by alena1108** [comment]
You have to create a separate host name routing rule for each host/service combination to make this work. Passing "a.com,b.com,c.com" as a single host wouldn't work. Closing the bug for now.
