### ISSUE TITLE
imagePullSecrets gone after upgrade when using namespace scoped registry credential

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#15994]
**Rancher versions:**
rancher/rancher:v2.1.0

**Steps to Reproduce:**
1.  Add a registry in Rancher UI. 
2.  Select `Available to a single namespace`
3.  Deploy a workload in the same namespace with image `loganhz/aa:v1`
4.  Check the imagePullSecrets has been added automatically
5.  Upgrade the image version in the workload to `loganhz/aa:v2`
6.  Click `Upgrade`

**Results:**
`imagePullSecrets` is gone.  Docker can not pull the image on the private registry

**Comment by loganhz** [comment]
Please feel free to move it out from `v2.1.1`

**Comment by kinarashah** [comment]
Looks like the bug was introduced in 2.0.7, when `setSecrets` was added for workload updates

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/15994 as it was filed first

**Comment by kennyjohnson2** [comment]
This bug resurfaces when using kubectl set deployment to upgrade a workflow, and then trying to upgrade again through the web UI. You can use one or the other in perpetuity, but once the kubectl command is used, the imagepullsecrets entry is removed during an upgrade done through the web UI

**Comment by shuckepco** [comment]
Ehm... You closed this issue in favor of _itself_ @alena1108 ?! :-)

**Comment by loganhz** [comment]
@shuckepco this one https://github.com/rancher/rancher/issues/15725

**Comment by loganhz** [comment]
and it will be released in v2.1.2 with https://github.com/rancher/rancher/issues/16202

**Comment by shuckepco** [comment]
Thx!
