### ISSUE TITLE
rancher/types  go generate lack function about gitlab/github 

### ISSUE THREAD

**Issue by qingfengming** [rancher/rancher#15996]
version : rancher/rancher 2.1 ,rancher/types latest

I am trying to get go-rancher from rancher/types.

when i use go generate in rancher/types,in the rancher/types/client/project/v3/zz_generated_gitlab_pipeline_config.go, there should be some func like auth gitlab/github app function.   

but there is nothing except some types declare.

![code](https://user-images.githubusercontent.com/16607730/46602577-2f244480-cb23-11e8-8e47-b209a091daad.png)

Any comments will be much appreciated ！

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
