### ISSUE TITLE
Allow to configure additional tolerations for cluster-agent, node-agent rancher will deploy

### ISSUE THREAD

**Issue by ukinau** [rancher/rancher#15990]
This is the feature requests for new 2 configurations (settings).
* first one is the "tolerations-of-clusteragent" which will accept json string to indicate additional tolerations which will be applied to Deployment resource for cluster-agent.
* second one is the "tolerations-of-nodeagent" which will accept json string in the same way as "tolerations-of-clusteragent". Only difference from it is this tolerations will be applied to DaemonSet resource for node-agent.

Background of this feature request is that Rancher is expected to maintain many type of k8s cluster deployment and agent is needed to deploy/run on the user cluster if we want to maintain a certain cluster. 
But currently tolerations which is the concept to schedule POD to Node is hardcoded for rancher-agent deployment and only the taints configured by rancher/rke is considered to tolerate, which means rancher-agent won't run on some node if user configured own taints for nodes. 
Due to limitation, some user can not maintain some clusters. So it would be nice if rancher provide the way to configure additional tolerations for rancher-agent via configuration

**Comment by superseb** [comment]
This is a subset of https://github.com/rancher/rancher/issues/15734 and is basically needed for all system pods as you run into it for every one.

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/16050 for another example, if this can be handled more easily than adding more settings I'm all for that.

**Comment by superseb** [comment]
I don't see a benefit of having configurable tolerations, versus having a toleration for all taints as the pods needs to be scheduled to every node anyway. And making it configurable is not only yet another configuration option, it's also not that clear for an user that they need to edit a setting after tainting their nodes (plus the situation where it changes when half the clusters are already running, which is kind of the same with changing server-url/certificates).

@ukinau I'm planning to re-open https://github.com/rancher/rancher/issues/16050 and put a fix allowing all taints for the agents. Let me know if you don't agree.
