### ISSUE TITLE
When editing LB service , UI does not complain when target port is not specified for services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1600]
Build from master:

Edit an existing LB service.
Add a new target without specifying target port and save.
UI does not complain when target port is not specified for services. But the new target does not get saved since target port is a required parameter.

Expected Behavior:
UI should warn users when user tried to save when target port is not specified .

**Comment by vincent99** [comment]
We're back to allowing rules with no target port specified now, it will use the Default Target Port on the Listener or the Source Port of the request if that is also not set.

**Comment by sangeethah** [comment]
with server version - V0.29.0-rc1 , we have the "sourceport" and "defaultTargetPort" in "Listening Ports" section which should be used as default target port.

Closing this issue.
