### ISSUE TITLE
Backport: Upgrade to Rancher 2.1.0 kills Prometheus installed from Helm

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16008]
https://github.com/rancher/rancher/issues/15986

And review the rest of rancher templates to see if they are compatible with the tiller version Rancher 2.1.x uses

**Comment by loganhz** [comment]
The issue happens in the charts from helm-stable.
All of charts with `tillerVersion` defined will have this issue.
I don't think we have apps with `tillerVersion` in our Library charts. 

We need to trim our version `2.10.0-rancher4`

1. Do smoke tests for charts in Library
2. Do smoke tests for charts in Helm Stable (such as Prometheus)
3. Test upgrade case from v2.0.8 to v2.1.1 with Prometheus from helm stable and Prometheus from library
4. Test upgrade case from v2.0.8 to 2.1.0 and then 2.1.0 to 2.1.1  with Prometheus from helm stable and Prometheus from library

**Comment by soumyalj** [comment]
Reproduced the issue in fresh install of v2.1.0 and also on an upgrade from v2.0.8 to v2.1.0.
Tested with v2.1.1-rc4. 
1. Deployed Prometheus from Helm charts successfully on a freshinstall setup.
2. Upgraded from v2.0.8 with prometheus (from helm charts) to v2.1.1-rc4. Prometheus was still functional after upgrade with no errors
