### ISSUE TITLE
Panic in controller

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16000]
@janeczku encountered the following panic
![screen shot 2018-10-08 at 15 52 31](https://user-images.githubusercontent.com/2473240/46618853-68ce5e80-cad5-11e8-96e6-8c2c22fac8fe.png)

**Comment by jiaqiluo** [comment]
Validated on master 11/29

Steps:

1. ran Rancher server rancher: master
2. added a DO cluster
3. created notifier 
4. created several different types of alters 
5. deployed some workloads and catalog apps

Results:
alters were being fired and no panic in logs

Fix validated.
