### ISSUE TITLE
Backport: Can not upgrade Rancher installed via RKE addon to v2.1.0 in HA Mode

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16013]
Backport a fix for https://github.com/rancher/rancher/issues/16012

**Comment by deniseschannon** [comment]
We have decided that we no longer support v2.1 install using the RKE add-on methods. We only support/work with the helm chart install. 

This is now documented as expected. 

https://github.com/rancher/rancher/issues/16033
