### ISSUE TITLE
Global DNS: UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16015]
This ticket is to track UI work for https://github.com/rancher/rancher/issues/16014

**Comment by westlywright** [comment]
I'm marking this as resolved because the UI is done but we're waiting to merge as the backend is adding RBAC around the new feature

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/25/19) HA Setup
Confirmed feature. Multiple bugs were entered around this however no critical issues were identified during my UI testing. RBAC was not included in my tests and this is in progress with others on our team. HTTP validation was performed as well as validating the API to ensure everything we submitted in request payloads was correctly taken by the rancher server. Further testing will continue in this area and a few more bugs may be created if any found. Halo testing and fuzzing of data was also performed.
