### ISSUE TITLE
Multi Cluster App: UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16017]
This ticket is to track UI work for Multi Cluster App feature: https://github.com/rancher/rancher/issues/16016

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/25/19) HA Setup
Confirmed feature. Several bugs were entered around this and some may need to be resolved before 2.2 GR. RBAC was not included in my tests and this is in progress with others on our team. HTTP validation was performed as well as validating the API to ensure everything we submitted in request payloads was correctly taken by the rancher server. Further testing will continue in this area and a few more bugs may be created if any found. Halo testing and fuzzing of data was also performed.
