### ISSUE TITLE
Environments with a high volume of DNS queries will drop them from time to time

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16018]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.21 (this impacts 2.x as well)
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Description of the problem:**
Weave has some great research done here,
https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts

**Results:**
Not sure if we need to move away from kube-dns behind a service IP, but thats for architects to decide.

**Comment by Oats87** [comment]
If `kube-dns` were to be run as a daemonset, the `kubelet` could be configured to configure pods to forward DNS queries to the local node's kube-dns rather than traversing through the service IP, it should be possible to avoid having the kernel drop DNS query packets.

**Comment by superseb** [comment]
https://github.com/kubernetes/kubernetes/issues/56903

**Comment by aemneina** [comment]
@superseb @alena1108, @Oats87 pointed me to Node Local DNS, which should be a solid solution. Forces dns lookups over TCP. I believe it's alpha in 1.13.x
https://github.com/kubernetes/kubernetes/pull/70555

**Comment by alena1108** [comment]
@aemneina that would be the best solution given it's officially supported by k8s. And that k8s 1.13 was released today, 12/03/2018 :)
