### ISSUE TITLE
Multi Cluster App

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16016]
Implement Multi Cluster App - a feature allowing to define a helm based template application that can be deployed to projects in multiple clusters, and (optionally) registered to a Global Load Balancer (https://github.com/rancher/rancher/issues/16014)

**Comment by alena1108** [comment]
Cover following things before considering a feature ready:

- [X] multi cluster app deployment to different projects @mrajashree 
- [ ] RBAC for the multi cluster app with an ability to share the app cross members @mrajashree 
- [ ] rolling upgrade with the batch size as a parameter @kinarashah 
- [ ] as a part of a rolling upgrade, we have to start storing the app state on the app object (today the logic is done on the UI side) and aggregated state on the multi cluster app. Rolling upgrade should work off that state @kinarashah

**Comment by alena1108** [comment]
Created a separate ticket for ALL targets support: https://github.com/rancher/rancher/issues/17520

**Comment by bmdepesa** [comment]
rancher/rancher:master

Basic use cases are working.

**Comment by luisdavim** [comment]
where can I find the documentation around this feature?

**Comment by superseb** [comment]
Documentation is added when there is an official release containing the feature.

**Comment by luisdavim** [comment]
But is there a repo with the source of the documentation that I can look at? When will this be released?

**Comment by superseb** [comment]
https://rancher.com/docs/rancher/v2.x/en/contributing/#docs

**Comment by rbq** [comment]
> When will this be released?

https://github.com/rancher/rancher/wiki/Rancher-Project-Plan#roadmap
