### ISSUE TITLE
Global DNS 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16014]
Implement Global DNS - feature allowing to register workloads from different clusters into the same fqdn record on the public cloud provider

**Comment by alena1108** [comment]
@prachidamle we need to have support for at least 2 providers in 2.2. Route53 is the first - the default one - have to decide on the second one

**Comment by alena1108** [comment]
Providers list: 

- [X] Route54
- [ ] TBD

**Comment by alena1108** [comment]
@galal-hussein check of what alternative provider would make sense to add (cloudFlare?)

**Comment by alena1108** [comment]
Submitted a separate issue for adding the alternative global dns provider. Adding it won't change the logic for the global dns configuration, so this feature can be tested against route53.

**Comment by sangeethah** [comment]
Workflows relating to Global DNS feature is available in master builds.
Issues found when testing this feature are tracked in different issues.
Some of them are:
https://github.com/rancher/rancher/issues/17507
https://github.com/rancher/rancher/issues/17455
https://github.com/rancher/rancher/issues/17454
https://github.com/rancher/rancher/issues/17451
https://github.com/rancher/rancher/issues/17450
