### ISSUE TITLE
Can not upgrade Rancher installed via RKE addon to v2.1.0 in HA Mode

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16012]
rancher/rancher:v2.1.0

Steps to reproduce

1. Step up Rancher HA follow https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/layer-7-lb/
2. Add a cluster into Rancher
3. Upgrade Rancher by using `kubectl set image`

Results:

The cluster state become `unavailable` in Rancher UI. But everything works well with `kubectl`

Workaround:

A workaround is following

1.  Change the value of `/v3/settings/peer-service`  to `cattle-service` (cattle-service is the service name for rancher/rancher)
2. (Optional) Change the value of `/v3/settings/namespace`  to `cattle-system` (the namespace for rancher/rancher) if your `rancher/rancher` pod is not in the `cattle-system` namespace
3.  Restart all pods for `rancher/rancher`

I think we need to add it in the release note or document

**Comment by jiuchongxiao** [comment]
@loganhz  i have update the setting,but it is not useful.
![Uploading image.png…]()

**Comment by loganhz** [comment]
@jiuchongxiao jiu You need to restart all pods for rancher/rancher .

**Comment by jiuchongxiao** [comment]
yes ,i had restart docker,so that the all pods restart,and the error always, is it relate with the kubernets version?

**Comment by loganhz** [comment]
@jiuchongxiao jiu can you find me via wechat `howl6616`, please?

**Comment by loganhz** [comment]
Linked to https://github.com/rancher/docs/issues/869

**Comment by alena1108** [comment]
Direct upgrade from rancher installed via rke addon to HA in 2.1 is not supported. Following steps should be done and tested:

* upgrade rke addon install to helm prior to 2.1 upgrade
* upgrade to 2.1 using helm (from helm chart to helm chart)

Following needs to be documented: 

* release note it in the github and forums
* update the docs (indicate that migration to helm needs to occur before upgrading to 2.1)

**Comment by deniseschannon** [comment]
We have decided that we no longer support v2.1 install using the RKE add-on methods. We only support/work with the helm chart install. 

This is now documented as expected. 

https://github.com/rancher/rancher/issues/16033


Also, our QA team has tested using  RKE add-on install and using our docs to migrate to a helm chart install for 2.1:

If you are currently using the RKE add-on install method, see [Migrating from a RKE add-on install](https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/migrating-from-rke-add-on/) for details on how to move to using the helm chart.

**Comment by wzrdtales** [comment]
@deniseschannon Ok, but RKE will still be used to setup the k8s cluster right? Or do you drop rke alltogether?

And another thing I noted while upgrading: I also upgraded the k8s cluster itself with rke, and noticed that rke is still running the deploy job even so I removed everything from the yaml of the addon section. Does that interfere somehow with the helm installation or is that just fine?

**Comment by deniseschannon** [comment]
@wzrdtales Yes, RKE is still being used as how to setup your k8s cluster, but using the RKE addon method of installing Rancher is no longer supported.

We just added notes into the docs of migration on how to clean up the addon itself:

https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/migrating-from-rke-add-on/#remove-addons-section-from-rancher-cluster-yml

Did you eliminate the whole `addons` section or did you leave the `addons` directive but clear it out? I think you need to do the latter for RKE to realize that there are explicitly no addons and what to remove.

**Comment by wzrdtales** [comment]
@deniseschannon Yes, I compeltely deleted it, just the server config is there.

**Comment by wzrdtales** [comment]
Basically just asking if the things that rke still executes in the deploy step collide. As far as I have seen these are setting up the network stack.

**Comment by wzrdtales** [comment]
Most things also seem to work, except when logging in it is throwing `failed to find schema resourceQuotaTemplates: undefined`, so something went wrong there, just noticed now.

**Comment by deniseschannon** [comment]
@wzrdtales that's actually a UI caching error: https://github.com/rancher/rancher/issues/15981
