### ISSUE TITLE
After service is upgraded successfully , we are left with older service which has no containers and still linked to LB and DNS service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1602]
Rancher Server - Build from master
Rancher compose version - V0.2.2

Steps to reproduce the problem:
Have a service S1 with scale 4.
Create an LB service with target at S1.
Create a DNS service with target at S1.

using rancher-compose , upgrade S1 to S2.

After upgrade is fully done , service S1 is still present with no containers (all containers were removed as part of upgrade).
LB service now has links to both S1 and S2.
DNS service now has links to both S1 and S2.
Questions:

1. Is there a need for service S1 to still be in "Active" state with no containers ? I am allowed to scale up this service and add new containers which eventually becomes a part of LB service. 
This is not desirable?

2. Why do we still have the LB service links to S1  ? Should this be removed once upgrade is completed.

3. Why do we still have the DNS service links to S1  ? Should this be removed once upgrade is completed.

**Comment by will-chan** [comment]
After an upgrade, the end result is that the original service has zero container with all existing inbound and outbound links as it is.  It will be up to the user to remove this manually for now.  We can always add a flag in the future to automatically clean this up but the purpose of this is just in case users need to rollback to the previous service.
