### ISSUE TITLE
Resource Quotas for different namespace sizes

### ISSUE THREAD

**Issue by KuroObi** [rancher/rancher#16028]
**Rancher versions:**
rancher/rancher:v2.1.0
rancher/rancher-agent:v2.1.0
**Setup details: single node rancher**
**Environment Template: (RKE)**

I have a Qustion regarding the new Resource Quotas released in v2.1.0.
A Project Level Limit Sounds like a great idea, but in our case the size of the namespaces differ greatly (from 500mCPU to a Namespace with about 10 CPU's) so i can't configure the namespace limit to the higher CPU value for this would limit our number of available namespaces greatly, unless I would overwrite moste of them with custom quotas.

Is there another way to configure this or is this a feature planed future releases?

**Comment by lcx102737** [comment]
I have this problem too. In the namespace edit display, current namespace use resource is zero, but other namespaces resource more than allocation. I think this problem is  edit namespace function used as create.

**Comment by deniseschannon** [comment]
It sounds like you would need to configure each namespace individually  and specify which ones would have the higher limites on top of the project level. 

No matter what the total of the namespace limits would need to be within the project level.
