### ISSUE TITLE
 When I upgraded rancher from 2.0.8 to 2.1.0, pipeline display No Permission

### ISSUE THREAD

**Issue by sdjnmxd** [rancher/rancher#16024]
I follow the documentation [ha-server-upgrade](https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha-server-upgrade/) to upgrade my rancher cluster from `2.0.8` to `2.1.0`

The upgrade process went smoothly. But after the upgrade is complete, the pipeline function does not work properly. The page displays No Permission.

![image](https://user-images.githubusercontent.com/6388562/46660458-a8866a80-cbe9-11e8-94bc-c880983433e8.png)

How should I configure to use this feature? Or what information do I need to provide to further locate the problem?

Thank you :D

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`authenticated.project.pipeline.settings`|

**Comment by loganhz** [comment]
Only project owner can enable the pipeline. Please check if you have that role

**Comment by sdjnmxd** [comment]
![image](https://user-images.githubusercontent.com/6388562/46665436-67e11e00-cbf6-11e8-9873-ccde3bac3985.png)

I can be sure I am the project owner. In fact, I am using a super administrator account.

![image](https://user-images.githubusercontent.com/6388562/46665620-f9509000-cbf6-11e8-9bd7-483a18819fdd.png)

**Comment by loganhz** [comment]
@sdjnmxd Can you add me in WeChat `howl6616`?

**Comment by loganhz** [comment]
Pipeline can not work in Rancher 2.1.0 RKE-Addon HA mode as the pipeline related controller can not start.

Please migrate to helm before upgrade to v2.1.0

https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/migrating-from-rke-add-on/

Related issue https://github.com/rancher/rancher/issues/16012
