### ISSUE TITLE
Ingresses show as initializing

### ISSUE THREAD

**Issue by dabeck** [rancher/rancher#16027]
**Rancher versions:**
rancher/server or rancher/rancher: 2.1.0

**Infrastructure Stack versions:**
kubernetes: 1.10.5 and 1.11.3

**Docker version: (`docker version`,`docker info` preferred)**
Docker 18.6.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Container Linux by CoreOS 1855.4.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes setup

**Steps to Reproduce:**
Upgrade from Rancher 2.0.8 to 2.1.0

**Results:**
All previously created and new ingresses show up as "initializing" in the UI but they are still fully functional. Maybe this is a UI related problem!?

![image](https://dbecker.net/ds/Screen-Shot-2018-10-09-12-05-46-DOKSlw14Ac.png)

**Comment by loganhz** [comment]
@dabeck Can you check the state field in API by clicking the `View API` action of the ingress, please?

**Comment by dabeck** [comment]
@loganhz The state says `initilizing`

```
[...]
"state": "initializing",
"status": {
"loadBalancer": {
"type": "/v3/project/schemas/loadBalancerStatus"
},
"type": "/v3/project/schemas/ingressStatus"
},
"transitioning": "no",
"transitioningMessage": "",
"type": "ingress",
[...]
```

**Comment by robtimmer** [comment]
I also experience this issue, but can resolve it by re-enabling `Nginx Ingress` in the cluster settings (started of in disabled state)

**Comment by bmartin13** [comment]
Same here....

**Comment by alena1108** [comment]
We've added the logic for populating ingress state based on the status/Load balancer field with commit aa102c67526504553c7bed623665e04718167e1a. By some reason, status/LoadBalancer/ingress in your case is nil. Can you check if it nil on Kubernetes side as well. We can only say that the ingress is functional when controller populates this field with the ip address.

Kubecl output - Address field is the one we are looking for
```
> kubectl get ingress
NAME         HOSTS    ADDRESS        PORTS     AGE
ingressfoo  foo.com  142.93.30.63   80        47s
```

The same field presented in `kubectl get ingress -o json` output:

```
"status": {
                "loadBalancer": {
                    "ingress": [
                        {
                            "ip": "142.93.30.63"
                        }
                    ]
                }
            }
```

**Comment by alex-s-team** [comment]
you are right, the status field is not populated by the controller. can i work around this in some way?

```

    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "extensions/v1beta1",
            "kind": "Ingress",
            "metadata": {
...
            },
            "status": {
                "loadBalancer": {}
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```

**Comment by alena1108** [comment]
@alex-s-team that would be an issue on the ingress controller side; it is supposed to populate this field. Which ingress controller do you use?

**Comment by dabeck** [comment]
@alena1108 For me, I am using [traefik 1.7.2](https://github.com/containous/traefik)

**Comment by bmartin13** [comment]
We use nginx/modSecurity (type loadbalancer) for our SSL termination/ security filtering.  We have Traefik 1.6.5 (nodeport) handling the routing behind it.  Only the Traefik ingresses are showing the issue.  With this config they will never get a public IP.

Traefik Ingress status:

 "status": {
                "loadBalancer": {
                    "ingress": [
                        {}
                    ]
                }
            }
        }

**Comment by alena1108** [comment]
@dabeck @bmartin13 looks like there is an issue on a traefik side that is supposedly got resolved in 1.7 version, but based on the last comments, still requires some extra config:

https://github.com/containous/traefik/issues/2173

**Comment by dabeck** [comment]
@alena1108 Ahh that did the trick! Thank you very much 👍

**Comment by alex-s-team** [comment]
@alena1108 i am using traefik (tried 1.6.5 and 1.7.2), i know its not yet supported, but traefik supports kubernetes. traefik works as advertised, but it doesn't set the status correctly.

i will try the suggested workaround / solution from
https://github.com/containous/traefik/issues/2173

thanks very much
