### ISSUE TITLE
User can create namespaces without permission

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#16022]
**Rancher versions:**
rancher/rancher: 2.1.0
kubernetes (if applicable): 1.11.3
Docker version: 17.3.2
Type/provider of hosts: baremetal
Setup details: singel-node
Environment Template: Kubernetes

**Steps to Reproduce:**
- setup Rancher2 + auth via LDAP

- make "User Base" default role
- create a project project1
- add a testuser from LDAP only to that project with custom permissions ALL **without** 'create namespace', 'manage-members'

**Results:**
User is still able to create namespaces, which shouldn't be..

**Comment by deniseschannon** [comment]
Is the testuser added in any other project?

There is a caveat about project roles: 
https://rancher.com/docs/rancher/v2.x/en/admin-settings/rbac/cluster-project-roles/#project-roles

**Comment by strowi** [comment]
@deniseschannon: No, this was a clean setup and the testuser is only a member in that project.

**Comment by cjellick** [comment]
Can you provide a little more info by showing us the role(s) you used that did not have the create namespace permission?

**Comment by cjellick** [comment]
either a screenshot or  view it in the api and copy pasting the output

**Comment by cjellick** [comment]
I just tested this scenario with OpenLDAP with these steps and could not reproduce:
1. spin up rancher
2. turn on OpenLDAP integration
3. Add a cluster
4. Open the default project in the cluster, go to members tab
5. Click Add member and then select the custom option and check all the boxes except Create Namespaces and Manage Project Members.
6. In a different browser (ie firefox instead of chrome bc my admin session was still active in chrome), log in as the user added in step 5.
7. Attempt to create namespaces in the cluster and project that I was granted access in.

Result:
Request rejected with this error message:
``` 
namespaces is forbidden: User "u-6wxyvvf3ra" cannot create namespaces at the cluster scope
```

Note that the enforcement of this rule is done by kubernetes itself. Does the cluster that you are trying this in have RBAC turned on? How did you deploy that cluster?

**Comment by superseb** [comment]
Let us know if you can still reproduce.

**Comment by strowi** [comment]
Hi,

this feels  a little awkward, but i am running into the same problem again with 2.1.3 on another cluster...

```
> k create ns test
namespace "test" created
> k delete ns test
Error from server (Forbidden): namespaces "test" is forbidden: User "u-zbw65mdtej" cannot delete resource "namespaces" in API group "" in the namespace "test"
```

global->users->ci:
```
x  | Create Clusters | n/a |  
x  | Manage Authentication | n/a |  
x  | Manage Catalogs | n/a |  
x  | Manage Node Drivers | n/a |  
x  | Manage PodSecurityPolicy Templates | n/a |  
x  | Manage Roles | n/a |  
x  | Manage Settings | n/a |  
x  | Manage Users | n/a |  
x  | Use Catalog Templates | n/a |  

- no cluster roles
- no project roles
```
cluster: prod->members:
```
Default Admin (admin)
```
cluster: prod->Projects->testperm:
```
ci dev ( ci ) User  View Config Maps  6:13 PM   
ci dev ( ci ) User  View Ingress  6:13 PM 
ci dev ( ci ) User  View Volumes  6:13 PM 
ci dev ( ci ) User  View Secrets  6:13 PM 
ci dev ( ci ) User  View Service Accounts   6:13 PM 
ci dev ( ci ) User  View Services   6:13 PM 
ci dev ( ci ) User  View Workloads  6:13 PM 
```

**Comment by strowi** [comment]
OK, some more investigating showed a lot of (probably leftover) clusterrolebindings "clusterrolebinding-hash".
After removing ALL of them, and re-adding the group via rancher-ui it seems to work again.

**Comment by rchench** [comment]
I met the similar issue. In addition, I also figured out following issue with this.

1. after creation of the namespace, I cannot remove it
```
> kubectl create ns test1
namespace "test1" created
> kubectl delete ns test1
Error from server (Forbidden): namespaces "test1" is forbidden: User "u-6v6fk" cannot delete resource "namespaces" in API group "" in the namespace "test1": RBAC: clusterrole.rbac.authorization.k8s.io "p-4cdgd-namespaces-edit" not found
```

2. I can move the namespace to the project I own and then delete it.

3. If I have view permission to other projects or view permission to namespaces, I can also move namespaces from other projects to my project, and then delete them. This is a serious concern.
