### ISSUE TITLE
Ability to remove/delete hosts after being inactive for a configurable time

### ISSUE THREAD

**Issue by kylegoch** [rancher/rancher#16035]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent: v2.0.8

It seems like in Rancher <2.0 there is a setting of `host.remove.delay.seconds` where you can automatically remove inactive hosts (like if you are using an ASG). However in Rancher 2.x, there is no `Advanced Settings` in the regular `Settings` tab. And I can't find any mention of `host.remove.delay.seconds` in any of the docs.

This setting would be huge for us as we use Spot Fleet for our worker instances and they will randomly die, but then be "stuck" in the cluster as `Inactive`.

I found this setting mentioned here:
https://github.com/rancher/rancher/issues/3745#issuecomment-353121804
And here:
https://github.com/rancher/rancher/issues/9737#issuecomment-339652262

**Comment by superseb** [comment]
We have a request to remove nodes in Rancher that are deleted in Kubernetes here: https://github.com/rancher/rancher/issues/14184

This setting of removing nodes is more tricky with Kubernetes, it should be used with precaution. For now deleting the node as action coming from a terminate action would be the way, we need to discuss if we want to implement this feature in 2.x again.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15737
