### ISSUE TITLE
Upgraded service does not have service links that were present in the original service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1603]
Rancher Server - Build from master
Rancher compose version - V0.2.2

Steps to reproduce the problem:
Have a service S1 with scale 4 which links to another service - S2.
Upgrade service S1 to S3.

upgraded service S3 does not have service links to S2.

Expected Behavior:
upgraded service should have all service links from the original service.

**Comment by will-chan** [comment]
Talking to Sangeetha, this is not an issue because the S3 definition did not have the links to begin with.
