### ISSUE TITLE
server-chart: removing tls=external option breaks upgrade.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#16030]
**Rancher versions:**
rancher/rancher: 2.1.0
rancher/server-chart: 2.1.0

We removed the option to do TLS offload exclusively on an external load balancer.

Removing this option doesn't stop you from having a cert on your lb, you just need to forward your traffic to the https endpoint on the ingress instead of port 80.

We removed the option since there was no consistent way to describe configuring external load balances, too many variations. Also exposing port 80 left the possibility of connecting unencrypted to rancher.

The problem is removing this option will break upgrades for people who have installed with that option.  No error is provided when you upgrade, but http->https redirect will be turned on and no certificate will be configured on the ingress.

See rancher/server-chart#30 for PR to add the option back in.
See rancher/docs#871 for new docs warning of the deprecation of that option and instructions on how to convert to a supported tls configuration.

**Comment by ITBlogger** [comment]
Well this is good to know...this is definitely effecting me.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/16030

**Comment by deniseschannon** [comment]
Available in the master branch of https://github.com/rancher/server-chart

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.0
rancher/server-chart:master

3 node HA cluster w/ ssl termination at nginx lb, trusted certs, --tls=external chart option

Upgrade path 1
v2.0.8 -> v2.1.0 -> v2.1.0 (master chart)
* Created a cluster for each version during upgrade path, with workloads and ingress. 
* Rancher UI is accessible at each upgrade
* New cluster creation with workloads and ingress is successful.
* `nginx.ingress.kubernetes.io/ssl-redirect: false` is present in deployment

```
helm install rancher-stable/rancher --version v2.0.8 \
  --name rancher \
  --namespace cattle-system \
  --set hostname=<host> \
  --set tls=external

helm upgrade rancher rancher-stable/rancher \
  --set hostname=<host> \
  --set tls=external

helm upgrade rancher ./ \ # local rancher/server-chart:master
  --set hostname=<host> \
  --set tls=external
```

Upgrade path 2
v2.0.8 -> v2.1.0 (master chart)
* Created a cluster in 2.0.8, with workloads and ingress. 
* Upgraded to 2.1.0 from master chart. Existing cluster continued to function. 
* Creating a cluster in 2.1.0 with workloads and ingress is successful.
* `nginx.ingress.kubernetes.io/ssl-redirect: false` is present in deployment

```
helm install rancher-stable/rancher --version v2.0.8 \
  --name rancher \
  --namespace cattle-system \
  --set hostname=<host> \
  --set tls=external

  helm upgrade rancher ./ \ # local rancher/server-chart:master
  --set hostname=<host> \
  --set tls=external
```
