### ISSUE TITLE
Unable to provision nodes with fresh install of 2.1 using privateCA

### ISSUE THREAD

**Issue by terribleplan** [rancher/rancher#16036]
**Rancher versions:**
rancher/rancher:v2.1.0
rancher/rancher-agent:v2.1.0

**Infrastructure Stack versions:**
n/a

**Docker version: (`docker version`,`docker info` preferred)**

(rancher server host, but all hosts are identical)

```
[ec2-user@ip-10-0-1-146 ~]$ docker info
Containers: 24
 Running: 20
 Paused: 0
 Stopped: 4
Images: 11
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.5 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.7GiB
Name: ip-10-0-1-146.ec2.internal
ID: 7ULT:5ECE:6OU6:G4BI:B3TB:AWW4:PCNN:QDEC:5B2Z:GC2N:27TT:FCLA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
[ec2-user@ip-10-0-1-146 ~]$ uname -r
3.10.0-862.el7.x86_64
[ec2-user@ip-10-0-1-146 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS, technically, being treated as custom/bare metal.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher HA atop a cluster provisioned by RKE

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

0. Have a CA and TLS key in secrets that rancher can use.
1. Create a new rancher master deployed via helm using `--set ingress.tls.source=secret` and `--set privateCA=true`.
2. Create a cluster.
3. Try to provision a node into the cluster.

**Results:**
The generated join command has the wrong value for `--ca-checksum` and fails to join the cluster with `level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"`

In 2.0.8 `--ca-checksum` was being set correctly. It is worth noting that 2.1.0 (latest) is now being deployed with no interaction from us via the same automation that was previously deploying 2.0.8 (stable) via the stable helm chart.

update: It also looks like it can't adopt the local cluster. I've blown this rancher install away and `--set rancherImageTag=v2.0.8` until 2.1 can approach something resembling stable and/or the stable helm charts actually install a stable version.

**Comment by superseb** [comment]
I just ran the setup for v2.1.0 again with self signed certificates and I can create a custom cluster and add a node. Can you supply a bit more info on your setup? As there is a bug in the helm chart, what manual steps did you take? What certificates are you using, is it a single or with intermediates?

What checksum is being generated in the UI, and what is being returned from the API? (`curl  -s -k https://RANCHER_URL/v3/settings/cacerts | jq -r .value | sha256sum`) Is the `cacerts.pem` in the pod correctly configured? `kubectl exec -n cattle-system a_rancher_pod -- cat /etc/rancher/ssl/cacerts.pem`

**Comment by terribleplan** [comment]
This is a single self-signed RSA-4096 cert with no intermediates. To run the chart I simply copied the chart according to your PR (https://github.com/rancher/server-chart/pull/32) into my repo and am deploying from that rather than the cert repo. Other than that I have overridden the following:

```
--set hostname=[redacted]
--set ingress.tls.source=secret
--set privateCA=true
--set rancherImageTag=v2.0.8
```

Right now it is looking like something weird may be happening with certmanager, or possibly somewhere else in the cert process. 

The ca cert in my repo is `c236d6385970f85924207695a304a39bf541e46582e9abcf3f36ef86d5f82a3a`

The ca cert at `/v3/settings/cacerts` is `07355aa4b982e48546b346adeaaec87ac0f333463759916aaa12986a8b59a7a6`

The kube secret tls cert `tls-rancher` (with a key of `tls.crt`) is `07355aa4b982e48546b346adeaaec87ac0f333463759916aaa12986a8b59a7a6`

The kube opaque secret `tls-ca` (with a key of `ca.crt`) is `c236d6385970f85924207695a304a39bf541e46582e9abcf3f36ef86d5f82a3a`

`/etc/rancher/ssl/ca.crt` on a rancher pod is `c236d6385970f85924207695a304a39bf541e46582e9abcf3f36ef86d5f82a3a`

`/etc/rancher/ssl/cacerts.pem` does not exist

The register command uses `07355aa4b982e48546b346adeaaec87ac0f333463759916aaa12986a8b59a7a6`

**Comment by cloudnautique** [comment]
The tls-ca key needs to be cacerts.pem

**Comment by superseb** [comment]
`/etc/rancher/ssl/cacerts.pem` is what used to calculate the checksum, what command did you run when you added the secret, it should be:

```
kubectl -n cattle-system create secret generic tls-ca \
  --from-file=cacerts.pem
```

**Comment by terribleplan** [comment]
Very similar, just a little modified to run well in CI:

```
kubectl -n cattle-system create secret generic tls-ca --from-file=./[redacted]/ca.crt --dry-run -o yaml | kubectl apply -f -
```
