### ISSUE TITLE
Add `latest` helm repo for Rancher installations

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16034]
Currently stable helm chart for rancher points to 2.1. It should point to 2.0.8

**Comment by terribleplan** [comment]
Doing this would likely have prevented our deployments from breaking in #16036, this should be done urgently.

**Comment by gregkeys** [comment]
we have come to the conclusion in our own charts that a charts should always use tags, using latest images in charts and kubernetes for that matter is problematic in more that one way.  in some instances it will not pull the latest image which can cause problems.

**Comment by deniseschannon** [comment]
@gregkeys In our Rancher helm charts, we never use the `latest` tag. It's always been specified with a specific tag. 

We are going to be introducing a `rancher-latest/rancher` repo, which will contain any helm chart that gets a Rancher version that is tagged as `latest` . Only when a Rancher tag is promoted to `stable`, we will introduce that chart into the `rancher-stable/rancher`.

Notes on the Docker tag for Rancher:

https://rancher.com/docs/rancher/v2.x/en/installation/server-tags/

To move between chart repos, you should be able to `helm upgrade rancher <repo-name>` to switch to a different chart repo. We need to also document the change about how to switch between repo names as well as defaulting to use the `rancher-latest/rancher` repo in the docs.

**Comment by deniseschannon** [comment]
Docs issue: https://github.com/rancher/docs/issues/907

**Comment by alena1108** [comment]
@bmdepesa rancher-latest/rancher repo is up. We should test upgrading between the repos (see instructions https://github.com/rancher/rancher/issues/16034#issuecomment-430395245)

**Comment by sangeethah** [comment]
Tested the following workflow of deploying rancher server version - v2.0.8 from ```stable``` repo and then upgrading it to rancher server version - v2.1.0 using ```latest``` repo.


1.  Add ```stable``` repo.
``` helm repo add rancher-stable https://releases.rancher.com/server-charts/stable ```
2. Install  v2.0.8 from ```stable``` repo 
``` helm install rancher-stable/rancher --name rancher --namespace cattle-system  --set hostname=<hostname> --set ingress.tls.source=secret --set rancherImageTag=v2.0.8 --set replicas=1
```
3.To upgrade rancher server version - v2.1.0 using ```latest``` repo.
```helm search rancher```
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION                                                 
rancher-stable/rancher	2018.10.1    	v2.1.0     	Install Rancher Server to manage Kubernetes clusters acro...
```helm repo add rancher-latest https://releases.rancher.com/server-charts/latest```
"rancher-latest" has been added to your repositories
```helm search rancher```
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION                                                 
rancher-latest/rancher	2018.10.1    	v2.1.0     	Install Rancher Server to manage Kubernetes clusters acro...
rancher-stable/rancher	2018.10.1    	v2.1.0     	Install Rancher Server to manage Kubernetes clusters acro...
```helm upgrade rancher rancher-latest/rancher --set hostname=sangeetestha.rancher.space --set ingress.tls.source=secret```
