### ISSUE TITLE
Upgraded service still has service links in "active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1604]
Rancher Server - Build from master
Rancher compose version - V0.2.2

Steps to reproduce the problem:
Have a service S1 with scale 4 which links to another service - S2.
Upgrade service S1 to S3.

After upgrade is successful, all instances of service S1 is deleted. But the service link to S2 is still in "active" state. Should this service link be removed as part of upgrade process?

**Comment by will-chan** [comment]
This is as designed.  We should leave S1 alone in case they need to rollback.  The user can manually remove this or we can support some flag in the future to automatically delete the service.
