### ISSUE TITLE
No cacerts cattle-node-agent entrypoint.sh issues

### ISSUE THREAD

**Issue by ts-mini** [rancher/rancher#16046]
**Rancher versions:**
rancher/server or rancher/rancher: 2.1.0
rancher/agent or rancher/rancher-agent: 2.1.0

**Steps to Reproduce:**
Launch helm chart HA installation with --no-cacerts (provide your own tls)
Restart pod in cattle-node-agent workload
You will get this error from the entrypoint.sh script.  There is no --ca-checksum being passed in [here](https://github.com/rancher/rancher/blob/32e12d5e1a418f917dc9b170e3354bf4e28c803b/package/run.sh#L214) resulting it in trying to fetch the cert from cacerts (which doesn't exist) and the entrypoint script dies out with exit 1.  The cattle-node agent produces the following log:

 INFO: https://rancher2.blah.com/ping is accessible
ERROR: Value from https://rancher2.blah.com/v3/settings/cacerts does not look like an x509 certificate (unable to load certificate 139659323314624:error:0906D06C:PEM routines:PEM_read_bio:no start line:../crypto/pem/pem_lib.c:691:Expecting: TRUSTED CERTIFICATE)
ERROR: Retrieved cacerts:

**Results:**

It seems like the entrypoint.sh script should be able to accept a similar --no-cacerts flag (for both custom clusters, and the cattle-node-agent created by importing clusters should have it passed to it)

**Comment by ts-mini** [comment]
It seems I was a bit backwards.  I edited the cattle-node-agent workload and removed the variable:

CATTLE_CA_CHECKSUM 

from the list of env vars for that deployment, the cattle-node-agent successfully started on the rest of the nodes, had no issue.

**Comment by ts-mini** [comment]
same with cattle-cluster-agent workload

**Comment by superseb** [comment]
`--no-cacerts` should make sure that the `value` parameter from `https://rancher2.blah.com/v3/settings/cacerts` is empty. It being empty makes sure the daemonset gets deployed without the env var, so it doesn't get checked.

The question is if `--no-cacerts` is applied to the Deployment, and what the content is of `https://rancher2.blah.com/v3/settings/cacerts`

**Comment by ts-mini** [comment]
It correctly provisions the master with no ca cert, that worked fine. 
```
{
"baseType": "setting",
"created": "2018-05-16T23:01:59Z",
"createdTS": 1526511719000,
"creatorId": null,
"customized": false,
"default": "",
"id": "cacerts",
"links": {
"remove": "…/v3/settings/cacerts",
"self": "…/v3/settings/cacerts",
"update": "…/v3/settings/cacerts"
},
"name": "cacerts",
"type": "setting",
"uuid": "23956365-595d-11e8-ba65-42010a96009e",
"value": ""
}
```

**Comment by superseb** [comment]
What is shown below: ```ERROR: Retrieved cacerts:```

**Comment by ts-mini** [comment]
There is nothing
![screenshot from 2018-10-11 10-12-31](https://user-images.githubusercontent.com/4910513/46818424-6ae72600-cd3e-11e8-886c-5cf98d974143.png)

**Comment by superseb** [comment]
What was the original value of `CATTLE_CA_CHECKSUM`? I just ran with valid certificates and the DaemonSet gets created with:

```
                                    {
                                        "name": "CATTLE_CA_CHECKSUM"
                                    },
```

Which means the path to check `cacerts` in the agent is not even traversed because of `CATTLE_CA_CHECKSUM` is empty.

I also deleted the pods (not sure how you restarted them), and it still came back fine.

If you are able to reproduce from scratch, please supply all the steps/commands and full logs as the agent logs all env variables on startup and it makes no sense to work once and doesn't after. There shouldn't be a need to edit any deployment/daemonset.

**Comment by ts-mini** [comment]
I can't reproduce from scratch - it seems like it was caused from my cluster originally having a rancher-provisioned cacert, then me going to --no-cacerts during the upgrade from 2.0.8 to 2.1.0
I imagine it might not be an issue for many people - or even an on going bug, but we will see.  
```
CATTLE_SERVER	https://rancher2.blah.com
CATTLE_K8S_MANAGED	true
CATTLE_CLUSTER	false
CATTLE_CA_CHECKSUM	0ffca5e006147b98adbe16616edc752f8e77c3d723f83c06650314ade8d3bfa2
CATTLE_AGENT_CONNECT	true
```

**Comment by superseb** [comment]
It's being tracked here https://github.com/rancher/rancher/issues/14731

**Comment by superseb** [comment]
Commands to fix the issue where `CATTLE_CA_CHECKSUM` is set but there is no `cacerts` configured in Rancher.

```
# DaemonSet cattle-node-agent
# Check current value
kubectl -n cattle-system get ds -o go-template='{{range .items}}{{range .spec.template.spec.containers}}{{range .env}}{{if eq .name "CATTLE_CA_CHECKSUM"}}{{.name}}{{"="}}{{.value}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}'
# Patch DaemonSet
kubectl -n cattle-system patch daemonset/cattle-node-agent -p '{"spec": {"template": {"spec": {"containers": [{"name": "agent", "env": [{"name": "CATTLE_CA_CHECKSUM", "value": ""}]}]}}}}'
```

```
# Deployment cattle-cluster-agent
# Check current value
kubectl -n cattle-system get deploy -l app=cattle-cluster-agent -o go-template='{{range .items}}{{range .spec.template.spec.containers}}{{range .env}}{{if eq .name "CATTLE_CA_CHECKSUM"}}{{.name}}{{"="}}{{.value}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}'
# Patch Deployment (Change version to your environment, in this case `rancher/rancher-agent:v2.1.1`)
kubectl -n cattle-system patch deploy/cattle-cluster-agent -p '{"spec": {"template": {"spec": {"containers": [{"name": "cluster-register", "image": "rancher/rancher-agent:v2.1.1", "env": [{"name": "CATTLE_CA_CHECKSUM", "value": ""}]}]}}}}'
```

**Comment by ArgonQQ** [comment]
> Commands to fix the issue where `CATTLE_CA_CHECKSUM` is set but there is no `cacerts` configured in Rancher.
> 
> ```
> # DaemonSet cattle-node-agent
> # Check current value
> kubectl -n cattle-system get ds -o go-template='{{range .items}}{{range .spec.template.spec.containers}}{{range .env}}{{if eq .name "CATTLE_CA_CHECKSUM"}}{{.name}}{{"="}}{{.value}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}'
> # Patch DaemonSet
> kubectl -n cattle-system patch daemonset/cattle-node-agent -p '{"spec": {"template": {"spec": {"containers": [{"name": "agent", "env": [{"name": "CATTLE_CA_CHECKSUM", "value": ""}]}]}}}}'
> ```
> ```
> # Deployment cattle-cluster-agent
> # Check current value
> kubectl -n cattle-system get deploy -l app=cattle-cluster-agent -o go-template='{{range .items}}{{range .spec.template.spec.containers}}{{range .env}}{{if eq .name "CATTLE_CA_CHECKSUM"}}{{.name}}{{"="}}{{.value}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}'
> # Patch Deployment (Change version to your environment, in this case `rancher/rancher-agent:v2.1.1`)
> kubectl -n cattle-system patch deploy/cattle-cluster-agent -p '{"spec": {"template": {"spec": {"containers": [{"name": "cluster-register", "image": "rancher/rancher-agent:v2.1.1", "env": [{"name": "CATTLE_CA_CHECKSUM", "value": ""}]}]}}}}'
> ```

We had the same problems - how can this be avoided in the future? We only changed from self signed (rancher) certs to trusted cert/key.

**Comment by superseb** [comment]
Currently the resources deployed are not refreshed when configured parts are changed, this will be resolved when https://github.com/rancher/rancher/issues/14731 is fixed.

**Comment by ArgonQQ** [comment]
Looking forward for the fix! Thanks 👍
