### ISSUE TITLE
Execute Shell exists unexpectedly

### ISSUE THREAD

**Issue by Longy1217** [rancher/rancher#16049]
When run kubectl exec -it xxxx  with param --request-timeout=3h in linux terminal ,it works.
How to modify default value of this param in rancher config file or web?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by superseb** [comment]
The default `--request-timeout` is `0`. What setup are you running, single install/HA, is there something in front of the `rancher/rancher` container that you connect to?

**Comment by Longy1217** [comment]
docker run -d --name rancher-server --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher
the above is my start command,  the cluster is in single mode

**Comment by superseb** [comment]
What is between the node running `kubectl` and the node running `rancher/rancher`? What is the output of `kubectl version`?

Can you also share the output of the `kubectl` command with adding `-v9` and with and without the `--request-timeout` parameter?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
