### ISSUE TITLE
server-chart: upgrade or install with privateCA=true is broken

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#16053]
rancher/rancher: 2.1.0
rancher/server-chart: 2.1.0

---

cola4u reports - rancher/server-chart#33

I tried both upgrading 2 existing Rancher installs:

* A 2.0.8 rancher install, setup with the helm chart - the upgrade gives the error message below
* A 2.0.8 rancher install, setup with rke and AddOns - went through the upgrade process which meant removing the old add-ons and installing rancher anew using helm. The same result as below

```
helm upgrade rancher rancher-stable/rancher \
--set hostname=whatever.tls.domain.name 
--set ingress.tls.source=secret 
--set privateCA=true
Error: UPGRADE FAILED: Deployment.apps "rancher" is invalid: [spec.template.spec.volumes[0].secret.defaultMode: Invalid value: 750: must be a number between 0 and 0777 (octal), both inclusive, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "tls-ca-volume"]
```

**Comment by jgreat** [comment]
We should be releasing an updated chart soon with a fix. In the mean time  you should be able to add the `--version 2.0.8` option to your `helm install` command to select the previous version of the chart.

If all else fails see https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/ for the process to restore the snapshot you took before the upgrade maintenance. This will get the rancher install back into the state it was before the migration.

**Comment by cola4u** [comment]
@jgreat THANK YOU sir!  that worked, I'm back in business with 2.0.8.
I'll keep watching the helm chart and attempt moving to 2.1 once you push out the fix.

**Comment by deniseschannon** [comment]
Available in the master branch of https://github.com/rancher/server-chart

**Comment by bmdepesa** [comment]
rancher/server-chart:master

HA cluster, self signed certs

Upgrade from helm v2.0.8 -> 2.1.0:master
* Deployed v2.0.8
* Created a cluster with workloads/ingress
* Upgrade to 2.1.0 from master
* Created a cluster with workloads/ingress
* All clusters, workloads, ingress functional

```
helm install rancher-stable/rancher --version v2.0.8 \
  --name rancher \
  --namespace cattle-system \
  --set hostname=brandon-ha.rancher.space \
  --set ingress.tls.source=secret \
  --set privateCA=true

helm upgrade rancher ./ \
  --set hostname=brandon-ha.rancher.space \
  --set ingress.tls.source=secret \
  --set privateCA=true
```

Fresh install from 2.1.0:master
* Deployed v2.1.0 from master
* Created a cluster with workloads/ingress
* Cluster, workloads, ingress functional.

```
helm install ./ \
  --name rancher \
  --namespace cattle-system \
  --set hostname=brandon-ha.rancher.space \
  --set ingress.tls.source=secret \
  --set privateCA=true
```

**Comment by bmdepesa** [comment]
@nxf5025 

The chart has been updated recently:
```
NAME                  	CHART VERSION 	APP VERSION
rancher-stable/rancher	2018.10.1     	v2.1.0
rancher-stable/rancher	2.1.0         	v2.1.0
```
is the latest chart which includes the octal permissions fix.

When removing `--version 2.1.0` you are using the latest version, instead of the older chart.
