### ISSUE TITLE
EKS - Waiting for API to be available after successful cluster and worker node creation

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#16054]
**Rancher versions:**
v2.1.0

**Setup details: **
HTTPS/Layer 7 HA install using AWS ALB and RKE v0.1.10

**Steps to Reproduce:**
On an HA install launch an EKS cluster

**Results:**
The EKS cluster and worker nodes will all create successfully within AWS, but in Rancher will remain stuck at "Waiting for API to be available". EKS creation is working fine for 2.0.8

I also noticed that the HA install docs have changed and now no longer mention the HTTPS/Layer 7 load balancer install. Are we forced to redeploy to the new standard? (https://rancher.com/docs/rancher/v2.x/en/installation/ha/)

**Comment by alena1108** [comment]
@nxf5025 have you used Helm or rke addon for Rancher HA install?

**Comment by nxf5025** [comment]
The article I followed now seems to be hidden, but I had it bookmarked - https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/layer-7-lb/

This was the RKE template I used which is linked to in the above article - https://raw.githubusercontent.com/rancher/rancher/master/rke-templates/3-node-externalssl-recognizedca.yml

I didn't add anything besides fill in the blanks that were needed.

**Comment by nxf5025** [comment]
Confirmed that after upgrading using helm the issue is fixed. (https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/migrating-from-rke-add-on/)
