### ISSUE TITLE
K8s upgrade isn't propagated to nodes manually tainted by users

### ISSUE THREAD

**Issue by jepp2078** [rancher/rancher#16050]
The cattle-node-agent isn't present on nodes manually tainted with NoExecute/NoSchedule.

This is due to the fact that the tolerations on the cattle-node-agent deployment only take into account the etcd and controlplane taints, and not user taints.

The following tolerations (taken from the canal deployment) will work with all user defined taints.

```
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        operator: Exists
```

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/15990 as it needs discussion

**Comment by superseb** [comment]
Re-opening this as it describes the issues we've seen. For allowing all, this is probably the way to go:

```
An empty key with operator Exists matches all keys, values and effects which means this will tolerate everything.
tolerations:
- operator: "Exists"
```

**Comment by superseb** [comment]
Current PR:

- Allow all taints for `cattle-node-agent`, this needs to run on every machine.
- Tolerations for `cattle-cluster-agent` for etcd and controlplane
- Soft affinity for controlplane (weight 100) and etcd (weight 1)

**Comment by Hitesh-Agrawal** [comment]
Is this workaround implemented in future rancher releases like 2.1.7 and 2.2

**Comment by Oats87** [comment]
@superseb do you foresee any issues with this and windows/arm nodes? https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/#ensuring-os-specific-workloads-land-on-the-appropriate-container-host

**Comment by sowmyav27** [comment]
@superseb 

verified the below scenario

1. Had Rancher setup on v2.2.3
2. Deployed a cluster - 1 control plane, 1 worker and 31 etcd nodes.
3. Added taints on all the three nodes.
4. Upgraded the rancher server to v2.2.4
5. Noticed the `cattle-node-agent` and `cattle-cluster-agent` fail to deploy. 
6. upgraded to v2.2.5-rc12(which has the fix)

**Observations:**
`cattle-cluster-agent` is stuck in `Scheduling` state.
`cattle-node-agent` has upgraded to correct version `rancher-agent:v2.2.5-rc12`
`kube-api-auth` has failed to deploy. there are no pods available.
<img width="1335" alt="Screen Shot 2019-07-09 at 4 08 28 PM" src="https://user-images.githubusercontent.com/26032343/60929089-b5151d80-a264-11e9-9c22-6bdb27dbdb05.png">

**Comment by superseb** [comment]
The nodeselector is already added for Windows nodes, I don't see any other issues with manually tainting than described in this issue and PR.

**Comment by sowmyav27** [comment]
### Verified on 2.2.4 - fresh install to master-head upgrade
**2.2.4 - fresh install**
cluster - 1 etcd, 1 control plane, 1 worker node - all nodes tainted
```
cattle-cluster-agent -- 1 pod on worker node
cattle-node-agent-- 3 pods ( all 3 nodes)
kube-api-auth -- 3 pods ( all 3 nodes)
```
cluster - 3 etcd, 2 control plane, 2 worker node - 1 node of each tainted
```
cattle-cluster-agent -- 1 pod on worker node
cattle-node-agent-- 7 pods ( all 7 nodes)
kube-api-auth -- 7 pods ( all 7 nodes)
```

**upgrade to master-head**
cluster - 1 etcd, 1 control plane, 1 worker node - all nodes tainted
```
cattle-cluster-agent -- 1 pod on control node --as expected
cattle-node-agent-- 3 pods ( all 3 nodes) --as expected
kube-api-auth -- 1 pod on control node --as expected
```
cluster - 3 etcd, 2 control plane, 2 worker node - 1 node of each tainted
```
cattle-cluster-agent -- 1 pod on control node --as expected
cattle-node-agent-- 7 pods ( all 7 nodes) --as expected
kube-api-auth -- 2 pods ( 2 control nodes) --as expected
```
