### ISSUE TITLE
rancher v2.0.2 udgrade to v2.0.7 dns question

### ISSUE THREAD

**Issue by jinchaoxiang** [rancher/rancher#16067]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.7
rancher/agent or rancher/rancher-agent:v2.0.7

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.0
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
network poliy is calico ,rancher v2.0.2 udgrade to v2.0.7
**Results:**
kubedns only in system project can resolve normal ,in other project no matter internal or external also hostname can't be  resolve

**Comment by jinchaoxiang** [comment]
**kubedns log**

> I1010 14:42:24.968419 1 dns.go:48] version: 1.14.10
2018/10/10 下午10:42:24 I1010 14:42:24.969460 1 server.go:69] Using configuration read from directory: /kube-dns-config with period 10s
2018/10/10 下午10:42:24 I1010 14:42:24.969513 1 server.go:121] FLAG: --alsologtostderr="false"
2018/10/10 下午10:42:24 I1010 14:42:24.969523 1 server.go:121] FLAG: --config-dir="/kube-dns-config"
2018/10/10 下午10:42:24 I1010 14:42:24.969530 1 server.go:121] FLAG: --config-map=""
2018/10/10 下午10:42:24 I1010 14:42:24.969534 1 server.go:121] FLAG: --config-map-namespace="kube-system"
2018/10/10 下午10:42:24 I1010 14:42:24.969537 1 server.go:121] FLAG: --config-period="10s"
2018/10/10 下午10:42:24 I1010 14:42:24.969544 1 server.go:121] FLAG: --dns-bind-address="0.0.0.0"
2018/10/10 下午10:42:24 I1010 14:42:24.969547 1 server.go:121] FLAG: --dns-port="10053"
2018/10/10 下午10:42:24 I1010 14:42:24.969553 1 server.go:121] FLAG: --domain="cluster.local."
2018/10/10 下午10:42:24 I1010 14:42:24.969563 1 server.go:121] FLAG: --federations=""
2018/10/10 下午10:42:24 I1010 14:42:24.969573 1 server.go:121] FLAG: --healthz-port="8081"
2018/10/10 下午10:42:24 I1010 14:42:24.969582 1 server.go:121] FLAG: --initial-sync-timeout="1m0s"
2018/10/10 下午10:42:24 I1010 14:42:24.969590 1 server.go:121] FLAG: --kube-master-url=""
2018/10/10 下午10:42:24 I1010 14:42:24.969600 1 server.go:121] FLAG: --kubecfg-file=""
2018/10/10 下午10:42:24 I1010 14:42:24.969608 1 server.go:121] FLAG: --log-backtrace-at=":0"
2018/10/10 下午10:42:24 I1010 14:42:24.969620 1 server.go:121] FLAG: --log-dir=""
2018/10/10 下午10:42:24 I1010 14:42:24.969629 1 server.go:121] FLAG: --log-flush-frequency="5s"
2018/10/10 下午10:42:24 I1010 14:42:24.969637 1 server.go:121] FLAG: --logtostderr="true"
2018/10/10 下午10:42:24 I1010 14:42:24.969645 1 server.go:121] FLAG: --nameservers=""
2018/10/10 下午10:42:24 I1010 14:42:24.969651 1 server.go:121] FLAG: --stderrthreshold="2"
2018/10/10 下午10:42:24 I1010 14:42:24.969658 1 server.go:121] FLAG: --v="2"
2018/10/10 下午10:42:24 I1010 14:42:24.969661 1 server.go:121] FLAG: --version="false"
2018/10/10 下午10:42:24 I1010 14:42:24.969679 1 server.go:121] FLAG: --vmodule=""
2018/10/10 下午10:42:24 I1010 14:42:24.969741 1 server.go:169] Starting SkyDNS server (0.0.0.0:10053)
2018/10/10 下午10:42:24 I1010 14:42:24.969935 1 server.go:179] Skydns metrics enabled (/metrics:10055)
2018/10/10 下午10:42:24 I1010 14:42:24.969947 1 dns.go:188] Starting endpointsController
2018/10/10 下午10:42:24 I1010 14:42:24.969952 1 dns.go:191] Starting serviceController
2018/10/10 下午10:42:24 I1010 14:42:24.970020 1 dns.go:184] Configuration updated: {TypeMeta:{Kind: APIVersion:} Federations:map[] StubDomains:map[] UpstreamNameservers:[]}
2018/10/10 下午10:42:24 I1010 14:42:24.970126 1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
2018/10/10 下午10:42:24 I1010 14:42:24.970135 1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
2018/10/10 下午10:42:24 I1010 14:42:24.987778 1 dns.go:601] Could not find endpoints for service "busybox-test" in namespace "default". DNS records will be created once endpoints show up.
2018/10/10 下午10:42:24 I1010 14:42:24.988137 1 dns.go:601] Could not find endpoints for service "rocketmq" in namespace "middleware". DNS records will be created once endpoints show up.
2018/10/10 下午10:42:24 I1010 14:42:24.988318 1 dns.go:601] Could not find endpoints for service "busybox" in namespace "efk". DNS records will be created once endpoints show up.
2018/10/10 下午10:42:24 I1010 14:42:24.988465 1 dns.go:601] Could not find endpoints for service "busybox" in namespace "cattle-system". DNS records will be created once endpoints show up.
2018/10/10 下午10:42:25 I1010 14:42:25.470257 1 dns.go:222] Initialized services and endpoints from apiserver
2018/10/10 下午10:42:25 I1010 14:42:25.470282 1 server.go:137] Setting up Healthz Handler (/readiness)
2018/10/10 下午10:42:25 I1010 14:42:25.470300 1 server.go:142] Setting up cache handler (/cache)
2018/10/10 下午10:42:25 I1010 14:42:25.470306 1 server.go:128] Status HTTP port 8081

**dnsmasq log**

> I1010 14:42:38.052175 1 main.go:74] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
2018/10/10 下午10:42:38 I1010 14:42:38.052495 1 nanny.go:94] Starting dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
2018/10/10 下午10:42:38 I1010 14:42:38.156225 1 nanny.go:119]
2018/10/10 下午10:42:38 W1010 14:42:38.156254 1 nanny.go:120] Got EOF from stdout
2018/10/10 下午10:42:38 I1010 14:42:38.156267 1 nanny.go:116] dnsmasq[13]: started, version 2.78 cachesize 1000
2018/10/10 下午10:42:38 I1010 14:42:38.156273 1 nanny.go:116] dnsmasq[13]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
2018/10/10 下午10:42:38 I1010 14:42:38.156277 1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain ip6.arpa
2018/10/10 下午10:42:38 I1010 14:42:38.156281 1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa
2018/10/10 下午10:42:38 I1010 14:42:38.156284 1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain cluster.local
2018/10/10 下午10:42:38 I1010 14:42:38.156288 1 nanny.go:116] dnsmasq[13]: reading /etc/resolv.conf
2018/10/10 下午10:42:38 I1010 14:42:38.156293 1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain ip6.arpa
2018/10/10 下午10:42:38 I1010 14:42:38.156297 1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa
2018/10/10 下午10:42:38 I1010 14:42:38.156300 1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain cluster.local
2018/10/10 下午10:42:38 I1010 14:42:38.156304 1 nanny.go:116] dnsmasq[13]: using nameserver 172.16.249.1#53
2018/10/10 下午10:42:38 I1010 14:42:38.156309 1 nanny.go:116] dnsmasq[13]: read /etc/hosts - 7 addresses

**sidecar log**

> I1010 14:42:46.746159 1 main.go:51] Version v1.14.8.3
2018/10/10 下午10:42:46 I1010 14:42:46.746433 1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
2018/10/10 下午10:42:46 I1010 14:42:46.746539 1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
2018/10/10 下午10:42:46 I1010 14:42:46.746621 1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}

**Comment by jinchaoxiang** [comment]
**in system project nslookup log**
`/ # nslookup kubernetes.default
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.43.0.1 kubernetes.default.svc.cluster.local`

**in other project nslookup log** 

`/ # nslookup kubernetes.default
Server:    10.43.0.10
Address 1: 10.43.0.10

nslookup: can't resolve 'kubernetes.default'`

**Comment by loganhz** [comment]
Thanks for your report!

We have an open issue for it.  You can find the solution for it.

Please check https://github.com/rancher/rancher/issues/15146#issuecomment-414738661
