### ISSUE TITLE
server-chart: upgrade from 2.0.8 -> 2.1.0 fails on single node cluster.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#16068]
**Rancher versions:**
rancher/rancher: 2.1.0
rancher/server-chart: 2.1.0

Upgrade from 2.0.8 -> 2.1.0 gets stuck deploying new pods.   Old deployment/replica-set is still running.

```
➜ kubectl get pods -n cattle-system
NAME                       READY   STATUS    RESTARTS   AGE
rancher-544d47bf7f-btn57   1/1     Running   0          3h
rancher-544d47bf7f-khl54   1/1     Running   0          3h
rancher-7bf74f957b-gwxj6   0/1     Pending   0          3h
rancher-7bf74f957b-pf76w   0/1     Pending   0          3h
```

I would expect to see a new pod from the new deployment come up, the old pod come down and two more new pods go into pending since they won't pass the anti-affinity rules.

Instead I see the old deployment/replicaset scale up from 1 to 2 and two pods come up from the new replicaset and hang since they don't pass the anti-affinity rules.

**Comment by deniseschannon** [comment]
@bmdepesa please use what's in the master in the server-chart repo

**Comment by bmdepesa** [comment]
rancher/server-chart:master
Single node cluster

Reproduced by upgrading from 2.0.8 -> 2.1.0

* Deployed 2.0.8 
* Verified one rancher pod running
* Upgraded to server-chart:master
* Old pod was terminated
* 3 new rancher pods were created and went into running
* Performed basic tests (cluster provisioning / some workloads) and everything is functional
