### ISSUE TITLE
[server-chart] Error deploying chart on GKE (evaluating ingress spec)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#16061]
ngres sevice reports on GKE: Error during sync: error while evaluating the ingress spec: service "rancher/rancher" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

Manual updating the created service rancher/rancher to be type NodePort resolves this

have GKE cluster
deploy helmchart (optionally do some value updates)
check GKE dashboard, and notice the rancher ingress stays in state "creating"
Show detail of said ingress and see the error

**Comment by robcharlwood** [comment]
👍 +1 on this. Specifically I think this is related to running the GKE ingress rather than ``nginx`` or ``traefik``. I have raised a PR to allow that allows the service type to be configured by the user. Default behaviour of ClusterIP remains if not explicitly overridden. 😄

**Comment by KevinJoiner** [comment]
@JonCrowther Can you rerun this test with the new helm setting `service.type` set. The new rancher install command would look like this. `helm install rancher ./build/chart/rancher --namespace cattle-system --create-namespace --set global.cattle.psp.enabled=false --set hostname=jono.cp-dev.rancher.space --set bootstrapPassword=admin --set service.type: NodePort`

**Comment by anupama2501** [comment]
Closing the ticket as the validations look good.

**Comment by JonCrowther** [comment]
# Release Notes
## Synopsis of issue

The default type for `cattle-system/rancher` is ClusterIP. When using the default GKE ingress in a cluster not using VPC-native cluster mode (ie `--no-enable-ip-alias` is set) it is incompatible with the ClusterIP type.

## Resolved (or not):

Resolved by adding a new helm setting `--set service.type: NodePort`

## Status:

resolved in v2.7.5

## Versions:

< v2.7.5
