### ISSUE TITLE
[rancher-NFS] socket file not found  with rancher-NFS

### ISSUE THREAD

**Issue by tomtom30** [rancher/rancher#16065]
Hi, 
I have a problem with Rancher NFS service

**Rancher

 versions:**
rancher/rancher: v1.6.21

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: 17.12.0-ce**

**Operating system and kernel:"Ubuntu 16.04.4 LTS" 4.4.0-62-generic

**Type/provider of hosts: VMware Workstation

**Setup details: single node rancher with external DB

**Environment Template: Cattle

**Steps to Reproduce:**

I create NFS service with catalogue. (0.9.7) -> OK
I Launch it -> OK 
I create a portainer service with rancher-nfs driver named "PortainerData:/data" -> FAIL

**Results:**

portainer (Failed to allocate instance [container:1i694]: Bad instance [container:1i694] in state [error]: socket file not found at /var/run/rancher/storage/rancher-nfs.sock)

I have try with boot2docker and rancherOs on host and it done the same issue.

Can you help please. I have try all I can.
Really thanks

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
