### ISSUE TITLE
[windows] `nginx-proxy` container sometimes fails to start

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#16074]
**Rancher versions:**
rancher/server or rancher/rancher:  maiwj/rancher:db7cb551
rancher/agent or rancher/rancher-agent: maiwj/rancher-agent:db7cb551

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Windows 1803

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
Restarting the Windows node, the `nginx-proxy` container occasionally fails to start. I can view the following log in `nginx-proxy`:
```
2018/09/25 02:15:14 [error] 2112#6848: *1551 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 10.0.0.30, server: 0.0.0.0:6443, upstream: "10.0.0.28:6443", bytes from/to client:0/0, bytes from/to upstream:0/0

```
If I restart this `nginx-proxy` container, the windows node will work fine.

**Comment by thxCode** [comment]
There are two cases:
- If `curl -k https://127.0.0.1:6443/healthz` can work on Windows host, that means the connection between `kubelet` and `nginx-proxy` container was broken by some unknown bug in Windows Docker Network or [nginx](https://www.nginx.kr/nginx/) (only 64-bit compiled nginx can work on Windows container)
- If not, there are some errors in the `nginx-proxy` container network.

This issue should be rechecked on later Windows version.

**Comment by yusufmendes** [comment]
@thxCode  @superseb do you intend to solve this problem in version v2.3.Would you please resolve this problem in version 2.2.x.I have to finish my task (linux+windows hybrid cluster on kubernetes) in 10 day.What is your roadmap about v2.3
