### ISSUE TITLE
Project member cannot scale a statefulset via kubectl

### ISSUE THREAD

**Issue by Crokoking** [rancher/rancher#16079]
**Rancher versions:**
rancher/rancher: 2.0.8, 2.1.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GKE

**Steps to Reproduce:**
Add project member to project (might be Github only)
Log in as the user and try to scale a statefulset via UI and kubectl

**Results:**
Scaling via UI works fine, scaling via kubectl throws an error

```
> kubectl --namespace=voidspace get statefulset
NAME                DESIRED   CURRENT   AGE
voidspace-nightly   1         1         140d

> kubectl --namespace=voidspace scale --replicas=0 statefulset/voidspace-nightly
error: Scaling the resource failed with: could not fetch the scale for statefulsets.apps voidspace-nightly: statefulsets.apps "voidspace-nightly" is forbidden: User "user-5ccvh" cannot get statefulsets.apps/scale in the namespace "voidspace": Unknown user "user-5ccvh"
```

**Comment by tnimni** [comment]
use
kubectl -n voidspace patch sts voidspace-nightly -p '{"spec":{"replicas":3}}'

by the way, i see you put replicas = 0 meaning you want to remove all pods, i do believe you have to remove the stateful set first and only then delete the pods
