### ISSUE TITLE
Application scheduling failed

### ISSUE THREAD

**Issue by dongjuanwinhong** [rancher/rancher#16073]
**Rancher versions:**
rancher/server or rancher/rancher:v2.1.0
rancher/agent or rancher/rancher-agent:v2.1.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node ranche

**Steps to Reproduce:**
1.create a cluster has three-nodes
![default](https://user-images.githubusercontent.com/39041059/46783226-09ce4b00-cd5c-11e8-83af-09e93681e8c0.png)

2.Add a workload nginx and Listen host port 8081
![default](https://user-images.githubusercontent.com/39041059/46783295-4306bb00-cd5c-11e8-9127-cf36444c48fc.png)
![default](https://user-images.githubusercontent.com/39041059/46783346-7a756780-cd5c-11e8-94ab-b8d59003bd16.png)
3.View which host the workload is deployed on 
![default](https://user-images.githubusercontent.com/39041059/46783413-b7415e80-cd5c-11e8-84e3-475f8f35c5be.png)
4.eidt this workload and add Node Scheduling,the specified host is the same as the host where the workload is located.
![default](https://user-images.githubusercontent.com/39041059/46783521-2e76f280-cd5d-11e8-9293-79e8b5523744.png)
5.update

**Results:**
the workload display error(Maybe this becanse port occupation,I think it's still a bug when this happens)
![default](https://user-images.githubusercontent.com/39041059/46783707-dab8d900-cd5d-11e8-92e9-c207ec9d863c.png)
![default](https://user-images.githubusercontent.com/39041059/46783692-cecd1700-cd5d-11e8-910a-b6aa0d943082.png)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14985
