### ISSUE TITLE
 The automatic migration is applied successfully, but the original pod is not deleted

### ISSUE THREAD

**Issue by dongjuanwinhong** [rancher/rancher#16075]
**Rancher versions:**
rancher/server or rancher/rancher:v2.1.0
rancher/agent or rancher/rancher-agent:v2.1.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
1.create a cluster with three-nodes
2.deploy workload nginx
3.shutdown the host which nginx located on
![default](https://user-images.githubusercontent.com/39041059/46795601-2169fb80-cd7d-11e8-8bd7-9bf34d28ad7f.png)

4.Observe if the pod is automatically migrated
**Results:**
The automatic migration is applied successfully, but the original pod is not deleted
![default](https://user-images.githubusercontent.com/39041059/46795617-2a5acd00-cd7d-11e8-83bc-92368cd6273b.png)
![default](https://user-images.githubusercontent.com/39041059/46795624-2dee5400-cd7d-11e8-8346-e6ad96761232.png)

**Comment by superseb** [comment]
This is default k8s behavior, see https://github.com/kubernetes/kubernetes/issues/44458 for design decisions on this.
