### ISSUE TITLE
Reconsider/fix Catalog related CRD resources and what we store

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16077]
Created from https://github.com/rancher/rancher/issues/14322.

* Discuss if we want to change the way we store catalog related CRD resources
* Security check stuff that is downloaded and don't store the retrieved content 1-on-1.

**Comment by pehbehbeh** [comment]
Any updates on this? Would highly appreciate a solution here - looks like @StrongMonkey came up with something #16473 back in November?

It would really help if the Enable/Disable toggle of the catalog would be permanent. Currently the Library Catalog gets re-enabled everytime we restart the rancher server workload... and thus the etcd gets filled up again.

**Comment by erikwilson** [comment]
This is maybe fixed as part of rancher/rancher/issues/14322 PR (https://github.com/rancher/rancher/pull/17596), everything is now cached to disk and the icons are checked for media type. There are probably extra security checks we can do for verifying Helm tarballs.

**Comment by deniseschannon** [comment]
It sounds like the caching was introduced in Rancher 2.2.
