### ISSUE TITLE
Additional CAs to trust doesn't seem to work

### ISSUE THREAD

**Issue by Seeefo** [rancher/rancher#16086]
**Rancher versions:**
rancher/rancher: 2.1.0
rancher/server-chart: 2.1.0

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher On a 3 node cluster with a LB.

Chart configuration
```
$ helm get values rancher
additionalTrustedCAs: true
auditLog:
  level: 1
hostname: <fqdn>
```

Secrets list in cattle-system:
```
kubectl get secrets -n cattle-system
NAME                         TYPE                                  DATA      AGE
cattle-credentials-640fef6   Opaque                                2         3h
cattle-token-tm748           kubernetes.io/service-account-token   3         3h
default-token-4x9m6          kubernetes.io/service-account-token   3         0s
default-token-9gs66          kubernetes.io/service-account-token   3         3h
rancher-token-9kpmd          kubernetes.io/service-account-token   3         3h
rancher-token-ctn4c          kubernetes.io/service-account-token   3         37m
tls-ca-additional            Opaque                                1         37m
tls-rancher                  kubernetes.io/tls                     2         3h
tls-rancher-ingress          kubernetes.io/tls                     2         3h
```

**Steps to Reproduce:**
- Created a secret named tls-ca-additional with a file named ca-additional.pem
- Set additionalTrustedCAs=true
- Add a Private Helm repo that uses the cert in the additional store.
- Rancher will fill the logs with errors due to unknown cert.  Private repo won't load either.

**Results:**
Error from the logs:
`2018/10/11 15:47:33 [ERROR] CatalogController sl1 [catalog] failed with : Error in HTTP GET to [<repo URL>], error: Get [<repo URL>]: x509: certificate signed by unknown authority`

I got on one of the Rancher nodes and I see the `ca-additional.pem` is there.  Its not added to the `ca-certifcates.crt` like all the other certs though.
```root@rancher-56b8578574-dstbs:/etc/ssl/certs# ls -al ca*
-rw-rwx---. 1 root root   1646 Oct 11 15:44 ca-additional.pem
-rw-r--r--. 1 root root 207436 Oct  6 00:35 ca-certificates.crt
lrwxrwxrwx. 1 root root     37 Oct  6 00:35 ca6e4ad9.0 -> ePKI_Root_Certification_Authority.pem
```

Can't tell if there is anything I am missing, or if this is a real bug?

**Comment by superseb** [comment]
Does it validate when you run `openssl s_client -CAfile /etc/ssl/certs/ca-additional.pem -connect repo.domain.com:443 -servername repo.domain.com` inside the pod?

If so, can you try setting the environment variable `SSL_CERT_DIR` to `/etc/ssl/certs` on the Deployment and try again with the newly spawned pod?

**Comment by Seeefo** [comment]
> Does it validate when you run `openssl s_client -CAfile /etc/ssl/certs/ca-additional.pem -connect repo.domain.com:443 -servername repo.domain.com` inside the pod?
> 
> If so, can you try setting the environment variable `SSL_CERT_DIR` to `/etc/ssl/certs` on the Deployment and try again with the newly spawned pod?

It does validate when I replace both `-connect` and `-servername` with the repository name. 
```Verify return code: 0 (ok)```

I created the Deployment as such:
```
kubectl get deployments -n cattle-system -o yaml rancher > new_rancher.yml
```
I then modified the env section:
```
        env:
       ...other vars...
        - name: SSL_CERT_DIR
          value: "/etc/ssl/certs"
        image: rancher/rancher:v2.1.0
```
Then a `kubectl apply -f` and I tailed the logs on the first successful pod from the new deployment.  I didn't get the constant spam about `unknown cert`.  I also found one message for the catalog name:
```
2018/10/12 16:54:45 [INFO] Updating catalog test-catalog
```

So looks like adding the environment variable works.

**Comment by cjellick** [comment]
@deniseschannon I guess this is ready for test?

**Comment by deniseschannon** [comment]
If the PR is merged, I think we can test it. @cjellick

**Comment by lllamnyp** [comment]
If anyone comes here looking for a quick workaround, I'd suggest trying out

`kubectl -n cattle-system set env deployment/rancher SSL_CERT_DIR=/etc/ssl/certs`

right after installing the Rancher helm chart. It seems to be doing the job for us so far.

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/7
rancher/server-chart:master 2/7

* Created HA installation with additionalTrustedCAs=true, with file `ca-additional.pem`
* Cert is successfully mounted to `/etc/rancher/ssl`
