### ISSUE TITLE
Maximum number of retries (60) exceeded And Server don't have IP on eth0 provisioning Kubernetes on VMWare vSphere

### ISSUE THREAD

**Issue by MarcusVMesquita** [rancher/rancher#16083]
Rancher versions:
rancher/rancher: 2.1.0

Infrastructure Stack versions:
kubernetes (if applicable): v1.11.3-rancher1-1

Docker version:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Operating system and kernel:
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Type/provider of hosts: VMWare vSphere

Setup details: single node rancher

Environment Template: Kubernetes

Steps to Reproduce:
- Run rancher/rancher docker;
- Create a vSphere Kubernetes cluster and use vSphere template to deploy Kubernetes cluster in VMWare 

Another infos:
- VMWare ESXI version:  6.5.0, 5146846
- VMWare vSphere version: 6.5.0.13000
- RancherOS URL: https://releases.rancher.com/os/latest/rancheros-vmware.iso

Results:

Hi,

I'm trying to create a Kubernetes cluster using vSphere as provider and vSphere template to create all necessary nodes and I'm getting this error during node provision:

[ERROR] NodeController c-szg7r/m-twqgn [node-controller] failed with : Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

On server it's possible to observer that RancherOS created node dont have IPV4 on eth0:
![image](https://user-images.githubusercontent.com/4422802/46823152-d4c5f680-cd63-11e8-90a3-a21b6c9edbd8.png)

Entire provision log:
2018/10/11 14:35:44 [INFO] Generating and uploading node config kubernetes-1,
2018/10/11 14:35:44 [ERROR] NodeController c-szg7r/m-jzzlm [node-controller] failed with : Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded,
2018/10/11 14:37:51 [ERROR] NodeController c-szg7r/m-jzzlm [node-controller] failed with : nodes.management.cattle.io "m-jzzlm" not found,
2018/10/11 14:37:51 [INFO] stdout: Creating CA: management-state/node/nodes/kubernetes-1/certs/ca.pem,
2018/10/11 14:37:51 [INFO] stdout: Creating client certificate: management-state/node/nodes/kubernetes-1/certs/cert.pem,
2018/10/11 14:37:52 [INFO] stdout: Running pre-create checks...,
2018/10/11 14:37:54 [INFO] stdout: Creating machine...,
2018/10/11 14:37:54 [INFO] stdout: (kubernetes-1) Image cache directory does not exist, creating it at management-state/node/nodes/kubernetes-1/cache...,
2018/10/11 14:37:54 [INFO] stdout: (kubernetes-1) Downloading management-state/node/nodes/kubernetes-1/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros-vmware.iso...,
2018/10/11 14:38:00 [INFO] stdout: (kubernetes-1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB),
2018/10/11 14:38:00 [INFO] stdout: (kubernetes-1) Generating SSH Keypair...,
2018/10/11 14:38:01 [INFO] stdout: (kubernetes-1) Creating VM...,
2018/10/11 14:38:03 [INFO] stdout: (kubernetes-1) Uploading Boot2docker ISO ...,
2018/10/11 14:38:08 [INFO] stdout: (kubernetes-1) adding network: VDS-R22/Network_1782,
2018/10/11 14:38:08 [INFO] stdout: (kubernetes-1) Reconfiguring VM,
2018/10/11 14:38:10 [INFO] stdout: (kubernetes-1) Setting disk.EnableUUID to TRUE,
2018/10/11 14:38:12 [INFO] stdout: (kubernetes-1) Waiting for VMware Tools to come online...,
2018-10-11 14:40:02.586280 I | mvcc: store.index: compact 151023,
2018-10-11 14:40:02.587732 I | mvcc: finished scheduled compaction at 151023 (took 862.847µs),
2018/10/11 14:40:08 [INFO] stdout: (kubernetes-1) Provisioning certs and ssh keys...,
2018/10/11 14:40:08 [INFO] stdout: Waiting for machine to be running, this may take a few minutes...,
2018/10/11 14:40:09 [INFO] stdout: Detecting operating system of created instance...,
2018/10/11 14:40:09 [INFO] stdout: Waiting for SSH to be available...,
2018-10-11 14:45:02.590587 I | mvcc: store.index: compact 151384,
2018-10-11 14:45:02.592058 I | mvcc: finished scheduled compaction at 151384 (took 907.445µs),
2018/10/11 14:45:34 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.,
2018/10/11 14:45:34 [INFO] stdout: ,
2018/10/11 14:45:35 [INFO] Generating and uploading node config kubernetes-1,
2018/10/11 14:45:35 [ERROR] NodeController c-szg7r/m-nhfvk [node-controller] failed with : Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded,

**Comment by superseb** [comment]
Does the network have DHCP to provide the node with an IP?

**Comment by MarcusVMesquita** [comment]
Hi,

The network don't have DHCP provider... I'm closing this issue.

But, have any way to provide a server using Rancher with static IP?

**Comment by superseb** [comment]
We added cfgparam for guestinfo here https://github.com/rancher/rancher/issues/13347 which has the downside to create a node template for each node.

Another option is https://github.com/rancher/rancher/issues/15817, which is work in progress atm.
