### ISSUE TITLE
A custom EKS Role prevents cluster creation

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#16080]
Problem:
When creating an EKS cluster with a custom service role, the cluster fails to create with error message:
`Error getting role: NoSuchEntity: The role with name AROAJAT42HXT5PISP5ZSE cannot be found. status code: 404, request id: aa86a480-cd6d-11e8-ab86-e536efbf76bf`

Expected:
EKS cluster will create successfully with a custom service role.

Notes:
The root cause of this issue is that kontainer-engine and the UI are using different fields to identify the role.  Kontainer-engine expects a role name, but the UI is sending the role id.  This can be resolved by modifying the UI to send the role name, or modifying kontainer-engine to accept the role ID.

This bug exists in Rancher 2.0.8.

**Comment by westlywright** [comment]
@tfiduccia UI tag: 2.1.1 for backport testing

**Comment by t-readyroc** [comment]
Just a note that I'm [definitely still seeing this in 2.1.0](https://forums.rancher.com/t/clusters-wont-create-role-cannot-be-found/12223).

**Comment by tfiduccia** [comment]
@t-readyroc - this fix won't be available until the 2.2.0 release.

**Comment by t-readyroc** [comment]
@tfiduccia right, that's what I read - just wanted to note it was present in 2.1 as the initial report was for 2.0.8.

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/3/18)
Confirmed fixed. I am able to create an Amazon AKS cluster when we utilize a custom Service Role. Further, I validated HTTP POST to amazon API to ensure we are properly formatting RoleId/RoleName. Reviewed docker logs and found no issues as well. Halo tested as well. The cluster operates correctly.
