### ISSUE TITLE
Multiple calls to load Vendor CSS

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#16084]
UI is loading the vendor CSS file twice.

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/7/19)
Confirmed fixed.
Started with an empty browser cache, monitor http traffic, launch rancher server URL, observed that vendor.js is only requested once. Navigate to other pages ensure is not requested again. Log out and log back in with same browser cache/session and confirm vendor.js is still not requested again.
