### ISSUE TITLE
Font (size) changed in Shell windows

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16089]
Version: master

Since new Xterm.js

<img width="380" alt="screen shot 2018-10-11 at 23 11 51" src="https://user-images.githubusercontent.com/2620179/46834245-2ba2ee80-cdab-11e8-83d2-2266ed3b2d8c.png">
<img width="337" alt="screen shot 2018-10-11 at 19 51 05" src="https://user-images.githubusercontent.com/2620179/46834246-2c3b8500-cdab-11e8-9faa-a29ddba0c9f5.png">

**Comment by tfiduccia** [comment]
Version - 2.2 master
Verified fixed
