### ISSUE TITLE
process list grows and causes rancher to act up.

### ISSUE THREAD

**Issue by phynias** [rancher/rancher#16094]
More and more the process list in rancher gets out of control. which then causes most of rancher to function erraticly.  Currently there are around 80k processes. 50k of which are volumestoragepoolmap.remove which always seems to have a ton. Most of the time the rest of the queue items are relatively  low (around 20 or so). I have 4 rancher servers in HA mode. All with low load and cpu usage. 

When it gets this high rancher just act weird. It will take time for certain things to happen that normally are instant. It can cause upgrades to to fail and become stuck. 

It almost feels like the 40K volume remove tries again every now and then and when that happens all the other processes pile up. I'm not sure though.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.22` Cattle: `v0.183.63` UI: `v1.6.47` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.processes.list`|

**Comment by loganhz** [comment]
Can you go to the agent host and check if there are a lot of containers in `dead` status?

**Comment by phynias** [comment]
the ones that i run rancheros come up with   17.06.2-ce
my ubuntus are 17.09

**Comment by loganhz** [comment]
OK, Thanks. 
Please try `docker ps -aq --filter status=dead` on your agent host to find out if it is due to the dead container

**Comment by phynias** [comment]
i'm pretty sure its due to hosts disconnecting and then never coming back.
we have machines that come up and go away as they are always used in
different ways. we have ec2 instances that come online and then deleted for
scaling.
i have a lot of agents and so running that on all of them is kind of tough.

**Comment by loganhz** [comment]
https://github.com/rancher/rancher/issues/6808#issuecomment-266551514

**Comment by phynias** [comment]
i got this under control by deleting a couple hosts that where dead and gone, but the problem still exists. i have about 300 volumestoragepoolmap.remove that are sitting in delayed since last year. when i click on the resource in the process list it shits 'Not Found'. so i am not even sure how to clear these up. 

is there a query i can run in the db to find out what host this resource was associated with?
or something i can do to clear these out?


![screen shot 2018-10-22 at 4 30 46 pm](https://user-images.githubusercontent.com/10147213/47325251-dc18ba00-d617-11e8-849b-d9e3445d5240.png)


![screen shot 2018-10-22 at 4 30 15 pm](https://user-images.githubusercontent.com/10147213/47325253-dfac4100-d617-11e8-9a18-6384cf5edd42.png)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
