### ISSUE TITLE
Add UI Support for AssociatePublicIPAddress

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#16090]
Add UI Support for https://github.com/rancher/rancher/issues/15419. We will need a boolean field `associateWorkerNodePublicIp`. The field should default to `true`.  If the field is set to `false`, then the user must also specify a custom VPC and Subnet(s).

**Comment by westlywright** [comment]
ready to test on master

**Comment by davidnuzik** [comment]
Version: master 2.2 (11/29/18)
Confirmed new UI feature VPC & Subnet section of EKS config. I tested all the different options in the UI with the radio buttons. I made sure that we can select a custom VPC and that the calls to amazon API went thru correctly and that the UI updates to show the subnets once we pick a VPC. My customized cluster worked without any issues as well as with default options. I made sure I can select multiple subnets as well. Halo testing was also performed.
