### ISSUE TITLE
Backport UI for EKS Session Token to 2.1

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#16091]
Backport UI issue to 2.1: https://github.com/rancher/rancher/issues/16087

**Comment by westlywright** [comment]
Waiting for RC to release

**Comment by alena1108** [comment]
Backend is tracked in https://github.com/rancher/rancher/issues/16007

**Comment by tfiduccia** [comment]
Version - 2.1.2-rc2
Verified fixed
