### ISSUE TITLE
Backport UI support for AssociatePublicIPAddress to 2.1

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#16092]
Backport UI support for AssociatePublicIPAddress to 2.1:  https://github.com/rancher/rancher/issues/16090

**Comment by westlywright** [comment]
will be ready for test when new rc is created `>v2.1.1-rc2`

**Comment by deniseschannon** [comment]
Available in v2.1.1-rc3

**Comment by tfiduccia** [comment]
Version - 2.1.1 rc5
Verified fixed
