### ISSUE TITLE
server-url setting not update

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#16098]
**Rancher versions:** 
rancher/server or rancher/rancher:   2.1
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.13.1

**Steps to Reproduce:**
Build Rancher 2.1 using RKE. 
Set server-url at first time login to http://host1/
Login and change server-url in Global/setting to http://host2/
Login out and login
In Cluster.local view kubeconfig file or open launch kubectl
in kubeconfig file server: "http://host1"
in launch kubectl,  cat ~/.kube/config still have only server-url http://host1/

**Expect Results:**
server-url change to http://host2/

This causes a problem if I have F5 load-balance in front. I have to wait for F5 created before set server-url first time or change kubeconfig  everytime I download the file.

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/14731
