### ISSUE TITLE
[RFE] have rke snapshot etcd automatically, once a day. either via rke or custom clusters created by rancher

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16093]
**Purpose:**
Have rke snapshot etcd automatically, once a day. either via rke or custom clusters created by rancher

**Comment by loganhz** [comment]
Link https://github.com/rancher/rancher/issues/13688

**Comment by superseb** [comment]
https://github.com/rancher/rke/issues/888
https://rancher.com/docs/rke/v0.1.x/en/etcd-snapshots/#etcd-recurring-snapshots

**Comment by aemneina** [comment]
Closing in favor of the rke bug, and will pursue another ticket for rancher backup ui
