### ISSUE TITLE
Vagrant, ssh-authorization fails on restart

### ISSUE THREAD

**Issue by indeyets** [rancher/rancher#161]
We set up rancher in Vagrant. It seems to work on the first run, but after the restart ssh-key is no longer accepted and we have to re-create the VM.

On the first run there is a notification about replacing insecure key. I wonder if that is related somehow.

**Comment by indeyets** [comment]
seems to be related to https://github.com/mitchellh/vagrant/issues/5153 and https://github.com/mitchellh/vagrant/issues/5219 (Vagrant 1.7 issue)

**Comment by indeyets** [comment]
adding `config.ssh.insert_key = false` to `Vagrantfile` might help. testing it now

**Comment by karlingen** [comment]
It might help the first time with `config.ssh.insert_key = false`, but after a virtualbox or vagrant upgrade you will get the password prompt again.

**Comment by stephenlawrence** [comment]
Any fixes for this? We are dealing with the same issue. Once I create the vagrant box, if I stop and start it it just loops through "rancher: Warning: Authentication failure. Retrying..."

**Comment by diogogmt** [comment]
I'm having the same issue.

**Comment by cloudnautique** [comment]
We recently cutover to using RancherOS in our Vagrant environment. We are interested to hear how it impacts this issue.

**Comment by deniseschannon** [comment]
I'm going to close this issue as we haven't heard any issues after we've moved over to RancherOS. If anyone has issues with vagrant file, please open a new one or comment back on this one.
