### ISSUE TITLE
Error connecting to WebSocket

### ISSUE THREAD

**Issue by huangyanhong** [rancher/rancher#16101]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent:2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
calico 

scheduler:
1.8.4
kubernetes (if applicable):
1.8.4 
**Docker version: (`docker version`,`docker info` preferred)**
17.09.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7.4              3.10.0-693.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
kubectl create -f  rancher.yaml
( I install 3 replicas rancher in k8s cluster)
rancher.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
   kind: ClusterRole
   name: cluster-admin
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rancher
  name: rancher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher
      ima: pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rancher
        ima: pod
    spec:
      containers:
      - image: rancher/rancher:stable
        imagePullPolicy: Always
        name: rancher
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 30
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rancher
  labels:
    app: rancher
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: rancher
---
apiVersion: v1
kind: Service
metadata: 
  name: rancher-nodeport
spec: 
  type: NodePort
  selector:
     app: rancher
  ports: 
  - name: rancher-api
    protocol: TCP
    nodePort: 30443
    port: 443
    targetPort: 443

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
access the rancher ui 

**Results:**

**### Error connecting to WebSocket
Unable to establish a WebSocket connection to the server. If your server is behind a proxy or SSL-termination device, Browser can not connect to WebSocket. If you run the server behind a proxy, please make sure the proxy supports WebSockets. Streaming stats, logs, shell/console, and auto-updating of the state of resources may not work until this is resolved.**

**Comment by superseb** [comment]
Running more than 1 replica is supported from v2.1.0, please setup a cluster using the Helm install method https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/ and you get v2.1.0 and 3 replicas which should work by default.

Let me know if this doesn't solve your issue.
