### ISSUE TITLE
When creating RKE clusters, expand the options section 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#16108]
When creating k8s clusters that use RKE, the options are not expanded open, which makes it hard to know which k8s version is going to be deployed by default. 

From UX, I think it'd be better if it was expanded so people could see the options immediately.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (11/26/18)
Confirmed fixed. Tested with all RKE providers. Cluster options section is now automatically opened.
