### ISSUE TITLE
LB rules are not functional when source and tagert ports for service targets are different.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1610]
Server version - v0.29.0-rc1

steps to reproduce the problem:
Created a LB service with source port as 7777 and target port as 80.
Added 1 service and chose only service (did not provide any other parameters).

API shows ports on LB service is set correctly:
"ports": [
"7777:80",
],

source port is not configured in happroxy

<img width="717" alt="screen shot 2015-07-22 at 8 54 21 am" src="https://cloud.githubusercontent.com/assets/4266958/8830306/595fdb04-3050-11e5-9476-1b85788c9346.png">

iptables cofigured for source port on host as expected:

-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 7777 -j DNAT --to-destination 10.42.40.179:7777

LB rules are not functional:
Sangeethas-MBP:testwget sangeethahariharan1$ wget http://104.197.40.91:7777/name.html
--2015-07-22 09:04:00--  http://104.197.40.91:7777/name.html
Connecting to 104.197.40.91:7777... failed: Connection refused.
Sangeethas-MBP:testwget sangeethahariharan1$

**Comment by alena1108** [comment]
happens because private port is not set correctly. Fixing it.

**Comment by sangeethah** [comment]
Tested with build from master:
LB rules are functional when source and tagert ports for service targets are different.
source port is configured in happroxy.
