### ISSUE TITLE
creating a ingress status has always been Initializing

### ISSUE THREAD

**Issue by huntsman-li** [rancher/rancher#16100]
![image](https://user-images.githubusercontent.com/36752240/46855205-9a2c8e80-ce35-11e8-8546-3260a67d3887.png)

**Comment by loganhz** [comment]
Thanks for your report.

Can you supply more info on your setup ?(basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Please submit another issue with more detail. Thanks
