### ISSUE TITLE
Rancher server with unprivileged service account

### ISSUE THREAD

**Issue by tobru** [rancher/rancher#16102]
**Rancher versions:**

2.1.0

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher HA installation on OpenShift using Helm, without applying `clusterRoleBinding.yaml`.

**Steps to Reproduce:**

```
helm install ./rancher \
  --name rancher \
  --namespace rancher \
  --set tls=external \
  --set hostname=blubb.example.com \
  --set ingress.tls.source=none
```

(Copy of [rancher/server-chart](https://github.com/rancher/server-chart), removed `rancher/templates/clusterRoleBinding.yaml`)

**Results:**

```
2018/10/12 11:58:21 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:true ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2018/10/12 11:58:21 [INFO] Listening on /tmp/log.sock
2018/10/12 11:58:21 [INFO] Activating driver aks
2018/10/12 11:58:21 [INFO] Activating driver aks done
2018/10/12 11:58:21 [INFO] Activating driver eks
2018/10/12 11:58:21 [INFO] Activating driver eks done
2018/10/12 11:58:21 [INFO] Activating driver import
2018/10/12 11:58:21 [INFO] Activating driver import done
2018/10/12 11:58:21 [INFO] Activating driver rke
2018/10/12 11:58:21 [INFO] Activating driver rke done
2018/10/12 11:58:21 [INFO] Activating driver gke
2018/10/12 11:58:21 [INFO] Activating driver gke done
I1012 11:58:21.470253       8 http.go:108] HTTP2 has been explicitly disabled
2018/10/12 11:58:21 [FATAL] namespaces "cattle-system" is forbidden: User "system:serviceaccount:rancher:rancher" cannot get namespaces in the namespace "cattle-system": no RBAC policy matched
```

I would want to run Rancher control plane on an already existing OpenShift cluster, without managing the cluster itself but instead using it to manage other Kubernetes clusters. How can I run Rancher on a Kubernetes cluster where the ServiceAccount doesn't have access to the cluster itself (at least no cluster-admin)? Similar to running Rancher "[Single Node Install](https://rancher.com/docs/rancher/v2.x/en/installation/single-node/)", but on a Kubernetes / OpenShift cluster.

**Comment by tobru** [comment]
Ok, discovered by myself: Had to make `/etc/kubernetes` and `/var/lib/rancher` a writeable volume and Rancher is now happily starting!

**Comment by patlachance** [comment]
@tobru are you using the official docker.io/rancher/rancher image running with extended privileges (ie: running as user root) or you managed to build your own image?

@superseb : any plan to release official rancher images that don't run as root ?
