### ISSUE TITLE
rancher exec always returns zero exit code

### ISSUE THREAD

**Issue by grabekm90** [rancher/rancher#16103]
I know development on v1.6 is only limited to critical bug fixes and security patches but we use Rancher in CI to run tests. The bug was introduced in v0.6.9 CLI version:
https://github.com/rancher/cli/releases/tag/v0.6.9

**Rancher versions:**
rancher/cli: 0.6.9, 0.6.10, 0.6.11, 0.6.12
rancher/server or rancher/rancher: 1.6.22
rancher/agent or rancher/rancher-agent: 1.2.11

**Steps to Reproduce:**
```
$ rancher exec bash
root@service: exit 1
$ echo $?
0
```

**Results:**
rancher exec always returns zero exit code

**Comment by andrezaycev** [comment]
```
root@ADP-INF-APP-01:/tmp# ./rancher -v
rancher version v0.6.4
root@ADP-INF-APP-01:/tmp# rancher -v
rancher version v0.6.12
root@ADP-INF-APP-01:/tmp# ./rancher exec -i  1i93995 lsssss || echo 1
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "exec: \"lsssss\": executable file not found in $PATH"

1
root@ADP-INF-APP-01:/tmp# rancher exec -i  1i93995 lsssss || echo 1
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "exec: \"lsssss\": executable file not found in $PATH"
```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
