### ISSUE TITLE
"Add Load Balancer" page should show "Default Target Port" for "Listening Ports" in the default view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1611]

**Comment by sangeethah** [comment]
Server version - V0.29.0-rc1

Launch the ""Add Load Balancer" page". The Listening ports shows only "Source Port" . Should also include "Default Target Port" field.  This field shows up only when "Show advanced routing options" is selected.
<img width="1052" alt="screen shot 2015-07-22 at 9 45 44 am" src="https://cloud.githubusercontent.com/assets/4266958/8831413/fc4b829a-3056-11e5-8f84-144a9df18e59.png">

**Comment by vincent99** [comment]
This was intentional, but at 1am and maybe too simplified... Opinions @ibuildthecloud and @alena1108 ?

**Comment by deniseschannon** [comment]
Verified Fixed in v0.31.0-rc4
