### ISSUE TITLE
Backport: UX Change: Unable to see annotation on Load Balacer Rules Unless they're edited

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#16112]
Backport: https://github.com/rancher/rancher/issues/15096

**Comment by deniseschannon** [comment]
Available in v2.1.1-rc3

**Comment by tfiduccia** [comment]
This is not better.  I added a 1 label and 1 annotation.  Now I see 2 labels from annotations and 0 from labels.

![image](https://user-images.githubusercontent.com/11514927/46897525-eaa4eb80-ce37-11e8-9678-5e53653d610f.png)

**Comment by westlywright** [comment]
available in UI Tag: `2.1.4`

**Comment by deniseschannon** [comment]
Available in v2.1.1-rc5

**Comment by tfiduccia** [comment]
Version - 2.1.1 rc5
Verified fixed
