### ISSUE TITLE
Wrong DNS resolving on workloads with same image

### ISSUE THREAD

**Issue by gjongenelen** [rancher/rancher#16129]
**Rancher versions:**
rancher/rancher: 2.0.8
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes /Canal

**Steps to Reproduce:**
1 Workload on image1 (named inbound1)
2 Workloads on image2 (named work1 and work2)
Ping work1.namespace.svc.cluster.local from inbound1
You get IPs resolved from work2. 

**Results:**
Wrong workload selected resulting in wrong response or connections refused

**Comment by superseb** [comment]
Not able to reproduce, can you provide exact steps to reproduce? Also the output from `kubectl get ep -n namespace1/namespace2` and `kubectl get pods -n namespace1/namespace2 -o wide`

**Comment by gjongenelen** [comment]
For me to reproduce is just creating services with the same image.

I think this explains the problem very well (compute is the namespace):
```
> kubectl get ep -n compute
NAME            ENDPOINTS                                               AGE
cloud-workers   10.42.0.74:42,10.42.0.75:42,10.42.0.76:42 + 3 more...   153d
php             10.42.0.74:42,10.42.0.75:42,10.42.0.76:42 + 3 more...   94d
redis           10.42.0.6:42                                            153d
websocket       10.42.0.74:42,10.42.0.75:42,10.42.0.76:42 + 3 more...   153d
```
Different workloads with exact same IPs

```
> kubectl get pods -n compute -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP           NODE
cloud-workers-5b9dbd6dd5-lbr9m   1/1       Running   11         94d       10.42.0.78   ip-172-30-0-161
cloud-workers-5b9dbd6dd5-np62x   1/1       Running   13         94d       10.42.0.79   ip-172-30-0-161
php-657d6c559f-7h5cq             1/1       Running   1          94d       10.42.0.75   ip-172-30-0-161
php-657d6c559f-fk8k9             1/1       Running   1          94d       10.42.0.74   ip-172-30-0-161
php-657d6c559f-nbrjh             1/1       Running   1          94d       10.42.0.76   ip-172-30-0-161
redis-78c9dd9b65-ptltb           1/1       Running   4          153d      10.42.0.6    ip-172-30-0-161
websocket-74984645cd-sv6vn       1/1       Running   1          83d       10.42.0.81   ip-172-30-0-161
```

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
