### ISSUE TITLE
Edit Load Balancer is not able to show existing targets.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1612]
Server version - v0.29.0-rc1

Created a LB service with source port as 7777 and target port as 80.
Added 1 service and chose only service (did not provide any other parameters).

Now edit this LB.
On the Edit Load Balancer page , no service targets are listed.

Expected Behavior:
Should be able to all targets in the Edit Load Balancer page.

**Comment by vincent99** [comment]
This was broken for "basic" targets that had no hostname/srcPott/path/dstPort.

**Comment by sangeethah** [comment]
Server version - v0.29.0-rc2

Created a LB service with 2 service and chose only service (did not provide any other parameters).

Now edit this LB.
On the Edit Load Balancer page ,all service targets are listed.
