### ISSUE TITLE
rancher clobbers dnsConfig in YAML

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#16126]
Forgive me if this is answered somewhere else...I've been searching for weeks and am unable to find any reference to it as either a problem or a solution.

**Problem:**

There are issues with alpine containers and the musl resolver library. These most commonly show up as Kubernetes not appending search domains or else appending search domains to everything. The default `resolv.conf` in pods is setting `options ndots 5`, which results in normal queries for `host.domain.com` failing because it refuses to do an absolute lookup for anything with less than 5 dots in it. This shows up as something like this:

```
Error: getaddrinfo EAI_AGAIN api.darksky.net:443
```

You can read about this [here](https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html) and [here](https://github.com/kubernetes/kubernetes/issues/45976), but I suspect you're already aware of the issue.

The solution/workaround is easy:  for all alpine containers, add the following to the pod spec:

```
dnsConfig:
  options:
  - name: ndots
    value: "1"
```

This results in DNS queries for both search domains and absolute hosts for anything that has a single dot.

The problem is that Rancher clobbers this. I'm unable to find a means to set it through the UI, and setting it directly in the YAML (either through `kubectl edit` or `view/edit YAML` in the UI) works for that single update. I can delete pods and have them recreated with the option set, but if I update the YAML or scale replicas to 0 and back up to 1, this directive is no longer present in the configuration.

I said in the beginning that I've searched high and low for a solution to this, or even for anyone else referencing it as a problem. When I'm unable to find even that, I assume that it's _my_ problem, so I've delayed opening a ticket. I'm now out of solutions, so I hope that there's either something I've missed, or that it's actually a bug.

**Steps to Reproduce:**

1. deploy a workload
2. edit it and set dnsConfig options
3. let it deploy the updated pod
4. edit it again and change something else
5. view the new config and see that the `dnsConfig` options are gone

**Results:**

- `dnsConfig` is removed from the pod spec

**Comment by loganhz** [comment]
This is an UI bug. https://github.com/rancher/ui/blob/master/app/models/workload.js#L337

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/48527500-5b6f7580-e8c6-11e8-8ae4-45f690616405.png)
Fixed the issue and added dnsConfig in networking section

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/9/19)
Confirmed fix. I was not able to reproduce the issue. I tried both with the steps to reproduce by editing the YAML and via the new UI additions and the DNS settings remained both times. I tried to bring the scale down to zero and back up again. No matter what I try we keep the dnsConfig now. There are now additional DNS config options when creating a workload under the "Networking" section.
![image](https://user-images.githubusercontent.com/45179589/50918072-74932f00-13fc-11e9-91d3-4b8c20567b31.png)
You can also now see this data when viewing the workload details.
![image](https://user-images.githubusercontent.com/45179589/50918049-6513e600-13fc-11e9-97de-53fc5fdd5346.png)
I halo tested and validated this new section and was not able to identify any issues. Validated HTTP/UI API/YAML.
