### ISSUE TITLE
It is right  when add node-temlate?

### ISSUE THREAD

**Issue by Baozi2** [rancher/rancher#16128]
**Rancher versions:**
rancher/rancher 2.1
![node-template](https://user-images.githubusercontent.com/5621510/46930240-182ba800-d077-11e8-88ad-ab884a27a469.png)

**Comment by loganhz** [comment]
Can you supply more info on your setup? (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
