### ISSUE TITLE
Cannot access API using Kubectl Proxy

### ISSUE THREAD

**Issue by jmwilkinson** [rancher/rancher#16138]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0 / latest
rancher/agent or rancher/rancher-agent: 2.0 / latest
 
**Infrastructure Stack versions:**
healthcheck: standard
ipsec: standard
network-services: flannel
scheduler: standard
kubernetes (if applicable): 1.11.2-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)**
18.06-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos 7.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernets

**Steps to Reproduce:**
Cannot access kubernetes API from Rancher kube installation when using `kubectl proxy`.

Expected behavior is ability to run `kubectl proxy`, and then access the api normally, i.e. `curl http://127.0.0.1:8001/api` should return standard info about the api- version, CIDR info, etc. However, it gives a 404 error.

**Comment by superseb** [comment]
Rancher can proxy requests to multiple clusters, so you have to specify where you want to go:

```
http://localhost:8001/k8s/clusters/CLUSTERID/
```

where CLUSTER is = `c-xxxxx`

**Comment by jmwilkinson** [comment]
I understand that, I don't want to proxy the request through rancher.

Writing directly to the api, as per [this solution](https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-408599873), can apparently solve certain problems in kubernetes. This does not appear to be possibly with rancher's proxying.

There is no obvious way to effectively use the API directly under these conditions.

**Comment by superseb** [comment]
That's covered in https://github.com/rancher/rancher/issues/13698

**Comment by zhanghongtong** [comment]
@superseb I executed the `kubectl proxy`, then accessed it and got the following log

**Comment by mukeshyadav1997** [comment]
Hi, 
Can anyone of you help me.
when I do :curl http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "services \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "services"
  },
  "code": 404
}
