### ISSUE TITLE
Rancher 2.1 HA - SSL wildcard cert issue

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#16137]
**Rancher versions:**
Rancher 2.1.0

**Steps to Reproduce:**
1. Follow this document for HA install - https://rancher.com/docs/rancher/v2.x/en/installation/ha/
2. Adding a wildcard cert using by following this section - https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#certificates-from-files-kubernetes-secret

**Results:**
It seems like we are now unable to use wildcard certs even though my rancher 2.0.8 deployment was successful using this article - https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/layer-7-lb/

There is a note which says the common name must match the hostname which I'd imagine could be the issue 
`Note: The common name for the cert will need to match the hostname option or the ingress controller will fail to provision the site for Rancher.`

When execute any API calls I'm hitting the following (using python requests):
`requests.exceptions.SSLError: HTTPSConnectionPool(host='dvl-rancher.scm.jnj.com', port=443): Max retries exceeded with url: /v3/clusters (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))`

My cert is for *.scm.jnj.com and I am using a privately signed CA

I can temporarily add in verify=False, but was wondering if anyone else had success using a wildcard cert.

**Comment by massimo-cannavo** [comment]
I believe that is expected and normal behavior because the private root CA is not trusted. Executing the API call will fail to verify the root CA because your private certificate store does not have the root CA. You will need to include it in order to establish the trust.

Python Request Library
```
requests.get('https://dvl-rancher.scm.jnj.com', verify='/path/to/cacert')
```

**Comment by nxf5025** [comment]
Yup that's it. Thanks for looking into it.
