### ISSUE TITLE
RKE component logs issue with internal fluentd

### ISSUE THREAD

**Issue by renesch-de** [rancher/rancher#16133]
Due to local storage restrictions, we need to store anything large on our servers in `/big`, including the docker installation, and then symlink to them from the original location. This seems to cause minor issues when enabling cluster logging in rancher. I looked into the issue, and saw the following logs for the fluentd container on my agent for each of my containers:

`2018-10-15 09:09:27 +0000 [warn]: #0      /var/lib/rancher/rke/log/kube-scheduler_57c1405279ca581658bb0d6093a5a43d8f473ba4acbb947bce1c5883e4ada765.log unreadable. It is excluded and would be examined next time.`
`2018-10-15 09:09:27 +0000 [warn]: #0      /var/lib/rancher/rke/log/kubelet_ba85faa5f99dbf6986d8cb36a808d3437254231d96bc7d61a80a6024326bed5c.log unreadable. It is excluded and would be examined next time.`

Strangely these warnings are only related to the folder `/var/lib/rancher/rke/log`. As far as I can see, all RKE logs are actually available in elasticsearch regardless of the warnings, but I want to get rid of these warnings nevertheless.

The Rancher created fluentd configuration looks fine to me in a quick glance:
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: 2018-10-12T10:38:17Z
  generation: 1
  labels:
    cattle.io/creator: norman
    k8s-app: fluentd
  name: fluentd
  namespace: cattle-logging
  resourceVersion: "783310"
  selfLink: /apis/apps/v1beta2/namespaces/cattle-logging/daemonsets/fluentd
  uid: ede9679a-ce0a-11e8-b539-509a4c53ed2e
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fluentd
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: fluentd
      name: fluentd
      namespace: cattle-logging
    spec:
      containers:
      - args:
        - --watched-file-list
        - /fluentd/etc/config/cluster
        - --watched-file-list
        - /fluentd/etc/config/project
        - --watched-file-list
        - /fluentd/etc/config/custom/cluster
        - --watched-file-list
        - /fluentd/etc/config/custom/project
        - --watched-file-list
        - /fluentd/etc/ssl
        command:
        - fluentd-helper
        image: rancher/fluentd-helper:v0.1.2
        imagePullPolicy: Always
        name: fluentd-helper
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentd/etc/config/cluster
          name: cluster-logging
        - mountPath: /fluentd/etc/config/project
          name: project-logging
        - mountPath: /fluentd/etc/config/custom/cluster
          name: clustercustomlogconfig
        - mountPath: /fluentd/etc/config/custom/project
          name: projectcustomlogconfig
        - mountPath: /fluentd/etc/ssl
          name: sslconfig
      - args:
        - -c
        - /fluentd/etc/fluent.conf
        command:
        - fluentd
        image: rancher/fluentd:v0.1.10
        imagePullPolicy: IfNotPresent
        name: fluentd
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentd/etc/config/cluster
          name: cluster-logging
        - mountPath: /fluentd/etc/config/project
          name: project-logging
        - mountPath: /fluentd/etc/config/custom/cluster
          name: clustercustomlogconfig
        - mountPath: /fluentd/etc/config/custom/project
          name: projectcustomlogconfig
        - mountPath: /big/docker/containers
          name: varlibdockercontainers
        - mountPath: /var/log/containers
          name: varlogcontainers
        - mountPath: /var/log/pods
          name: varlogpods
        - mountPath: /var/lib/rancher/rke/log
          name: rkelog
        - mountPath: /var/lib/rancher/log-volumes
          name: customlog
        - mountPath: /fluentd/log
          name: fluentdlog
        - mountPath: /fluentd/etc/ssl
          name: sslconfig
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluentd
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        value: "true"
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        value: "true"
      volumes:
      - name: cluster-logging
        secret:
          defaultMode: 420
          secretName: cluster-logging
      - name: project-logging
        secret:
          defaultMode: 420
          secretName: project-logging
      - hostPath:
          path: /var/lib/rancher/fluentd/etc/config/custom/cluster
          type: ""
        name: clustercustomlogconfig
      - hostPath:
          path: /var/lib/rancher/fluentd/etc/config/custom/project
          type: ""
        name: projectcustomlogconfig
      - hostPath:
          path: /big/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /var/log/containers
          type: ""
        name: varlogcontainers
      - hostPath:
          path: /var/log/pods
          type: ""
        name: varlogpods
      - hostPath:
          path: /var/lib/rancher/rke/log
          type: ""
        name: rkelog
      - hostPath:
          path: /var/lib/rancher/log-volumes
          type: ""
        name: customlog
      - hostPath:
          path: /var/lib/rancher/fluentd/log
          type: ""
        name: fluentdlog
      - name: sslconfig
        secret:
          defaultMode: 420
          secretName: sslconfig
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
  observedGeneration: 1
  updatedNumberScheduled: 2

Any suggestions how to proceed?

**Rancher versions:**
2.1.0

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.11.3

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /big/docker/aufs
 Backing Filesystem: extfs
 Dirs: 196
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Docker Root Dir: /big/docker

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.13.0-46-generic
Ubuntu 17.10

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Install docker
move the docker installation to another dir
sym link /var/lib/docker to your new location
start rancher agent as normal on that machine and add it to your cluster
configure cluster logging in rancher UI to send to a valid elasticsearch endpoint
view logs of fluentd container started on the agent

**Results:**

**Comment by Kralor-Guldan** [comment]
This issue is affecting us as well. Are there any known solutions?

**Comment by speedfire514** [comment]
This is something we encountered as well. I don't have any workaround but either don't use rancher logging and use fluentd yourself or reinstall/restart rancher cluster logging pods

**Comment by aiwantaozi** [comment]
Seems like fluentd couldn't get the real log file, whether the docker root is default /var/lib/docker? If the docker root is not the default /var/lib/docker, you can change the docker root at cluster configure option page, then the Fluentd will mount the correct docker root, then the symbol link chain is complete.

**Comment by aiwantaozi** [comment]
For collect rke log, rke will create some symlink like what kubelet does, after the container recreates, the real container log for old container is deleted, but the symlink still there, this will cause above error. Need to get the fix from rke to remove the legacy symlink.

**Comment by MrBones757** [comment]
I'm seeing this issue too exactly as described - willing to test any workarounds / fixes that may eventually be made available

**Comment by aiwantaozi** [comment]
@MrBones757 Hi, could you help check what the Rancher server version and Kubernetes version? What provider you use to create the cluster, `add custom node` or other providers?

**Comment by MrBones757** [comment]
Hi - sorry for the slow reply.

I'm using:
    rancher 2.2.7
    kubernetes: 1.14.5
    docker: 19.3.1

Cluster is deployed using custom method (using own nodes)

**Comment by aiwantaozi** [comment]
@MrBones757 Have you check docker root? If docker root is not the default `/var/lib/docker`, change it in cluster option page. Have check those files' symbol link inside the fluentd container?

**Comment by floydljy** [comment]
Hello I hit the same bug in the rke cluster which is custom created cluster.
I'm not using the default docker root. and I have already set it as /data/docker in the cluster option. 
but when checking the daemonset of the fluentd , there's no real docker root mounted. so I manually mount the real docker root path by "kubectl edit daemonset", and after save it. everything goes well now. 
This is definitely a bug that the "rancher fluentd daemonset“ does not parse the docker root when docker root is not default.

**Comment by paynejacob** [comment]
With logging v2 introduced in rancher 2.5, support was added for configuring non standard docker roots.

https://rancher.com/docs/rancher/v2.x/en/logging/v2.5/
https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/rancher-logging/3.9.400/values.yaml#L169
