### ISSUE TITLE
Sorting members list by user not working

### ISSUE THREAD

**Issue by mhoyer** [rancher/rancher#16130]
**Rancher versions:**
rancher/server or rancher/rancher: 2.1.0

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.11.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2 CE

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- HA Rancher, 4 nodes
- Internal DB
- Authentication via Active Directory

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
- Kubernetes

**Steps to Reproduce:**
- Just create a proper set of users
- Go to _Members_ list of a cluster (or a namespace)
- Try to sort the list by _User_ (clicking the table header)

![screen-rec](https://user-images.githubusercontent.com/76611/46866599-6300b200-ce22-11e8-94b8-6e14239f3857.gif)
(For instance, see my account _Marcel Hoyer_)

**Results:**
It changes the order somehow, but not by username (as expected).

**Comment by davidnuzik** [comment]
Version: master 2.2 (11/30/18)
Confirmed fixed. Tested with both namespace and project. Also is working in other areas (global users, etc).
