### ISSUE TITLE
[Pipeline] Integrate with self-signed-certificate GitLab

### ISSUE THREAD

**Issue by modogo2000** [rancher/rancher#16136]
Hello,

I'm testing rancher 2.1 with gitlab . I have set an application on gitlab.

Now I try to configure the pipeline on rancher I put the application id , the secret , I'm using a private  gitlab the problem con from the certificat I'm using a self signed certificat. 

I have this error "Post https://gitlab.mlkain.org/oauth/token: x509: certificate signed by unknown authority" and nothing happen after that .

How can I fixed this .

**Comment by gitlawr** [comment]
To support integration with Gitlab instances that use self-signed certificates.
1. The certificate needs to be validated by rancher server, which can be done following the [instruction](https://rancher.com/docs/rancher/v2.x/en/admin-settings/custom-ca-root-certificate/)
2. Git client in user clusters need to validate the certificate. The `Clone` stage is not customizable at the moment so there's some todo work.
It would be nice if we can have options to skip ssl verify, install custom ca certificate for cloning, etc.

**Comment by modogo2000** [comment]
Do you have a work around ? or for the moment there is nothing to do for skip the ssl for git

**Comment by gitlawr** [comment]
@modogo2000 Sorry, there's no workaround at the moment, for testing you may try to connect gitlab using HTTP.

**Comment by Code2Life** [comment]
Another circumstance is that there could be a legacy jenkins which is used to build jar, tar, etc,. To smoothly migrate to kubernetes, using rancher pipeline to build docker image and auto deploy could be an awesome choice, but now first stage of pipeline is fixed with Clone, which limits the usage. 
It's impossible to tell project manager disposing their current CI and doing all the stuff on rancher~

**Comment by JohnDavidLarsen** [comment]
I can get past the first issue by launching rancher-server with bind mounted certs in /etc/rancher/ssl putting a cert.pem and key.pem and a cacerts.pem 
But when I go to authenticate the gitlab server sends back (after a popup that I click authorize on the gitlab server)  400 Bad Request Response.  400 No required SSL certificate was sent.  Meaning the gitlab server is expecting to be sent a client cert to HTTPS.   Can the Gitlab outgoing send client certs?

**Comment by Kralor-Guldan** [comment]
@gitlawr - Is there a timeline for when there will be customization options to add a ca-cert, private/public key combination to the cloning config?

**Comment by chux0519** [comment]
I also strongly hope that clone stage can use ssh instead of user name and token.

I'm using a private gitlab server, and admin only allow git clone via ssh.

See issue 16504

**Comment by arymkus** [comment]
Same here, but for GitHub Enterprise.

**Comment by cjellick** [comment]
@loganhz  @gitlawr I merged the rancher/rancher PR but I had some questions on the "support additional ca certs" PR

**Comment by rootwuj** [comment]
Verified with rancher/rancher:master 01/29

* Verified that Github/Gitlab/Bitbucket can be enabled with a self-signed certificate
* Verified that the Clone and Build work after configuring the CA certs
