### ISSUE TITLE
AD users now require domain prefix when logging in

### ISSUE THREAD

**Issue by mhoyer** [rancher/rancher#16131]
**Rancher versions:**
rancher/server or rancher/rancher: 2.1.0

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.11.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2 CE

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- HA Rancher, 4 nodes
- Internal DB
- Authentication via Active Directory

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
- Kubernetes

**Steps to Reproduce:**
- Install Rancher 2.0.8, configure AD authentication **with default domain enabled** and create one or more users
- Upgrade to Rancher 2.1.0 and create further more users

Previously created users don't need to log in with domain prefix. E.g. `m.hoyer`.

The upgrade to 2.1.0 now seems to drop the default domain which requires newly created users to **require entering the full domain credentials**. E.g. `INT\m.hoyer`. Thus, we now have a mixed set of users.

**Comment by tfiduccia** [comment]
Version - 2.0.8 upgraded to 2.1.0
I was unable to reproduce this behavior.

**Comment by deniseschannon** [comment]
@mhoyer If you're still having issues, please open a new ticket.
