### ISSUE TITLE
from 2.0.6 upgrade to 2.1.0,ingresss can't  add

### ISSUE THREAD

**Issue by jackcailj** [rancher/rancher#16144]
**Rancher versions:**
rancher/rancher:v2.1.0
ancher/rancher-agent:v2.1.0

from 2.0.6 upgrade to 2.1.0,ingresss can't  add

status:Initializing
nginx conf, the server node not create

how to fix?

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
