### ISSUE TITLE
Add note to UI to not use Root credentials for EKS

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#16157]
When supplying credentials for an EKS cluster, add a note to the UI telling the user not to use root credentials.  From the documentation:

https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html
> You must use IAM user credentials for this step, not root credentials. If you create your Amazon EKS cluster using root credentials, you cannot authenticate to the cluster.

**Comment by vincent99** [comment]
@nathan-jenan-rancher Is this still true?  That note is not present in their docs anymore.

**Comment by nathan-jenan-rancher** [comment]
I don't see it in the docs anymore either. We could try bringing up a cluster with root credentials or reaching out to AWS.

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/4/19)
Confirmed enhancement. There is now text in the Account Access section when trying to create an EKS cluster:
![image](https://user-images.githubusercontent.com/45179589/50708405-6ec6d380-1021-11e9-9d63-ec50cd758015.png)
"Paste in your AWS key pair here. Use only IAM access keys, using keys generated from the root user will make the cluster unreachable."
