### ISSUE TITLE
Helm Chart needs to support L7 TLS offloading for external termination

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#16155]
There's a logic error in the Helm Chart.  External TLS offloading should not required the installation of cert-manager, but does.  Because the options for ingress.tls.source are rancher,secret,letsencrypt.  There should be an option for none https://github.com/rancher/server-chart/blob/master/rancher/values.yaml#L37 as the other options invoke cert-manager.

**Comment by deniseschannon** [comment]
Cert-manager should only be deployed for when `ingress.tls.source` = rancher or letsEncrypt

**Comment by bmdepesa** [comment]
rancher/server-chart:master

`tls.ingress.source=none` - did not require cert-manager
`tls.ingress.source=secret` - did not require cert-manager
`tls.ingress.source=rancher` - did require cert-manager
`tls.ingress.source=letsEncyrypt` - did require cert-manager

**Comment by bmdepesa** [comment]
Used wrong repo when testing, so re-opening.

**Comment by jgreat** [comment]
`ingress.tls.source=none` is not a valid option. It might accept it, but there's no logic to support `none`.

**Comment by bmdepesa** [comment]
@jgreat I figured that out when looking at the correct chart and trying to use tls=external. Once we have that resolved I will re-test with the correct values.

**Comment by bmdepesa** [comment]
`tls=external`  & `ingress.tls.source=secret` did not require cert-manager
`ingress.tls.source=rancher` & `ingress.tls.source=letsEncrypt` did require cert-manager
