### ISSUE TITLE
Some values in annotations in load balancer view are showing up in with black background

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16159]
**Rancher versions:** 2.1.1 rc5

**Steps to Reproduce:**
1.  Create a load balancer
2.  View the load balancer
3.  Open the Labels & Annotations section

**Results:**  The system label is showing a black background instead of white
![image](https://user-images.githubusercontent.com/11514927/47035607-4d93cc80-d12f-11e8-84b1-07e14f60da40.png)

**Comment by tfiduccia** [comment]
Version: 2.2 master 1/2
Label view is now hanging.  Annotation and label section is missing
0:46575 Uncaught TypeError: Cannot read property 'workloads' of undefined

**Comment by n313893254** [comment]
@tfiduccia The error is rule target display, So I create a new issue https://github.com/rancher/rancher/issues/17575 and will fix it.

**Comment by tfiduccia** [comment]
Version - 2.2 master 2/28
Verified fixed
