### ISSUE TITLE
Project members cannot fetch their own repositories for pipelines

### ISSUE THREAD

**Issue by Maxwell1987** [rancher/rancher#16153]
I used a non-admin user, cluster owner and project owner. After adding the gitlab private repository, click "Authorize & Fetch Your Own Repositories" and I get an error
`Sourcecodecredentials.project.cattle.io "p-zx9dv-gitlab-root" is forbidden: User "u-j88t5" cannot get sourcecodecredentials.project.cattle.io in the namespace "u-j88t5"
`
But I tested it successfully with the user 'admin'.

**Comment by gitlawr** [comment]
The cause it users missing credential permissions the user namespace.

Workaround in v2.1.0:
1. Exec into rancher server container(or target to the management cluster in HA mode) and run
`$ kubectl edit globalrole user`
2. Find rules for `sourcecodecredentials` & `sourcecoderepositories` resources, change their apiGroups from `management.cattle.io` to `project.cattle.io`, and save.

**Comment by Maxwell1987** [comment]
>     1. kubectl edit globalrole user

root@9eea3ba74dda:/var/lib/rancher# kubectl edit globalrole user
error: unable to launch the editor "vi"

**Comment by gitlawr** [comment]
You can do a `apt install vim` in the container before editing, or patch the resource in some other ways.

**Comment by rootwuj** [comment]
Version -2.2 master 10/23
Verified fixed

**Comment by qingdi** [comment]
# kubectl edit globalrole user
error: the server doesn't have a resource type "globalrole"

how to fix it

**Comment by gitlawr** [comment]
@qingdi Are you using standalone or ha install, which kubernetes is your kubectl connecting to?

**Comment by gitlawr** [comment]
@qingdi Are you using standalone or ha install, which kubernetes is your kubectl connecting to?

**Comment by ebauman** [comment]
I was able to reproduce this once again using v2.2.2. 
I have a local user that has Project Owner and Cluster Owner roles.
When attempting to add their own repositories for pipelines, the following error is encountered:

sourcecodecredentials.project.cattle.io "p-2ckk4-github-ebauman" is forbidden: User "u-499kl" cannot get resource "sourcecodecredentials" in API group "project.cattle.io" in the namespace "u-499kl"

**Comment by ebauman** [comment]
Adding versioning information:
```
Rancher | v2.2.2
User Interface | v2.2.41
Helm | v2.10.0-rancher10
Machine | v0.15.0-rancher6-1
```

**Comment by Oats87** [comment]
Reopening issue. This does not appear to be fixed.

**Comment by gitlawr** [comment]
Synced with @ebauman it is reproducible in v2.2.2 with the following steps:
1. Add a `test` user with custom global permissions: `Manage Authentication`,`Manage Catalogs`
2. Add the user to be the owner of a provisioned cluster, and the owner of the Default project.
3. As the test user try to fetch repositories for pipelines in the Default project.

The cause is that RBAC rules for sourcecodecredential resources are only included in `user`(Standard) role, and it's user-scoped resource so it's not granted by prtb.

A workaround is to use `Standard User` global permission.

**Comment by rootwuj** [comment]
Tested with master-head from July 15

Test:
1. Add a `test` user with custom global permissions: `Manage Authentication`, `Manage Catalogs`
2. Add the user to be the owner of a provisioned cluster, and the owner of the Default project.
3. Use the `test` user to fetch repositories of the pipeline in the Default project.

Result:
The `test` user can fetch pipeline repositories.
