### ISSUE TITLE
Catalog apps naming messed up.

### ISSUE THREAD

**Issue by dabeck** [rancher/rancher#16152]
**Rancher versions:**
rancher/rancher:2.1.0

**Infrastructure Stack versions:**
kubernetes: 1.10 + 1.11

**Steps to Reproduce:**
Install an app from catalog e.g. `MariaDB` to a custom namespace e.g. `testnamespace`
Enter some answers (content doesn't matter) and click install.

**Results:**
The app is installed but named `testnamespace/mariadb-mariadb-0` I expected it to be named `testnamespace/mariadb` like I entered during the catalog app configuration.

**Comment by guangbochen** [comment]
it is the catalog app name that you have defined,  the `mariadb-mariadb-0` is generated by the [mariadb yaml file](https://github.com/rancher/charts/blob/master/charts/mariadb/latest/templates/master-statefulset.yaml#L4), this is regular naming standard in helm and if you want to keep your own name you can folk and edit the file accordingly.

**Comment by dabeck** [comment]
OK but why did it work as expected before Rancher 2.0.8

**Comment by guangbochen** [comment]
You can deploy the MariaDB app with version v3.0.3, this should be the one you are originally using, and it has no dependency on the rancher version.

**Comment by loganhz** [comment]
https://github.com/rancher/charts/blob/master/charts/mariadb/latest/templates/_helpers.tpl#L18

https://github.com/rancher/charts/blob/master/charts/mariadb/v3.0.3/templates/_helpers.tpl#L14

**Comment by dabeck** [comment]
Got you. Thanks
