### ISSUE TITLE
Does Rancher 2.0 already support containerd 1.1?

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#16150]
Hey together,

Just a quick question, which raised since the new ubuntu lts does not support and deliver the 17.03 version anymore, and kubernetes officially supports containerd 1.1, can rancher handle this already?

https://kubernetes.io/blog/2018/05/24/kubernetes-containerd-integration-goes-ga/

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/16246
