### ISSUE TITLE
addServiceLink: override link if new "ports" information is different

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1616]
When you call addServiceLink for the same service twice, with different port information, the new link doesn't override the old one.

**Comment by jwhitcraft** [comment]
Should the old link be overridden or just appended to?

**Comment by alena1108** [comment]
@jwhitcraft I think its better to override. Otherwise you won't be able to erase a particular port with addServiceLink. And even if we agreed to delegate ports erasing to removeServiceLink, it would be not clear when removeServiceLink is called to just erase all the ports, or remove the service link in general. Plus removeServiceLink name kind of implies that at the end the entire link with all its rules should be gone.

**Comment by jwhitcraft** [comment]
Sounds good, just figured I would ask :+1:

**Comment by kaos** [comment]
confirm resolved :)

**Comment by sangeethah** [comment]
Closing this issue as per @kaos findings.

**Comment by joshuakarjala** [comment]
What if I want to to have two different ports 443/80 pointing to the same service?

Right now I can do it through the UI - but not through the API

**Comment by alena1108** [comment]
@joshuakarjala 

> Right now I can do it through the UI - but not through the API

UI uses API, so anything that is doable via UI, is doable via API. UI uses setServiceLinks call to pass multiple service links, have you tried using the same call?

**Comment by joshuakarjala** [comment]
I'm using addServiceLink to set first

*.foo.bar.com 443 -> service_name:80

then 

foo.bar.com 443 -> service_name:80

Afterwards only foo.bar.com is on the load balancer.

**Comment by joshuakarjala** [comment]
@alena1108 also just tested with `setservicelinks`

get error

```
{"id":"715d71b9-43c0-4a7b-8ef0-3984a55d7e50","type":"error","links":{},"actions":{},"status":422,"code":"NotUnique","message":null,"detail":null,"fieldName":"serviceId and link name combination"}%
```

**Comment by joshuakarjala** [comment]
apparently `*.foo.bar.com` and `foo.bar.com` are seen as nonunique

**Comment by joshuakarjala** [comment]
ok founder out I should put all the different mapping in the same `ports:[]` array -- works this way
