### ISSUE TITLE
Optimize and move user controllers

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#16168]
A set of user controllers has been moved into the user cluster but a large number remain running in the management cluster. For the remaining controllers the following things need to be done:

- Determine if it can be optimized/refactored to not require management and pushed to the user cluster. 
- If it can not be pushed to the user cluster, optimize the caches being used. For example: Instead of listing all pods in the cluster list a subset with a selector (label, namespace)

Previous issue: https://github.com/rancher/rancher/issues/15100

**Comment by alena1108** [comment]
Revise and remove unnecessary listers as a part of this effort

**Comment by dramich** [comment]
All tests ran against 2.1.1

Running rancher through docker run has a memory leak, not present when running in HA mode
  - This could be fixed by the move to k3s

Connecting to the UI through multiple tabs and browsers doesn't seem to grow linearly, appears to be a one time cost to the server

Catalog:
  - Adding additional catalogs holds templates in memory - this is being addressed by Daishan
  - 20 MiB increase in memory usage after the sync completed. Unable to repro this with adding a new catalog and updating  one template then updating a file in all templates. Perhaps could be due to the size of the single template update but should be addressed by Daishans work to write templates to disk and not hold in memory.

Approx 27 MiB per cluster that is added to rancher server, this means no other running things in the cluster

Adding 100 basic workloads (nginx base image) adds ~15 MiB to the server

All workloads added were nginx with no other options set

First memory graph is rancher server running a single DO cluster with 100 workloads.
The bump in the base memory is when a 2nd catalog is added. The catalog added was a clone of the rancher catalog. This 2nd catalog added ~20MiB
6 hour resync spikes to 157 MiB

2nd memory graph is rancher server running 5 cluster and 100 workloads > 200 > 500 workloads. Always running 5 clusters.
230 MiB base > 246 MiB base > unstable - this is due to the host running rancher was not large enough 
The 6 hour resync spikes grow from 280 > 315 > 340 MiB

3rd memory graph is rancher server with pod lister's sync and start disabled, 5 clusters 500 workloads
5 cluster 500 workloads base ~300 MiB spikes to ~340 MiB. Note the large 6 hour spikes are no longer present, just the 2 hour resync

The 6 hour spikes seen in the first two runs were eliminated when running with the pod lister disabled. This indicates a pod handler is broken which needs to be investigated. It could be the handler itself or a call to anything else doing something bad on a 6 hour interval.

100
<img width="1015" alt="screen shot 2018-11-09 at 1 17 54 pm" src="https://user-images.githubusercontent.com/13897607/48286121-e7deeb80-e421-11e8-92c3-5f6eeb8770ff.png">


100 > 200 > 500 with 5 clusters
<img width="1027" alt="screen shot 2018-11-09 at 1 15 43 pm" src="https://user-images.githubusercontent.com/13897607/48286055-ae0de500-e421-11e8-9de0-fabd6f80da8d.png">

500 no pod lister
<img width="1447" alt="screen shot 2018-11-09 at 1 14 00 pm" src="https://user-images.githubusercontent.com/13897607/48285974-70a95780-e421-11e8-9026-2fe5f8f73162.png">

**Comment by dramich** [comment]
The tests were ran using a DO droplet - 16GB 6vcpus if you want to run 5 clusters 500 workloads. After setting up the droplet using RKE to get a cluster running, the following script was used to get rancher HA up and running. This is not an official script and is only being added here as a record of how the setup was created. 
Note that this script points to a specific rancher image and tag that was build locally and pushed to dockerhub. The hostname should your DO droplet IP with `.xip.io` appended, this should also be set as the server url.
Once rancher is running, install prometheus through the catalog apps into the local cluster and you can use the grafana dashboard to watch memory consumption. 

``` shell
#!/bin/bash
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh &&
chmod 700 get_helm.sh &&
./get_helm.sh

kubectl -n kube-system create serviceaccount tiller

kubectl create clusterrolebinding tiller \
  --clusterrole cluster-admin \
  --serviceaccount=kube-system:tiller

helm init --service-account tiller

#Verify deployment is up - deployment "tiller-deploy" successfully rolled out
kubectl -n kube-system  rollout status deploy/tiller-deploy

# Verify server and client are listed
helm version

helm repo add rancher-latest https://releases.rancher.com/server-charts/latest

helm install stable/cert-manager \
  --name cert-manager \
  --namespace kube-system

helm install rancher-latest/rancher \
  --name rancher \
  --namespace cattle-system \
  --set hostname=10.0.0.1.xip.io \
  --set replicas=1 \
  --set rancherImage=<your_docker_hub>/rancher \
  --set rancherImageTag=<image_tage>
```
