### ISSUE TITLE
Github auth: some places in code don't close the http response after reading it

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16165]
Based on code review, there are some places in 2.1 code that don't close the response properly. Revise the code and fix the issues.

From testing perspective, make sure our existing github auth tests pass.

**Comment by jiaqiluo** [comment]
Validated on rancher:master on 11/19

The following is major scenarios tested:
- Enable/Disable authentication
- Allow any valid user for server, cluster, and project level
- Allow members of Environments, plus Authorized Users and Organizations for server, cluster, and project level
- Restrict access to only Authorized Users and Organizations for server, cluster, and project level
- Local users for server, cluster, and project level
