### ISSUE TITLE
Add S3 for etcd backup/restore

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16163]
https://github.com/rancher/rke/issues/616

**Comment by alena1108** [comment]
Should in the end be tested in conjunction with https://github.com/rancher/rancher/issues/13688

**Comment by firasalkafri** [comment]
Take a look at this: https://github.com/Salalem/rancher-s3-backup

**Comment by soumyalj** [comment]
Tested with master, we have the ability to configure and create backups on S3. The feature to restore from a backup in S3 is functional.
