### ISSUE TITLE
Ingress stays in 'Initializing' status

### ISSUE THREAD

**Issue by eb10005** [rancher/rancher#16172]
**Rancher versions:**
rancher/rancher: 2.1.0

**Infrastructure Stack versions:**
healthcheck: None
ipsec: 
network-services: Canal
scheduler:
kubernetes (if applicable): 1.11.3

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 30
 Running: 27
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.67-rancher2
Operating System: RancherOS v1.4.1
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.42 GiB
Name: cl01-w1
ID: MELF:YYLU:7C4E:L5V4:HCPE:7FVX:R5N6:GYPQ:EWEM:ZMRL:LI3S:BPA5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarevsphere
Experimental: false
Insecure Registries:
 artifactory.mydomain.com
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.14.67-rancher2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
deploy nginx workload with TCP/80 on ClusterIP
deploy ingress to nginx Service with Specify a hostname to use

**Results:**
Ingress stays in 'Initializing' status

**Comment by loganhz** [comment]
@eb10005  Thanks for the report!

I guess it is the same issue with https://github.com/rancher/rancher/issues/16027?

**Comment by eb10005** [comment]
It looks similar, but I'm using the default ingress that gets deployed with Rancher/Kubernetes.  Is this a bug in Kubernetes 1.11.3?  Any way to fix/workaround?

**Comment by loganhz** [comment]
Have you tried this https://github.com/rancher/rancher/issues/16027#issuecomment-428310589?

**Comment by ybizeul** [comment]
Same here, ingress creation stuck `Initializing`

**Rancher versions:**
rancher/rancher: 2.1.1

```
{
"annotations": {
"field.cattle.io/ingressState": "{}"
},
"baseType": "ingress",
"created": "2018-10-21T20:30:55Z",
"createdTS": 1540153855000,
"creatorId": "user-prgtz",
"id": "monitoring:test",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"remove": "…/v3/project/c-5797b:p-ljjnf/ingresses/monitoring:test",
"self": "…/v3/project/c-5797b:p-ljjnf/ingresses/monitoring:test",
"update": "…/v3/project/c-5797b:p-ljjnf/ingresses/monitoring:test",
"yaml": "…/v3/project/c-5797b:p-ljjnf/ingresses/monitoring:test/yaml"
},
"name": "test",
"namespaceId": "monitoring",
"projectId": "c-5797b:p-ljjnf",
"rules": [
{
"host": "test.r2.lab",
"paths": {
"": {
"serviceId": null,
"targetPort": 3000,
"type": "/v3/project/schemas/httpIngressPath",
"workloadIds": [
"deployment:monitoring:grafana"
]
}
},
"type": "/v3/project/schemas/ingressRule"
}
],
"state": "initializing",
"status": {
"loadBalancer": {
"type": "/v3/project/schemas/loadBalancerStatus"
},
"type": "/v3/project/schemas/ingressStatus"
},
"transitioning": "no",
"transitioningMessage": "",
"type": "ingress",
"uuid": "36547f57-d570-11e8-9bf2-005056a4419f"
}
```

**Comment by ybizeul** [comment]
Try to disable nginx ingress and re-enable it. Did the trick for me.

**Comment by gaui** [comment]
Also experiencing this problem, Rancher v2.1.1

**Comment by singularo** [comment]
I had this issue. In my case, it was operator error, but documenting in case it helps others.
I was trying to run the cluster node on the same server as rancher itself , but the ingres can never start as port 80/443 is already in use by rancher.
I solved it by deploying the node on a different machine, but you could possibly solve it and run all on the same machine by using ports other than 80/443 when you launch the initial container.
`docker ps -a` to find the ingres container, then `docker logs xxxx` helped diagnose.

**Comment by alena1108** [comment]
@ybizeul @gaui @singularo what ingress controller do you have in the cluster?

**Comment by gaui** [comment]
@alena1108 traefik

**Comment by loganhz** [comment]
@gaui Can you try this https://github.com/rancher/rancher/issues/16027#issuecomment-429627605?

**Comment by ybizeul** [comment]
At first I just had nginx, in my case I just had to flip nginx controller off and on then all was good. 

Traefik is a different story and doesn’t look like it can be implemented by just running the helm chart. 

Did some tests with a friend yesterday and he thinks the way it works, an actual L4 load balancer is expected so I need to do some tests with MetalLB. 

What he couldn’t understand is why adding externalIP to traefik parameters ends up working (but ingress are still Initializing).

**Comment by ybizeul** [comment]
Edit your cluster then check "Disabled" on Nginx Ingress setting
Save, and enable it again.

Worked for me, let us know how that goes.

**Comment by docmattman** [comment]
@ybizeul, thanks.  I just noticed the following message on the cluster edit:

```
Note: Currently Amazon EKS will not create an ingress controller when launching a new cluster. If you need this functionality you will have to create an ingress controller manually after cluster creation.
```

Any idea what the best way to create a new ingress controller would be?

**Comment by alena1108** [comment]
We've added the logic for populating ingress state based on the status/Load balancer field with commit aa102c67526504553c7bed623665e04718167e1a.  As we can only truly say that the ingress is functional when controller sets `status/Load balancer` with the ip address/hostname. Nil field value would indicate that the controller failed to populate it by some reason. There is a known issue for traefik provider side that is supposedly got resolved in 1.7 version, but based on the last comments, still requires some extra config on traefik controller side:

containous/traefik#2173

Way to fetch k8s ingress address info:

Kubecl output - Address field is the one we are looking for
```
> kubectl get ingress
NAME         HOSTS    ADDRESS        PORTS     AGE
ingressfoo  foo.com  142.93.30.63   80        47s
```

The same field presented in `kubectl get ingress -o json` output:

```
"status": {
                "loadBalancer": {
                    "ingress": [
                        {
                            "ip": "142.93.30.63"
                        }
                    ]
                }
            }
```

**Comment by Zikovic** [comment]
Hello 

I Have the same probeme, i think the probleme is  in the nginx-ingress-controller, th logs show : 

-------------------------------------------------------------------------------
NGINX Ingress controller
Release: 0.16.2-rancher1
Build: d36d4cc
Repository: git@github.com:rancher/ingress-nginx.git
-------------------------------------------------------------------------------
F1103 10:51:39.712022 6 main.go:72] Port 80 is already in use. Please check the flag --http-port


Any idea ?

**Comment by superseb** [comment]
Port is either in use (check by running `netstat -plant | grep \:80`) or you are running into https://github.com/kubernetes/ingress-nginx/issues/2781

**Comment by jnk0** [comment]
In my case, neither the ingress-nginx namespace nor the workloads are created.

But workload rke-ingress-controller-delete-job spawns multiple pods on same node. Error message in log is always the same:

```
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
'-f rsrc.yaml'
'--filename=rsrc.json'
'<resource> <name>'
   '<resource>'
```

**Comment by jnk0** [comment]
Is there any other way to force Rancher to create Nginx Ingress workloads if disabling/enabling in cluster settings doesn't work?

**Comment by gaui** [comment]
@loganhz

I've set in traefik configuration:

```
--kubernetes.ingressendpoint.publishedservice=traefik/traefik
```

and I'm getting:

```
time="2018-11-15T19:33:38Z" level=debug msg="Skipping updating Ingress default/coffee-ingress due to service traefik/traefik having no status set"
```

and it's still stuck in "Initializing"

**Comment by obenziane2** [comment]
> @ybizeul, thanks. I don't see that setting in cluster edit. I just noticed the following message on the cluster edit:
> 
> ```
> Note: Currently Amazon EKS will not create an ingress controller when launching a new cluster. If you need this functionality you will have to create an ingress controller manually after cluster creation.
> ```
> Any idea what the best way to create a new ingress controller would be?

Having the same issue! i don't see that settings from Edit cluster . FYI: I'm running the EKS as cloud provider

**Comment by azbpa** [comment]
> In my case, neither the ingress-nginx namespace nor the workloads are created.
> 
> But workload rke-ingress-controller-delete-job spawns multiple pods on same node. Error message in log is always the same:
> 
> ```
> error: You must provide one or more resources by argument or filename.
> Example resource specifications include:
> '-f rsrc.yaml'
> '--filename=rsrc.json'
> '<resource> <name>'
>    '<resource>'
> ```

Getting the same issue on one custom cluster using rancher v2.1.3

**Comment by mshivanna** [comment]
Having same issue with traefik and metalLB

**Comment by mshivanna** [comment]
commented out the `kubernetes.io/ingress.class: traefik` and redeployed its now in active state.

**Comment by mshivanna** [comment]
rancher is addings its own annotations to ingress:
`  field.cattle.io/publicEndpoints: '[{"addresses":["X.X.X.X"],"port":80,"protocol":"HTTP","serviceName":"default:prometheus-server","ingressName":"default:prometheus-server","hostname":"prometheus.hello.int","path":"/","allNodes":true}]'`

**Comment by Pluto1010** [comment]
> Hello
> 
> I Have the same probeme, i think the probleme is in the nginx-ingress-controller, th logs show :
> 
> ```shell
> -------------------------------------------------------------------------------
> NGINX Ingress controller
> Release: 0.16.2-rancher1
> Build: d36d4cc
> Repository: git@github.com:rancher/ingress-nginx.git
> -------------------------------------------------------------------------------
> F1103 10:51:39.712022 6 main.go:72] Port 80 is already in use. Please check the flag --http-port
> ```
> 
> Any idea ?

I have the same message in my logs. Did you solve this somehow?

**Comment by Pluto1010** [comment]
Just found out it works if I move away my rancher/rancher container from port 80+443 to 8080+8443.
Its logical. Using a single node install rancher blocks the port 80 used for load balancer by itself. Had to recreate the whole "cluster" setup to do this.

This is somehow a little bit dumb :)

**Comment by helletheone** [comment]
Hey i have the same problem.
And recreating the ingress doesn't work.. 

Anybody any ideas?

**Comment by Vashiru** [comment]
> Try to disable nginx ingress and re-enable it. Did the trick for me.



> Hey i have the same problem.
> And recreating the ingress doesn't work..
> 
> Anybody any ideas?

So after a lot of digging, it turns out your storage driver might be the issue. I tried turning my Ingress NGINX off/on, only to have `nginx-ingress-controller` getting stuck at `F0407 22:51:52.909611 7 main.go:72] Port 80 is already in use. Please check the flag --http-port`.

I went searching for it, and down the rabbit hole I ran into: ttps://github.com/rancher/rancher/issues/16172. I happen to be using the aufs Storage Driver (since it's an old docker installation), which apparently is no longer supported. To check if you're running the aufs driver, run `docker info`.

As far as I know the only way to upgrade it is to uninstall docker completely, including removing images / volumes etc. since there's no way to switch them from one to the other. Though I'm not entirely sure of this. The aufs driver is no longer supported anyway, so this might be a good motivation to upgrade it.

**Comment by rajha-korithrien** [comment]
My run in with this problem was that I had the default Pod Security Policy set to "restricted" which denied the pods deployed by the ingress daemonset the ability to bind with the host ports 80/443. When I switched the Pod Security Policy for the "System" project to "unrestricted" everything deployed correctly.

**Comment by deniseschannon** [comment]
There are a lot of different issues of why people might have their ingress stuck. If you still have this issue and could create a new issue if you are still facing this issue with more details, that'd be great!

**Comment by maroshi** [comment]
Following the initial ["quickstart-deploy-workload-ingress"](https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/) .
On Centos 7.7 from scratch. Is permanent in Initializing state.
Docker-ce 19.03.6
Rancher image rancher/rancher latest for the date.

Listing my docker images:
-----------------------------
rancher/rancher-agent                             v2.3.5                  f29ece87a195        3 weeks ago         282MB
rancher/rancher                                   latest                  83fe4871cf67        3 weeks ago         670MB
rancher/hyperkube                                 v1.17.2-rancher1        00405a225ef9        4 weeks ago         1.48GB
rancher/rke-tools                                 v0.1.52                 6e421b8753a2        7 weeks ago         132MB
rancher/calico-node                               v3.10.2                 387b2425e2ee        2 months ago        192MB
rancher/calico-cni                                v3.10.2                 f37e2726b796        2 months ago        163MB
rancher/calico-pod2daemon-flexvol                 v3.10.2                 a29221a9eb60        2 months ago        9.78MB
rancher/coredns-coredns                           1.6.5                   70f311871ae1        3 months ago        41.6MB
rancher/coreos-etcd                               v3.4.3-rancher1         a0b920cf970d        3 months ago        83.6MB
rancher/metrics-server                            v0.3.6                  9dd718864ce6        4 months ago        39.9MB
rancher/cluster-proportional-autoscaler           1.7.1                   14afc47fd5af        5 months ago        40.1MB
rancher/nginx-ingress-controller                  nginx-0.25.1-rancher1   a80ffa0b898e        6 months ago        506MB
rancher/kube-api-auth                             v0.1.3                  2817cb463960        11 months ago       149MB
rancher/coreos-flannel                            v0.11.0                 ff281650a721        12 months ago       52.6MB
hello-world                                       latest                  fce289e99eb9        13 months ago       1.84kB
rancher/nginx-ingress-controller-defaultbackend   1.5-rancher1            b5af743e5984        16 months ago       5.13MB
rancher/hello-world                               latest                  cab3bc026f39        20 months ago       18.2MB
rancher/pause                                     3.1                     da86e6ba6ca1        2 years ago         742kB

**Comment by maroshi** [comment]
![image](https://user-images.githubusercontent.com/5566058/74932174-d688db00-53e9-11ea-89b7-18902f2f89c4.png)

**Comment by simvux** [comment]
If you're having this issue while following the Rancher getting started guide, and you're using Minikube for your cluster, make sure that you've enabled the ingress addon in minikube! Took longer to figure out than I'm willing to admit, but at least I got a lesson in Kubernetes debugging.
