### ISSUE TITLE
[cli] Answers file ignored when installing app from a catalogue as it's impossible to avoid interactive question dialogue

### ISSUE THREAD

**Issue by xaralis** [rancher/rancher#16177]
**Rancher versions:**
rancher/cli: 2.0.5
rancher/server or rancher/rancher: 2.1.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

macOS, Darwin 17.7.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
not applicable

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
not applicable

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
not applicable

**Steps to Reproduce:**

Install rancher catalogue chart and provide answers file using:

`rancher app install --answers myanswers.json appchart appname`

**Results:**

Instead of respecting the contents of answers file, rancher-cli starts interactive dialogue for question responses to fill out some missing pieces if not provided in answers file.

Looking at the code, when installing catalogue chart, it always runs interactive question dialog no matter what, see https://github.com/rancher/cli/blob/master/cmd/app.go#L565.

This *ruins all the scriptability* as there is no way to avoid it. I suggest turning off the interactive question mode when answer file is provided and fall back to defaults where applicable. Or at least provide a toggle for that mode.

**Comment by loganhz** [comment]
Please validate it with rancher cli v2.2.0-rc3

**Comment by jiaqiluo** [comment]
Following the same steps described in the ticket. The bug is reproduced on CLI 2.0.5 , and the bug fix is validated on CLI v2.2.0-rc5

Result: there is no prompt when adding `--no-prompt` option and even the answer file does not contain everything.
