### ISSUE TITLE
Custom CertManager issuer name in server-chart

### ISSUE THREAD

**Issue by patst** [rancher/rancher#16178]
My kubernetes cluster has a ClusterIssuer configured (see CertManager: http://docs.cert-manager.io/en/latest/reference/clusterissuers.html ). The name is `ca-cluster-issuer` and I would like to use this issuer for my rancher ingress . I am setting up rancher with the rancher helm chart.

To make this work I need the following annotation in my ingress:

`certmanager.k8s.io/issuer: ca-cluster-issuer`

Unfortunately I see no way to make this happen in the current helm chart.
The template looks like this at the moment:

```
{{- if ne .Values.ingress.tls.source "secret" }}
    certmanager.k8s.io/issuer: {{ template "rancher.fullname" . }}
{{- end }}
```

I would propose something like this:

```
  {{- if eq .Values.ingress.tls.source "clusterIssuer" }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.tls.issuerName }}
  {{- else if eq .Values.ingress.tls.source "issuer" }}
    certmanager.k8s.io/issuer: {{ .Values.ingress.tls.issuerName }}
  {{- else if ne .Values.ingress.tls.source "secret" }}
    certmanager.k8s.io/issuer: {{ template "rancher.fullname" . }}
  {{- end }}

```
The issuerName can be set with `ingress.tls.issuerName`

**Comment by patst** [comment]
I created a PR for the changes in the docs  too.

Would be great to see those two PRs merged.

**Comment by jgreat** [comment]
You can achieve what you are looking for by setting ingress.tls.source=secret and using the new ingress.extraAnnotations option from rancher/server-chart#43 to set any certmanager.k8s.io annotation you would like.

Something like:

```
helm install ./rancher --name rancher --namespace cattle-system \
  --set hostname=rancher.my.org --set ingress.tls.source=secret \
  --set ingress.extraAnnotations.'certmanager\.k8s\.io/cluster-issuer'=ca-key-pair
```

**Comment by deniseschannon** [comment]
@patst let me know if you still have issues with the workaround that @jgreat has provided. I'll close this issue for now.
