### ISSUE TITLE
Rancher with private registry stuck on "Waiting to register with Kubernetes"

### ISSUE THREAD

**Issue by jonathanlang** [rancher/rancher#16173]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent: 2.0.8

**Infrastructure Stack versions:**
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 5
Running: 4
Paused: 0
Stopped: 1
Images: 3
Server Version: 1.13.1
Storage Driver: overlay2
Backing Filesystem: xfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 5eda6f6fd0c2884c2c8e78a6e7119e8d0ecedb77 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 15.5 GiB
Name: //server2//
ID: AXHI:DFMA:V3XM:RQSM:2UFZ:RRUC:YIEV:MCZS:CCRJ:XD5B:EGZ7:NOUK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Experimental: false
Insecure Registries:
//server1//:5000
127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), docker.io (secure)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
air gapped, single node rancher installation - no certificates - with private registry

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
I have an air-gapped single-node installation, with a private registry (no certificates, entered in docker on all nodes as an insecure-registry). Registry is running on //server1// on Port 5000, Rancher 2.0.8 is running on //server1// as well. 
I have added the registry in Rancher settings, so the command to add a new node contains the relevant parameter as described in https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-installation/config-rancher-for-private-reg/

**Results:**
When I try adding //server2// the node shows up but remains in state "Waiting to register with Kubernetes".

**Comment by superseb** [comment]
Please provide the logs of the `rancher/rancher` container as it will show the provisioning steps, and the `rancher/rancher-agent` container logging from the host to be added. Also the output from `docker ps -a` from the host added.

**Comment by jonathanlang** [comment]
We worked around it. Seems that this is an issue with the new docker version.

**Comment by cocobear** [comment]
I got the same error, when I add second and third node into cluster, and finally figure out it is because master node's firewall is not disabled, it can been see at `rke-tools` container's log :

> 2019/10/09 07:14:50 [error] 14#14: *14715 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "192.168.0.12:6443", bytes from/to client:0/0, bytes from/to upstream:0/0

after disabled firewall on master node, everything is ok.
