### ISSUE TITLE
Cannot start rancher (stable) infrastructure stacks on Centos 7.5 with docker 18.06.1-ce

### ISSUE THREAD

**Issue by nick-manasys** [rancher/rancher#16170]
Docker version: 18.06.1-ce, build e68fc7a

Operating system and kernel: CentOS Linux release 7.5.1804 (Core), 3.10.0-862.14.4.el7.x86_64
Type of host: Bare-metal

Steps to Reproduce:
Install centos CentOS Linux release 7.5.1804 (Core)
Run sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:stable

Results:
After waiting for over an hour some infrastructure stacks have not started up.

Interestingly turning off the firewall helps. Then only the IPSec infrastructure stack stays in bad state with a message "Failed to acquire lock [service ...]"

-------- 8< --------
\# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s31f6
  sources: 
  services: ssh dhcpv6-client
  ports: 5901/tcp 5900/tcp 10000/tcp 500/udp 4500/udp 80/tcp 443/tcp 4789/udp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
-------- 8< --------

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
