### ISSUE TITLE
Pipeline crash causing "boot loop" on rancher/rancher:latest when pushing to ECR

### ISSUE THREAD

**Issue by AdamSutch** [rancher/rancher#16187]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Setup rancher/rancher:latest on 1 EC2 T2-Medium on RancherOS 1.4.1
Make a cluster using the same server type.
Authenticate to github.
Add a private repo with the following .rancher-pipline.yml file
```
stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: company/app:latest
      pushRemote: true
      registry: xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com
timeout: 120
```
Build the pipeline manually
Got the following error after the image is made and about to be pushed
```
panic: interface conversion: interface {} is nil, not string

goroutine 126387 [running]:
github.com/rancher/rancher/pkg/pipeline/engine/jenkins.(*Engine).prepareRegistryCredential(0xc0145b9970, 0xc004ff78c0, 0xc0079a39e0, 0x2c, 0x6d54a1, 0xc00114cc50)
	/go/src/github.com/rancher/rancher/pkg/pipeline/engine/jenkins/engine.go:187 +0xb52
github.com/rancher/rancher/pkg/pipeline/engine/jenkins.(*Engine).preparePipeline(0xc0145b9970, 0xc004ff78c0, 0x807dba0, 0xc017b18230)
	/go/src/github.com/rancher/rancher/pkg/pipeline/engine/jenkins/engine.go:158 +0x1ab
github.com/rancher/rancher/pkg/pipeline/engine/jenkins.(*Engine).RunPipelineExecution(0xc0145b9970, 0xc004ff78c0, 0xf87e01, 0x0)
	/go/src/github.com/rancher/rancher/pkg/pipeline/engine/jenkins/engine.go:137 +0x2bd
github.com/rancher/rancher/pkg/controllers/user/pipeline/controller/pipelineexecution.(*ExecutionStateSyncer).checkAndRun(0xc014882000, 0xc004e678c0)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/pipeline/controller/pipelineexecution/statesyncer.go:101 +0x1c1
github.com/rancher/rancher/pkg/controllers/user/pipeline/controller/pipelineexecution.(*ExecutionStateSyncer).syncState(0xc014882000)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/pipeline/controller/pipelineexecution/statesyncer.go:61 +0x31f
github.com/rancher/rancher/pkg/controllers/user/pipeline/controller/pipelineexecution.(*ExecutionStateSyncer).sync(0xc014882000, 0x80c1920, 0xc014161300, 0x12a05f200)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/pipeline/controller/pipelineexecution/statesyncer.go:37 +0x7f
created by github.com/rancher/rancher/pkg/controllers/user/pipeline/controller/pipelineexecution.Register
	/go/src/github.com/rancher/rancher/pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go:143 +0xd92
```
This is followed by the rancher/rancher:latet container restarting over and over.

**Result:**
The built image isn't pushed to the AWS ECR registry and the rancher/rancher:latest container gets suck in a restart loop with the above error over and over.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Single install of `rancher/rancher:latest` (v2.1.0)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
AWS EC2 using RancherOS 1.4.1 AMI
T2-Medium

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker (use `docker info`):

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.67-rancher2
Operating System: RancherOS v1.4.1
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853 GiB
Name: ip-10-200-0-171.ec2.internal
ID: 4QT5:N3V3:XRI3:OZAO:I6IU:EK2W:NO4J:7GZQ:X3YV:MLGD:QI3T:E6AB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by gitlawr** [comment]
It happens when a registry secret with empty username/password is used.
To help recover rancher container, remove either the registry secret or the pipeline execution resource.
1. For HA mode, it can be done by running `kubectl delete pipelineexecutions.project.cattle.io -n <projectid>`.
2. For standalone setup, it is a bit tricky because the embedded kubernetes starts up by rancher. you can try the following command:
```
docker start <rancher-container-id> && docker exec <rancher-container-id> bash -c "while ! kubectl get cs; do echo waiting apiserver;done; RET=$(kubectl get pipelineexecutions.project.cattle.io -o=custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,STATE:.status.executionState --all-namespaces|grep Waiting);echo $RET | read v1 v2 v3;kubectl delete pipelineexecutions.project.cattle.io $v2 -n $v1;"
```

**Comment by gitlawr** [comment]
Here's a workaround before getting the fix:
1. Go to project - registries
2. Click View API action of your ECR registry item
3. Click `Edit` button.
4. In `registries` fields, find the key which is your registry address and put `{"username":"","password":""}` to the value.
5. Click `Show request` then `Send request`

These steps help to bypass the issue now.

I'm not familiar with ECR(and I'll investigate more later) but I doubt if it works without credentials set in the registry. Please be aware that the publish step runs in dind mode so configurations of docker daemon on the host will not affect it. By passing envvars, there are more options to custom the dind daemon and the build, as mentioned in the docs.

**Comment by gitlawr** [comment]
ECR credentials are handled by kubelet: https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry.
To have desired registry credential for publish image step, you can try some dedicated tools for credential refreshment, example: https://github.com/rancher/rancher/issues/14907#issuecomment-418864667

**Comment by rootwuj** [comment]
Version -2.2 master 10/24
Verified fixed
