### ISSUE TITLE
Cant setup RKE node due to iptable error

### ISSUE THREAD

**Issue by KuroObi** [rancher/rancher#16182]
**Rancher versions:**
rancher/rancher: v2.1.0

**Docker version: 17.03.02-ce**

**Operating system and kernel: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux)**

**iptables version: v1.6.0**

**Type/provider of hosts:bare-metal**

**Setup details: single node rancher**

**Environment Template: RKE**

**Steps to Reproduce:**
Trying to setup a new RKE node with etcd, control plane and worker roles

**Results:**
```
This cluster is currently Updating.

Failed to start [rke-etcd-port-listener] container on host [xxx.xxx.xxx.xxx]: Error response from daemon: driver failed programming external connectivity on endpoint rke-etcd-port-listener (xxxxxxxxx): (iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 1337 -j ACCEPT: iptables: No chain/target/match by that name. (exit status 1))
```

After executing the generated docker command the above message is displayed and the deployment stops.
For testing i disabled all my custom iptables rules, restarted the docker service and than started the deployment.
After the the deployment stopped the chain in question (docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 1337 -j ACCEPT) is generated and visible in my iptables.
```
Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:1337
```

Am i doing something wrong or is this a bug?

**Comment by superseb** [comment]
The `DOCKER` chain should be present after installing/restarting Docker. Usually there is something `iptables` related overwriting/removing those rules. Not sure what custom iptables rules means exactly, but it's most likely something on the system is messing up iptables.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by coder-michaelwu** [comment]
我也面临了同样的问题。

**Comment by ZhiqinYang** [comment]
> 我也面临了同样的问题。
> 我仅仅是将rancher中已添加的集群删除，同时删除了master节点上的container，清理了遗留的iptables规则，然后再此节点添加回来就出现这样的问题了。
> @loganhz

我也遇到相同的问题了， 请问你是如何解决的？

**Comment by niceKou** [comment]
我也遇到了同样的问题，重启docker也不好使啊，有处理方案吗
