### ISSUE TITLE
Cannot move a namespace to project None

### ISSUE THREAD

**Issue by chanjarster** [rancher/rancher#16193]
**What kind of request is this (question/bug/enhancement/feature request):**

Cannot move a namespace to project None

**Steps to reproduce (least amount of steps as possible):**

Choose a namespace, click Move, choose None

**Result:**

```
cluster.management.cattle.io "" not found
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

v2.1.0

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 30
 Running: 25
 Paused: 0
 Stopped: 5
Images: 22
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 226
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-137-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: rancher-4
ID: TDKR:JLNG:P6NI:2RII:STZS:BHQA:LIG7:2HMJ:BSC2:J7V6:KZY7:6DDV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by jiaqiluo** [comment]
Fix validated on mater 12/21, single installation

Steps:
- add a project p1
- go to p1, add namespace ns1 and ns2 to p1
- move ns1 to None
- try to deploy a workload and check the exisiting namespace list

Result:
1. the namespace is moved to anotehr section which is out of the current project 
1. the namespace is gone from the list of existing namespace

Note:
Although the bug in this ticket is fixed, it revesals antoher bug which is tracked here: https://github.com/rancher/rancher/issues/17219
