### ISSUE TITLE
rancher installation --set noProxy via helm chart results in error on comma separated list

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#16195]
**What kind of request is this (question/bug/enhancement/feature request):**

BUG

**Steps to reproduce (least amount of steps as possible):**

Install Rancher per your docs.
Use this helm command instead:

`helm install rancher-stable/rancher --name rancher --namespace cattle-system  --set hostname=somehost --set proxy=http://someproxy --set noProxy="localhost,127.0.0.1,10.0.0.0/8"`

**Result:**

    Error: failed parsing --set data: key "1" has no value (cannot end with ,)

**Other details that may be helpful:**

I'm reporting this for my client. The part of this command that ends up in a failure is the noProxy part. Not sure if this is a helm problem. or a rancher problem. But reporting this, since you documented this, as it should be working: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#http-proxy

**Environment information**
- Rancher version (`rancher/rancher:v2.1.0`):
- Installation option (single install/HA): HA (helm)

**Cluster information**
- Cluster type (Imported): Nutanix
- Machine type (private cloud/VM) and specifications (CPU/memory - not relevant):
- Kubernetes version (use `kubectl version`): - not relevant
- helm version - latest available (v2.11.0)

**Comment by superseb** [comment]
It's probably the escaping comma issue, can you try escaping the commas:

```
--set noProxy="localhost\,127.0.0.1\,10.0.0.0/8"
```

I'll submit a fix for the docs

**Comment by superseb** [comment]
Fixed in https://github.com/rancher/docs/pull/914
