### ISSUE TITLE
Errors relating to renewing fqdn in rancher-server logs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16199]
Rancher server version - v2.1.1-rc6
Had few DO clusters with few workloads and ingress deployed in them.

Following errors seen in logs:

```
2018/10/17 23:52:27 [ERROR] renew fqdn [] to server [https://api.lb.rancher.cloud/v1] error
```

**Comment by alena1108** [comment]
duplicate of https://github.com/rancher/rancher/issues/16194
