### ISSUE TITLE
Backport: Upgrading workload unable to pull new image from custom repository

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16202]
backport issue for https://github.com/rancher/rancher/issues/15725

**Comment by soumyalj** [comment]
Reproduced the issue in v2.1.1
Tested with v2.1.2-rc1. Steps below:
1. Add a custom registry in Rancher UI with scope available to a single namespace
2. Deploy a workload in the same namespace with image testuser/abc:v1
3. Verify the imagePullSecrets field exists in the yaml file for the workload
4. Edit the image version in the workload to testuser/abc:v2
5. Click Upgrade

The upgraded workload image was active and had the imagePullSecrets field in the yaml file. 
This was tested with both custom and quay private registries.
