### ISSUE TITLE
Deploy catalog app got "Name" contains an invalid character: .

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#16207]
**Environment information**
- Rancher master 10/19

**Steps to reproduce**
1. go to project
2. deploy a memcached app from library catalog
3. Use all default settings and click `Launch`

**Result**
Unable to deploy the app and got the error in the UI
![image](https://user-images.githubusercontent.com/5697937/47196672-45889680-d394-11e8-9add-bb0a84012db1.png)

**Comment by tfiduccia** [comment]
Version - 2.2 master
Verified fixed
