### ISSUE TITLE
Can not add Catalog behind a corporate proxy

### ISSUE THREAD

**Issue by mristok** [rancher/rancher#16200]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Add Helm Catalog to Rancher
Name: artifactory-helm-remote
URL: https://artifactory.domain.local/artifactory/helm-remote/
Attempt to deploy app from catalog

**Result:**
The catalog is successfully added to Rancher, and all catalog items are display with looking at the Catalog Apps page. However, when selecting an App to deploy, the chart is not fully populates and the UI spins trying to load all of the details. Looking at the cattle logs, it appears that the chart is loaded but 

[ERROR] CatalogController artifactory-helm-remote [catalog] failed with : failed to sync templates. Resetting commit. Multiple error occurred: [Get https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.16.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.16.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.16.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.15.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.14.8.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.14.7.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.14.6.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.14.5.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.14.4.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.14.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.14.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.14.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.13.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.13.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.12.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.12.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.11.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.10.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.10.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.9.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.8.0.tgz: Forbidden Get https://kubernetes-ch
arts.storage.googleapis.com/kibana-0.7.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.6.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.5.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.4.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.4.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.3.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.2.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.2.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.2.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.2.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.1.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kibana-0.1.0.tgz: Forbidden Get https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ee-0.2.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ee-0.2.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ee-0.2.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ee-0.1.10.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ee-0.1.9.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ee-0.1.8.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ee-0.1.7.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ee-0.1.6.tgz: Forbidden Get https://bitnami.com/assets/stacks/redmine/img/redmine-stack-220x234.png: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-5.2.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-5.2.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-5.1.0.tgz: Forbidden Get https://
kubernetes-charts.storage.googleapis.com/redmine-5.0.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-5.0.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-5.0.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-4.1.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-4.0.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-4.0.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-4.0.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-4.0.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-3.0.4.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-3.0.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-3.0.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-3.0.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-3.0.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-2.0.6.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-2.0.5.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-2.0.4.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-2.0.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-2.0.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-2.0.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-2.0.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.2.7.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.2.6.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.2.5.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.2.4.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.2.3.tgz: Forbidden Get https:
//kubernetes-charts.storage.googleapis.com/redmine-1.2.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.2.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.2.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.1.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.1.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.0.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-1.0.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.4.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.4.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.4.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.4.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.11.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.10.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.9.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.8.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.7.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.6.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.5.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.4.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/redmine-0.3.0.tgz: Forbidden Get https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.2.2.tgz: Forbidden Get
https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.2.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.2.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.12.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.11.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.10.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.9.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.8.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.7.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.6.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.5.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.4.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/gitlab-ce-0.1.0.tgz: Forbidden Get https://raw.githubusercontent.com/JFrogDev/artifactory-dcos/master/images/jfrog_med.png: Forbidden Get https://kubernetes-charts.storage.googleapis.com/mission-control-0.4.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/mission-control-0.4.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/mission-control-0.4.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/mission-control-0.3.0.tgz: Forbidden Get https://avatars1.githubusercontent.com/u/9976052?s=64: Forbidden Get https://kubernetes-charts.storage.googleapis.com/weave-scope-0.9.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/weave-scope-0.9.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/weave-scope-0.9.1.tgz: Forbidde
n Get https://raw.githubusercontent.com/JanusGraph/janusgraph/master/janusgraph.png: Forbidden Get https://kubernetes-charts.storage.googleapis.com/janusgraph-0.2.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/janusgraph-0.1.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/janusgraph-0.1.0.tgz: Forbidden Get https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.4.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.4.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.3.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.2.7.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.2.6.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.2.5.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.2.4.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.2.3.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.2.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.2.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.2.0.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.1.2.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.1.1.tgz: Forbidden Get https://kubernetes-charts.storage.googleapis.com/kong-0.1.0.tgz: Forbidden]
[INFO] Updating catalog artifactory-helm-remote

**Other details that may be helpful:**
semi-related issue: https://github.com/rancher/rancher/issues/13371

Due to the behavior of Artifactory, the tgz are cached in Artifactory but because of the URL in the index.yaml file, helm is redirected to an internet repo and without proxy access cannot be downloaded.

** Workaround**
Allow host to access internet based chart repos via corporate proxy directly. Then the charts are properly downloaded and made available.

**Environment information**
- Rancher version: rancher/rancher:v2.0.8
- Installation option: HA

**Cluster information**
- Cluster type: Imported (RKE)
- Machine type (CPU/memory): VMware (2/8)
- Kubernetes version (use `kubectl version`): 1.10.3

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19695
