### ISSUE TITLE
backport for 400 null error when accessing /meta/proxy when logged in as an user from authentication provider (except the user that enabled it) 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16203]
Backport for issue https://github.com/rancher/rancher/issues/13920

**Comment by sangeethah** [comment]
Tested with v2.1.2-rc2.

Had Azure AD auth enabled with site access set to "Allow any valid user".

Log in as a user who is part of ~1000 groups.

Try to create EC2 node template.
This fails with "400 null" error .

```
Request URL: https://<ip>/meta/proxy/ec2.us-east-2.amazonaws.com/
Request Method: POST
Status Code: 400 Bad Request
Remote Address: <ip>:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by superseb** [comment]
Commit for this is in branch `release/v2.1` but not in tag `v2.1.2-rc2`

**Comment by sangeethah** [comment]
Tested with v2.1.2-rc3.

Had Azure AD auth enabled with site access set to "Allow any valid user".

Log in as a user who is part of ~1000 groups.

Try to create EC2 node template.
Node template creation succeeded.

Also user is able to access  clusters and project have access to one of the 1000 groups the user belongs to.
