### ISSUE TITLE
Pipeline / Build / Error authenticating: exit status 1

### ISSUE THREAD

**Issue by lakano** [rancher/rancher#16218]
**What kind of request is this (question/bug/enhancement/feature request):**

question or possible bug 

**Steps to reproduce (least amount of steps as possible):**
Install a fresh cluster, with RKE
Install a fresh Rancher 2.1.1 ( 2.1.0 have the same problem )

**Result:**

If I add a private repository ( docker-registry from Catalog or from Helm-incubator ), or even if I try to use the DockerHub private repository, each time the Pipeline fail on the build part, about an « Error authenticating »:

> 11:05:34 [pipeline_p-bvz7d-5] Running shell script
> 11:05:36 + /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
> 11:05:36 + /usr/local/bin/dockerd -g /var/lib/docker
> 11:05:55 EXITCODE   0time="2018-10-21T11:05:52Z" level=fatal msg="Error authenticating: exit status 1"
> 

**Other details that may be helpful:**
I never used Rancher before, so may be I've missed something. But after 3 days of multiples tests, and search in the issues, I've found there is multiple bugs around private registry. One bug have been fixed in 2.1.1, so I've tried to remove everything (reformat all my cluster disks) and re-install the 2.1.1, but I get the same issue. I've found a ticket about registry that should be fixed in 2.1.2, I'm not known if it's really related.  
Is it a bug, do I need to wait the version 2.1.2 ? 

**Environment information**
- Rancher version: 2.1.1
- Installation option (single install/HA): single on a HA cluster v1.12 installed with RKE 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom, Imported 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal, 11 nodes 32Go RAM / 8vCPU
- Kubernetes version (use `kubectl version`): 1.12.0

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 28
 Running: 18
 Paused: 0
 Stopped: 10
Images: 12
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-34-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.3GiB
Name: cp1.readact.page
ID: RJJU:SN4M:6G2H:HL2D:UL6S:UF5Y:WOFD:YJEL:TBT5:RYEF:U7DV:5IZI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
( installed from get.docker.com, channel stable, 18.06.x seems to be the new references for k8s on v1.12.x )

**Comment by loganhz** [comment]
Thanks for the report.

@lakano Can you provide the detailed reproduce steps? 

It will be great if you can provide the `.rancher-pipeline.yml` file

**Comment by gitlawr** [comment]
@lakano Basically when the docker login fails you will see this error. We've found users hitting the same error message due to different causes, like dns issue/improper configs of registry.
To diagnose you can enable debug mode of dockerd to get more information, e.g.:
```
stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myproject
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_DEBUG: "true"  
```

**Comment by lakano** [comment]
Ok I'll check that ASAP. Currently, we doesn't need to push outside, so if we uncheck "push" option, the build is correctly completed.

**Comment by gitlawr** [comment]
@iwin4aids You can give additional envvars to tweak the build image step:
```
stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myproject
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"  
```
You can check more in the docs(clicking on `By Yaml` tab of `Build and Publish Images`) https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/configurations/#build-publish-image

**Comment by lakano** [comment]
Hi,
I can't continue to debug my initial issue, because my Rancher crash in loop on each build. Each time I need to restart the rancher docker, to reconfigure logging, recreate all secrets, configure Gitlab.com and retry. This bug have been fixed but will be fixed in 2.2 (planned firstly for 2.1.2 and moved to 2.2 ... )
Do you have an idea of how many days I need to wait for the 2.2 version please? To known if we keep trying to uses Rancher or not. 
Thanks

**Comment by loganhz** [comment]
@lakano which issue causes your Rancher crash in loop?

**Comment by lakano** [comment]
@loganhz The issue #16187

**Comment by loganhz** [comment]
@lakano 
You are using ECR on AWS with IAM and you don't need to input the username and password for the registry. But it will cause your rancher server crash in loop. Is it correct?

Can you try this workaround https://github.com/rancher/rancher/issues/16187#issuecomment-431038011 , please?

**Comment by lakano** [comment]
Not exactly, I'm not using AWS, but docker-registry with empty username/password, and this crash in loop when I try to push on the registry.
Yes I've tried the workaround, and this doesn't crash anymore, but there is surely another problem, because after this workaround, I have another error;

> 08:59:19 Get http://127.0.0.1:5000/v2/: dial tcp 127.0.0.1:5000: getsockopt: connection refused
> 08:59:19 time="2018-10-28T08:59:19Z" level=fatal msg="exit status 1"

I don't known why there is a /v2/ in the URL. When I've installed docker-registry, I've set a NodePort on port 5000. So the URL is good until the /v2/ ... but why there is a /v2/ I don't known :-/

**Comment by gitlawr** [comment]
@lakano You see a /v2/ because it is the docker distribution API specification.
The publish step does not use docker socket on the host, so it does not work in this way...
You are not able to access the registry in a pod using the loopback address. You need to use nodeIP:nodePort to access the registry for your case.

**Comment by lakano** [comment]
Ok, thanks @gitlawr 
But, I've just tried with the DNS name, this is now a different response:

> 15:13:59 Get https://docker-registry-docker-registry.default:5000/v2/: http: server gave HTTP response to HTTPS client

But can't see anything else because there is again a crash loop of rancher... even with the workaround used previously.

**Comment by lakano** [comment]
Thanks @gitlawr 
Now, I've removed the manually installed Helm chart docker-registry, and now I use the auto-generated docker-registry when the Rancher pipeline is triggered.
In my .ranche-pipeline.yaml I have set:

> registry: docker-registry.p-fs5p6.pipeline


and in my deployment.yaml, my docker image is prefixed by the same hostname.
Now, there is a auth problem:

> 
> 16:17:58 Successfully built e679aa5e3887
> 16:17:58 Successfully tagged 00000000:latest
> 16:17:58 + /usr/local/bin/docker tag 00000000 docker-registry.p-fs5p6-pipeline/readact/upload:latest
> 16:17:58 + /usr/local/bin/docker push docker-registry.p-fs5p6-pipeline/readact/upload:latest
> 16:17:58 The push refers to repository [docker-registry.p-fs5p6-pipeline/readact/upload]
> 16:17:58 d0f08e0aa672: Preparing
> 16:17:58 30a0582be6f3: Preparing
> 16:17:58 5ba1448b4861: Preparing
> 16:17:58 2ee25a145bbc: Preparing
> 16:17:58 47de5ef441f1: Preparing
> 16:17:58 2839211f95e7: Preparing
> 16:17:58 89099b8fbac6: Preparing
> 16:17:58 cb18274b2dd1: Preparing
> 16:17:58 df64d3292fd6: Preparing
> 16:17:58 89099b8fbac6: Waiting
> 16:17:58 2839211f95e7: Waiting
> 16:17:58 cb18274b2dd1: Waiting
> 16:17:58 df64d3292fd6: Waiting
> 16:17:58 no basic auth credentials
> 16:17:58 time="2018-10-28T16:17:58Z" level=fatal msg="exit status 1"

This seems to be related to issues #15554 / #13339 , but the workaround to add imagePullSecrets in my deployment.yaml doesn't seems to help. Or may be I don't refer to the good secret, i've used the secret named "p-fs5p6-pipelinedockerregistrydefault".

If you have any idea to help, this will be really appreciated!

**Comment by gitlawr** [comment]
If you use the auto-generated docker registry, 
1. remove `pushRemote` & `registry` field for publish step
2. add imagePullSecrets with `pipeline-docker-registry` secret name in deployment

**Comment by lakano** [comment]
This works! Thanks a lot !

**Comment by lakano** [comment]
@gitlawr Please, could you tell me if I need to put a special host in the field template.spec.containers.image ? I've got ErrImagePull errors currently.

**Comment by iDube** [comment]
This works for me. https://github.com/rancher/rancher/issues/16624#issuecomment-440213383

**Comment by pamarquez** [comment]
I'm having the very same problem even the pipeline I'm trying to run is from Rancher examples.
https://github.com/rancher/pipeline-example-go

stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/rancher
        ln -s `pwd` /go/src/github.com/rancher/pipeline-example-go
        cd /go/src/github.com/rancher/pipeline-example-go
        go build -o bin/hello-server
        go test -cover
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml

The error I get is "Got FAILED status in 'Publish' stage"

22:02:58 [pipeline_p-7g8b6-10] Running shell script
22:03:01 + /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
22:03:01 + /usr/local/bin/dockerd -g /var/lib/docker
22:03:07 EXITCODE   0time="2019-06-23T22:03:06Z" level=fatal msg="Error authenticating: exit status 1"

**Comment by usernamecantbeXXX** [comment]
add up max-concurrent-uploads in /etc/docker/daemon.json

**Comment by easonjim** [comment]
everybody，how to fix this bug?
