### ISSUE TITLE
Can't import airgapped copy of default Library Catalog. (2.x)

### ISSUE THREAD

**Issue by JohnDavidLarsen** [rancher/rancher#16211]
Using Rancher 2.1
Library catalog at 
https://git.rancher.io/charts does not work in airgapped environment. If I try to point to a local repo copy of it, it looks for index.yaml instead as currently only Helm Charts are supported. Yet natively rancher seems to support a git version of its own Library? 
Is there instructions or means of a simple clone of the Library, or does it all have to be converted into helm charts?

**Comment by superseb** [comment]
What does `git ls-remote <your_git_repo_URL>` return?

**Comment by JohnDavidLarsen** [comment]
Ok, figured it all out. I guess this is more of a documentation issue. I though I was proxying correctly but I wasn't, my internal git is https with client cert.. Solution was to bind in a /etc/gitconfig file which contained
[http]
  sslCert = /run/secrets/certs/server.crt
  sslKey = /run/secrets/certs/server.key
  sslCaInfo = /run/secrets/certs/ca.crt

And obviously binding in those certs as well.
I can add my local github through the interface now.

**Comment by superseb** [comment]
This is covered in https://github.com/rancher/rancher/issues/14766
