### ISSUE TITLE
Node Template DigitalOcean

### ISSUE THREAD

**Issue by moisesdelacruz** [rancher/rancher#16217]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
![captura de pantalla_2018-10-21_00-29-11](https://user-images.githubusercontent.com/11895442/47265453-abd4fc80-d4ed-11e8-922d-4d2850fdf3bd.png)

|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`nodes.node-templates`|

**Comment by loganhz** [comment]
Thanks for the report.
Duplicated with https://github.com/rancher/rancher/issues/11280
It will be fixed in 2.2
