### ISSUE TITLE
Unable to clone a cloned secret

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#16219]
**Environment information**
- Rancher version: v2.1.0 or master 10/21

**Steps to reproduce (least amount of steps as possible):**
1. Go to the default project Create a secret named `s1` in default namespace.
2. Clone secret `s1` to a new secret named `s2`.
3. Clone secret `s2` and call it `s3`.

**Result:**

Got a validation error when saving `s3`.
![image](https://user-images.githubusercontent.com/5697937/47268437-91e5f900-d583-11e8-99ca-48e52394b2da.png)

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed
