### ISSUE TITLE
Sometimes local cluster in HA setup takes about 10 mts to get to "Active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16213]
Rancher server version - v2.0.8.

Steps to reproduce the problem:
Deploy a 3 node HA setup.
Even after rancher server is up and running , its take about 10 minutes for local cluster to get to "Active" state.
Until then the local cluster is in "Provisioning" state with message - "waiting for server-url setting to be set" 

[halogs.txt](https://github.com/rancher/rancher/files/2497423/halogs.txt)

**Comment by janeczku** [comment]
Reproduced the behaviour on v2.1.1 with steps per above using LE certificate from cert-manager.

**Comment by zhangyelong** [comment]
Same problem by using a Private CA Signed Certificate, I don't think waiting for 10 minutes works, even    not for 10 hours ...

**Comment by Melvin-mlp** [comment]
Reproduced with "rancher/rancher v2.1.1" using LE certificate with "quay.io/jetstack/cert-manager-controller v0.5.2" on AWS debian-stretch instances behind a network load balancer.

After spending 10 minutes to wait, the message _Provisioning state with message - waiting for server-url setting to be set_ has gone without modifying anything.

**Comment by cjellick** [comment]
from @ibuildthecloud regarding a solution:
```
there is nothing that watches the server-url setting.  so when you set it there's no trigger to retry.  the clusterprovisioner needs to watch Setting and enqueue all clusters if server-url != ""
this is only a problem with "local" cluster
all other clusters should naturally have server-url before you ever imported them
maybe a simpler solution is that we don't add local cluster until server-url is set.  so just error in a loop until we find server-url set
``

**Comment by erikwilson** [comment]
This is reproducible with a single node install by waiting before setting the server url in the UI. 

We are currently using an `ExponentialFailureRateLimiter` with a max backoff of 1000 seconds, one solution might be to reduce that max to a smaller value, like 30 seconds.

**Comment by xlight** [comment]
Same problem when install rancher with self signed CA  in HA mode .
Solved by Edit the "local" cluster , and click save .  
Only try once, I don't know this will help or not.

**Comment by slamkalukas** [comment]
> Same problem when install rancher with self signed CA in HA mode .
> Solved by Edit the "local" cluster , and click save .
> Only try once, I don't know this will help or not.

Hello xlight, i got this very same error. What do you mean by edit the "local" cluster and click save? thanks for answer.

**Comment by derWeihnachtsmann** [comment]
> Hello xlight, i got this very same error. What do you mean by edit the "local" cluster and click save? thanks for answer.

Click on your "local" cluster and then click "edit".

![grafik](https://user-images.githubusercontent.com/16196578/58878474-a79fcd00-86d3-11e9-8faa-bf2ed8795fdf.png)

without doing anything click "save".

Result:  Cluster is active.

**Comment by rodcloutier** [comment]
Same problem when install rancher with self signed CA in HA mode.
Solved with the Edit->Save workaround.

**Comment by divyangjp** [comment]
> > Hello xlight, i got this very same error. What do you mean by edit the "local" cluster and click save? thanks for answer.
> 
> Click on your "local" cluster and then click "edit".
> 
> ![grafik](https://user-images.githubusercontent.com/16196578/58878474-a79fcd00-86d3-11e9-8faa-bf2ed8795fdf.png)
> 
> without doing anything click "save".
> 
> Result: Cluster is active.

That's weird but works !!!

**Comment by Aisuko** [comment]
Same issue when installing rancher with [rancher-generated-certificates](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#rancher-generated-certificates) in HA mode by using rke. rancher version v2.2.5

**Comment by j-lorenzo** [comment]
> > Hello xlight, i got this very same error. What do you mean by edit the "local" cluster and click save? thanks for answer.
> 
> Click on your "local" cluster and then click "edit".
> 
> ![grafik](https://user-images.githubusercontent.com/16196578/58878474-a79fcd00-86d3-11e9-8faa-bf2ed8795fdf.png)
> 
> without doing anything click "save".
> 
> Result: Cluster is active.

Thank you :heart_eyes:

**Comment by leodotcloud** [comment]
I ran into the same issue today twice.

Running a HA setup with v2.2.8 using the install steps from docs.

```
2019/09/18 01:33:10 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2019/09/18 01:33:10 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2019/09/18 01:33:10 [INFO] Adding peer wss://10.42.2.6/v3/connect, 10.42.2.6
2019/09/18 01:33:14 [INFO] Handling backend connection request [10.42.2.6]
2019/09/18 01:33:22 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2019/09/18 01:33:25 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2019/09/18 01:33:53 [INFO] Catalog-cache removed 2 entries from disk
2019/09/18 01:33:54 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2019/09/18 01:36:02 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
```

During the time of the problem, I see that the `cattle-cluster-agent` and `cattle-node-agent` are not deployed in `cattle-system` namespace.

Just waiting for few minutes, the issue resolved itself.

**Comment by spali** [comment]
> During the time of the problem, I see that the `cattle-cluster-agent` and `cattle-node-agent` are not deployed in `cattle-system` namespace.
> 
> Just waiting for few minutes, the issue resolved itself.

I can confirm that.

> Click on your "local" cluster and then click "edit".
> 
> ![grafik](https://user-images.githubusercontent.com/16196578/58878474-a79fcd00-86d3-11e9-8faa-bf2ed8795fdf.png)
> 
> without doing anything click "save".
> 
> Result: Cluster is active.

And the workaround mentioned above to edit and save the cluster just forces these to pods to get deployed.

**Comment by drajen** [comment]
> Click on your "local" cluster and then click "edit".
> 
> ![grafik](https://user-images.githubusercontent.com/16196578/58878474-a79fcd00-86d3-11e9-8faa-bf2ed8795fdf.png)
> 
> without doing anything click "save".
> 
> Result: Cluster is active.

This worked for me too. Using self-signed certs with cert-manager and Rancher 2.3.3 fresh everything today.

**Comment by robinbraemer** [comment]
My workaround was to recreate the rancher pod.

**Comment by drajen** [comment]
Why is this still an issue with 2.3.5?

**Comment by maxmengtr** [comment]
Seems you have the only chance to set the url with the inital page. I have no idea if there is any other way to feed it.

**Comment by maxmengtor** [comment]
Seems always starting
2020/03/02 00:13:49 [INFO] Starting cluster controllers for local
2020/03/02 00:13:49 [INFO] Starting cluster agent for local [owner=true]

**Comment by jochemvankessel** [comment]
Why is this issue still Open? Should not be that hard to fix this right?
It is a very annoying bug if you try to automate the whole rancher setup.
Big thumbs up for the one who can fix this!

**Comment by shivdeepnv** [comment]
> Same problem when install rancher with self signed CA in HA mode .
> Solved by Edit the "local" cluster , and click save .
> Only try once, I don't know this will help or not.



> I ran into the same issue today, twice.
> 
> Running a HA setup with v2.2.8 using the install steps from docs.
> 
> ```
> 2019/09/18 01:33:10 [INFO] kontainerdriver amazonelasticcontainerservice stopped
> 2019/09/18 01:33:10 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
> 2019/09/18 01:33:10 [INFO] Adding peer wss://10.42.2.6/v3/connect, 10.42.2.6
> 2019/09/18 01:33:14 [INFO] Handling backend connection request [10.42.2.6]
> 2019/09/18 01:33:22 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
> 2019/09/18 01:33:25 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
> 2019/09/18 01:33:53 [INFO] Catalog-cache removed 2 entries from disk
> 2019/09/18 01:33:54 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
> 2019/09/18 01:36:02 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
> ```
> 
> During the time of the problem, I see that the `cattle-cluster-agent` and `cattle-node-agent` are not deployed in `cattle-system` namespace.
> 
> Just waiting for few minutes, the issue resolved itself.


_+_+_+_+_+_


Even after waiting for a long time, the `cattle-cluster-agent` and `cattle-node-agent` were not deployed on `cattle-system`. 

Whereas, one of the Rancher pods keeps complaining about

```
2020/06/03 17:31:22 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 17:31:23 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 17:31:24 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set

```

**Comment by shivdeepnv** [comment]
I waited for sometime (1 hour) as suggested in this thread. but I see the following error on only one of the rancher pods.

```
2020/06/03 18:04:13 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:14 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:15 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:16 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:16 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:39511
2020/06/03 18:04:16 [INFO] kontainerdriver googlekubernetesengine stopped
2020/06/03 18:04:16 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating
2020/06/03 18:04:16 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:46879
2020/06/03 18:04:16 [INFO] kontainerdriver azurekubernetesservice stopped
2020/06/03 18:04:16 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating
2020/06/03 18:04:16 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:44363
2020/06/03 18:04:16 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2020/06/03 18:04:16 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2020/06/03 18:04:17 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:18 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:19 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:20 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:21 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:22 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:23 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:24 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:25 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:26 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/06/03 18:04:27 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
```

kubectl get pods -n cattle-system

```
NAME                          READY   STATUS    RESTARTS   AGE
rancher-01-5948d5db55-2w88k   1/1     Running   0          5m23s
rancher-01-5948d5db55-ltvwk   1/1     Running   0          5m23s
rancher-01-5948d5db55-9zsrc   1/1     Running   0          5m23s
```
Additional details -

sudo k3s -v

```
k3s version v1.18.3+k3s1 (96653e8d)
```
sudo kubectl version

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3+k3s1", GitCommit:"96653e8d86b74a1f73eadf09d4edc44778c2f8dd", GitTreeState:"clean", BuildDate:"2020-06-01T16:47:11Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```
K3s HA with LB

```
helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher-k3s-lorem-ipsum.elb.us-east-9.amazonaws.com
```

K3s Config File

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ASDLASJDLAKDJASJDLADLAJLDALD$
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: ASDASDSADSADASDSD
    username: admin
```

Tried deleting the deployment and re-created it. Got the same error again.

Is the K3s config looking right? There was an instruction to replace localhost (127.0.0.1) with the LB, when I made that change, I could not even reach the cluster using Kubectl.

**Comment by marcelbeeker** [comment]
I have the same problem too. I'm running Kubernetes v.1.17 with a single Master and a single Node as VM on my Windows10 Host. 

ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set

Rancher Pods are running ok.
![image](https://user-images.githubusercontent.com/18581814/84080062-e00b7280-a9db-11ea-8b2e-9cbdcd95417c.png)

 kubectl -n cattle-system describe pod

![image](https://user-images.githubusercontent.com/18581814/84080222-206af080-a9dc-11ea-9eb5-db87549fafec.png)

Liveness probe failed and Readiness probe failed. I think this was caused my problem. But the rest of my pods are running ok.

**Comment by imriss** [comment]
Deleting the `rancher` pod with the error message `waiting for server-url setting to be set` in the logs resolved the issue after the pod came back up without the error message.

**Comment by memelet** [comment]
I am seeing with rancher 2.5 on k3s 1.19. No workaround works yet.

**Comment by zaggash** [comment]
You can set or change the server-url setting with:

`kubectl patch settings.management.cattle.io server-url -p '{"value":"https://DNS_NAME"}' --type=merge`

But you should not have to.
