### ISSUE TITLE
AWS Security Group ELB Limit

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rancher#16212]
**What kind of request is this (question/bug/enhancement/feature request):** Feature Request

**Steps to reproduce (least amount of steps as possible):**

 Create > 50 inbound rules per security group using rancher v1.6.21 ec2 

**Result:**

Limit is reached, not able to create more rules.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/server v1.6.21
- Installation option (single install/HA): HA

**Comment by massimo-cannavo** [comment]
https://github.com/kubernetes/kubernetes/issues/26670

**Comment by jamiebuxxx** [comment]
I'm running into this issue and trying to find a way to enable this in within Rancher 1.6. I know that is now apart of the Kubernetes cloud provider, but I'm not sure how this can be set using the Rancher templates. Any leads would be helpful.

**Comment by alena1108** [comment]
https://github.com/kubernetes/kops/blob/release-1.9/docs/cluster_spec.md#cloudconfig

**Comment by jamiebuxxx** [comment]
@alena1108 I was looking at the cloudconfig for kops. I guess I could add the cloudconfig file on my host and update controller-manager pod to mount the config file and point to the proper location. 

But if I update K8s in Rancher, that will go away. I found a deployment under the Rancher catalog files. 

https://github.com/rancher/rancher-catalog/blob/v1.6-development/infra-templates/k8s/53/docker-compose.yml.tpl#L340-L355

I figure this would be the best place to add this.

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.26-rc1`

**Comment by superseb** [comment]
Current situation:
* Create k8s environment with aws cloudprovider
* Create `LoadBalancer` service, wait for ELB to provision
* Check instances security group and see the security group for ELB added (if you create >50, you will hit the limit)

To validate:
* Create/upgrade k8s environment with aws cloud provider and the following in `Kubernetes cloud provider config file content`:

```
[global]
DisableSecurityGroupIngress = true
```
* Create `LoadBalancer` service, wait for ELB to provision
* See security group not being added to instances security group (eliminating hitting any limit)

**Comment by soumyalj** [comment]
Reproduced the issue in v1.6.25 . After creating a loadbalancer in the K8s setup, ELB's security group was added to the instance's security group.

Created k8s environment with AWS cloud provider by adding the below in `Kubernetes cloud provider config` file content
```
[global]
DisableSecurityGroupIngress = true
```
Created load balancer service and observed that the ELB's security group was not added to the instance's security group
