### ISSUE TITLE
Incorrect ordering of acl enabled backends configured in haproxy causes LB to send traffic to incorrect backend.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1621]
Server version - V0.29.0-rc1
Steps to reproduce the problem:
Create LB service with 2 listener ports - 80 and 81 with following targets:
<img width="983" alt="screen shot 2015-07-22 at 1 14 55 pm" src="https://cloud.githubusercontent.com/assets/4266958/8837724/a86d9f98-307c-11e5-96ba-64d4b31c15b8.png">

The order in which the acls are configured in haproxy , causes the traffic to be not redirected to the correct backend:

<img width="816" alt="screen shot 2015-07-22 at 2 21 01 pm" src="https://cloud.githubusercontent.com/assets/4266958/8837765/eda94bfc-307c-11e5-83a8-e22dd8a8dbd5.png">

Traffic for the following url gets redirected to instances of new1 instead of being redirected to new4:
wget --header="host: abc" http://104.154.66.248:80/service1.html

**Comment by alena1108** [comment]
will fix by ordering hostname+path, single hostname, single path, default

**Comment by sangeethah** [comment]
Server version - V0.29.0-rc2

Tested with LB having targets with similar configuration from the bug and ordering of acls programmed in haproxy is in the order hostname+path, single hostname, single path, default.
