### ISSUE TITLE
Rancher 2 Show HPA in UI

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#16214]
We deploy HPAs along with our workloads but there is no way to view them in the UI currently.

UI for https://github.com/rancher/rancher/issues/19084

**Comment by jira-sync-svc** [comment]
➤ Kelly Griffin commented:

This is a feature we need for rancher UI as we can’t see it today.

Numerous customers are/have been asking for this feature.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/7/19)

HPA has been tested via the UI HPA Test Plan. We can confirm basic functionality currently and I didn't identify any critical issues.
Testing will continue in this area as we finalize our test plans but basic functionality is validated.
