### ISSUE TITLE
node_selector in cluster config can't take truethy input in annotation value

### ISSUE THREAD

**Issue by damongant** [rancher/rancher#16210]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Create a cluster with ingress controller "nginx" and set a `node_selector` with a "truethy" value (true, yes) as a string.

**Result:**

The ingress job fails because the node selector was marshalled to a boolean, not a string. (The deployment is rejected by apiserver.)

**Other details that may be helpful:**

None.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.0
- Installation option (single install/HA): Single, HTTPS port remapped

**Comment by loganhz** [comment]
Thanks for your report.
Current workaround is not using `true` as the value for node selector
