### ISSUE TITLE
Support kubectl impersonate (--as)

### ISSUE THREAD

**Issue by de13** [rancher/rancher#16221]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

```
$ kubectl create ns dev
$ kubectl create rolebinding joe-view --clusterrole view --user joe --namespace dev
$ kubectl auth can-i get pods --namespace dev --as joe
yes
$ kubectl auth can-i create deployments --namespace dev --as joe
yes
```

**Result:**

Looks like it's wide open. I was expecting:

```
$ kubectl auth can-i create deployments --namespace dev --as joe
no
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

rancher/rancher:v2.1.0

- Installation option (single install/HA):

single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):

On AWS EC2

- Machine type (cloud/VM/metal) and specifications (CPU/memory):

EC2

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

Managed by rancher/ubuntu

**Comment by superseb** [comment]
It's returning yes, but can you actually create it? Sounds like a side effect from https://github.com/rancher/rancher/issues/14997

**Comment by de13** [comment]
Sounds like it isn't:

```
$ kubectl run nginx --image nginx --replicas=3 --as=joe
kubectl run --generator=deployment/apps.v1beta1 is DEPRECATED and will be removed in a future version. Use kubectl create instead.
deployment.apps/nginx created
$ kubectl get po --as=joe
NAME                     READY   STATUS    RESTARTS   AGE
nginx-64f497f8fd-4tjqp   1/1     Running   0          41s
nginx-64f497f8fd-gfwfp   1/1     Running   0          41s
nginx-64f497f8fd-rfp9z   1/1     Running   0          41s
```

**Comment by dramich** [comment]
@de13 RBAC isn't broken and we aren't allowing anything you shouldn't be able to do. The request is being sent through rancher server which proxies requests to the user cluster. As part of this rancher server uses the token the request was made with (an admin token most likely) and sets the impersonation header on the request based off your token. Rancher server is ignoring `--as` in all requests it proxies. Ignoring the `--as` flag is a bug which will be addressed.

**Comment by de13** [comment]
@dramich I know that Rancher does not authorize everything, and that RBAC is well implemented for user management in projects. I just had that strange point that I wanted to point out so you can measure the impact. The answer suits me perfectly.

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/26
HA install

* Reproduced original issue
* Created master install
* Attempt again:
```
kubectl create namespace dev
kubectl create rolebinding test-view --clusterrole view --user testuser --namespace dev
kubectl auth can-i create deployments --namespace dev --as testuser
no - no RBAC policy matched
```

**Comment by seboudry** [comment]
Hi!

Is kubectl impersonate working for now?
Didn't managed to have a correct response using `--as`, always have `yes`.

Furthermore, I not sure what user name to use on `--as` parameter.
Is this the `name` of a `users.management.cattle.io` or `metadata.uid` or any `principalIds`?

Thx for your help
