### ISSUE TITLE
Location not Displayed for Exoscale Node Template in Note Template List

### ISSUE THREAD

**Issue by Remigius2011** [rancher/rancher#16226]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

* create an exoscale node template
* display the `Node Templates`

**Result:**

The location is displayed as Ùnknown`(see screenshot below)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher 2.1.1 single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Exoscale
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud
- Kubernetes version (use `kubectl version`):
v1.11.3-rancher1-1

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

![image](https://user-images.githubusercontent.com/2393965/47296545-d79dd280-d612-11e8-8557-4fa6b0e76409.png)

**Comment by vincent99** [comment]
https://github.com/rancher/ui/blob/master/lib/shared/addon/mixins/node-driver.js#L25

**Comment by tfiduccia** [comment]
Version - 2.2 master 10/31

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed.
