### ISSUE TITLE
Complete Rancher setup using env vars to allow full automation

### ISSUE THREAD

**Issue by amioranza** [rancher/rancher#16225]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature

**Steps to reproduce (least amount of steps as possible):**
When running Rancher for the very first time, via compose or helm, have the options to set the initial admin password and the endpoint URL via environment vars to allow automation tools to deploy Rancher. If it is possible get the initial api keys too, to make a complete automate initial cycle like:

Start Rancher (compose/helm) > Generate initial API keys > Setup authorization > Create/import new cluster.

**Result:**
Have a complete automation of Rancher deployment and cluster import.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.0.8
- Installation option (single install/HA): Both methods

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/15477 and https://github.com/rancher/rancher/issues/13271

There is nothing that can't be automated, and having an initial password set is hard to do securely without additional software that provides a secure source for that password.
