### ISSUE TITLE
Feature Request - Enhancements to Log Viewer in the UI

### ISSUE THREAD

**Issue by emm-dee** [rancher/rancher#16229]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Overview**
Users would like to be able to easily select & export logs from the Rancher built in log viewer for pods. 
Select CTRL-A or CMD-A selects more than just the logs in the log viewer. 

Choosing CTRL-A or CMD-A selects components of the entire page, not just the log contents. There is no way to export the logs for download. 

**Other details that may be helpful:**
Either a button that "selects all" or allowing keyboard shortcuts would suffice. 
A button to "export" logs to a file for download would also suffice. 

**Environment information**
`rancher/rancher` - UI specific
`v2.1`
`v2.x`

**Cluster information**
Any - UI related. 

**To Open Log Viewer:** 
![pod_logs](https://user-images.githubusercontent.com/43972480/47305727-43664800-d5df-11e8-8697-cb60fb5d878e.png)

**Log Viewer View (no select all or export function):** 
![pod_log_viewer](https://user-images.githubusercontent.com/43972480/47305733-45c8a200-d5df-11e8-9a24-bb440c31abac.png)

**CMD-A to select all selects more than just log contents:** 
![cmd-a](https://user-images.githubusercontent.com/43972480/47305894-bd96cc80-d5df-11e8-81d7-41db4c60434d.png)

**Comment by deniseschannon** [comment]
@emm-dee We are going to investigate into adding the "Copy to Clipboard" button.

**Comment by westlywright** [comment]
I'll be adding a `Download Logs` button that will grab the plain text content, minus the timestamp we prepend, to the container log modal.

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed
