### ISSUE TITLE
Deleted services showing up in dropdown of target services in Load Balancer

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1623]
v0.29.0-rc1

Steps to Reproduce:
1. Create a Service/LB Service
2. Delete the Service. The service will no longer be visible in the stack.
3. Immediately, add a LB Service.

Result: In the target service dropdown, the deleted service will still be an option.

Expected Result: If the UI is no longer showing the service in the stack, the dropdown on the load balancer should not show the target service of the deleted service.

Note: When linking services, the service drop down shows the state of the service, so it's clear that the service is already removed. That is a potential option to make it more clear.

**Comment by vincent99** [comment]
Also same control in new alias service and regular service "service links".  And reduced it from `num_stacks+1` API calls to 0-2, depending on what else was already loaded.

**Comment by tfiduccia** [comment]
Version - master UI 3/18
Verified fixed
