### ISSUE TITLE
Cluster provisioning stuck in "provisioning" for Azure cluster with cloud provider.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16234]
Rancher server version - Build from master

Steps to reproduce the problem:
 Create a cluster with Azure with cloud provider enabled:

Cluster provisioning gets stuck in "provisioning" state with following error message:
```
[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check http://localhost:10252/healthz for service [kube-controller-manager] on host [13.64.101.0]: Get http://localhost:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused, log: ++ cut -d / -f 9]
```
All nodes are stuck in "Registering" state with message - "Waiting to register with Kubernetes"

**Comment by david-maumenee** [comment]
Same issue with Rancher v2.1.1
Nodes config : 1 master (etcd+control plane) and 2 workers

**Comment by moelsayed** [comment]
@sangeethah Did the cluster recover after this or stuck there for ever ?

**Comment by david-maumenee** [comment]
In ma case (Rancher 2.1.1), it stuck for ever too.

**Comment by cjellick** [comment]
@sangeethah was this a once-off bug or does it repro consistently?

**Comment by cjellick** [comment]
Ive marked this as low priority assuming this does not repro consistently. If you tell me it does, I will bump up priority
