### ISSUE TITLE
Helm upgrade: Error: This command needs 2 arguments: release name, chart path

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#16233]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Bug

**Steps to reproduce (least amount of steps as possible):**
1. Attempt to run:
`helm upgrade rancher-stable/rancher --version 2018.10.2 --set hostname=dvl-rancher.scm.jnj.com --set ingress.tls.source=secret --set privateCA=true`

**Result:**
`Error: This command needs 2 arguments: release name, chart path`

**Other details that may be helpful:**
```
#-> helm search rancher
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
rancher-stable/rancher  2018.10.2       v2.1.1          Install Rancher Server to manage Kubernetes clusters acro...
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Attempting to upgrade from 2.1.0 to 2.1.1
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
Can you try the command as described in the docs here: https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha-server-upgrade-helm/#upgrade-rancher

```
helm upgrade rancher rancher-<CHART_REPO>/rancher <rest_of_parameters>
```

**Comment by nxf5025** [comment]
If I drop the version as shown in the doc I still get the same thing:

```
helm upgrade rancher-stable/rancher --set hostname=dvl-rancher.scm.jnj.com --set ingress.tls.source=secret --set privateCA=true

Error: This command needs 2 arguments: release name, chart path
```

**Comment by nxf5025** [comment]
Ah missing the first rancher. Thanks!
