### ISSUE TITLE
Shibboleth provider now (1.6.22) implements strict check against host registration url

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16232]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/regression

**Summary of problem:**
When using a multi-tiered DNS configuration with a high-level domain for tenants and a subdomain used for the agent registration url.
 
Using the current hierarchyo:
domain.example.com -> intermediate.domain.example.com -> blue/green DNS -> Rancher host
 
When attempting to login on the domain.example.com domain we receive the following error:level=error msg="Cannot redirect to anything other than Rancher host"
The login is stopped at the url: https://intermediate.domain.example.com/v1-auth/saml/login?redirectBackBase=https%3A%2F%2Fdomain.example.com&redirectBackPath=%2Flogin%2Fshibboleth-auth%2F during the SSO login.
 
We need to be able to leverage white lists or something.

**Comment by sangeethah** [comment]
Scenarios to be validated:
Have 2 fqdn entries - fqdn1, fqdn2 and fqdn3 point to same Rancher server instance.
Access rancher server using fqdn1 , set "host registration url" as fqdn1 and enabled Shibboleth provider.
Log out as rancher server.
Log in to rancher server using fqdn2 as a user who has access to rancher server (site access). Log in should fail.
Log in to rancher server using fqdn3 as a user who has access to rancher server (site access). Log in should fail.
Add fqdn2 to whitelist.
Log in to rancher server using fqdn2 as a user who has access to rancher server (site access). Log in should succeed.
Log in to rancher server using fqdn3 as a user who has access to rancher server (site access). Log in should continue to fail.
Add fqdn3 to whitelist.
Log in to rancher server using fqdn2 as a user who has access to rancher server (site access). Log in should succeed.
Log in to rancher server using fqdn3 as a user who has access to rancher server (site access). Log in should succeed.
Remove fqdn2 from whitelist.
Log in to rancher server using fqdn2 as a user who has access to rancher server (site access). Log in should fail.
Log in to rancher server using fqdn3 as a user who has access to rancher server (site access). Log in should continue to succeed.

**Comment by sangeethah** [comment]
Tested the following upgrade scenario:

Fresh install of 1.6.14.
Have 2 fqdn entries - fqdn1, fqdn2 point to same Rancher server instance.
Access rancher server using fqdn1 , set "host registration url" as fqdn1 and enable Shibboleth provider.
Log out as rancher server.
Log in to rancher server using fqdn2 as a user who has access to rancher server (site access). 
Log in succeed .

Upgrade to rancher server version - v1.6.23
Log in to rancher server using fqdn1 as a user who has access to rancher server (site access). 
Log in succeed .
Log in to rancher server using fqdn2  as a user who has access to rancher server (site access). 
Log in fails. When user click on "Authenticate with Shibboleth" , user is presented with an empty page. 

Following error seen in rancher server logs:
time="2018-11-12T23:56:04Z" level=error msg="Cannot redirect to anything other than Rancher host” 


Upgrade to rancher server version - v1.6.24-rc3
Log in to rancher server using fqdn1 as a user who has access to rancher server (site access). 
Log in succeed .
Log in to rancher server using fqdn2  as a user who has access to rancher server (site access). 
Log in fails. When user click on "Authenticate with Shibboleth" , user is presented with error page having - ```"message":"Cannot redirect to anything other than whitelisted domains and rancher api host","status":"403","type":"error```

Add fqdn2  to whitelist using settings - ```api.auth.shibboleth.redirect.whitelist```
Log in to rancher server using fqdn2  as a user who has access to rancher server (site access). 
Log in succeeds now as expected.

**Comment by garyellis** [comment]
Validated **v1.6.24-rc4** is working as expected using the DNS configuration hierarchy described originally:
```
CNAME1 ("endpoint for users") to CNAME2 ("intermediate" endpoint)
CNAME2 ("intermediate" endpoint) to CNAME3 (green)
CNAME3 (green) to rancher server A record
CNAME4 (blue) to rancher server A record
Registration URL: CNAME2 ("intermediate" endpoint)
```
Summary of validation:
1. Login to rancher server as local admin using CNAME2, set registration URL to CNAME2, enable Shibboleth auth provider and logout.
2. Login to rancher server as authorized user using CNAME2 is successful.
3. Login to rancher server as authorized user using CNAME3 **fails as expected** with error message: `time="2018-11-13T22:53:46Z" level=error msg="Cannot redirect to anything other than whitelisted domains and rancher api host"`
4. Login to rancher server as authorized admin user using CNAME2, and set Advanced Setting:`api.auth.shibboleth.redirect.whitelist` list to: `CNAME1,CNAME3,CNAME4` and logout.
5. Login to rancher server as authorized user using CNAME3 **successfully as expected** and log out.
6. Login to rancher server as authorized user using CNAME4 **successfully as expected** and log out.
7. Login to rancher server as authorized user using CNAME1 **successfully as expected** and log out.
8. Update CNAME2 -> CNAME3 mapping to CNAME2 -> CNAME4 and validate DNS configuration reflects locally.
10. Login to rancher server as authorized user using CNAME1 **successfully as expected** and log out.
