### ISSUE TITLE
Validate steps to backup/restore single node 2.x rancher server

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16237]
**What kind of request is this (question/bug/enhancement/feature request):**
Test and document the process for backing up and restoring a single node rancher install.

**Steps to reproduce (least amount of steps as possible):**
Backing up as stolen from @galal-hussein 

1- stop rancher container
2- run the following command:

docker run  --volumes-from rancher-data -v $PWD:/backup alpine tar  zcvf  /backup/rancher-data-backup-<RANCHER_VERSION>-<DATE>.tar.gz  /var/lib/rancher

**Comment by deniseschannon** [comment]
Validated as part of every release.
