### ISSUE TITLE
[2.1] failed to find schema resourceQuotaTemplates: undefined

### ISSUE THREAD

**Issue by niranjan94** [rancher/rancher#16239]
**What kind of request is this:** bug

**Steps to reproduce:** 
- Have a rancher server running on version `2.0.8` with atleast one cluster added.
- Upgrade the rancher server to `2.1.1`
- Login to rancher server
- The following error pops-up

![image](https://user-images.githubusercontent.com/2404372/47336218-69a5e980-d6ac-11e8-9e9a-806b34d03afc.png)

> But this is not consistent. It doesn't _always_ popup. Happens once in a while.

**Result:**
- Nothing in particular seems to be affected. In terms of UI and functionality. But I could be missing something as I haven't checked all parts of the server.

**Additional information:**
Looks like the rancher UI is trying to make a request to `GET /v3/resourceQuotaTemplates` but it results in a `404`.

**Environment information**
- Rancher version: `v2.1.1`
- Installation option: `single node`

**Comment by loganhz** [comment]
There was a UI cache issue which has been fixed now
Please clear your browser cache this time. And it will not happen anymore.
https://github.com/rancher/rancher/issues/15981

**Comment by niranjan94** [comment]
Okay thanks :)
