### ISSUE TITLE
Add support for mode tcp for Rancher's Ingress HAProxy loadbalancer

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16248]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Use case is to have SSL termination at the container and not at the Rancher Ingress LBs. Today, it is only possible to use either HTTP or SSL termination at the Rancher Ingress LBs, we need support for `mode tcp`.

**Comment by cianiandreadev** [comment]
+1
