### ISSUE TITLE
sometimes imagepullbackoff ,ErrImagePull

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#16243]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/14210543/47343689-46ddfa00-d6d9-11e8-9834-9fcc5dd79160.png)

The image is existed in my worknode, and the image pull policy is never.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`container`|

**Comment by loganhz** [comment]
Maybe it is related to https://github.com/rancher/rancher/issues/15994

Also, you need to make sure you add the registry in rancher first, then you can deploy your workload

The information you provided is very limited. We can not reproduce or help you to fix it.

Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

**Comment by wuchencm** [comment]
my pod pull policy is never，but it pull image from harbor first when it upgrade the pod

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/47355837-055b4800-d6f5-11e8-9de9-67dabbfde3c5.png)

Can you check it in UI if it is `Never` and also in the workload YAML, please?
It works well for me in 2.1.1

**Comment by wuchencm** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
1、It mean my image is not present with pull policy of never, but the image is existed in my node
2、It's run successed when i delete the pod and then create a new pod with the same image

**Comment by loganhz** [comment]
The pod is scheduled to woker1. Your screen shot is for worker2

**Comment by wuchencm** [comment]
![image](https://user-images.githubusercontent.com/14210543/47400217-e1d4e380-d76e-11e8-9e84-fabaf26a4db9.png)
How can i delete work1 in rancher ui, i found work2 only

**Comment by loganhz** [comment]
Can you create a new issue with the reproduce steps, please?

We need the stets to find out why the worker1 is missing in your cluster.
