### ISSUE TITLE
Feature request: Locks on environments, stacks

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#1624]
A nice to have: some kind of lock for objects such as environments and stacks. I feel a little scared at times doing things like search and delete via the API. It would be nice to not be able to accidentally delete production!

This this is kind of similar to RightScale's locks on Deployments and Servers. Making containers immutable (like EC2's disable termination) I think is a different story, but locking container services makes sense at least.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
