### ISSUE TITLE
Make pod view more in line with get pods output

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16245]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
When running `kubectl get pods`, you get a lot of info about the pods like the status (which is `containerStatuses.state.waiting.reason`) and restart count. Would be nice to have this in our pod list view as well. Pod age is covered in https://github.com/rancher/rancher/issues/15761

``` 
NAME                    READY     STATUS             RESTARTS   AGE
nginx-69fcf667c-hsj65   0/1       CrashLoopBackOff   14         25m
```

**Comment by tfiduccia** [comment]
This is being shown inside the pod for containers.  The pod list itself is listing in the workload details page and it's not added there?  Did you want it for Pods as well or just for containers?

Workload details - Pod list
![image](https://user-images.githubusercontent.com/11514927/49481527-963f3c00-f7e8-11e8-8624-f8578d3563e5.png)

Pod Details - container list
![image](https://user-images.githubusercontent.com/11514927/49481580-c1c22680-f7e8-11e8-8e38-3b98804fac6c.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/4/19)
Confirmed enhancement.
You can now see pod restarts in the Workload view under image subtext:
![image](https://user-images.githubusercontent.com/45179589/50704799-e0992000-1015-11e9-8213-1ae50fe17f1c.png)
And under the pod itself:
![image](https://user-images.githubusercontent.com/45179589/50704813-ef7fd280-1015-11e9-987e-1c5ad29932a8.png)

Statuses are shown on workload page as the pod is created. With a small workload this can be hard to see. Try creating an ubuntu workload and quickly view workload details page to see status under the State (subtext). You can also try to create nginx and scale up a few and quickly view the workload details page to see the statuses.
