### ISSUE TITLE
 Rancher2.0.8 add public cloud problem

### ISSUE THREAD

**Issue by yangjia517** [rancher/rancher#16249]
Operating system: ubuntu16.04
Docker version: 17-03-2

Hello everyone:

I had a problem that bothered me for a long time. I had the same problem when I added clusters for rancher 2.0, by creating a host template (Ali Cloud), and then adding clusters. As I can see from the console in Aliyun, the ECS server has been successfully created and the docker has been installed, but an error was reported when k8s was installed:

![image](https://user-images.githubusercontent.com/33953118/47357686-0f337a00-d6fa-11e8-8d0d-2d6fd7f69981.png)

**Comment by yangjia517** [comment]
My AliCloud ECS server has been bound to EIP (Public Network IP) and my master host is on the local intranet, but has access to public network resources. Is this possible?
![image](https://user-images.githubusercontent.com/33953118/47358031-2161e800-d6fb-11e8-9424-d90d20f7d0e7.png)

**Comment by loganhz** [comment]
`192.168.101.128` is the IP of your rancher server.
`192.168.0.167 is` the IP of the only node in your cluster.
What is `192.168.0.163` for?
How did you start rancher? With docker run or in a HA mode?
Did you setup the `server-url` to `192.168.101.128` after you changed the password?
When you create the cluster, did you select a VPC and what security group did you select?
How many instances did you add into the cluster? What roles did you select for each node. Did you remove some node during provisioning?

**Comment by yangjia517** [comment]
Let me explain in detail:
I define the host template and add clusters in my local environment：
![image](https://user-images.githubusercontent.com/33953118/47410600-ef06c800-d798-11e8-9fa2-3898d3725e39.png)

Configuration of public cloud:
![image](https://user-images.githubusercontent.com/33953118/47410639-15c4fe80-d799-11e8-97eb-fed6d05767fc.png)
I am not sure whether it is k8s or aliyun.

**Comment by loganhz** [comment]
Can you try the following, please? I guess the issue is you created two nodes in the cluster and removed one. The cluster will be broken in this case.

1. Remove your current rancher server
2. Start rancher server by running `docker run -d -p 80:80 -p 443:443 rancher/rancher:v2.1.1`
3. Login Rancher UI with the public IP of the rancher server node.
4. Update the password and set the `server-url` (If you want to use private IP, you need to make sure it is in the same VPC or reachable with your k8s cluster nodes )
5. Enable aliyun node driver
6. Add a aliyun node template as you did before
7. Add one node with all roles as you did before
8. Click create and wait

**Comment by yangjia517** [comment]
> 你能试试以下吗？我想问题是你在集群中创建了两个节点并删除了一个节点。在这种情况下，群集将被破坏。
> 
> 1. 删除当前的牧场服务器
> 2. 通过运行启动rancher服务器 `docker run -d -p 80:80 -p 443:443 rancher/rancher:v2.1.1`
> 3. 使用rancher服务器节点的公共IP登录Rancher UI。
> 4. 更新密码并设置`server-url`（如果要使用专用IP，则需要确保它位于同一个VPC中，或者使用k8s群集节点可以访问）
> 5. 启用aliyun节点驱动程序
> 6. 像以前一样添加aliyun节点模板
> 7. 像以前一样添加一个包含所有角色的节点
> 8. 单击“创建并等待”

![image](https://user-images.githubusercontent.com/33953118/47417752-49a91f80-d7ab-11e8-95b8-3855236fe6d7.png)
According to your suggestion, the problem still exists.
![image](https://user-images.githubusercontent.com/33953118/47417912-9d1b6d80-d7ab-11e8-9f01-5768fba27a2d.png)

**Comment by yangjia517** [comment]
> 这对我来说很有用。你能发布安全组规则了吗？

Is the security group rule a public cloud security group?
![image](https://user-images.githubusercontent.com/33953118/47423808-8e878300-d7b8-11e8-818c-7a3713d1cb87.png)

**Comment by loganhz** [comment]
Yes, the security group for your node `test1`. You need to show all of the inbound rules.

For more port requirements detail,  please see https://rancher.com/docs/rancher/v2.x/en/installation/references/

**Comment by yangjia517** [comment]
> 是，您的节点的安全组`test1`。您需要显示所有入站规则。
> 
> 有关更多端口要求的详细信息，请参阅https://rancher.com/docs/rancher/v2.x/en/installation/references/

My problem was solved. I changed the IP connection to master to network IP. ECS created the instance successfully. Thank you very much.
