### ISSUE TITLE
Backport: Rancher 2.1 runs in HA mode on Kubernetes even with 1 replica

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#16256]
Backport: https://github.com/rancher/rancher/issues/16251

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc5
rancher/rancher:master

* Reproduced original issue where clusters would be unavailable after rke aio install was upgraded to 2.1.x
* Deployed HA rke all in one cluster - v2.0.8
* Created DO cluster, deployed workloads, ingress
* Upgraded to v2.1.2-rc5/master

After upgrading, clusters remained available. Logs showed Rancher as running in single-server mode. Workloads and ingress remained functional.
