### ISSUE TITLE
nginx.ingress.kubernetes.io/permanent-redirect-code annotation not working

### ISSUE THREAD

**Issue by carolosf** [rancher/rancher#16260]
I am using an ingress to expose port 443 that uses port 80 on a workload.

I have added an annotation nginx.ingress.kubernetes.io/permanent-redirect-code=301.

As you can see in this screenshot
https://imgur.com/XmsHbqZ

Annotation documentation:
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#permanent-redirect-code

By default this is using redirect code 308 to perform the redirect when you hit port 80 and this 308 redirect code is not yet widely supported.

E.g. sharing a link on facebook shows a screenshot of the redirect page rather than the end page.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`ingress`|

**Comment by superseb** [comment]
This has been added in 0.18.0 (https://github.com/kubernetes/ingress-nginx/pull/2834) and will be fixed when https://github.com/rancher/rancher/issues/15163 is done.
