### ISSUE TITLE
Backport: k8s 1.12 official support 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16262]
Backport https://github.com/rancher/rancher/issues/16261. Need to add rke fix for flannel provider in before assigning to qa for testing.

**Comment by sangeethah** [comment]
Need to cover the following configurations for k8s 1.12:

```
Ubuntu 16.04 - docker version 17.03 
RHEL 7.5 - docker version 1.13 (native) 
ROS 1.4.1 -  docker version 17.03 
SLES - 12 SP2 - docker version 17.09.1_ce 

Network Provider/Project Isolation:
Canal/No - Default configuration 
Canal/Yes 
Flannel/No
Calico/No
```

**Comment by soumyalj** [comment]
Completed validation on
1.  ROS 1.4.2 with Canal/No
2. SLES - 12 SP2 - docker version 17.09.1_ce with Canal/No

**Comment by alena1108** [comment]
Closing as testing discovered some issues with 1.12 release on a patched branch. Will evaluate it against 2.2 only
