### ISSUE TITLE
Backport: logging to elastic search uses TLSv1

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16276]
Backport https://github.com/rancher/rancher/issues/16042

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc3

* Created Rancher server & cluster
* Setup external ElasticSearch
* Enabled ES logging target w/ https endpoint, selecting TLSv1.2
* Saw logs being transported to ES
* Checked logs for TLS handshake and saw correct version
