### ISSUE TITLE
Display Helm Answers in the UI.

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#16279]
We don't currently expose the answers in the UI.  Though they are available in the API.  We have a request to expose them via the API as well.

![helm answers](https://user-images.githubusercontent.com/942110/47449077-bca49d00-d78f-11e8-9fef-9960325a4e48.gif)

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/48524524-8902f180-e8bb-11e8-90c0-e37c906fecca.png)
Add a `Answers` section in app detail page

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/18)
Confirmed the enhancement. We now see an Answers section in the UI when looking at the app details. Compared against the answers.yml and the API to ensure this matches. Tested with several apps and halo tested.
