### ISSUE TITLE
There is one node work2 only in my k8s cluster, but the pod is scheduled to woker1

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#16272]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/14210543/47421666-ab6d8780-d7b3-11e8-99aa-18a9210357d8.png)
![image](https://user-images.githubusercontent.com/14210543/47421682-b58f8600-d7b3-11e8-81c7-238994c5d466.png)
There is one node work2 only in my k8s cluster, but the pod is scheduled to woker1
to #16243 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
There is no reproduce steps.  We can not help

Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

**Comment by loganhz** [comment]
You can find us in wechat by searching `rancher2`.
