### ISSUE TITLE
View rancher server logs in UI

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#1627]
Would be very nice to have a websocket tail of the rancher server log(s) and potentially other relevant logs that can be accessed such as agents. Keeps you out of server shells and better readability etc. :)

**Comment by vincent99** [comment]
This will be available indirectly in the upcoming HA improvements..

**Comment by deniseschannon** [comment]
Leaving this open as it still needs to be supported in a single node setup.

In a HA setup, this is available when [viewing the management stack](http://docs.rancher.com/rancher/faqs/server/#ha-monitoring).

**Comment by LLParse** [comment]
We could implement this just like HA by exposing a 'System' stack that is comprised of the standalone Rancher server node.

**Comment by will-chan** [comment]
Using #71 to track this.
