### ISSUE TITLE
When the service is set to inactive, the container can be run manually

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#16270]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. Create a service；
2. Set the service to inactive state；
3. Manual start container；

**Result:**
The service is set to inactive, but the container is always running.
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/20707603/47415105-3bf09b80-d7a5-11e8-8e13-5c93bb9216f7.png">

**Environment information**
- `rancher/server` : v1.6.22,1.6.15
- Installation option (single install):

**Comment by alena1108** [comment]
@xiaoluhong @loganhz this is by design. Service being inactive means that reconcile won't run for it. You can remove the container, start it, do any operation - there will be no intervention.

**Comment by xiaoluhong** [comment]
I see. Thank you @alena1108
