### ISSUE TITLE
Can't refresh catalog from "Helm Charts server URL"

### ISSUE THREAD

**Issue by dengzhh** [rancher/rancher#16271]
I create a local helm charts server and add a catalog from it. The catalog sync ok. I changed a app's templete, but i can't find a way to refresh the app in catalog.
After serveral hours, the catalg seems still not refreshed yet.
I checked the "index.yaml" file in helm server side and rancher server side, they are different.

helm server side:
[root@localnode stable]# ll index.yaml 
-rwxrwxrwx 1 root root 165652 Oct 24 10:26 index.yaml

rancher server side
[root@node1 794469a8cda4100cce4ff5603cf236f9]# ll
total 112
-rwxr-xr-x 1 root root 114309 Oct 24 15:36 index.yaml

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`global-admin.catalog`|

**Comment by guangbochen** [comment]
the catalog will be auto-refreshed in 1hr or you can click the `Refresh` button in the project level `Catalog Apps` page.

**Comment by guangbochen** [comment]
close due to no respond.
