### ISSUE TITLE
Backport: UI Support tls version config for elasticsearch

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16283]
Backport https://github.com/rancher/rancher/issues/16070 to 2.1.2

**Comment by westlywright** [comment]
Available in ui tag `2.1.5` in the next 2.1.2 rc

**Comment by tfiduccia** [comment]
@bmdepesa - This is not in rc1

**Comment by westlywright** [comment]
@tfiduccia & @bmdepesa the commit is present in 2.1.5 but the UI is weird. If you are on the elastic search logger tab and input `https://` into the address input the fields will show up. I will be opening a UI ticket to change that because its super confusing

**Comment by tfiduccia** [comment]
Yes, field should always be there but dimmed if it's not https:

**Comment by tfiduccia** [comment]
Version - 2.1.2-rc2
Verified field added and modified on Post/Put methods
