### ISSUE TITLE
View in API "Show Request" error - Error: parsererror

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#16287]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Go into any cluster and project, select "workloads", on the right of any workload select the ellipsis and click on "view in api".

Once the api info has come up, select the "rollback" button in the top right, in the edit window select the "show request" button.

**Result:**
![image](https://user-images.githubusercontent.com/18737885/47473514-80cc0f00-d845-11e8-800e-98663fbbddbe.png)

**Comment by vincent99** [comment]
I mean you can fix this but the API call causing this is wrong. There should be a response object, or it should be returning 204.

**Comment by deniseschannon** [comment]
After talking with @vincent99 , the API should be fixed for this use case.

**Comment by vincent99** [comment]
The UI was changed in api-ui 1.1.5 to not show the error, but the response is still "wrong".  If there's no body the response code should be 204.
