### ISSUE TITLE
Feature request: Placement/port usage maps

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#1628]
A nice to have: a UI view on hosts to show the current port usage/placements. In turn this data would be exposed easily in the API too which is very handy for systems interfacing Rancher such as monitoring and dashboards. A global view of this across all hosts would look amazing!

**Comment by flaccid** [comment]
RightScale has a cool feature for SDN networks such a network map, http://support.rightscale.com/12-Guides/Dashboard_Users_Guide/Manage/Network_Manager/Actions/01-Networks/View_a_Network/View_a_Network_Map/index.html (just a thought).

**Comment by vincent99** [comment]
This data is available per-host now to show as an addtl tab on hosts

**Comment by vincent99** [comment]
@alena1108 `publicEndpoints` seems to only include service containers, can you add standalone ones too?

**Comment by alena1108** [comment]
@vincent99 sure

**Comment by vincent99** [comment]
Not a terribly fancy graph or anything, but something..

![image](https://cloud.githubusercontent.com/assets/753917/13799809/165eaca4-eae0-11e5-8eed-993661446ae3.png)

**Comment by sangeethah** [comment]
Tested with latest build from master - Mar/16.

We now have "ports" tab in host detail view which lists all exposed ports (by service containers and standalone containers) on the host 

<img width="1270" alt="screen shot 2016-03-16 at 11 07 00 am" src="https://cloud.githubusercontent.com/assets/4266958/13823556/50b0c0fe-eb67-11e5-8576-923d37f41e99.png">

**Comment by MoulderUtes** [comment]
Sorry to ask a question on an old old old thread but is there some way to do this on rancher 2.x?
