### ISSUE TITLE
Private Registry Auth Causes Worker Nodes to Go Down

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rancher#16282]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Provision a cluster using rke with private registry (3 nodes).
Provision a custom cluster from UI with private registry and separate control plane, worker, and etcd.

**Result:**

Worker nodes restart every 15 seconds, kubelet, kube-proxy, and nginx. @galal-hussein discovered that the worker nodes communicating with the control plane kept receiving the private registry auth token over and over again.

**Other details that may be helpful:**
@aemneina suggested to configure the worker nodes as worker and control plane. That seemed to fix the issue. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **rancher v2.1.1**
- Installation option (single install/HA): **HA**

**Cluster information**
- Machine type (cloud/VM/metal) and specifications (CPU/memory): **4 CPU/16 GB**
- Kubernetes version (use `kubectl version`): **v1.11.3-rancher1-1**

**Comment by soumyalj** [comment]
Reproduced the issue in v2.1.1.
Tested with v2.1.2-rc2 on a setup with 3 nodes:
N1 - etcd
N2 - control
N3 - Worker.
Created the cluster with all the images in private registry. After the cluster came up successfully, the kubelet, kube-proxy, and nginx containers did not restart periodically.

Also tested with v2.1.2-rc7 on a Standalone airgap setup using private registry & cluster w/ private registry w/ auth. The cluster had
N1 -etcd
N2 - control
N3 - worker.

The cluster came up successfully . kubelet, kube-proxy, and nginx containers did not restart periodically.
Also, tested with v2.1.2-rc8 on a HA airgap setup using private registry and cluster with private registry. 
N1 -etcd
N2 - control
N3 - worker.

kubelet, kube-proxy, and nginx containers did not restart periodically.
```
ubuntu@ip-abc:~$ sudo docker ps -a|grep kube-proxy
7c1bab4d341c        registry:443/rancher/hyperkube:v1.11.3-rancher1                                                                                        "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                                     kube-proxy
ubuntu@ip-defg:~$ sudo docker ps -a|grep kubelet
7759b9319522        registry:443/rancher/hyperkube:v1.11.3-rancher1                                                                                        "/opt/rke-tools/en..."   3 hours ago         Up 3 hours                                      kubelet
ubuntu@ip-ghi:~$ sudo docker ps -a|grep nginx-proxy
b95b0cda7678        registry:443/rancher/rke-tools:v0.1.15                                                                                                 "nginx-proxy CP_HO..."   3 hours ago         Up 3 hours                                      nginx-proxy

```
