### ISSUE TITLE
Add the ability to support multiple node groups on EKS

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16299]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

Request from a potential user. More details to come.

When you create an EKS cluster, we currently limit you to a single node group/node pool/auto scaling group for workers. This request is to support multiple node groups.
This probably folds into https://github.com/rancher/rancher/issues/15772 but I opening a separate ticket because it is potentially a little more nuanced or captures a slightly different use case.

**Environment information**
rancher/rancher:v2.1.x

**Comment by deniseschannon** [comment]
Closed in favor of #15772 as it will be taken care of through that issue.
