### ISSUE TITLE
Config Rancher Pipeline's console timezone

### ISSUE THREAD

**Issue by iwin4aids** [rancher/rancher#16293]
![1](https://user-images.githubusercontent.com/16768783/47510500-d981c300-d8aa-11e8-9a00-da7f67e2fdbd.png)

As u see, the pipeline console works well, but the time display in console seems bad to me, it use the default utc timezone.But my local timezone is utc+8, how to config the timezone in the pipeline console ?

**Comment by gitlawr** [comment]
Edit the Jenkins workload in pipeline namespace, add the following argument to existing JAVA_OPTS environment variable and click `Upgrade`:
```
 -Duser.timezone=Africa/Abidjan
```
Change the above `Africa/Abidjan` to whatever timezone you need. It helps to set system timezone in jenkins master.
