### ISSUE TITLE
Error while getting agent config: invalid response 500: Failed to validate cluster: Hostname_override [xxx-xxx-KUB02] for host

### ISSUE THREAD

**Issue by rammaram06** [rancher/rancher#16294]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
Spin up rancher 2.1.1 server and add a cluster with etcd, controlpanel and worker and run it on an server with hostname in xxx-xxx-xxx format.

**Result:**
ime="2018-10-25T14:49:16Z" level=info msg="Connecting to wss://testrancher.xxx.org/v3/connect/register with token 2gprbmc9lc5wmbbc8d7cmcj8qtq62ckx2n229dmlqlbdp8wxl9t6rz"
time="2018-10-25T14:49:16Z" level=info msg="Connecting to proxy" url="wss://testrancher.xxx.org/v3/connect/register"
time="2018-10-25T14:49:16Z" level=info msg="Error while getting agent config: invalid response 500: Failed to validate cluster: Hostname_override [xxx-xxx-KUB02] for host (1) is not valid: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]"
time="2018-10-25T14:49:21Z" level=info msg="Error while getting agent config: invalid response 500: Failed to validate cluster: Hostname_override [xxx-xxx-KUB02] for host (1) is not valid: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]"

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, CPU 2, Memory - 4GB
- Kubernetes version (use `kubectl version`): v1.11.3 and also tried v1.10.5

Before I used v2.0.0 of rancher and it worked without any issue, seeing this issue in v2.1.1 of rancher.
All our hostnames are in this format xxx-xxx-xxx. Could you let me know, how to fix this issue?

**Comment by superseb** [comment]
The validation was added in https://github.com/rancher/rancher/issues/14571, the error describes the validation used which is lower case. Can you try with hostnames not containing uppercase characters?

**Comment by rammaram06** [comment]
@superseb  All our hostnames have uppercase characters, Is there a workaround for it. If not could you please add support to allow uppercase characters?

**Comment by superseb** [comment]
Current workaround is adding `--node-name lowercase-hostname` at the end of the generated `docker run` command. We can discuss if we want to lowercase hostname by default (currently it's `hostname -s`)

**Comment by rammaram06** [comment]
Thank you for your quick response. I think it should either support upper case hostnames or change them to lowercase by default instead of adding --node-name.

**Comment by david-maumenee** [comment]
@superseb, What is the workaround for #16508 and #16541 when the issue rise during an upgrade ?

Thanks

**Comment by jiaqiluo** [comment]
### Reproduction
**Rancher version**: 2.1.1
**Installation option**: single
**Step**: Added a cluster from an existing node which hostname is uppercased, put all roles on one node
**Result**:
get the following error:
```Failed to validate cluster: Hostname_override [xxx-xxx-KUB02] for host (1) is not valid: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9?(\.a-z0-9?)')]"```
<img width="1517" alt="reproduce-bug" src="https://user-images.githubusercontent.com/6218999/48451368-6364d380-e767-11e8-9399-7ec5a1f13431.png">

### Validation 
**Rancher version**: 2.1.2-rc11
**Installation option**: single
**Step**: Added a cluster from an existing node which hostname is uppercased, put all roles on one node
**Result**:
Successfully added the cluster. 
<img width="1544" alt="fix" src="https://user-images.githubusercontent.com/6218999/48452022-67462500-e76a-11e8-9fa5-691b3faded36.png">

### Conclusion
Bug fixed verified.

**Comment by david-maumenee** [comment]
Is this will also fix #16541and #16508 when upgrading an old cluster create with v2.0.x on UpperCase named node ?

**Comment by jiaqiluo** [comment]
@david-maumenee Hi, the issue #16541 and #16508 are fixed in the coming Rancher v2.1.2.
Please see my comment here for testing result in v2.1.2-rc12: https://github.com/rancher/rancher/issues/16541#issuecomment-439117764
