### ISSUE TITLE
New added Node not available in GUI

### ISSUE THREAD

**Issue by dmaggo** [rancher/rancher#16290]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Baseline situation: 
A 4-Node-Cluster deployed via RKE with Rancher Version 2.1.1

Adding a additional Workernode to the rancher-cluster.yaml and update the cluster via "rke up --update-only"

**Result:**
The new Workernode (10.201.40.132) is available via kubectl **but not in the GUI**
![image](https://user-images.githubusercontent.com/38687952/47482127-f203c600-d835-11e8-9bc5-5970867db672.png)
Also available with kubectl over the Rancher GUI
![image](https://user-images.githubusercontent.com/38687952/47482184-1790cf80-d836-11e8-981c-aa11237b5d27.png)

**Other details that may be helpful:**
Browser cache cleaned.
Test with other browsers

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher version 2.1.1

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported (Created via RKE)

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Every VM with 4 Cores and 16GB RAM.

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Docker (use `docker info`):

Server Version: 17.03.2-ce

**Comment by loganhz** [comment]
Is this the `local` cluster? Or you started a rancher server and imported the 4-nodes RKE cluster into rancher?

**Comment by dmaggo** [comment]
This is the local cluster. we only renamed it via GUI.

**Comment by dmaggo** [comment]
so you mean i should remove the complete addon part in the cluster.yaml?
