### ISSUE TITLE
Only Rancher administrator can download keys. Cluster owner can not.

### ISSUE THREAD

**Issue by jannylund** [rancher/rancher#16292]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- Create cluster as Administrator
- Add another user as Cluster Owner
- Login as the user with Cluster Owner permissions
- Try to download keys for the node.

**Result:**
- The list item Download keys is missing.

**Other details that may be helpful:**
- Administrator can download keys to all nodes in all clusters.

**Environment information**
- Rancher version: v2.0.4
- Installation option: Standalone
<img width="226" alt="screenshot 2018-10-25 11 51 32" src="https://user-images.githubusercontent.com/121457/47497945-65243100-d864-11e8-9c72-41ab93e247b0.png">
<img width="284" alt="screenshot 2018-10-25 11 50 59" src="https://user-images.githubusercontent.com/121457/47497948-65bcc780-d864-11e8-892c-93b71e6ef286.png">

**Comment by loganhz** [comment]
Fixed in v2.1.3
