### ISSUE TITLE
Improve workflow deployments

### ISSUE THREAD

**Issue by anjmao** [rancher/rancher#16291]
Hi, it would be really useful to get some documentation about best practices how to deploy your own services to rancher using rancher-cli. I can only find tutorials for user interface which is completely useless if I want automated CI/CD.

I found only tutorials how to use rancher workflow UI.
1) https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/workloads/deploy-workloads/
2) https://www.linode.com/docs/applications/containers/how-to-deploy-apps-with-rancher/

Here is how I currently do it.
1) I have golang backend with gRPC.
2) Each time I merge to gitlab develop branch it automatically builds new docker image and pushes to gitlab docker registry.
3) After image is built and sent I use standard kubectl to apply resources  `rancher kubectl apply -f /k8s/`.

**My suggestion.**
I imagine that there should be some kind of workflow.yaml. Example:
workflow.yaml
```yaml
name: my-service
image: myregistry/my-service/v1.2.3
namespace: test
portMapping: ...
scale: 2
```

deploy workflow with rancher cli
```sh
rancher workflow deploy -f workflow.yaml
```

This way I don't need to use that UI (any good dev ops tool should focus on command line first instead of UI).

**Comment by ap1969** [comment]
I'm working on a CI-based implementation, and that's pretty much what I'm doing:
 - Create the dev deployment via the UI till I'm happy.
 - Extract the YML for that object (including secrets, configmaps, etc)
 - Add/update the YML file in GIT
 - Incorporate that into my CI scripts (which is running on Gitlab)

That way, everything is version-controlled.

**Comment by deniseschannon** [comment]
It sounds like you should look into the pipeline feature:

https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/pipelines/

Let me know if that doesn't cover what you're looking for.
