### ISSUE TITLE
Edit Load Balancer page does not have "Save" button when there is lot of target entries ( 8 in my case). 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1629]
Server version - V0.29.0-rc2

Edit Load Balancer page does not have "Save" button when there is lot of target entries ( 8 in my case). 

<img width="936" alt="screen shot 2015-07-23 at 8 38 04 am" src="https://cloud.githubusercontent.com/assets/4266958/8854790/90b48b42-3116-11e5-97c7-769f2a7c8c4d.png">

Need scroll bar support to list all target entries.

**Comment by vincent99** [comment]
Now with more scrolling..

**Comment by deniseschannon** [comment]
Verified v0.30.0-rc4
