### ISSUE TITLE
Add the ability to upload "user-data" while spinning up EKS clusters

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16300]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

When spinning up instances, you can add `user-data` to an AWS instance, we want to be able to upload this same text when spinning up EKS nodes

**Environment information**
v2.1.x

**Comment by mitchellmaler** [comment]
@cjellick 
Can this be extended to other drivers as well? Like the openstack driver (docker-machine) asks for a ssh-key private and optional user-data file. I have had to manually add those as config maps to the rancher server pods. It would be very useful to be able to upload those to rancher (api/ui).

I am sure other infra templates would benefit from this as well.

**Comment by cjellick** [comment]
@mitchellmaler this issue will be specifically for EKS, which is somewhat unique, but you can open an issue for either openstack specific support or general support for us to consider

**Comment by cjellick** [comment]
does this need first class api support or can it be supported via the custom yaml editor

**Comment by daxmc99** [comment]
This  [issue](https://github.com/rancher/rancher/issues/14598) about adding SSH keys for EKS can also be acomplished during this improvement.

**Comment by davidnuzik** [comment]
Validated in #17711 please refer to that issue.
