### ISSUE TITLE
Backport: Private Registry Auth Causes Worker Nodes to Go Down #16282

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16304]
Backport https://github.com/rancher/rancher/issues/16282

**Comment by moelsayed** [comment]
Fixed in https://github.com/rancher/rancher/pull/16321

**Comment by soumyalj** [comment]
Reproduced the issue in v2.1.1. 
Tested with v2.1.2-rc2 on a single node setup. Created a cluster with all the images in private registry. After the cluster came up successfully, the kubelet, kube-proxy, and nginx containers did not restart periodically.
