### ISSUE TITLE
Rancher agent logs websocket: bad handshake when Rancher is deployed/running on GKE

### ISSUE THREAD

**Issue by bluemalkin** [rancher/rancher#16305]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install rancher v2 using the latest chart (2018.10.2), using secret for ingress.tls.source (my own cert-manager let's encrypt certificate)
- Import a cluster

**Result:**
Imported cluster stuck in "Waiting for API"

Catle node agent logs:
```
time="2018-10-25T04:18:15Z" level=info msg="Connecting to wss://xxxxx/v3/connect with token qb8rgrcwfdr2kqj78jkbrb677sp4pctw5k95gq546z2z4jnzjvds5g"
time="2018-10-25T04:18:15Z" level=info msg="Connecting to proxy" url="wss://xxxxxx/v3/connect"
time="2018-10-25T04:18:16Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-10-25T04:18:16Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

- Firewall is open for 443
- I am able to curl the CATTLE_SEVER host
- I am *NOT* able to wget the host
```
 wget -O- https://xxxx
--2018-10-25 22:41:41--  https://xxxx
Resolving xxxx
Connecting to xxxxx|:443... connected.
ERROR: cannot verify xxxxx certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Unable to locally verify the issuer's authority.
To connect to xxxxxx insecurely, use `--no-check-certificate'.
```
- I am able to wget the host from stock ubuntu:latest image

Is the cattle-node-agent image missing some CA's for let'sencrypt ?

**Comment by superseb** [comment]
The CA's are present, the wget is probably failing because the `SSL_CERT_DIR` is set to `/etc/kubernetes/ssl/certs` for the retrieved `cacerts` (if needed, not in case of recognized CA signed certificates). Curl working also indicates the chain is valid, also Golang will print `x509: certificate signed by unknown authority` when the chain is not valid as well. 

What cluster are you importing and what is the network path between agent and rancher?

**Comment by bluemalkin** [comment]
@superseb  I've been trying to import a number of GKE's into rancher v2 also running on it's own GKE. All GKEs are in their own project and the rancher server is public accessible....

**Comment by bluemalkin** [comment]
I can see that the annotations of the chart Ingress is correctly setting:
```
			proxy_connect_timeout                   30s;
			proxy_send_timeout                      1800s;
			proxy_read_timeout                      1800s;
```

According to https://cloud.google.com/load-balancing/docs/https/#timeouts_and_retries to support Websockets on GCP LBs the `keepalive_timeout` needs to be increased to  `620s` from default `72s`

This is unfortunately hard-coded in the ingress controller:
https://github.com/kubernetes/ingress-nginx/blob/master/rootfs/etc/nginx/template/nginx.tmpl#L136

So I'm out of ideas on how to configure my GCP tcp lb to support websockets.

**Comment by bluemalkin** [comment]
Furthermore, the nginx ingress controller logs is showing just HTTP 200
```
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:13 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3974 0.028 [rancher-ops-rancher-80] 10.95.34.12:80 60 0.028 200
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:15 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3978 0.002 [rancher-ops-rancher-80] 10.95.33.15:80 60 0.002 200
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:20 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3978 0.002 [rancher-ops-rancher-80] 10.95.34.12:80 60 0.002 200
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:23 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3974 0.004 [rancher-ops-rancher-80] 10.95.33.15:80 60 0.003 200
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:25 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3978 0.004 [rancher-ops-rancher-80] 10.95.34.12:80 60 0.003 200
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:30 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3978 0.037 [rancher-ops-rancher-80] 10.95.33.15:80 60 0.038 200
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:33 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3974 0.003 [rancher-ops-rancher-80] 10.95.34.12:80 60 0.004 200
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:35 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3978 0.033 [rancher-ops-rancher-80] 10.95.33.15:80 60 0.034 200
x.x.x.x - [x.x.x.x] - - [30/Oct/2018:08:31:40 +0000] "GET /v3/connect HTTP/1.1" 200 60 "-" "-" 3978 0.003 [rancher-ops-rancher-80] 10.95.34.12:80 60 0.003 200
```

**Comment by superseb** [comment]
I ran the following setup:

- Created 2 GKE clusters version `1.10.7-gke.6` (one for Rancher with GKE ingress disabled, one to import)
- Setup Helm using https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-init/ against Rancher GKE
- Installed NGINX ingress controller by using `helm install --name nginx stable/nginx-ingress --set controller.service.externalTrafficPolicy=Local`
- Retrieved IP for created LB in front of NGINX ingress controller (`kubectl get svc`)
- Pointed FQDN to that IP in DNS
- Installed Rancher using https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/ with default self signed certificates
- Login to the UI, set server-url to FQDN
- Add Cluster -> Import
- Run generated commands on 2nd GKE cluster

<img width="1133" alt="screen shot 2018-10-30 at 11 46 56" src="https://user-images.githubusercontent.com/2620179/47713022-8a84b680-dc39-11e8-97dd-d39310292f65.png">

If you can mention anything that deviates from these steps, I can use it to reproduce. You can also run these steps and see if you run into the same or not.

**Comment by bluemalkin** [comment]
I can confirm that the above works with fresh GKEs.

Let me do some more digging with my Shared VPC GKEs.

**Comment by bluemalkin** [comment]
Fixed by recreating the Rancher GKE cluster from scratch.

@superseb I think it's because at some point I changed the IP of my rancher endpoint from private to public IP and that CATTLE_HOST may have been cached somewhere in rancher server ?
