### ISSUE TITLE
Tweaks Cluster Capabilities Fields

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#16302]
Some of the field names in the `capabilities` object of a cluster are confusing. We should rename the following:

    `l4loadBalancer` -> `loadBalancerCapabilities`
    `ingressControllers` -> `ingressCapabilities`

We are also going to drop the following field from the `ingressControllers` object:

    `httpLoadBalancingEnabled`

**Comment by vincent99** [comment]
The type names too..

**Comment by jiaqiluo** [comment]
Validated on rancher:master on 11/19

The following is major scenarios tested:
- Enable/Disable authentication
- Allow any valid user for server, cluster, and project level
- Allow members of Environments, plus Authorized Users and Organizations for server, cluster, and project level
- Restrict access to only Authorized Users and Organizations for server, cluster, and project level
- Local users for server, cluster, and project level

**Comment by sangeethah** [comment]
Tested with rancher server build done on Nov 16 from master:

Following are the names of the capabilities field for clusters:

```
capabilities": {
"ingressCapabilities": [
{
"customDefaultBackend": true,
"ingressProvider": "GCLB",
"type": "/v3/schemas/ingressCapabilities"
}
],
"loadBalancerCapabilities": {
"enabled": true,
"healthCheckSupported": true,
"protocolsSupported": [ 2 items
"TCP",
"UDP"
],
"provider": "GCLB",
"type": "/v3/schemas/loadBalancerCapabilities"
},
"nodePoolScalingSupported": false,
"nodePortRange": "30000-32767",
"type": "/v3/schemas/capabilities"
````
