### ISSUE TITLE
Find the pipeline workspace in rancher 2.0 pipeline

### ISSUE THREAD

**Issue by pkeshab** [rancher/rancher#16317]
Hello Guys,

Is it possible to find the workspace of the jenkins pipeline in rancher 2.0? I have used the CI/CD pipeline from rancher 2.0 to build sample maven springboot application. It successfully  build the image as below:

15:43:16 [INFO] Installing /home/jenkins/workspace/pipeline_p-cdljb-5/pom.xml to /root/.m2/repository/org/springframework/boot/hello-springboot/1.3.5.RELEASE/hello-springboot-1.3.5.RELEASE.pom
15:43:16 [INFO] ------------------------------------------------------------------------
15:43:16 [INFO] BUILD SUCCESS
15:43:16 [INFO] ------------------------------------------------------------------------
15:43:16 [INFO] Total time: 14.540 s
15:43:16 [INFO] Finished at: 2018-10-26T15:43:16Z

Now I want to check where my war file is located. Here I am running rancher 2.0 as a docker container in aws ubuntu. 
Here is my pipeline code:

stages:
- name: rancher-pipeline.yaml
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: |-
        mvn clean install
timeout: 55

Thanks

**Comment by gitlawr** [comment]
Hi,
As described in `workspace` section in the docs: https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/concepts
The artifacts in the workspace will be cleaned up when a pipeline execution ends. You need to publish the war files somewhere else if you want to keep them.
