### ISSUE TITLE
Add support for dnsConfig in UI

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#16310]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`containers.run`|

**Comment by wuchencm** [comment]
i want to achieve
docker run --dns=xx.xx.xx.xx images

**Comment by superseb** [comment]
Per pod DNS is beta since v1.10 and we don't expose it in the UI as far as I can see, it's in the API so we should be able to add it. It just needs more than a single checkbox.

Ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config

**Comment by loganhz** [comment]
It will be out in v2.2
Close in favor of https://github.com/rancher/rancher/issues/16126
