### ISSUE TITLE
Pipeline runs to get 403 errors very frequently

### ISSUE THREAD

**Issue by zhangsean** [rancher/rancher#16314]
*Describe your issue here*
I create a pipeline which authorized with internal Gitlab, the project is so simple just contains one file `README.md`, the pipeline get a very little chance runs to success, but runs to get 403 errors very frequently. 
The screenshot of build history of this pipeline.
![image](https://user-images.githubusercontent.com/2536402/47577843-72334400-d97a-11e8-88b5-b77d9c42550f.png)

All the build errors are the same 403.
```
Build job got 403 403: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 403 No valid crumb was included in the request</title> </head> <body><h2>HTTP ERROR 403</h2> <p>Problem accessing /job/pipeline_p-xsswx-14/build. Reason: <pre> No valid crumb was included in the request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/> </body> </html>
```
The screenshot of fail build:
![image](https://user-images.githubusercontent.com/2536402/47578582-52048480-d97c-11e8-9e02-e8eff47b0182.png)
While I rerun the build again and again, usually the 403 error shows very fast in one second, then all the other steps are frozen as you see. If there are no 403 error in three seconds, the message `Assigning jobs to pipeline engine` are shown, then everything goes well run to success finally.  

It seems like the following jenkins issue: Control initial crumb issuer proxy compatibility value
https://issues.jenkins-ci.org/browse/JENKINS-50767
The Jenkins Setup Wizard enables the CSRF protection.
The default setttings can then cause problems (invalid crumb errors) when using the default setup.
The goal of this issue is to provide a way to enable or disable the initial state on startup using a system property.
e.g. -Djenkins.model.Jenkins.crumbIssuerProxyCompatibility=true will enable Proxy Compatibility on first startup.

---
My Rancher and K8S env:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`authenticated.project.pipeline.pipelines.run`|

**Comment by zhangsean** [comment]
The Changing of rancher server url caused this issue.

**Comment by nickelzhang** [comment]
i hava this problem too

Rancher | v2.1.6
-- | --
User Interface | v2.1.19
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1
