### ISSUE TITLE
Rework RBAC for Project/Cluster level templates

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16316]
For project/cluster level templates and template versions, the rbac handling is done in a custom way due to the fact that these resources are not namespaced. TAs we can't convert template/templateVersion to be namespaced - it will break the rollback - we have to address is differently:

* introduce 2 new namespaced CRDs - CatalogTemplate and CatalogTemplateVersion. They will backup global, cluster and project catalog templates.
* introduce a global namespace for storing global level templates
* on the api, translate catalogTemplate/catalogTemplateVersion to Template/TemplateVersion respectively
* drop current custom rbac rules handling

**Comment by jiaqiluo** [comment]
The first pass of all test cases is finished, and issues/bugs are tracked with separate tickets.
This ticket is closed.
