### ISSUE TITLE
Use recommended admission controllers for clusters

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16312]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Result:**
For v1.10 and later, recommended admission controllers are:
```
--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
```

https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use

**Comment by jiaqiluo** [comment]
Validated on Rancer:master 11/28

Steps:

1. Created DO cluster through Rancher
2. ssh to `Control Plane` node and run 

```
docker inspect kube-apiserver |  grep enable-admission-plugins
```
get the following output as expected:
```
            "--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota",
                "--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota",
```


Enhancement verified.
