### ISSUE TITLE
Container not starting with EBS volume

### ISSUE THREAD

**Issue by ajouve** [rancher/rancher#16327]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a new volume in the cluster
<img width="1298" alt="screen shot 2018-10-27 at 12 51 56" src="https://user-images.githubusercontent.com/2337492/47603077-1f43a600-d9e7-11e8-8218-18af203463d9.png">

2. Link the volume
<img width="1269" alt="screen shot 2018-10-27 at 12 52 44" src="https://user-images.githubusercontent.com/2337492/47603086-3f736500-d9e7-11e8-8660-1a9fbf586bf2.png">

3. Create a new mysql workload
<img width="1319" alt="screen shot 2018-10-27 at 12 53 29" src="https://user-images.githubusercontent.com/2337492/47603101-777aa800-d9e7-11e8-8e91-a7a9bfa153ac.png">
<img width="1262" alt="screen shot 2018-10-27 at 12 54 01" src="https://user-images.githubusercontent.com/2337492/47603102-777aa800-d9e7-11e8-8cf1-91e30f17743d.png">

**Result:**

the container is not starting, I always have `Containers with unready status: [infra-mysql]`

**Other details that may be helpful:**

If I remove the volume, the container is starting

**Environment information**
- Rancher version 2.11

**Cluster information**
- Cluster type : AWS EC2
- Machine type : t2.medium
- Kubernetes version 

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker:

```
Containers: 42
 Running: 28
 Paused: 0
 Stopped: 14
Images: 16
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 177
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1052-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: staging-1
ID: VIT5:NRCG:SQ6V:UGNP:Y6TE:FCNC:VK6O:X5YG:6CE7:HJSE:6PPE:ZTN6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=amazonec2
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by gcmcnutt** [comment]
I've got a similar problem on 2.1.6 -- a cluster of c5xx machines in AWS seem to have trouble after a while starting containers that have EBS volumes -- there seems to be an intermittent pattern where a worker node gets into a state where the I/O to the EBS store (as seen from the EC2 instance) is very very slow.

Perhaps some race condition as this is hard to reproduce.  Here's a recent example showing how slow reads are to the 2nd drive.

We first thought this might be something to do with the volume being a st1 type, however this seems more related to the actual host getting into a state where subsequent operations remain slow.

As a result, the actual mkfs takes hours to complete when it should be seconds.



root@gmcnutt-rancher-a-worker2:/var/log# dd if=/dev/nvme1n1 of=/dev/null bs=64k count=1000
1000+0 records in
1000+0 records out
65536000 bytes (66 MB, 62 MiB) copied, 109.636 s, 598 kB/s
root@gmcnutt-rancher-a-worker2:/var/log# lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0  128G  0 disk 
└─nvme0n1p1 259:1    0  128G  0 part /
nvme1n1     259:2    0  500G  0 disk 
root@gmcnutt-rancher-a-worker2:/var/log# dd if=/dev/nvme0n1 of=/dev/null bs=64k count=1000
1000+0 records in
1000+0 records out
65536000 bytes (66 MB, 62 MiB) copied, 0.118567 s, 553 MB/s

**Comment by deniseschannon** [comment]
Did your clusters have the AWS cloud provider enabled? You cannot use EBS volumes without having the AWS cloud provider enabled on the kubernetes cluster.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
