### ISSUE TITLE
Load Balancer does not work in v2.1.1

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16326]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Add a cluster by choosing Amazon EC2 with Amazon as cloud provider
Create a project under this cluster
deploy a workload with load balancer (see screenshot for settings at bottom)

**Result:**
the corresponding load balancer in the ****Load Balancing**** section is stuck on pending status.  (see screenshot for pending load balancer at bottom)

**Other details that may be helpful:**
Load Balancer work in v2.1.0 ( k8s service version v1.11.3)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.1
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provide, Amazon EC2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud,  t2.medium
- Kubernetes version (use `kubectl version`): 

```
```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}```
```

- Docker (use `docker info`):

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1049-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: ip-172-31-9-73
ID: VS64:X6T3:DFXS:3GPI:WII5:QCOD:CWL6:EUEF:NRDZ:4SMZ:HGGA:BBC2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
Setting:
<img width="1276" alt="bug1" src="https://user-images.githubusercontent.com/6218999/47600513-2e8b0b00-d977-11e8-9e09-275b066f8aad.png">

Error: infinity pending
<img width="1088" alt="bug2" src="https://user-images.githubusercontent.com/6218999/47600515-321e9200-d977-11e8-8c83-d59a974d7f69.png">

**Comment by alena1108** [comment]
@jiaqiluo I can't reproduce the issue on 2.1.2-rc1. Steps taken:

* created v1.11.3 cluster with cloud provider = aws
* created an nginx workload, with containerPort=listeningPort=80 of a type Load Balancer.

Lb works. Note that it might take some time for k8s cloud provider code to populate Load Balancer endpoint, so LB might become accessible only after ~2 mins.

I've tried testing with `sangeetha/testnewhostrouting`, and I wonder why in your comment you have 9098 as a container port? The container started from this image, listens on port 80

**Comment by jiaqiluo** [comment]
Update on 10/31/2018:

The same scenario is reproduced on a new AWS account with less security group settings & rules. And it works fine without errors! 

Test on Rancher Server Versions: v2.1.1 & v2.1.2-rc2

Conclusion:
There are some limitations on the number of rules per security group in AWS, which causes the load balancer cannot be active.
