### ISSUE TITLE
Cloud Provider Azure : add check on mandatory fields

### ISSUE THREAD

**Issue by david-maumenee** [rancher/rancher#16334]
**kind :** enhancement

**Steps to reproduce :**
- Add a cluster on Azure IaaS and select "cloud Provider" **Azure**
- Confirm the creation without fill in mandatory fields

**Result:**
Rancher UI don't display any warning, but the Cluster provisioning stuck in "provisioning"

**Environment information**
- Rancher version : v2.1.1

**request**
Add check on  mandatory fields
- subscription_id
- tenant_id
- aad_client_id
- aad_client_secret

**Comment by davidnuzik** [comment]
Note: blocked by #16893 and #16887 (not able to fully test and validate all is working correctly because cannot successfully fully provision azure cloud)

**Comment by davidnuzik** [comment]
We are able to provision Azure / custom RKE with azure cloud option now.
Version: master 2.2 (12/10/18)
Confirmed fixed. Verified that the form is validated by checking each of the required fields. Tested with both Azure RKE and custom RKE with azure cloud option. This worked in both cases. Confirmed I could stand up a cluster for each. Halo tested.
