### ISSUE TITLE
[CI/CD]Mount data reduce CI consumption

### ISSUE THREAD

**Issue by yl-yue** [rancher/rancher#16333]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Environment information**
- Rancher version: 2.1.1
- Installation option: single install

issue: Run Script By means of data mount reduce CI consumption

![image](https://user-images.githubusercontent.com/39790401/47636222-8f425f80-db92-11e8-8b7c-1cacde787004.png)

Every time CI runs out of resources, I wonder if I can solve this problem through caching

![image](https://user-images.githubusercontent.com/39790401/47636398-1bed1d80-db93-11e8-87bb-32be4e23f388.png)

**Comment by loganhz** [comment]
It will be covered in https://github.com/rancher/rancher/issues/16223
We will work on it soon

**Comment by materemias** [comment]
#19768 could resolve this
