### ISSUE TITLE
certs empty during provisioning

### ISSUE THREAD

**Issue by rrusso1982** [rancher/rancher#16332]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create three nodes running centos 7 in vmware.  Run rke up against them with defaults.

**Result:**
FATA[0125] [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [rancher03.sb.xanedu.com]: Get https://localhost:10250/healthz: Unable to access the service on localhost:10250. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: F1029 00:04:17.948164   32417 server.go:141] tls: failed to find any PEM data in certificate input

**Other details that may be helpful:**
Investigation shows that the files /var/lib/kubelet/pki/kubelet.crt and /var/lib/kubelet/pki/kubelet.key are empty on all nodes.

**Environment information**
- rke version v0.1.11
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 4CPU, 8GB RAM

- Docker (use `docker info`):

```
Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 17.03.3-ce
Storage Driver: devicemapper
 Pool Name: docker-8:3-402891181-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.295 GB
 Data Space Total: 107.4 GB
 Data Space Available: 91.33 GB
 Metadata Space Used: 3.539 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.639 GiB
Name: rancher01.sb.xanedu.com
ID: 42B4:KVHL:F7WT:6N7Y:DB3B:MIYX:S6XZ:QGVG:X53M:ADJ4:JDL2:JYCQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by loganhz** [comment]
Thanks for the report.

Close in favor of https://github.com/rancher/rancher/issues/15801
Also there is a workaround in that issue.

**Comment by rrusso1982** [comment]
The workaround in that issue says to copy the file from another node that has a working file but I have no nodes with a good file on it.  I’ve repeated the process multiple times and never wind up with a good node to copy from.

**Comment by loganhz** [comment]
@rrusso1982 
Thanks for the update. We will look at it soon.

**Comment by deniseschannon** [comment]
This sounds like a RKE CLI issue which should be opened in rancher/rke if you are still having issues.
