### ISSUE TITLE
How can i create workload by rancher 2.1 api

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#16336]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/14210543/47643866-a8a1d680-dba7-11e8-98c9-ac72bf15cbe3.png)
![image](https://user-images.githubusercontent.com/14210543/47643907-ba837980-dba7-11e8-817b-524abbba20e9.png)
the name option is not allowed edit ,What parameters must be needed to create workload?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`global-admin.clusters.index`|

**Comment by vincent99** [comment]
It is editable, but the type changed recently and the API-UI doesn't know how to draw a `dnsLabelRestricted`.

**Comment by vincent99** [comment]
Need someone to update the version of api-ui served to `1.1.6`.  The way that's done is currently changing in existing PRs so I'm leaving it alone.

**Comment by loganhz** [comment]
PR for updating api-ui is https://github.com/rancher/rancher/pull/15377

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/1
Verified fixed
