### ISSUE TITLE
Rancher 2.0 | Is it possible to set-up Rancher server authentication using CLI/API/Other automated mechanism?

### ISSUE THREAD

**Issue by aku105** [rancher/rancher#16339]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
N/A

**Result:**
I'm expecting to able to set Rancher server authentication information using CLI/API, so that I can automate this step in a configuration management tool.

**Other details that may be helpful:**
I've checked the API docs and CLI, but haven't found a way to configure Rancher server authentication. Also tried RKE and Helm chart for Rancher, but they don't have that option as well.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): latest
- Installation option (single install/HA): Any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): N/A
- Machine type (cloud/VM/metal) and specifications (CPU/memory): N/A
- Kubernetes version (use `kubectl version`): N/A

- Docker (use `docker info`): N/A

**Comment by superseb** [comment]
There is no logic in the UI, it's just a frontend to the API, see https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-automate-task-x-in-rancher

We also have a Work In Progress for a terraform provider here: https://github.com/rancher/terraform-provider-rancher2

For local auth, we use that in our quickstart which can be found here: https://github.com/rancher/quickstart/
