### ISSUE TITLE
Failed to connect to proxy WSS Error on cattle-cluster-agent - AWS EKS Import

### ISSUE THREAD

**Issue by brianelliott-wt** [rancher/rancher#16348]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Import EKS cluster into Rancher container outside of AWS
2. Check logs on `cattle-cluster-agent` pod for `wss` errors

**Result:**
Cattle-System pods report `wss` error:
```
level=info msg="Connecting to wss://rancher.example.com/v3/connect/register with token zhjvh97mmhwmnd4wsqlq9hj4qz8jbtw9jmrs75rw57bsnn4tl42k24"
level=info msg="Connecting to proxy" url="wss://rancher.example.com/v3/connect/register"
level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

Import cluster on Rancher reports:

```
This cluster is currently Pending; areas that interact directly with it will not be available until the API is ready.

Waiting for full cluster configuration
```

**Other details that may be helpful:**
- Private network connected to AWS using a mesh network via Meraki network device
- Private DNS server was given to the cattle pods:

``` 
      dnsPolicy: "None"
      dnsConfig: 
        nameservers:
          - 192.168.143.90
```

- All ports are open between AWS and local private network

**Environment information**
- Rancher version: *rancher/rancher:master*
- Installation option: *single install*
- VPN Mesh
- Local DNS
- CA signed chained certs

**Cluster information**
- Cluster type: *Imported*
- Machine type: *Cloud - AWS EKS* 
- specifications (CPU/memory): *AWS t2.medium*
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-06-06T00:44:24Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`) from Rancher machine:

```
Containers: 26
 Running: 1
 Paused: 0
 Stopped: 25
Images: 9
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-138-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859GiB
Name: cypress
ID: WTYE:3YBD:7NXV:K7GT:VJ77:X35C:LRRU:QSR6:HNBW:Z4KF:OD3X:6EKN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

---

I am not sure why I get the `wss` error, everything seems to be configured correctly, but its possible I am missing something on my end.  No other `wss` issues seemed to fix my issue or have the same issue as me with AWS EKS Imports.

**Comment by superseb** [comment]
Please don't use `master` builds, these are for internal testing purposes. Also, we can't know what you are actually running if you only say `master`. Latest released version is `v2.1.1`.

Does it work without the all the network components in between? Probably the easiest way to rule out possible causes.

**Comment by brianelliott-wt** [comment]
@superseb good catch, I was using master to try and see if it solved a few other errors I was getting but it wasn't related and I had not reverted back to a "stable" version yet.  I reverted back to v2.1.1 this morning and will test with that release.

Removing the network components isn't a super simple process in my current environment, so I will attempt to set up another example in a different environment and test there.

I imagine, and originally thought, that the VPN mesh devices could be causing this, but I am not seeing anything in their logs that would indicate they are messing up the secure socket connection.

**Comment by mpostument** [comment]
Have the same issue on rancher 2.0.8 and 2.1.1

**Comment by superseb** [comment]
@mpostument Can you please describe the (network) environment

**Comment by brianelliott-wt** [comment]
Just re-launched rancher/rancher:v2.1.1 on the same machine I was using before, and re-deployed the cattle-system resources after deleting them.  Seems like everything is working now 👍 

Logs below:
```
>$ kubectl logs cattle-cluster-agent-8657fbf8f-sd825 --namespace cattle-system
INFO: Environment: CATTLE_ADDRESS=10.100.30.216 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-8657fbf8f-sd825 CATTLE_SERVER=https://rancher.example.com
INFO: Using resolv.conf: nameserver 172.20.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
INFO: https://rancher.example.com/ping is accessible
time="2018-10-30T15:55:44Z" level=info msg="Rancher agent version v2.1.1 is starting"
time="2018-10-30T15:55:44Z" level=info msg="Connecting to wss://rancher.example.com/v3/connect/register with token fpmmxjn9k2mmhc5tldsqvvbltl7zrkv2wdqx7b5qzzlnl5gw7ld7ht"
time="2018-10-30T15:55:44Z" level=info msg="Connecting to proxy" url="wss://rancher.example.com/v3/connect/register"
time="2018-10-30T15:55:44Z" level=info msg="Listening on /tmp/log.sock"
```

This issue can be closed for now. Thanks for troubleshooting my mistakes with me 😉

**Comment by superseb** [comment]
@brianelliott-wt Cool. If anything changed in your setup, please let me know as that could be helpful to pin down in other cases.

@mpostument Please file a new issue with your environment details (see issue template)

**Comment by mpostument** [comment]
@superseb issue was in dns, there were 3 dns servers, two private and on google. After removing google dns issue was resolved

**Comment by Huixxi** [comment]
https://github.com/rancher/rancher/issues/22063#issuecomment-859926251 I referenced this and patched the code that make the rancher-agent follow the local /etc/resolve.cnf then solved my problem, maybe you should replace the ip
with your own public ip.
