### ISSUE TITLE
nginx-proxy has a very low setting for proxy_timeout

### ISSUE THREAD

**Issue by cristifalcas** [rancher/rancher#16341]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
```
docker exec nginx-proxy sh -c "cat /etc/nginx/nginx.conf"
    error_log stderr notice;
    
    worker_processes auto;
    events {
      multi_accept on;
      use epoll;
      worker_connections 1024;
    }
    
    stream {
            upstream kube_apiserver {
                
                server 172.21.4.12:6443;
                
                server 172.21.4.4:6443;
                
                server 172.21.4.5:6443;
                
            }
    
            server {
                listen        6443;
                proxy_pass    kube_apiserver;
                proxy_timeout 5;
                proxy_connect_timeout 2s;
    
            }
    
    }
```

**Result:**
Because all connections to the k8s cluster are made through that nginx-proxy, they all timeout after 5 seconds of inactivity: kubectl exec/get, UI shell connections, helm commands.

**Other details that may be helpful:**
In a recent PR it looks like that was increased to 30 seconds. This is still way to low for watchers or for helm installs (which can take a lot longer then 30s). If a helm install gets terminated because of that timeout, the chart will fail, with unpredictable results(partial installs that are not recognized at the next try and other funky stuff).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.0.8
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
metal
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
root@dear-crane:~# docker info
Containers: 44
 Running: 34
 Paused: 0
 Stopped: 10
Images: 67
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 493
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 47.15 GiB
Name: dear-crane
ID: NSSI:PR5Z:35ZX:DRZK:QJEQ:C6YE:EA4G:FDAM:GYBD:FC2U:D66T:64TD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by superseb** [comment]
It was raised in https://github.com/rancher/rancher/issues/14971, please provide examples of when you encounter failing connections that we can use to reproduce.

**Comment by cristifalcas** [comment]
I'll continue the discussion there.
