### ISSUE TITLE
Rancher Upgrade - Imported Cluster stuck Provisioning

### ISSUE THREAD

**Issue by B3DTech** [rancher/rancher#16343]
We just upgraded to rancher 2.1.1 last week from 2.0.7.  Everything went fine, except for one cluster.

We have two imported K8S clusters (v1.10.3) that were created "the old fashioned" way pre-Rancher.  We had them imported in Rancher and they were working great before the upgrade.  After the upgrade, one is perfectly fine, the other is stuck at:

> This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Exit status 1, Error from server (ServiceUnavailable): the server is currently unable to handle the request

Looking at the Rancher Cattle System Node Agent container logs, I see:

> time="2018-10-25T20:17:15Z" level=info msg="Connecting to wss://rancher.internal.ieeeglobalspec.com/v3/connect with token 8hnx69trlxw8jdbdpsvh8qxn6vd2cxnl8ghw29b4zcdphl272thpfv"
time="2018-10-25T20:17:15Z" level=info msg="Connecting to proxy" url="wss://rancher.internal.ieeeglobalspec.com/v3/connect"
time="2018-10-25T20:17:15Z" level=error msg="Failed to connect to proxy" error="dial tcp 10.85.160.67:443: getsockopt: connection refused"
time="2018-10-25T20:17:15Z" level=error msg="Failed to connect to proxy" error="dial tcp 10.85.160.67:443: getsockopt: connection refused"
time="2018-10-25T20:17:25Z" level=info msg="Connecting to wss://rancher.internal.ieeeglobalspec.com/v3/connect with token 8hnx69trlxw8jdbdpsvh8qxn6vd2cxnl8ghw29b4zcdphl272thpfv"
time="2018-10-25T20:17:25Z" level=info msg="Connecting to proxy" url="wss://rancher.internal.ieeeglobalspec.com/v3/connect"
time="2018-10-25T20:17:25Z" level=info msg="Starting plan monitor"
INFO: Environment: CATTLE_ADDRESS=10.85.164.229 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=64a3b07463dd6c9de3b93faaf5711d37468e0ef7b17528be3ca39ae7054cdb05 CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=dp-cs-uat-m01.internal.ieeeglobalspec.com CATTLE_SERVER=https://rancher.internal.ieeeglobalspec.com
INFO: Using resolv.conf: nameserver 10.85.128.6 nameserver 10.85.128.5 nameserver 10.85.136.5 search internal.ieeeglobalspec.com
INFO: https://rancher.internal.ieeeglobalspec.com/ping is accessible
INFO: Value from https://rancher.internal.ieeeglobalspec.com/v3/settings/cacerts is an x509 certificate
time="2018-10-29T15:19:04Z" level=info msg="Rancher agent version v2.0.7 is starting"
time="2018-10-29T15:19:04Z" level=info msg="Option worker=false"
time="2018-10-29T15:19:04Z" level=info msg="Option requestedHostname=dp-cs-uat-m01.internal.ieeeglobalspec.com"
time="2018-10-29T15:19:04Z" level=info msg="Option customConfig=map[internalAddress: roles:[] label:map[] address:10.85.164.229]"
time="2018-10-29T15:19:04Z" level=info msg="Option etcd=false"
time="2018-10-29T15:19:04Z" level=info msg="Option controlPlane=false"
time="2018-10-29T15:19:05Z" level=info msg="Listening on /tmp/log.sock"
time="2018-10-29T15:19:05Z" level=info msg="Connecting to wss://rancher.internal.ieeeglobalspec.com/v3/connect with token 8hnx69trlxw8jdbdpsvh8qxn6vd2cxnl8ghw29b4zcdphl272thpfv"
time="2018-10-29T15:19:05Z" level=info msg="Connecting to proxy" url="wss://rancher.internal.ieeeglobalspec.com/v3/connect"
time="2018-10-29T15:19:05Z" level=info msg="Starting plan monitor"

It wasn't communicating to Rancher after the upgrade, so I restarted the container.  Now it isn't complaining about communication with Rancher, but it's still saying is "provisioning"

Not too sure where to go from here.

**Comment by loganhz** [comment]
Are you using Rancher HA setup? 
https://github.com/rancher/rancher/issues/16012

**Comment by MaxDiOrio** [comment]
Nope. Single server install for now.

**Comment by MaxDiOrio** [comment]
I deleted the cluster and re-added it, now it's waiting for api.

I feel that the agents never were removed from the cluster, but I can't manually remove them either. The containers restart after removing them. Even after setting them to only restart unless stopped.

**Comment by dramich** [comment]
@MaxDiOrio It sounds like your cluster is in a bit of a dirty state so I would suggest cleaning it up and trying to reimport it. First, delete the imported cluster from the UI, then head [here](https://rancher.com/docs/rancher/v2.x/en/admin-settings/removing-rancher/user-cluster-nodes/#imported-cluster-nodes) and click on the `By Script` tab. This will run a cleanup on the cluster removing some Rancher related things as seen in the table at the top.  Add the `-dry-run` flag to see what items would be deleted/modified if you are curious.

By deleting and reimporting there are annotations and labels that get left around which make it so you can't reimport the cluster cleanly. 

After the script has run reimport the cluster and you _should_ be good to go.

**Comment by B3DTech** [comment]
Won't work - it's stuck:

Error from server (Forbidden): error when creating "STDIN": serviceaccounts "cattle" is forbidden: unable to create new content in namespace cattle-system because it is being terminated
Error from server (Forbidden): error when creating "STDIN": secrets "cattle-credentials-e771b6e" is forbidden: unable to create new content in namespace cattle-system because it is being terminated
Error from server (Forbidden): error when creating "STDIN": deployments.extensions "cattle-cluster-agent" is forbidden: unable to create new content in namespace cattle-system because it is being terminated
Error from server (Forbidden): error when creating "STDIN": daemonsets.extensions "cattle-node-agent" is forbidden: unable to create new content in namespace cattle-system because it is being terminated

**Comment by B3DTech** [comment]
Got it - a pod was stuck terminating in the cattle-system namespace.  Had to force it to terminate so that the rest of the cleanup could happen.  Once that was gone, I was able to re-import the cluster successfully.

Strange how things got stuck terminating.
