### ISSUE TITLE
Getting "too many open files" after adding GKE cluster

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16345]
**Steps to reproduce (least amount of steps as possible):**
1.  Add two clusters (first one was a DO cluster, second one was a GKE cluster)

**Result:**  ServerError (500) - too many open files
![image](https://user-images.githubusercontent.com/11514927/47672359-0c5bdd80-db6f-11e8-950f-c2d105a2abec.png)

**Environment information**
Version - 2.2 master 10/29

**Comment by loganhz** [comment]
Link to another `too many open files` issue https://github.com/rancher/rancher/issues/14987

**Comment by cjellick** [comment]
@tfiduccia to help reproduce, can you share information about your OS and how you installed docker?

**Comment by cjellick** [comment]
Ive asked @tfiduccia to retest just to see if its still occuring. im going to assign over just so she doesnt forget

**Comment by tfiduccia** [comment]
Version - master 1/23
Verified fixed.  I don't get this box anymore.
