### ISSUE TITLE
Backport: Pipeline crash causing "boot loop" on rancher/rancher:latest when pushing to ECR

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16351]
Backport for https://github.com/rancher/rancher/issues/16187

**Comment by loganhz** [comment]
Commit for it https://github.com/rancher/rancher/pull/16197/commits

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc3
rancher/rancher:master

* Created rancher server & cluster
* Created ECR registry
* Enabled pipeline
* In pipeline config, add steps to build and push to an ECR registry
* Run pipeline

Push step runs without crashing
