### ISSUE TITLE
Need new helm repo  for alpha rancher server images

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16353]
We currently have two helm repos for rancher server: stable and latest. Latest contains every official non-rc release. Stable contains every release that gets "promoted" from latest.

We need to introduce a third channel for our upcoming alpha releases.

### Concerning versioning
The chart version for our server chart follows the pattern `<year>.<month>.<build number that starts at zero each month>`.
Alpha release should follow the same versioning scheme and should get their build numbers from the same "pool" as latest and stable. A release will NEVER be promoted from alpha to stable. So, if a build number is used in the alpha channel, we should never see it in the latest or stable channels.

### Concerning automation
We need new/different automation to accommodate the building and publishing of alpha releases.

Automated builds are triggered off of git tags. The builder needs to be able to distinguish between stable, latest, and alpha release because each one has a different release process. To accomplish this, alpha releases should be tagged with a `-alpha` suffix. So, the tag should look like `2018.11.2-alpha`. The automation should key off of the `-alpha` to know that it needs to build the chart and publish it to the alpha channel. The actual version specified in the chart.yaml file should omit the suffix, ie `2018.11.2`.

**Comment by cjellick** [comment]
The name of the repo shall be `alpha`

**Comment by cloudnautique** [comment]
There is a helm repo called alpha. Items will be published to the alpha channel, when tagged with:
`<rel>-alpha` and pushed to master.

**Comment by bmdepesa** [comment]
Installing from server-chart:master was successful, with rancher/rancher:master image.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.0-alpha2
rancher-alpha/rancher 2018.12.2 chart

Installed from alpha repo & chart successfully. 

```
helm repo add rancher-alpha https://releases.rancher.com/server-charts/alpha
helm repo update
helm install rancher-alpha/rancher \
  --name rancher \
  --namespace cattle-system \
  --set hostname=<host>
```
