### ISSUE TITLE
Alternative to dynamically build a new cluster and deploy to it

### ISSUE THREAD

**Issue by bvhoang2003** [rancher/rancher#16352]
We need to spin up new clusters on-demand and deploy builds there to run as a one-time deal. The cluster and worker nodes will tear down after it is completed. The reason is, it requires super huge nodes (GPU level) to run for hours for each run. We do not want to keep the clusters running with huge nodes as wasteful resources with preset clusters.

Currently, we have an automation to build a cluster with new nodes and join to the cluster dynamically using Rancher API and automation.

The problem is rancher CLI is used to run the rancher kubernetes deployment. 
- First of all, rancher CLI requires preset context using "rancher context switch" to deploy with "rancher kubectl". Switching context would switch all pipelines concurrent on the CI runners. Only the on-demand cluster needs to go to a new context.
- There is no clean way to switch context cleanly from rancher CLI. "rancher context switch" is an interactive command. To lookup the new context as a script would require and interactive mode. A simple context list option would be helpful. I also tried "rancher project ls" which only list current context, and "rancher clusters" which does not provide project_id to switch context.

What would be the best alternative to create new clusters on demand, deploy application to new cluster, run, and then tear down?

**Result:**

**Other details that may be helpful:**
   None

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
  * rancher version v2.0.2
  * rancher/rancher version 2
- Installation option (single install/HA):
  * Both singleton and HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
   * Cloud
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):
```
Docker version 17.12.1-ce
Containers: 20
 Running: 0
 Paused: 0
 Stopped: 20
Images: 66
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-14.33.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.798GiB
Name: ip-10-101-1-15
ID: VCQW:5ZDI:3ZZZ:7CJV:7CIF:QO6R:JOW2:CSZN:RQBS:ENMX:CF5D:5RE2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 32
 System Time: 2018-10-29T23:12:24.7121145Z
 EventsListeners: 0
HTTP Proxy: http://proxy.ext.ray.com:80
HTTPS Proxy: http://proxy.ext.ray.com:80
No Proxy: rancher4-singleton,10.101.1.226
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 10.101.1.226:5000
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by superseb** [comment]
Thanks for the report. I believe both issues are addressed in https://github.com/rancher/rancher/issues/15692

**Comment by bvhoang2003** [comment]
Can I run the "rancher context switch" just to grab the list w/out the prompt? I am doing everything from a fully automated aspect, hoping to not require to be in interactive mode to select a context manually.
