### ISSUE TITLE
"(Custom)" tag on rbac rules is wrong

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16355]
If a role has a rule where there is more than one resource defined, the UI tags the resource as "custom" even though it isnt. See `templates,templateverions` in the following:
![custom-issue](https://user-images.githubusercontent.com/2473240/47690143-24048780-dbaa-11e8-9a2b-d62dc46e61f6.png)

**Comment by vincent99** [comment]
We've always created entries with one resource each because there's not a great way to represent multiple.  The value is "these two resources", which is not a standard choice, so it's a "custom" value.

**Comment by loganhz** [comment]
I think API should return two records for `templates` and `templateversions`
Then UI will not show it as custom
