### ISSUE TITLE
Failed to remove clusters from Rancher GUI

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16350]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
step1: Run rancher server with image ***rancher/rancher:master***, I hosted one on DO, one on GCP 
step2: Add new clusters from different providers, in my case I tried DO, AWS, and GKE
step3: After clusters are active, do something work, then remove those clusters

**Result:**
Clusters are not removed correctly, their status are stuck on ***removing***, clicking on their names causes ***503 error***. 
  

**Other details that may be helpful:**
On DO/AWS/GCP dashboards, those instances are not destroyed at all.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:maste 10/29
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted, Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```
<img width="1609" alt="remove-bug1" src="https://user-images.githubusercontent.com/6218999/47682592-1ccd8180-db8a-11e8-8c28-ef5e39ca9160.png">
<img width="1633" alt="remove-bug2" src="https://user-images.githubusercontent.com/6218999/47682595-1fc87200-db8a-11e8-9a3c-a3b4263a2099.png">

**Comment by cjellick** [comment]
@jiaqiluo does this reproduce consistently?

**Comment by jiaqiluo** [comment]
@cjellick It is not reproducible anymore. I think it used to happen in some rare condition and it has been fixed in the mater. The ticket can be closed.
