### ISSUE TITLE
The Resource quotas  display error when editing the namespace 

### ISSUE THREAD

**Issue by dongjuanwinhong** [rancher/rancher#16364]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1.add a project
![image](https://user-images.githubusercontent.com/39041059/47703268-afd5ec80-dc5a-11e8-9fd3-834f49e9d488.png)
2.add a namespace
![image](https://user-images.githubusercontent.com/39041059/47703337-e449a880-dc5a-11e8-9719-16e081fd1d59.png)
3.edit this namespace

**Result:**

as shown,the other namespaces is a,but there is only one namespace actually.

![image](https://user-images.githubusercontent.com/39041059/47703374-06dbc180-dc5b-11e8-93ae-a749e3283591.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by rustymunkey** [comment]
I can confirm this issue. In addition, the UI prevents you from increasing the quotas, if the "other" workspaces takes up the remaining resources.
Thus, if you have one namespace using half the resources, you cannot increase the quotas for this namespace in the UI.

**Comment by myclau** [comment]
same issue on v2.1.1 install from helm

**Comment by loganhz** [comment]
Thanks for the report
Fixed in https://github.com/rancher/ui/pull/2408
It will be out in v2.2
