### ISSUE TITLE
UI: Cancreating namespace with a resource quota set to zero

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#16367]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a project with the resource quota for Service Load Balancers set to Zero (in order to disable that resource)
2. Navigate to > New project > Namespaces in the UI and click on Add Namespace
3. Specify the namespace name and leave the limit for the Service Load Balancers resource at zero
4. Click Create

**Result:**
Namespace fails to be created.
Error:
> Services Load Balancers limit is required.

**Other details that may be helpful:**
This is a UI bug, as the namespace is created successfully when invoking the API directly.

**Environment information**
- Rancher version v2.1.1

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/16368
