### ISSUE TITLE
UI: Failure to create namespace when resource quota is set to zero

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#16368]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a project with the resource quota for Service Load Balancers set to Zero (in order to disable usage of that resource)
2. Navigate to > New project > Namespaces in the UI and click on Add Namespace
3. Specify the namespace name and leave the limit for the Service Load Balancers resource at zero
4. Click Create

**Result:**
Namespace fails to be created.
Error:
> Services Load Balancers limit is required.

**Other details that may be helpful:**
- This is a UI bug, as the namespace is created successfully when invoking the API directly.
- It's not limited to the Service Load Balancers resource.
- Same issue exists when editing an existing namespace in the UI and trying to change a resource quota to zero.

**Environment information**
- Rancher version v2.1.1

**Comment by davidnuzik** [comment]
Version: 2.2 Master (11/26)
Confirmed fixed. Was able to create the namespace with the limit of 0 on servicesLoadBalances set by the project. Validated POST request payload and server response.
