### ISSUE TITLE
Make k8s v1.12 default K8s version.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16362]
Rancher server version - v2.1.2-rc1

k8s v1.11.3 is still presented as default K8s version when provisioning clusters using UI / API .

Make k8s v1.12 default K8s version.

**Comment by sangeethah** [comment]
Tested with rancher server version - v2.1.2-rc2

k8s v1.12.1 still presented as default K8s version when provisioning clusters using UI / API .

**Comment by alena1108** [comment]
Removed `resolved` label as we rolled back to having k8s 1.11.3 as default
