### ISSUE TITLE
Can't deploy coredns from helm

### ISSUE THREAD

**Issue by rpelissi** [rancher/rancher#16377]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Install rancher 2.10 on a node, then try to deply coredns 1.1.1 from helm using the webgui

**Result:**
Got this error:
Failed to install app coredns-xcsdx. Error: release coredns-xcsdx failed: Deployment.apps "coredns-xcsdx-coredns" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"coredns-xcsdx-coredns", "k8s-app":"coredns", "release":"coredns-xcsdx"}: `selector` does not match template `labels` 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher 2.10
Installed one 2 node system (one is worker, etcd, control pane, the other one is a worker only node)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

1.11.3

```
(paste the output here)
```

- Docker (use `docker info`):
17.3.2

```
(paste the output here)
```

**Comment by codekoala** [comment]
This was a problem with the helm chart itself. It's resolved with stable/coredns 1.1.3.

https://github.com/helm/charts/pull/7736
