### ISSUE TITLE
Logger UI Hides SSL Fields Until `https` Scheme is Entered

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#16374]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Open Elasticsearch Logger UI

**Result:**
No SSL config fields are visible

The SSL config fields shouldn't be hidden from the user and then displayed when we enter the correct schema. The fields should be disabled until the right schema is entered with a small note that they will only be available when `https` is used.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/29/19)
The SSL fields do not show as editable until you enter https in the url endpoint field for elasticsearch, splunk, and syslog (select tcp). There is helptext to indicate that you must enter https:// or select TCP (Syslog).
