### ISSUE TITLE
pipeline occured  t.linkFor is not a function

### ISSUE THREAD

**Issue by LGTH** [rancher/rancher#16376]
*Describe your issue here*

When I enter the  pipeline from the menu, then  It show me message below:

>  t.linkFor is not a function
> Reload to try again or log out

It must come up every time. If I log out and log in again, it has no problem.
But when I delete pipeline, and install again, it not occur, I don't know is it a problem?
 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.18` Cattle: `v0.183.52` UI: `v1.6.43` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
