### ISSUE TITLE
Show resolved DNS for CATTLE_SERVER in agent startup

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16386]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
We already print almost everything used on agent startup, except the resolved DNS for `$CATTLE_SERVER`. This can be useful to see if the correct addresses are returned from within the container vs what is expected.

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/27
HA install

* Deployed Rancher server
* Created cluster
* Logs for cluster and node agents show `INFO: <hostname> resolves to <ip>`
