### ISSUE TITLE
DigitalOcean provider prefix

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#16381]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a node pool with an underscore in the prefix.

**Result:**
During provision you get invalid hostname

**Other details that may be helpful:**
It seems DO doesn't allow `_` as part of the hostname, so the UI/api shouldn't allow it as part of the prefix

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): single

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/4/19)
Confirmed fix. The UI no longer allows you to create a digital ocean node(s) starting with an _ when you attempt to do so the form is validated and you will get an "Name Prefix" can not contain "_" error.
