### ISSUE TITLE
Check for empty cacerts does not work

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16385]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
In case of a configured `CATTLE_CA_CHECKSUM` but no value at `/v3/settings/cacerts`, the check executed is `! test -s` (not zero size), but the output is actually 1 byte so it is not caught. If we catch it, we can provide a better error message (`CATTLE_CA_CHECKSUM` is set but `cacerts` is empty or anything along that line)

The current error shown in this scenario is:
```
(unable to load certificate 139659323314624:error:0906D06C:PEM routines:PEM_read_bio:no start line:../crypto/pem/pem_lib.c:691:Expecting: TRUSTED CERTIFICATE)
ERROR: Retrieved cacerts:
```

Ref https://github.com/rancher/rancher/issues/16046

**Comment by xorpierre** [comment]
can confirm on 2.1.5
problem is now my nodes don't join the cluster...

**Comment by bmdepesa** [comment]
Reproduced in v2.1.9
```ERROR: Value from https://x.x.x.x/v3/settings/cacerts does not look like an x509 certificate (unable to load certificate 140696957018560:error:0906D06C:PEM routines:PEM_read_bio:no start line:../crypto/pem/pem_lib.c:691:Expecting: TRUSTED CERTIFICATE)
ERROR: Retrieved cacerts:
```

v2.2.2-rc11
* Deploy Rancher server
* Create custom cluster
* Edited cacerts via kubectl (api is readonly) to set value to ""
* Deleted node agent pod
```
ERROR: The environment variable CATTLE_CA_CHECKSUM is set but there is no CA certificate configured at https://x.x.x.x/v3/settings/cacerts
```
