### ISSUE TITLE
System namespaces not listed under "System" project post upgrade

### ISSUE THREAD

**Issue by h3d-thanhpv** [rancher/rancher#16380]
**What kind of request is this (question/bug/enhancement/feature request): bug**

**Steps to reproduce (least amount of steps as possible):**
I have 2 clusters for dev and production
In dev cluster: all system namespace in "system" project
In product cluster: "cattle-system", "default", "ingress-nginx", "kube-public" namespaces not in a project.

![image](https://user-images.githubusercontent.com/6016904/47773027-4669e280-dd1b-11e8-9f75-022eec5d32ab.png)
![image](https://user-images.githubusercontent.com/6016904/47773079-774a1780-dd1b-11e8-8354-70f0db07bab5.png)

**Result:**
I want to all the system namespace to "system" project in production cluster (similar to dev cluster)

**Other details that may be helpful:**
I upgraded rancher server in several times. From 2.0.2 -> 2.0.6 -> 2.0.8 -> 2.1.1

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom (dev and production)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud (dev and production)
- Kubernetes version (use `kubectl version`):  v1.11.3 (dev and production)
![image](https://user-images.githubusercontent.com/6016904/47770121-c50d5280-dd10-11e8-84e8-ad7ee10111a7.png)
![image](https://user-images.githubusercontent.com/6016904/47770199-0dc50b80-dd11-11e8-8520-3fd9713756c8.png)
Product cluster:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
Dev cluster:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

Product cluster
```
Containers: 129
 Running: 78
 Paused: 0
 Stopped: 51
Images: 36
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-127-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: ...
Total Memory: ... GiB
Name: .......
ID: ....
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
Dev cluster:
```
Containers: 223
 Running: 111
 Paused: 0
 Stopped: 112
Images: 571
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1680
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-134-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: ...
Total Memory: ... GiB
Name: ....
ID: ....
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by h3d-thanhpv** [comment]
I find other issue about that #14995, but it doesn't help

**Comment by loganhz** [comment]
Can you try to move them to system project manually? You can do it via UI.

**Comment by h3d-thanhpv** [comment]
Sorry, but this is the production cluster, so I dared not move those namespaces into the system project

**Comment by h3d-thanhpv** [comment]
@loganhz can you explain the mechanism of moving some namespaces into the system project?

**Comment by h3d-thanhpv** [comment]
I tried move manually, it worked. Thanks for your help!
