### ISSUE TITLE
Cron Job Configuration not saving

### ISSUE THREAD

**Issue by nloui** [rancher/rancher#16390]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create new cron job
- Enter "1" for each of the settings in Job configuration
- Save
- Click the new Workload

**Result:**
- All say "n/a"

**Other details that may be helpful:**
Expected result: they should say 1

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA):
sibngle install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
I cannot reproduce this issue in v2.1.1
Is there any step I missed?

1. Click Deploy 
2. Select `Run on a cron schedule`
3. Input 1 for `Completions`, `Parallelism`, `Back Off Limit` and `Active Deadline Seconds`
4. Click Save
5. Go to cronjob detail page to check the value of `Completions`, `Parallelism`, `Back Off Limit` and `Active Deadline Seconds`

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by niccontrerasf** [comment]
v2.3.6 same behavior, even editing yml, values are not preserved

**Comment by cardamo** [comment]
Got the same issue in 2.3.5. Steps to reproduce:
1. Create a CronJob *without changing* anything in Job Configuration section.
2. Edit the created CronJob and set some fields in Job Configuration (parallelism for example), click Save.
3. Open the CronJob details or edit again - values set on step 2 are not saved.

If any of Job Configuration values est upon CronJob creation, then they are editable further on. 
Also, if `parallelism` (and perhaps any other relevant field) is changed in yaml (.spec.jobTemplate.spec.parallelism) then the problem goes away.

@loganhz could you test this scenario and reopen this issue?

**Comment by metsis** [comment]
Still experiencing this in 2.3.8.
