### ISSUE TITLE
nodes ip addresses go missing when using k8s 1.11.x

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16393]
Ticket to track the upstream issue: https://github.com/kubernetes/kubernetes/issues/68270

**Comment by alena1108** [comment]
Here is an upstream PR for getting the fix into k8s 1.11: https://github.com/kubernetes/kubernetes/pull/70154. Open as of now, looks like it's targeted for v1.11.6

**Comment by jiaqiluo** [comment]
Validated # 1 on master 1/4
Steps:
- ran Rancher server versionmaster 1/4 (single Install)
- Ran test scrips on three clusters:
   - Ubuntu 16.04 docker 17.03.2-ce, k8s 1.11.6
- Tests cover the following areas:
   - workload
   - dns
   - rbac
   - communication
   - ingress
   - secret
   - registry
   - service discovery

Validated # 2 on v2.1.5-rc3 which is derived from master 1/2
Steps:
- ran Rancher server version v2.1.5-rc3 (single Install)
- Ran test scrips on three clusters:
   - Ubuntu 16.04 docker 17.03.2-ce, k8s 1.11.6
   - RancherOS 1.4.2 docker 17.03.2-ce, k8s 1.11.6, 1 control plane, 1 etcd, and 3 workers
   - Rhel 7.5, native docker 1.13 with selinux enabled, k8s 1.11.6, 1 control plane, 1 etcd, and 3 workers
- Tests cover the following areas:
   - workload
   - dns
   - rbac
   - communication
   - ingress
   - secret
   - registry
   - service discovery
