### ISSUE TITLE
Backport: Site Access configured for an auth provider should not restrict local user login

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16399]
Backport https://github.com/rancher/rancher/issues/15113

**Comment by sangeethah** [comment]
Tested with rancher server version - v2.1.2-rc8

Local users (Standard User/Admin) are allowed to access rancher-server when auth (other than local) is enabled and "Site Access" is set to "Allow members of Clusters, Projects, plus Authorized Users and Organizations" / "Restrict access to only Authorized Users and Organizations".
