### ISSUE TITLE
prevent web UI from opening a console in privileged containers

### ISSUE THREAD

**Issue by tobowers** [rancher/rancher#1640]
Kubernetes has a plugin which stops remote `docker exec` when acting on a privileged container. This is a pretty good security feature as otherwise you can have access to the entire host. Kubernetes has it as an optional setting when turning on the cluster.

**Comment by vincent99** [comment]
1.x: https://github.com/rancher/rancher/issues/9064
2.0: you can do whatever you want to k8s PSPs.
