### ISSUE TITLE
I can not create new cattle env. 

### ISSUE THREAD

**Issue by YeonSeoMom** [rancher/rancher#16401]
I can not create new cattle env. 
 
network-services restart every 5 seconds.

network manager made error log below.

"11/1/2018 3:35:51 PMtime="2018-11-01T06:35:51Z" level=info msg="routesync: DOCKER_BRIDGE=docker0, METADATA_IP=169.254.169.250"
11/1/2018 3:35:51 PMtime="2018-11-01T06:35:51Z" level=info msg="Listening on /tmp/log.sock"
11/1/2018 3:35:51 PMtime="2018-11-01T06:35:51Z" level=info msg="routesync: starting monitoring on bridge: docker0, for metadataIP: 169.254.169.250 every 60 seconds"
11/1/2018 3:35:51 PMtime="2018-11-01T06:35:51Z" level=info msg="Waiting for metadata"
11/1/2018 3:36:50 PMCreating metadata client: Get http://169.254.169.250/2016-07-29/version: dial tcp 169.254.169.250:80: getsockopt: connection refused"

Some host ipsec and scheduler time out get ip address.

How can I fix this?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by YeonSeoMom** [comment]
I have upgraded server 1.6.17, but still same errors.
Metadata container says 


11/6/2018 12:07:39 PMtime="2018-11-06T03:07:39Z" level=info msg="Registering metadata server [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:07:39 PMtime="2018-11-06T03:07:39Z" level=info msg="Registered metadata server for [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:07:39 PMtime="2018-11-06T03:07:39Z" level=info msg="Loading answers from file ./answers.json"
11/6/2018 12:08:09 PMFailed to subscribe to url [http://172.21.76.70:8080/v1]: Get http://172.21.76.70:8080/v2-beta/schemas: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
11/6/2018 12:08:11 PMtime="2018-11-06T03:08:11Z" level=info msg="Registering metadata server [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:08:11 PMtime="2018-11-06T03:08:11Z" level=info msg="Registered metadata server for [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:08:11 PMtime="2018-11-06T03:08:11Z" level=info msg="Loading answers from file ./answers.json"
11/6/2018 12:08:41 PMFailed to subscribe to url [http://172.21.76.70:8080/v1]: Get http://172.21.76.70:8080/v2-beta/schemas: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
11/6/2018 12:08:43 PMtime="2018-11-06T03:08:43Z" level=info msg="Registering metadata server [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:08:43 PMtime="2018-11-06T03:08:43Z" level=info msg="Registered metadata server for [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:08:43 PMtime="2018-11-06T03:08:43Z" level=info msg="Loading answers from file ./answers.json"
11/6/2018 12:09:13 PMFailed to subscribe to url [http://172.21.76.70:8080/v1]: Get http://172.21.76.70:8080/v2-beta/schemas: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
11/6/2018 12:09:15 PMtime="2018-11-06T03:09:15Z" level=info msg="Registering metadata server [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:09:15 PMtime="2018-11-06T03:09:15Z" level=info msg="Registered metadata server for [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:09:15 PMtime="2018-11-06T03:09:15Z" level=info msg="Loading answers from file ./answers.json"
11/6/2018 12:09:45 PMFailed to subscribe to url [http://172.21.76.70:8080/v1]: Get http://172.21.76.70:8080/v2-beta/schemas: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
11/6/2018 12:09:46 PMtime="2018-11-06T03:09:46Z" level=info msg="Registering metadata server [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:09:46 PMtime="2018-11-06T03:09:46Z" level=info msg="Registered metadata server for [8FFCB447C8C7AC171806] with url [http://172.21.76.70:8080/v1]"
11/6/2018 12:09:46 PMtime="2018-11-06T03:09:46Z" level=info msg="Loading answers from file ./answers.json"

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
