### ISSUE TITLE
Rancher 2 backups on GKE

### ISSUE THREAD

**Issue by bluemalkin** [rancher/rancher#16400]
GKE is self-managed with the etcd cluster "invisible" and inaccessible to us.

I find it hard to believe that there is no way to backup Rancher v2 data running on GKE. There will be cases where the cluster needs to be re-created. 

Are there any plans to backup data or any tools we can use ?

Thanks

**Comment by bradjones1** [comment]
I believe this could (?) be accomplished by exporting the various custom resource entries created by Rancher, and then importing them on recovery? Could this theoretically be used to move Rancher to a different cluster entirely?

**Comment by deniseschannon** [comment]
Rancher hasn't been tested or supported to run on other Kubernetes clusters except for RKE. We have a ticket to investigate it, but the main issue is getting the backups from the hosted k8s providers. 

Closing in favor of : https://github.com/rancher/rancher/issues/16627
