### ISSUE TITLE
Backport : cannot get revisions when creating and updating a workload 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#16409]
Backport : https://github.com/rancher/rancher/issues/16408

**Comment by jiaqiluo** [comment]
The bug is fixed on v2.1.2-rc4. 

Reproduced the bug on v2.1.2-rc3
Validated on v2.1.2-rc4
For detailed procedures and results: https://github.com/rancher/rancher/issues/16408#issuecomment-436029746
