### ISSUE TITLE
Backport: Use recommended admission controllers for clusters

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16404]
Backport: https://github.com/rancher/rancher/issues/16312

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc7

* Created DO cluster through Rancher
* ssh to node and run `docker logs kube-apiserver | grep --enable-admissions-plugins`

Validated the default admission plugins match:
```
--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
```
