### ISSUE TITLE
UI: let user to configure etcd snapshots for RKE clusters

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16414]
We should enable etcd snapshot configuration for 2.1.x in the UI. Here are the 3 parameters we have to let user configure (@galal-hussein would update types to provide some meaningful defaults, but assume that `snapshot` would be set to `true` by default)

https://github.com/rancher/types/blob/325dce50b65029b88f561ef2788419799ebf921e/apis/management.cattle.io/v3/rke_types.go#L181
https://github.com/rancher/types/blob/325dce50b65029b88f561ef2788419799ebf921e/apis/management.cattle.io/v3/rke_types.go#L183
https://github.com/rancher/types/blob/325dce50b65029b88f561ef2788419799ebf921e/apis/management.cattle.io/v3/rke_types.go#L185

**Comment by tfiduccia** [comment]
version - 2.2 master 11/14
Verified fixed
