### ISSUE TITLE
Keys and session token should be required in delete modal

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16418]
Version - 2.1.2-rc2

**Steps to reproduce (least amount of steps as possible):**
1.  Create a EKS cluster with a session token
2.  After it's active, click on delete menu option
3.  Click on "Update keys"

**Result:**  The modal closes and the standard delete modal comes up.  This allows you to delete the cluster from Rancher without session keys.  But cluster and such still exist in AWS, so no cleanup happens.  These keys should be required.

**Comment:** I think this is both a UI and API issue?

**Comment by cjellick** [comment]
I think, depending on how we address this, it would also address https://github.com/rancher/rancher/issues/16424.
Here is what I am envisioning. @vincent99 what do you think?
1. Add validation such that doing a http DELETE on cluser that was created via temp tokens FAILS with Method Not Allowed
2. Add an action called deleteWithCredentials or deleteWithToken to clusters created via temp tokens
3. In this action, to help ensure that the keys work, we could make some API request (to get the cluster maybe?) with the supplied credentials

**Comment by vincent99** [comment]
That feels very backwards to me, and counterproductive to the other work going on moving credentials to their own resource.  I ultimately want to be able to prompt the user enter their credentials once (per day or whatever) and then have things like bulk actions and API delete work like normal, not have super special actions for manipulating everything that can touch AWS...

**Comment by westlywright** [comment]
For QA: When deleting an eks cluster with a session token we will now check that you can list the clusters with the newly entered keys before we actually delete the cluster.

**Comment by westlywright** [comment]
This is in master and will be available to 2.1.x in ui tag: `2.1.8`

**Comment by tfiduccia** [comment]
Version - 2.1.2 rc7 & master
Verified fixed
