### ISSUE TITLE
UI: Add option for selecting node image for a node pool in GKE

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#16412]
Related Issue: https://github.com/rancher/rancher/issues/16411

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/13/19)
Confirmed enhancement. You can now pick the Image Type for your nodes in the node pool. This is a drop-down in the UI in the Nodes section when configuring GKE for cluster creation/edit.

![image](https://user-images.githubusercontent.com/45179589/52733927-36e86f80-2f81-11e9-972c-ad5aca3f8f9c.png)

In the API this is imageType under googleKubernetesEngineConfig and I validated that I can create/edit this without issue (change image type for edit). I first picked Ubuntu for creation and then Container optimized "COS" for my edit of the cluster.

Validated in the Google Cloud web console that the image is correct (creation with ubuntu and changed upon new selection. Note that COS is still ubuntu for GKE so when we look in GKE console and node template details it's still ubuntu but API/http looks correct.
