### ISSUE TITLE
Backport: UI: let user to configure etcd snapshots for RKE clusters

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16415]
Backport for https://github.com/rancher/rancher/issues/16414

**Comment by westlywright** [comment]
This is available in ui tag: `2.1.8`

**Comment by tfiduccia** [comment]
Version 2.1.2-rc7
Setting this seems to work, but as soon as I set it looks like it's switching back.  The post headers and preview show false, but the API for the cluster shows true.  Not sure if this backend or frontend.

**Comment by alena1108** [comment]
Should be fixed in rancher/rancher:v2.1.2-rc8

**Comment by tfiduccia** [comment]
Version - 2.1.2-rc8
Verified fixed
