### ISSUE TITLE
Add option for selecting node image for a node pool in GKE

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#16411]
This requires an API endpoint in order to display options to the user.

Took this one issue out of https://github.com/rancher/rancher/issues/14299

**Comment by jiaqiluo** [comment]
The enhancement is validated on rancher: master 2/13
Rancher HA setup

Steps:
- add  two GKE cluster
- choose different OS image for those two clusters

Result:
Two GKE clusters using different OS images are provisioned successfully.
