### ISSUE TITLE
Enhance audit log message

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#16426]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature

**Steps to reproduce (least amount of steps as possible):**
enable audit function in Rancher 2.1.1

**Result:**

{"auditID":"747d4fba-5516-403c-96f3-9dbe92453d2e","requestURI":"/v3/project/local:p-k22fw/workloads?limit=-1\u0026sort=name","sourceIPs":["10.1.1.2"],"user":{"name":"user-p5rcm","group":["system:authenticated"]},"verb":"GET","stage":"RequestReceived","stageTimestamp":"2018-11-02 02:42:28 +0000"}

Need a way to translate 
local:p-k22fw to a real project/namespace
user-p5rcm to a real user name in local or LDAP or AD

**It would be great the actual project/namespace/username/ output to audit log file**

**Comment by Negashev** [comment]
Any upgrades?
(use adfs auth)
