### ISSUE TITLE
session keys not verified on delete

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16424]
Version - 2.1.2-rc2

**Steps:**
1.  Create a EKS cluster with a session token
2.  Wait for it to be active
3.  Select Delete from menu
4.  Put in random text in key/session token fields
5.  Click on update keys

**Result:**  Moves on to delete modal

**Comments:**
Flow for delete - Always bring up session token modal.  Enter correct info, should delete cluster from Rancher and EKS.  If session info not correct, warn user and ask if they are sure they want to delete from rancher (and they will have to manually remove from EKS)

**Comment by cjellick** [comment]
closing as the UI will do simply key validation for this case. but this exposes a broader issue, which I've opened separately: https://github.com/rancher/rancher/issues/16453
