### ISSUE TITLE
HELM can not be accessed by installing rancher

### ISSUE THREAD

**Issue by yangjia517** [rancher/rancher#16431]
hi~
I used RKE to create the rancher cluster, but I visited the page through the nginx proxy to appear 503：
![image](https://user-images.githubusercontent.com/33953118/47911431-5aa31080-ded0-11e8-8aad-fb1f12901a78.png)
Execute command view:
![image](https://user-images.githubusercontent.com/33953118/47911495-92aa5380-ded0-11e8-8079-dc494cf91630.png)
Why can't I visit rancher's home page?
Thanks！

**Comment by yangjia517** [comment]
I made my own CRT and key files produced by OpenSSL and added them：
![image](https://user-images.githubusercontent.com/33953118/47911709-254af280-ded1-11e8-9fc8-01dbf717459e.png)

**Comment by superseb** [comment]
Please use the steps in the troubleshooting sections to narrow down the cause:

https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/troubleshooting/
https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/troubleshooting/generic-troubleshooting/

**Comment by yangjia517** [comment]
> 请使用故障排除部分中的步骤缩小原因：
> 
> [https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/troubleshooting/ ](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/troubleshooting/)
> [https://rancher.com/docs/rancher/v2.x/en/installation/ha/ RKE -附加/故障/一般的故障排除/](https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/troubleshooting/generic-troubleshooting/)

The results are as follows:
![image](https://user-images.githubusercontent.com/33953118/47911892-b326dd80-ded1-11e8-98ab-dfe2779a5d0d.png)

**Comment by superseb** [comment]
Can you check the first steps in generic troubleshooting to make sure your cluster is healthy and ready?

Then to see why its stuck on `ContainerCreating` you can run:

```
kubectl -n cattle-system get events
kubectl -n cattle-system describe deploy/rancher
kubectl -n cattle-system describe pod/rancher-db6cd8bb7-hhm2s
```

If this shows nothing, you can check `docker logs kubelet` on one of your hosts.

If you are using self signed certificates, you need to add `--set privateCA=true` as described on https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#certificates-from-files-kubernetes-secret, but that shouldn't get you into this situation so there is also something else going on.

**Comment by yangjia517** [comment]
#16235
