### ISSUE TITLE
Add the ability to configure disk space for EKS nodes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#16437]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

When spinning up AWS instances, configure the disk space for the nodes in EKS.

**Comment by cjellick** [comment]
@deniseschannon  does this need first class support or can it be done via the yaml editor feature?

**Comment by deniseschannon** [comment]
I think this would be a common request, so first class support would be better as I don't think it's an "advanced" feature

**Comment by davidnuzik** [comment]
Validated in #17690
