### ISSUE TITLE
Backport: forbidden: User \"system:anonymous\" cannot get path \"/login\"

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16444]
Backport https://github.com/rancher/rancher/issues/14931

@sangeethah read https://github.com/rancher/rancher/issues/14931#issuecomment-435564217 for steps to reproduce

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc8

Reproduced in v2.0.8

* Create ALB (ensure HTTP/2 is disabled in ALB attributes)
* Deploy Rancher as a single container
* Followed steps to reproduce
  * Deployed workload
  * Get curl command to execute shell - replacing pod name w/ invalid name
  * After running curl command a few times, saw the offending error: 

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/k8s/clusters/c-z7j9j/api/v1/namespaces/default/pods/inval-7x9xd/exec\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}
```

* Deployed fresh install of 2.1.2-rc8
* Followed steps to reproduce

Did not see the offending error -- all commands returned 404 correctly.
