### ISSUE TITLE
Rancher Override/Delete the annotation of node flannel internally used to setup Vtep on the Host

### ISSUE THREAD

**Issue by ukinau** [rancher/rancher#16440]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create Cluster with RKE + OpenStack (or other VM Provider)
     -> Use flannel as a plugin
2. Add 10 nodes up to 100 nodes
3. Check annotation of all nodes if all nodes have annotation for flannel 

**Result:**
Some of the nodes missed following annotation values, which caused the problem of setting up Container Networking across nodes since flannel won't configure vtep related settings for these nodes which have not following values.

```
      flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"XXXXXXXXX"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
```

**Other details that may be helpful:**
Let me leave more background of this problem.
This bugs have been found when we noticed some of the pod are not reachable from other pods.
First of all we checked networking setting flanneld injected on all nodes and I noticed some of the node doesn't have `routes, fdb, neighbor information` for specific hosts
If flannel correctly setup VXLAN overlay network, all nodes should have the same number of `routes, fdb, neighbor information` but actually it was not. you can see following logs. just let you know this `ip r | grep 172.18` include only PodCidr and not including any other Cidr. 
And we couldn't ping to the pod living on the host which other hosts don't have `routes, fdb, neighbor information` for. 

```
[test@neww14 ~]$ date
Sat Nov  3 01:54:21 JST 2018
[test@neww14 ~]$ ip r | grep 172.18 | wc -l
22
```
```
[test@neww13 ~]$ date
Sat Nov  3 01:54:21 JST 2018
[test@neww13 ~]$ ip r | grep 172.18 | wc -l
21
```
```
[test@neww1 ~]$ date
Sat Nov  3 01:54:21 JST 2018
[test@neww1 ~]$ ip r | grep 172.18 | wc -l
24
```

And I found the reason why it is happening, because flannel use the annotation of node as a data store for their essential information to inject `routes, fdb, neighbor information` . but somehow some of the nodes have not that information. I already confirm that information have been registered first but then that annotation has been deleted after a while by rancher. This is not happening in all nodes. So I can assume there is kind of timing related bugs.

Actually I already found the case rancher would delete existing annotation around NodeController, NodeSyncer.

NodeController always check if NodeController need to set DesiredNodeAnnotations, DesiredNodeLebel to v3.Nodes when anything change happened in v3.Nodes.
* https://github.com/rancher/rancher/blob/master/pkg/controllers/management/node/controller.go#L313-L330
* https://github.com/rancher/rancher/blob/master/pkg/controllers/management/node/labels.go#L61-L75
-> here RKE would insert own metadata(rke.cattle.io/external-ip...) to annotation. So NodeController generate DesiredNodeAnnotations with Current v1.Node.Metadata.Annotations with RKE desired Annotation and Update v3.Node. This is usually happened when Node added to cluster.

After X sec (depending on loads in k8s),  NodeSyncer detect v3.Node Change and Try to replace v1.Node.Metadata.Annotation with v3.Node.Spec.DesiredNodeAnnotations
* https://github.com/rancher/rancher/blob/master/pkg/controllers/user/nodesyncer/nodessyncer.go#L164-L184

Problem could be happened between NodeController and NodeSyncer processing time.
If some addon(e.g. flanneld) added annotation to v1.Node after NodeController set DesiredNodeAnnotation and before NodeSyncer evaluate DesiredNodeAnnotation, NodeSyncer would just override few annotation which didn't exist when NodeContoller generate DesiredNodeAnnotation.

This is the case for rancher to delete important annotation of nodes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Confirmed this bugs at rancher/rancher:2.0.8

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM  4GB 8vCPU 100GB SSD
- Kubernetes version (use `kubectl version`):
1.11.2

- Docker (use `docker info`):
Server Version: 17.03.2-ce

** Solution I would suggest **
To be honest, although I found out the bugs and root cause of it, I don't have strong solution against it.
Because I don't think it's good idea to replace annotation of nodes with something in the first place which is exactly NodeSyncer is doing. we can expect user to run own addon which  depend on annotation of nodes and NodeSyncher mechanism always have the risk to delete these metadata easily. I think it's better to limit the annotation of nodes rancher would maintain.  but this is just in my opinion and maybe I missed something important.

So I would think of other solution as well while give a respect to NodeSyncer concept.
How about this solution?
* Add ResourceVersion of v1.Node to v3.Node that indicate which ResourceVersion of v1.Node is used as a base information when DesiredNodeAnnotations is generated. (we could have "force" reserved word letting always override annotations if we want to keep current behaviour)
     * e.g. v3.Node.Spec.DesiredNodeAnnotationBaseResourceVersion
               v3.Node.Spec.DesiredNodeLabelBaseResourceVersion
* NodeSyncer compare ResourceVersion between v1.Node and v3.Node
    *  if ResourceVersion don't match, NodeSyncer would change behaviour as following 
        * Don't replace annotation of v1.Node with DesiredNodeAnnotation
        * Add error condition to v3.Node to indicate Annocation, Label Sync is failed because of ResourceVersion miss match
        * And Don't delete DesiredNodeAnnotation
    * If ResourceVersion match or ResourceVersion is force, Do replace annotation in the same way as current behaviour
 
This change also can prevent from deleting annotation which have been injected by others after set up DesiredNodeAnnotation.

**Comment by superseb** [comment]
Thanks for the report, we can use it in https://github.com/rancher/rancher/issues/13644

**Comment by henrydecovo** [comment]
Hi,

This still appears to be an issue on 2.2:

Rancher	v2.2.3
User Interface	v2.2.41
Helm	v2.10.0-rancher10
Machine	v0.15.0-rancher6-1

Context:
- Imported cluster from GKE (Version: v1.12.7-gke.10)

Running the following recommended debug script writes out the name of every node in the cluster:
kubectl get nodes -o json | jq '.items[].metadata | select(.annotations["flannel.alpha.coreos.com/public-ip"] == null or .annotations["flannel.alpha.coreos.com/kube-subnet-manager"] == null or .annotations["flannel.alpha.coreos.com/backend-type"] == null or .annotations["flannel.alpha.coreos.com/backend-data"] == null) | .name'

Is there anything else I can do/provide to help triage this further?

**Comment by DominicGunn** [comment]
Also happening for me, rancher v2.2.2 and imported cluster in AWS.
