### ISSUE TITLE
Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml]

### ISSUE THREAD

**Issue by reeshuai** [rancher/rancher#16449]
2018/11/05 06:33:09 [ERROR] CatalogController library [catalog] failed with : Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml], did not respond in 30s 
2018/11/05 06:33:49 [ERROR] CatalogController library [catalog] failed with : Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml], did not respond in 30s 
2018/11/05 06:34:29 [ERROR] CatalogController library [catalog] failed with : Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml], did not respond in 30s

**Comment by reeshuai** [comment]
can not find this yaml

**Comment by reeshuai** [comment]
2018/11/05 07:12:10 [INFO] Rancher version v2.1.1 is starting,
2018/11/05 07:12:10 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:3},
2018/11/05 07:12:10 [INFO] Listening on /tmp/log.sock,
2018/11/05 07:12:10 [INFO] Running etcd --peer-client-cert-auth --client-cert-auth --initial-cluster-token=etcd-cluster-1 --initial-advertise-peer-urls=https://127.0.0.1:2380 --initial-cluster=etcd-master=https://127.0.0.1:2380 --cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --election-timeout=5000 --name=etcd-master --listen-peer-urls=https://0.0.0.0:2380 --initial-cluster-state=new --heartbeat-interval=500 --listen-client-urls=https://0.0.0.0:2379 --peer-trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --peer-key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --data-dir=/var/lib/rancher/etcd/ --advertise-client-urls=https://127.0.0.1:2379,https://127.0.0.1:4001 --trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --peer-cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem,
2018-11-05 07:12:10.453969 I | etcdmain: etcd Version: 3.2.13,
2018-11-05 07:12:10.453984 I | etcdmain: Git SHA: Not provided (use ./build instead of go build),
2018-11-05 07:12:10.453990 I | etcdmain: Go Version: go1.11,
2018-11-05 07:12:10.453996 I | etcdmain: Go OS/Arch: linux/amd64,
2018-11-05 07:12:10.454005 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1,
2018-11-05 07:12:10.454309 N | etcdmain: the server is already initialized as member before, starting as etcd member...,
2018-11-05 07:12:10.454349 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true,
2018-11-05 07:12:10.455168 I | embed: listening for peers on https://0.0.0.0:2380,
2018-11-05 07:12:10.455252 I | embed: listening for client requests on 0.0.0.0:2379,
2018-11-05 07:12:10.458174 I | etcdserver: name = etcd-master,
2018-11-05 07:12:10.458192 I | etcdserver: data dir = /var/lib/rancher/etcd/,
2018-11-05 07:12:10.458199 I | etcdserver: member dir = /var/lib/rancher/etcd/member,
2018-11-05 07:12:10.458204 I | etcdserver: heartbeat = 500ms,
2018-11-05 07:12:10.458209 I | etcdserver: election = 5000ms,
2018-11-05 07:12:10.458217 I | etcdserver: snapshot count = 100000,
2018-11-05 07:12:10.458230 I | etcdserver: advertise client URLs = https://127.0.0.1:2379,https://127.0.0.1:4001,
2018-11-05 07:12:10.491041 I | etcdserver: restarting member e92d66acd89ecf29 in cluster 7581d6eb2d25405b at commit index 3571,
2018-11-05 07:12:10.491205 I | raft: e92d66acd89ecf29 became follower at term 4,
2018-11-05 07:12:10.491221 I | raft: newRaft e92d66acd89ecf29 [peers: [], term: 4, commit: 3571, applied: 0, lastindex: 3571, lastterm: 4],
2018-11-05 07:12:10.596131 I | mvcc: restore compact to 2395,
2018-11-05 07:12:10.598212 W | auth: simple token is not cryptographically signed,
2018-11-05 07:12:10.680997 I | etcdserver: starting server... [version: 3.2.13, cluster version: to_be_decided],
2018-11-05 07:12:10.681909 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true,
2018-11-05 07:12:10.684459 I | etcdserver/membership: added member e92d66acd89ecf29 [https://127.0.0.1:2380] to cluster 7581d6eb2d25405b,
2018-11-05 07:12:10.684643 N | etcdserver/membership: set the initial cluster version to 3.2,
2018-11-05 07:12:10.684703 I | etcdserver/api: enabled capabilities for version 3.2,
2018-11-05 07:12:15.492215 I | raft: e92d66acd89ecf29 is starting a new election at term 4,
2018-11-05 07:12:15.492368 I | raft: e92d66acd89ecf29 became candidate at term 5,
2018-11-05 07:12:15.492396 I | raft: e92d66acd89ecf29 received MsgVoteResp from e92d66acd89ecf29 at term 5,
2018-11-05 07:12:15.492423 I | raft: e92d66acd89ecf29 became leader at term 5,
2018-11-05 07:12:15.492445 I | raft: raft.node: e92d66acd89ecf29 elected leader e92d66acd89ecf29 at term 5,
2018-11-05 07:12:15.493351 I | etcdserver: published {Name:etcd-master ClientURLs:[https://127.0.0.1:2379 https://127.0.0.1:4001]} to cluster 7581d6eb2d25405b,
2018-11-05 07:12:15.493427 I | embed: ready to serve client requests,
2018-11-05 07:12:15.494028 I | embed: serving client requests on [::]:2379,
2018/11/05 07:12:15 [INFO] Activating driver eks,
2018/11/05 07:12:15 [INFO] Activating driver eks done,
2018/11/05 07:12:15 [INFO] Activating driver import,
2018/11/05 07:12:15 [INFO] Activating driver import done,
2018/11/05 07:12:15 [INFO] Activating driver rke,
2018/11/05 07:12:15 [INFO] Activating driver rke done,
2018/11/05 07:12:15 [INFO] Activating driver gke,
2018/11/05 07:12:15 [INFO] Activating driver gke done,
2018/11/05 07:12:15 [INFO] Activating driver aks,
2018/11/05 07:12:15 [INFO] Activating driver aks done,
I1105 07:12:15.549895       6 http.go:108] HTTP2 has been explicitly disabled,
2018/11/05 07:12:15 [INFO] Running kube-apiserver --allow-privileged=true --storage-backend=etcd3 --service-cluster-ip-range=10.43.0.0/16 --requestheader-group-headers= --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem --etcd-prefix=/registry --requestheader-client-ca-file= --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --insecure-bind-address=127.0.0.1 --proxy-client-key-file= --proxy-client-cert-file= --requestheader-username-headers= --cloud-provider= --enable-admission-plugins=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --authorization-mode=Node,RBAC --advertise-address=10.43.0.1 --insecure-port=0 --secure-port=6443 --requestheader-allowed-names= --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem --etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem --bind-address=127.0.0.1 --service-node-port-range=30000-32767 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --requestheader-extra-headers-prefix= --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --endpoint-reconciler-type=lease --etcd-servers=https://127.0.0.1:2379 -v=1 --logtostderr=false --alsologtostderr=false,
2018/11/05 07:12:15 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: dial tcp 127.0.0.1:6443: connect: connection refused,
[restful] 2018/11/05 07:12:17 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi,
[restful] 2018/11/05 07:12:17 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/,
[restful] 2018/11/05 07:12:19 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi,
[restful] 2018/11/05 07:12:19 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/,
2018/11/05 07:12:22 [INFO] Running kube-controller-manager --allow-untagged-cloud=true --pod-eviction-timeout=5m0s --service-account-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --enable-hostpath-provisioner=false --node-monitor-grace-period=40s --cloud-provider= --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --address=0.0.0.0 --cluster-cidr=10.42.0.0/16 --service-cluster-ip-range=10.43.0.0/16 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --configure-cloud-routes=false --leader-elect=true --v=2 --allocate-node-cidrs=true --use-service-account-credentials=true -v=1 --logtostderr=false --alsologtostderr=false --controllers * --controllers -resourcequota --controllers -service,
2018/11/05 07:12:22 [INFO] Running in single server mode, will not peer connections,
2018/11/05 07:12:23 [INFO] Starting API controllers,
2018/11/05 07:12:23 [INFO] Listening on :443,
2018/11/05 07:12:23 [INFO] Listening on :80,
2018/11/05 07:12:40 [INFO] Starting catalog controller,
2018/11/05 07:12:40 [INFO] Starting management controllers,
2018/11/05 07:12:41 [INFO] Reconciling GlobalRoles,
2018/11/05 07:12:41 [INFO] Reconciling RoleTemplates,
2018/11/05 07:12:41 [INFO] Rancher startup complete,
2018/11/05 07:13:21 [ERROR] CatalogController library [catalog] failed with : Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml], did not respond in 30s,
2018-11-05 07:13:44.000417 W | etcdserver: apply entries took too long [116.315841ms for 1 entries],
2018-11-05 07:13:44.000444 W | etcdserver: avoid queries with large range/delete range!,
2018/11/05 07:14:02 [ERROR] CatalogController library [catalog] failed with : Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml], did not respond in 30s,

**Comment by superseb** [comment]
Please see the reply from @loganhz , it uses `git ls-remote` to check the repository and then uses `git clone` to get the contents. If `git ls-remote` fails, it falls back to HTTP server where there should be an `index.yaml` file.

**Comment by ronny35** [comment]
I use Gitea in order to obtain a mirror of this repo with a minimal number of outside connections.
I can not follow your request.

**Comment by btapo** [comment]
Opening this https://git.rancher.io/charts/index.yaml on browser gives 404 error. This file does not exist. Can we please have clear instructions on how to resolve this step by step? This seems to be very basic functionality which should get a beginner up and running on the tool.

**Comment by superseb** [comment]
As described in https://github.com/rancher/rancher/issues/16449#issuecomment-435777340, its a Git repository.  Running `git ls-remote https://git.rancher.io/charts` inside the container will show if it's reachable or not.

There is an open issue to host charts via HTTP here: https://github.com/rancher/rancher/issues/16672

**Comment by superseb** [comment]
Closing as inactive, there is a follow up for hosting on HTTP and debug steps are in this issue.

**Comment by rajha-korithrien** [comment]
Greetings!
I am using Rancher v2.1.5 on top of Rancher OS v1.4.2 and I have this same issue.

In the main Rancher UI under Global->Catalogs I have the following error message "Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml], did not respond in 30s"
![image](https://user-images.githubusercontent.com/8145476/51334041-3ae5a800-1a3c-11e9-9984-a455594c40ae.png)

I have a shell on one of my rancher pods via the following steps:
1. Get the pod name:
```
kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY   STATUS      RESTARTS   AGE
cattle-system   cattle-cluster-agent-655ddcdfb6-j4f6s     1/1     Running     0          1d
cattle-system   cattle-node-agent-7s6br                   1/1     Running     0          1d
cattle-system   cattle-node-agent-dkqsb                   1/1     Running     0          1d
cattle-system   cattle-node-agent-mnxzd                   1/1     Running     0          1d
cattle-system   rancher-74848fd487-9m9hn                  1/1     Running     1          1d
cattle-system   rancher-74848fd487-jdktn                  1/1     Running     0          1d
cattle-system   rancher-74848fd487-mv247                  1/1     Running     0          1d
ingress-nginx   default-http-backend-797c5bc547-zqjjh     1/1     Running     0          1d
...
...
```
2. Get a shell on a rancher pod:
```
kubectl --namespace cattle-system exec -it rancher-74848fd487-9m9hn -- /bin/bash
root@rancher-74848fd487-9m9hn:/var/lib/rancher#
```
3. With that shell check that the git repo described in @superseb comment is reachable:
```
root@rancher-74848fd487-9m9hn:/var/lib/rancher# git ls-remote https://git.rancher.io/charts
f4066758a9a453454f6d7e7f2225c1be9afb2aa8	HEAD
f4066758a9a453454f6d7e7f2225c1be9afb2aa8	refs/heads/master
3b9847dbf54705e36d6eed70a2d2697fbf194a0a	refs/pull/1/head
36156859c3e07c3a1333af2180a7e728b8f17a1f	refs/pull/100/head
...
...
```
So clearly the Rancher container can access the remove git repository.

How do I fix Rancher so it correctly accesses the Rancher Library catalog so I can use the charts that have been curated by the good folks at Rancher Labs?

Thanks!

**Comment by metal3d** [comment]
This issue should be reopened - fresh rancher server installed, got the same problem. There is no helm repository working

**Comment by Estebanor** [comment]
Hi, I have the same problem too
Hello community, recently I am in the world of kuberenetes in 3 nodes, I have deployed rancher v.2.2.2 with docker without problem. I have a proxy but before I worked with rancher V1.6 the catalog but now with the latest version I get error loading   Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml], did not respond in 30s . (image capture) 

I tried to follow the same steps as rajha-korithrien but I still have no solution,

thank you very much to all!

![kubernetes](https://user-images.githubusercontent.com/5777958/57290976-ca33cb80-70be-11e9-8123-9ea519f4c157.PNG)

**Comment by metal3d** [comment]
OK I just realize that, for weird reasons, I didn't have internet access from docker container. I fixed that with iptables rules to allow traffic from docker0 interface to outside. It now works.

**Comment by permanzh** [comment]
> OK I just realize that, for weird reasons, I didn't have internet access from docker container. I fixed that with iptables rules to allow traffic from docker0 interface to outside. It now works.

could you provide these rules please? I meet the same issue with rancher 2.2.3

**Comment by Shyckymn** [comment]
> 
> 
> OK I just realize that, for weird reasons, I didn't have internet access from docker container. I fixed that with iptables rules to allow traffic from docker0 interface to outside. It now works.

Hi @metal3d! 
Please, could you give me more details of how you managed to solve this issue?
What should I do inside the container so it has internet access?

**Comment by Estebanor** [comment]
> 
> 
> > OK I just realize that, for weird reasons, I didn't have internet access from docker container. I fixed that with iptables rules to allow traffic from docker0 interface to outside. It now works.
> 
> Hi @metal3d!
> Please, could you give me more details of how you managed to solve this issue?
> What should I do inside the container so it has internet access?

I solved this by removing the cluster and throwing everything with proxy rancher instructions.

docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -e HTTP_PROXY="http://192.168.10.1:3128" \
  -e HTTPS_PROXY="http://192.168.10.1:3128" \
  -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,192.168.10.0/24,example.com" \
  rancher/rancher:latest

https://rancher.com/docs/rancher/v2.x/en/installation/single-node/proxy/

Regards!

**Comment by Shyckymn** [comment]
@Estebanor, my proxy is running on the same server where docker is installed and where I'm trying to install Rancher.
My server ip address is 10.10.10.213 and my proxy is listening at port 40080.
When I try to install Rancher, the following occurs:
```

2019/06/05 17:59:05 [ERROR] CatalogController system-library [catalog] failed with : Error in HTTP GET to [https://git.rancher.io/system-charts/index.yaml], error: Get https://git.rancher.io/system-charts/index.yaml: proxyconnect tcp: dial tcp 10.10.10.213:40080: connect: connection refused
2019/06/05 17:59:05 [ERROR] CatalogController library [catalog] failed with : Error in HTTP GET to [https://git.rancher.io/charts/index.yaml], error: Get https://git.rancher.io/charts/index.yaml: proxyconnect tcp: dial tcp 10.10.10.213:40080: connect: connection refused

```
It seems like the container cannot reach the ip address 10.10.10.213... 
If I try to change the ip to localhost (or 127.0.0.1) in the `docker run` command line, it will try to access locally in the container, no the server ip address as I would like.
Any idea how to get around this problem?

**Comment by iDube** [comment]
I have the same problem too.  I  solved this by add --net="host" to start the single node rancher.
```
docker ps -a
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS                                      NAMES
9fa10df4e4ae        rancher/rancher:v2.2.4   "entrypoint.sh"     12 hours ago        Up 12 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   loving_bardeen

docker stop loving_bardeen
docker create --volumes-from mystifying_hawking --name rancher-data rancher/rancher:v2.2.4
docker run -d --volumes-from rancher-data --restart=unless-stopped --net="host" rancher/rancher:v2.2.4
```
