### ISSUE TITLE
Create user with uppercase letters works, but local login doesn't

### ISSUE THREAD

**Issue by pcornelissen** [rancher/rancher#16457]
**What kind of request is this (question/bug/enhancement/feature request):**
You can create users that can't log in

**Steps to reproduce (least amount of steps as possible):**

1. create user with uppercase characters using the rancher UI
1. logout
1. login with new user

**Result:**

Login doesn't work

**Other details that may be helpful:**
When I removed the user and created the same without uppercase chars it worked

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
I can not reproduce this issue by the following steps:

1. Start rancher with command `docker run -d -p 80:80 -p 443:443 rancher/rancher:v2.1.1`
2. Login as default admin user
3. Create a user with username `ABCd`, and choose `Standard User`
4. Logout admin user
5. Login with `ABCd`

![image](https://user-images.githubusercontent.com/21168270/48050004-89283080-e1db-11e8-886c-68a9af0cb751.png)

Did I miss something?

**Comment by pcornelissen** [comment]
Good question :-)

![image](https://user-images.githubusercontent.com/1177440/48088145-7c1e3800-e201-11e8-9bc9-9b31b552f1d9.png)

I created a user with the name deployment-TEST-infra and used custom rights. The user has only login right on rancher and then more rights on some cluster.

**Comment by loganhz** [comment]
I can reproduce this issue in v2.2.1 by the following steps:

1. Create a user with username `deployment-TEST-infra` and global custom role with `Login` permission only
2. Enable Github auth
3. Logout default `admin`
4. Try to login `deployment-TEST-infra` with local auth

It works in rancher/rancher:master

**Comment by jiaqiluo** [comment]
**Reproduction in rancher:v2.1.1**
Steps:
1. Started a Rancher Server v2.1.1
1. Added a user which username is `ABC-def-G` with custom permission.
2. Enabled Github auth.
3. Logout default admin.
4. Tried to login ABC-def-G with local auth.

Got the following error 
```
Logging in failed: Check credentials, or your account may not be authorized to log in.
```

**Validation on rancher:master 11/16**
Did the same procedures as the above with Rancher Server rancher:master on 11/16. And local user can log in successfully.

Bug fix validated.
