### ISSUE TITLE
After workload is edited, rancher 2.1.1 stucked in creating-failing pods.

### ISSUE THREAD

**Issue by erikbotta** [rancher/rancher#16450]
**What kind of request is this (question/bug/enhancement/feature request):**
Rancher 2.1.1 , one cluster, one node in cluster with all roles.
BUG: When I edited workload and changed port from : Nodeport to: Hostport there was situatiation when 300 and more pods was created ( then showed as failed ). 

**Steps to reproduce (least amount of steps as possible):**
1) Create workload (mongo:3.2.7) on onecluster onenode
2) Publish port with NodePort (27017 - > 30000)
3) Edit workload and change to HostPort (27017 -> 28018)

**Result:**
After step 3 -> stucked creating of POD -> created more than 300 pods. After that I deleted (hardly in UI) workload. 

**Other details that may be helpful:**

**Environment information**
- Rancher version 2.1.1
- Installation option (single install/HA): single install, one cluster, one node(all roles)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 16vcpu, 32G RAM
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
>
```

- Docker (use `docker info`):

```
root@kubernetes1:/home/erik# docker info
Containers: 61
 Running: 47
 Paused: 0
 Stopped: 14
Images: 28
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 290
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-131-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.42 GiB
Name: kubernetes1
ID: R2LN:7H4Q:L7WJ:I3B7:AJPA:YWDM:NIE4:UBHI:RAUY:USWN:EYZA:ZDYV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by loganhz** [comment]
@erikbotta Could you look at the events section in the failed pod detail page, please?

**Comment by erikbotta** [comment]
@alena1108 Here it is ... 
[rancher.log](https://github.com/rancher/rancher/files/2552686/rancher.log)

**Comment by erikbotta** [comment]
@loganhz Sorry, I was deleted that workload ASAP when this happened due to cluster health :)

**Comment by tfiduccia** [comment]
Version - v2.2
I cannot reproduce this on our latest build.

**Comment by deniseschannon** [comment]
@erikbotta Please try again with our most recent release and let me know if you still have issues.
