### ISSUE TITLE
Make UI token expiration configurable

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16467]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Other details that may be helpful:**
The UI session is hard coded to expire after some time, looking to make that configurable.

https://github.com/rancher/ui/blob/bc7338e6a82ff8d5ee56dc50c921519bc4b9410e/lib/shared/addon/utils/constants.js#L479

**Comment by cjellick** [comment]
make sure you open a UI issue for this

**Comment by sowmyav27** [comment]
Verified on `master-head` - commit id:`93019c54b`


- Login as admin. Enable an Auth (say AD). Change the AuthUserSessionTTLMinutes to 1.
- Login as user1.
- He is not able to see his UI Session token.
- He is logged out after 1 minute.
- When he logs back in, he sees a token with Expired status. 


Admin and standard user are logged out on a hard refresh of page/while performing actions on the UI after the configured AuthUserSessionTTLMinutes has elapsed. 

The tokens get deleted on the management after the 1 hr window (after which the expired token are purged)
