### ISSUE TITLE
Edit Load Balancer shows incorrect information when host and source values are set. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1646]
UI - latest master
Server version - v0.30.0-rc2

Created LB with targets having following labels from UI.
  labels:
    io.rancher.loadbalancer.target.web2: host1/service1=80
    io.rancher.loadbalancer.target.web3: host3:7777
    io.rancher.loadbalancer.target.web1: host2/service2

When this LB is opened for editing , host and source values are set incorrectly:

<img width="814" alt="screen shot 2015-07-24 at 12 50 43 pm" src="https://cloud.githubusercontent.com/assets/4266958/8883337/e015f51c-3202-11e5-9897-fa13a169b1db.png">

**Comment by deniseschannon** [comment]
Note: This only occurs when there is a number in the request host and includes a source port. WIll test out further combinations of numbers in host/path and ports.

**Comment by vincent99** [comment]
Missing a `^` in the regex, so any hostname ending with a number in it was triggering matching of the old format:  `tgtPort[:hostname][:srcPort][/path]`.

Bonus fix: srcPort in the old format wasn't handled right before either.

**Comment by sangeethah** [comment]
Tested with server version - v0.30.0-rc3.

Edit Load Balancer shows incorrect information when host (which ends with numeric value) and source values are set.
