### ISSUE TITLE
Rancher ARM64 Support

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#16461]
The technological ecology of Docker and Kubernetes is becoming more and more friendly to ARM, Rancher should also support it. After discussing with some customers, we think they are more inclined to these features:
1. Creating an ARM k8s cluster using RKE. (P0)
2. ARM k8s cluster can be imported into Rancher. (P0)
3. Support one Rancher Server to manage both ARM and x86 k8s clusters. (P0)
3. Adding ARM k8s via `add custom node` (P1)
4. Running Rancher Server on ARM. (P1)
5. ~Support Rancher Logging/Monitoring/Pipeline feature. (P2)~

**Comment by niusmallnan** [comment]
@ekristen Thanks your PR!
But some of your changes are not the same as we expected, our engineers will also submit PR, we will invite you to review.
If some ideas are consistent with your PR, we will follow yours.

**Comment by ekristen** [comment]
By my list the following need to have multi-arch builds that are in the rancher portfolio.

* [ ] - https://github.com/rancher/machine-package
* [ ] - https://github.com/rancher/rke-tools (https://github.com/rancher/rke-tools/pull/28)
* [ ] - https://github.com/rancher/hyperkube (https://github.com/rancher/hyperkube/pull/8)
* [ ] - https://github.com/rancher/loglevel
* [x] - https://github.com/krallin/tini
* [ ] - https://github.com/rancher/helm
  * [x] - (upstream does) https://github.com/helm/helm
* [ ] - https://github.com/rancher/telemetry
* [ ] - https://github.com/rancher/cli (NOTE: has arm, not arm64)
* [ ] - https://github.com/rancher/share-mnt

External to Rancher Portfolio 

* [ ] - https://github.com/c-bata/kube-prompt

**Comment by ekristen** [comment]
> @ekristen Thanks your PR!
> But some of your changes are not the same as we expected, our engineers will also submit PR, we will invite you to review.
> If some ideas are consistent with your PR, we will follow yours.

Care to comment on the PR(s) as to what is not the same as expected, happy to change it, or review an engineers PR. I just want multi-arch support.

**Comment by ekristen** [comment]
I want to help test, any chance you can provide instructions on how to? Or provide instructions on how the development team is testing while developing? Thanks!

**Comment by ekristen** [comment]
Is the whole cluster going to have to be ARM64? Or is it going to allow for a mix? 

For my use case, my control planes and etcd nodes can be any architecture, but my workers need to be arm64.

**Comment by ekristen** [comment]
Just checking in on this! Really excited for this and want to start testing it out as soon as possible. Instructions, howtos, and/or ETA on when we can see an alpha release with this would be awesome. Thanks for the hard work. Cheers!

**Comment by hcaz** [comment]
@kingdevnl If you check the [readme.md](https://github.com/rancher/os) for the rancheros repo they do have ARM downloads for the v1.5.0 release.

I think they just are not including those in the actual github releases

**Comment by kingdevnl** [comment]
Omg, sorry totally overlooked it

**Comment by j2l** [comment]
Can't wait to test it on my RasPi.

**Comment by ekristen** [comment]
Any status update on this?

**Comment by cjellick** [comment]
Hi @ekristen we are making progress! We redesigned our approach to be based on docker manifests, which set us back a bit. But we are not progressing forward again. Still planning for experimental support in v2.2

**Comment by ekristen** [comment]
Awesome, Thanks for the update. 

I would really like to help test and get eyes on it as soon as possible.

Any chance there’s documentation to go through manually building the components so I can test before it lands? 

Thanks!!

**Comment by cjellick** [comment]
Appreciate your interest. I'll ask the devs working on it to put something together.

**Comment by kingsd041** [comment]
Version: master 2.2 (3/15/19) 
Confirmed fix.
According to https://github.com/rancherlabs/the-ranch/issues/215 has completed the Rancher ARM64 test, all test cases passed, I will close this issue
