### ISSUE TITLE
Validate RHEL 7.6 for 2.x

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16469]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Steps to reproduce (least amount of steps as possible):**
Validate RHEL 7.6

https://www.redhat.com/en/about/press-releases/red-hat-refines-hybrid-cloud-innovation-latest-version-world%E2%80%99s-leading-enterprise-linux-platform

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.6_release_notes/index

**Comment by Oats87** [comment]
👍

**Comment by panho66** [comment]
+1

**Comment by soumyalj** [comment]
Tested RHEL 7.6 on Master build for the following :

1. K8s v1.13.1 with docker 1.13(native and selinux enabled)
2. K8s v1.13.1 with docker 1.13(upstream and selinux disabled)
3. K8s v1.12.5 with docker 1.13(native and selinux enabled)
4. K8s v1.12.5 with docker 1.13(upstream and selinux disabled)

Automation runs were successful with no new issues found.

**Comment by panho66** [comment]
Rancher 2.1.6 default Kubernete version

1.10.12
1.11.6 (default)
1.12.4 (experimental)

This ticket only test  K8s v1.12.5 with docker 1.13. Does it mean K8s 1.11.6 also passed and validated ?
