### ISSUE TITLE
Windows GA in Rancher

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16460]
**Areas for QA to test (checked indicates QA checks are done).**

- [x] Support adding Windows 1903 worker nodes for custom cluster
- [x] Only support k8s 1.15 and above for Windows cluster
- [x] Only support flannel as the network plugin for Windows cluster
- [x] Support 2 flannel backends. VXLAN and HOST-GW.
- [x] Add default taints for linux workers in Windows clusters. So users don't have to add node selector stuff for their Windows workloads. 
- [x] Users should be able to use Rancher logging to collect log from stdout 
- [x] Users should be able to enable Rancher monitoring to see Windows worker metrics/pod metrics
- [x] Users should be able to use Rancher alerting and notification for Windows nodes and pod.

https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

**Comment by viniciusxyz** [comment]
I'm waiting for support for 1809 a few months, do you have any news or preview of release?

**Comment by JasonvanBrackel** [comment]
@thxCode / @deniseschannon Any update on the timeline for 1809 support?  Anything I can do to help move this forward?

**Comment by ekarlso** [comment]
Any news on this?

**Comment by JasonvanBrackel** [comment]
@ekarlso It's actively being developed as I write this.

**Comment by ekarlso** [comment]
@loganhz did you have a preview build?

**Comment by loganhz** [comment]
@ekarlso you can use `rancher/rancher:master` for now. We will release the preview build in the middle of May. Thanks!

**Comment by loganhz** [comment]
Blocked by https://github.com/rancher/rancher/issues/21899

**Comment by sangeethah** [comment]
@loganhz 

Users should be able to add Windows 2019 (1809 or 1903). ==> We are currently validating only with 1903 with K8s 1.15 . Can you please confirm that we are NOT planning extend support for 1809?

**Comment by lanoxx** [comment]
Windows Server 2019 is based on 1809. Does that mean you are not planning to support  Windows 2019 either?

**Comment by loganhz** [comment]
1809 should just work unless there are some Docker and Windows side bug.
1809 will not be in our support list https://rancher.com/support-maintenance-terms/

**Comment by davidnuzik** [comment]
I unchecked the last three checkboxes in issue description. I put those there for QA to test. Once we have validated we will check them off (and issue will be ready to close).

**Comment by sangeethah** [comment]
All the features tracked in this ticket are available and have been validated using latest rancher server build `master-head`.

Issues found when testing these features are tracked as separate issues.
