### ISSUE TITLE
Backport: Rancher log shows running in single-server mode when clustered

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16476]
Backport https://github.com/rancher/rancher/issues/16475

**Comment by alena1108** [comment]
Should be fixed in rancher/rancher:v2.1.2-rc8

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc8

* Deployed Rancher with a standalone container
* Check Rancher logs: `docker logs <container> | grep mode`
* Logs correctly show `2018/11/08 16:03:37 [INFO] Running in single server mode, will not peer connections`

* Deployed Rancher in HA
* Check Rancher logs: `kubectl logs -n cattle-system <rancher leader pod> | grep mode`
* Logs correctly show `2018/11/08 16:22:45 [INFO] Running in clustered mode with ID 10.42.1.3, monitoring endpoint cattle-system/rancher`
