### ISSUE TITLE
Editing EKS cluster - when clicking on save without keys/token, stuck in saving

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16470]
Version - 2.2 master

**Steps to reproduce (least amount of steps as possible):**
1.  Create an EKS cluster (with or without session token - it doesn't matter)
2.  Wait for it to be active
3.  Edit EKS cluster
4.  Do not fill out access or secret key.

**Result:**  Save is stuck spinning.  Error from dev console: 0:254091 Uncaught TypeError: Cannot read property 'trim' of undefined
![image](https://user-images.githubusercontent.com/11514927/48096465-765e2d80-e1d4-11e8-91e9-0045f253b0d5.png)

**Comment by westlywright** [comment]
Will be available in `2.1.12` when a rc >8 is created.

**Comment by tfiduccia** [comment]
Version - 2.1.2-rc9 - verified fixed.  Leaving open to verify in 2.2

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/13
Verified fixed
