### ISSUE TITLE
UI for reaching clusters without the rancher server proxy

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16486]
We're going to make it so that for RKE clusters, users can specify an FQDN and optionally a CA cert on cluster creation or as an update which will cause us to create the kubeconfig differently so that it points directly at the FQDN, not the rancher server url.

https://github.com/rancher/rancher/issues/13698
https://github.com/rancher/rancher/issues/13474

@erikwilson please add more details and make sure you work with @westlywright on this, once it gets to a point where he can integrate. Assign to erik as well as wes until its ready for wes to integrate with, then you can unassign yourself erik.

**Comment by erikwilson** [comment]
The related rancher PR has been merged @westlywright 

ClusterSpec has been updated to include `EnableClusterAuth`, `ClusterEndpointFQDN`, and `ClusterEndpointFQDNCaCert`. (also see https://github.com/rancher/types/pull/614/commits/c128e6a06ec73f992b8038d1e91a41ae4804cc21#diff-fb6a90b273f7a0747ca4791359846dbd) 

`EnableClusterAuth` should only be available for RKE clusters at the moment, when enabled the `ClusterEndpointFQDN` and `ClusterEndpointFQDNCaCert` fields are optional.

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/31
Not completed:
Certificate field won't take any value.  Throwing error, even thou I have a valid cert format.
![image](https://user-images.githubusercontent.com/11514927/52080426-f9cdb780-2554-11e9-8c1e-f7d9d8d2e6fe.png)

Dev tool says not schema found to validate:
0:151688 No schema found to validate /v3/schemas/localclusterauthendpoint

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/14/19)
This adds Authorized Cluster Endpoint section under Advanced Options for RKE clusters.
![image](https://user-images.githubusercontent.com/45179589/52821538-4d1f2a00-306c-11e9-9625-d46531f15cfd.png)

In the API this adds localClusterAuthEndpoint. I validated this from UI perspective and http/API looks good.
```
localClusterAuthEndpoint: {enabled: true, type: "localClusterAuthEndpoint",…}
  caCerts: value goes here. if empty is "null" without quotes
  enabled: true
  fqdn: "redacted.us-west-1.compute.amazonaws.com"
  type: "localClusterAuthEndpoint"
```

v3/schemas/localClusterAuthEndpoint seems to match what I see in the UI appropriately.

If your certificate is invalid (garbage data, etc) you will get a message in the UI:
![image](https://user-images.githubusercontent.com/45179589/52821708-df273280-306c-11e9-829c-6e0ced58df2e.png)

Once I have a proper certificate (It checks for ------BEGIN CERTIFICATE------ and ------END CERTIFICATE------) only then may I submit the form and create/edit my cluster.
