### ISSUE TITLE
Two labels on a single host with the same key but different values never start containers with matching labels.

### ISSUE THREAD

**Issue by montgomerytech** [rancher/rancher#1648]
This may not be considered a bug, or a lack of understand on how key vlaue pairs are entered for Rancher. But I figured I would report it anyway.

If you have two key/value pair labels on a host (i.e. rule1=bob and rule1=tom) and you try to run rancher-compose with two unique containers each with one of those labels the rancher-compose command just hangs and neither the container is ever created.

Steps to reproduce:
1. Creat a host in Rancher with the following two labels "rule1=bob" and "rule1=tom".
2. Create a rancher compose with instructions for starting two containers, one container with the label "io.rancher.scheduler.affinity:host_label: rule1=bob" and the other with the label "io.rancher.scheduler.affinity:host_label: rule1=tom"
3. Run "rancher-compose up".

Observation: rancher compose command hangs and containers are never created on the single host.

**Comment by sonchang** [comment]
Hi @montgomerytech 
Having two host labels with the same key will overwrite each other.  However, I would've expected one of the containers to start up (but not the other).

**Comment by deniseschannon** [comment]
In Step1, did you mean to write `rule2=tom` or `rule`=tom`?

Can you share your docker-compose.yml? And provide the output from rancher-compose?

**Comment by montgomerytech** [comment]
So do both the value and the key have to be unique on the host? The use case I have in mind is using a host for multiple service in a stack (for example, in a wordpress, db, load balancer stack having the wordpress container(s) and the load balancer on the same host, theoretically using the labels wordpress=wordpress and wordpress=lb.

@deniseschannon both of them should have been rule1 (typo on the putting rule2).

**Comment by vincent99** [comment]
Labels are a map structure and cannot have duplicate keys.  So you'd have to do something like `wp_app=true`, `wp_db=true`, `wp_lb=true`.

**Comment by deniseschannon** [comment]
Only the key has to be unique. 

From what I'm reading, you're trying to have the wordpress/db and lb deployed together on the same host. Using a host label will help define where you want to apply all of the services, but i'm not sure why you need two labels to achieve this. Why can't they have the same scheduling rule?

Wouldn't using this rule for all services work?
`io.rancher.scheduler.affinity:host_label: rule1=bob`

Another way to make sure that the DB and wordpress are always deployed together, you could create a sidekick label. http://docs.rancher.com/rancher/rancher-compose/#sidekicks

**Comment by vincent99** [comment]
If you *always* want them on the same host a single label is fine.  But if you want a single compose template and a prod environment where they're all on separate hosts but on dev they share then multiple labels is useful.

**Comment by deniseschannon** [comment]
@montgomerytech Please re-open if you need more help.
