### ISSUE TITLE
Save all configurations of Rancher

### ISSUE THREAD

**Issue by RafaelGSS** [rancher/rancher#16483]
Hello everyone!

I searched on google and "issues" someone who asked what I'm going to ask now, but I did not find.

I need save the actual state of Docker container Rancher on my registry or anywhere, because when container exit by several reasons I need start it with same configuration. I see the issue: https://github.com/rancher/rancher/issues/1555 But when I went test it, did not saved my Stack and Hosts configurations.

I also tested with "Docker commit" for save the actual state of container rancher/rancher:stable but, Stacks, Hosts and Local Password is not saved. 

Sumarry:
I need save the hosts configurations for when the container dies, I upload it already with the hosts pointed at it.

**Comment by RafaelGSS** [comment]
Ps: When use external database with:

```
sudo docker run -p 8080:8080 --name rancher rancher/server:stable \ 
--db-host <host> --db-port <port> --db-user <user> --db-pass <password> --db-name <database>
```
But when execute the startup has failed: 
```
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Duplicate entry 'host.api.key' for key 'idx_data_name'
Query is: insert into `data` (`name`, `visible`, `value`) values (?, ?, ?), parameters ['host.api.key',0,'-----BEGIN RSA PRIVATE KEY-----
KEY...
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1115)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1047)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1002)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:588)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:399)
	... 80 common frames omitted

STARTUP FAILED [513031] ms
```

**Comment by superseb** [comment]
Both options still work as expected, either bind mounted directory or external DB:

Bind mounted:
```
docker run -d -p 8080:8080 -v /mysql:/var/lib/mysql rancher/server:stable
```

External:
```
docker run --name db -e MYSQL_ROOT_PASSWORD=root -d mariadb:10.2
```

https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#launching-rancher-server---single-container---external-database

```
docker run --link db -p 8080:8080 --name rancher rancher/server:stable  --db-host db --db-port 3306 --db-user cattle --db-pass cattle --db-name cattle
```

Let me know if you have steps to reproduce so I can look into it again.
