### ISSUE TITLE
Not able to add etcd node to cluster

### ISSUE THREAD

**Issue by Gloix** [rancher/rancher#16485]
When adding an etcd, control panel and worker node in the same host running the rancher server container (Rancher 2.1.1) it registers as 10.10.0.5 and when connecting another host the cluster running the same 3 services it cannot connect to the previously connected host and I get:

    [network] Host [172.31.X.X] is not able to connect to the following ports: [10.10.0.5:2379, 10.10.0.5:2380]. Please check network policies and firewall rules

Of course the ports are open on both hosts and even tested that with nmap.

Apparently the local host registers itself to k8s (or rancher I'm not sure) with a vnet local ip address and thus, the external host cannot connect to it. Or at least that is as far as my understanding of the issue goes.

I do have to say that both machines are not in the same datacenter (not even the same cloud provider), so their external IPs should be used for communication.

I have cleaned docker and related folders multiple times, and even with the scripts by @jdall found here [https://github.com/rancher/rancher/issues/14249#issuecomment-400941075](url) on both hosts with no progress on the matter.

**Comment by mjschmidt** [comment]
Can confirm. Setup a quick 6 node cluster. 3 etc, control nodes and 3 workers. I then deleted an etcd node and tried to re add it just to see if I could lose an etc node and bring it back online later. The answer is nay.

**Comment by deniseschannon** [comment]
When trying to re-use nodes, be sure to properly clean them up:

https://rancher.com/docs/rancher/v2.x/en/removing-rancher/
