### ISSUE TITLE
Project active but updates are not applied

### ISSUE THREAD

**Issue by hmonadjem** [rancher/rancher#16494]
After updating (from 2.0.8) I see the following error message:

![image](https://user-images.githubusercontent.com/4346277/48164654-6a14c600-e2e3-11e8-8418-fb1197026281.png)

It shows that its Active, but still if I upgrade the catalog app it doesn't change any of the pods

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.2-rc7` UI: `v2.1.11` |
|Route|`apps-tab.detail`|

**Comment by loganhz** [comment]
You are using a RC build. Can you try v2.1.1, please?

**Comment by hmonadjem** [comment]
I already tried 2.1.1 and had the same issue (why I tried the RC build).

Still same Error on the one App:
![image](https://user-images.githubusercontent.com/4346277/48185970-eb497880-e336-11e8-9364-c6503c4cfa46.png)

But I also see the following one:
![image](https://user-images.githubusercontent.com/4346277/48185986-f8fefe00-e336-11e8-91c4-3d5d405e3072.png)

It's weird since its really not reacting to any changes I do on the helm project.

**Comment by deniseschannon** [comment]
It sounds like you have hit this: https://github.com/rancher/rancher/issues/18571
