### ISSUE TITLE
Custom cluster unavailable after node registered in HA Airgap setup

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16491]
rancher/rancher:v2.1.2-rc7
HA Airgap setup

* Deployed Rancher server in HA air gap
* Created custom cluster
* Registered node specifying the internal IP as the public IP in the node registration command
* Node provisioned correctly
* Cluster showed as unavailable

Sometimes cluster comes back as available for a few seconds, but then becomes unavailable soon after.

Rancher logs:
```
2018/11/07 20:49:51 [ERROR] ClusterController c-fdbsh [user-controllers-controller] failed with : failed to start user controllers for cluster c-fdbsh: failed to contact server: Get https://172.31.28.98:6443/version?timeout=30s: waiting for cluster agent to connect
```

Rancher pod troubleshooting: 
```
root@rancher-9c888fff6-bz97w:/var/lib/rancher# curl https://172.31.28.98:6443 -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}

root@rancher-9c888fff6-bz97w:/var/lib/rancher# curl https://172.31.28.98:6443/healthz -k
ok
```

**Comment by alena1108** [comment]
Can potentially have the same root cause as https://github.com/rancher/rancher/issues/16476

**Comment by jiaqiluo** [comment]
Rancher v2.1.2-rc8 HA(3 nodes)  Airgap setup

Tried adding different custom clusters:
- 3 node( 1 etcd, 1 control plane, 1 worker )  Success!
- 6 node( 3 etcd, 1 control plane, 2 worker)  Success!
- 1 node( all roles)  Success!
Verified fixed.
<img width="1687" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/48231592-e9e67300-e36b-11e8-9a60-7d3732283445.png">
