### ISSUE TITLE
Error Get https://xxx.xxx.xxx.xxx:6443/api/v1/namespaces?timeout=30s: waiting for cluster a gent to connect  

### ISSUE THREAD

**Issue by gxl191911** [rancher/rancher#16499]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
@gxl191911 Can you provide the node agent log and rancher server log please?

**Comment by gxl191911** [comment]
> @ gxl191911你能提供rancher版本，重现步骤，节点代理日志和牧场服务器日志吗？



> @gxl191911 Can you provide the rancher version, reproduce steps, node agent log and rancher server log please?
> @loganhz I used rancher v2.1.1,appear once in a few minutes without any indication

**Comment by gxl191911** [comment]
> > @ gxl191911你能提供rancher版本，重现步骤，节点代理日志和牧场服务器日志吗？
> 
> > @gxl191911 Can you provide the rancher version, reproduce steps, node agent log and rancher server log please?
> > @loganhz I used rancher v2.1.1,appear once in a few minutes without any indication

wait a minute，I find some agent log fou you

**Comment by gxl191911** [comment]
> > @ gxl191911你能提供rancher版本，重现步骤，节点代理日志和牧场服务器日志吗？
> 
> > @gxl191911 Can you provide the rancher version, reproduce steps, node agent log and rancher server log please?
> > @loganhz I used rancher v2.1.1,appear once in a few minutes without any indication

> node agent timeout,but a minute later, it back to normal。
