### ISSUE TITLE
Provide helper text for Creation/Retention Period units.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16509]
Rancher server version - v2.1.2-rc8

It would be helpful to have sone helper text for Creation/Retention Period fields about the allowed units that can be set.

**Comment by alena1108** [comment]
Resolved in rancher/rancher:v2.1.2-rc9

**Comment by sangeethah** [comment]
Tested with v2.1.2-rc9

@westlywright We have the following helper text for Snapshot Creation Period - "acceptable units: s, m, h, d, w, m, y" which is incorrect .only h,m,s is supported ( format like - 2h10m3)

Reopening this issue to fix the text.

**Comment by westlywright** [comment]
available in master and `2.1.13`

**Comment by cjellick** [comment]
`rancher/rancher:v2.1.2-rc10` will have UI 2.1.13. It is currently being built

**Comment by tfiduccia** [comment]
@sangeethah - Is this what you wanted this text to say?  If so can you close.

**Comment by sangeethah** [comment]
With v2.1.2-rc10 , we see the following helper text ```acceptable duration units: h, m, s```.
