### ISSUE TITLE
[Question] Rancher HA cluster load balancing

### ISSUE THREAD

**Issue by wmolyneux** [rancher/rancher#16507]
I have created a Kubernetes cluster on 3 Ubuntu 16.04 machines using RKE as described in the high availability guide here (https://rancher.com/docs/rancher/v2.x/en/installation/ha/)

I have a front end load balancer on a machine (e.g. my.host.com) routing to the Kubernetes cluster on my three nodes. This routes all traffic on port 443 to the cluster on port 443 of each cluster node. NGinx then routed the request to Rancher which is registered with the ingress for any traffic with the hostname provided on install (i.e. my.host.com).

My issue however is that I want to run a Traefik ingress controller in my Kubernetes cluster on a specific node port (e.g. 30000) and then I want my front end load balancer to send all traffic to Traefik and **not** NGinx and route to my services running in the cluster registering with the Ingress at different urls.

Some examples of my ideal routing would be:
1) my.host.com/example1 = load balancer -> traefik -> example1Service
2) my.host.com/example2 = load balancer -> traefik -> example2Service
3) my.host.com/rancher = load balancer -> traefik/nginx -> Rancher UI

My questions:
1) The HA rancher documentation uses the Rancher helm chart to deploy Rancher. Is there a way to change its ingress configuration to not use the hostname but instead a registered route e.g. /rancher?

2) If this is not possible, what other solutions can I do to be able to route to both my services and the rancher UI from a single load balancer?

**Comment by superseb** [comment]
The cluster with 3 nodes created by RKE for Rancher is meant for running Rancher only. If you want to run your workloads, please create a new cluster from within Rancher (https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/#cluster-creation-options). In this newly created cluster you can then either disable the built-in Ingress controller (https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/ingress-controllers/#disabling-the-default-ingress-controller via https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file) and launch your own, or configure the built-in controller to point to your controller or basically however you want to configure it.

**Comment by wmolyneux** [comment]
Oh wow... So if I run a single instance of Rancher using the docker run command and install some catalog apps, If i lost the machine with Rancher on but create a new rancher container on a new machine. Will the new Rancher know about my catalog apps installed or was my data on the original machine and therefore lost?

Is there a way to deploy Rancher to the same cluster as my workloads?

**Comment by superseb** [comment]
Keeping state with single install is described here: https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#persistent-data. You will need to move the data manually to another host (or have some other sync mechanism). Single install doesn't give you a cluster to run your workloads, you still need to create a cluster so that won't help you. (except maybe https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#running-rancher-rancher-and-rancher-rancher-agent-on-the-same-node)

You can run workloads in the cluster for Rancher but it's not recommended/supported, as your workloads can take down Rancher, and there are some other technical challenges that arise you decide to do so.

**Comment by wmolyneux** [comment]
Thanks for the quick response.

Can I use the RKE cluster for my workloads without putting Rancher on it? I like the setup scenario of creating a cluster using this tool.

**Comment by superseb** [comment]
RKE was made to easily setup Kubernetes clusters, if you want to use just that, that's fine.
