### ISSUE TITLE
add side car bug v2.1.1 rancher ui  with projcet resource quota

### ISSUE THREAD

**Issue by jagjag** [rancher/rancher#16505]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
![image](https://user-images.githubusercontent.com/1321754/48195520-d39bdf80-e38a-11e8-810d-a4979698e115.png)

I tryed to add a sidecar to a pod which the pod's namespace with  limit quota 

If you don't set limit quota in the first time .  
![image](https://user-images.githubusercontent.com/1321754/48195709-591f8f80-e38b-11e8-8f07-4384845c68ff.png)
there was an alert  of no limit  was set

and then I added the limit  and continue 

The alert change to  this sidecar already exists.
![image](https://user-images.githubusercontent.com/1321754/48195814-92f09600-e38b-11e8-917a-0600a22ac046.png)

and  I changed the side car 's name to a-side-car-1

I got 
![image](https://user-images.githubusercontent.com/1321754/48195897-d0552380-e38b-11e8-90b7-93d15bba2638.png)

then I get stuck of this ui. and no side car created.

**Result:**

stuck in the add side car ui

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher 2.1.1  helm install
k8s 1.11.3-rancher-1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker (use `docker info`):

```
Containers: 40
 Running: 25
 Paused: 0
 Stopped: 15
Images: 33
Server Version: 17.03.3-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-124-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66 GiB
Name: ran2t-m01
ID: BOTO:LVHD:47NH:3ADD:H6I2:3JWF:AXT2:S4XB:FKTC:AKRP:QOIS:MF5K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed
