### ISSUE TITLE
[2.1.1]Failed to validate cluster: Hostname_override

### ISSUE THREAD

**Issue by D-T-Y** [rancher/rancher#16508]
![image](https://user-images.githubusercontent.com/21084531/48210790-022db080-e3b3-11e8-89c2-6f419d421e0b.png)

> 此集群当前为Updating
> 
> Failed to validate cluster: Hostname_override [DataCenter005] for host (1) is not valid: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')] 

I modified hostname, still can't update end.

**Comment by superseb** [comment]
The workaround is mentioned in https://github.com/rancher/rancher/issues/16294

**Comment by D-T-Y** [comment]
![image](https://user-images.githubusercontent.com/21084531/48213512-f8a74700-e3b8-11e8-8490-ee397c2bdd3f.png)


Modified to lowercase letters, still can't update end.
