### ISSUE TITLE
Develop and document minimum IAM policy required to use encrypted EBS volumes

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16501]
**What kind of request is this (question/bug/enhancement/feature request):**
Develop recommendations, test and document

Rancher doesnt document the minimum viable IAM policy to use encrypted ebs volumes with k8s (aws cloud provider).

**Steps to reproduce (least amount of steps as possible):**
To get it to work we used a fairly open role, here are the permissions used:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:DetachVolume",
                "ec2:DescribeInstances",
                "ec2:DescribeVolumes"
                "kms:CreateGrant",
                "kms:Decrypt",
                "kms:Describe*",
                "kms:Encrypt",
                "kms:GenerateDataKey*",
                "kms:ReEncrypt*"
        ],
        "Resource": "arn:aws:kms:{EBS-Volume)"
       }
    ]
}
```

Would like to document the minimum most rules required and have those tested.

**Comment by drpebcak** [comment]
I'll look at writing up a restrictive IAM policy for this.. people may also be interested in this though: https://aws.amazon.com/blogs/aws/new-opt-in-to-default-encryption-for-new-ebs-volumes/

**Comment by deniseschannon** [comment]
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/ec2/#example-iam-policy-to-allow-encrypted-ebs-volumes
