### ISSUE TITLE
[Feature Request] Add color config to project

### ISSUE THREAD

**Issue by k8w** [rancher/rancher#16500]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Feature Request**
1. Add a **color** config to project
2. Project should be highlighted with its color when switched to
![1.png](https://i.loli.net/2018/11/08/5be3b42f3887b.png)
![2.png](https://i.loli.net/2018/11/08/5be3b42f349ff.png)

**Request Reason**
1. Test and production are different project
2. Sometimes users operate in wrong project by mistake
3. A highlighted color is useful to avoid this mistake
4. Software `NoSQL Booster` have this feature, and it's very useful (as below)
![3.png](https://i.loli.net/2018/11/08/5be3b45188901.png)

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/15838
