### ISSUE TITLE
System-tools was unable to clean up the workload/pod

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#16502]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. Deploy the K8S cluster through RKE
2. Import the cluster into Rancher
3. Create a workload
4. Delete the cluster
5. Run system-tools to clean up K8S

**Result:**

1. Before clearing, use kubectl to view only one POD，
  <img width="578" alt="image" src="https://user-images.githubusercontent.com/20707603/48185369-c02f4b00-e36f-11e8-8899-a9476913b1dc.png">

2. After cleaning up, there are several more pods
<img width="613" alt="image" src="https://user-images.githubusercontent.com/20707603/48185895-66c81b80-e371-11e8-9113-6d1953bd8a50.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version :
    rancher/rancher:v2.1.1

- Installation option (single install/HA):
    HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
   Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
   VM
- Kubernetes version (use `kubectl version`): 
   v1.11.3
- System-tools version:
   v0.1.0

**Comment by alena1108** [comment]
@xiaoluhong system-tools only takes care of cleaning up rancher system pods. It won't cleanup user workloads, and this is by design.
