### ISSUE TITLE
The name of the rancher server cluster is not distinguishable in HA setup.

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16513]
Environment:
- Rancher v2.1.2-rc8, 
- High Availability (HA) Install

The cluster **local** is the cluster where rancher server is running, and we don't recommend users to deploy their own workloads on this cluster although they could. So it will be better if we can have a more clear and distinguishable name for this cluster, such like "rancher-server-default".  Or we can have some visual enhancement to notice user not to delete or modify this cluster.
<img width="1699" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/48229099-58bfce00-e364-11e8-9d3e-c4e53414d9e2.png">

**Comment by superseb** [comment]
ref https://github.com/rancher/rancher/pull/15657
