### ISSUE TITLE
L7 balancer (ingress) stucked in "initializing" state

### ISSUE THREAD

**Issue by erikbotta** [rancher/rancher#16519]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Was testing HADR
1) added node to cluster
2) rescaled workload to run on both nodes (workload had L7 balancer(ingress)
3) cordon -> drain -> delete new node

**Result:**
Workload is still accessible via L7 balancer but state of balancer is stucked in: Initializing

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.1
- Installation option (single install/HA):
single install 
Rancher LOG:
[rancher-L7balancer.log](https://github.com/rancher/rancher/files/2566496/rancher-L7balancer.log)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):
root@rancher2:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-138-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: rancher2
ID: WBQ2:M3XP:S6XE:ENLR:IOVU:ZJ6V:DYBC:ANX6:RXKX:KOJU:BQOK:GQTS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
(paste the output here)
```

**Comment by erikbotta** [comment]
<img width="1272" alt="snimek obrazovky 2018-11-09 v 16 47 22" src="https://user-images.githubusercontent.com/832402/48272779-bd9c2680-e43f-11e8-93f5-19969262db21.png">

**Comment by erikbotta** [comment]
![image](https://user-images.githubusercontent.com/832402/48273067-63e82c00-e440-11e8-99d3-7332881fa7a1.png)

**Comment by tfiduccia** [comment]
Version - v2.2.4 
Cannot reproduce.

**Comment by deniseschannon** [comment]
@erikbotta if you can reproduce this, please re-open.
