### ISSUE TITLE
Creating an ARM64 k8s cluster using RKE

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16518]
sub task of https://github.com/rancher/rancher/issues/16461

Detail : https://github.com/jianghang8421/rke/wiki/ARM64-Support

**Comment by loganhz** [comment]
https://github.com/rancher/rke-tools/pull/29
https://github.com/rancher/hyperkube/pull/9
https://github.com/rancher/hyperkube/pull/10
https://github.com/rancher/ingress-nginx/pull/13

**Comment by jianghang8421** [comment]
The following pull requests make the repositories support arm64 architecture and  using `drone1.0` and `docker manifest` for both amd64 and arm64 images build and publish.
- https://github.com/rancher/rke-tools/pull/33
- https://github.com/rancher/ingress-nginx/pull/16
- https://github.com/rancher/hyperkube/pull/13
- https://github.com/rancher/hyperkube/pull/14
- https://github.com/rancher/hyperkube/pull/15

The following two pull requests make rke can create arm64 kubernetes using the default versions and  system images defined in `rancher/types`.
- https://github.com/rancher/types/pull/690
- https://github.com/rancher/rke/pull/1107

**Comment by AWDDude** [comment]
This is super exciting, can wait for arm support in rke/rancher. 
I see one issue however, it seems that arm64 is being targeted, however Raspbian (probably the most prolific ARM based OS) is only ARMv7 32bit. Is there a plan to offer ARMv6 or ARMv7 builds of RKE/rancher?

**Comment by loganhz** [comment]
@kingsd041 Please test it with RKE v0.2.0-rc8

**Comment by loganhz** [comment]
Please test with RKE v0.2.0-rc9

**Comment by kingsd041** [comment]
Version: master 2.2 (3/15/19) 
Confirmed fix.
According to https://github.com/rancherlabs/the-ranch/issues/215 has completed the Rancher ARM64 test, all test cases passed, I will close this issue
