### ISSUE TITLE
Include External Service in targets dropdown when adding targets for Load Balancer.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1651]
Server version - V0.30.0-rc2
UI build from master

Include External Service in targets dropdown when adding targets for Load Balancer.

**Comment by vincent99** [comment]
All external, alias, and balancer services were missing.  Fixed, but we don't know how balancers pointing to an external hostname works so those are hidden from the list for balancer targets.

**Comment by sangeethah** [comment]
Tested with server version - V0.30.0-rc3.
External Services is included in targets dropdown when adding targets for Load Balancer
