### ISSUE TITLE
Ingres broke after edit via kubectl

### ISSUE THREAD

**Issue by tgruenert** [rancher/rancher#16516]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Setup single Node Rancher2 
* Create demo workload from https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/
* create second ingres 'demoonhostname' via Rancher WebGUI with custom url and port 80
* with Rancher CLI `.\rancher.exe kubectl edit ingress demoonhostname`

**Result:**
Editor open config file but changed serviceName tp some ingres specific key instead. It should be the name of the workload.
After Change the path and saving the changed configuration, Rancher WebUI Show N/A for target for the ingres. The Service is no longer available.

**Other details that may be helpful:**

**Environment information**
- Rancher version 2.1.1
- Installation option is single
- Host is Linux
- Cmd-Line Rancher CLI on Windows

**Cluster information**
- Cluster type (Custom):
- Machine type VM and specifications (CPU/memory):
- Kubernetes version 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker (use `docker info`):
```
Docker version 17.03.2-ce, build f5ec1e2
root@some.tld:~# docker info
Containers: 45
 Running: 29
 Paused: 0
 Stopped: 16
Images: 19
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: some.tld
ID: G7C4:JW6H:IXFI:OBT3:Z4HB:DZTU:BIHX:BI4U:VHIK:SQIW:AIZM:MZDT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
