### ISSUE TITLE
GUI is needed for installing Rancher

### ISSUE THREAD

**Issue by JanoschDeurer** [rancher/rancher#16527]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

All installation descriptions that I found included manual UI steps for setting the initial password. It would be great to be able to e.g. provide this as an environment variable to the Docker container. The same holds for API Keys, where manual creation is necessary. 

**Environment information**
- Rancher 2 afaik all versions

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/16225, this has been discussed before.

**Comment by JanoschDeurer** [comment]
Hey, thanks for the fast response, it would be great, if this would find its way into the manual.
