### ISSUE TITLE
Backport: Remove local cluster when --add-local set to false

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16523]
Backport https://github.com/rancher/rancher/issues/16522

**Comment by alena1108** [comment]
helm chart fixes to provide user with an option to reset --add-local: https://github.com/rancher/rancher/issues/16521

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/pull/16550

**Comment by cjellick** [comment]
available in v2.1.2-rc10

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc10
HA setup w/ helm installation

Test cases: 

* Fresh install w/ addLocal=false
  * local cluster is not added, node agents & cluster agent not running
    * Pass

* Upgrade to same version w/ `addLocal=auto`
  * local cluster is added back, node agents & cluster agent started and running
    * Pass

* Fresh install w/ `addLocal=auto` explicitly set
  * local cluster is added, node agents & cluster agent are running
    * Pass

* Upgrade to same version with `addLocal=false`
  * local cluster is removed, agents should be removed
    * Fail - cluster & node agents are still running, cluster agent replicaset remains

* Fresh install w/ `addLocal` not included in set options
  * local cluster is added, node agents & cluster agent are running
    * Pass

* Fresh install w/ `addLocal=auto`, deploy some workloads to local cluster, upgrade to same version w/ `addLocal=false`. View workloads still running through kubectl but the local cluster is not present in UI & agents are not running, then upgrade to `addLocal=auto`
  * cluster added to UI, agents running, workloads should still be present in UI
    * Incomplete (blocked - #16571)

**Comment by erikwilson** [comment]
The fix for this issue is in rancher/rancher:v2.1.2-rc12 (not rc10)

**Comment by bmdepesa** [comment]
@erikwilson this issue was for the original feature available in rc10

We are tracking the failing cases in #16596 and #16602, once all are resolved this issue will be closed.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc14
HA setup w/ Helm install

All test cases detailed above are passing.
