### ISSUE TITLE
Remove local cluster when --add-local set to false.

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#16522]
**What kind of request is this (question/bug/enhancement/feature request):**
There is an option for adding the local cluster or not. Unless this is set on initial install, you can not remove the local cluster from an HA Rancher install.

**Comment by jgreat** [comment]
Or ability to remove the "local" cluster from the GUI.  Right now there is no "Delete" option in the cluster ellipsis menu.

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/16521

**Comment by alena1108** [comment]
@jgreat @kinarashah @cloudnautique  Before committing to the fix, we should make sure that removing local cluster won't result in workloads removal on it. So if prior to upgrade user had workloads in the local cluster, then local cluster got disabled, re-enabling it should bring the cluster with the workloads back to the UI

**Comment by alena1108** [comment]
We are going with the fix where local cluster will be removed only when `--add-local` is passed as false to the rancher server start.

**Comment by bmdepesa** [comment]
rancher/rancher:master

All test cases detailed in #16523 are passing

**Comment by ainiml** [comment]
Will rancher then create a new cluster? The docs weren't very clear about this, when installing Rancher with helm

**Comment by vincent99** [comment]
The cluster always exists and continues to; the flag just controls whether it is exposed through the Rancher API (and UI) or not.
