### ISSUE TITLE
SAML/Keycloak always logged in as admin - no user mapping

### ISSUE THREAD

**Issue by tobru** [rancher/rancher#16539]
**What kind of request is this (question/bug/enhancement/feature request):** question/bug (unclear yet)

**Steps to reproduce (least amount of steps as possible):**

Configured Keycloak authentication as described [here](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/) with additional information from #16004 and rancher/docs#951.

Keycloak configuration:

![screenshot_20181110_214644](https://user-images.githubusercontent.com/1695957/48305834-2237ae00-e532-11e8-8161-ab41d4d0b208.png)

Rancher configuration:

![screenshot_20181110_214753](https://user-images.githubusercontent.com/1695957/48305838-472c2100-e532-11e8-8c0a-0a6a82a2eea2.png)

(Why is the "Rancher API Host" field red?)

![screenshot_20181110_214927](https://user-images.githubusercontent.com/1695957/48305852-7f336400-e532-11e8-8a0d-9a11a11201cc.png)

**Result:**

Login with Keycloak works, but no matter which user is logging in, every user is mapped to the `admin` user - every time. No new user is created and the mapping doesn't seem to be updated.

**Other details that may be helpful:**

I've read the information in [External Authentication Configuration and Principal Users](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/#external-authentication-configuration-and-principal-users) and I understand that the local user logged in during initial SAML/Keycloak configuration gets mapped to the admin user. But I do not understand how it should work with other users. Do they have to be pre-created? How does the mapping happen? 

Also after login using Keycloak, no user icon is displayed anymore:

![screenshot_20181110_215325](https://user-images.githubusercontent.com/1695957/48305901-0da7e580-e533-11e8-8639-bf12d4d3e7a6.png)

When wanting to switch to "Allow members of Clusters, Projects, plus Authorized Users and Organizations", no group can be selected:

![screenshot_20181110_215544](https://user-images.githubusercontent.com/1695957/48305931-637c8d80-e533-11e8-92f0-81776e08f5af.png)

Where should these groups come from?

I've manually created a local user which has the same user id as a user which is able to authenticate using Keycloak, but also no mapping happened.

I'm puzzled how to configure a properly working Keycloak authentication, maybe someone is able to shed some light?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): IaaS, created using rke
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tobru** [comment]
I was able to track this down to missing/incorrect Mapper configuration in Keycloak. It didn't match between Keycloak and the values configured in Rancher.

It would have helped if Rancher would complain that this mapping is incorrect - or at least not just silently login every user as admin. I see this as a security issue: An incorrect IdP configuration could lead into a situation where every user is admin. I would prefer a failed login instead of users just being admin if something is wrong.

**Comment by klainte** [comment]
Hi,
Could you elaborate on your Keycloak client mapper configuration?

**Comment by tobru** [comment]
The Mapping looks like this:

![screenshot_20181113_150420](https://user-images.githubusercontent.com/1695957/48418363-68b92280-e755-11e8-9025-78dd9fb22f28.png)

And an example detail configuration:

![screenshot_20181113_150452](https://user-images.githubusercontent.com/1695957/48418398-7bcbf280-e755-11e8-9580-7308f09b05c2.png)

The group mapping does not work yet, I still have to figure out how to properly do that.

**Comment by tobru** [comment]
Group mapping also works, the SAML attribute gets correctly transported to Rancher:

![screenshot_20181113_152229](https://user-images.githubusercontent.com/1695957/48419329-ef6eff00-e757-11e8-878b-5b62387aa829.png)

**Comment by mrajashree** [comment]
Hi @tobru, every Keycloak user could be getting logged in as the same user in Rancher, if the UID field in Rancher isn't configured correctly. It should be a field from Keycloak that is unique for every user. Rancher doesn't have a way to differentiate between incorrect field names and correct ones, but we are adding a fix to disable user creation if the UID field value isn't present for a particular user. Please refer this issue https://github.com/rancher/rancher/issues/15530#issuecomment-420460541
Based on your last comments, do you have it working now after getting the correct mapping, or are you still facing the same issue?

**Comment by tobru** [comment]
>  Based on your last comments, do you have it working now after getting the correct mapping, or are you still facing the same issue?

Everything is working now as expected and I guess #15530 solves my concern with the login issue described above.
