### ISSUE TITLE
Load Balancers Should Have Editable Scheduling Parameters

### ISSUE THREAD

**Issue by andrewmunsell** [rancher/rancher#1653]
Right now, load balancers (as far as I can tell) cannot be scheduled onto certain hosts like other services can. Ideally, you should be able to specify scheduling parameters for the load balancer service much like other services so that you know which IPs to configure DNS for.

**Comment by vincent99** [comment]
This is in the next release.

**Comment by andrewmunsell** [comment]
Thanks, I just found the relevant change log item. I'll go ahead and close this since it's already implemented.
