### ISSUE TITLE
EKS Options in Rancher for us-east-2

### ISSUE THREAD

**Issue by eaf-josephportello** [rancher/rancher#16532]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

Attempt to launch EKS Cluster.

**Result:**

us-east-2 is not available. It reached general availability a few days ago.

[Amazon Announcement](https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-eks-available-in-ohio-region/)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:latest
- Installation option (single install/HA): Single install, Ubuntu 18.04

**Comment by superseb** [comment]
Thanks for your report, I merged it into https://github.com/rancher/rancher/issues/17081
