### ISSUE TITLE
As soon as shibboleth auth is enabled successfully , user is brought back to auth page where there is "none" entry added to site access list.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16535]
Rancher server version - v1.6.24-rc3

Steps to reproduce the problem:
Have 3 fqdn entries - fqdn1, fqdn2 and fqdn3 point to same Rancher server instance.
Access rancher server using fqdn1 , set "host registration url" as fqdn1 and enabled Shibboleth provider.
Once  shibboleth auth is enabled successfully , user is brought back to auth page where there is "none" entry added to site access list.

Expected behavior:
The admin user should be added to the site access list.

**Comment by mrajashree** [comment]
This has always been the case. Can be reproduced for 1.6.14 too

**Comment by alena1108** [comment]
Moving to the next milestone as the issue is not a regression in 1.6.24 rc
