### ISSUE TITLE
Etcd snapshots continue to be saved even after disabling snapshots

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#16531]
**Environment information**: v2.1.2-rc9

**Steps to reproduce (least amount of steps as possible):**
1. Create a DO cluster(RKE) with snapshots enabled every 5m
2. Ensure snapshots are created in /opt/rke/etcd-snapshots directory 
3. Edit the cluster, disable snapshots and save
4. Wait for the cluster to completely update

The snapshots are created even after snapshots are disabled.

**Comment by sangeethah** [comment]
Rancher server version : v2.1.2-rc11

Steps to reproduce:

Create a DO cluster(RKE) with snapshots enabled every 5m
Ensure snapshots are created in /opt/rke/etcd-snapshots directory
Edit the cluster, disable snapshots and save
Wait for the cluster to completely update

In the etcd nodes, etcd-rolling-snapshots container  gets terminated and no more snapshots are taken after this.
