### ISSUE TITLE
Rancher Pipeline's jenkins init failed due to no resource quotas

### ISSUE THREAD

**Issue by jagjag** [rancher/rancher#16538]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug of rancher pipeline

**Steps to reproduce (least amount of steps as possible):**

another resouce limit related  bug was found.
Pipeline  deployment  failded in a resouce quota namespace:
![image](https://user-images.githubusercontent.com/1321754/48302055-1f3cbd80-e532-11e8-9884-0bbd0229d237.png)
this project had resource limit quota, so jenkins failed to start
![image](https://user-images.githubusercontent.com/1321754/48302074-5dd27800-e532-11e8-9b38-f1467a2dd669.png)

**Result:**
manual add resource quota to rancher pipeline 's jenkins and etc.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher helm 2.1.1
kubernetes 1.11.3-rancher-1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

same to
https://github.com/rancher/rancher/issues/16505

- Docker (use `docker info`):
same to
https://github.com/rancher/rancher/issues/16505

**Comment by cjellick** [comment]
if there's a separate UI ticket, i think should keep the status/to-test label

**Comment by loganhz** [comment]
@aiwantaozi please validate it

**Comment by aiwantaozi** [comment]
Validate result: failed
Server version: master
Cluster have one node 2 cores, 8G memory
Validate step:
1. create a project, add resource quota cpu limit 2000 milli, memory 1024M, default namespace quota set same as before
2. enable pipeline repo in example, run rancher/pipeline-example-go
3. get error below
![image](https://user-images.githubusercontent.com/5936271/52837921-b74ad400-312b-11e9-933f-2955e2011615.png)

4. I also try to use other quota 
4.1 only use cpu limit, could deploy the pipeline success
4.2 use memory reservation, set to 100M, get the same error
4.2 use secret limit, set to 500, get the same error

**Comment by gitlawr** [comment]
When project quota is set, resource quota in a namespace is set to all zero on creation and then update to the default ns quota. The error happens If the resources are created before the resource quota is synced.

**Comment by aiwantaozi** [comment]
Reopened, validate failed

**Comment by cjellick** [comment]
I think we need more details on why validation failed

**Comment by gitlawr** [comment]
With the following steps:

1. Create a new project `test` with 2000 CPU reservation for both project and the default namespace quota
2. Create a namespace `ns1` in project `test` with the default 2000 CPU reservation
3. Run pipeline

Build fails with the error: `Error create secret: exceeded quota...`

When the project quota is used up, the dedicated pipeline namespace cannot fit in the project with the default namespace quota. So its resource quota is set to everything zero.
I think this is an expected result, but we can improve the error handling to show better message.

**Comment by loganhz** [comment]
@aiwantaozi Please validate it

**Comment by aiwantaozi** [comment]
Validate in two several environments:
* One node gke cluster: **Failed**
Environment: 8C 26G, kubernates version: v1.12.5-gke.5
  * Case one: 5C 5G configure without other namespaces 
      1. add project with 5C cpu limit, 5G memory limit, default namespace 5C 5G, no exist namespace before
      2. enable pipeline sample repo, and run it
      3. failed, UI show
![image](https://user-images.githubusercontent.com/5936271/53949411-f2c23800-4104-11e9-9c7e-bfefbd0cf3bc.png)
   * Case two: 5C 5G 25 sercret limit configure without other namespaces 
      same step, same result
* One node do cluster: **Failed**
Environment: 8C 32G NYC3 region, kubernates version: v1.13.4
Same case above, same result
* Three nodes gke cluster: **Success**
Same case one and case two but success
   * Case three: 10C, 10G, defalut namesapce quota is 5C 5G
      1. add project with 10C cpu limit, 10G memory limit, default namespace 5C 5G, create one namespace before enable pipeline
       2. enable pipeline sample repo, and run it
       3. pipeline success run

**Comment by aiwantaozi** [comment]
Test base on the latest doc: https://github.com/rancher/docs/pull/1115
Pipeline resource quota strategy
```
Rancher sets default compute resources for pipeline steps except for Build and Publish Images and Run Script steps. You can override the default value by specifying compute resources in the same way.
```

goal：after configuring project quota, could run pipeline by config resource quota in pipeline yaml and slave default resource quota

Case:
1. after enabling github/gitlab，update executor resources under project-tools-pipeline, expecting Jenkins agent use the resource quota we configured
2. could configure pipeline step resources quota
3. try above case in different for one node and multiple node cluster

Verify success.
