### ISSUE TITLE
Wrong version detection for Catalog apps when running on GKE

### ISSUE THREAD

**Issue by yasker** [rancher/rancher#16543]
When installing an app with GKE, the error shows:

```
^1.8.x which is incompatible with Kubernetes v1.10.9-gke.3
```

**Comment by deniseschannon** [comment]
Per @yasker this is working in the latest version.

**Comment by yasker** [comment]
This has been resolved. Helm chart needs something similar to https://github.com/rancher/charts/blob/master/proposed/longhorn/latest/Chart.yaml#L5 to deal with special version of Kubernetes.
