### ISSUE TITLE
Question - Moving rancher server and rancher agent 

### ISSUE THREAD

**Issue by anaryk** [rancher/rancher#16544]
Hello, I should have such a request. I've been solving the problem for a few days but unsuccessfully, and since my knowledge of Rancher and the docker is marginal, but unfortunately I have to do it so I turn to you because I do not know the advice anymore. Set the situation. Now the rancher server runs on vps and rancher agent on a dedicated server at one hosting company that also used the rancher as a basis for client sites that are assembled to help commit into gitlab. I'm trying to find the simplest solution that both the server and the agent can move to the same medium elsewhere. New VPS for rancher server and new dedicated server for rancher agent. And I needed some export or something like all the stacks to get into that new location. If I could transfer the server directly, it would be simple, but it does not have to be moved just after the software page. Both the server and the agent run rancher 1.6. I would like to ask for help if you have any instructions, it would help me the most.
Thx

**Comment by superseb** [comment]
Make sure you have proper backups and test before actual moving everything. Moving `rancher/server` is described in here: https://gist.github.com/superseb/f44d51cc42c7e5a0049d393d6d2563e7. 

Is there anything specific agent wise you need to move, do you mean that the server is running server and agent? `/var/lib/rancher` is where state is on the host for the agent, it can be moved to retain its identity in Rancher but possibly re-adding it would be just as easy. (again, don't know what you are looking for agent wise)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
