### ISSUE TITLE
There are errors in RKE's deployment of rancher

### ISSUE THREAD

**Issue by yangjia517** [rancher/rancher#16546]
hi~

My problem：

system:ubuntu16.04.5
docker:17-03-2

Installing rancher cluster through RKE：
![image](https://user-images.githubusercontent.com/33953118/48345142-2be81f80-e6b2-11e8-834e-df117645104b.png)
When the installation is finished, is this normal?
![image](https://user-images.githubusercontent.com/33953118/48345221-6782e980-e6b2-11e8-9247-b3448373870e.png)
![image](https://user-images.githubusercontent.com/33953118/48345300-a44ee080-e6b2-11e8-9551-1d44807b0c96.png)
Under normal circumstances, should it be displayed in green?

**Comment by superseb** [comment]
Agents are connecting back to the configured `server-url`, is that resolvable in DNS and reachable by the cluster nodes?

`kubectl -n cattle-system logs -l app=cattle-cluster-agent`
`kubectl -n cattle-system logs -l app=cattle-agent`

**Comment by yangjia517** [comment]
> 代理连接回配置`server-url`，是否可在DNS中解析并可由群集节点访问？
> 
> `kubectl -n cattle-system logs -l app=cattle-cluster-agent`
> `kubectl -n cattle-system logs -l app=cattle-agent`

How do I adjust it? I still can't work now.

**Comment by superseb** [comment]
The `nodes` part in your `cluster.yml` does not show `192.168.103.216`, so not sure what cluster setup you are using currently. The logging shows that there are no nameservers specified in `/etc/resolv.conf` on `192.168.103.216` and the error also shows it cannot resolve your configured `server-url`. The configured `server-url` should be a DNS resolvable name, and the hosts need to have proper name resolution configured. I can't tell wether `rancher-master` is any of these nodes, but that does seem to have a nameserver configured.

For the second error, the name resolving goes well via the cluster DNS (a bit of an assumption) but it can't connect to the configured `server-url` on TCP/443. This needs to be open from all nodes to the configured `server-url`.

**Comment by yangjia517** [comment]
> The `nodes` part in your `cluster.yml` does not show `192.168.103.216`, so not sure what cluster setup you are using currently. The logging shows that there are no nameservers specified in `/etc/resolv.conf` on `192.168.103.216` and the error also shows it cannot resolve your configured `server-url`. The configured `server-url` should be a DNS resolvable name, and the hosts need to have proper name resolution configured. I can't tell wether `rancher-master` is any of these nodes, but that does seem to have a nameserver configured.
> 
> For the second error, the name resolving goes well via the cluster DNS (a bit of an assumption) but it can't connect to the configured `server-url` on TCP/443. This needs to be open from all nodes to the configured `server-url`.
I am puzzled. I explained the deployment process again. This problem has been plagued for a long time.
First, I created the cluster.yml file on the host (103.216) (minimize the installation), and installed the rancher in the helm mode according to the official documentation (although there is a node)
Secondly, when I executed the helm installation rancher, I modified the domain name to rancher.itrus.com and successfully completed the installation work (the domain name is not resolved by the public network);
Finally, I installed the nginx service on the host of rke (103.215), proxyed the master, and filled in the files of my native windows's hosts file (192.168.103.215 rancher.itrus.com), which can be accessed through the browser. The interface of rancher, finally observed that the system space in the local cluster created by rancher has 2 pod exceptions, and the error is as above.
How can I deal with this problem and hope to get it?

**Comment by yangjia517** [comment]
> `nodes`您的部分`cluster.yml`未显示`192.168.103.216`，因此不确定您当前使用的是哪种群集设置。该记录显示，没有在指定的域名服务器`/etc/resolv.conf`上`192.168.103.216`以及错误也说明它无法解析您的配置`server-url`。配置的`server-url`应该是DNS可解析的名称，并且主机需要配置正确的名称解析。我不知道是否`rancher-master`有任何这些节点，但似乎确实配置了名称服务器。
> 
> 对于第二个错误，名称解析通过群集DNS（一点假设）很顺利，但它无法连接到`server-url`TCP / 443上的配置。这需要从所有节点打开到配置`server-url`。

![image](https://user-images.githubusercontent.com/33953118/48470957-cb7ded00-e82d-11e8-8a8c-ae65491d5f08.png)

The problem has been solved, but I would like to ask the reason, if I install the rncher without specifying the domain name is OK?
![image](https://user-images.githubusercontent.com/33953118/48470977-d6d11880-e82d-11e8-9b6e-36062dcf9193.png)

**Comment by superseb** [comment]
I don't think there is a bug here. The setup requires proper name resolving, and that's clearly missing here. Working around it by adding names to `/etc/hosts` is not really a clean solution but might work if the hostname/IPs stay the same. It's not the recommended setup.

The hostname set is used to route the incoming request to the appropriate backends when hitting the NGINX ingress controller. This is at all times a required setting.
