### ISSUE TITLE
[RKE] Flannel/Calico ignores --address and --internal-address

### ISSUE THREAD

**Issue by xorpierre** [rancher/rancher#16542]
I been trying to setup any custom node (KVM Ubuntu 18.06) with rancher but flannel always starts up with the wrong interface, even if I switched interface (because I read flannel selects the first it finds) it actively selects the other one again. I don't get how it even selects the wrong interface, even if I switch them around it uses the wrong one every time (like wtf?).

In rancher UI and CLI I set --address flag and every other cluster option to specify the flannel interface but it always uses the wrong one.

latest rancher stable version v2.1.1

from logs:

{"log":"I1111 14:35:26.599341       1 main.go:488] Using interface with name eth1 and address 192.168.0.3\n","stream":"stderr","time":"2018-11-11T14:35:26.602484757Z"}

executed:
docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.1 --server https://10.3.1.1 --token xxxxxxxxx --ca-checksum xxxxxxxxxx --address eth0 --internal-address $(ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://') --etcd --controlplane

cluster.yml:
network: 
  options: 
    flannel_backend_type: "vxlan"
    flannel_network_provider: "map[iface:eth0]"
  plugin: "flannel"

**Comment by xorpierre** [comment]
related https://github.com/rancher/rancher/issues/11365

**Comment by xorpierre** [comment]
I can't change the title but its not flannel bug but RKE bug.
Same for Calico: 
startup.go 564: Using autodetected IPv4 address on interface eth1: 192.168.0.3/24\n","stream":"stdout","time":"2018-11-11T15:59:02.623674833Z"}

**Comment by superseb** [comment]
It's a separate setting to the network plugin as described in https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/network-plugins/#flannel-network-plug-in-options

Let me know if that doesn't solve the issue.

**Comment by xorpierre** [comment]
That's the first thing we tried. I tested all possible options and reasons for the last 12 hours, not once I had the right interface.

**Comment by superseb** [comment]
Please describe the steps to reproduce as requested in the issue template.

**Comment by xorpierre** [comment]
reason of failure: docker 18.06
seems like a RKE issue, not necessarily a K8S problem
