### ISSUE TITLE
Need to define order for acl rules with only hostname / only path name entries.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1654]
Server Version - V0.30.0-rc2

Create LB rule for 2 services - s1 and s2 with following rules:
target1 - hostname - "abc" service - "s1"
target2 - path - "/test1" service - "s2"

When trying to access , http://<ipaddress>:port/test1 with header set to "abc" , we could hit containers from service s1/s2.

Currently there is no defined order to program acl rules with only hostname / only path name entries in haproxy. There needs to be an order defined for it.

**Comment by alena1108** [comment]
the order is:

* hostName and url
* just host name
* just url
* default

**Comment by sangeethah** [comment]
Tested with server version - rancher/server:v0.31.0-rc1 

The following order is enforced when programming haproxy:
hostName and url
just host name
just url
default

<img width="628" alt="screen shot 2015-07-29 at 4 03 45 pm" src="https://cloud.githubusercontent.com/assets/4266958/8972082/7358e148-360b-11e5-8a77-812f9978e650.png">
