### ISSUE TITLE
【 Help Nedded】How to compile and take effect by modifying vendor Module Code ？

### ISSUE THREAD

**Issue by Angel0507** [rancher/rancher#16545]
Steps to reproduce (least amount of steps as possible):

1. i modify vendor module code of rancher server (vendor/k8s.io/kubernetes/pkg/apis/core/v1/defaults.go)  
   then compile rancher , it doesnot take effect .
2. i modify vendor.conf file(k8s.io/kubernetes     v1.10.5-rancher-v2-1    https://github.com/rancher/kubernetes.git 
   transitive=true,staging=true) , it doesnot take effect as well .
   
 **so i want to know if i need to modify other configurations or something else , thx?**

Environment information:
	
1. Rancher server version : origin/release/v2.0.8
	
2. docker version
	Client:
	 Version:      17.09.0-ce
	 API version:  1.32
	 Go version:   go1.8.3
	 Git commit:   afdb6d4
	 Built:        Tue Sep 26 22:39:28 2017
	 OS/Arch:      linux/amd64

	Server:
	 Version:      17.09.0-ce
	 API version:  1.32 (minimum version 1.12)
	 Go version:   go1.8.3
	 Git commit:   afdb6d4
	 Built:        Tue Sep 26 22:45:38 2017
	 OS/Arch:      linux/amd64
	 Experimental: false

3. kubernetes version: 1.8.4

**Comment by loganhz** [comment]
You can fork the vendor which you would like to modify and do something like this.

https://github.com/rancher/rancher/pull/17237/files#diff-4061fcef378a6d912e14e2ce162a1995R43

Then you can just run `make` to compile and build it.
