### ISSUE TITLE
Rancher 1.6 UI cannot process 403 error code for SAML auth redirects

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#16554]
Rancher server v1.6.24-rc2 (Also exists in prior versions)
When api redirects to rancher host with 403 error code, the following page is shown
<img width="1391" alt="screen shot 2018-11-12 at 1 44 27 pm" src="https://user-images.githubusercontent.com/10672776/48378107-9edaa180-e684-11e8-9c2e-1b2a9afccc22.png">

But with error code 401/500 the UI shows up correctly.
<img width="1046" alt="screen shot 2018-11-12 at 1 58 13 pm" src="https://user-images.githubusercontent.com/10672776/48378104-9aae8400-e684-11e8-8682-6b526f392bd1.png">

Looks like 403 code isn't being handled correctly. Same with 422 error code

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher/issues/16534

**Comment by alena1108** [comment]
Can be tested with rancher/server:v1.6.24-rc4
