### ISSUE TITLE
Backport: Ingress not able to reach one of the pods because of missing flannel annotations on the nodes

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16552]
Backport https://github.com/rancher/rancher/issues/13644

**Comment by cjellick** [comment]
@kinarashah backport issues shoudl go to test until and RC is cut containing them

**Comment by sangeethah** [comment]
Tested with rancher-server version v2.1.2-rc13. 

Created a cluster with 1 control node , 3 etcd nodes and 30 worker nodes.
Cluster gets created successfully and all the worker nodes have the flannel annotations as expected.

The above test was done multiple times and in all the cases the  all the worker nodes have the flannel annotations as expected.

Related issue seen when trying to create a cluster with 1 control node , 3 etcd nodes and 30 worker nodes - https://github.com/rancher/rancher/issues/16669
