### ISSUE TITLE
[API] v3 invalid action resume

### ISSUE THREAD

**Issue by yl-yue** [rancher/rancher#16565]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
1. request api action=pause
2. request api action=resume

**Result:**
The workload does not redeploy every time

**Environment information**
- Rancher version: v2.1.1
- Installation option (single install/HA): single

**Comment by vincent99** [comment]
As we've [covered before](https://github.com/rancher/rancher/issues/14953), that is [not what pause is](https://github.com/rancher/rancher/issues/14935#issuecomment-410296084) and [not for redeploying](https://github.com/rancher/rancher/issues/15387#issuecomment-432548566).
