### ISSUE TITLE
rancher 2.0 can't kubectl get all 

### ISSUE THREAD

**Issue by xiaods** [rancher/rancher#16564]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

aws, ubuntu 14.04, single install
**Result:**

click rancher console button: [lunch kubectl], it print errors:

```
# Run kubectl commands inside here
# e.g. kubectl get all
su: System error
command terminated with non-zero exit code: Error executing in Docker Container: 1
```
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
ubuntu@ip-172-31-3-103:~$ docker info
Containers: 109
 Running: 65
 Paused: 0
 Stopped: 44
Images: 272
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-202:1-524301-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 40GB
 Data Space Total: 107.4GB
 Data Space Available: 67.38GB
 Metadata Space Used: 49.67MB                                                                                                                                                    
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.098GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340

```

**Comment by superseb** [comment]
This issue is missing a lot of information but both the OS and Docker are unsupported. Docker 18.06 can be used with the experimental support for k8s 1.12. We've seen issue with 14.04 before in https://github.com/rancher/rancher/issues/14095

Please create a new issue with all requested info if you are still experiencing issues on a supported setup.
