### ISSUE TITLE
[redeploy] Redeploy via API

### ISSUE THREAD

**Issue by yl-yue** [rancher/rancher#16567]
**What kind of request is this (question/bug/enhancement/feature request):**
question/enhancement

**Question explain**
How to redeploy via API

![image](https://user-images.githubusercontent.com/39790401/48405812-fc96e880-e76d-11e8-8db5-f00cc7ca6732.png)

**Comment by yl-yue** [comment]
@loganhz Hope API enhancement thanks!

**Comment by deniseschannon** [comment]
Anything done in the UI can be done through the API. Please "view in API" to see the operation and you can see the API calls.

**Comment by vincent99** [comment]
"Redeploy" sets an annotation on the workload with the current time as the value, which causes k8s to do a redeployment because the definition has changed.

**Comment by yl-yue** [comment]
@vincent99 Thank you. That's how I've implemented CDS so far

**Comment by dlednik** [comment]
does anyone have a `curl` command to perform this operation from cmd line?

**Comment by yl-yue** [comment]
> does anyone have a `curl` command to perform this operation from cmd line?

I'm using the curl command to invoke an intermediate service that accesses the rancher API over HTTP for workload details, changes the time field in the load, and submits it to the rancher implementation's CD

**Comment by dlednik** [comment]
@yl-yue question was if anyone can share curl command so we don't need to reinvent the wheel to make it work

**Comment by yl-yue** [comment]
> @yl-yue question was if anyone can share curl command so we don't need to reinvent the wheel to make it work

But just with `curl` for workload upgrades, exist rancher Bearer token issue.
If you customize a wheel, you can also add some notifications you want

**Comment by dlednik** [comment]
got it :+1:
