### ISSUE TITLE
Ingress cannot broker external services(Services Resolves To External IP)

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#16561]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. There is a web service at 192.168.1.19:8881
2. Switch to the `Workloads`/`Service Discovery`, add external services (Services Resolves To External IP)
<img width="982" alt="image" src="https://user-images.githubusercontent.com/20707603/48392926-6a301e00-e748-11e8-83d4-d54369f70344.png">

3. Add ingress in Load Balancing
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/20707603/48393001-b24f4080-e748-11e8-9023-82952e7057d8.png">

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/20707603/48393032-da3ea400-e748-11e8-87d2-c6f5e9682492.png">

**Result:**
1. Access the generated xip.io suffix domain name，the return status is 503. 
<img width="730" alt="image" src="https://user-images.githubusercontent.com/20707603/48394838-0b6ea280-e750-11e8-8b9c-096cfe9c8db7.png">

2. Curl is used in other pods to return information normally
<img width="512" alt="image" src="https://user-images.githubusercontent.com/20707603/48393634-53d79180-e74b-11e8-8832-2ed280c36294.png">

3. View the nginx configuration file generated by ingress, no external service for upstream configuration
<img width="771" alt="image" src="https://user-images.githubusercontent.com/20707603/48394129-46230b80-e74d-11e8-8822-27696e6c35dc.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version:
    rancher/rancher：v2.1.1

- Installation option (single install/HA):
    All

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15809
