### ISSUE TITLE
Lb agents of original LB service shown in UI for cloned services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1656]
Server version - v0.30.0-rc3

Steps to reproduce the problem:
Create LB service and activate it.

Clone another LB service from this LB service.
The cloned LB service shows the Lb agent (even when it is not activated yet) from the original LB service it was cloned from.

When  UI is refreshed , lb Agent is not shown anymore. 

<img width="726" alt="screen shot 2015-07-26 at 8 11 43 am" src="https://cloud.githubusercontent.com/assets/4266958/8894514/2361ce88-336e-11e5-92c4-108be955d89c.png">

**Comment by deniseschannon** [comment]
+1 Very weird UI with this. Saw it when testing out my demo.

**Comment by deniseschannon** [comment]
Still relevant in new UI. v0.49.0-rc1. 

Cloned a load balancer, container from old LB is in LB summary and LB detail view.

**Comment by deniseschannon** [comment]
No longer relevant in the latest UI. 

Verified with v0.57.0-rc5.
