### ISSUE TITLE
nginx.ingress return "503 Service Temporarily Unavailable" with external service

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#16560]
![image](https://user-images.githubusercontent.com/14210543/48392360-f42ab780-e745-11e8-8ff6-000cda0d88fa.png)
![image](https://user-images.githubusercontent.com/14210543/48392464-7d41ee80-e746-11e8-8edf-935361c61bfc.png)
![image](https://user-images.githubusercontent.com/14210543/48392481-964a9f80-e746-11e8-8b2b-2e448bbf607f.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`authenticated.project.dns.index`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15809

**Comment by wuchencm** [comment]
The external hostname is not in my k8s cluster !

apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-bwd57
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  creationTimestamp: 2018-11-13T06:25:20Z
  labels:
    cattle.io/creator: norman
  name: test
  namespace: palteform-dev
  resourceVersion: "3702144"
  selfLink: /api/v1/namespaces/palteform-dev/services/test
  uid: e53f3c9d-e70c-11e8-a883-00163e0c682f
spec:
  externalName: www.baidu.com
  ports:
  - name: default
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}

**Comment by loganhz** [comment]
Please read https://github.com/rancher/rancher/issues/15809#issuecomment-433296055

**Comment by wuchencm** [comment]
Thanks ! it is working.....

**Comment by loganhz** [comment]
@wuchencm cool
I think we can support user to input the port when creating the service for external hostname.
And change the `port` input in ingress page to a dropdown.
