### ISSUE TITLE
Unable to recover worker cluster: 401 Unauthorized after etcd restore

### ISSUE THREAD

**Issue by matthax** [rancher/rancher#16574]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a worker cluster (not using RKE) through the Rancher UI with one node as etcd, worker and control plane
2. `docker exec etcd etcdctl snapshot save /var/lib/rancher/etcd/snapshot.db`
3. `etcdctl snapshot restore /var/lib/rancher/etcd/snapshot.db \
--initial-cluster=etcd-${SHORT_HOSTNAME}=https://${HOST_IP}:2380 \
--name=etcd-${SHORT_HOSTNAME} \
--initial-advertise-peer-urls=https://${HOST_IP}:2380 \
--initial-cluster-token=etcd-cluster-1`
4. `mv /etcd-${SHORT_HOSTNAME} /var/lib/etcd/backup # copy the snapshot to the mounted volume`
5. Exit the container and `systemctl stop docker # or however you need to disable the docker processes`
6. `mv /var/lib/etcd/member /var/lib/etcd/member-old # back up the current etcd state`
7. `mv /var/lib/etcd/etcd-${SHORT_HOSTNAME}/member /var/lib/etcd/`
8. `systemctl start docker`
8. `docker logs kube-apiserver`
**Result:**
`E1113 17:28:22.894593       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]`

**Other details that may be helpful:**
I may have missed a few steps, but essentially I'm taking a worker cluster, not configured with RKE, and trying to snapshot it so that in the event of a cluster failure, we can restore. We attempted to follow the typical etcd failure recovery steps and have not been successful. You may need to wait some time before the restore, in our case the snapshot was about 24 hours old.

Seems to be related to #8388  
May also be relevant to #13688  

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM/metal @ 4CPU/32GB 
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 46
 Running: 19
 Paused: 0
 Stopped: 27
Images: 17
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.26 GiB
Name: ebidev-as-4d.sys.comcast.net
ID: TQRD:L3YE:5PR4:ZEXP:RNHC:OP4B:SPG2:P2R3:NYQC:IAUW:JZGT:WXCT
Docker Root Dir: /app/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by appacea** [comment]
Hello, I have this same issue, were you able to resolve it?

**Comment by fdelahaye-mmtt** [comment]
hello all,
anything new ? 
I have exactly the same issue ...

**Comment by deniseschannon** [comment]
How are these clusters created?

**Comment by deniseschannon** [comment]
In v2.2.2, we've added the ability to back up and restore for RKE clusters:

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/backing-up-etcd/
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/restoring-etcd/

If you're still having issues within v2.2.2, please open a new issue.
