### ISSUE TITLE
Backport: Error while getting agent config: invalid response 500: Failed to validate cluster: Hostname_override [xxx-xxx-KUB02] for host

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16575]
Backport: https://github.com/rancher/rancher/issues/16294

https://github.com/rancher/rke/pull/1027

**Comment by alena1108** [comment]
Fix is available in rancher/rancher:2.1.2-rc11

**Comment by jiaqiluo** [comment]
### Reproduction
**Rancher version**: 2.1.1
**Installation option**: single
**Step**: Added a cluster from an existing node which hostname is uppercased, put all roles on one node
**Result**:
get the following error:
```Failed to validate cluster: Hostname_override [xxx-xxx-KUB02] for host (1) is not valid: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9?(\.a-z0-9?)')]"```
<img width="1517" alt="reproduce-bug" src="https://user-images.githubusercontent.com/6218999/48451368-6364d380-e767-11e8-9399-7ec5a1f13431.png">

### Validation 
**Rancher version**: master, 11/13/2018
**Installation option**: single
**Step**: Added a cluster from an existing node which hostname is uppercased, put all roles on one node
**Result**:
Successfully added the cluster. 

### Conclusion
Back port verified.
