### ISSUE TITLE
Document minimum roles required to a service principal

### ISSUE THREAD

**Issue by alexeyzimarev** [rancher/rancher#16577]
I checked the scenarios in rancher/rancher#11492 and I am doing the first option, adding the cluster that already exists. The cluster was created with the service principal, which I also use in the Rancher form to add a new cluster.

Authentication test completes and I enter the existing resource group. When I get to the list of clusters, the following error message is shown:

> Error getting resource group DevAndTest: resources.GroupsClient#CheckExistence: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

**Comment by alexeyzimarev** [comment]
Ok, I needed to add a role to the service principal, although it is not described anywhere. Now, I get another error:

> Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 > -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="The value of parameter orchestratorProfile.OrchestratorVersion is invalid." Target="orchestratorProfile.OrchestratorVersion"

**Comment by AlexMikhalev** [comment]
bump. Same issue.

**Comment by AlexMikhalev** [comment]
@alexeyzimarev  how did you add the role to service principal?

**Comment by alexeyzimarev** [comment]
@AlexMikhalev I used both `az` and Portal guidelines, same result.

**Comment by aemneina** [comment]
I'd agree we need to document minimum roles required to a service principal to get this working.

**Comment by daxmc99** [comment]
See also docs issue here https://github.com/rancher/docs/issues/1355

**Comment by cjellick** [comment]
So, this is effectively a dupe of the above mentioned docs issue. Moving over to-test

**Comment by davidnuzik** [comment]
Closing in favor of https://github.com/rancher/docs/issues/1355
