### ISSUE TITLE
Make GlobalRoles createable

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16573]
more details to come

**Comment by cjellick** [comment]
will need a UI change as well

**Comment by cjellick** [comment]
need to protect against editing the built in roles

**Comment by alena1108** [comment]
This functionality is needed for cluster templates RBAC

**Comment by ankur111** [comment]
@cjellick note says we need to protect against editing built in role. 
Yet this bug is referencing an issue which allows creating new global roles and setting them as default.
Could you provide more details please?

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/16216
