### ISSUE TITLE
Access Key is saved in edit for EKS with session token

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16576]
Version - 2.2 master 11/13

**Steps to reproduce (least amount of steps as possible):**
1.  Create a EKS cluster with session token
2.  Edit EKS cluster

**Result:**  the Access Key is being automatically filled out.  The Key should not be filled out as all the keys are temporary and will probably need to be replaced.  We fixed this on delete but not on edit.

**Comment by davidnuzik** [comment]
Version - 2.2 master (11/27/18)
Confirmed fixed. I created an EKS cluster with session token, when I edited it the Access Key, Secret Key, and Session Token were all blank. Further, I entered new credentials in these fields and validated POST request headers sent to amazon and our PUT to rancher server to confirm the credentials were there upon form submission.
