### ISSUE TITLE
Validation for snaphot fields are not correct.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16581]
Rancher server version - v2.1.2-rc11

Steps to reproduce the problem:

Create a DO cluster and try to set "Snapshot Creation Period" as 5m.
User is presented with following error:

<img width="1258" alt="screen shot 2018-11-13 at 3 11 57 pm" src="https://user-images.githubusercontent.com/4266958/48449616-07df1980-e758-11e8-9bd4-a2c384d3bf54.png">

Had to provide the value as "0h5m" to move forward.

**Comment by westlywright** [comment]
Will be available in UI Tag 2.1.15

**Comment by cjellick** [comment]
available in available in v2.1.2-rc12 and master

**Comment by tfiduccia** [comment]
Version - 2.1.2-rc12 - verified fixed

**Comment by tfiduccia** [comment]
Version - master 11/14
Verified fixed
