### ISSUE TITLE
Launch the app with a cluster/project-level catalog, and report 500 error

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#16589]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add a catalog at the cluster/project level
2. Use the template under catalog, launch application
3. Click launch

**Result:**
Report 500 error:
`message: "templateversions.management.cattle.io "cluster-new-mysql-0.10.2" not found"`

**Other details that may be helpful:**
Both the public catalog and the private catalog will report an error.

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/42061003/48472293-ebfb7680-e830-11e8-8950-57c3b4b6a0bb.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher/rancher: master

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/16585

The root cause is the same

**Comment by rootwuj** [comment]
Version -2.2 master 10/27
Verified fixed
