### ISSUE TITLE
Add catalog at the cluster/project level, but can't get the template

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#16585]
**What kind of request is this (question/bug/enhancement/feature request):**

bug
**Steps to reproduce (least amount of steps as possible):**

Add a custom git catalog to the cluster or project level, the catalog templates will be deleted automatically after 1 hour, and the logs didn't show any relevant `delete` messages.

**Result:**
Global level templates are fine, but cluster and project level templates will be removed automatically after 1 hour.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher/rancher: master

**Comment by rootwuj** [comment]
I tried again and didn't reproduce the problem.

**Comment by guangbochen** [comment]
@rootwuj is this still a problem or can we close it?

**Comment by guangbochen** [comment]
@mrajashree this issue still exists on the latest master 11/27, can u please help to check it, thanks.
