### ISSUE TITLE
Flannel label text is missing for Custom Clusters

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16580]
Version - 2.1.2-rc11

**Steps to reproduce (least amount of steps as possible):**
1.  Add Cluster
2.  Select Custom
3.  Open Cluster Options
4.  Click on Network Provider drop-down

**Result:** Flannel text is showing I8n label
![image](https://user-images.githubusercontent.com/11514927/48447274-b84d1d80-e758-11e8-919d-b49051758e37.png)

**Comment by westlywright** [comment]
Will be available in UI Tag `2.1.15`

**Comment by cjellick** [comment]
available in v2.1.2-rc12 and master

**Comment by tfiduccia** [comment]
Version - 2.1.2 rc12 and master 11/14
Verified fixed
