### ISSUE TITLE
Add existingClaim option for the charts if applicable

### ISSUE THREAD

**Issue by yasker** [rancher/rancher#16583]
Almost every chart uses persistent volume supports using existing PVCs. But the option was disabled by questions.yaml which used by Rancher. This option is needed if the user wants to persist the volume content beyond the lifecycle of the app.

We need something similar to https://github.com/rancher/charts/pull/41/commits for all the charts which support persistent volume.

If we can enable the user to choose which PVC they want in the current namespace it would be even better.

https://github.com/rancher/charts/issues/47

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/4/19)
Confirmed new feature. See #17060 for details. This was tested in the UI and confirmed working.
