### ISSUE TITLE
I want use rancher in a private cloud(can not access internet), could rancher had a road-map to support that?

### ISSUE THREAD

**Issue by hjianhao** [rancher/rancher#1659]
I found a few problems.

1. When open the home page, some resource require access internet, for example, vender.css, vender.js
2. start rancher agent, it seems like download file from internet.

**Comment by ebuildy** [comment]
Maybe you can setup a transparent proxy and copy/paste the needed files in your server?

**Comment by hjianhao** [comment]
Seems like a not good idea. Should I try to find files need by every pages and needed to download from agent? If resource added or modified in the new version, we will work again to make sure everything is ready?

**Comment by ebuildy** [comment]
You can run Rancher with a transparent proxy that forward traffic to internet AND cache files on disk, then switch off Internet and Rancher should use cached files.

Easy to write but I am not sure about the implementation ;-)

**Comment by deniseschannon** [comment]
Yes, we already have this on our roadmap. https://github.com/rancher/rancher/issues/924

Please follow the other issue to get status updates.
