### ISSUE TITLE
Feature request for namespace information in alerts

### ISSUE THREAD

**Issue by sdillen** [rancher/rancher#16592]
**Feature request for namespace information in alerts**

It would be quite helpful to get the namspace in an alert. At the moment you get for a Pod Event following information:

Alert Name:
Severity:
Cluster Name:
Target:
Count:
Event Message:
First Seen:
Last Seen:

In our case sometimes the targets have nearly an identical name, so it is not possible to see in the first look which workload has problems. 

**Steps to reproduce:**
Set the cluster wide alert for warning event of pod. 

**Other details that may be helpful:**
I didn´t checked all alert types. Maybe it could be useful in some others as well.

**Environment information**
- Rancher version: v2.1.1

**Comment by aiwantaozi** [comment]
The Target will include the namespace, the format will like ```namespace:name```

**Comment by rootwuj** [comment]
Version -2.2 master 01/29
Verified fixed
This version of the alert message includes the project name, pod name, namespace
