### ISSUE TITLE
Mitigate kubernetes API timeouts in rancher server

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16598]
Some cloud providers have APIs that  timeout on get and list requests. The timeout is current set to 30 seconds, which is very long for an API request, but these requests basically hang forever. We need to mitigate this problem in Rancher

Steps to reproduce:
1. Spin up an AKS cluster in Rancher
2. Let the Rancher setup sit for 30-60 minutes without doing anything in the UI
3. Do something in the UI.

Expected result
no timeouts

Actual result
You have a good chance of getting this error
![aks-fail](https://user-images.githubusercontent.com/2473240/48516405-84d5c600-e820-11e8-8acc-5f4bb9ab83cd.png)
:

**Comment by cjellick** [comment]
The fix I'm adding to mitigate this drops the timeout to 15 seconds, but tries the request 3 times, so you could actually get up to 45 seconds of spin in the worst case scenario (generally, the second try just works though).

**Comment by JasonvanBrackel** [comment]
> Would be a UI change. What do you think @vincent99 @westlywright ?
> Under normal circumstances, these calls happen so fast that it wouldnt make sense to flash any text on the screen. But what about some timer logic or something that kicks in after a request goes longer than 3 or 5 seconds?

That makes sense to me if the team agrees.

> 
> Additionally, would you want to special case these timeout errors in anyway that makes it a little more clear about what happened? We're return the raw error message regarding the timeout. Should I send back more user friendly message?

Anywhere we can let the user know what's happening, is a huge win.  A user's tolerance for issues increases significantly when the software is communicating state in a human-friendly way.

**Comment by vincent99** [comment]
I can add something if people we really want, but I don't think it accomplishes anything.  You already know from the animation that you're waiting for something.  Saying "This is taking longer than expected" or "Still loading" doesn't make me feel any better or add any information.

And I don't really have any more useful information to offer; I don't know* which specific requests is being waited on.  I don't know if it's ever actually going to respond, and I don't know whose fault it is that it's taking this long.  It could be the user's computer, their internet connection, Rancher, the cluster provider, or the connection from Rancher to the provider, etc.

*: We could theoretically keep track of all the outstanding requests and know this, but don't currently.

**Comment by soumyalj** [comment]
Reproduced the issue is v2.1.1 as below:
<img width="1399" alt="screen shot 2018-11-23 at 1 28 06 pm" src="https://user-images.githubusercontent.com/18536626/48960719-f2ba7580-ef23-11e8-98b0-6085b3d0cf7c.png">

**Comment by soumyalj** [comment]
Tested with master build from Nov 26th. 
Created AKS cluster . Created few projects and workloads and the setup was left around for 30 to 90 minutes. After the idle time, when navigated to different projects, it was observed that the spin could be longer, but eventually it succeeds without the error message.
