### ISSUE TITLE
Backport: Cluster & node agents are still running after HA install upgraded to addLocal=false 

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16596]
Backport for https://github.com/rancher/rancher/issues/16571

**Comment by cjellick** [comment]
available in v2.1.2-rc12

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc12
rancher/server-chart:master

* Deployed Rancher in HA via helm, with `addLocal=auto`
* Confirmed local cluster is present in UI
* Confirmed the cluster & node agent pods were running
* Confirmed cattle-node-agent daemonset is present
* Confirmed cattle-cluster-agent deployment & replicaset are present
--
* Upgraded to same version w/ `addLocal=false`
* Confirmed local cluster is not present in UI
* Confirmed cluster & node agent pods removed
* Confirmed cattle-node-agent daemonset removed
* Confirmed cattle-cluster-agent deployment and replicaset removed
--
* Upgraded to same version w/ `addLocal=auto`
* Confirmed local cluster is present in UI
* Confirmed all cluster & node agent pods, deployments, and replicasets were present
