### ISSUE TITLE
VMware  Distributed Switch

### ISSUE THREAD

**Issue by tfpereira93** [rancher/rancher#16593]
**What kind of request is this (question/bug/enhancement/feature request):** Question

**Steps to reproduce (least amount of steps as possible):** Assign distributed switch to VMware Node

**Result:**  Error with pre-create check: "network 'VLAN801_10.80.1.0_GERENCIA' not found"; Timeout waiting for ssh key 

**Other details that may be helpful:** Its only a simple question, its possible to use vmware distributed switch in the network name? Or just vmware standard switch? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM and default specifications 
- Kubernetes version (use `kubectl version`): 
```

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):
```

Containers: 23
 Running: 14
 Paused: 0
 Stopped: 9
Images: 17
Server Version: 17.03.3-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.5 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: EQXPLRANAPP01
ID: QTMZ:HI5L:J5KD:H74J:UDBI:5XQ6:HNCO:SSI4:LPGO:GDAJ:IIWR:3PN2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by segfault** [comment]
Hi, I have been using a distributed switch since 2.0 without issue until recently when assigning any network failed. In general it's worked well.
