### ISSUE TITLE
Namespace group changed to Pod after adding new service/ingress 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16591]
rancher/rancher:v2.1.0

Steps to reproduce:

1. Go to service discovery tab
2. Click Add Record and create one record.

Result:

Namespace group changed to Pod

![image](https://user-images.githubusercontent.com/21168270/48484365-e57cf700-e850-11e8-87a0-d42e97cfb3b7.png)

Expected:

It should show `Namespace: XXXX` instead of `Pod`

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/14
Verified fixed
