### ISSUE TITLE
When shibboleth auth enabled rancher-server is accessed from a fqdn that is not in whitelist, user is redirected to the register url with error page presented to the user.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16603]
Rancher server version - v1.6.24-rc4

Steps to reproduce the problem:
Have 3 fqdn entries - fqdn1, fqdn2 and fqdn3 point to same Rancher server instance.
Access rancher server using fqdn1 , set "host registration url" as fqdn1 and enabled Shibboleth provider.
Attempt to log in to rancher server using fqdn2 as a user who has access to rancher server (site access).

User is presented with "Unprocessed Entity" but it redirected to "host registration url" fqdn1 page.

Expected Behavior:
User should still be in fqdn2 url when "Unprocessed Entity" is presented to the user.

**Comment by mrajashree** [comment]
Discussed with @prachidamle and @sangeethah offline. This should be the expected behavior.
Because if the user does not have access to host registration URL, it just won't resolve.
However, if we redirect to the param redirectBackBase, then we are doing open redirection.

**Comment by sangeethah** [comment]
Closing this issue after discussing this  issue and getting confirmation from @cjellick .
