### ISSUE TITLE
Projects not loading

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#16612]
Rancher master
Attempting to load a clusters projects just spins and never loads

**Comment by westlywright** [comment]
Repro:
* Launch HA Install (or at the very least launch rancher with `--add-local=true`
* Navigate to the cluster level view of the local cluster
* Select the `Projects/Namespaces` tab

Expected:
* View loads

Actual:
* View stuck on spinner view

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/12/18)
Confirmed fixed. I set up a simple HA set up using ec2, amazon NLB, etc per our rancher docs. Once this was up and running (used alpha3 charts and master imageTag) I tried to repro and could not. I tried refreshing leaving the projects/namespaces page coming back. Creating a workload and more namespaces (try to break things, etc) and did not encounter any issues with my rancher deployment.
