### ISSUE TITLE
WebSocket failed to connect after Rancher upgrade

### ISSUE THREAD

**Issue by ebuildy** [rancher/rancher#1661]
I upgraded Rancher to:

Rancher	v0.28.0
Cattle	v0.64.0
User Interface	v0.34.0
Rancher Compose	beta/latest

Now on the UI I got a WebSocket 404 error for /stats endpoint:

![Rancher error]
(https://beemapp.s3-eu-west-1.amazonaws.com/70b3baf1-e12f-4e0d-9fda-f87238c8d33e.jpg)

Same thing on agents:

````
time="2015-07-27T13:08:17Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"9618a22b09ed75ec0c9c176f2e26c5ec993ea37e73ed0082baec2aed3b3af0b6\", From:\"-simulated-\", Time:0}"
time="2015-07-27T13:08:17Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"4270ad7d7b2c49c3a19392d7650be3139872fb415abbbf812c58dc21c311b941\", From:\"-simulated-\", Time:0}"
time="2015-07-27T13:08:17Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"82d3092550f6136ba78add602618173f4ad1dfca9cfea792b51a74f7a317a702\", From:\"-simulated-\", Time:0}"
time="2015-07-27T13:08:17Z" level="info" msg="Assigning IP [10.42.206.62/16], ContainerId [26a527fcc0421beb01234fd000d47e16af5b44973e5f2c88dc2b3889f5425af2], Pid [26603]"
time="2015-07-27T13:08:17Z" level="info" msg="Assigning IP [10.42.118.230/16], ContainerId [9618a22b09ed75ec0c9c176f2e26c5ec993ea37e73ed0082baec2aed3b3af0b6], Pid [21504]"
time="2015-07-27T13:08:17Z" level="info" msg="Assigning IP [10.42.220.206/16], ContainerId [82d3092550f6136ba78add602618173f4ad1dfca9cfea792b51a74f7a317a702], Pid [1463]"
time="2015-07-27T13:08:17Z" level="info" msg="Connecting to proxy." url="ws://******:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0MzgwMDI3OTcsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjUxM2E2OGY0LTRmOTUtNDZlYS1iMjU4LTFiMWQwMjY4YzFiNSIsImlhdCI6MTQzODAwMjQ5Nywia2lkIjoiZGVmYXVsdCJ9.TLWbaBcOejlTfX5bf8Bbdetg9HGf3-EFMXgGlItGLpAugu84J324V6gM9f_15PwOY5y29kr-i3sAhnzLCfzASOdpshvRcv1R9WW-RpSCSAmN75mwgbl5_pdD99Fo04XlZAqSnyJUeZ9kTQNEm_9FymqGInfd8o_hkEMlHZ_YAH0qKWWO5jfozO2Xd3PXG1kZZNp555svs7nPuCjADn8nAiTAoxmUpFxDlupPoTj77Jx2XjQh-nYageMDBOoz3pTgqnbDwEk_uvLykZWhngGlNKmOaemFDihLWKiIRKX4caX0EC7dC8R4IO0bouJKt8CfJP-VhkXEowqQieCJvi3hLQ"
time="2015-07-27T13:08:17Z" level="fatal" msg="Failed to connect to proxy." error="websocket: bad handshake"
````

It complains every seconds ;-( 

Is it normal?

**Comment by ebuildy** [comment]
I have removed the database, and re-install Rancher, now it's fine.

Any idea of what happened?

**Comment by cjellick** [comment]
Hi @ebuildy not sure what happened there, but depending on what version you upgraded from, there were some pretty major changes in how we were connecting to hosts for stats.

Do you know what version of rancher you were on prior to the upgrade? 

Also, was the domain/ip that you blurred out the same as the domain/ip you use in your browser to connect to Rancher? Was it also the same host you configured in the "Host Registration" dailog?

Finally, do you have any additional proxies in the mix? For example, an nginx proxy or ELB for ssl termination?

**Comment by ebuildy** [comment]
Hello,

No proxy, 8080 is Rancher directly. 

Now it's fine:

![]
(https://beemapp.s3-eu-west-1.amazonaws.com/a932b1c4-323c-4732-9672-7dc17acc8590.jpg)

Looks like the root **/v1/stats** was lost ;-) this was the strange thing because socket on /subscribe worked but not /stats.

**Comment by cjellick** [comment]
@ebuildy sorry for delayed response. We introduced a new microservice called the websocket-proxy that hosts connect on /v1/connectbackend and the UI connects on /v1/stats (and /v1/logs and /v1/exec).

When you upgraded to a version of rancehr that had the websocket-proxy, something must have went sideways with the websocket-proxy.

**Comment by deniseschannon** [comment]
@ebuildy Are you still having issues with your websocket proxy? Otherwise, I'd like to close this issue as it looks like an old upgrade issue for when we introduced websocket-proxy.

**Comment by ebuildy** [comment]
No more issue with 0.35

Thanks you
