### ISSUE TITLE
Rancher 2.x UI  edit or move namespace

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#16617]
Rancher version 2.1.1
There are two options in edit namespace.
- Edit 
- Move

![image](https://user-images.githubusercontent.com/15118220/48602616-d8364880-e9c7-11e8-8b54-559e32746977.png)

Using Move could move namespace from one project to other
Using Edit, select Default or System then save
![image](https://user-images.githubusercontent.com/15118220/48602705-26e3e280-e9c8-11e8-9f81-a0e74ea896b9.png)

It looks like move namespace to project Default
![image](https://user-images.githubusercontent.com/15118220/48602746-4aa72880-e9c8-11e8-91f1-9a3e50569750.png)

But refresh browser namespace still no belongs to a project
![image](https://user-images.githubusercontent.com/15118220/48602775-66aaca00-e9c8-11e8-8c38-c020155389f1.png)

In Edit function, nothing you could change besides project. Why there is Edit function for namespace ?

**Comment by vincent99** [comment]
> In Edit function, nothing you could change besides project.

The description is editable., edit is confusing if it doesn't include the NS and Move exists because edit cannot be a bulk action.

**Comment by loganhz** [comment]
UI sends the correct project Id to backend. But it looks like backend just ignored it.
I guess we should not allow user to update the project field in edit namespace modal.

**Comment by vincent99** [comment]
@loganhz how is changing the project here different to the server than the move UI action?

**Comment by vincent99** [comment]
oh yeah, that's new-ish.  Yes 2 API requests if the projectId has changed.

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/3/19)
Confirmed fix. I can use edit to both move a namespace and update it's description at the same time. When this happens we send a PUT to update the description and a POST to move the namespace. Once moved it now successfully moves even upon refresh. I also tested Move functionality without any issues. I could not reproduce the issue and HTTP/API looks good.
