### ISSUE TITLE
When is logging to Kafka going to support sasl/scram-256?

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#16614]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`global-admin.clusters.index`|

**Comment by cjellick** [comment]
@aiwantaozi @loganhz Does this require a UI change? I imagine it does. If so, a UI issue should be opened with the `area/ui` label attached. You should open the UI issue as soon as you know the change will require UI changes

**Comment by cjellick** [comment]
backend is in, but no UI yet.

**Comment by cjellick** [comment]
@aiwantaozi please provide a summary of the fields added to the api and how they can be tested

**Comment by aiwantaozi** [comment]
On the API side, we add four fields to support SASL auth for ship log to Kafka. 
```
saslType: sasl auth we support two sasl auth type plain and scram, config one of them.
saslUsername: both plain and scram type have this field
saslPassword: both plain and scram type have this field
saslScramMechanism: this field is for scram type, it could be sha256 or sha512
```

Step to test the sasl support:
1. Config sasl plain/scram for kafka
2. Config sasl related field in logging API
Plain example:
```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"clusterId":"local", "customTargetConfig":null, "elasticsearchConfig":null, "excludeSystemComponent":false, "fluentForwarderConfig":null, "kafkaConfig":{"brokerEndpoints":["http://michelia.rancher-test.com:9093"], "certificate":"xxxx", "clientCert":"yyyy", "clientKey":"zzzz", "saslType":"plain", "saslUsername":"alice", "saslPassword":"alice-screct", "topic":"test1", "type":"/v3/schemas/kafkaConfig"}, "namespaceId":"", "outputFlushInterval":60, "splunkConfig":null, "syslogConfig":null}' \
'https://localhost:8443/v3/clusterloggings'
```

Scram example:
```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"clusterId":"local", "customTargetConfig":null, "elasticsearchConfig":null, "excludeSystemComponent":false, "fluentForwarderConfig":null, "kafkaConfig":{"brokerEndpoints":["http://michelia.rancher-test.com:9093"], "certificate":"xxxx", "clientCert":"yyyy", "clientKey":"zzzz", "saslType":"scram", "saslUsername":"alice", "saslPassword":"alice-screct", "saslScramMechanism":"sha256", "topic":"test1", "type":"/v3/schemas/kafkaConfig"}, "namespaceId":"", "outputFlushInterval":60, "splunkConfig":null, "syslogConfig":null}' \
'https://localhost:8443/v3/clusterloggings'

``` 

3. Check secret under system project secret name ```rancher-logging-fluentd```, key ```cluster.conf``` or ```project.conf``` whether include kafka sasl related config

Plain Type:
```
    @type kafka_buffered
    brokers michelia.rancher-test.com:9093
  
    ssl_ca_cert /path
    ssl_client_cert /path
    ssl_client_cert_key /path 
    max_send_retries  3        
    username alice
    password alice-secret
```

Scram Type:
```
    @type kafka_buffered
    brokers michelia.rancher-test.com:9093
  
    ssl_ca_cert /path
    ssl_client_cert /path
    ssl_client_cert_key /path 
    max_send_retries  3        
    username alice
    password alice-secret
    scram_mechanism sha256
```

4. Check kafka whether we could get log from cosumer

**Comment by kingsd041** [comment]
Version: master 2.2 (2/18/19)  Image ID: 46f4b03ba30e
Confirmed fix.  Follow the test case test below, all tests passed

#### Test cases:
**Cluster level Logging**
1. Test sasl/scram-256 authentication
2. Test sasl/scram-512 authentication
3. Test Plain authentication
4. Test SSL Configuration
5. Multiple Endpoint
6. Test using advanced mode to customize `match` and SSL Configuration

**Project level Logging**
1. Test sasl/scram-256 authentication
2. Test sasl/scram-512 authentication
3. Test Plain authentication
4. Test SSL Configuration
5. Multiple Endpoint
6. Test using advanced mode to customize `match` and SSL Configuration
