### ISSUE TITLE
Better control for selecting global/cluster/project

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#16613]
The current cluster/project dropdown is hard to use if you have many clusters and/or projects.  It should be organized into 2 tiers (cluster, then project) and have search.

Old & busted:

![image](https://user-images.githubusercontent.com/753917/48586607-a3ee5980-e8ed-11e8-8bf6-d34358eeddd4.png)

New hotness:

![image](https://user-images.githubusercontent.com/753917/48587875-119c8480-e8f2-11e8-8583-1e1ac4ba25ff.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (11/27/18)
Validated new feature. Carefully tested all functionality (proper navigation, search functionality, fuzzing data, etc) issues found were entered under the referenced issue, #16735
