### ISSUE TITLE
jenkins slave pod bug

### ISSUE THREAD

**Issue by vvkkhjt** [rancher/rancher#16621]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
use jenkins start slave pod then click into 

**Result:**
![tim 20181116175329](https://user-images.githubusercontent.com/12765476/48614164-922db480-e9c8-11e8-8863-15c9b7abf56d.png)
ui crash
![1](https://user-images.githubusercontent.com/12765476/48614245-c6a17080-e9c8-11e8-8700-95b75323dc34.png)
i cant click anything,unless i refresh web.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.0.8
- Installation option (single install/HA): single install

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/issues/15199
Please try it in v2.1.1
