### ISSUE TITLE
Cloning an "edited" load balancer shows original load balancer routing and not modified routing.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1662]
v0.30.0-rc2 

Steps To Reproduce:
1. Create service 
2. Create load balancer with advanced routing options. Add in a rule with some request host/path.
3. Edit the load balancer. Remove the path and add in new target port. Click Save.
4. Clone the LB 

Result: 
In the UI, the creation screen shows the original routing rules and not the modified routing rules. 

Expected Result
In the UI, the clone screen would show the modified routing rules.

**Comment by deniseschannon** [comment]
Tried with UI v0.59.0, it's not fixed. Having the same issue.

**Comment by vincent99** [comment]
How about now..

**Comment by deniseschannon** [comment]
Verified with latest UI (evening 11/24)
