### ISSUE TITLE
Missing cni configuration

### ISSUE THREAD

**Issue by MaxDiOrio** [rancher/rancher#16628]
Rancher 2.1.1, RancherOS v1.4.2, K8s 1.11.3-rancher1-1 running vSphere provider

Ever since Rancher 2.1.1 upgrade, it's been an absolute nightmare.  I've lost clusters randomly and now I can't seem to get any to deploy fully/properly or without a ton of container/vm restarts

Turning up a new cluster, I'm seeing:

[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.85.164.220]: Get https://localhost:10250/healthz: can not build dialer to c-r2vdg:m-j92fv, log: E1116 19:26:39.626801 3843 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

If I go to the containers, there is no configuration in /etc/cni, and in at least one instance, there is no /etc/cni folder at all.

Before this, the cluster random went unavailable "waiting for api" after it was up and stable for a week.

I've had a cluster that had a node go bad, deleted it, it recreated it, but Rancher still retained info about the old node and complained about it relentlessly.

I've had several clusters I brought up have one or two nodes use a self-assigned eth0 IPv6 address for internal/external IP instead of the IPv4 address.

Somehow it doesn't seem anyone else has these problems but me. Not sure why.

**Comment by deniseschannon** [comment]
@MaxDiOrio Can you see if you still have these issues in v2.2.2?

**Comment by superseb** [comment]
Let us know if this needs further investigation
