### ISSUE TITLE
Air gap rancher helm install: agents don't use private registry

### ISSUE THREAD

**Issue by yvespp** [rancher/rancher#16630]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
* Air gapped installation with a private registry
* Deploy 3 Node Kubernetes cluster via rke
* Deploy stable helm chart rancher-2018.10.2
* Login to rancher ui and set password

**Result:**
cattle-cluster-agent and cattle-node-agent get deployed but get an `ImagePullBackOff` trying to pull rancher/rancher-agent:v2.1.1, which is not reachable as it is an air gap install.

**Other details that may be helpful:**
* I tryed to change the system-default-registry in the ui of rancher but it did not update the already deployed agents.
* https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-installation/config-rancher-for-private-reg/ notes that you can set the env var `CATTLE_SYSTEM_DEFAULT_REGISTRY` but there is no way to set it via the helm chart.
* The rancher node gui (https://my-rancher/c/local/nodes) shows all nodes as green...

**Environment information**
- Rancher version: v2.1.1, helm chart rancher-2018.10.2
- Installation option (single install/HA): HA via helm chart

Please add an option to the helm chart to set the `CATTLE_SYSTEM_DEFAULT_REGISTRY` env var.
Or is there another way to set the registry before rancher deployes the agent on the local cluster?

**Comment by xiaoluhong** [comment]
Please check the `rancher-cluster.yml` configuration, is there a `private_registries` parameters?

https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-installation/install-rancher/#rke
https://www.cnrancher.com/docs/rke/v0.1.x/en/config-options/private-registries/#default-registry

**Comment by yvespp** [comment]
@xiaoluhong yes, there is and I also set that parameter but that is for rke and in the rancher gui this url is not set after installing rancher via helm chart.
I found a script this script and I'm now using it to set the registry url: https://gist.github.com/superseb/c363247c879e96c982495daea1125276
As far as I'm concerned you can close this issue as I have a way to do it now.
