### ISSUE TITLE
Cannot delete certificates after update certs and key from API

### ISSUE THREAD

**Issue by heamaral** [rancher/rancher#16637]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a new certificate on project, try to update it changing certs and key fields, it does not reflects changes to ingress and it is not possible to delete this certificate anymore

**Environment information**
Rancher v2.1.1

**Cluster information**
Hosted
Kubernetes version: v1.11.1

**Comment by loganhz** [comment]
Is there any error message when you delete the certificate? You might find some error logs in browser network tab or console log.

**Comment by heamaral** [comment]
No, the status code is 200:
```
Request URL: https://rancher.ciatech.com.br/v3/project/c-8rj42:p-gzszp/certificates/p-gzszp:gen-ciatechtk-cert
Request Method: DELETE
Status Code: 200 OK
```
But certificate is not deleted.
There is no log on rancher server container that is related to certificate.

**Comment by heamaral** [comment]
Have tried to delete secret related to the certificate but I still cannot delete the certificate.

**Comment by heamaral** [comment]
I have sent "links" on the request, this seems to be the problem.
When it was sent, I can't update or delete it. Maybe links/actions should be ignored when received in request payload?

**Comment by tfiduccia** [comment]
Version - v2.2.4
I am unable to reproduce.

**Comment by ajacques** [comment]
Running v2.2.4, I can still reproduce.

```
https://[hostname]/v3/project/c-5spdj:project-cqcq5/certificates/project-cqcq5:mycert
Request Method: DELETE
Response Status: 200
```

But the certificate is still there. This only seems to happen for certificates that exist on all namespaces (`namespaceId: null`)
