### ISSUE TITLE
nfs file locking fails 

### ISSUE THREAD

**Issue by alex-s-team** [rancher/rancher#16644]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
use nfs as storage for a container that locks files (i.e. rspamd)

**Result:**
lock on file failed: Bad file descriptor

**Other details that may be helpful:**
nfs server:
nfs-kernel-server on Ubuntu 18.04.1 LTS

exports:
/srv/docker                x.x.x.x/24(rw,no_root_squash,sync,no_subtree_check,insecure)

mailserver-data on /var/mail type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=x.x.x.x,local_lock=none,addr=x.x.x.x)

the option local_lock=none is set

can this option be overridden? (how?)
why is this option being set?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher/rancher:v2.1.1
single install
rancheros v1.4.2
docker 18.03.1-ce

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
vm
Xeon(R) CPU E5-1650
8gb memory
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.73-rancher
Operating System: RancherOS v1.4.2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.793GiB
Name: rancher010002002030
ID: SS42:CEWO:5KHT:IFDV:PBA2:VBMN:KXLC:AS5M:MJD5:MJHS:HCUV:M2D7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 10.2.2.20:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by loganhz** [comment]
Please try to use https://kubernetes.io/docs/concepts/storage/storage-classes/#mount-options
