### ISSUE TITLE
local storage provisioner is not creating local-volume in k8s

### ISSUE THREAD

**Issue by AmreeshTyagi** [rancher/rancher#16642]
I am running Rancher 2.1.1 (Kubernetes v1.11.3)

I am trying to use local storage volume provision plugin provided on [kubernetes incubator](https://github.com/kubernetes-incubator/external-storage/tree/local-volume-provisioner-v2.1.0/local-volume) (in beta) to provision local storage automatically. 

I have successfully installed it via helm (and via following yaml files too without helm). DeamonSet & pods are running fine. But it is not creating local PVs automatically. Logged same issue on incubator [#713](https://github.com/kubernetes-incubator/external-storage/issues/713).

As per provisioner:v2.1.0 pod logs: 
`I1116 11:46:37.235094 1 common.go:259] StorageClass "local-scsi" configured with MountDir "/mnt/disks", HostDir "/mnt/disks", BlockCleanerCommand ["/scripts/quick_reset.sh"]`
`I1116 11:46:37.235681 1 main.go:42] Configuration parsing has been completed, ready to run...`
`I1116 11:46:37.236266 1 common.go:315] Creating client using in-cluster config`
`I1116 11:46:37.266784 1 main.go:52] Starting controller`
`I1116 11:46:37.266895 1 controller.go:42] Initializing volume cache`
`I1116 11:46:37.271524 1 populator.go:85] Starting Informer controller`
`I1116 11:46:37.271573 1 populator.go:89] Waiting for Informer initial sync`
`I1116 11:46:38.272051 1 controller.go:72] Controller started`

I have also enabled `"feature-gates": "PersistentLocalVolumes=true, VolumeScheduling=true, MountPropagation=true"`

Reference yaml files to create provisioner with rbac.
**local-storage-provisioner.yaml**
`apiVersion: v1`
`kind: ConfigMap`
`metadata:`
`  name: local-provisioner-config`
`  namespace: mysql`
`data:`
`  storageClassMap: |`
`    local-scsi:`
`       hostDir: /mnt/disks`
`       mountDir:  /mnt/disks`
`---`
`apiVersion: extensions/v1beta1`
`kind: DaemonSet`
`metadata:`
`  name: local-volume-provisioner`
`  namespace: mysql`
`  labels:`
`    app: local-volume-provisioner`
`spec:`
`  selector:`
`    matchLabels:`
`      app: local-volume-provisioner`
`  template:`
`    metadata:`
`      labels:`
`        app: local-volume-provisioner`
`    spec:`
`      containers:`
`        - image: "quay.io/external_storage/local-volume-provisioner:v2.1.0"`
`          imagePullPolicy: "Always"`
`          name: provisioner`
`          securityContext: mysql-sa`
`            privileged: true`
`          env:`
`          - name: MY_NODE_NAME`
`            valueFrom:`
`              fieldRef:`
`                fieldPath: spec.nodeName`
`          volumeMounts:`
`            - mountPath: /etc/provisioner/config`
`              name: provisioner-config`
`              readOnly: true`
`            - mountPath:  /mnt/disks`
`              name: local-scsi`
`      volumes:`
`        - name: provisioner-config`
`          configMap:`
`            name: local-provisioner-config`
`        - name: local-scsi`
`          hostPath:`
`            path: /mnt/disks`

**local-storage-rbac.yaml**
`---`
`apiVersion: v1`
`kind: ServiceAccount`
`metadata:`
`  name: mysql-sa`
`  namespace: mysql`
`---`
`apiVersion: rbac.authorization.k8s.io/v1beta1`
`kind: ClusterRole`
`metadata:`
`  name: mysql-cr`
`rules:`
`  - apiGroups: [""]`
`    resources: ["persistentvolumes"]`
`    verbs: ["get", "list", "watch", "create", "delete"]`
`  - apiGroups: [""]` 
`    resources: ["persistentvolumeclaims"]`
`    verbs: ["get", "list", "watch", "update"]`
`  - apiGroups: ["storage.k8s.io"]`
`    resources: ["storageclasses"]`
`    verbs: ["get", "list", "watch"]`
`  - apiGroups: [""]`
`    resources: ["events"]`
`    verbs: ["create", "update", "patch"]`
`  - apiGroups: [""]`
`    resources: ["services"]`
`    verbs: ["get","watch","list"]`
`  - apiGroups: [""]`
`    resources: ["pods"]`
`    verbs: ["get","watch","list"]`
`  - apiGroups: ["extensions"]`
`    resources: ["ingresses"]`
`    verbs: ["get","watch","list"]`
`  - apiGroups: [""]`
`    resources: ["nodes"]`
`    verbs: ["get","watch","list"]`
`---`
`apiVersion: rbac.authorization.k8s.io/v1beta1`
`kind: ClusterRoleBinding`
`metadata:`
`  name: mysql-crb`
`roleRef:`
`  apiGroup: rbac.authorization.k8s.io`
`  kind: ClusterRole`
`  name: mysql-cr`
`subjects:`
`  - kind: ServiceAccount`
`    name: mysql-sa`
`    namespace: mysql`

**Comment by fabiorauber** [comment]
It took me long to understand that the volumes need to be manually created:
https://github.com/kubernetes-incubator/external-storage/issues/713#issuecomment-440465504

Tried to use https://github.com/rancher/local-path-provisioner, but could not find way to make it work, probably because of the Kubernetes version I'm using (1.11): https://github.com/rancher/local-path-provisioner/issues/3
