### ISSUE TITLE
helm  lifecycle not supported by catalog

### ISSUE THREAD

**Issue by manlme** [rancher/rancher#16641]
**What kind of request is this (question/bug/enhancement/feature request):**

BUG

**Steps to reproduce (least amount of steps as possible):**

helm provides the lifecycle hook using annotations. I wrote a chart containing a job to initiate the DB.

the job is with annotations  "helm.sh/hook": "pre-install". it works in helm but it doesn't work in rancher

catalog. 

**Result:**

**Other details that may be helpful:**

**Environment information**
- RANCHER 2.0.8
- Installation option HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):

RKE

- Machine type (cloud/VM/metal) and specifications (CPU/memory):

vm

- Kubernetes version (use `kubectl version`): 1.11

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Thanks for your report.
Please use v2.1.1
This issue has been fixed in 2.1.1
