### ISSUE TITLE
Cluster save fails after editing with advanced options open

### ISSUE THREAD

**Issue by maxkorp** [rancher/rancher#16647]
Kind: Bug
Repro:
 - Create cluster (in my case in DO)
 - Edit cluster such that advanced options is open (e.g. increase port range) 
 - Try to edit cluster again with advanced options open
 - It fails

NoRepro:
 - Create cluster (in my case in DO)
 - Edit cluster such that advanced options is open (e.g. increase port range), but delete empty catalog
 - Try to edit cluster again with advanced options open, again deleting catalog
 - It works

Soon as you save with advanced options open but without deleting the empty catalog it adds, you can no longer edit the cluster

Rancher Version: 2.1.x (haven't tested master)
Install: running code locally

**Comment by davidnuzik** [comment]
Version: Master (11/21/18)
Confirmed fix, the row of empty fields under "Private Registries" no longer appears upon editing the cluster (with "Show advanced options"). Can save, and edit again without issues.
