### ISSUE TITLE
Backport AKS cluster goes to "Unavailable" state intermittently

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16654]
Backport https://github.com/rancher/rancher/issues/14354

**Comment by soumyalj** [comment]
This issue reproduced in rancher v2.1.2-rc13 too.

<img width="1247" alt="screen shot 2018-11-20 at 4 29 38 pm" src="https://user-images.githubusercontent.com/18536626/48862165-55700d80-ed7a-11e8-835a-1811677dabe8.png">

**Comment by alena1108** [comment]
This fix for this issue will be moved out off 2.1.2 scope, and addressed in master (2.2). cc @cjellick 
Closing the bug.
