### ISSUE TITLE
Backport Etcd snapshot container is not deployed after upgrade 

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16653]
Backport https://github.com/rancher/rancher/issues/16556

**Comment by soumyalj** [comment]
a. Tested with upgrade from v2.1.1 to v2.1.1-rc13.
After upgrade, the etcd snapshot was still disabled as expected
<img width="1218" alt="screen shot 2018-11-21 at 11 56 17 am" src="https://user-images.githubusercontent.com/18536626/48865788-78ec8580-ed85-11e8-88f3-80590445bef2.png">
b. Edited another parameter(PSP) and after the update succeeded, the etcd snapshot field was still disabled as expected. This is to verify that changing other parameters does not change the etcd-snapshot field
c. Enabled etcd snapshots and set the creation/retention time as 5m/1h. 
etcd-rolling-snapshots was running 
Snapshots were created every 5m as expected
