### ISSUE TITLE
Rolling Upgrade - Batch size not honored when deleting the the first set of containers from source service after the first batch of containers are created for the target.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1665]
rancher-server version - v0.30.0-rc3
rancher-compose version v0.2.4

Used the following command to upgrade from test5 - test8 in batches of 3:
./rancher-compose -p testupgrade upgrade test5 test8 --interval 30000 --batch-size 3 --scale 8

When the first 3 instances of test8 have started , only 1 instance of test5 gets removed.
Expected Behavaior:
We should delete 3 instances of test5.

**Comment by ibuildthecloud** [comment]
@sangeethah What scale did you start with for test5 and test8

**Comment by sangeethah** [comment]
test8 did not exist.
test5 had a scale of 3.

**Comment by ibuildthecloud** [comment]
This is the behaviour you should see:

3,0
3,3
3,6
2,6
2,8
0,8

**Comment by sangeethah** [comment]
Closing this issue since batch size is not meant to be used  when deleting instances from the source service. Deletion of instances in the source service starts happening only when the total scale of both the source and target services has gone beyond the final scale and  deletion is done to maintain the final scale.
