### ISSUE TITLE
OpenStack node driver is hard to use. Problems collected.

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/rancher#16656]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug and enhancement.

**Steps to reproduce (least amount of steps as possible):**
Using openstack node driver with node templates on k8s cluster creating.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher/rancher:v2.1.1  single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): OpenStack
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): default(1.11)
- Docker (use `docker info`): docker-ce 17.03.2

**From now on is the problems**
PART1. Openstack node template
1. Some params input only need one value but there is no explanation on ui.
e.g.
![image](https://user-images.githubusercontent.com/23303886/48744684-2e92d800-eca3-11e8-8525-9361e4c8343a.png)
Such as flavorId and flavorName. Only one of the items can be filled in. The exception info which can be found in rancher-server's docker logs will tell you not to do this if you do it both.

suggestion: 
Updated like this: with only 1 input element like 'flavorId/flavorName'

2. All the params in the node template need a kind of order or group. A bit messy for now.

3. Need more guidance on params input.
e.g.
![image](https://user-images.githubusercontent.com/23303886/48744949-68b0a980-eca4-11e8-8ab2-516274c12cfe.png)
How to fill in with this input? A path? Or a filename? 
On openstack you can either upload a file or just fill in the form:
![image](https://user-images.githubusercontent.com/23303886/48745481-94349380-eca6-11e8-91f2-344409d6acb3.png)

I didn't find the full document on these area(openstack node templates). Please let me know if i missed. Thx.

4. Password area value missing after the form saved. And when u typing the value into this input, the value is not hidding like the usual password type.
![image](https://user-images.githubusercontent.com/23303886/48745129-28056000-eca5-11e8-8aef-764e4db5cac6.png)

![image](https://user-images.githubusercontent.com/23303886/48745098-060bdd80-eca5-11e8-9814-f45f8baf1a48.png)

PART2. Node controller(internal)
1. Using keypair created by openstack will meet exception: 
```
Error getting config for native Go SSH: asn1: structure error: superfluous leading zeros in length
```
And using the rancher created keypair is ok.

2. Using generic cloud (made by official)  is ok. But using the image which is made by generic cloud + cloud-init failed with following exception:
```
NodeController c-fps8s/m-t5vts [node-controller] failed with : Error creating machine: Error running provisioning: Failed to obtain lock: Maximum number of retries (60) exceeded
```

PART3. Extra
1. Really need cloud-init support.

**Comment by loganhz** [comment]
Hi @BalaBalaYi 

We can fix part one.

For part two, Rancher is using docker-machine to provision VM now. 
Rancher will pass the parameters to docker-machine. 
Could you try to create openstack with your keypair and customized image via docker-machine cli directly, please?  

For part three, it looks like openstack docker-machine doesn't support cloud-init yet.

**Comment by loganhz** [comment]
Keypair and userdata script won't work in Rancher. 
It reads the path inside the rancher/rancher container. But it doesn't make sense if you put the private key and script inside rancher server container

https://github.com/rancher/rancher/issues/14330

**Comment by BalaBalaYi** [comment]
@loganhz Thx for your suggestions.

**Comment by loganhz** [comment]
Sorry, we will not update openstack UI for now. 

We kind fo specifically didn't port the old openstack UI because it's confusing and not very goodl. userdata and key options don't make sense, they're going to end up looking for files in the server container.

Please submit new issues for part 2 and part 3.
