### ISSUE TITLE
Backport fix for after re-importing local cluster with addLocal=auto, Default and System projects are not associated with the correct namespaces

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16652]
Backport for https://github.com/rancher/rancher/issues/16602

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.2-rc14
HA setup w/ Helm install

Validated successfully. 

* Deployed 2.1.2-rc14 w/ `addLocal=auto`
* Created a workload / ingress in local cluster default namespace
* Upgraded to same version w/ `addLocal=false`
* Validated workload running and ingress functional after local cluster is removed from UI (and node/cluster agents are not running)
* Upgraded to same version w/ `addLocal=auto`
* Local cluster returned in UI w/ cluster & node agents running. Previously deployed workload is visible in the correct project / namespace; ingress still functional; System projects & workloads contain all expected items.
