### ISSUE TITLE
[Pipeline] Directions for Github Enterprise direct to incorrect place to create application

### ISSUE THREAD

**Issue by shubb30** [rancher/rancher#16667]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
I am using an on-prem Github Enterprise server, but I get the same thing if I follow the same directions on my GitHub account.

Follow the steps at https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/configurations/
On the page to add a new Github repo, the directions say:

```
For standard GitHub, click here to go applications settings in a new window.
 -   For Github Enterprise, login to your account. Click on Settings, then Applications.
```

When I go to my Github account > Settings > Applications, there is no option for `Register new application`.
If you go to the `click here` link for standard GitHub, the URL is `https://github.com/settings/developers`, but the link I get to following the directions is `https://github.example.com/settings/installations`.  Right under the `Applications` link, is a `Developer settings` link that takes you to the page `https://github.example.com/settings/developers` where there is a link to Register a new application.

The directions should say 
```
For Github Enterprise, login to your account. Click on Settings, then Developer settings.
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): 2.1.0

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.11.3

**Comment by tfiduccia** [comment]
Version - 2.2 master 11/4
Verified fixed
