### ISSUE TITLE
'Refresh' button did not change waring icon when respond is 200

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#16662]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Go to the project catalog.
2. Click 'Refresh' button
3. Click 'Refresh' button again

**Result:**

Both respond is 200,  but UI shows warning icon. 

![image](https://user-images.githubusercontent.com/18737885/48761672-2f982980-ece4-11e8-9d62-6c25d160b67a.png)

**Other details that may be helpful:**

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/18)
Confirmed fixed. I can no longer reproduce the issue where the warning icons shows up on the refresh button. I tested again and validated HTTP and everything appears to be operating correctly. All the appropriate requests to the server happen and succeed:
![image](https://user-images.githubusercontent.com/45179589/50308992-4d2eef00-045a-11e9-8fc8-e06083fabc4e.png)
