### ISSUE TITLE
Rancher up command do not work

### ISSUE THREAD

**Issue by dotyso** [rancher/rancher#16663]
I run the command as:

**rancher up -s my-stack-name -p -u -d**

or other “rancher up” command do not work, i want to upgrade service by this command

but other cmd is valid, such as “rancher stop”, “rancher logs”, etc…

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.23` Cattle: `v0.183.64` UI: `v1.6.47` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
