### ISSUE TITLE
Global catalog "Refresh" action have no effect

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#16661]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Add a global catalog.
2. Click "Refresh" action.

**Result:**
The UI has not sent a request to the backend.

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/18)
Confirmed fixed. When I perform the refresh action in the UI I see we make a POST request to https://<rancherServer>/v3/catalogs/<catalogName>?action=refresh with the action: refresh query string parameters in our request to the server. I can also see this happen in the UI as the State very briefly changes while this occurs. I also halo tested (refresh whole page and validate HTTP, check other catalog pages (project level, etc)).
