### ISSUE TITLE
Add LimitRange config to Project and Namespace quota settings

### ISSUE THREAD

**Issue by garyellis** [rancher/rancher#16677]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Other details that may be helpful:**

**Add limitrange configuration to project configuration similar to resource quotas.**
**Add limitrange configuration to namespace configuration similar to resource quotas.**

After a user sets resource quotas at project or namespace scope, his/her next step will create a limitrange so the Rancher UI can continue to deploy charts in those projects/namespaces. Limitrange configuration should be added to project and namespace settings to simplify resource quotas configuration management.

Related 2.2 backlog item: #15648

**Comment by alena1108** [comment]
@loganhz yes, it is

**Comment by alena1108** [comment]
Duplicate of https://github.com/rancher/rancher/issues/15648
