### ISSUE TITLE
Validation failed in API: target namespace kube-system is not assigned to the current project

### ISSUE THREAD

**Issue by dukelyuu** [rancher/rancher#16671]
**question:**

**Steps to reproduce (least amount of steps as possible):**
   go to the app catelog, and search the kubernete-dashboard in library.
   start the app

**Result:**
Validation failed in API: target namespace kube-system is not assigned to the current project

**Other details that may be helpful:**

**Environment information**
- Rancher 2.0.5:
- single install:

![image](https://user-images.githubusercontent.com/5789960/48828324-68023b00-edaa-11e8-9d52-7bbeb44a7870.png)

**Comment by superseb** [comment]
There is a note at the bottom saying it should be installed in the `System` project, did you select that before installing the app? It can only be installed using the kube-system namespace currently.
