### ISSUE TITLE
Show AD username in Users page

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#16679]
Rancher: v2.1.1
Setup with AD authentication.

Navigate to Cluster:myclustername > Members, I can see the User's Full name with the username in round parenthesis. This is very helpful.

When I navigate to Global > Users, "Local Username" is empty for the AD users and their username info is not available. Adding the AD username in this page is quite helpful for figuring out login issues.

**Comment by davidnuzik** [comment]
@loganhz could you put a space after the full name and before the username? See this screenshot there is no space before the (
![image](https://user-images.githubusercontent.com/45179589/50846758-29f6b180-132d-11e9-991b-6c2eef752583.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/9/19)
Confirmed enhancement. Full names are now shown with local / AD / etc under global users. I tested with both local and AD. Further testing will be occurring in this area as well as we continue to test around Authentication providers.
Screenshot example:
![image](https://user-images.githubusercontent.com/45179589/50918636-03ed1200-13fe-11e9-96d8-67b8f8d52948.png)
