### ISSUE TITLE
How can i parser the log filed when i use the rancher logging (fluentd) to efk

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#16673]
![image](https://user-images.githubusercontent.com/14210543/48835743-e1565980-edbb-11e8-9883-5220c99853ad.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`authenticated.cluster.index`|

**Comment by gwiersma** [comment]
+1

**Comment by horihel** [comment]
I second this question. Is there any way (or plan) to support enabling any fluentd parser plugins in cattle-logging, or configure parts of the parser (e.g. with annotations on workloads or via configmap)?

**Comment by deniseschannon** [comment]
Being able to customize your logging is available in v2.2.2. 

Please view step #4 in cluster logging: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/logging/#enabling-cluster-logging

Or step #4 in project logging: https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/logging/#enabling-project-logging
