### ISSUE TITLE
Specifying private_registries in Rancher RKE config causes kubelet/kube-proxy/etc. to constantly be restarted

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#16678]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a cluster provisioned by Rancher using RKE with separate worker, etcd, and control plane hosts.
Add your own private registries (or just docker.io, does not matter) while editing the cluster as YAML i.e.
```
private_registries: 
  - url: "docker.io"
```
Allow cluster to provision and examine the status of the RKE-managed containers on the worker nodes.

**Result:**
Kubelet/kube-proxy/etc. are constantly being restarted by the Rancher node agents on the worker nodes due to the following error message:
```
time="2018-11-21T19:10:26Z" level=info msg="For process nginx-proxy, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:10:28Z" level=info msg="For process kube-proxy, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:10:30Z" level=info msg="For process kubelet, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:12:32Z" level=info msg="For process service-sidekick, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:12:32Z" level=info msg="For process kube-proxy, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:12:34Z" level=info msg="For process kubelet, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:12:36Z" level=info msg="For process nginx-proxy, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:14:39Z" level=info msg="For process service-sidekick, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:14:39Z" level=info msg="For process kube-proxy, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:14:42Z" level=info msg="For process kubelet, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:14:43Z" level=info msg="For process nginx-proxy, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:16:46Z" level=info msg="For process service-sidekick, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:16:47Z" level=info msg="For process kube-proxy, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:16:49Z" level=info msg="For process kubelet, ImageRegistryAuthConfig has changed from e30= to "
time="2018-11-21T19:16:52Z" level=info msg="For process nginx-proxy, ImageRegistryAuthConfig has changed from e30= to "
```
which repeats forever.
**Other details that may be helpful:**
This happens on any conventional OS but for some reason doesn't happen on Rancher OS

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.0.8, 2.1.0, 2.1.1, 2.1.2
- Installation option (single install/HA): Both

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Reproduced on both Infrastructure Provider and Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): any
- Operating System: RHEL/CentOS/Ubuntu

**Comment by superseb** [comment]
Sounds like https://github.com/rancher/rancher/issues/16282

**Comment by Oats87** [comment]
Closing as a duplicate of https://github.com/rancher/rancher/issues/16282
