### ISSUE TITLE
SSL enabled ports behind the load balancer (again)

### ISSUE THREAD

**Issue by boardbloke** [rancher/rancher#16685]
This is a reopening of the issue / request described in issue #2448.
https://github.com/rancher/rancher/issues/2448

It was auto-closed there because the original request was raised in the context of Rancher 1, but in fact it's documenting a missing feature that people have expressed interest in, so I think still relevant.

The original discussion that prompted the original issue was here:
https://forums.rancher.com/t/ssl-enabled-ports-behind-the-load-balancer/730

But in sum, I have a WSO2 servers running that have to expose their services via SSL.  I would like to put those behind a Rancher load balancer that does SSL termination, so the request flow is:

request --ssl--> balancer --ssl--> container

But that does not seem to be supported in current Rancher, or if it is, I can't find documentation to explain how to do it. 

Is this a feature that could be added?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
