### ISSUE TITLE
Not able to launch kubectl shell from UI , gets stuck in "connecting.."

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16681]
Rancher server version - v2.1.2-rc13

Steps to reproduce the problem:
Create a 1 node DO cluster.
Try to launch kubectl shell from UI  using the "launch kubectl" option.
Kubectl  shell gets stuck in "connecting.."

Note - This issue is not seen when testing with v2.1.2-rc12

**Comment by alena1108** [comment]
The cause of kubectl not being available, is the panic described in this issue: https://github.com/rancher/rancher/issues/16682

**Comment by pasikarkkainen** [comment]
I'm seeing the same issue with v2.1.2-rc14, using a custom cluster provisioned with rke (using kubernetes v1.11.3).

"Launch kubectl" fails to connect / show the shell prompt.

**Comment by sangeethah** [comment]
Tested with latest build from master (Nov 26) .
Able to launch kubectl shell from UI for provisioned clusters.
