### ISSUE TITLE
Catalog app YAML editor doesn't support keys with dots in answers

### ISSUE THREAD

**Issue by jamesmcminn96** [rancher/rancher#16680]
What kind of request is this (question/bug/enhancement/feature request): **bug**

**Steps to reproduce (least amount of steps as possible):**

Create a catalog app (Prometheus in my case) and supply answers that aim for this structure when using the yaml editor, then apply
```
alertmanagerFiles: 
  alertmanager.yml: value
```

**Result:**
The yaml is saved in this format
```
alertmanagerFiles: 
  alertmanager:
    yml: value
```

I've tried escaping the dot in the yaml, but it is not preserved

**Environment information**
- Rancher v2.1.1
- User Interface v.2.1.4
- Helm v2.10.0-rancher5
- Machine v0.15.0-rancher1-1
- HA Installation

**Comment by loganhz** [comment]
@jamesmcminn96 

Can you try this pattern, please?
`alertmanagerFiles.alertmanager\.yml: value`

**Comment by loganhz** [comment]
I think https://github.com/rancher/rancher/issues/13158 will address this issue

**Comment by fdlk** [comment]
> @jamesmcminn96
> 
> Can you try this pattern, please?
> `alertmanagerFiles.alertmanager\.yml: value`

That works for me when I try to fill in the answers, thanks!
A roundtrip to yaml and back works, but the yaml is unfortunately incorrect:

```
alertmanagerFiles:
  alertmanager\:
    yml: value
```

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Confirmed issue. See #17605 which covered related testing as well.
When you edit as YAML this is passed as a yaml file in valuesYaml. This is working for me due to this change ( https://github.com/rancher/rancher/pull/17576 PR )

I again validated the http/api like I did in my #17605 testing.
When I inspect the valuesYaml string our whitespaces/carraige returns appear correct just like how they were created in the UI.
![image](https://user-images.githubusercontent.com/45179589/53129346-8a7c2f80-3524-11e9-9385-b42b32310070.png)

**Comment by cfstras** [comment]
This still occurs with Rancher 2.3.3.

Repro:

have a "values.yaml" with 

```yaml
ingress:
  annotations:
    kubernetes.io/ingress.class: something
```
And deploy it with `rancher apps upgrade --values values.yaml ...`

Will cause cause it to be rendered internally as below, you can also see that when clicking "edit as yaml" in the "upgrade" screen.
```yaml
ingress:
  annotations:
    kubernetes:
        io/ingress:
            class: something
```

The workaround with escaping produces the following error:
```
Failed to install app blog. Error: UPGRADE FAILED: v1beta1.Ingress.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|ls-acme":true,"nginx|..., bigger context ...|ess.class":"ingressClass","kubernetes.io/tls-acme":true,"nginx.ingress.kubernetes.io/force-ssl-redirec|...
```

**Comment by cfstras** [comment]
Other users are also affected by this: https://github.com/rancher/rancher/issues/22027

**Comment by NRDiaz92** [comment]
Hi, is there any news on this? i'm having this issue as well

**Comment by petertang2012** [comment]
This is still true for rancher 2.3.5
passing key with dots `rbac.serviceAccountAnnotations.”eks\.amazonaws\.com/role-arn”` renders to 
``` 
serviceAccountAnnotations: 
      "eks: 
        amazonaws: 
```

**Comment by vl-jantoth** [comment]
Still the same issue with rancher 2.5.8

```
spring:
  mail:
     host:
```
