### ISSUE TITLE
rancher 2.1.1 pipeline runScriptConfig image can not use private registries

### ISSUE THREAD

**Issue by Daily1116** [rancher/rancher#16683]
pipeline step 1-0 runScriptConfig，image can not use private registries，please help me

**Comment by gitlawr** [comment]
The imagepullsecret is missing. It is injected in API layer, we need to inject it in similar way for pipeline build pod.

As the workaround in v2.1.1, you can pre-pull necessary images on the hosts before running the pipeline. For example, deploy a daemonset with the image, then remove it when the image is present on all hosts.

**Comment by Daily1116** [comment]
@gitlawr thank you, it works now , but next step is failed, can not build image and push private registries, error info is:

`11:44:21 [pipeline_p-52cb4-9] Running shell script
11:44:22 + /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
11:44:22 + /usr/local/bin/dockerd -g /var/lib/docker --insecure-registry docker-registry.p-kmbfd-pipeline
11:44:22 time="2018-11-22T11:44:22Z" level=warning msg="The \"-g / --graph\" flag is deprecated. Please use \"--data-root\" instead"
11:44:22 time="2018-11-22T11:44:22.377728813Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
11:44:22 time="2018-11-22T11:44:22.378643419Z" level=info msg="libcontainerd: started new docker-containerd process" pid=43
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="setting subreaper..." module=containerd 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="changing OOM score to -500" module=containerd 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." module=containerd type=io.containerd.snapshotter.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." module=containerd type=io.containerd.snapshotter.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." module=containerd type=io.containerd.metadata.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt" 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." module=containerd type=io.containerd.differ.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." module=containerd type=io.containerd.gc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." module=containerd type=io.containerd.monitor.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." module=containerd type=io.containerd.runtime.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." module=containerd type=io.containerd.grpc.v1 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug" 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc" 
11:44:22 time="2018-11-22T11:44:22Z" level=info msg="containerd successfully booted in 0.016682s" module=containerd 
11:44:22 time="2018-11-22T11:44:22.467849023Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
11:44:22 time="2018-11-22T11:44:22.468070378Z" level=warning msg="Your kernel does not support cgroup rt period"
11:44:22 time="2018-11-22T11:44:22.468083578Z" level=warning msg="Your kernel does not support cgroup rt runtime"
11:44:22 time="2018-11-22T11:44:22.470629456Z" level=info msg="Loading containers: start."
11:44:22 time="2018-11-22T11:44:22.487484266Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'\nbridge                126976  1 br_netfilter\nstp                    16384  1 bridge\nllc                    16384  2 bridge,stp\nip: can't find device 'br_netfilter'\nbr_netfilter           24576  0 \nbridge                126976  1 br_netfilter\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
11:44:22 time="2018-11-22T11:44:22.496658918Z" level=warning msg="Running modprobe nf_nat failed with message: `ip: can't find device 'nf_nat'\nnf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE\nnf_nat_ipv4            16384  1 iptable_nat\nnf_nat                 24576  3 xt_nat,nf_nat_masquerade_ipv4,nf_nat_ipv4\nnf_conntrack          106496  6 nf_conntrack_netlink,nf_nat_masquerade_ipv4,nf_conntrack_ipv4,nf_nat_ipv4,xt_conntrack,nf_nat\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
11:44:22 time="2018-11-22T11:44:22.505124564Z" level=warning msg="Running modprobe xt_conntrack failed with message: `ip: can't find device 'xt_conntrack'\nxt_conntrack           16384 122 \nx_tables               36864 15 xt_statistic,xt_multiport,iptable_mangle,ipt_REJECT,xt_comment,xt_tcpudp,xt_set,iptable_raw,xt_nat,xt_mark,ipt_MASQUERADE,xt_addrtype,iptable_filter,ip_tables,xt_conntrack\nnf_conntrack          106496  6 nf_conntrack_netlink,nf_nat_masquerade_ipv4,nf_conntrack_ipv4,nf_nat_ipv4,xt_conntrack,nf_nat\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
11:44:22 time="2018-11-22T11:44:22.616350594Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
11:44:22 time="2018-11-22T11:44:22.665294407Z" level=info msg="Loading containers: done."
11:44:22 time="2018-11-22T11:44:22.701584683Z" level=info msg="Docker daemon" commit=c97c6d6 graphdriver(s)=overlay2 version=17.12.0-ce
11:44:22 time="2018-11-22T11:44:22.701947310Z" level=info msg="Daemon has completed initialization"
11:44:22 time="2018-11-22T11:44:22.714570320Z" level=info msg="API listen on /var/run/docker.sock"
11:44:23 + /usr/local/bin/docker version
11:44:23 Client:
11:44:23  Version:	17.12.0-ce
11:44:23  API version:	1.35
11:44:23  Go version:	go1.9.2
11:44:23  Git commit:	c97c6d6
11:44:23  Built:	Wed Dec 27 20:05:38 2017
11:44:23  OS/Arch:	linux/amd64
11:44:23 
11:44:23 Server:
11:44:23  Engine:
11:44:23   Version:	17.12.0-ce
11:44:23   API version:	1.35 (minimum version 1.12)
11:44:23   Go version:	go1.9.2
11:44:23   Git commit:	c97c6d6
11:44:23   Built:	Wed Dec 27 20:12:29 2017
11:44:23   OS/Arch:	linux/amd64
11:44:23   Experimental:	false
11:44:23 + /usr/local/bin/docker info
11:44:23 Containers: 0
11:44:23  Running: 0
11:44:23  Paused: 0
11:44:23  Stopped: 0
11:44:23 Images: 0
11:44:23 Server Version: 17.12.0-ce
11:44:23 Storage Driver: overlay2
11:44:23  Backing Filesystem: extfs
11:44:23  Supports d_type: true
11:44:23  Native Overlay Diff: true
11:44:23 Logging Driver: json-file
11:44:23 Cgroup Driver: cgroupfs
11:44:23 Plugins:
11:44:23  Volume: local
11:44:23  Network: bridge host macvlan null overlay
11:44:23  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
11:44:23 Swarm: inactive
11:44:23 Runtimes: runc
11:44:23 Default Runtime: runc
11:44:23 Init Binary: docker-init
11:44:23 containerd version: 89623f28b87a6004d4b785663257362d1658a729
11:44:23 runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
11:44:23 init version: 949e6fa
11:44:23 Security Options:
11:44:23  seccomp
11:44:23   Profile: default
11:44:23 Kernel Version: 4.4.0-87-generic
11:44:23 Operating System: Alpine Linux v3.7 (containerized)
11:44:23 OSType: linux
11:44:23 Architecture: x86_64
11:44:23 CPUs: 16
11:44:23 Total Memory: 31.4GiB
11:44:23 Name: jenkins-slave-ts1f3-pz7gx
11:44:23 ID: BR7W:K2CQ:VDHW:REDO:XWTT:3PRP:RQ7C:HICZ:O35P:VZ4W:2TVG:WHJ2
11:44:23 Docker Root Dir: /var/lib/docker
11:44:23 Debug Mode (client): false
11:44:23 Debug Mode (server): false
11:44:23 Registry: https://index.docker.io/v1/
11:44:23 Labels:
11:44:23 Experimental: false
11:44:23 Insecure Registries:
11:44:23  docker-registry.p-kmbfd-pipeline
11:44:23  127.0.0.0/8
11:44:23 Live Restore Enabled: false
11:44:23 
11:44:23 WARNING: bridge-nf-call-iptables is disabled
11:44:23 WARNING: bridge-nf-call-ip6tables is disabled
11:44:23 + /usr/local/bin/docker build --rm=true -f ./Dockerfile -t 00000000 . --pull=true --label org.label-schema.build-date=2018-11-22T11:44:23Z --label org.label-schema.vcs-ref=00000000 --label org.label-schema.vcs-url=
11:44:24 Sending build context to Docker daemon  34.76MB

11:44:24 Step 1/8 : FROM java:8-jre-alpine
11:44:36 time="2018-11-22T11:44:35.473711390Z" level=warning msg="Error getting v2 registry: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout"
11:44:36 time="2018-11-22T11:44:35.473846823Z" level=info msg="Attempting next endpoint for pull after error: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout"
11:44:36 Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
11:44:36 time="2018-11-22T11:44:35Z" level=fatal msg="exit status 1"`

please help me .

**Comment by kapolos** [comment]
@gitlawr Is pushing built images on private registries also planned for `v2.2` or is the milestone only for pulling from private registries?

**Comment by gitlawr** [comment]
@Daily1116 The failure shows that you failed due to network connection. Are you in an air-gapped environment?
You are using `java:8-jre-alpine` as the base image in the Dockerfile, which is from docker hub. In the case when you cannot access docker hub you need to use base images from your private registry.
```
# example Dockerfile
FROM registry.example.com/somepath/java:8-jre-alpine

RUN anything
```

**Comment by gitlawr** [comment]
@kapolos This issue is for using private images as the context image in runScript steps. You can build and publish to private registry now.

**Comment by Daily1116** [comment]
@gitlawr It not in an air-gapped environment. now i change base image in the Dockerfile. Still failed.

Dockerfile 
```
FROM index.paas.com/software/base-jre:8
LABEL author=Daily1116
VOLUME /tmp
COPY target/demo.jar app.jar
EXPOSE 8090
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```
.rancher-pipeline.yml

```
stages:
- name: compile
  steps:
  - runScriptConfig:
      image: index.paas.com/software/maven:1.0
      shellScript: mvn clean package -Dmaven.test.skip=true
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
- name: build_push_image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: index.paas.com/spring_cloud/demo:test
      pushRemote: true
      registry: index.paas.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
    when:
      branch:
        include:
        - master
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
```
The error info is:
```
01:26:02 [pipeline_p-52cb4-10] Running shell script
01:26:04 + /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
01:26:04 + /usr/local/bin/dockerd -g /var/lib/docker --insecure-registry index.paas.com
01:26:04 time="2018-11-23T01:26:04Z" level=warning msg="The \"-g / --graph\" flag is deprecated. Please use \"--data-root\" instead"
01:26:04 time="2018-11-23T01:26:04.515431226Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
01:26:04 time="2018-11-23T01:26:04.516520109Z" level=info msg="libcontainerd: started new docker-containerd process" pid=36
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="setting subreaper..." module=containerd 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="changing OOM score to -500" module=containerd 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." module=containerd type=io.containerd.snapshotter.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." module=containerd type=io.containerd.snapshotter.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." module=containerd type=io.containerd.metadata.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt" 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." module=containerd type=io.containerd.differ.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." module=containerd type=io.containerd.gc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." module=containerd type=io.containerd.monitor.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." module=containerd type=io.containerd.runtime.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." module=containerd type=io.containerd.grpc.v1 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug" 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc" 
01:26:04 time="2018-11-23T01:26:04Z" level=info msg="containerd successfully booted in 0.014546s" module=containerd 
01:26:04 time="2018-11-23T01:26:04.604572072Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
01:26:04 time="2018-11-23T01:26:04.604829417Z" level=warning msg="Your kernel does not support cgroup rt period"
01:26:04 time="2018-11-23T01:26:04.604844298Z" level=warning msg="Your kernel does not support cgroup rt runtime"
01:26:04 time="2018-11-23T01:26:04.607416598Z" level=info msg="Loading containers: start."
01:26:04 time="2018-11-23T01:26:04.625899918Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'\nbridge                126976  1 br_netfilter\nstp                    16384  1 bridge\nllc                    16384  2 bridge,stp\nip: can't find device 'br_netfilter'\nbr_netfilter           24576  0 \nbridge                126976  1 br_netfilter\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
01:26:04 time="2018-11-23T01:26:04.636087859Z" level=warning msg="Running modprobe nf_nat failed with message: `ip: can't find device 'nf_nat'\nnf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE\nnf_nat_ipv4            16384  1 iptable_nat\nnf_nat                 24576  3 xt_nat,nf_nat_masquerade_ipv4,nf_nat_ipv4\nnf_conntrack          106496  6 nf_conntrack_netlink,nf_nat_masquerade_ipv4,nf_conntrack_ipv4,nf_nat_ipv4,xt_conntrack,nf_nat\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
01:26:04 time="2018-11-23T01:26:04.645230438Z" level=warning msg="Running modprobe xt_conntrack failed with message: `ip: can't find device 'xt_conntrack'\nxt_conntrack           16384 122 \nx_tables               36864 15 xt_statistic,xt_multiport,iptable_mangle,ipt_REJECT,xt_comment,xt_tcpudp,xt_set,iptable_raw,xt_nat,xt_mark,ipt_MASQUERADE,xt_addrtype,iptable_filter,ip_tables,xt_conntrack\nnf_conntrack          106496  6 nf_conntrack_netlink,nf_nat_masquerade_ipv4,nf_conntrack_ipv4,nf_nat_ipv4,xt_conntrack,nf_nat\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
01:26:04 time="2018-11-23T01:26:04.764449714Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
01:26:04 time="2018-11-23T01:26:04.816670967Z" level=info msg="Loading containers: done."
01:26:04 time="2018-11-23T01:26:04.846828914Z" level=info msg="Docker daemon" commit=c97c6d6 graphdriver(s)=overlay2 version=17.12.0-ce
01:26:04 time="2018-11-23T01:26:04.847200283Z" level=info msg="Daemon has completed initialization"
01:26:04 time="2018-11-23T01:26:04.857406372Z" level=info msg="API listen on /var/run/docker.sock"
01:26:06 time="2018-11-23T01:26:06.673440497Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://index.paas.com/v2/: dial tcp: lookup index.paas.com on 10.43.0.10:53: no such host"
01:26:06 time="2018-11-23T01:26:06.675997534Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get http://index.paas.com/v2/: dial tcp: lookup index.paas.com on 10.43.0.10:53: no such host"
01:26:06 time="2018-11-23T01:26:06.676077379Z" level=error msg="Handler for POST /v1.35/auth returned error: Get http://index.paas.com/v2/: dial tcp: lookup index.paas.com on 10.43.0.10:53: no such host"
01:26:06 time="2018-11-23T01:26:06Z" level=fatal msg="Error authenticating: exit status 1"
```

**Comment by gitlawr** [comment]
It shows that `index.paas.com` is not resolvable in pods

**Comment by Daily1116** [comment]
@gitlawr 
Then how can I solve it?

**Comment by gitlawr** [comment]
I assume the domain name is something you set in `/etc/hosts` on the hosts. It takes no effect in pods because kubenetes manage it in pods.
One solution is to add that custom DNS entry to pods
```
# pod.spec
hostAliases:
  - ip: "your registry ip"
    hostnames:
    - "index.paas.com"
```
The build pod is provisioned dynamically and there's no configuration entry for this. But you can try to add the above entry to kube-dns deployment, if you're using kube-dns.

**Comment by Daily1116** [comment]
@gitlawr 
as you said, the build pod is provisioned dynamically, so user can not set dnsPolicy default, can it be resolved in v2.2？

**Comment by gitlawr** [comment]
@Daily1116 I believe adding the entry to kube-dns helps in the case, you don't need to configure the dnsPolicy for the build pod. Have you tried that or it does not work for you?
Additionally, you can configure a custom nameserver for the publish step instead of the default cluster dns:
```
    env:
      PLUGIN_CUSTOM_DNS: "8.8.8.8"
```

**Comment by Daily1116** [comment]
@gitlawr I does not tried to add the entry to kube-dns yet. Can you provide a method how to add it?https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/configurations/ 
Available variables includes do not have PLUGIN_CUSTOM_DNS , Other variables do not provide an example description,Is the guidance document to be more detailed?

**Comment by gitlawr** [comment]
it is not a pipeline-scoped configuration so you cannot find it there.
Here's the instruction via UI:
1. Go to system project
2. find the workload named `kube-dns` under `kube-system` namespace. Edit it.
3. Click `upgrade` for kubedns container(the first one)
4. Roll down to the bottom, click `show advanced options`
5. Expand the networking tab, find the `Host Aliases` option
6. Click `Add Host Alias` and input the dns entry according to your need.

if you use kubectl, 
1. `kubectl edit deploy kube-dns --namespace kube-system`
2. Edit the deployment yaml and add what i've mentioned above.

**Comment by Daily1116** [comment]
@gitlawr it works through add the entry to kube-dns, thank you very much!

**Comment by Daily1116** [comment]
@gitlawr another issue, in runScriptConfig step, I found that every time maven is built, it go to download the jars. it costs much time, Is there any way to cache the built jars?

**Comment by rootwuj** [comment]
Tested with Rancher -2.2 master 01/29
Verified fixed
This version of Pipeline can use private registries and run successfully.

**Comment by adrianovieira** [comment]
Hi! 

I have this problem on 2.1.9.

Will this issue be fixed on 2.1 series?

cc: @loganhz

**Comment by gitlawr** [comment]
@adrianovieira The fix is in 2.2 and we probably won't backport it to 2.1

**Comment by ainiml** [comment]
What dns entry should you give it, if the private registry is running in a container

Should you give it its internal address, like `registry.default` if it's in the default namespace?

**Comment by gitlawr** [comment]
@ainiml The image is pulled by dockerd on the node, so it should be something accessible on your hosts.
