### ISSUE TITLE
DNS support for containers on Host network

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1669]
Today we don't register containers on Host network to Rancher DNS, so DNS resolution won't work for services having networking=host. 

Now about possible way to implement it. The idea of host networking is that we don't do anything with networking. So we would not be assigning a 10.42 IP to the host. We could resolve that DNS entry to the IP of server, but that will be the CATTLE_AGENT_IP. From the Rancher perspective we just have that one IP, if your server has different IPs or an externally bound IP (like Amazon EIP), we wouldn't know about it. So the IP we would resolve to might be a little limited in flexibility. 

So we'll have to think whether to 1) Simply default container IP to the ip address of the rancher agent. 2_ introduce one extra parameter to addHost API allowing to specify public host ip address, and use this address for DNS resolution

@will-chan

**Comment by alena1108** [comment]
A service with host level network will get registered to rancher dns only when label "io.rancher.network.dns"=true is set for it.

**Comment by Kelindar** [comment]
@alena1108 Sounds good, I'll make sure to try this in the next release.

**Comment by alena1108** [comment]
@Kelindar corresponding PR is still in review - https://github.com/rancher/cattle/pull/727, but we do aim to include it to the next release

**Comment by Kelindar** [comment]
@alena1108 Cool, no rush. 

Just leaving a suggestion here, instead of a simple flag for the label, would it be possible to specify the interface? Something like `io.rancher.container.dns="docker0"`, `io.rancher.container.dns="eth0"` or even a url, for example `io.rancher.container.dns="http://ipv4.icanhazip.com"` would simply issue an `HTTP GET` on the specified url and get the external IP address that way (or any address) and publish this to the DNS. What do you think?

**Comment by alena1108** [comment]
@Kelindar unfortunately its not how its implemented in the first run. The ip address of the instance would always be the host ip specified in "CATTLE_AGENT_IP" during the host registration (as per comments in http://forums.rancher.com/t/service-discovery-of-containers-with-host-networking/155). And today label "io.rancher.container.dns" more stands for "user internal rancher dns", not the ip address that you would want your container to be registered as.

We will def enhance this functionality in the future releases as specifying exact ip is a very valid use case when your host has multiple interfaces + EIP. I'll file a ticket to keep track of it as soon as the initial version gets in.

**Comment by alena1108** [comment]
@sangeethah the fix is in master

**Comment by sangeethah** [comment]
Tested with build from master - Aug 13.

DNS support for containers on Host network works when service is deployed with label "io.rancher.container.dns"=true. 
There are few issues found when testing different use cases which are tracked as separate issues - #1792 , #1793 and #1794.
