### ISSUE TITLE
/ping endpoint not GCE Kubernetess ingress compliant as a healthcheck

### ISSUE THREAD

**Issue by lukewhiting** [rancher/rancher#16693]
The /ping endpoint often used as a health indicator is subject to the same rules on HTTP redirects as all other endpoints. This means that ingress controllers that are a bit stricter on health checks like Google's Load Balancer always mark Rancher instances as unhealthy as the ping returns a 302 FOUND redirect rather than a 200 OK it requires (See https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-loadbalancing/glbc#limitations for details on required return types).

Ideally HTTP proxy should be modified so the ping endpoint never does a redirect to HTTPS.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Make a request to the `/ping` endoint

**Result:**
HTTP 302 FOUND status returned

**Other details that may be helpful:**
See Above

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.0
- Installation option (single install/HA): HA on GKE (I'm aware this is not supported but this is the last impediment to running it in a GKE VPC. I hope to submit docs and helm charts to make it an official way of hosting Rancher HA in the future).

**Comment by lukewhiting** [comment]
@loganhz I notice a commit for this got merged into 2.1.4 however it does not seem to have fixed the issue. The `/healthz` and `/ping` endpoints still redirect to https when hit via http on port 80.

```
GET http://localhost:8080/healthz  <-- Port 8080 is a kubectl proxy to port 80 on the container

Content-Type →text/html; charset=utf-8
Location →https://localhost:8443/healthz
Date →Thu, 03 Jan 2019 16:43:07 GMT
Content-Length →53

302 Found

<a href="https://localhost:8443/healthz">Found</a>.
```

**Comment by superseb** [comment]
Can you explain where you see it being merged in v2.1.4? The PR is merged 13 days ago and v2.1.4 is released 17 days ago.

It's also merged in master, which is for 2.2.x

**Comment by lukewhiting** [comment]
Sorry your absolutely right I had the diff round the wrong way :man_facepalming: My head is still full of turkey and mice pies :-)

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/7

* Reproduced on 2.1.6, saw `http://<host>/healthz` endpoint return 302 Found. 
* On master, `http://<host>/healthz` returns 200 OK.
