### ISSUE TITLE
k8s nodes go to Unavailable status

### ISSUE THREAD

**Issue by eliyahu77** [rancher/rancher#16690]
HI, 
 I run rancher with k8s , nodes go to Unavailable status case out of ram memory , 
there is any option in the creation cluster using curl , to add flags for reserved memory and cpu for kubelet service and system services , 

env details : 
Kubelet Version v1.10.5
Docker Version 17.12.1-ce
Rancher  Version v2.1.1

curl body
{
	"type": "cluster",
	"nodes": [],
	"rancherKubernetesEngineConfig": {
		"ignoreDockerVersion": true,
		"kubernetesVersion": "v1.10.5-rancher1-2"
	},
	"name": "clustername"
}

BR Eliyahu

**Comment by loganhz** [comment]
Hi @eliyahu77 

It looks like you can config it by adding extra args `--kube-reserved` for kubelet

When you create cluster, you can edit cluster options via yaml in Rancher UI.

https://rancher.com/docs/rke/v0.1.x/en/config-options/services/services-extras/
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved

**Comment by eliyahu77** [comment]
HI ,
thanks for replay , I try to reserved ram and memory for rancher agent , my
problem is when i deploy a lot of services the ram on the node is out of
space , and i think the problem is the rancher agent not have memory , how
can i solve this problem? , and case if i cannot do , so i have to create
extra sizing to all nodes ?
what is the best practice of rancher ?

thanks u a lot logan for the help

BR Eliyahu

**Comment by loganhz** [comment]
cc @superseb
