### ISSUE TITLE
ClusterRoles are showing up in project member assignment view

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16700]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create a cluster role
2. navigate to project -> members
3. add project member
4. cluster role created shows up here

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/3/18)
Replicated in older version. Confirmed fixed in latest master build. Followed the steps to reproduce and was not able in master. Performed halo testing.
