### ISSUE TITLE
Remove the text in node driver icon

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16701]
There is node driver name in the svg icon for Aliyun/Openstack/Packet/Rackspace

We should remove them.

![image](https://user-images.githubusercontent.com/21168270/48974914-80bb6b00-f0a0-11e8-8845-4d0803a46998.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/10/19)
Confirmed fix. The text within the node driver icon (in the image) has been removed. I enabled all node drivers to ensure they all look good now. A couple are a bit out of alignment but this is an improvement. I will enter a minor bug around this.
![image](https://user-images.githubusercontent.com/45179589/50990927-a7a6f280-14d0-11e9-880a-d0f4e040f75d.png)
