### ISSUE TITLE
Update node roles/taints

### ISSUE THREAD

**Issue by mvehar** [rancher/rancher#16703]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Current way to change node roles is by changing node labels and modifying node taints.
But after cluster change (adding/removing node) all changes are reverted.

**Result:**
Updated labels/taints on nodes are reset after adding/removing cluster nodes

**Other details that may be helpful:**

**Environment information**
rancher/rancher:stable (2.1.1 - single node master)

**Cluster information**
- Cluster type - custom:
- Machine type - VMs:
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Docker (use `docker info`):
docker-ce 18.06.1-ce

**Comment by rene-demonsters** [comment]
Can confirm that this is still an issue in Rancher 2.1.6.

I can edit the labels, doesn't have any effect. Not even after a reboot.

Running the `sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.6 --server https://example.com --token [removed] --controlplane --worker` command will temporarily make it blink different roles (currently it has All roles, I'm trying to drop etcd from it).

I'm not even trying to add/remove nodes from the cluster. Just keeping it running and I can't seem to change it.

**Comment by MSandro** [comment]
I have a simular issue, I have a controller node which currently only has the ETCD and Control Plane roles and a worker node, but because I whant to deploy some containers on the controller node, I have to add the worker role, it seems to not work. I've tried to add the label, execute the command, and restarted the nodes, but nothing solved the issue. My custom cluster is not able to deploy a workload on the controll container.

I am on Rancher v2.1.8.

**Comment by bruno-lopes** [comment]
Any news on this?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/22319
