### ISSUE TITLE
Unable to add docker host 

### ISSUE THREAD

**Issue by hbajaj2** [rancher/rancher#1670]
Hi All, We are running Docker with -H  flag (tcp://0.0.0.0:2375), to ensure Swarm API's are available over TCP. I tried running Rancher agent on this Docker node and it fails around validating Docker version, as it tries to directly access Docker, without specifying -H flag. Is there a workaround available to update Rancher agent to connect using -H flag. We are running Docker on CentOS 7 and using latest version of Rancher server/agent.

**Comment by ebuildy** [comment]
Hello,

As a dirty fix, you can run Docker on both TCP and .sock:

````
-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock
````

**Comment by ibuildthecloud** [comment]
@hbajaj2 @ebuildy's answer is correct.  Not really a dirty hack.  We require the unix socket to talk to Docker.  So just add both `-H` parameters.
