### ISSUE TITLE
[2.0][AWS] Rancher pods logs and Nginx gives 504 gateway timeout 

### ISSUE THREAD

**Issue by kc004** [rancher/rancher#16706]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**  I am making a hybrid cluster with on-premise servers and AWS servers. I already made a cluster with on-premise servers and when I add aws server in this cluster daemon set pods IP address is automatically assigned same as private IP of AWS server. When I browse through the pods logs it gives me 504 gateway timeout and I made nginx server on a cluster using AWS server, it gives me 504 gateway timeout it means the request is accepted at nginx server and it throws 504.

Command which i ran on AWS server: 
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.0 --server https://xx.xx.xx.xx --token dpntmq6888pzxn6dwnsqvx4g7xndbqf6k9dc5zrs7g7zk4x8bk7xs8 --ca-checksum 0bf4361e19d4e4c6495add22cec75a95aad0049f4f0da94d7451edaf47b5cc71 --address xx.xx.xx.xx --internal-address 172.31.13.71 --worker

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.0

**Cluster information** 
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hybrid
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud and metal
- Kubernetes version (use `kubectl version`): 1.10.1
- Docker version: 18.6.1

**Comment by qubusp** [comment]
You can not run kubernetes on Docker 18.6.1, it's not supported.

**Comment by kc004** [comment]
still getting the same error with docker version 17.03.3

**Comment by qubusp** [comment]
Do you have on premise master as well, because it has to be visible too.

**Comment by superseb** [comment]
There is not enough information provided to root cause the issue. How are the nodes in AWS and on-premise able to connect to each other? Is there a tunnel or is it through external IPs? The ports required for all nodes are described here: https://rancher.com/docs/rancher/v2.x/en/installation/references/

Based on the error, the NGINX can't route to a pod which could be caused by overlay network not functioning correctly. 

```kubectl get nodes -o template --template='{{range.items}}{{.metadata.name}}{{"\t"}}{{range.status.addresses}}{{if eq .type "InternalIP"}}{{.address}}{{end}}{{if eq .type "ExternalIP"}}{{"\t"}}{{.address}}{{end}}{{end}}{{"\n"}}{{end}}'``` will give you all the IP addresses the nodes are registered with to check if they can communicate with each other.

**Comment by kc004** [comment]
@superseb Hi, I ran command given by you and it shows me internal IP of my AWS server and all on-premises servers having external IP. so, that's why AWS server can't connect with other servers. Now how can I tell rancher to use External IP?
