### ISSUE TITLE
Dark Theme contrast issues

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16712]
Version 2.2 master (11/26/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, Usability

**Results:**

- [x] Global Menu search box has poor contrast (light blue on medium gray)
![screen shot 2018-11-26 at 10 24 46 am](https://user-images.githubusercontent.com/45179589/49030774-8a5ad680-f165-11e8-8400-1d72f57c8cac.png)

- [x] Text contrast in settings value fields is poor (Settings page)
![screen shot 2018-11-26 at 10 26 03 am](https://user-images.githubusercontent.com/45179589/49030841-b2e2d080-f165-11e8-95a9-6056d6068042.png)

**Comment by davidnuzik** [comment]
Text in search box field not fixed.

**Comment by westlywright** [comment]
Had to roll back some changes on master this will be on hold until we can merge again.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/6/19)
Confirmed fix.
Search box now has highly visible text:
![image](https://user-images.githubusercontent.com/45179589/52370679-c4bbdc00-2a10-11e9-8a5b-7020c65645b4.png)

Text in text fields such as on settings page now has highly visible text:
![image](https://user-images.githubusercontent.com/45179589/52370725-ddc48d00-2a10-11e9-9b0e-7bbf6dd8d23d.png)
