### ISSUE TITLE
Tons of secret volumes is left inactive and orphaned, causing slow page load in UI

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#16719]
Rancher version:
1.6.x

Step to reproduce:
1. Enable secret driver and create a secret named foo.
2. Make image name an invalid name and create a service using secret foo. 

Result:
The service won't start due to invalid image name and In infrastructure/storage, inactive volumes keep being created. When the service is deleted, inactive volumes are not cleaned up.

This is because when we delete service, we find all the mounts associated with instances. But if a secret volume does not have a mount(which might happen in the scenario described above) it won't get cleaned up along with instances. A proper fix is to find all the inactive secret driver volumes that are not associated any instance and purge those in cleanup thread.

**Comment by rafabios** [comment]
I have the same issue:

https://github.com/rancher/rancher/issues/16231


I had to modify a script to lunch every hour in order to clean this up:

```
#!/bin/bash

rancher volumes ls -a > volumes.txt

cat volumes.txt | grep inactive | cut -d' ' -f1 > volumes_id.txt

FILE_PARA_O_CONTADOR="volumes_id.txt"

#loop
    for i in $(cat $FILE_PARA_O_CONTADOR ); do
      rancher volumes rm $i


      done

```

**Comment by mveroone** [comment]
I know rancher 1.6.x is now restricted to critical bug fixed ans security patches.

Doesn't this qualifies as a critical bug ?  
We have CI/CD using rancher, and the number of volumes in inactive state is growing quite fast...

**Comment by stefanlasiewski** [comment]
I reproduced this problem in our test environment:

1. Verify that the problem is not present

        $ rancher volume ls --all |grep "inactive *rancher-secrets"

2. Create a secret

        $ openssl rand -base64 8 > web-password 
        $ rancher secret create web-password web-password 
        1se377 
        $

3. Review the stack. Note how the service references the secret but has a bogus Docker image:

        $ cat docker-compose.yml 
        version: '2' 
        services: 
        web: 
        image: nginx-bogus 
        secrets: 
        - mode: '0444' 
        uid: '0' 
        gid: '0' 
        source: web-password 
        target: web-password

        secrets: 
        web-password: 
        external: true

        $

4. Start the stack and wait a couple minutes. Notice how it fails to start, but never really exits. Eventually, I give up and hit ^C:

        $ rancher up 
        INFO[0000] Creating stack stale-secrets-test 
        INFO[0001] Secret web-password already exists 
        INFO[0001] [web]: Creating 
        INFO[0001] Creating service web 
        INFO[0001] [web]: Created 
        INFO[0001] Secret web-password already exists 
        INFO[0001] [web]: Starting 
        1s5691 
        INFO[0006] [web]: Started 
        ERRO[0006] Failed to get logs for stale-secrets-test-web-1: Failed to find action: logs 
        ^C 
        $

5. Now, notice how there are a bunch of 'inactive' rancher-secrets volumes. If I had let command 4 run indefinitely, there could be thousands of these volumes. I believe that if we wait long enough, these things eventually become 'detached'.

        $ rancher volume ls --all |grep "inactive *rancher-secrets" 
        1v359782 ea159d8623066bedabcdefghijkmokdjas414e7f88bf9235ad22fe84e804d6ca inactive rancher-secrets 
        1v359784 514d540c1f0a049fjkasjdklajsdlasjdlajsdlaj55c53e7692ac2cbef49d0ce inactive rancher-secrets 
        1v359786 29c17823439b9cfaklakdskadljmlvcasn2a4ae9048702a6ab913c8d775ab9a7 inactive rancher-secrets 
        1v359788 d8da906dbe9d00asjdlkasjdklsadkajsljljdlasd7bb2c682ee23eca78f7aa0 inactive rancher-secrets 
        1v359790 kasdjasjdlasjdlajsdljsdlajsdlajsdl21c268940c9bb51955499cea84a68c inactive rancher-secrets 
        1v359792 iqwoeiqpeiqwpeiasjkdlajlajhlajhdiasoiuqioweu11dfd32aaf22aa651a57 inactive rancher-secrets 
        $

**Comment by stefanlasiewski** [comment]
I managed to delete 11,000 stale secrets using the following commands. Note that the `sleep` statements were necessary for me, otherwise the Rancher API got overwhelmed with requests which led to failures with Rancher managing certain infrastructure stacks.

```
rancher volume ls |grep 'detached *rancher-secrets' | cut -f1 -d" " | while read V
do 
    rancher volume rm $V
    sleep 1
done
```

And I also had success deleting them in batches of 100, and sleeping for a minute or two. This was faster than the method above, but there's a risk it might DOS the Rancher API.

```
while true; do
  rancher volume ls |grep 'detached *rancher-secrets' | head -100 | cut -f1 -d" " | while read V; do 
    rancher volume rm $V
  done
  sleep 60
done
```

**Comment by mveroone** [comment]
I have setup a similar script on our environments, but is often not enough, and I have to run a bunch of SQL .
Here is a sample from my history :
```
elete from volume_storage_pool_map where state='removed';
delete from volume where state in ('inactive','detached') and id not in (select volume_id from volume_storage_pool_map);
delete from storage_pool where id in (select storage_pool_id from storage_pool_host_map where state=removed);
```

**Comment by alena1108** [comment]
@StrongMonkey provided 2 queries needed to cleanup all the dangling volumes:

```
delete s from volume_storage_pool_map as s join (select id from volume as vv where vv.data like '%\"driver\":\"rancher-secrets\"%' and created < date_sub(utc_timestamp(), INTERVAL 1 HOUR) and vv.state = "inactive" and vv.instance_id is NULL and id not in(select volume_id from mount as m where m.state != "removed" or m.state != "purged")) vx on vx.id = s.volume_id;
delete v from volume as v join (select id from volume as vv where vv.data like '%\"driver\":\"rancher-secrets\"%' and created < date_sub(utc_timestamp(), INTERVAL 1 HOUR) and vv.state = "inactive" and vv.instance_id is NULL and id not in(select volume_id from mount as m where m.state != "removed" or m.state != "purged")) vx on vx.id = v.id;
```

**Comment by alena1108** [comment]
We are going to address this issue by running secrets cleanup on periodic basis. This would be the least impactful fix.

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc1`

**Comment by StrongMonkey** [comment]
@soumyalj 
To reproduce this issue:
1. Use an old build without this fix. Enable secret driver and create a secret named foo in UI.
2. Create a stack and service, make service an invalid image so that it will crash and restart. Make sure this service reference secret name foo that just gets created.
3. Go to storage tab and watch volumes. There should have been volumes that keeps getting created. Watch for 10 minutes as volume should keep growing.

Expected:
Upgrade or use the latest build `rancher/server:v1.6.29-rc1`. Volume will be purged at a certain interval. Watch for a couple of minutes and volume should constantly be cleaned up.

**Comment by StrongMonkey** [comment]
@soumyalj 
Sorry the clean up logic only delete stale volumes that were created for at least a hour https://github.com/rancher/cattle/pull/3271/files#diff-061c90d552756a7400ba2ee8416649d2R139. So make sure volumes that were created get purged after one hour.

**Comment by soumyalj** [comment]
Reproduced the issue with v1.6.26 with the steps above. Lots of secret volumes get created as below:
![Screen Shot 2019-09-27 at 2 26 48 PM](https://user-images.githubusercontent.com/18536626/65803265-f108a200-e132-11e9-9fdb-cdc11c8a4104.png)

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc3`

**Comment by StrongMonkey** [comment]
To make sure set these two settings:
`mount_delete.purge.after.seconds`: `x`. Delete volume and volume mount if they are older than x seconds
`task.table.cleanup.schedule`: `x`. Run database clean up thread per x seconds

**Comment by soumyalj** [comment]
Tested with v1.6.29-rc3.

Enable secret driver and create a secret named foo in UI.
Create a stack and service, make service use an invalid image so that it will crash and restart.
Make sure this service reference secret name foo that just gets created. Many secret volumes get created. For testing , set the `mount_delete.purge.after.seconds = 30` and 
`task.table.cleanup.schedule = 30`. 
(Note: Make sure "s" is not added when setting the above two paramters)
After 30s, all the inactive volumes get deleted as expected.

**Comment by abeMedia** [comment]
Cleanup code doesn't work for volumes in `detached` state.
