### ISSUE TITLE
Unable to remove private registry from cluster

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16718]
Version: master 2.2 (11/26/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, Functional

**Steps to reproduce (least amount of steps as possible):**

1. Create any cluster. Edit it by adding a private registry (Advanced options). Leave it blank -- do not modify anything. Save and wait for the cluster to update.
2. Edit the cluster again. Try to remove this empty private registry and notice you cannot. The UI will report: "You must designate one private registry as the default"

**Result:**
You cannot remove a private registry from a cluster.

**Comment by westlywright** [comment]
@davidnuzik can this be closed in favor of rancher/rancher#16767? Also the repro is wrong, only RKE clusters should have private registries. Regardless this will be resolved by

**Comment by davidnuzik** [comment]
@westlywright yes I'll close this one.
Refer to #16767
