### ISSUE TITLE
Edit service page shows scale set to "1" for service with scale 0.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1671]
Server version - V0.30.0-rc3

Create a service with scale 1.
Scale down the service.
Service scale is set to 0 for service.
Edit this service.
Edit service page shows scale set to "1" .
Expected Behavior:
Edit service page should the scale as "0".

**Comment by vincent99** [comment]
The minimum on the slider is 1, because 0 used to make no sense.

**Comment by deniseschannon** [comment]
Verified Fixed v0.31.0-rc4
