### ISSUE TITLE
Add cluster/project level catalog, the templates will disappear after one hour

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#16721]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add catalog at cluster/project level
2. View cluster/project level templates after an hour

**Result:**
Can't see the corresponding templates.

**Other details that may be helpful:**
Private/public catalog has the same problem.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher: master
- Installation option (single install/HA):

**Comment by rootwuj** [comment]
https://github.com/rancher/rancher/issues/16585

**Comment by loganhz** [comment]
Hi @mrajashree

any idea about this issue?

**Comment by alena1108** [comment]
@loganhz can we get @guangbochen to look at the issue as he's put the attempted fix at some point.

**Comment by guangbochen** [comment]
@alena1108 submitted a fix PR in #16774.

**Comment by rootwuj** [comment]
Version -2.2 master 12/04
Verified fixed
