### ISSUE TITLE
Can not exec ping command using common user

### ISSUE THREAD

**Issue by ChrisYuan** [rancher/rancher#16727]
*Describe your issue here*

Can not exec ping command using common user(not root, root can exec ping), error bellow:
ping: icmp open socket: Operation not permitted.

Is this a bug or a mistake made by wrong operation?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by cjellick** [comment]
This is not enough detail to understand or reproduce the problem. Please provide specific steps to reproduce. Assume we know nothing about the context in which you are attempting to execute the ping.

**Comment by ChrisYuan** [comment]
> This is not enough detail to understand or reproduce the problem. Please provide specific steps to reproduce. Assume we know nothing about the context in which you are attempting to execute the ping.

Hi there, I made a image by my Mac, and I used docker-save to export the image then I loaded it to rancher local repository. Next, I used rancher(rancher 2.0.4 with k8s) to deploy container service using this image. Finally, I login the container and changed to a normal user(not root), use command-ping. The rancher k8s container shows an error: "ping: icmp open socket: Operation not permitted." - https://stackoverflow.com/questions/53501716/i-can-not-use-command-ping-by-user-gpadminnot-root. 
Actually, 1) I run a container in my local Mac and ping is ok(not root) 2) then I tried anther rancher environment(rancher 2.1.1) and it also worked 3) I also tried to run a container using the same image on local docker service in the same machine with rancher 2.0.4, still worked. The only problem is rancher 2.0.4 k8s deploy.
I don't know if this scenario is enough, please give me a hand, Thanks~
