### ISSUE TITLE
After upgrading from 2.1.1 to 2.1.2-rc16 , cattle-node-agent daemonset in system project is stuck in "updating" state. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16722]
Rancher Server -> 2.1.1 upgraded to 2.1.2-rc16

Setup:
Fresh install of 2.1.1
Create a custom cluster with 5 nodes - rhel 7.5 with native docker 1.13 with following configuration:
1 control nodes
1 etcd nodes
3 worker nodes

Create projects , namespace and deploy few workloads and ingress.

Upgrade rancher server to 2.1.2-rc16.

Cluster gets to "Unavailable"state for sometime and is back to "active" state.

After this notice that ```cattle-node-agent``` daemonset in ```system``` project is stuck in "updating" state forever.

Only the cattle-node-agent pod in etcd node gets upgraded to ```rancher/rancher-agent:v2.1.2-rc16```.
cattle-node-agent pod in one of the worker nodes is stuck in "removing" state and the cattle-node-agent pod in all other nodes are still in ```rancher/rancher-agent:v2.1.1```.

```
> kubectl get pods -n cattle-system
NAME                                    READY     STATUS        RESTARTS   AGE
cattle-cluster-agent-696cd5cbbb-v85kg   1/1       Running       0          17h
cattle-node-agent-4lk7v                 1/1       Running       0          17h
cattle-node-agent-5dv9f                 1/1       Running       1          17h
cattle-node-agent-5wtrt                 1/1       Running       1          17h
cattle-node-agent-dxtjm                 1/1       Running       0          17h
cattle-node-agent-h9qh2                 0/1       Terminating   1          17h
```

**Comment by jiaqiluo** [comment]
I met the similar problem on the cluster hosted on Azure after upgrading Rancher server from 2.1.1 to 2.1.2-rc16.

Steps:

1. Fresh install of 2.1.1
2. Add a cluster with 3 nodes, one role on each, choosing Azure as the infrastructure provider 
3. Create projects, namespace and deploy few workloads and ingress.
4. Upgrade rancher server to 2.1.2-rc16.

Results:

The cluster is active and functional, but `cattle-node-agent` daemonset in `system` project is stuck in `updating` state forever. Only one pod gets updated to  `rancher/rancher-agent:v2.1.2-rc16` 

<img width="1510" alt="screenshot 5" src="https://user-images.githubusercontent.com/6218999/49096770-7f1caf00-f228-11e8-88ad-008e79d7c5c1.png">

**Comment by sangeethah** [comment]
Able to get past the issue of cattle-node-agent daemonset stuck in "updating" state , by forcefully deleteing the pod that is stuck in "removing" state.

```kubectl delete pods <pod-name> --force --grace-period=0```

This resulted in this pod getting upgraded successfully and update of cattle-node-agent daemonset proceeded further.
In my case , I encountered the same issue with one more node getting stuck in "removing" . But once the workaround was applied ,  update of cattle-node-agent daemonset proceeded further and succeeded for all other nodes.

**Comment by alena1108** [comment]
https://github.com/kubernetes/kubernetes/issues/65879

**Comment by alena1108** [comment]
The issue is not new in 2.1.2; @sangeethah and @soumyalj reproduced it for 2.1.0-2.1.1 upgrade for rhel 7.5 clusters several times. Seems like it presents itself for rhel more frequently. 

The workaround is: forcefully remove `node-agent` pods stuck in Terminating state with `kubectl delete pods <podname> --force --grace-period=0`, and the node-agent daemonset upgrade will go through.

Moving the issue out to 2.2
