### ISSUE TITLE
Rancher renames primary container in deployment after edit

### ISSUE THREAD

**Issue by easybi-mv** [rancher/rancher#16725]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Apply deployment with kubectl and multiple containers. 
Name deployments differently than first container
Open edit deployment then first container in rancher (name of the containers is replaced by rancher) and click Upgrade

**Result:**
List of containers in pod show that the first one was renamed. 

**Other details that may be helpful:**
/

**Environment information**
- Rancher version (`rancher/rancher:stable` 2.1.1):
- Installation option (single install):

**Cluster information**
- Cluster type (Custom):
- Machine type (VM) 
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Docker (use `docker info`):
Docker 18.06

**Comment by loganhz** [comment]
Thanks for the report.
Fixed in https://github.com/rancher/rancher/issues/16143
