### ISSUE TITLE
Menus have 1px gap between navbar and menu list

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16738]
Version: master 2.2 (11/27/18

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Open any menu from the nav bar (global menu or security menu for example).
2. Notice that there is a 1px gap between the nav bar and the menu item list.
<img width="196" alt="menus_have_1px_gap" src="https://user-images.githubusercontent.com/45179589/49108072-76d26d00-f244-11e8-8d83-63a20a94de02.png">

**Result:**
1px gap between nav bar and menu list

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/2451

**Comment by davidnuzik** [comment]
Version: master 2.2 (11/30/18)
Confirmed fixed. Additionally tried to break things by changing browser window dimensions, etc and it still works.
