### ISSUE TITLE
DO cluster provisioning fails on master build

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#16739]
Rancher Version: Master 
root@soumyatestserver:~# sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rancher/rancher     master              7a2ec2a14308        14 hours ago        439.5 MB

Steps:
1. Create a cluster using Digital Ocean provider nodes
2. Cluster creation fails. 
The nodes are getting recreated as ssh fails .
Error message below:  
<img width="1302" alt="screen shot 2018-11-27 at 11 57 39 am" src="https://user-images.githubusercontent.com/18536626/49108368-e5abc800-f23c-11e8-9134-1621cac6c4b1.png">

**Comment by tfiduccia** [comment]
Happens with EC2 as well.  Not just a DO issue.  Looks like it's all of RKE.

**Comment by soumyalj** [comment]
Tested with master build from Nov 28. Created cluster using Digital Ocean nodes.
Cluster provisioning was successful.
