### ISSUE TITLE
Use description for roles in member screens

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16734]
Version - master 2.0 11/27

**Steps to reproduce (least amount of steps as possible):**
1.  Create a cluster or project role & add description
2.  go to Member screen for cluster or project
3.  Add member

**Result:**  Description for the new role always says "User defined role."  We should use the description for this instead.
![image](https://user-images.githubusercontent.com/11514927/49106174-ad59b900-f23f-11e8-9449-2f4519f8b9ab.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/11/18)
Confirmed fix. The description is now shown for any custom cluster/project roles when you add a cluster/project member. If you edit and remove the description or just don't have one we will go back to our default "User defined role." Halo testing was also done in this area.
Cluster:
![image](https://user-images.githubusercontent.com/45179589/49830169-9e016200-fd4d-11e8-84c2-c2af7f28020a.png)
Project:
![image](https://user-images.githubusercontent.com/45179589/49830188-af4a6e80-fd4d-11e8-936e-9ab83232e032.png)
