### ISSUE TITLE
Settings page uses odd color button

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16732]
Version: master 2.2 (11/27/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Go to the settings page. Observe the green colored "show cacerts" button. This color isn't used anywhere else for a button. A blue button was expected.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/2559

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/10/19)
Confirmed fix. Bot the "Show cacerts" and "Hide cacerts" buttons now use the more conventional blue colored button.
