### ISSUE TITLE
Support port ranges

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#1673]
`docker run` supports exposing ranges of ports `-p 1024-2048:1024-2048`. This is very useful for containers that manage VOIP/Web RTC connections which need to allocate arbitrary UDP ports. It would be nice if Rancher supported such assignments, but as of now the port forwards only accept single values.

Not sure if this should be handled on the container or load balancer layer. Probably the latter, but either would certainly do here.

**Comment by gregory** [comment]
:+1:  have the exact same scenario!

**Comment by gregory** [comment]
just figured out you guys might be interested by the fact there has been a [fix](https://github.com/docker/compose/issues/2160) for this but docker-compose client hasn't  been released yet.

Not sure which version of docker-compose rancher-compose is based on though...

**Comment by deniseschannon** [comment]
@gregory We're based on docker/libcompose, which is another implementation of docker-compose, but in Go. :)

**Comment by alena1108** [comment]
It should be fixed in both Rancher and rancher-compose @deniseschannon

**Comment by vincent99** [comment]
Just to clarify, Alena means support *needs to be* added to the cattle API, rancher-compose, and the rancher UI.

**Comment by alena1108** [comment]
@vincent99 thank you :) I meant exactly that

**Comment by blahRus** [comment]
+1

**Comment by cjellick** [comment]
@will-chan @deniseschannon I'm not going to be able to do this one for GA.
Per my convo with Will, I'm going to move it out.

**Comment by gregory** [comment]
The solution i ended up doing was to link net to host so that you wont have to write all the forwarding rules in iptable.

**Comment by alexishida** [comment]
+1

**Comment by gjongenelen** [comment]
Any news on this? I've got the same scenario where in need to define port 50000-50400 for PassiveFtp. Currently using network=host...

**Comment by cpoole** [comment]
would also love to see this. Is rancher-compose still using libcompose?

**Comment by cpoole** [comment]
cause without this my stack looks pretty comical 

![screen shot 2017-04-12 at 7 54 06 pm](https://cloud.githubusercontent.com/assets/5151386/24988295/e33fe0ee-1fb9-11e7-99d1-9af4e99293d6.png)

**Comment by misterkramer** [comment]
any update?

**Comment by zhuangsirui** [comment]
+1

**Comment by tomasvinduska** [comment]
Why is this not working when documentation says that rancher-compose.yml support docker-compose.yml?
Or how syntax shoud look like for this basic functionality?

**Comment by guilbill** [comment]
+1

**Comment by sliard** [comment]
Can't use rancher for my media server without port range :(
I need to open 2000 ports

**Comment by guilbill** [comment]
A workaround is to use the servicesPortRange (https://rancher.com/docs/rancher/v1.1/en/api/v1/api-resources/servicesPortRange/). But it would set a port range for the entire environment.
```
curl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
-X PUT \
-H 'Content-Type: application/json' \
-d '{
        "servicesPortRange": {
                "endPort": 25000,
                "startPort": 20000
        }
}' 'http://rancher-host/v2-beta/projects/environment_id'
```
Then when you expose a port, let docker chose it randomly, it would chose inside this range.
In my case it was close enough to what I wanted.

**Comment by tomasvinduska** [comment]
The lack of support from developers is iritating after 2 years still no suport for basic docker-compose.yml function

**Comment by guilbill** [comment]
FYI it's an issue in docker-compose to : https://github.com/docker/compose/issues/5230

**Comment by oesile** [comment]
So, Rancher does not support range of ports? no plans to support it?

**Comment by vincent99** [comment]
Probably not, given that 2.0 is based on Kubernetes and [they don't](https://github.com/kubernetes/kubernetes/issues/23864) support ranges either.

**Comment by sliard** [comment]
In my case, I use network mode "host" in compose file :
```
name:
  image: name:version
  net: "host"
```
It's not perfect but it's the only solution to deploy a media server with 2000 ports open.

**Comment by oesile** [comment]
@sliard, how do you do that? I tried  in a docker-compose file with the port range and network_mode: host but it doesn't work...

**Comment by sliard** [comment]
@oesile just add network_mode, remove port range declaration

**Comment by juanluisbaptiste** [comment]
This seems to have been fixed in docker-compose, the issue https://github.com/docker/compose/issues/5230 has been closed, but I still can't define an udp range with rancher-compose v0.12.5

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
