### ISSUE TITLE
Current Version

### ISSUE THREAD

**Issue by qrpike** [rancher/rancher#1674]
Could you please post the current version somewhere so I know when my server is out of date and I need to update it?

Thanks,

**Comment by vincent99** [comment]
Each version is tagged in this repo and pushed to DockerHub; "stable" ones are generally released once a week after one or more `-rcN` tags gave gone through testing starting Wednesdays.  Those are also announced on the [forum](http://forums.rancher.com/c/announcements).

Are you thinking of more like an API?

**Comment by deniseschannon** [comment]
I've also updated the README in Rancher to include the latest stable release.

**Comment by qrpike** [comment]
@deniseschannon Perfect! This makes it much easier for me (and others) to recognize when releases are made.
