### ISSUE TITLE
How do you version control Kubernetes configuration files while using Rancher?

### ISSUE THREAD

**Issue by JasonShin** [rancher/rancher#16741]
**What kind of request is this (question/bug/enhancement/feature request):**
Hi,

I am working with Rancher and I'd like to know how to version control Kuberentes configurations created by Rancher. We are currently using the database backup for the time being but version controlling the configs using Git would be much more ideal in our situation. 

1. Could you please tell me how to achieve it?
2. Is there a native support to version control the configs using Git?

**Comment by fabiorauber** [comment]
I was also wondering this myself.

**Comment by vincent99** [comment]
Deployments (the default kind of workload) automatically keep the last few revisions and can be rolled back when needed

Other than that, you either don't, or do it yourself and use the cli tools to apply changes to the cluster.

**Comment by deniseschannon** [comment]
If there are still questions, please open a new issue.

**Comment by GrabbenD** [comment]
> Deployments (the default kind of workload) automatically keep the last few revisions and can be rolled back when needed.
> 
> Other than that, you either don't, or do it yourself and use the cli tools to apply changes to the cluster.

Is this still up to date in 2024?
