### ISSUE TITLE
ssk keys not working after fresh cluster deployment

### ISSUE THREAD

**Issue by fosk06** [rancher/rancher#16747]
What kind of request is this (question/bug/enhancement/feature request): bug

Steps to reproduce (least amount of steps as possible): 
install a fresh cluster with Vsphere driver (version 6.0), rancher V2.1.1.
Set the cloud_provider options in the cluster file
Create a sandox cluster with one node with all roles.
Wait for the cluster is up and running, then download the keys of the node with the UI ( " Download Keys" menu).

then move to the folder with the key then try to ssh : 
ssh -i .id_rsa rancher@<NODE_IP> -v
same result with rancler cli  with : 
rancher ssh -l rancher sb1
same result with the user "root"

Result:
The ssh prompt ask for a password : 

OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to 151.80.10.74 [151.80.10.74] port 22.
debug1: Connection established.
debug1: identity file id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6
debug1: match: OpenSSH_7.6 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 151.80.10.74:22 as 'rancher'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:/Fy5o3hkeJXw7QApLUvS7CKEwEKIDIZ9IfNbBith1Hk
debug1: Host '151.80.10.74' is known and matches the ECDSA host key.
debug1: Found key in /Users/thomas/.ssh/known_hosts:23
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering RSA public key: id_rsa
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: password

Environment information
- Rancher version : 2.2.1
- Installation option (single install/HA): single

Cluster information
- Cluster type : created using Vsphere driver
- Machine type: VM
- Kubernetes version: v1.11.3-rancher1-1

**Comment by superseb** [comment]
Can you try `ssh -i .id_rsa docker@<NODE_IP>`

**Comment by fosk06** [comment]
great superseb, it worked with the user docker.
I did ssh -i id_rsa docker@<NODE_IP> and it logged me.
It's not written anywhere in the officials docs ( [here](https://rancher.com/docs/rancher/v2.x/en/faq/technical/), they say to use "rancher" user) , and i didn't find the solution in any issues.
You save my day.

**Comment by fosk06** [comment]
working with user docker. Would be great to update the [faq](https://rancher.com/docs/rancher/v2.x/en/faq/technical/)

**Comment by superseb** [comment]
Filed https://github.com/rancher/docs/issues/1006

**Comment by fosk06** [comment]
thanks a lot for you quick response :)
