### ISSUE TITLE
Ability to decouple hosted k8s clusters cloud providers keys

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16744]
Similar to decoupling keys for the node templates (https://github.com/rancher/rancher/issues/15696), we should do the similar thing for hosted k8s providers - EKS/AKS/GKE

**Comment by deniseschannon** [comment]
Closing this in favor of the refactored versions for EKS (available as of v2.5.0).

AKS and GKE are currently targeted for v2.5.7 (end of April).

The cloud credential separation is involved in these refactors.
