### ISSUE TITLE
Provide "Refresh" option/button for Custom Catalog in Catalogs page

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#16752]
rancher/rancher/v2.1.1

Adding a "Refresh" button on the Catalogs page next to each custom catalog item is very useful as it's contextual.

The current way of being able to Refresh the catalog only when the user is trying to Launch a Catalog App is quite not intuitive and not straightforward.

<img width="1472" alt="screen shot 2018-11-28 at 9 24 59 am" src="https://user-images.githubusercontent.com/19392926/49170029-0b45d980-f2f0-11e8-8ff3-81074cf2ab76.png">

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/49725008-ad2cd500-fca5-11e8-93eb-e99151228760.png)

It has been added in rancher/rancher:master

**Comment by leodotcloud** [comment]
Cool! Thanks for taking care of this.

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/18)
Enhancement has been validated. The refresh action is working as was tested in more detail in #16661
