### ISSUE TITLE
Failed to communicate with API server even when server available

### ISSUE THREAD

**Issue by pulse14** [rancher/rancher#16755]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
I have two servers
server1: rancher + one agent with etcd and panel role
server2: All roles

Then I kill server2. And I connect to rancher on server1

server1 should have everything required to work  but I have this error

**Result:**
```
This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.
Failed to communicate with API server: Get https://<server1ip>:6443/api/v1/componentstatuses?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM

**Comment by superseb** [comment]
This is expected as 2 etcd nodes gives you 0 fault tolerance. See https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/production/#count-of-etcd-nodes
