### ISSUE TITLE
support helm upgrade options with `--force` for immutable fields changes

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#16769]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Deploy a `docker-registry` app with service type set to `NodePort` from the catalog page.
2. Upgrade the app with changing the service type from `NodePort` to `ClusterIP` and it will report:
```
Failed to install app docker-registry. Error: UPGRADE FAILED: Service "docker-registry" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

**Result:**

Need to support helm upgrade for those immutable fields by setting an option with `--force`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master
- Installation option (single install/HA): single

Related Issues:
https://github.com/rancher/charts/issues/71
https://github.com/rancher/longhorn/issues/340

**Comment by loganhz** [comment]
@guangbochen Do we need an UI change for this?

**Comment by guangbochen** [comment]
created related UI issue - https://github.com/rancher/rancher/issues/17510

**Comment by rootwuj** [comment]
Verified with rancher/rancher:master 01/30

* Verified forced upgrades and rollbacks
* Verified that the app works after upgrade or rollback
* Verified that charts in public/private catalog
