### ISSUE TITLE
When creating GKS and AKS, expand the cluster options section

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16762]
Reference #16108 
Version: master 2.2 (11/28/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Review #16108 and notice we open cluster options for all RKEs
- Notice we do not do this, however, for GKS and AKS

**Result:**
Cluster options does not automatically open for GKS/AKS

**Comment by loganhz** [comment]
Only RKE clusters have the cluster options

**Comment by davidnuzik** [comment]
There actually are cluster options for AKS and GKS. For example try to create AKS cluster. You have to authenticate first. Once you put in your api keys and click button to authenticate you'll see the cluster options section. It does not auto-expand unlike the RKE options.

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/11/18)
Confirmed fixed. Cluster options now are automatically expanded for GKS and AKS (as well as other providers where the Cluster Options section is available).
