### ISSUE TITLE
[rancher/server] Unable to start rancher/server:v0.30.0

### ISSUE THREAD

**Issue by Mmdixon** [rancher/rancher#1676]
Commands were:
```
docker pull rancher/server:v0.30.0
docker run -d --name=rancher-server-test --restart=always -p 8080:8080 rancher/server:v0.30.0
```
under `docker ps` it container stays there with STATUS: `Restarting (0) 2 minutes ago` etc.
`docker logs rancher-server-test` give similar messages a few times:
```
150728 19:03:35 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150728 19:03:35 [Warning] option 'max_connections': unsigned value 10000000000000 adjusted to 100000
150728 19:03:35 [Warning] option 'max_binlog_size': unsigned value 10485760000000000000 adjusted to 1073741824
150728 19:03:35 [Note] /usr/sbin/mysqld (mysqld 5.5.43-0ubuntu0.14.04.1) starting as process 12 ...
s6-svscanctl: fatal: unable to control /service: supervisor not listening
150728 19:07:01 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150728 19:07:01 [Warning] option 'max_connections': unsigned value 100000000000000 adjusted to 100000
150728 19:07:01 [Warning] option 'max_binlog_size': unsigned value 12623879631452241920 adjusted to 1073741824
150728 19:07:01 [Note] /usr/sbin/mysqld (mysqld 5.5.43-0ubuntu0.14.04.1) starting as process 11 ...
s6-svscanctl: fatal: unable to control /service: supervisor not listening
```
Any advice?

**Comment by ibuildthecloud** [comment]
Can you share the output of `docker version; docker info`?

**Comment by Mmdixon** [comment]
docker version
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

docker info
```
Containers: 20
Images: 431
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 551
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 12
Total Memory: 31.39 GiB
WARNING: No swap limit support
```

**Comment by ibuildthecloud** [comment]
@Mmdixon Anything special about the setup of your ubuntu?  Ubuntu 14.04.2 LTS is our most popular installation base so its a bit odd to see it not even start

**Comment by cloudnautique** [comment]
@Mmdixon can you start the container like so:
`docker run -it -p 8080:8080 rancher/server:v0.30.0 bash`

That should place you on a command line. Then run `/usr/bin/s6-svscan /service`

In a separate terminal, get the ID of the container you just started... and run:
`docker exec -it <id> bash`

From that shell, can you get the log output from /var/log/mysql/error.log?

**Comment by Mmdixon** [comment]
The logs show that there was no space left on device. So checking the host machine, there was also no space left there, this was the issue.

Thanks for the help!

**Comment by sebmoule** [comment]
Hello,

I have the same problem.
I have make an inspect on the rancher-data container and it seams that my directory for that container is fill with 27go 

27G	/var/lib/docker/volumes/bd630902a87a0d1915d1804577d5acb4b335ff9f999db77a2d9cdf1f5a295759/

it seams that it is mysql binary logs that fill the space :+
-rw-rw---- 1 messagebus fuse 104878846 Sep 30 01:34 mysql-bin.000271
-rw-rw---- 1 messagebus fuse  71217152 Sep 30 15:25 mysql-bin.000272

I've got 272 files of each 100M...

Is that normal ? does rancher-server can free them by itself ?

thanks

**Comment by deniseschannon** [comment]
@sebmoule In our more recent versions, we've added some additional cleanup to help clean up the DBs. Have you tried installing the latest (v0.39.0)?

**Comment by sebmoule** [comment]
I've tried but with loading volume-from previous version and it says no space left to boot mysql...

Sébastien

**Comment by deniseschannon** [comment]
We'll need to investigate which table in your DB has grown too large. 

Can you exec into the container? `docker exec -it containerID bash`
Switch to MySQL `mysql`
Switch to Cattle DB `use cattle;`

Run query to look for biggest tables:
```
SELECT  concat(table_schema,'.',table_name),
    concat(round(table_rows/1000000,2),'M') rows,
    concat(round(data_length/(1024*1024),2),'MB') DATA,
    concat(round(index_length/(1024*1024),2),'MB') idx,
    concat(round((data_length+index_length)/(1024*1024),2),'MB') total_size,
    round(index_length/data_length,2) idxfrac
FROM information_schema.TABLES
WHERE table_schema = 'cattle'
ORDER BY data_length+index_length DESC LIMIT 10;
```

**Comment by cloudnautique** [comment]
@sebmoule if MySQL isn't running because of out of disk space, is there anything you can free up on the host?

if its a docker host you could try the usual.. `docker rmi $(docker images -aq -f 'dangling=true')`
Sometimes docker logs get really large.. if you go to /var/lib/docker/containers and do a `du -sh *`
If you find a large one, you can cd to the directory and `cat /dev/null > logfile` (This will erase the log completely but frees up space.) Or, any usual tricks to clean stuff up on a linux host :)

In v0.39.0 we set the log_expire_delay to 2 days and moved to file_per_table for innodb. So this shouldn't happen any more. 

Another approach would be to get a little bit of space freed up to start mysql, and manually clean up bin logs in mysql:

`docker run -it --volumes-from=<oldrancher> rancher/server:<old rancher version> bash`
`service mysql start`
`mysql`
`mysql> PURGE LOGS BEFORE 2015-09-30 00:00:00`
`service mysql stop`
`exit`

This approach might work a little better since you won't have rancher trying to run the migrations to the new version.

**Comment by sebmoule** [comment]
@deniseschannon it get your command 
```
+-------------------------------------+-------+-----------+----------+------------+---------+
| concat(table_schema,'.',table_name) | rows  | DATA      | idx      | total_size | idxfrac |
+-------------------------------------+-------+-----------+----------+------------+---------+
| cattle.process_execution            | 0.19M | 5352.02MB | 32.16MB  | 5384.17MB  |    0.01 |
| cattle.instance_label_map           | 0.91M | 125.67MB  | 215.58MB | 341.25MB   |    1.72 |
| cattle.instance                     | 0.13M | 147.72MB  | 48.72MB  | 196.44MB   |    0.33 |
| cattle.label                        | 0.24M | 52.59MB   | 86.08MB  | 138.67MB   |    1.64 |
| cattle.image                        | 0.13M | 60.59MB   | 37.13MB  | 97.72MB    |    0.61 |
| cattle.volume                       | 0.12M | 25.55MB   | 46.19MB  | 71.73MB    |    1.81 |
| cattle.nic                          | 0.12M | 18.55MB   | 45.14MB  | 63.69MB    |    2.43 |
| cattle.service_expose_map           | 0.13M | 21.55MB   | 35.09MB  | 56.64MB    |    1.63 |
| cattle.process_instance             | 0.08M | 36.06MB   | 18.09MB  | 54.16MB    |    0.50 |
| cattle.instance_link                | 0.07M | 21.53MB   | 26.59MB  | 48.13MB    |    1.24 |
+-------------------------------------+-------+-----------+----------+------------+---------+
10 rows in set (9.11 sec)
```

@cloudnautique,

here is my space usage
root@usso:/var/lib/docker# du -hs *
2.5G	aufs
608K	containers
5.9M	graph
12K	linkgraph.db
4.0K	repositories-aufs
4.0K	tmp
8.0K	trust
37G	volumes

so the problem comes from volumes

In mysql i uses : 
`PURGE BINARY LOGS BEFORE '2015-09-30 00:00:00';`

That frees up instantenely 31G :)

I still don't understant why the mysql binary log are so huge because my stack seems very simple..

Thanks for help

**Comment by cloudnautique** [comment]
The process instance table has a record of every event, and until a few releases ago we were not pruning it. It is now removing records on a rolling 24 Hr interval. In v0.39.0 we moved the bin log rotation down to 2 days. Hopefully this will help avoid the situation you ran into in the future.

**Comment by baillieny** [comment]
We are using an external mysql DB but are still seeing some storage being used in /var/lib/docker/volumes
Rancher (v 1.1.3) is the only container running on the docker host

hundreds of folders similar to this
12K     volumes/eb39f16ac0991810eefeb6cd04ec982ae7c100e11ee0404d33af258308919626/_data/DATA/community/templates/gocd-server/0

Containing docker and rancher compose.yml files. 
Is there any way to disable storing these to disk or calculate how much storage is likely to be used so we don't run out of disk space?

Thanks for your help.

**Comment by vincent99** [comment]
That would be the cloned catalogs for whichever catalogs are enabled, typically rancher/rancher-catalog and community-catalog.  There would also be machine drivers and a few other things but all of that is order of megabytes.  The main large thing is probably log files.

**Comment by kbroughton** [comment]
I'm getting the same 
s6-svscanctl: fatal: unable to control /service: supervisor not listening

but in my case, i noticed that the ownership of /service is messed up.  On a working rancher it is root:root.  on my borked server it is 
root@d04aeac696f8:/# ls -alh /service/
total 20K
drwxr-xr-x  8 1944522877 499 4.0K Dec 16 02:21 .
drwxr-xr-x 85 1944522877 499 4.0K Dec 20 14:42 ..
drwxrwxr-x  4 1944522877 499 4.0K Dec 16 16:45 cattle
drwxrwxr-x  4 1944522877 499 4.0K Dec 16 16:45 mysql
drwxrwxr-x  2 1944522877 499 4.0K Dec 16 16:45 .s6-svscan

I'm controlling it with docker-compose and a --force-recreate fixed it.

**Comment by davide** [comment]
@cloudnautique thanks for the tip about the docker logs! That alone was enough to clear 12G.

After freeing up disk space and launching rancher this message still shows up in the logs:
s6-svscanctl: fatal: unable to control /service: supervisor not listening

Any hints?

**Comment by davide** [comment]
Same symptom different cause: mysql was crashing while trying to recover the InnoDB database and failing.

**Comment by Sebisnow** [comment]
@davide how did you recover from your issue? Or rather how did you make mysql recover InnoDB?

**Comment by davide** [comment]
@Sebisnow can't really recall but I'm running a MariaBD Galera cluster (3 nodes) and probably had a good one in the mix. 😃
