### ISSUE TITLE
Rancher disconnected from rke cluster after (only) node reboot

### ISSUE THREAD

**Issue by rbq** [rancher/rancher#16776]
Hi there! This is a question about an issue I encountered with my specific rke/Rancher setup.

So I started a single-host cluster using rke (mostly defaults, just increased max-pods, disabled ingress). Since the add-on installation of Rancher seems to be deprecated, I manually started a Rancher container on a separate host (default self-signed certificate), added the cluster and used the setup successfully for a couple of days. In-between I re-ran rke a couple of times to experiment with installing Longhorn, Træfik and Nvidia Device Plugin via the add-ons mechanism.

But only after a reboot of the (only) node for a kernel update, the cluster suddenly didn't want to talk to Rancher any more. The UI says:

> Failed to communicate with API server: Get https://10.43.0.1:443/api/v1/componentstatuses?timeout=30s: waiting for cluster agent to connect

It might be a certificate issue since the Rancher API is definitely reachable via curl:

```
$ kubectl logs -f -n cattle-system cattle-cluster-agent-[…]
[…]
ERROR: https://[my-rancher]/ping is not accessible (Failed to connect to [my-rancher] port 443: Connection refused)

$ ssh [my-node] curl https://[my-rancher]/ping
curl: (60) SSL certificate problem: unable to get local issuer certificate

$ ssh [my-node] curl -k https://[my-rancher]/ping
pong
```

And this is where I'm stuck, having no idea how Rancher deploys its generated CA to the nodes during setup, where they should be stored and how to fix this. Is there any built-in way to re-add nodes/clusters?

Versions:
* Host OS (node/Rancher): Ubuntu 18.04.1 LTS
* Docker: CE 18.09
* Kubernetes: v1.12.1-rancher1-1
* rke: first 0.1.11, re-ran with 0.1.12
* Rancher: 2.1.1 (UI 2.1.4)

**Comment by rbq** [comment]
Edit: I guess my problem is actually caused by me changing the host name of my Rancher server at some point. And the settings seem to be contained in the K8 metadata of the agent deployment? Anyway, I tried to revert this by patching the node agent (`kubectl edit -n cattle-system deployments/cattle-node-agent-[…]`) and switching back to the previous host name, but that didn't solve it.

**Comment by superseb** [comment]
OK thanks for reporting that, changing the server-url/certificates are not propagated to the agents as of today, see https://github.com/rancher/rancher/issues/14731. Let me know if that doesn't solve the issue.

**Comment by rbq** [comment]
I think that certificates might have not be my problem after all. I removed and reinstalled the whole cluster as well as Docker (nvidia-docker2 actually) a couple of times. I also tried to install from Rancher instead of standalone RKE. The result is always the same. Something is weird tough:

My **cattle-cluster-agent** throws the errors I mentioned:
```
# INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local mydomain.tld options ndots:5
# ERROR: https://k8.mydomain.tld/ping is not accessible (Failed to connect to k8.mydomain.tld port 443: Connection refused)
```

But meanwhile **cattle-node-agent** successfully (!) connects to the same endpoint:
```
# INFO: Using resolv.conf: nameserver 192.168.2.1 search mydomain.tld
# INFO: https://k8.mydomain.tld/ping is accessible
# time="2018-12-07T13:25:03Z" level=info msg="Connecting to wss://k8.mydomain.tld/v3/connect with token blahblahblahblah"
# time="2018-12-07T13:25:03Z" level=info msg="Connecting to proxy" url="wss://k8.mydomain.tld/v3/connect"
```

So, both of these guys run with different DNS settings and one of them can't reach my Rancher installation. Where do the different DNS settings come from? Is that something I can influence?
