### ISSUE TITLE
Support Proxy protocol to allow Rancher to run behind ELB

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1677]
In order to support putting Rancher behind an ELB, we must support the Proxy protocol.

This is because ELB does not support websockets when ran in http(s) mode.

Here's a link to the protocol: http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

**Comment by cjellick** [comment]
Note that this is different than #1554. That issue is dealing with the Rancher LB service, not the configuration of Rancher itself.

**Comment by ebr** [comment]
+1 for this

**Comment by aruneli** [comment]
We support proxy protocol now and Rancher behind ELB supporting only proxy protocol would work fine now.
