### ISSUE TITLE
When one node restart，Cluster's CPU Cores and RAM GiB is not correct.

### ISSUE THREAD

**Issue by myaniu** [rancher/rancher#16771]
When I shutdown A node.
after 1 day ,I start A node.
Nodes number is correct.
But CPU Cores and RAM GiB is not correct , miss A node's CPU  and RAM 。
When I click Cluster's name, go to Nodes page, A node is included and it's CPU  and RAM is correct
this Cluster is imported from exist kubernetes.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`global-admin.clusters.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
