### ISSUE TITLE
Import existing cluster to another rancher can't see any system workloads, load balancing, etc.

### ISSUE THREAD

**Issue by sdjnmxd** [rancher/rancher#16773]
First, I have deployed two ranchers, 
one is a cluster deployed with rke **(ui-endpoint: `prod-rancher.s.example.com`, name: `prod-rancher`)**.
and the other is installed by single node mode **(ui-endpoint: `rancher.example.com`)**.

Then I want to manage the rancher cluster of `prod-rancher` through the ui of `rancher.example.com`.

I did the following:
1. open `rancher.example.com`, There are no clusters at this time.
2. "Add Cluster" by use "Import existing cluster", then i got kubectl command like `kubectl apply -f https://rancher.example.com/v3/import/[some hash].yaml`
3. exec command at `prod-rancher` cluster, It looks like everything is ok
![image](https://user-images.githubusercontent.com/6388562/49205000-94403c00-f3e8-11e8-8dde-3903ba41c9c9.png)
4. open `rancher.example.com`, there now can see `prod-rancher` cluster in the list
5. but I found the inconsistency seen in `prod-rancher.s.example.com` when looking at the `prod-rancher` cluster information at `rancher.example.com`
![image](https://user-images.githubusercontent.com/6388562/49205623-8095d500-f3ea-11e8-9a80-7c08c15a391f.png)
![image](https://user-images.githubusercontent.com/6388562/49205592-68be5100-f3ea-11e8-9abb-e6d2dd992c9b.png)

Is it something I am having? Or is my idea incorrect? (I want to manage the rancher cluster of multiple environments through a single-node rancher-ui deployment)

thanks :D

**Environment information**
- Rancher version
  - `rancher.example.com`: v2.1.1
  - `prod-rancher.s.example.com`: v2.1.2

- Installation option (single install/HA):
  - `rancher.example.com`: Single Node
  - `prod-rancher.s.example.com`: HA with rke

**Comment by huegelc** [comment]
Same issue with rancher 2.2.8

**Comment by MrAmbiG** [comment]
Did anybody solve this ? @sdjnmxd

**Comment by Repooc** [comment]
Would love to hear how to solve this as well.
