### ISSUE TITLE
When Lb capability is disabled for the cluster, we still see Layer4-Load Balancer being presented as option for port Mapping when creating workloads.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16784]
Rancher server version - Build from master Nov 29

Steps to reproduce the problem:
Create a RKE cluster (DO/EC2).
"loadBalancerCapabilities" is disable for this cluster.

```
"loadBalancerCapabilities": {
"enabled": false,
"healthCheckSupported": false,
"type": "/v3/schemas/loadBalancerCapabilities"
}
```
When Lb capability is disabled for the cluster, we still see Layer4-Load Balancer being presented as option for port Mapping when creating workloads.

<img width="1280" alt="screen shot 2018-11-29 at 1 26 54 pm" src="https://user-images.githubusercontent.com/4266958/49253018-779d0780-f3da-11e8-80f7-25014ff32447.png">

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/12/18)
Confirmed fixed. 1) Confirm the cluster API reports that ```"loadBalancerCapabilities": {
"enabled": false, ...```
2) Confirm that in the UI we cannot pick L4 LB when deploying a workload (port mapping). Screenshot:
![image](https://user-images.githubusercontent.com/45179589/49958755-04f75600-fec9-11e8-8b24-75ff3fdd80ef.png)
