### ISSUE TITLE
Consolidate rancher-agent logs

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1678]
Curently for rancher-agent, our logs are split between the docker logs for the container and /var/logs/rancher/agent.log.

This leads to confusion and difficulty when getting logs from customers. We should consolidate into a single log file.

This could potentially make the docker logs too chatty, so maybe the request/response json event logs could continue to go to a file inside of the container.

cc @ibuildthecloud

**Comment by sangeethah** [comment]
I have a similar issue to track some log related enhancements - #199

**Comment by will-chan** [comment]
Tracked as part of #71.
