### ISSUE TITLE
Update the recommended Docker version

### ISSUE THREAD

**Issue by dhaus97** [rancher/rancher#16780]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

Update the recommended Docker version for Kubernetes version 1.12 according to the Changelogs found on the Kubernetes GitHub Repo.
[Link](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#external-dependencies)

Current supported / recommended Versions are: 17.03.2

Expected versions according to Kubernetes: 17.03, 17.06, 17.09, 18.06.

**Comment by superseb** [comment]
Its updated for k8s 1.12 and thats experimental in Rancher currently. It will be updated when its officially supported, see https://github.com/rancher/rancher/issues/16261
