### ISSUE TITLE
With “customDefaultBackend”: false, “Use as the default backend” option in Ingress page is not disabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16783]
Rancher server version - Build from master Nov 29

Steps to reproduce the problem:
Create a RKE cluster (DO/EC2).
```customDefaultBackend ``` is set to ```False``` for the cluster.
 ```
"ingressCapabilities": [
{
"customDefaultBackend": false,
"ingressProvider": "Nginx",
"type": "/v3/schemas/ingressCapabilities"
}
```
When trying to add Ingress , “Use as the default backend” option in still enabled.
<img width="1286" alt="screen shot 2018-11-29 at 11 24 55 am" src="https://user-images.githubusercontent.com/4266958/49252462-fabd5e00-f3d8-11e8-83ac-cd766d1b39b5.png">

Expected behavior:
 “Use as the default backend” option should be disabled in this case.

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/12/18)
Confirmed fixed. 1) confirmed cluster API indicates ```"ingressCapabilities": [
{
"customDefaultBackend": false,
...``` 2) create an ingress and notice the UI now disables this radio button and mentions that the "Ingress controller does not support default backend"
screenshot:
![image](https://user-images.githubusercontent.com/45179589/49958390-f52b4200-fec7-11e8-85d2-c3a71cef4f1c.png)
