### ISSUE TITLE
Changes made to "Node Port Range" as part of editing cluster is not reflected in the capabilities field.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16785]
Rancher server version - Build from master - Nov 29

Steps to reproduce the problem:

Create a cluster without changing the defaults for "Node Port Range" .
Once the cluster is provisioned successfully , edit the cluster and change the values for  "Node Port Range" .
Wait for the cluster to become "active".

"Node Port Range" in "Capabilities" field does not reflected the updated values.

Note - ""serviceNodePortRange" in kubeApi field gets updated as expected in ```rancherKubernetesEngineConfig```.

**Comment by davidnuzik** [comment]
Note to self: UI needs to be tested in this area (see #15105)

**Comment by cjellick** [comment]
we can address this in a maintenance release

**Comment by soumyalj** [comment]
Reproduced the issue with Rancher v2.2.2. 
Created a DO cluster. 
Edited the cluster and changed the default values of NodePortRange to `30000-32100`.
"Node Port Range" in "Capabilities" field did not reflect the updated values. It showed the default values as below:
```
capabilities": {
"ingressCapabilities": [
{
"customDefaultBackend": false,
"ingressProvider": "Nginx",
"type": "/v3/schemas/ingressCapabilities"
}
],
"loadBalancerCapabilities": {
"enabled": false,
"healthCheckSupported": false,
"type": "/v3/schemas/loadBalancerCapabilities"
},
"nodePoolScalingSupported": true,
"nodePortRange": "30000-32767",
"type": "/v3/schemas/capabilities"
},
``` 

Tested with master build from June 11. 
Created a DO cluster . Edited the cluster and changed the default values of NodePortRange to `30000-32000`. After cluster update, Capabilities field got updated and reflected the NodePortRange to `30000-32000`. 
```
"capabilities": {

    "ingressCapabilities": [
        {
            "customDefaultBackend": false,
            "ingressProvider": "Nginx",
            "type": "/v3/schemas/ingressCapabilities"
        }
    ],
    "loadBalancerCapabilities": {
        "healthCheckSupported": false,
        "type": "/v3/schemas/loadBalancerCapabilities"
    },
    "nodePoolScalingSupported": true,
    "nodePortRange": "30000-32000",
    "type": "/v3/schemas/capabilities"

},

```


KubeApi field in rancherKubernetesEngineConfig also reflected the serviceNodePortRange correctly as below:
```
kubeApi": {

    "alwaysPullImages": false,
    "podSecurityPolicy": false,
    "serviceNodePortRange": "30000-32000",
    "type": "/v3/schemas/kubeAPIService"

},



```
