### ISSUE TITLE
New global menu does not work with small browser window (hamburger menu)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16794]
Version: master 2.2 (11/30/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Shrink the browser window down so that we switch to our mobile menu (hamburger menu)
- [ ] Try to use the global menu and notice it doesn't work. If you try to hover over Global it glitches out like shown below in the screenshot.
![image](https://user-images.githubusercontent.com/45179589/49309561-dde85f80-f498-11e8-862b-55f857b04d62.png)
- [ ] Also notice that as you mouse over the various menu items in the hamburger menu they change vertical size and will flash on the screen if your cursor is between them.

**Result:**
Global menu does not work and hamburger menu has issues.

**Comment by lvuch** [comment]
Since some of the issue is that this is written on with js (dropdowns only are written into the DOM on hover) I'll need help @vincent99

**Comment by NerdyShawn** [comment]
Still an issue for me on Rancher 2.3.1 coming from Android Chrome or iOS Safari.  essentially cannot click on all menu items on a mobile device either requesting mobile or desktop site. Is there something I have to do on my client side to resolve or server-side?

**Comment by hameno** [comment]
Yes, still broken.
