### ISSUE TITLE
UI: Decouple node template cloud provider keys

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16796]
This issue is to track the UI component for node template key decoupling. Changes:

* Cloud provider key would be stored in its own CRD now
* The CRD reference would be passed on the node template creation/update - instead of user entering the credentials on create/update

Backend is tracked in https://github.com/rancher/rancher/issues/15696

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/12/19)
Confirmed new feature. 

Summary: This adds cloudcredentials and decouples the cloud provider keys (EC2, Azure, DigitalOcean, vSphere) from node templates. In the UI now you essentially are prompted for your cloudcredential entry. This allows you to re-use your api keys/secrets etc for each provider so you do not have to re-type this each time for each node template. Once you have created one you will be able to pick it from a drop-down menu each time you create a new node template.
This also adds a Cloud Keys page to the Security menu. This was also validated (create, delete, view in API, etc).

Screenshot of UI prompting us for cloudcredential upon node template creation:
![image](https://user-images.githubusercontent.com/45179589/52678462-fb04ca00-2eee-11e9-80d8-91992482ecdb.png)

Screenshot of the new Cloud Keys page:
![image](https://user-images.githubusercontent.com/45179589/52678572-5fc02480-2eef-11e9-9a4d-177c9fce5433.png)


Validated HTTP/API. When I create new cloudcredential entries http req payload and response looks correct. API looks correct. When I create clusters now I can see my cloud credentialid and node template being used. ("cloudCredentialId":"cattle-global-data:davidtest" for example is seen upon cluster creation in req payload). Tested both by creating new cloudkeys on the fly when creating a new cluster and via the Cloud Keys page. Tested creation/deletion. Smoke tested these areas.

A few issues were identified by the QA team and entered today. For example this does not seem to be working with Azure and you can delete the cloudcredentials even if associated with node templates (at which point these node templates are still usable and will fail in provisioning a cluster).

Further testing in this area will continue.
