### ISSUE TITLE
UI: etcd backup to S3 for RKE clusters

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16797]
This ticket is to track UI support for etcd backup to S3 and restoring rke clusters from the backup

Backend work is tracked in https://github.com/rancher/rancher/issues/13688 and https://github.com/rancher/rke/issues/616

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/30/19)
Confirmed feature. I tested mainly from the UI perspective as the backend QA team is already testing s3/local back up in further detail. I validated HTTP/API and basic functionality. The UI nicely informs you that the backup is complete and I successfully was able to do an s3 and local backup and restore without any issues. From the UI I tried picking various etcd backups as well to ensure I can pick numerous and I performed general smoke and halo testing in this area.
