### ISSUE TITLE
support no auth with rancher-compose/api

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#1680]
I am not sure if this should reside in the rancher-compose repo.

If I stand up a test environment such as using https://github.com/flaccid/rancher-test-farm I want to be able to run up a stack without creating an API key pair.

Running rancher-compose returns:

```
INFO[0000] Creating environment countdown-demo
ERRO[0000] Failed to open project countdown-demo: Resource type [environment] is not creatable
2015/07/29 18:57:31 Failed to read project: Resource type [environment] is not creatable
```

If I create a keypair and use it with the command it works normally. For easy test purposes such as integration testing, CI builds etc. not needing auth is useful, but if it should be mandated I just need the easiest way to generate a keypair using curl (I expect thats fairly trivial).

The goal of rancher-test-farm is to have an easy way to spin up rancher envs and then stacks and do some basic client-side tests after to make sure the networking is intact to server applications. Once that is going, it will be easier to spot test new releases before upgrading other rancher envs.

**Comment by deniseschannon** [comment]
Rancher Compose issues can be filed here. 

The API key pair is required for rancher-compose as it defines what environment (with reference to the UI in the upper right corner) to deploy the services. Even though the environment is called "Default", there is no actual default environment in Rancher, so you'd need the api key pair to pick the environment. 

Please note that "environment/project" in rancher-compose refer to our API (and do not match the UI). 

As for the curl command, 
```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{}' \
'http://localhost:8080/v1/projects/1a5/apikeys'
```
This will need the context of a project (API term), but the project that starts with Rancher on a fresh install will always be 1a5.

If auth is off, you don't need the `-u`.

**Comment by flaccid** [comment]
Great thanks very much @deniseschannon, it works a treat (https://github.com/flaccid/rancher-test-farm/blob/master/Vagrantfile#L79-L81). Maybe consider adding a lit bit of doc in respect to the API key pair relationship to environments and its need with rancher-compose, but its kind of minor in the scheme of things.

**Comment by ibuildthecloud** [comment]
@flaccid This a bit of a hack because you are hard coding an ID, but the below will work for no-auth with rancher-compose

```
export RANCHER_URL=http://localhost:8080/v1/projects/1a5/schemas
rancher-compose up
```

You don't have to set an access key and secret key if you put the correct project id (which is called environment in the UI).  As @deniseschannon pointed out the "Default" environment will always be `1a5` on a fresh install.  If you didn't want to hard code the ID the small curl/jq command below will find the ID of the environment named "Default"

    curl -s 'http://localhost:8080/v1/projects?name=Default' | jq -r .data[0].i

**Comment by flaccid** [comment]
Most appreciated, thank you @ibuildthecloud.

**Comment by dx9** [comment]
Just wanted to say I found this useful. Would be nice if rancher compose just works when auth is off. Default to default or something.

**Comment by jmreicha** [comment]
Another vote for making rancher-compose work when auth is turned off.
