### ISSUE TITLE
Certificate rotations in Rancher seem to be getting stuck to k8s/tls

### ISSUE THREAD

**Issue by ajacques** [rancher/rancher#16808]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
I created a certificate in the Rancher UI scoped to all namespaces. Before expiring, an automatic script renewed the certificate from Let's Encrypt and used the Rancher API to update the certificate. The Rancher API showed the updated certificate version, but the certificate did not appear to be updated across any of the namespaces in the k8s/tls record. Even when manually updating the certificate using the UI, it won't update the k8s tls object.

**Result:**
Rancher API Output:
```json
{
"algorithm": "RSA",
"annotations": {
"example.com": "30",
"lifecycle.cattle.io/create.secretsController_c-5spdj": "true"
},
"baseType": "secret",
"certFingerprint": "AD:A5:[...]",
"certs": "-----BEGIN CERTIFICATE----- <--- Certificate Version A --> [...]=\n-----END CERTIFICATE-----",
"cn": "a.example.com",
"created": "2018-07-13T16:31:04Z",
"createdTS": 1531499464000,
"creatorId": "user-tb6j6",
"expiresAt": "2019-01-27T00:00:00Z",
"id": "project-cqcq5:example",
"issuedAt": "2018-10-29T00:00:00Z",
"issuer": "Let's Encrypt Authority X3",
"keySize": "256",
"links": {
"remove": "…/v3/project/c-5spdj:project-cqcq5/certificates/project-cqcq5:example",
"self": "…/v3/project/c-5spdj:project-cqcq5/certificates/project-cqcq5:example",
"update": "…/v3/project/c-5spdj:project-cqcq5/certificates/project-cqcq5:example"
},
"name": "example",
"namespaceId": null,
"projectId": "c-5spdj:project-cqcq5",
"serialNumber": "3218167[...]",
"subjectAlternativeNames": [
"a.example.com",
"b.example.com"
],
"type": "certificate",
"uuid": "231108c9-86ba-11e8-a3a7-0242ac110004",
"version": "3"
}
```

kubectl for default/example shows:
```
> kubectl get secret example -o yaml
apiVersion: v1
data:
  tls.crt: [Not Correct Certificate Version. PEM does not match Rancher record]
  tls.key: [removed]
kind: Secret
metadata:
  annotations:
    example.com: "30"
    field.cattle.io/algorithm: RSA
    field.cattle.io/certFingerprint: E8:5F:[...]
    field.cattle.io/cn: a.example.com
    field.cattle.io/creatorId: user-tb6j6
    field.cattle.io/expiresAt: 2018-11-29T00:00:00Z
    field.cattle.io/issuedAt: 2018-08-31T00:00:00Z
    field.cattle.io/issuer: Let's Encrypt Authority X3
    field.cattle.io/keySize: "256"
    field.cattle.io/projectId: c-5spdj:project-cqcq5
    field.cattle.io/serialNumber: "30891...."
    field.cattle.io/subjectAlternativeNames: b.example.com
    field.cattle.io/version: "3"
    lifecycle.cattle.io/create.secretsController_c-5spdj: "true"
    secret.user.cattle.io/secret: "true"
  creationTimestamp: 2018-07-13T16:31:04Z
  name: example
  namespace: default
  resourceVersion: "6306605"
  selfLink: /api/v1/namespaces/default/secrets/example
  uid: 234fe9ac-86ba-11e8-821f-0025907b44b8
type: kubernetes.io/tls
```

From what I can tell, the `kubernetes.io/tls` object does not appear to be updated to match what Rancher knows about. The `field.cattle.io/version: 3` does match, but `serialNumber, expiresAt, issuedAt, certFingerprint` annotations along with the `tls.crt` do not match what the Rancher API shows.

**Other details that may be helpful:**
Attempting to update the certificate in the UI with the same certificate, does not fix the issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.1
- Installation option (single install/HA): Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Self-hosted single node cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 109
 Running: 101
 Paused: 0
 Stopped: 8
Images: 55
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1488
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-33-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.65GiB
Name: srv1.example.com
ID: [...]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: [user]
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`authenticated.project.certificates.index`|

**Comment by 3pns** [comment]
same probleme here :
- I wanted to delete a certificate in the UI, impossible to delete it with the UI. I delete it successfully with kubectl ( I checked with kubectl get secret that the cert was properly deleted afterward ). After that the deleted certificate still shows up in the UI.
- Another certificated I wanted to update, After I added the new cert and RSA private key, the UI show the certificate was properly updated, the expired date is correct. However the old certificate is still being served by my apps. I check with kubectl and it turns out the rancher did not updated the certificate, the AGE date correspond to the old certificate secret

**Comment by 3pns** [comment]
So I created the certificate secret manually using
  `kubectl create secret tls`
The new certificate was properly created as shown with kubectl, looking at rancher UI I noticed that :
- the bugged certificate are shown in "All" namespace
- the new manually created certificate is inside the "default" namespace

I think (to be confirmed) in the new kubernetes version as I just migrated my kubernetes to 1.12.3 don't support secrets including kubernetes.io/tls without any namespace since they are now created in the default namespace, thus the old secret still in "All" are in some kind of broken state.

It is impossible to get a certificate from the default namespace from another namespace

I recreated the certificate with the correct namespace and it works now.
