### ISSUE TITLE
Better support for DigitalOcean when creating cluster.

### ISSUE THREAD

**Issue by shinebayar-g** [rancher/rancher#16812]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

![image](https://user-images.githubusercontent.com/3091558/49352794-dd4c0500-f6f4-11e8-999b-d0a0560eca9e.png)

Digital Ocean provides multiple types of specs for their servers.

![image](https://user-images.githubusercontent.com/3091558/49352689-37989600-f6f4-11e8-8d4b-158b44f67f91.png)

This is the screenshot of when user creates DigitalOcean cluster. As you're seeing on the picture, it's hard to tell which is which. If it's possible, please modify this page little bit for better user experience.

Bonus: Also DigitalOcean now has **Projects** option. When creating new DO cluster by rancher UI all nodes goes into default project. Then I move them to another project using DO control panel.

**UPDATE:** Support DigitalOcean created kubernetes cluster.
Digital Ocean released their own version of Kubernetes. If it's possible please support DO version of kubernetes. If it's not possible yet, at least take a look at their **Block Storage** for volume class. (It's equivalent of Google persistent disk) Persistent volume class is much needed feature for DO users.

Kubernetes 
https://www.digitalocean.com/docs/kubernetes/how-to/add-persistent-storage/

**Comment by shinebayar-g** [comment]
Hey @loganhz thank you for looking up this issue, I've just updated the thread for volume storage issue. Could you take a look at it?

**Comment by loganhz** [comment]
Hi @shinebayar-g 

> Digital Ocean provides multiple types of specs for their servers.

I can do this as it's just some UI changes.

> Bonus: Also DigitalOcean now has Projects option.

We are using [rancher/machine](https://github.com/rancher/machine) a fork of docker/machine to provision DO nodes. But project doesn't support in docker/machine yet. Please submit a new issue if you would like us to support it. Maybe you could submit PRs to `docker/machine` then we can use it in Rancher?

> Support DigitalOcean created kubernetes cluster.

Please submit a new issue for supporting DO k8s cluster.
Rancher supports pluggable cluster driver in 2.2. 
Maybe you could submit a PR to support DO hosted k8s cluster?

https://github.com/rancher/kontainer-engine 
https://github.com/rancher/kontainer-engine-example-driver

I guess you could create a DO k8s cluster and import it into rancher. Then the storage class will be automatically in your cluster.

Or maybe your can try this ? https://github.com/digitalocean/digitalocean-cloud-controller-manager

**Comment by shinebayar-g** [comment]
Thanks for an update.

**Comment by shinebayar-g** [comment]
Update,

> I guess you could create a DO k8s cluster and import it into rancher. Then the storage class will be automatically in your cluster.

I guess In that case rancher doesn't recognize volume class and import it to UI. But it may work when deploying using yaml files.
