### ISSUE TITLE
Member list is cutting off on screen

### ISSUE THREAD

**Issue by se-achiu** [rancher/rancher#16818]
*Describe your issue here*
When configuring SSO with Ping, the list of groups are being cut off, you can't really see the whole group name for each.  this also applied on add cluster member.

![image](https://user-images.githubusercontent.com/44265811/49389531-8fcf9800-f6f4-11e8-81d3-80518d7102a0.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`authenticated.cluster.security.members.new`|

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/7/19)
There is now a horizontal scroll bar for situations where there is very long user or group names.
![image](https://user-images.githubusercontent.com/45179589/50798804-d9cd1000-1296-11e9-9b7f-e92f09e36b80.png)
