### ISSUE TITLE
/v3/clusters doesn't return kontainer engine config field but /v3/clusters/c-${id} does

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16813]
We have integrated Aliyun/Tencent/Huawei hosted k8s in Rancher based on Kontainer engine.

The newly created cluster shows as `Imported` in Rancher UI.

`/v3/clusters` never returns the config for `myclusterEngineConfig`. Only `/v3/clusters/c-${id}` returns the config.

However, Rancher UI is using `/v3/clusters` to get the cluster objects. So UI never know what the engine config is. 

`/v3/clusters`
![image](https://user-images.githubusercontent.com/21168270/49356040-3754c680-f705-11e8-9910-64ea584500b0.png)

`/v3/clusters/c-${id}`
![image](https://user-images.githubusercontent.com/21168270/49356132-9e727b00-f705-11e8-8997-7f0dd05239f9.png)

**Comment by loganhz** [comment]
Not only `/v3/clusters` API, we should make sure the correct cluster obj will be sent to UI via websocket.

**Comment by loganhz** [comment]
Monitoring feature is also blocked by this issue as it doesn't return `actions` field via `/v3/clusters/`

**Comment by cjellick** [comment]
The actions are not being returned because of a bug in the monitoring code here:
https://github.com/rancher/rancher/pull/16777/files#diff-cfb20222110d5d52a85bdbfe032e323cR21

The formatter is called on list requests as well, so that line is always erroring out on list requests because there is no ID on the request @orangedeng @loganhz

**Comment by loganhz** [comment]
Thanks！

**Comment by cjellick** [comment]
you can get the ID from `resource` parameter passed into that method

**Comment by rootwuj** [comment]
Version -2.2 master 12/05
Verified fixed
