### ISSUE TITLE
Error while adding aws esb to a container on kubernetes

### ISSUE THREAD

**Issue by smetal1** [rancher/rancher#16811]
I am getting the following error while adding esb to a conatiner on kubernetes:

Error from server (Forbidden): error when creating "redis-pv-ebs.yml": persistentvolumes "ebs" is forbidden: error querying AWS EBS volume vol-01ed6a9c3fc0d4e90: error finding instance i-069a3cd738c463ffa: "error listing AWS instances: \"NoCredentialProviders: no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\""

**Comment by loganhz** [comment]
The errors you are showing are all related to not having the correct IAM profile attached to the instances

Close in favor of https://github.com/rancher/rancher/issues/9343
