### ISSUE TITLE
Getting source IP from the request

### ISSUE THREAD

**Issue by adalga** [rancher/rancher#16815]
I have 5 nodes custom kubernetes cluster v1.10.1 which is created via rancher. Rancher version is 2.0.8 .It has default rke nginx ingress controller. I want to get source IP from the request. I searched about it and found a configuration which is "use-proxy-protocol: true" . I added it into the nginx-configuration configmap. After then I could not reach any of my servers including default backend. Nginx-ingress-controller pods logs an error which is "broken headers".  How can I get the source IP from the request?

**Comment by vincent99** [comment]
That option means to expect the incoming request to have the proxy protocol preamble in it.  Since it doesn't, the beginning of the request is eaten and what's left to try and process as a http request is garbage.

**Comment by adalga** [comment]
When I try to get source IP I get LB's IP. So, How could I get the source IP?
