### ISSUE TITLE
[rancher-compose] Service Upgrade provide way to delete old service

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#1682]
Currently when running `rancher-compose upgrade service1 service2`, i have to follow it up with a `rancher-compose rm --force service1`, it would be nice to have a flag for the `upgrade` command to remove service1,

eg.

`rancher-compose upgrade --remove service1 service2`

**Comment by deniseschannon** [comment]
Pre-duplicate of #1817
