### ISSUE TITLE
RKE tools resolves empty Azure NSG as 'null'

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#16825]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
RKE tools resolves empty Azure NSG as 'null' which causes issues for customer environment that does not use a NSG.

**Other details that may be helpful:**
Pull request has been created to change behavior to prefer value from the rke config
https://github.com/rancher/rke-tools/pull/31

**Comment by alena1108** [comment]
@sangeethah the fix is in k8s 1.11.6 that should be available on master now

**Comment by moelsayed** [comment]
I don't have more details regarding the issue. @patrick0057 should be able to help further.

**Comment by patrick0057** [comment]
I am currently waiting for more information on this issue from our customer.  I'll update again once I receive a reply.

**Comment by patrick0057** [comment]
https://github.com/rancher/rke-tools/pull/31 has been merged and confirmed working.  This issue can be resolved at this time.
