### ISSUE TITLE
Document editing message for pipeline notification 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16827]
Enhancement. 

So far the only way to change the notification message for a pipeline is to edit the YAML file via `View/Edit YAML` option. And there are no hints for users to know that Rancher has this feature.

It will be great to have a field under the notification setting section to allow the user to edit the notification message. 

The image shows the current UI for setting the pipeline's notification. 
![screenshot](https://user-images.githubusercontent.com/6218999/49410502-26667e00-f722-11e8-8cc4-0e53e910784a.png)

Related issue:
Be able to send notifications to notifiers when pipelines are finished: https://github.com/rancher/rancher/issues/15665

**Comment by loganhz** [comment]
Hi @jiaqiluo It is by design as @cloudnautique decided to hide it in UI as most of users won't change it at all. We will make it clear in the document.

**Comment by jiaqiluo** [comment]
That sounds good!  I will leave this issue open now until we get those documents done.

**Comment by arbermarleku** [comment]
@jiaqiluo - can you tell me how did you enable that option into Rancher .

Thanks in advance

**Comment by jiaqiluo** [comment]
@arbermarleku  You can see those options when you edit a pipeline in a project. 

At first, you need to add a notifer to the clsuter: go to `Tools` ->` Notifier` -> `Add Notifier` to add a notifier. 

Then you can go to a proejct, add a pipeline under `workloads`; after that, when you choose to `Edit Config`, you can see a section called `Notification` which is disabled by default. Turn it on and now you can see the options I am talking about. 
![screenshot](https://user-images.githubusercontent.com/6218999/51709757-81ab4300-1fe4-11e9-878e-1d9cd0b1ab16.png)
![screenshot](https://user-images.githubusercontent.com/6218999/51709802-a0a9d500-1fe4-11e9-83f7-d1543ebce72a.png)


Rancher document has a detailed explanation for notifers and polelines under the section `Rancher Tools` : https://rancher.com/docs/rancher/v2.x/en/tools/

I hope this will be helpful.  Let me know if you have any question.

**Comment by arbermarleku** [comment]
@jiaqiluo - first thanks for the quick reply. 
My rancher version is 2.1.4
I have added for notifier my slack channel as you said but i still didnt manage to see the notification.
I have read the rancher documentation before asking for help.
Do you need anything else from my side in order to troubleshoot my issiue.
i will attach a screen shot just to update of what i have on my Rancher

<img width="1548" alt="screenshot 2019-01-29 at 10 12 03 pm" src="https://user-images.githubusercontent.com/41958760/51941230-5c6b6a00-2414-11e9-9d34-b3ada4535c11.png">


br
@arbermarleku

**Comment by jiaqiluo** [comment]
@arbermarleku  This will be a new feature in the v2.2 release. I am sorry not to mention it in my previous reply. You can play around with it with rancher: master which is **unstable** and **not** meant to be used in production.

**Comment by cjellick** [comment]
Resolution of this is that we are not going to expose it in the UI. Switching type to task

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/docs/issues/1036
