### ISSUE TITLE
[UI] Text gets overlapped in site-access /member list page when user's UID fields are big

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16820]
Server version - Build from master - Nov 30

Enable SAML - Ping Federator auth.

Try to add users to site-access / cluster or project member list.
Users in this case gets added with Distinguished Name of format - ```CN=<cn-name>,CN=Users,DC= <name>,DC=<name>,DC=<name>```

Text gets truncated .

**Comment by davidnuzik** [comment]
Version: master-head (8/9/19)

Our test system for PingFederator is not currently working but I was able to test via an alternative method that is sufficient.

- Create a new user with a long user name and a long displayname. Per the PR, we now wrap accordingly.

Some examples/tests:

with spaces:
![image](https://user-images.githubusercontent.com/45179589/62795635-101c7900-ba8c-11e9-90b9-182ff7fc84d9.png)

without spaces:
![image](https://user-images.githubusercontent.com/45179589/62795712-34785580-ba8c-11e9-9a7b-6a3816d81e63.png)

In both situations the wrapping is working as expected now.
