### ISSUE TITLE
Fix typo in created clusteralerts

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16823]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
See https://github.com/rancher/rancher/blob/master/pkg/controllers/user/alert/controller.go#L166

```	
eventRule := &v3.ClusterAlert{
		ObjectMeta: metav1.ObjectMeta{
			Name: "clusteralert-deploment-event",
		},
```

**Result:**

**Comment by loganhz** [comment]
The typo has been fixed.
