### ISSUE TITLE
Validate applications in Library catalog .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16830]
For every application in  Library catalog:
1. Make sure we are able to launch the application successfully.
2. Able to launch the application successfully.
3. We should be able to get the application to start successfully without having to override any default settings.

**Comment by cjellick** [comment]
@sangeethah @rootwuj what does status/tested mean? I dont like this label. doesnt fit into my understanding of our labels :-)

**Comment by rootwuj** [comment]
Version: master 2.2 (2/12/19)
Confirmed fix.
