### ISSUE TITLE
cannot delete namespace

### ISSUE THREAD

**Issue by miahwk** [rancher/rancher#16833]
when delete project or namespace, it display Waiting on project-precan-alert-controller_local. And cannot delete again. I have tried to use kubectl. It was error.

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

**Comment by superseb** [comment]
Let me know if you need help on this.
