### ISSUE TITLE
Windows support for recognized CA

### ISSUE THREAD

**Issue by laoshancun** [rancher/rancher#16837]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG
**Steps to reproduce (least amount of steps as possible):**
1. Create a Rancher server with recognized CA.
2. Create a custom cluster with windows support.
3. add windows worker node.
**Result:**
```cmd
C:\Users\Administrator>PowerShell -Sta -NoLogo -NonInteractive -Command "& {docker run --rm -v C:/:C:/host rancher/rancher-agent:v2.1.2-nanoserver-1803 -server https://rancher-host -token wzznldxpbkd48fflcc9m7khwhfqbwfcr4f2v4gl4hp9zkhkxdtm79r; if($?){& c:/etc/rancher/run.ps1;}}"
C:\Program Files\rancher\start.ps1 : Cannot process command because of one or more missing mandatory parameters: caChecksum.
+ CategoryInfo          : InvalidArgument: (:) [start.ps1], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingMandatoryParameter,start.ps1
```
**Other details that may be helpful:**
 #16078 was merged,but `rancher/rancher-agent:v2.1.2-nanoserver-1803` still require caChecksum.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.1.2
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):v1.12.1

```
(paste the output here)
```

- Docker (use `docker info`):

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.2-ee-17
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.997GiB
Name: WIN-FUQ95A46CN2
ID: EM2H:GUIJ:OK4M:GHFJ:3MEU:2UWL:K4SK:CWHJ:7AEO:F32F:X2EI:3BER
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false
```

**Comment by superseb** [comment]
Ticket https://github.com/rancher/rancher/issues/15966 is still open en marked for milestone v2.2
