### ISSUE TITLE
EKS option Produces a bad URL 502 bad gateway

### ISSUE THREAD

**Issue by GitaWei** [rancher/rancher#16845]
Simply starting orstar/Rancher and selecting the EKS option entering valid key and secret information produces the bad gateway 502 error.  It is obvious that the generated url cannot work I believe : https://34.219.228.173/meta/proxy/ec2.us-west-2.amazonaws.com/

Thanks for any assistance.
L 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6-cce-rc36` UI: `v2.0.61-consumer-42` |
|Access|`local` `admin`|
|Route|`global-admin.clusters.new`|

**Comment by vincent99** [comment]
Assuming that's your IP that's correct.  The request is proxied through the rancher server container because the browser can't make API calls directly to AWS.

**Comment by GitaWei** [comment]
Yes but apparently not using the generated url.

**Comment by vincent99** [comment]
That is the correct URL for the UI to be requesting.  Whether the server can then hit the EC2 API and get a response is another matter, is the US AWS API even reachable from China?  EKS is only available in 4 regions, all in the US/EU.

**Comment by loganhz** [comment]
@GitaWei Please talk to Yuxing Deng or Fei Chen directly. Thanks a lot

**Comment by loganhz** [comment]
can you try it by using rancher/rancher:v2.1.3?

**Comment by orangedeng** [comment]
@weidongshao @GitaWei Hi, I am Yuxing who build the image which you are using. Can I have your email addresses which I can get in touch with you? My email address is `yuxing@rancher.com`.
