### ISSUE TITLE
Helm chart doesn't clean up resources when deleted

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#16843]
**What kind of request is this (question/bug/enhancement/feature request):** `Bug`

**Steps to reproduce (least amount of steps as possible):**

* Deploy Rancher using Docker for Mac via [helm installation instructions](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/)
* Delete helm installation `helm delete rancher-server --purge`

**Result:**

Rancher resources don't get cleaned up.  After the helm delete, attempting to manually delete the `cattle-system` namespace results in the namespace getting stuck in "terminating" and the namespace never fully deletes.

**Other details that may be helpful:**

This is reproducible on Docker for Mac, I haven't tested elsewhere.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `Rancher stable chart v2.1.1`
- Installation option (single install/HA): `Helm`

**Comment by superseb** [comment]
It has been discussed before and is described in https://github.com/rancher/rancher/issues/14715#issuecomment-407900343 and following comments.

Let me know if that doesn't solve the issue.
