### ISSUE TITLE
Change Kontainer Engine Driver naming scheme

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#16842]
We need to update the kontainer engine driver naming scheme to be more in line with docker machine driver naming scheme.

Right now, the kontainer engine driver naming scheme is:
```
kontainer-engine-<<driver name>>-driver-<<extra info>>
```
So a driver with a binary name of `kontainer-engine-example-driver-linux` will have a display name of `example` in Rancher.

Our new scheme will be of the format:
```
kontainer-engine-driver-<<driver name>>-<<extra info>>
```
So a driver with a binary name of `kontainer-engine-driver-example-linux` will have a display name of `example` in rancher.

This is to bring the kontainer engine drivers more in line with the docker machine drivers, which have a format of:
```
docker-machine-driver-<<driver name>>-<<extra info>>
```

**Comment by loganhz** [comment]
Version master 12/05 
The cluster driver name field is expected
Verified fixed
