### ISSUE TITLE
Case sensitivity of Stack Names throws error in rancher-compose

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1684]
Rancher: v0.30.0
Rancher-Compose: v0.2.5

Rancher requires unique stack names regardless of case sensitivity. I am not allowed to have two stacks named `MyApp` and `myapp`.

Issue A:
Rancher-Compose will take the project name and assume that it is all lowercase when looking for the project in Rancher. If we fix to stop making all the project all lowercase, we should also fix #1565.

Issue B: 
If I use `rancher-compose -p MyApp up`, it will look for a project in Rancher named `myapp` based on Issue A. If I have `MyApp` in Rancher as a stack name, it'll throw an error.

**Comment by deniseschannon** [comment]
Needs to be fixed with #1693 and #1694

**Comment by sangeethah** [comment]
Tested with build from master on Aug 21:

When creating services from rancher-compose (and UI) , stack name get created in lowercase.

When stack name is passed from rancher-compose , it tries to look up for existing stacks  in lowercase  in rancher server .
