### ISSUE TITLE
UI review of Drain modal

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16854]
Version - 2.2 master 12/4
NOTE: #16894 needs to be fixed first

**Steps to reproduce (least amount of steps as possible):**
1.  Create a cluster with at least 1 node
2.  Go to Node list page
3.  Select a node and click drain

**Result:**  Drain modal comes up and has never been tested.  Please test modal
![image](https://user-images.githubusercontent.com/11514927/49482124-15ce0a80-f7eb-11e8-9b57-b42dd5353cf6.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/13/18)
Tested the new Drain modal:
- Test every option within the modal, ensure that each option is taken (inspect http for each)
- Check spelling.
- Test selecting one or more nodes at once and draining both with and without the modal. Confirmed when using modal only the node we used to pick the context menu to drain with the modal was actually drained even if multiple selected.
- Uncordon and drain again, halo test by fuzzing data, try to break modal, test all the other options on the node UI page. Notice with extremely long numbers for gracePeriod we get an API error, as expected. Notice the timeout is limited to 10800 in the UI.
- Have no nodes selected and ensure can still drain via node context menu.

**Comment by blevinson** [comment]
2.2.3 Drain doesn't work:
2019/06/09 05:08:47 [ERROR] nodeDrain: [k8s-2] in cluster [c-gvtcq] :  <nil>
2019/06/09 05:08:47 [INFO] Draining node k8s-2 in c-gvtcq
2019/06/09 05:08:50 [ERROR] nodeDrain: [k8s-2] in cluster [c-gvtcq] :  <nil>
2019/06/09 05:08:50 [INFO] Draining node k8s-2 in c-gvtcq
2019/06/09 05:08:52 [ERROR] nodeDrain: [k8s-2] in cluster [c-gvtcq] :  <nil>
2019/06/09 05:08:52 [INFO] Draining node k8s-2 in c-gvtcq

**Comment by davidnuzik** [comment]
@blevinson please open an issue. This is most likely a backend issue.
