### ISSUE TITLE
rancher 1.6 removal of team via github causes environment to become inaccessible

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#16850]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Setup Github authentication on Rancher 1.6
2) add team to environment
3) remove team via github

**Result:**
You can no longer access the environment.  rancher/server logs below:
time="2018-12-04T21:53:35Z" level=info msg="Auth provider configured githubconfig" 
time="2018-12-04T21:55:24Z" level=error msg="Github getTeamByID: GET url https://github.testenvironment.local/api/v3/teams/2 received error from github, err: Request failed, got status code: 404. Response: {\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://developer.github.com/enterprise/2.15/v3/teams/#get-team\"\n}\n" 
time="2018-12-04T21:55:24Z" level=error msg="SearchIdentities Failed with error Request failed, got status code: 404. Response: {\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://developer.github.com/enterprise/2.15/v3/teams/#get-team\"\n}\n" 
2018-12-04 21:55:24,555 ERROR [:] [] [] [] [ecutorService-2] [.a.a.i.e.ExternalServiceAuthProvider] getIdentity: Got error from Auth service. statusCode: 500 
time="2018-12-04T21:55:25Z" level=error msg="Github getTeamByID: GET url https://github.testenvironment.local/api/v3/teams/2 received error from github, err: Request failed, got status code: 404. Response: {\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://developer.github.com/enterprise/2.15/v3/teams/#get-team\"\n}\n" 
time="2018-12-04T21:55:25Z" level=error msg="SearchIdentities Failed with error Request failed, got status code: 404. Response: {\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://developer.github.com/enterprise/2.15/v3/teams/#get-team\"\n}\n" 
2018-12-04 21:55:25,191 ERROR [:] [] [] [] [qtp766572210-88] [.a.a.i.e.ExternalServiceAuthProvider] getIdentity: Got error from Auth service. statusCode: 500 

**Other details that may be helpful:**
As a work around, you can manually update the MySQL table to set the entry as removed.
use cattle;
select * from project_member;
update project_member set removed=now(),remove_time=now(),state='removed' where id=<id_#_of_row_you_want_to_remove>; 

**Environment information**
Rancher v1.6.24

**Comment by deniseschannon** [comment]
You should remove the team from Rancher environments before removing it from Github. 

Development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by prachidamle** [comment]
The way I see this happening is:

- Setup Github authentication on Rancher 1.6
- add team to environment
- remove team via github

What happens when you remove the team is that on the UI, if you try to launch the environment to edit it, it never loads the members list. The UI hits some NPE error cause this. 

So "You can no longer access the environment" in the ticket above means that you can no longer edit it to list/add/delete members.The environment and all stacks/services continue functioning well.

Fix:
https://github.com/rancher/cattle/pull/3275

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc1`

**Comment by soumyalj** [comment]
Reproduce the issue with v1.6.26. 
In Github, created an organization and team under it .
Added the team as a member of an env.
Deleted the team in Github. 
After deleting, editing the env displayed a blank screen.
http://abcd:8080/settings/env/1a26?editing=true
![Screen Shot 2019-09-27 at 5 19 02 PM](https://user-images.githubusercontent.com/18536626/65808744-15707880-e14b-11e9-9c1d-e656df954ba1.png)

Tested with v1.6.29-rc2. Performed the same steps as above. 
Editing the env did not give any error. The deleted team was displayed as "team not found"
![Screen Shot 2019-09-27 at 5 21 14 PM](https://user-images.githubusercontent.com/18536626/65808760-3f299f80-e14b-11e9-85d3-a02040538e80.png)

After this operation, adding and deleting members to the env was functional.  The setup was functional
