### ISSUE TITLE
项目、命名空间的资源限制

### ISSUE THREAD

**Issue by xiliangMa** [rancher/rancher#16856]
*Describe your issue here*
现在以项目、命名空间的资源限制没有达到预期的效果，还是在每个容器上添加了limits限制，如果从应用的维度去限制是不能满足需求的；

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.2` UI: `v2.1.17` |
|Route|`authenticated.project.alert.index`|

**Comment by loganhz** [comment]
这个2.2里会加LimitRange  就不用每个容器都做限制了 可以看一下k8s的文档。 还要这里一定要用英文，因为全球用户都要看。我们有微信群的支持，在微信上搜索 `rancher2`

**Comment by xiliangMa** [comment]
> 这个2.2里会加LimitRange 就不用每个容器都做限制了 可以看一下k8s的文档。 还有这里一定要用英文，因为全球用户都要看。我们有微信群的支持，在微信上搜索 `rancher2`
我的意思是限制到命名空间就好了，现在并没有限制，需要手动修改ymal文件，并且如果在项目添加限制后部署应用报错
` is forbidden: failed quota: default-gfgvj: must specify limits.cpu,limits.memory,requests.cpu,requests.memory; Deployment does not have minimum availability.`

**Comment by loganhz** [comment]
@xiliangMa This is a k8s limitation. Please read the k8s doc. And please do not use Chinese here.

**Comment by xiliangMa** [comment]
> @xiliangMa This is a k8s limitation. Please read the k8s doc. And please do not use Chinese here.

ok thanks
