### ISSUE TITLE
Node hangs while working on the build context

### ISSUE THREAD

**Issue by cedricziel** [rancher/rancher#1686]
When i push via `rancher-compose up` and use a image that has to be build from a directory, the node becomes unresponsive on the rancher UI and via SSH i can see that the python process sucks up 100% CPU and never finishes.

The rancher ui shows just "Storage" for the newly created service.

My docker-compose manifest:

```
web:
  build: .
```

Am I doing it wrong? AWS and Rancher credentials are set, the build context is transferred to S3 correctly, it's just that the image building (i think) doesnt work. Tried both Ubuntu and CoreOS nodes.

**Comment by deniseschannon** [comment]
I haven't tried building from rancher-compose, but I don't think you need the `.` if the DockerFile is in the same directory.

Can you try 
```
web:
  build: 
```

**Comment by cedricziel** [comment]
Doesnt fix the problem :/
How do others go by? Build upfront and use a registry?

**Comment by deniseschannon** [comment]
People have been a combination of building upfront and using the build. 

Have you confirmed that you can build the file using `docker build`? 

Can you share the `rancher-compose` log and your `rancher-compose -v`?

**Comment by deniseschannon** [comment]
@cedricziel If you're still having issues, please let me know. Otherwise I will be closing this issue.

**Comment by cedricziel** [comment]
The problem still persists. I discarded Rancher completely because of that.

Rancher compose is `v0.2.5`

```
Rancher	v0.35.0
Cattle	v0.86.0
User Interface	v0.45.0
Rancher Compose	beta/latest
```

I just now provisioned a fresh DO host with 8GB to see if it can compute the build context. It cant. The node hangs and doesnt get re-added to the cluster.

Here's my example app: https://github.com/cedricziel/rancher-1686
