### ISSUE TITLE
Kontainer engine doesn't support edit cluster options

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16862]
rancher/rancher:master 12/04

Now we have implemented Tencent and Aliyun hosted k8s drivers in rancher.
But it doesn't support to update the config.

That means user can not scale up or scale down the nodes in the cluster.

We need to support it.

**Comment by cjellick** [comment]
@loganhz can you have some try this again? This was broken even for GKE briefly on master, but it was fixed. So, I am just wondering if  it is also fixed for your providers

**Comment by cjellick** [comment]
@loganhz said  in 17174/5/6 that this has been fixed in master. closing
