### ISSUE TITLE
Validate RHEL 7.6 for 1.x

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16867]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Add RHEL 7.6 to supported OS for 1.6

**Comment by alena1108** [comment]
@sangeethah can we run an automation test for this version, to see if there are any failures.

**Comment by soumyalj** [comment]
Tested Rancher v1.6.26-rc1/master with RHEL 7.6 for below configurations:
1. Native Docker 1.13 with Selinux enabled
2. Upstream Docker 1.13 with Selinux disabled

Automation test runs were fine no new issues.
