### ISSUE TITLE
Add option to provide extra_env to NGINX ingress controller

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16868]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Setup was in a proxied environment and wanted to complete the certificate chain with needed intermediates (for use with OCSP), but the NGINX ingress controller couldn't reach it without proxy information:

```unexpected error generating SSL certificate with full intermediate chain CA certs: Get http://xxx: dial tcp x.x.x.x:x: getsockopt: network is unreachable.```

After manually patching the daemonset, it was able to work.

```
kubectl -n ingress-nginx patch daemonset/nginx-ingress-controller -p '{"spec": {"template": {"spec": {"containers": [{"name": "nginx-ingress-controller", "env": [{"name": "HTTP_PROXY", "value": "http://127.0.0.1:3128"},{"name": "HTTPS_PROXY", "value": "http://127.0.0.1:3128"},{"name": "NO_PROXY", "value": "localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"}]}]}}}}'
```

Or use `--enable-ssl-chain-completion=false` to disable chain completion

**Comment by mrajashree** [comment]
Closing in flaovro of https://github.com/rancher/rke/issues/1104
