### ISSUE TITLE
K8s 1.12.x impossible to create external loadbalancers on openstack if no parameters passed to cloud provider config

### ISSUE THREAD

**Issue by m-wcislo** [rancher/rancher#16866]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Deploy new k8s cluster with bumped up version of kubernetes to 1.12.x. Using Openstack as cloud provider, no specific LBaas configuration applied - worked with k8s 1.11.3.

**Result:**
Services using load balancer will hang with pending status for obtaining external IP. Nothing happens in Openstack.

**Other details that may be helpful:**
Caused by https://github.com/kubernetes/kubernetes/pull/65781. 

**Environment information**
- Rancher version 2.1.1/2.1.2
- Installation option (single install/HA): HA on kubernetes 2.12.x, spawning new cluster with same version.

**Cluster information**
- Cluster type Openstack
- Machine type VM
- Kubernetes version (use `kubectl version`): 1.12.x

This is just to share knowledge and possibly save some time for people upgrading to k8s 1.12.x with Rancher. Example workaround:
"loadBalancer": {
  "lb-method": "ROUND_ROBIN"
 }, 
which is deafult.

I was expecting to put some default value by Rancher but then it will be against the original k8s PR which caused the behavior described here. But certainly some message in UI could be passed to user to understand that without defined LBaas configuration exposing this way is not possible.

Also, Rancher API is a bit misleading by showing loadBalancer  with empty values, but nothing is actually applied to /etc/kubernetes/cloud-config on k8s until something is set explicitly.

**Comment by deniseschannon** [comment]
Looks like this is fixed in upstream k8s and should work in rancher now.
