### ISSUE TITLE
Rollback UI fails to account for ReplicaSet count changes

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#16874]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Steps to reproduce (least amount of steps as possible):**
1. Create a deployment
2. Change the image
3. Change the count

**Result:**
The change to the image is accounted for in the Rollback feature, the count is not

Image Change
![image](https://user-images.githubusercontent.com/942110/49525256-58d7be80-f87b-11e8-9c52-3e4dbb64b0a5.png)

Count Change
![image](https://user-images.githubusercontent.com/942110/49525299-7573f680-f87b-11e8-8521-5a4e64912066.png)

**Environment information**
Rancher 2.1.2

**Comment by vincent99** [comment]
The scale/how many pods there are?  The scale is a property of the deployment and not the replicasets/revisions it creates. 

Changing it (on its own) doesn't create a new revision, and rolling back doesn't restore a previous value of it.

**Comment by JasonvanBrackel** [comment]
I thought that changed the underlying replicas count.  My mistake.  Regardless, by abstracting out the various controllers into a workload, we've created an area of confusion for the user.  Not sure what the right answer is there, but it was brought to my attention as an annoyance for a customer.

**Comment by deniseschannon** [comment]
Minimally, we should document how revisions work and how scale is not within that scope.
