### ISSUE TITLE
Add additional to alertstatus to signify the condition causing the alert has changed

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#16876]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

Rancher 2.1.2

When an alert changes from alerting to active it would be helpful to have something to track that the change has occurred.  This would help recognizing a change in state or possible resolution at scale.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17962
