### ISSUE TITLE
Rancher dashboard reporting wrong usage stats

### ISSUE THREAD

**Issue by CombatCode** [rancher/rancher#16870]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Set up rancher on AWS EC2 instances

**Result:**
Custer dashboard shows wrong stats

**Other details that may be helpful:**

**Environment information**
- Rancher version `rancher/rancher` 2.1.2
- Installation option single install:

**Cluster information**
- Cluster type Infrastructure Provider:
- Machine type (cloud) and specifications (4GB RAM/ 2CPU / T3):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

![](https://i.gyazo.com/856bb0a98edd8e640d30d290bd44f701.png)

vs ![](https://i.gyazo.com/acac357a89dcd4e2c5657887f472a7f2.png)

**Comment by superseb** [comment]
`kubectl top` shows actual usage, while the dashboard shows reserved. See https://github.com/rancher/rancher/issues/12683
