### ISSUE TITLE
Rancher 2.1 github teams do not show up in members dropdown when added after setting up GitHub authentication

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#16872]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Create some teams in GitHub enterprise
2) Setup GitHub enterprise authentication in Rancher 2.1
3) Add a new team in GitHub enterprise
4) Select your cluster from dropdown menu, click members> click add member> then click drop down arrow to the right of the member field.

**Result:**
Teams added before enabling GitHub authentication show up.
Teams added after enabling GitHub authentication do not show up.

**Other details that may be helpful:**
Disabling GitHub authentication and re-enabling it will refresh teams list in Rancher.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): single

**Comment by deniseschannon** [comment]
Workaround: Log out and log back into Rancher to see new teams.
