### ISSUE TITLE
[cli] cannot install app into existing namespace

### ISSUE THREAD

**Issue by quorak** [rancher/rancher#16873]
I would like to use the cli to install apps into an existing namespace. is there a customize flag, just like in the ui?

**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
rancher apps install kibana --answers values/kibana.yaml kibana -n logging

**Result:**
FATA[0001] namespace logging already exists  

**Other details that may be helpful:**

**Environment information**
rancher version v2.0.6

**Cluster information**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by quorak** [comment]
can anyone reproduce this?

**Comment by anjmao** [comment]
I have the same problem.

**Comment by davidnuzik** [comment]
Version: v2.2.3

- Create project `16873` and create `logging` namespace in this project
- Create API key for Rancher CLI in my case with `no scope`
- Download CLI from rancher (v2.2.0)
- Login to CLI and choose the `16873` project upon login
```
NUMBER    CLUSTER NAME   PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         david-223ec2   c-hdmzq:p-dncb9   Default        Default project created for the cluster
2         david-223ec2   c-hdmzq:p-jc5xf   16873          
3         david-223ec2   c-hdmzq:p-jdqh4   System         System project created for the cluster
Select a Project:2
INFO[0011] Saving config to /Users/david/.rancher/cli2.json 
```
- Have your answers in a yaml and execute command to deploy the app in my case `docker-registry`
`./rancher apps install docker-registry --answers values/docker-registry.yaml docker-registry -n logging`

This worked for me. I didn't get the `FATA[0001] namespace logging already exists` error mentioned by the issue author.

I did run into an unrelated issue while the app was deploying and will investigate. If an issue needs to be created I will update this comment with a link to that issue.

**Comment by davidnuzik** [comment]
@quorak I wasn't able to reproduce the issue in Rancher v2.2.3. If you have any questions or concerns please let us know and feel free to re-open the issue please.

**Comment by hoozecn** [comment]
People may with same prob:

Just make sure the namespace is under the current project in rancher configuration
