### ISSUE TITLE
Not async catalog refresh

### ISSUE THREAD

**Issue by Razikus** [rancher/rancher#16871]
Hi for now there is only option for async catalogue refresh, and we can't check in API if the catalogue was refreshed.

My proposal is to make a new api endpoint to refresh and wait for response to be sure that catalogue was refreshed.

That will help in auto-deploying catalogue apps.

What kind of request is this: feature request

**Comment by gitlawr** [comment]
You can infer that from the catalog state. When the catalog is refreshing, its state goes to `refreshed`. When it is done, the state goes to `active`.

**Comment by vincent99** [comment]
It really should have been `refresging`, but yes.  You can also look at the transitioning field on most types.  You either pool the resource or subscribe to the websocket and get pushed updated copies of the resource as it changes.

Synchronous response for long-running requests leads to all sorts of trouble with timeouts in the client, server, or proxies or loadbalancers in between; we will not be adding that.

**Comment by Razikus** [comment]
Okay i understand - thanks for answer!
