### ISSUE TITLE
Custom cluster failed to provision worker plane with kube-proxy unhealthy

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#16883]
rancher/rancher:v2.0.9-rc1
rancher/server-chart:v2.0.8

HA setup via helm

_We have not been able to reproduce so far_

When provisioning a custom cluster, once saw the cluster fail to provision with the following error: 
```
[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Service [kube-proxy] is not healthy on host [<etcd host>]. Response code: [503], response body: {"lastUpdated": "2018-12-04 23:52:42.752128059 +0000 UTC m=+0.168332221","currentTime": "2018-12-04 23:56:43.405681641 +0000 UTC m=+240.821885919"}, log: E1204 23:56:47.909906 9749 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.Endpoints: Get https://127.0.0.1:6443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: connect: connection refused
```

From debugging by @galal-hussein: 
```
nginx proxy is failing because of a wrong ip address for the controlplane
```

The registration command only specified the public address for the nodes.

**Comment by gav1nb81** [comment]
I get the same error after upgrading my bare metal Rancher server from v2.1.1 to v2.1.5. 

Having successfully upgraded Rancher server, I then try to bring my custom cluster up to Kubernetes version v1.11.6 through the Edit Cluster option in the Rancher interface:

`
[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Service [kube-proxy] is not healthy on host [10.10.54.170]. Response code: [503], response body: {"lastUpdated": "2019-01-15 14:27:22.400278675 +0000 UTC m=+0.520846541","currentTime": "2019-01-15 15:27:45.248558789 +0000 UTC m=+3623.369126679"}, log: E0115 15:27:50.334772 11923 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.Endpoints: Get https://127.0.0.1:6443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 127.0.0.1:6443: connect: connection refused
`

On the Ubuntu host used for this node I can see the nginx-proxy container is constantly restarting. Docker logs for this container show:

`2019-01-15T14:38:57Z serveretcd03 confd[8]: INFO Backend set to env`
`2019-01-15T14:38:57Z serveretcd03 confd[8]: INFO Starting confd`
`2019-01-15T14:38:57Z serveretcd03 confd[8]: INFO Backend source(s) set to`
`2019/01/15 14:38:57 [emerg] 14#14: no host in upstream ":6443" in /etc/nginx/nginx.conf:13
nginx: [emerg] no host in upstream ":6443" in /etc/nginx/nginx.conf:13`
`2019-01-15T14:39:24Z serveretcd03 confd[8]: INFO Backend set to env`
`2019-01-15T14:39:24Z serveretcd03 confd[8]: INFO Starting confd`
`2019-01-15T14:39:24Z serveretcd03 confd[8]: INFO Backend source(s) set to`
`2019/01/15 14:39:24 [emerg] 14#14: no host in upstream ":6443" in /etc/nginx/nginx.conf:13`
