### ISSUE TITLE
Adding hosts via private networks leaves host without any public IP registerd

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#1688]
When setting host registration to use the private network the new host is added correctly however the only IP address that gets registered is the private IP of the host. Then when adding a balanced service the load balancer is configured on the private ip and so you can never get to the service.

New hosts should try and be intelligent with their IP reporting. Typically eth0 is the public interface, or there should be a way to specify the IP address of a host.

**Comment by haswalt** [comment]
Note this is mostly a UI issue in that when you create a host using the EC2 api or DO api for example I don't want to have to login to those accounts to work out how to access my containers

**Comment by haswalt** [comment]
This also causes things like viewing container logs and executing console on hosts doesn't work

**Comment by cjellick** [comment]
@haswalt thanks for the feedback. Wi'll look into all the issues you mentioned, but want to start with the last one first: I'm surprised that this causes logs and exec not to work. Do you have behind a elastic load balancer or any other proxy?

Next, we do have a way to allow you to explicit set a host's IP, but it's only available when you add a custom host and execute the `docker run ... rancher/agent` command on the host yourself. When you do that, you can add `-e CATTLE_AGENT_IP=<desired ip>`.

Next, I don't have a great answer for your balanced service problem. Will need to investigate it a little more.

Can you share the version of Rancher that are you using? If you inspect the rancher/server container, you'll see an environment called CATTLE_RANCHER_SERVER_IMAGE that has that information.

**Comment by haswalt** [comment]
I'm currently using v0.31.0-rc3.

There is no load balancer or proxy in front of the instances. Hosts talked to the server via the private network. The websocket proxy is also running over the private network as well.

I get no error messages or log output when attempting to connect to the container console or get logs.

If I change the CATTLE_AGENT_IP won't that mean that the host won't communicate over the private network?

In my setup in attempting to get all orchestration traffic to run over the private network (99% works) and only expose the public network to incoming container traffic such as web.

**Comment by haswalt** [comment]
I've just found the issue for the connecting to the console and it is related. Basically because the host gets configured with the private ip the browser then attempts to use the private ip for the web socket connection which it can access. I'd expect some way to allow rancher to handle public traffic and let orchestration between host and server to go over the private network

**Comment by ibuildthecloud** [comment]
A couple things don't line up here.  I'll investigate further.  The IP of the host is used only to setup the private network and nothing else.

The console/logs go directly to the server now.  In the past the web browser would connect to the host but that is no longer the case.  You web browser needs to talk to the rancher/server and nothing else.

When we bind a load balancer to the host we actually don't bind it to a specific IP.  It is essentially all IPs.  In the case of EC2 the load balancer will be available on your EIP if you have your security groups setup.  If you create a host through the UI unfortunately the default behavior of Docker Machine is to not open any ports except those needed by Docker.

**Comment by haswalt** [comment]
@ibuildthecloud So here is some more information:

I added the hosts manually and I started the agent with this command:

```
docker run -d --privileged -e CATTLE_AGENT_IP=46.101.4.70 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.11 http://10.131.252.223/v1/scripts/3329F2900677B4EC9733:1438534800000:nMBfjQpEeEIWsYSWoL1YLhPMQmo
```

So you can see that the CATTLE_AGENT_IP is set to the public IP of host and the private IP address is used to connect tot he server.

If I try to view container logs in the browser for a container running on this host I see the following in the browser:

```
Socket connect 3 to ws://10.131.252.223:9000/v1/stats/9e9e74bc3e2411a4b848f5f6cba20ecd041745a186b11b696ede2ec817f95f19...
```

Of course that fails as the private IP can't be accessed over the WAN.

**Comment by haswalt** [comment]
Currently use:

```
Component	Version
Rancher	v0.32.0
Cattle	v0.75.0
User Interface	v0.40.0
Rancher Compose	beta/latest
```

**Comment by cjellick** [comment]
@haswalt Did you install rancher using our simple single-node setup or do you have a multi-node setup? "Node" in this case refers to instances of rancher/server.

Also, I see that in your docker run, the connection URL is `http://10.131.252.223/v1`, with no port and in the socket connect error, it is `ws://10.131.252.223:9000/v1/`, with port 9000. So, what do you have running on port 9000 and where did you configuring that?

I'm going to take a guess and say that you followed this multinode setup:
http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/
and set `...-e CATTLE_HOST_API_PROXY_HOST="10.131.252.223:9000" ...` is that right?

**Comment by haswalt** [comment]
@cjellick Your guess is correct, and yes the CATTLE_HOST_API_PROXY_HOST is set with the port number. Everything works as expected that i can see except for the viewing of logs and stats for hosts and containers due to the proxy connecting issue above

**Comment by cjellick** [comment]
@haswalt The IP you configure for the websocket proxy needs to be accessible from your browser and from the hosts. The hosts make outbound connections to it and browsers connect directly to it as well.

So, `CATTLE_HOST_API_PROXY_HOST` for rancher/server would need to have the public IP of the server running the websocket proxy and the websocket proxy's `-listen-address=<ip:port>` param would need to be 0.0.0.0:9000.

**Comment by haswalt** [comment]
@cjellick Thanks for the tip. Maybe worth adding some hinst about these environment settings and how they should be configured to make it clearer for others trying the same setup as me

**Comment by deniseschannon** [comment]
We've added more docs to make it clearer. https://github.com/rancher/rancher.github.io/pull/79
