### ISSUE TITLE
Monitoring - Cluster member can enable/disable monitoring on cluster level

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16888]
Bug.

Rancher master on 12/5

Steps:
- logged in as admin to add a standard user to a cluster as a `cluster member`
- logged in as the cluster member, go to the cluster -> Tools-> Monitoring

Result:
The cluster member can see settings and turn on the monitoring.

Expected result:
The cluster member should not be able to turn on the monitoring.

Other details might be helpful:

If the monitoring is already enabled by the admin/cluster owner, then the cluster member will see the following uncompleted sentences:
<img width="1456" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49544543-4cae2a00-f898-11e8-807a-542e1454620d.png">

**Comment by sangeethah** [comment]
Related issue - https://github.com/rancher/rancher/issues/16889

**Comment by jiaqiluo** [comment]
This issue also happens on HA setup.

**Comment by jiaqiluo** [comment]
The fix is validated on master 1/3
Steps:
- logged in as admin to enable Github Auth
- then add a Github user (standard user role) to a cluster as a cluster member
- logged in as the cluster member, go to the cluster -> Tools-> Monitoring

Result:
- The cluster member cannot turn on the monitoring.
- The cluster member cannot see live metrics and graphs when the monitoring is on.
