### ISSUE TITLE
Feature Request: Make text area like secret and configmap values resizeable

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#16882]
It's not uncommon to store configuration files in configMaps where the key is the filename and the value is the contents of a multi-line file.  The UI limits this to one line.  It would be helpful if these could be resized in the UI.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/49724433-37743980-fca4-11e8-8836-0dd2487c6dd1.png)

 Multi-lines value is already supported in UI.
