### ISSUE TITLE
GKE cluster goes to "active" state immediately after creation 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#16884]
Rancher version: Master build from Dec 5
```
root@soumyatestserver:~# sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rancher/rancher     master              17d2747c0008        46 minutes ago      448.2 MB

```
Steps:

1. Create a GKE cluster

The cluster goes to "Active" state immediately after creation and then goes to provisioning state after around 20s.   

<img width="1638" alt="screen shot 2018-12-05 at 11 19 58 am" src="https://user-images.githubusercontent.com/18536626/49538585-a73b8c00-f880-11e8-9a4d-c89867c6771f.png">

**Comment by cjellick** [comment]
@soumyalj is this a regression introduced recently?

**Comment by cjellick** [comment]
marked as p/0 under the assumption that it is a regression introduced by pluggable cluster drivers

**Comment by rmweir** [comment]
Similar to #17282

**Comment by soumyalj** [comment]
Tested with master build from Feb 13. 
Create a GKE cluster. 
The cluster goes to "Provisioning" state as expected. Example below:

<img width="1317" alt="screen shot 2019-02-13 at 10 39 19 am" src="https://user-images.githubusercontent.com/18536626/52735149-bffca800-2f7b-11e9-946c-579085fcb1dd.png">
