### ISSUE TITLE
can't edit container settings after save

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#1689]
If I save a new container / service I can no longer edit much more than the name. I'd expect to be able to change environment variables either allowing a trigered restart after or at least if I haven't started the container yet.

**Comment by deniseschannon** [comment]
Unfortunately Docker containers are immutable (not changeable) after creation. The only things you can edit are things that we store that aren't really part of the container (name, description) or are accomplished with magic the network agent enables (linked container destinations).

This includes rebooting, it's still the same container if you stop and start it. So you pretty much have to remove and recreate a container to change anything else.

There is a "Clone" action in the UI that will basically pre-fill the "add container" screen with all the settings from an existing container. So if you forget one thing you can clone the container, change it, and then delete the old container. Which is roughly what you'd do in the docker CLI, hit the up arrow a couple times to get the previous command and change it.
