### ISSUE TITLE
Monitoring - Project level monitoring is always enable if the cluster level monitoring is enabled 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16898]
Bug.

Rancher master on 12/5

Steps:
- Enable the monitoring feature at the cluster level
- Add a project under the cluster
- Do not enable the monitoring feature at the project level (by default it is off)

Result:
We can see live monitoring graphs for workloads, pods, and containers. 

More details:
It turns out that no matter the project level monitoring is on or off, as soon as the cluster level monitoring is on, the project level one is on.

**Comment by loganhz** [comment]
Close as it is by design
