### ISSUE TITLE
Local user cannot see the user's name who is form authentication provider

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16899]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Logged in as admin to enable the Github authentication
- Opened another session to log in via `log in with Github`, named user2
- Logged in as admin to add user2 to a cluster as the cluster member 
- Logged in as admin to check the cluster members

**Result:**
Cannot get the name of user2, showing `Unable to fetch user info`

<img width="1551" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49552444-e386e080-f8b0-11e8-942d-b046f98ccac1.png">

gz#3882

**Comment by cjellick** [comment]
not a bug. working as expected. when you log in using local credentials, we cannot query github for users. this is the expected degraded behavior

**Comment by aemneina** [comment]
Reopening this ticket to track as a feature request.

**Comment by bluemalkin** [comment]
In our case we use AzureAD.

Since there's no way in Rancher v2.2.0 to assign an AzureAD group as Admin role, we need to login as admin local user and add Admin to the azureAD users, however without seeing the list of Users we cannot do this.

**Comment by aemneina** [comment]
@bluemalkin the user account that's used to test/enable AzureAD becomes an Admin account capable of viewing user names and assign roles. Being a local admin is not a requirement here to carry out that task.
