### ISSUE TITLE
Azure cluster with cloud provider - worker nodes fails to start because of kubelet restarting constantly with cloud provider option set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16893]
Rancher server - Build from master - Dec 5

Steps to reproduce the problem:
Provision a Azure cluster with cloud provider with following node configuration with Azure cloud provider option set:
1 control node
1 etcd node
3 worker nodes.

Azure cluster gets to "Active" sate but worker nodes continue to be stuck in "Unavailable" state 
with error message 
```Kubelet stopped posting node status.``` 
or 
```
Container runtime is down,PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s,runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

Rancher server logs:

```
018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioning cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Updating cluster [c-bcgdr]
2018/12/05 20:46:51 [INFO] Provisioned cluster [c-bcgdr]
```

Agent logs:
```
time="2018-12-05T20:48:44Z" level=info msg="For process kubelet, Env has changed from [RKE_CLOUD_CONFIG_CHECKSUM=da94b08b5b80f8b5d5440cfd61760890] to [RKE_CLOUD_CONFIG_CHECKSUM=a2a7f88d0f324000661600c46fbe024a PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]"
```

**Comment by sangeethah** [comment]
Tested with latest latest master build from dec 6. 
Able to get Azure cluster with cloud provider to work successfully and worker nodes get to active state.

**Comment by ArgonV** [comment]
I am seeing this too, with a 11 node RancherOS cluster (5 etcd/controlplane, 6 workers), and a vSphere cloud config. We are spanning two data centers in the same region. Everytime I loose a worker node, I have this:

`"For process kubelet, Env has changed from [RKE_CLOUD_CONFIG_CHECKSUM=...`

This is with a newly provisioned cluster, using a single node Rancher Server that has been upgraded with every stable release since v2.0.6 to v2.1.6. Currently at v1.11.6-rancher1-1

**Comment by ArgonV** [comment]
Does anyone know where this env var rke_cloud_config_checksum is set?

**Comment by ArgonV** [comment]
I have found a stop-gap fix that I've tested on two vSphere node driver clusters, with node template provisioned VMs in vSphere, and using VMWare vSphere Volume storage class:

**Comment by ArgonV** [comment]
It didn't fix the issue with one RKE_CLOUD entry and comma separated values. It also didn't work with just one RKE_CLOUD entry and one env var. I forgot to mention that I also redeployed in the System project after I edited and updated the cluster:

cattle-cluster-agent
cattle-node-agent
nginx-ingress-controller
