### ISSUE TITLE
/var/lib/cattle in the rancher-agent container does not purge old downloads

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#169]

**Comment by deniseschannon** [comment]
@ibuildthecloud Is this still an issue?

**Comment by ibuildthecloud** [comment]
Yes it is.  Slowly over time the disk will just fill up.

**Comment by ibuildthecloud** [comment]
This was resolved a long time ago.  `/var/lib/cattle/downloads` will only keep 10+1 downloads for each item.
