### ISSUE TITLE
Support whitelist for docker registries per environment

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1690]
Rancher should support the ability to allow owners of environments to specify a list of docker registries that can be used when creating containers and services.
- Should we support a global whitelist?
- What about Rancher specific images that are currently hosted on dockerhub?  Do we default this to "always" whitelisted?  If not, we would need a way to configure where Rancher can find these images.

**Comment by mrajashree** [comment]
We support global whitelist with the referenced PR, as per this issue: https://github.com/rancher/rancher/issues/5799
