### ISSUE TITLE
Monitoring - Rancher Components Grafana Dashboard is broken

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16902]
rancher/rancher:master

The Grafana dashboard for Rancher Components is broken.
The metrics of the dashboard is wrong.

We need to update the default dashboard in system-charts.

**Comment by jiaqiluo** [comment]
Validation failed on master 12/6

Steps:
- logged in as admin
- added a DO cluster
- enabled the monitoring on cluster level

Result:
There are no metrics under the `Rancher Component Metrics` section, and Rancher did not deploy fluentd to the cluster
<img width="1528" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49607381-02d64a00-f953-11e8-9e7a-62acee23a13a.png">


```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by loganhz** [comment]
The issue is for fixing Rancher Components Grafana Dasboard  issue.

Maybe because you just deployed it? Could you try to switch to 5mins?

Did you enable the logging with a real endpoint such as splunk?
Could you go to System project page and check if the workloads under cattle-logging namespace are working well? The thing is if fluentd can not conncet to the endpoint (like splunk) sucessfully, users will not be able to see the metrics.

**Comment by davidnuzik** [comment]
@jiaqiluo contact me if you need any help I set up fluentd and got this working.

**Comment by jiaqiluo** [comment]
@loganhz thank you for the feedback. It works as expected after adding a cluster logging. 
Also thank @davidnuzik for providing the fluentd setup. 

Bug fix validated on master 12/6
