### ISSUE TITLE
[logging-elasticsearch]  allow local elasticsearch cluster url to log to

### ISSUE THREAD

**Issue by quorak** [rancher/rancher#16908]
I cannot add local elasticsearch cluster for logging to elasticsearch.
It looks like validating with dns records at 8.8.8.8 should not be mandatory.

**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
add logging to elasticsearch and enter internal endpoint like 

> http://elasticsearch-client.logging.svc.cluster.local

**Result:**
![image](https://user-images.githubusercontent.com/68172/49585402-8d707680-f95e-11e8-9e51-f54e8cec4538.png)

Validation failed in API: url elasticsearch-client.logging.svc.cluster.local:80 unreachable, error: dial tcp: lookup elasticsearch-client.logging.svc.cluster.local on 8.8.8.8:53: no such host

**Other details that may be helpful:**

**Environment information**
rancher 2.1.3

**Comment by loganhz** [comment]
Thanks for the report 
Close in favor of https://github.com/rancher/rancher/issues/13785
