### ISSUE TITLE
updating cluster ran into a hiccup, proceeded to succeed, warning message from UI wont go away

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#16918]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. updated a cluster via the UI (there may have been a temporary communication issue with a specific node)
2. subsequent updates to the cluster succeed, even for the host reporting a warning against

**Result:**
error message in ui wont go away:
`Provisioning incomplete, host(s) [host_ip] skipped because they could not be contacted`  

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.1
- Installation option (single install/HA):
HA

**Comment by santascsi** [comment]
I encountered the same issue when changing a cluster setting and keeping the "edit cluster" window open for too long. As a result, 2 of my 3 etcd/control nodes were listed as unable to contact.

Any following change to the cluster was only carried out on the first etcd/control node and did not carry on past the two "unreachable" nodes.

I cordoned, drained and rebooted the nodes each individually and eventually the cluster did recover and finish its configuration change.

**Environment**
- Rancher: v2.1.6
- Kubernetes: 1.11.6
- Docker-CE: 18.09.2
-  Single node Rancher setup with custom clusters on Ubuntu 16.04.5 LTS.
