### ISSUE TITLE
Multiple ports and protocols on Rancher 2.x LB

### ISSUE THREAD

**Issue by arcozen** [rancher/rancher#16912]
Hi,
I'm exploring Rancher 2.x capabilities about networking.
I would like to expose a service on multiple ports and multiple protocols.

So I used a based-on-hostname load balancer, but it seems to expose only http/https and i can expose more ports only using the /path parameter.
It's not useful for my scenario.

In Rancher 1.x it was a very useful feature by using the http.ports annotation, but it seems not to be available in Rancher 2.x.

Thanks in advance

**Comment by vincent99** [comment]
Layer 7 and Layer 4 load balancers are separate things in k8s.

There is no default L4 load balancer provider in clusters managed by Rancher (3rd party ones like AKS/GKE/EKS/imported may have their own).  Projects like MetalLB can provide them.

L7 is Ingress, which is nginx by default.  It is HTTP[S] only and runs on the standard 80/443.

**Comment by arcozen** [comment]
Why the http.ports annotation has been removed from Rancher 2?
It would be very helpuful, could be possible to get it again in next releases?
Thanks

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/11179
