### ISSUE TITLE
UI needs review - mobile

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16926]
Version: master 2.2 (12/6/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to view the rancher dashboard on a mobile device (portrait mode) and notice the page styling has issues.
- Needs general review of all the UI pages on mobile.
![bad mobile view](https://user-images.githubusercontent.com/45179589/49612152-feb12900-f960-11e8-97dd-b06349d332da.jpg)

**Result:**
Poor mobile experience

**Other details that may be helpful:**
Chrome for Android was used for testing

**Comment by westlywright** [comment]
Removing the resolved later and assigning to me because I need to look at the js dynamic padding that is being added

**Comment by lvuch** [comment]
resolved in mobile ui fixes #3076

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

I can confirm the improvements. Thank you.

When you first log in you can now see clusters view looks better:
![SmartSelect_20190806-103530_Chrome](https://user-images.githubusercontent.com/45179589/62565228-3eefe080-b83b-11e9-830b-f1ff0b29cd03.jpg)

The same is true as in other areas such as node detail view.

For remaining issues identified I created a separate issue tracked here: https://github.com/rancher/rancher/issues/22010
