### ISSUE TITLE
Cannot add the same GitHub user to two different clusters with the same role

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16929]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. enable Github auth
2. added a GitHub user to Cluster1 as either owner, member, or custom member
3. tried to add the same user to Cluster2 with the same role as step2

**Result:**
Failed to add the user.
<img width="1487" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49613215-569d5f00-f964-11e8-9e9e-005d92d4ecb2.png">

**Other details that may be helpful:**
You can add the same group to 2 clusters with the same role, or add the same user to 2 clusters with a different role. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master on 12/6
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: jiaqi-rancher-master
ID: HUDH:QL2Q:UNRI:N5JV:UCPB:KFKM:JFHQ:FXFR:A2PV:YHFA:VPEX:HQB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by bmdepesa** [comment]
This also occurs for adding the same member to two different projects. 

Groups do not seem to be affected. I was able to add the same group as a member to two different clusters.

**Comment by jiaqiluo** [comment]
Validated on master 12/7

Case1:
- enable Github auth
- added a GitHub user to Cluster1 as either owner, member, or custom member
- tried to add the same user to Cluster2 with the same role as step2

Case2:
- enable Github auth, and add two projects under the same cluster
- added a GitHub user to proejct1 as either owner, member, or custom member
- tried to add the same user to project2 with the same role as step2

Bug fix validated.
