### ISSUE TITLE
VMWare node creation failing due to missing network definition

### ISSUE THREAD

**Issue by segfault** [rancher/rancher#16923]
Creating a node in VMWare with a network specified fails. The created VM does not have a network associated with it. This was working in 2.0.x

The ui does not display a value in the Networks field but the api shows a collection for the same node template.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.3` UI: `v2.1.17` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by loganhz** [comment]
Does the `network` field of the node template look good in API?

**Comment by segfault** [comment]
It's populated and matches my expectation. I attempted to recreate the template and it ends up generating the same api response.

It's worth noting that the VM doesn't appear to be constructed correctly. The logs indicate it's trying but the VMware side doesn't reflect it. On the VMware side I don't see anything beyond the create call.
```2018/12/07 12:33:47 [INFO] stdout: Creating CA: management-state/node/nodes/wct-k8w-1/certs/ca.pem
2018/12/07 12:33:48 [INFO] stdout: Creating client certificate: management-state/node/nodes/wct-k8w-1/certs/cert.pem
2018/12/07 12:33:48 [INFO] stdout: Running pre-create checks...
E1207 12:33:48.974562       6 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
2018/12/07 12:33:49 [INFO] stdout: Creating machine...
2018/12/07 12:33:49 [INFO] stdout: (wct-k8w-1) Image cache directory does not exist, creating it at management-state/node/nodes/wct-k8w-1/cache...
2018/12/07 12:33:49 [INFO] stdout: (wct-k8w-1) Downloading management-state/node/nodes/wct-k8w-1/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.03.2-ce/boot2docker.iso...
2018/12/07 12:33:52 [INFO] stdout: (wct-k8w-1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2018/12/07 12:33:52 [INFO] stdout: (wct-k8w-1) Generating SSH Keypair...
2018/12/07 12:33:52 [INFO] stdout: (wct-k8w-1) Creating VM...
2018/12/07 12:34:17 [INFO] stdout: (wct-k8w-1) Uploading Boot2docker ISO ...
2018/12/07 12:34:45 [INFO] stdout: (wct-k8w-1) adding network: DPortGroup-trunk
2018/12/07 12:34:45 [INFO] stdout: (wct-k8w-1) Reconfiguring VM
2018/12/07 12:34:48 [INFO] stdout: (wct-k8w-1) Waiting for VMware Tools to come online...
2018/12/07 12:34:50 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2018/12/07 12:34:50 [INFO] stdout:
2018/12/07 12:34:51 [INFO] Generating and uploading node config wct-k8w-1
2018/12/07 12:34:51 [ERROR] NodeController c-pczff/m-hrcff [node-controller] failed with : Error creating machine: Error in driver during machine creation: No IP despite waiting for one - check DHCP status```

I've noticed that the VM does not actually get the boot2docker iso assigned and thus does not boot. The VMware side of this hasn't changed the only recent change was the upgrade to 2.1.x from 2.0.x

**Comment by char-iot** [comment]
It can't get boot2docker.iso from github, then it uploaded from local location then it can't find IP. Which is probably reason why it couldn't download the iso. same issue #16549

**Comment by segfault** [comment]
> It can't get boot2docker.iso from github, then it uploaded from local location then it can't find IP. Which is probably reason why it couldn't download the iso. same issue #16549

I don't read that log as it being unable to get the iso from github. I read it as the local cache of that iso doesn't exist, fetch it from github. You see it download the image and then in theory upload it to the vmware cluster.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue in Rancher 2.3, and we'll reopen it
