### ISSUE TITLE
UI needs general review and fixes for alignment and etc

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16924]
Version: master 2.2 (12/6/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Task

The UI needs a general review of buttons, menus, etc where there is text. There are many areas where text is not centered properly mostly vertically. In some cases horizontally as well. For example consider these two buttons on the cluster view:
![image](https://user-images.githubusercontent.com/45179589/49611736-b6ddd200-f95f-11e8-8f8d-2a08a97a46bb.png)

Notice the underscore under the > is way off center horizontally and the text doesn't quite seem centered in the light blue area of the buttons. There are many little things like this throughout the UI.

Another example from Catalogs page the Delete button text is too high vertically and is therefore not vertically centered. Also overall this and the icon do not look horizontally centered
![image](https://user-images.githubusercontent.com/45179589/49611807-f4425f80-f95f-11e8-839f-ae5d1693bf9d.png)

**Comment by davidnuzik** [comment]
@lvuch the Delete button appears to be fixed but the issues remain on cluster details page:
![image](https://user-images.githubusercontent.com/45179589/50665562-5a75ce80-0f6e-11e9-92ac-8f6c5afb04a4.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/2630
![screen shot 2019-02-06 at 10 22 26 am](https://user-images.githubusercontent.com/3013118/52360411-2c662d00-29f9-11e9-8cc9-1dfcfa227ba3.png)

**Comment by davidnuzik** [comment]
@lvuch Icon before "Launch kubectl" is still not fixed. Would you like a separate issue?
![image](https://user-images.githubusercontent.com/45179589/52371263-45c7a300-2a12-11e9-8023-9183dfd9c3f0.png)

**Comment by cjellick** [comment]
@davidnuzik if you kick an issue back, you have to remove the resolved label and add the reopened label

**Comment by lvuch** [comment]
Icon fixed in this pr to the icon repo https://github.com/rancher/icons/pull/22

**Comment by davidnuzik** [comment]
Thanks. The issue is fixed.

Version: Master 2.2 (2/21/19)
Confirmed the remaining issue is resolved:
![image](https://user-images.githubusercontent.com/45179589/53186178-bac3dc80-35bd-11e9-92ea-d32b2c560bd9.png)

The UI also got another general review of buttons/alignment and I did not spot any noticeable issues.
