### ISSUE TITLE
Alerts for "controller manager and scheduler unavailable" are not functional

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#16937]
Rancher Version: Master build from Dec 6th

Steps:

1. Create a DO cluster with two control nodes , 1 etcd and 1 worker nodes.
2. Enable monitoring
3. Set notifier for the alerts
4. Power OFF one control node. 

The alert for controller-manager and scheduler unavailable are not triggered.
Note: Control node has controller-manager and scheduler containers.

**Comment by loganhz** [comment]
This issue is not introduced with the monitoring feature. Move it out to 2.2
