### ISSUE TITLE
Failed to generate kube-etcd certificate: x509: cannot parse IP address of length 0

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#16934]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Attempt to update a Rancher-provisioned RKE cluster in bad state, and find this error message appear.

Internal: For steps on fully reproducing this, please contact me.

**Result:**
Cluster is unable to update.

**Other details that may be helpful:**
Relevant Rancher logs are:
```
2018/12/06 23:54:04 [INFO] Provisioning cluster [c-9qsrj]
2018/12/06 23:54:04 [INFO] Updating cluster [c-9qsrj]
2018/12/06 23:54:04 [INFO] cluster [c-9qsrj] provisioning: Building Kubernetes cluster
2018/12/06 23:54:04 [INFO] cluster [c-9qsrj] provisioning: [dialer] Setup tunnel for host [172.31.36.194]
2018/12/06 23:54:04 [INFO] cluster [c-9qsrj] provisioning: [dialer] Setup tunnel for host [172.31.44.234]
2018/12/06 23:54:05 [INFO] cluster [c-9qsrj] provisioning: [dialer] Setup tunnel for host [172.31.36.151]
2018/12/06 23:54:06 [INFO] cluster [c-9qsrj] provisioning: [dialer] Setup tunnel for host [172.31.42.3]
2018/12/06 23:54:06 [INFO] cluster [c-9qsrj] provisioning: [state] Found local kube config file, trying to get state from cluster
2018/12/06 23:54:06 [INFO] cluster [c-9qsrj] provisioning: [state] Fetching cluster state from Kubernetes
2018/12/06 23:54:06 [INFO] cluster [c-9qsrj] provisioning: [state] Successfully Fetched cluster state to Kubernetes ConfigMap: cluster-state
2018/12/06 23:54:06 [INFO] cluster [c-9qsrj] provisioning: [certificates] Getting Cluster certificates from Kubernetes
2018/12/06 23:54:06 [INFO] cluster [c-9qsrj] provisioning: [certificates] Successfully fetched Cluster certificates from Kubernetes
2018/12/06 23:54:06 [INFO] cluster [c-9qsrj] provisioning: [certificates] Regenerating new etcd-172.31.36.151 certificate and key
2018/12/06 23:54:07 [ERROR] ClusterController c-9qsrj [cluster-provisioner-controller] failed with : Failed to generate kube-etcd certificate: x509: cannot parse IP address of length 0
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1, 2.1.2, 2.1.3, other versions could be affected
- Installation option (single install/HA): single node/HA

As of now, it looks like the reason why RKE is re-generating certs for etcd is due to the certificate secret being empty. It's possible to get around this by re-creating the secret for the missing etcd certificates on the downstream cluster.

**Comment by Oats87** [comment]
Potentially related: https://github.com/rancher/rke/issues/947

**Comment by alena1108** [comment]
With _rke_ refactoring, the issue should be fixed on master.

**Comment by bmdepesa** [comment]
The etcd cert is now stored within etcd (cluster.rkestate) rather than as a secret. After refactoring in master, this use case is no longer valid and will not be tested.
