### ISSUE TITLE
Pipelines with gitlab not working

### ISSUE THREAD

**Issue by n13101** [rancher/rancher#16935]
*Describe your issue here*
When setting up a gitlab application in rancher pipelines the verify hangs and does not return.  The verification never completes - just displays "creating"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`authenticated.project.pipeline.settings`|

**Comment by gitlawr** [comment]
Do you see any abnormal information in browser console or rancher server logs?
