### ISSUE TITLE
Edit alert screen for nodes, etcd, events always has "scheduler" selected by default

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#16936]
Rancher Version: Master build from Dec 6th

Steps:
1. Create a DO cluster, enable monitoring
2. The default alerts for etcd, nodes, etcd, events are displayed.
3. Edit alert for nodes, etcd, events etc.
 Edit screen always displays "scheduler" by default.

Example:
<img width="1376" alt="screen shot 2018-12-06 at 4 20 15 pm" src="https://user-images.githubusercontent.com/18536626/49619767-db8f7500-f972-11e8-92aa-cf1d687b3987.png">
<img width="1377" alt="screen shot 2018-12-06 at 4 20 53 pm" src="https://user-images.githubusercontent.com/18536626/49619774-ecd88180-f972-11e8-9943-a6ba78ddaebe.png">

The fields which are not relevant to that alert should be disabled

**Comment by tfiduccia** [comment]
Version - 2.2 master 12/7
Verified fixed
