### ISSUE TITLE
Multiclusterapp answers override is not working

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#16941]

**Comment by alena1108** [comment]
@kinarashah could you please check if it is still the issue

**Comment by kinarashah** [comment]
both cluster and project answer override works in latest master, @bmdepesa could you please test this as a part of test plan too?

**Comment by bmdepesa** [comment]
This is not functioning in rancher/rancher:master (pulled 1/28). 

* Deployed MC app to 3 clusters - Docker registry w/ nodeport default of 30000
* Override answer for cluster 1 for all projects (cluster level override) - nodeport 30001
* Override answer for cluster 2 - one project - nodeport 30002
* Override answer for cluster 3 - one project - nodeport 30003

The nodeport answer for all apps in each cluster/project is set to 30003. 

API for the deployed multicluster app shows clusterId & projectId empty for answers:
<img width="585" alt="screen shot 2019-01-28 at 12 46 35 pm" src="https://user-images.githubusercontent.com/21316915/51864358-cc88cb80-2300-11e9-8cbc-6f052df1a379.png">

API for each app in each project -- answer shows:
<img width="629" alt="screen shot 2019-01-28 at 1 30 41 pm" src="https://user-images.githubusercontent.com/21316915/51864444-00fc8780-2301-11e9-8220-f0f20c0f2d1a.png">

**Comment by kinarashah** [comment]
Looks like UI is not sending the correct values, it just ends `null` all the time. 
Works on trying with just API - 
- created multi cluster app with just few targets
- in api, clicked on edit and added answer in the form of 
```
{"clusterId":"local","projectId":"local:p-thrxb","type":"/v3/schemas/answer","values":{"adminPassword":"system"}}
```
- multi cluster app got upgraded as expected, 
![image](https://user-images.githubusercontent.com/16870565/51888722-19de5a80-234c-11e9-9bba-c5446c5fe540.png)
- the app got upgraded correctly as well 
![image](https://user-images.githubusercontent.com/16870565/51888760-3a0e1980-234c-11e9-8046-da565cd6b972.png)

**Comment by westlywright** [comment]
thi is a UI bug @kinarashah I am working on resolving it now

**Comment by bmdepesa** [comment]
rancher/rancher:master 1/30

The answer overrides are set correctly when creating the multicluster app, but when upgrading the multicluster app, the answer overrides area shows 0 answers. 

clusterId is `null` in the API as well:

![screen shot 2019-01-30 at 3 07 09 pm](https://user-images.githubusercontent.com/21316915/52016045-c7628280-24a0-11e9-9962-6f278494e9cb.png)
![screen shot 2019-01-30 at 3 07 28 pm](https://user-images.githubusercontent.com/21316915/52016051-ca5d7300-24a0-11e9-9fd9-51930779bc11.png)

**Comment by westlywright** [comment]
@bmdepesa i'll have to investigate why they are not showing up, they were for me on upgrades when I was working on this yesterday. Can you message me the catalog item you are using? 

The `clusterId` will be null unless you select the `all projects on cluster option` from the scope drop down. `clusterId` and `projectId` are mutually exclusive for answer overrides.

**Comment by bmdepesa** [comment]
rancher/rancher:master 1/31
UI - latest2 / 2.2.1

Answers are displaying correctly when upgrading the MCA.
