### ISSUE TITLE
Alert for "etcd member has no leader " presents too many irrelevant options in edit screen

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#16945]
Rancher version: master

Steps:
1. Create cluster and enable monitoring using Prometheus
2. Alerts for etcd, nodes become available.
3. Edit the alert "Etcd member has no leader" 
It presents with too many options where as we can have only one etcd leader in a cluster.
If the cluster quorum is broken, there will not be a leader. 
Alert should be sent when the number of leaders is not equal to 1.

<img width="1369" alt="screen shot 2018-12-06 at 5 00 25 pm" src="https://user-images.githubusercontent.com/18536626/49622265-b48a7080-f97d-11e8-8052-64187cea303c.png">

**Comment by loganhz** [comment]
Changed to `not equal to 1`

**Comment by soumyalj** [comment]
Tested with master build from Dec 7th. Edit for alert "etcd member has no leader " has the expression `not equal to 1` set  by default as below :
<img width="1238" alt="screen shot 2018-12-07 at 11 15 55 am" src="https://user-images.githubusercontent.com/18536626/49668015-bdc51d00-fa11-11e8-9d5a-469f54e0e863.png">

**Comment by soumyalj** [comment]
This issue will be open as the irrelevant options will be removed at a later point.
