### ISSUE TITLE
Editing Alert Group or individual alert, sets Target back to System Service

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#16943]
Version - 2.2 master 12/6

**Steps to reproduce (least amount of steps as possible):**
1.  Create a node alert.
2.  Edit the alert group or the alert

**Result:**  Sets it to System Service alert.  In the Alert Group, it sets all alerts to System Service.

**Comment by n313893254** [comment]
The bug is the same as https://github.com/rancher/rancher/issues/16936

**Comment by tfiduccia** [comment]
Version - 2.2 master 12/7
Verified fixed
