### ISSUE TITLE
Pods Column Does Not Sort Numerically

### ISSUE THREAD

**Issue by docmagic** [rancher/rancher#16944]
On the Nodes page, the Pods column does not sort numerical. Since the display is something like 11/110 rather than a pure number the UI sorts this textually. Therefore, it is not possible to accurately sort the nodes by which ones have the most or the least pods running.

For example, when sorting least to greatest, 11/110 sorts before 9/110 even though 11 is numerically higher than 9.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.3` UI: `v2.1.17` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/2
Verified fixed
