### ISSUE TITLE
Rancher server reboots multiple times

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16948]
Rancher server version - Build from master - Dec 6
```
root@santestservernew:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rancher/rancher     master              718cac8deaf9        2 hours ago         448MB
root@santestservernew:~# 
root@santestservernew:~# date
Fri Dec  7 02:57:32 UTC 2018
```

Steps to reproduce the problem:
Have 3 clusters - DO, ec2 and Azure clusters with few workloads in them.
 
Noticed that rancher server reboots multiple times in the 2 hours it has bee installed.

Encountered issues like getting "server error" when trying to log in or failure when trying to create workloads .

<img width="1289" alt="screen shot 2018-12-06 at 5 51 16 pm" src="https://user-images.githubusercontent.com/4266958/49625138-24522880-f989-11e8-986c-5114a9f0b75c.png">

root@santestservernew:~# docker ps
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS                                      NAMES
81a68665f793        rancher/rancher:master   "entrypoint.sh"     2 hours ago         Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   vibrant_almeida

```
root@santestservernew:~# docker inspect 81a | grep -i restart
            "Restarting": false,
        "RestartCount": 9,
            "RestartPolicy": {
root@santestservernew:~# 
```

Seems like restart of rancher sever is got to do with garbage collection and acquiring new lease fr kube-system/kube-scheduler.

```
```I1207 01:53:47.503411       7 controller_utils.go:1034] Caches are synced for garbage collector controller
I1207 01:53:47.503440       7 garbagecollector.go:142] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
I1207 01:53:47.539680       7 controller_utils.go:1034] Caches are synced for garbage collector controller
2018-12-07 01:53:47.823041 W | etcdserver: 80% of the file descriptor limit is used [used = 968, limit = 1024]
I1207 01:53:50.269556       7 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
```

```
root@santestservernew:~# grep "successfully acquired lease kube-system/kube-scheduler" mylogsnew
I1207 01:01:12.370335       8 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 01:29:46.616694       7 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 01:51:18.070246       8 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 01:52:21.444880       8 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 01:53:50.269556       7 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 02:45:24.029955       8 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 02:49:54.005652       8 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 02:51:25.824954       8 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 02:52:58.211334       8 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
I1207 02:54:00.423327       9 leaderelection.go:196] successfully acquired lease kube-system/kube-scheduler
root@santestservernew:~# date
```

**Comment by cjellick** [comment]
The number of allowed open files is very low (1024) in this setup. Docker was installed via ubuntu snap, which appears to be controlling this ulimit setting. TCP connections count towards the # of open files and rancher by its nature opens a lot of those, especially when running in non-HA mode where you have to also count the k8s and etcd connections. 
We can close this as not a bug because the ulmit setting is way too low.

**Comment by sangeethah** [comment]
Closing this issue. This issue is not seen in setups that have bigger ulimit settings for rancher-server process.
