### ISSUE TITLE
Importing RKE built cluster into rancher

### ISSUE THREAD

**Issue by sbavi2** [rancher/rancher#16959]
Rancher | v2.1.1
User Interface | v2.1.4
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1

Docker version:
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-84.git07f3374.el7.centos.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Fri Nov 30 02:48:45 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-84.git07f3374.el7.centos.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Fri Nov 30 02:48:45 2018
 OS/Arch:         linux/amd64
 Experimental:    false

OS: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Build rancher HA cluster in 3 centos vm's. Created a self signed CA. Created a secret and used it when configuring the rancher cluster using helm. All good so far. I could see the rancher site up and running. local cluster is Active. 

Using RKE created another application cluster on another 3 centos vm's. Now trying to add it to rancher using the certs I created while configuring rancher HA.

Stuck in provisioning...
Pending. Waiting for full cluster configuration.

**Comment by superseb** [comment]
Please provide exact steps and commands used as there is no way to reproduce given the current instructions. For self signed CA you need `--set privateCA=true` and need to add all secrets mentioned on https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/tls-secret/.

The logs of the agents launched to connect to the cluster can be retrieved using:

```
kubectl -n cattle-system logs -l app=cattle-agent
kubectl -n cattle-system logs -l app=cattle-cluster-agent
```

Usually it's unable to connect to the configured `server-url` (https://rancher.com/docs/rancher/v2.x/en/installation/references/) or certificates are incomplete/wrongly configured.

**Comment by sbavi2** [comment]
Teared down the rancher cluster and dev app cluster. Rebuilt with latest rke. Ran the below instructions still the same issue.

On Rancher Cluster:
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
./helm init --service-account tiller
kubectl -n kube-system  rollout status deploy/tiller-deploy
kubectl create namespace cattle-system
kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key
kubectl -n cattle-system create secret generic tls-ca --from-file=cacerts.pem
./helm version
./helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
./helm install rancher-stable/rancher --name rancher --namespace cattle-system --set hostname=rancherweb --set ingress.tls.source=secret --set privateCA=true

On Dev Cluster:
curl -vk --key tls.key --cert tls.crt -sfL https://rancherweb/v3/import/ngxm6hkgnmkt8tdj2nfsgn5bbnt4wf4fhwhl92c4xzq2bnc98578nf.yaml | kubectl apply -f -

tls.crt has cert + root 

kubectl -n cattle-system logs -l app=cattle-agent:
time="2018-12-07T20:43:17Z" level=info msg="Rancher agent version v2.1.3 is starting"
time="2018-12-07T20:43:17Z" level=info msg="Option etcd=false"
time="2018-12-07T20:43:17Z" level=info msg="Option controlPlane=false"
time="2018-12-07T20:43:17Z" level=info msg="Option worker=false"
time="2018-12-07T20:43:17Z" level=info msg="Option requestedHostname=192.168.1.33"
time="2018-12-07T20:43:17Z" level=info msg="Listening on /tmp/log.sock"
time="2018-12-07T20:43:17Z" level=info msg="Option customConfig=map[address:192.168.1.33 internalAddress: roles:[] label:map[]]"
time="2018-12-07T20:43:18Z" level=info msg="Connecting to wss://rancherweb/v3/connect with token wrn24j5sh9lbphfddwgtfn7kvkwdcbzs4j7rnvr6d8x6m7znxr7kq7"
time="2018-12-07T20:43:18Z" level=info msg="Connecting to proxy" url="wss://rancherweb/v3/connect"
time="2018-12-07T20:43:18Z" level=info msg="Starting plan monitor"
time="2018-12-07T20:43:14Z" level=info msg="Rancher agent version v2.1.3 is starting"
time="2018-12-07T20:43:14Z" level=info msg="Option customConfig=map[internalAddress: roles:[] label:map[] address:192.168.1.32]"
time="2018-12-07T20:43:14Z" level=info msg="Option etcd=false"
time="2018-12-07T20:43:14Z" level=info msg="Option controlPlane=false"
time="2018-12-07T20:43:14Z" level=info msg="Option worker=false"
time="2018-12-07T20:43:14Z" level=info msg="Option requestedHostname=192.168.1.32"
time="2018-12-07T20:43:14Z" level=info msg="Listening on /tmp/log.sock"
time="2018-12-07T20:43:14Z" level=info msg="Connecting to wss://rancherweb/v3/connect with token wrn24j5sh9lbphfddwgtfn7kvkwdcbzs4j7rnvr6d8x6m7znxr7kq7"
time="2018-12-07T20:43:14Z" level=info msg="Connecting to proxy" url="wss://rancherweb/v3/connect"
time="2018-12-07T20:43:14Z" level=info msg="Starting plan monitor"
time="2018-12-07T20:43:17Z" level=info msg="Rancher agent version v2.1.3 is starting"
time="2018-12-07T20:43:17Z" level=info msg="Option customConfig=map[internalAddress: roles:[] label:map[] address:192.168.1.31]"
time="2018-12-07T20:43:17Z" level=info msg="Option etcd=false"
time="2018-12-07T20:43:17Z" level=info msg="Option controlPlane=false"
time="2018-12-07T20:43:17Z" level=info msg="Option worker=false"
time="2018-12-07T20:43:17Z" level=info msg="Option requestedHostname=192.168.1.31"
time="2018-12-07T20:43:17Z" level=info msg="Listening on /tmp/log.sock"
time="2018-12-07T20:43:17Z" level=info msg="Connecting to wss://rancherweb/v3/connect with token wrn24j5sh9lbphfddwgtfn7kvkwdcbzs4j7rnvr6d8x6m7znxr7kq7"
time="2018-12-07T20:43:17Z" level=info msg="Connecting to proxy" url="wss://rancherweb/v3/connect"
time="2018-12-07T20:43:17Z" level=info msg="Starting plan monitor"

kubectl -n cattle-system logs -l app=cattle-cluster-agent:
INFO: Environment: CATTLE_ADDRESS=10.42.0.4 CATTLE_CA_CHECKSUM=da5a8565ddd088c8f2adfaae957d585a638e41e12434a59df10e7f054a8a7922 CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-6585657c96-bqpxs CATTLE_SERVER=https://rancherweb
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
ERROR: https://rancherweb/ping is not accessible (Could not resolve 
host: rancherweb)

I see the catle agent keeps crashing and restarting all the time.

![image](https://user-images.githubusercontent.com/13546918/49672146-6f227d80-fa27-11e8-9481-b7ea5856f767.png)

![image](https://user-images.githubusercontent.com/13546918/49672175-86fa0180-fa27-11e8-9895-c462a4bacfb3.png)

**Comment by superseb** [comment]
Configured `server-url` has to be a DNS resolvable name, not a workaround via `/etc/hosts`.

**Comment by superseb** [comment]
Let me know if this doesn't solve the issue.
