### ISSUE TITLE
Monitoring - Grafana chart for workloads/pods/containers  not provided to cluster member/project member/project owners when cluster level monitoring is enabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16951]
Rancher server version - Build from master - Dec 6

Steps to reproduce the problem:
Enable AD auth.
Create a cluster and have prometheus monitoring enabled as cluster level.
Create a project -p1 and deploy workloads in this project.

Add  user1 as cluster member to this cluster.
Add user2 as project member to p1.
Add user3 as project owner to p1.
Add user4 as cluster owner to p1.

When logged in as  user1/user2/ user3 , Grafana chart for workloads under project p1 is not presented to the user.

Only when  logged in as  user4 (cluster owner ) , Grafana chart for workloads under project p1 is presented to the user.

**Comment by thxCode** [comment]
@sangeethah , If enabling `p1` project-level monitoring, you can see the Grafana which only belong to `p1`.

**Comment by sangeethah** [comment]
@thxCode Just like cluster owner is able to see the Grafana charts for workloads in all the projects under the cluster ,  cluster member/project member/project owners should be able to see it without having to enable monitoring at the project level.

**Comment by cjellick** [comment]
@thxCode is write. this is by design

**Comment by sangeethah** [comment]
Closing this issue as per the comments from @thxCode and @cjellick
