### ISSUE TITLE
Monitoring - grafana with persistent storage fails to start with CrashLoopBackOff

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#16953]
rancher/rancher:master
rancher/server-chart:master
k8s v1.12.3
ec2 w/ cloud provider

**To reproduce:**
* Enable prometheus monitoring with persistent storage enabled for grafana
* grafana container fails to start with: 
`CrashLoopBackOff: Back-off 1m20s restarting failed container=grafana pod=grafana-cluster-monitoring-66576b8ffc-ct49r_cattle-prometheus(6c8d21c8-f9d5-11e8-921b-06b3c373602c)`

**Expected:**
* grafana container starts successfully 

grafana container logs:
```
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
```

**Additional info:** 
* grafana without persistent storage starts successfully
* prometheus persistent storage is functional

**Comment by bmdepesa** [comment]
rancher/rancher:master 12/7
HA installation via helm

Grafana pod still crashes with the same error: 
```
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
```

In catalog app configuration, I see the changes made in the merged commit.

**Comment by loganhz** [comment]
Thanks. We will look at it again.

**Comment by bmdepesa** [comment]
rancher/rancher:master 12/7

grafana is able to launch with persistent storage enabled. 

* Installed rancher/rancher:master
* Created ec2 cluster w/ cloud provider
* Created storage class for EBS volumes
* Enabled monitoring w/ persistent storage for grafana & prometheus
* Both catalog apps & all workloads started successfully.
