### ISSUE TITLE
UI show undefined threshold value when set threshold to zero in metric alert

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#16958]
This happened in dev and should not happen after v2.2.0-alpha4

When the threshold value is zero, the threshold value in the UI show undefined

![image](https://user-images.githubusercontent.com/5936271/49640858-9427e800-fa49-11e8-94f1-b175cc2a712f.png)

**Comment by kingsd041** [comment]
Version: master 2.2 (2/20/19)  Image ID: 46f4b03ba30e
Confirmed fix.
![image](https://user-images.githubusercontent.com/19684717/53072023-dfb54280-351e-11e9-8554-3b0f08f16cab.png)
