### ISSUE TITLE
Grafana, Kiali, Jaeger links not showing up for EKS

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#16968]
Version: master 2.2 (12/7/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Set up EKS cluster and enable monitoring
- Once it is ready notice there are no grafana links on the cluster monitoring screen. There are also none for projects, workloads, pods,containers, etc areas.
Screenshot showing cluster monitoring page grafana links missing:
![image](https://user-images.githubusercontent.com/45179589/49664655-b8ff6980-fa0f-11e8-8834-847f1ff6cd39.png)

**Result:**
No grafana links when using EKS

**Additional Information:**
Based on discussions it seems like this might be a K8s issue. Only 1.12.3 seemed to work for showing the grafana links. This is likely an issue with the k8s proxy not being able to access grafana.

**Comment by davidnuzik** [comment]
GKS is not affected (Soumya tested)

**Comment by loganhz** [comment]
This is a backend issue. It works well in GKE and other hosted k8s

Now Rancher UI use the k8s proxy to access Grafana via `/k8s/clusters/${cluster-id}/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/`

It looks like only `kubernetes-dashboard` is accessible with k8s proxy `/k8s/clusters/${cluster-id}/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:443/proxy/`

I tried to create a nginx workload, and create a service, and try to access nginx via `/k8s/clusters/c-62mzm/api/v1/namespaces/default/services/http:abc:80/proxy/`

it works well in a `1.12.3` cluster but it doesn’t work in `v1.10.11-eks` (edited)

**Comment by jiaqiluo** [comment]
The bug still exists on rancher: master 1/29
The Garafa icon is missing for both cluster and project level monitoring
![screenshot](https://user-images.githubusercontent.com/6218999/51947181-2eb8fd80-23e1-11e9-938f-a6fc3bbcacd5.png)

**Comment by jiaqiluo** [comment]
The bug also exists in the HA install mode

Rancher: master on 2/26
Cluster: EKS
<img width="1562" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53514836-e21b1d80-3a85-11e9-8f34-a7fa2d72d434.png">

**Comment by vikas027** [comment]
I am too seeing this in Rancher v2.2.1 in an imported EKS cluster

**Comment by loganhz** [comment]
@vikas027 Current workaround is  find `access-grafana` in system project service discovery tabs.
And look at what `access-grafana` does and  create another node port service to expose Grafana UI via node port.

**Comment by loganhz** [comment]
@vikas027 you can add the service in UI
![image](https://user-images.githubusercontent.com/21168270/55530092-380f6080-56d7-11e9-9893-47f0891d9f17.png)

**Comment by Ilya-Kuchaev** [comment]
It doesn't work
Still get 503 when UI trys to access https://<rancher_url>/k8s/clusters/<cluser_id>/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/api/search
```
Error: 'dial tcp 10.42.1.67:80: i/o timeout'
Trying to reach: 'http://10.42.1.67:80/api/search'
```

**Comment by loganhz** [comment]
Can you access the newly created node port service? Something like node ip:node port

Is there a public ip on the node? 

https://<rancher_url>/k8s/clusters/<cluser_id>/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/api/search won't work in EKS

https://github.com/rancher/rancher/issues/16968#issuecomment-445504120

**Comment by Ilya-Kuchaev** [comment]
Yes. I can access Grafana UI via the new Node Port.  But the Rancher's Cluster UI still lacks its links. However, the metrics are functional

<img width="1274" alt="Screenshot 2019-04-04 at 11 15 58" src="https://user-images.githubusercontent.com/897428/55540168-10b29680-56cb-11e9-9938-4b08c45940aa.png">

The cluster is a custom bare metal cluster with two nodes - 1 for management components and 1 for the worker.

**Comment by loganhz** [comment]
Ok, I thought you were using EKS.

Please don't do https://github.com/rancher/rancher/issues/16968#issuecomment-479739400 if it is a custom cluster. If you did, please revert it.

Can you deploy a busybox on each node to check if `access-grafana:80` is accessable ?

**Comment by Ilya-Kuchaev** [comment]
Nope. But the issue is the same.
And yes, access-grafana:80 is accessible. Even via the full notation (access-grafana.cattle-prometheus.svc.cluster.local) from outside the cattle-prometheus namespace.

**Comment by loganhz** [comment]
So it's not just `access-grafana` service. 
I think maybe for a simple nginx service, you still can not use `https://<rancher_url>/k8s/clusters/<cluser_id>/api/v1/namespaces/${ns}/services/http:nginx:80/proxy/`

I never hit it in a custom cluster. Is there anything special in your setup?

**Comment by Ilya-Kuchaev** [comment]
Yes. That's strange. Because I have two clusters configured via the same rancher. One custom cluster is fully functional and the second has this issue. Nothing special I believe. Except the second one had  Prometheus installed via Helm before the upgrade to 2.1.

**Comment by vikas027** [comment]
Yeah, same for me. I have three clusters as of now all behaving differently

- Imported k3s Cluster - running fine
- Created EKS Cluster - Showing Nothing
- Imported EKS Cluster - Message `Monitoring API is not ready`

**Comment by loganhz** [comment]
@vikas027 

> Created EKS Cluster - Showing Nothing

This is the known issues . Please try https://github.com/rancher/rancher/issues/16968#issuecomment-479747800 to use node port to access it

> Imported EKS Cluster - Message Monitoring API is not ready

Please go to System project and look at the workloads under cattle-prometheus namespaces. I think they cannot fully start up. It will be good if you can provide the screenshot for the workloads page of the System project

**Comment by vikas027** [comment]
Hey @loganhz ,

I did try doing the same in vain. 
![2019-04-06_00-53-53](https://user-images.githubusercontent.com/6998650/55632673-7ce5e500-5806-11e9-8876-b69ba2567464.png)

**Comment by vikas027** [comment]
Thanks for the all the help @loganhz  Finally, I was able to see the graphs, not from the Rancher UI though. Creating a vhost and pointed to `access-grafana` service worked fine.

**Comment by wreed4** [comment]
@loganhz I tried following the workaround you suggested, but still don't see the links.  I'm on the EKS cluster on which I installed rancher in HA configuration (via helm).  I enabled metrics, but added a node selector so that they only run on the private subnet.  Is that not going to work?  Rancher has no such nodeSelector, though I intended to add one.

**Comment by lbogdan** [comment]
(Potential) Solution here: https://github.com/rancher/rancher/issues/19740#issuecomment-486657688 .

**Comment by supermiguel** [comment]
> @vikas027 you can add the service in UI
> ![image](https://user-images.githubusercontent.com/21168270/55530092-380f6080-56d7-11e9-9893-47f0891d9f17.png)

For me this works... is there a way to add this to a link so is easy to click?

**Comment by vikas027** [comment]
@supermiguel I don't have that cluster now. Give me some time, I will try to replicate the issue.

**Comment by gitlawr** [comment]
As @lbogdan  stated, the cause is that the default security group blocks the proxy traffic.

In short,
1. Find security groups for your EKS cluster in `AWS EKS console - cluster detail page - Networking session`
2. Edit outbound rules of ControlPlaneSecurityGroup so that it allows port range `0-65535`(the default is `1025-65535`) to WorkerSecurityGroup
3. Edit inbound rules of WorkerSecurityGroup so that it allows port range `0-65535` to ControlPlaneSecurityGroup

After that, you will be able to see those links in the UI.

Per AWS [documentation](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html):
>To allow proxy functionality on privileged ports or to run the CNCF conformance tests yourself, you must edit the security groups for your control plane and the worker nodes. The security group on the worker nodes' side needs to allow inbound access for ports 0-65535 from the control plane, and the control plane side needs to allow outbound access to the worker nodes on ports 0-65535.

**Comment by mohag** [comment]
Fixing the CloudFormation templates you use to deploy the nodes is likely the most reliable solution. In the Amazon supplied one, search for "1025" and replace that with a number <= 80 to get this working

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/9/19)

This primarily changes the NodeSecurityGroup such that inbound port 80 is open now. If you have Rancher automatically set up the SG for you port 80 is now open. Reference https://github.com/rancher/kontainer-engine/pull/175

I can now see Grafana links for monitoring and visit the links without any issues; I also enabled istio and ensured I can also access Istio Grafana, Kiali, Jaeger, Prometheus UIs without any issues.

SG before (rancher v2.2.7 used to check):
![image](https://user-images.githubusercontent.com/45179589/62806992-1e2cc280-baa9-11e9-86a9-7cab5203bf79.png)

SG after the change:
![image](https://user-images.githubusercontent.com/45179589/62806999-2258e000-baa9-11e9-8b1c-69ed0f59b349.png)

Note: I checked the documentation and it already mentions inbound port 80 needed for nodes so no need for any documentation update. https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ (networking tab)

**Comment by arbujsiddharth** [comment]
> 
> 
> The bug still exists on rancher: master 1/29
> The Garafa icon is missing for both cluster and project level monitoring
> ![screenshot](https://user-images.githubusercontent.com/6218999/51947181-2eb8fd80-23e1-11e9-938f-a6fc3bbcacd5.png)

Hello All,
I am facing the same issue in Rancher 2.2.4 version. 
I edited ControlPlaneSecurityGroup 1025-65535 to 0-65535 for WorkerSecurityGroup. But no luck. Has anyone found a solution? Appreciate help. Thanks.

**Comment by fmunteanu** [comment]
I confirm opening **only port 80** between cluster and workers allows the Grafana stats to be visible in Rancher 2.2.8.

**Comment by chad-barensfeld-exa** [comment]
Experiencing the same issue with imported GKE cluster

**Comment by eramirez51** [comment]
I have same issue in GKE cluster

**Comment by davidnuzik** [comment]
@chad-barensfeld-exa and @eramirez51 can you both confirm port 80 is open? See https://github.com/rancher/rancher/issues/16968#issuecomment-520054816
