### ISSUE TITLE
Question: add extra volume mounts for kubernetes components (kubelet)

### ISSUE THREAD

**Issue by slimee** [rancher/rancher#16965]
Hi,

How to add, while creating a cluster, extra volume mounts for kubernetes components (kubelet)?

Thanks

**Comment by superseb** [comment]
Please see https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file and https://rancher.com/docs/rke/v0.1.x/en/example-yamls/.

Let me know if it doesn't work.
