### ISSUE TITLE
Cannot see default Grafana dashboards

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16962]
rancher/rancher:master 12/06

Steps:

1. Turn on Grafana PV
2. Login Grafana and change the default password
3. Remove the Grafana pod manually
4. Wait for pod re-create
5. Login Grafana 

Result:

There is no dashboard in the Grafana. There is no default dashboards

Workaround:

Find the grafana secret in secrets page and change it to the updated password.

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: mater 2/13
Rancher Single Install, DO cluster 

Step:
- deploy Longhorn as the storage class
- turn on the cluster monitoring with  setting Grafana PV to on and default
- after the `cluster-monitoring` is active, click the link to Grafana's homepage
- click the icon on the left bottom of the page to log in and change the password
- remove the Grafana pod manually
- wait for Grafana back to be active, click the link to Grafana's homepage

Result:
- Log in successfully with the changed password. 
- All dashboards are preserved.
