### ISSUE TITLE
App: drone return error when Bitbucket is selected

### ISSUE THREAD

**Issue by SteeveGL** [rancher/rancher#16964]
Installing **App: drone** from the Library. Selecting **Bitbucket** give me this error:

Failed to install app drone. Error: YAML parse error on drone/templates/deployment-server.yaml: error converting YAML to JSON: yaml: line 29: could not find expected ':'

Steps:
- In Catalog, select Drone from the Library
- In Drone Integration Server, select Bitbucket
- Fill the forms Bitbucket OAuth2 Client ID and Bitbucket OAuth2 Client Secret
- Click Launch
- Click on the App Drone while installing
- The error message: Failed to install app drone. Error: YAML parse error on drone/templates/deployment-server.yaml: error converting YAML to JSON: yaml: line 29: could not find expected ':'

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.3` UI: `v2.1.17` |
|Route|`catalog-tab.launch`|

**Comment by somq** [comment]
Same error with gogs

**Comment by guangbochen** [comment]
addressed in the https://github.com/rancher/charts/pull/88.
