### ISSUE TITLE
Monitoring - Project custom and read-only member cannot see Grafana icon on workload/pod/container

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16967]
Bug.

Rancher master on 12/7

Steps:
- logged in as admin to create a new project and enable the project level monitoring 
- deployed several workloads in the project
- added several Github users to the project as different roles: project member, project read-only member, project custom member with permission to view workloads
- logged in as those users to check workload under the project

Result:
All of them can click a workload and see its detailed page, but 
- the project member can see Grafana icon on workload/pod/container
- the project read-only member cannot see Grafana icon on workload/pod/container 
- the project custom member cannot see Grafana icon on workload/pod/container 

Expected result:
All three kinds of project members should be able to see Grafana icon 

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by loganhz** [comment]
`kubectl describe clusterrole view`
![image](https://user-images.githubusercontent.com/21168270/50884926-3bbc7f80-1427-11e9-829f-a8b39a664273.png)

`kubectl describe clusterrole edit`
![image](https://user-images.githubusercontent.com/21168270/50884963-55f65d80-1427-11e9-94e3-60eab906c1ee.png)

The base role of read-only is the default kubernetes role view. `services/proxy` is not in the role.

**Comment by cjellick** [comment]
We are not going to give read-only users access to service/proxy.

**Comment by loganhz** [comment]
Added the permission for Manage Service role. Custom users with Manage Service role will be able to see the Grafana icon

**Comment by jiaqiluo** [comment]
Validated on Rancher: master 1/21

Steps:
- logged in as admin to create a new project and enable the project level monitoring
- deployed several workloads in the project
- added several Github users to the project as different roles: project member, project read-only member, project custom member with permission to view workloads
- logged in as those users to check workload under the project

Result:

- the project member **can** see Grafana icon on workload/pod/container
- the project read-only member **cannot** see Grafana icon on workload/pod/container
- the project custom member **cannot** see Grafana icon on workload/pod/container
- the project custom member with `manage service` role **can** see Grafana icon on workload/pod/container

Note:
Since the design is changed, the expected result described in the original ticket is not accurate. So do not be confused when going through the conversion. 
The result of this validation reflects the latest design properly.
