### ISSUE TITLE
Monitoring - Project member can enable/disable project-level monitoring

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16978]
Bug.

Rancher master on 12/7

Expected: 

- Project owner **can** enable/disable monitoring on project level
- project member **cannot** enable/disable monitoring on project level
- project custom member **cannot** enable/disable monitoring on project level
- project read-only member **cannot** enable/disable monitoring on project level

Related issue:
https://github.com/rancher/rancher/issues/16888
https://github.com/rancher/rancher/issues/16889

**Comment by jiaqiluo** [comment]
The big fix is validated on master 1/4

The following cases are validated:
- project member **cannot** enable/disable monitoring on project level
- project custom member **cannot** enable/disable monitoring on project level
- project read-only member **cannot** enable/disable monitoring on project level

Wait for the response from @thxCode befor closing the ticket.

Question: 
Does only the admin can tun on/off project-level monitoring in the current implementation?

**Comment by loganhz** [comment]
@thxCode   I can reproduce this issue in rancher/rancher:master 04/01

1. Create a standard user
2. Assign the user to a project with project owner role
3. Login as the created user
4. Enable/Disable project level monitoring

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master 2/12 on the following setups:

Single Install
- DO cluster with 3 nodes, 1 role on each
- EKS cluster


HA Install
- DO cluster with 3 nodes, 1 role on each
- EKS cluster
