### ISSUE TITLE
Update Helm to support latest features

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16971]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Update Helm used to support latest features/bug fixes etc

**Comment by deniseschannon** [comment]
Check helm to update to the latest stable version for 2.3.

**Comment by cjellick** [comment]
It is probably too late in the cycle to take this on, especially without a clear specific bug (or set of bugs) that this would solve.

**Comment by superseb** [comment]
Examples:
https://github.com/rancher/rancher/issues/19112
https://github.com/rancher/rancher/issues/21041
https://github.com/rancher/rancher/issues/21932

**Comment by KaelBaldwin** [comment]
Unable to install Spinnaker on our cluster due to the a missing mergeOverwrite function I believe.

**Comment by drbothen** [comment]
This is also preventing me from install Jupyterhub. The error message i receive is: Failed to install app jupyterhub. Error: Chart incompatible with Tiller v2.10+unreleased. Looks like the work around is to install it manually until this has been resolved

**Comment by deniseschannon** [comment]
@dramich what version of helm are we using now in 2.3.0?

**Comment by dramich** [comment]
We are on 2.14.3 https://github.com/rancher/helm/releases

**Comment by deniseschannon** [comment]
Closing as at the time of 2.3.0, that was the latest helm version. 

We will have to track Helm versions in a different lifecycle but overall, the previous issues should be addressed with this version of helm.
