### ISSUE TITLE
Backport: Failed to generate kube-etcd certificate: x509: cannot parse IP address of length 0

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16975]
Backport https://github.com/rancher/rancher/issues/16934

**Comment by alena1108** [comment]
Fixed in v2.1.4-rc1

**Comment by sangeethah** [comment]
Steps to reproduce the issue:
Create K8s cluster.
kubectl edit secret -n kube-system <kube-etcd-cert-name> and make secret empty
Edit cluster and add a new node or enable/disable snapshots.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.4-rc1

* Reproduced original issue in v2.1.3: 
```
2018/12/11 16:41:28 [INFO] cluster [c-qf2nq] provisioning: [certificates] Regenerating new etcd-138.68.252.198 certificate and key
2018/12/11 16:41:29 [ERROR] ClusterController c-qf2nq [cluster-provisioner-controller] failed with : Failed to generate kube-etcd certificate: x509: cannot parse IP address of length 0
```

* Installed Rancher v2.1.4-rc1
* Created cluster
* Edited kube-etcd cert secret to remove data
* Updated cluster (turned off etcd snapshots)
* Cluster regenerated certs and updated successfully

```
2018/12/11 16:54:39 [INFO] cluster [c-xdvdb] provisioning: [certificates] Regenerating new etcd-178.128.13.207 certificate and key
2018/12/11 16:54:39 [INFO] cluster [c-xdvdb] provisioning: [certificates] Successfully generated new etcd-178.128.13.207 certificate and key
```
