### ISSUE TITLE
Backport: rke uses internal IP's when building a cluster but ApplyAuthzResources doesnt

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16976]
Backport https://github.com/rancher/rancher/issues/16536

**Comment by alena1108** [comment]
Fixed in v2.1.4-rc1

**Comment by soumyalj** [comment]
Reproduced the issue with v2.1.3. 
1. Created security group in AWS that references itself  
2. Created cluster using AWS as cloud provider with an appropriate AMI
Cluster provisioning failed with the below error:
<img width="1394" alt="screen shot 2018-12-10 at 4 48 34 pm" src="https://user-images.githubusercontent.com/18536626/49771649-ef9ee380-fc9e-11e8-9bf0-2ed04947ade4.png">
