### ISSUE TITLE
Monitoring - Grafana links for EKS cluster is overwritten by DO cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16970]
Bug. 

Rancher master on 12/5.

Steps:
- logged in as admin, add 2 clusters: DO and EKS
- Enabled cluster level monitoring for both DO and EKS cluster
- Clicked into the EKS cluster to see the following page:
<img width="1533" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49666232-a0de1900-fa14-11e8-87e2-c51e862a3efb.png">

Results:
- There is a Grafana icon on the `Etcd` tab, which is not expected
- Clicking any Gafana icon on this page will jump to the corresponding page for DO cluster, not EKS cluster. 

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by davidnuzik** [comment]
This also happens both ways or at least it did for me in this scenario: I have EKS monitoring on with fluentd for logging. I have DO with elasticsearch logging. When I check on DO rancher logging I see fluentd stuff from the separate EKS cluster. It seems like in the UI we aren't changing context to the correct cluster. I think it's probably the same issue.

**Comment by loganhz** [comment]
@davidnuzik just saw your comment. I didn't fix your issue in this PR. Maybe we can keep this issue open or file another issue for that

**Comment by sangeethah** [comment]
@davidnuzik Can you log a different bug for this ?

**Comment by davidnuzik** [comment]
#16973 was entered for that separate issue with logging charts not updating.

**Comment by jiaqiluo** [comment]
Validated on master 12/7

Steps:
- logged in as admin, add 2 clusters: DO and EKS
- Enabled cluster level monitoring for both DO and EKS cluster
- Clicked into the EKS cluster to see the following page:
<img width="1473" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49673011-464fb780-fa2a-11e8-88cb-438362a38180.png">

There are no Grafana icons, which is the expected behavior.

Bug fix validated.
