### ISSUE TITLE
Unable to add new host in private VMs

### ISSUE THREAD

**Issue by smetal1** [rancher/rancher#16987]
12/9/2018 5:32:04 PM+ export ETCD_KEY_FILE=/etc/etcd/ssl/key.pem
12/9/2018 5:32:04 PM+ ETCD_KEY_FILE=/etc/etcd/ssl/key.pem
12/9/2018 5:32:04 PM+ export ETCDCTL_CA_FILE=/etc/etcd/ssl/ca.pem
12/9/2018 5:32:04 PM+ ETCDCTL_CA_FILE=/etc/etcd/ssl/ca.pem
12/9/2018 5:32:04 PM+ export ETCD_CERT_FILE=/etc/etcd/ssl/cert.pem
12/9/2018 5:32:04 PM+ ETCD_CERT_FILE=/etc/etcd/ssl/cert.pem
12/9/2018 5:32:04 PM+ export ETCDCTL_KEY_FILE=/etc/etcd/ssl/key.pem
12/9/2018 5:32:04 PM+ ETCDCTL_KEY_FILE=/etc/etcd/ssl/key.pem
12/9/2018 5:32:04 PM+ export ETCDCTL_CERT_FILE=/etc/etcd/ssl/cert.pem
12/9/2018 5:32:04 PM+ ETCDCTL_CERT_FILE=/etc/etcd/ssl/cert.pem
12/9/2018 5:32:04 PM++ giddyup service scale etcd
12/9/2018 5:32:04 PM+ SCALE=3
12/9/2018 5:32:04 PM++ echo
12/9/2018 5:32:04 PM++ grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
12/9/2018 5:32:04 PM+ '[' '!' '' ']'
12/9/2018 5:32:04 PM+ sleep 1
12/9/2018 5:32:05 PM++ wget -q -O - http://169.254.169.250/2015-12-19/self/container/primary_ip
12/9/2018 5:32:05 PM+ IP=10.42.21.46
12/9/2018 5:32:05 PM++ curl -s http://169.254.169.250/2015-12-19/self/container/name
12/9/2018 5:32:05 PM+ ETCD_CONTAINER_NAME=kubernetes-etcd-1
12/9/2018 5:32:05 PM++ echo 10.42.21.46
12/9/2018 5:32:05 PM++ grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
12/9/2018 5:32:05 PM+ '[' '!' 10.42.21.46 ']'
12/9/2018 5:32:05 PM++ wget -q -O - http://169.254.169.250/2015-12-19/self/container/create_index
12/9/2018 5:32:05 PM+ CREATE_INDEX=44828
12/9/2018 5:32:05 PM++ wget -q -O - http://169.254.169.250/2015-12-19/self/container/service_index
12/9/2018 5:32:05 PM+ SERVICE_INDEX=1
12/9/2018 5:32:05 PM++ wget -q -O - http://169.254.169.250/2015-12-19/self/host/uuid
12/9/2018 5:32:05 PM+ HOST_UUID=23d90fa8-8778-4f54-abd2-ec3793759af3
12/9/2018 5:32:05 PM+ LEGACY_DATA_DIR=/data
12/9/2018 5:32:05 PM+ DATA_DIR=/pdata
12/9/2018 5:32:05 PM+ DR_FLAG=/pdata/DR
12/9/2018 5:32:05 PM+ export ETCD_DATA_DIR=/pdata/data.current
12/9/2018 5:32:05 PM+ ETCD_DATA_DIR=/pdata/data.current
12/9/2018 5:32:05 PM+ export ETCDCTL_ENDPOINT=https://etcd.kubernetes:2379
12/9/2018 5:32:05 PM+ ETCDCTL_ENDPOINT=https://etcd.kubernetes:2379
12/9/2018 5:32:05 PM++ echo 10.42.21.46
12/9/2018 5:32:05 PM++ tr . -
12/9/2018 5:32:05 PM+ NAME=10-42-21-46
12/9/2018 5:32:05 PM+ '[' 1 -eq 0 ']'
12/9/2018 5:32:05 PM+ eval node
12/9/2018 5:32:05 PM++ node
12/9/2018 5:32:05 PM++ mkdir -p /pdata/data.current
12/9/2018 5:32:05 PM++ '[' -d /data/member ']'
12/9/2018 5:32:05 PM++ '[' -d /data/data.current ']'
12/9/2018 5:32:05 PM++ '[' -f /pdata/DR ']'
12/9/2018 5:32:05 PM++ '[' -d /pdata/data.current/member ']'
12/9/2018 5:32:05 PM+++ etcdctl_one member list
12/9/2018 5:32:05 PM+++ target_ip=0
12/9/2018 5:32:05 PM+++ container_name=
12/9/2018 5:32:05 PM+++ grep 10.42.21.46
12/9/2018 5:32:05 PM++++ giddyup service containers
12/9/2018 5:32:05 PM+++ for container in '$(giddyup service containers)'
12/9/2018 5:32:05 PM++++ wget -q -O - http://169.254.169.250/2015-12-19/self/service/containers/kubernetes-etcd-2/primary_ip
12/9/2018 5:32:05 PM+++ primary_ip=10.42.150.133
12/9/2018 5:32:05 PM+++ giddyup probe tcp://10.42.150.133:2379
12/9/2018 5:32:10 PM+++ '[' 1 == 0 ']'
12/9/2018 5:32:10 PM+++ for container in '$(giddyup service containers)'
12/9/2018 5:32:10 PM++++ wget -q -O - http://169.254.169.250/2015-12-19/self/service/containers/kubernetes-etcd-1/primary_ip
12/9/2018 5:32:10 PM+++ primary_ip=10.42.21.46
12/9/2018 5:32:10 PM+++ giddyup probe tcp://10.42.21.46:2379
12/9/2018 5:32:10 PM+++ '[' 1 == 0 ']'
12/9/2018 5:32:10 PM+++ '[' 0 == 0 ']'
12/9/2018 5:32:10 PM+++ echo No etcd nodes available
12/9/2018 5:32:10 PM++ '[' '' ']'
12/9/2018 5:32:10 PM++ giddyup leader check
12/9/2018 5:32:10 PM++ echo Adding Node
12/9/2018 5:32:10 PM++ runtime_node
12/9/2018 5:32:10 PM++ rm -rf '/pdata/data.current/*'
12/9/2018 5:32:10 PM+++ date -R
12/9/2018 5:32:10 PM++ timestamp='Sun, 09 Dec 2018 12:02:10 +0000'
12/9/2018 5:32:10 PM++ echo 'Sun, 09 Dec 2018 12:02:10 +0000 -> Scaling up. Deleted stale data'
12/9/2018 5:32:10 PM+++ giddyup service containers --exclude-self
12/9/2018 5:32:10 PM++ for container in '$(giddyup service containers --exclude-self)'
12/9/2018 5:32:10 PM++ echo Waiting for lower index nodes to all be active
12/9/2018 5:32:10 PM+++ wget -q -O - http://169.254.169.250/2015-12-19/self/service/containers/kubernetes-etcd-2/create_index
12/9/2018 5:32:10 PM++ ctx_index=36643
12/9/2018 5:32:10 PM+++ wget -q -O - http://169.254.169.250/2015-12-19/self/service/containers/kubernetes-etcd-2/primary_ip
12/9/2018 5:32:10 PM++ primary_ip=10.42.150.133
12/9/2018 5:32:10 PM++ '[' 36643 -lt 44828 ']'
12/9/2018 5:32:10 PM++ probe_https https://kubernetes-etcd-2:2379/health loop 1 15 1.2
12/9/2018 5:32:10 PM++ url=https://kubernetes-etcd-2:2379/health
12/9/2018 5:32:10 PM++ loop=loop
12/9/2018 5:32:10 PM++ min=1
12/9/2018 5:32:10 PM++ max=15
12/9/2018 5:32:10 PM++ backoff=1.2
12/9/2018 5:32:10 PM++ SECONDS=0
12/9/2018 5:32:10 PM++ delay=1
12/9/2018 5:32:10 PM++ '[' loop == loop ']'
12/9/2018 5:32:10 PM++ true
12/9/2018 5:32:10 PM+++ echo '1>15'
12/9/2018 5:32:10 PM+++ bc
12/9/2018 5:32:10 PM++ '[' 0 -eq 1 ']'
12/9/2018 5:32:10 PM+++ echo '1*1.2'
12/9/2018 5:32:10 PM+++ bc
12/9/2018 5:32:10 PM++ delay=1.2
12/9/2018 5:32:10 PM++ grep -q '{"health": "true"}'
12/9/2018 5:32:10 PM++ curl -s -k --cacert /etc/etcd/ssl/ca.pem --cert /etc/etcd/ssl/cert.pem --key /etc/etcd/ssl/key.pem https://kubernetes-etcd-2:2379/health
12/9/2018 5:34:18 PM++ '[' 1 -eq 0 ']'
12/9/2018 5:34:18 PM++ '[' true == true ']'
12/9/2018 5:34:18 PM++ echo seconds= 128
12/9/2018 5:34:18 PM++ '[' 128 -gt 60 ']'
12/9/2018 5:34:18 PM++ return 128
12/9/2018 5:34:18 PM++ '[' 128 -ne 0 ']'
12/9/2018 5:34:18 PM++ echo 'Failed to get a healthy response. Giving up..'
12/9/2018 5:34:18 PM++ exit 1

**Comment by superseb** [comment]
There is not enough information in this issue to investigate. Please provide all steps to reproduce (OS/docker version used, how many nodes, what is the status and logging of all etcd containers, what steps did you take to get into this situation from scratch)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
