### ISSUE TITLE
Failed to modify StatefulSet

### ISSUE THREAD

**Issue by Gambler13** [rancher/rancher#16984]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

I tried to deploy the MariaDB chart from the Rancher Library with my self signed SSL certificates. But I failed to mount the certificates into the pod in the Rancher UI.

Steps to reproduce:
1. Deploy MariaDB from Rancher library
2. Got To Catalog Apps and click on MariaDB
3. Edit Workload (MariaDB Master)
4. Add new mount from secrets source
5. Click on save and get following error

`Validation failed in API: StatefulSet.apps "maria-mariadb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

If I do the same via "Edit YAML", and configure the secret mount manually it works like expected. The volume is part of the template field. So I guess the validation is wrong or Rancher modifies more than just the volume part.

**Environment information**
- Rancher version 2.1.3

**Comment by BalaBalaYi** [comment]
I guess it's because of the k8s design. The statefulset can only be upgraded  in several limited areas such as containers and replicas.  Edit the yaml meas redeploy i think.
Please see the [source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go#L101-L123).

**Comment by Gambler13** [comment]
Of course, this is what the validation error says. Only following fields can be updated:
- Replicas
- Template
- UpdateStrategy

But if I add a secret volume mount, this should only affect the template.containers.volumeMounts.* and the template.spec.volume.* field, right?

If I modify these values directly in the YAML file, the workload is upgraded as expected.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17283
