### ISSUE TITLE
Default project level alert fired unexpectedly

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16986]
rancher/rancher:v2.2.0-alpha2

Steps:

1. Add a new alert group and a alert rule based on expression in project level
2. Make the newly alert fired

Results:

The precan alert `Memory usage close to the quota` shows alerting status as well.

![image](https://user-images.githubusercontent.com/21168270/49692778-cb0f1280-fb9d-11e8-9b27-77068a6d1934.png)

Expected:

The pre-can alert `Memory usage close to the quota` should not be in `Alerting` state

**Comment by cjellick** [comment]
I see a commit for this. is there a PR?

**Comment by loganhz** [comment]
We will submit the PR later. There is some dependency. We need to merge the Prometheus refactor PR first.

**Comment by rootwuj** [comment]
Version: master 2.2 (2/15/19)
This version of the pre-can alert is not affected by other alert statuses.
Confirmed fix.
