### ISSUE TITLE
Monitoring UI issues 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16985]
rancher/rancher:v2.2.0-alpha2

- It show read message when user re-enters enabling monitoring page
- When you refresh etcd graph "Disk operations" chart and "Disk Sync Duration" chart will switch places.
- User can not see the page for enabling project level monitoring for system project.
- User can see system library in project/cluster level catalog config page
- Support more durations for alerting rules such as 1s, 10s, 30s

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/10/18)
I can confirm the first four items are indeed fixed. Soumya will be testing the last item:
- Support more durations for alerting rules such as 1s, 10s, 30s

**Comment by soumyalj** [comment]
Tested with master build from Dec 10. When new alerts are created or existing alerts are edited, 1, 10, 30s are seen in the UI. These were not available in alpha2

Screenshot from alpha2 add alerts section

<img width="1198" alt="screen shot 2018-12-10 at 1 15 09 pm" src="https://user-images.githubusercontent.com/18536626/49762092-aab68500-fc7d-11e8-8739-ddc51b10ad5e.png">


Screenshot from master add alerts section

<img width="1179" alt="screen shot 2018-12-10 at 1 16 19 pm" src="https://user-images.githubusercontent.com/18536626/49762146-d20d5200-fc7d-11e8-980e-9444232e8996.png">
