### ISSUE TITLE
Unable to authenticate login to rancher UI when multiple browser Windows are opened

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#16991]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1. Setup Rancher 1.6.24 with local auth
2. Open two or more browser Windows and go to Rancher login page
3. Click Login

**Result:**

Can not login to Rancher. 

**Environment information**
- Rancher version :
`rancher/server`:v1.6.22 to v1.6.24
- Installation option (single install/HA):
HA

**Comment by xiaoluhong** [comment]
@loganhz

**Comment by vincent99** [comment]
This is the same as https://github.com/rancher/rancher/issues/15869
