### ISSUE TITLE
Sometimes it takes around 10mins to start monitoring

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16996]
rancher/rancher:v2.2.0-alpha2

Steps:

1. Add a cluster
2. Enable the monitoring

Results:

In the catalog page, I can see the monitoring related workloads are running as expected.
But the condition for monitoring is still unknown. So UI will not show the graph to users. 

Expected:

User doesn't have to wait that long.

**Comment by jiaqiluo** [comment]
Vsalidation falied. 

This problem still exists on master 12/10

Step:
- Add a cluster
- Enable the monitoring

Result:
After the catalogs and workloads were `active`, it takes an additional 16 mins to wait API available and to show live graphs in cluster page. 

This is another ticket for the same issue which contains more detailed info: https://github.com/rancher/rancher/issues/17013

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17013 as there is more detail

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/pull/17094

**Comment by jiaqiluo** [comment]
Validate on master 12/17

Steps:
- started rancher server with image rancher: master 12/17
- added a DO cluster with 3 nodes, one role on each
- enabled the cluster level monitoring
- added a second cluster, all roles on 1 node
- enabled the cluster level monitoring for the second cluster
 
Result:
The live metrics and Grafana icons show up very quickly after related catalog apps and workloads being active for both clusters.

Bug fix verified.
