### ISSUE TITLE
How can i use ssl on 7 level slb (aliyun slb) only when the rancher server without https ?

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#16992]
use ssl in aliyun slb and close https on rancher server

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
External SSL termination is covered in https://rancher.com/docs/rancher/v2.x/en/installation/single-node/single-node-install-external-lb/ or https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#external-tls-termination.

If this is not sufficient, please explain your use-case in more detail.

**Comment by wuchencm** [comment]
Thanks very much ,i will try it
