### ISSUE TITLE
Workload and Pod information is missing in alert message

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16990]
The information is limited. We need to add more information

Such as 

Workload, Project, Pod info 
Current value of the expression

```
The metric my app crossed the threshold
Alert Name: my app
Severity: info
Cluster Name: c-4rbvj
Expression: web_app_online_user_count>4
Description: Threshold Crossed: datapoint was greater than to the threshold (4) for (1s)
```

**Comment by soumyalj** [comment]
@loganhz : I tested the alerts in master to see if we get more information about pods. Is this specific for alerts with an expression ?

**Comment by aiwantaozi** [comment]
@soumyalj For event we have common info for them like resource namespace and name, will not have workload for the pod.

**Comment by aiwantaozi** [comment]
@soumyalj The workload info is not the k8s event resource, so we just add the namespace to the pod, but not the workload info, if that is useful we will try to add it.

**Comment by soumyalj** [comment]
Workload information is missing in the current implementation. Assigning it back to @aiwantaozi
