### ISSUE TITLE
Change the default workload alert rule

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16994]
rancher/rancher:v2.2.0-alpha2

The rule is 

```
sum(container_memory_working_set_bytes{pod_name=~"prometheus-cluster-monitoring.*"}) by (pod_name) / sum(label_join(kube_pod_container_resource_limits_memory_bytes{pod=~"prometheus-cluster-monitoring.*"},"pod_name", "", "pod")) by (pod_name)
```

The pod name is specified to prometheus-cluster-monitoring. It doesn't make sense as it is the pod for cluster monitoring. We need to change the pod to something else.

**Comment by cjellick** [comment]
@loganhz i see the associated pr was merged. is this waiting on something to go to-test?

**Comment by loganhz** [comment]
yes. It’s better to verify it after the monitoring refactor PRs get merged

**Comment by rootwuj** [comment]
Version: master 2.2 (2/15/19)
Confirmed fix.
