### ISSUE TITLE
Health check: Host header not working.

### ISSUE THREAD

**Issue by shinebayar-g** [rancher/rancher#16998]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Deploy something, edit health check:
![image](https://user-images.githubusercontent.com/3091558/49713935-d0e02300-fc85-11e8-98df-0422aca35c77.png)

Let's say my app only accept request from `mydomain.com` and returns 404 otherwise.
In that case I have to define host header on my health check request and If I set it like this, it doesn't work. 

**Result:**
![image](https://user-images.githubusercontent.com/3091558/49714043-52d04c00-fc86-11e8-93b2-f56a9e878864.png)

I assume it's not saving what I typed there. Because if I edit the deployment again my saved health check host header is empty again..

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

Single/2.1.1

**Comment by loganhz** [comment]
Thanks for the report.

Close in favor of https://github.com/rancher/rancher/issues/16853

**Comment by shinebayar-g** [comment]
Thanks for an update.
