### ISSUE TITLE
EAI_AGAIN for DNS lookups

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1699]
I have been seeing the EAI_AGAIN error creep up in some of my app logs when performing DNS lookups for external public internet services. Wondering how the rancher DNS resolving could be influencing this (or if it is at all).

My understanding is that `/etc/resolv.conf` on the rancher machines is set to use the rancher resolvers. What could affect the reliability of the resolvers?

**Comment by ibuildthecloud** [comment]
@defunctzombie the Rancher DNS server does no form of caching.  Every request to our DNS server gets delegated up to the external DNS server.  My guess would just be that really the upstream DNS server can not be contacted.  We never restart the DNS server, the reloads of configuration are done through a SIGHUP, so the DNS server should be running.

Now it is definitely possible that there is a bug or something of that sorts and maybe the DNS server panics and restarts.  In that situation you should be able to see some logs in monit that indicated that the DNS server was restarted.

**Comment by defunctzombie** [comment]
Gotcha. I think these have mostly gone away but if I see it again I will
check the logs for a DNS restart. Which log file would that be?

**Comment by deniseschannon** [comment]
```
/var/log/monit.log 
/var/log/rancher-dns.log 
/var/log/rancher-metadata.log
```

Sorry for the delay.

**Comment by deniseschannon** [comment]
@defunctzombie Please re-open if you are still seeing these issues.
