### ISSUE TITLE
  Rancher webhooks update service does not take effect

### ISSUE THREAD

**Issue by xrnick** [rancher/rancher#17004]
Rancher version 1.6.10,

Is there an upper limit for adding webhooks to rancher? Adding new webhooks to upgrade the corresponding services does not take effect.

Jenkins compiles, packages, mirrors, and latest. then updates the service through api.

The results of the update show that the service has been successfully restarted and updated.

This problem has been bothering me for a long time. I tried many times, but it didn't work.

Attached is the command I executed through the api.
<img width="960" alt="api" src="https://user-images.githubusercontent.com/36979992/49724579-99cd3a00-fca4-11e8-89c0-782283ca9cd1.png">
<img width="933" alt="webhooks" src="https://user-images.githubusercontent.com/36979992/49724643-bec1ad00-fca4-11e8-8870-8747a0a2ec20.png">

**Comment by loganhz** [comment]
@xrnick Can you provide the rancher server logs, please?

**Comment by xrnick** [comment]
Thank you for giving me a reply.
One. By building and upgrading services through jenkins, the logs generated by rancher server are shown in Figure rancher server log.
<img width="960" alt="rancher server log" src="https://user-images.githubusercontent.com/36979992/49776348-a5694100-fd36-11e8-82fc-24622d88761f.png">
Two. Execute hook scripts separately and return 200, as shown in Webhooks script
<img width="952" alt="webhooks script" src="https://user-images.githubusercontent.com/36979992/49776363-af8b3f80-fd36-11e8-9338-956360a4b2ea.png">

**Comment by xrnick** [comment]
docker 版本是1.13.0

**Comment by loganhz** [comment]
Thanks for the report. With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
