### ISSUE TITLE
Clone project alert rule result UI crash

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#17007]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Go to Project alert.
2. Select a metric alert rule and click clone action.

**Result:**
UI console throws an error: "cannot read model.podRule ......."

**Comment by davidnuzik** [comment]
Version: v2.2.0-alpha3
Confirmed fixed. I was able to clone the project alert rule without any issues. The browser console did not complain of any issues, and I was successfully able to clone. Validated HTTP POST.
