### ISSUE TITLE
[Feature] Kubectl UX Improvement

### ISSUE THREAD

**Issue by Coopyrightdmin** [rancher/rancher#17008]
Dear Rancher Team,

When managing projects, it is not convenient to come back to the cluster view in order to launch kubectl. What about having the capability of running kubectl from any view or at least on the workloads view? (e.g., to create secrets which are not "Opaque", retrieving tokens etc... ideally, in accordance with the namespace).

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`containers.index`|

**Comment by superseb** [comment]
You can use `~` to access kubectl from any view inside a cluster.
