### ISSUE TITLE
[Features] Docker Registry

### ISSUE THREAD

**Issue by Coopyrightdmin** [rancher/rancher#17005]
Dear Rancher Team,

here some enhancements that we would appreciate to see concerning the integration of custom docker registries:
1) Nice to have:  Ability to define cross-projects registries to avoid having to maintain the same information several times ;
2) Nice to have: Displaying  password when entering credentials ;
3) Mandatory:  Including the following statement automatically within the yaml file when deploying an image as already stated by other people in other messages.
```
imagePullSecrets:
  - name: <my registry>
```

Sincerly,
Ludovic

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`authenticated.project.registries.index`|

**Comment by shinebayar-g** [comment]
Dup: https://github.com/rancher/rancher/issues/1738

**Comment by deniseschannon** [comment]
Closing in favor of 1738
