### ISSUE TITLE
Rancher pipeline stage name "compile-api-abc" cause Strconv.Atoi: parsing "api": invalid syntax

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#17006]
**What kind of request is this :**
bug

**Steps to reproduce :**
Setup a pipeline and configure a stage with name "compile-api-abc" and with any stage type.
Then save and run the pipeline.

**Result:**
Strconv.Atoi: parsing "api": invalid syntax

**Environment information**
- Rancher version : 2.1.3
- Installation option : single

**Comment by gitlawr** [comment]
This bug happens when the stage name is in the `x-x-x` format

**Comment by rootwuj** [comment]
Version -2.2 master 12/19
Verified fixed
