### ISSUE TITLE
Legacy Authorization under GKE cluster options has no default selected

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17015]
Version: master 2.2 (12/10/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create GKE cluster, while doing so expand Cluster Options section.
- Observe that Legacy Authorization has no default picked.
![image 1](https://user-images.githubusercontent.com/45179589/49756369-2eb93e80-fc77-11e8-8a4c-f909ff6ca136.png)

**Result:**
No default radio button is picked for Legacy Authorization. If there is no default Enabled or Disabled then perhaps two radio buttons may not be the best option (if there is more than 2 states?)

**Other details that may be helpful:**
Perhaps the API does not provide us with a default so the UI doesn't render with one picked.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/49868174-8e664400-fe47-11e8-83b3-75fb1520dc66.png)

The type of `enableLegacyAbac` is string. I guess we need to fix it in backend by changing this filed to `boolean` and set the default value of it to `true` or `false`

**Comment by fyery-chen** [comment]
@n313893254 Please give it a default value in UI, it is related to the field `enableLegacyAbac`.

**Comment by loganhz** [comment]
@thxCode Please validate it

**Comment by thxCode** [comment]
The default radio button is picked for Legacy Authorization.

![image](https://user-images.githubusercontent.com/3394724/52910430-4c87cd00-32d2-11e9-979b-7ab389911138.png)
