### ISSUE TITLE
Monitoring - Cluster level monitoring is stuck on "API not ready" although it is already ready

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17013]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- started rancher server with image rancher: master 12/10
- added a DO cluster with 3 nodes, one role on each
- enabled the cluster level monitoring 

**Result:**
- the catalog apps were deployed and in `active` state under `system` project
- all workload under the namespace `cattle-prometheus` were in `active` state
- BUT the cluster page showed the API not ready, and never become ready
- the docker log shows the following error message: 
```
2018/12/10 18:10:28 [ERROR] ClusterController c-vhk5l [user-cluster-monitoring] failed with: unable to sync Cluster do(c-vhk5l): failed to detect the installation status of monitoring components: [Grafana Deployment is deploying, Kube State Exporter Deployment is deploying]
```

**Other details that may be helpful:**
Turning off  the cluster monitoring and turning it on again could fix the problem

<img width="1486" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49752777-9b7c0b00-fc6e-11e8-8ef3-aa05ef104fa3.png">
<img width="1431" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49752785-a33baf80-fc6e-11e8-905e-f3c0bb58b42d.png">
<img width="1472" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49752794-a8006380-fc6e-11e8-9349-0482b431a929.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master 12/10
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: jiaqi-rancher-master
ID: HUDH:QL2Q:UNRI:N5JV:UCPB:KFKM:JFHQ:FXFR:A2PV:YHFA:VPEX:HQB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by jiaqiluo** [comment]
same issue: https://github.com/rancher/rancher/issues/16996

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/pull/17094

**Comment by jiaqiluo** [comment]
Validate on master 12/17

Steps to reproduce (least amount of steps as possible):
- started rancher server with image rancher: master 12/17
- added a DO cluster with 3 nodes, one role on each
- enabled the cluster level monitoring
- added a second clsuter, all roles on 1 node
- enabled the cluster level monitoring for the second cluster
 
Result:
The live metrics and Grafana icons show up very quickly after related catalog apps and workloads being active for both clusters.

Bug fix verified.
