### ISSUE TITLE
strip path after load balancer advanced routing

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1701]
Maybe this is documented but I was unable to find it. If I have setup advanced routing using a custom path to direct traffic to a different service, how do I strip this path from the routed request?

Example:

Setup LB with path `/api/` to direct to the API backends but requests to `example.com/api/foobar` hit the API backend with URL `/api/foobar` when I want them to hit the backend with `/foobar`.

**Comment by alena1108** [comment]
@defunctzombie LB url path based traffic rules work in "begin_with" way. Here are couple of examples:

1) path = /foo 

Requests having url /foo,  /foo/bar1, /foo/bar2 qualify for this rule

2) path /foo/bar

Requests having /foo/bar url qualify for this rule

Also paths' ACLs are sorted in descending order on the backend, so the longest (more specific) path is checked first. For example 2 rules above are going to be applied this way:

/foo/bar -> service1
/foo -> service2

So requests having /foo/bar/something will always hit the /foo/bar rule and be redirected to service1. All requests who's path begins with "/foo", but not having following "/bar" will be redirected to service2

@deniseschannon we document that under our LB section

**Comment by defunctzombie** [comment]
@alena1108 yep, that part I understand but the part that may be missing is if I have `/foo/bar` -> service1, how can I make it so that when I visit `/foo/bar/baz` it actually hits `/baz

**Comment by alena1108** [comment]
@defunctzombie unfortunately unlike apache/nginx, haproxy doesn't have direct support for proxy_pass, mode_override directives. There is a way to hack it by overriding the URL on haproxy side, but thats not something Rancher supports. Today we just redirect you to a specific backend based on hostname/path of your requests, without actually overriding these parts.

**Comment by deniseschannon** [comment]
@defunctzombie it looks like haproxy doesn't support what you are looking for so I will be closing this issue. Let meknow if you think it should be re-opened.

**Comment by vincent99** [comment]
There is a way to rewrite the requested path in haproxy (`reqrep`) but not a way to configure that in Rancher today.  This cannot really be the default behavior because it breaks any application that responds with absolute or root-relative links, css/js includes, etc, and that is pretty common.

Subdomains (or different domains altogether) are a good alternative and do not require any path rewriting.

**Comment by defunctzombie** [comment]
Gotcha. Didn't know haproxy doesn't do it easily.

Subdomains are not ideas due to CORS issues.

**Comment by andrefreitas** [comment]
The ability of rewriting urls is a killer-feature for us to use Rancher. 

Anyway, although in the documentation you refer the load balancer is Haproxy, current version uses Nginx.

**Comment by vincent99** [comment]
The Rancher load balancer service is and always has been haproxy, not nginx.

**Comment by andrefreitas** [comment]
@vincent99 sorry, was a mistake of mine. You are right. 

What we are doing to solve this, is putting a nginx containers that translates URLs, called "gateway" that routes for services balancers.

Hope this tip helps for those that search for this issue here.

**Comment by ryudice** [comment]
Is there still no way to do this?

**Comment by christianhuening** [comment]
Would also be very interested in this!

**Comment by ocasta** [comment]
Adding a custom entry to the the haconfig.cfg achieves this. For instance

`backend my-backend
  reqrep ^([^\ :]*)\ /api/(.*)     \1\ /\2
`

removes the string **/api/** and replaces it with a **/**

**Comment by mattdodge** [comment]
One thing to note (we didn't realize this at first) is that you have to add a custom name for your backends in order to support this. Under your service rules click "Show custom backend names" and give the service you want a unique backend name. After we did that, we were able to make @ocasta's configuration work (backend name in his example is `my-backend`).

**Comment by empinator** [comment]
I used a slightly different rule, but it @ocasta and @mattdodge answers combined make it work.
One hint: if you have a rule matching on "/", you might have to put it at the end of your rules :-)

`backend example-app
    reqrep ^([^\ ]*\ /)example[/]?(.*)     \1\2`

**Comment by grabekm90** [comment]
Nowadays it's much better to use more intuitive `set-path` from [http-request](http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#4.2-http-request). It also prevents warnings from haproxy (_'http-request' rule placed after a 'reqxxx' rule will still be processed before_).
```
backend my-backend
  http-request set-path %[path,regsub(^/api,)]
```
