### ISSUE TITLE
Rancher pipeline cannot build multiple docker images.

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#17024]
**What kind of request is this :**
bug

**Steps to reproduce:**
Edit a pipeline and create 2 steps with type "Build and publish image"

**Result:**
Error log as follows:
````
03:05:32 [pipeline_p-rtptn-5] Running shell script
03:05:35 + /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
03:05:35 + /usr/local/bin/dockerd -g /var/lib/docker
03:06:31 EXITCODE   0time="2018-12-11T03:06:24Z" level=fatal msg="Error authenticating: exit status 1"
````

**Environment information**
- Rancher version: 2.1.3
- Installation option : single

**Comment by gitlawr** [comment]
Duplicate of https://github.com/rancher/rancher/issues/16624
