### ISSUE TITLE
The Rancher catalog questions.yml password type does not support pure numeric type passwords.

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#17021]
The question.yml variable password type in the chart. The pure digital test app store does not support the grafana password. The deployment with pure numeric type fails, but the number and letter can be mixed.

The question.yml variable password type in the chart. The pure digital test app store does not support the grafana password with a pure numeric type deployment failure, but the combination of numbers and letters or plus ' ' or " " can be deployed successfully.

It treats the transmitted value as a float64 type handler
The error message is as follows
![](https://training-1251900790.cos.ap-guangzhou.myqcloud.com/image/error-1.png)
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.2` UI: `v2.1.17` |
|Route|`global-admin.clusters.index`|

**Comment by wanshaoyuan** [comment]
@guangbochen

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/13158
