### ISSUE TITLE
How can i set the default index  patters to  ${clusterName}_${projectName}_${workloadName}_${dateFormat}

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#17031]
![image](https://user-images.githubusercontent.com/14210543/49777144-25dd7100-fd3a-11e8-8e82-801fbe890657.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`authenticated.project.logging.logging`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
