### ISSUE TITLE
Changing scale of service from 1 to 0 doesn't have the UI update with no containers. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1703]
v0.31.0-rc4

By adding ability to scale to 0 (due to Rancher-compose), when I scale a service to 0, the scheduler correctly removes the container on the host, but the UI still shows the container as active/running.

Note: This only affects when going from 1 to 0.  It works for 2 to 0.

Steps to Reproduce: 
1. Start a service of scale 1.
2. Edit the scale to 0.

Result: UI will continue to have 1 active running container, but if you click on the hosts page, the container is already in removed state.

Expected result: UI will show the removed state container and eventually purged and removed from the UI.

**Comment by deniseschannon** [comment]
Still an issue in v0.57.0-rc5 in the stack summary page and the summary of the service. 

<img width="1122" alt="screen shot 2016-02-04 at 12 39 19 pm" src="https://cloud.githubusercontent.com/assets/11410997/12828982/7417013e-cb3c-11e5-9a26-36b70ba502f6.png">

**Comment by tfiduccia** [comment]
Version - 1.1.0-dev2-rc6

**Comment by tfiduccia** [comment]
Version - 1.1.0-dev2
Not fixed
![image](https://cloud.githubusercontent.com/assets/11514927/15529974/3c037d74-2206-11e6-9fee-71602fd94b79.png)

**Comment by tfiduccia** [comment]
Version - master 5-27
Verified fixed
