### ISSUE TITLE
Monitoring: Switch from detail to summary if the number of hosts is greater than 10

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17038]
Switch the monitoring graphs in cluster dashboard from detail to summary if the number of hosts is greater than 10

**Comment by cjellick** [comment]
Feedback from @cloudnautique is that at scale the graphs are unreadable. Add logic to switch from detail to summary if the number of hosts is greater than 10

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/11/19) HA Setup
Confirmed issue.

- Create a cluster with 10 nodes.
- Enable monitoring.
- Notice is in detail mode when expand any metrics section on the Cluster page.
- Leave the page open, on another page increase node pool by 1 so we get to 11 nodes.
- Once node is up and we are monitoring it, close the panes and open again. They are all now "Summary" and there was no need to refresh the browser, just need to close and open each section/pane again.

Screenshot shows in Summary mode. This was automatically picked for me when opening this section when I have 11 or more nodes.
![image](https://user-images.githubusercontent.com/45179589/54145714-c13eba80-43eb-11e9-8c8b-86823a39a0bc.png)

Smoke tested. Ensured I can still switch to detail view without issues. If I switch to detail, close the pane, open the pane again is now Summary view.
