### ISSUE TITLE
Cannot see the metrics of the node which doesn't have a worker role

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17030]
rancher/rancher:v2.2.0-alpha3

Steps to reproduce:

1. Add three nodes into a cluster.  First node with etcd and controller manager role. (not a worker). The others nodes are worker nodes.
2. Enable monitoring
3. I can see only two lines in cluster cpu usage graph

**Comment by jiaqiluo** [comment]
Some finds on master 1/30:
I have two RKE clusters, one DO and one EC2, both of them have 3 nodes: 1 `etcd`, 1 `control plane`, and 1 `worker`. 
After enabling the cluster level monitoring,
for EC2 cluster, the `etcd` and `control plane` nodes have no metrics showing
for DO cluster, the `etcd` node has no metrics showing
![screenshot](https://user-images.githubusercontent.com/6218999/52010855-c414ca00-2493-11e9-83a1-c34c7baa3e37.png)

**Comment by jiaqiluo** [comment]
### The valdiation are failed faied on Rancher HA install 
Test faield on a  DO cluster with 3 nodes, 1 role on each; but the same test are passed on the EKS cluster.  
Result: for the DO cluser, the line for `etcd` node is missing from all graphs under the cluster metrics section.

<img width="1471" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52660055-130f2600-2ebc-11e9-97af-5b70d99a196d.png">



### The valdiation are passed on Rancher single install
tested on the following clusters:
  - DO cluster with 3 nodes, 1 role on each
  - EKS cluster

**Comment by jiaqiluo** [comment]
The reason for the above failure is the chart for monitoring catalog apps is not updated to v0.0.2, so after fetching and newest chart and enabling the cluster monitoring again, the issue saw before was solved.
