### ISSUE TITLE
Always use project level Grafana link for Workload/Pod/Container

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17041]
Always use project level Grafana link for Workload/Pod/Container if the project level monitoring is enabled.

Steps:

1. Enable cluster level monitoring and project level monitoring
2. Login as admin user
3. Click the Grafana icon of a workload

Result:

It will jump to cluster level Grafana

Expected:

It should go to project level Grafana

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/3
Verified fixed
