### ISSUE TITLE
rancher-nfs volume sometimes empty after container recreation

### ISSUE THREAD

**Issue by sevenval-admins** [rancher/rancher#17048]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Unfortunately we haven't managed to reproduce the bug successfully yet.

But we noticed the following behavior.

After the upgrade to Rancher 1.6.23 we also updated all storage-nfs stacks to the offered version 0.9.1.

After that, we've seen some critical behavior a few times that we didn't notice before.

In the middle of operation, a running Nginx container suddenly delivered errors. During the investigation we noticed that the volume that normally contains the config was empty. Deleting the container and recreating it fixed the problem.

As a workaround we first adjusted the healthcheck of the container so that an empty config volume leads to a failure of the healthcheck.

In the following log examinations we were able to narrow down the problem to such an extent that we are now of the opinion that the sequence of the error is as follows.

* Rancher notices the failure of a health check, e.g. because of a defective Nginx process.
* As a result, the container is deleted.
* The new container finds an empty volume.

In the storage-nfs code diffs we found some changes to the garbage collection, https://github.com/rancher/storage/compare/v0.8.7...v0.9.1

We suspect that rancher-nfs clears the volume too quickly or too slowly after the defective container has been killed, resulting in a race condition.

We also found these log lines in the logs of the storage-nfs container.

`time="2018-11-14T15:33:08Z" level=error msg="Mounted but not registered in Docker: /var/lib/rancher/volumes/rancher-nfs/my-volume"
`

and

`wai-devel-wa already mounted on /var/lib/rancher/volumes/rancher-nfs/my-volume`

Please examine the problem once, as it has already produced several ugly failures.

Thank you very much.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 1.6.23
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

We are using cattle.

- Docker (use `docker info`):

```
Containers: 22
 Running: 22
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 19.45GiB
Name: xxxx
ID: OWXB:5ZKX:X62W:4HXI:XSVA:SQXJ:AYPZ:GQPK:NHQO:4WP7:625R:QNON
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by charliefd** [comment]
I can confirm that we have encountered this behavior too.

**Comment by taifu** [comment]
I too can confirm that we have encountered this behavior.

**Comment by martijnt** [comment]
We can confirm we have this too

**Comment by maltyxx** [comment]
We can confirm we have this too

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
