### ISSUE TITLE
Show images tooltip when a pod has multiple images

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17043]
rancher/rancher:master 12/10

Steps to reproduce:

1. Create a workload
2. Add three sidecars into this workload

Results:

UI shows `myimage + 4 images`. 

Expected:

It will be good if users can see the images list when hover `4 images`

![image](https://user-images.githubusercontent.com/21168270/49783886-5b905300-fd56-11e8-8bf6-fcad86d1a7ee.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/11/18)
Confirmed new feature. If you mouseover the images now a tooltip will popup listing the names of the workload and sidecars.
