### ISSUE TITLE
Ensure Rancher system pods are not killed by kubelet eviction manager

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#17049]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Starve the free space in the root filesystem on a node that runs system-level pods (e.g. ingress-controller, pipeline jenkins or minio, prometheus, etc) by allocating disk space until kubelet's hard eviction threshold is crossed (by default `nodefs.available<10%`).
E.g. Create a large file with `$ dd bs=1M if=/dev/zero of=/bigfile.tmp count=...`

**Result:**

System-level pods are evicted/killed even before user pods (e.g. nginx-ingress-controller, Pipeline's Minio or Jenkins) resulting in service disruption (ingress) or data loss (pipeline build logs).

```
Warning   Evicted Container nginx-ingress-controller was using 252Ki, which exceeds its request of 0.
The node was low on resource: ephemeral-storage.
Killing container with id docker://nginx-ingress-controller:Need to kill Pod nginx-ingress-controller-r7q7s.156f4e7f716145fe
```

Reason:  Kubelet might evict a pod from its node when the node’s ephemeral storage is exhausted. Since these system-level pods have no resource requests/limit specified for ephemeral storage they are targeted first for eviction.

**Expected Result:**

System-level pods should never be killed/evicted by kubelet when resources are starved on a node or at least they should be selected for eviction with lower priority than user pods.

> The kubelet ranks Pods for eviction first by whether or not their usage of the starved resource exceeds requests, then by Priority, and then by the consumption of the starved compute resource relative to the Pods’ scheduling requests.
(...)
Guaranteed pods and Burstable pods whose usage is beneath requests are evicted last. **Guaranteed Pods are guaranteed only when requests and limits are specified** for all the containers and they are equal. Such pods are guaranteed to never be evicted because of another Pod’s resource consumption.
_[source](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods)_

> In general, it is strongly recommended that DaemonSet not create BestEffort Pods to avoid being identified as a candidate Pod for eviction. Instead DaemonSet should ideally launch Guaranteed Pods.
_[source](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#daemonset)_

Solutions that should be explored to address this:

1. Configure the pods of system-level services such as they are assigned a QOS class of Guaranteed and thus "guaranteed to never be evicted because of another Pod’s resource consumption." This would imho require to specify the following requests/limits for the pods:
```
spec.containers[].resources.limits.memory
spec.containers[].resources.requests.memory
spec.containers[].resources.limits.ephemeral-storage
spec.containers[].resources.requests.ephemeral-storage
```
2. Mark these pods as critical so they are protected from eviction: https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Environment information**
- Rancher version 2.1.3
- Kubernetes version v1.11.3

**Comment by jama707** [comment]
Is there any update on this? I think I'm having the same issue.
I'm getting such error for the cattle-system pods
- `The node was low on resource: ephemeral-storage. Container nginx-ingress-controller was using 56Ki, which exceeds its request of 0.`
- `The node was low on resource: ephemeral-storage. Container agent was using 60Ki, which exceeds its request of 0.`
