### ISSUE TITLE
Support upgrade and downgrade for monitoring alert rules

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17042]
We have changed the data model for alert rules in 2.2.

We need to support upgrade and downgrade for it.

Upgrade:

Add some alert in 2.1.X
Upgrade the server to 2.2
The existing alerts should be still working

Downgrade:

Add some alert in 2.1.X
Upgrade the server to 2.2
Downgrade to 2.1.X
The existing alerts should be still working

**Comment by rootwuj** [comment]
@aiwantaozi 
After the alert rules are upgraded or downgraded, they cannot work normally.
My test process:
Configure Email notifier.

Upgrade:
1. Deploy rancher v2.1.5: Add alert rule A and send alerts repeatedly.
2. Upgrade to rancher v2.2: list does not display alert rule A and stops sending alerts
3. Then downgrade to rancher v2.1.5: list shows alert rule A and resumes sending alerts

Downgrade:
1. Deploy rancher v2.2: Add alert rule B and send alerts repeatedly.
2.  Downgrade to rancher v2.1.5: The alert rule B is not displayed in the list, and the alert is stopped.
3. Upgrade to rancher 2.2: The list shows alert rule B and resumes sending alerts.

**Comment by aiwantaozi** [comment]
@rootwuj 
I try upgrade:
old server version: 2.1.5
new server version v2.2.0-alpha6
1. start a old version server
2. add notifier, add cluster alert and project alert
3. check whether alertmanager deploy in system project cattle-alerting namespace
4. upgrade rancher server tot v2.2.0-alpha6
5. after upgrade we deploy an alertmanager app to cattle-prometheus and migrate the cluster level alert and project level alert, the cluster level alert could show in the UI and work, but the project level alert could not show in the UI beccause the wrong projectId value in project alert, the projectId should be clusterName:ProjectName, for example local:p-6w7q8, not just projectName

For the downgrade:
1. we will not migrate want you add in the new version server, but will keep the data you have when you use the old version server
2. we will not delete the new alertmanager app

Could you check the upgrade, whether you could see the cluster/project level alert migrate from old version in the UI? Which level you config and can't sending alerts.

**Comment by rootwuj** [comment]
Old server version: 2.1.6
New server version: master 2.2 (2/14/19)

* The old server version is upgraded to the new server version and the cluster/project level alert is migrated normally.
* Downgraded to the old service version, existing alerts are still valid.

Confirmed fix.
