### ISSUE TITLE
Rancher logo should go back to main cluster overview

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17052]
Version: master 2.2 (12/11/18)

**What kind of request is this:**
Enhancement Request

The Rancher icon should link to https://<rancherServer>/g just like the "Global" link does on the new global menu today. This effectively takes us back to <rancherServer>/g/clusters so we can see our list of clusters.

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13153
