### ISSUE TITLE
Update RKE Experimental K8s Version

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17050]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Through the UI attempt to launch an RKE based cluster
In cluster options select the k8s version dropdown 

**Result:**
UI does not list the `1.12` version as experimental and it should.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by sangeethah** [comment]
Tested with -v2.1.4-rc2

v1.12.3 is shown as experimental in the "Kubernetes Version" when provisioning RKE clusters and also the same is seen in "Edit Cluster" page.

<img width="1135" alt="screen shot 2018-12-13 at 8 55 13 am" src="https://user-images.githubusercontent.com/4266958/49954552-952ba000-feb5-11e8-9c94-a4afc25c4dc3.png">
