### ISSUE TITLE
Cannot switch to custom host when deploy catalog app sometimes

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17058]
rancher/rancher:master 12/11

Steps:

1. Add catalog https://github.com/guangbochen/charts-test into Rancher
2. Deploy test app in the catalog
3. Select `Expose app using Layer 7 Load Balancer` to `true`
4. Try to select `Specify a hostname to use` in Hostname field

Results:

Can not switch to it.

**Comment by guangbochen** [comment]
@mrajashree FYI, the custom host using `xip.io` can't switch is now addressed in the latest master.

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/18)
Confirmed fixed in master. I cannot reproduce the issue and was able to create the app with a specific hostname.
![image](https://user-images.githubusercontent.com/45179589/50310031-0b07ac80-045e-11e9-952a-7803da0c4147.png)
