### ISSUE TITLE
Update AKS locations

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#17054]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Update list of locations for AKS

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/2/19)
Confirmed enhancement.
The new locations have now been added to the "Location" drop-down when creating an AKS cluster:
East Asia, South India, Southeast Asia, and UK West
I made sure the previous were also listed and validated HTTP. I smoke tested creating AKS clusters with some of these locations.
