### ISSUE TITLE
[Question] How to achieve internal load balancers in Rancher 2.x?

### ISSUE THREAD

**Issue by CombatCode** [rancher/rancher#17051]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Other details that may be helpful:**
Using Rancher 1.x we were using built-in haproxy load balancers to set up internal and external load balancers.
Our basic configuration included:
```
:443 main-loadbalancer |->
                  |-> :8000 frontend-loadbalancer (with session stickiness) -> :8010 frontend pods
                  |-> :7000 backend-loadbalancer -> :7010 backend pods
```
Now, using Rancher 2.x there is avaialble only nginx-ingress based load balancer listening on ports 80 and 443.
Q: Is there any built-in solution to create "internal" load balancer supporting session stickiness ?
Q: How session stickiness was achived in Rancher 1.x? Do we need to know exact IPs hidden by container hostname to create native haproxy stickiness configuration ? 

**Environment information**
Rancher 2.0

**Comment by CombatCode** [comment]
It seems that internal load balancing could be now achieved by setting up *Services*.

Each *Workload* created via Rancher has associated *Service* with the same name.
*Services* works like a Layer-4 Load Balancers. Editing the yaml configraution we can set up:
``` sessionAffinity: ClientIP``` (default is None)
to get session stickiness.

**Comment by loganhz** [comment]
`sessionAffinity` supports has been added in https://github.com/rancher/ui/pull/2546

Close in favor of https://github.com/rancher/rancher/issues/15070
