### ISSUE TITLE
safely upgrade kubernetes cluster

### ISSUE THREAD

**Issue by manlme** [rancher/rancher#17057]
**What kind of request is this (question/bug/enhancement/feature request): question
 

**Steps to reproduce (least amount of steps as possible): upgrade the existing kubernetes cluster managed by rancher 2x

**Result:** 

rancher upgrade k8s cluster by editing the cluster. how it works? one by one node upgrade?

is there a why that I could  control the upgrading  procedure, like stop upgrading and rollback?

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.0.8
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment]
Currently, etcd is upgraded 1 at a time, while control plane and worker nodes were 50 at a time. 

As of 2.4 with our new feature for zero downtime upgrades, etcd and control plane will upgrade 1 at a time, while worker nodes will be upgraded based on a maxUnavailable setting. 

We will also introduce the ability to easily rollback to previous k8s versions based on snapshots. 
https://github.com/rancher/rancher/issues/22232#issuecomment-577276339
