### ISSUE TITLE
Ingress editor breaks rule paths ordering

### ISSUE THREAD

**Issue by patrikbeno** [rancher/rancher#17065]
**What kind of request is this (question/bug/enhancement/feature request):**

bug report

**Steps to reproduce (least amount of steps as possible):**

1. create ingress with 1 rule and 2 paths: [ "/something", "/" ], in this order
2. view in yaml: all ok, path order is as entered
3. edit in GUI: "/" is first, "/something is second". Save with no changes made.
4. view in yaml:  path order is changed and invalid: "/" is first, "/somehing" is second

**Result:**

- path ordering is broken on GUI edit. More precisely, during the load into the GUI editor.
- "/something" never matches anymore, because "/" is now first and is always prioritized.

**Other details that may be helpful:**

Woraround: always edit in YAML. Never save in GUI as it breaks the ordering.

**Environment information**

rancher/rancher:v2.1.2, docker, single node

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/49913455-9c0fde00-fec8-11e8-9f70-a5d9f66e39f4.png)
![image](https://user-images.githubusercontent.com/21168270/49913460-a5994600-fec8-11e8-8fae-4706c1ef2551.png)

The order in API is incorrect. We need to fix it in backend

**Comment by orangedeng** [comment]
@loganhz This change will require UI change for the API schema changed.

**Comment by vincent99** [comment]
Breaking the API is not something to be done casually.  Most languages preserve the order keys are entered, doesn't go have a way to?

**Comment by orangedeng** [comment]
@vincent99 As I found out in JSON-spec in http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2.1,
> object:
> An unordered set of properties mapping a string to an instance, from the JSON "object" production

In our API schema for `ingressRule`, it is defined as an json object for `paths`. I don't have any other ways to get around it beside breaking the API.
@ibuildthecloud Do you have a better idea for this one?

**Comment by vincent99** [comment]
We don't use JSON-schema.  While it's technically true that maps are unordered, the reality is there is an order and most languages preserve it (go's normal map intentionally randomizes it on iteration to discourage it).

Or you could add a `priority` int field.

Or sort the generated rules by path length.  Is there wildcard matching or something else that can go in here?  If literal prefixes is all that you can enter then I don't know why manual ordering is even needed, you sort by length so that `/a` and `/b` come first or `/` will always match everything.

**Comment by orangedeng** [comment]
Let's sort the path in reverse order. It would ensure that `/abc` is in front of `/a`.

**Comment by cjellick** [comment]
Reverse alphabetical ordering. This seems like a overly-simple, naive solution that is going to bite us in the future.
See: https://github.com/kubernetes/contrib/issues/885 / https://github.com/kubernetes/ingress-nginx/issues/555
How paths are interpreted is specific to the underlying provider. I have seen some truly complex pathing setups in the wild. I think we assume too much by thinking we can impose an arbitrary reverse alphabetical ordering and have that actually be what the customer wants/expects all the time.

@vincent99 your thoughts?

**Comment by cjellick** [comment]
@orangedeng @loganhz upon further discussion with @ibuildthecloud and @vincent99 and based on the last comment i made,
let's break the API to fix this. Change the type to a list so that order is definitely always preserved.

Carefully consider upgrade scenarios and how to handles those and make sure QA knows to test such scenarios

**Comment by cjellick** [comment]
This won't be moved to test until we can merge the UI and backend simultaneously, since it breaks the UI

**Comment by sangeethah** [comment]
Tested with latest build from master

1, Create ingress with 1 rule and 2 paths: [ "/name.html", "/" ], in this order
2. Edit ingress,  "/name.html" is first, "/" is second as expected. Save with no other changes.
3. View in yaml: path order is correct: "/name.html" is first, "/" is second

Api has been changed to accept paths as an ordered list:

```
rules: [{host: "test1.default.45.55.34.89.xip.io", paths: [,…], type: "/v3/project/schemas/ingressRule"}]
0: {host: "test1.default.45.55.34.89.xip.io", paths: [,…], type: "/v3/project/schemas/ingressRule"}
host: "test1.default.45.55.34.89.xip.io"
paths: [,…]
0: {path: "/name.html", serviceId: null, targetPort: 80, type: "/v3/project/schemas/httpIngressPath",…}
1: {path: "/", serviceId: null, targetPort: 80, type: "/v3/project/schemas/httpIngressPath",…}
``` 
Works as expected.
