### ISSUE TITLE
UI - Add existingClaim option for the charts if applicable

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17060]
UI for https://github.com/rancher/rancher/issues/16583

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/4/19)
Confirmed feature.
Validation steps:
- Create a PV on the cluster, Create a PVC under the default namespace.
- Launch a catalog app that supports this such as the ChartMuseum app and be sure to change the namespace of it to existing default.
- Pick from the "Uses Exsiting Persistent Volume Claim for LocalStorage" drop down and you'll see the PVC listed.

Ensured I can create the app with these settings and that it works.

Screenshot of this working:
![image](https://user-images.githubusercontent.com/45179589/50707926-d0863e00-101f-11e9-805c-f5f28fa1dc35.png)
