### ISSUE TITLE
master nodes are added to elb loadbalancer

### ISSUE THREAD

**Issue by Frintrop** [rancher/rancher#17064]
if you create an ec2 cluster with rancher and you have  masters without worker role the masters are tagged as "Unschedulable" but still be added from k8 as target of created loadbalancers.

rancher must  also label  "Unschedulable" nodes with  node-role.kubernetes.io/master="". this excludes master nodes as loadbalancer targets

**Comment by Frintrop** [comment]
see https://github.com/kubernetes/kubeadm/blob/master/docs/design/design_v1.9.md)

**Comment by superseb** [comment]
We use `node-role.kubernetes.io/etcd` and `node-role.kubernetes.io/controlplane` to identify nodes ((https://rancher.com/docs/rke/v0.1.x/en/config-options/nodes/#kubernetes-roles)
). 

The service controller has `node-role.kubernetes.io/master` hardcoded to exclude master nodes, which is a design discussions currently discussed in https://github.com/kubernetes/kubernetes/issues/65618. Adding the label yourself is a workaround, but this will probably mess something up in the node labels, I'd have to check that one.

**Comment by Frintrop** [comment]
yes. but master nodes should independend be up and running regardless of incoming traffic from loadbalancer ?!

**Comment by janeczku** [comment]
Same behaviour can be observed for Azure load balancer. Routing service traffic through master nodes is unexpected behaviour imho.
Kubernetes 1.16 introduced a new label that can should be used going forward to exclude nodes from being added to load balancer backend pools:
`node.kubernetes.io/exclude-from-external-load-balancers`
This label should be set by default on any RKE nodes that do not have the worker role.

**Comment by dr4Ke** [comment]
It is also true with openstack and the external cloud controller.
