### ISSUE TITLE
Unable to switch github account for pipelines

### ISSUE THREAD

**Issue by Nalha** [rancher/rancher#17062]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Go to pipelines -> Configure Repositories
2) Authorize & Fetch Your Own Repositories, log in to github account
3) Log out User *username*
4) Log in to another user

**Result:**
Instantly logged in to same user again, no option to log in to another github account

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.2

**Comment by gitlawr** [comment]
You will need to logout on github side before log in to another github account.
OAuth is used for the authentication, so it is done in the "OAuth Dance" way.

**Comment by gitlawr** [comment]
Feel free to reopen it if you have further questions
