### ISSUE TITLE
UI: Need a way to trigger an auth refresh on demand

### ISSUE THREAD

**Issue by maxkorp** [rancher/rancher#17075]
See https://github.com/rancher/rancher/issues/17067

We need a button added somewhere (in auth maybe?) to trigger a refresh of all users' groups.

**Comment by cjellick** [comment]
@maxkorp do you have a ticket to track the backend for exposing this as an action? or is it already exposed as an aciton?

**Comment by davidnuzik** [comment]
@westlywright could we briefly touch base on this tomorrow?

**Comment by tfiduccia** [comment]
@westlywright - 
- Add menu option to individual users
- Add refresh all button to user page

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/31
Verified fixed
