### ISSUE TITLE
Pipeline execution logs fail to load in HA install

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#17079]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Rancher HA installation with 3 rancher replica
2. Any cluster (hosted, custom)
2. In a project enable one of the example pipeline configuration
3. Trigger a build via Pipeline->Context Menu->Run
4. Once the build has completed click on the pipeline name to open the pipeline activity page
5. Then click on the run number, e.g.`#1`, to open the build details
5. Click on the different build steps repeatedly to dynamically fetch the execution logs
6. Observe whether the execution log is displayed on every attempt

**Result:**

Execution logs fail to load approx. 2 out of 4 times. Instead `Log is unavailable.` is displayed.

![screen shot 2018-12-12 at 22 05 17](https://user-images.githubusercontent.com/3813921/49899925-6e417f80-fe5d-11e8-94c5-c73ab7a12536.png)

**Other details that may be helpful:**

Upon inspecting debug logs for the `rancher/rancher` deployment pods, it could be observed that the timing of failed attempts to load the execution logs correlated to that of the following log event
> [DEBUG] service "p-qpn77-pipeline/minio" not found

Furthermore these log messages only occurred in the two cluster followers but never in the cluster owner pod instance, indicating that when the logs were loaded successfully the API request for the `p-qpn77-pipeline/minio` service was handled by the owner instance (successfully).

Source of log entry:
https://github.com/rancher/rancher/blob/efeb00a2576d14adabd08b4b6933503e1761ac5d/pkg/api/customization/pipeline/pipeline_execution_log.go#L90-L94

**Environment information**
- Rancher version: v2.1.3
- Installation option (single install/HA): HA with 3 rancher replicas

**Cluster information**
- Cluster type: Custom
- Kubernetes version (use `kubectl version`): v1.11.3

**Comment by rootwuj** [comment]
Version -2.2 master 12/24
Verified fixed
