### ISSUE TITLE
Need to add settings for user authentication refresh

### ISSUE THREAD

**Issue by maxkorp** [rancher/rancher#17074]
See https://github.com/rancher/rancher/issues/17067

2 new settings have been added
`AuthUserInfoMaxAgeSeconds` (`auth-user-info-max-age-seconds`) default `3600`
and
`AuthUserInfoResyncCron` (`auth-user-info-resync-cron`) default `0 0 * * *`

**Comment by westlywright** [comment]
I have a branch exposing these new params in the UI but am waiting until rancher/rancher#1776 & rancher/rancher#1775 backend fixes have been merged.

**Comment by cjellick** [comment]
You're issue numbers are wrong @westlywright but i believe all backend bits have been merged

**Comment by westlywright** [comment]
@cjellick fixed the issue references, will verify backend changes and open a PR for UI after.

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/29
Verified fixed
