### ISSUE TITLE
UI - Update EKS regions/AMIs/templates

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#17082]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
UI for https://github.com/rancher/rancher/issues/17580 https://github.com/rancher/rancher/issues/17561 https://github.com/rancher/rancher/issues/17579 https://github.com/rancher/rancher/issues/17580

**Comment by tfiduccia** [comment]
@n313893254 - The eks kubernetes version 1.10 is dimmed and I can't actually select it?  According to #17579 I should be able to select it?
![image](https://user-images.githubusercontent.com/11514927/52016302-67b8a700-24a1-11e9-9f80-77b33dd147ec.png)

**Comment by n313893254** [comment]
@tfiduccia I try master branch (2/2/2019)
When adding a cluster, I can select 1.11 and 1.10.
![image](https://user-images.githubusercontent.com/18737885/52159557-fa935480-26e0-11e9-9fc9-1da1999d4048.png)

But when editing a cluster, we cannot select a lower version. 
Are you add a cluster and cannot select 1.10?

**Comment by n313893254** [comment]
I reproduce the issue when `k8s-supported-versions-range` is `>= 1.10.0`

**Comment by jiaqiluo** [comment]
The bug is reproducible on master 2/4, the k8s version 1.10 is dimmed.

**Comment by westlywright** [comment]
@tfiduccia what you're seeing is a bug. The ui uses the setting `ui-k8s-supported-versions-range`, which at the time this ticket was created included the 1.10 support. 1.10 was removed in https://github.com/rancher/rancher/commit/d6b4bd22a9b32471863a050bdf48c5ed27d23e8f#diff-8cae2b257a070262d733c79cc16f917b so the UI now displays it as unsupported and as a result unselectable.

**Comment by ChrisMcKee** [comment]
@superseb is the change to add other regions to EKS likely to go out in a patch pre-2.2 becoming stable?

**Comment by tfiduccia** [comment]
Version - master 3/11
Verified fixed
