### ISSUE TITLE
Project Owner/Member cannot deploy a catalog app

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17084]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- DO cluster with 3 nodes, one role each 
- logged in as project owner/member, go to launch a catalog app 
- closed WordPress and gave its a unique name and namespace (in my case, they are `wordpress100`)
<img width="1520" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49906090-9fa25700-fe2d-11e8-9152-53475b264f28.png">

**Result:**
Failed to launch the app because of this error
```
namespaces "wordpress100" is forbidden: User "u-55mwq" cannot get namespaces in the namespace "wordpress100": RBAC: clusterrole.rbac.authorization.k8s.io "p-v48ps-namespaces-edit" not found
```
<img width="1482" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49906118-c19bd980-fe2d-11e8-99d0-9dbabd3bbb6f.png">

**Other details that may be helpful:**
It works if I added a namespace first, and then deployed the catalog app to that namespace.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.4-rc2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: jiaqi-rancher-2-1-3
ID: HUDH:QL2Q:UNRI:N5JV:UCPB:KFKM:JFHQ:FXFR:A2PV:YHFA:VPEX:HQB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

NOTE:  I don't see the issue in DO cluster with 1 node, all role in it.

**Comment by jiaqiluo** [comment]
The bug does NOT exist on v2.1.3

**Comment by StrongMonkey** [comment]
The client(UI) has to wait for the namespace to be full populated with RBAC before trying to create apps. @vincent99 @alena1108 i believe this bug is always there.

**Comment by cjellick** [comment]
How frequently does the repro?

**Comment by jiaqiluo** [comment]
@cjellick  I did not see it happen often. In most case, Rancher will generate a unique name for the app and its namespace. But in some very rare condition, I need to add a unique name manually, which will usually fail as the error in the ticket.
