### ISSUE TITLE
Project Owner/Member cannot remove namespaces

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17086]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- DO cluster with 3 nodes, one role each
- logged in as project owner/member, go to `Namespaces` page
- deleted some namespaces (in my case, deleted `wordpress100` and `wordpress7`)

**Result:**
the namespaces are gone from the list. But if logging as Admin and go to `Namespaces` page, you can see those two namespaces in the list under state `removing`
<img width="1510" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49906395-ed6b8f00-fe2e-11e8-97df-6c40e3cd98a9.png">

**Other details that may be helpful:**
```
> kubectl get ns wordpress7 -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2018-12-12T23:42:26Z"},{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2018-12-12T23:42:25Z"}]}'
    field.cattle.io/creatorId: u-55mwq
    field.cattle.io/projectId: c-57xw9:p-v48ps
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: 2018-12-12T23:42:24Z
  deletionTimestamp: 2018-12-12T23:42:35Z
  labels:
    cattle.io/creator: norman
    field.cattle.io/projectId: p-v48ps
  name: wordpress7
  resourceVersion: "267061"
  selfLink: /api/v1/namespaces/wordpress7
  uid: 9369aad5-fe67-11e8-942c-061c843b6212
spec:
  finalizers:
  - kubernetes
status:
  phase: Terminating
```
```
> kubectl get ns wordpress100 -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2018-12-12T23:47:42Z"},{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2018-12-12T23:47:41Z"}]}'
    field.cattle.io/creatorId: u-55mwq
    field.cattle.io/projectId: c-57xw9:p-v48ps
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: 2018-12-12T23:47:40Z
  deletionTimestamp: 2018-12-12T23:55:14Z
  labels:
    cattle.io/creator: norman
    field.cattle.io/projectId: p-v48ps
  name: wordpress100
  resourceVersion: "268341"
  selfLink: /api/v1/namespaces/wordpress100
  uid: 4fe06987-fe68-11e8-942c-061c843b6212
spec:
  finalizers:
  - kubernetes
status:
  phase: Terminating
```
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.4-rc2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: jiaqi-rancher-2-1-3
ID: HUDH:QL2Q:UNRI:N5JV:UCPB:KFKM:JFHQ:FXFR:A2PV:YHFA:VPEX:HQB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
NOTE: I don't see the issue in DO cluster with 1 node, all role in it.

**Comment by jiaqiluo** [comment]
The bug does NOT exist on v2.1.3

**Comment by StrongMonkey** [comment]
Couldn't reproduce it. 
The steps i tried:
1. Create rancher v2.1.4-rc2. created  3 node DO setup.
2. Create user test1. Add test1 as the project owner.
3. Create namespace test1. Delete test1. Both admin and test1 can't namespace test1 now.

@jiaqiluo Can you re-try this and keep the setup if you reproduce it? i couldn't find a chance to reproduce this.

**Comment by jiaqiluo** [comment]
After talking with @StrongMonkey and showing him my setup, we agree that this abnormal happens because Rancher server needs some time to finish the deleting, and refreshing the webpage several times to fetch the latest response could solve the problem.

**Comment by jiaqiluo** [comment]
The ticket is opened again because it reveals the problem that sometimes the Rancher server takes too long to remove a namespace. The initial setup where I saw the bug was deleted so I cannot reproduce it in new-created setups, but the bug does exist in some rare condition. It is worth to keep the ticket open and to do more investigation.
