### ISSUE TITLE
Catalog routing issue

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17089]
rancher/rancher:master 12/12

Issue one steps:

1. Go to `Catalog Apps` page
2. Click launch
3. Refresh the page

Issue two steps:

1. Go to `Catalog Apps` page
2. Click launch
3. Click `View Details` of an app
3. Refresh the page

Results:

It will go back to the `Catalog Apps` page.

Expected:

UI should stay at the page when users refresh it

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/18)
Confirmed fixed. Could not reproduce the issue in latest master. I also ensured that we can set categories / library to filter down the listings under Catalog apps, refresh, and our filters remain the same. Halo tested.
