### ISSUE TITLE
Unable to Configure OneLogin IdP on Rancher v1.6.12

### ISSUE THREAD

**Issue by fagun-tripathi** [rancher/rancher#17083]
Hi,

I configured OneLogin IdP for Rancher v1.6.12

Inside the Rancher, I used the Shibboleth-based Access Control feature to configure the IdP metadata, Private Key, Certificate as well as the fields for the SAML assertion ( Displayname, UID, User Name, Groups).

The Rancher is throwing this error after shibboleth authentication 
![image](https://user-images.githubusercontent.com/43222727/54245217-30500800-44ed-11e9-8500-95318f71442d.png)

**Comment by fagun-tripathi** [comment]
@loganhz Is this one of the issue associated with the Rancher v1.6.x ?

**Comment by loganhz** [comment]
Yes, this is Rancher 1.6 UI

**Comment by fagun-tripathi** [comment]
level=error msg="HandleSAMLPost: Error doing POST /v1/token

time="2019-03-13T00:03:55Z" level=error msg="GetSamlAuthToken failed to Get token from cattle with error Post https://rancher.<domain>.com/v1/token: dial tcp: lookup rancher.<domain>.com on x.x.x.x:53: no such host"

This is the error I am getting

**Comment by fagun-tripathi** [comment]
@loganhz  I am sorry to bother you, but would you be able to tell if this problem associated with Rancher internally, that it is not able to handle the SAML authentication process ? It worked fine before but it is throwing a 500 internal server error right now ?

Do I need to upgrade the Rancher version from the version 1.6.x for better integration stability over SAML ?

**Comment by deniseschannon** [comment]
@fagun-tripathi v1.6 has a generic "shibboleth" authentication that has been attempted to be used for multiple SAML providers. but we've learned that each provider has specific differences which makes it challenging to support all SAML providers. 

with v2.x, we have added specific SAML providers as tested authentication providers. 

currently onelogin idp is not a tested auth provider, but there have most likely been updates in the auth code between v1.6.12 and v1.6.26 (our latest version). i can't confirm that it would fix your issue, but you can try a fresh install to see if that works before upgrading. 

I'll be closing this issue as development on v1.6 is limited to critical bugs and security fixes. We currently do not support onelogin idp and will not be adding it into a future release.
