### ISSUE TITLE
Ability to create Regional Clusters in GKE

### ISSUE THREAD

**Issue by colinwilson** [rancher/rancher#17099]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement/Feature request

It'd be nice to be able to create [GKE Regional Clusters](https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters) via the UI `Add Cluster` feature.

![2018-12-13 22_35_11-rancher](https://user-images.githubusercontent.com/12916656/49971778-8a115800-ff27-11e8-854c-7fe674c099e0.png)

**Comment by jiaqiluo** [comment]
The feature enhancement is validated in Rancher: master-head 5216a35d

Steps:
- add a GKE cluster with setting the `Location Type` to `regional` 

Results:
- the API call sends the correct values to the backend 

<img width="397" alt="Screen Shot 2019-08-16 at 8 45 09 AM" src="https://user-images.githubusercontent.com/6218999/63182195-da850c00-c006-11e9-99ec-a48407cac7aa.png">


- the cluster is created successfully in Google Cloud as a regional cluster

<img width="281" alt="Screen Shot 2019-08-16 at 8 55 02 AM" src="https://user-images.githubusercontent.com/6218999/63182236-f5f01700-c006-11e9-8c2b-c5662a8a52b6.png">

- the cluster is active and functional in Rancher 
- Editing the cluster to change the count of node works as expected
