### ISSUE TITLE
Cluster post deploy action

### ISSUE THREAD

**Issue by mikenorgate** [rancher/rancher#17091]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

I would like to be able to configure some sort of hook to allow me to run a custom script after a new cluster has been deployed. My initial thought would be to configure a pod/job that is runs either in the new cluster or in the rancher cluster.

My main use cases are:
    - Install apps that we always deploy to a cluster, things like cert-manager, ingress controller (in the case of Azure AKS)
    - Connect the cluster to our Vault instance
   -  Create a project for our apps 

The post deploy action would need to be passed details about the new cluster in order to (probably) use the Rancher CLI to perform the actions

**Comment by superseb** [comment]
Anything regarding the cluster creation can be done in the user-addons is described in https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/user-defined-add-ons/.

Having default apps/workloads deployed is a subset of https://github.com/rancher/rancher/issues/14337.

If anything else has to be done, you can use the Rancher CLI to automate tasks to create projects/namespaces or basically what you need.

**Comment by superseb** [comment]
Let me know if those do not cover what you are looking for.
