### ISSUE TITLE
Node Pools as a first class resource

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#17095]
We need to make node pools a resource so that we easily edit them and drive the creation of nodes from them.

Design doc:
https://docs.google.com/document/d/1T0SrEvBIMgkmQuLFO9dXkiIf8H-tjIMjmpRt3JgV7Io/edit?usp=sharing

**Comment by nathan-jenan-rancher** [comment]
We need to make sure that this issue is addressed as a part of this feature:

https://github.com/rancher/rancher/issues/13596

**Comment by deniseschannon** [comment]
Closing this in favor of the node pool support added in refactored versions for EKS (available as of v2.5.0).

AKS and GKE are currently targeted for v2.5.7 (end of April).

The node pool support will be available for each hosted provisioner as it's added in.
