### ISSUE TITLE
Scheduling ignores required tag sometimes?

### ISSUE THREAD

**Issue by smurfy** [rancher/rancher#17090]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

i cant reproduce manually. Tried by manually increasing scaling, all new containers start on the correct host.

**Environment information**
rancher 1.6.23
single

Two hosts, one main and one "special" host i use for testing only.

 The special host has required tag rancher.io.system and special=true

**Issue encountered**

Tonight all load-balancer services and one database service restarted, based on the logs by healthcheck ("Removing unhealthy service instance")

But they restarted on the wrong host, "special" instead of the main host.

Scheduling settings are default (auto pick host, with no rules), for most services. Only the services i really want on the special host have run on host option.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
