### ISSUE TITLE
UI - TCP load balancer still shows stickiness options

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1709]
When selecting TCP for the load balancer, stickiness options are still present in the UI. Maybe for TCP stickiness could be based on IP but certainly not cookie or existing cookie.

**Comment by deniseschannon** [comment]
@alena1108 Is this stickiness option supported in the API for load balancers with TCP?

**Comment by vincent99** [comment]
No; they work by reading/setting cookies and TCP mode means it is blindly copying the message because haproxy will have no idea what protocol it it.  The stickiness options should be grayed out unless there is at least one http listener.

**Comment by deniseschannon** [comment]
v0.37.0-rc1
Verified Fixed. When selecting a tcp protocol in load balancer, the stickiness is disabled.
