### ISSUE TITLE
Provide UI support for adding Private Registries when creating a cluster

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#17109]
Being able to add private registries using RKE when creating a cluster is a very useful feature. Without this, if I have to provide access to a private registry for all the projects, I will end up adding the same registry details over and over for all the projects, which is quite tedious.

At first, it might sound like a security issue, adding the private registry with auth to the host, but there are enterprises, where they know what they are exactly doing and this solves their problem.

Currently, we already have the UI components to add Registry details, we just need to bring those into the Cluster Create Page. This can be done from the YAML as documented, but it's quite tricky when using GCR service account JSON. Having a UI is very helpful.

Also, I request that we continue to support RKE Private Registries this way till we have a cross-project Registry support or some other means of Cluster wide Registry.

**Comment by deniseschannon** [comment]
@alena1108 @ankur111 should this be considered for the cluster templates issue? 
https://github.com/rancher/rancher/issues/14337

**Comment by westlywright** [comment]
@deniseschannon @leodotcloud Am I missing something or is this feature actually different from the `Private Registries` section when creating an RKE cluster?

**Comment by leodotcloud** [comment]
@westlywright You are right, the Private Registries section is what I was looking for.
