### ISSUE TITLE
Liveness probe http headers issue

### ISSUE THREAD

**Issue by Stonedge** [rancher/rancher#17100]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Set a liveness/readiness probe on an existing deployment with additional http headers (e.g. Authorization) using the ui , apply the change.

**Result:**
the headers is missing(ui don't show headers value nor name) and those are not apply to the probe.

**Other details that may be helpful:**
Probe Hostname headers also didn't seem to work 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.1.1
- Installation option (single install/HA):HA

**Comment by loganhz** [comment]
Thanks fro the report.
It has been fixed with https://github.com/rancher/rancher/issues/16853
It will be released in `v2.2.0`
