### ISSUE TITLE
Windows clusters - add support for multiple subnets

### ISSUE THREAD

**Issue by garyellis** [rancher/rancher#17102]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

Add support for custom clusters with Windows workers to run in multiple subnets.

Currently, Rancher 2.x clusters running Windows worker nodes, requires that all cluster members belong to the same layer 2 subnet. When nodes are on separate layer 2 networks, flannel `host-gw` networking does not work. In other words, `host-gw` back end is not able to setup routes to pod networks and routing between pod networks must be configured manually.

It will simplify HA and data center deployments where windows and linux systems are on separate networks if a usable overlay cni option can be determined even if it is in an alpha or experimental state.

**Comment by sowmyav27** [comment]
verified on `rancher:master` and `rancher:v2.3.0-alpha1`

- Custom cluster  - 1etcd & contrlo plane linux node
- 1 worker node - linux node
- 2 windows worker nodes

All the above nodes were created on different subnets.
Verified network connectivity between different workloads, ingresses and dns entries.
they work fine
