### ISSUE TITLE
cattle-cluster-agent can not access rancher-server-ip/ping

### ISSUE THREAD

**Issue by yudar1024** [rancher/rancher#17105]
**What kind of request is this (question/bug/enhancement/feature request):**
 cattle-cluster-agent

**Steps to reproduce (least amount of steps as possible):**
install 3 nodes k8s cluster use rancher server custom manner, 1 master  2 nodes
   master and nodes use rancher.me(192.168.x.x  rancher.me record in /etc/hosts) to point rancher server
install istio 1.0.4
deploy helloworld exmaple of istio 

cattle-cluster-agent always error state 

**Result:**

log of pod

```
INFO: Environment: CATTLE_ADDRESS=10.42.0.52 CATTLE_CA_CHECKSUM=bef8cee61dab2c6de88cb8444a5cc16203e6f82559faaec81b27e34aec479d27 CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-766dfbf568-n7dbk CATTLE_SERVER=https://rancher.me
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local localdomain options ndots:5
ERROR: https://rancher.me/ping is not accessible (Failed to connect to rancher.me port 443: Connection refused)
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.3
- Installation option (single install/HA):
single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):
1.12.3

```
(paste the output here)
```

- Docker (use `docker info`):
18.09.0

```
(paste the output here)
```

**Comment by superseb** [comment]
Rancher installs require a resolvable DNS name, not via a workaround in `/etc/hosts`. That works for the node-agents but not for the cluster agent as it uses the clusters DNS to resolve names. See https://github.com/rancher/rancher/issues?q=is%3Aissue+cattle-cluster-agent+dns+is%3Aclosed for more examples.

If you believe there is a bug here, let me know.

**Comment by yudar1024** [comment]
can i use ip directly for node-agents?

**Comment by gatici** [comment]
Dear  @superseb ,

Is there  any solution for it ? 
how  this  cattle-cluster-name  will be  resolved?
