### ISSUE TITLE
TPROXY support

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1710]
Does the load balancer support TPROXY? Will it forward the IP address along when proxying in TCP mode?

**Comment by ibuildthecloud** [comment]
No it's not.  The problem with TPROXY is that haproxy must be the default route of return traffic.  This causes various difficult problems.  For example how do I have two load balancers running on two VMs with RR DNS between them.

Let me know if you think of some creative way to support it.  The easier route would probably be to support proxy protocol.

**Comment by defunctzombie** [comment]
Gotcha, makes sense. Also easy for users to deploy whatever they need if they have such a requirement.
