### ISSUE TITLE
Error initializing the SP client unsupported key type "DSA PRIVATE KEY"

### ISSUE THREAD

**Issue by ocasta** [rancher/rancher#17107]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**
Shibboleth auth to Google provider
Updated from v1.6.14 to 1.6.25

**Result:**
Auth service fails to start

time="2018-12-14T08:39:12Z" level=info msg="Starting Rancher Auth service"

time="2018-12-14T08:39:12Z" level=info msg="Config stored"

time="2018-12-14T08:39:12Z" level=info msg="Auth provider configured shibbolethconfig"

time="2018-12-14T08:39:12Z" level=error msg="Error initializing the SP client unsupported key type \"DSA PRIVATE KEY\""

time="2018-12-14T08:39:12Z" level=error msg="Error initializing the provider unsupported key type \"DSA PRIVATE KEY\""

time="2018-12-14T08:39:12Z" level=fatal msg="Failed to reload the auth provider from db on start: unsupported key type \"DSA PRIVATE KEY\""

**Other details that may be helpful:**

**Environment information**
RancherOS
rancher os 1.0.4

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v1.6.14 -> 1.6.25

- Installation option (single install/HA):
HA

**Comment by deniseschannon** [comment]
It sounds like you are trying to use google auth provider, which isn't supported. 

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
