### ISSUE TITLE
Alert advanced options do not seem to be working

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17114]
Version: master 2.2 (12/14/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add a custom alert group. Set up a simple one that is guaranteed to go off such as if the Node CPU goes over 2%. Set it up to alert one of your notifiers you have configured.
- Wait to receive an alert. Edit the alert group. Change the advanced options so that you will get alerts much more often such as every minute. Notice this doesn't seem to take any effect after saving even though the server was updated correctly (HTTP).
- Turn off monitoring on the custer and you'll suddenly get many alerts. Turn it back on and this will happen again. Once it happens though it will still take an hour to get the alert to repeat send to notifier(s).

**Result:**
If you edit your alert group such as to make alerts repeat more often (send repeatedly to the notifier much more often) this doesn't seem to work.
Screenshot of my advanced settings:
![image](https://user-images.githubusercontent.com/45179589/50025370-87a01400-ffa2-11e8-8030-83d861d623c8.png)

I expect that this is constantly alerting because my CPU on the node is always above 15% constantly. As such based on my settings I expect to get a notification every 30 seconds approximately. I only get one notification, however. I suspect if I wait one hour I might get a second. This would indicate my settings to decrease Repeat Interval Time were not taken.

This issue might only be around Repeat Interval Time but could also include the others under advanced options.

**Comment by rootwuj** [comment]
Tested with Rancher version-2.2 master 01/23.
Verified fixed
This version can be repeated alerts.
