### ISSUE TITLE
Make the API receive a yaml as an answers file

### ISSUE THREAD

**Issue by dedsm** [rancher/rancher#17122]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

Right now the API receives a custom structure that flattens the content of the answers.yaml into a simple hash with dots to represent levels and all the values as string.

That works for some cases but notably fails with others, I was recently bitten by #13158 and #16680 

I guess the reason rancher has this custom format is because it's easier in the UI to fill it, but at least there should be an option to send a real YAML in both the UI and the API for the "advanced" cases.

A real life scenario is the grafana chart (and basically any chart that has an ingress), a common annotation is something like `kubernetes.io/ingress.class: nginx` it results in the deployment as 
```yaml
kubernetes: 
  io/ingress:
      class: nginx
```

**Comment by dedsm** [comment]
@vincent99 helm provides the `-f` flag to send a "real yaml" file, as in not flattened in dot notation, support for that would be appreciated in both the API and the UI.

Another problem I'm recently encountering, if I want to have an answer being a json string, `helm install -f values.yaml | rancher kubectl apply` works as intended, while I get `Helm template failed. Error: failed parsing --set data: key "\n \"datasource\": \"-- Grafana --\"" has no value (cannot end with ,) : exit status 1` if I load the same values.yaml in the UI and deploy or I flatten it myself and use the API

**Comment by dedsm** [comment]
https://github.com/rancher/rancher/pull/15448 is exactly what I'm looking for I think

**Comment by loganhz** [comment]
users can pass the real YAML to backend in 2.2.
You can config it by clicking `Edit as YAML` in launch catalog page.

**Comment by jiaqiluo** [comment]
The enhancement is validated on rancher v2.2.0-rc2. 

Steps:
- run rancher v2.2.0-rc2
- add a DO cluster
- launch WordPress catalog app
- test 1: Edit the config yaml file by clicking `Edit as YAML` 
- test 2: Edit the config yaml file by clicking `Edit as YAML` then `Read from File`
