### ISSUE TITLE
System catalog framework

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17126]
By this point, we've deployed prometheus as a system chart. We would like to have a general framework for managing all chart-based system components. Then we can migrate alerts and pipelines to this framework.

**Comment by cjellick** [comment]
Not sure if the framework will make it into v2.2. We need to assess if we can release monitoring without it and then update later. Will discuss with @ibuildthecloud.
Marking as priority/0 with the assumption that it IS necessary for 2.2, until we can prove it otherwise

**Comment by loganhz** [comment]
Move this out from 2.2 after discussed with @cjellick

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/19487

**Comment by cjellick** [comment]
Min/max version is implemented and tracked in a different issue. We will not be introducing an general automatic upgrade feature for v2.3, which is what I think this represents. Moving out.

**Comment by deniseschannon** [comment]
The updated apps framework in v2.5.0 used in cluster Dashboard is the path forward to how to serve Helm charts. It also has ability to indicated dependencies across charts. 

Monitoring v2 has moved from being embedded in Rancher to a helm chart that deploys all components for monitoring.
