### ISSUE TITLE
Assigning jobs to pipeline engine; buildinfo result failure

### ISSUE THREAD

**Issue by milovanderlinden** [rancher/rancher#17120]
I have set up jekyll test to see if I can use pipelines to build a static website through jekyll. When I run it, It fails before the first step (clone). With the error as shown in the screenshot. Configuration is exactly as available in the repository.

![image](https://user-images.githubusercontent.com/106038/50044354-76c6cf80-0082-11e9-9647-bf6b93397584.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.3` UI: `v2.1.17` |
|Route|`authenticated.project.pipeline.pipelines.run`|
Pipeline repository available at https://github.com/milovanderlinden/pipeline-example-jekyll.git

**Comment by gitlawr** [comment]
The cause is that there's an invalid step configuration in the pipeline file.
```- name: Deploy
  steps:
  - {} #remove this line
  - applyYamlConfig:
      path: ./deployment.yaml
```
Removing the 15th line helps to resolve it.

We can improve validation so that users can figure out what's going on more easily.

**Comment by milovanderlinden** [comment]
Thank you! I am now a step further and get a permission denied during build, but I will be able to solve this.
```bash
04:01:41 [pipeline_p-gvjnd-2] Running shell script
04:01:43 + jekyll build
04:01:43 ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-musl]
04:01:44 [33mConfiguration file: none[0m
04:01:44             Source: /home/jenkins/workspace/pipeline_p-gvjnd-2
04:01:44        Destination: /home/jenkins/workspace/pipeline_p-gvjnd-2/_site
04:01:44  Incremental build: disabled. Enable with --incremental
04:01:44       Generating... 
04:01:44 jekyll 3.8.5 | Error:  Permission denied @ dir_s_mkdir - /home/jenkins/workspace/pipeline_p-gvjnd-2/_site
```

**Comment by arbermarleku** [comment]
I am having the same problem @gitlawr 

My Yml is down bellow
Can you give me a hint what i am doing problem

`stages:
- name: Build Backend
  steps:
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :api:shadowJar
    when:
      branch:
        include:
        - api*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :collector:shadowJar
    when:
      branch:
        include:
        - collector*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :consumer:shadowJar
    when:
      branch:
        include:
        - consumer*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :sync:shadowJar
    when:
      branch:
        include:
        - sync*
      event:
        include:
        - tag
- name: Publish to QA
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/qa/Dockerfile
      buildContext: .
      tag: kodelabs-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - api-qa*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/qa/Dockerfile
      buildContext: .
      tag: kodelabs-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - collector-qa*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/qa/Dockerfile
      buildContext: .
      tag: kodelabs-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - consumer-qa*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/qa/Dockerfile
      buildContext: .
      tag: kodelabs-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - sync-qa*
      event:
        include:
        - tag
- name: Publish to Staging
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/stagign/Dockerfile
      buildContext: .
      tag: kodelabs-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - api-staging*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/stagign/Dockerfile
      buildContext: .
      tag: kodelabs-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - collector-staging*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/stagign/Dockerfile
      buildContext: .
      tag: kodelabs-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - consumer-staging*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/stagign/Dockerfile
      buildContext: .
      tag: kodelabs-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - sync-staging*
      event:
        include:
        - tag
- name: Publish to Production
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/prod/Dockerfile
      buildContext: .
      tag: kodelabs-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - api-production*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/prod/Dockerfile
      buildContext: .
      tag: kodelabs-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - collector-production*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/prod/Dockerfile
      buildContext: .
      tag: kodelabs-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - consumer-production*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/prod/Dockerfile
      buildContext: .
      tag: kodelabs-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - sync-production*
      event:
        include:
        - tag
- name: Deploy to QA
  steps:
  - applyYamlConfig:
      path: .k8s/api/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - api-qa*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/collector/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - collector-qa*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/consumer/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - consumer-qa*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/sync/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - sync-qa*
      event:
        include:
        - tag
- name: Deploy to Staging
  steps:
  - applyYamlConfig:
      path: .k8s/api/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - api-staging*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/collector/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - collector-staging*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/consumer/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - consumer-staging*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/sync/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - sync-staging*
      event:
        include:
        - tag
- name: Deploy to Production
  steps:
  - applyYamlConfig:
      path: k8s/api/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - api-production*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/collector/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - collector-production*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/consumer/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - consumer-production*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/sync/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - sync-production*
      event:
        include:
        - tag`
