### ISSUE TITLE
When all cluster drivers are enabled add cluster page looks bad

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17133]
Version: master 2.2 (12/14/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable all the cluster drivers via the "Custom Drivers" page
- Try to add a cluster

**Result:**
Notice that the arrangement of the infrastructure providers is not good. Things are not aligned in a proper grid. This may be because some grid items are not the proper size/shape.
Notice that pictures are missing for "Open Telekom Cloud" and "SoftLayer"
Note, if you inspect the page source you'll see that class machine-driver softlayer and machine-driver otc do not have a background image defined in CSS. If these two drivers do not have images perhaps this is related to the issue of them both being odd shapes in the grid.
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/50099985-9c67ec00-01dc-11e9-8d60-932453e0b499.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/2559

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/10/19)
Confirmed fix. The alignment of the tiles is nice now. Tested browser resizing as well and this looks good too.
![image](https://user-images.githubusercontent.com/45179589/50991410-cb1e6d00-14d1-11e9-98e8-8447dde5a27c.png)
