### ISSUE TITLE
When restart master, Cannot connect host_ip:8080 from docker container because of CATTLE_PREROUTING

### ISSUE THREAD

**Issue by bxy09** [rancher/rancher#1713]
With `iptables -L -t nat` on host, I find that threre is rule not cleared as:
```
DNAT       tcp  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL tcp dpt:8086 to:former_master_docker_ip:8080
```

After deleting this rule , master works.

**Comment by oomathias** [comment]
Seems like it's related to my issue #1702

**Comment by deniseschannon** [comment]
@bxy09 I haven't been able to reproduce getting the old rule in the iptable upon a restart. 

Can you share your Rancher version? Where did you launch Rancher? (AWS, GCE, locally?) and also what was in your setup? (General number of hosts/containers)/

**Comment by deniseschannon** [comment]
If you can reproduce and provide more information, I will re-open this issue for you. If it's related to #1702, a fix has been made and available.
