### ISSUE TITLE
Install rancher app to specific namespace 

### ISSUE THREAD

**Issue by MoHD20** [rancher/rancher#17132]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
I want to install rancher app to specific namespace So that gitlab private registry credentials could be used. I'm using `rancher` cli command.

To install the app I'm using:
```
rancher app install --answers ans.yaml rancher-app
```

**Result:**
It installs the app on its own namespace and it errors cause the images don't get pulled from the gitlab registry.

I searched for away to make the creds secret to be available for all namespace but I don't think this could be done.  

I can't find anything on the [docs](https://rancher.com/docs/rancher/v2.x/en/cli/)  regards this issue.

**Comment by MoHD20** [comment]
@superseb  Is this possible  in the current version of rancher?

**Comment by loganhz** [comment]
Please use `--namespace`  https://github.com/rancher/cli/blob/master/cmd/app.go#L168
