### ISSUE TITLE
unable to import existing k8s cluster in to rancher 

### ISSUE THREAD

**Issue by arunbpt7** [rancher/rancher#17134]
[root@myinfra ]# kubectl get pods -n cattle-system
NAME                                    READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-865b4bd6cb-dcxgw   1/1     Running   0          12m
cattle-node-agent-rcptp                 1/1     Running   0          12m
[root@myinfra ]#

 kubectl logs -f cattle-node-agent-rcptp -n cattle-system
INFO: Environment: CATTLE_ADDRESS=10.253.8.238 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=50ca35c4f9c00a9884884b890b0fabef224d45960dd4d2ff6117363ee2d4a19c CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=node3 CATTLE_SERVER=https://10.253.8.240
INFO: Using resolv.conf: nameserver 10.253.16.207
INFO: https://10.253.8.240/ping is accessible
INFO: Value from https://10.253.8.240/v3/settings/cacerts is an x509 certificate
time="2018-12-17T16:44:58Z" level=info msg="Rancher agent version v2.1.3 is starting"
time="2018-12-17T16:44:58Z" level=info msg="Option requestedHostname=node3"
time="2018-12-17T16:44:58Z" level=info msg="Option customConfig=map[address:10.253.8.238 internalAddress: roles:[] label:map[]]"
time="2018-12-17T16:44:58Z" level=info msg="Option etcd=false"
time="2018-12-17T16:44:58Z" level=info msg="Option controlPlane=false"
time="2018-12-17T16:44:58Z" level=info msg="Option worker=false"
time="2018-12-17T16:44:58Z" level=info msg="Listening on /tmp/log.sock"
time="2018-12-17T16:52:27Z" level=info msg="Connecting to proxy" url="wss://10.253.8.240/v3/connect"
time="2018-12-17T16:52:29Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-12-17T16:52:29Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-12-17T16:52:39Z" level=info msg="Connecting to wss://10.253.8.240/v3/connect with token jxzqcg7mkllcvh464czlvvzccb7sbrjpc95zx2vnrtwmrc6twxmrjr"
time="2018-12-17T16:52:39Z" level=info msg="Connecting to proxy" url="wss://10.253.8.240/v3/connect"
time="2018-12-17T16:52:41Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-12-17T16:52:41Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-12-17T16:52:52Z" level=info msg="Connecting to wss://10.253.8.240/v3/connect with token jxzqcg7mkllcvh464czlvvzccb7sbrjpc95zx2vnrtwmrc6twxmrjr"
time="2018-12-17T16:52:52Z" level=info msg="Connecting to proxy" url="wss://10.253.8.240/v3/connect"

Rancher container Logs 

or cluster c-hmkcd: failed to contact server: Get https://10.99.0.1:443/version?timeout=30s: dial tcp: lookup http on 10.99.0.3:53: no such host
2018/12/17 16:48:31 [INFO] Stopping cluster agent for c-hmkcd
2018/12/17 16:48:31 [ERROR] ClusterController c-64qxx [user-controllers-controller] failed with : failed to start user controllers for cluster c-hmkcd: failed to contact server: Get https://10.99.0.1:443/version?timeout=30s: dial tcp: lookup http on 10.99.0.3:53: no such host
2018/12/17 16:48:31 [INFO] Stopping cluster agent for c-hmkcd
2018/12/17 16:48:32 [INFO] Stopping cluster agent for c-hmkcd
2018/12/17 16:48:32 [ERROR] ClusterController c-64qxx [user-controllers-controller] failed with : failed to start user controllers for cluster c-hmkcd: failed to contact server: Get https://10.99.0.1:443/version?timeout=30s: dial tcp: lookup http on 10.99.0.3:53: no such host
2018/12/17 16:48:33 [INFO] 2018/12/17 16:48:33 http: multiple response.WriteHeader calls
2018-12-17 16:48:34.690981 W | etcdserver: apply entries took too long [185.406321ms for 1 entries]
2018-12-17 16:48:34.691041 W | etcdserver: avoid queries with large range/delete range!
2018/12/17 16:48:37 [INFO] Stopping cluster agent for c-hmkcd

**Comment by arunbpt7** [comment]
The environment is as below

Kubernetes cluster running on baremetal and it is behind corperate proxy .. and rancher container is running on another centos 7 VM

**Comment by arunbpt7** [comment]
Can someone please help to resolv this issue

**Comment by loganhz** [comment]
Please file another issue with the configuration of your proxy if you can still reproduce the issue.
