### ISSUE TITLE
Failover not working on Rancher Kube cluster

### ISSUE THREAD

**Issue by ssirag** [rancher/rancher#17142]
**Failover Question:**

I've got a Rancher-installed Kubernetes cluster on Ubuntu 18.04, standing up the cluster with no customization except that I added heketi/gluster storage for storage redundancy.  Maybe I'm missing some step here, but my sample app containers do not fail over to a working node when the node they're on is down.  I've waited 15 minutes with no action being taken by the cluster except it shows that the desired number of containers is not available.  Once I turn the down node back on, the containers there resume.  I'd expect this for daemonsets but not for regular apps like mysql.

I've looked at this case https://github.com/rancher/rancher/issues/14712 referencing setting tighter time limits for down containers before they are recovered, and in following the advice I've found that the cluster's yaml file doesn't even have an active kube_api or kube_controller section.  I do have this, but as you can see, it is commented out:

![image](https://user-images.githubusercontent.com/8559431/50115599-ddc8bd80-0215-11e9-8413-5e5a2148ccfb.png)

So am I missing some major step, or does swarm really kick Kubernetes' butt in re-scheduling down containers elasewhere?

**Environment information**
- Rancher version: v2.1.1
- Installation option (single install/HA): Single install
- Network: flannel

**Cluster information**
- Cluster type: Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4 vcpu's, 16 GB RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker (use `docker info`):

```
Containers: 106
 Running: 95
 Paused: 0
 Stopped: 11
Images: 42
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-42-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65GiB
Name: vva-er-k8s0
ID: GBFE:IF3Z:ZQTI:7SIW:MN55:HM33:QKMA:4G6D:PZGN:PPQU:PMAP:XIFQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

```

**Comment by superseb** [comment]
If there are no services defined, the defaults are used. You can add/override parameters as described in https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file and we have a FAQ entry describing the default Kubernetes behavior: https://rancher.com/docs/rancher/v2.x/en/faq/technical/#why-does-it-take-5-minutes-for-a-pod-to-be-rescheduled-when-a-node-has-failed

By default, it takes around 5 and a half minutes to reschedule a pod. If this doesn't happen, please describe steps to reproduce and the output from the `kube-controller-manager` container and `kubectl describe` output from the resource you created.

**Comment by ssirag** [comment]
OK... my cluster config yaml file contains the following service section:

services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api: 
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kube-controller: 
    extra_args: 
      node-monitor-grace-period: "16s"
      node-monitor-period: "2s"
      pod-eviction-timeout: "30s"
  kubelet: 
    extra_args: 
      node-status-update-frequency: "5s"
    fail_swap_on: false

I'm still not seeing any failover.

**Comment by superseb** [comment]
How many nodes with what roles do you have in the cluster? Did you confirm the settings were applied (`docker inspect kube-controller-manager`) on the hosts? What are you deploying and what is the logging as requested in https://github.com/rancher/rancher/issues/17142#issuecomment-448001465

**Comment by ssirag** [comment]
I have 3 master nodes with all roles assigned, one worker node with just worker assigned.

I do see the kube-controller-manager container, and the age of it matches when I added the kube-controller args to the cluster yaml.
(docker ps output):

468f26f3de88        rancher/hyperkube:v1.11.3-rancher1   "/opt/rke-tools/entr…"   18 hours ago        Up 18 hours                             kube-controller-manager

However, if I "kubectl get service --all-namespaces" I don't see it listed as a service.  Same with pods.

![image](https://user-images.githubusercontent.com/8559431/50165156-4ebdb300-02b2-11e9-9b6b-73463848f9f0.png)

![image](https://user-images.githubusercontent.com/8559431/50165129-41082d80-02b2-11e9-8174-bd7e9f7ecce0.png)

The last lines of the container logs:

I1217 22:08:52.603563       1 controllermanager.go:122] Version: v1.11.3
W1217 22:08:52.604052       1 authentication.go:55] Authentication is disabled
I1217 22:08:52.604164       1 insecure_serving.go:49] Serving insecurely on [::]:10252
I1217 22:08:52.605217       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/kube-controller-manager...

**Comment by superseb** [comment]
Let me know if this still causes issues, this should be default Kubernetes logic. The logs requested are from all `kube-controller-manager` containers as there is only one active which will log the actions.
