### ISSUE TITLE
Cluster and Node CPU/Mem wheels do not update with rke provider

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17143]
Version: master 2.2 (12/17/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Set up a cluster with default settings. I used DigitalOcean. I had one node with etcd,CP,worker.
- View the cluster dashboard. The CPU/Memory/Pods wheels will update once and then never again. They may stay stuck at approximately 27% CPU, 4% memory, 8/110 (7%) pods forever.
- Try to add a workload to increase CPU and the wheel still will not update nor the Memory wheel. The Pods wheel will update however.
- Try again with a non-rke provider such as GKE. Everything works fine. Thus it's believed to be an issue with rke not updating counts in the API. (allocatable and requested ?)

**Result:**
CPU/Memory pods never update with rke provider.

**Other details that may be helpful:**
This is not related to Prometheus monitoring, this is the default monitoring have without Prometheus enabled.

**Comment by loganhz** [comment]
@davidnuzik Could you try if refresh browser can fix it?

**Comment by davidnuzik** [comment]
@loganhz refreshing the browser or clearing browser cache did not fix the issue for me.

**Comment by n313893254** [comment]
I try custom node to set up a cluster, select a workload and scale pod to 50. (image: ubuntu:xenial)
Check the API found the pod changes, but CPU/Mem not changes. 
![image](https://user-images.githubusercontent.com/18737885/51236362-f101b100-19ac-11e9-8aa2-4304bda38652.png)
@loganhz I think it is backend issue.

**Comment by loganhz** [comment]
I cannot reproduce it on DO.
steps:

1. Create a cluster on DO
2. Look at the current wheels
3. Deploy a workload with 1000 memory reservation and 1000 cpu reservation.
4. The wheels updated automatically

![image](https://user-images.githubusercontent.com/21168270/51794073-12ad3480-2206-11e9-9d3f-68206c1304c9.png)
![image](https://user-images.githubusercontent.com/21168270/51794074-1771e880-2206-11e9-9790-52f9a2552db7.png)
![image](https://user-images.githubusercontent.com/21168270/51794086-38d2d480-2206-11e9-8138-9dfe992b63bd.png)
