### ISSUE TITLE
Elasticsearch Logging wrong project

### ISSUE THREAD

**Issue by quick691fr** [rancher/rancher#17144]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1/ Create a cluster with AWS (using EC2 nodes)
2/ Create 2 projects (let say name1 and name2)
3/ Install mongoDB helm-mongodb-replicaset Helm chart from catalog app on project name1. I actually use 3.6.1 version
4/ Install an Elasticsearch for logging purposes
5/ Activate Logging in project name1 to use elastisearch from step 4/
6/ Activate Logging in empty project name2 to use elastisearch from step 4/

**Result:**
If you check indexes from project name2, you'll see name1 project mongodb logs. name2 indexes should not contain logs from another project.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider Amazon EC2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud T2.medium (for controller) and T3.medium (workers)
- Kubernetes version (use `kubectl version`): 1.11.3

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 74
 Running: 55
 Paused: 0
 Stopped: 19
Images: 32
Server Version: 17.03.2-ce
Storage Driver: devicemapper
 Pool Name: docker-259:1-20971765-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.763 GB
 Data Space Total: 107.4 GB
 Data Space Available: 23.04 GB
 Metadata Space Used: 9.638 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.149-RHEL7 (2018-07-20)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.4-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.794 GiB
Name: dev-t3lg-wrkr-2
ID: UA2Y:OC34:PHA7:KIXF:YQRB:HWLA:HCLL:KQLN:4F2K:7YIM:OVYF:I7OA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=amazonec2
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for pro                          duction use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage de                          vice.
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by quick691fr** [comment]
It seems to appear only on empty project (the one without any workload on it)

**Comment by kingsd041** [comment]
Version: master 2.2 (2/15/19)  Image ID: 0fbe8118f412
Confirmed fix. 

> **Steps to reproduce (least amount of steps as possible):**
> 1/ Create a cluster with AWS (using EC2 nodes)
> 2/ Create 2 projects (let say name1 and name2)
> 3/ Install mongoDB helm-mongodb-replicaset Helm chart from catalog app on project name1. I actually use 3.6.1 version
> 4/ Install an Elasticsearch for logging purposes
> 5/ Activate Logging in project name1 to use elastisearch from step 4/
> 6/ Activate Logging in empty project name2 to use elastisearch from step 4/
> 
> **Result:**
> If you check indexes from project name2, you'll see name1 project mongodb logs. name2 indexes should not contain logs from another project.

I tested it in the master (2/15/19) version according to the above steps. Check the index from the project name2, no more logs from the name1 project.
@quick691fr thank you for the bug report!
