### ISSUE TITLE
Cluster agent controllers should only run once

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#17148]
Related issue: https://github.com/rancher/rancher/issues/16168

Problem:
For now, after the cluster agent reconnect to rancher server, the `onConnect` function will be call again and controllers will be started again. It should not happen.

Solution;
The `RunControllers` function only run once and do nothing after the first call.

**Comment by cjellick** [comment]
@orangedeng can you better describe the impact of this bug?

**Comment by orangedeng** [comment]
I found this issue when I am debugging custom metrics in monitoring. Multiple `ServiceMonitor` objects are created for one workload and that is not the expectation for `ServiceMonitor` controller. It should be one to one relation.
And I check all the controllers run in cluster agent, the controllers will work in this situation. But when multiple instances of the controller are running, only one of the is valid and the others will fail.

**Comment by orangedeng** [comment]
@jiaqiluo 
**Step to reproduce before fix:**
1. Setup a single node Rancher server with 1 user clusters.
2. After the cluster agent is connected and the cluster is provisioned, you can see the logs in cluster agent like 
```
time="2019-01-15T01:28:39Z" level=info msg="Starting workload controllers"
time="2019-01-15T01:28:39Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-46pqw to namespace=kube-public"
time="2019-01-15T01:28:39Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-fg98b to namespace=default"
time="2019-01-15T01:28:39Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-46pqw to namespace=cattle-system"
time="2019-01-15T01:28:39Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-46pqw to namespace=kube-system"
```
3. Stop Rancher server container for 30s and make sure cluster agent logs that it is disconnected to Rancher server. 
4. Restart Rancher server and wait for cluster agent has reconnected to server.
5. Another `time="xxx" level=info msg="Starting workload controllers"` will show in the cluster agent logs.

**Result:** 
Create a new namespace and assign it to project, you will see 2 following logs instead of 1:
```
time="xxx" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-fg98b to namespace=xxx"
time="xxx" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-fg98b to namespace=xxx"
```
This means that 2 namespace handlers are running in the same time.
**Expect:**
Should only has 1 logs for this operation.

**Comment by jiaqiluo** [comment]
Validation FAILED on Rancher:master 1/21. 


Steps: 
the same as the above comment describes.

Results:
1. For EC2 cluster, there is only one line for adding a naemsapce in the log, which is the expected output 
```
time="2019-01-21T19:26:45Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-hvjbc to namespace=ns1" 
```
2. For DO cluster, the same message showed twice and there is an error message between them:
```
time="2019-01-21T19:35:13Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-hvjbc to namespace=ns5" 
time="2019-01-21T19:35:13Z" level=error msg="namespaceHandler: Sync: error adding project id label to namespace err=Operation cannot be fulfilled on namespaces \"ns5\": the object has been modified; please apply your changes to the latest version and try again" 
time="2019-01-21T19:35:13Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-hvjbc to namespace=ns5" 
```
3. After stopping and re-starting the Rancehr server, I did not see this message in the cluster agent log:
```
time="xxx" level=info msg="Starting workload controllers"
```
cc @orangedeng

**Comment by orangedeng** [comment]
@jiaqiluo I test it in DO cluster with master 1/23. It didn't have two logs for the same adding namespace operation. The two logs you saw in the DO cluster are because the first `adding label` one failed(failure log is in the second line) and the controller is trying it again.

**Comment by jiaqiluo** [comment]
@orangedeng  Thank you for the feedback. I did not see this kind of behavior in my other tests, so I think you are right that it happens just because the first try fails.

The bug fix is validated.
