### ISSUE TITLE
Unable to edit existing cluster K8s version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17141]
Version: master 2.2 (12/17/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create any cluster. I used DigitalOcean and had one node with all node roles.
- Try to edit the cluster once it is up and notice that you cannot modify the k8s version under the Cluster Options section.

**Result:**
Unable to edit the K8s version of an existing cluster.

**Comment by jiaqiluo** [comment]
This bug also exists for those setups:
- single install, DO cluster with 3 nodes, one role on each
- HA install, DO cluster with 3 nodes, one role on each

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/20/19)
Confirmed fixed. Tested with other RKE providers as well and hosted providers as well just do double-check them all.
