### ISSUE TITLE
Allow CATTLE_SYSTEM_DEFAULT_REGISTRY to be set via helm install

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#17156]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancements

Currently there is no way to set extra environment variables such as CATTLE_SYSTEM_DEFAULT_REGISTRY when performing a helm install. The helm template should be updated to add this capability.

**Comment by jgreat** [comment]
@chrisurwin not that this is a difficult request, but I question the need to set this as an Env Var. This setting is available in the GUI or as an API call and as far as I know isn't really used as part of the Rancher install. 

As much as possible I'd like to keep the list of options to the server chart as few and as simple as possible.  Too many of the community charts try to be everything to everybody and become very complicated and confusing, especially to novice users.

**Comment by cloudnautique** [comment]
@chrisurwin would using the terraform provider be a reasonable approach vs. updating the chart. 

I think adding this means we would allow setting any environment variables to the deployment. To echo @jgreat, not a big deal, but feels like there are alternate ways.

**Comment by deniseschannon** [comment]
How about we add the ability to add external variables and not have to specify specific keys?

Would that be a compromise of having something generic as well as not force us to keep maintaining all the options as we add them to Rancher?

**Comment by jiaqiluo** [comment]
The enhancement is validated on Rancher: master

Steps:
- build a chart from Rancher: master
- run helm install command with the following variables:
```
helm install rancher-0.0.0-dirty.7d3da2630.tgz --namespace cattle-system --name rancher --set hostname=jiaqi-ha.qa.rancher.space --set rancherImageTag=master --set 'extraEnv[0].name=CATTLE_SYSTEM_DEFAULT_REGISTRY' --set 'extraEnv[0].value=http://example.jiaqi.com/'
```
- open the host on brower to check settings

Result:
`System Default Regisry` is set to the passed value
<img width="1514" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52512941-d80fa880-2bc4-11e9-8b95-db04fb7ddb03.png">
