### ISSUE TITLE
Concerns about rancher cluster high availability

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#1715]
Before creating this issue I've read [an Google Group topic](https://groups.google.com/forum/#!topic/rancherio/lDr2KCvR88g) that didn't cleared out my doubts.

I've tried rancher a couple of months ago but it seems it had a lot of improvements since then that made me wondering if we could use it...

I remember that my first concern was related with cluster agents high availability. Since agents are working on top of an URL for cluster joining, does the cluster goes faulty if node who has `rancher/server` running goes down and for some reason they need to reboot?

I've read somewhere that you also have some kind of internal service discovery, is it also scalable?

**Comment by vincent99** [comment]
If you have a single `rancher/server` and it goes down then you can no longer manage the hosts and containers, but the existing containers on those hosts and the overlay network between them continue working.  Things like rescheduling containers when a host fails will not happen while the server is gone.

It is possible to do a multi-nose setup.  We plan to make this easier, and eventually fully managed/automatic, but it's possible today: http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/

Service discovery is a DNS server that runs in the Network Agent on each host and answers queries from the containers on that host using a local copy of the answers (or a recursive server if not found).  `rancher/server` pushes updates to the answers down to the agents but is not involved in answering a particular query.

**Comment by ebuildy** [comment]
I am still having the "unregister_netdevice: waiting for lo to become free. Usage count = 1" issue when I stop/remove/re-add a Rancher agent. And the only solution is to clean the iptables and reboot the machine ;-(

Containers are still working hopefully, but docker is not responding.

**Comment by ebuildy** [comment]
You really should put a big confirm popup when user wants to restart "Network agent" container ;-)

**Comment by ibuildthecloud** [comment]
@ebuildy this is a bug in the Linux kernel that Rancher seems to easily trigger.  If it doesn't get fixed soon in Linux upstream we will start investigating a work around.  Sorry about that.  What we've seen is it's better to stop the agent and then delete it.  Don't do both at the same time.

**Comment by ibuildthecloud** [comment]
More context https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1403152

**Comment by ebuildy** [comment]
Just by curiosity, how Rancher triggers this bug?

Except that, Rancher is really a good product, I love the scheduler with services, the fact that we can open logs/console for any container in a few clicks and the help of the team ... we should open an issue "Thanks you guys" ;-)

**Comment by ibuildthecloud** [comment]
I honestly don't really know why Rancher triggers it as I don't fully understand what is the root issue in the kernel.  What we suspect is just that the network agent takes advantage of a heavy amount of Linux networking features that we do more than the normal container.  For example creating interfaces, arp proxying, iptables, ebtables, and IPSec.

**Comment by cusspvz** [comment]
@vincent99 thanks for your answer!

Does `rancher/agent` retries connection to `rancher/server` after a failure attempt?

**Comment by ibuildthecloud** [comment]
Yes it should try to reconnect every 5 seconds or so.

**Comment by deniseschannon** [comment]
@cusspvz Please re-open if you have more questions, but it looks as if they have been answered.
