### ISSUE TITLE
Use one set of fields for external and local auth

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#17153]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
* Enable external auth
* Logout
* Select login as local
* See an additional set of fields and login button

I guess we can do better than this, either switch the current field/buttons or dropdown with auth providers?

<img width="473" alt="screen shot 2018-12-18 at 10 50 38" src="https://user-images.githubusercontent.com/2620179/50146028-22eefd00-02b3-11e9-8234-c84a5b44c66c.png">

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/21/19)
Confirmed enhancement. There is now only one username/password field and if you need to switch to local user you are able to do so. 
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/51503712-cd1de100-1d99-11e9-9172-32b598289dcd.png)
When you click on login with local you will get an option to use your auth provider instead to switch back if necessary.
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/51503722-e4f56500-1d99-11e9-857f-37e1ce7c9214.png)

The browser will remember which you used last assuming the session is still active with the server / cookies/cache intact, etc.
