### ISSUE TITLE
Able to see catalog apps from another projects catalog

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17165]
Version: master 2.2 (12/17/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add a catalog to a project. In my case I added https://github.com/tfiduccia/charts to my "catalogs" project with project scope so only this project has access to this catalog.
- Launch the catalog apps. Filter the category down in my case to "Stuffs" and you'll see the nginx app. Now, using the global menu, change your project to another one that should not have access. In my case this is "catalogs2" and you can still see the app! You can also view details and deploy it on the separate project that should not have access. Refreshing will not fix the issue.
- Please see screenshots and additional information below!

**Result:**
Before switching we see our nginx app under our "catalogs" project:
![image](https://user-images.githubusercontent.com/45179589/50175596-6ac55280-02ba-11e9-8030-257791829f8f.png)

After we switch to our other project, "catalogs2" (which does not have this catalog configured for this project) we can still see the nginx app from "catalogs" project!:
![image](https://user-images.githubusercontent.com/45179589/50175619-803a7c80-02ba-11e9-9888-09723be20fbd.png)

**Additional Info:**
- _If you click on view details you can see details still - no errors occur therefore giving the user potentially access to see apps from another project._
- _If you deploy the app it will indeed deploy under the separate project that should not have access!_
- _If you set up a catalog for a cluster you can still see the apps on a second cluster!_

**Comment by vincent99** [comment]
Seems like both, the list of templates is global and not reloaded per cluster/project change.  So

1: the API needs to only return templates that the user has access to in _some_ cluster/project (it hopefully already does this)
2: the UI should filter the displayed list to only show entries that match the current scope
3: the API shouldn't allow deploying a templateVersion that the target project can't "see" (even if the user has access to it in another project, and especially if they don't and it's just someone else's random template id)

**Comment by westlywright** [comment]
Two things are happening here.

1. we have some permissions issues with cluster level catalogs that are being addressed
2. which is pertinent to this bug, we are not filtering the catalogs by current cluster id and project id. I will be adding a fix to address this.
