### ISSUE TITLE
Be able to edit OpenLDAP config as YAML

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#17171]
When configuring OpenLDAP, a user has to copy paste the config into multiple boxes. It would be nice to be able to click "Edit as YAML" and paste all the possible fields.

**Comment by vincent99** [comment]
Use the API is you want to automate setting up auth?  This is something that's set ~once, I don't want to put edit as yaml (and conversion to json) on every possible corner of the UI.

And if we did you'd say it's showing secrets and should be partially masked somehow, in a Yaml editor.
