### ISSUE TITLE
Cannot update node count in Alibaba hosted k8s

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17174]
As https://github.com/rancher/rancher/issues/16862 has been fixed in master, we need to make sure we can update Alibaba hosted k8s successfully

**Comment by loganhz** [comment]
Move into 2.2. QA think we have to fix it in 2.2

**Comment by rootwuj** [comment]
Version: master 2.2 (3/7/19) Image ID: a3f8c48fe1e6
Validate fixed.

Validate steps:

1. Creating alibaba ACK managed kubernetes `cluster1` and unmanaged kubernetes `cluster2`
2. Edit cluster1:
  Modify Cluster Name
  Modify the number of nodes: node range is 2-300
3. Edit cluster2:
  Modify Cluster Name
  Modify the number of nodes: node range is 0-300
