### ISSUE TITLE
K8s 1.12.3-rancher1-1 should be shown as default version when deploying a cluster in master

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17173]
Rancher version: master

Steps:
When deploying a cluster in rancher, K8s 1.11.5-rancher1-1 is shown as the default version
K8s 1.12.3-rancher1-1 should be shown as default version in master
<img width="1246" alt="screen shot 2018-12-18 at 4 51 32 pm" src="https://user-images.githubusercontent.com/18536626/50191976-33b86680-02e5-11e9-8dc9-9eb2dba654e7.png">

**Comment by cjellick** [comment]
wont fix as we are going to make 1.13 the default
 https://github.com/rancher/rancher/issues/17532
