### ISSUE TITLE
kubernetes-dashboard  Service unavailable

### ISSUE THREAD

**Issue by yyhLogin** [rancher/rancher#17178]
*Describe your issue here*
Removing bad service instance: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate"
Docker version 18.06.1-ce, build e68fc7a

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.25` Cattle: `v0.183.68` UI: `v1.6.49` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.dashboard`|

**Comment by superseb** [comment]
Docker up to 17.03.2 is supported for the k8s versions in v1.6, see https://github.com/rancher/rancher/releases/tag/v1.6.25

**Comment by superseb** [comment]
`curl https://releases.rancher.com/install-docker/17.03.sh`

**Comment by yyhLogin** [comment]
> `curl https://releases.rancher.com/install-docker/17.03.sh`
When I execute the above command
E: Version '' for 'docker-ce' was not found

**Comment by superseb** [comment]
You are probably on Ubuntu 18.04 which does not have a published package for Docker 17.03

**Comment by yyhLogin** [comment]
what should i do
