### ISSUE TITLE
Cannot update node count in Tencent hosted k8s

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17175]
rancher/rancher:master
Cannot update node count in Tencent hosted k8s

**Comment by cjellick** [comment]
other bugs/features/issues should take precedence over this. if we cant get to this, we will move it out

**Comment by rootwuj** [comment]
Version: master 2.2 (3/7/19) Image ID: a3f8c48fe1e6
Validate fixed.

Validate steps:
1. Creating tencent TKE kubernetes
2. Edit cluster:
  Modify cluster name
  Modify node count：node range is 1-100
