### ISSUE TITLE
Azure cloud provider does not correctly configure firewall

### ISSUE THREAD

**Issue by mikenorgate** [rancher/rancher#17181]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

When deploying a service with a type of `LoadBalancer` in an Azure cluster with the cloud provider configured the firewall is not opened on all nodes

**Steps to reproduce (least amount of steps as possible):**
 - Create a cluster with multiple nodes from Microsoft Azure and configure the cloud provider
 - Deploy a service with a type of `LoadBalancer`

**Result:**
 - In Azure each node is provisioned with it's own firewall (NSG)
 - The rules for the ports defined in the service are only opened in one of the NSGs, this means it is a bit of luck as to whether the load balancer sends the request to the one node with the correct NSG settings

**Other details that may be helpful:**
I think the best solution would be to only create one NSG that is attached to the subnet instead of one NSG per node

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.3
- Installation option (single install/HA): HA

**Comment by aiyengar2** [comment]
https://github.com/rancher/machine/pull/77 should facilitate creating one NSG that is attached to all nodes in a node pool

**Comment by aiyengar2** [comment]
re: NSG attached to subnet

https://github.com/rancher/machine/pull/77#issuecomment-610093619

**Comment by soumyalj** [comment]
Tested with v2.4-head(aae934198)

- NSG field provided in the template

1. Create a azure node template providing a nsg name in the NSG field .  
2. Create a azure cluster with a single node using this template. 
3. Create a daemonset and a L4 loadbalancer pointing to the daemonset.  Load balancer is functional
4. Add another node to the cluster. Loadbalancer is functional hitting all the targets. 

- Empty NSG field 
1. Create a azure node template with an empty NSG field .  
2. Create a azure cluster with a single node using this template. 
3. Create a daemonset and a L4 loadbalancer pointing to the daemonset.  Load balancer is functional
4. Add another node to the cluster. Loadbalancer is functional hitting all the targets. 

- Upgrade use case
1. Create a azure node template in Rancher v2.4.3
2. Create a azure cluster with a single node using this template. 
3. Create a daemonset and a L4 loadbalancer pointing to the daemonset.  Load balancer is functional
4. Upgrade rancher to v2.4-head(aae934198)
5. Verified loadbalancer is functional
6. Add another node to the cluster. Loadbalancer is functional hitting all the targets.

**Comment by soumyalj** [comment]
Tested with master-head(d9184e914)

- NSG field provided in the template

1. Create a azure node template providing a nsg name in the NSG field .  
2. Create a azure cluster with cloud provider set  using a single node using this template.
3. Create a daemonset and a L4 loadbalancer pointing to the daemonset.  Load balancer is functional
4. Add another node to the cluster. Loadbalancer is functional hitting all the targets. 

- Empty NSG field 
1. Create a azure node template with an empty NSG field .  
2. Create a azure cluster with cloud provider set  using a single node using this template. 
3. Create a daemonset and a L4 loadbalancer pointing to the daemonset.  Load balancer is functional
4. Add another node to the cluster. Loadbalancer is functional hitting all the targets.
