### ISSUE TITLE
Due to dead nginx-proxy container, all worker nodes become NotReady after adding masters

### ISSUE THREAD

**Issue by canhnt** [rancher/rancher#17187]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Not reliable to reproduce. The bug does not occur in testing cluster, but in another cluster, it happened:

Status: cluster has two master nodes: m1 (controlplane+etcd), m2(controlplane) and multiple workers
Steps:
1. Add a new master node m3 with role controlplane+etcd. The m3 is active and works well.
2. Right after that, all existing worker nodes become NotReady. All master nodes m1, m2, m3 are still working and Ready.

**Result:**
Checking inside worker nodes, the nginx-proxy containers are all in DEAD state. Cannot restart or replace this container. Because this proxy is not available, kubelet cannot connect to masters, making worker node becomes NotReady.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher server: v2.1.3, HA
Rancher agent: v2.1.3
rke-tools:v0.1.16

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 10CPU, 64GBi each
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 10
Total Memory: 68.67GiB
Name: xxx
ID: xxx
Docker Root Dir: /u02/docker_graph/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by canhnt** [comment]
With further investigation, we found out that the problem may relates to locking issue bind mounts in old kernel (3.10.0-514.16.1.el7.x86_64) and [filebeat/metricbeat](https://discuss.elastic.co/t/is-metricbeat-preventing-a-container-from-being-deleted-some-locking-issue/91236).

- With dead nginx-proxy container, it's unable to delete it with `docker rm nginx-proxy`. Error message is like:
```
docker rm nginx-proxy1
Error response from daemon: unable to remove filesystem for xxx: remove /u02/docker_graph/docker/containers/xxx/shm: device or resource busy
```
- Investigate further, the folder `/u02/docker_graph/docker/containers/xxx/shm` is bound to the filebeat container running in the node, so it's cannot be removed:
```
/proc/14862/mountinfo:1372 1364 0:60 / /u02/docker_graph/docker/containers/xxx/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,seclabel,size=65536k
```
The process `14862` is the filebeat process. If I stop the filebeat container of that process, `nginx-proxy` container can start normally.

**Lessons**: due to old kernel compatibility, prior upgrading/adding master nodes, we should stop all filebeat/metricbeat daemonsets otherwise it may clash with updating nginx-proxy created by rancher agent.

**Comment by superseb** [comment]
We added Docker retry logic in https://github.com/rancher/rke/pull/1393 to make the best out of the situation, if we can't tell Docker to successfully complete an operation, there is manual intervention needed. I dont think we should be going into process level and try killing processes at this point.
