### ISSUE TITLE
[Pipeline] The gitlab member has parent group owner permissions, but cannot fetch repo under the subgroup.

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#17188]
**Steps to reproduce**
Add members to gitlab subgroup or project and set the permissions to the maintainer or owner.
The pipeline can fetch the repo under the subgroup.

But add members in the gitlab parent group, and set the permission to the owner.
The pipeline cannot fetch the repo under the subgroup.

rancher/rancher:master

**Comment by gitlawr** [comment]
This is pending on upstream gitlab issues:
https://gitlab.com/gitlab-org/gitlab-ce/issues/43684
https://gitlab.com/gitlab-org/gitlab-ce/issues/46510
This project API is not showing users' group permission in this case. Need to add the user to the subgroup or the project member list explicitly.
