### ISSUE TITLE
UI becomes unresponsive after JS error

### ISSUE THREAD

**Issue by kevinsimons-wf** [rancher/rancher#17199]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
I believe the issue may be caused because we restrict user privileges to see secrets, and when secrets are mounted into pods, the UI cannot load the volume to display.

Steps:
1. Create a user without permissions to view Secrets in a cluster
2. Deploy an app that creates a secret and mounts it into a deployment as a volume
3. Try to load the app workload in the UI
4. Check the console, try to use the "snowman option" buttons to view logs / execute shell

**Result:**
The UI logs a stacktrace in the console 
```
component.js:119 Uncaught TypeError: Cannot read property 'data' of undefined
    at n.updateSecretKeys (component.js:119)
    at n.init (component.js:37)
    at n [as init] (0:58190)
    at n.e (0:57415)
    at n (0:57475)
    at n (0:57475)
    at n (0:57475)
    at new n (0:57475)
    at Function.e.create (0:57488)
    at e.create (0:35834)
updateSecretKeys @ component.js:119
init @ component.js:37
```
And the UI becomes unresponsive, where I can't click any of the options buttons in order to view logs, and can't click the drop down boxes to view env vars, volumes, etc.

**Other details that may be helpful:**
Looking through the debugger, it seems that in the `updateSecretKeys` function ( https://github.com/rancher/ui/blob/master/app/components/form-key-to-path/component.js#L109 ) , we are able to correctly load the `secretName`, but the `allSecrets` returns an empty object.
```
 > Ember.get(this, 'secretName');: "pypi-files-tmp-secrets"

 > Ember.get(this, 'allSecrets');: {…}
     _arrangedContent: []
     _length: 0
     _lengthDirty: false
     _objects: null
     _objectsDirtyIndex: 0
     _super:f<()
     content: []
     <prototype>: {…}
```
This then causes this line https://github.com/rancher/ui/blob/master/app/components/form-key-to-path/component.js#L116 to blow up since `undefined` has no property `data`.

I also think this may be a problem if we restrict things such as configmaps https://github.com/rancher/ui/blob/master/app/components/form-key-to-path/component.js#L133

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.1
- Installation option (single install/HA):
HA

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/8/19)
Confirmed fixed. I was not able to reproduce the issue. My cluster member had custom permissions set and I ensured I did not have permission to view secrets. When I create a workload that mounts a volume by using a secret I am able to view the console without any issues. I didn't not identify any other UI issues as well nor did I find any issues in the browser console.
