### ISSUE TITLE
AWS EKS available in Frankfurt & Stockholm

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/rancher#17197]
I thought it would be using the api to fetch the regions / eks availability but I think its hard coded?

https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-eks-available-in-frankfurt-singapore-sydney-and-tokyo-regions/

EKS regions have expanded.

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/17081

**Comment by ChrisMcKee** [comment]
Ta I searched for frankfurt and the region name; missed that ticket as it has neither in 😁
