### ISSUE TITLE
Kube service ports broken

### ISSUE THREAD

**Issue by LiamMartens** [rancher/rancher#17198]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Create workload
* View/edit YAML of the auto-generated svc and change port (eg 80:80)
* Attach it to an Ingress
* Service port gets reset to initial value (port 42)

**Result:**
* Ingress results in 503 since port gets reset to 42

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.3
- Installation option (single install/HA): Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): KVM VPS
- Kubernetes version (use `kubectl version`): 1.11.3

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 75
 Running: 38
 Paused: 0
 Stopped: 37
Images: 50
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.769GiB
Name: vandenborrekitchen.stereo
ID: 4L46:YXLJ:AMTN:PVGT:HVIG:H377:FJJK:SKYV:22N2:OTSD:5OGE:4JQV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by LiamMartens** [comment]
Wanted to add a note here. In the mean time I manually created a k8s service usin a simple label selector and this does appear to work and it keeps the correct ports.

**Comment by rossigee** [comment]
FTR, same behaviour reproducible with 2.2.2.

**Comment by rzyeleven** [comment]
same behaviour reproducible with 2.5.3

**Comment by vincent99** [comment]
Services are not created the same way in 2.6 and this isn't going to change for 2.5.x.
