### ISSUE TITLE
Rancher Authentication Add Gmail 

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/rancher#17196]
Hi 

It will be great that if you could add a features under the Authentication to Add gmail sign in as Options since now all are commonly use gmail in the organization. 

Under Authentication 

GitHub / LDAP /  <ADD Gmail Sign up>

**Comment by sjkeerthi** [comment]
It's terrible to have to manage user access manually. Having Google Auth would solve this problem for many of us.

**Comment by sjkeerthi** [comment]
Will it be available on 2.2 label

**Comment by vincent99** [comment]
Duplicate of #1411
