### ISSUE TITLE
Cluster state goes to pending state before provisioning state

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17201]
Rancher version: Master

Steps:
1. Create a cluster using DO machines.
Ex: 
```
a. One node with all roles
b. Two nodes N1 : etcd, control ; N2: worker
c. 3 nodes with all roles in each of them
```
The API shows error as below:
```
"state": "pending",
"transitioning": "error",
"transitioningMessage": "waiting for full cluster configuration",
"type": "cluster",


```

The cluster goes to pending state before going to provisioning state.
<img width="1370" alt="screen shot 2018-12-20 at 11 00 24 am" src="https://user-images.githubusercontent.com/18536626/50305308-4054d000-0447-11e9-9a98-31cf5b58981c.png">

The cluster did not go to pending state in older releases.

**Comment by cjellick** [comment]
related https://github.com/rancher/rancher/issues/17281 https://github.com/rancher/rancher/issues/15907

**Comment by soumyalj** [comment]
Tested with master build from Feb 12. Created clusters with DO template.

The following clusters were created:
a. One node with all roles
b. Two nodes N1 : etcd, control ; N2: worker
c. 3 nodes with all roles in each of them

Cluster does not go to pending state. Cluster goes to "Provisioning" state as expected. 
API snippet below:
```
"state": "provisioning",
"transitioning": "yes",
"transitioningMessage": "waiting for etcd and controlplane nodes to be registered",
"type": "cluster",
"uuid": "e83c33b5-2f11-11e9-9e3d-0242ac110002"

```
