### ISSUE TITLE
User can add a new template without template name

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17205]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- logged in as admin
- User icon -> Node Templates -> Add Template -> DigitalOcean
- Saved the template without template name
<img width="1376" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/50315193-fd0e5780-046e-11e9-83e1-b2d7896bc126.png">

**Result:**
Although the template name is required, but the template was saved successfully with a random name
<img width="1343" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/50315220-1c0ce980-046f-11e9-8997-441fa2710afa.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master 12/20
- Installation option (single install/HA): single install

**Comment by loganhz** [comment]
@vincent99 

I guess we can 

1. Validate it in node driver component
2. Change it to a required field in API
3. Remove the red `*` in UI

Which solution should we do?
