### ISSUE TITLE
UI Routing Error Catalog Tab Launch Route

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17206]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a setup with at least one cluster
Navigate to a catalog item launch page at the project level
Select global from the top nav
Select a project from the top nav

**Result:**
We are transitioned to the `fail-whale` page 

**Other details that may be helpful:**
This happens because the catalog app launch page is expecting an ID and when we use the project route session variable to return the user back to the previous project page we dont save any of the query params, only the route.

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/2/19)
Confirmed fixed. I could not reproduce the issue and also halo tested related areas. Further testing will also be done around this PR in related issues that the PR fixed.
