### ISSUE TITLE
Adding tolerations in answers.yaml while deploying a catalog app doesn't show up in UI

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#17204]
v2.1.3

Launch a catalog app that supports overriding tolerations.

Say:
```
'mysql.tolerations[0].key': app
'mysql.tolerations[0].operator': Equal
'mysql.tolerations[0].value': mysql
'mysql.tolerations[0].effect': NoSchedule
```

The workload gets launched it does have the tolerations when you check using `kubectl` but these tolerations don't show up in the UI under "Node Scheduling"

Related: https://github.com/rancher/rancher/issues/15585

**Comment by rootwuj** [comment]
Version: master 2.2 (1/31/19)
Confirmed fixed.
* This version of the UI shows the tolerances under "Node Scheduling" when launching a catalog app that supports coverage tolerations.
