### ISSUE TITLE
Add "pvc" as supported type for questions in UI.

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#17202]
Specifying a question to be of`storageclass` type brings up a nice dropdown menu in the UI when launching a catalog application. This is a very useful feature, taking away the confusion from what a user needs to fill in.

Similarly, I propose we add a type `pvc` type to show existing PVCs in the drop-down menu.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/16583

@leodotcloud  Here is an example https://github.com/rancher/charts/blob/29010a534efcc5a5c17350f22f20c49e0b264178/charts/mongodb/latest/questions.yml#L104
