### ISSUE TITLE
Healtcheck for Load Balancer service

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1721]
Today you can configure a healtcheck for the regular service, and if service's container is considered unhealthy, Service discovery replication controller is going to recreate it. 

We have to enable the heatlcheck for the lb service as well. In the UI, as its a rancher system service, we might not give a user all the configuration choices he sees for the regular service. Instead, we just show the check box asking whether health check needs to be configured. And then UI would send an appropriate API call with all the parameters needed. I'll see on the backend what port needs to be checked against on the haproxy side, and provide this info to the UI.

@vincent99 @will-chan

**Comment by alena1108** [comment]
@deniseschannon this fix enables health check for all lb services in the system by default. We should document the fact that port 42 is reserved for health checks, and can't be used as a public port for the LB Service.

**Comment by alena1108** [comment]
Sangeetha, we enabled health check for LB service by default. Check will be performed against port 42, so could you make sure none of your validation scripts use this as a public port for LB service?

**Comment by deniseschannon** [comment]
Can we put in a validation check in the code to throw an error if they try to use that port?

**Comment by sangeethah** [comment]
@alena1108 , port 42 is not used by any of the validation scripts.

**Comment by sangeethah** [comment]
Tested with server build - v0.46.0-rc2
Lb services have health check enabled by default on port 42 . When the host in which the "LB Agent" is running get to "reconnecting" state , new LB agent is started . But there is an issue where the unhealthy instance is not being removed which is tracked in #2694
