### ISSUE TITLE
Feature request: Ability to select certificates and secrets in catalog questions

### ISSUE THREAD

**Issue by riaan53** [rancher/rancher#17213]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

Request:
Be able to select (dropdown) certificates, secrets (and config maps if possible) from the questions.yaml catalog file if all permissions are valid.

**Comment by loganhz** [comment]
They are supported types in catalog questions.
Here is the list for supported types
https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/constants.js#L614-L630
