### ISSUE TITLE
Editing Cluster Node type is not working. [GKE] - Node vertical scale.

### ISSUE THREAD

**Issue by shinebayar-g** [rancher/rancher#17210]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create Google cluster with n1-standard-1 type. (1vCPU, 3.75GB ram)
Edit Cluster and change Node type to n1-standard-2 type. (2vCPU, 7.5GB ram)

**Result:**
No effect. (Actually it went to updating ... etc and cluster became unavailable for some time. But it didn't upgrade nodes)
I noticed nodes are not updated. But if I select Edit cluster again, it shows nodes are n1-standard-2 type which is invalid.

**Other details that may be helpful:**
I've been using GCP's n1-standard-1 type Nodes, which has 1vCPU, 3.75GB ram.
And I needed to scale my cluster. I decided to scale nodes vertically instead of adding more nodes. So I edited cluster and changed Node type n1-standard-1 to n1-standard-2. I expected node will be upgraded to n1-standard-2 type. But it didn't. So I guess this is bug.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): Single

**Comment by shinebayar-g** [comment]
There is no option to edit nodes as pool like how we edit cluster created by RKE. This results I cannot add 1 more Node with different size. I can only edit curret node pool. Is this possible to support node pool on GKE? Or it's not possible by design?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14299 for GKE node pool support
