### ISSUE TITLE
User menu list is very wide with particular screen widths

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17217]
Version: master 2.2 (12/21/18)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Have the browser window very small such that we switch to mobile view. The user menu list stretches all the way across the main area. (I am not certain if this is expected or not)
![image](https://user-images.githubusercontent.com/45179589/50358052-46b17d80-0515-11e9-8040-7133e891fbef.png)
- Increase the browser window width a little bit and now the user menu list is a normal width.
![image](https://user-images.githubusercontent.com/45179589/50358085-5cbf3e00-0515-11e9-937d-f4ad2552bc10.png)
- Maximize the browser window (1920x1200px in my case) and now the user menu list is very wide again.
![image](https://user-images.githubusercontent.com/45179589/50358099-72346800-0515-11e9-8011-24c65b029fac.png)

**Result:**
Unexpected changes in user menu list width.
_Ideally we should dynamically change the width of the User menu depending on length of user name with a set minimum._

**Other details that may be helpful:**
Latest Google Chrome browser on macOS

**Comment by davidnuzik** [comment]
I've moved this to v2.3 milestone for consideration.

**Comment by vincent99** [comment]
Is because .identity-block is 30vw (30% of the screen) wide
