### ISSUE TITLE
Pods fail to start with custom kubelet path

### ISSUE THREAD

**Issue by skoop** [rancher/rancher#17222]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug, I think

**Steps to reproduce (least amount of steps as possible):**

I have a setup of 3 servers with our current hosting provider. One is the main Rancher server, the second is the controlplane and etc server, and the third is currently the only worker server. Our hosting provider has a specific setup where `/var` is very limited in size. Instead, we are supposed to write to `/data`. 

I've configured docker to write to `/data/docker` and that works fine. I was configuring pipelines and Jenkins kept failing. After some research it turned out that Jenkins was writing all data into `/var/lib/kubelet`, which would cause the disk space limit to be met.

Through some research I've found out that by editing the cluster YAML file I could customize this path. I've added the following configuration to the `kubelet:` configuration:

```
extra_args: 
      root-dir: "/data/kubelet"
```

This is nicely respected. However, all containers now fail with the following error:

```
RunContainerError: failed to start container "aaec4230d5248e6f6bc2f7411703c99506c72e9c72b18543b42665f067920fab": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/data/kubernetes/pods/c6b899f6-0378-11e9-a127-005056a15664/etc-hosts\\\" to rootfs \\\"/data/docker/overlay2/b6c060457cb770ed8b865f817099ec4a4801a235f8dfe0d19358df867a036afd/merged\\\" at \\\"/data/docker/overlay2/b6c060457cb770ed8b865f817099ec4a4801a235f8dfe0d19358df867a036afd/merged/etc/hosts\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

If I check `etc-hosts`, I find out that indeed, this is not a file, this is a directory all of a sudden. If I check `/var/lib/kubelet` I see that the pods there do have a file. Somehow, changing the directory in the configuration causes (empty) directories to be generated instead of a file.

**Result:**

Pods don't want to start anymore

**Other details that may be helpful:**

**Environment information**

Rancher v2.1.3

I have a setup of 3 servers with our current hosting provider. One is the main Rancher server, the second is the controlplane and etc server, and the third is currently the only worker server. Our hosting provider has a specific setup where `/var` is very limited in size. Instead, we are supposed to write to `/data`. 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM/2CPU/8GB RAM
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Docker (use `docker info`):

Containers: 84
 Running: 71
 Paused: 0
 Stopped: 13
Images: 43
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.639GiB
Name: mob-app-t03.devapp.mob.sentia
ID: STFX:EN3B:5H7R:PXMA:RERF:5RMH:MNAH:ZSCY:MFEU:REUU:RX5G:M23S
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by loganhz** [comment]
- Create the new kubelet folder on each nodes.
- Edit the cluster.yaml file adding the line below :

```
kubelet:
    extra_args:
      root-dir: "/opt/data/kubelet"
    extra_binds:
    - "/opt/data/kubelet:/opt/data/kubelet:shared,z"
```
