### ISSUE TITLE
Add system log option

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#17228]
UI for https://github.com/rancher/rancher/issues/15555

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/31
Our field says Include System Log.  The API says "exclude".  The API fields should not be negative.  Currently it is "excludeSystemComponent".  That will need to change and so the UI will need to change to attach to the new API field.  Sending back.
Also - we should change the text to "Include System Logs".  Add the 's' to Log.
![image](https://user-images.githubusercontent.com/11514927/52076279-93906700-254b-11e9-9435-c61de5d10079.png)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/18026
