### ISSUE TITLE
UI - Backport Adding tolerations to a workload via the UI does not work

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17220]
UI for https://github.com/rancher/rancher/issues/17215

**Comment by davidnuzik** [comment]
Version: 2.1.5-rc3 (1/2/19)
Confirmed fixed.
- Validated that the UI is still correctly sending scheduling information.
- Validated that the pod indeed has our Toleration settings as described in the 15585 issue.
![image](https://user-images.githubusercontent.com/45179589/50613726-c3d8dd00-0e9b-11e9-805e-04db49af4054.png)
