### ISSUE TITLE
Ingress (Traefik) - Daemonset not binding properly

### ISSUE THREAD

**Issue by Yomanz** [rancher/rancher#17230]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce:** 

1. Install daemonset version of https://docs.traefik.io/user-guide/kubernetes/
2. Attempt to upgrade/redeploy the daemonset

**Result:**
The ports it bound on *80* will no longer be bonded

**Other details that may be helpful:**
(I have to manually delete the pods but I believe that's because rolling updates are not turned on for the daemonset)
Prior to upgrade: https://you-have-a.bigno.se/4f2f9ba.png
After upgrade: https://you-have-a.bigno.se/c01b5e1.png

**Environment information**
- Rancher version: v2.1.1
- Installation option: Single installation

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal - 2x 6gb 3core
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):
(I ran this on a worker node)
```
Containers: 42
 Running: 19
 Paused: 0
 Stopped: 23
Images: 32
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d6de12e2f362cb9dc49ad957911996d3de59b338
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 5.821GiB
Name: daave1.aaathats3as.com
ID: 4IIJ:H7ZV:J2YH:CEKX:TYRQ:S5DD:T7UI:VDHK:ZU3B:QRUX:RSRE:H372
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by victionn** [comment]
I actually do relate to this; this happens to me to and its rather annoying. fix when

**Comment by vincent99** [comment]
This is the way k8s works and not a "rancher issue".  It's because the upgrade policy **is** rolling update instead of on delete.

Rolling update creates a new pod and then deletes an old one.  But because you (they) are using daemonset + node ports, there is nowhere a new pod can be successfully scheduled and bind the requested ports, since they are still all already in use on every node.

**Comment by Yomanz** [comment]
So changing the upgrade policy to ondelete should fix it, or have i misread

**Comment by Yomanz** [comment]
@vincent99 the update policy is ondelete not rolling update
