### ISSUE TITLE
Rancher-Compose: Add option to delete stack when removing services.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1723]
When removing services, it'd be nice to have an option to also delete the stack (assuming there are no other services).

**Comment by deniseschannon** [comment]
Fixed with https://github.com/rancher/rancher-compose/pull/57

**Comment by kaos** [comment]
+1

**Comment by kaos** [comment]
Or, just realized we'll probably call the API directly when deleting a stack using the [gdapi](https://github.com/rancher/gdapi-python) :)

**Comment by joshuakarjala** [comment]
Also wanting this :)

@kaos did you work out doing it through the API?

**Comment by tombmurphy** [comment]
+!

**Comment by kaos** [comment]
@joshuakarjala I have this, but haven't tested it that much yet, but it seems to do what I want...
```
    def delete_stack (self, name):
        for e in self.client.list_environment (name=name):
            self.log.info ('delete stack %s [%s]', name, e.links.self)
            e.remove ()
```

**Comment by joshuakarjala** [comment]
@kaos thanks!

Hope they will also fix here :)

**Comment by soumyalj** [comment]
While deleting services as below, it says Project deleted but does not delete it ..

soumyas-MacBook-Pro:rancher-compose-v0.8.0 soumya$ ./rancher-compose -p stack2 -f dc1.yml -r test2.yml rm --f
INFO[0000] Project [stack2]: Deleting project           
INFO[0000] [0/1] [test2]: Deleting                      
INFO[0000] [0/1] [test2]: Deleted                       
INFO[0000] Project [stack2]: Project deleted

**Comment by hugochinchilla** [comment]
+1

**Comment by nrvale0** [comment]
+1

**Comment by deniseschannon** [comment]
Instead of adding this into Rancher Compose, we recommend using the new [Rancher CLI](http://docs.rancher.com/rancher/cli/) which allow users to delete stacks.

**Comment by rocketeer125** [comment]
@deniseschannon Slightly confused about this; the new Rancher CLI is meant to be available through the UI (see documentation), however this doesn't give me the options to manipulate the stack (Using current version 1.1.4)

- Is there more than one CLI as the one in the UI is labeled "Rancher CLI" but downloads the rancher-compose tar ball.

**Comment by deniseschannon** [comment]
The new CLI (particularly  v0.2.0+) is available for v1.2.0-pre3+. The v0.1.0 CLI is compatibly with v1.1.4, but will not be available through the UI as it wasn't released/created until post v1.1.4. You could download it through the releases page in CLI. https://github.com/rancher/cli/releases/tag/v0.1.0

**Comment by pschirch** [comment]
+1

**Comment by loicgasser** [comment]
Hi! Great project!
I am using exculsively Rancher-Compose to deploy our apps.
I don't understand why you can create a stack with rancher-compose API, but you can't delete it and why you won't consider this feature in a future release?

**Comment by cjellick** [comment]
Are you using rancher cli (`./rancher` not `./rancher-compose`)? That has the ability to delete stacks

**Comment by loicgasser** [comment]
rancher-compose
I'd like to avoid mixing APIs if possible.

**Comment by cjellick** [comment]
`./rancher` does everything that `rancher-compose` does. In fact, we've deprecated rancher-compose in favor of `rancher`

**Comment by loicgasser** [comment]
Ok thanks for the tip, I ll use rancher cli instead then.
