### ISSUE TITLE
Investigate impact of AggregationController API lag / metrics server Rate Limited Requeue

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#17248]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Create custom cluster with 3 nodes with all roles
* Shutdown a node
* See some kubectl commands take a long time
* Logging shows `Rate Limited Requeue`.

Other symptoms seen are high CPU usage of kube-apiserver.

**Result:**
Applying the workaround from https://github.com/kubernetes/kubernetes/issues/56430 (`kubectl --namespace kube-system delete apiservice v1beta1.metrics.k8s.io`) speeds things up, need to investigate what the actual root cause is and if we can apply the fix by default or possibly to some other mitigation (or wait for upstream).

**Comment by proegssilb** [comment]
Something involving metrics is definitely slowing things down way more than it should. The STR doesn't work for me, because my cluster's low-powered enough that it's always seeing the `Rate Limited Requeue` message, and the workaround makes the Rancher UI stop issuing timeout warnings/errors all the time.

**Comment by proegssilb** [comment]
I'm now running Kubernetes 1.12 (RKE v0.2.0-rc3), and still seeing high CPU usage until I follow the workaround.

**Comment by mboudet** [comment]
We have the same issue following the [quickstart manual install](https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/#2-install-rancher)

We use the 1.13.4 kubernetes version.

We use 4 nodes, 3 of them as as an etcd/control plane/worker, and the last one as a worker.
The kube-apiserver containers seem to have random cpu spikes on all three nodes where they are launched.

On the node where the metricserver is up, we have this : 

![image](https://user-images.githubusercontent.com/17642511/54814108-587afc00-4c8f-11e9-8bf7-d82180149197.png)

On the other two nodes, something like this :

![image](https://user-images.githubusercontent.com/17642511/54814156-721c4380-4c8f-11e9-8c91-88e7f660cdd2.png)

The metrics container does not show any logs since we added the nodes.

We do not have any application launched.

**Comment by daanemanz** [comment]
We're seeing this on `v1.12.4` as well. 3 nodes on GCP recently updated with RKE `v0.2.2`. We're seeing that some clusters are intermittently unavailable in the Rancher UI - it just times out.

**Comment by rajha-korithrien** [comment]
I believe we are also seeing a related aspect to this problem. Putting information here in the hope it helps and possibly get a question clarified. This is mostly a development/experiment cluster, so we are willing to use it to help debug the problem if such would be useful.

We are using:

- RancherOS v1.5.1
- Rancher v2.2.0
- Rancher itself deployed via RKE command line to a small bare metal cluster only used for Rancher itself (this cluster does not have the issue).
- Rancher deployed a larger bare metal cluster on top of RancherOS created via the Rancher UI (this cluster does have the issue)
- kubectl version below
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
From the moment the larger cluster is brought online, the ```kube-apiserver``` logs on various nodes are spammed with the following:
```
# docker logs kube-apiserver
...
...
I0428 14:17:53.781218       1 controller.go:116] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Requeue.
I0428 14:18:53.781733       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I0428 14:18:53.784131       1 controller.go:116] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Requeue.
I0428 14:19:53.784636       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I0428 14:19:53.786944       1 controller.go:116] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Requeue.
I0428 14:20:53.787424       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I0428 14:20:53.789707       1 controller.go:116] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Requeue.
I0428 14:21:53.790256       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I0428 14:21:53.792711       1 controller.go:116] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Requeue.
I0428 14:22:53.793003       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I0428 14:22:53.795160       1 controller.go:116] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Requeue.
```
When the cluster exhibiting this behavior is first brought up the Rancher UI interaction with it works correctly for perhaps a day. Then the UI becomes unresponsive and at time displays the following error.
<img width="957" alt="image" src="https://user-images.githubusercontent.com/8145476/56900005-14c79f00-6a52-11e9-8bf3-60a93e689259.png">

We found that we can bring the cluster back into a "working" state by restarting the kube-apiserver on each node (which is a very bad solution)
```
# docker restart kube-apiserver
kube-apiserver
```
After reading through this issue and the seemingly related kubernetes/kubernetes#56430 we also did the suggested workaround.
```
# Run kubectl commands inside here
# e.g. kubectl get all
> kubectl --namespace kube-system delete apiservice v1beta1.metrics.k8s.io
apiservice.apiregistration.k8s.io "v1beta1.metrics.k8s.io" deleted
>
```
Our logs are no longer being spammed and have an interesting final entry having to do with ```v1beta1.metrics.k8s.io```
```
I0428 14:41:22.797971       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I0428 14:41:28.509677       1 controller.go:116] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Requeue.
I0428 14:42:28.510041       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I0428 14:42:32.319257       1 controller.go:122] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Nothing (removed from the queue).
```

After taking the step of deleting the apiservice, the RancherUI has worked correctly for 48 hours now, and we have not had to restart the kube-apiservers.

**Question** We did not get a good feel for the operational impact of deleting apiservice v1beta1.metrics.k8s.io from the kubernetes issue. Does this impact our ability to use Rancher to collect metrics about our cluster?

Thanks!

**Comment by muyufan** [comment]
@superseb  do you know how to add it back after run "kubectl --namespace kube-system delete apiservice v1beta1.metrics.k8s.io"? my error seems not caused by this

**Comment by elacy** [comment]
`docker info`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 36
  Running: 20
  Paused: 0
  Stopped: 16
 Images: 14
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-84-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.59GiB
 Name: rke-1
 ID: PZQK:VIJO:GLRG:WOOD:4N26:32OM:MIYX:YNQF:QDVR:ENT2:57QS:TRAR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
