### ISSUE TITLE
cloud provider Amazon option - cluster creation fail

### ISSUE THREAD

**Issue by thiagosantosleite** [rancher/rancher#17240]
**What kind of request is this (question/bug/enhancement/feature request):**
bug?

**Steps to reproduce (least amount of steps as possible):**
Create a new ec2 cluster and use cloud provider = "Amazon"

**Result:**
Error:
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.53.111.128]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused, log: F1226 18:08:56.949847 31560 server.go:262] failed to run Kubelet: could not init cloud provider "aws": ClusterID tags did not match: "c-7cjkr" vs "dev01"

**Other details that may be helpful:**
-> If I edit the cluster and choose the option none in cloud provider the cluster creation works
-> Rancher instance profile role is aws admin, so I think its is not aws permission issue

**Environment information**
HA Installation
Component	Version
Rancher	v2.1.3
User Interface	v2.1.17
Helm	v2.10.0-rancher5
Machine	v0.15.0-rancher1-1

**Cluster information**
1 - Master
Active | tmaster1|10.53.111.128 | etcd Control Plane | v1.12.3 17.3.2 | 0.3/2 Cores | 0/7.4 GiB | 2/110 |  

1 - worker
Active|tworker1|10.53.91.50|Worker	v1.12.3 17.3.2 0.5/2 Cores	0.1/7.4 GiB	8/110

**Comment by thiagosantosleite** [comment]
I build a new cluster to get more info from logs:

I1227 20:51:39.837329   23114 aws.go:1025] Building AWS cloudprovider
I1227 20:51:39.837356   23114 aws.go:987] Zone not specified in configuration file; querying AWS metadata service
F1227 20:51:40.216036   23114 server.go:262] failed to run Kubelet: could not init cloud provider "aws": ClusterID tags did not match: "c-xvdtx" vs "dev01"
+ echo kubelet --v=2 --hostname-override=master1 --cloud-provider=aws --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --address=0.0.
0.0 --resolv-conf=/etc/resolv.conf --anonymous-auth=false --authentication-token-webhook=true --read-only-port=0 --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bi
n --volume-plugin-dir=/var/lib/kubelet/volumeplugins --pod-infra-container-image=rancher/pause-amd64:3.1 --cluster-dns=10.43.0.10 --fail-swap-on=false --root-dir=/var/lib/kubelet --tls-ciph
er-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES
_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --cadvisor-port=0 --cgroups-per-qos=True --enforce-node-allocatable= --allow-privileged=true --cluster-domain=cluster.local --register-w
ith-taints=node-role.kubernetes.io/controlplane=true:NoSchedule

**Comment by superseb** [comment]
The prerequisites for Amazon cloud provider are listed here: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/cloud-providers/#amazon

The log says the ClusterID tags do not match, can you check what ClusterID tag is set on the resources mentioned in the docs?

**Comment by thiagosantosleite** [comment]
thanks @superseb ! that is true.....I didnt put the tags in the subnets and security groups in the first try. I fixed it now, but still no success with my current cluster and same error when create a new cluster and enable aws as cloud provider.

NEW CLUSTER c-hkcq4:
```
[rancher-f4fb5f5c6-vwpcc] 2018/12/28 12:43:02 [INFO] 2018/12/28 12:43:02 http: multiple response.WriteHeader calls
[rancher-f4fb5f5c6-r247s] 2018/12/28 12:42:56 [ERROR] cluster [c-hkcq4] provisioning: [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.53.95.99]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused, log: F1228 12:43:36.748220   18636 server.go:262] failed to run Kubelet: could not init cloud provider "aws": ClusterID tags did not match: "c-hkcq4" vs "dev01"
[rancher-f4fb5f5c6-r247s] 2018/12/28 12:42:56 [ERROR] ClusterController c-hkcq4 [cluster-provisioner-controller] failed with : [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.53.95.99]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused, log: F1228 12:43:36.748220   18636 server.go:262] failed to run Kubelet: could not init cloud provider "aws": ClusterID tags did not match: "c-hkcq4" vs "dev01"
[rancher-f4fb5f5c6-mshdw] 2018/12/28 12:43:57 [INFO] 2018/12/28 12:43:57 http: multiple response.WriteHeader calls
[rancher-f4fb5f5c6-r247s] 2018/12/28 12:43:14 [INFO] 2018/12/28 12:43:14 http: multiple response.WriteHeader calls
[rancher-f4fb5f5c6-r247s] 2018/12/28 12:43:22 [ERROR] ProjectRoleTemplateBindingController p-xjzpv/creator-rt-ffjhv [mgmt-auth-prtb-controller] failed with : roleTemplate.management.cattle.io "rt-ffjhv" not found
[rancher-f4fb5f5c6-r247s] 2018/12/28 12:43:22 [ERROR] ProjectRoleTemplateBindingController p-pqcz8/creator-rt-fzrf6 [mgmt-auth-prtb-controller] failed with : roleTemplate.management.cattle.io "rt-fzrf6" not found
[rancher-f4fb5f5c6-r247s] 2018/12/28 12:43:22 [ERROR] ProjectRoleTemplateBindingController p-dd4xc/creator-rt-fzrf6 [mgmt-auth-prtb-controller] failed with : roleTemplate.management.cattle.io "rt-fzrf6" not found
[rancher-f4fb5f5c6-r247s] 2018/12/28 12:43:25 [INFO] 2018/12/28 12:43:25 http: multiple response.WriteHeader calls
[rancher-f4fb5f5c6-vwpcc] W1228 12:43:43.869114       7 reflector.go:341] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: watch of *v3.Node ended with: too old resource version: 5435615 (5439806)
[rancher-f4fb5f5c6-vwpcc] 2018/12/28 12:43:46 [INFO] 2018/12/28 12:43:46 http: multiple response.WriteHeader calls
[rancher-f4fb5f5c6-r247s] W1228 12:43:40.084877       7 reflector.go:341] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: watch of *v3.Node ended with: too old resource version: 5439136 (5439834)
[rancher-f4fb5f5c6-mshdw] 2018/12/28 12:44:34 [ERROR] ProjectRoleTemplateBindingController p-xjzpv/creator-rt-ffjhv [cluster-prtb-sync] failed with : couldn't get role template rt-ffjhv: roleTemplate.management.cattle.io "rt-ffjhv" not found
[rancher-f4fb5f5c6-mshdw] 2018/12/28 12:44:34 [ERROR] ProjectRoleTemplateBindingController p-dd4xc/creator-rt-fzrf6 [cluster-prtb-sync] failed with : couldn't get role template rt-fzrf6: roleTemplate.management.cattle.io "rt-fzrf6" not found
[rancher-f4fb5f5c6-mshdw] 2018/12/28 12:44:34 [ERROR] ProjectRoleTemplateBindingController p-pqcz8/creator-rt-fzrf6 [cluster-prtb-sync] failed with : couldn't get role template rt-fzrf6: roleTemplate.management.cattle.io "rt-fzrf6" not found
[rancher-f4fb5f5c6-mshdw] 2018/12/28 12:44:40 [INFO] 2018/12/28 12:44:40 http: multiple response.WriteHeader calls
[rancher-f4fb5f5c6-mshdw] 2018/12/28 12:44:51 [INFO] 2018/12/28 12:44:51 http: multiple response.WriteHeader calls
[rancher-f4fb5f5c6-vwpcc] 2018/12/28 12:44:17 [INFO] 2018/12/28 12:44:17 http: multiple response.WriteHeader calls

```

CURRENT CLUSTER c-5mf6j:
```
[rancher-f4fb5f5c6-mshdw] W1228 12:52:26.468466       7 reflector.go:341] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: watch of *v3.Node ended with: too old resource version: 5440512 (5441678)
[rancher-f4fb5f5c6-r247s] 2018/12/28 12:51:44 [ERROR] ClusterController c-5mf6j [cluster-provisioner-controller] failed with : [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.53.103.111]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused, log: F1228 12:51:59.310500   31898 server.go:262] failed to run Kubelet: could not init cloud provider "aws": ClusterID tags did not match: "c-5mf6j" vs "dev01"
[rancher-f4fb5f5c6-vwpcc] W1228 12:52:02.753388       7 reflector.go:341] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: watch of *v1.Endpoints ended with: too old resource version: 5428500 (5429463)

```

TAGS:
```
aws ec2 describe-tags --filters "Name=resource-id,Values=xxxxxxxxxxxxxx" "Name=resource-type,Values=subnet"
{
    "Tags": [
        ...
        ...
        {
            "ResourceType": "subnet",
            "ResourceId": "xxxxxxx",
            "Value": "shared",
            "Key": "kubernetes.io/cluster/c-5mf6j"
        },
        {
            "ResourceType": "subnet",
            "ResourceId": "xxxxxxx",
            "Value": "shared",
            "Key": "kubernetes.io/cluster/c-hkcq4"
        }
    ]
}



aws ec2 describe-tags --filters "Name=resource-id,Values=xxxxxxxxxxxxxx" "Name=resource-type,Values=security-group"
{
    "Tags": [
        ...
        ...
        {
            "ResourceType": "security-group",
            "ResourceId": "sg-0892da2dc7fd5031e",
            "Value": "shared",
            "Key": "kubernetes.io/cluster/c-5mf6j"
        },
        {
            "ResourceType": "security-group",
            "ResourceId": "sg-0892da2dc7fd5031e",
            "Value": "shared",
            "Key": "kubernetes.io/cluster/c-hkcq4"
        }
    ]
}

```

Note: I'll not post here the node tags, because looks fine! and its created by rancher automatically.

**Comment by thiagosantosleite** [comment]
When I create new nodes the provision process tag new nodes with:
kubernetes.io/cluster/c-5mf6j -> owned

but should tag with:
kubernetes.io/cluster/dev01 -> owned

What I'm doing wrong? if I tag manually the new nodes with kubernetes.io/cluster/dev01, I'm able to change the cloud provide from none to aws.

**Comment by thiagosantosleite** [comment]
After the I changed the cluster provider from none to aws I see that the output from "rancher node list" changed too from "master-us-east-1b-m5-large1" (pool name format) to "ip-10-53-103-111.ec2.internal" (aws format).

is it expected?

**Comment by thiagosantosleite** [comment]
Hi....

What should I change to make my clusters nodes tagged with the correct cluster id?
Any ideas?

**Comment by thiagosantosleite** [comment]
the error still happen in the latest version:

Component | Version
-- | --
Rancher | v2.1.5
User Interface | v2.1.19
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1

please advise....

**Comment by superseb** [comment]
When using EC2 node template driver, the tag on the instances is set to `kubernetes.io/cluster/<CLUSTERID>=owned`. If you want to have more flexibility on this, you can use the custom cluster functionality and manually tag the instances with the correct tags and then add them to the cluster (which can still be configured with the k8s cloud provider amazon to get desired cloud provider functionality).

Let me know if you have any other questions on this.
