### ISSUE TITLE
Failed to pull image from nexus private registry

### ISSUE THREAD

**Issue by leochan007** [rancher/rancher#17241]
Failed to pull image ": rpc error: code = Unknown desc = unauthorized: authentication required

docker 17.03.2  nexus 3
rancher 2.1.3.
already add private registry in rancher. rancher pull failed. but docker pull directly on node is OK.

**Comment by leochan007** [comment]
rancher 2.1.3.

**Comment by loganhz** [comment]
@leochan007 Can you check if `imagePullSecrets` is in the yaml of your deployment, please?

**Comment by leochan007** [comment]
@loganhz yes. i works. a workaround method : add this opt mannually. thx.
