### ISSUE TITLE
How can I skip CA certificate validation for active directory ldaps ?

### ISSUE THREAD

**Issue by voxmaster** [rancher/rancher#17245]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Try to setup Active Directory Authentication with next parameters:
Server IP=x.x.x.x, Use TLS=checked, port=636, CA certificate exported from CA server: inserted
Other standard parameters for ldap

**Result:**
IN WEB: Error creating ssl connection: LDAP Result Code 200 "": x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
IN LOG:  [ERROR] Unknown error: Error creating ssl connection: LDAP Result Code 200 "": x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

**Environment information**
- Rancher version:
`rancher/rancher` docker image v 2.1.4

**Comment by loganhz** [comment]
Please see https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/ad/#prerequisites
