### ISSUE TITLE
Add Service container name into the hostname for the container

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1724]
Currently, when containers are scaled within a service, Rancher creates a name for this by generating a name "<stack>_<service>_<cardinal number>".  Unfortunately, this is not propagated down to inside the container where it can become useful for certain apps.

#1431 will eventually solve this by providing this info, but we can also consider adding a label to specify whether to automatically have rancher add the "--hostname" of the container name generated.  If this label is specified, it overrules any other --hostname requests.

**Comment by ibuildthecloud** [comment]
We shouldn't set environment variables.  Why do we need this?

**Comment by alena1108** [comment]
There is a use case (@will-chan has more details on that) when service container needs to know its own name; and it should be able to figure it out from within the container (so just setting up the label won't be a solution). Metadata service would be able to solve it properly, so I believe this is the temporary workaround.

**Comment by vincent99** [comment]
I agree, :-1: on setting arbitrary environment vars for one of a hundred things you might want from metadata.  Can't we just finish the packaging and json generation for the metadata service?

**Comment by alena1108** [comment]
Instead of setting up the env vars, we are going to override container.hostname with container.name if following label is defined:

io.rancher.container.hostname_override=container_name

**Comment by sangeethah** [comment]
Tested with server version - v0.32.0-rc1

When I use  label to deploy containers using labels -  "io.rancher.container.hostname_override: container_name" , hostname of the container is set to the "stack_name_servicename_n" format.

I also see env variable HOSTNAME being set.

<img width="708" alt="screen shot 2015-08-06 at 10 59 30 am" src="https://cloud.githubusercontent.com/assets/4266958/9119221/6b24f686-3c2a-11e5-88fc-a99c9d052321.png">

**Comment by alena1108** [comment]
@sangeethah it has always been set. I've just checked on the branch that doesn't have my fix, whenever host name is being set for a container, it appears in env vars.

**Comment by sangeethah** [comment]
@alena1108 , Thanks for the confirmation.

I also see this env set to container_id when io.rancher.container.hostname_override=container_name label is not specified.
