### ISSUE TITLE
Show current count/scale in Workload view

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#17246]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
From the workload view, it's hard to discover what the current state of the scale/count of pods is. Only the configured scale is shown on top, and the pagination controls are on the bottom so you need to scroll down.

Possible solutions are adding current scale (`availableReplicas` or `readyReplicas`) to the top view, or add the pagination to the top of pods list so you don't have to scroll and it shows the current amount of pods. Actually, both would be helpful as one solves the issue of seeing the current scale/count and the other solves other use cases where you can find additional pods besides from the scale (for instance, evicted pods)

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/22/19)
Workload scale was added to the top of the workload view. Confirmed this is functioning as expected.
![image](https://user-images.githubusercontent.com/45179589/51640399-958d7100-1f20-11e9-8b26-2b15e0ba6016.png)
