### ISSUE TITLE
Pipeline publishCatalog step using SSH to push with Git does not work

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#17252]
**Steps to reproduce :**

1. Edit pipeline configuration, add a step
2. Step type selection "publish catalog app"
3. Edit step, select the protocol "Push to Git with SSH"
<img width="1037" alt="002" src="https://user-images.githubusercontent.com/42061003/50504226-0f0f7c00-0aa7-11e9-87f9-72dc1ed9f65a.png">

4. Select DEPLOY_KEY  (I can be sure it is correct)
5. Run the pipeline

**Result:**
Output error log:

<img width="1292" alt="001" src="https://user-images.githubusercontent.com/42061003/50504385-44689980-0aa8-11e9-9518-a2862a36e99c.png">

**Comment by gitlawr** [comment]
The deploy key is in an invalid format so it is an expected failure.
But we should improve error handling so that it exists and terminates earlier without printing last few lines.

**Comment by cjellick** [comment]
waiting on something else?

**Comment by rootwuj** [comment]
Version -2.2 master 01/14
Verified fixed
