### ISSUE TITLE
Excessive logging when node/cluster is down

### ISSUE THREAD

**Issue by proligde** [rancher/rancher#17257]
**What kind of request is this (question/bug/enhancement/feature request):**

bug/enhancement

**Steps to reproduce (least amount of steps as possible):**

1. Create a new cluster containing only one node including control-plane services, etcd... Everything with default settings.

2. Shutdown the node.

**Result:**

The rancher server will put out this block once every second, filling up storage rather quickly:

`E1228 13:25:58.843239       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1beta1.PodSecurityPolicy: Get https://192.168.1.181:6443/apis/extensions/v1beta1/podsecuritypolicies?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.860569       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.ConfigMap: Get https://192.168.1.181:6443/api/v1/configmaps?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.878941       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Node: Get https://192.168.1.181:6443/api/v1/nodes?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.903896       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1beta2.Deployment: Get https://192.168.1.181:6443/apis/apps/v1beta2/deployments?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.915981       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.ResourceQuota: Get https://192.168.1.181:6443/api/v1/resourcequotas?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.926853       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Secret: Get https://192.168.1.181:6443/api/v1/secrets?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.939837       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Event: Get https://192.168.1.181:6443/api/v1/events?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.956420       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.NetworkPolicy: Get https://192.168.1.181:6443/apis/networking.k8s.io/v1/networkpolicies?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.969187       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1beta2.StatefulSet: Get https://192.168.1.181:6443/apis/apps/v1beta2/statefulsets?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.979149       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.ReplicationController: Get https://192.168.1.181:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:58.993362       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Service: Get https://192.168.1.181:6443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.004756       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Namespace: Get https://192.168.1.181:6443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.014989       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.ServiceAccount: Get https://192.168.1.181:6443/api/v1/serviceaccounts?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.019157       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1beta2.ReplicaSet: Get https://192.168.1.181:6443/apis/apps/v1beta2/replicasets?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.023452       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.RoleBinding: Get https://192.168.1.181:6443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.037371       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.ClusterRoleBinding: Get https://192.168.1.181:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.050777       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Endpoints: Get https://192.168.1.181:6443/api/v1/endpoints?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.052183       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Role: Get https://192.168.1.181:6443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.068936       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Job: Get https://192.168.1.181:6443/apis/batch/v1/jobs?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.080397       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1beta2.DaemonSet: Get https://192.168.1.181:6443/apis/apps/v1beta2/daemonsets?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.084697       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1beta1.CronJob: Get https://192.168.1.181:6443/apis/batch/v1beta1/cronjobs?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.085769       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Pod: Get https://192.168.1.181:6443/api/v1/pods?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.099531       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1beta1.Ingress: Get https://192.168.1.181:6443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E1228 13:25:59.102842       5 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.ClusterRole: Get https://192.168.1.181:6443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
`

**Other details that may be helpful:**

We're using k8s nodes and clusters in our dev environment at the office and the nodes (onpremise and cloud) will be shut down at night and on weekends if they're not needed. This is resulting in nearly 100% of the rancher logs consisting of these messages. Maybe I'm just too stupid to find it but I could not find any location to change that behavior.

Is there any option to limit this or is there an exponential backoff on the roadmap?

**Environment information**

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.4 on Kubernetes v1.12.3-rancher1-1 but it occurred with older versions of both rancher2 and kubernetes as well.

- Installation option (single install/HA):

single node install on rancherOS

**Comment by superseb** [comment]
Linking to https://github.com/rancher/rancher/issues/16723
