### ISSUE TITLE
Rancher-Compose: check version when connecting to Rancher Server

### ISSUE THREAD

**Issue by anapsix** [rancher/rancher#1725]
It's too easy to get burned by using an incompatible version of `rancher-compose`.
It would make sense if `rancher-compose` would inform use when it's version is not compatible with the version of Rancher Server it's connecting to. It could provide a link to download an update and even self-update, upon receiving confirmation it's ok to do so that is.

**Comment by ibuildthecloud** [comment]
This is a good idea.  We really need to make a change to cattle for this.

**Comment by deniseschannon** [comment]
From v0.4.3+, we provide a warning if you are using another version that is not pinned with your rancher version. 

Verified with using rancher-compose v0.4.3 on v0.43.0-rc3 (which uses rancher-compose v0.5.0-rc2).
