### ISSUE TITLE
UI for Revise AKS kontainer-engine driver and add missing fields

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17262]
UI for https://github.com/rancher/rancher/issues/15697

**Comment by cjellick** [comment]
backend is in

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/6/19
Confirmed issue. Validated forms from UI perspective. Further testing around this with AKS will be tested by other members on the QA team.
CREATED new AKS cluster and specify values for the various additions per https://github.com/rancher/kontainer-engine/pull/107#issuecomment-452272906
Inspected http request payload and server resp to validate the new options. Inspect API and ensure everything looks correct.
UPGRADED (edit) AKS cluster and specify new values for the various additions per the comment above. Also inspected http request payload and server resp to validate new options. Inspect API and ensure everything looks correct. Confirm all of these are editable. Ensure in UI able to upgrade k8s, etc.
