### ISSUE TITLE
When adding cluster in UI, Kubernetes Version drop down selects wrong version

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#17263]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Log into Rancher UI
2. Add Cluster
3. Select Custom
4. Expand Cluster Options
5. In Kubernetes drop down select box, select v1.10.11-rancher-1-1

**Result:**
Note, it selects v1.12.3-rancher1-1 (experimental)

**Other details that may be helpful:**
Firefox 64.0 on MacOS X 10.14.2 (could not reproduce on Chrome or Safari)
See also this video: [k8s-version-select.mov.zip](https://github.com/rancher/rancher/files/2716088/k8s-version-select.mov.zip)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.4
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by n313893254** [comment]
Try 1/11/2019 master; the issue has fixed.

**Comment by jiaqiluo** [comment]
The bug is reproduced on v2.1.4 as the ticket describes.
The bug fix is validated on Rancher: master on 1/28
Firefox 64.0 & 65.0
