### ISSUE TITLE
Cannot upgrade Rancher catalog apps when their creator user is deleted

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17265]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Create a catalog app deployment, then delete the original user as someone else. Now, with the other user, try to upgrade the app installation.

**Result:**

App cannot be upgraded with following message:

```
Users.management.cattle.io "user-cpf9t" not found; waiting on helm-controller_local
```

Rancher pod logs show:

```
2018/10/24 13:42:17 [ERROR] AppController p-tmfn2/tpsk [helm-controller] failed with : users.management.cattle.io "user-cpf9t" not found
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs, 4 node setup
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/16274

**Comment by loganhz** [comment]
@cjellick 's proposed solution:

if you get a is-not-found error on the user, then check if the current user has permission to create apps (can use the subject access review api for this) and if they do, set them as the creator (effectively transfering ownership) and use them to execute the helm task

**Comment by orangedeng** [comment]
I implement the feature what @cjellick suggest. But still, if the updater can not access to the resources(workloads/configmap/...) the app needs, the app can't be deployed.

**Comment by cjellick** [comment]
@orangedeng but if the updater has the same perms as the orignal user that was deleted, it'll all work, correct?

**Comment by orangedeng** [comment]
Yes, it works. I check the app/create privilege of the updater.

**Comment by jiaqiluo** [comment]
The bug is reproduced on v.2.1.1
The bug fix is validated on master 2/1
Results:
- the app can be upgraded by another user when its creator is deleted
- the `creatorId` of the app is changed to the user who upgrades it
