### ISSUE TITLE
Units for CPU/Memory resource limits not consistent

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#17267]
rancher: v2.1.5-rc1

Created a workload with resource limits:
CPU: 2000m, 4000m
Memory: 4Gi, 8Gi
<img width="690" alt="screen shot 2018-12-29 at 10 07 56 pm" src="https://user-images.githubusercontent.com/19392926/50544807-5a648000-0bb6-11e9-972a-e5ea19bd326d.png">

**What's shown in UI:**

<img width="996" alt="screen shot 2018-12-29 at 10 06 51 pm" src="https://user-images.githubusercontent.com/19392926/50544811-5f293400-0bb6-11e9-83de-d7c5369329ed.png">

**Expected:**

Both reservation and limit should use the same units.
- 2000m/4000m or 2/4
- 8Gi/16Gi or ...

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/21/19)
Confirmed fix. Units are now in MiB only. 
When creating:
![image](https://user-images.githubusercontent.com/45179589/51500584-c4bea980-1d8b-11e9-9a56-e47e7c5908f7.png)
When checking workload details:
![image](https://user-images.githubusercontent.com/45179589/51500570-b96b7e00-1d8b-11e9-8359-6e7ca6c6d956.png)

When I create values in MiB in the UI they are expressed correctly when inspecting HTTP (which uses Gi if values were perfect i.e. 8192MiB = 8Gi in http request and 16384MiB in UI = 16Gi in http request). When I specify unique values such as 7777MiB in the UI they are properly at 7777Mi in http request. Validated API as well and smoke / halo tested this area.
