### ISSUE TITLE
Redeploy via CLI

### ISSUE THREAD

**Issue by jonaskello** [rancher/rancher#17275]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Run CLI command with redeploy option.

**Result:**
Run CLI command with redeploy should have same effect as running redeploy in the UI.

**Other details that may be helpful:**
This feature would make it possible to build a tool like`cdrx/rancher-gitlab-deploy` that works with rancher 2.0 (the current one only works for 1.6,  [see this issue](https://github.com/cdrx/rancher-gitlab-deploy/issues/38)).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.3
- Installation option (single install/HA): single install

**Comment by gabrielcalderon** [comment]
This is much needed feature! I was hoping to redeploy when a new image is created and the cli doesn't support this feature!

**Comment by loganhz** [comment]
link to https://github.com/rancher/rancher/issues/23053
