### ISSUE TITLE
Rename catalog field to catalogTemplate in pipeline applyApp/publishCatalog step

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17277]
At the moment it is called `catalog` but we are using it as the catalog template. Rename it to avoid confusion in API/pipeline file.
We use catalogTemplate + version to locate the chart we want to deploy/upgrade.

**Comment by davidnuzik** [comment]
@loganhz does this impact the UI visually? or is this just a label for a field or something along those lines?

**Comment by loganhz** [comment]
Hi @davidnuzik , it doesn't impact the UI visually and it's just a field change.

We haven't verified the deploy catalog app ini pipeline yet. So we can test it with https://github.com/rancher/rancher/issues/16026

Assign to @rootwuj who is testing https://github.com/rancher/rancher/issues/16026

**Comment by rootwuj** [comment]
Tested with Rancher version-2.2 master 01/23.
Verified fixed
This version of yaml has been modified to catalogTemplate.
