### ISSUE TITLE
Add ca checksum field to clusterregistrationtoken API

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#17273]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Call https://hostname:8443/v3/clusterregistrationtoken API

**Result:**
The nodeCommand contains the ca checksum, but it would be easier to parse the data if it was in it's own field.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.4
- Installation option (single install/HA):
single install

**Comment by PhilipSchmid** [comment]
Any updates on this? Thanks!

**Comment by aslafy-z** [comment]
Un-stale.

**Comment by aslafy-z** [comment]
Un-stale.

**Comment by aslafy-z** [comment]
Un-stale
