### ISSUE TITLE
Backport: k8s 1.11.6 support to address "Kubernetes 1.11.1 nodes occasionally do not register internal IP address"

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17280]
Backport https://github.com/rancher/rke/issues/860

**Comment by alena1108** [comment]
Support should be available in `v2.1.5-rc3`

**Comment by jiaqiluo** [comment]
Validated on v2.1.5-rc3
Steps:
- ran Rancher server version v2.1.5-rc3 (single Install)
- Ran test scrips on three clusters:
   - Ubuntu 16.04 docker 17.03.2-ce, k8s 1.11.6
   - RancherOS 1.4.2 docker 17.03.2-ce, k8s 1.11.6, 1 control plane, 1 etcd, and 3 workers
   - Rhel 7.5, native docker 1.13 with selinux enabled, k8s 1.11.6, 1 control plane, 1 etcd, and 3 workers
- Tests cover the following areas:
   - workload
   - dns
   - rbac
   - communication
   - ingress
   - secret
   - registry
   - service discovery
