### ISSUE TITLE
AD - Group changes not reflected in user attributes even after auth-user-info-max-age-seconds passed or forcing rancher login using cli

### ISSUE THREAD

**Issue by maxkorp** [rancher/rancher#17286]
Original issue: https://github.com/rancherlabs/rancher-security/issues/40

Original text:

Rancher server version - build from master

Steps to reproduce the problem:
AD auth enabled setup
Create a cluster with 3 projects:
p1 - member access given to "group1"
p2 - member access given to "group2"
p3 - member access given to "group3"

Log in to rancher UI as "user1" who is part of "group1" and "group2"
Create API keys.

Set "auth-user-info-max-age-seconds" to 120 seconds.

Use the above created keys to log in using rancher-cli.
User is provided access to both projects p1 and p2 as expected (./rancher project)

From AD console,  remove p1 from being part of "group2".

Wait for more than > "auth-user-info-max-age-seconds" to pass.

scenario 1:
In the current logged in rancher-cli session , execute ```./rancher project``` .
Both projects p1 and p2 are listed.

scenario 2:
Log into rancher-cli using the same token , execute ```./rancher project``` .
Both projects p1 and p2 are listed.

In this case , following error logs seen in rancher-server logs:
```
2018/12/14 01:22:48 [DEBUG] REST UPDATE apis/management.cattle.io/v3//userattributes/u-66zjeognlk
2018/12/14 01:22:48 [DEBUG] UserAttributeController calling handler mgmt-auth-userattributes-controller u-66zjeognlk
2018/12/14 01:22:48 [DEBUG] REST GET apis/management.cattle.io/v3//authconfigs/activedirectory
2018/12/14 01:22:48 [DEBUG] REST GET api//v1/mgmt-secrets/secrets/activedirectoryconfig-serviceaccountpassword
2018/12/14 01:22:48 [DEBUG] Now creating Ldap connection
2018/12/14 01:22:48 [DEBUG] Binding service account username password
2018/12/14 01:22:48 [DEBUG] LDAP Search query: {(sAMAccountName=activedirectory_user://CN=testguser1,CN=Users,DC=testad,DC=rancher,DC=io)}
2018/12/14 01:22:48 [ERROR] Error refreshing token principals, skipping: Cannot locate user information for (sAMAccountName=activedirectory_user://CN=testguser1,CN=Users,DC=testad,DC=rancher,DC=io)
2018/12/14 01:22:48 [DEBUG] REST UPDATE apis/management.cattle.io/v3//userattributes/u-66zjeognlk
2018/12/14 01:22:48 [DEBUG] UserAttributeController calling handler mgmt-auth-userattributes-controller u-66zjeognlk
```

In both scenario1 and scenario2 , we expect user to have access to only project p1 since they are not part of "group2" anymore.

Also the user-attributes does not reflect the group change (```kubectl get user attribute <user-id> -o json```)

Note:
When "user1" logs in using the UI , I see the user-attributes reflect the group changes as expected.
Further log ins done from rancher-cli using the older token shows only project p1.

**Comment by sangeethah** [comment]
Tested with latest build from master (Jan/10).
Group changes are reflected in user attributes when rancher cli calls are made after auth-user-info-max-age-seconds passed.

Following scenario works as expected:

AD auth enabled setup
Create a cluster with 3 projects:
p1 - member access given to "group1"
p2 - member access given to "group2"
p3 - member access given to "group3"

Log in to rancher UI as "user1" who is part of "group1" and "group2"
Create API keys.

Set "auth-user-info-max-age-seconds" to 120 seconds.

Use the above created keys to log in using rancher-cli.
User is provided access to both projects p1 and p2 as expected (./rancher project)

From AD console, remove p1 from being part of "group2".

Wait for more than > "auth-user-info-max-age-seconds" to pass.

From the current logged in rancher-cli session , execute ./rancher project .
Only projects p1 is listed as expected.
