### ISSUE TITLE
Workload details page shows toleration settings as editable

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17285]
Version: master 2.2 (1/2/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a workload and set toleration settings under Node Scheduling (click Show advanced options to see this)
- Add a toleration such as:
Label key: node-role.kubernetes.io/controlplane
Operator: Equals
Value: true
Effect: NoExecute
Time: 0 (seconds)
- Once the deployment is done provisioning, click on the workload name to see details and expand the Node Scheduling section.

**Result:**
The toleration settings are editable in the UI. This has no effect on the workload but these fields should not be editable.
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/50615451-d524e800-0ea1-11e9-950c-fceecc0ab97d.png)

**Comment by westlywright** [comment]
@davidnuzik According to `/v3/project/<SOMEPROJECTID>/schemas/toleration` tolerations are all updatable. If they shouldn't be this will need a backend ticket before the UI change. If they are updatable but have no effect when changed this ticket should be `area/api` 
<img width="548" alt="Screenshot 2019-04-19 14 59 07" src="https://user-images.githubusercontent.com/858614/56445751-b9f4b180-62b3-11e9-96fd-f6c94bab9894.png">

**Comment by alena1108** [comment]
@davidnuzik Kubernetes does allow to update tolerations on the workloads. When you say `This has no effect on the workload but these fields should not be editable.` - do you mean the updated values are not being persisted/displayed back to the user? Or there is some backend functionality - like pods being evicted, etc - you expected, but that didn't happen?

**Comment by davidnuzik** [comment]
@alena1108 @westlywright the problem is that we are not in an "Edit" view in the API here. We are only viewing details for the workload, thus we should not be able to access dropdowns, text boxes, etc.

I can't save changes I make because there is no "Save" button because this is just viewing details of workload (not editing workload).

**Comment by alena1108** [comment]
@davidnuzik looks like a UI issue, @westlywright can you confirm.

**Comment by westlywright** [comment]
Yes if this is not the edit view then this is a UI bug.

**Comment by davidnuzik** [comment]
Version: master-head (7/30/19)

- Create the workload, set toleration settings.
- Click on the workload to view it's details.

Now, Tolerations are no longer shown as "editable" in the workload details page:
![image](https://user-images.githubusercontent.com/45179589/62142649-8dcdd100-b2a3-11e9-8104-0c34b63dd20f.png)
