### ISSUE TITLE
Failed To Update StatefulSet with VolumeClaimTemplates

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17283]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a stateful set workload with a volumeClaimTemplate
Edit workload with or without changes 

**Result:**
Error is returned from the API
`StatefulSet.apps "wl1" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

**Other details that may be helpful:**
Upstream K8s Dependency: https://github.com/kubernetes/kubernetes/issues/69041
Possibly related to rancher/rancher#16984

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master (new cluster 01/02/19)
- Installation option (single install/HA): single

**Comment by gittygoo** [comment]
i can also confirm this bug, interestingly enough editing the YAML via the GUI allows you to save properly (if you dont touch the volumeClaimTemplate)
Related to : https://forums.rancher.com/t/statefulset-image-upgrade-forbidden/13214/6

**Comment by loganhz** [comment]
close in favor of https://github.com/rancher/rancher/issues/25089
