### ISSUE TITLE
[Rancher] Ensure rancher images are portable, agents do not need internet access

### ISSUE THREAD

**Issue by mryuha** [rancher/rancher#1728]
I have agents behind firewalls that can't access github.  The agents are trying to access github to obtain files such as host-api, rancher-dns.

**Comment by cjellick** [comment]
Hi @mryuha we are currently working on a version of Rancher that will exactly what you need. All the binaries we attempt to download will be packaged into the container(s). We'll update this issue when it is completed. I don't have know the issue number for this feature off hand, but I'll find it and post it.

We also currently have a solution where you can send the Internet bound traffic through a proxy. Not sure if it will work for you, but some of our other users have found it to be a reasonable solution. Here's the details: http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#hosts-behind-a-proxy

**Comment by deniseschannon** [comment]
Here's the feature that @cjellick was mentioning. It's basically running Rancher server without internet. https://github.com/rancher/rancher/issues/924

**Comment by Telmo** [comment]
:+1:

#924 is specifically for the Server, our issue is running agents in networks that because of their security level are not allowed to access the internet, even through proxies.

**Comment by deniseschannon** [comment]
Closing as this was implemented with #924.

http://docs.rancher.com/rancher/installing-rancher/installing-server/no-internet-access/
