### ISSUE TITLE
Ports for service in payload will be ignored in Rancher API

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17288]
rancher/rancher:master 02/01

Rancher will always drop the ports in the payload and add a default 42 port in server side.
https://github.com/rancher/rancher/blob/master/pkg/api/store/service/service.go#L46

So we cannot add custom ports for a service to address https://github.com/rancher/rancher/issues/15070

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/15/19 1:20PM PST)
Confirmed fixed. I was reproducing the issue with a slightly older build from the same day.
I tested by creating a LB service and this is now working. I also halo tested, test ingresses, etc and encountered no issues.
