### ISSUE TITLE
AWS cloudprovider error

### ISSUE THREAD

**Issue by a-dawg** [rancher/rancher#17296]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
rke up

**Result:**
```
I0103 10:34:16.943370   23494 aws.go:988] Zone not specified in configuration file; querying AWS metadata service
F0103 10:34:16.945894   23494 server.go:233] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0a1cf7f4a37a9c92b: "error listing AWS instances: \"NoCredentialProviders: no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\""
```
How to solve one not specified in configuration file; querying AWS metadata service?
I have the right iam permissions and I have configured the aws credentials on my workerplane instance as well as the region.
How could I solve this?

**Other details that may be helpful:**
using rke and aws as cloud provider

**Cluster information**
- cluster installed on AWS EC2, deployment using rke
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version
```
17.03.3-ce
```

**Comment by superseb** [comment]
Cloud provider requirements are listed on https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/aws/, you are not specifying what you have configured. The error is regarding not having the correct IAM role on the instances you are provisioning. 

If it's not working, please provide full details on what configured as that helps reproducing or root causing the issue. Also, if you are only using RKE, please file an issue at https://github.com/rancher/rke/issues/new
