### ISSUE TITLE
Rollback app but got another new revision 

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#17298]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
- deploy an app with catalog or local folder, record as `revision-a`
- upgrade the app, , record as `revision-b`
- rollback to previous `revision-a`

**Result:**
Another revision has been created

**Expected:**
~~Rollback to the correct revision without any new creating~~
Another revision has been created with the operation description

**Comment by thxCode** [comment]
Revision is another record for operation, it is increasing. But rancher app revision doesn't have operation description, I think we need to enrich this. For example:

Steps:
```
1. deploy an app with catalog or local folder, record as revision-a
2. upgrade the app, , record as revision-b
3. rollback to previous revision-a
```

Show revisions:
```
1. install app version a
2. upgrade app version b
3. rollback app to version a
```

**Comment by loganhz** [comment]
Close  in favor of https://github.com/rancher/rancher/issues/18571
