### ISSUE TITLE
[UI] Rancher 2 Logs - 500 Internal Server Error

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#17302]
I'm unable to find any errors in the logs, I've looked at the cattle-system namespace and all the pod logs, I can't seem to find any HTTP or WS logs to indicate why the 500 is being thrown?

**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** Deploy any workload, attempt to view logs, immediately get disconnected, browser shows 500 Internal Server Error.

**Result:** 500 Internal Server Error

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-alpha3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported HA
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/17028

**Comment by ekristen** [comment]
Thanks @superseb, missed that in my search.
