### ISSUE TITLE
Simplify enable cluster monitoring page

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17306]
Version: master 2.2 (1/3/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Notice that to enable cluster/project level monitoring we have two choices, None or Prometheus. We should change this to something simpler since there are only two options -- monitoring is either on or off. I understand that there are options for Prometheus but we don't like these large icons for these two choices.

![image](https://user-images.githubusercontent.com/45179589/50655924-db24d280-0f4e-11e9-857a-39d15d07eaa4.png)

I propose removing the icons and try to make the page more compact (i.e. Disabled and Enabled radio buttons or something) Then when enabled options can show up for Prometheus. Contact me with any questions.

**Comment by westlywright** [comment]
I dont think it makes sense to change design of this. Its consistent with our other the way we select other resources when multiple config options are available, see auth or cluster select etc.

@vincent99 your thoughts?

**Comment by vincent99** [comment]
This is not one of those situations though; monitoring isn't pluggable, there isn't multiple choices available, and we have no plans for others.  So I agree it should be a radio for disabled or enabled.

The "Please go to the System project catalog app and find cluster-monitoring app to update the configuration" part is not very nice though, I'd expect it to reveal all the configuration options if you choose enabled.  At the very least it should be able to link you to editing the appropriate app.

**Comment by loganhz** [comment]
Backend doesn't support update monitoring options via monitoring API.
As a short term solution, I have added the link to editing monitoring app page.
Created a new issue to track it https://github.com/rancher/rancher/issues/17340

**Comment by davidnuzik** [comment]
@loganhz @westlywright may we change the title of the /monitoring/cluster-setting page? I would argue that Prometheus is more or less abstracted from the user. They just want to turn on "monitoring" can we change the title from "Cluster Prometheus Configuration" to just "Cluster Monitoring Configuration" ?
![image](https://user-images.githubusercontent.com/45179589/50918989-eff5e000-13fe-11e9-8fbd-6ad380832d4d.png)

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/10/19)
Confirmed enhancement. We now have an option on this page to Enable or Disable Cluster/Project Monitoring. Smoke tested this and monitoring in general to ensure everything is still functioning correctly. Screenshots:
Cluster level:
![image](https://user-images.githubusercontent.com/45179589/50990749-23ed0600-14d0-11e9-887f-fc3d53f984c3.png)

Project level:
![image](https://user-images.githubusercontent.com/45179589/50990717-06b83780-14d0-11e9-9b1a-9cb414eed80e.png)
