### ISSUE TITLE
how i can create workload with local docker image

### ISSUE THREAD

**Issue by TheYkk** [rancher/rancher#17300]
rancher 2.0
i can see my image in server vps  http://prntscr.com/m2mxq7

when i create workload its not working http://prntscr.com/m2my07

http://prntscr.com/m2myal

how i create workload with local image

**Comment by superseb** [comment]
Using local images:
Default ImagePullPolicy is always, so it won't use a local image if present. You can change it when deploying a Workload -> Advanced Options -> Security & Host Config.

Using private registry:
You add a registry with `:5000` but don't specify it when launching the workload. You need to provide the full address to the registry. 

The events will provide better errors on why it is failing, but my guess is one of those.

**Comment by TheYkk** [comment]
> Using local images:
> Default ImagePullPolicy is always, so it won't use a local image if present. You can change it when deploying a Workload -> Advanced Options -> Security & Host Config.
> 
> Using private registry:
> You add a registry with `:5000` but don't specify it when launching the workload. You need to provide the full address to the registry.
> 
> The events will provide better errors on why it is failing, but my guess is one of those.

iam usin rancher 2.x version i cant see  Workload -> Advanced Options -> Security & Host Config.

**Comment by TheYkk** [comment]
> Using local images:
> Default ImagePullPolicy is always, so it won't use a local image if present. You can change it when deploying a Workload -> Advanced Options -> Security & Host Config.
> 
> Using private registry:
> You add a registry with `:5000` but don't specify it when launching the workload. You need to provide the full address to the registry.
> 
> The events will provide better errors on why it is failing, but my guess is one of those.

thanks

**Comment by superseb** [comment]
Let me know if it doesn't solve your issue.

**Comment by TheYkk** [comment]
> Let me know if it doesn't solve your issue.

how i change cluster ip for load balancer http://prntscr.com/m2nbc1
i want change 10.0.2.15 to 192.168.37.1(main ip)
