### ISSUE TITLE
K8s 1.12/k8s1.13 : Service discovery fails for a record pointing to multiple daemonsets

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17309]
Rancher Version:
v2.1.5-rc4

Kubernetes Version:
v1.12.4

Steps:
1. Create few daemonsets and workloads
2. Create service discovery record pointing two daemonsets or one workload and one daemonset.

Service discovery fails when pointing to two daemonsets or one workload and one daemonset

**Comment by sowmyav27** [comment]
Service discovery fails when pointing to a daemonset.
rancher version:v2.1.7-rc2
k8s v1.12.5.

**Comment by soumyalj** [comment]
Service discovery fails when pointing to a daemonset.
rancher version:v2.1.7-rc2
k8s v1.13.1

**Comment by alena1108** [comment]
Happens due to k8s 1.10 being a base version for rancher and norman (vendor.conf). Have to switch to 1.12 base

**Comment by alena1108** [comment]
Resolved in `rancher/rancher:v2.1.7-rc4`

**Comment by alena1108** [comment]
Can be tested on `rancher/rancher:v2.1.7-rc7`

**Comment by sowmyav27** [comment]
verified on `rancher/rancher:v2.1.7-rc7` and k8s version `v1.12.6`.
Service discovery works when pointing to a daemonset. 
<img width="584" alt="screen shot 2019-03-01 at 11 58 35 am" src="https://user-images.githubusercontent.com/26032343/53663710-53d8a000-3c1b-11e9-8f15-523cfab338d8.png">

**Comment by soumyalj** [comment]
Teted with v2.1.7-rc9 with k8s version 1.13.4
Service discovery works for a record pointing to multiple daemonsets or one workload and one daemonset
```
root@ttt-7x4f6:/# dig dsetrecord.default.svc.cluster.local

; <<>> DiG 9.10.3-P4-Debian <<>> dsetrecord.default.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45982
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dsetrecord.default.svc.cluster.local. IN A

;; ANSWER SECTION:
dsetrecord.default.svc.cluster.local. 19 IN A   10.42.0.43
dsetrecord.default.svc.cluster.local. 19 IN A   10.42.2.73
dsetrecord.default.svc.cluster.local. 19 IN A   10.42.2.69
dsetrecord.default.svc.cluster.local. 19 IN A   10.42.1.69
dsetrecord.default.svc.cluster.local. 19 IN A   10.42.1.65
dsetrecord.default.svc.cluster.local. 19 IN A   10.42.0.47

;; Query time: 0 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Sat Mar 02 23:53:05 UTC 2019



```
