### ISSUE TITLE
UI for configuring custom CA root certificate in pipeline

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17314]
Expose the `git-cacerts` pipeline setting in the UI so that users can configure their custom ca root certificate and do the clone from self-signed-cert git service.

**Comment by gitlawr** [comment]
Related to https://github.com/rancher/rancher/issues/16136

**Comment by westlywright** [comment]
@gitlawr or @loganhz can you add some QA how to test text?

**Comment by gitlawr** [comment]
Steps to test:
1. set up a self-signed cert git service(gitlab/github/bitbucket server)
2. add the CA root certificate to Rancher server container, following the [instruction](https://rancher.com/docs/rancher/v2.x/en/admin-settings/custom-ca-root-certificate/).
3. Integrate with the git service in project-tools-pipeline.
4. Configure the CA root certificate setting in project-tools-pipeline.
5. Configure and run a pipeline and verify that it can do clone and build using the self-signed-cert git repo successfully.

**Comment by rootwuj** [comment]
@loganhz  
The UI only supports pasting text, but the prompt message contains the `necessary chain certificate`. It is best to modify the default prompt message.

**Comment by loganhz** [comment]
@rootwuj Checked with @gitlawr . The text is expected.

**Comment by rootwuj** [comment]
Verified with rancher/rancher:master 01/29

* Check the UI display
* Validate Github, Gitlab, Bitbucket pipeline settings
* Validate add, modify, delete CA
