### ISSUE TITLE
if cpu limits set in project/namespace pods can't be deployed

### ISSUE THREAD

**Issue by michalswi** [rancher/rancher#17316]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
![selection_006](https://user-images.githubusercontent.com/18167377/50697151-c1b08300-1041-11e9-83f9-acfbaf1c1c28.png)
![selection_007](https://user-images.githubusercontent.com/18167377/50697152-c1b08300-1041-11e9-8ebd-3d7a44eb4c11.png)

On cluster deployed by RKE project (testproject) with CPU limit was created. In this project namespace (testns) was created with added limit. 
```sh
$ kubectl describe quota -n testns
Name:       default-w4cvq
Namespace:  testns
Resource    Used  Hard
--------    ----  ----
limits.cpu  0     2

# base on that: https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/

$ kubectl apply -f https://k8s.io/examples/application/deployment.yaml -n testns
deployment.apps/nginx-deployment created

$ kubectl describe quota -n testns
Name:       default-w4cvq
Namespace:  testns
Resource    Used  Hard
--------    ----  ----
limits.cpu  0     2

$ kubectl get pods -n testns
No resources found.

$ kubectl get svc -n testns
No resources found.

# I did that in default namespace without quota and it worked:
$ kubectl apply -f https://k8s.io/examples/application/deployment.yaml
deployment.apps/nginx-deployment created
$ kubectl get pods
NAME                                READY   STATUS    RESTARTS   AGE
hello-app-794869cb84-8m662          1/1     Running   0          13m
nginx-deployment-5c689d88bb-lmjlv   1/1     Running   0          27s
nginx-deployment-5c689d88bb-zwx5r   1/1     Running   0          27s
```

**Environment information**
RKE 0.1.13
Kubernetes v1.12.3

**Cluster information**
OS: Ubuntu 16.04.4 LTS
Cloud provider: openstack
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):
```
version: 17.3.2
```

**Comment by vincent99** [comment]
Every workload in a project/namespace that is using quotas needs to have appropriate reservations/limits set in order to enforce the quotas.

**Comment by michalswi** [comment]
@vincent99, do you mean reservations related to VM resources?
There was already created issue related to quotas:
https://github.com/rancher/rancher/issues/16746
Closed without comments.

**Comment by vincent99** [comment]
No;  As I said above if you turn on a project quota for some resource (like CPU) then _every_ workload in the namespaces of that project must specify their reservation of that resource they want.  Quotas are a _scheduling_ construct, not realtime enforcement of the utilization.  So they only way they can control how much is used is to not allow the scheduling of new pods that will exceed the available quota (or do not specify how much they want).

(That issue was closed, by the creator, less than 12 hours after being created, probably because they figure out their problem was exactly what the error said, `exceeded quota: default-wcxcn, requested: secrets=1, used: secrets=4, limited: secrets=0`.  0 does not mean unlimited, it means 0)

**Comment by michalswi** [comment]
Got it. It works if Pod has specified limits and requests. I thought that if you don't specify resources in pod(.yml file) it will take defaults one using LimitRange. Problem solved. Sorry for inconvenience.
```sh
# project 'aaa' with quota for CPU and Memory + namespace 'bbb'
$ kubectl describe quota -n bbb
Name:            default-5snpl
Namespace:       bbb
Resource         Used  Hard
--------         ----  ----
limits.cpu       0     2
limits.memory    0     2Gi
requests.cpu     0     1
requests.memory  0     1Gi
$ kubectl create -f https://k8s.io/examples/admin/resource/quota-mem-cpu-pod.yaml -n bbb
pod/quota-mem-cpu-demo created
$ kubectl describe quota -n bbb
Name:            default-5snpl
Namespace:       bbb
Resource         Used   Hard
--------         ----   ----
limits.cpu       800m   2
limits.memory    800Mi  2Gi
requests.cpu     400m   1
requests.memory  600Mi  1Gi
$ kubectl get pods -n bbb
NAME                 READY   STATUS    RESTARTS   AGE
quota-mem-cpu-demo   1/1     Running   0          17s
```
