### ISSUE TITLE
ui-index will be reset to the default value during rancher server restarts

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17312]
This issue will be introduced in the PR https://github.com/rancher/rancher/pull/17208

Steps to reproduce

1. Start rancher server
2. Change ui-index from `local` to `https://releases.rancher.com/ui/latest2/index.html`
3. Restart rancher server

Results:

ui-index has been reset to `local`

Expected:

ui-index should still be `https://releases.rancher.com/ui/latest2/index.html`

**Comment by cjellick** [comment]
@orangedeng @loganhz can this be sent to test now? no additional changes needed, right?

**Comment by cjellick** [comment]
Had to revert the fix. Sending back to dev

**Comment by loganhz** [comment]
I will validate this issue

**Comment by cjellick** [comment]
@loganhz to validate

**Comment by loganhz** [comment]
Validated in rancher/rancher:master 02/20

Case 1:

1. Start rancher and change the ui-index to another cdn url
2. Restart rancher server

Result:

The ui-index is correct.

Case 2:

1. Start rancher and change the ui-index to local
2. Restart rancher server

Result:

The ui-index is still local.
