### ISSUE TITLE
Delete rancher pipeline repository failed if the authorizing gitlab user is deleted

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#17322]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Delete the gitlab user which authorized the application to rancher pipeline.
Try to delete the pipeline repositotry.
**Result:**
Rancher server prints log:
````
PipelineController failed with : sourceCodeCredential.project.cattle.io "user-6d6s7/p-kf5rz-gitlab-yangyuan" not found
````
The repository keeps in removing status all the time.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.3
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yeldiRium** [comment]
Can confirm this problem. Is there a workaround to manually remove the pipelines?

**Comment by bmdepesa** [comment]
@gitlawr 

* Created gitlab project (cloud hosted)
* Added second user to the gitlab project 
* Created pipeline in Rancher using application id/secret from the second user
* Deleted second user
* Attempt to delete pipeline
* Pipeline is stuck in removing

**Comment by gitlawr** [comment]
@yeldiRium 
Workaround:
Edit the stuck pipeline resource in management plane and remove the finalizer lines
`$ kubectl edit pipeline [PIPELINE_ID] -n [PROJECT_ID]`
By management plane, it means `docker exec` to rancher server container in standalone mode, or kubectl to the local cluster in HA mode. But be careful of other stuff there since it is the persistent data rancher relies on

**Comment by bmdepesa** [comment]
rancher/rancher:master 3/1

* Created cluster
* Created secondary user for Gitlab project
* Created pipeline with secondary user's application credentials
* Deleted the secondary user
* Deleted the pipeline
* Deleted the repository

All was successful.
