### ISSUE TITLE
Can not edit cluster

### ISSUE THREAD

**Issue by lazybetrayer** [rancher/rancher#17325]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

When add cluster, I add `private_registries` to the yaml file.
I can successfully add nodes to the cluster.
But when I edit the cluster, the page shows error `*%cruPrivateRegistry.defaultError%*` even if I didn't change anything.

**Result:**

![image](https://user-images.githubusercontent.com/4188244/50733778-2220fb00-11cf-11e9-83ab-31cef413afaf.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA): HA

**Comment by n313893254** [comment]
@loganhz Compared and tested in `master` and `v2.1.5`, Already fixed in `master`.

**Comment by kingsd041** [comment]
Version: master 2.2 (1/30/19)  image id: 4cf95ecf529b
Confirmed fix.
