### ISSUE TITLE
How can I pass entire json configuration via rancher multiline question?

### ISSUE THREAD

**Issue by kostrahb** [rancher/rancher#17328]
How can I pass entire json configuration via rancher multiline question?

**What kind of request is this (question/bug/enhancement/feature request):**

Question, possibly bug

**Steps to reproduce (least amount of steps as possible):**

The main thing I want to achieve is to pass entire JSON string via rancher multiline question to the Helm chart and then mount it to the pod as a secret file. The details and a simple Helm chart are described [here](https://stackoverflow.com/questions/54038837/how-to-pass-entire-json-string-to-helm-chart-value).

My question looks like this:

    - variable: config
      default: ""
      description: Configuration in json format.
      label: "Configuration"
      group: configuration
      type: multiline

**Result:**

If I pass simple JSON such as `{"json":"something"}` and examine the content of secret I get totally wrong JSON: `["\"json\":\"something\""]`

**Other details that may be helpful:**

This issue arises almost certainly due to how rancher handles questions and passes its values to Helm. I have no problem when installing Helm chart with Helm and overriding `config` value with another value file such as:

    config: {"json": "something"}

**Environment information**

Component | Version
-- | --
Integration | v2.1.3
User Interface | v2.1.17
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/23008
