### ISSUE TITLE
[fluentd-logging] buffer files are not cleaned up

### ISSUE THREAD

**Issue by quorak** [rancher/rancher#17324]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. setup elasticsearch logging for project
2. produce lots of logs, so that they are buffered
3. after a while the buffer directory gets a lot of buffer files over many days that fill up the server

**Result:**
![image](https://user-images.githubusercontent.com/68172/50726742-aad96180-1111-11e9-8bb6-4f1e2c5bffef.png)
![image](https://user-images.githubusercontent.com/68172/50726803-4a96ef80-1112-11e9-8219-c51d4fe26146.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.3
- Installation option (single install/HA):
single
- Fluentd container version
Image: rancher/fluentd:v0.1.10

**Comment by totogo** [comment]
I'm having the same issue in version ```2.2.7```, the rancher fluentd buffer file quickly eats up 50G disk space in the node, causing Has Disk Pressure alert.

**Comment by georev** [comment]
Same issue on 2.2.3

**Comment by pirminjanka** [comment]
we have the same issue on rancher 2.3.2 > fluentd buffer fills up /var fs up to 90% (folder: /var/lib/rancher/fluentd/log/buffer/cluster.buffer*) which ends up in disk pressure and node unscheduling

**Comment by dmlabs** [comment]
Same issue here on v2.3.2.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/21451
