### ISSUE TITLE
Cannot pull private docker image from Docker Hub

### ISSUE THREAD

**Issue by yu36yuqing** [rancher/rancher#17323]
**Error Message**   
(Container should have been running but is in error state. Check logs for more information.: Error response from daemon: Get https://registry-1.docker.io/v2/XXXXXX/XXXXX/manifests/latest: unauthorized: incorrect username or password) 

**Context** 
I have added the Docker Hub account into the rancher registries，and I make my image XXX to a private one on the Docker Hub web page. Then, I failed to upgrade the service which base on XXX image.

If I change the image XXX into a public one, it could be success to upgrade the service.
Many thanks for your response to this question.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.25` Cattle: `v0.183.68` UI: `v1.6.49` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
