### ISSUE TITLE
Rancher 2.1.5   Login problem when using subdomain

### ISSUE THREAD

**Issue by gelinger777** [rancher/rancher#17327]
I have a strange problem. I  have installed Rancher via docker on ip. 
I have then setup subdomain, which is via dns directed to the IP where rancher is installed. Strangely when I login to rancher using IP in browser, it works. When I visit the rancher via subdomain , it opens the login page, but login does not work. It says 

> Logging in failed: Check credentials, or your account may not be authorized to log in

Any ideas why ?

**Comment by loganhz** [comment]
Are you using local auth? A Record works for me

**Comment by loganhz** [comment]
BTW, I am using v2.1.3

**Comment by gelinger777** [comment]
I am using the very default login system. I have set it up with docker and when it asked for a password on first run, I have provided a password. Also I have provided the hostname. That's it.

**Comment by gelinger777** [comment]
I think that that time problem could be also the cloudflare  via which my domain was served.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue in Rancher 2.3, and we'll reopen it
