### ISSUE TITLE
hostPort not functional when testing  Network Provider is set to "weave".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17336]
Rancher server version - Build from master - Jan 4

Steps to reproduce the problem:
Create a cluster with  Network Provider is set to "weave".
Create a workload with "portmapping" set to "hostPort".
Once the workload is deployed , clicking on endpoint URL is not functional.

comments from @galal-hussein:
it turned out that weave 2.1.2 doesn't support hostPort
the latest version does though 2.5.0

**Comment by alena1108** [comment]
@galal-hussein can we update weave version for k8s 1.12 as well? https://github.com/rancher/types/blob/ca1efcec973c149667b17776bb704710a6f3d566/apis/management.cattle.io/v3/k8s_defaults.go#L742

We can also add 1.12.5 as it's the latest version

**Comment by galal-hussein** [comment]
Updated k8s 1.12 to 1.12.5 and weave to v2.5.0 in both k8s versions 1.12.5 and 1.13

**Comment by sangeethah** [comment]
Tested with rancher sever built from master - Jan 28

Created a 1 node DO cluster with Network Provider is set to "weave".
Cluster gets to "Active" state. But node continues to be in "Unavailable" state forever with following status:

"Runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"

The behavior is seen with both K8s version  v1.12.5 and v1.13.1
