### ISSUE TITLE
helm templates exceeds inode limit

### ISSUE THREAD

**Issue by KuroObi** [rancher/rancher#17330]
**What kind of request is this (question/bug/enhancement/feature request):**
Our rancher server host run out of free inodes due to the helm templates.
The /tmp folder inside the rancher/rancher container creates a folder for each commit, even if the version is no longer visable in the ui. 

**Steps to reproduce (least amount of steps as possible):**
Connect a git helm chart repo with a lot of commits (>2000 commits)

**Result:**
Filesystem runs out of inodes

df -i /var/lib/docker/
Filesystem       Inodes   IUsed   IFree IUse% Mounted on
/dev/md2       13492224 13492224 0   100% /

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:2.1.3
- Installation option (single install/HA): single node install
```
- Docker (use `docker info`): Server Version: 17.06.2-ce
```

**Comment by erikwilson** [comment]
This should be fixed as part of rancher/rancher/issues/14322 PR (#17596).

There was a part of the code in helm.generateTemplates where we were improperly cleaning up a ioutil.TempDir call.

**Comment by erikwilson** [comment]
To test this change first you need to find the directory that golang ioutil.TempDir uses for creating temporary directories. On OSX the directory is something like `/var/folders/kg/hqsbshz50fg8qxwrt2c5q1980000gn/T`, while on Linux it may be in `/tmp`. There should be other files in this location, like Rancher logs.

It is best to start with Rancher server v2.1.6:
- Install a library App
- Observe that the temp location contains a new directory like `helm-XXXXXXXXXX` after install is complete

Upgrade to Rancher master:
- Install a library App
- Observe that the temp location does not retain any new directories like `helm-XXXXXXXXXX` after install is complete

**Comment by sowmyav27** [comment]
Reproduced this in `rancher:v2.1.6`

<img width="879" alt="screen shot 2019-02-25 at 2 57 47 pm" src="https://user-images.githubusercontent.com/26032343/53374713-ff2ce080-390d-11e9-9363-38fca47e917e.png">
<img width="1296" alt="screen shot 2019-02-25 at 2 58 09 pm" src="https://user-images.githubusercontent.com/26032343/53374715-00f6a400-390e-11e9-8d88-1e652cd0abe9.png">

Verified in `rancher:master`. temp location does not retain any new directories like `helm-XXXXXXXXXX`

<img width="332" alt="screen shot 2019-02-25 at 3 06 15 pm" src="https://user-images.githubusercontent.com/26032343/53375069-14eed580-390f-11e9-9290-7ef441cbfa8d.png">
<img width="1337" alt="screen shot 2019-02-25 at 3 06 47 pm" src="https://user-images.githubusercontent.com/26032343/53375075-18825c80-390f-11e9-8dcc-70abc9818343.png">
