### ISSUE TITLE
The Service "nginx" is invalid: spec.clusterIP: Invalid value: "None": may not be set to 'None' for LoadBalancer services

### ISSUE THREAD

**Issue by jmwilkinson** [rancher/rancher#17332]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Follow Metallb docs to try and setup a load balancer service for an nginx pod.

https://metallb.universe.tf/usage/

**Result:**
ImportYaml Error
The Service "nginx" is invalid: spec.clusterIP: Invalid value: "None": may not be set to 'None' for LoadBalancer services

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.4
- Installation option (single install/HA):
single install

**Comment by jmwilkinson** [comment]
Appears to be related to the load balancer in k8s, not kubernetes.

**Comment by MohammedFadin** [comment]
Has this been solved? what was the solution?
