### ISSUE TITLE
Deploy workload failed: statefulSetConfig could not be found

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17338]
**Rancher Version:** master 1/8

**Steps to reproduce:**
1. provision a gke cluster
2. In default project, deploy a workload.
3. input workload name, use `nginx` image, leave the rest configs default.

**Result:**
Get Error `Property set failed: object in path "statefulSetConfig" could not be found or was destroyed.` in the UI.
![image](https://user-images.githubusercontent.com/5697937/50810653-aa291100-1345-11e9-8c37-5bb15b008d0a.png)

**Comment by davidnuzik** [comment]
This issue is resolved and confirmed fixed in latest master see #17343 for notes.
