### ISSUE TITLE
Unable to create any clusters on master

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17334]
Version: master 2.2 (1/7/19) (Image ID 90cf3ce3f0c9)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, blocking

**Steps to reproduce (least amount of steps as possible):**
- Pull latest rancher/rancher:master and try to create any cluster

**Result:**
You will get errors in the rancherserver logs for any relevant driver such as:
```
2019/01/07 22:46:49 [INFO] kontainerdriver azurekubernetesservice stopped
2019/01/07 22:46:54 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10424
```

This seems to happen infinitely or at least for quite some time. In the UI you will get: `Failed while: Wait for Condition: InitialRolesPopulated: True`

Sometimes if you try to create again you will get the same message or if you wait a while (2-10 minutes) the cluster may actually provision.

**Other details that may be helpful:**
Single-node install on supported Ubuntu 16.04 w/ supported Docker 17.03

**Comment by orangedeng** [comment]
It seems like this issue cause the problem https://github.com/rancher/rancher/issues/14592.

function `updateClusterAnnotationandCondition` wait too long to update cluster condition `ClusterConditionInitialRolesPopulated`.

**Comment by orangedeng** [comment]
@loganhz @cjellick I am testing this issue and It seems an UI problem. After I create a new cluster, I get `InitialRolesPopulated` condition in WS response already. It should not pop up a timeout error `Failed while: Wait for Condition: InitialRolesPopulated: True`.
<img width="1110" alt="2019-01-08 5 03 04" src="https://user-images.githubusercontent.com/15376837/50820417-8d053a00-1367-11e9-9207-5af5d38ba267.png">

**Comment by loganhz** [comment]
@orangedeng Thanks for the investigation 
It will be fixed in https://github.com/rancher/ui/pull/2557

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/8/19)
Confirmed fix. I am no longer able to reproduce this issue. I tried most of the providers and all are working without any issues. Validated HTTP.
