### ISSUE TITLE
Hide controller manager and scheduler for AKS cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17344]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

Due to an upstream bug in K8s, the AKS cluster shows the `controller manager` and `scheduler` unhealthy forever. But the AKS cluster still works without problems, so it will be great if we can hide those two items from UI.
<img width="1486" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/50849326-ec495700-1333-11e9-8f54-3dc55f25b409.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v2.0+

related issues: 
https://github.com/rancher/rancher/issues/11496
https://github.com/Azure/AKS/issues/173

**Comment by vincent99** [comment]
Do these ever really have meaning for the hosted providers?  I'd probably rather there be a capability entry for something like `usefulComponentStatuses` managed by the backend instead of the UI hardcoding behavior for AKS.

**Comment by jonesbusy** [comment]
+1 for this issue

**Comment by cjellick** [comment]
We will probably drop them soon

**Comment by deniseschannon** [comment]
We don't need to hide, but maybe grey out so that at least it's not looking like a bug when it's just expected due to the AKS issues.

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master 5d74988c

The `Controller Manager` and `Scheduler` are grayed out and no error messages showing in the UI anymore. 
<img width="1294" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57478812-bf10a500-7250-11e9-92fc-9cdafd6d8aac.png">

**Comment by dhawaldenny** [comment]
> The bug fix is validated on Rancher: master [5d74988](https://github.com/rancher/rancher/commit/5d74988c06762f5e516b6d2814156892504e9266)
> 
> The `Controller Manager` and `Scheduler` are grayed out and no error messages showing in the UI anymore.
> <img alt="screenshot" width="1294" src="https://user-images.githubusercontent.com/6218999/57478812-bf10a500-7250-11e9-92fc-9cdafd6d8aac.png">

@jiaqiluo , How to hide warnings and  gray out? Any steps or documentation available?

**Comment by alasgarov** [comment]
I'm running rancher on a linux host as docker container, latest version image, I'm still facing this issue after importing AKS cluster. Are you using some specific docker image where it was set to be grayed-out or what is your implementation?
