### ISSUE TITLE
Support update prometheus config in enable monitoring page

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17340]
rancher/rancher:master 1/8

After enabled monitoring, user cannot update the options in enable page. Users have to go to the catalog app page to update it.

We should let user to update the config in enable monitoring page.

It came from https://github.com/rancher/rancher/issues/17306#issuecomment-451553868

**Comment by thxCode** [comment]
@loganhz , a dev container for this: `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e "CATTLE_AGENT_IMAGE=maiwj/rancher-agent:2defb1a95" maiwj/rancher:2defb1a95`

- Use `viewMonitoring` action to get the answers from the Monitoring App
- Use `editMonitoring` action to commit the modification of the answers

---

### 1. Cluster Level
#### 1.1 Grafana options
##### 1.1.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| grafana.image.repository | Image repository | `grafana/grafana` |
| grafana.image.tag | Image tag | `5.3.0` |
| grafana.persistence.enabled | Enable PVC | `false` |
| grafana.persistence.size | Size for PV | `50Gi` |
| grafana.persistence.storageClass | StorageClass for PV | `""` |
| grafana.resources.core.requests.memory | RAM-request | `100Mi` |
| grafana.resources.core.requests.cpu | CPU-request | `100m` |
| grafana.resources.core.limits.memory | RAM-limit | `200Mi` |
| grafana.resources.core.limits.cpu | CPU-limit | `100m` |

##### 1.1.2 Proxy
| Answer | Usage | Default |
| --- | --- | --- |
| grafana.image.proxy.repository | Proxy image repository | `nginx` |
| grafana.image.proxy.tag | Proxy image tag | `1.15.8-alpine` |
| grafana.resources.proxy.requests.memory | RAM-request for proxy | `50Mi` |
| grafana.resources.proxy.requests.cpu | CPU-request for proxy | `50m` |
| grafana.resources.proxy.limits.memory | RAM-limit for proxy | `100Mi` |
| grafana.resources.proxy.limits.cpu | CPU-limit for proxy | `100m` |

#### 1.2 Prometheus options
##### 1.2.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.repository | Image repository | `prom/prometheus` |
| prometheus.image.tag | Image tag | `v2.5.0` |
| prometheus.persistence.enabled | Enable PVC | `false` |
| prometheus.persistence.size | Size for PV | `50Gi` |
| prometheus.persistence.storageClass | StorageClass for PV | `""` |
| prometheus.resources.core.requests.memory | RAM-request | `100Mi` |
| prometheus.resources.core.requests.cpu | CPU-request | `100m` |
| prometheus.resources.core.limits.memory | RAM-limit | `500Mi` |
| prometheus.resources.core.limits.cpu | CPU-limit | `1000m` |
| prometheus.retention | How long to retain metrics | `24h` |
| prometheus.replicaCount | Number of replicas desired | `1` |

##### 1.2.2 Proxy
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.proxy.repository | Proxy image repository | `nginx` |
| prometheus.image.proxy.tag | Proxy image tag | `1.15.8-alpine` |
| prometheus.resources.proxy.requests.memory | RAM-request for proxy | `50Mi` |
| prometheus.resources.proxy.requests.cpu | CPU-request for proxy | `50m` |
| prometheus.resources.proxy.limits.memory | RAM-limit for proxy | `100Mi` |
| prometheus.resources.proxy.limits.cpu | CPU-limit for proxy | `100m` |

##### 1.2.3 Auth
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.auth.repository | Auth image repository | `rancher/prometheus-auth` |
| prometheus.image.auth.tag | Auth image tag | `v0.2.0` |
| prometheus.resources.auth.requests.memory | RAM-request for auth | `100Mi` |
| prometheus.resources.auth.requests.cpu | CPU-request for auth | `100m` |
| prometheus.resources.auth.limits.memory | RAM-limit for auth | `200Mi` |
| prometheus.resources.auth.limits.cpu | CPU-limit for auth | `500m` |

#### 1.3 Exporter options
##### 1.3.1 Node exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-node.enabled | Enable node-exporter for host metrics, like `node_*` | `true` |
| exporter-node.image.repository | Image repository | `prom/node-exporter` |
| exporter-node.image.tag | Image tag | `v0.17.0` |
| exporter-node.resources.requests.memory | RAM-request | `30Mi` |
| exporter-node.resources.requests.cpu | CPU-request | `100m` |
| exporter-node.resources.limits.memory | RAM-limit | `50Mi` |
| exporter-node.resources.limits.cpu | CPU-limit | `200m` |
| exporter-node.ports.metrics.port | Listening port | `9100` |
| exporter-node.enabledHostNetwork | Use `hostNetwork` or not | `true`, if `false`, node_exporter cannot collect the real network traffic in host |
| exporter-node.enabledHostPID | Use `hostPID` or not | `true`, if `false`, node_exporter cannot collect the real filesystem situation in host |
| exporter-node.collectors.[xxx] | Adapt [node_exporter#v0.17.0 Linux OS type collector](https://github.com/prometheus/node_exporter#collectors), considering https://github.com/rancher/system-charts/pull/8#issuecomment-458446962 | `{}`, the default settings can review from [here](https://github.com/rancher/system-charts/blob/69520015a0f1f34576523790ad52ec2392255a3d/charts/rancher-monitoring/v0.0.2/charts/exporter-node/values.yaml#L56-L197) |

##### 1.3.2 Kubelet exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-kubelets.enabled | Enable scraping kubelets for container metrics, like `container_*` | `true` |
| exporter-kubelets.https | Should be `false` when deploying in GKE, relating https://github.com/rancher/rancher/issues/17745 | `true` |

##### 1.3.3 Kube-state exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-kube-state.enabled | Enable kube-state-exporter for Kubernetes Resources metrics, like `kube_*`| `true` |
| exporter-kube-state.image.repository | Image repository | `quay.io/coreos/kube-state-metrics` |
| exporter-kube-state.image.tag | Image tag | `v1.4.0` |
| exporter-kube-state.resources.requests.memory | RAM-request | `130Mi` |
| exporter-kube-state.resources.requests.cpu | CPU-request | `100m` |
| exporter-kube-state.resources.limits.memory | RAM-limit | `200Mi` |
| exporter-kube-state.resources.limits.cpu | CPU-limit | `100m` |

##### 1.3.4 Kubernetes exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-kubernetes.enabled | Enable scraping `kubernetes.default.svc` for Kubernetes APIServer metrics, like `apiserver_*`| `true` |

##### 1.3.5 Fluentd exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-fluentd.enabled | Enable scraping fluentd metrics, when using Rancher Logging | `true` |

---

### 2. Project Level
#### 2.1 Grafana options
##### 2.1.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| grafana.image.repository | Image repository | `grafana/grafana` |
| grafana.image.tag | Image tag | `5.3.0` |
| grafana.persistence.enabled | Enable PVC | `false` |
| grafana.persistence.size | Size for PV | `50Gi` |
| grafana.persistence.storageClass | StorageClass for PV | `""` |
| grafana.resources.core.requests.memory | RAM-request | `100Mi` |
| grafana.resources.core.requests.cpu | CPU-request | `100m` |
| grafana.resources.core.limits.memory | RAM-limit | `200Mi` |
| grafana.resources.core.limits.cpu | CPU-limit | `100m` |

##### 2.1.2 Proxy
| Answer | Usage | Default |
| --- | --- | --- |
| grafana.image.proxy.repository | Proxy image repository | `nginx` |
| grafana.image.proxy.tag | Proxy image tag | `1.15.8-alpine` |
| grafana.resources.proxy.requests.memory | RAM-request for proxy | `50Mi` |
| grafana.resources.proxy.requests.cpu | CPU-request for proxy | `50m` |
| grafana.resources.proxy.limits.memory | RAM-limit for proxy | `100Mi` |
| grafana.resources.proxy.limits.cpu | CPU-limit for proxy | `100m` |

#### 2.2 Prometheus options
##### 2.2.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.repository | Image repository | `prom/prometheus` |
| prometheus.image.tag | Image tag | `v2.5.0` |
| prometheus.persistence.enabled | Enable PVC | `false` |
| prometheus.persistence.size | Size for PV | `50Gi` |
| prometheus.persistence.storageClass | StorageClass for PV | `""` |
| prometheus.resources.core.requests.memory | RAM-request | `100Mi` |
| prometheus.resources.core.requests.cpu | CPU-request | `100m` |
| prometheus.resources.core.limits.memory | RAM-limit | `500Mi` |
| prometheus.resources.core.limits.cpu | CPU-limit | `1000m` |
| prometheus.retention | How long to retain metrics | `24h` |
| prometheus.replicaCount | Number of replicas desired | `1` |

##### 2.2.2 Proxy
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.proxy.repository | Proxy image repository | `nginx` |
| prometheus.image.proxy.tag | Proxy image tag | `1.15.8-alpine` |
| prometheus.resources.proxy.requests.memory | RAM-request for proxy | `50Mi` |
| prometheus.resources.proxy.requests.cpu | CPU-request for proxy | `50m` |
| prometheus.resources.proxy.limits.memory | RAM-limit for proxy | `100Mi` |
| prometheus.resources.proxy.limits.cpu | CPU-limit for proxy | `100m` |

**Comment by loganhz** [comment]
- Use `viewMonitoring` action to get the answers from the Monitoring App
- Use `editMonitoring` action to commit the modification of the answers

---

### 1. Cluster Level
#### 1.1 Grafana options
##### 1.1.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| grafana.image.repository | Image repository | `grafana/grafana` |
| grafana.image.tag | Image tag | `5.3.0` |
| grafana.persistence.enabled | Enable PVC | `false` |
| grafana.persistence.size | Size for PV | `50Gi` |
| grafana.persistence.storageClass | StorageClass for PV | `""` |
| grafana.resources.core.requests.memory | RAM-request | `100Mi` |
| grafana.resources.core.requests.cpu | CPU-request | `100m` |
| grafana.resources.core.limits.memory | RAM-limit | `200Mi` |
| grafana.resources.core.limits.cpu | CPU-limit | `100m` |

##### 1.1.2 Proxy
| Answer | Usage | Default |
| --- | --- | --- |
| grafana.image.proxy.repository | Proxy image repository | `nginx` |
| grafana.image.proxy.tag | Proxy image tag | `1.15.8-alpine` |
| grafana.resources.proxy.requests.memory | RAM-request for proxy | `50Mi` |
| grafana.resources.proxy.requests.cpu | CPU-request for proxy | `50m` |
| grafana.resources.proxy.limits.memory | RAM-limit for proxy | `100Mi` |
| grafana.resources.proxy.limits.cpu | CPU-limit for proxy | `100m` |

#### 1.2 Prometheus options
##### 1.2.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.repository | Image repository | `prom/prometheus` |
| prometheus.image.tag | Image tag | `v2.5.0` |
| prometheus.persistence.enabled | Enable PVC | `false` |
| prometheus.persistence.size | Size for PV | `50Gi` |
| prometheus.persistence.storageClass | StorageClass for PV | `""` |
| prometheus.resources.core.requests.memory | RAM-request | `100Mi` |
| prometheus.resources.core.requests.cpu | CPU-request | `100m` |
| prometheus.resources.core.limits.memory | RAM-limit | `500Mi` |
| prometheus.resources.core.limits.cpu | CPU-limit | `1000m` |
| prometheus.retention | How long to retain metrics | `24h` |
| prometheus.replicaCount | Number of replicas desired | `1` |

##### 1.2.2 Proxy
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.proxy.repository | Proxy image repository | `nginx` |
| prometheus.image.proxy.tag | Proxy image tag | `1.15.8-alpine` |
| prometheus.resources.proxy.requests.memory | RAM-request for proxy | `50Mi` |
| prometheus.resources.proxy.requests.cpu | CPU-request for proxy | `50m` |
| prometheus.resources.proxy.limits.memory | RAM-limit for proxy | `100Mi` |
| prometheus.resources.proxy.limits.cpu | CPU-limit for proxy | `100m` |

##### 1.2.3 Auth
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.auth.repository | Auth image repository | `rancher/prometheus-auth` |
| prometheus.image.auth.tag | Auth image tag | `v0.2.0` |
| prometheus.resources.auth.requests.memory | RAM-request for auth | `100Mi` |
| prometheus.resources.auth.requests.cpu | CPU-request for auth | `100m` |
| prometheus.resources.auth.limits.memory | RAM-limit for auth | `200Mi` |
| prometheus.resources.auth.limits.cpu | CPU-limit for auth | `500m` |

#### 1.3 Exporter options
##### 1.3.1 Node exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-node.enabled | Enable node-exporter for host metrics, like `node_*` | `true` |
| exporter-node.image.repository | Image repository | `prom/node-exporter` |
| exporter-node.image.tag | Image tag | `v0.17.0` |
| exporter-node.resources.requests.memory | RAM-request | `30Mi` |
| exporter-node.resources.requests.cpu | CPU-request | `100m` |
| exporter-node.resources.limits.memory | RAM-limit | `50Mi` |
| exporter-node.resources.limits.cpu | CPU-limit | `200m` |
| exporter-node.ports.metrics.port | Listening port | `9100` |
| exporter-node.enabledHostNetwork | Use `hostNetwork` or not | `true`, if `false`, node_exporter cannot collect the real network traffic in host |
| exporter-node.enabledHostPID | Use `hostPID` or not | `true`, if `false`, node_exporter cannot collect the real filesystem situation in host |
| exporter-node.collectors.[xxx] | Adapt [node_exporter#v0.17.0 Linux OS type collector](https://github.com/prometheus/node_exporter#collectors), considering https://github.com/rancher/system-charts/pull/8#issuecomment-458446962 | `{}`, the default settings can review from [here](https://github.com/rancher/system-charts/blob/69520015a0f1f34576523790ad52ec2392255a3d/charts/rancher-monitoring/v0.0.2/charts/exporter-node/values.yaml#L56-L197) |

##### 1.3.2 Kubelet exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-kubelets.enabled | Enable scraping kubelets for container metrics, like `container_*` | `true` |
| exporter-kubelets.https | Should be `false` when deploying in GKE, relating https://github.com/rancher/rancher/issues/17745 | `true` |

##### 1.3.3 Kube-state exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-kube-state.enabled | Enable kube-state-exporter for Kubernetes Resources metrics, like `kube_*`| `true` |
| exporter-kube-state.image.repository | Image repository | `quay.io/coreos/kube-state-metrics` |
| exporter-kube-state.image.tag | Image tag | `v1.4.0` |
| exporter-kube-state.resources.requests.memory | RAM-request | `130Mi` |
| exporter-kube-state.resources.requests.cpu | CPU-request | `100m` |
| exporter-kube-state.resources.limits.memory | RAM-limit | `200Mi` |
| exporter-kube-state.resources.limits.cpu | CPU-limit | `100m` |

##### 1.3.4 Kubernetes exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-kubernetes.enabled | Enable scraping `kubernetes.default.svc` for Kubernetes APIServer metrics, like `apiserver_*`| `true` |

##### 1.3.5 Fluentd exporter
| Answer | Usage | Default |
| --- | --- | --- |
| exporter-fluentd.enabled | Enable scraping fluentd metrics, when using Rancher Logging | `true` |

---

### 2. Project Level
#### 2.1 Grafana options
##### 2.1.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| grafana.image.repository | Image repository | `grafana/grafana` |
| grafana.image.tag | Image tag | `5.3.0` |
| grafana.persistence.enabled | Enable PVC | `false` |
| grafana.persistence.size | Size for PV | `50Gi` |
| grafana.persistence.storageClass | StorageClass for PV | `""` |
| grafana.resources.core.requests.memory | RAM-request | `100Mi` |
| grafana.resources.core.requests.cpu | CPU-request | `100m` |
| grafana.resources.core.limits.memory | RAM-limit | `200Mi` |
| grafana.resources.core.limits.cpu | CPU-limit | `100m` |

##### 2.1.2 Proxy
| Answer | Usage | Default |
| --- | --- | --- |
| grafana.image.proxy.repository | Proxy image repository | `nginx` |
| grafana.image.proxy.tag | Proxy image tag | `1.15.8-alpine` |
| grafana.resources.proxy.requests.memory | RAM-request for proxy | `50Mi` |
| grafana.resources.proxy.requests.cpu | CPU-request for proxy | `50m` |
| grafana.resources.proxy.limits.memory | RAM-limit for proxy | `100Mi` |
| grafana.resources.proxy.limits.cpu | CPU-limit for proxy | `100m` |

#### 2.2 Prometheus options
##### 2.2.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.repository | Image repository | `prom/prometheus` |
| prometheus.image.tag | Image tag | `v2.5.0` |
| prometheus.persistence.enabled | Enable PVC | `false` |
| prometheus.persistence.size | Size for PV | `50Gi` |
| prometheus.persistence.storageClass | StorageClass for PV | `""` |
| prometheus.resources.core.requests.memory | RAM-request | `100Mi` |
| prometheus.resources.core.requests.cpu | CPU-request | `100m` |
| prometheus.resources.core.limits.memory | RAM-limit | `500Mi` |
| prometheus.resources.core.limits.cpu | CPU-limit | `1000m` |
| prometheus.retention | How long to retain metrics | `24h` |
| prometheus.replicaCount | Number of replicas desired | `1` |

##### 2.2.2 Proxy
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.image.proxy.repository | Proxy image repository | `nginx` |
| prometheus.image.proxy.tag | Proxy image tag | `1.15.8-alpine` |
| prometheus.resources.proxy.requests.memory | RAM-request for proxy | `50Mi` |
| prometheus.resources.proxy.requests.cpu | CPU-request for proxy | `50m` |
| prometheus.resources.proxy.limits.memory | RAM-limit for proxy | `100Mi` |
| prometheus.resources.proxy.limits.cpu | CPU-limit for proxy | `100m` |

**Comment by cjellick** [comment]
Backend is in, but UI not yet merged. If you want to test via UI, you have to wait for this issue to go to-test
https://github.com/rancher/ui/pull/2649

**Comment by westlywright** [comment]
UI is merged

**Comment by jiaqiluo** [comment]
The feature is tested on Rancher: master 2/15.  
The tests cover both cluster-level and project-level monitoring, and all options in the monitoring setting page.
