### ISSUE TITLE
The ingress is Initializing for long time when i add the new ingress rule

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#17356]
![image](https://user-images.githubusercontent.com/14210543/50891067-77127a80-1436-11e9-8a0c-491d5b12d02f.png)
rancher server log:
![image](https://user-images.githubusercontent.com/14210543/50891176-af19bd80-1436-11e9-982d-6d520b08f0f0.png)

![image](https://user-images.githubusercontent.com/14210543/50891550-7f1eea00-1437-11e9-9533-104d8e83c77b.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |
|Route|`ingresses.index`|

**Comment by kangjianhua** [comment]
How they solve ？

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
