### ISSUE TITLE
pipeline: The difference between the request time and the server's time is too large.

### ISSUE THREAD

**Issue by bdue** [rancher/rancher#17354]
**What kind of request is this (question/bug/enhancement/feature request):**
Issue when running new or existing pipelines

**Steps to reproduce (least amount of steps as possible):**
Any pipline, new or existing in different namespaces/projects are all exhibiting exact the same issue.
Create a pipeline
Run it/triger it
**Result:**
I see the message when executing the pipeline, after 5/6 seconds the red error-message appears in the browser.
The state of the pipline run then changes to failed. And the slaves from jenkins are terminated.

**Other details that may be helpful:**
Checked time/timezones on cluster. Also tried solution from: https://github.com/rancher/rancher/issues/16293

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher 2.1.5  HA install

**Cluster information**
- Cluster type (Custom):
- Machine type: Cloud, 3 nodes total 16 cores 32gib ram.
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Docker (use `docker info`):

1.13.1

**Comment by gitlawr** [comment]
This message is one of the s3 error responses. Can you check the time in Minio container?

**Comment by bdue** [comment]
I have managed to solve this issue. 2 nodes of the HA management cluster had a issue with their time. Corrected the time on those 2 nodes and the pipelines started running again.
Why the time on 2 nodes from the management cluster caused an issue with the pipelines on another cluster beats me.

**Comment by sinkcoder** [comment]
@bdue Hey!Could you tell me how you solve this issue in detail?I see the same message when running pipelines, but I don't konw the server's time and which timezone should I set.Thank you.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
