### ISSUE TITLE
Alert Group - Slider sync sliding of multiple Alert Rules

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#17353]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Add an alert group and add multiple alert rules
2. Select workload
3. Drag the slider

**Result:**

Slider slides synchronously

<img width="1279" alt="slider" src="https://user-images.githubusercontent.com/42061003/50875326-d22a7a00-1402-11e9-8ba4-b09995d47260.png">

**Comment by davidnuzik** [comment]
Re-opening the issue. The issue is still occurring for me on latest master 1/15. Please let me know if there is anything I can do to assist / provide environment, etc.

**Comment by rootwuj** [comment]
Version -2.2 master 01/23
Verified fixed
