### ISSUE TITLE
2.x rancher api doc for websocket

### ISSUE THREAD

**Issue by zengcul** [rancher/rancher#17352]
2.x rancher api doc for websocket

**Comment by loganhz** [comment]
Yes, it supports websocket. We don't have the API doc yet. If you want to find out how to use shell and log via websocket.

Please check the following code or look at the kubernetes API doc directly. We are using native k8s API for shell and log.

https://github.com/rancher/ui/blob/master/app/components/container-logs/component.js#L151
https://github.com/rancher/ui/blob/master/lib/shared/addon/components/container-shell/component.js#L100

**Comment by zengcul** [comment]
the other api like /v3/project/clusterid:xxxx/workflows/  can not support websocket,  so I must use interval in js to get the latest workflows status ?

**Comment by loganhz** [comment]
It supports resource status update via ws.

There are 3 kinds of ws for resource update

`/v3/subscribe` for global level menu such as users list and clusters list

`/v3/clusters/${cluster-id}/subscribe` for cluster level menu such as nodes list, members and projects.

`/v3/projects/${project-id}/subscribe` for project level menu such as workload list and catalog app.

**Comment by zengcul** [comment]
so kind of you 呜呜呜 .   

should I use access_key and access_secret in HTTP header, like Authorization: Bearer <token_string> ?  It is hard to find use doc .   wuwuwu

**Comment by loganhz** [comment]
You can use cookie header or add Auth header in a proxy such as nginx.
https://github.com/loganhz/tianhe/blob/master/index.html#L9
