### ISSUE TITLE
Adding rancher/agent to a rancher 1.6 via docker-compose

### ISSUE THREAD

**Issue by uvwild** [rancher/rancher#17361]
We need to start the rancher-agent together with the rancher/server from a docker-compose file.
Please dont refer to rancher2 as it has a different feature set. 

This has been asked in #9063 before, but answered with a link to a dead page!

So I am trying to figure out which info is needed in the docker-compose.yml, 
but since I couldnt find any documentation (nor the repository to look at the sources from the label on the agent rancher/agent:v1.2.11) I am giving up now.

- copying the docker inspect info in the docker-compose.yml is not doing the right thing. 
- adding the reponse from the rancher URL into the environment of the agent is not suficient
- the entrypoint cmd functionality is not intuitive and I cannot find the repo for the agent
- there is some magic happening which is not obvious.

A few clarifying words or just links from an insider seem necesary. It cannot be so hard after all!
please help!

**Comment by uvwild** [comment]
One major obstacle also with the agent is the **issue with the loopback dnsmasq** which is the default on ubuntu18.04 distros and causes the agent to not startup.

Is there a neat workaround better than me editing resolv.conf everytime before I start the agent?

Changing the dnsmasq config seems a bit cumbersome. 

https://stackoverflow.com/questions/35693117/how-can-i-give-docker-containers-access-to-a-dnsmasq-local-dns-resolver-on-the-h

**Comment by superseb** [comment]
The docs page was moved, the new URL is https://rancher.com/docs/os/v1.x/en/about/running-rancher-on-rancheros/.

The docs for running a local DNS server are at https://rancher.com/docs/rancher/v1.6/en/hosts/#hosts-running-a-local-caching-nameserver.

Let me know if those don't solve the issue

**Comment by vincent99** [comment]
The docs page is literally the first search result for `rancher-agent`, rancher/agent`, `rancher agent`, or similar.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/753917/50921960-7f52c180-1406-11e9-984a-ae8690e73fc8.png">

The agent is GitHub rancher/agent.  1.6 is a branch.  https://github.com/rancher/agent/tree/v1.6

**Comment by uvwild** [comment]
rancher-agent start in docker-compose with rancher

**Comment by uvwild** [comment]
@vincent99  Thanks for this very useful feedback!
That simplification of the query would lead me to the right page didnt cross my mind. 
My search was "rancher-agent start in docker-compose with rancher"
Good Point. 
However, with more common search terms this approach is not working. 
But I will integrate that in my problem solving process. 
trying query simplification also in the future.
:)

**Comment by uvwild** [comment]
@superseb thanks for this quick feedback :) 
I had figured most of the dns, just how to stop the resolver from overwriting the entries I was missing.
Main mistake I installed the **resolvconf** service which overwrites the resolv.conf all the time.
