### ISSUE TITLE
Add support for EKS in ap-northeast-2

### ISSUE THREAD

**Issue by dele5247** [rancher/rancher#17369]
Amazon have recently announced support for ap-northeast-2(seoul) within the EKS product
We need to add support for this region to the list of EKS options available

**Comment by loganhz** [comment]
Related doc https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17081
