### ISSUE TITLE
Add P3 AWS Instance Types 

### ISSUE THREAD

**Issue by mak3r** [rancher/rancher#17377]
**Feature Request**
Add P3 instance types in the drop-down for AWS hosts. 

**Result:**
P3 Instances are available when using AWS node templates

**Environment information**
Rancher version: 2.1.5

**Comment by cjellick** [comment]
note p3s are gpu instances. i think they take special consideration when testing. Talk to @nathan-jenan-rancher about it

**Comment by loganhz** [comment]
https://aws.amazon.com/ec2/instance-types/p3/

Add the following aws instance types in aws node driver

p3.2xlarge
p3.8xlarge
p3.16xlarge
p3dn.24xlarge

**Comment by davidnuzik** [comment]
@nathan-jenan-rancher could we briefly touch base before I begin testing? Craig mentioned special requirements for testing. I was thinking I should just briefly test with p3.2xlarge as this is the smallest option just so I can see http req/resp and API for UI testing.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/30/19)
Confirmed enhancement. I validated the node template form and http/api. And I also tried creating a cluster with just p3.2xlarge instanceType but we are not authorized for these machines. From UI/http/api perspective everything appears correct however.
