### ISSUE TITLE
Rancher Agent stuck on "INFO: Deleting container rancher-agent"

### ISSUE THREAD

**Issue by burhan** [rancher/rancher#1737]
I am facing a strange problem while trying to get a RHEL Atomic Host to be detected by the interface. After copy-pasting the agent installer docker command, the agent never finishes and the host is not detected; here is the log:

```
INFO: Running Agent Registration Process, CATTLE_URL=http://172.xx.x.xxx:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.6.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.6.2
INFO: docker version: Server API version: 1.18
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): ba1f6c3/1.6.2
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 11
INFO: docker info: Images: 29
INFO: docker info: Storage Driver: devicemapper
INFO: docker info: Pool Name: rah_tweb1-docker--pool
INFO: docker info: Pool Blocksize: 65.54 kB
INFO: docker info: Backing Filesystem: xfs
INFO: docker info: Data file:
INFO: docker info: Metadata file:
INFO: docker info: Data Space Used: 1.076 GB
INFO: docker info: Data Space Total: 37.15 GB
INFO: docker info: Data Space Available: 36.08 GB
INFO: docker info: Metadata Space Used: 2.9 MB
INFO: docker info: Metadata Space Total: 46.14 MB
INFO: docker info: Metadata Space Available: 43.24 MB
INFO: docker info: Udev Sync Supported: true
INFO: docker info: Library Version: 1.02.93-RHEL7 (2015-01-28)
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.10.0-229.7.2.el7.x86_64
INFO: docker info: Operating System: Red Hat Enterprise Linux
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 1.791 GiB
INFO: docker info: Name: tweb1.example.com
INFO: docker info: ID: VOUD:2MGF:PDN5:N3O4:PCGH:XGFP:DKAB:GZH6:Y3JS:YKBM:5YSK:DLDL
INFO: Attempting to connect to: http://172.xx.xx.xxx:8080/v1
INFO: http://172.xx.xx.xxx:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: true
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=73B871E16E7D0EA68252
INFO: ENV: CATTLE_AGENT_IP=172.xx.x.xx
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SYSTEMD=true
INFO: ENV: CATTLE_URL=http://172.xx.x.xxx:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=172.xx.x.xx
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v0.7.9
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
```

After this point, the last line keeps repeating; as if in an infinite loop.

**Comment by ibuildthecloud** [comment]
I know this sounds like a silly question, but what happens if you do `docker rm -fv rancher-agent`?

**Comment by burhan** [comment]
Well obviously I get this:

    Error response from daemon: no such id: rancher-agent

As there is no such `rancher-agent` container running.

**Comment by deniseschannon** [comment]
@burhan I know it's been awhile, but have you been able to get a RHEL Atomic Host to be added into Rancher. Are you still facing the same issues? If not, I'll be closing this.

**Comment by mishak87** [comment]
I am encountering same issue with Debian Jessie on OVH VPS.

**Comment by manthis** [comment]
I'm presently encountering the same issue with my container. Any solution?

**Comment by deniseschannon** [comment]
@manthis Can you provide more details on your OS type and Rancher setup?

**Comment by courcelm** [comment]
Similar problem here but no infinite loop

I started the agent the following way:

sudo docker run --name=rancher-agent --add-host=X.X.ca:172.17.0.2  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.1 http://X.X:8080/v1/scripts/8DA3971F45AE0BB324DD:1464354000000:UCw3cFPQmcYFvhDHSyzQ

Here is the log:

INFO: Running Agent Registration Process, CATTLE_URL=http://X.X.ca:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.11.1
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.11.1
INFO: docker version: Server API version: 1.23
INFO: docker version: Go version (server): go1.5.4
INFO: docker version: Git commit (server): 5604cbe
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 19
INFO: docker info: Images: 181
INFO: docker info: Storage Driver: devicemapper
INFO: docker info: Pool Name: docker-8:2-5636491-pool
INFO: docker info: Pool Blocksize: 65.54 kB
INFO: docker info: Base Device Size: 107.4 GB
INFO: docker info: Backing Filesystem: xfs
INFO: docker info: Data file: /dev/loop0
INFO: docker info: Metadata file: /dev/loop1
INFO: docker info: Data Space Used: 10.94 GB
INFO: docker info: Data Space Total: 107.4 GB
INFO: docker info: Data Space Available: 96.44 GB
INFO: docker info: Metadata Space Used: 16.26 MB
INFO: docker info: Metadata Space Total: 2.147 GB
INFO: docker info: Metadata Space Available: 2.131 GB
INFO: docker info: Udev Sync Supported: true
INFO: docker info: Deferred Removal Enabled: false
INFO: docker info: Deferred Deletion Enabled: false
INFO: docker info: Deferred Deleted Device Count: 0
INFO: docker info: Data loop file: /var/lib/docker/devicemapper/devicemapper/data
INFO: docker info: Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
INFO: docker info: Library Version: 1.02.107-RHEL7 (2015-12-01)
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 3.10.0-229.20.1.el7.x86_64
INFO: docker info: Operating System: CentOS Linux 7 (Core)
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 11.57 GiB
INFO: docker info: Name: capamhc
INFO: docker info: ID: TILT:YU5G:COCP:WKQJ:UR2V:EIGG:YTBH:FHYJ:MIQW:NIST:QSEH:G3OI
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://X.X.ca:8080/v1
INFO: http://capamhc.iric.ca:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: true
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=03A64976D87FBFDD8D12
INFO: ENV: CATTLE_AGENT_IP=172.17.0.3
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SYSTEMD=true
INFO: ENV: CATTLE_URL=http://X.X.ca:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=172.17.0.3
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.0.1
INFO: Deleting container rancher-agent

**Comment by deniseschannon** [comment]
Can you explain why you added this part into the command? `--add-host=X.X.ca:172.17.0.2 `

**Comment by courcelm** [comment]
This rancher-agent is on the same node as the server. The computer is in a private network in 10.0.0.X. It can be reached with a public host name and ip    X.X.ca:132.X.X.X

I added this --add-host=X.X.ca:172.17.0.2 because the firewall/routing at my institution is doesn`t allow me to loop back using my public IP.
With this host entry the rancher-agent can reach the rancher-server.

Other rancher-agents on the public network can connect without an issue to the rancher-server.

Mathieu Courcelles, Ph.D. Bio-informatique
Associé de recherche, Centre d’analyse protéomique avancée
IRIC - Institut de recherche en immunologie et cancérologie
Université de Montréal

**Comment by nayyden** [comment]
I got the same issue and managed to solve it. Do not add --name rancher-agent, this command creates a container named rancher-agent and exits. When you set the name it removes itself :)

**Comment by deniseschannon** [comment]
@courcelm I didn't catch the `--name rancher-agent` in your command.

http://docs.rancher.com/rancher/latest/en/faqs/agents/#what-are-reasons-why-rancher-agent-would-fail-to-start

**Comment by courcelm** [comment]
Yup removing --name rancher-agent  avoid INFO: Deleting container rancher-agent.

However my --add-host  seems not to be propagated to all the containers rancher-agent start which create other issues.

I decided to use another host to avoid these issues.

Thanks for your help!
