### ISSUE TITLE
Center SoftLayer node driver image

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17378]
Version: master 2.2 (1/10/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, minor

**Steps to reproduce (least amount of steps as possible):**
- Enable the SoftLayer node driver

**Result:**
Notice the SoftLayer node driver icon is very high up and is not centered. Compared to the others it looks like it is up too high:
![image](https://user-images.githubusercontent.com/45179589/50991054-02d8e500-14d1-11e9-9b99-eeb43ae180bf.png)

**Comment by westlywright** [comment]
Had to roll back some changes on master this will be on hold until we can merge again.
