### ISSUE TITLE
Alert and Notifier flow not posting Alerting messages to Slack

### ISSUE THREAD

**Issue by sdanieru** [rancher/rancher#17383]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1. rancher 2.1.5 single install
2. Create a cluster
3. Setup a notifier that posts alert messages to a slack channel; click 'Test' to verify it posts to the specified channel.
4. Set the out-of-box 'Alert for etcd' to use the slack notifier setup in step 3
5. Make etcd unhealthy (docker stop etcd on one of the management nodes worked for me).

**Result:**
The etcd alert goes from a state of 'Active' to 'Alerting', yet even after the default 3 minute delay, no alert is ever sent to slack. I've gone into advanced settings and changed the delay to 0, re-cycled states (back to Active and healthy, then to Alerting again) yet nothing is ever posted to slack. This is particularly surprising since clicking 'Test' when editing the Notifier posts to slack just fine.

It would be nice if there were a 'Test' button in the alert as well, to verify that it's properly passing on the alert to the selected Notifier.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.5
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): test cluster running inside of VirtualBox VMs (1core/1GB)
- Kubernetes version (use `kubectl version`): 1.11.6

- Docker (use `docker info`):

```
$ docker info
Containers: 22
 Running: 12
 Paused: 0
 Stopped: 10
Images: 8
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-141-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.1MiB
Name: mgmt1
ID: WC5Y:2ZL2:AD3R:26GR:TAIX:2K4J:OQI2:BEK7:ET47:7FDL:FPML:LPJW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by sdanieru** [comment]
I think this might not be specific to a Slack notifier; seems more like a problem between the Alert and the  Notifier. How well baked is the Alert/Notifier flow in Rancher? This is my first time trying to use it for alerting on a cluster and I can't seem to get any alerts to propagate from an Alert all the way to a Slack channel. Others having better luck than me?

**Comment by aiwantaozi** [comment]
@sdanieru how many etcd node for the cluster, if there are many etcd, and one node is broken, but others still available,  like kubectl get clustercomponent, the etcd status will not be failed.

**Comment by sdanieru** [comment]
hi @aiwantaozi that's an interesting point: there is a difference between the service not functioning, vs one of the members of the quorum being down. Good to know the alerts are only looking at the service's ability to function, rather than if an individual member has failed.
In my test env, I was using 3 etcd nodes, and in the 'Alerts' list, the test had changed to 'Alerting' status with only one of the etcd members down, but no alert was sent to the notifier.
From what you've said, the Alert should have never gone to 'Alerting' status, but since it had, I would have assumed it should have told the Notifier.
Can I expand on your comment to assume that all system alerts are considered 'healthy' as long as the service is doing it's job?

**Comment by aiwantaozi** [comment]
Hi @sdanieru could you share some screenshot for alert/notifier configure and logs from rancher and alertmanager?

**Comment by sdanieru** [comment]
sure. here's my test setup for context: cluster is running 3 etcd members. When I bring one of the members down, I'm notified on the cluster dashboard "Alert: Component etcd-0 is unhealthy". The alerts page shows the Alert is in 'Alerting' state (see image) but the notifier never posts to the slack channel. the config for the 'etcd test' alert is, pretty much setup like the default (see image)
![alertpage](https://user-images.githubusercontent.com/18471926/51192822-a432b300-18a4-11e9-8310-a2572d11f7e5.png)
![alertconfig](https://user-images.githubusercontent.com/18471926/51192835-ab59c100-18a4-11e9-8a2c-40fdf501031d.png)
[rancher.log](https://github.com/rancher/rancher/files/2760451/rancher.log)
Where can I pickup the alertmanager log?

**Comment by aiwantaozi** [comment]
@sdanieru you could see under system project/workload alertmanager

**Comment by sdanieru** [comment]
so, I've also been playing around with alerts and notifiers for workloads: I setup a workload alert that should trigger if the workload drops below 100%; I then crippled the workload with taints so it can't run any pods anywhere - and the alert never triggers. Either I'm missing something here, or the Alert/Notification system in Rancher doesn't seem to be functioning properly. Is anyone successfully using Alerts/Notifications in Rancher? I'm really hoping it's just me since this would be great to leverage if I can get it working right!

**Comment by aiwantaozi** [comment]
Hi @sdanieru this feature was tested, first it will detect whether the configured alerts happened, change the status to alerting, you could see in the UI; then call the Alertmanager API, Alertmanager was deployed in the cluster; third, Alertmanager will send out the alert to notifiers. So in your cluster, the second or third steps may have problems. I see in the rancher log, the server sometimes could not connect to the agent. You could open debug log to see if there are any send alert failed log cause by connection ```curl --unix-socket /tmp/log.sock -X POST -d "level=debug" localhost:8080/v1/loglevel``` You also could check the Alertmanager workload log if it could receive API request and success send out.

**Comment by sdanieru** [comment]
Thanks for the troubleshooting suggestions. I found the problem: my taint/toleration strategy was preventing the AlertManager from having any nodes to deploy on. For now I'm using NodeSelector instead but using taints would be preferable, but most importantly alerts seem to be working fine now!
Is there a good way to add a toleration to the AlertManager deployment?

**Comment by aiwantaozi** [comment]
Usually, Alertmanager deploys to the worker node, you could schedule base on your resource.

**Comment by angeloudy** [comment]
I am still having this issue. It can trigger the alerts, but sometime cannot post messages to slack.
The problem is that sometimes it works sometimes not.
If I click on the TEST button, it sends `Slack setting validated` successfully every time.
