### ISSUE TITLE
User with config map view access can view secrets

### ISSUE THREAD

**Issue by kevinsimons-wf** [rancher/rancher#17380]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Restrict a users permissions so they cannot view secrets
2. Deploy an app that contains a secret
3. Go into Resources > Config maps and find the app.v1 config map for the app you deployed
4. Run `kubectl get cm app.v1 -o jsonpath='{.data.release}' | base64 --decode | gunzip`
5. Verify you can see secrets

**Result:**
A user can view secrets if they have config map view permissions

**Other details that may be helpful:**
It looks like tiller can be encrypted by default in which case I believe those deployment info config maps would be secrets instead https://docs.helm.sh/using_helm/#best-practices-for-securing-helm-and-tiller

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.1
- Installation option (single install/HA): HA

**Comment by ankur111** [comment]
https://github.com/rancher/rancher/issues/17164
