### ISSUE TITLE
UI: Implement default cpu/memory limit for workloads in a namespace

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17387]
UI field will be needed once addressed on the API side https://github.com/rancher/rancher/issues/15648

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/ui/pull/2638

Now users can config the default limit for a namespace

**Comment by davidnuzik** [comment]
Testing this depends on #16753

**Comment by davidnuzik** [comment]
Testing was completed in #16753 which should cover everything here. Refer to that issue for details.
