### ISSUE TITLE
Support Prometheus Federation

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17390]
We should support Prometheus Federation for project level Prometheus.

If we turn it on, project level Prometheus will persist the data from cluster level Prometheus.

**Comment by cjellick** [comment]
You agree we can move this out, right @loganhz ?

**Comment by loganhz** [comment]
yes

**Comment by thxCode** [comment]
@loganhz , add a new project-level parameter when enabling project Monitoring:

### 1. Project Level
#### 1.1 Prometheus options
##### 1.1.1 Core
| Answer | Usage | Default |
| --- | --- | --- |
| prometheus.sync.mode | Project -> Cluster sync mode | - [`remote`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cremote_read%3E): project-level can share the same date with cluster-level without storing; <br/> -  [`federate`](https://prometheus.io/docs/prometheus/latest/federation/): project-level can restore the namespace-related data itselft from cluster-level. <br/><br/> _`remote` will block the metrics query for project-level if cluster-level is disabling, but `federate` is fine._|

**Comment by loganhz** [comment]
We need to move this into 2.2 as it is a must for https://github.com/rancher/rancher/pull/18116

**Comment by loganhz** [comment]
@aiwantaozi Please validate now if the project level prom can persist the cpu/memory data which come from cluster level

**Comment by aiwantaozi** [comment]
Verified

**Comment by aiwantaozi** [comment]
Verify step:
First enable cluster then project
1. enable cluster monitoring
2. check metric for cluster/node/workload/pod/container
3. enable project monitoring
4. config custom metric
5. go to project prometheus, check custom metric
6. search container metric (which data is sync from cluster prometheues), container_cpu_cfs_periods_total
7. disable cluster monitoring, check project prometheus, make sure custom metric could still searchable, and could see the history data for container_cpu_cfs_periods_total
8. disable cluster and project monitoring, cluster prometheus, operator, grafana workload under system project is deleted, project prometheus, grafana under default is deleted.

Enable only project monitoring
1. enable project monitoring
2. set up custom metric
3. search custom metric in project prometheus

First enable project then cluster
base on above step
4. enable cluster monitoring
5. go to project prometheus search container metric container_cpu_cfs_periods_total which data should be sync from cluster
6. close cluster/project monitoring

**Comment by cjellick** [comment]
This is part of a big feature and it should have been validated by QA. Assigning back to QA

**Comment by jiaqiluo** [comment]
The enhancement is validated on master 2/28

Test scenarios:

case   1: enable cluster then project
--
- enable cluster monitoring 
- check metric for cluster/node/workload/pod/container
- enable project monitoring 
- config custom metric
- go to project prometheus, check custom metric 
- search container metric (which data is sync from cluster prometheues), container_cpu_cfs_periods_total
- disable cluster monitoring, check project prometheus, make sure custom   metric could still searchable, and could see the history data for   container_cpu_cfs_periods_total 
- disable cluster and project monitoring, cluster prometheus, operator,   grafana workload under system project is deleted, project prometheus, grafana   under default is deleted.


case   2: enable project then cluster
--
- enable project monitoring
- set up custom metric
- search custom metric in project prometheus 
- enable cluster montoring  
-  search container_cpu_cfs_periods_total from project prometheus



case   3: Enable only project monitoring
--
-  enable project monitoring  
-  set up custom metric     
- search custom metric in project prometheus     
- search cpu_cfs_periods_total should not be able to find it


case   4: move namespace and worklaod to another project
--
- enable cluster montiroing      
- enable project monitoring for project A and project B     
- delploy workload with custom metrics in namespace1 in project A     
- check the custom metrics in project A's promethues      
- move the namespace1 to project B     
- the custom metrics shouild show in project B's Promethues     
-  the metrics for the workload in project A's Promethus should have no new   data
