### ISSUE TITLE
[Load Balancer] Support pattern matching

### ISSUE THREAD

**Issue by bcaudesaygues** [rancher/rancher#1739]
Add pattern matching on advanced routing option.
Like HAProxy 1.5 flag -m.

**Comment by deniseschannon** [comment]
@bcaudesaygues 

Does the wildcard ability solve what you were looking for?

https://github.com/rancher/rancher/issues/1787

http://docs.rancher.com/rancher/rancher-compose/rancher-services/#syntax-of-the-combination-of-all-optional-fields
 
Scroll down to Wildcards.

**Comment by eesprit** [comment]
@deniseschannon : The wildcard ability works only for host name maching.
@bcaudesaygues was in fact asking to have the ability to use regexp matching for path.

As I see it, it could be a selection list in the UI to indicate the type of tge desired match for the path. HAproxy supports those :

**Comment by eesprit** [comment]
If you prefer that we made a new issue rather than reopening this one, please tell us.
