### ISSUE TITLE
Support turn on/off Node Exporter for cluster level Prometheus

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17392]
Support turn on/off Node Exporter for cluster level Prometheus
Node exporter requires host network and so people can access it via hostip:port
Then they will be able to see the node metrics such as node cpu and memory usage.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Confirmed issue.
Confirmed the option exists, you can change the option to fit your needs, and that cluster monitoring still works as expected regardless of the setting you choose. Smoke tested this area and validated the HTTP/api.

Note when enabled you won't see charts for Cluster Metrics, as expected.

Screenshot below shows the relevant areas. You can change the port to your liking. The field asking for the Node Exporter Host Port is only displayed if you have enabled Node Exporter.
![screen shot 2019-02-20 at 3 21 39 pm](https://user-images.githubusercontent.com/45179589/53128966-78e65800-3523-11e9-9025-afe5bb402319.png)
