### ISSUE TITLE
Get Token For Joining a Node to existing provisioned cluster 

### ISSUE THREAD

**Issue by gelinger777** [rancher/rancher#17397]
Hi everybody. One simple question. 
I have created a cluster on Hetzner nodes using UI Hetzner Driver 
 
https://mxschmitt.github.io/ui-driver-hetzner/  . 

In the same datacenter I have a dedicated server with docker on it.
If I imagine right, if i have the token and md5 of  rancher 
With following  command 

`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.5 --server https://myrancherserver.com  --token MYTOKENHERE  --ca-checksum MYCHECKSUM_HERE --worker`

I should be able to join the machine to existing , provisioned by rancher server. Is that right?

If so, how I can get the Token and Checksum?

**Comment by superseb** [comment]
Automation for adding nodes to cluster is shown in the quickstart guides: https://github.com/rancher/quickstart

You can extract the command from: `$RANCHER_URL/v3/clusterregistrationtoken`
