### ISSUE TITLE
Drop k8s 1.9 and 1.10 from Rancher cluster provisioning

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#17399]
With 1.13 being the new default in v2.2 and k8s's policy of supporting 3 releases, we should drop 1.9 and 1.10 from new cluster provisioning.
If this is a dupe, feel free to close it @alena1108

**Comment by alena1108** [comment]
https://github.com/rancher/rke/issues/1075

**Comment by alena1108** [comment]
Closing as a duplicate of rke issue
