### ISSUE TITLE
Cannot add answers to a chart previously deployed with none

### ISSUE THREAD

**Issue by kevinsimons-wf** [rancher/rancher#17405]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy chart application with no answers
2. Try to upgrade app through cli and add a new answer

**Result:**
An error about assigning an entry to nil map and the upgrade fails

**Other details that may be helpful:**
```
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/rancher/cli/cmd.getAnswersFile(0x7ffddf6d88ba, 0xc, 0x0, 0x7ffddf6d88ba, 0xc)
/go/src/github.com/rancher/cli/cmd/app.go:863 +0x259
github.com/rancher/cli/cmd.processAnswers(0xc4200dab00, 0xc420107260, 0x0, 0x0, 0x0, 0x0, 0xc4201fe000)
/go/src/github.com/rancher/cli/cmd/app.go:823 +0x25a
github.com/rancher/cli/cmd.appUpgrade(0xc4200dab00, 0xc42000f500, 0xc4200dab00)
/go/src/github.com/rancher/cli/cmd/app.go:306 +0x1b1
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x8427a0, 0x923280, 0xc4200dab00, 0x0, 0xc42000f5c0)
/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/rancher/cli/vendor/github.com/urfave/cli.Comma... (1132 more, please see e.stderr)
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.5
- Installation option (single install/HA): HA

**Comment by hevelop-team** [comment]
I get the same error when trying to upgrade my app from rancher/cli.
`rancher apps upgrade --set httpd.tag=k8s-1aa26cdaa5d03016ac819c6e4eadb77a64653a58 magento1-k8s 6.0.2`

**Comment by bordeo** [comment]
I get the same error when trying to upgrade my app from rancher/cli.
`rancher apps upgrade --set httpd.tag=k8s-1aa26cdaa5d03016ac819c6e4eadb77a64653a58 magento1-k8s 6.0.2`

**Comment by davidnuzik** [comment]
**Replication:**
v2.2.0 rancher cli
v2.2.4 Rancher Server

- Install an app with no answers. In my case helm clamav
`rancher app install --namespace apps2 clamav clamavname1`
- Attempt to upgrade the app and set answers this time
`rancher app upgrade --set asdf=fdsa clamavname1 1.0.1`

This will fail. We expected to be able to upgrade the app and to set answers.
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/rancher/cli/cmd.processAnswers(0xc4200ba9a0, 0xc4200eb420, 0x0, 0x0, 0x0, 0x0, 0xc4203680c0)
        /go/src/github.com/rancher/cli/cmd/app.go:1015 +0x196
github.com/rancher/cli/cmd.appUpgrade(0xc4200ba9a0, 0xc420102300, 0xc4200ba9a0)
        /go/src/github.com/rancher/cli/cmd/app.go:404 +0x1c3
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x1486000, 0x1583bd0, 0xc4200ba9a0, 0x0, 0xc42014a720)                                                                                                                    
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0x156555c, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1575f25, 0x2a, 0x0, ...)                                                                                                        
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:165 +0x4bb
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc420126380, 0xc4200ba6e0, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:383 +0xad7
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.startApp(0x1564698, 0x4, 0x0, 0x0, 0xc420051120, 0x1, 0x1, 0x156a5fe, 0x14, 0x0, ...)                                                                                          
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:330 +0x944
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0x1564698, 0x4, 0x0, 0x0, 0xc420051120, 0x1, 0x1, 0x156a5fe, 0x14, 0x0, ...)                                                                                               
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:103 +0x8c9
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc4201261c0, 0xc420102300, 0x7, 0x8, 0x0, 0x0)
        /go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:259 +0x740
main.mainErr(0xc420111f70, 0x0)
        /go/src/github.com/rancher/cli/main.go:116 +0x1605
main.main()
        /go/src/github.com/rancher/cli/main.go:57 +0x22
```

**Validation:**
v2.3.0-rc1 rancher cli
v2.2.4 Rancher Server

- Install an app with no answers. In my case helm clamav
`rancher app install --namespace apps2 clamav clamavname2`
- Attempt to upgrade the app and set answers this time
`rancher app upgrade --set asdf=fdsa clamavname2 1.0.1`

The CLI does not panic and the app successfully updates. My answers are there
asdf": "fdsa"

**Comment by paylocity-sflanders** [comment]
the upgrade issue happens even if you had answers before.  basically includes --set or --values or --answers will result in that same crash... essentially it doesn't appear you can do an upgrade using the cli unless you completely exclude doing config updates.. it is possible to do it from the ui though
