### ISSUE TITLE
cluster logging doesnt dynamically update when cluster settings are changed

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#17401]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. have a host with a custom docker root (rancher wont detect its custom)
2. enable logging for the cluster
3. update the cluster to have the correct docker root
4. logging is still broken

**Expected Result:**
logger and fluentd should dynamically be updated if there are any cluster changes.

**Comment by aemneina** [comment]
**Workaround**
1. disable logging
2. delete fluentd and logger workloads
3. reenable logging

**Comment by aemneina** [comment]
This was seen in v2.1.x and possibly related to the following:
https://github.com/rancher/rancher/issues/21112
https://github.com/rancher/rancher/pull/27585

**Comment by sadhugit** [comment]
The variable "fluentd.cluster.dockerRoot " value is hardcoded and needs to make it configurable.

**Comment by paynejacob** [comment]
With logging v2 introduced in rancher 2.5, logging configuration was moved to custom resources monitored by an operator.  All changes are monitored and dynamically applied.
