### ISSUE TITLE
Network field empty when editing a vSphere Node Profile

### ISSUE THREAD

**Issue by hwasp** [rancher/rancher#17412]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** 

 - Create a vSphere Node Profile
 - Fill all info including Network field in 3. Scheduling section
 - Save the profile
 - Edit the profile

**Result:**

 - The Network field in 3. Scheduling section appears blank
 - The profile can not be saved without setting the Network field again

**Environment information**

- Rancher version:  v2.1.5
- Installation option (single install/HA): Single

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/15879

**Comment by tfiduccia** [comment]
Version - master 4/8, UI v2.3.0
Verified fixed
