### ISSUE TITLE
two eureka services in one application, ping failed between the two services in different host

### ISSUE THREAD

**Issue by wang-michael** [rancher/rancher#17415]
I want to use rancher to deploy eureka ha ,
my rancher version: v1.6.25; os version: ubuntu-16.04.5-server-amd64; docker version: 17.03.1-ce;

Two eureka services are in one application.
if two services in one host , ping is success, but  if in different host,ping is always failed.

for example, peer1 and peer2 are in one host, they can ping; peer3 is in the other host, when i ping peer3 in peer1, peer3's ipaddress is shown in peer1, but ping is always failed. ufw is disabled among all hosts.

![image](https://user-images.githubusercontent.com/30339130/51081885-349eb580-1736-11e9-84c2-16c4904cd727.png)

![image](https://user-images.githubusercontent.com/30339130/51081907-cf978f80-1736-11e9-8329-05468b15e1c4.png)

and sometimes i meet a very weird phenomenon， that is the first eureka service named peer1 deploy in one rancher-agent, and the other service named peer2 deploy in the other rancher-agent, then one of the rancher-agent host will auto shutdown !!! The two hosts are virtualized by xen server.

I don't know where the problem is. I hope someone can help me with this question. I will appreciate it very much ！！！

**Comment by wang-michael** [comment]
I create my own environment template, change the ipsec to vxlan, the bug is fix. I dont know why, this is so weird, hope it can help others.
![image](https://user-images.githubusercontent.com/30339130/51095687-848e8280-17f1-11e9-80f3-c611d3ebcebb.png)

**Comment by loganhz** [comment]
Thanks for the report. With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
