### ISSUE TITLE
leaving "wrap lines" turned off does not preserve whitespace

### ISSUE THREAD

**Issue by john-mcgowan-wowza** [rancher/rancher#17411]
When I am looking at logs in 2.1.3 and have the wrap lines option turned off, it seems like whitespace is being gobbled up.   So indentation and other formatting that depends on leading whitespace is broken.  when I check "wrap lines" the problem stops.

I don't think the wrap lines option should affect the leading whitespace behavior when viewing logs.  if this is intentional behavior it should be a different option like "condenced output" or something.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.3` UI: `v2.1.17` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/ui/pull/3444/files. It will be released in 2.4
