### ISSUE TITLE
Unexpected error when reading response body: http.http2StreamError

### ISSUE THREAD

**Issue by xuejipeng** [rancher/rancher#17416]
**What kind of request is this (question/bug/enhancement/feature request):**
bug
**Steps to reproduce (least amount of steps as possible):**

**Result:**
in the webui lanch kubectl get error Unexpected error http.http2StreamError and `kubextl exec -ti` to cattle-cluster-agent is work

log:
> kubectl get node -v 9
I0114 02:57:58.939040      41 loader.go:357] Config loaded from file /nonexistent/.kube/config
I0114 02:57:58.940051      41 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-tph6q:b5mxkqht9wvw7r76vgctpks87ckb6sfq7bt7c4zmw96f2tlh8sg7w9" https://xx.xxx.com/k8s/clusters/local/api
I0114 02:57:58.973161      41 round_trippers.go:405] GET https://xxx.xxx.com/k8s/clusters/local/api 200 OK in 33 milliseconds
I0114 02:57:58.973190      41 round_trippers.go:411] Response Headers:
I0114 02:57:58.973253      41 round_trippers.go:414]     Content-Length: 136
I0114 02:57:58.973282      41 round_trippers.go:414]     Strict-Transport-Security: max-age=15724800; includeSubDomains
I0114 02:57:58.973295      41 round_trippers.go:414]     Server: nginx/1.13.12
I0114 02:57:58.973486      41 round_trippers.go:414]     Date: Mon, 14 Jan 2019 02:57:58 GMT
I0114 02:57:58.973504      41 round_trippers.go:414]     Content-Type: application/json
I0114 02:57:58.973795      41 request.go:874] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.24.38.242:6443"}]}
I0114 02:57:58.974248      41 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-tph6q:b5mxkqht9wvw7r76vgctpks87ckb6sfq7bt7c4zmw96f2tlh8sg7w9" https://xxx.xxx.com/k8s/clusters/local/apis
I0114 02:57:58.985775      41 round_trippers.go:405] GET https://xxx.xxx.com/k8s/clusters/local/apis 200 OK in 11 milliseconds
I0114 02:57:58.985794      41 round_trippers.go:411] Response Headers:
I0114 02:57:58.985852      41 round_trippers.go:414]     Server: nginx/1.13.12
I0114 02:57:58.985869      41 round_trippers.go:414]     Date: Mon, 14 Jan 2019 02:57:58 GMT
I0114 02:57:58.985879      41 round_trippers.go:414]     Content-Type: application/json
I0114 02:57:58.985906      41 round_trippers.go:414]     Vary: Accept-Encoding
I0114 02:57:58.985914      41 round_trippers.go:414]     Strict-Transport-Security: max-age=15724800; includeSubDomains
E0114 02:57:58.986162      41 request.go:785] Unexpected error when reading response body: http.http2StreamError{StreamID:0x3, Code:0x2, Cause:error(nil)}
I0114 02:57:58.986266      41 cached_discovery.go:124] skipped caching discovery info due to Unexpected error http.http2StreamError{StreamID:0x3, Code:0x2, Cause:error(nil)} when reading response body. Please retry.
I0114 02:57:58.986424      41 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-tph6q:b5mxkqht9wvw7r76vgctpks87ckb6sfq7bt7c4zmw96f2tlh8sg7w9" https://xxx.xxx.com/k8s/clusters/local/api
I0114 02:57:58.997361      41 round_trippers.go:405] GET https://xxx.xxx.com/k8s/clusters/local/api 200 OK in 10 milliseconds
I0114 02:57:58.997381      41 round_trippers.go:411] Response Headers:
I0114 02:57:58.997399      41 round_trippers.go:414]     Date: Mon, 14 Jan 2019 02:57:58 GMT
I0114 02:57:58.997414      41 round_trippers.go:414]     Content-Type: application/json
I0114 02:57:58.997427      41 round_trippers.go:414]     Content-Length: 136
I0114 02:57:58.997440      41 round_trippers.go:414]     Strict-Transport-Security: max-age=15724800; includeSubDomains
I0114 02:57:58.997454      41 round_trippers.go:414]     Server: nginx/1.13.12
I0114 02:57:58.997585      41 request.go:874] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.24.38.242:6443"}]}
I0114 02:57:58.997813      41 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-tph6q:b5mxkqht9wvw7r76vgctpks87ckb6sfq7bt7c4zmw96f2tlh8sg7w9" https://xxx.xxx.com/k8s/clusters/local/apis
I0114 02:57:59.008869      41 round_trippers.go:405] GET https://xxx.xxx.com/k8s/clusters/local/apis 200 OK in 11 milliseconds
I0114 02:57:59.008907      41 round_trippers.go:411] Response Headers:
I0114 02:57:59.008917      41 round_trippers.go:414]     Vary: Accept-Encoding
I0114 02:57:59.008924      41 round_trippers.go:414]     Strict-Transport-Security: max-age=15724800; includeSubDomains
I0114 02:57:59.008941      41 round_trippers.go:414]     Server: nginx/1.13.12
I0114 02:57:59.008949      41 round_trippers.go:414]     Date: Mon, 14 Jan 2019 02:57:59 GMT
I0114 02:57:59.008957      41 round_trippers.go:414]     Content-Type: application/json
E0114 02:57:59.009121      41 request.go:785] Unexpected error when reading response body: http.http2StreamError{StreamID:0x7, Code:0x2, Cause:error(nil)}
I0114 02:57:59.009197      41 cached_discovery.go:124] skipped caching discovery info due to Unexpected error http.http2StreamError{StreamID:0x7, Code:0x2, Cause:error(nil)} when reading response body. Please retry.
I0114 02:57:59.009614      41 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-tph6q:b5mxkqht9wvw7r76vgctpks87ckb6sfq7bt7c4zmw96f2tlh8sg7w9" -H "Accept: application/json, */*" https://xxx.xxx.com/k8s/clusters/local/api
I0114 02:57:59.019979      41 round_trippers.go:405] GET https://xxx.xxx.com/k8s/clusters/local/api 200 OK in 10 milliseconds
I0114 02:57:59.020033      41 round_trippers.go:411] Response Headers:
I0114 02:57:59.020052      41 round_trippers.go:414]     Content-Type: application/json
I0114 02:57:59.020081      41 round_trippers.go:414]     Content-Length: 136
I0114 02:57:59.020088      41 round_trippers.go:414]     Strict-Transport-Security: max-age=15724800; includeSubDomains
I0114 02:57:59.020094      41 round_trippers.go:414]     Server: nginx/1.13.12
I0114 02:57:59.020100      41 round_trippers.go:414]     Date: Mon, 14 Jan 2019 02:57:59 GMT
I0114 02:57:59.020222      41 request.go:874] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.24.38.240:6443"}]}
I0114 02:57:59.020424      41 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-tph6q:b5mxkqht9wvw7r76vgctpks87ckb6sfq7bt7c4zmw96f2tlh8sg7w9" https:/xxx.xxx.com/k8s/clusters/local/apis
I0114 02:57:59.030869      41 round_trippers.go:405] GET https://xxx.xxx.com/k8s/clusters/local/apis 200 OK in 10 milliseconds
I0114 02:57:59.030887      41 round_trippers.go:411] Response Headers:
I0114 02:57:59.030895      41 round_trippers.go:414]     Date: Mon, 14 Jan 2019 02:57:59 GMT
I0114 02:57:59.030903      41 round_trippers.go:414]     Content-Type: application/json
I0114 02:57:59.030909      41 round_trippers.go:414]     Vary: Accept-Encoding
I0114 02:57:59.030919      41 round_trippers.go:414]     Strict-Transport-Security: max-age=15724800; includeSubDomains
I0114 02:57:59.030927      41 round_trippers.go:414]     Server: nginx/1.13.12
E0114 02:57:59.030989      41 request.go:785] Unexpected error when reading response body: http.http2StreamError{StreamID:0xb, Code:0x2, Cause:error(nil)}
I0114 02:57:59.031062      41 cached_discovery.go:124] skipped caching discovery info due to Unexpected error http.http2StreamError{StreamID:0xb, Code:0x2, Cause:error(nil)} when reading response body. Please retry.
I0114 02:57:59.031081      41 factory_object_mapping.go:93] Unable to retrieve API resources, falling back to hardcoded types: Unexpected error http.http2StreamError{StreamID:0xb, Code:0x2, Cause:error(nil)} when reading response body. Please retry.
I0114 02:57:59.031591      41 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl/v1.10.5 (linux/amd64) kubernetes/32ac1c9" -H "Authorization: Bearer kubectl-shell-user-tph6q:b5mxkqht9wvw7r76vgctpks87ckb6sfq7bt7c4zmw96f2tlh8sg7w9" https://xxx.xxx.com/k8s/clusters/local/api/v1/nodes?limit=500
I0114 02:57:59.045646      41 round_trippers.go:405] GET https://xxx.xxx.com/k8s/clusters/local/api/v1/nodes?limit=500 200 OK in 14 milliseconds
I0114 02:57:59.045666      41 round_trippers.go:411] Response Headers:
I0114 02:57:59.045680      41 round_trippers.go:414]     Server: nginx/1.13.12
I0114 02:57:59.045746      41 round_trippers.go:414]     Date: Mon, 14 Jan 2019 02:57:59 GMT
I0114 02:57:59.045761      41 round_trippers.go:414]     Content-Type: application/json
I0114 02:57:59.045768      41 round_trippers.go:414]     Vary: Accept-Encoding
I0114 02:57:59.045774      41 round_trippers.go:414]     Strict-Transport-Security: max-age=15724800; includeSubDomains
E0114 02:57:59.045935      41 request.go:785] Unexpected error when reading response body: http.http2StreamError{StreamID:0xd, Code:0x2, Cause:error(nil)}
F0114 02:57:59.046042      41 helpers.go:119] Unexpected error http.http2StreamError{StreamID:0xd, Code:0x2, Cause:error(nil)} when reading response body. Please retry.
>

**Other details that may be helpful:**

**Environment information**
- Rancher version rancher:v2.1.5 from helm:
- Installation option HA:

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:39:52Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 27
 Running: 16
 Paused: 0
 Stopped: 11
Images: 9
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 129
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-117-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.796 GiB
Name: iZ6weda51fban8wa024ccdZ
ID: EURA:CJXD:YUEP:DCHK:W4B3:AXNM:RBZ3:3M2R:F23N:D7VT:J6Z2:WDUZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by brechsteiner** [comment]
the same problem here

**Comment by lianlianhe** [comment]
i got same issue.

**Comment by ZoltanPD** [comment]
We had a similar issue in our Rancher GUI and after a thorough investigation we found out that it was an issue in our nginx configuration. If you try to run in GUI the "kubectl get no -v 9" command you can see, that it tries to do some curl call. Copy that curl command and paste it in the console, then you can see that the response is cut at 1024 bytes. To avoid this issue we had to add the following to our nginx config:

map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

and then under server:

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

For us it solved the issue.

**Comment by superseb** [comment]
That is already documented at https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#example-nginx-config.

If this still happens on the latest version, please reply with the environment details so we can investigate.
