### ISSUE TITLE
Ability to restore from the "local" backup

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17414]
Support for taking etcd backups and restoring from them was added as a part of https://github.com/rancher/rancher/issues/16163. Today you can restore from the remote (S3) backup  only; we should add restore from local too. There are not to many changes on the backend needed, mostly wiring up rancher/rke/rke-tools to make the correct calls.

**Comment by soumyalj** [comment]
Tested with master build from Jan 30 2019. 
1. Create a DO cluster with 3 nodes having all roles in each and use local etcd backup
2. Create workloads/ingress
3. Perform a backup through UI.
4. Break the cluster by deleting the etcd containers in two hosts
5. Restore the cluster by performing "restore from Backup" action. Choose the backup to restore from.   

The cluster was restored successfully and the data was intact. Creation of new workloads after restore also succeeded   

Also, performed restore from a backup on a healthy cluster. Restore was successful with no data loss. Creation of new workloads/ingress succeeded.
