### ISSUE TITLE
Auto-populate host labels for scheduling

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#1742]
When adding hosts certain labels should be added for ease of use in scheduling rules. For instance, I want service A to run on a host with Docker version 1.7 vs 1.6. 

Labels that seem most obvious:

Memory
CPU
Kernel
Docker Version

To start out CPU total and Memory total might work, and let users ask for more advanced or realtime statistics. But for simple host based scheduling decisions, these would be a good start.

**Comment by vincent99** [comment]
These don't sound like they would be actual labels... what's going to keep them in sync when the kernel or amount of memory change?  And how would you really use them without greater-than/less-than scheduling rules... kernel is exactly `3.19.0-25-generic`?

**Comment by deniseschannon** [comment]
We've added these labels now:

`io.rancher.host.linux_kernel_version`
`io.rancher.host.docker_version`

@cloudnautique Do you think you'd want to add more or can we close for now?

**Comment by deniseschannon** [comment]
Closing as we've added some of the requested labels. @cloudnautique to open another issue if he wants more labels added.
