### ISSUE TITLE
EKS cluster with invalid AMI is not removed from AWS after deleting from Rancher

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17424]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add an Amazon EKS cluster with a wrong AMI role (at the `Custom AMI override` filed)
![screenshot](https://user-images.githubusercontent.com/6218999/51129292-51df8c80-17e7-11e9-9ba4-8e64db571398.png)

- After the provision fails, delete this cluster from Rancher UI
![screenshot](https://user-images.githubusercontent.com/6218999/51130260-d501e200-17e9-11e9-827f-3e8bcdd2eddd.png)

**Result:**
The cluster is left on AWS. 
![screenshot](https://user-images.githubusercontent.com/6218999/51130308-f531a100-17e9-11e9-9e39-c6bc3284f71a.png)

Expected result: the cluster should be deleted from AWS.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master on 1/14
- Installation option (single install/HA):
Single Install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by rmweir** [comment]
@nathan-jenan-rancher Ready for review. Will update vendor conf once kontainer-engine PR is merged.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/12/19)
Confirmed fixed. Followed steps and when I delete the EKS cluster now it is removed from EKS console.
