### ISSUE TITLE
Node scheduling problem Linux/Windows for Rancher System components

### ISSUE THREAD

**Issue by JohnnyElvis** [rancher/rancher#17423]
I am using Rancher v2.1.1 agents on my cluster. Since we experiment with Windows nodes via flanneI we found some issues. I am having problems with Node Scheduling. Sometimes eg. kube-dns (rancher/k8s-dns-kube-dns-amd64:1.14.10) tries to start on a Windows node

I've checked the Node Scheduling, maybe adding "beta.kubernetes.io/os = linux" out of the box would avoid this behavior

**Comment by kingsd041** [comment]
Version: master 2.2 (3/1/19) 
Confirmed fix.  We added the `beta.kubernetes.io/os != windows` tag to avoid this behavior.

@JohnnyElvis Thank you for your feedback
