### ISSUE TITLE
GKE : Cattle stop new preemptible nodes to join the cluster 

### ISSUE THREAD

**Issue by cyrilbkr** [rancher/rancher#17422]
Hi,
I'm  using a GKE cluster with the GCP preemptible node feature  and Rancher.
When a node is preempted the new node don't join the K8S cluster, it's strange because the new node is correctly added to the GCP instance group. 
GCP support  have confirmed that it looks like the issue arose as a result of a race condition caused by cattle. It looks like the kubelet recreated (re-registered) the node, and cattle deleted it. This resulted in the node being left behind. The source of this problem appears therefore appears to have been generated by cattle.

Log 
Jan 07 06:26:23 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: I0107 06:26:23.842031 1104 kubelet_node_status.go:82] Attempting to register node kubcluster-log-preemp-pool2-3854b57f-gr9z 
Jan 07 06:26:23 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: E0107 06:26:23.852059 1104 kubelet_node_status.go:144] Previously node "kubcluster-log-preemp-pool2-3854b57f-gr9z" had externalID "4366846573777210910"; now it is "6488086000208454384"; will delete and recreate. 
Jan 07 06:26:23 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: I0107 06:26:23.858811 1104 kubelet_node_status.go:150] Deleted old node object "kubcluster-log-preemp-pool2-3854b57f-gr9z" 
Jan 07 06:26:24 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: I0107 06:26:24.070111 1104 kubelet_node_status.go:82] Attempting to register node kubcluster-log-preemp-pool2-3854b57f-gr9z
Jan 07 06:26:24 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: I0107 06:26:24.080146 1104 kubelet_node_status.go:85] Successfully registered node kubcluster-log-preemp-pool2-3854b57f-gr9z 
Jan 07 06:26:24 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: E0107 06:26:24.104840 1104 kubelet_node_status.go:390] Error updating node status, will retry: failed to patch status "{}" for node "kubcluster-log-preemp-pool2-3854b57f-gr9z": nodes "kubcluster-log-preemp-pool2-3854b57f-gr9z" not found 
Jan 07 06:26:24 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: E0107 06:26:24.117693 1104 kubelet_node_status.go:390] Error updating node status, will retry: error getting node "kubcluster-log-preemp-pool2-3854b57f-gr9z": nodes "kubcluster-log-preemp-pool2-3854b57f-gr9z" not found  
Jan 07 06:26:24 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: E0107 06:26:24.133761 1104 kubelet_node_status.go:390] Error updating node status, will retry: error getting node "kubcluster-log-preemp-pool2-3854b57f-gr9z": nodes "kubcluster-log-preemp-pool2-3854b57f-gr9z" not found  
Jan 07 06:26:26 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: I0107 06:26:26.830530 1104 kubelet.go:1865] SyncLoop (ADD, "api"): "cattle-node-agent-n7tl9_cattle-system(0306b9e6-117a-11e9-8b72-42010a8e0002), prometheus-node-exporter-6xwbh_monitoring(03069eab-117a-11e9-8b72-42010a8e0002), kube-proxy-kubcluster-log-preemp-pool2-3854b57f-gr9z_kube-system(04cac534-117a-11e9-8b72-42010a8e0002), redis-log-bd78cddf9-n5ts5_regional-log(f3c217bf-1179-11e9-8b72-42010a8e0002)"                
Jan 07 06:26:30 kubcluster-log-preemp-pool2-3854b57f-gr9z kubelet[1104]: I0107 06:26:30.491898 1104 kubelet.go:1881] SyncLoop (DELETE, "api"): "cattle-node-agent-n7tl9_cattle-system(0306b9e6-117a-11e9-8b72-42010a8e0002)" 

Stackdriver log : 
protoPayload.methodName: delete
protoPayload.resourceName: kubcluster-log-preemp-pool2-3854b57f-gr9z
protoPayload.authenticationInfo.principalEmail="system:serviceaccount:cattle-system:cattle"
 
GKE Version  : 1.10.7-gke.11

Rancher version : 2.0.8

**Comment by FRoGbis** [comment]
Encountering the same problem... 

Any ideas?

**Comment by medanasslim** [comment]
same big problem !!! cattle still deleted my nodes
anybody have find a solution ?

**Comment by cyrilbkr** [comment]
any news ?
