### ISSUE TITLE
Deploying consul from catalog apps is throwing error - status unavailable

### ISSUE THREAD

**Issue by kvdivya** [rancher/rancher#17436]
Deploy consul as catalog app on rancher 2.1.5 goes into unavailable state -

Yaml file for deployment
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["3.16.70.171"],"port":32506,"protocol":"TCP","serviceName":"consul-rjsdr:consul-rjsdr-ui","allNodes":true}]'
  creationTimestamp: 2019-01-15T01:01:53Z
  generation: 1
  labels:
    chart: consul-3.5.1
    component: consul-rjsdr-consul
    heritage: Tiller
    io.cattle.field/appId: consul-rjsdr
    release: consul-rjsdr
  name: consul-rjsdr
  namespace: consul-rjsdr
  resourceVersion: "57338"
  selfLink: /apis/apps/v1beta2/namespaces/consul-rjsdr/statefulsets/consul-rjsdr
  uid: 25a6edde-1861-11e9-af1d-02ce6a0f3e4a
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: consul-rjsdr-consul
      release: consul-rjsdr
  serviceName: consul-rjsdr
  template:
    metadata:
      creationTimestamp: null
      labels:
        chart: consul-3.5.1
        component: consul-rjsdr-consul
        heritage: Tiller
        release: consul-rjsdr
      name: consul-rjsdr
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - consul-rjsdr-consul
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - command:
        - /bin/sh
        - -ec
        - |
          IP=$(hostname -i)
          if [ -e /etc/consul/secrets/gossip-key ]; then
            echo "{\"encrypt\": \"$(base64 /etc/consul/secrets/gossip-key)\"}" > /etc/consul/encrypt.json
            GOSSIP_KEY="-config-file /etc/consul/encrypt.json"
          fi

          for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
              while true; do
                  echo "Waiting for ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME} to come up"
                  ping -W 1 -c 1 ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc > /dev/null && break
                  sleep 1s
              done
          done

          PEERS=""
          for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
            NEXT_PEER="$(ping -c 1 ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc | awk -F'[()]' '/PING/{print $2}')"
            if [ "${NEXT_PEER}" != "${POD_IP}" ]; then
              PEERS="${PEERS}${PEERS:+ } -retry-join ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc"
            fi
          done

          exec /bin/consul agent \
            -ui \
            -domain=consul \
            -data-dir=/var/lib/consul \
            -server \
            -bootstrap-expect=${INITIAL_CLUSTER_SIZE} \
            -disable-keyring-file \
            -bind=0.0.0.0 \
            -advertise=${IP} \
            ${PEERS} \
            ${GOSSIP_KEY} \
            -client=0.0.0.0 \
            -dns-port=${DNSPORT} \
            -http-port=8500
        env:
        - name: INITIAL_CLUSTER_SIZE
          value: "3"
        - name: STATEFULSET_NAME
          value: consul-rjsdr
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: STATEFULSET_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DNSPORT
          value: "8600"
        image: consul:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - consul
            - members
            - -http-addr=http://127.0.0.1:8500
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: consul-rjsdr
        ports:
        - containerPort: 8500
          name: http
          protocol: TCP
        - containerPort: 8400
          name: rpc
          protocol: TCP
        - containerPort: 8301
          name: serflan-tcp
          protocol: TCP
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8302
          name: serfwan-tcp
          protocol: TCP
        - containerPort: 8302
          name: serfwan-udp
          protocol: UDP
        - containerPort: 8300
          name: server
          protocol: TCP
        - containerPort: 8600
          name: consuldns-tcp
          protocol: TCP
        - containerPort: 8600
          name: consuldns-udp
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/consul
          name: datadir
        - mountPath: /etc/consul/secrets
          name: gossip-key
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gossip-key
        secret:
          defaultMode: 420
          secretName: consul-rjsdr-gossip-key
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: consul-rjsdr-589488b7c6
  observedGeneration: 1
  replicas: 1
  updateRevision: consul-rjsdr-589488b7c6
  updatedReplicas: 1

**Comment by loganhz** [comment]
consul is not in Rancher library. Please file another issue and provide the catalog url for it.
