### ISSUE TITLE
Prometheus is leaking memory within rancher

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#17434]
**What kind of request is this (question/bug/enhancement/feature request):**

bug
**Steps to reproduce (least amount of steps as possible):**

run rancher server container
**Result:**

Rancher container seems to leak memory and run the server out of memory

Steps to reproduce:
- Run rancher server container
- provision a new DO cluster

I ran the pprof to fetch the heap profile and i can see that prometheus is taking up a lot of memory:

![graph](https://user-images.githubusercontent.com/3309968/51146145-9eb27a00-185e-11e9-9b76-da8ff89cd0b7.gif)

**Comment by cloudnautique** [comment]
Whatever controller is getting that, needs to do something like this:
https://github.com/rancher/rancher/pull/14823/files

**Comment by thxCode** [comment]
I think the root cause isn't Prometheus, it seems like the `metrics collector` which coded in the rancher.

**Comment by orangedeng** [comment]
I think it has been taken care of. Adding environment variable `NORMAN_REFLECTOR_METRICS=true` should be able to disable the reflector metrics.

**Comment by orangedeng** [comment]
@cjellick Related PR is https://github.com/rancher/norman/pull/201.

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher:master 1/21

Steps:
- ran Rancher sever container
- added 6 different clusters and enabled monitoring for all of them
- leave the server running for about 12 hours
- use pprof to fetch the heap profile

Result:
- Rancher server is running smoothly and using about 1 GiB memory overall 
```
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
objective_murdock   13.36%              1.023 GiB / 7.796 GiB   13.13%              377 MB / 159 MB     0 B / 9.09 GB       18
```
- the heap looks good and no memory leak from either Prometheus or metrics collector

![out](https://user-images.githubusercontent.com/6218999/51556054-5125a680-1e36-11e9-82a4-13eb62f06f9f.png)
