### ISSUE TITLE
Monitoring not working with AKS

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17446]
Version: master 2.2 (1/15/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an AKS cluster and enable monitoring

**Result:**
Monitoring will never enable. In the UI the state will always be "Monitoring API is not ready"
In the logs you'll eventually see:
```
2019/01/15 16:46:14 [ERROR] ClusterController c-72nkq [user-cluster-monitoring] failed with : unable to sync Cluster aks-david-take2(c-72nkq): failed to deploy system monitoring: failed to grant monitoring permissions: [failed to query "system-monitor" ServiceAccount: Get https://c-72nk-aks-docker-machi-14a619-master-f5b5a276.hcp.westus.azmk8s.io:443/api/v1/namespaces/cattle-prometheus/serviceaccounts/system-monitor?timeout=30s: context deadline exceeded, failed to query "system-monitor" ClusterRole: Get https://c-72nk-aks-docker-machi-14a619-master-f5b5a276.hcp.westus.azmk8s.io:443/apis/rbac.authorization.k8s.io/v1/clusterroles/system-monitor?timeout=30s: context deadline exceeded]
2019/01/15 16:46:19 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10242
2019/01/15 16:46:19 [INFO] kontainerdriver azurekubernetesservice stopped
```
Full log file:
[aks_nomonitor.txt](https://github.com/rancher/rancher/files/2760646/aks_nomonitor.txt)

In some cases the monitoring will appear to be functional in the UI but you cannot view charts:
![image](https://user-images.githubusercontent.com/45179589/51197549-15776380-18af-11e9-83a7-06f28ab885fe.png)
In this case above it took over 30 mins for monitoring to be "working".
Here is the full log file again with some more information:
[aks_nomonitor_after_longtime_monitoring_claims_to_be_working.txt](https://github.com/rancher/rancher/files/2760693/aks_nomonitor_after_longtime_monitoring_claims_to_be_working.txt)

**Other details that may be helpful:**
Single rancher install on supported docker and ubuntu (17.03 and 16.04 respectively).
Tested with other types of clusters and they are working.

**Comment by thxCode** [comment]
@davidnuzik , I think this can be retested after merging https://github.com/rancher/rancher/pull/17311. cc @loganhz

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/11/19)
Confirmed fixed. You can enable monitoring with AKS now without any issues.
Note that the only issue I observed is an existing issue: #17344
Smoke tested grafana monitoring with AKS.
