### ISSUE TITLE
Active Directory authenticated user's permissions are gone if the user's Active Directory path changes.

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#17445]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. Configure rancher2.1.x to use Active Directory authentication.
2. Assign some permissions to one AD user.
3. Adjust the above user's AD path in the AD management system without changing its sAMAccountName
4. Login again using the above AD user.

**Result:**
The permissions assigned to the AD user above  are all gone.

**Other details that may be helpful:**
I think the sAMAccountName is the global unique username for the Active Directory and should be unique user for rancher too.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.3
- Installation option (single install/HA): single

**Comment by happyyangyuan** [comment]
Similar to "Add unique user ID attribute to AD configuration" #13434 but not quite the same.

**Comment by nlowe** [comment]
We just got bit by this pretty badly (see my comments in #13434). The sAMAccount name can change as well (i.e. when an employee name changes). What about instead using `objectGUID` or `objectSid`?

**Comment by happyyangyuan** [comment]
> We just got bit by this pretty badly (see my comments in #13434). The sAMAccount name can change as well (i.e. when an employee name changes). What about instead using `objectGUID` or `objectSid`?

Id is great, I can't agree more.
