### ISSUE TITLE
Rancher is not pulling my private latest image

### ISSUE THREAD

**Issue by iwan** [rancher/rancher#17449]
I have deployed my 4 container app, and all work fine. But when i update my private container hosted by Docker Hub  iwan/my_app:latest and i upgrade the container in Rancher it doesn't pull the latest image but the same image already running although the checkbox "Always pull image before creating" is checked...

Any idea?

Thanks

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.25` Cattle: `v0.183.68` UI: `v1.6.49` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
Could you provide the reproduce steps, please?

**Comment by superseb** [comment]
Let me know if you need help on this.
