### ISSUE TITLE
Unable to remove alert rules from an alert group

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17448]
Version: master 2.2 (1/22/19) ImageID: 7960ae27b837

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an alert group
- Click on the "Add alert rule" blue button to add another rule
- Try to "Remove this Alert" and nothing will happen.

**Result:**
Unable to remove alert rules from a group. There are no errors in the browser console.
Screenshot below shows that I clicked the "Remove this Alert" link but the rule is still there:
![image](https://user-images.githubusercontent.com/45179589/51547239-1d8d5100-1e23-11e9-81ec-7198888ba3c6.png)

**Environment:**
Single node rancher server on Ubuntu 16.04 with Docker 17.03
Google Chrome for macOS 71.0.3578.98 (Official Build) (64-bit)

**Comment by aiwantaozi** [comment]
Hi @davidnuzik  , do you have any environment or more details? I could not reproduce it.

**Comment by davidnuzik** [comment]
Hi @aiwantaozi , I updated the issue description and reproduced again today with latest master. I added environmental information. The version used is on top.

**Comment by aiwantaozi** [comment]
@davidnuzik Thanks David, I will let our UI colleague check it.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/28/19)
Confirmed fix. I am no longer able to reproduce the issue. I can successfully remove alert rules without any errors in the UI. I also lightly tested alerts / halo tested.
