### ISSUE TITLE
Services don't restart existing containers on host reboot

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#1744]
Rancher version v0.31.0

Create a service (no restart policy) that schedules to all hosts with host label.
Host 1 should now have service container "A0"
reboot host
Host comes back you have a stopped "A0" container and a new "A1" container is created.

Discussed this with Alena, this is a bug.

**Comment by LLParse** [comment]
+1

Would really like to see this fixed, recoverable errors become unrecoverable ones when stateful containers get deleted and recreated.

**Comment by tfiduccia** [comment]
Version - 2.0 master 10/10
This is still an issue in the 2.0 builds.  Still needs to be fixed.

**Comment by vincent99** [comment]
This doesn't apply to 2.0-preview2+, though you may need a statefulset instead of a deployment depending on exactly what behavior you want.
