### ISSUE TITLE
Doc Bug (cosmetic)

### ISSUE THREAD

**Issue by longwuyuan** [rancher/rancher#17442]
**What kind of request is this (question/bug/enhancement/feature request):**
Cosmetic bug on Docs

**Steps to reproduce (least amount of steps as possible):**
Visit https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/registries/

**Result:**
Opening paragraph seems repeated 2 times ;

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by superseb** [comment]
Thanks, created https://github.com/rancher/docs/pull/1110
