### ISSUE TITLE
When removing a project from GlobalDNS entry , ingress ips from the removed project are not getting cleared.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17455]
Rancher server version - Build from master - Jan 14
HA setup with 2 DO clusters.

Steps to reproduce the problem:
1. Create a globalDns entry with fqdn - "test1.test.com" with projectIds set to Cluster1 and project p1.
2. Create globalDnsProvider with root domain - "test.com"
3. In user cluster - Cluster1 and project p1, Create Ingress - ingress1 using annotation - rancher.io/globalDNS.hostname=test1.test.com which points to a workload with host name rule pointing to "test1.test.com"
4. After this , we see an FQDN entry getting created with ingress1 ips.
5. Edit globalDns entry and remove " Cluster1/project p1".

FQDN entry with ingress1 ips continue to be present.

Expected Behavior:
FQDN entry should be deleted .

**Comment by alena1108** [comment]
Has the same nature as https://github.com/rancher/rancher/issues/17454. Discussed the fix with @prachidamle , it should address both issues.

**Comment by alena1108** [comment]
The fix should be:

```
* Instead - or in addition to - globalDNS.status.endpoints, have cluster scoped endpoints map[string][]string
* have a global dns controller on the user cluster side. This controller will be responsible for updating global dns's endpoints for only its own cluster
* The controller will be listening on the global dns changes, and will drop the events for the global dns that are not bound to its cluster
* The controller will also be listening to any ingress updates in its cluster
* The logic for the endpoints reconciliation shouldn't be specific to a particular ingress, it should be done for all global dns's referencing this user cluster
```

**Comment by sangeethah** [comment]
Tested with latest build from master - Jan 28


1. Create a globalDns entry with fqdn - "test1.test.com" with projectIds set to Cluster1 and project p1.
2. Create globalDnsProvider with root domain - "test.com"
3. In user cluster - Cluster1 and project p1, Create Ingress - ingress1 using annotation - rancher.io/globalDNS.hostname=test1.test.com which points to a workload with host name rule pointing to "test1.test.com"
4. After this , we see an FQDN entry getting created with ingress1 ips.
5. Edit globalDns entry and remove " Cluster1/project p1" and add another project that does not have ingress with the expected FQDN set as annotation.

After this ,Route 53 entry relating to this FQDN gets deleted as expected.
