### ISSUE TITLE
Adding a new Global DNS with an fqdn for a project which has ingress with the same global fqdn configured does not result in route53 entry getting created.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17454]
Rancher server version - Build from master - Jan 14

HA setup with 2 DO clusters.

Steps to reproduce the problem:
1. Create globalDnsProvider with root domain - "test.com"
2. In user cluster - Cluster1/P1,  Create Ingress - ingress1 using annotation - rancher.io/globalDNS.hostname=test1.test.com which points to a  workload with host name rule pointing to "test1.test.com"
3. Create a globalDns entry  with fqdn - "test1.test.com" with projectIds set to Cluster1/P1.

After this , we dont see a FQDN entry getting created with ingress1 ips.

**Comment by sangeethah** [comment]
Tested with latest build from master - Jan 28

HA setup with 2 DO clusters.

1. Create globalDnsProvider with root domain - "test.com"
2. In user cluster - Cluster1/P1, Create Ingress - ingress1 using annotation - rancher.io/globalDNS.hostname=test1.test.com which points to a workload with host name rule pointing to "test1.test.com"
3. Create a globalDns entry with fqdn - "test1.test.com" with projectIds set to Cluster1/P1.

After this , we see route53 entry getting created for "test1.test.com" as expected.

**Comment by kz12123** [comment]
Similar issue with CF provider.

Subdomain fqdn works.
Root fqdn does not propogate.
