### ISSUE TITLE
failed to start user controllers for cluster c-xxxxx: timeout syncing controllers

### ISSUE THREAD

**Issue by vvkkhjt** [rancher/rancher#17456]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1,import k8s cluster from qcloud
2,log rancher agent

**Result:**
rancher log:
![1547605892](https://user-images.githubusercontent.com/12765476/51222826-6011e200-197a-11e9-8f45-af9db86e459d.png)

rancher-agent log:
![1547605931](https://user-images.githubusercontent.com/12765476/51222833-656f2c80-197a-11e9-821e-43d89c0a66da.png)

**Environment information**

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.3
- Installation option (single install/HA): rancher-ha

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):cloud,8u32g
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.8-qcloud", GitCommit:"be8246736c14f62bd0a91601c8bac5629738045f", GitTreeState:"dirty", BuildDate:"2017-10-17T15:37:17Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.8-tke.5", GitCommit:"a42ba7fc66d0258077c8397253ed80182e2453ed", GitTreeState:"clean", BuildDate:"2018-12-01T00:58:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 18
 Running: 16
 Paused: 0
 Stopped: 2
Images: 178
Server Version: 1.12.6
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.26 GiB
Name: VM_1_3_centos
ID: NB2N:GOPK:K5J6:RC5G:QJ65:QEXF:SUG6:54PE:L6RW:M6JI:QWFN:F3ND
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by vasartori** [comment]
Same behaviour, but in version 2.3.3

**Comment by JannikZed** [comment]
Same behaviour but 2.6.9 ...seems to go hand in hand with this issue when trying to access our cluster via kubectl:
```
Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user user-XXX: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-XXX, error: timed out waiting for the condition") has prevented the request from succeeding
```

**Comment by rmdvb** [comment]
@JannikZed Did you ever find a solution for this issue? We run into the same issue on Rancher v2.7.9

**Comment by JannikZed** [comment]
@rmdvb I honestly don't know, what I did.. as always with rancher and kube: "diddling" around until it works again ..
