### ISSUE TITLE
GlobalDNS: handle RBAC when both either projectId or multiclusterappId is not set

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#17462]
When GlobalDNS is created, user should set either
a) projectId
b) multiclusterappId 

But if none of the above is set on the GlobalDNS, what RBAC rules should apply to the GlobalDNS? Should only admins be able to create a GlobalDNS without any of the project/multiclusterapp?

This ticket is more for followup, for 2.2 we have decided to always have either of the above two set on GlobalDNS

cc @alena1108

**Comment by mrajashree** [comment]
> This ticket is more for followup, for 2.2 we have decided to always have either of the above two set on GlobalDNS
@prachidamle then is it okay to remove this from 2.2 milestone?

**Comment by mrajashree** [comment]
I think users should be allowed to create it too. Since they will become the owners of that globalDNS entry and can add their projects later on or select a multiclusterapp

**Comment by alena1108** [comment]
@mrajashree if we remove this ticket from the milestone, we should file another one for `we have decided to always have either of the above two set on GlobalDNS` as this enforcement hasn't been added yet.

**Comment by mrajashree** [comment]
@alena1108 I have updated my RBAC PRs, and included the enforcement that either of these must be provided

**Comment by mrajashree** [comment]
In our user ingress controller's sync handler, we check if there are any Global DNS entries targeting the cluster in which this ingress is, and then we enqueue only those gdns entries. So if a gdns entry does not have mcapp, or target projects, it won't get enqueued, and the gdns controller won't work on it. Closing this as per our discussion @alena1108
