### ISSUE TITLE
Support for other values for restartPolicy than Always 

### ISSUE THREAD

**Issue by rajgpl** [rancher/rancher#17461]
Rancher versions:
rancher/server or rancher/rancher: v2.1.5
rancher/agent or rancher/rancher-agent: v2.1.5

What I did:
- Created a Workload without a restartPolicy
- The job was created with restartPolicy defaulting to Always
- Tried to create the Workload with values OnFailure, Never. It says not supported. Only supported is: Always.

This is the error message captured in the UI:
ImportYaml Error
The Deployment "some-name" is invalid: spec.template.spec.restartPolicy: Unsupported value: "OnFailure": supported values: "Always" 

Between, I am migrating from 1.6 where I use the following system label: 
io.rancher.container.start_once True

My requirement is that some specific containers needs to be run only once a day. They quit once their job is done. 

I tried using the same label in 2.x and it didn't work. As there is no support for OnFailure, Never for restartPolicy, is there any other way I can achieve the requirement of running a specific workload only once in 2.x?

**Comment by vincent99** [comment]
The options in kubernetes are what they are and are not really going to change unless k8s does.  2.x shares roughly no backend code and in general no labels from 1.x are relevant.


The rough equivalent of what you're looking for is either jobs (a different kind of workload) or "init" sidecar containers on a deployment (similar to a sidekick with start once in 1.x)

**Comment by rajgpl** [comment]
Thank you, Vincent. Will try jobs and sidecar containers.

I am using RKE v1.11.6. From the Kubernetes docs, I see restartPolicy field has possible values Always, OnFailure, and Never
https://v1-11.docs.kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy

I am not sure if I am missing something.

**Comment by vincent99** [comment]
Further down on that page:

```
Use a ReplicationController, ReplicaSet, or Deployment for Pods that are not expected to terminate, for example, web servers. ReplicationControllers are appropriate only for Pods with a restartPolicy of Always.
```

**Comment by rajgpl** [comment]
Ah .. I see.

Thank you so much for the help. Workload type Job worked for me.
