### ISSUE TITLE
Rancher-cli produces Warning about port mapping

### ISSUE THREAD

**Issue by ronny35** [rancher/rancher#17465]
**What kind of request is this (question/bug/enhancement/feature request):**
I deploy some services via rancher-cli but this action produces this warning:
"This workload is not created by Rancher UI or Rancher API. Rancher will not automatically create related services for port mapping" in rancher-ui

**Steps to reproduce (least amount of steps as possible):**
rancher-cli app install helm-repo/nginx

**Result:**
This workload is not created by Rancher UI or Rancher API. Rancher will not automatically create related services for port mapping

**Other details that may be helpful:**

**Environment information**
- Rancher 2.1.1

**Cluster information**
- Cluster type : Hosted
- Kubernetes version :
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"

**Comment by Galactros** [comment]
Same issue here!

**Comment by oexo** [comment]
similarly

**Comment by jrwhetse** [comment]
Same here

**Comment by dgigalo** [comment]
Any updates?

**Comment by stefanlasiewski** [comment]
Adding a comment to attempt to reopen.

This is still happening in Rancher 2.4. 

![image](https://user-images.githubusercontent.com/142752/132767414-19529f7f-7155-43ed-a53b-6d8711b56684.png)
