### ISSUE TITLE
Unable to add sidecar to existing Stateful set

### ISSUE THREAD

**Issue by Gambler13** [rancher/rancher#17463]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a stateful set (e.g. deploy Redis from catalog)
2. After successful deploy, try to add a sidecar (Prometheus exporter)

**Result:**
`Validation failed in API: StatefulSet.apps "redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

In my opinion, it should work. Because adding a sidecar should only affect the template field field an its children.
Manually adding a sidecar is working as expected.

**Other details that may be helpful:**
Related to rancher/rancher#16984
related to rancher/rancher#17283

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.4

**Comment by erSitzt** [comment]
I have the same problem with Rancher v2.2.1

**Comment by Rancheroo** [comment]
I have also ran into this issue in Rancher 2.3.3 and Rancher 2.3.4

**Comment by KuroObi** [comment]
+1

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/25089 
same issue
