### ISSUE TITLE
so many rancher agent running ?

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#17466]
*
![image](https://user-images.githubusercontent.com/14210543/51321480-dc511600-1a9d-11e9-83cd-7bff7fdb2c50.png)
*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |
|Route|`node`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14735
