### ISSUE TITLE
Load Balancer Layer 7 not working

### ISSUE THREAD

**Issue by rpelissi** [rancher/rancher#17460]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
- Install rancher 2 nodes 2.1.3 on vm/baremetal, 1 node will etcd/worker/controller, one node will be worker only
- Install a workload (hello world should be enough) and expose a port
- Create a LB Layer7 that will expose the workload to a specific hostname (hello.domain.lan for ex, the local domain is domain.local)
- Add a record in the local dns (local meaning in the network) to point hello.domain.lan to the ip of the etcd/worker/controller node so when accessing to http://hello.domain.lan it goes to the hello world workload page

**Result:**
This work fine as soon as the workload is running in the etcd/controller/worker node. But if the workload is running on the worker only node, then the http://hello.domain.lan give a 404 page not found and so the LB seems to not forward the request to the workload

**Other details that may be helpful:**
Maybe I am wrong but I thought that the LB will follow the worload wherever node is it running. So if I create a LB entry to a workload to point to a hostname known on the network and point this hostname ip to the primary node, then even if the workload is running on the node 2, the LB will forward the request to the right node, which is not the case right now.
Or maybe I have no understand at all how to have the LB setup correctly... In this case the documentation is lacking some details.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.3
- Installation option (single install/HA):
2 nodes (1 is etcd/controller/worker, the other one is worker only) on VMs

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by superseb** [comment]
Was an ingress created? Can you specify exact steps to reproduce? The default NGINX ingress controller will route requests based on hostname to the pods. For this to work, overlay networking should be functional between nodes. If not, usually 504 is presented when trying to access. What is the exact error when you try to visit the URL? The default response for NGINX ingress when not matching a host is `404 - default backend`. Are you using a hostname only or also a path? What does the logging of the NGINX ingress controller say? There are also some troubleshooting steps mentioned on https://rancher.com/docs/rancher/v2.x/en/troubleshooting/

Let me know when you can provide the requested info.
