### ISSUE TITLE
Feature request: set git branch to monitor with pipeline

### ISSUE THREAD

**Issue by materemias** [rancher/rancher#17474]
I would like to have a setting to select which git branch to monitor with a pipeline. This way I could have separate configs in different branches and it were easy to have a pipeline for staging and a pipeline for prod. 
Right now my staging cluster builds the prod pipeline as well because it gets triggered when a commit happens on prod branch. Ideally I would connect my staging cluster to only listen to commits in master branch. Is this possible?

**Comment by keson-chen** [comment]
@gitlawr @materemias @loganhz   I wanted this feature too.  Currently, branch binding  for pipeline confused me .

**Comment by materemias** [comment]
better explanation or options are recommended.

**Comment by pxvp2008** [comment]
> I would like to have a setting to select which git branch to monitor with a pipeline. This way I could have separate configs in different branches and it were easy to have a pipeline for staging and a pipeline for prod.
> Right now my staging cluster builds the prod pipeline as well because it gets triggered when a commit happens on prod branch. Ideally I would connect my staging cluster to only listen to commits in master branch. Is this possible?

@materemias  For the Gitlab repository, how do you handle the `.rancher-pipeline.yml` and `deployment.yaml` files for different branches? How do you ensure that the two files do not conflict with each other?

I have encountered a similar problem and look forward to your reply.

Thanks!

**Comment by materemias** [comment]
`.rancher-pipeline.yml` is different in `master` and in `prod` branches, and I set some rules to avoid ending up with the wrong version
eg. in master:
```
branch:
  include:
  - master
  exclude:
  - prod
```
I also have 2 different `deployment.yaml` files: `deployment-master.yaml` and `deployment-prod.yaml` referenced by the `.rancher-pipeline.yml` so far it works fine.

**Comment by pxvp2008** [comment]
Thank you very much, I have solved it here.

I also use 2 `deployment.yaml` files, `master-deployment.yaml` and `develop-deployment.yaml`, and then use the ${CICD_GIT_BRANCH} environment variable in the `.rancher-pipeline.yml` file. .

The contents of the `.rancher-pipeline.yml` file are as follows:
```yml
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./${CICD_GIT_BRANCH}-deployment.yaml
```
