### ISSUE TITLE
Clone cluster alert rule throw an error

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#17475]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Clone a cluster alert rule.
2. Click page.

**Result:**

![image](https://user-images.githubusercontent.com/18737885/51374577-7e283f80-1b3e-11e9-8857-e75297231f61.png)

**Comment by davidnuzik** [comment]
Entered possibly related issue: #17500
