### ISSUE TITLE
[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck

### ISSUE THREAD

**Issue by DarkBlaez** [rancher/rancher#17470]
Decided to give this a go under DigitalOcean. 

I have tried spinning up a single node instance and 3 node instances. There are all through adding a new cluster. The VMs are being spun up and built by Ranger automated. Taking the default OS, Region, etc. However, increased nodes to 8G 4vCPU, plenty of SSD. Again tried single node, tried 3 node. 

Tried Ubuntu 16.XX, tried CentOS 7.5

result is the same, cluster does not complete:

[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] 

Either this is something that is in just the setup or some other issue. But I have noticed in the git issues this pops up with regularity.

Thanks
DB

**Comment by DarkBlaez** [comment]
I also tried this with additional nodes with Centos 7.5, Docker 1.13.x

3 etcd nodes (2G, 2vcpu)
2 Control Plane (2G, 2vcpu)
2 Workers  (4G, 2vcpu)

Same result
[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver]

**Comment by superseb** [comment]
Can you describe the steps you are taking in more detail so I can run them? Please also share the logs from the `rancher/rancher` container and the output of `docker logs kube-apiserver` from the node(s) created. (see https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-access-nodes-created-by-rancher how to access them)

**Comment by superseb** [comment]
Let me know when you can follow up on this
