### ISSUE TITLE
[Question] Link to an older version of rancher/rke on release page?

### ISSUE THREAD

**Issue by FleischKarussel** [rancher/rancher#17476]
**What kind of request is this (question/bug/enhancement/feature request):**
Question: 
Why does point the rke release v0.1.15 to https://github.com/rancher/rke/releases/tag/v0.1.13?
https://github.com/rancher/rancher/releases

**Steps to reproduce (least amount of steps as possible):**
n/a

**Result:**
n/a

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Release v2.1.5

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
n/a
```

- Docker (use `docker info`):

```
n/a
```

**Comment by superseb** [comment]
It's a typo, thanks for the report.
