### ISSUE TITLE
Rancher CLI should expose Helm timeout flag

### ISSUE THREAD

**Issue by nickolaskraus-wf** [rancher/rancher#17471]
**What kind of request is this (question/bug/enhancement/feature request):**

🐞Bug

**Steps to reproduce (least amount of steps as possible):**

When attempting to deploy a Helm chart via Rancher that requires the `--wait` and `--timeout` flag, the deploy fails.

The Helm chart in question is [stable/sentry](https://github.com/helm/charts/tree/master/stable/sentry).

In order for this chart to deploy successfully, the following command is needed:

```bash
helm install -f values.yaml --name sentry --wait --timeout 600 .
```

Since Rancher does not allow for `--wait`, Rancher returns an error even thought the deployment is `active`.

**Result:**

```
$ rancher app install -n workiva -a helm/sentry/answers/inf-dev.yaml ./helm/sentry sentry
FATA[0149] timed out waiting for app notes, the app could still be installing. Run 'rancher apps' to verify
```

**Other details that may be helpful:**

From the Helm documentation:
```
helm install --help

This command installs a chart archive.

Usage:
  helm install [CHART] [flags]

Flags:
--timeout int              time in seconds to wait for any individual Kubernetes
                           operation (like Jobs for hooks) (default 300)

--wait                     if set, will wait until all Pods, PVCs, Services, and minimum
                           number of Pods of a Deployment are in a ready state before
                           marking the release as successful. It will wait for as long as
                           --timeout
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, 16 cores/64GiB RAM
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
$ docker info
Containers: 30
 Running: 0
 Paused: 0
 Stopped: 30
Images: 132
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: QLPR:76HS:XCEP:FU5G:T5ZO:J3IJ:677C:KRQV:57UY:OIB2:MYMV:YFTF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 50
 System Time: 2019-01-17T20:51:08.719624987Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by rmweir** [comment]
@nickolaskraus-wf have you tried this using a newer version of the CLI? I change was made involving timeout around the time of this issue, and I see you are using the version prior to the change: https://github.com/rancher/rancher/issues/16201

**Comment by rmweir** [comment]
@cjellick @deniseschannon regardless, we do use a default timeout of 2 minutes, and could add a flag so it is configurable.

**Comment by rmweir** [comment]
after looking into it further, we do need to pass these flags to helm. After speaking to @dramich and @vincent99 it makes sense to remove the current timeout we use in rancher. If the user would like the cli to hang while waiting for an app, they can use the usual wait command that works one would use for clusters or projects. Rancher will now have --wait and --timeout flags. To test, enable helm stable catalog. On new release and previous attempt to install sentry with "app install sentry". After fix, the cli should not hang. Next, use app install --wait --timeout 5, the install should fail quickly, then try app install --wait --timeout 600. This may  fail to to lack of config but will at least try for 10 minutes before failing, when the default is to fail after 5 minutes.

**Comment by dramich** [comment]
Available in v2.3.0-rc3

**Comment by sowmyav27** [comment]
### reproduced the issue in v2.2.7
**Steps:**

- Deploy an rke cluster in 2.2.7
- Enable helm stable catalog.
- Through Rancher CLI, `app install sentry`
- Cli hangs and error is seen -``
```
./rancher app install sentry
FATA[0124] timed out waiting for app to install. Run 'rancher apps' to verify status 
```
Error is seen on the UI--apps after sometime. `Failed to install app a-cpds9. Error: timed out waiting for the condition`

### Validated on cli version - `rancher version v2.3.0-rc3`

- Deploy an rke cluster on rancher:master - latest
- Enable helm stable catalog.

**Scenario#1**
Through Rancher CLI, `app install sentry`
CLI does not hang.
```
./rancher apps install sentry
run "app show-notes a-t2t5p" to view app notes once app is ready
```
app install --help lists `--wait` and `--timeout value` as OPTIONS
```
Options:
   --answers value, -a value    Path to an answers file, the format of the file is a map with key:value. This supports JSON and YAML.
   --values value               Path to a helm values file.
   --namespace value, -n value  Namespace to install the app into
   --set value                  Set answers for the template, can be used multiple times. Example: --set foo=bar
   --version value              Version of the template to use
   --no-prompt                  Suppress asking questions and use the default values when required answers are not provided
   --timeout value              Amount of time to wait for k8s commands (default is 300 secs). Example: --timeout 600 (default: 300)
   --wait                       Wait, as long as timeout value, for installed resources to be ready (pods, PVCs, deployments, etc.). Example: --wait
```

**Scenario#2**
 on  running this command - the app fails immediately and you can see the error message on the UI (seen in `installing` state with red background)
```
./rancher app install sentry --wait --timeout 5
run "app show-notes a-dqrww" to view app notes once app is ready
```
**Error:**
`Failed to install app a-dqrww. Error: release a-dqrww failed: timed out waiting for the condition`

**Scenario#3**
On running this command, the app is deployed.
```
./rancher app install sentry --wait --timeout 600
run "app show-notes a-z7rlb" to view app notes once app is ready
```
The app is seen in `installing` status with a blue background. 
It fails with an error on the UI - `Failed to install app a-z7rlb. Error: release a-z7rlb failed: timed out waiting for the condition` in 10 minutes. App will be seen in `installing` state with red background.

**Comment by sowmyav27** [comment]
Waiting for feedback from @cjellick to close this issue

**Comment by cjellick** [comment]
leaving in "To Test". I will get to it probably tomorrow

**Comment by sowmyav27** [comment]
**Multicluster app**

`./rancher mcapp install --help` lists 
```
...
  # Block cli until installation has finished or encountered an error. Use after multiclusterapp install.
  $ rancher wait <multiclusterapp-id>

.....

 --helm-timeout value            Amount of time for helm to wait for k8s commands (default is 300 secs). Example: --helm-timeout 600 (default: 300)
   --helm-wait                     Helm will wait for as long as timeout value, for installed resources to be ready (pods, PVCs, deployments, etc.). Example: --helm-wait
```

` ./rancher multiclusterapps install sentry`, CLI does not hang.
```
$./rancher multiclusterapps install sentry
Installing multi-cluster app ""...
```
`rancher multiclusterapps install sentry ` does not show the app name being installed. Logged bug for this -- https://github.com/rancher/rancher/issues/22527
```
$ ./rancher multiclusterapps install sentry 
Installing multi-cluster app ""...

```
