### ISSUE TITLE
Kubelet stopped posting node status

### ISSUE THREAD

**Issue by grcann101** [rancher/rancher#17486]
One node in the cluster is experiencing errors and dropping out of the cluster.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`containers.index`|

kubectl logs metrics-server-97bc649d5-6prqn   --namespace kube-system

E0120 19:35:05.000293       1 summary.go:374] Node 10.202.102.13 is not ready
E0120 19:35:12.527037       1 summary.go:97] error while getting metrics summary from Kubelet 10.202.102.13(10.202.102.13:10250): Get https://10.202.102.13:10250/stats
/summary/: dial tcp 10.202.102.13:10250: getsockopt: connection timed out
W0120 19:35:12.527084       1 manager.go:102] Failed to get kubelet_summary:10.202.102.13:10250 response in time
E0120 19:36:05.000291       1 summary.go:374] Node 10.202.102.13 is not ready

**Comment by superseb** [comment]
Please describe the situation in detail as requested in the issue template and described on https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions.

The log from the metrics servers shows it can't reach the kubelet to gather metrics, which makes sense as the kubelet seems to be down. The best place to look is in the kubelet container on the node that is reporting to be down (`docker logs kubelet`).

**Comment by grcann101** [comment]
Kubelet Version v1.11.3
Kube Proxy Version v1.11.3
Docker Version 17.3.2
Kernel Version 4.14.32-rancher2
Operating System RancherOS v1.4.0
Created 10/24/2018

Component | Version
-- | --
Rancher | v2.0.8
User Interface | v2.0.67
Helm | v2.9.1-rancher1
Machine | v0.15.0-rancher1-1
