### ISSUE TITLE
multi-cluster app stuck in installing state

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17483]
**Rancher version**
master 1/20

**Steps to reproduce**
1. install a mysql multiclusterapp to the default project, use default answers. e.g.:
```
PROJECT_ID="c-xxx:-xxx"
ACCESS_TOKEN="xxx:xxx"
RANCHER_HOST="x.x.x.x"
curl -k -u "${ACCESS_TOKEN}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"revisionHistoryLimit":10,"type":"multiclusterapp","answers":[{"type":"answer","clusterId":null,"projectId":null,"values":{"defaultImage":"true","image":"mysql","imageTag":"5.7.14","mysqlDatabase":"admin","mysqlUser":"admin","mysqlPassword":"","persistence.enabled":"false","persistence.size":"8Gi","persistence.storageClass":"","service.port":"3306","service.type":"ClusterIP","service.nodePort":""}}],"catalogId":"library","targets":[{"type":"target","projectId":"'${PROJECT_ID}'"}],"templateVersionId":"cattle-global-data:library-mysql-0.3.8","name":"mysql"}' \
"https://${RANCHER_HOST}/v3/multiclusterapps"
```
2. wait until the app in the project becomes active, check mcapp's state

**Result**
It stays in `installing` state.

**Expected Result**
It goes to `active`

**Comment by gitlawr** [comment]
1. On fresh install, mcapp can randomly be in `deploying` state now, although underlying app is active.
![image](https://user-images.githubusercontent.com/5697937/51659165-bfa86700-1fe4-11e9-8b8d-95cdea5aebde.png)
![image](https://user-images.githubusercontent.com/5697937/51659178-c6cf7500-1fe4-11e9-816f-3e08b8ff1ead.png)
2. On upgrade(By editing answers of an active mcapp), it can randomly be in `installing` state.
![image](https://user-images.githubusercontent.com/5697937/51659525-bec40500-1fe5-11e9-9086-61c766645119.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master 1/30

I have not been able to reproduce this -- have deployed ~10 multicluster across the following scenarios:

* Single target in one cluster
* Multiple targets in one cluster
* Single target in each of multiple clusters
* Multiple targets in each of multiple clusters
* Upgrading existing multicluster app

In every case the multicluster app went to `active`.
