### ISSUE TITLE
multi-cluster app: Failed to do rollback

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17485]
**Rancher Version**
master 1/20

**Steps to reproduce (least amount of steps as possible):**
1. Deploy a mysql multiclusterapp to Default project, use default answers.
2. Edit the mcapp via API UI, change `mysqlPassword` to a new value. send the request to do the upgrade.
3. Click rollback action in API UI, choose a previous multiClusterAppRevision. Send the request

**Result:**
Got a 500 server error
![image](https://user-images.githubusercontent.com/5697937/51464248-14a76b80-1da0-11e9-811c-5eaae8b1a337.png)

**Comment by kinarashah** [comment]
@gitlawr I'll put in a pr, but for temporary workaround (just so you're not blocked) - you can call the action with only the name, not `namespace:name`.

**Comment by gitlawr** [comment]
Base on master 1/23:

I can do rollback action successfully and the mcapp is updated to specific version.
However, the underlying app is not updated accordingly(answers in this case).

It's also rollback related but a different symptom from the original one. Please let me know if you want to track it as a new issue.

**Comment by kinarashah** [comment]
I think we can use the same issue @gitlawr, 
- did the answers on multi cluster app get updated? 
- was a new revision created under `multiclusterapp/revisions`?

**Comment by gitlawr** [comment]
1. answers on mcapp get updated.
2. a new revision is created.

 It is not consistently reproducible. I tried 8 revisions until the inconsistency occurs this time.
![image](https://user-images.githubusercontent.com/5697937/51722362-15861900-2090-11e9-8362-70dfe7ac1fde.png)
![image](https://user-images.githubusercontent.com/5697937/51722375-2040ae00-2090-11e9-94ab-c8c0b5e39913.png)

**Comment by kinarashah** [comment]
@gitlawr I tried it a lot of times, but still haven't been able to reproduce this behavior. Do you still see it frequently? 

@bmdepesa can you keep an eye out for this use case when testing multi cluster apps? would like to see the setup when this happens

**Comment by bmdepesa** [comment]
I have not yet been able to reproduce this, but will leave it open for now while continuing MCA testing.

**Comment by gitlawr** [comment]
On master 1/31
I am not able to reproduce this as well
