### ISSUE TITLE
Canary deployment is possible on Rancher 2.0?

### ISSUE THREAD

**Issue by cayohollanda** [rancher/rancher#17481]
Searching on the internet, im not have success to find a way to do the canary deployment on **Rancher 2.0**, its possible?

**Comment by hwaastad** [comment]
Without a service mesh (ex istio), you can do ingress by selectors. (ex scale v1 of app as 10 and scale v2 of app as 1....)

**Comment by cayohollanda** [comment]
In Rancher 1.6, we do canary with HAProxy, on haproxy.cfg, we consider up HAProxy was a default ingress on Rancher 2.0, what do you think about this?

**Comment by loganhz** [comment]
Nginx ingress supports https://www.elvinefendi.com/2018/11/25/canary-deployment-with-ingress-nginx.html

You can also use istio and other service mesh tools for it. 

Close in favor of https://github.com/rancher/rancher/issues/19582
