### ISSUE TITLE
Purge task gets created for the removed resources several times in a row in overloaded systems

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17482]
In 1.6 every minute we create purge for all resources in removed state.  If those purge tasks get queued or stuck we schedule new ones one minute later. The bug is usually observed on overloaded systems.
The fix could be - check if the task already exists in a `project_instance` table before creating a new one.

cc @ibuildthecloud

**Comment by alena1108** [comment]
Workaround: if you have tons of Purge task you can just straight up delete them from process_instance table with no harm.  They will be recreated if needed

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
