### ISSUE TITLE
Failure mounting iso when starting rancher using vagrant on OS X

### ISSUE THREAD

**Issue by ahmedomarjee** [rancher/rancher#1748]
Bringing machine 'rancher-server' up with 'virtualbox' provider...
==> rancher-server: Importing base box 'rancherio/rancheros'...
==> rancher-server: Matching MAC address for NAT networking...
==> rancher-server: Checking if box 'rancherio/rancheros' is up to date...
==> rancher-server: Setting the name of the VM: rancher_rancher-server_1438874432037_97611
==> rancher-server: Clearing any previously set network interfaces...
==> rancher-server: Preparing network interfaces based on configuration...
    rancher-server: Adapter 1: nat
    rancher-server: Adapter 2: hostonly
==> rancher-server: Forwarding ports...
    rancher-server: 8080 => 8080 (adapter 1)
    rancher-server: 22 => 2222 (adapter 1)
==> rancher-server: Running 'pre-boot' VM customizations...
==> rancher-server: Booting VM...
==> rancher-server: Waiting for machine to boot. This may take a few minutes...
    rancher-server: SSH address: 127.0.0.1:2222
    rancher-server: SSH username: rancher
    rancher-server: SSH auth method: private key
    rancher-server: Warning: Connection timeout. Retrying...
    rancher-server: Warning: Remote connection disconnect. Retrying...
    rancher-server: Warning: Remote connection disconnect. Retrying...
    rancher-server: Warning: Remote connection disconnect. Retrying...
    rancher-server: 
    rancher-server: Vagrant insecure key detected. Vagrant will automatically replace
    rancher-server: this with a newly generated keypair for better security.
    rancher-server: 
    rancher-server: Inserting generated public key within guest...
    rancher-server: Removing insecure key from the guest if it's present...
    rancher-server: Key inserted! Disconnecting and reconnecting using new SSH key...
==> rancher-server: Machine booted and ready!
No installation found.
The guest's platform is currently not supported, will try generic Linux method...
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: mounting ?~6?E on /mnt failed: Invalid argument
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount /tmp/VBoxGuestAdditions.iso -o loop /mnt

Stdout from the command:

Stderr from the command:

mount: mounting ?~6?E on /mnt failed: Invalid argument

**Comment by cloudnautique** [comment]
Hmm... are you using the vbguest plugin? I'm surprised that it fails at this part.. I would expect it to copy and fail during the installation. :) 

Can you try adding:
config.vbguest.auto_update = false

to the virtualbox provider config block starting at line 26 in the Vagrant file? We haven't gotten to the point where we support the VBoxGuest additions in RancherOS.

**Comment by deniseschannon** [comment]
@ahmedomarjee Were you able to try @cloudnautique's suggestions to see if that helps? If you are still having issues, please let us know. Otherwise I will close this in the next couple of days.

**Comment by ahmedomarjee** [comment]
Thanks it did work.

**Comment by manishmj07** [comment]
> @ahmedomarjee Were you able to try @cloudnautique's suggestions to see if that helps? If you are still having issues, please let us know. Otherwise I will close this in the next couple of days.

@deniseschannon, I have been using Oracle VM, Vagrant on Windows 10, added the suggested line in 'Vagrantfile', however, still I am getting error as :

default: No guest additions were detected on the base box for this VM! Guest
default: additions are required for forwarded ports, shared folders, host only
default: networking, and more. If SSH fails on this machine, please install
default: the guest additions and repackage the box to continue.

Thanks,
Samir Sinha
