### ISSUE TITLE
Settings that were set via environment variables should no be updatable

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#17488]
While addressing https://github.com/rancher/rancher/issues/14392 and https://github.com/rancher/rancher/issues/17312, we introduced functionality to make the API more accurately reflect the state of settings in rancher.

Rancher has always functioned such that settings that were set as environment variables could not be updated via the API. However, they were just silently ignored when updated via the API. Now, if the setting was set via an env var, the update link will be removed from the resource in the UI and an error will be returned if a user attempts to update the setting.

**Comment by cjellick** [comment]
moved this back to dev bc the PR had to be reverted

**Comment by sangeethah** [comment]
Tested with latest build from master:
Tried to update the setting - `helm-version` and get the following error as expected:

```{"baseType":"error","code":"MethodNotAllow","message":"helm-version is readOnly because its value is from environment variable","status":405,"type":"error"}```
