### ISSUE TITLE
Unable to remove cluster that was created with example pluggable driver

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17495]
Version: master 2.2 (1/21/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add our example custom cluster driver: https://github.com/rancher/kontainer-engine-driver-example/releases/download/v0.2.0/kontainer-engine-driver-example-linux (or latest release)
- Note, you will need the ui-cluster-driver-skel deployed on your local machine you are testing with. Use the [google-gke-example](https://github.com/rancher/ui-cluster-driver-skel/tree/google-gke-example) branch.
- Create a cluster using the example driver. Wait for it to fully provision. Now try to delete it and this will never succeed. 

**Result:**
You will see the following:
UI:
`No kontainer driver for cluster david-gke-example; waiting on cluster-provisioner-controller`
Rancher server logs:
`2019/01/21 18:33:23 [ERROR] ClusterController c-4m8gh [cluster-provisioner-controller] failed with : failed to remove the cluster [c-4m8gh]: no kontainer driver for cluster david-gke-example`
Full log (tried to remove cluster @ 2019/01/21 18:33:19)
[pluggable-driver-issue.txt](https://github.com/rancher/rancher/files/2780248/pluggable-driver-issue.txt)

**Other details that may be helpful:**
Single rancher server install w/ supported docker and ubuntu

**Comment by nathan-jenan-rancher** [comment]
Unable to reproduce.  Possibly related to using an old version of the example driver?  Please re-test.

**Comment by davidnuzik** [comment]
@nathan-jenan-rancher what I see when I try to use updated v0.2.1 is that the url is wrong? per the steps to test this I just need to plug in path to binary directly:
https://github.com/rancher/kontainer-engine-driver-example/releases/download/v0.2.1/kontainer-engine-driver-example-linux

`2019/02/05 17:50:59 [INFO] Download https://github.com/rancher/kontainer-engine-driver-example/releases/download/v0.2.1/kontainer-engine-driver-example-linux                                                                              
2019/02/05 17:51:10 [ERROR] NodeDriverController nd-7mkkr [node-driver-controller] failed with : invalid URL https://github.com/rancher/kontainer-engine-driver-example/releases/download/v0.2.1/kontainer-engine-driver-example-linux, path should be of the format docker-machine-driver-*
2019/02/05 17:51:10 [ERROR] Returning previous error: invalid URL https://github.com/rancher/kontainer-engine-driver-example/releases/download/v0.2.1/kontainer-engine-driver-example-linux, path should be of the format docker-machine-driver-*
`

**Comment by davidnuzik** [comment]
Note: backend looks good now, successfully create and update the pluggable kontainerdriver.
Next step is UI skeleton for testing; having a bit of a hard time getting this to work (nodeJS setup, etc, etc); will ask for help if cannot get this going by tomorrow.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/6/19)
Confirmed fixed. I am no longer able to reproduce with v0.2.1 of kontainer-engine-driver-example
I successfully used the pluggable driver with example UI and provisioned a GKS cluster using it. I lightly smoke tested this by deploying a workload, etc. I did not observe any issues. I was successfully able to remove the cluster when done testing.
