### ISSUE TITLE
Possible memory leak in Rancher server

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1749]
I have been running rancher server in a EC2 micro instance (1GB memory) for a while. Was repeatedly running some automated tests that add/delete hosts, services etc. Now, host addition is failing and on further triage, noticed that there are docker-machine defunct processes hanging around and memory usage is stuck at > 80% even when there are no user actions.

time="2015-08-06T17:48:17Z" level=error msg="Error processing event" err="fork/exec /usr/bin/docker-machine: cannot allocate memory" eventId="3c869c43-f404-4223-97d1-321a1288de65" eventName="physicalhost.create;handler=goMachineService" resourceId=1ph50

root     14259 13980  0 07:42 ?        00:00:00 [docker-machine] <defunct>
root     14260 13980  0 07:42 ?        00:00:00 [docker-machine] <defunct>
root     14280 13980  0 07:42 ?        00:00:00 [docker-machine] <defunct>
root     14302 13980  0 07:43 ?        00:00:00 [docker-machine] <defunct>
root     14327 13980  0 07:44 ?        00:00:00 [docker-machine] <defunct>
root     15494 13980  0 17:22 ?        00:00:00 [docker-machine] <defunct>

![image](https://cloud.githubusercontent.com/assets/7720752/9121300/4924e828-3c36-11e5-9bdc-504dc980fc55.png)

Few issues:
1. If Rancher server needs to run on a host with certain memory size, it can be documented
2. Need a proper error message instead of "exit status 2"
3. Check for potential memory leak in the server.

**Comment by dsvmacdonald** [comment]
I have experienced this issue too on v0.47.0.  Unable to add any hosts to Digital Ocean.  Had to reinstall Rancher to fix.

**Comment by will-chan** [comment]
closed as obsolete.
