### ISSUE TITLE
Restrain API keys scope in rancher 2

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#17496]
**Request type**

This is a feature request.

** Context **
Our rancher 2 HA installation is now used in production to manage a dozen of various clusters for our clients infrastructures.

We use Rancher CLI to manage common tasks from our CI, and to be able to do that we created API keys.

** Motivation **
The problem is API keys are not scoped to any cluster or project. They are kind of global.

A way to **scope API keys to a certain cluster** or to a project withing a cluster, for example would be a great benefit in order to properly avoid to have too large rights.

**Comment by vincent99** [comment]
This is in 2.2.
