### ISSUE TITLE
Add Service should be disabled when there is no valid host or introduce a timeout

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1750]
User is able to add a service even there is no valid host. In this case, wile starting container, it is stuck in "creating" for ever. Either "Add service" should be disabled in UI when there is no host or timeout at API/UI when a user is trying to add a service/container without a valid host being added first.

**Comment by deniseschannon** [comment]
This is similar to https://github.com/rancher/rancher/issues/249 except related to services.

**Comment by deniseschannon** [comment]
Consolidating to #249
