### ISSUE TITLE
"Backup now" operation on a cluster should provide info to the user that a backup was performed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17504]
Version: Master
Steps:
1. Create a DO cluster with S3 configuration 
2. Click on edit cluster and perform "Backup now"
3. Backup is performed which can be observed in S3 and also
https://testabc/v3/clusters/c-8hddb/etcdbackups      

There is no information to the user that a backup actually happened.
User feedback must be provided that a backup was performed with the pointer to where they can find it.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/30/19)
The UI now shows a green balloon pop-up indicating the backup was successful. Validated HTTP/API.
Smoke tested backups/restore functionality as well with local and s3.
![image](https://user-images.githubusercontent.com/45179589/52016631-53c17500-24a2-11e9-8f42-12a0a17191d2.png)
