### ISSUE TITLE
[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [192.168.2.27]: Get https://localhost:6443/healthz: read tcp [::1]:54386->[::1]:6443: read: connection reset by peer, log: I0122 03:02:45.241013 1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.

### ISSUE THREAD

**Issue by zhengll0514** [rancher/rancher#17506]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Can you supply more info on your setup, please? (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

There is even no reproduce steps and no rancher version in your issue.  Please create a new issue if you have the required information for an issue
