### ISSUE TITLE
rancher agent lead to kubernetes failure

### ISSUE THREAD

**Issue by INT-ZC** [rancher/rancher#17515]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
```sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.11 http://<ip-address>:8080/v1/scripts/<token>```

**Result:**
The output of kubelet get pods (or any other thing) would return:
```The connection to the server <ip-address>:6443 was refused - did you specify the right host or port?```

**Other details that may be helpful:**
It is a single node machine running Ubuntu Server 16.04, Docker 18.06.0, and Kubernetes 1.13.2
Both rancher/server and rancher/rancher are running
After the running of the rancher-agent, k8s_POD_kube-controller-manager-<token>, k8s_POD_kube-flannel-ds-amd64-pqpbw_kube-system_<token>, k8s_POD_etcd-<token>, k8s_POD_kube-scheduler-<token>, k8s_POD_kube-proxy-<token>, k8s_POD_kube-apiserver-<token> docker started to restarting. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 1.6.25 (2.1.5 for rancher/rancher)
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): local, 1 CPU with 8 cores, 16GB memory
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server <ip-address>:6443 was refused - did you specify the right host or port?
```

- Docker (use `docker info`):

```
Containers: 87
 Running: 29
 Paused: 0
 Stopped: 58
Images: 30
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-131-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.62GiB
Name: smartedu
ID: IZC3:WGQB:PXIP:UURJ:CU2Z:ZXGG:RIJE:7AU4:MVIJ:AC3J:NC5B:COUP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by INT-ZC** [comment]
Tried again and failed again. 
Does rancher request a specific way to install kubernetes?

**Comment by superseb** [comment]
Can you please provide exact steps to reproduce? `rancher/server` is 1.6, `rancher/rancher` is 2.x. Both installs and usage are documented at https://rancher.com/docs/, can you describe what you are trying to use and provide steps to reproduce?
