### ISSUE TITLE
[UI] Syntax issue -> typo pileine

### ISSUE THREAD

**Issue by wrogrammer** [rancher/rancher#17513]
https://github.com/rancher/ui/blob/master/lib/pipeline/translations/en-us.yaml#L368

What kind of request is this (question/bug/enhancement/feature request):
Syntax issue.

Result:
```
Currently:
The detailed log of the current pileine run.

Should be:
The detailed log of the current pipeline run.
```

**Comment by wrogrammer** [comment]
PR:

https://github.com/rancher/ui/pull/2578

**Comment by wrogrammer** [comment]
Can be closed.

**Comment by loganhz** [comment]
Thanks!
