### ISSUE TITLE
vSphere provisionned cluster failed

### ISSUE THREAD

**Issue by NicolasDEVOUGE** [rancher/rancher#17512]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Create cluster provisionned by vSphere

**Result:**

Error : 

2019/01/22 10:22:34 [ERROR] NodeController c-nnpsb/m-md7zs [node-controller] failed with : Error with pre-create check: "Post https://192.168.70.10:443/sdk: dial tcp 192.168.70.10:443: i/o timeout"
2019/01/22 10:22:34 [ERROR] NodeController c-nnpsb/m-5vg89 [node-controller] failed with : Error with pre-create check: "Post https://192.168.70.10:443/sdk: dial tcp 192.168.70.10:443: i/o timeout"
2019/01/22 10:22:34 [ERROR] NodeController c-nnpsb/m-wm49m [node-controller] failed with : Error with pre-create check: "Post https://192.168.70.10:443/sdk: dial tcp 192.168.70.10:443: i/o timeout"

**Other details that may be helpful:**

I have followed the assistant, no specific configuration

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere 6.7.0
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM (2 cpu, 4096 RAM)
- Kubernetes version (use `kubectl version`): no (docker compose image)

```
(paste the output here)
```

- Docker (use `docker info`):
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.853GiB
Name: tpl-ubuntu-18-04
ID: ZQJC:OYDO:IUV5:FF7B:GWO5:6BXE:YTSH:M3GX:YRBK:H2HI:KCO3:KEDG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
(paste the output here)
```

**Comment by hackman61** [comment]
Here is the Cluster yml file that I use : 

cloud_provider: 
  name: "vsphere"
  vsphereCloudProvider: 
    global: 
      insecure-flag: true
      soap-roundtrip-count: 0
    virtual_center: 
      vcenter-01.domoce.local: 
        datacenters: "AZNetwork-Alencon"
        password: "mypassword"
        soap-roundtrip-count: 0
        user: "rancher"
    workspace: 
      datacenter: "AZNetwork-Alencon"
      default-datastore: "Datastore_R10"
      folder: "tests"
      server: "vcenter-01.domoce.local"
ignore_docker_version: true
addon_job_timeout: 30
authentication: 
  strategy: "x509"
bastion_host: 
  ssh_agent_auth: false
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "nginx"
kubernetes_version: "v1.11.6-rancher1-1"
monitoring: 
  provider: "metrics-server"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
network: 
  options: 
    flannel_backend_type: "vxlan"
  plugin: "canal"
# 
#      services:
#        kube_api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube_controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
services: 
  etcd: 
    creation: "12h"
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    retention: "72h"
    snapshot: true
  kube-api: 
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kubelet: 
    fail_swap_on: false
ssh_agent_auth: false

**Comment by hackman61** [comment]
I have tested with Rancher 2.1.4, same problem, I think Rancher cannot access to https://vcenter-01.domoce.local:443/sdk, can you explain me how it is implemented ?  Because in vsphere appliance 6.7.0, this URL can't be acceded, we must add /vimService.wsdl .

**Comment by JerryCurl** [comment]
same issue here.  on-prem vcenter using appliances (that need /vimService.wsdl).  Cannot deploy cluster with 404 errors

**Comment by aledr** [comment]
Is there any workaround available for vSphere 6.7?

**Comment by Aaron-ML** [comment]
I'm also seeing this issue.

**Comment by hbowron** [comment]
Any update on this?  Does this mean Rancher is unable to provision clusters whatsoever on vSphere 6.7?  This [issue](https://github.com/rancher/rancher/issues/24568) seems to indicate cluster creation is possible on v6.7 but I don't see how with this open issue.
