### ISSUE TITLE
UI - input-slider component throwing errors

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17522]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
The input slider used in the template in rancher/rancher#15444 or the alerts functionality to bring up a view that uses the `input-slider` component.

**Result:**
A console error regarding setting the `elementId` after initialization is thrown.
If using the node template provided in the issue referenced above, you'll see the slider doesn't even work slide with no errors being reproduced.

**Other details that may be helpful:**

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/31
Verified fixed
