### ISSUE TITLE
Kubectl shell breaks after etcdbackup restore

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#17521]
master (22/01)

After restoring a cluster from backup kubectl shell fails with this error:
```
Unable to connect to the server: x509: certificate signed by unknown authority
```

**Comment by moelsayed** [comment]
reverted fix in https://github.com/rancher/kontainer-engine/pull/124

**Comment by soumyalj** [comment]
Tested with master build from Feb 12th. 
Steps:
* Create a 3 node cluster with all 3 roles
* Create few workloads. Verify kubectl is functional
* Create a backup.
* Local backup succeeds.
* Perform a restore.
After restore, launch kubectl from UI. kubectl is functional. 
```
> kubectl get node
NAME                 STATUS    ROLES                      AGE       VERSION
soumyakubectltest1   Ready     controlplane,etcd,worker   41m       v1.13.1
soumyakubectltest2   Ready     controlplane,etcd,worker   41m       v1.13.1
soumyakubectltest3   Ready     controlplane,etcd,worker   41m       v1.13.1


```
