### ISSUE TITLE
API Token Does Not Retain clusterId Field When Set

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17526]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Using the API UI create a new token
Ensure that a clusterId is set
Save and create token

**Result:**
The newly created token should have the same clusterId field but it returns as `null`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Master (01/22/19)
- Installation option (single install/HA):
Single

**Comment by cjellick** [comment]
@westlywright was this blocking anything in the UI?

**Comment by westlywright** [comment]
@cjellick no, the UI is in as it does not throw any errors from the front-end.

**Comment by sangeethah** [comment]
Tested with latest build from master.

Create a token with cluster scope.

Once token is created , clusterId field of the token has clusterId set.
