### ISSUE TITLE
When restart is set to "no", stopping and starting services , results in all the containers to remain in "stopped" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1752]
Server version - v0.32.0-rc1

Steps to reproduce the problem:
Create a service with  restart is set to "no" and scale to 3.
Stop service.
This results in all containers in the service to be stopped.
Start service.
All containers continue to remain in "stopped" state.

Expected behavior:
As part of service activation , all containers should get to "running" state.

Also scale up , does not result in stopped containers to be started.

**Comment by alena1108** [comment]
This bug is no longer relevant as we don't use this parameter to identify createOnly containers. Would still be worth to validate that restartPolicy=no doesn't break service.deactivate/activate functionality.

**Comment by sangeethah** [comment]
Tested with server version built from master - sep 8
When restart is set to "no", stopping and starting services , results in all the containers be stopped and then started successfully.
