### ISSUE TITLE
UI - Ingress editor breaks rule paths ordering

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17529]
UI for https://github.com/rancher/rancher/issues/17065

**Comment by cjellick** [comment]
@loganhz @westlywright please coordinate with me when you are ready to merge this. The backend is ready to merge but it has an api change that breaks the UI. So, I want to coordinate merging back and front near simultaneously.

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/28
Verified fixed
