### ISSUE TITLE
Global DNS UI: Cannot edit the name of DNS Providers

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17528]
Version: master 2.2 (1/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add a Global DNS Provider
- Try to edit it and simply change the name to something new. Click create
- Try to edit a Global DNS Entry. Notice the listing does not change until you refresh (table).

**Result:**
The PUT does go through and everything looks correct except for the Name you cannot modify the name. In the PUT request payload we still have our old name even if we changed it in the UI.
This issue does not affect the Root Domain or AWS credentials - those work.

**Other details that may be helpful:**
HA rancher setup on supported Ubuntu and Docker running HELM alpha chart as this is closest to master currently. imageTag: Master

**Comment by westlywright** [comment]
@davidnuzik you can not edit the name of a Global DNS provider. If you look at the schema via the API UI `/v3/schemas/globaldnsprovider` the name field is set to `update: false`.

**Comment by alena1108** [comment]
@prachidamle is there a reason for `globalDNS.name` not being updatable?

**Comment by prachidamle** [comment]
The reason is that DNSProvider's name is used to generate the name of the actual K8s deployment running the external-dns image. So to reference the deployment back, we use the DNSProvider's name.
It should be non-editable.

**Comment by davidnuzik** [comment]
@alena1108 @prachidamle @westlywright if it is not editable then I should not be allowed to edit it in the UI. The field needs to be grayed out when I try to edit the entry.

**Comment by davidnuzik** [comment]
Something changed in the UI and this field is no longer editable. Both Tani and I could edit this before on Wednesday. Will keep an eye open to see if something changes again (maybe something changed in API or something at some point?)
![image](https://user-images.githubusercontent.com/45179589/51773290-9b638d80-20ab-11e9-8ea5-30ce75acdd55.png)

**Comment by davidnuzik** [comment]
Closing issue; name field is no longer editable. Further testing in this area will continue. This might have changed due to fixes in related bugs reported too.
