### ISSUE TITLE
Service proxy endpoint doesn't work in master 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17530]
rancher/rancher:master

Steps:

1. Deploy k8s dashboard
2. Click the index.html link in catalog app

Result:

The link doesn't work.

Expected:

it should jump to the dashboard ui page

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/30/19)
Confirmed fix. When I follow the steps to reproduce the index.html link now works; the endpoint appears correct. Example: https://<RancherServer>/k8s/clusters/c-25hs9/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:443/proxy/
Smoke tested, checked service details, etc.
