### ISSUE TITLE
Inherit the advanced options for alert rule from the alert group

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#17538]
**What kind of request is this (question/bug/enhancement/feature request):**
UX

**Steps to reproduce (least amount of steps as possible):**

1. Add an alert group and include two alert rules. 
2. Modify advanced options for alert group. 
3. Check advanced options under Alert Groups and Alert Rules

**Result:**

1. The advanced option of the alert rule is still the default value, and the alert group is not inherited.
Need to modify the advanced options of the alert group again. In this way, the alert message can be sent according to the custom time.
2. Similarly, editing the advanced options of the alert group has no meaning for the alert rules.

In order to avoid the above problems, it is best to remove the advanced options of the alert group.

**version:** 
rancher/rancehr:master

**Comment by aiwantaozi** [comment]
Hi @rootwuj we want to keep this, but add ```inherit advance option``` from alert group in the alert rule as the default value. If you change the advance in the alert group level, the inherit alert rule will also use the latest one.

**Comment by rootwuj** [comment]
Version: master 2.2 (3/5/19) Image ID: 62b73e8b4ba8
Confirmed fixed.

1. Enable `Inheriting the advanced options from group` at cluster/project level.
* The added alert can inherit the rules of the alert group.
* Modify the alert group rules. The alert rules will be modified synchronously.

2. Disable `Inheriting the advanced options from group` at cluster/project level.
* The added alert does not inherit the rules of the alert group.
* Modify the alert group rules. The alert rules are unchanged.
