### ISSUE TITLE
Make k8s 1.13 default version when deploying RKE clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17532]
Make k8s 1.13 default version when deploying RKE clusters.

**Comment by jiaqiluo** [comment]
Failed to validate the issue on Rancher: master 1/28
When Adding a new RKE cluster, in my case a DO cluster, the default k8s version is 1.11.6.
![screenshot](https://user-images.githubusercontent.com/6218999/51867319-80da2000-2308-11e9-8324-6fa320f6d44a.png)

**Comment by alena1108** [comment]
@cjellick rke/types have been addressed to use k8s 1.13 as default. Rancher side needs to be fixed to display the right defaults, most likely in https://github.com/rancher/rancher/pull/16880/files#diff-8cae2b257a070262d733c79cc16f917bR46

**Comment by jiaqiluo** [comment]
The enhancement is validated on Rancher: master 1/28.

Validateion 1: the default k8s version is 1.13 when adding a new RKE cluster
Validateion 2: the DO cluster runs up successfully with default settings
