### ISSUE TITLE
UI for new docker versions in the node template dropdown

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#17547]
I've changed the setting to have 18.06 as the default, but we need to add it, 17.06, and 17.09 to the UI. those are hardcoded in the UI.
Related backend issue: https://github.com/rancher/rancher/issues/15824

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/29/19)
Confirmed enhancement/update. I validated that all the Docker Install URLs were correctly linked to (the URL) and tested with them all on at least one type of provider (DO). The new menu has new options and all they all work.

![image](https://user-images.githubusercontent.com/45179589/51942493-6ff6e080-23d4-11e9-9d26-bf7f6fbc4b1d.png)

I also smoke tested other providers (ec2, etc) to ensure they work such as with latest, Recommended, and v1.13.x, etc. For each, I deployed a simple workload and created an ingress to validate I could reach the application. I also ensured the appropriate docker version was installed (although kubelet doesn't quite report it correctly see below). Further testing with node templates will/is occurring as well.
Confirmed that when we use latest, rancher server logs indicate:
```
2019/01/29 20:22:19 [ERROR] cluster [c-9mzxj] provisioning: Unsupported Docker version found [18.09.1], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x 17.06.x 17.09.x 18.06.x]
```
and subsequently:
```
2019/01/29 20:28:27 [WARNING] Unsupported Docker version found [18.09.1], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x 17.06.x 17.09.x 18.06.x]
```
as expected.
When you edit a cluster and update the template for the nodes the node is not updated; investigating and will enter a bug if necessary.
Discovered kublet incorrectly reports docker version: #17718
