### ISSUE TITLE
Move kube-api-auth image builds to Rancher

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#17544]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Other details that may be helpful:**
In Rancher settings we are using an AuthImage published to an unofficial Dockerhub account:
https://github.com/rancher/rancher/blob/master/pkg/settings/setting.go#L17

This image should be generated & pushed to the Rancher hub account, and the following repo also moved to Rancher github:
https://github.com/erikwilson/rancher-kube-api-auth

**Comment by loganhz** [comment]
repo and image are all under Rancher account now
