### ISSUE TITLE
Answers cannot be reset on app

### ISSUE THREAD

**Issue by kevinsimons-wf** [rancher/rancher#17540]
**What kind of request is this (question/bug/enhancement/feature request):**
question / enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Rancher app install and give it some answer with `--set`
2. Rancher app upgrade and give it a different answer with `--set` and not the first one

**Result:**
You should see that the first answer you gave in step 1 still exists on your application.

**Other details that may be helpful:**
As I was looking into this, I was trying to determine if it was an "issue" with the underlying helm implementation, or with something Rancher has on top of it. 

It looks like Rancher just calls `helm upgrade --install` with no extra flags https://github.com/rancher/rancher/blob/master/pkg/controllers/user/helm/common/common.go#L92

Based on this, I would expect the helm behavior to exist where if you repeat the steps to reproduce but use `helm` instead of `rancher`, then the first value set is not carried over to the second app upgrade. However this is not the case.

So it seems like Rancher may be keeping the information around about the previous passed in answers? However here on the update action https://github.com/rancher/rancher/blob/master/pkg/api/customization/app/app.go#L101 , the answers get cleared into just what is now passed in. So I think it may have to do with wherever this `PUT` request goes https://github.com/rancher/rancher/blob/master/pkg/api/customization/app/app.go#L108 , that may be hanging on to old answers.

I think it would be nice to either follow the `helm` way of values passed into apps, or at least provide a similar flag that `helm` does with a `--reset-values` so that we have some way of upgrading an application and removing old answers passed into old versions.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.5
- Installation option (single install/HA): HA

**Comment by guangbochen** [comment]
The `helm upgrade --install` will reuse existing values if no `--set` or `--values` values have provided,   and it defaults to `--reset-values` if the user has provided new `--set` values, I have tested through both rancher UI or API, it works as expected, can you please help to provide reproducible process, thanks.  cc @alena1108

**Comment by kevinsimons-wf** [comment]
```console
$ rancher --version
rancher version v2.2.0
$ rancher app install --set foo=bar --namespace workiva kevin-test test-upgrade
---
# Source: kevin-test/templates/NOTES.txt
Kevin's Test App
```

Api view shows 
```
answers": {
    "foo": "bar"
},
```

```console
$ rancher app upgrade --set asdf=qwer test-upgrade 0.4.0
```

Api view shows
```
answers": {
    "asdf": "qwer",
    "foo": "bar"
},
```

**Comment by guangbochen** [comment]
Then this should be a bug in the rancher cli, thanks.

**Comment by cjellick** [comment]
waiting on a cli rc

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.0 rancher cli
v2.2.4  Rancher Server

- `rancher app install --set foo=bar --namespace apps docker-registry dockerregname`
- View app in API and it shows "foo": "bar"
- `rancher app upgrade --set asdf=fdsa dockerregname 1.6.1`
- View app in API and it now shows "asdf": "fdsa" AND "foo": "bar"

Expected result was only shows answer "asdf": "fdsa"

**Validation (FAILED):**
v2.3.0-rc1 rancher cli
v2.2.4 Rancher Server

- `rancher app install --set foo=bar --namespace apps2 docker-registry dockerregname2`
- View app in API and it shows "foo": "bar"
- `rancher app upgrade --set asdf=fdsa dockerregname2 1.6.1`
- View app in API and it now shows ONLY "asdf": "fdsa"

- View app in API and it now shows "asdf": "fdsa" AND "foo": "bar"

Expected result was only shows answer "asdf": "fdsa"

**Comment by davidnuzik** [comment]
I am not certain why validation failed. I upgraded from 1.6.1 to 1.6.1 but this should still work --  just like in the UI.

**Comment by rmweir** [comment]
@davidnuzik this is my bad david, I was unclear about the change. I have added a --reset flag that will cause the answers to reset.

**Comment by davidnuzik** [comment]
**Validation now passes:**
(I was not using the --reset flag before)
v2.3.0-rc1 rancher cli

`rancher app install --set foo=bar --namespace apps docker-registry dockerregname`

View app in API and UI and it shows "foo": "bar"

`rancher app upgrade --reset --set asdf=fdsa dockerregname 1.6.1`

View app in API and it now shows ONLY "asdf": "fdsa" (because we supplied the --reset flag)
