### ISSUE TITLE
Global DNS Provider: root domain field should be optional

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17559]
Version: 2.2 master (1/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a DNS Provider. Notice the root domain field. This should not exist our Amazon account could allow us to have multiple root domains.

**Result:**
Root domain field should be removed.

**Comment by alena1108** [comment]
@prachidamle we should put validation on the domain field. I believe we have fqdn type in types/norman

**Comment by prachidamle** [comment]
@davidnuzik what do you mean by "Root domain field should be removed." NOt sure if I understand the concern. Can you explain more please?
The root domain field is an essential input of a DNS Provider config.

**Comment by alena1108** [comment]
@davidnuzik: root domain is required for programming route53 by kubernetes/external-dns. If you need to create an entry for the same api/secret key, but for diff root domain, you'd have to register it as a separate global dns provider.

**Comment by prachidamle** [comment]
@alena1108 @davidnuzik The "domain" is optional input to the kubermetes/external-dns providers. 

```Ref: https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/aws.md
  
      - --domain-filter=external-dns-test.my-org.com # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones ```

Thus we should be keeping this field optional as well and pass it to the external-dns deployment  if user provides it.

**Comment by prachidamle** [comment]
@alena1108 I will update this issue title to reflect the changes we make regarding the "domain" field of globalDNSProvider

**Comment by sangeethah** [comment]
Tested with latest build form master - Feb 26

Set up - Rancher HA setup with 2 user clusters provisioned.

Tested the following p1 workflow for adding and deleting DNS records to AWS Route53 external provider:

1. Create a Global DNS provider - GDNSP1 with NO root domain and valid AWS credentials which has access to 2 Route53 root domains - test1.test.com and test2.test.com
2. Deploy Mcapp - mcapp1 with ingress having Global DNS annotations for host name  say - "hello1.test1.test.com" with target projects from 2 different clusters.
3. Add Global DNS entry for fqdn -"hello1.test1.test.com" pointing to mcapp1 with GDNS provider - GDNSP1.

DNS record for "hello1.test1.test.com" gets created as expected in Route53 with root domain - test1.test.com as expected.

4. Deploy Mcapp - mcapp2 with ingress having Global DNS annotations for host name  say - "hello1.test2.test.com" with target projects from 2 different clusters.
5. Add Global DNS entry for fqdn -"hello1.test2.test.com" pointing to mcapp2 with GDNS provider - GDNSP1.

DNS record for "hello1.test2.test.com" gets created as expected in Route53 with root domain - test2.test.com as expected.

6. Add worker node to clusters were the Multicluster APP is deployed.

DNS records for "hello1.test2.test.com" and "hello1.test1.test.com" get updated with the new worker node ip as expected in Route53 with root domain - test1.test.com and test2.test.com as expected.

7. Delete Global DNS entry for fqdn -"hello1.test2.test.com" .

DNS records for "hello1.test2.test.com" gets deleted from Route53 with root domain - test2.test.com as expected.
