### ISSUE TITLE
UI - When is logging to Kafka going to support sasl/scram-256

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17555]
UI for https://github.com/rancher/rancher/issues/16614

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/30/19)
Validated Kafka sasl/scram-256 support (UI Form). Submitted form with new SASL configuration options. Further testing in this area will happen by the back-end QA team.
![image](https://user-images.githubusercontent.com/45179589/52020391-5f1a9d80-24ae-11e9-8762-c1bc6136c36a.png)

Validated clusterlogging POST req payload and server resp. API appears correct as well. Tested both Plain type and Scram type.
Validated clusterLoggings PUT (edit config) req payload and server resp as well.
