### ISSUE TITLE
Global DNS UI: DNS Provider form is not validated

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17560]
Version: 2.2 master (1/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- You can enter anything or nothing on the global DNS provider form.

**Result:**
Required fields are not required. You can avoid entering amazon credentials and it will still let you create.

**Comment by alena1108** [comment]
@prachidamle have to put required attribute on the fields

**Comment by alena1108** [comment]
@davidnuzik api/secret keys should be required now, can you retest. Note that the fix doesn't include making `rootDomain` non-required field, it will be addressed and tested separately as a part of https://github.com/rancher/rancher/issues/17559

**Comment by davidnuzik** [comment]
@alena1108 thanks for taking a look; however it does not appear to be working for me. I pulled latest and can create a Global DNS Provider entry will out filling any field.
![image](https://user-images.githubusercontent.com/45179589/51927945-006ff980-23b2-11e9-828f-5985ea6bb879.png)
Version: Master 2.2 (1/29/19) ImageID: 980f2aed2232 with clean browser cache

**Comment by davidnuzik** [comment]
@alena1108 fixed. Thanks!
`Validation failed in API: route53ProviderConfig accessKey=NotNullable 422:`

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/30/19)
Confirmed fix. You must supply at least an access key and a secret key to be able to submit the form to create a Global DNS Provider. The error is pretty clear indicating that either field cannot be null.
