### ISSUE TITLE
Validate S3 backup on (non-AWS) S3 compatible provider (Minio)

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17562]
This ticket is to make sure we validate etcd backup/recovery works on non AWS setups. @moelsayed please do the initial validation + put any fixes if needed. Once the happy path works, reassign to qa

**Comment by moelsayed** [comment]
Tested and works fine. Endpoint must be configured with TLS.

**Comment by soumyalj** [comment]
Tested with master build from Feb 21. 
1. Created a 3 node DO cluster providing the configuration for Minio setup. After choosing S3 as the etcd snapshot target, S3 bucket name, access key/ secret key and the endpoint needs to be provided.
2.  After the cluster is created, it was observed that backups were taken at the set interval (1hr) as expected.  Also, one time backup entries were observed in the Minio buckets
3. Restore from these backups were also successful
