### ISSUE TITLE
RBAC changes for Multi Cluster App

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17565]
Following changes are needed for Multi cluster app RBAC based on follow up design discussion with @ibuildthecloud @cjellick and @vincent99 

- [x] everything defined in https://github.com/rancher/rancher/issues/17564
- [x] given the current complexity of userId/creatorId association to MCA and underlying apps, we should do the following:

1) API: Multi cluster app create accepts list of Roles (references to the project roles). On the API we do validation if the person modifying MCA has all these role in the projects. Those roles **are not** the roles assigned to the members. They are the existing roles (role template resources) in the projects.
2) Controller: Underlying controller listening on MCA create/update, would create a serviceAccount (local rancher user with the principalID `system://`, we have an example for that in the code that creates a user for deploying cluster agent) for the MCA, and assigns all the roles from the step 1) to it. For this user we'd create PRTBs based on the roles defined on step 1)
3) Controller: Service account created on step 2) would become a creatorId on the Application
4) API: Whoever modifies []role on MCA, should have this role in every project. Roles can be modified only by members having `all` privilege. Role update is done via MultiClusterApp.Update call where all roles are passed as a set.

**Comment by mrajashree** [comment]
Updated: From yesterday's design discussion

Multilclusterapp
3 roles: owner, member, read-only
Owner: Can modify members, projects and roles list. Owners manage the multiclusterapp config: where it can launch apps, and who can have access to multiclusterapp
Member: Can modify templateVersion and answers. Members manage the config of the app instances which are launched by the multiclusterapp. By adding someone with member permission, you are giving them permission to upgrade apps in projects they might not belong to, so only add trusted users.
Read-Only: can only see multiclusterapp. If we want a user to monitor the status of this multiclusterapp or apps in target projects, but not have permissions to do anything else, we can add that user as read-only member

**Comment by mrajashree** [comment]
UI ticket: https://github.com/rancher/rancher/issues/17975

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/20

Test plan has been executed with no major failures.
