### ISSUE TITLE
Logging won't work in an air gap environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#17568]
After we refactored the logging, we can not deploy logging tools in an air gap environment. It need to be enhanced.

The logging system-chart also need changes for this enhancement.

Test steps:

Set the system-default-registry to a private registry via the Settings menu.
Launch the logging.
Check if the rancher-logging app pulls the image from the set private registry.

**Comment by cjellick** [comment]
Is this really an enhancement or is it a bug? Did it work in airgap in a previously released version of rancher? if so, this needs to be a bug

**Comment by cjellick** [comment]
system-charts and rancher/rancher PR merged. moving to test. let me know if there was some other dependency that i didnt know about

**Comment by fyery-chen** [comment]
> system-charts and rancher/rancher PR merged. moving to test. let me know if there was some other dependency that i didnt know about

No some other dependency.

**Comment by rootwuj** [comment]
Version: master 2.2 (2/15/19)
This version of the rancher-logging app pulls the image from the set private registry.
Confirmed fix.
