### ISSUE TITLE
Multi-Cluster App UI: App is still seen on Multi-Cluster Apps page even after cluster/project deleted

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17566]
Version: 2.2 master (1/23/19) single node install

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Launch a multi-cluster app and target to any cluster(s). Delete the project or workload or catalog app on one cluster - the multi-cluster app still shows up in the UI and does not update target projects.
- Delete the cluster(s) - the multi-cluster app still shows up in the UI referencing any/all target projects.

**Result:**
When delete all clusters:
![image](https://user-images.githubusercontent.com/45179589/51646812-633b3e00-1f37-11e9-9332-397543f8d68e.png)

When delete one of two clusters it does update but is still showing the project:
![image](https://user-images.githubusercontent.com/45179589/51647380-c62dd480-1f39-11e9-9c91-dda86a316820.png)

**Comment by alena1108** [comment]
@kinarashah we should consider removing the project id ref from multi cluster app on the project removal.

**Comment by davidnuzik** [comment]
Re-opening FYI @kinarashah and @sangeethah 
Deploy MC app on two clusters. Delete project 1 of 2, MC app updates (nice!), delete project 2 of 2 (mc app is still listed!).
![image](https://user-images.githubusercontent.com/45179589/52148327-8ac09380-2626-11e9-992e-9ed572ac2c54.png)

**Comment by kinarashah** [comment]
@davidnuzik we don't expect the multi cluster app itself to be cleaned up in this case

**Comment by davidnuzik** [comment]
@kinarashah OK I will enter an enhancement request around this for future consideration down the road.

**Comment by davidnuzik** [comment]
Enhancement request for future consideration: #17819

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/1

After deleting a project containing a multicluster app, the target link is removed from the multicluster app dashboard.
