### ISSUE TITLE
Login dialog display both reload and local auth

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#17578]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

When the rancher server is disconnected.  
It seems this steps only dev will show the reload button.

1. Stop the rancher server.
2. refresh login page.

**Result:**

![image](https://user-images.githubusercontent.com/18737885/51669867-533b6100-2000-11e9-8825-69846855c7e3.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

master branch

**Comment by tfiduccia** [comment]
Version - 2.2 master 2/28
@loganhz - The only way this will happen is if you are running the UI separately (which means you are a dev and it won't be reflected in any of the builds we receive.)  So I'm closing this and if you want to have someone in china validate you can.
