### ISSUE TITLE
Pipeline gets stuck when required answers are not provided for app installation 

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17570]
**Rancher version**
master 1/23

**Steps to reproduce (least amount of steps as possible):**
1. Configure a pipeline, Add a `Deploy Catalog App` step
2. Provides a part of the required answers.
3. Run it.

**Result:**
![image](https://user-images.githubusercontent.com/5697937/51653214-80225080-1fcd-11e9-8b78-e62f55af7b60.png)

**Expected Result**
successfully deployed the app.

**Comment by rootwuj** [comment]
Version: master 2.2 (2/14/19)
Confirmed fix.
