### ISSUE TITLE
View ingress detail UI throw error

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#17575]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a load balancer
2. View the load balancer

**Result:**

Rule target cannot display, and throw an error in console, `services`/`workload` is undefined.

**Other details that may be helpful:**

**Environment information**

UI master branch

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/28
Verified fixed
