### ISSUE TITLE
Multi Cluster App Rollback Revisions - verify RBAC works

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17571]
@kinarashah can we make sure creator of the multi cluster app can see app revisions to rollback to. The same rbac roles/rolebindings as for MCA itself should be created for corresponding revision objects.

**Comment by bmdepesa** [comment]
rancher/rancher:2/1

* Created a user and added as a project member
* Logged in as project member and created a multicluster app
* Upgraded multicluster app
* Project member was able to see revisions

* Logged in as admin
* Admin was able to see revisions
* Updated app
* Viewed revisions

* Logged in as project member
* Viewed revisions
* Project member was able to see all revisions
