### ISSUE TITLE
UI upgrade button didn't work for catalog apps

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#17573]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. install a new catalog e.g., like docker-registry
2. after the app is launched click the `Upgrade` button, but nothing changes.

**Result:**
error message is shown in the console as below

```
app.js:154 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at n.upgrade (app.js:154)
    at n.send (0:55195)
    at n.triggerAction (0:206361)
    at n.clickedAction (0:184318)
    at n.send (0:58931)
    at n [as send] (0:58190)
    at n.triggerAction (0:57009)
    at n.sendAction (0:58911)
    at n.click (0:184281)
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher:master`
- Installation option (single install/HA): `single`

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/28
Verified fixed

**Comment by samddico** [comment]
How was this solved please?
