### ISSUE TITLE
[AKS] Namespace stuck in "Activating" state intermittently

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#17589]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a hosted cluster on AKS
2. Create a project under this cluster
3. Create a namespace in this project using the GUI

**Result:**

1. Namespace gets stuck in "activating" state for minutes or even hours in the GUI.
2. Namespace is showing as "active" in AKS K8s API immediately after creation.
3. Namespace `initialRolesPopulated` status remains "Unknown" until GUI status changes to "active".
4. Debug logs shows continuous (backoffed) retries to ensure rolebindings.
5. Only a single error logged while stuck in activating state:
> 2019/01/23 15:23:58 [ERROR] NamespaceController pelle5 [namespace-auth] failed with : couldn't ensure binding creator-project-owner in pelle5: Delete https://***.hcp.westeurope.azmk8s.io:443/apis/rbac.authorization.k8s.io/v1/namespaces/pelle5/rolebindings/clusterrolebinding-ws4bf?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Other details that may be helpful:**

kubectl output:

<img width="563" alt="kubectl" src="https://user-images.githubusercontent.com/3813921/51697473-2c812880-2008-11e9-9137-8c996254fc0a.png">

Rancher debug log for namespace stuck in activating for 2h:
[ns-activating-stuck_2h.log](https://github.com/rancher/rancher/files/2793134/ns-activating-stuck_2h.log)

1. Created in GUI around 13:21
2. Became active in GUI around 15:27

Rancher debug log for namespace activated within seconds (`grep <namespace>`):

[ns-activating-ok.log](https://github.com/rancher/rancher/files/2792877/ns-activating-ok.log)

-> Note the repeated attempt to ensure rolebindings

Possibly related https://github.com/rancher/rancher/issues/14354

**Environment information**
- Rancher version: v2.1.5 and v2.2.0-alpha3
- Installation option: HA

**Cluster information**
- Cluster type: AKS Hosted

**Comment by rjbaat** [comment]
This is also happening to me on v2.1.7. When adding a namespace this keeps hanging into Activating state for a while. When being patient it will become active. But this has been faster like instant.

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/20549
