### ISSUE TITLE
Add App which belongs to a cluster catalog throw an error

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#17581]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Add cluster catalog, e.g. https://kubernetes-charts.storage.googleapis.com
2. Add App which belongs to cluster catalog

**Result:**

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/8afc0785-9575-4dc1-8375-64e361093576)

**Other details that may be helpful:**

master branch

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/28
Verified fixed
