### ISSUE TITLE
Support EKS kubernetes version upgrade from 1.10 to 1.11

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#17580]
The EKS support new kubernetes version 1.11. We need to support upgrade eks cluster from 1.10 to 1.11.

Related PR: https://github.com/rancher/rancher/pull/17459
Related Issue: https://github.com/rancher/rancher/issues/17081

**Comment by jiaqiluo** [comment]
Validated on Rancher: master 11/26

Steps:
- ran Rancher: master, single  install
- added an EKS cluster with default settings but set k8s version 1.10
- after the cluster is active, run pre-upgrade tests on it
- upgrade the cluster's k8s from 1.10 to 1.11
- after the cluster is active, run post-upgrade tests on it

Result:
The upgrade was successful and all tests were passed.
