### ISSUE TITLE
test_app_wordpress failing

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#17582]
in https://drone8.rancher.io/rancher/rancher/5776/3

=================================== FAILURES ===================================
______________________________ test_app_wordpress ______________________________
[gw1] linux -- Python 3.7.1 /go/src/github.com/rancher/rancher/tests/.tox/py37/bin/python3.7

admin_pc = <core.conftest.ProjectContext object at 0x7f4f446336a0>
admin_mc = <core.conftest.ManagementContext object at 0x7f4f48947d68>

    def test_app_wordpress(admin_pc, admin_mc):
        client = admin_pc.client
        name = random_str()
    
        ns = admin_pc.cluster.client.create_namespace(name=random_str(),
                                                      projectId=admin_pc.
                                                      project.id)
        wait_for_template_to_be_created(admin_mc.client, "library")
        answers = {
            "defaultImage": "true",
            "externalDatabase.database": "",
            "externalDatabase.host": "",
            "externalDatabase.password": "",
            "externalDatabase.port": "3306",
            "externalDatabase.user": "",
            "image.repository": "bitnami/wordpress",
            "image.tag": "4.9.4",
            "ingress.enabled": "true",
            "ingress.hosts[0].name": "xip.io",
            "mariadb.enabled": "true",
            "mariadb.image.repository": "bitnami/mariadb",
            "mariadb.image.tag": "10.1.32",
            "mariadb.mariadbDatabase": "wordpress",
            "mariadb.mariadbPassword": "",
            "mariadb.mariadbUser": "wordpress",
            "mariadb.persistence.enabled": "false",
            "mariadb.persistence.size": "8Gi",
            "mariadb.persistence.storageClass": "",
            "nodePorts.http": "",
            "nodePorts.https": "",
            "persistence.enabled": "false",
            "persistence.size": "10Gi",
            "persistence.storageClass": "",
            "serviceType": "NodePort",
            "wordpressEmail": "user@example.com",
            "wordpressPassword": "",
            "wordpressUsername": "user"
        }
        external_id = "catalog://?catalog=library&template=wordpress" \
                      "&version=1.0.5&namespace=cattle-global-data"
        client.create_app(
            name=name,
            externalId=external_id,
            targetNamespace=ns.name,
            projectId=admin_pc.project.id,
            answers=answers
        )
>       wait_for_workload(client, ns.name, count=2)

test_app.py:86: 
_ _ _ _ _ _ _ _ _ _

**Comment by alena1108** [comment]
The number of workloads created by the wordpress chart is 3, not 2. One is wordpress itself, the other 2 are mariadb and busybox as the wordpress chart packages mariadb chart: https://github.com/rancher/charts/blob/master/charts/wordpress/latest/README.md

**Comment by alena1108** [comment]
Update: the number of pods is 3, but the number of workloads is 2. The original issue seemed to be caused by misplaced sleep in a python test
