### ISSUE TITLE
spelling mistake logging configuration

### ISSUE THREAD

**Issue by berenss** [rancher/rancher#17588]
*Describe your issue here*
There is a spelling mistake in the logging configuration page:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/20711730/51698043-e065c200-1fce-11e9-8093-a2b43a2b6d3e.png">

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |

Component | Version
-- | --
Rancher | v2.1.5
User Interface | v2.1.19
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1

|Route|`authenticated.cluster.logging.logging`|

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/28
Verified fixed
