### ISSUE TITLE
Change Route53 logo for Global DNS provider dialog

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17594]
We can perhaps re-use the logo from 1.6 route53 external dns catalog item

**Comment by lvuch** [comment]
Here is a modified version of the older one.
[route-53-global-dns-logo.svg.zip](https://github.com/rancher/rancher/files/2793598/route-53-global-dns-logo.svg.zip)

**Comment by davidnuzik** [comment]
I still see the old one.
Expected:
![image](https://user-images.githubusercontent.com/45179589/51996739-9703ef80-2472-11e9-9203-42782b442575.png)

Actual (1/30/19 Master pulled this morning 30 mins ago) ImageID: b7753122536a:
![image](https://user-images.githubusercontent.com/45179589/51996788-b3079100-2472-11e9-97a1-9aac3259b10e.png)

This is with cleared browser cache.

**Comment by westlywright** [comment]
Had to roll back some changes on master this will be on hold until we can merge again.

**Comment by davidnuzik** [comment]
@westlywright and @lvuch I still see what I reported earlier. We still show the the wrong svg image. See my comment from 7 days ago.

**Comment by westlywright** [comment]
@davidnuzik sorry about the mix up but the correct logo is in now

**Comment by davidnuzik** [comment]
No worries @westlywright 
Version: Master 2.2 (2/6/19)
Confirmed fixed. We have the old route53 svg image back for the Amazon route 53 option when adding Global DNS Provider.
A new related bug was created: #17897
