### ISSUE TITLE
Logging config could not sync collect because could not detect logging app deploy

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#17599]
Use the wrong context when checking the application deployment

**Comment by aiwantaozi** [comment]
Before:
Because can't get the deployed application, so the logging config  could not get updated, so you can't see the cluster.conf, project.conf secret key under the system project -> secret rancher-logging-fluentd.

After:
Config the cluster logging and will see the cluster.conf secret. project logging will see the project.conf

**Comment by kingsd041** [comment]
Version: master 2.2 (2/11/19) 
Confirmed fix.
