### ISSUE TITLE
[rancher-compose] Does not pull in environment values from host like docker-compose

### ISSUE THREAD

**Issue by phallguy** [rancher/rancher#1759]
docker-compose will resolve an environment variable from the machine that executed the docker-compose command if the docker-compose.yml file does not provide a value. For example

```
db:
  environment:
    POSTGRES_PASSWORD:
```

Using the above file, docker-compose will look for an environment variable POSTGRES_PASSWORD from the current machine and include that in the environment of the container. This is useful to seed secrets into a container without checking them into source control.

**Comment by ibuildthecloud** [comment]
@phallguy This should work but we read the env variables from the context of the CLI, not the host.  Are you looking to have env variable read from the host running docker?

**Comment by phallguy** [comment]
It would be from the CLI machine - my macbook in this case.

**Comment by deniseschannon** [comment]
Using a docker-compose.yml that references a environment variable set on my local machine (where I run rancher-compose) doesn't pull in the environment variable.

Example:

```
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 
```

When I run on my mac (and have already done an `export MYSQL_ROOT_PASSWORD=test`), it doesn't pick up the value when launching the containers.

**Comment by deniseschannon** [comment]
Update: It actually doesn't work when I do a `docker-compose up` to the same file. 

@phallguy Have you actually tested it with `docker-compose` as well?

**Comment by deniseschannon** [comment]
https://github.com/docker/libcompose/pull/68

@sangeethah This is in our forked branch of libcompose.

**Comment by deniseschannon** [comment]
Verified with Rancher v0.41.0-rc1 and rancher-compose v0.4.1-rc2.
