### ISSUE TITLE
Local etcdbackup restore process for multiple nodes fails.

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#17590]
master (24/01)

Multiple etcd node backup fails to restore correctly since the nodes don't sync the snapshots among them.

**Comment by soumyalj** [comment]
Tested with master build from Jan 30 2019. 
1. Create a DO cluster with 3 nodes having all roles in each and use local etcd backup
2. Create workloads/ingress
3. Perform a backup through UI.
4. Break the cluster by deleting the etcd containers in two hosts
5. Restore the cluster by performing restoreFromEtcdBackup action. Choose the backup to restore from.
The cluster was restored successfully and the data was intact. Creation of new workloads after restore also succeeded
Also, performed restore from a backup on a healthy cluster. Restore was successful with no data loss. Creation of new workloads/ingress succeeded.
