### ISSUE TITLE
Rancher should manage RancherOS

### ISSUE THREAD

**Issue by smw355** [rancher/rancher#176]
Rancher should be able to:
- Identify which  hosts are running RancherOS
- identify which RancherOS containers are running on the System Docker Daemon and label them as "System Containers."  
- Identify which RancherOS containers are running on the User Docker Daemon and label them as "User Containers." 
- Independently upgrade the OS kernel and system containers on individual hosts and across swarms or environments
- Upgraded system containers should ideally not require OS restarts
- Monitor the health of containers.
- Report on the RancherOS version, as well as system container version running on all hosts. 
- Report and query on status of system containers (i.e. is contianer x running on host a, swarm b, all of environment c, or all hosts globally)

**Comment by haswalt** [comment]
I like the idea of this, but i'd more like Rancher to be packaged into RancherOS as an optoinal system container

**Comment by smw355** [comment]
Good idea. I don't think they are mutually exclusive. Do you want to create that as an additional enhancement request.

**Comment by haswalt** [comment]
https://github.com/rancherio/os/issues/82
