### ISSUE TITLE
rancher pipeline jenkins error

### ISSUE THREAD

**Issue by leiwanggit** [rancher/rancher#17602]
*Describe your issue here*
Get http://10.43.228.43:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): net/http: request canceled (Client.Timeout exceeded while awaiting headers); Setting up jenkins. If it is not deployed, this can take a few minutes.; Get http://10.43.228.43:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): net/http: request canceled (Client.Timeout exceeded while awaiting headers)
在运行rancher pipeline时候默认安装的jenkins，但是报错了，上面的错误信息

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |
|Route|`authenticated.project.pipeline.pipelines.run`|

**Comment by k-spit** [comment]
@leiwanggit  I've had the same experience. Would be very grateful about any kind of help.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Ha-Installation Rancher

**Result:**
Log-Output (container.log):
`io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/p-b2t7w-pipeline/pods. Message: Pod "jenkins-slave-3m2sh-x79b8" is invalid: spec.containers[4].image: Required value. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.containers[4].image, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=null, kind=Pod, name=jenkins-slave-3m2sh-x79b8, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "jenkins-slave-3m2sh-x79b8" is invalid: spec.containers[4].image: Required value, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}). 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:411) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227) 
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:756) 
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:334) 
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:105) 
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:291) 
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46) 
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
	at java.lang.Thread.run(Thread.java:748) 
 
May 07, 2019 1:10:09 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate 
INFO: Terminating Kubernetes instance for agent jenkins-slave-3m2sh-x79b8 
May 07, 2019 1:10:09 PM okhttp3.internal.platform.Platform log 
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path? 
ERROR: Failed to delete pod for agent p-b2t7w-pipeline/jenkins-slave-3m2sh-x79b8: not found 
May 07, 2019 1:10:09 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate 
WARNING: Failed to delete pod for agent p-b2t7w-pipeline/jenkins-slave-3m2sh-x79b8: not found `

**Comment by gitlawr** [comment]
The error message from the original issue is a timeout when Rancher server tried to connect to the Jenkins. Would be helpful if you can
1. Describe the setup of your Rancher and the cluster.
2. Check if agents in the cluster are healthy.

**Comment by gitlawr** [comment]
@k-spit Your logs look like a different story where an image is missing for a runscript step, can you show your pipeline file definition?

**Comment by k-spit** [comment]
@gitlawr Thanks for responding :+1: 
The pipeline file definition belongs to this [example project](https://github.com/rancher/pipeline-example-go).
So basically I'd like to test the pipeline with this project first, before going further.

**Comment by gitlawr** [comment]
@k-spit Can you elaborate your setup so that I can try to reproduce,
e.g., how the cluster is provisioned, rancher/kubernetes/docker version, steps before getting the error

**Comment by k-spit** [comment]
I exactly followed [Rancher HA-Installation Guide](https://rancher.com/docs/rancher/v2.x/en/installation/ha/).

Something special about the setup is that the VM's are hosted via Proxmox VE.

The cluster itself is provisioned via RKE.

Rancher Version: 2.2.2
Kubernetes Version: Client 1.12 / Server 1.13
Docker Version: 17.03.2-ce
Helm Version: v2.10.0-rancher10

[Workloads showing failed pods 1](https://imgur.com/PUlba2X)
[Workloads showing failed pods 2](https://imgur.com/0pts7Qj)

There are no logs available from failed pods, because they are already destroyed. 

Hope that helps

**Comment by NMathar** [comment]
i had the same problem. I restarted all my nodes an then the error was gone. luckily on my test env.

**Comment by gitlawr** [comment]
@k-spit From your screenshots, The Jenkins workload has tens of failed pods. Why didn't they get removed by kubernetes when the deployment replica is 1, can you provide bootstrap logs of the Jenkins master workload?

**Comment by pamarquez** [comment]
Hello,
I'm having issues for deploying the test apps in pipeline from rancher.
My Rancher machine is installed in microsoft Azure (Linux (ubuntu 16.04))
I've imported my cluster up to rancher from K3S nodes

1 master: 2 cores - 4G RAM - ubuntu/xenial64
3 agents: 1 core - 1G RAM (each machine). - ubuntu/xenial64
The cluster implementation was made on VirtualBox(Version 6.0.6_Ubuntu r129722) through Vagrant (vers2.2.3).
All firewalls for all machines are off.
It's all working perfectly fine up to the moment I run the pipeline testing rancher has.

The error Jenkins shows off is as follows,

Normal | Scheduled | Successfully assigned p-thf9b-pipeline/jenkins-546c6fbd58-hpqgf to agent03 | an hour ago
-- | -- | -- | --
Normal | Pulling | Pulling image "rancher/pipeline-jenkins-server:v0.1.0" | an hour ago
Normal | Pulled | Successfully pulled image "rancher/pipeline-jenkins-server:v0.1.0" | an hour ago
Normal | Created | Created container jenkins | an hour ago
Normal | Started | Started container jenkins | an hour ago

Warning | Unhealthy | Readiness probe failed: Get http://10.42.3.4:8080/login: dial tcp 10.42.3.4:8080: connect: connection refused | an hour ago
-- | -- | -- | --
Warning | Unhealthy | Readiness probe failed: Get http://10.42.3.4:8080/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers) | an hour ago
Warning | Unhealthy | Readiness probe failed: HTTP probe failed with statuscode: 503 | an hour ago

The pipeline I'm running is "Repositry https://github.com/rancher/pipeline-example-php" and the error it shows of is as follows,

"Get http://10.43.28.162:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.28.162:8080: connect: no route to host; Setting up jenkins. If it is not deployed, this can take a few minutes.; Get http://10.43.28.162:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.28.162:8080: connect: no route to host"

**Comment by pamarquez** [comment]
Does anybody can help me out on this please? I don't know what else to do for trying to fix this issue.
Thanks a lot.

BR.

**Comment by tnaduc** [comment]
Had this issues several time during standing up a Rancher pipeline:
![image](https://user-images.githubusercontent.com/21374032/66253399-1c326780-e7ab-11e9-865c-28eecd17c7e2.png)

Rancher pipeline seems to be unstable, especially around pulling Jenkins pod.

Could anyone please help please?
Duc

**Comment by DeepLJH0001** [comment]
disable the project network isolation，make sure pipeline project and system was able to communicate.Because cluster-agent in cattle-system namespace, if not the same project with pipeline ,may cause this problem.
