### ISSUE TITLE
Disable access control

### ISSUE THREAD

**Issue by VogonogoV** [rancher/rancher#1760]
We are not using github and use our own authentication in front of Rancher. The docs state something about [disabling access control](http://docs.rancher.com/rancher/configuration/access-control/#disabling-access-control). Is this only possible after linking to github? And if so, does this also disable the "Access Control is not configured" bar? I would like to be able to disable it.

**Comment by deniseschannon** [comment]
Yes, it only refers to disabling after linking to github. 

You can remove the "Access Control is not configured" bar by clicking on the "X" that is on the right hand side of the bar. 

We are adding LDAP authentication as well as local authentication in the near future in case that interests you. https://github.com/rancher/rancher/issues/688  and https://github.com/rancher/rancher/issues/1687

**Comment by vincent99** [comment]
How are you putting auth in front of Rancher?  You'll want to make sure the API is locked down, but that the host agents can still talk to it.

**Comment by VogonogoV** [comment]
> You can remove the "Access Control is not configured" bar by clicking on the "X" that is on the right hand side of the bar.

Yes this works until you refresh the page, then the bar is there again. As a temporary solution I remove the bar using an ad blocker.

> We are adding LDAP authentication as well as local authentication in the near future in case that interests you. #688 and #1687

We already have authentication for all our internal services. 

> How are you putting auth in front of Rancher? You'll want to make sure the API is locked down, but that the host agents can still talk to it.

Rancher, and the hosts added to Rancher, are all in the same network. So the agents connect via a local network. External access to Rancher is via nginx. And nginx configured with [oauth2-proxy](https://github.com/bitly/oauth2_proxy/). Does this answer your question?

**Comment by vincent99** [comment]
This is ancient, but at some point long ago a user preference was added to hide the message, and if auth is off there is only one "user" as far as we're concerned so that would hide it for everyone.

![image](https://cloud.githubusercontent.com/assets/753917/20734657/2f2d26cc-b658-11e6-9d8b-640b65b6ec9f.png)
