### ISSUE TITLE
Logging Elasticsearch/Splunk need to add more info in header

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#17600]
When calling elasticsearch API need add application/json type in header in case ES not success create index also not return error.

Splunk need add token in header.

**Comment by aiwantaozi** [comment]
Try the elasticsearch and splunk test button to verify this issue

**Comment by kingsd041** [comment]
Version: master 2.2 (2/12/19)  Image id: e1a8f397c6cd
Confirmed fix.
