### ISSUE TITLE
Global DNS UI: Name field does not allow special chars but no message is shown in UI to indicate this

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17612]
Version: master 2.2 (1/23/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to add a Global DNS Provider just put an ! in the Name field
- Click Create

**Result:**
The UI will not allow you to submit the form, but there are no errors in the browser console. There is no message sent in the UI indicating what characters are allowed and so it can be confusing when Create is clicked on and nothing will happen.

**Comment by westlywright** [comment]
@davidnuzik can you retest on latest? I am seeing an error when on master 

<img width="1509" alt="Screenshot 2019-04-19 15 23 39" src="https://user-images.githubusercontent.com/858614/56446380-2e7d1f80-62b7-11e9-96f6-6cb33cd17a77.png">

**Comment by davidnuzik** [comment]
@westlywright yes looks like it was fixed a while ago. I will close this issue.
