### ISSUE TITLE
UI: Add "type" to the confirmation to namespace deletion

### ISSUE THREAD

**Issue by tylerstapler-wf** [rancher/rancher#17619]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
Navigate to the Workloads page of a project. Look at the right hand portion of the screen by the first namespace listed.
![screen shot 2019-01-25 at 10 51 35 am](https://user-images.githubusercontent.com/19389666/51760075-47e34680-208f-11e9-9e1e-a1a9759559c8.png)

**Result:**
![screen shot 2019-01-24 at 4 01 54 pm](https://user-images.githubusercontent.com/19389666/51759897-e6bb7300-208e-11e9-8841-1633c7342acc.png)

One of our developers accidentally deleted a namespace when they were trying to delete the first workload on the page.

While people should be more careful, It was surprising that you can delete a namespace from the "Workloads" page with no prompt.

Deleting a namespace seems like a very intentional action which should require navigating  to a dedicated page. Alternatively, a confirmation message could have avoided this situation.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA): HA

**Comment by vincent99** [comment]
There's already a prompt for deleting them, like every other resource.

**Comment by tylerstapler-wf** [comment]
![screen shot 2019-01-25 at 11 37 59 am](https://user-images.githubusercontent.com/19389666/51762551-b2978080-2095-11e9-8f8c-2ca4351b4f08.png)

Could also specify the type of the resource being deleted? here it's not clear that the namespace is being deleted instead of the workload.

**Comment by tfiduccia** [comment]
Add "type" to the delete.  So instead of saying "Are you sure you want to delete:" resource.  It would says "Are you sure you want to delete namespace:" resource.

**Comment by tylerstapler-wf** [comment]
Yep!

**Comment by tfiduccia** [comment]
After the word "delete", please add "the <type>": to the popup delete.  The <type> can be bold if you want it to stand out.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/17/19)
Note: (v2.3.0-rc4 uses local UI so did not have change, used latest master-head to test)

Now we indicate the type of resource being deleted in the delete modals.

![image](https://user-images.githubusercontent.com/45179589/65081480-92843c80-d958-11e9-8d37-0102cf4aba70.png)

I don't see this for some resources like workloads though. We don't show the type it's the same style. Is this expected? Only changes are namespace, project, and cluster objects?

I Also see lots of changes to translations. Is this expected? I thought we normally don't touch these for languages we don't natively know?

cc: @tfiduccia @vincent99

**Comment by soumyalj** [comment]
Tested with version v2.3.0-rc4
Deleting a namespace from the workloads page indicates that a namespace is being deleted

<img width="749" alt="Screen Shot 2019-09-17 at 2 41 49 PM" src="https://user-images.githubusercontent.com/18536626/65081826-60270f00-d959-11e9-8a7a-bf1a21227f5c.png">

As @davidnuzik points out, type is not displayed for workloads (while deleting)

**Comment by codyrancher** [comment]
> Version: master-head (v2.3) (9/17/19)
> Note: (v2.3.0-rc4 uses local UI so did not have change, used latest master-head to test)
> 
> Now we indicate the type of resource being deleted in the delete modals.
> 
> ![image](https://user-images.githubusercontent.com/45179589/65081480-92843c80-d958-11e9-8d37-0102cf4aba70.png)
> 
> I don't see this for some resources like workloads though. We don't show the type it's the same style. Is this expected? Only changes are namespace, project, and cluster objects?
> 
> I Also see lots of changes to translations. Is this expected? I thought we normally don't touch these for languages we don't natively know?
> 
> cc: @tfiduccia @vincent99

Per this comment I only added namespaces, projects and clusters
> This wasn't really well described in the issue, but seems like the bold message should be shown for deleting namespaces or "higher" (project, cluster).
https://github.com/rancher/ui/pull/3352#issuecomment-531056326

And in the PR I mentioned
> I didn't provide any translations beyond en-us. I did change a string id which I carried through.
https://github.com/rancher/ui/pull/3352#issuecomment-531371836

**Comment by davidnuzik** [comment]
Thanks @codyrancher that was my fault for misreading the diff. I had read it too fast and thought the value was changed for each, not just the value.

@tfiduccia @vincent99 are we sure we're okay with only changing these areas? Would it be a chore/pain to add other resources like workloads, pods, etc, etc? What about just adding in workloads?

**Comment by davidnuzik** [comment]
Reopened for @tfiduccia @vincent99 review.

**Comment by codyrancher** [comment]
It's not a big chore/pain to add other resources. If we wanted to add this for all resource types I think we should discuss I more reliable way to enumerate and translate the resource types.

**Comment by tfiduccia** [comment]
@davidnuzik @codyrancher - I think we should make this consistent across all "types".  But if we want to discuss a more reliable way/better solution to do this, I would prefer to have a separate issues that we can push to 2.4 if Denise wants?  For now the confusion with Namespace is at least solved.
