### ISSUE TITLE
load balancer ssl

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#1761]
I'm trying to pass through 443 port through the load balancer to an nginx with ssl... it goes through http for some reason. I have setup the 443 as an tcp protocol in the load balancer.

Is this doable to pass through the load balancer ssl connections?

**Comment by deniseschannon** [comment]
Currently, this isn't supported today, but it's a feature request. https://github.com/rancher/rancher/issues/1251

**Comment by silviupanaite** [comment]
O.K., thank you.
