### ISSUE TITLE
Feature Request: Allow selection of multiple concurrent logging drivers.

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#17628]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

1. The need for this functionality is based on a requirement that all K8S cluster logs be sent to a specific logging system for archival and use in compliance auditing.  This logging system is **not** what would be used for "generic" K8S logging, or what would be used by various dev/admin/etc teams for troubleshooting.

2. Some teams already have an existing logging system and just want us to send logs to that system instead of using our logging system, but we need to get the logs into our logging system as well.

The request is to allow the selection of multiple logging driver output at both the cluster and/or project level logging - 

Example - 

At the cluster level, select Splunk as logging driver, input HEC endpoint info, add custom fields, etc. Save config.  This would be the auditing and compliance log archive.

While still in the cluster level logging, let me add **another** logging driver of my choosing (this could be another instance of the same log driver, or a new instance of a different log driver). This logging driver will be for more filtered log ingestion to a separate logging system used by various teams for troubleshooting, reporting, etc.

The same criteria applies to Project level logging.

gz#4261

**Comment by paynejacob** [comment]
With logging v2 introduced in rancher 2.5, you can configure multiple logging sources with the Logging resource.

https://rancher.com/docs/rancher/v2.x/en/logging/v2.5/
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/logging/
