### ISSUE TITLE
Multicluster app details are blank after launching

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#17627]
rancher/rancher:master
rancher/ui:v2.2.1

After deploying a multicluster app, the app details are blank.

To reproduce:
* Launch a multicluster app
* After app is `Active`, click on the app links in the app status

Expected:
* All details show for the multicluster app

Actual:
* All fields are blank except for notes and answers (ingress, endpoints, status, etc.. are all blank)

![screen shot 2019-01-25 at 2 42 50 pm](https://user-images.githubusercontent.com/21316915/51774432-8852bc80-20af-11e9-9be9-4e4bf113044f.png)

**Comment by alena1108** [comment]
Can be caused by https://github.com/rancher/rancher/issues/17754

**Comment by bmdepesa** [comment]
rancher/rancher:master 1/31

App details are populated.
