### ISSUE TITLE
No backends are associated with TCP frontend when there are host routing rules configured w/o specifying sourcePorts

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1762]
No backends are associated with TCP frontend when there are host routing rules configured for http frontends.

Server version - v0.32.0-rc2

Created LB rules with the tcp and http listening ports with the following configuration:
<img width="850" alt="screen shot 2015-08-07 at 3 37 44 pm" src="https://cloud.githubusercontent.com/assets/4266958/9147338/75fb076c-3d1a-11e5-808d-2246e9e5c861.png">

haproxy config has no backends associated with TCP frontend:
<img width="819" alt="screen shot 2015-08-07 at 3 37 25 pm" src="https://cloud.githubusercontent.com/assets/4266958/9147352/a4e5c1ac-3d1a-11e5-9a87-f53d5ba20a69.png">

Lb rules does not work because of this:
```
Sangeethas-MacBook-Pro:testwget sangeethahariharan1$ wget http://162.222.181.214:9081/service3.html
--2015-08-07 15:32:59--  http://162.222.181.214:9081/service3.html
Connecting to 162.222.181.214:9081... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2015-08-07 15:33:00--  (try: 2)  http://162.222.181.214:9081/service3.html
Connecting to 162.222.181.214:9081... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2015-08-07 15:33:03--  (try: 3)  http://162.222.181.214:9081/service3.html
Connecting to 162.222.181.214:9081... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

```

**Comment by sangeethah** [comment]
Workaround for this issue is to have specific source port associated with the services.

**Comment by alena1108** [comment]
hostname routing rules will be ignored for tcp listeners now, and you should see them all merged to the same backend assigned to the source port

**Comment by sangeethah** [comment]
Tested with build from master - Aug 14th.
hostname routing rules is ignored for tcp listeners and accessing the LB for tcp port with/without headers , results in traffic routed to all the targets associated both the services.
