### ISSUE TITLE
After deploying a MultiCluster app, the corresponding app at the project level shows no pods

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#17626]
rancher/rancher:master 1/25

After deploying a multicluster app, the corresponding catalog app at the project level shows 0 pods running, and no ingress link. 

To reproduce: 
* Deploy a multicluster app
* View the catalog apps at the project level dashboard

Expected:
* Apps show the correct number of pods, and any ingress links

Actual: 
* Apps show 0 pods running, though the workloads are present and running within the cluster.

**Comment by alena1108** [comment]
Can be caused by https://github.com/rancher/rancher/issues/17754

**Comment by bmdepesa** [comment]
rancher/rancher:master 1/31

Pod count is showing correctly in project apps.
