### ISSUE TITLE
Ingress - cannot add an ingress for a existing workload

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17630]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- ran rancher: master 
- added a DO cluster with 3 nodes: one role one each
- deployed a workload using the image `sangeetha/testnewhostrouting`
- added an ingress pointing to the workload 

**Result:**
1. I cannot access to the name.html page supported by the image  and the browser gave me  502 error.
<img width="1472" alt="screenshot 5" src="https://user-images.githubusercontent.com/6218999/51776574-11b9bd00-20b7-11e9-9c50-fb93750e9a6c.png">
2. the port is set to 42 by rancher and I cannot change it back to 80
<img width="1535" alt="screenshot 6" src="https://user-images.githubusercontent.com/6218999/51776578-141c1700-20b7-11e9-80dc-f68e23bec70c.png">
3. there is an extra 0 at the end of the link

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master 1/25
- Installation option (single install/HA):
singgle install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-103-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: jiaqi-master-latest
ID: HUDH:QL2Q:UNRI:N5JV:UCPB:KFKM:JFHQ:FXFR:A2PV:YHFA:VPEX:HQB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17622
