### ISSUE TITLE
UI - Error messages are not presented in "ADD Global DNS Provider" page when creation fails.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17636]
Rancher server version - Build from master

Steps to reproduce the problem:
Create a "Global DNS Provider" with name say "test1".
Create another "Global DNS Provider" with same name.
API fails
```
{"baseType":"error","code":"AlreadyExists","message":"globaldnsproviders.management.cattle.io \"route53new\" already exists","status":409,"type":"error"}
```

But UI shows no error message and stays in the same  "ADD Global DNS Provider" page

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/25/19) HA Setup
Confirmed fix. I am unable to reproduce the problem after the fix. When I attempt to create another DNS provider with the same name the UI will indicate this already exists on the form:
![image](https://user-images.githubusercontent.com/45179589/51863991-b595a980-22ff-11e9-903a-30015e1009e0.png) This area was also smoke/halo tested (DNS providers / dns entries)
