### ISSUE TITLE
Regular users are not presented with any "hosted Kubernetes provider" option when trying to create a cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17634]
Rancher server version - Build from master

Steps to reproduce the problem:
AD Auth enabled setup with site access set to "Allow any valid user".
Log in as any user other than admin user.

Try to add a cluster.
No "hosted Kubernetes provider" options  are presented:
<img width="1318" alt="screen shot 2019-01-25 at 4 53 42 pm" src="https://user-images.githubusercontent.com/4266958/51780354-9b22bc80-20c2-11e9-9a90-62a5c8b1d8ca.png">

**Comment by cjellick** [comment]
@nathan-jenan-rancher if this is true, it needs fixed for alpha

**Comment by sangeethah** [comment]
Tested with latest build from master
FreeIPA Auth enabled setup with site access set to "Allow any valid user".
Log in as any user other than admin user.

Try to add a cluster.
All "hosted Kubernetes provider" options are presented in the UI.
Able to provision a GKE cluster successfully.
