### ISSUE TITLE
Template format error when creating EKS cluster

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#17635]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Start rancher from master.
2. Select "Add Cluster"
3. Enter Valid Access Key and Secret Key
4. Leave all other fields as the default values.
5. Select "Create" button

**Result:**
After starting worker node create error will be displayed on UI:

Error creating stack: error creating master: ValidationError: Template format error: Unresolved resource dependencies [PublicIps] in the Resources block of the template status code: 400, request

![screen shot 2019-01-25 at 6 09 52 pm](https://user-images.githubusercontent.com/19376037/51780523-83503600-20cc-11e9-8684-d5fa58ceea4b.png)

**Other details that may be helpful:**
--add-local=true
related to this commit: https://github.com/rancher/kontainer-engine/commit/70debf4b384743e27bb47ae69d5842f10bc07aff

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master on 1/14
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by orangedeng** [comment]
This issue will block following issues: 
https://github.com/rancher/rancher/issues/17580
https://github.com/rancher/rancher/issues/17579
https://github.com/rancher/rancher/issues/17561
https://github.com/rancher/rancher/issues/17081

**Comment by rmweir** [comment]
> This issue will block following issues:
> #17580
> #17579
> #17561
> #17081

It's ready for review @nathan-jenan-rancher

**Comment by cjellick** [comment]
LGTM

**Comment by jiaqiluo** [comment]
The bug fix is validated on master 1/28
Steps:
- Start rancher from the master.
- Select "Add Cluster" and choose EKS
- Enter valid `Access Key` and `Secret Key`
- Leave all other fields as the default values.
- Select "Create" button

Result:
the EKS cluster is running up successfully.
