### ISSUE TITLE
[UI] link in ingress rules form leads to 404 error when backend type is service

### ISSUE THREAD

**Issue by CornSoiliml** [rancher/rancher#17644]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Workloads -> Load Balancing -> click any name which backend is service,not workload ->click link of rules , target  

**Result:**
404 error

**Other details that may be helpful:**
rancher version v2.1.5

i have a workload named tomcat-test-work , and a service named tomcat-test-svc in namespace dev.
then i create 2 ingress rule:
1. target is service: tomcat-test-svc
2. target is workload: tomcat-test-work

and i click the url of the first one in page i describe in "Step to reproduce"
i check url  like
"https://myrancher/p/c-k862c:p-9xwj6/workload/dev:tomcat-test-svc"
the "workload" in url may be the reason of this error
because that workload doesn't exist , it should be like "dns" instead
because 
"https://myrancher/p/c-k862c:p-9xwj6/dns/dev:tomcat-test-svc"  is a valid page

and if ingress backend is workload , it goes fine to  workload page.
"https://myrancher/p/c-k862c:p-9xwj6/workload/dev:tomcat-test-work"
will lead to a valid page.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):rancher version v2.1.5
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rancher/rancher     stable              d728e80d9719        3 weeks ago         541 MB
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/28/19)
Confirmed fix. After the fix I was not able to reproduce the issue. I also smoke and halo tested this area and validated http/api.
