### ISSUE TITLE
Cannot use port name for ingress rule target port

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17640]
rancher/rancher:master

Steps to reproduce:

1. Deploy a `nginx` workload
2. Create a service with type `Alias of another DNS record's value`
3. In create service page, click show advanced and add a port with name `test`, service port `80`
4. Create an ingress and point to the newly created service

Results:

User cannot select port name `test` as the target port. User can only select `80`

Expected:

User should be able to select `test` as the port like the following screenshot

![image](https://user-images.githubusercontent.com/21168270/51782487-112b3000-2164-11e9-8a64-c67fa4c52a44.png)

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/28
Verified fixed
