### ISSUE TITLE
rancher-compose.yml generated for LB has " config" appended to the name in " load_balancer_config" section.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1764]
Server version - V0.32.0-rc2

Create a LB service.
Use "View Config" option to view the generated rancher-compose.yml

Lb config generated for the LB service's name has "lb-2 config" .  
lb-2:
  scale: 1
  load_balancer_config:
    description: lb-2
    name: lb-2 config

This is not causing any issue. But the name is stored as " lb-2 config" in load_balancer_config table. Is it better to not have any space in name and instead have it named in the format <name>_config?

**Comment by alena1108** [comment]
@sangeethah the name having " config" in it is the name passed to the createLoadBalancerService.loadBalancerConfig.name field. If no name is passed, Rancher code generates one (and it doesn't have spaces).

 I've tested from the UI, the UI passes the config name with the space. @sangeethah double check if Rancher compose does the same. And if you are not ok with this name format, pls reassign the bug to the UI/Rancher-compose components.

**Comment by vincent99** [comment]
This should eventually go away with the removal of the standalone balancer from the API...

**Comment by deniseschannon** [comment]
Closing as this no longer exists today.
