### ISSUE TITLE
Rancher failing to provide Kubernetes infrastructure on AWS EC2

### ISSUE THREAD

**Issue by santosh3702** [rancher/rancher#17649]
Hi ,

i am trying created Kubernetes cluster on AWS EC2 (t2.medium) through Rancher.

bellow error log i am facing 

Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [18.215.187.163]: Get https://localhost:6443/healthz: can not build dialer to c-t85s2:m-q5kbk, log: I0127 12:14:24.386010 1 storage_rbac.go:276] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public

Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [18.215.187.163]: Get https://localhost:6443/healthz: can not build dialer to c-t85s2:m-q5kbk, log: I0127 12:16:07.549383 1 log.go:172] http: TLS handshake error from 172.31.8.39:37956: EOF

**Comment by loganhz** [comment]
Can you provide the detailed steps for your cluster, please?
Such as how many nodes and what roles for the nodes, which security groups did you select.

**Comment by santosh3702** [comment]
Issue was resolved after following pre-req.
