### ISSUE TITLE
Custom logging content don't need match label

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#17659]
when input custom config, now the match part also included in the request, we don't need match label.

Current:
```
 "customTargetConfig": {
        "content": "<match *>\n  @type elasticsearch\n  include_tag_key true\n  hosts http://xxxx:port\n  logstash_format true\n  logstash_prefix \"michelia-custom\"\n  logstash_dateformat %Y-%m-%d\n  type_name \"container_log\"\n</match>"
    }
```

Expected:
```
 "customTargetConfig": {
        "content": "@type elasticsearch\n  include_tag_key true\n  hosts http://xxxx:xxxx\n  logstash_format true\n  logstash_prefix \"michelia-custom\"\n  logstash_dateformat %Y-%m-%d\n  type_name \"container_log\""
    }
```

**Comment by davidnuzik** [comment]
Confirmed that we don't send this content in customTargetConfig any longer. Is this okay that it is still seen in the UI? @aiwantaozi ? Is this expected and appropriate to still see the <match *> in the UI?

![image](https://user-images.githubusercontent.com/45179589/52730393-79597e80-2f78-11e9-9fe8-383252f9b23a.png)

Actual in req payload (snippet):
```
  content: "@type forward↵  client_key /fluentd/etc/config/ssl/cluster_c-dln4t_client-key.pem↵  
  client_cert /fluentd/etc/config/ssl/cluster_c-dln4t_client-cert.pem↵  ca_file /fluentd/etc/config/ssl/cluster_c-dln4t_ca.pem"
```

**Comment by aiwantaozi** [comment]
@davidnuzik Yes, the real match part is not like what show in the UI. We will generate the match part,  so we don't need the match part, you can check the final fluentd file under the system project secret

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/13/19)
Confirmed fix. The <match *> is not longer sent to the server. Inspected HTTP/API. See my comment above for details.
