### ISSUE TITLE
Multi-Cluster App: When delete a mc app namespace(s) are randomly left behind

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17650]
Version: master 2.2 (1/25/19) HA Setup

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a MC app such as with grafana from https://github.com/mrajashree/charts mcapp branch catalog. This will create namespaces for you.
- Let it fully provision. Delete it.

**Result:**
Everything is properly removed however the namespace is left behind seemingly randomly on one or more clusters.
![image](https://user-images.githubusercontent.com/45179589/51804102-ae946b80-2219-11e9-83c9-888145ede683.png)

**Comment by davidnuzik** [comment]
I noticed on DO custom rke cluster the namespace was deleted however I don't see this with other providers such as ec2 rke. Please let me know if I can help by testing more providers, etc.

**Comment by davidnuzik** [comment]
This might be a more general issue. When I create a normal catalog app the namespaces are left behind there as well. This seems consistent however.

**Comment by deniseschannon** [comment]
@davidnuzik We don't delete the namespace when you delete a catalog app as we don't know what else is in the namespace, which is why it's not deleted. 

https://github.com/rancher/rancher/issues/13159
