### ISSUE TITLE
ability to pass in user-data when adding hosts

### ISSUE THREAD

**Issue by gregory** [rancher/rancher#1765]
would be awesome to be able to pass in user-data for the cloud-config when adding new hosts.

**Comment by vincent99** [comment]
The add host screen is essentially a frontend for `docker-machine`.  I do not see support for userdata in any of the major [drivers](https://github.com/docker/machine/tree/master/drivers).

**Comment by gregory** [comment]
hmm i see... makes sens. Could you think of any alternative solution?

**Comment by vincent99** [comment]
You can replicate what docker-machine does by using your provider's native API or CLI to provision the machine with your user data.  Then have it run the appropriate command to install Docker (if not already in your OS image), and finally run the command from the "custom" section of the Rancher Add Host screen to have it register into the Rancher server.

We are working on adding an ec2-metadata-style "introspection API" to allow a container to get information about itself, such as labels that are set on it.  I don't think we really considered having this work for the host itself too but it seems like something we could do. Thoughts @ibuildthecloud?

**Comment by joshwget** [comment]
@vincent99 It looks like this feature is now available for Amazon and Digital Ocean.

**Comment by vincent99** [comment]
@joshwget but not in any usable form; They take content from a file that lives on disk local to where machine is running, which we have no way to inject or point to.

**Comment by joshwget** [comment]
Isn't that something that could be in scope for go-machine-service?

**Comment by vincent99** [comment]
It can, you'd have to generate schema that said does that take a path are text, then write the text to temp file and call machine with the path to the file.  And probably generate consistent paths that can be recreated from db is the container hosting gms goes away.

**Comment by joshwget** [comment]
Not sure I follow on the last part, but it's not too important that we iron out the details right now. Just wanted to point out it's theoretically possible now.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
