### ISSUE TITLE
Rancher chart's question.yaml

### ISSUE THREAD

**Issue by RRadziejewski** [rancher/rancher#17660]
Hello, I have a question regarding to questions.yaml.

First i will copy the important files content.
This is my values.yaml file:

app:
  envs:
    DB_HOST: db
    DB_NAME: test
    DB_PASSWORD: root
    DB_USER: root
  image:
    repository: kac/nodeapp
    tag: latest
  ports:
  - containerPort: 3000
    onPort: 30111
    protocol: TCP
    type: NodePort

And this is my service spec:

apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    chart: {{ include "genericedgedemo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
{{- range $index, $port := .Values.app.ports }}
{{- if (and (eq $port.type "NodePort") (not (empty $port.onPort))) }}
  - port: {{ $port.containerPort }}
    protocol: {{ $port.protocol }}
    name: {{ printf "%s-%.0f" $port.type $port.onPort | lower }}
    targetPort: {{ $port.containerPort }} 
    nodePort: {{ $port.onPort }}
{{- end }}
{{- end }}
  selector:
    app: app
    release: {{ .Release.Name }}

And the problem is with questions yml. When i try to change value of app.ports[0].onPort and later deploy i am having a lot's of errors. Somehow rancher is changing the other values of app.ports[0] to 0 and i get errors.
But on other hand when i pass all values in answers yml of app.ports[0] so containerPort, onPort, protocol and type it's working correctly. Shouldn't i be bale to change only onPort in questions.yaml??

**Comment by guangbochen** [comment]
yes for now, and for the syntax you can reference the official doc https://github.com/helm/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set here.

we will introduce custom `values.yaml` in Rancher v2.2 so you can specify answers like the original `values.yaml`.
