### ISSUE TITLE
Local etcdbackup restore process for single node fails

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17665]
Version: master 2.2 (1/28/19) single node rancher

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an RKE cluster such as with ec2 or DO. Use defaults (local etcd backup). Keep it in a healthy state.
- Once it is provisioned backup and then try to restore using the latest etcd snapshot.

**Result:**
The local etcd restore will fail. The logs will continuously loop with errors. In the UI you will see under the cluster:
`[[network] Host [34.215.84.224] is not able to connect to the following ports: [172.31.34.197 (172.31.34.197:8472) open]. Please check network policies and firewall rules]`

**Other details that may be helpful:**
It is possible this is related to #17655 
Full log from rancher server (see near bottom the continuous loop of errors/failures:
[localrestoreerror.txt](https://github.com/rancher/rancher/files/2804347/localrestoreerror.txt)

**Comment by davidnuzik** [comment]
Depends on https://github.com/rancher/rke/issues/1102

**Comment by galal-hussein** [comment]
The issue should be resolved by this PR https://github.com/rancher/rke/pull/1105

**Comment by sangeethah** [comment]
Tested with latest build from master.

Created 1 node DO cluster.
Deployed few workloads.
Take a Backup.
Deployed few more workloads.
Restore from the backup.
Cluster gets to "Updating" state and then gets to "Active" state as expected.
