### ISSUE TITLE
Kubelets fail to start on K8s1.116 setup with default docker version 18.06

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17667]
Rancher version: v1.6.26-rc5
Kubernetes version: K8sv1.11.6
Docker version: 18.06

Steps:
1. Create a K8s cluster on v1.6.26-rc5
The default docker version picked up is 18.06. 
Kubelets fail to start on this setup with the below error:
```

(Container should have been running but is in error state. Check logs for more information.: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate") 

```

**Comment by alena1108** [comment]
Can be tested on `rancher/server:v1.6.26-rc6`

**Comment by soumyalj** [comment]
Tested with rancher v1.6.26-rc6. Created Kubernetes environment using k8s 1.11.6 template. 
Docker default version was set to 17.03 by default. Kubelets started fine and the setup came up successfully.
