### ISSUE TITLE
sever-chart build and versioning change

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#17663]
Move charts into rancher/rancher and automatically release charts as part of the Rancher server build process.

### Attempt 1: 
Chart hosted in separate repo and Chart releases matched Rancher versions.

#### What worked:
Deploying Rancher with a chart was a new idea.  We were not entirely committed to the idea. Having the chart in its own repo allowed for development on the chart and the chart build/publish pipeline without constant updates to rancher/rancher.

#### What didn't work:
Chart development was new and we were still working out patterns, so lots of updates. At that time we didn't want to have to version rancher every time we wanted to fix something in the chart. The chart version got tricky since helm is pretty strict when it comes to semver. If we wanted to maintan the lock step versioning and were not willing to update Rancher, every time we wanted to update the chart we had to overwrite the chart.  With caching and other issues it was going to be hard to figure out what exactly was in a chart that a customer downloaded.

Release process was painful. Requiring commits and tags to the server-chart repo.

### Attempt 2: 
(Current) Chart hosted in separate repo and Charts versioned YYYY.MM.Release.

#### What worked:
Several charts required updates after being released, but patterns were being developed and changes were slowing down. We still didn't want to have to version Rancher for a chart update, but need to version charts between rancher releases. This allowed us to make chart updates decoupled from Rancher updates.

#### What didn't work:
This would be fine if we were only maintaining one branch/stream of Rancher.  We discovered a big flaw in this plan when the K8s CVE came out and we had to publish updates to 2.0 and 2.1 series of Rancher. We discovered that whe we need to do something like this with 2.3, there's no good way for a customer to figure out how to stay on the 2.2 series if we just count up with the date style deployments.

Release process is still a pain and error prone, with coordinating multiple repos/branches and manual inputs.

## What we want to do now:
Charts hosted in rancher/rancher built and deployed with Rancher releases.

We need to be able to maintain several branches of chart and coordinate the builds with releases of rancher/rancher.  The simplest solution to this is to put the chart in the rancher/rancher repo and build the versioned chart as part of the Rancher server build.  The charts will be added to each branch and will be in lock step with Rancher server versioning. 

### Advantages:
- No extra manual (error prone) process to release a chart with a Rancher.
- Chart and Rancher releases get created and tested as a whole. 

### Disadvantages:
- If there is some critical fix for the chart, we will need to create a patch (x.x.1) release of rancher to fix it. 

At this point I believe Chart development has stabilized enough that this should be an uncommon occurrence (knock on wood). New development is happening, but on a slower rate and should be part of the rancher release testing.  Unit tests are being added to help prevent changes breaking existing behavior.

#### Transition
We have put us in a tough spot with the choice to use the date stamp release numbers.  Since helm uses semver order to pick the "latest default" release, the date stamps will always come first.  We will have to transition away from date stamps and unpublish them from the repo with the 2.2 release.

#### The Plan:
- [x] Move rancher/server-chart code by branch to the various release branches in rancher/rancher.
Enhance rancher/rancher build process to build chart with matching version.
- [x] Build process will continue to publish yyyy.mm.release style of tags along with matching rancher release tags.
- [x] Backport previous yyyy.mm.release to matching rancher tag releases.  In places where we have multiple chart versions as part of the release use the latest version as the rancher versioned release.
- [x] Communicate to customers this transition.
- [x] When 2.2.0 is released, unpublish yyyy.mm.release charts from helm repo. This is necessary to allow latest to be 2.2.0 instead of 2018.mm.release.

**Comment by cjellick** [comment]
moved out of release as its tracked in my overall release todos item

**Comment by cjellick** [comment]
can close once release is out and this is completed

**Comment by deniseschannon** [comment]
With the release out, this has been moved/transitioned to no longer using charts using build numbers.
