### ISSUE TITLE
RKE Cluster is in "Pending" state when nodes are still getting created and then transitions to "Provisioning" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17673]
Rancher server - Build from master

Steps to reproduce the problem:
Create any RKE cluster using  nodes frominfrastructure provider like AWS ,DO.

RKE Cluster is in "Pending" state when nodes are still getting created and then transitions to "Provisioning" state.

<img width="1289" alt="screen shot 2019-01-28 at 1 54 10 pm" src="https://user-images.githubusercontent.com/4266958/51869086-7027ab00-2304-11e9-9801-21d6fdc438ed.png">

Do we need this "Pending" state ? Or should the cluster be in "Provisioning" state even when nodes are getting created?

**Comment by cjellick** [comment]
@rmweir will this also be addressed by your fix?

**Comment by cjellick** [comment]
I guess not done yet, right @rmweir ?

**Comment by sangeethah** [comment]
Tested with latest build from master - Feb 12:

When creating RKE cluster using nodes from infrastructure provider , cluster gets to "Provisioning" state when nodes are getting created and then eventually gets to "Active" state when k8s cluster creation is done.
