### ISSUE TITLE
Add cloud provider gce to an existing Rancher/Kubernettes setup?

### ISSUE THREAD

**Issue by bearmoo-repo** [rancher/rancher#17677]
**What kind of request is this (question/bug/enhancement/feature request):**
It would be nice to add a cloud provider (ie. gce, aws, azure) to an existing Rancher/Kubernettes setup?

**Steps to reproduce (least amount of steps as possible):**
Maybe in the ui or cli where you can sepcify what provider your setup is on?

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
lastest version/Single HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM. Shared CPU, 1.7G Ram
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```
(paste the output here)
```

- Docker (use `docker info`):
docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

```
(paste the output here)
```

**Comment by loganhz** [comment]
I guess we can talk about it in https://github.com/rancher/rancher/issues/12562
Close in favor of it
