### ISSUE TITLE
Add support Azure AKS Virtual Nodes

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#17670]
Azure Virtual Nodes allow operators to support architectural paradigms allowing them to quickly and easily scale temporarily to respond to spikes in traffic without provisioning additional nodes.  This allows them to

> only pay per second for their execution time. In a scaling scenario, you don't need to wait for the Kubernetes cluster autoscaler to deploy VM compute nodes to run the additional pods. 

This would require adding backend and frontend support to toggle the option.

https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-portal

**Comment by vdweij** [comment]
Really looking forward to this feature. Any idea when at least the API will have this feature?
