### ISSUE TITLE
load balancer not in dns service discovery

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#1767]
I added the balancer service to an nginx server and the dns is not resolving the LB name assigned.
LB is set to listen to internal port 80.
Nginx is set to decrypt traffic based on hostnames.

Rancher	v0.32.0
Cattle	v0.75.0
User Interface	v0.40.0
Rancher Compose	beta/latest

Cross stack service discovery is not working also...

**Comment by silviupanaite** [comment]
Duplicate, view https://github.com/rancher/rancher/issues/1771

**Comment by alena1108** [comment]
@silviupanaite could you please share the details of your LB setup - exported docker-compose.yml of your stack. Just want to make sure that there is nothing misconfigured on the LB side, so reopening this bug.

**Comment by silviupanaite** [comment]
It's related to this issue [#1771]( https://github.com/rancher/rancher/issues/1771)
