### ISSUE TITLE
Cluster Reserved wheels should be expressed as milliCPU and MiB in UI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17674]
Version: master 2.2 (1/28/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Proposal:**
If you look at how the CPU Reserved wheel works today on the cluster page it is expressed in plain CPU rather than milliCPU. This is confusing because if you inspect the API we are reserving in milliCPU and allocatable is in plain CPU. Therefore it's possible from looking at the UI to see that we have reserved 1 of 2 CPU but that is 48%.

![image](https://user-images.githubusercontent.com/45179589/51869283-5474d280-230d-11e9-852b-4ea3be8b681c.png)

In my case this was because (if you inspect the API) I had:
```
allocatable": {
"cpu": "2",
"memory": "3943976Ki",
"pods": "110"
```
and
```
"requested": {
"cpu": "955m",
"memory": "560Mi",
"pods": "16"
```
therefore 955/2000 = 48%

Similarly, with memory we round down or truncate. As you can see above we requested 560MiB of memory but the UI indicates 500MiB:

![image](https://user-images.githubusercontent.com/45179589/51869546-16c47980-230e-11e9-8a7c-8dfba15f8bb6.png)

I believe it would make sense to be more specific in this area to avoid confusion with percentages not being in alignment with what is actually stated in the API.

**Pros/Cons:**
Pro: It will be more clear to the user that the wheel is at 48% if we indicate 955mCPU of 2000mCPU Reserved and this is why we are at 48% rather than 1 of 2 = 48%.
Con: 955mCPU of 2000mCPU might confusing a few people. Perhaps we instead want this as subtext below the "1 of 2 Reserved" text.
Possible cons: If the requested/allocatable varies depending on provider then more work may be required to make all providers compatible with showing milliCPU only and MiB/GiB.

**Wireframe:**
Here is what I propose we do:
![screen shot 2019-01-28 at 3 08 02 pm](https://user-images.githubusercontent.com/45179589/51869881-34461300-230f-11e9-8095-ebd30724e6b2.png)
![screen shot 2019-01-28 at 3 10 24 pm](https://user-images.githubusercontent.com/45179589/51869885-37410380-230f-11e9-8922-c669712dce3f.png)

**Comment by davidnuzik** [comment]
Assigned to me and with to-test status so I can take another look at this later with new changes in this area.

**Comment by davidnuzik** [comment]
Looked at this again in latest master (3/19/19) and this is still basically the case. I don't think we need any API changes we just need to consider expressing the CPU/memory differently in my opinion.

**Comment by vincent99** [comment]
It's a dashboard and humans think in CPUs, not thousandths of a CPU.  Requests can be in _any_ unit, unless you're going to show 4039114752 bytes you're going to be rounding somewhere.  The numbers are rounded to a couple significant figures.
