### ISSUE TITLE
Make supported k8s range v1.11 - v1.13

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#17676]
This will make v1.10 and below unsupported in both RKE and EKS/GKE/AKS.
In EKS, this will take the supported versions down to only v1.11

**Comment by jiaqiluo** [comment]
The enhancement is validated on rancher: master 1/28
Steps:
- run rancher: master 1/28, single install
- attempt to add new clusters: EC2, DO, Azure, vSphere

Result:
- the default k8s version is 1.13
- supported k8s version range from 1.11 - 1.13
