### ISSUE TITLE
Values get appended by UI with extra value on multi cluster app upgrade 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#17678]
-  Create a multi cluster app, see answers in API. 
- Upgrade app, add/remove target. 
Answers get appended with `0: "resource:/v3/schemas/answer"` 

This results into app getting upgraded, when only targets should be changed. 

![image](https://user-images.githubusercontent.com/16870565/51871304-ddd6d580-230a-11e9-818d-02b45dfb9e39.png)

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/29
Verified fixed
