### ISSUE TITLE
Multicluster app - Upgrading MCA and removing target does not remove catalog app from the selected project

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#17672]
rancher/rancher:master (1/28)

Upgrading a multicluster app and removing a target does not remove the project level catalog app. 

To reproduce: 
* Deploy a multicluster app to more than 1 project
* Upgrade the MCA and remove a target
* The link to the removed target is removed from the MCA dashboard

Expected:
* The catalog app at the project level for the removed target is removed

Actual:
* The catalog app at the project level for the removed target remains
* Workloads & service discovery records also remain for the app

The MCA dashboard after a target has been removed (2 original -- 1 removed):
<img width="1131" alt="screen shot 2019-01-28 at 2 55 10 pm" src="https://user-images.githubusercontent.com/21316915/51869098-d87a8a80-230c-11e9-9870-9b42e94ae68d.png">

MCA api view correctly shows only one target:
<img width="542" alt="screen shot 2019-01-28 at 2 57 04 pm" src="https://user-images.githubusercontent.com/21316915/51869183-08c22900-230d-11e9-98ee-0e41ff4cee9f.png">

The catalog apps & workloads for the project where the target was removed:
<img width="921" alt="screen shot 2019-01-28 at 2 55 35 pm" src="https://user-images.githubusercontent.com/21316915/51869128-e8926a00-230c-11e9-80aa-42219a98cc92.png">
<img width="1161" alt="screen shot 2019-01-28 at 2 55 29 pm" src="https://user-images.githubusercontent.com/21316915/51869129-e92b0080-230c-11e9-945a-81a0c6c99b07.png">

**Comment by alena1108** [comment]
Closing as this issue is already tracked https://github.com/rancher/rancher/issues/17484
