### ISSUE TITLE
Ingress doesn't launch when using restricted PSP as cluster default.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#17671]
`ingress-controller` pods are unable to launch if you apply the `restricted` PSP as cluster default.  Looks like the `unrestricted` PSP is not applied to the entire System project. 

**Expected behavior:**
When enabling PSP for a cluster, all namespaces in `System` project should get the `unrestricted` PSP role bound to the default service account.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. When creating a cluster, in advanced options turn on PSP and set the default policy to `restricted`.
1. Cluster will create, but pods in the `ingress-nginx` namespace under the `System` project will never schedule.

**Result:**
Ingress controller never starts.

**Other details that may be helpful:**
Work around: Edit `System` project, change PSP from `None` to `unrestricted`.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.5
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): ec2 t3.lartge
- Kubernetes version (use `kubectl version`): v1.11.6

**Comment by superseb** [comment]
Can you check/update https://github.com/rancher/rancher/issues/16119?

**Comment by jgreat** [comment]
Duplicate of #16119
