### ISSUE TITLE
Pipeline deploy app steps display incorrectly for project/cluster level catalog

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17685]
**Rancher version**
master 1/28

**Steps to reproduce (least amount of steps as possible):**
1. Add a project/cluster catalog
2. Add a pipeline, edit config
3. Add a deploy app step, choose a project catalog & choose mysql template. Fill in other fields.
4. Click save.
5. Click on the step to edit it

**Result:**
![image](https://user-images.githubusercontent.com/5697937/51882145-e84fa880-23b8-11e9-98dc-f2418106066a.png)

**Comment by tfiduccia** [comment]
Version - 2.2 master 1/29
Verified fixed
