### ISSUE TITLE
[Load Balancer] basic auth

### ISSUE THREAD

**Issue by flower-pot** [rancher/rancher#1768]
I know that the load balancer used for the managed lb is HAProxy and HAProxy can do basic auth. Although maybe not the primary goal of a load balancer, do you think it makes sense to add it to be configured through rancher?

**Comment by deniseschannon** [comment]
This might be answered in this issue: https://github.com/rancher/rancher/issues/1871, but not completely sure.

**Comment by vincent99** [comment]
Yes; I don't think we want to make auth a first-class option on the balancer resource but that would allow a way to configure it

**Comment by deniseschannon** [comment]
@flower-pot Please follow #1871 to follow the abilities to add custom parameters to the load balancer.
