### ISSUE TITLE
Configure EKS disk space UI

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#17690]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Select "Add Cluster" button
2. Select "Amazon EKS" under "In a hosted Kubernetes provider"
3. Fill out required information and leave default options until reaching "Node" section

**Result:**
The desired result would be to have a text field where the user can enter volume size they would like allocated for each node (in GB). The label for this field should be "Node Volume Size (GB)".

Pictured below is how the section currently looks. Ideally, there would be one more input as described in this section:
![image](https://user-images.githubusercontent.com/19376037/51886946-0b457280-234f-11e9-947b-b0d2f5d79477.png)

**Helpful information:**
The template id for this property will be nodeVolumeSize
This is the UI component to the following issue: https://github.com/rancher/rancher/issues/16437

**Comment by loganhz** [comment]
The disk field is not supported in Rancher server backend. We need to support it in backend first. Maybe we need to push this issue out from 2.2

**Comment by rmweir** [comment]
> The disk field is not supported in Rancher server backend. We need to support it in backend first. Maybe we need to push this issue out from 2.2

I am working on it right now and should have a PR up soon.

**Comment by westlywright** [comment]
@rmweir can you remove the `status/awaiting-backend` when your backend is merged?

**Comment by rmweir** [comment]
@westlywright Yes, thank you.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/12/19)
There is now an option to set the disk size for each EKS node. This is nodeVolumeSize and the default is 20GB (20). 
![image](https://user-images.githubusercontent.com/45179589/52636215-37054400-2e89-11e9-8f2e-30ecec072f9f.png)
Validated http/api.
