### ISSUE TITLE
Get container ID using container name

### ISSUE THREAD

**Issue by luckykalangi** [rancher/rancher#17694]
**Question :**
Is there anyway i can get the Container ID using the API? ( given container name)

**Other details that may be helpful:**
I want to restart the rancher container. But API will only accept container ID, for me i will be knowing only container name. Is there any way to get container ID using container name? OR is there anyway i can restart the container through API using *container name*?

**Environment information**
- Rancher version : 1.6.17

**Comment by loganhz** [comment]
Please check the metadata service doc
https://rancher.com/docs/rancher/v1.6/en/rancher-services/metadata-service/

**Comment by ganeshknr** [comment]
Thank you @loganhz  
In the document the URL to use meta-data service is given like curl **http://rancher-metadata/<version>/<path>**. I am trying to get the container information from remote machine. So what can be the URL?

**Comment by loganhz** [comment]
Ah, then you can call Rancher API directly. @ganeshknr 

`/v2-beta/projects/${project_id}/instances?name=${container_name}`

**Comment by ganeshknr** [comment]
@loganhz  Thank you so much, Now i am able to get the container ID.

BTW I didn't find this API in the docs, Can you provide the link to the docs if it is documented, maybe i would have overlooked few sections of API docs.

And is there anyway we can get container information without knowing project ID?

**Comment by loganhz** [comment]
Here is the API docs. https://rancher.com/docs/rancher/v1.6/en/api/v2-beta/
But maybe this API is not in it. You can use rancher ui and look at the network tab in Chrome to find out  the related requests you want.
container is a project/env scoped resource. So you need the project id. You can use api to list all projects.

**Comment by ganeshknr** [comment]
Oh okay. Thank you @loganhz
