### ISSUE TITLE
UI-add cert config for custom logging target

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#17697]
UI for this https://github.com/rancher/rancher/issues/17696

UI will change ca file to custom logging target

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/13/19)
Confirmed feature. Tested UI.
- Create custom logging target (edit as file)
- Input values for SSL Configuration section in the UI. I used fluentd for my custom target (@type forward)
- Inspect HTTP/API to ensure settings took (request payload and server resp and UI API).

Example:
![image](https://user-images.githubusercontent.com/45179589/52729844-3945cc00-2f77-11e9-8cfd-87ca7a8d4fab.png)

Result:
```
customTarget: {includeSystemComponent: true, outputFlushInterval: 60, type: "clusterLogging",…}
  config: {certificate: "cacert", clientCert: "clientcert", clientKey: "clientpriv",…}
  includeSystemComponent: true
  outputFlushInterval: 60
  outputTags: {}
  type: "clusterLogging"
customTargetConfig: {clientKey: "clientpriv", clientCert: "clientcert", certificate: "cacert",…}
  certificate: "cacert"
  clientCert: "clientcert"
  clientKey: "clientpriv"
  content: "@type forward↵  client_key /fluentd/etc/config/ssl/cluster_c-dln4t_client-key.pem↵  client_cert /fluentd/etc/config/ssl/cluster_c-dln4t_client-cert.pem↵  ca_file /fluentd/etc/config/ssl/cluster_c-dln4t_ca.pem"
```
