### ISSUE TITLE
Error getting Service "\"kube-system/kube-dns" from local store: service "kube-system/kube-dns was not found

### ISSUE THREAD

**Issue by ibayue** [rancher/rancher#17692]
I hava two ingress controller,one is good ,but another error 
ping kube-dns in another pod  resolve is good and the clusters is good 
![snipaste_2019-01-29_16-03-24](https://user-images.githubusercontent.com/11729209/51893604-5cea0d80-23e0-11e9-80a6-9a291042cac0.jpg)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |
|Route|`workload`|

**Comment by loganhz** [comment]
Please provide more info with reproduce steps.

**Comment by ibayue** [comment]
It is normal
But I didn’t do anything.

![snipaste_2019-01-30_10-06-54](https://user-images.githubusercontent.com/11729209/51953316-e77d4c00-2476-11e9-9431-69ce3e0b2340.jpg)

**Comment by superseb** [comment]
Let us know more details on the setup or steps to reproduce if you are still hitting this.
