### ISSUE TITLE
add cert config for custom logging target

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#17696]
custom logging target also need certificate configure

**Comment by aiwantaozi** [comment]
Step to verify:
1. enable logging in advance mode, use the ```edit as File```, input fluentd config and certificate
2. check whether the fluentd config and certificate are generated to secret,  check the secret under system project, cluster.conf, project.conf, rancher-logging-fluentd-ssl
3. check whether the log could deliver success

**Comment by kingsd041** [comment]
Version: master 2.2 (2/15/19)  Image ID: c9eb10780a80
Confirmed fix.  With the logging advance mode enabled, I can view the correct cluster or project level configuration and the correct certificate in the secret under the system project. At the same time, I can receive the log using the advanced mode.
