### ISSUE TITLE
Multi cluster app upgrade with batch size and high intervals not working 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#17701]
rancher/server: 1/29 master

Upgrading with default upgrade strategy works, but with batch size and high interval, the multi cluster app gets stuck in installing. 

- Deployed 5 apps, batch size 2 and interval 600 seconds.

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/21

* Deployed multicluster app with 10 targets
* Set upgrade strategy to rolling, batch size=2, interval=600 and upgraded template version
* First two apps upgraded immediately, the remaining apps were upgraded at 10 minute intervals
