### ISSUE TITLE
Default values for Int in driver schema are incorrect

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#17708]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Go to https://YOURHOST/v3/schemas/amazonElasticContainerServiceConfig.
2. Scroll down to "maximumNodes" field.
![image](https://user-images.githubusercontent.com/19376037/51933668-1506be80-23bf-11e9-83d3-9097ce6e8c60.png)

**Result:**
The values are all 0, but they should reflect how they are declared in the EKS driver:
![image](https://user-images.githubusercontent.com/19376037/51933844-7af34600-23bf-11e9-87a4-4f7708d16ef9.png)

**Other details that may be helpful:**
**For Testing**
When testing, kubernetes should be restarted to view the corrections in the schema. This is related to another bug: https://github.com/rancher/rancher/issues/17712

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master branch 1/29/19

**Comment by soumyalj** [comment]
Observed the issue in v2.1.6 where the schema for amazonElasticContainerServiceConfig showed the defaults as zero 
```
"maximumNodes": {
"create": true,
"default": 0,
"type": "int",
"update": true
},
"minimumNodes": {
"create": true,
"default": 0,
"type": "int",
"update": true
},

```

Tested with master build from Feb 7th. The schema for amazonElasticContainerServiceConfig showed the defaults correctly as below:
<img width="481" alt="screen shot 2019-02-08 at 11 07 15 am" src="https://user-images.githubusercontent.com/18536626/52500014-bea13900-2b91-11e9-9cfa-aab9cc43dc00.png">
