### ISSUE TITLE
Auth user settings missing description text.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17707]
Version - 2.2 master 1/29

**Steps to reproduce (least amount of steps as possible):**
1.  Go to global Setting page

**Result:**  The auth-user-info-max-age-seconds & auth-user-info-resync-cron fields do have descriptions under them.  Add text letting the user know what these fields are for like the other fields on the page.

![image](https://user-images.githubusercontent.com/11514927/51930148-21871900-23b7-11e9-98e7-64b23378ae7c.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/21/19)
Confirmed issue. There is now helptext for these two settings and this text makes sense to me:

![image](https://user-images.githubusercontent.com/45179589/53186469-4e95a880-35be-11e9-939c-35a42f89a764.png)

I also briefly tested this area, change defaults, revert to default, etc.
