### ISSUE TITLE
backupEtcd action returns null resource

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17702]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an RKE cluster
After the cluster has provisioned select the 'Backup Now' action from the actions menu

**Result:**
The action fires and returns a 200 but a null response is sent. The resource should be returned in a 200 similar to other action api's

**Comment by soumyalj** [comment]
Tested with master build from Jan 30. Backup action has a response now:
```
{"kind":"EtcdBackup","apiVersion":"management.cattle.io/v3","metadata":{"name":"c-zkz2z-k65fz","generateName":"c-zkz2z-","namespace":"c-zkz2z","selfLink":"/apis/management.cattle.io/v3/namespaces/c-zkz2z/etcdbackups/c-zkz2z-k65fz","uid":"63d59245-24c1-11e9-9a8f-0242ac110002","resourceVersion":"5932","generation":1,"creationTimestamp":"2019-01-30T19:01:03Z","labels":{"cattle.io/creator":"norman"},"ownerReferences":[{"apiVersion":"management.cattle.io/v3","kind":"Cluster","name":"c-zkz2z","uid":"9ee03912-24bc-11e9-9a8f-0242ac110002","controller":true}]},"clusterId":"c-zkz2z","backupConfig":{"s3BackupConfig":null},"status":{"conditions":null}}

```
For a local backup, the backupConfig object does not have information that it is a local config.
@moelsayed : Shouldn't the backupConfig object have information about local backup ?

**Comment by moelsayed** [comment]
@soumyalj No, the backup configuration is part of the cluster. It's added to the backup object later when it's picked up and processed by the backup controller.
