### ISSUE TITLE
TLS Handshake issue when creating first master node (Custom cluster with RKE)

### ISSUE THREAD

**Issue by sboulkour** [rancher/rancher#17704]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Adding a new node to a fresh and empty custom rancher cluster.

**Result:**
Everythings installs fine using provided command in the UI on this first master node (etcd + control plane roles), but Rancher never gets Cluster / node status.

From the TLS handshake issue, I understand that rancher/rancher is performing an http request and not an https one ?..

The install command : 

```
docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.5 --server https://10.200.107.174:443 --token [HIDDEN] --ca-checksum [HIDDEN] --node-name k8s-2-ms1 --etcd --controlplane

```

**Other details that may be helpful:**
I don't see any errors on the node containers (etcd, apiserver etc.)

Error appears only in rancher/rancher logs : 
```
2019/01/29 16:42:05 [ERROR] cluster [c-z7b9p] provisioning: [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [10.200.107.175]: Get https://localhost:6443/healthz: dial tcp: lookup localhost on 8.8.8.8:53: no such host, log: I0129 16:17:24.596867       1 log.go:172] http: TLS handshake error from 10.200.107.174:60960: tls: first record does not look like a TLS handshake

2019/01/29 16:42:05 [ERROR] ClusterController c-z7b9p [cluster-provisioner-controller] failed with : [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [10.200.107.175]: Get https://localhost:6443/healthz: dial tcp: lookup localhost on 8.8.8.8:53: no such host, log: I0129 16:17:24.596867       1 log.go:172] http: TLS handshake error from 10.200.107.174:60960: tls: first record does not look like a TLS handshake
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:v2.1.5
rancher/rancher-agent:v2.1.5
- Installation option (single install/HA):
Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):
v1.12.4-rancher1-1 (taken from the cluster params in the UI)

- Docker (use `docker info`):

```
# docker info
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.701GiB
Name: k8s-2-ms1
ID: HTZA:FMJQ:PIVB:NTQ2:G63A:IFUP:VP6P:RBVO:PWOG:3SRJ:QUX6:D26R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by loganhz** [comment]
Thanks for the report.
It will be fixed in https://github.com/rancher/rancher/issues/16419

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/16419

**Comment by superseb** [comment]
@sboulkour Based on `dial tcp: lookup localhost on 8.8.8.8:53: no such host`, it seems that your host does not have `localhost` in `/etc/hosts`, and tries to ask Google's DNS for a `localhost`.

Can you check for `127.0.0.1 localhost` in `/etc/hosts` and try again?

The TLS errors usually come from either old nodes that were connected to the cluster and that are not properly cleaned up (see https://rancher.com/docs/rancher/v2.x/en/admin-settings/removing-rancher/user-cluster-nodes/) or just network scanners or people trying to access that IP when they shouldn't (or a DNS entry is pointing to it and users are trying to access the wrong resource).

**Comment by sboulkour** [comment]
Hey @superseb adding the missing `127.0.0.1 localhost` line did the trick. Now I'll try to figure out why this is missing from our CentOS 7 masters ...

Thank you for your time !
