### ISSUE TITLE
Kubelet incorrectly reports Docker Version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17718]
Version: Master 2.2 (1/29/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a DO cluster, for your node template, go to the Engine Options section and pick Latest for the Docker Install URL
- View the node details.

**Result:**
The UI shows that the Docker Version: 18.9.1 but it is actually 18.09.1. This is also seen if you view the node in the API:
```
os": {
"dockerVersion": "18.9.1",
"kernelVersion": "4.4.0-141-generic",
"operatingSystem": "Ubuntu 16.04.5 LTS"
```
Actual version is: 18.09.1

**Comment by superseb** [comment]
This is how `kubelet` reports Docker version, for example, Docker `17.03.2`:

```
> kubectl get nodes -o wide
NAME                     STATUS    ROLES                      AGE       VERSION   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
seb-rancheragent-0-all   Ready     controlplane,etcd,worker   16m       v1.11.6   <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://17.3.2
seb-rancheragent-1-all   Ready     controlplane,etcd,worker   16m       v1.11.6   <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://17.3.2
seb-rancheragent-2-all   Ready     controlplane,etcd,worker   21m       v1.11.6   <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://17.3.2
```

**Comment by davidnuzik** [comment]
So then this is an upstream bug @superseb or possibly just not a bug?

**Comment by zmarcel** [comment]
Hi,

i got the same problem here. 
I updated to Docker Version 18.09.2, but in the UI i see the old Version 17.3.2

# kubectl get nodes -o wide
NAME            STATUS   ROLES               AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
etcdnode01    Ready    controlplane,etcd   54d     v1.13.4   10.59.8.11    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
etcdnode02    Ready    controlplane,etcd   54d     v1.13.4   10.59.8.12    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
etcdnode03    Ready    controlplane,etcd   54d     v1.13.4   10.59.8.13    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
host01	      Ready    worker              54d     v1.13.4   10.59.8.14    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
host02   	  Ready    worker              54d     v1.13.4   10.59.8.15    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
host03   	  Ready    worker              54d     v1.13.4   10.59.8.16    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
host04   	  Ready    worker              54d     v1.13.4   10.59.8.17    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
host05  	  Ready    worker              54d     v1.13.4   10.59.8.18    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
host06   	  Ready    worker              54d     v1.13.4   10.59.8.19    <none>        Ubuntu 16.04.5 LTS   4.4.0-141-generic   docker://18.9.2
host07  	  Ready    worker              7d20h   v1.13.4   10.59.8.23    <none>        Ubuntu 16.04.6 LTS   4.4.0-142-generic   docker://18.9.2
host08  	  Ready    worker              7d20h   v1.13.4   10.59.8.24    <none>        Ubuntu 16.04.6 LTS   4.4.0-142-generic   docker://18.9.2
host09  	  Ready    worker              7d20h   v1.13.4   10.59.8.25    <none>        Ubuntu 16.04.6 LTS   4.4.0-142-generic   docker://18.9.2

**Comment by deniseschannon** [comment]
I don't think this is a bug. This is how it is reported.

**Comment by vincent99** [comment]
They are probably trying to make them semver-compatible, leading zeros are not allowed.
