### ISSUE TITLE
Remove single auth Note: text from Authentication pages.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17710]
Version - 2.2 master 1/29

**Steps to reproduce (least amount of steps as possible):**
1.  Go to Authentication page

**Result:**  There is a note that talks about single authentication only.  I think we can remove this warning now, since the change went in for 2.1 and 2.2 is 6 months past that.  It would be nice to get that space back and we shouldn't keep these messages around forever.

![image](https://user-images.githubusercontent.com/11514927/51934441-d3771300-23c0-11e9-8995-56ff10d84c78.png)

**Comment by cjellick** [comment]
@westlywright lets discuss before you impl

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/11/19)
Confirmed this message is removed.
I also tried setting up AD auth and looking at other providers to make sure it does not show up in other areas on the Authentication page.
