### ISSUE TITLE
UI - Add "user-data" while spinning up EKS nodes

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#17711]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement 
When spinning up EKS nodes we would like to be able to add in `user-data`

**Steps to reproduce (least amount of steps as possible):**
<img width="1503" alt="screen shot 2019-01-29 at 12 13 31 pm" src="https://user-images.githubusercontent.com/31839142/51934088-ac681380-23b7-11e9-940c-49144beda97f.png">

See https://github.com/rancher/rancher/issues/16300

**Environment information**
v2.1.x

**Cluster information**
- Cluster type (EKS):
- Machine type (cloud)

**Comment by westlywright** [comment]
@loganhz this is waiting on a new api field, @daxmc99 will remove the `awaiting-backend` label when its in.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/12/19)
Confirmed enhancement. This adds userData: option which is a multi-line text field where you can enter a script to run. Validated http/api. I tested both by filling in text manually and by reading from a file. This is under Advanced Options when you create / edit the cluster. When you edit your settings remain (are not blanked out). UserData can also be empty. Smoke tested this area.
`"userData": "#!/bin/bash\nset -o xtrace\n/etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments}/opt/aws/bin/cfn-signal --exit-code $? --stack  ${AWS::StackName} --resource NodeGroup --region ${AWS::Region}\ntouch ~/tacos.txt\necho tacos > ~/tacos.txt",`
![image](https://user-images.githubusercontent.com/45179589/52637142-a9772380-2e8b-11e9-8e41-e3fc4be68a57.png)
