### ISSUE TITLE
Catalog App 'mongodb-replicaset' install fails with `Helm template failed` error 

### ISSUE THREAD

**Issue by sdanieru** [rancher/rancher#17726]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. With a Rancher 2.1.5 single install, setup a cluster
2. Attempt to install the 'mongodb-replicaset' Catalog App from the Rancher library with all defaults

**Result:**
Fails with the message:
`Helm template failed. Error: failed parsing --set data: key "Frableaz5" has no value (cannot end with ,) : exit status 1`
**Other details that may be helpful:**
I've tried this with: auth enabled/disabled, and with persistence volume disabled/enabled. For persistent volumes enabled, I've setup a default StorageClass using the 'nfs-client-provisioner', which works great when I manually run deploys w/ persistent volumes, but the helm template doesn't seem to get far enough to actually request a PVC before it fails.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.5
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): bare metal
- Kubernetes version (use `kubectl version`): 1.12.3

- Docker (use `docker info`): 17.3.3

**Comment by sdanieru** [comment]
Is there someone who helps maintain Catalog Apps in Rancher that would want to know about this?

**Comment by loganhz** [comment]
`mongodb-replicaset` has been updated in https://github.com/rancher/charts. Default answer works.
