### ISSUE TITLE
Update docs to show that binlog_format for MySQL/MariaDB need to be set to row

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#1772]
When starting rancher/server against a database server with the default mysql configuration, the user will see a stack trace.

The setting can be configured in the my.cnf file by adding the line `binlog_format = row` to the server section. Or it can be set at server startup time with the command line flag `--binlog_format=row`.

**Comment by vincent99** [comment]
Seems like we should explicitly set this on our connections rather than require non-standard configuration options that affect the whole database.

**Comment by alena1108** [comment]
@cloudnautique what is the reason from switching from default to row format? Would this setting be important to setups using DB replications, or standalone as well? Looks like it can be costly performance wise.

**Comment by cloudnautique** [comment]
The cattle code is making DB calls that use READ COMMITTED and/or READ UNCOMMITTED which requires row-based logging. 

The Issue is very easy to reproduce, and dumps out a stack trace

```
docker run -d --name=database -e MYSQL_ROOT_PASSWORD=password -e MYSQL_USER=cattle -e MYSQL_PASSWORD=cattle -e MYSQL_DATABASE=cattle mariadb

docker run -it --link=database:mysql -p 8080:8080 rancher/server:v0.32.0
```

It should result in a nice stack trace :)

**Comment by kaos** [comment]
:+1: for the suggestion by @vincent99 :)

**Comment by ibuildthecloud** [comment]
I believe is it most likely misconfiguration on the application side that we are using READ_COMMITTED at all.  I will investigate switching to REPEATABLE READ.

**Comment by cloudnautique** [comment]
We decided against changing the setting. Will not change docs, and will be setting rancher server container to use the default binlog format.
