### ISSUE TITLE
Rancher backup configuration is not set/updated correctly

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#17720]
master 29/01

Steps to reproduce:
- Create an RKE cluster with default backup settings
- Try to edit the cluster after it's provisioned
issues:
1 - UI shows the message:
```
This cluster was configured with a legacy ectd snapshot api. The new api replaces the creation time and retention time durations with a simpler creation time in hours and retention count. We have migrated your creation period automatically. Retention count has been configured to the default of 6 backups (current retention duration: 72h), if you're okay with this setting no further action is required. If not, you may change the setting in the advanced settings section.
```
2 - The API view shows `snapshot: true`, which is only related to RKE local backup. For rancher provisioned clusters, this should be `false`
3- When S3 configuration is added to to the backup configuration it works correctly, but if you try edit it again, the UI shows the default settings again and the S3 configuration is discarded.

**Comment by soumyalj** [comment]
With master from Jan 30, the the rke legacy backups are uploaded to s3. These records do not get deleted even when the cluster is deleted.   

<img width="1408" alt="screen shot 2019-01-31 at 10 41 36 am" src="https://user-images.githubusercontent.com/18536626/52077000-d0a52b00-2544-11e9-94a2-7f10ad8fae25.png">

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/1/19)
Confirmed fix. In API (assuming default config for DO RKE cluster) snapshot indeed is false now.
I successfully edit the cluster and saved without any issues; I did not get the UI mentioned in the issue description.
Regarding #3 under the steps to reproduce this was recently tested in a separate issue and is resolved. You can edit a cluster and it will correctly show the previous s3 settings you set when you created it. You can save without issues with s3 as well.
