### ISSUE TITLE
Add Volume Claim Template option doesn't go away if I switch workload type of out stateful set

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17739]
Version - 2.2 master 1/29

**Steps to reproduce (least amount of steps as possible):**
1.  Create a workload that uses stateful set as workload type.
2.  Click on deploy (note that stateful set is preselected)
3.  Go to Volume Accordion and click on Add Volume (note that Volume Claim option is there)
4.  Change Workload type to Scalable deployment
5.  Go back to Volume Accordion and click on Add Volume

**Result:**  Volume Claim option is still available.  Should only be available for Stateful sets.
![image](https://user-images.githubusercontent.com/11514927/51949767-19e16780-23eb-11e9-81a3-f58afb23be1d.png)

**Comment by davidnuzik** [comment]
@tfiduccia or @westlywright can you confirm that we expected with fix that ONLY _**Add a Volume Claim Template**_ option was expected to be removed when we change back to Scalable deployment per steps?
I can confirm when I switch to stateful set the option comes back and when I switch to scalable deployment it goes away.

**Comment by westlywright** [comment]
Correct, the option should be removed but only for this single item.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/7/19)
Confirmed fix. Cannot reproduce after the fix. Follow the steps and when you pick scalable deployment there is no "Add a Volume Claim Template" option. When you pick Stateful Set again the option does come back on the Volume drop down. And again it will go away when you switch back. If you already picked a template it won't be removed from the UI but you cannot continue.
