### ISSUE TITLE
Monitoring - Project owner cannot enable/disable project level monitoring

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17737]
Bug.

Setup: 
- Rancher master on 1/29, single install
- DO cluster, 3 nodes, 1 role on each node

Steps:
- enabled Github Auth
- logged in as `admin` to add a Github user to a project as a `project owner`
- logged in as the Github user
-  tried to enable/disable the project level monitoring when the cluster level monitoring is on

Result:

The cluster owner cannot enable/disable project level monitoring
![screenshot](https://user-images.githubusercontent.com/6218999/51949276-2d8bce80-23e9-11e9-9719-7216298bd953.png)

Expected result:

The project owner should be able to enable/disable project-level monitoring

Other details might be helpful:

This feature worked before and passed the test for previous alpha release

**Comment by thxCode** [comment]
Related: https://github.com/rancher/rancher/issues/16889

**Comment by jiaqiluo** [comment]
The bug fix is validated on master 1/30
Followed the same steps as the ticket describes and got the expected result.

**Comment by hoangnh1806** [comment]
I'm the cluster admin and also the project owner but I can't enable Project Monitoring. I also tried to create another user and set project owner for that, then login with it but still got errors as you describe above. 
Do I have to do exactly steps: enable Github Auth and login with it?

Setup:
- Rancher v2.2.2
- Google Kubernetes Engine cluster with 8 nodes.
