### ISSUE TITLE
Many errors in ClusterController and DeploymentController when enable cluster monitoring

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17733]
Version: Master 2.2 (1/29/19) ImageID: 4e865e7bffb1

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster, enable monitoring, watch rancher server logs

**Result:**
The rancher server logs will report the following repeated many times, however monitoring is functional:
```
2019/01/29 23:49:33 [ERROR] DeploymentController cattle-prometheus/grafana-cluster-monitoring [workloadServiceGenerationController] failed with : error getting app grafana-cluster-monitoring app.project.cattle.io "p-gxlgn/grafana-cluster-monitoring" not found
```
and
```
2019/01/29 23:49:08 [ERROR] ClusterController c-fhkbc [user-cluster-monitoring] failed with : unable to sync Cluster david-do-test1(c-fhkbc): failed to detect the installation status of monitoring components: Kube State Exporter Deployment is deploying
```
After a brief while (minute or so) these repeating errors will stop and monitoring appears to be functioning correctly.

**Other details that may be helpful:**
Single-node rancher install. In my case I created one DigitalOcean RKE cluster using defaults for the node template and default kubernetes (1.13). One cluster node which was 4gb, 2cpu; there is plenty of memory, etc.

**Comment by thxCode** [comment]
@davidnuzik , Can you verify this again?

**Comment by davidnuzik** [comment]
@thxCode it may be a little better but I still see numerous for the ClusterController.
![image](https://user-images.githubusercontent.com/45179589/52804041-7924b600-3040-11e9-846f-75096ff58369.png)

**Comment by thxCode** [comment]
@davidnuzik , yes, we use a loop to detect the installation status of the Monitoring components. During this time, it will print some logs until all components are ready.

Take a look into the logs, you can see that: `monitoring components: [xx, yy, zz]`, the elements of the array is reducing, it means the components are deployed step by step.

**Comment by davidnuzik** [comment]
@thxCode is this normal/expected? I would not expect to see errors for this during this process. I would normally expect errors to be suppressed during this process or for this to be at INFO level or something like that.

**Comment by davidnuzik** [comment]
I think it should be supressed from showing up in stdout/stderr. From an end-user perspective this is a bit confusing to me and I see noise in logs and think there is an error when this is being set up. I might log a support ticket if I was a customer.

**Comment by thxCode** [comment]
@davidnuzik , this is expected. I think to keep a support ticket here is nice.

**Comment by davidnuzik** [comment]
Version: Master (4/15/19)

When you enable cluster monitoring a significant amount of errors are no longer seen as described in the issue description. I now only see five errors for a second then those discontinue -- this seems to only be for a mere instant right after I click "Enable Monitoring"

Since the described issue is resolved I am closing this issue.
Here are the few errors I briefly saw when I enabled monitoring:

```
2019/04/15 20:23:47 [INFO] deploy prometheus operator error
2019/04/15 20:23:47 [ERROR] ClusterController c-v6f47 [cluster-monitoring-handler] failed with : failed to get cattle-prometheus/prometheus-operated endpoints: endpoints "cattle-prometheus/prometheus-operated" not found                                                  
2019/04/15 20:23:47 [ERROR] ClusterController c-v6f47 [cluster-monitoring-handler] failed with : failed to get cattle-prometheus/prometheus-operated endpoints: endpoints "cattle-prometheus/prometheus-operated" not found                                                  
2019/04/15 20:23:47 [ERROR] ClusterController c-v6f47 [cluster-monitoring-handler] failed with : failed to get cattle-prometheus/prometheus-operated endpoints: endpoints "cattle-prometheus/prometheus-operated" not found                                                  
2019/04/15 20:23:47 [ERROR] ClusterController c-v6f47 [cluster-monitoring-handler] failed with : failed to get cattle-prometheus/prometheus-operated endpoints: endpoints "cattle-prometheus/prometheus-operated" not found                                                  
2019/04/15 20:23:51 [ERROR] ClusterController c-v6f47 [cluster-monitoring-handler] failed with : failed to get cattle-prometheus/prometheus-operated endpoints: endpoints "cattle-prometheus/prometheus-operated" not found  
```

While we shouldn't show any errors at all, I find this satisfactory compared to the issues I observed before the fix.
