### ISSUE TITLE
UI creating persistent volume when selecting Volume Claim template

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17738]
Version - 2.2 master 1/29

**Steps to reproduce (least amount of steps as possible):**
1.  Add a GKE cluster
2.  Create a Storage Class using "Google Persistent Disk" as Provisioner
3.  Go to workload and Deploy
4.  Change to Stateful set of "2" pod
5.  Go to Volume Accordion and Add Volume Claim Template
6.  Select the Google storage class & capacity to 10
7.  Deploy

**Result:**  Created 3 volumes.  UI is creating a persistent volume and it shouldn't.
![image](https://user-images.githubusercontent.com/11514927/51949164-be15df00-23e8-11e9-9a80-029467a8000b.png)

Call that UI is making - Shouldn't make the persistentvolumeclaim POST if Volume Claim Template is selected from drop-down.
![image](https://user-images.githubusercontent.com/11514927/51949573-4052d300-23ea-11e9-9e70-575d7ccd7e46.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/8/19)
Confirmed fix. Follow the steps to reproduce and when you deploy the workload the UI is no longer sending the persistentvolumeclaim POST and when I inspect the Volumes tab I only see the two expected volumes (one for each pod).
![image](https://user-images.githubusercontent.com/45179589/52512026-122a7b80-2bc0-11e9-9289-7754d4c983fd.png)

![image](https://user-images.githubusercontent.com/45179589/52512040-1d7da700-2bc0-11e9-8abc-18869df42e86.png)
