### ISSUE TITLE
Monitoring - Cluster owner cannot enable/disable cluster & project level monitoring

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17736]
Bug.

Setup: 
- Rancher master on 1/29, single install
- DO cluster, 3 nodes, 1 role on each node

Steps:
- enabled Github Auth
- logged in as `admin` to add a Github user to a cluster as a `cluster owner`
- logged in as the Github user, go to the `cluster` -> `Tools` -> `Monitoring`
- tried to enable/disable the cluster level monitoring
- when the cluster level monitoring is on, tried to enable/disable the project level monitoring

Result:

The cluster owner cannot enable/disable cluster & project level monitoring
![screenshot](https://user-images.githubusercontent.com/6218999/51949251-1220c380-23e9-11e9-96a9-e4ac4354e89e.png)
![screenshot](https://user-images.githubusercontent.com/6218999/51949276-2d8bce80-23e9-11e9-9719-7216298bd953.png)

Expected result:

The cluster owner should be able to enable/disable cluster & project level monitoring

Other details might be helpful:

This feature worked before and passed the test for previous alpha release

**Comment by thxCode** [comment]
Related: https://github.com/rancher/rancher/issues/16889

**Comment by jiaqiluo** [comment]
The bug fix is validated on master 1/30
Followed the same steps as the ticket describes and got the expected result.
