### ISSUE TITLE
Complete monitoring configuration in GKE

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#17745]
rancher/rancher:master

When enabling `cluster-level` monitoring in GKE, we need to scrap kubelet metrics (AKA. `container_**` metrics ) from `http-metrics` endpoint.

We should let the user to config this in enable monitoring page, or we detect GKE ourself :
> `exporter-kubelets.https` should be `false` when deploying in GKE. Default is `true`.

It came from https://github.com/rancher/system-charts/pull/8#issuecomment-458446962

reproduce steps:
1. Create GKE cluster
2. Enable Monitoring

result:
Go into Prometheus UI, query on Graph page, cannot see any `container_**` metrics.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/19/19)
Confirmed issue. I am now able to see Workload, Pod, and Container charts.
Smoke tested this; ran a stress test on an ubuntu workload, etc and charts appear to be working correctly.
