### ISSUE TITLE
Should set to cert to empty when change from https to http

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#17744]
when I use https before and then change to use http, the cert still there
![image](https://user-images.githubusercontent.com/5936271/51953239-91100d80-2476-11e9-9c48-1af54822bb2e.png)

**Comment by n313893254** [comment]
@aiwantaozi Are you mean after use HTTP and after click save, the cert still there? Sorry, I cannot reproduce.

Here are my steps:
1. Select Splunk and use https, input cert.
2. Click the save button.
3. Change use https and click save button.

Result:
The cert disappears as expected.

**Comment by aiwantaozi** [comment]
Close because after clicked save the cert disappeared
