### ISSUE TITLE
its failed when i update rancher/fluentd v0.1.10 to v0.1.12

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#17749]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/14210543/51956415-83608500-2482-11e9-9756-9a811d97c3d8.png)
![image](https://user-images.githubusercontent.com/14210543/51956465-b6a31400-2482-11e9-8f4c-8c845adba059.png)

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
