### ISSUE TITLE
[Host-Proxy] are there any instructions for starting up with ssl?

### ISSUE THREAD

**Issue by wenlock** [rancher/rancher#1774]
Hi, are there any instructions for setting up the host proxy with an ssl cert?

**Comment by vincent99** [comment]
You probably don't want the host-proxy package anymore... Current versions of Rancher automatically do multiplexing through the server container, browser --> server <-- host agent.

SSL configuration of Rancher in general is in http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/

**Comment by wenlock** [comment]
@vincent99 thanks for the info, this looked like it would solve my problem for this error I get on the client side in console output of the browser

WebSocket connection to 'ws://<rancher server>:8080/v1/subscribe?eventNames=resource.change&include=hosts&include=instances&include=instance&include=loadBalancerConfig&include=loadBalancerTargets&include=loadBalancerListeners&include=instanceLinks&include=ipAddresses&projectId=1a5' failed: Error in connection establishment: net::ERR_TIMED_OUT

noticing it does a websocked connection and we only allow http 80 443 to our servers...

**Comment by vincent99** [comment]
If properly configured the websocket connections for subscribe (automatic updating of the UI) and host-specific stuff (stats, logs, shell) are to the same origin (protocol, host, port) as the API and the UI.  So they should "just work" in ~v0.28+ if you can load the page in the first place*.

You can run rancher/server on port 80 by just changing the `docker run` command, and/or add SSL on top with that link.  Please be sure to use the latest release for SSL as there were some issues in earlier releases.

*: Unless your firewall is doing deep packet inspection and specifically blocking websockets/upgrade.
