### ISSUE TITLE
WorkloadLabels error causes app details to not show workloads

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#17754]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Launch `longhorn`, `drone` or other app with default parameters, I have not done any other operations.
2. The pods of the workloads list are all running

**Result:**

The app active number is 0, and there is nothing in the workload of the details page.
WorkloadLabels appId tag is incorrect.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:master 1/30

- Installation option (single install/HA):
single , HA

**Comment by guangbochen** [comment]
related to rancher/helm in https://github.com/rancher/helm/pull/15

**Comment by rootwuj** [comment]
Version: master 2.2 (1/31/19)
Confirmed fixed.
