### ISSUE TITLE
Custom / Imported cluster status is stuck as "Unavaliable" in the UI, after upgrading to 2.1.6 HA

### ISSUE THREAD

**Issue by PicoCreator** [rancher/rancher#17755]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Upgraded from 2.1.5 to 2.1.6 HA

**Result:**
Clusters are stuck as "unavailable". Interestingly, if one has the full URL to a pod / etc, one is still able to access the logs / ssh in. So a part of me suspect its a UI issue?

**Comment by loganhz** [comment]
@PicoCreator What's the cluster is in unavailable status? Are they still in unavailable state?  Could you describe more about the clusters such as custom/imported/gke and how many nodes in the cluster, please?

**Comment by PicoCreator** [comment]
Following up on progress : I have tried to crate a brand new cluster in GKE to test the import. The cluster seem to end up hanging on the "Waiting" step

![screen shot 2019-01-31 at 10 14 14 am](https://user-images.githubusercontent.com/17175484/52025879-00523400-2541-11e9-9a40-00b99d6aadae.png)

As a side note - if multiple other issues are found for 2.1.6, is there consideration on reverting the stable tag away from 2.1.6?

**Comment by cjellick** [comment]
Can you look at one of the clusters in the api and post the response here (right click view in api).

Be sure for scrub any sensitive data

**Comment by cjellick** [comment]
If you want more help tonight, can you DM on our slack channel? https://slack.rancher.io/

I’m cjellick on there

**Comment by PicoCreator** [comment]
API access via rancher is something i have access to : this is from a "Custom node" test cluster (which doesnt have any production data)

[custom-cluster-api.yaml.txt](https://github.com/rancher/rancher/files/2815546/custom-cluster-api.yaml.txt)

Note that i renamed it to .yaml.txt (because of github limitation)

**Comment by PicoCreator** [comment]
Doing a followup, after trying to debug this with @cjellick - it does not seem like much can be done in restoring the cluster. Currently the solution we took was to spin up a new rancher cluster in GKE, and start spinning up new clusters while transferring any data and workload in between.

The following is the steps involved in getting any relevant information that you may need from an environment stuck in "unavailable" state. But has all the pods access working

1) Search through your history / bookmarks, some of the links may still work.
2) For environments where you may not have a link, open it up in the API
![screen shot 2019-02-02 at 5 54 48 pm](https://user-images.githubusercontent.com/17175484/52162881-e49f8700-2714-11e9-837c-318667483326.png)

3) Search for "links" inside the api, and click on "namespace"
![screen shot 2019-02-02 at 5 55 21 pm](https://user-images.githubusercontent.com/17175484/52162885-f7b25700-2714-11e9-9fe7-cb9ff9f7b3c4.png)

4) Your project information may still be there, go find one that you would need, and get the project ID
![screen shot 2019-02-02 at 6 08 48 pm](https://user-images.githubusercontent.com/17175484/52162937-a8205b00-2715-11e9-9695-ebc98de67b24.png)

5) Access the project workload page using the following URL format `https://<rancher-server>/p/<cluster-id>:<project-id>/workloads` in the above screenshots it would be `https://awesome.rancher.server/p/c-chpgj:p-ks45t/workloads`

6) Once the workload is loaded, you can then start exporting whatever yaml you may need to transfer to a new environment 
![screen shot 2019-02-02 at 6 00 28 pm](https://user-images.githubusercontent.com/17175484/52162921-81fabb00-2715-11e9-950a-245eb7b4fe32.png)

You can even ssh into pods if needed, just try not to "delete" / "restart" them. They may not start back.

---

Hopefully if you encounter this wierd issue, the above can help you in restoring your clusters. And if so do try to add in more information to this issue if possible. So that hopefully we can come up with reliable means to replicate it.

**Comment by superseb** [comment]
Let us know if there are steps to reproduce the issue.
