### ISSUE TITLE
Should not send sasl related info if user not enable them

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#17751]
Now if user doesn't input SASL info will also send SASL type plain, we shouldn't for plain type, we have a validate for check user should also input cert, this will be affected. Can we disable SASL by default, only input data when user enables it.

And we should seperate ssl config and sasl config

![image](https://user-images.githubusercontent.com/5936271/51959353-e22bfb80-248e-11e9-8620-99cf4366ebe7.png)

**Comment by n313893254** [comment]
1. We need separate SSL Configuration and SASL configuration
2. UI pass type to backend only when both username and password is input.

**Comment by davidnuzik** [comment]
@n313893254 May I request confirmation that this is what we are expecting? Submit form without Username/Password for SASL set (empty) therefore request payload sends null or "" for values for sasl (this I was not sure on if we are supposed to still send plain if username/password are empty)

```
kafka: {includeSystemComponent: true, outputFlushInterval: 60, type: "clusterLogging",…}
  config: {type: "kafkaConfig", saslType: null, saslScramMechanism: null, zookeeperEndpoint: null,…}
  brokerEndpoints: ["https://159.65.64.22"]
  saslPassword: ""
  saslScramMechanism: null
  saslType: null
  saslUsername: ""
  topic: "topic"
  type: "kafkaConfig"
  zookeeperEndpoint: null
  includeSystemComponent: true
  outputFlushInterval: 60
  outputTags: {}
  type: "clusterLogging"
kafkaConfig: {type: "kafkaConfig", saslType: null, saslScramMechanism: null, zookeeperEndpoint: null,…}
  brokerEndpoints: ["https://159.65.64.22"]
  saslPassword: ""
  saslScramMechanism: null
  saslType: null
  saslUsername: ""
  topic: "topic"
  type: "kafkaConfig"
  zookeeperEndpoint: null
```

IF we want SASL we input Username/Password (pick Type of Plain or Scram and if Scram pick hash type) and then of course get this information in request payload:

```
kafka: {includeSystemComponent: true, outputFlushInterval: 60, type: "clusterLogging", config: null,…}
  config: null
  includeSystemComponent: true
  outputFlushInterval: 60
  outputTags: {}
  type: "clusterLogging"
kafkaConfig: {brokerEndpoints: ["https://159.65.64.22"], saslScramMechanism: "sha512", saslType: "scram",…}
  brokerEndpoints: ["https://159.65.64.22"]
  saslPassword: "tacosrule"
  saslScramMechanism: "sha512"
  saslType: "scram"
  saslUsername: "John"
  topic: "topic"
  type: "/v3/schemas/kafkaConfig"
  zookeeperEndpoint: null
```

And from UI perspective I can see that SSL configuration is now separate and is above SASL optional config (this looks correct to me).

![image](https://user-images.githubusercontent.com/45179589/52728995-8a54c080-2f75-11e9-9ef5-de930f8a087a.png)

**Comment by aiwantaozi** [comment]
@davidnuzik For the SASL part, if username and password not exist, means user don't enable SASL, so no SASL related field sent to the backend.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/13/19)
Thanks @aiwantaozi 
Closing based on my testing done earlier today. This is working as expected if SASL username/password are not provided then we are sending the correct information (no sasl config in API). SASL is now separate from SSL config and I smoke tested this page from a UI perspective.
