### ISSUE TITLE
Rancher docker upgrade lost settings

### ISSUE THREAD

**Issue by paulmorabito** [rancher/rancher#17752]
**What kind of request is this (question/bug/enhancement/feature request):**
Question or bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade rancher to latest version using watch tower.

**Result:**
All of my cluster settings and longhorn volume settings are gone. Actually, the nodes are still running so for now and everything looks OK, only that the rancher docker that was managing the cluster is no longer doing so.

So, first thing, is there any way I can re-connect to the existing Rancher cluster so it can be managed as it was before?

Secondly, if not, if I start again, can I somehow use my existing longhorn volumes?

Finally and maybe most importantly, I was persisting "/var/lib/rancher" and also "/var/log/auditlog" but my existing cluster data still seems to have been wiped. Did something go wrong here or is there something I missed in terms of folders/data to persist outside the rancher container?

**Environment information**

Latest version from docker hub in HA on bare metal

**Comment by loganhz** [comment]
Which version of Rancher were you using before the upgrade? Did you upgrade it to v2.1.6?

**Comment by paulmorabito** [comment]
I had Watchtower running which checks for updates to containers and does
and pull and restart on them.

I was running the previous stable version (possibly v2.1.5). It updated to
2.1.6.

**Comment by loganhz** [comment]
How did you setup the Rancher HA? Did you setup it with helm https://rancher.com/docs/rancher/v2.x/en/installation/ha/?

**Comment by paulmorabito** [comment]
I deployed the docker container to the machine I wanted to manage the
cluster on. Created the cluster within the WebUI and then ran the commands
it provided to initailise the two nodes. That installed the required
rancher and k8s containers etc.

**Comment by loganhz** [comment]
The link is for Rancher 1.6.X

**Comment by paulmorabito** [comment]
sorry, I'm trying to go through my old links to find what I followed.
Possibly this:
https://andrewlock.net/home-home-on-the-range-installing-kubernetes-using-rancher-2-0/

Essentially, I installed the docker, created the cluster and issued the
commands it provided to setup the nodes.

**Comment by superseb** [comment]
For future reference, please supply the exact commands used to run and upgrade Rancher. Did the persisted directories contain the data before and after the upgrade? Did you get prompted for setting a password and server-url as it were a fresh install?

Let me know if you can still reproduce this.
