### ISSUE TITLE
Support Cloud-init Configuration for Exoscale Node Template

### ISSUE THREAD

**Issue by srueg** [rancher/rancher#17760]
I'd like to be able to specify custom cloud-init for Exoscale node templates. The [Hetzner node driver](https://github.com/mxschmitt/ui-driver-hetzner) for example supports this.
Any chance you can support this?

**What kind of request is this (question/bug/enhancement/feature request):**
/feature request

**Steps to reproduce (least amount of steps as possible):**
Create a new node template for Exoscale.

**Result:**
At no point can the cloud-init be configured.

**Other details that may be helpful:**
The [Hetzner node driver](https://github.com/mxschmitt/ui-driver-hetzner) implements this.

**Environment information**
- Rancher version: v2.1.6
- Installation option (single install/HA): HA
- Rancher UI: v2.1.19

**Comment by srueg** [comment]
If you could point me in the right direction, I'll hack together a PR myself...

**Comment by vincent99** [comment]
The Hetzner driver directly takes a string of userdata, which is easy to use.  Exoscale and most of the other built-in docker-machine drivers only have an option to read userdata from a file on disk, which is not.

**Comment by srueg** [comment]
Let's see how this goes: https://github.com/docker/machine/pull/4668
