### ISSUE TITLE
Alerts using expressions are not always firing

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17763]
Version: Master 2.2 (1/30/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Have cluster monitoring enabled.
- Create an alert group and add at least one rule using an expression such as the following example:
`sum(node_load1) by (instance) / count(node_cpu_seconds_total{mode="system"}) by (instance) * 100`
Is greater than 5 For 1 minute
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/52014751-97fe4680-249d-11e9-9989-2c3f691109c2.png)

**Result:**
The rule will never fire and a notification will never be sent. In some cases after many minutes longer than the times indicated in the alert group they eventually will fire and send notifications.
Try adding another alert such as CPU reservation over 10% for the node and this will fire almost instantly. I also get an email quite quickly for this.
![image](https://user-images.githubusercontent.com/45179589/52014947-1529bb80-249e-11e9-8daa-0438f23f9c08.png)

**Other details that may be helpful:**
Decreasing repeat interval time or any times have no effect. If you look at the chart as seen in the screenshot above for this rule it should have been firing for quite a while as the blue line (CPU utilization) is way over the red line (alert rule requirement).
For my tests I ran `stress --cpu 2` to fully stress both cpus.

**Comment by davidnuzik** [comment]
In some cases alerts eventually will fire many minutes after indicated in wait times under advanced settings.

**Comment by davidnuzik** [comment]
@loganhz Is this just due to a misunderstanding of alerting? The rules in some cases eventually do fire but not per the times indicated for
```
"groupIntervalSeconds": 60,
"groupWaitSeconds": 30,
"repeatIntervalSeconds": 120,
```
I was expecting these to be constantly alerting non-stop in the UI because we are always exceeding 99% CPU load per my rules set and stress on cpu. And I was expecting notifications per those time settings for the alert group. But I seem to get them nearly randomly or about every 7 or so mins

**Comment by davidnuzik** [comment]
Lots of things just seem broken :) I am still getting notifications for an alert group after setting repeat interval time to many many hours. The http resp payload and server response and API are correct but it's still not working correctly per my settings.

**Comment by aiwantaozi** [comment]
@davidnuzik thanks, I will try to reproduce, now we advance option for alert group and alert rule level. The alert rule level advance option will finally affect the alert interval. Where do you edit the alert advance option? 

PS: What we try to implement is the alert rule could inherit the advanced option from alert group, there is an issue to update the UI/UX. Will implement soon.
https://github.com/rancher/rancher/issues/17604
https://github.com/rancher/rancher/issues/17538

**Comment by davidnuzik** [comment]
@aiwantaozi thanks for the fix. Is #17604 what is potentially causing our issue? I see alerts constantly alerting now in UI which is good, but I only got the first notification. I am not getting repeat notifications for any rules in my group.
![image](https://user-images.githubusercontent.com/45179589/52073153-0a296680-2544-11e9-80b1-5d43c000a64a.png)

![image](https://user-images.githubusercontent.com/45179589/52073128-fa118700-2543-11e9-83cd-1243f59c2cca.png)

**Comment by davidnuzik** [comment]
Again this seems to only affect when we have expressions for our alerts; i never get repeat alerts for expression rules. When i create a normal pod rule and create a pod I get notifications immediately (which is strange seems like my Group wait time, group interval time, and repeat interval time are not quite honored). Since this is a specific case (use expressions rules) and other rules don't seem affected probably no longer should be considered a blocker / needed for alpha2.

**Comment by davidnuzik** [comment]
In order to avoid confusion this issue should only track alert rules firing in UI and not notifications.
I have validated that when we have an expression set and we exceed our threshold in the UI we are always alerting now. When we go below that threshold after about 15 seconds we stop alerting; this is acceptable.
Version: Master 2.2 (1/31/19)

**Comment by davidnuzik** [comment]
See #15663 and #17536
