### ISSUE TITLE
Node Status - Disk space bar is red even there is no disk pressure 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#17767]
BUG

Step:
- run rancher: master 1/30, single install
- add an EC2 cluster with 3 nodes, one role on each
- after the cluster is active,  check each node's status

Result:
1. the `Disk Space` bar is red, although the node has a 40GB disk and I do not run any workload on it.
![screenshot](https://user-images.githubusercontent.com/6218999/52016754-b31f8500-24a2-11e9-93d6-007429e25f5d.png)

2. the API shows status is False. 
![screenshot 1](https://user-images.githubusercontent.com/6218999/52016757-b4e94880-24a2-11e9-8195-46428be3fc7a.png)

Other Info:
This behavior does not exist in DO cluster.

**Comment by westlywright** [comment]
@loganhz we're not accounting for when this `OutOfDisk` condition doesn't exist

https://github.com/rancher/ui/blob/master/lib/monitoring/addon/components/node-conditions/component.js#L27

**Comment by jiaqiluo** [comment]
The bug fix is validated on mater 1/31

Steps are the same as the ticket describes, `Disk Space` bars on all nodes are green when there is no disk pressure as expected.
