### ISSUE TITLE
EKS k8 version UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17762]
Version - 2.2 master 1/29

**Steps to reproduce (least amount of steps as possible):**
1.  Start the steps to create a EKS cluster

**Result:**

- [x] The alignment of the drop-down with the k8s version needs to lower so it lines up with the service role radio options

- [ ] Move the drop-down field to the left a bit so it aligns with the Kubernetes version text.

![image](https://user-images.githubusercontent.com/11514927/52013961-9b90ce00-249b-11e9-889f-23307b64db43.png)

- [ ] When I click on the drop-down, the drop-down is not aligned with the field?
![image](https://user-images.githubusercontent.com/11514927/52014027-bbc08d00-249b-11e9-9fb5-256d5e8923da.png)

- [x] Change main title text to say "Cluster Options.  Add the s, since there is more then 1 field.
![image](https://user-images.githubusercontent.com/11514927/52014123-f1fe0c80-249b-11e9-9c0a-faa8cf8f6159.png)

**Comment by westlywright** [comment]
Had to roll back some changes on master this will be on hold until we can merge again.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/7/19)
Confirmed the 2 of 4 fixes (the first and last issues were fixed only). A new issue was created to track the other two issues that still need fixing and a separate PR to resolve see: #17914 
- Now reads "Cluster Options" with the 's'
- Kubernetes Version drop-down and Radio buttons for Service Role are now aligned.
