### ISSUE TITLE
Editing a cluster does not retain few configurations set for etcd snapshots in UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17772]
Rancher Version: Master

Steps:
Case 1:
1. Create a DO cluster with default settings which has local backup and `Snapshot Creation Period` as 12h (or have any number set )
2. Once the cluster is created, edit the cluster and the etcd "Snapshot Creation Period" is shown as `0 `
<img width="472" alt="screen shot 2019-01-30 at 3 17 20 pm" src="https://user-images.githubusercontent.com/18536626/52019312-44422c00-24a2-11e9-8b9b-1b6f52de28d4.png">

The snapshot creation period should be retained on the edit screen.

Note: This same issue is seen when a cluster is created with S3 backup too.

Case 2:
1. Create a DO cluster with etcd snapshot target set to S3 and other related valid settings.
2. Once the cluster is created, edit the cluster. etcd snapshot target changes to `local`

<img width="1065" alt="screen shot 2019-01-30 at 4 00 51 pm" src="https://user-images.githubusercontent.com/18536626/52021014-3f807680-24a8-11e9-80f6-e7940cb86394.png">

etcd snapshot target set to S3 should not change.

**Comment by cjellick** [comment]
Try to fix for alpha, but not a blocker

**Comment by davidnuzik** [comment]
Case 1 passes. Case 2 does not. I configured s3 snapshot target and when I edit my cluster it shows local again, incorrect snapshot creation period of 12 hours (I set it to 1) and correct retention count (I set 4 and it is 4) but It is set to local even though I picked s3. Upon creation http was correct and we did set s3 for etcd backup.

**Comment by westlywright** [comment]
Currently waiting on a back-end change from @moelsayed to change the default of `snapshot` in the ETCD services to be changed from `true` to `false`. When that is in I'll have the fix ready for this shortly after.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/1/19)
Case 2 is now passing. When I edit my cluster my s3 settings are there exactly as I specified when I created the cluster.
![screen shot 2019-02-01 at 9 46 38 am](https://user-images.githubusercontent.com/45179589/52153740-62da2b80-2638-11e9-9ad9-7dca5c1da914.png)
