### ISSUE TITLE
Db transaction deadlock on clean install of v0.32.0, external mariadb

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#1777]
Creating issue per request by @deniseschannon 
Docs issue is #1772.
Complete start logs on pastebin: http://pastebin.com/7mi2U11i

**Comment by aruneli** [comment]
Verified in latest master (with fix) that this change is working. Tested basic work flows.

**Comment by kaos** [comment]
Confirmed. We're up & running on our mariadb cluster now. :+1:
