### ISSUE TITLE
Pods can not resolve domain if they are not working on the node which kube-dns is running on

### ISSUE THREAD

**Issue by adalga** [rancher/rancher#17784]
I created 3 nodes cluster via Rancher 2.1.2  with the configuration below:

Kubernetes version: v1.11.3-rancher1-1
Network Provider Flannel (I also tried with Canal)
The other setting are default.

All of my 3 nodes have etcd, control plane and worker role. I use Ubuntu 16.04 as a host OS. Docker version is 17.03.2-ce . 

The problem is pods only can resolve domain name when they work on the same node kube-dns work on.
I could not find the reasonable cause for this situation. Would someone help me ?

**Comment by superseb** [comment]
It means that there is no functional overlay network. See https://rancher.com/docs/rancher/v2.x/en/installation/references/ for the required ports (note, its UDP). Please also run through the troubleshooting steps for networking as described on https://rancher.com/docs/rancher/v2.x/en/troubleshooting/networking/

**Comment by adalga** [comment]
Thank you very much for quick response!

I missed to open 8472/udp port. I did it and it works now.
