### ISSUE TITLE
"Create" button at end of Node Template Amazon EC2 edit

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#17781]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
I created a new Amazon EC2 Node Template. When I later edit it, the button at the end reads "Create", it should read "Update" (or "Save").

**Result:**

**Other details that may be helpful:**
Firefox 64.0.2, MacOS 10.14.2 (Mojave)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
v2.1.6

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
Had to roll back some changes on master this will be on hold until we can merge again.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/6/19)
Confirmed fix. When you edit your ec2 node template you'll now see a "Save" button at the end. Tested this to ensure it is still functioning correctly. HTTP/API looks good. Tested some others as well. When I edit them I also get a Save button. Also created new node templates and confirmed we still see "Create" button in that case when it's indeed our first time creating.
