### ISSUE TITLE
Kubelets fail to start on a Ubuntu 16.04 setup with Docker 18.09

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17780]
Version: Rancher v1.6.26-rc7
K8s: v1.11.6-rancher1-2
Docker version: 18.09

Steps:

1. Create a kubernetes setup using Ubuntu 16.04 nodes with Docker 18.09
kubelets fail to start with the below error:
```
(Container should have been running but is in error state. Check logs for more information.: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate") 

```

**Comment by alena1108** [comment]
@soumyalj does the same issue happen on k8s 1.12?

**Comment by soumyalj** [comment]
@alena1108 : k8s 1.12 worked fine with Docker 18.09. Automation runs succeeded as well.
