### ISSUE TITLE
Random nodeport

### ISSUE THREAD

**Issue by RRadziejewski** [rancher/rancher#17783]
Hello, I have a question.

While creating a chart I am giving the user the possibility to choose nodePort.
I would also like to give them the possibility to not choose but make it auto-generated from free ports in range 30000 - 32676 as it is in simple deployment via Rancher UI.
Does anybody have some advice? How to create service for it?

Regards

**Comment by vincent99** [comment]
That is the default behavior of [NodePorts](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport), just don't set the `nodePort` to request a specific one if you don't want a specific one (or wrap it in an `{{if}}` condition).

Please use our forum, slack channel, or the kubernetes community slack for things like this that are not code issues with the product.
