### ISSUE TITLE
Cannot move an existing namespace into new project

### ISSUE THREAD

**Issue by ximbal** [rancher/rancher#17786]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG/Question

**Steps to reproduce (least amount of steps as possible):**
An existing namespace created outside rancher will not allow to be moved into a new project:

Tried selecting namespace and button to move to project is grayed out.
Tried to edit the namespace, select the target project and ends in error:
projects.management.cattle.io "p-b9fkf" not found: undefined
![rancher](https://user-images.githubusercontent.com/19576367/52062619-d730a400-253e-11e9-859c-21b8baabc86a.gif)

![rancher2](https://user-images.githubusercontent.com/19576367/52062671-f62f3600-253e-11e9-9905-0e7fb2cbdf68.gif)

**Result:**
Unable to move namespace

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.1
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported GCP
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud 
![rancher3](https://user-images.githubusercontent.com/19576367/52062796-2f67a600-253f-11e9-9f29-69b2baea73d9.gif)

- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1", GitCommit:"5c4fddf874319c9825581cc9ab1d0f0cf51e1dc9", GitTreeState:"clean", BuildDate:"2018-11-30T16:18:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
docker info
Containers: 15
 Running: 1
 Paused: 0
 Stopped: 14
Images: 194
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 4QNB:QFLV:CCMZ:F6PT:2JDR:JGQP:ZUHW:QNJK:ANQO:3B6G:Q775:NGNP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 57
 System Time: 2019-01-31T15:02:10.6694912Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by akkie** [comment]
I have the same issue after upgrading from Rancher 2.1.6 to 2.2.3-rc4. All my catalog apps that were previously installed into the Default project have currently now project association. If I try to move them again into the Default project, I get the same error: projects.management.cattle.io "p-jzk5q" not found: undefined

**Comment by RSWilli** [comment]
Same issue here: Move is grayed out and changing the project through settings panel shows

"Move Error
Unknown action: move"

Rancher version:

Rancher | v2.2.6
-- | --
User Interface | v2.2.90
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1

**Comment by metal3d** [comment]
I get the same with rancher cli

```
$ rancher --version
rancher version v2.2.0

$ rancher project
rancher project
ID                NAME          STATE     DESCRIPTION
c-t6c42:p-2x8t7   Default       active    Default project created for the cluster
c-t6c42:p-fd9k6   System        active    System project created for the cluster
c-t6c42:p-jfn58   my-infra   active  

$ rancher namespaces move drone c-t6c42:p-jfn58
FATA[0000] Namespace drone cannot be moved     

$ rancher namespaces
ID                 NAME               STATE     PROJECT           DESCRIPTION
default            default            active    c-t6c42:p-2x8t7   
drone              drone              active    c-t6c42:p-2x8t7  
...
```

**Comment by superseb** [comment]
The `cattle.io/appIds` annotation blocks the namespace from being moved as there is an App installed into it. If this is not the case, or you think something else is wrong, please report the API output for the namespace and we can investigate.

**Comment by RSWilli** [comment]
> 
> 
> The `cattle.io/appIds` annotation blocks the namespace from being moved as there is an App installed into it. If this is not the case, or you think something else is wrong, please report the API output for the namespace and we can investigate.

this is exactly my situation!

I wanted to move the efk from my "default" project to a "logging" project, but I couldn't. It would've saved me quite some time reconfiguring it!

Could it be possible that we can move apps to other projects in the future?

**Comment by Ronsevet** [comment]
So what can I do currently to add a namespace via kubectl to an existing project (default for instance)? this is a blocker for us as we want to automatically create separate namespaces as part of our ci/cd

**Comment by lasc** [comment]
Is there a way to force move? Old project ID is not exist anymore.

**Comment by erSitzt** [comment]
@superseb is the blocking intentional because moving a namespace with apps deployed is not supported/working ? Or just a precaution ?

**Comment by harshsharma22** [comment]
change the annotation and label of your current name space  with the cluster id and new project id
    for example old project id:-
annotation
    field.cattle.io/projectId: xx-yy:z-kkk
label
    field.cattle.io/projectId: z-kkk
the new project id
annotation
    field.cattle.io/projectId: xx-yy:z-lll
label
      field.cattle.io/projectId: z-lll
