### ISSUE TITLE
DO template for rancher OS fails with default settings

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#17795]
Rancher master 31/01

Steps to reproduce:
- Create a new DO template 
- Use Rancher OS v:1.4.2

Problem:
The default droplet size selected is 2GB, which has 40 GB disk. This is incompatible with the ROS image. Provisioning fails with the error:
```
Error creating machine: Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 Cannot create a droplet with a smaller disk (40GB) than the image (50GB)
```

**Comment by cjellick** [comment]
Following up with @niusmallnan on why the image is 50 GB

**Comment by niusmallnan** [comment]
It seems that DO size does not support 40GB.
https://www.digitalocean.com/pricing/

**Comment by cjellick** [comment]
@deniseschannon apparently, we don't control the template size. Can we reach out and see if it can be reduced?

**Comment by cjellick** [comment]
Reached out. Can't be reduced. @westlywright @vincent99 can we bump up the smallest DO node to have 50gb disk

**Comment by davidnuzik** [comment]
@cjellick we still have smaller droplet sizes but I presume we just wanted the _default_ to be larger than 40GB disk?

> Reached out. Can't be reduced. @westlywright @vincent99 can we bump up the smallest DO node to have 50gb disk

I also notice it's not possible for me to pick older ROS; expected? All of these are grayed out.
![image](https://user-images.githubusercontent.com/45179589/53127848-ab428600-3520-11e9-9eda-c3a74b3427a8.png)

**Comment by cjellick** [comment]
> @cjellick we still have smaller droplet sizes but I presume we just wanted the _default_ to be larger than 40GB disk?

Correct. just default. Beyond that, you're on your own

> I also notice it's not possible for me to pick older ROS; expected? All of these are grayed out.

I think this is fine. You cannot spin up ROS v1.4.3 in the DO UI either I don't think. @westlywright  what makes you grey them out? A flag on the DO UI?

**Comment by davidnuzik** [comment]
The DO UI lets me spin up ROS v1.4.3 it just asks for an ssh key to do that. (So not sure why it's grayed-out in the dropdown)

**Comment by vincent99** [comment]
The UI filters the API response for images that have an appropriate `slug` (containing something in [this list](https://github.com/rancher/ui/blob/master/lib/nodes/addon/components/driver-digitalocean/component.js#L15-L28)), and ROS 1.4.3 has a null slug for some reason.  DO could probably fix it.

![image](https://user-images.githubusercontent.com/753917/53196814-23b74e80-35d6-11e9-974d-6e6745060036.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/21/19)
Confirmed issue. Default has now changed to something greater than 40GB disk size:
![image](https://user-images.githubusercontent.com/45179589/53199488-76940480-35dc-11e9-8aa0-86b3b5948520.png)

The conversation around being unable to select ROS 1.4.3 has been taken offline as this is not related to this issue specifically.

**Comment by davidnuzik** [comment]
The slug issue was reported to DigitalOcean.
