### ISSUE TITLE
HA UI - Unable to search for users or groups

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#17796]
rancher/rancher:master 1/31
HA setup

Searching for users or groups in an HA setup does not function. This occurs for local users, and users from external authentication.

To reproduce:
* Create an HA setup w/ master
* Create a cluster 
* Add a local user
* Attempt to add the user as a project member to a project

Expected:
* The user can be searched for and added

Actual:
* No users are found when searching

When authentication is enabled (Github, AD), users do not appear in search fields for adding members to projects/clusters, or when adding authorized users to site authentication.

![screen shot 2019-01-31 at 2 55 30 pm](https://user-images.githubusercontent.com/21316915/52088116-466ebe00-2568-11e9-8034-f4bff6b5648a.png)
![screen shot 2019-01-31 at 2 56 12 pm](https://user-images.githubusercontent.com/21316915/52088162-5f776f00-2568-11e9-9d3d-10fa2608d2ad.png)

The API response returns correctly and returns all of the principals searched for.

**Comment by cjellick** [comment]
looking at the developer tab, users are being return in the calls to the principals api. example response:
```
{
  "type": "collection",
  "links": {
    "self": "https://brandonha.qa.rancher.space/v3/principals"
  },
...
  "resourceType": "principal",
  "data": [
    {
      "baseType": "principal",
      "created": null,
      "creatorId": null,
      "id": "github_user://2473240",
      "links": {
        "self": "https://brandonha.qa.rancher.space/v3/principals/github_user:%2F%2F2473240"
      },
      "loginName": "cjellick",
      "me": true,
      "memberOf": false,
      "name": "cjellick",
      "principalType": "user",
      "profilePicture": "https://avatars1.githubusercontent.com/u/2473240?v=4",
      "provider": "github",
      "type": "principal"
    }
  ]
}
```

UI issue?

**Comment by sangeethah** [comment]
@westlywright This issue is not seen in single Node installs. Happens only on HA setups.

**Comment by bmdepesa** [comment]
UI - latest2

User is able to search for both external auth users and groups, as well as local users.
