### ISSUE TITLE
If Cluster endpoint cert throws Parse error, error won't clear properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17793]
Version - 2.2 master 1/31

**Steps to reproduce (least amount of steps as possible):**
1.  Go to RKE cluster, click on Advanced Options
2.  Go to Authorized Cluster Endpoint
3.  Read from file for cert with invalid data (this throws a parsing error)
4.  Remove cert info and try to create cluster

**Result:**  Parsing error won't go away.  So I can't create a cluster now.  Even if I switch RKE provider (like move to Azure).  The parsing error won't go away.

**Comment by cjellick** [comment]
UI bug? @westlywright or @erikwilson can you discuss and figure out if its UI or backend?

**Comment by westlywright** [comment]
@cjellick if the parsing error is happening when we read the cert then its a UI bug.

**Comment by erikwilson** [comment]
Yes, I talked with Wes and Tani and confirmed it was a UI issue, in the API we aren't currently doing any validation on the certs so will take any value.

**Comment by cjellick** [comment]
I missed the part where Wes unassigned you. Got it

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/11/19) Confirmed fix.
A parse error is not thrown. Rather, upon attempt to submit form (Create button) the form is checked and you will get a simple message of "Certificate is invalid". Once this text field for the cert is empty or valid only then may I submit the form.
I can create other clusters afterwards as well without any issues. I smoke tested this area as well. HTTP/API looks good for cluster creation.
