### ISSUE TITLE
Multi-cluster app is loading every template and version before bringing up apps page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17790]
Version - 2.2 master 1/30

**Steps to reproduce (least amount of steps as possible):**
1.  Add a catalog that has lots of templates
2.  Go to Multi-Cluster Apps page

**Result:**  Page looks like it hangs because it's loading every single app and every single template of the app before bringing up the App page.  So it consistently looks like it's broken.  Please load page same way we load the page in the Projects section.

**Comment by vincent99** [comment]
No bueno, loading all template versions is dozens of megabytes and seconds if you have something like Helm Stable on: https://github.com/rancher/ui/blob/master/lib/global-admin/addon/multi-cluster-apps/index/route.js#L11

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/1/19)
Confirmed fix. Now when you load the MC Apps page it will launch instantly; inspected http and I don't see us trying to load all the catalogs. Now this loading is only happening when we launch catalog apps, as expected and performance here is decent. I smoke tested this area and tried to narrow down catalogs by category/catalog and all at once and my browser did not hang too long.
The performance is now the same as when we launch catalog apps at the project level.
