### ISSUE TITLE
Adding Digital Ocean host fails

### ISSUE THREAD

**Issue by bilal** [rancher/rancher#1779]
Adding Digital Ocean hosts fails with error "digital ocean requires a valid region". 

**Rancher Info:**

Rancher	v0.32.0
Cattle	v0.75.0
User Interface	v0.40.0
Rancher Compose	beta/latest

**Digital Ocean Host options:**

Image: Ubuntu-14-04-x64
Size: 1gb
Region: New York 3

![image](https://cloud.githubusercontent.com/assets/60473/9206546/843ca988-4036-11e5-9e89-6065cd367e28.png)

**Comment by vincent99** [comment]
@bilal can you try this again?  The Rancher UI is pretty much just a fronted for `docker-machine`, and that message comes from it when the region passed in does not match a list of regions they pulled from their API (https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go#L135).  So I'm guessing the API response did not contain `nyc3` for you for some reason, and that may have been transient.

If it fails again, the docker-machine & go-machine-service related lines in the logs for the `rancher/server` container will be of interest. Please be sure to mask your DigitalOcean token from them before posting.

**Comment by deniseschannon** [comment]
@bilal If you are still having this issue, please re-open.
