### ISSUE TITLE
RKE cluster provisioning takes long time to complete (~12 minutes for 3 nodes).

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17794]
Rancher server version - Build from master - Jan 31

Steps to reproduce the problem:
Create DO cluster with 3 nodes.
Takes about 12 minutes for the cluster provisioning to complete.
It takes several failed attempts , before provisioning succeeds.

root@santestserver01:~# grep "c-t2ddc" logs | grep " provisioning: Initiating Kubernetes cluster"
2019/01/31 19:26:29 [INFO] cluster [c-t2ddc] provisioning: Initiating Kubernetes cluster
2019/01/31 19:29:24 [INFO] cluster [c-t2ddc] provisioning: Initiating Kubernetes cluster
2019/01/31 19:33:37 [INFO] cluster [c-t2ddc] provisioning: Initiating Kubernetes cluster
2019/01/31 19:34:18 [INFO] cluster [c-t2ddc] provisioning: Initiating Kubernetes cluster
root@santestserver01:~#

**Comment by moelsayed** [comment]
I checked the logs from the rancher server, and commented on each case:
```
2019/01/31 19:26:29 [INFO] cluster [c-t2ddc] provisioning: Initiating Kubernetes cluster // initial run, when one node couldn't be reached. This completed successfully.

2019/01/31 19:29:24 [INFO] cluster [c-t2ddc] provisioning: Initiating Kubernetes cluster // subsequent run, the unreachable node was added . This completed successfully. At this point the cluster is fully operational.

2019/01/31 19:33:37 [INFO] cluster [c-t2ddc] provisioning: Initiating Kubernetes cluster // cluster is being updated, didn't complete with error "[INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF". This is possibly a networking timeout. 

2019/01/31 19:34:18 [INFO] cluster [c-t2ddc] provisioning: Initiating Kubernetes cluster // retrying cluster update again. completed successfully
```
It's possible that the error was stuck in the UI due to the the cluster conditions not being cleared issue. I tried to reproduce this several times with no problems.

**Comment by alena1108** [comment]
@sangeethah can this be tested on other cloud providers like ec2? to confirm that it's a do issue

**Comment by sangeethah** [comment]
Tried to provision a 3 node ec2 cluster.

It takes about ~5 minutes to provision the cluster after the nodes have been created.
```
2019/02/01 18:48:58 [INFO] cluster [c-dxgkq] provisioning: Initiating Kubernetes cluster
2019/02/01 18:52:05 [INFO] cluster [c-dxgkq] provisioning: Initiating Kubernetes cluster
```
