### ISSUE TITLE
add logging added filter tags in the UI

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#17808]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
For users who want to use external `fluentd-aggregator` to filter logs by event tags, they would appreciate this info so they can filter and parse logs accordingly.

e.g, event tag with `foo.**`
```
<filter foo.**>
  @type grep
  regexp1 log ERROR
</filter>
```

**Result:**
Addding rancher used event tags to the rancher logging UI so user can use it later on.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single/HA

**Comment by paynejacob** [comment]
With logging v2 introduced in rancher 2.5, you can organize logs into groups based on pod attributes.  If you configure the logs to forward to another fluentd instance, the tags are passed as well.

https://rancher.com/docs/rancher/v2.x/en/logging/v2.5/
