### ISSUE TITLE
etcd restore fails on a cluster with prometheus monitoring enabled

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17804]
Version: Master

**Steps to reproduce (least amount of steps as possible):**
1. Create a 3 node DO cluster with all 3 roles on each node
2. Enable monitoring and create few workloads
3. Perform backup
4. Perform restore from the backup

Restore fails with the below error:
```

Failed to ensure monitoring project name: failed to find "cattle-prometheus" Namespace: Get https://abcd:6443/api/v1/namespaces/cattle-prometheus?timeout=30s: dial tcp ancd:6443: connect: connection refused; Failed to download etcd snapshot from backup server [abcd], exit code [1]: time="2019-02-01T01:08:55Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"

```
Cluster is stuck in updating state

**Comment by moelsayed** [comment]
@soumyalj What was the OS on those nodes ?

**Comment by soumyalj** [comment]
@moelsayed : Ubuntu 16.04, K8s v1.13.01-rancher1-1

**Comment by soumyalj** [comment]
@moelsayed : I see that restore fails for a regular DO cluster with local etcd backup set (Not specific to prometheus) with the same error as above.
```

Failed to download etcd snapshot from backup server [a.b.c.d], exit code [1]: time="2019-02-01T23:30:46Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"

```

**Comment by moelsayed** [comment]
A regression caused by a fix for #17521, reverted for now.

**Comment by soumyalj** [comment]
Tested with master build from Feb 4th. etcd backup/restore is functional with no data loss.

**Comment by soumyalj** [comment]
Tested with master build from Feb 4th. Created a cluster and enabled prometheus monitoring. 
Performed backup and restore several times. Cluster was restored successfully with no data loss.
