### ISSUE TITLE
Display additional variables in app catalog

### ISSUE THREAD

**Issue by dawidmalina** [rancher/rancher#17813]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
Go to app catalog and launch one of the chart available (from the library). There is no option to edit particular parameters like we have when you try to launch regular helm chart. There is only way to answare questions provided in particular chart. It would be very nice improvment if we could configure both: questions and custom parameters.

![zrzut ekranu 2019-02-1 o 20 47 07](https://user-images.githubusercontent.com/5910851/52146432-fe34c600-2663-11e9-8f52-9c34290c1831.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
Hi @dawidmalina , do you mean you would like to have a custom answers section below the questions?

Actually you can configure both questions and custom parameters. 

1. Find an app in Library
2. Click `Launch`
3. Answer some questions 
4. Click `Edit as YAML` 
5. Append customized answers in the yaml editor such as `hello.test: foo`

Both custom answers and  answers with questions will be applied for the app

**Comment by dawidmalina** [comment]
Yes I know that you can edit as yaml but I was rather thinking about ability to add special type o question in questions.yml. I don't know how this is implemented in regular helm. But when added it will be possible to add simple key, value sections several times and this will be used by the app.
