### ISSUE TITLE
Rancher agent containers need to be hidden in UI when creating hosts running docker 1.8 on server that has been upgraded

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1781]
While upgrading server to latest version (with fix), these random containers should not be seen from UI/API.

Docker version - 1.8
Rancher version - 0.32.0

![image](https://cloud.githubusercontent.com/assets/7720752/9230013/cf245902-40d4-11e5-9178-91d6cc2889e7.png)

**Comment by deniseschannon** [comment]
In order to test, you'll need to spin up a new setup to see that they don't show up. We don't have a cleanup for the containers once they are in Rancher.

**Comment by ibuildthecloud** [comment]
This is an issue with 1.8.  In 1.7 and earlier these containers were ignored but 1.8 introduced a breaking change.  We have a patch for it in this weeks build.

**Comment by aruneli** [comment]
Verified the fix. Random containers are hidden now.

Rancher 	v0.35.0-rc4
Cattle 	v0.86.0
User Interface 	v0.45.0
Rancher Compose 	beta/latest
