### ISSUE TITLE
MultiClusterApp upon upgrade creates some extra revisions showing just the uuid change

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#17818]
Rancher server build from master Jan 31.

HA setup with 2 DO clusters.

Steps to reproduce the problem:
1) Create a Multi Cluster App with 2 targets in cluster1/p1 and clusert2/p2 

2) After the app is in "active" state, click on Upgrade option and change some parameter(I changed the globaldns hostname for grafana app) and upgrade.

3) After the app is "active" again, click on Rollback option and check the dropdown. The dropdown should list only 2 revisions (original and the one after upgrade). But I see some more revisions listed that show only the ID being different than other revisions.

Screenshot:
<img width="992" alt="screen shot 2019-02-01 at 1 36 26 pm" src="https://user-images.githubusercontent.com/1470602/52151011-7f6d6800-2626-11e9-8e78-c29429b2b44f.png">

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/21

* Created cluster
* Created multicluster app
* Upgraded multicluster app several times
* The only revisions present were from changes during upgrade, there are no revisions with just a uuid change.
