### ISSUE TITLE
Enable local backup by default in the API layer

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#17817]
Currently, rancher local backups are enabled by settings through the UI. We need to also enable it by default on the API level.

**Comment by moelsayed** [comment]
@soumyalj there are 2 cases:
- `snapshot: true`: rancher local backup (backupConfig) will NOT be enabled by default, since we don't want two types of backups simultaneously..
- `snapshot: false` or no `snapshot` at all: rancher local backup (backupConfig) will be enabled by default

**Comment by soumyalj** [comment]
Tested with master build from Feb 19. The following three cases were performed:
1. `snapshot=true`:  Created a cluster using rancher API with `snapshot=true`. Cluster was created successfully with the below config set in the API. Backup config was not present as expected. 
```
services": {
"etcd": {
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": true,
"type": "/v3/schemas/etcdService"
},
```

2.  `snapshot=false`:  Created a cluster using rancher API with `snapshot=false`. Cluster was created successfully with the below config set in the API. Backup config was present as expected. 

```

services": {
"etcd": {
"backupConfig": {
"intervalHours": 12,
"retention": 6,
"s3BackupConfig": null,
"type": "/v3/schemas/backupConfig"
},
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": false,
"type": "/v3/schemas/etcdService"
}

```

3.  No snapshot provided in the rke config:  Created a cluster using rancher API with no snapshot field in the rke config. Cluster was created successfully with the below config set in the API. Backup config was present with `snapshot: false` as expected.
