### ISSUE TITLE
UI for creating alibaba ACK managed kubernetes

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17825]
Add support for creating managed kubernetes cluster when using alibaba ACK driver

1. Available Regions & AZs are different from non-managed type:
![image](https://user-images.githubusercontent.com/5697937/52159555-f5cea080-26e0-11e9-9c80-f74f912e7e50.png)
2. No need for non-managed clusters' configurations:
```
	SSHFlags                 bool   `json:"ssh_flags,omitempty"`
	MasterInstanceChargeType string `json:"master_instance_charge_type,omitempty"`
	MasterPeriod             int64  `json:"master_period,omitempty"`
	MasterPeriodUnit         string `json:"master_period_unit,omitempty"`
	MasterAutoRenew          bool   `json:"master_auto_renew,omitempty"`
	MasterAutoRenewPeriod    int64  `json:"master_auto_renew_period,omitempty"`
	MasterInstanceType       string `json:"master_instance_type,omitempty"`
	MasterSystemDiskCategory string `json:"master_system_disk_category,omitempty"`
	MasterSystemDiskSize     int64  `json:"master_system_disk_size,omitempty"`
	MasterDataDisk           bool   `json:"master_data_disk,omitempty"`
	MasterDataDiskCategory   string `json:"master_data_disk_category,omitempty"`
	MasterDataDiskSize       int64  `json:"master_data_disk_size,omitempty"`
```
3. Enable The `PublicSlb` option so that we can connect to the cluster without providing the client cert

**Comment by loganhz** [comment]
@gitlawr Please validate it after UI gets merged

**Comment by gitlawr** [comment]
1. Confirmed with Aliyun team that the `1.11.5` version does not support `publicSlb` option. So we need to use the latest `1.12.4-aliyun.1` that supports it.
2. NumsOfNodes of a managed cluster has a minimum of 2. It would be better to have this validation in the UI.

**Comment by gitlawr** [comment]
To validate:
1. Be able to create/delete a managed ACK cluster
2. Be able to create workload, LB, use the cluster kubectl terminal in an active managed ACK cluster

Notes:
The provision option we use is only available in Singapore region(ap-southeast-1) at the moment. According to aliyun team, support for other regions will be added in late Feb.

**Comment by rootwuj** [comment]
Create a managed ACK cluster error, the error log is as follows:
```
time="2019-02-20T04:15:59Z" level=info msg="provisioning cluster lawrm2: Set up k8s DNS configuration successfully"
time="2019-02-20T04:15:59Z" level=info msg="Cluster lawrm2 is running"
time="2019-02-20T04:16:03Z" level=info msg="service account token generation failed, retries left: 5"
time="2019-02-20T04:16:33Z" level=info msg="service account token generation failed, retries left: 4"
time="2019-02-20T04:17:03Z" level=info msg="service account token generation failed, retries left: 3"
time="2019-02-20T04:17:33Z" level=info msg="service account token generation failed, retries left: 2"
time="2019-02-20T04:18:03Z" level=info msg="service account token generation failed, retries left: 1"
time="2019-02-20T04:18:33Z" level=error msg="retries exceeded, failing post-check"
2019/02/20 04:18:33 [INFO] kontainerdriver aliyunkubernetescontainerservice stopped
2019/02/20 04:18:33 [ERROR] ClusterController c-r9w2s [cluster-provisioner-controller] failed with : Post https://161.117.2.10:6443/api/v1/namespaces: x509: certificate signed by unknown authority
```

**Comment by rootwuj** [comment]
Edit ACK cluster, cannot choose Kubernetes version.
<img width="1664" alt="edit" src="https://user-images.githubusercontent.com/42061003/53069446-03748a80-3517-11e9-8402-6b96592c167a.png">

**Comment by loganhz** [comment]
It will be fixed in https://github.com/rancher/rancher/issues/17174

**Comment by gitlawr** [comment]
logged the error in https://github.com/rancher/rancher/issues/18268

**Comment by rootwuj** [comment]
Version: master 2.2 (2/20/19) Image ID: cdd98a0abb92
The following cases have been verified:
1. Create a managed ACK cluster
2. Delete a managed ACK cluster
3. Create a workload
4. Create and verify that LB is available
5. create catalog app
6. Use the cluster kubectl terminal
