### ISSUE TITLE
Unable to correct ectd s3 backup password once it has been entered incorrectly

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17822]
Version: Master 2.2 (2/1/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a DO cluster and set up s3 etcd backup.
- Once it is fully provisioned, edit it but enter the wrong secret key.
- Notice you will (as expected) now get an error if you try to backup or restore etcd manually:
`Failed to download etcd snapshot from s3, exit code [1]: time="2019-02-01T23:10:42Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:davidtest2bucket, err:Access Denied."`
- Now, edit the cluster again so we can correct this, plug in the correct secret key and save the changes.

**Result:**
When you correct the secret key by editing and saving the issue will remain as if you made no changes. If you look at the http/UI it looks as though the UI passed everything correctly.

**Comment by moelsayed** [comment]
Tested using master 12/02. 

I created a DO cluster with s3 backup configuration. I was able to change the secret key several times with no issues.

**Comment by moelsayed** [comment]
The changed secret remains in the cluster status, and used for restore.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/21/19)
Follow the steps to reproduce (both mine and Mohamed's). The issue no longer occurs. Once you have edited the cluster to fix the secret and allow the cluster to reprovision, you can successfully backup/restore now.
