### ISSUE TITLE
Ability to use alidns provider in globaldns

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17838]
Add alidns(Alibaba Cloud DNS) as an option in globaldns.

**Comment by gitlawr** [comment]
Steps to validate:
1. Go to `https://dns.console.aliyun.com/#/dns/domainList` and check that the rootDomain about to use is available in alidns console, and the aliyun user has permision to manage the domain.
2. Go to globaldns-provider, Create a alidns provider, with your accesskey/secretkey.
3. Create a multiclusterapp that uses ingresses, the ingress need to has sub-domain of the rootDomain as the hostname, and contains the annotation `rancher.io/globalDNS.hostname: 'subdomain.rootdomain'`
4. Go to globaldns-entries, Create an entry that uses the above provider, and choose the mcapp as the target(Also try using projects targets as another use case).

**Result:**
An A-record is added in alidns console. you can access the app ingress via the configured domain.

**Comment by kingsd041** [comment]
Version: master 2.2 (2/15/19)  Image ID: 43fc066bb7db
Confirmed fix.  I tested the `Multi Cluster App` and `Projects` with Alibaba Cloud Provider and worked fine on my environment.
