### ISSUE TITLE
Multiclusterapp: Cannot go to lauch page when there is a project scope catalog

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17837]
**Rancher version**
master 2/3

**Steps to reproduce (least amount of steps as possible):**
1. Create a project scope catalog in the Default project.
```
Name: pcatalog
URL: https://git.rancher.io/charts
Branch: master
```
2. Go to global - multi-cluster apps page.
3. Click `Launch`

**Result:**
Stuck in waiting state, see an error in the browser console.
![image](https://user-images.githubusercontent.com/5697937/52172103-b61cbd00-27a3-11e9-95d1-61fc7cbd9e46.png)

**Comment by westlywright** [comment]
Had to roll back some changes on master this will be on hold until we can merge again.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/6/19)
Confirmed fix. Attempted to reproduce per steps and was unable. When I launched MC apps after adding the project-scope catalog the MC app launch page loaded immediately without any issues.
