### ISSUE TITLE
UI for alidns provider in globaldns

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17839]
Able to use alidns(Alibaba Cloud DNS) as a provider option in the UI.
Similar to route53, supported configurations include `rootDomain,accessKey,secretKey`

Related backend issue: https://github.com/rancher/rancher/issues/17838

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/13/19)
Tested the UI. Confirmed I can create, edit, delete an Ali DNS GDNS provider.
Inspected HTTP/API to ensure this looks correct.
Further testing will be done in the linked backend issue.

Initial creation (POST)
```
alidnsProviderConfig: {accessKey: "acessKey", secretKey: "SecretKey", rootDomain: "myroot.alidns.com"}
  accessKey: "accessKey"
  rootDomain: "myroot.alidns.com"
  secretKey: "SecretKey"
description: "description."
name: "alidnsprovidername"
provider: "alidns"
providerName: "alidns"
type: "globaldnsprovider"
```

Edit (PUT)
```
alidnsProviderConfig: {accessKey: "acessKey2", rootDomain: "myroot.alidns.com", type: "/v3/schemas/alidnsProviderConfig",…}
  accessKey: "acessKey2"
  rootDomain: "myroot.alidns.com"
  secretKey: "2secret"
  type: "/v3/schemas/alidnsProviderConfig"
annotations: {}
baseType: "globalDnsProvider"
created: "2019-02-13T18:07:51Z"
createdTS: 1550081271000
creatorId: "user-dgfz7"
id: "alidnsprovidername"
labels: {cattle.io/creator: "norman"}
  cattle.io/creator: "norman"
name: "alidnsprovidername"
provider: "alidns"
type: "globalDnsProvider"
uuid: "474c75b0-2fba-11e9-841e-0242ac110002"
```

And Delete function (HTTP DELETE)

Screenshot of the UI upon creation:
![image](https://user-images.githubusercontent.com/45179589/52733527-2edc0000-2f80-11e9-9307-f7a3c64b64a0.png)
