### ISSUE TITLE
Manually deployed helm charts not visible from the UI

### ISSUE THREAD

**Issue by dawidmalina** [rancher/rancher#17835]
I've got one kubernetes cluster where rancher is deployed via helm. During cluster creation I've been deployed several other charts but those charts are not visible from the rancher ui.

```
helm ls
NAME         	REVISION	UPDATED                 	STATUS  	CHART                	APP VERSION	NAMESPACE
cert-manager 	1       	Mon Jan 21 17:22:45 2019	DEPLOYED	cert-manager-v0.5.2  	v0.5.2     	cattle-system
efs          	1       	Thu Jan 24 20:36:11 2019	DEPLOYED	efs-provisioner-0.1.2	v0.1.2     	kube-system
grafana      	11      	Tue Jan 22 17:41:38 2019	DEPLOYED	grafana-1.25.2       	5.4.3      	cattle-monitoring
nginx-ingress	1       	Mon Jan 21 17:22:46 2019	DEPLOYED	nginx-ingress-0.31.0 	0.20.0     	ingress-nginx
prometheus   	1       	Tue Jan 22 14:32:18 2019	DEPLOYED	prometheus-8.4.5     	2.6.1      	cattle-monitoring
rancher      	2       	Sat Feb  2 22:08:47 2019	DEPLOYED	rancher-2019.1.2     	v2.1.6     	cattle-system
```
And opposite all charts deployed from rancher ui are not visible from the console.

Expected behaviour: I should be able to see charts created via different ways (console based or ui based). This would allows me to inject needed charts during cluster creation but reconfiguration/upgrade/etc can be done from the rancher ui.

Workload are properly displayed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.6
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
is it possible @StrongMonkey ?

**Comment by pluqueTheLuxe** [comment]
Hi guys, do we have additionnal information on this topic?

There is clearly something I don't understand in the Rancher's role. I thought Rancher was acting somepoint as a wrapper around k8s management ... Can you point me to some infos or article around it's role!

**Comment by dawidmalina** [comment]
@loganhz, @deniseschannon, @tfiduccia, @StrongMonkey any updates on this topic? Your feedback would be really valueable. Maybe there is different way or workarround for this issue.

**Comment by vincent99** [comment]
You are taking about two similar but different resources.  The UI supports "apps", which are a Rancher CRD to deploy helm charts in demand as the user making the request.  

Actual helm/tiller is not installed at all in clusterz by default because it has no mechanism for multi-tenant operation.  So if you install tiller and a chart with helm, it creates its own Cards that are not a Rancher App and do not show up in the UI.

In either case, the underlying resources it creates (deployments, volumes, etc) do show up, if the appropriate namespace(s) are part of your selected project.

**Comment by dawidmalina** [comment]
Ok. Thanks for the explanation. Closing ticket.

**Comment by pluqueTheLuxe** [comment]
> You are taking about two similar but different resources. The UI supports "apps", which are a Rancher CRD to deploy helm charts on-demand as the user making the request with only the permissions they have.
> 
> Actual helm/tiller is not installed at all in clusterz by default because it has no mechanism for multi-tenant operation. So if you install tiller and a chart with helm, it creates its own CRDs that are not a Rancher App and do not show up in the UI. It then deploys the underlying resources as the service account tiller was configured with, which usually has wide-ranging or full permission to the cluster.
> 
> In either case, the underlying resources it creates (deployments, volumes, etc) do show up, if the appropriate namespace(s) are part of your selected project.

I think it’s important to mention that you can also use the ˋrancher cli` so your apps will appear in the ui

**Comment by piyush94** [comment]
Is there a possibility to show charts installed using Helm3 in the UI as it's not dependent on Tiller?

**Comment by cospeedster** [comment]
Same here @piyush94 ..

Have you been able to fix this?

**Comment by vincent99** [comment]
The newer cluster explorer Ui in 2.5 shows and installs helm 3 charts (and vice versa).  They will continue to not show up in the older Ui apps (which shows our CRDs).

**Comment by cospeedster** [comment]
Thanks for your reply @vincent99 !

I‘ll check the new UI soon.
