### ISSUE TITLE
Support configure PV reclaim policy in UI

### ISSUE THREAD

**Issue by ryanrca** [rancher/rancher#17834]
**What kind of request is this (question/bug/enhancement/feature request):**
 bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a persistent volume at the cluster level.  In this case, I used an NFS Share.
1. Create a persistent volume claim at the project level.  Use the PV created in the previous step.
1. Once bound, delete the PVC.  
1. Go back to Persistent Volumes at the cluster level.  Note the state of the PV of "Released".

**Result:**
PV is stuck in state "Released". 
How to get the PV back to "Available" state?  24 hours later, its still in "Released" state and the PV is not useful.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Single install, Rancher V 2.1.5

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 2CPUs, 8G RAM
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
ryan@Rancher2:~$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by loganhz** [comment]
Now the PV's reclaim policy is `Retain` when you create the PV in Rancher UI.
Released is the expected state. You can find more info via https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain

I guess what you want is `Recycle` mode which is deprecated. https://kubernetes.io/docs/concepts/storage/persistent-volumes/#recycle

However, users cannot configure the reclaim policy in Rancher UI.

@vincent99 Does it make sense to expose reclaim policy option in UI? So users can change it to `Delete` or `Recycle`.
