### ISSUE TITLE
Anonymous auth is enabled for grafana in library chart

### ISSUE THREAD

**Issue by longwuyuan** [rancher/rancher#17843]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install grafana chart from library

**Result:**
Anonymous login is possible as in anyone can view any dashboard without login

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

# Grafana settings has anon auth enabled
````
auth.anonymous |  
-- | --
enabled | true
```

**Comment by loganhz** [comment]
There is an option when you deploy Grafana. It's enabled by default. You can disable it.
![image](https://user-images.githubusercontent.com/21168270/52191390-601d4780-287f-11e9-8167-6317290a2d69.png)

**Comment by longwuyuan** [comment]
![2019-02-04-111349_1687x593_scrot](https://user-images.githubusercontent.com/5085914/52192140-1cefb400-2840-11e9-9087-6f917392a541.png)

The choice is in the Grafana Chart but not in the Prometheus chart (which also installs grafana).

I can't see that checkbox for Anonymous Access True/Flase. I choose the "Prometheus" chart from Library. Must be missing in the questions.

**Comment by loganhz** [comment]
Thanks!
