### ISSUE TITLE
When creating services with network mode set to "host", containers should not be placed on hosts where the exposed ports already taken by other containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1784]
Server version - V0.32.0

Steps to reproduce the problem:

Setup has 3 hosts.

Scenario 1:
Create a service - S1 with image that exposes some port say 80 with network set to "host" with scale 1.

Create another service with the same image with network set to "host" with scale 3.
One of the instances that gets placed in the same host as the container from S1 , keeps restarting.

Scenario 2:
Create a service - S1 with image that exposes some port say 80 with network set to "host" with scale1.

We are able to access the container in S1 using hostIp address and port 80.

Create a LB service with source port as "80" with target as S2 . Lb Agent could get created on the same host where S1's container is launched.

Accessing hostIp address and port 80 now gets access to containers in S2.

Both the above scenarios should be prevented by allocators by choosing the host which have free exposed  ports.

**Comment by will-chan** [comment]
Won't fix this as we don't know what the app the container may be listening to when in host mode.
