### ISSUE TITLE
Please add new added AWS region for EKS cluster.

### ISSUE THREAD

**Issue by biswajit-crvsh** [rancher/rancher#17844]
**What kind of request is this (question/bug/enhancement/feature request):**

enhancement 
**Steps to reproduce (least amount of steps as possible):**

Login -----> Create cluster ------> Select EKS ------> in the region of Account access section, only 3 aws regions are listed but actually EKS is now available in many other regions too.

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher:latest)

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/17561
