### ISSUE TITLE
Monitoring won't work in an air gap environment

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17842]
Support monitoring in air gapped environment

**Comment by loganhz** [comment]
We will post the steps for air gapped install later.

**Comment by loganhz** [comment]
We need to make sure the setup has the access to system chart repo `https://git.rancher.io/system-charts`. 

Option 1: 
Setup the http proxy https://rancher.com/docs/rancher/v2.x/en/installation/single-node/proxy/

Options 2: 
Clone and host the repo in your air gap env. And point to it via api `/v3/catalogs/system-library`

In 1.6, there is a `DEFAULT_CATTLE_CATALOG_URL` env which you can use to config the catalog url. But we don’t support it in 2.0.  

Also, we need to setup rancher to use private registry for the images which monitoring is using
https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/config-rancher-for-private-reg/

Make sure you have the following images in your private registry

rancher/coreos-prometheus-operator:v0.26.0
rancher/coreos-prometheus-config-reloader:v0.26.0
rancher/coreos-configmap-reload:v0.0.1
rancher/node-exporter:v0.17.0
rancher/coreos-kube-state-metrics:v1.4.0
rancher/prom-alertmanager:v0.15.2
rancher/grafana:5.3.0
rancher/nginx:1.15.8-alpine
rancher/prometheus:v2.5.0

**Comment by jiaqiluo** [comment]
Comment from @thxCode at https://github.com/rancher/rancher/issues/18417#issuecomment-467738296

Monitoring in airgap should be set as the following:

- Setup an inner git server or helm server to sync `system-library`: https://github.com/rancher/system-charts
- Setup a private image registry to include necessary images.

##### 1. How to change `system-library` URL in internal
For now, we cannot change `system-library` URL as same as `library` in Catalogs page, but we can use schema API. Accessing `https://$ADDRESS/v3/catalog/system-library` to edit.
##### 2. Which images are necessary for Monitoring
For master:
```
rancher/coreos-prometheus-operator:v0.29.0
rancher/coreos-prometheus-config-reloader:v0.29.0
rancher/coreos-configmap-reload:v0.0.1
rancher/prom-node-exporter:v0.17.0
rancher/coreos-kube-state-metrics:v1.5.0
rancher/prom-alertmanager:v0.16.1
rancher/grafana-grafana:5.4.3
rancher/nginx:1.15.8-alpine
rancher/prom-prometheus:v2.7.1
```
For v2.2-rc2
```
rancher/coreos-prometheus-operator:v0.26.0 
rancher/coreos-prometheus-config-reloader:v0.26.0 
rancher/coreos-configmap-reload:v0.0.1 
rancher/node-exporter:v0.17.0 
rancher/coreos-kube-state-metrics:v1.4.0 
rancher/prom-alertmanager:v0.15.2 
rancher/grafana:5.3.0 
rancher/nginx:1.15.8-alpine 
rancher/prometheus:v2.5.0
```
Related https://github.com/rancher/rancher/issues/17842#issuecomment-466605325

**Comment by jiaqiluo** [comment]
The enhancement is validated on Rancher v2.2.0-rc1

Rancher installation option: Airgap HA
Node config: EC2 instance, t2.xlarge, Ubuntu 16.04.5 LTS, docker 17.3.2 

Steps:
- add a custom cluster (3 nodes, one role on each) 
- enable cluster level monitoring
- enable project level monitoring

Result:
Both cluster and project montioring work as expected.
