### ISSUE TITLE
Failed to validate cluster: Network plugin [none] is not supported

### ISSUE THREAD

**Issue by micw** [rancher/rancher#17852]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a cluster with network.plugin=none

**Result:**
Rancher errors with "Failed to validate cluster: Network plugin [none] is not supported"

**Other details that may be helpful:**
RKE supports "none" network plug-in, Rancher not error here.

**Environment information**
Rancher	v2.1.6
User Interface	v2.1.19
Helm	v2.10.0-rancher5
Machine	v0.15.0-rancher1-1

**Comment by micw** [comment]
Seems to work now (2.2.0-rc2).

**Comment by superseb** [comment]
This was added in RKE v0.2 and Rancher v2.2.0
