### ISSUE TITLE
How to change ingress port and access rancher web ui?

### ISSUE THREAD

**Issue by paulmorabito** [rancher/rancher#17857]
Using latest rancher (2.16) on Ubuntu 18.04 and following the HA setup.

I have two questions/issues:

1. How can I access the rancher web UI? After deploying in Helm successfully, I don't see any host/port information other than the internal IP and I can't access this. When you deploy via docker using single node setup, you can specify the listening port but I don't see this here and hitting the node's IP also doesn't work (as port 80/443 are used by other services). I've set the hostname to be the hostname I'll use once I set up via a reverse proxy but should it be set to something else?

2. How can I change the ingress default port? I've followed the instructions at issue 15225 but I get a site can't be reached error . When I check via "kubectl --namespace=ingress-nginx logs nginx-ingress-controller-4vkzx" I see the following error:

Error: exit status 1
2019/02/05 10:32:35 [emerg] 33#33: duplicate listen options for 0.0.0.0:18080 in /tmp/nginx-cfg464753742:470
nginx: [emerg] duplicate listen options for 0.0.0.0:18080 in /tmp/nginx-cfg464753742:470
nginx: configuration file /tmp/nginx-cfg464753742 test failed

I did this:

kubectl edit daemonset nginx-ingress-controller -n ingress-nginx

And added the two lines below the controller line.

- /nginx-ingress-controller
- --http-port=18080
- --https-port=18443

Then I ran:

kubectl delete pod -l app=ingress-nginx -n ingress-nginx

I was also at different stages toying with host and container ports in the same ingress config but they are definitely 80 and 443 now.

Any help would be very appreciated.

**Comment by superseb** [comment]
This is the configuration to have the default ingress controller listen on other ports than default (see https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/ingress-controllers/#configuring-nginx-ingress-controller):

```
ingress:
    provider: nginx
    extra_args:
      http-port: 8080
      https-port: 8443
```

If it's complaining about duplicate listen options, you are probably adding new arguments instead of replacing the ones that are already there.

Let me know if this doesn't work for you.

**Comment by paulmorabito** [comment]
It works. Thanks!
