### ISSUE TITLE
When Services get deployed with network mode host ,  ipaddress of the container is shown as "None".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1785]
Server version - V0.32.0

When Services get deployed with network mode host ,  ip address of the container is shown as "None".
We should be able to show the ip address of the container as the host ip address or we should be able to show the network mode of the container (from which we are able to deduce the ip address of the container)

**Comment by sangeethah** [comment]
This is still the case with latest build from master:

<img width="575" alt="screen shot 2016-03-08 at 8 27 40 am" src="https://cloud.githubusercontent.com/assets/4266958/13608017/bad7454a-e507-11e5-804b-38f0564dc747.png">

**Comment by will-chan** [comment]
@vincent99 is this something we can do in the UI or do you need this in the API to return the value?

**Comment by vincent99** [comment]
@will-chan `primaryIpAddress` should be the host IP in the API if that's what you want to display..
