### ISSUE TITLE
Validate k8s 1.13 for 1.6

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17851]
Need to add k8s 1.13 support for 1.6 release line. It should include support for Node Local DNS to address 

https://github.com/rancher/rancher/issues/15718#issuecomment-443979606

**Comment by alena1108** [comment]
@kinarashah is going to handle releasing k8s 1.13 binary and a first pass of rancher/kubernetes image

@superseb we should revise all the addons to see if it needs version bump up for k8s 1.13

**Comment by superseb** [comment]
For K8s 1.13, etcd2 backend was dropped. We will need to support etcd3 first before being able to support k8s 1.13 in 1.6:

```
Urgent Upgrade Notes
(No, really, you MUST do this before you upgrade)
Before upgrading to Kubernetes 1.13, you must keep the following in mind:

kube-apiserver
The deprecated etcd2 storage backend has been removed. Before upgrading a kube-apiserver using --storage-backend=etcd2, etcd v2 data must be migrated to the v3 storage backend, and kube-apiserver invocations changed to use --storage-backend=etcd3. Please consult the installation procedure used to set up etcd for specific migration instructions. Backups prior to upgrade are always a good practice, but since the etcd2 to etcd3 migration is not reversible, an etcd backup prior to migration is essential.
```

**Comment by deniseschannon** [comment]
Due to the deprecated support of etcd v2 in k8s 1.13 and with the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
