### ISSUE TITLE
Multiple cluster app UI: targets need to show the cluster name

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#17853]
In Rancher 2.2.0 Alpha4, after I select a multi cluster app target, the UI does not display the cluster name. So I only see the project name. It is confusing when multiple clusters have the same project name.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/19/19)
Confirmed feature component.
In the UI you are now presented with an improved drop-down menu and chart showing an array of cluster & project so you can more clearly see what you have picked.
![image](https://user-images.githubusercontent.com/45179589/53042407-6eed2800-3443-11e9-8e6b-8537a6c88014.png)

![image](https://user-images.githubusercontent.com/45179589/53042380-63016600-3443-11e9-8b6a-bc3846484635.png)

As you pick projects they are added to the chart and the drop down menu will show a checkbox for the last item you had picked. I entered this feature request so we show check boxes for all projects picked not just the last picked: #18230

![image](https://user-images.githubusercontent.com/45179589/53042462-904e1400-3443-11e9-8075-0093ad61758a.png)

![image](https://user-images.githubusercontent.com/45179589/53042525-afe53c80-3443-11e9-8a8a-f3683d87f50f.png)

Tested this area with numerous projects, confirmed we can add and remove as needed. Test column sorting, fuzz data, try to break things, etc. Confirm http/api still looks correct. Successfully provision a couple of mc apps and ensure upgrading is working in this area including upgrading by adding more target projects, removing, etc. Smoke/halo tested.
