### ISSUE TITLE
Pods can not resolve hostname from external DNS server

### ISSUE THREAD

**Issue by adalga** [rancher/rancher#17859]
I want to reach my services via their ingress adresses. I have dns server on my local network and ingresses are resolved from this server. The problem is pods work inconsistent. Sometimes they resolve the address from external dns server sometimes they don't. It also happens when I try other hostnames which are registered on that dns server.
They can resolve other services via their service names from kube-dns btw. 

Rancher version: 2.1.2
Host OS: Ubuntu 16.04 LTS
Kubernetes Version: v1.10.1-rancher2-1
Network Provider: Canal
docker version: 17.03.2-ce
kube-dns version: 1.14.8

**Comment by adalga** [comment]
Kube-dns logs indicate that skydns: failure to forward request "read udp *.*.*.*:33616->10.0.0.1:53: i/o timeout

However my dns server address is not 10.0.0.1

It tries to forward to wrong address. I restarted kube-dns and for now it seems work. However, I don't get what was the problem is and if I will face with it again.

**Comment by superseb** [comment]
It uses the upstream nameserver from the node where kube-dns is scheduled. You can retrieve some more information on the state of kube-dns running those two one-liners in the embedded kubectl shell or when using the generated kubeconfig for this cluster:

Check upstream nameserver in every kube-dns pod:
```
kubectl -n kube-system get pods -l k8s-app=kube-dns --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do echo "Pod ${pod} on host ${host}"; kubectl -n kube-system exec $pod -c kubedns cat /etc/resolv.conf; done
```

Check resolving from each kube-dns pod to upstream:
```
kubectl -n kube-system get pods -l k8s-app=kube-dns --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do echo "Pod ${pod} on host ${host}"; kubectl -n kube-system exec $pod -c kubedns -- /bin/sh -c 'for i in `seq 1 5`; do nslookup www.google.nl; done'; done
```

**Comment by adalga** [comment]
As I said after I restart it works.
I checked resolv.conf and it is configured correct and I can resolve the names now. If something changes again I will inform. For now I can close this. Thanks for your effort.
