### ISSUE TITLE
App status is incorrect during updates

### ISSUE THREAD

**Issue by tylerstapler-wf** [rancher/rancher#17863]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Run a cluster with a large number of nodes (48 in our case)
2. Deploy a daemonset via catalog app on host network with several containers which have a slow (20secs) startup
3. Update the image of one of the daemonset containers via the catalog app's answers
4. Check Catalog App status and the workload status

**Result:**
The Catalog app reports "Active" instead of "Deploying" or "Updating".
![screen shot 2019-02-05 at 11 28 57 am](https://user-images.githubusercontent.com/19389666/52295719-1fd2cd80-2942-11e9-8c33-fa26d9ff4b72.png)

The Workload oscillates between "Active" and "Updating"
![screen shot 2019-02-05 at 12 32 51 pm](https://user-images.githubusercontent.com/19389666/52295835-61fc0f00-2942-11e9-842d-8fc2c2834926.png)
![screen shot 2019-02-05 at 12 33 16 pm](https://user-images.githubusercontent.com/19389666/52295842-67f1f000-2942-11e9-8017-59ccddbf1b2c.png)

Our CI/CD system reads the Catalog App status to tell if a deploy succeeded. Since the Catalog Apps page reports "Active" before the update is actually complete our deployment pipeline continues before it should.

We would like the workload state and catalog state to reflect the underlying k8s state.

Specifically we would like the state to remain updating until desired == ready == up-to-date
```
┗➤$ kubectl get ds -n workiva-system
NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR AGE
k8s-harbour-network         47        47        47      4            47          <none>          80d
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):  AWS m5.4xlarge
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 18.06

**Comment by alena1108** [comment]
Should be fixed by the app state being set internally in the app condition

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/12

* Installed Rancher in HA
* Created cluster
* Deployed Artifactory catalog app into project

Expected:
* Catalog app stays in `deploying` until all pods are ready, and then transitions to `active`

Actual:
* App status switches repeatedly from `deploying` to `active` and back again until all pods are ready.

![screen shot 2019-02-12 at 2 44 01 pm](https://user-images.githubusercontent.com/21316915/52669959-ae13fa00-2ed4-11e9-911b-0545764c0973.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/19

When creating or updating a multicluster app, the state is now showing correctly. Installing/deploying when creating/upgrading, and active when operations are completed.

**Comment by harshalkwagh** [comment]
@tylerstapler-wf @alena1108 @bmdepesa 
I am new to rancher, I have created my first catalog using rancher chart in git repository.
I am able to launch application using that catalog, but in status section its not showing any entry.
Its empty
![image](https://user-images.githubusercontent.com/22464777/84643063-f43efa80-af1a-11ea-9992-6640e345da34.png)
I tried to find documentation for the same but dint get any, which will explain how can i add/update entries in status section.
Can you please help understand it.
Thanks in advance :-)
