### ISSUE TITLE
Rancher CLI release version does not match its actual version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17866]
Version: Rancher Master 2.2 (2/5/19) CLI: v2.0.5 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy rancher master branch or latest alpha
- Download CLI and notice points to v2.2.0-rc5 as of rancher/rancher v2.2.0-alpha6
- Run **rancher -v** and the cli returns v2.0.5 not v.2.2.0-rc5

**Result:**
Naming convention is potentially confusing to customers and QA. Does the cli release need to change or the version the binary returns?

**Comment by tfiduccia** [comment]
@davidnuzik - I checked both 2.2.2 and master and the cli is currently pointed at 2.2.0 version.  Which is correct.  
The version for cli is located at rancher/cli, not rancher/rancher.

**Comment by davidnuzik** [comment]
Checked v2.2.3-rc1 rancher - it brings me to v2.2.0 binary and binary now reports correct version.
```
rancher-v2.2.0$ ./rancher -v
rancher version v2.2.0
```
