### ISSUE TITLE
Add -d(daemon) option to create container interface

### ISSUE THREAD

**Issue by epelc** [rancher/rancher#1786]
The web interface doesn't seem to have an option for `-d` when creating a container. Perhaps it'd also be a good idea to allow adding custom flags for when things like this aren't added yet?

**Comment by vincent99** [comment]
`-d` is "detach" in `docker run`, to connect stdin/out/err to the console you're running the command in.  This has no meaning in the Remote API or Rancher, it's always "detached".

**Comment by deniseschannon** [comment]
@epelc Please reopen if you have more questions.

Anything that `docker run` supports should be available through our UI.

**Comment by epelc** [comment]
Thanks. I overlooked the flag like @vincent99 said. Sorry I forgot to close this.
