### ISSUE TITLE
Wildcard host matches in load balancer

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#1787]
Not sure if this is supported, apologies if I've missed it. I'd like to set up a wildcard host match in a Rancher load balancer.

Since (I think) the load balancer uses HAProxy, I wonder if it might be worth adding a type setting to domain and path matches? Or perhaps it'd be enough just to add it for hosts? "Exact" and "Ends with" are the only use cases I can think of, and those only for hosts.

Thanks.

**Comment by alena1108** [comment]
@ndarilek today rancher uses "equals" for host rules and "starts with" for the path. Its a good idea to enhance it with custom qualifiers. 

@deniseschannon - marking this ticket as an enhancement request. The fix is not trivial as it would require rancher-compose syntax change for port labels.

**Comment by Skeen** [comment]
+1; This enhancement would be nice.

We're running multiple domains on a single server / IP.
The natural approach was a load balancer to divide requests on a domain basis; such that requests for `example.com` hit the DomainBalancer which forwards it to a specific load balancer for that domain, and requests for `magic.com` is forwarded to another domain-specific load balancer.

We tried to use;
* `example.com` --> ExampleLoadBalancer
* `*.example.com` --> ExampleLoadBalancer
* `magic.com` --> MagicLoadBalancer
* `*.magic.com` --> MagicLoadBalancer

But as the wildcard isn't supported, only the `magic.com` requests will go to the balancer; `wiki.magic.com` will be lost on the DomainBalancer.

While regex support would be a nice enhancement; I believe that simple capture-all wildcards are a must.

**Comment by Ilya-Kuchaev** [comment]
+1

**Comment by kaos** [comment]
+1

**Comment by edit** [comment]
+1

**Comment by lukerandall** [comment]
+1

**Comment by ebr** [comment]
+1

**Comment by demarant** [comment]
+1

**Comment by haswalt** [comment]
Huge +1 on this

**Comment by zaubererty** [comment]
+1 
For the implementation of let's encrypt it would be nice to have a total wildcard. Just a asterisk for the hostname would be funtastic

**Comment by alena1108** [comment]
@sangeethah here are the rules for the wildcards:
```
*.domain.com ->  hdr_end(host) -i .domain.com
domain.com.* ->  hdr_beg(host) -i  domain.com.
domain.com   ->  hdr(host)     -i  domain.com
```

**Comment by sangeethah** [comment]
Tested with server version - V0.50.0-rc3
LB service is degraded when targets are added with Request Host - https://github.com/rancher/rancher/issues/3023

**Comment by sangeethah** [comment]
Tested with server version - V0.50.0-rc4

We are able to specify ""Request Host" for targets in the following format:

*.domain.com ->  hdr_end(host) -i .domain.com
domain.com.* ->  hdr_beg(host) -i  domain.com.
domain.com   ->  hdr(host)     -i  domain.com

Traffic gets routed to the correct set of targets.

This should be available in the next rancher release.

**Comment by zaubererty** [comment]
What has the higher priority?

*.domain.com           /api      <container>
app.domain.com                  <container>

If you request 'app.domain.com/api' which container is addressed? I'll assume the first one.

**Comment by sangeethah** [comment]
@zaubererty: yes, In your case  , request 'app.domain.com/api' will be redirected to targets configured for  "*.domain.com /api " . The order of priority should be as defined in #1654.

**Comment by hendryluk** [comment]
Just checking if wildcard in the middle is not supported. Didn't work for me.

**Comment by vincent99** [comment]
No, thery are mapped to "begins with" and "ends with".  In the middle requires regex, and probably a manually controlled ordering of the rules to control priority.

**Comment by hendryluk** [comment]
Any particular reason it wouldn't use `hdr_reg`?

**Comment by vincent99** [comment]
It would, but there is no sensible way to decide what order multiple begin, contains, and end rules should go in and no mechanism for you to specify it today.

What exactly is the use case here?

**Comment by hendryluk** [comment]
But hdr_reg would only require one single rule, i.e. replacing the need for individual begin/contain/end rules.
My case involves multiple layers of load balancing, so that the layer in the middle ends up with a `*.foo.*` rule. There's a workaround, but was just curious why this is not supported.

**Comment by vincent99** [comment]
Again, the specific way the rule is implemented is irrelevant, there still needs to be an explicit way to order them and we don't have that today because they are an unordered map of labels.

**Comment by Dids** [comment]
Does Rancher not support catch-all wildcards? I need one container to be a "fallback" container, so if no other rules match, go to this one. This needs to catch any custom domains pointing to it, and is crucial to my use case. Worked fine with setting the virtual host and weight with the official Docker Cloud image, but I've since migrated to Rancher.

**Comment by Ilya-Kuchaev** [comment]
Does Rancher support *.sub.domain.com notations?

**Comment by entwu** [comment]
+1

**Comment by kaos** [comment]
@Ilya-Kuchaev just a few comments up, the response to https://github.com/rancher/rancher/issues/1787#issuecomment-164651124 indicates that it is.. ;)
