### ISSUE TITLE
Configurable TTL for Route53 Global DNS provider

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17871]
We should add TTL as a configurable param to a Route53 provider. See if there are more params that can be added as well.

**Comment by prachidamle** [comment]
The kubernetes-incubator/external-dns supports configuring TTL for a DNS record using an annotation:
https://github.com/kubernetes-incubator/external-dns/blob/master/docs/ttl.md

As a fix, added TTL parameter to GlobalDNS entry (types PR: [rancher/types#717](https://github.com/rancher/types/pull/717)) and it will get applied as an annotation to the mgmt plane ingress that the external-dns provider syncs up with.

**Comment by sangeethah** [comment]
Tested with latest build from master - Feb 13

Able to set "ttl" when creating Global DNS entry and we see the ttl getting programmed in route53 entry as expected.
Able to edit existing Global DNS entry and set a different "ttl". The changed ttl gets programmed in route53 entry.

Default value of "300 seconds" is set for ttl when no value is set.

**Comment by sangeethah** [comment]
UI ticket - https://github.com/rancher/rancher/issues/18101
