### ISSUE TITLE
host proxy settings no longer honored by kubectld

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#17874]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. My guess is that since we no longer build kubectld using `-tags netgo` we dont inherit the hosts (or dockers) proxy settings.

https://github.com/rancher/kubectld/blob/d4b5a1ec1aba0318eb499673a897e449de9a46de/scripts/build#L10

**Result:**
kubectld never starts properly resulting in an environment that appears degraded.

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.27-rc1`

**Comment by superseb** [comment]
Steps to reproduce:

- Create hosts with no direct internet access, and configure proxy in OS and Docker so it can work through a proxy
- Create Kubernetes environment template, configuring the proxy in the environment template
- Add hosts using the command provided in the environment -> Add Host view
- See kubectld service not getting active, container doesn't stay running

Steps to validate:
- Same as above, but kubectld container stays running

**Comment by soumyalj** [comment]
Tested with rancher server v1.6.26 using k8s1.12.7-rancher1-1

Created a proxy server using tinyproxy.
Created hosts with no direct internet access, and configured proxy in OS and Docker so it can work through  proxy
Added a custom host to the k8s environment. 

kubectld service did not start up and it was stuck in "Activating" state

**Comment by soumyalj** [comment]
Tested with rancher server v1.6.26 using k8s1.12.7-rancher1-1

1. Create a proxy server using tinyproxy.
2. Create hosts with no direct internet access, and configured proxy in OS and Docker so it can work through proxy
3. Create Kubernetes environment template, configuring the proxy in the environment template
Provide http://PRIVATE IP OF THE PROXY SERVER HOST:8888 in the field http proxy to be used by kubernetes services
4. Create a k8s environment and add a custom host to this k8s environment.

Kubernetes setup was active and kubectld service was in running state
