### ISSUE TITLE
Support for Global DNS provider launch in agirgapped setups

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17883]
We need to support running global dns in airgapped setup. @prachidamle you can check how alert/logging components handle that, and do something similar

**Comment by alena1108** [comment]
As a part of this feature component, lets also make sure the upgrade to the new Global DNS image is supported once new rancher gets released.

**Comment by vincent99** [comment]
What does this even mean until you have support for a provider that isn't out on the internet?

**Comment by alena1108** [comment]
@vincent99 filed the issue just to keep track, so we don't forget to add support in once the private providers are supported.

**Comment by prachidamle** [comment]
What do we mean by "private providers"? Also how does this work since for dns programming with external-dns servers we need internet access.

**Comment by vincent99** [comment]
e.g. [rfc2136](https://github.com/kubernetes-incubator/external-dns/blob/master/provider/rfc2136.go) is something that would talk to a DNS server inside your network instead of out in the cloud.

"Airgap" support for the public providers is conceivable too... what we usually mean by airgap is "need to be able to download images from a custom registry", not that it necessarily actually has no outbound internet access.

**Comment by prachidamle** [comment]
thanks @vincent99 for the explanation. We can then resolve this ticket with the system-charts supporting images pulled from a registry

**Comment by jiaqiluo** [comment]
This feature is tested on Rancher:v2.2.0-rc3 in the air-gap HA mode.
Steps:
- at the global level, go to `Tools` -> `Global DNS Providers` to add a new `Route53` provider
- go to the local cluster, launch kubectl 
- run `kubectl get pods -n cattle-global-data` to check the pod 
```
> kubectl get pods -n cattle-global-data
NAME                                                              READY     STATUS    RESTARTS   AGE
systemapp-test-dns-provider-rancher-external-dns-74fb64bb5gjc6k   1/1       Running   0          21s
```
- run `kubectl logs systemapp-test-dns-provider-rancher-external-dns-74fb64bb5gjc6k -n cattle-global-data` to check the log
```
> kubectl logs systemapp-test-dns-provider-rancher-external-dns-74fb64bb5gjc6k -n cattle-global-data
time="2019-03-09T02:33:12Z" level=info msg="config: {Master: KubeConfig: RequestTimeout:30s IstioIngressGateway:istio-system/istio-ingressgateway Sources:[service ingress] Namespace: AnnotationFilter: FQDNTemplate: CombineFQDNAndAnnotation:false Compatibility: PublishInternal:false PublishHostIP:false ConnectorSourceServer:localhost:8080 Provider:aws GoogleProject: DomainFilter:[test-domain.com] ZoneIDFilter:[] AlibabaCloudConfigFile:/etc/kubernetes/alibaba-cloud.json AlibabaCloudZoneType: AWSZoneType:public AWSZoneTagFilter:[] AWSAssumeRole: AWSBatchChangeSize:1000 AWSBatchChangeInterval:1s AWSEvaluateTargetHealth:true AWSAPIRetries:3 AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup: CloudflareProxied:false CloudflareZonesPerPage:50 InfobloxGridHost: InfobloxWapiPort:443 InfobloxWapiUsername:admin InfobloxWapiPassword: InfobloxWapiVersion:2.3.1 InfobloxSSLVerify:true DynCustomerName: DynUsername: DynPassword: DynMinTTLSeconds:0 OCIConfigFile:/etc/kubernetes/oci.yaml InMemoryZones:[] PDNSServer:http://localhost:8081 PDNSAPIKey: PDNSTLSEnabled:false TLSCA: TLSClientCert: TLSClientCertKey: Policy:sync Registry:txt TXTOwnerID:431333e4-6232-4183-b84e-c7f76c420cd8_test-dns-provider TXTPrefix: Interval:1m0s Once:false DryRun:false LogFormat:text MetricsAddress::7979 LogLevel:debug TXTCacheInterval:0s ExoscaleEndpoint:https://api.exoscale.ch/dns ExoscaleAPIKey: ExoscaleAPISecret: CRDSourceAPIVersion:externaldns.k8s.io/v1alpha1 CRDSourceKind:DNSEndpoint ServiceTypeFilter:[] RFC2136Host: RFC2136Port:0 RFC2136Zone: RFC2136Insecure:false RFC2136TSIGKeyName: RFC2136TSIGSecret: RFC2136TSIGSecretAlg: RFC2136TAXFR:false}"
time="2019-03-09T02:33:12Z" level=info msg="Created Kubernetes client https://10.43.0.1:443"
time="2019-03-09T02:35:13Z" level=error msg="RequestError: send request failed\ncaused by: Get https://route53.amazonaws.com/2013-04-01/hostedzone: dial tcp 52.94.235.198:443: i/o timeout"
>```

**Comment by sangeethah** [comment]
Will retest this scenarion when we add support for private dns provider(s).
