### ISSUE TITLE
Update the rancher/machine repo to support the latest Azure features

### ISSUE THREAD

**Issue by stevenimle-honeywell** [rancher/rancher#17881]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
The current version of Docker Machine is not using a recent version of the Azure go SDK. Though this is not necessarily a problem, it does not allow for provisioning of the latest (and now recommended) storage solutions for VMs.

**Result:**
VMs are provisioned using Blob storage for their OS disks which kubernetes does not support resizing.

**Other details that may be helpful:**
I was hoping to have a discussion on this. The work for it is already done and I can raise a PR for it.

There are two parts to this need:
- Update to latest Azure SDK
- Add options for managed Disks as OS Disk

**Environment information**
- Rancher repo: `rancher/machine`

**Comment by fabionitto** [comment]
We use Rancher v2.2.2 with Azure and this is very very expected. Also, azure-sdk-for-go is already on v29.0.0 so I think it should be updated ASAP.
