### ISSUE TITLE
Importing an existing EKS cluster to rancher does not work

### ISSUE THREAD

**Issue by biswajit-crvsh** [rancher/rancher#17880]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

 Create cluster ----> Import

**Comment by superseb** [comment]
Please enter the information requested from the template, especially what Rancher version and what EKS version you are using.

Also we have a troubleshooting section which can help https://rancher.com/docs/rancher/v2.x/en/troubleshooting/imported-clusters/
