### ISSUE TITLE
Endless redirect loop with L7 loadbalancer

### ISSUE THREAD

**Issue by dawidmalina** [rancher/rancher#17887]
**What kind of request is this (question/bug/enhancement/feature request):**
Going through docs (https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/layer-7-lb/) describing how to setup L7 loadbalancer (with tls termination) with rancher and nginx ingress I've found issues with redirect endless loop. The problem was related with default nginx ingress which ignores forwarded headers and force ssl redirect. To make it properly work (with alb in my case) we need to instrument ingress with additional configuration:
- `ssl-redirect: "false"`
- `use-forwarded-headers: "true"`

If someone is using helm chart the addition parameters will looks like this:
```
--set-string controller.config.ssl-redirect=false --set-string controller.config.use-forwarded-headers="true"
```

It would be nice to mention this under this doc page just to save some time someone who will try to set this up like me :)

**Comment by superseb** [comment]
That page is no longer supported as stated on top, and using the Helm install it should already specify `ssl-redirect` when specifying external termination (https://github.com/rancher/rancher/blob/master/chart/templates/ingress.yaml#L12)

If you can share what steps you followed using the supported installation method and what didn't work, I can correct it.

**Comment by dawidmalina** [comment]
Well I did it my way (a bit). So my scenario looks like this:
- Setup EKS cluster with 3 nodes (auto-scaling group) with terraform
- Setup ALB L7 with TLS termination with terraform
  - ALB listen on port 443 and 80 (this preform redirect from 80 to port 443)
  - Target group point to ASG group on port 80
  - DNS point to ALB public endpoint
- Setup nginx ingress as helm chart with terraform
  - Nginx ingress is deployed as daemonset with network host (I need fixed/approved network flows)
- Setup rancher as helm chart with terraform
  - Rancher is configured with proper public ALB endpoint (DNS name)
  - TLS is configured as external

I see that ingress add `ssl-redirect` so looks like we are missing `use-forwarded-headers`. I will try to recreate this cluster and will let you know.

**Comment by dawidmalina** [comment]
Adding only `nginx.ingress.kubernetes.io/use-forwarded-headers: "true"` to rancher ingress does not work. I've check on this: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md and looks like`nginx.ingress.kubernetes.io/use-forwarded-headers` annotation does not exist (is not supported).

**Comment by ThunderRush** [comment]
We have the exact same issue with out BIG-IP F5 Setup. We reach the backend-servers but end up in a redirect loops.

We were using helm install rancher-stable/rancher --name rancher  --namespace cattle-system --set hostname=rancher-test.xxx.xx --set tls=external --version v2.1.6

**Comment by ThunderRush** [comment]
To follow up on my issue; I figured out what the problem was.
I did not set the X-Forwarded-Proto header on our F5 Loadbalancer. However, this was also not directly mentioned in the External TLS Termination section for HA Clusters, and only in the Single-Node install one.

Could you maybe add this to make it more clear?

**Comment by ferhatguneri** [comment]
This problem is not fixed. Need to reopen it.
