### ISSUE TITLE
Unable to set http_proxy config on Rancher notifier

### ISSUE THREAD

**Issue by garyellis** [rancher/rancher#17885]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a slack notifier from Rancher server. (The notifier type is arbitrary)
2. Edit any alert  and set the alert to the notifier created in the previous step; wait for cattle-alertmanager resources to deploy in the current cluster context.
3. Edit the alertmanager secret and add the proxy URL under: `global.http_config.proxy_url`; alerts will work temporarily, but this is not a permanent nor a working solution. 

**Result:** 
alertmanager secret is reverted and alert send fails.

**Other details that may be helpful:**

Alertmanager configures http proxy in config exclusively. `http_proxy`, `https_proxy`, etc environment is not supported in the current version of alertmanager by design. 

See:
https://github.com/prometheus/alertmanager/issues/853
https://github.com/prometheus/alertmanager/pull/1222
https://github.com/prometheus/alertmanager/issues/1300

Alertmanager does not support multiple configuration files. A custom configuration file mounted is not an option.
See:
https://github.com/prometheus/alertmanager/issues/1150

To support http proxies, we need to allow users to configure `http_config.proxy_url per alert and/or at the global level or do something more generic like parameterize an empty http_config map for each alert.
See
https://prometheus.io/docs/alerting/configuration/

**Environment information**
- Rancher version: 2.1.6
- Single and HA installation

**Comment by panho66** [comment]
slack_configs:
     - channel: application
       send_resolved: true
       text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
       http_config:
         tls_config:
            insecure_skip_verify: YES
         proxy_url: http://proxy:8080


Please add insecure_skip_verify in tls_config as well. For some unknown reason, one of the environment I have need to skip tls in order to work around problem.

**Comment by alena1108** [comment]
@aiwantaozi When we fix this issue, we have to make sure it is respected by all the notifiers, including the webhook

**Comment by panho66** [comment]
Need a flexible option please, Ie proxy setting for selected notifiers.

**Comment by aiwantaozi** [comment]
@alena1108 Hi Alena, backend pr will be ready today, then we going to integrate with UI. http_proxy could be added to slack, pageduty, webhook, wechat, except email, alertmanager doesn't allow to set smtp proxy.

**Comment by bmdepesa** [comment]
Was able to reproduce and see the workaround working. 

rancher/rancher:v2.2.5-rc1
* Create custom cluster with no access to internet
  * apt-get and docker configured to use proxy
  * only allow outbound traffic through proxy and to rancher-server in node security group
* Without modifying any settings, create a notifier and alerts
* Alerts are not sent.
* Edit alertmanager secret in `System` project to use http_proxy in notifier config
* Alerts are successfully sent

**Comment by jiaqiluo** [comment]
The bug fix is validated on rancher/rancher:master-head 259cfa71

- Deployed Rancher behind a proxy
- Created custom cluster behind a proxy
- Tested notifier without proxy URL  --> Test failed
- Tested notifier with proxy URL --> Test passed
- Created alerts and saw them sent successfully through the proxy

Proxy setup is seen on all notifiers except for e-mail.

**Comment by dolphyvn** [comment]
sorry to dig this up, but is it available on v2.2.3?

**Comment by panho66** [comment]
I think it is in 2.2.5 but 2.2.5 has air gap installation issue.

**Comment by Hkavya1215** [comment]
After adding the below entry in secret alertmanager.yml. The entry is getting overwritten 
It will go back to automated structure created by rancher monitoring 

slack_configs:
 - channel: application
   send_resolved: true
   text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
   http_config:
     tls_config:
        insecure_skip_verify: YES
     proxy_url: http://proxy:8080

**Comment by jiaqiluo** [comment]
@Hkavya1215 Can you provide more information about your setup?  What is the rancher version you are using? 

Is the alert manager/ monitoring redeployed/upgrade?  The secret will be overwritten in those two cases as I know.

**Comment by Hkavya1215** [comment]
@jiaqiluo i am using Rancher version: 2.4.5 

I have enabled monitoring in Rancher and also i have created notifier, which in tern created the alertmanager secrets and many more other configurations. I am trying to edit the alertmanager secret which is auto created.  

After I edit and close the alertmanager.yml and notification.tmpl, if there is any change in alerts the configuration files in alertmanager secrets are getting overwritten. 

![image](https://user-images.githubusercontent.com/9451731/99474747-2db8dd80-2973-11eb-80e3-5e92e44960f5.png)

**Comment by Hkavya1215** [comment]
I have not redeployed or upgraded
