### ISSUE TITLE
Propagate app state to multi cluster app target

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#17899]
Today we generate multi cluster app by aggregating the underlying apps' states. But there is no way to check on an individual app state w/o actually listing the app. We should propagate the apps' states to the multi cluster app targets to provide this visibility.

**Comment by alena1108** [comment]
api is available for testing, so marking the ticket accordingly

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/27
HA install

* Created cluster
* Created multiple projects
* Created multicluster app with 4 targets
  * Multicluster app dashboard shows individual status for each project app
* Upgraded the multicluster app
  * Statuses for each project updated accordingly
* Created standard user with project member access to 2 of the 4 targets
* Added the standard user as a member of the multicluster app
  * User can see statuses for all targets, but can only access targets he has access to.
* Upgraded the multicluster app
  * User can see statuses for each project updated
