### ISSUE TITLE
Feature Request: Add pod restarts to workload overview

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#17891]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
Add pod restart count to workload overview page.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/56803163-876b2b80-6854-11e9-80c7-2073cf4b5aa1.png)

We already have it in pods section of workload detail page. Is that what you want? @patrick0057

**Comment by patrick0057** [comment]
![restarts_modified](https://user-images.githubusercontent.com/44879867/56821679-43eccf00-680c-11e9-977f-2ead25c52934.jpg)
Would it be possible to have an overview of pod restarts from this page?

**Comment by loganhz** [comment]
Added in workload list page and workload detail page

![image](https://user-images.githubusercontent.com/21168270/56859225-60c70500-69ba-11e9-9096-ea99ea452b93.png)
![image](https://user-images.githubusercontent.com/21168270/56859229-67ee1300-69ba-11e9-8642-a2f257a49680.png)

**Comment by davidnuzik** [comment]
Version: Master (4/30/19)

I can confirm the addition of "Pod Restarts" to the workloads detail page and to the workload deployment details page (where pods are listed) as Logan outlined here in the above comment.
https://github.com/rancher/rancher/issues/17891#issuecomment-487345704

@loganhz would you mind making one small change? I think it would be nice to have a colon before the number sort of like what was done for Config Scale / Ready Scale

![image](https://user-images.githubusercontent.com/45179589/56994751-dcf55000-6b54-11e9-96d5-6e434ba0c930.png)

I think it looks nicer and be a bit better formatting to have a colon in all areas:
![Screen Shot 2019-04-30 at 2 34 34 PM](https://user-images.githubusercontent.com/45179589/56994850-1b8b0a80-6b55-11e9-81a9-cf3ff3bb6ba3.png)
![Screen Shot 2019-04-30 at 2 33 52 PM](https://user-images.githubusercontent.com/45179589/56994854-1e85fb00-6b55-11e9-97a6-467e670feee5.png)

**Comment by loganhz** [comment]
Thanks @davidnuzik I don't understand what you want for  `1 Pod / Created 4 minutes ago / Pod Restarts 0`

What's the expected layout?

**Comment by davidnuzik** [comment]
This is what I was thinking @loganhz https://github.com/rancher/ui/pull/2951

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/6/19)

I have validated the addition of "Restarts" and "Pod Restarts" in the UI.
If you are the /workloads page you will see the addition of "Pod Restarts" to the subtext under the Image name. I ensured this works correctly in all areas below.

![image](https://user-images.githubusercontent.com/45179589/57246446-1f55db80-6ff2-11e9-9d53-4a4e70c1f972.png)

This has also been added to the Workload Details page (/workload/deployment:(image))
As you can see this is in two places. Again in the subtext for Image in the Image column and at the bottom-right cell for the workload info.
![image](https://user-images.githubusercontent.com/45179589/57246508-4ad8c600-6ff2-11e9-9a0a-fa302c95d02a.png)

This has also been added to the Pod Details page (/workloads/(pod))
As you can see this is in two places as well. Again at the bottom-right cell for the pod info and also under the Restarts Column.
![image](https://user-images.githubusercontent.com/45179589/57246582-6e9c0c00-6ff2-11e9-9996-c48829779d4f.png)

Last, if you go to the Container Details page (/workloads/(pod)/container/(container))
You can see this in the container info at the bottom-center cell.
![image](https://user-images.githubusercontent.com/45179589/57246632-896e8080-6ff2-11e9-8311-0a8af984d44b.png)
