### ISSUE TITLE
Global DNS Provider SVG icons are disproportional in size

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17897]
Version: Master 2.2 (2/6/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add global DNS provider

**Result:**
Notice the Route53 and Cloudflare logos are very different in size. It's almost hard to read the cloudflare logo and the r53 logo is almost too large.
![image](https://user-images.githubusercontent.com/45179589/52377984-a7dcd400-2a23-11e9-98b8-3416465704ac.png)

**Comment by vincent99** [comment]
They're whatever size fits in the rectangle, but we can use a more rectangular cloudflare icon... https://www.cloudflare.com/logo/

**Comment by davidnuzik** [comment]
Version: master-head (7/26/19)

The logos are now all comparable in size:

![image](https://user-images.githubusercontent.com/45179589/61969763-23115280-af90-11e9-80a1-4e359bbc51fd.png)
