### ISSUE TITLE
Cattle shows net-util.sh error when not -ti is missing

### ISSUE THREAD

**Issue by feliksik** [rancher/rancher#179]
If I start a ubuntu:14.04.1 docker image with command /bin/bash but choose "console:no", I get the following error: 

: 52ea013e-fad7-4929-abd9-2b65ecf926e1 : Command '['/var/lib/cattle/pyagent/cattle/plugins/docker/net-util.sh', '-p', '2418', '-i', '10.42.156.244/16', '-d', 'eth0']' returned non-zero exit status 43

Maybe I should use a terminal-interactive setting, but cattle should nicely point that out, I think...

**Comment by ibuildthecloud** [comment]
The problem here is that net-util masks the errors from Docker.  If the container fails to start instead of showing the correct error from docker the net-util fails and we show that error.

@cjellick Can you reference the issue that you are using to track this?

**Comment by cjellick** [comment]
I have an umbrella issue for the entire native docker experience feature.
Here's is the comment where I reference all the net-util related bugs explicitly:
https://github.com/rancherio/rancher/issues/47#issuecomment-75267544

**Comment by deniseschannon** [comment]
@cjellick Not sure if this is fixed as #47 is closed.

**Comment by deniseschannon** [comment]
Tried to reproduce with v0.61.0-rc3, but I don't see any errors.
