### ISSUE TITLE
Docker version not updated on the nodes when docker version gets upgraded on the nodes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17902]
Rancher server version - v2.1.6

Steps to reproduce the problem:
Started with K8s cluster where the nodes had docker version - 17.03
Upgraded docker version to 18.09 on the etcd nodes.
Even after docker version got upgraded successfully , docker version on the  nodes continue to be shown as "17.03" in the nodes detail page.

The same behavior is also seen when  docker version gets upgraded on the control nodes.

Expected Behavior:
Correct docker version needs to be reflected on the nodes in rancher side.

Note - When I do some changes on the node (like adding a label from rancher UI) , this triggers node sync and the right docker version gets synced.

**Comment by sowmyav27** [comment]
Verified on Rancher:master.
Docker version: 18.9.1 is displayed on the UI under the nodes detail page.

<img width="1326" alt="workernode" src="https://user-images.githubusercontent.com/26032343/52598749-9886cd80-2e0b-11e9-9348-5e12fffd5419.png">

<img width="1284" alt="controlnode" src="https://user-images.githubusercontent.com/26032343/52598756-9c1a5480-2e0b-11e9-92d4-5ebd7880dd01.png">

<img width="1363" alt="etcdnode" src="https://user-images.githubusercontent.com/26032343/52598763-9de41800-2e0b-11e9-9a16-dec7342074a9.png">
