### ISSUE TITLE
Can't mount empty secrets

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#17907]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"description":"test", "name":"test", "value":""}' \
'http://"${CATTLE_URL}":8080/v2-beta/projects/1a5/secrets/'

**Result:**
Activating (Container should have been running but is in error state. Check logs for more information.: Failed to attach volume ########. Driver: rancher-secrets. Status code: 500. Status: 500 internal server error. Error Message: Unsuccessful request: 500 Internal Server Error)
NOTE: Any container that is using that secret will get stuck in a starting state.

**Other details that may be helpful:**
The UI will return a "Internal Server Error" if you try to create an empty secret. Also, you can do delete the secret from the UI as it will get stuck in a removing state. So you will have to go into the database and remove the entry.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v1.6.26
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
AWS EC2 using Cattle
rancher-server: c5.4xlarge; rancher-agent: m4.2xlarge
N/A
```

- Docker version (use `docker version`):

```
Client: 
Version: 18.06.1-ce 
API version: 1.38 
Go version: go1.10.6 
Git commit: e68fc7a 
Built: Tue Aug 21 17:16:31 2018 
OS/Arch: linux/amd64 
Experimental: false
```

**Comment by alena1108** [comment]
@mattmattox can you attach rancher-server logs?

**Comment by leodotcloud** [comment]
Note for QA team: Please create empty secrets prior to upgrading to the fixed version. These are not removable without the fix, should be deletable after the fix.

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc1`

**Comment by soumyalj** [comment]
Reproduced the issue with Rancher v1.6.26.
Create secret with empty value. Delete the secret. The secret is stuck in removing state.
```
2019-09-25 23:55:52,695 ERROR [05f98998-fecc-45c5-8f9f-665cf249d27f:578] [secret:3] [secret.remove->(SecretRemove)]
 [] [ecutorService-3] [i.c.p.process.secret.SecretRemove   ] Failed to delete secret from storage [3] java.io.IOExc
eption: Failed to delete secret :Bad Request
```
![Screen Shot 2019-09-25 at 5 02 37 PM](https://user-images.githubusercontent.com/18536626/65648238-4e2b1900-dfb6-11e9-8678-8850c53c09ee.png)

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc3`

**Comment by soumyalj** [comment]
Tested with rancher v1.6.29-rc3. 
Create empty secret in UI. It fails with the correct validation error as  below :
```
{"id":"019f07a0sdfdsfdsfdsfsdfdsfsdfdsfs","type":"error","links":{},"status":422,"code":"EmptySecret","message":"Secret cannot be empty","detail":null,"fieldName":"value","baseType":"error","actionLinks":{}}
```

<img width="988" alt="Screen Shot 2019-10-02 at 4 09 43 PM" src="https://user-images.githubusercontent.com/18536626/66088181-17617f80-e52f-11e9-86b0-f24cf97ca005.png">
