### ISSUE TITLE
When there are 2 global DNS entries created with same fqdn , only ip addresses relating to 1 of the entries get programmed in route53.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17901]
Rancher server version - Build from master -Feb 2

Steps to reproduce the problem:

1. Create Global DNS provider with root domain - "test.com" for route53 provider with invalid cerdentials.
2. Create Multicluster App - mcapp1 for cluster1 and cluster2 with Global DNS enabled Ingress for fqdn - "test1.test.com"
3. Create globalDnsEntry for `mcapp1` with fqdn - `test1.test.com`.

This results in ingress entry being created in cattle-global-data as expected.

fqdn  gets programmed in AWS with node ips from cluster1 and cluster2.

4. Create Multicluster another App - mcapp2 for cluster1 and cluster2 with Global DNS enabled Ingress for fqdn - "test1.test.com"
5. Create another globalDnsEntry for `mcapp2` with fqdn - `test1.test.com`.

This results in another ingress entry being created in cattle-global-data as expected.

But fqdn  entry in AWS continues to be programmed with node ips from cluster1 and cluster2.

This is a very misleading behavior.

In this case , we should prevent creating 2 global DNS entries created with same fqdn , since the ips from these 2 entries step on each other and the ingress url gets served incorrectly.

**Comment by prachidamle** [comment]
Had a discussion with @alena1108 regarding FQDN unique check, and it seems we dont want to enforce this since such validations on hostname/fqdn are never applied by kubernetes as well and its upto the user to encure they use an fqdn in their rootdomain that is not stepping on other. 

cc @alena1108

**Comment by vincent99** [comment]
This is clearly confusing and unexpected behavior..  We can't validate simultaneous submissions perfectly, but that doesn't mean we should just not try at all and make it the user's problem.

**Comment by prachidamle** [comment]
So we need to put validations on FQDN uniqueness while creating DNS entries.

**Comment by sangeethah** [comment]
Tested with latest build from master.

We are not allowed to create 2 Global DNS entries with same FQDN.
API errors out with following message:
`
{"baseType":"error","code":"NotUnique","fieldName":"fqdn","message":"","status":422,"type":"error"}
`
