### ISSUE TITLE
Can't create ec2 rke cluster

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17918]
Version - v2.2.0-alpha6

**Steps to reproduce (least amount of steps as possible):**
1.  Try to setup a EC2 RKE cluster with 1 node

**Result:** Waiting for SSH to be available...
![image](https://user-images.githubusercontent.com/11514927/52438473-930d4880-2ad6-11e9-8b93-52c4cba47a79.png)

**Comment by cjellick** [comment]
appears it was caused by using a subnet that was not publicly routeable
on another note, seems like we arent doing a good job of clkeaning up vpcs and subnets for EKS clusters https://github.com/rancher/rancher/issues/17920
