### ISSUE TITLE
New "default" networkMode not respected by native docker integration

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1791]
WIth docker 1.8, if you don't specify a networking mode, "default" is set. In 1.7, it was simply set to "bridged."

**Comment by cjellick** [comment]
Edit: I think in 1.7, the networkMode of the inspect would have been blank/null, not "bridged"

**Comment by sangeethah** [comment]
Prior to this fix, following 2 validation test cases used to fail:

test_native_net_blank 
test_native_managed_network

Failures reported:
test_native_net_blank 
>       assert rancher_container.networkMode == expected_net_mode
E       assert 'none' == 'bridge'
E         - none
E         + bridge

test_native_managed_network
>       assert container.primaryIpAddress != docker_container['NetworkSettings'][
           'IPAddress']
E       assert '172.17.0.102' != '172.17.0.102'
E        +  where '172.17.0.102' = {'dns': [], 'ports': [u'3000/tcp'], 'capDrop': [], 'removed': None, 'dataVolumes': [], 'dataVolumesFrom': None, 'build... None, 'registryCredentialId': None, 'state': u'running', 'firstRunning': u'2015-08-12T05:54:08Z', 'securityOpt': None}.primaryIpAddress

With server version - V0.33.0-rc1 , both the validation test cases succeed.
