### ISSUE TITLE
Which Rancher version support Docker 17.12

### ISSUE THREAD

**Issue by stephanedaviet** [rancher/rancher#17910]
**What kind of request is this (question/bug/enhancement/feature request):**

Question

**Steps to reproduce (least amount of steps as possible):**

Check both pages :
- https://rancher.com/docs/rancher/v1.6/en/hosts/,
- https://github.com/rancher/rancher/releases/tag/v1.6.14

**Result:**

Docker 17.12 is indicated as supported in changelog of 1.6.14, but only since 1.6.15 in compatibility matrix.

**Comment by vincent99** [comment]
Run a modern release instead of either of these?  Both tags are nearly a year old and 1.6.15 fixed a serious k8s CVE.

**Comment by superseb** [comment]
Should be fixed in https://github.com/rancher/rancher.github.io/pull/1056, but please use a recent version.

**Comment by stephanedaviet** [comment]
Thanks. The upgrade is planned.
