### ISSUE TITLE
[server-chart] change relative path in chart build scripts.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#17915]
The server chart build scripts outputs a non-fatal error when calling `scripts/version`. This is due to scripts/version expecting to be called from the scripts directory and the chart/* were being called from the repo root directory.

Update chart/* to use scripts as its base path.

Worked on as part of #17764

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/12

* ran `make` from rancher/rancher root
* build was successful
* chart built successfully & tests passed

We have not yet tested publishing the chart to a repo
