### ISSUE TITLE
Add name & description fields to `cloudCredential` resource

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17912]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

The `cloudCredential` resource should have name and description fields available.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/8/19)
Confirmed issue. This adds name and description to the cloudcredential schema.
```
"name": {
"create": true,
"nullable": true,
"type": "dnsLabel",
"update": false
},
```
```
"description": {
"create": true,
"nullable": true,
"type": "string",
"update": true
},
```
collectionFilters:
```
"name": {
"modifiers": [ 4 items
"eq",
"ne",
"in",
"notin"
]
},
```
```
"description": {
"modifiers": [ 4 items
"eq",
"ne",
"in",
"notin"
]
},
```
