### ISSUE TITLE
EKS k8s version issues #2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17914]
Continuation of #17762

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- [x] Move the drop-down field to the left a bit so it aligns with the Kubernetes version text.

![image](https://user-images.githubusercontent.com/11514927/52013961-9b90ce00-249b-11e9-889f-23307b64db43.png)

- [x] When I click on the drop-down, the drop-down is not aligned with the field?
![image](https://user-images.githubusercontent.com/11514927/52014027-bbc08d00-249b-11e9-9fb5-256d5e8923da.png)

The 17762 issue only fixed half of the issues. This was created to track the unresolved issues that will require a separate PR to fix.

**Comment by lvuch** [comment]
For the second piece that's just how browsers handle selects. @westlywright is there anything that you can think of that I'm not?

**Comment by davidnuzik** [comment]
I figured that was probably the case; I am just repeating what was not covered in the related issue that Tani reported. I figure there is nothing we can do about number 2 because it depends on how the browser renders the drop-down options. Right @westlywright ?

**Comment by lvuch** [comment]
<img width="1273" alt="screen shot 2019-02-15 at 2 34 21 pm" src="https://user-images.githubusercontent.com/3013118/52885556-ddbe3e80-312e-11e9-920c-a86c8cd0d3c7.png">

**Comment by cjellick** [comment]
Per @lvuch wont fix. Please close @davidnuzik unless you find a new reason not to

**Comment by davidnuzik** [comment]
I agree @lvuch @cjellick the issue `#1` no longer seems to be there. Something else must have resolved this. I am not worried about `#2` that we are at the mercy of the browser rendering the drop-down.

Version: Master 2.2 (2/26/19)

`#1` fixed:
![image](https://user-images.githubusercontent.com/45179589/53441893-11b62100-39c5-11e9-97ab-458bcee15cd8.png)

It is still not correct alignment but is much better.

`#2` not possible to fix.
