### ISSUE TITLE
Permission denied on testAndApply action on authconfigs from API

### ISSUE THREAD

**Issue by rawmind0** [rancher/rancher#17924]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Issue occurs trying to do `testAndApply` action on authconfigs from API using go client. Working fine from UI.

Easy way to reproduce is to use rancher2 terraform provider that use API. 
Add `rancher2_auth_config_openldap` definition to tf file and run `terraform apply`. 

tf file example
```
resource "rancher2_auth_config_openldap" "openldap" {
  servers = ["XX.XX.XX.XX"]
  service_account_distinguished_name = "USERDN"
  service_account_password = "PASSWORD"
  user_search_base = "SEARCH_BASE"
  username = "USERNAME"
  password = "PASSWORD"
  port = 389
}
```

**Result:**

If rancher system doesn't have any cluster created, you got permission denied error from the API using rancher `admin` user token:
`Bad response statusCode [403]. Status [403 Forbidden]. Body: [message=Permission denied, baseType=error, code=PermissionDenied] from [https://127.0.0.1:8443/v3/openLdapConfigs/openldap?action=testAndApply]`

Same error checked on `openldap`, `freeIpa` and `activeDirectory`.

**Other details that may be helpful:**

Same action with same user on same rancher system, finish correctly if you create a cluster on rancher, no problem if cluster is in `provisioning` or `pending` state. 
Same action  on a rancher HA installation finish correctly due to `local` cluster already exist. 

**Environment information**

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
Tested on distinct v2.0.X and v2.1.X versions
- Installation option (single install/HA): 
Single install. On HA install same command is not failing due to `local` cluster is created.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by vincent99** [comment]
The UI is just an API client.. a thing it does successfully by definition works in the API.  There has to be some other factor, e.g. like the timing of how fast things are happening (which creating a cluster might cause enough of a delay in to matter, because that otherwise doesn't sound like it could be related at all).

**Comment by rawmind0** [comment]
Hi @vincent99, the issue is using API with go client.. 

I activated audit log on Rancher and it shows the following..

- Using UI works fine, no problem if a cluster exist or not....
```
{
  "auditID": "92c23f96-7257-4e56-ab58-0e0fddbd478c",
  "requestURI": "/v3/openLdapConfigs/openldap?action=testAndApply",
  "sourceIPs": [
    "172.17.0.1"
  ],
  "user": {
    "name": "user-tptf5",
    "group": [
      "system:authenticated"
    ]
  },
  "verb": "POST",
  "stage": "RequestReceived",
  "stageTimestamp": "2019-02-01 11:17:12 +0000",
  "requestBody": {
    "ldapConfig": {
      "actionLinks": {
        "testAndApply": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap?action=testAndApply"
      },
      "baseType": "authConfig",
      "connectionTimeout": 5000,
      "created": "2019-02-01T10:59:21Z",
      "createdTS": 1549018761000,
      "creatorId": null,
      "enabled": true,
      "groupDNAttribute": "entryDN",
      "groupMemberMappingAttribute": "member",
      "groupMemberUserAttribute": "entryDN",
      "groupNameAttribute": "cn",
      "groupObjectClass": "groupOfNames",
      "groupSearchAttribute": "cn",
      "id": "openldap",
      "labels": {
        "cattle.io/creator": "norman"
      },
      "links": {
        "self": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap",
        "update": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap"
      },
      "name": "openldap",
      "nestedGroupMembershipEnabled": false,
      "port": 389,
      "tls": false,
      "type": "openLdapConfig",
      "userDisabledBitMask": 0,
      "userLoginAttribute": "cn",
      "userMemberAttribute": "memberOf",
      "userNameAttribute": "cn",
      "userObjectClass": "simpleSecurityObject",
      "userSearchAttribute": "cn|sn|givenName",
      "uuid": "6da5cab5-2610-11e9-80f9-0242ac110002",
      "servers": [
        "172.17.0.3"
      ],
      "serviceAccountDistinguishedName": "cn=admin,dc=test,dc=io",
      "userSearchBase": "dc=test,dc=io",
      "serviceAccountPassword": "test1234",
      "accessMode": "unrestricted"
    },
    "enabled": true,
    "username": "admin",
    "password": "test1234"
  }
}
```

- Using API with go client, and no cluster created on Rancher...
```
{
  "auditID": "bdd17adb-caf3-4d44-9c5f-657c0078a02e",
  "requestURI": "/v3/openLdapConfigs/openldap?action=testAndApply",
  "sourceIPs": [
    "172.17.0.1"
  ],
  "user": {
    "name": "user-tptf5",
    "group": [
      "system:authenticated"
    ]
  },
  "verb": "POST",
  "stage": "RequestReceived",
  "stageTimestamp": "2019-02-01 12:06:52 +0000",
  "requestBody": {
    "ldapConfig": {
      "id": "openldap",
      "links": {
        "self": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap",
        "update": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap"
      },
      "actions": {
        "testAndApply": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap?action=testAndApply"
      },
      "accessMode": "restricted",
      "connectionTimeout": 5000,
      "created": "2019-02-01T10:59:21Z",
      "enabled": true,
      "groupDNAttribute": "entryDN",
      "groupMemberMappingAttribute": "member",
      "groupMemberUserAttribute": "entryDN",
      "groupNameAttribute": "cn",
      "groupObjectClass": "groupOfNames",
      "groupSearchAttribute": "cn",
      "labels": {
        "cattle.io/creator": "norman"
      },
      "name": "openldap",
      "port": 389,
      "servers": [
        "172.17.0.3"
      ],
      "serviceAccountDistinguishedName": "cn=admin,dc=test,dc=io",
      "serviceAccountPassword": "test1234",
      "type": "openLdapConfig",
      "uuid": "6da5cab5-2610-11e9-80f9-0242ac110002",
      "userLoginAttribute": "cn",
      "userMemberAttribute": "memberOf",
      "userNameAttribute": "cn",
      "userObjectClass": "simpleSecurityObject",
      "userSearchAttribute": "cn|sn|givenName",
      "userSearchBase": "dc=test,dc=io"
    },
    "password": "test1234",
    "username": "admin"
  }
}
```

  Getting 403 permission denied error....
```
{
  "auditID": "bdd17adb-caf3-4d44-9c5f-657c0078a02e",
  "responseStatus": "403",
  "stage": "ResponseComplete",
  "stageTimestamp": "2019-02-01 12:06:53 +0000",
  "responseBody": {
    "baseType": "error",
    "code": "PermissionDenied",
    "message": "Permission denied",
    "status": 403,
    "type": "error"
  }
}
```

- Using API with go client, and a cluster is created on Rancher...
```
{
  "auditID": "14f314cf-9198-4b60-a1ad-6493b42ef84d",
  "requestURI": "/v3/openLdapConfigs/openldap?action=testAndApply",
  "sourceIPs": [
    "172.17.0.1"
  ],
  "user": {
    "name": "user-tptf5",
    "group": [
      "system:authenticated"
    ]
  },
  "verb": "POST",
  "stage": "RequestReceived",
  "stageTimestamp": "2019-02-01 12:33:50 +0000",
  "requestBody": {
    "enabled": true,
    "ldapConfig": {
      "id": "openldap",
      "links": {
        "self": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap",
        "update": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap"
      },
      "actions": {
        "testAndApply": "https://127.0.0.1:8443/v3/openLdapConfigs/openldap?action=testAndApply"
      },
      "accessMode": "restricted",
      "connectionTimeout": 5000,
      "created": "2019-02-01T10:59:21Z",
      "enabled": true,
      "groupDNAttribute": "entryDN",
      "groupMemberMappingAttribute": "member",
      "groupMemberUserAttribute": "entryDN",
      "groupNameAttribute": "cn",
      "groupObjectClass": "groupOfNames",
      "groupSearchAttribute": "cn",
      "labels": {
        "cattle.io/creator": "norman"
      },
      "name": "openldap",
      "port": 389,
      "servers": [
        "172.17.0.3"
      ],
      "serviceAccountDistinguishedName": "cn=admin,dc=test,dc=io",
      "serviceAccountPassword": "test1234",
      "type": "openLdapConfig",
      "uuid": "6da5cab5-2610-11e9-80f9-0242ac110002",
      "userLoginAttribute": "cn",
      "userMemberAttribute": "memberOf",
      "userNameAttribute": "cn",
      "userObjectClass": "simpleSecurityObject",
      "userSearchAttribute": "cn|sn|givenName",
      "userSearchBase": "dc=test,dc=io"
    },
    "password": "test1234",
    "username": "admin"
  }
}
```

  Getting 200 OK

**Comment by cjellick** [comment]
Can you get the full http request? I think the go client has a way to turn on debug, but I don’t know it offhand. Maybe CATLLE_DEBUG env var

**Comment by cjellick** [comment]
Also, where is the TF provider and how do I use it? I’m not a TF user, so I’d you can give exact steps to repro, that’d help

**Comment by cjellick** [comment]
This fails on 2.1 and 2.0?

**Comment by cjellick** [comment]
Is there code you can point to where you are constructing this client and request?

**Comment by rawmind0** [comment]
> Can you get the full http request? I think the go client has a way to turn on debug, but I don’t know it offhand. Maybe CATLLE_DEBUG env var

On the way to get it.

> Also, where is the TF provider and how do I use it? I’m not a TF user, so I’d you can give exact steps to repro, that’d help

Sure, TF provider is https://github.com/rancher/terraform-provider-rancher2

Steps to reproduce:
* Download terraform
* Clone the repo and run `make` to get rancher2 provider binary 
* Copy rancher2 provider binary to current folder.
* Set `RANCHER_URL`, `RANCHER_TOKEN_KEY` and `RANCHER_INSECURE=true` env variables
* Generate TF file with `rancher2_auth_config_openldap` resource

```
resource "rancher2_auth_config_openldap" "openldap" {
  servers = ["XX.XX.XX.XX"]
  service_account_distinguished_name = "USERDN"
  service_account_password = "PASSWORD"
  user_search_base = "SEARCH_BASE"
  username = "USERNAME"
  password = "PASSWORD"
  port = 389
}
```
* Run `terraform init` and `terraform apply` to apply tf file.

> This fails on 2.1 and 2.0?

Yes, failing if no cluster defined on rancher. Working on all versions if rancher has a cluster defined.

> Is there code you can point to where you are constructing this client and request?

`resourceRancher2AuthConfigOpenLdapCreate` is the function that is failing. 
This is the call that is getting permission denied, https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_auth_config_openldap.go#L90

**Comment by cjellick** [comment]
yeah, the audit logs dont have http request headers. im worried theres a funky header being sent.
Also worried the audit logs might be doing some processing on the request url that would obfuscate some nuance. I have no proof of either of these things, just hunches.

**Comment by rawmind0** [comment]
More info about this issue. The error was coming from ldap provider `ldapLogin` function that calls UserManager `CheckAccess` function, when `AccessMode = required || restricted` and `AllowedPrincipalIDs` is not specified.

https://github.com/rancher/rancher/blob/master/pkg/auth/providers/ldap/ldap_client.go#L88
https://github.com/rancher/rancher/blob/master/pkg/auth/providers/common/usermanager.go#L141

No problem when `AccessMode = unrestricted`, but when `AccessMode = required || restricted`, to avoid `Permission Denied` error message, `AllowedPrincipalIDs` is required with at least the test user DN specified.

**Comment by vincent99** [comment]
That's the definition of restricted and required, but what does that have to do with the presence of a cluster changing the result?

**Comment by rawmind0** [comment]
The definition makes sense for both, required and restricted, due to both need `AllowedPrincipalIDs` defined.

The presence of cluster was changing the result on `AccessMode = restricted` without adding `AllowedPrincipalIDs`, because the usermanager function `userExistsInClusterOrProject` was returning true https://github.com/rancher/rancher/blob/master/pkg/auth/providers/common/usermanager.go#L184

Anyway, adding `AllowedPrincipalIDs` field, authConfig `testAndApply` action is working fine with and without cluster existence.

**Comment by cjellick** [comment]
can this be closed @rawmind0 ?
