### ISSUE TITLE
Monitoring: Kubernetes Components Metrics is missing a couple of charts

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17922]
Version: Master 2.2 (2/7/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable monitoring for an RKE cluster
- Expand the "Kubernetes Components Metrics" section

**Result:**
Notice we are missing data from Nginx Ingress Request Rate and Controller Manager Queue Depth.
Click on the Controller Manager Grafana Icon, notice that these charts have No data points in grafana.

**Other details that may be helpful:**
Grafana should show data points for these two charts and rancher should show these in the UI as well under "Kubernetes Components Metrics"

**Comment by thxCode** [comment]
@davidnuzik , the monitoring is following https://kubernetes.io/docs/concepts/cluster-administration/controller-metrics/#configuration to scrape the controller metrics.

Accessing `cluster-level` Prometheus `Status -> Targets` page, I found an refused error on `cattle-prometheus/exporter-kube-controller-manager-cluster-monitoring/0` target: 
```
Get http://xxxxxx:10252/metrics: dial tcp xxxxx:10252: connect: connection refused
```

`docker exec` into`kube-controller-manager` container and execute `curl http://127.0.0.1:10252/metrics`, I can see the controller metrics.

Finally, I found this issue cause by https://github.com/rancher/rancher/pull/17350 which is related with https://github.com/rancher/rke/pull/1056. We are following the **CIS Benchmark Recommendation** to narrow the listening address of `kube-controller-manager` and `kube-scheduler`, but the monitoring could not be able to scrape the metrics of them normally.

cc @loganhz , @orangedeng @cjellick

**Comment by loganhz** [comment]
The fact that we cant get metrics for etcd/controler/scheduler in hardened clusters can just be documented for v2.2.0

We will fix https://github.com/rancher/rancher/issues/18044 after v2.2.0

**Comment by cjellick** [comment]
@loganhz can you open up an issue in rancher/docs so that we dont miss documenting this?

**Comment by loganhz** [comment]
Done

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/54663067-0e710980-4b1b-11e9-854d-2f9df44dcd6e.png)

Now you can see the charts for controller and scheduler.

**Comment by davidnuzik** [comment]
Tested in latest master. We are missing the Nginx Ingress Request Rate chart.
![image](https://user-images.githubusercontent.com/45179589/54705994-29cc1c80-4afb-11e9-9151-e79ee2d44897.png)

**Comment by davidnuzik** [comment]
@thxCode @loganhz FYI reopened

**Comment by davidnuzik** [comment]
@thxCode @loganhz Had discussion with Craig, Sangeetha, et al and this is working as expected. We are not worried about Nginx Ingress Request Rate chart specifically. For all intents and purposes this is working in a way we expect. As such I am moving this back to test.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/20/19) ImageID: 92dd7193e7bf
This adds the following four charts to Kubernetes Components Metrics section of cluster monitoring:
![Screen Shot 2019-03-20 at 11 05 53 AM](https://user-images.githubusercontent.com/45179589/54708287-4e76c300-4b00-11e9-90b5-22cf09f5658d.png)

I tried to create more pods than available to get this data to show up (failed pods, preemption attempts, etc). This data matches what I see visually in Grafana however there is no specific chart for Scheduler E2E Scheduling Latency, Scheduler Preemption Attempts, Scheduling Failed Pods to compare to. However this data appears correct based on my testing done.

I smoke tested this area as well and gave monitoring another high level overview to ensure nothing broke. I did not identify any issues except for a rare occurrence of seeing etcd cluster is unhealthy which I am investigating and will open a separate issue for if necessary but this doesn't appear to be an actual problem and is likely not related.

The test plan will also be improved in this area so we ensure each chart is explicitly checked for each section of cluster / workload / pod / container monitoring.

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher: Master 2.2 (3/20/19) ImageID: 92dd7193e7bf, Rancher commigt 68e56010
Install type: install install
cluster: EC2 cluster, 1 etcd, 1 control plane, 2 workers

The test result is the same as @davidnuzik 's.

**Comment by mshivanna** [comment]
We only see 3 graphs under kubernetes components metrics section. We are on version 2.3.5 rancher.  Is this expected? and when we navigate to grafana dashboard for kubernetes components metrics  none of the graphs display data. 

![image](https://user-images.githubusercontent.com/2934982/73612855-a05ff480-45bd-11ea-9e72-5e772e8cce86.png)

![image](https://user-images.githubusercontent.com/2934982/73612874-d00efc80-45bd-11ea-9f51-e214f6f50520.png)

**Comment by lauretti** [comment]
> 
> 
> We only see 3 graphs under kubernetes components metrics section. We are on version 2.3.5 rancher. Is this expected? and when we navigate to grafana dashboard for kubernetes components metrics none of the graphs display data.
> 
> ![image](https://user-images.githubusercontent.com/2934982/73612855-a05ff480-45bd-11ea-9e72-5e772e8cce86.png)
> 
> ![image](https://user-images.githubusercontent.com/2934982/73612874-d00efc80-45bd-11ea-9f51-e214f6f50520.png)

I have the same issue on Rancher 2.3.5.
