### ISSUE TITLE
Locked roles are no longer displayed in UI #14736

### ISSUE THREAD

**Issue by rchench** [rancher/rancher#17925]
This is the same issue as https://github.com/rancher/rancher/issues/14736 which was opened and closed mid 2018. I found exactly the same issue in rancher 2.2.0-alpha6 release

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Go to Global->Role->Select any cluster or project Role to Edit->Select "Yes" under "Locked" and Save it.
![image](https://user-images.githubusercontent.com/12016189/52450204-e7bcbd80-2aee-11e9-9384-ffee252d3f5d.png)

**Result:**
The edited role (Locked) disappeared from the UI.
It shall have a "Yellow Locked" state rather than make it disappear.
![image](https://user-images.githubusercontent.com/12016189/52450219-f73c0680-2aee-11e9-91ca-47c8c81547a9.png)

**Other details that may be helpful:**
It is still editable if remember and paste the role edit link, e.g.
https://rancher-server-endpoint/g/security/roles/edit/configmaps-manage?type=project

tried the same in v2.1.6 and no such issue.
believe this is a bug.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.0-alpha6
- Installation option (single install/HA):
Single

**Comment by davidnuzik** [comment]
Replicated in master as well (Master 2.2 (2/7/19) ImageID: 72be82632fe2)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/11/19)
Confirmed fix. Locked roles now show up in the UI again. Tested with various cluster and projects roles. Test locking/unlocking. Validate HTTP and API.
