### ISSUE TITLE
[URGENT] restoring backup docs wrong

### ISSUE THREAD

**Issue by xorpierre** [rancher/rancher#17933]
After finding out that rancher has the most INSANE defaults as to NOT save configs that survive a simple reboot. I am trying to push a backup, but the restore commands in the docs are wrong.

It says:
"docker run  --volumes-from <RANCHER_CONTAINER_NAME> -v $PWD:/backup " ?!

Obviously I get :  "docker run" requires at least 1 argument(s)

Can someone shed some light on how to restore from backup?

**Comment by cjellick** [comment]
This is a single command:
```
docker run  --volumes-from <RANCHER_CONTAINER_NAME> -v $PWD:/backup alpine sh -c "rm /var/lib/rancher/* -rf  && tar zxvf /backup/rancher-data-backup-<RANCHER_VERSION>-<DATE>"
```
The images is alpine

**Comment by xorpierre** [comment]
bad docs formatting then

**Comment by cjellick** [comment]
agreed. I've opened this https://github.com/rancher/docs/issues/1133 to address the command formatting
and this https://github.com/rancher/docs/issues/1134 to better surface the fact that the console is ephemeral and only /home and /opt are persistent

i'm curious: what state were you storing & where such that you lost it on a reboot? Did you have /var/lib/docker bind mounted somewhere?

**Comment by xorpierre** [comment]
I actually did not experience data loss in the end, but rancher-master got started as a new container and I thought everything was gone, but the old one was still existing, just not running. Was a big relief after started the old one that all was still there

**Comment by cjellick** [comment]
ah, ok. Glad it turned out that way
