### ISSUE TITLE
Azure AKS node OS Disk size not honored.

### ISSUE THREAD

**Issue by matthewhembree** [rancher/rancher#17934]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create or edit AKS cluster
2. Enter a OS disk size other than 30gb

**Result:**
OS disk size of node is 30gb

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud :: Standard_D2_v2 | Standard_D2s_v3 | maybeAny
- Kubernetes version (use `kubectl version`): 1.12.4

Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/kontainer-engine/pull/107
Close in favor of https://github.com/rancher/rancher/issues/15697
