### ISSUE TITLE
install-docker 17.03.sh shell script is not working on 18.04 Ubuntu

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17935]
Version: Master 2.2 (2/8/19) and this might occur in 1.6 as well (we should check there)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Attempt to provision a cluster by selecting v17.03.x for docker engine
![image](https://user-images.githubusercontent.com/45179589/52492694-ef2fa580-2b86-11e9-92f5-5727bc89505a.png)
- Alternatively just try to execute the following on a fresh VM:
`curl https://releases.rancher.com/install-docker/17.03.sh | sh`

**Result:**
The script will not successfully install docker. It will appear to be operating normally and then eventually print the following before exiting
`E: Version '' for 'docker-ce' was not found`

**Other details that may be helpful:**
It appears as though this version may have been removed from the repo.
Exit code is 100

Here is entire output from my terminal with exit code check at end:
[term_output.txt](https://github.com/rancher/rancher/files/2846017/term_output.txt)

**Comment by superseb** [comment]
`17.03` was never released for Bionic Beaver, see https://github.com/rancher/rancher/issues/13222#issuecomment-394307237

**Comment by davidnuzik** [comment]
gotcha. Then we should update the shell script to provide notice to the user that 17.03 is not available on 18.04 ub and while it might not be practical it would be nice to see this in the UI too if someone tries to create a cluster with 17.03 on 18.04 ub

**Comment by davidnuzik** [comment]
Confirmed 17.03sh working on 16.04 ub; closing in favor of Seb's issue #13222 and I will open a separate issue with enhancement request for the script so it at least notifies the user that 17.03 may not be / is not available on 18.04 ub.

**Comment by davidnuzik** [comment]
Enhancement request: #17936
