### ISSUE TITLE
[UI] Update Configuration on Cluster Monitoring Page Results in 404/Fail

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#17937]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Ensure Cluster Monitoring is enabled, then go back to the Cluster Monitor and click on Update Configuration.

**Result:**
404/Fail

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-alpha6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported HA Cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Meta 16GB/4 Core
- Kubernetes version (use `kubectl version`): 1.12.1

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/18004 
Users don't have to go to the catalog page to edit it
