### ISSUE TITLE
No environment variables relating to service links is created when the service that is linked to has "host" network.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1794]
Server version - Build from master Aug 13

Created a service - T1 (in managed network) and linked to service S1 in "host" network mode as "mytest2" and linked to S2 in "managed" network node as "myweb2"

Environment variables relating to "mytest2" are missing.
<img width="673" alt="screen shot 2015-08-13 at 6 03 42 pm" src="https://cloud.githubusercontent.com/assets/4266958/9265255/b35b3fd0-41e5-11e5-9c66-c1fbec3eedf9.png">

This issue is also seen when the service T1 is in host network

**Comment by alena1108** [comment]
Closing the issue after chatting with @ibuildthecloud . Environment variables are no longer recommended method for connecting to linked services in Docker: https://docs.docker.com/compose/env/

You should use linked service name instead for resolution
