### ISSUE TITLE
When set up pipeline and pick repos should then redirect us to pipeline settings

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17942]
Version: Master 2.2 (2/8/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Proposal:**
Set up a pipeline (I used GitHub) and pick your repo(s).
Notice you are then redirected to the listing of your repos.

I propose we instead redirect to the pipeline settings page so we can see our options for Memory/Cpu reservation/limits etc. Since this is the first time we are setting up our pipeline we are likely interested in any additional settings/options.

**Result:**
Easier for end-users to notice the settings for a new pipeline they have just configured.

**Comment by vincent99** [comment]
No?  If you're just starting using it you're not likely to care about tweaking how many executors and things there are, you want to setup a pipeline on one of the repos you enabled.
