### ISSUE TITLE
UI - Imported Cluster - "Load Balancing" option is not  presented as an option in "port mapping" drop down when user creates a workload.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17941]
Rancher server version - Build from master - Feb 7

Steps to create problem:
Create a imported cluster.
Load Balancing" option is not available as on option in "port mapping" drop down when user creates a workload.

Expected result:
"Load Balancing" option should be presented as an option in "port mapping" drop down when user creates a workload.

Please refer to  - https://github.com/rancher/rancher/issues/12422#issuecomment-461880904

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/21/19)
Confirmed issue. "Layer-4 Load Balancer" is now an option under Port Mapping when creating a workload on an imported cluster.

![image](https://user-images.githubusercontent.com/45179589/53204412-c24cab00-35e8-11e9-9515-f10426d53d57.png)

Inspect HTTP/API and validated this as well. This looks correct.
From request payload > containers > ports
```
ports: [,…]
0: {containerPort: "80", type: "containerPort", kind: "LoadBalancer", protocol: "TCP", sourcePort: "80"}
containerPort: "80"
kind: "LoadBalancer"
protocol: "TCP"
sourcePort: "80"
type: "containerPort"
```
