### ISSUE TITLE
cattle-cluster-agent and cattle-node-agent ping 403 error

### ISSUE THREAD

**Issue by paulmorabito** [rancher/rancher#17952]
Using the latest rancher on Ubuntu 18.04 Linux bare metal. I followed the HA install and when logging into Rancher WEB UI, the cluster I created with rke earlier is set up/initialized. I notice after this is complete that cattle-cluster-agent and cattle-node-agent are in crash loops. The error in the logs are the same for both:

INFO: Environment: CATTLE_ADDRESS=10.42.1.4 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-5f86d579b9-8xk2q CATTLE_SERVER=https://192.168.1.52:6443
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local netis options ndots:5
ERROR: https://192.168.1.52:6443/ping is not accessible (The requested URL returned error: 403)

Using curl, I can access the URL (and get the same error).

Any help would be very appreciated.

**Comment by cjellick** [comment]
What is running at 192.168.1.52:6443?
That is generally the k8s api port

**Comment by cjellick** [comment]
What does hitting the root of that url give you? What url are you hitting in browser to get the UI?

**Comment by paulmorabito** [comment]
If I hit https://192.168.1.52 I get:

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

**Comment by cjellick** [comment]
Yep, that’s the k8s api. You have the wrong url configure CATTLE_SERVER should not be the k8s api. It should be the url you can hit rancher on

**Comment by paulmorabito** [comment]
ahh! how can I change to the correct URL?

**Comment by cjellick** [comment]
Settings page under admin in the UI

**Comment by paulmorabito** [comment]
I changed server URL in the settings to https://192.168.1.52:30443

I tried redeploying both agents and they give me the same error with the old server URL. Do I need to refresh somehow?
