### ISSUE TITLE
Failed to connect to K8s proxy - certificate signed by unknown authority

### ISSUE THREAD

**Issue by paulmorabito** [rancher/rancher#17954]
Using the latest rancher on Ubuntu 18.04 Linux bare metal and followed the HA install. cattle-cluster-agent and cattle-node-agent are both repeatedly logging the following error:

level=info msg="Connecting to proxy" url="wss://192.168.1.52:6443/v3/connect"
time="2019-02-10T05:09:06Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"

When I installed rancher via helm, I didn't specify ingress.tls.source so it should have defaulted to Rancher provided certificates. But this seems to happen when connected to the K8S API.

**Comment by cjellick** [comment]
What version exactly? (We have alphas, so I don’t if you mean that or a supported release)

**Comment by cjellick** [comment]
This is related to the other problem you reported. I tend to think something is misconfigured. I suggest you start from scratch with the installation hide.

**Comment by cjellick** [comment]
Guide not hide (autocorrect)

**Comment by paulmorabito** [comment]
v2.1.6.

Can you point me to the area/config I need to look into more closely? I'll try again from scratch but I have re-checked all my installation steps and it seems like I followed the guide fully.

**Comment by paulmorabito** [comment]
Rebuilding the cluster fixes this.
