### ISSUE TITLE
RFE rancher-logs-collector collect rancher server logs as well as db dump

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#17956]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement request to rancher 1.6's [rancher-logs-collector](https://github.com/rancher/rancher-logs-collector/)

**Enhancement Request:**
add commonly requested bits of info to troubleshoot rancher. Namely rancher server logs (ideally cattle-debug.log's) and the db backing rancher.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
