### ISSUE TITLE
Rancher 2.2 Alpha 6 - meaningful cluster name 

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#17955]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Generate alert

**Result:**
Alert Name: Etcd member has no leader
Severity: critical
Cluster Name: c-l7zln
Namespace: cattle-prometheus
Expression: etcd_server_has_leader{job="exporter-kube-etcd-cluster-monitoring"}==1
Description: Threshold Crossed: datapoint value 1 was equal to the threshold (1) for (30s)

**Expected Result**
A meaningful  cluster name but not 'Cluster Name: c-l7zln'  if Rancher going to manage a lot of environments.

**Comment by aiwantaozi** [comment]
the clusterName is updated in master now, will release soon, will look like Cluster Name: mycluster(ID: c-l7zln)

**Comment by rootwuj** [comment]
Version: master 2.2 (2/27/19) Image ID: bf5e00877a76
Confirmed fixed.
