### ISSUE TITLE
Unable to build using rancher-compose and S3 builds

### ISSUE THREAD

**Issue by gmeans** [rancher/rancher#1796]
When trying to 'create' services using rancher-compose, I'm receiving this:

```
▶ rancher-compose -p <project> create
INFO[0000] Creating service web
INFO[0000] Uploading build for web using provider S3
ERRO[0001] Failed Creating web : :
	status code: 403, request id: []
ERRO[0001] Failed to start: web : :
	status code: 403, request id: []
FATA[0001] :
	status code: 403, request id: []
```

I had an issue w/ the project name (the directory) having a period in it so had to use the -p flag.

I'm guessing it's having an issue authenticating. I have my env vars for AWS configured correctly and am able to run commands using the AWS CLI. I don't see anything in S3 to indicate rancher uploaded anything however.

**Comment by vincent99** [comment]
You need an API key for Rancher (from the API & Keys section of the UI underneath the user icon in the header) to use rancher-compose.  It doesn't use AWS credentials to talk to Rancher because we're not Amazon :-)

**Comment by ibuildthecloud** [comment]
@vincent99 We use S3 to upload builds so if you're doing builds you need both AWS and Rancher credentials set up.

**Comment by vincent99** [comment]
d'oh... I read `rancher-compose up`, not `create`.  Never mind...

**Comment by wlan0** [comment]
@gmeans Are you still facing this issue?

If so, could you paste your `docker-compose.yml` and `rancher-compose.yml` in here?

**Comment by deniseschannon** [comment]
@gmeans If you would still like help, please re-open and provide the docker-compose.yml and rancher-compose.yml files.

**Comment by lewistaylor** [comment]
@gmeans this is not a rancher issue, I had the same problem but it was because the permissions on the bucket created did not match the IAM user I was uploading with.

**Comment by r24y** [comment]
@lewistaylor would you mind posting what you had to change as far as IAM permissions to get it to work? I'm facing the same issue and documentation seems light on the subject.

**Comment by lewistaylor** [comment]
I forget now, but I believe it was on the bucket permissions itself, not the IAM user.

**Comment by r24y** [comment]
Thanks. I'll dig a bit and leave what I find here for the next person.
