### ISSUE TITLE
Upgrade request required when using kubectl exec on a cluster when using single install behind Amazon ALB

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#17963]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Run Rancher in single install (`docker run`) and put ALB in front

**Result:**
`kubectl exec` fails on managed clusters using embedded kubectl and externally using generated kubeconfig with:

```
Error from server (BadRequest): Upgrade request required
```

**Other details that may be helpful:**
UI itself reports no issues when visited

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.1.6
- Installation option (single install/HA):single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):EC2 instance

**Comment by gsoyka** [comment]
For what it's worth, we're seeing the same error when using Helm locally as well:
```
~ $ helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Error: forwarding ports: error upgrading connection: Upgrade request required
```

**Comment by tylfin** [comment]
Trying to solve this for myself, I think you're running into this https://stackoverflow.com/questions/47884666/kubectl-exec-command-failing-with-upgrade-request-required/47890411

**Comment by elixxx** [comment]
> Hello
> 
> We are facing to this problem (ALB in front of rancher. WS works well through the UI but not with kubectl: Upgrade request required ).
> 
> Do you have any information about this issue ? :)
> 
> BR

Having the same Issue with aws ALB

**Comment by TM-Developers** [comment]
hi guys, was there any developments to fix this? Thanks

**Comment by renperez** [comment]
@superseb is there any update on this issue? I am running rancher in eks and using alb ingress and having the same issue. i am running version 2.3.5.

**Comment by gricuk** [comment]
Hi, are there any updates?

**Comment by s50600822** [comment]
I got same issue, verbose logs
`kubectl exec -it --v=9  ... bash`
shows
`69816 helpers.go:219] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Upgrade request required",
  "reason": "BadRequest",
  "code": 400
}]`

**Comment by kjflaherty** [comment]
We have the same issue

**Comment by maradwan** [comment]
I have the same issue, any update?
