### ISSUE TITLE
Rancher should allow sharing of node templates between users/groups

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#17966]
Currently, node templates are tied to each user that creates them. There should be a feature which should allow you to share node templates from a master "admin" account, allowing users to get a more "vending-machine" like experience to spin up clusters (i.e. pre-populated node templates). Users should not be able to access the credentials of the shared node templates, but be able to use them.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/12186
