### ISSUE TITLE
LB-HAproxy loses restarted containers

### ISSUE THREAD

**Issue by Fermiy** [rancher/rancher#17964]
**Bug**

I tried using Rancher 1.6.20 and after update on 1.6.26 this behaviour was present in both environments. I added LB to service through rancher UI (I tried also catalogue launched LB behaviour is the same) rancher/lb-service-haproxy:v0.9.3 and 0.9.6 (Rancher 1.6.20 and 1.6.26). LB loses container completely once it stopped and do not return it back once it is restarted. 

Once containers in service are stopped there is Draintimeout. And LB does not provide new connections to the container that is being stopped. But once container started again configuration in lb is not reloaded and running container is skipped for newly coming connections. If all containers in service were restarted there is no container left that can accept new connection from LB perspective. And service is left in zombie state it is alive but dead at the same time.

I mentioned that config reloading in lb happens sometimes if there is small delay between container in stopped state and started again. However it happens very infrequently. 

If I use old version of this LB (lb-service-haproxy:v0.7.X) everything works as expected but I need new functionality for my stack that was added in HAproxy >= v1.7 

Logs from HA-LB:
LOGS showing behaviour that was present in **0.7.15 or 0.7.17** LBs:
**1 restart**
2/6/2019 8:50:28 AMtime=“2019-02-06T06:50:28Z” level=info msg=“Received target.drain IP: 10.42.162.23, drainTimeout: 10000, eventID: 466b4379-5eef-4171-9ad8-07e1aafbecda, resourceID 1i349872”
2/6/2019 8:50:28 AMtime=“2019-02-06T06:50:28Z” level=info msg="[Endpoint IP: 10.42.162.23, name: 1516362c18a417e74e830f2313719dec917ffae6] Result: Drain not needed"
2/6/2019 8:50:28 AMtime=“2019-02-06T06:50:28Z” level=info msg=“New reply: &client.Publish{Resource:client.Resource{Id:…
2/6/2019 8:50:29 AMtime=“2019-02-06T06:50:29Z” level=info msg=” – reloading haproxy config with the new config changes\n * Reloading haproxy haproxy…

Here is log record with reloading config: **– reloading haproxy config with the new config changes\**

Here is output from lb **v0.9.3**:
I restarted the same container 2 times no reloading happening in any case. An it is not accessible from LB
**1 restart**
2/6/2019 8:51:01 AMtime=“2019-02-06T06:51:01Z” level=info msg=“Received target.drain IP: 10.42.162.23, drainTimeout: 10000, eventID: b1d1ce0c-3d3d-44d0-bfa7-e17346653891, resourceID 1i349872”
2/6/2019 8:51:01 AMtime=“2019-02-06T06:51:01Z” level=info msg="[Endpoint IP: 10.42.162.23, name: 1516362c18a417e74e830f2313719dec917ffae6] Result: Drain not needed"
2/6/2019 8:51:01 AMtime=“2019-02-06T06:51:01Z” level=info msg=“New reply: &client.Publish{R”
**2 restart**
2/6/2019 8:55:43 AMtime=“2019-02-06T06:55:43Z” level=info msg=“Received target.drain IP: 10.42.162.23, drainTimeout: 10000, eventID: 7e5a2904-9771-48cf-a48b-c921c0174c84, resourceID 1i349872”
2/6/2019 8:55:43 AMtime=“2019-02-06T06:55:43Z” level=info msg="[Endpoint IP: 10.42.162.23, name: 1516362c18a417e74e830f2313719dec917ffae6] Result: Drain not needed"
2/6/2019 8:55:43 AMtime="2019-02-06T06:55:43Z
**3 restart**
2/6/2019 8:56:10 AMtime=“2019-02-06T06:56:10Z” level=info msg=“Received target.drain IP: 10.42.162.23, drainTimeout: 10000, eventID: d3b89076-beee-4237-958b-d41f0d3a6de5, resourceID 1i349872”

>>LB does not provide connection in this case after all successive restarts.

**Environment information**
- Rancher 1.6.20;1.6.26
- Docker version (17.12.1-ce):

**Comment by wongchao** [comment]
https://github.com/rancher/rancher/issues/10593
@loganhz  repoduced bug on v1.6.22  and v1.6.25 as following #10593 steps

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
