### ISSUE TITLE
Load balancer configuration

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#17974]
Please add a configurable ability to not inherit target hostname routing rules if the target service is a load balancer service.

**Comment by alena1108** [comment]
The issue is specific to a selector based service when hostname routing rules are defined on a target service.

**Comment by prachidamle** [comment]
This is for the configuration where there are two LB's involved, for a LB config with selector based rules, skip adding hostname/path routing rules if label 'io.rancher.lb_service.skip_target_lb_rules' is set to "true" on the LB and the target service is of kind Loadbalancerservice which is being added by the selector.

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.27-rc1`

**Comment by soumyalj** [comment]
Tested with rancher/server:v1.6.27-rc1
1. Created a service "inttest1" and LB "testlb" pointing to the service inttest1 with selector label `foo=bar`
2. Created another LB "extlb" pointing to "testlb" with selector label "foo1=bar"
The haproxy config of "extlb" inherits the target hostname rules of "testlb"
```
listen default
bind *:42

frontend 80
bind *:80
mode http
acl 80_name_html_path path_beg -i /name.html
use_backend 80_name_html if 80_name_html_path
```

After adding the label 'io.rancher.lb_service.skip_target_lb_rules=true`, the rules were not inherited as seen below in the haproxy.cfg snippet
```
listen default
bind *:42

frontend 80
bind *:80
mode http
default_backend 80_

```
