### ISSUE TITLE
CLI changes for multiclusterapp RBAC and actions

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#17981]
This issue is to track the CLI changes needed for multiclusterapp RBAC and actions
* Multiclusterapp spec will have a new field for Roles which references v3.RoleTemplate
* There will be 2 new actions on multiclusterapp called addProjects and removeProjects for modifying the projects. Both will take as input a list of v3.Project, and for addProjects you can also provide project-scoped answer overrides for the new projects by passing a list of v3.Answer
* Targets field is now non updatable in the API, since we have actions described above for updating them.
* Rest of the fields can be updated via Edit/PUT

**Comment by cjellick** [comment]
@moelsayed to validate

**Comment by alena1108** [comment]
@mrajashree to validate

**Comment by mrajashree** [comment]
Validated with rancher-v2.2.0-rc11
1. Creation with roles
```
./rancher multiclusterapps install --target c-xx7q5:p-dhckk --target c-tfq9t:p-6tldl --role project-member grafana test1-grafana
```
2. Updating a role
```
./rancher multiclusterapps upgrade --role cluster-owner test1-grafana 0.0.31
```
3. Adding a new project 
```
./rancher multiclusterapps add-project test-graf-ap c-tfq9t:p-6tldl
```
4. Removing an existing project
```
./rancher multiclusterapps delete-project test-graf-ap c-xx7q5:p-dhckk
```

This issue was specifically for roles and addProject/removeProject actions
Updating/passing scoped answers and templateversions will be validated in this issue https://github.com/rancher/rancher/issues/17147

**Comment by mrajashree** [comment]
I'm able to add members with different access types while creating the mcapp. But add-member command is failing with the following error
```
➜ ./rancher multiclusterapp add-member admintest member user

FATA[0004] Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=InvalidBodyContent, message=No roles provided] from [https://localhost:8443/v3/multiClusterApps/cattle-global-data:admintest]
```
Is there anything wrong with my command

**Comment by gitlawr** [comment]
Confirmed as a bug.
Usually, a missing field gets unchanged in the proxy store. But missing roles on mcapp update get rejected on API layer.

**Comment by mrajashree** [comment]
Okay @gitlawr, you can assign it back to me to validate once it's ready to test

**Comment by cjellick** [comment]
fix available in cli 2.2.0-rc14

**Comment by mrajashree** [comment]
Validated with cli 2.2.0-rc14
Adding members and removing members both works as expected.
```
➜  rancher-v2.2.0-rc14 ./rancher multiclusterapp lm admintest
NAME      MEMBER_TYPE   ACCESS_TYPE
➜  rancher-v2.2.0-rc14 ./rancher multiclusterapp add-member admintest member user
Multiple results found:
[1] user (user)
[2] Default Admin (user)
Select: 1
➜  rancher-v2.2.0-rc14 ./rancher multiclusterapp lm admintest
NAME      MEMBER_TYPE   ACCESS_TYPE
user      Local User    member
➜  rancher-v2.2.0-rc14 ./rancher multiclusterapp delete-member admintest user
Multiple results found:
[1] user (user)
[2] Default Admin (user)
Select: 1
➜  rancher-v2.2.0-rc14 ./rancher multiclusterapp lm admintest
NAME      MEMBER_TYPE   ACCESS_TYPE
➜  rancher-v2.2.0-rc14
```

**Comment by mrajashree** [comment]
Closing as validated
