### ISSUE TITLE
UI: Ability to create private clusters in GKE

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17991]
UI for https://github.com/rancher/rancher/issues/13980

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/14/19)
Tested UI. Validated this section (Advanced options) under Cluster Options.
![image](https://user-images.githubusercontent.com/45179589/52818688-a97e4b80-3064-11e9-99a5-6c32fdaf8bfc.png)

Validated API/HTTP.
