### ISSUE TITLE
UI: Can't add labels to nodes from GKE

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17990]
UI for https://github.com/rancher/rancher/issues/10922

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/13/19)
Confirmed enhancement. We can now set Node labels for our pool upon GKE cluster creation.

In UI this is in the Node section:
![image](https://user-images.githubusercontent.com/45179589/52736436-16231880-2f87-11e9-96cd-90c93bf72a60.png)

API/http snippet of googleKubernetesEngineConfig:
```
labels: ["foo=bar", "tacos=awesome", "tacquitos=awesome2"]
0: "foo=bar"
1: "tacos=awesome"
2: "tacquitos=awesome2"
```

Confirmed that these labels show up under Nodes page. Confirmed they are also in the GKE web console.

Confirmed I can edit labels (Nodes > node function menu > Edit > Update Labels. You cannot edit labels for the whole pool via the Edit Cluster page. This is expected.

Validated http/api/ui.
