### ISSUE TITLE
Monitoring - failing for "rules-configmap-reloader" container starting

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#17997]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Add `Custom - v1.13.1|v1.11.6` cluster on AWS VMs (one for controlplane & etcd, one for worker)
- Enable `cluster-level` monitoring

**Result:**
Failing for "rules-configmap-reloader" container starting

**Other details that may be helpful:**
- Launch kubectl to execute `k describe pod prometheus-cluster-monitoring-0 -n cattle-prometheus`:
```
Warning  Failed     24s (x4 over 1m)   kubelet, ip-172-31-47-132  Error: failed to start container "rules-configmap-reloader": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config forprocHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/pod02689b56-2e75-11e9-a17a-06be303be28c/rules-configmap-reloader/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```
- It is working, after changing the `resources.limits.memory` from `10Mi` to `50Mi` of "rules-configmap-reloader" conatiner which locates in `prometheus-cluster-monitoring` StatefulSet.
- With `10Mi` resources memory limitation on Ubuntu 18.04 LTS in GCP is ok.

**Environment information**
rancher/rancher:master

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `Custom`
- Machine type (cloud/VM/metal) and specifications (CPU/memory): `AWS t2.medium`
- AWS AMI: `Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - ami-07ad4b1c3af1ea214`

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.1
 Git commit:        e68fc7a
 Built:             Fri Jan 25 14:33:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       e68fc7a
  Built:            Thu Jan 24 10:49:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thxCode** [comment]
The resources limitation is managed by Prometheus-Operator: https://github.com/coreos/prometheus-operator/blob/48248f5dfb3de74daa0eb3aee2fa2912c6646559/pkg/prometheus/statefulset.go#L623-L625, it cannot be overwrited for now.

**Comment by heppstux** [comment]
same problem here – fix would be highly appreciated :)

**Comment by jaysonwor** [comment]
Not using Rancher but found this to be a problem with using the K8s / Prometheus-Operator, and this is the only thread I can find so far....

Having the same issue here. Nothing was upgraded, it just started. Only thing different was a docker security update was applied to the Ubuntu kernel. Also I tried to provision a brand new stack on new hardware and getting the same issue. I do see after some time prometheus-operator container inits but the alert manager doesn't. I tried destroying the prometheus-operator pod and it failed on init with this message (all point to this error):

OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/pod972cf87b-3192-11e9-bae2-005056a0380b/f19343bc4a22779f02cf98fe8f70942a5fd95070466cad490d3f200dc3be28f8/memory.limit_in_bytes: device or resource busy\\\"\"": unknown

**Comment by jaysonwor** [comment]
That is Kubernetes 1.12 and latest helm install prometheus-operator

**Comment by RaynDol** [comment]
HI,

Im having the exact same error with K8S 1.13.3 , in the last few days.


 Kernel Version:             4.14.96-coreos
 OS Image:                   Container Linux by CoreOS 1967.5.0 (Rhyolite)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.6.1
 Kubelet Version:            v1.13.3
 Kube-Proxy Version:         v1.13.3


any idea what this could be ?

**Comment by thxCode** [comment]
```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

Back-off `Docker 17.03` can start "rules-configmap-reloader":
```
$ sudo apt-get update

$ sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

$ sudo yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2

$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   xenial \
   stable"

$ sudo apt-get update

$ sudo apt-get install -y docker-ce=17.03.2~ce-0~ubuntu-xenial containerd.io
```

**Comment by RaynDol** [comment]
@thxCode  - not sure what I should do in k8s to resolve it ? can you please explain ?

**Comment by thxCode** [comment]
@RaynDol , Are you using Rancher? I have not dug why `Docker 18.06.1` occurs `OCI runtime create failed` while deploying Prometheus via Prometheus Operator. I found enabling Rancher Monitoring on GKE `v1.11.7-gke.4` can work by:

```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

$ uname -r
4.15.0-1026-gcp

$ sudo docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.9.4
 Git commit:   f5ec1e2
 Built:        Thu Jan 24 10:43:29 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.9.4
 Git commit:   f5ec1e2
 Built:        Thu Jan 24 10:43:29 2019
 OS/Arch:      linux/amd64
 Experimental: false
```

Maybe you can setup another environment to test with `Docker 17.03.2`.

**Comment by RaynDol** [comment]
@thxCode  - ok thanks. we are not using Rancher directly we are using Prometheus Operator and we got the exact same error.  i guess Prometheus is using it under the hood. do you know perhaps ? any idea how we can overcome this ?

**Comment by thxCode** [comment]
https://github.com/coreos/prometheus-operator/issues/2409 @RaynDol , @jaysonwor , @heppstux , FYI.

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master 2/27

Rancher Installation option: HA

Steps:
- provision a custom cluster with the same config as the issue describes
- enable cluster level monitoring
- check the version of the image `coreos-prometheus-config-reloader`

Result:
- the monitoring works as expected
- the version of the image `coreos-prometheus-config-reloader` v0.29.0 , which is the expected version containing the fix for `resources.limits.memory`

**Comment by BenWUKFast** [comment]
Hey I still get this issue, with the following information can you confirm if I'm doing anything wrong?

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m20s                  default-scheduler  Successfully assigned monitoring/prometheus-k8s-0 to redacted-host
  Normal   Pulling    4m18s                  kubelet, redacted-host   pulling image "quay.io/coreos/prometheus-config-reloader:v0.28.0"
  Normal   Pulled     4m15s (x2 over 4m18s)  kubelet, redacted-host   Container image "quay.io/prometheus/prometheus:v2.5.0" already present on machine
  Normal   Pulled     4m15s                  kubelet, redacted-host   Successfully pulled image "quay.io/coreos/prometheus-config-reloader:v0.28.0"
  Normal   Created    4m15s                  kubelet, redacted-host   Created container
  Normal   Started    4m15s                  kubelet, redacted-host   Started container
  Normal   Created    4m14s (x2 over 4m18s)  kubelet, redacted-host   Created container
  Normal   Started    4m14s (x2 over 4m18s)  kubelet, redacted-host   Started container
  Warning  BackOff    3m43s (x3 over 4m13s)  kubelet, redacted-host   Back-off restarting failed container
  Normal   Pulled     3m29s (x4 over 4m15s)  kubelet, redacted-host   Container image "quay.io/coreos/configmap-reload:v0.0.1" already present on machine
  Normal   Created    3m29s (x4 over 4m15s)  kubelet, redacted-host   Created container
  Warning  Failed     3m29s (x4 over 4m15s)  kubelet, redacted-host   Error: failed to start container "rules-configmap-reloader": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/pod5529d0f0-4722-11e9-b326-801844f05da0/rules-configmap-reloader/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```

```bash
# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
*Note:* Use of kubeadm import and node ports.

**foo.jsonnet**
```
local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-node-ports.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-kubeadm.libsonnet') + {
    _config+:: {
      namespace: 'monitoring',
    },
  };

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

**Comment by thxCode** [comment]
@BenWUKFast , Are you using Rancher Monitoring? Can you test this with 2.2.0-rc6?

**Comment by BenWUKFast** [comment]
@thxCode I'm afraid I'm using prometheus operator directly,  v0.29.0. Apologies I believe I got the wrong repo here :disappointed:
