### ISSUE TITLE
Failed catalog deployment reties to quickly/spams rancher server log

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#17994]
Failed catalog launch is retrying immediately after failing. This is thrashing the tiller install and spamming the rancher server logs. 

Repeated entries like below are too much noise for info level
```
[main] 2019/02/12 00:26:06 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/02/12 00:26:06 GRPC listening on :48861
[main] 2019/02/12 00:26:06 Probes listening on :44274
[main] 2019/02/12 00:26:06 Storage driver is ConfigMap
[main] 2019/02/12 00:26:06 Max history per release is 0
[main] 2019/02/12 00:26:06 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/02/12 00:26:06 GRPC listening on :40740
[main] 2019/02/12 00:26:06 Probes listening on :41174
[main] 2019/02/12 00:26:06 Storage driver is ConfigMap
[main] 2019/02/12 00:26:06 Max history per release is 0
[tiller] 2019/02/12 00:26:07 getting history for release system-monitor
[storage] 2019/02/12 00:26:07 getting release history for "system-monitor"
Release "system-monitor" does not exist. Installing it now.
[tiller] 2019/02/12 00:26:07 preparing install for system-monitor
[storage] 2019/02/12 00:26:07 getting release history for "system-monitor"
[tiller] 2019/02/12 00:26:07 rendering rancher-monitoring chart using values
[tiller] 2019/02/12 00:26:07 performing install for system-monitor
[tiller] 2019/02/12 00:26:07 executing 0 crd-install hooks for system-monitor
[tiller] 2019/02/12 00:26:07 hooks complete for crd-install system-monitor
[tiller] 2019/02/12 00:26:07 getting history for release cluster-monitoring
[storage] 2019/02/12 00:26:07 getting release history for "cluster-monitoring"
Release "cluster-monitoring" does not exist. Installing it now.
[tiller] 2019/02/12 00:26:07 preparing install for cluster-monitoring
[storage] 2019/02/12 00:26:07 getting release history for "cluster-monitoring"
[tiller] 2019/02/12 00:26:07 rendering rancher-monitoring chart using values
2019/02/12 00:26:07 info: manifest "rancher-monitoring/charts/exporter-kube-dns/templates/endpoints.yaml" is empty. Skipping.
2019/02/12 00:26:07 info: manifest "rancher-monitoring/charts/exporter-coredns/templates/endpoints.yaml" is empty. Skipping.
2019/02/12 00:26:07 info: manifest "rancher-monitoring/templates/deployment.yaml" is empty. Skipping.
2019/02/12 00:26:07 info: manifest "rancher-monitoring/charts/grafana/templates/pvc.yaml" is empty. Skipping.
2019/02/12 00:26:07 info: manifest "rancher-monitoring/templates/metrics-service.yaml" is empty. Skipping.
2019/02/12 00:26:07 info: manifest "rancher-monitoring/templates/servicemonitor.yaml" is empty. Skipping.
[tiller] 2019/02/12 00:26:07 performing install for cluster-monitoring
[tiller] 2019/02/12 00:26:07 executing 0 crd-install hooks for cluster-monitoring
[tiller] 2019/02/12 00:26:07 hooks complete for crd-install cluster-monitoring
[tiller] 2019/02/12 00:26:07 failed install perform step: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
2019/02/12 00:26:07 [ERROR] AppController p-ncv7x/system-monitor [helm-controller] failed with : failed to install app system-monitor. Error: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Environment information**

Rancher | master (pulled 2/11/2019)
-- | --
User Interface | v2.2.2
Helm | v2.10.0-rancher8
Machine | v0.15.0-rancher4-1

Installation option (single install/HA): HA

**Comment by ekristen** [comment]
Agreed, there is also no backoff or retry limit. I've seen where the JIT tiller thinks it needs to upgrade an existing deployment but fails and increase the releases and configmaps until the Rancher UI is unusable and the API is very slow. 

I think there should be a retry limit and retry backoff.

**Comment by wzrdtales** [comment]
@superseb Since you closed https://github.com/rancher/rancher/issues/18673

I want to raise this issue with more criticality again. I have had several customers running into this problem, **COMPLETELY BREAKING** their environments! Luckily only one have had this problem in production yet. You really only need to have a failing catalog item, and someone forgetting about it and it will have very serious consequences.

So this is not a minor issue. The fix would be easy, make it configurable to limit the history that helm keeps otherwise the configmap grows into infinity and in the end crashes all kind of components. I've had OOM on the master and etcd nodes, and as well very slow responding interfaces on all sides. Fixing the problem includes deleting all the configmap entries by hand.

Or is there any solution yet to configure the limit of history for helm when using the rancher catalog @superseb? Otherwise there is no solution to avoid and fix this problem yet.

**Comment by superseb** [comment]
This is tracked and fixed in https://github.com/rancher/rancher/pull/19079 and backported to 2.2 in https://github.com/rancher/rancher/pull/19879

**Comment by wzrdtales** [comment]
Ok, is this already released? I just had this problem on 2.2.2 @superseb 

Thank you for the information though!

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/pull/19079. It will be out in 2.2.4

**Comment by wzrdtales** [comment]
Great news! Thanks for your work.
