### ISSUE TITLE
Rancher 2 should be able to run as non-root user

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#17996]
We should only grant the capabilities we need as a non-root user instead of using root user in our container(server/agent)

- [ ] Rancher server run as non-root user
- [ ] Rancher agent run as non-root user
- [ ] Modify the helm chart for deploying Rancher server to set capability we need for our user
- [ ] Check the possibility for other images we owned to run as non-root

**Comment by sameyes911** [comment]
We have the same use case. Is there any progress on this?

**Comment by Fez29** [comment]
Is there any plans to deliver this item?
