### ISSUE TITLE
UI: Add more complex GKE Options 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17993]
UI for https://github.com/rancher/rancher/issues/14634

**Comment by davidnuzik** [comment]
Compared to older release, this and a few related UI issues adds the following to GKE cluster options and node options:

Cluster options new features:
![image](https://user-images.githubusercontent.com/45179589/52806454-51385100-3046-11e9-9989-9a5341f15936.png)

Node options new features:
![screen shot 2019-02-14 at 10 50 55 am](https://user-images.githubusercontent.com/45179589/52806560-8cd31b00-3046-11e9-9e42-df0bc41d89db.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/14/19)

Tested the following per linked issue. This comment will be updated once get more info in that linked issue.

* basic authentication
? What is this?

* client certificate
? I don't see an option to enter client cert in UI ?

* labels
Confirmed. You can set node labels now. Validated this and confirmed this is seen on Google Cloud console.
When you set cluster label first a cluster is brought up with the name we set in UI then it's torn down and we bring up one with the cluster label we specified. This seems odd.

* vpc-native
? What is this ?

* Automatically create secondary ranges
? What is this ? Subnetwork?
```
  ipPolicyCreateSubnetwork: true
```
![image](https://user-images.githubusercontent.com/45179589/52808552-66fc4500-304b-11e9-8f39-6dff1c31caf0.png)

* Master authorized networks
Confirmed. You can set Master authorized network.
```
  enablePrivateEndpoint: false
  enablePrivateNodes: true
  masterAuthorizedNetworkCidrBlocks: ["10.0.0.0/8"]
    0: "10.0.0.0/8"
  masterIpv4CidrBlock: "10.128.0.0/17"
```
![image](https://user-images.githubusercontent.com/45179589/52808643-9612b680-304b-11e9-89b5-87d61b790c0f.png)

* maximum number of nodes per pool
Confirmed. This was already validated in another issue: #17992
```
  maxNodeCount: null
  minNodeCount: null
```
![image](https://user-images.githubusercontent.com/45179589/52808853-23560b00-304c-11e9-949b-acf4b2df3217.png)


* network policy config (GKE appears to ignore this value and always sets `disabled` to `true`)
? What is this? Is this just Network and Node Subnet options? if so already validated in #17992 
```
  network: "default"
  subNetwork: null  ???????
```
![image](https://user-images.githubusercontent.com/45179589/52808946-5bf5e480-304c-11e9-9fbf-f6f829726ea8.png)



Diff below shows list of all new options when submit create GKE cluster form via UI compared to previous. I know many are not related to this specific issue.
```
  diskType: "pd-standard"
  displayName: ""
  driverName: "googlekubernetesengine"
  enableAutoRepair: false
  enableAutoUpgrade: false
  enableMasterAuthorizedNetwork: true
  enableNodepoolAutoscaling: false
  enablePrivateEndpoint: false
  enablePrivateNodes: true
  gkeCredentialPath: ""
  imageType: "UBUNTU"
  ipPolicyClusterIpv4CidrBlock: "10.128.0.1/11"
  ipPolicyClusterSecondaryRangeName: null
  ipPolicyCreateSubnetwork: true
  ipPolicyNodeIpv4CidrBlock: ""
  ipPolicyServicesIpv4CidrBlock: "10.128.0.1/18"
  ipPolicyServicesSecondaryRangeName: null
  ipPolicySubnetworkName: ""
  issueClientCertificate: true
  kubernetesDashboard: false
  labels: []
  legacyAuthorization: false
  localSsdCount: 0
  maintenanceWindow: ""
  masterAuthorizedNetworkCidrBlocks: ["10.0.0.0/8"]
    0: "10.0.0.0/8"
  masterIpv4CidrBlock: "10.128.0.0/17"
  maxNodeCount: null
  minNodeCount: null
  name: ""
  network: "default"
 nodePool: ""
  nodeVersion: ""
  oauthScopes: ["https://www.googleapis.com/auth/devstorage.read_only",…]
    0: "https://www.googleapis.com/auth/devstorage.read_only"
    1: "https://www.googleapis.com/auth/logging.write"
    2: "https://www.googleapis.com/auth/monitoring"
    3: "https://www.googleapis.com/auth/servicecontrol"
    4: "https://www.googleapis.com/auth/service.management.readonly"
    5: "https://www.googleapis.com/auth/trace.append"
  preemptible: false
  resourceLabels: ["clusterlabelkey=labelvalue"]
    0: "clusterlabelkey=labelvalue"
  serviceAccount: "secret"
  subNetwork: null
  taints: []
  useIpAliases: true
  zone: "us-central1-f"
  id: "c-c5sz8"
  internal: false
```

**Comment by davidnuzik** [comment]
@loganhz I don't see anything in UI for issueClientCertificate is this expected? Is it a hidden/unconfigurable field?
cc: @fyery-chen 

otherwise I believe I have validated everything from UI perspective.

**Comment by n313893254** [comment]
@davidnuzik It is a hidden field, always be true.
https://github.com/rancher/ui/blob/bdc2f2d324b99b0ec324e47b4f67baf547b37462/lib/shared/addon/components/cluster-driver/driver-googlegke/component.js#L679

**Comment by davidnuzik** [comment]
Thanks everyone for your help.
Closing per my comment above https://github.com/rancher/rancher/issues/17993#issuecomment-463744885 which has details outlining the testing done. Some further testing is also continuing in this area as we test other related issues. Validated http/API.
