### ISSUE TITLE
Need delete old alertmanager when upgrade rancher

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18007]
old server version: 2.1.5
new server version v2.2.0-alpha6

1. start a old version server
2. add notifier, add cluster alert and project alert
3. check whether alertmanager deploy in system project cattle-alerting namespace
4. upgrade rancher server tot v2.2.0-alpha6
5. after upgrade we deploy an alertmanager app to cattle-prometheus but the old alertmanager deployment in cattle-alerting namespace not remove before, we should delete it automatically

**Comment by loganhz** [comment]
please validate it @thxCode

**Comment by thxCode** [comment]
**Validated steps:**
- Start an old version server
- Add notifier, add cluster alert
- Check whether Alertmanager deploy in `System` project `cattle-alerting` namespace
- Upgrade rancher server to `rancher/rancher:master`

**Result:**
After the upgrade, an Alertmanager app is deploying in `cattle-prometheus` and the old Alertmanager deployment in `cattle-alerting` namespace has been removed

@loganhz   cc @aiwantaozi
