### ISSUE TITLE
UI: Support update prometheus config in enable monitoring page

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18004]
UI for https://github.com/rancher/rancher/issues/17340

**Comment by davidnuzik** [comment]
@loganhz could we change the Edit button to a Save button? When I click on the Edit button in my mind I am expecting a new page or modal to pop-up asking for what I want to change and then save. If we just make this a save button I think it will make more sense that we are already on the page for editing.

![image](https://user-images.githubusercontent.com/45179589/53050021-96e58700-3455-11e9-9fad-d16d50ee861d.png)

**Comment by loganhz** [comment]
It will be addressed in https://github.com/rancher/ui/pull/2673

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/19/20)
Confirmed issue. Refer to #17734 where this was tested.
The Edit button is now a normal Save button.
