### ISSUE TITLE
Add australiasoutheast to AKS regions

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#18009]
**What kind of request is this (question/bug/enhancement/feature request):**
task

https://azure.microsoft.com/en-gb/updates/general-availability-azure-kubernetes-service-in-australia-southeast/

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/12/19)
Confirmed enhancement. Australia East was added as a region option when creating an AKS cluster.
Validated http and API `location": "australiaeast",`. Validated in Azure console that this was the correct region.

![image](https://user-images.githubusercontent.com/45179589/52658053-531fda00-2eb7-11e9-9623-07a457c26aea.png)


![image](https://user-images.githubusercontent.com/45179589/52658925-7a77a680-2eb9-11e9-8e75-33247b5da73a.png)

**Comment by davidnuzik** [comment]
I am going to restest this. K8s service is in Australi East but other components in resource group are in southeast. This does not add up.

**Comment by davidnuzik** [comment]
Re-validated I didn't have a build with the commit for this and had mistaken the Australia East entry from the location drop-down. Tested again and this is working. Validated in API/HTTP again. Confirmed each component of this resource group is in the appropriate Australia Southeast region in Azure web console. See previous comments.

location: "australiasoutheast"

![image](https://user-images.githubusercontent.com/45179589/52681208-453e7900-2ef8-11e9-9cd8-417d788581e1.png)

![image](https://user-images.githubusercontent.com/45179589/52681191-38218a00-2ef8-11e9-9734-1c41b0199f2f.png)
