### ISSUE TITLE
Specifying the type of secret should be supported from UI

### ISSUE THREAD

**Issue by jiuchen1986** [rancher/rancher#18002]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Try to add a secret from UI.

**Result:**
It's not able to specify the type of the secret.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-alpha6
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
Rancher API Field is `kind` maps to type in kube api

**Comment by codyrancher** [comment]
I'm currently working on the ui for this. It looks like the backend still needs some work done before it can support the 'kind' field.

When making a request I get this response back:
```
{
"baseType": "error",
"code": "InvalidOption",
"fieldName": "kind",
"message": "",
"status": 422,
"type": "error"
}
```
As seen in this screenshot:
![Screen Shot 2019-09-30 at 3 50 58 PM](https://user-images.githubusercontent.com/55104481/65922505-6033ff80-e39a-11e9-81a8-d50580886bf2.png)

**Comment by JaseKing** [comment]
I'm facing this issue on a new v2.5.9 install, prevents me from provisioning via Ansible.
