### ISSUE TITLE
Parameters of Ceph RBD StorageClass Provided by Rancher 2.2.0-alpha6 Should Support Specifying Namespace of User Secret

### ISSUE THREAD

**Issue by jiuchen1986** [rancher/rancher#18000]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Try to create a storage class with Ceph RBD provisioner via Rancher 2.2.0-alpha6 UI.

**Result:**
No field in Parameters could be used to specify the namespace of user secret.

**Other details that may be helpful:**
Since Kubernetes 1.12+, the namespace of user secret used for dynamically provisioning Ceph RBD PV is able to be specified in the definition of Ceph RBD StorageClass. Without this field being specified, each namespace containing workloads using Ceph RBD PVs must include a replica of the user secret. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-alpha6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/69047319-dfa68c80-0a35-11ea-9621-415eb2767f44.png)
