### ISSUE TITLE
Failed to update system-monitor to 0.0.2 in Rancher 2.2.0-alpha6

### ISSUE THREAD

**Issue by jiuchen1986** [rancher/rancher#18003]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable cluster monitoring for a cluster
2. Go to system project of the cluster
3. Go to Catalog Apps of the project
4. Upgrade system-monitor to 0.0.2

**Result:**
The system-monitor APP stuck in "Installing" status, with error outputs:
```
Failed to install app system-monitor. Error: UPGRADE FAILED: Service "expose-operator-metrics" is invalid: spec.clusterIP: Invalid value: "None": field is immutable && Deployment.apps "prometheus-operator-system-monitor" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"prometheus-operator", "chart":"prometheus-operator-0.0.2", "release":"system-monitor"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-alpha6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by jiuchen1986** [comment]
When the system-monitor became sticking in "Installing" after triggering upgrade, it is neither able to rollback nor remove the application, even the real workload of system-monitor on cluster has gone.

**Comment by loganhz** [comment]
It doesn't support to upgrade to 0.0.2 in alpha-6.  It should be invisible in UI. It will be fixed in https://github.com/rancher/rancher/issues/15014
