### ISSUE TITLE
After upgrading auth enabled rancher server to latest build from master, not able to log in to the server.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1800]
Rancher server was running on build made form master  on Aug at ~2:30 pm. This set up had git hub authentication turned on and allowed access to member from a certain group say- "group1".

Upgraded rancher server to build made form master  on Aug at ~9:00 pm.  After the upgrade , I am not able to log in as member of "group1" . Following error presented to the user:

Error
Unauthorized (401)
Unauthorized

**Comment by sangeethah** [comment]
In this set up , listing projects as admin client returns no projects:

From test code , following exception seen:

 project = admin_client.list_project()[0]
E       IndexError: list index out of range

**Comment by hibooboo2** [comment]
rancher/cattle#754 addresses this.

**Comment by sangeethah** [comment]
RancherServer - V0.32.0 - access control enabled for git-hub to allow access for "Default" environment and another env - "test" that was created by admin to couple of github users.

Upgraded to RancherServer - V0.33.0-rc3.
The github users that were given access to the environment continue to have access and are able to get access to the server and environment.

Closing this issue.
