### ISSUE TITLE
Make first letter of each driver for cluster/node drivers capitalized

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18018]
Version: Master 2.2 (2/12/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Details and Proposal:**
Look at the Node drivers and Cluster drivers list. Notice that some do not have the first letter capitalized for nodes and under clusters they are all lowercase.

We'd like to override the first letter for each cluster/node driver always capitalized.

**Comment by vincent99** [comment]
If not overridden with a specific name, which cloud.ca needs to be anyway.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/13/19)
Confirmed issue. Every Node and Cluster driver now has the first letter for each name capitalized.
