### ISSUE TITLE
AKS and GKE Monitoring - No charts for workloads, pods, containers

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18014]
Version: Master 2.2 (2/12/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable monitoring on AKS
- Enable monitoring on GKE (UPDATE: Already fixed in #17745 )

**Result:**
Notice there are no charts for any workload, pod, container.
It looks like GKE still has work to be done #17745 which might be the cause for GKE but I don't see an issue for AKS work that needs to be done for this.

**Comment by jiaqiluo** [comment]
The cluster-level monitoring is broken on EKS cluster sometimes. 
Rancher: master 2/12, single install 

<img width="1671" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/52670023-d4d23080-2ed4-11e9-9f3f-27093316de5a.png">

**Comment by thxCode** [comment]
@davidnuzik , GKE still has work to be done on UI (https://github.com/rancher/rancher/issues/17745), a workaround is accessing Rancher view API like (https://PUBLIC-IP/v3/clusters/CLUSTER-ID) to send `enableMonitoring` action with `exporter-kubelets.https=false`:
![image](https://user-images.githubusercontent.com/3394724/52699233-3f0bd380-2fb0-11e9-9f52-75814096c961.png)

I am afraid that AKS is also the same problem. Can you try the above steps on AKS?

**Comment by davidnuzik** [comment]
@thxCode I gave this a shot with the answer you mentioned and it is still not working on AKS.
![image](https://user-images.githubusercontent.com/45179589/52726690-e49f5280-2f70-11e9-80c7-2dffa0fb44ae.png)
(HTTP 200 OK) monitoring gets enabled, but still cannot see charts for workloads/pods/containers.
![image](https://user-images.githubusercontent.com/45179589/52726725-fbde4000-2f70-11e9-932d-d744fd14f74d.png)

**Comment by davidnuzik** [comment]
Note: GKE testing is done and confirmed working per issue #17745 
There is no need to test GKE side of things any further (well except for standard regression tests before release).

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/19/19)
Confirmed fixed. I tested like the related #17745 issue but with AKS. This is now working as expected. I see charts for workloads, pods, containers and they appear accurate. See the related issue for GKE testing notes.
