### ISSUE TITLE
Failed to reconcile etcd plane / websocket: bad handshake

### ISSUE THREAD

**Issue by dabeck** [rancher/rancher#18016]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Adding a new ETCD-Node to an existing cluster failes with:
`Failed to reconcile etcd plane: Failed to add etcd member [etcd-node3] to etcd cluster`

When connection via SSH to the newly created node it has 3 docker containers running:
```
05d0f5e5fbf1        rancher/rancher-agent:v2.1.6   "run.sh --server htt…"   21 minutes ago      Up 21 minutes                           stoic_pasteur
33394a4e4ac2        rancher/rancher-agent:v2.1.6   "run.sh -- share-roo…"   21 minutes ago      Up 21 minutes                           share-mnt
f3f5cf11e663        rancher/rancher-agent:v2.1.6   "run.sh --server htt…"   21 minutes ago      Up 21 minutes                           amazing_pike
``` 

While the last two containers seem to run normaly the first one logs:
```
time="2019-02-12T14:34:09Z" level=info msg="Connecting to proxy" url="wss://rancher.my.domain/v3/connect"
time="2019-02-12T14:34:09Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-02-12T14:34:09Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

**Result:**
The cluster is stuck in provisioning.

Creating worker nodes works perfectly!
Sadly an identical cluster created at the same platform works with creating new ETCD nodes 🙈 

**Environment information**
- rancher/rancher:v2.1.6
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): OpenStack provisioned via Rancher 2.0.x
- Machine type (cloud/VM/metal) and specifications (CPU/memory): OpenStack VM
- Kubernetes version (use `kubectl version`): 1.10.11-rancher1-1

- Docker version (use `docker version`): 18.3.1

**Comment by cjellick** [comment]
Can you curl that url from the host?

**Comment by dabeck** [comment]
Sure

**Comment by superseb** [comment]
What's the status of etcd in the cluster where you are trying to add a node?

See https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/#etcd-cluster-and-connectivity-checks

**Comment by dabeck** [comment]
OK, I've got no idea why and changed like nothing related to etcd but now it's working again 🤷‍♂️  a little bit confusing but I'm closing this for now. Thank you for your suggestions ✌️

**Comment by JasonvanBrackel** [comment]
We're seeing this behavior enough to reopen.  Having a community member update this ticket.

**Comment by TechCanuck** [comment]
Happened to me today, was in this state for maybe 40 minutes.  Repro steps:
- Rancher HA cluster, running 2.1.7
- Added a new managed cluster, added a first server to it, specified all 3 roles for the server (etcd, worker, controlplane)
- We us custom config, specified both the external and internal address.  My internal address is an internal 10.x address space
- When copy/pasting the add server node, we noticed that the agent started but no connectivity.  Logs attached.

NOTEABLES: 
- our rancher cluster sits behind an nginx proxy - straight passthrough LB

40 minutes or so later it just 'started' connecting.

```
time="2019-06-10T17:53:31Z" level=info msg="Connecting to wss://rancher.omitted.com/v3/connect with token aaaaaaaa"
time="2019-06-10T17:53:31Z" level=info msg="Connecting to proxy" url="wss://rancher.omitted.com/v3/connect"
time="2019-06-10T17:53:31Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-06-10T17:53:31Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-06-10T17:53:41Z" level=info msg="Connecting to wss://rancher.omitted.com/v3/connect with token aaaaaaaa"
time="2019-06-10T17:53:41Z" level=info msg="Connecting to proxy" url="wss://rancher.omitted.com/v3/connect"
time="2019-06-10T17:53:41Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-06-10T17:53:41Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

Token and domain changed to protect the innocent.

**Comment by superseb** [comment]
In Rancher v2.3, we added more websocket logging (logging the actual error besides "bad handshake"), which should give a better indication what is happening. If you encounter a similar issue, please file a new issue with the requested information and the logging.
