### ISSUE TITLE
Clicking "Launch" button on the MultiClusterApp launch form does nothing.

### ISSUE THREAD

**Issue by luisdavim** [rancher/rancher#18020]
*Describe your issue here*

Clicking "Launch" button on the MultiClusterApp launch form does nothing.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-alpha6` UI: `v2.2.2` |
|Route|`global-admin.multi-cluster-apps.catalog.launch`|

The browser console displays an error:
```
No schema found to validate templateversion
```

**Comment by vincent99** [comment]
That message is "normal" and not relevant to whatever problem you're having.

**Comment by luisdavim** [comment]
It's the only thing popping up in the console when I click the button, anything you'd like me to look for? I also don't see anything in the networking tab.

**Comment by luisdavim** [comment]
Looks like yesterday I've missed an error. It seems like the problem is that the chart I'm trying to deploy from my private repo doesn't have a readme, I'm seeing this error:
```
{
"baseType": "error",
"code": "ServerError",
"message": "resource name may not be empty",
"status": 500,
"type": "error"
}
```

on https://rancher.my-domain.com/v3/templateVersions/cattle-global-data:my-chart-0.1.0/readme

**Comment by mrajashree** [comment]
@luisdavim you would be seeing this error then even while launching a regular non-multicluster catalog app then?

**Comment by luisdavim** [comment]
I guess so, my focus has been on multicluster apps, I'll check that once I'm on a computer.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
