### ISSUE TITLE
Enable k8s 1.12 and 1.13 non experimental support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18023]
Enable k8s 1.12 and 1.13 official support for clusters provisioned by RKE

**Comment by alena1108** [comment]
The fix is available and can be tested against rke >=`v0.1.17-rc1` and rancher >= `v2.1.7-rc1`

**Comment by soumyalj** [comment]
Tested with v2.1.7-rc2 on setup k8s 1.13.1 with docker 18.06 
Tested with v2.1.7-rc2 on setup k8s 1.13.1 with docker 18.09

Automation runs passed except for the issues https://github.com/rancher/rancher/issues/16391 and https://github.com/rancher/rancher/issues/17309

**Comment by sowmyav27** [comment]
Tested with v2.1.7-rc2 on setup k8s v1.12 with docker 18.06 and docker 18.09.

Automation test cases pass, except for the issues https://github.com/rancher/rancher/issues/16391 and https://github.com/rancher/rancher/issues/17309
