### ISSUE TITLE
Provide CRD yaml examples

### ISSUE THREAD

**Issue by luisdavim** [rancher/rancher#18021]
I'm opening this here because https://github.com/rancher/types doesn't allow creating issues.
It would be nice to have a place where we can take a look at some examples for rancher's CRDs.

**Comment by vincent99** [comment]
Rancher's CRDs are not a "public" interface and we do not support manipulating or creating them yourself or make any guarantee that their structure will stay the same or be compatible between versions.  Use the actual API, which you can explore by going to `https://your-rancher/v3`.

**Comment by luisdavim** [comment]
The reason I'm asking is because I'm trying to evaluate the multicluster apps and neither the rancher cil or the ui is allowing me to do it. I've opened issues about it. Also I don't want to manage my deployments through the ui or a bunch of scripts. I'd prefer to keep yaml manifests in a git repo.

**Comment by luisdavim** [comment]
#18017 and #18020 are the issues I was referring to in my previous comment. I'll take a look at the api and see if that's enough for my needs.

**Comment by luisdavim** [comment]
BTW, what is the recommended approach for managing cluster configuration?

**Comment by superseb** [comment]
API/Terraform/CLI are all options for this.

Let me know if there are any other questions.
