### ISSUE TITLE
UI - Add option at Cluster level logging config to include RKE K8s system components or not

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#18026]
UI fo rhttps://github.com/rancher/rancher/issues/15555
To address the feedback on the parent issue, an API field was changed from `excludeSystemComponent` to `includeSystemComponent` for `clusterLoggingSpec`.

**Comment by cjellick** [comment]
Related https://github.com/rancher/rancher/issues/17228

**Comment by kingsd041** [comment]
Version: master 2.2 (2/14/19)  Image ID: 9d5bb3a31761
Confirmed fix.  
1. The interface name has been changed to `includeSystemComponent `
2. Cluster level logging defaults to `True`
