### ISSUE TITLE
Run Kubernetes conformance tests against k8s 1.12.5, 1.11.6, 1.13

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18022]
We have to evaluate k8s 1.12.5, 1.11.6 and 1.13 by running conformance tests against them. Also we might need to incorporate k8s conformance test into jenkins automation run in the future.

**Comment by moelsayed** [comment]
https://github.com/cncf/k8s-conformance/pull/486
https://github.com/cncf/k8s-conformance/pull/487
https://github.com/cncf/k8s-conformance/pull/488

**Comment by alena1108** [comment]
Closing as validated. The conformance tests have passed, and the corresponding prs have been merged.
