### ISSUE TITLE
There is no validation done for cloud credential .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18037]
Rancher server version - Build from master - Feb 12

Steps to reproduce the problem:
Create a cloud credential for DO provider with invalid accessToken.
Cloud credential creation succeeds.

Expected Behavior:
Cloud credential creation should fail.

**Comment by alena1108** [comment]
Reassigning to the UI as per @vincent99 the logic of credential validation should be done on the UI side.

**Comment by westlywright** [comment]
@alena1108 @vincent99 What API's should I be hitting? We don't have any centralized place to send the credentials to to validate so should I hit random API's with the different cloud providers?

**Comment by vincent99** [comment]
Yes, one of the basic calls that the node driver or the UI are going to call later anyway... list instance types, regions, networks, etc.

**Comment by westlywright** [comment]
Partial support for DO and Amazon has been pushed

**Comment by westlywright** [comment]
@cjellick do you want to move this ticket to test and open a new one for the investigation into vsphere/azure etc?

**Comment by cjellick** [comment]
Yep. Can you enumerate the providers for which we DO do validation?

**Comment by sangeethah** [comment]
Tested with latest build from master.

When creating a cloud credential for "Amazon" with invalid keys user is presented with following error message:

``401 AuthFailure: There was a problem validating your keys. Enter valid credentials and try agian.```

When creating a cloud credential for "Amazon" with valid keys but with a region the keys dont have access to ,  user is presented with following error message:

```403 UnauthorizedOperation: There was a problem validating your keys. Enter valid credentials and try agian.```

When valid credentials are entered , able to create cloud credentials successfully.

When creating a cloud credential for "DO" with invalid keys user is presented with following error message:
```401: There was a problem validating your keys. Enter valid credentials and try agian.```
