### ISSUE TITLE
UI - Error message not presented to user when adding global DNS entries fails.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18038]
Rancher server version - Build from master

Steps to reproduce the problem:
Create a global DNS provider.
Create a Global entry with fqdn say - "test1.test.com"
Create another Global entry with same fqdn  - "test1.test.com". API fails with error - "{"baseType":"error","code":"NotUnique","fieldName":"fqdn","message":"","status":422,"type":"error"}"

No error message is presented to the user.

Expected Behavior:
Error message should be  presented to the user.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/25/19)
Confirmed issue. When you get an API error (such as attempt duplicate entry) you will get an appropriate error in the UI:

![image](https://user-images.githubusercontent.com/45179589/53356053-c712a700-38e7-11e9-9678-e8a451b5ed76.png)
