### ISSUE TITLE
etcd restore fails after an upgrade from v2.1.6 to master

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18035]
Rancher version: v2.1.6

Steps:
1. Create a 3 node cluster with all 3 roles in v2.1.6
2. Create few workloads
3. Upgrade rancher from v2.1.6 to master
4. After upgrade succeeds and cluster is in active state, create a backup.
5. Local backup succeeds.
6. Perform a restore. 
Restore fails with the below error.

```
Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-099519145/cluster.rkestate: no such file or directory

```
Logs from rancher server:
```
2019/02/12 19:30:45 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10553
2019/02/12 19:30:45 [INFO] Restoring etcd snapshot c-82vk7-8zmj2
2019/02/12 19:30:45 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/02/12 19:30:45 [ERROR] ClusterController c-82vk7 [cluster-provisioner-controller] failed with : Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-086015474/cluster.rkestate: no such file or directory
2019/02/12 19:30:54 [ERROR] EtcdBackupController c-82vk7/c-82vk7-8zmj2 [etcdbackup-controller] failed with : [etcd-backup] cluster doesn't have a backup config
2019/02/12 19:32:45 [INFO] Provisioning cluster [c-82vk7]
2019/02/12 19:32:45 [INFO] Restoring cluster [c-82vk7] from backup
2019/02/12 19:32:50 [ERROR] EtcdBackupController c-82vk7/c-82vk7-vrl99 [etcdbackup-controller] failed with : [etcd-backup] cluster doesn't have a backup config
2019/02/12 19:32:50 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10770
2019/02/12 19:32:51 [INFO] Restoring etcd snapshot c-82vk7-8zmj2
2019/02/12 19:32:51 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/02/12 19:32:51 [ERROR] ClusterController c-82vk7 [cluster-provisioner-controller] failed with : Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-099519145/cluster.rkestate: no such file or directory
2019/02/12 19:33:02 [ERROR] EtcdBackupController c-82vk7/c-82vk7-8zmj2 [etcdbackup-controller] failed with : [etcd-backup] cluster doesn't have a backup config



```

**Comment by moelsayed** [comment]
@soumyalj after upgrading rancher server, you will need to edit the cluster to enable rancher backup, otherwise you will not be able to see the backup/restore actions on the cluster. 

Once the cluster is updated to enable the new backup feature, they backup/restore actions will be available.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.1.6 to master build from Feb 19th
1. Created a cluster in v2.1.6 with few workloads. 
2. Upgrade rancher from v2.1.6 to master
3. After upgrade succeeds, cluster is in active state, backup and restore options are not available on the cluster
4. Edit the cluster and enable rancher local back up. The cluster goes to updating state to reflect the new changes. etcd-rolling-snapshots container will be removed from the etcd nodes
5. Backup and restore options will now be available on the cluster. 
6. Create a backup and local backup succeeds.
7. Perform restore operation and restore succeeds.
