### ISSUE TITLE
Creation of vmware node template failed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18040]
**Steps to reproduce (least amount of steps as possible):**
Appropriate values for the below fields were entered.
vCenter or ESXi Server
Username
Password
Data Center
Pool
Host
Data Store
Network

**Expected Result**
Template should be created successfully.

**Actual result:**
Validation failed in API: vmwarevsphereConfig password=NotNullable 422:

**Response from UI:**
{"baseType":"error","code":"InvalidFormat","fieldName":"vmwarevsphereConfig","message":"password=NotNullable 422: ","status":422,"type":"error"}

**Request:**
<img width="823" alt="vmwarebug" src="https://user-images.githubusercontent.com/26032343/52671556-3c39b180-2ed0-11e9-9abf-854060734e29.png">

**Environment information**
- Rancher version: rancher:master(02/12/2019)

**Comment by kinarashah** [comment]
@westlywright It looks like we're sending empty password even if the credential is set, don't see the `secretKey` or `clientSecret` getting sent for other node templates, could you confirm this is the issue?

**Comment by westlywright** [comment]
@kinarashah it is a UI issue, the `vmwarevsphereConfig` is being initialized with the password field which is breaking stuff. I'll assign to myself and have a fix in shortly.

**Comment by sowmyav27** [comment]
verified on latest master build rancher:master (02/14/2019).

Able to create a vSphere node template. 

<img width="1275" alt="screen shot 2019-02-14 at 12 16 28 pm" src="https://user-images.githubusercontent.com/26032343/52815047-7c28a200-3052-11e9-82a3-1d29802ec2d3.png">
