### ISSUE TITLE
Rancher-monitoring prometheus can't scrape node-exporter, etcd, scheduler and controller-manager endpoints in hardened cluster

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#18044]
With a cluster that follows security best practices, ports for etcd (tcp:2379), kube-scheduler (tcp:10251) and kube-controller-manager (tcp:10252) should not be open to cluster worker nodes.  

Scraping the endpoints directly will not be possible. We need alternatives.

Current thoughts are running some kind of simple agent/daemonSet that runs on the etcd/controlplane nodes to scrape the service and push the metrics to prometheus  https://prometheus.io/docs/instrumenting/pushing/

**What kind of request is this (question/bug/enhancement/feature request):**
bug

gzrancher/rancher#10986

gzrancher/rancher#7392

**Comment by jgreat** [comment]
This is also an issue for node_exporter.  The node_exporter ports should not be exposed to the external network.  If services are on the host network, we should default to running metrics endpoints on localhost.

Possible solution for a push agent https://github.com/Showmax/prometheus-pusher.

**Comment by loganhz** [comment]
Proposed changes

![image](https://user-images.githubusercontent.com/21168270/59521844-17efe080-8e82-11e9-914f-9c911630857f.png)

**Comment by MrBones757** [comment]
Is there any update / ETA on this issue? 
I've deployed a patched cluster following the CIS hardening guide provided in the documentation and appear to be having the same issues as described. 

I've spent some time looking into this issue and attempting to understand this. I'm at a point where i could help test a potential solution if required.

**Comment by gpkoltermann** [comment]
Any update?

**Comment by bdschaap** [comment]
Are there any workarounds?

**Comment by bhrobinson** [comment]
I am researching this issue, and coming up against it as well. We just updated to the 2.3 builds, and according to bug 17992 this was going to be fixed after 2.2.0 and just count it as a limitation. 

Can we get some kind of update?

**Comment by FedeBev** [comment]
Hi there, any news about that?

**Comment by Tejeev** [comment]
Would this increase latency for alerts because of the push?

**Comment by jiaqiluo** [comment]
reopen this issue because we see the monitoring v2 is not working on harden cluster in master-head currently 
https://github.com/rancher/rancher/issues/28536

**Comment by jiaqiluo** [comment]
reopen because of https://github.com/rancher/rancher/issues/29059

**Comment by jiaqiluo** [comment]
`v2.5-b72284720041c18fa2e64f63896c0388133aa9f6-head` 
still hit the same error https://github.com/rancher/rancher/issues/29059#issuecomment-707997762

**Comment by jiaqiluo** [comment]
The bug fix is validated on monitoring v2 chart `9.4.201` on 
- rancher:`v2.5-7eb1792946639251f51bd109b630f9c1cf8940c2-head`
- rancher:`master-3d755ff62ae975044b19d1b74c564e9920127f73-head`


Results:
- the monitoring v2 is installed successfully on a harden cluster 
- all endpoints (node-exporter, etcd, scheduler and controller-manager endpoints) are healthy in Prometheus 
- metrics show data in Grafana
