### ISSUE TITLE
Unable to provision Azure cluster with node provider / cloud credentials

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#18043]
rancher/rancher:master 2/12
HA installation 

When creating an Azure cluster with cloud credentials, the following error is seen: 
`Error setting machine configuration from flags provided: azure driver requires the "azure-subscription-id" option.; Timeout waiting for ssh key` 

To reproduce: 
* Attempt to provision Azure cluster
  * Add cloud credentials for Azure with subscription id, app id, and app secret
  * Create cluster

Expected:
* Cluster provisions successfully

Actual:
* The above error is seen when provisioning nodes

**Comment by kinarashah** [comment]
Issue is caused because the node template didn't have any cloud credential, confirmed with @bmdepesa works when cloud credential is present

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/14

This is working correctly when cloud credential is present.

**Comment by cyr-riv** [comment]
I reproduce the issue with rancher/rancher:v2.2.4 with HA setup even if my azure cloud credentials are present.

**Comment by acabrele** [comment]
I'm also getting this issue with 2.2.7 when creating a cluster from 

Error setting machine configuration from flags provided: azure driver requires the "azure-subscription-id" option.; Timeout waiting for ssh key

Sub id is set in both cloud credentials and the cluster configuration when azure is selected as the cloud provider.
