### ISSUE TITLE
Endpoints in rancher-monitoring don't update when cluster nodes change.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#18042]
The chart that drives rancher-monitoring creates endpoints with the cluster node addresses statically defined at monitoring activation time to monitor etcd, kube-scheduler, and kube-controller-manager services.

If you switch out the nodes (they change ip addresses) the endpoint objects don't get updated.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster with a node-driver
- Create a node pool for etcd/controlplane with 3 nodes
- Create a node pool for workers (1 node is fine)
- Enable monitoring at the cluster level (Tools -> Monitoring)
- Monitor etcd graphs (DB Size should have 3 nodes)
- Delete one of the etcd/controlplane nodes
- Wait for rancher to re-deploy the node (should end up with a different address)
- Notice that the etcd DB Size graph doesn't add the new node. 

**Other details that may be helpful:**
Etcd graphs can be viewed from the grafana icon on the cluster status page:
![image](https://user-images.githubusercontent.com/5324639/52674581-a3179480-2ee9-11e9-88c9-535e7045d2a7.png)

Static definiations can be seen by updating the cluster-monitoring chart deployed under the System project.

![image](https://user-images.githubusercontent.com/5324639/52674651-d6f2ba00-2ee9-11e9-9dad-62588dfc9391.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Component | Version
-- | --
Rancher | master
User Interface | v2.2.2
Helm | v2.10.0-rancher8
Machine | v0.15.0-rancher4-1

**Comment by jiaqiluo** [comment]
The bug fix is validated on master 2/21. 

The step is the same as the issue describes.

Result:
Etcd graphs update and show all etcd nodes
