### ISSUE TITLE
Ability to add a new Kubernetes version support without shipping a new Rancher release

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18041]
Today adding a new k8s version support into Rancher actually requires releasing Rancher. It happens because supported k8s versions are read by Rancher from github.com/rancher/types. And any changes to the types require Rancher re-compile.

We should think of a different model allowing to ship new k8s versions to existing Rancher releases. Similar to how it was done in Rancher 1.6 where k8s install specs got published using Rancher catalog.

**Comment by vincent99** [comment]
The downloaded info for new versions should include some sort of importance flag so that things like CVE releases can be shown more prominently in the UI compared to a regular patch releases.

**Comment by rbq** [comment]
@vincent99 I think it would make more sense to include information about bugs and vulnerabilities present in a certain version than communicating the ones it resolves.

a) An individual version is not (inherently) more important—unless you happen to run a vulnerable previous release. v1.13.1-rancher1 could be released to fix a CVE in v1.13.0-rancher1 and, according to your proposal, would therefore be tagged as important. Still, there would be no safe way for rancher to tell users running e.g. v1.11.2-rancher1-1 if they're affected or not, unless all patches are always backported and released at exactly the same time.
b) An issue might be uncovered without a fix being available. There could be a temporary workaround that admins should know about though.
c) There might be multiple versions that fix the same issue. If v1.13.0-rancher1-1 had a known CVE, upgrading to v1.13.0-rancher1-2, v1.13.1-rancher1-1 or v1.14.0-rancher1-1 might all fix the problem.

**Comment by vincent99** [comment]
Patches for security issues are generally released together by upstream for all supported k8s versions (and possibly backported further back by us).

We're not going to replicate the release notes of k8s releases in the UI, or try to indicate the importance of every upgrade. 

I just want some indicator that can be used for the usual "there's some update available you may or not care about" vs "there's a critical update available you SHOULD care about" for next time there's a major CVE.  A lot of people don't otherwise apply minor releases.; We don't even currently ship most of them, and once we start there being more frequent updates available is going to exacerbate update fatigue.

**Comment by jiaqiluo** [comment]
The feature is implemented by introducing a new setting and a new action 
```
v3/settings/rke-metadata-url - the branch and url to the metadata repo 
v3/kontainerdrivers          - refresh to fetch new metadata in Rancher 
```

It is tested by using testing Rancher images and forked `kontainer-driver-metadata` Github repo.

Steps:
- run Rancher-testing:v2.3.3
- in Rancher, change the value of `v3/settings/rke-metadata-url` to the forked `kontainer-driver-metadata` Github repo
- in Rancher, check the k8s list: v1.12.4-rancher1-1 (default), v1.13.1-rancher1-1(experimental)
- in kontainer-driver-metadata, add a new k8s minor version v1.12.10-rancher1-1
- in kontainer-driver-metadata, add a new k8s major version v1.16.0-rancher1-1
- generate new metadata and push to Github
- in Rancher, refresh `v3/kontainerdrivers`

Result:
- the k8s list reflects the changes, meaning it shows newly-added v1.12.10-rancher1-1 as default and v1.16.0-rancher1-1 as experimental
- also checked the v3/settings and see proper values in the follow filed
```
- ui-k8s-supported-versions-range 
- ui-k8s-default-version-range 
- k8s-version-to-images
- k8s-versions-current
- k8s-version
- k8s-version-to-service-options
```
- also tested upgrading existing clusters from the older versions to newly-added versions
