### ISSUE TITLE
Flannel doesn't work in master with k8s 1.13

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18053]
rancher/rancher:master 02/12

Steps:

1. Create a custom cluster
2. Select Flannel
3. Use default k8s version 1.13

Results:

Node is always in `Unavailable` state. It works well if we select k8s 1.12

rancher/rancher:master
![image](https://user-images.githubusercontent.com/21168270/52697082-8d6aa380-2fab-11e9-999a-f1fc20875f89.png)
![image](https://user-images.githubusercontent.com/21168270/52697095-a2dfcd80-2fab-11e9-90e3-46e3b020d451.png)
![image](https://user-images.githubusercontent.com/21168270/52697167-d4f12f80-2fab-11e9-9fde-dbd538a62265.png)

**Comment by superseb** [comment]
Can you check if this solves it:

```kubectl -n kube-system patch ds/kube-flannel --type=merge -p '{"spec":{"template":{"spec":{"tolerations":[{"key":"node-role.kubernetes.io/controlplane","effect":"NoSchedule","value":"true"},{"key":"node-role.kubernetes.io/etcd","effect":"NoExecute","value":"true"},{"key":"node.kubernetes.io/not-ready","effect":"NoSchedule","operator":"Exists"}]}}}}'```

If so, we'll need to review: https://github.com/rancher/rke/pull/1025

**Comment by loganhz** [comment]
@superseb Yes. You command resolves it!

**Comment by sowmyav27** [comment]
verified on rancher:master (02/13/2019)
Kubernetes version: v1.13.1
Network Provider: Flannel
