### ISSUE TITLE
Error Pulling image from Private Registry via Catalog App

### ISSUE THREAD

**Issue by BiggA94** [rancher/rancher#18057]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1.  Add private Catalog (Chartmuseum with absolute paths)
2.  Add private Docker registry in Registries for a Project
3.  Start a Catalog App

**Result:**
At first it tries to pull the Image:
>  pulling image "docker.example.com/image:latest"

> Failed to pull image  "docker.example.com/image:latest": rpc error: code = Unknown  desc = Error response from daemon: Get  https://docker.example.com/v2/image/manifests/latest:  unauthorized: authentication 

But if I start a new deployment in the same Project and namespace and I specify exactly the same Image ('docker.example.com/image:latest'), the Image can be pulled successfully.

**Other details that may be helpful:**
Registry domain and image name changed to examples.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.0-alpha6
- Installation option (single install/HA):
HA in GKE

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted/GKE

```
Rancher | v2.2.0-alpha6
User Interface | v2.2.2
Helm | v2.10.0-rancher8
Machine | v0.15.0-rancher4-1
```

**Comment by loganhz** [comment]
Please add imagePullSecrets into your deployment yaml of your catalog. 

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret
