### ISSUE TITLE
Should delete old fluentd/log-aggregator, secret when upgrade rancher server with a enable logging

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18054]
Rancher server version: v2.2.0-alpha6
Step to reproduce
1. enable logging in server 2.1.5
2. then the fluentd/log-agregator will deploy to cattle-logging namespace, secret cluster-config/project-config/sslconfig will add to cattle-logging namespace
3. Upgrade from 2.1.5 to v2.2.0-alpha6
4. the new fluentd app deployed but the old fluentd and secret still there

**Comment by loganhz** [comment]
@fyery-chen please validate it

**Comment by fyery-chen** [comment]
Reproduced:
* enable logging in server 2.1.5
* then the fluentd/log-agregator will deploy to cattle-logging namespace, secret cluster-config/project-config/sslconfig will add to cattle-logging namespace
* Upgrade from 2.1.5 to v2.2.0-alpha6
* the new fluentd app deployed but the old fluentd and secret still there

Check as the same steps:
enable logging in server 2.1.5
* then the fluentd/log-agregator will deploy to cattle-logging namespace, secret cluster-config/project-config/sslconfig will add to cattle-logging namespace
* Upgrade from 2.1.5 to master
* the new fluentd app deployed but the old fluentd and secret are not exist.

Result:
Delete old fluentd/log-aggregator, secret successfully.
