### ISSUE TITLE
As admin , other user's environment is not listed in "Your Environments" , but  have access to this environment from "Manage Environments" list.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1805]
Server version  -  v0.33.0-rc1

Have access control enabled using git hub with admin user say -a.

As user b who has been granted access to this server , create a environment - "test".

As admin user a ,  "test" environment ( even default environment of user b) is not listed in  "Your Environments" . But using "Manage Environment" view , I am able to get to this environment  using "switch to this environment".

Why are these environments not being listed in "Your Environments" for admin. If I add admin user explicitly as a member to this environment then I see this being listed in "Your Environments".

Admin user doesn't seem to need to be added as member to any environment to get access to it .
We expect all environments to be listed in "Your Environments" list?

**Comment by vincent99** [comment]
That's the point... The admin user is admin so they *can* see every environment, but they are also a user that doesn't care about everybody else's environments on a day to day basis.  So the drop down includes only ones they are a member of, but in the manage screen you can see or switch to any of them.

**Comment by sangeethah** [comment]
Closing as the behavior seen is as per design.
