### ISSUE TITLE
helm: workloads not getting correct labels after app upgrade

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#18068]
Rancher master: 2/13 

Create multi cluster app, using `docker-registry` with template version `1.4.3` in any project.
App `test-p-4zzgs` got created, and workloads had the correct label, 
```
"io.cattle.field/appId": "test-p-4zzgs"
```

Upgrade multi cluster app, to version `1.6.1`. 
App `test-p-4zzgs` gets upgraded correctly, but the new workload has no `"io.cattle.field/appId"` label.  

As a result, detail page for the app that shows workloads, ingresses in UI shows up empty.

**Comment by guangbochen** [comment]
@kinarashah this should be fixed in the https://github.com/rancher/helm/pull/16

For testing purpose:
1. Download the helm and tiller(darwin-amd64) binary build in [here](https://github.com/guangbochen/helm/releases), 
2. Rename it to `helm` and `tiller` respectively, then move them to your `/user/local/bin/` path
3. Run the rancher server and it will use the current build

**Comment by cjellick** [comment]
@dramich to validate

**Comment by cjellick** [comment]
@daxmc99 to validate

**Comment by daxmc99** [comment]
Steps taken to validate:

1. Created docker-registry (template version 1.4.3) from global via multi-cluster app page under tools. 
2. Observed deployment of the workload in the local/default project api
```	
workloadLabels": {
		• "app": "docker-registry",
		• "chart": "docker-registry-1.4.3",
		• "heritage": "Tiller",
		• "io.cattle.field/appId": "test2-p-7fvzs",
		• "release": "test2-p-7fvzs"
```
3. Upgrade the multi-cluster app from global/ multi-cluster app page to template version 1.6.1
4. Observed the workload in the local/default project api
```	
	"workloadLabels": {
			• "app": "docker-registry",
			• "chart": "docker-registry-1.6.1",
			• "heritage": "Tiller",
			• "io.cattle.field/appId": "test2-p-7fvzs",
			• "release": "test2-p-7fvzs"
}
```
5. Viewed the workload in catalogs apps of local/Default project. Workload was marked active. Service was also marked active.

**Comment by cjellick** [comment]
Validation looks good Dax
