### ISSUE TITLE
When updating cluster State does not change in UI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18061]
Version: Master 2.2 (2/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a DO cluster such as with default settings
- Once it is fully provisioned and ready, edit it and change something small such as the port range under advanced settings.

**Result:**
The State does not change from Active to Updating even though on the backend we can see the cluster is provisioning again and essentially updating. This may affect other providers as well.

**Comment by n313893254** [comment]
@davidnuzik Hi, I cannot reproduce the cluster state does not change from Active to Updating.

my steps:
1.  Create a DO cluster with default settings.
2. Edit it and change the port range.
3. Wait for about 1 min.

Also, I check the API, when the API change to updating, the UI change.

result:
![image](https://user-images.githubusercontent.com/18737885/52773522-1d751f80-3076-11e9-8c24-581ad8cf04ed.png)

**Comment by davidnuzik** [comment]
@n313893254 sorry I should have been more specific in the issue. I stayed on the Clusters page 
![image](https://user-images.githubusercontent.com/45179589/52803009-52fe1680-303e-11e9-9464-eeaa3ca9adc9.png)

After edit go straight back to /g/clusters page to see clusters. State did not change on that page for me. Possibly even a websocket issue or something now that I think about it more however I did not spot anything obvious when testing and watching browser console. I tried to repro again so I could record a short movie but there is a bug where you cannot edit clusters you get a TypeError: Invalid Version: undefined when editing RKE clusters: #18120

**Comment by cjellick** [comment]
is it possible this is a dupe of https://github.com/rancher/rancher/issues/17865 ?

**Comment by davidnuzik** [comment]
It's possible @cjellick I will retest as soon as possible once we have #18120 blocker resolved.

**Comment by davidnuzik** [comment]
Yes @cjellick this does appear to be a dupe of that issue. I am going to close this one in favor of #17865 which describes the issue better.
