### ISSUE TITLE
docker-machine provisions with outdated default for storage-driver in CentOS/RHEL

### ISSUE THREAD

**Issue by rajiteh** [rancher/rancher#18065]
**What kind of request is this (question/bug/enhancement/feature request):**

Enahancement

**Steps to reproduce (least amount of steps as possible):**

Provision a RHEL/CentOS node with rancher 

**Result:**

Dockerd is using devicemapper as the storage driver (set by a systemd drop-in `10-machine.conf`)

**Other details that may be helpful:**

When provisioning centos/rhel nodes with rancher + docker-machine, the default storage driver for dockerd is set to `devicemapper`. This is outdated and not recommended for production ready work loads. Upstream docker-machine had already switched over to `overlay2` as the default. See: https://github.com/docker/machine/pull/4560

**Environment information**
- Rancher 2.1.3

**Comment by Azaradel** [comment]
Hi!
I opened a pull request in rancher's docker-machine fork that changes the default storage driver for redhat to overlay2. Luckily I encountered first problems with the devicemapper on staging cluster

PR: https://github.com/rancher/machine/pull/75

**Comment by luthermonson** [comment]
Hi @Azaradel im going to close your PR and add this one which included the tests https://github.com/docker/machine/pull/4560/files (we dont run them today but want to) thanks for the submission and ill try and cherry pick your PR and add to it so you get credit but no promises that i dont screw that up :D

**Comment by luthermonson** [comment]
@sangeethah only merged into master for now.

**Comment by Oats87** [comment]
This is changing behavior for our existing users -- we should heavily document this if possible.

**Comment by luthermonson** [comment]
@catherineluse ^^

**Comment by soumyalj** [comment]
Tested with upgrade from v2.3.5 to master-head
1. Created a Rancher setup with version v2.3.5
2. Created a 3 node AWS cluster "Cluster1" (node driver) using RHEL 7.7 nodes(RHEL-7.7_HVM_GA-20190723-x86_64-1-Hourly2-GP2 (ami-03cfe750d5ea278f5)). 
3. Created a 3 node custom cluster "Cluster2" with RHEL 7.7 nodes 
4. For both Cluster1 and Cluster2
- The nodes had docker info `Storage Driver: devicemapper`
- Created few workloads and ran pre-upgrade test which succeeded
4. Upgrade Rancher server from v2.3.5 to master-head
5. After upgrade, added new nodes to "Cluster1" and "Cluster2" .
- The new nodes had `Storage Driver: overlay2`
- Created few workloads and ran post-upgrade test which succeeded
6. Created new cluster in the setup. 
- The nodes had `Storage Driver: overlay2`

**Comment by catherineluse** [comment]
@Oats87 Where should this be documented? our docs don't mention devicemapper, so I'm not sure where to capture the change to overlay2.
