### ISSUE TITLE
Update to app's creator's permissions does not get reflected during helm install

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#18077]
Rancher master Feb 13, also tried on 2.1.5
**Steps to reproduce**:
1. Create a user and add that user as a project-owner to some project
2. Login as this user and create grafana app; there are no errors in UI
but app creation fails with the following error:
```
2019/02/13 13:28:16 [ERROR] AppController p-9fprs/grafana-wmbnn [helm-controller] failed with : failed to install app grafana-wmbnn. Error: release grafana-wmbnn failed: podsecuritypolicies.extensions is forbidden: User "u-bskqn" cannot create resource "podsecuritypolicies" in API group "extensions" at the cluster scope
```
3. Login as admin and add this user to that project’s cluster as cluster-owner,

**Result**:
App creation still keeps failing with same error

**Expected**:
App creation should have succeeded now that the creator's roles are updated

**NOTE**: Creation of a new grafana app by this user works after step 3, once this user has the cluster-role too.
This affects multiclusterapp too, since users could launch a multiclusterapp with only "project-member" role, see this error and try to update Roles by passing "cluster-owner" role. But the actual app creation would still fail

**Comment by cjellick** [comment]
Side note: Why in the world is the grafana app creating pod security policies

**Comment by cjellick** [comment]
Pre-existing bug. not fixing in v2.2.0

**Comment by mrajashree** [comment]
Closing this as it will be tracked through https://github.com/rancher/rancher/issues/18088
cc @alena1108
