### ISSUE TITLE
Need additional environment variables for DataDog chart

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#18076]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
It looks like Rancher's version of the chart does not have some of the capabilities we need. 
For example, I need the ability to pass more env vars 
- name: DD_APM_NON_LOCAL_TRAFFIC 
  value: "true" 
 - name: DD_TAGS 
    value: 'kube_cluster:test-cluster' 
- name: DD_PROCESS_AGENT_ENABLED 
  value: "true" 

Also for the following env var, you have 
   - name: KUBERNETES 
      value: "yes" 
When it maybe should be 
   - name: KUBERNETES 
     value: "true" 

**Result:**

**Other details that may be helpful:**
It would also be good to make the default image the chart uses the latest one.  By default it's pulling a quite old version. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.6
- Installation option (single install/HA): Single

**Comment by guangbochen** [comment]
Hi @mattmattox, please deploy a new Datadog app using the latest version of 1.12.0 to verify, all of the `DD_APM_NON_LOCAL_TRAFFIC`, `DD_TAGS` and `DD_PROCESS_AGENT_ENABLED` are configurable via the UI form.
and for the question of 
```
name: KUBERNETES
value: "yes"
```
we can not change it to "true" as this is the original design from the Datadog and is not customizable, thanks.

**Comment by mattmattox** [comment]
I've gotten DataDog mostly working, but I need to edit the DataDog agent after install due to the chart still missing some capabilities. I'm listing those below as requested additions.

Need to add the following ENV Vars, I'm inputing the default values as I know them 
- name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL 
value: "false" 
- name: DD_LOGS_CONFIG_USE_PORT_443 
value: "false" 
- name: DD_LOGS_CONFIG_LOGS_DD_URL 
value: "" 
- name: DD_LOGS_CONFIG_LOGS_NO_SSL 
value: "false" 
- name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL 
value: "false" 

Need to be able to specify tolerances

Can we add the ability to add arbitrary ENV vars?

For logging, the DataDog docs say we need to mount the following volumes 
(...) 
volumeMounts: 
(...) 
- name: pointerdir 
mountPath: /opt/datadog-agent/run 
(...) 
volumes: 
(...) 
- hostPath: 
path: /opt/datadog-agent/run 
name: pointerdir 
(...) 

But the chart mounts the /var/lib/datadog-agent/logs path to /opt/datadog-agent/run 
/var/lib/datadog-agent/logs

**Comment by guangbochen** [comment]
Hi @mattmattox the catalog does allow the user to input custom values through `Edit as YAML`

you can check `Detailed Description` section of each Catalog App to find out what parameters are configurable, also you can reference the [doc here](https://github.com/helm/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set) of how to convert YAML values into dot formatted inputs:

and for your above mentioned values, u can add them as below:
```
datadog.env[0].name: "DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL"
datadog.env[0].value: "false"
datadog.env[1].name: "DD_LOGS_CONFIG_USE_PORT_443"
datadog.env[1].value: "false"
datadog.logsPointerHostPath: "/opt/datadog-agent/run"
datadog.tolerations[0].key: "key"
datadog.tolerations[0].operator: "Equal"
datadog.tolerations[0].value: "value"
datadog.tolerations[0].effect: "NoSchedule"
```

btw, from Rancher2.2.0 we will add support for real YAML file instead of using dot-formatted inputs.

**Comment by mattmattox** [comment]
I was able to confirm the fix worked.
Thank you @guangbochen for your help
