### ISSUE TITLE
Gray-out Create button on cloud credential creation modal until all required credentials are entered

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18079]
Version: Master 2.2 (2/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create any cloud credential.
- Notice that we can click the Create button even though we have not filled out required fields yet (keys, etc).

**Result:**
NOTE: This doesn't let us submit the form so it's not the end of the world, but we would prefer the button be grayed-out until we have entered any data in all required fields.

Screenshot shows that today we can have required fields empty but the Create button is still available.
![image](https://user-images.githubusercontent.com/45179589/52749981-1a136280-2fa8-11e9-8555-7a0024015760.png)

**Comment by vincent99** [comment]
:-1: This is not a pattern we use anywhere.  

If you can't submit until all the input is valid, then you need a completely different proactive mechanism to show which parts of the form are invalid in a very obvious way, because you can't just click and see what the errors are.

**Comment by davidnuzik** [comment]
Is it different from this below? I have not made a selection thus the button is grayed-out here.
_This issue isn't for validating_ just check if required fields are empty if empty then Create button grayed out. If full but with garbage then when user clicks create they get any expected error in UI if such an error/check exists.

![image](https://user-images.githubusercontent.com/45179589/52802129-88096980-303c-11e9-9274-2c83ab801962.png)

**Comment by westlywright** [comment]
The state's are different. The image you linked is the state when we have not selected a cloud credential. Its only checking the one field vs checking _n_ fields on the cloud credential config. 

After talking to Vince though I am going to change the UX and we'll always select the first item in the dropdown as our default cloud credential that way the user is never presented with this ux.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Confirmed issue.
When you create a cluster for the first time the modal automatically picks "Add New" button for you to create a cloud key.
The Create button is still available as it's not possible to gray this out if required fields are empty.

![screen shot 2019-02-20 at 4 07 22 pm](https://user-images.githubusercontent.com/45179589/53131336-c4036980-3529-11e9-83c9-ef9501cc5548.png)

If you have not filled out the required fields you will get an appropriate error message:
![image](https://user-images.githubusercontent.com/45179589/53131371-de3d4780-3529-11e9-9001-eb8ff9e024bf.png)

Smoke tested cloud keys / node templates / cluster creation to ensure there are no issues.
