### ISSUE TITLE
EC2 cloud credentials are missing optional Session Token field

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18085]
Version: Master 2.2 (2/13/19)
Also missing in older v2.0.77 UI (this used to be there).

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to create an EC2 cloud credential. There is no optional 3rd field to enter session token.

**Result:**
Missing optional Session Token field.

**Comment by westlywright** [comment]
@davidnuzik I don't think this is a bug, the UI never included the Session Token for EC2 instances. I don't think the machine driver takes the session token. Amazon EKS does take a session token but there was a specific update for only that cluster driver a while back. 

If it is required, we need to make an update to `https://localhost:8000/v3/schemas/amazonec2credentialconfig` first to add the fields then this would need to come back to me.

**Comment by davidnuzik** [comment]
@westlywright sorry about that you are correct. This was only ever an option for Amazon EKS, not EC2. I am closing this issue. My mistake.

EKS:
![image](https://user-images.githubusercontent.com/45179589/52757462-f9580680-2fc1-11e9-90e2-8de1c1506120.png)
