### ISSUE TITLE
Cloud Keys search is not working correctly

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18097]
Version: Master 2.2 (2/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Have several cloud keys
- Search for something that is not among any of the keys (name, date, etc)

**Result:**
![image](https://user-images.githubusercontent.com/45179589/52758774-ce23e600-2fc6-11e9-86a1-5ba8ba5fc8d2.png)

You will still get results when searching for something that is not seen on the page. It looks like it's searching the "created" long date in the API. We should only be searching for things we can actually see in the UI on this page such as the name and type.

**Comment by davidnuzik** [comment]
@westlywright looks like it's still searching long date in API

![image](https://user-images.githubusercontent.com/45179589/53133200-7b4eaf00-352f-11e9-964c-e137e99cef4e.png)
![image](https://user-images.githubusercontent.com/45179589/53133210-843f8080-352f-11e9-8bc7-881b29810ac1.png)

**Comment by westlywright** [comment]
@davidnuzik we shouldn't even be searching on the time field, its not a typical pattern and seems like it was included as a search field erroneously. Time is made human readible on the fly and not as a part of the model. Don't know if a big under taking to change this is really worth it when searching on time created isn't really useful.

**Comment by westlywright** [comment]
@davidnuzik can you retest, I am not seeing this anymore.

**Comment by davidnuzik** [comment]
@westlywright I can confirm; I am not seeing this anymore as well.

Version: Master 2.2 (2/25/19)
Confirmed issue. The problem is no longer occurring. When I search cloud credentials or other areas we are no longer searching the time/date in the API. Search is working as I would expect and I did not identify any issues.
