### ISSUE TITLE
The validation error when adding vSphere node template

### ISSUE THREAD

**Issue by zhangsean** [rancher/rancher#18099]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Start the latest rancher/rancher:master with docker run.
2. Set the password and login to dashboard.
3. Add an Cloud Key with type `VMware vSphere`, all filed are fulled.
4. Add an Node Template with type `vSphere`, select the Cloud Credentials with the upon Cloud Key, input something into Name filed, then just click `Add` button.

**Result:**
I got the validation error:
```
Validation failed in API: vmwarevsphereConfig password=NotNullable 422:
```
![image](https://user-images.githubusercontent.com/2536402/52761405-3c5fbb80-304e-11e9-8f1b-200e1a9b9fbe.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Thanks for the report.

Close in favor of https://github.com/rancher/rancher/issues/15879
