### ISSUE TITLE
Change how Cloud Keys are sorted by default

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18095]
Version: Master 2.2 (2/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Have several Cloud Keys. Notice the sorting order is by date.
- We should change this to sort by Name alphabetically and then by type so that keys are grouped by type.

**Result:**
This will group your keys by provider and then alphabetically by name. This will make it much easier for customers with many entries to find the relevant ones for the provider they want. If they have one provider then their keys are still sorted alphabetically.

**Comment by cjellick** [comment]
Marking this as bug-qa. Enhancements represent issues that improve or augment existing released functionality. This feature isn't released yet, so enhancement isnt the right label. I interpret this as a usability bug. Just mark all issues like this as bug-qa @davidnuzik.

**Comment by davidnuzik** [comment]
Gotcha, makes sense @cjellick will do

**Comment by davidnuzik** [comment]
@westlywright is it possible to make the groups stay in place when we sort by name/date? This way groups don't jump around as we sort by either?

Or make a new issue?

**Comment by westlywright** [comment]
That would break the sorting, when you're grouped and then you change the name sort first its sorts the groups then it sorts the content inside. You're talking about nested sorting which is probably possible but outside the scope of the ticket and 2.2 imo. Would probably require some discussion about design as its going to affect everything that uses these sortable tables.

**Comment by davidnuzik** [comment]
That makes sense thanks. I'll open a separate enhancement request for consideration in the future for the nested sorting.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/21/19)
Cloud keys are now sorted in groups. This makes it easier to keep track of them when you have many. Sorting is still functioning as expected.
![image](https://user-images.githubusercontent.com/45179589/53185798-f6aa7200-35bc-11e9-81ce-6e3599699a7b.png)
