### ISSUE TITLE
LoadBalancer logs

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#1809]
I'm not able to find the logs from the rancher loadbalancer in order to debug it.

**Comment by kaos** [comment]
Look for the Lb Agent container.. The round little button has a dropdown menu for the logs..

<img width="155" alt="screen shot 2015-08-17 at 13 20 01" src="https://cloud.githubusercontent.com/assets/72965/9303890/ca8d83fc-44e2-11e5-9f5b-0e3fd3982411.png">

<img width="1221" alt="screen shot 2015-08-17 at 13 21 27" src="https://cloud.githubusercontent.com/assets/72965/9303964/7e431128-44e3-11e5-9041-e771df0ddc50.png">

**Comment by kaos** [comment]
If you need more, there's always the `Execute Shell` option as well, where you can look at (and tweak, for testing purposes) the haproxy config, etc..

**Comment by deniseschannon** [comment]
The troubleshooting FAQs might help you find out how to debug a bit more in detail. It has instructions on how to look at your haproxy config.

http://docs.rancher.com/rancher/faqs/troubleshooting/

**Comment by deniseschannon** [comment]
@silviupanaite Please re-open if you need more logs or information for Load Balancers.

**Comment by mrproper** [comment]
I gave up using the rancher lb's until they're finished with the lb refactor
In the mean time i just created my own image which does this amongst other handy things:
https://hub.docker.com/r/nodeintegration/rancher-haproxy/
