### ISSUE TITLE
Description field does not work for cloud keys

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18098]
Version: Master 2.2 (2/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- When prompted to create a cloud key enter something in the description field.

**Result:**
If you look at the API there is no description option.
We should either remove it from the UI or add it to the backend so the UI can implement this.
Related to #17546

**Comment by westlywright** [comment]
@davidnuzik I think this should be available, seems useful. This ticket should be back end and when its added to the correct schema the UI will just work.

**Comment by kinarashah** [comment]
Description is now present as a part of cloud credential schema, I can see it under API but doesn't show up under UI - 
<img width="675" alt="screen shot 2019-02-23 at 4 25 39 pm" src="https://user-images.githubusercontent.com/16870565/53293382-bba86a00-3787-11e9-8643-3046b13b536a.png">

https://github.com/rancher/types/pull/710

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/25/19)
Confirmed issue (backend change). I can view a cloud credential in the UI API and edit and submit a request with a description string. This is not showing in the UI and will be addressed in the linked issue, #17546

**Comment by davidnuzik** [comment]
@kinarashah I just realized I might have closed prematurely, it's up to UI team to fix this issue right? When I edit an existing cloud credential and submit with a new string for description it does not show up in API UI. So is UI issue, yes? This issue should be closed because I can successfully submit edit request with string for description -- right?
