### ISSUE TITLE
Container state reports as "starting", when the container failed to start because of insufficient memory

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#181]
Version:
rancher/server      beta                54eb289064e5        3 days ago          510.5 MB

Tried to start  "rancher/server" container in a Host node with 512 MB using "Add Container" option in the Host object in the UI.
Container fails to start because of insufficient memory.

UI reports this container is to be in "Starting" state for about 30 minutes , after which it gets into "stopped" state.

Expected Behavior:
UI should be able to report the state of the container as being in "Stopped" state  as soon as the container fails to start because of insufficient memory.

Error seen in container logs:

OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000edcce000, 30572544, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 30572544 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /var/lib/cattle/hs_err_pid1.log

Container is reported as being in "Exited" state:

root@mydropnode2:~# docker ps -a
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS                         PORTS                                          NAMES
bf218999a2bf        rancher/server:latest           "/usr/share/cattle/c   27 minutes ago      Exited (1) 26 minutes ago                                                     14bb0b47-7763-4728-b8b5-46501e38bd56   
ca14269c6937        node:latest                     "node"                 57 minutes ago      Up 57 minutes                                                                 ce08eecc-e0dd-4f0a-9f57-ebc4a157eb1f   
021e26300178        ubuntu:14.04                    "/bin/bash"            About an hour ago   Up About an hour                                                              86bdeacb-cea3-49e1-8afe-7868b7798738   
4dfdec3cb068        rancher/agent-instance:v0.2.0   "/etc/init.d/agent-i   About an hour ago   Up About an hour               0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   d794117a-ee1c-4e82-b2ea-384e9abf22bf   
a56c7994fe08        rancher/agent:v0.5.2            "/run.sh run"          About an hour ago   Up About an hour                                                              rancher-agent                          
16ad1d70733b        rancher/agent:latest            "/run.sh state"        About an hour ago   Exited (0) About an hour ago                                                  rancher-agent-state                    
root@mydropnode2:~#

**Comment by will-chan** [comment]
obsolete.
