### ISSUE TITLE
Rancher server crash when deleting a cluster

### ISSUE THREAD

**Issue by fyery-chen** [rancher/rancher#18103]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Delete an existing GKE cluster

**Result:**
rancher server will crash

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master

**Comment by loganhz** [comment]
@thxCode Please validate it

**Comment by thxCode** [comment]
**Validated steps:**
- Create 2 GKE cluster
- Destroy one cluster

**Result:**
Rancher server doesn't crash

@loganhz   cc @fyery-chen
