### ISSUE TITLE
Limit project resources to 0

### ISSUE THREAD

**Issue by nheinemans** [rancher/rancher#18107]
What kind of request is this: Question
Steps to reproduce (least amount of steps as possible):

- Create new project with Persistent volume claims set to 0 for both project and namespace
- Create namespace in this project results in this error message:

Persistent Volume Claims limit is required.

**Result:**
Cannot create namespace

**Environment information**
- Rancher version: v2.1.6
- Installation option: HA

**Comment by loganhz** [comment]
Thanks for the report
It will be fixed in 2.2
Close in favor of https://github.com/rancher/rancher/issues/16368
