### ISSUE TITLE
Invalid catalog app version - version: null when version is a string

### ISSUE THREAD

**Issue by Amir-Abushanab** [rancher/rancher#18118]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Add the harbor chart to the Global Catalog https://github.com/goharbor/harbor-helm
Launch the harbor catalog in any cluster

**Result:**
Everything works as expected, except that every time you go into the deployed catalogs, the UI displays an error message `Invalid catalog app version in harbor - Invalid Version: null`

**Additional Information:**
This probably has to do with the fact that they are using a character string for the version number (`dev`)

**Environment information**
- Rancher version: v2.1.6, UI v2.1.19, Helm v2.10.0-rancher5, Machine v0.15.0-rancher1-1
- Installation option: single install

**Comment by cycgp** [comment]
Same problem. Anyone knows how to deal with this. The fake warning seems quite annoying...

**Comment by blevinson** [comment]
Can someone fix this please?

**Comment by bglee** [comment]
Is there a fix for this yet?

**Comment by ccc7574** [comment]
That make me cray!!! Have to click all the alert and can't find anywhere to disable it

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.3.3.**

- Used catalog url: ` https://github.com/loganhz/harbor-helm`
- Deploy harbor helm, version - dev
- Error is displayed on the UI
<img width="1501" alt="Screen Shot 2020-01-27 at 10 22 19 PM" src="https://user-images.githubusercontent.com/26032343/73240376-a5531d00-4153-11ea-8a74-16d97abb2979.png">

Verified on latest master - UI tag: latest2
- Used catalog url: ` https://github.com/loganhz/harbor-helm`
- Deploy harbor helm, version - dev
- No error is displayed on the UI/console
