### ISSUE TITLE
Update EKS regions (Mumbai, London, Paris)

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#18114]
**What kind of request is this (question/bug/enhancement/feature request):**
task

**Steps to reproduce (least amount of steps as possible):**

Amazon EKS Available in Mumbai, London, and Paris AWS Regions
Posted On: Feb 13, 2019

Amazon Elastic Container Service for Kubernetes (Amazon EKS) is now available in Asia Pacific (Mumbai), Europe (London), and Europe (Paris) AWS regions.

https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-eks-available-in-mumbai--london--and-paris-aws-regions/

**Comment by ChrisMcKee** [comment]
AWS Region Codes for the 3 regions 
* ap-south-1 - mumbai
* eu-west-2 - london
* eu-west-3 - paris 

_just adding as I was searching for eu-west-2 and found nothing_ 👍

**Comment by davidnuzik** [comment]
This was already carefully validated as part of https://github.com/rancher/rancher/issues/20992 as you can see in the comment this covered testing the newly added regions ap-south-1, eu-west-2, eu-west-3, etc. I reviewed both PR's again to make doubly sure I am not missing testing anything.

I have included the test results from that issue:

Version: master-head (6/26/19)

Validated new UI option to pick 1.13 k8s version for EKS, new regions, allowed instance type values, etc. Validated amazonElasticContainerServiceConfig. Smoke tested creating various EKS clusters including older k8s versions (make sure 1.12 creates 1.12, 1.11 creates 1.11, etc).
Validated that UI shows correct k8s version for the cluster and nodes.

HTTP looks good, API looks good, compare to AWS console looks good, all checks passed. I was not able to test all regions as our account does not have access to them all (cannot fully test those) but the PR looks good to me.

I also did some spot checks to ensure AMI id's are correct for each k8s version (for regions I have access to via aws console).

Regions:
![image](https://user-images.githubusercontent.com/45179589/60200377-dacd0c00-97fa-11e9-97af-ac91d14c390a.png)

Allowed values for instances too large to fit in screenshot but looks correct.

UI does not pick latest as default, but this is a separate issue tracked in #20759
