### ISSUE TITLE
With Docker 1.8, rancher agent containers are showing up in UI. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1811]
V0.32.0

When using Docker 1.8, rancher agent containers are showing up in UI. These used to be hidden. 

This issue is to track that we've fixed the change in v0.33.0+ and on fresh installs, these will no longer appear.

**Comment by aruneli** [comment]
Verified that Rancher agent containers don't show up anymore and it is hidden from UI.
