### ISSUE TITLE
Monitoring - Refactor project level

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#18115]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Problem:**
Based on https://github.com/rancher/rancher/issues/16932, we have addressed something that wasn't a bug. We shouldn't delete `project-level` monitoring if the user was monitoring a custom app.

**Expected:**
- Deploy `project-level` without enabling `cluster-level`
- Disable`cluster-level` could not shut down `project-level`.

**Comment by cjellick** [comment]
I see the UI PR isnt merged. Might make sense to hold off on testing until #18204 is to-test

**Comment by loganhz** [comment]
As the pods/containers cpu/memory metrics are from cluster level monitoring. So we cannot show the icon for pods/containers and Graph in Rancher UI if only project level monitoring is enabled. So it is expected.

The purpose of enabling project level monitoring only is that users will be able to collect custom metrics. Then users can jump to the grafana page (you can find it in catalog app page) to see the metrics.

Users can see cpu/memory/network io/disk io if they enable cluster level monitoring

**Comment by jiaqiluo** [comment]
The enhancement is validated on master 2/21 on the following clusters:
- DO	
- AKS	
- EKS
- GKE
