### ISSUE TITLE
Hard to replay API execution of "/v3/connect/config"  with X-Tunnel-Params for troubleshooting 

### ISSUE THREAD

**Issue by ukinau** [rancher/rancher#18112]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Other details that may be helpful:**
We observed some situation which cluster provisioning won't finish with message of "waiting to register with Kubernetes" and node-agent continue on printing "waiting for node to register" every 2 sec.   This is happened probably some mis-configuration or some bugs.

But in this case, we want to reply "/v3/connect/config" with X-Tunnel-Params header actually node-agent specified but currently node-agent only print Token and Tunnel Params won't appear anywhere in log even if debug option is true.

We can actually build up json with environment variable and encode that as base64 but it's very bothersome so I think we should print X-Tunnel-Params in log for troubleshooting purpose

**Comment by superseb** [comment]
For debugging I have made https://gist.github.com/superseb/117efe9faaa6655c7483e92209033c6d and https://gist.github.com/superseb/d73fcdae7e64a8e978b06695071ebf6e, I agree debug logging can contain better information in this case.

We should consider to mask certain parts of information before just putting everything in the log.

**Comment by ukinau** [comment]
After I get reviewed on "Print X-Tunnel-Params value in addition to Token #18113" from @alena1108 , I changed the mind about it, and also as she commented on PR, I'm gonna change the logging logic for Token so that Agent can just show first / last 4 characters
