### ISSUE TITLE
Cannot update valuesYaml field for catalog app

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18111]
rancher/rancher:master

1. Deploy a catalog app
2. Click view API
3. Click upgrade action

Result:

There is no `valuesYaml` field in the params

![image](https://user-images.githubusercontent.com/21168270/52783611-64bada80-308d-11e9-8fb6-6ffd3063c887.png)

**Comment by guangbochen** [comment]
**Validation Steps:**

1. Deploy an app e.g like `docker-registry` v1.6.1 from the library catalog with default configurations
2. after installed click `View in API` to upgrade the app with the following config
```
replicaCount: 2
image:
  repository: registry
  tag: 2.7
```
3. ensure both image tag and replicas are updated correctly.
![image](https://user-images.githubusercontent.com/4569037/52832522-d8072f80-3113-11e9-9d2d-e03678e134f4.png)

**Comment by loganhz** [comment]
Verified in master 02/15

Now I can see the valuesYaml field in upgrade param.

1. Deploy a catalog app with yaml in edit yaml mode
2. Upgrade the catalog by changing the yaml

Now I can see the changed yaml applied to the catalog
