### ISSUE TITLE
Text fields should have helper text remain gray or blue when click in box

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18125]
Version: Master 2.2 (2/14/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Use light theme. Create a cluster. Notice that when focus goes into the Cluster Name box the helper text is a black color now. This is not how this used to work a few weeks ago.

**Result:**
Other text boxes with helper text in them are like this too.
This is confusing to the user because it looks like text is already in this field when we start editing it.

Expected:
![image](https://user-images.githubusercontent.com/45179589/52815508-13debe00-305c-11e9-96be-3ccab0ef88e4.png)

Actual:
![image](https://user-images.githubusercontent.com/45179589/52815518-19d49f00-305c-11e9-96d5-5b80e08d8033.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/2678

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/26/19)
Confirmed issue. Helper text in text boxes is now the light blue color again when you select the box to start typing:

Some examples:
![image](https://user-images.githubusercontent.com/45179589/53441711-a1a79b00-39c4-11e9-85ea-cd9616b263cb.png)
![image](https://user-images.githubusercontent.com/45179589/53441751-b5eb9800-39c4-11e9-903a-7965446e234a.png)
