### ISSUE TITLE
Unable to edit RKE clusters

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18120]
Version: Master 2.2 (2/14/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster such as DO RKE, EC2 RKE, Custom RKE, etc.
- Edit it

**Result:**
Browser console reports a TypeError: Invalid Version: undefined
Form is mostly all empty fields

**Other details that may be helpful:**
Issue was not occurring yesterday afternoon 2/13/19.
Tested with empty browser cache and is reproducible.
This issue did NOT happen when testing GKE. I imagine only RKE providers effected.

**Comment by westlywright** [comment]
Upon further investigation this doesn't look like a UI issue to me as the `/v3/schemas/rancherKubernetesEngineConfig` has changed completely. 

the new config looks like 
```
{
   "baseType":"schema",
   "id":"rancherKubernetesEngineConfig",
   "links":{
      "self":"…/v3/schemas/rancherKubernetesEngineConfig"
   },
   "pluralName":"rancherKubernetesEngineConfigs",
   "resourceFields":{
      "configFilePath":{
         "create":true,
         "default":"",
         "description":"the path to the config file",
         "dynamicField":true,
         "type":"string",
         "update":true
      },
      "driverName":{
         "create":true,
         "default":"rancherkubernetesengine",
         "dynamicField":true,
         "type":"string",
         "update":true
      }
   },
   "type":"schema",
   "version":{
      "group":"management.cattle.io",
      "path":"/v3",
      "version":"v3"
   }
}
```

This looks incorrect and I will update the bug more when i have more info.

**Comment by westlywright** [comment]
reassigning and removing myself as this isn't a UI issue.

**Comment by cjellick** [comment]
Note, you need a fresh rancher. Would still be broke if you upgraded from an old rancher

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/14/19) ImageID: 0fbe8118f412
Confirmed fixed. I successfully brought up a couple of RKE clusters (DO and EC2), edited and had no issues doing this and all my data is there, I then saved and successfully updated my cluster.
