### ISSUE TITLE
UI should display the states of backup objects based on conditions

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#18133]
master 15/02

Backups are performed in two phases:
- Backup object is created when the cluster action is triggered or the controller creates a new backup based on the creation interval. Once completed the `Created` condition is set to true.
- Backup procedure is executed by the controller. If successful, the condition `Completed` is set to true.

The UI (and alerts ?) should reflect the backup status based on those conditions.

**Comment by moelsayed** [comment]
Small backend fix needed for this is already in #18134

**Comment by alena1108** [comment]
@moelsayed there should be a state filed UI can work off. State is an aggregation of the conditions. Lets make sure state doesn't show "active" till the snapshot is ready, and after that is confirmed, the UI can work off that

**Comment by cjellick** [comment]
@moelsayed confirm @alena1108 's above statement, then assign over to @westlywright and add area/ui label

**Comment by moelsayed** [comment]
I believe the UI changes are already in. CC @westlywright

**Comment by westlywright** [comment]
The state badge was added and merged a couple days ago.

**Comment by soumyalj** [comment]
@moelsayed : Can you please provide different steps we need to check for w.r.t backup/restore. 
I have observed "Active" and "Activating" state so far.

**Comment by alena1108** [comment]
@soumyalj those are the 2 states supported for now. The Error state will be implemented post 2.2 as a part of https://github.com/rancher/rancher/issues/18465

**Comment by soumyalj** [comment]
Tested with master build from Feb 28 and March 1. 
The states "Active" and "Activating" are observed for etcd backup objects.
