### ISSUE TITLE
Cannot add answer override for catalog app which doesn't have questions.yaml

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18132]
rancher/rancher:master 02/14

Steps to reproduce

1. Enable Helm Incubator
2. Launch an app from Helm Incubator
3. Click the `Add Override` button in `Answer Overrides` section

Results:

User cannot add any override as there is no question in this catalog
 
![image](https://user-images.githubusercontent.com/21168270/52823736-fb6cb300-30f0-11e9-95a3-009a06a97d00.png)

**Comment by davidnuzik** [comment]
I think this is not working correctly:
When you create a MC app that does not have questions.yaml you can still create your own answers and you can overwrites those answers now:

![image](https://user-images.githubusercontent.com/45179589/53366382-aa369d80-3900-11e9-91c0-ea241d251825.png)

![image](https://user-images.githubusercontent.com/45179589/53366486-f1249300-3900-11e9-8e89-ede5b878af4f.png)

Why are we sending two answers? Shouldn't we overwrite answer number 0 so we just send answer 0 with foo: tacos ?

When I submit I do indeed see in API two answers:
```
answers": [ 2 items
{
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"foo": "bar"
}
},
{
"clusterId": null,
"projectId": "c-g5ktw:p-z7r8t",
"type": "/v3/schemas/answer",
"values": {
"foo": "tacos"
}
}
```

**Comment by davidnuzik** [comment]
Re-opening; pretty sure this is not expected behavior. Otherwise please let me know if I made a mistake in my testing. See the first screenshot. There are no answers in helm incubator therefor in UI I must make one and then I can override mine (which seems a little odd). Is this just a misunderstanding? A separate bug? Thank you.

**Comment by davidnuzik** [comment]
Assigned back to me -- there was a misunderstanding around how answer overrides work -- what I am seeing in the HTTP / API is actually correct.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/25/19)
When you create a MC app that does not have questions.yaml you can still create your own answers and you can overwrite those answers now:

![image](https://user-images.githubusercontent.com/45179589/53366382-aa369d80-3900-11e9-91c0-ea241d251825.png)

HTTP:
![image](https://user-images.githubusercontent.com/45179589/53366486-f1249300-3900-11e9-8e89-ede5b878af4f.png)

API:
```
answers": [ 2 items
{
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"foo": "bar"
}
},
{
"clusterId": null,
"projectId": "c-g5ktw:p-z7r8t",
"type": "/v3/schemas/answer",
"values": {
"foo": "tacos"
}
}
```

You can also just fill in the question as a plain text box assuming you have not created any of your own answers already:
![image](https://user-images.githubusercontent.com/45179589/53368726-be7d9900-3906-11e9-89ee-45db8b22f9d3.png)

HTTP:
![image](https://user-images.githubusercontent.com/45179589/53368709-b3c30400-3906-11e9-9525-9691b721255f.png)

API:
```
answers": [ 2 items
{
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer"
},
{
"clusterId": null,
"projectId": "c-g5ktw:p-z7r8t",
"type": "/v3/schemas/answer",
"values": {
"my2ndquestion": "my2ndanswer",
"my3rdquestion": "my3rdanswer",
"myquestion": "myanswer"
}
}
```
