### ISSUE TITLE
Admin user gets logged in to the the last default environment that was created for other users.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1814]
Server version - V0.33.0-rc1
Set up - Rancher server with LDAP auth enabled.
Log in as any user (who does not have access to any existing environments) - say "test1".
This results in a default environment created for this user.

Log in as admin user. We get automatically get logged in to Default environment of "test1".

**Comment by vincent99** [comment]
I think this is a result of setting the defaultProjectId userPreference failing (@hibooboo2).  So the default isn't set or is a project that isn't available, and the UI just picks one, and LDAP/admin/etc has nothing directly to do with it.

![image](https://cloud.githubusercontent.com/assets/753917/9342556/58bc9838-45b1-11e5-9445-194ddf6ba131.png)

**Comment by hibooboo2** [comment]
Unable to duplicate on master. Can you try and duplicate it again @sangeethah

**Comment by sangeethah** [comment]
This issue is also reproducible using local auth enabled set up.

Server version - V0.37.0-rc1
Set up - Rancher server with local auth enabled.
Log in as any user (who does not have access to any existing environments) - say "test1".
This results in a default environment created for this user.
Log out.
Log in as admin user. We get automatically get logged in to Default environment of "test1".

**Comment by hibooboo2** [comment]
Using master unable to replicate given steps to reproduce.

**Comment by deniseschannon** [comment]
Just reproduced on v0.47.0-rc2.

**Comment by tfiduccia** [comment]
Version - master 1/29
Verified fixed
