### ISSUE TITLE
Monitoring - Disable cluster-level Monitoring in one cluster will affect others

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#18146]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create 2 clusters
- Enable Monitoring for them
- Disable one cluster Monitoring

**Result:**
The `cluster-monitoring` App of another cluster has been dropped, but this cluster is still `enable monitoring`. 

**Expect:**
Withdrew the `cluster-level` monitoring in one cluster should not affect others.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master
- Installation option (single install/HA): single

**Comment by jiaqiluo** [comment]
The bug fix is validated on master 2/15. The steps are the same as the issue provides.
Result:
Disabling the cluster monitoring of cluster A does not affect the cluster monitoring of cluster B.
