### ISSUE TITLE
Mark deleted containers as deleted

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1815]
In our initial implementation of native docker integration, we made the decision that if rancher-agent was down and containers got deleted, when rancher agent came back up, we would not mark those containers as deleted in rancher. Instead, we marked them as stopped.

This confuses users. @ibuildthecloud referenced some specific companies/users that were confused by it.

We want to change the behavior so that rancher marks such containers as deleted.

**Comment by cjellick** [comment]
In our initial implementation of native docker integration, we made the decision that if rancher-agent was down and containers got deleted, when rancher agent came back up, we would not mark those containers as deleted in rancher. Instead, we marked them as stopped.

This confuses users. @ibuildthecloud referenced some specific companies/users that were confused by it.

We will change this behavior so that rancher marks such containers as deleted.

**Comment by sangeethah** [comment]
Tested with server version - v0.34.0-rc3

container1 in "stopped" state
container2 in "running" state.

From host:
stop rancher agent.
delete container1
delete container 2.

start rancher agent,

When host gets to "active" , state both "container1" and "container2" get deleted and purged in rancher-server.
