### ISSUE TITLE
Outer ring display wrong position when change page size and wait value change 

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#18158]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**
1. Spinning up a GKE cluster.
2. Enable monitoring.
3. After monitoring ready, Change page size and deploy a test workload in another window.

**Result:**

![image](https://user-images.githubusercontent.com/18737885/56011530-9f9e5f00-5d1a-11e9-8d9f-fe394d5e47cb.png)

![image](https://user-images.githubusercontent.com/18737885/56016164-f95c5480-5d2d-11e9-9201-566131ecc1ca.png)

**Other details that may be helpful:**

master (4/12/2019)

**Comment by vincent99** [comment]
This is probably related to zooming...

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19102
