### ISSUE TITLE
命名空间无法删除

### ISSUE THREAD

**Issue by libao2235** [rancher/rancher#18150]
命名空间无法删除

![image](https://user-images.githubusercontent.com/12504429/52830765-12210300-310d-11e9-809c-54e51118e663.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.6` UI: `v2.1.19` |
|Route|`authenticated.project.ns.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup, please? (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Close as there is no reproduce steps
