### ISSUE TITLE
UI - MultiCluser App - Member details not displayed correctly in upgrade view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18152]
Rancher server version - Build from master - Feb 14

Steps to reproduce the problem:
Create a standard user - test1.
As admin user, Create a Multi cluster app with targets as projects from 2 different cluster and add "test1" as owner.

Edit the  Multi cluster app. 
Notice that the member details are not displayed correctly.

<img width="1255" alt="screen shot 2019-02-14 at 8 05 52 pm" src="https://user-images.githubusercontent.com/4266958/52833905-fcbbc280-3093-11e9-85c4-4e6656c453aa.png">

Name should not be the principal id .It should be the user name.
Memeber Type should not be empty.
Acces type should be preselected to the right value.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Confirmed fixed. I tested a few times and could not reproduce each time.
I did spot an issue that when I am creating a Global DNS Entry this issue will occasionally pop-up so I opened a separate issue to track this: #18278 Global DNS Provider was tested as well and it looks good.

I smoke tested this issue and performed some regression testing as well around RBAC with MCapp and ensured this is working as expected per our test plan in this area. The HTTP/API looks good.
