### ISSUE TITLE
Kontainer-Engine - Upgrade rancher-server the existing EKS cluster displays an error message

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#18162]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
old server version: 2.1.5
new server version: master

- Start an old version server
- Create an EKS cluster
- Upgrade rancher server to `rancher/rancher:master`

**Result:**
Rancher server will show an error msg

![image](https://user-images.githubusercontent.com/3394724/52843523-5926ec80-313d-11e9-88c8-5b36abd83f9c.png)

**Other details that may be helpful:**
- Error log from rancher server
```
2019/02/15 08:16:47 [INFO] Starting post-check
2019/02/15 08:16:47 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2019/02/15 08:16:47 [ERROR] ClusterController c-7m45b [cluster-provisioner-controller] failed with : error getting cluster: ResourceNotFoundException: No cluster found for name: eks2.
	status code: 404, request id: 0985512e-30fa-11e9-9a1a-5b053df9f214
2019/02/15 08:16:52 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10270
2019/02/15 08:16:52 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2019/02/15 08:16:57 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10534
2019/02/15 08:16:57 [INFO] Starting post-check
```
- The cluster is working
![image](https://user-images.githubusercontent.com/3394724/52843901-5d9fd500-313e-11e9-98d2-1193e97b9070.png)
- Cluster CRD conditions info
![image](https://user-images.githubusercontent.com/3394724/52844036-a3f53400-313e-11e9-9ec5-e31a53df9bbf.png)

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher:v2.2.0-rc2

steps:
* Start an old version server v2.1.5
* Create an EKS cluster
* Upgrade rancher server to v2.2.0-rc2

results:
The EKS cluster still works after the upgrade and the error message in the issue does not show up.
