### ISSUE TITLE
Kontainer-Engine - Upgrade rancher-server the existing AKS cluster displays an error message

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#18165]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
old server version: 2.1.5
new server version: master

- Start an old version server
- Create an AKS cluster
- Upgrade rancher server to `rancher/rancher:master`

**Result:**
Rancher server will show an error msg

![image](https://user-images.githubusercontent.com/3394724/52850188-db1f1180-314d-11e9-8023-c7c0452d3800.png)

**Other details that may be helpful:**
- Error log from rancher server
```
2019/02/15 10:09:05 [INFO] Provisioning cluster [c-4j6hr]
2019/02/15 10:09:05 [INFO] Updating cluster [c-4j6hr]
2019/02/15 10:09:10 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10834
2019/02/15 10:09:11 [INFO] kontainerdriver azurekubernetesservice stopped
2019/02/15 10:09:11 [ERROR] ClusterController c-4j6hr [cluster-provisioner-controller] failed with : containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="A new agent pool was introduced. Adding agent pools to an existing cluster is not allowed at this time." Target="agentPoolProfiles"
2019/02/15 10:09:16 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10176
2019/02/15 10:09:16 [INFO] kontainerdriver azurekubernetesservice stopped
2019/02/15 10:09:21 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10909
2019/02/15 10:09:21 [INFO] kontainerdriver azurekubernetesservice stopped
2019/02/15 10:11:21 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10462
2019/02/15 10:11:21 [INFO] kontainerdriver azurekubernetesservice stopped
2019/02/15 10:11:21 [INFO] Provisioning cluster [c-4j6hr]
2019/02/15 10:11:21 [INFO] Updating cluster [c-4j6hr]
```
- The cluster is working
![image](https://user-images.githubusercontent.com/3394724/52850203-e2deb600-314d-11e9-887d-889ee6a756f9.png)

- Cluster CRD conditions info
![image](https://user-images.githubusercontent.com/3394724/52850260-03a70b80-314e-11e9-941e-91c2ba075367.png)

**Comment by loganhz** [comment]
@fyery-chen Please validate it

**Comment by fyery-chen** [comment]
Reproduced:
Install rancher of version v2.1.5
Launch an AKS cluster from rancher
Upgrade rancher server to version master
Wait for updating of aks cluster

Expected Result:
No error logs above

Actual Result:
No error logs

Validated:
OK
