### ISSUE TITLE
Cannot see Cluster/Project name in alert message

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18160]
rancher/rancher:master 02/14

Steps:

1.  Enable monitoring
2. Add a rule based on metrics
3. Trigger the alert

Results:
There is no cluster/project name in alert message
Users can only see the cluster id and project id for it.

![image](https://user-images.githubusercontent.com/21168270/52842326-b15bef80-3139-11e9-8224-257dea47399d.png)

**Comment by rootwuj** [comment]
Version: master 2.2 (2/20/19) Image ID: 7c0a59c18460
This version can see the cluster/project name (ID)
Confirmed fixed.
