### ISSUE TITLE
Rancher 2.2 Alpha 6 -  prometheus-cluster-monitoring-nginx keeps updating

### ISSUE THREAD

**Issue by jbroq** [rancher/rancher#18166]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enable cluster level monitoring with default option
Click on the etcd metrics of the cluster

**Result:**
you get a popup with
```
query series failed, query range failed, Get http://prometheus-operated.cattle-prometheus.svc.cluster.local:9090/api/v1/query_range?end=2019-02-15T11%3A00%3A23.541030956Z&query=sum%28etcd_debugging_mvcc_db_total_size_in_bytes%29+by+%28instance%29&start=2019-02-15T10%3A00%3A23.541030956Z&step=60.000: dial tcp: i/o timeout, expression: sum(etcd_debugging_mvcc_db_total_size_in_bytes) by (instance)
```
Pod: prometheus-cluster-monitoring-nginx
Container image : nginx:1.15.2 keeps updating and failing with error message 
```
host not found in upstream "prometheus-operated" in /nginx/nginx.conf:35
nginx: [emerg] host not found in upstream "prometheus-operated" in /nginx/nginx.conf:35
```

**Other details that may be helpful:**
Centos 7.6 VMs up to date

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-alpha6
- Installation option (single install/HA):single install
No persistent storage

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMware : 3 masters, 3 nodes, 2CPU/4GB/20GB HDD each
- Kubernetes version (use `kubectl version`): 1.13.1-Rancher

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
Thanks for your help

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/18104
Similar issue

**Comment by thxCode** [comment]
I have did some cross-validations, but I am not an expert in this area.:

| `cat /etc/centos-release` | `uname -r` | `sudo docker version` | can cluster-level Monitoring work now? |
| --- | --- | --- | --- |
| CentOS Linux release 7.6.1810 (Core) | 3.10.0-957.1.3.el7.x86_64 | 17.03.2-ce | yes |
| CentOS Linux release 7.6.1810 (Core) | 3.10.0-957.1.3.el7.x86_64 | 18.06.0-ce | no |
| CentOS Linux release 7.6.1810 (Core) | 3.10.0-957.5.1.el7.x86_64 | 17.03.2-ce | no |
| CentOS Linux release 7.6.1810 (Core) | 3.10.0-957.5.1.el7.x86_64 | 18.06.0-ce | no |

@jbroq what is the `uname -r` of your `CentOS 7.6` worker node? At same time, if you really want CentOS, can you follow [the requirements of rancher](https://rancher.com/docs/rancher/v2.x/en/installation/requirements/) to try `CentOS 7.5` with `Docker 17.03.2`?

**Comment by thxCode** [comment]
I create https://github.com/rancher/system-charts/pull/16 to embed the Nginx into Prometheus Pod to remove the checking for `prometheus-operated.cattle-prometheus` in cluster-level Monitoring. @jbroq , I have tested with the followed env, it is fine.

```
[centos@ip-172-31-10-131 ~]$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
[centos@ip-172-31-10-131 ~]$ uname -r
3.10.0-957.5.1.el7.x86_64
[centos@ip-172-31-10-131 ~]$ sudo docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

I think you can try again after it merged.

**Comment by jbroq** [comment]
Thanks all for you share and your effort.
I will have a look at it this coming week.

**Comment by jbroq** [comment]
In 2.2.0-rc2 the following error message has disappeared : 
```
host not found in upstream "prometheus-operated" in /nginx/nginx.conf:35
nginx: [emerg] host not found in upstream "prometheus-operated" in /nginx/nginx.conf:35
```

yet the popup is still present : 
```
query series failed, query range failed, Get http://prometheus-operated.cattle-prometheus:9090/api/v1/query_range?end=2019-02-27T08%3A47%3A46.442214178Z&query=sum%28rate%28node_network_transmit_packets_total%7Bdevice%21~%22lo%7Cveth.%2A%7Cdocker.%2A%7Cflannel.%2A%7Ccali.%2A%7Ccbr.%2A%22%7D%5B5m%5D%29%29+by+%28instance%29&start=2019-02-27T07%3A47%3A46.442214178Z&step=60.000: dial tcp 10.42.5.6:9090: i/o timeout, expression: sum(rate(node_network_transmit_packets_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m])) by (instance)
```
I will create a new ticket pointing to rc2

**Comment by thxCode** [comment]
@jbroq , I always debug the `cluster-level` Monitoring as the following steps, I hope you can try and report them in your new ticket.

1. Enabling `cluster-level` Monitoring and wait 5-10 mins;
2. Going to `System Project` and check there are any unavailable workloads of `cattle-prometheus Namespace`;
3. Checking there are any error/warning logs of `prometheus-agent Container` in `cattle-prometheus/prometheus-cluster-monitoring Pod`;
4. Launching kubectl from Rancher UI and check the Endpoints of `prometheus-operated Service` via `kubectl -n cattle-prometheus get endpoints prometheus-operated`;
5. Accessing the Prometheus web UI from `cluster-monitoring App` of `Catalog Apps` and check there are any failure targets from the `Status -(drop down)-> Targets menu`.

Step 1: give enougth time for Kubernetes deployment.
Step 2: make sure all Monitoring workloads working.
Step 3: `rancher/prometheus-auth` is the key component for separating Cluster and Project in rancher Monitoring.
Step4: Prometheus Operator will help us to deploy Prometheus as a StatefulSet workload which related to a Headless Service named `prometheus-operated`, this Service is the communication bridge for other components and `cluster-level` Prometheus.
Step5: Prometheus will report the scraping result in Targets page, it is useful for knowing our scraping configuration working or not.
