### ISSUE TITLE
publish and use rancher image for the "reach k8s without rancher feature"

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#18169]
image is currently coming from erik's repo need to build, deploy, and update it

**Comment by cjellick** [comment]
image is rancher/kube-api-auth:v0.1.1

**Comment by cjellick** [comment]
IT shows up as a deployment in the user's cluster

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/21

Cluster auth is correctly using `"authImage": "rancher/kube-api-auth:v0.1.1"`
