### ISSUE TITLE
Backport: docker 18.09 and 18.06 in UI 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18176]
Backport https://github.com/rancher/rancher/issues/18171

**Comment by alena1108** [comment]
The fix is available in rancher versions >= `v2.1.7-rc2`

**Comment by davidnuzik** [comment]
Version: v2.1.7-rc2 (Pulled 2/21/19, ImageID: fcf6df771928)
Confirmed that https://releases.rancher.com/install-docker/18.09.sh is the default Docker Install URL (Recommended) and that 1809 and 1806 work as well. Http looks good. Validate that correct version of docker is actually deployed.
![image](https://user-images.githubusercontent.com/45179589/53198703-4a778400-35da-11e9-947b-b560011ac0d2.png)

Validate that when we choose to only install supported versions of docker (Advanced cluster options) that both 1806 and 1809 still work (and are thus supported on backend).
![image](https://user-images.githubusercontent.com/45179589/53198472-bc030280-35d9-11e9-98dc-1853549c2840.png)
(This is ignoreDockerVersion: false)

Smoke test each cluster. One with 1806 docker and one with 1809 (Recommended). Briefly smoke test the general UI (general v2.1.7 sanity checks)
