### ISSUE TITLE
docker 18.09 in UI

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#18171]

**Comment by alena1108** [comment]
Per @deniseschannon, we should also add 18.06

**Comment by cjellick** [comment]
18.06 should be in already

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/19/19)
Confirmed issue. Docker 18.09 is now the Recommended (default) option when creating an RKE cluster. Both 18.06 and 18.09 are listed. Validated http (nodetemplate engineInstallURL, etc) / ui. Validated that when we pick 18.06 or 18.09 these are actually deployed to the nodes (18.06.2-ce build 6d37f41 & 18.09.2 build 6247962 at time of testing). Other versions were already validated in another issue.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/21/19)
Amended testing:
Include testing 18.06 and 18.09 with cluster option set to only allow supported Docker versions. Confirm both these are now supported and work without issue with this setting enabled. I tested with DigitalOcean RKE.
