### ISSUE TITLE
Add more fixes to multi cluster app

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#18189]
Based on review comments `https://github.com/rancher/rancher/pull/18144`, following things need to be done, 
- [x] Move namespace creation to user controller 
- [x] Avoid using cluster contexts in management controller, add data/conditions if required
- [ ] Use timestamp on app and not multi cluster app to figure out if interval has passed 
- [ ]  replace interval map with TTL

**Comment by alena1108** [comment]
Moving out of 2.2 as this is mostly covers backend improvements that are not fixing any bugs/issues.
