### ISSUE TITLE
On an upgraded Rancher setup, Edit Or Add Node Template throws error

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18194]
**What kind of request is this:** bug

**Steps to reproduce (least amount of steps as possible):**
Scenario#1
1. On rancher:v2.1.6 - create node templates, and a cluster.
2. Upgrade rancher to rancher:master.
3. Login to Rancher. Select 'Node Templates'.
4. Select a template and click on 'Edit Template'.
5. User is prompted to select 'Cloud Credentials'.
6. Add one/Select existing.
7. Click on 'Create'

**Expected Result:**
User must be able to navigate to the next page after entering the 'Cloud Credentials'.

**Actual Result:**
Error `502: null` is displayed on the UI.

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.1.6 to master
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Amazon
- Kubernetes version (use `kubectl version`):

```
v1.13.1
```

<img width="905" alt="screen shot 2019-02-15 at 3 49 35 pm" src="https://user-images.githubusercontent.com/26032343/52890875-039e1000-313c-11e9-98d3-5c0bd15a1be8.png">

<img width="680" alt="screen shot 2019-02-15 at 3 49 47 pm" src="https://user-images.githubusercontent.com/26032343/52890906-2af4dd00-313c-11e9-9606-c14329fe1aa7.png">

Scenario#2
1. On rancher:v2.1.6 - create node templates, and a cluster.
2. Upgrade rancher to rancher:master.
3. Select 'Node Templates'. Click 'Add Template'.
4. User is prompted to select 'Cloud Credentials'.
5. Add one/Select existing.
6. Click on 'Create'

**Actual Result:**
Error `502: null` is displayed on the UI.

**Comment by sowmyav27** [comment]
Attaching a snapshot of the Rancher logs:

<img width="1607" alt="screen shot 2019-02-15 at 4 17 57 pm" src="https://user-images.githubusercontent.com/26032343/52891072-5d530a00-313d-11e9-8994-110222de871b.png">

**Comment by kinarashah** [comment]
@westlywright from the logs, it looks like empty credentials are sent? could you take a look

**Comment by sowmyav27** [comment]
verified on rancher:master (02/19/2018)

User is able to add/edit node templates on an upgraded Rancher setup. No error is seen on the UI. Snapshots of the API and secrets created on the management place are attached below.

![screen shot 2019-02-19 at 11 04 23 am](https://user-images.githubusercontent.com/26032343/53041255-5cb9bc80-3438-11e9-877c-04199f0c92e5.png)

<img width="287" alt="screen shot 2019-02-19 at 11 04 34 am" src="https://user-images.githubusercontent.com/26032343/53041261-5f1c1680-3438-11e9-87a5-0b71d9b13bb9.png">

<img width="747" alt="screen shot 2019-02-19 at 11 06 45 am" src="https://user-images.githubusercontent.com/26032343/53041265-60e5da00-3438-11e9-8667-33956ad69d68.png">
