### ISSUE TITLE
UI - Provider help for Global DNS annotation when creating ingress.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18199]
Rancher server version -  Build from master

When user wants to create Global DNS entries pointing to projects , they are expected to create ingress with annotation - `rancher.io/globalDNS.hostname` to match the  host name they use for their routing rules.

It would be good if UI is able to provide some helper text /option to make this annotation made available to the user.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/21/19)
There is now helper text if you pick the Projects radio button when creating a GDNS entry:

![image](https://user-images.githubusercontent.com/45179589/53201350-05a31b80-35e1-11e9-9de5-656b0a38e238.png)
