### ISSUE TITLE
Unable to view installed apps in UI after removing catalog template version

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#18197]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install an app, remove the catalog associated with the app, and refresh the apps page view (eg /g/apps).

**Result:**
The app list is not displayed, instead an error page like the following is shown:
```
NotFound (404)
catalogtemplateversions.management.cattle.io "library-redis-3.0.2" not found

Reload to try again or log out
```

**Other details that may be helpful:**
If a version of a chart is removed from a catalog we should still be able to see all of the installed apps, and highlight apps where the associated catalog template version no longer exists.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
server master
UI v2.2.2

**Comment by no-reply** [comment]
I'm also seeing behavior like this.

It's not clear to my team, from documentation, what the is preferred mechanism for updating chart versions in Rancher. We thought we had developed a reasonable practice using `charts/mychart/latest` and incremental version numbers in `Chart.yaml`, but running into this error has called that into question.

**Comment by rstanonik** [comment]
We're seeing it also.  Rancher 2.2.0.  Any suggestions for recovering?  I tried refresh on the catalog, whose name occurs in the error.  And I killed any deploys/updates that seem to be hung.  Restart rancher?

Thanks.

**Comment by rstanonik** [comment]
We recreated the missing branch and Global/Apps works again.
Not ideal, but one way to recover.

**Comment by Negashev** [comment]
Any progress on this?

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 

* Reproduced in v2.2.2
* Added a catalog
* Installed multicluster app from catalog
* Removed the catalog
* Viewed multicluster apps page
* Error was presented: `404 - catalogtemplateversions.management.cattle.io "test2-alpine-test-v1-0.1.0" not found`

* Deploy Rancher
* Create cluster
* Add catalog
* Deploy multicluster app from catalog
* Upgrade app
* Delete catalog
* View multicluster apps
* Apps display successfully
* App from deleted catalog cannot be upgraded or rolled-back, only deleted or view in api
* Adding the catalog back allows the user to upgrade or roll-back the app
