### ISSUE TITLE
Allowed to start multiple containers on the same host using the same public port.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#182]
version:
rancher/server      beta                54eb289064e5        3 days ago          510.5 MB
rancher/server      v0.10.1             54eb289064e5        3 days ago          510.5 MB

Steps to reproduce the problem:
On a host , start a container which maps public port 8080 of the host to  private port 8080 on the container.
On the same host , start another container which maps public port 8080 of the host to  private port 8080 on the container.

Creation of this container is successful and we see port 8080 on the host being mapped to both the containers.

Expected Behavior:
We should not be allowed to create multiple containers using the same public port mapping on the same host.

snippet of iptable on the host showing port 8080 mapped to multiple ip addresses:

-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 8080 -j DNAT --to-destination 10.42.119.68:8080
-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 8080 -j DNAT --to-destination 10.42.14.203:8080

**Comment by ibuildthecloud** [comment]
We actually view this as more of a feature. We allow the port to be bound multiple times to allow you to do a seemless cut over to a new application.  If you have v1 running on port 80 and then deploy v2 on port 80, v1 should be active on 80 until it is shut down and v2 will immediately take over.

What should be changed in rancher is that this behavior should be deterministic which it isn't today.  The container that was created first should always own the port.

**Comment by sangeethah** [comment]
Is the intent to allow only for different versions of the same application to use the same port ? Or can 2 different applications be allowed to use the same public port , as well ?

Thanks
Sangeetha


On Mar 10, 2015, at 6:49 PM, Darren <notifications@github.com<mailto:notifications@github.com>> wrote:


We actually view this as more of a feature. We allow the port to be bound multiple times to allow you to do a seemless cut over to a new application. If you have v1 running on port 80 and then deploy v2 on port 80, v1 should be active on 80 until it is shut down and v2 will immediately take over.

What should be changed in rancher is that this behavior should be deterministic which it isn't today. The container that was created first should always own the port.

**Comment by ibuildthecloud** [comment]
It can be any two arbitrary containers

**Comment by vincent99** [comment]
See also #435.  This seems more like a land-mine than a feature..

**Comment by tfiduccia** [comment]
I'm no longer able to do this through the UI.  I see the error:  Error (500 Server Error: Internal Server Error ("failed to create endpoint r-container2 on network bridge: Bind for 0.0.0.0:8080 failed: port is already allocated")).

Sangeetha, is there something I am missing or can we just close?
