### ISSUE TITLE
Wrong cluster driver name for custom cluster drivers

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18208]
rancher/rancher:master 02/18

It shows cluster driver id instead of name

The name should be `Aliyun` instead of `Aliyunkubernetescontainerservice`

![image](https://user-images.githubusercontent.com/21168270/52924235-d6817580-3366-11e9-9c26-69dfcd1d0319.png)

**Comment by orangedeng** [comment]
I think UI should check for the `Installed` condition for the driver. If `Installed`, UI should shows the binary from the `url` attribute. e.g. `aliyun` from `https://github.com/rancher/kontainer-engine-driver-aliyun/releases/download/v0.2.3/kontainer-engine-driver-aliyun-linux`.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Confirmed fix.
The proper driver name is shown for each node/cluster driver regardless if active or not.
