### ISSUE TITLE
Getting an error: "Node created without a route" when adding new nodes to the cluster

### ISSUE THREAD

**Issue by bearmoo-repo** [rancher/rancher#18207]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
create a a cloud in gce
create vms and join them to the cluster

**Result:**
All nodes should be Active

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.6

- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
 v1.11.6 
```

**Comment by bearmoo-repo** [comment]
I've tried to do some googling, and I came across this:

https://github.com/kubernetes/kubernetes/issues/44254

My issue seems very similar to the issue above. I've tried looking at way that I can apply the workaround, and not sure exactly sure how. Any idea how I would go about it?

**Comment by bearmoo-repo** [comment]
To provide more information that I'm seeing. Here are the error messages I'm getting when creating a new cluster and adding a node:

2019/02/18 18:10:41 [INFO] Creating roleBinding User user-w9kxc Role project-owner
2019/02/18 18:10:41 [INFO] Creating roleBinding User user-w9kxc Role admin
2019/02/18 18:10:41 [INFO] Updating clusterRoleBinding clusterrolebinding-dlvxz for project access to global resource for subject user-w9kxc role project-owner-promoted.
2019/02/18 18:10:41 [INFO] Deleting roleBinding clusterrolebinding-jrl9m
2019/02/18 18:10:41 [ERROR] NamespaceController cattle-system [namespace-auth] failed with : clusterroles.rbac.authorization.k8s.io "p-2ftmn-namespaces-edit" already exists
2019/02/18 18:10:41 [INFO] Updating clusterRoleBinding clusterrolebinding-vrm8d for project access to global resource for subject user-w9kxc role create-ns.
2019/02/18 18:10:41 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-qgi5elknlg with role cluster-owner in namespace
2019/02/18 18:10:43 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-2ftmn to namespace=kube-system
2019/02/18 18:10:52 [INFO] Handling backend connection request [c-nbzpm:m-ace49df4ec0c]
2019/02/18 18:11:07 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/02/18 18:11:07 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/02/18 18:11:07 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
E0218 18:11:07.888099       6 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0218 18:11:07.888584       6 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0218 18:11:07.888613       6 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0218 18:11:07.888650       6 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0218 18:11:07.888818       6 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0218 18:11:07.888859       6 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect

**Comment by bearmoo-repo** [comment]
Any update please?

**Comment by thxCode** [comment]
@bearmoo-repo  I guess you are using the GCE Cloud Provider function and `Flannel` network plugin.

- Following https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#gce, if using GCE cloud provider, please override **Node Name** when adding a host. Left it blanks if you never change the hostname inside the host.
- For GCE cloud provider configuration, here is a template: https://github.com/rancher/rke/issues/1329#issuecomment-490775878
- If using Calico/Canal, this calico PR https://github.com/projectcalico/node/pull/89 should fix https://github.com/kubernetes/kubernetes/issues/44254.
- if using Flannel, I got a suggestion: https://github.com/kubernetes/kubernetes/issues/56794#issuecomment-362023245. For rancher custom cluster, click **Edit as YAML** when creating a new one, and then configure as below:
```yaml
...
cloud_provider:
  name: gce
  customCloudProvider: |-
    [Global]
    network-name=frank-vpc
    subnetwork-name=frank-vpc
    node-instance-prefix=frank-windows2019-
    node-tags=http-server,https-server
services:
  kubeController:
    configure-cloud-routes: true
...
```

Could you test again?

**Comment by thxCode** [comment]
@bearmoo-repo  I guess you are using the GCE Cloud Provider function and `Flannel` network plugin.

- Following https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#gce, if using GCE cloud provider, please override **Node Name** when adding a host. Left it blanks if you never change the hostname inside the host.
- For GCE cloud provider configuration, here is a template: https://github.com/rancher/rke/issues/1329#issuecomment-490775878
- If using Calico, this calico PR https://github.com/projectcalico/node/pull/89 should fix https://github.com/kubernetes/kubernetes/issues/44254.
```yaml
network: 
  options: 
    calico_cloud_provider: "gce"
  plugin: "calico"
```
- if using Flannel, I got a suggestion: https://github.com/kubernetes/kubernetes/issues/56794#issuecomment-362023245. For rancher custom cluster, click **Edit as YAML** when creating a new one, and then configure as below:
```yaml
...
cloud_provider:
  name: gce
  customCloudProvider: |-
    [Global]
    network-name=your-vpc
    subnetwork-name=your-vpc
    node-instance-prefix=your-instance-prefix/your-instance-group-name
    node-tags=network-tags
services:
  kubeController:
    extra_args:
      configure-cloud-routes: true
...
```

**Comment by superseb** [comment]
Let us know if this still needs work.
