### ISSUE TITLE
UI - Not able to present the projects that user does not have access to as part of the shared Global DNS entries.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18203]
Rancher server Version - Build from master - Feb 15

Steps to reproduce the problem:

As `user1`:

1. Create globalDnsProvider with root domain - "test.com"   
2. Create a globalDns entry  with fqdn   - "test1.test.com" with projectIds set to cluster1/p1 and add   `user2` as owner.
3. In user cluster - Cluster1/p1,  Create Ingress using annotation -   rancher.io/globalDNS.hostname=test1.test.com which points to a  workload with host name rule pointing to   "test1.test.com"

Log in as `user2`.
Go to "globalDns entry" tab.
The above shared globalDnsProvider is listed as expected.

In the list view it is not able to show that it this entry is associated with project -p1.
Also in the detail view does not have details of the project it is associated with and presents a list of projects user has access to.

User is able to add another project say -p1 to this  globalDnsProvider after which it shows up as being associated with only this project when there are 2 projects associated with it.

`user2` view:

<img width="1209" alt="screen shot 2019-02-15 at 7 34 54 pm" src="https://user-images.githubusercontent.com/4266958/52894913-9653a480-3166-11e9-99b7-48d7ba8f381e.png">

<img width="1125" alt="screen shot 2019-02-15 at 9 16 17 pm" src="https://user-images.githubusercontent.com/4266958/52894939-0eba6580-3167-11e9-8885-98d303d4da34.png">

`user1` view
<img width="1119" alt="screen shot 2019-02-15 at 7 34 48 pm" src="https://user-images.githubusercontent.com/4266958/52894917-9d7ab280-3166-11e9-8b04-0829836355cf.png">

<img width="1116" alt="screen shot 2019-02-15 at 9 20 29 pm" src="https://user-images.githubusercontent.com/4266958/52894957-93a57f00-3167-11e9-94e7-d0de2253bf50.png">

**Comment by mrajashree** [comment]
Does user1 have access to both projects? I tried this by
1. Giving user1 access to 2 projects: p1 and p2. 
2. Then I created gdns entry with p1 as target project and added user2 as owner. 
3. Logged in as user2 and added user2's project p2 to targets, list view display shows only p2. But the API UI has both project IDs in it. I think UI not showing those projects that user does not have access to is expected? cc @westlywright

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/21/19)
The UI now shows when you do not have access to a project(s):
![image](https://user-images.githubusercontent.com/45179589/53200954-0edfb880-35e0-11e9-975e-1089af5c3746.png)

![image](https://user-images.githubusercontent.com/45179589/53200989-228b1f00-35e0-11e9-9c58-dd7cfa037f76.png)

If you have permission to a project and add it you can access it, otherwise you will get a message for each project you do not have access to like shown in the above screenshots.

**Comment by davidnuzik** [comment]
@sangeethah do you want a message in Edit of GDNS entry when we don't have access to one of the projects? See my last screenshot in comment above. It's already indicated on GDNS entry listing but it's not shown in edit view. Only if you don't have access to all projects will you get a message that you do not have access. If you have access to at least one project it's listed but it doesn't tell you what you DON'T have access to only when editing. Hope this makes sense.
