### ISSUE TITLE
Continue enable/disable logging quickly may deploy failed finally

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18214]
Server version: master
Step to reproduce:
1. enable project logging, config a target, then it will deploy a rancher-logging, you can see it system project catalog, also can see fluentd, aggregator workload
2. disable logging quickly
3. then enable logging ASAP
4. you may finally don't see any rancher-logging catalog even you enable logging.

**Comment by rootwuj** [comment]
Version: master 2.2 (2/21/19) Image ID: cdd98a0abb92
Confirmed fixed.
