### ISSUE TITLE
Custom kontainer-driver is active status while downloading binary

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#18211]
Rancher master 2/18

After I activate the cloud driver, the status of the driver becomes `Active` immediately while the driver's binary is still downloading. It should show the `Downloading` status instead of `Active`.

Reproduce:
1. Setup a rancher server in you laptop.
2. Disable the network(Wifi/Lan) and make sure you don't have the internet access.
3. Active one of the custom cloud drivers(aliyun/tencent/huawei) and you should see the status become `Active` immediately.

**Comment by cjellick** [comment]
@rmweir to validate

**Comment by rmweir** [comment]
Validated that driver goes to downloading upon activation.

Steps to validate:
1. Ran rancher
2. Navigated to drivers
3. Activated each inactive drive, alternating between menu activate and header active button.
4. Created a new driver using darwin version of Aliyun driver (https://github.com/rancher/kontainer-engine-driver-aliyun/releases/download/v0.2.4/kontainer-engine-driver-aliyun-darwin).

Results:
Each driver went to 'Downloading' and did not go appear to go to 'Active' first.

**Comment by rmweir** [comment]
Validated that driver goes to downloading upon activation.

Steps to validate:

Ran rancher
Navigated to drivers
Activated each inactive drive, alternating between menu activate and header active button.
Created a new driver using darwin version of Aliyun driver (https://github.com/rancher/kontainer-engine-driver-aliyun/releases/download/v0.2.4/kontainer-engine-driver-aliyun-darwin).
Results:
Behaved as expected. Each driver went to 'Downloading' and did not go appear to go to 'Active' first.
