### ISSUE TITLE
Rancher tmp not cleaned up properly causing inode exhaustion when invalid helm config is used.

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#18217]
**What kind of request is this (question/bug/enhancement/feature request):** BUG

**Steps to reproduce (least amount of steps as possible):** 

I accidentally caused this with an invalid helm value being left in place. I'll attempt to figure out how to produce this, but hopefully the log messages and context will be enough to resolve.

**Result:**

The `tmp` directory gets 10s of 1000s of `./tmp/helm-475588576` created as it attempts to resolve a conflict it cannot resolve and does not clean them up, this winds up exhausting inodes in the `/var/lib/docker` filesystem.

**Important:** About 50 `helm-INT` directories are are created every 10 seconds when an invalid key exists, if not caught (like it wasn't in my cause until inode exhaustion) this leads to 300/minute, 18k/hour, 432k/day of directories being created.

**Other details that may be helpful:**

```
2019/02/18 21:18:26 [ERROR] AppController p-rnz4r/test-s6 [helm-controller] failed with : helm template failed. Error: failed parsing --set data: key "test-key" has no value (cannot end with ,)
```
This error is spit out an an alarming rate which seems to be correlated to the tmp files.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-alpha6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): METAL
- Machine type (cloud/VM/metal) and specifications (CPU/memory): quad core / 16GB RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Instructions to Reproduce
1. Enabled Helm Stable Charts
2. Launch Minecraft (from Helm)
3. Edit Answers as YAML and use the following
```
---
  minecraftServer: 
    difficulty: "hard"
    eula: "true"
    ops: "AnyName"
    pvp: "true"
    type: "VANILLA"
    version: "1.13.2"
    whitelist: "AnyName,AnyName1,AnyName2"
```
4. Click into the Newly Deployed Catalog, you'll see an error something like
```
Helm template failed. Error: failed parsing --set data: key "AnyName1" has no value (cannot end with ,) : exit status 1
```

This could be a bug in of itself as well. ITSM that its perfectly valid to have a string of comma separated values for the value whitelist and according to the helm chart it should pass those to an env var. It might however be throwing an error due to the `| quote` instruction. However changing the answers.yml to not have quotes in it still results in the same error, so I'm not sure.

**Comment by ekristen** [comment]
The silver lining is that the cluster remained online, but the primary node running rancher was unable to complete any new operations.

**Comment by erikwilson** [comment]
This should be fixed as part of [/issues/14322](https://github.com/rancher/rancher/issues/14322) PR (#17596). Also see /issues/17330.

There was a part of the code in helm.generateTemplates where we were improperly cleaning up a ioutil.TempDir call.

The basic case of deploying an app would leave behind temporary directories, but an error condition would create those very quickly. Without proper information on how to induce an error condition, we should use the basic test case as described in /issues/17330.

**Comment by ekristen** [comment]
I found a way to induce the error condition. Standby for instructions.

**Comment by ekristen** [comment]
I updated the original description with `Instructions to Reproduce`.

**Comment by sowmyav27** [comment]
tested with rancher:master and was able to validate the basic case of deploying an app. https://github.com/rancher/rancher/issues/17330#issuecomment-467221602 

Reproduced the issue as mentioned in https://github.com/rancher/rancher/issues/18217#issue-411655485 when tested on `rancher:v2.2.0-alpha6`. 

When tested on `rancher:master`, on launching 2\. Minecraft and editing answers as YAML, the error seen earlier, isnt seen anymore. But the application is still in `deploying` status and error `Pod has unbound immediate PersistentVolumeClaims` is seen on the UI.

<img width="1413" alt="screen shot 2019-02-25 at 5 50 35 pm" src="https://user-images.githubusercontent.com/26032343/53381523-e4fefc80-3925-11e9-888b-d2bd3f64719b.png">

**Comment by bordeo** [comment]
@ekristen I’m using rancher-server 2.1.6 and I get into this bug. During the waiting of 2.2 version to avoid the problem can I remove all file in ./tmp/helm-*?

**Comment by ekristen** [comment]
I cleared mine out. Seemed to be ok
