### ISSUE TITLE
Monitoring - Project-level Grafana cannot read data when restarting cluster host

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#18218]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable cluster-level monitoring
2. Enable project-level monitoring
3. Catalog app project-monitoring works normally
4. Click index.html to enter the grafana console, grafana can read data normally
5. Stop the cluster host
6. After a few hours, start the cluster host

**Result:**
Project-level Grafana cannot read data

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:master (2/18/19) Image ID: 46f4b03ba30e

**Comment by thxCode** [comment]
I found that `remote reader` mode doesn't occur any error after host restarting. We will recommend using `federate` mode in https://github.com/rancher/rancher/pull/18116.

**Comment by rootwuj** [comment]
Version: master 2.2 (2/21/19) Image ID: cdd98a0abb92
Confirmed fixed.
