### ISSUE TITLE
Rancher2: similiar Project Names break rancher-cli

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#18222]
**What kind of request is this (question/bug/enhancement/feature request):** 
Bug

**Steps to reproduce (least amount of steps as possible):**
create NS, and multiple Projects with same Name.
```
~> rancher project create project1
~> rancher project create project1

~> rancher namespace create test1
~> rancher namespace move test1 project1
FATA[0000] Multiple resources of type project found for name project1: ...
```

**Result:**
namespace can't be moved into a project if name is equal to some other project

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.6
- Installation option (single install/HA): HA

**Comment by strowi** [comment]
imho creating similar named projects should be forbidden, same way as kubernetes doesn't allow 2 ns with the same name. Nobody will remember the hash/id of a project.

Also it is problematic if you are creating projects/ns via a repository, imagine following ci-script..
We also would like to create the projects idempotent, but that won't work with the current cli.
```
#!/bin/bash

NS_SYS="
  sys-k8-ingress-controller \
  sys-k8-node-cleanup \
  sys-logging-filebeat \
  sys-monitoring-alertmanager \
  sys-monitoring-blackbox-exporter \
  sys-monitoring-kube-metrics \
  sys-monitoring-node-exporter \
  sys-monitoring-prometheus \
  "
rancher login \
  ${RANCHER2_PROD_URL} \
  --token "${RANCHER2_PROD_CISYS_TOKEN}" \
  --context "${RANCHER2_CONTEXT}"


for ns in ${NS_SYS}; do
  sed "s/\$KUBE_NAMESPACE/$ns/g" templates/rancher2_namespace_sys.yml > manifests/$ns.yml
 rancher namespaces move $ns ck.sys
done
```

**Comment by vincent99** [comment]
Unique project names means that in an installation with many clusters and thousands of users, one early random person gets (or intentionally squats on) all the "good" names like "dev" or "prod" and everyone else has to pick something else even though they have no idea who that person or department is and will probably never be a member of that project.

The CLI accepts project/cluster IDs too, which are unique.

**Comment by strowi** [comment]
@vincent99 Ah so projects are supposed to be global? I only saw them on the cluster-level, where the same principle would apply to namespaces. But with global projects it makes a little more sense. Thx!

**Comment by vincent99** [comment]
A project uses a single particular cluster, but is a top-level global resource (it is not actually inside the cluster).

They are organized by cluster in the UI because that's how you logically think of that, but with the right rbac config it is theoretically possible for a user to have access to a project and the namespace(s) it is assigned without having any access to or knowledge of the cluster resource/nodes of that cluster/etc.  (That probably wouldn't work today without UI changes, but think public SaaS with large managed clusters shared by unrelated customers)
