### ISSUE TITLE
Server Crashes After A MC App Deletes an App Target in a Project They Don't Have Access To

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#18229]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug
Found while fixing rancher/rancher#18153

**Steps to reproduce (least amount of steps as possible):**
Create a standard user - `test1`.
As admin user, Create a Multi cluster app with targets as projects from 2 different cluster and add "test1" as owner.

Log in as `test1` and go to Multi-cluster app tab

On the mc app that was created earlier select the upgrade action.
On the upgrade page ONLY remove a target, it can be either one because this user should not have had explicit access granted to the project.

**Result:**
A server panic occurs and the UI can no longer reach the server, all that is received is proxy errors.

**Other details that may be helpful:**
The logs from my server
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x228 pc=0x2aa00c4]

goroutine 10073 [running]:
github.com/rancher/rancher/pkg/controllers/management/multiclusterapp.(*MCAppManager).delete.func1(0x8, 0x3bc9658)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/multiclusterapp/controller_multiclusterapp.go:596 +0x164
github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc006838840, 0xc0068388a0)
	/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/rancher/rancher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Master (2/19/2019)
- Installation option (single install/HA):
Single Node launched with `--add-local=true`

**Comment by mrajashree** [comment]
@westlywright I'm looking into this, but just wanted to confirm that projects aren't updatable via Upgrade action anymore, and only through addProjects/removeProjects action

**Comment by mrajashree** [comment]
@westlywright the fix is available in master now

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/21

As admin:
* Created 2 clusters
* Created multicluster app with 2 project targets, adding a user who does not have access to any projects as app owner 

As standard user:
* Login and upgrade multicluster app
* Remove one target

The target project was removed successfully, and the app was removed from the project correctly. There were no panics in the logs, and the UI remains functional.
