### ISSUE TITLE
GKE - cannot provision a GKE cluster with custom access scope

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18226]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher master container
- add a GKE cluster
-  choose `Set access for each API` for the `Security`, and leave the rest default value
<img width="1445" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53038013-e9fd1100-3438-11e9-980c-655198ba3923.png">

**Result:**
Rancer shows error message like this
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Googleapi: Error 400: Cluster.node_config.oauth_scopes cannot have the same scope (https://www.googleapis.com/auth/none) repeated twice., badRequest
```
<img width="1423" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53038004-e1a4d600-3438-11e9-941a-8ccd2dc7fc48.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master 2/19
- Installation option (single install/HA):
single install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by fyery-chen** [comment]
@n313893254 Please check if there are same scopes when sending the request as the steps showing above.

**Comment by n313893254** [comment]
Yes, I will fix it.

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master 2/20. Following the steps in the issue, the GKE cluster is provisioned successfully. Also, test the `full access` mode.
