### ISSUE TITLE
Logging does not clear the cache

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18220]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch project level or cluster level logging
2. Click on `Edit as File` and enter the value below.  `Save`
```
<match *>
  @type kafka_buffered
  # list of seed brokers
  brokers XXX:19094
  # topic settings
  default_topic ksd2
  # data type settings
  output_data_type json
  compression_codec gzip
  # producer settings
  max_send_retries 1
  required_acks -1

  username alice
  password alice-secret
  scram_mechanism sha512
</match>
```
3. Click `None`-->'Save' to disable logging.
4. Launch logging again and go to `Edit as File`

**Result:**
The cache is not cleared, the value added in step 2 still exists in the form.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master 02/19
- Installation option (single install/HA):
single install/

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/22/19, ImageID: 6fbc596be2db) Replicated the issue again.
Follow the steps to reproduce. Once you click Save for "None" to turn off logging go back to edit as File. Notice the text is still there:

![image](https://user-images.githubusercontent.com/45179589/53268976-dc4bc380-36a4-11e9-8c0e-e90bb3b31831.png)

I am re-opening the issue please let me know if there is anything you need from me.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/26/19)
Confirmed issue. Follow the steps to reproduce again. When you go to None type and save the text is now cleared if you Edit as File again.

Before:
![image](https://user-images.githubusercontent.com/45179589/53441449-20500880-39c4-11e9-86be-fe3c50c99c8b.png)

After:
![image](https://user-images.githubusercontent.com/45179589/53441465-25ad5300-39c4-11e9-9fde-ab875691960a.png)
