### ISSUE TITLE
UI - Multicluster app - unable to view/add members to existing app on upgrade

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#18242]
rancher/rancher:master 2/19
HA setup

Github auth enabled - checked with standard and admin users

After creating a multicluster app, members can not be viewed or edited.

To reproduce: 
* Create a multicluster app, adding at least one member
* After app is created, click upgrade from the menu

Expected:
* Existing members are displayed
* New members can be added

Actual:
* Existing members are not displayed
* Unable to add members to the list

![screen shot 2019-02-19 at 2 32 32 pm](https://user-images.githubusercontent.com/21316915/53049020-5c7aea80-3453-11e9-9ea1-feffae88059d.png)

**Comment by westlywright** [comment]
Please see https://github.com/rancher/ui/pull/2671 for comments on verification

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/20

This is now functioning correctly when using external auth admin.
