### ISSUE TITLE
Multi-Cluster App UI: Able to add multiple of the same project target

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18241]
Version: Master 2.2 (2/19/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a MC app. Add multiple of the same project.

**Result:**
You can add multiple target projects (same project). You should not be able to do this.

**Other details that may be helpful:**
The MCapp will actually provision to the same project several times but only actually appears to be one workload and doesn't seem to hurt anything including when I upgrade to add/remove more or add other unique projects.

![image](https://user-images.githubusercontent.com/45179589/53048874-00b06180-3453-11e9-9020-d287d83a8912.png)

![image](https://user-images.githubusercontent.com/45179589/53048867-fb531700-3452-11e9-98ae-1bb18d6d798a.png)

**Comment by westlywright** [comment]
@davidnuzik I am making a change in the UI that will stop the the user from being able to add duplicates before you launch but this should also have a backend change (not required to verify this ticket or for my code changes). The backend should validate the projectIds and error if there are dupes. Can you open a ticket for that as well?

**Comment by davidnuzik** [comment]
@westlywright sure thing. Issue is here: #18335

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/22/19)
Confirmed issue. The UI no longer allows you to pick multiple of the same project.
As you pick target projects from the drop-down they are removed from the drop-down list.
You can also remove the target project using the minus button to add them back to the drop-down.

Screenshot showing p1 and Default projects removed from drop-down because I have already picked them.
![image](https://user-images.githubusercontent.com/45179589/53268114-72321f00-36a2-11e9-9b83-f26d32d2f039.png)

Screenshot showing them back in the drop-down list because I removed those target projects:
![image](https://user-images.githubusercontent.com/45179589/53268160-8bd36680-36a2-11e9-8750-82b19c271ce4.png)

Tested with multi-cluster as well to ensure no issues here. Try with same name project, etc. I could not identify any issues. Smoke tested mcapps / target projects selection.
