### ISSUE TITLE
Restored custom cluster never sync old cluster in rancher dashboard

### ISSUE THREAD

**Issue by thiagosantosleite** [rancher/rancher#18245]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

After restore a ha custom cluster, its does not sync with the old cluster in the rancher dashboard. Would be nice if the restore process have a step do sync it again

https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/

In my case, After I restore my custom cluster, I have to delete the cluster and create a new cluster with the import feature, but with this feature I lost some benefits of custom clusters, like auto install and register the new nodes.

Please advise if I'm wrong.

**Comment by MKlimuszka** [comment]
Closing as stale.
