### ISSUE TITLE
Host List Filter

### ISSUE THREAD

**Issue by gerred** [rancher/rancher#1824]
We're in an environment that has a lot of hosts (600+) per environment, and we'd like to filter our host lists to get a better handle on it. This could be as simple as a label match to start.

Happy to open a PR on this if it's a useful enhancement.

**Comment by lavvy** [comment]
+1 I have always thought of this. I think this will be great. And so happy seeing rancher navigating  600+ hosts :)

**Comment by vincent99** [comment]
Honestly I'm surprised the UI is actually usable with that many hosts, as we've spent no time optimizing it lately.  And also that it's correct, as there are pagination issues with responses that have more than 1000 resources in them (#1339 -> #1606) causing duplicate containers to show up.

If you're familiar with Ember, doing client-side filtering of the hosts would be relatively straightforward I think.  If not, yes we will add something like this eventually :smile:
  - Add a computed property to `app/hosts/index/controller.js` with a sorted/uniq-ed array of all the labels
  - Create a dropdown-type component for the upper-right side of the screen with a list of each of those labels (like the label filters on the issue list here in GitHub, though I'd prefer checkboxes and multi-select/select all/select none to only being able to see a single label).
  - Create something like a "filterable" mixin that takes an unfiltered array and the selected label(s) and returns the ones that match (similar to `app/mixins/sortable.js`)
  - Change the hosts screen (`app/hosts/index/template.hbs` and `controller.js`) to display only the filtered hosts

**Comment by gerred** [comment]
I usually avoid looking at it. :smile:

I'm familiar with Ember, I'll take a shot. Should I open this issue over in the ui repo and reference it from here?

**Comment by vincent99** [comment]
There are too many sub-projects for us to keep track of effectively so issues go in here and are disabled on most of the other repos; you can fork and PR into rancher/ui though.

**Comment by gerred** [comment]
Ok! Will do.

**Comment by kaos** [comment]
+1

**Comment by defunctzombie** [comment]
@vincent99 still interested in a PR here or have other plans for the UI?

Personally, beyond a host filter (which I am happy to PR), I would find it much more straightforward to look at the hosts as a list versus the "card" view which is only useful for a handful of hosts.

**Comment by vincent99** [comment]
Consolidating with #1533
