### ISSUE TITLE
EKS does not allow less than 3 worker nodes

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#18243]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Click add cluster
2. Select EKS cluster
3. input access key and secret key, click next
4. set max number of nodes to 1 or 2
5. Create cluster

**Result:**
cluster creation will fail with error message `Error creating stack: stack failed to create: Desired capacity:3 must be between the specified min size:1 and max size:1`.

**Other details that may be helpful:**
When the template was last updated we added a `NodeAutoScalingGroupDesiredCapacity` parameter to the template but did not supply it a value when we create the cluster.  We need to add this capacity field to the KE driver interface or else remove it from the template.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): eks
- Machine type (cloud/VM/metal) and specifications (CPU/memory): N/A
- Kubernetes version (use `kubectl version`): N/A

```
(paste the output here)
```

- Docker version (use `docker version`): N/A

```
(paste the output here)
```

**Comment by davidnuzik** [comment]
I also ran into this today. v2.2.2-rc7 I just wanted to create an EKS cluster with min 1 max 1 for testing purposes. The cluster creates successfully in EKS without any issues; only rancher reports this issue.

![image](https://user-images.githubusercontent.com/45179589/55837686-f4519800-5ad6-11e9-9b96-f6fbc0f707ea.png)

**Comment by siddharthlatest** [comment]
Running into this as well. @nathan-jenan-rancher Can you link to the template you are referencing to? Will try to create a PR if that fix is useful.

**Comment by cjellick** [comment]
When we fix, need to make sure that we do not break/change the behavior of existing clusters

**Comment by ishantanu** [comment]
Ran into this issue as well. Is there any way the desired node capacity can be configurable via Rancher? The autoscaling group always defaults to 3 nodes as the desired capacity which is A LOT of cases could be an incorrect assumption.

**Comment by jiaqiluo** [comment]
Will be tested when the UI is merged. Expected to see there is only one value being sent to the backend and it will be used to set the min, max and desired.

**Comment by davidnuzik** [comment]
https://github.com/rancher/rancher/issues/22097#issuecomment-520910243 UI issue has been tested end to end. I don't think any other testing is required unless is specific to API.

**Comment by jiaqiluo** [comment]
@davidnuzik 's test is sufficient to validate the bug fix. Thank you David. 

Also checked that the ssh key used for nodes is the one picked during creating process.

**Comment by vasanthapriya-svp** [comment]
I am using 2.2.8 version of rancher . still the issue prevails . Have inputted 1 for min & max ASG. However the cloud formation script framed by rancher still defaults the desired to 3 .


NodeAutoScalingGroupDesiredCapacity | 3 | -
NodeAutoScalingGroupMaxSize | 1 | -
NodeAutoScalingGroupMinSize | 1 | -

Error : Desired capacity:3 must be between the specified min size:1 and max size:1 (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: fc0e7edd-c440-11e9-be03-d336ff22f57a)

**Comment by cbron** [comment]
Hi @vasanthapriya-svp, this will be included in the official 2.3.0 release. You can follow [our releases page](https://github.com/rancher/rancher/releases) to see when that is out, or see [our roadmap](https://github.com/rancher/rancher/wiki/Rancher-Project-Plan) for target dates.
