### ISSUE TITLE
Multi-Cluster apps disappear after server restart

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#18250]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Restart Rancher server after installing a multi-cluster app

**Result:**
After restart the following error may appear:

```
2019/02/19 15:55:52 [ERROR] MultiClusterAppController cattle-global-data/mca-hr7w9 [multi-cluster-app-controller] failed with : error App.project.cattle.io "" is invalid: metadata.name: Required value: name or generateName is required in creating multiclusterapp: &{{} {MultiClusterApp management.cattle.io/v3} {mca-hr7w9  cattle-global-data /apis/management.cattle.io/v3/namespaces/cattle-global-data/multiclusterapps/mca-hr7w9 64014b69-3499-11e9-a1ab-025000000001 3541 1 2019-02-19 15:55:02 -0700 MST <nil> <nil> map[cattle.io/creator:norman] map[field.cattle.io/creatorId:user-gskw4] [] nil [] } {cattle-global-data:library-redis-3.0.2 [{  map[image.repository:bitnami/redis cluster.enabled:true image.tag:4.0.9 master.persistence.enabled:false slave.service.nodePort: cluster.slaveCount:3 metrics.image.repository:oliver006/redis_exporter password: slave.service.type:ClusterIP usePassword:true master.service.type:ClusterIP master.persistence.storageClass: defaultImage:true master.service.nodePort: metrics.image.tag:v0.11 master.persistence.size:8Gi]}] [{local:p-8s57j   }] [] [cluster-owner project-owner] 10 {<nil>}} {[{Installed True 2019-02-19T15:55:04-07:00   } {Deployed True 2019-02-19T15:55:21-07:00   }] mcapprevision-95k4m}}
.
.
.
[tiller] 2019/02/19 16:08:11 uninstall: Deleting mca-hr7w9-p-8s57j
```

The app disappears from from the Project Catalog Apps page and attempt to access the project deployment from the Multi-Cluster apps page will result in a 404, even though the app shows as 'Active' in MC Apps.

Another restart of the server will re-deploy the app on the project level, but may result in errors like:

```
[kube] 2019/02/19 16:02:56 Using reaper for deleting "mca-hr7w9-p-8s57j-redis-master"
2019/02/19 16:02:56 [ERROR] StatefulSetController mca-hr7w9-p-8s57j/mca-hr7w9-p-8s57j-redis-master [workloadServiceGenerationController] failed with : cannot find app namespace in labels of mca-hr7w9-p-8s57j
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher master (d1d307c0ed18cb13c743e7b5d41986f985d918c9)
- Installation option (single install/HA):
Single

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/22

* Single node install
* Created cluster
* Deployed multicluster app to multiple targets
* Stopped Rancher server
* Started Rancher server
* Multicluster app is still present and functional

* HA install
* Created cluster
* Deployed multicluster app to multiple targets
* Redeployed Rancher daemonset
* Multicluster app is still present and functional
