### ISSUE TITLE
Image preload from Docker registry

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#1825]
We should allow users to set a label on Docker image specifying that they want to preload this image on every host. When Rancher sees a new image is pushed (through listening to DockerHub webhook or polling private registry) Rancher can pull the image for every host.

The label should indicate what version to preload since the user may not always want the latest. Default should be the latest.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/1825

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/1277
