### ISSUE TITLE
Update tiller version for k8s 1.13/1.14 deployments

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18259]
Tiller version should be upgraded for k8s 1.13 and 1.14 (once released) deployments, to align with the latest stable version

**Comment by deniseschannon** [comment]
Since we're not adding in support for k8s 1.13 due to the deprecation of etcd v2, we won't be updating tiller.

https://github.com/rancher/rancher/issues/17851#issuecomment-479329157
