### ISSUE TITLE
Add state to cluster etcd backups page

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#18257]
UI should be updated to the new changes tracked in https://github.com/rancher/rancher/issues/18133

**Comment by westlywright** [comment]
QA: 
Set up a new cluster with default etcd backup options.
Performing a backup.
Navigate to cluster level backups page

Verify the state badge is now present on the page.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Confirmed issue.
The state badge now exists on the cluster etcd backups page.

Additional smoke testing:
Opened two windows. One to do backup from (clusters), one to watch backup page update with new entry.
Confirmed the window updates with new entry (websocket).
Restored from recent backup; ensure this is working as expected. Backups page updates indicating Cluster is currently Updating (websocket). Encountered no issues with any testing.
