### ISSUE TITLE
Can not upgrade multi cluster app with external auth member because of api error

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#18252]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Ensure that github auth is enabled.
2. Logout as the local user.
3. Log in to rancher as the github user you turned rancher auth on with.
4. Create a multi-cluster app with another github user added as a member owner.
5. Log out of rancher.
6. Log in to rancher as the default admin user.
7. Select "upgrade" for the app that has the additional github user added as a member
8. Select the "upgrade" button, it is no required to change any details because simply having the "github_user" member present will cause the error

**Result:**
The Api sends a 500 and the user is presented with the following error from the `/v3/multiClusterApps` api
`user.management.cattle.io "858614" not found`

**Other details that may be helpful:**
I had 1 local import cluster and one GKE dev cluster. I tested this and describe the repro with github auth but didn't verify other auth providers. I am assuming the results will be the same. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): single launched with `--add-local=true`

**Comment by mrajashree** [comment]
This does not happen if you login as the github user and try upgrading right? Only if you're a local user? because that's what I'm seeing @westlywright

**Comment by westlywright** [comment]
Correct. It happens when the user can not view the principal info of the member. in this case the local user can't view the github user principal info.

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/21

* Enabled GH auth
* Created multicluster app and added a GH user as app owner
* Log in as local admin
* Upgrade the app (changed template version)
* The upgrade was successful 

Previously there would be an error that the user could not be found. 

*Note - there will still be a 500 response from the initial API request, but the initial error is being handled silently.
