### ISSUE TITLE
[Pipeline] Support Docker registry with self-signed certificate

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#18269]
Support for providing custom CA cert for GitLab when configuring a pipeline was added here: https://github.com/rancher/rancher/issues/16136.

But this custom CA cert seems to be only in effect when verifying the certificate of the Git server not that of external Docker registries (e.g. GitLab Registry) that might be used to pull and push images in any of the pipeline steps.

We should provide a way to configure pipeline with custom CA certs for both the Git and Docker registry integrations.

**Steps to reproduce (least amount of steps as possible):**
1. Set up a Docker registry with self-signed certificate
2. Add the CA root certificate to Rancher server container, following the [instruction](https://rancher.com/docs/rancher/v2.x/en/admin-settings/custom-ca-root-certificate/).
4. Configure the CA root certificate setting in project-tools-pipeline.
5. Configure a pipeline that pulls a custom base image from the private registry (`runScriptConfig`) and/or pushes the built images to the private registry (`publishImageConfig`).

**Result:**
Pipeline run fails:

```
11:11:47 Sending build context to Docker daemon 154.1kB
11:11:47 Step 1/5 : FROM private-registry.xxxxx.com/base-jboss-eap7:1.2
11:11:47 Get https://private-registry.xxxxx.com/v2/: x509: certificate signed by unknown authority
11:11:47 time="2019-02-07T11:11:46Z" level=fatal msg="exit status 1"
```

**Environment information**
v2.2.0-alpha6

gz#11043

gz#11902

**Comment by cyliu0204** [comment]
any update on this issue? how can I use private registry in the pipeline?
