### ISSUE TITLE
Admin user is not able to deploy multi app clusters in clusters that he is not owner of.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18260]
Rancher version - Build from master - Feb 19

Setup - Rancher  Server deployed in HA setup
Steps to reproduce the problem:
Enable Auth,
As regular user (non admin user) , create 2 clusters.
As admin user , try to deploy  multi app clusters app in "Default"project in both the cluster.
Multi app clusters app gets stuck in "Installing" state.
App fails to start with the following error message:

```Installing
Failed to install app mytestapp-p-g288k. Error: UPGRADE FAILED: an error on the server ("{\"Code\":{\"Code\":\"ServerError\",\"Status\":500},\"Message\":\"Forbidden 403: clusters.management.cattle.io \\\"c-tdztr\\\" is forbidden: User \\\"u-f5y24i3thh\\\" cannot get resource \\\"clusters\\\" in API group \\\"management.cattle.io\\\" at the cluster scope\",\"Cause\":null,\"FieldName\":\"\"}") has prevented the request from succeeding (get configmaps)```

**Comment by mrajashree** [comment]
This happened because you didn't provide any Roles as input to the multiclusterapp. And so we derived the creator's roles in these target projects.
Creator is the admin, who can access all resources, but is not explicitly made a member of the cluster that user created through CRTBs. So we didn't find any cluster roles for the creator; which led the app creator to not have permissions to get the clusters

**Comment by mrajashree** [comment]
Changes to the RBAC logic for addressing these
- [ ] When Roles are passed during multiclusterapp creation, if the creator of the app is a global admin, relax the API validation check; Since admins should have access to everything

**Comment by mrajashree** [comment]
Changes to the RBAC logic for addressing these

- [ ] When no Roles are passed during multiclusterapp creation, if the creator of the app is a global admin, add the clusterCreatorDefault role to set of MulticlusterappSpec.Roles
- [ ] When Roles are passed during multiclusterapp creation, if the creator of the app is a global admin, and does not have CRTBs/PRTBs in the targets, on account of being a global admin, we will relax the check in API to ensure that the admin has MulticlusterappSpec.Roles in targets
- [ ] When checking whether the creator is admin or not, don't compare against the role name "admin", check the permissions from the globalrole off of the globalrolebinding for the caller.
- [ ] If user is creating an app and no roles are passed, after deriving roles from the targets, make sure length of roles > 0

**Comment by mrajashree** [comment]
Adding one more change: A call to ensure that the caller has all roles in targets will only happen if they are editing roles

**Comment by cjellick** [comment]
or theyre creating the app, right?

**Comment by mrajashree** [comment]
@cjellick Yes, I meant while updating multiclusterapp, the check will happen only if Roles are being updated. 
Otherwise the check will continue to happen during multiclusterapp creation, and during addProjects to see if caller has access to the new projects they are adding

**Comment by sangeethah** [comment]
Tested with latest build from master . This issue is still reproducible.
Enable Auth,
As regular user (non admin user) , create 2 clusters.
As admin user , try to deploy multi app clusters app in "Default"project in both the cluster.
Multi app clusters app gets stuck in "Installing" state.
App fails to start with the following error message:


```
Failed to install app santestwordpress-p-wbbld. Error: UPGRADE FAILED: an error on the server ("{\"Code\":{\"Code\":\"ServerError\",\"Status\":500},\"Message\":\"Forbidden 403: clusters.management.cattle.io \\\"c-ss4gv\\\" is forbidden: User \\\"u-ylqlcbnino\\\" cannot get resource \\\"clusters\\\" in API group \\\"management.cattle.io\\\" at the cluster scope\",\"Cause\":null,\"FieldName\":\"\"}") has prevented the request from succeeding (get configmaps)
```

**Comment by sangeethah** [comment]
Closing this issue since the workflow mentioned in the use case of creating a MCAPP without roles which is not going to be supported in 2.2 release.
