### ISSUE TITLE
UI: Add Cluster view shows empty row when no cluster drivers are active

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#18264]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Navigate to Global->Custom Drivers->Cluster Driver and deactivate all
2. Navigate to Global->Clusters, Add Cluster

Expected:
The "Hosted Kubernetes Providers" row is not visible

Actual:

![addcluster](https://user-images.githubusercontent.com/3813921/53081118-79b6c400-34fa-11e9-869d-f3b4472bbe4e.png)

**Environment information**
- Rancher version 2.2.0-alpha6

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Confirmed fixed. I followed the steps to reproduce and now the hosted Kubernetes providers section is removed and the UI looks appropriate. (Removed GKE, AKS, EKS to do this).

![image](https://user-images.githubusercontent.com/45179589/53119024-c0f98080-350b-11e9-8c30-920f3c28b2cb.png)

I also removed Rancher RKE and Import drivers but I still see it listed in the UI so I entered a separate issue for this: #18276

**Comment by vincent99** [comment]
This is weird.. there's a 2x2 grid of sections that have logical meaning, the "User Provided" makes no sense (there isn't one for the node drivers section) and hiding sections that are empty is breaking the logical ordering.

Top row: Someone else creates & manages the cluster
Bottom row: Rancher creates & manages the cluster
Left column: From nodes that will be created for this cluster and are manageable in Rancher
Right column: From nodes that already exist and are managed externally.

https://github.com/rancher/ui/pull/2675#issue-254781433

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Retested. The "In a hosted Kubernetes provider" now stays on the screen whether or not any hosted k8s providers are selected under Drivers page for cluster.
If you add a custom pluggable driver it will show up in this area.

![image 3](https://user-images.githubusercontent.com/45179589/53124872-bcd45f80-3519-11e9-8bda-7e4282ce82dc.png)

![image](https://user-images.githubusercontent.com/45179589/53124877-c1991380-3519-11e9-91ab-347fc892feaa.png)

And here is a screenshot if we have no node drivers selected with a similar message:
![image](https://user-images.githubusercontent.com/45179589/53125269-d7f39f00-351a-11e9-8970-ffba505ac092.png)


Duplicate heading removed on Drivers page. This makes the page a bit nicer looking and we can now fit more rows on one page:

![image](https://user-images.githubusercontent.com/45179589/53124950-f6a56600-3519-11e9-8c5c-533fe547bf60.png)

A generic icon is shown for pluggable drivers:
![image](https://user-images.githubusercontent.com/45179589/53125305-f194e680-351a-11e9-9c69-3fba111f8b1d.png)

Node drivers are sorted alphabetically.
Smoke/halo tested. Tested with user with less privileges but still access to rancher. Ensured can still activate/deactivate drivers, etc. Cannot delete as expected (insufficient permission).
