### ISSUE TITLE
If deactivate Rancher RKE / Import cluster driver these are still shown on Clusters page in UI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18276]
Version: Master 2.2 (2/20/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deactivate the Import cluster driver and the Rancher RKE cluster driver
- Look at the Clusters page and Add a cluster

**Result:**
Import and Rancher RKE is still shown but should not be since we removed these drivers.
Refreshing the browser / clearing cache does not fix the issue.

**Comment by vincent99** [comment]
You shouldn't be able to deactivate them and they shouldn't show up (imported already doesn't now). 
 https://github.com/rancher/rancher/issues/19775
