### ISSUE TITLE
Importing PKS cluster fails because agent can't stat the docker socket

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#18274]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**

Import a Kubernetes cluster created with VMware PKS by applying the manifest generated by Rancher

**Result:**
Rancher node-agent pods are failing to start with following error:
> Please bind mount in the docker socket to /var/run/docker.sock

**Notes:**
PKS/BOSH nodes use a non-standard path for the Docker engine socket:
`/var/vcap/data/sys/run/docker/docker.sock`

Agent shouldn't fail here since access to docker socket is not required at all in imported cluster.

**Environment information**
Rancher 2.2-alpha6

**Comment by cjellick** [comment]
@janeczku in theory, you could overcome this by downloading and modifying the deployment yaml and bind mounting `/var/vcap/data/sys/run` to `/var/run` in the container.

Something like this:
```
wget https://rancher/v3/import/28g8khm6nt9jnnw42w9j4vqv9rh82dwqwpw8ntxr52q9xtwvs826hv.yaml

vim 28g8khm6nt9jnnw42w9j4vqv9rh82dwqwpw8ntxr52q9xtwvs826hv.yaml
# and then modify the host mount. Here's a diff of what I did:
diff --git a/28g8khm6nt9jnnw42w9j4vqv9rh82dwqwpw8ntxr52q9xtwvs826hv.yaml b/28g8khm6nt9jnnw42w9j4vqv9rh82dwqwpw8ntxr52q9xtwvs826hv.yaml
index dd4d39f73..775f796bd 100644
--- a/28g8khm6nt9jnnw42w9j4vqv9rh82dwqwpw8ntxr52q9xtwvs826hv.yaml
+++ b/28g8khm6nt9jnnw42w9j4vqv9rh82dwqwpw8ntxr52q9xtwvs826hv.yaml
@@ -184,7 +184,7 @@ spec:
           type: DirectoryOrCreate
       - name: var-run
         hostPath:
-          path: /var/run
+          path: /var/vcap/data/sys/run/docker
           type: DirectoryOrCreate
       - name: run
         hostPath:
```
If that doesn't work, you could also try specifically mounting JUST the docker socket to /var/run/docker.sock

**Comment by chipzoller** [comment]
As of Rancher 2.2.8, imported clusters created by PKS do not see the node-agent failing to start.
