### ISSUE TITLE
Can not check AD Federation SAML as button is stuck at "waiting to hear back from IDP"

### ISSUE THREAD

**Issue by ryanwaldron** [rancher/rancher#18271]
**Bug: Can not check AD Federation SAML as button is stuck at "waiting to hear back from IDP"**

![image](https://user-images.githubusercontent.com/11997459/53110009-1af84700-3508-11e9-8441-ff223409a543.png)

SAML was previously setup with federation server, and it suddenly just stopped working over a weekend. No changes have been made to the networking or the MS Federation server or Domain.

This was previously reported and supposedly solved in:

https://github.com/rancher/rancher/issues/14891

The issue still persists.

![image](https://user-images.githubusercontent.com/11997459/53110143-57c43e00-3508-11e9-89c3-c462f594f0ae.png)

**Comment by mrajashree** [comment]
@ryanwaldron Hi, if it was previously setup, did it get disabled? just curious about why you're on the test and enable page. Also can you open up developer tools and share the requests in Network tab so we can see if there's a more detailed error there?

**Comment by Bernd-Walter** [comment]
Hi,
I'm experiencing this bug as well when trying to use Okta. Is this still open?

Bernd
