### ISSUE TITLE
import should not be in the list of /v3/kontainerenginedrivers as a driver

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#18273]
will let nathan figure out the details

**Comment by nathan-jenan-rancher** [comment]
We want import driver removed from the kontainer driver resources because it makes building the UI difficult.  We need to find the best way to remove this driver or else hide it from view, while still making imported clusters work.

**Comment by nathan-jenan-rancher** [comment]
This change is removing the `import` driver from the kontainer drivers `/v3/kontainerdrivers` endpoint in Rancher API.  It should no longer be listed or accessible at that endpoint.  Importing clusters should still work as normal.

**Comment by soumyalj** [comment]
Observed in older master before the fix and observed that import driver was present in /v3/kontainerdrivers as below:
```
{
"actions": {
"deactivate": "…/v3/kontainerDrivers/import?action=deactivate"
},
"active": true,
"actualUrl": "",
"annotations": {
"lifecycle.cattle.io/create.mgmt-kontainer-driver-lifecycle": "true"
},
"baseType": "kontainerDriver",
"builtIn": true,
"checksum": "",
"conditions": [ 2 items
{
"lastUpdateTime": "2019-02-21T21:41:33Z",
"status": "True",
"type": "Downloaded"
},
{
"lastUpdateTime": "2019-02-21T21:41:33Z",
"status": "True",
"type": "Installed"
}
],
"created": "2019-02-21T21:41:32Z",
"createdTS": 1550785292000,
"creatorId": null,
"executablePath": "",
"id": "import",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"self": "…/v3/kontainerDrivers/import",
"update": "…/v3/kontainerDrivers/import"
},
"name": "import",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "kontainerDriver",
"uiUrl": "",
"url": "",
"uuid": "749db967-3621-11e9-b009-0242ac110002"
},

```
Tested with master from Feb 22nd. Observed that /v3/kontainerdrivers did not have an entry for import driver. 
Also, tested importing cluster and it was functional.
