### ISSUE TITLE
Doc- correct the version of cert-manager in HA airgap install docs

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18283]
Our HA airgap install docs relating to `cert-manager` installation is incorrect where it tells the user to use the latest cert-manager chart. In our regular HA install docs we tell the user to specify version `0.5.2`. The air gap install docs should be updated to use:
```
helm fetch stable/cert-manager --version 0.5.2
```

**Comment by tonycrotwell** [comment]
Following this. I was able to get through all the steps using cert-manager 0.5.2, however, now when I attempt to access the rancher page https://10.1.19.55:6443 I get the following:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

Did you see this using the cert-manager for Air Gap install?
