### ISSUE TITLE
Multicluster app error code 500 on invalid role

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#18281]
When creating a multi cluster app if an invalid role is provided the error returned from rancher is a 500. 

Example body to create the issue:

```
{
    "answers": [],
    "members": [],
    "name": "ddd",
    "revisionHistoryLimit": 10,
    "roles": [
        "random-thing"
    ],
    "targets": [
        {"appId": null, "projectId": "real-project", "type": "/v3/schemas/target"}
    ],
    "templateVersionId": "cattle-global-data:library-artifactory-ha-0.2.2",
    "upgradeStrategy": null
}
```

**Comment by sangeethah** [comment]
Able to reproduce the issue with master build from feb 20:

Following error seen when "null" is set for roles when creating/upgrading Multi Cluster App. 
{
"baseType": "error",
"code": "ServerError",
"message": "roleTemplate.management.cattle.io \"__-*NULL*-__\" not found",
"status": 500,
"type": "error"
}

**Comment by sangeethah** [comment]
This issue is fixed in latest master build:

Status is now set to 422 .

Following error seen when "null" is set for roles when creating/upgrading Multi Cluster App. 
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "Role __-*NULL*-__ does not exist",
"status": 422,
"type": "error"
}
```
