### ISSUE TITLE
Upgraded clusters are appearing as if they have temporary security credentials

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#18285]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an EKS cluster in Rancher 2.1.6 _without_ using a session token
2. Upgrade Rancher to `e1dabeffdcdd8f92ee9e9497e381151b277c73b3 `
3. Attempt to delete EKS cluster

**Result:**
Rancher will prompt for a new set of credentials because it thinks the previously provided ones have expired.

**Other details that may be helpful:**
Note that this issue will only appear on `e1dabeffdcdd8f92ee9e9497e381151b277c73b3 ` because it was hidden by the previous [EKS upgrade bug](
https://github.com/rancher/rancher/issues/18162).  It will only be possible to reproduce this bug on that specific commit.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `e1dabeffdcdd8f92ee9e9497e381151b277c73b3 `
- Installation option (single install/HA): Single node

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher:v2.2.0-rc2

steps:
* Create an EKS cluster in Rancher 2.1.6 _without_ using a session token
* Upgrade Rancher to v2.2.0-rc2
* Attempt to delete EKS cluster

result:
The cluster is deleted successfully and there is no prompt for credentials.
