### ISSUE TITLE
Cloud Keys minor header issue

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18287]
Version: Master 2.2 (2/20/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, Minor

**Steps to reproduce (least amount of steps as possible):**
- Look at the Cloud Keys page. For some reason the "Cloud Keys" header is not centered it is up and to the left more than other pages such as the Clusters page, Catalogs Page, etc, etc.

**Result:**
![screen shot 2019-02-20 at 3 45 48 pm](https://user-images.githubusercontent.com/45179589/53130207-d039f780-3526-11e9-8634-555c3ee29974.png)

**Comment by deniseschannon** [comment]
@tfiduccia i can't tell if @lvuch put in a PR to fix this, but can you check if it's been fixed or not?

**Comment by tfiduccia** [comment]
Version - master 4/8, UI version - v2.3.0
Verified fixed.  Changed name to Cloud Credentials and centered properly.
