### ISSUE TITLE
UI - Duplicate entries get added to the member list when member gets added to Global DNS entry/DNS procider/Multi Cluster App.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18292]
Rancher server version - Build from master - Feb 20

Set up - rancher server in HA setup with AD auth enabled.
Steps to reproduce the problem:
Log in as any valid user who has access to rancher server setup.
Create a Global DNS provider (with out any Members).
Edit Global DNS provider and search for any existing member and select in "Member" drop down.
Notice that duplicate entries get added to the member list .

<img width="1127" alt="screen shot 2019-02-20 at 4 49 31 pm" src="https://user-images.githubusercontent.com/4266958/53135521-5dce1500-3530-11e9-85d7-b0fa9851ba65.png">

**Comment by sangeethah** [comment]
This issue happens when adding members to Global DNS entry/DNS procider/Multi Cluster App.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/22/19) HA Setup
Followed steps to reproduce and tested with GDNS Entry and MC app as well. I could not reproduce with any of these after the fix.

I did find an issue when testing: When create MC app with AD Auth enabled (or not) cannot add any members when you upgrade. I entered a bug for this: #18343
