### ISSUE TITLE
[cli] Rancher cli packaging issues

### ISSUE THREAD

**Issue by marcinbojko** [rancher/rancher#18297]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature request

**Steps to reproduce (least amount of steps as possible):**
Downloading *.tar.gz and unarchiving cli requires some non-standard approach in batch/shell/ansible/puppet/whatever modules, as rancher is tared and gzipped with /./ folder

```
/./rancher-v2.2.0-rc9/
```

**Result:**
Standard approach require more 'flattening' this tree during unarchiving.

**Expected**
Get rid of /./ during packaging of rancher.
or
Provide uncompressed executable (like some other packages)

**Comment by superseb** [comment]
Changing this would break current implementations, so that would mean a transition to something different. I don't see a blocking issue as tar includes a strip parameter, and those can be used in every wrapper that uses tar.

Let me know if you see a blocking issue for the current archive method.
