### ISSUE TITLE
Provide used rke version in rancher-release/ui

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#18299]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Trying to add rke-features like private-registries to new clusters in rancher-ui via yaml-config.

**Result:**
Fails because feature is not supported...

**Other details that may be helpful:**
It would be very helpful to know which version of rancher correlates to which rke-version..

regards,
strowi

**Comment by superseb** [comment]
See each release https://github.com/rancher/rancher/releases/tag/v2.1.6 and https://forums.rancher.com/t/rancher-release-v2-1-6/13148
