### ISSUE TITLE
Failed to find system images for version v1.11.6-rancher1-1

### ISSUE THREAD

**Issue by stenwt** [rancher/rancher#18300]
I'm attempting to build a new cluster with Kubernetes version 1.11 on VSphere. This fails with: 

Failed to find system images for version v1.11.6-rancher1-1

If I look at https://hub.docker.com/r/rancher/hyperkube/tags/ there's no image named "rancher1-1", only "rancher1". If I go to select a Kubernetes version from the drop-down when I go to build my cluster, my options are v1.11.6-rancher1-1, v1.12.4-rancher1-1, v1.10.12-rancher1-1, v1.9.7-rancher2-2, none of which exist. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.6` UI: `v2.0.67` |
|Access|`` `admin`|
|Route|`global-admin.clusters.index`|

**Comment by stenwt** [comment]
I hit this issue repeatedly with both custom metal clusters and vmware clusters, but only when I was using 2.1.6:latest. I do not experience the issue on 2.1.6:stable.

**Comment by JohnDavidLarsen** [comment]
May be coincidence, But I ran into this issue a little after I upgraded and rebooted. Discovered that my docker actually launched the previous version of rancher/rancher on boot instead of the new one. docker rm -f old  and docker start new fixed it.
