### ISSUE TITLE
default Rancher install results in use of weak TLS cipher suites and protocols and sub-optimal security assessment

### ISSUE THREAD

**Issue by canariecaf** [rancher/rancher#18308]
The docker container built for Rancher results in use of weak ciphers and TLS protocols. The Rancher container component would benefit from having user managed TLS and cipher suite settings to ensure an evergreen/futureproof container vis-a-vis TLS settings that can be easily updated and tuned to a sites needs (within reason).

At this time these cipher suites are declared week by SSLLabs:
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)   WEAK
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)   WEAK
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)   WEAK
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)   WEAK
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (0xc012)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK     112
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   WEAK 

and cannot be disabled in the docker container.

A related issue about TLS settings can be found here: https://github.com/rancher/rancher/issues/15885  but is limited to TLS1.0 adjustments. It's great that the TLS1.0 adjustment is happening and recommend an approach to enable sites to configure things as opposed to await for the next large release for security posture updates. This would help offload security adjustments from the dev team and allow users in the field to self manage their settings.

If there is guidance on where ciphersuites and tls protocols could be remediated by us in the community and a pull request offered, it is welcomed. Thanks!

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
Configurable TLS and cipher suites is going to be added in https://github.com/rancher/rancher/issues/15885. Until then, you need to front Rancher and configure it there.
