### ISSUE TITLE
"ssh connection refused" using rancher External Service and LB

### ISSUE THREAD

**Issue by luisgtz** [rancher/rancher#1830]
I am trying to setup a load balancer to redirect ssh call from port 443 to port 29418 using and external service on rancher but every time that  I try to ssh using my local ip (ssh -T -i ~/.ssh/id_rsa -p 443 user@<local_ip>) I get connection refused.

System detail:
Ubuntu 14.04 under VM with NAT network 
Docker 1.8.1
Rancher server latest 
Rancher agent v0.7.11

Adding compose files as reference:

docker-compose.yml

GerritExternalService:
  image: rancher/external-service
GerritLB:
  ports:
  - 443:29418/tcp
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - GerritExternalService:GerritExternalService
  stdin_open: true

rancher-compose.yml

GerritExternalService:
  external_ips:
  - Gerrit_IP
GerritLB:
  scale: 1
  load_balancer_config:
    name: GerritLB config

**Comment by alena1108** [comment]
@luisgtz currently Rancher LB doesn't have support for SSL. Its going to be added soon:

https://github.com/rancher/rancher/issues/1251

**Comment by deniseschannon** [comment]
@luisgtz SSL has been added in for load balancers. If you still have issues with using SSL, please re-open.

**Comment by vincent99** [comment]
You seem to be conflating SSH and SSL... SSH to port 443 doesn't make any sense.
