### ISSUE TITLE
'Kubernetes version' showing v1.12.5 and v1.13.1 versions as 'experimental' on Rancher UI while creating clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18306]
**What kind of request is this:** bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch Rancher server- v2.1.7-rc2
2. Click on Add Cluster.

**Expected Result:**
v1.12.5-rancher1-1-1 and v1.13.1-rancher1-1-1 should not be shown as 'experimental'

**Actual Result:**
v1.12.5-rancher1-1-1 and v1.13.1-rancher1-1-1 are shown as 'experimental'

<img width="1037" alt="screen shot 2019-02-21 at 9 25 22 am" src="https://user-images.githubusercontent.com/26032343/53189261-ecd43f00-35bb-11e9-83cd-004fca3d2c1f.png">

**Environment information**
- Rancher version: rancher:v2.1.7-rc2

**Comment by westlywright** [comment]
Available in UI tag `2.1.21`

**Comment by alena1108** [comment]
Fix is available in rancher `v2.1.7-rc3`

**Comment by sowmyav27** [comment]
verified in rancher v `v2.1.7-rc3`

`v1.12.5-rancher1-1-1` and `v1.13.1-rancher1-1-1` are not shown as 'experimental'. 

<img width="1507" alt="screen shot 2019-02-25 at 11 01 11 am" src="https://user-images.githubusercontent.com/26032343/53361528-d5af8d00-38ec-11e9-8b4f-22b2078c0e47.png">
