### ISSUE TITLE
json response from proxy are not compacted

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18301]
Step to reproduce:
1. start rancher server(version: v2.2) with audit log enable 
--audit-log-path=/etc/var/log/new-api-audit.log --audit-level=3 --audit-log-maxage=1  --audit-log-maxsize=100 --audit-log-maxbackup=5
2. access configmap use the proxy URL https://localhost:8443/k8s/clusters/local/api/v1/namespaces/default/configmaps
3. will get audit log like below picture, the json response is not compacted
![image](https://user-images.githubusercontent.com/5936271/53177279-b41f7e80-362a-11e9-950d-6975d209e9c3.png)

**Comment by rootwuj** [comment]
Version -2.2 master 02/22 
This version of json response is compressed
Verified fixed
