### ISSUE TITLE
User added before upgrade of Rancher from v2.1.7-rc2 to master, is not able to list Catalog Apps

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18318]
**What kind of request is this:** bug

**Steps to reproduce:**
1. Launch Rancher v2.1.7-rc2.
2. Create cluster. Add rancherdev github user as owner of the cluster.
3. Upgrade Rancher to master build (latest).
4. Go to Catalog Apps and click on 'Launch'.

**Expected Result:**
A list of Catalog Apps should be seen by the user.

**Actual Result:**
No Catalog Apps are seen and message 'There are no compatible templates.' is displayed on the UI.

<img width="1676" alt="screen shot 2019-02-21 at 3 18 56 pm" src="https://user-images.githubusercontent.com/26032343/53208571-23c24900-35ec-11e9-9bc9-4462d8e52871.png">

**Note:**
Users created after the upgrade are able to see the list of Catalog Apps.

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.1.7-rc2 to master
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type: DO
- Kubernetes version (use `kubectl version`):

```
v1.12.5
```

**Comment by mrajashree** [comment]
Even admins are able to see the templates after upgrade.

**Comment by sowmyav27** [comment]
verified on `rancher:master` (02/25/2019)

User added before upgrade of Rancher from v2.1.7-rc3 to master, is able to list Catalog Apps.

<img width="1346" alt="screen shot 2019-02-25 at 11 41 18 am" src="https://user-images.githubusercontent.com/26032343/53363851-663c9c00-38f2-11e9-983a-8b0cbbaa755d.png">
