### ISSUE TITLE
Monitoring - Catalog apps for cluster monitoring is not removed after disabling cluster monitoring

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18315]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- provision an AKS/EKS cluster
- enable the cluster monitoring
- after the monitoring is active, disable it

**Result:**  
- the catalog app `monitoring-operator` is not removed after disabling cluster monitoring
<img width="1042" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53204865-f379ab00-35e9-11e9-9fc3-a86413def40e.png">

**Other details that may be helpful:**
My tests shows this issue exists for all kind of clusters. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher master 2/21
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by thxCode** [comment]
@jiaqiluo , monitoring-operator app is using for operating Prometheus deployment. This app will keep until there is not `project-level` and `cluster-level` Monitoring enabling.

**Comment by jiaqiluo** [comment]
@thxCode Thank you for the feedback. Yes, you are right, after turning off both the cluster and project monitoring, the app `monitoring-operator` is removed. 
This issue is closed as it is not a bug.

**Comment by miv** [comment]
I'm having same issue. All monitoring and alerting in Rancher has been disabled. But monitoring-operator still popup up
