### ISSUE TITLE
More meaningful message to delete the "not found" entries when saving environment member list.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1831]
Server version - V0.33.0-rc3

rancher-server with ldap authentication enabled.
Add a user - "test1" as member to any environment.
Delete this user.

Try to list the members of this environment.

Delete user - "test1" is listed as (USER not found) in the list.

Try to "save" this list ( with /without adding new members)

This action fails and following error is seen - "Identity externalIdType is invalid".

Expected Behavior:
Present more meaningful message that will let users know that they have to delete the entries that are marked as "not found" before saving.

**Comment by hibooboo2** [comment]
I believe this may be more of a ui bug as the api is returning the correct codes and doing its job. The ui needs to inform the user that users / orgs in the current list that are not found cannot be resubmitted as members.

**Comment by vincent99** [comment]
If they're an existing entry why can't I send it back you to leave it in the list whether that energy currently exists in ldap or not?

**Comment by sangeethah** [comment]
When testing the same use case on rancher server version - v0.35.0-rc4 , I see the error message being presented in a different way. Is this a new implementation ?

<img width="1456" alt="screen shot 2015-08-28 at 3 37 03 pm" src="https://cloud.githubusercontent.com/assets/4266958/9558474/f7310e36-4d9a-11e5-99d4-cc1870d75ce0.png">

**Comment by vincent99** [comment]
This was for when deleting a cert fails, but yes... actions that fail and are not otherwise caught show growl messages now.

**Comment by vincent99** [comment]
@hibooboo2 Is there a good reason why an existing identity for a user that no longer exists can't be preserved?

**Comment by vincent99** [comment]
Offline conversation.. ok, we'll change the UI to warn and delete the not-found users from the list before putting back.
