### ISSUE TITLE
Orphaned service in Rancher (Stack is removed, but containers in service are still active in hosts) 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1832]
v0.31.0

User was able to have an orphaned service. In the UI, the stack name was no longer present, but containers of the service continued to start up in the hosts. Since it is a service, deleting the containers in the host was unsuccessful as containers would re-spawn new ones. 

In the API, the service was in an active state, but the stack was in a removed state. 

This is most likely a race condition and will try to report more if it can be reliably reproduced.

**Comment by deniseschannon** [comment]
Workaround Update: If you find yourself in this situation, you can remove the service by going to the API (using the "View in API" button for the containers) and "Delete" button in the API.

**Comment by ebuildy** [comment]
I believe this is the normal behavior, Rancher will not remove container unless you explicitly ask for it.

**Comment by deniseschannon** [comment]
The intented behavior is that if a stack is deleted, all services in the stack should also be deleted.

**Comment by alena1108** [comment]
This issue is caused by a bug in our generic process management code. @ibuildthecloud ^^
