### ISSUE TITLE
Cluster stuck in "removing" state when it was deleted when in "unavailable" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18328]
Rancher Server version - Build from master - Feb 21

Steps to reproduce the problem:
Create a 1 node DO cluster.
Power down the node from DO console.
Wait for the cluster to get to "Unavailable" state.
Delete the cluster.

Cluster gets stuck in "removing" state forever with following message:
<img width="1325" alt="screen shot 2019-02-21 at 10 31 50 pm" src="https://user-images.githubusercontent.com/4266958/53224238-e6c87780-3628-11e9-8c07-06ff12a15a90.png">

**Comment by micw** [comment]
Is there a workaround to get rid of the stuck clusters?

**Comment by sangeethah** [comment]
Tested with latest build from master.

Create a 1 node DO cluster.
Power down the node from DO console.
Wait for the cluster to get to "Unavailable" state.
Delete the cluster.
Cluster gets removed successfully.

**Comment by micw** [comment]
I can confirm that my test clusters that where stuck in "removing" state got removed directly after I upgraded to 2.2.0-rc3.
Thank you very much!

**Comment by vikas027** [comment]
I am still seeing this behavior in v2.2.1 while deleting an EKS cluster

**Comment by yuvraj9** [comment]
still facing this in v2.4.8

**Comment by dipakparmar** [comment]
Removing the finalizers will remove it. 

`kubectl edit clusters.management.cattle.io/[cluster-name]` and set finalizers to `finalizers:`

If you need to see which API-Resource type/name you have in your cluster run following command

`kubectl api-resources -o wide | grep "cluster" `
