### ISSUE TITLE
Should consist label in service monitor and logging charts

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18327]
Version: v2.2.0-alpha6
Step to reproduce:
1. enable monitor
2. enable logging
3. but can see rancher logging metric
4. because of not consist label selector and endpoint name

**Comment by thxCode** [comment]
`rancher/rancher:master` has reproduced too.

**Comment by rootwuj** [comment]
Version: master 2.2 (2/25/19) Image ID: 9f599ca2647e
Confirmed fixed.
