### ISSUE TITLE
ingress doesn't work in air-gapped env using system-default-registry

### ISSUE THREAD

**Issue by adf2007** [rancher/rancher#18331]
*Describe your issue here*
rancher集群的node没有访问外网的权限，所以部署的时候需要的镜像都是从内网私有仓库拉取的。
具体方法就是修改全局的system-default-registry参数，把它改成私有镜像仓库的地址，这里比如是10.0.0.1。部署的时候没有问题，节点都能添加并部署成功。
但是后续给某服务添加ingress的时候，状态一直处于"initializing"。后来查看节点kubelet容器的日志，发现错误发生在拉取“rancher/nginx-ingress-controller:0.16.2-rancher1”这个镜像的过程。
后来通过手动拉取的方式，把“10.0.0.1/rancher/nginx-ingress-controller:0.16.2-rancher1”拉取到本地，但是仍然报错。  我后来把这个镜像tag为“rancher/nginx-ingress-controller:0.16.2-rancher1”这个名字，问题就解决了。

整个部署的过程中，其他涉及到的组件都会自动从10.0.0.1这个私有仓库拉取，只有“rancher/nginx-ingress-controller:0.16.2-rancher1”这个镜像不会从私有仓库拉取，还是从docker官方网站拉取。

所以bug就是：修改系统默认仓库这个功能，做得不够彻底。没有覆盖到添加ingress这个功能。

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.6` UI: `v2.1.19` |
|Route|`ingresses.index`|

**Comment by xiaoluhong** [comment]
I didn't reproduce your question. Can you reproduce it? Or is there a corresponding screenshot?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
