### ISSUE TITLE
Backend should not allow us to create MC app with multiple of same projectid

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18335]
API for #18241 

Backend should not allow us to create a MC app with multiple targets of same projectid

**Comment by sangeethah** [comment]
Tested with latest build from master:

Using API UI , create a MCApp by providing 2 targets with the same project Id.

API errors out with following:

``
{
"baseType": "error",
"code": "ServerError",
"message": "duplicate projects in targets c-9gqn9:p-wwh9t",
"status": 500,
"type": "error"
}
```
We should be using an error code other than 500 in this case.

**Comment by sangeethah** [comment]
Tested with latest build from master:
When attempting to create MC app with multiple targets pointing to same projectid , API returns 422 error code as expected.
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "duplicate projects in targets c-ftgzf:p-gtqnk",
"status": 422,
"type": "error"
}'```
