### ISSUE TITLE
Enable project monitor not display correctly

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18330]
Version: master
Reproduce step:
1. click enable monitor in default project
2. go to system project or other project not enable monitor, in enable system project page will find that the UI show monitoring enable in this page
@loganhz

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/27/19)
Confirmed issue.
I can no longer reproduce. Enable project-level monitoring on Default and go to System project and it is not enabled there.

I smoke tested this area tried with cluster-level monitoring on and off, etc. I could not identify any issues.
