### ISSUE TITLE
Should enable validate fluentd ssl ca and hostname for test function

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18332]
Server version: master
Step to reproduce:
1. config fluentd logging target with ssl config
2. ssl config input server.cert not ca.cert
3. click test function, it validate success
4. but fluentd throw error with the ssl certificate config
5. the test function should not return validate success when ssl use server.cert

**Comment by kingsd041** [comment]
Version: master 2.2 (2/28/19) 
Confirmed fix. 
- Use the wrong hostname, click TEST, verify failure and prompt error message `tls handshake michelia.cnrancher.com:24224 failed: x509: certificate is valid for michelia.cnrancher.com, not michelia.cnrancher.com1`
- If the ca certificate is wrong, it will not pass the verification.
