### ISSUE TITLE
Move RootDomain to GlobalDNSProviderSpec 

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#18346]
Currently RootDomain sits under each provider config for GlobalDNSProviders, instead it should be moved out to the GlobalDNSProviderSpec since this field is present in every external-dns provider.

*UI will also need to change after this fix in API.*

**Comment by gitlawr** [comment]
Validated in master 2/25:
![image](https://user-images.githubusercontent.com/5697937/53384699-ca289880-39b6-11e9-9e41-524b23319813.png)
