### ISSUE TITLE
unable to ssh into containers running in rancher OS

### ISSUE THREAD

**Issue by swathikrishna1** [rancher/rancher#18357]
**What kind of request is this (question/bug/enhancement/feature request):**
ssh into the docker

**Steps to reproduce (least amount of steps as possible):**

[root@ip ~]# docker exec -it 3fa2b30cae02 bash
rpc error: code = 2 desc = containerd: container not found
[root@ip ~]#

**Result:**

**Other details that may be helpful:**
docker version

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Environment information**

Rancher OS
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

DISTRIB_ID=RancherOS
DISTRIB_RELEASE=v1.0.1
DISTRIB_DESCRIPTION="RancherOS v1.0.1"
NAME="RancherOS"
VERSION=v1.0.1
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.1
PRETTY_NAME="RancherOS v1.0.1"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"

- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
RancherOS v1.0.1 was released on the 27th of April 2017, my advice would be to upgrade asap. Both for security as for improvements made in the newest releases. If you still experience issues on the latest release, please file an issue with all steps to reproduce at https://github.com/rancher/os/issues
