### ISSUE TITLE
Upgrade - GKE/EKS/AKS cluster goes to "Updating" state after upgrading rancher

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18352]
Version: v2.1.6 upgraded to v2.2.0-rc2

Steps;
1. Create a GKE cluster in rancher v2.1.6. Create few workloads
2. Upgrade rancher to v2.2.0-rc2

After uprade, GKE cluster goes to upgrading state and gets updated. This is not expected after rancher upgrade.

LOgs below:

```

2019/02/22 23:20:19 [INFO] kontainerdriver googlekubernetesengine stopped
2019/02/22 23:20:19 [INFO] Provisioning cluster [c-9mb8b]
2019/02/22 23:20:19 [INFO] Updating cluster [c-9mb8b]
2019/02/22 23:20:19 [ERROR] ClusterController c-9mb8b [user-controllers-controller] failed with : failed to start user controllers for cluster c-nzwwg: failed to contact server: Get https://10.43.0.1:443/version?timeout=30s: waiting for cluster agent to connect

.....
......

.....

2019/02/22 23:20:24 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/02/22 23:20:24 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:10877
2019/02/22 23:20:24 [WARNING] could not convert <nil> MasterAuth=<nil>
2019/02/22 23:20:25 [INFO] cluster [c-9mb8b] provisioning: Updating master to 1.11.7-gke.6
2019/02/22 23:20:25 [INFO] cluster [c-9mb8b] provisioning: reconciling cluster c-9mb8b......
2019/02/22 23:20:26 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF




```

**Comment by nathan-jenan-rancher** [comment]
I believe that this issue is caused because old clusters from previous versions of Rancher are not being updated properly.  I noticed several issues in the existing code base:
1) The clusterconfigcopier.go controller is not being registered, and it therefore not copying cluster configs from the old-style AKSConfig/GKEConfig/etc to the new style GenericEngineConfig
2) The clusterconfigcopier controller is not updating the `Status.AppliedSpec` field.  Because the provisioner.go controller checks the Spec against the Applied Spec I believe this may also trigger an unnecessary update.  I attempted to update the clusterconfigcopier to also update the AppliedSpec field, but this also did not solve the issue.  Note that the applied spec is run through a special function called `censorGenericEngineConfig` designed to prevent sensitive data from leaking in the Rancher API, the Spec MUST be censored before comparing it to the applied spec, and the AppliedSpec must be censored as well before being set from the existing spec.

**Comment by jiaqiluo** [comment]
The same bug occurs on AKS,  GKE, EKS, and RKE custom clusters when upgrading Rancher from 2.1.7 to 2.2.0-rc3
<img width="1500" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/54044660-c9e58580-418c-11e9-89ab-000ed02f7bf2.png">

AKS
```
> k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
RKE Custom
```
> k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

EKS
```
> k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

GKE
```
> k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.5-gke.10", GitCommit:"d0686b9f0adfcf759cde9f1d2d80fd52ab01d58f", GitTreeState:"clean", BuildDate:"2019-02-22T20:02:13Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sangeethah** [comment]
"RKE Custom Cluster" getting to "upgrading" state after rancher server is upgraded is tracked in https://github.com/rancher/rancher/issues/18704

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher:v2.16 upgraded to master 3/12

Following the same steps as the issue describes,  in my test the GKE and EKS cluster do not go to `Updating` state anymore.
