### ISSUE TITLE
prometheus fail to start because rules-configmap-reloader hits memory limit

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#18353]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

Prometheus fail to start 
**Steps to reproduce (least amount of steps as possible):**

I'm hitting this issue https://github.com/coreos/prometheus-operator/issues/2364

**Result:**

Prometheus fail to start because `rules-configmap-reloader` fail to start (both on project-level monitoring and cluster level monitoring)

**Environment:information**
- Rancher version:

Component | Version
-- | --
Rancher | v2.2.0-rc2
Use (Interface | v2/HA):.2.3
Helm | v2.10.0-rancher9
Machine | v0.15.0-r: cher4-1

- Installation option: single install

**Cluster information**
- Cluster type: Imported (from managed digitalocean k8s)
- Machines: 3* cheap 10$ DigitalOcean
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by rvion** [comment]
![image](https://user-images.githubusercontent.com/2150990/53286650-0323fb80-3772-11e9-838f-c28f2ee71e4f.png)

**Comment by thxCode** [comment]
@rvion , a similar issue for this,  https://github.com/rancher/rancher/issues/17997. I think we can update the Prometheus Operator version to [`v0.29.0`](https://github.com/coreos/prometheus-operator/commits/v0.29.0) to fix this. 

cc @loganhz , @orangedeng , @cjellick .

**Comment by jiaqiluo** [comment]
The bug fix is validated. 
check this issue for detailed testing steps and results: https://github.com/rancher/rancher/issues/17997#issuecomment-468024851
