### ISSUE TITLE
UI for Moving RootDomain field to GlobalDNSProviderSpec

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18359]
Related backend issue: https://github.com/rancher/rancher/issues/18346

Do corresponding changes on the UI side.

**Comment by cjellick** [comment]
Maybe this should go to @loganhz

**Comment by westlywright** [comment]
@cjellick no need, when the backend is merged I can tackle it. Adding the waiting backend label though. @prachidamle will you remove the label when your PR is merged?

**Comment by prachidamle** [comment]
sure @westlywright

**Comment by gitlawr** [comment]
Validated in master 2/25.
With the API changes, I can create route53/cloudflare/alidns globaldns providers. I can edit them as expect.

**Comment by gitlawr** [comment]
Validated in master 2/25.
With the API changes, I can create route53/cloudflare/alidns globaldns providers. I can edit them as expect.
