### ISSUE TITLE
Fluentd `CA Certificate PEM` prompt message is wrong

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18354]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch fluentd logging
2. Check `Use TLS`
**Result:**
The `CA Certificate PEM` prompt message is wrong, because it is rootCA, so it should be like `xxx -----END CERTIFICATE-----`
![image](https://user-images.githubusercontent.com/19684717/53287599-61c09800-37b9-11e9-921f-6c5e24268a24.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master 02/23

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/25/19)
Confirmed issue. The helptext in this box now uses correct text indicating a certificate rather than rsa private key:

![image](https://user-images.githubusercontent.com/45179589/53360427-bca9da80-38f2-11e9-9996-0e4453b9f6b1.png)
