### ISSUE TITLE
Images in system charts are not in rancher-images.txt

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18351]
rancher/rancher:master 02/23

In each rancher release, there is an images list for all system images 

However, the images for monitoring, logging and external-dns are not in the list.

So users cannot pull and push the monitoring, logging and external-dns related images into private registry easily

https://github.com/rancher/rke/blob/master/cmd/config.go#L404
https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/k8s_defaults.go
https://github.com/rancher/rancher/releases/download/v2.2.0-rc2/rancher-images.txt
https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/prepare-private-registry/#a-collect-images

**Comment by prachidamle** [comment]
We will be using system-charts for deploying GlobalDNSProvider, we use the following image for this:
name: rancher/kubernetes-external-dns   tag: v0.5.10

**Comment by thxCode** [comment]
#### system-chart/rancher-monitoring

| image | tag |
| --- | --- |
| rancher/coreos-prometheus-operator | v0.29.0 |
| rancher/coreos-prometheus-config-reloader | v0.29.0 |
| rancher/coreos-configmap-reload | v0.0.1 |
| rancher/prom-node-exporter | v0.17.0 |
| rancher/coreos-kube-state-metrics | v1.5.0 |
| rancher/prom-alertmanager | v0.16.1 |
| rancher/grafana-grafana | 5.4.3 |
| rancher/nginx | 1.15.8-alpine |
| rancher/prom-prometheus | v2.7.1 |

**Comment by aiwantaozi** [comment]
#### system-chart/rancher-logging

| image | tag |
| --- | --- |
| rancher/fluentd | v0.1.12, v0.1.13 | 
| jimmidyson/configmap-reload | v0.2.2 |
| rancher/log-aggregator | v0.1.5 |

**Comment by loganhz** [comment]
Hi @jiaqiluo we already have an issue for rancher-image.txt

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher:v2.2.0-rc3 in the air-gap HA mode. 
All images for the monitoring features are included in the `rancher-images.txt`file.
