### ISSUE TITLE
Global DNS: Cannot change an entry target from a mcapp to projects

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18366]
**Rancher version**
master 2/25

**Steps to reproduce**
1. Create a global DNS entry `test.fqdn` using a "gapp" multiclusterapp as the target.
2. Edit the entry, deselect the mcapp target.
3. Click resolves to `Projects` and choose the Default project of a cluster.
4. Click `save`

**Result**
![image](https://user-images.githubusercontent.com/5697937/53323191-68b1ec80-3918-11e9-8a42-e36966188675.png)

There's a similar UI ticket: https://github.com/rancher/rancher/issues/17549

But I think it is also undoable from the API perspective.
We disable updating projectIds via PUT API, and require an addProject action for that purpose. When a multiclusterapp target is selected after Step 1:
1. If I try to do an PUT API that sets multiClusterAppId to empty, I get the following error:
![image](https://user-images.githubusercontent.com/5697937/53323981-90a24f80-391a-11e9-9bde-c8d17a3454ef.png)

2. If I try to call addProject action when multiClusterAppId is set:
![image](https://user-images.githubusercontent.com/5697937/53324022-b0397800-391a-11e9-87c2-85aa3efc3811.png)

**Comment by kinarashah** [comment]
@gitlawr @westlywright 
With latest change, now UI/CLI would need to explicitly pass `{"multiClusterAppId":"", "projectIds":[p1,p2]"}` in the `actionInput` when user has unselected the multi cluster app and now wants to add projects. Earlier, we were only passing `projectIds` and there was no way to decide if multiClusterAppName was edited.

**Comment by westlywright** [comment]
@kinarashah can you open a UI ticket with that info and assign it to me? @gitlawr i'll take care of the UI updates.

**Comment by westlywright** [comment]
@kinarashah sorry no need for a UI ticket, we already have rancher/rancher#17549 that highlights the problem.

**Comment by cjellick** [comment]
backend is in, im moving to-test, but maybe you need to wait for UI to properly test this one?

**Comment by sangeethah** [comment]
@kinarashah  I tried to test the fix by using "addProjects" option on a GlobalDNS entry that has a MulticlusterApp assocaited with it to remove the mcapp and add a project by doing the following:

```
HTTP Request:
HTTP/1.1 POST /v3/globalDnses/cattle-global-data:gd-2ktl4?action=addProjects
Host: santest.qa.rancher.space
Accept: application/json
Content-Type: application/json
Content-Length: 59

{
"multiClusterAppId": null,
"projectIds": [
"c-6vpvj:p-j5qnd"
]
}
HTTP Response:
HTTP/1.1 422
date: Sat, 02 Mar 2019 03:56:01 GMT
server: nginx/1.15.6
strict-transport-security: max-age=15724800; includeSubDomains
content-type: application/json
status: 422
x-api-schemas: https://santest.qa.rancher.space/v3/schemas
content-length: 184
expires: Wed 24 Feb 1982 18:42:00 GMT

{
"baseType": "error",
"code": "InvalidOption",
"message": "cannot add projects to globaldns as targets if multiclusterappID is set cattle-global-data:hello123",
"status": 422,
"type": "error"
}
```

Is passing `"multiClusterAppId": null`  OK ? Or we need to be passing "" (empty string) ?

**Comment by sangeethah** [comment]
@kinarashah @mrajashree Why are we introducing "multiClusterAppId" in addProject field ? It does not seem natural to have a "multiClusterAppId" in addProject action.  Can we instead have "addProject" action error out when the GDNS entry has a "multiClusterAppId" associated with it and provide appropriate error message to let users know that "multiClusterAppId" needs to be removed before add projects can succeed ? I understand that this will be a 2 step process for the users . But that will also ensure that the user explicitly removing  "multiClusterAppId"  before he adds a project.

@alena1108 @westlywright  ^^^

**Comment by kinarashah** [comment]
@sangeethah Talked to @mrajashree and @alena1108 Will remove the `multiClusterAppId` from the actions and UI will do first update an then call `addProjects`

**Comment by cjellick** [comment]
Move to @westlywright for UI changes

**Comment by sangeethah** [comment]
Tested with latest build from master.

When trying to add Projects to a Global DNS entry that is already associated with MCAPP , API errors out with following exception:

```
{
"baseType": "error",
"code": "InvalidOption",
"message": "cannot add projects to globaldns as targets if multiclusterappID is set cattle-global-data:mcappnew",
"status": 422,
"type": "error"
}
```

**Comment by westlywright** [comment]
The UI will allow a user to change to a project target or multi-cluster app target on edit.

**Comment by davidnuzik** [comment]
UI aspect already tested in #17549
Refer to: https://github.com/rancher/rancher/issues/17549#issuecomment-470194479
