### ISSUE TITLE
Node driver Executable won't be recognized as node-driver

### ISSUE THREAD

**Issue by mxschmitt** [rancher/rancher#18365]
In the current `master` release the node-driver binary of a custom node-driver won't be downloaded. It will result in the following error:

```
2019/02/25 07:13:08 [INFO] create kontainerdriver kd-xfxkz
2019/02/25 07:13:08 [ERROR] Returning previous error: failed to find machine driver in archive. There must be a file of form docker-machine-driver*
2019/02/25 07:13:08 [ERROR] KontainerDriverController kd-xfxkz [mgmt-kontainer-driver-lifecycle] failed with : failed to find machine driver in archive. There must be a file of form docker-machine-driver*
```

In the 2.0 / 2.1 release it was working fine without any issues and I haven't changed anything related to the node-driver binary.

I've tested it with the hetzner-ui-driver: https://github.com/mxschmitt/ui-driver-hetzner

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `dev` UI: `v2.2.3` |
|Route|`nodes.custom-drivers.cluster-drivers`|

Thank you!

**Comment by vincent99** [comment]
The error says you're trying to create a kontainer-engine (cluster) driver instead of a node driver.  (But also says `docker-machine-driver-*` so one of those 2 messages is wrong..)

**Comment by mxschmitt** [comment]
Thanks for the quick response!

Yes indeed. I've selected `Cluster Driver` instead of `Node Driver`. That fixed the issue. 👍 
But maybe adjust the error message in the logs, that would be awesome.

**Comment by cjellick** [comment]
So, the only fix needed for this issue is to fix the error message

**Comment by mxschmitt** [comment]
works as expected, should I close this issue now? 👍

**Comment by cjellick** [comment]
Yeah, sure, I'll do that.
