### ISSUE TITLE
kubectl fails to launch after rancher rollback 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18363]
Rancher version: v2.1.6 
Upgrade to v2.2.0-rc2 and rollback to v2.1.6

Steps: 
1. Create 3 node clusters [DO, GKE] in rancher v2.1.6 setup . Create new workloads/ingress in each of the clusters. 
2. Upgrade rancher to v2.2.0-rc2 . Create new workloads/ingress in each of the clusters. Create a new cluster
3. Rollback to rancher v2.1.6

After rollback, launch kubectl in any of the clusters. kubectl fails to launch with the below error:
```
No cacerts provided
command terminated with non-zero exit code: Error executing in Docker Container: 1

```

<img width="1253" alt="screen shot 2019-02-24 at 9 47 40 pm" src="https://user-images.githubusercontent.com/18536626/53316747-d9f09180-387d-11e9-9525-b2b5d9d60d1d.png">

**Comment by cjellick** [comment]
@soumyalj you rolled back by  restoring the etcd snapshot of rancher-server?

**Comment by soumyalj** [comment]
Rollback was performed using the steps below:
https://rancher.com/docs/rancher/v2.x/en/upgrades/rollbacks/single-node-rollbacks/

**Comment by sowmyav27** [comment]
kubectl fails to launch after rancher rollback for cluster types - DO, AWS, Azure

**Comment by soumyalj** [comment]
Tested with upgrade from v2.1.6 to master build from Feb 26.
* Create 3 node clusters [DO, GKE] in rancher v2.1.6 setup . Create new workloads/ingress in each of the clusters.
* Upgrade rancher to master . Create new workloads/ingress in each of the clusters. Create a new cluster
* Rollback to rancher v2.1.6

After rollback, launch kubectl in any cluster. kubectl shell was functional in all the clusters. 

<img width="1298" alt="screen shot 2019-02-26 at 9 53 02 pm" src="https://user-images.githubusercontent.com/18536626/53468922-f113b880-3a10-11e9-8bbf-11068b9a811a.png">
