### ISSUE TITLE
Re-add same node to same cluster (after node cleanup) not working

### ISSUE THREAD

**Issue by ChrisHaPunkt** [rancher/rancher#18369]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a cluster
2. Add a Node to the Cluster (we tested with 1 Node having all 3 roles)
3. Wait for the cluster to finish provisioning
4. Remove the Node from the Cluster (GUI)
5. Clean node manually (automatic cleanup not working, see below)
   1. Delete all Docker containers, volumes & images
   2. <details>
         <summary>Delete folders:</summary>
       /etc/ceph  /etc/cni  /etc/kubernetes  /opt/cni         /opt/rke         /run/secrets/kubernetes.io         /run/calico         /run/flannel         /var/lib/calico         /var/lib/etcd         /var/lib/cni         /var/lib/kubelet  
       /var/lib/rancher/rke/log         /var/log/containers         /var/log/pods         /var/run/calico
         </details>
   3. Unmount /var/lib/kubelet
   4. clean iptables
   4. Reboot node
6. Re-add the same node again to the same cluster

**Result:**

```
This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.

Failed to communicate with API server: Get https://10.62.47.30:6443/api/v1/componentstatuses?timeout=30s: waiting for cluster agent to connect
```

Kubelet container not spawning:

```
...
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
...
```

**Other details that may be helpful:**
Following things recognized:

- After node deletion in GUI, no automatic cleanup process started as mentioned in [the docs here](https://rancher.com/docs/rancher/v2.x/en/admin-settings/removing-rancher/user-cluster-nodes/#removing-a-node-from-a-cluster-by-rancher-ui)
- The node is removed from GUI, but seems still present in API 
![unbenannt](https://user-images.githubusercontent.com/4389395/53338625-76f60d80-3904-11e9-9687-0523bb73009a.jpeg)

- After deletion of the node in GUI, the following error appeared in rancher logs: 
```
2019/02/25 10:21:07 [ERROR] NodeController c-hpql5/m-3e09727abeeb [user-node-remove] failed with : failed to remove finalizer on c-hpql5:m-3e09727abeeb
```
-  Re-add a node with the same hostname (vvm6349) fails with above error, Re-add a node with a different node-name succeeds (--node-name test1 ). Adding the host afterwards with the first hostname (vvm6349) succeeds. Wrap up: 
    - add vvm6349 -> rem vvm6349 -> add vvm6349 -> fails
    - add vvm6349 -> rem vvm6349 -> add vvm6349 as test1 -> succeeds.
- Adding the refreshed node to another Cluster also succeeds

**Environment information**
- Node OS: RHEL 7

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): vm
- Kubernetes version (use `kubectl version`): 1.11.6

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by superxor** [comment]
when do we see this fixed? Its annoying to reschedule worker nodes with hostname versioning
its a major annoyance that should be fixed asap
