### ISSUE TITLE
Bug in websocket proxy could cause entire server to hang.

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1836]
Cant easily reproduce, but you'd be likely to see it if you ran all the validation tests.
It was first fixed by a reversion of websocket-proxy.https://github.com/rancher/cattle/pull/771

This issue represents it being properly fixed and the new proxy protocol code getting deployed.

**Comment by cjellick** [comment]
Original bug  that was fixed by revert: https://github.com/rancher/rancher/issues/1823

**Comment by aruneli** [comment]
Verified proxy protocol fix in v0.34rc2
