### ISSUE TITLE
logging target fluentd generate wrong client cert config

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18374]
Server version: v2.2.0-rc2
![image](https://user-images.githubusercontent.com/5936271/53353684-3e841d00-3960-11e9-9c10-ac441ed40271.png)
Should be 
tls_client_cert_path 
tls_client_private_key_path

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/27/19)
Confirmed issue. This is now working as expected per the comments here and the PR:
![image](https://user-images.githubusercontent.com/45179589/53508510-20f5a700-3a77-11e9-9125-c11ed30277d6.png)

When I submit the customTarget and customTargetConfig look correct. content string looks correct.
