### ISSUE TITLE
Move top-level GDNS and MCApp to under a tools menu item

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#18378]
As the title says. These items should be sub-menu items

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/28/19)
Confirmed issue. Multi-Cluster Apps, Global DNS Provider, Global DNS Entries were moved to under a Tools menu at the global menu.
![image](https://user-images.githubusercontent.com/45179589/53606038-9a27f380-3b76-11e9-8b1a-2f7d5619b1d1.png)

I entered a related bug around this to request some changes: #18487
