### ISSUE TITLE
Custom host containers are not transfered to hosts on the same infrastructure.

### ISSUE THREAD

**Issue by shakisha** [rancher/rancher#1837]
I have got 3 hosts:

host1.dev  with 5 custom made containers and more than 20 images 
host2.dev  with 0 containers
host3.dev  with 0 containers

now, i went to a container in host1 and i have clicked on "clone", putting in advanced option scheduling on host2.dev

but immediately after i see the cloning as failed, for this reason :
 7a781c9-5775-4919-b260-097af1681865 : Invalid repository name

**Comment by vincent99** [comment]
There is no mechanism to copy images from host to host.  The images need to be in a configured public or private registry.

**Comment by kawa636r** [comment]
So, when adding a new host, should i configure private registry also on that ? (even if the server has already it's own private registry configured?)

**Comment by vincent99** [comment]
User menu in the top-right -> Registries -> Add.  You only have to configure it once, not once per-host.

![image](https://cloud.githubusercontent.com/assets/753917/9373341/3efe8a12-469e-11e5-81d8-28f68bf1d9f7.png)

**Comment by kawa636r** [comment]
How i can handle insecure docker host here? 

i have created as docker instructions (https://docs.docker.com/registry/insecure/) , so i went into custom, and i've put an address and an email, but it stays on registering :-(

**Comment by deniseschannon** [comment]
Did you look at the Rancher instructions on insecure registries? http://docs.rancher.com/rancher/configuration/registries/

**Comment by shakisha** [comment]
oh, really nice, i didn't found it before, there is a little error here :

`Note: Whenever you restart docker on the host, you may encounter issues with Network Agent being stuck in Starting state. To workaround the issue, please reboot the issue.
`

**Comment by deniseschannon** [comment]
thanks for the docs issue. i've updated and will make a PR soon.

**Comment by shakisha** [comment]
i can collaborate on writing some blog articles or tutorials?

**Comment by deniseschannon** [comment]
Anyone can contribute to the docs: https://github.com/rancher/rancher.github.io

If you're interested in blogs/tutorials, I can have our marketing person contact you.
