### ISSUE TITLE
Multi-Cluster App UI: %pagination.roles% not counting higher than 1

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18373]
Version: Master 2.2 (2/25/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create any MC App
- Add any one role
- Add another role for a total of two
- Remove one of the two roles

**Result:**
When you add any one role you will get text in the UI (%pagination.roles%) indicating you have picked "1 Role". 

If you then add one or more additional roles this is no longer shown in the UI so we no longer see our count of roles chosen (which I presume is what %pagniation.roles% is for).

If you have two roles and remove one so you only have 1 role listed you still won't see the %pagination.roles% still.

**Comment by vincent99** [comment]
While you're there this should have been `pagination.role`.  Every other key is singular.

**Comment by davidnuzik** [comment]
I'm still seeing the oddity we discussed where this shows up sometimes but not always.
Master 2.2 (2/26/19) pulled 9:30AM ImageID: 1a8f0f17c606
Fresh incognito browser, cache disabled, latest Chrome

How to reproduce:
- Create a new MC app
- Open Roles section and add any member. %pagination.role% suddenly appears
- Add a second role of any type and %paginataion.role% disappears
- Remove it and it's still gone
- Remove them all so you are back at zero. Add another role of any type again and %pagination.role% appears again.

Screencast showing the issue:
https://vimeo.com/319941980

**Comment by westlywright** [comment]
@davidnuzik I think this can be closed now that the component was redesigned and doesn't show the component that would have displayed this label in the first place.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/11/19) HA Setup
This area has been redesigned and thus this is no longer an issue. I am closing this issue.
![image](https://user-images.githubusercontent.com/45179589/54147868-56dc4900-43f0-11e9-87b5-c9ba9bff3544.png)
