### ISSUE TITLE
Rancher logging to elastic doesnt support passwords with special characters

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#18389]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. enable logging with elastic search
2. configure with user that has special characters in their password

**Result:**
enabling log exporter fails

**Other details that may be helpful:**
rancher/rancher:v2.1.3

```
{"log":"2019-02-25 13:54:20 +0000 [warn]: #0 failed to flush the buffer. retry_time=8 next_retry_seconds=2019-02-25 13:54:20 +0000 chunk=\"582b7ed065a06ad08bff99637b74457 f\" error_class=URI::InvalidURIError error=\"bad URI(is not URI?): https://abuser:password#@elastic.example.com:3602\"\n","stream":"stdout","time":"201 9-02-25T13:54:20.507771327Z"}
```

**Comment by orangedeng** [comment]
We should change the fluentd configuration using user/password block instead of adding them to the elastic url.

**Comment by kingsd041** [comment]
Version: master 2.2 (3/7/19) 
Confirmed fix. Config with a password with special characters, for example: `Please@ChangeM#e`. ES starts successfully and can receive logs

We now change the configuration of fluentd using the user/password block, I can verify it in the configuration of rancher-logging-fluentd secrets
```
  <match  c-npj2v:p-q6f22.** project-custom.c-npj2v:p-q6f22.** > 
    @type copy
    <store>
      @type elasticsearch
      include_tag_key  true
      user elastic
      password Please@ChangeM#e
      hosts https://xxx.xxx.com:9200  
      ……

```
