### ISSUE TITLE
Manually running Pipeline appears to connect gitlab timeout error

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#18387]
I manually run Pipeline and I get an error connecting gitlab repo timeout. The picture is as follows, I initially suspected the root size of my repo, my repo storage size is 1G

![](https://image-1251900790.cos.ap-chengdu.myqcloud.com/image/1.png?q-sign-algorithm=sha1&q-ak=AKID6wXdmw8NIclgQaC6UAbGTKEY1qVExlwW&q-sign-time=1551148139;1551149939&q-key-time=1551148139;1551149939&q-header-list=&q-url-param-list=&q-signature=baf294875395691e0bbbbbf30d65503e86e71e33&x-cos-security-token=bc333018809a869b2d29d040f068b4dd25b2fa6210001)

@gitlawr 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.6` UI: `v2.1.19` |
|Route|`global-admin.clusters.index`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/20191
