### ISSUE TITLE
Syslog target use empty certificate `TEST`

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18388]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**precondition:**
Syslog server has certificate verification enabled

**Steps to reproduce (least amount of steps as possible):**
1. Configure the syslog logging target
2. Click on `Use TLS`
3. The certificate is empty, click `TEST`
**Result:**
Return to Setting validated, but I can see the error log on the syslog server.
```
rsyslogd: gnutls returned error on handshake: An unexpected TLS packet was received.  [v8.34.0 try http://www.rsyslog.com/e/2083 ]
2019-02-26T02:33:00.599755+00:00 7ee7c56258ff rsyslogd: gnutls returned error on handshake: An unexpected TLS packet was received.  [v8.34.0 try http://www.rsyslog.com/e/2083 ]
```
When the entered certificate is empty, it should return some logs about the authentication failure.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master 2/25

**Comment by aiwantaozi** [comment]
Hi @kingsd041 this should be fixed, could you check?

**Comment by aiwantaozi** [comment]
Duplicated with https://github.com/rancher/rancher/issues/18470
