### ISSUE TITLE
Global DNS: UI shows no access in entry target when the user has the access

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18392]
**Rancher Version**
master 2/25

**Steps to reproduce (least amount of steps as possible):**
1. Log in as the default admin.
2. Create a Global DNS provider and a DNS entry.
3. Do a browser refresh on the link `https://server-url/g/dns/entries/index`, The Entries page shows as expected:
![image](https://user-images.githubusercontent.com/5697937/53392268-dcfd9600-39d3-11e9-975e-c7bb28f1b328.png)
4. Click on the top navigation bar `Global DNS - Providers`.
5. Click on the top navigation bar `Global DNS - Entries`.

**Result:**
Now in the entry target, the project ID is displayed, with the "no access" message:
![image](https://user-images.githubusercontent.com/5697937/53392412-41205a00-39d4-11e9-8f5e-d5124c77bb47.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/5/19) (Single-node and HA Setup both tested)
Confirmed issue. I carefully followed the steps to reproduce on a fresh browser with clean cache and could not reproduce the problem.
