### ISSUE TITLE
"InvalidFormat : Token malformed after retrieval." error when trying to get adminclient.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1839]
Server version - Build from mater -Aug 19

Not able to get admin client using apikey and secret key.

Following error returned:

E   ApiError: (ApiError(...), "InvalidFormat : Token malformed after retrieval.\n{'status': 400, 'detail': None, 'message': u'Token malformed after retrieval.', 'code': u'InvalidFormat', 'actions': {}, 'id': u'65ae6815-6f03-4447-9332-f57e0bcadfd3', 'links': {}, 'type': u'error'}")

**Comment by will-chan** [comment]
If this only occurs during upgrade and the fix is to re-generate the keys, we don't need to fix this for the release.

**Comment by hibooboo2** [comment]
This occurs whenever an apikey for a user who has logged in with github is used. re generating keys does not fix this bug.

**Comment by sangeethah** [comment]
This issue is not seen anymore on the latest server and we are able to start run validation tests on github auth enabled setup which uses user API keys.

Also tested with server build - v0.34.0-rc2. We are able to get authenticated successfully multiple times using the user api keys by setting api.auth.jwt.token.expiry to 5000 (5 secs).
