### ISSUE TITLE
The splunk logging target UI issue

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18397]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Rancher version:** rancher/rancher:master 0226

**Steps to reproduce (least amount of steps as possible):**
1. Configure splunk logging
2. Enable `SSL Verify` and enter the CA Certificate
3. Click on `TEST` or `SAVE`

**Result:**
After clicking `TEST` or `SAVE`, the page will slide up

Before clicking the button:
![image](https://user-images.githubusercontent.com/19684717/53400294-8058a600-39e8-11e9-9e49-ae6a084fc99a.png)

After clicking the button:
![image](https://user-images.githubusercontent.com/19684717/53400337-96666680-39e8-11e9-808c-f21b347b5321.png)

**Comment by n313893254** [comment]
related issue: https://github.com/rancher/rancher/issues/17782

It is SSL config being clear made the page slide up.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/28/19)
Confirmed issue. Test with both Elasticsearch and Splunk and when click save and test page no longer slides upwards.
