### ISSUE TITLE
Can not update alertmanager.yaml to Alertmanager config

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#18398]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**
1. spinning up a GKE cluster.
2. Add an alert group. 
3. Check the alertmanager.yaml and Alertmanager status. 
![image](https://user-images.githubusercontent.com/18737885/53403401-8ea9c080-39ee-11e9-8506-dcc21ce67713.png)

![image](https://user-images.githubusercontent.com/18737885/53403424-9a958280-39ee-11e9-82db-3fae4ad93cec.png)

**Result:**
Alertmanager Config lack of the alert rule.

**Other details that may be helpful:**

I change `slack_api_url: slack_api_url` to `slack_api_url: https://hooks.slack.com/services.....`. The alertmanager.yaml can update to Alertmanager config.

**Comment by rootwuj** [comment]
Version: master 2.2 (2/27/19) Image ID: 89502a3aea80
Confirmed fixed.
