### ISSUE TITLE
In order to consist advance mode ssl config in UI need to upgrade fluentd version

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18396]
Related UI: https://github.com/rancher/rancher/issues/18374
Fluentd version before 1.3.1 can't support add client cert for fluentd output, so in the logging target fluentd UI we can't support client cert, in order to make the UI consist with other target, we can upgrade fluentd

**Comment by kingsd041** [comment]
I need to wait for the https://github.com/rancher/rancher/issues/18476 verified to pass before I can verify this issue.

**Comment by kingsd041** [comment]
Version: master 2.2 (3/5/19) 
Confirmed fix. Fluentd has been upgraded to fluentd-1.3.3. I tested the project-level and cluster-level fluentd logging targets separately, and in this release already support verifying client certificates.
