### ISSUE TITLE
Upgrade - EKS - Fail to update  existing EKS cluster after upgrading Rancher to v2.2.0-rc2

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18390]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher 2.1.6
- add an EKS cluster
- upgrade Rancher to v2.2.0-rc2
- Edit the EKS cluster
- The first step is to choose the version of K8s, the default value is 1.10, and the only option is 1.11
- choose k8s 1.11, and leave the rest unchanged to finish the edit process.
![screenshot](https://user-images.githubusercontent.com/6218999/53388818-e6dab700-3949-11e9-9bef-168dc2dfbc2e.png)

**Result:**
The cluster is stick in the updateing state, and Rancher shows an error message.
```
InvalidParameterException: unsupported Kubernetes version update from the current version, 1.11, to 1.11 
status code: 400, request id: 923d63af-397e-11e9-beba-59a2fd494d5f
```
![screenshot](https://user-images.githubusercontent.com/6218999/53388988-9d3e9c00-394a-11e9-9841-7e3f26e80d45.png)

**Other details that may be helpful:**
1. the cluser on AWS console is still in active state
2. no matter changing the k8s version or not, the upgrading always fails on the same error
3. Editing the cluster in Rancher again will take no effect
4. This is the k8s version of the EKS cluster on Rancher v2.1.6
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
upgrade from v2.1.6 to v2.2.0-rc2
- Installation option (single install/HA):
single install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
17.6.2
```

**Comment by jiaqiluo** [comment]
It is interesting that even though the UI shows the cluster is `updating` and has an error message, I can check the cluster, deploy workloads, run Kubectl, etc. 
<img width="1434" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53437034-cf3b1700-39b9-11e9-943f-58cfa4c2429a.png">

**Comment by cjellick** [comment]
@jiaqiluo before you did the upgrade, was the version (via kubectl) of k8s 1.10 or 1.11?
I mean, I see the version is 1.11, so does that mean it was never actually 1.10 or that it did do the upgrade but then tried again for some reason and failed?
```
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jiaqiluo** [comment]
@cjellick  This is the k8s version of the EKS cluster on Rancher v2.1.6
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Also the error message says upgrading from 1.11 to 1.11 which makes no sense, right?

**Comment by jiaqiluo** [comment]
The bug is reproduced when updating Rancher from v2.1.7 to v.2.2.0-rc3 in HA installation mode.

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher:v2.16 upgraded to master 3/12

Following the same steps as the issue describes, I get two observations:
1. when editing the EKS cluster, the default value is 1.11, and the only option is 1.11
2. The EKS cluster's state will stay `active` if I change nothing during the editing process
