### ISSUE TITLE
Syslog logging advanced mode does not automatically remove `client_key`

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18394]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Configure Syslog target Advanced mode
2. `Client Private Key` adds the key, then it will automatically add `client_key /fluentd/etc/config/ssl/project_c-bmb99_p-vzlpr_client-key.pem` in `Edit as a Form`
3. Clear the certificate added in `Client Private Key`
**If it cannot be reproduced, please re-operate Step 2 and Step 3**

**Result:**
`client_key /fluentd/etc/config/ssl/project_c-bmb99_p-vzlpr_client-key.pem` in `Edit as a File` is not automatically cleared

The same bug exists at the project level or cluster level

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master  02/26

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/28/19)
Confirmed issue. When I test now if I enter anything in any of the certificate fields (Client Private Key, Client Certificate, CA Certificate PEM) the appropriate entry will be added to the Edit as File text editor as pictured here:
![image](https://user-images.githubusercontent.com/45179589/53598356-be2d0a00-3b61-11e9-998e-b7371ec34865.png)

As soon as I remove my text in each certificate text box so they are null again the entries are immediately removed from the Edit as File text editor as pictured here:
![image](https://user-images.githubusercontent.com/45179589/53598389-d6048e00-3b61-11e9-9c3b-a4f2988e4a48.png)

This add/remove action happens immediately and I was not able to break it. This appears to be working correctly now.
