### ISSUE TITLE
Abilitiy to use dry run to verify ssl certitificate,

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18395]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Prerequisites:**
Syslog server enables certificate verification `StreamDriver.AuthMode="x509/certvalid"`

1. Click `Edit as File` in the syslog logging target.
2. `Edit as a Form` enter the following configuration and the `SSL Configuration` setting is empty
```
<match *>
  @type remote_syslog
  host X.X.X
  port 60514
  severity notice
  protocol tcp
  packet_size 65535
  verify_mode 0
  tls true
  slow_flush_log_threshold 40.0
</match>
```
3. Save Settings

**Result:**
When `SSL Configuration` is empty, the certificate will fail to be verified. There is no error log for authentication failure in fluentd, which will confuse users.

**Environment information**
- Rancher version: rancher/rancher:master

**Comment by aiwantaozi** [comment]
Dry run does not verify ssl certitificate, it call fluentd binary to dry run the configure.
