### ISSUE TITLE
Labels for cluster

### ISSUE THREAD

**Issue by henres** [rancher/rancher#18402]
Hello,

Is it possible to add labels to cluster for easy filtering, like in gke ?

Form gke cluster creating form :
```
To organize your project, add arbitrary labels as key/value pairs to your resources. Use labels to indicate different environments, services, teams, and so on.
```

Thanks in advance.

Henri

**Comment by henres** [comment]
Ok, just looking on latest version. It's possible in rancher 2.2.0. Thanks rancher !

**Comment by henres** [comment]
Finally, i reopen, because, labels not displaying in cluster list in rancher.
And the search doesn't use them. 
I would like to have this feature, if possible.

**Comment by loganhz** [comment]
Thanks for the report

![image](https://user-images.githubusercontent.com/21168270/53980659-18801a80-40ce-11e9-8658-9eb1ee1085d3.png)
It will be out in 2.2. You will be able to add cluster labels for GKE
