### ISSUE TITLE
elasticsearch plain text password in logs

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#18407]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Setup elastic search.

**Result:**
Observe plain text password in /var/log/containers/fluent*

**Other details that may be helpful:**
{"log":"2019-02-25 13:54:20 +0000 [warn]: #0 failed to flush the buffer. retry_time=8 next_retry_seconds=2019-02-25 13:54:20 +0000 chunk=\"582b7ed065a06ad08bff99637b74457 f\" error_class=URI::InvalidURIError error=\"bad URI(is not URI?): https://username:plaintextpassword@secret.host.com:3602\"\n","stream":"stdout","time":"201 9-02-25T13:54:20.507771327Z"}

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.3
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
Talked to @orangedeng , he has removed it in the log. Please test it in master

**Comment by orangedeng** [comment]
This issue has been fixed in https://github.com/rancher/rancher/pull/18543. The master build should be no long logging the password.

**Comment by kingsd041** [comment]
Same reason as https://github.com/rancher/rancher/issues/18389. Closing duplicate

**Comment by loganhz** [comment]
@kingsd041 it's another issue

**Comment by kingsd041** [comment]
Version: master 2.2 (3/12/19)
Confirmed fix. 
-  Config with a password with special characters, for example, `Please@ChangeM#e`. ES starts successfully and can receive logs
- ES password will not be displayed in the fluentd log
