### ISSUE TITLE
Backup to AWS S3 is not functional

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18418]
Rancher Server: Master build from Feb 25.

Steps:
1. Create a 3 node DO cluster with all 3 roles (etcd, control, worker) along with S3 configuration
2. Create few workloads
3. Perform a backup
4. Verify if a backup is created in S3. 

Results:
 There is no backup entry in S3. Back up to S3 fails with the below error in server logs:
```
2019/02/26 19:59:41 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/02/26 19:59:41 [ERROR] EtcdBackupController c-42zw5/c-42zw5-rc4m9 [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Failed to take one-time snapshot, exit code [1]: time="2019-02-26T19:59:40Z" level=info msg="invoking set s3 service client" 

2019/02/26 19:59:41 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/02/26 19:59:41 [ERROR] EtcdBackupController c-42zw5/c-42zw5-k8v2k [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Failed to start [etcd-snapshot-once] container on host [a.b.c.d]: Error response from daemon: No such container: e925f72827c96755aaf0cc6296a56a1db245a262cf637f9fd9fdd21850313aa9

```

**Comment by moelsayed** [comment]
@soumyalj I am unable to reproduce this issue with latest master, can you please re-validate ?

**Comment by soumyalj** [comment]
Tested with master from Feb 27
Steps:

1. Create a 3 node DO cluster with all 3 roles (etcd, control, worker) along with S3 configuration
2. Create few workloads
3. Perform a backup
4. Verify if a backup is created in S3.

Back up S3 was successful. Restore was also successful.
