### ISSUE TITLE
UI: Show Global DNS Provider's root domain field as optional

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#18412]
UI ticket for this change: https://github.com/rancher/rancher/issues/17559

On the GlobalDNSProvider screen, we need to remove the * that indicates Root Domain field is required.

This field is now optional from API.

**Comment by prachidamle** [comment]
cc @cjellick @alena1108

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/28/19)
Confirmed issue.

Created GDNS Provider (route53) and I can see in UI we removed red asterisk indicating the field is required. Created provider while leaving this blank. Inspect HTTP and confirm that our route53ProviderConfig only contains our accessKey and secretKey. Inspect GDNS Provider entry in API (View in API) and confirm that rootDomain is "null".

Inspect v3/schemas/route53ProviderConfig and confirmed that only accessKey and secretKey are required: true in the API.
