### ISSUE TITLE
Error while launching Minecraft(from Helm) catalog app

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18411]
**What kind of request is this:** bug

**Steps to reproduce:**
1. Launch Rancher UI.
2. Create a cluster. Click on Catalog and enable 'Helm Stable'.
3. Go to the cluster-->Project-->Catalog Apps
4. Click on Launch
5. From the catalog list, select Minecraft. 
6. Click on launch

Scenario#1

**Expected Result:**
Application should be in `Active` state and have deployed successfully.

**Actual Result:**
Application is in `Active` state but it still says `Load balancer is being provisioned`.

<img width="1260" alt="screen shot 2019-02-26 at 10 02 32 am" src="https://user-images.githubusercontent.com/26032343/53435902-be38d880-39ae-11e9-943e-39900064a6fe.png">

Scenario#2
Click on Minecraft application, and click on 'Upgrade'. Click on 'Edit as YAML' and enter the below details and click on Upgrade.
```
---
  minecraftServer: 
    difficulty: "hard"
    eula: "true"
    ops: "AnyName"
    pvp: "true"
    type: "VANILLA"
    version: "1.13.2"
    whitelist: "AnyName,AnyName1,AnyName2"
```

**Expected Result:**
Application should be deployed successfully.

**Actual Result:**
Application is in `Deploying` state and it shows error `Pod has unbound PersistentVolumeClaims` on the UI.

<img width="1413" alt="screen shot 2019-02-25 at 5 50 35 pm" src="https://user-images.githubusercontent.com/26032343/53435966-e1638800-39ae-11e9-9cc2-f2fc02ebffc4.png">
<img width="1268" alt="screen shot 2019-02-26 at 10 11 15 am" src="https://user-images.githubusercontent.com/26032343/53435970-e3c5e200-39ae-11e9-883c-e77798fdcaa7.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version: rancher:master (02/25/2018)
- Installation option (single install/HA): single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
v1.13.1
```

**Comment by guangbochen** [comment]
Hi, @sowmyav27 for the `Minecraft` app u will need to install the persistence storage to make the pvc works and disable LB if u don't input any LB address.
Also, we don't maintain the stable chart, and it will only be upstream to the  https://github.com/helm/charts/tree/master/stable, so the user needs to figure out what are the right inputs to make the chart run correctly.
