### ISSUE TITLE
Trailing line break of a secret entered in the Rancher UI is not preserved 

### ISSUE THREAD

**Issue by jgerken** [rancher/rancher#18413]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

I stumbled upon this bug when I tried to enter a SSH private key as a secret and mount the secret into a file in a container, but it occurs with any kind of data.

1. Launch Rancher UI.
1. Resources -> Secrets -> Add secret
1. give the secret a key like `SSH-KEY`
1. enter private key in PEM format as value
1. make sure you have a trainling line break 
1. mount secret into a volume

**Result:**

The file created in the container from the secret misses the last line break. The key is used to operate on a GIT repository and due to the missing line break, the authentication was not successful. 

**Other details that may be helpful:**

A workaround for SSH private keys, is to add a line containing some text after the end of the key, e.g.

```
-----END OPENSSH PRIVATE KEY-----
xxxxx
```

For other secrets which require a trailing line break, this workaround will likely not work.

**Environment information**
- Rancher version: 2.1.6
- Installation option: single install

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24577
