### ISSUE TITLE
[QUESTION] How to access instance with Rancher cli V2.2? 

### ISSUE THREAD

**Issue by JonasMatos0** [rancher/rancher#18410]
QUESTION:
We've upgraded our Rancher and don't have API V2-beta, used by Rancher cli v0.6.13.
Rancher cli V2.2 doesn't have docker nor exec commands available. 

I can PS and see the containers with  cli V2.2, but I'm unsure on how to access the container to perform any operations. 

Can anyone help me on that? Thanks in advance. 

The following image shows the difference between V2.2 (Missing docker command) and V0.6 ( has docker command by it still pointing to /v2-beta/ url): 
![image](https://user-images.githubusercontent.com/30418115/53488327-c1929980-3a6c-11e9-8a95-aba9e9240851.png)

**Comment by JonasMatos0** [comment]
Hi, @rancherio-gh-m , can you help me clarify that question? 

Thanks in advance.

**Comment by cloudnautique** [comment]
For exec you have to go through rancher kubectl.

**Comment by JonasMatos0** [comment]
Thanks a lot @cloudnautique, that was exactly what I needed to know. 

For those who have the same question:
1 - Install Kubernetes Client: 
https://kubernetes.io/docs/tasks/tools/install-kubectl/
2 - To access an instance from an specific namespace:
2.1 - Get the POD of the instances: 
rancher kubectl --namespace=<NAMESPACE> get pods
2.2 - Access the instance bash: 
rancher kubectl --namespace=<NAMESPACE> exec -it <POD> -- /bin/bash
