### ISSUE TITLE
Even when user has exact roles for a target project , he is not able to set these roles when deploying Multi Cluster app.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18420]
Rancher Server - Build from master

Steps to reproduce the problem:
Log in to rancher server , as a regular user who has access to it.
Create a cluster.

Steps to reproduce the problem:

Add the current user to the "Default" project with "Manage Ingress" and "Manage workloads" roles.
Deploy a Multi cluster app in "Default" project with role set to "Manage Ingress" and "Manage workloads"

Multi cluster app deployment fails with following error:
`user u-4ntonnmxa5 does not have all project roles provided in project p-8pvxm`

Expected Behavior:
Creating MultiClusterApp should succeed .

**Comment by mrajashree** [comment]
I'm not able to reproduce this.

**Comment by sangeethah** [comment]
Tested with latest build from master - Feb 26

The issue mentioned in the bug is not reproducible.
When user has exact roles for a target project , he is not able to set these roles when deploying Multi Cluster app.
