### ISSUE TITLE
When multicluster app creation fails , there is no error message presented to the user.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18430]
Rancher server version - Build from master

Steps to reproduce the problem:
Create MCApp with name - say `test1`
Create another MCApp  with same name - `test1`

MCApp fails to get created with following error:
```
{"baseType":"error","code":"AlreadyExists","message":"multiclusterapps.management.cattle.io \"santestnew\" already exists","status":409,"type":"error"}
```

User is not presented with any error message and the user stays in the same create MCApp page.

Expected Behavior:
User should be presented with error message

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/28/19)
Replicated the issue. Confirmed there is now a message in the UI:

![image](https://user-images.githubusercontent.com/45179589/53597733-267aec00-3b60-11e9-87e2-79893f604ef6.png)
