### ISSUE TITLE
docker registry images published from gitlab and using deploy token are not pulled

### ISSUE THREAD

**Issue by mihai-satmarean** [rancher/rancher#18439]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a registry in gitlab
enable deploy token
add the registry as custom in Rancher
Create a workload with kubectl

**Result:**
ImagePullBackOff: Back-off pulling image in rancher workload screen

**Other details that may be helpful:**

**Environment information**
- Rancher version 2.1.6 (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install):

**Cluster information**
- Cluster type (Hosted):
- Machine type (VM) and specifications (2 CPU/ 2GB memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by Joeasaurus** [comment]
In the workload you have to tell it the name of the registry to pull from for your image. It goes in the spec as a sibling of 'containers'

```yaml
spec:
  containers:
    - ...
  imagePullSecrets:
      - name: <the registry name you saved in rancher ui>
```

**Comment by superseb** [comment]
We do this automatically when using the UI, when using kubectl you need to add it yourself as described above. Also see https://github.com/rancher/rancher/issues/13332

**Comment by mihai-satmarean** [comment]
Thanks, by the time any answer came, we already gave up rancher in favour of other software.
