### ISSUE TITLE
UI:Client key and certificate should be supported in fluentd normal mode

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18437]
**What kind of request is this (question/bug/enhancement/feature request):** feature
**Rancher version:** rancher/rancher:master 02/27

We should support the normal mode configuration client key and certificate in the UI.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/13/19)

This validates UI checks. This does not fully test from end to end.

This changes the UI form when setting up logging for Fluentd.

**_Before_** (v2.2.7 pictured, "Use TLS" checked)
![image](https://user-images.githubusercontent.com/45179589/62976663-fa7fba00-bdd1-11e9-8894-ff7c3930bb72.png)

**_After the changes_** (master-head, "Use TLS" checked, "Enabled" set for SSL Verify)
![image](https://user-images.githubusercontent.com/45179589/62976722-1aaf7900-bdd2-11e9-8edf-9844b21ae1fd.png)

I validated the fields (keys/certs field inputs) and ensured each worked as expected. Ensured read from file or copy/paste work as expected. UI HTTP/API appear correct. We do the normal JS checks to ensure cert/key format is what we expect (putting in garbage data will not work).

I was not able to identify any issues with my tests. I tried various combinations of settings I may pass. With and without ssl verify, supply or don't supply password, etc. All worked as I had expected. Again, this was not tested from end to end though.
