### ISSUE TITLE
v2.2.0-rc2  wss 500

### ISSUE THREAD

**Issue by lanmingle** [rancher/rancher#18436]
``` bash

rancher | v2.2.0-rc2
-- | --
用户界面 | v2.2.3
Helm | v2.10.0-rancher9
主机 | v0.15.0-rancher4-1

```

component.js:164 WebSocket connection to 'wss://rancher.lmlily.com/k8s/clusters/local/api/v1/namespaces/cert-manager/pods/cert-manager-7f4ff694df-rg4kt/log?container=cert-manager&tailLines=500&follow=true&timestamps=true' failed: Error during WebSocket handshake: Unexpected response code: 500

logs & exec shell

2.1.6 normal

**Comment by riaan53** [comment]
We are seeing the same error also on rancher v2.2.0-rc2 and latest master as of now. Container logs and exec is unable to connect from the UI with the same websocket error.

Running Rancher v2.2.0-rc2 in HA mode installed via Helm.
![image](https://user-images.githubusercontent.com/7716342/53568400-98583300-3b6a-11e9-9dbc-c74f42bad68b.png)

**Comment by superseb** [comment]
This is being fixed in https://github.com/rancher/rancher/issues/17028
