### ISSUE TITLE
Cannot add aws node template in master

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18431]
rancher/rancher:master 02/26

Steps:

1. Create an aws node template
2. Input the access key and secret key
3. Click next

Results:

UI sends empty accesskey to backend. So the auth will always fail

![image](https://user-images.githubusercontent.com/21168270/53470816-b7d55a00-3a9d-11e9-9d14-374a98a15656.png)
![image](https://user-images.githubusercontent.com/21168270/53470823-be63d180-3a9d-11e9-8f98-a198b70e9749.png)
![image](https://user-images.githubusercontent.com/21168270/53470870-efdc9d00-3a9d-11e9-8ae4-9a35211c6cef.png)

**Comment by davidnuzik** [comment]
This is working for me on latest master I pulled recently ImageID: 89502a3aea80

**Comment by cjellick** [comment]
Maybe "wont fix"?

**Comment by kinarashah** [comment]
yeah, @loganhz even I'm unable to reproduce this in latest master, please let me know if this still reproduces for you, marking "wont-fix" for now

**Comment by loganhz** [comment]
Fixed! I cannot reproduce it in rancher/rancher:master 02/27. Thanks all
