### ISSUE TITLE
Now the advance mode support client key and certificate, the normal mode should also support config client certificate and client key for fluentd in target

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18438]
**What kind of request is this (question/bug/enhancement/feature request):**  feature

**Rancher version:** rancher/rancher:master 02/27
Related UI: https://github.com/rancher/rancher/issues/18437

We should support the configuration of `Client Private Key` and `Client Certificate` in the fluentd logging target normal mode.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ad16795

* Created fluentd server w client cert, key, passphrase
* Created cluster
* Enabled cluster logging
* Enabled TLS and supplied client cert, key, passphrase
  * Log statements transported correctly
* Enabled TLS and supplied client cert, key, passphrase w/ validate CA
  * Log statements transported correctly with correct CA
  * Log statements would not transport correctly with an invalid CA; an error was received for OpenSSL_Connect
