### ISSUE TITLE
If a host label's *key* has any caps, its *values* are missing from container scheduling rules.

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#1844]
A UI bug. Steps to reproduce:

  0. add a Label to a host with a capital character anywhere in the Key
  0. go to create a container or service
  0. in Scheduling rules, the Key itself will appear in the dropdown (note, the name will be lowercase)
  0. the value for this key will be missing from the Values dropdown

A wild guess: Key gets lowercased, and the search for its values is case-sensitive?

Workaround:

  - don't use caps in key names ;)

**Comment by ebr** [comment]
just noticed that the values are also getting lowercased, resulting in containers not being scheduled correctly (b/c the server is unable to find a host with a specified label?)

**Comment by vincent99** [comment]
Your wild guess is correct, but the labels and values are supposed to be matched case-insensitive on the scheduler side too.

**Comment by deniseschannon** [comment]
@sonchang can you look at the scheduler? It doesn't seem to be case insensitive for certain combo.

Host Label:  Foo1 = bar1
Scheduling rules: foo1=bar1

It is unable to find a placement for the container.

**Comment by sangeethah** [comment]
Tested with server version built from master on sep 8.

Scheduler is now case insensitive. 
Label on the host was "Test1"="value1".  
The labels used when scheduling the service was for host_label affinity with value "test1=value1" . 
This results in all the containers of the service to be deployed in the host with label = "Test1=value1"


The UI issue of not being to list the values for a key which has upper case is still not addressed.

Reopening this issue to fix the UI part.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/13939769/23785be2-ef95-11e5-9524-8db5cfff1ad3.png)

**Comment by tfiduccia** [comment]
Version - master 3/22
Although you can have case sensitive labels in host, for scheduling it will be case insensitive and always show lower case.  FOO=BAR is the same as foo=bar and will only show 1 rule in scheduler.  Original bug is fixed in that it now shows all Values no matter the case associated Key.

Verified fixed
