### ISSUE TITLE
Etcd version

### ISSUE THREAD

**Issue by bgrissin** [rancher/rancher#18444]
We just performed a source code scan of Rancher 2.1.6 and found that the etcd version is rather dated.   There are medium vulnerabilities in the 3.0.14 release that are remediated in a more recent release of etcd, are there any plans to update to a more current etcd version 

One component (etcd v3.0.14) that has two known MEDIUM vulnerabilities.

enhancement/feature request:  Update to latest release of etcd 
https://github.com/etcd-io/etcd/releases/tag/v3.3.12 **

Environment information
- Latest - v2.1.6 - rancher/rancher:latest:

**Comment by superseb** [comment]
Please share what you used to scan, and the reference where v3.0.14 is found. This is the vendored etcd for v2.1.6: https://github.com/rancher/rancher/blob/v2.1.6/vendor.conf#L12

Is the scan done against single node Rancher, HA? What's the info on the cluster where it's run if HA?

**Comment by superseb** [comment]
Any update here?

**Comment by bgrissin** [comment]
The scan was a source code scan done using Blackduck.

**Comment by superseb** [comment]
Can you share more detail on what source file it was pointing to? And what date and what tag/commit was it pointing to when it was scanned
