### ISSUE TITLE
Can't remove cluster when custom drivers have been disabled

### ISSUE THREAD

**Issue by guilhem** [rancher/rancher#18446]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

* add a custom cluster driver
* create a cluster with this driver
* disable custom driver
* enable custom driver
* remove cluster

**Result:**

![screenshot from 2019-02-27 15-57-03](https://user-images.githubusercontent.com/486876/53500192-2ddfbe00-3aaa-11e9-9cf4-0dabed3fb53b.png)

**Other details that may be helpful:**

Name in CRD is generated each disable/enable
```
kubectl get kontainerdrivers
NAME                               AGE
[...]
kd-q89j2                           1h  <--- should be "aks3"
kd-rj67j                           1d  <--- should be "aks2"
rancherkubernetesengine            4d
```

In cluster:
`status.failedSpec.genericEngineConfig.driverName` it refers an old name, and it's not the same than `status.driver` which is the "good" display name ("aks3")

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2-rc2
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
AKS
- Kubernetes version (use `kubectl version`):
1.12

**Comment by cjellick** [comment]
This seems like it is missing steps in reproducing. Did you change the name or something in between steps? Did the binary change?

**Comment by daxmc99** [comment]
I wasn't able to repro this on v2.2-rc2 

Steps taken:
1. Add two identical drivers with different URLs but the same name (v2.1 & v2.2 of example driver)
2. Activate/deactivate both drivers
3. Run `kubectl get drivers` and see two separate `kd-*` values. No new `kd-*` names are generated on activate/deactivate.
4. Spin up a cluster with an example driver.
5. Observe that `kd-*` value in exampleEngineConfig 
6. Activate/deactivate both drivers 
7. Cluster removal works correctly. 

Any steps that I might be missing?
