### ISSUE TITLE
When editing node tags, "enter" deletes the 1st tag

### ISSUE THREAD

**Issue by micw** [rancher/rancher#18445]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Edit node, add a new label, enter a key and a value. Press enter while the "value" field is focussed.

**Result:**

The 1st label is removed from the list (can be repeated until all labels are gone).

**Other details that may be helpful:**

Chromium browser

**Environment information**
Rancher	v2.2.0-rc2
User Interface	v2.2.3
Helm	v2.10.0-rancher9
Machine	v0.15.0-rancher4-1

**Comment by davidnuzik** [comment]
Replicated v2.2.0-rc12

**Comment by davidnuzik** [comment]
This issue also happens in v2.1.7 taking out of v2.2 milestone.

**Comment by micw** [comment]
Not a bug because it existed in the release before? ^^

**Comment by vincent99** [comment]
Still a bug, just one that's been around probably forever so it's not going to hold up 2.2.0.

**Comment by tfiduccia** [comment]
@vincent99 - can we just please do something to fix this?

**Comment by loganhz** [comment]
Instead of removing the 1st row, it will add a new line when you press enter

**Comment by izaac** [comment]
Version: master-head (v2.3) (8/13/19)

NOTE: I reproduced in v2.2.7:

<img width="982" alt="Screen Shot 2019-08-13 at 3 37 04 PM" src="https://user-images.githubusercontent.com/27659/62983273-a087f000-bde3-11e9-9c28-6518fd5bfb96.png">

After hitting enter in the value field you can see the **beta.kubernetes.io/arch** Key and Value disappears:

<img width="977" alt="Screen Shot 2019-08-13 at 3 37 28 PM" src="https://user-images.githubusercontent.com/27659/62983286-abdb1b80-bde3-11e9-9d74-51f1fa5aae28.png">

**Validation**
This is not longer the case of master-head:

<img width="973" alt="Screen Shot 2019-08-13 at 4 00 10 PM" src="https://user-images.githubusercontent.com/27659/62983328-d3ca7f00-bde3-11e9-8ee5-8112cee2465d.png">

cc @davidnuzik
