### ISSUE TITLE
Not able to use user's access_key and secret_key with rancher compose.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1845]
Rancher compose version - rancher-compose-v0.2.5

I tried to use rancher-compose with a user's access_key and secret_key who has access to an environment to create containers using up command.

I get the following error:

 ./rancher-compose -p testranch -f dc1.yml up
INFO[0001] Creating environment testranch               
ERRO[0001] Failed to open project testranch: Resource type [environment] is not creatable 
2015/08/20 22:26:37 Failed to read project: Resource type [environment] is not creatable

Is there support for passing user's access_key and secret_key . If so , which environment will be used for deploying the service ? Currently , I don't se a way to pass the environment.

**Comment by ibuildthecloud** [comment]
We only support environment access_key/secret_key not a user.
