### ISSUE TITLE
External DNS pod sends an update for all the records every 1 minute even when there are no changes made.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18454]
Rancher server version - Build from master
Rancher server in HA setup 

Steps to reproduce the problem:

1. Create a Global DNS provider - GDNSP1 with no root domain and valid AWS credentials which has access to 2 Route53 root domains - test1.test.com and test2.test.com
2. Deploy Mcapp - mcapp1 with ingress having Global DNS annotations for host name  say - "hello1.test1.test.com" with target projects from 2 different clusters.
3. Add Global DNS entry for fqdn -"hello1.test1.test.com" pointing to mcapp1 with GDNS provider - GDNSP1.

DNS record for "hello1.test1.test.com" gets created as expected in Route53 with root domain - test1.test.com as expected.

Notice that the external DNS pod sends an update for all the DNS records every 1 minute even when there are no changes made.

```
time="2019-02-27T02:23:43Z" level=info msg="Desired change: UPSERT xxxx A"
time="2019-02-27T02:23:43Z" level=info msg="Desired change: UPSERT xxx TXT"
time="2019-02-27T02:23:44Z" level=info msg="2 record(s) in zone xx were successfully updated"
time="2019-02-27T02:23:44Z" level=info msg="Desired change: UPSERT xxx A"
time="2019-02-27T02:23:44Z" level=info msg="Desired change: UPSERT xx A"
time="2019-02-27T02:23:44Z" level=info msg="Desired change: UPSERT xx TXT"
time="2019-02-27T02:23:44Z" level=info msg="Desired change: UPSERT xx TXT"
time="2019-02-27T02:23:44Z" level=info msg="4 record(s) in zone xx were successfully updated"
```

Expected behavior:
We should not be seeing updates happen every 1 minute when there are no changes.

**Comment by prachidamle** [comment]
This appears to be a problem introduced in the kubernetes-incubator/external-dns v0.5.10 version that we use to launch external-dns:. Refer the issue here:
https://github.com/kubernetes-incubator/external-dns/issues/883

As mentioned in this issue, trying out with version v.0.5.11 should most likely solve this problem. Will check this version.

**Comment by prachidamle** [comment]
Tested with registry.opensource.zalan.do/teapot/external-dns:v0.5.11 and the constant updates do not happen with this version.

@alena1108 Can we create an image for rancher/kubernetes-external-dns: using this release registry.opensource.zalan.do/teapot/external-dns:v0.5.11?

**Comment by sangeethah** [comment]
Tested with latest build from master.

We now use `rancher/kubernetes-external-dns:v0.5.11` for external dns pods.
1. Create a Global DNS provider - GDNSP1 with no root domain and valid AWS credentials which has access to 2 Route53 root domains - test1.test.com and test2.test.com
2. Deploy Mcapp - mcapp1 with ingress having Global DNS annotations for host name say - "hello1.test1.test.com" with target projects from 2 different clusters.
3. Add Global DNS entry for fqdn -"hello1.test1.test.com" pointing to mcapp1 with GDNS provider - GDNSP1.

There is no update done ever minute when there are no changes made to DNS entries.
```
time="2019-03-02T02:54:04Z" level=info msg="All records are already up to date"
time="2019-03-02T02:55:04Z" level=info msg="All records are already up to date"
time="2019-03-02T02:56:04Z" level=info msg="All records are already up to date"
time="2019-03-02T02:57:04Z" level=info msg="All records are already up to date"
time="2019-03-02T02:58:04Z" level=info msg="All records are already up to date"
time="2019-03-02T02:59:04Z" level=info msg="All records are already up to date"
time="2019-03-02T03:00:05Z" level=info msg="All records are already up to date"
time="2019-03-02T03:01:04Z" level=info msg="All records are already up to date"
```

**Comment by sangeethah** [comment]
Tested basic workflows that involve addition/deletion/updates on DNS entries to external DNS provider - Route53
Set up - Rancher HA setup with 2 user clusters provisioned.

Tested the following p1 workflow for adding/deleting/updating of DNS records to AWS Route53 external provider:

1. Create a Global DNS provider - GDNSP1 with no root domain and valid AWS credentials which has access to 2 Route53 root domains - test1.test.com and test2.test.com
2, Deploy Mcapp - mcapp1 with ingress having Global DNS annotations for host name say - "hello1.test1.test.com" with target projects from 2 different clusters.
3. Add Global DNS entry for fqdn -"hello1.test1.test.com" pointing to mcapp1 with GDNS provider - GDNSP1.

DNS record for "hello1.test1.test.com" gets created as expected in Route53 with root domain - test1.test.com as expected.

4. Deploy Mcapp - mcapp2 with ingress having Global DNS annotations for host name say - "hello2.test1.test.com" with target project from 1 of the clusters.
5. Add Global DNS entry for fqdn -"hello2.test1.test.com" pointing to mcapp2 with GDNS provider - GDNSP1.
DNS record for "hello2.test1.test.com" gets created as expected in Route53 with root domain - test2.test.com as expected.

6. Update mcapp2 and another project from another cluster.

DNS records for "hello2.test1.test.com" gets updated with the worker node ip of the cluster as expected in Route53.

7. Delete Global DNS entry for fqdn -"hello1.test2.test.com" .
DNS records for "hello1.test2.test.com" gets deleted from Route53 with root domain - test2.test.com as expected.
