### ISSUE TITLE
Add Docker Images for Monitoring, External DNS and Logging to "rancher-images.txt"

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18453]
Enhancement

The docker images used by monitoring, external DNS and logging features should be added to the `rancher-images.txt` file which is used when installing Rancher in airgap environment. 

Reference:
- https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/prepare-private-registry/
- https://github.com/rancher/system-charts

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/18351
