### ISSUE TITLE
UI should display a relevant message when a cluster is configured using S3 and backup is performed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18457]
Rancher server version: Master

Steps:
1. Create a single node cluster with S3 backup configured.
2. Create few workloads
3. Perform a backup through UI.

UI displays a message that "Cluster has been backed up to local provider" even though S3 is configured. 
<img width="346" alt="screen shot 2019-02-27 at 2 43 03 pm" src="https://user-images.githubusercontent.com/18536626/53528738-5d3cfd80-3a9f-11e9-85e0-e35a294737d6.png">

UI should display a relevant message like "Cluster has been backed up to AWS S3"

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/28/19)
Confirmed issue. When you backup with s3 the UI message bubble now mentions S3:

"A s3 backup has been started for CLUSTERNAME"

![image](https://user-images.githubusercontent.com/45179589/53597507-98066a80-3b5f-11e9-808b-871ebabc2f17.png)
