### ISSUE TITLE
Add in rancher minimum and maximum versions to use with helm charts/catalog service

### ISSUE THREAD

**Issue by jira-sync-svc** [rancher/rancher#18469]
Currently, for the applications, which are helm charts, there is way to specify minimum or maximum Rancher version. Without these fields in one of the helm chart files, there is no way to prevent newer applications from showing up in older versions of Rancher, which could be a problem if the chart leverages a feature that is only available in a newer release of Rancher.

**Comment by jira-sync-svc** [comment]
➤ Denise Schannon commented:

We need to consider what branches are packaged in Rancher after this change is implemented so that older versions of Rancher are not using the same branch. The reason being that if you assume that the functionality exists in older versions, then you will end up pushing out template versions that are not compatible in older versions of Rancher that cannot prevent these applications from showing up.

**Comment by cjellick** [comment]
swithc this issue to release/v2.3 milestone and open a backport issue

**Comment by deniseschannon** [comment]
Does this issue need UI support? If so, create a ticket please.

**Comment by sowmyav27** [comment]
Verified with custom images from rancher:master-head

**Precondition:**
rancher version: rancher:v2.3.2(custom image for testing) - r1
rancher version: rancher:v2.3.3(custom image for testing) - r2
rancher version: rancher:v2.3.4(custom image for testing) - r3
chart - fluentd-aggregator
chart version: latest - rancher_min_version: 2.3.2 and rancher_max_version: 2.4.0 - v3
chart version: v0.1.0 - rancher_max_version: 2.3.2 - v1
chart version: v0.2.1 - rancher_min_version: 2.3.3 - v2

The basic test scenario:
Verified when you deploy the custom app in the project

In rancher:r1 - v1 is available and v2 and v3 are NOT available
In rancher:r2 - v2 and v3 are available and v1 is NOT available
In rancher:r3 - v2 and v3 are available and v1 is NOT available
