### ISSUE TITLE
When upgrading GKE, the API is leaving diskType, network, imageType, subNetwork null

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18464]
Version: v2.1.6
Upgrade to: Master 2.2 (2/27/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Upon upgrading from v2.1.6 when I edit a GKE cluster in the UI I see that the "Network", "Image Type" and "Root disk type" fields are blank. Subnet is missing presumably UI is doing this because it's also null in API.
![screen shot 2019-02-27 at 4 04 10 pm](https://user-images.githubusercontent.com/45179589/53533114-c9772b80-3ab6-11e9-99d2-0db15e80deda.png)
- Upon inspecting cluster API I see that these are null as well

**Results:**

**Expected result:**
API fills in these values for us based on what is in gcloud post-upgrade:
![image](https://user-images.githubusercontent.com/45179589/53532799-8c5e6980-3ab5-11e9-8e49-95cacac125e9.png)
![image](https://user-images.githubusercontent.com/45179589/53532847-c3cd1600-3ab5-11e9-86d6-4f6a7fae9320.png)
![image](https://user-images.githubusercontent.com/45179589/53533148-ea3f8100-3ab6-11e9-9229-0e02446e2c8f.png)
![image](https://user-images.githubusercontent.com/45179589/53532855-caf42400-3ab5-11e9-8efa-16c48a59fc3e.png)

**Actual result:**
API shows that diskType, network, and imageType, subNetwork are null.

**Other details that may be helpful:**
Single-node rancher install from v2.1.6 upgraded to master 2.2 (2/27/19)

**Comment by fyery-chen** [comment]
@davidnuzik

**Comment by loganhz** [comment]
We need to fetch the config from gke and update our crd.

**Comment by loganhz** [comment]
Hi @davidnuzik ,

The missing fields are newly added in 2.2. So we don't know the values for the fields in an existing GKE cluster which created in 2.1

kontainer engine framework doesn't support sync configuration back from providers.
For example, if you created a GKE cluster in Rancher UI. Then you go to the GKE console and update a configuration there. 
In Rancher, the value for the configuration is still the old one as Rancher will not fetch the current configuration from GKE.

Long Term Solution :

Maybe we need to fetch configuration from GKE periodically?

Short Term Solution:

As they are newly added fields and they are not editable in Rancher UI, we can hide those fields in Rancher UI as we don't know the correct values for them.

**Comment by davidnuzik** [comment]
@sangeethah do you have any input or anything to add?

**Comment by davidnuzik** [comment]
Test 1:
Version: Master 2.2 (3/1/19)
Confirmed that we make all fields uneducable when we try to edit a GKE cluster except for Node Count and Node Pool Autoscaling options which are the only two that take effect on gcloud for the cluster.

Test 2:
Version: v2.1.6 (Upgrade to master)
- Create GKE cluster on v2.1.6
- Upgrade rancher to latest master
- Wait for GKE cluster to finish reconciling
- Every option is HIDDEN except for ones that existed in v2.1.6 and Node Pool Autoscaling. Again I can tweak Node Count and Node Pool Autoscaling again just like with a fresh master install.
![image](https://user-images.githubusercontent.com/45179589/53659531-078c6080-3c19-11e9-8e66-f093606ad21e.png)

I believe this is acceptable for now. Down the road we should try to see if we can still show the other fields and just leave them uneditabale if they cannot be changed via gcloud api.
