### ISSUE TITLE
Cannot Switch Authentication from ldap to github and vice versa.

### ISSUE THREAD

**Issue by hibooboo2** [rancher/rancher#1846]
In order to reproduce:
Turn on github. Add a user to an environment.
Turn off github.
Turn on ldap.
List the project members on the environment that you added the github user too. 
You get a 400.

**Comment by hibooboo2** [comment]
Addressed with rancher/cattle#778

**Comment by sangeethah** [comment]
Tested with server version - v0.34.0-rc2

Had a set up with LDAP authentication on.
Created environment and added a member to this environment.
Turned on ldap.
Turn on github.
List the project members on the environment that had LDAP user.
LDAP user gets listed as (USER not found) / (GROUP not found)
Add github user to this environment.
Turned off github.
Turn on ldap.
List the project members on the environment that had github user.
github user gets listed as (USER not found)
