### ISSUE TITLE
Subtags with other `@type` are not supported in logging advanced mode

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18479]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Rancher version:** rancher/rancher:master 02/28/2019

**Steps to reproduce (least amount of steps as possible):**

When I set the following logging config file and then click `TEST`, Will return `@type is not supported, you can chose the following type: ['elasticsearch', 'splunk_hec', 'remote_syslog', 'kafka_buffered', 'forward']` error.
```
<match  * > 
  @type elasticsearch
  include_tag_key  true
  hosts https://elastic:XXX@X.X.X.X:9200
  logstash_prefix "local-2019-02-28-ssl"
  logstash_format true
  logstash_dateformat  %Y-%m-%d
  type_name  "container_log"
  ssl_verify false
  ssl_version TLSv1_2
  <buffer>
    @type file
    path /fluentd/log/buffer/project.c-rqjwd_p-pb7mr.buffer
    flush_mode interval
    flush_interval 60s
    flush_thread_count 8
    queued_chunks_limit_size 200
  </buffer> 
  slow_flush_log_threshold 40.0    
</match>
```

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/1/19)
Confirmed issue. Followed the steps to reproduce and I no longer see this behavior. The Dry Run (Previously Test button) is working regardless of type -- I tried them all and encountered no issues.
