### ISSUE TITLE
When `Log Severity` is `Warning`, the log cannot be sent to the syslog server.

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18472]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Rancher version:**rancher/rancher:master 02/27

**Steps to reproduce (least amount of steps as possible):**
1. Enable syslog logging target
2. `Log Severity` select `Warning`
3. Save

**Result:**
The log could not be sent to the syslog server, fluentd error log:
```
2019-02-28 07:50:58 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="'warning' is not a designated severity"
```
I tested all `Log Severities`, only the `Warning` level could not send logs to the syslog server.

**Comment by aiwantaozi** [comment]
Could you add you syslog config and version, the warning severity is supported. https://en.wikipedia.org/wiki/Syslog

**Comment by kingsd041** [comment]
rsyslog version:
```
root@ip-172-31-31-219:/var/log# rsyslogd -v
rsyslogd 8.16.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64
```
rsyslog config:
```
module(load="imuxsock") # provides support for local system logging
module(load="imklog")   # provides kernel logging support
#module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

*.warning /var/log/hailong/warning_Log
*.debug /var/log/hailong/debug_Log
*.err /var/log/hailong/err_Log
*.info /var/log/hailong/info_Log
*.notice /var/log/hailong/notice_Log
*.crit /var/log/hailong/crit_Log
```
@aiwantaozi Tested with rsyslogd 8.34.0, the same error exists

**Comment by aiwantaozi** [comment]
The fluentd syslog gem depends on this gem, and it used deprecated warn instead of warning https://github.com/eric/syslog_protocol/blob/master/lib/syslog_protocol/common.rb#L58

**Comment by kingsd041** [comment]
Version: master 2.2 (3/7/19) 
Confirmed fix. When Log Severity sets `Warning`, the log can be sent to syslog
