### ISSUE TITLE
rancher connecting using externalIP instead of internalIP

### ISSUE THREAD

**Issue by segator** [rancher/rancher#18473]
rancher/rancher:v2.2.0-rc2

created cluster with custom cluster(kube 1.12.5) network tryied canal and flannel. Same error on both
Cluster of 3 machines, the 3 machines are interconnected with --internal-ip, externalIP is also defined using public Domain names
external IP is full block except ports 80,443,ICMP.
Rancher server run on the same machine as kube etcd/controlplane

I see in the docker rancher lot of failure request, rancher are trying to use externalIP instead of internalIP for a request, I dont know what is for.

```
2019-02-28 08:42:20.405187 I | mvcc: finished scheduled compaction at 85763 (took 9.069514ms)
2019/02/28 08:42:25 [INFO] Handling backend connection request [c-h5qs2:m-2014f483defe]
2019/02/28 08:42:35 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->publicIP:38198: i/o timeout
2019/02/28 08:42:50 [INFO] Handling backend connection request [c-h5qs2:m-2014f483defe]
2019/02/28 08:43:00 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->publicIP:38228: i/o timeout
2019/02/28 08:43:16 [INFO] Handling backend connection request [c-h5qs2:m-2014f483defe]
2019/02/28 08:43:26 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->publicIP:38268: i/o timeout
```

**Comment by corentin59** [comment]
Hello,

I have same problem with imported cluster.
The imported cluster start normaly, but when I close all ports (except 80 and 443) on my public ip XXX.XXX.XXX.XXX the communication between node stop.

![2019_03_18_21_53_46_Rancher](https://user-images.githubusercontent.com/2035983/54563002-73681a80-49c8-11e9-9065-1dd05d02d61b.png)

**Comment by amitnegi6190** [comment]
Hi @segator , did you get a resolution for your issue? I am facing the same thing.

Thanks!

**Comment by martin-kieliszek** [comment]
Was there a resolution for this issue?
