### ISSUE TITLE
Not able to get access to all environments when access control that was enabled is disabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1848]
Server version - V0.33.0-rc3

Steps to reproduce the problem:
rancher server with access control enabled using github authentication.
As admin user , create an environment -env1 and add "test1" as member of this environment.
Have few more environments in this setup.

In another session , Login as "test1" to rancher server where u get access to "test1.
When still logged in as "test1" in this session , disable github authentication as admin user.

Refresh the current session of "test1" . We still do not get access to all other environments in this setup. Sometimes I have access to no environments and other times I get access to the environments i had before - "env1" only.
We do not see the "log out" option any more and instead see "Access is not configured" and have
"Access Control" option provided.

We get a "Error - Not Found(404)" when trying to access this page with reload and logout option, both of which bring us back to the same view where we have access to only 1 environment and no logout option.

<img width="367" alt="screen shot 2015-08-20 at 7 14 48 pm" src="https://cloud.githubusercontent.com/assets/4266958/9400326/0b4cd87c-4775-11e5-8b75-64e07dc78215.png">

**Comment by sangeethah** [comment]
<img width="1069" alt="screen shot 2015-08-21 at 11 13 13 am" src="https://cloud.githubusercontent.com/assets/4266958/9415812/91604882-47f6-11e5-94e5-329bd873c8e4.png">

@vincent99 , should we see projectId to be "1a5" - Default project when access control is disabled. 
I always seem to get to this state. 
The project Id it shows is an "ldap user" that I was logged in earlier . So this set up had LDAP on and then was switched to github and the deactivated it.

**Comment by vincent99** [comment]
The projectId in localStorage is the one that is currently selected; there's no reason it needs to be 1a5/Default or be reset to that after turning access control off.

More interesting/relevant to this issue would be the `/v1/projects` response after turning off auth on the other browser and **reloading** this one.

**Comment by vincent99** [comment]
Is this still a thing?

**Comment by tfiduccia** [comment]
The access control 404 bug was fixed in previous release.
Access when auth turned off is working.  This will also be retested when James is finished redoing the authentication for admin users.
Version - master 3/9
Verified fixed
