### ISSUE TITLE
Change names of Global Tools menu items

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18487]
Version: Master 2.2 (2/28/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Inspect the Tools menu at the global level. Looks at the menu items.

**Result:**
The tools menu items should not say:
![image](https://user-images.githubusercontent.com/45179589/53605901-11a95300-3b76-11e9-8a6c-71353b17b619.png)

Since we are already in the Global context the menu items should say:
```
Apps
DNS Entries
DNS Providers
```
in this specific order.
We do NOT need to change the titles for the pages for "Multi Cluster Apps" "Global DNS Providers" etc.

**Comment by cjellick** [comment]
I'm not sure I agree with this. Everything at the global level does not have an implied "global" in front of it. Its not "Global Clusters" and "Global Mutli-cluster Apps"

**Comment by vincent99** [comment]
Agree with Craig, I especially don't like MCA -> App.  That will make it very hard to separate talking about the feature versus the existing single project apps.

**Comment by davidnuzik** [comment]
@tfiduccia any input? Okay if we leave it as it is?

**Comment by westlywright** [comment]
@davidnuzik I think tools should stay the same as well, it follows the same pattern as cluster/project level where we place the non-top level pages like alerts and logging. Just because it only contains multi-cluster resources right now doesn't mean it always will.

**Comment by tfiduccia** [comment]
@cjellick, @westlywright, @vincent99 - I don't care if you want to keep multi-cluster app, but having global/global DNS entries seems redundant.  I would still like to remove the "global" in front of DNS entries and DNS providers.  We are at the global level of the menu.  It's just silly to leave that in there.
