### ISSUE TITLE
NodePort service stops working when patched with 'externalTrafficPolicy=Local'

### ISSUE THREAD

**Issue by sonaikar** [rancher/rancher#18483]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Create a cluster using Amazon as Service Provider. 
Deploy an application with below steps. 
```
 kubectl run source-ip-app --image=//k8s.gcr.io/echoserver:1.4
kubectl expose deployment source-ip-app --name=nodeport --port=80 --target-port=8080 --type=NodePort
  kubectl patch svc nodeport -p '{"spec":{"externalTrafficPolicy":"Local"}}'
  NODEPORT=$(kubectl get -o jsonpath="{.spec.ports[0].nodePort}" services nodeport)
 NODES=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="ExternalIP")].address }')
for node in $NODES; do curl -s $node:$NODEPORT | grep -i client_address; done
```

**Result:**
Service does not respond.

**Other details that may be helpful:**
You can patch service as cluterip and it starts responding
kubectl patch svc nodeport -p '{"spec":{"externalTrafficPolicy":"ClusterIP"}}'

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 1.11.5

```
(paste the output here)
```

- Docker version (use `docker version`):17.3.2

```
(paste the output here)
```

**Comment by mak3r** [comment]
sonaikar, when you say 

> the service does not respond

can you be more more specific about how your are calling the service and whether you are inside or outside the cluster network when doing so? I have run your example on a rancher cluster built on ec2 instances without any issue. Could it be your security groups settings?

I get the following output using nodeport with and without the `ExternalTrafficPolicy:Local` respectively. My workstation IP is the one that’s patched on local (the first one) That’s what the local policy does. Whereas the second version is using the cluster node IP.
 
With ExternalTrafficPolicy:Local patched on svc
```
CLIENT VALUES:
client_address=74.76.72.180
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://ec2-54-82-26-49.compute-1.amazonaws.com:8080/
 
SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001
 
HEADERS RECEIVED:
accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding=gzip, deflate
accept-language=en-US,en;q=0.9
connection=keep-alive
host=ec2-54-82-26-49.compute-1.amazonaws.com:30416
upgrade-insecure-requests=1
user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
BODY:
-no body in request-
```
 
 
WithOUT ExternalTrafficPolicy:Local patched on svc
```
CLIENT VALUES:
client_address=172.31.31.165
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://ec2-54-82-26-49.compute-1.amazonaws.com:8080/
 
SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001
 
HEADERS RECEIVED:
accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding=gzip, deflate
accept-language=en-US,en;q=0.9
connection=keep-alive
host=ec2-54-82-26-49.compute-1.amazonaws.com:32426
upgrade-insecure-requests=1
user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
BODY:
-no body in request-
```

**Comment by dhrp** [comment]
OK, I've been running into the same issue(s) the past year, and have now diagnosed this issue further:

What I think the issue is:

kube-proxy (in node.go:103) fails to find the node by it's local hostname, because the (k8s) node is not named like the hostname.

i.e. Rancher may name the host: 
`ip-172-31-27-83.eu-central-1.compute.internal`, but the hostname is set to `k8s-ing-test1`

Kube-proxy is started with:
--hostname-override=k8s-ing-test1

It then causes the following error when the NodePort service with ExternalTrafficPolicy: Local is started:

```
root@k8s-ing-test1:/home/ubuntu# sudo docker logs kube-proxy 2>&1 |grep "Failed to retrieve node info:"
W0712 14:02:42.933714   10872 node.go:103] Failed to retrieve node info: nodes "k8s-ing-test1" not found
```

This issue on Juju started clusters provides really helpful information to debug and reproduce this issue:
https://github.com/charmed-kubernetes/bundle/issues/489

System detail:
Node OS: Ubuntu 18.04
Rancher: 2.2.2

--- 
Steps to reproduce:
* Create a 1-node cluster (Ubuntu) on AWS EC2
* Create a deployment
* Create a NodePort service for that deployment with ExternalTrafficPolicy: Local

Notice no traffic occurs. But it does work when ExternalTrafficPolicy is changed to Cluster.

-- I have found it to make sense to set traffic policy to local when creating a ingress-nginx daemonset behind an AWS LoadBalancer.

**Comment by dhrp** [comment]
@mak3r, perhaps I should make this a new issue? I've reproduced the issue also when a node is running RancherOS

**Comment by mak3r** [comment]
@dhrp no need to create a separate issue for RancherOS if it's the same fundamental problem

**Comment by neelesh3710** [comment]
We hit this when installing our own nginx ingress controller on k8s cluster created by rancher. Default instructions for nginx ingress controller use "ExternalTrafficPolicy:Local" which results in a silent failure. We could not find any errors in logs so this was hard to debug. After changing that setting to "Cluster" things started working.

**Comment by simone6021** [comment]
Hello,
any chance to get this issue addressed? We are hitting this on premise install.

Maybe this so answer can help to solve this: https://stackoverflow.com/a/47426401
