### ISSUE TITLE
UI - Support disable auto backup

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18490]
rancher/rancher:master 02/28

When we create a RKE cluster, there is no option to disable the auto snapshot. 
In 2.1, users can turn on and turn off it in UI.

![image](https://user-images.githubusercontent.com/21168270/53612113-0143b780-3c0c-11e9-96e3-0d5bbb8da05b.png)

**Comment by alena1108** [comment]
Closing as a duplicate of https://github.com/rancher/rancher/issues/18647
