### ISSUE TITLE
UI: Cannot update node count in Alibaba hosted k8s

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18496]
UI for https://github.com/rancher/rancher/issues/17174

**Comment by davidnuzik** [comment]
@loganhz could you contact me privately for credentials to test Alibaba? Or is there someone who can test and has access to Alibaba test account?

**Comment by loganhz** [comment]
@davidnuzik yes, we will test it. Thanks!

**Comment by rootwuj** [comment]
@n313893254
I can edit the `region` through the UI and get an error. Edit `region` should be disabled.
```
Uncaught TypeError: Cannot read property 'map' of undefined
    at n.setInstances (vendor.js:15641)
    at n.configMaster (vendor.js:15633)
    at n.send (vendor.js:3749)
    at n [as send] (vendor.js:3706)
    at n.triggerAction (vendor.js:3641)
    at n.sendAction (vendor.js:3747)
    at n.save (vendor.js:16597)
    at n.send (vendor.js:3749)
    at n [as send] (vendor.js:3706)
    at vendor.js:2805
```

**Comment by westlywright** [comment]
@loganhz can you assign to the appropriate person for testing?

**Comment by loganhz** [comment]
sure

**Comment by rootwuj** [comment]
Version: master 2.2 (3/7/19) Image ID: b4e18ff93fa1
Validate fixed.

Validate steps:

Creating alibaba ACK managed kubernetes cluster1 and unmanaged kubernetes cluster2
Edit cluster1:
Modify Cluster Name
Modify worker nodes count: node range is 2-300
Edit cluster2:
Modify Cluster Name
Modify worker nodes count: node range is 0-300
