### ISSUE TITLE
Multicluster app - API should not allow removing of roles

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#18494]
rancher/rancher:master 2/28

The api should throw an error when attempting to remove roles from a multicluster app. 

Additionally, when removing roles in the current implementation, the associated rolebindings for the multicluster service account are not removed.

To reproduce: 
* Create a multicluster app and add a role
* Upgrade app and remove the role

Actual:
* Role can be removed

Expected:
* Role cannot be removed

**Comment by mrajashree** [comment]
@bmdepesa  I don't think we ever wanted this to throw an error. It was just going to be a no-op earlier. But now along with allowing this, we will also be removing the rolebindings for the sys acc from the target projects.
cc @alena1108 @cjellick

**Comment by bmdepesa** [comment]
rancher/rancher:master 38fd13a8 3/7
HA installation

* Create cluster(s)
* Deploy multicluster app 
* Remove all roles from multicluster app
* HTTP 422 - No roles provided
