### ISSUE TITLE
f5-bigip-ctlr helm chart doesn't set annotations

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#18499]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Enable this helm chart on Rancher 2.1.5

https://github.com/F5Networks/charts/tree/master/src/stable/f5-bigip-ingress

Install f5-bigip-ctlr chart and set the following annotations:

https://imgur.com/a/uq0sIVS

**Result:**

The annotations will be missing in Rancher as seen here:

https://imgur.com/a/Piacats

**Other details that may be helpful:**

These entries show up in the logs:

2019/02/14 17:55:52 [INFO] No virtual IP was specified for the virtual server ingress__80, creating pool only.

2019/02/14 17:55:52 [INFO] Wrote 0 Virtual Server and 0 IApp configs

2019/02/14 17:55:52 [WARNING] Overwriting existing entry for backend {ServiceName:nginx-nodeport ServicePort:80 Namespace:default}

2019/02/14 17:55:52 [INFO] Wrote 0 Virtual Server and 0 IApp configs

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

2.1.5

- Installation option (single install/HA):

Customer is on HA, but I reproduced on single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
custome
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
vm

- Kubernetes version (use `kubectl version`):
1.11.6

- Docker version (use `docker version`):
17.9.1

**Comment by guangbochen** [comment]
Hi @bentastic27, in `Helm` you need to use backslash for the non-nested layer keys that contains the `.` value, the right example in your case should be:
```
ingress.annotations.virtual-server\.f5\.com/ip=10.21.18.201
ingress.annotations.virtual-server\.f5\.com/partition=Kubernetes
ingress.annotations.virtual-server\.f5\.com/ingress\.class=f5
ingress.annotations.virtual-server\.f5\.com/http-port=80
ingress.spec.backend.serviceName=nginx-nodeport
ingress.spec.backend.servicePort=80
```
and the expected result is:
![image](https://user-images.githubusercontent.com/4569037/55598528-b75b6d80-5785-11e9-9edf-f1a10a3fbd6e.png)

**Comment by bentastic27** [comment]
@guangbochen Thanks! The customer confirmed that that resolves the issue.
