### ISSUE TITLE
etcd restore from subsequent backup fails after failure to restore from first backup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18504]
**What kind of request is this:** bug

**Steps to reproduce:**
1. Create a custom cluster with 1 etcd/1control plane /2 worker nodes.
2. Register the cluster with the nodes and take a backup (Backup#1).
3. Register/add two more etcds nodes to the cluster.
4. take a backup (Backup#2)
5. Added namespaces and take backup (Backup#3)
6. Restore the cluster to the first backup (Backup#1) (this snapshot is available on 1 etcd and NOT available on the other 2 etcds)
7. Error - `Failed to download etcd snapshot from backup server [<ip>], exit code [1]: time="2019-03-01T00:48:59Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"`  will be seen on the Rancher UI. CLuster is in `Updating` state.
8. Now restore the cluster to the Backup#2 or Backup#3. (these backup snapshots are available on all the three etcds)

**Expected Result:**
The cluster should be successfully restored to the backed up state.

**Actual Result:**
Error continues to be seen in the Rancher UI.
Error - `Failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2019-03-01T17:40:19Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory" Failed to run backup server container, container logs: time="2019-03-01T17:40:25Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory" Failed to run backup server container, container logs: time="2019-03-01T17:40:33Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory" ]`

<img width="1283" alt="screen shot 2019-03-01 at 9 46 11 am" src="https://user-images.githubusercontent.com/26032343/53656106-136f2700-3c07-11e9-872e-56b78bf61c4a.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version: rancher:master (02/28/2019)
- Installation option (single install/HA): Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): SUSE cluster
- Kubernetes version (use `kubectl version`):

```
v1.13.1
```

**Comment by moelsayed** [comment]
fixed in https://github.com/rancher/rke/pull/1166/files

**Comment by sowmyav27** [comment]
Verified in `rancher:master` (03/05/2019). 

etcd restore from subsequent backup happens successfully after an initial failure to restore from first backup.
