### ISSUE TITLE
Project monitoring - occasionally failed to enable project monitoring after disabling it

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18508]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- add a DO cluster
- enable project-level monitoring
- wait for the catalog app and workloads to be active
- click both Grafana and Prometheus link on the catalog app to confirm they are accessible
- disable project-level monitoring
- wait for the catalog app and workloads to be removed from the UI
- enable project-level monitoring again
- check the UI for both the catalog app and workloads to wait for them to be active

**Result:**
- the Prometheus is not accessible 
<img width="1304" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53658406-f130d580-3c15-11e9-81a5-3f2a6bce38c1.png">

- the workload `prometheus-project-monitoring` shows active but actually not.
<img width="1433" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53658135-3b658700-3c15-11e9-94bb-346fe0468e1a.png">
<img width="1428" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53658141-3d2f4a80-3c15-11e9-8693-d65b571a6c38.png">

- the old pod `prometheus-project-monitoring-0` is failed to terminate and re-create 
```
# Run kubectl commands inside here
# e.g. kubectl get all
> k get ns
NAME                        STATUS    AGE
cattle-prometheus           Active    2h
cattle-prometheus-p-fz5rx   Active    2h
cattle-system               Active    3h
default                     Active    3h
ingress-nginx               Active    3h
kube-public                 Active    3h
kube-system                 Active    3h
> k get pods -ncattle-prometheus-p-fz5rx
NAME                                          READY     STATUS        RESTARTS   AGE
grafana-project-monitoring-7696c5d8fd-rrnfb   2/2       Running       0          2m
prometheus-project-monitoring-0               4/4       Terminating   1          2h
```

**Other details that may be helpful:**
This bug shows occasionally and could be healed by itself sometimes, and in such case, I need to disable and enable the project monitoring one more time to get it running up. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master on 2/28
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thxCode** [comment]
@jiaqiluo , Can you try as the following cases with the same above steps?:
|  | Kuberentes Version | Docker Version |
| --- | --- | --- |
| 1 | 1.12 | 18.09 |
| 2 | 1.13 | 17.03 |

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher: master 3/6

Setup and steps are the same as the issue describes, tried to enable/disable cluster-level and project-level monitoring multiple times and did not meet any issue.
