### ISSUE TITLE
k8s 1.13.4, 1.11.8, 1.12.6 support to 2.1.x

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18514]
Enable support for k8s 1.13.4, 1.11.8, 1.12.6 
Disable support for 1.9 and 1.10

**Comment by alena1108** [comment]
Can be tested in `rancher/rancher:v2.1.7-rc8`

**Comment by sowmyav27** [comment]
Verified with `rancher/rancher:v2.1.7-rc8` for k8s v1.12.6 and docker version 18.06 and 18.09. Automation test cases pass.

**Comment by sowmyav27** [comment]
verified on `rancher/rancher:v2.1.7-rc7` with k8s 1.11.8, docker v18.09. Automation test cases passed.

**Comment by soumyalj** [comment]
Tested using rancher/rancher:v2.1.7-rc9 with K8s v1.13.4 for Docker 18.06 and Docker 18.09.
Automation tests ran ok.
