### ISSUE TITLE
[server-chart] cacerts.pem volume has the wrong path.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#18510]
@kinolaev discovered deploying with private CA certificates is broken in 2.2.0-alpha/rc releases.

#18474 updates the path for the cacerts.pem so its not mounting over the `/etc/rancher/ssl` directory.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher
```
helm install rancher-latest/rancher --version 2.2.0-rc2 --name rancher --namespace cattle-system --set hostname=rancher.localhost --set ingress.tls.source=secret --set privateCA=true
```
Add Self-Signed Cert and CA
```
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key

kubectl -n cattle-system create secret generic tls-ca \
  --from-file=cacerts.pem
```

**Result:**
Rancher pods fail to start.
```
➜ kubectl -n cattle-system logs  rancher-5598f67959-5hqf9
2019/03/01 20:25:37 [INFO] Rancher version v2.2.0-rc2 is starting
2019/03/01 20:25:37 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2019/03/01 20:25:37 [INFO] Listening on /tmp/log.sock
I0301 20:25:37.792188       6 http.go:110] HTTP2 has been explicitly disabled
2019/03/01 20:25:37 [FATAL] open /etc/rancher/ssl/cert.pem: not a directory
```

**Other details that may be helpful:**

**Environment information**
- Rancher version 2.2.0-rc2 HA install

**Comment by cloudnautique** [comment]
Verified in load testing.

**Comment by imwower** [comment]
still does not work in version 2.4.8
`helm install rancher rancher-stable/rancher  --namespace cattle-system  --set hostname=rancher.xxx.com  --set ingress.tls.source=secret  --set privateCA=true --version v2.4.8`
then get pod logs:
`kubectl logs rancher-767cc66f9d-kc697 -n cattle-system -f`
get:
 ```
2020/09/28 06:19:32 [INFO] Watching metadata for management.cattle.io/v3, Kind=Feature
2020/09/28 06:19:32 [INFO] Watching metadata for management.cattle.io/v3, Kind=NodeDriver
2020/09/28 06:19:32 [INFO] Refreshing all schemas
2020/09/28 06:19:32 [FATAL] read /etc/rancher/ssl/cacerts.pem: is a directory
```
