### ISSUE TITLE
Projects/Namespaces search is not working

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18513]
Version: Master 2.2 (3/1/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Go to the Projects/Namespaces page
- Search for any of the projects or namespaces

**Result:**
No results will come up.
![image](https://user-images.githubusercontent.com/45179589/53669964-277e4d00-3c36-11e9-8324-2909ade3e6e7.png)

It seems like the search does not work for any projects. I was thinking possibly System and Default are excluded but even my own projects/namespaces are not showing up for me.
No errors in browser dev console.

**Comment by westlywright** [comment]
@loganhz can you tackle this please

**Comment by loganhz** [comment]
Sure

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/5/19) HA Setup
Confirmed issue. I am no longer having any issues with searching. I smoke tested and trying fuzzing data, etc and it appears to be working correctly now.

**Comment by lopf** [comment]
Search for project name doesn't work in 2.2.4, only namespace matches are shown.

**Comment by davidnuzik** [comment]
I can confirm this as well in both v2.2.4 and latest master-head build.

@westlywright are we able to search by project? Or can we only search via namespaces?

When I search for Default and System these work but it appears to be because it's searching namespaces _within_ those projects and that's why we get results for those

**Comment by westlywright** [comment]
The functionality exists to search on both. @loganhz Can you investigate this? We should be able to utilize the `extraSearchFields` param on `sortable-table` to achieve this.

**Comment by davidnuzik** [comment]
@logan I created issues to track this.
https://github.com/rancher/rancher/issues/21379 (v2.2.4)
https://github.com/rancher/rancher/issues/21380 (v2.3)
Feel free to re-assign I just assigned to you for now.
cc: @lopf (FYI)
