### ISSUE TITLE
k8s 1.11.8 and 1.12.6 support to 1.6 catalog

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18516]
- [x] Add support for k8s 1.11.8 and 1.12.6 k8s to rancher catalog. Put 1.6.26 as a min rancher version for now
- [x] Update max rancher version to v1.6.26-rc1 for k8s 1.12.5 (folder 57) and v1.11.6 (folder 55) - all that to hide these versions

**Comment by soumyalj** [comment]
Automation tests passed for on ​V1.6.26 ​with ​catalog ​1.6-development ​branch for the below:
1. K8sv1.12.6-rancher1-1 ​Docker ​18.09 ​.
