### ISSUE TITLE
Multiclusterapp Roles design changes

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#18521]
- [x] Roles will be a required field
- [x] For 2.2, the UI will now only present two options for mc app roles. project-member and cluster-owner with clearer label text describing exactly what these roles are doing. The mcapp will also be defaulted to use the project-member role
The idea being project-member role encompasses all permissions required for apps/namespace/workloads management, and also ensures the user's access to the projects. But some apps like grafana, datadog require cluster-owner's permissions to deploy, so you have the option to add that when needed.
Rancher's API, meaning v3/multiclusterapps if used for creating mcapp, will still display all roletemplates. This is because we want to support more custom roles later. 
1. Users can pass only either of the two options through UI (Cluster or project)
2. For API or CLI, we will document that users stick to either project-member and cluster-owner roles, or any roles they are confident can manage the namespace/workload/app creation. 

**While creating mcapp through api/cli, where users could pass roles other than cluster-owner and project-member**

- [x] Built-in cluster-owner, project-owner and project-member roles can assign any built-in project/cluster roles; with the exception that project-member cannot assign project-owner role
- [x] Backend will continue to do an exact match, if from the roles passed, any of the roles are custom roles and the user does not have a prtb/crtb for that custom role, then irrespective of whether the user is a cluster-owner, project-owner or project-member, we will error out (Global admins will still be excused from this strict check)

**When using UI, and only cluster-owner and project-member options are presented**
- [x] Global admin should be able to select any of the two options, even without explicitly being in the members list of the target projects or their clusters
- [x] Cluster-owner should be able to select any option, as long as the targets are within that cluster. Cluster-owner need not explicitly be present in that cluster's projects' members list
- [x] Project-owner/member can only provide the Project scoped permission.

**Updating roles/projects**
- [x] When adding any new role to the multiclusterapp, as before, the caller of this update request must have all new Roles in all mcapp.Spec.Targets.
This check will be relaxed for global admins, cluster-owners while adding all roles and project-owners while adding project-roles
- [x] Upon removal of a role from mcapp.Spec.Roles, the prtb/crtb created for the system account with this role must be removed from all mcapp.Spec.Targets
- [x] During addProjects, the caller must have all mcapp.Spec.Roles in the new projects being added. This check will be relaxed for global admins, cluster-owners/project-owners while adding new projects they are owners of
- [x] During removeProjects, the prtb/crtb created for the system account with all mcapp.Spec.Roles must be deleted from the projects being removed

**Comment by cjellick** [comment]
When this ticket gets moved over to-test, move over https://github.com/rancher/rancher/issues/18326

**Comment by cjellick** [comment]
Also, I think this one should probably be moved as well https://github.com/rancher/rancher/issues/18494 just linking it to make sure we do not miss it

**Comment by cjellick** [comment]
@bmdepesa @sangeethah FYI with this refactor, I consider anything beyond what the UI presents to be p2 or p3 test cases.

**Comment by bmdepesa** [comment]
rancher/rancher:master-38fd13a8 3/7
HA installation
```
* As standard user:
	* Roles presented:
		* Cluster owner
		* Project member
	* Create MC app
		* Cluster owners can add all projects in cluster
		* Project members can add project 
		* Targets are correctly displayed based on member permissions
	* Update roles
		* cluster-owner -> project-member
		* project-member -> cluster-owner
		* Cluster owner can choose cluster/project role
		* Project member can only choose project role
	* Update projects
		* User can add projects they have access to (cluster & project permissions)
```
```
* As global admin: 
	* Roles presented:
		* Cluster-owner
		* Project-member
	* Create MC app
		* Cluster-owner roles
		* Project-member role
	* Update roles
		* cluster-owner -> project-member
		* project-member -> cluster-owner
	* Update projects
		* User can add projects they have access to (cluster & project permissions)
```
```
* When updating target projects, crtb/prtb are removed/added
* When changing roles, old crtb/prtb are removed and new added
* When adding projects, user must have same roles in each target
	* Relaxed for admin & cluster/project owners
* When adding roles, user must have the role in all targets
```
