### ISSUE TITLE
UI Slowness and API timeout when large number of pods (no pagination model in fetch)

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#18522]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
When trying to open a project in a specific cluster in Rancher we're receiving the following error: 
Unexpected error &http.httpError{err:"net/http: request canceled (Client.Timeout exceeded while reading body)", timeout:true} when reading response body. Please retry

**Other details that may be helpful:**
This project has a namespace that has about 2700 pods.  It seems like when a project has a large number of pods in a single name space, the fetch call becomes blocked or worse times out.  There does not seem to be any pagination model presently in these fetches.  Seems like the API attempts to list all workloads without any  limits.

1. What is Rancher recommendation on how many pods max per namespace within a project?
2. Request a pagination model to be implemented to address this situation.

**Environment information**
- Rancher 2.1.3

**Comment by ts-mini** [comment]
I've seen the same behavior - but I'm not at that scale of pods/project.  The following screen shot is loading times of 104 Workloads across a dozen or so namespaces.  Have seen the similar performance across all versions of rancher, but running the latest now (2.1.7)

I know this doesn't provide a ton of useful information, but 48 seconds for 52KB of data is nuts

![image](https://user-images.githubusercontent.com/4910513/54075981-f370e080-4262-11e9-8991-4f3c4b265778.png)

**Comment by cjellick** [comment]
@ts-mini whats the nature of your cluster? is it phiscally far away from your rancher server? Is it RKE, GKE, AKS, EKS?

**Comment by ts-mini** [comment]
@cjellick The cluster is in AWS us-east-1 (RKE), the master is in a GKE us-central-1.  So not huge distances, but not 'close'.  We dont see the same issues on smaller clusters in our datacenters.

**Comment by ts-mini** [comment]
Number of nodes is 69 across the us-east-1a/b/c
7 etcd nodes, 3 control plane nodes  (both of these types are overscaled and instance 'hardware' limitations arent the issue)
Pods: 1755
Deployments: 696
Namespaces: 201
Projects: 26

ICMP ping stats from our control plane to our gke master
64 bytes from <redacted> icmp_seq=1 ttl=27 time=29.4 ms
64 bytes from <redacted> icmp_seq=2 ttl=27 time=28.7 ms
64 bytes from <redacted> icmp_seq=3 ttl=27 time=28.6 ms
64 bytes from <redacted> icmp_seq=4 ttl=27 time=28.8 ms
64 bytes from <redacted> icmp_seq=5 ttl=27 time=28.7 ms
64 bytes from <redacted> icmp_seq=6 ttl=27 time=28.7 ms
64 bytes from <redacted> icmp_seq=7 ttl=27 time=28.7 ms
64 bytes from <redacted> icmp_seq=8 ttl=27 time=28.7 ms
64 bytes from <redacted> icmp_seq=9 ttl=27 time=28.7 ms
64 bytes from <redacted> icmp_seq=10 ttl=27 time=28.7 ms

**Comment by rmweir** [comment]
@jambajaar @ts-mini can you run `kubectl -v=9 get pods --all-namespaces > <output_file> ` then tell us the size of the output file, as well as if there were any timeouts?

**Comment by cjellick** [comment]
@ts-mini @jambajaar do you have a kubeconfig that can query the cluster directly without going through rancher as a proxy? If so, can you run `time kubectl get pods --all-namespaces` and let us know the response times?

**Comment by ts-mini** [comment]
sorry im bad at notifications
real	0m3.113s
user	0m0.544s
sys	0m0.140s
14:55:35 product

**Comment by ts-mini** [comment]
i rm -rf'ed ~/.kube/cache and ran it again
real	0m2.954s
user	0m0.522s
sys	0m0.108s

**Comment by ts-mini** [comment]
I misread your request.  The above response was from my kubectl on my laptop (pointing through the rancher proxy).  

This is ssh'd to the control node, kubectl'ing directly 'on' the cluster:
root@control-80:/etc/kubernetes/ssl# time kubectl --kubeconfig kubecfg-kube-scheduler.yaml get pods --all-namespaces > /dev/null

real	0m0.354s
user	0m0.401s
sys	0m0.045s
root@control-80:/etc/kubernetes/ssl# time kubectl --kubeconfig kubecfg-kube-scheduler.yaml get pods --all-namespaces | wc -l    
1827

real	0m0.404s
user	0m0.390s
sys	0m0.116s

**Comment by junkiebev** [comment]
> Number of nodes is 69 across the us-east-1a/b/c

Nice.

**Comment by jira-sync-svc** [comment]
➤ Jack Luo commented:

The bug fix is validated in Rancher: v2.2.3-rc1 in both single installed and HA mode 

Case 1:

  * launch 300 workloads with a large environment variable in p1
  * launch 800 workloads without large environment variable in p2
  * no workload in p3
  * switch between project

Time used to load a project:

.p1p2p3single install mode 11.38s2.60s176msHA mode4.33s1.49s179msCase 2:

  * launch 1100 workloads without large environment under the same namespace in a p4
  * navigate to project p4
  * refresh the project page
  * observe the number of calls made to project related resources such as pods and workloads

The number of call to each API:

.workloadspodsservicessingle install mode 111HA mode111Case 3:

  * the same steps as Case 2
  * observe the time used for the API call pods?limit=-1&sort=name

.time usedsingle install mode 2.81sHA mode1.75sMore info: test results in v2.2.1 and master https://github.com/rancher/rancher/issues/18870#issuecomment-484278427 ( https://github.com/rancher/rancher/issues/18870#issuecomment-484278427|smart-link )
