### ISSUE TITLE
Handle pipeline components upgrade

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18526]
We would like to keep pipeline components’ spec on upgrade at the moment, so that user configured stuff like volumes is kept during upgrade.

It should be easier after pipeline deployments migrates to the system chart way

**Comment by gitlawr** [comment]
To test:
1. Use pipelines in an old Rancher version. Upgrade Rancher to the newer version, check that pipeline components are upgraded accordingly(which is Jenkins at the moment), and pipelines work as expected in the new version.
2. In the cases when the configurations are customized per the [docs](https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/pipelines/#configuring-persistent-data-for-pipeline-components), check that they are untouched after the upgrade.

**Comment by kingsd041** [comment]
rancher/rancher:master-head (08/27/19)
 
Currently blocked from testing by https://github.com/rancher/rancher/issues/21777#issuecomment-524912246

**Comment by kingsd041** [comment]
I tested rancher to upgrade from `v2.2.8` to `master-head` and configured persistent data. The pipeline-jenkins-server is upgraded to `v0.1.4`.
The pipeline works as expected in the new version
