### ISSUE TITLE
UI: Cannot update node count in Tencent hosted k8s

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18525]
UI for https://github.com/rancher/rancher/issues/17175

**Comment by rootwuj** [comment]
@loganhz 
It is best not to bring in the `Secret ID` directly when editing the cluster.
<img width="1350" alt="edit" src="https://user-images.githubusercontent.com/42061003/53935822-c4336580-40e2-11e9-9a43-765ab3caa9a7.png">

**Comment by loganhz** [comment]
@rootwuj we don't hide the secret id usually. User can see it in api if we hide it here.

**Comment by rootwuj** [comment]
@loganhz  I got it thank you.

**Comment by rootwuj** [comment]
Version: master 2.2 (3/7/19) Image ID: a3f8c48fe1e6
Validate fixed.
