### ISSUE TITLE
New rancher/rancher container stuck at infinite loop trying to get https://git.rancher.io/charts/index.yaml (404 error)

### ISSUE THREAD

**Issue by rawzone** [rancher/rancher#18530]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.1.6 --acme-domain rancher.example.com`

On a fresh install of Ubuntu 16.04 running docker 18.06.2

**Result:**

The container never get fully started as it get stuck at at loop checking for a file that gives a 404 error.

This is from the docker logs command:

`2019/03/02 06:32:42 [ERROR] CatalogController library [catalog] failed with : Timeout in HTTP GET to [https://git.rancher.io/charts/index.yaml], did not respond in 30s`

**Other details that may be helpful:**

The file also gives a 404 if i manuel try to fetch it either with curl or in a browser.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:v2.1.6
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom test cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
metal - Intel Xeon CPU and 16GB RAM
- Kubernetes version (use `kubectl version`):
No version returned as the rancher didn't start and it's a new cluster setup.

**Comment by superseb** [comment]
This is not a blocking operation for the container to start, I see the same in my airgapped setup and the UI/API is still accessible. If it's really continuously looping, please provide the complete log of the container.

What does `curl https://rancher.example.com` return on the host running the container?

**Comment by rawzone** [comment]
Hey @superseb 
Thanks for your reply. Feel free to close the issue - It seemed to be our IDS system killing off the network connection.

Moved the host out of the IDS network and now it works like a charm.

What made me thing of this was that i was looking over other issues talking about the index.yaml and someone suggested to try the `git ls-remote https://git.rancher.io/charts` in the container - And it got an alert up on the IDS i was watching. Not entire sure why it got flagged.

But i now have a working container - So again, please close the issue and sorry for the trouble.
