### ISSUE TITLE
Include 18.06 and 18.09 in docker install url dropdown and default to 18.09 when creating node templates.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18536]
Rancher server version - v2.0.12-rc1

Steps to reproduce the problem:
When creating a node template , docker install url dropdown does not include 18.06 and 18.09 version.

<img width="797" alt="screen shot 2019-03-03 at 10 08 33 am" src="https://user-images.githubusercontent.com/4266958/53699427-e785aa00-3d9c-11e9-9e55-afe0c98ceae5.png">

Expected behavior:
Docker install url dropdown  should include 18.06 and 18.09  and  default to docker version 18.09.

**Comment by alena1108** [comment]
Can be tested in `v2.0.12-rc2`

**Comment by sangeethah** [comment]
Tested with Rancher server version - v2.0.12-rc2

18.06 and 18.09 are presented as options in docker install url dropdown and is defaulted to 18.09 when creating node templates.
