### ISSUE TITLE
AKS - fail to provision an AKS cluster because the default k8s version is not supported 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18532]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher: v2.0.12-rc1 container
- add a new AKS cluster

when you add an AKS cluster, the option for k8s version is collapsed, (see the `cluster options` section) so if you don’t choose a version the default is `1.8.11` which is not supported by AKS anymore, and therefore causes failure.
![aks-2-0-12-rc1](https://user-images.githubusercontent.com/6218999/53685371-eab66280-3cd6-11e9-9be2-bc482bd08f54.png)

**Result:**
<img width="577" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53685373-f013ad00-3cd6-11e9-8cb1-d87fd75d84dd.png">
<img width="1273" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53685376-f30e9d80-3cd6-11e9-9fc3-1974cf64a5c9.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.0.12-rc1
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by alena1108** [comment]
Can be tested in `v2.0.12-rc2`

**Comment by jiaqiluo** [comment]
The bugfix is validated  on Rancher:v2.0.12-rc4
The default k8s version for AKS is 
```
kubernetesVersion": "1.12.6"
```
And the cluste is provisioned successfully.
