### ISSUE TITLE
Make docker versions 18.06 and 18.09 supported versions.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18537]
Rancher server version - v2.0.12-rc1

Steps to reproduce the problem:
Create a RKE cluster with docker version 18.09 by choosing " Require a supported Docker version" . 

Cluster provisioning fails with following errors:
<img width="1109" alt="screen shot 2019-03-03 at 10 58 22 am" src="https://user-images.githubusercontent.com/4266958/53700046-4a7a3f80-3da3-11e9-8902-9ffbb0294b0e.png">

Expected Behavior:
Docker version  18.06 and 18.09 should be supported versions.

**Comment by alena1108** [comment]
Can be tested in `v2.0.12-rc2`

**Comment by sangeethah** [comment]
@alena1108 This requires a new version of RKE that supports docker version 18.06 and 18.09 ?

**Comment by alena1108** [comment]
Should be available in `v2.0.12-rc3`

**Comment by sangeethah** [comment]
This issue still reproduces using v2.0.12-rc3.

**Comment by sangeethah** [comment]
Tested with v2.0.12-rc4.

This issue is not reproducible anymore.

Able to create  RKE cluster with docker version 18.09 by choosing " Require a supported Docker version" successfully.
