### ISSUE TITLE
The Rancher Windows related images should be in release image list

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#18534]
The Rancher Windows image list is missing in `rancher-images.txt` and the related tool scripts for Windows images are missing also. We need to add them.

Since the images in `rancher-images.txt` will be used bash shell script, we can not just add Windows images into `rancher-images.txt`. We need to create the `rancher-windows.images.txt` to store the Windows image list. And we would have `rancher-load-images.ps1`, `rancher-save-images.ps1` and `rancher-mirror-to-rancher-org.ps1` powershell scripts for that list.

**Comment by loganhz** [comment]
@thxCode please validate it when we have a new RC release. Low risk issue as it's for windows air-gapped env

**Comment by loganhz** [comment]
Verified in rc4

rancher-load-images.ps1
rancher-mirror-to-rancher-org.ps1
rancher-save-images.ps1

```
rancher/calico-cni:v0.0.1-nanoserver-1803
rancher/canal-cni:v0.0.1-nanoserver-1803
rancher/flannel-cni:v0.0.1-nanoserver-1803
rancher/hyperkube:v1.11.8-nanoserver-1803
rancher/hyperkube:v1.12.6-nanoserver-1803
rancher/hyperkube:v1.13.4-nanoserver-1803
rancher/kubelet-pause:v0.0.1-nanoserver-1803
rancher/nginx-proxy:v0.0.1-nanoserver-1803
rancher/rancher-agent:v2.2.0-rc4-nanoserver-1803

```
