### ISSUE TITLE
feature request: support self-signed SSL certificates on agents

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#1853]
Tried joining a host to a server with SSL enabled and using a self-signed cert. In the agent's logs: `level="fatal" msg="Failed to connect to proxy." error="x509: certificate signed by unknown authority"`. It would be great to be able to use a self-signed certificate in situations where only encryption is of interest and not authentication.

**Comment by ka2er** [comment]
+1 : would be great to allow agent to connect to server served via https+self signed certificates

**Comment by kaos** [comment]
+1

**Comment by sebmoule** [comment]
+1 this is really needed

**Comment by smaccona** [comment]
We managed to solve this with custom builds of `rancher/server`, `rancher/agent` and `rancher/agent-instance`. I detailed our approach at https://github.com/rancher/rancher/issues/2237#issuecomment-149386553

**Comment by kaos** [comment]
@smaccona Thank you. That's pretty close to what I did, although I gave up when I reached the point that I had to patch the python tar ball in rancher/server.. But seeing that you actually managed to get it to work is cool :)

**Comment by sstine** [comment]
+1 really need this.  Something like what Flocker does might work:  https://docs.clusterhq.com/en/latest/docker-integration/configuring-authentication.html

**Comment by will-chan** [comment]
I believe this is now supported.

**Comment by deniseschannon** [comment]
http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta

**Comment by exocode** [comment]
@deniseschannon the docs link ended in a 404 error page 
![bildschirmfoto 2017-02-10 um 22 33 17](https://cloud.githubusercontent.com/assets/1597621/22832540/fb6b6476-efe0-11e6-87e3-9e3541eabf5f.png)

**Comment by deniseschannon** [comment]
@exocode I updated the link for the current latest (1.4)
