### ISSUE TITLE
Workload with Host port fails on docker v18.6.3 but works on docker v18.9.3

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18533]
**What kind of request is this:** bug

**Steps to reproduce:**
1. Launch Rancher UI and create a cluster with nodes - docker `version 18.6.3`.
2. Deploy a workload with Host port. 

**Expected Result:**
Host port service should work

**Actual Result:**
Host port service must work.

**Other details that may be helpful:**

**Environment information**
- Rancher version: rancher:v2.1.7-rc7
- Installation option: single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Amazon EC2
- Kubernetes version (use `kubectl version`):

```
v1.12.6
```

- Docker version (use `docker version`):

```
18.6.3
```

**Comment by sangeethah** [comment]
Host port is not accessible because of the ports not being opened in the Security Group that were used for the AWS nodes in the cluster.
Once the ports are opened in the SG , host port is functional.
