### ISSUE TITLE
Fail to create EC2 cloud credential if you change the region option

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18538]
**Rancher version**
master 3/4

**Steps to reproduce (least amount of steps as possible):**
1. In a fresh standalone rancher, go to node templates - Add Template
2. check that template type is Amazon EC2(the default)
3. Click on the `Region` option, change it to `ap-southeast-1` from the default `us-west-2`
4. Input name, access key and secret key, then click `Create`

**Result:**
Validation error pops up in the UI:
![image](https://user-images.githubusercontent.com/5697937/53706678-6db9f300-3e66-11e9-8565-a742b2c31ce0.png)

**Other details that may be helpful:**
1. The cloud credential fields are not passed to backend in the API input.
2. If you input name, keys, then change the region option, the name/keys are gone.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/5/19) HA setup
Confirmed issue. I no longer reproduce the specific error. Now we just get an expected error stating that there was a problem validating the keys. We are not authorized to make nodes in this region. I tested several regions and they are working as expected (ones we are authorized for and ones we are not authorzied for we get an expected message in the UI as pictured below)

unauthorized expected message:
![image](https://user-images.githubusercontent.com/45179589/53827852-50098e00-3f39-11e9-82d3-a6d0a252320a.png)

authorized is working (must be in US with our QA testing key):
![image](https://user-images.githubusercontent.com/45179589/53827943-834c1d00-3f39-11e9-8a37-f2334ee2b82a.png)
