### ISSUE TITLE
Allow customizing generated DNS name pattern

### ISSUE THREAD

**Issue by nheinemans** [rancher/rancher#18544]
**Feature request**

**Details:**
When exposing a service in rancher 2.1, a DNS name is generated, specifically to be used for xip.io. It looks like the pattern to generate this name is hard coded here:
https://github.com/rancher/rancher/blob/master/pkg/controllers/user/ingresshostgen/ingresshostgen.go

We don't use xip.io, but we do want to generate DNS names using a slightly different pattern. Therefore, we would like to change the pattern.

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.6
- Installation option (single install/HA): HA

**Comment by nheinemans** [comment]
Any update or insight on this request?

**Comment by BobVanB** [comment]
Any updates on this request?

**Comment by bestksw** [comment]
"xip.io" is too unstable in my region, so I always specify a "nip.io" hostname instead of using automatically generated hostname in ingress edit page.
