### ISSUE TITLE
Only remove etcd snapshots after successful snapshot creation

### ISSUE THREAD

**Issue by kylerome** [rancher/rancher#18548]
**Enhancement**

**Result:**
It appears Rancher continues to delete snapshots even if a creation is unsuccessful.  This can lead to removing all etcd snapshots if the issue is not noticed within the retention period.

For reference: https://github.com/rancher/rke-tools/blob/c0f4a7744d3b8e93bfadc9c952f78e38889cc3b4/main.go#L274

**Environment information**
- Rancher version `rancher/rancher` 2.1.6

**Comment by soumyalj** [comment]
Tested with fresh install of master build from March 8th
```
1. Created cluster with 3 nodes(N1, N2, N3) having set snapshot creation as 1h and retention count as 1
2. Powered OFF two nodes N2 and N3, and waited for an hour.
3. The snapshot in node 1 was not deleted.
The issue is fixed in fresh install of master.
```

Tested on an upgrade from v2.1.7 to master. 
1. Created cluster in v2.1.7 with 3 nodes(N1, N2, N3) having set snapshot creation as 5m and retention time as 20m
2. Upgrade to master. After upgrade, the legacy snapshots were still functional. 
3. Powered OFF two nodes N2 and N3, and waited for 20m.
The snapshots in node 1 were deleted . 

```
root@soumyadoupgbugtest1:/opt/rke/etcd-snapshots# ls -ltr
total 13596
-rw-r--r-- 1 root root   27158 Mar 10 01:46 pki.bundle.tar.gz
-rw-r--r-- 1 root root 3469344 Mar 10 02:26 2019-03-10T02:26:43Z_etcd
-rw-r--r-- 1 root root 3469344 Mar 10 02:31 2019-03-10T02:31:43Z_etcd
-rw-r--r-- 1 root root 3469344 Mar 10 02:36 2019-03-10T02:36:43Z_etcd
-rw-r--r-- 1 root root 3469344 Mar 10 02:41 2019-03-10T02:41:43Z_etcd
root@soumyadoupgbugtest1:/opt/rke/etcd-snapshots# date
Sun Mar 10 02:42:44 UTC 2019
root@soumyadoupgbugtest1:/opt/rke/etcd-snapshots# ls -ltr
total 6812
-rw-r--r-- 1 root root   27158 Mar 10 01:46 pki.bundle.tar.gz
-rw-r--r-- 1 root root 3469344 Mar 10 02:36 2019-03-10T02:36:43Z_etcd
-rw-r--r-- 1 root root 3469344 Mar 10 02:41 2019-03-10T02:41:43Z_etcd
root@soumyadoupgbugtest1:/opt/rke/etcd-snapshots# ls -ltr
total 6812
-rw-r--r-- 1 root root   27158 Mar 10 01:46 pki.bundle.tar.gz
-rw-r--r-- 1 root root 3469344 Mar 10 02:36 2019-03-10T02:36:43Z_etcd
-rw-r--r-- 1 root root 3469344 Mar 10 02:41 2019-03-10T02:41:43Z_etcd
root@soumyadoupgbugtest1:/opt/rke/etcd-snapshots# ls -ltr
total 3420
-rw-r--r-- 1 root root   27158 Mar 10 01:46 pki.bundle.tar.gz
-rw-r--r-- 1 root root 3469344 Mar 10 02:41 2019-03-10T02:41:43Z_etcd
root@soumyadoupgbugtest1:/opt/rke/etcd-snapshots# ls -ltr
total 3420
-rw-r--r-- 1 root root   27158 Mar 10 01:46 pki.bundle.tar.gz
-rw-r--r-- 1 root root 3469344 Mar 10 02:41 2019-03-10T02:41:43Z_etcd
root@soumyadoupgbugtest1:/opt/rke/etcd-snapshots# ls -ltr
total 3420
-rw-r--r-- 1 root root   27158 Mar 10 01:46 pki.bundle.tar.gz
-rw-r--r-- 1 root root 3469344 Mar 10 02:41 2019-03-10T02:41:43Z_etcd
root@soumyadoupgbugtest1:/opt/rke/etcd-snapshots# ls -ltr
```

**Comment by moelsayed** [comment]
@soumyalj The fix for this issue is in the `rke-tools` image. This will require the user to upgrade the cluster following the rancher server upgrade to get the latest image with the fix.

**Comment by alena1108** [comment]
@soumyalj please close the issue after ensuring that it fixed on the clusters that are upgraded to the latest version of 1.12.x or 1.13.x

**Comment by soumyalj** [comment]
Tested with upgrade from v2.1.7 to master. 
Case 1:
1. Created cluster with 3 nodes(N1, N2, N3) having set snapshot creation as 1h and retention count as 1 in v2.1.7 with k8s 1.12.6
2. Upgraded cluster to master and K8s to v1.13.4
3. Powered OFF two nodes N2 and N3, and waited for an hour.
4. The snapshot in node 1 was not deleted.

Case 2:
1. Created cluster with 3 nodes(N1, N2, N3) having set snapshot creation as 1h and retention count as 1 in v2.1.7 with k8s 1.13.4
2. Upgraded cluster to master 
3. Powered OFF two nodes N2 and N3, and waited for an hour.
4. The snapshot in node 1 was not deleted.
