### ISSUE TITLE
Windows - host-gw network cannot setup

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#18542]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- Add `Custom` cluster
- Choose `Flannel` Network plugin, choose `Windows` support
- Setup a Linux host as `contorlplan, etcd & worker` node
- Add a Windows host as `worker` node

**Result:**
Windows network cannot work as expected

**Other details that may be helpful:**
UI create action POST - https://XXXX/v3/cluster?_replace=true:
![image](https://user-images.githubusercontent.com/3394724/53715936-5262de00-3e8e-11e9-8f31-2b1448f51b8e.png)

But [RKE doc](https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/network-plugins/#flannel-network-plug-in-options) network plugin config:
![image](https://user-images.githubusercontent.com/3394724/53715829-fa2bdc00-3e8d-11e9-8d14-413cfe1388e1.png)

Get-HNSNetwork in windows node:
![image](https://user-images.githubusercontent.com/3394724/53716381-b1752280-3e8f-11e9-8be2-e6f6d7374236.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.0-rc2-nanoserver-1803
- Installation option (single install/HA): single

**Comment by kingsd041** [comment]
Version: master 2.2 (3/6/19) 
Confirmed fix. Followed the same steps as the ticket describes and got the expected result
![image](https://user-images.githubusercontent.com/19684717/53854988-b3adbd00-4006-11e9-8484-818b965f4fe7.png)

Windows pods and Linux pods can ping each other and can access windows pods using nodeport
