### ISSUE TITLE
Switch to other projects, cache the config of logging

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18541]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Rancher version:** rancher/rancher:master 03/04

**Steps to reproduce (least amount of steps as possible):**
1. Enable project level logging
2. Configure logging advanced mode, add configuration and save
3. Click the Global drop-down menu to switch to another project.

**Result:**
After switching to other projects, the config of the original project logging is displayed.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/4/19)
Confirmed issue. This is now fixed, follow the steps to reproduce and when I use the global menu to switch to another project I see that my project logging "Edit as File" text field is now default again:
![image](https://user-images.githubusercontent.com/45179589/53757580-46205600-3e79-11e9-9baf-3a0e9a49093d.png)
I did not identify any issues with smoke testing I performed in this area.
