### ISSUE TITLE
UI: Used wheel needs fix on mouseover chart

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18559]
Version: Master 2.2 (3/4/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Have a cluster with 2 or more nodes. Do NOT enable monitoring.
- View the cluster page so you see the CPU/Mem/Pod wheels.
- Mouseover the min/max/average bar as pictured below.

**Result:**
Noticed this is related to recent issue #18500 
Notice the word "Value" should be "Reserved"
![screen shot 2019-03-04 at 4 41 48 pm](https://user-images.githubusercontent.com/45179589/53770568-cdcb8c00-3e9c-11e9-9aff-df7b99a0844a.png)

This is working when monitoring is enabled:
![screen shot 2019-03-04 at 4 41 22 pm](https://user-images.githubusercontent.com/45179589/53770574-d58b3080-3e9c-11e9-8d34-0cb8dce8d48e.png)
(Picture shows Used but both Reserved and Used work when monitoring is on)

**Other details that may be helpful:**
Tested on HA Setup on Master 2.2 (3/4/19)

**Comment by loganhz** [comment]
Close it as the outline has been removed in master as well
