### ISSUE TITLE
Tolerations editor still very broken in 2.1.6

### ISSUE THREAD

**Issue by sarg3nt** [rancher/rancher#18550]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Scenario 1:
  1. Add a toleration either via YAML or via the GUI and launch the workload
  2. Edit the workload and view the toleration, often, data is missing.  An example of this is if you launch the Rancher provided DataDog chart.  The chart adds tolerations to run the workload on the etc and control plane nodes, but editing the chart and showing the tolerations breaks them
  3. Save your changes, the tolerations that loaded improperly will be removed

Scenario 2: 
  1.  Add a new workload and add the Kubernetes approved tolerate everything toleration via the GUI
       - operator: "Exists"
       From: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  2.  Save the workload.  The toleration is removed as I guess it does not match validation (even though it is valid)  Note: there is no error reported, which is another bug IMHO.

**Result:**
When valid tolerations are loaded via the GUI they are often loaded incorrectly then deleted on save.
When a valid toleration that does not match the validation is loaded, it too is deleted on save.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.6
- Installation option (single install/HA): Single

**Comment by codyrancher** [comment]
This appears to be a backend issue. While working on reproducing scenario 1 I noticed that what the backend is returning is completely different from what the frontend is sending.

Frontend sends:
![Screen Shot 2019-10-21 at 5.23.53 PM.png](https://zube.io/files/rancher/2e56c36162ad62799905aab90d57cac8-screen-shot-2019-10-21-at-5-23-53-pm.png)

Backend returns:
![Screen Shot 2019-10-21 at 5.24.03 PM.png](https://zube.io/files/rancher/ad82253baa46cf598ab9cf5c10d08a7f-screen-shot-2019-10-21-at-5-24-03-pm.png)

**Comment by westlywright** [comment]
Can we retest this? My initial tests passed but my Datadog chart no longer has toleration added AFAIKT, so I was using my own workloads and some of the system workloads/containers to validate. 

I believe the this is where the issues were resolved

https://github.com/rancher/ui/pull/3439/commits/560a7cbc71b4225cd5b8b58e2b035b265d87eae5

**Comment by khushboo-rancher** [comment]
I tested both the scenarios in latest version. They worked fine.
In 2.1.6 toleration effect doesn't get saved first time on deploying workloads with toleration. However when I tried editing workloads second time, it got saved.

**Comment by deniseschannon** [comment]
@westlywright Can we look at fixing this for the Datadog 1.1.0 chart? There may be other charts that use tolerations and it sounds like it's not working in general.

**Comment by westlywright** [comment]
@deniseschannon I had a chance to sync up with @khushboo-rancher about this. What we are seeing on edit of the workload/container is valid. Because the chart does not include an operator or effect (excluding both is a valid configuration) the inputs for those fields being empty is valid and because we're editing the node we can't just change those.

There does seem to be a bug in the scheduling that @khushboo-rancher found, when deploying the datadog 1.1.0 app is that regardless of the toleration's the workload is deployed on every node not just workers.

**Comment by deniseschannon** [comment]
@khushboo-rancher Can you try with v2.4.0-rc1 to see if that datadog chart is even available? It seems that the chart was broken, therefore we should be able to close this isue.

**Comment by khushboo-rancher** [comment]
In v2.4.0-rc1 datadog chart is available.
Issue: 
1. The option in data dog to enable/disable 'datadog pods on control plane node' is suppose to add toleration in daemon set deployed by app but no toleration is getting added. 
<img width="682" alt="toleration-option" src="https://user-images.githubusercontent.com/60111667/75743339-7fc2b180-5cc5-11ea-82df-3d78432f7668.png">
2. Irrespective of enabled or disabled, daemon set runs on all nodes - control plane node and worker node.

**Comment by westlywright** [comment]
@khushboo-rancher @maggieliu @deniseschannon I checked 2.4.0-rc2 and I only see version 1.33.0

**Comment by khushboo-rancher** [comment]
Even in version 1.33.0 problem exists.

**Comment by sarg3nt** [comment]
Closing as it's super old and I doubt anyone cares any longer.
