### ISSUE TITLE
Reserved wheel greater than circumference of circle for a while when add a node

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18553]
Version: Master 2.2 (3/4/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, Minor

**Steps to reproduce (least amount of steps as possible):**
- Have a cluster with 1 node. Enable monitoring. View the Cluster page to see the wheels.
- Add a node, quickly go back to the cluster page while the node is provisioned.

**Result:**
After a while you will see the CPU reserved wheel will probably circle around itself especially if your nodes only have a couple of CPUs. It looks like we don't have prometheus information yet so it's hard to see in the picture but we have 1.7 of 4 Reserved and 0.4 of 2 Used. This disparity likely is what causes the issue.
![image 4](https://user-images.githubusercontent.com/45179589/53759126-d57b3880-3e7c-11e9-93c9-e95febff04af.png)

Once prometheus is up and we have info this is fixed without a refresh of the page. But it can look like this for 30-60 seconds.

**Other details that may be helpful:**
Master 2.2 (3/4/19) on HA Setup

**Comment by vincent99** [comment]
What's happening is that as soon as the node appears we know how much is reservable, but it takes some time for Prometheus to have data for it.  (You can see below the hover that it's 1.7 of 4 reserved, so another 2gb node appeared)

So the scale of the wheel should go from 0 to `max(usable, reservable)` (in this case max(2,4) == 4).  That will make the "used" part only take up half of the wheel and its gray area stop at the top in this case, temporarily until prometheus stats come in.

I also think we should probably drop the black outline thing and the center dot in general.  They're too busy and nobody knows what they mean.  How about just a small marker at the min/max individual node point, if they're at least a far enough away from the average to be fully displayed? (maybe 5% different?  You'll need to play with it)

Top-quality artist's rendering:

![image](https://user-images.githubusercontent.com/753917/53759905-9e0d8b80-3e7e-11e9-9e44-f9d186ae440c.png)

**Comment by davidnuzik** [comment]
@loganhz FYI I am now seeing this on latest master staying. It will never go away unless I manually refresh or leave the page and come back. Probably not completely necessary for v2.2 but if it's an easy fix would be nice to fix in my opinion:
![image](https://user-images.githubusercontent.com/45179589/54218679-43da7f00-44ab-11e9-9187-d9ccde42e8ff.png)

**Comment by loganhz** [comment]
sure, we will look at it today.

**Comment by loganhz** [comment]
@davidnuzik fixed and moved into 2.2

**Comment by loganhz** [comment]
```
This isn't the fix I was taking about, you're just capping it at 100%. Both wheels should be based on the same scale, from 0 to max(2,4) = 4 for the CPU example.

Then the inner wheel gray should end at the top of the wheel (2 is half of the max of 4) because the rest is not possible (yet), and the green fill 54% of that gray area (which is the same as 1.1/4 if the whole wheel).
```

Move it out from 2.2 as there is still something need to be changed.

**Comment by loganhz** [comment]
Close it as the outline has been removed
