### ISSUE TITLE
rancher新增节点

### ISSUE THREAD

**Issue by shushulele** [rancher/rancher#18567]
*Describe your issue here*

rke新增节点成功后，在rancher页面看不到新增的节点，请问下该如何更新呢？

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.6` UI: `v2.1.6` |
|Route|`global-admin.clusters.index`|

**Comment by shushulele** [comment]
error="websocket: bad handshake"

**Comment by jpd-dds** [comment]
Here's a Google Translate of what we have so far.
Subject: Add node

rke新增节点成功后，在rancher页面看不到新增的节点，请问下该如何更新呢？ == 
After rke added a node successfully, I can't see the new node on the rancher page. How can I update it?

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
