### ISSUE TITLE
After deleting Ingress using Kubectl, rancher LB service does not get deleted

### ISSUE THREAD

**Issue by jira-sync-svc** [rancher/rancher#18569]
Rancher versions:
rancher/server or rancher/rancher: v1.6.18-patch1-rc2

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
HA

Steps to Reproduce:

* There are more than 100 ingress created on the Kubernetes environment. 
* There will be corresponding 100 loadbalancer services launched on rancher backing the ingress
* Delete an Ingress using Kubectl
* The corresponding loadbalancer service is not deleted sometimes and gets listed under Rancher UI.
* The issue is seen intermittently.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/18568
