### ISSUE TITLE
AKS - cluster's state is unstable 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18562]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run rancher v2.0.12-rc2
- add an AKS cluster

**Result:**
- it is extremely slow to click to open any page in this cluster from Rancher's UI for most of the time
- The cluster's state goes to `Unavailable` frequently although it is active in Azure's dashborad

<img width="1490" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53772888-62d28300-3ea5-11e9-8c1c-8afca15c51c6.png">
<img width="1481" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53772894-65cd7380-3ea5-11e9-85ca-5fdf592101f8.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
 v2.0.12-rc2
- Installation option (single install/HA):
single install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/14354 ?

**Comment by sangeethah** [comment]
This is a known issue with v2.0.x version.
