### ISSUE TITLE
After deleting Ingress using Kubectl, rancher LB service does not get deleted when number of ingresses/lbs > 100

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#18568]
Rancher versions:
rancher/server or rancher/rancher: v1.6.18-patch1-rc2

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
Single node

Steps to Reproduce:
- There are more than 100 ingress created on the Kubernetes environment. 
- There will be corresponding 100 loadbalancer services launched on rancher backing the ingress
- Delete an Ingress using Kubectl
- The corresponding loadbalancer service is not deleted sometimes and gets listed under Rancher UI.
- The issue is seen intermittently.

**Comment by deniseschannon** [comment]
Available with  lb image tag: v0.9.10

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.27-rc1`

**Comment by soumyalj** [comment]
Reproduced the issue in v1.6.18-patch1-rc2 as mentioned above

**Comment by prachidamle** [comment]
The image used for this test is not the correct image - so this fix is not available for the above test done, we need to update rancher-catalog template to deliver the new image rancher/lb-service-rancher:v0.9.11

**Comment by soumyalj** [comment]
Tested with v1.6.27rc1 using updated K8s catalog. K8s - v1.12.7-rancher1-1-1
1. Created Kubernetes environment 
2.Created around 140 ingresses
3. Deleted ingresses using kubectl.
The ingress gets deleted through kubectl and the corresponding LB service is also deleted in UI. 
Tested with deleting multiple ingresses and it worked successfully.
