### ISSUE TITLE
Hardcoded assign_ipv6_address_on_creation in somewhere to false (not working Assign IPv6 on creation) for ec2 instances

### ISSUE THREAD

**Issue by josenobile** [rancher/rancher#18573]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** Create a subnet with AssignIpv6AddressOnCreation = true and use that subnet to launch a instance from Rancher

**Result:**
Instance is created without a IPv6 assigned.

**Other details that may be helpful:**
Creating a instance using  the EC2 management console in such subnet will result in a instance with an IPv6 assigned.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.3
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): c5.large
- Kubernetes version (use `kubectl version`): 1.12.3

- Docker version (use `docker version`): 17.3.2

**Comment by vincent99** [comment]
This is probably in docker-machine, but Kubernetes doesn't support dual-stack anyway, so your goal may be mostly moot...

**Comment by josenobile** [comment]
@vincent99  Just to clarify, I need IPv6 communication from inside Docker to external only IPv6 networks, that is not achievable with AWS EC2 -> Rancher -> Kubernetes -> Docker?

**Comment by vincent99** [comment]
Kubernetes supports IPv4-only or IPv6 only, but not both together (dual-stack) and pods/services/nodes/etc having one of each kind of address.  If you just need to talk to an external thing that has only a v6 address, that might be possible.

I'd launch some nodes in EC2 manuallyy and make a "custom" cluster out of them.  If you can get them to do what you want, then there would be a reason to look into who/where is disabling v6 in the docker-machine flow.
