### ISSUE TITLE
Config logging advanced mode will enter the elasticsearch advanced mode

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18570]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Rancher version:** rancher/rancher:master 03/05

Config logging advanced mode. Regardless of the choice of any logging target, it will switch to the elasticsearch advanced mode.

```
<match *>
  @type elasticsearch
  
</match>
```

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/5/19)
Confirmed issue. I no longer reproduce, this is working as expected now.
Pick the target you want in the UI (Edit as Form) then switch to Edit as File and it will show the right target per what you picked. 

Some examples below:

pick fluentd target then switch to advanced mode (Edit as File):
```
<match *>
  @type forward
  
</match>
```

pick splunk target then switch to advanced mode (Edit as File):
```
<match *>
  @type splunk_hec
  
</match>
```

I tested with all the providers and they all work. They show the correct type for each.
