### ISSUE TITLE
Monitoring - Unable to configure additional parameters via upgrading Rancher-Monitoring APP by GUI

### ISSUE THREAD

**Issue by jiuchen1986** [rancher/rancher#18576]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enable the cluster monitoring for a cluster:
![image](https://user-images.githubusercontent.com/33239761/53784018-d381aa00-3f4e-11e9-9495-09c0f2fa055c.png)

The container prometheus in pod prometheus-cluster-monitoring-0 hits the memory limit, which is 500Mi by default (This happens only when lots of workload exist in cluster. Whether the container hits the memory limit has no impact on following steps and results):
![image](https://user-images.githubusercontent.com/33239761/53784107-2a877f00-3f4f-11e9-9feb-58b676170166.png)

Track the memory limit spec in prometheus resouce object:
```
# while true;do date;kubectl get -n cattle-prometheus prometheus cluster-monitoring -o jsonpath='{.spec.resources.limits.memory}{"\n"}';sleep 2;done
Tue Mar  5 07:12:31 CET 2019
500Mi
Tue Mar  5 07:12:33 CET 2019
500Mi
Tue Mar  5 07:12:35 CET 2019
500Mi
Tue Mar  5 07:12:38 CET 2019
500Mi
```

Increase the memory limit for prometheus container by adding a parameter which is not present on the upgrading APP page by default, and upgrade the Rancher-Monitoring APP:
![capture](https://user-images.githubusercontent.com/33239761/53784751-40963f00-3f51-11e9-9077-3ebbf0b6bbab.JPG)
Those parameters in the red circle are present when open the upgrading page of Rancher-Monitoring APP by default, while the last one is newly added to increase the memory limit of prometheus.

**Result:**
After upgrading the APP, the newly added parameter first takes effect for several minutes waiting for old prometheus pod to remove, but then change back to the default value by itself when new prometheus pod gets up:
![image](https://user-images.githubusercontent.com/33239761/53784994-fc576e80-3f51-11e9-93fe-5a3778d9e685.png)
![image](https://user-images.githubusercontent.com/33239761/53785007-07aa9a00-3f52-11e9-9c6f-f3e3beb39e31.png)
![image](https://user-images.githubusercontent.com/33239761/53785103-57896100-3f52-11e9-936c-507909f788ca.png)
![image](https://user-images.githubusercontent.com/33239761/53785468-8e13ab80-3f53-11e9-9c17-64c69317461f.png)
![image](https://user-images.githubusercontent.com/33239761/53785488-9c61c780-3f53-11e9-9247-5cc4b2d47945.png)

I've tried several other additional parameters, which are not present on the upgrading APP page by default, and they behaved similarly.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher 2.2.0-rc2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM with 4 CPU and 16G MEM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.3-1+fee411aca93f0e", GitCommit:"fee411aca93f0e786995cc125cf8f9783484f958", GitTreeState:"clean", BuildDate:"2018-12-04T06:49:44Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.3-1+fee411aca93f0e", GitCommit:"fee411aca93f0e786995cc125cf8f9783484f958", GitTreeState:"clean", BuildDate:"2018-12-04T06:45:24Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-88.git07f3374.el7.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Thu Dec  6 07:01:49 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-88.git07f3374.el7.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Thu Dec  6 07:01:49 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by loganhz** [comment]
Please configure them in monitoring setting page
