### ISSUE TITLE
Publish catalog template step type/description is improper

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18579]
**Rancher version:**
master 3/5

This is what we show at the moment:
![image](https://user-images.githubusercontent.com/5697937/53788063-a091e300-3f5b-11e9-8297-c409cfceacc6.png)

Per the original design it is a `Publish Catalog Template Step`: https://github.com/rancher/rancher/issues/16026

We should change `App` to `Template` or `App Template` in step type/descriptions.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/6/19)
Confirmed issue. All of gitlawr's issues were addressed. As you can see below the words were changed to Template now to make it more clear we are publishing a catalog template:

![image](https://user-images.githubusercontent.com/45179589/53898079-a8519600-3ff4-11e9-8e1b-255075689de0.png)
