### ISSUE TITLE
PKI Bundle backups failing on nodes following HA Cluster restore

### ISSUE THREAD

**Issue by iwalmsley** [rancher/rancher#18583]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

Restore a 3 node HA cluster completely from backups (e.g completely delete/re-create VMs). Restore the backup via the recommended procedure (https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/), using a 'target node' to bootstrap the cluster. Set up standard etcd snapshot backups (e.g every 6 hours). Cluster is restored successfully without issue.

Following this only the initial 'target node' generates pki bundle backups of the certs, the other two nodes which were bootstrapped into the cluster no longer generate this - however do generate the etcd backup fine. This is also true for triggering a backup manually as per below.

**Result:**
```
rancher@ip-2:~ $ rke etcd snapshot-save --name test-snapshot.db --config rancher-cluster.yml
INFO[0000] Starting saving snapshot on etcd hosts       
INFO[0000] [dialer] Setup tunnel for host [ip-1] 
INFO[0000] [dialer] Setup tunnel for host [ip-2] 
INFO[0000] [dialer] Setup tunnel for host [ip-3]
INFO[0000] [etcd] Saving snapshot [test-snapshot.db] on host [ip-1] 
INFO[0001] [etcd] Successfully started [etcd-snapshot-once] container on host [ip-1] 
INFO[0005] [etcd] Saving snapshot [test-snapshot.db] on host [ip-2] 
INFO[0005] [etcd] Successfully started [etcd-snapshot-once] container on host [ip-2] 
INFO[0009] [etcd] Saving snapshot [test-snapshot.db] on host [ip-3] 
INFO[0009] [etcd] Successfully started [etcd-snapshot-once] container on host [ip-3] 
INFO[0013] [certificates] Successfully started [rke-bundle-cert] container on host [ip-3] 
INFO[0013] [certificates] Successfully started [rke-bundle-cert] container on host [ip-2] 
INFO[0013] [certificates] Successfully started [rke-bundle-cert] container on host [ip-1] 
INFO[0013] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [ip-3] 
INFO[0013] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [ip-2] 
INFO[0013] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [ip-1] 
INFO[0013] Finished saving snapshot [test-snapshot.db] on all etcd hosts 
rancher@ip-2~$ ll /opt/rke/etcd-snapshots/
total 914236
drwxr-xr-x 2 root root      4096 Mar  5 11:05 ./
drwxr-xr-x 3 root root      4096 Feb 27 16:14 ../
-rw-r--r-- 1 root root 133734432 Mar  5 10:14 2019-03-05T10:14:36Z_etcd
-rw-r--r-- 1 root root 133734432 Mar  5 11:05 test-snapshot.db
```

**Other details that may be helpful:**

The two nodes which joined the cluster (i.e the non target nodes) do not dump the pki bundle, despite the log messages above. Etcd is being dumped fine, it's only the pki bundle. All functionality works correctly on the initial target node.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.6
- Installation option (single install/HA): HA (3 node cluster)

- Docker version (use `docker version`): 17.03.2-ce

```
~$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Comment by jimliming** [comment]
I was just chasing this. Is your RKE v0.2.0 or later? If so, it seems it no longer generates that bundle and the restore documentation is incorrect.

https://rancher.com/docs/rke/latest/en/etcd-snapshots/ 

> Available as of v0.2.0
>
> RKE can also upload your snapshots to a S3 compatible backend. Additionally, the pki.bundle.tar.gz file usage is no longer required as v0.2.0 has changed how the Kubernetes cluster state is stored.

**Comment by iwalmsley** [comment]
Right - it is indeed later than 0.2.0 so that would explain why it's not being dumped! Not sure how I missed it as it's written all over the docs. Maybe just needs those messages to be altered then?

Thanks alot

**Comment by iwalmsley** [comment]
Sorry have just re-reviewed and actually we've upgraded to 0.2.0 after this issue occurred. Obviously now we are generating the state file we no longer need the pki dump so this isn't a problem, but the version we were running at the time was actually "v0.1.18".
