### ISSUE TITLE
Reboot host or manage system-docker container from web-gui?

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#1858]
It seems I killed my ssh service (console container?) and can't login with ssh anymore...
Rancher web-gui works fine, but there is no chance to reboot the machine or (re-)start an system-docker container.

Maybe useful features?
- Reboot host
- web console
- manage system-docker services

**Comment by fentas** [comment]
:+1: would also have need for that.

**Comment by lavvy** [comment]
+1

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
