### ISSUE TITLE
Quick Start instructions result in HTTP Error 404

### ISSUE THREAD

**Issue by joaompinto** [rancher/rancher#18581]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher
curl -kv https://localhost/

**Result:**
HTTP/2 404

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
18.09.2-ce
```

**Comment by superseb** [comment]
Please provide the complete `curl -kv https://localhost` output. Running this sequence on a fresh machine does not reproduce.

**Comment by joaompinto** [comment]
[jpinto@jpinto-pc ~]$ curl -kv https://localhost 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Colorado; L=Boulder; O=ExampleCorp; OU=IT; CN=*.example.com; emailAddress=admin@example.com
*  start date: Oct 24 21:09:52 2016 GMT
*  expire date: Oct 24 21:09:52 2017 GMT
*  issuer: C=US; ST=Colorado; L=Boulder; O=ExampleCorp; OU=IT; CN=*.example.com; emailAddress=admin@example.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x555935a4ee80)
> GET / HTTP/2
> Host: localhost
> User-Agent: curl/7.64.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404 
< content-type: text/plain; charset=utf-8
< vary: Accept-Encoding
< x-content-type-options: nosniff
< content-length: 19
< date: Tue, 05 Mar 2019 09:44:52 GMT
< 
404 page not found
* Connection #0 to host localhost left intact
[jpinto@jpinto-pc ~]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                      NAMES
da6cf26a165b        rancher/rancher     "entrypoint.sh"     26 minutes ago      Up 26 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   kind_brattain

**Comment by superseb** [comment]
Pretty sure you are not hitting the container at this point, if you stop the container, does the curl stop responding?

Can you try `curl -kv https://127.0.0.1` (although it seems to resolve) or `curl --no-proxy '*' -kv https://127.0.0.1`

**Comment by joaompinto** [comment]
@superseb you are right, I was tricked by iptables rules. Thanks for the quick reponse.

**Comment by yhyddr** [comment]
I have the same question and don't know how to solve
