### ISSUE TITLE
Support Stockholm (eu-north-1) for EC2 region

### ISSUE THREAD

**Issue by lentzi90** [rancher/rancher#18589]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Add new cluster
2. Select Amazon EC2
3. Try to add eu-north-1 as region in the node template

**Result:**
The region does not exist in the list.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.6 (also tested on `master`)
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
Needs https://github.com/rancher/machine/pull/20 before it can be tested.

**Comment by llarsson** [comment]
If this is marked as resolved, when can we hope to get support for this?

**Comment by cjellick** [comment]
next release (v2.2.0)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/8/19) 
Confirmed issue. eu-north-1 region has been added to ec2 node templates.
![image](https://user-images.githubusercontent.com/45179589/54062261-48a8e580-41c2-11e9-910e-abab440702e5.png)
Note: QA test account does not allow creation in this region.
