### ISSUE TITLE
Feature request: Support restrict ability to spin up privileged containers

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#1859]
As an enterprise I'd like to provide teams with Rancher access with free roam on spinning up containers but prevent them from effectively gaining root to host machines so I can feel like I'm in control of my infra.
This could get quite granular with RBAC and things like AD security groups but on the basic level, a toggle within an environment to prevent `--privileged` and other host capabilities would go a long way in the enterprise space.

**Comment by sangeethah** [comment]
This feature will be available in 2.0 release and is tracked as part of this issue - https://github.com/rancher/rancher/issues/11159
