### ISSUE TITLE
Rancher catalog takes up excessive space over time when using Artifactory (5-7GB)

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#18594]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Setup Artifactory to mirror helm repository
2) Setup Artifactory to mirror Incubator repository
3) add both to Rancher's catalog as custom catalogs

**Result:**
Over a month or so /repo/rancher/management-state/catalog-controller grows to 5-7GB in size

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.3
- Installation option (single install/HA): Single

**Comment by superseb** [comment]
Cleanup is implemented in https://github.com/rancher/rancher/pull/17596 for 2.2
