### ISSUE TITLE
Add francecentral to AKS regions

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#18598]
**What kind of request is this (question/bug/enhancement/feature request):**
task

**Steps to reproduce (least amount of steps as possible):**
Add France Central to AKS regions

https://azure.microsoft.com/en-gb/updates/general-availability-azure-kubernetes-service-in-france-central/

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/6/19) ImageID: b39d3427146a

Confirmed France Central has been added to the list of Location options (drop-down) upon AKS creation.
![image](https://user-images.githubusercontent.com/45179589/53897113-ab4b8700-3ff2-11e9-9195-4554499d1b39.png)

Inspect HTTP POST (create cluster) request payload and server response and confirm that in azureKubernetesServiceConfig that `location: "francecentral"` exists.

Inspect Azure web console and ensure the AKS cluster exists at the France Central location.
![image](https://user-images.githubusercontent.com/45179589/53897419-50665f80-3ff3-11e9-9f61-ed269f781cae.png)

Smoke tested and ensured cluster is working correctly.
