### ISSUE TITLE
Containerd version reported as unknown when listing nodes in cluster

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#18593]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Install k3s cluster
2. In Rancher UI, create a custom cluster
3. Apply the YAML on the k3s cluster to import the cluster
4. In Rancher UI, go to the list of nodes

**Result:**
The nodes are listed with Version "containerd://1.2.3+unknown"

**Other details that may be helpful:**
![image](https://user-images.githubusercontent.com/468462/53822470-a4eed980-3f24-11e9-9ec2-a0d4f920b63b.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher v2.1.6
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
AWS
- Kubernetes version (use `kubectl version`):
```
v1.13.3-k3s6
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by dnoland1** [comment]
According to @ibuildthecloud, this is likely a k3s issue and can be tracked here: https://github.com/rancher/k3s/issues/159

**Comment by superseb** [comment]
This should be extended to the Node view:

<img width="1451" alt="Screen Shot 2019-04-15 at 12 15 09" src="https://user-images.githubusercontent.com/2620179/56124980-2bf98d80-5f78-11e9-90ef-980a9e3a0765.png">

**Comment by vincent99** [comment]
Wasn't this already fixed for 2.2?

**Comment by superseb** [comment]
It's fixed in the Nodes view, not in the Node view (or Node detail view)

**Comment by dnoland1** [comment]
Should label be `Docker Version:"`? Should it be changed to just `Version:` or `Runtime Version:`? I don't think containerd is considered a Docker version.

**Comment by superseb** [comment]
Yep, should probably move to what k8s uses:

```                   
"containerRuntimeVersion": "docker://18.9.2",
```

Or something along that displays nicely in the UI

**Comment by superseb** [comment]
Version containing unknown is tracked in https://github.com/rancher/k3s/issues/159, UI in node list view is fixed, node detail view can be tracked in https://github.com/rancher/rancher/issues/21099
