### ISSUE TITLE
Docker 18.09 should be made default for Rancher 1.6 in the UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18596]
Current Rancher version: v1.6.26

Docker 18.09 is supported for Cattle and Docker 18.09 is supported for K8s1.12.6 . 
But the UI defaults to docker version 17.03.
For the next release, UI should default to docker version 18.09

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.27-rc1`

**Comment by soumyalj** [comment]
Tested with rancher/server:v1.6.27-rc1. Verified that Docker 18.09 is set as the default for both Cattle and K8s environments. The setups came up correctly with Docker 18.09 
<img width="1656" alt="Screen Shot 2019-04-11 at 10 25 17 AM" src="https://user-images.githubusercontent.com/18536626/55977871-6a274200-5c44-11e9-971c-c423ff3eac5c.png">
