### ISSUE TITLE
Disabled buttons have different text color on mouseover

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18592]
Version: Master 2.2 (3/5/19)

**RELATED ISSUE:** rancher/rancher#18591 (This issue asks (enhancement) to just change all disabled buttons so there is NO reaction on mouseover).

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Observe on the Drivers page when you have nothing selected hover over the buttons and they react with the button text changing to black. (Screenshot shows Activate button is hovered)
![image](https://user-images.githubusercontent.com/45179589/53821640-70325080-3f2b-11e9-8218-cb9484368446.png)
This is class btn btn-sm bg-default btn-disabled
- Observe on the Add Node Template page if you are creating a cloud key the "Add New" button is the same but for some reason on hover the text turns white. (Screenshot shows Add New button is hovered)
![image](https://user-images.githubusercontent.com/45179589/53821787-ac65b100-3f2b-11e9-9a32-1f9438c9ee4b.png)
This is class btn btn-sm bg-primary inline-block

**Result:**
The two buttons are different but we expect to use the same styling for disabled buttons across the product.

**Other details that may be helpful:**
Please see the related issue above; it might or might not be easier to just do that instead of fixing this bug.

**Comment by cjellick** [comment]
minor, moving out of release

**Comment by davidnuzik** [comment]
Version: master-head (7/26/19)

I can confirm there is now no longer any change in text color upon hover over disabled buttons. This makes it more clear the button is indeed disabled. We also get the "no" mouse cursor when we hover over such buttons.

I tested everywhere I could think of and this appears to work correctly in all areas.

Examples below are screenshots with my mouse hovered over the disabled button; I am not able to show screenshots with the mouse cursor but this is an appropriate "no" cursor in Chrome and Firefox.

![image](https://user-images.githubusercontent.com/45179589/61969141-a762d600-af8e-11e9-82a3-01a888a5a220.png)
![image](https://user-images.githubusercontent.com/45179589/61969157-afbb1100-af8e-11e9-9f5a-5d5b5b6a91fa.png)
These are just a couple of examples. This just proves that on mouseover of these buttons the text color does not change. There is effectively no reaction on hover.
