### ISSUE TITLE
Security Scan (CIS Scan Only)

### ISSUE THREAD

**Issue by jira-sync-svc** [rancher/rancher#18600]
Develop an overall security report. Do the following

* Scan cluster settings
* Check other options

Share results

---------

**Acceptance criteria:**
* Adhoc scan of an RKE cluster
* Must deploy into a CIS level 1 and level 2 cluster.
* Have the ability to have a copy of the report that can be sent to auditors
* Report to show tests that are (configured-skipped) from the test configuration.
* Schedule recurring scans from the UI
* Alert when a failure occurs in the cluster.
* Show run history/results in UI 

**Stretch**
* Updates to CIS Benchmark scans must be out of band to Rancher releases.
* Adhoc Scan Imported
* Adhoc Scan hosted providers.

* CLI Support:
  - Initiate scan and display report.
  - wait for scan to complete.
  - Exit non-zero when scan has failures.

**Comment by cloudnautique** [comment]
The way this ties into Prometheus, Grafana and AlertManager is something we should look at foldig into this feature.

https://github.com/ibrokethecloud/kube-bench-metrics

**Comment by zbialik** [comment]
Will this also be available for air-gapped clusters? Will the CIS Benchmarks be packaged in each rancher release or will they have to get pulled from [kontainer-driver-metadata](https://github.com/rancher/kontainer-driver-metadata)?

**Comment by sowmyav27** [comment]
@zbialik currently it is packaged with ever rancher release. But here is the issue which tracks  `benchmark version info is being moved to k-d-m` - https://github.com/rancher/rancher/issues/24935

**Comment by deniseschannon** [comment]
Closing as the acceptance criteria has been met and all bugs are being tracked elsewhere. The stretch goals have been added to this issue: https://github.com/rancher/rancher/issues/25915
