### ISSUE TITLE
Disable globalDNS collection/resourceMethods 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18603]
As Global DNS would only work on the setups with local cluster present, we should disable collection/resource methods on the setups with no local cluster.

@kinarashah lets make sure UI hides the corresponding tabs when the collection/resource methods are removed.

**Comment by sangeethah** [comment]
Tested with latest build from master - Mar 7 - 6d41993c

Single node install using the following command
```
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master
```

Using this rancher server instance , able to still see GDNS provider and entries under tools .

Also able to create a Gdns provider entry.
<img width="1146" alt="screen shot 2019-03-07 at 8 34 44 pm" src="https://user-images.githubusercontent.com/4266958/54007808-8a7d5180-4118-11e9-82e5-ec684643e640.png">


Rancher server logs:
```
2019/03/08 04:20:29 [INFO] Rancher version 6d41993c is starting
2019/03/08 04:20:29 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
```
```
root@sangee-testserver:~# docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rancher/rancher     master              b4e18ff93fa1        7 hours ago         493MB
```

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/17558

**Comment by sangeethah** [comment]
Tested with latest build from master.
On a single install node , UI does not present Global DNS provider/entries options under "Tools".

Not able to access Global DNS provider/entries using API.

```
https://<ip>/v3/globalDnses/
https://<ip>/v3/globalDnsProviders/
"message": "Method GET not supported",
"status": 405,```
```
