### ISSUE TITLE
CLI changes for multiclusterapp Roles

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#18609]
This issue is based on the roles design refactor issue https://github.com/rancher/rancher/issues/18521

1. Roles is required in API now, so maybe CLI should make it required too
2. UI is only going to present cluster-owner and project-member roles. But we do want API and CLI to allow users to pass other roles. But can CLI add a short description suggesting users to provide the project-member role, or if they know that their app requires cluster role, then use the cluster-owner role?

Already discussed with @gitlawr that this is doable, but opening an issue to track this

**Comment by cjellick** [comment]
@mrajashree to validate

**Comment by mrajashree** [comment]
Tested with v2.2.0-rc13
1. Roles is being handled as mandatory by passing project-member by default
2. The -h option explains why by displaying the following text as expected
```
   --role value                Set roles required to launch/manage the apps in target projects. For example, set "project-member" role when the app needs to manage resources in the projects in which it is deployed. Or set "cluster-owner" role when the app needs to manage resources in the clusters in which it is deployed. (default: "project-member")
```
