### ISSUE TITLE
Remove k8s 1.9, 1.10 from the default versions list

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18606]
Remove support for k8s 1.9 and 1.10 from the default list so the list has support for k8s 1.11, 1.12 and 1.13 - the only versions where Kubernetes back ports CVE fixes.

**Comment by jiaqiluo** [comment]
The enhancement is validated on Rancher:v2.1.7-rc9  on both freshly installed and upgraded scenarios. 

The following are the k8s versions in the supported list when adding an RKE cluster
- 1.13.4-rancher1-1
- 1.12.6-rancher1-1
- 1.11.8-rancher1-1
