### ISSUE TITLE
CLI feature to have users create namespaces within projects

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#18615]
**Feature request:**
add a command to rancher cli that can create a namespace within its specified project

**Steps to reproduce (least amount of steps as possible):**
```
> kubectl get pod
No resources found.
> kubectl create ns test-namespace
namespace/test-namespace created
> kubectl -n test-namespace get pod
Error from server (Forbidden): pods is forbidden: User "u-UID" cannot list pods in the namespace "test-namespace"
```

**Result:**
Currently one is able to create namespaces in no project which prevents the creator from using that namespace.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by jcambronero** [comment]
Thanks for opening this issue @aemneina 
A couple of things to note, first I would consider this a bug and not a feature. Being able to create namespaces that you don't have access to, is a bug in my opinion.

Secondly, in order to be able to replicate the issue simply create a test user with the built-in "project member" role in the default project.
Next, run these commands using the kubectl configuration for the test user:

```
> kubectl get po
No resources found.
> kubectl create ns test-project-member
namespace/test-project-member created
> kubectl -n test-project-member get po
Error from server (Forbidden): pods is forbidden: User "u-3j7i5yuu7m" cannot list pods in the namespace "test-project-member"
```

**Comment by vincent99** [comment]
The feature is to add a command to the `rancher` CLI to add a namespace and associate it to the project.  We can't do anything about`kubectl` allowing you to do only the first half of that.

**Comment by ThunderRush** [comment]
We just ran into this issue today. It's pretty bad if you run a more tight permission scheme for your production cluster.

**Comment by ribx** [comment]
How about an annotation to allow a user to create a namespace with `kubectl` inside a Rencher Project he has permissions to?
