### ISSUE TITLE
Backport RKE cluster cert rotation to 2.1.x

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18612]
We have to address RKE cluster certificate expiration in 2.1.x release line. Need to explore the best way to approach it: either via 2.2 cert rotation feature backport, or by providing a scriptable workaround.

**Comment by jira-sync-svc** [comment]
➤ hussein@rancher.com commented:

Proposed solution:

  * Adding the ability to rotate 2.1.x and 2.0.x clusters to system-tools, the code will do the following:
    * Use kubeconfig to connect to rancher
    * Fetch the cluster object and rkeconfig of the target cluster
    * run rke cert rotate with the fetched rkeconfig

Example:

./system-tools cert rotate --kubeconfig kube_config_cluster.yml --cluster c-fgltwRKE already handles legacy cluster by recreating rke state file from the current certificates, this will require the system-tools code to update the cert secrets including:

kube-system     kube-admin                                       Opaque                                9         3h7m
kube-system     kube-apiserver                                   Opaque                                6         3h7m
kube-system     kube-apiserver-proxy-client                      Opaque                                9         3h7m
kube-system     kube-controller-manager                          Opaque                                9         3h7m
kube-system     kube-etcd-x.x.x.x                                Opaque                                6         42m
kube-system     kube-node                                        Opaque                                9         3h7m
kube-system     kube-proxy                                       Opaque                                9         3h7m
kube-system     kube-scheduler                                   Opaque                                9         3h7m

**Comment by jira-sync-svc** [comment]
➤ hussein@rancher.com commented:

https://github.com/rancher/system-tools/pull/21 ( https://github.com/rancher/system-tools/pull/21|smart-link )

**Comment by alena1108** [comment]
The first pass on the tool can be done with `https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc6`

**Comment by sowmyav27** [comment]
verified with system tool from - `https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc6`. Verified on cluster in  `rancher:v2.1.8`. Get the below error.
```
sowmyaviswanathan$ ./system-tools_darwin-amd64 cert info --url https://x.x.x.x/v3 --token "token-xxx:xxxxxxxx" --cluster c-wk8k2
INFO[0000] Check certificates Info for cluster [c-wk8k2] 
INFO[0000] Setup rkeconfig for cluster [c-wk8k2]        
FATA[0000] http: read on closed response body
```

**Comment by galal-hussein** [comment]
Can be tested with https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc7

**Comment by sangeethah** [comment]
Reopening this issue , Since have made a decision to go with rancher API support for cert rotation and not go with standalone system tool approach.

**Comment by alena1108** [comment]
Instead of system-tools, cert rotation was backported to rancher rke/rancher. The feature can be tested with rancher v2.1.9-rc2.

**Comment by sowmyav27** [comment]
verified following scenarios on:
1. On a fresh install of `v2.1.9-rc3`
2. Upgrade from custom image to `v2.1.9-rc3`
3. upgrade from `v2.1.8` to `v2.1.9-rc3`

On rotating certificates, expiration date of the certs was 10 years from the time of performing the action. Verified pods - kube-proxy, kubelet, nginx-proxy, kube-scheduler, kube-controller-manager and kube-apiserver restarted after rotating the certs. Verified certs changed on all the nodes except for `kube-apiserver-key.pem`
