### ISSUE TITLE
Feature request: Create stacks/services with compose yaml in UI

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#1861]
It is an excellent feature that you can view and copy the `rancher-compose.yml` and `docker-compose.yml` files from created stacks in the UI. The reverse would also be very handy (paste or upload your yaml files to the UI) to avoid going to a command line and using API keys to stand up a stack. A nice to have.

**Comment by lavvy** [comment]
that would be nice, now there is more security in the ui through ldap auth, i think this feature will be nice

**Comment by ibuildthecloud** [comment]
This is in the works.  @wlan0 is there an issue tracking this task?

**Comment by deniseschannon** [comment]
We just created an issue, but have been working on it. I'll close in favor of the feature. https://github.com/rancher/rancher/issues/1865
