### ISSUE TITLE
Backport RKE cluster cert rotation to 2.0.x

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18613]
We have to address RKE cluster certificate expiration in 2.0.x release line. Need to explore the best way to approach it: either via 2.2 cert rotation feature backport, or by providing a scriptable workaround

https://github.com/rancher/rancher/issues/18612

**Comment by jira-sync-svc** [comment]
➤ hussein@rancher.com commented:

Proposed solution:

  * Adding the ability to rotate 2.1.x and 2.0.x clusters to system-tools, the code will do the following:
    * Use kubeconfig to connect to rancher
    * Fetch the cluster object and rkeconfig of the target cluster
    * run rke cert rotate with the fetched rkeconfig

Example:

./system-tools cert rotate --kubeconfig kube_config_cluster.yml --cluster c-fgltwRKE already handles legacy cluster by recreating rke state file from the current certificates, this will require the system-tools code to update the cert secrets including:

kube-system     kube-admin                                       Opaque                                9         3h7m
kube-system     kube-apiserver                                   Opaque                                6         3h7m
kube-system     kube-apiserver-proxy-client                      Opaque                                9         3h7m
kube-system     kube-controller-manager                          Opaque                                9         3h7m
kube-system     kube-etcd-x.x.x.x                                Opaque                                6         42m
kube-system     kube-node                                        Opaque                                9         3h7m
kube-system     kube-proxy                                       Opaque                                9         3h7m
kube-system     kube-scheduler                                   Opaque                                9         3h7m

**Comment by jira-sync-svc** [comment]
➤ hussein@rancher.com commented:

https://github.com/rancher/system-tools/pull/21 ( https://github.com/rancher/system-tools/pull/21 )

**Comment by alena1108** [comment]
The first pass on the tool can be done with `https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc6`

**Comment by sangeethah** [comment]
Fix available in `v2.0.14-rc2` . Cert rotation was backported to rancher rke/rancher. UI support is not available. Can we tested using API UI.

**Comment by bmdepesa** [comment]
All certs rotated through API action.
All scenarios after Rancher deploy are executed as a standard user.

**Fresh install v2.0.14-rc3**
  * Create cluster
  * Logged cert hashes
  * Checked cert expiry
  * Rotated certs successfully

**v2.0.13 to v2.0.14-rc3**
  * Fresh install v2.0.13
  * Create cluster
  * Logged cert hashes
  * Checked cert expiry
  * Preupgrade checks
  * Upgrade to v2.0.14-rc3
  * Rotate certs successfully
  * Postupgrade checks

**v2.0.13 w/ expired certs -> v2.0.14-rc3**
* Deploy Rancher v2.0.13 custom image where certs expire after 30m
* Create cluster
* Check cert hashes and expiry
* Preupgrade checks
* Upgrade to v2.0.14-rc3
* Wait for certs to expire & cluster cannot be accessed
* Rotate certs
* After some time cluster becomes accessible
* Postupgrade checks
