### ISSUE TITLE
rancher no monitoring for etcd in local cluster and import cluster

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#18619]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
Install Rancher as per Rancher 2.x installation guide
https://rancher.com/docs/rancher/v2.x/en/installation/ha/
install K8s cluster using RKE
install helm
install rancher as workload via server-chart
enable monitoring for cluster local

**Result:**
no monitoring Grafana link in cluster local
Alert like 'Etcd member has no leader' in cluster local  show No metric graph data 
Seems etcd monitoring is off
Cluster other than local is ok

![image](https://user-images.githubusercontent.com/15118220/53865194-94cd1c00-4042-11e9-8bfb-4190e928ba93.png)

![image](https://user-images.githubusercontent.com/15118220/53865140-6e0ee580-4042-11e9-88f2-dd064813e1e6.png)

**Comment by davidnuzik** [comment]
v2.2.0-rc14 replicated.

**Comment by cjellick** [comment]
@loganhz can you explain what is going on here?

**Comment by cjellick** [comment]
@loganhz @sangeethah has monitoring local cluster been tested? is it supported

**Comment by loganhz** [comment]
@cjellick Now we only scrap ETCD metrics for RKE cluster (node template or custom).  `local` cluster is an imported cluster.  So it's not in our scope. But maybe we can detect if it is an imported RKE cluster, then we can scrap it.

**Comment by jnne** [comment]
so, but how to monitor local etcd metrics? have any suggestion ? thanks you

**Comment by adeleglise** [comment]
> so, but how to monitor local etcd metrics? have any suggestion ? thank you

Same question here.

**Comment by stefanlasiewski** [comment]
> so, but how to monitor local etcd metrics? have any suggestion ? thank you

Since this isn't built into Rancher yet, you could build custom Grafana graphs to monitor `etcd`. Some Rancher customers build an external Grafana/Prometheus service which does this (and which also does monitoring and alerting outside of Rancher). I imagine it's also possible to build custom graphs within the existing Grafana service-- I'm sure that some etcd/grafana tutorials could help us to do this.

**Comment by stefanlasiewski** [comment]
> Now we only scrap ETCD metrics for RKE cluster (node template or custom). local cluster is an imported cluster.

Generally speaking, an RKE cluster shouldn't be considered an `import`ed cluster to the point that it excludes expected features. Installing via RKE is [Rancher's #1 recommended way to provide a standard HA cluster](https://rancher.com/docs/rancher/v2.x/en/installation/ha/), and it's suprising  when important features like this don't work. This feels like Rancher software can't support other Rancher software, which makes for a disjointed user experience that feels disjointed. Would love to see this improved.

**Comment by cloudnautique** [comment]
We are going to include this in scope of our overall monitoring improvements. At a minimum, it should at least be able to use the enhanced configurability of the cluster monitoring solution.

**Comment by mohjam2004** [comment]
Hi, 
How can I monitor ETCD and Kubernetes Components?
What is the alternative solution?
Regards

**Comment by mohjam2004** [comment]
Hi,
Enterprise PKS had the same problem and resolved it:
https://kb.vmware.com/s/article/71049
Is there any solution in Rancher?
Regards

**Comment by jiaqiluo** [comment]
The support for scraping metrics from etcd is tested on both local cluster and imported RKE cluster on a Rancher:`master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head` HA setup with `rancher-monitoring v2`.

As of today, with monitoring v2, the Rancher UI does not show the metrics; 
Instead, we need to expose Grafana UI and Prometheus UI and check graphs and metrics from there.

here is the yaml file of the configuration used when installing the rancher-monitoring chart (if not installing rancher-monitoring from rancher's dashboard)
```
prometheus:
  prometheusSpec:
    evaluationInterval: 1m
    resources:
      limits:
        memory: 1000Mi
    retentionSize: 50GiB
    scrapeInterval: 1m
rkeControllerManager:
  enabled: true
rkeEtcd:
  enabled: true
rkeProxy:
  enabled: true
rkeScheduler:
  enabled: true
```

In Prometheus, we see the targets for etcd are active
<img width="1436" alt="Screen Shot 2020-08-12 at 4 59 26 PM" src="https://user-images.githubusercontent.com/6218999/90079693-72224680-dcbd-11ea-862a-ca850df74a00.png">

and we can query etcd metrics

<img width="731" alt="Screen Shot 2020-08-12 at 4 59 44 PM" src="https://user-images.githubusercontent.com/6218999/90079716-87977080-dcbd-11ea-87a0-90116e6f2e87.png">

In Grafana, the etcd dashboard also shows metrics 

<img width="1861" alt="Screen Shot 2020-08-12 at 5 00 05 PM" src="https://user-images.githubusercontent.com/6218999/90079752-a138b800-dcbd-11ea-8abf-283478f8fc8f.png">

**Comment by Zhang21** [comment]
Same question.
