### ISSUE TITLE
Alert - cluster-alerting cannot deploy after add an alert

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#18618]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Spinning up a GKE cluster.
2. Config notifier and add an alert group included an alert rule.

**Result:**

cluster-alerting cannot deploy.

![image](https://user-images.githubusercontent.com/18737885/53863730-df8c6b00-4025-11e9-8722-bdf69058c45d.png)

**Other details that may be helpful:**

- Rancher server log

```
[ERROR] ClusterAlertRuleController c-9rjsz/car-k8b5x [cluster-alert-rule-deployer] failed with : failed to get Alertmanager Deployment information, statefulsets.apps "alertmanager-cluster-alerting" not found, [cluster-alert-rule-controller] failed with : Failed to get service for alertmanager, service "cattle-prometheus/alertmanager-operated" not found
```

- Cluster message
```
   message: ‘failed to ensure monitoring project name: failed to move Namespace cattle-prometheus
     into a Project: Operation cannot be fulfilled on namespaces “cattle-prometheus”:
     the object has been modified; please apply your changes to the latest version
     and try again’
```

Seems its lack of `monitoring-operator`

![image](https://user-images.githubusercontent.com/18737885/53864603-e320f180-4027-11e9-8374-40517324fb02.png)

**Environment information**
03/06/2019 master

**Comment by orangedeng** [comment]
Can not reproduce  in master 3/26. Closing it.
