### ISSUE TITLE
Add a k8s cluster where to set the password from a private registry

### ISSUE THREAD

**Issue by xuejipeng** [rancher/rancher#18622]
**What kind of request is this (question/bug/enhancement/feature request):**

question

I wang add a k8s cluster to rancher2.0, and rancher-agent image in my private registry and the private registry have password, i have set CATTLE_SYSTEM_DEFAULT_REGISTRY,but i don't know where to set username and password
Access the password for this registry where do I set it up?

**Comment by superseb** [comment]
It can be done as described on https://rancher.com/docs/rke/v0.1.x/en/config-options/private-registries/#default-registry, we have https://github.com/rancher/rancher/issues/17109 open for adding it into the UI.

Let me know if it doesnt work

**Comment by xuejipeng** [comment]
@superseb  Sorry, my k8s cluster is not installed through rke
