### ISSUE TITLE
Monitoring - Predefined metrics not match

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#18624]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable `cluster-level` monitoring

**Result:**
- Cannot see `ingress-controller` metrics
- Some of the metric graphs from Grafana cannot match Rancher UI
  + Kubernetes Components
    * [x] Nginx Ingress Request Rate
    * [x] API Server Request Latency
  + ETCD
    * [x] Should consider multiple Etcd
  + Cluster
    * [x] CPU usage is using 2m avg

**Other details that may be helpful:**
- [x] `ingress-controller`: use the new metric implementation since [0.16.1](https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.16.1), should replace the stale metrics by new;
- [x] `ingress-controller`: `accpeted`, `active` & `handled` state connections are [Counter](https://prometheus.io/docs/concepts/metric_types/#counter)s, using `sum` expressions are not correct: https://github.com/rancher/rancher/blob/95cc15027a192f2e7dc95c8c105d378f0e53a7a4/pkg/controllers/user/monitoring/metricExpression.go#L3411
- [x] `etcd` network client grpc received bytes are using the wrong measure, received traffic and sent traffic are not in the same magnitude:
https://github.com/rancher/rancher/blob/95cc15027a192f2e7dc95c8c105d378f0e53a7a4/pkg/controllers/user/monitoring/metricExpression.go#L2467-L2468
https://github.com/rancher/rancher/blob/95cc15027a192f2e7dc95c8c105d378f0e53a7a4/pkg/controllers/user/monitoring/metricExpression.go#L2534
- [x] `etcd`: there aren't any differences between `failed` and `failure` in Raft Proposals, and I prefer to use `sum(increase(etcd_server_proposals_failed_total[5m]))`:
https://github.com/rancher/rancher/blob/95cc15027a192f2e7dc95c8c105d378f0e53a7a4/pkg/controllers/user/monitoring/metricExpression.go#L2638-L2653
https://github.com/rancher/rancher/blob/95cc15027a192f2e7dc95c8c105d378f0e53a7a4/pkg/controllers/user/monitoring/metricExpression.go#L2991-L3005
- [x] `metric-expression` resources are managing by rancher, we should remove them from system-chart, as user clusters are never using them.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom

**Comment by cjellick** [comment]
@thxCode @loganhz i am concerned that QA wont understand what this change is and how to test it. You may need to explain more clearly

**Comment by loganhz** [comment]
Sure, we will have a zoom with @jiaqiluo today

**Comment by jiaqiluo** [comment]
Some observations on Rancher: master 3/12

1. see the metric `Ingress Controller Connections` under `Kubernetes Components Metrics` in a custom cluster, but see `Ingress Controller Connections` and `Ingress Controller Request Process Time` under the same section in a DO cluster 
2. The metric `API Server Request Latency`'s value does not match in Rancher UI and Grafana UI

**Comment by jiaqiluo** [comment]
The bugfix validation is on Rancher: master 3/13
Cluster: custom RKE cluster, 1 control plane, 3 etcd node, 4 worker

1.  there are `Ingress Controller Connections` and `Ingress Controller Request Process Time` presenting under `Kubernetes Components Metrics` section 
2. Since the precision and scale of Y-direction of graphs in Rancher's dashboard  are different from those in Grafana's dashboard,  the Y-values in `Nginx Ingress Request Rate`, `API Server Request Latency`and etc. are rougly equal to the values in their corresponding graphs in Grafana.
3. Graphs for `ETCD` in Grafana show multiple lines representing differnt etcd nodes when it is posibble
4. `CPU usage` in Grafana is using 5 mins avg as the default
