### ISSUE TITLE
Rancher Default Library reports 404 in GUI

### ISSUE THREAD

**Issue by ThunderRush** [rancher/rancher#18621]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher 2.1.6 on a 3 Node HA Cluster with external load balancer.

**Result:**
In the GUI, the Default Library Reports: 
Unexpected HTTP status code 404 from [https://git.rancher.io/charts/index.yaml], expected 200

**Environment information**
- Rancher version: v2.1.6
- Installation option: HA

**Comment by ThunderRush** [comment]
It just works again, despite us not changing anything.

**Comment by patriziobassi** [comment]
for me i still have the same issue instead, while i can download the helm library
