### ISSUE TITLE
Unable to save specific toleration to workload

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#18627]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Deploy a workload
2) Set toleration on workload to the following values:
Label Key: <blank>
Operator: Exists
Value: n/a
Effect: <blank>
Time: <blank>

3) expect that it will come out in the following valid YAML form:
```
tolerations: 
- operator: "Exists"
```

**Result:**
It does not save properly.

**Other details that may be helpful:**
The only way to save this toleration is to edit the YAML file directly.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.6
- Installation option (single install/HA): Single

**Comment by dsargent3220** [comment]
Tolerations also do not load properly, with the last tolerations effect being empty, this will cause Rancher to delete that toleration upon save in certain circumstances.

The GUI will also wipe out other types of tolerations as well, for example, the tolerations in Rancher's own DataDog chart
```
 - key: "node-role.kubernetes.io/etcd"
   value: "true"
 - key: "node-role.kubernetes.io/controlplane"
   value: "true"
```
Will be deleted if you add another toleration via the GUI

**Comment by sowmyav27** [comment]
### Reproduced this issue on `v2.2.7`
Steps:
- Deploy a workload
- Set toleration on workload to the following values:
```
Label Key: <blank>
Operator: Exists
Value: n/a
Effect: <blank>
Time:<blank>
```
- YAML file of the workload, after deployment does not contain the tolerations set.

### Verified on `master-head`.

- Deploy a workload and set tolerations as:
<img width="1288" alt="Screen Shot 2019-08-08 at 2 52 34 PM" src="https://user-images.githubusercontent.com/26032343/62740258-34c11400-b9ec-11e9-9348-6ed3268350ae.png">
- Can see tolerations set on the workload

```
tolerations:
      - effect: NoSchedule
        operator: Exists
```

- On setting tolerations as below. (Effect: choose custom)
<img width="1254" alt="Screen Shot 2019-08-08 at 2 55 08 PM" src="https://user-images.githubusercontent.com/26032343/62740391-8a95bc00-b9ec-11e9-9fe1-b5ad5707f001.png">

In YAML file, user is able to see the set tolerations as
```
tolerations:
      - operator: Exists
```
