### ISSUE TITLE
Clarify TCP vs HTTP health check

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1862]
The current healthcheck screen does not make it at all clear now how to do a TCP vs HTTP check.

New:

![image](https://cloud.githubusercontent.com/assets/753917/9433176/5a1f7188-49e3-11e5-881a-60205e17f078.png)

**Comment by sangeethah** [comment]
Tested with build form master - Aug 28
We see 2 different health check tabs for TCP and HTTP. Enabling TCP/HTTP health check works as expected.
