### ISSUE TITLE
Certificate key cannot be added with UI v2.2.0-rc2

### ISSUE THREAD

**Issue by Troyhy** [rancher/rancher#18620]
*Certificate cannot be added.* Same files are tested to work with earlier versions of Rancher

"Private Key is invalid. Please make sure it is a RSA key."

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc2` UI: `v2.2.3` |
|Route|`authenticated.project.certificates.new`|

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/7/19) a3f8c48fe1e6
Confirmed issue is resolved. 
I am able to successfully use a private key under Project > Resources > Certificates. I tested with other non-valid certs and get an appropriate error in the UI.
Tested via text insert (copy/paste) and "Read from a file".
I also tested in other areas this code is utilized such as on the Cluster/Project Logging page when you enable SSL for a target. 
This appears to be working correctly.
