### ISSUE TITLE
Search filter under customize schema for openldap doesn't work.

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#18630]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

configure openldap on Rancher 2.x, go to customize schema, add a filter to the "Search Filter" and click save.

**Result:**

Clicking save will make it disappear.

**Other details that may be helpful:**

It seems as though the user search filter field isn't included in the API:

```
"userDisabledBitMask": 0,
"userLoginAttribute": "uid",
"userMemberAttribute": "memberOf",
"userNameAttribute": "cn",
"userObjectClass": "inetOrgPerson",
"userSearchAttribute": "uid|sn|givenName",
"userSearchBase": "dc=example,dc=com",
```

Only these messages show up in the logs when trying to add it:

```
2019/03/05 21:12:28 [DEBUG] Impersonating user user-b9p7h, groups [system:authenticated]
2019/03/05 21:12:28 [DEBUG] GET: 2.333876msauthconfigs
2019/03/05 21:12:28 [DEBUG] GET: 1.9112msauthconfigs
2019/03/05 21:12:28 [DEBUG] GET: 2.937752msauthconfigs
2019/03/05 21:12:28 [DEBUG] AuthConfigController calling handler authConfigController openldap
```

Dev tools in chrome also show the api endpoing returning a 200 for the request. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.6

- Installation option (single install/HA):
Either, I recreated in single, but the customer is on HA.

**Comment by alena1108** [comment]
SearchFilter support was implemented for AD only https://github.com/rancher/rancher/issues/13656. We just have to extend it to include OpenLDAP.

**Comment by mrajashree** [comment]
Same as https://github.com/rancher/rancher/issues/19436

**Comment by soumyalj** [comment]
Tested with v2.3-head. 
Enabled FreeIPA auth .  "Search Filter" field option is presented for User and Groups in "Customize Schema" section.
Users has the option to set these fields when FreeIPA auth is enabled. When the field is set , this filter gets applied to the list of users/groups that get searched when adding users to add members to cluster/projects.
The following tests were done:
1. User Search Filter
(memberOf=cn=davidgroup1,cn=groups,cn=accounts,dc=rmfreeipa,dc=do,dc=rancher,dc=space)
2. Multiple user search filter
(|((memberOf=cn=group1,cn=groups,cn=accounts,dc=rmfreeipa,dc=do,dc=rancher,dc=space)(memberOf=cn=group1,cn=groups,cn=accounts,dc=rmfreeipa,dc=do,dc=rancher,dc=space))
3. Single group search filter - (cn=group2)
4. Multiple group search filter
(|(cn=group1)(cn=group2))
