### ISSUE TITLE
Gometallinter will be deprecated on 04-07-2019

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#18638]
See https://github.com/alecthomas/gometalinter/issues/590
While releases will still be available we should consider other linters.

**Comment by dramich** [comment]
Suggested replacement is https://github.com/golangci/golangci-lint

**Comment by daxmc99** [comment]
As of c0e17880540a115151c5edb8712e06dea1906da4 this is still tbd. 
golangci-lint has issues with memory consumption and would break local dev workflow with `make ci` taking a very long time to run locally

**Comment by superseb** [comment]
https://github.com/golangci/golangci-lint/releases/tag/v1.20.0 contains multiple memory usage fixes

**Comment by dramich** [comment]
Technically this was fixed by going back to standard go tools but with the memory fixes in golangci we are going to give it another go.
