### ISSUE TITLE
UI: Edit cluster failed with 's3BackupConfig' of undefined error

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#18635]
Steps to reproduce:
- run rancher 2.0.6 
- create do cluster (1cp,1etcd,1worker)
- upgrade to master
- edit cluster

The edit cluster failed to proceed and i can see the following error in the browser console:
```
0:189889 Uncaught TypeError: Cannot read property 's3BackupConfig' of undefined
    at n.initBackupConfigs (0:189889)
    at n.init (0:189074)
    at n [as init] (0:58190)
    at n.e (0:57415)
    at n (0:57475)
    at n (0:57475)
    at n (0:57475)
    at n (0:57475)
    at new n (0:57475)
    at Function.e.create (0:57488)
```

**Comment by davidnuzik** [comment]
Version: v2.0.6 -> master (Upgrade)
Confirmed issue resolved. I followed the steps and can no longer reproduce. I watched the browser dev console the whole time while testing and identified no issues.
I am able to edit my cluster without any issues and I can pick local/s3 backup settings in the UI and save these changes without any issues in the UI.
I smoke tested the upgraded cluster as well after making changes to enable etcd backup.
