### ISSUE TITLE
Kubectl not working

### ISSUE THREAD

**Issue by devfelipereis** [rancher/rancher#18640]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
I just installed(clean install) Rancher 2.2.0-rc2 and I did try to use kubectrl from Rancher UI.

**Result:**
![image](https://user-images.githubusercontent.com/5348752/53907277-9808dd80-402b-11e9-91b4-4d64490a5eaf.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.0-rc2 

- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Infrastructure provider (Digital Ocean)

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud. 4GB memory and 2vCPUs

- Kubernetes version (use `kubectl version`): 
Can't get but I'm using 1.13.1
```
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
Can you try `v2.2.0-rc3` on a new machine?

**Comment by devfelipereis** [comment]
Yes!

**Comment by devfelipereis** [comment]
@superseb 

Works with v2.2.0-rc3.

![image](https://user-images.githubusercontent.com/5348752/53910756-68f66a00-4033-11e9-9f4c-161bd42e9838.png)

**Comment by superseb** [comment]
Cool, thanks for testing and reporting.
