### ISSUE TITLE
rancher app install local chart breaks CLI

### ISSUE THREAD

**Issue by kgignatyev-inspur** [rancher/rancher#18646]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**

rancher app install ./src/charts/bitnami/nginx

**Result:**
chart is installed and working, but rancher app ls now returns error:
 rancher app ls
ID        NAME      STATE     CATALOG   TEMPLATE   VERSION
FATA[0000] can't parse info from app       

**Other details that may be helpful:**
before installing chart the rancher app ls was working and listing 1 app:

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5

rancher --version
rancher version v2.2.0-rc11

**Comment by kgignatyev-inspur** [comment]
I have recompiled cli on and added output 

func appLs(ctx *cli.Context) error {
	c, err := GetClient(ctx)
	if err != nil {
		return err
	}

	collection, err := c.ProjectClient.App.List(defaultListOpts(ctx))
	fmt.Println("---kgi--")
	fmt.Println(collection)

here is what I got:


&{{collection map[self:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps] map[app:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps] map[] 0xc00014a000 0xc000242a00 map[appRevisionId:[] created:[] creatorId:[] description:[] externalId:[] lastAppliedTemplate:[] name:[] namespaceId:[] notes:[] projectId:[] prune:[] removed:[] state:[{ne inactive}] targetNamespace:[] transitioning:[] transitioningMessage:[] uuid:[]] app} [{{p-l66jq:a-pngtt app map[remove:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:a-pngtt revision:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:a-pngtt/revision self:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:a-pngtt update:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:a-pngtt] map[rollback:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:a-pngtt?action=rollback upgrade:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:a-pngtt?action=upgrade]} map[lifecycle.cattle.io/create.helm-controller_c-6kfpm:true] map[] apprevision-hnxxx map[] [{ 2019-03-06T19:29:32Z   True Migrated} { 2019-03-06T19:29:45Z   True Installed}] 2019-03-06T19:29:32Z u-qsugkn3bg2   map[] map[cattle.io/creator:norman]   a-pngtt   [] c-6kfpm:p-l66jq false  active nginx-prbt0 no  2afc8955-4046-11e9-b6d8-0242ac110002 } {{p-l66jq:magic-namespace app map[remove:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:magic-namespace revision:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:magic-namespace/revision self:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:magic-namespace update:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:magic-namespace] map[rollback:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:magic-namespace?action=rollback upgrade:https://qa-rncrsrv1.sea1.marchex.com/v3/project/c-6kfpm:p-l66jq/apps/p-l66jq:magic-namespace?action=upgrade]} map[lifecycle.cattle.io/create.helm-controller_c-6kfpm:true] map[] apprevision-548pg map[] [{ 2019-01-24T22:31:34Z   True Migrated} { 2019-01-24T22:31:42Z   True Installed}] 2019-01-24T22:31:34Z user-9g9zr  catalog://?catalog=helm&template=magic-namespace&version=0.3.0 map[] map[cattle.io/creator:norman]   magic-namespace  ---
# Source: magic-namespace/templates/NOTES.txt

The namespace "magic-namespace" has been created if it didn't already exist.

The following service accounts have been created in the namespace:

  - tiller
  - some-service-account
  - another-service-account

The following role bindings have been created in the namespace:

  - ServiceAccount[tiller] --> [admin]

Utilize the Tiller in your new namespace like so:

  $ helm <command> --tiller-namespace magic-namespace

 [] c-6kfpm:p-l66jq false  active magic-namespace no  ce524258-2027-11e9-b6d8-0242ac110002 }] 0xc0001640f8}
ID        NAME      STATE     CATALOG   TEMPLATE   VERSION
FATA[0000] can't parse info from app

**Comment by kgignatyev-inspur** [comment]
another interesting observation, when I run debugger then 
collection, err := c.ProjectClient.App.List(defaultListOpts(ctx)) works fine, no errors, I was able to see app-id and delete it, then 'rancher app ls' started to work again, it shows list of apps with one item in it.

However, if I add --format json then it returns invalid json, it should be json array, but it is a single object, very much like https://github.com/rancher/rancher/issues/18642 , this makes automation difficult

**Comment by thxCode** [comment]
@kgignatyev-inspur , Can you format your comments by some markdown instructions, they make me very  confused?

**Comment by kgignatyev-inspur** [comment]
Not sure what formatting will help, those are outputs from debugger, 

(cmd/app.go:262 ) collection, err := c.ProjectClient.App.List(defaultListOpts(ctx))

produces those outputs, the call to server seems to be working fine, no error, but then parsing of that output seem to fail on client side.

**Comment by kgignatyev-inspur** [comment]
anyway, here is the chart [charts.zip](https://github.com/rancher/rancher/files/2953395/charts.zip)  attached I am trying to deploy with command 

rancher app install ./src/charts/bitnami/nginx 

and that causes rancher CLI to stop parsing server output and and show list of applications, desirable behavior: able to deploy local chart per documentation and CLI does not fail with fatal errors
