### ISSUE TITLE
Disabling etcd snaphots should be supported

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18647]
Rancher version: Master

Currently, there is no option to disable etcd snapshots. 
We should have the ability to disable snapshots

**Comment by westlywright** [comment]
@moelsayed @alena1108 I've got the UI PR opened for this already, I really dont have to wait to merge  that since it forces enabled: true as the default. I tested this out with out your changes and the API just drops the field as expected. But I will wait until teh backend PR's have been moved out of WIP.

**Comment by westlywright** [comment]
UI has been merged.

**Comment by sangeethah** [comment]
Tested with Rancher server version - Build from master - Mar 9 - 2ae5225

There is option in "Edit/Add Cluster" view to be able to enable/disable snapshots.
Snapshots are enabled by default.

When snapshot is enabled , snapshots get taken as per "Snapshot Creation Period" specified. If manual backup is taken , then the next snapshot will be taken after "Snapshot Creation Period" from the time this manual backup is taken.

When snapshot is disabled, recurring snapshots are not taken.
When snapshots are enabled  back,  recurring snapshots gets taken as expected.

When snapshots are disabled , we are NOT able to take 1 time manual backups as well. Will log a different issue , if we expect time manual backup to be allowed in case were  snapshots are disabled.

When snapshots are taken , they seem to get done twice which is tracked in -https://github.com/rancher/rancher/issues/18766
