### ISSUE TITLE
Error in restoring from etcd backups available on all the nodes after one successful restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18659]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a custom cluster (SUSE) with 1 etcd(etcd#1)/1control plane /2 worker nodes.
2. Register the cluster with the nodes and take a backup (Backup#1).
3. Create project and namespace. Take a backup (Backup#2)
4. Register/add two more etcds(etcd#2, etcd#3) nodes to the cluster.
5. Take a backup (Backup#3)
6. Add project and namespaces and take backup (Backup#4). Verified etcd#1 had 4 snapshots and etcd#2 and etcd#3 had 2 snapshots each.
7. Restore backup from Backup#1. Restore is successful
8. Restore from Backup#2. Error message is seen in the UI and the logs after multiple attempts to restore the backup.
9. Restore from Backup#3 or Backup#4 (these snapshots are available on all the 3 etcd nodes).
Similar error as seen in the previous step is seen on the UI and in the logs. Cluster was still in `Updating` state.

The cluster was in this state for almost one hour, after which another cluster was created in the rancher server and first cluster came to `Active` state.

**Note:** This issue happened once, and is not reproducible.

**Error seen on the UI:**
<img width="1366" alt="screen shot 2019-03-06 at 3 56 32 pm" src="https://user-images.githubusercontent.com/26032343/53926213-7d3c6600-4037-11e9-9576-95c509fdc314.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master (03/06/2019)
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom SUSE
- Kubernetes version (use `kubectl version`):

```
1.1.3.4
```

- Docker version (use `docker version`):

```
v1.12.3
```

**Comment by alena1108** [comment]
Marking with `priority/2` as the issue was observed only once

**Comment by moelsayed** [comment]
this is the same issue as https://github.com/rancher/rancher/issues/18918

**Comment by sowmyav27** [comment]
verified on `rancher:master` (04/23/2019)

**Steps taken:**

1. Create a cluster - 1 etcd, 1 ctrl plane, 1 worker node
2. When the cluster comes to `Active` state, take a `Snapshot`.
3. Add an etcd node.
4. Add a namespace to a project. Take a `Snapshot`
5. Add an etcd node. and Take a snapshot again. 
6. Do a restore from snapshot, and select the snapshot taken in step 2. 
7. The cluster will transition to `Updating state` and then to `Active` successfully.
8. Do a restore from snapshot, and select the snapshot taken in step 4. 
9. The cluster will transition to `Updating state` and then to `Active` successfully.

**Comment by alphakiran** [comment]
Hi Sowmyav27, a quick question as I have started with the rancher usage in my company and want only the application based backup which is cluster recovery. This should be done through code not manually and retention period as can be mentioned in rke-cluster.yml. Any advice or documentation which will help. Not the regular doc from rancher pklease. 

Thank You
