### ISSUE TITLE
Rancher Upgrade Does Not Upgrade Cluster Monitoring

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#18653]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Install Rancher 2.2.0-alpha6
2. Upgrade to Rancher 2.2.0-rc3

**Result:**

I would expect any cluster monitoring or project monitoring to be upgraded automatically or provide a simple way to notify the user that manual upgrade is required.

Instead the upgrade is not occurring.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-rc3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal 4 CPU/16 GB
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by superseb** [comment]
As described in the announcement of the alpha (https://forums.rancher.com/t/rancher-release-v2-2-0-alpha6)

```
Preview releases are tagged with the suffix -alpha<number> and are bleeding edge. They should not be run in a production environment. Upgrading to or from an alpha release is not tested or supported, even if it appears to work successfully.
```
