### ISSUE TITLE
Rancher 1.6x - rancher/metadata-windows gets errored out  :"Failed to subscribeGet"

### ISSUE THREAD

**Issue by vishnuvpotti** [rancher/rancher#18656]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Install rancher server 1.6.26
2) Create Windows Environment
3) Add windows hosts to the new environment.

**Result:**
Two stacks named "windows" and "windows-network-services" starts getting created. But windows-network-services never gets created successfully as "windows-metadata" service gets errored out with following error.
```
3/6/2019 11:52:32 AMtime="2019-03-06T11:52:32+11:00" level=info msg="Starting rancher-metadata v0.10.0"
3/6/2019 11:52:32 AMtime="2019-03-06T11:52:32+11:00" level=info msg="Subscribing to events"
3/6/2019 11:52:32 AMtime="2019-03-06T11:52:32+11:00" level=fatal msg="Failed to subscribeGet http://ranserver:8080/v2-beta: dial tcp: lookup ranserver no such host"

```
**Other details that may be helpful:**
1) telnet from node to server on port 8080 works fine.
2) Created couple of windows environments with different hosts. The issue still persists.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v 1.6.26
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
PS C:\program files\rancher> docker version
Client:
 Version:      17.06.2-ee-17
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   66834de
 Built:        Thu Oct 25 12:16:20 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-17
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   66834de
  Built:        Thu Oct 25 12:25:12 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

**Comment by loganhz** [comment]
Please try v2.3.0-alpha3 for windows
