### ISSUE TITLE
validateNonSpecial IP returns 500 errors

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#18652]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
change  https://github.com/rancher/rancher/blob/c8da22fb9218fcfa5df8921bd188afc3517462af/tests/core/test_dns.py#L106 to remove the indent
Run test_dns.py 

**Result:**
Errors with status code 500 are returned rather than the expected 422

**Other details that may be helpful:**
Tested on 573a3695c048724e31cd80e9e24600a5ae4fac12

**Comment by sangeethah** [comment]
Tested with 2.1.9-rc3. Able to reproduce the issue that we get a "500 Server Error" when trying to create a dnsRecord pointing to invalid ip address.

```
{
"baseType": "error",
"code": "ServerError",
"message": "0.0.0.0 may not be unspecified (0.0.0.0)",
"status": 500,
"type": "error"
}
```

Tested with latest build from master - `c098b38` we get a "422 InvalidOption" error when trying to create a dnsRecord pointing to invalid ip address.

```
{
"baseType": "error",
"code": "InvalidOption",
"message": "0.0.0.0 may not be unspecified (0.0.0.0)",
"status": 422,
"type": "error"
}
```
