### ISSUE TITLE
Import compose and rancher YML via API/UI

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1865]
Rancher already supports importing/launching docker compose via the rancher-compose CLI tool. We need to add the ability to import docker compose and rancher compose via the API and subsequently, via the UI.

**Comment by will-chan** [comment]
Reopening as we need to still complete packaging and UI.

**Comment by will-chan** [comment]
@cloudnautique can you package this into Rancher?

**Comment by aruneli** [comment]
Tested Rancher Compose UI with various docker-compose.yml and rancher-compose.yml and all the functionalities supported in rancher-compose CLI works. Build with local option is not supported.
