### ISSUE TITLE
Uploading development helm charts

### ISSUE THREAD

**Issue by strainovic** [rancher/rancher#18650]
Hi all,

Currently, when I change something in helm chart, I have to pack it, create repo index and upload files to web server and wait for a few minutes until Rancher refresh helm catalog.

It would be very helpful if we can upload our development helm chart directly to Rancher without need to push it to some helm catalog.

Can we somehow speedup this process?

Thanks!

**Comment by kgignatyev-inspur** [comment]
See my related bug https://github.com/rancher/rancher/issues/18646 
dev iterations I think are supposed to work as 
   rancher app upgrade app-name  ./local-chart
analogous to raw 
 helm upgrade release-name ./local-chart

**Comment by strainovic** [comment]
I'd like to test my questions.yaml file and that's why I need to install it through rancher's gui.

Anyway, rancher is missing textarea field which can be very useful for json data or other...

Thanks
