### ISSUE TITLE
Should not show custom cloud driver's page while the driver is not active

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#18662]
In master 3/7, I am using Huawei CCE cloud driver as an example:
While I am still downloading the driver:
![image](https://user-images.githubusercontent.com/15376837/53930304-c807bd80-40cb-11e9-8c66-9ecd13557cfc.png)

I can see the Huawei CCE in adding cluster page:
![image](https://user-images.githubusercontent.com/15376837/53930348-ec639a00-40cb-11e9-8dec-bc19acd27a20.png)

I don't think it is a good UX.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/7/19)
Confirmed issue is resolved.
* Confirm drivers do not show up while Inactive
* Confirm driver does not show up while in Downloading or Activating state (monitor add cluster page and refresh several times while in these states)
* Confirm driver DOES show up when in Active state

* Test again with fake driver that will never succeed. Wait for a while and keep refreshing, driver never shows up as expected.
* Smoke test this area. Did not find any issues.
