### ISSUE TITLE
Rancher Errors with Deploying Monitoring Charts to Cluster

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#18664]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** 

1. Enable cluster monitoring

**Result:**

The internal JIT tiller throws a bunch of errors about credentials being required for config maps it seems?

**Other details that may be helpful:**

Other catalog entries from the Library do not seem to be affected, I was able to install redis and mysql without issue.

**Logs:**
```
[main] 2019/03/07 03:32:49 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/03/07 03:32:49 GRPC listening on :49213
[main] 2019/03/07 03:32:49 Probes listening on :42696
[main] 2019/03/07 03:32:49 Storage driver is ConfigMap
[main] 2019/03/07 03:32:49 Max history per release is 0
[tiller] 2019/03/07 03:32:49 getting history for release monitoring-operator
[storage] 2019/03/07 03:32:49 getting release history for "monitoring-operator"
[storage/driver] 2019/03/07 03:32:49 query: failed to query with labels: the server has asked for the client to provide credentials (get configmaps)
[tiller] 2019/03/07 03:32:49 getting history for release cluster-monitoring
[storage] 2019/03/07 03:32:49 getting release history for "cluster-monitoring"
[storage/driver] 2019/03/07 03:32:49 query: failed to query with labels: the server has asked for the client to provide credentials (get configmaps)
[tiller] 2019/03/07 03:32:49 preparing update for monitoring-operator
[storage] 2019/03/07 03:32:49 getting deployed releases from "monitoring-operator" history
[storage/driver] 2019/03/07 03:32:49 query: failed to query with labels: the server has asked for the client to provide credentials (get configmaps)
2019/03/07 03:32:49 [ERROR] AppController p-kctht/monitoring-operator [helm-controller] failed with : failed to install app monitoring-operator. Error: UPGRADE FAILED: the server has asked for the client to provide credentials (get configmaps)

[tiller] 2019/03/07 03:32:49 preparing update for cluster-monitoring
[storage] 2019/03/07 03:32:49 getting deployed releases from "cluster-monitoring" history
[storage/driver] 2019/03/07 03:32:49 query: failed to query with labels: the server has asked for the client to provide credentials (get configmaps)
2019/03/07 03:32:49 [ERROR] AppController p-kctht/cluster-monitoring [helm-controller] failed with : failed to install app cluster-monitoring. Error: UPGRADE FAILED: the server has asked for the client to provide credentials (get configmaps)
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-rc3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal 4core/16gb
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by thxCode** [comment]
@ekristen , I have no idea about this error. It seems tiller cannot `get configmap` from API server, as it doesn't provide any credentials in the process. Do you have any other progress?

**Comment by ekristen** [comment]
Nope it just sits on this error and repeats. Unfortunate the JIT tiller spins up, throws the error, tearsdown and repeats and spams the logs a lot. 

What troubleshooting data can I provide?

**Comment by ekristen** [comment]
It seems like based on Google, this is an error with how tiller is started. For some reason it does not have the correct permissions to access the namespace it's requesting.

**Comment by ekristen** [comment]
Ok I found the root cause.

If you deactivate the default admin, this fails to deploy because it uses a token generated by the default user.

The default user should be able to be deactivated or deleted ... so should there be a system user that gets created that can't be modified by the end user?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/18787

**Comment by boomshadow** [comment]
@ekristen I'm having this same problem when Rancher starts up. How did you reactive your default user? FOr me, I can't access Rancher.
