### ISSUE TITLE
Update kubectl in embedded kubectl shell

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#18676]
**What kind of request is this (question/bug/enhancement/feature request):**
task

**Steps to reproduce (least amount of steps as possible):**
With newly supported k8s versions, we should bump kubectl to 1.12.6

To validate:

* Open embedded kubectl shell
* Run `kubectl version`
* `Client Version` should show correct version

**Comment by sangeethah** [comment]
Tested with v2.2.2-rc-x12

Client version for K8s - v1.12.7 is now v1.12.7

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
