### ISSUE TITLE
the pipline can not build two or more image

### ISSUE THREAD

**Issue by k332772194** [rancher/rancher#18672]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/39399043/53941744-e1bcfb00-40f3-11e9-9c5f-2cf7d631f33b.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.6` UI: `v2.1.19` |
|Route|`authenticated.project.pipeline.pipelines.edit`|

**Comment by gitlawr** [comment]
Thanks for the report. It will be fixed in 2.2. Please check the workaround in https://github.com/rancher/rancher/issues/16624
