### ISSUE TITLE
[Cloud Driver]Huawei CCE node operating system options are mismatched

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#18674]
The operating system options in Huawei CCE cloud driver are `EularOS 2.2` and `EularOS 2.3` in Rancher UI. But `EularOS 2.2` and `CentOS 7.4` are shown in Huawei cloud UI. We need to update our options and keep sync with Huawei public cloud.

**Comment by deniseschannon** [comment]
@orangedeng @loganhz is there a way to avoid hard coding this and being able to pull it directly from  CCE?

**Comment by loganhz** [comment]
Confirmed with @orangedeng . There is no API we can use for now.

**Comment by davidnuzik** [comment]
@loganhz I do not have testing credentials to validate Huawei. Could we assign to someone with such credentials or provide them to me privately?

**Comment by rootwuj** [comment]
Tested with rancher/rancher:master from Apr 16.
This version of Huawei CCE driver node os options are the same as Huawei public cloud.
Confirmed fixed.
