### ISSUE TITLE
Default Docker MTU may break container builds in pipelines

### ISSUE THREAD

**Issue by Matsca09** [rancher/rancher#18684]
**What kind of request is this (question/bug/enhancement/feature request):** bug

The Docker daemon inside the Jenkins executor pod for building Docker images uses the default MTU (1500) and this creates network errors in the build steps if the MTU of the pod main interface is lower (in our case 1376); we've observed those issues for example when downloading requirements via pip (which constantly fails to download packages with the `Read timed out.` error) and when cloning git repositories via SSH (the process completely hangs).

A workaround which I'm using right now to use the pipelines successfully is to add the environment variable `PLUGIN_MTU` to a lower value for the image `rancher/jenkins-plugins-docker:17.12` inside the file `pkg/pipeline/engine/jenkins/convert.go` but this requires a full and custom build of Rancher.

**Steps to reproduce (least amount of steps as possible):**
- Enable pipelines, configure a Git provider and prepare a repository for the pipeline
- Write a Dockerfile which does network operations (pip install requirements, git clones with SSH) and push it to the pipeline repository
- Setup a pipeline into Rancher that refers to the prepared repository
- Configure the pipeline to build the image
- Run the pipeline

**Result:**
During the build of the image you should encounter the problems written above.

**Environment information**
- Rancher version: v2.2-rc2
- Installation option: HA

**Cluster information**
- Cluster type: Imported
- Machine type: Cloud (OpenStack)
- Kubernetes version: v1.13.2 (Docker 18.06.1-ce, Calico 3.4.0)

**Comment by gitlawr** [comment]
You can pass the `PLUGIN_MTU` env by editing the pipeline file so that you don't need a custom Rancher build.
See https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/configurations/#configuring-environment-variables and click `By YAML`. The example is for the run script step but you can also apply the same `env` syntax to the publish image step.
Let me know if you have further questions.

**Comment by Matsca09** [comment]
Hi @gitlawr 
I've tried and it works; I've completely missed the `env` part for the pipeline step, my bad!

I think that could be useful to provide some environment variables which can be used to edit the parameters for the image build in the UI and/or in the documentation, in order to help someone which may have the same or related issues in the future.

Thank you!

**Comment by loganhz** [comment]
Please see if you hit this https://github.com/rancher/rancher/issues/18684#issuecomment-470782632
