### ISSUE TITLE
Update rancher-agent to nanoserver-1809 base image

### ISSUE THREAD

**Issue by carlosvsilva** [rancher/rancher#18686]
** Main topic **
Hello! I would like to request the moving up of Windows Server 2019 (1809) support to be released in the Rancher **2.2.x** or even **2.1.x** lines. 
Windows Server 2019 is the latest and greatest release from Microsoft with the latest support for Kubernetes on Windows features (including networking) and it's part of _Long Term Servicing Channel_ with full extended support, so it's the obvious choice for many organizations deploying Windows Server.
Organizations like the one where I work at who depend on Rancher for Linux containers, and have Windows Containers to run but right not we can't join Windows nodes to the Rancher cluster because the rancher-agent:v2.1.6 is built on a nanoserver-1803 image, which is out of date and does not run on Windows Server 2019. Windows requires the host Kernel and the container userland to be in sync so it's imperative that a new rancher-agent:v2 image is built upon nanoserver-1809 matching Windows Server 2019 to run successfully! Can you please provide a built package or a build script to DIY? It would go a long way! Looking forward for your feedback!

Best regards,
Carlos Silva

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
docker run --rm -v C:/:C:/host rancher/rancher-agent:v2.1.6-nanoserver-1809 -server https://master-ip -token <token> -caChecksum <checksum>

**Result:**
C:\Program Files\Docker\docker.exe: Error response from daemon: CreateComputeSystem 20f9bcce3c16a4d0cfe62a0ce3c60e1dd098d5a2f8954ab0ca1eaa16f293f232: **The container operating system does not match the host operating system.**

**Other details that may be helpful:**

**Environment information**
- Rancher version (2.1.6)
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
- Infrastructure Provider ( Azure)
- Machine Type (Cloud), 4 CPUs, 8Gb Memory
- Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        142dfcedca
 Built:             02/28/2019 06:33:17
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       142dfcedca
  Built:            02/28/2019 06:31:15
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
This is tracked in https://github.com/rancher/rancher/issues/16460

**Comment by carlosvsilva** [comment]
I know it's tracked over there, but the place to state reasons to move up the release of Windows Server 1809 support to the 2.2.x line is here I believe, not there. Thanks

**Comment by carlosvsilva** [comment]
Another set of reasons to update Rancher to Windows Server 1809 are as follows:

- **Azure** does not carry Windows Server 1803 full images, just smalldisk core images with no GUI at all. One is required to use Windows Server 2019 for the full experience and manageability.
- **overlay networking**: use Flannel in vxlan mode to configure a virtual overlay network
requires either Windows Server 2019 with KB4482887 installed or Windows Server vNext Insider Preview Build 18317+
( - requires Kubernetes v1.14 (or above) with WinOverlay feature gate enabled )
( - requires Flannel v0.11.0 (or above) )
- **simplified network management**: use Flannel in host-gateway mode for automatic route management between nodes
- **scalability improvements**: enjoy faster and more reliable container start-up times thanks to deviceless vNICs for Windows Server containers
- **hyper-v isolation** (alpha): orchestrate hyper-v containers with kernel-mode isolation for enhanced security (see Windows container types)
( - requires Kubernetes v1.10 (or above) with HyperVContainer feature gate enabled )
- **storage plugins**: use the FlexVolume storage plugin with SMB and iSCSI support for Windows containers

I hope these are taken into account. Thanks!
