### ISSUE TITLE
Container  rancher/storage-secrets crashes

### ISSUE THREAD

**Issue by svenluzar** [rancher/rancher#18687]
**Kind of request is bug**

**Steps to reproduce (least amount of steps as possible):**

- Install Ubuntu Server 18.04.2 LTS
- Install Docker 18.03.1-ce
- Add Host via Command Line (Command Line generated with Rancher Server)

**Result:**
- On Host the Docker rancher/storage-secrets:v0.9.6 does not start and crashes with the following error

> 7.3.2019 14:47:56goroutine 13 [select]:
7.3.2019 14:47:56net.cgoLookupIP(0xe65a00, 0xc4201f34a0, 0xc420255740, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:47:56	/usr/local/go/src/net/cgo_unix.go:214 +0x2f5
7.3.2019 14:47:56net.(*Resolver).lookupIP(0xeb1263, 0xe65a00, 0xc4201f34a0, 0xc420255740, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:47:56	/usr/local/go/src/net/lookup_unix.go:69 +0x125
7.3.2019 14:47:56net.(*Resolver).(net.lookupIP)-fm(0xe65a00, 0xc4201f34a0, 0xc420255740, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:47:56	/usr/local/go/src/net/lookup.go:156 +0x56
7.3.2019 14:47:56net.glob..func11(0xe65a00, 0xc4201f34a0, 0xc420283520, 0xc420255740, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:47:56	/usr/local/go/src/net/hook.go:19 +0x52
7.3.2019 14:47:56net.(*Resolver).LookupIPAddr.func1(0x6baa5a, 0x6c4118, 0xe59a00, 0xe659c0)
7.3.2019 14:47:56	/usr/local/go/src/net/lookup.go:162 +0x5c
7.3.2019 14:47:56internal/singleflight.(*Group).doCall(0xe8d650, 0xc420248af0, 0xc420255740, 0x10, 0xc4202cc0c0)
7.3.2019 14:47:56	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x3c
7.3.2019 14:47:56created by internal/singleflight.(*Group).DoChan
7.3.2019 14:47:56	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x323
7.3.2019 14:50:12time="2019-03-07T13:50:12Z" level=info msg=Running
7.3.2019 14:50:12time="2019-03-07T13:50:12Z" level=info msg=Starting
7.3.2019 14:50:12fatal error: unexpected signal during runtime execution
7.3.2019 14:50:12[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f36b8e95259]
7.3.2019 14:50:12
7.3.2019 14:50:12runtime stack:
7.3.2019 14:50:12runtime.throw(0xa06712, 0x2a)
7.3.2019 14:50:12	/usr/local/go/src/runtime/panic.go:596 +0x95
7.3.2019 14:50:12runtime.sigpanic()
7.3.2019 14:50:12	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 38 [syscall, locked to thread]:
7.3.2019 14:50:12runtime.cgocall(0x7e0e00, 0xc420302dd8, 0xa05e7d)
7.3.2019 14:50:12	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420302d98 sp=0xc420302d58
7.3.2019 14:50:12net._C2func_getaddrinfo(0x7f36ac0008c0, 0x0, 0xc4202c51a0, 0xc4202d6520, 0x0, 0x0, 0x0)
7.3.2019 14:50:12	net/_obj/_cgo_gotypes.go:86 +0x68 fp=0xc420302dd8 sp=0xc420302d98
7.3.2019 14:50:12net.cgoLookupIPCNAME.func2(0x7f36ac0008c0, 0x0, 0xc4202c51a0, 0xc4202d6520, 0xc4202ca840, 0x10, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/net/cgo_unix.go:151 +0x171 fp=0xc420302e38 sp=0xc420302dd8
7.3.2019 14:50:12net.cgoLookupIPCNAME(0xc4202ca840, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/net/cgo_unix.go:151 +0x1bd fp=0xc420302f38 sp=0xc420302e38
7.3.2019 14:50:12net.cgoIPLookup(0xc4202be7e0, 0xc4202ca840, 0x10)
7.3.2019 14:50:12	/usr/local/go/src/net/cgo_unix.go:203 +0x4d fp=0xc420302fc8 sp=0xc420302f38
7.3.2019 14:50:12runtime.goexit()
7.3.2019 14:50:12	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420302fd0 sp=0xc420302fc8
7.3.2019 14:50:12created by net.cgoLookupIP
7.3.2019 14:50:12	/usr/local/go/src/net/cgo_unix.go:213 +0xb4
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 1 [select]:
7.3.2019 14:50:12net/http.(*Transport).getConn(0xe59a00, 0xc4202ca820, 0x0, 0xc4202ca700, 0x5, 0xc4202ca840, 0x14, 0x0, 0x0, 0xe8e438)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:913 +0xb92
7.3.2019 14:50:12net/http.(*Transport).RoundTrip(0xe59a00, 0xc42007e200, 0xe59a00, 0xed413189e, 0x4102513)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:378 +0x58c
7.3.2019 14:50:12net/http.send(0xc42007e100, 0xe60200, 0xe59a00, 0xed413189e, 0x4102513, 0xe8e660, 0x0, 0x8, 0xc4202d6500, 0x40fdd8)
7.3.2019 14:50:12	/usr/local/go/src/net/http/client.go:249 +0x162
7.3.2019 14:50:12net/http.(*Client).send(0xc4202c4b40, 0xc42007e100, 0xed413189e, 0x4102513, 0xe8e660, 0xc4202d6500, 0x0, 0x1, 0x442a07)
7.3.2019 14:50:12	/usr/local/go/src/net/http/client.go:173 +0x108
7.3.2019 14:50:12net/http.(*Client).Do(0xc4202c4b40, 0xc42007e100, 0x14, 0x7ffd831e5d06, 0x28)
7.3.2019 14:50:12	/usr/local/go/src/net/http/client.go:595 +0x254
7.3.2019 14:50:12github.com/rancher/storage/vendor/github.com/rancher/go-rancher/v2.setupRancherBaseClient(0xc4202ca6e0, 0xc4202bc3c0, 0x0, 0x0)
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/vendor/github.com/rancher/go-rancher/v2/common.go:157 +0x1f5
7.3.2019 14:50:12github.com/rancher/storage/vendor/github.com/rancher/go-rancher/v2.NewRancherClient(0xc4202bc3c0, 0xc4202bc3c0, 0x11, 0x7ffd831e5d06)
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/vendor/github.com/rancher/go-rancher/v2/generated_client.go:331 +0xca
7.3.2019 14:50:12main.start(0xc42024c8c0, 0xc420193a88, 0x7da084)
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/main.go:90 +0x309
7.3.2019 14:50:12main.main.func1(0xc42024c8c0, 0xc42024c8c0, 0xc420193a6f)
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/main.go:25 +0x2f
7.3.2019 14:50:12github.com/rancher/storage/vendor/github.com/urfave/cli.HandleAction(0x919e00, 0xa0d910, 0xc42024c8c0, 0xc4201f2780, 0x0)
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/vendor/github.com/urfave/cli/app.go:485 +0xd4
7.3.2019 14:50:12github.com/rancher/storage/vendor/github.com/urfave/cli.(*App).Run(0xc4202ac340, 0xc4200100e0, 0x7, 0x7, 0x0, 0x0)
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/vendor/github.com/urfave/cli/app.go:259 +0x70d
7.3.2019 14:50:12main.main()
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/main.go:71 +0x73d
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 17 [syscall, locked to thread]:
7.3.2019 14:50:12runtime.goexit()
7.3.2019 14:50:12	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 5 [chan receive]:
7.3.2019 14:50:12github.com/rancher/storage/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xe8e8e0)
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/vendor/github.com/golang/glog/glog.go:882 +0x7a
7.3.2019 14:50:12created by github.com/rancher/storage/vendor/github.com/golang/glog.init.1
7.3.2019 14:50:12	/go/src/github.com/rancher/storage/vendor/github.com/golang/glog/glog.go:410 +0x21d
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 8 [IO wait]:
7.3.2019 14:50:12net.runtime_pollWait(0x7f36b9dd40d0, 0x72, 0x3)
7.3.2019 14:50:12	/usr/local/go/src/runtime/netpoll.go:164 +0x59
7.3.2019 14:50:12net.(*pollDesc).wait(0xc420284b58, 0x72, 0xe62040, 0xe5dd98)
7.3.2019 14:50:12	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
7.3.2019 14:50:12net.(*pollDesc).waitRead(0xc420284b58, 0xc4202a7000, 0x1000)
7.3.2019 14:50:12	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
7.3.2019 14:50:12net.(*netFD).Read(0xc420284af0, 0xc4202a7000, 0x1000, 0x1000, 0x0, 0xe62040, 0xe5dd98)
7.3.2019 14:50:12	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
7.3.2019 14:50:12net.(*conn).Read(0xc42000e3c0, 0xc4202a7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/net/net.go:181 +0x70
7.3.2019 14:50:12net/http.(*persistConn).Read(0xc42009b320, 0xc4202a7000, 0x1000, 0x1000, 0x4, 0x44f7e0, 0xc4202be000)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:1316 +0x14b
7.3.2019 14:50:12bufio.(*Reader).fill(0xc4201f2c60)
7.3.2019 14:50:12	/usr/local/go/src/bufio/bufio.go:97 +0x117
7.3.2019 14:50:12bufio.(*Reader).Peek(0xc4201f2c60, 0x1, 0xc42004abe5, 0x1, 0x0, 0xc4201f2cc0, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/bufio/bufio.go:129 +0x67
7.3.2019 14:50:12net/http.(*persistConn).readLoop(0xc42009b320)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:1474 +0x196
7.3.2019 14:50:12created by net/http.(*Transport).dialConn
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:1117 +0xa35
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 9 [select]:
7.3.2019 14:50:12net/http.(*persistConn).writeLoop(0xc42009b320)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:1704 +0x43a
7.3.2019 14:50:12created by net/http.(*Transport).dialConn
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:1118 +0xa5a
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 35 [select]:
7.3.2019 14:50:12net/http.setRequestCancel.func3(0x0, 0xc4202c4c00, 0xc4202bc480, 0xc4202c2a5c, 0xc4202be2a0)
7.3.2019 14:50:12	/usr/local/go/src/net/http/client.go:320 +0x17c
7.3.2019 14:50:12created by net/http.setRequestCancel
7.3.2019 14:50:12	/usr/local/go/src/net/http/client.go:330 +0x287
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 36 [select]:
7.3.2019 14:50:12net.(*Resolver).LookupIPAddr(0xeb1263, 0xe65a00, 0xc4202be6c0, 0xc4202ca840, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/net/lookup.go:165 +0x9b1
7.3.2019 14:50:12net.(*Resolver).internetAddrList(0xeb1263, 0xe65a00, 0xc4202be6c0, 0x9f5926, 0x3, 0xc4202ca840, 0x14, 0x0, 0x0, 0xc42004b7e8, ...)
7.3.2019 14:50:12	/usr/local/go/src/net/ipsock.go:245 +0x4cc
7.3.2019 14:50:12net.(*Resolver).resolveAddrList(0xeb1263, 0xe65a00, 0xc4202be6c0, 0x9f5ba0, 0x4, 0x9f5926, 0x3, 0xc4202ca840, 0x14, 0x0, ...)
7.3.2019 14:50:12	/usr/local/go/src/net/dial.go:188 +0x6b3
7.3.2019 14:50:12net.(*Dialer).DialContext(0xc420080360, 0xe659c0, 0xc420016200, 0x9f5926, 0x3, 0xc4202ca840, 0x14, 0x0, 0x0, 0x0, ...)
7.3.2019 14:50:12	/usr/local/go/src/net/dial.go:349 +0x247
7.3.2019 14:50:12net.(*Dialer).DialContext-fm(0xe659c0, 0xc420016200, 0x9f5926, 0x3, 0xc4202ca840, 0x14, 0xc42004ba60, 0x6455fd, 0xc420016200, 0x94ec00)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:45 +0x73
7.3.2019 14:50:12net/http.(*Transport).dial(0xe59a00, 0xe659c0, 0xc420016200, 0x9f5926, 0x3, 0xc4202ca840, 0x14, 0x0, 0x0, 0x0, ...)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:849 +0x227
7.3.2019 14:50:12net/http.(*Transport).dialConn(0xe59a00, 0xe659c0, 0xc420016200, 0x0, 0xc4202ca700, 0x5, 0xc4202ca840, 0x14, 0x0, 0x0, ...)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:1008 +0x1c4c
7.3.2019 14:50:12net/http.(*Transport).getConn.func4(0xe59a00, 0xe659c0, 0xc420016200, 0xc4202c4cc0, 0xc4202be360)
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:908 +0x78
7.3.2019 14:50:12created by net/http.(*Transport).getConn
7.3.2019 14:50:12	/usr/local/go/src/net/http/transport.go:910 +0x3a3
7.3.2019 14:50:12
7.3.2019 14:50:12goroutine 37 [select]:
7.3.2019 14:50:12net.cgoLookupIP(0xe65a00, 0xc4202be6c0, 0xc4202ca840, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/net/cgo_unix.go:214 +0x2f5
7.3.2019 14:50:12net.(*Resolver).lookupIP(0xeb1263, 0xe65a00, 0xc4202be6c0, 0xc4202ca840, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/net/lookup_unix.go:69 +0x125
7.3.2019 14:50:12net.(*Resolver).(net.lookupIP)-fm(0xe65a00, 0xc4202be6c0, 0xc4202ca840, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/net/lookup.go:156 +0x56
7.3.2019 14:50:12net.glob..func11(0xe65a00, 0xc4202be6c0, 0xc4202c2af0, 0xc4202ca840, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
7.3.2019 14:50:12	/usr/local/go/src/net/hook.go:19 +0x52
7.3.2019 14:50:12net.(*Resolver).LookupIPAddr.func1(0x6baa5a, 0x6c4118, 0xe59a00, 0xe659c0)
7.3.2019 14:50:12	/usr/local/go/src/net/lookup.go:162 +0x5c
7.3.2019 14:50:12internal/singleflight.(*Group).doCall(0xe8d650, 0xc4202cc190, 0xc4202ca840, 0x10, 0xc4202c4de0)
7.3.2019 14:50:12	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x3c
7.3.2019 14:50:12created by internal/singleflight.(*Group).DoChan
7.3.2019 14:50:12	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x323

**Other details that may be helpful:**

**Environment information**
- Rancher version rancher/server: stabile (1.6.26)
- Installation option: HA

**Cluster information**
- Cluster type: Cattle
- Machine type: metal
- Specifications CPU: 16 Threading Cores
- Specifications Memory: 283 GB
- Docker version: 
```
18.03.1-ce
```

**Comment by superseb** [comment]
Does your Rancher FQDN contain `.local`? See https://github.com/rancher/rancher/issues/9322

**Comment by svenluzar** [comment]
> Does your Rancher FQDN contain `.local`? See #9322

![image](https://user-images.githubusercontent.com/695812/53971785-d2db4600-40fd-11e9-958f-1483df995fe9.png)

**Comment by superseb** [comment]
Can you share the output of `dig rancher.beemo.eu`? And is `rancher.beemo.eu` also the currently configured Host Registration URL in Rancher?

**Comment by svenluzar** [comment]
Thank you so much for the hint. 

The problem had its origin in the file `/etc/resolve.conf`

Ubuntu adds the following line by default:
`options edns0`

You can remove the line, but after a restart of the service is the option back. 
`service resolvconf restart`

Currently I haven't found a permanent solution to the problem,
but it's an accepted bug in the Ubuntu operating system:

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1817903
