### ISSUE TITLE
[go-rancher] Rancher Client example for creating a cluster

### ISSUE THREAD

**Issue by rohithsharmaks** [rancher/rancher#18680]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

I am trying to use go-rancher v3 API to create cluster. I didn't see any examples wrt to go-rancher API. I am writing provisioning layer using go-rancher API's. Basically my use case is to create/delete cluster in rancher. I was able to create a cluster using  REST end point, but didn't any info how to use go-rancher api to create/delete cluster. 
It would be helpful if any point out for existing go-rancher document demonstrating simple example.

**Comment by rawmind0** [comment]
Hi @rohithsharmaks, rancher/go-rancher repo is just for use with rancher v1.6. 

For rancher v2.x you should use go client from [rancher/types](https://github.com/rancher/types/tree/master/client) . On rancher v2.x, go client has 3 parts:
- management to do tasks at global level. 
- cluster to do tasks at cluster level.
- project to do tasks at projects level. 

To create a cluster,  you need basically to:
- connect to API using [generated client](https://github.com/rancher/types/blob/master/client/management/v3/zz_generated_client.go) functions.
- use [generated cluster](https://github.com/rancher/types/blob/master/client/management/v3/zz_generated_cluster.go) functions to set cluster data and create it.

For some examples, you could take a look at [rancher/cli](https://github.com/rancher/cli/blob/master/cmd/cluster.go) cluster cmd and at [rancher/terraform-provider-rancher2](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_cluster.go#L290) cluster resource.

**Comment by rohithsharmaks** [comment]
Thanks @rawmind0  for your inputs! I will try these API's and get back to you with updates.

**Comment by rohithsharmaks** [comment]
I could able to make use of pointed reference. Closing the issue.

**Comment by gongzg1115** [comment]
Could you give a Rancher Client example for creating a cluster?
I met the same error "x509: certificate signed by unknown authority"
