### ISSUE TITLE
[rancher-compose] Interpolate environment variables

### ISSUE THREAD

**Issue by VogonogoV** [rancher/rancher#1868]
docker-compose version 1.5 (release date TBD) will [support environment variables](https://github.com/docker/compose/pull/1765) in docker-compose.yml files. I would like to use this feature in a Continuous Integration/Deployment setup. The workflow will be like:

1. A developer commits code and pushes the code to a repository
2. A build is triggered in a CI tool (like Jenkins)
3. The unique IDs are inserted in environment variables
4. The docker images will be built, and tagged with unique IDs, then pushed to the registry
5. Jenkins will use rancher-compose to deploy the docker-compose file where the unique IDs are interpolated

An example docker-compose file could be:
```yaml
web:
  image: "registry.example.com/myapplication:$IMAGE_TAG"
```
Where IMAGE_TAG will be `latest` for a developer when is working locally. And can be a unique ID when rancher-compose is used, to make sure the right version is deployed.

**Comment by ibuildthecloud** [comment]
@VogonogoV Rancher Compose is based off of github.com/docker/libcompose so I've created an issue https://github.com/docker/libcompose/issues/40 in that repo to track this.  It will be supported by the time 1.5 is released, hopefully earlier.

**Comment by deniseschannon** [comment]
Merged in all relevant places. @sangeethah

**Comment by aruneli** [comment]
```Component 	Version
Rancher 	v0.41.0-rc1
Cattle 	v0.99.0
User Interface 	v0.55.0
Rancher Compose 	beta/latest```

It is not working as expected. Below in an example docker-compose.yml that was used to test

```Arunkumars-MacBook-Pro-2:rancher aruneli$ env | grep IMAGE
IMAGE1_TAG=15.02
IMAGE_TAG=14.02
Arunkumars-MacBook-Pro-2:rancher aruneli$ cat docker-compose.yml
test:
  tty: true
  image: ubuntu:$IMAGE_TAG
  stdin_open: true
  volumes_from:
  - test-data
  labels:
    io.rancher.sidekicks: test-data
test-data:
  tty: true
  command:
test:
  - cat
  image: ubuntu:$IMAGE1_TAG
  stdin_open: true```

**Comment by aruneli** [comment]
Verified with compose release - v0.4.1-rc2
