### ISSUE TITLE
A certificate volume mount becomes a secret volume mount when editing via UI

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#18685]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. add a certificate to Rancher (I did this via cert-manager with an LE cert off of an ingress)
2. deploy something and add the certificate as a volume on `/etc/ssl/certs`
3. save 
4. edit it again

**Result:**

The Certificate volume mount becomes a Secret volume mount, but the certificate is not available for selection. Only Secrets are available. It's not possible to change the Secret type; the volume must be removed and re-added.

**Other details that may be helpful:**

**Environment information**
- 2.1.6
- single

**Comment by loganhz** [comment]
fixed in master-head
