### ISSUE TITLE
Rancher Server (single node) with persistent volume will restart endlessly, with no error messages or logs whatsoever

### ISSUE THREAD

**Issue by kingmatusevich** [rancher/rancher#18694]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
rancher is a volume, but I also tried using a directory. 
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:latest -v rancher:/var/lib/rancher
```

**Result:**
if you look at the `docker ps` results, you'll see it start for a second and then restart, over and over.
If you check the `docker logs`, you see only the rancher version over and over. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Latest
- Installation option (single install/HA):
Single install

- Docker version (use `docker version`):
18.0.9
```
(paste the output here)
```

**Comment by superseb** [comment]
As shown on https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#persistent-data, the command is (volume param is part of docker, not rancher):

```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v /host/rancher:/var/lib/rancher \
  rancher/rancher:latest
```

Let me know if this doesn't solve the issue.
