### ISSUE TITLE
Rancher UI to include the the rancher/agent and rancher/agent-instance versions for private registry support

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1869]
By adding the ability to support running Rancher from private registries (https://github.com/rancher/rancher/issues/924), it'd be nice to have the rancher/agent and rancher/agent-instance image versions tied with the rancher/server available from the versions page.

**Comment by vincent99** [comment]
These would need to be in the unprivileged settings API first @ibuildthecloud
