### ISSUE TITLE
Set default prometheus retention period to 12 hours

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#18695]
The metrics volume can be expensive on disk space. Since the default setup for prometheus is ephemeral storage, we should shorten the retention interval. In a 50 node cluster with all the end points being scraped, Prometheus can be writing GB of data per day. 

I recommend a shorter retention window of 12 hours. The user can always change this if they want to.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/8/19) bda75638b43f
Confirmed issue. The default retention period is now 12 hours:
![image](https://user-images.githubusercontent.com/45179589/54047561-99a1e500-4194-11e9-8671-c88471f55d6e.png)

Confirmed upon form submission `prometheus.retention: "12h"`
