### ISSUE TITLE
Upgrade - rancher- rke clusters go to 'Updating' status when upgraded from rancher v2.1.7 to v2.2.0-rc3 for k8s v1.13.4

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18704]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Have a HA setup with rancher:v2.1.7.
2. Create rke clusters - DO/AWS/Azure.
3. Upgrade the rancher to v2.2.0-rc3.

**Expected Result:**
The clusters do not update, should go from `Unavailable` to `Active` state.

**Actual Result:**
The cluster with k8s v1.13.4 go to `Updating` state after upgrade.

**Note:** This happens only to clusters with k8s v1.13.4 and not on clusters with k8s v1.11.8 or v1.12.6.

<img width="1332" alt="screen shot 2019-03-07 at 3 35 27 pm" src="https://user-images.githubusercontent.com/26032343/53998692-7e33cd00-40f5-11e9-8c8b-d43cb94f6d41.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version: rancher v2.1.7 to v2.2.0-rc3 
- Installation option: HA

**Cluster information**
- Cluster type: rke cluster - DO/Amazon EC2/Azure
- Kubernetes version (use `kubectl version`):

```
v1.13.4
```

- Docker version (use `docker version`):

```
18.9.3
```

**Comment by alena1108** [comment]
@sowmyav27 the issue has been fixed with b7bced5d6d8821d88380fb991f24aa2d7dd8f70d, can you retest

**Comment by sowmyav27** [comment]
verified on `rancher:master`(08/03/2019). when upgraded from v2.1.7 to master, the cluster temporarily go into `Unavailable` state and then become active. There is no updating of the clusters that happens on the UI as well as in the rancher logs.
