### ISSUE TITLE
The logging example port is incorrect

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18708]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Rancher version:** rancher/rancher:master 3/8/19

- The zookeeper default port is 2181, not 9200
![image](https://user-images.githubusercontent.com/19684717/54002080-5f324b00-4188-11e9-827a-7184464ccca4.png)

- The Kafka default port is 9092, not 9200
![image](https://user-images.githubusercontent.com/19684717/54002101-6bb6a380-4188-11e9-9349-938f475b09ec.png)

- The Splunk default port is 8088, not 9200
![image](https://user-images.githubusercontent.com/19684717/54002113-76713880-4188-11e9-8525-b943b9afe00a.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/8/19) bda75638b43f
Validated each area:
- The zookeeper default port is 2181, not 9200
This is now fixed, is now 2181.
- The Kafka [Broker] default port is 9092, not 9200
This is now fixed, is now 9092
- The Splunk default port is 8088, not 9200
This is now fixed, is now 8088
