### ISSUE TITLE
Ability to specify display name for custom cluster driver

### ISSUE THREAD

**Issue by guilhem** [rancher/rancher#18719]
**What kind of request is this (question/bug/enhancement/feature request):**

enhancement

**Steps to reproduce (least amount of steps as possible):**

* Add a custom cluster driver

**Result:**

Name is the end of the binary name... Oo

**Other details that may be helpful:**

What would be awesome is to be able to set a "user-friendly name" without having to fork UI and edit translation files...

**Comment by janeczku** [comment]
Currently the driver name displayed in the GUI is derived from the driver binary file name suffix.
E.g. a driver whose filename is `kontainer-engine-driver-aks2` will be displayed as `Aks2` instead of a pretty name like the built-in drivers have, e.g. `Azure AKS`.
