### ISSUE TITLE
LB (haproxy): support for custom parameters

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1871]
We should let user define custom default config parameters for haproxy config ("defaults" section has parameters like timeout, maxconn, maxpipes, etc). Those parameters are arbitrary, and won't interfere with config changes propagated by Rancher.

One approach would be to define it in the labels for the lb service in the format:

io.rancher.loadbalancer.custom.defaults

Later on - not in the initial version as it has some implications - we might also add support custom params for frontend/backend sections:

io.rancher.loadbalancer.custom.frontend.${PORT}
io.rancher.loadbalancer.custom.backend.${SERVICE_NAME}

**Comment by kaos** [comment]
+1 for this.. :)

**Comment by Moridinmhael** [comment]
+1 from me as well

**Comment by rewop** [comment]
As discussed in the forum: http://forums.rancher.com/t/load-balancer-redirect-80-to-443/470.

A use case may be adding redirect rules from port 80 to 443 to ensure the communication is always encrypted from the web.

In HAProxy config it is:
```
redirect scheme https if !{ ssl_fc }
```

**Comment by nhumrich** [comment]
+1

**Comment by flaccid** [comment]
+1

**Comment by nixelsolutions** [comment]
+1

**Comment by MhdAli** [comment]
:+1:

**Comment by c58** [comment]
+1

**Comment by Rucknar** [comment]
+1

**Comment by diranged** [comment]
+1

**Comment by demarant** [comment]
+1 
so we can change the HAproxy load balancing algorithms and many other features that are not available (or will take time) to be part of the rancher UI

**Comment by blaggacao** [comment]
+1 
--------------
(I'm just entering the topic) I'd think of a DDOS protection:

```
  # DDOS protection
  # Use General Purpose Couter (gpc) 0 in SC1 as a global abuse counter
  # Monitors the number of request sent by an IP over a period of 10 seconds
  stick-table type ip size 1m expire 1m store gpc0,http_req_rate(10s),http_err_rate(10s)
  tcp-request connection track-sc1 src
  tcp-request connection reject if { sc1_get_gpc0 gt 0 }
  # Abuser means more than 100reqs/10s
  acl abuse sc1_http_req_rate(ft_web) ge 100
  acl flag_abuser sc1_inc_gpc0(ft_web)
  tcp-request content reject if abuse flag_abuser
```

stolen from: http://blog.haproxy.com/2012/10/12/scalable-waf-protection-with-haproxy-and-apache-with-modsecurity/

I would be also ok to be this a standard feature :smile:

**Comment by fentas** [comment]
+1

**Comment by lukerandall** [comment]
+1

**Comment by flower-pot** [comment]
This would be awesome! :+1:

**Comment by qrpike** [comment]
+1

**Comment by iamveen** [comment]
Yes please +1

**Comment by jloisel** [comment]
+1 on this, we would like to enable gzip compression on haproxy since it's much more efficient that enabling it in our backend. (Tomcat)

**Comment by AnalogJ** [comment]
Have you guys looked at solving this using multiple haproxy -f flags? If we could upload a custom configuration file, that was included after the rancher generated config file, that would work for me :)

**Comment by mebinum** [comment]
:+1:

**Comment by kaos** [comment]
:+1: for the suggestion from @AnalogJ :)

**Comment by alena1108** [comment]
@AnalogJ when pass multiple config files with -f option, "default" sections don't get merged. Each "default" section is respected only within the same haproxy.cfg file content. 

We started by adding support for custom parameters for "defaults" and "global" sections. 

@sangeethah they can be specified in loadBalancerConfig.haproxyConfig parameter ("global" and "defaults" fields). There is gonna be UI support for that; and for validation test reference, you can check this file for the syntax: https://github.com/rancher/cattle/blob/8963edc5032c21356f53602aa02b14128af5f02b/tests/integration/cattletest/core/test_svc_discovery_lb.py#L313

**Comment by AnalogJ** [comment]
@alena1108 damn, thats unfortunate. I've used the `-f` and `--` flags before, but only in simple applications, didn't realize the global sections never merged across files.

It looks like you're going to have to go the route of manually generating a config file. 
From what I've read, something like the folder structure specified in https://www.mail-archive.com/haproxy@formilux.org/msg00742.html might be the most customizable and clear, but definitely would require alot more work than just uploading a single file. 

You could also solve this by parsing the user given file, breaking it up into the component sections, merging it with the rancher generated sections, and then merging all the sections again into the final rancher haproxy.cfg file

**Comment by sangeethah** [comment]
Tested with rancher server version - v0.50-rc1

Tested for LB services by passing haproxyConfig parameters for format:

"haproxyConfig": {
"global": <values>,
"defaults": <values> ,
},

The values passed for "global" and "defaults" are appended to the end in "global" and "default" section in haproxy.conf file.

Tested with UI as well as using rancher-compose version v0.6.2.

**Comment by Negashev** [comment]
And what about Basic Auth #1178

**Comment by sebmoule** [comment]
How can we use this for basic auth on specific target ?

**Comment by deniseschannon** [comment]
@Negashev @sebmoule This is going to be covered as part of https://github.com/rancher/rancher/issues/2179

**Comment by meggarr** [comment]
May I ask how to use custom rules for a specific backend service (k8s)? E.g. I want to customize the config below only for `coper` service, is it possible?
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: cloud
  name: api
  annotations:
    config: "backend\nhttp-request set-path %[path,regsub(^/coper,/)]"
spec:
  rules:
  - http:
      paths:
      - path: /coper
        backend:
          serviceName: coper
          servicePort: 80
      - path: /diag
        backend:
          serviceName: diag
          servicePort: 80
```

**Comment by aemneina** [comment]
@meggarr can you try replacing `backend` with `backend 80_`

**Comment by meggarr** [comment]
@aemneina okay, it seems working when it is `backend 80_coper\nhttp-request set-path %[path,regsub(^/coper,/)]`

However, I was trying `set-path %[path,regsub(^/[^/]*,/)]`, but as the HAProxy's `regsub` does not support brackets in regular expression, [1.7dev change log](https://github.com/haproxy/haproxy/commit/7d1b48fae0e8d98d259df60dbe048b0179fa254c), so can rancherlb support a annotation to automatically strip path?

I can help a PR if someone can guide me where is related code. :-)
