### ISSUE TITLE
Adding custom cluster can only support one node

### ISSUE THREAD

**Issue by gyliu513** [rancher/rancher#18717]
*Describe your issue here*

When adding a cluster with `From my own existing nodes`, I found that I can only create a cluster on one node, how can I create a cluster with multiple nodes? 

![image](https://user-images.githubusercontent.com/4461983/54021270-b822d300-41ca-11e9-8c37-a56f31f7b5a7.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.6` UI: `v2.6` |
|Route|`global-admin.clusters.new`|

**Comment by superseb** [comment]
The command is dynamically generated based on the options you select, you can run that command on 1 or 10 hosts, depending on how you want to setup your cluster.

For example, select only etcd and run the command on 3 separate nodes, select only controlplane and run the command on 2 separate nodes, select only worker and run the command on 2 workers to get a decent HA cluster.

**Comment by gyliu513** [comment]
Thanks @superseb , this helps ;-)
