### ISSUE TITLE
HPA metrics server api issue

### ISSUE THREAD

**Issue by kc004** [rancher/rancher#18712]
**What kind of request is this (question/bug/enhancement/feature request):** Question

**Steps to reproduce (least amount of steps as possible):** I have Total 3 server cluster. 
Server1: All (control plane, ETCD and Worker)
Server2: ETCD and Worker
Server3: Worker

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA):  Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Bare metal
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`): 17.03

Master API server is having issue with kube-apiserver-proxy-client.

<pre>
1 x509.go:172] x509: subject with cn=system:node is not in the allowed list: [kube-apiserver-proxy-client]
1 x509.go:172] x509: subject with cn=system:node is not in the allowed list: [kube-apiserver-proxy-client]
1 x509.go:172] x509: subject with cn=system:node is not in the allowed list: [kube-apiserver-proxy-client]
1 x509.go:172] x509: subject with cn=system:node is not in the allowed list: [kube-apiserver-proxy-client]
1 x509.go:172] x509: subject with cn=system:node is not in the allowed list: [kube-apiserver-proxy-client]
1 x509.go:172] x509: subject with cn=system:node is not in the allowed list: [kube-apiserver-proxy-client]
1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
1 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]
1 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
1 trace.go:76] Trace[1570494268]: "Get /api/v1/namespaces/default/secrets/netes-default-token-45bfe" (started: 2019-03-08 04:49:39.608414017 +0000 UTC m=+51457.671723654) (total time: 1m0.002137305s):
Trace[1570494268]: [1m0.002137305s] [1m0.002130994s] END
1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
1 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]
1 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
1 trace.go:76] Trace[1293998141]: "Get /api/v1/namespaces/kube-system/secrets/canal-token-2c58a" (started: 2019-03-08 04:49:39.639400875 +0000 UTC m=+51457.702710517) (total time: 1m0.002146292s):
Trace[1293998141]: [1m0.002146292s] [1m0.002138856s] END
1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
1 x509.go:172] x509: subject with cn=system:kube-proxy is not in the allowed list: [kube-apiserver-proxy-client]
1 x509.go:172] x509: subject with cn=system:kube-proxy is not in the allowed list: [kube-apiserver-proxy-client]
1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
1 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]
1 x509.go:172] x509: subject with cn=system:kube-scheduler is not in the allowed list: [kube-apiserver-proxy-client]
1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [kube-apiserver-proxy-client]
</pre>

I have changed my kubelet setting for metrics sever and HPA.
<pre>
services: 
  etcd: 
    creation: "12h"
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    retention: "72h"
    snapshot: true
  kube-api: 
    extra_args: 
      proxy-client-cert-file: "/etc/kubernetes/ssl/kube-proxy.pem"
      proxy-client-key-file: "/etc/kubernetes/ssl/kube-proxy-key.pem"
      requestheader-client-ca-file: "/etc/kubernetes/ssl/kube-ca.pem"
      requestheader-extra-headers-prefix: "X-Remote-Extra-"
      requestheader-group-headers: "X-Remote-Group"
      requestheader-username-headers: "X-Remote-User"
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kube-controller: 
    extra_args: 
      horizontal-pod-autoscaler-downscale-delay: "5m0s"
      horizontal-pod-autoscaler-sync-period: "30s"
      horizontal-pod-autoscaler-upscale-delay: "1m0s"
  kubelet: 
    extra_args: 
      authentication-token-webhook: "true"
      max-pods: "250"
      read-only-port: "10255"
    fail_swap_on: false
ssh_agent_auth: false
</pre>

Is there any issue with this config?

**Comment by superseb** [comment]
Please use the issue template and supply the used versions and steps to reproduce.

**Comment by superseb** [comment]
The settings are no longer needed on clusters created in v2.0.7 and higher as described on https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/horitzontal-pod-autoscaler/.

Please let me know if you can supply the steps to reproduce so we can investigate other issues with default cluster creation.
