### ISSUE TITLE
Workload logs "view logs" are empty

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#18715]
**What kind of request is this (question/bug/enhancement/feature request):**
**BUG**

**Steps to reproduce (least amount of steps as possible):**
Create a cluster
Create a workload in default namespace (for example nginx image)
Wait for green
Click "View logs"

**Result:**
It stays empty
![bildschirmfoto 2019-03-07 um 20 05 01](https://user-images.githubusercontent.com/1597621/53982097-53a53c80-4114-11e9-9ab0-9940e5b6e79e.png)

**Other details that may be helpful:**
Rancher 2.1.7
Cluster @ Hetzner
Ubuntu 16

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
  - **Bare metal**
- Machine type (metal) and specifications (CPU/memory): **4GB**
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by superseb** [comment]
nginx doesn't log anything by default, see `docker run nginx`. If it's happening with all containers, please share if `docker logs` on the command line does output anything and `docker info` from the node(s) in the cluster.

**Comment by exocode** [comment]
thank you! you were right (of course) :-)

**Comment by superseb** [comment]
Filed https://github.com/rancher/rancher/issues/18722 to see if we can notify user when logs are empty
