### ISSUE TITLE
[Document] `cluster types` is not reachable

### ISSUE THREAD

**Issue by gyliu513** [rancher/rancher#18724]
*Describe your issue here*

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/cloning-clusters/

![image](https://user-images.githubusercontent.com/4461983/54034910-0b108080-41f3-11e9-8fd5-93482096b01c.png)

Click `cluster types` is return `404 Not Found`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc3` UI: `v2.2.4` |
|Route|`global-admin.clusters.new`|

**Comment by superseb** [comment]
Thanks for reporting, should get fixed in https://github.com/rancher/docs/pull/1221
