### ISSUE TITLE
Flannel: Pod unable to connect to itself via service IP

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#18721]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create cluster with flannel CNI
2. Create a deployment using for example an Nginx image
3. Create a service of type clusterIP that maps to port 80 of the deployment
4. Exec into the pod that has been created by the deployment
5. Execute `curl http:://<Service Cluster IP>`

**Result:**
Curl command fails with connection refused or timeout

**Other details that may be helpful:**
The flannel template used by RKE is out of sync with the recommended upstream configuration and does not enable hairpin mode for the bridge interface.

https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#a-pod-cannot-reach-itself-via-service-ip

Use cases:
Clustered applications like Mongo, Cassandra where pods must connect to their peers using the service IP.

**Environment information**
Rancher v2.1.1.7

**Comment by janeczku** [comment]
https://github.com/rancher/rke/issues/1168

**Comment by loganhz** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#a-pod-cannot-reach-itself-via-service-ip

It says “If the effective hairpin mode is hairpin-veth, ensure the Kubelet has the permission to operate in /sys on node.”

I think RKE doesn’t give kubelet that permission. So we hit this issue.

A workaround is running `for intf in /sys/devices/virtual/net/cni0/brif/*; do echo 1 > $intf/hairpin_mode; done` on the node manually.

**Comment by alena1108** [comment]
For flannel, there was no image update, but there was a template update. To verify template update, check kube-flannel-cfg config map (kube-system namespace) - it should have the following parameters set:

```
delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
```

**Comment by sangeethah** [comment]
Tested with rancher server built from master-head (Jul 17)
Created a RKE cluster uisng flannel network mode.
hairpinMode is enabled as expected
> kubectl get configmap kube-flannel-cfg -n kube-system -o json
{
    "apiVersion": "v1",
    "data": {
        "cni-conf.json": "{\n  \"name\": \"cbr0\",\n  \"plugins\": [\n    {\n      \"type\": \"flannel\",\n      \"delegate\": {\n        \"hairpinMode\": true,\n        \"isDefaultGateway\": true\n      }\n    },\n    {\n      \"type\": \"portmap\",\n      \"capabilities\": {\n        \"portMappings\": true\n      }\n    }\n  ]\n}\n",
        "net-conf.json": "{\n  \"Network\": \"10.42.0.0/16\",\n  \"Backend\": {\n    \"Type\": \"vxlan\",\n    \"VNI\": 1,\n    \"Port\": 8472\n  }\n}\n"
    },
\"delegate\": {\n        \"hairpinMode\": true,\n        \"isDefaultGateway\": true\n      }\n    },\n
```
Create a deployment
Create a service of type clusterIP that maps to port 80 of the deployment
Exec into the pod that has been created by the deployment
Execute curl http:://<Service Cluster IP>
Able to reach itself successfully.
```
root@mytest1-7d8497cdb-pq52f:/# curl 10.43.20.67/name.html
mytest1-7d8497cdb-pq52f
root@mytest1-7d8497cdb-pq52f:/# 
```
