### ISSUE TITLE
OpenStack Node Driver still request cloud provider from UI

### ISSUE THREAD

**Issue by gyliu513** [rancher/rancher#18725]
*Describe your issue here*

Add a cluster based on openstack node driver.

![image](https://user-images.githubusercontent.com/4461983/54035456-5bd4a900-41f4-11e9-8080-6e4dcaf9804a.png)

When configure, there are still request to select cloud provider, why? As here I was already using OpenStack.

![image](https://user-images.githubusercontent.com/4461983/54035480-70b13c80-41f4-11e9-994c-6a03f136208d.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc3` UI: `v2.2.4` |
|Route|`global-admin.clusters.new`|

**Comment by Oats87** [comment]
@gyliu513 The node template provider you choose does not directly correlate to the "Cloud Provider" option in the Cluster Options. The node template provider is simply the provider where instances will be created, rather dealing with anything to configure Kubernetes to talk to OpenStack for cloud provider integration for storage/LB/etc.

**Comment by gyliu513** [comment]
@Oats87 so you mean that the `Cloud Provider` is used to provide integration with storage/LB etc? Still not quite clear about this, can you please show more detail or does there are any document that I can refer? Thanks.
