### ISSUE TITLE
Cloud Credential - 'Region' field is not a mandatory field on the Add Cloud Credential page for Amazon type

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18739]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. On the Rancher UI, go to Cloud Credential page.
2. Click on 'Add Cloud Credential'.
3. Select Cloud Credential type: Amazon and enter the Access Key and Secret Key (Mandatory fields)
4. Click on create.

**Expected Result:**
Region field is made mandatory or has a value by default, so that appropriate error message gets populated.

**Actual Result:**
Error `undefined ConfigError: There was a problem validating your keys. Enter valid credentials and try agian.` is seen on the UI.

<img width="994" alt="Screen Shot 2019-03-08 at 12 05 10 PM" src="https://user-images.githubusercontent.com/26032343/54053133-31a2cd00-419b-11e9-8dab-01d4f099dff1.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): HA

**Comment by westlywright** [comment]
The region field is required to validate keys. We validate the keys by making a call to the AWS api. In order to call the AWS api you must give a region. Technically it is not required to save the resource but I don't think that matters nor do I think it would be useful to explain this to the user.

**Comment by sowmyav27** [comment]
Verified on `rancher:master`. 'Region' field has been marked mandatory. If you don't enter region, it throws an appropriate error `You must select a region in order to validate your keys`.
