### ISSUE TITLE
When editing some areas in UI, has "Add/Create" in title and "Create" button

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18730]
Version: Master 2.2 (3/7/19) a3f8c48fe1e6

**Summary:**
When editing some areas in the UI, it has "Create" in title and "Create" button. In one area if you Create you see a "Save" button.

**What kind of request is this:**
Bug

**Problem Areas:**

_New v2.2 features:_
- [x] **Edit** Global DNS Provider
Shows Title "Add Global DNS Provider" (%globalDnsPage.providersPage.add%) should be "Edit Global DNS Provider"
Shows "Create" button (%saveCancel.create%) should be "Save" button (%saveCancel.edit%).

- [x] **Add** Global DNS Entry
Shows "Save" button (%saveCancel.edit%) should be "Create" button (%saveCancel.create%)

- [x] **Edit** Global DNS Entry
Shows Title "Add Global DNS Entry" (%globalDnsPage.entriesPage.add%) should be "Edit Global DNS Entry". The button is already correct Save button when editing.

- [x] **Edit** Cloud Credential
Shows Title "Add Cloud Credential" (%modalAddCloudKey.header%) should be "Edit Cloud Credential"

_Not-new features:_
- [x] **Edit** AKS Cluster
Shows the "Create" button (%saveCancel.create%) should be "Save" button (%saveCancel.edit%)

**Other details that may be helpful:**
I checked other areas especially new v2.2 features like Cloud Credentials and Node Templates changes to list a couple and these were either already fixed or are correct. I did my best to explore the whole UI to check everything.

**Comment by sangeethah** [comment]
This issue is also seen in "Edit Cloud Credential" page.

**Comment by davidnuzik** [comment]
^^ Updated issue description to include this.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/11/19) HA Setup
Re-opening. All issues are resolved except for one. I unchecked this in the issue description:

- **Add** Global DNS Entry
Shows "Save" button (%saveCancel.edit%) should be "Create" button (%saveCancel.create%)

It is still a "Save" button. It should be a "Create" button when add a new GDNS entry.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/11/19) HA Setup
Confirmed issue. All areas were fixed exactly as requested in the issue description.
The **Add** Global DNS Entry button has been fixed. When you add an entry it is now a create button.
