### ISSUE TITLE
Backport: Node Status - Disk space bar is red even there is no disk pressure

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#18733]
Backport https://github.com/rancher/rancher/issues/17767 to 2.1.x

Update: Requires #14392 in 2.1.x

**Comment by ainiml** [comment]
Can confirm, v2.1. has this issue

**Comment by devfelipereis** [comment]
I have the same in v2.1.7

**Comment by alena1108** [comment]
Happens for the clusters having k8s 1.13

**Comment by coyoty** [comment]
can also confirm this running k8s 1.13.4 and rancher 2.1.7

**Comment by bongaquino** [comment]
Same here.

**Comment by ArgonV** [comment]
Can confirm this after upgrading to Rancher 2.1.7, the cluster to RKE 1.13, using vSphere cloud config, and vSphere node driver templates.

**Comment by westlywright** [comment]
Has not been added to a 2.1.8 rc release yet but the UI tag `2.2.30` contains the fix for this and could probably be verified without a new RC.

**Comment by westlywright** [comment]
Backported to UI tag `2.1.21`. No RC candidate but this could be verified on a 2.1 with this UI tag.

**Comment by davidnuzik** [comment]
This requires waiting for a fix for #14392 in v2.1.x
I cannot change the UI url in current v2.1.7 / v2.1.8 due to that issue (well, it submits but does not take effect due to the bug).
cc: fyi @cjellick

**Comment by davidnuzik** [comment]
Note: is awaiting a v2.1.x RC

**Comment by alena1108** [comment]
Can be tested in v2.1.9-rc1

**Comment by davidnuzik** [comment]
Version: v2.1.9-rc1

Carefully followed the steps outlined in #17767 (3 nodes, each with 1 role, 40GB disk space each, ec2 rke cluster, check node status for each)
I no longer see the red "Disk Space" warning on the node dashboard view for each node.
I also do not see it while the nodes are still provisioning (but you can see the node dashboard while you wait for them to be fully up and ready).

![image](https://user-images.githubusercontent.com/45179589/56164452-9107b000-5f85-11e9-84d7-15ecfbd27264.png)
