### ISSUE TITLE
Multicluster app - Allow admin to edit all multicluster apps

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#18734]
rancher/rancher:master-38fd13a8 3/7
HA installation

* As `admin` create cluster 
* As `admin` create projects
* As `admin` add `User2` as cluster owner
* As `User2` create multicluster app
* As `admin` edit multicluster app roles/members/target projects

Expected:
* Admin is able to make edits to the multicluster app

Actual:
* HTTP 500 - `user user-pz84w is not in members list`

**Comment by sangeethah** [comment]
@bmdepesa Wait for the fix for issues - https://github.com/rancher/rancher/issues/18774 , before you validate this issue .

**Comment by bmdepesa** [comment]
rancher/rancher:master 3/12

* Created two clusters
* Created additional user
* Added second user as cluster owner to one of the clusters
* Login as second user and create a multicluster app in the cluster where user has access
* Login as admin (without admin being added as a member to MCA) and add a second target project
* Target projects / MCA updated successfully.
