### ISSUE TITLE
Azure and VMware node templates are tagged to incorrect cloud credentials

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18737]
**What kind of request is this:** bug

**Steps to reproduce:**
1. In a Rancher HA set up, create an Amazon cloud credential.
2. Create an Azure/VMware cloud credential.
3. Go to 'Node Templates' page.
4. Create an Azure/VMware node template. 
5. Select the appropriate azure/vmware cloud credential while creating the template.
6. After creation of the template, click on 'View in API'

**Expected Result:**
`cloudCredentialId` should be tagged to the azure/vmware cloud credential selected while creating the template.

**Actual Result: **
`cloudCredentialId` is tagged to Amazon cloud credential, which is the first one on the Cloud Credentials page.

<img width="407" alt="Screen Shot 2019-03-08 at 12 00 39 PM" src="https://user-images.githubusercontent.com/26032343/54052704-f784fb80-4199-11e9-8832-97bcc8d0276d.png">
<img width="343" alt="Screen Shot 2019-03-08 at 12 00 52 PM" src="https://user-images.githubusercontent.com/26032343/54052707-f81d9200-4199-11e9-8b63-9ee37218fc56.png">

<img width="362" alt="Screen Shot 2019-03-08 at 11 56 23 AM" src="https://user-images.githubusercontent.com/26032343/54052579-9b21dc00-4199-11e9-8063-d55f8fc93b03.png">
<img width="371" alt="Screen Shot 2019-03-08 at 11 56 45 AM" src="https://user-images.githubusercontent.com/26032343/54052582-9ceb9f80-4199-11e9-92b4-853e3ddf35d5.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): HA

**Comment by sowmyav27** [comment]
While creating a DO node template, in a HA setup, `rancher:master`, error : `: Unable to authenticate you.` is seen on the UI.
This happens only with the first key in drop down when there are multiple cloud credentials to pick from for DO. When switched to some key and then back to 1st entry, we do not see it happen.
<img width="1439" alt="Screen Shot 2019-03-08 at 11 23 55 AM" src="https://user-images.githubusercontent.com/26032343/54059757-18a41700-41af-11e9-89e0-b747bbc52cf3.png">

**Comment by sowmyav27** [comment]
verified on `rancher:master`. Azure and VMware node templates are tagged to correct cloud credentials. 
<img width="381" alt="Screen Shot 2019-03-09 at 10 19 46 AM" src="https://user-images.githubusercontent.com/26032343/54075512-43e14180-4255-11e9-887a-46fe432f2f1a.png">
<img width="464" alt="Screen Shot 2019-03-09 at 10 19 55 AM" src="https://user-images.githubusercontent.com/26032343/54075514-45ab0500-4255-11e9-8624-51cf681227ae.png">
<img width="391" alt="Screen Shot 2019-03-09 at 10 20 21 AM" src="https://user-images.githubusercontent.com/26032343/54075516-4774c880-4255-11e9-9449-8b8d855771e1.png">
<img width="350" alt="Screen Shot 2019-03-09 at 10 20 29 AM" src="https://user-images.githubusercontent.com/26032343/54075518-48a5f580-4255-11e9-9c73-145da368b708.png">

**Comment by davidnuzik** [comment]
Reopening this issue; we have seen regression of the issue (BOTH issues mentioned in this issue -- the one in the issue description and also the one in Sowmya's comment here: https://github.com/rancher/rancher/issues/18737#issuecomment-471099293)

We have also created a separate blocker issue for v2.3 as we also see this in master-head: https://github.com/rancher/rancher/issues/22662

**Comment by davidnuzik** [comment]
Closing; we are going to create a separate backport issue
