### ISSUE TITLE
Make role selection more prominent when adding MCAPP.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18749]
Rancher server version - Build from master - Mar 8

Currently the roles option "Application Access Roles" is presented way below and is not expanded by default even though "project member" role gets assigned by default.

<img width="1108" alt="Screen Shot 2019-03-08 at 3 28 02 PM" src="https://user-images.githubusercontent.com/4266958/54062811-4f812980-41bd-11e9-8cb1-3a46a3dd306f.png">
 
With roles becoming mandatory for MCAPP deployments , Can we surface it more prominently in the UI , like may be right after “Upgrade Strategy” and make it expanded to make clear that "project member" role gets assigned by default.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/12/19) 68f13abc3245
Confirmed issue. This is now much more prominent and is always seen. It is right under the "Upgrade strategy" when deploying a MC app:
![image](https://user-images.githubusercontent.com/45179589/54216502-03790200-44a7-11e9-9bc7-121947918fe6.png)

Projects radio button is always picked by default; this make it clear that Project access is always granted by default.

Launched an app, confirmed that depending on what is picked the appropriate role is applied.
For example default project access:
```
roles: ["project-member"]
0: "project-member"
```

Also tested upgrades to ensure it works as expected as well. I upgraded and increased privileges to cluster-owner role. Smoke tested this area and did not identify any issues.
