### ISSUE TITLE
[CLI] [Feature] Support Helm

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#18742]
**What kind of request is this (question/bug/enhancement/feature request):** feature request

Obviously Rancher believes Helm charts are worth supporting since apps can be based on Rancher Catalog versions of Helm or Helm charts themselves.

I believe there would be a lot of benefit to support helm through the rancher cli like kubectl is.

If there could be help support through the Rancher CLI, I believe it could take advantage still of Rancher's JIT Tiller setup, thus allowing Rancher to maintain it's security posture.

The other big benefit would be local development of charts. Being able to reference a chart from a local directory for development and testing would be extremely beneficial without having to install tiller and helm.

**Comment by ekristen** [comment]
Can we get some traction on this? 

Installing catalogs are nice, but that means you have to have a full setup to publish them and its hard to use it for development whereas with Helm directly you can just reference a local helm chart and deploy it.

**Comment by SimonHeimberg** [comment]
I use the following work around.

Save this file as kubectl-helm (or create a symlink to helm) and place it somewhere in your PATH
```
#!/bin/sh
helm "$@"
```
now you can run `rancher kubectl helm yourHelmCommand`
