### ISSUE TITLE
Optimize Rancher cluster with large number of custom resources and jobs/pods

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#18741]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

We have a custom Kubernetes cluster managed by Rancher where we currently have 3,000 thousand of pods and custom resources and we expect these to continue growing.  We have already experienced issues with etcd becoming read-only because the default 2GBs quota is exceeded. Our short-term solution was to increase the quota to 4GBs. However, we believe a better/long-term solution should be possible by optimizing the cluster specifications, etcd defragmentation/optimization, etc.

Our cluster configuration is currently:
3 etcd/control plane servers with 8 cores and 64 GBs of RAM
36 worker nodes with varied specifications.

The etcd/control plane servers seem to be pretty idle at the moment, even when etcd is exceeding the quota.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.3
- Installation option (single install/HA):
HA

**Comment by dkeightley** [comment]
Closing in favour of https://github.com/rancher/docs/issues/1426
