### ISSUE TITLE
Add rancher/kube-api-auth:v0.1.1 to rancher-images.txt

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18755]
The image `rancher/kube-api-auth:v0.1.1` needs to be added to `rancher-images.txt` for the airgap HA installation.

**Comment by cjellick** [comment]
We probably need to retest air gap bc of this images and more importantly changes to the image list from  ARM

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher: v2.2.0-rc4 in Airgapped HA mode

The mentioned image is included in the rancher-images.txt file and the workload using this image gets deployed successfully.
