### ISSUE TITLE
two services on one host?

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#1875]
Hi there,
somehow I am not able to start two service utilizing the same host.
The first service starts just fine, but the second complains then that it didn't find a place to start the container. Did I miss something?

**Comment by deniseschannon** [comment]
Are you using port mapping on the host? If the services are using the same ports, then they cannot use the same host as there is only 1 available port on the host.

**Comment by fentas** [comment]
Dough. Stupid. I overlooked on port. Thanks a lot.
