### ISSUE TITLE
Release note how the "backup/restore" feature works on existing clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18754]
Rancher server version - Fresh install of rancher server version - v2.17  upgraded to 2.2 master builds.

Currently there is no straight forward way to enable the new "backup/restore" feature on existing cluster in upgraded setup. 
The only way this feature can be turned on is , for the  users to  edit the cluster and "Save" , the new backup/restore feature in the UI will be available (There is a message that is presented to the user).
If the users do not edit the cluster , they will continue to be using the legacy backups.

Questions:

1. Why can this feature not be turned on automatically on  existing clusters as part of rancher server uprgade ? Is it because we may not be able to do exact conversion of the settings ? ` retention": "72h"/"creation": "12h" ` in  2.1.7 to `"intervalHours": 12, "retention": 6` in 2.2.

2. If we are not able to turn on this feature automatically on  existing clusters as part of rancher server upgrade , Can the user be provided with an option at the cluster level which when selected would enable this feature( similar to what happens on the edit cluster currently).

We could continue to have current way of making an attempt to turn on this feature on edit cluster , if needed .

**Comment by alena1108** [comment]
> Why can this feature not be turned on automatically on existing clusters as part of rancher server upgrade ? Is it because we may not be able to do exact conversion of the settings ?

Yes, it is mostly because it is not easy to convert. Plus we usually try to avoid any auto updates for a cluster.

> If we are not able to turn on this feature automatically on existing clusters as part of rancher server upgrade , Can the user be provided with an option at the cluster level which when selected would enable this feature( similar to what happens on the edit cluster currently)

We do have a way to convert from an old snapshot setting to the new ones. @westlywright can you confirm

**Comment by westlywright** [comment]
@alena1108 I misunderstood when we talked offline, we do not offer a way at the cluster level to upgrade just this setting, the only time this setting is changed is when the user opt's into upgrading the cluster. I think what sangeetha is asking is that we showcase some kind of warning and possible action if the user is at the cluster level and just wants to change this particular cluster setting without editing. @sangeethah is that correct?

**Comment by cjellick** [comment]
we just need to document and put in the release notes

**Comment by cjellick** [comment]
closing. the act of releasing noting it is tracked separately
