### ISSUE TITLE
[UI] [FEATURE] Global clusters overview and aggregated Grafana

### ISSUE THREAD

**Issue by amioranza** [rancher/rancher#18758]
It is not a bug, it is a suggestion.

When looking at the version 2.2 cluster monitoring feature I figured out how to have a single panel with all cluster metrics, it is something that could be included on Global section and at Rancher server to get one page view of live metrics of all clusters, like the main view of the clusters but all clusters in one page, or with simpler graphs at the global cluster page.
![image](https://user-images.githubusercontent.com/30518346/54073274-f5876f00-4263-11e9-89e4-0507587f649c.png)

At the sketch the highlighted Grafana could be the aggregated grafana and pronmetheus that gathers information from all managed clusters, only for basic information, and puts it on one page status (grafana dashboard) for all clusters, and the global clusters page can contain the samenew live graphics of the main cluster page with the option to show/hide the graphics.

I don't if is something you have palnned for the new releases of Rancher, but it could be cool to have this ine page status view of all managed clusters.

Thanks.

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/21018
