### ISSUE TITLE
cluster driver nil error when removing cluster driver of provisioning cluster

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18761]
Version: Master 2.2 (3/9/19) 365fde6ba442
Closely related to issue #18460 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add a cluster driver via the UI (you can use the instructions [here](https://github.com/rancher/ui-cluster-driver-skel/tree/google-gke-example) to add the google gke example)
- Launch a cluster with the `example` cluster driver
- When the cluster is still in provisioning state you can delete the cluster driver. 

**Result:**
Unlike #18460 the UI is still usable. On the backend you will see in rancher server container logs:
`[WARNING] unable to find the kontainer driver (ID) that maps to <nil>`
You are able to delete this cluster still and Ui is still working, we just probably should not be able to delete the kontainer-driver while it's still being used for provisioning.

**Other details that may be helpful:**
There is a UI bug as well that might help to resolve this: #18762

**Comment by cjellick** [comment]
moving out. not a blocker
