### ISSUE TITLE
UI - Change field name for snapshot enable to be more descriptive.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18764]
Rancher server version - Build from master 

"snapshot enable" field name is currently "Enabled" .  Can it be changed to "Snapshot Enabled"?
<img width="892" alt="Screen Shot 2019-03-09 at 2 14 59 PM" src="https://user-images.githubusercontent.com/4266958/54078022-d8f43280-4275-11e9-99e3-37fd4da443db.png">

**Comment by westlywright** [comment]
In hopes of further clarification the label will now read `Recurring etcd Snapshot Enabled`. Additionally the input has been moved to below the target config settings since these settings apply to both recurring and one-time snapshots.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/11/19) 540d086476c9
Confirmed issue. The names have changed and been moved downwards below etcd snapshot config options. This makes it more clear these are recurring snapshots per Wes' comment.

![image](https://user-images.githubusercontent.com/45179589/54164391-a5eaa400-4419-11e9-8fdd-3d62c9002892.png)

Smoke tested this area to ensure still working correctly, etc.
