### ISSUE TITLE
ConfigMap removed on kubernetes version upgrade

### ISSUE THREAD

**Issue by mrigesh** [rancher/rancher#18767]
Kubernetes Old Version : v1.11.6
Kubernetes New Version : v1.13.4

Rancher Version: v2.1.7
Rancher Old Version: v2.1.5

After upgrade, ConfigMap for `nginx-ingress-controller` is empty.

**Comment by superseb** [comment]
Not really sure what configmap you are talking about exactly, but I guess it's `nginx-configuration` and that is covered in https://github.com/rancher/rancher/issues/21851. Let me know if that does not cover your issue.
