### ISSUE TITLE
[Question] Does Rancher Server Support HA?

### ISSUE THREAD

**Issue by gyliu513** [rancher/rancher#18772]
*Describe your issue here*

I was following documents at https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/#2-install-rancher to install Rancher, but there is no steps for how to set up a HA rancher server. 

So if the node which host the rancher server goes down, I will lose the capability of managing all of the clusters in Rancher.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc3` UI: `v2.2.4` |
|Route|`global-admin.clusters.new`|

**Comment by superseb** [comment]
See the note on top of the quickstart:

```
Quick Start Guides
Note:
The intent of these guides is to quickly launch a sandbox that you can use to evaluate Rancher. These guides are not intended for production environments. For comprehensive setup instructions, see Installation.
```

Which points to https://rancher.com/docs/rancher/v2.x/en/installation/
