### ISSUE TITLE
Is there any option to configure EKS cluster spot pricing ?

### ISSUE THREAD

**Issue by rohithsharmaks** [rancher/rancher#18777]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

I am using Rancher for bringing up EKS cluster and sometimes install k8s cluster on AmazonEC2 instances. AWS supports spot pricing. But from Rancher API specs, I didn't see any configs to enable spot pricing! 

Does Rancher support configuring spot pricing for either AWS services or k8s cluster installed on EC2 instances?

**Comment by aemneina** [comment]
@rohithsharmaks lets track this feature using this ticket: https://github.com/rancher/rancher/issues/22042
I'll close this out and we can move the discussion forward there.
