### ISSUE TITLE
Delete the pipeline workloads,  run the pipeline again will report "Jenkins pod not found".

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#18779]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):**

1. Enable and run the pipeline to make `docker-registry`, `jenkins`, `minio` running.
```
> kubectl get all -n p-cfwhk-pipeline
NAME                                   READY   STATUS    RESTARTS   AGE
pod/docker-registry-54ccc58f87-bg5px   1/1     Running   0          108s
pod/jenkins-6679b5595-7g9dc            1/1     Running   0          108s
pod/minio-7d9b5556f-zdg6w              1/1     Running   0          108s

NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)              AGE
service/docker-registry   ClusterIP   10.43.29.170   <none>        443/TCP              108s
service/jenkins           ClusterIP   10.43.20.145   <none>        8080/TCP,50000/TCP   108s
service/minio             ClusterIP   10.43.221.13   <none>        9000/TCP             108s

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/docker-registry   1/1     1            1           108s
deployment.apps/jenkins           1/1     1            1           108s
deployment.apps/minio             1/1     1            1           108s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/docker-registry-54ccc58f87   1         1         1       108s
replicaset.apps/jenkins-6679b5595            1         1         1       108s
replicaset.apps/minio-7d9b5556f              1         1         1       108s
>
```
2. Manually delete workloads: `docker-registry`, `jenkins`, `minio`.
```
> kubectl get all -n p-cfwhk-pipeline
NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)              AGE
service/docker-registry   ClusterIP   10.43.29.170   <none>        443/TCP              3m10s
service/jenkins           ClusterIP   10.43.20.145   <none>        8080/TCP,50000/TCP   3m10s
service/minio             ClusterIP   10.43.221.13   <none>        9000/TCP             3m10s
>
>
```
3. Run the pipeline again, or disable the pipeline and then re-enable it.

**Result:**
The pipeline cannot run. Report error:" `Jenkins pod not found`".
<img width="1343" alt="pipeline" src="https://user-images.githubusercontent.com/42061003/54115058-ba816900-4426-11e9-8ac6-adc23fc31a71.png">
When I delete the `namespace:p-cfwhk-pipeline` and re-run the pipeline, the workload(`docker-registry,` `jenkins`, `minio`) can be recreated. The pipeline runs successfully.

If the `jenkins pod` is deleted, you can create it again when running the pipeline. That would be great, I don't need to delete the namespace.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master
- Installation option (single install/HA): single

**Comment by gitlawr** [comment]
Jenkins works as a system resource and we don't expect users to delete it. We used to try creating any necessary resources when a build is triggered, but that involves extra API calls to the API server. 

To recover from this failure state users need to remove the pipeline dedicated namespace now.

I would consider it as a wont-fix issue, but let me know if it doesn't make sense.

**Comment by battmanux** [comment]
I get to the same issue. first jerkin install failed due to quota activated on the project. I removed quota and tryed to re run the cicd. then I get the "jerkins pod not found". I had to remove the namespace to fix it.
Thanks for the solution

**Comment by FinalVersion** [comment]
Same here as battmanux. It makes a new user desparate to dig around about why jenkins pod not found, even worse after troubleshooting how project quota not fit dedicated pipeline namespace. 
I think we can at least remind people to delete the namespace when this happen, or better clean up the broken namespace automatically.

**Comment by Jlaird** [comment]
In case anyone else runs across this issue. If you delete the namespace it will recreate it.
