### ISSUE TITLE
Any plan to migrate to cluster-api

### ISSUE THREAD

**Issue by gyliu513** [rancher/rancher#18771]
*Describe your issue here*
I found that the cloud provider in Rancher are still using cloud providers from k8s at https://github.com/kubernetes/kubernetes/tree/master/cluster , but this is now deprecated. Any plan to migrate to [cluster-api](https://github.com/kubernetes-sigs/cluster-api) for cloud providers?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc3` UI: `v2.2.4` |
|Route|`global-admin.clusters.new`|

**Comment by ShadowJonathan** [comment]
IMO the CAPI is more declarative and abstract enough to represent a wider range and richer support for getting clusters up and running, the `kontainer-engine` is very good, but if kubernetes is providing a solution on their own, there should be at least some support for it.

**Comment by vincent99** [comment]
The new/rke2 provisioning system in 2.6 uses CAPI.
