### ISSUE TITLE
Controller Manager and Scheduler stop working

### ISSUE THREAD

**Issue by RalicIvan** [rancher/rancher#18786]
We have the same problem for 2 weeks now and haven't managed to fixed it even after a few questions on stackoverflow and rancher forum.

Around 2 weeks ago we had a memory overflow by one of our PODs and after that Controller Manager and Scheduler are not working properly.

`kube-controller-manager` is impossible to restart using `docker restart` command on any node, so the only way we managed to keep it running was with restarting whole docker service with `systemctl restart docker.socket docker.service`. Firstly we tough that this fixed the problem but after a few days problem would return.

Today morning we moved all our servers to bare metal because rancher couldn't start working properly at all even after a few restarts, and we already had a few hour downtime..

Can someone please help me troubleshoot this issue. The last logs are below.

_kube-controller-manager_
```
E0311 09:08:57.135369       1 resource_quota_controller.go:430] failed to discover resources: Get https://127.0.0.1:6443/api?timeout=32s: context deadline exceeded
E0311 09:09:24.717936       1 cronjob_controller.go:109] can't list Jobs: the server was unable to return a response in the time allotted, but may still be processing the request (get jobs.batch)
E0311 09:09:24.718817       1 leaderelection.go:234] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: stream error: stream ID 1053; INTERNAL_ERROR
I0311 09:09:25.091210       1 leaderelection.go:213] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
F0311 09:09:25.091292       1 controllermanager.go:215] leaderelection lost
```

_kube-scheduler_
```
W0311 09:28:43.966555       1 authorization.go:47] Authorization is disabled
W0311 09:28:43.966572       1 authentication.go:55] Authentication is disabled
I0311 09:28:43.966581       1 insecure_serving.go:47] Serving healthz insecurely on [::]:10251
I0311 09:28:44.868193       1 controller_utils.go:1025] Waiting for caches to sync for scheduler controller
I0311 09:28:44.968341       1 controller_utils.go:1032] Caches are synced for scheduler controller
I0311 09:28:44.968373       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/kube-scheduler...
E0311 09:29:58.163852       1 leaderelection.go:234] error retrieving resource lock kube-system/kube-scheduler: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints kube-scheduler)
E0311 12:40:25.609957       1 leaderelection.go:234] error retrieving resource lock kube-system/kube-scheduler: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints kube-scheduler)
W0311 12:41:11.076778       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.ReplicationController ended with: too old resource version: 23893203 (23926774)
W0311 12:41:11.141484       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.StorageClass ended with: too old resource version: 23891982 (23926774)
W0311 12:41:11.141637       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1beta1.PodDisruptionBudget ended with: too old resource version: 23892078 (23926774)
W0311 12:41:11.163989       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.PersistentVolumeClaim ended with: too old resource version: 23893119 (23926774)
W0311 12:41:11.165037       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1beta1.StatefulSet ended with: too old resource version: 23896157 (23926774)
W0311 12:41:11.234610       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.Service ended with: too old resource version: 23893544 (23926774)
W0311 12:41:16.635942       1 reflector.go:341] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.PersistentVolume ended with: too old resource version: 23893119 (23926804)
E0311 12:43:09.194445       1 leaderelection.go:234] error retrieving resource lock kube-system/kube-scheduler: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints kube-scheduler)
I0311 12:43:31.677549       1 leaderelection.go:194] successfully acquired lease kube-system/kube-scheduler
E0311 12:48:20.622459       1 leaderelection.go:234] error retrieving resource lock kube-system/kube-scheduler: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints kube-scheduler)
E0311 12:53:06.372882       1 leaderelection.go:234] error retrieving resource lock kube-system/kube-scheduler: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints kube-scheduler)
W0311 12:53:43.954461      
```

_kubectl components status_
```
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
scheduler            Healthy     ok                                                                                     
etcd-2               Healthy     {"health": "true"}                                                                     
etcd-1               Healthy     {"health": "true"}                                                                     
etcd-0               Healthy     {"health": "true"} 
```

Infrastructure is HA, on 3 nodes with 4CPU and 8GB RAM each hosted on DigitalOcean, load balanced by DigitalOcean LB and it worked fine for at least 3 months without any errors and with a lot more of traffic.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |

**Comment by URSTYLE** [comment]
had the same issue multiple times at 2.1.2, the only way was to restart instance / docker service and we still don't know how to prevent these situations

**Comment by RalicIvan** [comment]
It is very irritating because for the last couple of months we've spent a lot of energy in dockerizing everything and developing CI/CD system with Rancher in mind. And now we have returned to a stone age with VMs again.
No matter everything we are still holding on these 3 VMs with compromised Rancher, it costs us money, and if anyone is willing to at least help me debug and troubleshoot everything I think this issue might be solved in the following releases.
Because with this kind of unpredictable behavior Rancher is useless....

**Comment by URSTYLE** [comment]
@RalicIvan did you try to run controller on an instance with more available memory? it's not a fix, but could provide a longer life for your stack 

There is also new issue related to this one #19038

**Comment by cjellick** [comment]
Is this the cluster that rancher server is deployed into or is it a cluster managed by Rancher?

Do the rancher logs say anything? You say you migrated to new machines and it resurfaced? How did you achieve that migration? Especially for etcd

What version of k8s are you running?

How is this cluster deployed and managed? RKE?

**Comment by RalicIvan** [comment]
@URSTYLE thank you for suggestion, we'll try it.

@cjellick First of all excuse me for my noobism if I do not understand something or make a mistake in communication and thank you very much for a reply!

The HA Rancher was deployed with RKE following [this tutorial](https://rancher.com/docs/rancher/v2.x/en/installation/ha/) so I think it is the cluster managed by rancher.

K8s versions are
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Currently Rancher logs say a lot, mainly those running say
```
ClusterController c-xc4wt [user-controllers-controller] failed with : failed to start user controllers for cluster ...
```
And those pods who are in "removing" state say
```
E0311 09:28:20.594708 7 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.ClusterRoleBinding: Get https://192.168.121.49:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
2019/03/11 09:28:20 [ERROR] Failed to connect to peer wss://10.42.1.144/v3/connect [local ID=10.42.0.127]: dial tcp 10.42.1.144:443: connect: network is unreachable
E0311 09:28:20.679494 7 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Namespace: Get https://192.168.121.49:6443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
2019/03/11 09:28:20 [ERROR] Failed to connect to peer wss://10.42.1.140/v3/connect [local ID=10.42.0.127]: dial tcp 10.42.1.140:443: connect: network is unreachable
E0311 09:28:20.748253 7 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.Role: Get https://192.168.121.49:6443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0311 09:28:20.961803 7 leaderelection.go:224] error retrieving resource lock kube-system/cattle-controllers: Get https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/cattle-controllers?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E0311 09:28:20.971273 7 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1.ClusterRole: Get https://192.168.121.49:6443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0311 09:28:20.962804 7 event.go:260] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil), BinaryData:map[string][]uint8(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'rancher-6dc68bb996-mvr5r stopped leading'
I0311 09:28:20.972496 7 leaderelection.go:203] failed to renew lease kube-system/cattle-controllers: timed out waiting for the condition
2019/03/11 09:28:20 [FATAL] leaderelection lost for cattle-controllers
```

![image](https://user-images.githubusercontent.com/9627557/54765605-1bb0f580-4bfa-11e9-9b78-802b671c9615.png)


Sorry for misunderstanding but we haven't migrated rancher on another servers, we just transferred whole our infrastructure on an old non-k8s architecture where HA is achieved with multiple VMs for every bigger service and a few VMs for microservices.

What we did and what kinda solved the problem in first place was only rebooting running Rancher VMs or restarting docker service on those nodes.

**Comment by cjellick** [comment]
Looks like you are having pretty major networking/communication issues. I don’t think rancher server has connectivity to the k8s cluster it is managing.

**Comment by cjellick** [comment]
@cloudnautique is 8GB ram enough for mgmt plane cluster?

**Comment by RalicIvan** [comment]
Thank you, I have been looking at related issue that URSTYLE has added, I will look into networking problems and get back with more information or a solution.

**Comment by RalicIvan** [comment]
Issue wasn't resolved and found the appropriate reproduction steps because of the nature of the problem (form reload to fail it took sometimes more than week, logs were not helpful). There was not an obvious networking nor RAM problem. Now the servers with an error are down so the reproduction of the same error probably won't be possible.

Thank you all for your help.

**Comment by cakiem8x** [comment]
Same issue when i add new node. kube-scheduler status running (real not run) but port 10251 not listen and log: 
E0729 08:15:56.424195       1 leaderelection.go:270] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I0729 08:16:22.034512       1 leaderelection.go:214] successfully acquired lease kube-system/kube-scheduler
I0729 08:20:55.265174       1 leaderelection.go:249] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
E0729 08:20:55.499156       1 server.go:261] lost master
lost lease
