### ISSUE TITLE
Cannot deploy cluster monitoring feature if the creator of cluster has been removed or deactivated

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#18787]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create second admin account
2. Login with second admin account
3. Deactivate default admin account
4. Enable cluster monitoring

**Result:**

This is the root cause of issue #18664, but I thought it warranted a specific bug report itself.

The charts will fail to deploy, with errors describe in this issue rancher/rancher#18664

**Other details that may be helpful:**

This is the root cause of issue #18664, but I thought it warranted a specific bug report itself.

The default user should be able to be deleted or deactivated and the system continue to function. There might be other areas that are affected too that I'm not familiar with.

I would expect that there would be a system user that's hidden that is used for system like interactions and not the default admin.

**Environment information**

 * Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-rc3
 * Installation option (single install/HA): HA

**Comment by cjellick** [comment]
To elaborate: if the user who created the cluster has been removed or deactivated, you will see this failure.

In the case of the "local" cluster, the creator is considered the default admin, which is why you would see this for the local cluster.

**Comment by jcambronero** [comment]
We encountered this bug as well. BTW, we noticed that besides the monitoring feature this also impacts the logging feature (and therefore it is very likely to also impact the alerting feature).

**Comment by jiaqiluo** [comment]
The big fix is validated on Rancher: master b4bdcfd

Steps:
- provision an RKE cluster
- Create second admin account
- Login with second admin account
- Deactivate default admin account
- Enable cluster monitoring

Result:
- the cluster monitoring is up successfully
