### ISSUE TITLE
10.43.0.1:443 no route to host

### ISSUE THREAD

**Issue by volatilemolotov** [rancher/rancher#18783]
What kind of request is this: BUG 

Steps to reproduce: Deploy fluentd daemonset which connects  to 10.43.0.1:443 (kubernetes service)

Result: No route to host - connect(2) for "10.43.0.1" port 443 (Errno::EHOSTUNREACH)

Other details that may be helpful: using RKE (deployed CUSTOM cluster from rancher)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): CUSTOM
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM Controlplane: 2vcpu/4GBmem Worker: 4vcpu/16GBmem
- Kubernetes version (use `kubectl version`): 

```
No route to host - connect(2) for "10.43.0.1" port 443 (Errno::EHOSTUNREACH)
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by loganhz** [comment]
This should be some KubeDNS/CoreDNS issue. Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by volatilemolotov** [comment]
Cannot reproduce anymore

**Comment by HectorB-2020** [comment]
@volatilemolotov, do you remember what you did so that the issue disappeared?
I've been looking into similar issue based on symptoms described by you.
* https://github.com/rancher/rke/issues/3288

So far I've played with SELinux, disabled it bu in vain.
I gain some success with preventing Networkmanager from touching CNI:
/etc/NetworkManager/conf.d/calico.conf
```ini
[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:vxlan-v6.calico;interface-name:wireguard.cali;interface-name:wg-v6.cali
```

/etc/NetworkManager/conf.d/flannel.conf
```ini
[keyfile]
unmanaged-devices=interface-name:flannel.1;interface-name:veth*;interface-name:cni0
```

**Comment by volatilemolotov** [comment]
Honestly cannot remember. 

Check if the pod that you are trying to reach DNS from does not have `hostNetwork: true` and if yes try adding `dnsPolicy: ClusterFirstWithHostNet`
