### ISSUE TITLE
When snapshot is disabled , We are not allowed to Restore from existing backups / take manual back ups.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18793]
Rancher server version - Build from master - Mar 9 - 2ae5225

Steps to reproduce the problem:
Create a DO cluster.
Snapshots are enabled by default.
Edit cluster and disable snapshot.

Currently when snapshot is disabled , we are NOT allowed to perform manual back up. "Backup Now"  option shown in UI for the cluster.  API UI for the cluster also shows "backupEtcd" action as greyed out .

We are NOT allowed to  restore from backups. "Restore From Backup" is not show for the cluster. API UI for the cluster also shows "restoreFromEtcdBackup" action as greyed out .

Expected behavior:
When snapshot is disabled,  we should still be allowed to take manual back ups and also be allowed to restore from existing backups.

**Comment by jira-sync-svc** [comment]
➤ Sowmya commented:

Verified the below scenarios on rancher/rancher:master and rancher/rancher:v2.2.3-rc1.

Steps Taken:

  1. Create a AWS cluster.
  2. Snapshots are enabled by default.
  3. Edit cluster and disable snapshot.

Manual backups can be taken. Snapshot option is enabled on the Rancher UI. backupEtcd option is enabled on the API level in rancher.

Restore from Snapshots is enabled on the UI and API level.

Manual snapshots can be taken, and restored from.
