### ISSUE TITLE
Dark Theme UI: Improve contrast of "Global" on Global Menu by making BG darker

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18792]
Version: Master 2.2 (3/11/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable the dark theme
- Open the Global Menu

**Result:**
Notice the text to background contrast is poor. Recommend making the bg behind the text darker so you can more easily read "Global" when the dark theme is enabled.
![image](https://user-images.githubusercontent.com/45179589/54143124-69518500-43e6-11e9-8507-f3da52a5280c.png)

**Other details that may be helpful:**
I thought in CSS this might be inherited from `body.no-touch.ember-application.theme-ui-dark`
BG color `#bcc3c7` but I don't think this is quite right. The color is (RGB 144,153,160) which should be closer to #9099a0 but my colors could be off on my display.

**NOTICE:**
You might not be able to reproduce this unless you are somewhere besides the main global (cluster view) page. Try going into a cluster and clicking on a project. Now you should see the gray background as pictured.

If you are on the main cluster view page (/g/clusters) you may see the global background is a blue color. We would like this blue color to be everywhere ideally or just fix the background so is darker when we are not on this page per the issue result information.
From /g/clusters page:
![image](https://user-images.githubusercontent.com/45179589/54146024-5772e080-43ec-11e9-8940-0e38df5684eb.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/12/19) 68f13abc3245
This isn't quite right, there is a box around global now that is off color to a BG behind it or something:
![image](https://user-images.githubusercontent.com/45179589/54217373-bb5adf00-44a8-11e9-9ff3-5d90cf90cfe6.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/2749

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/12/19) a183dc4359c4
The contrast is still very poor when on dark theme. I cleared cache and hard reloaded UI.

At /g/clusters (cluster listing page):
![image](https://user-images.githubusercontent.com/45179589/54233163-99258900-44c9-11e9-9517-e4b927293ef7.png)
^This is good

At projects/workload/other areas:
![image](https://user-images.githubusercontent.com/45179589/54233134-8a3ed680-44c9-11e9-9356-d61c1eda65cf.png)
^This is not good. I can't really read "Global"

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/13/19)
On light theme background is now too light when on global:
![image](https://user-images.githubusercontent.com/45179589/54294970-68982a80-456f-11e9-9b1d-270f5d4ff6fb.png)

It seems good on dark theme just not on light.

**Comment by davidnuzik** [comment]
It looks like there is also an issue when hover over projects on light theme:
![image](https://user-images.githubusercontent.com/45179589/54296778-bd897000-4572-11e9-9656-c9646559f554.png)

and dark theme:
![image](https://user-images.githubusercontent.com/45179589/54296799-c67a4180-4572-11e9-9c68-d25c709f0e85.png)

**Comment by davidnuzik** [comment]
@lvuch Per our conversation re-opening.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/14/19) HA Setup

Confirmed issue resolved. The Global text is now readable whether on dark or light theme. I ensured the other issues are resolved as well (see comments above). I smoke tested the global menu and did not identify any issues.
![image](https://user-images.githubusercontent.com/45179589/54387359-6d84d900-4658-11e9-8954-444dd6bdcd34.png)
