### ISSUE TITLE
Error - streamwatcher/round_trippers - CancelRequest Not Implemented / Client.Timeout

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#18797]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Unsure.

**Result:**

Seeing the following logs. 

```
E0311 19:21:27.136991       8 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0311 19:21:27.137019       8 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0311 19:21:27.137428       8 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0311 19:21:27.143791       8 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-rc3
- Installation option (single install/HA): HA

**Comment by ts-mini** [comment]
I'm seeing a similar error on 2.2.1

I am experiencing 'socket leaking' (tcp alloc sockets) on a control plane node originating from whichever host is running the `cattle-cluster-agent` pod.  The sockets are being kept alive from the cattle-cluster-agent and I'm wondering if this log line is an indication that whatever initiated the request attempted to cancel it, and it never did thus leaving a hanging connection.
