### ISSUE TITLE
UI: example kontainer driver cluster does not show up when deactivate and then activate

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18794]
Version: Master 2.2 (3/11/19) HA Setup

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add the custom example [kontainer driver](https://github.com/rancher-plugins/kontainer-engine-driver-example/releases) with the [UI skeleton](https://github.com/rancher/ui-cluster-driver-skel/tree/google-gke-example)
- Once it is fully ready you will see it is active in the API /v3/kontainerdrivers
```
actions": {
"deactivate": "…/v3/kontainerDrivers/kd-bf89m?action=deactivate"
},
"active": true,
"actualUrl": "https://github.com/rancher-plugins/kontainer-engine-driver-example/releases/download/v0.2.3/kontainer-engine-driver-example-linux-amd64",
```
- In the UI click on Add cluster and you will see it listed
![image](https://user-images.githubusercontent.com/45179589/54146749-e8968700-43ed-11e9-8b08-1b0f8d8371bd.png)
- Now, deactivate the example cluster driver
- It is now not active in the /v3/kontainerdrivers API
`active: false,`
- Now, in the UI activate the example cluster driver
- It is now active again in the /v3/kontainerdrivers API
`active: true`
- Now, add a cluster again. Refresh the UI. It's not listed even though the example driver is active:
![image](https://user-images.githubusercontent.com/45179589/54146939-488d2d80-43ee-11e9-81b8-c5ace6531940.png)

**Result:**
UI is not showing the "Example" cluster driver when we try to add a cluster when we deactivate the driver, wait a moment, then activate again.

**Other details that may be helpful:**
I made sure to be fair and not quickly deactivate and then activate again. I waited a moment between each action and tried refreshing the UI a few times and logging out and back in again. It still does not show up in the UI.

There are no errors in the browser console.

**Environment information**
Version: Master 2.2 (3/11/19) HA Setup (latest master chart used via local chart)

**Comment by westlywright** [comment]
@davidnuzik I have attempted to reproduce this numerous times without luck. I'm not sure this would be a UI issue if I could reproduce it. The ui loads all the drivers and filters those on the active state. Additionally we check to make sure that the schema exists in the api, in this case `exampleEngineConfig`, if it can't load that schema we won't display that choice because bad things would. From your repro it sounds like this may have been what happened for you. If you can reproduce it reliably can you check to see if that schema exists? If the schema doesn't exist this is an API issue. If it does there may be a UI bug (I don't see anything currently that would cause this). I am going to remove myself and the UI label since I don't think this is a UI issue.

**Comment by davidnuzik** [comment]
@westlywright Yes I'll investigate further per your comments. I have reproduced numerous times on latest master I will look into exampleEngineConfig.

**Comment by davidnuzik** [comment]
@westlywright I have reproduced several times. Maybe there is something unique/environmental about my set up? (HA setup?) I don't see how this would affect anything but it's possible. I can show you the issue on my set up when you are free. When I test exampleEngineConfig schema still exists each time. You must refresh your browser to see the Example cluster go away from the Add Cluster page.

**Comment by davidnuzik** [comment]
Perhaps this still might? be an api issue. `exampleEngineConfig` stays there but I don't see an update to conditions for the kontainerDriver. When I make it active again it is `active: true` but under conditions lastUPdateTime for "Active" type does not change. I still see latest is "Inactive"

**Comment by davidnuzik** [comment]
I noticed that exampleEngineConfig is NOT listed on /v3/schemas but I can still see it when I refresh `v3/schemas/exampleEngineConfig` @westlywright so this is an API issue probably then? If its listed at `v3/schemas/exampleEngineConfig` is irrelevant if it is NOT listed on `/v3/schemas` ?

**Comment by davidnuzik** [comment]
Closing issue based on discussion with Wes. The fact that exampleEngineConfig is not listed on `/v3/schemas` is an API bug. Yes we can GET `/v3/schemas/exampleEngineConfig` but the issue of this not being listed on `/v3/schemas` is an API issue. I have opened a separate issue to address this problem here: #18800
