### ISSUE TITLE
Warning - Norman Generic Controller - too old resource version

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#18796]
**What kind of request is this (question/bug/enhancement/feature request):** question/bug

**Steps to reproduce (least amount of steps as possible):**

Unsure, when I was reviewing the logs, I noticed warnings in the logs.

Everything seems to be operating properly. 

Since I'm running an RC release I wanted to bring this up, if it's a non-issue sorry for the noise.

**Result:**

```
W0311 19:24:13.175595       8 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38539750 (38541167)
W0311 19:33:10.202441       8 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38542191 (38543019)
W0311 19:39:24.192770       8 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38543496 (38544305)
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-rc3
- Installation option (single install/HA): HA

**Comment by doog33k** [comment]
I have the exact same issue by using the Helm install with the latest repo

**Comment by ekristen** [comment]
My installs seem to be fine for what it's worth, but seeing it in the logs.

**Comment by cdbyrd** [comment]
Same issue here in v2.2.1 using helm HA install on an existing EKS cluster.  Doesn't seem to cause an issue, but would be interested to understand what the message about.

**Comment by Amos-85** [comment]
same issue for me 
rancher 2.1.8

**Comment by Hitesh-Agrawal** [comment]
Same issue for me using rancher 2.2.2
Helm server and client version: v2.12.1
K8 Cluster version on which rancher workload is running : v1.12.4
rancher image -> rancher/rancher:v2.2.2
Docker Version (both server and client) : 17.03.2-ce
Node : CentOS Linux release 7.6.1810 (Core) 
Node Kernel : 4.4.166-1.el7.elrepo.x86_64


```
5/8/2019 9:35:02 AM W0508 04:05:02.515261       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Event ended with: The resourceVersion for the provided watch is too old.
5/8/2019 9:37:16 AM W0508 04:07:16.500816       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 39116010 (39117317)
5/8/2019 9:46:15 AM W0508 04:16:15.497057       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 39118162 (39118759)
5/8/2019 9:46:42 AM W0508 04:16:42.568884       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Event ended with: The resourceVersion for the provided watch is too old.
```

**Comment by khauser** [comment]
moved away for me with 2.2.3.rc6 but not with 2.2.4.rc5

**Comment by risayew** [comment]
The same for version 2.2.3

E0607 12:16:10.369139 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:11 PM E0607 12:16:11.356334 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:11 PM E0607 12:16:11.357769 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:11 PM E0607 12:16:11.359145 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:11 PM E0607 12:16:11.362858 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:11 PM E0607 12:16:11.363387 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:11 PM E0607 12:16:11.369751 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:12 PM E0607 12:16:12.356792 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:12 PM E0607 12:16:12.358781 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:12 PM E0607 12:16:12.359883 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:12 PM E0607 12:16:12.364132 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:12 PM E0607 12:16:12.364956 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:12 PM E0607 12:16:12.370450 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:13 PM E0607 12:16:13.357551 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:13 PM E0607 12:16:13.359949 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:13 PM E0607 12:16:13.360740 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:13 PM E0607 12:16:13.368078 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:13 PM E0607 12:16:13.368454 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:13 PM E0607 12:16:13.371008 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:14 PM E0607 12:16:14.358257 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:14 PM E0607 12:16:14.363691 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:14 PM E0607 12:16:14.364699 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:14 PM E0607 12:16:14.368621 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:14 PM E0607 12:16:14.370098 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:14 PM E0607 12:16:14.371898 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:15 PM E0607 12:16:15.359075 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:15 PM E0607 12:16:15.364890 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:15 PM E0607 12:16:15.365759 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:15 PM E0607 12:16:15.369091 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:15 PM E0607 12:16:15.370858 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:15 PM E0607 12:16:15.372792 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:16 PM E0607 12:16:16.359723 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:16 PM E0607 12:16:16.367444 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:16 PM E0607 12:16:16.368159 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:16 PM E0607 12:16:16.369521 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:16 PM E0607 12:16:16.371231 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:16 PM E0607 12:16:16.373295 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:17 PM E0607 12:16:17.360553 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:17 PM E0607 12:16:17.375701 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:17 PM E0607 12:16:17.375811 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:17 PM E0607 12:16:17.375890 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:17 PM E0607 12:16:17.375958 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:17 PM E0607 12:16:17.376082 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:18 PM E0607 12:16:18.367141 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:18 PM E0607 12:16:18.376099 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:18 PM E0607 12:16:18.377762 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:18 PM E0607 12:16:18.379114 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:18 PM E0607 12:16:18.380072 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:18 PM E0607 12:16:18.380987 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:19 PM E0607 12:16:19.367855 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:19 PM E0607 12:16:19.376488 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.0.32.1:443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:19 PM E0607 12:16:19.378269 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:19 PM E0607 12:16:19.379481 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.0.32.1:443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:19 PM E0607 12:16:19.380591 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
6/7/2019 2:16:19 PM E0607 12:16:19.381782 6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.0.32.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect``

**Comment by xayangjing** [comment]
This warning messaage is also found with rancher 2.2.4
W0802 02:16:19.231181 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38267390 (38268666)
W0802 02:35:10.247101 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38271517 (38271854)
W0802 02:58:18.265469 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38274838 (38275890)
W0802 03:19:25.282396 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38278930 (38279688)
W0802 03:37:09.292458 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38282622 (38282796)
W0802 04:00:33.300521 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38285695 (38286834)
W0802 04:23:54.324377 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38289747 (38290798)
W0802 04:40:47.342906 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38293616 (38293647)
W0802 05:04:55.355835 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38296570 (38297877)
W0802 05:22:32.378530 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38300858 (38301016)
W0802 05:47:57.395363 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38303948 (38305514)
W0802 06:05:36.412221 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38308409 (38308558)
W0802 06:24:43.431106 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38311398 (38311803)
W0802 06:44:52.442793 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38314670 (38315238)
W0802 07:03:40.460875 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38318158 (38318515)
W0802 07:24:55.483584 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38321532 (38322307)
W0802 07:47:24.507525 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38325327 (38326316)
W0802 08:09:15.531270 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38329325 (38330202)
W0802 08:30:55.554052 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38333274 (38334121)
W0802 08:52:00.577489 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38337143 (38337892)
W0802 09:13:10.602206 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38340908 (38341675)
W0802 09:31:05.618634 1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 38344694 (38344895)
time="2019-08-02T09:41:05Z" level=error msg="Failed to connect to proxy" error="websocket: close 1006 unexpected EOF"

**Comment by surco1971** [comment]
Still there in 2.3.5 and it fills up the docker disc (33 GB)

W0310 14:45:29.865132       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 49625633 (49625925)
W0310 14:49:20.873764       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 73001323 (73001638)
W0310 14:50:29.488386       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 61285433 (61286402)
W0310 14:52:13.188812       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 82950193 (82950279)
W0310 15:01:37.535659       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 28231005 (28232533)
W0310 15:03:58.885020       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 49629188 (49629536)
W0310 15:04:05.215865       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 82952492 (82953408)
W0310 15:08:23.508479       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 61289579 (61289796)
W0310 15:10:05.888157       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 73005066 (73005991)
W0310 15:18:52.556673       6 reflector.go:299] github.com/rancher/norman/controller/generic_controller.go:193: watch of *v1.Endpoints ended with: too old resource version: 28235709 (28235799)

**Comment by jgreat** [comment]
I'm running into this problem too. Lots of log noise. 

```
E0730 15:37:35.683681       1 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.StatefulSet: Timeout: Too large resource version: 10471696, current: 10471475
```

Agents on K3s version v1.18.4+k3s1

Rancher | v2.4.5
-- | --
User Interface | v2.4.28
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher43
