### ISSUE TITLE
Cancel upgrade of original service during rolling upgrade (triggered before container in new service got deployed successfully) deletes all the containers in original service

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1879]
Executed rolling upgrade with wrong image name in docker-compose.yml. Noticed that service link is getting created, old service is stuck in UPGRADING status and new service is stuck in UPDATING-ACTIVE status for ever. 

Now, I deleted the new service that was stuck in UPDATING-ACTIVE. All the containers in OLD service got deleted, new service got removed and scale of old service became 0. Essentially, original service is not available anymore. Basically, if user is able to do cancel upgrade, scale of that service should not be made 0.

scale of original service : 3

I was able to reproduce this even with scale : 2

<img width="1368" alt="screen shot 2015-08-26 at 9 36 14 am" src="https://cloud.githubusercontent.com/assets/7720752/9499717/eb6f9598-4bd5-11e5-9b14-59c9df731666.png">

<img width="1368" alt="screen shot 2015-08-26 at 9 43 20 am" src="https://cloud.githubusercontent.com/assets/7720752/9499874/e789acd8-4bd6-11e5-9529-4cdc31d1ca0c.png">

**Comment by joshwget** [comment]
Once Rancher Compose calls the `serviceUpgrade` API, it does nothing further and the rest of the actions taken (like deleting the new service) are done via the UI. I think the problem is actually in how Cattle detects an upgrade is complete.

@alena1108 does this seem like an issue in Cattle to you?
