### ISSUE TITLE
UI: change "Container Default Limit" label to a "Container Default Resource Limit"

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18808]
As the latter is more descriptive.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/12/19) 68f13abc3245
Confirmed issue.
This has now been renamed to "Container Default Resource Limit"

From Add Namespace page:
![image](https://user-images.githubusercontent.com/45179589/54216236-864d8d00-44a6-11e9-81c9-1f2b7efbcc9e.png)

Also checked from Add Project page.
