### ISSUE TITLE
Rotating certificates causes worker node to become unavailable / kubelet not restarted

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#18805]
rancher/rancher:master-aef0332a 3/11
HA install
k8s 1.13.4 on clusters (did not check other versions)

Rotating certificates on a cluster causes the worker node to become unavailable with message `Kubelet stopped posting node status`.

Kubelet log shows:
```
E0311 21:48:11.879498   21676 reflector.go:134] object-"kube-system"/"kube-dns-token-5zn9c": Failed to list *v1.Secret: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/secrets?fieldSelector=metadata.name%3Dkube-dns-token-5zn9c&limit=500&resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-ca")
```

Certificates did get rotated; certs between controlplane/worker are the same.
```
ubuntu@brandon-ec22-w1:/etc/kubernetes/ssl$ sudo md5sum kube-ca.pem
4e27938dd968fc7f7af914c97c855af8  kube-ca.pem

ubuntu@brandon-ec22-c1:/etc/kubernetes/ssl$ sudo md5sum kube-ca.pem
4e27938dd968fc7f7af914c97c855af8  kube-ca.pem```
```

`docker ps` shows that `kubelet` on worker node did not get restarted after cert rotation.

Manually stopping/starting the `kubelet` container allows the node to become active. Cert is still the same as on controlplane/etcd.

This was last seen working 3/8/19 when creating a new cluster and rotating certs was successful.

To reproduce:
* Create RKE cluster
* Rotate all certificates
* ETCD/Controlplane become active

Actual:
* Worker node becomes unavailable. 

Expected:
* Worker node becomes available

**Comment by alena1108** [comment]
@bmdepesa Can you elaborate on the option you've chosen for the cert rotation:

`Rotate the CA and all Service certificates` 
or
`Rotate all Service certificates (keep the same CA)`

**Comment by bmdepesa** [comment]
@alena1108 I chose `Rotate the CA and all Service certificates`

**Comment by alena1108** [comment]
After talking to @galal-hussein, there are 2 issues:

1) Kubelet restart doesn't happen when cert is changed for the worker node on k8s 1.13. 
2) Node agent restart doesn't happen when CA cert gets changed. 

We should definitely address 1) for 2.2 as worker node certificates have 1 year expiration prior to 2.2. @galal-hussein is looking into it.

Number 2) can be punted post 2.2 as CA cert expiration is 10 years. We can address it in 2.2.1

cc @cjellick

**Comment by alena1108** [comment]
Update: for CA cert rotation node agent restart wasn't needed. But there were some other fixes done to support `Rotate the CA and all Service certificates`:

* kube-api-auth container restart on CA change
* user cluster kubeconfig regeneration 

To fully validate the issue, we have to make sure cluster is accessible from embedded kubectl after cert rotation is finished.

**Comment by sangeethah** [comment]
@bmdepesa Validate this issue on a cluster with 1 control node , 3 etcd nodes and 3 worker nodes.
Also validate this on a custom cluster as well as a EC2 node provider cluster.

**Comment by bmdepesa** [comment]
rancher/rancher:master 3/14

* Created ec2 cluster with 1 control node, 3 etcd, and 3 workers. 
* Rotated certs - successfully changed
* Worker node restart successfully
* kubeconfig regeneration was successful
* Embedded kubectl is functional
* Remote kubectl is functional


* Created custom cluster with 1 control node, 1 etcd, and 1 worker. 
* Rotated certs - successfully changed
* Worker node restart successfully
* kubeconfig regeneration was successful
* Embedded kubectl is functional
* Remote kubectl is functional
