### ISSUE TITLE
Manual backup snapshots should not get deleted on account on retention count and recurring snapshot creation time should not get altered based on manual backup taken.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18807]
Manual backup snapshots should not get deleted on account on retention count.
Recurring snapshot creation time should not get altered based on manual backup taken.

┆Attachments: <a href="https://rancher.atlassian.net/secure/attachment/10201/Screen+Shot+2019-04-24+at+5.52.54+PM.png">Screen Shot 2019-04-24 at 5.52.54 PM.png</a>

**Comment by jira-sync-svc** [comment]
➤ Sowmya commented:

validated on rancher:v2.2.3-rc1

Created a cluster AWS - 1 etcd, 1 worker, 1 control plane.

Edit on cluster to change -

Recurring etcd Snapshot Creation Period - 1 hour

Recurring etcd Snapshot Retention Count - 3

Observations:

Manual snapshots are getting deleted on the etcd node, when the recurring snapshots are enabled.

Error - Failed to start backup server on all etcd nodes: \[Failed to run backup server container, container logs: time="2019-04-25T02:17:06Z" level=fatal msg="stat /backup/c-kwtlr-ml-lkj99: no such file or directory" ] is seen when you try to restore from the missing snapshot.

snapshots on the etcd node:

!Screen Shot 2019-04-24 at 5.52.54 PM.png|width=906,height=534!

**Comment by jira-sync-svc** [comment]
➤ Sowmya commented:

This issue is fixed in{{ rancher:master}}.

**Comment by alena1108** [comment]
Can be tested on `v2.2.3-rc3`

**Comment by sowmyav27** [comment]
verified on `v2.2.3-rc3`
**Steps taken:**

1. Created a cluster AWS - 1 etcd, 1 worker, 1 control plane.
2. Edit on cluster to change -
     Recurring etcd Snapshot Creation Period - 1 hour
     Recurring etcd Snapshot Retention Count - 2

**Observation:**
Manual snapshots do not get deleted.
2 Recurring snapshots are available and upon creation of a new one, older recurring snapshot is deleted.
