### ISSUE TITLE
Websocket origin is not allowed behind apache reverse proxy

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#18816]
I'm trying rancher 2 and my setup contains apache reverse ssl proxy. 
I can log in, but wss connection gives me 403 in a browser and next lines in container log:

    019/03/12 04:05:38 [ERROR] Error during subscribe websocket: origin not allowed
    2019/03/12 04:05:38 [ERROR] Unknown error: websocket: origin not allowed

My startup command:

     docker run -d --restart=unless-stopped -v /opt/rancher:/var/lib/rancher 
     \ -p 127.0.0.1:8880:80 -p 127.0.0.1:8843:443 --name rancher rancher/rancher:stable

Apache config:

    <IfModule mod_ssl.c>
    <VirtualHost *:443>
        ServerName rancher.DOMAIN.XXX
        ServerAdmin admin@DOMAIN.XXX
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        ProxyRequests Off

        SSLProxyEngine on
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off

        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>

        RewriteEngine On
        RewriteCond %{HTTP:Connection} Upgrade [NC]
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteRule /(.*) wss://127.0.0.1:8843/$1 [P,L]
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set X-Forwarded-Port "443"

        ProxyPass / https://127.0.0.1:8843/
        ProxyPassReverse / https://127.0.0.1:8843/

        <Location />
                Order allow,deny
                Allow from all
        </Location>

        SSLCertificateFile /etc/letsencrypt/live/rancher.DOMAIN.XXX/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/rancher.DOMAIN.XXX/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
     </VirtualHost>
    </IfModule>

I can successfully login via https://rancher.DOMAIN.XXX but websocket connection from browser fails.

P.S.: Apache enabled modues:

    access_compat alias auth_basic authn_core authn_file authz_core authz_host authz_user autoindex 
    deflate dir env filter headers mime mpm_event negotiation proxy proxy_http proxy_wstunnel 
    reqtimeout rewrite setenvif socache_shmcb ssl status

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.7` UI: `v2.1.21`  Docker-ce: `18.09.3`, Ubuntu: `18.04`|

**Comment by clicman** [comment]
My fault. Fixed by adding `ProxyPreserveHost On` to virtualhost.

**Comment by jewelbdx** [comment]
> My fault. Fixed by adding `ProxyPreserveHost On` to virtualhost.

yes, exactly! It's also solved my issue! Thank you! 💯
