### ISSUE TITLE
Deprecated labels - io.rancher.{project,project_service}.name

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1881]
Server version - Build from master Aug 26

Deploy a service with scale 3.

From within one of the containers of the service get metadata for container:
curl --header 'Accept: application/json' 'http://rancher-metadata/latest/self/container

io.rancher.project.name and io.rancher.stack.name point to same value.
io.rancher.project_service.name and io.rancher.stack_service.name point to same value.

In addition we also have stack_name and service_name fields.

<img width="671" alt="screen shot 2015-08-26 at 10 41 19 am" src="https://cloud.githubusercontent.com/assets/4266958/9501447/3d2aeca2-4be0-11e5-83d2-eeb90d009971.png">

**Comment by alena1108** [comment]
For redundant data in labels, please file a separate bug. Metadata just displays all the labels set on the container.

**Comment by alena1108** [comment]
Actually lets just keep it in this bug, I'm just gonna change the title.

**Comment by vincent99** [comment]
They're not redundant, they're the older names of the labels.  If we get rid of them older service affinity rules that refer to the old labels will no longer work.

**Comment by alena1108** [comment]
@vincent99 closing it then for now?

**Comment by vincent99** [comment]
We can probably mark these as deprecated in the docs (if they're even mentioned) and drop them for the GA release.
