### ISSUE TITLE
EKS cluster nodes are being removed abruptly

### ISSUE THREAD

**Issue by rohithsharmaks** [rancher/rancher#18819]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Provision EKS cluster with all default settings provided by Rancher. EKS cluster is provisioned successfully and able to view all details
- Wait for 15 to 20 mins. EKS cluster nodes disappears

**Result:**
Expected EKS cluster to work properly until cluster is deleted by user.

**Other details that may be helpful:**
Logs : The below error seen rancher logs. 
```
2019/03/12 05:05:45 [INFO] Deleted cluster node [machine-65jtl]
2019/03/12 05:05:45 [ERROR] NodeController c-plbf4/machine-65jtl [user-node-remove] failed with : failed to remove finalizer on c-plbf4:machine-65jtl
2019/03/12 05:05:50 [INFO] Updating workload [kube-system/aws-node] with public endpoints [[{"nodeName":"c-plbf4:machine-x5v78","addresses":["192.168.157.62"],"port":61678,"protocol":"TCP","podName":"kube-system:aws-node-vtggm","allNodes":false},{"nodeName":"c-plbf4:machine-4998g","addresses":["192.168.67.47"],"port":61678,"protocol":"TCP","podName":"kube-system:aws-node-k5nqk","allNodes":false},{"nodeName":"c-plbf4:machine-8h2qr","addresses":["192.168.117.3"],"port":61678,"protocol":"TCP","podName":"kube-system:aws-node-lgrdr","allNodes":false},{"nodeName":"c-plbf4:machine-flbnt","addresses":["192.168.232.72"],"port":61678,"protocol":"TCP","podName":"kube-system:aws-node-nmt2r","allNodes":false}]]

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:latest used to start rancher. 

- Installation option (single install/HA):
Single Install

**Comment by rohithsharmaks** [comment]
I found that our company has script to kill instances if instance tag is not defined with "Owner" tag.
Now I got question that how to pass vm instance tags from rancher? The label which provides rancher doesn't delegate to VM instances. Only displayName is tagged in VM instances.

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/16356 as the filed issue is not a Rancher issue and the follow up is covered in https://github.com/rancher/rancher/issues/16356
