### ISSUE TITLE
Rancher 1.6.27 + Rancher-NFS

### ISSUE THREAD

**Issue by Fail-Unsafe** [rancher/rancher#18829]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**

1. Change Host Registration URL
2. Re-Add Hosts to the environment with the updated docker command copy&pasted

**Result:**
Hosts receive the new Registration URL but Rancher-NFS still uses the old URL

**Other details that may be helpful:**
```(Container should have been running but is in stopped state. Check logs for more information.: Failed to create volume phpipam_db_e8f4a. Driver: rancher-nfs. Status code: 500. Status: 500 internal server error. Error Message: Get http://blah-is-blubb.mydomain.com:8080/v2-beta/volumes?name=phpipam_db_e8f4a&removed_null=true&storageDriverId=1sd1: dial tcp 10.13.2.136:8080: getsockopt: connection refused)```

The new Host Registration URL is https://blah-is-blubb.mydomain.com

**Environment information**
- Rancher version: 1.6.27
- Installation option: non-HA

- Docker version (use `docker version`):

```
Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
Do I have to re-deploy Rancher-NFS from the catalog _and_ delete all volumes before that?

**Comment by StrongMonkey** [comment]
@Fail-Unsafe can you post your rancher-nfs logs and rancher-agent logs?

**Comment by StrongMonkey** [comment]
@Fail-Unsafe can you restart your storage driver to see if it picks up the latest environment variable? don't have to delete volumes.

**Comment by Fail-Unsafe** [comment]
> @Fail-Unsafe can you restart your storage driver to see if it picks up the latest environment variable? don't have to delete volumes.

I restarted the nfs-driver storage service and entered a shell in the container but `export` still shows the old `CATTLE_URL` and `CATTLE_CONFIG_URL`.

`declare -x CATTLE_CONFIG_URL="http://host-is-097.domain.com:8080/v1"`
`declare -x CATTLE_URL="http://host-is-097.domain.com:8080/v1"`

The Rancher server is behind an NGINX reverse proxy. I had hoped to fully hide the Rancher container behind the reverse proxy but because of the NFS problem, I had to expose port 8080 on the container because otherweise the containers running on the Rancher hosts lose their connection to the storage.

I can't share logs because I would have to delete to port mapping and then nothing works.

**Comment by StrongMonkey** [comment]
@Fail-Unsafe Also can you try deleting the container and let it recreate? It might pick up the latest URL since the environment variable is attached when the container is created.

**Comment by Fail-Unsafe** [comment]
No, that doesn't work.

`Error deleting
Driver from service is in use by volumes (1v637,1v638,1v644,1v2380,1v2503,1v2554,1v2651)`

**Comment by Fail-Unsafe** [comment]
Small Update:

After upgrading the docker version from 18.09.2 -> 18.09.4, therefore restarting all containers I now have one out of two NFS containers that has the correct URL. The other container still has the old URL.

A bit strange.

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
