### ISSUE TITLE
Rancher cluster memory metrics mismatch grafana cluster metrics on v2.2.0-rc3

### ISSUE THREAD

**Issue by riaan53** [rancher/rancher#18827]
**What kind of request is this (question/bug/enhancement/feature request):**
Possible bug

**Steps to reproduce (least amount of steps as possible):**
1. Create kubernetes cluster via RKE on Rancher OS
2. Install Rancher v2.2.0-rc3 in HA mode via helm
3. Enable monitoring and leave for a while

**Result:**
![Screenshot 2019-03-12 at 15 20 49](https://user-images.githubusercontent.com/7716342/54203233-7f407200-44da-11e9-8823-2f1cc9a83062.png)
![Screenshot 2019-03-12 at 15 21 04](https://user-images.githubusercontent.com/7716342/54203237-810a3580-44da-11e9-8504-bc3bcb54d2b4.png)
![Screenshot 2019-03-12 at 15 21 47](https://user-images.githubusercontent.com/7716342/54203257-92ebd880-44da-11e9-97ce-3dd9349b3be8.png)
![Screenshot 2019-03-12 at 15 22 25](https://user-images.githubusercontent.com/7716342/54203286-a9922f80-44da-11e9-8af2-53730dcf6186.png)

**Environment information**
v2.2.0-rc3 in HA mode on Rancher OS 1.5.1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
RKE created single node
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Virtual Box, 2 CPU, 4 Gb ram
- Kubernetes version (use `kubectl version`):
v1.13.4

- Docker version (use `docker version`):
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by rdu** [comment]
I have exactly the same issue on rancher v2.2.3. 
I am using single install with AWS cloud provider. 
RancherOS:
version v1.5.1 from os image rancher/os:v1.5.1
(ami-04c6caa71c063e2a2)

The Issue only occours on the grafana cluster dashboard. When switching to the node dashboard all values a reasonable.
