### ISSUE TITLE
windows rancher-agent stucks on 'Starting plan monitor'

### ISSUE THREAD

**Issue by yusufmendes** [rancher/rancher#18824]
**What kind of request is this (question/bug/enhancement/feature request):**
  Bug

**Steps to reproduce (least amount of steps as possible):**
  Run rancher server
  Create custom cluster 
  Add custom linux(ubuntu) node as etc/worker/contolplane
  Wait for provisioning
  Cluster will be created successfully with one etc/worker/contolplane node
  Edit cluster and add Windows Node using flannel network provider
  Copy rancher agent command and execute it in the Windows Server 2016 1803 machine

  
  

**Result:**
Rancher windows agent  powershell command result
*********************************************************
C:\>PowerShell -Sta -NoLogo -NonInteractive -Command "& {docker run --rm -v C:/:C:/host rancher/rancher-agent:v2.1.6-nanoserver-1803 -server https://192.168.10.41 -token fzvfptmmst57fnzbpc42ksd5s46n54x2qxzvljxl9mxljb8mjnj6vm -caChecksum 6616465a44630020c2ba3b33458168258f5f1ff2583a084790451382040a09a4; if($?){& c:/etc/rancher/run.ps1;}}"
INFO[117364] Starting kubelet ....
INFO[117368] ...................., generating flanneld config
INFO[117369] ...................., generating cni config
INFO[117370] .....................
INFO[117386] .................. OK
INFO[117387] Starting flanneld ...
INFO[117390] .....................
INFO[117402] .....................
INFO[117409] ...................., checking HNS network
INFO[117410] .....................
INFO[117419] .................. OK
INFO[117420] Starting kube-proxy .
INFO[117421] ...................., wait a few seconds
INFO[117427] .....................
INFO[117437] .................. OK
INFO[117438] Starting plan monitor

Below is the output of Windows docker ps -a command;
************************************************************

C:\Shared\rancher2.1.7>docker ps -a
CONTAINER ID        IMAGE                                        COMMAND                   CREATED             STATUS                          PORTS                    NAMES
fd5a030a7287        rancher/nginx-proxy:v0.0.1-nanoserver-1803   "pwsh.exe -f 'c:\\Pro…"   About an hour ago   Up About an hour (healthy)      0.0.0.0:6443->6443/tcp   nginx-proxy
9673a0c99730        rancher/hyperkube:v1.11.6-nanoserver-1803    "pwsh.exe -f 'c:\\Pro…"   About an hour ago   Exited (0) About a minute ago                            kubernetes-binaries
84cf1403b40a        rancher/flannel-cni:v0.0.1-nanoserver-1803   "pwsh.exe -f 'c:\\Pro…"   About an hour ago   Exited (0) About a minute ago                            cni-binaries

nginx-proxy is up but rancher/hyperkube:v1.11.6-nanoserver and ancher/flannel-cni:v0.0.1-nanoserver-1803 exited.When I type docker logs 9673a0c99730 or   84cf1403b40a ,it returns nothing

kubelet,flanneld and kube-proxy seems okey but agent process is waiting for 'starting plan monitor' statement,
Rancher UI states that 2 nodes successfully registered.I can deploy sample app on windows node using rancher ui.When I type ipconfig I show cbr0  network interface created by flanneld process.
No log file created under C:\var\log\rancher directory.
As a result except for 'starting plan monitor'  and exited  rancher/flannel-cni,rancher/hyperkube ,Everthing seems okey
I wonder If These problems may cause something else more important 
 
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher Version
 *v2.1.6 
Single node install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
  Custom cluster
  VM
```

- Docker version (use `docker version`):
```
 Windows Server 2016 1803
 *****************************
 Docker version 18.09.2, build 142dfcedca 
```

**Comment by pseckd** [comment]
Same on 2.2-rc3 and Windows Server 2019 1809

**Comment by yusufmendes** [comment]
After restarting windows node machine,RancherUI now gives following error;
 Kubelet stops posting node status..
I cannot make progress on adding windows node to kubernetes cluster using rancher for one week.
Any help would be appreciated

**Comment by loganhz** [comment]
@thxCode Can you verify if windows 1803 support is still working in latest rc version?

**Comment by loganhz** [comment]
@yusufmendes @pseckd Now rancher only supports Windows 1803 + K8s 1.11.

Windows 1809 and k8s 1.11 + support is coming soon

**Comment by yusufmendes** [comment]
@loganhz My environment is  already Windows 1803 + K8s 1.11.6 but it didnt worked .It stucks on  INFO[117438] Starting plan monitor and kubelet agent/flannel-cni container exited without any log
Rancher version v.2.1.6 and selected k8s version is 1.11.6

**Comment by yusufmendes** [comment]
@loganhz  @thxCode  Now I used rancher v2.1.2 instead of v2.1.6 ,but the result didnt changed.Still stucks on  'starting plan monitor'.I downloaded source code of hyperkube.ps1 and it doesnt  contains any log starting with 'Starting plan monitor' but has Starting kubelet..,Starting flanneld and Starting kube-proxy

**Comment by pseckd** [comment]
@loganhz @thxCode i try it with 1803 today. The windows agent isn't available as rc3, there is only a rc2 image on dockerhub

**Comment by yusufmendes** [comment]
@loganhz  @thxCode  You say  Now rancher only supports Windows 1803 + K8s 1.11. 
This means 1.11.* ? or higher than 1.11 (1.12,1.13 is valid ?)

Windows 1803 +v2.2.0-rc2(k8s 1.13.4) gives following error on windows node

var/log/rancher/kubelet.log
*****************************
F0313 10:49:35.501269    4272 server.go:147] unknown flag: --cadvisor-port

Kubernetes removed --cadvisor-port in 1.12.4 but you are already using this parameter and it causes kubelet to fail.

As a result If you successfully bootstrap windows+linux (hybrid) kubernetes in any rancher and  kubernetes version(rc or stable),then please expose your environment.I m blocked and waiting for your help :(

**Comment by thxCode** [comment]
@yusufmendes , in fact, printing`Starting plan monitor` is matching our design. If you are facing the kubelet cannot report the node status, here we get another similar issue: https://github.com/rancher/rancher/issues/16074. FYI, we have filed an enhancement issue https://github.com/rancher/rancher/issues/16460 to record what we doing now.

**Comment by thxCode** [comment]
@pseckd , sorry, I am not sure why we don't have a windows agent image for 2.2-RC3. cc @cloudnautique

**Comment by yusufmendes** [comment]
@thxCode Thanks my issue is similar with #16074. So This the reason why following containers immediately exited ? 
**9673a0c99730 rancher/hyperkube:v1.11.6-nanoserver-1803 "pwsh.exe -f 'c:\Pro…" About an hour ago Exited (0) About a minute ago kubernetes-binaries
84cf1403b40a rancher/flannel-cni:v0.0.1-nanoserver-1803 "pwsh.exe -f 'c:\Pro…" About an hour ago Exited (0) About a minute ago cni-binaries**
but only nginx-proxy container is up 
  **fd5a030a7287 rancher/nginx-proxy:v0.0.1-nanoserver-1803 "pwsh.exe -f 'c:\Pro…" About an hour ago Up About an hour (healthy) 0.0.0.0:6443->6443/tcp nginx-proxy
 container**

**Comment by thxCode** [comment]
Both `flannedl-cni` and `hyperkube` are just using for unpackaging the executable binaries into a host, and then `rancher-agent` will take over them. @yusufmendes

**Comment by kingsd041** [comment]
#### Test environment:
Kubernetes version: 1.14.1
Windows version: 1809
Rancher version: rancher/rancher:master(05/08 commit id: e1e6fc93)

Has been fixed, windows nodes can be successfully added to the cluster.
```
> k get nodes
NAME              STATUS   ROLES                      AGE   VERSION
ec2amaz-jejjm6i   Ready    worker                     15m   v1.14.1
ip-172-31-1-205   Ready    controlplane,etcd,worker   49m   v1.14.1

> k version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
