### ISSUE TITLE
Rancher fails after update from 2.1.5 to 2.1.7 in single-node

### ISSUE THREAD

**Issue by Upgreydd** [rancher/rancher#18828]
This cluster is currently Provisioning.
Exit status 1, unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-6bbbj/api?timeout=32s: remote error: tls: internal error unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-6bbbj/api?timeout=32s: remote error: tls: internal error unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-6bbbj/api?timeout=32s: remote error: tls: internal error unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-6bbbj/api?timeout=32s: remote error: tls: internal error unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-6bbbj/api?timeout=32s: remote error: tls: internal error unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-6bbbj/api?timeout=32s: remote error: tls: internal error unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-6bbbj/api?timeout=32s: remote error: tls: internal error

rancher is running at port 8443:
docker run -d --volumes-from rancher-data --restart=unless-stopped --name rancher -p 8443:443 -v /srv/rancher:/var/lib/rancher rancher/rancher:latest --acme-domain my.domain.tld:8443

**Comment by talisto** [comment]
I'm experiencing the same issue attempting to upgrade from 2.1.6 to 2.1.7 on docker desktop for mac.

**Comment by totogo** [comment]
I'm facing similar issue after upgrade from 2.1.6 to 2.1.7, but the apps in the cluster is still running, just rancher cannot communicate with the kubernetes cluster: 

This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Exit status 1, unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request

**Comment by CollinChaffin** [comment]
First experience with Rancher coming from others and after dealing with totally unclear wording on the setup, and the shortest help topics in the docs I've seen in a long time, a simple single-node setup and it doesn't work and flat out crashes with errors on multiple systems/attempts.

Is there any workaround or is a single-node installation simply not possible?  For those needing to lab/test, the single-node option is absolutely critical for a quick spin-up so hopefully it's not going away.

**Comment by ASwingler** [comment]
New install of 2.1.7 does this too. I'm also hoping for a workaround. Using Digital Ocean API.

**Comment by jesusmariagarcia** [comment]
I think I am hit by this also

**Comment by gjongenelen** [comment]
I hit this issue yesterday and read on the [forum](https://forums.rancher.com/t/v2-1-6-upgrade-to-v2-2-1-failed-unable-to-recognize-management-statefile-path-redacted/13790) that someone fixed it by adding a node to the cluster. This triggers something (I guess) which recovers the cluster. Worked for me.

**Comment by nagaland88** [comment]
Adding more nodes doesn't seem to fix the problem.
We are affected by this issue and currently cannot communicate with the cluster.

**Comment by modemhead** [comment]
ive experiencing the same after upgrading 2.2.8 to 2.3.2 , anyone found a solution? thanks!

**Comment by such** [comment]
I'm experiencing the same thing after upgrading from 2.4.3 to 2.4.4. I can't find anything helpful on the topic... I've tried adding a node but it did not fix anything... Any idea that might help?
