### ISSUE TITLE
How to do resizing of EKS cluster nodes?

### ISSUE THREAD

**Issue by rohithsharmaks** [rancher/rancher#18820]
**What kind of request is this (question/bug/enhancement/feature request):**
Question. If no support for this, then it is much required feature 

**Steps to reproduce (least amount of steps as possible):**
- Install EKS cluster with 2 nodes.
- Try to edit cluster, UI doesn't allow to resize the cluster for worker nodes. 

**Result:**
Expected to resize the nodes

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.6
- Installation option (single install/HA):
Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud
- Kubernetes version (use `kubectl version`):
```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by rohithsharmaks** [comment]
Folks, can anyone suggest me on this please?

**Comment by walkafwalka** [comment]
AFAIK, you have to manually go into CloudFormation and edit the ASG.
