### ISSUE TITLE
How to Get Token And ca-checksum Parameter Of Adding  k8s Cluster Node

### ISSUE THREAD

**Issue by liyongxian** [rancher/rancher#18823]
**What kind of request is this (question/bug/enhancement/feature request):**
After running rancher/rancher,I want to get parameter of **--token** and **--ca-checksum** by API Or Shell,Not by Rancher Web.How can I do? Thanks.

**Steps to reproduce (least amount of steps as possible):**
1、docker run -d  --restart=unless-stopped --name rancher  rancher/rancher:v2.1.1
2、Want to  add k8s cluster By CUSTOM ,Need to get --token and --ca-checksum by API Or Shell,But not by Rancher Web.
--token  and --ca-checksum  in cmd :  
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.1 --server https://xxx.xxx.xxx.xxx **--token** sjc8t7npc7ptr9zlqkw4z4bd6b7nm7wmm2khkl5m4jdj7fbdg86xgh **--ca-checksum** 9a8bbfa935491fdf82e3098909ccb8cdc410ca91d9274b2a5187131d339c3c83 --worker

**Result:**
I can not get --token and --ca-checksum by API Or Shell,But not by Rancher Web.

**Other details that may be helpful:**
Rancher version:
rancher/rancher:v2.1.1

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Docker version (use `docker version`):
Server Version: 17.03.2-ce

```
(paste the output here)
```

**Comment by superseb** [comment]
Automation examples are in https://github.com/rancher/quickstart, API fields can be checked using the API UI browser at `$RANCHER_URL/v3`, in this case `$RANCHER_URL/v3/clusterregistrationtokens`. Currently the checksum is computed and not a separate field, see https://github.com/rancher/rancher/issues/17273
