### ISSUE TITLE
How to find CAfile accessing URL Of Rancher Server By Https

### ISSUE THREAD

**Issue by liyongxian** [rancher/rancher#18825]
After runing rancher,I want to get parameter of --token and --ca-checksum by API By Curl,but curl needs CAfile.How can I find the CAfile of rancher.

**What kind of request is this (question/bug/enhancement/feature request):**
I can not find where Rancher' CAfile is.

**Steps to reproduce (least amount of steps as possible):**

**Result:**

Other details that may be helpful:
Rancher version:
rancher/rancher:v2.1.1

Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Docker version (use docker version):
Server Version: 17.03.2-ce
Thanks.

**Comment by superseb** [comment]
Please read https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions and use the forums for questions.

You can see how the agent uses the CA certificate here https://github.com/rancher/rancher/blob/master/package/run.sh#L226
