### ISSUE TITLE
Error seen while trying to restore from backup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18838]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a DO cluster on Rancher. (1 etcd/1 control plane/1 worker nodes)
2. Default, first backup (Backup#1) will be taken.
3. Scale upto 3 etcd nodes.
4. Take a backup. (Backup#2)
5. Edit cluster and change the `Recurring etcd Snapshot Creation Period` to 1 hour. Click on Save. 
6. After the cluster has finished updating, restore from back - to the first backup taken.(Backup#1)

**Expected Result:**
Cluster is restored to the first backup successfully.

**Actual Result:**
Error `Host must be a URL or a host:port pair: "https://"` is seen on the UI and in the Rancher logs.

**Note:** If Step 5 from above set of steps, was not performed, the restore works fine. 

<img width="1284" alt="Screen Shot 2019-03-12 at 10 23 11 AM" src="https://user-images.githubusercontent.com/26032343/54222234-3d033a80-44b2-11e9-8616-801a382ca035.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO cluster.
- Kubernetes version (use `kubectl version`):

```
v1.13.4
```

- Docker version (use `docker version`):

```
18.9.3
```

**Comment by soumyalj** [comment]
See the same restore issue, with the following steps:

```
Create a cluster with local backup
Create few backups B1, B2
Edit and change to S3
Perform a backup and ensure it goes to S3
Perform a restore to B1.
```

Restore fails with the below error:
```
2019/03/12 17:57:04 [ERROR] ClusterController c-tbt9r [cluster-provisioner-controller] failed with : host must be a URL or a host:port pair: "https://"
W0312 17:57:13.656423       8 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.ClusterAlertGroup ended with: too old resource version: 733732 (739974)

```

**Comment by cloudnautique** [comment]
I have seen this when loading Rancher with lots of clusters.

**Comment by moelsayed** [comment]
@soumyalj Current workflow when handling mixed providers:
- If the cluster is configured with s3 configuration, and you try to restore a local backup: this is now handled automatically
- if the cluster is configured with local configuration, and you try to restore an s3 backup: this is not currently possible and you get a message saying:  `"failed to prepare backup: restoring S3 backups with no cluster level S3 configuration is not supported"`

**Comment by soumyalj** [comment]
Tested with master build from March 14th.

Create a cluster with local backup config
Create few backups B1, B2
Edit and change to S3 backup config
Perform a backup and ensure it goes to S3
Perform a restore to B1.

Restore succeeded with no issues. Cluster was functional.

**Comment by sowmyav27** [comment]
Verified on `rancher:master`. 
**Steps taken:**

1. Create a EC2 cluster on Rancher. (1 etcd/1 control plane/1 worker nodes)
2. Default, first backup (Backup#1) will be taken.
3. Scale upto 3 etcd nodes.
4. Take a backup. (Backup#2)
5. Edit cluster and change the Recurring etcd Snapshot Creation Period to 1 hour. Click on Save.
6. After the cluster has finished updating, restore from back - to the first backup taken.(Backup#1)
No error is seen on the UI/Logs.
