### ISSUE TITLE
Monitoring - kube-state exporter print too many error log

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#18830]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- Enable Cluster Monitoring

**Result:**
- kube-state exporter keeps printing error logs

**Other details that may be helpful:**
![image](https://user-images.githubusercontent.com/3394724/54208457-ee3bbc00-4516-11e9-8a96-f5d992ce2672.png)

Cannot list `poddisruptionbudgets.policy`, it seems kube-state exporter doesn't have the `list` and `watch` permission on `poddisruptionbudgets.policy` resource.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom

**Comment by jiaqiluo** [comment]
Observe the same issue on v2.2.0

**Comment by loganhz** [comment]
The log shows in `kube-state exporter` pod. There is no harmful. So I think it's not a blocker issue. If we want to fix it, we need to release a new version of monitoring chart

**Comment by junkiebev** [comment]
I upgraded to v2.2.2 and then enabled monitoring - I had previously enabled and then disabled it when it did not work - and I'm seeing the following error in the `exporter-kube-state-cluster-monitoring` workload

`E0417 02:18:42.366969 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope`

**Comment by loganhz** [comment]
@junkiebev Do you mean your monitoring doesn't work now?

**Comment by junkiebev** [comment]
> @junkiebev Do you mean your monitoring doesn't work now?

that workload was blowing up and creating a new configmap every few minutes.

**Comment by loganhz** [comment]
This error will not cause the exporter-kube-state-cluster-monitoring pod failed.
The configmap issue will be fixed in https://github.com/rancher/rancher/pull/19079

Can you look at the logs and events for the pod?

**Comment by junkiebev** [comment]
The issue may be related to workers re-starting plan monitors due to websocket timeouts. You want the logs for the `exporter-kube-state-cluster-monitoring` pod, right?

**Comment by junkiebev** [comment]
@loganhz  - It looks like the cluster monitoring catalog item has a PR in which would fix this error:

https://github.com/rancher/system-charts/pull/27

**Comment by loganhz** [comment]
Chart PR merged

Waiting for https://github.com/rancher/rancher/pull/19766 https://github.com/rancher/types/pull/801 https://github.com/rancher/system-charts/pull/37 merged and https://github.com/rancher/rancher/pull/19766 https://github.com/rancher/types/pull/801 backport to 2.2. branch.

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master beffccd

Step:
- add an ec2 cluster
- enable cluster monitoring
- check the log of the workload `exporter-kube-state-cluster-monitoring` under proejct `System` and the namespace `cattle-prometheus`

Result:
- the error messages showed in the original issue are gone

<img width="1494" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57734892-e48a1e00-7657-11e9-87e6-cb6569e3b81c.png">
