### ISSUE TITLE
Backport: elasticsearch plain text password in logs

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18835]
Backport https://github.com/rancher/rancher/issues/18407

**Comment by alena1108** [comment]
Can be tested in v2.1.9-rc1

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.9-rc1

* Reproduced in v2.1.3
  * Setup ElasticSearch with basic auth
  * Saw plaintext password in fluentd logs
* Deploy rancher v2.1.9-rc1
* Setup ElasticSearch with basic auth
  * Password was not present in logs
