### ISSUE TITLE
execute Shell not working

### ISSUE THREAD

**Issue by fedeostrit** [rancher/rancher#18840]
hello,
I have installed rancher v2.2-rc2 in my cluster of kubernetes v1.13 with F5 big IP as layer7 load balance, everything works fine except the Shell console from Rancher UI and the kubectl console, with the version of Rancher 2.1.6 this was working, I do not know what logs I can pass to be able to investigate a bit about this or if it could be a bug of this version since with the other one it was working

**Comment by fedeostrit** [comment]
this is the error message that I see when I run "kubectl logs -n cattle-system -l app=cattle-agent" in my nodes

time="2019-03-11T21:14:26Z" level=error msg="Failed to connect to proxy" error="websocket: close 1006 unexpected EOF"

**Comment by fedeostrit** [comment]
![image](https://user-images.githubusercontent.com/48490228/54224179-c24d1600-44d7-11e9-9b53-c109d0cf6e4d.png)

**Comment by superseb** [comment]
This is a known issue in rc2, see https://github.com/rancher/rancher/issues/17028
