### ISSUE TITLE
dns-field being added to config in spec on update

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#18845]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. provision RKE cluster (DO) with default options
2. edit cluster and save, without making any changes.

**Result:**
Cluster goes to updating.

**Other details that may be helpful:**
This is happening because of a comparison preformed in getSpec. There is a difference between old config (taken from applied spec) and new config (taken from spec). One difference I found was that dns was going from an empty value to kube-dns.
old config DNS in debugger:
![image](https://user-images.githubusercontent.com/19376037/54230831-7b095a00-44c4-11e9-80d4-e85cc470ea99.png)

new config DNS value:
![image](https://user-images.githubusercontent.com/19376037/54230853-89577600-44c4-11e9-83c2-64c83809aabf.png)
![image](https://user-images.githubusercontent.com/19376037/54230965-cb80b780-44c4-11e9-9d6c-d79672621783.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Observed on master 3/12

**Comment by cjellick** [comment]
note: the cluster doesnt jsut go to updating, it goes through provisioning again

**Comment by alena1108** [comment]
Happens because older clusters don't have a DNS field set. And as the field exists in 2.2 cluster schema, it gets included to the PUT request with its default values. The fix is - make the field nullable by converting it to a pointer, and default to a struct on RKE side if nill value is passed.

**Comment by cjellick** [comment]
@alena1108 this did not occur with an "old" cluster created pre upgrade. was just a newly provisioned one

**Comment by alena1108** [comment]
@cjellick I'll try the upgrade usecase to see what the difference is.

**Comment by cjellick** [comment]
@alena1108 I just tested your fix with the non-upgrade case. steps:
1. on master, provision rke cluster
2. wait until active
3. edit, change nothing, save

it worked. cluster did not go back through provisioning

**Comment by alena1108** [comment]
@cjellick I've tested the fix too, but only for non-upgrade use case. So I want to:

* Understand why the original issue happens for clusters freshly provisioned on 2.2, but not for the upgraded ones.
* Test the fix for the upgrade use case

**Comment by cjellick** [comment]
oh, i think you misunderstood me because I worded it poorley. when i said

> @alena1108 this did not occur with an "old" cluster created pre upgrade. was just a newly provisioned one

i meant that we did not even test or try the upgrade path. We just saw the bug on master, never did an upgrade test.

I just wanted to make sure that you know it occurred for freshly provisioned clsuter

**Comment by alena1108** [comment]
@cjellick 
> I just wanted to make sure that you know it occurred for freshly provisioned cluster 

ok, that's the scenario I've used to reproduce the bug and verify the fix, so we should be good.

**Comment by sangeethah** [comment]
Tested with latest build from master -  85962565  (Mar13)

Steps to reproduce (least amount of steps as possible):

1.Provision RKE cluster (DO) with default options
2.Edit cluster and save, without making any changes.
Cluster does not got to "updating" state anymore.
