### ISSUE TITLE
Failed inspect causes container event spamming

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1884]
Seen by one of our users.

If docker errors out when inspecting a container, this can cause rancher to spam container events and eventually fill up the database.

Steps to reproduce (abridged):
1. Create new docker host and reconfigure it to use device mapper.
2. Launch a container on that host
3. On host, delete /var/lib/docker/devicemapper/metadata/<container id>* files
4. Restart docker daemon.
5. Launch rancher-agent on the host.

Once the host is registered, it will try to sync that broken container and it will never succeed and create a new entry in container_event table every 5 seconds.

**Comment by cjellick** [comment]
Note that at this point, the container will likely get stuck in a stopping state. @ibuildthecloud and I determined this was acceptable for now. We may address that separately, this fix was solely to stop the event spamming.

**Comment by aruneli** [comment]
Rancher 	v0.35.0-rc4
Cattle 	v0.86.0
User Interface 	v0.45.0

Verified that container_event is not getting spammed.
mysql> select * from container_event;
