### ISSUE TITLE
Warnings for local cluster on upgrade

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#18843]
On upgrade the local cluster will cause warnings in the logs due to not having a driver in the config.

**Comment by dramich** [comment]
This is seen when upgrading from 2.1.7 to master prior to this fix. The logs seen are `Failed to find driver and schema on upgrade`. The error comes from the local cluster, no other clusters are required to see the logs.

**Comment by soumyalj** [comment]
Tested on upgrade from v2.1.7 to master on a HA setup and single node setup. The logs 
`Failed to find driver and schema on upgrade` were not present in the logs.
