### ISSUE TITLE
UI: Navbar changes

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18847]
Version: Master 2.2 (3/12/19) a183dc4359c4

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, Usability

**Requested Changes:**
It's currently a bit confusing for the user with our current method of organizing MC apps, catalog apps, and other nav bar items. We'd like to change somethings:

_At Global Level:_
MOVE Multi-Cluster Apps to "Apps" item on nav bar
MOVE Catalogs and Drivers into Tools menu (So now Tools menu is Catalogs, Drivers, Global DNS Providers, Global DNS Entries)

_At Cluster Level:_
MOVE Catalogs into Tools menu

_At Project Level:_
CHANGE Catalog Apps to "Apps"
ADD Catalogs to Tools menu (Manage Catalogs)

**Result:**
This should make things a bit more clear for the user to understand.
This keeps things consistent across all levels.

**Other details that may be helpful:**
I do not think we need to make any changes to page Titles / Headers in the UI. I think we can probably do all this stuff by just changing en-us translations and some other finagling.

**Things to note:**
We need to not break functionality of GDNS entries hiding when not an HA setup.
We need to not break any "shortcut buttons" such as "Manage Catalogs" button on the (currently) "Catalog Apps" page at project level.

**Comment by cjellick** [comment]
Will see if @ankur111 wants to review the change

**Comment by ankur111** [comment]
Can you explain what the user flow will be. Here is what I think will happen
User - Operator/Admin
Flow 1- Tools --> Catalog --> Add Catalog
Flow 2 -Cluster --> Apps --> Multi Cluster --> Launch

User - Developer, DevOps practitioner
Flow 1 - Cluster --> Apps --> Catalog Apps --> Launch

Instead, how about putting "Resources" at all levels and pushing Catalogs as one of the Resource menu entry? 

What is the definition of "Apps"? Will a user deployed workload also be an "App"?

**Comment by vincent99** [comment]
"Apps" are a deployed instance of a helm chart/catalog template.

There is no "Apps -> Multi Cluster" or "Apps -> Catalog Apps", that is one "Apps" item in the nav with one page which lists the deployed (multi or single, depending on where you are) apps.

We're just trying to reorganize a bit so that apps and multicluster apps look the same in the nav and you don't end up with dropdowns with only one choice in them (which is what triggered talking about this).

**Comment by davidnuzik** [comment]
I have some input from the team who wants to make these changes:

>1.  The current menu has been expanded for 2.2 so we should make sure the new menu items makes sense
>2.  The menu for 2.2 doesn’t have consistency for our users.  The same page is found in different ways on different levels (like manage catalog)
>3.  Current 2.2 menu changes with HA enable or not.  It makes some of the drop-downs look silly with single items.
![image](https://user-images.githubusercontent.com/45179589/54242779-15789600-44e3-11e9-8aab-0eb30adf3440.png)


And here is my attempt to explain user flow:
User - Operator/Admin
Flow 1- (Global) Tools Menu --> Catalog --> Add Catalog
Flow 2 -(Global) Tools Menu --> Apps --> Launch Multi-Cluster App

User - Developer, DevOps practitioner
Flow 1 - (Project) Tools Menu --> Apps* --> Launch
* Still has "Manage Catalogs" shortcut button to easiyl set up catalogs here too if needed.
![image](https://user-images.githubusercontent.com/45179589/54243041-1eb63280-44e4-11e9-80b9-3fa0fa4d9aab.png)

^ Does this make sense? If at cluster level you only see Catalogs listed there so you should only be using that as a secondary way of doing first Flow 1. You can do it from global or cluster level today and we want to keep that just move to Tools menu.

I agree there is a bit of ambiguity with Resources vs. Tools but perhaps we should still keep them separate.

> What is the definition of "Apps"? Will a user deployed workload also be an "App"?
This is a good question, but I think no. A user-deployed workload is their own pod/set of pods/containers. An app is strictly a catalog application deployed via Rancher UI and should remain separate in my opinion.

If there is any confusion contact me and perhaps we can just set up a quick Zoom meeting with you, me, Tani, Vincent, and Wes as well if he wishes to join.

**Comment by jonnylocke** [comment]
Hi

Regarding the usability of the navigation menu, I'd like to make the following suggestion...

At the moment the menu is like a 3 in 1 function depending on whether you are at a global level, cluster or within the cluster. This could be made clearer by applying css changes to provide a different colour menu depending on what level you are at. Perhaps each cluster could be auto assigned a different colour or shade of colour?

A further enhancement could be to allow the user to set the colours as they see fit.

**Comment by davidnuzik** [comment]
@jonnylocke I think it's an idea worth considering in the future. Would you mind creating a new issue of kind/enhancement (label)? We might make an epic later around UI changes / possible redesign.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/14/19) 6875782b6131 (Single node)
Version: Master 2.2 (3/14/19 (3 node HA Setup, so we can see GDNS entries under global Tools menu)
BOTH single and HA setup were validated for each below. I made sure we didn't break anything per my concerns in the issue description. Ensure links to Catalogs are correct for each level, etc.

I tested all the requested changes:

At Global Level:
MOVE Multi-Cluster Apps to "Apps" item on nav bar
MOVE Catalogs and Drivers into Tools menu (So now Tools menu is Catalogs, Drivers, Global DNS Providers, Global DNS Entries)

_Single node rancher:_
![image](https://user-images.githubusercontent.com/45179589/54381526-42e05380-464b-11e9-9e05-df41436f48b8.png)

_Multi-node HA rancher:_
![image](https://user-images.githubusercontent.com/45179589/54381552-51c70600-464b-11e9-8e25-fbfb55bf8b17.png)



At Cluster Level:
MOVE Catalogs into Tools menu

_Single/HA rancher (Same):_
![image](https://user-images.githubusercontent.com/45179589/54381594-6905f380-464b-11e9-8216-bc37e023ed7e.png)



At Project Level:
CHANGE Catalog Apps to "Apps"
ADD Catalogs to Tools menu (Manage Catalogs)

_Single/HA rancher (Same):_
![image](https://user-images.githubusercontent.com/45179589/54381630-7ae79680-464b-11e9-8621-0fce66639fbd.png)


I tested each area by smoke testing (at all levels ensure each page we moved/renamed works as expected, UI look/feel is good, ensure any "shortcut" buttons work such as when we click on Apps at project level the "Manage Catalogs" button shortcut still works.
![image](https://user-images.githubusercontent.com/45179589/54381709-a5395400-464b-11e9-8850-06d1c3260552.png)

I could not identify any issues. I think the new changes make sense and helps with the flow of setting up apps (multi-cluster or individual ones at project level) It's nice that "Catalogs" is always in Tools menu for configuring catalogs.

**Comment by ankur111** [comment]
What is the impact on 2.2 docs because of these changes?

**Comment by davidnuzik** [comment]
Based on my review of Rancher 2.x docs this should only have a very minimal impact on https://rancher.com/docs/rancher/v2.x/en/catalog/ which probably needs to be updated anyway for Multi-Cluster app (not sure who is working on that currently).

Custom drivers are also new so if we are creating a guide to discuss there is just the small navigation change to it being under the tools menu.

**Comment by davidnuzik** [comment]
Thanks @cjellick ^ The referenced doc issue will address these changes.
Closing this issue again.

**Comment by cjellick** [comment]
tracking docs separately here https://github.com/rancher/rancher/issues/18847

**Comment by rbq** [comment]
Would it be possible to automatically add services with certain annotations to the menu bar? I'm thinking mostly of cluster services such as the longhorn UI. But maybe something on a project level might also be useful, so that user groups can easily add their CI tools etc. there.
