### ISSUE TITLE
vSphere instance size in node template row is incorrect

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18856]
rancher/rancher:master 03/12

Steps:

Create a vShpere node template with memory 2048mb

Result:

It shows 2048 GB in node template list

Expected:

It should be 2Gib

![image](https://user-images.githubusercontent.com/21168270/54253357-a904a200-4589-11e9-8e15-c441f4da2787.png)

**Comment by laoshancun** [comment]
That's interesting. 😄

**Comment by loganhz** [comment]
@laoshancun thanks for your report!

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/13/19)
Confirmed issue. This now shows the size as 2 GiB:

![image](https://user-images.githubusercontent.com/45179589/54298799-b19fad00-4576-11e9-9c10-9ee0657af447.png)
