### ISSUE TITLE
Not able to edit global DNS entry and point to a different project.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18852]
Rancher server version - Build from  master - Rancher version 8657cb2

Steps to reproduce the problem:
Have 2 clusters - cluster1 and cluster2
As Global Admin user ,
Create a Global DNS Provider
Create a Global DNS Entry with targets as project - cluster1/Default.
Edit Global DNS Entry and change target as project - cluster2/Default (remove cluster1/Default).

This operation fails:

There is a  addProject and removeProject actions being called by UI.
removeProject succeeds. But addProject fails.

<img width="1321" alt="Screen Shot 2019-03-12 at 6 03 13 PM" src="https://user-images.githubusercontent.com/4266958/54246364-d867d000-44f1-11e9-9545-5815b475c36c.png">

**Comment by alena1108** [comment]
@mrajashree can be caused by the fact that UI adds/removes project at the same time, can you follow up with @westlywright on the flow.

**Comment by mrajashree** [comment]
@westlywright It looks like the UI is doing three separate calls, a PUT to the globalDNS entry, addProject and then removeProject, which is causing it to error out since object was modified after the first request itself. Can UI make calls to get the object after each update?

<img width="1437" alt="Screen Shot 2019-03-12 at 6 40 03 PM" src="https://user-images.githubusercontent.com/10672776/54247563-aefd7300-44f6-11e9-80cc-c25d9edae160.png">

**Comment by mrajashree** [comment]
@westlywright It's the same for Multiclusterapp as well

**Comment by westlywright** [comment]
Whats the reason to make a get call after each request? Sure its possible but that seems odd to me. In order to add a project. remove a project, or both we'd have to make upwards of 5 calls?

**Comment by westlywright** [comment]
@mrajashree is it appropriate that these calls are staggered? If I call add projects first, then remove, would this provide a suitable resolution without calling get on each? I've put in a quick fix to test locally and it functions, but this used to function as well so I am not sure.

**Comment by sangeethah** [comment]
Same issue is also seen when we remove 1 of the projects from a GDNS entry that is pointing to multiple target projects.

**Comment by sangeethah** [comment]
@westlywright @mrajashree Another scenario where I see the same problem:

I start with a GDNS entry that has 2 project targets.
Edit GDNS entry and try to remove 1 of the projects.
There is a add and remove called for this action and the addProject fails the same way.
Why is there a need to call addProjects in this case ?

If I cancel out of this error , removal of project has actually succeeded in this case.

**Comment by westlywright** [comment]
@sangeethah that sounds like it may be a UI bug. Were there any project ids in the addProject call? I'll use your repro to test.

**Comment by sangeethah** [comment]
@westlywright Yes. addProject is called with the projectId that is already present in the GDNS entry.

**Comment by sangeethah** [comment]
@westlywright Logged this UI issue for tracking the behavior seen with removing of 1 of the projects from a GDNS entry that is pointing to multiple target projects -https://github.com/rancher/rancher/issues/18876

**Comment by sangeethah** [comment]
Tested with latest build from master -  Build from master - 8596256
There is no error seen when  editing global DNS entry and pointing to a different project. Bu we see this error intermittently  - https://github.com/rancher/rancher/issues/18897
