### ISSUE TITLE
LB configuration is not updated if host down

### ISSUE THREAD

**Issue by ebuildy** [rancher/rancher#1886]
2 hosts (encoder-1, stream-2) with same stack with 1 Rancher load balancer.

![Rancher]
(http://b3.ms/0xZnXDONnopO)

In the encoder-1 LB, **/etc/haproxy/haproxy.cfg**, I have seen the second backend added, but after desactivate stream-2 host, it remains here:

![haproxy]
(https://beemapp.s3-eu-west-1.amazonaws.com/36682bff-ff4a-419f-b225-bc076611d430.jpg)

It should be removed?
Where I can see the source code related (github)?

Thanks you,

And BTW, I got the following HAProxy configuration warning (because the defaults settings):

````[WARNING] 237/183229 (500) : config : 'option forwardfor' ignored for frontend '1f9d1aab-fa09-4453-a18c-6ae540ef6957_frontend' as it requires HTTP mode.````

**Comment by ebuildy** [comment]
Actually nothing is updated ;-(

Rancher API still tell me the container is up (state == running).

**Comment by alena1108** [comment]
@ebuildy host being in inactive state does mean only that the new instances can't be scheduled for start on this host. All the existing instances continue to run (and participate in the Load Balancer as we check just for the instance state when building the haproxy config).

**Comment by deniseschannon** [comment]
@ebuildy Please let us know if there are additional questions on this scenario. Otherwise, I'll close this issue as this is the design of the inactive state of a host.
