### ISSUE TITLE
Cannot create 1.12.x or 1.13.x clusters on vsphere

### ISSUE THREAD

**Issue by horihel** [rancher/rancher#18864]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a cluster with version 1.12 or 1.13 on vSphere
2. Edit YAML, enter cloud_provider information.

**Result:**
Cluster doesn't come up, hangs in "Waiting to register with kubernetes"
note that this works fine with 1.11.8 , just 1.12 and 1.13 don't work.

**Other details that may be helpful:**
it ultimately fails with these messages (from kubelet)

```
E0313 10:52:58.807943   11757 vsphere.go:1420] Get zone for node k8s-test1: POST https://149.240.170.210:443/rest/com/vmware/cis/session: 401 Unauthorized
E0313 10:52:58.807960   11757 kubelet_node_status.go:68] Unable to construct v1.Node object for kubelet: failed to get zone from cloud provider: POST https://149.240.170.210:443/rest/com/vmware/cis/session: 401 Unauthorized
E0313 10:52:58.812219   11757 vsphere.go:1420] Get zone for node k8s-test1: POST https://149.240.170.210:443/rest/com/vmware/cis/session: 401 Unauthorized
F0313 10:52:58.812237   11757 kubelet.go:1379] Kubelet failed to get node info: failed to get zone from cloud provider: POST https://149.240.170.210:443/rest/com/vmware/cis/session: 401 Unauthorized
```

Now this looks like a permission issue (as described [here](https://github.com/kubernetes/kubernetes/issues/73307)), but all the people there are getting "403 Forbidden", which indicated permission problems. I get 401, which makes me believe somewhere the vSphere credentials don't get used at all.

I also had IT triple check permissions and checked them myself with the tipps provided in issue 73307 from k8s.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.7
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastrucure Provider: Vsphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4GB RAM (doesn't matter)
- Kubernetes version (use `kubectl version`): v1.13.4-rancher1-1 or v1.12.6-rancher1-1.
- Creation works fine with v1.11.8-rancher1-1

- Docker version (use `docker version`): 

17.3.2 (automatically chosen by rancher 2.1.7 for rancheros)

**Comment by horihel** [comment]
In addition - upgrading a preexisting 1.11.x cluster to 1.12 or 1.13 will kill it.

**Comment by ArgonV** [comment]
I am seeing this as well with Rancher v2.1.7, Kubernetes v1.12 and higher with vSphere cloud config. Not setting the vSphere cloud config in the cluster YAML, the cluster will provision or an existing cluster will add the hosts. No problems with Kubernetes v1.11.8 and vSphere cloud config.

**Comment by horihel** [comment]
Just tested with rancher 2.2.0 - same problem

**Comment by horihel** [comment]
tested again on 2.2.2 - didn't go away

**Comment by TimMeade** [comment]
I just tried v2.2.2 and creating a 1.11.9 cluster and issue occurred also.  At this point we cannot create anything on vsphere with rancher 2
