### ISSUE TITLE
UI/API Slowness

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#18870]
_This issue's intended purpose is to centralize related slowness issues_

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**All related issues:**
https://github.com/rancher/rancher/issues/18522
https://github.com/rancher/rancher/issues/18295
https://github.com/rancher/rancher/issues/17101
https://github.com/rancher/rancher/issues/18571

**Fixes**
_NOTE:_ These fixes should improve performance for all types of clusters whether RKE, non-RKE, imported or not.

A. Filter by namespaces:
What: When a project is selected, norman retrieves its associated namespaces. Rancher then uses those namespaces to query workloads and other project resources.

B. Properly response to -1 pagination flag:
What: When -1 is passed to the API, the max limit is set. The max limit has been raised to 10k. This is because pagination is done on the way out of the backend. This means if X pages are provided then called by the UI, it takes X times as long as a non-paginated response.

C. Increase size of parent cache:
What: The cache used to map pods to their parents has had its size increased to 100k. When it was 1k, any resource load over 1k would cause all entries to shift out. This rendered the cache nearly unused if a user had many resources.

_How to test_: Check the "Steps to reproduce" section for steps corresponding to each fix.

**Steps to reproduce (least amount of steps as possible):**

I have been able to reproduce the behavior with the following steps:
_NOTE:_ I mentioned the type of cluster _I_ used however, any type of cluster should work for reproducing issues, as mentioned above.

_A_:
1. Use RKE on 8gb DO instance

2. Import to Rancher

3. Create new project and namespace.

4. Create additional project and namespace.

5. Launch 220 workloads with large environment variable: https://github.com/rmweir/many-workloads/ in first project/namespace pair.

6. Launch a a couple workloads without large environment variable in second project/namespace pair.

7. Create one more empty project with one empty namespace.

8. Switch between projects.

Before fix: Both projects and project related API calls will take similar times to load.

After fix: Projects containing less resources should load faster.

_B_:
1. Use GKE default instance.

2. Launch 2050 workloads in a single project and namespace. Can use the script from previous steps, but do NOT include environment variable.

3. Navigate to project, and inspect (networking tab).

4. Refresh page. Observe number of calls made to project related resources such as pods and workloads.

Before fix: multiple requests of varying yet similar length
After fix: 1 request for each project related resource

_C_:
1. Follow steps from B.

2. Navigate to project containing large number of pods

Before fix: Project related resource API calls, particularly pods, take a long time to load (if hosting rancher locally this time will likely be >50 seconds.

After fix: API calls complete and page is useable in a fractions of the time. (API calls should if rancher is local should be <10 seconds.

----
There appears to be three recorded ways of reproducing this issue:
https://github.com/rancher/rancher/issues/18295
"have a large number resources under management (pods, namespaces, clusters, deployments, pods, etc...)"

https://github.com/rancher/rancher/issues/17101
"Create a cluster with a large amount of Catalog Apps. These catalog apps should have some large answers (like base64 encoded x509 certificates). In our case we have 90+ catalog apps. To recreate the configmap portion. Deploy a large number of versions of each catalog app (over a hundred in some cases)."

https://github.com/rancher/rancher/issues/18571
"Install a lot of config maps, in this case this was caused by Rancher running tiller over and over and over again in the background trying to upgrade a catalog that was erroring out. This has resulting in 22k+ config maps and a UI that is completely unusable and it is starting to make the cluster itself unusable."

**Result:**
Project switch and loading apps is slow.

**Other details that may be helpful:**
All issues appear to be related to config maps.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.1+
- Installation option (single install/HA):
At least two of the environments were HA

**Comment by rmweir** [comment]
Have edited original post with reliable steps to reproduce slowness.

**Comment by rmweir** [comment]
Performed calls straight to k8s api via curl. Observed acceptable response times <~200ms.

**Comment by rmweir** [comment]
Repeatedly switching projects triggers error: "waiting for cluster agent to connect"

**Comment by rmweir** [comment]
Logging time for Rancher to make list requests and time to transform the responses into an object. These appear to be taking the most amount of time. Transforming the responses into objects frequently takes the most time.

**Comment by rmweir** [comment]
Compared EKS setup to RKE EC2 setup, using identical VMs. Both running identical sets of 40 workloads with a 63kb environment variable set on each workload. EKS switches projects smoothly while RKE can take >5s.

**Comment by cjellick** [comment]
@rmweir can you clean this issue up to clearly enumerate the fixes you made and how to test them specifically

**Comment by cjellick** [comment]
I haven't moved the referenced issues over to test yet and that is intentional. I think we need to hold those issues back and just test the specific improvements that @rmweir made. A few of the issues referenced (specifically related to config maps) are not fully addressed by the attached PRs. Furthermore, I don't think we can close the issues opened by users until they confirm our enhancements addressed their problems. Their may be some nuances to their scenarios that are not covered by the changes we've made.

**Comment by rmweir** [comment]
@cjellick I tested 2050 pods on an imported RKE cluster and observed a dramatic difference in performance.

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher: master  4/17 705af329
Case 1:
- launch 300 workloads with a large environment variable in `p1` 
- launch a couple of workloads without large environment variable in `p2`
- no workload in `p3`
-  switch between project

Time used to load a project:

.          | p1    | p2 | p3
--       |  --    | ----| ---
v2.2.1 | 2.2 min |2.1 min |2.2 min
master| 11.06s | 258 ms | 202 ms

Case 2: 
- launch 1100 workloads without large environment  under the same namespace in a `p4`
- navigate to project `p4`
- refresh the project page
- observe the number of calls made to project related resources such as pods and workloads

The number of call to each API: 

.          | workloads   | pods | services
--       |  --               | ----  | ----
v2.2.1 |  2                 | 2    | 2 
master| 1                  | 1    | 1

Case 3:
- the same steps as Case 2
- observe the time used for the API call `pods?limit=-1&sort=name`

.          | time used
--       |  --  
v2.2.1 | 2.2 min 
master| 3.74 s
