### ISSUE TITLE
UI: Not showing resource quota on existing or new namespaces after a resource quota is added to an existing project

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#18875]
master 3/13 

1. Create a k8s cluster, it automatically creates a Default project and default namespace
2. Add a resource quota to the "Default" project

Issue #1: Try to view/edit the resource quota on the "default" namespace in the UI. There is no resource quota shown even tho it is in the API. 

<img width="953" alt="Screen Shot 2019-03-13 at 11 24 31 AM" src="https://user-images.githubusercontent.com/11410997/54304575-b4080400-4582-11e9-8a34-6df293d9ae3a.png">

Issue #2: Try to add a new namespace to the Default project and resource quota isn't shown even tho namespace defaults should exist. 

<img width="1266" alt="Screen Shot 2019-03-13 at 11 26 43 AM" src="https://user-images.githubusercontent.com/11410997/54304722-fe898080-4582-11e9-9d16-3eeef647a552.png">

**Comment by sangeethah** [comment]
@soumyalj Can you confirm if this was the case even in 2.1.7  ?

**Comment by soumyalj** [comment]
This issue does not exist in v2.1.7. Resource quotas are shown correctly for default namespace and new namespaces.
Edit Default namespace
<img width="981" alt="Screen Shot 2019-03-13 at 12 14 01 PM" src="https://user-images.githubusercontent.com/18536626/54307699-85415c00-4589-11e9-86e8-cf8d5b738844.png">

Add new namespace
<img width="1417" alt="Screen Shot 2019-03-13 at 12 14 51 PM" src="https://user-images.githubusercontent.com/18536626/54307743-9f7b3a00-4589-11e9-8026-fd1b4f97eec2.png">
