### ISSUE TITLE
Edit as YAML is shown in the Add node screen after creating cluster

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#18879]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Select Add Cluster, select custom cluster, give it a name and create

**Result:**
* See `Edit as YAML` shown in the top of the next screen where you see the node run command

<img width="1437" alt="Screen Shot 2019-03-13 at 21 05 27" src="https://user-images.githubusercontent.com/2620179/54311038-0faead80-45d4-11e9-9637-928990d74edd.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master 3/13

**Comment by deniseschannon** [comment]
Adding this being fixed as of the cluster templates.

**Comment by davidnuzik** [comment]
Version: master-head (7/30/19)
With the new changes in the UI for cluster templates this appears fixed.

If I create a custom cluster and move on to the next step the "Edit as YAML" is now removed:

![image](https://user-images.githubusercontent.com/45179589/62155977-f7a7a400-b2be-11e9-8978-16c0a8781d74.png)
