### ISSUE TITLE
Function Menu "..." Icons wrong shape in most areas

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18886]
Version: Master 2.2 (3/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Inspect the UI and notice most function menu icons (The vertical "...") are strectched out. They are supposed to be square.
- Look at the Workloads page. Create one workload. This is an example of one area where we see the correct square verison:
![image](https://user-images.githubusercontent.com/45179589/54319288-5be2f900-45a6-11e9-85a9-5a4b6b1ff65d.png)

**Result:**
Function menu icons are stretched out vertically but should not be.

**Comment by cjellick** [comment]
moving out
