### ISSUE TITLE
Regression of #18288: Search not working anywhere with 'a' and sometimes 'z' chars and some numbers

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18889]
Version: Master 2.2 (3/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to use search in various places in the UI notice that when you just enter 'a' it does not seem to work. Many times 'z' does not work as well but sometimes it does. All other chars seem to work.
- Try to search on Cloud Keys page with numbers and this also does not work in some cases.

**Result:**
Regression of #18288
Search does not work for individual z or a char and sometimes numbers

**Comment by vincent99** [comment]
There's nothing magic about a or z... Searching works fine, it's just being told to search in fields that aren't being displayed.  Specifically for cloud keys, `created` (the ISO-8601 timestamp that always has a `T` and a `Z` in it) and `displayType`, which is the driver ("DigitalOcean", "VMWare vSphere", etc).

**Comment by davidnuzik** [comment]
Closing issue as this will be tested during testing of related issue #18890 I did not initially understand the nature of the problem. See Vincent's comment. This issue is essentially a duplicate of #18890
