### ISSUE TITLE
Show advanced options in Add Cluster also shows advanced options in add node screen

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#18880]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Add cluster, select custom, give it a name, click `Show advanced options` in the bottom right and create the cluster

**Result:**
* Advanced options are also shown in the add node screen where it shows the add node command

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master 3/13
- Installation option (single install/HA):

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: Master (4/26/19)

I followed the steps to reproduce and no longer observe this behavior on the latest master (v2.3). When I click next to get to the node screen Advanced Options is not expanded.
