### ISSUE TITLE
Vmware - Discrepancy in the disk size on node template and node created on vsphere backend client

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18884]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce:**
1. Create a VMware cluster with disk space - 20000MB mentioned in the node template.
2. Verify the node created on the vSphere backend client, and verify its disk space

**Expected Result:**
Node be created with disk space - 20GB

**Actual Result:**
Node is created with disk space 19.53GB

<img width="641" alt="Screen Shot 2019-03-13 at 12 14 57 PM" src="https://user-images.githubusercontent.com/26032343/54316251-7fee0c80-459d-11e9-8611-ff094de9418c.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master (03/13/2019)
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): VMware vSphere cluster
- Kubernetes version (use `kubectl version`):

```
v1.13.4
```

**Comment by vincent99** [comment]
They are using powers of 2, i.e. 1GB = 1024MB instead of 1000MB.  20,000MB "is" 19.53GB.
