### ISSUE TITLE
Consider Maintaining Homebrew Tap for Rancher Tools for MacOS

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#18898]
**What kind of request is this (question/bug/enhancement/feature request):** feature

I was thinking it might be useful for not only Rancher employees but many open source users if Rancher maintained it's own homebrew tap that could be updated solely through Rancher's existing CI system to provide easy and quick updates to all Rancher CLI based tools. It could also support versions so CLI for Rancher and Rancher 2 can be installed side by side, also it could support RC releases. 

Right now I the process is either wait for the homebrew formula to be updated, or to manually go to the right project and download the binary, install it, etc and there's discrepancy in how tools are packaged. With rke the binary is just uploaded, but for the rancher cli is in an archive for some reason. system-tools is a direct binary upload.

With a Homebrew Tap, user's could install just by doing `brew install rancher/homebrew/cli` or install the `brew tap rancher/homebrew` to have the tap indexed.

I'll volunteer to help get it started, but would need someone at Rancher to wire it up to the CI system.

**Comment by superseb** [comment]
I don't think solving a packaging method for one platform is beneficial to the other platforms. We are moving to archives for RKE as described in https://github.com/rancher/rke/issues/911 and will do the same for system-tools here https://github.com/rancher/rancher/issues/18904.

Besides that, we have had RKE added to brew manually and now its in some auto update cycle but not in the release process itself. There hasn't been much response on having tools in brew in general, and when the releases are generic after resolving both issues, there is a generic approach to get releases for all platforms so maybe that is the best option for now.

**Comment by ekristen** [comment]
I understand. You could solve the other platforms at the same time by hosting your own apt repo, rpm repo etc ...

I suppose it depends on the number of users that are on MacOS vs other platforms.
