### ISSUE TITLE
Expand container default resource limit panel when editing a namespace

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18893]
Version: Master

Steps
1. Create a DO cluster
2. Create a project with default resource quota limits and container default resource limits.
3. Create a new namespace.
4. Edit the namespace 

On edit, the "container default resource limit" panel should be expanded (just like the resource quota panel)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/14/19) 6875782b6131

Follow the steps to reproduce. Have settings set for Container Default Resource Limit for the project, but when create namespace it is NOT automatically expanded for me.
![image](https://user-images.githubusercontent.com/45179589/54379075-ef1f3b80-4645-11e9-866a-e9fb345657d6.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/14/19) 6875782b6131
Confirmed issue. The Container Default Resource Limit section is now automatically opened upon namespace creation or edit.
