### ISSUE TITLE
Support Rancher Logging/Monitoring/Pipeline feature in ARM64

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18891]
We introduced arm64 support in https://github.com/rancher/rancher/issues/16461

But Logging/Monitoring/Pipeline features are not working on ARM64.

We need to support them

**Comment by ekristen** [comment]
From my perspective Logging and Monitoring are of higher priority to support.

**Comment by kerven88** [comment]
Is the Logging/Monitoring/Pipeline features available on arm64 now?

**Comment by kerven88** [comment]
> We introduced arm64 support in #16461
> 
> But Logging/Monitoring/Pipeline features are not working on ARM64.
> 
> We need to support them

Is the Logging/Monitoring/Pipeline features available on arm64 now ?

**Comment by Shaked** [comment]
Is there a way to export data from remote IoT devices (ARM based) to main prometheus/grafana?

**Comment by Ashtonian** [comment]
I think this is still an issue.

**Comment by g1i7ch** [comment]
absolutely still an issue.
