### ISSUE TITLE
[UI] vSphere node template incorrectly requires 'VM Network' field when using 'Data Store'

### ISSUE THREAD

**Issue by ebauman** [rancher/rancher#18894]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a node template using the vSphere driver. Defaults are fine. 
1. Edit the newly-created template, and attempt to specify the Data Store under the Scheduling dropdown.
1. Save the node template. You will receive an error of `Validation failed in API: vmwarevsphereConfig network=NotNullable 422:`
1. Fill in the VM Network field. You will then be able to save the node template
1. Edit the node template once again. Delete (nullify) the VM Network field. You will now be able to save the template.

**Result:** Desired result is that filling in the Data Store field should not require also completing the VM Network field.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher 2.2.0-rc4, user interface v2.2.7 
--

- Installation option (single install/HA): single install (really just `docker run ...`)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Does not require kubernetes (no cluster created)
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by sowmyav27** [comment]
Verified on `rancher:v2.2.0-rc4`. 
When the you do not enter any value in field 'Network', value passed - `[]`
But on clicking on edit, and when no value is entered in the 'Network field', value passed is `null` and error `Validation failed in API: vmwarevsphereConfig network=NotNullable 422:` is seen on the UI.

**Comment by sangeethah** [comment]
@westlywright Will a fix from UI be sufficient for this ?

**Comment by westlywright** [comment]
@sangeethah seems like a UI fix may be in order if the UI is setting it null. @loganhz can you verify that the UI is actually the one to set this field to null on edit and if it is can you fix that? We should verify that after save there isn't a bug in the API that set the field null when coming back to us.

**Comment by loganhz** [comment]
API returns `null` to UI.

![image](https://user-images.githubusercontent.com/21168270/54322983-3ef40780-4632-11e9-8662-e155258bbffe.png)

@westlywright do you want to me to fix it in UI? We can workaround it. But i think it's an API issue

**Comment by loganhz** [comment]
Just check with backend developer. We need to pass an empty array or do not pass the array filed if it is empty. I will fix in UI side

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/14/19) 6875782b6131
This is now fixed. When we do this we pass an empty array for `network: []`.
I can create or edit a vsphere template, specify the datastore and leave the network field empty (null) without any issues now.

I ensured HTTP/API looks correct now.
