### ISSUE TITLE
UI keep loading in save button but not send request to backend in logging

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18908]
Step to reproduce:
1. configure invalid custom tag with key <source>
2. click save button.
3. server return 422 code
4. continue to click save again
5. UI hang and save button turn to "Saving" when UI does not send the request to backend at the second time click

**Comment by loganhz** [comment]
@aiwantaozi I cannot reproduce this issue. Can you try on master, please?

**Comment by aiwantaozi** [comment]
Couldn't reproduce in current master
