### ISSUE TITLE
Metadata - secondary launch config service does not have any information about the parent service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1890]
Server version - Build from master - Aug 26

Create a service with  secondary launch config.

From within container of the secondary launch config service , metadata for container/service does not include any information about the primary service it belongs to.

**Comment by alena1108** [comment]
It really doesn't have to know anything about primary launch config unless it uses a) network of primary config b) volumes of primary config. In this case, metadata already includes this info
