### ISSUE TITLE
Project-Scoped Secrets can only handle kind:opaque

### ISSUE THREAD

**Issue by McSlow** [rancher/rancher#18906]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Create a Project Scoped Secret

**Result:**
It's fixed to kind:opaque

**Other details that may be helpful:**
Reason for this request: Ceph for example needs secrets in a particular namespace to allow creating/attaching storage. So it would be nice to deploy this secret project-wide. Unfortunately this secret has a kind of kubernetes/rbd instead of 'opaque', so it can't be created by rancher right now. (at least not project-scoped using the ui or api. 

**Environment information**
- Rancher version 2.1.6

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24240
