### ISSUE TITLE
2.1.7: cluster stuck in Updating after Rancher upgrade

### ISSUE THREAD

**Issue by bjornmagnusson** [rancher/rancher#18903]
This cluster is currently Updating.

Failed to get Kubernetes server version: Get https://10.210.36.110:6443/version?timeout=32s: can not build dialer to c-gqxjb:m-e1cf59755c38
Querying that URL in a browser works fine though.
`{
major: "1",
minor: "11",
gitVersion: "v1.11.6",
gitCommit: "b1d75deca493a24a2f87eb1efde1a569e52fc8d9",
gitTreeState: "clean",
buildDate: "2018-12-16T04:30:10Z",
goVersion: "go1.10.3",
compiler: "gc",
platform: "linux/amd64"
}`

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade Rancher server with existing RKE cluster from 2.1.5 to 2.1.7

**Result:**
Existing cluster is stuck in Updating

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher 2.1.7
Single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
RKE cluster 1.11.6
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```
(paste the output here)
```

- Docker version (use `docker version`):
Rancher server:
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64
 Experimental:    false

Nodes of cluster running 18.06.1 / 18.09.2 / 18.09.3
```
(paste the output here)
```

Logs:
2019/03/14 08:20:25 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-mfpg5
2019/03/14 08:20:25 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/03/14 08:20:25 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/03/14 08:20:25 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/03/14 08:20:26 [INFO] Handling backend connection request [c-gqxjb:m-6dee2a607049]
2019/03/14 08:20:27 [INFO] Handling backend connection request [c-gqxjb:m-a6d59f48b418]
2019/03/14 08:20:27 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/03/14 08:20:27 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
....
2019/03/14 08:30:33 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
E0314 08:30:33.896278       6 reflector.go:251] github.com/rancher/norman/controller/generic_controller.go:144: Failed to watch *v1beta1.PodSecurityPolicy: Get https://10.210.36.110:6443/apis/extensions/v1beta1/watch/podsecuritypolicies?resourceVersion=46664435&timeout=1h0m0s&timeoutSeconds=351: tunnel disconnect
2019/03/14 08:30:34 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/03/14 08:30:34 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/03/14 08:30:34 [INFO] Handling backend connection request [c-gqxjb:m-469a811a0661]
2019/03/14 08:30:34 [INFO] Handling backend connection request [c-gqxjb:m-b91176a42aa8]
2019/03/14 08:30:34 [INFO] Handling backend connection request [c-gqxjb:m-e1108850ce67]
E0314 08:30:35.686558       6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:144: Failed to list *v1beta1.PodSecurityPolicy: Get https://10.210.36.110:6443/apis/extensions/v1beta1/podsecuritypolicies?limit=500&resourceVersion=0&timeout=30s: tunnel disconnect
2019/03/14 08:30:35 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/03/14 08:30:35 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/03/14 08:30:35 [INFO] Handling backend connection request [c-gqxjb:m-6dee2a607049]
2019/03/14 08:30:35 [INFO] Handling backend connection request [c-gqxjb:m-4e933c6a65a8]
2019/03/14 08:30:36 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF

**Comment by sboulkour** [comment]
I had a similar issue when upgrading from v2.1.6 to v2.1.7.
Rolling back to v2.1.6 fixed the issue for me.

**Comment by sboulkour** [comment]
Tried to upgrade to 2.1.8 and 2.2.2 : exact same issue.

**Comment by huegelc** [comment]
Same issue here from 2.2.4 to 2.2.8.

**Comment by ypodo** [comment]
![image](https://user-images.githubusercontent.com/1647305/67289008-902c7980-f4e6-11e9-9fcb-0aa8b963ab2d.png)

Same issue here from 2.2.8 to 2.3.1.

**Comment by JeanClaudeVanDam** [comment]
Same issue after upgrade from 2.2.8 to 2.3.1
