### ISSUE TITLE
 How do I change the rancher-server timezone settings?

### ISSUE THREAD

**Issue by portfield-slash** [rancher/rancher#18913]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
I want to use kubernetes cronjob. My timezone setting is UTC+9.
I believe that it is necessary to change the timezone setting of the rancher-server container.
Is there any other good way?

**Result:**
-

**Other details that may be helpful:**
-

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.7

- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):cloud
- Kubernetes version (use `kubectl version`):v1.13.4
```

- Docker version (use `docker version`):

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by cjellick** [comment]
Change the timezone of the underlying host?

**Comment by bou7mis** [comment]
+1. I have a scheduled job on my production cluster that is programmed like so : "0 6,12,18 * * *". Timezone is correctly set in the host node and i confirmed that with date command. But i noticed from workload logs that the job is executing at 8am, 2pm and 8pm everyday. Is there a timezone setting somewhere to configure in rancher cluster settings ?

**Comment by wisepotato** [comment]
also having this problem, because rancher is using UTC, anda ll docker containers that execute from it are UTC, but my server host is CEST

**Comment by dunxiii** [comment]
I also see this problem, host has the correct timezone set but rancher is off by 2 hours.

**Comment by portfield-slash** [comment]
Duplicate of #19675 #22259

**Comment by pakali** [comment]
Edit cluster.yaml (Edit cluster > Edit as YAML) and add this lines to services section:

```
services:
    kube-controller:
      extra_binds:
        - '/etc/localtime:/etc/localtime'
```

After that configure correct timezone on Control Plane role nodes.
