### ISSUE TITLE
'Failed to download etcd snapshot' error seen while trying to restore from backup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18918]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create cluster with one node with all roles - etcd, ctrl plane, worker
2. Automatic backup occurs.
3. Scale up one node. (all roles)
4. Take a backup
5. Scale up one more node (all roles)
6. Take a backup
7. Restore to the backup taken in Step 2.

**Expected Result:**
Restore happens successfully.

**Actual Result:**
Error `Failed to download etcd snapshot from backup server [<ip-address>], exit code [1]: time="2019-03-14T18:00:04Z" level=fatal msg="Get https://<ip-address>:2379/c-fttlh-rl-svh48: dial tcp <ip-address>:2379: getsockopt: connection refused"` is seen in the logs

<img width="1272" alt="Screen Shot 2019-03-14 at 11 06 45 AM" src="https://user-images.githubusercontent.com/26032343/54380724-6f936b80-4649-11e9-9f2c-7c7260c15b3b.png">

**Note:**
This is a regression issue. This scenario was working earlier.
The retry happens, seen in the log, but it always hits the same node (which does not have the backup)

Issue https://github.com/rancher/rancher/issues/18419, has the similar scenario, which was tested and closed.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): both - single install and HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Digital Ocean cluster
- Kubernetes version (use `kubectl version`):

```
v1.13.4
```

- Docker version (use `docker version`):

```
18.9.3
```

**Comment by moelsayed** [comment]
@sowmyav27 I couldn't reproduce this. I tried about 2 dozen times. I was only able to hit it once and it recovered immediately in the second run.

**Comment by sowmyav27** [comment]
verified on `rancher:master`. (commit id: a4b44d55) 
Reproduced the same issue on a fresh install - single node.

**Comment by sangeethah** [comment]
@sowmyav27 , When validating this issue can you also see if the .part is not getting created for the backup snapshots in all etcd nodes ?

**Comment by moelsayed** [comment]
The backup server container should start, check if the snapshot it should serve is there, and exit with an error if it's not. We check for the container status and if it's not running, we try on another node..

In the cases where this fails. The status check happens faster than the container failure and exists. It finds the container running before it's stopped with an error. So rke assumes the backup server is running on that node, while it's not.

The fix was simply to add a small wait time after the server container start to give it a chance to report the correct status.

**Comment by sowmyav27** [comment]
verified on rancher:master. (03/18/2019)
**Steps taken:**

1. Create cluster with - etcd, ctrl plane, worker nodes
2. Automatic backup occurs.
3. Scale up etcd node.
4. Take a backup
5. Scale up etc node
6. Take a backup
7. Restore to the backup taken in Step 2.

No error is seen on UI/logs.
.part files are also not seen.
