### ISSUE TITLE
Error connecting to WebSocket

### ISSUE THREAD

**Issue by TheYkk** [rancher/rancher#18910]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
i create cluster and set etcd , worker , console
and i wait but app is broken
gime me error on after login

**Result:** 

**Other details that may be helpful:**

Logs-> https://gist.github.com/TheYkk/6b6f1fb67f0848b6a8dbf28888772da4

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 

Rancher | v2.1.7
-- | --
User Interface | v2.1.21

- Installation option (single install/HA): **single**

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): vm
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
There is not really enough information in here to determine what is going on. Are you getting the error websocket popup after logging in to Rancher? Are you directly connecting to port 443 on the host you are running the `rancher/rancher` container? Does it happen when you start a new container without creating a cluster or does it always happen?

**Comment by TheYkk** [comment]
I forgot to close the problem , sorry.
