### ISSUE TITLE
Metadata - For secondary launch config services create_index refers to the entire service's (along with all secondary launch configs) index.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1891]
Server version - Build from Aug 26

Had a service - s1 with scale 2 which had 2 secondary launch config services -s2 and s3.

Metadata for s1 , s2 and s3 services have create_index set to 6.

We expect this to be set to "2" for s1,s2 and s3.

**Comment by alena1108** [comment]
We are gonna hide it from metadata for now.

**Comment by sangeethah** [comment]
Tested with server built from master on Aug 27.

create_index is not available in the service metadata anymore.
