### ISSUE TITLE
FreeIPA group memberships not showing up in cluster membership auto complete list

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#18927]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1) setup FreeIPA authentication
2) attempt to add a group to a cluster membership

**Result:**
No groups show up in the auto complete list

**Other details that may be helpful:**
Ping me for logs or additional information

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.1.7
- Installation option (single install/HA): HA

**Comment by mrajashree** [comment]
This fix worked for the setup (customer) that didn't have entryDN attribute. Our test setup returns that attribute. So we may not be able to reproduce the bug

**Comment by deniseschannon** [comment]
Per @mrajashree's comments, our test setup aren't missing these attributes so we won't be able to test this exact use case, but we should run at least one pass to ensure FreeIPA setups are still working as expected.

**Comment by soumyalj** [comment]
Tested with master-head branch(bdb8e67c907d)
Enabled auth with Free IPA. Adding groups/users to clusters and project members is functional. 
"Search Filter" field option is presented for User and Groups in "Customize Schema" section.
Users have the option to set these fields when FreeIPA auth is enabled. When the field is set , this filter gets applied to the list of users/groups that get searched when adding users to add members to cluster/projects.
