### ISSUE TITLE
UI Monitoring: Memory leak can cause browser to crash after a couple of hours

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18929]
Version: Master 2.2 (3/14/19) 6875782b6131

Related to #18883 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Set up a cluster. In my case this was DO with six nodes (five are workers)
- In the rancher tab, enable cluster monitoring. When this is ready, expand ALL tabs on the cluster monitoring page. I set mine to 5 mins each. Leave this page up for approx 1 hour and you will see the memory leak happen if you open the Chrome Task Manger. If you leave it up for 2 or more hours the browser tab _might_ crash.

**Result:**
After 60 mins, memory footprint is approx 2GB (which is a notable improvement over related issue) #18883 

![image](https://user-images.githubusercontent.com/45179589/54390520-e6d3fa00-465f-11e9-99e2-b72974d0091a.png)

It's great that we seem to cap out at about 2GB of memory but there is _still_ a memory leak happening here and SOMETIMES but not always the page can still crash. In a perfect world, we would not need more than a couple hundred MB tops and clean up / garbage collect / free up memory that is no longer needed continually without exceeding x number of MB. If we could at least improve this so we only need perhaps 300MB or less max that would be very nice.

Screenshot showing a crash -- this took a couple of hours for me and we never exceeded 1.9GB of memory footprint so there is still an issue.
![image](https://user-images.githubusercontent.com/45179589/54392503-19ccbc80-4665-11e9-956a-2213f5d72c89.png)

**Comment by davidnuzik** [comment]
I made updates to the issue; the memory footprint does not exceed 2GB, so this only addresses the fact that we still technically have a memory leak and would like to request further improvement if feasible.

**Comment by loganhz** [comment]
@davidnuzik I found something else we can improve. moved into 2.2.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/15/19) 21d45c0f8e83
Tested again with latest update (latest master).
Start at 10:05am Local time
- 10:00am baseline without monitoring 120MB memory footprint
- 10:06am when monitoring enabled and charts open initial 157MB footprint
- 10:20am (15 mins) 220MB footprint
- 10:35am (30mins) 231MB footprint
- 11:05am (1hr) 257MB footprint (way better!)
- 12:05pm (2hrs) 305MB footprint (so far seems to hover around 300MB tops)
- 1:05pm (3hrs) 291MB footprint (great!)

I occasionally went thru, scrolled the page to see all charts, mouseover them, etc and I would maybe see up to 40MB increase but this goes down after a while. I think this has resolved the issue because I am no longer seeing memory increase over time about 300-350MB seems to be the cap based on my testing.

**Comment by Neneil94** [comment]
We are using the latest version of rancher (2.8) we are facing a memory problem too. Especially in our UI when we list all Ingresses or open the Workloads page. Rancher tries to load around 3000 Workloads and freezes with >5GB memory usage:

![Bildschirmfoto 2023-12-08 um 18 33 17](https://github.com/rancher/rancher/assets/26835980/d9c6d97b-93cf-4e57-8cad-13e3fb94217c)

It's a large scale cluster with more than 60 worker nodes and three main nodes.

Does anyone else have this problem with the Rancher UI?

**Comment by michbeck100** [comment]
Yes I have the same problem. It's also a bigger cluster with lots of resources. So I Wouldn't consider this issue fixed. Please reopen.

**Comment by snivou** [comment]
I also encountered the same problem, it appeared in v2.7.9 and v2.8.1. My cluster only has 3 master & 6 workers(170 pods )(9 VMs). Frequent memory overflow occurs when switching options.

**Comment by ciantfv456** [comment]
I'm using 2.7.9, when there are a lot of changes 
 in the cluster, the UI just get stuck and most of the time receive OutOfMemory in the browser
