### ISSUE TITLE
vip - unique vip needs to be assigned for each of the secondary launch config services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1892]
Server version - Build from master - Aug 26

Had a service - s1 with scale 2 which had 2 secondary launch config services -s2 and s3.

Same vip is generated for s1, s2 and s3.

Expected Behavior:
We should be assigning unique vips for s1, s2 and s3.

**Comment by alena1108** [comment]
Current behavior is aligned with kubernetes - one VIP (k8s cluster ip) gets assigned per service (k8s pod). Not going to fix it
