### ISSUE TITLE
Do not allow restoring to a S3 backup when local backup is configured and provide appropriate error message 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18920]
Version: Master build from March 14

Steps:
1. Create a cluster with S3 backup config
2. Create few backups B1, B2
3. Edit and change to local backup config
4. Perform a restore to B1 which is a S3 backup

After restore, cluster is stuck in "Updating" state with the message below:
```
This cluster is currently Updating.
Failed to prepare backup: restoring S3 backups with no cluster level S3 configuration is not supported
```

We should not allow restoring to a S3 backup when local backup is configured. It should error out at the API level with appropriate message

**Comment by alena1108** [comment]
Making a check on the API level should be sufficient enough.

**Comment by soumyalj** [comment]
Tested with master build from March 14th evening. 
Performed the steps above as mentioned in the issue: 

The following error message is shown in UI:

<img width="350" alt="Screen Shot 2019-03-14 at 8 55 27 PM" src="https://user-images.githubusercontent.com/18536626/54408236-5963ca80-469e-11e9-8b0e-2b2fceada631.png">

There is no relevant error message displayed. 

In the inspect call,  `405 : Method not allowed` is displayed as request  and the response is NULL

<img width="537" alt="Screen Shot 2019-03-14 at 9 18 10 PM" src="https://user-images.githubusercontent.com/18536626/54408330-b9f30780-469e-11e9-9067-c75eeef8f810.png">

**Comment by soumyalj** [comment]
Tested with master build on March 16th. Tested with the steps above and now we do not allow restoring to S3 backup when local backup is configured. 

<img width="1236" alt="Screen Shot 2019-03-16 at 2 12 03 PM" src="https://user-images.githubusercontent.com/18536626/54481862-85469380-47f7-11e9-9b21-47df538a96fc.png">


A UI bug related to this issue is filed here : https://github.com/rancher/rancher/issues/18975
