### ISSUE TITLE
Should cache system library chart in Rancher server

### ISSUE THREAD

**Issue by JohnDavidLarsen** [rancher/rancher#18921]
Now that monitoring has been upgraded to more than just a Catalog App/Charts it is still using the rancher catalog to deploy which doesn't work in air-gapped environments. 
Even if I add an internal catalog with rancher-monitoring catalog, it won't install correctly as it needs many internal elements. Can this be packaged/documented in a such a way to allow air-gapped installation?

**Comment by alena1108** [comment]
@JohnDavidLarsen could you post the exact RC version you've hit the issue on?

**Comment by JohnDavidLarsen** [comment]
Currently testing 2.2.0-rc4 released yesterday, hadn't tested previous 2.2.0-rc in airgrapped environment. 

Currently error I get is 
failed to ensure catalog "catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2" failed to find by catalog by ID "catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2"

Alternatively if I install through the custom catalog from  https://github.com/rancher/system-charts/tree/dev/charts/rancher-monitoring/v0.0.2
it get stuck giving me the Error: no objects visited" in the log.

**Comment by jiaqiluo** [comment]
HI @JohnDavidLarsen the v2.2.0-rc4 is good for the monitoring feature, you are almost there but there are two more steps to make it happen:
1. Clone the `system-charts` repo and run the git server in your air-gapped environment such that Rancher server can reach the repo to use those charts. You need to make sure the `master` branch exists in your lcoal repo, the link you provided points to `dev` not `master`, so it clones the `dev`branch not `master`
2. add a new global catalog named  `system-library` and set its catalog URL to your local git server. 
Save and wait its state to be active. 

Now you should be able to enable monitoring.

**Comment by JohnDavidLarsen** [comment]
Thanks I get an error that there are already is a system-library though

**Comment by jiaqiluo** [comment]
@JohnDavidLarsen  Could you try this: 
1.  replace `<your-server>` with your real address and open it in the browser 
```
https://<your-server>/v3/catalogs/system-library
```
2. click on `edit` on the upper right corner -> change the URL in the editing page -> show request -> send request -> follow self link
3. switch back to your Rancher UI, and now the `system-library` should show up in the list of catalogs.

**Comment by JohnDavidLarsen** [comment]
Awesome, thanks that worked. So mostly a documentation issue. Glad to know I can customize those core catalogs now.

**Comment by JohnDavidLarsen** [comment]
Possibly related, should I put in another ticket. The Global-DNS system doesn't even appear in the Tools dropdown in the air-gapped system. I'm assuming it couldn't find the library on first boot, but I don't see a way of retriggering it, I've tried to restarting the rancher/rancher container.

**Comment by cjellick** [comment]
global dns is not supported in a couple scenarios:
1. if you are in a single node rancher server install
2. youve disabled the local cluster
this is because we need to deploy the controller for it into the local cluster. if we detect youre in one of those setups, we hide the option

It won't really work in an airgap env regardless bc we only support dns providers that are on the public internet at this time

**Comment by adalga** [comment]
Hi, 

I have the same issue and I wonder if there is a way to use monitoring without requiring git server. 

After I saw the problem, I disabled monitoring. However, The error message <failed to ensure catalog "catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2" failed to find by catalog by ID "catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2"> didn't disappear. How would I get rid of that message?

**Comment by cjellick** [comment]
where is it appearing?

**Comment by ekristen** [comment]
This is showing up on my HA local cluster on the cluster list. Active is in RED but everything else looks ok.

**Comment by mjschmidt** [comment]
@ekristen when you clicked save did you change any configs? This did not help me

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/20387
