### ISSUE TITLE
GlobalDNSProvider RBAC: Add a new role to add  read-only members

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#18938]
We need to enhance the RBAC for GlobalDNSProvider and let the creator of the GlobalDNSProvider add users with "read-only" role as members.

The usecase for this is: A user who has created a GlobalDNSProvider, may want to share this with other users only for creating globalDNS entries using this provider. But not for managing the provider itself (members should not be able to edit/delete the provider entry). For this case, we should add the "readonly"/"use" kind of role.

**Comment by mrajashree** [comment]
In rancher types, we already have all three access types listed in the enum for members. I think only UI changes are needed for this, @westlywright do you agree?

**Comment by westlywright** [comment]
@prachidamle @mrajashree yes the UI will need to be updated to allow additional roles for the DNS Provider. There was a choice made sometime back that limited the UI selection to owner only to reduce confusion I believe.

**Comment by mrajashree** [comment]
@westlywright thanks, I'm assigning it over to you

**Comment by westlywright** [comment]
@prachidamle does this only apply to global dns providers or global dns entries as well?

**Comment by davidnuzik** [comment]
(Cannot validate at this time, blocked by #19676 )
(Need to update GDNS test plan around this)

**Comment by davidnuzik** [comment]
Version: Master (4/18/19)

RBAC was tested in this area and I updated the GDNS test plan around RBAC as well as the UI test plan.
I ensured that:
read-only user can see the GDNS Provider, can NOT edit it, can NOT delete it, can leverage the GDNS provider by creating GDNS entires (and ensured worked and created in Route53), no-access user cannot see anything or create GDNS entries (doesn't see GDNS provider).
