### ISSUE TITLE
UI (GlobalDNS Entry): Add the helper tip about annotation to Ingress, for both mcapp and projects.

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#18937]
We need to a UI change to show the tip about adding the annotation label ( rancher.io/globalDNS.hostname ) on the ingress, for both - Multi Cluster App or target projects.

Currently this tip appears only if the user selects the "target projects" option. But this annotation is required even in case of Multi Cluster App.

Also the text should be changed to: "To finalize programming for your Global DNS entry, you must add the following annotation label ( `rancher.io/globalDNS.<HOSTNAME>` ) on the ingress for your application, where `<HOSTNAME>` is the host name used in the routing rules of your ingress. This `<HOSTNAME>` must also match the FQDN of the Global DNS entry."

<img width="1405" alt="Screen Shot 2019-03-14 at 4 00 10 PM" src="https://user-images.githubusercontent.com/1470602/54397049-49ce8c80-4672-11e9-924e-494f1485908a.png">

**Comment by alena1108** [comment]
This item came via doc review feedback.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/15/19) 21d45c0f8e83

The tip has been improved per the recommendation. It now is also shown whether Multi-Cluster App or Projects radio button is chosen:
![image](https://user-images.githubusercontent.com/45179589/54468409-86b98280-4749-11e9-91ec-ee108fd7693f.png)
