### ISSUE TITLE
Etcd snapshots have .part file along with the actual snapshot

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18935]
Version: Master build from March 14th

Steps:
1. Create a single node cluster with local backup config of 1hr creation time
2. Wait for the first automatic snapshot to be taken

The snapshots have a .part in /opt/rke/etcd-snapshots directory
```
root@soumyasingagn1:/opt/rke/etcd-snapshots# ls -ltr
total 1940
-rw-r--r-- 1 root root 1982496 Mar 14 22:06 c-smfrt-rl-bxr9h
-rw-r--r-- 1 root root       0 Mar 14 22:06 c-smfrt-rl-bxr9h.part

```
3. Take a manual backup, the .part file is present here for the manual backup too
```
root@soumyasingagn1:/opt/rke/etcd-snapshots# ls -ltr
total 5936
-rw-r--r-- 1 root root 1982496 Mar 14 22:06 c-smfrt-rl-bxr9h
-rw-r--r-- 1 root root       0 Mar 14 22:06 c-smfrt-rl-bxr9h.part
-rw-r--r-- 1 root root 3170336 Mar 14 22:33 c-smfrt-ml-tfg64
-rw-r--r-- 1 root root  917504 Mar 14 22:33 c-smfrt-ml-tfg64.part

```

**Comment by moelsayed** [comment]
Part files are generated by the etcdctl command: https://github.com/etcd-io/etcd/blob/release-3.2/etcdctl/ctlv3/command/snapshot_command.go#L110-L146

**Comment by cjellick** [comment]
@moelsayed what does that mean? are you saying its ok that they are there?

**Comment by moelsayed** [comment]
@cjellick No. We were discussing why/how these file are created. I put the source for reference.

**Comment by sowmyav27** [comment]
verified on `rancher:master` (Commit id: a4b44d5). 
.part files are not seen anymore. verified by taking manual backups.

**Comment by soumyalj** [comment]
Tested with master build from March 16th/17th. Verified that there is no .part file for the etcd snapshots for the following cases:

1. Manual back on fresh install
2. Recurring back up on fresh install
3. Recurring back up after restore
4. Manual backup after restore
5. Manual backup after changing from S3 to local config
6. Manual back up after upgrade after editing cluster
7. Recurring back up after upgrade after editing cluster

.part files are not present along with the snapshots
