### ISSUE TITLE
UI Global Menu: Make it easier to see which cluster is selected when picking a project

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18933]
Version: Master 2.2 (3/14/19) 6875782b6131

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
- Have a couple of clusters. At the global level, open the Global Menu and hover over a cluster and then go to the right to mouseover projects.
- Notice that there is no color to indicate which cluster we have selected (which cluster we are looking at)

**Result:**
I would like to request having some "selected" state for a cluster on this menu (not necessarily active just selected) such as a lighter blue color or something not as dark as active state perhaps.
We could also have an arrow or something pointing to the right so it's more clear what cluster is selected.

Here is a screenshot of how it looks today. Notice that "david-ec2" cluster is not highlighted in any way we can only see small text above the projects list to indicate what cluster we have selected.
![image](https://user-images.githubusercontent.com/45179589/54392919-0cfc9880-4666-11e9-8ac2-574f1b306ca5.png)

**Comment by cjellick** [comment]
moving out of release

**Comment by cjellick** [comment]
accidentally closed by misclick

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/19/19) ImageID: afe8fffcf864 (latest master)
The cluster does not stay highlighted medium-blue color when I move my mouse to the right to pick a project.
![image](https://user-images.githubusercontent.com/45179589/54639571-f631b980-4a4a-11e9-82e5-8938322750a7.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/19/19)
Confirmed issue. Now when you hover over the cluster then go to the right to hover on projects, cluster stays highlighted. This makes it much more visually clear what cluster's projects you are looking at in the Global menu.
![image](https://user-images.githubusercontent.com/45179589/54653797-23955c00-4a79-11e9-8f05-d9bbbb225374.png)

Smoke tested the menu and didn't spot any issues with navigation / look and feel.
