### ISSUE TITLE
Air Gap HA Install (stable) does not work

### ISSUE THREAD

**Issue by scotthesterberg** [rancher/rancher#18931]
I am using version 1.13 of kubectl and version 1.11 of kubernetes (deployed per instructions from Rancher docs by RKE). I can get Rancher 2.x to deploy and work no problem via the non-air gap install method. Unfortunately the air-gap method (stable) does not work and seems to need fixing. 
Edit: forgot to mention this on RHEL 7.5 operating system.

The command to deploy the certificate manager, 'kubectl -n kube-system apply -R -f ./cert-manager', fails as show below. I was able get it to deploy following instructions [from helm](https://docs.cert-manager.io/en/latest/getting-started/install.html#installing-with-helm), which seems to fix the issue by applying required Custom Resource Definitions to kubernetes. I also tried applying the change for fetching a specific version of cert-manager discussed in [issue 18283](https://github.com/rancher/rancher/issues/18283), but that did not seem to make any difference.

> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl --kubeconfig=$(echo \"/home/ec2-user/kube_config_20190314-rancher02_rke_config.yml\") -n kube-system apply -R -f ~/cert-manager", "delta": "0:00:00.507408", "end": "2019-03-14 20:30:49.463995", "msg": "non-zero return code", "rc": 1, "start": "2019-03-14 20:30:48.956587", "stderr": "unable to recognize \"/home/ec2-user/cert-manager/charts/webhook/templates/pki.yaml\": no matches for kind \"Issuer\" in version \"certmanager.k8s.io/v1alpha1\"\nunable to recognize \"/home/ec2-user/cert-manager/charts/webhook/templates/pki.yaml\": no matches for kind \"Certificate\" in version \"certmanager.k8s.io/v1alpha1\"\nunable to recognize \"/home/ec2-user/cert-manager/charts/webhook/templates/pki.yaml\": no matches for kind \"Issuer\" in version \"certmanager.k8s.io/v1alpha1\"\nunable to recognize \"/home/ec2-user/cert-manager/charts/webhook/templates/pki.yaml\": no matches for kind \"Certificate\" in version \"certmanager.k8s.io/v1alpha1\"\nerror validating \"/home/ec2-user/cert-manager/charts/webhook/templates/validating-webhook.yaml\": error validating data: [ValidationError(ValidatingWebhookConfiguration.webhooks[0].clientConfig): missing required field \"caBundle\" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig, ValidationError(ValidatingWebhookConfiguration.webhooks[1].clientConfig): missing required field \"caBundle\" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig, ValidationError(ValidatingWebhookConfiguration.webhooks[2].clientConfig): missing required field \"caBundle\" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig]; if you choose to ignore these errors, turn validation off with --validate=false", "stderr_lines": ["unable to recognize \"/home/ec2-user/cert-manager/charts/webhook/templates/pki.yaml\": no matches for kind \"Issuer\" in version \"certmanager.k8s.io/v1alpha1\"", "unable to recognize \"/home/ec2-user/cert-manager/charts/webhook/templates/pki.yaml\": no matches for kind \"Certificate\" in version \"certmanager.k8s.io/v1alpha1\"", "unable to recognize \"/home/ec2-user/cert-manager/charts/webhook/templates/pki.yaml\": no matches for kind \"Issuer\" in version \"certmanager.k8s.io/v1alpha1\"", "unable to recognize \"/home/ec2-user/cert-manager/charts/webhook/templates/pki.yaml\": no matches for kind \"Certificate\" in version \"certmanager.k8s.io/v1alpha1\"", "error validating \"/home/ec2-user/cert-manager/charts/webhook/templates/validating-webhook.yaml\": error validating data: [ValidationError(ValidatingWebhookConfiguration.webhooks[0].clientConfig): missing required field \"caBundle\" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig, ValidationError(ValidatingWebhookConfiguration.webhooks[1].clientConfig): missing required field \"caBundle\" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig, ValidationError(ValidatingWebhookConfiguration.webhooks[2].clientConfig): missing required field \"caBundle\" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig]; if you choose to ignore these errors, turn validation off with --validate=false"], "stdout": "apiservice.apiregistration.k8s.io/v1beta1.admission.certmanager.k8s.io created\ncronjob.batch/cert-manager-webhook-ca-sync created\njob.batch/cert-manager-webhook-ca-sync created\nconfigmap/cert-manager-webhook-ca-sync created\nserviceaccount/cert-manager-webhook-ca-sync created\nclusterrole.rbac.authorization.k8s.io/cert-manager-webhook-ca-sync created\nclusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook-ca-sync created\ndeployment.apps/cert-manager-webhook created\nclusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:auth-delegator created\nrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:webhook-authentication-reader created\nclusterrole.rbac.authorization.k8s.io/cert-manager-webhook:webhook-requester created\nservice/cert-manager-webhook created\nserviceaccount/cert-manager-webhook created\ncustomresourcedefinition.apiextensions.k8s.io/certificates.certmanager.k8s.io created\ncustomresourcedefinition.apiextensions.k8s.io/clusterissuers.certmanager.k8s.io created\ndeployment.apps/cert-manager created\ncustomresourcedefinition.apiextensions.k8s.io/issuers.certmanager.k8s.io created\nclusterrole.rbac.authorization.k8s.io/cert-manager created\nclusterrolebinding.rbac.authorization.k8s.io/cert-manager created\nserviceaccount/cert-manager created", "stdout_lines": ["apiservice.apiregistration.k8s.io/v1beta1.admission.certmanager.k8s.io created", "cronjob.batch/cert-manager-webhook-ca-sync created", "job.batch/cert-manager-webhook-ca-sync created", "configmap/cert-manager-webhook-ca-sync created", "serviceaccount/cert-manager-webhook-ca-sync created", "clusterrole.rbac.authorization.k8s.io/cert-manager-webhook-ca-sync created", "clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook-ca-sync created", "deployment.apps/cert-manager-webhook created", "clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:auth-delegator created", "rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:webhook-authentication-reader created", "clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:webhook-requester created", "service/cert-manager-webhook created", "serviceaccount/cert-manager-webhook created", "customresourcedefinition.apiextensions.k8s.io/certificates.certmanager.k8s.io created", "customresourcedefinition.apiextensions.k8s.io/clusterissuers.certmanager.k8s.io created", "deployment.apps/cert-manager created", "customresourcedefinition.apiextensions.k8s.io/issuers.certmanager.k8s.io created", "clusterrole.rbac.authorization.k8s.io/cert-manager created", "clusterrolebinding.rbac.authorization.k8s.io/cert-manager created", "serviceaccount/cert-manager created"]}
> 

the command 'kubectl -n cattle-system apply -R -f ./rancher' results in this:

> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl --kubeconfig=$(echo \"/home/ec2-user/kube_config_20190314-rancher02_rke_config.yml\") -n cattle-system apply -R -f ~/rancher", "delta": "0:00:00.397727", "end": "2019-03-14 20:32:17.150395", "msg": "non-zero return code", "rc": 1, "start": "2019-03-14 20:32:16.752668", "stderr": "error: error validating \"/home/ec2-user/rancher/tasks/main.yml\": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false", "stderr_lines": ["error: error validating \"/home/ec2-user/rancher/tasks/main.yml\": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false"], "stdout": "clusterrolebinding.rbac.authorization.k8s.io/rancher created\ndeployment.apps/rancher created\ningress.extensions/rancher created\nissuer.certmanager.k8s.io/rancher created\nservice/rancher created\nserviceaccount/rancher created", "stdout_lines": ["clusterrolebinding.rbac.authorization.k8s.io/rancher created", "deployment.apps/rancher created", "ingress.extensions/rancher created", "issuer.certmanager.k8s.io/rancher created", "service/rancher created", "serviceaccount/rancher created"]}
> 

If I turn off validation I simply get an json error, "cannot unmarshal array into Go value of type unstructured.detector".

**Comment by alena1108** [comment]
@scotthesterberg could you post Rancher version you are hitting the issue on.

**Comment by scotthesterberg** [comment]
This would be the latest stable rancher, which from my online install appears to be 2.1.7.

I have not tried kubectl 1.11, but I encountered this exact same issue running on a machine with kubectl 1.5 (against a kubernetes 1.11 cluster), so I doubt it is a kubectl issue. I can give it a try if it would help though.

**Comment by cjellick** [comment]
@jiaqiluo ever hit this error in your air gap testing? can you spot anything obviously wrong?

**Comment by scotthesterberg** [comment]
@alena1108 tried downgrading to kubectl 1.11, same error. Running kubectl from an Amazon linux 2 machine, against Redhat hosts configured by RKE.

**Comment by superseb** [comment]
There is no difference in airgap vs regular install besides the fetching archive and manually template and deploy in airgap vs that all automated in Helm/Tiller itself normally.

The first error still seems to refer to newer version being applied, as that needs custom CRDs before applying. Possibly the cluster was not cleaned/reset before re-applying? The second error seems to apply `rancher/tasks/main.yml` which is not in the chart itself, probably the playbook files.

If you can share the content of the files and reproduce using the commands/steps in https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/install-rancher/, let me know so we can reopen and investigate.
