### ISSUE TITLE
GlobalDNS: Make Global DNS Providers pluggable

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#18936]
Global DNS Provider support currently supports following providers from the https://github.com/kubernetes-incubator/external-dns project:

- AWS Route53
- CloudFlare
- AliDNS

We should make the Global DNS Provider framework pluggable, so that more providers or custom providers can be added without a requiring us to build new Rancher release.

**Comment by stefanlasiewski** [comment]
On-Prem customers need more options. Since Rancher only supports 3 commercial cloud-based DNS providers, and some on-prem customers cannot use cloud-based DNS, we are forced to roll our own.

I would really like to see more External DNS options supported by Rancher to help on-prem customers, such as the RFC 2136 (Bind) provider.

**Comment by rgroux** [comment]
It could be interesting to have the rfc2136 dns plugin.

Basicaly it s the most usable dns plugin for on prem rancher/k8s clusters.

**Comment by stefanlasiewski** [comment]
@rgroux FYI, I filed an RFE to request better support for the ExternalDNS RFC2136 provider here: https://github.com/rancher/rancher/issues/29870

**Comment by rgroux** [comment]
thanks

**Comment by kmpm** [comment]
This is still a thing that would be really good to have.

**Comment by kmpm** [comment]
This is still valid

**Comment by stefanlasiewski** [comment]
This is still needed, and is important for on-prem customers. Without this tight integration, on-prem customers need to build something on our own, which misses some of integration that Rancher provides.   I would really like to see Rancher support on-prem customers better.

**Comment by rgroux** [comment]
Hi,

I think it's still relevant and important. 

to be honest, I don t understand why the easyest  method (RFC2136) is not yet implmented

https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md

it s part or external dns features :(

**Comment by rgroux** [comment]
please do not forget this
