### ISSUE TITLE
Rancher 2.x UI allows creation of multiple projects with same name

### ISSUE THREAD

**Issue by vishnuvpotti** [rancher/rancher#18946]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Install Rancher 2.x 
2) Create Project .
3. Create project with same name as in Step 2.

**Result:**
Rancher UI allows creation of multiple projects with same names. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher version : v2.1.7

Screenshot : [https://imgur.com/a/SMVZCV9](url)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
1.13.1
```
(paste the output here)
```

**Comment by cjellick** [comment]
This is intentional. It’s designed to be multi-tenant. Tenant X shouldn’t be restricted to picking a project name that hasn’t been used by Tenants A-W.

**Comment by vishnuvpotti** [comment]
Ok. But should we allow to create in same cluster? Won't that be causing issues.
Even in multi tenant environment, no two teams have same project names.

**Comment by vincent99** [comment]
As Craig said, it is not unique and does not need to be; is just a display name.  Two unrelated groups can be sharing the same cluster and know nothing about each other.  Since projects don't "cost" anything, enforcing uniqueness just leads to early users claiming all the "good" names.
