### ISSUE TITLE
User can create pod run as root in K8s cluster v1.13.4 that enabled PSP RunAsNonRoot

### ISSUE THREAD

**Issue by canhnt** [rancher/rancher#18948]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
A k8s v1.13.4 cluster with enabled PSP via Rancher UI.
- PSP that aims to prevent running pods as root user:
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    serviceaccount.cluster.cattle.io/pod-security: mycloud
    serviceaccount.cluster.cattle.io/pod-security-version: "191456281"
  creationTimestamp: "2018-09-06T12:33:56Z"
  name: mycloud-psp
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
  defaultAllowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - nfs
  - persistentVolumeClaim
  - configMap
```
- Run the following command:
```
$ kubectl run -ti  my-busybox --image=busybox --restart=Never sh -n canh
```
**Result:**
- Expect: due to enforced PSP, the pod creation should fail.
- Actual: got the root shell command:
```
$ kubectl run -ti  my-busybox --image=busybox --restart=Never sh - canh

If you don't see a command prompt, try pressing enter.

/ # id
uid=0(root) gid=0(root) groups=10(wheel)
/ #
```

**Other details that may be helpful:**
- RoleBindings in current namespace (I deleted other default rolebindings prior creating above pod to isolate the issue)

```
$ kubectl get rolebinding -n canh
NAME                                 AGE
default-mycloud-clusterrole-binding   63d

$ kubectl get rolebinding default-mycloud-clusterrole-binding -n canh -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  name: default-mycloud-clusterrole-binding
  namespace: canh
  resourceVersion: "44254683"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/canh/rolebindings/default-mycloud-clusterrole-binding
  uid: 7573283b-14c2-11e9-9e62-005056b1e4b1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mycloud-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: canh
```

- The cluster role ` mycloud-clusterrole`:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 annotations:
   serviceaccount.cluster.cattle.io/pod-security: mycloud
 creationTimestamp: "2018-09-06T12:33:56Z"
 labels:
   creator.cattle.io/rancher-created: "true"
 name: mycloud-clusterrole
 resourceVersion: "15658599"
 selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/mycloud-clusterrole
 uid: 1ef88251-b1d1-11e8-a201-005056b1e4b1
rules:
- apiGroups:
 - extensions
 resourceNames:
 - mycloud-psp
 resources:
 - podsecuritypolicies
 verbs:
 - use
```

- Verified that PSP was enabled in kube-apiserver:
```
# docker inspect kube-apiserver  | grep 'enable-admission-plugins'
            "--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,PodSecurityPolicy",
                "--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,PodSecurityPolicy",
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher v2.1.17
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs, 10core, 72GB
- Kubernetes version (use `kubectl version`): 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by canhnt** [comment]
I cannot produce above bug in the other cluster running k8s v1.12.6, v1.12.3.

**Comment by canhnt** [comment]
Update: I've tested on a clean k8s cluster v1.13.4 created by kubeadm and cannot reproduce the bug.

Some observations:
- kube-apiserver:
```
# docker images | grep kube-apiserver
k8s.gcr.io/kube-apiserver            v1.13.4             fc3801f0fc54        3 weeks ago         181MB

# docker inspect k8s_kube-apiserver_kube-apiserver-k8s-master_kube-system_7256643a384d3ea77fa7a5f65dbc0ad9_0 | grep Image
        "Image": "sha256:fc3801f0fc5405d3c1ec02e7ed6f2fed84a8e4e22d3ef9583fcc67fd29878efe",
            "Image": "sha256:fc3801f0fc5405d3c1ec02e7ed6f2fed84a8e4e22d3ef9583fcc67fd29878efe",
```

- PSP admission controller was enabled:
```
# docker inspect k8s_kube-apiserver_kube-apiserver-k8s-master_kube-system_7256643a384d3ea77fa7a5f65dbc0ad9_0 | grep admission
            "--enable-admission-plugins=NodeRestriction,PodSecurityPolicy",
                "--enable-admission-plugins=NodeRestriction,PodSecurityPolicy",
```

- Execute `kubectl run -ti  my-busybox --image=busybox --restart=Never sh -n canh` stuck:
```
$ kubectl get pod -n canh
NAME                           READY   STATUS                       RESTARTS   AGE
my-busybox                     0/1     CreateContainerConfigError   0          7m44s
my-netutils-7f998dc698-vvjmd   0/1     CreateContainerConfigError   0          8m13s

$ kubectl describe pod my-busybox -n canh
...

  Normal   Scheduled  8m27s                   default-scheduler  Successfully assigned canh/my-busybox to node-1
  Normal   Pulled     6m48s (x8 over 8m24s)   kubelet, node-1    Successfully pulled image "busybox"
  Warning  Failed     6m48s (x8 over 8m24s)   kubelet, node-1    Error: container has runAsNonRoot and image will run as root
  Normal   Pulling    3m21s (x22 over 8m27s)  kubelet, node-1    pulling image "busybox"
```

**Comment by cjellick** [comment]
I have a theory on what is happening. Here it is:

1. You ran that `kubectl run` command as a "cluster owner" (i.e. someone who has the been granted the cluster-admin role)
2. You have another PSP in that cluster that is more permissive (can confirm via `kubectl get psp`)
3. As a cluster owner, you have permissions to all resources, including that more permissive psp. So, when you create a pod directly, the kubernetes sees that you have proper access to the permissive PSP and thus allows you to create the pod.


Can you see if that checks out and let me know?

**Comment by canhnt** [comment]
@cjellick : Thanks for your comment.

I create both users: admin (the user I used in the first post) and project-member, then do the test `kubectl run -ti my-busybox --image=busybox --restart=Never` with below scenarios:

1. k8s v1.12.3 or v1.12.6: for both admin and member users, the pod cannot be created with error `CreateContainerConfigError`, the annotation in the pod in both cases is `kubernetes.io/psp: default-psp`.

2. k8s v1.13.4: 
-  project-member user: Annotation: `kubernetes.io/psp: mycloud-psp`, error: `Error: container has runAsNonRoot and image will run as root`
- admin user: `kubernetes.io/psp: default-psp`, no error, can create pod running as root

So your guess is correct with k8s v1.13.4. It's good that the limited-user cannot create pod running as root.

However it's not clear to me why k8s v1.12.x can prevent admin running pod as root, but k8s-v1.13.4 cannot.

**Comment by cjellick** [comment]
My guess is simply that through some other situation, the v1.12 cluster does not have a permissive PSP in in it. If you do `kubectl get psp` in the 1.12 cluster, what all is listed?

**Comment by cjellick** [comment]
Rancher only deletes PSPs when the PSP Template that exists in the Rancher Global level is deleted and even then only if no projects are referncing it in the cluster.
So, a few things could have got you into this situation:
1. You currently have or previously had at least 1 project in the cluster referencing the permissive PSP.
2. Outside of Rancher, someone created a permissive PSP in the cluster that is completely unmanaged by Rancher.

FWIW, a cluster-admin has fully control in the cluster, so even if Rancher deleted the PSP, there's nothing to stop a cluster-admin from creating a new PSP and quickly and easily getting root access once again.

**Comment by canhnt** [comment]
> My guess is simply that through some other situation, the v1.12 cluster does not have a permissive PSP in in it. If you do `kubectl get psp` in the 1.12 cluster, what all is listed?

The 1.12.x clusters and 1.13.4 cluster both have the same list of PSP we defined via rancher server. So `kubectl get psp` in these clusters return the same 4-5 PSPs.

**Comment by cjellick** [comment]
@canhnt should I close this issue then? Seems like we figured out what the root of the problem was then?

**Comment by canhnt** [comment]
Thanks for your support. I think the issue can be closed.
