### ISSUE TITLE
Toleration value is not quoted in Helm Charts

### ISSUE THREAD

**Issue by solovyevt** [rancher/rancher#18952]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Add Rook Helm repository (stable) as a catalog: https://charts.rook.io/stable
2. Deploy rook-ceph chart with suggested tolerations:

```
tolerations:
    - 
      effect: "NoSchedule"
      key: "ceph-system"
      operator: "Equal"
      value: "true"
```

**Result:**
Rancher throws an error during the deployment:
```
"message": "failed to install app rook-ceph-ltrsl. Error: release rook-ceph-ltrsl failed: Deployment in version \"v1beta1\" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Tolerations: []v1.Toleration: v1.Toleration.Value: ReadString: expects \" or n, but found t, error found in #10   byte of ...|,\"value\":true}]}}}}\n|..., bigger context ...|\",\"key\":\"ceph-system\",\"operator\":\"Equal\",\"value\":true}]}}}}\n|...\n",
```

**Other details that may be helpful:**

The error seems to be related with answer quotations. The error explicitly shows that all  key:value pairs in tolerations array are updated with quotes except for the  **value: true**, even though it is quoted in the YAML view. In the Form View all answers are provided without any quotations. e.g. **tolerations[0].value: true** 
![Screenshot from 2019-03-15 13-48-20](https://user-images.githubusercontent.com/7433083/54432693-2ff08080-472a-11e9-9ee9-a90dc66d071d.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.7
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal, 3 machines, 256 GB RAM each
- Kubernetes version (use `kubectl version`):  

```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 

```
Docker version 18.09.3
```

**Comment by cjellick** [comment]
This might be fixed by some changes to answer processing coming in 2.2
