### ISSUE TITLE
DNS resolution fails to upgraded services

### ISSUE THREAD

**Issue by tomasbartalos** [rancher/rancher#18950]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create 2 services - Master and Worker, both services with scale 2 (total 4 containers).
Service Master is executing ping to both Worker container instances in a loop - spark-test-worker-1, spark-test-worker-2
```
	ping -w 4 spark-test-worker-1
	ping -w 4 spark-test-worker-2
```

Upgrade the Worker service (just confirm upgrade without any change) and leave it in **Upgraded** state. The upgrade will result in 2 stopped Worker containers and 2 newly started Worker containers.

**Result:**
DNS resolving mismatch. Container **master-1**  is resolving to IP of stopped worker container **worker-1** (10.42.102.53) while **master-2** is resolving correct IP of **worker-1** (10.42.24.206). 

**Other details that may be helpful:**
**MASTER-1 Logs**
Ping master-1 -> worker-1 (IP changed *.53 -> *.206) - Resolves to stopped container
```
[root@dranch3] ~ # docker logs r-spark-test-master-1-fd895a1d | grep PING | grep worker-1 | uniq -c
     20 PING spark-test-worker-1.rancher.internal (10.42.102.53) 56(84) bytes of data.
      1 PING spark-test-worker-1.rancher.internal (10.42.24.206) 56(84) bytes of data. # Resolved to newly started container
     26 PING spark-test-worker-1.rancher.internal (10.42.102.53) 56(84) bytes of data. # **DNS rollback to stopped container**
```

Ping master-1 -> to worker-2 (IP changed *.59 -> *.221)  - All Good
```
[root@dranch3] ~ # docker logs r-spark-test-master-1-fd895a1d | grep PING | grep worker-2 | uniq -c
     97 PING spark-test-worker-2.rancher.internal (10.42.10.59) 56(84) bytes of data.
     29 PING spark-test-worker-2.rancher.internal (10.42.110.221) 56(84) bytes of data.
```

**MASTER-2 Logs**

Ping master-2 -> worker-1 (IP changed *.53 -> *.206) - Correct
```
[root@dranch2] ~ # docker logs r-spark-test-master-2-24df0087 | grep "PING.*worker-1" | uniq -c
     89 PING spark-test-worker-1.rancher.internal (10.42.102.53) 56(84) bytes of data.
     24 PING spark-test-worker-1.rancher.internal (10.42.24.206) 56(84) bytes of data. # Resolved newly started container and didn't rollback as MASTER-1
```

Ping master-2 -> worker-2 (IP changed *.59 -> *.221) - Correct
```
[root@dranch2] ~ # docker logs r-spark-test-master-2-24df0087 | grep "PING.*worker-2" | uniq -c
     18 PING spark-test-worker-2.rancher.internal (10.42.10.59) 56(84) bytes of data.
     27 PING spark-test-worker-2.rancher.internal (10.42.110.221) 56(84) bytes of data.
```
**Workaround**
When upgrade is finished with "Finish Upgrade" button, the stopped worker containers are removed and the DNS resolution gets fixed.
Problem of the workaround is that we need to finish upgrade to get into working state and we're loosing the rollback option.

**Environment information**
- Rancher version: 1.6.21
- Installation option: single install

- Docker version (use `docker version`):
```
Docker version 18.09.0, build 4d60db4
```

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
