### ISSUE TITLE
Enable rolling upgrade after validating correctness of image and successful pull from registry

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1895]
During rolling upgrade, if some syntax is wrong (wrong image name for new service), link is getting created, old service is stuck in UPGRADING status and new service is stuck in UPDATING-ACTIVE status for ever. Can we do a check if image is valid and can be pulled even before trying upgrade?

<img width="1368" alt="screen shot 2015-08-26 at 9 36 14 am" src="https://cloud.githubusercontent.com/assets/7720752/9509539/be953e84-4c15-11e5-9e0b-fb7360e4a230.png">

**Comment by nhumrich** [comment]
I ran into this issue as well
