### ISSUE TITLE
Missing Region For adding existing AKS cluster

### ISSUE THREAD

**Issue by kasunsjc** [rancher/rancher#18951]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement or Bug 

**Steps to reproduce (least amount of steps as possible):**
Adding existing AKS cluster. Southeast Asia is not available for location selector

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```
![image](https://user-images.githubusercontent.com/16514562/54427514-b617c180-4740-11e9-98cf-e6306cd46d82.png)

**Comment by superseb** [comment]
This was added in https://github.com/rancher/rancher/issues/17054 and will be in the next release
