### ISSUE TITLE
Multicast Support

### ISSUE THREAD

**Issue by adalga** [rancher/rancher#18953]
I have rancher cluster with Canal Network Provider. I have an application which needs multicast network support. I have done some research and found that Weave is providing multicast support. Is Canal also providing this? If not is there a way to change my network provider with Weave? 

My Rancher version: v2.1.2
Bare Metal Ubuntu 16.04 host
Kubernetes version: v1.12.1
Docker version:17.03.2

**Comment by alena1108** [comment]
@adalga Weave CNI driver support will be added as a part of Rancher 2.2. Please refer to this ticket for more info: https://github.com/rancher/rancher/issues/12909

**Comment by adalga** [comment]
@alena1108 I saw that and I wonder if I would be able to switch my CNI provider with Weave. Would I ?
