### ISSUE TITLE
UI - When trying to addProjects to a GDNS entry which has projects the user does not have access to , the project gets removed from the GDNS entry. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18954]
Rancher server version - Build from master - Mar 14

Steps to reproduce the problem:
Create a DO cluster - mytest1 with following projects:

test1 -> user1 is NOT a project member
test2 -> user2 is project member
test3 -> user2 is project member

Create a GDNS entry with project targets as test1 and test2 and add user2 as owner.
Log in as "user2"

GDNS entry shows project it does not have access to  - test1 as not a link which is expected,
 
<img width="1043" alt="Screen Shot 2019-03-15 at 8 18 11 AM" src="https://user-images.githubusercontent.com/4266958/54442361-c0fc3300-46fb-11e9-9022-b949f01f1a4c.png">

In Edit GDNS entry page , test1 is not presented at all.
<img width="1042" alt="Screen Shot 2019-03-15 at 8 18 21 AM" src="https://user-images.githubusercontent.com/4266958/54442568-159fae00-46fc-11e9-9770-26bbb838c268.png">

Try to add "test3" project and "save".

GDNS entry gets created with project test2 and test3 . test1 is removed.
UI sends a removeProject action for "test1" which should not be the case.

Expected Behavior:
UI should be able to present "test1" in the edit view.
UI should not send a removeProject action for "test1".

**Comment by sangeethah** [comment]
Tested with latest build from master:

Steps to reproduce the problem:
Create a DO cluster - mytest1 with following projects:

test1 -> user1 is NOT a project member
test2 -> user2 is project member
test3 -> user2 is project member

Create a GDNS entry with project targets as test1 and test2 and add user2 as owner.
Log in as "user2"

GDNS entry shows project it does not have access to - test1 as not a link which is expected.
Edit GDNS entry  and add project "test3".

GDNS entry gets associated with 3 projects - test1, test2 and test3 as expected.

**Comment by davidnuzik** [comment]
Validated again in HA setup v2.2.0-rc8 as requested by Sangeetha.
I can confirm this is still working as expected. user2 "sees" project 1 (doesn't have access but still listed). removeProject action does not happen. Login as admin again and verify all three test projects are still listed in that view as well.
