### ISSUE TITLE
%pagination.member% shows up when pick 1 project from GDNS Target projects drop-down

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18967]
Version: Master 2.2 (3/15/19) 21d45c0f8e83 **w/ --add-local=true flag**

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add ONE project from the Target Projects drop down under GDNS entry.
Notice, %pagination.member% shows up.

**Result:**
This is similar to #18373 which was closed because this was removed from MC app creation/upgrade page.

**Comment by westlywright** [comment]
@davidnuzik when you see this do you see any console messages (errors/warning/logs) about translations not being found?

**Comment by davidnuzik** [comment]
@westlywright No, I just double-checked; no warnings about translation not found, etc.
![image](https://user-images.githubusercontent.com/45179589/54546152-5ef03780-4960-11e9-8887-51de70710f9d.png)

**Comment by westlywright** [comment]
is the ticket for seeing the translation missing text or seeing the pagination?

**Comment by davidnuzik** [comment]
It's for seeing the pagination. If I recall correctly, this was a bug in MCapp when we added the new projects drop-down. I think you mentioned you should only see it if we hit max table list per page or something. In this case I am reproducing what I found here but on GDNS Entries: #18373

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/18/19)
I am no longer able to reproduce the problem. %pagination.member% is no longer unnecessarily popping up when I pick a project from the target dropdown.
