### ISSUE TITLE
Metrics view on rancher UI units looks incorrect, out by few factors (rc6)

### ISSUE THREAD

**Issue by riaan53** [rancher/rancher#18962]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Setup a 3 node cluster and enable cluster level metrics on RC6.
2. Go to cluster metrics and node metrics on Rancher UI

**Result:**
1. Ingress controller avg response time is not 1000 seconds as show in graph.
<img width="897" alt="Screenshot 2019-03-16 at 00 30 23" src="https://user-images.githubusercontent.com/7716342/54465224-c355a000-4782-11e9-8cd8-ca4d5c2026a0.png">

2. Network IO and disk IO units shoud prob be Mbps like it was in alpha6.
Cluster view on UI:
<img width="838" alt="Screenshot 2019-03-16 at 00 31 16" src="https://user-images.githubusercontent.com/7716342/54465241-da948d80-4782-11e9-9092-47d334e17372.png">

<img width="1604" alt="Screenshot 2019-03-16 at 00 32 06" src="https://user-images.githubusercontent.com/7716342/54465256-f6982f00-4782-11e9-8bab-9fdd329034a2.png">

Note that is the same on the node view on Rancher UI.

**Other details that may be helpful:**
On alpha6 it looks like the units was correct.

**Environment information**
- RKE install on 3 node Digitalocean (3 x 8 GB / 4 CPUs)
- Followed Helm HA install guide
- Using weave for networking

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by alena1108** [comment]
@riaan53 could you elaborate on Rancher version?

**Comment by riaan53** [comment]
Hi @alena1108 ,

I used the latest RC build (rc6) to test out the new monitoring - looking forward to the release!

https://github.com/rancher/rancher/releases/tag/v2.2.0-rc6

I used the docker image: rancher/rancher:v2.2.0-rc6

**Comment by loganhz** [comment]
Unit issue has been fixed. The ingress metrics issue will be fixed in backend. https://github.com/rancher/rancher/pull/18970/files

**Comment by loganhz** [comment]
ingress metrics fix is also in. The response time should be correct now.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/16/19)
Confirmed issue.

Ingress controller time is fixed:
![image](https://user-images.githubusercontent.com/45179589/54484388-fa7b8e00-4822-11e9-986c-ff148018acf0.png)

Network IO and Disk IO are fixed as well:
![image](https://user-images.githubusercontent.com/45179589/54484403-42021a00-4823-11e9-9236-6ee934b81b36.png)
Node metrics are also correct.
