### ISSUE TITLE
Cannot upgrade GKE k8s version when perform HA upgrade from v2.1.7 to v2.2.0-rc6

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18966]
Version: Master 3/15/19 HA Setup

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a v2.1.7 HA setup rancher
- Create a GKE cluster with v1.11.7-gke.12
- Upgrade the HA set via rancher-latest helm repo verison 2.2.0-rc6:
`helm upgrade rancher rancher-latest/rancher --version 2.2.0-rc6 --namespace cattle-system --set hostname=<fqdn>`
Note, make sure you run `helm repo update` first to update repos if needed
- Post HA upgrade, try to edit the GKE cluster.

**Result:**
Notice, when you try to edit the GKE cluster after HA upgrade you cannot edit the k8s version. You should be able to change it to v1.12.5-gke.5 but there is no option in the rancher UI. 

**Other details that may be helpful:**
You _can_ upgrade to this version in the gcloud web console so we should support it in the rancher UI after upgrade to 2.2.0 rancher in single-node rancher and HA setup.

**Comment by cjellick** [comment]
Was this tested in non HA? Is gke k8s version upgrade supported in 2.1.x line?

**Comment by loganhz** [comment]
@cjellick yes, we need an UI fix for it

**Comment by davidnuzik** [comment]
Version: v2.1.7 -> Master 2.2 (3/16/19) upgrade
Confirmed issue. You can now upgrade the master k8s version in this situation post-upgrade.
![image](https://user-images.githubusercontent.com/45179589/54484226-462c3880-481f-11e9-99fe-a6401b2c86c0.png)
![image](https://user-images.githubusercontent.com/45179589/54484293-74f6de80-4820-11e9-8a66-02bfc2498fc2.png)
You cannot, however, also upgrade the nodes. This also does not work in existing v2.1.7 (pre-existing issue) and this issue tracks this problem: #18976 
![image](https://user-images.githubusercontent.com/45179589/54484301-a53e7d00-4820-11e9-8436-4e10ab60c2ce.png)

I confirmed that post-upgrade when I upgrade k8s this indeed upgrades the k8s master version per the gcloud console. HTTP/API looks good.
`masterVersion: "1.12.5-gke.5"`
