### ISSUE TITLE
Infinite restart loop of 'go-machine-service' after rancher server restart: Unable to create EventRouter

### ISSUE THREAD

**Issue by advanderveer** [rancher/rancher#1896]
I've got a basic rancher server running in a Docker container without any agent. The container is behind Nginx (for ssl termination) and an ELB. The MySQL database is hosted outside the docker container (AWS RDS). Upon starting the rancher server for the first everything goes perfect, but after a restart the `docker log` start to fill itself with the following:

```
10:32:40.219 [main] INFO  ConsoleStatus - [DONE ] [38553ms] Startup Succeeded, Listening on port 8081
time="2015-08-27T10:32:42Z" level=info msg="Starting websocket proxy. Listening on [:8080], Proxying to cattle API at [localhost:8081], Monitoring parent pid [9]." 
time="2015-08-27T10:32:42Z" level=info msg="Setting log level" logLevel=info 
time="2015-08-27T10:32:42Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-08-27T10:32:42Z" level=error msg="Unable to create EventRouter" Err="Bad response from [http://compute.nerdalize.com/v1], statusCode [401]. Status [401 Unauthorized]. Body: [{\"id\":\"31b0fdd3-4ac5-40e5-b785-84abdf49841f\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":401,\"code\":\"Unauthorized\",\"message\":\"Unauthorized\",\"detail\":null}]" 
time="2015-08-27T10:32:42Z" level=info msg="Exiting go-machine-service..." 
time="2015-08-27T10:32:44Z" level=info msg="Setting log level" logLevel=info 
time="2015-08-27T10:32:44Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-08-27T10:32:44Z" level=error msg="Unable to create EventRouter" Err="Bad response from [http://compute.nerdalize.com/v1], statusCode [401]. Status [401 Unauthorized]. Body: [{\"id\":\"eef70715-1097-4cc7-a90c-ffccc3cecfe3\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":401,\"code\":\"Unauthorized\",\"message\":\"Unauthorized\",\"detail\":null}]" 
time="2015-08-27T10:32:44Z" level=info msg="Exiting go-machine-service..." 
time="2015-08-27T10:32:46Z" level=info msg="Setting log level" logLevel=info 
time="2015-08-27T10:32:46Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-08-27T10:32:46Z" level=error msg="Unable to create EventRouter" Err="Bad response from [http://compute.nerdalize.com/v1], statusCode [401]. Status [401 Unauthorized]. Body: [{\"id\":\"540d85a5-4f13-4c5a-a10a-f7768816c17c\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":401,\"code\":\"Unauthorized\",\"message\":\"Unauthorized\",\"detail\":null}]" 

etc...
```
I've attempted to upgrade to 0.35.0-rc2 but this didn't change the situation.  I would like to get some assistance with this issue.

**Comment by cjellick** [comment]
@advanderveer What does your auth setup look like for this deployment? Is it turned on? Using github?

**Comment by cjellick** [comment]
Also, is the a brand new install or has it been around for awhile and through a few upgraades?

**Comment by cjellick** [comment]
I ask this because the logs indicate that go-machine-service cannot auth to rancher. It auths with api keys that we generate in the api server and send to go-machine-service when we start it. So, it is odd that those keys are invalid.

**Comment by cjellick** [comment]
One more question: what value is set for your Host Registration? You can access it from the dropdown in the top right.

**Comment by advanderveer** [comment]
Woah, let me see:

- Auth is configured through the very first "Settings" link when just launching a fresh rancher server and uses GitHub
- When I do a fresh install of 0.34 (without an external database) I get a log of warnings like this: 

  `modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case ` but afterwards it continues to boot up correctly without the error mentioned in my initial post. If I then ask docker compose to restart the rancher server it will work without errors as well. If I enable auth through the settings link, use my github tokens and press save the error message will start to appear after a few seconds in my Docker logs. 

- When Going to the Host Registration menu (didn't knew about this option!) and follow the instructions about ssl termination (for us this is done by nginx on the docker host) and use the https:// suggestion the error disappears but is replaced by:

```
level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="wss://compute.nerdalize.com/v1/subscribe?eventNames=physicalhost.remove%3Bhandler%3DgoMachineService&eventNames=ping%3Bhandler%3DgoMachineService&eventNames=physicalhost.create%3Bhandler%3DgoMachineService&eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService" 
```

**Comment by advanderveer** [comment]
Configuring my Nginx proxy to deal with websockets made the 'bad handshake' error go away. And effectively solved the problem for me. I'll close the issue, but feel free the ask any other questions!

Thanks for the help!

**Comment by cjellick** [comment]
Glad to hear you were able to solve the problem.
