### ISSUE TITLE
How the features "redeploy" implementation?

### ISSUE THREAD

**Issue by 8427003** [rancher/rancher#18972]
**What kind of request is this (question):**
How the features "redeploy" implementation. someboy know?

**Comment by cjellick** [comment]
What specifically do you want to know or are you curious about?

**Comment by 8427003** [comment]
@cjellick 
![image](https://user-images.githubusercontent.com/5475231/54478645-83102380-484f-11e9-8fcf-cbb146335fb8.png)
the features "redeploy" deployment: it keeps the "deployment"  not recreated,  create new pods, then delete then old one. it's so cool. how to trigger the action.
how to do it  if using `kubectl apply -f ...` ? (Do you understand what I said, my English is poor)

**Comment by vincent99** [comment]
All it does is set an annotation with the value as the current time.  This causes there to be a difference which requires replacing the pods.  Beyond that it doesn't matter what the difference is, k8s does the redeployment according to the policies configured on the workload.

**Comment by loganhz** [comment]
Related code https://github.com/rancher/ui/blob/38c876e7636ee583a8630d921ce9addbc390f6ed/app/models/workload.js#L283

https://github.com/rancher/ui/blob/38c876e7636ee583a8630d921ce9addbc390f6ed/app/models/workload.js#L321-L330
