### ISSUE TITLE
Two error boxes are shown during restore to a S3 backup when local backup is configured

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18975]
Version: Master from March 16th

Steps:

Create a cluster with S3 backup config
Create few backups B1, B2
Edit and change to local backup config
Perform a restore to B1 which is a S3 backup

After restore, error is shown as expected, but two error boxes are shown as below:

<img width="1236" alt="Screen Shot 2019-03-16 at 2 12 03 PM" src="https://user-images.githubusercontent.com/18536626/54481825-10735980-47f7-11e9-9b12-e38f77dbe5fb.png">

There should be only one clean error box presented in UI.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/16/19)
Confirmed issue.
Follow the steps to reproduce. When you switch the cluster to local etcd backup method, try to restore B1 (s3) and now you only get one error message in the UI:

![image](https://user-images.githubusercontent.com/45179589/54484490-4e877200-4825-11e9-82f2-65c4faff214d.png)
