### ISSUE TITLE
Support upgrade node k8s version for GKE

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18976]
rancher/rancher:2.1.7

Users can only upgrade GKE master k8s version in Rancher UI.
Users cannot upgrade node k8s version of GKE in Rancher UI

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/18966

**Comment by davidnuzik** [comment]
If can be fixed / low risk should get in v2.2 otherwise we'll need to add a warning in the UI explaining that we do not currently support upgrade node k8s version post-upgrade of rancher and that only the master k8s version will be updated.

**Comment by loganhz** [comment]
@davidnuzik 
Just tried to upgrade node version in GKE.
upgrading node version means delete and recreate nodes. 
It's kind of a dangerous operation.
Maybe we need to think about the UX a bit more.
So I would like to leave it as-is. I will add a warning in UI. 

Could you provide the position and the content for the warning message, please?
Maybe we need to file another issue instead of using this one for warning message?

**Comment by davidnuzik** [comment]
@loganhz I will create a separate issue for the UI warning message and suggest content for it.
I understand the concern regarding upgrading nodes.
