### ISSUE TITLE
Grafana monitoring does not show that a node is down and the node count gets messed up (v2.2.0-rc6)

### ISSUE THREAD

**Issue by riaan53** [rancher/rancher#18971]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1 .Setup a 3 node cluster (etcd, controlplane and worker on all) and enable cluster level metrics on RC6.
2. Go to cluster metrics Rancher UI and open Grafana view to show the node count
3. Shut down a node
4. Wait until k8s settle
5. Make sure all components are healthy apart from the node being down
6. Note the node count and node down count on Grafana (a refresh does not fix it)

**Result:**
<img width="1279" alt="Screenshot 2019-03-16 at 14 25 10" src="https://user-images.githubusercontent.com/7716342/54475206-5f20f380-47f7-11e9-866d-8f1c214fd916.png">
<img width="1589" alt="Screenshot 2019-03-16 at 14 22 37" src="https://user-images.githubusercontent.com/7716342/54475203-59c3a900-47f7-11e9-9e5a-5f8f33b8d9cd.png">
<img width="1625" alt="Screenshot 2019-03-16 at 13 59 40" src="https://user-images.githubusercontent.com/7716342/54475167-dd30ca80-47f6-11e9-8ebd-3c3dba4b0e93.png">
<img width="1579" alt="Screenshot 2019-03-16 at 14 21 23" src="https://user-images.githubusercontent.com/7716342/54475168-df932480-47f6-11e9-964a-3842e624abad.png">

**Environment information**
- RKE install on 3 node Digitalocean (3 x 8 GB / 4 CPUs)
- Followed Helm HA install guide (except using rancher/rancher:v2.2.0-rc6 image)
- Using weave for networking
- Rancher RC6 (rancher/rancher:v2.2.0-rc6)

**Cluster information**
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thxCode** [comment]
@riaan53 
- The expression of "Number of Nodes" is `sum(kube_node_info{node=~"$Node"})`
- The expression of "Nodes Unavailable" is `sum(kube_node_spec_unschedulable{node=~"$Node"})`

The [`kube_node_info`](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/node-metrics.md) describes the real information of the Kubernetes Nodes resources, which means this is simialr to count(`kubectl get nodes`), so I am not sure why the reading of the graph is so strange. 

The [`kube_node_spec_unschedulable`](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/node-metrics.md) describes the unschedulable Kubernetes Nodes, an unschedulable Node has been marked as unschedulable via [`kubectl cordon $NODENAME`](https://kubernetes.io/docs/concepts/architecture/nodes/#manual-node-administration), so I think this cannot show you "a node is down".

In fact, from the Rancher Nodes page, you could know which node is down, is this not enough? 

If you really need to know which node is down on the Grafana, you can add a dashboard with `sum(kube_node_status_condition{condition="Ready", status!="true"}) by (instance)`.

**Comment by riaan53** [comment]
Hi @thxCode ,

Thx for the feedback. I was looking at it from a pure monitoring side, to see if by looking only at the cluster page on Grafana our ops team would be able to hint what is wrong without having to look at the Rancher UI nodes page as well. Currently if a node goes down (dont need to know which one) the cluster page on Grafana does not indicate that (but can be added manually like you said). The naming is a bit misleading as `unavailable` hints to a `not ready` node status. If it was named `unschedulable` then just cordon makes more sense as it is now. Dont need to change it, im just trying to give some input from an outside perspective :) Thank you.

**Comment by riaan53** [comment]
Just noticed that the status on Rancher UI is also `unavailable` when a node goes down or `not ready`, so it will def cause some confusion.
