### ISSUE TITLE
random AD integrated users unable to log in

### ISSUE THREAD

**Issue by JohnnyElvis** [rancher/rancher#18987]
Details: Rancher 2.1.7, AD "classic" and AD Azure affected

Random users are unable to log in to Rancher via UI or kubectl after random time period. After removing the login on Rancher side users can log in again

**Comment by deniseschannon** [comment]
What do you mean by "removing login on Rancher side"? How are you removing login for users?

**Comment by JohnnyElvis** [comment]
We have to remove the user via WevUI: Global => Users => <username> => 3 dots => delete
