### ISSUE TITLE
Not all published ports are getting exposed

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#1898]
This could be environment specific, and it has been very reproducible in that environment.  I was unable to reproduce on a fresh installation of Rancher.

Issue:
Deploying a [stack](https://github.com/rancher/compose-templates/blob/master/logstash/docker-compose.yml) The published ports are not exposed on the host. Looking at the iptables rules the first port is exposed, but the second is not. Creating a single container with a published port causes all of the ports to be exposed and functional.

**Comment by ebuildy** [comment]
I believe I have this problem too, I publish port 80 as 8080:

![rancher]
(https://beemapp.s3-eu-west-1.amazonaws.com/5a9df9dc-4df2-43b3-8f2d-a59877020227.jpg)

But on **docker ps** I don't see the port translation:

![docker ps]
(https://beemapp.s3-eu-west-1.amazonaws.com/1ae657e4-eecd-459e-be2c-5546595d7886.jpg)

Strange thing is I can access to it from **outside the Docker host**:

````
admin@stream-2:~$ curl stream-1.*****.com = OK
admin@stream-1:~$ curl stream-1.*****.com = Connection refused
````

It looks like Rancher didn't pass the port settings to Docker.

**Comment by cloudnautique** [comment]
@ebuildy, rancher manages the ports, and they will not show up in docker. In order to verify you need to do `iptables -L -t nat` and you should see the ports being handled there.

**Comment by vincent99** [comment]
@ebuildy Different issue...

The public ports are never show in `docker ps` because they can be dynamically changed in Rancher but we can't change the output of Docker to match.  So the port is exposed, but your issue is that "Hairpin NAT" is not currently supported.

This is where you're making a request from the host to the public IP of itself back to itself.  There's just not a rule in iptables to handle that.

**Comment by ebuildy** [comment]
Haaa ok, sorry for bother you for that, didn't check with the right iptables command.. 

So the Rancher agent is in charge of managing this on each host?

You said **they can be dynamically changed in Rancher**, how?

Thanks you very much,

**Comment by vincent99** [comment]
If using the "managed" networking (which is the default), yes.  You can click the edit action on a container and change the public port bound to each container port.

**Comment by ebuildy** [comment]
Sometimes ports are not well exposed, I have to restart container to expose all ports:

![]
(http://b3.ms/raNnPVd89bXP)

Here I have the same stacks running on 2 hosts, port 843 is not exposed on the second, if I restart the container, the port is exposed fine.

Note: I have this problem after cloned service, delete original and start new one.

**Comment by ibuildthecloud** [comment]
@cloudnautique Do you have a reproducible failing test case?  If so I could quickly fix this I'm sure.

**Comment by andrepinto** [comment]
@ebuildy I have the same issue, when I restart the container for the first time both ports are exposed fine, but when a I restart again, only the first port is exposed.

**Comment by cjellick** [comment]
@ebuildy This happens consistently? Is the container part of a service? Does it have a sidekick? Do you have a compose yaml that you'd be able to share so that we could try to reproduce?

**Comment by ebuildy** [comment]
Yes it's happen all the time I remove then create new containers of a service. Then if I restart new created container, I can see the ports opened.

**Comment by kevin-thorpe** [comment]
I am having exactly this problem and very reproducible. Only one port of any container is ever exposed.

Docker hosts are CentOS-7 and are running Docker 1.7.1, build 3043001/1.7.1 if that helps.

**Comment by will-chan** [comment]
@sangeethah can we try to reproduce this in-house?

**Comment by ibuildthecloud** [comment]
The problem with this issue is that there is plenty of reasons why a port might not be accessible due to environmental issues (such has bad security group configuration) or user error.  To really proceed forward on this issue we need some reproducible tests case.

**Comment by cloudnautique** [comment]
I don't disagree. The issue I saw had incomplete iptables rules. When doing an iptables -L -t nat the port was missing. Adding another container forced a config load and things worked. I haven't seen it since reporting the issue.

**Comment by kevin-thorpe** [comment]
This was completely reproducible on my setup. Just to be annoying though I tried several times today and all is working as it should. I did attempt to upgrade from Rancher 0.35 to 0.39 (with errors as mentioned in the forum) so maybe that updated something on the hosts.

**Comment by deniseschannon** [comment]
This might be related to https://github.com/rancher/rancher/issues/1730

**Comment by kevin-thorpe** [comment]
Back to this one again. Upgraded to Docker 1.8.3 and now on Rancher 0.42 all running on CentOS 7. This is still very reproducible to me. As a quick test:
mongodb:
  ports:
  - 27017:27017/tcp
  - 8001:8001/tcp
  - 8002:8002/tcp
  - 9000:9000/tcp
  - 9001:9001/tcp
  image: mongo
When starting this service only the proper port 27017 is open in iptables:
Chain CATTLE_PREROUTING (1 references)
target     prot opt source               destination
DNAT       udp  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL udp dpt:ipsec-nat-t to:10.42.187.164:4500
DNAT       udp  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL udp dpt:isakmp to:10.42.187.164:500
DNAT       tcp  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL tcp dpt:peerwire to:10.42.15.112:9104
DNAT       tcp  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL tcp dpt:8761 to:10.42.247.183:8761
DNAT       tcp  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL tcp dpt:27017 to:10.42.50.22:27017
After restarting the service they *mostly* appear:
Chain CATTLE_PREROUTING (1 references)
target     prot opt source               destination
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL udp dpt:4500 to:10.42.187.164:4500
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL udp dpt:500 to:10.42.187.164:500
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:9104 to:10.42.15.112:9104
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:8761 to:10.42.247.183:8761
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:27017 to:10.42.50.22:27017
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:8001 to:10.42.50.22:8001
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:8002 to:10.42.50.22:8002
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:9000 to:10.42.50.22:9000

**Comment by jest** [comment]
Same for me. Using stack imported from `docker-compose.yml` (https://gist.github.com/jest/7ffd79833865b10d2909) I can see that port 10022 is being published, while 10080 is not.

```
Chain CATTLE_PREROUTING (1 references)
target     prot opt source               destination         
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL udp dpt:4500 to:10.42.204.93:4500
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL udp dpt:500 to:10.42.204.93:500
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:10022 to:10.42.248.59:22
```

The UI shows both 10022 and 10080 as published.

Rancher v0.42, Docker 1.8.3.

**Comment by ebuildy** [comment]
I never  see  this bug fixed, it happens sometimes when i remove /
re-create containers.

UI says no  error but ports are not mapped.
Le 27 oct. 2015 5:19 PM, "Przemek Wesołek" <notifications@github.com> a
écrit :

**Comment by jest** [comment]
Removing and re-creating container doesn't help (at least not in last 5 times I tried)

**Comment by ebuildy** [comment]
You have to restart it, this will  run the  Rancher networking process at
the  end.
Le 28 oct. 2015 9:44 AM, "Przemek Wesołek" <notifications@github.com> a
écrit :

**Comment by kevin-thorpe** [comment]
Restarting doesn't always work. Some ports may still not be connected after the restart. In any case that's not a workable option as we're trying to do automated deployment and scaling so there isn't always going to be someone there,

**Comment by ebuildy** [comment]
Absolutely agree  , this makes impossible automatic deploy.

Also i dont like  the  fact that Rancher manages ports whereas Docker can
do that very  well.
Le 28 oct. 2015 11:00 AM, "kevin-thorpe" <notifications@github.com> a
écrit :

**Comment by cloudnautique** [comment]
Try adding another container to the host. It sounds odd, but the entire network config is supposed to be reloaded.

**Comment by ibuildthecloud** [comment]
I'm so sorry this hasn't been fixed. I will resolve this.  Don't give up on me yet 🙏

The reason we manage the ports and not docker is that docker can't dynamically change the port mapping.  If they could we wouldn't do this.

I've misread this issue in the past.  I didn't realize the issue was related to multiple ports.  That gives me something to work with.

Again, I'm sorry this has taken so long to resolve.

**Comment by ibuildthecloud** [comment]
@cloudnautique was able to reproduce this for me.  I'll get a fix in, probably won't make it for v0.44 but for sure v0.45.

**Comment by kevin-thorpe** [comment]
Great, at least we have a timescale now. The unreproducible ones are always
annoying.

**Comment by MhdAli** [comment]
I'm having the same issue here, note that only one port is mapped on iptables the rest isn't mapping.

**Comment by kevin-thorpe** [comment]
From earlier correspondence Darren now can reproduce and is aiming to fix
by 0.45

**Comment by sangeethah** [comment]
Tested with latest build from master - Nov 13

Created a service with 11 exposed ports.
Once the service is activated and started , we see all 11 exposed ports being programmed in the iptables of the host. Verified that all these ports are accessible.

Fix will be made available in the next release.

**Comment by kevin-thorpe** [comment]
Thank you.
