### ISSUE TITLE
Feature Request: Configure Auth Provider outside of the UI

### ISSUE THREAD

**Issue by tibers** [rancher/rancher#18988]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request. Similar to this one: https://github.com/rancher/rancher/issues/20 if I can setup my auth provider when spinning up a rancher cluster I don't have to worry about getting beaten to the punch to configure AD or similar.

Right now we can sort of do it with the pipeline and bringing up rancher and logging in with the default admin credentials, then getting the token, then squirting JSON in there but it seems like a long reach (and insecure) to hope that I'm the first one in there and complete all my pointy-clicky before someone else notices the pipeline has run. Or worse, someone spinning up a rancher docker container on their laptop to mess around with it might be exposed to someone else sending rancher the admin creds and doing goofy stuff. 

If we just gave us some sort of command line way of doing it (or a helm chart), that would be great.

**Comment by cjellick** [comment]
@rawmind0 can you share what you’ve done in our TF templates? Maybe that will meet his needs.

FWIW, it’s 100% api driven and scriptable.

**Comment by vincent99** [comment]
The public API is PUTting to `/v3/activeDirectoryConfigs/activedirectory`. (or others in `/v3/authConfigs`).

When you setup a new server the first step is to set the local admin password, regardless of what auth you ultimately want configured.  If you're not changing it then there's no point turning on other auth providers because anyone can use local with `admin/admin`.

**Comment by tibers** [comment]
I am setting a local admin password, but I want to turn on other auths in some easier way than squirting JSON at the API endpoint. I was hoping that rancher defined these as CRDs or something but that's not the case. Then I was hoping that I could add AD auth via the command line or RKE config.

**Comment by tibers** [comment]
https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-reset-the-admin-password This sort of scratches the itch. I still think it should be an option in RKE or on the initial spin up. :)

**Comment by vincent99** [comment]
2.6 sets a random initial password and has inputs to let you override that with one of your choosing.

The auth config is (and always has been) a CRD with CRs you can directly edit in the local cluster if you want to, after the server is up.  You would also need to setup the admin or other user with a principalId to tie them to the auth provider, if you're bypassing the API and the steps it does.
