### ISSUE TITLE
Empty rancher-secrets in UI after cleaning up secrets via SQL

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#18992]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
After running the following SQL query to resolve an issue. 
In the UI you see a number of blank areas which say "rancher-secrets" and "No Hosts".

SQL Query:
delete s from volume_storage_pool_map as s join (select id from volume as vv where vv.data like '%\"driver\":\"rancher-secrets\"%' and created < date_sub(utc_timestamp(), INTERVAL 1 HOUR) and vv.state = "detached" and vv.instance_id is NULL and id not in(select volume_id from mount as m where m.state != "removed" or m.state != "purged")) vx on vx.id = s.volume_id; 

delete v from volume as v join (select id from volume as vv where vv.data like '%\"driver\":\"rancher-secrets\"%' and created < date_sub(utc_timestamp(), INTERVAL 1 HOUR) and vv.state = "detached" and vv.instance_id is NULL and id not in(select volume_id from mount as m where m.state != "removed" or m.state != "purged")) vx on vx.id = v.id; 

**Result:**
![image](https://user-images.githubusercontent.com/17145893/54548258-7e458f80-4975-11e9-96d8-6287a1da6883.png)

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
