### ISSUE TITLE
When create Azure node template, dockerPort is 0 by default

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18993]
Version: Master 2.2 (3/18/19) 022651b0ec13
Version: v2.2.0-rc6

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an Azure node template. Look at the docker port number

**Result:**
The Docker Port number is 0 by default. If you submit the node template with this default setting, it's indeed sent via http `dockerPort: 0` and azure cluster provisioning will fail for the node due to docker port misconfiguration.

**Other details that may be helpful:**
When we have v2.1.7 and upgrade to master we do NOT see this issue when we create a NEW azure node template -- double-checked.

This was working on Friday 3/15/19

**Comment by davidnuzik** [comment]
@westlywright updated issue description; it's very strange but we have double-checked and when we are on v2.1.7 and upgrade to master we do NOT see the issue with new azure node templates. We have not been able to determine why. 

Any fresh v2.2.0-rc6 or master install WILL see the issue with new azure nodes templates.

**Comment by westlywright** [comment]
@davidnuzik the default for the azureConfig ( `/v3/schemas/azureconfig` ) is 0. My guess is there is a bug on upgrade and either the default of the schema is not set. If the default needs to change this should be a backend issue.

**Comment by sangeethah** [comment]
@kinarashah In upgraded setup (2.1.7 -> rc6)
```
"dockerPort": {
"create": true,
"default": "2376",
"description": "Port number for Docker engine",
"dynamicField": true,
"type": "string",
"update": true
},
```
In fresh install of master:
```
"dockerPort": {
"create": true,
"default": 0,
"description": "Port number for Docker engine",
"dynamicField": true,
"type": "int",
"update": true
},
```

**Comment by sowmyav27** [comment]
verified on `rancher:v2.2.0-alpha6`. docker-port is not passed in the request to docker-machine while creating an Azure cluster.

**Comment by sangeethah** [comment]
@logan @alena @kinara The change to schema from “int” to “string” is not applied on upgraded setups . That is a problem as well we need to look at ?

**Comment by loganhz** [comment]
@sowmyav27 I guess this issue is not introduced in #18822. It should be reproduced in v2.2.0-rc3 which doesn't have the fix for #18822

**Comment by sangeethah** [comment]
@loganhz,  #18822 issue did not introduce this issue. But until this issue was not addressed , the docker port being set to 0 was not preventing the Azure node creation from succeeding since it was not being passed to the docker machine command at all. Once #18822 was fixed , we are see this parameter being actually passed to docker machine command and node creation reports failure.

**Comment by loganhz** [comment]
@sangeethah Got it! Thanks a lot

**Comment by sowmyav27** [comment]
verified on latest master (image ID: `afe8fffcf864`),default values for the int type fields in the API:
VMware
Port: vmwarevsphereconfig: 443 vmwarevspherecredentialconfig: 443, cpuCount: 2, diskSize: 20480, memorySize: 2048
 
Azure: 
dockerPort: 2376

Amazon EC2: 
blockDurationMinutes: 0, retries: 5, rootSize: 16

digital ocean: 
sshPort: 22

On previous master (image id: `022651b0ec13`), default values for the int type fields in the API:
VMware:
Port: vmwarevsphereconfig: 0 vmwarevspherecredentialconfig: 443, cpuCount: 0, diskSize: 0, memorySize: 0

Azure: 
dockerPort: 0
 
Amazon EC2: 
blockDurationMinutes: 0, retries: 0, rootSize: 0
 
digital ocean: 
sshPort: 0

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/19/19) ImageID: afe8fffcf864 (40 mins old as of now)
Confirmed issue. In the UI when creating an Azure node template it now shows the proper docker port.
![image](https://user-images.githubusercontent.com/45179589/54632433-57519100-4a3b-11e9-9178-0b1cdff8e564.png)

When I create the nodetemplate and inspect req. payload and server resp. dockerPort is correct for both:
`dockerPort: 2376`

When I create a cluster using the node template the API looks correct for the cluster (dockerPort still correct) and when I inspect API for nodeTemplate this too is correct.

When I run an nmap check on the node dockerPort I can see it's indeed open. And I smoke tested my azure cluster.
```
PORT     STATE SERVICE
2376/tcp open  docker
```
