### ISSUE TITLE
rancher-dns fails if upstream DNS server sends truncated responses

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#18991]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create 1.6.14-patch3-rc1 cluster with ROS v1.4.2
- Use Rancher-DNS

**Result:**
Containers can not resolve external addresses

**Other details that may be helpful:**
If you bypass the Rancher-DNS by updating /etc/resolv.conf to use the external DNS server directly. It works but nslookup will return "can't resolve '(null)': Name does not resolve" but DNS will work.

This issue might be related to the following:
https://github.com/rancher/rancher/issues/9605
https://github.com/nicolaka/netshoot/issues/6

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v1.6.14-patch3-rc1
- Installation option (single install/HA): HA

**Comment by chappelleshow** [comment]
Would like to add, as I don't see it listed here.  This is only regarding containers built from Alpine images.  Other containers are able to resolve the same address

**Comment by mattmattox** [comment]
**Workaround**
Adding the following to the docker-compose.yml will resolve this error.
```
    dns_search:
    - company.com
    - <stack-name>.rancher.internal
    - <stack-name>.rancher.internal
    - rancher.internal
    dns:
    - 1.1.1.1 <<-- change to your DNS server
    - 1.0.0.1 <<-- change to your DNS server
    - 169.254.169.250 <<-- change to Rancher DNS server
```

**Comment by vincent99** [comment]
That's really just disabling the use of rancher-dns entries entirely;  Multiple `dns` entries are not a "try them all in order until you find an answer you like" thing, only the first one will be used unless it's entirely unresponsive.  If you try to resolve `something.something.rancher.internal` it's going to go to 1.1.1.1, get a nxdomain response, and give you back nothing.  Not retry 1.0.0.1 and then 169.254.169.240.

**Comment by onedr0p** [comment]
This does seem to be an issue with alpine, linking the GH issues below

https://github.com/gliderlabs/docker-alpine/issues/255
https://github.com/gliderlabs/docker-alpine/issues/476
https://github.com/gliderlabs/docker-alpine/issues/236

**Comment by alena1108** [comment]
@mattmattox what is the hosts OS?

**Comment by jambajaar** [comment]
CentOS/RHEL @alena1108 cc: @mattmattox

**Comment by onedr0p** [comment]
CentOS/RHEL in our environments too.

**Comment by mattmattox** [comment]
@alena1108 The host is RHEL7

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
