### ISSUE TITLE
Support for RHEL/CentOS 7.6 in Rancher 2.0.x and 2.1.x

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#18994]
It appears Rancher 2.2 might be supported only on RHEL 7.6 and not RHEL 7.5

To give teams a chance to upgrade the OS first, a version of 2.0.x and 2.1.x should support both RHEL 7.5 and 7.6.  

This will be very helpful for contexts where the team performing the OS upgrade is different from the one performing Rancher upgrade

**Comment by sangeethah** [comment]
@soumyalj As part of certifying  RHEL 7.6 for 2.0.x and 2.1.x  , we need to validated the following configurations:

Rancher server version - v2.0.13
1. RHEL 7.6 with native docker (SE linux enabled) 
2. RHEL 7.6 with upstream docker 18.09 (SE linux not enabled)

Rancher server version - v2.1.8
1. RHEL 7.6 with native docker (SE linux enabled) 
2. RHEL 7.6 with upstream docker 18.09 (SE linux not enabled)

**Comment by soumyalj** [comment]
Rancher server version - v2.0.13

Tested RHEL 7.6 with upstream docker 18.09 (SE linux not enabled) - Fails
https://github.com/rancher/rancher/issues/19299

**Comment by sangeethah** [comment]
Rancher server version - v2.1.8 - RHEL 7.6 nodes and native docker 1.13.1 (SE linux enabled) on v1.13.5  failed - https://github.com/rancher/rancher/issues/19305

**Comment by soumyalj** [comment]
Rancher server version - v2.0.13

RHEL 7.6 with native docker (SE linux enabled)  with docker 1.13.1 - Automation tests in progress
RHEL 7.6 with upstream docker 18.09 (SE linux not enabled) K8s 1.11.9- Pass 


Rancher server version - v2.1.8

RHEL 7.6 with native docker (SE linux enabled) K8s 1.13.5- Fail 
RHEL 7.6 with upstream docker 18.09 (SE linux not enabled) k8s 1.13.5 - Automation tests in progress

**Comment by soumyalj** [comment]
Note: Cluster using RHEL 7.6 nodes with K8s v1.13.5 on Rancher v2.2.2-rc2 was tested and automation tests were successful
