### ISSUE TITLE
[rancher-python] Remove cli interface option

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#19000]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement
The cli has been moved to https://github.com/rancher/cli and the cli for https://github.com/rancher/client-python has been deprecated.

**Other details that may be helpful:**
The client-python readme also needs to be updated to reflect this change

Also:
- The client-python package install as `rancher` which causes confusion as the cli is also called `rancher`

**Comment by dramich** [comment]
README also needs to clarify the python version required to run (3.7 as of this comment)

**Comment by cjellick** [comment]
nothing to test here. closing
