### ISSUE TITLE
AWS EC2 Cluster nodes use default disk size

### ISSUE THREAD

**Issue by gd-asharov** [rancher/rancher#19001]
**What kind of request is this:**
bug / question

**Steps to reproduce:**
Create a cluster with a configuration like on the screenshot.
<img width="1042" alt="Screenshot 2019-03-19 at 01 55 21" src="https://user-images.githubusercontent.com/22218101/54566693-07e37480-49eb-11e9-83bd-626a9df074be.png">

**Result:**
Cluster works fine, but nodes have got wrong root volume. Template created a new device nvme1n1 and system doesn't use it.

```
NAME        MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
nvme1n1     259:0    0   50G  0 disk
nvme0n1     259:1    0   50G  0 disk
|-nvme0n1p1 259:2    0  128M  0 part  /boot
|-nvme0n1p2 259:3    0    2M  0 part
|-nvme0n1p3 259:4    0    1G  0 part
| `-usr     254:0    0 1016M  1 crypt /usr
|-nvme0n1p4 259:5    0    1G  0 part
|-nvme0n1p6 259:6    0  128M  0 part  /usr/share/oem
|-nvme0n1p7 259:7    0   64M  0 part
`-nvme0n1p9 259:8    0  5.7G  0 part  /
```

Device nvme0n1 has 50G disk size because I increased it manually. By default it was 8G.

**Environment information**
- Rancher version: `rancher/rancher:master`
- Installation option: single

**Cluster information**
- Cluster type: AWS EC2
- Machine type: t3.medium
- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:16:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:16:31 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by loganhz** [comment]
@gd-asharov I guess you are using an old `rancher/rancher:master` image. Can you try to pull again?

**Comment by kingsd041** [comment]
@loganhz 
If I use ubuntu16.04 to launch the cluster, it works fine.
If I use CoreOS to launch the cluster, I will reproduce the issue. Create a node template to set the disk size to 50G. After the cluster starts, it does not extend the root disk to 50G, but mounts a 50G volume to the node. You can see through the following commands and instance details.
```
# fdisk -l
Disk /dev/nvme1n1: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/nvme0n1: 8 GiB, 8589934592 bytes, 16777216 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: CD2320E5-103A-4329-AC6F-0A1FC5B6FD93

Device           Start      End  Sectors  Size Type
/dev/nvme0n1p1    4096   266239   262144  128M EFI System
/dev/nvme0n1p2  266240   270335     4096    2M BIOS boot
/dev/nvme0n1p3  270336  2367487  2097152    1G unknown
/dev/nvme0n1p4 2367488  4464639  2097152    1G unknown
/dev/nvme0n1p6 4464640  4726783   262144  128M Linux filesystem
/dev/nvme0n1p7 4726784  4857855   131072   64M unknown
/dev/nvme0n1p9 4857856 16777182 11919327  5.7G unknown
```
![image](https://user-images.githubusercontent.com/19684717/54589104-b2957a80-4a5f-11e9-9161-28ab9863ab81.png)

**Comment by gd-asharov** [comment]
Hello,

Does anybody know how can fix this issue? 

Maybe I can to help you with that.

**Comment by gd-asharov** [comment]
I checked Debian 9 (ami-0636e459be80b841e) and it have got the same issue.

**Comment by deniseschannon** [comment]
Since launching through the UI is just using a docker-machine command, can you test the same scenario using docker-machine? If you hit this issue in docker-machine, then it's an issue with Docker Machine.
