### ISSUE TITLE
System chart is not presented as a catalog entry in Global/Tools/Catalog page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#19017]
Rancher server version - Build from master - Mar 18

Setup - HA setup using  3 node RKE cluster.

System chart is not presented as a catalog entry in Global/Tools/Catalog page.

Expected Behavior:
System chart should be  presented as a catalog entry in Global/Tools/Catalog page.

**Comment by superseb** [comment]
I think we should consider showing all catalogs in a list, either 2 lists with the built-in ones and another with custom or a single list with an indicator of being built-in or not. This way you have an uniform view of all catalogs, where you can easily edit the source repository (for airgap) and see feedback from fetching the repositories in an uniform way.

**Comment by cjellick** [comment]
This would ease airgap installation.

**Comment by westlywright** [comment]
Available in master

**Comment by davidnuzik** [comment]
@loganhz if this expected? If I disable the Library I still see the system-library listed. But when I try to launch an app there are no libraries listed.

![Screen Shot 2019-04-15 at 12 26 43 PM](https://user-images.githubusercontent.com/45179589/56159566-e211a700-5f79-11e9-8ef4-9e342e5779fc.png)

**Comment by loganhz** [comment]
@davidnuzik yes, it's expected. You can only disable system library by deleting it. And users should not be able to deploy apps in system library directly manually.

**Comment by davidnuzik** [comment]
Thanks @loganhz 

Version: Master (4/16/19)

Confirmed issue. You can now see the system-library chart under the global > Tools > Catalog page:
![image](https://user-images.githubusercontent.com/45179589/56240485-8d892d00-6048-11e9-8f09-61fc12f12bc5.png)

You are able to edit the chart (have full access) as expected.

![image](https://user-images.githubusercontent.com/45179589/56240519-a09bfd00-6048-11e9-870c-a3317910c538.png)
