### ISSUE TITLE
Node driver fields should not change from string to int type between 2.1 and 2.2

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19027]
We introduced a change in the 2.2 cycle that fixed a bug where fields that should have been of type int were exposed as type string in the rancher API.

We fixed this on master, but later realized that it would be a breaking
API change. We could have dealt with just the breaking API change, but this
also exposed a bug that node driver schemas were not automatically updated
when Rancher was upgraded. The combination of fixing the int-to-string bug
but not fixing the update bug is too confusing. So, we are rolling back the
change to match how it was in v2.1.

We will have to fix these two bugs together at a later date.

Related: https://github.com/rancher/rancher/issues/19011

**Comment by cjellick** [comment]
The fields in question:
<img width="457" alt="Screen Shot 2019-03-19 at 11 32 25 AM" src="https://user-images.githubusercontent.com/2473240/54642673-698af980-4a52-11e9-9755-0b07258a8574.png">

**Comment by sangeethah** [comment]
@sowmyav27 @jiaqiluo @davidnuzik  Tested with rancher server build from master - `87654dc3` and `68e56010`
All test cases from the  test plan worked as expected for both fresh install and upgraded rancher server (from 2.1.7) -  [NodeTemplatesSchemaCheck.xlsx](https://github.com/rancher/rancher/files/2986745/NodeTemplatesSchemaCheck.xlsx)
