### ISSUE TITLE
Default value mismatch between API and Rancher UI for int type fields

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19028]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
While creating node templates for the providers - Amazon EC2, Azure, Digital Ocean and VMware vSphere, there is value mismatch between the default values for `int` type fields in API vs Rancher UI.

<img width="446" alt="Screen Shot 2019-03-19 at 11 13 35 AM" src="https://user-images.githubusercontent.com/26032343/54643755-e919c800-4a54-11e9-9d07-a4ae730bb382.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master (image id: `022651b0ec13`)

**Comment by rmweir** [comment]
@cjellick I believe this was introduced by the fix for https://github.com/rancher/rancher/issues/19027, since then that fix has been reverted. The types are strings again and the default appear to be correct. I think we can close this one.

**Comment by cjellick** [comment]
kicking to QA then for reverification

**Comment by sowmyav27** [comment]
The type are string. Default values are as mentioned in https://github.com/rancher/rancher/issues/19027#issuecomment-474589748.
Verified on master-head. (latest)
