### ISSUE TITLE
Purge the deleted certs from UI

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1903]
Current behavior:

When a cert is deleted, it stays in UI in deleted status

Nice to have:

Deleted cert can be removed from UI unless there is a plan to re-store.

User Interface 	v0.43.0

<img width="1385" alt="screen shot 2015-08-27 at 10 59 45 am" src="https://cloud.githubusercontent.com/assets/7720752/9529399/e6ba5fc2-4cae-11e5-8886-c7cffeaff6d8.png">

**Comment by vincent99** [comment]
Purge/restore isn't in the API.  Removed certs hidden now.

**Comment by aruneli** [comment]
Verified that deleted certs are hidden from UI in below version.

Rancher 	v0.35.0-rc4
Cattle 	v0.86.0
User Interface 	v0.45.0
Rancher Compose 	beta/latest
