### ISSUE TITLE
Ingress resource showing Node IP instead of Load Balancer's IP?

### ISSUE THREAD

**Issue by shinebayar-g** [rancher/rancher#19046]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
- create fresh cluster on GKE
- install nginx-ingress-controller via helm chart
![image](https://user-images.githubusercontent.com/3091558/54700916-ddbabf80-4b6e-11e9-8242-e8a23cc40d36.png)
As I understand, It creates L4 TCP Load Balancer on GCP.
- Deploy nginx image and expose it through ingress
![image](https://user-images.githubusercontent.com/3091558/54701336-c4664300-4b6f-11e9-8b70-b2346031de25.png)

**Result:**
If I view this new ingress' YAML it shows one of my Node's IP, not Load Balancer's IP.
![image](https://user-images.githubusercontent.com/3091558/54701535-26bf4380-4b70-11e9-89e3-1cbf0fc78d52.png)

So If I point the domain address to this IP, it doesn't work.
However If I point the domain to L4 Load Balancer's IP, it works. I don't know it's working as intended or not.. Is this correct behavior? Thank you.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Single install / v2.1.7

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE, created from Rancher UI
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.12.5

**Comment by shinebayar-g** [comment]
Found an answer for my poor question [here](https://www.joyfulbikeshedding.com/blog/2018-03-26-studying-the-kubernetes-ingress-system.html).

**Comment by nvaklinov** [comment]
@shinebayar-g How did you fix it? I am facing the same issue.

**Comment by shinebayar-g** [comment]
@nvaklinov I don't recall the specifics of the solution. My last comment is not so useful... 😅 
It's probably better to create a separate issue.
