### ISSUE TITLE
Bad interpretation of values.yml in helm catalog UI

### ISSUE THREAD

**Issue by AlexisDucastel** [rancher/rancher#19042]
Yaml representation problem, for example in helm kibana config:

When specifying values for helm kibana template, the "kibana.yml" key of config map is misunderstood by Rancher. 

So :
```
files:
  kibana.yml: |
    elasticsearch.url: http://elasticsearch-client:9200
```

gives :
```
files:
  kibana:
    yml: |
      elasticsearch.url: http://elasticsearch-client:9200
```
which changes the behavior and generate a broken configMap.

See the result configMap below :
<img width="1281" alt="Capture d’écran 2019-03-20 à 11 24 41" src="https://user-images.githubusercontent.com/1911945/54680936-728bd180-4b0b-11e9-9dbc-38ab6e368db4.png">
---
Steps to reproduce : 
* in Rancher go to catalog, select Kibana from helm stable
* Copy the "files" section of the preview as values
* deploy kibana
* check the configMap, you'll see two keys as in above picture.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.7` UI: `v2.1.21` |
|Route|`catalog-tab.launch`|

**Comment by superseb** [comment]
This should be fixed in https://github.com/rancher/rancher/issues/16680, let me know if this is different.
