### ISSUE TITLE
UI: Have to hit Cancel button twice when creating new node template for first time

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19049]
Version: Master 2.2 (3/20/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- On a fresh install, go to the Node Templates page
- Add any node template. Click cancel

**Result:**
You have to actually hit cancel twice because there is no cloud credentials set yet.

**Other details that may be helpful:**
In this situation where we do not have any cloud credentials set, we would like the cancel button to cancel out of both prompts.

**Comment by tfiduccia** [comment]
Remove Create/Cancel buttons from the Account Access accordion, for the create on bottom, post both the credential & template events?

![image](https://user-images.githubusercontent.com/11514927/62253902-36675800-b3ac-11e9-9a55-d8cfb765177b.png)

**Comment by tfiduccia** [comment]
Comments for Tani after discussion with Vincent:
There are currently two different paths for RKE clusters:
1.  Amazon EC2 & DigitalOcean - Two step process where you need the credentials to fill out which fields & options you get for the node.
2.  Azure, Linode & vSphere - One step process where the node fields are already available & we have two cancel/create button on single page.

We need to:  
- [ ] Make the experience consistent across all RKE drivers
- [ ] Remove the two cancel/create buttons on single page

**Comment by tfiduccia** [comment]
Closing in favor of : #23313.  We will be dealing with the two cancels in this ticket.
