### ISSUE TITLE
Upgraded version of Rancher stops windows nodes being added to existing environment

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#19048]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a Rancher 2.1.1 cluster and add a child cluster with a windows node in it.
Upgrade the Rancher cluster to 2.1.7 and try to add additional windows node to the environment,

**Result:**
It will fail with an error similar to:
```INFO[1791794] Connecting to proxy wss://<ip>/v3/connect with token xptflqqqqj57lnrv9r7ngpl5rd8tvp62mdzqbc2lqs4b2tnjcg9r4l
ERRO[1791795] Failed to connect to proxy: Error response from daemon: Conflict. The container name "/kubernetes-binaries" is already in use by container "7077fd7357a4df735b8ee24d5bc14825a81ba790edefe5d749caaf629c7c9b72". You have to remove (or rename) that container to be able to reuse that name.
INFO[1791796] Connecting to proxy wss://<ip>/v3/connect with token xptflqqqqj57lnrv9r7ngpl5rd8tvp62mdzqbc2lqs4b2tnjcg9r4l
ERRO[1791797] Failed to connect to proxy: Error response from daemon: Conflict. The container name "/cni-binaries" is already in use by container "0cfd57a3cf9ce3b9c1a7b0b7906a819661e717f0740ffa755259f5fa851e05fe". You have to remove (or rename) that container to be able to reuse that name.
```
**Other details that may be helpful:**
Running on Windows Server 1803 with docker 18.09 for all environments

**Comment by kingsd041** [comment]
Based on rancher/rancher: v2.3.0-alpha1 and k8s 1.14.1 and windows 2019 test

After upgrading rancher/rancher:v2.3.0-alpha1 to rancher/rancher:v2.3.0-alpha2, add windows node, which can be added successfully without error message.
