### ISSUE TITLE
Webaccess not possible after fresh installation

### ISSUE THREAD

**Issue by hotschmaster23** [rancher/rancher#19043]
**What kind of request is this (question/bug/enhancement/feature request):**
Question / BUG

**Steps to reproduce (least amount of steps as possible):**
I have installed everything according to the documentation but when i wanted to open the webui it is not possible. It seems that the webserver is not working correctly after a fresh installation.
I can ping all other servers in this cluster and normal internettraffic is also working.
https://siemonster.knowledgeowl.com/help/siemonster-version-3-diy-vm-install-video-step-by-step
https://dyzz9obi78pm5.cloudfront.net/app/image/id/5b0d28ca6e121c062e714dd8/n/siemonster-v3-vm-build-guide-v26.pdf#5.2
but when i check the docker ps output eveything seems fine

docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                              NAMES
8f132829e138        rancher/server:v1.6.17   "/usr/bin/entry /usr…"   36 minutes ago      Up 36 minutes       3306/tcp, 0.0.0.0:8080->8080/tcp   rancher-mgmt

According to the netstat output Port 8080 is not started

Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:56743           0.0.0.0:*               LISTEN      0          20516      1088/rpc.mountd
tcp        0      0 0.0.0.0:49899           0.0.0.0:*               LISTEN      0          19211      1071/rpc.statd
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      0          19850      1/systemd
tcp        0      0 0.0.0.0:35317           0.0.0.0:*               LISTEN      0          19349      -
tcp        0      0 0.0.0.0:36217           0.0.0.0:*               LISTEN      0          20532      1088/rpc.mountd
tcp        0      0 0.0.0.0:38877           0.0.0.0:*               LISTEN      0          20524      1088/rpc.mountd
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN      0          20636      -
tcp6       0      0 :::40301                :::*                    LISTEN      0          20528      1088/rpc.mountd
tcp6       0      0 :::58797                :::*                    LISTEN      0          19217      1071/rpc.statd
tcp6       0      0 :::35759                :::*                    LISTEN      0          20536      1088/rpc.mountd
tcp6       0      0 :::47375                :::*                    LISTEN      0          20520      1088/rpc.mountd
tcp6       0      0 :::111                  :::*                    LISTEN      0          19852      1/systemd
tcp6       0      0 :::8080                 :::*                    LISTEN      0          25223      931/dockerd
tcp6       0      0 :::36531                :::*                    LISTEN      0          19351      -
tcp6       0      0 :::22                   :::*                    LISTEN      0          17482      1/systemd
tcp6       0      0 :::2049                 :::*                    LISTEN      0          20646      -
udp        0      0 0.0.0.0:111             0.0.0.0:*                           0          19851      1/systemd
udp        0      0 0.0.0.0:45460           0.0.0.0:*                           0          20514      1088/rpc.mountd
udp        0      0 0.0.0.0:819             0.0.0.0:*                           0          19096      1070/rpcbind
udp        0      0 127.0.0.1:823           0.0.0.0:*                           0          19119      1071/rpc.statd
udp        0      0 0.0.0.0:41956           0.0.0.0:*                           0          19208      1071/rpc.statd
udp        0      0 0.0.0.0:42654           0.0.0.0:*                           0          19348      -
udp        0      0 0.0.0.0:43681           0.0.0.0:*                           0          20530      1088/rpc.mountd
udp        0      0 0.0.0.0:60340           0.0.0.0:*                           0          20522      1088/rpc.mountd
udp6       0      0 :::40822                :::*                                0          20534      1088/rpc.mountd
udp6       0      0 :::111                  :::*                                0          19853      1/systemd
udp6       0      0 :::37145                :::*                                0          20526      1088/rpc.mountd
udp6       0      0 :::41660                :::*                                0          19214      1071/rpc.statd
udp6       0      0 :::819                  :::*                                0          19097      1070/rpcbind
udp6       0      0 :::38119                :::*                                0          19350      -
udp6       0      0 :::34260                :::*                                0          20518      1088/rpc.mountd

Selftest is also working
curl http://localhost:8080/ping
pong

**Result:**
Please update the documentation and the installation guide as it seems not really working after the configuration steps documented in your document.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VMWare ESXi 6.5 and later (VM version 13)
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:16:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:16:31 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```
(paste the output here)
```

**Comment by deniseschannon** [comment]
If you have further questions, please re-open or file a new issue.
