### ISSUE TITLE
Elasticsearch username & password is stored in clusterlogging CustomResourceDefinition as clear text

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#19053]
**What kind of request is this (question/bug/enhancement/feature request):**

Similar to [this](https://github.com/rancher/rancher/issues/18407) bug. Elasticsearch username and password are begin stored in `CustomResourceDefinition` as plain text 

Arguably a bug, although the password does not appear to be getting inadvertently stored in Elasticsearch itself. On the other hand, it's better practice to use a `SecretRef`. 

**Steps to reproduce (least amount of steps as possible):**

Configure Elasticsearch for Cluster Logging - including login credentials.

Result:

Observe plain text password stored in `CustomResourceDefinition`:

```
$ kubectl get clusterloggings --all-namespaces -o yaml | grep -i password 

      authPassword: myElasticsearchPassword!
        authPassword: myElasticsearchPassword!
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.7
- Installation option (single install/HA): HA

**Comment by alena1108** [comment]
@aiwantaozi check with @kinarashah to see if "Store sensitive data in secrets" framework can be leveraged.

**Comment by aiwantaozi** [comment]
Continually create a new secret when password is in an array, because at this situation, current code couldn't get that correct key in the existing map.

**Comment by alena1108** [comment]
Added @kinarashah as an extra assignee as she is doing some fixes in the passwords to secrets framework for this issue.

**Comment by kinarashah** [comment]
@aiwantaozi The fix for fluentd array has been merged in master, could you give it a test? Let me know if you face any issues.

**Comment by bmdepesa** [comment]
rancher/rancher:master  ebf11403

The password is not always masked as a reference to a secret. Repeated executions of `kubectl get clusterloggings --all-namespaces -o yaml | grep -i password` with or without changes sometimes shows the plaintext password, or the secret id.

* Create Rancher server
* Create cluster
* Enable elasticsearch cluster logging

```
root@828c1b95fd64:/var/lib/rancher# kubectl get clusterloggings --all-namespaces -o yaml | grep -i password
      authPassword: cattle-global-data:fnw7lk7h6x2gnxlrlpsdknlwtlk5z9g4xggb78nsffjn69ftl7skh6

root@828c1b95fd64:/var/lib/rancher# kubectl get clusterloggings --all-namespaces -o yaml | grep -i password
      authPassword: cattle-global-data:kckcgdzh9c5xjc7dzkhkwgd6nmrxvxxlmprxgtcf8zdwnsxczrq9md
        authPassword: testpassword

root@828c1b95fd64:/var/lib/rancher# kubectl get clusterloggings --all-namespaces -o yaml | grep -i password
      authPassword: cattle-global-data:kckcgdzh9c5xjc7dzkhkwgd6nmrxvxxlmprxgtcf8zdwnsxczrq9md
        authPassword: testpassword

root@828c1b95fd64:/var/lib/rancher# kubectl get clusterloggings --all-namespaces -o yaml | grep -i password
      authPassword: cattle-global-data:kckcgdzh9c5xjc7dzkhkwgd6nmrxvxxlmprxgtcf8zdwnsxczrq9md
        authPassword: testpassword

root@828c1b95fd64:/var/lib/rancher# kubectl get clusterloggings --all-namespaces -o yaml | grep -i password
      authPassword: cattle-global-data:kckcgdzh9c5xjc7dzkhkwgd6nmrxvxxlmprxgtcf8zdwnsxczrq9md
        authPassword: testpassword

root@828c1b95fd64:/var/lib/rancher# kubectl get clusterloggings --all-namespaces -o yaml | grep -i password
      authPassword: asdfasdfdas
        authPassword: asdfasdfdas

root@828c1b95fd64:/var/lib/rancher# kubectl get clusterloggings --all-namespaces -o yaml | grep -i password
      authPassword: asdfasdfdas
        authPassword: asdfasdfdas

root@828c1b95fd64:/var/lib/rancher# kubectl get clusterloggings --all-namespaces -o yaml | grep -i password
      authPassword: asdfasdfdas
        authPassword: asdfasdfdas
```

**Comment by bmdepesa** [comment]
rancher/rancher:master 5d74988c

* Enabled elasticsearch cluster logging
* Passwords are no longer shown in plaintext in CRD
