### ISSUE TITLE
Expose customization of integrated fluentd watched-file-list to enable logging on more clusters

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#19055]
Expose customization of integrated fluentd `DaemonSet` watched-file-list (e.g. as an optional Helm value and/or Cluster Logging configuration in the UI) to enable logging on a wider variety of cluster/workers.

For example, adding `/foo` would ensure that (1) `/foo` is mounted from the worker into the fluentd container and (2) `/foo` is appended to fluentd's watched-file-list.

**What kind of request is this (question/bug/enhancement/feature request):**

enhancement

**Steps to reproduce (least amount of steps as possible):**

Enable logging on a cluster whose workers unfortunately either store or symlink container logs outside of `/var/log/containers` or `/var/log/pods`.

For example, my workers ultimately links to an external volume i.e. `/var/log/containers` => `/var/log/pods` => `/u01/data/docker/containers`. 

Since `/u01/data/docker/containers` is not mounted, you'll see the following warning in the integrated`fluentd` logs and container logs will not be stored:

```
2019-03-20 22:07:35 +0000 [warn]: #0 /var/log/containers/cattle-node-agent-m9csl_cattle-system_agent-a5959a82287f5e61839b25fa52c5017134b1bbd273fdfe8434a83fd51a589a98.log unreadable. It is excluded and would be examined next time.
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.7
- Installation option (single install/HA): HA

**Comment by aiwantaozi** [comment]
You could change the docker root in cluster option, and reenable the logging now.

**Comment by jlamillan** [comment]
@aiwantaozi thanks for the suggestion. I'm not sure I am following though.  Are you suggesting I change the docker filesystem root for the fluentd container? If so, isn't that a bit more drastic and error prone than just editing the` fluentd` `daemonset` and adding the volume?

**Comment by aiwantaozi** [comment]
Hi @jlamillan If your docker root is not the default, you can update the docker root to Rancher(In Rancher UI, cluster option page), then reenable the logging.

**Comment by deniseschannon** [comment]
@jlamillan Let me know if you have more questions.
