### ISSUE TITLE
Windows core container not Run

### ISSUE THREAD

**Issue by fedeostrit** [rancher/rancher#19063]
Hello,

I have a cluster with 3 hosts in Centos 7 with rancher V2.2.0-rc7, I have a private registy created with a microsoft / dotnet-framework image: 4.6.2-runtime-windowsservercore-ltsc2016e and when I try to deploy it in the cluster throw the following error, I need a node in the cluster that runs on Windows server as a worker?
![image](https://user-images.githubusercontent.com/48490228/54760037-03c37c80-4bce-11e9-98be-01397a48b688.png)

**Comment by loganhz** [comment]
You cannot run a windows image in linux worker. You need to add a Windows worker and use label to schedule your workloads into the Windows worker.

Here is the doc for adding windows worker in Rancher (Experimental). https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/

Please create a new issue if you have further issues or questions
