### ISSUE TITLE
Custom node driver says active but template fields don't immediately show up

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#19066]
What kind of request is this (question/bug/enhancement/feature request):
Bug

Steps to reproduce (least amount of steps as possible):

Activate a custom node driver. 
- It goes to installing and becomes "Active"
- Go to Node Templates and try adding node template for this new driver 
- Fields don't show up in UI
- But they do eventually come up after a while 

Expected: 
- Either node driver immediately doesn't go active, or some indication should be present while adding node template

Environment information

Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): v2.2.0-rc8
Installation option (single install/HA): Single

**Comment by westlywright** [comment]
Fix in master and `2.2.30` ui tag which will go into 2.2.1 rc when one is cut but this could be verified on the 2.2 release with that tag as well.

**Comment by davidnuzik** [comment]
This was validated in v2.2.2-rc2 in issue https://github.com/rancher/rancher/issues/19330
This issue checks again in the latest master for v2.3.

Version: Master (4/16/19)

I confirmed this is working as expected.
- Add a custom node driver such as https://mxschmitt.github.io/ui-driver-hetzner/
- The driver will download and activate
- Try to add a node template for it -- notice it now appears ready right away. The UI for it loads right away without any issues. The icon shows up.

Add node template screenshot:
![image](https://user-images.githubusercontent.com/45179589/55573973-1ce52680-56c0-11e9-8cda-8c21cb3cd804.png)
