### ISSUE TITLE
Tick symbol used in dashboard to represent failure

### ISSUE THREAD

**Issue by rossigee** [rancher/rancher#19061]
**What kind of request is this (question/bug/enhancement/feature request):**

bug
(sort of)

**Steps to reproduce (least amount of steps as possible):**

Go to the cluster dashboard view when one of the 'pressure' alerts is raised. See attached screenshot.

**Result:**

User see's a 'tick' where a failure is present. Understood it's red, but the symbol is just inappropriate.

**Suggestion:**

The symbol to be used to represent a failure state should probably be a cross (X) or a warning symbol (i.e. triangle, with exclamation mark).

**Comment by rossigee** [comment]
![tick-probably-not-best-symbol](https://user-images.githubusercontent.com/5194485/54745258-a9d9ab80-4bfb-11e9-8479-2ef04f3a595f.png)

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: Master (4/29/19)

The symbol is now a caution symbol:

!image-20190429-165728.png|width=157,height=35.5!
