### ISSUE TITLE
Errors shown in UI when cluster is insufficient size for Prometheus

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19068]
Version: v2.2.0-rc8

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster (such as non-default size digital ocean with 1vcpu)
- Enable monitoring (with default settings) and watch the cluster page
- Observe errors (see results section below)
- Edit monitoring settings to decrease these settings. They seem to take effect on the workloads/pods but the pods are not restarted and we cannot recover. (The resolution to this issue just covers the error messages) See #19078 for this

**Result:**
You will get errors in the UI as pictured below.
![image](https://user-images.githubusercontent.com/45179589/54780133-3e311780-4bd6-11e9-9bdb-da8e731d3e3d.png)

You will see that prometheus-cluster-monitoring has insufficient resources
![image (1)](https://user-images.githubusercontent.com/45179589/54780136-40937180-4bd6-11e9-9d44-0e2743e3a264.png)

**Expected Behavior:**
An appropriate error message should be shown to the user indicating there is insufficient resources for Prometheus. The user should be able to recover the issue by changing prometheus settings.

**Comment by cjellick** [comment]
Realistically, i think we are we talking about doing two things:
1. Replacing the bad error message with something friendly like "Unable to obtain monitoring data"
2. Preventing users from selecting monitoring options that wont work for their cluter?

**Comment by cjellick** [comment]
for 2.2.0, we are just going to make the error message friendly. @davidnuzik can you do me a favor and spin off a new non v2.2 issue for the other ones?

**Comment by davidnuzik** [comment]
Thanks @cjellick I will open another issue.

I have done more testing and discovered that we require a bare minimum of 850m vCPU be reserved before we even factor in prometheus container so this is likely the reason why we cannot recover on a small cluster. When we account for minimum vCPU reserved by k8s there isn't really anything left for the prometheus container so I'll make an issue that basically describes this problem and proposes a solution. I think that we should effectively not allow someone with only 1vCPU single-node cluster to use prometheus and this should prevent the situation from occurring.

**Comment by davidnuzik** [comment]
https://github.com/rancher/rancher/issues/19078 was created

**Comment by cjellick** [comment]
error message fix is available in msater

**Comment by jiaqiluo** [comment]
Test on Rancher master version 693664a7
Steps:
- add a DO cluser with  2 node DO cluster (1 node - etcd/control and 1 worker both default offering 2 cpu/2gb )
- deploying the wordpress app 2 times to reduce the available CPU resource
- enabling monitoring at the cluster level

Result:
<img width="1845" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/54795052-dabfdd80-4c07-11e9-88cb-0c2a1c395eb5.png">

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/21/19)
Confirmed issue as well. Jacks findings match my own:
![image](https://user-images.githubusercontent.com/45179589/54795368-32127d80-4c09-11e9-819e-4776c096a66a.png)

**Comment by davidnuzik** [comment]
Version: v2.2.0-rc9
Validated again in rc9
![image](https://user-images.githubusercontent.com/45179589/54840316-f4096e00-4c89-11e9-9b21-50fb79c288d0.png)
