### ISSUE TITLE
Rancher CLI doesn't allow context switching from environment variables or flags

### ISSUE THREAD

**Issue by willtcarey** [rancher/rancher#19064]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
- Run kubectl commands with the CLI `rancher kubectl ...`
- Expect commands to allow switching contexts on a per command basis e.g. `rancher --context "c-123456:p-12345" kubectl ...`

(kubectl is an example here, this holds true for all of the Rancher CLI commands)

**Result:**
Commands aren't able to be run with a command specific context!

**Other details that may be helpful:**
The Rancher v1 CLI included the ability to set an environment on every call, as well as reading from environment variables. As far as I can tell the Rancher v2 CLI only supports reading from the config written to disk.

We are setting up a deploy pipeline using the Rancher CLI and we may have several projects deploying at the same time which introduces a race condition in our deploys that could cause our Rancher commands to write to incorrect contexts.

This is similar to rancher/rancher#15195 however I would love specific environment variable overrides and Rancher CLI flags.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.6
- Installation option (single install/HA): Single install

**Comment by schuylr** [comment]
+1. Notice the old Rancher CLI for Rancher v1.6:

```
schuylr@schuylr-ThinkPad-P52s:~$ rancher inspect --help
View details for service, container, host, environment, stack, volume, secret

Inspect resources by ID or name in the current $RANCHER_ENVIRONMENT.  Use '--env <envID>' or '--env <envName>' to select a different environment.

Example:
  $ rancher inspect 1s70

Usage: rancher [global options] inspect [OPTIONS] [ID NAME...]

Options:
   --type value    Restrict restart to specific types (service, container, host, stack)
   --links         Include URLs to actions and links in resource output
   --format value  'json' or Custom format: '{{.kind}}' (default: "json")
```

And the new one:

```
schuylr@schuylr-ThinkPad-P52s:~$ rancher2 inspect --help
View details of resources

Inspect resources by name or ID in the current context. If the 'type' is not specified inspect will search: cluster, node, project, secret, namespacedSecret, workload, persistentVolume, storageClass, namespace
Examples:
  # Specify the type
  $ rancher inspect --type cluster clusterFoo

  # No type is specified so defaults are checked
  $ rancher inspect myvolume

  # Inspect a project and get the output in yaml format with the projects links
  $ rancher inspect --type project --format yaml --links projectFoo

Usage: 
  rancher2 inspect [OPTIONS] [RESOURCEID RESOURCENAME]

Options:
   --links         Include URLs to actions and links in resource output
   --type value    Specify the type of resource to inspect
   --format value  'json', 'yaml' or Custom format: '{{.kind}}' (default: "json")
```

For some reason, support for flag-defined contexts/environments was not preserved between Rancher 1.6 and Rancher 2+ support, and I'm having a hard time migrating since my deployment automation tools run in parallel with the Rancher CLI, which can use several clusters at the same time. The `--env` flag was extremely useful and without it, I'll have to scrape by using cURL instead.
