### ISSUE TITLE
UI: Upon edit GKE, Security section is missing

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19070]
Version: v2.2.0-rc8

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a GKE cluster
- Once it is fully provisioned, edit it

**Result:**
The entire Security section is missing when you edit.
Note that this would be not editable anyway -- but ideally we show everything on edit just like on add new but we gray out things you cannot modify.

**Expected Result:**
Should still see the Security section but just with all fields uneditable.

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 4beb5cf3e`

Create a GKE cluster.
Once it is fully provisioned, edit it.
Security section is shown.
![Screen Shot 2019-11-14 at 9 07 15 AM](https://user-images.githubusercontent.com/57409052/68874416-679b3800-06be-11ea-9e68-433227926933.png)
