### ISSUE TITLE
Monitoring: Should not allow 1 node cluster with only 1vCPU to enable monitoring

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19078]
Version: v2.2.0-rc8

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a 1vCPU cluster such as with DO RKE
- Try to enable monitoring with defaults

**Result:**
Monitoring will not work as expected, prometheus-cluster-monitoring will have insufficient CPU.

Sum up the CPU reservation for each container in cattle-prometheus namespace. Notice it comes out to 850mCPU plus our setting for prometheus cpu reservation (200mCPU) which exceeds the 1vCPU we have. We also need to note that k8s will reserve some CPU. If you don't count the part that k8s reserves we need 1050 mCPU to enable prometheus successfully assuming we use default setting in the UI to enable monitoring.

**Proposal:**
In the UI prevent the user from enabling monitoring in this situation or in a situation where we calculate that we have insufficient milliCPU to succeed based on settings the user has chosen (ideally). If this is not feasible we should at a minimum not allow a user that is having only a 1 node cluster with only 1vCPU enable monitoring.

**Other details that may be helpful:**
Based on my calculations the following make these CPU reservations (hard coded) (assuming 1 node cluster and used default settings to enable monitoring):
```
exporter-kube-state-cluster-monitoring:                          100
exporter-node-cluster-monitoring:                                100
grafana-cluster-monitoring:                                      250 (SUM)
prometheus-cluster-monitoring:                                   500 (SUM)
prometheus-operator-monitoring-operator:                         100
TOTAL:                                                           1050 mCPU
```

**Comment by thxCode** [comment]
#### Cluster Monitoring 2.2.0 Default Resources

|          Workload (Type)         	|            Container (Type)            	| CPU - Request 	| Mem - Request 	| CPU - Limit 	| Mem - Limit 	| Configurable 	|
|:--------------------------------:	|:--------------------------------------:	|:-------------:	|:-------------:	|:-----------:	|:-----------:	|:------------:	|
|         Prometheus (StatefulSet) 	|                   prometheus (Running) 	|          200m 	|         100Mi 	|       **1000m** 	|       **500Mi** 	|       Y      	|
|                                  	|             prometheus-proxy (Running) 	|           50m 	|          50Mi 	|        100m 	|       100Mi 	|       Y      	|
|                                  	|              prometheus-auth (Running) 	|          100m 	|         100Mi 	|        500m 	|       200Mi 	|       Y      	|
|                                  	|   prometheus-config-reloader (Running) 	|             - 	|             - 	|         50m 	|        50Mi 	|       N      	|
|                                  	|     rules-configmap-reloader (Running) 	|             - 	|             - 	|        100m 	|        25Mi 	|       N      	|
|             Grafana (Deployment) 	|   grafana-init-plugin-json-copy (Init) 	|           50m 	|          50Mi 	|         50m 	|        50Mi 	|       Y      	|
|                                  	| grafana-init-plugin-json-modify (Init) 	|           50m 	|          50Mi 	|         50m 	|        50Mi 	|       Y      	|
|                                  	|                      grafana (Running) 	|          100m 	|         100Mi 	|        200m 	|       200Mi 	|       Y      	|
|                                  	|                grafana-proxy (Running) 	|           50m 	|          50Mi 	|        100m 	|       100Mi 	|       Y      	|
| Kube-State Exporter (Deployment) 	|                   kube-state (Running) 	|          100m 	|         130Mi 	|        100m 	|       200Mi 	|       Y      	|
|        **Node Exporter (DaemonSet)** 	|                exporter-node (Running) 	|          **100m** 	|          **30Mi** 	|        **200m** 	|        **50Mi** 	|       **Y**      	|
|            Operator (Deployment) 	|          prometheus-operator (Running) 	|          100m 	|          50Mi 	|        200m 	|       100Mi 	|       Y      	|

#### Project Monitoring 2.2.0 Default Resources

|      Workload (Type)     	|            Container (Type)            	| CPU - Request 	| Mem - Request 	| CPU - Limit 	| Mem - Limit 	| Configurable 	|
|:------------------------:	|:--------------------------------------:	|:-------------:	|:-------------:	|:-----------:	|:-----------:	|:------------:	|
| Prometheus (StatefulSet) 	|                   prometheus (Running) 	|          200m 	|         100Mi 	|       1000m 	|       500Mi 	|       Y      	|
|                          	|             prometheus-proxy (Running) 	|           50m 	|          50Mi 	|        100m 	|       100Mi 	|       Y      	|
|                          	|   prometheus-config-reloader (Running) 	|             - 	|             - 	|         50m 	|        50Mi 	|       N      	|
|                          	|     rules-configmap-reloader (Running) 	|             - 	|             - 	|        100m 	|        25Mi 	|       N      	|
|     Grafana (Deployment) 	|   grafana-init-plugin-json-copy (Init) 	|           50m 	|          50Mi 	|         50m 	|        50Mi 	|       Y      	|
|                          	| grafana-init-plugin-json-modify (Init) 	|           50m 	|          50Mi 	|         50m 	|        50Mi 	|       Y      	|
|                          	|                      grafana (Running) 	|          100m 	|         100Mi 	|        200m 	|       200Mi 	|       Y      	|
|                          	|                grafana-proxy (Running) 	|           50m 	|          50Mi 	|        100m 	|       100Mi 	|       Y      	|
|            Operator (Deployment) 	|          prometheus-operator (Running) 	|          100m 	|          50Mi 	|        200m 	|       100Mi 	|       Y      	|

Conclusion
- At least `800m + 100m * node_count` CPU requested for Cluster monitoring
- At least `680Mi + 30Mi * node_count` Mem requested for Cluster monitoring
- At least `600m` CPU requested for Project monitoring
- At least `450Mi` Mem requested for Project monitoring
- Both Cluster monitoring and Project monitoring are sharing the same Operator
- Cluster monitoring Prometheus grows very fast, the default limit value is used for 4C8G 1 Node cluster testing, but doesn't satisfy all scenarios. Project monitoring Prometheus is ok, as it only consider the monitor endpoints on the namespaces of Project. Take care about **huge** Project~
- One cluster requested resource calculation formula:
```
CPU > 100m + (700m + 100m * node_count) * enabling_cluster_monitoring + 500m * enabling_monitoring_project_count
Mem >  50Mi + (630Mi + 30Mi * node_count) * enabling_cluster_monitoring + 400Mi * enabling_monitoring_project_count
```

**Comment by loganhz** [comment]
Min CPU value is `900 + your input in UI for Prometheus CPU Limit  (200 by default) + 100 * schedulable_node_count`

Min Memory value is `970 + your input in UI for Prometheus Memory Limit  (100 by default) + 30 * schedulable_node_count`

The left reservation of schedulable nodes should not be less than the min value.

**Comment by loganhz** [comment]
@davidnuzik Please verify it after the PR merged. We can back port to 2.2.x if you are happy with it.

**Comment by davidnuzik** [comment]
@thxCode when I tweak monitoring settings I only see this affect the prometheus container thus only that is configurable. Or am I missing something?

**Comment by materemias** [comment]
It would be preferable to be able to override default resource settings for all components. Monitoring smaller clusters is less resource hungry.

**Comment by cjellick** [comment]
@vincent99 @westlywright id like you to take a look at the approach that @loganhz is proposing. To see if it is the best approach to take.

**Comment by vincent99** [comment]
The approach seems fine, but they're hardcoded into the UI so that's not going to mix with being able to customize the requested amounts...

**Comment by davidnuzik** [comment]
Note: Validated minimum 1200 milliCPU requirement in issue #19311 against v2.2.2-rc1 (this will need to be checked again in v2.3 later)

**Comment by davidnuzik** [comment]
Version: Master (4/4/19) ImageID: 10a1ef90fcbd
We now have a minimum requirement in the UI -- you must have at least 1200 milliCPU. I tested this again just like in #19311 with v2.2.2-rc1 with the same steps as seen below. Essentially the UI blocks you from enabling cluster monitoring unless you have 1200 milliCPU.

---

I also noticed that if we try to enable project level monitoring we get a message stating we must have at least 700 milli CPU. However we still have the same defaults for project level monitoring. I believe this is expected but @loganhz can you please comment on this? (i.e. says make sure you have at least 700 milli CPU at project level monitoring but cpu limit is still 1000milli CPU?
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/55570611-9e38bb00-56b8-11e9-8178-53ba2ce2f666.png)

---

Here are my testing steps:

_Scenario A:_
- Create a 1-node 1 vcpu cluster such as with DO RKE
- Try to enable monitoring with the default settings
- UI will not allow you to enable monitoring now and has a warning message explaining why. Cannot click Save button. (This is perfect!)
![image](https://user-images.githubusercontent.com/45179589/55501605-a41e9580-55ff-11e9-84a3-1851df8bb2f5.png)

_Scenario B:_
- Create a 1-node 2 vcpu cluster such as with DO RKE
- Add workloads that make CPU reservation so we are just barely shy of having 1200 milliCPU available.
- Try to enable monitoring with the default settings
- Again, just like in Scenario A, UI will not allow you to enable monitoring and has the same warning message explaining why. Cannot click Save button. (This proves that we are checking how many milliCPU we have upon attempt to enable monitoring and disallow if only have 1199 milliCPU or less).
![image](https://user-images.githubusercontent.com/45179589/55501605-a41e9580-55ff-11e9-84a3-1851df8bb2f5.png)
- Now, remove workloads so we have just barely more than 1200 milliCPU available
- Enable monitoring - UI lets us and monitoring works.

_Scenario C:_
- Create a 1-node 2 vcpu cluster such as with DO RKE
- Try to enable monitoring with the default settings
- We are allowed to enable monitoring (I used default settings) because we have at least 1200 milliCPU available out of the box. Monitoring works.

I effectively tested the same for project-level monitoring. I need to have at least 700 milliCPU until I am allowed to enable project-level monitoring.

**Comment by davidnuzik** [comment]
Update: The requirement also increases depending on how many nodes you have. If 1 node, 1200 milliCPU is required, if 2 nodes, 1300 milliCPU and so on. This is due to the min requirements per node. each additional node requires 100 more milliCPU.

**Comment by mohag** [comment]
This (actually #2818) prevents deploying monitoring on imported clusters running the cluster-autoscaler that would add more capacity as needed. (A warning that more resources are requested that what is available might work better than plainly blocking enabling monitoring....)

**Comment by macduff23** [comment]
Grafana & Prom mon up on Rancher v2x - A very unconventional accident in the lab with resource limitation workaround , ubuntu 18/19x bionic/disco docker 19.x, on baremetal/doubledutch.
1.Rancher v1.x Server_A  (2core,4GB), install rancher server port8080/80. -
- install the agent for server_A on server_B (server_A up -2 node non_ha config,no ssl port 80/8080) 
- install Prometheus from catalog rancherv1x -server_A.
2. Rancher v2.x server_B (2core,4GB), install rancher server port80/8080 (must be opposite srv_A)
- add  Rancher v1.6 Server_A node  to Rancher v2x cluster  Server_B cluster up (2 node non_ha config,no ssl port 80/8080).
- install longhorn from app catalog to use with grafana as storage class.
-* Prometheus CPU Reservation 750 milli cpu should be available now in the UI (Prometheus must be up in rancher v1.x server_a).
-install grafana from rancherv2 catalog on server_b cluster. 
Grafana metrics should appear now in Rancher v2 Server_B cluster UI  full metrics host and node.:)

Summary 2 rancher servers with 2 agents running flipflopped/crissXcross //totally unstable nonscale-able fun:)  This came from testing both versions of rancher side by side. *dont try this in  Prod kids.
rancher <3
