### ISSUE TITLE
Flannel.1 is not connect between nodes， when rancher network with canal

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#19089]
*Describe your issue here*

Flannel.1 does not work between nodes,  and Normal after closing iptables
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.6` UI: `v2.1.19` |
|Route|`workload`|

**Comment by deniseschannon** [comment]
@wuchencm I need more details about your set up and where your clusters are built.

This issue doesn't give enough details for us to attempt to reproduce.
