### ISSUE TITLE
Metadata - search for services/containers/stacks by name is case sensitive.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1908]
Server version - Build from master - Aug 27

From within container of a service , using any of the following links to retrieve metadata is case sensitive:

http://rancher-metadata/latest/containers/<container_name>
http://rancher-metadata/latest/services/<service_name>
http://rancher-metadata/latest/stacks/<stack_name>

When there is a mismatch in case , we get a "404 Not Found" error.

**Comment by vincent99** [comment]
URLs are normally case-sensitive. Since the metadata server is given arbitrary JSON I'm not sure I really like the idea of it assuming all keys (and some values, like 'name's of array items) are insensitive...

**Comment by sangeethah** [comment]
Kubernetes system stack is stuck in "activating" state forever.

Kubernetes container logs have the following logs:
```
 curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
+ echo Waiting for metadata
Waiting for metadata
+ sleep 1
+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
+ echo Waiting for metadata
Waiting for metadata
+ sleep 1
+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
+ echo Waiting for metadata
Waiting for metadata
+ sleep 1
+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
+ echo Waiting for metadata
Waiting for metadata
```

**Comment by sangeethah** [comment]
Tested with latest build from master:

From within container of a service , using any of the following links to retrieve metadata is not case sensitive anymore:

http://rancher-metadata/latest/containers/
http://rancher-metadata/latest/services/
http://rancher-metadata/latest/stacks/

But the data that is returned metadata has stack/service/container names in lower case always irrespective of the actual case of  stack/service/container names. This is a change from the way it used to work before and we may need to introduce a new version of metadata to support this change .This issue is tracked in https://github.com/rancher/rancher/issues/6226.
