### ISSUE TITLE
UI: Istio Integration Alpha

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19088]
UI for https://github.com/rancher/rancher/issues/19087

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/5/19)

A UI test plan was created to thoroughly test the new feature. As the majority of test cases have been completed and passed I am going to close this issue. Some final testing will continue with the feature and as more testing is done new issues may be created, if necessary.

-----
**Pages Added:**

This adds the "Service Mesh" menu option to Tools at the cluster level. This brings you to the "Cluster Service Mesh" page which is for configuration.

Nav:
![image](https://user-images.githubusercontent.com/45179589/58986481-51459380-8792-11e9-9246-2bbdff1e24d7.png)

Cluster Service Mesh Config:
![image](https://user-images.githubusercontent.com/45179589/58986523-70dcbc00-8792-11e9-8375-80d8dd886ddb.png)
![image](https://user-images.githubusercontent.com/45179589/58986538-7934f700-8792-11e9-9408-e152b6ce6d55.png)
![image](https://user-images.githubusercontent.com/45179589/58986555-7f2ad800-8792-11e9-991a-8597085f8ac1.png)

This also adds the "Service Mesh" page at the project level.
Nav:
![image](https://user-images.githubusercontent.com/45179589/58986653-be592900-8792-11e9-902f-818ee4fc7a60.png)

Page:
![image](https://user-images.githubusercontent.com/45179589/58987238-f6ad3700-8793-11e9-82c0-dcd6e18dcbf5.png)

**This also adds a new entry when creating/editing a namespace**

Note, the default option is Disabled.

![image](https://user-images.githubusercontent.com/45179589/58987072-9cac7180-8793-11e9-94f8-ad7bcf65115c.png)
-----

To Set up the Service mesh successfully, you should generally be using the default configuration on the Cluster Service Mesh (config) page, but should opt-in to enable the Istio Gateway so you can get traffic metrics (charts). This is optional, though.
You also need to ensure that the namespace(s) where you will be deploying your apps/workloads has "Istio sidecar auto injection" Enabled. If you fail to do this, then you will need to manually create istio sidecars yourself so we can have the istio-proxy for each workload you would like to monitor.

![image](https://user-images.githubusercontent.com/45179589/58987072-9cac7180-8793-11e9-94f8-ad7bcf65115c.png)

For testing we recommend using the istio example app "bookinfo" including the bookinfo-gateway. This was used for testing.

We ensured that the Cluster Service Mesh config is working as expected (although there are a handful of edge cases to test remaining), the Service Mesh > Traffic Graph and Traffic Metrics tabs are working correctly, and that we can access the UI pages for Kiali, Jaeger, Grafana, and Prometheus.

RBAC testing was also done in this area and future testing will involve fuzzing the text fields/API and upgrade checks per the internal test plan. As we continue to add more enhancements in this area testing will continue and the test plan will be appended with new test cases.
