### ISSUE TITLE
Istio Integration Alpha

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19087]
**Acceptance Criteria:**
 
**- As Cluster Owner**
- Under tools - Service Mesh option is visible

**- As Project member -** 
- Edit Namespace and enable “istio sidecar auto injection”
- Deploy workloads (https://istio.io/docs/setup/kubernetes/prepare/requirements/)
- Verify that the pods have istio init and istio proxy containers running
- Generate some load (traffic) on your application 
- Select project and Navigate to Service Mesh - verify the Kiali, Jaeger, Prometheus and Grafana icons
- Traffic graph and Traffic Metrics should be visible
- Click on Kiali
- Click on Graph icon to see the traffic flow across all the apps/pods matches the one shown in Rancher UI 
- Dashboard and see all the Namespaces displaying the number of applications running on each and the status (green/red)
- Check Applications and verify all workloads/deployments are visible here
- 
- Click on grafana icon - choose your service and verify the metrics in grafana
- Click on Prometheus - select different metrics (ex - istio_requests_total) and verify the data in console and graph tabs
- Click on Jaeger - select your service and click on Find Trace to view time it takes the service to run
- User should be able to deploy istio configuration for canary deployment

**Comment by deniseschannon** [comment]
Acceptance Criteria: 

[ ] Enable Istio - Only Cluster Owner
[ ] Ability to create Istio enabled Workloads using yaml that can view the routing and links are shown and clickable - Cluster Owners/Members and Project Owners/Members
[ ] Ability to click on components that it can be launched after workload is launched - Cluster Owners/Members and Project Owners/Members
[ ] Launch yaml through Rancher CLI and `kubectl apply`  - Cluster Owners/Members and Project Owners/Members

**Comment by bmdepesa** [comment]
rancher/rancher:master 7a23ff88

All acceptance criteria are met.

Acceptance Criteria:
- As Cluster Owner
[x] Under tools - Service Mesh option is visible

- As Project member -
[x] Edit Namespace and enable “istio sidecar auto injection”
[x] Deploy workloads (https://istio.io/docs/setup/kubernetes/prepare/requirements/)
[x] Verify that the pods have istio init and istio proxy containers running
[x] Generate some load (traffic) on your application
[x] Select project and Navigate to Service Mesh - verify the Kiali, Jaeger, Prometheus and Grafana icons
[x] Traffic graph and Traffic Metrics should be visible
[x] Click on Kiali
[x] Click on Graph icon to see the traffic flow across all the apps/pods matches the one shown in Rancher UI
[x] Dashboard and see all the Namespaces displaying the number of applications running on each and the status (green/red)
[x] Check Applications and verify all workloads/deployments are visible here
[x] Click on grafana icon - choose your service and verify the metrics in grafana
[x] Click on Prometheus - select different metrics (ex - istio_requests_total) and verify the data in console and graph tabs
[x] Click on Jaeger - select your service and click on Find Trace to view time it takes the service to run
[x] User should be able to deploy istio configuration for canary deployment


[x] Enable Istio - Only Cluster Owner
[x] Ability to create Istio enabled Workloads using yaml that can view the routing and links are shown and clickable - Cluster Owners/Members and Project Owners/Members
[x] Ability to click on components that it can be launched after workload is launched - Cluster Owners/Members and Project Owners/Members
[x] Launch yaml through Rancher CLI and kubectl apply - Cluster Owners/Members and Project Owners/Members

**Comment by codejamninja** [comment]
How do I enable istio?

**Comment by codejamninja** [comment]
It says `Cluster Service Mesh is not enabled yet.`.
![Screenshot from 2019-06-12 19-55-31](https://user-images.githubusercontent.com/6234038/59395922-17edc480-8d4c-11e9-8f71-e875634cdc1d.png)

**Comment by loganhz** [comment]
Please go to the bottom of this page and click enable

**Comment by codejamninja** [comment]
The enable button is grayed out. Maybe I need more CPU's.

![Screenshot from 2019-06-12 20-02-23](https://user-images.githubusercontent.com/6234038/59396167-0a850a00-8d4d-11e9-800a-7ed248e0a52d.png)

**Comment by codejamninja** [comment]
Also, do I need to turn off nginx ingress?

**Comment by loganhz** [comment]
You can add more nodes into your cluster. Or you can go through each CPU / Memory Reservation fields in this page and reduce the value. such as change them to 0.

**Comment by loganhz** [comment]
No need to turn off nginx ingress

**Comment by codejamninja** [comment]
So how do I route 80 and 443 traffic into the service mesh?

**Comment by loganhz** [comment]
https://istio.io/docs/reference/config/networking/v1alpha3/gateway/

I guess most of istio users would do this.

1. Trun on istio gateway
2. Expose it via LoadBalancer
3. Config the DNS to make their own domain point to the loadbalancer address for istio gateway

**Comment by codejamninja** [comment]
Hmm, I would like traffic to come in over port 80/443 using node port instead of nginx ingress.

**Comment by loganhz** [comment]
You mean you don't want to use istio gateway? https://istio.io/docs/reference/config/networking/v1alpha3/gateway/

**Comment by codejamninja** [comment]
I want a service mesh without having to create a LoadBalancer resource.

**Comment by codejamninja** [comment]
I guess I want to use istio as the ingress controller.

**Comment by loganhz** [comment]
Got it. Then you can turn of nginx ingress in Rancher. And enable istio gateway when enable service mesh. Then you can change the ports to 80 and 443 in the page

But it doesn't like nginx ingress controller. It will not be running as a DaemonSet.  Maybe you could help to raise another ticket, if the current UX is not what you want.

Thanks a lot

**Comment by codejamninja** [comment]
Ok, cool thanks. That at least gets me started.

**Comment by robodude666** [comment]
Curious... Why is Rancher working on integrating these into Rancher, when you are also working on Rio side by side?

**Comment by loganhz** [comment]
Because people is asking origin istio in rancher2. RIO is based on knative and istio. It provides microPaaS user experience. So users don’t need to have istio knowledge

**Comment by robodude666** [comment]
Does this change any plans to develop a web interface for Rio or integrate it into Rancher?

**Comment by loganhz** [comment]
No, we have a separated team working on RIO. You can deploy RIO in Rancher 2. Actually I don’t know the detail plan for RIO UI
