### ISSUE TITLE
Support CRUD HPA

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19084]

**Comment by soumyalj** [comment]
Tested with master. HPA feature is functional. 
Basic workflow:

1. Create a deployment with CPU/memory reservation. 
2. Create a HPA with CPU/memory metric pointing to deployment
3. Verifed HPA object is created in the kubernetes end using "kubectl get hpa"
4. Verifed that `kubectl get hpa.v2beta2.autoscaling hpa-sq2lz -o json` displays the metrics as provided for the hpa

HPAs for different target types were created in UI and associated HPAs were verified using "kubectl"
