### ISSUE TITLE
Ability to disable username/password based login

### ISSUE THREAD

**Issue by kutchar** [rancher/rancher#19097]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
N/A

**Result:**
A checkbox in "Security > Authentication" settings page that enables/disables username/password based login.

**Other details that may be helpful:**
We would like to be able to disable username/password logins when SAML is configured, this way we can control access to Rancher from our SAML identity provider and not worry about any security backdoors.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.7
- Installation option (single install/HA): single install

**Comment by vincent99** [comment]
This is a recipe for temporarily or permanently locking yourself out when ${preferred auth provider} is unavailable, or moves, or a cert expires, a password is rotated, configuration is changed, etc.

**Comment by kutchar** [comment]
We use quite a lot of various software and they all disable username/password login once SAML is enabled. The whole point of SSO is so you can manage the lifecycle of users in a single place and have access/password policies set in a single place. Allowing users to login using username/password creates a security backdoor.

You also have a valid concern, I have seen it handled in two ways:
1. Have exempt users or groups that can also login with username/password
2. The flag to enable/disable the password login is controlled using a config file or database field, so you can disable it if needed

**Comment by kutchar** [comment]
As a workaround I disabled the `/v3-public/localProviders/local` in the load balancer level, until we have a resolution here.

**Comment by KawaiiZapic** [comment]
For anyone who find out this issue by search or sth else:
1. `kubectl edit AuthConfig/local`
2. change `enable: true` -> `enable: false`
