### ISSUE TITLE
Rancher [2.2.0] CLI can't use YAML formatted RKE configuration files

### ISSUE THREAD

**Issue by skwair** [rancher/rancher#19095]
**What kind of request is this (question/bug/enhancement/feature request):**

Probably a bug.

**Steps to reproduce (least amount of steps as possible):**

Create a cluster with the rancher CLI and a RKE config file like so:

`rancher cluster create --rke-config rke-config.yaml foobar`

**Result:**

The cluster is created as expected but it did not use the given RKE config file.

**Other details that may be helpful:**

After some research, it looks like the content returned [here](https://github.com/rancher/cli/blob/133a5a34ef097c940ea8bf0662985e19b9865846/cmd/cluster.go#L771) as JSON is fine, but it's using snake_case naming, and it's then unmarshaled [here](https://github.com/rancher/cli/blob/133a5a34ef097c940ea8bf0662985e19b9865846/cmd/cluster.go#L775) in a `RancherKubernetesEngineConfig`, which uses camelCase JSON struct tags (at least in the version imported by `rancher/cli` in its vendors).

Using a JSON formatted RKE config file with camelCase naming fixes this issue.

The other issue I encountered was [here](https://github.com/rancher/cli/blob/133a5a34ef097c940ea8bf0662985e19b9865846/cmd/cluster.go#L787), `ctx.String("network-provider")` seems to always be set (to its default value when not specified explicitly by the user I guess), meaning this overrides what a user specified in his RKE config file.  

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/cli:v2.2.0 and rancher/server:v2.1.7
- Installation option (single install/HA): simple single rancher server installation

Probably related to rancher/rancher#15098 and #15083

**Comment by ChrisMcKee** [comment]
Fails silently on yaml config supplied
Converting as described above to 

```
cat <<EOF >> ./tmpcluster.json
{
  "addonJobTimeout": 30,
  "authentication": {
    "strategy": "x509"
  },
  "bastionHost": {
    "ssh_agent_auth": false
  },
  "ignoreDockerVersion": true,
  "ingress": {
    "provider": "nginx"
  },
  "kubernetesVersion": "v1.13.4-rancher1-1",
  "monitoring": {
    "provider": "metrics-server"
  },
  "network": {
    "options": {
      "flannel_backend_type": "vxlan"
    },
    "plugin": "canal"
  },
  "services": {
    "etcd": {
      "creation": "12h",
      "extraArgs": {
        "electionTimeout": "5000",
        "heartbeatInterval": "500"
      },
      "retention": "72h",
      "snapshot": true
    },
    "kubeApi": {
      "extraArgs": {
        "encryption-provider-config": "/etc/kubernetes/encryption.yaml"
      },
      "podSecurityPolicy": false,
      "serviceNodePortRange": "30000-32767"
    },
    "kubelet": {
      "fail_swap_on": false
    }
  },
  "ssh_agent_auth": false
}
EOF


rancher cluster create --disable-docker-version --rke-config tmpcluster.json custom-cluster-one

```

Works as you'd expect

**Comment by deniseschannon** [comment]
Closing in favor of #15098
