### ISSUE TITLE
Admin should able to configure the default Grafana dashboards for cluster and projects

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#19092]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Enable Monitoring in cluster and project
Open cluster grafana instance
Open project grafana instance

**Result:**
The default dashboards provisioned for new Grafana instances deployed by Rancher are hardcoded and can not be configured. Cluster owner or Global Admin should be able to add/remove/customize the default dashboards for Cluster and Project Grafana instances.

Default Dashboards (json) for Cluster Grafana could be managed globally using CRD
Default Dashboards  (json) for Project Grafana could be managed on cluster scope using CRD

**Environment information**
- Rancher version: 2.2-rc3

**Comment by fredleger** [comment]
+1 on cluster where resources are not infinite it does not make sense for us to deploy a prom/grafana only dedicated to rancher & k8s. would like to be able to collect and see metrics from other apps as well. At least include the most commons ones.

**Comment by OriHoch** [comment]
the default grafana admin user/password is `admin` / `admin` you can use it to log into the grafana instance installed by rancher

**Comment by horihel** [comment]
the grafana chart on helm-stable already introduces several methods for loading extra dashboards, one of them via ConfigMap (see [here](https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-dashboards))

This would allow Apps/Helm Charts to deliver a dashboard in a standardized way, similar to what ServiceMonitors are for prometheus.

And as the sidecar allows for namespace filtering, this can be even configured per project.

**Comment by OriHoch** [comment]
thanks @horihel 

it's still very useful to have admin login to Grafana if you want for example, to visually edit dashboards or to use Grafana alerts

**Comment by horihel** [comment]
I agree @OriHoch - and I agree the default should be manageable by configuration.

Just for deployment (as OP stated), there is already an implementation in the wild and it doesn't seem to need a CRD.

**Comment by vhuezo** [comment]
![grafana2022](https://i.imgur.com/T2PHwVd.png)

**What is the username and password?**
