### ISSUE TITLE
[Vsphere] Problem with provisionning cluster

### ISSUE THREAD

**Issue by Pierre-Malherbe** [rancher/rancher#19096]
**What kind of request is this (question/bug/enhancement/feature request):**

BUG

**Steps to reproduce (least amount of steps as possible):**

Create a Cluster provisionning with Vsphere (With rancherOS 1.5.1)

**Result:**

019/03/22 14:16:14 [INFO] stdout: Provisioning with rancheros...
2019/03/22 14:18:31 [INFO] stdout: Copying certs to the local machine directory...
2019/03/22 14:18:34 [INFO] stdout: Copying certs to the remote machine...
2019/03/22 14:18:35 [INFO] stdout: Setting Docker configuration on the remote daemon...
2019/03/22 14:19:11 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2019/03/22 14:19:11 [INFO] stdout:
2019/03/22 14:19:12 [INFO] Generating and uploading node config testpierre11
2019/03/22 14:19:12 [ERROR] NodeController c-ztbjk/m-djhqx [node-controller] failed with : Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
2019/03/22 14:19:12 [INFO] Generating and uploading node config
2019-03-22 14:20:10.738668 I | mvcc: store.index: compact 1054446
2019-03-22 14:20:10.744262 I | mvcc: finished scheduled compaction at 1054446 (took 1.644381ms)

**Other details that may be helpful:**

I have followed the assistant, no specific configuration, we just add a proxy

**Environment information**
Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): v2.1.5
Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere 6.7.0
- Machine type (cloud/VM/metal) and specifications (CPU/memory):  VM (2 cpu, 8GO RAM)
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /data/docker/devicemapper/devicemapper/data
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Data Space Used: 2.103GB
 Data Space Total: 107.4GB
 Data Space Available: 1.178GB
 Metadata Space Used: 20.23MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 1.178GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.149-RHEL7 (2018-07-20)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.5.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.639GiB
Name: rancher01
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://xxxxx:3128
HTTPS Proxy: https://xxxxx:3128
No Proxy: localhost,127.0.0.1,infra.local
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by deniseschannon** [comment]
This seems like a generic docker machine provisioning issue. Have you tried to provision with the same credentials in Docker Machine?

**Comment by superseb** [comment]
Let us know if this needs further investigation.
