### ISSUE TITLE
UI with Firefox: User nav menu is 1px taller than rest of navbar

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19101]
Version: v2.2.0-rc9
local UI: v2.2.14
Browser: Firefox 65.0 (macOS, Linux, Windows)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Login to rancher

**Result:**
Notice the usernav menu is 1px taller than the main navbar. Firefox only.
![image](https://user-images.githubusercontent.com/45179589/54844428-2750fa80-4c94-11e9-8ac4-3114040cb3fd.png)

**Related:**
rancher/rancher#19184

**Comment by westlywright** [comment]
@davidnuzik can you retest in the lastest version of FF (version 66 if im not mistaken), I attempted to repro this in stable, dev version and nightly without success.

**Comment by davidnuzik** [comment]
@westlywright I do NOT repro in new version 66 of Firefox. Tested macOS, Windows, Linux (Debian Jessie) Closing issue; fixed in FF browser in version 66 and newer.

**Comment by davidnuzik** [comment]
Re-opening. This appears to have regressed in latest Firefox update 66.0.2
Rancher: master (4/10/19) UI v2.3.0

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/14/19) ImageID: 24cdc69e2d86 RancherVer (logs): 81c587fe UI ver: v2.3.1 (latest2)

I still am observing this behavior on FireFox. I tested on Firefox for Windows and Linux (debian) (desktop). This happens whether or not in the mobile view.
![image](https://user-images.githubusercontent.com/45179589/57736601-72b4d300-765d-11e9-978d-29bd77e59dfa.png)

I am running the latest version of Firefox. 66.0.5

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/20/19)

This issue is no longer observed; this is fixed. I again tested with latest FireFox (66.0.5) and tested on latest macOS, Windows 10 (1809) and Linux (Debian Stretch).
