### ISSUE TITLE
[UI Bug] upgrade a service with portmap breaks if press enter. 

### ISSUE THREAD

**Issue by narfeta** [rancher/rancher#19109]
**What kind of request is this (question/bug/enhancement/feature request):**

UI Bug

**Steps to reproduce (least amount of steps as possible):**

Select a workload
Upgrade service (must had a port mapping)
Focus on docker image box
Press enter
Port mapping dissapear

**Result:**

If you don't notice and press upgrade button, the service breaks.

tested on rancher version 2.1.7 / 2.2.0-rc10

**Comment by davidnuzik** [comment]
Version: Master (4/23/19)

Followed the steps to reproduce. I put focus on the Docker Image field and pressed enter. Now I see that the UI creates a second entry for port mapping instead of deleting the existing port mapping.
