### ISSUE TITLE
RKE clusters: show auto generated certificates' expiration info in API/UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19103]
Once support is added for it on RKE side https://github.com/rancher/rke/issues/1220, we have to surface it or implement similar logic in Rancher UI/API.

In 2.2, the check for cert expiry will be done via script.

Consider the issue for 2.2.1.

**Comment by dnoland1** [comment]
As a nice to have, if the certificate is near expiration (maybe 30 days), can this be called out in a big red obvious font on the dashboard?

**Comment by alena1108** [comment]
@dnoland1 should be doable. As long as UI has the info about certs expiration, it can generate the warning.

**Comment by gburton1** [comment]
Would this include the ability to configure an alert/notifier based on time remaining before expiration?

**Comment by Oats87** [comment]
@alena1108 @moelsayed does this show up for users that are not cluster owners (and thus don’t have the capability to rotate the certificates themselves)?

**Comment by sowmyav27** [comment]
**Rancher server with custom 2.2.4 image --> upgrade to rancher:master-head --> wait for the certs to expire**

1. create a cluster in custom 2.2.4 image 
2. upgrade to rancher:master-head.
3. View in API does have certificatesExpiration block
4. expiry would be 30 minutes from the time of creation of cluster
5. wait for the cluster certs to expire.
6. Do Rotate Certificates.
7. The cluster will go into Updating state and will come up Active.
8. The cluster will have the certificatesExpiration in View in API. and the expiration date would now be close to 10 years from the time the action was performed.

**Fresh install of rancher:master-head**

1. Create an AWS cluster - 3 nodes - 1etcd, 1 control plane, 1 worker node
2. View in API has the certificatesExpiration block with the expiration 10 year from cluster creation time.
3. Perform a Rotate Certificates for all services separately and verify every one of them changes when you look at View in API.
