### ISSUE TITLE
Cannot recover AKS cluster if edited with improper SSH key

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19114]
Version: v2.2.0-rc9

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an AKS cluster normally (defaults or 1 node is ok)
- Edit the AKS cluster, put in garbage data in the SSH key
- You'll get the following error in the UI (as expected AKS does not like this)
`Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="The value of parameter linuxProfile.ssh.publicKeys.keyData is invalid." Target="linuxProfile.ssh.publicKeys.keyData"`
And this is basically what is seen when tailing logs.
- Now, let's fix the issue so we can recover the cluster. Edit again and put in your correct SSH key again.

**Result:**
Notice that when you edit again to correct our "mistake" with the SSH key, and put in the correct SSH key, we can still not recover the cluster. You will always see the error message in the UI.
You can still navigate the UI with the cluster BUT, if you try to add workloads to the cluster this will not succeed.

NOTE: I tested in v2.1.7 and we get the error, but we are able to recover. When I plug in the correct SSH key upon edit again the cluster instantly goes back to Active state and I can successfully deploy workloads.

**Comment by davidnuzik** [comment]
It may be worth noting that when you edit in either v2.1.7 or v2.2 the UI plugs in the SSH key for you -- so no user should really be changing this unless necessary. This is basically just a problem if someone made a mistake and put in an invalid SSH public key such as the "garbage data" I put in. I imagine that the common issue would be putting in the _wrong_ ssh key not necessarily one that has invalid formatting, etc.

**Comment by cjellick** [comment]
@daxmc99 one thing im interested in is if there is any way to recover, beyond what @davidnuzik tried

**Comment by daxmc99** [comment]
I'm having trouble reproducing this.
Steps taken:

1. Create azure cluster with default values and credentials
2. When inputting ssh creds enter "tacos"
3. Azure complains about the ssh keys being invalid
4. Edit the cluster and give them valid ssh keys `cat ~/.ssh/id_rsa.pub | pbcopy`
5. Get coffee and wait for AKS to provision 
6. Cluster provisions successfully. 
7. Workloads succeed

Only thing I noticed was `Alert: Component controller-manager is unhealthy.` and `Alert: Component scheduler is unhealthy.` in the UI

**Comment by davidnuzik** [comment]
@daxmc99 I tested in v2.2.2-rc1 and I too cannot reproduce this now. Note step #2 should have been edit basically per the issue steps you:

- Create proper AKS cluster with proper SSH key
- EDIT AKS cluster make ssh key field have "garbage data" (literal string I put in)
- EDIT AKS cluster again and fix ssh key

It used to not worked (repro'd a few times) but now it seems to work?
Also possible was a one-off issue communicating with Azure/slowness/etc? Not sure.

Since I cannot reproduce in v2.2.2-rc1, I think we should close the issue. cc: @cjellick
