### ISSUE TITLE
When edit AKS cluster to upgrade k8s initially fails then recovers after about 20 mins

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19115]
Version: v2.1.7
Version: v2.2.0-rc9

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an AKS cluster with 1.11.8 K8s
- Edit the AKS cluster (when it is ready) and upgrade K8s to latest (1.12.5)
- Check Azure Console, upgrade is successful and there appears to be no issues with the cluster on Azure
- The AKS cluster will eventually recover after 20 or so minutes in both v2.1.7 and v2.2.0-rc9

**Result:**
This will not work and you will get an error in the UI (same as in backend logs)
`Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>`
You cannot deploy workloads.

NOTE: This is very closely related to rancher/rancher#19114  I believe. It's the same message but we don't get a description for the status of the error just `<nil> <nil>`

NOTE: This can also happen with just a plain k8s upgrade (no need to node scale)

**Comment by jiaqiluo** [comment]
the issue is reproduced on v2.1.7

**Comment by dnauck** [comment]
Same issue with rancher 2.2.4

**Comment by soumyalj** [comment]
Tested with rancher v2.4.5-rc6

1. Create a 3 node AKS cluster with K8s version v1.15.11
2. Create few workloads
3. Edit the cluster and change K8s version to v1.16.9. Cluster goes to updating state. 
Rolling upgrade is observed,  for every node, a new node is created with the new K8s version(v1.16.9) and the node with older K8s version(v1.15.11) goes to cordoned state and gets deleted. 
![Screen Shot 2020-06-15 at 9 20 15 PM](https://user-images.githubusercontent.com/18536626/84732650-13587f00-af51-11ea-8888-362ede9af427.png)
All the cluster nodes are upgraded to v1.16.9 and cluster goes to active state. 

<img width="1325" alt="Screen Shot 2020-06-15 at 9 46 34 PM" src="https://user-images.githubusercontent.com/18536626/84732905-b7422a80-af51-11ea-9733-b9a4113c870e.png">

**Comment by tuxicorn** [comment]
I am facing similar issue
