### ISSUE TITLE
[rancher/helm] Bug on helm --upgrade --install --force

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#19112]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Run tiller locally KUBECONFIG=/path/config tiller
(New terminal)
```
export HELM_HOST=$(tiller grpc port from ^)
helm init --client-only
helm version
Client: &version.Version{SemVer:"v2.10.0-rancher10"
Server: &version.Version{SemVer:"v2.10.0-rancher10"
```
```
helm repo update
helm install --set minecraftServer.eula=true,minecraftServer.type=VANILLA stable/minecraft
```
Deployment finishes
```
helm upgrade loitering-alligator stable/minecraft --set minecraftServer.eula=true,minecraftServer.type=VANILLA,minecraftServer.serviceType=ClusterIP
Error: UPGRADE FAILED: Service "loitering-alligator-minecraft" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```
Add force param
`helm upgrade loitering-alligator stable/minecraft --set minecraftServer.eula=true,minecraftServer.type=VANILLA,minecraftServer.serviceType=ClusterIP --force`
See tiller logs
[tiller_logs.txt](https://github.com/rancher/rancher/files/2998284/tiller_logs.txt)
**Result:**
Pod is unschedulable because tiller deleted the Persistent Volume Claim and then tried to use it after. 
```
 Warning  FailedScheduling  14m (x2 over 14m)  default-scheduler  persistentvolumeclaim "loitering-alligator-minecraft-datadir" is being deleted
  Warning  FailedScheduling  3m (x36 over 14m)  default-scheduler  persistentvolumeclaim "loitering-alligator-minecraft-datadir" not found
```

**Other details that may be helpful:**

Tested on helm v2.10.0 -rancher
**Environment information**

local cluster with tiller running locally

**Comment by daxmc99** [comment]
This bug is not present in upstream helm v2.13.0

**Comment by deniseschannon** [comment]
Consider upgrading helm to latest version in Rancher

**Comment by deniseschannon** [comment]
Closing in favor of the ticket calling out to upgrade helm. https://github.com/rancher/rancher/issues/16971
