### ISSUE TITLE
User "system:anonymous" cannot create namespaces at the cluster scope on GKE

### ISSUE THREAD

**Issue by kamkie** [rancher/rancher#19129]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
run rancher (2.1 or 2.2) in docker (docker desktop) create cluster in gke

**Result:**
cluster is crated in gke but not visible in rancher

**Other details that may be helpful:**
2019/03/24 22:57:59 [ERROR] Cluster c-6prpf previously failed to create
2019/03/24 22:58:00 [INFO] cluster [c-6prpf] provisioning: Cluster c-6prpf is running
2019/03/24 22:58:00 [INFO] cluster [c-6prpf] provisioning: Cluster c-6prpf is running
2019/03/24 22:58:01 [INFO] kontainerdriver googlekubernetesengine stopped
2019/03/24 22:58:01 [ERROR] ClusterController c-6prpf [cluster-provisioner-controller] failed with : namespaces is forbidden: User "system:anonymous" cannot create namespaces at the cluster scope
2019/03/24 22:58:06 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:10662
2019/03/24 22:58:06 [INFO] kontainerdriver googlekubernetesengine stopped

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cjellick** [comment]
This is one of our most basic use cases and it is exercised a lot. I'm not sure what the issue is, but I strongly suspect it is not a Rancher bug.

**Comment by cjellick** [comment]
Any more details you can provide would be helpful

**Comment by kamkie** [comment]
I created Google cloud service account with rolled from docs (in rancher itself there are different role names for gce iam)
Maybe there is some bug in docs then

In rancher I tried to create cluster using default Admin account and new standard user

**Comment by kamkie** [comment]
I created new service account in GKE and cluster started properly
