### ISSUE TITLE
UI - rancher 2.20.rc11 edit cluster missing information

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#19123]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
upgrade rancher to 2.2.rc-11
add custom cluster check advance options have default values such as nginx ingress enabled, Recurring etcd Snapshot Enabled 
edit cluster, most of advance options default data missing
update advance options and save
edit cluster again, advance options default data still missing, can't save
**Result:**
![image](https://user-images.githubusercontent.com/15118220/54861492-b71ea380-4d7d-11e9-9f8c-585396629c4a.png)

![image](https://user-images.githubusercontent.com/15118220/54861493-cbfb3700-4d7d-11e9-8819-9c0b43d71287.png)

**Comment by Troyhy** [comment]
https://github.com/rancher/rancher/issues/18985#issuecomment-475843203

I think this is duplicate.

**Comment by cjellick** [comment]
Yes, what versions of rancher have you upgraded through?

**Comment by panho66** [comment]
rancher-2.2.alpha -> rancher-2.2-rc11 (edit cluster missing info)
rancher 2.1.7 -> rancher-2.2-rc11 OK
