### ISSUE TITLE
Digital Ocean nodes are never added

### ISSUE THREAD

**Issue by etcook** [rancher/rancher#1912]
I'm attempting to add DO nodes using the api key. They seem to add ok through the gui, and shows "waiting for agent connection" but I don't even see the nodes in my DO account.

**Comment by cjellick** [comment]
@etcook Do they jump to "waiting for agent connection" right away or do they go through a number of other steps first?

Can you post the last 300 hundred lines from the logs of your rancher master container? If the hosts are jumping straight to "waiting for agent connection", then the microservice that calls docker machine (which then calls digital ocean) isn't starting up correctly. If that's the case, the logs will clearly show this with repeated entries about go-machine-service.

**Comment by etcook** [comment]
@cjellick I actually ended up wiping the server and starting fresh with a larger one this morning. I tried installing the rancher-server on a DO 512, and it seemed flaky. Jumped to a 1 gig, and now things seem to operate as intended.

What is the recommended amount of resources for a server node? (no other docker containers will run on it)

Thanks!

**Comment by etcook** [comment]
Oh, and to answer your question, it did go through a couple of steps, although they went quickly.

**Comment by cjellick** [comment]
We recommend at least 1 GB of memory. Other than that, currently our DB grows pretty quickly (in some scenarios, a gig a day), so you'll actually want a fair amount of disk space. We'll be fixing this soon though; we'll cleanup the DB and it won't grow nearly as quickly.

**Comment by cjellick** [comment]
@etcook I'm closing this issue let me know if there is any reason it should remain open.
