### ISSUE TITLE
use rancher how to add ETCD member after removing it 

### ISSUE THREAD

**Issue by treemore** [rancher/rancher#19126]
**What kind of request is this (question/bug/enhancement/feature request):**
As mentioned in this post
https://github.com/etcd-io/etcd/issues/2676
It seems that i need to add a few environment variables before starting the deleted etcd node. But how do you add it?

**Steps to reproduce (least amount of steps as possible):**
Set up Rancher (v2.1.7)
Copy & Paste the Rancher command for adding a host to your Kubernetes-Cluster
docker exec it one of etcd container ,etcdctl member remove one etcd node
Readd the removed node

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.7
- Installation option (single install/HA): ha

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): 1.3.4

- Docker version (use `docker version`): 18.06.1-ce

**Comment by treemore** [comment]
may be . like https://github.com/moby/moby/issues/8838
find the config.json and restart the container ?  Or is there a better way?

**Comment by MiTschMR** [comment]
Hi treemore

Please edit your post and fill out the additional information (Environment information and cluster information). 

I assume you did the following: 
1. Set up Rancher (v2.x?)
2. Copy & Paste the Rancher command for adding a host to your Kubernetes-Cluster
3. Remove an Etcd-Node
4. Readd the removed node

In what state is the node you are trying to add again? Active, Updating or anything else?

**Comment by treemore** [comment]
@MiTschMR   i just  remove the cluster and rebuild rancher can resolve this problem .  

some delele operator not run in the rancher ui . but use docker exec -it  etcd-containder  .  and use the etcdctl to remove the member.

**Comment by MiTschMR** [comment]
What I had to do (I had the problem too) was the following: 
1. Unmount all unused pod-volumes with `umount $(df -HT | grep '/var/lib/kubelet/pods' | awk '{print $7}')`
2. Remove some data folders which can cause problems if they have config files or data in it with
`rm -rf /var/lib/etcd /etc/kubernetes/ssl /etc/cni /opt/cni /var/lib/cni /var/run/calico /etc/kubernetes/.tmp/`
3. Readd the node to the cluster

**Comment by deniseschannon** [comment]
We have docs on how to restore etcd with a snapshot (avialable as of v2.2) or without a snapshot.

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/restoring-etcd/
