### ISSUE TITLE
UI - Not able to enable recurring snapshots on an upgraded setup where backup snapshot was disabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#19122]
Rancher server version - 2.1.7  (recurring snapshots disabled) -> upgrade to 2.2.0-rc11

Steps to reproduce the problem:
Fresh install of Rancher server version - 2.1.7.
Disable recurring snapshots .
Upgrade to Rancher server version - 2.2.0-rc11.

Try to enable recurring snapshots by editing cluster and going to "Advanced settings"
It says "Recurring etcd Snapshot Enabled" but both "Yes" and "No" are not selected .

<img width="1069" alt="Screen Shot 2019-03-22 at 8 29 53 PM" src="https://user-images.githubusercontent.com/4266958/54861119-56da2400-4ce1-11e9-9843-bf41a7bc97d3.png">

```
"etcd": {
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": false,
"type": "/v3/schemas/etcdService"
},
```
Try to select "yes" , `Recurring etcd Snapshot Creation Period` and `Recurring etcd Snapshot Retention Count` remain greyed out. 
<img width="1113" alt="Screen Shot 2019-03-22 at 8 03 45 PM" src="https://user-images.githubusercontent.com/4266958/54861001-a61f5500-4cdf-11e9-9544-c3aad2a6364b.png">

Clicking on "Save" does not result in recurring snapshot being enabled.

Also when I try to toggle between yes and no , both end up being selected.

<img width="1091" alt="Screen Shot 2019-03-22 at 8 03 59 PM" src="https://user-images.githubusercontent.com/4266958/54861110-2a260c80-4ce1-11e9-9cb7-82fbdc2bab38.png">

**Comment by sangeethah** [comment]
Tested with latest build from master:

Steps to reproduce the problem:
Fresh install of Rancher server version - 2.1.7.
Disable recurring snapshots .
Upgrade to Rancher server version - 2.2.0-rc11.

Try to enable recurring snapshots by editing cluster and going to "Advanced settings"
It says "Recurring etcd Snapshot Enabled" as "No" as expected.

Able to select "Yes" and enable snapshots.

Snapshot gets enabled as expected in API.
```
"etcd": {
"backupConfig": {
"enabled": true,
"intervalHours": 12,
"retention": 6,
"s3BackupConfig": null,
"type": "/v3/schemas/backupConfig"
},
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": false,
"type": "/v3/schemas/etcdService"
},
```
I also see a snapshot being created shortly (after about couple of minutes) after the cluster went to updating and active state.

Edit cluster again and go to "Advanced Settings". Snapshot shows as being disabled even though it is enabled at the API level.

<img width="1004" alt="Screen Shot 2019-03-23 at 11 58 21 PM" src="https://user-images.githubusercontent.com/4266958/54876147-e3f7a880-4dc7-11e9-831e-ccdbe0801a13.png">

**Comment by westlywright** [comment]
Available in `2.2.17` and master

**Comment by sangeethah** [comment]
Tested with master and ui-index set to  - https://releases.rancher.com/ui/latest2/index.html".

Fresh install of Rancher server version - 2.1.7.
Disable recurring snapshots .
Upgrade to Rancher server version - 2.2.0-rc11.
Able to enabled recurring snapshots .

Edit cluster and go to "Show Advanced options" . "Recurring etcd Snapshot enabled" section reflects the correct information that snapshot is enabled with the correct creation period and retention count.

**Comment by sangeethah** [comment]
Also tested the following scenarios using 2.2.0-rc12.

Fresh install of Rancher server version - 2.1.7.
Create a cluster - c1 (with recurring  snapshots enabled by default)
Create a cluster - c2 (with recurring  snapshots enabled by default)
Disable recurring snapshots .
Create a cluster - c3 with recurring  snapshots disabled while creation.
Create a cluster - c4 with recurring  snapshots enabled and customized creation period and retention hours.

Upgrade to Rancher server version - 2.2.0-rc12.

After upgrading , Edit cluster and enable snapshots (turn on the new way of enabling snapshots) for all the above clusters.

Able to enable snapshots successfully.

Once snapsots are enabled , going to "Edit" cluster page ->"Show Advanced options"  , "Recurring etcd Snapshot enabled" section reflects the correct information that snapshot is enabled with the correct creation period and retention count.
