### ISSUE TITLE
Release Hardening and benchmark assessment as part of docs

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/rancher#19139]
* https://releases.rancher.com/documents/security/latest/Rancher_Hardening_Guide.pdf
* https://releases.rancher.com/documents/security/latest/Rancher_Benchmark_Assessment.pdf 

The conversion of theses docs to PDF causes a lot of the markdown syntax to be dodgy (i.e. the encryption yaml isn't valid)

It would be better as part of the docs.

**Comment by superseb** [comment]
This is covered in https://github.com/rancher/docs/issues/1157
