### ISSUE TITLE
Tell rancher agent that host is about to shut down

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#1913]
As I mentioned in #1870 I creating an infrastructure in which hosts are self managing meaning starting up and shutting down, leaving the rancher ui in a mess of zombie hosts.

Is it possible to tell rancher agent that he should shutdown his services on the given host?

**Comment by cjellick** [comment]
@fentas out-of-the-box Rancher does not support that. But you could script something like it. Do you have startup and shutdown hooks in your host provisioning? If so, when you shutdown a host, you could call the Rancher API to delete and purge the host. The tricky part would be finding the right host in the API. I believe you could probably accomplish this by querying by name, which by default is the hostname of the machine. So, something on shutdown like: `GET http://rancher/v1/projects/<project id>/hosts?name=<host name>` would get you the host and then you would deactivate, remove and purge it via the API. You can play with these commands in the API UI which is accessible under your avatar icon in the top right. The nice thing is that it shows you the exact curl command and raw HTTP request you would need to make if you were scripting this.

**Comment by vincent99** [comment]
(Fair warning: I'm talking about a feature that isn't in a release yet)

If we added an `api_href` property to metadata on each resource then shutdown script could `docker run` a container, which would hit metadata to get it's own `/v1/[projects/:id/]containers/:id URL, and from there it could lookup the host and `DELETE` it.  Or we could add info about the host directly to metadata too.

@alena1108 / @ibuildthecloud ?

**Comment by vincent99** [comment]
Or this could be an actual feature of the `rancher/agent` container to clean up after itself in response to a kill signal like `SIGUSR1`.

**Comment by fentas** [comment]
@cjellick yeah. In a way I am already using the api that way only in reverse to register the host to rancher. But I rather wish for a bit more convenient way like @vincent99 mentioned. Would that be possible? This also would solve the problem of having tons of reconnecting hosts in rancher ui ( out of the box :). +container running on the host could get instantly a new home without waiting/depending on health checks.

**Comment by ephillipe** [comment]
Hi @cjellick, you say to @fentas:
" I believe you could probably accomplish this by querying by name, which by default is the hostname of the machine."

I will try this approach but name of my host is null on api. I could not can find by name or hostname.
I'm using Rancher 1.0.1 and starting my host with this custom script.:
`     PUBLIC_DNS=$(curl -s checkip.amazonaws.com)
     HOST_LABELS='io.rancher.host.external_dns_ip='$PUBLIC_DNS
     docker stop $(docker ps -q -f name=rancher-agent)
     docker run -d --privileged -e CATTLE_HOST_LABELS=$HOST_LABELS -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.1 http://cirrus-rancher.xxx.com.br/v1/scripts/TOKEN`

Do you can help me?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
