### ISSUE TITLE
Updated cluster from 2.1.3 to 2.2.0-rc13. Cluster is missing etcd snapshot feature

### ISSUE THREAD

**Issue by Troyhy** [rancher/rancher#19138]
*Updated cluster and expected to have etcd snapshot feature available*
Also updated cluster to latest available kubernetes version.

![image](https://user-images.githubusercontent.com/587882/54913645-dd6a4d80-4efb-11e9-9e77-57e4c317a49f.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc13` UI: `v2.2.17` |
|Route|`global-admin.clusters.index`|

**Comment by soumyalj** [comment]
@Troyhy : When we upgrade from a version prior to v2.2.0, we have to edit the cluster and save it. Only then the new etcd snapshot feature will be available. 
There will be a note in the UI about this feature when we edit the cluster

**Comment by Troyhy** [comment]
Hey, Thanks. I missed that one! Now working.
