### ISSUE TITLE
es-data-node (Failed to allocate instance .. needs host with label kraken:1)

### ISSUE THREAD

**Issue by shishir2019** [rancher/rancher#19131]
Rancher Version: 
v1.6.17

CoreOS Version:
4.19.25-coreos

Application Stack:
Siemonster V3

Hosts:
makara, capricorn, proteus, kraken, tiamat

Issue: 
When deploying Siemonster V3 Stack in Rancher, below services have error activating: 

`es-data-node1 + 1 Sidekick (Failed to allocate instance [container:1i10855]: Bad instance [container:1i10855] in state [error]: Allocation failed: Host must satisfy resource constraints: [instanceReservation: 1]. needs host with label kraken: 1, needs host with label kraken: 1) `

`es-data-node2 + 1 Sidekick (Failed to allocate instance [container:1i10857]: Bad instance [container:1i10857] in state [error]: Allocation failed: Host must satisfy resource constraints: [instanceReservation: 1]. needs host with label tiamat: 1, needs host with label tiamat: 1) `

`logstash-collector (Failed to allocate instance [container:1i10860]: Bad instance [container:1i10860] in state [error]: Allocation failed: Host must satisfy resource constraints: [1516:1516/tcp, 1516:1516/udp, 3520:3520/tcp, 3521:3521/tcp, 3522:3522/tcp, 3524:3524/tcp, 3525:3525/tcp, 3526:3526/tcp, 3527:3527/tcp, 3528:3528/tcp portReservation]. needs host with label proteus: 1) `

`logstash-indexer-exporter (Failed to allocate instance [container:1i10861]: Bad instance [container:1i10861] in state [error]: Allocation failed: needs host with label capricorn: 1) `

**Comment by deniseschannon** [comment]
It looks as if our hosts do not have the labels needed in order for the application to succeed.  YOu need at least one host that has at least
`kraken`
`tiamat`
`capricorn`
`proteus`

It's not that the host name needs this but it needs an actual label on the host. 

Also, it looks like you don't have a `proteus` host with the necesarry ports.

Each one of these error message indicates what is missing from your hosts.

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
