### ISSUE TITLE
Ability to move namespace with non-existent projectId (e.g. when importing cluster)

### ISSUE THREAD

**Issue by naorw** [rancher/rancher#19137]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
As Admin user:
Import an existing cluster to Rancher. Going to Namespaces, trying to allocate / move existing namespaces to projects. Expected result:
Being able to move to default / system projects. 

**Result:**
Unable to move via Web interface or Rancher CLI.
Web interface, move option is grayed out.
error from cli:
FATA[0000] Namespace XYZ cannot be moved

**Other details that may be helpful:**
Namespaces seem to contain invalid projectID. in format:
"projectId": "existing_cluster:notexisting_project"

I was able to use 

kubectl annotate --overwrite namespace existing_namespace field.cattle.io/projectId=existing_cluster:existing_project

**Environment information**
- Rancher version 2.1.15:
- Installation option (single install):

**Cluster information**
- Cluster type (Imported, created with another rancher, aws ec2 hosted, 6 nodes):
- Machine type (Nodes: 6x AWS ec2 Rancher server: Physical machine, 8 cores, 32 GB ram)):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
Nodes:
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
Rancher server
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Comment by deniseschannon** [comment]
When you say "import an existing cluster to Rancher", are you trying to import a cluster that had been previously imported into Rancher?

**Comment by naorw** [comment]
that is correct Denise. it is a cluster that was managed by another Rancher instance.

**Comment by deniseschannon** [comment]
@naorw Before you imported it into the 2nd rancher instance, did you delete that cluster from the original one so that it would be cleaned up to prevent issues?

**Comment by pjmorr** [comment]
what if the answer was no?  I have seen this before and never remember seeing that step mentioned anywhere.

I have also seen this in a case where the previous rancher server was un-recoverable and rebuilt, then the clusters were re-imported.

**Comment by vastik** [comment]
I was able to move namespaces after reimporting cluster by using `kubectl edit ns XYZ` and update `field.cattle.io/projectId` annotation. Hope it helps.
