### ISSUE TITLE
Upgrade from 2.1.7 - Deletion of existing projects gets stuck in "removing" state .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#19130]
Rancher server version - Upgrade from 2.1.7  to v2.2.0-rc12

Steps to reproduce the problem:
Fresh install of rancher server version - 2.1.7
Create few projects with namespace and workloads.

Upgrade to v2.2.0-rc12

Try to delete one of the existing projects.
Namespaces under the project gets deleted. But the project gets stuck in "removing" state.

<img width="1136" alt="Screen Shot 2019-03-24 at 4 19 52 PM" src="https://user-images.githubusercontent.com/4266958/54887467-aee36880-4e50-11e9-8186-ea1106bca97d.png">

```
"name": "mystep1-p1",
"namespaceId": null,
"podSecurityPolicyTemplateId": "",
"removed": "2019-03-24T23:07:08Z",
"removedTS": 1553468828000,
"state": "removing",
"transitioning": "yes",
"transitioningMessage": "waiting on project-precan-alert-controller_c-4sc9d",
"type": "project",
"uuid": "fc6f5099-4e7f-11e9-af49-0242ac110002"
}
```

rancher server logs:
```
2019/03/24 23:07:08 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-z95k4
2019/03/24 23:07:13 [INFO] Deleting secret [mystep1-testsecret] in namespace [mystep1-ns1]
2019/03/24 23:07:13 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding rolebinding-sgvkj
2019/03/24 23:07:13 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding rolebinding-tbnwr
2019/03/24 23:07:13 [INFO] [mgmt-auth-prtb-controller] Updating owner label for roleBinding clusterrolebinding-l87jl
2019/03/24 23:07:13 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding clusterrolebinding-mvwkn
2019/03/24 23:07:13 [INFO] [mgmt-auth-prtb-controller] Deleting rolebinding p-z95k4-creator-project-owner-project-owner in namespace c-4sc9d for prtb creator-project-owner
2019/03/24 23:07:13 [INFO] [mgmt-auth-prtb-controller] Deleting rolebinding p-z95k4-u-tup64myhvd-member-project-member in namespace c-4sc9d for prtb u-tup64myhvd-member
2019/03/24 23:07:13 [INFO] Deleting secret [mystep1-testsecret] in namespace [mystep1-ns2]
2019/03/24 23:07:14 [ERROR] ProjectRoleTemplateBindingController p-z95k4/creator-project-owner [cluster-prtb-sync] failed with : projectroletemplatebindings.management.cattle.io "creator-project-owner" not found
2019/03/24 23:07:15 [ERROR] ProjectRoleTemplateBindingController p-z95k4/u-tup64myhvd-member [cluster-prtb-sync] failed with : projectroletemplatebindings.management.cattle.io "u-tup64myhvd-member" not found
2019/03/24 23:07:16 [INFO] Updating workload [mystep1-ns1/mystep1-testingresswl2] with public endpoints [null]
```

**Comment by sangeethah** [comment]
Tested with v.2.2.0-rc3.

Fresh install of rancher server version - 2.1.7
Create few projects with namespace and workloads.
Upgrade to v2.2.0-rc12
Try to delete one of the existing projects.
Project gets deleted as expected,

**Comment by rootwuj** [comment]
Tested with v2.2.0-rc13 from Mar 25

Step1:

Fresh install of rancher server version - 2.1.7
Create few projects with namespace and workloads.
Create cluster and project alerts.
Upgrade to v2.2.0-rc13
Delete one of the existing projects.

Validate1:

Project gets deleted as expected.
The existing alters still works.
Update existing alerts and make sure they continue to work.


Step2:

Fresh install of rancher server version - 2.2.0-rc13
Create few projects with namespace and workloads.
Create cluster and project alerts.
Delete one of the existing projects.

Validate2:

Project gets deleted as expected.
Cluster and project alerts can work.
