### ISSUE TITLE
Cannot edit CCE cluster when eipids is null

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19147]
rancher/rancher:v2.2.0-rc13

Steps:

1. Enable Huawei CCE cluster driver
2. Add a CCE cluster
3. Edit the CCE cluster
4. Click Save

Result:

Cannot edit it and it says `eipids can not be null`

**Comment by westlywright** [comment]
The fix is in tag `2.2.18`, master is not merged yet.

**Comment by westlywright** [comment]
should be in master now too

**Comment by loganhz** [comment]
Validated in 2.2.0-rc14 and master. Now we can edit the cluster.

**Comment by rootwuj** [comment]
Version - 2.2.0-rc15  3/25
Verified fixed
