### ISSUE TITLE
Multicast between nodes

### ISSUE THREAD

**Issue by webfrank** [rancher/rancher#1914]
I've setup a simple two node cluster just to test some containers and the platform. I tried to deploy a two node hazelcast cluster, one container on each node, but as hazelcast uses multicast to discover other nodes, this traffic does not pass between nodes. If i have two container on the same node multicast works and hazelcast find the other node, if i start a new container on the second host it does not join the cluster. If I use the TCPIP joiner, specifying the other containers addresses, the cluster works.
How is routed, if it is, the multicast between nodes?

**Comment by vincent99** [comment]
The Rancher overlay network is a set of point-to-point Layer 3 IPSec tunnels between hosts.  There is no Layer 2 capability and thus no broadcast/multicast (unless the containers happen to be on the same host, as you said).

Layer 2 networks/large broadcast domains do not scale very well across many clients and disparate physical networks.  Typically you would end up having to segment a large-ish deployment into more than one, and then you have to start worrying about if the right containers are in the same segment.  So it's really better to avoid this altogether, the whole internet is one Layer 3 network and it scales ok so far :-)

In the next release or so there will be a new rancher-metadata service that containers will be able to query to get information about themselves, the service and stack they are a part of, etc.  so you will be able to use this in a startup script to get the list of IP addresses of the other hazelcast containers in the service in an automated way.

**Comment by deniseschannon** [comment]
As mentioned, we've released the metadata service, which is available in v0.35.0 and is documented here: http://docs.rancher.com/rancher/metadata-service/

Please let us know if you have other questions.
