### ISSUE TITLE
Cannot add CCE cluster in 2.2.0-rc13

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19146]
rancher/rancher:v2.2.0-rc13

Steps:

1. Enable Huawei CCE cluster driver
2. Add a cluster

Result:

Cannot add the cluster
```
time="2019-03-25T13:30:18Z" level=warning msg="trying to create node for cluster f70008ab-4f00-11e9-babb-0255ac101e31 again" error="http status code[400], huawei cloud api error code[], message: [The node name is empty or it's length exceed max value]"
```

It looks like there is a recent update in Huawei CCE side. The optional field is validated as a required field now.

It should be a bug of Huawei CCE

https://support.huaweicloud.com/api-cce/cce_02_0242.html

**Comment by rootwuj** [comment]
Version - 2.2.0-rc15  3/25
Verified fixed
