### ISSUE TITLE
Support 1.12.6 for Alibaba Cloud ACK

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19148]
rancher/rancher:v2.2.0-rc2

Now 1.12.6 is the only available version for managed k8s. 
But in Rancher UI there is only 1.12.4  available which cannot be used now. 
Users have to input `1.12.6-aliyun.1` manually for Alibaba Cloud ACK

**Comment by westlywright** [comment]
The fix is in tag 2.2.18, master is not merged yet.

**Comment by westlywright** [comment]
should be in master now too

**Comment by loganhz** [comment]
Validated in 2.2.0-rc14 and master. Now we can add managed k8s with default setting. 
`1.12.6-aliyun.1` is the default version and workloads/shell works well.

**Comment by loganhz** [comment]
The only change is the k8s version from 1.12.4 to 1.12.6. Before the managed cluster can not even provision. Now it is functional.

**Comment by rootwuj** [comment]
Version - 2.2.0-rc15  3/25
Verified fixed
