### ISSUE TITLE
Monitoring crashes on 2.2.0RC-13

### ISSUE THREAD

**Issue by riaan53** [rancher/rancher#19145]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Dont know the exact steps but happened a few times. Looks like it crashes when theres a bit of load from Grafana side and struggles to recover. We generate some network traffic with iperf to test something else and then monitor it on the nodes and cluster Grafana page with an update rate of 10s. 

**Result:**
Prometheus and prometheus-agent crashes.

![image](https://user-images.githubusercontent.com/7716342/54930938-d570d480-4f20-11e9-9872-32bec94f74fa.png)

```
level=warn ts=2019-03-25T14:48:52.452784826Z caller=main.go:295 deprecation_notice="\"storage.tsdb.retention\" flag is deprecated use \"storage.tsdb.retention.time\" instead."
level=info ts=2019-03-25T14:48:52.453046068Z caller=main.go:302 msg="Starting Prometheus" version="(version=2.7.1, branch=HEAD, revision=62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)"
level=info ts=2019-03-25T14:48:52.453152698Z caller=main.go:303 build_context="(go=go1.11.5, user=root@f9f82868fc43, date=20190131-11:16:59)"
level=info ts=2019-03-25T14:48:52.453254273Z caller=main.go:304 host_details="(Linux 4.14.85-rancher #1 SMP Sat Dec 1 12:40:08 UTC 2018 x86_64 prometheus-cluster-monitoring-0 (none))"
level=info ts=2019-03-25T14:48:52.453351163Z caller=main.go:305 fd_limits="(soft=1000000, hard=1000000)"
level=info ts=2019-03-25T14:48:52.453444294Z caller=main.go:306 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-03-25T14:48:52.457097107Z caller=web.go:416 component=web msg="Start listening for connections" address=127.0.0.1:9090
level=info ts=2019-03-25T14:48:52.456881773Z caller=main.go:620 msg="Starting TSDB ..."
level=info ts=2019-03-25T14:48:52.462002976Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1553513977668 maxt=1553515200000 ulid=01D6TMPSNVPVZ73PPX7R00MBG9
level=warn ts=2019-03-25T14:48:52.463578724Z caller=wal.go:116 component=tsdb msg="last page of the wal is torn, filling it with zeros" segment=/prometheus/wal/00000003
level=warn ts=2019-03-25T14:49:23.371099985Z caller=head.go:440 component=tsdb msg="unknown series references" count=88527
level=info ts=2019-03-25T14:49:23.885054937Z caller=main.go:635 msg="TSDB started"
level=info ts=2019-03-25T14:49:23.885704301Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-03-25T14:49:24.061997086Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T14:49:24.08395222Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T14:49:24.09450321Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T14:49:24.10044777Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T14:49:24.118638441Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-03-25T14:49:24.119196738Z caller=main.go:589 msg="Server is ready to receive web requests."
level=error ts=2019-03-25T14:49:27.483144369Z caller=notifier.go:481 component=notifier alertmanager=http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts count=0 msg="Error sending alert" err="Post http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts: dial tcp: lookup alertmanager-operated.cattle-prometheus on 10.43.0.10:53: no such host"
```

```
INFO[2019-03-25T14:53:47Z] listening on 10.42.224.7:9090, proxying to http://localhost:9090 with ignoring 'remote reader' labels [prometheus,prometheus_replica], only allow maximum 512 connections with 5m0s read timeout .
INFO[2019-03-25T14:53:47Z] Start listening for connections on 10.42.224.7:9090
2019/03/25 14:53:55 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:53:56 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:05 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:06 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:15 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:16 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:25 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:26 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:35 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:36 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:45 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
2019/03/25 14:54:46 http: proxy error: dial tcp 127.0.0.1:9090: connect: connection refused
```

**Environment information**
- Used latest Rancher RC (rancher/rancher:v2.2.0-rc13)
- 3 node HA install via RKE

**Cluster information**
- Machine type (cloud/VM/metal) and specifications (CPU/memory):

vmware 4 vCPU, 8GB mem

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version (use `docker version`):

```
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thxCode** [comment]
a similar issue: https://github.com/rancher/rancher/issues/18441

**Comment by riaan53** [comment]
I dont know if its related but with the default settings when monitoring is enabled on Rancher (500Mb ram) the prom container its getting OOM killed the whole time. This cluster is not tested with iperf just bare 3 node RKE + rancher (2.2.0RC-13) HA installed and playing on Grafana page. The cluster was created +/-12h. I upped the memory to 1Gb to see if that helps.

<img width="1477" alt="Screenshot 2019-03-26 at 08 15 26" src="https://user-images.githubusercontent.com/7716342/54978702-caae5200-4fa9-11e9-8c6c-6391e871ba69.png">
<img width="1487" alt="Screenshot 2019-03-26 at 08 20 40" src="https://user-images.githubusercontent.com/7716342/54978707-cc781580-4fa9-11e9-9dba-5b760e9dc528.png">

**Comment by rbq** [comment]
Same here, the Prometheus container gets OOMKilled over and over. Trying my luck with 1Gi as well.

**Comment by cjellick** [comment]
The docs have a guide on the resource consumption you should expect. Hopefully that helps https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/#resource-consumption

**Comment by rbq** [comment]
@cjellick Thanks! Found the settings under Tools → Monitoring and increased it there. I only have three nodes though.

Btw., I think the defaults should be increased so that monitoring works out of the box.

**Comment by IsNull** [comment]
> Btw., I think the defaults should be increased so that monitoring works out of the box.

Yes, the limit should probably not be that conservative.
Optimally, the default value should depend on the number of nodes in the cluster. A single node works out of the box (was my test setup), the staging system with 3 nodes got the same OOMKills issue.

* 1 Node: 500Mi Memory is sufficient
* 3 Nodes: 500Mi Memory leads to OOMKills, fixed with >= 1000Mi

**Comment by thxCode** [comment]
@rbq , @IsNull , it's difficult to decide what count is enough for `out of the box`. I have detailed the default resources on https://github.com/rancher/rancher/issues/19078#issuecomment-477009261, I think users need to consider it by self according to the cluster, meanwhile, the rancher document is a useful thing, https://github.com/rancher/rancher/issues/19145#issuecomment-476725944.

**Comment by rbq** [comment]
@thxCode Could the chart (or wherever the application configuration comes from) determine the resource usage using some basic arithmetic operations? The user questions could be the base amount of memory, memory per node and node count (for the request), as well as a safety factor (for the limit). Maybe the operator could even query the node count and scale resources even after deployment? Or the UI could at least pre-fill the setting when you enable monitoring?

**Comment by vincent927** [comment]
Same problem V2.2.0

**Comment by rbq** [comment]
Prometheus doesn't seem to be the only workload with resource issues. On one of my three hosts the Pod deployed by the `exporter-node-cluster-monitoring` DaemonSet crashes every couple of hours when reaching 50 MiB.

<img width="764" alt="exporter-node-cluster-monitoring" src="https://user-images.githubusercontent.com/68766/55396428-2c3f6500-5544-11e9-8a9b-6e2e682615bc.png">

At the same time I find it curious that the node exporter on this host not only uses twice the memory but up to 40 (!) CPU cores, compared to close to zero on the other ones. The software on my three nodes is mostly identical, but the problematic host is considerably more performant (96 Cores vs. < 20 Cores) runs a bunch of Nvidia GPUs using nvidia-docker2, device plugin, etc. Comparing the log output of the node exports I see that they use exactly the same set of collectors though (bcache, bonding, conntrack, cpu, diskstats, edac, entropy, filefd, filesystem, hwmon, infiniband, ipvs, loadavg, mdadm, meminfo, netclass, netdev, netstat, nfs, nfsd, sockstat, stat, textfile, time, timex, uname, vmstat, xfs, zfs). What is this one guy doing there?

**Comment by thxCode** [comment]
@rbq , is it a cfs_throttled CPU seconds? It seems the hight memory usage correlate to CPU throttling, maybe some goroutine leak. Can you install golang on that problematic host and dig out some information by:
```
## Log the top10 inuse memory entry
go tool pprof -inuse_space http://${HOST_IP}:${NODE_EXPORT_PORT}/debug/pprof/heap
top10

## Log the heap usage
go tool pprof -alloc_space -cum -svg http://${HOST_IP}:${NODE_EXPORT_PORT}/debug/pprof/heap > heap.svg

## Log the goroutine debug
curl http://${HOST_IP}:${NODE_EXPORT_PORT}/debug/pprof/goroutine?debug=2 > go_debug_2.log
```

**Comment by loganhz** [comment]
@rbq could you try to increase the limit for node exporter, please?

**Comment by rbq** [comment]
@loganhz Oh, yes, I did that earlier. Seems like it's been running without any restarts since then.

<img width="627" alt="metrics" src="https://user-images.githubusercontent.com/68766/55427170-b5778b80-5586-11e9-832e-4b935946b77a.png">

**Comment by rbq** [comment]
@thxCode Does collecting that information still make any sense, now that it runs relatively normal?

**Comment by loganhz** [comment]
@rbq Thanks for your update. The current 50Mi limit for node exporter is too small. We will increase the default value and make it configurable via Rancher UI. It will be out in 2.2.2.

For anyone else running into the same issue such as `OOMKill`,  please increase the Prometheus or Node exporter cpu/memory limitations in enable monitoring page. 

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/#resource-consumption

**Comment by rbq** [comment]
@loganhz Cool, thx!

**Comment by davidnuzik** [comment]
I am posting my findings by testing with v2.2.1 (rc was not yet available at the time testing started). This information does not invalidate anything discussed i.e. the rise seen in memory usage for the node exporter. I was simply asked to report my findings as a comment here.

I tested with v2.2.1 with a 3-node cluster. I observed about 10-12MB of memory usage per pod for the node exporter. I scaled up a test workload to 100 pods on my cluster and saw memory rise about 2MB. I scaled up to about 200 pods and saw memory rise no higher than about 21MB per pod. (nearly maxing out my 220 pod capacity)

I think in our situation we simply didn't have the exact same configuration and environment as @rbq and so that is why we had no issues with our node exporter memory. My guess is we would need a notably larger cluster that can take on many more workloads/pods. In such a situation we would likely see what @rbq observed.

We also tested for a long length of time to ensure there isn't any noticeable memory leak in node exporter. Memory did not rise when pod count stayed constant for the cluster after about 16+ hours of monitoring.

---

I am glad we now have an option to configure memory for the node exporter the default now is 100MB as well. I will be validating in v2.2.2-rc1 in issue #19343 (the new monitoring config options and defaults). Again this comment is only to report my findings with my specific QA setup as we might need this information later.

**Comment by davidnuzik** [comment]
New monitoring node exporter cpu/memory limit settings were validated here https://github.com/rancher/rancher/issues/19343#issuecomment-479673993 against v2.2.2-rc1 (we plan to check again for v2.3 in this issue)

**Comment by davidnuzik** [comment]
Version: Master (4/4/19) ImageID: 10a1ef90fcbd

The UI now has new defaults for cluster monitoring as pictured below.
As you can see we can now set the Node Exporter CPU Limit and Memory Limit.
Additionally, the Prometheus default memory limit is now 1000MiB which is a more reasonable value to start with.

![image](https://user-images.githubusercontent.com/45179589/55569009-a5aa9500-56b5-11e9-9160-d654a64fa1ba.png)

I ensured that we can enable cluster monitoring and these defaults and custom settings take effect. Further, we can make changes here, save, and the node exporter workload will restart the pods so the containers now have the updated values for node exporter cpu limit and memory limit.

HTTP / UI looks good. There is also now a minimum requirement for your cluster to have at least 1200 milliCPU available and this working see #19078

I smoke tested this area, tried putting in various values for node exporter CPU/Memory limits and did not encounter any issues. Each time the pods restarted and set new limits I specified.

The defaults are:
30Mi memory reservation (hard coded default)
200Mi memory limit (configurable when go to Tools > Monitoring)

100m cpu reservation (hard coded default)
200m cpu limit (configurable when go to Tools > Monitoring)

Upon submit enable/edit monitoring default answers are (HTTP):
`exporter-node.resources.limits.cpu: "200m"`
`exporter-node.resources.limits.memory: "200Mi"`

**Comment by doog33k** [comment]
excellent news.

**Comment by MSandro** [comment]
I am running rancher v2.2.2 and enabled the cluster monitoring. After a few minutes Prometheus crashes because of a very simular error:
`level=error ts=2019-05-06T15:13:49.530747807Z caller=notifier.go:481 component=notifier alertmanager=http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts count=0 msg="Error sending alert" err="Post http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts: dial tcp: lookup alertmanager-operated.cattle-prometheus on 10.43.0.10:53: no such host"`

I am not completely sure but I think the monitoring app din't deploy a alertmanager on my nodes. I can't find it.

**Comment by bruno-lopes** [comment]
When I enable Prometheus Persistent Storage, I get this error. Without this, it works fine.

**Comment by ansilh** [comment]
@bruno-lopes Please check https://github.com/rancher/rancher/issues/17256 that fixes the issue when enabling with Persistent Storage.

**Comment by hadifarnoud** [comment]
changing node exporter memory limits did not fix my issue. I changed it to 400Mi
