### ISSUE TITLE
[rancher-python]

### ISSUE THREAD

**Issue by RRadziejewski** [rancher/rancher#19140]
Hello,

I have a question about rancher python api.
I need functionality to launch launcher app from catalog.
For now i am using below code.

`
launchAppRequestData = {

            "projectId": projectID,
            "name": appName,
            "prune": False,
            "type": "app",
            "targetNamespace": namespace,
            "externalId": "catalog://?catalog=" + catalogue.lower() + "&template=" + appName.lower() + "&version=" + appVersion}`
requests.post(self.rancherServerAddress + '/projects/' + projectID + '/apps', data=launchAppRequestData, auth=self.accessToken, verify=self.checkSSLFlag).ok

I am trying to dig in into rancher python api.
Is it possible to run app somehow similar to above code through api client in python itself?
Or is it neccesary to use raw requests?

![chrome_2019-03-25_12-39-15](https://user-images.githubusercontent.com/32438378/54916985-11913e80-4efb-11e9-9c45-57dbb4c95b87.png)

There is operation available but i cannot get which method if there is one is responsible for that in api and on what resource. Could someone help me ?

**Comment by RRadziejewski** [comment]
I believe the same goes for replicaSets DaemonSets Jobs Workloads , is it possible to do it via API?

**Comment by Razikus** [comment]
Why this action to create app isn't listed in projects action list?

**Comment by dramich** [comment]
Hey @RRadziejewski, yes you can do this through the python client. Anything that exists in rancher can be done through the python client as it is auto generated based off the schema of the server you are using it with. 

For the apps, you need a project client as they live under a project. The same is true for the other resources you mentioned as well. 

```python
project_url = project.links.self + '/schemas'
project_client = rancher.Client(url=project_url, verify=False, token=<api_token>))
project_client.create_app(...)
```

@Razikus Creating an app is not a project action, actions affect the resource they live on. Check [here](https://github.com/rancher/api-spec/blob/master/specification.md#actions) for more info.

**Comment by RRadziejewski** [comment]
Thank you for your answer dramich.
I have also a question how to access v3-public api to login with username and password through the api?

**Comment by dramich** [comment]
You can access it through `v3-public/localProviders/local?action=login` based off just local auth. If you enabled a provider you can't do it through the API as we redirect to the provider for login. If using the python client you should have an api token to use with it as we don't support the login flow when it's not being done through the UI.

**Comment by deniseschannon** [comment]
@RRadziejewski if you have any more questions, please open a new issue.
