### ISSUE TITLE
Auto rotate self signed server certificate when it is close to expiration

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19154]
On a standalone rancher install, a server generated self signed certificate gets an expiration of 1 year. We have to add a certificate monitor logic - can run once a day - that would regenerate the cert when it's close to expiry. 

Here is the place where the cert gets generated:

https://github.com/rancher/rancher/blob/master/pkg/dynamiclistener/server.go#L391

The way to check the certificate expiration time:

```
curl https://<rancher server ip>/v3 -lkv

Connected to <rancher server ip> port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*      server certificate verification SKIPPED
*      server certificate status verification SKIPPED
*      common name: cattle (does not match '54.191.101.165')
*      server certificate expiration date OK
*      server certificate activation date OK
*      certificate public key: RSA
*      certificate version: #3
*      subject: O=the-ranch,CN=cattle
*      start date: Fri, 22 Mar 2019 04:30:25 GMT
*      expire date: Sat, 21 Mar 2020 04:31:33 GMT

```

**Comment by sangeethah** [comment]
@mrajashree , Could you provide some details on how this feature works?
1. how often does the thread to do cert expiry will run ? Is this configurable ? 
2. What  is the exact expiry check that will result in cert rotate to happen ? Is this configurable ? 
3. Can cert rotate be triggered after the cert is expired ?

**Comment by sowmyav27** [comment]
verified on `rancher:master` (04/23/2019)

Verified with a custom image provided by @mrajashree for v2.2.x.
Steps taken:

1. Create a cluster in rancher using image custom provided.
2. Verified the Rancher server certs. (expiry of 30 minutes)
3. Verified new certs are generated after 20 minutes(customized)
4. Verified certs expiry using command - curl https://x.x.x.x/v3 -lkv - Expiry was 30 minutes.
5. Verified rancher cli - commands work fine.
6. Pre upgrade scripts (automation) passed.
7. Upgrade to rancher:master.
8. Verified new certs are generated. Message Rancher server cert expires at <date> <Time >+0000 UTC, generating new cert will be seen in the logs.
9. Verified new certs have an expiry of 1 year, using command - curl https://x.x.x.x/v3 -lkv
10. Verified rancher cli - commands worked fine, with the token and certs from before upgrade.
11. Verified post upgrade scripts (automation) passed.
