### ISSUE TITLE
Removed certificates shows up in UI until the page is refreshed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1915]
Server version - Build from master Aug 28

Steps to reproduce the problem:
Remove a certificate.
It continues to shown in "Removed" state . Even after shifting between other tabs like "hosts"/"containers" and returning back to "Certificates" tab , we still see the "Removed" certs listed. Doing a manual reload of the page results in removed entries not being listed anymore.

**Comment by vincent99** [comment]
Dupe of #1903.
