### ISSUE TITLE
Change %taintsSection.detail% text

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19158]
Version 2.2. (Master) 3/25/19

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Go to the node details page. Look at the taints seciton subtext. 
![image](https://user-images.githubusercontent.com/45179589/54950951-b877d980-4eff-11e9-9479-566a55460dd8.png)

**Result:**
This text is a bit confusing. Perhaps we should change it to something closer to what the k8s docs describe https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
We may need to ask someone for a better description per the k8s docs as the current text is confusing. Taints seem to affect nodes not necessarily pods, pods just need to match the toleration?

**Comment by loganhz** [comment]
Please let me know the text. I will submit a PR to fix it.

**Comment by davidnuzik** [comment]
@deniseschannon do you have any suggestions? or perhaps @vincent99 ?
I was thinking it could be worded better per the issue description (see k8s docs) it was a little confusing to me but I'm not great with k8s and am not sure the best text for this.

**Comment by vincent99** [comment]
`Ensure workloads only run on appropriate nodes by adding taints to nodes and tolerations to workloads`?

**Comment by davidnuzik** [comment]
I think that makes sense and is pretty clear ^^ @vincent99 @loganhz 
How about we use that @loganhz ?

**Comment by davidnuzik** [comment]
Version: Master (4/23/19)

Confirmed this is resolved. The suggested text is in place:
![image](https://user-images.githubusercontent.com/45179589/56616282-da817c00-65d1-11e9-9076-5df8f74ed008.png)
