### ISSUE TITLE
UI: Catalog Usability Issues

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19165]
Version: v2.2.0-rc14

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, Usability

**Steps to reproduce (least amount of steps as possible):**
- Visit the apps page and launch
- Notice that Partner cards have a gold border. This makes it look like they are focused and that we can potentially use arrow keys to navigate (change focus) of cards.
![image](https://user-images.githubusercontent.com/45179589/54960010-495aaf00-4f18-11e9-987d-a33a5072b4b6.png)
- Notice that we cannot click on the app logo to view the details. It is not hyperlinked.
![Screen Shot 2019-03-25 at 4 09 24 PM](https://user-images.githubusercontent.com/45179589/54960067-7e670180-4f18-11e9-8352-45c2042d732e.png)

**Result:**
These areas can be a little confusing to new users.

**Other details that may be helpful:**
This could have some impact on accessibility.

**Comment by deniseschannon** [comment]
other feedback from when trying to find partners, the `(from Library)` is not clear to new users who aren't used to the catalog.

**Comment by tfiduccia** [comment]
Issue #1 - Gold border: After talking to Will and Sheng they like the border and want to keep it.
Issue #2 - Click on logo to get to details: We are removing the details button and making the whole box a button.
Issue #3 - (from Library): This is going to be removed and each "catalog" is going to be in its own section.

I'm going to send back to David as resolved.

**Comment by davidnuzik** [comment]
I am closing the issue (no changes as of yet for how UI shows catalogs). Refer to Tani's comment above for details. https://github.com/rancher/rancher/issues/19165#issuecomment-512606197
