### ISSUE TITLE
native docker rancher labels to register container to service

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#1916]
Hi there,
is there somewhere an overview of rancher labels able to assign to a container?
In my case I want to start a container with native docker. This container should be under a specific rancher service (resolvable within rancher network). After some parsing of open/closed issues I guess the best way to do this is with docker/rancher-compose?
Something with an example would be awesome.

p.s.: i played a bit around with rancher labels that I could find. e.g. `io.rancher.container.network=true` but this seems not to work anymore. Never got it into managed rancher network.

**Comment by deniseschannon** [comment]
Yes, we will be providing a labeling section in our docs shortly to help provide the overview of labels. 

To start containers as services in Rancher, you'll need to use rancher-compose. Have you looked into docker-compose? We follow all the same functionality as docker-compose and only add additional functionality that is supported in Rancher.

If you provide your native docker command, I could put up what the docker-compose.yml equivalent would be.

**Comment by fentas** [comment]
Thanks for the offer! But I guess I am fine. Labeling section would be awesome.
Besides of that how can I implement the health check within rancher-compose?

**Comment by fentas** [comment]
I guess labeling section is now there more or less. http://docs.rancher.com/rancher/labels/
I will open for health check a new issue in rancher/rancher-compose.

**Comment by deniseschannon** [comment]
Yes, I just added the labels docs yesterday and had created the PR for the health check, but didn't push it yet. There is a docs repo if you ever see documentation missing. You can file tickets there. 

https://github.com/rancher/rancher.github.io/issues
