### ISSUE TITLE
Catalog App - need to click the launch button twice to get the app launched

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19168]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- go to `App` -> `Launch` to launch an app from the existing list
- click the `Launch` button  
<img width="1485" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/54961329-6e055580-4f1d-11e9-9db8-c883e2600015.png">

**Result:**
I need to click the launch button twice to get it work.
For the fist time I click the buttion, the console will show this error
```
namespaces "redis-dmqsz" is forbidden: User "u-dhy4qez6jp" cannot get resource "namespaces" in API group "" in the namespace "redis-dmqsz"
```
<img width="1735" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/54961389-ab69e300-4f1d-11e9-8e31-70841fe0a4a9.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.0-rc14
- Installation option (single install/HA): Single Install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by sangeethah** [comment]
This issue is easily reproduces in the following case:

As admin , create a cluster - `cluster1` and assign `user1` as cluster member.

Log in as `user1`.
Create a project.
Deploy an App in this project.
Notice that when you click on "launch" for the first time , api errors out - ```{baseType: "error", code: "Forbidden",…}
baseType: "error"
code: "Forbidden"
message: "apps.project.cattle.io is forbidden: User "u-qxd6dri3v2" cannot create resource "apps" in API group "project.cattle.io" in the namespace "p-ljh9c""
status: 403
type: "error"```
This error seen by api is not shown in the UI.
Click again and the app will successfully deploy.

**Comment by davidnuzik** [comment]
Note: Validated against v2.2.2-rc1 in #19337 (but will need to be checked again in v2.3)

**Comment by davidnuzik** [comment]
Version: Master (4/15/19)

I validated this again in the latest master for v2.3. I followed the steps that Sangeetha outlined above https://github.com/rancher/rancher/issues/19168#issuecomment-477388917 and I do not see the console error nor do I have to click the Launch button twice.

The application (Redis in my case) launched without any issues. I also tried with a couple of other applications.
