### ISSUE TITLE
Feature Request: Deploy k3s cluster from Rancher

### ISSUE THREAD

**Issue by gabrielcalderon** [rancher/rancher#19169]
Currently there's no way to deploy k3s cluster from Rancher. The only work around is to first create the cluster/nodes and then import it into Rancher.

Expected behavior: Deploy k3s cluster from Rancher.

Are there any plans to support this?

**Comment by cjellick** [comment]
Not in the near term. We are going to keep it as import-only for the time-being. We are still feeling out how k3s fits into the ecosystem and experimenting with it.
