### ISSUE TITLE
incorrect information on global dns entries for how to program your ingress

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#19162]
This helper text in global dns entries was incorrect:

```To finalize configuring this Global DNS entry, you must add the following annotation label ( rancher.io/globalDNS.<HOSTNAME> ) on the ingress for your application or project, where <HOSTNAME> is the host name used in the routing rules of your ingress. This <HOSTNAME> must also match the FQDN of this Global DNS entry.```

It must be updated to:
```To finalize configuring this Global DNS entry, you must add the following annotation ( `rancher.io/globalDNS.hostname` ) on the ingress in your application or in your project. The value of this annotation should be the hostname used in the routing rules of your ingress and match the FQDN of this Global DNS entry. ```

**Comment by westlywright** [comment]
2.2.19

**Comment by davidnuzik** [comment]
Version: v2.2.0-rc15
Confirmed the UI now shows this for BOTH "Multi-Cluster App" and "Projects" selection when creating a GDNS entry (_or editing as well_). This section has now been moved above as well. The text is exactly as requested per the issue description.

Text:
>To finalize configuring this Global DNS entry, you must add the following annotation ( `rancher.io/globalDNS.hostname` ) on the ingress in your application or in your project. The value of this annotation should be the hostname used in the routing rules of your ingress and match the FQDN of this Global DNS entry.

Screenshots:
![image](https://user-images.githubusercontent.com/45179589/54961721-10720880-4f1f-11e9-9acc-918c2f389c68.png)
![image](https://user-images.githubusercontent.com/45179589/54961726-18ca4380-4f1f-11e9-8cda-5e5f80e5c4eb.png)
