### ISSUE TITLE
Feature request - add k8s controller-manager and etcd metrics to standalone RKE created cluster + HA Rancher install

### ISSUE THREAD

**Issue by riaan53** [rancher/rancher#19163]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Create a cluster with RKE and install HA rancher via helm. 

**Result:**
All metrics except controller-manger and etcd are available.

**Other details that may be helpful:**
All etcd certs are available in RKE created config map in kubernetes (full-cluster-state) so all information is available to add them to the metrics.

rancher 2.2.0 RC13

**Comment by superseb** [comment]
This is going to be fixed in https://github.com/rancher/rancher/issues/18044
