### ISSUE TITLE
Menu item - Multi-Cluster Apps and Global DNS not visible

### ISSUE THREAD

**Issue by pirminjanka** [rancher/rancher#19178]
**What kind of request is this (question/bug/enhancement/feature request):**
question or bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher Server 2.2.0-rc15
Login to the UI as admin

**Result:**
menu item - Multi-Cluster Apps and Global DNS are not visible in Global Section

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-rc15
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`): v1.12.5-gke.5

- Docker version (use `docker version`):

```
lient:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:56:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Tue Feb 12 22:47:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
Multi cluster apps are under Apps in the Global view, and Global DNS is only supported in HA setup. This will be outlined in release notes/docs when it is released.
