### ISSUE TITLE
Add target Port to Service Discovery interface

### ISSUE THREAD

**Issue by pseckd** [rancher/rancher#19175]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Go to worloads -> Service Discovery -> Add Record, choose "One or more external IP addresses" -> Add the record

**Result:**
The target port is allways 42 (the default).
You can add a record for an external IP Address but not a target Port in the interface. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher (v2.2.0-rc13)
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
Please try 2.2.0. There is an advanced section in service page. You can configure everything for a k8s service
