### ISSUE TITLE
Kubelet  volume-plugin-dir 

### ISSUE THREAD

**Issue by vincent927** [rancher/rancher#19172]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1.I deploy a rook and ceph block storage 
2.And start a mysql pod error 

**Result:**

```
Warning | FailedScheduling | pod has unbound PersistentVolumeClaims (repeated 2 times) | 23 minutes ago
Normal | Scheduled | Successfully assigned default/wordpress-mysql-6d9d576684-254c9 to node2 | 23 minutes ago
Warning | FailedMount | Unable to mount volumes for pod "wordpress-mysql-6d9d576684-254c9_default(59d6a78d-4ed3-11e9-a352-00163e0e2e83)": timeout expired waiting for volumes to attach or mount for pod "default"/"wordpress-mysql-6d9d576684-254c9". list of unmounted volumes=[mysql-persistent-storage]. list of unattached volumes=[mysql-persistent-storage default-token-plcdj] | a few seconds ago
```

**Other details that may be helpful:**

I find this doc https://rook.io/docs/rook/v0.9/flexvolume.html , and  update kubelet config by edit host  ```/etc/kubernetes/ssl/kubecfg-kube-node.yaml```  add 
```
services:
  kubelet:
    extra_args:
      volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    extra_binds:
      - /usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec
```
and restart kubelet container . But it does not seem to take effect . Rancher start kubernetes kubelet default volume-plugin-dir is ```/var/lib/kubelet/volumeplugins```. How can i change it ?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.1.6
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):8CPU/32G RAM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by switchboardOp** [comment]
@vincent927 did you ever figure it out?

**Comment by vincent927** [comment]
> @vincent927 did you ever figure it out?

change the operator.yaml like this 
```
 - name: FLEXVOLUME_DIR_PATH
   value: "/var/lib/kubelet/volumeplugins"
```
