### ISSUE TITLE
Add custom RBAC roles for Logging

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#19181]
We should have built-in roles for people manage logging like we do for other components https://rancher.com/docs/rancher/v2.x/en/admin-settings/rbac/cluster-project-roles/#cluster-role-reference.

Add roles for cluster:
- Manage cluster logging configuration
- View cluster logging configuration

Add roles for project:
- Manage project logging configuration
- View project logging configuration

**Comment by cjellick** [comment]
Is this coming from a real user? I don't strongly believe that people actually use these fine-grained roles and I'd rather not add more if we dont need to
