### ISSUE TITLE
upgrade Agent version and component on Windows 1803 host

### ISSUE THREAD

**Issue by fedeostrit** [rancher/rancher#19183]
hello, I have a cluster v2.2.0 with 3 nodes, two are linux Centos v7 with roles: etcd, control plane and worker
later I have another node with windows 1803 with role worker.
the problem I have is that the cluster in the linux nodes updates the components themselves and deploys them when I perform an update but in the window node this does not happen, I was running the agent rancher agent: v2.2.0-r6-nanoserver-1803 because until today there was no other available, now I want to update the agent to rancher-agent: v2.2.0-nanoserver-1803 but there is not a script that does it or a note in Rancher to explain this procedure in a clean way

**Comment by fedeostrit** [comment]
another problem I have with adding a host windows 1803 with kubernates v1.13.4 is that the host does not register since there is a kubelet parameter that is not taking this version, if I leave the version kubernetes v1.11 if it is possible to add to the cluster but I thought that in the version rancher v2.2 this problem with the windows agent was going to solve


F0326 12:55:36.269829    5920 server.go:147] unknown flag: --cadvisor-port

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19176
