### ISSUE TITLE
Upgrade to Rancher 2.2 GA: Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#19189]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** Upgrade Rancher using rancher-latest/rancher repo via Helm

**Result:** Previously provisioned Custom cluster is stuck with the following status "Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system"

**Other details that may be helpful:** I had previously upgraded this Rancher instance to 2.2.0-alpha6 and also enabled Prometheus monitoring on the custom cluster.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.11.6
- Docker version (use `docker version`): 18.9.2

**Comment by alena1108** [comment]
@eroji 

> I had previously upgraded this Rancher instance to 2.2.0-alpha6 and also enabled Prometheus 
monitoring on the custom cluster.

There is no support from alpha and rc releases to GA. Many things changed in between them, and upgrade can cause issues. 

Can you try a fresh install. Or if you have an official Rancher 2.1.x or 2.0.x install, see if upgrading to Rancher 2.2 causes the same issue.

**Comment by panho66** [comment]
Installed rancher v2.2.1 HA and add custom cluster with nodes. It seems ok no problem. 
But I got the error message below to install Rancher HA Cluster local using RKE as recommended in https://rancher.com/docs/rancher/v2.x/en/installation/ha/

 **Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system**

Steps
Create cluster.yaml
Rke up

It seems timing issue with RKE command line and run RKE up again work.

![image](https://user-images.githubusercontent.com/15118220/55272682-3c70fd80-5314-11e9-83d0-0e47650c41b2.png)

**Comment by panho66** [comment]
Rancher v2.2.1 add 3 nodes to custom cluster . It is slow than previous version, 2,1, 2.2apha6 causing my script to time out but eventually node added.  
![image](https://user-images.githubusercontent.com/15118220/55275397-933cfe00-5339-11e9-8763-d419ac0a86e2.png)
![image](https://user-images.githubusercontent.com/15118220/55275399-9fc15680-5339-11e9-9fab-5feff2bdda59.png)
![image](https://user-images.githubusercontent.com/15118220/55275409-abad1880-5339-11e9-8a98-11832ced70ad.png)
![image](https://user-images.githubusercontent.com/15118220/55275414-d1d2b880-5339-11e9-8f24-2c1dbb3a8d74.png)

**Comment by deniseschannon** [comment]
We haven't seen this issue in our upgrade tests for the most recent releases. If you hit this again, please open a new issue.

**Comment by ekristen** [comment]
I recently ran into this issue, it turns out that my nodes had Disk Pressure, so k8s was evicting pods. Once I resolved that issue, rke ran normally.

**Comment by wc-matteo** [comment]
It happened to me when I was using a relatively slower disk as the docker root. So it seems related to disk pressure/speed.
