### ISSUE TITLE
Support for IdP-initiated SSO for Okta SAML 

### ISSUE THREAD

**Issue by kutchar** [rancher/rancher#19196]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Configure Okta as a SAML provider in Rancher
2. Configure Rancher as an application in Okta
3. Verify configuration works by logging into Rancher using Rancher's login window (auth works when Rancher initiates login) (SP-initiated flow)
4. Try logging in to Rancher by clicking on the Rancher "chiclet" in Okta (IdP-initiated flow). This fails with the error "Logging in failed: Your account may not be authorized to log in.". But if you click on the "Log In with Okta" then you can login.

**Result:**
IdP-initiated flow fails with the error "Logging in failed: Your account may not be authorized to log in.".

**Other details that may be helpful:**
https://support.okta.com/help/s/article/Beginner-s-Guide-to-SAML

**Environment information**
- Rancher version: v2.2.0
- Installation option: single install

gz#6690

gz#9821

**Comment by mrajashree** [comment]
That's because IDP initiated SSO isn't allowed.

**Comment by kutchar** [comment]
@mrajashree Ah I see! Are there any plans of supporting IDP initiated SSO?

**Comment by DominicGunn** [comment]
+1 on this. Any plans on IDP support?

**Comment by zishan** [comment]
+1 is this present in the upcoming 2.4 release?

**Comment by stephenwolfe1** [comment]
+1

**Comment by mshade** [comment]
Another +1 for this

**Comment by savealive** [comment]
yet another +1 for this

**Comment by dlippiatt** [comment]
+1 here as well.

**Comment by sadhugit** [comment]
+1

**Comment by sadhugit** [comment]
Is it specific to Okta or applicable for other SAML providers like keycloak?

**Comment by bdobsonca** [comment]
+1 I just enabled OKTA integration which was going wonderfully until users could not login from the primary OKTA page via SSO. If they go directly to the site, OKTA works just fine but this seems to be a fairly large gap in functionality that people would expect from OKTA integration.

**Comment by josh-at-imperva** [comment]
I have the same issue on KeyCloak... When I able debug logging, I get the error:
ERROR: `InResponseTo` does not match any of the possible request IDs (expected [])

**Comment by M1kep** [comment]
@mrajashree or @deniseschannon  Any chance you could shed some light on what the the limitations are? I'm confused as to why this is limited currently. 

IDP Initiated SSO doesn't require Just in Time provisioning, so Rancher could still be in full control of Authorization, while allowing the IDP to be in control of Authentication
