### ISSUE TITLE
rancher can not delete pods after scale deployment

### ISSUE THREAD

**Issue by sharif-rahman** [rancher/rancher#19204]
**The Pods  old container stays for ever**
- How can i get Rid of this problem?
- Advice me any other possible solution would be appreciated. 

**Tried approaches: Still the same problem**
- Deploying completely new app from scratch.
- Redeploying same app by scale 0 and 1.

**Result:**
![image](https://user-images.githubusercontent.com/45973680/55056607-dad83700-5066-11e9-9e97-527a8a4ef675.png)

**Environment information**
- Rancher version : v2.1.5
- Docker version : 1.13.1
- kubernetes: 1.11.6

**Comment by IsNull** [comment]
Did you try to delete the pod using the UI? (Click on the offending pod, and then choose delete in the upper right menu)

<img width="335" alt="Screenshot 2019-03-27 at 08 43 44" src="https://user-images.githubusercontent.com/439313/55058508-73bd8100-506c-11e9-9fc9-2548ca1d873d.png">

**Comment by sharif-rahman** [comment]
yes i did it. it still the same problem. i forgot to mention it. thx

**Comment by IsNull** [comment]
In this case you have to use kubectl directly (its also available from the rancher dashboard directly in the browser).

`kubectl delete pods <pod_name> --grace-period=0 --force -n <namespace>`

**Comment by sharif-rahman** [comment]
This works finally. thanks. Is it a bug in Rancher?

**Comment by IsNull** [comment]
I guess rancher does not add the `--force` flag when you click delete. 
It would probably be a nice feature to add a "Force Delete" Button.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17823
