### ISSUE TITLE
v2.2.0 - Not using specified API endpoint as IP address

### ISSUE THREAD

**Issue by ainiml** [rancher/rancher#19205]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Run ansible playbook https://github.com/TheShellLand/antsable/blob/master/playbooks/rancher2.yml
2. Set API endpoint to `https://192.168.86.110:8443`

**Result:**
Wrong IP addressed used for Node

**Other details that may be helpful:**
ip r
```
vagrant@rancher1:~/antsable$ ip r
default via 10.0.2.2 dev enp0s3 proto dhcp src 10.0.2.15 metric 100
default via 192.168.86.1 dev enp0s8 proto dhcp src 192.168.86.110 metric 100
10.0.2.0/24 dev enp0s3 proto kernel scope link src 10.0.2.15
10.0.2.2 dev enp0s3 proto dhcp scope link src 10.0.2.15 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
192.168.86.0/24 dev enp0s8 proto kernel scope link src 192.168.86.110
192.168.86.1 dev enp0s8 proto dhcp scope link src 192.168.86.110 metric 100
```

hostname -I
```
vagrant@rancher1:~/antsable$ hostname -I
10.0.2.15 192.168.86.110 172.17.0.1 10.42.0.0
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.0`
- Installation option (single install/HA): `single`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `custom`
- Machine type (cloud/VM/metal) and specifications (CPU/memory): `vagrant`
- Kubernetes version (use `kubectl version`): `na`

```
(paste the output here)
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

![image](https://user-images.githubusercontent.com/28725423/55061331-e23d1780-5049-11e9-8960-537e612ce4ef.png)

**Comment by superseb** [comment]
The IP address(es) for the node can be specified using flags described at https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/custom-clusters/agent-options/#ip-address-options.

If that doesn't work, please share the exact command used to add the node.
