### ISSUE TITLE
[Pipeline] Support Gitlab repositories found in nested groups 

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#19217]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a nested project hierarchy in GitLab, e.g.
```
ParentGroup
     Project01
     Subgroup - Packages
         Project02
         Project03
    Subgroup - Software
        Project 04
```
2. Create a new user and add this user to `ParentGroup` with `maintainer` permissions
3. Follow Rancher docs to configure a pipeline in the Default project with GitLab, using this user's account/application credentials.
4. Navigate to Pipeline tab and click on fetch/authorize repositorires

**Expected Result:**
All repositories in which user has `maintainer` permissions are listed. In GitLab a user added to a parent group will by default inherit all permissions in every of the subgroups/projects.
In the example above, all 4 projects should be listed.

**Actual Result:**
Only the projects under the parent group are listed.

**Environment information**
- Rancher version: v2.2

**Comment by cjellick** [comment]
@janeczku @loganhz I don't think this should block 2.2 from being marked stable, should it?

**Comment by janeczku** [comment]
@cjellick at least it’s not a regression as it can be reproduced in 2.1.x.

**Comment by gitlawr** [comment]
Dependent on upstream gitlab API issue, see: https://github.com/rancher/rancher/issues/17188
