### ISSUE TITLE
Jenkins Pipeline not working on v2.2

### ISSUE THREAD

**Issue by aliazlan4** [rancher/rancher#19214]
Jenkins pipeline has so many issues in the version 2.2.

Sometimes, pods in the jenkins and docker registery will not start, sometime they starts but pipeline failed at one step or the other. I am testing with pipleline sample apps provided by rancher and i am unable to succeed even once.

**Comment by superseb** [comment]
Please use the issue template and read https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions why it is important to provide the requested information to reproduce issues. Based on the information provided, there is no way to begin investigating the issue. What version of Kubernetes is used, how many nodes with what roles, specifications on the nodes, what steps can be taken to reproduce, what errors are seen (this can be retrieved from the UI in the System project) all helps to root cause the issue and solve it if there is a bug.

**Comment by sharif-rahman** [comment]
Hello.
They are many possible ways to do that. It depends up on the organization which tool is perfect to do.
For example
We can use Jenkins which not recommended from my point
Other possible ways is to use gitlab-ci which is more convenient for rancher as well.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by gitlawr** [comment]
@aliazlan4 Can you elaborate the failure message/info, the cluster/node size of your setup?

**Comment by rootwuj** [comment]
@aliazlan4 @loganhz 
I tested the pipeline example repositories in rancher v2.2.0 and rancher v2.2.1. 
The pipeline can run successfully. Below is my test environment and test steps.

Environment:
Host configuration: AWS/ ubuntu 16.04/ t2.medium/ 40G 
Docker Version: 18.03
Rancher Version: v2.2.0 , v2.2.1 (single)
K8s Cluster Version: v1.13.4

Step:
Enable the example pipeline under the default or newly created namespace.
Run the example pipeline: `pipeline-example-php` `pipeline-example-go` `pipeline-example-maven`.

Result:
Pods in `Docker-registry`, `Jenkins`, `minio` are active.
Pod in `jenkins-slave` is active.
All stages are running successfully.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by pamarquez** [comment]
Hello, 
I'm having issues for deploying the test apps in pipeline from rancher.
My Rancher machine is installed in microsoft Azure (Linux (ubuntu 16.04))
I've imported my cluster up to rancher from K3S nodes 
* 1 master: 2 cores - 4G RAM - ubuntu/xenial64
* 3 agents: 1 core - 1G RAM (each machine). - ubuntu/xenial64
The cluster implementation was made on VirtualBox(Version 6.0.6_Ubuntu r129722) through Vagrant (vers2.2.3).
All firewalls for all machines are off.

It's all working perfectly fine up to the moment I run the pipeline testing rancher has.

The error Jenkins shows off is as follows,



Normal | Scheduled | Successfully assigned p-thf9b-pipeline/jenkins-546c6fbd58-hpqgf to agent03 | an hour ago
-- | -- | -- | --
Normal | Pulling | Pulling image "rancher/pipeline-jenkins-server:v0.1.0" | an hour ago
Normal | Pulled | Successfully pulled image "rancher/pipeline-jenkins-server:v0.1.0" | an hour ago
Normal | Created | Created container jenkins | an hour ago
Normal | Started | Started container jenkins | an hour ago


Warning | Unhealthy | Readiness probe failed: Get http://10.42.3.4:8080/login: dial tcp 10.42.3.4:8080: connect: connection refused | an hour ago
-- | -- | -- | --
Warning | Unhealthy | Readiness probe failed: Get http://10.42.3.4:8080/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers) | an hour ago
Warning | Unhealthy | Readiness probe failed: HTTP probe failed with statuscode: 503 | an hour ago



The pipeline I'm running is "Repositry https://github.com/rancher/pipeline-example-php" and the error it shows of is as follows, 

"Get http://10.43.28.162:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.28.162:8080: connect: no route to host; Setting up jenkins. If it is not deployed, this can take a few minutes.; Get http://10.43.28.162:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.28.162:8080: connect: no route to host"

**Comment by pamarquez** [comment]
@superseb can you please help me out here?
