### ISSUE TITLE
Templated Repository URL for Git-based catalog URL is not showing rancher

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#19215]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Run v2.2.0
* Open Global -> Tools -> Catalogs

See Git-based catalog URL shown as `Git-based catalog URL, e.g. https://github.com//charts.git`

<img width="1070" alt="Screen Shot 2019-03-27 at 14 14 46" src="https://user-images.githubusercontent.com/2620179/55078653-eb0a0980-509a-11e9-9d11-92ce9378ea43.png">

**Result:**
Git-based catalog URL shown as `Git-based catalog URL, e.g. https://github.com//charts.git`

**Expected Result:**
Git-based catalog URL shown as `https://github.com/rancher/charts.git`

**Comment by sharif-rahman** [comment]
Rancher allows us to deploy via helm chats with questions.
Got lab-CI can triggers the rancher envy via pipeline to deploy it.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by cjellick** [comment]
i dont udnerstand the bug @superseb

**Comment by superseb** [comment]
It should show `e.g. https://github.com/rancher/charts.git`, `appName` is not getting translated to `rancher` in this view.

**Comment by davidnuzik** [comment]
Note, validated in v2.2.2-rc1 see https://github.com/rancher/rancher/issues/19339#issuecomment-479591530 just needs check again in v2.3 later.

**Comment by davidnuzik** [comment]
Version: Master (4/4/19) ImageID: 10a1ef90fcbd

I tested again in latest master and had the same findings as in #19339 with v2.2.2-rc1 this is now working.

- Open Global -> Tools -> Catalogs
- Notice Git-based catalog URL shows example CORRECTLY as `https://github.com/rancher/charts.git` url

It used to show incorrectly as `https://github.com//charts.git`
