### ISSUE TITLE
Rancher UI not working after upgrade to 2.2.0

### ISSUE THREAD

**Issue by tomhouweling1987** [rancher/rancher#19213]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Air gapped cluster with rancher v2.1.0 or 2.1.7
Upgrade to 2.2.0

**Result:**
[ERROR] failed to serve UI: Get https://test/ui/latest2/index.html: dail tcp: lookuptest on <IP ADDRESS>: server misbehaving

**Actual Result:**
Working 
Rancher UI on v2.2.0

**Other details that may be helpful:**
Upgrade from v2.1.0 to v2.2.0 gives the same result as upgrade from v2.1.7.
When starting a new container with rancher v2.2.0 the UI is working.

**Environment information**
- Rancher version : v2.2.0
- Installation option: Air Gapped single install

**Cluster information**
- Cluster type: Air Gapped Custom
- Machine type: Metal 96 Cores and 756GB

- Docker version (use `docker version`):

```
Client:
 Version:           17.03.2-ce
 API version:       1.27
 Go version:        go1.7.5
 Git commit:        f5ec1e2
 Built:             Tue Jun 27 03:35:14 2017
 OS/Arch:           linux/amd64

Server:
 Version:           17.03.2-ce
 API version:       1.27 (minium version 1.12)
 Go version:        go1.7.5
 Git commit:        f5ec1e2
 Built:             Tue Jun 27 03:35:14 2017
 OS/Arch:           linux/amd64
 Experimental:      False
```
[container.log](https://github.com/rancher/rancher/files/3013231/container.log)

**Comment by superseb** [comment]
Please provide exact steps/commands used, and can you also provide the history from this setup (what versions of Rancher are used)? Is there a proxy in play here?

This does not reproduce from scratch starting on v2.1.7 and upgrading to v2.2.0 in an airgapped environment.

**Comment by loganhz** [comment]
I guess you updated the ui-setting. You can change it to `local` via  API `/v3/settings/ui-index`

**Comment by loganhz** [comment]
It should be the same with https://github.com/rancher/rancher/issues/19327

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19327
