### ISSUE TITLE
Breaking change in Node Template after 2.2

### ISSUE THREAD

**Issue by Nightapes** [rancher/rancher#19219]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Same node template request via API v3 does not work after migration from 2.17 to 2.2

- Create Nodetemplate via API v3 in rancher 2.1.7
- Copy Request JSON
- Create Nodetemplate via API v3 with Rancher 2.2 with same JSON
**Result:**
```
{
    "baseType": "error",
    "code": "MissingRequired",
    "message": "Cloud Credential must be set",
    "status": 422,
    "type": "error"
}
```

**Other details that may be helpful:**

Our deployment scripts are failing now. Expecting API v3 to be stable or backwards compatibility

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.3.4

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
18.06
```

**Comment by alena1108** [comment]
@Nightapes thank you for reporting the issue. It will get fixed in our maintenance release. The backend already handles both old and new style template, we just have to relax the check on the API Validation side.

**Comment by sowmyav27** [comment]
verified on `rancher:master`(04/03/2019)
**Steps taken:**
1. create a node template(type - AWS) via API v3. Give in values for field amazonec2Config - 
```{ "accessKey": "xyz",
 "secretKey": "yyy"}```
2. Click on send request.
3. A node template will be created successfully.
4. Create a cluster with this node template.
5. Cluster will be created successfully.
