### ISSUE TITLE
Node selector for monitoring doesn't work in some case

### ISSUE THREAD

**Issue by kapolos** [rancher/rancher#19218]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

I upgraded from 2.1.7 to 2.2.0 and enabled monitoring on a cluster.

**Result:**

Monitoring API unavailable. 

This error is constantly spammed on the exporter-kube-state-cluster-monitoring logs:

`E0327 13:32:13.962468 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
`

**Other details that may be helpful:**

![image](https://user-images.githubusercontent.com/10794126/55080674-2dd1de80-50a7-11e9-96e9-ee9d96cda26b.png)

![image](https://user-images.githubusercontent.com/10794126/55080746-4f32ca80-50a7-11e9-81a6-e4656482e06d.png)

**Environment information**

Single install, v2.2.0. Cluster 1.13, Calico with isolation and some extra rules.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

Custom type, Metal, more than enough resources

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thxCode** [comment]
@kapolos , a similar issue: https://github.com/rancher/rancher/issues/18830

**Comment by loganhz** [comment]
Close in favor of rancher/rancher#18830

**Comment by loganhz** [comment]
Please try to disable and enable it again as a workaround to see

**Comment by kapolos** [comment]
@loganhz I removed the cattle-prometheus namespace and disabled monitoring. Then I enabled monitoring again. Same errors on `exporter-kube-state-cluster-monitoring`.

There is one difference though. Now `prometheus-cluster-monitoring` also throws an error: `level=error ts=2019-03-29T22:34:22.659461791Z caller=notifier.go:481 component=notifier alertmanager=http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts count=0 msg="Error sending alert" err="Post http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts: dial tcp: lookup alertmanager-operated.cattle-prometheus on 10.43.0.10:53: no such host"`

No idea if this one is related but I haven't done anything else to the cluster in the meantime.

**Comment by loganhz** [comment]
Errors on exporter-kube-state-cluster-monitoring will be fixed in #18830

@thxCode Please look at the other error

**Comment by loganhz** [comment]
@kapolos Do you mean now UI still shows `Monitoring API is not ready` ? The error message is not related.

**Comment by kapolos** [comment]
@loganhz Yes, `Monitoring API is not ready`. I just did in another time and still the same result.

![image](https://user-images.githubusercontent.com/10794126/55270547-b7043380-52a8-11e9-957c-fb19f360cb47.png)

![image](https://user-images.githubusercontent.com/10794126/55270552-c1263200-52a8-11e9-8e45-57ef8ad511bd.png)

![image](https://user-images.githubusercontent.com/10794126/55270560-d3a06b80-52a8-11e9-8a95-a4159c15928d.png)

Is there something possibly logged somewhere that might be useful to the investigation of the issue?

**Comment by thxCode** [comment]
@kapolos , It seems the cluster level Prometheus cannot be installed in your environment. We are using Operator to schedule the Prometheus deploying. You can feedback us with the log of Operator pod and do some checking with:
```
# Confirm Prometheus CRD installed or not
kubectl -n cattle-prometheus get prometheus
# Confirm Prometheus StatefulSet status
kubectl -n cattle-prometheus describe statefulset prometheus-cluster-monitoring
```

**Comment by kapolos** [comment]
@thxCode Thank you. Here are the results:

```
#kubectl -n cattle-prometheus get prometheus
NAME                 AGE
cluster-monitoring   43m
```

```
# kubectl -n cattle-prometheus describe statefulset prometheus-cluster-monitoring
Error from server (NotFound): statefulsets.apps "prometheus-cluster-monitoring" not found
```

**Comment by thxCode** [comment]
@kapolos , Can you paste the log of the `prometheus-operator-monitoring-operator` Pod?

**Comment by kapolos** [comment]
@thxCode Nice catch! There's a ton of errors like this:

`E0330 11:37:40.532953 1 reflector.go:134] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:404: Failed to list *v1.Prometheus: v1.PrometheusList.Items: []*v1.Prometheus: v1.Prometheus.Spec: v1.PrometheusSpec.NodeSelector: ReadString: expects " or n, but found t, error found in #10 byte of ...|e/horse":true},"paus|..., bigger context ...|r":{"beta.kubernetes.io/os":"linux","mine/horse":true},"paused":false,"podMetadata":{"labels":{"app"|...
`

Regarding the Node Selector:

![image](https://user-images.githubusercontent.com/10794126/55275607-39b0e100-52f1-11e9-9f0f-908bdb10216e.png)

When enabling the Monitoring, I copy pasted the label from here (and the UI auto-filled the key/value):

![image](https://user-images.githubusercontent.com/10794126/55275624-71b82400-52f1-11e9-953f-36b394ed30bd.png)

Disabling the monitoring, removing the namespace and enabling the monitoring without a nodeSelector made it work. Thank you.

The problem now is that while the metrics API becomes available, `prometheus-cluster-monitoring` dies shortly after:

`level=error ts=2019-03-30T11:54:40.56921677Z caller=notifier.go:481 component=notifier alertmanager=http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts count=0 msg="Error sending alert" err="Post http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts: dial tcp: lookup alertmanager-operated.cattle-prometheus on 10.43.0.10:53: no such host"`

Should I open a different issue for this?

**Comment by thxCode** [comment]
@kapolos , I think `NodeSelector` should accept any kinds of character except `;` as the label name, so it's still a bug.

> The problem now is that while the metrics API becomes available, prometheus-cluster-monitoring dies shortly after: ...
The last error log about accessing Alertmanager is fine, as you don't enable Rancher Alerting at first.

**Comment by kapolos** [comment]
@thxCode I increased the memory limit from 500MB to 2GB and now Prometheus doesn't die. It seems it really needed more (great work with the metrics integration in the UI btw!):

![image](https://user-images.githubusercontent.com/10794126/55276443-78986400-52fc-11e9-9cc6-7e44ab8da217.png)

**Comment by thxCode** [comment]
@kapolos , `NodeSelector` of `PrometheusSpec` types `map[string]string`, if we pass `mine/horse=true` pair into nodeSeelctor, we should translate the `true` to string like `mine/horse="true"`.  UI needs to explicitly pass in string, @loganhz .

**Comment by davidnuzik** [comment]
**Replication steps:**
v2.2.1
- Create DO cluster, 1 node (all roles) set node label mine/horse = true (UI sends `mine/horse: "true"`)
- Enable monitoring but create a node selector with mine/horse = true (UI sends `prometheus.nodeSelectors[0]: "mine/horse=true"`)
- Monitoring does not work (always says `Monitoring API is not ready`)
- Review prometheus-operator logs and get errors mentioned above like:
`E0403 17:10:03.988174 1 reflector.go:134] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:404: Failed to list *v1.Prometheus: v1.PrometheusList.Items: []*v1.Prometheus: v1.Prometheus.Spec: v1.PrometheusSpec.NodeSelector: ReadString: expects " or n, but found t, error found in #10 byte of ...|e/horse":true},"paus|..., bigger context ...|r":{"beta.kubernetes.io/os":"linux","mine/horse":true},"paused":false,"podMetadata":{"labels":{"app"|...`

**Validation steps:**
v2.2.2-rc1
- Create DO cluster, 1 node (all roles) set node label mine/horse = true (UI sends `mine/horse: "true"`)
- Enable monitoring but create a node selector with mine/horse = true (UI sends `prometheus.nodeSelectors[0]: "mine/horse="true""`) (notice the quotes around true string now)
- Monitoring DOES work now. Cluster and node metrics look normal.
- prometheus-operator logs look nominal

**Comment by davidnuzik** [comment]
Re-opening I accidentally closed the wrong issue. I meant to close #19324 
I will keep my above comments though in case this is useful later!

**Comment by davidnuzik** [comment]
Version: Master (4/4/19) ImageID: 10a1ef90fcbd
I carefully followed the steps outlined in my above comment again with the latest master to check in v2.3. I ensured HTTP looks the same and this still works correctly.
I had the same findings, this works now without any issues for me.
See https://github.com/rancher/rancher/issues/19218#issuecomment-479583258 for steps.
