### ISSUE TITLE
Unable to mirror system-charts

### ISSUE THREAD

**Issue by Kralor-Guldan** [rancher/rancher#19229]
**What kind of request is this (question/bug/enhancement/feature request):**
We have mirrored the system charts into our internal gitlab. When we point Rancher at the repo (www.abc.com/imports/system-repo.git) we get a 401 charts.yaml. It seems as if Rancher isn't checking out the repository, but expecting it to be a helm repository.

Some further details, the "kind" in the API is set to HELM not git.

**Comment by Kralor-Guldan** [comment]
This happens only in air-gapped environments. Public github works fine.

**Comment by superseb** [comment]
Does it need auth to clone that repository? Can you try configuring the username and password fields shown in https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/config-rancher-system-charts/?

**Comment by Kralor-Guldan** [comment]
We have it set to public, so no authorization is required.

**Comment by superseb** [comment]
Can you run `git ls-remote https://www.abc.com/imports/system-repo.git` inside the `rancher/rancher` container (assuming you entered `https://www.abc.com/imports/system-repo.git` in the `url` field)

**Comment by Kralor-Guldan** [comment]
We get a CAfile: /etc/ssl/certs/ca-certficate.crt CRLfile: none error

**Comment by Kralor-Guldan** [comment]
My fix (and this should be made globally) was to turn off ssl-verify in the rancher container.

**Comment by Kralor-Guldan** [comment]
This didn't fix everything. The latest error: Lstat management-state/catalog-cache/xxxxxxxx/charts/rancher-monitoring/v0.0.2 no such file or directory

**Comment by superseb** [comment]
You are running into https://github.com/rancher/rancher/issues/14766, the last error sounds that it does not have all the necessary resources. How did you mirror the repository?

**Comment by Kralor-Guldan** [comment]
We just cloned it and uploaded it.

**Comment by Kralor-Guldan** [comment]
I refreshed the chart in gitlab, now I get this error:

"Failed to install app monitoring-operator. Error: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1

**Comment by Kralor-Guldan** [comment]
Things started working for no reason after I set TLS Verify to false.

**Comment by superseb** [comment]
This was root caused to https://github.com/rancher/rancher/issues/14766, after applying the workaround to all rancher/rancher containers, things started working.
