### ISSUE TITLE
Add South Africa Azure Regions to Rancher UI

### ISSUE THREAD

**Issue by MarcelMichau** [rancher/rancher#19227]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
N/A

**Result:**
N/A

**Other details that may be helpful:**

Microsoft recently launched two new Azure regions in South Africa.  This is just a request to add them to the region dropdown on the UI.

Output from `az account list-locations`
```
  {
    "displayName": "South Africa North",
    "id": "/subscriptions/xxx/locations/southafricanorth",
    "latitude": "-25.731340",
    "longitude": "28.218370",
    "name": "southafricanorth",
    "subscriptionId": null
  },
  {
    "displayName": "South Africa West",
    "id": "/subscriptions/xxx/locations/southafricawest",
    "latitude": "-34.075691",
    "longitude": "18.843266",
    "name": "southafricawest",
    "subscriptionId": null
  }
```
I'm happy to do a PR if it's just as simple as editing the https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/azure-choices.js file.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.0
- Installation option (single install/HA):
single install

**Comment by loganhz** [comment]
Yes, please!

**Comment by MarcelMichau** [comment]
Cool! PR is here: https://github.com/rancher/ui/pull/2820

**Comment by davidnuzik** [comment]
Version: Master (4/11/19) ImageID: 0d755e769e77

Confirmed that the "South Africa North" and "South Africa West" regions were added to azure.

When you try to create a node template these choices are now listed and are working as expected.
![image](https://user-images.githubusercontent.com/45179589/55986773-f3467500-5c54-11e9-8d5b-ed2e22b7e71f.png)

HTTP/API looks correct (location name matches what is seen in az cli).

QA does not have the ability to provision VMs in this region but the HTTP looks good for both regions.
