### ISSUE TITLE
Can't deploy images stored in a private registry via helm

### ISSUE THREAD

**Issue by guglez** [rancher/rancher#19226]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1 Add a private registry with credentials available for the whole project
2 Validate that registry is usable by deploying an image from the registry
3 Try to deploy the same image via helm

**Result:**
Unable to pull image:
ImagePullBackOff: Back-off pulling image

**Other details that may be helpful:**
If I deploy a workload - it works. If I deploy the same image from the same registry - it can't pull my image.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher | v2.1.7
User Interface | v2.1.21
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
RKE self hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM 24Gb of RAM 4 CPU
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by loganhz** [comment]
You need to add `imagePullSecrets` by yourself if you are using helm https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

**Comment by deniseschannon** [comment]
@guglez if you still have any questions, please re-open or make a comment and ping me.
