### ISSUE TITLE
Allow execute command in existing container in cron jobs

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#19221]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement / feature request

**Steps to reproduce (least amount of steps as possible):**

When creating a CRON job, we can use a docker image then a command.

But we sick to execute a command in existing pod.

Context: we have a gitlab installation on our kubernetes cluster and we try to run the following:

`docker exec -t <gitlab-pod-name> gitlab-rake gitlab:backup:create`

Could we have any way to achieve that?

Is it possible to trigger similar behavior than docker exec through kube-ctl CLI? We could then use dockerized rancher CLI to trigger that within cron jobs.

**Environment information**
- Rancher version: 2.2.0
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom and GKE
- Kubernetes version (use `kubectl version`): 1.13.4

**Comment by loganhz** [comment]
@blackholegalaxy can you try the following, please?

1. Click show advanced options in add workload page
2. Click `Command` section to open it.
3. Input the command field

![image](https://user-images.githubusercontent.com/21168270/55095396-086ac200-50f3-11e9-8b9a-cc33c6589f39.png)

**Comment by blackholegalaxy** [comment]
My point is not executing a command on a new container but on existing running pod

**Comment by blackholegalaxy** [comment]
@loganhz found a way to achieve my goal but I'm currently blocked by #19234

**Comment by jeremyherbert** [comment]
Was there ever a resolution to this? I’m trying to reload my nginx config once a day in case there are updated ssl certificates, and to do that I need to run a command in my nginx container.

**Comment by kutyla-philipp** [comment]
I have actually the same usecase as @blackholegalaxy.
I want to run backups of my gitlab on a regular basis.
How did you go about solving this issue?
