### ISSUE TITLE
OTC node driver fails to be activated

### ISSUE THREAD

**Issue by hvpareja** [rancher/rancher#19223]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
In a fresh rancher installation activate the Open Telecom Cloud node driver

**Result:**
Results in a hanging status of "Activating" in the UI and throws the following error in the logs:

```
[ERROR] NodeDriverController otc [node-driver-controller] failed with : hash does not match, got 3f793ebb0ebd9477b9166ec542f77e25, expected b4c05f6598dcfac7a8f10899aaac3d42
```

**Other details that may be helpful:**
Note there has been recent releases of the driver: https://github.com/Huawei/DockerMachineDriver4OTC

Also see the hashes here: https://dockermachinedriver.obs.eu-de.otc.t-systems.com/

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): I have reproduced the error in both v2.2.0 and v2.1.8
- Installation option (single install/HA): single node

**Comment by hvpareja** [comment]
Hi @loganhz - Can I ask what's the criteria to place an issue in one milestone or another? It is mere curiosity.

Thanks

**Comment by loganhz** [comment]
@hvpareja as a workaround, you can edit the node driver and update the hash to `3f793ebb0ebd9477b9166ec542f77e25`.

Usually, We will fix an issue in the master branch (now master is for 2.3) and create an issue to backport it if it is important.

**Comment by loganhz** [comment]
Maybe the right thing is uploading the binary to another place... instead of using `https://dockermachinedriver.obs.eu-de.otc.t-systems.com/docker-machine-driver-otc`

**Comment by hvpareja** [comment]
@loganhz, I suggested them to provide a fixed URL for each of their releases

**Comment by loganhz** [comment]
@hvpareja Thanks for your help!

**Comment by deniseschannon** [comment]
We need to either update the URL or checksum:

https://github.com/rancher/rancher/blob/master/app/machinedriver_data.go#L65

**Comment by alena1108** [comment]
We should consider opting out of the checksum verification. Otherwise it would be hard to maintain the checksum as we don't control the machine driver binary and can't ensure it won't change.

**Comment by vincent99** [comment]
That's like the opposite of what we should be considering?  Every driver we include in the default config (enabled or not) should have a fixed URL for a non-floating version and a matching checksum for it.

**Comment by loganhz** [comment]
Maybe we should upload the binary somewhere instead of using their kind of `latest` binary. @alena1108 Can I use my own github repo ?

**Comment by deniseschannon** [comment]
I don't think using a personal one makes sense, but we could put it into the rancher-plugins org? 
https://github.com/rancher-plugins

**Comment by deniseschannon** [comment]
@loganhz at a minimum, we should update the hash to match for the latest release. 

Can you open a new ticket on how to handle OTC releases if they keep updating it without versioned numbers?

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/13/19)

I validated the updated binary URL (https://github.com/rancher-plugins/docker-machine-driver-otc/releases/download/v2019.5.7/docker-machine-driver-otc) and that the hash was correctly updated (3f793ebb0ebd9477b9166ec542f77e25).

The driver now activates without any issues in the UI or rancher logs. I can access the OTC cluster config without any issues.
