### ISSUE TITLE
Allow S3 Snapshot service to trust internally signed certs when talking to the S3 endpoint

### ISSUE THREAD

**Issue by jrmercier1** [rancher/rancher#19222]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature request

Allow S3 Snapshot service to utilize internally signed certs when talking to the S3 endpoint.

We utilize internal S3 compatible services and would like to make use of the S3 Snapshot feature provided in 2.2.0.  We receive a trust type warning from the snapshot endpoint since our internal S3 endpoint utilizes an internally signed cert(private CA).

**Steps to reproduce (least amount of steps as possible):**

1. Edit Cluster -> Configure Internal S3 compatible endpoint that uses an internally signed cert (private CA).
2. Select cluster in UI -> Snapshot Now

**Result:**
Error in API view.

message": "Failed to take one-time snapshot, exit code [1]: time=\"2019-03-27T13:38:51Z\" level=fatal msg=\"faield to set s3 server: failed to check s3 bucket:mybucket, err:Head https://s3server:9021/mybucket/: x509: certificate signed by unknown authority\" \n",

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.2.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Kubernetes version (use `kubectl version`): 1.13.4

**Comment by straffalli** [comment]
+1
We encountered the same problem, it could be nice to have the possibility to setup our internal CA when configuring the S3 endpoint for snapshots.

**Comment by alena1108** [comment]
API/Backend support is in master. Separate ticket is filed for UI.

**Comment by sowmyav27** [comment]
Verified in rancher:master-head -- API testing

- Launch a minio server with Self-signed Keys and Certificates.
- Created a cluster, by configuring the minio server as S3 snapshot details without passing the  certs in`customCa`. Error was seen on the rancher logs:

```
2019/06/27 22:17:24 [WARNING] Failed to take one-time snapshot, exit code [1]: time="2019-06-27T22:17:23Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:sowmya-test, err:Get https://x.x.x.x:9000/sowmya-test/?location=: x509: certificate signed by unknown authority" 
```

- Now create a cluster passing the valid certs in`customCa`field.
- Snapshot is taken successfully. Restore from snapshot works.
