### ISSUE TITLE
Telemetry: Add new metrics for new v2.2.0 key features

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19231]
Version: v2.2.0

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Enhancement Details:**
We should add new metrics to telemetry for new v2.2 features. For example, we currently have no way of knowing how many people are utilizing Multi-Cluster Apps and Monitoring.

**Items**

- [x]  "#" of Cluster Templates, enforcement on/off - Ricky
- [x] "#" of HPA - Caleb
- [x] ~"#" of Cloud Credentials - Ricky~
- [x] ~"#" of Node Templates~
- [x] Istio enabled - Ricky
- [x] Monitoring enabled - Ricky
- [x] Logging enabled/provider- Ricky
- [x] # Pipeline enabled - Ricky
- [x] Pipeline feature enabled - Ricky
- [x] # Pipeline per provider enable - Ricky
- [x] Double check new auth providers are reporting (google) - Caleb
- [x] library apps counter - Ricky/Caleb
- [x] Info about CloudProvider enabled in RKE config, see Alena's comment - Caleb

-- EDIT (Ricky)

How to test:

1. go to settings and set "telemetry-opt" to "on"
2. go to **rancher_url**/v1-telemetry
3. perform action for stat being tested and refresh v1-telemetry. Confirm data has been incremented, changed, toggled, etc. (which ever is appropriate for particular metric)

Items specific testing notes:
* '#' of Cluster Templates and enforcement
    * Create new cluster template and check metric. In setting toggle "cluster-template-enforcement" and check metric.
* '#' of HPA
    * With an app already live, go to resources -> hpa -> add hpa and create one targeting your workload. In telemetry it will show up under `project/hpa`.
* '#' of Cluster Credentials
    * Create a few new cluster credentials and confirm that metrics matches number of cloud credentials.
* Istio, monitoring, logging
    * Enable each and confirm it is reflected in metrics
* '#' of Pipeline enabled
    * Enable example pipelines and confirm that count is reflected in metric.
* Pipeline feature enabled:
    * Setup any pipeline provider and check that metric shows pipeline feature is enabled.
* '#' of pipeline per provider
    * Create pipelines in diff projects with diff provider and confirm counts are reflected.
* Double check new auth providers are reporting
    * Setup an auth provider, if possible use google as that is newest. Add some users from it. Now in telemetry under `install/users` you will see both local and google specific users and groups. 
* Library apps counter 
    * Add a few applications in various clusters, now in telemetry under `project/charts` you should see them listed. 
* Info about CloudProvider enabled in RKE config, see Alena's comment
    * Create a cluster with RKE (like ec2) and now in telemetry under `cluster/cloudProvider` you should see 'aws'.

**Comment by cjellick** [comment]
Firstly, we need to enumerate all the new features that need added.
@cloudnautique maybe you can tell us what you want?

I think I heard @tfiduccia and @vincent99 talking about this. Do yall have specifics? Not just features, but the aspects of those features you want tracked.

Going to be honest, with v2.3.0 date looming, this is on the chopping block for me, but I think it should be a fast follow up in v2.3.1. or 2. Will leave it in for now in case we do have bandwidth for it.

@rmweir this should be prioritized below any bugs.

**Comment by loganhz** [comment]
catalogs deploy in Library charts ?

**Comment by rmweir** [comment]
testing notes in description

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/9/19)

Upon opting into telemetry and then hitting the v1-telemetry endpoint I get an HTTP 502.
Rancher server debug logs show:

```
2019/09/10 01:22:50 http: proxy error: dial tcp 127.0.0.1:8114: connect: connection refused
2019/09/10 01:24:47 [DEBUG] Requesting user: user-v8f26, Requesting groups: [system:authenticated] Impersonate user:  Impersonate group: []
2019/09/10 01:24:47 [DEBUG] Triggering auth refresh on user-v8f26
2019/09/10 01:24:47 [DEBUG] Skipping refresh for user-v8f26 due to max-age
2019/09/10 01:24:47 http: proxy error: dial tcp 127.0.0.1:8114: connect: connection refused
2019/09/10 01:24:47 [DEBUG] 2019/09/10 01:24:47 http: TLS handshake error from REDACTED_IP:33026: remote error: tls: unknown certificate
2019/09/10 01:24:47 [DEBUG] 2019/09/10 01:24:47 http: TLS handshake error from REDACTED_IP:47049: remote error: tls: unknown certificate
```

**Comment by cbron** [comment]
Can confirm the new release binary isn't working. Also not all commits made it into the release. Looking into it.

**Comment by cbron** [comment]
@davidnuzik new working telemetry binary in rancher master branch now

**Comment by davidnuzik** [comment]
Testing note: test with rc3

**Comment by davidnuzik** [comment]
All areas have been validated now. Please reference my comment above with the checkboxes: https://github.com/rancher/rancher/issues/19231#issuecomment-530592365
