### ISSUE TITLE
UI - No error message presented to the user when app deployment fails.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#19236]
Rancher server version - v2.2.0

Steps to reproduce the problem:
As admin , Create a cluster `c1` and add user `test1` as "cluster member".
Deploy any app , say redis.
Log in as  `test1` . Create a new project.
Deploy the same  app , redis.
User is brought back to the same page and no error message is presented.

In this case , namespace creation actually failed with following error message - 
```{"baseType":"error","code":"AlreadyExists","message":"namespaces \"artifactory-ha\" already exists","status":409,"type":"error"}```

This issue is also seen in this issue - https://github.com/rancher/rancher/issues/19168

**Comment by davidnuzik** [comment]
Note: Validated in v2.2.2.-rc1 in issue #19336 (will need to be checked again in v2.3)

**Comment by davidnuzik** [comment]
Version: Master (4/4/19) ImageID: 10a1ef90fcbd

I had the same findings as in #19336 with v2.2.2-rc1. I just tested with latest master this time to validate in v2.3.

- As admin, Create a cluster c1 and add user test1 as "cluster member".
- Deploy any app , say redis.
- Log in as test1 . Create a new project.
- Deploy the same app , redis.
- The user now gets an error message in the UI explaining the issue:
![image](https://user-images.githubusercontent.com/45179589/55573523-0b4f4f00-56bf-11e9-800f-9ad08f9db7b7.png)
