### ISSUE TITLE
containers on windows host 1803 not conect to external lan

### ISSUE THREAD

**Issue by fedeostrit** [rancher/rancher#19230]
I bother you with one more problem that I have in my cluster with 2 nodes with centos 7 and a node with windows 1803, the 3 hosts are in the same network 10.73.2.0/24 and there are also other VMs that are in that same network that has other services such as Oracle DB instances

The problem I have is that when I raise a caontainer in the Windows node, the container can not see the network 10.73.2.0/24, only see the 3 hosts that are in the cluster, if I raise a container in the Centos nodes if they can see the network 10.73.2.0/24 and you can also see other networks of my infrastructure

this is the CNI.config of the windows node:

{"capabilities":{"dns":true},"delegate":{"dns":{"search":["svc.cluster.local"],"nameservers":["10.43.0.10"]},"policies":[{"value":{"ExceptionList":["10.42.0.0/16","10.43.0.0/16","10.73.2.0/24"],"Type":"OutBoundNAT"},"name":"EndpointPolicy"},{"value":{"DestinationPrefix":"10.43.0.0/16","NeedEncap":true,"Type":"ROUTE"},"name":"EndpointPolicy"},{"value":{"DestinationPrefix":"10.73.2.224/32","NeedEncap":true,"Type":"ROUTE"},"name":"EndpointPolicy"}],"type":"win-bridge"},"name":"cbr0","type":"flannel","cniVersion":"0.2.0"}

the containers in the hosts with centos can see all the networks, I think it has to be something in that config but I can not change it because if I do it and restart the host it goes back to the configuration previous to the change
for example I need a container to access a db oracle with the following ip 10.73.2.79

**Comment by fedeostrit** [comment]
fixed, the cni.conf file has misplaced exclusions, add the exception for the entire network 10.73.2.0/24 where are the hosts and other services so the containers can not route to those networks, this is the rule that adds:

{"value": {"ExceptionList": ["10.42.0.0/16","10.43.0.0/16","10.73.2.0/24"],"Type":"OutBoundNAT"},"name": " EndpointPolicy "}

and in reality only the host of the cluster should be, change it by:

{"value": {"ExceptionList": ["10.42.0.0/16","10.43.0.0/16","10.73.2.47/32","10.73.2.232/32","10.73.2.224/32" ], "Type": "OutBoundNAT"}, "name": "EndpointPolicy"}

also add to the end of all this policy that I do not know if it is over but at least now everything works:

{"value": {"DestinationPrefix": "10.73.2.0/24" ""NeedEncap":true,"Type":"ROUTE"},"name":"EndpointPolicy"}

what if I restart the windows host the CNI.config is recreated so I have to enter, modify and redeploy the containers to take the new file.
another solution would be to add all the hosts in a different network to all the other services, for example service network 10.73.2.0/24 and host network 10.73.3.0/24

**Comment by wdeignan** [comment]
Did you have to restart one of the agents on the host layer after modifying cni.conf to make this work? I have the same problem but my modifications to that file don't seem to have any effect. I even tried trashing it and inter-pod networking keeps running.

**Comment by fedeostrit** [comment]
no, I only delete the Pod that is running so that it recreates and uses the new CNI file, the host where you modify the CNI.conf does not have to be restarted or restart the services because if this is done then the CNI recreates

**Comment by wdeignan** [comment]
I found my problem. I didn't realize that Flannel on Windows can't support translating ICMP (like pings) to external networks. Curl works as an alternative connectivity test. Of course now I discovered a secondary issue - my Windows hosts (and containers) can't reach anything in the "services" network of the Kubernetes cluster like kube-dns. Did you see that too?

**Comment by wdeignan** [comment]
And again I really need to read the Kubernetes.io documentation better before posting. Node -> service connectivity isn't supported yet. Pod -> service connectivity works fine. This isn't a Rancher limitation.

**Comment by deniseschannon** [comment]
@fedeostrit @wdeignan It sounds like both of you have figured out your issues with windows. We are introducing windows 1809 in v2.3 so look forward to announcements to test out the new windows!
