### ISSUE TITLE
Rancher 2.2.0: Setting CPU + Memory Limits actually requests them

### ISSUE THREAD

**Issue by ruffy91** [rancher/rancher#19241]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```
(paste the output here)
```

- Docker version (use `docker version`):
18.09

```
(paste the output here)
```
When limiting Memory + CPU for workloads the requested resources actually increase.
For example I have 3 pods with a CPU limit of 1 CPU each, this causes the reserved CPUs of the cluster to increase by 3 CPU.

Also this causes scheduling issues when trying to limit Pods.
If i want to run 10 Pods with 100mCPU Reservation and 1 CPU Limit to run on a 4 core node only 3 pods get scheduled, because 10 CPU get requested.

**Comment by vincent99** [comment]
The UI puts in whatever you said..  "Hosted" doesn't tell us much, but your provider may have an admission controller enabled that enforces a minimum reservation, that reservation is equal to limit, or similar.

![image](https://user-images.githubusercontent.com/753917/55186658-5368f180-5154-11e9-975a-36dd60677db7.png)

**Comment by ruffy91** [comment]
I use Ubuntu 18.04.2 on multiple Hetzner CX21 nodes (2vCPU, 4GB RAM, 40GB SSD) deployed via rancher with https://github.com/mxschmitt/ui-driver-hetzner and docker 18.09.
Rancher itself is running on CentOS 7 in single node config.
Separate node pools for etcd/control plane and workers.

When I look and - limits: and - requested: of the cluster (three dots -> view in API) I get following result:
If I add 1G memory reservation the requested value increases by 1G. If i add a 1G memory limit both limits and requested increases by 1G.

**Comment by daxmc99** [comment]
Hi @ruffy91 this is intended behavior per the k8s docs https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#what-if-you-specify-a-container-s-limit-but-not-its-request

So for your example, you would not be able to schedule 10 pods with a CPU limit of 1 vCPU each since that would exceed the capacity of your cluster.

**Comment by deniseschannon** [comment]
@ruffy91 if you have more questions, please let me know.

**Comment by ainiml** [comment]
> Hi @ruffy91 this is intended behavior per the k8s docs https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#what-if-you-specify-a-container-s-limit-but-not-its-request
> 
> So for your example, you would not be able to schedule 10 pods with a CPU limit of 1 vCPU each since that would exceed the capacity of your cluster.

So `Limit` means the max allowed, and `Request` is just a suggested amount the container can use?
