### ISSUE TITLE
Improve Dashboard Usability

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#19249]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Go to dashboard

**Result:**
![image](https://user-images.githubusercontent.com/468462/55176311-26114900-513e-11e9-8fb7-e797d6c63d78.png)

**Other details that may be helpful:**
Users have made remarks that they do not understand what the various lines and colors mean on the dashboard and have requested additional documentation. Might be good to enhance or overhaul the dashboard to make it completely intuitive.

**Comment by loganhz** [comment]
We are going to remove the outline and dots

**Comment by westlywright** [comment]
Available in master and ui-tag `2.2.31`

**Comment by davidnuzik** [comment]
@westlywright https://releases.rancher.com/ui/2.2.31/index.html doesn't seem to exist?

**Comment by davidnuzik** [comment]
(Waiting for RC to test with)

**Comment by davidnuzik** [comment]
Note, tested in #19308 against v2.2.2-rc1 but we might want to test again before v2.3 release?

**Comment by davidnuzik** [comment]
Version: Master (4/4/19) ImageID: 10a1ef90fcbd
This was checked again in latest master to validate for v2.3. I had the same findings as in #19308 against v2.2.2-rc1:

- Have a cluster with at least 2 scheduleable nodes.
- Enable monitoring. Notice the outlines and dots are NOW REMOVED.
- Hover around the areas where tooltips used to be expected when we had the outlines and dots (node min/max) ensured these tooltips are gone as well (nothing left behind that is unexpected).
