### ISSUE TITLE
Ingress name validation is failing

### ISSUE THREAD

**Issue by matfiz** [rancher/rancher#19268]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. On a fresh Rancher 2.2.1 installation, rollout a helm chart (eg. rabbitmq in my case)
2. Try to add ingress with name `my-name`
**Result:**
Error:
```
Validation failed in API: Ingress.extensions "rabbit-mq" is invalid: spec.rules[0].http.backend.serviceName: Invalid value: "rabbitmq:rabbitmq-staging": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.1
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`):

```
1.13.5
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by tfiduccia** [comment]
@matfiz - I am unable to reproduce this behavior, can you tell me:
1.  What is the name of the namespace of your helm chart
2.  According to the error, it looks like the ingress service you are creating is name rabbitmq, are you sure it's my-name?
3.  Are you attaching it to the rabbitmq workload or service?
4.  What type of custom cluster?  Who is the provider, type of vms?

I will continue to try and reproduce, but if you can give me a bit more information, maybe we can track this down.

**Comment by aldrinmagno** [comment]
Hello,

I'm experiencing the same issue with my Rancher v2.2.4 when adding to a new ingress.

I'm not sure what I'm doing wrong, I already remove the project and tried again with no success.

`Validation failed in API: Ingress.extensions "my-name" is invalid: spec.rules[0].http.backend.serviceName: Invalid value: "smsup:jsg": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')` This is the error message Im getting

**Comment by aldrinmagno** [comment]
Progress, it worked when I only have 1 port.
