### ISSUE TITLE
Stayed in the pull image all the time, but this image already exists on the node.

### ISSUE THREAD

**Issue by vincent927** [rancher/rancher#19263]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** Launch elasticsearch in the catalog

**Result:**  
Stayed in the pull image all the time

![image](https://user-images.githubusercontent.com/10399425/55218614-8f2bb600-523d-11e9-8ccb-16c134833159.png)

image already exists on the node

![image](https://user-images.githubusercontent.com/10399425/55218624-981c8780-523d-11e9-9442-534caf51584e.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.0
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by jiaqiluo** [comment]
Hi @vincent927  I cannot reproduce the issue on my setup. Does the issue happen all the time? Does it happen if you launch apps using other catalogs?

**Comment by vincent927** [comment]
I seem to find the reason, because this image pull strategy is “always” TKS a lot @jiaqiluo
