### ISSUE TITLE
Edit as yaml is not working

### ISSUE THREAD

**Issue by materemias** [rancher/rancher#19267]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
create a new app or open an existing one. do some configuration. click on `Edit as yaml`

**Result:**
 it should be reflecting the config but it is empty

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.2.1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): gke
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.7", GitCommit:"aeaa96020ec0614a8773799058c3b8d58c19b9ff", GitTreeState:"clean", BuildDate:"2019-03-13T11:22:57Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by jiaqiluo** [comment]
Hi @materemias I cannot reproduce the isseue on my setup. Here is what I did
- run Rancher v2.1.1 single install
- add a GKE cluster with all default configurations
- go to the `default` project -> `Apps` -> `launch` to launch Redis from the built-in catalog
- choose `edit as YAML` to set `slaveCount` to 4
- click `launch` and to wait the app be active
Result:
- the app is active and has 4 slaves 

Kubernetes version 
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.7", GitCommit:"aeaa96020ec0614a8773799058c3b8d58c19b9ff", GitTreeState:"clean", BuildDate:"2019-03-13T11:22:57Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

<img width="1399" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55250145-cc2a8500-520a-11e9-8557-0cda717de88b.png">

Also, I am not sure if you meet this but it is a known issue that the values in `edit as a form` and `edit as YAML` are not synced:  https://github.com/rancher/rancher/issues/19060

**Comment by materemias** [comment]
I have only tested with apps installed on v2.1.x as the related issue suggests there was free patching between answers and yaml. Now that these apps are on v2.2.1 the default view is answers and when I try to switch to yaml I got an empty text area. This happens with all catalog apps I have installed.
Some sort of initial yaml conversion would be highly welcome since that's the preferred way how I want to edit configurations. This is also required when I want to force recreate an app. Copy-pasting full yaml made it easy that option is gone with this issue.

**Comment by alena1108** [comment]
@jiaqiluo can you test the case when the apps were created on 2.1.7? Then upgrade to 2.2.1 and try to update them via yaml

**Comment by proligde** [comment]
@alena1108 I was able to reproduce this behaviour when editing a cluster yaml. Here is how:

I switched from the default local etcd backup to the s3 based backup and entered the corresponding access keys.

After that I was not able to change these setting in the yaml file. Clicking on "save" just didn't save anything. Changes to the form also seem to have no effect. 

I can however disable S3-Backup again and switch back to local within the form. This change will be saved successfully.

After trying this several times, now my secret key  I put into the form isn't reflected in the yaml at all. I'm not sure that's related, though.

**Comment by loganhz** [comment]
The original issue is same with https://github.com/rancher/rancher/issues/19060

https://github.com/rancher/rancher/issues/19267#issuecomment-478170524 is another issue

@proligde Could you please file a new issue?

**Comment by alena1108** [comment]
@proligde 

> I switched from the default local etcd backup to the s3 based backup and entered the corresponding access keys. Clicking on "save" just didn't save anything. Changes to the form also seem to have no effect.
> After trying this several times, now my secret key I put into the form isn't reflected in the yaml at all. I'm not sure that's related, though.

When you switch from local to s3 in yaml, do you see both s3 accessKey and secretKey missing? If access key is present, and only secret key is missing, then it's because we hide sensitive data in the API. Both accessKey/secretKey gets stored in the DB, but only accessKey gets displayed in the API.

**Comment by proligde** [comment]
@alena1108 I'm afraid both happens, actually :-D sometimes "secret_key" is shown, having the wrong content which seems to be caused by my chrome autopassword fill (and then I can't change it in the yaml view - it just stays the same). And sometimes it's not there at all. I'm trying to create a reproducable scenario here and after that I'll file another issue like @loganhz suggested as that would be something else than. Thanks a lot, guys!

**Comment by proligde** [comment]
@materemias I'm dealing with that problem since yesterday and by now I have a slight feeling it might be because of my LastPass plugin interfering. Do you use LastPass as well? If so - try deactivating it, and tell me if that helps.

**Comment by materemias** [comment]
@proligde I do use LastPass as well but these seem not to be correlated. I have tried in a guest window and in different browsers and I can reproduce the issue.

**Comment by proligde** [comment]
@materemias you're right. Sorry for pointing you in the wrong direction. I recreated the template without Lastpass activated and the first upgrade after that worked so I assumed this was correlated because I had in fact a problem with lastpass passing a password to a field I've manually entered another string in but yeah - it's not correlated.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19060

Let's move the talk to https://github.com/rancher/rancher/issues/19060
