### ISSUE TITLE
windows host kubernate v1.11.9

### ISSUE THREAD

**Issue by fedeostrit** [rancher/rancher#19269]
windows host not register in rancher cluster v2.2.1 whit kubernates v1.11.9, logs:

Downloaded newer image for rancher/hyperkube:v1.11.9-nanoserver-1803"}

ERRO[1435234] Failed to connect to proxy: Error: No such image: sha256:37fc58226c039f4d6f87ed356cfb5934d578ec795204a0314ce04d4ca2c176f8

the image rancher/hyperkube:v1.11.9-nanoserver-1803 not exist

**Comment by alena1108** [comment]
Per Drone Windows build, following images were pushed:

```
PUSHING hyperkube:v1.11.9-nanoserver-1803 to rancher ..
PUSHING hyperkube:v1.12.7-nanoserver-1803 to rancher ...
PUSHING hyperkube:v1.13.5-nanoserver-1803 to rancher ...
```

@loganhz  can you give 2.2.1 windows a quick test.

**Comment by thxCode** [comment]
@alena1108 , executing `docker pull rancher/hyperkube:v1.11.9-nanoserver-1803` on 1803 host, result as below:
![image](https://user-images.githubusercontent.com/3394724/55372973-3490a380-5536-11e9-855a-9e4cc69c8be2.png)

@fedeostrit , Can you try `docker pull rancher/hyperkube:v1.11.9-nanoserver-1803` on your Windows host? BTW, are you using Windows core 1803 or Windows 2016? You can feedback us some OS info by `Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\'`, like:
![image](https://user-images.githubusercontent.com/3394724/55373092-a537c000-5536-11e9-98e8-e7b799e65466.png)

**Comment by fedeostrit** [comment]
hello, I commented that I could update the hyperkube on my host with Windows 1803, I share the info from the rancher console where it shows this and also the info of the OS of the host of windows:

![image](https://user-images.githubusercontent.com/48490228/55486595-f4e3bd80-5602-11e9-8a0e-f52f7a426682.png)
![image](https://user-images.githubusercontent.com/48490228/55486697-28264c80-5603-11e9-8618-bb543303fe30.png)



On the other hand still not solved is the issue of updating to the version of Kubernetes v1.13.x since it pulls error:

server.go: 147] unknown flag: --cadvisor-port

I know that there are cases opened by this but I wanted to know if there is any estimated date of solution for this and for the support of Windows server 1809, I need some estimated date if possible

**Comment by deniseschannon** [comment]
@fedeostrit We are planning to add in windows support in 2.3 which is targeted for September release.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19173 https://github.com/rancher/rancher/issues/16460
