### ISSUE TITLE
error in cluster Provisioning 

### ISSUE THREAD

**Issue by mohapma** [rancher/rancher#19262]
**I am using below version of kubectl**
_Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}_

**I am getting below error during cluster provisioning** 
_This cluster is currently Provisioning.Exit status 1, namespace "cattle-system" configured clusterrolebinding.rbac.authorization.k8s.io "cattle-admin-binding" configured clusterrole.rbac.authorization.k8s.io "cattle-admin" configured Error from server (Forbidden): error when creating "management-statefile_path_redacted": serviceaccounts "cattle" is forbidden: unable to create new content in namespace cattle-system because it is being terminated Error from server (Forbidden): error when creating "management-statefile_path_redacted": secrets "cattle-credentials-159a243" is forbidden: unable to create new content in namespace cattle-system because it is being terminated Error from server (Forbidden): error when creating "management-statefile_path_redacted": deployments.extensions "cattle-cluster-agent" is forbidden: unable to create new content in namespace cattle-system because it is being terminated Error from server (Forbidden): error when creating "management-statefile_path_redacted": daemonsets.extensions "cattle-node-agent" is forbidden: unable to create new content in namespace cattle-system because it is being terminated_

**Comment by kinarashah** [comment]
@mohapma I am unable to reproduce this, is this single node or HA setup? What kind of cluster was this?

**Comment by mohapma** [comment]
I have installed 2 node, both are master, etcd, worker.

**Comment by deniseschannon** [comment]
@mohapma I need some more details than the error. 

Can you fill out the template that populates when you try to create a new issue?

**Comment by superseb** [comment]
Let me know if you need help on this
