### ISSUE TITLE
2.2 - Prometheus error when installing Monitoring

### ISSUE THREAD

**Issue by nloui** [rancher/rancher#19278]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Upgraded Rancher
- Enabled monitoring from GUI

**Result:**
- New namespace is created (with services: exporter-kube-state-cluster-monitoring, exporter-node-cluster-monitoring and grafana-cluster-monitoring). All are ready.
- Logs show: "failed to detect the installation status of monitoring components: Prometheus StatefulSet isn't deployed" as well as "ClusterAlertRuleController XXXXX/migrate-clusteralert-node-mem [cluster-alert-rule-deployer] failed with : failed to get Alertmanager Deployment information, statefulsets.apps "alertmanager-cluster-alerting" not found, [cluster-alert-rule-controller] failed with : Failed to get service for alertmanager, service "cattle-prometheus/alertmanager-operated" not found"

- GUI shows: Monitoring API is not Running

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.1

- Installation option (single install/HA):
- Single node installation
- Cluster on EC2

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Infrastructure / EC2

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
M5.2xl - 30.5gb ram, 8 cores

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}

```
(paste the output here)
```

- Docker version (use `docker version`):
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

```
(paste the output here)
```

**Comment by materemias** [comment]
#19209 possibly related

**Comment by thxCode** [comment]
https://github.com/rancher/rancher/pull/19259 will provide a new way to update the Monitoring enabling status.

**Comment by thxCode** [comment]
@cjellick , @nloui , in fact, I cannot reproduce this, but I think this may cause by the Monitoring detection loop logic on Cluster CRD. In practice, UI just wants to know Prometheus is ready or not and it can be known in real time. So we separate the Prometheus detection logic into another loop by https://github.com/rancher/rancher/pull/19259.

**Comment by jiaqiluo** [comment]
The bug fix is validated with Rancher:master 4fd2548 following the suggested steps outlined by @thxCode at https://github.com/rancher/rancher/issues/19326#issuecomment-479814459

- Enable Cluster Monitoring -> the monitoring dashboards should be on
- Disable Cluster Monitoring -> the monitoring dashboards should be off
- Enable Cluster Monitoring and then drop cattle-prometheus/prometheus-cluster-monitoring Pod -> the monitoring dashboards should be off until Prometheus Pod redeploy

But there is one new dashboard issue that the wheels will not switch to the new design (double rings) until refreshing the page manually. 

The issue is similar to the one mentioned in this comment https://github.com/rancher/rancher/issues/19326#issuecomment-480026318 and got fixed here in v.2.2 https://github.com/rancher/ui/pull/2862  

@loganhz @thxCode Could you confirm if the patch was applied to the master branch?

**Comment by loganhz** [comment]
@jiaqiluo , yes, it's in master. I can not reproduce it. Now UI will send request to backend until we have enough data to show the gauge. You can open network tab in Chrome and check if the `cluster-memory-usage` and `cluster-cpu-usage` graph in the API response. I guess if you wait a bit longer, you will see it.

**Comment by jiaqiluo** [comment]
@loganhz 
The issue happens only after deleting the pod `prometheus-cluster-monitoring` manually. 

I tracked the network tab in Chrome, and it shows that the request `clustermonitorgraphs?action=query` sends out only once after the pod recovers; if I refresh the page manually the request will start sending out every 30s and the gauge will show the new look.

**Comment by loganhz** [comment]
@jiaqiluo 

> I tracked the network tab in Chrome, and it shows that the request clustermonitorgraphs?action=query sends out only once after the pod recovers;

I guess you saw an error in UI? So UI will not send the request every 30s. If `clustermonitorgraphs` returns, it will re-send after 30s.

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher: master 4/17  705af329 and the gauge shows the new look after the pod `prometheus-cluster-monitoring` recoveries.
