### ISSUE TITLE
New cluster with Rancher 2.2.1 with monitoring turned on shows no results for master nodes

### ISSUE THREAD

**Issue by dsargent3220** [rancher/rancher#19271]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1.  Create a new cluster with three "master" nodes (etcd and control plane) and any number of worker nodes.
OS used is Centos 7
2.  Turn on Prometheus monitoring in Global
3.  Wait a while

**Result:**
* View a worker node in the GUI, notice that metrics are displayed on the gauges and in "Node metrics"
* View one of the etcd/control plane nodes, notice the gauges appear broken with "loading" tags in green.  Expand "Node metrics", displays "Not enough data to graph"

**Environment information**
- Rancher version 2.2.1
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): On prem, Custom on Centos 7.5
- Machine type (cloud/VM/metal) and specifications (CPU/memory):  Virtual machine using VMWare
- Kubernetes version (use `kubectl version`): 
> kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Docker version (use `docker version`):
18.9.2
![image](https://user-images.githubusercontent.com/3372486/55250839-60491c00-520c-11e9-956f-769a616f0c5f.png)

**Comment by loganhz** [comment]
Could you try https://github.com/rancher/rancher/issues/19187#issuecomment-476891083, please?

**Comment by cjellick** [comment]
@loganhz your belief is that this is caused by port 9796 not being open on the hosts and that updating the documentation to call out this port should be a sufficient fix?

**Comment by dsargent3220** [comment]
Yes, that was the fix for us, we needed to open the port in the on host firewall.  That fixed it.  Sorry I didn't see the other ticket before opening this one, I did do a search but must have missed that one.

**Comment by loganhz** [comment]
@cjellick Sure. I think we have that in the doc. I will add it if we don't have

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19187 as @dsargent3220 confirmed it is the same issue
