### ISSUE TITLE
Not able to remove default certificate from LB in UI

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1927]
Rancher 	v0.35.0-rc4
Cattle 	v0.86.0
User Interface 	v0.45.0
Rancher Compose 	beta/latest
==============================
Steps to Reproduce:

1. Create a service, SSL LB, add a certificate
2. I wanted to delete that cert since it was expired. This action gave me warning saying - "Certificate is in use by load balancer services" <lb name>
3. Edit LB and remove the cert by selecting "Choose a Certificate.."
4. Click Save
5. This action did not have any effect and hence user is not able to delete the cert (in my case, it was expired and hence wanted to delete from cattle)

Expected Result:

User should be able to have some way to delete the expired or invalid cert. If correct design is to disable edit/remove default cert and save, either save can be disabled or user can be given a warning message.

**Comment by rancherdev** [comment]
@aruneli , In step3 , did you choose a different certificate ? Currently , LB with ssl enabled listeners should have a default certificate associated with it. So you will not be allowed  to delete the default certificate but you should be allowed to set default  to a different certificate .

**Comment by sangeethah** [comment]
@aruneli , In step3 , did you choose a different certificate ? Currently , LB with ssl enabled listeners should have a default certificate associated with it. So you will not be allowed to delete the default certificate but you should be allowed to set default to a different certificate .

**Comment by aruneli** [comment]
@rancherdev : I and @vincent99 discussed this. This is to track for User getting a error message on edit/remove default cert/save. If default cert is expired, user will delete that cert and if user is expected to add a new cert before deleting the expired default cert, the mentioned flow of actions need to give message.
