### ISSUE TITLE
should Rancher 2.2.1 with rke 0.2.0 release or rke 0.2.1 ?

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#19280]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
Rancher 2.2.1 release note  https://github.com/rancher/rancher/releases   with
rke version 0.2.0
Kubernete 1.13.5 (default)

however Rke release note 0.2.0 https://github.com/rancher/rke/releases/tag/v0.2.0
Kubernete   v1.13.4-rancher1-2 (default)

rke releaes note 0.2.1  https://github.com/rancher/rke/releases/tag/v0.2.1
Kubernete   v1.13.5-rancher1-2 (default)

Rke 0.2.0 command line seems has problem
https://github.com/rancher/rancher/issues/19189

**Comment by alena1108** [comment]
@panho66 there was no need to bump up rke to v0.2.1 for rancher v2.2.1. We only vendor in new rke version when there are rke code changes. And the only diff between rke v0.2.0 and v0.2.1 is the rancher/types vendor update, and that update got to rancher 2.2.1 independently.
