### ISSUE TITLE
Slow load UI in Rancher 2.2.1 

### ISSUE THREAD

**Issue by aleksey005** [rancher/rancher#19281]
Hello,

Rancher 2.2.1 UI not load in Default project, in System project UI load fast (use nginx reverse proxy for SSL certs). Through the rancher-cli polling and operations take place quickly, but through the graphical UI cannot open the project Default.

Provider: Custom
Version: v1.13.5
Nodes: 4

![slow_load_rancher_2 2 1](https://user-images.githubusercontent.com/6145279/55289234-5706ad80-53cc-11e9-8da7-a6730ea9c6cc.png)

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/16605 and https://github.com/rancher/rancher/pull/19228
