### ISSUE TITLE
Service Discovery Links Not Updating

### ISSUE THREAD

**Issue by danielbjornadal** [rancher/rancher#19289]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
After upgrading to rancher 2.2, DNS Service Discovery links are not created or updated.
`Add Record` in `Service Discovery` that points to a `Workload`
```
$ kubectl get service -n shiftreport
NAME            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   
database        ClusterIP   None         <none>        42/TCP    
database-test   ClusterIP   None         <none>        42/TCP    
```

**Result:**
Logs are spammed with:
```
kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name | head -1) -c kubedns
...
I0401 07:55:58.537184       1 dns.go:601] Could not find endpoints for service "database" in namespace "shiftreport". DNS records will be created once endpoints show up.
I0401 07:55:58.537209       1 dns.go:601] Could not find endpoints for service "database-test" in namespace "shiftreport". DNS records will be created once endpoints show up.
```

**Other details that may be helpful:**
Worked fine before upgrading to 2.2
**Update 1:** Adding Type=Selector works fine, but not Type=Workload

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by alena1108** [comment]
@sangeethah can you try to reproduce the issue

**Comment by sangeethah** [comment]
Tested the following scenario in a HA setup upgraded from 2.1.6 to 2.2.0.

In existing cluster, 
Create a workload - `wkl1`.
Create a DNS Record - say - `test1-dns` by choosing "One or more workloads" option pointing to `wkl1`.
DNS resolution for `test1-dns`  works as expected. It resolves to all pods of the workloads it is pointing to as expected.

```
root@testclient-667fc9ccfb-jkdsg:/# dig test1-dns.mytest1.svc.cluster.local  +short
10.42.0.4
10.42.1.6
10.42.2.5
root@testclient-667fc9ccfb-jkdsg:/# 
```
We do see these errors in kube-dns , but there should be retries that would succeed.
```
I0401 18:12:10.609808 1 dns.go:601] Could not find endpoints for service "test1-dns" in namespace "mytest1". DNS records will be created once endpoints show up.
I0401 18:12:10.618171 1 dns.go:601] Could not find endpoints for service "test1-dns" in namespace "mytest1". DNS records will be created once endpoints show up.
I0401 18:12:21.678728 1 dns.go:601] Could not find endpoints for service "testclient" in namespace "mytest1". DNS records will be created once endpoints show up.
```

@danielbjornadal In your case , Does DNS resolution for "database-test" fails ? Does the DNS resolution for "database" work?
The error seen in kube-dns happens once but it should have retried and succeeded. Do these errors seen in kubedns stop for you?

**Comment by danielbjornadal** [comment]
@sangeethah 
DNS to `database` and `database-test` does not work.

All Workload Service Links that where created before the upgrade works.
All Workload Service links that are created after the upgrade does not work.
All Selector Service Links created after the upgrade works.

Before the upgrade, creating a new `workload`would automatically create a Workload Service Link to that Workload. This does not happen in 2.2.0.

Our Rancher are managing 3 separated clusters. One have different K8s and Docker Version than the others (v1.13.4 & 18.06.3-ce), and all have exactly the same problem.
Two of the clusters is in the same /24 network as Rancher.

All kube-dns Workloads all report the same errors as mentioned in the original post. 1 every 5 minutes.

**Comment by alena1108** [comment]
@danielbjornadal where exactly do you see this error `The target type cannot be Workload.`?

**Comment by deniseschannon** [comment]
@danielbjornadal If you're still facing this issue, can you help answer the questions posed. Our QA team has not been able to reproduce.

**Comment by danielbjornadal** [comment]
We have upgraded to Rancher 2.2.4, and are no longer experiencing this issue.
