### ISSUE TITLE
Supported method to inject a custom fluentd configuration

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#19286]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement Request

Request a supported solution from Rancher to drop logs generated by the fluentd containers or even better, a supported method to inject a custom fluentd configuration.

Rancher version:
v2.1.3

**Comment by deniseschannon** [comment]
It was listed as "advanced mode" internally in engineering: https://github.com/rancher/rancher/issues/15558

**Comment by bofh666** [comment]
@deniseschannon May I ask you to look into: https://forums.rancher.com/t/need-help-in-advanced-cluster-logging-configuration/16409 ?
