### ISSUE TITLE
v2.2.1 can not edit Memory Reservation & CPU Reservation in prometheus-cluster-monitoring

### ISSUE THREAD

**Issue by sunny0826** [rancher/rancher#19288]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
 global->cluster->System->prometheus-cluster-monitoring->edit->upgrade->Security & Host Config

I change the Memory Reservation & CPU Reservation to 500MiB,but when the update is over, it changes back.
--

**Result:**
This could be a bug！

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.2.1
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):aliyun-cloud/146/293
- Kubernetes version (use `kubectl version`):v1.11.5

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:48:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.06.2-ce-3
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   bb75847
 Built:        Tue Apr 17 08:08:32 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce-3
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   bb75847
 Built:        Tue Apr 17 08:11:43 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by alena1108** [comment]
@sunny0826 What is the reason you are trying to modify the prometheus default parameters? Changing monitoring cpu/memory reservation is not advisable as the default amount defines what is needed to run monitoring successfully. 

@loganhz as Prometheus gets deployed from the catalog, I assume app controller logic would always restore the app to the params defined in the template. Can you confirm.

**Comment by sunny0826** [comment]
Because the Pod of **prometheus-cluster-monitoring** always unavailable ! It restarted 419 times in 16 hours ！Our cluster is not very large ,that has only 20 nodes, 146 CPUs and 293M memory .I can only make him work by changing his configuration.But this doesn't work.

**Comment by sunny0826** [comment]
I try to change the value of helm charts that ***cluster-monitoring***. But it doesn't work too.

**Comment by sunny0826** [comment]
sometimes the Rancher will create new namespace like ***cattle-prometheus-p-zkxz6*** , I think this phenomenon is related to the restart.

**Comment by loganhz** [comment]
Where did you update the limit value? Can you provide the screenshot?

**Comment by sunny0826** [comment]
![image](https://user-images.githubusercontent.com/24563928/55378013-f1403000-5549-11e9-9810-a72878ba56af.png)

**Comment by loganhz** [comment]
You need to update it in enable monitoring page.

**Comment by sunny0826** [comment]
![image](https://user-images.githubusercontent.com/24563928/55378127-411ef700-554a-11e9-8346-3319221edca2.png)

**Comment by loganhz** [comment]
Currently, you cannot upgrade it here. Please update it in enable monitoring page. You can change the limit and click save there

**Comment by sunny0826** [comment]
reinstall ?

**Comment by loganhz** [comment]
1. Go to Tools-> Monitoring
2. Update the cpu limit and memory limit
3. Click Save

**Comment by sunny0826** [comment]
I change the ***Cluster Monitoring Configuration*** , and successfully modified the configuration. I will see if it will restart.

**Comment by loganhz** [comment]
What's the limit now ? like 2GB?

**Comment by sunny0826** [comment]
1 GB

**Comment by sunny0826** [comment]
https://github.com/rancher/rancher/issues/19078  I find a issue that can solve my problem. You may need to put that on the official website.

**Comment by loganhz** [comment]
@sunny0826 your issue describes `I change the Memory Reservation & CPU Reservation to 500MiB,but when the update is over, it changes back`

#19078 is talking about node exporter port. 

Yes,  we will add the doc for it. Thanks

**Comment by loganhz** [comment]
BTW, we have a doc https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/#resource-consumption

**Comment by sunny0826** [comment]
My bad

**Comment by loganhz** [comment]
Close https://github.com/rancher/rancher/issues/19288#issuecomment-478849274 works
