### ISSUE TITLE
Support for editing/upgrading certificates.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1928]
Server version - V0.35.0-rc4

When existing certificates that are used by Load Balancers ,  need to be updated  (when expired/for extending support for more domains) , the older certificates need to deleted from every load balancer that is configured to use this certificate and the new certificates need to added back to them.

It would be helpful to have a workflow that will allow for the editing/upgrading an existing certificate which will result in the newer version of the certificates to be pushed to all the existing LB services that uses them.

**Comment by vincent99** [comment]
The ability to edit the fields was added shortly before 1.0.0, so this is possible now.

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc3
