### ISSUE TITLE
Rancher UI always shows current time for "Created" for clusters

### ISSUE THREAD

**Issue by happydenn** [rancher/rancher#19285]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Click on any cluster
2. Switch to "Cluster" tab

**Result:**
On the second row of the cluster information, `Created` always shows the current time instead of cluster's creation time.

**Other details that may be helpful:**
This is happening for all the clusters that Rancher manages. Doing a `kubectl get clusters` from the `local` cluster shows the age of the clusters correctly but I'm not sure where the UI obtains the information from.

![image](https://user-images.githubusercontent.com/195297/55300501-57558600-546a-11e9-8218-a1fc0161d485.png)

**Environment information**
- Rancher version: 2.2.1
- Installation option (single install/HA): HA

**Comment by davidnuzik** [comment]
Note: this was validated and is working in v2.2.2-rc1 in issue #19309 (but will need to check again in v2.3)

**Comment by davidnuzik** [comment]
Version: Master (4/22/19)

I have confirmed again in latest master (for v2.3) that this is working. The cluster and node dashboard shows the correct creation time (not current time as they did before).
