### ISSUE TITLE
Cannot add node template for AWS China regions

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19287]
rancher/rancher:v2.2.1

The same API key works well in v2.1.8

Steps: 

1. Create a AWS node template
2. Select `cn-north-1` or `cn-northwest-1`
3. input key and secret
4. Click `Create`

Results:

UI shows `AuthFailure: AWS was not able to validate the provided access credentials`.

![image](https://user-images.githubusercontent.com/21168270/55304740-8f1af880-547f-11e9-9f23-50b343b12191.png)

**Comment by loganhz** [comment]
The root cause might be https://github.com/rancher/rancher/blob/master/pkg/httpproxy/sign.go#L103

It says `//format : service.region.amazonaws.com`

But for the format is `service.region.amazonaws.com.cn` for China regions.

**Comment by sowmyav27** [comment]
verified on `rancher:master`.
**Steps taken:**
1. Create an AWS node template
2. Select cn-north-1 or cn-northwest-1
3. give in the aws key and secret
4. Click Create
5. No error is seen on the UI. Proceed to create the node template.
6. Created an AWS cluster for region cn-north-1. Unable to create a cluster for region cn-northwest-1, issues tracked separately in #19379.

**Comment by deniseschannon** [comment]
@loganhz can you have someone in china confirm that this is working in china?

**Comment by loganhz** [comment]
Sure

**Comment by loganhz** [comment]
Sure

**Comment by rootwuj** [comment]
Tested with rancher/rancher:v2.2.4-rc19 from May 30

Step1:
1. Create two AWS node templates
2. select cn-north-1 and cn-northwest-1 region respectively

Node templates create successfully.

Step2:

1. Create EC2 cluster for region cn-north-1 
Created successfully.

2. Create EC2 cluster for region cn-northwest-1
Cluster was not created successfully. Get the same error as issue [#19379](https://github.com/rancher/rancher/issues/19379)
