### ISSUE TITLE
Monitoring - should use ClusterIP to query metric expressions

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#19292]
For now, Monitoring queries metrics expressions by`prometheus-operated` Service, this will increase the pressure on the DNS service within the cluster and can cause `kube-dns` component to crash.

We should replace the Service accessing by ClusterIP.

For the test, don't introduce regression testing, only verify that the main UI can view the Monitoring charts or not.

**Comment by loganhz** [comment]
waiting for https://github.com/rancher/rancher/pull/19295 merged and backport to 2.2 branch

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master beffccd

As a suggestion from the issue, validate only if the main UI can view the Monitoring charts or not. 

Tested on the following clusters and confirm the charts showed in the main UI
- EC2 cluster
- DO cluster
- custom cluster (3 nodes, one role on each)
- Imported GKE cluster

As to this issue, the above validation is sufficient to close it.
