### ISSUE TITLE
[Windows] Failed to connect to proxy: Error response from daemon: invalid volume specification: 'c:\etc\cni:c:\cni'

### ISSUE THREAD

**Issue by pseckd** [rancher/rancher#19290]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
add or upgrade Windows Node with the agent

**Result:**
Failed to connect to proxy: Error response from daemon: invalid volume specification: 'c:\etc\cni:c:\cni'

**Other details that may be helpful:**
Release 2.2.1 with Agent 2.2.1-nanoserver-1803

**Environment information**
rancher/rancher HA

**Cluster information**
custom Cluster, docker 18.09.4 on Windows Server
Kube Version 1.11.8

**Comment by loganhz** [comment]
@pseckd Can you try `rancher/rancher:master` on Windows 2019 , please?
You can use `Microsoft Windows Server 2019 Base with Containers - ami-0bb1a4b4bf67bd5bb` if you are using AWS
![image](https://user-images.githubusercontent.com/21168270/57112986-12788400-6d75-11e9-8c83-9676db8d4fd1.png)

**Comment by thxCode** [comment]
@pseckd , Could you try the master version on Windows 2019? BTW, it's not recommended to run with Docker CE on Windows Server, please try to install Docker EE via https://docs.docker.com/install/windows/docker-ee/.

**Comment by loganhz** [comment]
Please let us know if you still have this issue in v2.3.0-alpha3
