### ISSUE TITLE
Some problems with Alibaba ACK cluster

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#19294]
Rancher Version: v2.2.1

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create alibaba ACK cluster - `cluster1`
Create alibaba ACK managed kubernetes cluster - `cluster2`

**Problem:**
1. The dashboard red alert `scheduler` and `controller-manager` are unhealthy in cluster2.
<img width="1359" alt="2-01" src="https://user-images.githubusercontent.com/42061003/55334321-9b2ca780-54cb-11e9-9c98-d8873cd013f5.png">

2. The cluster node name is the same, both cluster1 and cluster2 have this problem.
<img width="1340" alt="1-02" src="https://user-images.githubusercontent.com/42061003/55335559-e1830600-54cd-11e9-86a6-f8d3ea77a74d.png">

3. Deploy workload - configure Node Scheduling -select `Run all pods for this workload on a specific node`, the drop-down list cannot select node.
<img width="1394" alt="1-03" src="https://user-images.githubusercontent.com/42061003/55336189-1d6a9b00-54cf-11e9-92dd-731205fb44cb.png">

**Comment by deniseschannon** [comment]
Is this the same issue that we have with AKS? https://github.com/rancher/rancher/issues/17344

Can we create a UI ticket to do the same fix until alibaba ACK exposes the ability? @loganhz

**Comment by loganhz** [comment]
It's the same issue

**Comment by loganhz** [comment]
Created https://github.com/rancher/rancher/issues/20560

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/26760
