### ISSUE TITLE
Backport: Rancher UI always shows current time for "Created" for clusters

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19309]
backport https://github.com/rancher/rancher/issues/19285

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1

- Create a DO RKE cluster
- Notice, on the cluster page the Created time is actually the current time

**Validation Steps:**
v2.2.2-rc1

- Create a DO RKE cluster
- Notice, on the cluster page the Created time is actually the CREATED TIME now
- Wait and refresh the page to ensure time does not change. Time actually reflects correct time when the cluster was created.

**Comment by davidnuzik** [comment]
This should NOT have slipped thru into release; the test plan was updated to more carefully check around cluster page basic info (Provider, Version, Nodes, CPU count, Memory, Created time, etc)
