### ISSUE TITLE
UI: Global Menu opens itself sometimes when switch clusters

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19300]
Version: v2.1.7, v2.2.0, and master 4/1/19 ImageID: bfcec653d832

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a digital ocean cluster, create an ec2 cluster
- Enable monitoring on ec2 cluster (makes browser take longer to refresh UI and switch clusters)
- On global menu click on digital ocean cluster name and move mouse cursor off menu immediately after clicking. Do this again for the ec2 cluster. Click the cluster name for ec2 and move your mouse quickly off the global menu area after clicking.

**Result:**
Sometimes, and fairly often, the global menu pops itself backup between switching clusters if the page is still loading.

**Other details that may be helpful:**
It's important to have monitoring on the ec2 cluster. You could probably reproduce with monitoring on both clusters. The important thing is that it makes the UI take longer to switch between clusters and therefore easier to reproduce.

This video does a good job of showing the issue:
https://vimeo.com/327804433

I reproduced on several environments several times as did Tani. v2.2.0 and latest master affected.

**Comment by davidnuzik** [comment]
Also reproduced in v2.1.7 global menu.

**Comment by alena1108** [comment]
Moving to 2.3 as the issue existed in 2.1.x

**Comment by davidnuzik** [comment]
Version: Master (4/15/19) (Latest master) ImageID: 0d755e769e77

I am still observing the issue with the latest master available. I tested with Firefox (latest update).
I have a video here of the issue occurring: https://vimeo.com/330607870

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: Master (4/26/19)

I made sure to use the same method to test (Firefox and several clusters that are slow to load). I am no longer seeing this issue. I also checked Chrome as well.
