### ISSUE TITLE
Ability to edit service/containers from UI to trigger a rolling upgrade of the service/container. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1930]
https://github.com/rancher/rancher/issues/198#issuecomment-135874384

@ebuildy suggested this way of allowing editing containers/service.

"It's a pity to have to clone 2 times services/containers in order to keep the same name/ports, why is not possible to edit the full settings then click on save could execute a kind of rolling upgrade? (delete each service containers 1 by 1 in order to "refresh" them)."

**Comment by Tails** [comment]
+1

I might not have the server capacity to allow a whole service to be cloned.

**Comment by kaos** [comment]
+1

I'd like to be able to tweak all parameters of a service, just as if I'm just creating it, without the hazzle of cloning and consequently update links.. It's just a nice to have feature, though. I'm much more eager to get #2288 ;)

**Comment by flaccid** [comment]
That convo was certainly nutted out in https://github.com/rancher/rancher/issues/198 I think the general gist of it is that if its editable it should be editable.

**Comment by deniseschannon** [comment]
With in-service upgrade, this is addressed.
