### ISSUE TITLE
Backport: Improve Dashboard Usability 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19308]
Backport https://github.com/rancher/rancher/issues/19249

**Comment by westlywright** [comment]
related PR: https://github.com/rancher/ui/pull/2824

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1

- Have a cluster with at least 2 scheduleable nodes.
- Enable monitoring. Notice the outlines and dots are still there (node min/max)

**Validation Steps:**
v2.2.2-rc1

- Have a cluster with at least 2 scheduleable nodes.
- Enable monitoring. Notice the outlines and dots are NOW REMOVED.
- Hover around the areas where tooltips used to be expected when we had the outlines and dots (node min/max) ensured these tooltips are gone as well (nothing left behind that is unexpected).
