### ISSUE TITLE
Backport: Breaking change in Node Template after 2.2

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19314]
Backport https://github.com/rancher/rancher/issues/19219

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by sowmyav27** [comment]
reproduced issue on `v2.2.1` .
**Steps taken:**
1. create a node template(type - AWS) via API v3. Give in values for field `amazonec2Config` - { "accessKey": "xyz",
"secretKey": "yyy"}.
2. Click on send request. 
3. Error is seen as below:
```
{
"baseType": "error",
"code": "MissingRequired",
"message": "Cloud Credential must be set",
"status": 422,
"type": "error"
}
```
verified on `rancher/rancher:v2.2.2-rc1`. 
**Steps taken:**
1. create a node template(type - AWS) via API v3. Give in values for field `amazonec2Config` - { "accessKey": "xyz",
"secretKey": "yyy"}.
2. Click on send request. 
3. A node template will be created successfully.
4. Create a cluster with this node template.
5. Cluster will be created successfully.
