### ISSUE TITLE
Global Role Edit

### ISSUE THREAD

**Issue by RRadziejewski** [rancher/rancher#19319]
Hello, I have a question.
I really need to add some custom global role into the rancher.
This can be empty without any privileges. I need that to indicate that something can be done. But I don't wanna use existing roles because every role is giving some privileges and I don't want to grant them to this particular "special" user.
Any ideas?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/16216#issuecomment-434140610
