### ISSUE TITLE
Backport: [Pipeline] Publishing catalog template fails with certificate error

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19313]
backport https://github.com/rancher/rancher/issues/19220

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by rootwuj** [comment]
Test with rancher/rancher: v2.2.2-rc1
Validate the publishCatalogConfig step with self-signed cert Git service (Gitlab / Github / Bitbucket server), this version of the pipeline can run successfully.
