### ISSUE TITLE
Backport: Cannot add node template for AWS China regions

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19312]
Backport https://github.com/rancher/rancher/issues/19287

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by sowmyav27** [comment]
reproduced on `rancher:v2.2.1`.
**Steps taken:**
1. Create an AWS node template
2. Select `cn-north-1` or `cn-northwest-1`
3. give in the aws key and secret
4. Click Create
Error `AuthFailure: AWS was not able to validate the provided access credentials` is seen.

Verified on `rancher/rancher:v2.2.2-rc1`.
**Steps taken:**
1. Create an AWS node template
2. Select `cn-north-1` or `cn-northwest-1`
3. give in the aws key and secret
4. Click Create 
5. No error is seen on the UI. Proceed to create the node template. 
6. Create a cluster using this node template. Cluster launches successfully.

**Comment by sowmyav27** [comment]
Created an AWS cluster for region `cn-north-1`. Unable to create a cluster for region `cn-northwest-1`, issues tracked separately in https://github.com/rancher/rancher/issues/19379.
