### ISSUE TITLE
EBS attachment limit

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#19328]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a deployment to a single EC2 host uses more than 26 volumes using the storage-ebs driver.

**Result:**
After 26 ebs volumes are created. storage-ebs will start failing to attach new volumes to the server. At which point it will keep creating new ebs volumes without cleaning up the failed volumes.

**Other details that may be helpful:**
While Rancher is trying to create a EBS volume, it gets a 500 error saying that `mkfs.ext4` failed. But instead of handling the error and deleting the problematic volume, it keeps the volume in "available" state and creates a new one. This process is repeated until eventually the volume is correctly mounted in the container, or the stack dies of an internal timeout we created.

Because of this, we are hitting the storage limit on multiple accounts, preventing engineers from spinning up new stacks, and also dealing with a very high finance cost.

This is the error message:

Error (Failed to create volume bamboo-demand_carta_web_db_9_adf96. Driver: rancher-ebs. Status code: 500. Status: 500 internal server error. Error Message: Usage: mkfs.ext4 [-c|-l filename] [-b block-size] [-C cluster-size] [-i bytes-per-inode] [-I inode-size] [-J journal-options] [-G flex-group-size] [-N number-of-inodes] [-m reserved-blocks-percentage] [-o creator-os] [-g blocks-per-group] [-L volume-label] [-M last-mounted-directory] [-O feature[,...]] [-r fs-revision] [-E extended-option[,...]] [-t fs-type] [-T usage-type ] [-U UUID] [-jnqvDFKSV] device [blocks-count])

We're using `rancher/storage-ebs:v0.9.7`.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v1.6.26
- Installation option (single install/HA): HA

**Comment by mattmattox** [comment]
I believe the issue is located in the do_attach() function where it hits the unrecoverable error section. Currently it does a detach-volume only but it doesn't cleanup the new volume. 

https://github.com/rancher/storage/blob/master/package/ebs/rancher-ebs

**Comment by snacky6** [comment]
We faced the exact same issue today. We managed to find some king of temporary a solution by manually setting the value of `ec2_az` to another region where some EC2 instances can attach volumes. I'm currently looking for a way to automatically create docker volumes for our Redis databases without creating EBS volumes (or maybe don't attach it to a EC2 instance) to avoid this kind of limitation.

**Comment by deniseschannon** [comment]
AWS doesn't recommend more than 40 volumes per host, so we can update it per recommended number from AWS, but I wouldn't advise we allow more than the recommended amount.

**Comment by soumyalj** [comment]
Reproduced the issue with Rancher v1.6.28. 

Create a single node Cattle env using AWS nodes. 
Deploy EBS driver catalog
Create stacks so that we can have  26 volumes using the storage-ebs driver.
After 20 ebs volumes are created. storage-ebs will start failing to attach new volumes to the server. At which point it will keep creating new ebs volumes without cleaning up the failed volumes.

In AWS, EBS volumes with the same name are created in "Available" state repeatedly

Stack creation fails with the below error:

```
Error (Failed to create volume compassionate-curran_testvol_1_d5357658-6bf5-46e1-a74b-a2a3c0397f89_be7f3. Driver: rancher-ebs. Status code: 500. Status: 500 internal server error. Error Message: Usage: mkfs.ext4 [-c|-l filename] [-b block-size] [-C cluster-size] [-i bytes-per-inode] [-I inode-size] [-J journal-options] [-G flex-group-size] [-N number-of-inodes] [-m reserved-blocks-percentage] [-o creator-os] [-g blocks-per-group] [-L volume-label] [-M last-mounted-directory] [-O feature[,...]] [-r fs-revision] [-E extended-option[,...]] [-t fs-type] [-T usage-type ] [-U UUID] [-jnqvDFKSV] device [blocks-count])

```

**Comment by alena1108** [comment]
Can be tested with the latest ebs catalog v0.6.1

**Comment by StrongMonkey** [comment]
With the current approach we can't create more than 21 volumes per host, but the fix will prevent creating new EBS volume if failure case happens(which is we go beyond the limit of 21 volumes).

**Comment by soumyalj** [comment]
Tested with ebs catalog v0.6.1.
Create a single node Cattle env using AWS nodes.
Deploy EBS driver catalog
Create stacks so that we can have 21 volumes using the storage-ebs driver.
After 21 ebs volumes are created, rancher-ebs will prevent  creating new volumes. 
At this point, the issue described above is not seen. In AWS, EBS volumes with the same name  are not created continuously. 
Logs for EBS driver container has the below as expected for each volume created beyond the allowed limit. 
```
All device paths are in use for instance-id: i-0f22e6307efce6263" name="test32_testvol_1_4c858c43-a35c-4e3b-95e1-e409e63c6cd3_35377"

```
