### ISSUE TITLE
Backport: Node selector for monitoring doesn't work in some case

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19324]
Backport https://github.com/rancher/rancher/issues/19218

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication steps:**
v2.2.1
- Create DO cluster, 1 node (all roles) set node label mine/horse = true (UI sends `mine/horse: "true"`)
- Enable monitoring but create a node selector with mine/horse = true (UI sends `prometheus.nodeSelectors[0]: "mine/horse=true"`)
- Monitoring does not work (always says `Monitoring API is not ready`)
- Review prometheus-operator logs and get errors mentioned above like:
`E0403 17:10:03.988174 1 reflector.go:134] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:404: Failed to list *v1.Prometheus: v1.PrometheusList.Items: []*v1.Prometheus: v1.Prometheus.Spec: v1.PrometheusSpec.NodeSelector: ReadString: expects " or n, but found t, error found in #10 byte of ...|e/horse":true},"paus|..., bigger context ...|r":{"beta.kubernetes.io/os":"linux","mine/horse":true},"paused":false,"podMetadata":{"labels":{"app"|...`

**Validation steps:**
v2.2.2-rc1
- Create DO cluster, 1 node (all roles) set node label mine/horse = true (UI sends `mine/horse: "true"`)
- Enable monitoring but create a node selector with mine/horse = true (UI sends `prometheus.nodeSelectors[0]: "mine/horse="true""`) (notice the quotes around true string now)
- Monitoring DOES work now. Cluster and node metrics look normal.
- prometheus-operator logs look nominal

**Comment by davidnuzik** [comment]
Test plan updated so we check for regression of this going forward.
