### ISSUE TITLE
Trying to save after editing container throws UI Error: "Health Check port is required"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1932]
v0.35.0-rc5

Steps to Reproduce:
1. Created a standalone container through Infrastructure tab. 
2. Click on Edit and change name.
3. Save

Result: UI Error "Health Check port is required"

Expected Result: Save the new name with no issues.

**Comment by deniseschannon** [comment]
Also happens for containers in services.

**Comment by aburnett** [comment]
Ditto for editing exposed ports on a container.

**Comment by deniseschannon** [comment]
v0.37.0-rc1
Verified Fixed. Able to save name changes.
