### ISSUE TITLE
[Pipeline] Jenkins instance fails to be ready on hosts with over 32 cores

### ISSUE THREAD

**Issue by wangqiongkaka** [rancher/rancher#19322]
Jenkins instance fails to be ready on hosts with over 32 cores

https://github.com/jenkinsci/docker/issues/702

**Comment by gitlawr** [comment]
Confirmed in v2.2.1.
1. Add a single node custom cluster with 72 cores.
2. Run go example pipeline.
3. Jenkins logs `up and running` but curling `localhost:8080` inside the container gives no response.

**Comment by gitlawr** [comment]
Need to bump jenkins to 2.138.2+ to address this.
See: https://issues.jenkins-ci.org/browse/JENKINS-33412?focusedCommentId=352805&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-352805

**Comment by kingsd041** [comment]
rancher/rancher:master-head (08/27/19)
 
Currently blocked from testing by https://github.com/rancher/rancher/issues/21777#issuecomment-524912246

**Comment by kingsd041** [comment]
Version: master master-head (8/30/19) 
Confirmed fix. I can run the sample pipeline in a 72 core single-node custom cluster and get the expected results.
