### ISSUE TITLE
Backport: UI: 2.2 - Prometheus error when installing Monitoring 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19326]
backport https://github.com/rancher/rancher/issues/19197

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by alena1108** [comment]
Update: removed `to-test` label. This UI fix should be tested in conjunction with https://github.com/rancher/rancher/issues/19278, and the fix for the backend is not in yet.

**Comment by thxCode** [comment]
@jiaqiluo , including validation cases:
1. Enable Cluster Monitoring -> the monitoring dashboards should be on
2. Disable Cluster Monitoring -> the monitoring dashboards should be off
3. Enable Cluster Monitoring and then drop `cattle-prometheus/prometheus-cluster-monitoring` Pod -> the monitoring dashboards should be off until Prometheus Pod redeploy

**Comment by alena1108** [comment]
Can be tested with rancher/rancher:v2.2.2-rc2

**Comment by davidnuzik** [comment]
Version: v2.2.2-rc2

I followed the suggested steps outlined by @thxCode 
1. Enable Cluster Monitoring -> the monitoring dashboards should be on
2. Disable Cluster Monitoring -> the monitoring dashboards should be off
3. Enable Cluster Monitoring and then drop `cattle-prometheus/prometheus-cluster-monitoring` Pod -> the monitoring dashboards should be off until Prometheus Pod redeploy

I confirmed that this works (step 3) the dashboard instantly goes to the classic cluster page when we delete the prometheus-cluster-monitoring-0 pod. It then quickly recovers and brings a new pod up.

I do see this though once it has recovered. @thxCode is a refresh needed and expected?
![image](https://user-images.githubusercontent.com/45179589/55575773-8cf5ab80-56c4-11e9-9360-ef88b727d13d.png)

I can confirm we at least don't see a broken cluster monitoring page now as we did before when prometheus was unhealthy. But when it recovers the UI isn't 100% okay until I manually refresh.

Once I manually refresh now everything is fine:
![image](https://user-images.githubusercontent.com/45179589/55575839-b282b500-56c4-11e9-957f-47153e25cd95.png)

**Comment by davidnuzik** [comment]
@sangeethah ^^ Just a reminder. This issue is validated and is working as expected per our discussion. I am merely waiting to see if @thxCode has any input per my comment. I wanted to double-check to ensure that once prometheus recovers and is healthy that we expect the user to manually refresh to fully fix monitoring.

The important thing is that monitoring is no longer in a quite broken state where it might show "loading" for % used (green text) whenever prometheus is not healthy and the UI quickly switches to basic view when it detects its unhealthy.

The issue can be closed later with my findings above; just wanted input.

**Comment by jiaqiluo** [comment]
Some observation on v2.2.2-rc2: the cluster page is not stable after the pod is recreated. 
As soon as the pod is recreated, the cluster page looks like this:
<img width="1388" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55581782-9d148780-56d2-11e9-9098-0cf826d55ae6.png">

Then the wheel metrics go back to classic view after 3 - 5 seconds:
 
<img width="1434" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55581791-a271d200-56d2-11e9-8015-d4e71393d53b.png">

Now if I refresh the page manually, it recovers to the desired view:
<img width="1392" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55581855-c3d2be00-56d2-11e9-83d6-02fb217de9ef.png">

**Comment by loganhz** [comment]
@jiaqiluo @davidnuzik I think we don't need refresh. If we can improve it.

**Comment by alena1108** [comment]
Can be tested with `rancher/rancher:v2.2.0-rc4`

**Comment by jiaqiluo** [comment]
The bug fix is validated with v2.2.2-rc5 on both fresh installed and upgraded setup 
Notice that when the pod is re-created and becomes active, the UI looks like this with the classic wheels 
<img width="1489" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55762131-9e1d2000-5a16-11e9-8650-731e53bfba36.png">

And after about 1 - 2 mins, the wheels changes to this which is expected 
<img width="1456" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55762156-b8ef9480-5a16-11e9-9423-9f84418dbdec.png">

So there is no need to refresh the page manually.
