### ISSUE TITLE
Backport: Catalog App - need to click the launch button twice to get the app launched 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19337]
Backport https://github.com/rancher/rancher/issues/19168

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1
_From https://github.com/rancher/rancher/issues/19168#issuecomment-477388917_

As admin, create a cluster - cluster1 and assign user1 as cluster member.

- Log in as user1.
- Create a project.
- Deploy an App in this project.
- Notice that when you click on "launch" for the first time the API does provide a 403 forbidden error.
- If you click the "Launch" button to deploy the catalog app the second time it works. But we should not see an error on the first attempt in the browser dev console.

**Validation Steps:**
v2.2.2-rc1

Perform the same as above. Now when you click "Launch" button to deploy the catalog app you do not get an API error on the first try. See linked issue for details.
