### ISSUE TITLE
Editing Cluster with Cluster Owner That Is Not the Creator is Broken

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#19332]
**Note:** I looked for an issue already, but my searches didn't uncover anything like this that I could see. 

**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a cluster with user A, ideally using EC2 w/ node pools
2. Add User B as a cluster owner
3. Logout
4. Login as User B
5. Edit Cluster as User B

**Result:**

User B is unable to see node templates because node templates seem to be user scoped. The UI also presents EC2 and Customer as options but neither is checked and I believe that Custom shouldn't even be shown.

If you click Amazon EC2 the rest of the information as you would expect it shows up, except for all the node pools are broken because User B cannot see the templates from User A.

It seems to me that either Node Templates need to be globally available to cluster owners or users that are allowed to edit a cluster or no one except for the cluster creator should be able to edit. 

I'd prefer the former.

**Other details that may be helpful:**

![Screen Shot 2019-04-02 at 1 04 14 PM](https://user-images.githubusercontent.com/48329/55429508-edf87480-5548-11e9-9d86-15f812ee864e.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/12038
