### ISSUE TITLE
Backport: UI - No error message presented to the user when app deployment fails.

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19336]
Backport https://github.com/rancher/rancher/issues/19236

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1
(From #19236)

- As admin , Create a cluster c1 and add user test1 as "cluster member".
- Deploy any app , say redis.
- Log in as test1 . Create a new project.
- Deploy the same app , redis.
- User is brought back to the same page and no error message is presented.

In this case, namespace creation actually failed with following error message -
{"baseType":"error","code":"AlreadyExists","message":"namespaces \"redis\" already exists","status":409,"type":"error"}

**Validation Steps:**
v2.2.2-rc1

- Perform the exact same steps as above in v2.2.2-rc1.

In this case, with v2.2.2.-rc1, the UI now shows an error message: `namespaces "redis" already exists`
![image](https://user-images.githubusercontent.com/45179589/55508503-e7343500-560e-11e9-96c2-337a48b318e5.png)
