### ISSUE TITLE
Backport: Templated Repository URL for Git-based catalog URL is not showing rancher 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19339]
Backport https://github.com/rancher/rancher/issues/19215

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1
- Open Global -> Tools -> Catalogs
- Notice Git-based catalog URL shows example INCORRECTLY as `https://github.com//charts.git` url

**Validation Steps:**
v2.2.2-rc1
- Open Global -> Tools -> Catalogs
- Notice Git-based catalog URL shows example CORRECTLY as `https://github.com/rancher/charts.git` url
