### ISSUE TITLE
certificate-authority-data does not populate when adding cluster authorized endpoint after the fact

### ISSUE THREAD

**Issue by Joeskyyy** [rancher/rancher#19341]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Create a cluster without authorized endpoint
* Edit cluster to now have authorized endpoint
* Generate kubeconfig

**Result:**

kubeconfig will not have a `certificate-authority-data` field

**Other details that may be helpful:**
N/A

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.20
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS , m5.xlarge
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by tfiduccia** [comment]
Version - v2.2.4
This is because it's a custom cluster.  There is no difference in the Run command if endpoint is enabled or disabled.

**Comment by dramich** [comment]
Hey @Joeskyyy, can you provide more detail on what you did turn on the authorized endpoint? Did you just set the `enabled` to `true` or was an `fqdn` also provided?

**Comment by Joeskyyy** [comment]
@dramich Yeah, we edited to `enabled: true` and also updated the `fqdn` at the same time.

**Comment by dramich** [comment]
@Joeskyyy Did you also add anything to `caCerts`? If not this is why it's blank when you attempt to download the kubeconfig.

**Comment by Joeskyyy** [comment]
Ah... that'd definitely do it 🤦‍♀ worked like a charm! Don't know how I missed that one before
