### ISSUE TITLE
Change the default Prometheus cpu/memory limits and reservation

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19349]
Change default CPU Limits to 1000
Change default CPU Reservation to 750

Change default Memory Limits to 1000
Change default Memory Reservation to 750

**Comment by davidnuzik** [comment]
Version: Master (4/4/19) ImageID:

Confirmed the following:
>Change default CPU Limits to 1000
>Change default CPU Reservation to 750
>
>Change default Memory Limits to 1000
>Change default Memory Reservation to 750

Here are the new settings as pictured:
![image](https://user-images.githubusercontent.com/45179589/55572304-23719f00-56bc-11e9-81ab-aef41161b779.png)

I ensured these settings affect the appropriate workloads/containers.
I also ensured HTTP looks correct, and when I make changes they take effect -- the appropriate pods get restarted so new reservation/limits take effect. Node exporter settings are validated in a separate issue.

This area was also smoke tested and I could not identify any issues.

HTTP example:
prometheus.resources.core.limits.cpu: "1111m"
prometheus.resources.core.limits.memory: "1212Mi"
prometheus.resources.core.requests.cpu: "222m"
prometheus.resources.core.requests.memory: "111Mi"

effect:
![image](https://user-images.githubusercontent.com/45179589/55572877-80218980-56bd-11e9-9b72-322c53b19de1.png)

**Comment by davidnuzik** [comment]
Re-opening issue; fix is not yet in Master (4/4/19) We see that Prometheus CPU and Memory are not 750 each yet.

**Comment by Oats87** [comment]
@loganhz what is the driver for this? Are we sure that 1 GB of memory is enough for Prometheus? Have we performed profiling to ensure this?

/cc @ebauman

**Comment by cloudnautique** [comment]
@Oats87, we are trying to come up with a reasonable default that won't immediately fall over in a small cluster. The docs reflect our recommendations based on node counts and our observation. We have done theoretical and actual testing to verify the numbers. 

@ebauman, Agreed in the future it would be nice for autoscaling, but for now the user has to plan out the monitoring infrastructure as they deploy it. From our own experience, it's best to leverage the node selector and have a dedicated host for it. The sizing guide as it is today, and more details will be coming, can be found here: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/#resource-consumption

**Comment by davidnuzik** [comment]
Version: Master (4/15/19)

The default CPU/Memory reservation for Prometheus has changed to 750 each respectively.
The default CPU/Memory limit for Prometheus has changed to 1000 each respectively.

Screenshot of defaults shown:
![image](https://user-images.githubusercontent.com/45179589/56159072-9f030400-5f78-11e9-9f65-02990be3c8c7.png)

After enabling, I confirmed that the reservation/limits indeed took effect.
Upon updating, the appropriate containers get restarted so the new limits take effect.
