### ISSUE TITLE
unable to add a cluster after upgrading rancher

### ISSUE THREAD

**Issue by renperez** [rancher/rancher#19340]
Hey Guys,

Anyone know what is going on here? Just upgraded my rancher to 2.2 and im not running it inside EKS using nginx ingress. Now i'm seeing this error inside my rancher pods.

"400 Bad Request" response

2019/04/02 23:20:58 [INFO] Rancher version v2.2.0 is starting
2019/04/02 23:20:58 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:true ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2019/04/02 23:20:58 [INFO] Listening on /tmp/log.sock
I0402 23:20:58.576699       8 http.go:110] HTTP2 has been explicitly disabled
2019/04/02 23:20:58 [INFO] Running in clustered mode with ID 10.82.82.217, monitoring endpoint rancher/rancher
2019/04/02 23:20:59 [INFO] Starting API controllers
I0402 23:20:59.502391       8 leaderelection.go:187] attempting to acquire leader lease  kube-system/cattle-controllers...
2019/04/02 23:20:59 [INFO] Listening on :443
2019/04/02 23:20:59 [INFO] Listening on :80
2019/04/02 23:20:59 [INFO] Starting cluster controllers for local
2019/04/02 23:20:59 [INFO] Starting cluster agent for local [owner=false]
2019/04/02 23:21:33 [ERROR] Error during subscribe websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:33 [ERROR] Unknown error: websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:46 [ERROR] Error during subscribe websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:46 [ERROR] Unknown error: websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:46 [ERROR] Error during subscribe websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:46 [ERROR] Unknown error: websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:50 [ERROR] Error during subscribe websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:50 [ERROR] Unknown error: websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:51 [ERROR] Error during subscribe websocket: could not find connection header with token 'upgrade'
2019/04/02 23:21:51 [ERROR] Unknown error: websocket: could not find connection header with token 'upgrade'

**Comment by renperez** [comment]
any update on this?

**Comment by renperez** [comment]
I tried changing the config for the cluster node agent and the cluster agent to point to the new url but the handshake still points to the old URL. This is why the handshake is failing

INFO: Environment: CATTLE_ADDRESS=10.82.80.201 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=ip-10-82-80-201.us-west-2.compute.internal CATTLE_SERVER=https://rancher-new.tools.xyz.com
INFO: Using resolv.conf: nameserver 10.82.80.2 search us-west-2.compute.internal options timeout:2 attempts:5
INFO: https://rancher-new.tools.tunenet.io/ping is accessible
INFO: rancher-new.tools.tunenet.io resolves to 35.167.114.26 52.25.37.103 54.213.166.78
time="2019-04-03T18:01:52Z" level=info msg="Rancher agent version v2.2.0 is starting"
time="2019-04-03T18:01:52Z" level=info msg="Option worker=false"
time="2019-04-03T18:01:52Z" level=info msg="Option requestedHostname=ip-10-82-80-201.us-west-2.compute.internal"
time="2019-04-03T18:01:52Z" level=info msg="Option customConfig=map[address:10.82.80.201 internalAddress: roles:[] label:map[]]"
time="2019-04-03T18:01:52Z" level=info msg="Option etcd=false"
time="2019-04-03T18:01:52Z" level=info msg="Option controlPlane=false"
time="2019-04-03T18:01:52Z" level=info msg="Listening on /tmp/log.sock"
time="2019-04-03T18:01:52Z" level=info msg="Connecting to wss://rancher.tools.tunenet.io/v3/connect with token zctb7ckhwztp7kdldnghmtgxj2tl5lb8vf7d8th8s6thmkj49j58jh"
time="2019-04-03T18:01:52Z" level=info msg="Connecting to proxy" url="wss://rancher.tools.xyz.com/v3/connect"
time="2019-04-03T18:01:52Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-04-03T18:01:52Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

**Comment by renperez** [comment]
i figured out the handshake issue. closing this issue.

**Comment by Sokwva** [comment]
so,how did you solved this problem?
