### ISSUE TITLE
"io.rancher.container.hostname_override" - ignore the flag when instance.name is longer than 64 chars

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1934]
Don't override hostname on the backend if instance.name is longer than 64 chars

**Comment by alena1108** [comment]
@vincent99 suggested we use following formula for resetting the name: ltrim(name,64-1-ceil(log(number))+"_"+number

**Comment by alena1108** [comment]
Prachi is fixing, her first bug fix, woo hoo!

**Comment by cjellick** [comment]
:+1:

**Comment by sangeethah** [comment]
Tested with server version - v0.37.0-rc1

Started a container with label - "io.rancher.container.hostname_override": "container_name" and the service name being - "test872302/testsangeetestsangeetestsangeetestsangeetestsangeetestsangee" ( > 64 chars).

I see the hostname being truncated to 64 chars.

In my case I also have domainName set to "abc.com" 


```
"domainName": "abc.com",
"entryPoint": null,
"environment": { },
"expose": null,
"externalId": "a3000ef353f1355a07aa052881945cde4c1a7441906735b1c51771da108c8f4d",
"extraHosts": null,
"firstRunning": null,
"healthCheck": null,
"healthState": null,
"hostname": "test872302_testsangeetestsangeetestsangeetestsangeetestsangeet_2",
"imageUuid": "docker:cattle/test-agent:v7",
"kind": "container",
"labels": {
"io.rancher.project.name": "test872302",
"io.rancher.service.deployment.unit": "b4efacbb-7dae-43db-8553-770942884fb5",
"io.rancher.service.launch.config": "io.rancher.service.primary.launch.config",
"io.rancher.project_service.name": "test872302/testsangeetestsangeetestsangeetestsangeetestsangeetestsangee",
"io.rancher.scheduler.affinity:container_label_soft": "io.rancher.service.deployment.unit=b4efacbb-7dae-43db-8553-770942884fb5",
"io.rancher.stack.name": "test872302",
"io.rancher.stack_service.name": "test872302/testsangeetestsangeetestsangeetestsangeetestsangeetestsangee",
"io.rancher.container.hostname_override": "container_name",
},
```

**Comment by sangeethah** [comment]
When I tested without the domain name , containers come up with successfully and the host_name is truncated to exactly 64 characters long (along with the instance index).

**Comment by vincent99** [comment]
This doesn't sound right... shouldn't the <= 64 char hostname be going into `sethostname()` and the domain into `setdomainname()`?  It sounds like we're doing `sethostname(hostname+domainName)`.

**Comment by prachidamle** [comment]
Yes looks like thats what is happening. I am not sure though what is right, I just added a fix to consider domainName in truncation as well. Check https://github.com/rancher/cattle/pull/861

**Comment by prachidamle** [comment]
The fix is merged to master via PR https://github.com/rancher/cattle/pull/861

**Comment by sangeethah** [comment]
Tested with build from master - sep 14

Started a container with label - "io.rancher.container.hostname_override": "container_name" and the service name being > 64 chars and domainName set to "abc.com"

I see the hostname being truncated to less than 64 chars , so that hostname+"."+domainName is 64 chars.

Containers stay up in "running" state.
