### ISSUE TITLE
[v2.2.1] Workloads associated to pipelines crash after X hours

### ISSUE THREAD

**Issue by pensiero** [rancher/rancher#19352]
**What kind of request is this (question/bug/enhancement/feature request):**
`bug`

**Steps to reproduce (least amount of steps as possible):**
I have 3 workloads which are associated with a pipeline. When the pipeline runs, everything is fine, the workloads are correctly deployed.

After X (not sure how many) hours, all the workloads crash.

- `.rancher-pipeline.yml`: https://gist.github.com/pensiero/be8725a3a5c922376806e208fb3350d8
- One of the deployment files: https://gist.github.com/pensiero/c682bef13a77b5cad11cab8cd911541f

**Result:**
![Screenshot 2019-04-03 at 10 24 59](https://user-images.githubusercontent.com/2010696/55464235-ef827500-55fa-11e9-931d-d4958b70a2a1.png)

![Screenshot 2019-04-03 at 10 26 50](https://user-images.githubusercontent.com/2010696/55464268-04f79f00-55fb-11e9-8814-c3388867e1bf.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.1`
- Installation option (single install/HA): `single install`

**Comment by loganhz** [comment]
The registry is down. So you cannot pull the images from the local registry. Can you check the log to see why it down? You can find it out in pipeline ns

**Comment by pensiero** [comment]
Ok, as soon as it happens again I’ll check the logs and report them here.

Thanks,
Oscar

**Comment by gitlawr** [comment]
According to the [docs](https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/pipelines/)

**Comment by gitlawr** [comment]
Feel free to reopen this if you have any question.

**Comment by pensiero** [comment]
Thanks @gitlawr, so what you are saying is that if a long-running workload uses an image which is not in a persistent volume, then if the workload restarts, we might not be able to access to that image.

So my question is: how come the workload restarted by itself? Is it normal that from time to time workloads restart?

Thank you

**Comment by gitlawr** [comment]
@pensiero In [kubernetes model](https://kubernetes.io/docs/concepts/workloads/pods/pod/), pods are considered to be relatively ephemeral (rather than durable) entities. They won’t survive scheduling failures, node failures, or other evictions, such as due to lack of resources, or in the case of node maintenance. 
I don't think pods would crash frequently in a stable environment, but yes it is normal(with my definition of "normal").

**Comment by pensiero** [comment]
Thank you
