### ISSUE TITLE
Cross-project networking

### ISSUE THREAD

**Issue by useltmann** [rancher/rancher#19351]
**What kind of request is this (question/bug/enhancement/feature request):** 
question

**Steps to reproduce (least amount of steps as possible):**
* create two projects
* create one workload in each project
* try to communicate from one workload to the other

**Result:**
network-traffic is blocked

**Other details that may be helpful:**
* Network-Provider: *Canal*
* network-traffic across namespaces in the same project works

Is there a way to enable cross-project networking? how is the network-isolation done? can it be customized with kubernetes' *[NetworkPolicies](https://kubernetes.io/docs/concepts/services-networking/network-policies/)*?

**Environment information**
- 
- single install

**Cluster information**
- Custom/On Premise
- metal
- Kubernetes version:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by rbq** [comment]
“In previous Rancher releases, Canal isolates project network communications with no option to disable it. If you are using any of these Rancher releases, be aware that using Canal prevents all communication between pods in different projects. As of v2.0.7, if you use Canal, you also have the option of using Project Network Isolation, which will enable or disable communication between pods in different projects.” ([source](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#rancher-ui))

**Comment by useltmann** [comment]
All right. Switching "Project Isolation" off helped. thanks.
