### ISSUE TITLE
Improve cluster dashboard nodes specs

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#19359]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Create custom cluster with one etcd, one controlplane and one worker, view cluster dashboard

<img width="1482" alt="Screen Shot 2019-04-03 at 15 43 58" src="https://user-images.githubusercontent.com/2620179/55483677-6170b380-5627-11e9-9c38-16f49a1af583.png">

In the same area (top), it shows 2 bars, the first one showing 3 nodes (1 etcd, 1 controlplane and 1 worker), and the bar below only shows the specs of the worker as we filter out unschedulable. This is not that clear from this view, one could argue that the second bar could even be removed as the same information is in the gauges and move Created to the first bar.

**Comment by davidnuzik** [comment]
Very closely related to https://github.com/rancher/rancher/issues/19896

Version: Master-head (6/24/19)
We essentially removed CPU, Memory, Nodes based on the issue I linked.

This is working as expected:
![image](https://user-images.githubusercontent.com/45179589/60197804-0b11ac00-97f5-11e9-8210-933c3f5a36cd.png)
