### ISSUE TITLE
CronJob cron setting is not visible without editing the job

### ISSUE THREAD

**Issue by rbkaspr** [rancher/rancher#19356]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Other details that may be helpful:**
CronJob cron spec (e.g. 0 8 * * *) is not visible anywhere when simply viewing the CronJob in the Rancher UI (either from the workload listing or just viewing the workload details). The information can only be found by editing the job within the Rancher UI or via kubectl (```kubectl get cronjobs```)

**Environment information**
- Rancher v2.2.0 (HA RKE deployment)
- Custom cluster (baremetal/on-premise)
- Docker version 18.09.3-CE
- Kubernetes version 1.13.4

**Comment by westlywright** [comment]
@loganhz if our workload has a cron job type we should swap out the scale info for the job info since scale is disabled in this case.

**Comment by davidnuzik** [comment]
Version: Master (4/23/19)

This now shows up under the Workload Details page and replaces the area we would normally see scale.

![image](https://user-images.githubusercontent.com/45179589/56617546-06523100-65d5-11e9-96dd-885e884433de.png)
