### ISSUE TITLE
Automate publishing Rancher images SHAs

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19366]
For every release, we include the list of images used by Rancher (rancher-images.txt) and the images SHAs (rancher-images-digests.txt). The rancher-images-digests generation and publishing should ideally be automated and done as a part of a Drone build.

**Comment by deniseschannon** [comment]
https://gist.github.com/alena1108/86321f7ec8d632d0f2025dad8472e8c9

**Comment by deniseschannon** [comment]
Closing in favor of this new issue: https://github.com/rancher/rancher/issues/30234
