### ISSUE TITLE
Backport: GDNS Entry-Broken links when user has access to GDNS entry that points to a MCAPP which has targets he does not have access to. 

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19369]
Backport: rancher/rancher#19174

**Comment by westlywright** [comment]
This was added as apart of https://github.com/rancher/ui/pull/2828

**Comment by davidnuzik** [comment]
**Replication Steps:**
N/A - already recently replicated in #19174 

**Validation Steps:**
v2.2.2-rc1 HA Setup

_Setup:_
Seup has 3 clusters.
Cluster1
Cluster2
Cluster3 - testuser2 is cluster owner and project member for "default" project.

Steps to reproduce the problem:
- As admin user, Create a MCAPP1 with targets from Cluster1/Default , Cluster2/Default .
- Add testuser2 as owner of MCAPP1.

- Create a GDNS entry pointing to MCAPP1 and add testuser2 as owner.

- Log in as testuser2.
- Add Cluster3/Default as another target to MCAPP1 (Upgrade the app)

- View GDNS entry

Now, we can see the projects we do not have access to in the UI. When you hover over these projects you just see the projectid and a message indicating you do not have permission.
