### ISSUE TITLE
405 When updating settings

### ISSUE THREAD

**Issue by rmebamds** [rancher/rancher#19367]
Rancher versions: 1.6.20 and 1.6.26
Go to your rancher server:8080/admin/settings

All attempts to change the Host Registration URL fail.  The UI doesn't complain, but if you look in the network tab the PUT results in a 405

{"id":"1bc3fbdd-32b8-42e8-920d-ecd8c32e32f9","type":"error","links":{},"status":405,"code":"Method not allowed","message":"Method not allowed","detail":null,"baseType":"error","actionLinks":{}}

We are completely down after a domain change on our rancher server

**Comment by superseb** [comment]
Method not allowed indicates no permission to do so, are you logged in as Admin user? Do you see the Admin tab when you open the Rancher UI?

**Comment by deniseschannon** [comment]
Even if you have the options to change, please be aware of the following issues: 

https://github.com/rancher/rancher/issues/14731

**Comment by rmebamds** [comment]
Yes, I absolutely have permissions.

**Comment by superseb** [comment]
Did you manage to change the settings, is this single install or HA?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
