### ISSUE TITLE
Load Balancing broken after redeploy

### ISSUE THREAD

**Issue by scndel** [rancher/rancher#19363]
Ingress not working after **redeploy** existing _Workload_ with existing _Load balancer_ ;
when trying to reach URL :
> 503 Service Temporarily Unavailable
> nginx/1.13.12

recreating Ingress after deletion is also not working : stuck "Initializing"

Rancher upgraded from 2.1.6 to 2.2.1 - single node
Docker 17.03.2-ce
Helm | v2.10.0-rancher10
Machine | v0.15.0-rancher6-1
Ubuntu 16.04.5

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.1` UI: `v2.2.19` |
|Route|`global-admin.clusters.index`|

**Comment by scndel** [comment]
Was probably similar to #19331. Load Balancing works fine with `v2.2.2`

**Comment by JustSomeHack** [comment]
This seems to be an issue again with 2.2.3, load balancing doesn't work with new ingress

**Comment by soumyalj** [comment]
Tested with v2.2.4-rc20. 
Created a workload and an ingress pointing to the workload. 
Verified that ingress is functional
Redeployed the workload through UI
The ingress was still functional pointing to the right set of pods.
