### ISSUE TITLE
Error while trying to create a cluster with AWS region 'cn-northwest-1a'

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19379]
**What kind of request is this:** bug

**Steps to reproduce:**
1. Create an AWS node template with region `cn-northwest-1a` and provide valid cloud credentials.
2. Create a cluster using this node template.

**Expected Result:**
Cluster is created successfully

**Actual Result:**
Cluster creation fails. Error `Error with pre-create check: "RequestError: send request failed\ncaused by: Post https://ec2.cn-northwest-1.amazonaws.com/: dial tcp: lookup ec2.cn-northwest-1.amazonaws.com on x.x.x.x.: no such host"; Timeout waiting for ssh key` is seen.

<img width="1492" alt="Screen Shot 2019-04-03 at 4 16 29 PM" src="https://user-images.githubusercontent.com/26032343/55519294-12794d00-562c-11e9-91f2-76be2c57e65c.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.2.2-rc1 and v2.1.8
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS hosted

**Comment by gitlawr** [comment]
The Vendored version of AWS sdk in docker machine is v1.4.10, whilst the proper config for this region is added in [v1.12.50](https://github.com/aws/aws-sdk-go/commit/03f37be7b3c2cec3a839ff74dea774c63819d45d#diff-fe3b36d57dc4378fa7b13c85492f4119R1712).

**Comment by kingsd041** [comment]
Version: master master-head (8/28/19) 
Confirmed fix. Use `master-head` to successfully create a cluster in 'cn-northwest-1' region

**Comment by linbingdouzhe** [comment]
> The Vendored version of AWS sdk in docker machine is v1.4.10, whilst the proper config for this region is added in [v1.12.50](https://github.com/aws/aws-sdk-go/commit/03f37be7b3c2cec3a839ff74dea774c63819d45d#diff-fe3b36d57dc4378fa7b13c85492f4119R1712).

my docker version is 1.13.1 . however i can't launch ec2 cluster on cn-northwest-1a, can you help me ?

**Comment by loganhz** [comment]
It will be fixed in 2.3.0.

**Comment by linbingdouzhe** [comment]
> It will be fixed in 2.3.0.

Could you please tell me that when the 2.3.0 version will be released?

**Comment by linbingdouzhe** [comment]
> It will be fixed in 2.3.0.

Please ask that when the 2.3.0 version will be released?
