### ISSUE TITLE
"CLOUDFLARE::http://rancher.com:8080/cdn-cgi/scripts/cf.common" could not be found or was destroyed.

### ISSUE THREAD

**Issue by etcook** [rancher/rancher#1937]
I'm getting the following error when attempting to use my server installation.

Error
Property set failed: object in path 
"CLOUDFLARE::http://rancher.com:8080/cdn-cgi/scripts/cf.common" could not be found or was destroyed.

It gives me the option to reload or log out - neither of which resolves the issue.

**Comment by deniseschannon** [comment]
At what point in the installation are you getting this error? Also, what kind of Rancher setup do you have? 

And what version are you installing?

**Comment by etcook** [comment]
Not during installation. It just happens after a day or so of it working.
I'm using the latest version, and have replicated the behavior thrice.




On Tue, Sep 8, 2015 at 11:05 AM -0700, "Denise" <notifications@github.com> wrote:












At what point in the installation are you getting this error? Also, what kind of Rancher setup do you have? 



And what version are you installing?

**Comment by vincent99** [comment]
CloudFlare is the CDN in front of the JS/CSS/fonts/images for the UI, so I imagine it broke at some point.  That URL doesn't really make a whole lot of sense though.

**Comment by etcook** [comment]
Well, this is a recurring issue on multiple fresh servers, so is there anything I can do to help troubleshoot.

**Comment by etcook** [comment]
Is there anything I can do to help troubleshoot this? It's a recurring issue after about a day of every fresh install.

**Comment by vincent99** [comment]
You can try network dumping or making the same requests with curl and such.. but the next release should have everything packaged into the app and no longer talk to the internet for the UI anyway.

**Comment by etcook** [comment]
I don't believe this to be a client side issue. I've tried this with multiple workstations and browsers to no avail.

**Comment by vincent99** [comment]
The latest release doesn't talk to anything that comes from cloudflare any more, so I presume this won't happen anymore even though we don't know what caused it @etcook.
