### ISSUE TITLE
On Edit node template, incorrect cloud credential key is displayed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19378]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Edit an existing Node template.
2. Incorrect cloud credential is displayed as the tagged credential.

**Note:** The first one from the cloud credentials list (sorted alphabetically) is always displayed.

On Edit incorrect cloud credential tagged displayed (do-1):
<img width="1220" alt="Screen Shot 2019-04-03 at 3 37 35 PM" src="https://user-images.githubusercontent.com/26032343/55517793-80bb1100-5626-11e9-9b42-072b302e9c69.png">

But View in API - gives the actual cloud credential(do-2) tagged:
<img width="353" alt="Screen Shot 2019-04-03 at 3 38 07 PM" src="https://user-images.githubusercontent.com/26032343/55517813-903a5a00-5626-11e9-92d2-e0d34b3a2eb8.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version: `rancher:v2.2.2-rc1`

**Comment by alena1108** [comment]
Moving out of 2.2.2 as it's not a very common situation for the same user to have more than one cloud credential per cloud provider.

**Comment by davidnuzik** [comment]
Version: Master (4/15/19)

Now the cloud credential associated with the template is chosen from the "Cloud Credentials" drop-down when you choose to edit a node template.

In this picture below you see that my "amazon" cloud credential is chosen even though I have an "aaa" cloud credential as well (which would alphabetically show up as picked when edit the template before the fix).

![image](https://user-images.githubusercontent.com/45179589/56163420-1f2e6700-5f83-11e9-8fd7-acac2d217d28.png)
![image](https://user-images.githubusercontent.com/45179589/56163434-25244800-5f83-11e9-987d-5bdb36d5c9c4.png)
