### ISSUE TITLE
A previous error message not cleared on the UI when another error message is displayed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19377]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an AWS node template. 
2. A cloud credential key is available on the UI. Change the Region to one which is not authorized for the cloud creds.
3. Error `UnauthorizedOperation: You are not authorized to perform this operation.` is displayed on the UI.
4. Click on `Add New` could credential. Enter invalid Access key/Secret Key.

**Expected Result:**
Only error `401 AuthFailure: There was a problem validating your keys. Enter valid credentials and try agian.` be displayed on the UI.

**Actual Result:**
Both error messages are displayed.
<img width="1215" alt="Screen Shot 2019-04-03 at 2 02 31 PM" src="https://user-images.githubusercontent.com/26032343/55512885-24052980-5619-11e9-8924-2631cbdfcb5a.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.2.2-rc1

**Comment by westlywright** [comment]
This ticket is available in to test in master

**Comment by davidnuzik** [comment]
Version: Master (4/15/19)

I carefully followed the steps to reproduce and now only one error is shown at a time. The previous error is very quickly blanked out before showing the next error (the 401 AuthFailure) error due to invalid credentials replaces the previous error. This is now working as expected.
