### ISSUE TITLE
Cannot create an Amazon EC2 cluster on ARM64 via node template

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#19384]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

-  Launching ARM64 instances in AWS, currently only supports the [Amazon EC2 A1](https://aws.amazon.com/ec2/instance-types/a1/) type, which is not supported in the rancher node template
- https://releases.rancher.com/install-docker/18.09.sh  install script does not support ARM64

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher/rancher:2.2.1
- Installation option (single install/HA):
single install

**Comment by superseb** [comment]
install-docker is tracked in https://github.com/rancher/rancher/issues/19161
