### ISSUE TITLE
Security networking

### ISSUE THREAD

**Issue by RRadziejewski** [rancher/rancher#19386]
Hello i am struggling with a security problem.
How to ensure that every deployment in namespace can resolve itself by name.
But it can't be done from other namespaces like that curl blablabla.chartone-wnhct.svc.cluster.local with FQDN? Because now i need to have all ports openned on some deployment but it may be dangerous when it is accessed from other namespaces.

**Comment by Razikus** [comment]
Hi 
The main problem is that if you want to use ClusterIP Service discovery it will expose this port to entire Cluster
And we don't want to have port exposed to entire cluster - just to the namespace
Is there any option to namespace isolation besides project isolation?

If we will use functionality of Rancher Service Discovery to Add Record as resolving to "One or more workloads" - it will expose all ports to the entire cluster, i believe that's security issue if you have more apps within it

**Comment by RRadziejewski** [comment]
Any idea or thoughts about it ?

**Comment by vincent99** [comment]
There is no "just this namespace" checkbox that you're missing.  There's project network isolation (in the extreme case every project can have only one namespace), or you can manage your own network policies in k8s directly.

**Comment by deniseschannon** [comment]
If you have more questions, please open a new issu.
