### ISSUE TITLE
[UI] CPU/Memory Reserved percentages not updating when switching between clusters

### ISSUE THREAD

**Issue by nugget** [rancher/rancher#19387]
**What happened**:

When moving between two clusters, the percentage of CPU and Memory Reserved displays do not update and retain the value from the initial cluster.  I've observed this with clusters that have Grafana/Prometheus monitoring enabled.

Here is a [demonstration screencap](https://macnugget.org/crud/rancher-stale-display.mov) (QuickTime movie, 5.4MB)

**What you expected to happen**:

When I switch to a different cluster the reserved CPU and Memory percentage displays should reflect the values for that cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Using a Rancher install with multiple clusters, switch back and forth between two clusters that have monitoring enabled.  You should observe that the **n%** displays for CPU and Memory do not update when changing between clusters.

Changing to a cluster that does not have monitoring enabled seems to "clear" the values.

**Anything else we need to know?**:

Rancher is awesome.  Thanks for all the hard work.

**Environment**:
- Rancher version: v2.2.1
- Kubernetes version (use `kubectl version`): v1.13.5
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g: `cat /etc/os-release`): RancherOS 1.5.1
- Install tools: RKE install of Rancher HA cluster, then working clusters via Amazon EC2 provisioning

**Comment by tfiduccia** [comment]
Version - 2.2.x master
Able to reproduce this on latest master version.  CPU Reserved & Memory Reserved don't change unless I do a hard refresh of the browser and will always show % of the first cluster you were in.
![image](https://user-images.githubusercontent.com/11514927/55921717-d5c0cf00-5bb2-11e9-9507-8ecd2b8f2e19.png)

**Comment by davidnuzik** [comment]
I too have reproduced in latest master 4/11/19. I observe what is shown in the video but yes for me I only saw it with clusters that had monitoring enabled.

**Comment by davidnuzik** [comment]
Version: Master (4/15/19)

I am no longer able to reproduce the issue in latest master. When I switch between clusters all the percentages (used/reserved) update appropriately. When we reproduced this we only saw it affecting clusters with monitoring ON but I checked both and do not see the issue in either case any longer.
