### ISSUE TITLE
Node template - Same error seen multiple times on the UI while creating an AWS node template

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19390]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a Node Template - AWS type. 
2. Enter a new cloud credential - Region, Access Key and Secret Key. 
3. Click on Configure. You will be prompted to select a VPC. Do not select a VPC/Subnet.
4. Click on 'Next'.

**Expected Result:**
Error `Select a VPC or Subnet` be displayed.

**Actual Result:**
Error `Select a VPC or Subnet` is displayed on the UI two times.

**Note:** Multiple error messages are displayed when no name is given to the Node Template and you click on Create.
<img width="1311" alt="Screen Shot 2019-04-04 at 9 57 42 AM" src="https://user-images.githubusercontent.com/26032343/55576530-6a649200-56c6-11e9-807e-0160cbfdb5a9.png">

<img width="1346" alt="Screen Shot 2019-04-04 at 9 57 21 AM" src="https://user-images.githubusercontent.com/26032343/55576471-4608b580-56c6-11e9-8bc0-bf0976b4fb00.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.2.2-rc1 and rancher:master

**Comment by davidnuzik** [comment]
Version: Master (4/15/19) ImageID: 0d755e769e77

Confirmed that in both scenarios (don't select VPC and don't enter a Name for the template) that the error for each is only displayed once now, at the bottom of the modal, as expected.
