### ISSUE TITLE
cattle-cluster-agent to control plane node leaking sockets

### ISSUE THREAD

**Issue by ts-mini** [rancher/rancher#19391]
**What kind of request is this (question/bug/enhancement/feature request):*Bug*

**Steps to reproduce (least amount of steps as possible):
Setup 3 node RKE cluster (minimum i tested with)
Have version >2.2.0 rancher master
Have latest helm/tiller installed
Setup kube config to point to cluster
`while true; do helm version; done`

**Result:**
The underlying host which is running the cattle-cluster-agent pod will open connections to one of the api servers (I've found it to be whichever is first in the 'upstream' of the nginx-proxy that rancher-tools makes).  You can see this by either:
`ss -a | grep 6443`
or `netstat -antp | grep 6443`

Watch this over time, this number of sockets will grow until net.core.somaxconn is hit on the api server, then the cluster will be 'unavailable'.  

Restarting cattle-cluster-agent (deleting the pod and letting kube recreate it) returns the socket and temporarily fixes the issue.

**Other details that may be helpful:**
This started in 2.2.0.  I've not tested on other cluster types that we have (GKE) but I have tested on two RKE clusters (large and small).  

Noticed it because the concourse helm resource continually calls `helm history $vars` to keep its resource about the deployed helm chart updated.  

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud EC2 and VM
- Kubernetes version (use `kubectl version`): 1.13.5

**Comment by ts-mini** [comment]
Here is a screenshot from node_exporter data of the last 24 hours.  You can see me manually 'fixing' it to keep the cluster alive. Over the night I scaled our concourse workers down to 0 so it didn't poll with the aforementioned "helm history" spam.

The last hump is me running the above `while true; do helm version; done` to ensure it creates the same issue (albeit at a slower rate).  
[
![Screenshot from 2019-04-04 11-11-58](https://user-images.githubusercontent.com/4910513/55574858-aef22c80-56ca-11e9-83a4-67c0a811bdf0.png)
](url)

**Comment by nugget** [comment]
Thanks for figuring this out, I've been in the middle of diagnosing this exact problem on a v2.2.1 setup this morning and I've been tearing my hair out.  Same exact behavior on an Amazon EC2 provisioned 1.13.5 cluster.  Killing `cattle-cluster-agent` immediately resolves the issue here as well.

**Comment by ts-mini** [comment]
Word of advice @nugget, do NOT delete the deployment of cattle-cluster-agent.  Just the pod.  You will be in a bad situation if it does not come back....

**Comment by nugget** [comment]
Yeah, thanks, I got that.  :)

**Comment by ts-mini** [comment]
<3

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.2.2-rc10, see this comment for details https://github.com/rancher/rancher/issues/19518#issuecomment-482375323

The bug fix is validated with Rancher: master 4fd2548

using the method from this comment https://github.com/rancher/rancher/issues/19518#issuecomment-482369816
> Global > [Cluster Name]> System (project)
> Exec inside the cattle-cluster-agent container.
> 
> `netstat -antp | grep 6443 | wc -l`
> The count shouldn't keep growing as you execute either `kubectl` or `helm` commands against the cluster.

Result:

- running the loop `while true; do kubectl version; done`  in the kubectl command line does not increase the count
- deploying the app `wordpress` and `redis` does not increase the count
- after running automation tests on an RKE cluster the total count is 71

**Comment by ts-mini** [comment]
Deployed version v2.2.2 3.5 hours ago and immediately turned my concourse workers back on.  Issue is resolved completely.  Thanks rancher team and @leodotcloud for crushing it as always :).
