### ISSUE TITLE
add link to sizing guide documention for monitoring

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19392]
On the page for enabling monitoring, we should link out to https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/#resource-consumption

so that people enabling know there is a sizing recommendation

**Comment by cjellick** [comment]
with this, we should also improve the docs: https://github.com/rancher/docs/issues/1363

**Comment by cjellick** [comment]
from @vincent99:
 has to be hidden if `ui-pl` setting != `rancher`

**Comment by davidnuzik** [comment]
Version: Master (4/15/19) ImageID: 0d755e769e77

Confirmed issue. Now, when you first try to enable cluster monitoring, you will see a message at the top suggesting to review the docs. This properly links to https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/#resource-consumption

If, in the settings, you set the ui-pl to non-default (not "rancher") then the message does NOT show up as expected (see the comment above, https://github.com/rancher/rancher/issues/19392#issuecomment-479986997).

Here is a screenshot of what this looks like (assuming ui-pl == rancher)
![image](https://user-images.githubusercontent.com/45179589/56155030-cbb21e00-5f6e-11e9-9c8d-aa5fb52cdbb8.png)
