### ISSUE TITLE
Node Template - 'Location' on the UI does not get updated when you edit and save an AWS node template

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19396]
**What kind of request is this:** bug

**Steps to reproduce:**
1. Edit an existing node template (AWS).
2. Choose another region and save the node template.

**Expected Result:**
The selected `Region` should be displayed on the UI under _Location_ for the particular node template.

**Actual Result:**
_Location_, on the UI, does not get updated with the selected `Region`. User has to refresh the page for the change in region to reflect on the UI.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.2.2-rc1 and rancher:master(04/04/2019)

**Comment by alena1108** [comment]
@westlywright let me know if it's not a UI issue, and I'll reassign.

**Comment by davidnuzik** [comment]
Version: Master (4/11/19)

I confirmed this is now working as expected. When I change the region for my aws template this is updated in the UI now including other locations in the same region (us-west-2a, us-west-2b, etc)

I also tried with a digitalocean template and the location will update for that template as well.
