### ISSUE TITLE
rancher-metadata addition host labels

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#1939]
Hey there,
would be nice to get host labels within rancher-metadata.

**Comment by Kelindar** [comment]
From the documentation, it seems like you can retrieve host labels: http://docs.rancher.com/rancher/metadata-service/. I haven't tried it yet myself tho.

```
labels : List of Host Labels. Format for labels is key:value.
```

**Comment by fentas** [comment]
Hm. Overlooked it.. :)
I guess this figures this. Thanks for pointing this out.
