### ISSUE TITLE
UI: EKS 1.12 k8s version is not shown in dropdown and when upgrade from v2.1.8 this causes an issue when attempt to update k8s

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19406]
Version: v2.2.0
Version: v2.2.2-rc2

Version: v2.1.8 -> Upgrade to v2.2.2-rc2 also has an issue

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Note, I describe a couple of issues but I believe this is likely all the same issue -- the issue being that the UI does not show us the 1.12 k8s version for EKS. If I am mistaken here, please ask me to create another issue, if necessary.

v2.2.x issue:
- UI does not show k8s version 1.12 in the UI and this is the latest available on AWS. We should show this as an option.

v2.1.8 -> v2.2.x (v2.2.2-rc2 in my case) upgrade
- Create an EKS cluster in v2.1.8 note that it auto picks the latest k8s version for you because we do not specify one in the UI (there is no option to do so). (Check EKS console). This causes us to have a 1.12 k8s version EKS cluster. 

- Upgrade to v2.2.any
- Edit the EKS cluster in the UI it will show that the current version is 1.10 (this is not true) so now pick 1.11 (so we can "upgrade" to this). Save the changes so the cluster tries to upgrade k8s.

**Result:**
When you try to upgrade k8s version from the claimed "1.10" version the UI shows to "1.11" you will get this message:
`InvalidParameterException: Unsupported Kubernetes minor version update from 1.12 to 1.11 status code: 400, request id: 2e7241ed-572f-11e9-8814-31c2af29b314`
This is because the version indeed actually is 1.12 since that was picked for us automatically in v2.1.8 rancher before we upgraded.

**Other details that may be helpful:**
This screenshot shows that in v2.x we only have an option for v1.11 but we should also see version 1.12 now.
![image](https://user-images.githubusercontent.com/45179589/55595595-82093e00-56f9-11e9-8863-8237707522ea.png)

**Comment by westlywright** [comment]
Currently the Amazon eks api doesn't support fetching the versions for k8s so we still have to manually update these lists.

**Comment by davidnuzik** [comment]
Refer to #19458 for upgrade test scenario.

**Comment by davidnuzik** [comment]
Version: Master (4/11/19) ImageID: 0d755e769e77

Confirmed fixed. You can now pick v1.12 K8s when creating an EKS cluster. It is also the default picked.
![image](https://user-images.githubusercontent.com/45179589/55985154-0efd4b80-5c54-11e9-92a4-6e3134d22fc3.png)

You can also upgrade from v1.11 k8s to v1.12 k8s without any issues. HTTP/API appears correct.
When comparing against EKS console everything appeared correct including upgrade of k8s.

I noticed that it takes a while for the updated cluster k8s version to display and we're not pulling it from the config in the API. This is addressed here: #19561
Note: workers are not upgraded - this is normal; Amazon requires a manual process to update k8s components on the worker nodes.
