### ISSUE TITLE
UI: When go to Cluster Monitoring Configuration, enable but don't save UI shows is Enabled

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19402]
Version: v2.2.2-rc2
Version: v2.2.0

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster
- Go to (Cluster) -> Tools menu -> Monitoring
- Click the Enable button

**Result:**
The Enable button turns green and becomes "Enabled" even though we have not yet actually saved and thus monitoring is not actually enabled yet.
![Screen Shot 2019-04-04 at 2 12 28 PM](https://user-images.githubusercontent.com/45179589/55589355-e241b500-56e4-11e9-8d1b-cb4b411266ce.png)

I can see that there is a message that it is not enabled yet, but we really should not have this button turn green and say "Enabled" until we have actually saved and monitoring is turned on (or in progress of deploying).

**Comment by deniseschannon** [comment]
Is the process of enabling monitoring changing at all? 

Are all the areas that we use the enable/disable similar, where you need to click on a "save" button? We should keep the way we use this button type the same. 

@loganhz @westlywright

**Comment by davidnuzik** [comment]
Version: Master (4/15/19)
The UI has been tweaked a bit on the Cluster Monitoring Configuration page so that it is now more in alignment with how the UI looks in similar areas. The Disable/Enabled buttons at the top-right have been removed. Now when you set up monitoring for the first time you will see this button to enable it at the bottom of the page:
![image](https://user-images.githubusercontent.com/45179589/56158021-cad0ba80-5f75-11e9-89b3-669c6a0e1e01.png)

And once it is enabled it changes to a normal "Save" button.

When cluster is enabled and fully ready (only when it is fully provisioned) you will now see a red "Disable Monitoring" button at the top-right of the page.
![image](https://user-images.githubusercontent.com/45179589/56158089-fa7fc280-5f75-11e9-8e26-b61a1c4c7015.png)
