### ISSUE TITLE
Rancher HA with amazon ELB very slow eith websocker connections

### ISSUE THREAD

**Issue by vic-marroquin** [rancher/rancher#19409]
**What kind of request is this (question):**

I used this guide to set up an HA rancher server: https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#multi-nodes

I made it with 3 ec2 instances (m5a.xlarge=4cores and 16GB of RAM) a classic ELB (80 TCP port to 8080 and 443 HTTPS to 8080) and RDS database, when I tried to see container's logs or try to connect to container's console the websocket response very slow (6 to 10 seconds) that I missing someting?, because in the single rancher server instance the websocket runs very fast.

**Environment information**
- Rancher version Server: 1.6.26
- Installation option (HA):

<!--

- Docker version (use `docker version`):

```
Docker version 18.09.2
```

**Comment by phillycheeze** [comment]
Did you ever figure this out? I run a single node server and it also really slow. Sometimes taking 20 seconds. Also behind an ELB in AWS.
