### ISSUE TITLE
UI: Cluster monitoring resource check needs improvements, can enable monitoring if have less than 750MiB in each schedulable node

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19403]
Version: v2.2.2-rc2
Related: #19405 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a GKE cluster with 3 nodes, each of machineType `n1-highcpu-2 (2 vCPUs, 1.8 GB RAM)`
- ALTERNATIVE: Create a DO cluster with 3 nodes each of type 1vCPU 1GB RAM.
- Enable monitoring with all the default settings

**Result:**
The UI javascript check for having enough resources succeeds and allows you to enable monitoring. However, we actually do not have at least 750MiB available for each node. My guess is we are summing up MiB available across all nodes.

Here is what I see when I check metrics via kubectl before enabling cluster monitoring:
![Screen Shot 2019-04-04 at 2 30 53 PM](https://user-images.githubusercontent.com/45179589/55590210-1918ca80-56e7-11e9-935a-ee620ee92b0f.png)

If I enable monitoring I get this issue in prometheus-cluster-monitoring workload:
![image](https://user-images.githubusercontent.com/45179589/55590267-3d74a700-56e7-11e9-8d6d-8272951646e7.png)

**Other details that may be helpful:**
I'm not an expert but my guess is the problem might be somewhere around here:
https://github.com/loganhz/ui/blob/6d64593ed0a87d26a5d139c3b352ea1a2214e54f/lib/monitoring/addon/components/enable-monitoring/component.js#L149

I think? we are getting sum of MiB memory available for all nodes rather than doing a check to ensure at least 1 schedulable node has at least the amount we are requesting on the cluster monitoring configuration page for prometheus.

**Environment information**
v2.2.2-rc2 rancher on HA setup

**Comment by jiaqiluo** [comment]
The bugfix is validated with Rancher: master 4fd2548
The same steps as this comment: https://github.com/rancher/rancher/issues/19429#issuecomment-481464944

Result: we will not be able to enable cluster/project monitoring if there is no sufficient resources in the cluster.
