### ISSUE TITLE
Improve or Remove Spot Instance Support for Node Templates [AWS]

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#19400]
**What kind of request is this (question/bug/enhancement/feature request):** bug/enhancement

**Steps to reproduce (least amount of steps as possible):**

1. Launch a spot instance using a node template and node pool
2. Wait for the spot instance to be reaped by AWS

**Result:**

Watch Rancher sit there with "Kubelet stopped posting node status." and that node just remains dead.

**Other useful information:**

I think that spot instances are great, but if Rancher is going to support them in EC2 node templates the UX has to be improved otherwise I would recommend removing the option as it can cause at a minimum confusion, if not problems.

I would love to see the node-template system be able to subscribe to AWS spot instance notifications so that when a node gets notified it's being taken down, the node template system simply tries to bring a new one up in it's place, or cleans out the old node and/or provides an alert mechanism.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.7
- Installation option (single install/HA): HA

**Comment by mohag** [comment]
[Spot fleet](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html) support seems like the ideal solution - it also allows multiple instance types to be requested...

The quick fix for this might be to check if the instance still exists, and if not, put in another spot request for a replacement instance (deleting the broken node currently seems to result in attempting to replace it...)

**Comment by ekristen** [comment]
Not sure if spot fleet would work since it's not supported by Docker Machine.

For me a simple fix to this would be to listen to AWS for when spot instances are scheduled to go down, have them automatically cordon, then deleted when the final AWS termination message comes across and when that happens, the node controller should automatically spin a new one back up.

**Comment by ajfriesen** [comment]
Is this planned in some feature release?
I would like to run non production cluster in spot instances for cost saving but without the auto healing approach it is not a feasible solution.

**Comment by alex-stout** [comment]
Bumping this as well. Without auto healing the option is basically useless.

**Comment by ekristen** [comment]
The new auto heal feature (I don’t recall what it is actually called) works pretty well on the node pools for this. I have mine set to 5 minutes and it will delete and recreate if the node is unresponsive. I haven’t had to manually add or remove nodes since my upgrade to 2.3.2.

**Comment by ajfriesen** [comment]
@alex-stout 
Please check out the new release.
It is already working.
