### ISSUE TITLE
cattle-node-agent trying to connect to removed node and failing 

### ISSUE THREAD

**Issue by paulmorabito** [rancher/rancher#19411]
Hi,

I'm using Rancher 2.2.0 and Kubernetes 1.13.4 on bare metal (Debian 9.8 nodes).

I created my cluster via rke. I removed the node from the rancher-cluster.yml and re-ran "rke up --config rancher-cluster.yml". There were no errors reported and the cluster worked fine afterwards.

I then added my new node and ran the same command above.

This time, everything seems to be working except that cattle-cluster-agent and cattle-node-agent are constantly failing. The error received is:

"ERROR: https://192.168.1.52:30443/ping is not accessible (Failed to connect to 192.168.1.52 port 30443: Connection refused)" 

This is the node that was previously removed. Is there anything I can do to correct this?

Thanks,

**Comment by superseb** [comment]
Did you follow https://rancher.com/docs/rancher/v2.x/en/installation/ha/? This includes creating a load balancer and a DNS name for Rancher to be configured as `server-url` that is used to connect agents to Rancher. If this is configured to an IP which is then not valid anymore, it won't work (even changing `server-url` at the moment won't solve this, as described in https://github.com/rancher/rancher/issues/14731)

**Comment by paulmorabito** [comment]
Yes I did follow the HA install and yes the server url was the removed
node. So, there is nothing I can do? Do I need to delete the whole cluster
and start again?

**Comment by paulmorabito** [comment]
can I re-add a node with the same IP address? Would that work?

**Comment by superseb** [comment]
It is to be expected when you point something to an IP address and then change/remove that IP address, connections will break. The instructions are to create a load balancer and a DNS name to make it highly available. Any workaround (making the IP available again, re-creating the sources like described in the linked issue) will only postpone a possible failure, even when using fail-over with that IP you will be bound to that IP if you configure it somewhere.

Let me know if something is unclear.

**Comment by paulmorabito** [comment]
I understand. I'm relatively new to this so am learning.

After reading into this a lot more, I follow the HA setup and use a domain/host for the server URL. Do I need to configure this to point to which IP? Any IP in the cluster?

After the HA setup is complete, for installing other applications/deployments - i should create a new cluster from within Rancher? So I then need 3 more nodes for this or can I use the same three nodes? If it's setup within Rancher, how is state maintained?

What happens if I want to use a different ingress in the future such as traefik (for either rancher or a new cluster?) If I delay the ingress in the yml and deploy traefik this is ok?
