### ISSUE TITLE
Error with pre-create check: "network 'VM Network' not found"; Timeout waiting for ssh key

### ISSUE THREAD

**Issue by nutexan04** [rancher/rancher#19418]
**What kind of request is this (question/bug/enhancement/feature request):**
This is a bug in deploying clusters in vSphere 6.0

**Steps to reproduce (least amount of steps as possible):**
Create node template with required fields.
Deploy cluster and node never provisions. It waits and retries the pre-check above,

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.18
Rancher HA deployment

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): VMWare 6.0
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 2cpu, 4GB RAM, 20GB
- Kubernetes version (use `kubectl version`):

> kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
> VMware
```
(paste the output here)
```

- Docker version (use `docker version`):

```
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-91.git07f3374.el7.x86_64
 Go version:      go1.10.3
 Git commit:      07f3374/1.13.1
 Built:           Fri Feb  8 20:24:43 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-91.git07f3374.el7.x86_64
 Go version:      go1.10.3
 Git commit:      07f3374/1.13.1
 Built:           Fri Feb  8 20:24:43 2019
 OS/Arch:         linux/amd64
 Experimental:    false

```

**Comment by mouradk78** [comment]
Experiencing similar error any solution for this?

**Comment by nRachid** [comment]
any updates?
