### ISSUE TITLE
Backport: EKS 1.12 k8s version is not shown in dropdown and when upgrade from v2.1.8 this causes an issue when attempt to update k8s

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19414]
Backport: rancher/rancher#19406

**Comment by alena1108** [comment]
Can be tested with `rancher/rancher:v2.2.0-rc4`

**Comment by tfiduccia** [comment]
@davidnuzik - tested this - findings:
The first issue where: "UI does not show k8s version 1.12 in the UI and this is the latest available on AWS. We should show this as an option." - This is fixed.


The second issue where you upgrade from 2.1.8 to 2.2.2-rc4, that is not fixed.  The kubernetes version is saying 1.10.  And it is reflecting what is in the API.  So I'm going to assume this is a backend issue and needs a new bug.

**Comment by sangeethah** [comment]
API issue tracked in - https://github.com/rancher/rancher/issues/19458

**Comment by davidnuzik** [comment]
Version: v2.2.2-rc7
I validated the first issue where: "UI does not show k8s version 1.12 in the UI and this is the latest available on AWS. We should show this as an option." to double-check with rc7. 

The second issue with v2.1.8 upgrade to v2.2.2-rc* is tracked in #19458
