### ISSUE TITLE
Backport: Cluster Monitoring - Setting page does not sync the value from the monitoring app

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19427]
backport: https://github.com/rancher/rancher/issues/19422

**Comment by loganhz** [comment]
It shows 50MB memory limit and 200m CPU limit for monitoring enabled in 2.2.1

**Comment by alena1108** [comment]
Can be tested with `rancher/rancher:v2.2.0-rc4`

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher v.2.2.2-rc5 
The steps are the same as https://github.com/rancher/rancher/issues/19422#issuecomment-480424082:

- run Rancher v2.2.1
- add a cluster
- enable cluster monitoring
- upgrade Rancher to v2.2.2-rc2
- go to the cluster monitoring setting page

Result:
- notice that the monitoring page show two more variables `Node Exporter CPU Limit` and `Node Exporter Memory Limit` which are not showed in v2.2.1
- the value of `Node Exporter Memory Limit` is 50
