### ISSUE TITLE
etcd snapshots stuck in activating state for RHEL 7.6 nodes with native docker and selinux enabled

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#19421]
Rancher version: v2.2.2-rc2 
Nodes: RHEL 7.6 Native docker(1.13) and Selinux enabled

Steps

1. Create a 3 node custom cluster using RHEL 7.6 nodes 
2. Create workload and create a snapshot. 
Snapshot is stuck in "Activating" state

Logs below:
```
2019/04/05 20:54:57 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10002
2019/04/05 20:54:57 [INFO] Starting saving snapshot on etcd hosts
2019/04/05 20:54:57 [INFO] [dialer] Setup tunnel for host [abcd]
2019/04/05 20:54:57 [INFO] [dialer] Setup tunnel for host [efgh]
2019/04/05 20:54:57 [INFO] [dialer] Setup tunnel for host [hijk]
2019/04/05 20:54:58 [INFO] [etcd] Saving snapshot [c-2d6fs-ml-q86r6] on host [abcd]
2019/04/05 20:54:59 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host [efgh]
2019/04/05 20:55:49 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/04/05 20:55:49 [WARNING] Error waiting for container [etcd-snapshot-once] on host [abcd]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```
![Screen Shot 2019-04-05 at 2 07 02 PM](https://user-images.githubusercontent.com/18536626/55656544-221f9f80-57ac-11e9-8fbc-488cc58757c4.png)

**Comment by alena1108** [comment]
Can be tested with `rancher/rancher:v2.2.0-rc4`

**Comment by intonet** [comment]
I have the same problem and the same looking logs but with ubuntu 16.04 nodes. Snapshot working ok on cluster with one master.

**Comment by soumyalj** [comment]
Tested with rancher server v2.2.2-rc4. 
1. Create a 3 node custom cluster using RHEL 7.6 nodes with native docker and selinux enabled. 
2. Create workload and create a snapshot.

Snapshot creation succeeded . Restore was  also successful.
