### ISSUE TITLE
Backport: UI: Cluster monitoring resource check needs improvements, can enable monitoring if have less than 750MiB in each schedulable node

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19429]
https://github.com/rancher/rancher/issues/19403

**Comment by alena1108** [comment]
Can be tested with `rancher/rancher:v2.2.0-rc4`

**Comment by davidnuzik** [comment]
v2.2.2-rc7
Confirmed issue. I did the following:

- Create a DO cluster with 3 nodes each of type 1vCPU 1GB RAM.
- Confirm via `kubectl top nodes` each node has less than 750MiB available.
- Try to enable monitoring the enhanced JS check now checks each node and will warn you in the UI.
(Note you may need to decrease CPU reservation requirements to see the message with this setup)

Here is an example of what we see in the UI:
![image](https://user-images.githubusercontent.com/45179589/55839426-ab9cdd80-5adc-11e9-8990-e500b2fbcfe9.png)

I also tested again but with a bigger cluster such that each node had more than 750MiB available, but I reserved more memory via some workloads so each now "artificially" (for lack of a better word) had less than 750MiB available. This also worked as expected. The JS checks seem to work each time I visit the configure monitoring page.

@loganhz does the screenshot look correct? We require 1810MB of memory by default with 3 node cluster? I just wanted to double-check.
