### ISSUE TITLE
images outside of the rancher namespace in rancher-images for v2.2.2-rc2

### ISSUE THREAD

**Issue by lonewulf** [rancher/rancher#19435]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug?

**Steps to reproduce (least amount of steps as possible):**

Some images seem to be outside of the rancher namespace:

coredns/coredns:1.2.2
coredns/coredns:1.2.6
minio/minio:RELEASE.2018-05-25T19-49-13Z
jimmidyson/configmap-reload:v0.2.2

**Result:**

For an offline installation, it would be best to have all images in the rancher namespace

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2-rc2
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by deniseschannon** [comment]
@alena1108 can you check that all images used that were introduced are in rancher in dockerhub?

**Comment by alena1108** [comment]
@deniseschannon for coredns, we already have the issue https://github.com/rancher/rancher/issues/19710

I'll check the rest

**Comment by alena1108** [comment]
Filed a https://github.com/rancher/rancher/issues/19836 to keep track of moving `jimmidyson/configmap-reload:v0.2.2` into rancher dockerhub. As we have a separate issue for fixing coredns too, this bug should only be used for minio image move verification.

@sangeethah to verify, enable pipeline. In older versions of rancher, `minio/minio:RELEASE.2018-05-25T19-49-13Z` was used. With the fix, it should be `rancher/minio-minio:RELEASE.2018-05-25T19-49-13Z`

**Comment by alena1108** [comment]
Can be validated in `v2.2.3-rc3`

**Comment by leodotcloud** [comment]
@alena1108 would it make sense to use the who image under rancher?
Example: For `coredns/coredns:1.2.2`, we might be pushing to `rancher/coredns:1.2.2`. Instead can we push to `rancher/coredns/coredns:1.2.2`?

**Comment by leodotcloud** [comment]
@alena1108 Looks like it's not possible to use sub repos on docker hub. nvm.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.3-rc4

* Enabled pipeline
* minio image being used is: `rancher/minio-minio:RELEASE.2018-05-25T19-49-13Z`
