### ISSUE TITLE
Backport: k8s 1.14

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19432]
Backport https://github.com/rancher/rancher/issues/19039

**Comment by alena1108** [comment]
Can be tested with `rancher/rancher:v2.2.2-rc4`

**Comment by alena1108** [comment]
Update: k8s 1.14.1 is made available in `rancher/rancher:v2.2.2-rc5`

**Comment by soumyalj** [comment]
The following configurations have been tested on v2.2.0-rc5. Automation tests for the below configurations succeeded. 

1. Ubuntu 16.04 - docker version 18.09 
2. Ubuntu 18.04 - docker 18.09
3. RHEL 7.6 - docker version 1.13 (native) ( Support for RHEL 7.5 will be dropped) 
4. RHEL 7.6 - Upstream docker 18.09
5. ROS 1.5.1 - docker version it comes with
6. SLES - 12 SP2 - docker version v18.06.1_ce-98.24.1 - Pass
