### ISSUE TITLE
rancher execute shell unexpected exit

### ISSUE THREAD

**Issue by 4admin2root** [rancher/rancher#19430]
**What kind of request is this (question/bug/enhancement/feature request):**
bug?

**Steps to reproduce (least amount of steps as possible):**
1. select a pod,  click execute shell
2. run some cmd in shell window
3. the shell window will close unexpected 

**Result:**
the shell window will close unexpected

**Other details that may be helpful:**
1. I have upgraded rancher from v2.1.5 to v2.1.8
k8s from v1.11.6 to v1.13.5
2. In chrome console  :  
 ```
Socket null closed
vendor-ebb1f9e6b4381d69a55448a2a5d7e4c9.js:22838 Cluster Subscribe disconnected (sockId=null)
```
In chrome network :
```
GET wss://rancher.xxxx.xxx/v3/clusters/local/subscribe?sockId=63 HTTP/1.1
Host: rancher.xxxx.xxx
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: https://rancher.xxxx.xxx
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en,zh-CN;q=0.9,zh;q=0.8
Cookie: tu=d060017e0bdc30a51ad15ed65f8ae974; R_USERNAME=admin; CSRF=0982caac62; R_SESS=token-cn2rl:664t2mxdfnqwnx7khjcngcq62z2h7fc4mxz68bmhgfg8qvrqkfpkhk
Sec-WebSocket-Key: 9P86nPBpPrsz2aSG52d3Gg==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

Time: pending and then  change to time
```
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5 and v2.1.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 8C16G
- Kubernetes version (use `kubectl version`): v1.11.6 and  v1.13.5

```
v1.11.6 
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by edb-a12** [comment]
We are also experiencing the same issue

**Comment by superseb** [comment]
Can you let us know if it happens on recent versions? And provide what the network path between client and server is (browser -> Rancher UI) so we can investigate.

**Comment by Napsty** [comment]
@superseb Any reason (or solution around?) why this was closed? Seeing the same issue (Execute Shell window is unexpectedly closed, sometimes after a few seconds, sometimes longer after up to 2 min) here with Rancher 2.2.8.
On another Rancher setup with 2.1.6 the "Execute Shell" window is not unexpectedly closed.

**Comment by superseb** [comment]
There is nothing on the Rancher side closing the connection, it's either the pod that is used stops (can check logs on that) or something in between browser and Rancher that is closing it.

There is no known bug at the moment about connections getting closed from Rancher.

**Comment by Napsty** [comment]
Thanks for your reponse. What I see so far is the following different behaviour in Chromium Network Console.

Rancher 2.1.6: After login, a websocket connection to `wss://rancher2.example.com/v3/subscribe?sockId=1` is opened. I see `Subscribe connected` and eventually the sockId increases as I navigate through the Rancher UI.

![image](https://user-images.githubusercontent.com/3702203/63860023-afa49b80-c9a8-11e9-9539-c67520143a1d.png)

Rancher 2.2.8: After login, a websocket connection to `wss://rancher2.example.com/v3/subscribe?sockId=1` is opened. I see `Subscribe connected` and eventually the sockId increases as I navigate through the Rancher UI. However here disconnects of the Websockets happen (`Subscribe disconnected`). 

![image](https://user-images.githubusercontent.com/3702203/63860236-0f02ab80-c9a9-11e9-8ab9-b8459e7b80f8.png)

>  something in between browser and Rancher that is closing it

I can't rule out a problem in the LB yet and will test this and report back. However if it turns out to be irrelevant of the LB, please open this issue again :)

**Comment by Napsty** [comment]
@superseb I was able to catch the following error from one of the system containers when such an unexpected exit of the "Shell Execute" window happened:

```
container_name: k8s_agent_cattle-node-agent-qlmdv_cattle-system_897e30ef-c951-11e9-adae-0050568d3842_1
message: time="2019-08-29T06:41:32Z" level=error msg="Failed to connect to proxy" error="websocket: close 1006 unexpected EOF"
```

Does this give you additional hints? 

I have increased all kind of timeout values in the load balancer, so far with no success. The "window close" event also happens pretty randomly. Sometimes after 2s, sometimes it stays open for 3min.

**Comment by Napsty** [comment]
Since upgrading to Kubernetes 14 (however this caused DNS issues, see https://forums.rancher.com/t/no-dns-resolution-after-upgrading-kubernetes-1-13-to-1-14/15253/6) or Kubernetes 15, the Shell Execute window does not close unexpectedly anymore. No change in LB, only Kubernetes version update.

**Comment by openstack-test** [comment]
这个bug是存在的，我也遇到了

**Comment by kk17** [comment]
Any update on this issue? We are also experiencing the same issue using Rancher 2.6.8.

**Comment by devopswe** [comment]
We are still experiencing this problem and we have not found a solution. @superseb

**Comment by superseb** [comment]
@devopswe I would advise to file a new issue with versions, logs and any other related data to help investigate. I cannot help you anymore unfortunately.
