### ISSUE TITLE
RBAC in Multi Cluster App

### ISSUE THREAD

**Issue by rodesousa** [rancher/rancher#19441]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Launch a multi cluster app with rbac (like external dns with `rbac.create = true`)

**Result:**

Rancher can't deploy because there isnt have the rights

![image](https://user-images.githubusercontent.com/8577532/55725596-509cb500-5a0e-11e9-98ee-605596a81734.png)

**Environment information**
- Rancher version: 2.2.1

**Cluster information**
- Cluster type : Full Aks
- Kubernetes version : 1.12.6

**Comment by janeczku** [comment]
@rodesousa If your application accesses cluster level resources (like `clusterrolebinding`) you need to grant it cluster role in the multi-cluster-app configuration:

<img width="804" alt="Screenshot 2019-04-08 at 17 35 33" src="https://user-images.githubusercontent.com/3813921/55737098-e04d5e00-5a24-11e9-93ec-31d14dcc4f16.png">

See also the docs here: https://rancher.com/docs/rancher/v2.x/en/catalog/multi-cluster-apps/#roles

**Comment by rodesousa** [comment]
ok thx =)
