### ISSUE TITLE
Add ability to re-IP or change the hostname of server in rancher agent-instances

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1944]
If the Rancher Server IP/hostname changes, and you re-add host agents, we need a way to reconfigure the existing network and lb containers so they point to the new rancher IP.

**Comment by sangeethah** [comment]
Tested with server version - v0.37.0-rc1

Had a setup with 2 hosts that had multiple instances running and had 1 LB agent.

Rebooted rancher-server. This resulted in rancher-server getting a new ip address in my case. Rancher server was an Ubuntu instance in GCE.

After this hosts went into "reconnecting" state.

Did host registration again to set the ip address to the current rancher-server ip address.
Got the rancher-agent command to add custom host from UI and execute this on both the hosts.

Host get to "active" state.

Able to start new containers on the host.
Able to stop existing containers on the host , which restarts on service reconcile.
LB service continues to work.
Scale up Lb service . New LB agent is also functional.
