### ISSUE TITLE
Default registry ignored in Rancher HA setup (2.2.1)

### ISSUE THREAD

**Issue by roycec** [rancher/rancher#19447]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Install or upgrade to Rancher HA 2.2.1 with env CATTLE_SYSTEM_DEFAULT_REGISTRY set to internal registry
- Try to provision workload without full path to image

**Result:**
Workload hangs because image cannot be found/pulled.

**Other details that may be helpful:**
Similar problem, when trying to activate new ectd backup feature in 2.2. In UI the backup hangs with "activating" and the API page shows the error 
```
Can't pull Docker image [rancher/rke-tools:v0.1.27] for host [10.xx.xx.xx]: Error response from daemon: No default registry configured.
```
Is there a way, that these kind of tasks use the default registry configured in Rancher?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.1
- Installation option (single install/HA):
HA

**Comment by roycec** [comment]
I also tried to add a private registry in 'edit cluster' -> 'advanced options' -> 'add private registry', but the error stays the same. We upgraded to 2.2.2 recently and the problem exists there, too.

**Comment by roycec** [comment]
Just for info: We configured our docker daemon without a default registry and usually provide the full path.

**Comment by roycec** [comment]
When activating snapshots for a cluster, after some days the situation shows like this 
 
![2019-05-10_rancher_snapshots](https://user-images.githubusercontent.com/16775292/57512235-710ca780-730b-11e9-8004-5597056eab9e.PNG)

**Comment by izaac** [comment]
This is no longer reproducible on 2.7.0 as the default registry setting is honored. Please open a new issue if this problem still occurs.
