### ISSUE TITLE
kafka broker logging test failed

### ISSUE THREAD

**Issue by mshack70** [rancher/rancher#19448]
This is for v2.2.1.   In rancher 2.1.7, we successfully setup log forwarding to kafka over http (to kafka broker), but for v2.2.1, even though I put in an http url, the SASL cert section is showing required red boxes, and the test always fails with :

couldn't create kafka topic k8s: [41] Not Controller: this is not the correct controller for this cluster

**Comment by deniseschannon** [comment]
@aiwantaozi can you check if this is a regression introduced in 2.2?

**Comment by aiwantaozi** [comment]
Sure

**Comment by aiwantaozi** [comment]
@mshack70 Hi, the Test function we add in 2.2 hasn't support auto-detect Kafka controller in brokers yet, will support soon. You can continue to ```Save``` if the endpoint you configure is reachable but not the controller. What do you mean ```the SASL cert section is showing required red boxes``` do you have a screenshot or more details? Thanks

**Comment by mshack70** [comment]
Validation failed in API: Plain SASL authentication requires SSL is configured


I'm trying kafka broker, but we use http vs. https.

**Comment by mshack70** [comment]
I think what is happening is that i use ldap auth, and then later setup logging.  it auto filled the SASL portion with an ldap account at some point so I cleared it out.  It may have been a browser autofill issue.

**Comment by aiwantaozi** [comment]
Thanks for updating, SASL configure isn't required.

**Comment by bmdepesa** [comment]
rancher/rancher:master 5d74988c

* Setup kafka logging
* Enabled logging to kafka broker w/ http
* Test function worked without error
* Logging is functioning correctly
