### ISSUE TITLE
No host IP was given to the Vagrant core NFS helper

### ISSUE THREAD

**Issue by thbeh** [rancher/rancher#1945]
I have got the above when i run vagrant up with virtualbox as provider. Anything I missed?

**Comment by cloudnautique** [comment]
Was NFS sharing enabled in the Vagrantfile? If so, Rancher OS doesn't support NFS sharing yet. (It is coming soon) If NFS wasn't enabled, Can you let us know the version of Virtualbox, Vagrant and base OS you are using(Mac, Windows, etc). Thanks!

**Comment by deniseschannon** [comment]
@thbeh Please re-open if you are able to provide the requested information.
