### ISSUE TITLE
gzip responses to /v3 API

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#19454]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Inspect rancher, select "Network" tab
2. Navigate to a project.

**Result:**
Response is not gzipped: lacks "gzip" in "Content-Encoding" header when request contains gzip in "Accept-Encoding" header.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1+

**Comment by vincent99** [comment]
(To tell if a response is compressed, look for `Content-Encoding: gzip` response header)

**Comment by rmweir** [comment]
@vincent99 good point, clarified.

**Comment by cjellick** [comment]
This fix will cause requests to the main /v3 api to be gzip compressed if the client sends the appropriate header. most clients (browsers, our python library, our golang library) automatically send this header.
To verify (beyond what has already been stated): in chrome, open developer tools and what network requests. in the size column, there will be two values, one is the uncompressed size the other is the compressed size. before our change, these numbers are the same. after our change, the compressed size is smaller. a typical response on a cluster with a lot of pods is that the uncompressed will be 5 MB and the compressed size will be about 200 KB.

Areas to check for regression:
1. Ensure UI loads like normal
2. Ensure python tests behave normally
3. Ensure that RKE provisioned clusters can deploy workloads (bc they connect to rancher server over a websocket request tunnel and we want to ensure that the compression does not negatively impact them)
4. Ensure that the UI continues to dynamically update. Meaning if you deploy a workload, namespace, or app you can watch it go from activating to active without reloading (again bc a websocket connection is handling this update and we want to make sure compression isnt impacting that)

**Comment by davidnuzik** [comment]
Version: latest master (4/11/19) ImageID: 0d755e769e77

I validated the UI aspect of this issue. This was already checked in v2.2.2-rc10 in #19490 but I double-checked again in the last master for v2.3 scope.

I made sure that we see Content-Encoding: gzip when interacting with the API in the UI. And that the Content-Type is correct (except in a couple of areas which have issues entered). I notice that we transfer much less compared to inflated size as well with the gzip compression.

Monitoring / pipelines were checked again (Firefox) as well as a general review of the UI (try to smoke test everything I can think of). I did not encounter any issues or unexpected headers, etc.

**Comment by davidnuzik** [comment]
Mistakenly closed (Only UI aspect of required tests has been checked in master)

**Comment by jiaqiluo** [comment]
The bug fix is validated with Rancher: master 4fd2548

Step:
- run Rancher container, single installed 
- add an RKE cluster
- deploy some workloads in a project in the cluster
- run automation on the cluster

Result:
- confirm that the UI loads like normally
- confirm that the python tests behave normally  
- confirm that RKE provisioned clusters can deploy workloads
- confirm that Ensure that the UI continues to dynamically update

The issue can be closed based on this and the above UI tests from @davidnuzik
