### ISSUE TITLE
Cluster provisioning fails for K8s v1.14.1-rancher1-1 on Suse Linux and Rancher OS nodes

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#19461]
Rancher version: v2.2.2-rc5
K8s version: v1.14.1-rancher1-1 
OS : suse-sles12-sp2 and ROS
Docker version for ROS nodes : 18.06
Docker version for Suse linux nodes: 18.06
Steps
1. Create a cluster using Rancher OS-v1.15.1 nodes OR using suse-sles12-sp2 nodes

Cluster provisioning fails with the error below:

```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Failed to find system images for version v1.14.1-rancher1-1

```
Server Logs below:

```
2019/04/09 00:09:21 [ERROR] ClusterController c-dpgvt [cluster-provisioner-controller] failed with : failed to find system images for version v1.14.1-rancher1-1
2019/04/09 00:09:24 [ERROR] ClusterController c-dpgvt [cluster-provisioner-controller] failed with : failed to find system images for version v1.14.1-rancher1-1
2019/04/09 00:09:24 [ERROR] ClusterController c-dpgvt [cluster-provisioner-controller] failed with : failed to find system images for version v1.14.1-rancher1-1
2019/04/09 00:09:24 [ERROR] ClusterController c-dpgvt [cluster-provisioner-controller] failed with : failed to find system images for version v1.14.1-rancher1-1
2019/04/09 00:09:25 [ERROR] ClusterController c-dpgvt [cluster-provisioner-controller] failed with : failed to find system images for version v1.14.1-rancher1-1




```

**Comment by sangeethah** [comment]
This issue is not seen when testing with Ubuntu 16.04 , Ubuntu 180.4 and RHEL 7.6 OS.

**Comment by alena1108** [comment]
@galal-hussein can you check if you can reproduce. `failed to find system images` shouldn't be version specific; it's an error from rancher server

**Comment by alena1108** [comment]
@soumyalj can you please re-test on rc5. This sort of error would only happen when  the version `v1.14.1-rancher1-1` is not in go bindings (compiled to) rancher. 2.2.2 RC5 definitely has this version in

**Comment by soumyalj** [comment]
Tested with v2.2.2-rc5. 
Cluster provisioning with Suse linux and ROS nodes succeeded.
