### ISSUE TITLE
Backport EKS - adding ESK cluster failed in v2.2.2-rc5 #19460

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19469]
backport for #19460

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher v.2.2.2-rc6

Test 1 :
- run Rancher container  v.2.2.2-rc6
- add an EKS cluster
- wait for the cluster to be active
- check the cluster's version in both UI and API 

Result:
the cluster works well as expected

Test 2:
- run Rancher v2.1.8
- add an EKS cluster
- wait for the cluster to be active
- check the cluster's version in both UI and API 
- upgrade Rancher to v2.2.2-rc6 
- check the EKS cluster's version in both UI and API 
- add the second EKS cluster
- check the second EKS cluster's version in both UI and API 

Result:
both clusters work well as expected, and the information in UI and API can match each other

**Comment by jiaqiluo** [comment]
So far tested only the us-east-1 region. 
will test on all US regions and update the comment.
