### ISSUE TITLE
Backport Upgrading from 2.1.8, eks cluster api is getting wrong k8s version #19458

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19467]
backport for https://github.com/rancher/rancher/issues/19458

**Comment by cjellick** [comment]
maybe i didnt need to backport

**Comment by jiaqiluo** [comment]
The fix for the original issue and two more issues I mentioned in my comment under the ticket https://github.com/rancher/rancher/issues/19458#issuecomment-481055002  is validated on Rancher v2.2.2-rc6 upgraded from v2.1.8
