### ISSUE TITLE
EKS - adding ESK cluster failed in v2.2.2-rc5

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19460]
Bug

Adding an EKS cluster will fail and show this error in v2.2.2-rc5 
- fresh installed 
- upgraded from 2.1.8  
```
Error parsing state: default ami of region us-east-1 for kubernetes version 1.12 is not set
```
<img width="1474" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55764494-9f534a80-5a20-11e9-84d3-6f3269ed1695.png">

**Comment by jiaqiluo** [comment]
The validation is failed in Rancher: master version 8b8dc86c, fresh install. 

Adding an EKS cluster will fail with the following error message in the UI
```
Error creating stack: stack failed to create: Parameter validation failed: parameter value for parameter name KeyName does not exist. Rollback requested by user.
```
<img width="1488" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55821045-68794500-5ab1-11e9-9b95-8fbfaac53734.png">

But actually, the cluster is up and active in AWS console. 
<img width="1569" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55821095-847ce680-5ab1-11e9-9c5c-038a5bc2c40a.png">

**Comment by daxmc99** [comment]
@jiaqiluo Created an issue to track your comment [here](https://github.com/rancher/rancher/issues/19483).

**Comment by cjellick** [comment]
resolved, i think?

**Comment by jiaqiluo** [comment]
The issue can be closed. The derived issue is tracked by its own ticket.
