### ISSUE TITLE
Support enabling Project Network Isolation with Weave CNI

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#19477]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Create cluster and select Weave network provider
2. Try to enable Project Network Isolation

**Result:**
Project Network Isolation can't be enabled if Weave is selected.

**Result:**
User should be able to enable Project Network Isolation for any available network provider that support K8s network policies: Canal, Calico and Weave.

**Other details that may be helpful:**
RFE for Calico is here: https://github.com/rancher/rancher/issues/14085 and https://github.com/rancher/rancher/issues/14879

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.1

gz#7699

**Comment by kinarashah** [comment]
PRs to add PNP for Calico tracked and tested in #31338.
