### ISSUE TITLE
cattle-prometheus namespace not removed alongside cattle-system when imported cluster deleted in Rancher

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#19476]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Import a cluster into Rancher v2.2.1
2. Enable cluster monitoring in the imported cluster
3. Delete the imported cluster via Rancher UI

**Result:**

The `cattle-system` namespace is removed from the cluster upon deletion in the Rancher UI; however, where cluster monitoring has been enabled and the `cattle-prometheus` namespace thus created and populated, this namespace is not removed upon cluster deletion in Rancher.

**Environment information**
- Rancher v2.2.1

**Comment by thxCode** [comment]
Should we clean up Monitoring after dropping the cluster from Rancher? @loganhz

**Comment by loganhz** [comment]
Should we drop logging, alerting, ( registry and istio in 2.3 ) workloads as well in this case? @alena1108 @cjellick

**Comment by deniseschannon** [comment]
yes, we should be cleaning up anything we enable. @loganhz

**Comment by jiaqiluo** [comment]
The bug fix is validated on master 5/31

Steps:
- Import a cluster into Rancher: master 
- Enable cluster monitoring in the imported cluster
- Delete the imported cluster via Rancher UI

Results:
- Both the namespaces and pods under the namespaces `cattle-prometheus` and `cattle-system` are removed from the cluster.
