### ISSUE TITLE
Add South Central US, Korea South, and Korea Central to AKS regions

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#19475]
**What kind of request is this (question/bug/enhancement/feature request):**
task

**Steps to reproduce (least amount of steps as possible):**

https://azure.microsoft.com/en-gb/updates/general-availability-azure-kubernetes-service-in-south-central-us-korea-south-and-korea-central/

**Comment by davidnuzik** [comment]
What version @westlywright ? (milestone missing)

**Comment by davidnuzik** [comment]
Version: Master (4/11/19)

These regions are now added to the Location drop-down when creating an AKS cluster.

![image](https://user-images.githubusercontent.com/45179589/55998328-abcee180-5c72-11e9-8cec-736e2fb5e9a2.png)
In the screenshot you'll notice we've added: "South Central US", "Korea South", "Korea Central"

QA is not able to actually provision these clusters, but I validated the HTTP and it looks correct for each region.
HTTP:
`location: southcentralus`
`location: koreacentral`
`location: koreasouth`

**Comment by davidnuzik** [comment]
master-head (v2.3) (7/19/19)
We now have access to these regions in Azure.

I tested again and confirmed my South Central US, Korea Central, and Korea South regions all work without any issues. All AKS clusters came up without any issues and the resources are all in the correct region.
