### ISSUE TITLE
UI Cloud Providers Should Add Kubernetes Version to Dropdown If Not Present

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19478]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
An EKS cluster with a version greater than 1.12 is required to test this, it make take some munging of the data to produce this as 1.13 is not ready for EKS currently. 

**Result:**
The version returned in the cluster config from the api is NOT shown in the Kubernetes version dropdown.

**Comment by n313893254** [comment]
Because of EKS support v1.13 now, Here are my reproduce steps:
1. Add an EKS cluster with v1.13.
2. Remove v1.13 from versions choice.
3. Edit EKS cluster

Result:
form-version cannot work. Browser console shows an error:  `Uncaught (in promise) TypeError: Invalid Version: 1.13`

**Comment by davidnuzik** [comment]
@n313893254 could you help me with #2 "Remove v1.13 from versions choice"
Forgive me, but I am failing to understand what this means. Is this going in the API and making a change? Or intercept HTTP and do something?

Appreciate any info

**Comment by n313893254** [comment]
@davidnuzik I edit the code to test, https://github.com/rancher/ui/blob/02226c4149fe39fcbff51f72b5d405e31b4a815b/lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js#L13.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/19/19)

- Create EKS 1.13 cluster (UI sends in amazonElasticContainerSeerviceConfig) `kubernetesVersion: "1.13"`
- Pull rancher/ui; modify /lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js such that line 13 no longer contains the 1.13 version. Follow the rancher/ui README.md to run the UI locally with this modification.
- Edit the EKS cluster. 

Result: Now we no longer have any issues with form-version; there are no JS console errors as well. The UI shows the version in the dropdown upon edit without any issues:
![image](https://user-images.githubusercontent.com/45179589/63288549-d7418880-c271-11e9-9c77-a29034d55db2.png)
