### ISSUE TITLE
Configure load balancer how to choose container/host

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#1947]
Hey,
is there a way to configure a rancher load balancer how to behaive?
Meaning e.g. choose a host depending on some kind of criteria. 
I read that normally load blancer choose container with good health check and then round robin(?). But I would like that instead of round robin I could configure e.g. a threshold for cpu (or any other measurement) usage.

**Comment by alena1108** [comment]
@fentas yes, today the server pick is made among healthy servers based on round robin algorithm. We use haproxy to implement our load balancer solution, and it supports more algorithms:

https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#balance

we are planning to expose them at some point. It can either be done by exposing this config via API:

https://github.com/rancher/rancher/issues/876

or allowing user specify it in the Defaults section:

https://github.com/rancher/rancher/issues/1871

**Comment by deniseschannon** [comment]
We've implemented #1871 to allow custom Defaults and global section. @fentas Please re-open if there is something additional that you would need.
