### ISSUE TITLE
Feature Request: Helm Charts Pre-loading for Air-Gap Support

### ISSUE THREAD

**Issue by gabrielcalderon** [rancher/rancher#19487]
The guide for installing the system charts in air-gap environments states that they must be hosted somewhere. Wouldn't it makes sense to be able to mount or copy this charts into a specific location in rancher?

Current:
 * In air-gap environments you must host your own charts using a git-repo which adds more complexity and prone to errors with instances that require user-auth with ssh-keys.

Expected:
 * Be able to run Rancher with an extra CLI flag that states to check for charts in a specific folder.
 * Rancher pre-loads all the charts found in that location.

**Environment information**
- Rancher version: v2.2.1
- Installation option (single install/HA): Single Install (air-gap)

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/17126

**Comment by dramich** [comment]
Tracking progress [here](https://github.com/rancher/rancher/issues/20387)

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/21260

**Comment by cjellick** [comment]
Closing as a dupe of #21260

**Comment by cjellick** [comment]
I mean https://github.com/rancher/rancher/issues/20387
