### ISSUE TITLE
API Keys - seperation of permissions

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#1948]
joho,
I would like to see that I can give api keys different kind of permissions.
As for example 'access to registration tokens', 'read services', 'start services' and so on. (In a way choose permissions (get/post/delete/etc.) for every rest api url)
Now it's a bit annoying because I have an infrastructure in which hosts are self managing. At the beginning I created my own rest api within to expose only that functionality I want. But as further I go as more blown up it will get. Could be solved with this proposal.

**Comment by fentas** [comment]
After re-parsing rancher issues found this #1364. Guess this points into the same direction.

**Comment by deniseschannon** [comment]
Our RBAC feature https://github.com/rancher/rancher/issues/1338 is probably more what you are looking for. If that's okay, I'll close this issue.

**Comment by fentas** [comment]
Right. Tx.
