### ISSUE TITLE
EKS cluster fails to provision with 'Error creating stack: Parameter validation failed'

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#19483]
The validation is failed in Rancher: master version 8b8dc86c, fresh install. 

Adding an EKS cluster will fail with the following error message in the UI
```
Error creating stack: stack failed to create: Parameter validation failed: parameter value for parameter name KeyName does not exist. Rollback requested by user.
```
<img width="1488" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55821045-68794500-5ab1-11e9-9b95-8fbfaac53734.png">

But actually, the cluster is up and active in AWS console. 
<img width="1569" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55821095-847ce680-5ab1-11e9-9c5c-038a5bc2c40a.png">

Other information:
I did not see the issue in v2.2.2-rc6

_Originally posted by @jiaqiluo in https://github.com/rancher/rancher/issues/19460#issuecomment-481350559_

**Comment by jiaqiluo** [comment]
The bugfix is validated in Rancher: master 7725bc8f

The EKS cluster provision is successful and basic automation tests are passed.
