### ISSUE TITLE
Backport: cluster state saved/fetched incorrectly in clusters with prefix path

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19484]
Backport https://github.com/rancher/rancher/issues/19519

RKE issue: https://github.com/rancher/rke/issues/1282

**Comment by alena1108** [comment]
Can be tested in rc8

**Comment by soumyalj** [comment]
Tested with the steps mentioned in Issue #17965 using Rancher OS 1.5.1 nodes

Create ros machine
Run rke v0.1.17 up on it
Break the kubeconfig by changing the client-certificate-data or client-key-data in the kubeconfig file
rke up fails as below:

INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [state] Possible legacy cluster detected, trying to upgrade 
INFO[0000] [reconcile] Rebuilding and updating local kube config 
INFO[0000] [state] Fetching cluster state from Kubernetes 
WARN[0000] Failed to fetch state from kubernetes: Failed to create Kubernetes Client: Error loading config file "./kube_config_cluster.yml": v1.Config: AuthInfos: []v1.NamedAuthInfo: v1.NamedAuthInfo: AuthInfo: v1.AuthInfo: ClientKeyData: ClientCertificateData: decode base64: illegal base64 data at input byte 1428, error found in #10 byte of ...|tLQo=ABCD","client-k|..., bigger context ...|veTJDZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=ABCD","client-key-data":"LS0tLS1CRUdJTiBSU0EgUFJJVkFURS|... 

There is no attempt to get the correct state from the nodes.
4. Download latest rke 0.2.2.-rc1
5. Ensure cluster-state.yml file exists on the nodes in /opt/rke/etc/kubernetes/.tmp
If it doesn't exist, then create it with content of the same cluster.yml that you have
7. remove the broken rkestate file in your local directory
8. run rke up

Cluster comes up correctly.
