### ISSUE TITLE
sticky session with nested load balancers

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#19482]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create Rancher 1.6 cattle cluster
- Create 1 public load balancer
- Create 2 internal only load balancers
- Create the following rules
End user -> Public LB -> Internal LB -> Application

**Result:**
Requests will bounce between both internal LBs

**Other details that may be helpful:**
We did add the following to the custom config with no change.
load_balancer_config:
lb_cookie_stickiness_policy:
cookie: persistencecookie

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v1.6.17
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
