### ISSUE TITLE
Support EBS drivers for Convoy

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1949]
support EBS as an additional driver for convoy.

**Comment by parabuzzle** [comment]
?? so does convoy support EBS then?

**Comment by yasker** [comment]
@parabuzzle 

Yes. It supports EBS now.

We would release Convoy v0.3 shortly with official EBS support. It's already working with [v0.3-rc1](https://github.com/rancher/convoy/releases/tag/v0.3-rc1)

See [here](https://github.com/rancher/convoy/blob/master/docs/ebs.md) for document.
