### ISSUE TITLE
rancher HA 2.1.8 - new cluster failed to register new worker with  long time "waiting for node to register"

### ISSUE THREAD

**Issue by lianlianhe** [rancher/rancher#19495]
**What kind of request is this (question/bug/enhancement/feature request):** question

**Steps to reproduce (least amount of steps as possible):**
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.8 --server https://rancher-test-ha.com --token {..........} --ca-checksum {..........} --worker --debug
**Result:**

waiting for node to register

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.1.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):cloud
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
18.09.3
```

**Comment by lianlianhe** [comment]
the command of registeration as new worker - 
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.8 --server https://rancher-test-ha.yingyukanshijie.com --token fjpn5j84hltfdh9clcfggrshxdmpvdmnkn4cfdsgx4gzz8zxgsl49p --ca-checksum 0043aeb774bf53212845aa36ecbf140b10ecb03f7b416d55aca406f71abaf5d4 --worker --debug

the  cert checking passed.

**Comment by superseb** [comment]
Each cluster needs at least one etcd and one controlplane node, what is the status of the cluster in the Global view?

The log message was improved in 2.2:

```
		logrus.Infof("waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first")
```

**Comment by lianlianhe** [comment]
Thanks! 
 My mistake,I lacked to add  etcd and controlplane role in target cluster.
