### ISSUE TITLE
[UI] Force managing namespaces from the main namespace tab or warn if there are other items in the namespace that will be deleted. 

### ISSUE THREAD

**Issue by hanxinyu** [rancher/rancher#19494]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
Delete a namespace in "Config Maps" or "Secrets" page.

**Result:**
The full namespace has been deleted including deployments and others in this namespace.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Kubernetes version (use `kubectl version`): v1.11.6

**My question is**
1. Why the namespace operation button is set in "Config Maps" or "Secrets" page, even if the login user has no authorization to manage namespace? 
2. If the login user has authorization to manage namespace, it's a definite possibility to make a mistake to delete the namespace when just want to delete a configmap in it.

**Comment by deniseschannon** [comment]
1. Any project member/owner has ability to manage namespaces. 
2. I'd like to make this as an UI enhancement to remove the ability to *only* manage namespaces in the Namespace tab.

Not sure if our users are already used to/prefer the ability to manage namespaces in all the other pages (workloads/load balancers, configmaps, etc).

**Comment by deniseschannon** [comment]
Alternatively, we can warn the user if there are other items in that namespace before deleting.

**Comment by hanxinyu** [comment]
God, I delete the whole namespace again and get ready to be fired.
