### ISSUE TITLE
gzip messages to and from agents

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#19493]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Run rancher locally
2. Log data written to tunnel?

**Result:**
Messages are readable and not being compressed (gzipped).
_Note:_ probably won't be able to tell from response header since its a wss connection

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1+

**Comment by cjellick** [comment]
We aren't going to pursue this change at this time.
