### ISSUE TITLE
As user, I want to backup/restore etcd IMPORTED clusters

### ISSUE THREAD

**Issue by donnguyen** [rancher/rancher#19492]
**What kind of request is this (question/bug/enhancement/feature request):**
**enhancement**

**Steps to reproduce (least amount of steps as possible):**
- Import a cluster

**Result:**
- Go to that imported cluster from Global view, there is no where to backup/restore etcd

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): |Versions|Rancher `v2.2.1` UI: `v2.2.19` |
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported

**Comment by deniseschannon** [comment]
If Kubernetes is not launched by Rancher (aka using either a node from an infrastructure provider or .a custom cluster), the expectation is that the management of Kubernetes (which includes backups/restores) is done outside of Rancher. This includes imported clusters.
