### ISSUE TITLE
Backport gzip responses to /v3 API #19454

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19490]
Backport for #19454

**Comment by cjellick** [comment]
will be in rc8

**Comment by davidnuzik** [comment]
I know we are aware of most of the issues with the gzip changes but I am recording them so we can be certain we are aware of all of them.

Monitoring:

v2.2.2-rc8
With Firefox, monitoring does not work as expected.
v3/clustermonitorgraphs?action=query
![image](https://user-images.githubusercontent.com/45179589/55898736-15b69080-5b78-11e9-97cd-76266259e31e.png)

![image](https://user-images.githubusercontent.com/45179589/55898802-3f6fb780-5b78-11e9-8b60-a5a6bd7f1507.png)


When I use Chrome I encounter no issues.

I noticed in FF I see the response as gzipped data or a hash or something like:
`H4sIAAAAAAAA/5SPwUoDMRCG32VOColMthmb7NmL4BuUPYRkWld3NyHJCqX03WUrCNrW4jn/l2++A9R9YmjBx2FgX/s4gYDgqoN2c4Bddun1+Wl5l4/bN/Pe+mEulbP0aZZDdAEEFM49l9N+cuPy2Ut0QdFdcB99kNmbexCQYj/VZbXBB4UkFJG2ilbGImLXHcVP+jrc2FvwH+ZGnbEn+nroyGPMezkXt+OLsd+u35GGcG0VoUZa6eb86BvibfmSysTZ81T/JUeyazSaFBltyKK9YO+OnwEAAP//uOiaxv4BAAA=`

Whereas in chrome I see the response as decompressed plain text:
`{"type":"collection","data":[{"graphID":"c-6fj8k:cluster-network-packet","series":[{"name":"Transmit packets(david-rc8)","points":[[2.07719298245614,1554915712000],[2.1052631578947367,1554915717000],[2.1052631578947367,1554915722000],[2.1052631578947367,1554915727000],[2.0561403508771927,1554915732000],[2.0561403508771927,1554915737000],[2.0561403508771927,1554915742000],[2.063157894736842,1554915747000],[2.063157894736842,1554915752000],[2.063157894736842,1554915757000],[2.0350877192982453,1554915762000],[2.0350877192982453,1554915767000],[2.0350877192982453,1554915772000],[2.0280701754385966,1554915777000],[2.0280701754385966,1554915782000],[2.0280701754385966,1554915787000],[2.021052631578947,1554915792000],[2.021052631578947,1554915797000],[2.021052631578947,1554915802000],[2.0561403508771927,1554915807000],[2.0561403508771927,1554915812000],[2.0561403508771927,1554915817000],[1.9964912280701754,1554915822000],
TRUNCATED_THIS!]]}]}]}`

**Comment by davidnuzik** [comment]
Pipelines:

v2.2.2-rc8
With Firefox pipelines do not work as expected.
v3/projects/c-6fj8k:p-5t5xt/pipelines/p-5t5xt:p-2jllq/configs
![image](https://user-images.githubusercontent.com/45179589/55899615-22d47f00-5b7a-11e9-96da-61377f691d13.png)

I run into the same problem as monitoring... I see the response is either not decompressed or is a hash or something -- it just looks like binary data to me.
![image](https://user-images.githubusercontent.com/45179589/55899722-57483b00-5b7a-11e9-94ae-7dd3aa15cb37.png)

response:
`H4sIAAAAAAAA/6pWyk0sLkktUrLKK83JqQUEAAD//wOUq5gPAAAA`


But in Chrome it works. The response is (in my case):
`{"master":null}`

The other browsers also work fine; I only see the issue in Firefox.

**Comment by davidnuzik** [comment]
I have not been able to identify any other issues in other areas of the UI. I spent a decent amount of time trying to smoke testing everything I could imagine in the UI.
If I identify any other issues I will leave a comment. I will continue my testing with other issues today with Firefox just in case I identify any other problem-areas.

**Comment by davidnuzik** [comment]
Refer to #19508 for incoming fix

**Comment by cjellick** [comment]
will be in rc9

**Comment by sowmyav27** [comment]
Verified the below cases in `rancher:v2.2.2-rc8`.
1. `Content-Encoding: gzip` is available in the response header.
2. Provisioned AWS and DO clusters. Deployed workloads and ingresses.
3. Deployed Multi cluster app, catalog apps and namespaces. They go from activating/installing to active without reloading.
4. Automation test cases have passed.
5. Verified a the size difference in the api calls(project having around 100 workloads where the size difference was noticeable) 
<img width="1667" alt="Screen Shot 2019-04-10 at 11 43 04 AM" src="https://user-images.githubusercontent.com/26032343/55904980-e575ee80-5b85-11e9-9e2f-4434f178598a.png">
<img width="1677" alt="Screen Shot 2019-04-10 at 11 52 39 AM" src="https://user-images.githubusercontent.com/26032343/55905911-f162b000-5b87-11e9-8d6f-88623858dc76.png">

**Comment by sangeethah** [comment]
@davidnuzik Issues seen with monitoring and pipeline can be validated in rc9  tracked in #19508. Please follow up on these workflows in  https://github.com/rancher/rancher/issues/19508.
