### ISSUE TITLE
Backport: Set content type if empty for gzipped responses

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#19508]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Open rancher using firefox browser
2. Enable monitoring for a cluster
3. Navigate to that cluster

**Result:**
Error messages caused by failure to parse JSON.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2-rc8

**Comment by cjellick** [comment]
backport of https://github.com/rancher/rancher/issues/19507

**Comment by cjellick** [comment]
in rc9

**Comment by davidnuzik** [comment]
Replicated in v2.2.2-rc8

Validated in v2.2.2-rc9
Test with FireFox.
- Create any cluster, enable monitoring
- No longer get any errors as previously observed with rc8
- Smoke test monitoring, ensure is working without any issues (all charts not just on main cluster page, include workloads, pods, containers).

- Set up a pipeline, ensure this works as well without any issues.

For both monitoring and pipeline, ensured json response now appears correct.
Content-Type is as expected. For example pipeline configs query:
![image](https://user-images.githubusercontent.com/45179589/55908003-1efe2800-5b8d-11e9-8a48-e67b9522f016.png)

And response is proper json now.
