### ISSUE TITLE
Backport: Custom CAs no-longer work with git-based custom catalogs in Rancher v2.2

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19505]
Backport https://github.com/rancher/rancher/issues/19473

**Comment by alena1108** [comment]
Can be tested with rc10

**Comment by bmdepesa** [comment]
rancher-latest/rancher:2.2.2-rc10

* Created HA Rancher installation
* Created gitlab instance with self signed certs configured (https://docs.gitlab.com/omnibus/settings/nginx.html#manually-configuring-https)
* Using the one-line validation provided here: (https://gist.github.com/superseb/8f472a89fb19874fedbb8621942f7b6f)
* git binary validation without adding additionalTrustedCAs:
 ```
rancher-749dfb475-7j98p: https://x.x.x.x: certificate not recognized
rancher-749dfb475-f5m7h: https://x.x.x.x: certificate not recognized
rancher-749dfb475-h7z6j: https://x.x.x.x: certificate not recognized
```
* Add additional CA cert
  * `kubectl -n cattle-system create secret generic tls-ca-additional --from-file=ca-additional.pem`
  * Update Rancher release with `--set additionalTrustedCAs=true`
 * git binary validation with additionalTrustedCAs
 ```
rancher-588f65f7fc-54vpn: https://x.x.x.x: certificate is recognized
rancher-588f65f7fc-ktzgh: https://x.x.x.x: certificate is recognized
rancher-588f65f7fc-vhxfk: https://x.x.x.x: certificate is recognized
 ```
 * Test HTTP GET
 * `rancher-add-selfsigned-catalog.sh` (https://gist.github.com/superseb/8f472a89fb19874fedbb8621942f7b6f#file-rancher-add-selfsigned-catalog-sh)
 ```
Adding https://x.x.x.x
Waiting for catalog status refreshed
Catalog status is refreshed
https://x.x.x.x: certificate is recognized
```
