### ISSUE TITLE
Backport: Node Template - 'Location' on the UI does not get updated when you edit and save an AWS node template

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19503]
Backport of rancher/rancher#19396

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: v2.2.3-rc1

I confirmed this is now working as expected. When I change the region for my aws template this is updated in the UI now including other locations in the same region (us-west-2a, us-west-2b, etc)

I also tried with a digitalocean template and the location will update for that template as well.
