### ISSUE TITLE
Backport: cattle-cluster-agent to control plane node leaking sockets

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19518]
Backport: https://github.com/rancher/rancher/issues/19391

**Comment by leodotcloud** [comment]
Global > Cluster > System (project)
Exec inside the cattle-cluster-agent container.

`netstat -antp | grep 6443 | wc -l`
The count shouldn't keep growing as you execute either `kubectl` or `helm` commands against the cluster.

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.2.2-rc10
Steps:
- run Rancher v.2.2.2-rc10 singe install
- add a DO cluster
- run `while true; do kubectl version; done` in the `Launch Kubectl` window
- follow @leodotcloud 's command to check the count and see the following output
```
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
3280
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
3292
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
4084
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
4102
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
4387
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
4407
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
4436
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
4562
root@cattle-cluster-agent-57b9d54db6-dbzt2:/# netstat -antp | grep 6443 | wc -l
6279
```

**Comment by sangeethah** [comment]
can be tested with  `v2.2.2-rc10`

**Comment by jiaqiluo** [comment]
on v2.2.2-rc11
- run the loop in kubectl command line increase the count by 1 
- deploy the app `wordpress` and `redis` increase the count by about 30

on v2.2.2-rc10
-  run the loop in kubectl command line keeps increasing the count 
- deploy the app `wordpress` and `redis` increase the count by about 300
