### ISSUE TITLE
Monitoring - Metrics for workload/pod/container are missing 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19516]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.2.2-rc9 container single installed
- add a DO cluster with 3 nodes (1 etcd, 1 control plane, 1 worker)
- enable cluster monitoring
- deploy some workloads in the default project
- go to check the metrics in the workload/pod/container page

**Result:**
- The Grafana link works and we can see relevant statistics in the Grafana page
- we expected to see the metrics for workload/pod/container

<img width="1425" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55912437-815c2600-5b97-11e9-9461-5044a6b008fb.png">

<img width="1418" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55912425-7dc89f00-5b97-11e9-94d3-5575b77f1049.png">

<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55912419-7acdae80-5b97-11e9-8569-33ff431fb89b.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.2-rc9
- Installation option (single install/HA):
single install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by jiaqiluo** [comment]
Here is another scenario
 
In v2.2.1
- as the admin, enable the cluster monitoring
- deploy some workloads in the project p1
- see the metrics for workload/container/pod
- see Grafana icon

upgrade to v2.2.2-rc9
- the metrics for workload/container/pod is missing
- still can see the Grafana icon

**Comment by alena1108** [comment]
Can be tested with rc10

**Comment by jiaqiluo** [comment]
The bug fix is validated with the following two test cases 

Case 1 
- run Rancher v2.2.2-rc10 single install
- add a DO cluster 
- as the admin, enable the cluster monitoring
- deploy some workloads in the project p1
- confirm that the metrics for workloads/pods/containers show up 
- log in as different roles to confirm that the RBAC around the metrics works as expected 

Case 2

- run Rancher v2.2.1 single install
- as the admin, enable the cluster monitoring
- deploy some workloads in the project p1
- see the metrics for workload/container/pod
- upgrade to v2.2.2-rc9
- confirm that the metrics for workloads/pods/containers still show up
