### ISSUE TITLE
Monitoring - Project Monitoring action -enableMonitoring still seen as link for project.

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19528]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.2.1
- add a DO cluster
- add a project 
- enable both the cluster and project monitoring
- upgrade to v2.2.2-rc9

**Result:**
- If viewing the project in API, it shows the link `enableMonitoring` in the `action` section, but all project-monitoring related actions are gone in the right upper widget
<img width="1880" alt="screenshot 3" src="https://user-images.githubusercontent.com/6218999/55925224-cac16b00-5bc1-11e9-89d7-edac4fc589a7.png">

- try to curl the API with those actions and get 404 error message
```
➜  ~ curl -u "my-tokey-and-key" -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{}' 'https://68.183.158.79/p/c-xgbq8:p-brrvd?action=disableMonitoring' --insecure
404 page not found
➜  ~ curl -u "my-tokey-and-key" -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{}' 'https://68.183.158.79/p/c-xgbq8:p-brrvd?action=editMonitoring' --insecure
404 page not found
➜  ~ curl -u "my-tokey-and-key" -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{}' 'https://68.183.158.79/p/c-xgbq8:p-brrvd?action=viewMonitoring' --insecure
404 page not found
➜  ~ curl -u "my-tokey-and-key" -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{}' 'https://68.183.158.79/p/c-xgbq8:p-brrvd?action=enableMonitoring' --insecure
404 page not found
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.1 upgrade to v2.2.2-rc9
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by sangeethah** [comment]
Is getting "404 page not found" the right behavior in this case ?

**Comment by loganhz** [comment]
@sangeethah Yes, confirmed with @thxCode

**Comment by thxCode** [comment]
Yes, @sangeethah . We disable the Project Monitoring until fixing the permission leak.

**Comment by alena1108** [comment]
Can be tested with rc10

**Comment by jiaqiluo** [comment]
The bug fix is validated with the following two test cases 

Case 1 
- run Rancher v2.2.2-rc10 single install
- add a DO cluster 
- enable the cluster monitoring
- add a project p1
- view the project p1 in API 
- confirm that the link `enableMonitoring` in the `action` section is gone
- confirm that curling the API with related actions and get 404 error message

Case 2
- run Rancher v2.2.1 single install
- add a DO cluster 
- enable the cluster monitoring
- add a project p1 
- upgrade to v2.2.2-rc9
- confirm that the link `enableMonitoring` in the `action` section is gone
- confirm that curling the API with related actions and get 404 error message
