### ISSUE TITLE
Invalid server response (expected JSON, got garbage) for some API calls with Firefox/Chrome

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19524]
v2.2.2-rc8

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

_Note: This doesn't really seem to hurt anything in the UI; however, it may be worth looking into at some point to identify the nature of the problem_
_This issue only shows an example with OpenLDAP but ALL other auth providers are affected. In order to keep this issue short we only included an example with OpenLDAP since these all appear related we get basically the same results for each area_
**Use Firefox only for all tests and keep dev tools open watching http, other browsers are ALSO AFFECTED but do not provide the same issues as seen in screenshots**
For example Chrome will just mention "Failed to load response data" for invalid json server response payloads

**Steps to reproduce (least amount of steps as possible):**
- Enable OpenLDAP Auth
- Disable access control

----------

**Result:**
## When _**Enable**_ OpenLDAP you will see these headers and this bad response from the server:
_**(happens in all, v2.1.8, v2.2.2-rc7 and v2.2.2-rc8)**_
_This is presumably happening because we are sending application/json but with a Content-Length of zero however we don't see that issue when we disable auth as seen in the below screenshots_
![image](https://user-images.githubusercontent.com/45179589/55919828-41ec0480-5bac-11e9-900f-27f934ce3c72.png)
![image](https://user-images.githubusercontent.com/45179589/55919839-49131280-5bac-11e9-80f5-44510aac73d2.png)

## When _**Disable**_ OpenLDAP you will see these headers and this non-json response from the server:
_**We get this for v2.1.8 and v2.2.2-rc7:**_
(notice response is null with content-length of zero)
![image](https://user-images.githubusercontent.com/45179589/55919882-7233a300-5bac-11e9-801c-c452c1cd897b.png)

![image](https://user-images.githubusercontent.com/45179589/55919990-ea01cd80-5bac-11e9-82e7-91444c4a11df.png)

_**and we get this for v2.2.2-rc8:**_
(notice response is _not null_ with content-length of 23)
![image](https://user-images.githubusercontent.com/45179589/55920046-246b6a80-5bad-11e9-8949-35aa4573c1ba.png)

![image](https://user-images.githubusercontent.com/45179589/55919975-db1b1b00-5bac-11e9-8f91-86dab5141f9b.png)

**Other details that may be helpful:**
These differences between v2.1.8/v2.2.2-rc7 and rc8 are due to #19490   
Again, nothing in the UI _seems_ to break and we don't see errors in the UI this is just something we thought was odd when testing rancher/rancher#19490  and rancher/rancher#19508  by smoke testing the UI in various areas.

**Comment by davidnuzik** [comment]
Based on a discussion in Slack this is probably out of scope and should be moved out, but it is only happening in v2.2.2-rc8 - essentially what has changed is our server response when we disable auth and change passwords but it doesn't seem to break anything or hurt the UI.

It may be worth investigating later.

**Comment by davidnuzik** [comment]
A separate issue has been created to track pwd change having incorrect Content-Type: #19553

**Comment by cjellick** [comment]
@davidnuzik could this be closed?

**Comment by davidnuzik** [comment]
@cjellick If we do not wish to fix the issue then yes. I do not consider it a priority or a must-fix.

It's more of an inconvenience and inappropriate way of sending a server response, but doesn't seem to hurt anything other than possibly in very edge cases with testing/troubleshooting.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/7/19)

I can confirm that a proper Content-Type header is now sent in server response when disabling auth. This resolves the issue. Reference https://github.com/rancher/rancher/pull/19526

![image](https://user-images.githubusercontent.com/45179589/59212573-a81ee480-8b67-11e9-80f2-b730cc4cdf7c.png)
