### ISSUE TITLE
Make k8s 1.14 an officially supported

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19522]
- [x] remove experimental tag from k8s 1.14 by doing more extensive test + upgrade
- [x] run and publish k8s conformance for rancher/k8s 1.14 and rke standalone/k8s 1.14. Instructions can be found [here](https://github.com/rancherlabs/the-ranch/wiki/Running-and-Submitting-Conformance-Tests).

**Comment by davidnuzik** [comment]
Once this is ready #20725 can be changed to test so UI can check that kube-node-lease is now in System project.

**Comment by superseb** [comment]
Conformance: https://github.com/cncf/k8s-conformance/pull/624 && https://github.com/cncf/k8s-conformance/pull/625

**Comment by sangeethah** [comment]
All tests relating to 1.14 done on master builds are tracked in https://github.com/rancher/rancher/issues/19039
