### ISSUE TITLE
Move enable/Disable to bottom of page for monitoring

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#19525]
Version - master

**Steps to reproduce (least amount of steps as possible):**
1.  Go to monitoring page when it is disabled.

**Result:**  I have to click on Enable then click on Save.  It's not intuitive that you have to go to bottom of page to save. 

**Expected:**
Disable and Enable button on bottom of page.  The options should always show up.  You can click Enable or Disable at bottom and it will enable/disable and save at the same time.  If you want you can grey the options when it's disabled, that is fine with me.

**Comment by loganhz** [comment]
Monitoring page has been updated in master

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/20/19)

I can confirm the Enable button has been moved to the bottom of the monitoring config page (both cluster and project level).

If you do not have sufficient resources to enable monitoring the button is grayed-out.
![image](https://user-images.githubusercontent.com/45179589/58037082-6f986780-7ae1-11e9-819f-f39ecbd2ffce.png)

If and only if you have sufficient resources based on your settings the button can then be clicked:
![image](https://user-images.githubusercontent.com/45179589/58037111-8212a100-7ae1-11e9-8547-99876f5c6b43.png)

Once enabled the button changes to a green color briefly stating "Saved!" it then goes back to a normal "Save" blue button so you can save your changes.

Disabling monitoring is still at the top-right which I think is okay. This keeps it out of the way and is in red so you do not accidentally click it and you also have to click it twice, one to prompt and another time to confirm.
