### ISSUE TITLE
Mirror coredns image to rancher

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19520]
Coredns image - used when coredns is chosen as a plugin for rke cluster (optional)  - is not being mirrored to rancher. We should:

- [x] start mirroring it (https://github.com/rancher/types/pull/787)
- [x] make sure that the mirrored image is used for new k8s versions only, so no auto upgrade happens for clusters deployed pre-2.2.x. Can be mitigated by dropping .m() for coredns versions shipped with 2.2.0, 2.2.1 and 2.2.2

**Comment by jiaqiluo** [comment]
The feature is validated in Rancher master 691f4cbc

For the following newly added rke cluster, the image used for coredns is `rancher/coredns-coredns`
- k8s v1.13.5
- k8s v1.12.7

Note: for k8s v1.14.1-rancher-1-1 it uses `coredns/coredns`


For existing clusters in which Rancher was upgraded from previous version to master the image used for coredns is `coredns/coredns`

**Comment by jiaqiluo** [comment]
reopen the issue since we will mirror coredns image for k8s `v1..14.1-rancher1-2`

**Comment by alena1108** [comment]
@jiaqiluo the fix is available in latest master build

**Comment by jiaqiluo** [comment]
validate on Rancher: master b4bdcfdb and see the newly created rke cluster with k8s `v1.14.1-rancher1-2` uses the mirrored coredns image.
