### ISSUE TITLE
Monitoring API is not ready

### ISSUE THREAD

**Issue by DavidBajon** [rancher/rancher#19539]
Enabling the Monitoring on our first cluster worked fine. 

Now we try it to do it on a second cluster on the same rancher server and have issues with it.

The Dashboard will always show the following message:
'Monitoring API is not ready'

Even though the "cluster-monitoring" and "monitoring-operator" app is deployed.

I also tried to do this workaround https://github.com/rancher/rancher/issues/19209#issuecomment-479404791 but it didn't help.

Screens: 

![image](https://user-images.githubusercontent.com/22654354/55968873-23097300-5c7d-11e9-8582-aaf9d8ed1366.png)

![image](https://user-images.githubusercontent.com/22654354/55968877-26046380-5c7d-11e9-8043-1ff870e53bbd.png)

![image](https://user-images.githubusercontent.com/22654354/55968886-2997ea80-5c7d-11e9-9e69-853694a1ee2a.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.1` UI: `v2.2.19` |
|Route|`containers.index`|

**Comment by DavidBajon** [comment]
Sorry, this was an operator issue

**Comment by rockoo** [comment]
@DavidBajon have you figured out what was wrong? I can't seem to find an issue. Works on two clusters with no problem, but third one stays at  "Monitoring API is not ready"

**Comment by dolphyvn** [comment]
same issue, what was the fixed? Im using v2.2.3
