### ISSUE TITLE
Support DingTalk as a notifier

### ISSUE THREAD

**Issue by wenxinnnnn** [rancher/rancher#19537]
DingTalk, produced by Alibaba, is a free smart mobile office platform for global enterprises.

In China, many companies use DingTalk to work, but rancher does not support using DingTalk as a notifier.

**Comment by loganhz** [comment]
Related PRs:

https://github.com/rancher/types/pull/1076 
https://github.com/rancher/system-charts/pull/156 
https://github.com/rancher/rancher/pull/25251 
https://github.com/rancher/ui/pull/3737

**Comment by DoNotSayYes** [comment]
**Steps to test:**
1. Create a DingTalk Group
2. Add a Group Assistant to the group
3. Add a DingTalk notifier by using the assistant Webhook URL and the secret

**Results:**
A DingTalk notifier can be configured and receive alerts successfully

![image](https://user-images.githubusercontent.com/57614736/88773815-35325c00-d1b5-11ea-8c51-d035f2b83cd5.png)

**Comment by Zhang21** [comment]
Same requirement.

Can add Enterprise Webchat robot webhook to support like Dingtalk?

Thanks.
