### ISSUE TITLE
v2.2.1 CI/CD  Pipeline Trigger Rules  No event rule

### ISSUE THREAD

**Issue by chengxingyao** [rancher/rancher#19536]
![WX20190411-194924](https://user-images.githubusercontent.com/10667374/55955127-1bed5f80-5c93-11e9-8dc0-b70735f742ed.png)
v2.2.1 CI/CD  Pipeline Trigger Rules  No event rule

**Comment by tfiduccia** [comment]
@chengxingyao - Not sure what your issue is.  Can you please explain.  That box is for triggering the build.  The box next to it is for Do not trigger.

**Comment by deniseschannon** [comment]
If you are looking for event triggers for the pipeline, they are located here as a setting.

 https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/pipelines/#modifying-the-event-triggers-for-the-repository

You are looking ta the pipeline trigger rules, which is different: https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/pipelines/#trigger-rules
