### ISSUE TITLE
Grafana can't show Pod Current Legend

### ISSUE THREAD

**Issue by sunny0826** [rancher/rancher#19530]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
Project -> Workloads -> Pods -> Go to Grafana 

**Result:**
![image](https://user-images.githubusercontent.com/24563928/55925739-1cf5a100-5c41-11e9-8235-59d9159918b1.png)

the Grafana can not show Pod Current Legend!

**Other details that may be helpful:**
I am trying to create a new Monitoring under the Project. but it does not work. Can you tell me where it is set up?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):rancher/rancher
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):122/247
- Kubernetes version (use `kubectl version`):v1.11.5

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by deniseschannon** [comment]
@sunny0826 Project monitoring is actually disabled as of v2.2.2 cause of some issues, but when we add it back in, you enable it at the project level and can follow these directions: 

https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/monitoring/

**Comment by sunny0826** [comment]
> @sunny0826 Project monitoring is actually disabled as of v2.2.2 cause of some issues, but when we add it back in, you enable it at the project level and can follow these directions:
> 
> https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/monitoring/
@deniseschannon I just want to know why this Metrics didn't take effect.
When I use the Helm install Prometheus in the APPS in rancher, it is effective.
furthermore, the gafana is configured with this Metrics.but it does not work.

**Comment by loganhz** [comment]
Can you see workload or pod metrics in Rancher UI? Something like this

![image](https://user-images.githubusercontent.com/21168270/56346995-e944e900-61f5-11e9-836c-ef3c057c921e.png)

**Comment by sunny0826** [comment]
> Can you see workload or pod metrics in Rancher UI? Something like this
> 
> ![image](https://user-images.githubusercontent.com/21168270/56346995-e944e900-61f5-11e9-836c-ef3c057c921e.png)

Nope
![image](https://user-images.githubusercontent.com/24563928/56348369-dd0e5b00-61f8-11e9-9ffd-b21ca1743688.png)

**Comment by loganhz** [comment]
I guess it is an imported cluster? 

Can you look at the workload `exporter-kube-state-cluster-monitoring` under cattle-prometheus? Is it green?

Can you go to Prometheus UI -> Status -> Targets

And check if `cattle-prometheus/exporter-kube-state-cluster-monitoring` is up

![image](https://user-images.githubusercontent.com/21168270/56348617-6faefa00-61f9-11e9-93cd-dd627a14e7fd.png)

**Comment by sunny0826** [comment]
@deniseschannon yes,it is an imported cluster.I check the prometheus ,it is down ! what should I do ?
![image](https://user-images.githubusercontent.com/24563928/56349150-86a21c00-61fa-11e9-8aed-bfbec54bb0e6.png)

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/56349515-47c09600-61fb-11e9-824f-dfd54e1800cd.png)

Try this

**Comment by sunny0826** [comment]
I try add the selector,and  reinstall the monitoring.but lost a workload... I delete the selector,It recovered.
![image](https://user-images.githubusercontent.com/24563928/56351017-b3583280-61fe-11e9-8716-21367a8b914d.png)

**Comment by loganhz** [comment]
It's not a selector. There is an `show advanced` button and input it as extra param

**Comment by sunny0826** [comment]
!!! It works !!! thx !!! I love Rancher !
![image](https://user-images.githubusercontent.com/24563928/56352041-fe734500-6200-11e9-944e-c1663d5f3b6a.png)

**Comment by loganhz** [comment]
Thanks! @thxCode Please document it.
