### ISSUE TITLE
Backport: (SOME OF) Invalid server response (expected JSON, got garbage) for some API calls with Firefox/Chrome

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19547]
Backport https://github.com/rancher/rancher/issues/19524

**Comment by alena1108** [comment]
Can be tested with rc10

**Comment by davidnuzik** [comment]
@alena1108 I still see the issue for some of the issues mentioned in #19524
For example, when change password we get the "garbage data" `H4sIAAAAAAAA/wEAAP//AAAAAAAAAAA=`

So are we only fixing auth responses I presume? based on what I see in PR? or do we wish to fix all the problems?

**Comment by davidnuzik** [comment]
Affected areas examples:

logout `v3/tokens?action=logout`
change password `v3/users?action=changepassword`
delete a workload `v3/project/c-kn4w5:p-grgj8/workloads/deployment:nx:nginx` (although contains no Content so this is probably okay? has always been like this before just no gziped
and auth disable (this is probably fixed now and is being tested currently)

**Comment by davidnuzik** [comment]
I also noticed when I enable auth for Active Directory Content-Length used to be 0 is now 23

**Comment by vincent99** [comment]
0 bytes gzipped becomes not-zero bytes.

**Comment by davidnuzik** [comment]
Thanks I figured this was the case we just needed someone to confirm this.
We are hoping the UI doesn't rely on any proper json in server response in these areas. Based on our testing it doesn't appear to hurt anything.

**Comment by davidnuzik** [comment]
v2.2.2-rc10
I can confirm in the server resp headers Content-Type is now included (application/json) for auth responses.

![image](https://user-images.githubusercontent.com/45179589/55979743-c17ae180-5c47-11e9-8448-b2a8b8d9962f.png)
![image](https://user-images.githubusercontent.com/45179589/55979761-c8095900-5c47-11e9-95c9-5b10efe160df.png)

![image](https://user-images.githubusercontent.com/45179589/55979685-a0b28c00-5c47-11e9-8b6a-a3de24542b82.png)
![image](https://user-images.githubusercontent.com/45179589/55979698-a60fd680-5c47-11e9-9026-f613c6e76882.png)

NOTE: This does NOT affect other areas such as password changes, etc. These are still application/x-gzip

**Comment by davidnuzik** [comment]
Closing issue; is valied auth responses are now Content-Type: application/json
A separate issue will be created for the remaining issues for future consideration
