### ISSUE TITLE
Allow Nginx-Ingress To Be Exposed Via Service

### ISSUE THREAD

**Issue by rajha-korithrien** [rancher/rancher#19549]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
Simply use the Rancher UI to deploy a bare metal cluster and observe that the default ingress deployment puts a pod on each node and that configured ingress objects have the status.loadBalancer.ingress field set to a list of IP addresses for the physical host nodes. This is perfectly useful current behavior.

**Result:**
A useful desired behavior (when configured to do so) is to have the nginx instances be exposed via a Service with type=LoadBalancer, this would allow in cluster load balancers such as MetalLB to be able assign IP addresses from a pool that is not associated with the physical host network. The configuration point would be exposed in the yaml used to define a cluster in the Rancher UI
```
ingress: 
  provider: "nginx"
  exposeAsService: true
```
If exposeAsService is true then the ingress will be completely provisioned, but will not be reachable externally until the service gets an IP address and route setup by the in-cluster load balancer.

**Other details that may be helpful:**
Discussion of why exposing an ingress via a service is useful (clusters with MetalLB installed can use it)
https://github.com/danderson/metallb/issues/260#issuecomment-389667656

Related Rancher Issues:
https://github.com/rancher/rancher/issues/18275

Somewhat loosely related rancher issues:
https://github.com/rancher/rancher/issues/16764
https://github.com/rancher/rancher/issues/13828

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.0
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Rancher Deployed on BareMetal
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
BareMetal on top of RancherOS
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Docker version 18.06.2-ce, build 6d37f41
```

gz#10310

**Comment by alena1108** [comment]
@superseb I believe we have an issue filed somewhere for exposing nginx ingress controller via LB service

**Comment by WMP** [comment]
I need this to run ingress on VRRP ip: https://github.com/aledbf/kube-keepalived-vip ?
