### ISSUE TITLE
Return user to original context after workload edit

### ISSUE THREAD

**Issue by amherrington13** [rancher/rancher#19540]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
View a specific workload from within a project.  
Edit the workload and select Upgrade.

**Result:**
After selecting Upgrade, user is redirected back to the Workloads view page showing all workloads for the current project. It would be nice to be redirected to the original context. In this case, the specific workload view for which the update was applied.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher 2.x

**Comment by tfiduccia** [comment]
@deniseschannon - I agree with @amherrington13.  If you edit, after saving it should take you back to the view you came from.
