### ISSUE TITLE
[rancher-compose] rancher-compose is missing a "pull" command like docker-compose

### ISSUE THREAD

**Issue by bymodude** [rancher/rancher#1955]
I could not figure out how to get rancher-compose to pull a new image that was checked into the registry (deploying a service to rancher hosts using rancher-compose up, the latest image was not being pulled from the registry), I had to manually login to the rancher host and "docker pull" there. docker-compose has "pull", is there any equivalent for docker-compose?

**Comment by ibuildthecloud** [comment]
Working on it now.  Expect `rancher-compose pull` in the next release.

**Comment by ibuildthecloud** [comment]
The following has been added

1) A new Cattle API at /v1/pullTask.  The input parameters are

`image`: The image name to pull
`mode`:  `all` to pull on all hosts that match the scheduling labels. or `cached` to pull on hosts that match the scheduling labels and already have the image.
`labels`: The scheduling labels

2) `rancher-compose pull [--cached] [SERVICE...]`

Pulls all the images that match the services using the labels from the compose file.  By default it will do mode `all` but `--cached` will do mode `cached`.

3) `rancher-compose upgrade --pull ...`

Added a `--pull` to upgrade which will do a pull mode=cached before doing the update

4) `io.rancher.container.pull_image=always`

If this label exists on a container at will always happen before the container is created on any host.

**Comment by ibuildthecloud** [comment]
@sangeethah

**Comment by parabuzzle** [comment]
![selfie-1](http://i.imgur.com/ORskT3T.gif)

**Comment by sangeethah** [comment]
Tested with build from master - Sep 18 and rancher-compose version - v0-4-0-rc2

Following options are now supported and functional:
1) rancher-compose pull [--cached] [SERVICE...]
2) rancher-compose upgrade --pull ...
3) io.rancher.container.pull_image=always

Issues seen when testing these options are tracked in different tickets.

**Comment by donny-dont** [comment]
Is there an example of this functionality for adding it within Rancher Server? I tried both

```
my-stack:
  image: my-registry.com:5000/foo/bar
  ports:
  - 8888:8888/tcp
  labels:
  - "io.rancher.container.pull_image=always"
```

and

```
my-stack:
  image: my-registry.com:5000/foo/bar
  ports:
  - 8888:8888/tcp
  labels:
    io.rancher.container.pull_image: always
```

in a docker-compose.yml but neither seem to actually pull the updated image. We have some docker containers being built out by Drone and pushed into our private registry but the devs can't pull their changes without logging into the machine currently. Are there any gotchas with this functionality?

```
Rancher	v0.43.1
Cattle	v0.106.0
User Interface	v0.63.0
Rancher Compose	v0.5.0
```

**Comment by deniseschannon** [comment]
Have you checked `rancher-compose -v` to make sure you are running the right version of rancher-compose? 

Also, the containers won't automatically restart with the new image. You'd need to do something to trigger so that new containers spin up. When new containers spin up, then the image would be pulled.
