### ISSUE TITLE
Add check for cluster-scoped lifecycle handlers that are not cleaned up when a cluster is deleted

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19550]
We have a problem with cluster scoped lifecycle handlers. When the cluster is deleted, we need to remove their finalizers (bc the handlers will have been deleted). We do that in cluster_scoped_gc.go, but adding logic there is a manual process and handlers/resources can be missed.

See this issue for an example https://github.com/rancher/rancher/issues/19529.

This is pretty bad bc it causes things to get stuck when you delete a cluster. We need some automated way of detecting when there is a cluster-scoped lifecycle that does not have a corresponding cleanup in cluster_scoped_gc.go

One possible fix is to add a new function to the cluster scoped lifecycle handler that returns a function that will be run to cleanup finalizers when the cluster is deleted.

**Comment by cjellick** [comment]
another possible fix would be to add something in CI that would fail if it detected a cluster scoped lifecycle handler didnt have cleanup, but i think this woudl be harder

**Comment by jiaqiluo** [comment]
As per the conversation with @daxmc99, the validation did for the cluster namespace cleanup issue (https://github.com/rancher/rancher/issues/19529 and https://github.com/rancher/rancher/issues/19900) should be sufficient for closing this issue.
