### ISSUE TITLE
Custom cluster - system tool - cert rotate- error while running cert rotate command

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19556]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. On rancher v2.1.8. have a custom cluster. (Node - Amazon EC2 instance)
2. Run the command - `./system-tools config --url https://x.x.x.x/v3 --token "token-xxxxxxxxxxxxxx" --cluster c-lx67x` (system tools from : https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc7)
3. config file will be generated. Enter the access file name and file path. 
4. Run the command - `./system-tools cert rotate --url https://x.x.x.x/v3 --token "token-xxxxxxxxxxxxxx" --cluster c-lx67x --config c-lx67x`

**Expected Result:**
certs are rotated successfully.

**Actual Result:**
Error is seen - `WARN[0002] Failed to set up SSH tunneling for host [y.y.y.y]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [y.y.y.y] using SSH. Please check if the configured key or specified key file is a valid SSH Private Key. Error: Error configuring SSH: ssh: no key found `

Command and error:
```sowmyaviswanathan$ ./system-tools cert rotate --url https://x.x.x.x/v3 --token "token-xxxxxxxxxxxxxx" --cluster c-lx67x --config c-lx67x
INFO[0000] Setup rkeconfig for cluster [c-lx67x]        
INFO[0000] Get kubeconfig for cluster [c-lx67x]         
INFO[0000] Write temporary kubeconfig for cluster [c-lx67x] 
INFO[0000] Successfully wrote temporary kubeconfig file for cluster [c-lx67x] at [./kube_config_c-lx67x] 
INFO[0000] Fetching cluster [c-lx67x] full state from kubernetes 
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] Rotating Kubernetes cluster certificates     
INFO[0000] [certificates] Generating admin certificates and kubeconfig 
INFO[0001] [certificates] Generating etcd-x.y.z.x certificate and key 
INFO[0001] [certificates] Generating Kube Proxy certificates 
INFO[0001] [certificates] Generating Kube Controller certificates 
INFO[0002] [certificates] Generating Kube Scheduler certificates 
INFO[0002] [certificates] Generating Node certificate   
INFO[0002] [certificates] Generating Kubernetes API server proxy client certificates 
INFO[0002] Successfully Deployed state file at [./c-lx67x.rkestate] 
INFO[0002] Rebuilding Kubernetes cluster with rotated certificates 
INFO[0002] [dialer] Setup tunnel for host [y.y.y.y] 
WARN[0002] Failed to set up SSH tunneling for host [y.y.y.y]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [y.y.y.y] using SSH. Please check if the configured key or specified key file is a valid SSH Private Key. Error: Error configuring SSH: ssh: no key found 
WARN[0002] Removing host [y.y.y.y] from node lists 
FATA[0002] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [y.y.y.y] ```

**Other details that may be helpful:**


**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.1.8
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster

**Comment by sowmyav27** [comment]
Error `Failed to set up SSH tunneling for host [x.x.x.x]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access the service on /var/run/docker.sock. The service might be still starting up. Error: ssh: rejected: connect failed (open failed)` seen while doing it for a custom cluster, is related to this issue - https://github.com/rancher/rancher/issues/19555

**Comment by alena1108** [comment]
Instead of system-tools, cert rotation was backported to rancher rke/rancher. The feature can be tested with rancher v2.1.9-rc2. Closing this issue.
