### ISSUE TITLE
Content-Type application/x-gzip when change password

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19553]
Version: v2.2.2-rc8 and v2.2.2-rc10

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Change password, watch http POST

**Result:**
Server responds with Content-Type application/x-gzip. We expected application/json. Additionaally, response payload is gzip of 0 bytes and so we have gone from 0 bytes to 23 bytes.

In v2.2.2-rc7 and earlier (before we introduced gzip) we would get a response of 0 bytes in length and no Content-Type/Content-Encoding was provided. This resulted in things looking correct in browser dev tools (no JSON.parse errors, etc when inspect server response)

**Other details that may be helpful:**
The change of adding gzip to many areas when server responds with 0 bytes (then gets gzipped to become 23 bytes) is in many areas across the product now. Pipelines, monitoring, auth, etc. There are probably more. Based on discussions it sounds like we are okay with this change and browser dev tools showing errors when inspect server response.

**Comment by vincent99** [comment]
Can the chained gzip-per just not do anything if the data is 0 bytes?  It makes no sense to compress empty responses (and also those responses should be `204`s, and have no body at all...)

**Comment by rmweir** [comment]
> Can the chained gzip-per just not do anything if the data is 0 bytes? It makes no sense to compress empty responses (and also those responses should be `204`s, and have no body at all...)

Spoke through a different channel about this. Unfortunately, the logic which sets this code happens after the gzip handler and is not making a call to write or write header since it is an empty response.

**Comment by cjellick** [comment]
@rmweir to backport

**Comment by cjellick** [comment]
test

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc8

POST to change password is now like prior method, is of Content-Length 0 bytes and is application/json instead of gzip. This works correctly now.
