### ISSUE TITLE
system-tools cert rotate gives error for AWS EC2 and Azure cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19555]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Have an AWS EC2 cluster running in rancher v2.1.8.
2. run the following command
` ./system-tools cert rotate --url https://x.x.x.x/v3 --token "token-xxxxxxxx" --cluster c-xxxx` (system tools from : https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc7)

**Expected Result:**
certificates should be rotated successfully.

**Actual Result:**
Error is seen `WARN[0003] Failed to set up SSH tunneling for host [y.y.y.y]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access the Docker socket (/var/run/docker.sock). Please check if the configured user can execute `docker ps` on the node, and if the SSH server version is at least version 6.7 or higher. If you are using RedHat/CentOS, you can't use the user `root`. Please refer to the documentation for more instructions. Error: ssh: rejected: administratively prohibited (open failed) `

**Note:** Same error is observed when cert rotate is done for an Azure rke cluster.
Command and Error:
```
Sowmyas-MacBook-Pro:Downloads sowmyaviswanathan$ ./system-tools cert rotate --url https://x.x.x.x/v3 --token "token-xxxxxxxxx" --cluster c-xxxx
INFO[0000] Setup rkeconfig for cluster [c-xxx]        
INFO[0000] Get kubeconfig for cluster [c-xxx]         
INFO[0001] Write temporary kubeconfig for cluster [c-xxx] 
INFO[0001] Successfully wrote temporary kubeconfig file for cluster [c-xxx] at [./kube_config_c-xxx] 
INFO[0001] Fetching cluster [c-xxx] full state from kubernetes 
INFO[0001] Initiating Kubernetes cluster                
INFO[0001] Rotating Kubernetes cluster certificates     
INFO[0001] [certificates] Generating Kube Scheduler certificates 
INFO[0001] [certificates] Generating etcd-xxxx certificate and key 
INFO[0001] [certificates] Generating Kube Controller certificates 
INFO[0002] [certificates] Generating Kube Proxy certificates 
INFO[0002] [certificates] Generating Node certificate   
INFO[0002] [certificates] Generating admin certificates and kubeconfig 
INFO[0002] [certificates] Generating Kubernetes API server proxy client certificates 
INFO[0002] Successfully Deployed state file at [./c-xxx.rkestate] 
INFO[0002] Rebuilding Kubernetes cluster with rotated certificates 
INFO[0002] [dialer] Setup tunnel for host y.y.y.y
WARN[0003] Failed to set up SSH tunneling for host [y.y.y.y]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access the Docker socket (/var/run/docker.sock). Please check if the configured user can execute `docker ps` on the node, and if the SSH server version is at least version 6.7 or higher. If you are using RedHat/CentOS, you can't use the user `root`. Please refer to the documentation for more instructions. Error: ssh: rejected: administratively prohibited (open failed) 
WARN[0003] Removing host [y.y.y.y] from node lists 
FATA[0003] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [y.y.y.y] 
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.1.8
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted AWS EC2

**Comment by alena1108** [comment]
Instead of system-tools, cert rotation was backported to rancher rke/rancher. The feature can be tested with rancher v2.1.9-rc2. Closing this issue.
