### ISSUE TITLE
Backport: Add South Central US, Korea South, and Korea Central to AKS regions (#19475)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19562]
Backport #19475

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: v2.2.3-rc1

These regions are now added to the Location drop-down when creating an AKS cluster.

HTTP:
location: southcentralus
location: koreacentral
location: koreasouth

**Comment by davidnuzik** [comment]
v2.2.5
We now have access to these regions in Azure.

I tested again and confirmed my South Central US, Korea Central, and Korea South regions all work without any issues. All AKS clusters came up without any issues and the resources are all in the correct region.
