### ISSUE TITLE
Network services and Scheduler infra stacks show multiple versions available for upgrade

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#19567]
Version : Upgrade from Rancher v1.6.14 to v1.6.27-rc1

Steps:

1. Create a setup in v1.6.14
2. Create few user stacks
3. Upgrade to v1.6.27-rc1
4. After upgrade, Network services and Scheduler infra stacks show two versions available for upgrade as below:

Network services infra stack:
There are two versions available for upgrade v0.2.10 and v0.2.11
<img width="760" alt="Screen Shot 2019-04-11 at 3 02 14 PM" src="https://user-images.githubusercontent.com/18536626/56002631-0159bd00-5c78-11e9-840a-5a2d1ad0bfa7.png">

Scheduler infra stack: 
There are two versions available for upgrade v0.8.5 and v0.8.6
<img width="970" alt="Screen Shot 2019-04-11 at 3 13 51 PM" src="https://user-images.githubusercontent.com/18536626/56002637-061e7100-5c78-11e9-9d44-3a8cee62fd6a.png">

**Comment by prachidamle** [comment]
Set the maximum_rancher_version: v1.6.26 for the above two templates show that the older versions do not show up for upgrade.

**Comment by soumyalj** [comment]
Tested with updated catalog on v1.6.27-rc1
1. Create a setup in v1.6.14
2. Create few user stacks
3. Upgrade to v1.6.27-rc1

After upgrade, Network services and Scheduler infra stacks shows one version available for upgrade as below:
Network services infra stack:
<img width="931" alt="Screen Shot 2019-04-17 at 1 13 19 PM" src="https://user-images.githubusercontent.com/18536626/56317894-bb3aa880-6112-11e9-9afa-198ecf87625d.png">

Scheduler infra stack:
<img width="880" alt="Screen Shot 2019-04-17 at 1 13 32 PM" src="https://user-images.githubusercontent.com/18536626/56317928-d4dbf000-6112-11e9-9413-9d2d77d7a0a2.png">
