### ISSUE TITLE
Cattle node upgrade strategy should be some percentage

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#19568]
At the moment the cluster upgrade maxUnavailble is an absolute 1, when you have a large number of nodes this upgrade takes a really long time. We should set it to a percentage of the cluster since it isn't that impactful for it to go down.

**Comment by cloudnautique** [comment]
This should also be looked at for other daemonsets like the node exporter in monitoring stack.

**Comment by cloudnautique** [comment]
Without adjusting this, upgrades will take hours in larger clusters.

**Comment by deniseschannon** [comment]
@kinarashah Did this change as part of zero downtime cluster maintenance?

**Comment by kinarashah** [comment]
@deniseschannon Yeah, cattle-node-agent's upgrade strategy has been updated as a part of zero downtime feature #24062. 

About the (second comment)[https://github.com/rancher/rancher/issues/19568#issuecomment-483775966] for node exporter in monitoring stack, I'm not sure if this got updated with v2 changes
