### ISSUE TITLE
Cert Rotation - kube-apiserver certs did not rotate

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19569]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Have a DO rke cluster on rancher:v2.1.8.
2. run the following command
./system-tools cert rotate --url https://x.x.x.x/v3 --token "token-xxxxxxxx" --cluster c-xxxx (system tools from : https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc7)

**Expected Result:**
certs should be rotated and 10 years should have been added to the expiry date, in all the nodes.

**Actual Result:**
1. after running the cert rotate command, on running a cert info command with the system tools, gave the below output. `kube-apiserver` certs' did not rotate and certs' expiry did not get the 10 years.
```
INFO[0000] Check certificates Info for cluster [c-g8tvb]
--
INFO[0000]   Setup rkeconfig for cluster [c-g8tvb]
INFO[0001]   Get kubeconfig for cluster [c-g8tvb]
INFO[0001]   Write temporary kubeconfig for cluster [c-g8tvb]
INFO[0001]   Successfully wrote temporary kubeconfig file for cluster [c-g8tvb] at   [./kube_config_c-g8tvb]
INFO[0001]   Fetching cluster [c-g8tvb] full state from kubernetes
INFO[0002]   possible legacy cluster, trying to fetch certs from kubernetes
INFO[0002]   [certificates] Getting Cluster certificates from Kubernetes
INFO[0003]   [certificates] Successfully fetched Cluster certificates from   Kubernetes
INFO[0003]   Certificate [kube-apiserver] has expiration date: [2020-04-10 21:24:01 +0000   UTC]
INFO[0003]   Certificate [kube-controller-manager] has expiration date: [2029-04-08   21:45:16 +0000 UTC]
INFO[0003]   Certificate [kube-scheduler] has expiration date: [2029-04-08 21:45:17 +0000   UTC]
INFO[0003]   Certificate [kube-proxy] has expiration date: [2029-04-08 21:45:17 +0000   UTC]
INFO[0003]   Certificate [kube-node] has expiration date: [2029-04-08 21:45:17 +0000   UTC]
INFO[0003]   Certificate [kube-admin] has expiration date: [2029-04-08 21:45:17 +0000   UTC]
INFO[0003]   Certificate [kube-apiserver-requestheader-ca] has expiration date:   [2029-04-08 21:24:03 +0000 UTC]
INFO[0003]   Certificate [kube-apiserver-proxy-client] has expiration date: [2029-04-08   21:45:17 +0000 UTC]
INFO[0003]   Certificate [kube-etcd-134-209-170-141] has expiration date: [2029-04-08   21:45:17 +0000 UTC]
INFO[0003]   clean temporary kubeconfig for cluster [c-g8tvb]
```
2. `kube-apiserver.pem` on the control node, did not get new certs, certs' expiry date did not get the 10 years.
3. `kube-node.pem` and  `kube-proxy.pem` on the worker node, did not get new certs, certs' expiry date did not get the 10 years. - issue tracked in https://github.com/rancher/rancher/issues/19620

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.1.8
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO cluster - hosted

**Comment by aleksey005** [comment]
I also have the same error

`2019/04/13 07:43:15 [ERROR] API error response 422 for PUT /v3/clusters/c-25d48?_replace=true. Cause: json: cannot unmarshal string into Go struct field RotateCertificates.services of type []string`

when trying to save cluster

`Validation failed in API: Cluster spec conversion error
`

**Comment by sangeethah** [comment]
Instead of system-tools, cert rotation was backported to rancher rke/rancher. The feature can be tested with rancher v2.1.9-rc2. Closing this issue.
