### ISSUE TITLE
Expiry Rancher Token

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#19572]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement/question

**Steps to reproduce (least amount of steps as possible):**
Run this command to add host to client or using Rancher API to add host to cluster. 

docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.2.1 --server https://URL --token 9nbnhpbzx7tcbfk --ca-checksum b93b8de5dc981ffe4c3774c960e --etcd --controlplane --worker

**Result:**
Is this one time token? If not, is there a way to expiry it ?

**Other details that may be helpful:**
This token got log into audit.log file and may be other log files. If support ask for log file and token is not expiry, It could expose token by sending log file to support

**Comment by vincent99** [comment]
The registration command/token is good for the life of the cluster, unless deleted (`/v3/clusters//<cluster id>/clusterregistrationtokens`)

**Comment by panho66** [comment]
@vincent99  thanks
