### ISSUE TITLE
Rancher2.1.8 always crashing after leaking memory for few hours to few days

### ISSUE THREAD

**Issue by 3pns** [rancher/rancher#19574]
**What kind of request is this:** bug 

**Steps to reproduce :**
- install 1 rancher server and provision 1 self hosted seperate node.
- run around 5 to 10 deployments using 10% of the capacity of one node
- wait few hours to few days until rancher/rancher will crash

**Result:** (preview of the stack I will send you)

~~~ bash
rancher-rancher    | 2019-04-11 23:29:55.898997 I | mvcc: finished scheduled compaction at 47315130 (took 649.352156ms)
rancher-rancher    | 2019-04-11 23:30:37.387517 I | wal: segmented wal file /var/lib/rancher/etcd/member/wal/0000000000000605-0000000002febd94.wal is created
rancher-rancher    | 2019-04-11 23:30:48.561002 I | pkg/fileutil: purged file /var/lib/rancher/etcd/member/wal/0000000000000600-0000000002fd11f5.wal successfully
rancher-rancher    | 2019-04-11 23:34:55.257176 I | mvcc: store.index: compact 47315933
rancher-rancher    | 2019-04-11 23:34:55.931099 I | mvcc: finished scheduled compaction at 47315933 (took 652.749827ms)
rancher-rancher    | E0411 23:39:44.320144       7 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
rancher-rancher    | 2019-04-11 23:39:55.287031 I | mvcc: store.index: compact 47316738
rancher-rancher    | 2019-04-11 23:39:55.979831 I | mvcc: finished scheduled compaction at 47316738 (took 655.52015ms)
rancher-rancher    | 2019-04-11 23:44:55.336104 I | mvcc: store.index: compact 47317541
rancher-rancher    | 2019-04-11 23:44:56.028631 I | mvcc: finished scheduled compaction at 47317541 (took 642.999499ms)
rancher-rancher    | E0411 23:49:23.419009       7 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
rancher-rancher    | 2019-04-11 23:49:55.396867 I | mvcc: store.index: compact 47318347
rancher-rancher    | 2019-04-11 23:49:56.086485 I | mvcc: finished scheduled compaction at 47318347 (took 644.301885ms)
rancher-rancher    | 2019-04-11 23:54:55.446515 I | mvcc: store.index: compact 47319150
rancher-rancher    | 2019-04-11 23:54:56.105789 I | mvcc: finished scheduled compaction at 47319150 (took 638.523444ms)
rancher-rancher    | 2019/04/11 23:55:43 [INFO] Running cluster events cleanup
rancher-rancher    | 2019/04/11 23:55:43 [INFO] Done running cluster events cleanup
rancher-rancher    | 2019/04/11 23:55:46 [INFO] Updating catalog gitlab
rancher-rancher    | 2019/04/11 23:55:46 [INFO] Updating catalog bitnami
rancher-rancher    | 2019/04/11 23:55:47 [INFO] Updating catalog helm-incubator
rancher-rancher    | 2019/04/11 23:55:48 [INFO] Updating catalog helm
rancher-rancher    | 2019/04/11 23:55:59 [INFO] Catalog sync done. 0 templates created, 3 templates updated, 0 templates deleted
rancher-rancher    | 2019/04/11 23:56:35 [INFO] Catalog sync done. 0 templates created, 8 templates updated, 0 templates deleted
rancher-rancher    | fatal error: runtime: out of memory
rancher-rancher    | 
rancher-rancher    | runtime stack:
rancher-rancher    | runtime.throw(0x58063f9, 0x16)
rancher-rancher    | 	/usr/local/go/src/runtime/panic.go:608 +0x72
rancher-rancher    | runtime.sysMap(0xc144000000, 0x4000000, 0xb7302f8)
rancher-rancher    | 	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
rancher-rancher    | runtime.(*mheap).sysAlloc(0xb715a20, 0x4000000, 0x7fe40b432598, 0xc01f7e3e58)
rancher-rancher    | 	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
rancher-rancher    | runtime.(*mheap).grow(0xb715a20, 0x51, 0x0)
rancher-rancher    | 	/usr/local/go/src/runtime/mheap.go:920 +0x42
rancher-rancher    | runtime.(*mheap).allocSpanLocked(0xb715a20, 0x51, 0xb730308, 0x20301600000000)
rancher-rancher    | 	/usr/local/go/src/runtime/mheap.go:848 +0x337
rancher-rancher    | runtime.(*mheap).alloc_m(0xb715a20, 0x51, 0x410100, 0x7fe4136a9100)
rancher-rancher    | 	/usr/local/go/src/runtime/mheap.go:692 +0x119
rancher-rancher    | runtime.(*mheap).alloc.func1()
rancher-rancher    | 	/usr/local/go/src/runtime/mheap.go:759 +0x4c
rancher-rancher    | runtime.(*mheap).alloc(0xb715a20, 0x51, 0x7fe412010100, 0x8)
rancher-rancher    | 	/usr/local/go/src/runtime/mheap.go:758 +0x8a
rancher-rancher    | runtime.largeAlloc(0xa0510, 0xc01f7e0001, 0x458bea)
rancher-rancher    | 	/usr/local/go/src/runtime/malloc.go:1019 +0x97
rancher-rancher    | runtime.mallocgc.func1()
rancher-rancher    | 	/usr/local/go/src/runtime/malloc.go:914 +0x46
rancher-rancher    | runtime.systemstack(0xc00d894d80)
rancher-rancher    | 	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
rancher-rancher    | runtime.mstart()
rancher-rancher    | 	/usr/local/go/src/runtime/proc.go:1229
rancher-rancher    | 
rancher-rancher    | goroutine 79071 [running]:
~~~~

**Other details that may be helpful:**

I will send an email with the full crash log to the security at rancher email as it may contain sensible information. Please note these memory leaking issues resulting into crash are not new and they only concern rancher/rancher, the applications running on the nodes are running perfectly fine.

**Environment information**
- Rancher version: image: rancher/rancher:v2.1.8
- Installation option: single install using the docker image
- OS: CoreOS Rhyolite 2023.5.0

**Cluster information**
- Cluster type : Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM for rancher master with 2vCPU and 8GB of Ram and one node with 8cores and 32GB Ram.
- Kubernetes version : Version v1.13.4 according to Rancher UI, 

- Docker version (use `docker version`):
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:16:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:16:31 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by cjellick** [comment]
HI,

We're taking a look.

**Comment by dramich** [comment]
Hey @3pns, based off the logs and what I have seen previously with catalog update memory consumption, when processing 4 catalogs rancher has a huge memory spike which in turn causes the OOM error and the crash. 
Some things you can consider is turn off some of the catalogs if they aren't being used. Run a larger instance if all the catalogs are required or upgrade rancher. With version 2.2.x we had a huge rework of how catalogs were handled and this shouldn't be an issue. We have 2.2.2 coming out sometime this week which is what I would suggest upgrading to.

**Comment by 3pns** [comment]
@dramich @cjellick , thank you for the looking at the logs, I will proceed to upgrade to 2.2.2 once it's released and let you know wether the crashs are gone, if it doesn't fix the crashs I will remove the extra catalog.

**Comment by cjellick** [comment]
Based on @dramich 's assessment, I'll assign this over to QA for testing

**Comment by jiaqiluo** [comment]
The enhancement is validated on v2.2.4-rc1

I run Rancher `v2.1.8` and `v2.2.4-rc1` on two identical VM (t2.large, 2 vCPU, 8GB RAM )

For both of them:
- add a single-node custom cluster (t2.xlarge, 4 vCPU, 16 GB RAM)
- enable catalogs `Helm Stable` and `Helm Incubator`
- add catalogs  `bitnami` (https://charts.bitnami.com) and `gitlab` (https://charts.gitlab.io)
- add 5 more catalogs (duplicates of https://git.rancher.io/charts)
- deploy some workloads and catalog apps in the custom cluster
- run `docker stats`  to track Rancher's memory usage
- run `docker logs` to track Rancher's log in debug mode
- on the catalog app's launch page, click `Refresh` to force refreshing catalogs 
- meanwhile, check the memory usage and logs 
<img width="1401" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57816451-33a38200-7730-11e9-9fe4-607090de26a2.png">

<img width="1419" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57816179-3c478880-772f-11e9-8ba4-ffd79b36fd0b.png">


Results:
- `v2.1.8` uses about 28% memory when idle, about 50% when refreshing catalogs
- `v2.2.4-rc1` uses about 12% memory when idle, about 30% when refreshing catalogs

Also, Rancher skips the catalog that has no changes by comparing the hash of the helm index file or git repo change, which makes it harder for me to reproduce the OOM crash.
The following log demonstrates this.
```
2019/05/15 22:36:53 [DEBUG] Catalog catalog-2 is already up to date
2019/05/15 22:36:53 [DEBUG] Catalog catalog-5 is already up to date
2019/05/15 22:36:53 [DEBUG] Catalog catalog-3 is already up to date
2019/05/15 22:36:53 [DEBUG] Catalog catalog-4 is already up to date
2019/05/15 22:36:53 [DEBUG] Catalog library is already up to date
```

per to the conversion with @erikwilson, the tests above should be sufficient to validate the enhancement around the catalog feature and to close the issue.

**Comment by alena1108** [comment]
We've run several test for 2.2.4 RCs on our side and didn't observe memory leak. To be 100% positive, @3pns we'd need your help with validation on your end. It can be done either with the latest v2.2.4 RC, or - if you feel more comfortable testing on the official release - once v2.2.4 ships

**Comment by 3pns** [comment]
@alena1108 I will upgrade to 2.2.4 once it is released and make a feedback about it.
Regarding the v2.2.2, I checked and it seems my rancher is running for 11 days straight without any crash, the restart on may 17 if I recall was an OS update and not a rancher crash. I didn't remove any catalog so it seems there was an improvement about the way the catalogs are handled as @dramich said.

**Comment by alena1108** [comment]
> Regarding the v2.2.2, I checked and it seems my rancher is running for 11 days straight without any crash, the restart on may 17 if I recall was an OS update and not a rancher crash. I didn't remove any catalog so it seems there was an improvement about the way the catalogs are handled as @dramich said.

thank you for the update @3pns. Based on your testing and observations, I'm going to close the issue for now. Please reopen it if you hit it again.
