### ISSUE TITLE
UI Monitoring: Cannot increase time when have Custom timeframe

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19588]
Version: v2.2.2-rc-x12
Version v2.2.20 (Pre-existing issue)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable monitoring
- Set a custom time range for any of the metrics. In my case the last 2 minutes up to current.
- Wait a few mins. Now change the time scale so we can include more recent time (increase time to newer)

**Result:**
You cannot increase the time to a higher (newer) value unless you manually refresh the whole page.
![image](https://user-images.githubusercontent.com/45179589/56061252-bdb98e80-5d1d-11e9-9b01-d873cef940a7.png)
As pictured above, current time is 12:20pm but I am not allowed to increase time to 12:20pm for my custom range.

Try hitting the blue refresh arrow and still cannot. (Must manually refresh the whole page)

**Comment by davidnuzik** [comment]
@loganhz just wanted to verify that it is expected to not be able to set custom time with seconds. I think it's okay to not have that granularity.

Otherwise this is working as expected now. I can close the issue once I hear back from you.

**Comment by loganhz** [comment]
@davidnuzik seconds should be hidden in the time picker.

**Comment by davidnuzik** [comment]
I can confirm seconds have been removed as well now.

![image](https://user-images.githubusercontent.com/45179589/56311939-fbdef580-6103-11e9-81b5-57432886d884.png)

This is otherwise working as expected now. I encounter no issues with the change to remove seconds.

Refer to this comment to see my test results (passed) for the fix to increase custom timeframe: https://github.com/rancher/rancher/issues/19588#issue-432711249
