### ISSUE TITLE
UI:Show kiali graph in Rancher

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19581]
UI for https://github.com/rancher/rancher/issues/19580

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/7/19)

This has already been validated per the UI Istio test plan.
I tested via the recommended method by using bookinfo Istio example app. We generated traffic with this app and confirmed we can see the flows. We basically see the same thing as in the Kiali UI (it looks like an iframe or similar).

This is working as expected and testing will continue as myself and the rest of the team tests Istio (Service Mesh) further.
