### ISSUE TITLE
VMware 6.7 GuestOS is incorrect

### ISSUE THREAD

**Issue by msnelling** [rancher/rancher#19584]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a new vanilla vSphere node template.
2. Create a new cluster based on the above template.
3. Open the vSphere web console.
4. Select the new cluster node.

**Result:**
You will see the following warning.
`The configured guest OS (Other Linux (64-bit)) for this virtual machine does not match the guest that is currently running (Other 4.x or later Linux (64-bit)). You should specify the correct guest OS to allow for guest-specific optimizations`

**Other details that may be helpful:**
vSphere 6.7 U1
The correct guestOS type should be `other4xlinux-64`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.8
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider (vSphere)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 2 CPU, 4096 MB
- Kubernetes version (use `kubectl version`):

```
N/A
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

gz#14772

**Comment by dbason** [comment]
This is also occurring on 2.4.x with a RHEL 7 guest.  When manually cloning the VM the Guest OS is correctly set to RHEL 7.  When the VM is created using the RKE node driver in Rancher the Guest OS is set to Other Linux

**Comment by luthermonson** [comment]
@dbason this is an old issue and should be avoided now with the template cloning process and is only still a thing today in the legacy boot2docker setup: https://github.com/rancher/machine/blob/b14d204b923fdfbdc17be0ff5ef949f8b0601fd9/drivers/vmwarevsphere/create.go#L98

could you check your vmxt file and see if it's explicitly defining the guest os? if you can just post that file we can take a look but the clones i did from say nodes imported from the ubuntu ova all came with Ubuntu Linux 64-bit and if you look at the clone process you can see no code we have to overwrite that guestid.

**Comment by luthermonson** [comment]
found it... we USED to do this: https://github.com/rancher/machine/commit/722ccc7d81bf56d2b094aea8cf3457071a3b638a

it's been fixed in later versions.

**Comment by dbason** [comment]
Closing seeing as this is fixed in later versions.
