### ISSUE TITLE
Replacing a Rancher Management node should work ... doesn't.

### ISSUE THREAD

**Issue by diranged** [rancher/rancher#1958]
It seems that if you replace a Rancher Management node (and you only have one), the Rancher Agent nodes will start to fail.

In our case, I tested by doing the following:

* Set up a Rancher Management node named `rancher-i-1abdk42.hosts.mydomain.com` with Amazon RDS hosting the MySQL database.
* Point `rancher.corp.mydomain.com` to `rancher-i-1abdk42.hosts.mydomain.com` via a CNAME.
* Launch Rancher Agent nodes and point them to `rancher.corp.mydomain.com`
.. success

Then, for the test:

* Terminate `rancher-i-1abdk42.hosts.mydomain.com` abruptly, and launch new host.
* New host `rancher-i-abcdefg.hosts.mydomain.com` comes up and connects to the RDS database successfully, but cannot start the go-machine-engine thing because `rancher.corp.mydomain.com` is pointing to the old dead hostname.
* Update the DNS record ... wait 5 minutes.
* New Rancher Management host is up and happy..

At this point, the Rancher Agent nodes go into a loop where they start up, launch their internal agent, and then die.. then restart, over and over and over again.

We're running the latest `v0.35.0` management server:
`rancher/server      latest              0b044c7480ea        2 days ago          519.4 MB`

For some reason the `latest` tag of the `rancher/agent` points to `0.7.9`, but once our initial `rancher/agent:latest` process starts up, it properly pulls down the `0.8.1` release and starts a second agent (_weird!_):
```
rancher/agent       v0.8.1              26dd86f4d9cd        12 days ago         365.1 MB
rancher/agent       latest              8def006f0d7a        3 months ago        372.4 MB
rancher/agent       v0.7.9              8def006f0d7a        3 months ago        372.4 MB
```

**Comment by sangeethah** [comment]
Tested with server version - v0.37.0-rc1

Had a setup with 2 hosts that had multiple instances running and had 1 LB agent.

Rebooted rancher-server. This resulted in rancher-server getting a new ip address in my case. Rancher server was an Ubuntu instance in GCE.

After this hosts went into "reconnecting" state.

Did host registration again to set the ip address to the current rancher-server ip address.
Got the rancher-agent command to add custom host from UI and execute this on both the hosts.

Host get to "active" state.

Able to start new containers on the host.
Able to stop existing containers on the host , which restarts on service reconcile.
LB service continues to work.
Scale up Lb service . New LB agent is also functional.
