### ISSUE TITLE
Cluster Owner is not able to deploy catalog apps 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19589]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. As an admin, create a cluster (rke DO).
2. Add authentication in Rancher example: Github.
3. Add another github user(say user1) as the cluster owner for the cluster created in step 1.
4. As an admin, create a project in the cluster.
5. As the github user - user1, deploy catalog app in project created in step 4.

**Expected Result:**
Cluster owner user should be able to create and deploy a catalog app.

**Actual Result:**
Cluster owner is not able to create a catalog app.
Error - `apps.project.cattle.io is forbidden: User "u-75s76v6b2h" cannot create resource "apps" in API group "project.cattle.io" in the namespace "p-hm6x5"
`

**Note:**
If the Cluster owner creates a Multicluster app in the project created in Step 4, He is not able to list the app under `Apps` but he is able to view the app under `Workloads`. 
Error in response - `{"baseType":"error","code":"Forbidden","message":"apps.project.cattle.io \"app03-p-b2sv5\" is forbidden: User \"u-75s76v6b2h\" cannot get resource \"apps\" in API group \"project.cattle.io\" in the namespace \"p-b2sv5\"","status":403,"type":"error"}` 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.2.2-rc-x12
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE cluster DO
- Kubernetes version (use `kubectl version`):

```
v1.13.5
```

- Docker version (use `docker version`):

```
18.9.4
```

**Comment by sangeethah** [comment]
This issue is NOT reproducible in v2.1.8.
This issue is reproducible in v2.2.1.

**Comment by mrajashree** [comment]
When a user is added to a cluster, we create a clusterroletemplatebinding, and the controller for crtb creates rolebindings for this user to grant access to them to project level resources in that cluster including apps, from [here](https://github.com/rancher/rancher/blob/release/v2.2/pkg/controllers/management/auth/crtb_handler.go#L155)
But in this case, the project is created in the cluster after the user is added as cluster-owner, and we don't seem to have the corresponding logic on project creation.

**Comment by jiaqiluo** [comment]
I met the same bug with another approach in v2.2.5-rc8, HA setup 

- as the global admin, enable Github auth
- as Github user1, create an RKE Azure cluster
- as the global admin, add a project p1 in the cluster 
- as user1, go to the project p1, try to deploy an app 

Results:
- the following error shows in the UI
```
apps.project.cattle.io is forbidden: 
User "u-4cnrgx47ty" cannot create resource "apps" in API group "project.cattle.io" in the namespace "p-vwfwx": RBAC: [clusterrole.rbac.authorization.k8s.io "c-877c9-clustermember" not found, clusterrole.rbac.authorization.k8s.io "c-877c9-clusterowner" not found]
```

**Comment by rmweir** [comment]
I believe it is possible to repro/test this while just using local auth, steps are in https://github.com/rancher/rancher/issues/15819

**Comment by sowmyav27** [comment]
**Verified on master-head - Commit id: `85dedb19b`**

**Steps:**

1. As an admin, create a cluster (rke DO).
2. Add authentication in Rancher example: AD Auth.
3. Add another AD user(say user1) as the cluster owner for the cluster created in step 1.
4. As an admin, create a project in the cluster.
5. As the AD user - user1, deploy catalog app in project created in step 4.
6. User is able to deploy a catalog app.
