### ISSUE TITLE
Catalog APP - 404 error when cloning an app if the catalog is deleted 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19593]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- add a cluster
- go to the `default` project
- add a catalog
- deploy an app using the catalog
- delete the catalog
- clone the app
<img width="728" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/56071514-f79d8b80-5d43-11e9-9ef7-088c81a73ad3.png">
 

**Result:**
Rancher shows the following error
<img width="987" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/56071516-fb311280-5d43-11e9-9e4e-e5ba99727f7a.png">

**Other details that may be helpful:**
- clicking the option `rollback` or `upgrade` will NOT  show the same error page  

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.2-rc-x12
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by deniseschannon** [comment]
@tfiduccia can you let me know if this reproduces on a v2.1.x setup?

**Comment by tfiduccia** [comment]
Version - 2.1.0
I was able to reproduce this 2.1.0 and this has probably been an issue since we originally deployed.  If the Catalog has been removed the clone and upgrade options should be dimmed and not clickable.

**Comment by tfiduccia** [comment]
Related issue: https://github.com/rancher/rancher/issues/18197

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/31/19)

I can confirm the same findings as Jack found in the backport issue.
Upon deleting the catalog then trying to clone from the app menu I don't get a 404 error, instead I get a growl error:
![image](https://user-images.githubusercontent.com/45179589/58720008-e78a4b80-8385-11e9-82c4-798f49f24a0f.png)

If the page is refreshed (or you navigate to another cluster and then back to this cluster) then the menu options are no longer available (to clone/upgrade) and there is a message "Catalog Template not found" in gray where version / upgrade available information goes.
![image](https://user-images.githubusercontent.com/45179589/58720073-0e488200-8386-11e9-917d-c1f60307b5c8.png)

What I am confused about is the Rollback option. I can still rollback - if I choose to roll back and opt to "Delete and recreate resources if needed during the rollback" then this will fail the logs will complain that catalogtemplateversions.management.cattle.io "(CATALOG_HERE)" not found
I think we should fix that.

**Comment by davidnuzik** [comment]
Same issue on HA with Multi-Cluster apps -- we should be hiding "Rollback" option there as well.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/6/19)

The Rollback menu option has now been removed. The issue is now resolved. See my prior comment here which validates checking the other respective areas: https://github.com/rancher/rancher/issues/19593#issuecomment-497775000

![image](https://user-images.githubusercontent.com/45179589/59067004-460f6800-8865-11e9-96b1-a7baeac7c1e6.png)
