### ISSUE TITLE
failure to launch k8s cluster when ipv6 disabled (flannel as network provider)

### ISSUE THREAD

**Issue by zbialik** [rancher/rancher#19597]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):** 
Deploy kubernetes cluster using flannel as network provider and with ipv6 disabled on all hosts.

**Result:**
Containers stuck in 

**Other details that may be helpful:**
I am deploying a k8s cluster deployed using `Rancher v2.1.7` (backed by `flannel`)

I am trying to run `Kubernetes v1.11.8`, which uses the following flannel-relevant system images:
- `flannel: rancher/coreos-flannel:v0.10.0`
- `flannel_cni: rancher/coreos-flannel-cni:v0.3.0`

When I try to initialize a k8s cluster using flannel, I get a ton of pods failing to create with the following message from `kubectl describe pod ${POD_NAME}`:

`Warning  FailedCreatePodSandBox  1m (x4 over 1m)   kubelet, 10.15.2.240  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "12345678910" network for pod "kube-dns-123456-abc4y": NetworkPlugin cni failed to set up pod "kube-dns-123456-abc4y_kube-system" network: open /proc/sys/net/ipv6/conf/eth0/accept_dad: no such file or directory, failed to clean up sandbox container "12345678910" network for pod "kube-dns-123456-abc4y": NetworkPlugin cni failed to teardown pod "kube-dns-123456-abc4y_kube-system" network: failed to get IP addresses for "eth0": <nil>]`

I have ipv6 disabled on my k8s nodes and don't have problems booting up a k8s cluster with another network provider (like Calico).

When I enable ipv6, I am able to bootup the cluster. However I don't want to have to do this. 

I read that this issue was fixed in the latest release of containernetworking/plugins: v0.7.0
- [relevant issue notes](https://github.com/coreos/flannel/issues/936)
- [fix notes](https://github.com/containernetworking/plugins/pull/62)
- [release notes](https://github.com/containernetworking/plugins/compare/v0.6.0...v0.7.0)

Is this going to get supported in a new release of flannel-cni? Since I use rancher for my k8s cluster deployments, I have to pretty much rely on the implementation of the flannel-cni docker container.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher:v2.1.7`
- Installation option (single install/HA): HA 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `Custom`
- Machine type: `AWS EC2 (t2.large)`
- Kubernetes version: 

```
v1.11.8
```

- Docker version (use `docker version`): 

```
v1.12.6
```

**Comment by figaw** [comment]
We had the same experience, running CentOS 7 machines, installing with Rancher. If we enabled IPv6, all pods came live.

We also had to configure 
```
network:
    plugin: flannel
    options:
        flannel_iface: eth1
 ```
for namespaces not to be stuck in `terminating`.
