### ISSUE TITLE
MultiAPP - cannot see the multiApp if the catalog used is deleted

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19592]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- add a catalog
- deploy a multiple cluster App using that catalog
- delete the catalog
- click on the `Apps` option in global view 
<img width="1415" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/56071030-6973d600-5d40-11e9-9919-768665815430.png">

**Result:**
The UI shows 404 error
<img width="713" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/56070972-097d2f80-5d40-11e9-8ea5-37204e97d6f1.png">

**Other details that may be helpful:**
- Somehow the UI is checking if the catalog still exists for the `Apps`
-  This issue does not happen to regular apps in projects, ie. the UI does not crash if the catalog used for an app is deleted. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.2-rc-x12

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by gabrielcalderon** [comment]
I ran into this same issue with Rancher 2.2.1.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/31/19)

I can confirm the same findings as Jack found in the backport issue. This is working as expected now.

![image](https://user-images.githubusercontent.com/45179589/58724825-700ee900-8392-11e9-8901-1107ce9552aa.png)

When I delete the catalog I can still navigate to "Apps" at the global level. I will see the app mentions "Catalog Template not found" in the version info/update area. Rolling back does not work but this is already reported in this issue and will be tracked there: #19593 
That issue has a comment that mentions there is a problem with Roll back for multi-cluster apps as well.
