### ISSUE TITLE
Should show alert group even not alert rule under that group

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#19599]
Version: master
Reproduce status:
1. create an alert group
2. create an alert rule under that group
3. only delete the alert rule
4. both alert group and alert rule disappear in the UI
5. the legacy alert group will affect backend to recycle the alertmanager app, because user won't see any alert group/rule in the UI but the app not recycle.

┆Attachments: <a href="https://rancher.atlassian.net/secure/attachment/10205/image-20190427-014240.png">image-20190427-014240.png</a>

**Comment by davidnuzik** [comment]
@loganhz @westlywright I'm not entirely sure if this is related, but now I seem to run into situations where I occasionally see the gorups listed twice such as seen below. It is more common to run into it if have 2 or more clusters and switch between them on alerts page.

Is this possible related? Should I re-open this issue for investigation or open a new bug? Thanks

![image](https://user-images.githubusercontent.com/45179589/56766752-fd8d6680-675e-11e9-8339-9799af5eb360.png)

The HTTP looks correct -- my guess is this is something happening in the DOM/JS ?

**Comment by loganhz** [comment]
@davidnuzik it's another issue. But I think we can use this ticket. PR submitted.

**Comment by jira-sync-svc** [comment]
➤ wes commented:

Available in v2.2.3-rc3

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: v2.2.3-rc3

I no longer observe the issue I saw where I see extra groups listed especially when switch between clusters.

For the main issue, I seem to be encountering a problem. I cannot delete my rule under my custom group. I get a 404 not found error upon attempt DELETE action.

!image-20190427-014240.png|width=288,height=142!

{"baseType":"error","code":"NotFound","message":"clusteralertrules.management.cattle.io \"car-vvdpb\" not found","status":404,"type":"error"}Basically just follow the steps to reproduce to encounter the issue. The only error I see in the browser console is that the 404 error happened upon HTTP DELETE request for my rule.

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc3

I followed the steps to test again and was able to delete my rule under my alert group but it still shows up in the UI.

I have to manually refresh the UI to see the alert disappear.

![Screen Shot 2019-04-30 at 11 10 16 AM](https://user-images.githubusercontent.com/45179589/56983486-972a8e80-6b38-11e9-9bda-867fd371e549.png)

Finally is removed after manually refresh the cluster Alerts page.

![image](https://user-images.githubusercontent.com/45179589/56983531-b88b7a80-6b38-11e9-802a-02b2aca792f3.png)

No browser errors, DELETE function is working now, but I don't think I should have to manually refresh the UI to see the rule disappear.

**Comment by loganhz** [comment]
@davidnuzik It should be fixed in v2.2.3-rc4 . Could you try that please?

**Comment by davidnuzik** [comment]
Will do. This is my fault I looked at created date for PR not the date it was actually merged in.

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc4

You can now successfully delete any/all rules under an alert group. An alert group can have zero rules and you can later add rules back in without any issues.

Alerting is not working (alert manager won't deploy) so I could not test alerting notifications but the core issue here in this issue is resolved. I created issue #19912 to track that.
