### ISSUE TITLE
UI:New Monitoring Prometheus PVC doesn't work with OpenEBS

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19608]
UI for https://github.com/rancher/rancher/issues/19410

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/7/19)

I can confirm that when monitoring is enabled it will now automatically set this answer:
`prometheus.persistent.useReleaseName` = `true`
You will see it added after you enable monitoring for cluster _or_ project level monitoring.

This essentially shortens the name of the `prometheus-project-monitoring-db-prometheus-project-monitoring-0` which is the issue that was observed here #19410
I confirmed that this indeed resulted in the shortening of that name and thus this should resolve the issue with OpenEBS. 
The name is now about as short as `prometheus-project-monitoring` and all  names stay under the 63 char limit OpenEBS has. This should resolve the issue.
