### ISSUE TITLE
Backport:Parsing issue with answers.yaml in UI

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19605]
https://github.com/rancher/rancher/issues/18196

**Comment by tfiduccia** [comment]
@loganhz - I'm not sure what is going on with this issue.  There is no milestone, no devs were assigned.  I'm not even sure who is supposed to review since Wes is not assigned either?

**Comment by davidnuzik** [comment]
This was checked in master in https://github.com/rancher/rancher/issues/18196#issuecomment-483839902

I tested again and can confirm that we can now view answers for git based chart apps without any issues. I do not observe any issues in the browser dev console and tried deploying some of these apps and was successful.
