### ISSUE TITLE
MongoDB Cluster Fails to Deploy

### ISSUE THREAD

**Issue by jlambright** [rancher/rancher#19603]
Many people have ran into issues with: 

` (Failed to allocate instance [container:1i742]: Bad instance [container:1i742] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [instanceReservation: 1, instanceReservation: 1, 27017:27017/tcp portReservation, instanceReservation: 1].)`

Issue rancher/rancher#10384  was closed before any real investigation was done. So here I am, another person with a three node rancher cluster, seeing the same issues. Can we get some guidance on how to correct this?

**Comment by deniseschannon** [comment]
> No healthy hosts meet the resource constraints: [instanceReservation: 1, instanceReservation: 1, 27017:27017/tcp portReservation, instanceReservation: 1].

In 1.6, that statement clearly shows what is required for the host. 

Do you have a host that has the port open and available?
