### ISSUE TITLE
Automatically lower case rancher catalog template names 

### ISSUE THREAD

**Issue by Amos-85** [rancher/rancher#19615]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
add jenkins-x catalog url: https://github.com/jenkins-x/jenkins-x-platform

exception in rancher logs:
`[ERROR] CatalogController jenkinsx [catalog] failed with : failed to update templates. Multiple error occurred: [TemplateVersion.management.cattle.io "jenkinsx-jenkins-x-platform-0.0.1-SNAPSHOT" is invalid: metadata.name: Invalid value: "jenkinsx-jenkins-x-platform-0.0.1-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/04/15 09:07:59 [INFO] Catalog sync done. 0 templates created, 4 templates updated, 0 templates deleted`

**Result:** catalog doesn't sync when chart version in chart.yaml is in uppercase characters the issue reproduced.

**expected behavior :**
manipulate chart.yaml version to lower case to avoid the issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.8 stable
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type: Hosted
- Machine type: Metal
- Kubernetes version: 1.13.5

**Comment by Amos-85** [comment]
@deniseschannon ,
is there any estimation to fix this issue?
sill happen in version 2.2.8

**Comment by stearz** [comment]
This Pull Request should fix the problem:
https://github.com/rancher/rancher/pull/26703

**Comment by stearz** [comment]
New PR https://github.com/rancher/rancher/pull/26943

**Comment by rancher-max** [comment]
#### Reopening due to unable to deploy app

The catalog is now able to be added, but when navigating to Apps > Launch and trying to deploy the app from this catalog, it fails with the same error:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/55997940/81445885-9c98bc80-912e-11ea-84aa-900bb918aed5.png">

This happens in both `master-2939-head` and `v2.4-2941-head`

**Comment by rancher-max** [comment]
#### Validated in both v2.4-head and master-head

- The original error does not appear when adding the catalog
- Apps do not have the error mentioned in the reopening of this issue: https://github.com/rancher/rancher/issues/19615#issuecomment-626007957

I'd like to note that this specific Jenkins-X chart is trying to do a helm install, when jenkins x should use jx to install. Therefore, there are other errors that happen when installing this chart. However, the catalog is present in etcd.
