### ISSUE TITLE
after restart rancher server, rancher ui server stuck in Provisioning

### ISSUE THREAD

**Issue by yuanbw** [rancher/rancher#19616]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
after restart rancher server, the rancher ui stuck in Provisioning

**Result:**
![image](https://user-images.githubusercontent.com/26744366/56125557-c58e6280-5fab-11e9-84b1-36be1ccc3525.png)

rancher ui  stuck in provising and output the error msg "Exit status 1, W0415 08:23:20.994606 2452 factory_object_mapping.go:423] Failed to download OpenAPI (an error on the server ("Error: 'waiting for cluster agent to connect'\nTrying to reach: 'https://10.126.146.18:6443/swagger-2.0.0.pb-v1'") has prevented the request from succeeding), falling back to swagger Error from server (InternalError): an error on the server ("Error: 'waiting for cluster agent to connect'\nTrying to reach: 'https://10.126.146.18:6443/api'") has prevented the request from succeeding"

**Other details that may be helpful:**
after restarting rancher server and rancher agent on 10.126.146.18, the issue remains

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.2.1
- Installation option (single install/HA):
 single 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):metal
- Kubernetes version (use `kubectl version`):
 1.10.5
```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```
1.13.1

**Comment by deniseschannon** [comment]
Are you just starting up rancher and adding a cluster and then restarting rancher?

How did you add your cluster to Rancher?

**Comment by yuanbw** [comment]
> Are you just starting up rancher and adding a cluster and then restarting rancher?
> 
> How did you add your cluster to Rancher?

**Comment by yuanbw** [comment]
I upgraded rancher from v2.0.6 to v2.2.1. After the upgrade, the rancher interface and k8s is ok. But when I restarted the rancher host, Rancher started reporting the above error. However, k8s is ok.
