### ISSUE TITLE
Backport:UI:New Monitoring Prometheus PVC doesn't work with OpenEBS

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19610]
https://github.com/rancher/rancher/issues/19608

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc7

I can confirm that when monitoring is enabled it will now automatically set this answer:
`prometheus.persistent.useReleaseName` = `true`
You will see it added after you enable monitoring for cluster _or_ project level monitoring.

This essentially shortens the name of the `prometheus-project-monitoring-db-prometheus-project-monitoring-0` which is the issue that was observed here #19410
I confirmed that this indeed resulted in the shortening of that name and thus this should resolve the issue with OpenEBS. 
The name is now about as short as `prometheus-project-monitoring` and all  names stay under the 63 char limit OpenEBS has. This should resolve the issue.

**Comment by davidnuzik** [comment]
This is NOT FIXED in v2.2.3 ! 
We had to cut a release for v2.2.3 to fix an important issue with monitoring so v2.2.3 only has that one monitoring fix. Please wait for v2.2.4 for this fix.
