### ISSUE TITLE
Cert Rotation - worker nodes did not get the new certs after cert rotation

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19620]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Have a DO rke cluster on rancher:v2.1.8.
2. run the following command
./system-tools cert rotate --url https://x.x.x.x/v3 --token "token-xxxxxxxx" --cluster c-xxxx (system tools from : https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc7)

**Expected Result:**
`kube-node.pem` and `kube-proxy.pem` on Worker nodes, should have the new certs. 

**Actual Result:**
`kube-node.pem` and `kube-proxy.pem` on the worker node, did not get new certs, certs' expiry date did not get the 10 years.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.8
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO hosted

**Comment by alena1108** [comment]
Instead of system-tools, cert rotation was backported to rancher rke/rancher. The feature can be tested with rancher v2.1.9-rc2. Closing this issue.
