### ISSUE TITLE
nfs not working with nextcloud

### ISSUE THREAD

**Issue by sofior** [rancher/rancher#19621]
container path is /var/www/html

rancher version is v2.2.1

**Comment by sofior** [comment]
I can't find any file on my nfs path
but works good with ubuntu:xenial

**Comment by superseb** [comment]
There is not enough information in this issue to try to reproduce or get a feel what you are trying to do, which makes it hard to look into. If you believe there is a bug in the product, please read https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions and fill out the issue template with the requested information so we can start investigating.

If you are trying to solve a certain use case, I want to ask to open a forum topic at https://forums.rancher.com, but still describe in detail what you are trying to do or what problem you are trying to solve so people can use that information to give you ideas on how to solve it.
