### ISSUE TITLE
View/Edit YAML for namespace is showing incorrect information

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#19637]
rancher/rancher:v2.2.1

Navigate to [Cluster] > Default > Namespaces.

From the drop-down menu of the "default" namespace and click "View/Edit YAML".

Expected:
YAML output for the namespace resource.

Actual:
I see the YAML for all the resources in this namespace.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/15038#issuecomment-483552143
