### ISSUE TITLE
Catalog App Upgrade Action Does Not Nullify a Null valuesYaml Field

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19634]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
This bug is a little hard to reproduce currently due to another bug in the UI with switching between yaml and form editing.

1. Launch project level app, something small like docker registry will suffice, but ensure that the app is launched with the `valuesYaml` field set, this means editing the yaml in the UI and launching without going back to the normal form.
2. After app is installed and deployed, upgrade the app (same version is fine), switch from edit as yaml to edit as form and refill in the answer data (this is being addressed in rancher/rancher#19060)  
3. Upgrade the app
4. After the upgrade view the resource in the api and you will see that `valuesYaml` which was cleared on the upgrade by switching back to form editing. You will also see the answers object populated.

**Result:**
The API should clear the valuesYaml or answers properties when sent as null. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Master (as of 4/15/2019) & UI v2.3.0
- Installation option (single install/HA): Single

**Comment by loganhz** [comment]
@westlywright @alena1108  Could you pass an empty string instead of `null`, please? I can reproduce it by passing `null` during upgrade. But passing an empty string works. We can put a fix for it if empty string is not good.

**Comment by guangbochen** [comment]
We will clear the `valuesYaml` or `answers` properties in the backend when it is set to null.

**Comment by westlywright** [comment]
@loganhz @alena1108 setting the `valuesYaml` the empty string `''` rather than `null` does work. I think that this should still be fixed in master even if we don't want to back port this because empty string is not null and since the type is nullable according to its schema it should be overwritten if `null` is sent.

**Comment by alena1108** [comment]
@loganhz can you see if we should make string types not nullable, with the default value ="" ? Or if the field is generic, and can't be defined in types, we should handle it in the api layer.

**Comment by jiaqiluo** [comment]
The bug is reproduced on Rancher:v2.2.2 following the steps in the issue, and notice that both the valuesYaml or answers properties exist when viewing the app in API.

The bug fix is validated on Rancher: master  397e8a8, notice that only one of those two will exist depending on the choice of `edit as yaml` or `edit as form` when upgrading the app.
