### ISSUE TITLE
etcd restore doesnt work on ROS hosts

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#19639]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. break your cluster and try to restore from the UI

**Result:**
```
2019/04/15 23:44:29 [ERROR] ClusterController c-66dsr [cluster-provisioner-controller] failed with : failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2019-04-15T23:44:09Z" level=fatal msg="stat /backup/c-CID-rl-HID: no such file or directory"
```

We copied the snapshots from `/opt/rke/etcd-snapshots/` to `/backup` on the host then ran the restore and that worked. We also provisioned all new etcd/control plane nodes and this worked without a hitch.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- single node rancher server (container non-ha)
- v2.2.1

**Comment by galal-hussein** [comment]
I wasn't able to reproduce using the following steps:

- start a cluster with 3 ROS nodes
- take local backup from ui
- Remove 2 nodes from the aws provider 
- Wait until the node left lose quorum and etcd break
- try to restore etcd snapshot on the node left.

The restoration works as expected and the cluster is back in an operational state.

**Comment by aemneina** [comment]
Will close this out for now as the repro to break the cluster is lacking.
