### ISSUE TITLE
Catalog templates didn't get updated on rancher slave pod in HA mode

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#19638]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Pre-requisites:  Rancher HA

1. add a custom catalog to the rancher global/cluster/project catalog.
2. update catalog charts:
    2.1 change the template files e.g. the default value in the values.yaml file and push the update.
    2.2 or add a new version of a chart e.g Nginx v0.2.0 to the same catalog and push the update.
3. click refresh catalog button and wait for the catalog repo get synced.
4. go to the rancher api `/v3/templates/cattle-global-data:CHART_NAME` and click the `versionLinks` to jump to the specified templateVersions, check the changed files is updated correctly.
    4.1 because it is rancher HA mode, so you may need to refresh the `templateVersions` page multiple time to check all node returns the same result.
    4.2 decode files using https://www.base64decode.org/
5. exec into the rancher server pod and check the catalog template is updated in the local cache `$ cd management-state/catalog-cache/CHART_HASH_PATH`, both master and follower node should be updated and keep consistent. 

**Result:**
All of the rancher server pod should have the same version of latest catalog apps templates.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master  16/04/2019
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

**Comment by guangbochen** [comment]
Link PR:  https://github.com/rancher/rancher/pull/19856

**Comment by mholasek** [comment]
I get this problem on my rancher 2.2.2 HA installation. Is there any workaround for this? Is it possible to rebuild the cache somehow?

**Comment by ericlarssen-wf** [comment]
Scaling down to one instance will bypass your immediate issue. (Not ideal, I know)

**Comment by gregkeys** [comment]
having the same issue

**Comment by bmdepesa** [comment]
rancher/rancher:master - e59adbc7

* Reproduced original issue
* Deployed Rancher master in HA
* Added a custom catalog
* Updated the custom catalog and refreshed
* Viewed the new version links in API
* Viewed the updated files in each rancher pod's catalog-cache
