### ISSUE TITLE
Monitoring - can't completely clean up after disabling cluster monitoring

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#19645]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable Monitoring with large size requirement CPU & RAM
1. Disable Monitoring without enabling Monitoring completely

**Result:**
Can't clean up the `cluster-monitoring` App of `System` Project

**Other details that may be helpful:**
- Enable - Disable (quickly) may output the same result.
- Enable Monitoring in a limited resource environment also output the same result.
- Workaround:
  + Re-enable the Monitoring, assign 1m CPU & 1m RAM to Prometheus
  + Disable Monitoring again after starting Prometheus

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2-rc11
- Installation option (single install/HA): single

**Comment by jiaqiluo** [comment]
The same bug exists when enabling cluster monitoring with default values in Rancher: master 4/17 705af32

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher master 397e8a8f

Test those two cases:
- enable and disable the cluster monitoring really quickly multiple times
- enable and disable the cluster monitoring in the environment with limited resource

**Comment by mkostersitz** [comment]
this seems still an issue in 2.3.3 when enabling cluster monitoring in a Windows enabled cluster
