### ISSUE TITLE
Backport:Monitoring: Fails to deploy in some cases due to insufficient vCPU

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19649]
https://github.com/rancher/rancher/issues/19624

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: v2.2.3-rc1

I tested again the outlined steps in the original issue herehttps://github.com/rancher/rancher/issues/19624 ( https://github.com/rancher/rancher/issues/19624|smart-link ) 

This includes both the EKS and GKE scenario with the respective machine configurations. For each I could not enable monitoring with the defaults (which is what we want). This is working as expected.
