### ISSUE TITLE
Backport:UI Monitoring: Cannot increase time when have Custom timeframe

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19641]
https://github.com/rancher/rancher/issues/19588

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc3

I validated again (was tested in master here https://github.com/rancher/rancher/issues/19588#issuecomment-484208639) following the same steps as outlined in that issue. I confirmed I can increase the time now when using a custom time range for the charts without any issues.
