### ISSUE TITLE
Issue with Catalogs display.

### ISSUE THREAD

**Issue by garelp** [rancher/rancher#19667]
Hello,

You can't see what catalogs are enabled when you're on the page Globals, Catalogs with a simple user role. It could be better to actually display what are the enabled catalogs.

Thanks.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.8` UI: `v2.1.21` |
|Route|`containers.index`|

**Comment by deniseschannon** [comment]
On the "catalogs" page, i can see which catalogs are enabled as a standard user.

Do you have a screenshot of what you are missing?

**Comment by superseb** [comment]
Let us know if we can investigate further on this.
