### ISSUE TITLE
Backport:Monitoring - can't completely clean up after disabling cluster monitoring

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19666]
https://github.com/rancher/rancher/issues/19645

**Comment by loganhz** [comment]
in rc5

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: v2.2.3-rc5

Test those two cases:
- enable and disable the cluster monitoring really quickly multiple times
- enable and disable the cluster monitoring in the environment with limited resource
