### ISSUE TITLE
Change timezone of rancher launched kubernetes's scheduler container

### ISSUE THREAD

**Issue by happyyangyuan** [rancher/rancher#19675]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
Our timezone is UTC+8 but the default timezone for kubernetes is UTC. We need to make Cron schedule running based on UTC+8 otherwise the schedule cron expression is confusing.

**Comment by wisepotato** [comment]
same question here, +1

**Comment by watersoona** [comment]
create cronjob at 12:00 everyday in shanghai。
but not run，change to 4:01 it runs ，  so timezone is UTC，so how to change it？

**Comment by IAkumaI** [comment]
Hi. Any solution?

**Comment by donnib** [comment]
same issue, is there a work around ?

**Comment by Duvel** [comment]
**Note: this worked for me, but as always: be careful!**

I think I found a workaround with the help of #18913:

* Make sure your server has the correct timezone
* Go to the page of your cluster
* Choose the option Save As RKE Template
* Go to Global > Tools > RKE templates
* Find your template and choose Clone Revision
* Choose Edit as yaml
* Find 
```
  services:
    kubecontroller: {}
```
* replace with or change to: 
```
  kube-controller:
      extra_binds:
        - '/etc/localtime:/etc/localtime'
```
* Edit your cluster
* Choose your new revision
* Save and your cluster will be updated
