### ISSUE TITLE
windows rancher-compose not looking for environments under project

### ISSUE THREAD

**Issue by uuunk** [rancher/rancher#1967]
It looks like the `rancher-compose` is looking for envronments as a root resource as opposed to under projects (e.g `/v1/projects/{proj_id}/environments/{env_id}`).

`D:\src\elk_stack>rancher-compose up`
`←[34mINFO←[0m[0000] Creating environment elk_stack`
`←[31mERRO←[0m[0000] Failed to open project elk_stack: Bad response from [http://10.0.1.45:8080/v1/environments], statusCode [422]. Status [422 status code 422]. Body: [{"id":"0fc03e8b-9863-4185-94b1-9df47142fb42","type":"error","links":{},"actions": },"status":422,"code":"InvalidCharacters","message":null,"detail":null,"fieldName":"name"}] `
`2015/09/03 16:41:54 Failed to read project: Bad response from [http://10.0.1.45:8080/v1/environments], statusCode [422]. Status [422 status code 422]. Body: [{"id":"0fc03e8b-9863-4185-94b1-9df47142fb4
2","type":"error","links":{},"actions":{},"status":422,"code":"InvalidCharacters","message":null,"detail":null,"fieldName":"name"}]`

This is on v0.2.5 for windows

**Comment by ibuildthecloud** [comment]
We need to report errors better but barried in that blob of json is InvalidCharacters.  Basically an Stack/project should be alphanumeric and - only.

**Comment by uuunk** [comment]
roger that, thanks that worked.
