### ISSUE TITLE
Pipelines: CICD_IMAGE contains index.docker.io

### ISSUE THREAD

**Issue by pensiero** [rancher/rancher#19679]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
While using Docker Hub as Registry for a Rancher pipeline, the value of the variable `CICD_IMAGE` is set to `index.docker.io/[user]/[image-name]`. In this way, in the deployment phase, it actually doesn't let the workload starts properly. In order to starts the workload, the image name has to be set to `[user]/[image-name]` only.

Why this happens and how can I solve it?

Thank you

**Comment by gitlawr** [comment]
1. You should be able to pull images from index.docker.io, is there any reason you can't do that?
2. If you don't want the registry prefix, you can explicitly set [user]/[image-name] as the image name in the manifest, instead of using the CICD_IMAGE variable.

**Comment by pensiero** [comment]
1. I don't know why I can't do that, without the registry prefix it works totally fine, do you know why this could happen?
2. That's what I did as "workaround" :) 

Thank you
