### ISSUE TITLE
Cannot create cloud credential if has underscore in name (and no error is provided)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19677]
Version: Master (4/17/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to create any cloud credential that has an underscore in the name

**Result:**
When you click the "Create" button nothing will happen and there are no errors or warnings in the browser dev console. Clicking the button just seems to do nothing.

![image](https://user-images.githubusercontent.com/45179589/56307851-b0741980-60fa-11e9-99bd-c2a1b904ea30.png)

**Expected Result:**
We expected the UI to supply an error indicating why this char is not acceptable 
OR
This is a bug and underscores should be allowed perhaps?

**Additional Information:**
My guess is that this is not a valid DNS char and this is why we cannot create. If this is so the UI should notify us so we can fix the name.

**Comment by deniseschannon** [comment]
In general, it seems that there is no error message when the API for creating a cloud credential is invalid:

https://github.com/rancher/rancher/issues/20577
https://github.com/rancher/rancher/issues/19677
https://github.com/rancher/rancher/issues/19759
https://github.com/rancher/rancher/issues/21215

**Comment by davidnuzik** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/21888 which is our main issue to track problems with UI not showing errors when create Cloud Credentials with invalid names and/or with required fields not filled out.
