### ISSUE TITLE
RFE: Revision history for changes made in the Rancher UI

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#19686]
*What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description**
When using workloads you have the ability to see a revision history when you access the rollback menu.  It would be nice to have a revision history with username that made the change for other resources that are managed in the user interface.  Examples of this would be ingresses, secrets, config maps, registries and certificates.

**Comment by patrick0057** [comment]
Closing issue in favor of https://github.com/rancher/rancher/issues/19541.

**Comment by vincent99** [comment]
That information doesn't exist for other types.  Workload "revisions" are really just previous ReplicaSets that still exist for the Deployment but are now scaled to zero.
