### ISSUE TITLE
Agent fails with self-signed SSL cert

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#1968]
I use Cloudflare for all of my SSL. Unfortunately, it blocks websockets so (I don't think)  I can use it with the UI. Please correct me if I'm wrong.

So instead I'm using Rancher behind a self-signed cert. Unfortunately, rancher-agent claims that https://my.rancher.url/v1 is inaccessible if it is not behind Cloudflare and, as such, being served by a self-signed cert. If I host it behind CF, this error goes away, but of course websocket connections then fail so I see no hosts added.

I need either a way to disable websockets, or to let the agent accept a self-signed certificate. I suspect the latter is easier to accomplish. Thanks.

**Comment by kaos** [comment]
see #1853

**Comment by deniseschannon** [comment]
Closing in favor of #1853
