### ISSUE TITLE
removing etcd member fails sometimes leaving broken etcd in cluster

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#19696]
**What kind of request is this (question/bug/enhancement/feature request):**
I believe this might be the design but it feels bad.

**Steps to reproduce (least amount of steps as possible):**
prereq: have a broken etcd node
1. if using rke, or ui, remove node from cluster yaml or delete node from ui

**Result:**
rke fails to remove member and continues, but the member no longer exists so etcd can develop issues.

**Other details that may be helpful:**
the code where this happens:
https://github.com/rancher/rancher/blob/release/v2.1/vendor/github.com/rancher/rke/cluster/reconcile.go#L154-L157

**Desired Result:**
remove the member from the other remaining etcd nodes? one can get in a situation where the other etcd nodes still have this broken member that was supposed to be removed present.

**Comment by aemneina** [comment]
This seems to be working as expected in v2.2.4, I'm not sure if anything changed or I wasn't waiting long enough for the cluster reconcile. I'm fine closing this @moelsayed

**Comment by alena1108** [comment]
@aemneina there were several things in 2.2.4 done by @superseb around rke being more reliable around failures. I'd like to run the issue through qa though before closing. @sangeethah can we check that the behavior no longer occurs in 2.2.5 rc.

**Comment by sowmyav27** [comment]
verified on latest `rancher:v2.2-head` (06/26/2019)
1. Bring up a cluster - DO - 3 etcd nodes(etcd#1, etcd#2, etcd#3), 1 control plane, 1 worker node
2. verify the `etcdctl member list` on all the etcd nodes, every etcd node will have the other two etcd nodes as its members.
3. Delete etcd#1. Wait for the cluster to come up active
4. The other two etcd node, on `etcdctl member list` , will have only one other etcd node as its members.
5. Add one etcd node etcd#4. Wait for the cluster to come up active.
6. Verify step 2. Delete etcd#2. The other two etcd nodes will have only one other etcd node as its members.
7. Add one etcd node etcd#5. Wait for the cluster to come up active.
8. Verify step 2. Delete etcd#3. The other two etcd nodes will have only one other etcd node as its members.
9. Add one etcd node etcd#6. Wait for the cluster to come up active. Verify step 2

Etcd member list have etcd members when and as expected. Closing the issue.
