### ISSUE TITLE
Upgrade K8s on customer cluster with monitoring enabled errors due to node_exporter

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#19690]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade to stable 2.2.2 deployment. Enable monitoring on the cluster. Edit the cluster and upgrade the Kubernetes version.

**Result:**
Errors like this is produced on every controlplane node.
```
This cluster is currently Updating.

[controlPlane] Failed to bring up Control Plane: [Can't remove Docker container [old-kube-apiserver] for host [10.0.1.13]: Error response from daemon: Unable to remove filesystem for ec5fe20a1a923740018d84f9d67a45413f21bc5310156f16cc344d14a3ad7219: remove /var/lib/docker/containers/ec5fe20a1a923740018d84f9d67a45413f21bc5310156f16cc344d14a3ad7219/shm: device or resource busy]
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): vSphere VM, 8c/32GB
- Kubernetes version (use `kubectl version`): 1.13.5
- Docker version (use `docker version`): Docker version 17.03.2-ce, build f5ec1e2

**Comment by tfiduccia** [comment]
Version 2.2.2 - There does seems to be a bug here.  Here are my steps
1.  In 2.1.0 - Create a DO custom cluster (I only have a single node and used kubenetes version 1.11)
2.  Upgrade 2.1.0 to 2.2.2
3.  Turn on monitoring (make sure to wait for it to be completed)
4.  Upgrade cluster to k8s version 1.11

It took forever for my cluster to upgrade (15 minutes).  And it kept repeating the steps over and over.  When I upgraded a regular rke cluster without monitoring, it seemed to be done in a couple of minutes.

**Comment by deniseschannon** [comment]
@eroji Did your cluster eventually resolve?

**Comment by eroji** [comment]
@deniseschannon The upgrade did eventually complete after all the attempts of removing those node_exporter pods appeared to have timed out. However it did put the cluster into an abnormal state. Pods would get stuck terminating forever. I had to drain each node and reboot the individually.
