### ISSUE TITLE
Prometheus Operator needs higher/configurable memory limit

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#19693]
Prometheus operator after 4 hours of running started hitting OOM memory limits. It is currently capped at 100Mi, I bumped to 200Mi and it started consuming 150Mi. We need a way to allow the user to increase these limits to prevent pod flapping

**Comment by xorpierre** [comment]
I see OOMkilled directly after container start, never seeing a succesfull run

**Comment by wzrdtales** [comment]
Also stumbled into this, since it caused to crash the whole cluster, b/c of the previously missing helm limitation for config maps, see https://github.com/rancher/rancher/issues/17994.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/7/19)

This change resulted in a new addition to the cluster monitoring page. A new field for "Prometheus Operator Memory Limit" was added and the default value is 500 MiB
UI issue is it sending too many requests to backend.
![image](https://user-images.githubusercontent.com/45179589/57336932-80f27480-70dc-11e9-9c94-584a4758bcd2.png)

If you inspect the Security & Host config of the prometheus operator workload you will see the setting will take effect including when you edit and save changes to monitoring settings for the cluster.
![image](https://user-images.githubusercontent.com/45179589/57336968-9f587000-70dc-11e9-9371-ef69e9b111ca.png)
