### ISSUE TITLE
Backport: Not able to create Global DNS Provider as as regular user

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19709]
Backport https://github.com/rancher/rancher/issues/19596

**Comment by sangeethah** [comment]
Tested with Rancher sever version - v2.2.3-rc3 deployed in HA setup.
Steps to reproduce the problem:
Create a regular user (non admin user).
Log in as this regular user.
Create a GlobalDNS Provider.
This results in GlobalDNS Provider pod being created in cattle-global-data namespace in the local cluster as expected.
Create a cluster.
Deploy Mcapp - `mcapp1` in a project in this cluster with external DNS annotation for `fqdn1`.
Create a GDNS entry for `fqdn1` pointing to `mcapp1`.

This results in `fqdn1` created in external DNS provider (Route53 in my case).
