### ISSUE TITLE
docker-machine: VMware vSphere Driver Doesn't Accept a Datastore Cluster as the Datastore

### ISSUE THREAD

**Issue by Hossy** [rancher/rancher#19706]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Reference a datastore cluster instead of a standalone datastore when trying to deploy a cluster node to vSphere.

**Result:**
2019/03/21 18:22:06 [ERROR] NodeController c-nj5hw/m-cs7xv [node-controller] failed with : Error with pre-create check: "datastore 'MyDatastoreCluster' not found"

**Other details that may be helpful:**
https://github.com/docker/machine/issues/4695

In a vSphere environment that uses a datastore cluster, the datastores are not directly accessible. The datastore cluster name must be used instead, but it cannot be used as a datastore object. The result is the inability to deploy to an environment that has no standalone datastores.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rodeo-master
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by luthermonson** [comment]
DSC lookup api https://github.com/rancher/rancher/pull/23951

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/48

**Comment by luthermonson** [comment]
https://github.com/rancher/machine-package/pull/49

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/24009
https://github.com/rancher/rancher/pull/24010

**Comment by sangeethah** [comment]
Tested with Rancher server version - `v2.3.3-rc1`.

We have a dropdown and a toggle to enable selecting datastore clusters over datastores when creating Vshpere templates.

<img width="414" alt="Screen Shot 2019-11-12 at 12 21 06 PM" src="https://user-images.githubusercontent.com/4266958/68708607-ebcbaf00-0548-11ea-9482-ca296f227b3b.png">

Able to pick datastore cluster from the dropdown when creating a vsphere template using `Clone an existing VM` option for `creation method`.
Able to create a vsphere cluster successfully using this template. Able to see the machines created using the selected datastore cluster from the template in Vsphere Client UI.

The same use case as above but using a template that uses the datastore clusters does not work when `Creation method` is set as `RancherOS ISO` .

Get the following error when machines are getting created:
```
2019/11/12 19:44:40 [INFO] [node-controller-docker-machine] (sangeedscw1) Creating VM...
2019/11/12 19:44:40 [INFO] [node-controller-docker-machine] (sangeedscw1) Image cache directory does not exist, creating it at /management-state/node/nodes/sangeedscw1/cache...
2019/11/12 19:44:40 [INFO] [node-controller-docker-machine] (sangeedscw1) Downloading /management-state/node/nodes/sangeedscw1/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros-vmware.iso...
2019/11/12 19:44:41 [INFO] [node-controller-docker-machine] (sangeedscc1) Creating VM...
2019/11/12 19:44:41 [INFO] [node-controller-docker-machine] (sangeedscc1) Image cache directory does not exist, creating it at /management-state/node/nodes/sangeedscc1/cache...
2019/11/12 19:44:41 [INFO] [node-controller-docker-machine] (sangeedscc1) Downloading /management-state/node/nodes/sangeedscc1/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros-vmware.iso...
2019/11/12 19:44:43 [INFO] [node-controller-docker-machine] (sangeedsce1) Creating VM...
2019/11/12 19:44:43 [INFO] [node-controller-docker-machine] (sangeedsce1) Image cache directory does not exist, creating it at /management-state/node/nodes/sangeedsce1/cache...
2019/11/12 19:44:43 [INFO] [node-controller-docker-machine] (sangeedsce1) Downloading /management-state/node/nodes/sangeedsce1/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros-vmware.iso...
2019/11/12 19:44:44 [INFO] [node-controller-docker-machine] (sangeedscw1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2019/11/12 19:44:44 [INFO] [node-controller-docker-machine] (sangeedscw1) Finding datastore cluster /RNCH-HE-FMT/datastore/ds_cluster
2019/11/12 19:44:44 [INFO] [node-controller-docker-machine] (sangeedscc1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2019/11/12 19:44:44 [INFO] [node-controller-docker-machine] (sangeedscc1) Finding datastore cluster /RNCH-HE-FMT/datastore/ds_cluster
2019/11/12 19:44:45 [INFO] [node-controller-docker-machine] (sangeedscw1) Uploading Boot2docker ISO ...
2019/11/12 19:44:45 [INFO] [node-controller-docker-machine] (sangeedscc1) Uploading Boot2docker ISO ...
2019/11/12 19:44:46 [INFO] [node-controller-docker-machine] (sangeedsce1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2019/11/12 19:44:46 [INFO] [node-controller-docker-machine] (sangeedsce1) Finding datastore cluster /RNCH-HE-FMT/datastore/ds_cluster
2019/11/12 19:44:47 [INFO] [node-controller-docker-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2019/11/12 19:44:47 [INFO] [node-controller-docker-machine] 
2019/11/12 19:44:47 [INFO] Generating and uploading node config sangeedscw1
2019/11/12 19:44:47 [ERROR] NodeController c-8zxtf/m-gvjx9 [node-controller] failed with : Error creating machine: Error in driver during machine creation: Put https://<ip>/folder/sangeedscw1/boot2docker.iso?dcPath=&dsName=ds_cluster_0: net/http: HTTP/1.x transport connection broken: write tcp <ip>:35266-><ip>:443: write: broken pipe
```

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/49 to fix ros upload bug

**Comment by sangeethah** [comment]
Tested with `v2.3-head`  version `4313c246b`

Create a Vsphere template using `datastore cluster` option and `Creation method`  set as RancherOS ISO .

Able to create a vsphere cluster successfully using this template. 
Machines created for the cluster use the selected datastore cluster (that was set in the template) . This check was done in Vsphere Client UI.
