### ISSUE TITLE
etcd backup to s3 successful when S3 access denied

### ISSUE THREAD

**Issue by greenu** [rancher/rancher#19703]
**Bug**

**Steps to reproduce (least amount of steps as possible):**
Create S3 bucket with lack of permissions (in my case it's upload forbidden without SSE header: x-amz-server-side-encryption)
Setup etcd backup to S3.

**Result:**
Observe successful Active backup in "tools -> snapshots" in UI
No backup created in fact.

Logs of rancher/rke-tools:v0.1.27
```
docker logs -f etcd-snapshot-once
time="2019-04-18T14:33:14Z" level=info msg="Initializing Rolling Backups" creation=12h0m0s retention=72h0m0s
time="2019-04-18T14:33:14Z" level=info msg="invoking set s3 service client"
time="2019-04-18T14:33:14Z" level=info msg="invoking set s3 service client use IAM role"
time="2019-04-18T14:33:16Z" level=info msg="Created backup" name=c-5npn7-ms-t96rl runtime=1.090654934s
time="2019-04-18T14:33:16Z" level=info msg="invoking uploading backup file c-5npn7-ms-t96rl to s3"
time="2019-04-18T14:33:18Z" level=info msg="failed to upload etcd snapshot file: Access Denied, retried 0 times"
time="2019-04-18T14:33:20Z" level=info msg="failed to upload etcd snapshot file: Access Denied, retried 1 times"
time="2019-04-18T14:33:21Z" level=info msg="failed to upload etcd snapshot file: Access Denied, retried 2 times"
time="2019-04-18T14:33:24Z" level=info msg="failed to upload etcd snapshot file: Access Denied, retried 3 times"
```

**Other details that may be helpful:**

**Environment information**
- Rancher version v2.2.2-rc2
- Installation option: single

**Comment by tfiduccia** [comment]
@soumyalj - I do not know enough about S3 buckets to be able to reproduce this issue.  Can you please touch base with Denise about it.

**Comment by bhood4** [comment]
I have the same problem.  Any update?

**Comment by superseb** [comment]
This should be resolved in the latest version, please file a new issue if you encounter issues.

**Comment by eliyamlevy** [comment]
@MKlimuszka Unable to reproduce in Rancher `2.7-head`, and according to @superseb this was resolved with the following RC/version.
