### ISSUE TITLE
Failed to obtain metrics. The metrics service may not be available.

### ISSUE THREAD

**Issue by ibayue** [rancher/rancher#19700]
The monitoring data will not be displayed every few minutes, then it is will be better again.
The error is as follows:

![image](https://user-images.githubusercontent.com/11729209/56341813-d24bca00-61e8-11e9-9b03-9ec2cb96659f.png)

![image](https://user-images.githubusercontent.com/11729209/56341830-e0014f80-61e8-11e9-8874-3786a9449ac3.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`workload`|

**Comment by cloudnautique** [comment]
How many nodes, pods, workloads do you have? Have you adjusted the memory and CPU limits based on our documentation?

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/#resource-consumption

**Comment by ibayue** [comment]
I hava 3 nodes ,100 pod, 70 workloads
I think I have given enough memory and CPU and no OOM occurred
Snipaste_2019-04-19_09-45-20.jpg

**Comment by Rajesh804** [comment]
I am facing the same issue. Is there any resolution for this ?

**Comment by sddrwsm** [comment]
I am facing the same issue too.

**Comment by gywang-** [comment]
I am facing the same issue too.

**Comment by ningmeng-ding** [comment]
I am facing the same issue too.

**Comment by tomsherrod** [comment]
Testing out a simple install, sample app and encountering the same issue.

**Comment by MiMiBaBa** [comment]
I am facing the same issue. Is there any resolution for this ?
INFO[2019-06-06T07:20:18Z] Start listening for connections on 10.42.7.14:9090
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: dial tcp [::1]:9090: connect: network is unreachable
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: context canceled
2019-6-6 15:21:34 2019/06/06 07:21:34 http: proxy error: context canceled

**Comment by MiMiBaBa** [comment]
exec to the container ,run prometheus-auth --log.debug
INFO[2019-06-06T07:25:52Z] listening on :9090, proxying to http://localhost:9999 with ignoring 'remote reader' labels [], only allow maximum 512 connections with 5m0s read timeout . 
FATA[2019-06-06T07:25:52Z] Failed to create agent                        error="unable to listen on addr :9090: listen tcp :9090: bind: address already in use"

**Comment by bbhuston** [comment]
I am also hitting this exact same issue.   Running monitoring on multiple Kops/Kubernetes 14.6 clusters.

**Comment by huegelc** [comment]
Same issue here

**Comment by funky81** [comment]
Still having the same problems here. Running 3 node worker for Cluster 1 and 1 node worker for Cluster 2. It gives http 500 error for this url : /v3/clustermonitorgraphs?action=query

**Comment by yuanyi-wang** [comment]
works fine after disable firewalld. you should follow document to setup firewall rule if you can't disable it.
