### ISSUE TITLE
Expose Container ID in UI

### ISSUE THREAD

**Issue by kevinfrommelt-wf** [rancher/rancher#19708]
In Rancher 2.x UI, it would be useful to be able to see the container ID from the Pod and/or Container details pages.

It looks like this was available in Rancher 1.x https://github.com/rancher/rancher/issues/2474

**Comment by loganhz** [comment]
@kevinfrommelt-wf May I know why you would like to see the container id?

**Comment by vharish** [comment]
@loganhz One possible use case is, in logs we can only see the container id and there's no way to know which container this is from by looking at the rancher UI. These containers are deployed on different servers, so it's not feasible for us to check on every singe server to know which container this(log) was from.
