### ISSUE TITLE
Backport: Flannel fails after upgrade because of lock: iptables: Resource temporarily unavailable.

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19711]
Backport: https://github.com/rancher/rancher/issues/18637

**Comment by jira-sync-svc** [comment]
➤ alena@rancher.com commented:

The apis are available in rancher/rancher:v2.2.3-rc1

**Comment by jira-sync-svc** [comment]
➤ Jack Luo commented:

The bug fix is validated in Rancher:v2.2.3-rc1

Steps:

  * add a cluster with k8s version 1.11.9 and Flannel as the network provider
  * run automation to deploy about 200 workloads with cluster IP and test their cross-node and cross-workload accessibility. 
  * check logs of the workload kube-flannel for errors
  * upgrade k8s to 1.12.7
  * check logs of the workload kube-flannel for errors
  * test cluster IP randomly picked 
  * upgrade k8s to 1.13.5
  * check logs of the workload kube-flannel for errors
  * test cluster IP randomly picked
