### ISSUE TITLE
Backport: Mirror coredns image to rancher

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19710]
Backport https://github.com/rancher/rancher/issues/19520

**Comment by alena1108** [comment]
Can be validated in `v2.2.3-rc3`

**Comment by jiaqiluo** [comment]
The feature is validated in Rancher v2.2.3-rc3

For the following newly added rke cluster, the image used for coredns is `rancher/coredns-coredns`
- k8s v1.13.5
- k8s v1.12.7

Note: for k8s v1.14.1-rancher-1-1 it uses `coredns/coredns`

For existing clusters in which Rancher was upgraded from previous version to v2.2.3-rc3 the image used for coredns is `coredns/coredns`

**Comment by jiaqiluo** [comment]
reopen the issue since we will mirror coredns image for k8s `v1.14.1-rancher1-2`

**Comment by alena1108** [comment]
Can be tested with rc4

**Comment by jiaqiluo** [comment]
validate on Rancher:v2.2.3-rc4 and see the newly created rke cluster with k8s v1.14.1-rancher1-2 uses the mirrored coredns image.
