### ISSUE TITLE
Backport: Rancher Global DNS cloudflare record cannot be proxied

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19712]
Backport https://github.com/rancher/rancher/issues/19251

**Comment by jira-sync-svc** [comment]
➤ alena@rancher.com commented:

The apis are available in rancher/rancher:v2.2.3-rc1

**Comment by sangeethah** [comment]
Tested with `rancher/rancher:v2.2.3-rc3`

When creating a GDN provider of type cloudflare , we have the option to set "Proxy Setting" to "yes"/"no".

When a  GDN provider is created with "Proxy Setting" set to "yes" , the GDNS entry that get created for this provider still have proxy settings on.

Reopening this issue.

**Comment by alena1108** [comment]
Can be tested on rc5

**Comment by sangeethah** [comment]
Tested with rancher server version - v2.2.3-rc5.

When a GDN provider is created with "Proxy Setting" set to "no" , the GDNS entry that gets created for this provider have proxy settings off as expected.

When a GDN provider is created with "Proxy Setting" set to "yed" , the GDNS entry that gets created for this provider have proxy settings on as expected.

When the "Proxy Setting" for a existing GDN provider is toggled between "yes" and "no" , we  see the external dns provider pod restart as expected.

**Comment by abhi1693** [comment]
@sangeethah This issue still exists on rancher `v2.4.5`. I created a provider with Proxy settings set to `no` and the record generated still had `proxy orange cloud`. I tried toggling the settings and nothing happens.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create Rancher HA 2.4.5
- create Global DNS Provider Cloudflare with proxy setting set to `no`
- make DNS record on project

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): VMware
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 VM (12 CPU/32 GB)
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version (use `docker version`):
```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```
