### ISSUE TITLE
Adding pre-issued let's encrypt certs causes x509 issue when adding nodes

### ISSUE THREAD

**Issue by AlexanderNZ** [rancher/rancher#19718]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug Report

**Steps to reproduce (least amount of steps as possible):**
1. Provision and download Let's Encrypt Certs from sslforfree.com
2. Rename `.cert` files to `.pem` (they're valid PEMs as per https://stackoverflow.com/questions/991758/how-to-get-pem-file-from-key-and-crt-files)
3. Upload certs to host
4. On a fresh ubuntu 18.04 LTS machine with docker 18.06.3-ce run:  
`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /cert_path/cert.pem:/etc/rancher/ssl/cert.pem -v /cert_path/key.pem:/etc/rancher/ssl/key.pem rancher/rancher:stable --no-cacerts`
5. Create a custom cluster, and run
`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.2.2 --server https://rancher_url --token token--etcd --controlplane --worker` on a fresh ubuntu 18.04 LTS with docker 18.06.3-ce

**Result:**
A working install of Rancher 2 with green lock indicating a valid SSL configuration + certs.
Any number of nodes with docker logs as follows:
```
INFO: Arguments: --server https://rancher_url --token REDACTED --etcd --controlplane --worker
INFO: Environment: CATTLE_ADDRESS=node_ip CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=node-1 CATTLE_ROLE=,etcd,worker,controlplane CATTLE_SERVER=https://rancher_url CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 127.0.0.53 options edns0
WARN: Loopback address found in /etc/resolv.conf, please refer to the documentation how to configure your cluster to resolve DNS properly
INFO: https://rancher_url/ping is accessible
INFO: rancher.ringfence.nz resolves to rancher_ip
time="2019-04-19T04:54:58Z" level=info msg="Rancher agent version v2.2.2 is starting"
time="2019-04-19T04:54:58Z" level=info msg="Option requestedHostname=rancher-node-1"
time="2019-04-19T04:54:58Z" level=info msg="Option customConfig=map[label:map[] address:192.168.1.20 internalAddress: roles:[etcd worker controlplane]]"
time="2019-04-19T04:54:58Z" level=info msg="Option etcd=true"
time="2019-04-19T04:54:58Z" level=info msg="Option controlPlane=true"
time="2019-04-19T04:54:58Z" level=info msg="Option worker=true"
time="2019-04-19T04:54:58Z" level=info msg="Listening on /tmp/log.sock"
time="2019-04-19T04:54:58Z" level=info msg="Connecting to wss://rancher_url/v3/connect/register with token token"
time="2019-04-19T04:54:58Z" level=info msg="Connecting to proxy" url="wss://rancher_url/v3/connect/register"
time="2019-04-19T04:54:58Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-04-19T04:54:58Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
```

**Other details that may be helpful:**
I've followed https://medium.com/@superseb/ssl-tls-options-for-rancher-2-0-dca483a7070d as a reference and nothing in there has solved my problem.
I've also used https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d when resetting and attempting to reinstall with different run paramters.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 2 vCPU, 6gb ram, 50gb storage
- Kubernetes version (use `kubectl version`):`v1.13.5-rancher1-2`
- Docker version (use `docker version`): `Docker version 18.06.3-ce, build d7080c1`

**Comment by superseb** [comment]
Let's Encrypt uses an intermediate certificate which needs to be supplied in the server certificate, the file Let's Encrypt provides for this when using certbot is `fullchain.pem`. If you mount this, as `cert.pem`, there shouldn't be an issue. If you don't have the file, you have to create the file manually as described on https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#cert-order.

Let me know if it doesn't work.
