### ISSUE TITLE
rancher 2.2.1 Cluster Alert request

### ISSUE THREAD

**Issue by symenghuan** [rancher/rancher#19714]
This is request:
1、rancher version: 2.2.1
2、The Cluster Alert no alarm，example：
![image](https://user-images.githubusercontent.com/44770931/56400456-9109f780-6286-11e9-98f7-3c7c1295b93f.png)

and this configuration is not change color，always is green，I want to know how to query log
![image](https://user-images.githubusercontent.com/44770931/56400515-e3e3af00-6286-11e9-98f6-6f18a405fab5.png)

This is my alert pod，and have not error：
![image](https://user-images.githubusercontent.com/44770931/56400562-17263e00-6287-11e9-926e-efba0073f8bc.png)

@loganhz

**Comment by symenghuan** [comment]
But  enable cluster monitoring  ，the Expression rule  can  alarm，send mail or wechat

**Comment by aiwantaozi** [comment]
Could you check 
1. rancher server's log
2. node labels
3. alertmanager page
Couldn't reproduce this issue now, you can go to alertmanager page by access link under ```System project``` -> ```cluster-alerting``` app to check whether alertmanager receive alert records.
![image](https://user-images.githubusercontent.com/5936271/56413707-ee1fa080-62ba-11e9-9e59-92c07250ba26.png)
![image](https://user-images.githubusercontent.com/5936271/56413799-40f95800-62bb-11e9-8a8a-a0d8f16cdeb2.png)

**Comment by symenghuan** [comment]
@aiwantaozi

**Comment by symenghuan** [comment]
@aiwantaozi 
sorry, the question is too late!
Now, my cluster alert:
![image](https://user-images.githubusercontent.com/44770931/56878238-ac92b080-6a85-11e9-842d-586896162ab0.png)

the alertmanage  is exist
![image](https://user-images.githubusercontent.com/44770931/56878317-06937600-6a86-11e9-957f-9d5fd4fa3db0.png)

But  the alert is not turn red  and  send message,  
I have update to rancher 2.2.2 the question always exist
I want to know :
1、Can i delete the alert namespaces  all pod  , How to redeploy
2、The log is not have some error
only rancher server :  
E0429 05:51:47.219459 6 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0429 05:51:47.219704 6 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)

**Comment by symenghuan** [comment]
The  Expression is normal ,but alert color is green
![image](https://user-images.githubusercontent.com/44770931/56881440-fcc43f80-6a92-11e9-8caa-5c61cdf5d10b.png)

But not Expression rule is not send emali

**Comment by symenghuan** [comment]
> @aiwantaozi
> sorry, the question is too late!
> Now, my cluster alert:
> ![image](https://user-images.githubusercontent.com/44770931/56878238-ac92b080-6a85-11e9-842d-586896162ab0.png)
> 
> the alertmanage is exist
> ![image](https://user-images.githubusercontent.com/44770931/56878317-06937600-6a86-11e9-957f-9d5fd4fa3db0.png)
> 
> But the alert is not turn red and send message,
> I have update to rancher 2.2.2 the question always exist
> I want to know :
> 1、Can i delete the alert namespaces all pod's workload , How to redeploy
> 2、The log is not have some error
> only rancher server :
> E0429 05:51:47.219459 6 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
> E0429 05:51:47.219704 6 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)

Alertmanager  only have Metric data, non Metric is null

**Comment by aiwantaozi** [comment]
Hi, @symenghuan I'm not sure I fully understand your situation. Which kind of alert can't receive notify? Node or metric? 
First, you can user ```Test``` in the notifier page to check whether could receive emails.
Second, you can configure alert, then try to trigger it, and go to the alert manager page to check whether the alert manager has this alert event.
Third, if the alert manager has this event check the group wait time in the alert rule advance configure, this configure will affect the first notify event.

**Comment by symenghuan** [comment]
@aiwantaozi 
Now  the Metric  rule is OK!  can send email and the alertmanager have message ! 
But node configure  alert is false, the alertmanage also have no alert message ,the rule is no problem
![image](https://user-images.githubusercontent.com/44770931/56939040-76facf80-6b38-11e9-9977-feda9788cd0b.png)

OR, Can you tell me, How to initialize the  alert rule and  services!
