### ISSUE TITLE
Rancher monitoring: fluentd query

### ISSUE THREAD

**Issue by spencergilbert** [rancher/rancher#19722]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/Fix

**Steps to reproduce (least amount of steps as possible):**
The default grafana dashboard "Rancher Components" has a singlestat metric for Fluentd uses the following query: 

`sum(kube_pod_info{pod=~"fluentd.*"})`

**Result:**
It appears as those this query always returns zero, it looks like the query does return as:

`sum(kube_pod_info{pod=~".*fluentd.*"})`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): HA

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master with Cluster Monitoring v0.0.3

Steps:
- run Rancher: master in HA mode
- add a Do cluster 
- enable the cluster monitoring, the default version is v0.0.3
- go to the Grafana's Rancher Components page
- see the count of Fluentd is zero
- enable the cluster logging with Fluentd
- go back to the Grafana's Rancher Components page
- see the  count of Fluentd is four now 
- also check Fluentd -> More -> Panel JSON 
- see the express is like this 
```
"expr": "sum(kube_pod_info{pod=~\".*fluentd.*\",pod!~\".*aggregator.*\"})"
```
<img width="578" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58993897-b48bf180-87a3-11e9-8c04-30185170df3b.png">
<img width="396" alt="Screen Shot 2019-06-05 at 3 05 52 PM" src="https://user-images.githubusercontent.com/6218999/58993904-b950a580-87a3-11e9-8985-28f7f52f7b38.png">
