### ISSUE TITLE
Can't SSH into the nodes (2.2.2)

### ISSUE THREAD

**Issue by vitobotta** [rancher/rancher#19720]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug?

**Steps to reproduce (least amount of steps as possible):**
I have upgraded Rancher to 2.2.2 and have tried several times to create a cluster as usual with my cloud provider (Hetzner Cloud). Clusters are created OK as usual but I cannot SSH into the nodes with neither "rancher ssh <node>" or directly with the SSH command. I have my default SSH key added to the Hetzner Cloud project so that it gets inserted in all servers, and if I create a server manually I can SSH with that key. However I can't SSH into the nodes provisioned by Rancher even though I can see the Rancher SSH keys are added to the project automatically for each server. It looks like something is wrong with the authorized_file or something like that. I haven't had such issues before and I could SSH into the nodes with both "rancher ssh" and ssh directly.

**Result:**
I can't SSH into the nodes provisioned by Rancher 2.2.2.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA):
Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
infrastructure provider - using the Hetzner Cloud node driver
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud, 4 cores, 16GB of ram
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
I can't SSH into the nodes so I am not sure how to check the docker version.

**Comment by deniseschannon** [comment]
@vitobotta When you say you could do this before? Are you saying it worked in v2.1.x or v2.0.x version?

**Comment by vitobotta** [comment]
Hi @deniseschannon , yes I didn't have that issue with clusters deployed with 2.2.1. Since I was having that issue, I have been creating servers with Ansible first and then setting them up with Rancher as custom nodes, instead of creating the servers with Rancher, so this way I don't have any issues with SSH keys etc. I would be surprised though if I was the only one having this issue because I tried several times with new clusters and always had the same problem.

**Comment by vincent99** [comment]
This is presumably the same as https://github.com/rancher/rancher/issues/19702 and fixed for 2.2.3.

**Comment by vitobotta** [comment]
Hi @vincent99, sounds good! I prefer to create servers from Rancher as it's quicker so looking forward to 2.2.3.

**Comment by deniseschannon** [comment]
@vitobotta I'll close this and if you have issues after 2.2.3 ships, please re-open or create a new issue!
