### ISSUE TITLE
globalDNS entry allows any string for fqdn even invalid DNS chars

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19738]
Version: Master (4/19/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- In the UI, attempt to create a GDNS entry with invalid FQDN such as "test!!!.test.com"

**Result:**
The API allows this because fqdn is of type "string" but should be of a type that checks for proper DNS chars ("dnsLabel" ?)

from v3/schemas/globalDns
```
"fqdn": {
"create": true,
"nullable": true,
"required": true,
"type": "string",
"update": true
},
```

**Comment by vincent99** [comment]
The right type would be a `hostname`.  A `dnsLabel` can't contain dots; a `hostname` is a series of `dnsLabel`s separated by dots.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/10/19)

Confirmed API was updated:
```
"fqdn": {
"create": true,
"nullable": true,
"required": true,
"type": "hostname",
"update": true
},
```

Tried in the UI to put invalid chars. UI tells me these chars are not allowed:
![image](https://user-images.githubusercontent.com/45179589/57558529-e475df80-7332-11e9-9585-f7a11d4e0617.png)
