### ISSUE TITLE
Service discovery fails for a record pointing to a daemonset in GKE cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#19732]
Rancher version: v2.0.13
Cluster : GKE
K8s version: v1.12.7-gke.7
Steps:

1. Create a GKE cluster with K8s version v1.12.7-gke.7
2. Create a daemonset 
3. Create a service discovery record pointing to a daemonset OR a service discovery record pointing to a daemonset and workload

Service discovery fails when pointing to a daemonset or to a daemonset and workload.
Service discovery succeeds when pointing only to a workload

Note: This issue persists after upgrade to v2.0.14-rc3 with newly created service discovery records and preexisting records too

Note: This issue does not occur with k8s v1.11.9-gke on a GKE cluster.

**Comment by soumyalj** [comment]
The same issue exists for RKE imported cluster in v2.0.13 and v2.0.14-rc3

**Comment by jiaqiluo** [comment]
The issue does not exist in v2.1.8 and after upgrading to v.2.19-rc3 
GKE version: v1.12.7-gke.7

**Comment by alena1108** [comment]
This issue will exist for any cluster having k8s version 1.12 and up, in 2.0.x branch. It got fixed in 2.1.x+ release by bumping up k8s vendor version for Rancher server.

**Comment by jiaqiluo** [comment]
This issue exists on 
- AKS (k8s v1.13.5) on Rancher v2.0.14
- Imported RKE cluster (k8s v1.13.5) on Rancher v2.0.14
