### ISSUE TITLE
Cluster-monitoring opens nodeport 9796

### ISSUE THREAD

**Issue by GiGurra** [rancher/rancher#19741]
**What kind of request is this (question/bug/enhancement/feature request):**
bug - Vulnerability. Nodeport opened to monitoring metrics without any authentication required.
Should this data really be publicly exposed? 

Imo node metrics should be communicated/collected within kubernetes network, not exposed with public nodeports. 

**Steps to reproduce (least amount of steps as possible):**
Deploy rancher 2.2.2, create a cluster and activate cluster monitoring

**Result:**
Go to cluster->system project->apps page, see:
![image](https://user-images.githubusercontent.com/1761299/56462649-15639400-63c7-11e9-975c-d93dd022f87f.png)

**Comment by deniseschannon** [comment]
This is in our docs:

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/prometheus/#node-exporter

**Comment by KuroObi** [comment]
To reopen this issue:
You can disable the external open port be adding this to the Monitoring Answers:
`exporter-node.enabledHostNetwork: false`
But than some metrics are not accessible to rancher, like the actual CPU and Memory usage.

Why does ranch not use an internal route to collect metrics from the node-exporter?

**Comment by Leen15** [comment]
any news here?

**Comment by MSandro** [comment]
same still in Rancher 2.6.2. I am still not able to use an internal route.
This is the correct link to the doc: https://rancher.com/docs/rancher/v2.0-v2.4/en/cluster-admin/tools/cluster-monitoring/prometheus/
but it is not realy helpfull.
