### ISSUE TITLE
etcd node having extra certs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19743]
**What kind of request is this:** bug

**Steps to reproduce:**
1. On Rancher v2.1.8, create a cluster with multiple etcd nodes - (3 etcd, 1 control plane, 3 worker) nodes

**Expected Result:** 
.pem files - certs related to only etcd node should be generated for all the etcd nodes.

**Actual Result:** 
.pem files - certs related to control plane node are also generated for an etcd node.

**Note:** 
This happens in a random manner. 
This occurs on rancher:v2.0.13 also. 
Extra certs are not rotated on rotateCertificates actions on the cluster.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.1.8
- Installation option (single install/HA): HA & Single install

**Comment by bmdepesa** [comment]
I reproduced this on v2.0.13 fresh install. The issue persists after upgrading to v2.0.14.

**Comment by alena1108** [comment]
Moving out to 2.3 as the issue existed for a while, and it's not pressing to fix it in the maintenance release.

**Comment by galal-hussein** [comment]
@sowmyav27 I wasn't able to reproduce with either v2.0.13 or v2.1.8, can you please retest with the master, you should expect the following certs in the etcd node:
```
root@hgalal-aws-etcd1:/etc/kubernetes/ssl# ls -l
total 40
drwxr-xr-x 2 root root 4096 Jul 23 18:58 certs
-rw-r--r-- 1 root root 1017 Jul 23 18:56 kube-ca.pem
-rw-r--r-- 1 root root  445 Jul 23 18:56 kubecfg-kube-node.yaml
-rw-r--r-- 1 root root  449 Jul 23 18:56 kubecfg-kube-proxy.yaml
-rw-r--r-- 1 root root 1675 Jul 23 18:56 kube-etcd-10-139-1-163-key.pem
-rw-r--r-- 1 root root 1269 Jul 23 18:56 kube-etcd-10-139-1-163.pem
-rw-r--r-- 1 root root 1679 Jul 23 18:56 kube-node-key.pem
-rw-r--r-- 1 root root 1070 Jul 23 18:56 kube-node.pem
-rw-r--r-- 1 root root 1679 Jul 23 18:56 kube-proxy-key.pem
-rw-r--r-- 1 root root 1046 Jul 23 18:56 kube-proxy.pem
```

**Comment by sowmyav27** [comment]
verified on master-head(07/25/2019)
etcd node has the following certs

```
root@sowmya-local-snapshot-basic-etcd1:/etc/kubernetes/ssl# ls -l
total 52
-rw------- 1 root root 1017 Jul 25 23:20 kube-ca.pem
-rw------- 1 root root  445 Jul 25 23:20 kubecfg-kube-node.yaml
-rw------- 1 root root  449 Jul 25 23:20 kubecfg-kube-proxy.yaml
-rw------- 1 root root 1675 Jul 25 23:20 kube-etcd-x.x.x.xkey.pem
-rw------- 1 root root 1428 Jul 25 23:20 kube-etcd-x.x.x.x.pem
-rw------- 1 root root 1679 Jul 25 23:20 kube-etcd-y.y.y.y-key.pem
-rw------- 1 root root 1428 Jul 25 23:20 kube-etcd-y.y.y.y.pem
-rw------- 1 root root 1675 Jul 25 23:20 kube-etcd-z.z.z.z-key.pem
-rw------- 1 root root 1428 Jul 25 23:20 kube-etcd-z.z.z.z.pem
-rw------- 1 root root 1679 Jul 25 23:20 kube-node-key.pem
-rw------- 1 root root 1070 Jul 25 23:20 kube-node.pem
-rw------- 1 root root 1679 Jul 25 23:20 kube-proxy-key.pem
-rw------- 1 root root 1046 Jul 25 23:20 kube-proxy.pem
```

No other files were available on the etcd nodes. Cluster config - 3 etcd, 1 control plane, 1 worker nodes.
