### ISSUE TITLE
Upgarde rancher to 2.2.2 version, cannot add new node to cluster.

### ISSUE THREAD

**Issue by HuangDelong** [rancher/rancher#19748]
*Describe your issue here*
Cannot add new node to cluster .

level=info msg="Error while getting agent config: invalid response 500: Failed to construct node config. Error: failed to find plan for x.x.x.x"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`global-admin.clusters.index`|

**Comment by URSTYLE** [comment]
Had the same issue as long as I keep two instances with the control panel option. When I turn back to keep control panel only on the one instance, everything backs to normal

**Comment by xayangjing** [comment]
@HuangDelong  How you fixed the problem ?
