### ISSUE TITLE
Add Clusters page changes

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19753]
Version: Master (4/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deactivate all drivers (hosted providers and node drivers)

**Result:**
Notice Import/Custom are still shown - these should be user-configurable so we can prevent showing them in the UI if the user wishes (I think these are the "Rancher RKE"). Also There is unused space when we deactivate all the drivers. If I only wanted to show the Digital Ocean driver I should only see this one and nothing else without any wasted blank space.

![image](https://user-images.githubusercontent.com/45179589/56534144-ec015000-650d-11e9-907c-e2fd9399c6f9.png)

**Comment by davidnuzik** [comment]
Some examples of what I was thinking -- we should be allowed to remove import/custom cluster -- when we disable rancher rke under cluster drivers _nothing_ happens. This should remove import/custom.
So if i disabled all the cluster drivers I would see this.

Before:
![current](https://user-images.githubusercontent.com/45179589/56602085-8f577100-65b1-11e9-99ca-18aa62ab6485.jpg)

After:
![proposed](https://user-images.githubusercontent.com/45179589/56602089-93838e80-65b1-11e9-8c89-632503ba405e.jpg)

**Comment by davidnuzik** [comment]
As a stop-gap measure we could perhaps just add room for one more tile so we can fit five at a time perhaps. Then later we can consider how to restructure this page.

For example we have a lot of padding we can probably use some of this and maybe make the tiles slightly smaller.
![1moretile_opinion](https://user-images.githubusercontent.com/45179589/56603850-718c0b00-65b5-11e9-9576-e77760a08741.jpg)

**Comment by vincent99** [comment]
RKE shouldn't even be a cluster driver option that's displayed.  Put in a separate bug for the backend.

**Comment by davidnuzik** [comment]
Thanks entered #19775 around "Rancher RKE" driver showing in UI (should not be displayed in UI).

**Comment by westlywright** [comment]
closing this ticket since design has changed so drastically with the addition of cluster templates.
