### ISSUE TITLE
Allow delegating "admin/global" cluster to non-local cluster

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#19757]
To leverage Multi-cluster app, Rancher needs to deploy pods into a cluster to facilitate global dns etc. In circumstances where users are following the hardening guide and disabling the local cluster, running in stand alone Docker container mode or a light weight Kubernetes without nodes this is not possible. 

We need to provide a capability where a user can provision a Kubernetes cluster, with or without Rancher, and designate that as the users "admin" cluster.

**Comment by jgreat** [comment]
If we want to use Rancher on Hosted K8s provider (EKS/GKE/AKS...) and use an etcd/kubernetes instance that runs on top of the hosted kubernetes provider, we will need to be able to designate an "admin" cluster.

**Comment by cjellick** [comment]
@will-chan is suggesting that this NOT even be optional. you must pic a non-local cluster

**Comment by will-chan** [comment]
I won't hardline this as NOT be optional, but shouldn't users be able to select a cluster of their own choosing?  I realize there are other issues with regards to requiring certs and making it easy if it was deployed on a local cluster.  We need to understand that more.

**Comment by deniseschannon** [comment]
If we add this, it should also support Global Registry

**Comment by deniseschannon** [comment]
When this goes in, we need to test that Global DNS, Global Registry and Terraform can deploy onto this other non-local cluster.
