### ISSUE TITLE
Backport default namespace didnot work in rancher 2.2 catalog apps page

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19752]
Backport of rancher/rancher#19697

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: v2.2.3-rc1

Followed the steps to reproduce (in original issue here: https://github.com/rancher/rancher/issues/19697 ( https://github.com/rancher/rancher/issues/19697|smart-link ) ). Noticed in the UI we cannot modify the requiredNamespace. Noticed upon submit we send the proper Namespace targetNamespace: "longhorn-system"
Noticed the app successfully provisioned without any issues. I can access index.html without any issues.
