### ISSUE TITLE
Provide error in UI when user supplies cloudCredential name that is not of type dnsLabel

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19758]
Version: Master (4/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cloudCredential with a name with special characters

**Result:**
You will get no error in the UI and the browser dev console will report no errors/warnings. (When you click the "Create" button nothing will happen).

**Comment by deniseschannon** [comment]
This seems like an API issue

**Comment by deniseschannon** [comment]
Actually this looks like a UI issue related to the fact that none of the errors for cloud credentials are being displayed when trying to create a cloud credential.

**Comment by davidnuzik** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/21888 which is our main issue to track problems with UI not showing errors when create Cloud Credentials with invalid names and/or with required fields not filled out.
