### ISSUE TITLE
Local Auth - Admin user did have get access to the "Default" environment until another user was added as member to this environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1975]
Server version - Build from sep 4

Steps to reproduce the problem:

Enable local auth.
Add an admin user.
When you get authenticated as this admin user , there is no access to the "Default" environment. 

<img width="1046" alt="screen shot 2015-09-04 at 1 15 32 pm" src="https://cloud.githubusercontent.com/assets/4266958/9693681/210f69fc-5307-11e5-8dd4-00e1093903db.png">

After I create another user and add it as member to the project , both admin user and regular user get access to the "Default" environment.

**Comment by hibooboo2** [comment]
Addressed with rancher/cattle#847

**Comment by sangeethah** [comment]
Tested with build from master - Sep 8
Admin user gets access to default environment after local Auth is enabled and admin user is created.
