### ISSUE TITLE
UI cloud Credential is not reporting error if credentials are empty

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19759]
Version: Master (4/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a new cloud credential such as with EC2:
 Do not supply a name, region, access key, secret key

**Result:**
The UI will report you must pick a region. Do so but leave all else blank and try to create. Now it reports nothing. The UI should be doing:
1. Check if credentials are null, if so first report that you must supply x, y 
2. check if region is selected, if not report the same "You must select a region in order to validate your keys" message
3. check if name is empty (#19756)

The UI should first check if our required credentials are empty, then any other checks after that for all rke providers.

**Comment by deniseschannon** [comment]
In general, it seems that there is no error message when the API for creating a cloud credential is invalid:

https://github.com/rancher/rancher/issues/20577
https://github.com/rancher/rancher/issues/19677
https://github.com/rancher/rancher/issues/19759
https://github.com/rancher/rancher/issues/21215

**Comment by davidnuzik** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/21888 which is our main issue to track problems with UI not showing errors when create Cloud Credentials with invalid names and/or with required fields not filled out.
