### ISSUE TITLE
Full management of imported Kubernetes clusters

### ISSUE THREAD

**Issue by amherrington13** [rancher/rancher#19769]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

It would be nice to have the same management capabilities on imported clusters as that of Rancher provisioned clusters.

**Comment by vincent99** [comment]
This is not possible.  As an imported cluster we have only access through the k8s API.  We do not know what provider it's in, where the nodes come from, and have no access create or delete them, manage etcd or the control plane nodes (if they exist at all, which they don't in some providers) or manage or the configuration of the components running behind that API.
