### ISSUE TITLE
Local Auth - Account list includes "AgentRegister" and "readAdmin" 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1976]
Server version - Build from sep 4

Local auth enabled.
Following is the account list that is presented , out of which only  "sangeetha" and "testme1" are the only 2 users that I have created.

<img width="1097" alt="screen shot 2015-09-04 at 1 27 28 pm" src="https://cloud.githubusercontent.com/assets/4266958/9693898/e8244d4a-5308-11e5-8ee6-2da87e85a1d6.png">

The other accounts , "AgentRegister", "readAdmin" , "test" , "user" should not be presented in this list .

**Comment by vincent99** [comment]
Changed to whitelist only 'User' and 'Admin' instead of incomplete blacklist of kinds we don't want to show.  The "user" User is a User though so that one will still be displayed.  I don't know what created it but it's 1a11 so it's not part of initial startup or anything.

**Comment by sangeethah** [comment]
Tested with build from master - Sep 8

Local auth enabled setup.
Accounts list now shows only "Admin" and "Users" that were created by the admin user.
