### ISSUE TITLE
Upgrade, Rollback, Delete options are missing for some apps

### ISSUE THREAD

**Issue by rpelissi** [rancher/rancher#19761]
**What kind of request is this (question/bug/enhancement/feature request):**
It's a bug

**Steps to reproduce (least amount of steps as possible):**
Not really sure about the exact path.. I have installed 2.2.1, then activate the helm stable catalog. Then installed some apps like metallb

**Result:**
Some apps can't be upgraded or deleted because the option is missing in the menu. Only the clone option and the view in api option are available

**Other details that may be helpful:**
When I go to the view in api and choose delete, this is what I have:

API Request
cURL command line:
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X DELETE \
-H 'Accept: application/json' \
'https://192.168.2.20:8443/v3/project/c-m2kjh:p-llnqd/apps/p-llnqd:metallb-p-llnqd'
HTTP Request:
HTTP/1.1 DELETE /v3/project/c-m2kjh:p-llnqd/apps/p-llnqd:metallb-p-llnqd
Host: 192.168.2.20:8443
Accept: application/json

HTTP Response:
HTTP/1.1 500
content-encoding: gzip
content-length: 141
content-type: application/json
date: Tue, 23 Apr 2019 00:11:14 GMT
expires: Wed 24 Feb 1982 18:42:00 GMT
x-api-schemas: https://192.168.2.20:8443/v3/project/c-m2kjh:p-llnqd/schemas

{

    "baseType": "error",
    "code": "ServerError",
    "message": "app p-llnqd:metallb-p-llnqd is controlled by mcapp metallb : cannot be deleted",
    "status": 500,
    "type": "error"

}

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by serveradmin99** [comment]
I'm seeing the same with Traefik app on one of my clusters.  I'm wondering if it's because there's an upgrade available but the upgrade fails with the nonsense error message "upgrade error unknown option upgrade" when I attempt it.

FWIW I installed Traefik app on another cluster and was able to delete it without problem.

**Comment by alena1108** [comment]
@rpelissi @serveradmin99 did you install the app from inside the project, or from the global view (Multi cluster app)?

**Comment by bottkv488** [comment]
seems that logging off && on does the trick ... at least in my case (rancher 2.2.2 deployed via terraform quickstart)
