### ISSUE TITLE
Set tiller's history-max as an option in the Rancher Server Chart

### ISSUE THREAD

**Issue by tylerstapler-wf** [rancher/rancher#19778]
We experienced an issue where one of our catalog apps created thousands of revisions. https://github.com/rancher/rancher/issues/17168

In addition to fixing the bug that caused the revisions, we would like to limit the number of revisions stored in our cluster.

_Originally posted by @bitfisher in https://github.com/rancher/rancher/issues/17168#issuecomment-479869119_
> I wonder if there is any option to limit the number of app revision?
Something like setting Tiller's [history-max](https://helm.sh/docs/using_helm/#initialize-helm-and-install-tiller) as option in [Rancher Server Chart](https://github.com/rancher/rancher/blob/master/chart/values.yaml)?

**Comment by nathankodilla** [comment]
We also just experienced this and adding an option like this would be great!

**Comment by thiago** [comment]
I customized my current installation to solve this problem and it worked well, but it would be much more interesting if this was a configuration in the rancher.

Basically I created my own docker image and changed tiller `--history-max=10`. To enforce security, I changed too `--storage=secret` ([Securing Installation](https://github.com/helm/helm/blob/master/docs/securing_installation.md#tillers-release-information))

`Dockerfile`

```docker
FROM rancher/rancher:v2.2.2

RUN mv $(which tiller) /usr/bin/tiller-original
ADD tiller.sh /usr/bin/tiller

RUN chmod +x /usr/bin/tiller
```

`tiller.sh`

```shell
#!/usr/bin/env bash

set -e

exec tiller-original --storage=secret -history-max=10 ${@}
```


Before redeploy the rancher, I moved all releases from `ConfigMap` to `Secret` with this tool:  https://github.com/dragonsmith/tiller-releases-converter

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/commit/c37a59d761245b483d4f8775794846f2a1effae8
