### ISSUE TITLE
Enable project level monitoring

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19771]
Project level monitoring is disabled in 2.2.2. We should add it back in 2.2.3

**Comment by alena1108** [comment]
can be tested with rc7

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: v2.2.3-rc7

Confirm that the project monitoring is up and active in the following setup:
- RKE EC2 cluster
- Custom RKE cluster
- Imported GKE cluster
 
A comprehensive test will be done later to fully validate both the cluster and project monitoring.
