### ISSUE TITLE
External Authentication with Shibboleth SAML IdP

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#19776]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Details:**
Add Shibboleth to [this list](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/) as one of the supported options for auth

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2

**Comment by ankur111** [comment]
a workaround (with Ping IdP) is being considered to help you move forward.
Full Shibboleth support will take much longer.

**Comment by luthermonson** [comment]
@jambajaar should be solved with this: https://github.com/rancher/rancher/pull/25396 if you want to close this issue fee free or write back if you do not agree.

**Comment by izaac** [comment]
This feature is available from 2.4 master-head commit id: f84c1e8f7

Bugs found when testing this feature are being tracked as separate issues.
