### ISSUE TITLE
RKE pods not getting correct upstream DNS hosts

### ISSUE THREAD

**Issue by ssirag** [rancher/rancher#19772]
**Bug**

I have an RKE-deployed Rancher 2.2.2 Kubernetes cluster with default DNS policy configured.  From my reading this should mean that the DNS settings on the hosts should be used within the pods for any beyond-cluster communications.

All my hosts have internal DNS servers set that allow for our internal network domain resolutions first.

I've noticed that my cattle-node-agents are in a crashloop state, with logs stating they can't reach the rancher server.

When I ping the rancher server from the host, I get the expected internal IP resolutions.  When I ping from the pod exec, I get the external IP, not internal, so it appears the pods are getting some external DNS server somewhere, but I can't find any specified in the cluster config yaml or anywhere else.

**Steps to reproduce (least amount of steps as possible):**

(note: busybox in this case is version 1.28 so https://bugs.busybox.net/show_bug.cgi?id=11161 doesn't apply)
____________________________________________________________________________
<user>@<kubernetes host># nslookup rancher.<mydomain>.com
Server:         <internal dns server>
Address:        <internal dns server>#53

Name:   rancher.<mydomain>.com
Address: <internal ip as expected>
___________________________________________________________________________

kubectl exec -it busybox nslookup rancher.<mydomain>.com
Server:    <kube-dns service ip>
Address 1: <kube-dns service ip> kube-dns.kube-system.svc.cluster.local

Name:      rancher.<mydomain>.com
Address 1: <rancher server external IP>
____________________________________________________________________________

**Other details that may be helpful:**

I've researched how to provide specific upstream DNS hosts via a configmap (https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/), but not sure how to retroactively supply them.  Plus, it appears that shouldn't be necessary.

**Environment information**
Rancher v2.2.2

**Cluster information**
- Cluster type (Custom):
- Machine type (VM) and specifications (vCPU: 8/memory 16 GB):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by superseb** [comment]
Can you use the DNS troubleshooting and supply the responses from the commands described? https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/

**Comment by ssirag** [comment]
# kubectl -n kube-system get pods -l k8s-app=kube-dns
NAME                        READY   STATUS    RESTARTS   AGE
kube-dns-74c78b5c6c-prtk8   3/3     Running   0          19h
kube-dns-74c78b5c6c-spnhj   3/3     Running   0          19h

# kubectl -n kube-system get svc -l k8s-app=kube-dns
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP   21d

# kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup kubernetes.default
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.43.0.1 kubernetes.default.svc.cluster.local
pod "busybox" deleted

# kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup www.google.com
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      www.google.com
Address 1: 2607:f8b0:4004:801::2004 iad30s10-in-x04.1e100.net
Address 2: 172.217.7.196 iad30s10-in-f196.1e100.net
pod "busybox" deleted

_______________________________________________________________________
**As I suspected: it's getting external DNS from somewhere:**
_______________________________________________________________________
# kubectl -n kube-system get pods -l k8s-app=kube-dns --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do echo "Pod ${pod} on host ${host}"; kubectl -n kube-system exec $pod -c kubedns cat /etc/resolv.conf; done
Pod kube-dns-74c78b5c6c-prtk8 on host 10.0.10.27
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

# No DNS servers known.

nameserver 8.8.8.8
nameserver 8.8.4.4


________________________________________________________________________________________________
**It appears it's getting the commented data from /run/systemd/resolve/resolv.conf

/etc/resolv.conf is being used by the host however, and I can thus resolve the DNS correctly from there.  How should this be resolved?**
____________________________________________________________________________________________________________

**Comment by ssirag** [comment]
**Update; ** per https://unix.stackexchange.com/questions/442598/how-to-configure-systemd-resolved-and-systemd-networkd-to-use-local-dns-server-f I've updated my /etc/systemd/resolved.conf file with our specific internal DNS information and restarted the cattle-agents... it has resolved this issue

**Comment by ssirag** [comment]
Correction: the cattle-agents resolved once i made the change on all hosts, but now the result is the same:

**This command:**
```
kubectl -n kube-system get pods -l k8s-app=kube-dns --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do echo "Pod ${pod} on host ${host}"; kubectl -n kube-system exec $pod -c kubedns cat /etc/resolv.conf; done
```

**Gives this result:**
```
Pod kube-dns-74c78b5c6c-spnhj on host 10.0.10.26
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

# No DNS servers known.

nameserver 8.8.8.8
nameserver 8.8.4.4
```

Despite the fact that all hosts have our specific internal DNS info in the /etc/systemd/resolved.conf file and have been restarted.

```/run/systemd/resolve/resolv.conf```
and 
```systemd-resolve --status```
both return the correct internal DNS servers, but the hosts are still defaulting to the Google DNS.

**Comment by ssirag** [comment]
Currently cattle-cluster-agent is in a crashloop backoff state (I've restarted it multiple times) while the cattle-node-agents are all working.

**Comment by superseb** [comment]
Docker defaults to these name servers last time I checked, there is some more info here: https://github.com/docker/for-linux/issues/488

When I change my name servers on my Ubuntu Bionic hosts and delete the kube-dns pods, it comes back with the changed name servers. There seems to be a configuration issue.

**Comment by superseb** [comment]
Let me know if you need help on this.

**Comment by ssirag** [comment]
I fixed it this way:

kubectl -n kube-system get pods -l k8s-app=kube-dns --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do echo "Pod ${pod} on host ${host}"; kubectl -n kube-system exec $pod -c kubedns cat /etc/resolv.conf; done

The above command revealed it wasn't getting internal dns servers from /etc/resolve.conf as expected

Research indicates that Ubuntu 18.04 uses systemd-resolved.

I used this article to add dns info to /etc/systemd/resolved.conf:

https://unix.stackexchange.com/questions/442598/how-to-configure-systemd-resolved-and-systemd-networkd-to-use-local-dns-server-f

This has resolved the issue.
