### ISSUE TITLE
Show "Updated" instead of "Created" time in workload/pod tables

### ISSUE THREAD

**Issue by patrikbeno** [rancher/rancher#19770]
Enhancement / Feature Request
(Rancher 2.2.2)

Workloads page, Image column contains useful grey text info about when the workload was CREATED.

Since workloads are often updated during development cycle (image version upgrades), more relevant information to show here is when the workload was UPDATED.

For simple one-time deployments, UPDATED is the same as CREATED, and CREATED is also shown in workload detail, so no information is lost.

Same applies for list of pods in workload detail

**Comment by gabrielcalderon** [comment]
+1 on this, it would help a lot for debugging new images, etc.

**Comment by deniseschannon** [comment]
Maybe we could add in `updated` instead of replacing `created`

**Comment by vincent99** [comment]
There is no API field for updated on workloads (and Pods are not updatable at all, in general).
