### ISSUE TITLE
Admin user is not prompted for entering "CURRENT PASSWORD" when changing password.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1978]
Server version - Built on Sep 4

"CURRENT PASSWORD" field is not present in the "Edit Account" page when admin user attempts to change the password.

**Comment by vincent99** [comment]
This is a feature.  They're the admin, they don't know the user's password and don't need it to just go into the API/DB and change it.

**Comment by sangeethah** [comment]
Does this apply to the case when admin  is changing his own  password as well  by using "Change Password" option ? In this page , there is also an option to change "Account Type" , is this required here ?

**Comment by vincent99** [comment]
Yes, the "Change Password" action is really the same as editing the account.  If you're a user the only thing you can change is your password, but if you're an admin then you can edit whatever you want about yourself.
