### ISSUE TITLE
Custom nodeport ranges not respected by service gui

### ISSUE THREAD

**Issue by GiGurra** [rancher/rancher#19798]
tested in v2.2.2:

Since https://github.com/rancher/rancher/issues/11732 we are able to configure the cluster nodeport range. However this change is not respected by the rancher service edit gui, where any number outside the standard range is auto-reverted.

Workaround: 
Select cluster IP, set the port, then set back to NodePort.

The ports then work as expected, but I suppose the gui should allow us to do it normally :)

How to recreate the bug.
1. Create a cluster with extended nodeports (e.g. 10 000 - ... instead of 30 000 - ...)
2. Create a workload
3. Add nodeport service to the workload, and pick port 11 000 or so
4. the gui will automatically revert to 30 000

**Comment by mrajashree** [comment]
Hi @GiGurra since [this](https://github.com/rancher/rancher/issues/18275#issuecomment-484410538) issue also mentions the bug, we are tracking it with this issue. So this will be fixed along with the linked issue. Closing as dup
