### ISSUE TITLE
Docker Daemon process Consuming complete host memory 15gb RAM

### ISSUE THREAD

**Issue by brahmos-92** [rancher/rancher#19791]
**What kind of request is this (question/bug/enhancement/feature request):**
Issue with Memory consumption on rancher hosts

**Steps to reproduce (least amount of steps as possible):**
We are using Rancher v1.6.18. We have around 220 stacks running in rancher farm.
Infra Details:
3 Rancher Masters
1 Rancher Db Host
70 Rancher Hosts
It is seen that the Docker process consumes complete memory of the Rancher host. This make the Rancher hosts unresponsive.
In order to resolve this we need to clean up the whole Rancher Hosts which include:
Stopping all the stacks
Removing Docker images, containers, Volumes
Removing /var/lib/docker, /var/lib/rancher
Reboot the Rancher host
Adding back to Rancher farm
Current Resource Limits:
Memory: 13000
mCPU: 4
Host Details:
16GB RAM
Rhel 7
Can you let us know how can we restrict the memory for docker process on Rancher Host?
Is there a way we can Manage the CPU and Memory usage?
Also should we upgrade to 1.6.26 version? Will this help resolve the Memory issue on the rancher hosts?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher 1.16.8
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):
We are using Cattle
```
(paste the output here)
```

- Docker version (use `docker version`):
1.13.1
```
(paste the output here)
```

**Comment by superseb** [comment]
Don't see why an issue is needed for this, let's continue in https://forums.rancher.com/t/rancher-v1-6-18-facing-memory-issues-on-rancher-host/14030
