### ISSUE TITLE
Detail view of the Container should include details set from "Advanced Options"->Command,volumes,networking,security/host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#198]
Currently the detail view of the container (When I follow the container name link from the "Containers" page) includes only the name , hostIp and image name of the container.

It would be more useful if we also show all the other advanced options with which this container was launched.

Edit Container option shows port mapping information. This screen also does not include any other advanced options. Is this because , the value of these settings are not editable once the instance is running?

**Comment by flaccid** [comment]
Currently only a few items are editable in a container service that is not started yet.
Ideally you should be able to edit everything in the same way when initially creating the container.
At the moment to make a small edit such as a port or env var, you need to clone the service (problem is you cannot use the same name) or recreate it.
![screen shot 2015-08-04 at 9 54 04 am](https://cloud.githubusercontent.com/assets/131730/9050251/241eaefe-3a8f-11e5-9fe7-d098978e5124.png)

**Comment by vincent99** [comment]
Docker containers are immutable.  The only things you can change are things that Rancher implements outside of Docker.

**Comment by flaccid** [comment]
@vincent99 this is true however I haven't pressed start yet so not containers exit yet. Because I forgot a setting I now have to either 1. rename the container service, clone it, name the new one (this is because service names are unique and I want the same service name), delete the old one, update the config, then start; or 2. delete the container service, create a new one with the missing setting, start.

**Comment by vincent99** [comment]
Frankly that seems even more confusing to me; we'd have to have a new state for "stopped but never started" and enforcement of it in the API for the off chance you forgot something *and remember that before starting*.

Actually we don't even have a construct in the API schema for a field that is editable depending on the value of another field, that would make it significantly more complicated for the client to handle weird partially applied or conflicting update situations.

If you further allow going back to that state by deleting all the containers, then it's encouraging what I would call an anti-pattern of deleting and recreating ithe world nstead of testable and recoverable zero downtime upgrading (create new, test, make live, remove old).

Alias services allow you to have a fixed name and point it to different services.  Or rancher-compose has an upgrade action that does the create and scaling down/up automatically.  This is only in the CLI for now but will go into the UI eventually.

**Comment by flaccid** [comment]
Very understandable points there. Its not a huge deal. I think of a container service like a blueprint which is mutable and currently existing containers for that service are immutable. I guess you can say the service is like a class which is instantiated (sorry I'm sounding like captain obvious here). The ability to not edit your class before instantiating is a usability issue but I assume a basic message in the UI about why its not editable even before being started might do the trick from a usability point of view. But again, Its not a big deal and I know the workaround when I need to modify the service.

**Comment by sangeethah** [comment]
It would also be very helpful to have the external_id value of the container ( maps to the docker id) shown in the container detail view.

**Comment by ebuildy** [comment]
It's a pity to have to clone 2 times services/containers in order to keep the same name/ports, why is not possible to edit the full settings then click on save could execute a kind of rolling upgrade? (delete each service containers 1 by 1 in order to "refresh" them).

Thanks you,

**Comment by deniseschannon** [comment]
@ebuildy What you're suggesting would definitely be an enhancement request, but personally I like the idea. We'd need to somehow make explicit it to the users that if you are editing the service, then you are essentially doing a rolling upgrade. Some users may object at doing a rolling upgrade on just editing. 

I've created an issue for this idea to see if other users would be interested. #1930

**Comment by tfiduccia** [comment]
Upgrade is now available and the container details page has been redone to show important information.

Closing
