### ISSUE TITLE
[cli] Missing rancher/cli:2.2.0 image on dockerhub

### ISSUE THREAD

**Issue by jonesbusy** [rancher/rancher#19800]
Hi,

Is there any plan to release the 2.2.0 CLI on dockerhub ?

works :

```
docker pull rancher/cli:v2.0.4
```

doesn't work 

```
docker pull rancher/cli:v2.2.0
```

The cli was released weeks ago but the dockerhub registry has not been updated since a long time.

It would be very useful for environment that rely on docker images (like Jenkins) for their build tools.

Thanks in advance.

**Comment by alena1108** [comment]
@jonesbusy the image name for v2.2.0 is `rancher/cli2:v2.2.0`

**Comment by jonesbusy** [comment]
My bad all good. Thank you
