### ISSUE TITLE
RFE CNI component healthcheck propagating to node/cluster health

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#19817]
**What kind of request is this (question/bug/enhancement/feature request):**

RFE

**Steps to reproduce (least amount of steps as possible):**

Currently issues affecting the CNI components in a cluster, which may cause pod network connectivity impacting workloads, do not result in any health warning/message at either the node or cluster level in Rancher. The user request is for unhealthy networking components to reflect in node/cluster health status.

As a workaround in Rancher v2.2 a user can enable cluster monitoring and then create an alert with the following type of expression, to check for instances of unavailable network pods:

kube_daemonset_status_number_unavailable{daemonset="canal",namespace="kube-system"}

gz#6986

**Comment by stefanlasiewski** [comment]
It might be helpful for Rancher to provide a Notifier which allows me to show when my own own custom alerts on the Dashboard, next to the other alerts.

For testing, I set up some monitors which alert for certain conditions. It would be nice if those alerts showed up here:

![image](https://user-images.githubusercontent.com/142752/57170737-ca348280-6dc3-11e9-84c7-fcc4500c4eaa.png)
