### ISSUE TITLE
Add Hong Kong to AWS regions

### ISSUE THREAD

**Issue by mkhmylife** [rancher/rancher#19810]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature request

**Steps to reproduce (least amount of steps as possible):**

The Hong Kong region is becoming available starting from today, please add Hong Kong to the AWS regions list.

https://aws.amazon.com/about-aws/whats-new/2019/04/announcing-the-aws-asia-pacific-hong-kong-region/

**Comment by loganhz** [comment]
Fixed in 2.2.4
