### ISSUE TITLE
AKS Regional Availability in South Central US

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#19811]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
We are limited to deploy into South Central US in Azure. When will this region be added to rancher? 
https://docs.microsoft.com/bs-latn-ba/azure/aks/container-service-quotas

**Environment information**
- Rancher version:
v2.2.2

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/19475 and https://github.com/rancher/rancher/issues/19562
