### ISSUE TITLE
footer style

### ISSUE THREAD

**Issue by DarrenHou1993** [rancher/rancher#19815]
*Describe your issue here*

![image](https://user-images.githubusercontent.com/9291785/56729291-7a343b00-6787-11e9-8521-38de208ac8b7.png)

please use `position: fixed` instead of `position: absolute`;

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`containers.run`|

**Comment by vincent99** [comment]
We are not going to do that. There is nothing frequently  used in it and no reason the footer needs to take up screen space all the time.
