### ISSUE TITLE
Every time workloads refresh, other restful APIs get stuck

### ISSUE THREAD

**Issue by LincolnBruce** [rancher/rancher#19814]
Version v2.2.2
As shown in the following figure
![image](https://user-images.githubusercontent.com/7814560/56713153-8908f680-6763-11e9-907e-e63c5abdf50e.png)

The interface will become very slow, and I will help provide the log if needed.
![image](https://user-images.githubusercontent.com/7814560/56713222-c8374780-6763-11e9-8759-06dab7b625f9.png)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/20052
