### ISSUE TITLE
Make Rancher dynamically support all available regions in EKS/AKS/GKE.

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#19812]
What kind of request is this (question/bug/enhancement/feature request):
Enhancement

Steps to reproduce (least amount of steps as possible):
As cloud providers add support for new regions, is there a way to dynamically support the newer ones.  Currently, it seems to be hardcoded to a limited list in Rancher

Environment information
Rancher version:
v2.2.2

**Comment by vincent99** [comment]
We would love to not maintain a hardcoded list, but AFAIK there is no API for what regions EKS is available in, or what instance types are available in EC2.

Or at least no practical one.  There is a billing API that indirectly contains e.g. instance type names, but it would require downloading hundreds of megabytes of noise (and a key that has access to get to it).

**Comment by dkeightley** [comment]
@vincent99 two options that could be workable for EKS:

Region and service availability is now [available via SSM](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters.html#parameter-store-public-parameters-global-infrastructure)

For instance types, the JSON payload from a GetAttributeValues call should be accurate for the full list, however it doesn't account for instances available on a region basis.

`aws pricing get-attribute-values --service-code AmazonEC2 --attribute-name instanceType --region us-east-1`

**Comment by vincent99** [comment]
I suspect that falls into the `(and a key that has access to get to it)` part... Our company is probably relatively lax with the accounts engineering uses for experimentation compared to other environments running serious stuff.  And in tehre my normal key for it does not have permission to call that.
