### ISSUE TITLE
Add T3a AWS instance types (1.6)

### ISSUE THREAD

**Issue by krumware** [rancher/rancher#19826]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Result:**
Add T3a instance types in the drop-down for AWS hosts. 
(similar to https://github.com/rancher/rancher/issues/15502)

**Other details that may be helpful:**

id | vCPU | ECU | Memory (GiB) | Instance Storage (GB) | Linux/UNIX Usage 
-- | -- | -- | -- | -- | --
t3a.nano | 2 | Variable | 0.5 GiB | EBS Only | $0.0047 per Hour
t3a.micro | 2 | Variable | 1 GiB | EBS Only | $0.0094 per Hour
t3a.small | 2 | Variable | 2 GiB | EBS Only | $0.0188 per Hour
t3a.medium | 2 | Variable | 4 GiB | EBS Only | $0.0376 per Hour
t3a.large | 2 | Variable | 8 GiB | EBS Only | $0.0752 per Hour
t3a.xlarge | 4 | Variable | 16 GiB | EBS Only | $0.1504 per Hour
t3a.2xlarge | 8 | Variable | 32 GiB | EBS Only | $0.3008 per Hour

https://aws.amazon.com/ec2/pricing/on-demand/

**Environment information**
- Rancher version: 1.6

**Comment by krumware** [comment]
Apologies, I previously opened a PR for this but mis-tagged the issue by not including the full repository path. The PR has been updated to be linked properly.

**Comment by ryanrca** [comment]
Can this get targeted to v2.2 (or 2.3) also?
I searched but could not tell if support has been added to 2.x yet. It's not in 2.2.

**Comment by krumware** [comment]
That update may need to be a separate PR, since 1.6 is in a specific maintenance branch.

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc1`, UI tag `1.6.51`

**Comment by soumyalj** [comment]
Tested with rancher/server:v1.6.29-rc2. 
T3a AWS instance types are available for selection in the dropdown list :

![Screen Shot 2019-09-25 at 11 53 39 AM](https://user-images.githubusercontent.com/18536626/65630920-3db17900-df8b-11e9-8934-afdb0fc0dde1.png)

The nodes were added to an environment successfully and the setup was functional
