### ISSUE TITLE
Local Auth - When a user in "inactive" state tries to  log , present a message that indicates he is not allowed to log in because of his state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1982]
Server - Build from master - Sep 4

Steps to reproduce the problem:
As admin user , De activate an existing user.
Try to log in as this user who is currently in "inactive" state.

User is presented with - "Username or Password incorrect" message,

It would be better to present a message that indicates that he is not allowed to log in because of his inactive state.

**Comment by hibooboo2** [comment]
@vincent99

**Comment by vincent99** [comment]
The API doesn't (and shouldn't) tell the user the reason why the request to authenticate failed.  I suppose we could tweak the message to say "...or your account is locked", but that seems overly verbose.
