### ISSUE TITLE
Feature request: multi-infrastructure clusters

### ISSUE THREAD

**Issue by steebchen** [rancher/rancher#19824]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

It would be awesome to be able to create clusters which run on multiple infrastructure providers. This probably does not make much sense on kubernetes providers such as GKE, but with my use-case on bare metal it would. I'd like to combine servers from different infrastructure providers for different purposes (i.e. storage servers from one and CPU servers from another).

Right now, you can only choose from a single infrastructure provider. Instead of only adding node pools from that single provider, I'd like to create clusters independent of any infrastructure provider and then create node pools which are bound to an infrastructure provider instead.

For example:

1. create cluster "my-cluster"
2. add node pool "compute" from infra provider "Hetzner"
3. add node pool "storage" from infra provider "DigitalOcean"

I'm not sure if this comes with any complicated issues such as different networking between providers and so on, but currently I am using this method without rancher and it's working completely fine.

**Comment by vincent99** [comment]
This is all actually already possible with custom nodes or with node drivers through the backend/API.. but is not exposed in the UI because it's not a good experience we can support.

From [a recent time someone else asked](https://devops.stackexchange.com/a/6893/4062):

> Kubernetes itself is really not meant for that use-case. A cluster is generally a set of machines in the same provider with close proximity (latency) to each other.
> 
> Kubernetes itself is really [not meant](https://kubernetes.io/docs/setup/multiple-zones/) for that use-case.  A cluster is generally a set of machines in the same provider with close proximity (latency) to each other.
> 
> - Etcd (and therefore API/CLI/UI/scheduling/everything) performance depends heavily on the (worst-case) latency between all members.
> - Only one cloud-provider integration (storage providers, L4 load balancers) can be configured and most assume nodes are all in the same "region" or similar concept.
> - Commonly used network plugins assume adjacency and/or provide no encryption or authentication suitable for communicating across untrusted networks/the internet.
> - Communication between pods/services within the cluster has no consideration for where the "nearest" place to reach a pod for that service is, so latency from a pod to another service can be large (however far apart the two worst nodes are) and unpredictable (sometimes close, sometimes far).  (There is an option for nodePorts to *always* go to a local pod, but if there is no local pod it will just get dropped).
