### ISSUE TITLE
Add logging system chart v0.0.2 to use `rancher/jimmidyson-configmap-reload:v0.2.2`

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19836]
As all images have to be mirrored into rancher dockerhub, I've pushed `rancher/jimmidyson-configmap-reload:v0.2.2`. @aiwantaozi as a part of fixing this issue, we have to:

- [x] add a new logging system chart having a new image.
- [x] change Rancher to use a new system chart version.

https://github.com/rancher/rancher/issues/19435

**Comment by aiwantaozi** [comment]
Sure

**Comment by bmdepesa** [comment]
rancher/rancher:master 5d74988c

* Enabled cluster logging
* Image used is `jimmidyson/configmap-reload:v0.2.2`
