### ISSUE TITLE
Local Auth - Enforce some policies for password length/characters. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1983]
Server version - Build from Sep 4
Currently we are allowed to have 1 letter character as password when creating accounts.
Enforce some policies for password length/characters.

**Comment by hibooboo2** [comment]
@vincent99

**Comment by hibooboo2** [comment]
This is on purpose not a bug.

**Comment by hibooboo2** [comment]
This is not an auth system for prod. So we have no pass policy on purpose.

**Comment by vincent99** [comment]
1 character is a policy :smile:

I'd be ok with a minimum length as a publicly readable setting (so the UI can enforce it too), but not any crazy this many of these kinds of characters craziness.  https://xkcd.com/936/

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/5973

**Comment by sangeethah** [comment]
Tested with Rancher-server version - v 

Set api.auth.local.validate.url to the password valiator url.
Enable local auth.

Password validator is called during the following workflow:

1. Adding System admin account as part of enabling local auth.
2. When adding user/ admin account. This does not work and is tracked in https://github.com/rancher/rancher/issues/6358

3. When changing password for existing accounts

Handling http return code:
- When the password validator returns any code between 200-299 -- > It is considered success.
- When the password validator returns any code between 400-499 -- > User is presented with the exact error message that was sent. Error code that is sent is not presented to the user.
- When the password validator returns any other code:
"Error talking to validator" error message is presented to the user and "500 Internal Server Error" Http code.

**Comment by sangeethah** [comment]
Related bugs:
https://github.com/rancher/rancher/issues/6362
https://github.com/rancher/rancher/issues/6363
