### ISSUE TITLE
Missing Eks cluster driver in UI / V2.2.2

### ISSUE THREAD

**Issue by Amos-85** [rancher/rancher#19838]
In Rancher V2.2.2 for enabling eks cluster driver form ui,
need to enable ecs which is wrong term.

eks for some reason missing in this version.

**Comment by deniseschannon** [comment]
@Amos-85 by default, EKS  and ECS is enabled. did you disable it and then try to enable it after?

**Comment by Amos-85** [comment]
yes @deniseschannon ,
in previous versions I have disabled all the cluster drivers.
in last version 2.2.2 I want to enable only eks and I didn't see it in the ui.
after enabling ecs it's actually enabled eks.
it's was confusing cause ecs and eks is not same aws services.

**Comment by deniseschannon** [comment]
@Amos-85 did you make sure to differentiate between cluster and node drivers? There are tabs at the top. 

Can you provide a screenshot of where you enabled the cluster driver?

**Comment by Amos-85** [comment]
I have enabled it in the cluster drivers list in the global settings.On May 4, 2019 01:22, Denise <notifications@github.com> wrote:@Amos-85 did you make sure to differentiate between cluster and node drivers? There are tabs at the top.
Can you provide a screenshot of where you enabled the cluster driver?

**Comment by tfiduccia** [comment]
Version - 2.2.2 & Master
This is indeed true.  The Amazon EKS driver is named Amazon ECS under cluster drivers.  We should probably fix that.
![image](https://user-images.githubusercontent.com/11514927/58501216-b406b180-8138-11e9-81e1-d35c489bcf0c.png)

**Comment by davidnuzik** [comment]
Version: master (v2.3) (5/31/19)

This is a simple translation file fix. I can confirm that we now show the correct "Amazon EKS" for this cluster driver rather than the incorrect "Amazon ECS" as previously seen.
Checked en-us and zh-hans (which contain fixes), then I checked each and every other language. They are all correct.
