### ISSUE TITLE
Cannot assign notifier for cluster alerts

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#19842]
I recently upgraded to Rancher 2.2.2 and have enabled Prometheus monitoring on my cluster. If I select the cluster and navigate to Alerts section, I see a number of new default alerts. However, all of them do not have a notifier set, nor do I get the option to set them.

![image](https://user-images.githubusercontent.com/13228540/56846749-b5b62e80-6887-11e9-9d50-f410ed2669af.png)

![image](https://user-images.githubusercontent.com/13228540/56846787-307f4980-6888-11e9-8cf5-cf52c71e9dc7.png)

**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
Upgrade to Rancher 2.2.2, enable cluster level Prometheus monitoring. Go to Tools > Alerts

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 16 cores/32G memory
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by deniseschannon** [comment]
You need to edit the alert group to set the notifier. You can not individually send a notifier per alert rule. 

Next to the "Add Alert Rule", edit and scroll down:

<img width="1275" alt="Screen Shot 2019-05-02 at 3 42 39 PM" src="https://user-images.githubusercontent.com/11410997/57111474-0f3bb480-6cf1-11e9-81f4-d78101a60fdb.png">
