### ISSUE TITLE
Error response from daemon: client is newer than server

### ISSUE THREAD

**Issue by wsmhz** [rancher/rancher#19843]
**try to add a host**

`[root@VM_0_6_centos developer]# sudo docker run -e CATTLE_AGENT_IP="118.25.144.155"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.1 http://118.25.144.155:8201/v1/scripts/127DFBB1680BE07A0A90:1546214400000:L2Zy46KCVGCw3w9ZfLb91tHmis

5217718d108296556491c46eaf58284c914ac9330f2a2d25a932679d15fccf24

[root@VM_0_6_centos developer]# docker logs 5217718d108296556491c46eaf58284c914ac9330f2a2d25a932679d15fccf24

**Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)**
`

**there is docker version**

`[root@VM_0_6_centos developer]# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
`

**why the version is different? Other operations are normal**

**Comment by superseb** [comment]
Seeing the agent version and Docker version, you are running way behind on versions here. Even Rancher v1.5.0 (https://github.com/rancher/rancher/releases/tag/v1.5.0) didn't support Docker 1.9.

I suggest using the latest stable (rancher/server:v1.6.26) and use https://rancher.com/docs/rancher/v1.6/en/hosts/ to setup the host(s) you want to add.

Let me know if you run into anything using the newest versions.
