### ISSUE TITLE
Vulnerability for ports 2379, 2380, 6443. SSL Certificate Cannot be trusted.

### ISSUE THREAD

**Issue by rigert3alekaj** [rancher/rancher#19844]
I have a rancher 2 cluster running in one of my environments. 
On all the hosts where etcd, controlplane are deployed am finding a SSL certificate cannot be trusted vulnerability on ports 2379,2380,6443.

Steps to reproduce (least amount of steps as possible):
1. Deploy etcd/controlplane node.
2. Scan node using a vulnerability scanning tool( Used Nessus Enterprise and OpenVas).
Results:
Certificate signed by unknown authority found on ports 2379,2380,6443.

From the Rancher documentation i only found valuable information regarding custom SSL certs only for the Rancher Web server, but none information for the certificates that are generated on the nodes running etcd/controlplane services.

Maybe i missed something, but if not, i think there should be a way to control how those certificates are generated, at least have the chance provide a custom certificate authority.

Rancher Version: rancher/rancher:v2.1.5
Installation Option: Single Install

**Comment by vincent99** [comment]
RKE can either generate a self-signed cert or produce CSRs for you to provide a signed cert. 
(It does not take a CA cert/key and then sign certs off that)

https://rancher.com/docs/rke/latest/en/cert-mgmt/

A cert that the scanning tool does not have the chain for is not a "vulnerability".
