### ISSUE TITLE
Support for North Central US in AKS

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#19853]
What kind of request is this (question/bug/enhancement/feature request):
Enhancement

Steps to reproduce (least amount of steps as possible):
West Central US and North Central US are expected to become available in Q2 2019
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=kubernetes-service

Add support for these two regions when they become available

Rancher version:
v2.2.2

**Comment by superseb** [comment]
https://azure.microsoft.com/en-gb/updates/general-availability-azure-kubernetes-service-in-north-central-us-japan-west/

**Comment by alena1108** [comment]
North support is already available, so we can enable it in Rancher. Created a separate ticket for West Central US support https://github.com/rancher/rancher/issues/20069

**Comment by alena1108** [comment]
@westlywright let me know if there is some backend work needed in order to enable the UI support.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/20/19)

I can confirm the addition of "North Central US" region for AKS.
![image](https://user-images.githubusercontent.com/45179589/57735756-932f5e00-765a-11e9-885a-5a37cab067a4.png)

The query to aksVersions looks correct and the cluster config looks good as well (azureKubernetesServiceConfig) I see `location: "northcentralus"` in the cluster creation request and in the API.

My AKS cluster with this Location provisioned successfully and shows as the correct location in Azure web console.

The original issue mentions West Central US support as well and this is tracked separately in #20069 as it is not yet available.
