### ISSUE TITLE
Rancher 2 cannot add custom project role where it says it already exists

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#19860]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create two custom project roles. Go into the project and try to give a user the lower role (before custom) in the list.

**Result:**
Either defaults to the option above it or if the user already has the option above it, it will error saying it already exits.

**Other details that may be helpful:**
These custom roles are the same as the OOTB ones with just the create namespace removed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | v2.2.2
User Interface | v2.2.41
Helm | v2.10.0-rancher10
Machine | v0.15.0-rancher6-1

- Installation option (single install/HA):
HA

![Screen Shot 2019-04-29 at 10 25 28 AM](https://user-images.githubusercontent.com/4107699/56907067-24061700-6a69-11e9-886f-fa03c574f3e1.png)

**Comment by tfiduccia** [comment]
Version: v2.2.4
I am not able to reproduce this issue.

**Comment by mrajashree** [comment]
Reproduced this on master 07/01
**Steps to repro**
1. Create custom project-member and project-owner roles by inheriting the built-in roles
2. Lock the built-in project-member and project-owner roles
3. Add user to a project as `Custom Project Member`
<img width="1337" alt="Screen Shot 2019-07-01 at 3 17 48 PM" src="https://user-images.githubusercontent.com/10672776/60470108-15c4aa80-9c14-11e9-8498-518cde731083.png">
That succeeds
4. Add same user to the same project as `Custom Project Owner` 
<img width="1167" alt="Screen Shot 2019-07-01 at 3 17 29 PM" src="https://user-images.githubusercontent.com/10672776/60470126-2d039800-9c14-11e9-9beb-a2df5ed563b4.png">
Fails with this error

This same request succeeds if done through v3/projectroletemplatebindings api
Seems to be something related to order in which the roles are presented on the add members page in UI maybe.

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.5

(Basically follow steps outlined by Rajashree above https://github.com/rancher/rancher/issues/19860#issuecomment-507447463)

1. Create custom project-member and project-owner roles by inheriting the built-in roles
2. Lock the built-in project-member and project-owner roles
3. Add user to a project as `Custom Project Member`
![image](https://user-images.githubusercontent.com/45179589/61669204-0f19d800-ac94-11e9-980b-2c587f2e4dd7.png)

This succeeds.  

4. Add same user to the same project as `Custom Project Owner` 

![image](https://user-images.githubusercontent.com/45179589/61669178-f6a9bd80-ac93-11e9-911b-759596262235.png)

Fails with this error pictured above.

**Validation:**
master-head (v2.3) (7/22/19) (`5894323d`)

1. Create custom project-member and project-owner roles by inheriting the built-in roles
2. Lock the built-in project-member and project-owner roles
3. Add user to a project as `Custom Project Member`
4. Add same user to the same project as `Custom Project Owner` 

This now succeeds without any issues. Confirmed that the UI now has two entries listed:
![image](https://user-images.githubusercontent.com/45179589/61671520-e21df300-ac9c-11e9-819b-9c7b67037537.png)

Review UI/HTTP/API and they appear correct.
