### ISSUE TITLE
[UI] Confusing example placeholder Add persistent volume

### ISSUE THREAD

**Issue by rene-demonsters** [rancher/rancher#19864]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement, copy update

**Steps to reproduce (least amount of steps as possible):**
1. Go to your Cluster overview in Rancher
2. Storage > Persistent Volumes > Add persistent Volume
4. Open the customize menu
5. Click on Add node selector
6. The placeholder in the first textbox is confusing and leads to a broken config

**Result:**
![image](https://user-images.githubusercontent.com/20322259/56916742-f6958980-6ab9-11e9-99c1-5c6e56b61449.png)
The first field shows "e.g. hostname". This would imply that "hostname in example-node1" works. However it does not. It has to be `kubernetes.io/hostname in example-node1`. It would be better if the copy accurately reflected this by stating "e.g. kubernetes.io/hostname".

**Environment information**
- Rancher version: 2.2.2

**Comment by davidnuzik** [comment]
Version: master-head (8/8/19)

The placeholder ("helper") text has been changed from "e.g. hostname" to "e.g. kubernetes.io/hostname" to make this more clear to the user.

![image](https://user-images.githubusercontent.com/45179589/62733450-801ef680-b9db-11e9-9d5f-5b064220b82a.png)
