### ISSUE TITLE
Private catalog charts not updating in HA

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#19869]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create private catalog in HA cluster using github as the host

**Result:**
Updates/changes will not propagates
Current message: lstat management-state/catalog-cache/95af757078a2fbe90d32c2e4bdd4e60dcb9f30906330bd7002d5e9e21de5e4b1/charts/cerberus/v16.282.0: no such file or directory 

**Other details that may be helpful:**
We were able to remediate the issue by deleting the catalog and adding it back, but the issue re-propagates immediately after. I will also provide that this is a Rancher Private Catalog not a Helm Catalog.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/19638
