### ISSUE TITLE
Unable to add second Private Registry in cluster config results in TypeError

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19871]
Version: v2.2.3-rc1

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to create any RKE cluster. Try to add two private registries

**Result:**
You will get an uncaught TypeError upon trying to add a second entry.
```
Uncaught TypeError: Cannot read property 'pushObject' of undefined
    at n.addRegistry (0:189294)
    at e._join (0:35263)
    at e.join (0:35019)
    at p (0:23941)
    at 0:42190
    at s (0:20930)
    at n.addRegistry (0:42189)
    at n.addRegistry (0:192154)
    at n.send (0:58931)
    at n [as send] (0:58190)
```

**Comment by davidnuzik** [comment]
I am re-opening the issue for now based on discussions in this area. We might not want the ability to have more than one entry for private registry for the cluster config...

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/19325

**Comment by westlywright** [comment]
Is resolved by https://github.com/rancher/ui/pull/2984

**Comment by alena1108** [comment]
can be tested in rc9

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc9

The UI for Private Registries for cluster config has been fixed (see the PR). We removed the option to have more than one entry because only one should be used. Also, this one is always default. It's for system-images and the help text under Private Registries accordion explains this. (%cruPrivateRegistry.title.label%)

![image](https://user-images.githubusercontent.com/45179589/57575091-25d0c280-73f9-11e9-95ec-f9affcd8e222.png)

Notice the subtext for "Private Registries" this explains what the registry is for.

Once Enabled you can config the registry url, user, and password just like before. I validated the fields and ensured HTTP and API are correct and enforce their respective types.

![image](https://user-images.githubusercontent.com/45179589/57575101-5b75ab80-73f9-11e9-8687-5010c3bc7ef6.png)
