### ISSUE TITLE
Backport UI and Cluster Unstable when configmap entries gets high, 22k+ #18571

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19880]
backport for https://github.com/rancher/rancher/issues/18571

**Comment by cjellick** [comment]
will be in rc4

**Comment by bmdepesa** [comment]
* Reproduced in v2.2.2
* Deploy Rancher v2.2.3-rc4
* Followed steps to reproduce
* Verified only one configmap being created
* Automated test `tests/validation/tests/v3_api/test_app.py:test_tiller` passing
* UI & Cluster remain stable
