### ISSUE TITLE
Backport UI - Catalog apps page extremely slow to load for large clusters #17101

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19881]
Backport for https://github.com/rancher/rancher/issues/17101

**Comment by cjellick** [comment]
will be in rc4

**Comment by bmdepesa** [comment]
* Reproduced in v2.2.2
* Deploy Rancher v2.2.3-rc4
* Followed steps to reproduce
* Verified only one configmap being created
* Automated test `tests/validation/tests/v3_api/test_app.py:test_tiller` passing
* UI & Cluster remain stable
