### ISSUE TITLE
Unable to bring up cluster on vsphere

### ISSUE THREAD

**Issue by sarmak1179** [rancher/rancher#19888]
**What kind of request is this (question/bug/enhancement/feature request):**
Question and Bug (not sure, if I am missing anything in the configuration)

**Steps to reproduce (least amount of steps as possible):**
1. Provision a single node rancher cluster on CentOS using something like:
docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 -v /var/log/rancher/auditlog:/var/log/auditlog  -v /var/lib/rancher/:/var/lib/rancher -v /root/.docker/machine/certs/server-cert.pem:/etc/rancher/ssl/cert.pem  -v /root/.docker/machine/certs/server-key.pem:/etc/rancher/ssl/key.pem  -v /root/.docker/machine/certs/ca.pem:/etc/rancher/ssl/cacerts.pem -e AUDIT_LEVEL=1 rancher/rancher:stable
2. Add a node template for vsphere provider
Mostly the default configuration of the vsphere cluster details
3. Add the vpshere cluster with a node pool

**Result:**
The vm is getting added and after sometime I can see the following message on rancher logs:
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "xx.xx.xx.xx:2376": remote error: tls: bad certificate
The node gets deleted and restarted again for provisioning.

**Other details that may be helpful:**

Added a query into Rancher 2.x forums mentioning the options specified https://forums.rancher.com/t/vsphere-how-to-disable-tls-or-provide-ca-certs/14096

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.1.8
- Installation option (single install/HA):
Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Infrastructure Provider (vsphere)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
2CPU 20Gigs RAM
- Kubernetes version (use `kubectl version`):
Tried selecting both 1.11.5 and 1.13.5 on the cluster

- Docker version (use `docker version`):
On the host
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by wenwenbaba** [comment]
I have encountered the same problem. Can you solve it?
@sarmak1179
