### ISSUE TITLE
kube-dns goes into CrashLoopBackOff

### ISSUE THREAD

**Issue by rborsaru** [rancher/rancher#19887]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Rancher 2.x on AWS.
Set up a Custom rancher cluster, by selecting Amazon as the cloud provider.

**Result:**
kubectl get po -n kube-system -o wide|grep kube-dns
kube-dns-6db5b57f97-wxzls                 1/3     CrashLoopBackOff   25         28m

**Other details that may be helpful:**
The only error i can find in the logs is in sidecar logs:
W0430 07:00:45.832893       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:54210->127.0.0.1:53: read: connection refused

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.7
- Installation option (single install/HA):
single install
AWS with three EC2 nodes. Selecting custom type cluster and cloud provider as Amazon.
We have followed the pre-reqs required for this kind of setup - AWS role and labels.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
18.09.3
```

**Comment by superseb** [comment]
There are troubleshooting docs that can be used to retrieve the root cause here: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/

Also, please supply what AMI you are using.

**Comment by rborsaru** [comment]
Hi Superseb,

We are using a Centos 7 AMI that we have customized.

Here is the output from the troubleshooting:
$ kubectl create -f ds-overlaytest.yml
daemonset.apps/overlaytest created
$ kubectl rollout status ds/overlaytest -w
daemon set "overlaytest" successfully rolled out

$ echo "=> Start network overlay test"; kubectl get pods -l name=overlaytest -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.nodeName}{"\n"}{end}' | while read spod shost; do kubectl ge
t pods -l name=overlaytest -o jsonpath='{range .items[*]}{@.status.podIP}{" "}{@.spec.nodeName}{"\n"}{end}' | while read tip thost; do kubectl --request-timeout='10s' exec $spod -- /bin/sh -c "ping -c2 $tip > /dev/null 2>&1"; RC=$?; if [
 $RC -ne 0 ]; then echo $shost cannot reach $thost; fi; done; done; echo "=> End network overlay test"
=> Start network overlay test
=> End network overlay test

$ kubectl -n kube-system get pods -l k8s-app=kube-dns
NAME                        READY   STATUS             RESTARTS   AGE
kube-dns-6db5b57f97-kf4h7   1/3     CrashLoopBackOff   37         47m
kube-dns-9c6c5558b-zdzcn    1/3     CrashLoopBackOff   38         48m

$ kubectl -n kube-system get svc -l k8s-app=kube-dns
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP   18d

$ kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup kubernetes.default
If you don't see a command prompt, try pressing enter.
Address 1: 10.43.0.10

nslookup: can't resolve 'kubernetes.default'
pod "busybox" deleted
pod default/busybox terminated (Error)

$ kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup www.google.com
If you don't see a command prompt, try pressing enter.
Address 1: 10.43.0.10

nslookup: can't resolve 'www.google.com'
pod "busybox" deleted
pod default/busybox terminated (Error)

$ kubectl create -f ds-dnstest.yml
daemonset.apps/dnstest created

$ kubectl rollout status ds/dnstest -w
daemon set "dnstest" successfully rolled out

$ export DOMAIN=www.google.com; echo "=> Start DNS resolve test"; kubectl get pods -l name=dnstest --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do
 kubectl exec $pod -- /bin/sh -c "nslookup $DOMAIN > /dev/null 2>&1"; RC=$?; if [ $RC -ne 0 ]; then echo $host cannot resolve $DOMAIN; fi; done; echo "=> End DNS resolve test"
=> Start DNS resolve test
command terminated with exit code 1
10.100.138.28 cannot resolve www.google.com
command terminated with exit code 1
10.100.138.166 cannot resolve www.google.com
command terminated with exit code 1
10.100.138.42 cannot resolve www.google.com
=> End DNS resolve test

$ kubectl delete ds/dnstest
daemonset.extensions "dnstest" deleted

$ kubectl -n kube-system get pods -l k8s-app=kube-dns --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do echo "Pod ${pod} on host ${host}"; kubectl -
n kube-system exec $pod -c kubedns cat /etc/resolv.conf; done
Pod kube-dns-6db5b57f97-kf4h7 on host 10.100.138.42
error: unable to upgrade connection: container not found ("kubedns")
Pod kube-dns-9c6c5558b-zdzcn on host 10.100.138.166
error: unable to upgrade connection: container not found ("kubedns")

$ kubectl -n kube-system get configmap kube-dns -o go-template='{{range $key, $value := .data}}{{ $key }}{{":"}}{{ $value }}{{"\n"}}{{end}}'
Error from server (NotFound): configmaps "kube-dns" not found

Regards,

**Comment by superseb** [comment]
Sorry missed the `CrashLoopBackOff` state. Can you share output of `kubectl -n kube-system describe pods -l k8s-app=kube-dns`?

**Comment by rborsaru** [comment]
Here is the requested output:
$ kubectl -n kube-system describe pods -l k8s-app=kube-dns
Name:               kube-dns-6db5b57f97-kf4h7
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-100-138-42.ap-southeast-2.compute.internal/10.100.138.42
Start Time:         Wed, 01 May 2019 15:31:10 +1000
Labels:             k8s-app=kube-dns
                    pod-template-hash=6db5b57f97
Annotations:        cattle.io/timestamp: 2019-04-30T05:42:51Z
                    cni.projectcalico.org/podIP: 10.42.2.47/32
                    field.cattle.io/ports:
                      [[{"containerPort":10053,"dnsName":"kube-dns-","name":"dns-local","protocol":"UDP","sourcePort":0},{"containerPort":10053,"dnsName":"kube-...
                    scheduler.alpha.kubernetes.io/critical-pod:
Status:             Running
IP:                 10.42.2.47
Controlled By:      ReplicaSet/kube-dns-6db5b57f97
Containers:
  kubedns:
    Container ID:  docker://eb97b3797a171982f64c8cb84b7785c322857b7bdc1195c603d552c1a8036e32
    Image:         rancher/k8s-dns-kube-dns-amd64:1.15.0
    Image ID:      docker-pullable://rancher/k8s-dns-kube-dns-amd64@sha256:e7f673b2c5ccd047c48b4eecd5452b2db1b9454daf07b23068ad239f98afaa29
    Ports:         10053/UDP, 10053/TCP, 10055/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --config-dir=/kube-dns-config
      --v=2
    State:          Running
      Started:      Thu, 02 May 2019 09:24:29 +1000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 02 May 2019 09:16:59 +1000
      Finished:     Thu, 02 May 2019 09:19:18 +1000
    Ready:          False
    Restart Count:  78
    Limits:
      memory:  170Mi
    Requests:
      cpu:      100m
      memory:   70Mi
    Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:  10055
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-vmhxf (ro)
  dnsmasq:
    Container ID:  docker://5bd8e14d87c78699333f0d27d9ae8c7e783787eb1ba3b9a5e871b267b393b4b3
    Image:         rancher/k8s-dns-dnsmasq-nanny-amd64:1.15.0
    Image ID:      docker-pullable://rancher/k8s-dns-dnsmasq-nanny-amd64@sha256:ed10a8d06cde253474a7e9cfa65bbdf5f8f0c6a377f66c033e623ff63e9d5edf
    Ports:         53/UDP, 53/TCP
    Host Ports:    0/UDP, 0/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/etc/k8s/dns/dnsmasq-nanny
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --log-facility=-
      --server=/cluster.local/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
    State:          Running
      Started:      Thu, 02 May 2019 09:24:59 +1000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 02 May 2019 09:17:30 +1000
      Finished:     Thu, 02 May 2019 09:19:50 +1000
    Ready:          True
    Restart Count:  78
    Requests:
      cpu:        150m
      memory:     20Mi
    Liveness:     http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-vmhxf (ro)
  sidecar:
    Container ID:  docker://d112131ebfede8bdb1b2a407fd7705c87b09da161b192ca1204d19ce28724e13
    Image:         rancher/k8s-dns-sidecar-amd64:1.15.0
    Image ID:      docker-pullable://rancher/k8s-dns-sidecar-amd64@sha256:fbaf5cf6218942898cb171a34dca9a1dd9e5dcf15c8f18ff2d391dddfe9482f5
    Port:          10054/TCP
    Host Port:     0/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 02 May 2019 09:20:09 +1000
      Finished:     Thu, 02 May 2019 09:21:59 +1000
    Ready:          False
    Restart Count:  82
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-vmhxf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-dns-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-dns
    Optional:  true
  kube-dns-token-vmhxf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dns-token-vmhxf
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                                                       Message
  ----     ------     ----                   ----                                                       -------
  Normal   Killing    38m (x12 over 80m)     kubelet, ip-10-100-138-42.ap-southeast-2.compute.internal  Killing container with id docker://sidecar:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy  28m (x178 over 83m)    kubelet, ip-10-100-138-42.ap-southeast-2.compute.internal  Readiness probe failed: Get http://10.42.2.47:8081/readiness: net/http: request canceled (Client.Timeout exceeded while awaiting head
ers)
  Warning  BackOff    13m (x171 over 71m)    kubelet, ip-10-100-138-42.ap-southeast-2.compute.internal  Back-off restarting failed container
  Warning  Unhealthy  8m27s (x88 over 82m)   kubelet, ip-10-100-138-42.ap-southeast-2.compute.internal  Liveness probe failed: Get http://10.42.2.47:10054/healthcheck/dnsmasq: net/http: request canceled (Client.Timeout exceeded while awa
iting headers)
  Warning  BackOff    3m21s (x213 over 71m)  kubelet, ip-10-100-138-42.ap-southeast-2.compute.internal  Back-off restarting failed container


Name:               kube-dns-9c6c5558b-zdzcn
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-100-138-166.ap-southeast-2.compute.internal/10.100.138.166
Start Time:         Wed, 01 May 2019 15:29:25 +1000
Labels:             k8s-app=kube-dns
                    pod-template-hash=9c6c5558b
Annotations:        cattle.io/timestamp: 2019-05-01T05:29:25Z
                    cni.projectcalico.org/podIP: 10.42.1.98/32
                    field.cattle.io/ports:
                      [[{"containerPort":10053,"dnsName":"kube-dns-","name":"dns-local","protocol":"UDP","sourcePort":0},{"containerPort":10053,"dnsName":"kube-...
                    scheduler.alpha.kubernetes.io/critical-pod:
Status:             Running
IP:                 10.42.1.98
Controlled By:      ReplicaSet/kube-dns-9c6c5558b
Containers:
  kubedns:
    Container ID:  docker://9c94faf91e230d832128d633024734708445d785c4e696ffecadefadabb68a7f
    Image:         rancher/k8s-dns-kube-dns-amd64:1.15.0
    Image ID:      docker-pullable://rancher/k8s-dns-kube-dns-amd64@sha256:e7f673b2c5ccd047c48b4eecd5452b2db1b9454daf07b23068ad239f98afaa29
    Ports:         10053/UDP, 10053/TCP, 10055/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --config-dir=/kube-dns-config
      --v=2
    State:          Running
      Started:      Thu, 02 May 2019 09:24:08 +1000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 02 May 2019 09:16:38 +1000
      Finished:     Thu, 02 May 2019 09:18:58 +1000
    Ready:          False
    Restart Count:  79
    Limits:
      memory:  170Mi
    Requests:
      cpu:      100m
      memory:   70Mi
    Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:  10055
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-vmhxf (ro)
  dnsmasq:
    Container ID:  docker://e0409b07868e3085ddd15e921bf3d0fcb3e5cbec16640d56a61c42c74aa70fc3
    Image:         rancher/k8s-dns-dnsmasq-nanny-amd64:1.15.0
    Image ID:      docker-pullable://rancher/k8s-dns-dnsmasq-nanny-amd64@sha256:ed10a8d06cde253474a7e9cfa65bbdf5f8f0c6a377f66c033e623ff63e9d5edf
    Ports:         53/UDP, 53/TCP
    Host Ports:    0/UDP, 0/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/etc/k8s/dns/dnsmasq-nanny
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --log-facility=-
      --server=/cluster.local/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 02 May 2019 09:17:37 +1000
      Finished:     Thu, 02 May 2019 09:20:03 +1000
    Ready:          False                                                                                                                                                                                                           [10/1934]    Restart Count:  77
    Requests:
      cpu:        150m
      memory:     20Mi
    Liveness:     http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-vmhxf (ro)
  sidecar:
    Container ID:  docker://4e127f77e143ac58b3ee5d0b9cc72b5d1226165751b4ab971f370f600adb61f9
    Image:         rancher/k8s-dns-sidecar-amd64:1.15.0
    Image ID:      docker-pullable://rancher/k8s-dns-sidecar-amd64@sha256:fbaf5cf6218942898cb171a34dca9a1dd9e5dcf15c8f18ff2d391dddfe9482f5
    Port:          10054/TCP
    Host Port:     0/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
    State:          Running
      Started:      Thu, 02 May 2019 09:24:39 +1000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 02 May 2019 09:22:51 +1000
      Finished:     Thu, 02 May 2019 09:24:39 +1000
    Ready:          True
    Restart Count:  82
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-vmhxf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-dns-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-dns
    Optional:  true
  kube-dns-token-vmhxf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dns-token-vmhxf
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                                                        Message
  ----     ------     ----                   ----                                                        -------
  Warning  Unhealthy  58m (x96 over 83m)     kubelet, ip-10-100-138-166.ap-southeast-2.compute.internal  Readiness probe failed: Get http://10.42.1.98:8081/readiness: net/http: request canceled (Client.Timeout exceeded while awaiting hea
ders)
  Warning  BackOff    53m (x54 over 71m)     kubelet, ip-10-100-138-166.ap-southeast-2.compute.internal  Back-off restarting failed container
  Warning  Unhealthy  28m (x70 over 82m)     kubelet, ip-10-100-138-166.ap-southeast-2.compute.internal  Liveness probe failed: Get http://10.42.1.98:10054/healthcheck/kubedns: net/http: request canceled (Client.Timeout exceeded while aw
aiting headers)
  Warning  Unhealthy  23m (x77 over 82m)     kubelet, ip-10-100-138-166.ap-southeast-2.compute.internal  Liveness probe failed: Get http://10.42.1.98:10054/metrics: net/http: request canceled (Client.Timeout exceeded while awaiting heade
rs)
  Warning  BackOff    13m (x180 over 71m)    kubelet, ip-10-100-138-166.ap-southeast-2.compute.internal  Back-off restarting failed container
  Warning  Unhealthy  8m29s (x87 over 82m)   kubelet, ip-10-100-138-166.ap-southeast-2.compute.internal  Liveness probe failed: Get http://10.42.1.98:10054/healthcheck/dnsmasq: net/http: request canceled (Client.Timeout exceeded while aw
aiting headers)
  Warning  BackOff    3m18s (x207 over 73m)  kubelet, ip-10-100-138-166.ap-southeast-2.compute.internal  Back-off restarting failed container

Thanks!!

**Comment by rborsaru** [comment]
I have resolved this issue. The problem was with the proxy settings I added to the Kube cluster. 
As the cluster is using 10.42.0.0/16 and 10.43.0.0/16 for internal communication, I needed to add those to No_PROXY list. After that the kube_dns service started working as expected.

Thanks for your help!!
