### ISSUE TITLE
The kubedns is failed when i update the rancher version v2.1.7 to v2.2.2

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#19889]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`pod`|
![image](https://user-images.githubusercontent.com/14210543/56956400-9dd7f680-6b76-11e9-8645-c7a7e25413be.png)
![image](https://user-images.githubusercontent.com/14210543/56956424-b2b48a00-6b76-11e9-8c3c-642a6ef5e044.png)
 kubedns and kube-dns ,Why are they the same?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
