### ISSUE TITLE
Backport: Cannot deploy cluster monitoring feature if the creator of cluster has been removed or deactivated

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19885]
Backport https://github.com/rancher/rancher/issues/18787

**Comment by alena1108** [comment]
Available in v2.2.3-rc4

**Comment by jiaqiluo** [comment]
The big fix is validated on v2.2.3-rc4 

Steps:
- provision an RKE cluster
- Create second admin account
- Login with second admin account
- Deactivate default admin account
- Enable cluster monitoring

Result:
- the cluster monitoring is up successfully
