### ISSUE TITLE
etcd restore fails 

### ISSUE THREAD

**Issue by janavenkat** [rancher/rancher#19894]
**What kind of request is this (question/bug/enhancement/feature request):**
Failed to restore the backup

**Steps to reproduce (least amount of steps as possible):**
1. Backup the etcd using rke cli
2. copy the snapshot to new target vm /opt/rke/etcd-snapshot/
3. Restore using rke cli
rke etcd snapshot-restore --name snapshot.db --config ~/tmpw/cluster.yml 

Already there is some similar issue but it says it fixed
https://github.com/rancher/rancher/issues/18504

**Result:**

```
jana@jvenkata:~/PycharmProjects/k8s$ rke etcd snapshot-restore --name snapshot.db --config ~/tmpw/cluster.yml 
INFO[0000] Restoring etcd snapshot snapshot.db          
INFO[0000] Successfully Deployed state file at [/home/jana/tmpw/cluster.rkestate] 
INFO[0000] [dialer] Setup tunnel for host [*****] 
WARN[0006] failed to stop etcd container on host [*****] : Can't stop Docker container [etcd] for host [*****] : Error response from daemon: No such container: etcd 
INFO[0006] [etcd] starting backup server on host [*****] 
INFO[0006] [etcd] Successfully started [etcd-Serve-backup] container on host [*****] 
WARN[0011] failed to start backup server on host [*****] : Failed to run backup server container, container logs: time="2019-04-30T14:45:00Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory" 
 
WARN[0012] failed to start etcd container on host [*****] : Failed to start [etcd] container on host [*****] : Error response from daemon: No such container: etcd 
FATA[0012] failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2019-04-30T14:45:00Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory" 
] 
```
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.2
rke version v0.2.2

- Installation option (single install/HA):
Installation in HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
vm
- Kubernetes version (use `kubectl version`):

```
v1.11.6
```

- Docker version (use `docker version`):

```
Docker version 18.09.5, build e8ff056

```

**Comment by alena1108** [comment]
@superseb was this issue fixed by one of your recent prs?

**Comment by superseb** [comment]
Is this only using the RKE CLI? Can you supply a bit more detail on the setup:

- RKE CLI or Rancher
- What OS is running on the nodes
- The complete `cluster.yml`
- Any upgrade path or versions where it worked before

**Comment by janavenkat** [comment]
> Is this only using the RKE CLI? Can you supply a bit more detail on the setup:
> 
> * RKE CLI or Rancher
> * What OS is running on the nodes
> * The complete `cluster.yml`
> * Any upgrade path or versions where it worked before

> rke cli
> ubuntu
>  ```nodes:
  - address: *****
    internal_address: 192.168.0.9
    user: root
    role:
        - controlplane
        - etcd
        - worker
    ssh_key_path: ~/.ssh/rke92.pub```

**Comment by RaceFPV** [comment]
Same error here when trying to restore on centos 7, using RKE CLI after having the cluster die and needing to recover. This is a first attempt at doing an etcd restore. Rancher version 2.2.2 RKE version 0.2.2.

**Comment by superseb** [comment]
Please supply the exact commands executed and the content of the directory (`ls -la`) where you run the `rke` command.

**Comment by janavenkat** [comment]
It turns out that name convention for file should be same. Restore is working fine

**Comment by aliabbasjaffri** [comment]
Still facing the same issue with whilst trying to restore from RKE `v1.0.0`
1. Restored the snapshot on the running server and downloaded it locally
2. scp '-ed' it to the target restore server in the folder `/opt/rke/etcd-snapshots`
3. Ran the rke restore command, 
`rke_v1.0.0 etcd snapshot-restore --name /opt/rke/etcd-snapshots/16.12.2019_backup --config rancher-cluster-restore.yaml`
4. The following output is observed:
```
INFO[0000] Running RKE version: v1.0.0
INFO[0000] Restoring etcd snapshot /opt/rke/etcd-snapshots/16.12.2019_backup
INFO[0000] Successfully Deployed state file at [./rancher-cluster-restore.rkestate]
INFO[0000] [dialer] Setup tunnel for host [xx.xx.xx.xx]
INFO[0001] Checking if container [cert-deployer] is running on host [xx.xx.xx.xx], try #1
INFO[0001] Image [rancher/rke-tools:v0.1.51] exists on host [xx.xx.xx.xx]
INFO[0001] Starting container [cert-deployer] on host [xx.xx.xx.xx], try #1
INFO[0001] Checking if container [cert-deployer] is running on host [xx.xx.xx.xx], try #1
INFO[0006] Checking if container [cert-deployer] is running on host [xx.xx.xx.xx], try #1
INFO[0006] Removing container [cert-deployer] on host [xx.xx.xx.xx], try #1
INFO[0006] Stopping container [etcd] on host [xx.xx.xx.xx] with stopTimeoutDuration [5s], try #1
WARN[0006] Can't stop Docker container [etcd] for host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0006] Stopping container [etcd] on host [xx.xx.xx.xx] with stopTimeoutDuration [5s], try #2
WARN[0006] Can't stop Docker container [etcd] for host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0006] Stopping container [etcd] on host [xx.xx.xx.xx] with stopTimeoutDuration [5s], try #3
WARN[0006] Can't stop Docker container [etcd] for host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0006] [etcd] starting backup server on host [xx.xx.xx.xx]
INFO[0006] Image [rancher/rke-tools:v0.1.51] exists on host [xx.xx.xx.xx]
INFO[0007] Starting container [etcd-Serve-backup] on host [xx.xx.xx.xx], try #1
INFO[0007] [etcd] Successfully started [etcd-Serve-backup] container on host [xx.xx.xx.xx]
INFO[0013] Removing container [etcd-Serve-backup] on host [xx.xx.xx.xx], try #1
WARN[0013] failed to start backup server on host [xx.xx.xx.xx]: Failed to run backup server container, container logs: time="2019-12-16T15:50:44Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"
INFO[0013] Starting container [etcd] on host [xx.xx.xx.xx], try #1
WARN[0013] Can't start Docker container [etcd] on host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0013] Starting container [etcd] on host [xx.xx.xx.xx], try #2
WARN[0013] Can't start Docker container [etcd] on host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0013] Starting container [etcd] on host [xx.xx.xx.xx], try #3
WARN[0013] Can't start Docker container [etcd] on host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
WARN[0013] failed to start etcd container on host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
FATA[0013] failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2019-12-16T15:50:44Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"
```
