### ISSUE TITLE
Node dashboard top table change

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19897]
Related: rancher/rancher#19896 
Version: Master 

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement Request

**Steps to reproduce (least amount of steps as possible):**
We'd like to _remove_ CPU, Memory, Kube Proxy Version. Basically we want to try to have these seven items based on a discussion 4/29.

Hostname, Internal IP, External IP
Docker/containerd Version, Kubelet Version, OS
Created time

This is because we don't really believe that Kube Proxy Version is all that useful, CPU/Memory is redundant as the wheels show this.

![Screen Shot 2019-04-30 at 9 44 59 AM](https://user-images.githubusercontent.com/45179589/56978821-41041e00-6b2d-11e9-91a8-335a06f89471.png)

**Notice:** I mentioned Docker/ Containerd version. We wanted to make this dynamic so that if we are running K3s for example the UI shows "Containerd Version:" instead of "Docker Version".

As this change requires seven items on these tables that can only fit 3 items (and look okay) we had discussed possibly putting the Hostname field actually up on the page title (%hostsPage.hostPage.header.title%) with copy to clipboard function remaining.

One last thing: it does not make sense that we have an icon to copy hostname to clipboard but we simply click on internal or external IP to copy to clipboard. We need to make this the same across the product. My preference is the iconless version where you just click on a hostname/IP to copy to clipboard.

**Comment by davidnuzik** [comment]
(Awaiting PR to get merged and new master-head build)
Confirmed this is not in latest master yet.

**Comment by lvuch** [comment]
@davidnuzik to separate ips @westlywright or @loganhz would have to refactor that component, but I think it makes sense to keep them paired together. Currently Docker version and ContainerD are dynamic (@westlywright can demo this).

**Comment by davidnuzik** [comment]
Version: master-head (6/24/19 1:00pm mst)

I no longer see the node wheels.
![Screen Shot 2019-06-24 at 3 45 42 PM](https://user-images.githubusercontent.com/45179589/60056838-3aaaa200-9697-11e9-8c1b-b59ee8dfac8c.png)

**Comment by davidnuzik** [comment]
Issue for fix clipboard icons: https://github.com/rancher/rancher/issues/21096
Issue for fix Docker Version / ContainerD version: https://github.com/rancher/rancher/issues/21099

**Comment by lvuch** [comment]
as noted in https://github.com/rancher/rancher/issues/21096 there are two different components for copy to clipboard, one has and icon the other does not. The dashboard charts are back, removed by mistake.

**Comment by westlywright** [comment]
fixes merged into master

**Comment by davidnuzik** [comment]
There still seems to be an issue. When I enable monitoring I see double the wheels again. It could also be because I had to add a second node so had enough resources for monitoring.
![image](https://user-images.githubusercontent.com/45179589/60471795-1280ed00-9c1b-11e9-8a90-32bcb282ef12.png)

**Comment by davidnuzik** [comment]
The issue is no longer occurring. The cells are now arranged correctly, see picture from comment https://github.com/rancher/rancher/issues/19897#issuecomment-505209397.

Checked again in latest master-head (7/18/19)
