### ISSUE TITLE
Backport Add check for cluster-scoped lifecycle handlers that are not cleaned up when a cluster is deleted #19550

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19899]
Backport for https://github.com/rancher/rancher/issues/19550

**Comment by alena1108** [comment]
Can be tested on rc5

**Comment by jiaqiluo** [comment]
As per the conversation with @daxmc99, the validation did for the cluster namespace cleanup issue (https://github.com/rancher/rancher/issues/19529 and https://github.com/rancher/rancher/issues/19900) should be sufficient for closing this issue.
