### ISSUE TITLE
Provide access logs from cattle server and logs for go-machine services

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#199]
Currently we have cattle server logs under /var/lib/cattle/logs. Can we also provide access logs (which tracks the API request and response) ?
go-machine services related logs are currently present in docker logs only. They are not present in catte-debug.log. We should be logging go-machine services related logs to a separate log file or log them in cattle-debug.log file. 

Also is there a reason we have the logs stored in /var/lib ? Why are we not mandating logs under /var/log?

**Comment by fuhbar** [comment]
@sangeethah Did you spend some effort into this? Still would be nice to have some kind of API access logs.

**Comment by jwhitcraft** [comment]
This would be really useful, any way to get this into 1.3.0?

**Comment by will-chan** [comment]
Tracking this as part of #71
