### ISSUE TITLE
Configure LogRotation by default for all containers

### ISSUE THREAD

**Issue by vinayagg** [rancher/rancher#19908]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Install Rancher in HA mode

**Result:**
Rancher's local cluster's kube-apiserver logs grow indefinitely.

**Other details that may be helpful:**
Once rancher is installed, i.e. kube-api container is running, there doesnt seem to be a way to configure log rotation. 
On our systems, the logs grew until disk was 100% full. Configuring as described here https://docs.docker.com/config/containers/logging/json-file/ and restarting server did not fix the problem because the setting is only for new containers. 
Hence it must be done as part of docker command inside rancher helm charts. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.2

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#12790

**Comment by vinayagg** [comment]
logrotate can rotate logs and rancher should install this by default on rancher cluster and maybe on child clusters too
https://github.com/stakater-charts/logrotate

**Comment by patrick0057** [comment]
It would be nice to be able to toggle this from the user interface.

**Comment by shinebayar-g** [comment]
We don't notice how critical this setting until our disk ran out of space and cause disaster.. :disappointed:

**Comment by AntonSmolkov** [comment]
On RancherOS i'v managed to configure log-rotation by adding following settings in cloud-config:

 ```rancher:
  docker:
    log_driver: json-file
    log_opts:
      max-file: 1
      max-size: 10m
```

**Comment by harshitmahapatra** [comment]
I also ran into this issue recently.

**Comment by chrisfosterelli** [comment]
Is using the 2.5 cluster logging a workaround? Or does it just export logs from the file, while still letting the file grow indefinitely?

**Comment by spatialy** [comment]
We just run into this for first time, any workaround?

**Comment by chrisfosterelli** [comment]
I still haven't found one, other than that nodes get a low-disk taint every now and then and will start killing containers until it's resolved... Sort of surprised more users aren't running into this one 😅

**Comment by mehran-prs** [comment]
Any update?

**Comment by bashofmann** [comment]
FYI, RKE2 and K3s clusters have a default log rotation configured, see https://www.suse.com/support/kb/doc/?id=000020071
