### ISSUE TITLE
Security Context (RunAsGroup) not applied (GID)

### ISSUE THREAD

**Issue by hwasp** [rancher/rancher#19901]
**What kind of request is this (question/bug/enhancement/feature request): question/bug

**Steps to reproduce (least amount of steps as possible): 

Follow "Set the security context for a Pod" example at: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

Once the pod is running, exec into the pod and run "id", it should output: 

$ id
uid=1000 gid=3000 groups=2000

but it shows:

$ id
uid=1000 gid=0(root) groups=2000

So it seems that Gid is not been enforced (selects the default root)

**Result:**
GID not being enforced

**Other details that may be helpful:**

Tested in 2.1.8 and 2.2.2 HA with kubernetes 1.13-5

- Docker version (use `docker version`): RedHat  1.13.1

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-94.gitb2f74b2.el7.x86_64
 Go version:      go1.10.8
 Git commit:      b2f74b2/1.13.1
 Built:           Mon Feb 25 14:45:39 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-94.gitb2f74b2.el7.x86_64
 Go version:      go1.10.8
 Git commit:      b2f74b2/1.13.1
 Built:           Mon Feb 25 14:45:39 2019
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by superseb** [comment]
The `RunAsGroup` feature is not enabled by default in Kubernetes 1.13, it is in 1.14 (see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md). The docs example is applicable to 1.14 as well.

If you want to enable this for Kubernetes 1.13, you can enable the feature gate for this using Cluster Options as described on https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file and with the following added lines to the `kube-api` service:

```
  kube-api: 
    extra_args: 
      feature-gates: "RunAsGroup=true"
```

Test it in your test cluster first before applying to production

**Comment by hwasp** [comment]
Hi, I can confirm that after applying the extra arguments to the cluster the GroupID is enforced correctly. Thanks for the quick answer!
