### ISSUE TITLE
packet driver not working

### ISSUE THREAD

**Issue by abh** [rancher/rancher#19902]
Using the packet node driver:

When clicking "authenticate & select an instance" the page just stays as-is.  Looking at the browser's network debugging rancher is getting/sending a 403 response.

**Comment by skbki** [comment]
You probably enter project api key instead of account one.

**Comment by abh** [comment]
Indeed, that was it!  It wasn't clear to me that I needed to enter a project ID but then an account API key (rather than a project one).

Thank you!
