### ISSUE TITLE
[BUG] Custom ingress-ip-domain results in no automatic generated ingress hostnames

### ISSUE THREAD

**Issue by gabrielcalderon** [rancher/rancher#19915]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Change the default ingress-ip-domain from xip.io to nip.io in the global rancher settings.
* Deploy docker-registry from Rancher Charts Catalog using a layer-7 ingress with auto-generated nip.io hostname.

**Result:**
* Ingress gets created with nip.io/ instead of auto-generated path.
* Rancher works just fine with xip.io, changing to any other values results in no hostnames generated.

**Logs**
When setting an ingress with xip.io I can see a message in rancher server:
- [INFO] Updating ingress [docker-registry:docker-registry] with public endpoints [ json data here]

When setting an ingress with anything other than xip.io, for example: nip.io I get:
- [INFO] Updating ingress [docker-registry:docker-registry] with public endpoints [null]

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Rancher 2.2.2
Running in bare-metal with 8443:443 and 8080:80
Single-Node Instance
I'm not setting the node IP, or internal cluster IP
```

- Docker version (use `docker version`):

```
docker version 18.09.5, build e8ff056
```

Other info:
* https://nip.io/ is a PowerDNS wildcard dns like xip.io but the backend runs Python instead of Bash.

**Comment by azubizarretap** [comment]
Seeing the same behavior as @gabrielcalderon . I am also running rancher on bare metal.

**Comment by zhmocean** [comment]
same on v2.2.3 stable

**Comment by rootwuj** [comment]
Tested with rancher/rancher:master-head from July 11

This version uses the ingress-ip-domain other than xip.io, the ingress target can automatically generate the hostname.
