### ISSUE TITLE
Alert manager isn't deploying - cannot get alerts and notifications

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19912]
Version: v2.2.3-rc4

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to create an alert group and make a pod event rule.

**Result:**
Alert manager will fail to deploy.
I did not have this issue in rc3

**Other details that may be helpful:**
I tested with DigitalOcean RKE and slack notifier. I created pods / deleted pods and never got alerts. I then looked at rancher logs and saw that there are many errors around alert manager.

[logs.txt](https://github.com/rancher/rancher/files/3133432/logs.txt)

**Comment by davidnuzik** [comment]
@loganhz I was not sure the best person to assign this to; please assign to another person if necessary. I tried a couple of different clusters and keep encountering the issue. My setup was single-node rancher.

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/pull/19983

**Comment by loganhz** [comment]
Need to https://github.com/rancher/rancher/pull/19983 into 2.2 branch before move to test

**Comment by alena1108** [comment]
will be available in rc6

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc6 and Master (v2.3) (5/6/19)

Alertmanager is now deploying; we can successfully get alerts (notifications) now.
