### ISSUE TITLE
Login username is missing from account drop down menu when using local DB

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1991]
UI v0.46.0

![screen shot 2015-09-08 at 9 56 37 am](https://cloud.githubusercontent.com/assets/11410997/9741579/000f16ec-5610-11e5-85a9-76e5cd5b9127.png)

Name shows up, but not username, which is causing alignment issues in the dropdown.

**Comment by vincent99** [comment]
The name might still be missing from the API response in some case, but the UI will display it not cut off like that now.

**Comment by deniseschannon** [comment]
So the missing name is due to the API?

**Comment by deniseschannon** [comment]
Verified fixed the UI alignment. Opened up #2130 to track the missing API.
