### ISSUE TITLE
[cli] switch rancher server

### ISSUE THREAD

**Issue by chaudyg** [rancher/rancher#19925]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request for rancher2/cli

**summary**
Add the ability to switch the cli context to point to a different rancher server.

**description**
Currently the `rancher login` command supports a `--name` flag to specify a name for the targeted rancher server. The cli then adds a server entry to the `~/.rancher/cli2.json` and sets the `CurrentServer` field to the name specified (see [source](https://github.com/rancher/cli/blob/a6c0425dcfd20c1301bb2f947f9a1e6d96453f67/cmd/login.go#L142)).

Sadly there is currently no mechanism available to switch the current server.

For our use case, we have multiple rancher servers, each responsible for it's own set of kubernetes clusters. We are looking for an easy way to switch the current cli context to point at the correct rancher server.

**proposal**
Extend the `rancher context switch` command as follow:

```
$ rancher context switch -h
Switch to a new context

The project arg is optional, if not passed in a list of available servers and projects will
be displayed and one can be selected. If only one server is available it will be automatically selected.  If only one project is available it will be automatically selected. 

Usage:
  rancher context switch [OPTIONS] [PROJECT_ID/PROJECT_NAME]

Options:
  --server-name value             Name of the rancher Server
```

Example:
```
$ rancher login --token token-12345  --name rancher1 https://rancher1.example.com/v3

$ rancher login --token token-67890  --name rancher2 https://rancher2.example.com/v3

$ rancher context switch
NUMBER    SERVER NAME   SERVER URL
1         rancher1            https://rancher1.example.com/
1         rancher2            https://rancher1.example.com/
Select a Server: 1

NUMBER    CLUSTER NAME   PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
...
Select a Project: 2

$ rancher context current
Server: rancher1 Cluster:minikube Project:demo
```

**implementation**
I am happy to raise a PR for this work. I would appreciate some feedback on the design first.

**Comment by chaudyg** [comment]
@dramich @drpebcak Any thought?

**Comment by dramich** [comment]
@chaudyg We always welcome PRs. As for the design I think it would be best to add a new command called `server` that allows this manipulation. Under `server` it would have at least three subcommands:

`switch` - operate similar to context switch
`current` - operate similar to context current but show the current server-cluster-project. Ideally the func `loginContext` would be updated to also include the server then both commands can use this helper. 
`ls` - list all servers that currently live in the json file and mark your current one

**Comment by chaudyg** [comment]
Thx @dramich
I did a quick first pass. Let me know what you think. Thx
https://github.com/rancher/cli/pull/243/files

**Comment by dramich** [comment]
Available in v2.3.0-rc3

**Comment by chaudyg** [comment]
Thx

**Comment by sowmyav27** [comment]
**Verified on `v2.3.0-rc3`**
Command - `./rancher server --help`
```
./rancher server --help

Operations for the server
Switch or view the server currently in focus.

Usage:
   rancher server command [command options] [arguments...]

Commands:
     current  Display the current server
     delete   Delete a server from the local config
     ls       List all servers
     switch   Switch to a new server

Options:
   --help, -h  show help
```

On Logging into multiple rancher servers - 
```
./rancher server ls
CURRENT   NAME             URL
          rancherDefault   https://<x.x.x.x>
*         test1            https://<y.y.y.y>
          test2            https://<z.z.z.z>
```

Command: `./rancher server current`
```
Name: test1 URL: https://<y.y.y.y>
```

Command: `./rancher server delete test2`
```
INFO[0000] Saving config to /Users/sowmyaviswanathan/.rancher/cli2.json 
INFO[0000] Server test2 deleted        
```
Command: `./rancher server switch test1`
```
INFO[0000] Saving config to /Users/sowmyaviswanathan/.rancher/cli2.json 

./rancher server ls
CURRENT   NAME             URL
          rancherDefault   https://<x.x.x.x>
*         test1            https://<y.y.y.y>
          test2            https://<z.z.z.z>

```
