### ISSUE TITLE
Backport: Monitoring - can't completely clean up after disabling cluster monitoring

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19938]
Backport https://github.com/rancher/rancher/issues/19645

**Comment by alena1108** [comment]
Can be tested on rc5

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher master v2.2.3-rc5

Test those two cases:
- enable and disable the cluster monitoring really quickly multiple times
- enable and disable the cluster monitoring in the environment with limited resource
