### ISSUE TITLE
Backport Get repeating alerts for pod that has been deleted

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19936]
Backport https://github.com/rancher/rancher/issues/19302

**Comment by alena1108** [comment]
Can be tested on rc5

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc6

I tested again and no longer get any additional alerts after my pod/workload has been deleted.
I also tried a scenario where I had a workload with multiple pods. As expected, I only get alerts once for each of the several pods deleted then no more alerts (notifications).
