### ISSUE TITLE
Backport: Alert manager sending 2 messages sent for every alert "alerting"

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19935]
Backport https://github.com/rancher/rancher/issues/19058

**Comment by alena1108** [comment]
Can be tested on rc5

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc6

I can confirm that now we only get one Event Message per notification now. I tested with Pod Events. Now I will get multiple notifications with one Event Message per each. Previously these would be grouped (see comments above). We would get an event with current info then past+ current and another with past+past+current, etc.

A good example of this is when you used to create a new pod it would group the multiple pod event messages. Now they are separate notifications.
