### ISSUE TITLE
ping on windows workload does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19930]
**What kind of request is this:** bug

**Steps to reproduce (least amount of steps as possible):**
1. create a custom cluster with 1etcd & control linux node, 1 worker linux node and 1 windows linux node. (VXLan mode)
2. deploy 2 workloads- wk01 and wk02.
3. executed the below commands in exec shell of wk02.

- ping google.com
- ping 8.8.8.8
- ping 34.66.21.175(ip address of the workload)
- ping wk01

**Actual Result:**
The ping commands did not work.

**Note:** Host port and Node port also do not work.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): single
 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.14.1
```

**Comment by loganhz** [comment]
`ping wk01` issue will be fixed in https://github.com/rancher/rancher/issues/19954

The others are security group issue. So please try again.

**Comment by sowmyav27** [comment]
verified on rancher:master(05/07/2019)
the below command works.

- curl www.google.com
- curl dns entries also require FQDN.
- curl on workloads- with FQDN works.
- ping ip address of the workload from another workload pod.
