### ISSUE TITLE
Disabled UI Features for Read-Only Users in Rancher 

### ISSUE THREAD

**Issue by rbkaspr** [rancher/rancher#19941]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Creating a read-only cluster user still has buttons for things like creating/deleting deployments or executing shells visible and enabled in the Rancher UI. These options really should be either removed from the view of read-only users or else grayed out/disabled at the very least.

**Other Useful Information**
Rancher v2.2.2

**Comment by superseb** [comment]
This is covered in https://github.com/rancher/rancher/issues/11165

**Comment by jingQingBANG** [comment]
In version 2.10, no relevant UI was found to close the method of entering the kubectl shell. Is there any progress now?
