### ISSUE TITLE
Adding etcd node fails with "bad handshake"

### ISSUE THREAD

**Issue by horihel** [rancher/rancher#19944]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
* Have a Cluster (Vsphere hosted RKE, 1.11.x)
* Add a node (tick etcd and control plane)

**Result:**
* Node gets provisioned
* Node stays stuck in "Waiting to register with kubernetes"
* Agent is stuck in a loop with theese logs:
```
 [docker@k8s-development-v3-mgmt1 ~]$ docker logs -f 04a
INFO: Arguments: --server https://10.240.180.42 --token REDACTED --ca-checksum efce62d90b1fdf3a6c24c1690587fbf566eacc94422f4de236aa909d51cb841b --no-register --only-write-certs
INFO: Environment: CATTLE_ADDRESS=10.240.180.28 CATTLE_AGENT_CONNECT=true CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=k8s-development-v3-mgmt1 CATTLE_SERVER=https://10.240.180.42 CATTLE_TOKEN=REDACTED CATTLE_WRITE_CERT_ONLY=true
INFO: Using resolv.conf: domain enterprise.<redacted> nameserver 10.240.180.2 nameserver 8.8.8.8
INFO: https://10.240.180.42/ping is accessible
INFO: Value from https://10.240.180.42/v3/settings/cacerts is an x509 certificate
time="2019-05-02T10:27:02Z" level=info msg="Rancher agent version v2.2.2 is starting"
time="2019-05-02T10:27:02Z" level=info msg="Option worker=false"
time="2019-05-02T10:27:02Z" level=info msg="Option requestedHostname=k8s-development-v3-mgmt1"
time="2019-05-02T10:27:02Z" level=info msg="Option customConfig=map[roles:[] label:map[] address:10.240.180.28 internalAddress:]"
time="2019-05-02T10:27:02Z" level=info msg="Option etcd=false"
time="2019-05-02T10:27:02Z" level=info msg="Option controlPlane=false"
time="2019-05-02T10:27:02Z" level=info msg="Listening on /tmp/log.sock"
time="2019-05-02T10:27:02Z" level=info msg="Connecting to wss://10.240.180.42/v3/connect with token <redacted>"
time="2019-05-02T10:27:02Z" level=info msg="Connecting to proxy" url="wss://10.240.180.42/v3/connect"
time="2019-05-02T10:27:02Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-05-02T10:27:02Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-05-02T10:27:12Z" level=info msg="Connecting to wss://10.240.180.42/v3/connect with token <redacted>"
time="2019-05-02T10:27:12Z" level=info msg="Connecting to proxy" url="wss://10.240.180.42/v3/connect"
time="2019-05-02T10:27:12Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-05-02T10:27:12Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

**Other details that may be helpful:**
* I checked the connection https://10.240.180.42/v3/connect and ../register with curl and the connection is working fine and gets correctly upgraded to a websocket if you tell CURL to try.
* Adding a worker node works without a problem.
This might be related to #18016, but the problem there just disappeared by itself.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider: Vsphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 2/4 Cores, 4,8,16 GB RAM
- Kubernetes version (use `kubectl version`): 

```
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): As provisioned by default with rancher 2.2.2

```
[docker@k8s-development-v3-mgmt1 ~]$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by Sokwva** [comment]
I got the same problem.

**Comment by gywang-** [comment]
I got the same problem. However, this problem is occasional

**Comment by mmaschenk** [comment]
I have this same problem, however it does not go away (for two weeks now).  Curl connectivity checks out, still always get the "websocket: bad handshake".

```
[~]# docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
[~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

This is seriously making me rethink putting a rancher-built cluster in production :-(

**Comment by mmaschenk** [comment]
I managed to fix the issue in my situation. It turned out te be that my etcd member list contained an errored entry from a previous attempt. This resulted in the 'bad handshake' error (which is not very descriptive).

Removing the errored member from the etcd member list using etcdctl fixed the issue for me. Helpful information was found in https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/#etcd-cluster-and-connectivity-checks

**Comment by horihel** [comment]
Thank you @mmaschenk - turns out my cluster had the same problem. etcd was shown as healthy, but had in fact a non-existing member in its list.
Deleting this member and trying to start another etcd member resulted again in lots of "bad handshake" in the logs, but eventually an etcd came up and after that the node came to life.
So my assumption is that the "bad handshake" log might not even have something todo with the nodes failing to come up, it's just the only thing that gets logged in this state.

So the real bug, as far as I understand, is etcd displayed as "healthy" when it actually isn't.

**Comment by dhrp** [comment]
I'm running into the same bad handshake issue, but have no errorred members in the etcd member list. I'm running a single node master.

```
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
|         ENDPOINT         |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
| https://172.31.17.0:2379 | 4a31477393e162e1 |  3.2.18 |   36 MB |      true |        12 |  107332590 |
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
```

**Comment by superseb** [comment]
In the last version, we've extended the error message to include the cause of the error versus just having `bad handshake`. Please post the new log from the latest version when encountering this issue.
