### ISSUE TITLE
Private Port

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#1994]
Hi,

I am trying to make a container port accessible to containers that run on different hosts,  over ranchers private network, 10,42,x,x, but servers aren't reachable,  ping linked service will not work (dns does resolve).
all container have 10.42.x.x, confirmed by Rancher UI.

Hope that helps.

**Comment by ebuildy** [comment]
DNS will resolve only if you "link" Rancher services.

Did you try to ping the IP from another container?

**Comment by silviupanaite** [comment]
The services are linked and when I try to ping the servers all packets are lost.
I tried an combination of things, ended up with container responding to ping but not on the desired port. Does rancher private network support source routing?

**Comment by ebuildy** [comment]
Yes!

Did you open ports 4500 & 500 between machines?

**Comment by silviupanaite** [comment]
Yes the ports are opened.

**Comment by ibuildthecloud** [comment]
@silviupanaite Make sure the hosts registered the right IP.  In the UI look at the IP for the host in the infrastructure tab.  If it is 172.17.42.1 for any of the hosts it is wrong.  More info on setting the correct IP is here: http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#vms-with-private-and-public-ip-addresses

**Comment by deniseschannon** [comment]
@silviupanaite We also updated some information on troubleshooting in our docs. 

Please re-open if you are still unable to ping containers on different hosts. 
http://docs.rancher.com/rancher/faqs/troubleshooting/
