### ISSUE TITLE
Error when adding the cluster

### ISSUE THREAD

**Issue by ranjeethap** [rancher/rancher#19957]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Just installed a new Rancher server and when adding the GCP cluster it throw the error

**Result:**
Error from server (Forbidden): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "cattle-admin" is forbidden: attempt to grant extra privileges: [{[*] [*] [*] [] []} {[*] [] [] [] [*]}] user=&{ranjeetha@<mycompany>.com  [system:authenticated] map[user-assertion.cloud.google.com:[AKUJVpnIxXk+TeJ05eAJHO97UzInN8GJ+jvQWWXgCFEkK0EmH7WYCJRQrG+ybiVFP+1a+w45xpYhQ9knJeOJqBbb1nx2c09WWoMhHKIpLa+7ujkFQ/yr7l6dNSsoVAJlVF+gNRkJPcqPX4S+RSblb5ZgUSH/sNoMd8rmmeOcFClWJJuY9yGHtHfMJ2kZV3f4B8s0adXkpsvoe2MeJjy8CGecIjlzM3Lb5tEPjR9cKAlnpAkisMk81OgtJUQ=]]} ownerrules=[{[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]}] ruleResolutionErrors=[]

**Other details that may be helpful:**
Other cluster work in GCP

**Environment information**
Ubuntu 18.04
Latest Docker installed
Docker version 18.09.5, build e8ff056
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v /opt/rancher:/var/lib/rancher \
  rancher/rancher:latest

- Installation option (single install/HA):
Single server install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/71051915-b5ef9b00-2184-11ea-8581-131a854d9bec.png)

I guess maybe this step was missing. Please let us know in a comment if you can still reproduce the issue, and we'll reopen it.
