### ISSUE TITLE
Readonly user - Able to add custom host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1995]
Server version - Build from master - sep 8

Local auth enabled setup

Log in as readonly user and navigate to "Add Host" - Custom page.
Host registration url is available for the  readonly user.  User is able to add a custom host.

**Comment by vincent99** [comment]
This is fixed in the API now, but not hidden in UI yet.

**Comment by deniseschannon** [comment]
As of v0.47.0-rc1, this redirects to Error page when clicking on Add Host. 

Closed in favor of #2778 to disable add host button for read only and restricted users.
