### ISSUE TITLE
DNS resolution on Windows workload does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#19954]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a custom cluster - 1 etcd & control plane node, 1 linux worker node, 2 windows worker nodes.
2. Create two workloads on windows host. 
3. Do a curl from one workload to the other

**Expected Result:**
Should be able to resolve the hostname of the workload.

**Actual Result:**
Host name could not be resolved

```
C:\inetpub\wwwroot>curl wk-nodeport
curl: (6) Could not resolve host: wk-nodeport
```

**Note:** Curl to a Linux host workload also does not resolve

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`): 

```
1.14.1
```

**Comment by loganhz** [comment]
Please try `curl wk-nodeport.default.svc.cluster.local`

**Comment by loganhz** [comment]
We should make `curl wk-nodeport` work as it is supported in k8s https://kubernetes.io/docs/setup/windows/#dns-limitations

**Comment by sowmyav27** [comment]
verified on rancher:master (05/09/2019)
**Steps Taken:**
1. Create a custom cluster - 1 etcd & control plane node, 1 linux worker node, 2 windows worker nodes.
2. Create two workloads - wk01, wk02 on windows host. 
3. create two workloads on linux - wk03, wk04 hosts
Verified the below.
- ping on windows workload, from another windows workload - works and vice versa (ex: ping wk01)
- ping on a linux workload from a windows workload - works. and vice versa
- ping on a workload between namespaces works when the FQDN is provided for the workload.
