### ISSUE TITLE
When a node down, the pod cannot recreate automatically. And stucked in state 'unkown'

### ISSUE THREAD

**Issue by zhangalex** [rancher/rancher#19965]
When a node down/poweroff, the pod cannot recreate automatically. And it stucked in state 'unknown'.

I'm using the mariadb-master-slave k8s in 'apps'.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`workload`|

**Comment by loganhz** [comment]
This is by design. https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/
