### ISSUE TITLE
Fluentd workloads not starting when logging is enabled - v2.2.3

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#19974]
rancher/rancher:v2.2.3-rc5

* Create fluentd server
* Deploy Rancher
* Create a cluster
* Enable cluster logging
* Validate logging settings shows the log message in syslog server
  * `May 2 23:48:42 598a0dd048f3 rancher[6] Rancher logging target setting validated`
* After saving settings, fluentd workloads do not start and logs are not forwarded.
* API response comes back 200 and clusterLogging settings are shown in the API. I am so far

**Comment by bmdepesa** [comment]
#19959 19959

**Comment by loganhz** [comment]
Need to https://github.com/rancher/rancher/pull/19983 into 2.2 branch before move to test

**Comment by alena1108** [comment]
will be available in rc6

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.3-rc6

* Enabled logging
* Fluentd workloads start correctly
* Logging is functional
