### ISSUE TITLE
rancher-compose confusion with environment creation

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#1997]
I set up my Rancher environment via the web interface, then downloaded the Compose config with the intent to perform everything via the command line. I then generated an access key and secret as per the docs and set up my environment variables accordingly.

I'm using the Default environment and Default stack to run a bunch of assorted, simple services with no links. I have my compose files in a Default/Default directory on my laptop. I know the higher-level path isn't important but assume Default will be the stack that rancher-compose manipulates.

I then run `rancher-compose logs VPN` to, in theory, retrieve the logs of my VPN service in the Default stack. Instead I see:

```
←[34mINFO←[0m[0002] Creating environment default
←[31mERRO←[0m[0002] Failed to open project default: Bad response from [https://rancher.example.com/v1/environments], sta
tusCode [422]. Status [422 status code 422]. Body: [{"id":"1e0ed811-edae-44f9-91bd-46ec3847ffc7","type":"error","links":{},"a
ctions":{},"status":422,"code":"NotUnique","message":null,"detail":null,"fieldName":"name"}]
2015/09/08 18:30:00 Failed to read project: Bad response from [https://rancher.example.com/v1/environments], statusCode
[422]. Status [422 status code 422]. Body: [{"id":"1e0ed811-edae-44f9-91bd-46ec3847ffc7","type":"error","links":{},"actions":
{},"status":422,"code":"NotUnique","message":null,"detail":null,"fieldName":"name"}]
```

First, should my endpoint be https://rancher.example.com and not the endpoint URL displayed above my API key? That's a little different, but the docs seem to use an example to the root of a Rancher server, and indicate that the key itself determines the environment. It might be wise to remove or repurpose the displayed endpoint since it was a point of confusion for me. For reference I'm referring to https://rancher.example.com/v1/projects/xxx.

Next, why is rancher-compose creating *anything* here? I would assume that `logs` is a read-only command and that no new environments will be created. Further, I'd assume it would try to modify existing environments rather than creating new ones, so that this is failing is a bit odd to me. IOW, if I tweaked the docker-compose.yml and ran `restart`, it wouldn't create a new environment/project but would instead update the container definition, recreating if necessary.

Thanks.

**Comment by vincent99** [comment]
I'm guessing this is a case sensitivity issue with "Default" vs "default"... And the first step is to get-or-create the environment.

**Comment by ndarilek** [comment]
I wondered about that. I'm on Windows so perhaps it's a filesystem issue.

I did try with `-p Default` and saw no change, though.

But I still wonder why `logs` would need to create the environment. 
Wouldn't it query the key, see that it's in the Default environment, see 
the directory or `-p` set to Default, then query the logs of the 
existing service? Maybe `up` would need to create, but `logs`?

**Comment by deniseschannon** [comment]
Can you let me know what version of rancher-compose you are running? There was a bug on case insensitivity with stack names that will be in the next release.

**Comment by ndarilek** [comment]
0.2.5.

**Comment by deniseschannon** [comment]
v0.3.0 is the current latest if downloaded through the UI using v0.37.1. This should have the sentitivity for stack name in side. Please re-open if you still have issues.
