### ISSUE TITLE
Typo in Error Message

### ISSUE THREAD

**Issue by mlh758** [rancher/rancher#19972]
*Describe your issue here*

Clicking Authorize and Fetch Your Own Repositories under the Pipelines tab gives this modal:

![image](https://user-images.githubusercontent.com/4331955/57160701-2c36bd00-6daf-11e9-8bd0-6c248eefab32.png)

enable is spelled wrong

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.3` UI: `v2.1.17` |
|Route|`authenticated.project.pipeline.repositories`|

**Comment by deniseschannon** [comment]
I searched `enalbe` in the UI directory and found it in multiple places: ```
./lib/monitoring/addon/components/cluster-dashboard/template.hbs:          <button class="btn bg-transparent p-0" {{action "enalbeMonitoring"}}>
./lib/monitoring/addon/components/cluster-dashboard/template.hbs:            {{t "clusterDashboard.enalbeMonitoring"}}
./lib/monitoring/addon/components/cluster-dashboard/template.hbs:        <button class="btn bg-warning pt-0 pb-0 pl-5 pr-5" {{action "enalbeMonitoring"}}>
./lib/monitoring/addon/components/cluster-dashboard/component.js:    enalbeMonitoring() {
./lib/monitoring/translations/zh-hans.yaml:  enalbeMonitoring: 启用监控并查看实时监控指标
./lib/monitoring/translations/en-us.yaml:  enalbeMonitoring: Enable Monitoring to see live metrics
```

**Comment by loganhz** [comment]
Hi @mlh758  ,

It only happens if you login as Project member and Project owner didn't config the auth provider yet.

You need to login as Project owner and choose which Git (Github/Gitlab/Bitbucket) you would like to use and enable it.

Please provide the reproduce steps if you were doing something else

**Comment by mlh758** [comment]
I opened the issue due to the typo in the string not that I was getting an error message.

The irony here being that my title should have been "Typo in Error Message"

**Comment by loganhz** [comment]
@mlh758 Thanks. It has been fixed in 2.2.x. I will fix the other Enable typo in the code.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/6/19)

I can confirm the originally reported issue is fixed:

![image](https://user-images.githubusercontent.com/45179589/59068865-478f5f00-886a-11e9-8ae2-8a81b2766ed7.png)

I also briefly reviewed the PR. There is no impact on the UI with these changes and they look good.
