### ISSUE TITLE
MCAPP continues to be stuck in "installing" state even after attempting to upgrade the Mcapp and fix with correct roles.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#19982]
Rancher server version - build from master - `03c40d64`

Steps to reproduce the problem:
As a cluster owner , deploy a MCAPP for "grafana" app by choosing  "project" role.
MCAPP will be stuck in "Installing" state since the app will fail to deploy in this case with error - ```Failed to install app mytestnew-p-729gk. Error: release mytestnew-p-729gk failed: podsecuritypolicies.extensions is forbidden: User "u-z4s7oiitrc" cannot create resource "podsecuritypolicies" in API group "extensions" at the cluster scope```
This is expected since "grafana" app requires cluster role to be deployed successfully.

Upgrade MCAPP and change the role to "cluster".

Even after this the MCAPP continues to be  stuck in "Installing" state and app fails to deploy in with error - 
```Failed to install app mytestnew-p-729gk. Error: release mytestnew-p-729gk failed: podsecuritypolicies.extensions is forbidden: User "u-z4s7oiitrc" cannot create resource "podsecuritypolicies" in API group "extensions" at the cluster scope```

Expected Behavior:
After the cluster role is set , MCAPP should get deployed successfully.

**Comment by mrajashree** [comment]
This looks like a regression from some of the recent helm controller fixes, because exactly this bug was fixed earlier.

**Comment by sangeethah** [comment]
This issue reproduces in v2.2.3-rc5 as well.

**Comment by sangeethah** [comment]
This issue is not reproducible in v2.2.2.

**Comment by sangeethah** [comment]
Tested with 2.2.4-rc1

Steps to reproduce the problem:

As a cluster owner , deploy a MCAPP for "grafana" app by choosing "project" role.
MCAPP will be stuck in "Installing" state since the app will fails to deploy.
This is expected since "grafana" app requires cluster role to be deployed successfully.

Upgrade MCAPP and change the role to "cluster".

After this , able to see the MCAPP deploy successfully.

**Comment by soumyalj** [comment]
Tested with master build from June 12. 
As a cluster owner , deployed a MCAPP for "grafana" app by choosing "project" role.
MCAPP was stuck in "Installing" state since the app fails to deploy.
This is expected since "grafana" app requires cluster role to be deployed successfully.

Upgrade MCAPP and change the role to "cluster".
After this,  MCAPP "grafana" deployed successfully.
