### ISSUE TITLE
Can't access its own svc name from pod

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#19996]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add a custom cluster and use the `flannel` network
2. Deploy Workload and configure NodePort, 
3. After clicking `Launch`, the service will be created automatically.
```
> k get deployment
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
hailong-test   1/1     1            1           2m36s
> k get svc
NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
hailong-test            ClusterIP   10.43.166.79    <none>        80/TCP         2m40s
hailong-test-nodeport   NodePort    10.43.123.245   <none>        80:31076/TCP   2m40s
kubernetes              ClusterIP   10.43.0.1       <none>        443/TCP        63m
> 
```
4. Log in to pod hailong-test via `Execute Shell` and try to access svc hailong-test
```
root@hailong-test-677774d998-hb76z:/# curl hailong-test.default.svc.cluster.local
```
**Result:**
`curl hailong-test.default.svc.cluster.local` did not return, then I tried `curl 10.43.166.79` still did not return results. If I execute `curl hailong-test.default.svc.cluster.local` on other pods I will get the correct result.

Others:
- The same problem will occur on v2.1.0
- I also tested the canal network and it works fine on the canal network.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2 and 2.1.0
- Installation option (single install/HA):
single install

**Cluster information** 
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}```

- Docker version (use `docker version`):
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Wed Jun 20 21:43:51 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Wed Jun 20 21:42:00 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

```

**Comment by superseb** [comment]
Pretty sure this is the same as https://github.com/rancher/rancher/issues/18721

**Comment by kingsd041** [comment]
Ok, then I close this issue
