### ISSUE TITLE
Backport: Monitoring - should use ClusterIP to query metric expressions

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19999]
https://github.com/rancher/rancher/issues/19292

**Comment by loganhz** [comment]
will be available in rc7

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: v2.2.3-rc7 

As a suggestion from the original issue, validate only if the main UI can view the Monitoring charts or not. 

Tested on the following clusters and confirm the charts showed in the main UI
- EC2 cluster
- custom cluster
- Imported GKE cluster

A more comprehensive test on the monitoring feature will be done later.  As to this issue, the above validation is sufficient.
