### ISSUE TITLE
Backport: Cluster monitoring cannot be restored once disabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19998]
https://github.com/rancher/rancher/issues/19209

**Comment by alena1108** [comment]
will be available in rc6

**Comment by jiaqiluo** [comment]
The issue is reopened. details: https://github.com/rancher/rancher/issues/19209#issuecomment-490671592

**Comment by jiaqiluo** [comment]
According to the conversation with @loganhz, the bug fix is validated and the issue can be closed. 

For more details please check comments in the upstream ticket : #19209
