### ISSUE TITLE
Use password store to save sensitive data in notifier configure

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#19991]
Rancher version: 2.2
Notifier sensitive data store in crd now. we could integrate with the latest password store to store them in the management side secret.
```k get notifiers.management.cattle.io --all-namespaces -o yaml```
![image](https://user-images.githubusercontent.com/5936271/57190091-27a60c00-6f49-11e9-81a6-84f9a2e2213c.png)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24335
