### ISSUE TITLE
Cannot change nodeport range

### ISSUE THREAD

**Issue by wendell-dev** [rancher/rancher#19993]
Steps:

1. Change nodeport range when create cluster to 8000-9000
2. Deploy a workload and add a node port
3. Try to input 8001 as the node port.

Result:

UI will auto change the port to 30000

**Comment by deniseschannon** [comment]
@loganhz can you see if this is true and reproducible?

**Comment by loganhz** [comment]
This has been fixed in master with https://github.com/rancher/rancher/commit/7bd6ebd166ee73e7c30706ea4c993175dfca2cf0#diff-6aee2186307640527a4a2bb6c3a56f3c

Close in favor of https://github.com/rancher/rancher/issues/18275#issuecomment-484410538
