### ISSUE TITLE
short-lived parametrized command containers

### ISSUE THREAD

**Issue by indeyets** [rancher/rancher#200]
Is there any support for containers which run parametrized commands?

Here's one of my use-cases: [composer/composer](https://registry.hub.docker.com/u/composer/composer/)

I need to mount it to a volume and then, from time to time, manually execute it with different parameters. I have an option to create several containers with different hardcoded commands. What I want, instead, is to be able to "pull" it and use in short-lived mode: `docker run --rm …`

In the ideal world, I would be able to pre-create several commands (bound to volume) based on this container for easy access in Rancher-ui

**Comment by deniseschannon** [comment]
@ibuildthecloud is this something that could be done?
