### ISSUE TITLE
OpenLDAP Cannot locate user information for (objectClass=inetOrgPerson)

### ISSUE THREAD

**Issue by coder-michaelwu** [rancher/rancher#20002]
When enabling openLDAP ,I get a error message : `Cannot locate user information for (objectClass=inetOrgPerson)`.
![image](https://user-images.githubusercontent.com/41537933/57274798-f5beb200-70ce-11e9-9def-f9237a749fa2.png)

I Just set first options `1. Configuer an OpenLDAP server`, And the sencond options `2. Customize Schema` keeps default value.
The same setup was successful in Rancher Version 1.6.25.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`global-admin.security.authentication.openldap`|

---
I got some logs from ldap server when I authenticate with openldap  :
```
[07/May/2019:11:06:36 +0800] SEARCH REQ conn=2532498 op=3 msgID=4 base="uid=xxx,ou=people,o=xxx.com.cn,o=isp" scope=base filter="(objectClass=inetOrgPerson)" attrs="1.1,+,*"
[07/May/2019:11:06:36 +0800] SEARCH RES conn=2532498 op=3 msgID=4 result=0 nentries=0 etime=1
```

When I get the right user info from ldap server，The Ldap server logs:
```
[07/May/2019:11:08:47 +0800] SEARCH REQ conn=2532641 op=12 msgID=29 base="uid=xxx,ou=people,o=xxx.com.cn,o=isp" scope=sub filter="(objectClass=inetOrgPerson)" attrs="1.1"
[07/May/2019:11:08:47 +0800] SEARCH RES conn=2532641 op=12 msgID=29 result=0 nentries=1 etime=1
```
Notice the difference between the two situation is search `scope`. But There are no options about "scope" in Rancher v2.x.

**Comment by mrajashree** [comment]
@coder-michaelwu The use Object Class value is inetOrgPerson by default which doesn't seem right for your setup. Can you check what that value was for your 1.6.25 setup and try that on your 2.x setup?

**Comment by mrajashree** [comment]
@coder-michaelwu Can you see if the following command returns any output for you?
```
ldapsearch -H ldap://ldapserver:port -x -D <DN of the test user used while setting up auth> -W -b <DN of the test user used while setting up auth> "(objectClass=inetOrgPerson)" "*" "+" "1.1"
```

If not then we can confirm that inetOrgPerson isn't the right object class. To find the appropriate object class you can run the following:
```
ldapsearch -H ldap://ldapserver:port -x -D <DN of the test user used while setting up auth> -W -b <DN of the test user used while setting up auth>  "*" "+" "1.1"
```
This will list the attributes of your test user and you can take the objectClass value from the output

**Comment by gabor-T-mandity** [comment]
We have the same issue with our Rancher env.
I tried the command you wrote above, and the objectClass for us seems to be OK (inetOrgPerson).
We had the same settings in Rancher 1.6 and it is working fine.

Rancher: v2.2.7
User Interface: v2.2.93
Helm: v2.10.0-rancher11
Machine: v0.15.0-rancher8-1

**Comment by coder-michaelwu** [comment]
@mrajashree 
The command you wrote above output:
The first one:
```
root@75b7acefa940:/# ldapsearch -H ldap://xx.xx.15.1x:389 -x -D "uid=apps,ou=Applications,o=xx.com,o=isp" -w xxx4 -b "uid=michael,ou=people,o=xx.com,o=isp" "(objectClass=inetOrgPerson)" "*" "+" "1.1"
# extended LDIF
#
# LDAPv3
# base <uid=michael,ou=people,o=xx.com,o=isp> with scope subtree
# filter: (objectClass=inetOrgPerson)
# requesting: * + 1.1 
#

# michael, People, xx.com, isp
dn: uid=michael,ou=People,o=xx.com,o=isp
objectClass: xx-person
objectClass: organizationalPerson
objectClass: top
objectClass: person
objectClass: inetOrgPerson
...
```
The second one:
```
root@75b7acefa940:/# ldapsearch -H ldap://xx.xx.15.1x:389 -x -D "uid=apps,ou=Applications,o=xx.com,o=isp" -w xxx4 -b "uid=michael,ou=people,o=xx.com,o=isp" "*" "+" "1.1"
# extended LDIF
#
# LDAPv3
# base <uid=michael,ou=people,o=xx.com,o=isp> with scope subtree
# filter: (objectclass=*)
# requesting: * + 1.1 
#

# michael, People, xx.com, isp
dn: uid=michael,ou=People,o=xx.com,o=isp
objectClass: xx-person
objectClass: organizationalPerson
objectClass: top
objectClass: person
objectClass: inetOrgPerson
passwordstrength: medium
...
```

**Comment by dahendel** [comment]
I am having the same issue attaching to our ldap provider. I have tried all the objectClasses

Cannot locate user information for (objectClass=inetOrgPerson)

`ldapsearch -H ldaps://ldap.xxx.com:636 -x -b "ou=Users,o=xxx,dc=xxx,dc=com" -D "uid=xxx,ou=Users,o=xxx,dc=xxx,dc=com" -W "(objectClass=inetOrgPerson)"`
```
# LDAPv3
# base <ou=Users,o=xxx,dc=xxx,dc=com> with scope subtree
# filter: (objectClass=inetOrgPerson)
# requesting: ALL
#

# xxx, Users, xxx, xxx.com
dn: uid=xxx,ou=Users,o=xxx,dc=xx,dc=com
mail: trudny@xxxxx
displayName: xxx
uidNumber: 5075
gidNumber: 5075
loginShell: /bin/bash
homeDirectory: /home/xxx
givenName: Anthony
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: shadowAccount
objectClass: posixAccount
```

Any update?
Rancher: 2.3.4

**Comment by spirit986** [comment]
I am having the same issue as well, any upates?
`TestAndApply Error
Cannot locate user information for (objectClass=inetOrgPerson)`

**Comment by dahendel** [comment]
@mrajashree @deniseschannon Do you all have any update on this?

**Comment by gabor-T-mandity** [comment]
Any update?

**Comment by wadeholler** [comment]
Same v2.3.5

**Comment by mrajashree** [comment]
@coder-michaelwu @dahendel @gabor-T-mandity @spirit986 @wadeholler can you please try the following ldapsearch command and let me know if it returns any ldap entries?
```
ldapsearch -H ldap://ldapserver:port -x -D <DN of the test user used while setting up auth> -s base -W -b <DN of the test user used while setting up auth> "(objectClass=inetOrgPerson)" "*" "+" "1.1"
```

**Comment by gabor-T-mandity** [comment]
@mrajashree I tried the command and got one entry back as the result. (the entry, which dn's was used as the search base)

**Comment by mrajashree** [comment]
@gabor-T-mandity So is the output same for the two commands? one with search scope set to `base` and one set to `subtree`? Rancher uses a query with `base` scope during login, and I was thinking maybe that's not fetching the right output. So I'm trying to see if the user entry is not returned when using `base` vs when using `subtree` scope

**Comment by wadeholler** [comment]
Yes I get back information for the test user AFTER our LDAP management admins updated the acls. I asked them for a description of what they changed and they said:

So it looks like I just added the following ACI, that allows read, write, search and compare on normal attributes, read, search and compare on sensitive attributes and read, search and compare on restricted attributes.  This is for users as self.  I think at one time that worked and may have needed adjusting since our upgrades.


access-id:CN=THIS:normal:rwsc:sensitive:rsc:restricted:rsc

**Comment by mrajashree** [comment]
@wadeholler Okay, so are you saying that solved the issue for you?

**Comment by wadeholler** [comment]
That is correct.   To be clear - this means that even though we provide a
bind user - for other purposes I know - that a "user" has to be allowed to
look up all their own information / attributes.  Is that correct ?

**Comment by mrajashree** [comment]
@wadeholler yes, seems like user needs read/search permissions for their own attributes.

@coder-michaelwu I see from your issue description you had attached ldap logs for search query done with both search scopes and the result is returned only for subtree, so let me test if that works for our test setups and we can make that change

**Comment by mrajashree** [comment]
We need to test auth setup and user login for openldap and freeipa

**Comment by sangeethah** [comment]
Reopening to get the fix merged in 2.4 release branch

**Comment by izaac** [comment]
Done this in tandem with #26061  Rancher versions described [here](https://github.com/rancher/rancher/issues/26061#issuecomment-611131140).
Rancher version: v2.4-head (04/06/2020) 04159d0 up to v2.4-head (04/08/2020) 64cf5ec

**Comment by soumyalj** [comment]
Tested with Rancher master-head build ( f47eb1a)
P1 scenarios and manual RBAC tests passed for the below Auth providers:

- OpenLDAP
- FreeIPA
- ActiveDirectory

**Comment by linmuqin** [comment]
Cannot locate user information for (&(objectClass=inetOrgPerson)(cn=readonly))
I have the same problem, is it still not fixed?
Rancher: 25.8

ldapsearch -H ldap://localhost:389 -x -D "cn=readonly,dc=xxx,dc=xxx" -w xxxx -b "cn=readonly,dc=xxx,dc=xxx" "(objectClass=inetOrgPerson)" "*" "+" "1.1"
# extended LDIF
#
# LDAPv3
# base <cn=readonly,dc=xxx,dc=xxx> with scope subtree
# filter: (objectClass=inetOrgPerson)
# requesting: * + 1.1 
#

# readonly, xxx.xxx
dn: cn=readonly,dc=xxx,dc=xxx
uid: readonly
sn: readonly
cn: readonly
objectClass: inetOrgPerson
objectClass: simpleSecurityObject
objectClass: top
objectClass: person
...
