### ISSUE TITLE
ListenConfig httpMode is not working. Is this intentionally disabled? 

### ISSUE THREAD

**Issue by ukinau** [rancher/rancher#20003]
**What kind of request is this (question/bug/enhancement/feature request):**

question

**Steps to reproduce (least amount of steps as possible):**
1. execute "kubectl edit listenconfig cli-config"
2. change mode from https to http 
3. save

**Result:**
Rancher Server doesn't listen http for Rancher API.

**Other details that may be helpful:**
I'm not sure this is expected behavior or not. 
But older version than v2.0.0-alpha17 actually supported http mode and we could configure Rancher Server to use http but after 605fd218e11fbc05565397c2598923654d5b24bf commit, http mode has gone and now we don't have a way to use Rancher Server with http.

if user put some loadbalancer in front of Rancher Server, the user sometimes want to terminate SSL in LB not in Rancher Server. In that case, I think it would be nice if we can configure Rancher Server to use http. That's why I want to know why this feature has gone, Is this intentionally removed?

**Environment information**
- rancher/rancher:v2.0.0-alpha17 ( later than 605fd218e11fbc05565397c2598923654d5b24bf commit)

**Comment by superseb** [comment]
The http-only flag was removed and the https redirect can be disabled by setting the `X-Forwarded-Proto` header, as seen here: https://github.com/rancher/rancher/blob/master/pkg/dynamiclistener/server.go#L497

Can be tested using
```
curl --header "X-Forwarded-Proto: https" http://127.0.0.1/v3/settings/cacerts
```

This is also documented at https://rancher.com/docs/rancher/v2.x/en/installation/single-node/single-node-install-external-lb/ and https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#external-tls-termination

**Comment by ukinau** [comment]
Thanks! I missed that point.
