### ISSUE TITLE
Make nodeTemplate exportable

### ISSUE THREAD

**Issue by garyhuang123** [rancher/rancher#20001]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Other details that may be helpful:**
It would be better if nodeTemplates can be exported out as file. And be able to imported into new cluster in case of the need of rebuilding up a new cluster.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17131
