### ISSUE TITLE
Describe certificate for Authorized Cluster Endpoint more clearly

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#20009]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Open Advanced Options and Authorized Cluster Endpoint:

<img width="1421" alt="Screen Shot 2019-05-06 at 15 59 34" src="https://user-images.githubusercontent.com/2620179/57230213-1b3cb480-7018-11e9-8e4f-934fb842f193.png">

**Result:**
Request is to put in a certificate and needed chain, while it is designated for the CA certificate to validate (as it is put in the kubeconfig)

**Comment by jensenbox** [comment]
For me, the confusion is around what it does with this cert. From what I am seeing (as a result of poking in the containers) it is only adding a section in the rendered kubconfig file and not actually pushing the cert down to the api-server. If this should be pushing down to the api-server I am not seeing that happen. We run our own CA and would prefer to inject our own cert for direct communication to the api-server. I cannot seem to find any docs that indicate how to do this.

**Comment by tfiduccia** [comment]
@superseb - we can add a ? next to the Certificate field with additional information.  What would you like to see in there?

**Comment by superseb** [comment]
- `Certificate` has to at least include `CA Certificate`
- The explanation on the CA certificate can either be in the title, or in the textbox explaining what should be pasted (which is also describing certificate vs CA certificate at the moment).
- Something along the lines of `Paste in the CA certificate that will be used in the generated kubeconfig(s) to validate the server certificate`. We have a docs part describing this feature as well: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#authorized-cluster-endpoint

**Comment by tfiduccia** [comment]
Add ? bubble with text and a link to the docs "For more info".
![image](https://user-images.githubusercontent.com/11514927/62887801-da2cfe00-bcf2-11e9-9d3b-803d03fd181e.png)

**Comment by tfiduccia** [comment]
Version - 8/13
Can you have the link open in a new window please, so it doesn't close rancher.

**Comment by tfiduccia** [comment]
@superseb - Here is the change.  Let me know if you want something else.  If not can you please close the issue.
![image](https://user-images.githubusercontent.com/11514927/62987888-e4d0bb80-bdf6-11e9-9211-dd163f708bd5.png)

**Comment by superseb** [comment]
1. On top of textbox: `Certificate` -> `CA Certificate`
1. In the textbox: `Paste in the CA certificate, starting with -----BEGIN CERTIFICATE-----`
1. In the popup: `The CA certificate will be placed in the generated kubeconfig file(s) to validate the certificate (chain) presented by the load balancer which you have configured at the provided FQDN. More information on this feature can be found in the documentation.`

Not sure if this might be too long for the popup?

**Comment by tfiduccia** [comment]
@superseb - the only thing that I changed was the final sentence.  The popup was getting too long so I just kept the "More info here."

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/21/2019)

- Rancher v2.2.8 doesn't have this change.
- Text content is in conformance with the request here https://github.com/rancher/rancher/issues/20009#issuecomment-522130760
- Latest Firefox and Chrome versions where used for validation.
- More info here. Link in the tooltip redirects to the proper Rancher documentation here: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#authorized-cluster-endpoint
- Tooltip gets rendered correctly in large and small UI layouts.

Sample screenshot:
<img width="1693" alt="Screen Shot 2019-08-21 at 12 16 57 PM" src="https://user-images.githubusercontent.com/27659/63461979-af3b5c00-c40e-11e9-9b46-45f16c21774a.png">
