### ISSUE TITLE
UI - catalog app page can't load page correctly if it doesn't contain the questions.yml file

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#20000]
**What kind of request is this (question/bug/enhancement/feature request):**
UI bug

**Steps to reproduce (least amount of steps as possible):**
1. add custom catalog e.g https://github.com/guangbochen/charts-test to the global catalog
2. go to the project level catalog apps page and click the Nginx app
3. the catalog app page can't display properly

![image](https://user-images.githubusercontent.com/4569037/57210626-e7f62780-700f-11e9-9b4b-1df772d31944.png)

**Result:**
catalog app page can't load page correctly if it does not contain the questions.yml file

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher master 06/05
- Installation option (single install/HA): HA&single

**Comment by JahavusDorahl** [comment]
I can confirm this is happening on v2.2.3-rc6. Any already installed apps are not loading if we try to upgrade or if we try install the app at the cluster level. Multi cluster seems to be loading.

```
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at n.parseQuestionsAndAnswers (component.js:288)
    at n.initTemplateModel (component.js:266)
    at component.js:70
    at e.invoke (0:34688)
    at e.flush (0:34604)
    at e.flush (0:34766)
    at e._end (0:35237)
    at MutationObserver._boundAutorunEnd (0:34934)
```

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19890
