### ISSUE TITLE
When deleting helm app namespace is not being deleted

### ISSUE THREAD

**Issue by gwiersma** [rancher/rancher#20004]
**What kind of request is this (question/bug/enhancement/feature request):** 
Bug

**Steps to reproduce (least amount of steps as possible):**
When deleting a App Catalog, the namespace is not being deleted en remains until a manual remove action is triggered. 

**Result:**
The namespace still exists after deleting the app 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.13.5

- Docker version (use `docker version`):  18.9.4

**Comment by deniseschannon** [comment]
This is by design and described why: https://rancher.com/docs/rancher/v2.x/en/catalog/apps/#deleting-catalog-application-deployments
