### ISSUE TITLE
Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by azbpa** [rancher/rancher#20011]
All of the sudden my Rancher Single container deployment stopped working (it refused connections to the UI). 

When I tried to restart the container I noticed the following log and the forever repeating message:

```
Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
```

Here is the full start up log:

```
2019/05/06 16:08:05 [INFO] Rancher version v2.1.8 is starting
2019/05/06 16:08:05 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2019/05/06 16:08:05 [INFO] Listening on /tmp/log.sock
2019/05/06 16:08:05 [INFO] Running etcd --peer-client-cert-auth --client-cert-auth --advertise-client-urls=https://127.0.0.1:2379,https://127.0.0.1:4001 --trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --peer-trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --data-dir=/var/lib/rancher/etcd/ --initial-cluster-token=etcd-cluster-1 --name=etcd-master --initial-cluster-state=new --heartbeat-interval=500 --election-timeout=5000 --initial-advertise-peer-urls=https://127.0.0.1:2380 --initial-cluster=etcd-master=https://127.0.0.1:2380 --cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --listen-client-urls=https://0.0.0.0:2379 --listen-peer-urls=https://0.0.0.0:2380 --peer-cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --peer-key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem
2019-05-06 16:08:05.518007 I | etcdmain: etcd Version: 3.2.13
2019-05-06 16:08:05.518026 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2019-05-06 16:08:05.518030 I | etcdmain: Go Version: go1.11
2019-05-06 16:08:05.518033 I | etcdmain: Go OS/Arch: linux/amd64
2019-05-06 16:08:05.518037 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2019-05-06 16:08:05.518105 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2019-05-06 16:08:05.518133 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2019-05-06 16:08:05.518573 I | embed: listening for peers on https://0.0.0.0:2380
2019-05-06 16:08:05.518618 I | embed: listening for client requests on 0.0.0.0:2379
2019-05-06 16:08:06.521742 W | etcdserver: another etcd process is using "/var/lib/rancher/etcd/member/snap/db" and holds the file lock.
2019-05-06 16:08:06.521759 W | etcdserver: waiting for it to exit before starting...
2019-05-06 16:08:15.600099 I | etcdserver: recovered store from snapshot at index 74100742
2019-05-06 16:08:15.650151 I | mvcc: restore compact to 69505013
2019-05-06 16:08:15.837148 I | etcdserver: name = etcd-master
2019-05-06 16:08:15.837172 I | etcdserver: data dir = /var/lib/rancher/etcd/
2019-05-06 16:08:15.837179 I | etcdserver: member dir = /var/lib/rancher/etcd/member
2019-05-06 16:08:15.837182 I | etcdserver: heartbeat = 500ms
2019-05-06 16:08:15.837186 I | etcdserver: election = 5000ms
2019-05-06 16:08:15.837189 I | etcdserver: snapshot count = 100000
2019-05-06 16:08:15.837230 I | etcdserver: advertise client URLs = https://127.0.0.1:2379,https://127.0.0.1:4001
2019-05-06 16:08:19.910817 I | etcdserver: restarting member e92d66acd89ecf29 in cluster 7581d6eb2d25405b at commit index 74171321
2019-05-06 16:08:19.912831 I | raft: e92d66acd89ecf29 became follower at term 150
2019-05-06 16:08:19.912853 I | raft: newRaft e92d66acd89ecf29 [peers: [e92d66acd89ecf29], term: 150, commit: 74171321, applied: 74100742, lastindex: 74171321, lastterm: 150]
2019-05-06 16:08:19.912969 I | etcdserver/api: enabled capabilities for version 3.2
2019-05-06 16:08:19.912981 I | etcdserver/membership: added member e92d66acd89ecf29 [https://127.0.0.1:2380] to cluster 7581d6eb2d25405b from store
2019-05-06 16:08:19.912988 I | etcdserver/membership: set the cluster version to 3.2 from store
2019-05-06 16:08:19.927814 I | mvcc: restore compact to 69505013
2019-05-06 16:08:20.107151 W | auth: simple token is not cryptographically signed
2019-05-06 16:08:20.120515 I | etcdserver: starting server... [version: 3.2.13, cluster version: 3.2]
2019-05-06 16:08:20.120884 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2019-05-06 16:08:24.413293 I | raft: e92d66acd89ecf29 is starting a new election at term 150
2019-05-06 16:08:24.413364 I | raft: e92d66acd89ecf29 became candidate at term 151
2019-05-06 16:08:24.413400 I | raft: e92d66acd89ecf29 received MsgVoteResp from e92d66acd89ecf29 at term 151
2019-05-06 16:08:24.413419 I | raft: e92d66acd89ecf29 became leader at term 151
2019-05-06 16:08:24.413426 I | raft: raft.node: e92d66acd89ecf29 elected leader e92d66acd89ecf29 at term 151
2019-05-06 16:08:24.415037 I | etcdserver: published {Name:etcd-master ClientURLs:[https://127.0.0.1:2379 https://127.0.0.1:4001]} to cluster 7581d6eb2d25405b
2019-05-06 16:08:24.415066 I | embed: ready to serve client requests
2019-05-06 16:08:24.415270 I | embed: serving client requests on [::]:2379
WARNING: 2019/05/06 16:08:24 Failed to dial 0.0.0.0:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
2019/05/06 16:08:25 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:26 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:27 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:28 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:29 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:30 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:31 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:32 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:33 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:34 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:35 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:36 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
2019/05/06 16:08:37 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
...
```

How can I recover my Rancher Server?

Thanks and Best Regards,
Paul

**Comment by dwoods** [comment]
I'm still on Rancher 2.0.8 and just noticed I'm having the exact same issue, which seemed to start yesterday.

**Comment by azbpa** [comment]
My guess is that some internal certificates are expired. However I am not sure if there is an official documentation on how to check this and, in case, how to rotate them by hand.

I noticed that since  Rancher 2.0.14, 2.1.9 and 2.2.x you can rotate certificates from UI: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/certificate-rotation/ (Btw there is also a typo related to the versions in the documentation: `Available as of v2.1.14 and v2.0.9` should be `Available as of v2.0.14 and v2.1.9`)

But I am running v2.1.8 and the UI is also unavailable since rancher doesn't start probably. So what to do if the UI is not available and/or one is running a lower version of Rancher server?

**Comment by azbpa** [comment]
Meanwhile I could verify that it is related to expired certificates.

1.  I set the system time of my host which is running the Rancher server container to one week in the past.
2. I started Rancher container and it was starting like expected and I could access the UI.
3. I was also able to upgrade to version 2.1.9 afterwards.

However, I noticed that I had a misunderstanding related to the new "rotate certificate" feature. It seems to only be available for the Kubernetes Clusters managed by Rancher. I thought I could rotate certificates of Rancher server itself.

So my question is how to renew certificates that Rancher server needs for all its components? Or should this be done automatically and the described behavior is a bug?

**Comment by winti** [comment]
+1 have exactly the same problem since yesterday morning. Did someone fixed this issue ?

**Comment by cjellick** [comment]
You have to upgrade to 2.0.14, 2.1.9, or 2.2.2 to get this fix.

**Comment by vincent99** [comment]
2.2.2/2.1.9/2.0.14 automatically rotates the self-signed server certificate it generates before it expires.  If you are on an older version, upgrade.

If you provided your own cert, you need to generate a new one and provide it to the server.

If you're using LetsEncrypt, it should already have be renewing itself.

**Comment by cjellick** [comment]
thats for the better explanation @vincent99. mine was quite terse

**Comment by winti** [comment]
after upgrading to latest version i am able to login, but getting: 

This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Failed to get Kubernetes server version: Get https://aaa.bbb.ccc.ddd:6443/version?timeout=32s: x509: certificate has expired or is not yet valid; exit status 1, unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request

**Comment by galal-hussein** [comment]
You need to rotate the certificates of the cluster managed by Rancher, you can do that from the UI, for more information please refer to the documentation https://rancher.com/docs/rancher/v2.x/en/cluster-admin/certificate-rotation/

**Comment by winti** [comment]
this did not solve the issue.
logs on single node rancher server::
[cluster-provisioner-controller] failed with : failed to get Kubernetes server version: Get https://172.18.112.63:6443/version?timeout=32s: x509: certificate has expired or is not yet valid
2019/05/07 21:15:43 [ERROR] Unknown error: Get https://172.18.112.63:6443/api/v1/namespaces?timeout=30s: x509: certificate has expired or is not yet valid
2019/05/07 21:15:57 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10780
2019/05/07 21:16:00 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:16:00 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:16:00 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:16:03 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/05/07 21:16:03 [ERROR] ClusterController c-zsdvm [cluster-deploy] failed with : exit status 1, unable to recognize "management-state/tmp/yaml-679521004": the server is currently unable to handle the request
unable to recognize "management-state/tmp/yaml-679521004": the server is currently unable to handle the request
unable to recognize "management-state/tmp/yaml-679521004": the server is currently unable to handle the request
unable to recognize "management-state/tmp/yaml-679521004": the server is currently unable to handle the request
unable to recognize "management-state/tmp/yaml-679521004": the server is currently unable to handle the request
unable to recognize "management-state/tmp/yaml-679521004": the server is currently unable to handle the request
unable to recognize "management-state/tmp/yaml-679521004": the server is currently unable to handle the request
, [cluster-provisioner-controller] failed with : failed to get Kubernetes server version: Get https://172.18.112.63:6443/version?timeout=32s: x509: certificate has expired or is not yet valid
2019/05/07 21:16:09 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:18:00 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:18:00 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:18:00 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:18:17 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019-05-07 21:19:56.641765 I | mvcc: store.index: compact 43760923
2019-05-07 21:19:57.092729 I | mvcc: finished scheduled compaction at 43760923 (took 428.832728ms)
2019/05/07 21:20:01 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:20:01 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:20:01 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release
2019/05/07 21:20:20 [WARNING] v1.10.1-rancher1 version exists but its recommended to install this version - see 'rke config --system-images --all' for versions supported with this release

**Comment by azbpa** [comment]
Like I wrote I upgraded to 2.1.9 but with no success.

Then I tried to upgrade to 2.2.2 which seems to solve my issue.

So thanks for your help. Feel free to close the issue or keep it to check why upgrade to 2.1.9 didn't solves the issue despite it should as of @vincent99 answer: https://github.com/rancher/rancher/issues/20011#issuecomment-490146275

**Comment by dwoods** [comment]
I can also confirm that upgrading to v2.2.2 resolves the issue.

**Comment by winti** [comment]
unfortunately for me upgrading to 2.2.2 did not solve the issue. I am able to login but etcd is still not ok. 
I suspect that this could be a issue in conjunction with the custom godaddy wildcard certificate in place on the standalone rancher admin node.

logs:
2019/05/08 20:30:00 [ERROR] ClusterController c-zsdvm [cluster-provisioner-controller] failed with : failed to get Kubernetes server version: Get https://172.18.112.63:6443/version?timeout=32s: x509: certificate has expired or is not yet valid

screenshots - rancher global view & cert on etcd & worker nodes.
![image](https://user-images.githubusercontent.com/906476/57407089-ab2e5a00-71e2-11e9-98d4-96abb8746b1b.jpeg)

![image](https://user-images.githubusercontent.com/906476/57407076-a1a4f200-71e2-11e9-9072-9004bb405182.jpeg)

Maybe one way to solve this issue could be startup rancher with the standard rancher certs to enable the agents to server communication again. How to overwride the custom certs supplied once by myself with the standard rancher certs/ca ?

**Comment by adampl** [comment]
I don't have any custom certificate. I just received a notification from Rancher that says:
> The system component etcd is not running
> Get https://_(secret)_/health: remote error: tls: bad certificate
> Get https://_(secret)_/health: x509: certificate has expired or is not yet valid

So I decided to rotate certificates for `etcd`, but the process got stuck in this state:
![image](https://user-images.githubusercontent.com/6024937/57542074-e51d6e80-7350-11e9-9bcb-d57aa822359d.png)

The status of `etcd` hasn't changed:
![image](https://user-images.githubusercontent.com/6024937/57544365-6972f000-7357-11e9-9a27-21375d4c02ed.png)

Repeating didn't help. What else can I do to fix this?

**Environment:**
Rancher: 2.2.2 (single node)
Docker: 18.9.1
Kubernetes: 1.11.6
System: Ubuntu Server 16 LTS
Cluster: 3 nodes, every node has all roles

**Rancher logs while rotating certificates:**
```
2019/05/10 16:08:14 [INFO] Provisioning cluster [c-vh2tk]
2019/05/10 16:08:14 [INFO] Rotating certificates for cluster [c-vh2tk]
2019/05/10 16:08:19 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10849
2019/05/10 16:08:19 [INFO] cluster [c-vh2tk] provisioning: Initiating Kubernetes cluster
2019/05/10 16:08:19 [INFO] cluster [c-vh2tk] provisioning: [state] Possible legacy cluster detected, trying to upgrade
2019/05/10 16:08:19 [INFO] cluster [c-vh2tk] provisioning: [reconcile] Rebuilding and updating local kube config
2019/05/10 16:08:19 [INFO] cluster [c-vh2tk] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-191947062/kube_config_cluster.yml]
2019/05/10 16:08:20 [INFO] cluster [c-vh2tk] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-191947062/kube_config_cluster.yml]
2019/05/10 16:08:20 [INFO] cluster [c-vh2tk] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-191947062/kube_config_cluster.yml]
2019/05/10 16:08:20 [INFO] cluster [c-vh2tk] provisioning: [state] Fetching cluster state from Kubernetes
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: Timed out waiting for kubernetes cluster to get state
2019/05/10 16:08:50 [ERROR] cluster [c-vh2tk] provisioning: Failed to fetch state from kubernetes: Timeout waiting for kubernetes cluster to get state
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: [dialer] Setup tunnel for host [10.123.0.140]
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: [dialer] Setup tunnel for host [10.123.0.139]
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: [dialer] Setup tunnel for host [10.123.0.138]
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: [state] Fetching cluster state from Nodes
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: [state] Successfully started [cluster-state-deployer] container on host [10.123.0.140]
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: [state] Successfully fetched cluster state from Nodes
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: [certificates] Getting Cluster certificates from Kubernetes
2019/05/10 16:08:50 [ERROR] cluster [c-vh2tk] provisioning: Failed to fetch certs from kubernetes: Unauthorized
2019/05/10 16:08:50 [INFO] cluster [c-vh2tk] provisioning: [certificates] Fetching kubernetes certificates from nodes
2019/05/10 16:08:54 [INFO] cluster [c-vh2tk] provisioning: [certificates] Successfully started [cert-fetcher] container on host [10.123.0.139]
2019/05/10 16:08:55 [INFO] cluster [c-vh2tk] provisioning: [certificates] Successfully started [cert-fetcher] container on host [10.123.0.138]
2019/05/10 16:08:56 [INFO] cluster [c-vh2tk] provisioning: Successfully Deployed state file at [management-state/rke/rke-191947062/cluster.rkestate]
2019/05/10 16:08:56 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/05/10 16:08:56 [INFO] cluster [c-vh2tk] provisioning: Rotating Kubernetes cluster certificates
2019/05/10 16:08:56 [ERROR] ClusterController c-vh2tk [cluster-provisioner-controller] failed with : CA Certificate or Key is empty
```

**Excerpt from the _kubelet_ logs when the error first occured:**
```
E0510 15:34:49.347087    5245 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "(secret)": Unauthorized
E0510 15:34:49.348230    5245 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "(secret)": Unauthorized
E0510 15:34:49.362569    5245 reflector.go:322] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to watch *v1.Service: the server has asked for the client to provide credentials (get services)
E0510 15:34:49.362606    5245 reflector.go:322] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to watch *v1.Pod: the server has asked for the client to provide credentials (get pods)
E0510 15:34:49.362665    5245 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "(secret)": Unauthorized
W0510 15:34:49.366071    5245 reflector.go:341] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: watch of *v1.Node ended with: very short watch: k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Unexpected watch close - watch lasted less than a second and no items received
E0510 15:34:49.376135    5245 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "(secret)": Unauthorized
E0510 15:34:49.385181    5245 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "(secret)": Unauthorized
E0510 15:34:49.385411    5245 kubelet_node_status.go:379] Unable to update node status: update node status exceeds retry count
E0510 15:34:50.372074    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
E0510 15:34:50.383590    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
E0510 15:34:50.384441    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
E0510 15:34:51.373452    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
E0510 15:34:51.384917    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
E0510 15:34:51.385373    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
E0510 15:34:52.374441    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
E0510 15:34:52.385695    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
E0510 15:34:52.386622    5245 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
```
The logs go on like this with lots of "unauthorized" :(

**Comment by jinchaoxiang** [comment]
@azbpa what can we do to resolve this question？

**Comment by sprutton1** [comment]
We are experiencing this same issue. We tried to upgrade to 2.2.2, but we are seeing similar issues.
```
2019/06/19 00:53:22 [INFO] cluster [c-rvc5c] provisioning: [dialer] Setup tunnel for host [10.40.7.35]
2019/06/19 00:53:22 [INFO] cluster [c-rvc5c] provisioning: [state] Fetching cluster state from Nodes
2019/06/19 00:53:22 [INFO] cluster [c-rvc5c] provisioning: [state] Successfully fetched cluster state from Nodes
2019/06/19 00:53:22 [INFO] cluster [c-rvc5c] provisioning: [certificates] Getting Cluster certificates from Kubernetes
2019/06/19 00:53:22 [ERROR] cluster [c-rvc5c] provisioning: Failed to fetch certs from kubernetes: Unauthorized
2019/06/19 00:53:22 [INFO] cluster [c-rvc5c] provisioning: [certificates] Fetching kubernetes certificates from nodes
2019/06/19 00:53:22 [INFO] cluster [c-rvc5c] provisioning: Successfully Deployed state file at [management-state/rke/rke-373043753/cluster.rkestate]
2019/06/19 00:53:22 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/06/19 00:53:22 [INFO] cluster [c-rvc5c] provisioning: Rotating Kubernetes cluster certificates
2019/06/19 00:53:38 [ERROR] ClusterController c-rvc5c [cluster-provisioner-controller] failed with : CA Certificate or Key is empty
2019/06/19 00:53:48 [INFO] Stopping cluster agent for c-rvc5c
```

**Comment by spawnia** [comment]
I think this is related to https://github.com/rancher/rancher/issues/20381

**Comment by AmitDJagtap** [comment]
Upgrading the Rancher version to more than 2.2.5 worked for me. Basically worth trying and restarting the Rancher host as well instead of nodes.

**Comment by papaiatis** [comment]
I'm using Rancher 2.2.7, 8 days ago I created a custom API key for "rancher login" for a different server. Now I tried to "rancher login" again and I'm getting the same error message:
`FATA[0000] Get https://rancher.MYDOMAIN.com/v3: x509: certificate has expired or is not yet valid`
Any idea how to fix it?

**Comment by 0x4c6565** [comment]
> 
> 
> I'm using Rancher 2.2.7, 8 days ago I created a custom API key for "rancher login" for a different server. Now I tried to "rancher login" again and I'm getting the same error message:
> `FATA[0000] Get https://rancher.MYDOMAIN.com/v3: x509: certificate has expired or is not yet valid`
> Any idea how to fix it?

I'm also seeing this (use the rancher CLI) - the `--skip-verify` flag seems to have no effect

**Comment by SrslyJosh** [comment]
Really cool to have a built-in self destruct. 👍

**Comment by SrslyJosh** [comment]
Seems like this should be linked here: [Manual Rotation of Certificates in Rancher Kubernetes Clusters](https://rancher.com/blog/2019/kubernetes-certificate-expiry-and-rotation-in-rancher-kubernetes-clusters/)

**Comment by de-robat** [comment]
We had the same issue. The rancher-server ui did not come up anymore and always kept restarting it self due to trying to access the api server under localhost:6443 . We then went into the servers file system (exec into the docker container) and found a directory `/var/lib/rancher/management-state/tls/` which had a localhost.crt which had expired (check with: `openssl x509 -enddate -noout -in localhost.crt`) . We renamed it to localhost.crt_back and restarted the container, and voila it was regenerated an resigned. The ui went live again.

P.S. if you struggle to manage all these steps within the brief timeframe before the container restarts, simply alter the date of your host to be in the past so that the internal crt is beeing considered valid again.

**Comment by SumeetR** [comment]
@de-robat Thanks for your solution. We were experiencing the same issue, having upgraded Rancher many times and suddenly we weren't able to access it since Friday. Went in the machine running the rancher docker image and looking and the logs and your solution, was able to identify that the certificate had expired (2nd April) and Rancher was not able to update it, probably due to the fact that an older version of Rancher had generated the .crt.

Anyway, renaming the .crt made Rancher create a new one and now it seems to be up and running. 

Thanks once again @de-robat !

**Comment by kpolszewski** [comment]
ugh! 
@de-robat you saved my day! it worked.

It was such a pain to find it. To this moment I was only aware of autorotated /etc/kubernetes/.tmp certificates and they had like 10 years more to expire so I had no idea what was going on.

**Comment by mbstacy** [comment]
@de-robat Thank you! Thank you. Your comment needs to be elevated and included within some documentation. Saved my bacon! Solution worked perfectly. 
 
I was using Lets Encrypt but did not update the container from v2.2.8. Lets Encrypt deprecation caused my localhost.crt not to update correctly.  I was running v2.2.8 and updated to v2.2.10 and moved localhost.crt to localhost.crt_back!!! Everything returned as expected. Problem solved.

Thanks again

**Comment by mthird** [comment]
> P.S. if you struggle to manage all these steps within the brief timeframe before the container restarts, simply alter the date of your host to be in the past so that the internal crt is beeing considered valid again.

Another approach we took was to create a "rescue" container that mapped the volume from the rancher container.

**Comment by mertikub** [comment]
We had the same problem. The Rancher UI stopped responding.  The only thing bringing to life was to rename /var/lib/rancher/management-state/certs/bundle.json -> /var/lib/rancher/management-state/certs/bundle.json_back and then we did an upgrade to v2.1.10. Maybe even the restart would have done the same effect, not sure.
