### ISSUE TITLE
New alerts rules  is invalid

### ISSUE THREAD

**Issue by symenghuan** [rancher/rancher#20016]
**What kind of request is this (question/bug/enhancement/feature request):**
This is question:
I  delete the   cluster-alerting and monitoring-operator  , the node rules  is invalid，have not alertmanager sync
But the metric rules (cluster monitoring ) is normal

**Steps to reproduce (least amount of steps as possible):**
1、closed  cluster monitoring
2、delete cluster-alerting and monitoring-operator，and all alert rules
3、rancher server:   kubectl get cluster ,kubectl edit cluster ${clusterid}  , init the cluster-alerting and monitoring-operator
![image](https://user-images.githubusercontent.com/44770931/57267525-06612f00-70b3-11e9-8b51-dcbd374e8e31.png)

**Result:**
I  also  init the alert ,  have no alertmanager message(metric is  normal), and  the  metric alert rules  always green, no red remind

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.2.2

@loganhz @aiwantaozi

**Comment by aiwantaozi** [comment]
What can I help you?

**Comment by symenghuan** [comment]
> What can I help you?

I want to know how to solve and handle this requestion
