### ISSUE TITLE
nginx-ingress-controller Unavailable

### ISSUE THREAD

**Issue by we7team** [rancher/rancher#20013]
-------------------------------------------------------------------------------
NGINX Ingress controller
Release: 0.21.0-rancher3
Build:
Repository: https://github.com/rancher/ingress-nginx.git
-------------------------------------------------------------------------------
nginx version: nginx/1.15.6
W0506 22:11:49.240939 7 client_config.go:548] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
I0506 22:11:49.241174 7 main.go:196] Creating API client for https://10.43.0.1:443
I0506 22:11:49.249533 7 main.go:240] Running in Kubernetes cluster version v1.13 (v1.13.5) - git (clean) commit 2166946f41b36dea2c4626f90a77706f426cdea2 - platform linux/amd64
I0506 22:11:49.251452 7 main.go:101] Validated ingress-nginx/default-http-backend as the default backend.
I0506 22:11:49.373574 7 nginx.go:258] Starting NGINX Ingress controller
I0506 22:11:49.381439 7 event.go:221] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"tcp-services", UID:"f8aea0ef-704a-11e9-b8dc-525400055e0b", APIVersion:"v1", ResourceVersion:"479", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-nginx/tcp-services
I0506 22:11:49.381541 7 event.go:221] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"udp-services", UID:"f8b0513e-704a-11e9-b8dc-525400055e0b", APIVersion:"v1", ResourceVersion:"482", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-nginx/udp-services
I0506 22:11:49.383135 7 event.go:221] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"nginx-configuration", UID:"f8acdbe6-704a-11e9-b8dc-525400055e0b", APIVersion:"v1", ResourceVersion:"478", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-nginx/nginx-configuration
I0506 22:11:50.573969 7 nginx.go:279] Starting NGINX process
I0506 22:11:50.574230 7 leaderelection.go:187] attempting to acquire leader lease ingress-nginx/ingress-controller-leader-nginx...
I0506 22:11:50.574902 7 controller.go:172] Configuration changes detected, backend reload required.
I0506 22:11:50.579707 7 leaderelection.go:196] successfully acquired lease ingress-nginx/ingress-controller-leader-nginx
I0506 22:11:50.579862 7 status.go:148] new leader elected: nginx-ingress-controller-l5nsx
I0506 22:11:50.700798 7 controller.go:190] Backend successfully reloaded.
I0506 22:11:50.700839 7 controller.go:202] Initial sync, sleeping for 1 second.
2019/05/06 22:11:51 [error] 51#51: *8 access forbidden by rule, client: 10.0.64.214, server: , request: "POST /configuration/backends HTTP/1.1", host: "localhost:18080"
W0506 22:11:51.702380 7 controller.go:220] Dynamic reconfiguration failed: unexpected error code: 403
E0506 22:11:51.702396 7 controller.go:224] Unexpected failure reconfiguring NGINX:
unexpected error code: 403
W0506 22:11:51.702402 7 queue.go:130] requeuing initial-sync, err unexpected error code: 403
I0506 22:11:53.908312 7 controller.go:172] Configuration changes detected, backend reload required.
I0506 22:11:54.028773 7 controller.go:190] Backend successfully reloaded.
I0506 22:11:54.028800 7 controller.go:202] Initial sync, sleeping for 1 second.
2019/05/06 22:11:55 [error] 128#128: *37 access forbidden by rule, client: 10.0.64.214, server: , request: "POST /configuration/backends HTTP/1.1", host: "localhost:18080"
W0506 22:11:55.029789 7 controller.go:220] Dynamic reconfiguration failed: unexpected error code: 403
E0506 22:11:55.029808 7 controller.go:224] Unexpected failure reconfiguring NGINX:
unexpected error code: 403

rancher v2.2.2

**Comment by we7team** [comment]
![111](https://user-images.githubusercontent.com/4837122/57258634-968d7d00-708f-11e9-9c79-a3dfa9d1cd02.png)
![222](https://user-images.githubusercontent.com/4837122/57258638-9b523100-708f-11e9-8d73-cee53e1c77a1.png)

**Comment by orangedeng** [comment]
I would like to have the `nginx.conf` in the `nginx-ingress-controller`. Try to local the session for listen port 18080. It should look like:
```
...
                location /configuration {
                        access_log off;

                        allow 127.0.0.1;

                        allow ::1;

                        deny all;

                        # this should be equals to configuration_data dict
                        client_max_body_size                    10m;
                        client_body_buffer_size                 10m;
                        proxy_buffering                         off;

                        content_by_lua_block {
                                configuration.call()
                        }
                }
...
```

**Comment by orangedeng** [comment]
And try to `curl -v localhost:18080/configuration/backends` in the host of you ingress controller pod and see 403 appears or not.
If so, you need to check `ip add` or `ifconfig` on your host whether there is a `lo` interface in the list.

**Comment by we7team** [comment]
**node ifconfig：**
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.64.214  netmask 255.255.192.0  broadcast 10.0.127.255
        ether 52:54:00:05:5e:0b  txqueuelen 1000  (Ethernet)
        RX packets 1183348  bytes 1269436793 (1.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 572703  bytes 71686947 (68.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4195401  bytes 1006716347 (960.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4195401  bytes 1006716347 (960.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**nginx-ingress-controller notice：**
2019/05/07 06:29:02 [error] 519#519: *190 access forbidden by rule, client: 10.0.64.214, server: , request: "POST /configuration/backends HTTP/1.1", host: "localhost:18080"

nginx-ingress-controller containers always reboot, how to chage nginx.conf,i think this is a bug

**Comment by we7team** [comment]
@orangedeng 
![image](https://user-images.githubusercontent.com/4837122/57277560-fbb89100-70d6-11e9-8d3d-5ad79069064f.png)

**Comment by we7team** [comment]
i found new version fix this question,can u release it?

https://github.com/rancher/ingress-nginx/tree/nginx-0.24.0-fix
![image](https://user-images.githubusercontent.com/4837122/57292655-d3d82600-70f4-11e9-9b2b-0ba176f5c470.png)

**Comment by we7team** [comment]
ingress用了host网络模式，但是ingress访问localhost:18080的client是10开头的内网ip，但是ingress的nginx.conf限制只允许127.0.0.1访问。

这地方应该是个悖论，k8s官方的包已经修复了这个问题，rancher nginx ingress最新版0.24也修复了，但是release还是0.21的。

发布一下新版就行了

**Comment by we7team** [comment]
想了很久，容器用了宿主机器的网络，为啥访问localhost，客户端ip是内网ip而不是127.0.0.1。不知道哪里出问题了

**Comment by superseb** [comment]
Let us know if this still needs a follow up
