### ISSUE TITLE
云上worker不能上线

### ISSUE THREAD

**Issue by timebubble** [rancher/rancher#20014]
worker部署的时候获取到了server的内网地址而不是外网地址
tools 日志：

2019/05/07 00:49:16 [error] 11#11: *747 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "192.168.x.x:6443", bytes from/to client:0/0, bytes from/to upstream:0/0

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`ingresses.index`|

**Comment by timebubble** [comment]
补充：
报错的容器：
rancher/rke-tools:v0.1.27            "nginx-proxy CP_HOST…"   21 seconds ago      Up 20 seconds                           nginx-proxy

**Comment by deniseschannon** [comment]
Can you please file an issue in english with steps on how to reproduce?
