### ISSUE TITLE
Backport: Monitoring - kube-state exporter print too many error log

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20018]
https://github.com/rancher/rancher/issues/18830

**Comment by alena1108** [comment]
can be tested with rc7

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rnacher: v2.2.3-rc7

Step:
- add an ec2 cluster
- enable cluster monitoring
- check the log of the workload `exporter-kube-state-cluster-monitoring` under proejct `System` and the namespace `cattle-prometheus`

Result:
- the error messages showed in the original issue are gone
<img width="1809" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57339207-94eea400-70e5-11e9-9547-0c7e94f114f3.png">
