### ISSUE TITLE
Backport: Use of 127.0.0.1 vs localhost in prometheus-cluster-monitoring StatefulSet

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20019]
https://github.com/rancher/rancher/issues/19243

**Comment by alena1108** [comment]
can be tested with rc7

**Comment by jiaqiluo** [comment]
The enhancement is validated on Rancher: v2.2.3-rc7

After enabling the cluster monitoring, go to check and confirm that 
- view the YAML file of the pod `prometheus-cluster-monitoring-0` and  see the configuration of container `prometheus`'s args has  
```
- --web.listen-address=127.0.0.1:9090
```
- inside the pod `prometheus-cluster-monitoring-0`, view the log of the container `prometheus-agent` and see this as the firt line
```
INFO[2019-05-07T22:40:32Z] listening on 10.42.3.5:9090, proxying to http://127.0.0.1:9090 with ignoring 'remote reader' labels [prometheus,prometheus_replica], only allow maximum 512 connections with 5m0s read timeout .
```

Those two checks should be sufficient to validate that `http://127.0.0.1:9090` is used instesad of `localhost`
