### ISSUE TITLE
[Windows] Restarting the rancher-agent service will cause the pod to be recreated.

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#20026]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add a windows cluster and wait for the cluster to boot successfully.
2. Run `Restart-Service rancher-agent` on the windows node to restart the rancher-agent service.

**Result:**
Restarting the "rancher-agent" service on the windows node will cause the pod on the node to be recreated.
```
  Normal   SandboxChanged  8s                 kubelet, ec2amaz-517t2kg  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         7s                 kubelet, ec2amaz-517t2kg  Pulling image "mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019"
  Normal   Pulled          6s                 kubelet, ec2amaz-517t2kg  Successfully pulled image "mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019"
  Normal   Created         6s                 kubelet, ec2amaz-517t2kg  Created container w1
  Normal   Started         5s                 kubelet, ec2amaz-517t2kg  Started container w1
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master 05/05
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.14.1

**Comment by sowmyav27** [comment]
Reproduced on `rancher:v2.3.0-alpha3`
1. Bring up a windows cluster - 2 linux nodes: 1 - all roles, 1 - worker role, 1 windows nodes - worker.
2. Deploy a workload on windows node.
3. Run `Restart-Service rancher-agent` on the windows node.
4. Pod on the windows node is also restarted. 
<img width="1415" alt="Screen Shot 2019-06-10 at 1 00 43 PM" src="https://user-images.githubusercontent.com/26032343/59223042-d90b1380-8b7f-11e9-8e78-1bf813d275a7.png">

verified with rancher:master(06/10/2019)
1. Bring up a windows cluster - 1 linux node: 1 - all roles, 1 windows nodes - worker.
2. Deploy a workload on windows node.
3. Run `Restart-Service rancher-agent` on the windows node.
4. Pod on the windows node does not get restarted.
