### ISSUE TITLE
Backport:rancher cluster monitoring, prometheus keeps getting oomkilled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20021]
https://github.com/rancher/rancher/issues/19673

**Comment by alena1108** [comment]
can be tested with rc7

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:v2.2.6

Steps:
- run Rancher container single install
- add an EC2 cluster with 3 etcd/control plane nodes, 3 workers nodes. Each node is t2.medium 2 vCPU, 4 GB memory
- enable the cluster monitoring with all default settings 
- run some automation test on the cluster to make it "busy"
- keep and observe the cluster monitoring apps for a while (its 16+ hours as the time writing the comment)

Results:
- the pod `prometheus-cluster-monitoring-0` in workload `prometheus-cluster-monitoring` does not get oomkilled anymore
- the cluster monitoring feature works as expected 

<img width="1423" alt="Screen Shot 2019-07-25 at 9 08 05 AM" src="https://user-images.githubusercontent.com/6218999/61890160-bf1d5a00-aebb-11e9-8a1b-0161e81c0c41.png">

<img width="1857" alt="Screen Shot 2019-07-25 at 9 03 17 AM" src="https://user-images.githubusercontent.com/6218999/61890134-b3319800-aebb-11e9-93c8-c2f7b291ed1a.png">
