### ISSUE TITLE
Backport:Still see extra groups under Alerts some of the time

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20023]
https://github.com/rancher/rancher/issues/19913

**Comment by loganhz** [comment]
already in rc6

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc6

I can no longer reproduce the issue. I followed Logan's suggested steps (#19913 ) and also smoke tested for a while to try to reproduce the issue in other ways, such as waiting for a time, having various clusters with different alert rules/groups/etc. I still am not able to run into the issue so I believe this is safe to close. I will continue to keep an eye out to see if the issue happens again.
