### ISSUE TITLE
Air-gapped cluster provisioning fails when private registry requires authentication

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#20029]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher HA following the [HA air gapped installation docs](https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/).

2. In [step 2](https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/prepare-private-registry/), publish the images to a private registry (say, `private.registry.com`) that requires authentication to push/pull images.

3. Note how in [Step 5](https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/config-rancher-for-private-reg) one configures Rancher to `use the private registry in order to provision any Rancher launched Kubernetes clusters`.

4. Once Rancher is installed, create a vSphere node template

5. Create a cluster using the vSphere node template, and configuring the private registry from step 2 as "default system registry" while providing credentials allowing to pull the images.

**Result:**
Cluster creation fails. After nodes were provisioned the following error was logged:

```
Unable to find image 'private.registry.com/rancher/rancher-agent:v2.2.2' locally
 docker: Error response from daemon: Get https://private.registry.com/v2/:  unauthorized: authentication required
```

**Other details that may be helpful:**
While Rancher uses the credentials configured for the cluster private registry when pulling the RKE system images, it does not use the credentials when pulling the initial Rancher Agent image via the docker-machine ssh connection.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by moelsayed** [comment]
The issue is not specific to air gapped setups. This happens when:
- Rancher is configured with server level private registry(no configurable credentials).
- That private registry requires authentication. 
When rancher provisions a node, it will install docker and then try to pull the agent image from the server level private registry. Since the registry requires authentication, the pull will fail:
```
2019/08/27 17:46:10 [INFO] [node-controller-docker-machine] Installing Docker...
2019/08/27 17:46:46 [INFO] [node-controller-docker-machine] Copying certs to the local machine directory...
2019/08/27 17:46:50 [INFO] [node-controller-docker-machine] Copying certs to the remote machine...
2019/08/27 17:46:57 [INFO] [node-controller-docker-machine] Setting Docker configuration on the remote daemon...
2019/08/27 17:47:06 [INFO] [node-controller-docker-machine] Checking connection to Docker...
2019/08/27 17:47:06 [INFO] [node-controller-docker-machine] Docker is up and running!
2019/08/27 17:47:08 [INFO] Generating and uploading node config melsayed-1
2019/08/27 17:47:08 [ERROR] NodeController c-jj49x/m-5bqhz [node-controller] failed with : Unable to find image 'private.registry.com/rancher/rancher-agent:dev' locally
docker: Error response from daemon: Get https://private.registry.com/v2/rancher/rancher-agent/manifests/dev: no basic auth credentials.
See 'docker run --help'.
Process exited with status 125
: exit status 1

```

I can think of two possible fixes:
- Modify the docker install script to read env variables and deploy registry auth config on the node during docker install. This is a work around.
- Patch our machine fork to accept registry credentials and deploy them on the node before pulling. 

In both cases, I am not sure how this will work with special cases like vSphere. This needs to be validated first.

**Comment by janeczku** [comment]
@moelsayed @alena1108 

It seems that cluster-level private registry settings are not only ignored when launching initial rancher-agent via Docker but also when creating the node-agent, cluster-agent K8s deployment/daemonset resources (see screenshot where kube-system and cattle-system images are pulled from different registries).

It would be good if we could address both so that cluster-level system registry applies to all system images required to provision a cluster.

<img width="941" alt="Screenshot 2019-09-10 at 18 08 17" src="https://user-images.githubusercontent.com/3813921/64660592-5aa16480-d441-11e9-9a26-46e1ab746532.png">

**Comment by alena1108** [comment]
@janeczku addressing node-agent, cluster-agent should be relatively easy (configuring and referring private registry secret cred in cluster-agent deployment yaml), and we can definitely address that.

For rancher-agent via Docker, the registry has to be pre-set on the docker side. We can't really automate it on Rancher. It was done this way in 1.6 The only thing we can do is - let user configure the rancher-agent image custom url/path. Please confirm if that would be enough to satisfy the basic requirements, and we'll get the ball rolling :)

**Comment by janeczku** [comment]
@alena1108 As discussed out-of-band, the proposed fix would be enough to meet the requirements.

**Comment by alena1108** [comment]
For qa:

The tests are better to perform in a true airgap setup. If that is not feasible (machine provisioned cluster), make sure private registry is credentials protected.

Perform the test for machine provisioned cluster (DO, etc) and custom cluster
* Deploy the cluster. Validate that cluster/node agent deployments have private registry image by looking at the system project. Login to the host, check all rancher system images, make sure they are coming from the private repo. Check all containers, even the ones that have exited (`docker ps -a`), make sure their image is coming from the private repo.
* Update private registry for the cluster. Check system project, all deployments should switch to the new images from the new repo


For custom cluster, make sure that the command generated by the UI has agent image prepended with the private repo url.

**Comment by deniseschannon** [comment]
@sangeethah @bmdepesa A requirement of testing this issue is to test with Azure Private Registry.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.4-rc3

**Cluster level private registry & Rancher agents**
* Reproduced in v2.3.3
* Provision a cluster w/ private registry using authentication
* Rancher agents are not using images from the private registry
* Upgrade to v2.3.4-rc3
* Existing clusters are now using images from the private registry for all system workloads
* New clusters are using images from the private registry for all system workloads
* Editing a cluster to use a different registry updates the images for all workloads to be pulled from the new private registry
* Custom cluster run commands correctly have the private registry in the image name

**Azure Container Registry**
Currently, only authentication with the Azure Container Registry admin account allows for Rancher to be used with the Azure Container Registry. 

* Azure Container Registry has two types of authentication - Admin account & via Identities
  * Admin Account
    * https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account
    * The ACR can have an admin account enabled which provides a username and password to push and pull from the registry
    * A cluster can be successfully created when using this set of credentials in the private registry configuration
  * Authentication with identities
    * https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication-managed-identity
    * Authenticating with identities requires to first login with the Azure CLI: `az login`, and then to the container: `az acr login`, before pulling from the private registry
      * This login process does not utilize any credentials in the commands, meaning you cannot pass a set of credentials directly through
    * Provisioning through the node driver does not allow for this authentication process
    * When provisioning a custom cluster, the user can authenticate with the registry on the node to pull the initial Rancher agent image, but further pulls from RKE fail with an error: `[Failed to pull image [<registry-name>.azurecr.io/rancher/rke-tools:v0.1.51] on host [192.168.0.5]: Error response from daemon: Get https://<registry-name>.azurecr.io/v2/rancher/rke-tools/manifests/v0.1.51: unauthorized: authentication required]`

**Comment by bmdepesa** [comment]
rancher/rancher:master-head
rancher/rancher:v2.3.4-rc3

With further testing today: 
* Fresh installs of master/v2.3.4 get an authentication error when creating a new cluster using a private registry, when pulling images
* Upgrading from v2.3.3 -> v2.3.4 still pulls the rancher agents from the private registry after upgrading

**Comment by sowmyav27** [comment]
### Upgrade scenario

- On `2.3.3` Provision a cluster with private registry using authentication (cluster level)
- Rancher agents are not using images from the private registry
- Upgrade rancher to v2.4.0-alpha1
- Rancher agents are pulled from the private registry (cluster level)

### **On a fresh install of `rancher:v2.4.0-alpha1`**
- Provision a cluster with private registry using authentication (cluster level) and global level private registry - with no Authentication
- Agent image is pulled from the global level private registry - with no Authentication and also from private registry - cluster level (checked on the node, image is present)
- When the cluster comes up Active, the cluster agent and node agent images are seen pulled from the private registry using authentication (cluster level)

**Comment by jiaqiluo** [comment]
Upgrade scenario 2.3.3 to v2.3.4-rc8 in air-gapped env
- 

- run Rancher 2.3.3 single install 
- set the global registry to registry-1
- add a custom cluster and set the cluster-level registry to registry-2
- **Result**: the workloads under the namespace cattle-system use images from the global registry, all other workloads in other namespaces use images from the cluster-level registry
- upgrade Rancher to v2.3.4-rc8
- **Result**: the workloads under the namespace cattle-system are upgraded to use images from the cluster-level registry
- add a new cluster and  set the cluster-level registry to registry-2
- **Result**: all workloads in the System project use images from the global registry

**Comment by raphink** [comment]
We're still seeing this issue with Rancher 2.5.5. I'm not sure to understand why this issue was closed actually.

**Comment by sowmyav27** [comment]
@raphink Can you please let us know what is the exact issue you are facing and please give us details about the setup.

**Comment by raphink** [comment]
We're using Rancher 2.5.5 to setup up an RKE cluster on VSphere. All images are in a private registry, authenticated.

After the nodes start, docker fails to pull the rancher agent image from the private registry, even though the private registry has been properly set up in Rancher.

**Comment by bmdepesa** [comment]
@raphink how are you configuring the private registry settings in Rancher? Can you provide any error messages from logs/events with sensitive information redacted?

**Comment by raphink** [comment]
@bmdepesa We are configuring the private registry as global, then providing the user & pass when instantiating the cluster.

**Comment by bmdepesa** [comment]
@raphink please follow the directions for provisioning a cluster using a private registry from these documentation links:

https://rancher.com/docs/rancher/v2.0-v2.4/en/cluster-provisioning/rke-clusters/options/#private-registries
https://rancher.com/docs/rke/latest/en/config-options/private-registries/

**Comment by raphink** [comment]
@bmdepesa that's what we did. It does set up the base registry to pull the images, but not the authentication when pull the rancher-agent image.

**Comment by bmdepesa** [comment]
@raphink Your previous comment mentioned setting the private registry at the global settings. 

When provisioning the cluster you also set this at the cluster level? These are the same steps we use when testing airgapped cluster creation during our release testing and we have not seen this fail since the issue was closed. 

![Screen Shot 2021-03-08 at 10 14 07 AM](https://user-images.githubusercontent.com/21316915/110356098-250a1700-7ff7-11eb-866a-7921026446c9.png)

**Comment by raphink** [comment]
Yes, we did this.

The only way to pass the cluster creation was to remove authentication on the registry.

**Comment by bmdepesa** [comment]
@raphink 

Can you remove the global private registry configuration (which does not have authentication credentials provided) and attempt while only setting the private registry at the cluster level? 

Any logs or error statements you can provide from Rancher server or the downstream cluster nodes would be helpful in determining where this is failing as we have not been able to reproduce this.

**Comment by raphink** [comment]
If I understand properly...

1. the global private registry sets which registry to use to pull images
2. the cluster authentication settings allow to authenticate to that registry

so (again if I understand properly) if I remove the global registry configuration, I won't see any 403 on the registry anymore, but it'll still fail to pull the rancher-agent image, since the nodes have no access to the Internet.

**Comment by bmdepesa** [comment]
@raphink that understanding is not wholly correct

The cluster level private registry allows specifying the registry and the authentication credentials, but does not require the global default registry to be populated. Please see the following docs page for more details:
https://rancher.com/docs/rancher/v2.x/en/admin-settings/config-private-registry/

```
The global default registry is intended to be used for air-gapped setups, for registries that do not require credentials. The cluster-level private registry is intended to be used in all setups in which the private registry requires credentials.
```

I tested 2 scenarios in an airgapped environment with Rancher 2.5.5:

1. Global level and cluster level private registry information provided, and the cluster was able to pull images from the auth-enabled private registry allowing the cluster to be provisioned.
 
2. Only the cluster level private registry information provided, and the cluster was able to pull images from the auth-required private registry allowing the cluster to be provisioned. 

Both cases were verified by checking that the images used in the system workloads were indeed tagged from the auth-enabled private registry. 

At this point I am unable to reproduce the issue. If you can provide an actual error message or logs, I'm happy to look further and see what we can find.

**Comment by dabelenda** [comment]
@bmdepesa I take over @raphink to try and explain our issue exactly, because I am missing a critical piece of info here that makes the whole thing work together.

From our understanding (and what we've actually seen during the installation), the Global Registry setting tells Rancher where RKE needs to download the platform images during the deployment (like for example rancher-agent). It is the prefix of the images so for the "rancher-agent" image is we put "myregistry.example:5000/mirrored/rancher/images/"  it will download the rancher-agent image from the repository "myregistry.example.com:5000/mirrored/rancher/images/rancher-agent".

The private registry setting is to populate the docker authentication file so we did what we do for a private registry and used "myregistry.example.com:5000" as the registry name with username and password.

This did not work as expected. The rancher-agent image was pulled without authenticating on the private registry.

Now if we don't set the Global Registry setting, the rancher-agent image is not pulled from our private registry at all, if I remember correctly it is pulled from the standard docker.io/rancher/rancher-agent repository.

I don't understand what we missed in this setup.

**Comment by carlp101** [comment]
I am having the same issue with my 2.5.5 install. 

If I have the global system-default-registry in global settings set-up to point to a local harbor repo 'harbor.lab.int/rancher' that configured without authentication, my managed cluster builds without error. If I configure my harbor repo to require authentication and provide the private registry URL, username and password in my node template I get the same error others are reporting - "[ERROR] error syncing 'c-999xm/m-xzxjp: handler node-conroller: Unable to find image 'harbor.lab.int/rancher/rancher/rancher-agent:v2.5.5' locally. docker: Error response from daemon: unauthorized: unauthorized access to repository: rancher/rancher/rancher-agent, action: pull.

My container images are held in the 'rancher' project, hence the additional 'rancher' in the URL. I can confirm that the path in the error is the exact path displayed in harbor to access the image.

**Comment by carlp101** [comment]
I've just shown that the issue is that Rancher ignores the private repo configured in the RKE template.
