### ISSUE TITLE
Volume/Backup Support in Rancher

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2002]
- Add ability to manage volumes (create, delete, list)
- Add ability to start a container with created volumes
- Add ability to create volumes using Convoy
- Add ability to create and restore backups of volumes

**Comment by lavvy** [comment]
Is it from UI ?

**Comment by wlan0** [comment]
@lavvy This will have to be supported through the API first, which will be done first, then it will be supported through the UI.

**Comment by djcenox** [comment]
Is this still unscheduled or will be integrated in 1.x release?

**Comment by deniseschannon** [comment]
This exists today with our persistent storage services. 

http://rancher.com/docs/rancher/v1.6/en/rancher-services/storage-service/
