### ISSUE TITLE
Backport: "project-monitoring" app reports Users.management.cattle.io "user-xxxxx" not found error

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20024]
https://github.com/rancher/rancher/issues/19674

**Comment by alena1108** [comment]
can be tested with rc7

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: v2.2.3-rc7

Steps:
- as the admin user, enable the Github Auth
- log in as Github user1 to provision an ec2 cluster
- log in as a local user to provision a custom cluster 
- log in as the admin, deactivate those above two users
- as the admin, go to the default project in the ec2 cluster to enable project monitoring
- as the admin, go to the default project in the custom cluster to enable project monitoring

Result:
- the project monitoring is up
- no errors in Rancher's log
