### ISSUE TITLE
Failed to bring up Control Plane: Failed to verify healthcheck

### ISSUE THREAD

**Issue by GarbageYard** [rancher/rancher#20027]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** Set up 3 nodes (VMs) for running k8s cluster and 4th node for running RKE and kubectl commands. Then run `./rke up --config ./rancher-cluster.yml`

**Result:** `FATA[0514] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [10.150.16.55]: Get https://localhost:6443/healthz: EOF, log: I0507 07:05:51.188445       1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.`

**Other details that may be helpful:** Trying to set up k8s HA cluster using RKE. Earlier, i was facing [this](https://github.com/kubernetes/kubernetes/issues/77494) issue. Now i am stuck with the health check issue.

**Environment information**

Using RKE release v0.1.18

```
# kubectl get nodes
The connection to the server 10.150.16.56:6443 was refused - did you specify the right host or port?
``` 

All 4 VMs have same OS
```
cat /etc/*release

CentOS Linux release 7.6.1810 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core)
CentOS Linux release 7.6.1810 (Core))

```

```
# uname -a
Linux mybox 3.10.0-693.17.1.el7.x86_64 #1   SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

- Installation option (single install/HA): Trying HA install with 3 VMs for k8s and 4th one for kubectl and RKE.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): On-prem VMs
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs

```
# top
top - 13:09:26 up 51 min,  1 user,  load average: 0.53, 0.55, 0.50
Tasks: 126 total,   1 running, 125 sleeping,   0 stopped,   0 zombie
%Cpu0  :  8.4 us,  1.3 sy,  0.0 ni, 89.9 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu1  : 10.2 us,  1.4 sy,  0.0 ni, 87.5 id,  0.0 wa,  0.0 hi,  1.0 si,  0.0 st
%Cpu2  :  8.1 us,  1.4 sy,  0.0 ni, 90.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  9.4 us,  1.7 sy,  0.0 ni, 88.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16266748 total, 13782844 free,   368796 used,  2115108 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 15449600 avail Mem
```

```
# free -g
              total        used        free      shared  buff/cache   available
Mem:             15           0          13           0           2          14
Swap:             0           0           0

```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: net/http: TLS handshake timeout
```

- Docker version (use `docker version`): Docker version on all 4 nodes:

```
docker version

Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Before posting this, i also checked similar issues here and i tried deleting nodes twice using the following commands but to no avail:

```
docker rm -f $(docker ps -qa) && docker rmi -f $(docker images -q) && docker volume rm $(docker volume ls -q) && rm -rf /etc/ceph \
       /etc/cni \
       /etc/kubernetes \
       /opt/cni \
       /opt/rke \
       /run/secrets/kubernetes.io \
       /run/calico \
       /run/flannel \
       /var/lib/calico \
       /var/lib/etcd \
       /var/lib/cni \
       /var/lib/kubelet \
       /var/lib/rancher/rke/log \
       /var/log/containers \
       /var/log/pods \
       /var/run/calico
```

Also, on the node (10.150.16.55) where health check is failing, output of `docker ps -a` is as stated under:

```
# docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                      PORTS               NAMES
ec79035243f7        rancher/hyperkube:v1.13.5-rancher1   "/opt/rke-tools/entr…"   33 minutes ago      Up 7 seconds                                    kube-apiserver
581e749a1a1e        rancher/rke-tools:v0.1.16            "/bin/bash"              33 minutes ago      Created                                         service-sidekick
c985098e8904        rancher/rke-tools:v0.1.16            "/opt/rke-tools/rke-…"   33 minutes ago      Up 33 minutes                                   etcd-rolling-snapshots
5cd6f57377e8        rancher/coreos-etcd:v3.2.24          "/usr/local/bin/etcd…"   33 minutes ago      Up 33 minutes                                   etcd
e10c8b1611e3        rancher/rke-tools:v0.1.16            "/bin/bash"              37 minutes ago      Exited (0) 37 minutes ago                       cert-fetcher
467c3d23d4b1        rancher/rke-tools:v0.1.16            "/bin/bash"              37 minutes ago      Exited (0) 37 minutes ago                       cluster-state-deployer

```

`kube-apiserver` container on this instance is restarting continuously.

Any help will be appreciated.

**Comment by GarbageYard** [comment]
When i checked the kube-apiserver logs, i see the following error:

```F0507 08:24:06.420707       1 storage_decorator.go:57] Unable to create storage backend: config (&{etcd3 /registry [https://10.150.16.54:2379 https://10.150.16.55:2379 https://10.150.16.56:2379] /etc/kubernetes/ssl/kube-node-key.pem /etc/kubernetes/ssl/kube-node.pem /etc/kubernetes/ssl/kube-ca.pem true 0xc000beccf0 <nil> 5m0s 1m0s}), err (context deadline exceeded)```

Then i checked the etcd logs and it's filled with these messages:
```
2019-05-07 08:32:25.934818 I | etcdmain: rejected connection from "10.150.16.55:43334" (error "remote error: tls: bad certificate", ServerName "")
2019-05-07 08:32:25.976974 I | etcdmain: rejected connection from "10.150.16.54:47536" (error "remote error: tls: bad certificate", ServerName "")
2019-05-07 08:32:25.985286 I | etcdmain: rejected connection from "10.150.16.55:43338" (error "remote error: tls: bad certificate", ServerName "")
2019-05-07 08:32:26.017834 I | etcdmain: rejected connection from "10.150.16.54:47538" (error "remote error: tls: bad certificate", ServerName "")
```

**Comment by GarbageYard** [comment]
In one of the [certificate related link](https://www.reddit.com/r/kubernetes/comments/9kxssd/x509_certificate_has_expired_or_is_not_yet_valid/), i noticed that time could be an issue. So when i checked the time on the server where i was running RKE and kubectl, i noticed that it's time was different from other 3 nodes (controlplane,etcd,worker). 

Another thing was that though i cleaned up all three nodes, i did not clean up RKE/kubectl `/etc/kubernetes` directory. Not sure whether cleanup of `/etc/kubernetes` directory on the server having RKE/kubectl was necessary. _Can anyone kindly confirm this_?

After i performed the above two steps, i was successfully able to run `./rke up --config ./rancher-cluster.yml` command.

**Comment by superseb** [comment]
Cleaning up nodes is described on https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/#cleaning-a-node-manually and exploring date/time differences is tracked in https://github.com/rancher/rke/issues/1123
