### ISSUE TITLE
Backport: Prometheus Operator needs higher/configurable memory limit

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20022]
https://github.com/rancher/rancher/issues/19693

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc7

This change resulted in a new addition to the cluster monitoring page. A new field for "Prometheus Operator Memory Limit" was added and the default value is 500 MiB
UI issue is it sending too many requests to backend.
![image](https://user-images.githubusercontent.com/45179589/57336932-80f27480-70dc-11e9-9c94-584a4758bcd2.png)

If you inspect the Security & Host config of the prometheus operator workload you will see the setting will take effect including when you edit and save changes to monitoring settings for the cluster.
![image](https://user-images.githubusercontent.com/45179589/57336968-9f587000-70dc-11e9-9371-ef69e9b111ca.png)

Additionally, the JavaScript check to ensure you have enough memory on the cluster was updated as well and appears to be working (operatorLimitsMemory)

**Comment by loganhz** [comment]
Version 2.2.4-rc5

Prometheus Operator memory limit doesn't work in rc5.
It is a regression issue when we merged the PR for refactor monitoring

**Comment by alena1108** [comment]
good catch @loganhz

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc6`

**Comment by davidnuzik** [comment]
My apologies for not catching this. I am typically very careful when I test and my testing includes checking non-default and unexpected values for fields (fuzzing data, unexpected data types, etc). It is not okay that this was not checked earlier and I will try to be more careful going forward.

Version: v2.2.4-rc6

This change adds a new option to cluster monitoring "Prometheus Operator Memory Limit" with a default value of 500 MiB
![image](https://user-images.githubusercontent.com/45179589/58057483-d9ccfe80-7b19-11e9-9359-0214380965a8.png)

This field was validated and is answer `operator.resources.limits.memory` upon enabling / updating monitoring.

I validated the new option by setting a non-default value such as 411 as seen below.
![image](https://user-images.githubusercontent.com/45179589/58057553-24e71180-7b1a-11e9-91e4-e92fe740cc7b.png)

http:
`operator.resources.limits.memory: "411Mi"`

Security & Host config of the workload:
![image](https://user-images.githubusercontent.com/45179589/58057545-1a2c7c80-7b1a-11e9-9e3f-6ef3a85e1057.png)

Non-numerical values cannot be entered into the field -- the UI prevents it.
You can supply arbitrarily long lengths of numbers but there are limits with k8s or the UI.
I can supply an extremely long length number and it will not be greater than 8796093022208 MiB
![image](https://user-images.githubusercontent.com/45179589/58057669-9030e380-7b1a-11e9-9a70-432b42f323f0.png)

Negative numbers can be supplied but are submitted as "4Mi" value which is the minimum. This value does not actually make changes to the workload. I will open another issue if necessary around this.
