### ISSUE TITLE
Remove windows options in 2.2.3 and 2.1.10 branch

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20025]
Old windows feature in 2.1 and 2.2 is deprecated. Please try new Windows feature in 2.3.0 preview/alpha.

**Comment by davidnuzik** [comment]
I can confirm removal of the Windows Support option for custom cluster in v2.2.3-rc7. This looks good in the UI. Notice "Flannel" network provider has the Windows Support removed from the name which is good.

There is no current 2.1.10 so I cannot test there. FWIW I reviewed the code changes and it looks good.
