### ISSUE TITLE
Backport: Can't login with Rancher CLI in Rancher 2.2.x when API key is cluster scoped 

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20031]
Backport of rancher/rancher#18639

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc9

This change makes it more clear in the UI via %editApiKey.scopeSelect.helpText% what cluster-scoped tokens can and cannot do.

![image](https://user-images.githubusercontent.com/45179589/57575291-8d3c4180-73fc-11e9-8e89-3d9c55ac91f4.png)

This helper text also links directly to documentation for Authorized Cluster Endpoint via https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#authorized-cluster-endpoint
