### ISSUE TITLE
Pipelines using Bitbucket not detecting .rancher-pipeline.yml in branches other than master

### ISSUE THREAD

**Issue by fdalm** [rancher/rancher#20030]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- add new pipeline on Rancher UI;
- add Bitbucket Cloud repository (private);
- associate credentials;
- enable repository;
- run build or edit config.

**Result:**
Though all branches contain a .rancher-pipeline.yml file, it is only detected in the master branch.
Upon selecting "Run", only that branch is visible and able to be processed. Upon selecting "Edit config", all branches are visible however only master is enabled.

Editing the yaml for any branch other than master triggers a commit with the updated .rancher-pipeline.yml but it keeps not being detected by Rancher.

Pushing a commit doesn't trigger any action despite Bitbucket logs showing a 200 response status code.

Maybe related to issue [#15270.](https://github.com/rancher/rancher/issues/15270)

Rancher:  v2.2.2
UI:  v2.2.41
Helm:  v2.10.0-rancher10
Machine:  v0.15.0-rancher6-1

**Cluster information**
- single node install, deployed on AWS
- "kernelVersion": "4.15.0-1037-aws",
- "osImage": "Ubuntu 18.04.2 LTS",
- "containerRuntimeVersion": "docker://18.9.6",
- "kubeletVersion": "v1.13.5",
- "kubeProxyVersion": "v1.13.5",
- "operatingSystem": "linux",
- "architecture": "amd64"

**Comment by gitlawr** [comment]
Unable to reproduce the issue yet. Can you share the pipeline file(trim any info you don't want to show)? I would like to check if there's any branch condition set in the spec.

**Comment by gitlawr** [comment]
We also set `Cache-control: no-cache` header requesting Bitbucket Cloud APIs, is it possible that it gets modified/dropped by a proxy server?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
