### ISSUE TITLE
[BUG] Rancher cli kubectl defaults to "Default" project.

### ISSUE THREAD

**Issue by gabrielcalderon** [rancher/rancher#20043]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
* Create a custom project other than Default/System. For ex: "lab"
* Run the following:

```
rancher login
rancher context switch lab
rancher kubectl create -f install.yaml
```

**Result:**
* Workloads get deployed to Default/default. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0
- Installation option (single install/HA): Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal
- Kubernetes version (use `kubectl version`): Latest supported
- Docker version (use `docker version`): Latest stable
- Rancher version: 2.2.0

**Other bugs and issues with Rancher CLI:**
* I'm trying to automate deployments and management of resources through Rancher CLI and it's been impossible. 

* It's a pain to handle projects using the CLI, there's no way to specify a project using the name, it requires the unique ID which makes automation a pain. 

* Running: rancher kubectl create -f namespace.yml results in the namespace not having a Project attached. 

Summary of problems:
* Provide --context flag for: rancher kubectl
* Provide ability of specifying project by Name instead of the weird unique id's.
* Provide way of having a default project where EVERYWHERE gets installed to if no project is specify.
* Provide way to run: rancher login --context ProjNameHere instead of unique id.

**Comment by dramich** [comment]
@gabrielcalderon `rancher kubectl` is a direct passthrough to `kubectl` using the required kubeconfig to access the cluster. We don't do any extra processing around those commands so if you want things to install to a specific namespace that would need to be in the install.yaml or kubectl will use it's default. A project is a collection of namespaces so specify the namespace for things and they will end up under the associated project. 

When creating a namespace it does need to be associated with a project, this can be automated using the cli through `rancher namespace move` which does accept a project name or ID. 

Almost all commands will use the project name if passed in, but if there are duplicates the command will fail. `login` is the exception to this but could be updated to use a name as well.

**Comment by gabrielcalderon** [comment]
@dramich Thanks for the explanation, I will make the necessary changes on my deployments to support this.

Note: I think this kind of stuff should be added to the documentation for Rancher CLI. Maybe also include an examples sections with different commands and how they related to Rancher usage, Rancher+Kubectl usage.
