### ISSUE TITLE
Add more driver info to telemetry

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#20040]
Add fields for what node & kontainer drivers are enabled, what auth providers are in use, and if there's is a cluster marked internal (which sorta but not entirely means HA install).

```
"install": {
  ...
  "auth": {
    "local": 1
  },
  "kontainerDriverCount": 5,
  "kontainerDrivers": {
    "amazonElasticContainerService": 1,
    "azureKubernetesService": 1,
    "googleKubernetesEngine": 1,
    "huawei": 1,
    "rancherKubernetesEngine": 1
  },
  "nodeDriverCount": 5,
  "nodeDrivers": {
    "aliyunecs": 1,
    "amazonec2": 1,
    "azure": 1,
    "digitalocean": 1,
    "vmwarevsphere": 1
  },
  "hasInternal": true
},
```

(The counts are pretty much redundant because each driver will always have one, but the telemetry API doesn't have an easy way to sum up the drivers to see get an idea how many drivers the typical install has on so this makes it easier)

https://github.com/rancher/telemetry/pull/20

**Comment by bmdepesa** [comment]
rancher/rancher:master 8e04837c

* Enabled telemetry
* Created cluster
* Viewed the new fields in telemetry data
* Deactivated some node/kontainer drivers
* Viewed updated data
