### ISSUE TITLE
Backport: Add logging system chart v0.0.2 to use `rancher/jimmidyson-configmap-reload:v0.2.2`

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#20046]
Backport: https://github.com/rancher/rancher/issues/19836

**Comment by loganhz** [comment]
will be available in rc8

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.3-rc8

* Enabled cluster logging
* Image used is `jimmidyson/configmap-reload:v0.2.2`
