### ISSUE TITLE
UI - Not able to edit cluster with cloud provider settings that have credentials.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#20044]
Rancher server version - v2.2.3-rc7

1. Create a Azure cluster with cloud provider.
2. Once the cluster gets to "active" state , try to edit the cluster. On edit page, user is not presented with the "aadClientSecret" parameter anymore.
3. Edit cluster ( In my case I disabled recurring snapshots) and "Save". Following error message is presented to the user.
<img width="1361" alt="Screen Shot 2019-05-07 at 7 31 28 PM" src="https://user-images.githubusercontent.com/4266958/57345432-a6dd4080-70ff-11e9-8a0f-1087680b4b4d.png">

The same issue is also seen when using "Edit as yaml" to change any setting and save.

**Comment by mrajashree** [comment]
@westlywright @sangeethah the following fields are made type=password now
`VsphereCloudProvider .GlobalVsphereOpts.Password`, `VsphereCloudProvider.VirtualCenterConfig.Password`, `OpenstackCloudProvider .GlobalOpenstackOpts.Password`,`AzureCloudProvider. AADClientSecret` and `AzureCloudProvider. AADClientCertPassword`
From this I think the Azure fields are shown in UI but rest aren't shown as separate fields.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/31/19)

I am now able to edit an Azure RKE cluster with Azure cloud option without supplying the aadClientSecret (this is what was preventing edits before).
