### ISSUE TITLE
Backport: Monitoring - Cluster Metrics is reporting only 1 out of 3 nodes

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20041]
Backport: https://github.com/rancher/rancher/issues/19187

**Comment by alena1108** [comment]
Can be tested in rc7

**Comment by loganhz** [comment]
Fixed in Azure. Still need to merge the PR for AWS. So we can not test it now

**Comment by loganhz** [comment]
will be in rc9

**Comment by loganhz** [comment]
in rc9

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: v2.2.4-rc1

Steps:
- run Rancher:  v2.2.4-rc1 container single install
- add an RKE ec2 cluster with 5 nodes (1 etcd, 1 control plane, 3 workers)
- enable cluster monitoring

Results:
- cluster metrics show all 5 nodes
<img width="722" alt="Screen Shot 2019-05-14 at 10 28 11 AM" src="https://user-images.githubusercontent.com/6218999/57718782-0f15b000-7633-11e9-9ec5-7c681b1dd55b.png">

- Prometheus shows all targets healthy  

- each node's `node metrics` have graphs.
