### ISSUE TITLE
Unable to install rancher using helm: no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by GarbageYard** [rancher/rancher#20049]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1) Install Nginx 1.15 for TLS termination
2) Try installing rancher stable version [using helm](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/)

**Result:**
```
# helm install rancher-stable/rancher \
>   --name rancher \
>   --namespace cattle-system \
>   --set hostname=rancher.abc.com
Error: validation failed: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Trying to install rancher-stable/rancher
- Installation option (single install/HA): HA install with Nginx 1.15 as LB and for TLS termination

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): On-prem VM
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
# helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

```

- Docker version (use `docker version`):

```
docker version

Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Documentation mentions that i do not need to install cert-manager if i am using external load balancer for TLS termination. Since there was no separate `helm` command mentioned for such scenario, i used the one mentioned at the top of this post for installing rancher stable version.

**Comment by superseb** [comment]
External TLS termination requires `--set tls=external` to be used in the `helm install` command as described on https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#external-tls-termination.

Let me know if that doesn't solve the issue.
