### ISSUE TITLE
Rancher UI opening too slowly

### ISSUE THREAD

**Issue by GarbageYard** [rancher/rancher#20052]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** Installed Rancher v2.2.2 using Helm as described in [documentation](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/)

**Result:** UI is too slow. Clicking on any link in UI _easily takes more than a minute_ to open.

**Other details that may be helpful:** Also checked etcd. It has some messages related to latency

`etcdserver: read-only range request "key:\"/registry/configmaps/kube-system/cattle-controllers\" " with result "range_response_count:1 size:413" took too long (161.08599ms) to execute`

Complete log attached here:  [etcd.log](https://github.com/rancher/rancher/files/3156966/etcd.log)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v2.2.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): On-prem VM
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4 core, 16 GB (All 3 nodes have same configuration)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by cjellick** [comment]
For the cluster that is slow, do you have a very large number of any partciular resource? Possibly configMaps?
Whats the output of these commands?
```
kubectl get configmaps --all-namespaces | wc -l
kubectl get pods --all-namespaces | wc -l
```

**Comment by GarbageYard** [comment]
This is a brand new cluster and i have not installed any application.

```
# kubectl get configmaps --all-namespaces | wc -l
16
```

```
# kubectl get configmaps --all-namespaces
NAMESPACE       NAME                                 DATA   AGE
cattle-system   admincreated                         0      9h
ingress-nginx   ingress-controller-leader-nginx      0      31h
ingress-nginx   nginx-configuration                  0      31h
ingress-nginx   tcp-services                         0      31h
ingress-nginx   udp-services                         0      31h
kube-system     canal-config                         4      31h
kube-system     cattle-controllers                   0      9h
kube-system     cluster-state                        1      31h
kube-system     extension-apiserver-authentication   6      31h
kube-system     kube-dns-autoscaler                  1      31h
kube-system     rancher.v1                           1      9h
kube-system     rke-ingress-controller               1      31h
kube-system     rke-kubedns-addon                    1      31h
kube-system     rke-metrics-addon                    1      31h
kube-system     rke-network-plugin                   1      31h
```

```
# kubectl get pods --all-namespaces | wc -l
23
```

```
# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY   STATUS             RESTARTS   AGE
cattle-system   cattle-cluster-agent-68795c6685-drqh2     0/1     CrashLoopBackOff   101        8h
cattle-system   cattle-node-agent-7wdd7                   0/1     CrashLoopBackOff   43         8h
cattle-system   cattle-node-agent-mqcqn                   0/1     CrashLoopBackOff   101        8h
cattle-system   cattle-node-agent-nrxzw                   0/1     CrashLoopBackOff   101        8h
cattle-system   rancher-6679788569-4vxzk                  1/1     Running            1          9h
cattle-system   rancher-6679788569-6zjsf                  1/1     Running            0          9h
cattle-system   rancher-6679788569-ws8wf                  1/1     Running            1          9h
ingress-nginx   default-http-backend-7f8fbb85db-q4lnr     1/1     Running            0          31h
ingress-nginx   nginx-ingress-controller-j6vdc            1/1     Running            0          31h
ingress-nginx   nginx-ingress-controller-rx6ss            1/1     Running            0          31h
ingress-nginx   nginx-ingress-controller-scwd9            1/1     Running            0          31h
kube-system     canal-g42gn                               2/2     Running            0          31h
kube-system     canal-qgglh                               2/2     Running            0          31h
kube-system     canal-wggc5                               2/2     Running            0          31h
kube-system     kube-dns-5fd74c7488-tq69j                 3/3     Running            0          31h
kube-system     kube-dns-autoscaler-c89df977f-dgdf7       1/1     Running            0          31h
kube-system     metrics-server-7fbd549b78-5rzzd           1/1     Running            0          31h
kube-system     rke-ingress-controller-deploy-job-m9t9s   0/1     Completed          0          31h
kube-system     rke-kubedns-addon-deploy-job-dfv7n        0/1     Completed          0          31h
kube-system     rke-metrics-addon-deploy-job-95kkz        0/1     Completed          0          31h
kube-system     rke-network-plugin-deploy-job-c62lk       0/1     Completed          0          31h
kube-system     tiller-deploy-5f4fc5bcc6-r28k9            1/1     Running            0          29h
```

I checked the crashing pod. Here's what i get:

```
# kubectl logs -p cattle-cluster-agent-68795c6685-drqh2 -n cattle-system
INFO: Environment: CATTLE_ADDRESS=10.42.2.3 CATTLE_CA_CHECKSUM=e4b2490847af6536ee580e8b346749825d24c4df6a41ada3640e5170f983173f CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-68795c6685-drqh2 CATTLE_SERVER=https://rancher.abc.com
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local abc.com options ndots:5
ERROR: https://rancher.abc.com/ping is not accessible (Could not resolve host: rancher.abc.com)
```

Seems many people have faced this issue and @superseb has [responded with the comment](https://github.com/rancher/rancher/issues/17105#issuecomment-447277445):
_Rancher installs require a resolvable DNS name, not via a workaround in /etc/hosts_

I also have set up `/etc/hosts` file. Not sure how do i implement what @superseb is suggesting. Any help?

**Comment by GarbageYard** [comment]
I was finally able to get the DNS issue resolved but still i am seeing CrashLoopBackOff for pods. Now when i check the pod log, i see the following message:

```
# kubectl -n cattle-system logs -p cattle-cluster-agent-68795c6685-gzdrr
INFO: Environment: CATTLE_ADDRESS=10.42.2.4 CATTLE_CA_CHECKSUM=e4b2490847af6536ee580e8b346749825d24c4df6a41ada3640e5170f983173f CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-68795c6685-gzdrr CATTLE_SERVER=https://rancher.abc.com
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local abc.com options ndots:5
ERROR: https://rancher.abc.com/ping is not accessible (The requested URL returned error: 404)
```

**Comment by GarbageYard** [comment]
Based on the [troubleshooting doc](https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/troubleshooting/404-default-backend/), i checked few things:

```
# kubectl --kubeconfig rke/kube_config_rancher-cluster.yml get ingress -n cattle-system -o wide
NAME      HOSTS                 ADDRESS                                  PORTS   AGE
rancher   rancher.abc.com   10.150.16.54,10.150.16.55,10.150.16.56   80      31h
```

```
# cat .kube/config
apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    certificate-authority-data: *******************
    server: "https://10.150.16.54:6443"
  name: "local"
contexts:
- context:
    cluster: "local"
    user: "kube-admin-local"
  name: "local"
current-context: "local"
users:
- name: "kube-admin-local"
  user:
    client-certificate-data: *******************
    client-key-data: *******************
```

If i go by the documentation, the `server` entry in `config` file should contain `https://rancher.abc.com:6443`. I don't get this because `config` file (actually file `kube_config_rancher-cluster.yml` was copied to ~/.kube/ as `config`) was automatically generated when i ran the command `./rke up --config ./rancher-cluster.yml` command.

 
```
# cat rke/rancher-cluster.yml
nodes:
  - address: 10.150.16.54
    internal_address: 10.150.16.54
    user: rke
    role: [controlplane,worker,etcd]
    ssh_key_path: ./id_rsa
  - address: 10.150.16.55
    internal_address: 10.150.16.55
    user: rke
    role: [controlplane,worker,etcd]
    ssh_key_path: ./id_rsa
  - address: 10.150.16.56
    internal_address: 10.150.16.56
    user: rke
    role: [controlplane,worker,etcd]
    ssh_key_path: ./id_rsa

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```

**Comment by Hwting** [comment]
Since we are adding the mapping through the hosts file, we need to add the host alias (/etc/hosts) for the Agent Pod
`kubectl -n cattle-system patch  deployments cattle-cluster-agent --patch '{
    "spec": {
        "template": {
            "spec": {
                "hostAliases": [
                    {
                        "hostnames":
                        [
                            "rancher.abc.com"
                        ],
                            "ip": "racnherserver-url"
                    }
                ]
            }
        }
    }
}'
kubectl -n cattle-system patch  daemonsets cattle-node-agent --patch '{
    "spec": {
        "template": {
            "spec": {
                "hostAliases": [
                    {
                        "hostnames":
                        [
                            "rancher.abc.com"
                        ],
                            "ip": "rancher server-url"
                    }
                ]
            }
        }
    }
}'`
[https://www.cnrancher.com/docs/rancher/v2.x/cn/installation/ha-install/helm-rancher/tcp-l4/rancher-install/?query=kubectl%20-n%20cattle-system%20patch%20%20deployments%20](url)

**Comment by GarbageYard** [comment]
Thanks @Hwting but I am no more using `/etc/hosts` mapping as i mentioned [here](https://github.com/rancher/rancher/issues/20052#issuecomment-490875837). I have removed entries for `rancher.abc.com` from `/etc/hosts` file on all the three nodes. If i try to ping `rancher.abc.com` from any of the three nodes, it works fine but i am now getting error as mentioned in my last post i.e., `default backend - 404`. Any idea how can i fix this issue now?

**Comment by GarbageYard** [comment]
I was reading your comment again. Hopefully, i have not misunderstood your comment and it seems your suggestion is based on the assumption that i am _still_ using `/etc/hosts` workaround which is not the case anymore.

Still, if i just go through the code that you've provided, i see that for
1) `cattle-cluster-agent`, you've mentioned `"ip": "racnherserver-url"`
2) `cattle-node-agent`, you've mentioned `"ip": "rancher server-url"`.

For `"ip"`, shouldn't some IP be used instead of URL? Also, since i have a 3 node (10.150.16.54, 10.150.16.55 and 10.150.16.56) set up, what should i use in those two blocks (`cattle-cluster-agent` and `cattle-node-agent`) that you've mentioned?

**Comment by Hwting** [comment]
> I was reading your comment again. Hopefully, i have not misunderstood your comment and it seems your suggestion is based on the assumption that i am _still_ using `/etc/hosts` workaround which is not the case anymore.
> 
> Still, if i just go through the code that you've provided, i see that for
> 
> 1. `cattle-cluster-agent`, you've mentioned `"ip": "racnherserver-url"`
> 2. `cattle-node-agent`, you've mentioned `"ip": "rancher server-url"`.
> 
> For `"ip"`, shouldn't some IP be used instead of URL? Also, since i have a 3 node (10.150.16.54, 10.150.16.55 and 10.150.16.56) set up, what should i use in those two blocks (`cattle-cluster-agent` and `cattle-node-agent`) that you've mentioned?

This address is rancher server address. If you are HA, that's LB.If you have an internal NDS, you don't need to configure hosts  Check ingress
```kubectl  get ingress   -n cattle-system```
[consult](https://www.cnrancher.com/docs/rancher/v2.x/cn/installation/ha-install/helm-rancher/tcp-l4/rancher-install/?query=kubectl%20-n%20cattle-system%20%EF%BC%8520patch%EF%BC%8520%EF%BC%8520deployments%EF%BC%8520)

**Comment by GarbageYard** [comment]
Thanks @Hwting! I have Rancher HA installed with Nginx (running as container) as LB and also for TLS termination.

```
kubectl -n cattle-system patch  deployments cattle-cluster-agent --patch '{
    "spec": {
        "template": {
            "spec": {
                "hostAliases": [
                    {
                        "hostnames":
                        [
                            "rancher.abc.com"
                        ],
                            "ip": "10.150.16.53"
                    }
                ]
            }
        }
    }
}'


kubectl -n cattle-system patch  daemonsets cattle-node-agent --patch '{
    "spec": {
        "template": {
            "spec": {
                "hostAliases": [
                    {
                        "hostnames":
                        [
                            "rancher.abc.com"
                        ],
                            "ip": "10.150.16.53"
                    }
                ]
            }
        }
    }
}'

```

After running them, `CrashLoopBackOff` issues finally went away. :) However, on hitting the URL, i am still getting `default backend - 404`. On checking `cattle-cluster-agent` pod log, i see the following message: `level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"`. I have used Helm to install Rancher.

Used this command while installing rancher: `helm install rancher-stable/rancher   --name rancher   --namespace cattle-system   --set hostname=rancher.abc.com --set tls=external`

Installed Nginx using: `docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   -v /etc/nginx.conf:/etc/nginx/nginx.conf   -v /etc/nginx/ssl:/etc/nginx/ssl   nginx:1.14`

**Comment by Hwting** [comment]
> Thanks @Hwting! I have Rancher HA installed with Nginx (running as container) as LB and also for TLS termination.
> 
> ```
> kubectl -n cattle-system patch  deployments cattle-cluster-agent --patch '{
>     "spec": {
>         "template": {
>             "spec": {
>                 "hostAliases": [
>                     {
>                         "hostnames":
>                         [
>                             "rancher.abc.com"
>                         ],
>                             "ip": "10.150.16.53"
>                     }
>                 ]
>             }
>         }
>     }
> }'
> 
> 
> kubectl -n cattle-system patch  daemonsets cattle-node-agent --patch '{
>     "spec": {
>         "template": {
>             "spec": {
>                 "hostAliases": [
>                     {
>                         "hostnames":
>                         [
>                             "rancher.abc.com"
>                         ],
>                             "ip": "10.150.16.53"
>                     }
>                 ]
>             }
>         }
>     }
> }'
> ```
> 
> After running them, `CrashLoopBackOff` issues finally went away. :) However, on hitting the URL, i am still getting `default backend - 404`. On checking `cattle-cluster-agent` pod log, i see the following message: `level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"`. I have used Helm to install Rancher.
> 
> Used this command while installing rancher: `helm install rancher-stable/rancher --name rancher --namespace cattle-system --set hostname=rancher.abc.com --set tls=external`
> 
> Installed Nginx using: `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /etc/nginx.conf:/etc/nginx/nginx.conf -v /etc/nginx/ssl:/etc/nginx/ssl nginx:1.14`
> 
> Was just going through the [troubleshooting docs](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/troubleshooting/) and noticed that my browser is displaying: `Kubernetes Ingress Controller Fake Certificate`
1、error="x509
Check to see if your host time is synchronized with the NTP server
2、default backend - 404
kubectl get ingress -n cattle-system information

**Comment by GarbageYard** [comment]
There is definitely some issue with time sync on all the nodes (VMs). Somehow NTP sync is not working. Looking into it.

Regarding the second command,
```
# kubectl get ingress -n cattle-system information
Error from server (NotFound): ingresses.extensions "information" not found
```

**Comment by Hwting** [comment]
> There is definitely some issue with time sync on all the nodes (VMs). Somehow NTP sync is not working. Looking into it.
> 
> Regarding the second command,
> 
> ```
> # kubectl get ingress -n cattle-system information
> Error from server (NotFound): ingresses.extensions "information" not found
> ```
Sync NTP time yourself
```kubectl get ingress -n cattle-system```

**Comment by GarbageYard** [comment]
```
# kubectl get ingress -n cattle-system
NAME      HOSTS                 ADDRESS                              PORTS   AGE
rancher   rancher.abc.com   10.150.16.54,10.150.16.55,10.150.16.56   80      5d2h
```

**Comment by GarbageYard** [comment]
@Hwting : All the nodes are in sync now but the issue still persists. Do i need to restart something?

**Comment by GarbageYard** [comment]
I looked online for more clues. Came across @superseb [tool](https://github.com/superseb/rancher-check)

```
# ./rancher-check.sh https://rancher.abc.com
OK: DNS for rancher.abc.com is 10.150.16.54
10.150.16.55
10.150.16.56
OK: Response from https://rancher.abc.com/ping is pong
INFO: CA checksum from https://rancher.abc.com/v3/settings/cacerts is e4b2490847af6536ee580e8b346749825d24c4df6a41ada3640e5170f983173f
ERR: Certificate chain is not complete
INFO: Found CN rancher.abc.com
INFO: Found Subject Alternative Name(s) (SANs): rancher.abc.com
OK: rancher.abc.com was found in SANs (rancher.abc.com)
Trying to get intermediates to complete chain and writing to /certs/fullchain.pem
Note: this usually only works when using certificates signed by a recognized Certificate Authority
./rancher-check.sh: line 96: cert-chain-resolver: command not found
Showing openssl s_client output
CONNECTED(00000003)
depth=0 CN = rancher.abc.com
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = rancher.abc.com
verify return:1
---
Certificate chain
 0 s:/CN=rancher.abc.com
   i:/CN=rancher.abc.com
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIC4TCCAcmgAwIBAgIJAMM2nr+V7NTMMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV
.....
.....
gefbAneh5viCZ7DD5TqeZnnY2evMRrAEjUw3lfJ8nNf2qqbWInujOollbQ2cIqev
t7aizNKoYeL7/qho/AYCbtsl6Iks
-----END CERTIFICATE-----
subject=/CN=rancher.abc.com
issuer=/CN=rancher.abc.com
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1427 bytes and written 443 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: E8EC8032D34EEF75171DA253923B08066EB9046494EF359794A7D78750E78525
    Session-ID-ctx:
    Master-Key: 471ADE944F32B07DAEB51C37430274D9246B7E443D61E89DD340844F2847D7A2406085AAE0CACA0E7D4240F1B9396D59
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - d2 a9 72 bc 14 19 d8 fd-28 c6 35 da 3b 44 b2 7e   ..r.....(.5.;D.~
    ...
	...
    00b0 - 71 14 7c 03 79 80 f2 f0-69 c7 ee 50 7c f2 d3 b9   q.|.y...i..P|...

    Start Time: 1557814449
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
DONE
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            c3:36:9e:bf:95:ec:d4:cc
        Issuer: CN=rancher.abc.com
        Validity
            Not Before: May 14 06:12:01 2019 GMT
            Not After : May 11 06:12:01 2029 GMT
        Subject: CN=rancher.abc.com
```

Any idea how i can fix this?

**Comment by drpebcak** [comment]
@GarbageYard try running it from docker. Looks like you don't have the `cert-chain-resolver` utility installed.

`docker run superseb/rancher-check https://rancher.abc.com`

**Comment by GarbageYard** [comment]
Tried but i get this:

```
# docker run superseb/rancher-check https://rancher.abc.com
OK: DNS for rancher.abc.com is 10.150.16.54
10.150.16.55
10.150.16.56
ERR: Response from https://rancher.abc.com/ping is not pong:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0    617      0 --:--:-- --:--:-- --:--:--   617
HTTP/1.1 404 Not Found
Server: nginx/1.15.6
Date: Wed, 15 May 2019 06:34:23 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains

default backend - 404
```

**Comment by GarbageYard** [comment]
I feel the main issue seems related to incomplete chain as shown in the error below:

```
# ./rancher-check.sh https://rancher.abc.com
OK: DNS for rancher.abc.com is 10.150.16.55
10.150.16.56
10.150.16.54
OK: Response from https://rancher.abc.com/ping is pong
INFO: CA checksum from https://rancher.abc.com/v3/settings/cacerts is e4b2490847af6536ee580e8b346749825d24c4df6a41ada3640e5170f983173f
ERR: Certificate chain is not complete
INFO: Found CN rancher.abc.com
INFO: Found Subject Alternative Name(s) (SANs): rancher.abc.com www.rancher.abc.com
OK: rancher.abc.com was found in SANs (rancher.abc.com www.rancher.abc.com)
Trying to get intermediates to complete chain and writing to /certs/fullchain.pem
Note: this usually only works when using certificates signed by a recognized Certificate Authority
./rancher-check.sh: line 96: cert-chain-resolver: command not found
```

I saw several links but not sure how to fix this. [One of the link](https://medium.com/@superseb/get-your-certificate-chain-right-4b117a9c0fce) is by @superseb  only. The issue is, in case of self-signed certificate, how do i fix it.

```
# openssl verify nginx.crt
nginx.crt: C = IN, ST = HY, L = GG, O = ABC Corp., OU = IT Department, emailAddress = it@rancher.abc.com, CN = rancher.abc.com
error 20 at 0 depth lookup:unable to get local issuer certificate
```
Going  by @superseb [link](https://medium.com/@superseb/get-your-certificate-chain-right-4b117a9c0fce), Root CA certificate is unknown. On my system, which is CentOS, i see that a CA bundle is present here but `subject` in this CA bundle is different from the `issuer`, which is what i was expecting.

```
# ls -l /etc/pki/tls/
total 12
lrwxrwxrwx  1 root root    49 May  2 15:51 cert.pem -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
drwxr-xr-x. 2 root root   138 May  2 15:51 certs
drwxr-xr-x. 2 root root   100 May  2 15:59 misc
-rw-r--r--  1 root root 10924 May 15 11:14 openssl.cnf
drwxr-xr-x. 2 root root    27 Mar 12 15:41 private
```

```
# openssl x509 -noout -subject -in /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
subject= /CN=ACCVRAIZ1/OU=PKIACCV/O=ACCV/C=ES
```

How do i fix such scenario?

**Comment by drpebcak** [comment]
Just to be clear here, you are terminating SSL in front of rancher, using nginx?

Try to relaunch rancher and also set `ingress.tls.source=secret`. Make sure nginx is configured to proxy traffic to rancher on port 80.

**Comment by drpebcak** [comment]
If your certificate is also self-signed, you might want to also look over the information here: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#certificates-from-files

**Comment by GarbageYard** [comment]
> Just to be clear here, you are terminating SSL in front of rancher, using nginx?
> 
> Try to relaunch rancher and also set `ingress.tls.source=secret`. Make sure nginx is configured to proxy traffic to rancher on port 80.

Thanks for the response but i am _now_ confused. I used [this suggestion](https://github.com/rancher/rancher/issues/20049#issuecomment-490394340) and installed Rancher using `--set tls=external`. Was that not the right setting? Also, I am using Nginx for SSL termination and using Helm to install Rancher.

> If your certificate is also self-signed, you might want to also look over the information here: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#certificates-from-files

I am simply using openssl to generate self-signed certificate but don't know why i am getting `Certificate chain is not complete` error.

**Comment by jocarren** [comment]
Did you get UI to work properly? Was it related to the DNS problem?

**Comment by superseb** [comment]
The Go based checker is probably more useful here: ```docker run superseb/ranchercheck https://your_rancher_url```

Given the multiple issues found, it would be good to isolate the issue as certificate issue (as long as there is only one source) would break in general, not intermittently which more seems like broken DNS/(overlay) network.

We have troubleshooting docs for those issues here https://rancher.com/docs/rancher/v2.x/en/troubleshooting/

**Comment by fabiorauber** [comment]
I'm having a similar problem, and right now can't access the Workloads section or Apps section in two of our clusters. We happen to have quite a lot of Apps (700+), Pods (1600+), ConfigMaps (1500+) and PVs (2300+) per cluster, but when querying via rancher kubectl, it does not seem to be an issue. Should not be in Rancher UI too, right?

**Comment by GarbageYard** [comment]
> Did you get UI to work properly? Was it related to the DNS problem?

Sorry for the delay in reply. This implementation has taken a backseat right now. Since it wasn't working that time, i switched to Rancher's own certificate set up. As of now, i am not working on it.

**Comment by superseb** [comment]
Let us know if there is something left to investigate.

**Comment by bmoorthi** [comment]
> 

45
29
