### ISSUE TITLE
Can't login to my v.2.2.2 Rancher instance via web

### ISSUE THREAD

**Issue by ssirag** [rancher/rancher#20058]
**Bug**

**Steps to reproduce:**
I have a stand-alone Rancher v.2.2.2 instance running on Ubuntu 18.04
Something happened over the weekend, and my Rancher container wasn't delivering the website correctly: all I got in the browser was a server error (I think it was a 500 error).
I rebooted the server, and the container came back online and the site is up, but now I can't log in.
The documented password doesn't work, and the AD integration I had been using isn't working.  Both return the result "Server error while authenticating".

Next I tried the reset-password command on the container outlined here:

https://rancher.com/docs/rancher/v2.x/en/faq/technical/

**Result:**

Login fails (see screenshots).

**Environment information**
- Rancher version: 2.2.2
- Installation option (single install/HA): Single

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```
![image](https://user-images.githubusercontent.com/8559431/57381734-85209f80-7179-11e9-9b81-92cd303c31d4.png)

![image](https://user-images.githubusercontent.com/8559431/57381820-b39e7a80-7179-11e9-9e11-8fde7549bcd9.png)

**Comment by cjellick** [comment]
you should be using the user name "admin", not user-zd54n

**Comment by ssirag** [comment]
I did try that also:  I got "Server error while authenticating"

**Comment by ssirag** [comment]
OK... that last result appears to have been browser caching somehow... I'm in again.
Thanks
