### ISSUE TITLE
Alerts don't work

### ISSUE THREAD

**Issue by vincent927** [rancher/rancher#20050]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

I created an alarm like this:

![image](https://user-images.githubusercontent.com/10399425/57356790-f4ab8480-71a3-11e9-986f-4358293ac3c4.png)

If it is normal, it will definitely alert and receive a notification, but I don’t have it.
**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v.2.2.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by deniseschannon** [comment]
@vincent927 what do you mean, you don't have it? are any alerts getting sent to your notifiers? have you tried testing your notifiers?

**Comment by vincent927** [comment]
> @vincent927 what do you mean, you don't have it? are any alerts getting sent to your notifiers? have you tried testing your notifiers?

Yes, I have not received any alert notifications, I have tested my email notification configuration, and I am able to receive test emails normally.

**Comment by vincent927** [comment]
i find this log in prometheus-cluster-monitoring pod
```
level=error ts=2019-05-10T06:11:32.747528559Z caller=notifier.go:481 component=notifier alertmanager=http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts count=0 msg="Error sending alert" err="Post http://alertmanager-operated.cattle-prometheus:9093/api/v1/alerts: dial tcp: lookup alertmanager-operated.cattle-prometheus on 10.43.0.10:53: no such host"
```

```
$ kubectl get all -n cattle-prometheus
NAME                                                          READY     STATUS    RESTARTS   AGE
pod/exporter-kube-state-cluster-monitoring-58f946d4d7-z88gw   1/1       Running   0          21h
pod/exporter-node-cluster-monitoring-l6vgg                    1/1       Running   0          21h
pod/exporter-node-cluster-monitoring-qwdlj                    1/1       Running   0          21h
pod/exporter-node-cluster-monitoring-rh4zl                    1/1       Running   0          21h
pod/grafana-cluster-monitoring-65d7cfccd8-7hjb2               2/2       Running   0          21h
pod/prometheus-cluster-monitoring-0                           5/5       Running   1          3m6s

NAME                                    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/access-grafana                  ClusterIP   10.43.246.17   <none>        80/TCP              21h
service/access-prometheus               ClusterIP   10.43.53.93    <none>        80/TCP              21h
service/expose-grafana-metrics          ClusterIP   None           <none>        3000/TCP            21h
service/expose-kube-cm-metrics          ClusterIP   None           <none>        10252/TCP           21h
service/expose-kube-etcd-metrics        ClusterIP   None           <none>        2379/TCP            21h
service/expose-kube-scheduler-metrics   ClusterIP   None           <none>        10251/TCP           21h
service/expose-kubernetes-metrics       ClusterIP   None           <none>        8080/TCP,8081/TCP   21h
service/expose-node-metrics             ClusterIP   None           <none>        9796/TCP            21h
service/expose-prometheus-metrics       ClusterIP   None           <none>        9090/TCP            21h
service/prometheus-operated             ClusterIP   None           <none>        9090/TCP            20h

NAME                                              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
daemonset.apps/exporter-node-cluster-monitoring   3         3         3         3            3           beta.kubernetes.io/os=linux   21h

NAME                                                     READY     UP-TO-DATE   AVAILABLE   AGE
deployment.apps/exporter-kube-state-cluster-monitoring   1/1       1            1           21h
deployment.apps/grafana-cluster-monitoring               1/1       1            1           21h

NAME                                                                DESIRED   CURRENT   READY     AGE
replicaset.apps/exporter-kube-state-cluster-monitoring-58f946d4d7   1         1         1         21h
replicaset.apps/grafana-cluster-monitoring-65d7cfccd8               1         1         1         21h

NAME                                             READY     AGE
statefulset.apps/prometheus-cluster-monitoring   1/1       20h
```

**Comment by vincent927** [comment]
![image](https://user-images.githubusercontent.com/10399425/57506398-4aac3380-732e-11e9-980c-d0e7b43411e2.png)

**Comment by Hwting** [comment]
Have you solved the same problem?

**Comment by vincent927** [comment]
not yet

**Comment by aiwantaozi** [comment]
Have you checked whether the DNS pod works well? ```dial tcp: lookup alertmanager-operated.cattle-prometheus on 10.43.0.10:53: no such host``` Seems like the DNS pod doesn't work.

**Comment by Hwting** [comment]
@aiwantaozi  
![image](https://user-images.githubusercontent.com/16237905/58223943-5516f600-7d4e-11e9-98b7-93b57cfdc830.png)

**Comment by Heiko-san** [comment]
Hi, I just wanted to file an issue about this, I think it is the very same problem.

**My findings about the potential root cause:**
We use Rancher v2.2.3 and the "integrated" prometheus/alert manager instances.
And actually it seems that this is the core of the problem:
As can be seen in the cattle-prometheus namespace of @vincent927 there is no alert manager running.
As a result of this none of the alerts seem to actually work/fire.

**Workaround:**
Create your own alert-group.
This will actually trigger the deployment of the alert manager.
As a "side-effekt" of this also alerts in the "standard" alert-groups will start to work.

**Steps to reproduce:**
* create a fresh cluster
* enable monitoring
* create an alert in an existing alert group (e.g. "A set of alerts for kube components") that should fire due  to the defined limit (e.g. "cluster:memory_usage:ratio > 0.001") and note that it doesn't ever fire (switch its state from "active" to "alerting", the notifiers itself aren't the issue here)
* have a look at "cattle-prometheus" namespace and note there is no "alertmanager-cluster-alerting" deployed
* create a new/own alert-group with the very same alert
* have a look at "cattle-prometheus" namespace and note "alertmanager-cluster-alerting" now is deployed
* note that the alert will fire now (and notify the configured hooks)

**But there is still a portion of the problem I don't understand:**
While writing this I could not get the original alert (the one under "A set of alerts for kube components") to fire, even after the alert manager was deployed.
However I'm absolutely certain that in similar experiments yesterday I managed to get firing alerts in the default alert-groups, too.

**Comment by Hwting** [comment]
@Heiko-san  It doesn't seem to be the same problem.
The alarm is triggered normally, but no message is sent.
![image](https://user-images.githubusercontent.com/16237905/58246578-0be49780-7d8a-11e9-834b-2ff7862353af.png)

**Comment by Heiko-san** [comment]
Sorry, I was pretty sure it is the same.
I now created: https://github.com/rancher/rancher/issues/20409

**Comment by vincent927** [comment]
@Hwting I find this error message in system apps cluster alerting 
![image](https://user-images.githubusercontent.com/10399425/59397015-acdcd600-8dbd-11e9-9824-bd5726f0987a.png)
![image](https://user-images.githubusercontent.com/10399425/59397018-b36b4d80-8dbd-11e9-9177-e02e058860a2.png)

**Comment by vincent927** [comment]
and i hava upgrade to v2.2.4

![image](https://user-images.githubusercontent.com/10399425/59397108-f9281600-8dbd-11e9-88d5-c40a23e399f7.png)

**Comment by aiwantaozi** [comment]
@vincent927   Alertmanager hasn't deployed success, could you check rancher server's logs for the deploy failed reason.

**Comment by vincent927** [comment]
I have upgraded the cluster alerting as shown below.![image](https://user-images.githubusercontent.com/10399425/59400300-96d51280-8dc9-11e9-8cc7-0236fdfdfde8.png)

But rancher ui is always like this

![image](https://user-images.githubusercontent.com/10399425/59400316-a6ecf200-8dc9-11e9-9d3a-934984905634.png)

Viewing with the command line seems to be normal again![image](https://user-images.githubusercontent.com/10399425/59400371-cf74ec00-8dc9-11e9-8e9e-79e520ad79fe.png)


And I have been able to receive the alert email, so how do I solve these problems?

**Comment by aiwantaozi** [comment]
UI have caches, you could refresh, then the UI will be updated, and your current version is 0.0.2, could select version 0.0.3 from the drop-down box

**Comment by vincent927** [comment]
@aiwantaozi 

```
[storage] 2019/06/13 05:38:17 updating release "cluster-alerting.v5"
2019/06/13 05:38:18 [ERROR] AppController p-zpvql/cluster-alerting [helm-controller] failed with : failed to install app cluster-alerting. Error: UPGRADE FAILED: no Service with the name "expose-kubelets-metrics" found

W0613 05:40:11.612442       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 24053601 (24054333)
2019-06-13 05:42:04.364387 I | mvcc: store.index: compact 9963686
2019-06-13 05:42:04.478609 I | mvcc: finished scheduled compaction at 9963686 (took 108.684195ms)
```

```
$ k get all -n cattle-prometheus
NAME                                                          READY     STATUS    RESTARTS   AGE
pod/alertmanager-cluster-alerting-0                           2/2       Running   0          3h39m
pod/exporter-kube-state-cluster-monitoring-58f946d4d7-dddd9   1/1       Running   0          4h
pod/exporter-node-cluster-monitoring-d5lqh                    1/1       Running   0          4h
pod/exporter-node-cluster-monitoring-mkqhk                    1/1       Running   0          4h
pod/exporter-node-cluster-monitoring-rhz8w                    1/1       Running   0          4h
pod/grafana-cluster-monitoring-65d7cfccd8-6wjrk               2/2       Running   0          4h
pod/prometheus-cluster-monitoring-0                           5/5       Running   1          4h
pod/prometheus-operator-monitoring-operator-85cbcb85b-zb9xd   1/1       Running   0          2d2h

NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/access-alertmanager             ClusterIP   10.43.75.208    <none>        80/TCP              3h57m
service/access-grafana                  ClusterIP   10.43.41.168    <none>        80/TCP              4h
service/access-prometheus               ClusterIP   10.43.115.127   <none>        80/TCP              4h
service/alertmanager-operated           ClusterIP   None            <none>        9093/TCP,6783/TCP   3h57m
service/expose-alertmanager-metrics     ClusterIP   None            <none>        9093/TCP            3h57m
service/expose-grafana-metrics          ClusterIP   None            <none>        3000/TCP            4h
service/expose-kube-cm-metrics          ClusterIP   None            <none>        10252/TCP           4h
service/expose-kube-etcd-metrics        ClusterIP   None            <none>        2379/TCP            4h
service/expose-kube-scheduler-metrics   ClusterIP   None            <none>        10251/TCP           4h
service/expose-kubelets-metrics         ClusterIP   None            <none>        10250/TCP           3h38m
service/expose-kubernetes-metrics       ClusterIP   None            <none>        8080/TCP,8081/TCP   4h
service/expose-node-metrics             ClusterIP   None            <none>        9796/TCP            4h
service/expose-prometheus-metrics       ClusterIP   None            <none>        9090/TCP            4h
service/prometheus-operated             ClusterIP   None            <none>        9090/TCP            4h

NAME                                              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
daemonset.apps/exporter-node-cluster-monitoring   3         3         3         3            3           beta.kubernetes.io/os=linux   4h

NAME                                                      READY     UP-TO-DATE   AVAILABLE   AGE
deployment.apps/exporter-kube-state-cluster-monitoring    1/1       1            1           4h
deployment.apps/grafana-cluster-monitoring                1/1       1            1           4h
deployment.apps/prometheus-operator-monitoring-operator   1/1       1            1           2d2h

NAME                                                                DESIRED   CURRENT   READY     AGE
replicaset.apps/exporter-kube-state-cluster-monitoring-58f946d4d7   1         1         1         4h
replicaset.apps/grafana-cluster-monitoring-65d7cfccd8               1         1         1         4h
replicaset.apps/prometheus-operator-monitoring-operator-85cbcb85b   1         1         1         2d2h

NAME                                             READY     AGE
statefulset.apps/alertmanager-cluster-alerting   1/1       3h58m
statefulset.apps/prometheus-cluster-monitoring   1/1       4h
```

**Comment by vincent927** [comment]
@aiwantaozi   but i can recive monitor message normaly :cry

**Comment by aiwantaozi** [comment]
Just check your environment again, system-chart 0.0.3 haven't released on rancher 2.2.2, what the server version? 0.0.3 not released yet.

**Comment by vincent927** [comment]
emmm···· I upgrad to 2.2.4  yesterday

**Comment by aiwantaozi** [comment]
Just checked, there is a bug will cause upgrade failed and deploy two operators, but it doesn't affect alert functionality we will fix it soon. Thanks. 0.0.2 and 0.0.3 version alertmanager almost the same,  just upgrade alertmanager version. Thanks, will fix soon.

**Comment by vincent927** [comment]
@aiwantaozi  thanks a lot

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/21113
