### ISSUE TITLE
Project Network Isolation not working

### ISSUE THREAD

**Issue by shibumi** [rancher/rancher#20054]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**
Deployed on metal
Rancher v2.2.2
Kubernetes Version: v1.13.5-rancher1-2
Network provider: Canal 
Project Network Isolation: Enabled

Running on a custom single node cluster

Create 1 Container with nginx in Project `default`.
Create 1 Container with nginx in a new Project called `test`

Execute a shell on one of the containers and try to ping the other container or reach the other containers Page at port 80

This works directly via: `curl 10.42.0.59:80`

**Result:**

The Project Network isolation doesn't work

**Other details that may be helpful:**

- 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

See above

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

See above

Docker 18.0.9.5-1

**Comment by deniseschannon** [comment]
Did you make sure to enable project isolation?

 For your cluster, can you "view in API" and share the `rancherKubernetesEngineConfig` section? 

Or in the UI, click on "edit" for the cluster and share the details if you click on "edit as yaml".

**Comment by shibumi** [comment]
Here is my `rancherKubernetesEngineConfig`:
```
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509|webhook",
"type": "/v3/schemas/authnConfig"
},
"authorization": {
"type": "/v3/schemas/authzConfig"
},
"bastionHost": {
"sshAgentAuth": false,
"type": "/v3/schemas/bastionHost"
},
"cloudProvider": {
"type": "/v3/schemas/cloudProvider"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "v1.13.5-rancher1-2",
"monitoring": {
"provider": "metrics-server",
"type": "/v3/schemas/monitoringConfig"
},
"network": {
"options": {
"flannel_backend_type": "vxlan"
},
"plugin": "canal",
"type": "/v3/schemas/networkConfig"
},
"restore": {
"restore": false,
"type": "/v3/schemas/restoreConfig"
},
"services": {
"etcd": {
"backupConfig": {
"enabled": true,
"intervalHours": 12,
"retention": 6,
"s3BackupConfig": null,
"type": "/v3/schemas/backupConfig"
},
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": false,
"type": "/v3/schemas/etcdService"
},
"kubeApi": {
"alwaysPullImages": false,
"podSecurityPolicy": false,
"serviceNodePortRange": "30000-32767",
"type": "/v3/schemas/kubeAPIService"
},
"kubeController": {
"type": "/v3/schemas/kubeControllerService"
},
"kubelet": {
"failSwapOn": false,
"type": "/v3/schemas/kubeletService"
},
"kubeproxy": {
"type": "/v3/schemas/kubeproxyService"
},
"scheduler": {
"type": "/v3/schemas/schedulerService"
},
"type": "/v3/schemas/rkeConfigServices"
},
"sshAgentAuth": false,
"type": "/v3/schemas/rancherKubernetesEngineConfig"
},
```

And here is a screenshot of the enabled canal:
![https://paste.xinu.at/ENp/](https://paste.xinu.at/ENp/)

**Comment by loganhz** [comment]
`cluster.enableNetworkPolicy ` should be `true` if it is enabled. Cannot reproduce in 2.3.3. Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
