### ISSUE TITLE
Rancher should allow per-cluster settings of an ingress static suffix (instead of just xip.io)

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#20056]
**What kind of request is this (question/bug/enhancement/feature request):** Feature Request

When creating an ingress object with an automatically generated hostname, Rancher assumes the user wants to create an ingress object with the global DNS wildcard domain (i.e. `xip.io`) which can be an incorrect assumption. For example, if I were to have `*.foo.example.com` be a wildcard that points towards the load balancer fronting my ingress controllers in cluster 1, I would not be able to have ingresses automatically have `foo.example.com` appended to them without creating my own controller to do this action.

This type of functionality can also be useful for TLS terminated workloads, where automatic TLS termination is enabled when the ingress wildcard domain is set. Thus, there are a few additional configurations that would be required (on a per-cluster setting) to enable such functionality:
```
auto-dns-suffix: foo.example.com
auto-dns-enabled: true
auto-dns-tls: true
```

with these three functionalities, at the cluster level, a user should be able to deploy their application, and request an ingress hostname that ends with the specific `foo.example.com`.

**Comment by janeczku** [comment]
Additionally, this functionality would also admins to configure a custom schema used to generate hostnames by specifying a template using a set of supported placeholders such as `{{ingressName}}`, `{{namespace}}`, `{{clusterName}}`, `{{clusterDnsSuffix}}`.
Example:
`auto-dns-template`: `{{ingressName}}.ingress-{{clusterName}}.{{clusterDnsSuffix}}`

**Comment by janeczku** [comment]
Related: https://github.com/rancher/rancher/issues/19786
