### ISSUE TITLE
Unable to send email notification without SMTP authentication

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#20060]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy Rancher v2.2.0
- Add an email notifier with the following settings
Port: 25
Use TLS: unchecked
Username: << blank >>
Password: << blank >>

**Result:**
level=error ts=2019-05-06T19:59:34.526761127Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="missing password for PLAIN auth mechanism" 
level=error ts=2019-05-06T19:59:34.526896715Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="missing password for PLAIN auth mechanism; missing password for PLAIN auth mechanism" 
level=error ts=2019-05-06T19:59:44.527164139Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="missing password for PLAIN auth mechanism" 
level=error ts=2019-05-06T19:59:44.527238936Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="missing password for PLAIN auth mechanism" 
level=error ts=2019-05-06T19:59:44.527322616Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="missing password for PLAIN auth mechanism; missing password for PLAIN auth mechanism"

**Other details that may be helpful:**
These settings work in Rancher v2.1.6 using rancher/prom-alertmanager:v0.15.2
Also, this look to be related to https://github.com/prometheus/alertmanager/issues/1721

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.0
- Installation option (single install/HA): HA

**Comment by berni2288** [comment]
We also have the same bug, I think this is a bug in alertmanager and has been fixed in 0.16.2, the prom-alertmanager in Rancher should be updated to 0.16.2 also.

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc7`

**Comment by rootwuj** [comment]
Tested with rancher/rancher:v2.2.4-rc7 (Environment: single install and HA ) from May 22
Verified fixed

Test1:
* Freshly deployed rancher:v2.2.4-rc7 and add cluster
* Add an email notifier without SMTP authentication
* Add an alert
* Check the alertmanager version
* Check the alertmanager log
* Validate cluster and project level alerting

Result1:
* Alertmanager version upgrade to `rancher/prom-alertmanager:v0.17.0`.
* Alertmanager does not have error log when SMTP authentication is not set.
* Ability to send mail, use this notifier at the cluster and project level.

Test2:

* Deploy Rancher:v2.2.0
* Add an email notifier without SMTP authentication
* Add an alert
* Upgrade from v2.2.0 to v2.2.4-rc7, then validate the alert is still working.

Result2:

* Manually update the cluster-alerting app and then be able to send alert emails.
