### ISSUE TITLE
Backport: Hide controller manager and scheduler for AKS cluster

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20066]
Backport rancher/rancher#17344

**Comment by alena1108** [comment]
can be tested in rc9

**Comment by davidnuzik** [comment]
Version: v2.2.4-rc1

I can confirm the same findings as in #17344 on master. The Controller Manager and Scheduler now show up as grayed-out.

![image](https://user-images.githubusercontent.com/45179589/57719069-c0b4e100-7633-11e9-833c-c8f893410a76.png)

**Comment by mikhail-arundo** [comment]
This issue still exists for AKS clusters imported in 2.2.4 after upgraded to 2.2.5. screenshot in #21537
