### ISSUE TITLE
slackConfig should not require defaultRecipient

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20067]
Version: v2.1.7, v2.2.0, v2.2.3, Master
(Is pre-existing issue)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Via slack API create an app and your own incoming webhook. Note you can define the default channel to anything  you like.
- Now, in Rancher  UI, create a slack notifier. Notice that the Default Channel is required and is required in the API.

**Result:**
slackConfig should not have defaultRecipient required: true because our default is already defined in the slack incoming webhook therefore it should be optional. The UI helper text also mentioned this is optional but it is required in the UI because of the API.

**Other details that may be helpful:**
required: false should be the proper setting for defaultRecipient in slackConfig schema.
```
{
"baseType": "schema",
"id": "slackConfig",
"links": {
"self": "…/v3/schemas/slackConfig"
},
"pluralName": "slackConfigs",
"resourceFields": {
"defaultRecipient": {
"create": true,
"nullable": true,
"required": true,
"type": "string",
"update": true
},
"url": {
"create": true,
"nullable": true,
"required": true,
"type": "string",
"update": true
}
},
"type": "schema",
"version": {
"group": "management.cattle.io",
"path": "/v3",
"version": "v3"
}
},
```

**Comment by aiwantaozi** [comment]
The slack webhook could be used for all channel, which means it doesn't matter whether you configure channel A or B, the webhook URL is the same, so when you configure channel A in slack, you can also configure B in Rancher, we will send alert to B, so the default recipient is required like others notifiers.

**Comment by deniseschannon** [comment]
Slack webhooks require you to select a channel, so it should not be required as @davidnuzik has pointed out.

@aiwantaozi can you update the schema so that it's not required and open a UI ticket for removing the asterisk and assign that to @loganhz 

![Screen Shot 2019-08-12 at 3.48.04 PM.png](https://zube.io/files/rancher/17d75ada2906de082f734c42f7ec216f-screen-shot-2019-08-12-at-3-48-04-pm.png)

**Comment by aiwantaozi** [comment]
Related PR already exist, https://github.com/rancher/types/pull/920

**Comment by deniseschannon** [comment]
Since this ticket is being used for API and UI, please test both in this issue.

**Comment by izaac** [comment]
Tested with default `defaultRecipient=null` and `defaultRecipient="#some-channel"`

```json
{
  "type": "notifier",
  "name": "izaac-test",
  "description": null,
  "clusterId": "EDITED",
  "slackConfig": {
    "type": "slackConfig",
    "url": "EDITED",
    "defaultRecipient": "#some-channel"
  }
}
```

```json
{
  "type": "notifier",
  "name": "izaac-test",
  "description": null,
  "clusterId": "EDITED",
  "slackConfig": {
    "type": "slackConfig",
    "url": "EDITED",
    "defaultRecipient": "#some-channel"
  }
}
```

using curl and from Rancher notifiers UI

<img width="282" alt="Screen Shot 2019-08-15 at 4 05 28 PM" src="https://user-images.githubusercontent.com/27659/63132604-8c282c80-bf76-11e9-8e9e-484aa947f84a.png">
