### ISSUE TITLE
[Monitoring] When have windows nodes the UI still shows monitoring features in unsupported (Windows) areas

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20076]
Version: Master (v2.3) (5/8/19)
Related: rancher/rancher#20077 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a custom RKE cluster that has at least 1 windows worker node
- Enable monitoring, view the node details page, and view the workload details page for a workload that is scheduled to run on the windows node.

**Result:**
When view the node details page we still see that we have the monitoring node dashboard even though this is not supported for Windows:
![image](https://user-images.githubusercontent.com/45179589/57406421-895ab600-7195-11e9-85d8-52b73eea01a1.png)
(We should show classic node dashboard when node is windows, and we should hide "Node Metrics")

When view the workload details of a workload that is scheduled to run on windows, we still see the "Workload Metrics"
![image](https://user-images.githubusercontent.com/45179589/57407755-c96f6800-7198-11e9-9558-0da8a28167f5.png)
(We should hide "Workload Metrics")

The same is true if view Pod Details page (We see "Pod Metrics" and should hide this)
And Container Details page (We see "Container Metrics" and should hide this)

**Comment by lvuch** [comment]
@loganhz could you review this issue, please?

**Comment by loganhz** [comment]
We will support monitoring for windows. It will get fixed after that

**Comment by davidnuzik** [comment]
I know this has been moved out of test, but I did some quick checks today in master-head (v2.3) (8/28/19) and I observed pod/container metrics working fine with a windows workload. I also did not observe the "loading" green text issue on the Cluster page.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/29/19)

I performed additional checks on top of my last comment. At the cluster page the summaries are now correct, showing the correct resources available regardless of the os (Windows info was missing before which used to make the stats inaccurate or not show at all).

This is mainly because the windows node exporter is working now. When I enable monitoring, all the workloads deploy successfully and work as expected now. This was not the case earlier.
![image](https://user-images.githubusercontent.com/45179589/63976884-34ee8580-ca67-11e9-8c74-2be4b442731d.png)

My workload metrics, pod metircs, and container metrics all work. I get CPU/Memory infos. When I stress the CPU the charts increase accordingly.

**To be tested: Project-level monitoring once we have a test windows image available.**

**Comment by davidnuzik** [comment]
TODO: test project-level monitoring
TODO: get question answered (or enter a new issue if necessary)

@loganhz things look good with my testing thus far. I had a question though (not sure if this needs to be a new issue)

When I view the cluster page, there is a dispairty between reserved and used CPU. Is this expected? My understanding is when you set up the rancher agent on a windows node some CPU has to be reserved and so k8s only reports so much CPU actually as usable -- is this why I see this?

![image](https://user-images.githubusercontent.com/45179589/63977082-acbcb000-ca67-11e9-8b1c-913bc1281bc4.png)

If this is expected, then perhaps I should enter a separate issue so we could add a small info bubble somewhere that explains this in the UI.

**Comment by loganhz** [comment]
yes. We reserved some cpu and memory for Windows OS itself by following the best practice
