### ISSUE TITLE
Backport: Fail to create persistent volume

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#20072]
Backport fix for https://github.com/rancher/rancher/issues/19237 rancher/rancher#19216

**Comment by alena1108** [comment]
can be tested in rc8

**Comment by alena1108** [comment]
@bmdepesa just found out that the fix is not included in rc8. Will be available in v2.2.4-rc2

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.4-rc1

* Creating a PV from Storage Class for Azure dedicated disk works correctly
* Creating a PV from Storage Class for Azure shared disk does not work

To reproduce
*  Deploy Rancher
* Create Azure cluster w/ cloud provider
* Create a storage class of type Azure Disk - Shared (Unmanaged) 
* Create a workload with a new PV from Storage Class

Workload does not provision and an error is shown: `Pod has unbound immediate PersistentVolumeClaims (repeated 2 times)`

The persistent volume is not created, though there is a claim.

**Comment by kinarashah** [comment]
@bmdepesa should work in rancher/rancher:v2.2.4-rc2

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.4-rc5

* Can create storage classes for shared and dedicated unmanaged disks
* PV are created correctly from storage classes
