### ISSUE TITLE
Backport globalDNS entry allows any string for fqdn even invalid DNS chars

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20088]
Backport https://github.com/rancher/rancher/issues/19738

**Comment by alena1108** [comment]
will be available in rc8

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc8

Confirmed API was updated:
```
"fqdn": {
"create": true,
"nullable": true,
"required": true,
"type": "hostname",
"update": true
},
```

Tried in the UI to put invalid chars. UI tells me these chars are not allowed:
![image](https://user-images.githubusercontent.com/45179589/57558529-e475df80-7332-11e9-9585-f7a11d4e0617.png)
