### ISSUE TITLE
[UI] Windows Support -  No way to pick whether apps get deployed to Linux or Windows nodes

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20089]
Version: Master (v2.3) (5/8/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create some apps on a cluster that has at least 1 windows worker node

**Result:**
The apps can be scheduled to run on windows nodes which will prevent the apps from deploying correctly.

**Other details that may be helpful:**
We need to consider adding an option similar to what we have when we create a workload to pick where the app can be scheduled to, either agnostic (either) or linux or windows. Ideally we should only be showing this option if we detect at least 1 windows worker node.

**Comment by deniseschannon** [comment]
Per @ibuildthecloud, we should go down the route of putting a taint on the linux worker node so nothing ever gets scheduled onto that worker node.

**Comment by loganhz** [comment]
Adding taints for linux worker will be done with https://github.com/rancher/rancher/issues/20805

Confirmed with Will, for this issue, we will show a warning message so users can notice that not all the apps in Library catalog will work in Windows clusters.

![image](https://user-images.githubusercontent.com/21168270/62297664-3a76a100-b4a4-11e9-96e1-9f22608b7737.png)

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/9/19)

I can confirm the addition of the warning ribbon and message when we have a windows cluster.

![image](https://user-images.githubusercontent.com/45179589/62808927-61d5fb00-baae-11e9-8ee7-9f1c561f09ae.png)

To have a cluster be considered a windows cluster, simply enable "Windows Support" when creating a custom cluster (need flannel CNI and k8s 1.15 or newer)
