### ISSUE TITLE
Backport: Remove windows options in 2.2.3 and 2.1.10 branch

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20081]
Backport https://github.com/rancher/rancher/issues/20025

**Comment by alena1108** [comment]
will be available in v2.1.10-rc1

**Comment by loganhz** [comment]
v2.1.10-rc1 is out

**Comment by kingsd041** [comment]
V2.1.10-rc5 and v2.2.4-rc22 have removed windows support options
