### ISSUE TITLE
QuickStart Guide does not work out

### ISSUE THREAD

**Issue by SockenSalat** [rancher/rancher#20105]
When working through the QuickStart Guide, the Step "Expose The Application Via An Ingress" does not produce the expected result.

When trying to reach the export workload Nginx answers ` 503 Service Temporarily Unavailable`. 

The log of the ingress-container says:
`controller.go:753] Error obtaining Endpoints for Service "default/ingress-568322f1cbe6a531554c821256913b21": no object matching key "default/ingress-568322f1cbe6a531554c821256913b21" in local stor` 

I tried that with latest and stable versions of rancher.

**Comment by superseb** [comment]
Can you provide full logs from the nginx ingress controller and the output of `kubectl get ep` and `kubectl get pods` so we can reopen and investigate?
