### ISSUE TITLE
Unable to create a first cluster (Getting Started)

### ISSUE THREAD

**Issue by gbrisson** [rancher/rancher#20106]
I have installed Docker-ce (latest) and then Rancher with success following the "Getting Started" guide on the Rancher web site.
When I try to create my first cluster, I get the followoing message:
"Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system".

I use Ubuntu 18.04 with 8GB of RAM.

Any suggestion?

Thanks in advance.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`global-admin.clusters.index`|

**Comment by xorpierre** [comment]
Did you wait? Sometimes the pods throw errors until other pods are started up, can take easily 10 min for a fresh cluster depending on its size.
Be aware k8s only runs on specific docker versions, we had troubles with that before, even a subversion mismatch can be the problem

**Comment by gbrisson** [comment]
Thanks for your reply. I did wait for at least 20 minutes.

I suspect my Linux installation to be perhaps not clean. I am reinstalling
Ubuntu and I will try again. Will keep you posted.

Gilles

**Comment by superseb** [comment]
Job logs can be retrieved using
 ```
kubectl -n kube-system logs -l job-name=rke-network-plugin-deploy-job
```

Issues with nodes can be retrieved using:

 ```
kubectl get nodes -o go-template='{{range .items}}{{$node := .}}{{range .status.conditions}}{{if ne .type "Ready"}}{{if eq .status "True"}}{{$node.metadata.name}}{{": "}}{{.type}}{{":"}}{{.status}}{{"\n"}}{{end}}{{else}}{{if ne .status "True"}}{{$node.metadata.name}}{{": "}}{{.type}}{{": "}}{{.status}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}'
```
Let me know if we need to continue investigating
