### ISSUE TITLE
backport: Monitoring API is not ready

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20114]
Backport https://github.com/rancher/rancher/issues/19665

**Comment by alena1108** [comment]
Can be tested with rc8

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: v2.2.3-rc8

Steps: 
- run Rancher container, single installed
- use RKE: v0.1.18 to provision a 3-node RKE cluster (all roles on each node)
- import the cluster into Rancher
- enable/disable cluster monitoring
- enable/disable project monitoring

Result:
- Both cluster and project monitoring work as expected.
