### ISSUE TITLE
Backport cattle-prometheus namespace not removed alongside cattle-system when imported cluster deleted in Rancher

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20113]
Backport https://github.com/rancher/rancher/issues/19476

**Comment by alena1108** [comment]
can be tested with rc8

**Comment by loganhz** [comment]
can be tested with rc9

**Comment by jiaqiluo** [comment]
The bug fix is validated on v2.2.4-rc1

Steps:
- Import a cluster into Rancher v2.2.4-rc1
- Enable cluster monitoring in the imported cluster
- Delete the imported cluster via Rancher UI

Results:
- Both the namespaces and pods under the namespaces `cattle-prometheus` and `cattle-system` are removed from the cluster.
