### ISSUE TITLE
Backport: UI - Not able to edit cluster with cloud provider settings that have credentials

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20117]
Backport rancher/rancher#20044

**Comment by sangeethah** [comment]
This issue is still reproducible in v2.2.3-rc9 , UI tag - v2.2.58.

**Comment by sangeethah** [comment]
This issue is still reproducible when testing with v2.2.4-rc1 and ui tag - v2.2.61

**Comment by sangeethah** [comment]
@westlywright , I am reopening this issue to see if we do not have to force users to enter a credential , every time edit cluster is done.

Even with credential field being empty , we should be able to allow updates to cluster succeed.
@mrajashree mentioned that API will be able to handle this case.

**Comment by sangeethah** [comment]
Tested with v2.2.4-rc2.

When editing a AZ cluster with cloud provider , user presented with "aadClientSecret" with no value in .  User is able to edit the cluster successfully without having to set any values for "aadClientSecret".

Also when editing the AZ cluster with cloud provider option , use "Edit as Yaml" option. aad_client_secret is shown as empty field (`aad_client_secret: ""`) . Change any other cluster option and save.  User is able to edit the cluster successfully without having to reenter secrets value.
