### ISSUE TITLE
Backport:OTC node driver fails to be activated

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20126]
https://github.com/rancher/rancher/issues/19223

**Comment by loganhz** [comment]
in rc8

**Comment by loganhz** [comment]
in rc9

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc9

I validated the updated binary URL (https://github.com/rancher-plugins/docker-machine-driver-otc/releases/download/v2019.5.7/docker-machine-driver-otc) and that the hash was correctly updated (3f793ebb0ebd9477b9166ec542f77e25).

The driver now activates without any issues in the UI or rancher logs. I can access the OTC cluster config without any issues.
