### ISSUE TITLE
rancher server stuck in Restarting state in loop

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2012]
Server version 0.34.0

sudo docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                         PORTS                              NAMES
408e9f7be161        rancher/server:v0.34.0   "/usr/bin/s6-svscan /"   19 hours ago        Restarting (0) 3 seconds ago   0.0.0.0:8080->8080/tcp, 3306/tcp   mad_colden

Re-started rancher server container and it got stuck in "Restarting" state and in loop. I see these logs copied below. 

150910  1:45:03 [ERROR] Incorrect integer value: '10000000000000000000000000000000000000000000'
150910  1:45:03 [Warning] option 'max_connections': unsigned value 0 adjusted to 1
150910  1:45:03 [ERROR] /usr/sbin/mysqld: Error while setting value 

'10000000000000000000000000000000000000000000' to 'max_connections'
150910  1:45:03 [ERROR] Aborting

150910  1:46:46 [ERROR] Incorrect integer value: '100000000000000000000000000000000000000000000'
150910  1:46:46 [Warning] option 'max_connections': unsigned value 0 adjusted to 1
150910  1:46:46 [ERROR] /usr/sbin/mysqld: Error while setting value '100000000000000000000000000000000000000000000' to 'max_connections'
150910  1:46:46 [ERROR] Aborting

150910  1:50:11 [ERROR] Incorrect integer value: '1000000000000000000000000000000000000000000000'
150910  1:50:11 [Warning] option 'max_connections': unsigned value 0 adjusted to 1
150910  1:50:11 [ERROR] /usr/sbin/mysqld: Error while setting value '1000000000000000000000000000000000000000000000' to 'max_connections'
150910  1:50:11 [ERROR] Aborting

**Comment by aruneli** [comment]
Just found that it was fixed in 0.35.0, hence closing this issue.

**Comment by haimari** [comment]
18675c5ed1fe        rancher/server:stable           "/usr/bin/entry --..."   29 seconds ago      Restarting (127) Less than a second ago
