### ISSUE TITLE
[Windows Logging] Logging does not deploy correctly

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20123]
Please note, I am aware that for experimental Windows, logging is not currently supported. The purpose of this issue is to track this, so we can figure out how to handle this in the future.

Version:  Master (v2.3) (5/9/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster with 1 or more windows nodes.
- Enable Logging on the cluster.

**Result:**
The Logging pods will fail to deploy. They cannot deploy to the windows worker node(s).
We, at a minimum, should try to warn the user about logging when you have windows nodes.
Longer-term we need  a better solution for this or handle it better when enabled.

If you try to disable logging it won't work too. It doesn't tear down the workloads.

**Comment by davidnuzik** [comment]
Note: presently on-hold; vxlan is not supported in rancher logging (according to UI message we get) so we're checking to see what our options are for testing.

**Comment by kingsd041** [comment]
Version: master-head (9/7/19)
Use the host-gw network, verify the following test cases, and verify the pass.
- Cluster level and project level logging
- RKE workload logging
- windows workload logging
- Include System Log
