### ISSUE TITLE
[Windows] Warning-FailedCreatePod is seen while creating a windows workload

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20121]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a custom cluster - 1etcd,control plane linux node, 1 linux worker node, 2 windows worker nodes.
2. Deploy a windows workload.

**Expected Result:**
Workload should be deployed with no warnings/errors.

**Actual Result:**
in workload - pods - under `Events` we see the below shown warning. This happens when the image is pulled for the first time on the node.
<img width="1436" alt="Screen Shot 2019-05-09 at 11 34 47 AM" src="https://user-images.githubusercontent.com/26032343/57496431-ce5f1500-7287-11e9-8cbd-b50289a56f23.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.14.1
```

**Comment by cjellick** [comment]
@loganhz please have your team investigate. If we can make the experience better without risking the release, id like to fix it

**Comment by cjellick** [comment]
not a blocker, but a nice to have for the alpha

**Comment by cjellick** [comment]
not a blocker and couldn't get to it in time for alpha. moving out of alpha

**Comment by loganhz** [comment]
It's a Windows side or docker side issue. We don't know how to fix it. It's just a warning. So maybe we can move it out from 2.3

**Comment by sirredbeard** [comment]
Old issue. Just a warning. Closing.
