### ISSUE TITLE
Support for managing OKE (hosted k8s)

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20132]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
https://cloud.oracle.com/containers/kubernetes-engine

gz#4296

**Comment by jlamillan** [comment]
The OKE driver is [available](https://github.com/rancher-plugins/kontainer-engine-driver-oke) for installation and on by default in Rancher 2.4.
