### ISSUE TITLE
Allowed to log in as a inactive account in a github auth enabled setup 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2014]
Server version - V0.37.0-rc1

Had enabled github authentication when in V.0.35.0 version with "ranchertdev" account having  access to "Default" and another project "test".

Upgraded to V0.37.0-rc1.

When logged in as admin user , I am able to see the list of github users that were authenticated to this set up including "ranhcerdev"

I used the "Deactivate" option to deactivate  "rancherdev" account which gets to "inactive" state,

I am still being allowed to log into rancher-server as "ranhcerdev".

Expected Behavior:
Inactive users should not be granted access  .

**Comment by hibooboo2** [comment]
Addressed with rancher/cattle#860

**Comment by sangeethah** [comment]
Tested with server version - V0.37.0-rc4

We not allowed to log as deactivated users in a github auth enabled setup.
