### ISSUE TITLE
Show global registry as an option in adding registry credential page

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20150]
If global registry enabled, users don't have to input the registry address manually in adding registry credential page.

**Comment by deniseschannon** [comment]
Can we make this more generic to be able to somehow indicate that if an app is a registry, we can have that show up as a registry?

**Comment by loganhz** [comment]
Created another issue for generic registry app  https://github.com/rancher/rancher/issues/20346

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/7/19)

When Global Registry is enabled you'll now see an option to use the local registry (it shows your hostname) as a radio button upon when you go to the "Registries" page at the project level.

The core functionality is working as expected (has been validated via UI Global Registry test plan).
Testing in this area will continue as I work to finalize executing test cases in the test plan; but basic functionality is validated and working as expected.
