### ISSUE TITLE
Security, Authentication, LDAP:  rancher server error on principal search (groups, users)

### ISSUE THREAD

**Issue by donatasnicequestion** [rancher/rancher#20159]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Configure Security, Provider Open LDAP 
Enter information  requested (the same like many other tools and systems)
Test-authentication: success. 

Afterwards

Select : "Allow members of Clusters, Projects, plus Authorized Users and Organizations" radio.
Start entering some user name into "Authorized Users and Organizations" input field

**Result:**
No users or groups available  -therefore  LDAP authorization ist not usable.
It is not possible to select users or groups and to assign them as a members of cluster.

Panic Errors in rancher server Logs:

```
2019/05/10 16:20:04 [ERROR] Panic serving api request:
goroutine 52240 [running]:
runtime/debug.Stack(0xc005c7a930, 0x33f6e40, 0x6a97ee0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x41d6e80, 0xc00739dcf0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x67
panic(0x33f6e40, 0x6a97ee0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/rancher/rancher/pkg/auth/providers.SearchPrincipals(0x68fb7d6, 0x1, 0x0, 0x0, 0xc0116e47aa, 0x5, 0xc01139cfa0, 0x17, 0xc0116e47d0, 0xb, ...)
        /go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:137 +0x74
github.com/rancher/rancher/pkg/auth/principals.(*principalsHandler).actions(0xc0028148c0, 0xc009fa78ab, 0x6, 0xc00555e180, 0xc0059370e0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/pkg/auth/principals/handler.go:56 +0x3f7
github.com/rancher/rancher/pkg/auth/principals.(*principalsHandler).actions-fm(0xc009fa78ab, 0x6, 0xc00555e180, 0xc0059370e0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/pkg/auth/principals/schema.go:16 +0x52
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.handleAction(0xc00555e180, 0xc0059370e0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:263 +0x62
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc00119b810, 0x41d6e80, 0xc00739dcf0, 0xc00c9c8400, 0xc00b651380, 0xc005d2dcb0, 0xc005c7b6d0)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:251 +0xd2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc00119b810, 0x41d6e80, 0xc00739dcf0, 0xc00c9c8400)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x7d
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0020a6d90, 0x41d6e80, 0xc00739dcf0, 0xc00c9c8400)
        /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x41a1080, 0xc005f28f00, 0x4196800, 0xc0020a6d90, 0x41b4d00, 0xc003c6bd00, 0x41a1040, 0xc003bf23f0, 0x41d6e80, 0xc00739dcf0, ...)
        /go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:110 +0x60d
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4195140, 0xc005029c40, 0x0, 0x41d6e80, 0xc00739dcf0, 0xc00c9c8200)
        /go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x46a
github.com/rancher/rancher/server/responsewriter.ContentType.func1(0x41c1d80, 0xc0057a8d20, 0xc00c9c8200)
        /go/src/github.com/rancher/rancher/server/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0030c1de0, 0x41c1d80, 0xc0057a8d20, 0xc00c9c8200)
        /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/rancher/rancher/server/responsewriter.Gzip.func1(0x41d6cc0, 0xc01107f960, 0xc00c9c8200)
        /go/src/github.com/rancher/rancher/server/responsewriter/gzip.go:60 +0x1ac
net/http.HandlerFunc.ServeHTTP(0xc0030c1e00, 0x41d6cc0, 0xc01107f960, 0xc00c9c8200)
        /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0020a6bd0, 0x41d6cc0, 0xc01107f960, 0xc00c9c8200)
        /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0x41d6cc0, 0xc01107f960, 0xc01114a700)
        /go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:436 +0x101
net/http.HandlerFunc.ServeHTTP(0xc003d50fa0, 0x41d6cc0, 0xc01107f960, 0xc01114a700)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc005e99ad0, 0x41d6cc0, 0xc01107f960, 0xc01114a700)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc010d500a0, 0x41e0380, 0xc0132a8200)
        /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5


```

**Other details that may be helpful:**
LDAP-Server: Oracle Internet Directory. 

**Environment information**
```
- Rancher version:  v 2.2.2 , Reproducible also with  v2.2.3-rc8
- Installation option: single install
```
- Docker version (use `docker version`):
```
$ docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.11.1
 Git commit:        4d60db472b
 Built:             Thu Nov  8 21:14:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056dbc
  Built:            Thu Apr 11 04:50:00 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by tannh** [comment]
I have same issue, 
![image](https://user-images.githubusercontent.com/21053829/58160657-13803f80-7ca9-11e9-827a-b3e939ecf08e.png)
DEBUG Logging 
DEBUG] Requesting user: user-s6xl6, Requesting groups: [system:authenticated] Impersonate user:  Impersonate group: []
2019/05/22 08:21:12 [ERROR] Panic serving api request:
goroutine 57351 [running]:
runtime/debug.Stack(0xc001fd68a0, 0x33d62a0, 0x6a44e90)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x419afe0, 0xc000af1ac0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x67
panic(0x33d62a0, 0x6a44e90)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/rancher/rancher/pkg/auth/providers.SearchPrincipals(0xc002abf0f8, 0x5, 0x0, 0x0, 0xc0012dede8, 0x5, 0xc000e31b00, 0x17, 0xc0012dee40, 0xb, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/providers/providers.go:137 +0x74
github.com/rancher/rancher/pkg/auth/principals.(*principalsHandler).actions(0xc0002bc8c0, 0xc001ed0e8b, 0x6, 0xc001e9f9a0, 0xc00120c120, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/principals/handler.go:56 +0x3f7
github.com/rancher/rancher/pkg/auth/principals.(*principalsHandler).actions-fm(0xc001ed0e8b, 0x6, 0xc001e9f9a0, 0xc00120c120, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/auth/principals/schema.go:16 +0x52
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.handleAction(0xc001e9f9a0, 0xc00120c120, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:263 +0x62
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc00088ef20, 0x419afe0, 0xc000af1ac0, 0xc002449800, 0xc00232fe00, 0xc0013b4750, 0xc001fd7640)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:251 +0xd2
github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc00088ef20, 0x419afe0, 0xc000af1ac0, 0xc002449800)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x7d
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00062c230, 0x419afe0, 0xc000af1ac0, 0xc002449800)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x4165260, 0xc001209b00, 0x415aa20, 0xc00062c230, 0x4178ee0, 0xc000e80e00, 0x4165220, 0xc0013b4e10, 0x419afe0, 0xc000af1ac0, ...)
	/go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:110 +0x60d
github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x4159360, 0xc000ff4400, 0x0, 0x419afe0, 0xc000af1ac0, 0xc002449600)
	/go/src/github.com/rancher/rancher/pkg/audit/filter.go:31 +0x46a
github.com/rancher/rancher/server/responsewriter.ContentType.func1(0x4185f20, 0xc000d2d470, 0xc002449600)
	/go/src/github.com/rancher/rancher/server/responsewriter/content.go:33 +0x93
net/http.HandlerFunc.ServeHTTP(0xc000b0b4e0, 0x4185f20, 0xc000d2d470, 0xc002449600)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/rancher/rancher/server/responsewriter.Gzip.func1(0x419ae20, 0xc002612620, 0xc002449600)
	/go/src/github.com/rancher/rancher/server/responsewriter/gzip.go:40 +0x1d2
net/http.HandlerFunc.ServeHTTP(0xc000b0b500, 0x419ae20, 0xc002612620, 0xc002449600)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00062c1c0, 0x419ae20, 0xc002612620, 0xc002449600)
	/go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/rancher/rancher/pkg/dynamiclistener.httpRedirect.func1(0x419ae20, 0xc002612620, 0xc002449400)
	/go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:506 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000954000, 0x419ae20, 0xc002612620, 0xc002449400)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0x419ae20, 0xc002612620, 0xc002449400)
	/go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:436 +0x101
net/http.HandlerFunc.ServeHTTP(0xc000954040, 0x419ae20, 0xc002612620, 0xc002449400)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc0015f1790, 0x419ae20, 0xc002612620, 0xc002449400)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc002d3ba40, 0x41a4320, 0xc0023ae580)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5

**Comment by tannh** [comment]
No anyone have idea ???

**Comment by mrajashree** [comment]
@tannh are you also using a single node cluster? @donatasnicequestion and @tannh have you tried the 2.2.8 version?

**Comment by donatasnicequestion** [comment]
we user single node rancher deployment (upgraded up to 2.2.8). 
 The bug ist reproducible also with 2.2.8. at our environment.

**Comment by mrajashree** [comment]
This issue isn't reproducible, the fix is to avoid panic and add error message to indicate what exactly fails, so on trying 2.3.4 we get an idea of where the error is from. Assigning it to @maggieliu based on discussion with @deniseschannon instead of to QA.

**Comment by maggieliu** [comment]
@donatasnicequestion @tannh would you mind testing and see if you can reproduce with a new RC?

**Comment by donatasnicequestion** [comment]
@maggieliu thanks for your efforts. I tested this issue with a new RC v2.3.4-rc4:

Step 1. configure LDAP. Log entry
```
..
 [INFO] Updating user user-rvg8v. Adding principal ist displayed.
..
```

Step 2. Select a Radio "Allow members of cluster etc." and start entering a Group into "Authorized Users and organisations"

Error in a log shows up on each keystroke:
```
...
[ERROR] Unknown error: [SearchPrincipals] no authProvider specified in token `
...
```

**Comment by sangeethah** [comment]
Tested with latest image `v2.3-head`  version  ` 565ef1a85`.

1. Configure openLdap authentication.
2. Able to search and add groups to "Allow members of Clusters, Projects, plus Authorized Users and Organizations" in "Site Access" section.

**Comment by soumyalj** [comment]
Tested with rancher v2.3-head (image 772124c841ee)

1. Configured open LDAP in the setup.
2. "Search Filter" field option is presented for User and Groups in "Customize Schema" section. Users have the option to set these fields when OpenLdap auth is enabled. When the field is set , this filter gets applied to the list of users/groups that get searched when adding users to add members to cluster/projects.
3. Able to search and add users/groups to "Allow members of Clusters, Projects, plus Authorized Users and Organizations" in "site access"
