### ISSUE TITLE
Cannot filter catalog apps by catalog or category

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20163]
Version: v2.3.0-alpha1

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Launch global apps. Try to filter by categories drop-down
- Add a catalog such as https://github.com/mrajashree/charts.git (mcapp branch). Try to filter by catalog drop down to just this mcapp chart.

**Result:**
You cannot  filter by any category or catalog on the app launch page. This happens on either global (Multi-Cluster Apps) or apps at project level.

There are no errors in the browser dev console, nor are there any exceptions. If you tell browser dev tools to break on any exceptions none will occur. I also do not observe any issues in Rancher logs.

**Other details that may be helpful:**
Issue does not happen to me on v2.2.3-rc8

**Environment information**
Issue has been observed on both HA and non-HA rancher setups running  v2.3.0-alpha1

**Comment by loganhz** [comment]
This part has been refactored in master-head. Please try again

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/12/19)

I can confirm after the refactor (refactor in general already has been tested) that we can now sort by category without any issues. I enabled helm stable and incubator and any/all categories work and filter as expected. I also added my own chart with custom categories and this works correctly as well.

I could not identify any issues.
