### ISSUE TITLE
Custom Metrics & Cluster Monitoring

### ISSUE THREAD

**Issue by DJAyth** [rancher/rancher#20160]
**What kind of request is this (question/bug/enhancement/feature request):**

Possible bug

**Steps to reproduce (least amount of steps as possible):**

1. Install Rancher 2.2.2 via rke
2. Create second cluster.
3. Use example steps to enable custom metrics:
https://gist.github.com/superseb/4147cbbe432d11b63e3a4432d12df2b7
https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/horitzontal-pod-autoscaler/
4. Confirm custom metrics work.
5. Enable cluster monitoring.

**Result:**

The built in cluster monitoring will not get setup right, and it actually seems to break the custom metric setup

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher:2.2.2

- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider - Openstack
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud - 2CPU, 8GB RAM
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14231
