### ISSUE TITLE
insecure robohash

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2016]
When accessing rancher server UI over SSL, I get a warning about there being unsecure content on the page. A closer look reveals that most content is indeed served over HTTPS with the exception of the ugly  robohash image (browsed their site now, and see I'd prefer another set, but that's just me, I guess..:p), for no particular good reason, as they serve it just as well over https too.

Ps. using gravatar could be a nice alternative, as well as using the image from LDAP.

**Comment by ibuildthecloud** [comment]
I agree the robohash is ugly and should be https.  @hibooboo2 do you have access to the email address?  If so gravatar would be immensely better.

**Comment by hibooboo2** [comment]
rancher/cattle#859 made this a setting with the default being gravatar identicons.

**Comment by kaos** [comment]
Nice :)
