### ISSUE TITLE
Error while trying to add windows node in a cluster with multiple control nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20178]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Have a cluster - 3 nodes - All roles. (custom cluster)
2. add a windows node to the cluster

**Expected Result:** 
windows node should get added successfully to the cluster

**Actual Result:** 
Failed to register the windows node. Error seen:
<img width="982" alt="Screen Shot 2019-05-11 at 5 09 11 PM" src="https://user-images.githubusercontent.com/26032343/57578252-3145dd00-743d-11e9-802d-7ac111f58314.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0-alpha1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom Azure
- Kubernetes version (use `kubectl version`):

```
1.14.1
```

**Comment by cjellick** [comment]
available in master and `v2.3.0-alpha2`

**Comment by sowmyav27** [comment]
Verified on `v2.3.0-alpha2`

Deployed a cluster with 3 linux nodes - `All Roles`, 2 windows worker nodes - Custom type -Azure. (verified on a HA setup)
Was able to successfully bring up the cluster and deploy workloads.
