### ISSUE TITLE
SSL certificate without a common name breaks various things

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#2018]
I'm using a self-signed SSL cert to secure communications between Cloudflare and my own host.

If I create a self-signed cert without a common name, various things break. First, no error appears to be displayed. Next, the Certificates screen fails to load so I can investigate the situation. Finally, I see no certificates listed in my load balancer. Ultimately I had to delete the cert from MySQL, at which point I successfully added a self-signed cert with a cn. It's fine to require a cn, it'd just be great to recover nicely from this error. :)

This is under 0.37-rc1.

Thanks.

**Comment by ibuildthecloud** [comment]
@alena1108 sounds like a good thing to validate.  I think we were mostly under the assumption a cert with no CN wasn't valid.

**Comment by ibuildthecloud** [comment]
@ndarilek if you happened to have a cert and key you'd like to share of a dummy cert with no CN we can use that as test data and add it to our automated tests.

**Comment by alena1108** [comment]
Not sure if we should reject certificates without CN as openssl for instance allows you to generate cert without this field, and haproxy doesn't bail either. I guess by now we just have to fix the UI so it doesn't break when CN is not set.

**Comment by aruneli** [comment]
```
Component 	Version
Rancher 	v0.40.0-rc1
Cattle 	v0.96.0
User Interface 	v0.53.0
Rancher Compose 	beta/latest
```
UI allows to upload a cert with no CN and same could be assigned to a LB
