### ISSUE TITLE
Can not create k8s cluster in China north west region

### ISSUE THREAD

**Issue by jack-yu-matrix** [rancher/rancher#20188]
----
error log
----
2019/05/13 06:21:25 [ERROR] NodeController c-vmb7x/m-x9dgd [node-controller] failed with : Error with pre-create check: "RequestError: send request failed\ncaused by: Post https://ec2.cn-northwest-1.amazonaws.com/: dial tcp: lookup ec2.cn-northwest-1.amazonaws.com on 20.12.0.2:53: no such host"
2019/05/13 06:21:25 [INFO] Generating and uploading node config
2019/05/13 06:21:25 [ERROR] NodeController c-vmb7x/m-mxdnc [node-controller] failed with : Error with pre-create check: "RequestError: send request failed\ncaused by: Post https://ec2.cn-northwest-1.amazonaws.com/: dial tcp: lookup ec2.cn-northwest-1.amazonaws.com on 20.12.0.2:53: no such host"
2019/05/13 06:21:25 [INFO] Generating and uploading node config
2019-05-13 06:21:25.837451 W | etcdserver: 80% of the file descriptor limit is used [used = 842, limit = 1024]
2019/05/13 06:21:25 [ERROR] NodeController c-vmb7x/m-wdwwp [node-controller] failed with : Error with pre-create check: "RequestError: send request failed\ncaused by: Post https://ec2.cn-northwest-1.amazonaws.com/: dial tcp: lookup ec2.cn-

**Comment by loganhz** [comment]
@jack-yu-matrix which version are you suing?

**Comment by jack-yu-matrix** [comment]
latest stable

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19379
