### ISSUE TITLE
Monitoring app get redeployed when have system-default-registry configured

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20186]
rancher/rancher:v2.2.2

Steps:

1. Configure system-default-registry in global setting
2. Create a RKE cluster and enable cluster monitoring

Results:

It will keep generating config maps in cattle-prometheus namespace time by time

Workaround:

We can workaround it by setting the private registry in monitoring custom answers `global.systemDefaultRegistry = xxx`

![image](https://user-images.githubusercontent.com/21168270/57598775-11223500-7587-11e9-8570-bb4d370c0152.png)

**Comment by cjellick** [comment]
I guess this one also needed the etcd sorting fix? That pr referenced this issue as well. i merged, so moving over

**Comment by cjellick** [comment]
fixed in master

**Comment by jiaqiluo** [comment]
The bug fix is validated on master 5/31

Following the same steps as the ticket describes the cluster-monitoring app does not redeploy and there are no revisions of the config map.
