### ISSUE TITLE
Questions rendering problem. Dictionaries in list's rendered as empty dictionary

### ISSUE THREAD

**Issue by Razikus** [rancher/rancher#20189]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
[badchart.tar.gz](https://github.com/rancher/rancher/files/3171658/badchart.tar.gz)

Download chart above

Add this chart to your git repository

Deploy this chart. 
Value deployment[0].containers[0].containerPort.value is missing, why? 
It inside values.yaml, not referenced by questions.yaml, so it is somehow rendered as empty dictionary

Add answer by yourself as follow
```
'deployment[0].containers[0].nodePort': '31397'
'deployment[0].containers[0].containerPort': '80'
```

It works.

Probably when rendering the sub-list-dictionaries are rendered as empty?

Values.yaml:
```
deployment:
- containers:
  - containerPort: 
      value: 80
    nodePort: 31397
```

Rendering:
```
containerPort: {{ (index (index .Values.deployment 0).containers 0).containerPort.value }}
```

![chrome_2019-05-13_10-14-49](https://user-images.githubusercontent.com/12664801/57605914-102ddb00-7568-11e9-8d35-3a34e4463575.png)

In more complex examples:
![chrome_2019-05-13_11-04-18](https://user-images.githubusercontent.com/12664801/57609321-ecba5e80-756e-11e9-972e-607739f6c3eb.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v.2.1.8
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted

**Comment by Razikus** [comment]
Probably refers to this problem:

https://github.com/helm/helm/issues/5711

**Comment by RRadziejewski** [comment]
I also have the same problem with this i think we should somehow poke @cjellick to look at this.

**Comment by daxmc99** [comment]
Looks to be an issue with the helm parser. I will monitor https://github.com/helm/helm/issues/5711 to see if we can upstream our helm version when this is fixed.

**Comment by Razikus** [comment]
In rancher v2.2.1 problem still exists, but questions have other rendering behavior
Workaround - set all questions to all values.yaml :(

**Comment by RRadziejewski** [comment]
Guys some concrete info which versions already are handling it ?
This is real pain in the ass

**Comment by vkim-rogers** [comment]
> Looks to be an issue with the helm parser. I will monitor [helm/helm#5711](https://github.com/helm/helm/issues/5711) to see if we can upstream our helm version when this is fixed.

Hi @daxmc99 ,

That issue already resolved in the upstream.
Can you please include the fix into the Rancher's helm ?

Thank you!
