### ISSUE TITLE
Assiging roles to Keycloak users without prior login

### ISSUE THREAD

**Issue by m-wcislo** [rancher/rancher#20193]
**What kind of request is this: question**
Rancher/rancher:v2.2.2

Hi, 
I'm creating automation (ansible) to configure Rancher with Keycloak. In general everything works fine, and users from Keycloak can login into Rancher. I'm configuring Keycloak auth in rancher using REST API. 

The problem I have is that I'd like to add one of  the Keycloak users as project/cluster member as a part of this automation. Which seems to be not possible when using local user (admin) to do that, because the target user (from Keycloak) is not present on Rancher side until first login.

I tried adding user using REST API with principal keycloak_user:... but it is not working. Principals itself cannot be created via REST API from what I know either.

Is there any way to achieve assigning cluster/project membership to keycloak user without having user login beforehand? 

MW.

**Comment by vincent99** [comment]
Principals are not a "real"/persisted resource, they're more like the ephemeral results of searching the provider (+ yourself).  You don't need to make a user to add them.  One will be created when they login.

Create a `projectRoleTemplateBinding` for 
```javascript
{
  "projectId": "p-abcde",
  "roleTemplateId": "project-member",
  "userPrincipalId": "keycloak_user://..."
}
```

(or similar for cluster)

**Comment by m-wcislo** [comment]
I tried creating clusterRoleBinding:
```
{
	"clusterId": "local",
	"roleTemplateId": "cluster-member",
	"userPrincipalId": "keycloak_user://some.user@domain"
}
```

but getting:
```
{
	"baseType": "error",
	"code": "ServerError",
	"message": "user.management.cattle.io \"some.user@domain\" not found",
	"status": 500,
	"type": "error"
}
```
This works only with local:// users. Just to mention I'm performing those as local admin.

**Comment by m-wcislo** [comment]
@vincent99 any comments on the above error?

**Comment by fsdaniel** [comment]
@m-wcislo Im a bit late to this the way i solved this was to use groups as you can add groups ahead of time without knowing users. The group permissions you CAN set in rancher.

Passing groups from keycloak means you can have people login into the right  projects ahead of time

Sample curl code for adding group to allow cluster management for 1 cluster:

```
curl -u "rancher-token:rancher-secret" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"type":"clusterRoleTemplateBinding","clusterId":"RANCHER_CLUSTER_ID","groupPrincipalId":"keycloak_group:///GROUPNAME","roleTemplateId":"cluster-member"}' \
'https://HOSTNAME/v3/clusterRoleTemplateBindings'
```

Ofcourse changing roletemplateid and more will mean you can do it on project scope also.

Hope it helps.
