### ISSUE TITLE
Pipeline applyyaml CRD

### ISSUE THREAD

**Issue by sauber** [rancher/rancher#20195]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Install kube-prometheus operator in cluster
* Create servicemonitor.yaml in git repository:
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-metrics
spec:
  selector:
    matchLabels:
      app: myapp
  endpoints:
  - port: metrics-port
* Create .rancher.pipeline.yml in git repository:
stages:
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./servicemonitor.yaml
timeout: 60
notification: {}
* Setup and execute pipeline

**Result:**
 09:53:51 from server for: “./servicemonitor.yaml”: servicemonitors.monitoring.coreos.com “app-metrics” is forbidden: User “system:serviceaccount:p-9h7jb-pipeline:jenkins” cannot get servicemonitors.monitoring.coreos.com in the namespace “p-9h7jb-pipeline”

**Other details that may be helpful:**
Running from command line works fine:
 $ kubectl --as=jenkins -n p-9h7jb-pipeline apply -f servicemonitor.yaml
 servicemonitor.monitoring.coreos.com/app-metrics created

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher 2.1.5, rancher 2.2.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): vSphere, RancherOS
- Kubernetes version (use `kubectl version`): 1.11.5
- Docker version (use `docker version`): 17.3.2

**Comment by gitlawr** [comment]
The build pods are using `jenkins` serviceaccount in the pipeline dedicated namespace. It has `edit` permission inside the project. That's a clusterrole for most native resources generated by kubernetes but it doesn't include CRD resources.

If you want to deploy stuff beyond the default scope, you can grant additional permissions to the `jenkins` service account, for example:
```
kubectl create clusterrolebinding --clusterrole=cluster-owner --serviceaccount=p-sxvhk-pipeline:jenkins custom-crb
```
**NB**: The above is giving `*` permission for `*` resources to the SA. You probably want to use fine-grained roles/rolebindings according to your needs.

**Comment by gitlawr** [comment]
We probably don't want to grant `*` permissions to the SA by default. Privilege escalation happens where project-members can access roles/rolebindings in the project although they should not.

**Comment by sauber** [comment]
Thanks for suggesting. Granting permissions (less that cluster-owner) works.
