### ISSUE TITLE
Metadata /containers returns ALL containers in the system

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2019]
When using the MetaData service, the call to /containers returns ALL containers in the system. It is my understanding, after talking with @ibuildthecloud,  that /containers is supposed to be scoped to the stack. 

To reproduce, create two stacks, each with a service. Launch the services with at least one container in each. Look at the metadata inside the container (using curl) you'll see the containers from both stacks under the "containers" key.

**Comment by deniseschannon** [comment]
Does that mean `/services` should only be services in the one stack?

**Comment by alena1108** [comment]
/containers are scoped to the account, not to the stack. The structure is the following:

```
/stacks - all stacks of your account
/services - all services of your account
/containers - all container of your account
```

You would see the info scoped to your container's stack only under "self" section
```
/stack - your stack
/service - your service
/container - your container
```

If we want to scope on per stack basis outside of the "self" section, the structure should be as follows:

```
/stacks
/stacks/<stackName - optional>/services
/stack/<stackName - optional>/services/<serviceName - optional>containers
```

It would also resolve https://github.com/rancher/rancher/issues/2091

@vincent99 I'm sure there might a better solution to that, let us know what you think

**Comment by alena1108** [comment]
Was resolved with metadata refactoring (v2 metadata). If you need to fetch containers per stack, you would request:

stacks/stackName/services/serviceName/containers

Do it per every service name of stack to fetch all the containers.
