### ISSUE TITLE
Allow to filter workloads by namespace

### ISSUE THREAD

**Issue by Leen15** [rancher/rancher#20196]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
go to workload list of a project and try to search by namespace

**Result:**
no result found

**Other details that may be helpful:**
When you have lots of workloads in a project it's impossible to find something without scroll all the page or use the CTRL-F / CMD-F to find something.
if you have more than 50 workloads you have also to switch between pages.
It should be very helpful if the search box can work also with the namespace name.

Also please add an option to see the namespace name in the "node view" of the workload.
if you have multiple workspaces with a service named "web" and you try the node view you cannot understand every workload what it is.

**Environment information**
Rancher HA, v 2.2.2

**Comment by fabn** [comment]
This would be very useful also for situations like these:

![image](https://user-images.githubusercontent.com/324213/61313180-3c7d0680-a7fa-11e9-8e74-0c49d00950d7.png)

Otherwise it's impossibile to choose the correct option.

**Comment by loganhz** [comment]
the original issue has been fixed in master (2.3).

For the `Alias of another DNS records's` issue will be addressed in https://github.com/rancher/rancher/issues/20484

**Comment by denniss17** [comment]
We are running Rancher 2.3.3 and this issue is not fixed? At least I dont see how I can filter workloads on namespace
