### ISSUE TITLE
Concurrent requests to same machine resource does not update

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#202]
I am not 100% sure what the root cause of this and will update this if I can figure it out.  The sequence of events that caused this for me was:

- in go-machine-server, there is an API update to machine resource to add the "machineDir" parameter within the data field.
- On a separate go routine, there is a ticker that is periodically sending transitioning messages for the same machine resource.  If this updates too close to the previous machine update, "machineDir" never gets added or gets clobbered.

**Comment by will-chan** [comment]
If you submit multiple requests to create events, the same thing happens.

- Reply event 1
- Reply event 2

Only event 1 gets updated while event 2 seems to be ignored/dropped.  If I put a sleep in between the two events will event 2 get updated.

**Comment by cjellick** [comment]
@will-chan any chance that this and #203 are relate?

**Comment by vincent99** [comment]
@will-chan @cjellick Was this resolved by doing `+data`?

**Comment by cjellick** [comment]
Ping @will-chan we can close this?
