### ISSUE TITLE
vSphere Node vApp options not sticking

### ISSUE THREAD

**Issue by alexholliz** [rancher/rancher#20209]
**What kind of request is this (question/bug/enhancement/feature request): Bug**

**Steps to reproduce (least amount of steps as possible):**

- Create a Network Protocol Profile associated with your desired network with a pool of IPs for vApps to be assigned
- Create vsphere node template
- Fill out all fields as appropriate, set the network to the network that your network protocol profile is associated with, and leaving Host field blank for DRS enabled cluster
- Click the radio button under vApp options: Use vApp to configure networks with network protocol profiles
- Save Node Template

**Result:**
Nodes do not deploy with IP from the range specified, they default to DHCP

**Other details that may be helpful:**
I have attempted to modify the Network Protocol Profile to remove DHCP, as well as several redeployments of nodes from new templates and the result is the same. I also tried to "Provide a custom vApp config" and fill out the three present fields with:

- com.vmware.guestInfo
- IPv4
- fixedAllocated

Which did not work. I also tried to fill out the interface 0 details as represented in this issue: https://github.com/rancher/rancher/issues/15817
![image](https://user-images.githubusercontent.com/273599/57654370-9d3d5800-7599-11e9-9924-eaadf48989fb.png)

That also did not work. Checking the node in the API, it looks like those options aren't being set at all. When I open the edit page for the node template, it's defaulted back to "Do no use vApp".

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
![image](https://user-images.githubusercontent.com/273599/57654711-792e4680-759a-11e9-9758-df3bfd20f3b6.png)

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type: Infrastructure Provider: vSphere
- Machine type: VM 
- Specifications: 8 vCPU 4GB memory
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by infraATE** [comment]
Hello,
same problem here. 
I tried the version 2.2.3 of Rancher and the page is always defaulted back to "Do no use vApp".
Since this option is the best way to provide static IP to vSphere nodes i want use it instead using DHCP.
Thanks.

**Comment by alexholliz** [comment]
Looks like we're not the only ones, some comments in this issue: https://github.com/rancher/rancher/issues/19166 indicate that the vApp configuration isn't sticking when trying to use cloud-init; though I am thinking it's because cloud-init is being used by default: https://github.com/rancher/rancher/issues/19166#issuecomment-485866178

**Comment by alexholliz** [comment]
@infraATE I do not use cloud-init for my templates at all, I leave that section of the Node Template config blank.

**Comment by infraATE** [comment]
@alexholliz, you're right, I tried without cloud-config and... Same problem, my template is alway defaulted back to "Do no use vApp". 
It seems that our issue is note cloud-config related. :(

**Comment by alexholliz** [comment]
I dug through the logs a bit the last couple days, and it looks like configuration with cloud-init is attempted even when the field is left blank. So this may be a problem of cloud-init being used and preventing the vApp option from ever kicking in.

**Comment by ivanfilippov** [comment]
I can confirm this is affecting me as well. It doesn't seem to be a UI bug like the Network field being blank yet still showing in the Rancher API from a few releases back.

**Comment by janeczku** [comment]
@ivanfilippov could you share some details on the issue you are seeing as well as your environment (Rancher version, vSphere version) and the configuration of your node template? TY

**Comment by alexholliz** [comment]
This is working in vSphere 6.7u3. Just upgraded my ESXi hosts and vCenter instance.

**Comment by terafirmanz** [comment]
Anyone tried this in 2.3? I had 2.3 and vApp turned off all working fine then when I turned vApp option on now all clusters are provisioned with no NIC on the node VMs. Turning vApp off again does not put fix it neither does recreating templates.

**Comment by virtuman** [comment]
Here's what worked for me on 2.3.3:

1. Specifying vSphere folder resulted in error that VM could not be found
2. Rancher generated full path to network in vApp options: ${dns:/ru-mo-dc01/network/dmz1 (vlan 32 - 10.255.32.0)}  I noticed that old VMs didn't have full path to network specified and removed /ru-mo-dc01/network/ from vApp valus, so it ended up like this: ${dns:dmz1 (vlan 32 - 10.255.32.0)} 

after these changes, VM got created successfully, not sure if it is a bug or some sort of feature that my vSphere 6.5 is lacking.

**Comment by bmdepesa** [comment]
We are unable to fully test this in our vSphere test environment, but I will update with our test steps after they have been completed.

@ivanfilippov @terafirmanz can you attempt this with `rancher/rancher:v2.3.6-rc6`?

**Comment by DH-Rancher** [comment]
Tested on 2.3.6-rc6

Created a Network Policy:

![image](https://user-images.githubusercontent.com/57356014/77758248-845f5900-702a-11ea-8b0b-75178945deb5.png)

Added the following into a node template:

![image](https://user-images.githubusercontent.com/57356014/77758297-9b9e4680-702a-11ea-84de-2f1fd09059c8.png)

format of the netmask and gateway is var:portGroupName (in my case, my port group is VDS-MGMT-DEFAULT)

vSphere shows the properties being passed:

![image](https://user-images.githubusercontent.com/57356014/77758519-02236480-702b-11ea-8dd8-34cc0704daed.png)

Run either vmware-rpctool `info-get guestinfo.ovfEnv` vmtoolsd --cmd or `info-get guestinfo.ovfEnv` on the deployed VM:


```
david@test1:~$ vmware-rpctool 'info-get guestinfo.ovfEnv'
<?xml version="1.0" encoding="UTF-8"?>
<Environment
     xmlns="http://schemas.dmtf.org/ovf/environment/1"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns:oe="http://schemas.dmtf.org/ovf/environment/1"
     xmlns:ve="http://www.vmware.com/schema/ovfenv"
     oe:id=""
     ve:vCenterId="vm-5339">
   <PlatformSection>
      <Kind>VMware ESXi</Kind>
      <Version>6.7.0</Version>
      <Vendor>VMware, Inc.</Vendor>
      <Locale>en</Locale>
   </PlatformSection>
   <PropertySection>
         <Property oe:key="guestinfo.interface.0.ip.0.address" oe:value="172.16.10.119"/>
         <Property oe:key="guestinfo.interface.0.ip.0.netmask" oe:value="255.255.255.0"/>
         <Property oe:key="guestinfo.interface.0.route.0.gateway" oe:value="172.16.10.1"/>
   </PropertySection>
   <ve:EthernetAdapterSection>
      <ve:Adapter ve:mac="00:50:56:bb:23:ae" ve:network="VDS-MGMT-DEFAULT" ve:unitNumber="7"/>
   </ve:EthernetAdapterSection>
</Environment>
```

So initial signs are looking good. The only last piece of the puzzle is to extract the OVF properties and actually apply them to the guest OS. I'm not sure if vmtools can do this by default or if some custom scripting needs to be applied to do so.

**Comment by DH-Rancher** [comment]
By leveraging some bash scripting and cloud-init, I've had sucsess in configuring the host OS based on the vApp parameters set within Rancher. I've used the following for the cloud-config section as a test:

```
#cloud-config
write_files:
  - path: /root/test.sh
    content: |
        #!/bin/bash
        vmtoolsd --cmd 'info-get guestinfo.ovfEnv' > /tmp/ovfenv
        IPAddress=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.address" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
        SubnetMask=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.netmask" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
        Gateway=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.route.0.gateway" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)

        cat > /etc/netplan/01-netcfg.yaml <<EOF
        network:
          version: 2
          renderer: networkd
          ethernets:
            ens160:
              addresses: 
                - $IPAddress/24
        EOF

        sudo netplan apply
runcmd:
  - bash /root/test.sh
```

**Comment by deniseschannon** [comment]
Based on this feedback, it's possible to configure the vApp using cloud-config.
