### ISSUE TITLE
Monitoring not working correct when using AWS cloud provider

### ISSUE THREAD

**Issue by rdu** [rancher/rancher#20200]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a cluster with with aws as cloud provider. Node size and count does'nt matter. (all spotinstances for testing purposes)
Enable monitoring once the cluster is ready.

**Result:**
Monitoring the pods and workloads seems to work correct. Monitoring the nodes is available for one node only (it seems to be randomly choosen). All the other nodes does not appear in grafana. On the node page it never shows metrics. For exactly one node it works
The cluster overview page in rancher shows wrong results - it shows for example only the RAM for the one working node.
The same is in grafana. If I try to switch the node in grafana only one node is displayed.

**Other details that may be helpful:**
It seem to work with other cloud environments. (I used hetzner without problems).
I noticed for hetzner the node name is based on pool name with a number.
AWS nodes are named in the scheme IP-XX-XX-XX-XX. Maybe this could cause some trouble?
All system pods runs flawless. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher 2.2.2 
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
AWS cloud provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud 4/15
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
18.6.1
```
OS:
RancherOS

**Comment by rdu** [comment]
Upgrading to v2.2.3 does not fix the problem.
Disableing and reenableing monitoring does not solve it.

**Comment by loganhz** [comment]
Could you check if this help https://github.com/rancher/rancher/issues/19187 ?

**Comment by rdu** [comment]
Hi,

this resolved my issue.

Thank you very much.

This can be closed now.
