### ISSUE TITLE
Backport: Support for North Central US in AKS 

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20203]
Backport rancher/rancher#19853

**Comment by davidnuzik** [comment]
Version: v2.2.4-rc1

I can confirm the addition of "North Central US" region for AKS.
![image](https://user-images.githubusercontent.com/45179589/57735756-932f5e00-765a-11e9-885a-5a37cab067a4.png)

The query to aksVersions looks correct and the cluster config looks good as well (azureKubernetesServiceConfig) I see `location: "northcentralus"` in the cluster creation request and in the API.

My AKS cluster with this Location provisioned successfully and shows as the correct location in Azure web console.

The original issue mentions West Central US support as well and this is tracked separately in #20069 as it is not yet available.
