### ISSUE TITLE
Not able to see any revisions for the apps.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#20204]
Rancher server version - v2.2.2-patch1-rc2

Steps to reproduce the problem:
Create cluster1 as admin user.
Add a regular user as cluster owner.
Log in as this regular user and deploy app in any project in cluster1.
Once the app is deployed , user is not able see the revisions of this app when launching the "Rollback" view for the app.

Note - User is able to upgrade apps successfully . He is just not able to see the revisions of this app.

This behavior is also seen for a project owner.

**Comment by kinarashah** [comment]
Note: not a regression, present in 2.1.x versions too

**Comment by bmdepesa** [comment]
rancher/rancher:master-head bc3700f8

* Create cluster1 as admin user.
* Add a regular user as cluster owner.
* Deploy an app as admin
* Log in as this regular user and deploy app in any project in cluster1.
* User is able to view revisions in both apps
