### ISSUE TITLE
Metadata service can be called before resolv.conf updated

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2020]
While building a confd container, the first time the container is started, it gets the following error:

```
ERROR Get http://rancher-metadata/2015-07-25/self/service/containers: dial tcp: lookup rancher-  metadata on 192.168.1.1:53: no such host
```

If the container is restarted, it resolves fine. 

To reproduce, you could create a shell script that immediately calls the metadata service. This environment is on my laptop in a VBox setup.

Services are created and scaled up from the UI.

**Comment by vincent99** [comment]
`/etc/resolv.conf` isn't populated yet?

**Comment by cloudnautique** [comment]
yeah that appears to be the case.

**Comment by vincent99** [comment]
@cloudnautique This should work now.. in 1.0.0-rcX

**Comment by LLParse** [comment]
Launched 100 containers hitting the metadata service on entrypoint, no communication issues.

https://github.com/LLParse/community-catalog/tree/issue-2020-test/templates/issue-2020
