### ISSUE TITLE
[Windows] Persistent volume failed to be provisioned using Azure File/Disk with storage class in a cluster with multiple control plane nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20207]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a custom cluster - Azure with 3 nodes - All roles - linux, 2 windows worker nodes
2. Use Azure Cloud provider while setting up the cluster.
3. register the nodes using the agent command
4. Add a storage class - for Azure File/Azure Disk.
5. Go to a project - default--> Volumes. And Add Volume.
6. Enter a name, select storage class created in step 4. 
7. Click on create.

**Expected Result:**
Volume should be provisioned successfully.

**Actual Result:**
Azure File error:
```
Failed to provision volume with StorageClass "testnew": could not get storage key for storage account sowmyateststorage: could not get storage key for storage account sowmyateststorage: storage.AccountsClient#ListKeys: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=MinLength value="" details: value length must be greater than or equal to 1
```
Azure Disk Error:
```
Failed to provision volume with StorageClass "disk-test": compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="" Message="No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/14a619f7-a887-4635-8647-d8f46f92eaac/resourceGroups/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-f3e6d553-75bf-11e9-b5c6-000d3a5953be?api-version=2018-06-01'."
```

**Note:**
This works in a cluster having 1 node - All roles, linux, and 1 windows worker node.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.3.0-alpha2`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.14.1
```

**Comment by alena1108** [comment]
@sowmyav27 : @sangeethah mentioned that the use case works when the setup has a single control node. Can you share the details of the working setup please (number of nodes, their roles, etc)

**Comment by sowmyav27** [comment]
verified on `rancher:master`. latest - 06/06/2019
**Steps taken:**

1. Create a custom cluster - Azure with 3 nodes - All roles - linux, 1 windows worker nodes
2. Use Azure Cloud provider while setting up the cluster.
3. register the nodes using the agent command
4. Confirm if the permissions are avialable in the cluster --kubectl on the cluster

```
k get sa persistent-volume-binder -n kube-system
k get clusterrole system:azure-cloud-provider -n kube-system
k get clusterrolebinding system:azure-cloud-provider -n kube-system
```
5. Import yaml file in System project - under workloads. 
6. Add a storage class - for Azure File/Azure Disk.
7. Go to a project - default--> Volumes. And Add Volume.
8. Enter a name, select storage class created in step 4.
9. Click on create. Volumes were created . And workloads with the volumes were deployed successfully.

I could not reproduce the issue. Closing it.
