### ISSUE TITLE
Support feature flags

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#20213]
Will add more context around what to test tomorrow (7/3)
**NOTE:** Will not be able to test this until it is used on an actual feature

Features are interacted with via the API like any other CRDs. For example, if you want to disable a feature then you would make a put request for that feature with the value set to false. Example requests can be found in the steps section.

Behaviors to consider:

- Schemas associated with a feature should not be visible on /v3/schemas or /v3/schemas/feature-name when feature is disabled.

- Any functionality associated with the feature should not work when the feature is disabled. For example, if the feature was for the entirety of kontainer drivers, then making a new kontainerDriver CRD should not cause a driver installation.

- API v3 API endpoints associated with the feature should be block

- On HA, feature status should be synced across all management nodes.

- No user should be able to create or delete features.

- All users should be able to list, get, watch features.

- Admin users should be able to update features.

**Steps for interacting with feature flags (assuming feature is enabled by default):**
1.	show local cluster

2.	check /v3/schemas
(you should see the features schema)

3.	curl -k -u _token_ -X GET -H 'Content-Type: application/json' https://_rancherurl_/v3/features
(should list all the features including the one in question)

4.	feature should be enabled and work

5.	curl -k -u  _token_ -X PUT -H 'Content-Type: application/json' -d '{"value":false}' https:///_rancherurl_/v3/features/feature-name

6.	feature should be disabled and not work

7.	check /v3/schemas
(should not be able to see schema)

8.    check /v3/schemas/schema-name
(should say schema is disabled)

can change feature defaults when running rancher using the feature flag like so:
`--features=feature-name=false`

or have the `CATTLE_FEATURES` environment variable set to `feature-name=false`

Developing with features flags (might not need this but just in case):
https://rancher.atlassian.net/wiki/spaces/EN/pages/87556097/Developing+with+Feature+Flags

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4.0-rc1

* Tested in both HA and single-node installs
* Tested feature flags for istio UI features, and steve
* Features can be enabled/disabled through API, flags when starting Rancher server, and through the UI
* Features can not be created/deleted
* Only admins can edit feature flags
