### ISSUE TITLE
Web Parameter Tampering on /login?errorMsg

### ISSUE THREAD

**Issue by MauroEldritch** [rancher/rancher#20216]
**What kind of request is this (question/bug/enhancement/feature request):** Enhancement

**Steps to reproduce (least amount of steps as possible):**

- Access the following endpoint on any Rancher instance up to 2.1.4: https://RANCHER:PORT

/login?errorMsg=%68%74%74%70%73%3a%2f%2f%77%77%77%2e%6f%77%61%73%70%2e%6f%72%67%2f%69%6e%64%65%78%2e%70%68%70%2f%57%65%62%5f%50%61%72%61%6d%65%74%65%72%5f%54%61%6d%70%65%72%69%6e%67

**Result:** It will display a link to OWASP Wiki explaining Web Parameter Tampering. 

**Other details that may be helpful:** Tags are effectively filtered. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.4
- Installation option (single install/HA): *

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
N/A
```

- Docker version (use `docker version`): *

```
N/A
```

**Comment by alena1108** [comment]
Based on @vincent99 input, the fix will be a combination of UI and the backend. There's one place the backend sends it that would need to be updated; https://github.com/rancher/rancher/blob/f966203b5eecf98ebdd5c8d8dc255af98f37a11b/pkg/auth/providers/saml/saml_client.go#L279

**Comment by davidnuzik** [comment]
I validated the UI aspect of the fix.

**Replication:**
v2.2.3

- Provision rancher, follow prompts to create password, set server url. Log out.
- Go to https://RANCHERSERVER/login?errorMsg=%68%74%74%70%73%3a%2f%2f%77%77%77%2e%6f%77%61%73%70%2e%6f%72%67%2f%69%6e%64%65%78%2e%70%68%70%2f%57%65%62%5f%50%61%72%61%6d%65%74%65%72%5f%54%61%6d%70%65%72%69%6e%67
Error shows link to the OWASP article (not an href/clickable hyperlink)
![image](https://user-images.githubusercontent.com/45179589/58213833-6efdfd80-7ca8-11e9-9d9d-267e12498a1a.png)
- Any arbitrary content is possible such as /login?errorMsg=tacos%20rule
![image](https://user-images.githubusercontent.com/45179589/58213864-90f78000-7ca8-11e9-88ea-8366d09e376d.png)
- HTML/etc is not rendered
/login?errorMsg=%3C!DOCTYPE%20html%3E%3Chtml%3E%3Cbody%3E%3Csvg%20width%3D%22100%22%20height%3D%22100%22%3E%3Ccircle%20cx%3D%2250%22%20cy%3D%2250%22%20r%3D%2240%22%20stroke%3D%22green%22%20stroke-width%3D%224%22%20fill%3D%22yellow%22%20%2F%3E%3C%2Fsvg%3E%3C%2Fbody%3E%3C%2Fhtml%3E
![image](https://user-images.githubusercontent.com/45179589/58214025-25fa7900-7ca9-11e9-9d27-9d6a769c1a46.png)

**Validation:**
v2.2.4-rc8

I tried the same again to validate. For all cases I only get the generic login error message:
![image](https://user-images.githubusercontent.com/45179589/58214081-53472700-7ca9-11e9-8968-88ef15cc8f9e.png)
