### ISSUE TITLE
[UI] Make Node Templates Friendlier when using RancherOS

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#20210]
When using RancherOS in a Node Template it's not very user friendly on how to configure it properly. It ends up that you have to ZERO out the Docker Install URL for it detect Rancher OS.

I think it would be better to do a couple things:

1) When using a Cloud Provider detect the AMI or IMAGE ID to be RancherOS and set all other settings accordingly
2) Add a RancherOS option to the Docker Install URL dropdown.

This could apply to more than AWS, but that's where I'm currently using them.

**Comment by vincent99** [comment]
Not sure what's happening but that is not supposed to be the case... 

The provisioner downloads and calls the install script if provided:  https://github.com/docker/machine/blob/eae38c196a2e10e4e11cc7b8d6dfe8863fb60519/libmachine/provision/rancheros.go#L121-L128

and the install script is supposed to switch engines to one that matches (maybe there isn't a rancheros engine for the version specified?):  https://github.com/rancher/install-docker/blob/master/18.09.6.sh#L499-L505

**Comment by ekristen** [comment]
Dang. I tested this like 30 times and it kept failing out, but now it is working just fine. Guess user error. 

Thanks for the info @vincent99 that's actually very helpful to know.
