### ISSUE TITLE
Issues with kubelet: Orphaned pod found

### ISSUE THREAD

**Issue by vistalba** [rancher/rancher#20227]
I run into issues with thousends of such log entries in kubelet. I found this because kubelet is using much CPU and I checked the logs.

```
Orphaned pod "017d4c65-6c26-11e9-8013-9600002440c4" found, but volume paths are still present on disk : There were a total of 2398 errors similar to this. Turn up verbosity to see them.
```

How can I resolve this?

**Comment by superseb** [comment]
Can you share a little bit more info on your setup? Especially what you have deployed and more kubelet logging would help too. This also helps in reproducing any issue that you encounter. Maybe https://github.com/kubernetes/kubernetes/issues/60987 has a relation with your issue, we can reopen if you can provide more information on the problem.
