### ISSUE TITLE
rancher升级etcd不健康

### ISSUE THREAD

**Issue by 532126051** [rancher/rancher#20223]
*Describe your issue here*
rancher升级到2.2.2之后etcd集群不正常，组件etcd不健康

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
