### ISSUE TITLE
OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown

### ISSUE THREAD

**Issue by liangkunyou** [rancher/rancher#20226]
*Describe your issue here*
docker  exec -it xxx bash throw error:"OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown"

network type:manage
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.27` Cattle: `v0.183.77` UI: `v1.6.50` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
