### ISSUE TITLE
can't add new worker on existing cluster

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#20232]
[BUG]
rancher 2.2.2
k8s 1.11
custom
single install/non-HA

For whatever reason I suddenly can't add new worker to our existing 80 node cluster thats been running since months (where we add and remove worker every week or so) ...

Following error on the new worker:
`time="2019-05-14T13:41:41Z" level=info msg="Error while getting agent config: invalid response 500: Failed to construct node config. Error: failed to find plan for 10.3.x.x"`

Error on the webui:
`This cluster is currently Updating.
Delete https://10.3.x.x:6443/api/v1/namespaces/default/serviceaccounts/netes-default: can not build dialer to c-q89w5:m-16d45e0c7c90`

I tested with different worker rancher versions, was always the same problem, issue must be on the master.
This is quite a problem.

edit: solution below

**Comment by deniseschannon** [comment]
It seems that in the other use cases, upgrading to k8s 1.13 has solved the issue for them. Would you be able to see if that fixes it for you?

**Comment by superxor** [comment]
I can't just upgrade the whole cluster for testing purposes. Furthermore this is not a k8s issue but a rancher issue, after all adding worker nodes doesn't work.

**Comment by superxor** [comment]
Ok so we upgraded to 1.12 and the issue disappeared.
Clearly a Rancher bug, my assumption was right.

**Comment by bhupfer** [comment]
We have the same issue here with rancher 2.2.3. We can't add new nodes but we are already at the latest kubernetes version 1.13.5 so we cannot upgrade.

Error while getting agent config: invalid response 500: Failed to construct node config. Error: failed to find plan for xxx.xxx.xxx.xxx

**Comment by superxor** [comment]
@bhupfer  Ok maybe I drew the wrong conclusion then. I didn't get anything proper from logs, did you have a look at rancher master logs?

**Comment by bhupfer** [comment]
The rancher logs look similar to our web-ui. We have the repeating error: 

2019/05/28 07:26:45 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10122
2019/05/28 07:26:45 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/05/28 07:26:45 [ERROR] ClusterController c-2kkwc [cluster-provisioner-controller] failed with : Delete https://10.x.x.x:6443/api/v1/namespaces/default/serviceaccounts/netes-default: can not build dialer to c-2kkwg:m-3a4a7d540b79
2019/05/28 07:26:45 [INFO] Provisioning cluster [c-2kkwc]
2019/05/28 07:26:45 [INFO] Updating cluster [c-2kkwc]

It repeats every 5 Seconds.

**Comment by superxor** [comment]
@bhupfer try to make sure that your new worker does not have the same hostname as an existing or prrior existing worker, they always need to have brand new hostnames. try again

**Comment by shmulikah** [comment]
Same here, same log output.

Rancher/K8S Details:
-Rancher server v2.2.3
-Rancher installation type: High availability, K8S v1.11.1
-K8S cluster managed by Rancher: v1.11.3

Worker Node Details:
-OS: Ubuntu 16.04.06, Kernel 4.15
-Docker version: 1.12.6

Please help

**Comment by bhupfer** [comment]
I've tried a total new never used Hostname. The Problem still persists. 

Rancher Agent Log:

time="2019-06-12T06:17:01Z" level=info msg="Error while getting agent config: invalid response 500: Failed to construct node config. Error: failed to find plan for 10.49.194.66"
time="2019-06-12T06:17:06Z" level=info msg="Error while getting agent config: invalid response 500: Failed to construct node config. Error: failed to find plan for 10.49.194.66"

Rancher Log:

2019/06/12 06:22:25 [ERROR] ClusterController c-3kkwc [cluster-provisioner-controller] failed with : Delete https://10.xxx.xxx.xxx:6443/api/v1/namespaces/default/serviceaccounts/netes-default: can not build dialer to c-123wc:m-345a7d540b75
2019/06/12 06:22:25 [INFO] Provisioning cluster [c-3kkwc]
2019/06/12 06:22:25 [INFO] Updating cluster [c-3kkwc]


Rancher Server: 2.2.3
K8s Version: 1.13.5
OnPrem Cluster managed by Rancher. 

Tested OS: 
- Ubuntu 1804
- RancherOS 1.5.1

**Comment by superseb** [comment]
The error is shown when a worker is added while the cluster is unavailable (either in Updating state or where cluster/node-agents are not connected). If you can supply the View in API output for the affected cluster, that would confirm that. 

`can not build dialer to` means that the agent is not connected to Rancher, you can check the logging on that host for the agent container to see whats going on, it might get stuck so deleting it might help to recreate it (if the actual k8s cluster is still healthy). Using the API for that node can help you identify it, use `https://rancher.yourdomain.com/v3/nodes/c-123wc:m-345a7d540b75` for your last log.

If any of you can supply the requested info, I can confirm and change the code to have the worker wait for Cluster in Active state or something else before proceeding.

**Comment by superseb** [comment]
Created https://github.com/rancher/rancher/issues/23253 to add better logging/investigate to prevent node from registering when cluster is not ready. If you encounter this in any other situation, let me know.
