### ISSUE TITLE
Docker quickstart not working. Container doesn't seem to successfully start.

### ISSUE THREAD

**Issue by poppahorse** [rancher/rancher#20233]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Run ```sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher```

**Result:**
`https://localhost` never seems to work, shows `ERR_CONNECTION_REFUSED`.

**Other details that may be helpful:**
Looking in the docker logs > 
[rancher.log](https://github.com/rancher/rancher/files/3178549/rancher.log) it seems to get stuck and repeat..
```
E0514 15:16:15.527602       8 memcache.go:134] couldn't get resource list for management.cattle.io/v3: the server could not find the requested resource
E0514 15:16:15.527931       8 memcache.go:134] couldn't get resource list for project.cattle.io/v3: the server could not find the requested resource
E0514 15:16:15.534570       8 memcache.go:134] couldn't get resource list for management.cattle.io/v3: the server could not find the requested resource
E0514 15:16:15.534884       8 memcache.go:134] couldn't get resource list for project.cattle.io/v3: the server could not find the requested resource
```

**Environment information**
```rancher/rancher                  latest              1d6627a9e2de        11 hours ago        508MB```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
The log attached does not contain the log lines you showed in the issue. Does this still occur? Where are you running the container, and what specifications does the machine have?

Let me know so I can reopen if needed
