### ISSUE TITLE
Console errors when add newline to YAML

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20249]
Version: v2.2.4-rc1

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Launch an app at project level. While configuring, switch to Edit as YAML view.
- Add a new line in the YAML

**Result:**
You will get various console errors as pictured below.
![image](https://user-images.githubusercontent.com/45179589/57722405-36707b00-763b-11e9-850c-ac6aafdc456a.png)

Note, this doesn't appear to actually break/hurt anything from what I can tell.

You can also reproduce by just view/edit yaml in any areas and add a newline.

**Comment by davidnuzik** [comment]
@deniseschannon @tfiduccia where is PR?
Or is this suspected as fixed based on changes in this area and I should test again and see if resolved by something else?

**Comment by deniseschannon** [comment]
yes, @tfiduccia is wonderingif it might already be fixed.

**Comment by davidnuzik** [comment]
Version: master-head (8/2/19)

I launched an app at the project level and while doing so went to the "Edit as YAML" view. I added a newline and still got the JS errors:

![image](https://user-images.githubusercontent.com/45179589/62400445-1793cd80-b534-11e9-86b1-7e80ecee21f7.png)
