### ISSUE TITLE
Backport: Monitoring - the app cluster-monitoring is stuck on installing state

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20248]
Backport https://github.com/rancher/rancher/issues/20166

**Comment by alena1108** [comment]
According to @loganhz https://github.com/rancher/rancher/issues/20166#issuecomment-492075538, we should test it on v2.2.4-rc1

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher:v2.2.4-rc1

Steps:
-  enable and disable the cluster monitoring on several different clusters

Result:
- did not see the state of the `cluster-monitoring` app being stuck on `installing`  anymore
- occasionally saw the following situation, but it goes normal after refreshing the page 
<img width="1489" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57726234-d5997080-7643-11e9-8b28-f71005dfd2b5.png">
