### ISSUE TITLE
When adding imported clusters high rate of 409s on globalrolebinding calls

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#20244]
Version:rancher/rancher:v2.2.2
HA Cluster config:
3x etcd nodes n1-standard-8s. Dual local NVMe drives for etcd wal and data dir.
3x API/Worker nodes n1-standard-4
1x Worker n1-standard-4

Add n1-standard-2 VMs running RKE dind clusters and import into Rancher in batches of 10-15. Observe high rate of http 409 responses. Gets worse over time:
![Screen Shot 2019-05-13 at 4 12 59 PM](https://user-images.githubusercontent.com/1989084/57717545-58183500-7630-11e9-93c5-b75066549f12.png)

**Comment by cloudnautique** [comment]
Reran the test. The first peak is with 3 Rancher server Pods in HA, and the second with a single instance of Rancher server running in an HA setup.
![Screen Shot 2019-05-15 at 3 01 07 PM](https://user-images.githubusercontent.com/1989084/57814043-4796b600-7727-11e9-8ced-adb68c873025.png)

There seems to be something wrong with the way we are handling Global role bindings.

**Comment by deniseschannon** [comment]
Closing in favor of: https://github.com/rancher/rancher/issues/23806
