### ISSUE TITLE
service with sidekick volume-from and link stucks in networking state

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#2025]
Tested with Rancher v0.35.0 release and v0.37.0-rc2 on RancherOS. Service is created by rancher-compose and stucks in networking.

mysql + mysql-storage (sidekick, volumes-from mysql-storage) containers working fine, but apache (sidekick, volumes-from apache-storage, link mysql) + apache-storage stucks in networking state.

***rancher-compose.yml***

    Apache:
      scale: 1
    Apache-Storage:
      scale: 1
    MySQL:
      scale: 1
    MySQL-Storage:
      scale: 1

***docker-compose.yml***

    MySQL:
      name: MySQL
      ports:
      - 3306:3306/tcp
      restart: always
      tty: true
      image: centos/mariadb
      stdin_open: true
      labels:
        io.rancher.sidekicks: MySQL-Storage
      volumes-from:
      - MySQL-Storage
      environment:
      -  MYSQL_ROOT_PASSWORD="password"
    MySQL-Storage:
      name: MySQL-Storage
      tty: true
      command:
      - cat
      image: centos/mariadb
      volumes:
      - /var/lib/mysql
      stdin_open: true
      environment:
      - MYSQL_ROOT_PASSWORD="password"
    Apache:
      name: Apache
      ports:
      - 80:80/tcp
      restart: always
      tty: true
      image: centos/httpd
      stdin_open: true
      links:
      - MySQL:db01
      labels:
        io.rancher.sidekicks: Apache-Storage
      volumes-from:
      - Apache-Storage
    Apache-Storage:
      name: Apache-Storage
      tty: true
      command:
      - cat
      image: centos/httpd
      volumes:
      - /var/www/httpd
      stdin_open: true

**Comment by pwFoo** [comment]
Same configs without link MySQL as db01 to apache works! 

So it's a problem with the link between the MySQL and Apache service. Reproduced with / without the two lines

    links:
  - MySQL:db01

Lines removed works fine. Lines added and it stucks during networking / linking.

**Comment by pwFoo** [comment]
Get it solved! Changed my docker-compose.yml file from 2 services with two data only containers to 2 services with ONE data only container. Result is nearly what I try to get. 

  Storage:
    image: centos
    name: Storage
    tty: true
    command:
    - cat
    volumes:
    - /var/lib/mysql
    - /var/www/html
    stdin_open: true

  MySQL:
    name: MySQL
    ports:
    - 3306:3306/tcp
    restart: always
    tty: true
    image: centos/mariadb
    stdin_open: true
    labels:
      io.rancher.sidekicks: Storage
    volumes-from:
    - Storage
    environment:
    -  MYSQL_ROOT_PASSWORD="password"

  Apache:
    name: Apache
    ports:
    - 80:80/tcp
    restart: always
    tty: true
    image: centos/httpd
    stdin_open: true
    labels:
      io.rancher.sidekicks: Storage
    links:
    - MySQL:db01
    volumes-from:
    - Storage

Will convoy volume plugin make the data only container needless?

**Comment by tsilenzio** [comment]
+1

I have the same issue with my setup

```
data:
    image: tsilenzio/base
    stdin_open: true
    tty: true
    command:
        - cat

postgresql:
    image: tsilenzio/postgresql

phpfpm:
    image: tsilenzio/phpfpm
    labels:
        io.rancher.sidekicks: data
    links:
        - postgresql
```

If I remove the ```postgresql``` link or the ```data``` sidekick label, then it will work as expected

**Comment by romanoaugusto88** [comment]
FYI: I've got the same issue here but was solved by upgrading rancher to v0.38.
Same approach: Only one data volume consumed by another using sidekicks.

**Comment by deniseschannon** [comment]
Yes, this was an issue in v0.37.0 and fixed in v0.37.1+.

**Comment by pwFoo** [comment]
A service with one data container an two app containers (apache, sshd) works, but they not share the same data container!

To get it work the data only container have to be the primary service and sshd / apache added as sidekick, but apache and sshd should be reachable by loadbalancer! As sidekicks that wouldn't work...

Is there a way to get it work with data only container as sidekick of sshd / apache? Another way could be convoy (share a convoy volume), but convoy volume plugin isn't added to RancherOS yet.

**Comment by deniseschannon** [comment]
@pwFoo Your use case is probably an enhancement request. Could you make a new issue laying out your use case (like above) as an issue?
