### ISSUE TITLE
Rancher cluster monitorings prometheus-config-reloader in crash-loop due to mismatch of config name in secret

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#20252]
**What kind of request is this (question/bug/enhancement/feature request):**

bug 

**Steps to reproduce (least amount of steps as possible):**

* Install Rancher v2.2.1 HA via Helm chart on a managed cluster
* Enable one or more "notifiers" on the newly imported Rancher Server cluster (without necessarily enabling monitoring)
* Upgrade to v2.2.2 via Helm chart 

**Result:**

* A failing `prometheus-config-reloader` container causes the `prometheus-k8s-0` pod to get into a crash-loop.

```
$ kubectl logs -f prometheus-k8s-0 -n monitoring  -c prometheus-config-reloader
ts=2019-05-14T18:31:52.910711239Z caller=main.go:68 msg="Starting prometheus-config-reloader version '0.29.0'."

add config file watch: no such file or directory
```

**Other details that may be helpful:**

The `prometheus-config-reloader` container is being passed the following argument for the config file to watch `--config-file=/etc/prometheus/config/prometheus.yaml.gz`, which comes from the secret `prometheus-k8s`.

The  `prometheus-k8s` Secret is using `prometheus.yaml` rather that `prometheus.yaml.gz`, which explains why the "no such file or directory" above.

```
rancher:iad jemillan$ kubectl get secret prometheus-k8s -n  monitoring -o yaml
apiVersion: v1
data:
  configmaps.json: eyJpdGVtcyI6bnVsbH0=
  prometheus.yaml: Z2xvYmFsOgogIGV2YWx1YX....
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
* Rancher  v2.2.2
* User Interface v2.2.41
* Helm v2.10.0-rancher10
* Machine v0.15.0-rancher6-1
* quay.io/prometheus/prometheus:v2.2.1
* coreos-prometheus-config-reloader:v0.29.0

- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-3+602d21b1679fa5", GitCommit:"602d21b1679fa5f8de2f9a04bbf485f1fa09a973", GitTreeState:"clean", BuildDate:"2019-02-27T16:46:58Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jlamillan** [comment]
Manual workaround:

(1) ` kubectl edit statefulset prometheus-k8s  -n monitoring` (2) change `--config-file=/etc/prometheus/config/prometheus.yaml.gz` to `--config-file=/etc/prometheus/config/prometheus.yaml`

**Comment by thxCode** [comment]
@jlamillan you got this when enabling Rancher Monitoring or installing `prometheus-operator` App? I cannot understand the context.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
