### ISSUE TITLE
Deleting a cluster does not clean up system account users

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#20250]
version: rancher/rancher:v2.2.2

Delete a cluster and the system Service account: u-<10digits> in the default namespace is not cleaned up. This is problematic over time as clusters come and go over time, as it also feeds into global role bindings. 

In larger environments where there would be lots of clusters our controllers performance would have issues doing list calls.

**Comment by rmweir** [comment]
I think this was addressed by: https://github.com/rancher/rancher/pull/19105, will test some more to confirm

**Comment by mrajashree** [comment]
@rmweir from what I remember, it was found during testing that deleting a project was deleting the system account user and globalrolebinding. But deleting a cluster wasn't doing the same for projects in those clusters, which is why bug was reopened. And like you said the ns not getting deleted could be underlying cause.

**Comment by rmweir** [comment]
@mrajashree were the projects deleting but the resources were left over were left over?

**Comment by rmweir** [comment]
@mrajashree @sowmyav27 what I am finding is that everything gets deleted aside from globalrolebinding. Going to move this to test as it is only concerned with service-account.

Steps I followed to validate:
create cluster
wait for it to come up
`kubectl get users`
see service accounts
delete cluster
`kubectl get users`
see service accounts have been delete

**Comment by mrajashree** [comment]
Yes I just checked and the service accounts do get deleted by the fix put in #19105
And we have #19018 to track grb deletion

**Comment by sowmyav27** [comment]
Verified on master-head - commit id: `72f2083c1`

- create cluster
- wait for it to come up
- do `kubectl get users` and see service accounts
- delete cluster
- do `kubectl get users`
- The service accounts pertaining to the projects are **NOT** deleted

**Comment by mrajashree** [comment]
Closing this as it's being tracked here https://github.com/rancher/rancher/issues/19018
