### ISSUE TITLE
Clone workload with nodePort will cause the newly added workload use the same nodeport

### ISSUE THREAD

**Issue by wendell-dev** [rancher/rancher#20258]
Clone workload with nodePort will cause the newly added workload use the same nodeport 

Steps:
1. Clone a workload which has a nodeport.
2. Change the name of the new workload
3. Click Save

Results:

No new node port created

**Comment by codyrancher** [comment]
I am not able to reproduce this. I'm going to throw this to QA to verify.

**Comment by sowmyav27** [comment]
**verified on 2.3.5 and master-head - commit id: `4f1aff9b7 `**

- Deploy a workload with nodeport
- clone a workload which has a nodeport.
- Change the name of the new workload
- Click Save
- New workload with a nodeport is created.

Not able to reproduce the original issue.
