### ISSUE TITLE
using private registry version for rancher/agent and rancher/agent-instance

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2026]
I use the new support for using a privately hosted rancher/agent and rancher/agent-instance.

This works for when kicking up a new agent. But the Lb Agent and Network agent doesn't pick up the private registry part:

![image](https://cloud.githubusercontent.com/assets/72965/9813962/8bef522c-588a-11e5-90dc-9bbbfb6ede6e.png)

This is from the startup of the agent:
```
INFO: Required Image: private-registry:8181/rancher/agent:server-0.35.0
INFO: Current Image: private-registry:8181/rancher/agent:server-0.35.0
INFO: Using image private-registry:8181/rancher/agent:server-0.35.0
```
(yes, I've tagged them with an additional tag to make it easier to deploy the correct version against a given server version).

And on the server I have this from the log during start:
```
CATTLE_AGENT_INSTANCE=private-registry:8181/rancher/agent-instance:server-0.35.0
CATTLE_AGENT_PACKAGE_AGENT_BINARIES_URL=/usr/share/cattle/artifacts/agent-binaries.tar.gz
CATTLE_AGENT_PACKAGE_CADVISOR_URL=/usr/share/cattle/artifacts/cadvisor.tar.gz
CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz
CATTLE_AGENT_PACKAGE_NODE_AGENT_URL=/usr/share/cattle/artifacts/node-agent.tar.gz
CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/python-agent.tar.gz
CATTLE_AGENT_PACKAGE_RANCHER_DNS_URL=/usr/share/cattle/artifacts/rancher-dns.tar.gz
CATTLE_AGENT_PACKAGE_RANCHER_METADATA_URL=/usr/share/cattle/artifacts/rancher-metadata.tar.gz
CATTLE_AGENT_PACKAGE_VOLMGR_URL=/usr/share/cattle/artifacts/volmgr.tar.gz
CATTLE_BOOTSTRAP_REQUIRED_IMAGE=private-registry:8181/rancher/agent:server-0.35.0
CATTLE_CATTLE_VERSION=v0.86.0
```

Looking at the bootstrap script, I find the required image there, for the agent, but I'm not sure where the image name comes from when cattle starts the networking agent (or load balancer image..)
`https://rancher/v1/scripts/bootstrap`
```
REQUIRED_IMAGE="private-registry:8181/rancher/agent:server-0.35.0"
```

**Comment by cloudnautique** [comment]
@kaos, to override the Agent instance the environment variable is CATTLE_AGENT_INSTANCE_IMAGE. Can you give that a try?

**Comment by kaos** [comment]
@cloudnautique Doh. I've missed the `_IMAGE` prefix on that setting. Will most likely work when I get that sorted, thank you.
