### ISSUE TITLE
cluster unavailable

### ISSUE THREAD

**Issue by FreeDemon** [rancher/rancher#20262]
**What kind of request is this (question/bug/enhancement/feature request):**
```
Bug
```
**Steps to reproduce (least amount of steps as possible):**

cluster unavailable no reason,  when it show unavailable, after a while it will be ok, and then a while it will be unavailable again, repeat this.

**Result:**
![image](https://user-images.githubusercontent.com/16284239/57763098-51261b00-7733-11e9-9c45-1c805ca28174.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
``` 
v 2.2.2
```
- Installation option (single install/HA):
```
HA(master3 /etcd 3)
```

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
```
Version: v1.13.5
CPU: 952 Cores
Memory: 3.1 TiB
```
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.3-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   e19b718
 Built:        Thu Aug 30 01:06:10 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.3-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   e19b718
 Built:        Thu Aug 30 01:06:10 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by superxor** [comment]
related https://github.com/rancher/rancher/issues/20102

**Comment by loganhz** [comment]
Is there any useful logs?

**Comment by superseb** [comment]
Please provide logs from the moment it happens so we can investigate this, you can also use https://rancher.com/docs/rancher/v2.x/en/troubleshooting/ at the moment it is happening to see if you can relate it to something. Also more detailed information helps in this case like specifications per node with what role and possibly anything related to deployments or anything else in cluster happening at the time. We can reopen to investigate.
