### ISSUE TITLE
Ingress stuck in initializing when using non-default ingress controller

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#20267]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a new cluster, disabling the Nginx ingress controller under Advanced settings
2. Deploy the Nginx Ingress Controller from the official Helm chart repository
3. Create a new ingress resource in the GUI

**Result:**
Ingress created and functional, but the state is stuck on "initializing" in the GUI

**Expected:**
Ingress not stuck on initializing. Rancher to be agnostic to the specific ingress controller used. Users may decide to use a different one, e.g. Traefik, F5 BigIP Controller or Avi Networks Ingress...

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2
- Installation option (single install/HA):
HA

<img width="1279" alt="Screenshot 2019-05-15 at 17 18 10" src="https://user-images.githubusercontent.com/3813921/57787416-9d725a80-7735-11e9-92a8-500c1d2ad5f1.png">

**Comment by vincent99** [comment]
There's a status field that the controller should be updating with the addresses the ingress is available at.  This is not Rancher or nginx-ingress-specific and I don't know about all of them but at least [Traefik](https://github.com/containous/traefik/pull/4397) supports it.

**Comment by janeczku** [comment]
I think that is right: `status.loadbalancer.ingress` should be not empty to signal ingress readiness. I guess thats what the GUI is basing the ready state on?

**Comment by janeczku** [comment]
https://github.com/kubernetes-sigs/application/issues/78
