### ISSUE TITLE
[cli] i am unable to figure out how to use alternate credentials

### ISSUE THREAD

**Issue by rmalchow** [rancher/rancher#20266]
this could be just a documentation issue. in 1.6, we had `--config` to specify alternate credentials. how about 2.2? is there any way i can do the same thing (short of running rancher cli in docker and doing `-v someother.json:/root/.rancher/cli2.json`)?

**Comment by dramich** [comment]
@rmalchow There is currently not a way to do that without using docker as you suggested.
