### ISSUE TITLE
Backport: Add in logic to upgrade system-charts branch

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#20270]
Backport: https://github.com/rancher/rancher/issues/20115

**Comment by alena1108** [comment]
Can be tested with v2.2.4-rc3

**Comment by jiaqiluo** [comment]
The bug fix is validated on v2.2.4-rc5

case 1:
1. Launch v2.2.3
2. Upgrade to  v2.2.4-rc5 - Confirm that the branch for the system-charts repo is updated to dev
3. Roll back to v2.2.3 - Confirm that the branch for the system-charts repo is updated to `master`

case 2:
1. v2.2.3 and enable cluster monitoring 
2. Upgrade to v2.2.4-rc5  -  Confirm that the new cluster monitoring chart is available.
3. Upgrade cluster monitoring
4. Roll back to v2.2.3 - Confirm that the cluster is running the old cluster monitoring chart. 

case 3:
1. Launch v2.2.3 and enable cluster monitoring and then change the defaults to dev.
2. Upgrade to v2.2.4-rc5 -  Confirm that the new cluster monitoring chart is available.
3. Upgrade cluster monitoring
4. Roll back to v2.2.3 - Confirm that the cluster is running the old cluster monitoring chart and the updated values is master

case 4:
1. Launch v2.2.3
2. set the system-chart branch and url to custom values.
3. Upgrade to v2.2.4 - Confirm system-chart branch and url DO NOT change

**Comment by jiaqiluo** [comment]
Another finding:

Steps:
- v2.2.3 and enable cluster monitoring
- Upgrade to v2.2.4-rc5 - Confirm that the new cluster monitoring chart v0.0.3 is available, and the branch for the system-charts repo is updated to dev
- Upgrade cluster monitoring apps to v0.0.3
- Roll back to v2.2.3 - confirm the branch for system-chart is master

Result:
- the cluster monitoring apps show the version as `v0.0.2`, in this case, the workloads deployed for the apps are actually from `v0.0.3`. The version here is incorrect here. 
- if we upgrade the Rancher server to v2.2.4-rc5 again, notice that the cluster monitoring apps will show upgrade available again although they are already the v0.0.3 version. 

This will be tracked as a separate issue.
