### ISSUE TITLE
Catalog refresh failed for SIEMonster

### ISSUE THREAD

**Issue by naturgy** [rancher/rancher#20277]
kind of request: question

As part of SIEMonster Installation procedure I added a catalog from https://github.com/siemonster/v3-final

**Result:**

After refreshing my browser, the catalog entry doesnt appears and in docker log I saw the followin messages:

time="2019-05-15T19:51:33Z" level=error msg="Multiple errors encountered performing catalog refresh"
time="2019-05-15T19:51:33Z" level=error msg="Catalog refresh failed for library (https://git.rancher.io/rancher-catalog.git): Remote commit check failed: Repo [https://git.rancher.io/rancher-catalog.git] is not accessible: Get https://git.rancher.io/repos/rancher-catalog/commits/v1.6-release: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2019-05-15T19:51:33Z" level=error msg="Catalog refresh failed for community (https://git.rancher.io/community-catalog.git): Remote commit check failed: Repo [https://git.rancher.io/community-catalog.git] is not accessible: Get https://git.rancher.io/repos/community-catalog/commits/master: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2019-05-15T19:51:33Z" level=error msg="Catalog refresh failed for SIEMonster (https://github.com/siemonster/v3-final): Remote commit check failed: Repo [https://github.com/siemonster/v3-final] is not accessible: Get https://api.github.com/repos/siemonster/v3-final/commits/master: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
2019-05-15 19:51:34,232 WARN  [:] [] [] [] [ecutorService-1] [i.c.p.s.c.impl.CatalogServiceImpl   ] Skipping catalog refresh because it failed. Response code: 500, reason: Internal Server Error

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

CATTLE_RANCHER_CLI_VERSION=v0.6.9
CATTLE_RANCHER_COMPOSE_VERSION=v0.12.5
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
CATTLE_RANCHER_SERVER_VERSION=v1.6.17

- Docker version (use `docker version`):
rancher@makara ~ $ docker info
Containers: 15
 Running: 12
 Paused: 0
 Stopped: 3
Images: 11
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: v0.13.2 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.88-coreos
Operating System: Container Linux by CoreOS 1967.3.0 (Rhyolite)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66GiB
Name: makara
ID: VI7U:BVAX:254N:CGV7:H63V:AG47:LE3J:SZWF:JW7E:XN7Y:ZO3S:HTQ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://xxxx:yyyy@10.xxx.xxx.xxx:8080
HTTPS Proxy: http://xxxx:yyyy@10.xxx.xxx.xxx:8080
No Proxy: localhost,127.0.0.1,.ar.gasnatural.com,10.218.3.170,10.218.3.57,10.218.3.135,10.218.3.82,10.218.3.87
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by superseb** [comment]
We don't actually support SIEMonster software, but as it seems you are using a proxy and the container can't reach the repository for the catalogs. Please refer to https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#http-proxy and see if it works using the `rancher/server` container in the latest version, if not, file a new issue so we can investigate.
