### ISSUE TITLE
Rancher does not remove nodes deleted via ec2/DO console despite k8s knowing node is gone

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#20282]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create IaaS cluster  with a cloud provider (ec2 preferred)
2. Create node templates with IAM roles usable for cloud provider
3. Provision a cluster.
4. Delete a node from the cluster via ec2 console
5. Run `kubectl get nodes` 
6. Node is no longer present
7. But node is still visible in rancher UI with  `kubelet stopped posting node status`

**Result:**

**Other details that may be helpful:**
Rancher should know if the node is gone if kubernetes knows

**Comment by cjellick** [comment]
I believe this is a dupe of https://github.com/rancher/rancher/issues/14184
if you verify it is a dupe, can you close this one and just add your repro steps to that issue?

**Comment by daxmc99** [comment]
Verified as duplicate, closing in favor of https://github.com/rancher/rancher/issues/14184
