### ISSUE TITLE
Local Auth - Member of an environment is allowed to "Deactivate" environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2028]
Server version - v0.37.0-rc3

Local Auth enabled set up
Steps to reproduce  the problem: 
Create a regular user - test1.
Add this user  - test1 as a member of  "Default" project.
Log in as "test1".

Go to "Manage Environment" .
When "Default" project is listed , we see both "Decativate" and "Edit" option presented to the user.

Both these options should not be presented for a member of the project.

"test1" is allowed to "Deactivate" this environment. This should not be allowed.

When I try to edit the environment , i am not allowed to and get the following error message -  "You must be a project owner to update the name or description." , which is acceptable. 

This issue is also reproducible in github enabled setup.

**Comment by rancherdev** [comment]
Tested with server version - v0.37.0-rc4

Members of a project are not given an option to"Deactivate" /"Edit" option for environments that are listed in the "Manage Environment" view.

Closing this issue.

**Comment by sangeethah** [comment]
Tested with server version - v0.37.0-rc4

Members of a project are not given an option to"Deactivate" /"Edit" option for environments that are listed in the "Manage Environment" view.

Closing this issue.
