### ISSUE TITLE
Cluster Not shown when the Machine containing Rancher Server and Rancher Agent Restarts

### ISSUE THREAD

**Issue by S93rastogi** [rancher/rancher#20284]
**BUG**

**Steps to reproduce:**

- Start a virtual machine (Rancher OS)
- Set up Rancher Server on the Rancher OS ( to get Rancher running )
- Create a single node cluster. (Node exists on the same Rancher OS )
- Shutdown the machine and again start the machine.

**Expectation**
- The created cluster must be shown.

**Result:**
- Rancher dashboard shown no cluster.

**Other details that may be helpful:**
It is a single node cluster with etcd,worker and control plane.
The node exists on the same machine where the Rancher Server exists.

**Environment information**
-Rancher OS : v1.5.1
-Rancher Server : Rancher Stable release (v2.2.3) (rancher:stable image used)
- Installation option (single install/HA): Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM (Rancher OS)

I tried to investigate the issue and found that when the Rancher OS machine restarted Rancher Agent is showing restarting status.

![image](https://user-images.githubusercontent.com/7479903/57826466-12d73d00-77c1-11e9-83c8-deed2ca17e0c.png)

I tried to check the logs of Rancher agent and found the issue with checksum. 
![image](https://user-images.githubusercontent.com/7479903/57826524-43b77200-77c1-11e9-8ea0-f57105d023a4.png)

The issue : https://github.com/rancher/rancher/issues/15012 seems to be linked but I cant find the solution as provided by him.

**Comment by S93rastogi** [comment]
@superseb @prachidamle  The issue seem to be persistent and there is no solution at present. Please let me know if I need to share some specific logs.

**Comment by superseb** [comment]
Please provide the exact commands to reproduce, based on what you are saying is that the data is getting lost as cluster is not showing and checksum mismatch means that there is a new certificate generated.

Let me know when we can reopen and investigate.
