### ISSUE TITLE
2.2 backport : Git Catalog templates didn't get updated on rancher slave pod in HA mode

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#20295]
backport of https://github.com/rancher/rancher/issues/19638

What kind of request is this (question/bug/enhancement/feature request):
bug

Steps to reproduce (least amount of steps as possible):
Pre-requisites: Rancher HA

add a custom git catalog to the rancher global/cluster/project catalog.
update catalog charts:
2.1 change the template files e.g. the default value in the values.yaml file and push the update.
2.2 or add a new version of a chart e.g Nginx v0.2.0 to the same catalog and push the update.
click refresh catalog button and wait for the catalog repo get synced.
go to the rancher api /v3/templates/cattle-global-data:CHART_NAME and click the versionLinks to jump to the specified templateVersions, check the changed files is updated correctly.
4.1 because it is rancher HA mode, so you may need to refresh the templateVersions page multiple time to check all node returns the same result.
4.2 decode files using https://www.base64decode.org/
exec into the rancher server pod and check the catalog template is updated in the local cache $ cd management-state/catalog-cache/CHART_HASH_PATH, both master and follower node should be updated and keep consistent.
Result:
All of the rancher server pod should have the same version of latest catalog apps templates.

Other details that may be helpful:

Environment information

Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): rancher v2.2.3
Installation option (single install/HA): HA
Cluster information

Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE
Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
Kubernetes version (use kubectl version):

**Comment by erikwilson** [comment]
Back-ported issue from #19638 for v2.2

**Comment by klinux** [comment]
Is there some workaround to this issue?

Thank you

**Comment by erikwilson** [comment]
If you remove the `management-state/catalog-cache` directory from each of the HA instances the cache will be re-populated

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.4-rc5

* Reproduced original issue
* Deployed Rancher v2.2.4-rc5 in HA
* Added a custom catalog
* Updated the custom catalog and refreshed
* Viewed the new version links in API
* Viewed the updated files in each rancher pod's catalog-cache

**Comment by tushar-sakpal** [comment]
> If you remove the `management-state/catalog-cache` directory from each of the HA instances the cache will be re-populated

Where to find `management-state/catalog-cache` in Artifactory? I have checked both master as well as worker nodes. I'm using Artifactory version 6.9.1
