### ISSUE TITLE
Container stuck in starting state forever - "Storage : Repository docker.io/<imagename> already being pulled by another client. Waiting."

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2029]
Server version - v0.37.0-rc3

Started a service with scale 2.
Services get stuck in "ACTIVATING" state forever since 1 of the container in the service is  stuck in starting state forever - "Storage : Repository docker.io/<imagename> already being pulled by another client. Waiting."

Trying to start another service using the same image , results in this service also being stuck in  "ACTIVATING" state forever since any container deployment that gets to the same host gets  stuck in starting state forever - "Storage : Repository docker.io/<imagename> already being pulled by another client. Waiting."

**Comment by alena1108** [comment]
@sangeethah haven't seen this exception after upgrading to docker 1.9 (used to happen a lot in the previous versions). So marking it with "to-test"

**Comment by sangeethah** [comment]
I have not seen this issue when testing with docker 1.9 hosts.

**Comment by rschreijer** [comment]
I'm having this issue with Rancher 1.0.1 on docker 1.10.3 on AWS, but it's stuck in `Starting (Storage : Extracting)` for the last 20 mins and going.

**Comment by nunofgs** [comment]
I have the same exact issue. I can reproduce reliably. Every stack I launch will launch its containers just fine, but will be "extracting" for 20+ minutes.

<img width="1165" alt="screen shot 2016-08-29 at 11 02 52" src="https://cloud.githubusercontent.com/assets/92085/18048120/3fb58d4a-6dd8-11e6-8917-d46b6a5386d4.png">

**Comment by rschreijer** [comment]
@alena1108

Had this issue again today.
In the Audit Log, I see a couple of these:
event type: service.reconcile --> extra Info; Request Object: `null`, Response Object: `null`
```
Waiting for [instance:zmXXXXXXX]. Instance status: Storage : Extracting
```

Docker version 1.10.3, build 20f81dd
Rancher v1.1.2
Linux <zmXXXXXXXXXX> 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Same way of solving this:
> adding an entirely new provisioned host and starting the services on there.
