### ISSUE TITLE
Streamline creation of grafana playlists

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#20293]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Steps to reproduce (least amount of steps as possible):**

Enable monitoring in Rancher and attempt to create a playlist in grafana.

**Result:**

You'll get a red access denied error

**Other details that may be helpful:**

Logging into grafana with the default admin/admin credentials allows playlist creation, but this isn't a great user experience. It'd be nice if this "log in" was automated when accessing the dashboard or some other way to make it so users didn't need to log in to create playlists.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.x

- Installation option (single install/HA):
either

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24213
