### ISSUE TITLE
Monitoring - the project monitoring should be auto-disabled after upgrading from v2.2.1 to v2.2.4-rc5

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20308]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run rancher v2.2.1
- add an ec2 cluster
- add a project and enable the project monitoring
- upgrade to v2.2.4-rc5

**Result:**
- the project monitoring is still enabled and the app `project-monitoring` still exits and  shows upgrade available

**Expected Result:**
- the project monitoring should be auto-disabled

**Comment by alena1108** [comment]
We will release note it for 2.2.4

**Comment by alena1108** [comment]
Closing the issue; added to the ReleaseNotes TODOs
