### ISSUE TITLE
Active Directory Integration Should Support Different Bind Formats

### ISSUE THREAD

**Issue by rajha-korithrien** [rancher/rancher#20303]
**What kind of request is this (question/bug/enhancement/feature request):**
This is a minor bug that is best solved by a feature addition.

**Steps to reproduce (least amount of steps as possible):**
1) Have an Active Directory setup where binding occurs via ADS_NAME_TYPE_DOMAIN_SIMPLE or ADS_NAME_TYPE_USER_PRINCIPAL_NAME specifically the binding (say with an ldapsearch) must be done as ```sAMAccountName@domain.com```
In this AD setup Rancher communicates with AD via an account named ```rancher```
2) Deploy Rancher via RKE
3) Using Global --> Security --> Authentication --> Active Directory fill in the UI with
* Service Account Username: rancher@domain.com
* Service Account Password: a verified working password via ldapsearch like so
```
ldapsearch -h adserver.domain.com -x -W -D "rancher@domain.com" -b "CN=Users,DC=icasa,DC=network"
Enter LDAP Password:
...
...
result: 0 Success
# numResponses: 171
# numEntries: 170
```
* Your Username: jdoe@domain.com
* Your Password: a verified working password via ldap search (just as above)

**Result:**
```
TestAndApply Error
Cannot locate user information for (sAMAccountName=jdoe@domain.com)
```

**Other details that may be helpful:**
Microsoft Documents the various kinds of binding formats:
https://docs.microsoft.com/en-us/windows/desktop/api/iads/ne-iads-__midl___midl_itf_ads_0001_0050_0001

The problem can be worked around by changing
* Login Attribute: sAMAccountName
to
* Login Attribute: userPrincipalName

But then all users *must* remember to put ```@domain.com``` during their login. If we set
* Default Login Domain: domain.com

Then Rancher assumes that the username should be:
```
domain.com\jdoe
```
When there are cases that it should be
```
jdoe@domain.com
```
It would be useful for Rancher to be able to provide a means of choosing which kind of login string gets used when "Default Login Domain" is populated.

Possibly related issues:
 #19989

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2
- Installation option (single install/HA):
HA install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE created cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Bare Metal
- Kubernetes version (use `kubectl version`)

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
>
```

- Docker version (use `docker version`):

```
$ docker version
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:43:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:51:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by heamaral** [comment]
I'm also having this problem. When the Default Login Domain parameter is specified the user is not authenticated.

**Comment by ZoSam32** [comment]
@rajha-korithrien thank you for posting the work around. I was forgetting my AD properties.

**Comment by mrajashree** [comment]
@rajha-korithrien won't it be solved by leaving default login domain empty along with setting loginAttribute to userPrincipalName like you already did.

**Comment by rajha-korithrien** [comment]
@ZoSam32 No problem! Glad to be of service.
@mrajashree "won't it be solved by leaving default login domain empty along with setting loginAttribute to userPrincipalName like you already did."

I don't believe so as I currently do have ```Default Login Domain``` as being blank and ```loginAttribute``` set to ```userPrincipalName```. With these settings when a user supplies just their username (and correct password), they are unable to log in.

In every Active Directory deployment I have ever used ```userPrincipalName``` is always of the form:
```txt
user@active-directory-domain
```
As a result, if we leave the default login domain empty, and set ```loginAttribute``` to ```userPrincipalName``` then users must supply ```@active-directory-domain``` along with their username in order for the search filter to correctly hit against their account.

Further, in order to bind to active directory as the user (in order to ensure the user entered the correct password) the bind attempt must use ```user@active-directory-domain```

I believe the reason ```Default Domain``` exists as an option is to remove the need for users to consistently have to put ```@active-directory-domain``` but the Rancher code currently seems to only allow for the use of the NT4 style format of
```txt
active-directory-domain\username
```
In this current method the user only supplies ```username``` and the contents of ```Default Domain``` are automatically added with a ```\```. To create ```active-directory-domain\username```. This will only work when Active Directory has been setup to allow binding via that format (for example ADS_NAME_TYPE_NT4). However many newer Active Directory deployments do not allow binding in that format (at least all the ones I have worked with do not).

A means of informing Rancher to build the string with a different format i.e.
```txt
username@active-directory-domain
```
Would be useful.
Thank you for your question and attention!
