### ISSUE TITLE
Errors in rancher logs when delete cluster

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20300]
Version: v2.2.4-rc3 (HA Setup)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Have an HA setup with many clusters. In my case one of every type.
- Once they are ready, delete them all at once. Observe that it takes 4-10 mins to delete them and the many errors in logs. In the UI the Removing state will change to error-type (red in UI)
- Optionally delete slowly one by one and you will still see errors in logs. But Removing state does change to error-type (red in UI)

**Result:**
- Clusters can take longer to delete than normal if deleting many at once
- Errors in log repeat many times (this repeats in some cases such as when delete many clusters -- i.e. the 4-10 minute scenario)
`
[rancher-754467b5b8-vm89j] 2019/05/16 20:34:05 [ERROR] problem retrieving user for CRTB map[projectId:c-sz5st:p-vch79 transitioningMessage:waiting on cluster-prtb-sync_c-sz5st uuid:e627cc53-7809-11e9-a602-02af34995612 userId:u-pcx42yvjt2 type:/v3/schemas/projectRoleTemplateBinding annotations:map[lifecycle.cattle.io/create.cluster-prtb-sync_c-sz5st:true lifecycle.cattle.io/create.mgmt-auth-prtb-controller:true] roleTemplateId:project-member namespaceId:p-vch79 transitioning:yes name:u-pcx42yvjt2-member .selfLink:/apis/management.cattle.io/v3/namespaces/p-vch79/projectroletemplatebindings/u-pcx42yvjt2-member userPrincipalId:local://u-pcx42yvjt2 labels:map[cattle.io/creator:norman] state:removing id:p-vch79:u-pcx42yvjt2-member removed:2019-05-16T20:34:05Z created:2019-05-16T18:39:12Z] from cache during CRTB transformation: user.management.cattle.io "u-pcx42yvjt2" not found 
`
- If delete many clusters at once UI shows red "Removing" state.

**Comment by davidnuzik** [comment]
I tested this again. This time keeping an eye on the time. Adding this as may help to add context to the issue.

t M:SS

t 0:00
Delete all the clusters.
![image](https://user-images.githubusercontent.com/45179589/57893644-91030600-77f8-11e9-80cd-a5a27e2796af.png)

t 9:00
All clusters are still in the normal "Removing state" and the error is still "spamming" logs.
![image](https://user-images.githubusercontent.com/45179589/57893698-c4de2b80-77f8-11e9-884f-382f2f7d7d43.png)

t 9:45
We start to see some clusters show error-state in UI for "Removing" (they changed to red)
![image](https://user-images.githubusercontent.com/45179589/57893728-d9222880-77f8-11e9-8cc8-c06ef4d2263b.png)

t 10:00
More clusters in the "red" error state. One got deleted.

t 12:30
Some clusters got deleted eks is still in error state for removal in UI
![image](https://user-images.githubusercontent.com/45179589/57893774-ffe05f00-77f8-11e9-812b-6a6e5d0fed06.png)

t 13:00
All clusters are finally deleted.

**Comment by davidnuzik** [comment]
I also observe this issue in a single-node rancher install on latest master. I at least observed that it took much longer to delete the clusters than normal. I'm pretty sure if I have many clusters and try to delete all at once in my single-node master rancher I too would see the exact issue.

**Comment by daxmc99** [comment]
These issues were introduced in 804b65d681dbb0abe9eaf8881ba3e42f850a9b9b.
We now iterate over a large number of objects to check for dangling finalizers. 
The error mentioned is a not found error, which is a result of the cluster role template binding not being found since the cluster is being deleted.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/29/19)

I am no longer seeing the issue. A very small handful of [ERROR] entries are seen in the logs but this has been significantly improved. Error entires no longer loop and removal of clusters is significantly faster now. I only had to wait up to 30 seconds to remove many clusters at once (delete all at once).

I consider the issue resolved.
