### ISSUE TITLE
Monitoring - cluster status is not correct after upgrading from v2.2.1 to v2.2.4-rc5

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20309]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run rancher v2.2.1
- add an ec2 cluster
- add a project and enable the project monitoring
- upgrade to v2.2.4-rc5

**Result:**
- this cluster shows `Active` in red with the error message that ` ... catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.3" not found`. 
- But the cluster is actually functional 
- the brancher of catalog `system-chart` is `dev`, which is correct 
- If enabling the cluster monitoring the cluster shows "Active" in green and the error message is gone
- This does not happen to another cluster that has both cluster monitoring and project monitoring enabled before upgrading.

**Comment by jiaqiluo** [comment]
Another observation:

after upgrading from v2.2.3 to v2.2.4-rc5, notice that both clusters (which cluster monitoring is enabled) have the error message.
<img width="1592" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57957603-b6077f80-78b1-11e9-91aa-e879590ad064.png">
Go to Global -> apps -> mamage catalogs and notice the `system-library`'s  branch is `master` and suddenly switch to `dev` by itself, and if switching back to clusters now, those clusters become active. 
<img width="1403" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57957679-ee0ec280-78b1-11e9-8412-e79f759d52af.png">

**Comment by alena1108** [comment]
In monitoring deployment code, we should account for the delay in the branch switch. It might take some time for it to switch from master to dev branch in RC (release-v2.2 in the official release)

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc6`

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher:v2.2.4-rc6

test 1:
- run Rancher: v2.2.4-rc6 fresh install
- add an EC2 cluster
- enable cluster monitoring

Result:
- cluster monitoring and project monitoring work as expected  

Test 2:
- run Rancher: v2.2.3 
- add an EC2 cluster
- enable cluster monitoring
- upgrade to v2.2.4-rc6

Result:
- cluster monitoring still work after upgrading
- the error mentioned in the issue does not present any more even when `system-library`'s branch is `master` 

Test 3:
- run Rancher: v2.2.1 
- add an EC2 cluster
- enable cluster monitoring
- upgrade to v2.2.4-rc6

Result:
- cluster monitoring still work after upgrading
- the error mentioned in the issue does not present any more even when `system-library`'s branch is `master`
