### ISSUE TITLE
[logging] [splunk] if app logs are json they never make it to splunk

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#20305]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** 

1. Turn on logging to Splunk HEC for the Cluster
2. Run any image that outputs logs in JSON format.

**Result:**

Logs never make it to Splunk.

**What should happen:**

The application logs should get parsed as JSON and set `log` as an object so that the entire entry that is sent to splunk is a JSON object.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.2
- Installation option (single install/HA): HA

**Other Thoughts:**

There probably needs to be a way to set the parser format of  the fluentd collector based on different pods, perhaps a label and an auto-reconfiguration of the fluentd collector. If this already exists, great, but the docs on logging are a bit sparse.

Alternatively I wouldn't mind an option per deployment to specify a MERGE of the application log and the resulting object that rancher puts together, so instead of `log` being sent, it would omit log and if based on labels know that the incoming log from the app is JSON and merge it with the object Rancher creates.

**Comment by aiwantaozi** [comment]
Hi, you could deploy a fluentd aggregator, and send rancher log to fluentd target, then customize logs in fluentd aggregator

## Use Catalog to Deploy Fluentd Server 

Rancher sends the log to fluentd server, you can add filter, parser plugins configure to customize your log. Rancher support deploy fluentd server by using catalog **Fluentd Aggregator**

1. Browse to the project catalog that you want to deploy fluentd aggregator.

1. Click the **Launch**, select **fluentd-aggregator**, view details.

1. Configure deploy **Namespace**.

1. Configure deploy **Service Type**, the default is ClusterIP, you can use DNS or ClusterIP to access the service inside the cluster.

1. Configure output, select one or customize yours, check catalog description **Output Plugins**, make sure your output is supported. For more information, see [Fluentd Output](https://docs.fluentd.org/v1.0/articles/output-plugin-overview).

1. Configure filter, giving an example for using the filter to only include log from namespace kube-system. For more information, see [Fluentd Filter](https://docs.fluentd.org/v1.0/articles/filter-plugin-overview).
```
   <filter cluster.**>
   @type grep
   <exclude>
       key $.kubernetes.namespace_name
       pattern ^test$
   </exclude>
   </filter>
```
1. Configure parser if need, for more information, see [Fluentd Parser](https://docs.fluentd.org/v1.0/articles/parser-plugin-overview).

1. Configure formatter if need, for more information, see [Fluentd Formatter](https://docs.fluentd.org/v1.0/articles/formatter-plugin-overview).

1. After deployed the Fluentd Aggregator, go to **Tools > Logging**, configure Fluentd output log to your Fluentd Aggregator.

1. Complete the **Fluentd Server Configuration** form.

    1. From the **Endpoint** field, enter the cluster dns you deployed just now (i.e. `fluentd-aggregator.fluentd-aggregator.svc.cluster.local:24224`)

    1. Continue to configure other fields.

1. Click **Test**. Rancher sends a test log to Fluentd.

1. Click **Save**.

**Result:** Rancher is now configured to send logs to Fluentd Aggregator. Check you Fluentd Aggregator output events for your cluster and containers.

**Comment by ekristen** [comment]
Thanks, I'll take a look.
