### ISSUE TITLE
Collapsable Project Namespace "Projectless" View

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20306]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
As a global admin launch a cluster.
After the cluster is ready add a namespace at the cluster level. Do not select a project for the namespace from the drop down.
Navigate to the default project, then namespaces.

**Result:**
The project-less name space is visible but should be collapsed.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/22986
