### ISSUE TITLE
Better error message when trying to save a deleted account as a member of the environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2031]
Server version - v0.37.0-rc4

Local auth enabled setup

As admin, created user - test1
Made "test1" member of default project.
Deactivated and deleted "test1".
"test1" does not have access to server as expected.

As admin , go to "Manage Environment" and click on "Default" project ,

"test1" is still listed with "(ID not found)".

Try add another member to this environment and save.

user is presented with the following error message which has user id instead of having the username
- "Rancher Account: 1a9 nonexistent"

Also this error message needs to be improved to indicate to the user that this non existent account needs to be removed from the environment before any other changes can be made to the member list.

**Comment by deniseschannon** [comment]
Verified with v0.47.0-rc1
