### ISSUE TITLE
Workloads assigned to a specific node doesn't get deployed

### ISSUE THREAD

**Issue by pensiero** [rancher/rancher#20319]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- I upgrade or deploy a workload
- I set as scheduling rule `Run all pods for this workload on a specific node` and I choose a node

**Results*
In the workload overview, I can see that it starts creating&terminating hundreds of pods (infinite)

![f968afd5-cf7b-48cc-bb1f-548e5386d461](https://user-images.githubusercontent.com/2010696/57980093-ec1a4000-7a26-11e9-96c5-f566dba57db6.jpg)

**Other details that may be helpful:**
- There is one node in the cluster
- The node is active, and many other pods are already running on that node
- I'm using a single-node installation
- I recently migrated the server where the rancher server runs

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.3
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:52:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Wed Feb 13 00:24:14 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by loganhz** [comment]
Please file a new issue with YAML you used for the deployment if you can still reproduce the issue
