### ISSUE TITLE
Backport: Increase Prometheus Cluster monitor proxy NGINX buffers

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20312]
https://github.com/rancher/rancher/issues/19689

**Comment by loganhz** [comment]
Just noticed the backport issue for it is missing.

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc6`

**Comment by jiaqiluo** [comment]
The bug fix is validated on v2.2.4-rc6
Steps:
- add a DO cluster
- enable cluster monitoring
- execute Shell on the container `grafana-proxy` in `Workload: grafana-cluster-monitoring` to check its `nginx.conf` file
- execute Shell on the container `prometheus-proxy` in `Workload: prometheus-cluster-monitoring` to check its `nginx-conf.tmpl` file 
- confirm to see the following line in both files
```
 proxy_buffering             off;
```
