### ISSUE TITLE
How reuse data containers inside a stack?

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#2032]
I create a test setup with services.

**Service Apache**
1. Apache container
2. Apache data only container
-> sidekick: volumes-from Apache data container to Apache
-> LB-Web to make it http reachable (80 -> 80, http)

** Service MySQL**
1. MySQL container
2. MySQL data only container
-> sidekick: volumes-from MySQL data container to MySQL

**Service SSH**
1. SSH container (added /var/lib/mysql, /var/www/html to the image as volume mount point)
-> sidekick: volumes-from Apache data container to SSH
-> sidekick: volumes-from MySQL data container to SSH
-> LB-Web to make it ssh reachable (22 -> 22, tcp)

Apache and MySQL service seems to work fine, but the volumes from SSH service are empty.
Is there a way to reuse the existing data only containers with the ssh service?
All services are inside the same stack.

I try to connect with ssh (via a lb, works fine) and change web content, but it seems not to be the same data only container.

**Comment by ebuildy** [comment]
Please add your docker-compose.yml or some "docker ps" details

**Comment by deniseschannon** [comment]
Can you add your docker-compose.yml to help troubleshoot how to set up the labels?

**Comment by pwFoo** [comment]
Hi @deniseschannon ,

should be closed as duplicate of #2049?
Thanks!
