### ISSUE TITLE
[RFE] provide functionality to add additional dashboards to grafana via ranchers monitoring

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#20327]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Other details that may be helpful:**
When using the official prometheus operator helm chart users can define additional dashboards via side cars as defined here: https://github.com/helm/charts/tree/master/stable/prometheus-operator#grafana Ranchers implementation doesnt have this feature.

gzrancher/rancher#5697

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24213

**Comment by jiaqiluo** [comment]
This feature will be supported in Rancher Monitoring v2.

This issue is closed. New issues will be made for bugs in this area if needed.
