### ISSUE TITLE
[RFE] Clarify 'Labels & Annotations' detail text for non-workload views

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#20329]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

The Rancher UI contains a single detail text for the Labels & Annotations form, in English this is 'Key/Value pairs that can be used to label/annotate containers and make scheduling decisions.' (https://github.com/rancher/ui/blob/master/translations/en-us.yaml#L4905). This is used in multiple contexts both where the reference to containers and scheduling decisions is relevant, i.e. the Pod/Deployment/DaemonSet views etc., as well as those where this is not, i.e. the Pod Security Policy, Ingress and Service views.

Request is therefore to clarify the single detail text to be more generic, or have different text for the different views.

**Environment information**
- Rancher v2.2.3

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
**Verified on 2.3-head**
ui tag: `latest-2.3`

Labels and Annotations show `Key/Value pairs that can be used to label/annotate resources.`
On create Workload page:
<img width="1277" alt="Screen Shot 2019-10-22 at 2 30 04 AM" src="https://user-images.githubusercontent.com/26032343/67243048-63d81500-f474-11e9-80e9-5e700bec119c.png">

Add Ingress page:
<img width="1277" alt="Screen Shot 2019-10-22 at 2 31 49 AM" src="https://user-images.githubusercontent.com/26032343/67243059-676b9c00-f474-11e9-96dd-3ef2a602ab4d.png">

And also on Pod Security Policy --> Add Policy page
