### ISSUE TITLE
Rancher server 2.2.3 high cpu usage on fresh empty install

### ISSUE THREAD

**Issue by IlyaSemenov** [rancher/rancher#20320]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Start a new Rancher server on a fresh Ubuntu 18.04 instance:

```
docker run --rm -it -p 1443:443 rancher/rancher
```

open https://100.100.100.100:1443 and set random password. Wait for the log to be quiet. Don't create any clusters.

**Result:**

```
...
2019/05/19 17:12:12 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2019/05/19 17:12:12 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2019/05/19 17:12:12 [INFO] update kontainerdriver amazonelasticcontainerservice
2019/05/19 17:12:17 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10162
2019/05/19 17:12:17 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2019/05/19 17:12:17 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
I0519 17:12:19.503450       6 controller_utils.go:1027] Waiting for caches to sync for garbage collector controller
I0519 17:12:19.703769       6 controller_utils.go:1034] Caches are synced for garbage collector controller
2019/05/19 17:12:22 [INFO] Creating token for user user-787g9
INFO[2019-05-19 17:12:22] Telemetry Client v0.5.3
INFO[2019-05-19 17:12:22] Listening on 0.0.0.0:8114
```

the log stops, Rancher is supposed to do nothing. However, the CPU usage is 20% on average (on the i7-7700 CPU @ 3.60GHz):

<img width="880" alt="Screenshot 2019-05-20 at 00 12 51" src="https://user-images.githubusercontent.com/128121/57985639-0a1e8980-7a95-11e9-8e6e-a9c7c374ed88.png">

It's not getting any better in at least an hour.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.3
- Installation option (single install/HA): single install

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:52:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Wed Feb 13 00:24:14 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by vincent99** [comment]
The single container is running an entire internal k8s cluster, and k8s has relatively high baseline load.

**Comment by IlyaSemenov** [comment]
I see. But can't it be tweaked somehow? Like reduce the frequency of etcd polling..or what causes the load? Since it's single node install the "work" it's doing is mostly useless anyway.

I tried starting the container with `ETCD_HEARTBEAT_INTERVAL=500` but it didn't make any difference.

**Comment by IlyaSemenov** [comment]
I still consider this a problem that can be worked around, so it's not stale. If the maintainers think otherwise please mention that and close the issue.

**Comment by vincent99** [comment]
It's 1/5th of 1/8th ≈ 2% of the CPU.  We are not realistically going to expend developer time optimizing for an edge case where you've installed the product but aren't using it for anything useful yet, in the docker packaging of the product meant mostly for experimenting/demos and not production.
