### ISSUE TITLE
disabling auth doesnt clean up authconfigs

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#20323]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. provision an SAML auth provider, in this case okta, with an invalid config
2. disable saml auth
3. reenable saml auth with the correct info
/registry/management.cattle.io/authconfigs/okta

**Result:**
Trying to login results in "Waiting to hear back from IDP"

**Other details that may be helpful:**
when looking in etcd we see that the authconfig isnt cleaned up when removing an auth provider, also the error wasnt helpful in surfacing the actual issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.3
- Installation option (single install/HA):
HA

**Comment by prachidamle** [comment]
@aemneina step#3 above say that the correct config was re-entered - do think that the original bad config was still taking effect and causing login problems?

**Comment by prachidamle** [comment]
@aemneina @alena1108 There is only one authconfig instance created per auth provider, and we create them on rancher server starts for the first time. When the provider is enabled, provider data  is saved in this authconfig. When we remove/disable auth, we mark the authconfig object as disabled. The config itself is not deleted, and you will find it in etcd - this is as designed, it will be however marked as disabled/inactive.

**Comment by alena1108** [comment]
@prachidamle 
> I am not sure I understand what is the problem we are trying to fix.

the problem on the user setup is they couldn't login even after re-adding the config, and there was an assumption made that the old config might be interfering with it.

@aemneina looks like it is by design to keep the old config in the disabled state. So only the new active config will get picked up. So we have to make sure that:

* The new config got created, and it's in active state. The old config got marked as inactive. Can we grab that info from kubectl
* Double check that the new config has all the parameters set correctly by the user.

**Comment by prachidamle** [comment]
@alena1108 there will be only one authconfig instance in etcd, we keep the same object updated everytime the config is changed by the user.

Seems like somehow the customer entered wrong config and they could not update it after or disable auth. @aemneina is going to get some concrete info/steps on this.

**Comment by Negashev** [comment]
@alena1108 @prachidamle Some information

> 0) Before that, I used ldap and I only have one user ldap (not admin, not me) which I cannot remove from rancher:443/v3/users

1) i create adfs configutration (it's work, i try to test access with groups)
set only allowed, add my saml group and `remove me`
2) disable adfs auth
2.1) after that i can't add new auth (adfs or ldap)
3) remove all principalIds in all users on rancher:443/v3/users (stay only local)
4) create adfs again (all saved only add Private Key)
5) In popup can see rancher:443/verify-auth?config=adfs&errorCode=403
on ui  button `Waiting to hear back from IDP`
on logs `[ERROR] SAML: User does not have access <nil>`

In rancher HA mode i see that config-spkey created round robin on secretes `cattle-global-data`


Active | adfsconfig-spkey | cattle-global-data | spkey | 3 minutes ago |  
Active | keycloakconfig-spkey | cattle-global-data | spkey | a few seconds ago |  
Active | pingconfig-spkey | cattle-global-data | spkey | 8 minutes ago

**Comment by prachidamle** [comment]
@negashev have few questions around the steps above:
- Are you enabling and also disabling Auth using Rancher UI? <specifically did you disable auth via UI or via API?>
- Are you testing this with Rancher 2.2.3 version?
- Is this seen only in HA setup? Or do you see this in single node setup as well?

**Comment by Negashev** [comment]
@prachidamle 
- Rancher UI
- 2.2.3
- only HA

**Comment by prachidamle** [comment]
@Negashev After the steps #2 above when you have disabled ADFS auth, if you pull the ADFS authconfig using kubectl (on your management plane local cluster), do you see the authconfig show the accessMode "required" similar to below?

```
{
"accessMode": "required",
"allowedPrincipalIds": <your adfs group>,
"baseType": "authConfig",
"id": "adfs",
... }
```

**Comment by Negashev** [comment]
@prachidamle Yes
```
> kubectl get  authconfigs.management.cattle.io adfs -o yaml
accessMode: required
allowedPrincipalIds: null
apiVersion: management.cattle.io/v3
displayNameField: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
enabled: false
```

**Comment by prachidamle** [comment]
Awesome, But allowedPrincipalIds is null or it also has the data you had set?

**Comment by Negashev** [comment]
@prachidamle  allowedPrincipalIds: null

**Comment by Negashev** [comment]
Oh cool, i set adfs Config to "default" (remove all keys) and setup adfs again, Auth Work! 
Thanks @prachidamle !
```
apiVersion: management.cattle.io/v3
kind: AuthConfig
metadata:
  creationTimestamp: 2019-04-18T14:13:33Z
  generation: 44
  labels:
    cattle.io/creator: norman
  name: keycloak
  resourceVersion: "5166"
  selfLink: /apis/management.cattle.io/v3/authconfigs/adfs
  uid: 12312322-61e4-11e9-bd43-fa163e582a9b
type: adfsConfig
```

**Comment by Negashev** [comment]
Fine, it's work
```bash
$ rancher kubectl get  authconfigs.management.cattle.io adfs -o yaml
accessMode: required
allowedPrincipalIds:
- adfs_user://MY_ACCOUNT@MY_COMPANY
- adfs_group://MY_COMPANY\MY_GROUP
apiVersion: management.cattle.io/v3
displayNameField: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
enabled: true
````

**Comment by prachidamle** [comment]
@Negashev yep awesome that is the workaround. That key "accessMode: required" was blocking you from enabling Auth again. 

@alena1108 The issue seems specific to HA, when you disable Auth from UI, there are 2 API calls that UI makes:
1) Call to disable the authConfig
2) Immediately a call to clear out the "accessMode" from the authConfig.
Seems like in an HA setup somehow this flow is not clearing out the config, most likely issue occurring due to separate servers nodes processing these leaving the etcd data in wrong state.
Instead of relying on the UI calls to clear out the data, we should add a server side fix.
We already seem to have this ticket for this fix: https://github.com/rancher/rancher/issues/14363

**Comment by Negashev** [comment]
The next step is to configure adfs to automatically enter rancher

**Comment by aemneina** [comment]
@Negashev take a look at this to see if it helps out:
https://gist.github.com/mrajashree/a96793d8c7e418efba1e0103a8639201

**Comment by Negashev** [comment]
Thanks, but it's about configuration adfs for rancher, not browser auto login by adfs

**Comment by mrajashree** [comment]
needs UI change too: https://github.com/rancher/rancher/issues/21803

**Comment by alena1108** [comment]
@sangeethah can be tested from the API. For the UI flow, there is one more fix needed - it's tracked in https://github.com/rancher/rancher/issues/21803

**Comment by sangeethah** [comment]
@sowmyav27 Lets wait for #21803 to be available for testing this issue.

**Comment by davidnuzik** [comment]
@sangeethah @alena1108 #21803 has been validated and closed.

**Comment by sowmyav27** [comment]
reproduced the issue on `v2.2.7`

**Steps:**
1. Verify this in 2.2.7 rancher setup
```
root@aa:/var/lib/rancher# kubectl  get authconfigs activedirectory -o yaml
apiVersion: management.cattle.io/v3
kind: AuthConfig
metadata:
  creationTimestamp: 2019-08-06T20:34:12Z
  generation: 1
  labels:
    cattle.io/creator: norman
  name: activedirectory
  resourceVersion: "14201"
  selfLink: /apis/management.cattle.io/v3/authconfigs/activedirectory
  uid: 8d050b1c-b889-11e9-bef3-0242ac110002
type: activeDirectoryConfig
``` 
2. Enable activedirectory auth using valid creds.
3. On doing a `kubectl  get authconfigs activedirectory -o yaml`, it will give you the details used while activating.
4. Disable the auth on the Rancher UI.
5. This is seen - details form the authconfigs are not deleted.
```
root@aa:/var/lib/rancher# kubectl get authconfig activedirectory -o yaml
accessMode: unrestricted
allowedPrincipalIds: null
apiVersion: management.cattle.io/v3
connectionTimeout: 5000
defaultLoginDomain: testad
enabled: false
groupDNAttribute: distinguishedName
groupMemberMappingAttribute: member
groupMemberUserAttribute: distinguishedName
groupNameAttribute: name
groupObjectClass: group
groupSearchAttribute: sAMAccountName
kind: AuthConfig
metadata:
  creationTimestamp: 2019-08-06T22:25:16Z
  generation: 1
  labels:
    cattle.io/creator: norman
  name: activedirectory
  resourceVersion: "1102"
  selfLink: /apis/management.cattle.io/v3/authconfigs/activedirectory
  uid: 10e28985-b899-11e9-b783-0242ac110002
nestedGroupMembershipEnabled: false
port: 389
........
......
```

Verified on fresh install of rancher:master-head - commit id: ``
1. Verify this in 2.2.7 rancher setup
```
root@aS:/var/lib/rancher# kubectl  get authconfigs activedirectory -o yaml
apiVersion: management.cattle.io/v3
kind: AuthConfig
metadata:
  creationTimestamp: 2019-08-06T20:34:12Z
  generation: 1
  labels:
    cattle.io/creator: norman
  name: activedirectory
  resourceVersion: "13440"
  selfLink: /apis/management.cattle.io/v3/authconfigs/activedirectory
  uid: 8d050b1c-b889-11e9-bef3-0242ac110002
type: activeDirectoryConfig
``` 
2. Enable activedirectory auth using valid creds.
3. On doing a `kubectl  get authconfigs activedirectory -o yaml`, it will give you the details used while activating.
4. Disable the auth on the Rancher UI.
5. This is seen - authconfig is cleaned up - details are deleted.
```
root@aS:/var/lib/rancher# kubectl  get authconfigs activedirectory -o yaml
apiVersion: management.cattle.io/v3
kind: AuthConfig
metadata:
  creationTimestamp: 2019-08-06T20:34:12Z
  generation: 1
  labels:
    cattle.io/creator: norman
  name: activedirectory
  resourceVersion: "14201"
  selfLink: /apis/management.cattle.io/v3/authconfigs/activedirectory
  uid: 8d050b1c-b889-11e9-bef3-0242ac110002
type: activeDirectoryConfig
```
