### ISSUE TITLE
Bitbucket cloud Pipeline setup fail (/verify-auth return status: 404 - Not found)

### ISSUE THREAD

**Issue by mhermosi** [rancher/rancher#20321]
Rancher v2.2.2 when Adding Bitbucket pipeline on Cluster > namespace > Tools

the url https:/rancher-host/verify-auth fails with status 404 Not found.

please advise

best
-Martin

**Comment by gitlawr** [comment]
Is it a fresh 2.2.2 install, or it is upgraded from an older version?

**Comment by mhermosi** [comment]
It is a fresh one. I used the existing volume at the beginning but then I removed everything from there and re-started the container to re-generate everything.

it is stand alone container.

No relevant error. (I have on debug mode)

**Comment by mhermosi** [comment]
I was tracing again the rancher logs and no error. I think because service is answering but it is not able to find some page ...

**Comment by mhermosi** [comment]
I am taking a look into rancher/pkg/pipeline/providers/bitbucketcloud/actions.go and was not able to trace back the value of:

toUpdate.RedirectURL = applyInput.RedirectURL 

and 

applyInput := &v3.BitbucketCloudApplyInput{}

I only found /verify-auth on gitlab actions.go file

I hope this can help..

**Comment by gitlawr** [comment]
The redirectURL is part of the action input, so you don't find it in the code but you should be able to see it inspecting the request body of the action.

1. Do you see popup windows that request you to grant permissions on Bitbucket side?
2. If you open browser console's network tab and check the testAndApply action request, do you see `code` properly set?
3. Can you edit your OAuth consumer on Bitbucket and show the configuration?

I got no luck in reproducing this, the above might help us know where we are in an OAuth dance.

**Comment by mhermosi** [comment]
ok.

I think I found the problem... the redirect_uri, I forgot to mention I am behind a firewall so I have a different hostname  at the wan doing NAT to the internal host+port so the popup has the internal hostname which is little frustrating... how to overcome the firewall and different rancher server name ...

Maybe rancher could consider having this scenario.... when you are behind a firewall how to have to server names one for public facing and another internal facing.

**Comment by mhermosi** [comment]
Maybe the Pipeline configuration should have an option to choose or input a different host name if rancher is behind a firewall in that case instead of using the default url  should use the public one.
This may be very needed

**Comment by mhermosi** [comment]
ok Solved.... I just tried connecting using the alternative URL I though it might be based on the used url in the web browser... and voila. it worked. was able to link bitbucket cloud with my rancher.
