### ISSUE TITLE
Backport: Support one click upgrade option for cluster/project monitoring. 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20326]
https://github.com/rancher/rancher/issues/20304

**Comment by sangeethah** [comment]
Available in `v2.2.4-rc8`

**Comment by jiaqiluo** [comment]
Two issues are found and tracked during validating this enhancement
- https://github.com/rancher/rancher/issues/20397
- https://github.com/rancher/rancher/issues/20398

cc @loganhz

**Comment by jiaqiluo** [comment]
This issue is closed since the overall functionality of the 1-click upgrade feature is validated. 
New issues will be made if necessary.
