### ISSUE TITLE
[Windows] Worker disconnected after users updated the rancher server certificate

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20331]
Windows node disconnected after users updated the rancher server certificate

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/pull/21667

**Comment by sowmyav27** [comment]
Verified in custom rancher master-head latest (1 hour cert expiry)

**Steps:**

- Bring up a windows cluster

```
1 etcd/control plane linux node
1 linux worker node
2 windows woker node
```

- Deploy a workload
- wait for the cert to expiry.
- It generates new certs - `Rancher server cert expires at 2019-08-30 18:40:09 +0000 UTC, generating new cert`
- The windows cluster is still up and running - `Active`. Windows worker nodes are also `Active`
- Deploy workloads/ingress. They work as expected.
