### ISSUE TITLE
Save Windows OS Target in user's preferences

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20333]
Steps:

1.  Create a cluster with Windows nodes
2. Deploy a workload and select os target Linux
3. Deploy another workload.

Results:

Windows is selected again.

Expected:

It should select previously selected os.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/6/19)

I can confirm that the OS is remembered now.

- Upon first launch of workload, "Windows" is chosen by default. I instead picked "Linux" and launched a workload.
- Upon second launch of workload now "Linux" is chosen (remembered). Instead picked "Any" and launched a workload.
- Upon third launch of workload now "Any" is chosen (remembered). Instead picked "Windows" and launched a workload.
- Upon the last launch of workload now "Windows" is chosen (remembered).

These tests should sufficiently support that in all cases the OS/Any option is remembered.
