### ISSUE TITLE
Link service containers inside the same stack doesn't works

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#2033]
I created two services inside a stack.

**Apache**
1. Apache container
2. Apache data only container

**MySQL**
1. MySQL container
2. MySQL data only container

That works fine as posted above. But if I add an link between two containers in the same stack it stucks in networking state and won't finished / activated.

Tried to link MySQL to Apache container by add two lines inside the Apache yml definition:

    links:
    - MySQL:db01

Is it a bug or is it not possible to link service containers inside the same stack?

**Comment by deniseschannon** [comment]
Per DockerHub on the MySQL image, you need the link needs to be:

links
  - MySQL-name:mysql

**Comment by pwFoo** [comment]
Yes, but it doesn't work. Name is set by docker-compose.yml and created by rancher-compose.

    MySQL
      name: MySQL

**Comment by deniseschannon** [comment]
Note that the second half of the links  *must* be "mysql"

So in your example it would be:

Links
  - MySQL:mysql

**Comment by pwFoo** [comment]
Wow... sorry. Your right. Changed it and it works fine... solved!

Is it possible to show an error message instead of stuck in networking state?
