### ISSUE TITLE
can't delete load-balancer

### ISSUE THREAD

**Issue by Matrix-Zhang** [rancher/rancher#20335]
for test goal, i deploy rancher on my aliyun's ces server, and create a slb service, of cause the service is always pending, and i tried to delete it, nothing happend...

![图片](https://user-images.githubusercontent.com/1751829/58034137-731b0580-7b58-11e9-8f40-6fac51ef487e.png)

**Comment by loganhz** [comment]
You need to config the cloud provider for Layer 4 LB in k8s

**Comment by Matrix-Zhang** [comment]
how to config it ? my rancher was deploy on aliyun's ces server

**Comment by loganhz** [comment]
https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/master/docs/getting-started.md

**Comment by loganhz** [comment]
https://yq.aliyun.com/articles/626066
