### ISSUE TITLE
Helm template failed

### ISSUE THREAD

**Issue by davidwindell** [rancher/rancher#20337]
Trying to deploy the charts for Eclipse Che and get the error below. Chart can be found at https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm/che

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Add https://github.com/eclipse/che/ as a custom catalog, try deploying the app

**Result:**

```
helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: che-postgres, che-keycloak, che-jaeger, prometheus, grafana\n: exit status 1
```

**Environment information**
- Rancher version: 2.2.2
- Installation option: single
- Docker version: 1.10.3

**Comment by davidwindell** [comment]
I was able to get this chart running by forking the upstream repo, running `helm dep update` and committing the changes. Could this be something that is automated on Rancher's side?

**Comment by cricket007** [comment]
Any updates on this?
