### ISSUE TITLE
Racher v2.2.2 - LDAP Groups for RBAC

### ISSUE THREAD

**Issue by switalski-disney-streaming** [rancher/rancher#20336]
We've been trying to use LDAP Groups for our Rancher v2.2.2 environment.  Unfortunately we've found that it is not working.

Our LDAP endpoint is a FreeIPA node.  We are using the following Schema parameters:
Users:
  - Object Class: inetorgperson
  - Username Attribute: givenName
  - Login Attribute: uid
  - User Member Attribute: memberOf
  - Search Attribute: uid|sn|givenName
  - Disabled Status Bitmask: 0
Groups:
  - Object Class: groupofnames
  - Name Attribute: cn
  - Group Member User Attribute: entrydn
  - Search Attribute: cn
  - Group Member Mapping Attribute: member
  - Group DN Attribute: entrydn

We can successfully enable the FreeIPA authentication access control option.  Our LDAP endpoint shows the following process when we first enable this auth endpoint.

`[20/May/2019:14:36:36.082769565 +0000] conn=22848870 op=1 SRCH base="cn=users,cn=accounts,dc=<removed>,dc=net" scope=2 filter="(&(objectClass=inetorgperson)(uid=switalski))" attrs="distinguishedName memberOf objectClass inetorgperson uid givenName "`
`[20/May/2019:14:36:36.099173716 +0000] conn=22848870 op=2 BIND dn="uid=switalski,cn=users,cn=accounts,dc=<removed>,dc=net" method=128 version=3`
`[20/May/2019:14:36:36.101065640 +0000] conn=22848870 op=2 RESULT err=0 tag=97 nentries=0 etime=0.0002010027 dn="uid=switalski,cn=users,cn=accounts,dc=<removed>,dc=net"`
`[20/May/2019:14:36:36.114271669 +0000] conn=22848870 op=3 SRCH base="uid=switalski,cn=users,cn=accounts,dc=<removed>,dc=net" scope=0 filter="(objectClass=inetorgperson)" attrs="1.1 + * aci"`
`[20/May/2019:14:36:36.234843587 +0000] conn=22848870 op=9 SRCH base="cn=groups,cn=accounts,dc=<removed>,dc=net" scope=2 filter="(&(member=uid=switalski,cn=users,cn=accounts,dc=<removed>,dc=net)(objectClass=groupofnames))" attrs="entrydn member objectClass groupofnames uid cn cn"`

Thus we can successfully see our LDAP users and groups.  We then set our Site Access to "Allow members of Clusters, Projects, plus Authorized Users and Organizations" and include an LDAP group.

We then try to login with a member of the LDAP group and receive the following error:

`Logging in failed: Check credentials, or your account may not be authorized to log in.`

I can assure that the user is a member of the group and verified all the required data is present using an LDAP browser.

My immediate suspicion is that the login process is not following the authentication process outlined here: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/openldap/

`1. When a user attempts to login with his LDAP credentials, Rancher creates an initial bind to the LDAP server using a service account with permissions to search the directory and read user/group attributes.`
`2. Rancher then searches the directory for the user by using a search filter based on the provided username and configured attribute mappings.`
`3. Once the user has been found, he is authenticated with another LDAP bind request using the user's DN and provided password.`
`4. Once authentication succeeded, Rancher then resolves the group memberships both from the membership attribute in the user's object and by performing a group search based on the configured user mapping attribute.`

In the initial authentication setup I can see all of the above steps executed.  However, when I attempt to login with a user who's a member of the group the process is as follows:

`[20/May/2019:14:47:12.363265680 +0000] conn=22859255 op=1 SRCH base="cn=users,cn=accounts,dc=<removed>,dc=net" scope=2 filter="(&(objectClass=inetorgperson)(uid=ss1234))" attrs="distinguishedName memberOf objectClass inetorgperson uid givenName "`
`[20/May/2019:14:47:12.380622737 +0000] conn=22859255 op=2 BIND dn="uid=ss1234,cn=users,cn=accounts,dc=<removed>,dc=net" method=128 version=3`
`[20/May/2019:14:47:12.381373592 +0000] conn=22859255 op=2 RESULT err=0 tag=97 nentries=0 etime=0.0000828174 dn="uid=ss1234,cn=users,cn=accounts,dc=<removed>,dc=net"`
`[20/May/2019:14:47:12.394661580 +0000] conn=22859255 op=3 SRCH base="uid=ss1234,cn=users,cn=accounts,dc=<removed>,dc=net" scope=0 filter="(objectClass=inetorgperson)" attrs="1.1 + * aci"`

As we can observe, step four is never executed.  Since this user is not explicitly defined (aka depends on matching the ldap group), it cannot log into rancher since the login process is not getting a list of groups.

If we explicitly add the user outside of the LDAP group, the user can login and access systems just fine.

I've tried to review the cattle-system namespace logs but did not find anything that (on first glance) pertains to this issue.  I'd greatly appreciate anyone's input regarding this issue.

Thanks!

**Comment by jnicholls** [comment]
I haven't attempted this process yet myself, but I know I will have an identical setup in the near future and would love to see this issue triaged and confirmed, and hopefully able to be resolved in short order. Happy to do the work too with a little direction.

**Comment by switalski-disney-streaming** [comment]
Also, just to further clarify, this issue seems present whether specifying the FreeIPA authentication access control option or the OpenLDAP authentication access control option.  My guess is that they're both using the same LDAP code on the back end.

**Comment by mrajashree** [comment]
Hi @switalski-disney-streaming, can you check if your freeipa server returns the `entrydn` attribute which we use to get group information by running this ldapsearch command?
```
ldapsearch -h <freeipa server> -x -D "<service account >" -W -b "<group search base>" "(&(objectClass=groupofnames)(entrydn=<distinguished name of group you added>))" "*" "+" "1.1"
```
All your server details will go in the angle brackets. Ideally this should return all attributes of that group including a field called `entrydn`

**Comment by switalski-disney-streaming** [comment]
@mrajashree, Thank you so much for your reply.  The issue was related to our FreeIPA endpoint not returning the `entrydn` attribute.

Both my and my colleagues accounts were returning the `entrydn` attribute as our accounts have all access with regards to permissions.  It wasn't until trying it with the service account that I realized the LDAP endpoint wasn't returning the `entrydn` attribute.

For others who might stumble across this, we created a Read Only LDAP role/privilege/permission within FreeIPA that our service accounts use.  This role did not explicitly define that the `entrydn` attribute was allowed.  We needed to add the `entrydn` attribute with both read and search rights to our service account.

Once we added this the service account was able to resolve our LDAP groups.

**Comment by mrajashree** [comment]
Thanks @switalski-disney-streaming for confirming it works now.
Just out of curiosity, do you have steps on how you added that role to your freeipa server? For some reason our test freeipa setup didn't need us to add that role.

**Comment by switalski-disney-streaming** [comment]
For all intensive purposes we're using FreeIPA but we're actually making use of RedHat IDM.  Thus my instructions might differ slightly.

1.) IPA Server --> Role-Based Access Control --> Permissions --> Add
a.) Bind rule type: permission
b.) Granted Rights: read, search
c.) Type: User Group
d.) Effective Attributes: entrydn
2.) IPA Server --> Role-Based Access Control --> Privileges --> Add
a.) add the previous permission
3.) IPA Server --> Role-Based Access Control --> Roles --> Add
a.) Add the service account
b.) Add the privilege

**Comment by mrajashree** [comment]
Thanks!
