### ISSUE TITLE
Move pipelines tab to Tools

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20334]
Now pipelines are in workloads tab.

We are going to add more tabs such as HPA into workloads tab as well.
That page will be too busy.

After discussion, we should move Pipelines list into Tools as well.

**Comment by deniseschannon** [comment]
@loganhz I do not want this in until you talk to @ankur111 about it

**Comment by loganhz** [comment]
A little bit background for it. @ankur111 

When I demoed HPA to the team, Alena, Sheng L and Will think the workloads pages are too busy.
They suggested we should move the pipeline tabs into tools.
So I just filed the issue and you guys can prioritize it.

**Comment by loganhz** [comment]
Fixed in master
