### ISSUE TITLE
[Windows] Update upstream CNI plugins/FlexVolume plugins

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20330]
We should switch the following binaries of rancher/rke-tools:
- [x] Update upstream CNI plugins
   + Related PR: https://github.com/rancher/rke-tools/pull/86
   + Testing: 
     - [ ] Verificate Pod2Pod connectivy
- [x] Update new FlexVolume bundle
  + Related PR: https://github.com/rancher/rke-tools/pull/86
  + Testing:
    - [ ] Verificate SMB storage, guide: https://gist.github.com/thxCode/38dbcf07d8cb8165dc8cbf53ac5167c6#file-local-smb-md
    - [ ] Verificate iSCSI storage, guide: https://gist.github.com/thxCode/38dbcf07d8cb8165dc8cbf53ac5167c6#file-local-iscsi-md

**Comment by alena1108** [comment]
The fix is available in `v0.1.51` rke-tools image version.

**Comment by sowmyav27** [comment]
**On 2.3-head latest**

In a k8s 1.15 cluster Azure custom cluster with 1809 version windows nodes,

- Validated `SMB storage`, using guide: `https://gist.github.com/thxCode/38dbcf07d8cb8165dc8cbf53ac5167c6#file-local-smb-md`

**Comment by kingsd041** [comment]
@thxCode Can you answer the above question?

**Comment by thxCode** [comment]
@sowmyav27 , according to https://kubernetes.io/docs/concepts/storage/volumes/#iscsi:
>  iSCSI volumes can only be mounted by a single consumer in read-write mode - no simultaneous writers allowed.

**Comment by sowmyav27** [comment]
@thxCode in the second step in the below scenario, do we expect an error similar to the one we see when we use block storage - AWS storage ? 
```
1. Deploy a workload with iSCSI storage mounted.
2. Scale up the workload to 2 pods.
3. The pod is deployed successfully
4. The newly created pod CANNOT access the iSCSI storage. 
```

**Comment by thxCode** [comment]
@sowmyav27 , Yes, I think so.

**Comment by sowmyav27** [comment]
Closing this issue.
