### ISSUE TITLE
Error creating vSphere cluster: Error in driver during machine creation: Post https://10.18.59.5:443/sdk: EOF

### ISSUE THREAD

**Issue by zhangsean** [rancher/rancher#20348]
I met an error in creating vSphere cluster in the Rancher UI.

Setup steps:
1. Add Cloud Credential point to my vCenter [10.18.59.5]
1. Add Node Template with vSphere type.
1. Add Cluster with vSphere node template.
1. Go to new cluster nodes list, I saw the following logs:
```
(worker1) Downloading management-state/node/nodes/worker1/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros-vmware.iso ...
(worker1) Creating VM ...
(worker1) Uploading Boot2docker ISO ...
...
(worker1) Waiting for VMware Tools to come online...
... A few seconds later ...
Error creating machine: Error in driver during machine creation: Post https://10.18.59.5:443/sdk: EOF
```
Then after a few seconds, the node was auto removed and a new node come up in `Provisioning` status showing the above logs in loop.

In vCenter, I saw the vm was created and started up normally into Rancher OS welcome information, but a while later, the vm was deleted. Then a new vm was created and deleted in loop.

Rancher UI screenshot:
![image](https://user-images.githubusercontent.com/2536402/58073038-1c531180-7bd4-11e9-86e7-a7bf3f519e41.png)
vCenter screenshot:
![image](https://user-images.githubusercontent.com/2536402/58073201-94213c00-7bd4-11e9-9888-cb0926660bd0.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`authenticated.cluster.nodes.index`|
|vCenter|v6.7|

**Comment by AntonSmolkov** [comment]
@zhangsean hi!
I’v got the same issue with Rancher 2.3.7 and Vsphere 6.5.  
How did you solve it? Was there smth Wrong with vcenter?
