### ISSUE TITLE
Cannot load cluster edit page as user

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#20340]
_NOTE:_ not to be confused with https://github.com/rancher/rancher/issues/20292 or https://github.com/rancher/rancher/issues/12038 but may be related

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create do cluster as admin
2. create user
3. edit cluster and add user as member
4. log in to user and attempt to edit cluster

**Result:**
edit view won't load:
![image](https://user-images.githubusercontent.com/19376037/58040544-9b6c1b00-7aea-11e9-9486-f541da120792.png)

**Other details that may be helpful:**
Console error:
![image](https://user-images.githubusercontent.com/19376037/58040596-b3dc3580-7aea-11e9-955d-06577e05933b.png)

Logs:
`2019/05/20 17:22:05 [INFO] Starting cluster agent for c-9nw2v [owner=true]
2019/05/20 17:22:05 [INFO] Creating clusterRole for roleTemplate Project Owner (project-owner).
2019/05/20 17:22:05 [INFO] Creating clusterRole for roleTemplate Project Owner (project-owner).
2019/05/20 17:22:05 [INFO] Creating clusterRole for roleTemplate Cluster Owner (cluster-owner).
2019/05/20 17:22:05 [INFO] Creating clusterRole for roleTemplate Cluster Owner (cluster-owner).
2019/05/20 17:22:05 [ERROR] ProjectRoleTemplateBindingController p-db8d2/creator-project-owner [cluster-prtb-sync] failed with : couldn't ensure roles: couldn't create role project-owner: clusterroles.rbac.authorization.k8s.io "project-owner" already exists
2019/05/20 17:22:05 [INFO] Creating clusterRole for roleTemplate Project Owner (project-owner).
2019/05/20 17:22:05 [INFO] Creating clusterRole project-owner-promoted for project access to global resource.
2019/05/20 17:22:05 [INFO] Creating clusterRole for roleTemplate Project Owner (project-owner).
2019/05/20 17:22:05 [INFO] Creating clusterRole for roleTemplate Cluster Owner (cluster-owner).
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-ns7cmsjh5e Role cluster-owner
2019/05/20 17:22:06 [ERROR] ClusterAlertRuleController c-9nw2v/node-disk-running-full [cluster-alert-rule-deployer] failed with : update cluster c-9nw2v failed, Operation cannot be fulfilled on clusters.management.cattle.io "c-9nw2v": the object has been modified; please apply your changes to the latest version and try again
2019/05/20 17:22:06 [ERROR] ClusterRoleTemplateBindingController c-9nw2v/creator-cluster-owner [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
2019/05/20 17:22:06 [INFO] Updating clusterRole project-owner-promoted for project access to global resource.
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role cluster-owner
2019/05/20 17:22:06 [ERROR] ClusterAlertGroupController c-9nw2v/kube-components-alert [cluster-alert-group-deployer] failed with : update cluster c-9nw2v failed, Operation cannot be fulfilled on clusters.management.cattle.io "c-9nw2v": the object has been modified; please apply your changes to the latest version and try again
2019/05/20 17:22:06 [ERROR] ClusterAlertRuleController c-9nw2v/high-cpu-load [cluster-alert-rule-deployer] failed with : update cluster c-9nw2v failed, Operation cannot be fulfilled on clusters.management.cattle.io "c-9nw2v": the object has been modified; please apply your changes to the latest version and try again
2019/05/20 17:22:06 [ERROR] ClusterAlertRuleController c-9nw2v/no-leader [cluster-alert-rule-deployer] failed with : update cluster c-9nw2v failed, Operation cannot be fulfilled on clusters.management.cattle.io "c-9nw2v": the object has been modified; please apply your changes to the latest version and try again
2019/05/20 17:22:06 [ERROR] ClusterAlertRuleController c-9nw2v/high-number-of-leader-changes [cluster-alert-rule-deployer] failed with : update cluster c-9nw2v failed, Operation cannot be fulfilled on clusters.management.cattle.io "c-9nw2v": the object has been modified; please apply your changes to the latest version and try again
2019/05/20 17:22:06 [ERROR] ClusterAlertGroupController c-9nw2v/node-alert [cluster-alert-group-deployer] failed with : update cluster c-9nw2v failed, Operation cannot be fulfilled on clusters.management.cattle.io "c-9nw2v": the object has been modified; please apply your changes to the latest version and try again
2019/05/20 17:22:06 [ERROR] RoleTemplateController cluster-owner [cluster-roletemplate-sync] failed with : couldn't ensure roles: couldn't create role cluster-owner: clusterroles.rbac.authorization.k8s.io "cluster-owner" already exists
2019/05/20 17:22:06 [ERROR] RoleTemplateController project-owner [cluster-roletemplate-sync] failed with : couldn't ensure roles: couldn't create role project-owner: clusterroles.rbac.authorization.k8s.io "project-owner" already exists
2019/05/20 17:22:06 [ERROR] ProjectRoleTemplateBindingController p-db8d2/creator-project-owner [cluster-prtb-sync] failed with : couldn't ensure roles: couldn't create role project-owner: clusterroles.rbac.authorization.k8s.io "project-owner" already exists
2019/05/20 17:22:06 [ERROR] ClusterAlertGroupController c-9nw2v/etcd-alert [cluster-alert-group-deployer] failed with : update cluster c-9nw2v failed, Operation cannot be fulfilled on clusters.management.cattle.io "c-9nw2v": the object has been modified; please apply your changes to the latest version and try again
2019/05/20 17:22:06 [ERROR] ClusterAlertGroupController c-9nw2v/event-alert [cluster-alert-group-deployer] failed with : update cluster c-9nw2v failed, Operation cannot be fulfilled on clusters.management.cattle.io "c-9nw2v": the object has been modified; please apply your changes to the latest version and try again
2019/05/20 17:22:06 [INFO] Creating clusterRole for roleTemplate Create Namespaces (create-ns).
2019/05/20 17:22:06 [INFO] Creating user for principal system://p-db8d2
2019/05/20 17:22:06 [INFO] Creating user for principal system://p-frt7j
2019/05/20 17:22:06 [INFO] Creating globalRoleBindings for u-hwuid6zgvp
2019/05/20 17:22:06 [INFO] Creating globalRoleBindings for u-kmcdtdlrrl
2019/05/20 17:22:06 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-wsdqf
2019/05/20 17:22:06 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-wsdqf for user u-hwuid6zgvp with role cattle-globalrole-user
2019/05/20 17:22:06 [INFO] Creating clusterRoleBinding for project access to global resource for subject user-r6mdz role p-frt7j-namespaces-edit.
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role admin
2019/05/20 17:22:06 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-4mz69
2019/05/20 17:22:06 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-4mz69 for user u-kmcdtdlrrl with role cattle-globalrole-user
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole p-frt7j-projectmember
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role project-owner
2019/05/20 17:22:06 [INFO] Creating clusterRole for roleTemplate Project Member (project-member).
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for membership in project p-frt7j for subject u-hwuid6zgvp
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role project-owner
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole p-db8d2-projectmember
2019/05/20 17:22:06 [INFO] Creating clusterRoleBinding for project access to global resource for subject user-r6mdz role project-owner-promoted.
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role project-owner
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating clusterRoleBinding for membership in cluster c-9nw2v for subject u-hwuid6zgvp
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role project-owner
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating role project-member in namespace c-9nw2v
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for membership in project p-db8d2 for subject u-kmcdtdlrrl
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role project-owner
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating clusterRoleBinding for membership in cluster c-9nw2v for subject u-kmcdtdlrrl
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-hwuid6zgvp with role project-member in namespace 
2019/05/20 17:22:06 [INFO] Creating clusterRole for roleTemplate Project Member (project-member).
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role project-owner
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating role edit in namespace p-frt7j
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-kmcdtdlrrl with role project-member in namespace 
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating role project-member in namespace p-frt7j
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-hwuid6zgvp with role edit in namespace 
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating role project-member in namespace p-db8d2
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-hwuid6zgvp with role project-member in namespace 
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating role edit in namespace p-db8d2
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-kmcdtdlrrl with role project-member in namespace 
2019/05/20 17:22:06 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-kmcdtdlrrl with role edit in namespace 
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role admin
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role admin
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role project-member
2019/05/20 17:22:06 [INFO] Creating clusterRoleBinding for project access to global resource for subject user-r6mdz role project-owner-promoted.
2019/05/20 17:22:06 [ERROR] ProjectRoleTemplateBindingController p-db8d2/u-kmcdtdlrrl-member [cluster-prtb-sync] failed with : couldn't ensure roles: couldn't create role project-member: clusterroles.rbac.authorization.k8s.io "project-member" already exists
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-kmcdtdlrrl Role edit
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role admin
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role admin
2019/05/20 17:22:06 [INFO] Creating roleBinding User user-r6mdz Role admin
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role edit
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role edit
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role project-member
2019/05/20 17:22:06 [INFO] Creating clusterRoleBinding for project access to global resource for subject user-r6mdz role create-ns.
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-kmcdtdlrrl Role project-member
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role project-member
2019/05/20 17:22:06 [INFO] Creating clusterRoleBinding for project access to global resource for subject user-r6mdz role p-db8d2-namespaces-edit.
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-kmcdtdlrrl Role project-member
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role project-member
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role edit
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role project-member
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role edit
2019/05/20 17:22:06 [INFO] Creating clusterRole project-member-promoted for project access to global resource.
2019/05/20 17:22:06 [INFO] Updating clusterRoleBinding clusterrolebinding-sqqfc for project access to global resource for subject user-r6mdz role project-owner-promoted.
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role edit
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role edit
2019/05/20 17:22:06 [INFO] Creating roleBinding User u-hwuid6zgvp Role project-member
2019/05/20 17:22:06 [INFO] Creating clusterRole project-member-promoted for project access to global resource.
2019/05/20 17:22:06 [INFO] Updating clusterRoleBinding clusterrolebinding-x5tt9 for project access to global resource for subject user-r6mdz role project-owner-promoted.
2019/05/20 17:22:06 [INFO] Updating clusterRole project-member-promoted for project access to global resource.
2019/05/20 17:22:06 [ERROR] ProjectRoleTemplateBindingController p-db8d2/u-kmcdtdlrrl-member [cluster-prtb-sync] failed with : couldn't create role project-member-promoted: clusterroles.rbac.authorization.k8s.io "project-member-promoted" already exists
2019/05/20 17:22:06 [INFO] Updating clusterRoleBinding clusterrolebinding-6kzlx for project access to global resource for subject user-r6mdz role create-ns.
2019/05/20 17:22:06 [INFO] Handling backend connection request [c-9nw2v:m-ckv6f]
2019/05/20 17:22:06 [INFO] Deleting roleBinding clusterrolebinding-l4rrl
2019/05/20 17:22:06 [INFO] Deleting roleBinding clusterrolebinding-5f7xf
2019/05/20 17:22:06 [INFO] Deleting roleBinding clusterrolebinding-zj8zk
2019/05/20 17:22:06 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-hwuid6zgvp role p-frt7j-namespaces-edit.
2019/05/20 17:22:06 [INFO] Deleting roleBinding clusterrolebinding-sgb27
2019/05/20 17:22:06 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-kmcdtdlrrl role p-db8d2-namespaces-edit.
2019/05/20 17:22:06 [INFO] Deleting roleBinding clusterrolebinding-sgb27
2019/05/20 17:22:06 [INFO] Deleting roleBinding clusterrolebinding-d9862
2019/05/20 17:22:06 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-hwuid6zgvp role project-member-promoted.
2019/05/20 17:22:06 [INFO] Deleting roleBinding clusterrolebinding-h9zj7
2019/05/20 17:22:07 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-hwuid6zgvp role project-member-promoted.
2019/05/20 17:22:07 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-kmcdtdlrrl role project-member-promoted.
2019/05/20 17:22:07 [INFO] Deleting roleBinding clusterrolebinding-fqv6l
2019/05/20 17:22:07 [INFO] Deleting roleBinding clusterrolebinding-l4rrl
2019/05/20 17:22:07 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-hwuid6zgvp role create-ns.
2019/05/20 17:22:07 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-kmcdtdlrrl role project-member-promoted.
2019/05/20 17:22:07 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-kmcdtdlrrl role create-ns.
2019/05/20 17:22:13 [INFO] Handling backend connection request [c-9nw2v:m-ckv6f]
2019/05/20 17:22:16 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10270
2019/05/20 17:22:17 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"c-9nw2v:m-ckv6f","addresses":["134.209.170.184"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-k4bbr","allNodes":false},{"nodeName":"c-9nw2v:m-ckv6f","addresses":["134.209.170.184"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-k4bbr","allNodes":false}]]
2019/05/20 17:22:18 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"c-9nw2v:m-ckv6f","addresses":["134.209.170.184"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-k4bbr","allNodes":false},{"nodeName":"c-9nw2v:m-ckv6f","addresses":["134.209.170.184"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-k4bbr","allNodes":false}]]
2019/05/20 17:22:18 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"c-9nw2v:m-ckv6f","addresses":["134.209.170.184"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-k4bbr","allNodes":false},{"nodeName":"c-9nw2v:m-ckv6f","addresses":["134.209.170.184"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-k4bbr","allNodes":false}]]
2019/05/20 17:22:18 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/05/20 17:22:24 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10594
2019/05/20 17:22:25 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/05/20 17:22:28 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
E0520 17:22:28.830385       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.830926       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.830933       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
2019/05/20 17:22:28 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
E0520 17:22:28.831268       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.831322       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.831612       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.831757       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.832044       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.832174       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.832210       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.832510       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.833225       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.833269       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.837087       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.837485       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.837598       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.837852       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.838129       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.838362       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.838420       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.839068       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.839147       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.839197       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.839265       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.839351       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.839400       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.839435       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
E0520 17:22:28.839507       7 streamwatcher.go:109] Unable to decode an event from the watch stream: tunnel disconnect
2019/05/20 17:22:30 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10328
2019/05/20 17:22:30 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/05/20 17:22:34 [INFO] Handling backend connection request [c-9nw2v]
2019/05/20 17:22:59 [INFO] [mgmt-auth-crtb-controller] Creating clusterRoleBinding for membership in cluster c-9nw2v for subject u-qkpp9
2019/05/20 17:22:59 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-member in namespace c-9nw2v
2019/05/20 17:22:59 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-qkpp9 with role cluster-member in namespace 
2019/05/20 17:22:59 [INFO] Creating clusterRole for roleTemplate Cluster Member (cluster-member).
2019/05/20 17:22:59 [INFO] Creating roleBinding User u-qkpp9 Role cluster-member
`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:master
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
rke

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/29/19)

I no longer observe the issue. My other user (cluster member) can successfully edit the cluster. I do not get any errors in logs as well.
