### ISSUE TITLE
Change default K8s version for amazonElasticContainerServiceConfig

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20342]
Version: Master (v2.3) (5/20/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Inspect default of kubernetesVersion of /v3/schemas/amazonElasticContainerServiceConfig

**Result:**
Notice it is old 1.10. We should consider changing this to the latest, 1.12.
In the UI we cannot pick 1.10 any longer so the UI does what it can and picks 1.11. We should be picking the latest 1.12 and need the backend to change the default for this to happen.

**Comment by rmweir** [comment]
@cjellick @davidnuzik I changed it to 1.13 now that it is the latest and the default used by EKS.

**Comment by izaac** [comment]
Rancher Version: master-head (v2.3) (08/21/2019)

1.13 is now the default version in the latest build.

<img width="1261" alt="Screen Shot 2019-08-21 at 1 16 18 PM" src="https://user-images.githubusercontent.com/27659/63468075-ccc2f280-c41b-11e9-95cf-819821fce46a.png">

Provisioning the new cluster with it selected created the cluster and the driver is displayed as:

**v1.13.8-eks-a977ba**
