### ISSUE TITLE
Backport: Upgrade rancher helm version

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#20358]
Backport for v2.2 
helm --set for out of order list values
Original issue: rancher/rancher#20310

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc7`

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.4-rc7

* Reproduce original issue in v2.2.3
* Access rancher pods and see the correct helm version: 
  * `HELM_URL_amd64=https://github.com/rancher/helm/releases/download/v2.10.0-rancher11/helm`
* Launch app from test catalog
* App does not fail when launching
