### ISSUE TITLE
support cloud credentials (ssh key) for openstack driver, rancher 2.2.3 or later

### ISSUE THREAD

**Issue by fgeorgatos** [rancher/rancher#20351]
**What kind of request is this (question/bug/enhancement/feature request):**

enhancement

**Steps to reproduce (least amount of steps as possible):**

install 2.2.3 and inspect under node-template/cloud-template

**Result:**

cloud credentials should have openstack as an option in the drop down menu

**Other details that may be helpful:**

It could be that the quick resolution for now is to provide explicit documentation about what is the expected way, to feed the ssh keys for openstack k8s clusters. I was able to make it work by planting it on the relevant pods, but the process is cumbersome in an HA setup and not very friendly for long term maintenance.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

2.2.3

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
openstack
```

- Docker version (use `docker version`):

```
N/A
```

gz#4572

**Comment by DJAyth** [comment]
Agreed. Was just looking at this in my setup and thought to look to see if it exists.

**Comment by fgeorgatos** [comment]
This is still outstanding: **cloud credentials should have openstack as an option**

In fact, let's stretch the goal, somewhat: **could there be a solution which allows to mix-and-match cloud credentials?**
