### ISSUE TITLE
Rancher enforces arbitrary limit on autoscaling nodes in GKE clusters

### ISSUE THREAD

**Issue by ebauman** [rancher/rancher#20355]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Setup & install rancher 
2. Attempt to provision a GKE cluster, and set Node Pool Autoscaling > Maximum Node Count to any value greater than 5. 

**Result:**
The UI will not allow you to perform this action. It resets the input field to a maximum of 5. *This also applies to minimum nodes*. 

**Other details that may be helpful:**

It was determined that this was a limit being enforced by the UI, and not for any meaningful reason. I propose removal of this arbitrary limit to allow customers full functionality of GKE-provisioned clusters. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.3
- Installation option (single install/HA): HA

**Comment by davidnuzik** [comment]
Note, this was recently tested against upcoming v2.2.5 release in issue #20936 see https://github.com/rancher/rancher/issues/20936#issuecomment-504596880 for details on the testing results.

This validation test does the same checks but against the last master build. I already replicated in that issue.

Version: master-head (6/21/19) latest UI

I performed the same checks as in the backport issue.
I am able to create a cluster with min/max greater than 5.
I also did some checks with other amounts like min 1 max 1 again.

This is working as expected now.
