### ISSUE TITLE
Feature request: Allow creation of alarms without a notifier

### ISSUE THREAD

**Issue by Heiko-san** [rancher/rancher#20352]
If you try to create an alert (or an alert group in Rancher >2.2) you are forced to add at least one notifier (tested with alert group in v2.2.3 and alert in v2.1.9).
This is since you can't remove the last notifier input line and can't leave it empty ... error: Recipient required

However since we plan to poll alerts via the rancher API (/v3/clusterAlertRules/) to show them in our custom monitoring system, we would like to be able to create new alert groups without "dummy-notifiers" (alert groups would suffice since we plan to move on to 2.2.X).

**Comment by davidnuzik** [comment]
This features exists in v2.3 (latest master) once  v2.3 is released this will be available.
