### ISSUE TITLE
Move k8s metadata from rke and types to the dedicated repo "rancher/kontainer-driver-metadata"

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20368]
Today k8s metadata is scattered around rke and types repos. We have to:

* Move metadata to its own repo - rancher/kontainer-driver-metadata
* Refactor RKE code to work with the externalized data

**Comment by jiaqiluo** [comment]
The feature is tested by using testing Rancher images and forked The feature is implemented by introducing a new setting and a new action 
```
v3/settings/rke-metadata-url - the branch and url to the metadata repo 
v3/kontainerdrivers          - refresh to fetch new metadata in Rancher 
```

It is tested by using testing Rancher images and forked `kontainer-driver-metadata` Github repo.

Steps:
- run Rancher-testing:v2.3.3
- in Rancher, change the value of `v3/settings/rke-metadata-url` to the forked `kontainer-driver-metadata` Github repo
- in Rancher, check the k8s list: v1.12.4-rancher1-1 (default), v1.13.1-rancher1-1(experimental)
- in kontainer-driver-metadata, add a new k8s minor version v1.12.10-rancher1-1
- in kontainer-driver-metadata, add a new k8s major version v1.16.0-rancher1-1
- generate new metadata and push to Github
- in Rancher, refresh `v3/kontainerdrivers`

Result:
- the k8s list reflects the changes, meaning it shows newly-added v1.12.10-rancher1-1 as default and v1.16.0-rancher1-1 as experimental
- also checked the v3/settings and see proper values in the follow filed
```
- ui-k8s-supported-versions-range 
- ui-k8s-default-version-range 
- k8s-version-to-images
- k8s-versions-current
- k8s-version
- k8s-version-to-service-options
```
- also tested upgrading existing clusters from the older versions to newly-added versions
- also tested upgrading Rancher from v2.2.5 to master-head
