### ISSUE TITLE
Service gets to "active" state , when containers are still being created for services started with label=io.rancher.container.start_once set to true.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2036]
Server version - Build from master - Sep 14

Steps to reproduce the problem:

Create a service with label -  io.rancher.container.start_once set to true and scale set to 3.
Activate service.
Service gets to "active" state even before containers get to "running" state.

**Comment by sangeethah** [comment]
Tested with build from master - Oct 8.

Automated test cases relating to io.rancher.container.start_once set to true succeeds now.

**Comment by tobowers** [comment]
Still seeing this on v0.42-rc3 but nn further inspection, we don't have start_once set... we're using that stdin: open and cat trick that was needed before start_once. We'll switch over to start_once and see if it still fails. Seems like still a bug doing it the "old" way though.
