### ISSUE TITLE
PVC resize is not working through the UI but it works when importing pvc yaml file 

### ISSUE THREAD

**Issue by sensre** [rancher/rancher#20362]
*PVC resize is not working through the UI but it works when importing pvc yaml file*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.5` UI: `v2.1.19` |
|Route|`authenticated.cluster.storage.persistent-volumes.index`|

**Comment by tfiduccia** [comment]
I can't reproduce this - @davidnuzik can you take a look.

**Comment by davidnuzik** [comment]
Version: v2.1.5, UI: v2.1.9

I too was unable to reproduce. I created a PV. I was able to edit it and change the PV size without any issues. The UI correctly did this then verified via kubectl that the change took effect.

**Comment by deniseschannon** [comment]
@sensre If you can reproduce this on a modern version, please re-open.
