### ISSUE TITLE
Template Driven Cluster Creation

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20371]
Cluster admin wants to create a new cluster. He has been told that his template covers all the security requirements. All he needs to do is to create a new cluster from the specified template.

Enforced/Protected settings cannot be changed by the cluster admin
Rest are modifiable

**Comment by soumyalj** [comment]
Tested with master build. 
Logged in as standard user
Created Cluster template through API
Created template revision creation by providing cluster config parameters through API 
Created cluster through API by choosing cluster template and template revision and it was functional

**Comment by soumyalj** [comment]
Tested using master-head build from July 9th.
Created a cluster template T1 and template revision R1 using UI successfully.
Created a cluster using the template revision R1 derived from template T1. 
[Cluster can be created by choosing template revision only]
Cluster was created successfully with the right k8s version as provided in the template. 
This use case worked for both admin and standard user.
