### ISSUE TITLE
Cluster Template Creation

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20370]
Admin creates the template using almost the same UI as “Add Cluster”.

After filling out all the details/settings, he sees an option to save the current cluster as a template. 

UI Vs YAML

We are talking about 100+ settings. We cannot offer these as UI options. Probably YAML will be a better way to present these options to the users (we ship default YAML so that the users don’t have to create one from scratch)

**Comment by soumyalj** [comment]
Tested with master build. 
Cluster template and template creation through API is functional.
Basic use case cases for template revision creation by providing different cluster config parameters through API were successful.

**Comment by soumyalj** [comment]
Tested using master-head build from July 9th.
Created a cluster template and template revision using UI successfully
