### ISSUE TITLE
Bug: download of node key results in network error on Google Chrome

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#20377]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Attempt to download keys for a node provisioned by Rancher.

**Result:**
Downloads fails with "Network Error"

**Other details that may be helpful:**
If you click the up arrow and click resume download will work.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.2.3
- Installation option (single install/HA): HA

**Comment by vincent99** [comment]
This will be fixed in 2.2.4: https://github.com/rancher/rancher/issues/19702 (The comments say 2.2.3 but that became a small patch release for one specific issue)
