### ISSUE TITLE
rancher alpha repo

### ISSUE THREAD

**Issue by miahwk** [rancher/rancher#20383]
$ helm search rancher
rancher-alpha/rancher   2.3.0-alpha3    v2.3.0-alpha3   Install Rancher Server to manage Kubernetes clusters acro...
But when I want to install the rancher,just give the error.

Error: failed to download "rancher-alpha/rancher" (hint: running `helm repo update` may help)

anyone have some ideas? Please help me,thank you.

**Comment by khauser** [comment]
Did you execute `helm repo add rancher-alpha https://releases.rancher.com/server-charts/alpha`?

**Comment by miahwk** [comment]
@khauser yes. I did that. 
![image](https://user-images.githubusercontent.com/20128378/58159056-4bd64c80-7cae-11e9-841f-88ee5fe0c14e.png)

**Comment by miahwk** [comment]
@khauser 
![image](https://user-images.githubusercontent.com/20128378/58159211-98ba2300-7cae-11e9-8e39-a290cb52d54e.png)

**Comment by khauser** [comment]
So `helm upgrade rancher rancher-alpha/rancher --version=2.3.0-alpha3 --set hostname=<yours>` fails?

**Comment by miahwk** [comment]
Yes. I install the new rancher. 
`helm install rancher-alpha/rancher --name rancher --namespace cattle-system --set hostname=rancher-test.ptit365.com --set ingress.tls.source=secret`
It's failed.

**Comment by miahwk** [comment]
@khauser It is ok now. i just add `--version=2.3.0-alpha3`. Nad it is working. Thank you for help.

**Comment by user-name-is-taken** [comment]
Just wanted to add that you can see the available versions of the latest chart for example with:

```
$ helm search repo rancher-latest/rancher --versions
```
