### ISSUE TITLE
Rancher v2.2.4-rc7  Rook Helm chart will not install

### ISSUE THREAD

**Issue by dsargent3220** [rancher/rancher#20389]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1.  In global Catalogs add the rook-release catalog: https://charts.rook.io/release/
2.  Create a project with an "Unrestricted" pod security policy and switch to it.
3.  In Apps search for rook and deploy v1.0.1  No changes to yaml files are necessary unless your nodes have taints.

**Result:**
In Rancher v2.2.3 three deployments are created and the rook-ceph operator is deployed
In Rancher v2.2.4-rc7 the following error is immediately thrown
```Failed to install app rook-ceph. Error: UPGRADE FAILED: Get https://localhost:443/k8s/clusters/c-l8rtd/api/v1/namespaces/rook-ceph/configmaps?labelSelector=NAME%!D(MISSING)rook-ceph%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp: lookup localhost on 10.100.0.11:53: no such host```
Note that 10.100.0.11 is our local DNS server.  It is referencing localhost for some reason.

**Other details that may be helpful:**
This worked in 2.2.3, then broken when I upgraded our test Rancher server to 2.2.4-rc7.  I reverted Rancher back to 2.2.3 and it immediately worked again.  
I use the same cleanup steps each time, including removing the rook-ceph namespaces and ensuring all global objects are removed and the rook folders on the target nodes are cleaned up if needed.

**Environment information**
- Rancher version v2.2.4-rc7 
- Installation option single on CentOs

**Cluster information**
- Cluster type Custom
- Machine type VM, CentOs, 3 workers, each worker is 4 cores and 16 gigs of RAM
- Kubernetes version (use `kubectl version`): 1.13.5

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Docker version (use `docker version`):

Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by bmdepesa** [comment]
Related: https://github.com/rancher/rancher/issues/20289

**Comment by guangbochen** [comment]
hi @dsargent3220 can you please provide the details of the `/etc/hosts` of your rancher server host.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/20289

**Comment by dsargent3220** [comment]
Sure, here it is
```[root@lpul-ranchertest ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
:1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.105.111.112  lpul-ranchertest.ad.selinc.com  lpul-ranchertest```
