### ISSUE TITLE
Adding acme-domain environment variable

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#20385]
Right now --acme-domain is just a command line option however to get rancher running on azure container service you can just modify environment variables, so it might be useful to add an environment variable for it as well:

https://github.com/rancher/rancher/blob/274d059936b2fd6bc401e38b9da646cf6b58f086/main.go#L101

**Comment by jgrumboe** [comment]
Thanks @galal-hussein . I tried this one locally and also ran my locally built docker image with ACME_DOMAIN - works great :)

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version b160c76c8`

Deploy with:
`docker run -d -e  ACME_DOMAIN=<Domain Name> --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master-head`

Rancher Logs show environment variable was recognized.
`2019/11/15 20:15:58 [INFO] Rancher arguments {ACMEDomains:[Domain Name]AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:}
2019/11/15 20:15:58 [INFO] Listening on /tmp/log.sock`
