### ISSUE TITLE
[Question] Change install from imported cluster to custom

### ISSUE THREAD

**Issue by ElGranLoky** [rancher/rancher#20399]
**Steps to reproduce (least amount of steps as possible):**
1.- Install RKE in a custom nodes with docker
2.- Install HELM 
3.- Install Rancher in HA and launch 
4.- Import the RKE cluster
5.- Create a new cluster with custom nodes from rancher 

**Result:**
- 2 cluster
   - 1 cluster import with rancher in HA
   - 1 cluster with custom nodes  
<img width="720" alt="Rancher" src="https://user-images.githubusercontent.com/2712200/58211760-2c124900-7ced-11e9-915b-c233a63fc5e1.png">

** Question **
* How can install rancher HA in a custom cluster instead of a imported cluster?, or 
* how can migrate the rancher install from one cluster to the other?

**Environment information**
- Rancher version 2.2.3
- Installation option HA

**Comment by loganhz** [comment]
It's not supported. Close this issue as it's a [Question]. Please feel free to file a [RFE] ticket
