### ISSUE TITLE
Monitoring - project Prometheus can't fetch metrics from the namespace moved from another project

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20390]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.2.4-rc6
- add an EC2 cluster
- add project p1 and namespace ns1 in p1 
- add project p2
- enable project monitoring in p1 and p2
- deploy workload wl1 with custom metrics in p1
- check p1's project Prometheus to confirm it fetch metrics from wl1
- move ns1 to p2
- check p2's project Prometheus 

**Result:**
-  p2's project Prometheus cannot fetch metrics from wl1
- the target list does not have wl1's endpoint
<img width="1246" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58195048-ea958580-7c7b-11e9-9f04-4e26f2264593.png">

**Comment by alena1108** [comment]
The fix will be available in rancher/rancher:v2.2.4-rc14

**Comment by jiaqiluo** [comment]
The issue is re-opened because the metrics can be fetched by the project Prometheus in both the old and new projects now. 

The bug fix is validated on a freshly installed v2.2.4-rc15

Steps:
- log in as admin, enable Github Auth, add Github user `user1` and `user2` as standard users
- log in as Github user `user1`, create an EC2 cluster
- add Github user `user2` as the cluster member
- log in as `user2`, create a new project `p1` and enable project monitoring 
- deploy a workload `wl-1` with custom metrics (image: loganhz/web) in namespace `ns-1`
- go to the project's Prometheus's page
- confirm that Prometheus fetches metrics from `wl-1`
-  create a new project `p2` and enable project monitoring 
- move the namespace `ns-1` to the project `p2`

Results:
- confirm that project `p2` Prometheus fetches metrics from `wl-1`, which is expected!
- but project `p1` Prometheus also fetches metrics from `wl-1`, which is not expected
- after 30 mins, the project `p1` Prometheus still can fetch metrics from `wl-1`

**Comment by jiaqiluo** [comment]
Update: Come back to check the project `p1` Prometheus after 3 hours,  the `wl-1` is removed from the Targets list and the Configuration

**Comment by orangedeng** [comment]
I tried to reproduce it with your steps, and the `wl-1` from p1's prometheus was removed in a few minutes.

**Comment by orangedeng** [comment]
There will be a delay between the new target is added into the prometheus configuration and the prometheus begins to scrape the metrics from the metrics. It is because the prometheus configuration configmap is mounted as file in prometheus pod. There will be a delay that the mounted file updates after the configmap is updated. From Kubernetes document:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

**Comment by loganhz** [comment]
Filed a new issue for the delay https://github.com/rancher/rancher/issues/20539

cc @alena1108 @jiaqiluo @sangeethah

**Comment by jiaqiluo** [comment]
Test again on v2.2.4-rc18 with the same steps, and the `wl-1` is removed from the Targets list and the Configuration on the old project's Prometheus in 3 mins.
