### ISSUE TITLE
Monitoring - failed to upgrade project monitoring which is enabled before upgrading Rancher

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20397]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.2.1
- add a single-node cluster
- enable cluster monitoring and project monitoring 
- upgrade Rancher to v2.2.4-rc8
- go to the project monitoring page
- check the checkbox `Upgrade monitoring to the latest version` and click `Save`
<img width="1410" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58209419-ed07d780-7c9b-11e9-94fb-9250c59c715b.png">

**Result:**
- The app `project-monitoring` failed to upgrade
<img width="1420" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58209566-25a7b100-7c9c-11e9-87da-85a6432985e1.png">
<img width="1395" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58209570-27717480-7c9c-11e9-9e7e-fd0aa3e436f7.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.1 -> v2.2.4-rc8
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4 vCPU, 8GB Ram
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
18.9.6
```

**Comment by loganhz** [comment]
We don’t support this upgrade path. Users need to disable project monitoring first if they upgrade from 2.2.1. This will be in release note

**Comment by loganhz** [comment]
It should be related to https://github.com/helm/helm/issues/1996
