### ISSUE TITLE
CoreDNS as a supported default DNS provider for Rancher provisioned clusters 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20395]
We have enabled support for coreDNS as an alternative provider to kubedns: https://github.com/rancher/rke/issues/722

As CoreDNS support was officially enabled by default in k8s 1.13 - you no longer have to pass `feature-gates=CoreDNS` api server param to make it work, we have to invest into making it a default dns provider for Rancher provisioned clusters.

**Comment by deniseschannon** [comment]
Make sure to update docs to remove "experimental"

**Comment by sangeethah** [comment]
Tested with rancher server build from latest master build.

k8s 1.14 and k8s 1.15 clusters now use CoreDNS as default DNS provider.


<img width="1292" alt="Screen Shot 2019-07-02 at 4 00 47 PM" src="https://user-images.githubusercontent.com/4266958/60552150-97830980-9ce2-11e9-9b9f-a66a88db23da.png">
