### ISSUE TITLE
Monitoring - upgrade project monitoring does not upgrade the app monitoring-operator

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20398]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- run Rancher v2.2.1 
- add an EC2 cluster (1 etcd, 1 control plane, 3 workers) 
- enable cluster monitoring and project monitoring 
- upgrade Rancher to v2.2.4-rc8 
- go to the project monitoring page 

- check the checkbox `Upgrade monitoring to the latest version` and click `Save`

**Result:**
- The app `project-monitoring` upgrades to `v0.0.3`
- the app `monitoring-operator` under namespace `System` is not upgraded 
<img width="1492" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58210001-107f5200-7c9d-11e9-82ca-77a361610399.png">

**Comment by jiaqiluo** [comment]
The same result is observed on the cluster which only project monitoring is enabled, 
Steps: 
- the same as the issue except the cluster monitoring is NOT enabled   

Result: 
- app `project-monitoring` upgrades to v0.0.3
- app `monitoring-operator` does not upgrade, still be v0.0.2

**Comment by loganhz** [comment]
Operator is in System project. Project owner doesn’t have permission to upgrade operator app.

**Comment by loganhz** [comment]
And it will impact all project monitoring apps across the cluster. So i think it’s not a good idea to upgrade it in project level monitoring page

**Comment by sangeethah** [comment]
“Operator is in System project. Project owner doesn’t have permission to upgrade operator app.” — When project owner enables , he has the ability to deploy Operator which is in System project . If this is allowed when enabling project , why would you not allow a project owner to do this as part of upgrading project monitoring ? 
“And it will impact all project monitoring apps across the cluster. So i think it’s not a good idea to upgrade it in project level monitoring page” — > This is the same impact we will have when “Cluster Monitoring” is enabled were we enable operator and all project level monitoring which might continue to be in older versions will be impacted.

**Comment by loganhz** [comment]
> “Operator is in System project. Project owner doesn’t have permission to upgrade operator app.” — When project owner enables project monitoring , he has the ability to deploy Operator which is in System project . If this is allowed when enabling project , why would you not allow a project owner to do this as part of upgrading project monitoring ? 

When enable Project monitoring, it's not project owner deploy the Operator. There is a controller in rancher server, the controller will deploy the Operator on demand. Currently is Operator is shared by cluster alerting, cluster monitoring and project monitoring in each project. Our current one click upgrade is an UI stuff. It will send out API calls to rancher. If the project owner doesn't have the System project access, Project owner will not be able to upgrade the Operator in UI.

> “And it will impact all project monitoring apps across the cluster. So i think it’s not a good idea to upgrade it in project level monitoring page” — > This is the same impact we will have when “Cluster Monitoring” is upgraded were we upgrade operator and all project level monitoring which might continue to be in older versions will be impacted.

Operator is kind of a cluster level component. Cluster owner should maintain the version of it. As the Operator is shared by alerting, cluster monitoring and project monitoring in each projects, it doesn't make sense to let a project owner to decide the Operator version and when to upgrade.

> Also since we are sharing operator between cluster monitoring app and project monitoring app  , are we saying that the operators are always going to be backwards compatible ? Meaning older version of operator will work with  new version of  project monitoring app and newer version of operator will work with existing version (not upgraded) version of project monitoring app ?

Yes, actually we don't have to upgrade Operator at all. It is backwards compatible. 

> If you had a cluster , where cluster level monitoring was never enabled , but projects have monitoring enabled. How would the operator ever be upgraded in this case ? Project owners will never get access to upgrading operator in this case. We expect global admin/Cluster owner to upgrade the operator in this case?

Even we don't upgrade Operator, project monitoring still works. We didn't change the image for operator when we release a new version of monitoring. But yes, in the case you mentioned, we should have cluster owner or global admin to upgrade the Operator version manually in System project. Operator is a cluster level component, if 10 projects are using the same Operator. It doesn't make sense to let the project owner of a project to decide when to upgrade the version.

**Comment by MKlimuszka** [comment]
This is specific to an old version of project monitoring v1, which is EoL and replaced by project monitoring v2
