### ISSUE TITLE
Azure AD Integration

### ISSUE THREAD

**Issue by awebsterHW** [rancher/rancher#20393]
When attempting to log into the portal with my Azure AD, I received:
![Rancher_AzureADlogin](https://user-images.githubusercontent.com/46532965/58198531-6c95a680-7c9c-11e9-9734-23a6c1e0ae1a.png)

 
I then logged in with the local admin user account and looked at the authentication settings, in which I noticed that the Azure user groups were no longer “fetchable”:
 
![Rancher_authentication](https://user-images.githubusercontent.com/46532965/58198567-7cad8600-7c9c-11e9-9d73-f766d506964c.png)

**Comment by amagura** [comment]
Your application secret for Rancher <-> Azure AD has expired.
