### ISSUE TITLE
Kubernetes cluster v1.11.9 to v1.13.5 upgrade failed to upgrade kube-proxy

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#20404]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch Rancher single host install v2.2.3
2. Add a custom cluster with Kubernetes v1.11.9. One node with worker, etcd, control plane roles.
3. Launch a new RancherOS 1.5.1 VM and run agent from step 2.
4. Once Kubernetes is finished installing, edit the cluster, change version to v1.13.5 and click Save.

**Result:**
According to UI, cluster upgrade was successful. However, the kube-proxy docker container still appears to be running 1.11.9:
```
[rancher@ip-10-0-0-10 ~]$ docker ps -a | grep hyperkube
a836adc6331b        rancher/hyperkube:v1.13.5-rancher1                "/opt/rke-tools/entr…"   8 minutes ago       Up 8 minutes                                     kubelet
6f58315a43f2        rancher/hyperkube:v1.13.5-rancher1                "/opt/rke-tools/entr…"   8 minutes ago       Up 8 minutes                                     kube-scheduler
145c912619cd        rancher/hyperkube:v1.13.5-rancher1                "/opt/rke-tools/entr…"   8 minutes ago       Up 8 minutes                                     kube-controller-manager
3181763f7c5a        rancher/hyperkube:v1.13.5-rancher1                "/opt/rke-tools/entr…"   8 minutes ago       Up 8 minutes                                     kube-apiserver
4f7716a89023        rancher/hyperkube:v1.11.9-rancher1                "/opt/rke-tools/entr…"   14 minutes ago      Up 7 minutes                                     kube-proxy
```
Noticed this error in the rancher logs:
```
2019/05/22 23:49:37 [ERROR] ClusterController c-r7cpp [cluster-provisioner-controller] failed with : [workerPlane] Failed to bring up Worker Plane: [Can't stop Docker container [kube-proxy] for host [10.0.0.10]: error during connect: Post http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/containers/kube-proxy/stop?t=5: tunnel disconnect]
```
However, according to the docker ps output, kube-proxy was stopped and started.

Suggested course of action - 1) if an attempt to upgrade a Kubernetes component fails, it should be retried. 2) UI should not report upgrade as successful when not everything was upgraded.

**Other details that may be helpful:**
Full rancher logs attached for reference.
[rancher.log](https://github.com/rancher/rancher/files/3210492/rancher.log)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.3
RancherOS 1.5.1

- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom on AWS

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud, t3a.medium in AWS.

- Kubernetes version (use `kubectl version`):
After upgrade:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
[rancher@ip-10-0-0-10 ~]$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
Possible parts of fixing this:

- Improve RKE behavior on errors, create loops to retry. We've seen other issues where the error was `could not remove container` but it was actually removed on the host, just delayed after the error but it already error'd out on the first error.
- Cluster state is changing and is applied (this is an upgrade but in general, any change in the spec triggers provisioning), but there is no such thing as validation. Making the provisioning more resilient is definitely solving part of the problem, and then erroring out should retry cluster provisioning. This can also include checking if the launched container is according to spec for instance.

**Comment by tobru** [comment]
I'm facing the same / a similar issue with one node on a three node cluster while upgrading from 1.13 to 1.14 with Rancher 2.2.5. The upgrade went through, all `rancher/hyperkube` images were updated to `v1.14.3-rancher1` except on one node, the kube-proxy still is `v1.13.5-rancher1`. The Rancher webinterface shows the cluster version as 1.14, whereas the node list lists every node still as 1.13, although `kubectl get nodes` shows 1.14 on every node. How can I fix this manually so that kube-proxy is upgraded as well and the node version is correct in the webinterface of Rancher?

**Comment by thbiela** [comment]
@tobru I also have this issue. Have you figured out a solution?

**Comment by tobru** [comment]
Sadly no.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.2.8 to v2.3.0-rc9 on a HA setup. K8s upgraded from v1.13.10-rancher1-2 to v1.3.11-rancher1-1
Verified that kube-proxy upgraded to the new version correctly on all the nodes.
```
c7bdb00434fe        rancher/hyperkube:v1.13.11-rancher1   "/opt/rke-tools/entr…"   20 hours ago        Up 20 hours                                   kube-proxy
aa0ff2ae94c2        rancher/hyperkube:v1.13.11-rancher1   "/opt/rke-tools/entr…"   20 hours ago        Up 20 hours                                   kubelet
e1f37cf6c2bf        rancher/hyperkube:v1.13.11-rancher1   "/opt/rke-tools/entr…"   20 hours ago        Up 20 hours                                   kube-scheduler
c404ce3a9f50        rancher/hyperkube:v1.13.11-rancher1   "/opt/rke-tools/entr…"   20 hours ago        Up 20 hours                                   kube-controller-manager
0b059e73f51a        rancher/hyperkube:v1.13.11-rancher1   "/opt/rke-tools/entr…"   20 hours ago        Up 20 hours                               

```

**Comment by sowmyav27** [comment]
Verified on an upgrade from `rancher:v2.2.8` to `rancher:v2.3.0-rc9`.
k8s upgrade from `v1.14.6-rancher1-1` to `v1.15.4rancher1-1`, `v1.12.10-rancher1-2` to `v1.15.4-rancher1-1` and `v1.14.6-rancher1-1` to `v1.14.7-rancher1-1`
Verified that kube-proxy upgraded to the new version correctly on all the nodes.
