### ISSUE TITLE
Monitoring - refine the UX for monitoring 1-click updating feature

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20400]
Enhancement

Now in order to upgrade cluster/project monitoring, we need to 
- go to the cluster/project monitoring page
- check the box `Upgrade monitoring to the latest version` and click `Save`

<img width="1410" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58209419-ed07d780-7c9b-11e9-94fb-9250c59c715b.png">

It will be more user-friendly if we can
- make the 1-click upgrade feature as a button instead of a checkbox, and show the button only when it is available
- also, show the current version and the target version

**Comment by loganhz** [comment]
I think we need to have Vince to review the design.

**Comment by loganhz** [comment]
We should add upgrade available info in cluster dashboard, so users can notice that. Click the button it will take users to the monitoring setting page.

![image](https://user-images.githubusercontent.com/21168270/58268301-c8a11d80-7db7-11e9-98ae-ee9186b799aa.png)

Make the text bold in setting page

![image](https://user-images.githubusercontent.com/21168270/58268762-a22fb200-7db8-11e9-8087-a545b28f237c.png)

**Comment by loganhz** [comment]
I don't think 2 button makes sense, 

if users changed some other fields and click the upgrade button, should we save the change for them as well? The text of the 2 buttons should be `upgrade monitoring only` / `save` or `upgrade monitoring and save` / `Save only`

**Comment by deniseschannon** [comment]
Monitoring version should be controlled as an additional setting for the feature. 

**Monitoring Version**
dropdown of monitoring
**Monitoring Option**
current disply of all the options

In the dropdown, when enabling monitoring for the first time, we should only show the latest available version. 

If monitoring is already enabled and new versions have been made available, we should show the current version deployed and any newer versions. 

When you click Save, it would save the version of what should be deployed.

**Comment by jiaqiluo** [comment]
The enhancement is validated on Rancher: master 1161061 upgraded from v2.2.2

<img width="1471" alt="Screen Shot 2019-06-05 at 3 59 45 PM" src="https://user-images.githubusercontent.com/6218999/58995926-f79d9300-87aa-11e9-9a00-e57b6f44051d.png">

**Comment by jiaqiluo** [comment]
The Project Monitoring on the setup upgrade from v2.2.1 to master
<img width="1477" alt="Screen Shot 2019-06-05 at 4 20 50 PM" src="https://user-images.githubusercontent.com/6218999/58996630-f883f400-87ad-11e9-838c-d52a8c900c5d.png">
