### ISSUE TITLE
Catalog auto-refreshing updates unchanged templates every hour 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20403]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

This is observed on both v2.1.8 and v2.2.4-rc6 while I was validating this issue: https://github.com/rancher/rancher/issues/19574

**Steps to reproduce (least amount of steps as possible):**
I run Rancher `v2.1.8` and `v2.2.4-rc6` on two identical VM (t2.large, 2 vCPU, 8GB RAM )

For both of them:
- add a single-node custom cluster (t2.xlarge, 4 vCPU, 16 GB RAM)
- enable catalogs `Helm Stable` and `Helm Incubator`
- add catalogs  `bitnami` (https://charts.bitnami.com) and `gitlab` (https://charts.gitlab.io)
- add 5 more catalogs (duplicates of https://git.rancher.io/charts)
 - leave the setup for couple hours
<img width="1401" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57816451-33a38200-7730-11e9-9fe4-607090de26a2.png">

**Result:**
The log shows that Rancher upgrades the catalog every hour, and it upgrades almost the same number of catalogs and templates each time. But if I go to the catalog's git repo, for example, bitnami (https://github.com/bitnami/charts/commits/master),  I can see that the last commit is 9 hours ago at the time I check, which means there are no changes in the catalog for the past 9 hours, but somehow Rancher thinks the catalog has some changes and fetches all the templates, again and again, each hour.
 

```
2019/05/22 22:18:46 [INFO] Updating global catalog helm-incubator
2019/05/22 22:18:47 [INFO] Catalog sync done. 0 templates created, 5 templates updated, 0 templates deleted
2019/05/22 22:18:47 [INFO] Updating global catalog helm
2019/05/22 22:18:48 [INFO] Updating global catalog bitnami
2019/05/22 22:18:50 [INFO] Catalog sync done. 0 templates created, 9 templates updated, 0 templates deleted
2019/05/22 22:18:53 [INFO] Catalog sync done. 0 templates created, 23 templates updated, 0 templates deleted
``` 

This shows the lines contains `Updating global catalog`
```
2019/05/22 18:18:46 [INFO] Updating global catalog helm-incubator
2019/05/22 18:18:47 [INFO] Updating global catalog helm
2019/05/22 18:18:47 [INFO] Updating global catalog bitnami
2019/05/22 19:18:46 [INFO] Updating global catalog helm-incubator
2019/05/22 19:18:47 [INFO] Updating global catalog helm
2019/05/22 19:18:47 [INFO] Updating global catalog bitnami
2019/05/22 20:18:46 [INFO] Updating global catalog helm-incubator
2019/05/22 20:18:47 [INFO] Updating global catalog helm
2019/05/22 20:18:47 [INFO] Updating global catalog bitnami
2019/05/22 21:18:46 [INFO] Updating global catalog helm-incubator
2019/05/22 21:18:47 [INFO] Updating global catalog helm
2019/05/22 21:18:47 [INFO] Updating global catalog bitnami
2019/05/22 22:18:46 [INFO] Updating global catalog helm-incubator
2019/05/22 22:18:47 [INFO] Updating global catalog helm
2019/05/22 22:18:48 [INFO] Updating global catalog bitnami
```

**Comment by rohitsakala** [comment]
This is catalogv1 and it is deprecated and the rancher version is EOL. Current version don't have this problem.
