### ISSUE TITLE
Closing Cluster Log Collection Manually Deletes Cattle-Logging and Reopens Invalid

### ISSUE THREAD

**Issue by Hwting** [rancher/rancher#20408]
**What kind of request is this (question/bug/enhancement/feature request):bug

**Steps to reproduce (least amount of steps as possible):
* Creating Cluster Log Collection

* Configure Kafka Click Save

* Check that cattle-logging has a corresponding pod

* Delete cattle-logging project and close cluster log collection:None

* Save in reconfiguration Kafka to see if cattle-logging is not creating the corresponding fluentd-anent
**Result:
No corresponding fluentd-anent is created under cattle-logging
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.2.2
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):cloud 4 vCPU 8 GiB
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Docker version 17.03.2-ce, build f5ec1e2
```

**Comment by aiwantaozi** [comment]
@Hwting I couldn't reproduce. Could you try the latest version?
