### ISSUE TITLE
Default cluster alerts / alert groups don't seem to work.

### ISSUE THREAD

**Issue by Heiko-san** [rancher/rancher#20409]
Hi, 

we use Rancher v2.2.3 and the "integrated" prometheus/alert manager instances.
The default alerts that ship with a new Rancher K8s cluster (and own alerts created in the default alert-groups) don't seem to work at all (they never seem to fire if the limit is hit).
As far as I can tell this is due to the alert manager that gets deployed only if you create your own alert groups.

**What kind of request is this:**

* Bug Report

**Steps to reproduce:**

* create a fresh cluster (we used K8s v1.13.5-rancher1-2)
* enable monitoring
* create an alert in an existing alert group (e.g. "A set of alerts for kube components") that should fire due  to the defined limit (e.g. "cluster:memory_usage:ratio > 0.001") and note that it doesn't ever fire (switch its state from "active" to "alerting")
* have a look at "cattle-prometheus" namespace and note there is no "alertmanager-cluster-alerting" deployed
* create a new/own alert-group with the very same alert
* have a look at "cattle-prometheus" namespace and note "alertmanager-cluster-alerting" now is deployed
* note that the alert (at least the one in the new alert-group, for the other see "Other details that may be helpful") will fire now

**Result:**

* Before creating an own alert-group: no alert manager is present, therefore no alerts ever fire
* After creating an own alert-group: alert manager is present, therefore alerts work now

**Other details that may be helpful:**

There is still a portion of the problem I don't understand:
While writing this I could not get the original alert (the one under "A set of alerts for kube components") to fire, even after the alert manager was deployed.
However I'm absolutely certain that in similar experiments yesterday I managed to get firing alerts in the default alert-groups, too.

**Environment information**
- Rancher version: v2.2.3
- Installation option (single install/HA): HA, vmware, on-premise

**Cluster information**
* Cluster type: HA, vmware, on-premise, created via rancher
* Machine type and specifications: TYPE: vmware CPU: 2 MEM: 4GB
* Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by aiwantaozi** [comment]
@Heiko-san Could you check:
**If the alertmanager hasn't deployed:**
1. check the rancher server's logs for the deploy related error

**if alertmanager was deployed and satisfy the  alert condition but alert doesn't fire:**
1. If you use express metric alert, first check whether prometheus trigger the alert(click the link in cluster-monitoring app then you could access prometheus UI)
2. then check whether alertmanager receive the trigger from prometheus(alertmanager UI could be accessed by clicking the link in cluster-alerting app).
3. If the alert manager receives the alert event, but email/slack... haven't received alert event, check the alertmanager log and notifier configure.
