### ISSUE TITLE
Increase elasticsearch log precision

### ISSUE THREAD

**Issue by kinolaev** [rancher/rancher#20405]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Activate Elasticsearch logging at cluster level.

**Result:**
Log timestamp contains only seconds.

**Other details that may be helpful:**
This was already reported rancher/rancher#17238 and partially fixed rancher/rancher#17239 but then lost during refactoring #20243.
Actual PR #20230.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.3
- Installation option (single install/HA): ha

**Comment by bmdepesa** [comment]
rancher/rancher:master ddf43bdb

* Created cluster
* Enabled cluster logging
* Log statements show nanoseconds:
`Jun 17 23:23:03 rancher-logging-fluentd-bp6zf ranchertest: log:I0617 23:22:57.740011`
