### ISSUE TITLE
etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-scheduler\" " with result "range_response_count:1 size:440" took too long (199.032407ms) to execute

### ISSUE THREAD

**Issue by ibayue** [rancher/rancher#20406]
As shown in the screenshot, this read-only occurs very frequently.

![image](https://user-images.githubusercontent.com/11729209/58241234-2107f900-7d7f-11e9-9dad-98e0d59dc202.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`containers.index`|

**Comment by dhrn** [comment]
same here, any workaround available?

**Comment by vishen** [comment]
@ibayue we are also seeing this issue on our rancher clusters, did you find the reason or a fix for this?

**Comment by loganhz** [comment]
link to https://github.com/etcd-io/etcd/issues/10174

**Comment by fabiorauber** [comment]
I'm also seeing these messages in etcd when the timeouts mentioned in https://github.com/rancher/rancher/issues/21587 occur.

**Comment by adhomdom** [comment]
I was also seeing this, coming from the current rancher:stable image, creating a new cluster on bare-metal. As a result, couldn't register an etcd node.

Downgrading to rancher:v2.2.0 resolved the issue, so I've tagged v2.2.0 in our private repo as stable (didn't use an rc, but accept that I might have trouble upgrading in future).
