### ISSUE TITLE
[UI] Displayed Hostname w/ AWS Cloud is Given Hostname not Requested Hostname

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#20411]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Deploy nodes using node-templates with a cluster that's setup with AWS cloud provider. 

**Result:**

Ultimately when the host is provisioned it's hostname on the physical box and therefore the one reported in the UI is ip-A-B-C-D.

However when you edit the node, it states that the "reported hostname by the node operating system" is the hostname that was generated apart of the node pool.

This makes it very difficult to understand what workload is running where unless I manually go in an edit the custom name for each node in the pool which sorta defeats the purpose of the node pool to begin with.

**Other details that may be helpful:**

You can override this via the custom name and it will then show the custom name field, but it should show the generated hostname to begin with.

It is however not setting the requestHostname properly on the OS, to do this, dynamic userdata would need to be generated to ensure that the custom hostname gets passed to the cloudinit system properly.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.1
- Installation option (single install/HA): HA

**Comment by vincent99** [comment]
"requested" here really means "what we told docker-machine to call it"... _Most_ providers use that to set the display name (in their UI) and hostname (on the VM, which gets picked up in ours), but Amazon's driver doesn't.

**Comment by ekristen** [comment]
Fair enough, perhaps a UI feature to prefer displaying requested vs actual? 

This is also a good segue into a feature request, dynamic UserData -- with node pools dynamically populate user data and expose user data to the end user to modify when creating a node pool, that way additional tweaks can be made to the cloud-init process, which would mean setting of hostname in AWS.

**Comment by vincent99** [comment]
Yeah not saying we can't necessarily do something about it, just that's why it currently is that.

**Comment by ekristen** [comment]
Fair enough. I appreciate the feedback.
