### ISSUE TITLE
Support unsecure registries through Docker Machine

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2041]
The Docker machine that is running, by default, cannot launch VMs/Hosts with unsecured registries.  This can be achieved by starting DM with --engine-insecure-registry myregistry:5000.  In the Host Registration page, we should provide means to specify this before starting up GMS+DM.

**Comment by cjellick** [comment]
Done as part of the last upgrade to machine

**Comment by sangeethah** [comment]
UI support for  --engine-insecure-registry is not available and this is tracked in #2913

**Comment by sangeethah** [comment]
Tested with latest build from master - Dec 8

Had a insecure registry set up in <ipaddress>:5000 with few images.

Add a host by passing "engineInsecureRegistry" set to "<ipaddress>:5000"  to create_machine api.
Docker machine gets installed on this host with  "--insecure-registry" set in /etc/default/docker.

Able to start containers on this host using images that are hosted in this insecure registry with image as "<ipaddress>:5000/<name of the image>".
