### ISSUE TITLE
Rancher 1.6.26 ignoring required conatiner label w/ Scheduler 0.8.6

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#20414]
It seems that with the latest version of 0.8.6 scheduler that hosts marked with "required container label" are no longer being honored.

**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Add a label to a host under "Require Container Label" and then schedule containers.

**Result:**

Rancher Scheduler no longer honoring required container labels. 

**Other details that may be helpful:**

We've been on 1.6.26 for a while, but only recently had an opportunity to upgrade the infrastructure services. After the upgrade of infrastructure services we noticed containers getting scheduled to our edge nodes that have the "required container label" enabled.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 1.6.26
- Installation option (single install/HA): HA

**Comment by alena1108** [comment]
@ekristen what was the previous version of scheduler where things were working as expected for you?

**Comment by ekristen** [comment]
I'm not sure there's anyway for me to know that for sure now but I want to say 0.8.3.

**Comment by alena1108** [comment]
@ekristen knowing the previous version would help to identify the point where it started breaking, thanks for your help with investigation!

**Comment by ekristen** [comment]
Ok, I just reviewed my notes and a downgraded one of my environments. It seems like I can definitely say that 0.8.3 seems to work ok and to my knowledge I wasn't ever on any other version after that until 0.8.6. 

What I'm seeing is the following behavior ...
* Globally deployed services IGNORE the container label requirement -- I thought global obeyed this too, but perhaps I'm wrong
* Random services that are *NOT* global are being scheduled on container label required hosts

I downgraded and re-upgraded and I am not able to reproduce this manually at the moment, however I'm looking at one other environment where there are containers that most definitely are NOT globally scheduled and the do NOT have the `edge=true` label and yet they are scheduled on my edge nodes that have container label `edge=true` set as a required label.

**Comment by ekristen** [comment]
Are there any other conditions when the scheduler would ignore the required container label rule? 

I've been seeing containers/services jump to servers all week that they shouldn't be on, but I can't reproduce on purpose. It's generally happened when a server has gone unavailable or we did a catalog upgrade with a start before stop rule in place.

**Comment by ekristen** [comment]
I'll keep monitoring. Myself and two of my coworkers witnessed this behavior on more than one occasion since the upgrade. I'll provide any other details that I can as soon as I can.

**Comment by alena1108** [comment]
@ekristen thank you, and please keep us posted. The only changes between 0.8.3 and 0.8.6 are log level changes, and shouldn't have caused the discrepancy you are seeing for non-global services.

@StrongMonkey pointed out that container labels are not working with the global servicehttps://rancher.com/docs/rancher/v1.6/en/cattle/scheduling/#finding-hosts-with-container-labels. So the global service behavior you are seeing, is a known limitation.
