### ISSUE TITLE
Template Sharing

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20417]
Templates can be shared or made private.Private - created by an admin for personal use onlyPublic - created by the admin for the purpose of enforcement 

Selective templates can be shared/made private.

**Comment by soumyalj** [comment]
Tested with master-head build. 
Template sharing feature is functional . Templates can be shared with other users as "member", "owner", "read-only" . Users have the correct access types on the templates as they have been assigned. 
Also, Public templates can be created and they are available for all users to create clusters. 

Related issues: 
https://github.com/rancher/rancher/issues/21414
https://github.com/rancher/rancher/issues/21401
