### ISSUE TITLE
UI for CIS Security Scan

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20425]
This ticket is to track UI for https://github.com/rancher/rancher/issues/18600

**Comment by deniseschannon** [comment]
@alena @leodotcloud i know that some of the API is already available for UI to consume, but not sure how much.

@tfiduccia can you work with backend (alena/murali) and discuss what we think the UX of this feature would entail? please include @codyrancher

**Comment by lvuch** [comment]
https://xd.adobe.com/view/12803751-70ec-46b9-5396-7907b7d6f9ff-64b1/

**Comment by deniseschannon** [comment]
Is there a mock of the detailed view of each scan? @lvuch @tfiduccia

**Comment by sowmyav27** [comment]
**Verified on master-head.**

- UI for cis scans is:
<img width="1291" alt="Screen Shot 2019-12-12 at 7 59 09 PM" src="https://user-images.githubusercontent.com/26032343/70768451-13fe2780-1d1a-11ea-8c56-aa239e9638d0.png">

**Scan details page:**
<img width="1292" alt="Screen Shot 2019-12-12 at 8 00 51 PM" src="https://user-images.githubusercontent.com/26032343/70768466-1f515300-1d1a-11ea-9c9e-3a6a9ae4c235.png">

Separate bugs have been logged to track other issues on the UI.
