### ISSUE TITLE
Template Enforcement

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20420]
Global admin wants to ensure that the templates can be applied when specific users/roles create new clusters.

All new clusters automatically inherit the properties above.

3 Options:

Single Template Enforced - the user cannot choose the template. It is automatically applied (but the user is informed which template was applied)

Choose from available Templates - if more than 1 template is enforced

Create a cluster without any template - same workflow as today

**Comment by ankur111** [comment]
- Only Global Admin can enforce templates
- "enforcement" implies that cluster admins must use one of the enforced template for cluster creation (no option to create a cluster without a template)
- once enforcement flag is on, globally public templates get enforced 
- templates created by cluster admins and made public should not be enforced (global admin cannot verify 100s of templates that may be created by others)
- if cluster admin would like to have their own template in a list of enforced template, they must work with the global admin to get their templates added to the list of globally enforced templates (how? new UI? or just email and request for review will suffice? global admin can review and then copy this template, make it public so it gets enforced too)

## Why cluster admins cannot enforce their own templates?
This will enable them to bypass the global enforcement. 

## Problems with this approach?
slightly complex workflow to get my template in the list of enforced templates 

## advantages of this approach?
allows global policy enforcement

**Comment by prachidamle** [comment]
@ankur111 In the above enforcement requirements, want to confirm this:
"once enforcement flag is on, globally public templates get enforced" - Does this translate to "once enforcement flag is on, only templates that are created by a global admin (any global admin) and made public, should be available for cluster creation by any user."

**Comment by ankur111** [comment]
@prachidamle - i think the right question to ask is - do all public templates (created by anybody) get enforced?
The answer - No. Because this means that any user (including malicious users) can create a bad template, make it public and then just wait for the global admin to turn enforcement on.
Also, what if the enforcement flag is already on?
As a bad user, i can create a bad template and make it public and then continue to create clusters with this bad template - thereby bypassing all the security policies for which templates were created in the first place

**Comment by prachidamle** [comment]
ok @ankur111 when you say 
"do all public templates (created by anybody) get enforced?", "The answer is No"

Then which public templates get enforced? how does global admin specify them? 
- does global admin provide a list of public templates to be enforced? OR
- do all public templates owned/created by global admin become enforced?

**Comment by ankur111** [comment]
Ideally, the global admin should choose which templates will be enforced from the list of available (public) templates. 
If that's not possible (and the enforcement flag is public only), we can limit enforcement to the templates created by global admin only. 
If there are multiple global admins - each has the right to make all global admin created templates public.

**Comment by prachidamle** [comment]
@ankur111 @alena1108 pls confirm this is what we are going with:
1) Enforcement will be a global setting that global admin can turn ON
2) When global admin turns Enforcement ON, Global Admin should choose from the list of public templates, the templates that should be enforced. UI should guide this.
3) During cluster creation, only the public templates that are marked as enforced by the global admin can be used.
4)With Enforcement ON, rest all functionalities - create/update/share templates will still be available to all users as before. Only cluster creation will be template enforced.

**Comment by sangeethah** [comment]
```
2. When global admin turns Enforcement ON, Global Admin should choose from the list of public templates, the templates that should be enforced. UI should guide this.
```
@prachidamle Why do we restrict list of enforced templates to be global ?

**Comment by ankur111** [comment]
We are asking admins to take an additional step (enable "Template Creation" capability) before the capability is usable. 
Instead, I will prefer if the capability to create templates is turned on by default for global and cluster admins. 
Let them create as many templates as they want and use it. 
When the time comes for enforcement, global admin will come and enforce templates. He may choose to delete the unusable templates and also revoke permissions at that time. 
This is an advanced use case. No reason for us to penalize/prevent people from using templates in the first place.

**Comment by prachidamle** [comment]
This is the recent design of "cluster template enforcement" captured from slack conversations. @ankur111 @vincent99 can you mark this ok.

- We will add a new global role 'Manage Cluster Templates'
- By default, only admins and users with this role can create templates. The current role 'Standard User' will NOT have the ability to create clustertemplates.
- Standard user should be able to GET and USE templates which are shared with them.  Only admin or user with manage cluster template role should be able to CREATE new templates/revision
- Admin may assign this global role to specific users per his discretion.
- Sharing a template with "owner/member" access with a standard user lets the user get/use the template and edit existing template/revisions. But they cannot create new revision unless they have been assigned the 'Manage Cluster Templates' role.

- When enforcement setting is ON, it means clusters can be created via template only. Clusters cannot be created without a clustertemplate. Global Admin can still create clusters without a template.
- Users can create clusters with templates that they can see. [created by them or have been shared with them]

**Comment by soumyalj** [comment]
Tested with master-head build from July 22.  Template enforcement as described above is functional.
Some of the use cases tested. 
1. With enforcement ON, verified that clusters can be created only using templates . Global admins can create clusters with and without templates
2. Verified that only users with global role "Create Cluster templates" can create new templates. Admins can assign this role to specific users
3. Verified that standard users can create clusters with the templates that are shared with them by global admins
