### ISSUE TITLE
Show Last Run and Result for the scan

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20421]
Last Run - 03/21/2019 (12:54 PM)Results - 4 failures (clickable link to download the report)

**Comment by sowmyav27** [comment]
**Verified on latest master-head.**

- UI shows a the scan reports like
<img width="1291" alt="Screen Shot 2019-12-12 at 7 59 09 PM" src="https://user-images.githubusercontent.com/26032343/70768418-e1542f00-1d19-11ea-81bc-2393e8c836ac.png">

- there are links to download and delete the report.
