### ISSUE TITLE
Generate A Scan Report

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20423]
A JSON and a text version is acceptable. 

The report should be readable.

Show only failures, nodes failed, and remediation steps

Allow users to download the report with a single click (JSON and text formats will do for now)

**Comment by vincent99** [comment]
I would think at least the JSON version would include every test and the pass/fail status, so that a UI could be constructed to show the whole result.

**Comment by deniseschannon** [comment]
This will be tracked with other issues from the API and UI issues.
