### ISSUE TITLE
[Windows] Rancher doesn't currently allow 2 certs in the serverca file

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20436]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Create a standalone rancher server by following the instructions at: https://rancher.com/docs/rancher/v2.x/en/installation/single-node/
-- For SSL we’re using the instructions described at OPTION B-BRING YOUR OWN CERTIFICATE: SELF-SIGNED
-- We’re using image: rancher/rancher:v2.3.0-alpha3

- Configure AD authentication

- Create a new custom cluster with Kubernetes v1.14.1:
-- Register one Ubuntu 16.04 node with Docker 18.9.6 using all the roles (etcd, control and worker). Wait until the node is active.
-- Register one Ubuntu 16.04 node with Docker 18.9.6 using only the worker role. Wait until the node is active.
-- Register one Windows Server 2019 node 18.9.6 using only the worker role.
--- When running the registration command as instructed in the Rancher UI, we get the error:

```
Status: Downloaded newer image for rancher/rancher-agent:v2.3.0-alpha3

ERRO[0000] The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
```

**Other Useful Info:**
```
C:\etc\kubernetes\ssl\certs\serverca

-----BEGIN CERTIFICATE-----
xxxx
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
xxxx
-----END CERTIFICATE-----
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.0-Alpha

**Comment by thxCode** [comment]
I have submitted a PR to fix this: https://github.com/rancher/rancher/pull/20441, as a workaround for now, you could execute in `powershell` as below:
```
# go into rancher agent directory
cd c:\etc\rancher

# modify the run.ps1 file
notepad.exe run.ps1

###notepad###
#     #import the self-signed certificate#
#-    $cacertsBytes = [Convert]::FromBase64String((Get-Content "$SSL_CERT_DIR\serverca" | select -Skip 1 | select -SkipLast 1))
#-    $cacertsFile = "$env:TEMP\serverca.cer"
#-    Set-Content -Value $cacertsBytes -Path $cacertsFile -Encoding Byte
#-    Import-Certificate -CertStoreLocation 'Cert:\LocalMachine\Root' -FilePath $cacertsFile | Out-Null
#-    rm -Force $cacertsFile -ErrorAction Ignore
#+    $caBytes = $null
#+    Get-Content "$SSL_CERT_DIR\serverca" | % {
#+        if ($_ -match '-+BEGIN CERTIFICATE-+') {
#+            $caBytes = @()
#+        } elseif ($_ -match '-+END CERTIFICATE-+') {
#+            $caTemp = New-TemporaryFile
#+            Set-Content -Value $caBytes -Path $caTemp.FullName -Encoding Byte
#+            Import-Certificate -CertStoreLocation 'Cert:\LocalMachine\Root' -FilePath $caTemp.FullName | Out-Null
#+            $caTemp.Delete()
#+        } else {
#+            $caBytes += [Convert]::FromBase64String($_)
#+        }
#+    }

###notepad###

# execute run.ps1 again:
./run.ps1
```

**Comment by sowmyav27** [comment]
Reproduced this issue with `rancher:v2.3.0-alpha3`
**Steps:**
1. Create a standalone rancher server by using self signed certs.( Have 2 certs)
2. Deploy a custom cluster - 1 linux node - all roles, 1 linux node - worker node, 1 windows node - worker.
3. When you run the agent command on the windows node, it fails with error
`ERRO[0000] The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters`

**Comment by dnoland1** [comment]
@sowmyav27 customer was able to reproduce this problem today on rancher v2.3.0-rc8. Was there a regression?

**Comment by loganhz** [comment]
@thxCode please have a try

**Comment by loganhz** [comment]
This was fixed in alpha version but we re-introduced it in the rc.

**Comment by sowmyav27** [comment]
Validated with `v2.3.0-rc9`
**Steps:**

- Create a standalone rancher server by using self signed certs.( Have 2 certs)
- Deploy a custom cluster - 1 linux node - all roles, 1 linux node - worker node, 1 windows node - worker.
- When you run the agent command on the windows node, it fails with error, the node fails to come up.
Error in the agent ocntainer
```
time="2019-09-25T22:09:59Z" level=info msg="Connecting to proxy" url="wss://<rancher-server>/v3/connect/register"
time="2019-09-25T22:09:59Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="x509: certificate signed by unknown authority"
time="2019-09-25T22:09:59Z" level=error msg="Remotedialer proxy error" error="x509: certificate signed by unknown authority"
time="2019-09-25T22:10:09Z" level=info msg="Connecting to wss://<rancher-server>/v3/connect/register with token 5tpgslkdmwbzq5w7tznphfwbn7strbt4tf7txdczsfv5kqwm28j2sr"
time="2019-09-25T22:10:09Z" level=info msg="Connecting to proxy" url="wss://<rancher-server>/v3/connect/register"
time="2019-09-25T22:10:09Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="x509: certificate signed by unknown authority"
time="2019-09-25T22:10:09Z" level=error msg="Remotedialer proxy error" error="x509: certificate signed by unknown authority"
```

@thxCode @loganhz Is this ^^^ error similar to one when it was reproduced at your end?

**Comment by sowmyav27** [comment]
verified with `master-head` - commit id: `58e0a2faf`
Steps:

**Comment by thxCode** [comment]
Damn, I found that the Powershell of `1903` has changed from `v5.1` to `v6.0`, and then `Set-Content` hasn't supported `Bytes` as an encoding type:
- `v5.1`: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-5.1#parameters
- `v6.0`: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-6#parameters

For convenience, I have verified on `1809`. Sorry, I need to give another PR to fix this. @sowmyav27 , cc @loganhz , @cjellick .

**Comment by sowmyav27** [comment]
verified with `master-head` - latest
**Steps:**

- Create a standalone rancher server by using self signed certs.( Have 2 certs) - cacerts on the Rancher UI -- 2 certs
- Deploy a custom cluster - 1 linux node - all roles 1 windows node - worker.
- When you run the agent command on the windows node, noticed the rke-tools - `service-sidekick` restart. It recovered after about 2 minutes. Logging issue --https://github.com/rancher/rancher/issues/23106 for this.
- The windows node gets registered eventually to the cluster successfully.
- Deployed a windows workload successfully.
