### ISSUE TITLE
Backport: MultiAPP - cannot see the multiApp if the catalog used is deleted

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20432]
Backport rancher/rancher#19592

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc12`

**Comment by jiaqiluo** [comment]
The bug fix is validated on v2.2.4-rc12

Steps:
- add a catalog
- deploy a multiple cluster App using that catalog
- delete the catalog
- click on the `Apps` option in the global view 

Result:
 
<img width="1347" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58360412-87ebe780-7e3d-11e9-83a3-e95eb6e65081.png">
