### ISSUE TITLE
Alert: Component etcd-1 is unhealthy.

### ISSUE THREAD

**Issue by tiger0425** [rancher/rancher#20435]
*Describe your issue here*
2019-05-24 01:33:57.093807 E | etcdserver: the member has been permanently removed from the cluster
2019-05-24 01:33:57.093905 I | etcdserver: the data-dir used by this member must be removed.
2019-05-24 01:33:57.093978 E | etcdserver: publish error: etcdserver: request cancelled
2019-05-24 01:33:57.094035 I | etcdserver: aborting publish because server is stopped

 Unhealthy   Get https://192.168.1.13:2379/health: dial tcp 192.168.1.13:2379: connect: connection 
refused   

 rancher/coreos-etcd:v3.2.24-rancher1   "/usr/local/bin/etcd…"   15 hours ago        Up Less than a second                       etcd

How do I remove data-dir
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |

**Comment by superseb** [comment]
It's `/var/lib/etcd` or `/opt/rke/var/lib/etcd` (if RancherOS/Container Linux), please supply more info so we can get an idea what happened to get into this state.

**Comment by linbingdouzhe** [comment]
any update ? i have face the same problem

**Comment by tiger0425** [comment]
@linbingdouzhe 你试试将etcd有问题的node先移除集群，然后删除node上的/opt/rke目录，在将这个node加入到集群中

**Comment by linbingdouzhe** [comment]
> @linbingdouzhe 你试试将etcd有问题的node先移除集群，然后删除node上的/opt/rke目录，在将这个node加入到集群中

一共3个etcd的node  /opt/rke目录只有一个删除成功了，另外两个无法删除

error：
rm: can't remove '/opt/rke/var/lib/kubelet/pods/afc435dc-d3ba-11e9-b579-02d39fe8592c/volumes/kubernetes.io~secret/calico-node-token-vt48k': Device or resource busy

**Comment by tiger0425** [comment]
说明你的容器还没有删除干净，占用中不能删除
