### ISSUE TITLE
Backport: Monitoring - refine the UX for monitoring 1-click updating feature

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20439]
https://github.com/rancher/rancher/issues/20400

**Comment by loganhz** [comment]
in rc13

**Comment by jiaqiluo** [comment]
The feature is tested and validated on Rancher: v2.2.4-rc18

Please see the following two comments for what I tested.
- https://github.com/rancher/rancher/issues/20469#issuecomment-497122182
- https://github.com/rancher/rancher/issues/20468#issuecomment-497124045
