### ISSUE TITLE
prometheus domain name

### ISSUE THREAD

**Issue by GitHubStevenLiu** [rancher/rancher#20437]
Hi 
Rancher import my k8s cluster is success，but when i add Alert Rule in rancher , rancher notify me that "get prometheus metric list failed, Get **http://prometheus-operated.cattle-prometheus:9090**/api/v1/label/__name__/values: dial tcp: lookup prometheus-operated.cattle-prometheus on 10.0.0.2:53: no such host" .  
My prometheus working at "http://prometheus.prom.svc:9090" well in my k8s cluster.
My dns gateway ip is 10.0.0.2:53.
I think Rancher default domain name  not match mine. ( I used kube-dns ).
    http://prometheus-operated.cattle-prometheus:9090  is  failed
    http://prometheus.prom.svc:9090  is ok 
I do not  know how to change prometheus default  domain name in Rancher .
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/19688
