### ISSUE TITLE
unhealthy k8s nodes (vSphere VMs) in node-pool don't get replaced by Rancher automatically

### ISSUE THREAD

**Issue by timobartels** [rancher/rancher#20442]
**What kind of request is this (question/bug/enhancement/feature request):**
- bug

**Steps to reproduce (least amount of steps as possible):**
- in Rancher UI, create new cluster, select Vsphere
- create a node-pool for master/etcd (eg. 3 instances)
- create a node-pool for workers (eg. 2 instances)
- provision the cluster and confirm it is healthy (`kubectl get nodes`)
- via the vSphere admin client, power down one of the worker VMs
- confirm via UI and kubectl, that the worker node is unhealthy

**Result:**
via kubectl:
```
❯ kubectl get nodes
NAME            STATUS     ROLES               AGE   VERSION
myranch-tf-m1   Ready      controlplane,etcd   12m   v1.13.5
myranch-tf-m2   Ready      controlplane,etcd   12m   v1.13.5
myranch-tf-m3   Ready      controlplane,etcd   12m   v1.13.5
myranch-tf-w1   Ready      worker              10m   v1.13.5
myranch-tf-w2   NotReady   worker              10m   v1.13.5
```

via Rancher-UI:
`Kubelet stopped posting node status.`
<img width="262" alt="node-pool-instance-down" src="https://user-images.githubusercontent.com/21707175/58316137-2b73d280-7e13-11e9-8ec0-e0d1027dea79.png">

**Other details that may be helpful:**
- I waited for several minutes, Rancher doesn't replace the unresponsive node (which is what I would expect)
- after I manually removed the unhealthy VM from the node-pool (via Rancher UI), Rancher immediately created a new VM (with same name/specs) and it successfully joined the cluster
- I also visited the Rancher booth at KubeCon EU 2019 (on May 23rd), and I believe his name was Ankor (?), and he said we should open an issue for it, since Rancher should have the capability/feature to replace unhealthy nodes in a node-pool.
- this behaviour/bug also applies to master/etcd nodes!

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.2`
- Installation option (single install/HA): `single install`

**Cluster information**
- Cluster type (on-prem vSphere 6.5):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):` VM (4 CPU / 4 GB RAM)`
- Kubernetes version (use `kubectl version`): `1.13.5`

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:48:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
$ docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
This is covered in https://github.com/rancher/rancher/issues/15737

**Comment by timobartels** [comment]
@superseb I must have overlooked this existing issue! Thanks!
