### ISSUE TITLE
Improve documentation for audit log rotation

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#20444]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Details**

The documentation isn't clear on how to setup log rotation when the audit logs are set to stdout as it's destination on the sidecar.

https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#api-audit-log

The customer would like for it to clarify that stdout log rotation needs to be set in the Docker daemon in this case. This misunderstanding led them to believe that setting answers like maxAge, maxSize, etc would take effect on the logs which led to a full disk.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/docs/issues/2105
