### ISSUE TITLE
Backport OpenStack Provider lbaas monitor parameter type error

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20456]
Backport https://github.com/rancher/rancher/issues/14577

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc12`

@sangeethah just input validation test is enough. Passing 12s as a param and making sure it got set on a cluster.

**Comment by sangeethah** [comment]
Tested with `v2.2.4-rc12`.

Able to set string value for `monitor-delay`(60s)  and `monitor-timeout`(30s) in `loadBalancer` section for 
`openstackCloudProvider` by using "Edit Cluster Yaml" option.

Values get stored in as string in cluster Api as expected:
 
```
"name": "openstack",
"openstackCloudProvider": {
"loadBalancer": {
"create-monitor": true,
"floating-network-id": "***",
"lb-method": "ROUND_ROBIN",
"lb-provider": "haproxy",
"manage-security-groups": false,
"monitor-delay": "60s",
"monitor-max-retries": 3,
"monitor-timeout": "30s",
"subnet-id": "****",
"type": "/v3/schemas/loadBalancerOpenstackOpts",
"use-octavia": false
},
"type": "/v3/schemas/openstackCloudProvider"
},
```
