### ISSUE TITLE
Backport Timeout issues with helm after upgrading to 2.2.4-rc2 #20289

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20453]
Backport https://github.com/rancher/rancher/issues/20289

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc12`

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.4-rc13

* Reproduced original issue in v2.2.4-rc11 (Ubuntu/GCE)
* Install Rancher v2.2.2 (Ubuntu/GCE)
* Create cluster (ec2)
* Deploy app
* Deploy multicluster app
* Upgrade Rancher to v2.2.4-rc13
* Enable cluster monitoring
* Deploy app
* Deploy multicluster app
* Upgrade all apps
* Rollback all apps
* Delete apps
