### ISSUE TITLE
Upgrade fluentd-plugin-elasticsearch to latest version to support Elasticsearch 7.x well.

### ISSUE THREAD

**Issue by jnicholls** [rancher/rancher#20450]
The `fluentd-plugin-elasticsearch` gem should be updated to at least v3.4.2 in order to support Elasticsearch 7.x without any flooding of warning messages.

See the below Slack thread and github issue for more information.
https://rancher-users.slack.com/archives/C3ASABBD1/p1558619528441700
https://github.com/uken/fluent-plugin-elasticsearch/issues/589

And here is the commit where the flooding of warning logs was fixed accordingly.
https://github.com/uken/fluent-plugin-elasticsearch/pull/573

It would also be prudent then to fix the default `type_name` setting of `container_log` to be `_doc`. Users can work-around this by providing their own fluentd config when enabling cluster/project logging, instead of using the UI.

**Comment by n0daft** [comment]
We are currently also facing this issue with the `rancher-logging-fluentd` containers flooding the fluentd buffer of each node with following message like crazy:

```
[warn]: #0 Detected ES 7.x or above: `_doc` will be used as the document `_type`.
```

The message occurs thousands times each minute. Providing a complete custom fluentd config seems to be exaggerated given the extend and scope of the rancher-created fluentd configs (analyzed via secrets of cattle-logging namespace)

Isn't there an easy way to override `type_name` with `_doc`?

**Comment by jnicholls** [comment]
Unfortunately, it won't work. I've tried it. The issue is that the elasticsearch plugin had an issue in it where it would flood this message all of the time. Rancher uses the version of the plugin with this issue. The plugin has since fixed the issue, but Rancher needs to update its logging setup to use the newer plugin.

**Comment by n0daft** [comment]
Thx for the quick response. In other words, the issue won't go away even if you provide custom fluentd config overriding `type_name `? If so, what is your current workaround? Using an ElasticSearch version lower than 7?

**Comment by jnicholls** [comment]
At the moment I do not have a workaround to this from within Rancher, other than using ES 6.x. What I end up doing is deploying my own fluentd/elasticsearch setup from the official cluster addons repo: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ad1679532

* Created a cluster
* Deployed Elasticsearch
* Enabled logging to Elasticsearch
* Plugin version is `'fluent-plugin-elasticsearch' version '3.5.4'`
* Logs are shown correctly
* No warning about _doc typename
