### ISSUE TITLE
Monitoring - project Prometheus can't fetch metrics from workloads

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20459]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Scenario 1:

create a cluster, add user2 as the cluster member
log in as user2, create a project p1
enable the project monitoring in p1
deploy a workload with custom metrics (image: loganhz/web)
go to the project's Prometheus's page
check the `Configuration` under `status`  , we see the workload is added as a job
check the `Targets` under `status` cannot see the endpoint for the workload

Scenario2:

- run v2.2.3
- add user1 and user2 as standard users  
- log in as user1, add a cluster (in my case, I test both EC2 RKE and GKE clusters)
- add a project 
- add user 2 as a cluster member
- log in as user2, add a project 
- upgrade to v2.2.4-rc11
- log in as user1, enable project monitoring of the project he created
- deploy a workload with custom metrics
- log in as user2, enable project monitoring of the project he created
- deploy a workload with custom metrics

**Result:**
the workload is shown in project Prometheus's Configuration, but not in the target list
<img width="378" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58350360-81984400-7e1a-11e9-8d43-d0307d9ebe96.png">

**Other details that may be helpful:**
- the issue still exist if enabling cluster monitoring and adding new projects to do the same test on the upgraded setup
- might be related to https://github.com/rancher/rancher/issues/20390
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
v2.2.3 -> v2.2.4-rc11
- Installation option (single install/HA): 
HA mode

**Comment by jiaqiluo** [comment]
This bug also happens on a newly added cluster after upgrading.

Step:
- create a cluster, add user2 as the cluster member
- log in as user2, create a project p1
- enable the project monitoring in p1 
- deploy a workload with custom metrics (image: loganhz/web)
- go to the project's Prometheus's page
- check the `Configuration ` under `status` seeing the workload is added as a job 
- check the `Targets` under `status` cannot see the endpoint for the workload

NOTE:  when the cluster owner enables the project monitoring, the cluster owner cannot see the `project-monitoring` app under `apps` , but the project app is available and the project owner can see it under `apps` and it is also functional (can see the endpoints for workloads)

**Comment by loganhz** [comment]
@orangedeng Can you check if the root cause is the same with https://github.com/rancher/rancher/issues/20390 ?

**Comment by orangedeng** [comment]
I think it is. But need the logs in project Prometheus to make sure.

**Comment by loganhz** [comment]
@orangedeng confirmed the root cause is the same with #20390

**Comment by alena1108** [comment]
The fix will be available in rancher/rancher:v2.2.4-rc14

**Comment by jiaqiluo** [comment]
The bug fix is validated on a freshly installed v2.2.4-rc15

Steps:
- log in as admin, enable Github Auth, add Github user `user1` and `user2` as standard users
- log in as Github user `user1`, create an EC2 cluster
- log in as `user1`, add Github user `user2` as the cluster member
- log in as `user2`, create a new project `p1`
- go to the project `p1` to enable project monitoring
- deploy a workload with custom metrics (image: loganhz/web)
- go to the project's Prometheus's page

Results:
- check the `Configuration ` under `status` to see the workload is added as a job 
- check the `Targets` under `status` to see the endpoint for the workload
<img width="958" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58518521-6bfd8400-8164-11e9-9e4e-8881469a0adc.png">

- check the `Graph` page to search and find `web_app_online_user_count`
<img width="964" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58518531-71f36500-8164-11e9-94e1-dc6c700e072d.png">

**Comment by sangeethah** [comment]
Will validate the upgrade workflow as well before closing this issue.

**Comment by jiaqiluo** [comment]
The bug fix is validated on the upgrade path from v2.2.3 to v2.2.4-rc18

Steps:
- run v2.2.3
- add user1 and user2 as standard users  
- log in as user1, add a cluster (in my case, I test EC2 RKE cluster)
- add a project 
- add user 2 as a cluster member
- log in as user2, add a project 
- upgrade to v2.2.4-rc18
- log in as user1, enable project monitoring of the project he created
- deploy a workload with custom metrics
- log in as user2, enable project monitoring of the project he created
- deploy a workload with custom metrics


Result:
- In each project, the project Prometheus can fetch the metrics from the workload in that project as expected.
