### ISSUE TITLE
UI Error when launching catalog app in v2.2.4-rc12

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#20466]
rancher/rancher:v2.2.4-rc12

* Deploy Rancher
* Create a cluster
* Go to the apps page
* Click launch app
* Select an app

A full page ui error is shown: `Cannot read property '_routerMicrolib' of undefined`

![Screen Shot 2019-05-24 at 3 07 08 PM](https://user-images.githubusercontent.com/21316915/58360040-56721c80-7e3b-11e9-92c7-1f53e93fd04c.png)

Default ui-index in RC is `local`, switching to `https://releases.rancher.com/ui/2.2.66/index.html` allowed to workaround

**Comment by loganhz** [comment]
Fixed in UI v2.2.68 https://github.com/rancher/ui/pull/3012/files/747b10ba4a8ade21e9331ed98806bdf0c95e08cc#r287244076

**Comment by loganhz** [comment]
master is good. So we don't need to fix it in master

**Comment by loganhz** [comment]
in rc13

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.4-rc13

* Installed Rancher
* Created cluster
* Able to create apps correctly.
