### ISSUE TITLE
Monitoring - New monitoring version is not obvious in monitoring setting page

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20469]
Bug.
Rancher v2.2.4-rc12, UI: v2.2.68

the app `project-monitoring` shows upgrade available, but the project monitoring setting page does not have the option of upgrading.

<img width="663" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58361994-609a1800-7e47-11e9-8f6e-62acdba693a7.png">

<img width="937" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58362002-6bed4380-7e47-11e9-957c-18b08dc8dba9.png">

**Comment by loganhz** [comment]
@jiaqiluo you need to select 0.0.3 version in monitoring version.

**Comment by jiaqiluo** [comment]
@loganhz Thank you for point it out. I did not realize the UI is changed. it is not clear for users that there is a new version to choose from the droplist.

**Comment by loganhz** [comment]
@vincent99 @westlywright Now it is not obvious to find out there is a new version available in this monitoring setting page.

Any suggestion :)

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/58362589-44d85580-7ecb-11e9-8462-8af1ee2df0fa.png)
I mean here

**Comment by alena1108** [comment]
Can be tested with v2.2.4-rc16

**Comment by jiaqiluo** [comment]
the bug fix is validated on the path from v2.2.1 to v2.2.4-rc18

Cluster monitoring:
<img width="1290" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58593910-2226a380-8221-11e9-9fef-158be90a2866.png">

Project monitoring:
<img width="1294" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58593919-2783ee00-8221-11e9-802d-da695c82997f.png">
