### ISSUE TITLE
Monitoring - Should not show upgrade available if only operator is not upgrade to date

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20468]
Bug.  
Rancher v2.2.4-rc12, UI: v2.2.68

Steps:
- run Rancher v.2.2.1
- enable project monitoring
- upgrade to v2.2.4-rc12
- enable cluster monitoring
- notice that the app `cluster-monitoring` is deployed, but the `monitoring-operator` continues to be the old vesion `v0.0.2`, should we expect it to upgrade automatically? 
- the cluster dashboard shows upgrade available, but the cluster monitoring setting page does not have the option of upgrading. 

<img width="937" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58361917-aa363300-7e46-11e9-8f88-24ba5cd1164b.png">
<img width="927" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58361920-b4583180-7e46-11e9-9b3c-4aa7bad8c316.png">

The possible reason is that only `monitoring-operator` is in the old version.
<img width="935" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58361955-fe411780-7e46-11e9-88b6-a9404fb21746.png">

**Comment by loganhz** [comment]
@jiaqiluo I think we should not show that `Monitoring 0.0.3 upgrade available` in cluster dashboard if only operator is not up to date. Cluster monitoring is already up to date actually.

**Comment by sangeethah** [comment]
@loganhz If older version of `monitoring-operator` is already available and cluster monitoring is enabled ,  we expect that as part of cluster monitoring being enabled , existing `monitoring-operator` gets upgraded automatically ?

**Comment by loganhz** [comment]
No, users need to upgrade operator manually. We don't have to upgrade the operator

**Comment by jiaqiluo** [comment]
The bug fix is validated on the path from v2.2.1 to v2.2.4-rc18

Steps:
- run Rancher v.2.2.1
- log in as a standard user
- add a cluster
- add a project in the cluster
- enable project monitoring
- upgrade to v2.2.4-rc18
- enable cluster monitoring

Results:
- the app `cluster-monitoring` is deployed, but the existing `monitoring-operator` keeps the old version (not re-deployed or upgraded)
- the cluster dashboard does not show the hint for upgrade available, which is expected 

Note:
- we can still go to the `apps` page under the system project to upgrade the `monitoring-operator` to the latest version (v0.0.3)
