### ISSUE TITLE
Deleting local user Admin will make all clusters uneditable

### ISSUE THREAD

**Issue by Troyhy** [rancher/rancher#20477]
We have 3 clusters created with default Admin account witch was created during install. All node templates were created by that user.

Changed to github authentication and deleted local user Admin. Following unexpected issues resulted: 
*  All node templates also were deleted. ( because were created by local admin )
* Clusters created by local Admin were running, but editing is not possible anymore -> 
![image](https://user-images.githubusercontent.com/587882/58409363-89edba80-8078-11e9-9a18-ecb0e3223e53.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`authenticated.cluster.monitoring.index`|

**Comment by Troyhy** [comment]
This makes user management really a no-go. You cannot remove user, because some of the clusters might have node-template, that user has made.

Node templates should be properties of cluster, not tied to user account.

**Comment by fun3md** [comment]
We got a similar issue.
One user, which logs in via active directory, created all the clusters and is the only one capable to edit those clusters.
No changes on members or member roles on those clusters help.
