### ISSUE TITLE
Monitoring - failed to enable project monitoring sometimes

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20471]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug
Rancher v2.2.4-rc12 

**Steps to reproduce (least amount of steps as possible):**
- log in as the cluster member
- add a new project p1
- enable project monitoring
- see the following errors 
<img width="914" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58363351-b2e33500-7e57-11e9-8706-f5a5a75f92d4.png">

- disable the project monitoring  
- enable the project monitoring again
- the project monitoring app gets deployed successfully 
- deploy workloads w1 with custom metrics 
- see the project Prometheus fetch the metrics from w1

**Comment by loganhz** [comment]
If you wait few minutes, will it recover automatically? I saw it before, it recovered automatically without re-enable it

**Comment by sangeethah** [comment]
@loganhz When this error was seen yesterday , we waited for few minutes and did not see it recover automatically. We had to disable and enable monitoring to get it to work.

**Comment by hoangnh1806** [comment]
As this notice: #19771 Project level monitoring should add to v2.2.3. After upgrade from 2.2.2 to 2.2.3 I still got the error: 
<img width="1668" alt="error" src="https://user-images.githubusercontent.com/42130462/58372192-48f48980-7f44-11e9-95a7-8f7a6bb11b8e.png">

Do I have to upgrade to 2.2.4?
Thanks!

**Comment by orangedeng** [comment]
Can't reproduce this issue with 2.2.4-rc13.

**Comment by loganhz** [comment]
Please check cluster agent log when you reproduce it next time. Thanks @jiaqiluo

**Comment by alena1108** [comment]
@hoangnh1806 project monitoring will be enabled in 2.2.4. 2.2.3 doesn't have it.

**Comment by hoangnh1806** [comment]
@alena1108 Thanks for your info. But 2.2.4 is not a stable version now, right?

**Comment by deniseschannon** [comment]
@hoangnh1806 2.2.4 hasn't been released.

**Comment by deniseschannon** [comment]
@jiaqiluo it sounds like this is an issue if cluster agent is down. If you hit this issue again, please check the cluster agent logs. Let's keep it open in to-test state to ensure it doesnt happen in other use cases.

**Comment by jiaqiluo** [comment]
The monitoring feature is tested on Rancher: master with k8s v1.14.3 (default version) and the issue does not occur anymore. 
The issue also does not occur on Rancher:v2.2.4 

Closed.
