### ISSUE TITLE
Cluster owner cannot see the app

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20470]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- create a cluster, add user2 as the cluster member
- log in as user2, create a project p1
- log in as the cluster owner, deploy an app in p1

**Result:**
the cluster owner cannot see the app under apps, but the app is available and the project owner can see it under apps and it is also functional.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher v2.2.4-rc12, UI: v2.2.68

- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Can you refresh your browser ? Not sure if is an UI issue.

**Comment by orangedeng** [comment]
I can not reproduce this issue in both `master` 5/27 or `release/v2.2` branch.

**Comment by jiaqiluo** [comment]
I got the issue reproduced on v2.2.4-rc13 with the following steps:
- log in as admin, enable Github Auth, add Github user `user1` and `user2` as standard users
- log in as Github user `user1`, create an EC2 cluster
- log in as `user1`, add Github user `user2` as the cluster member
- log in as `user2`, create a new project `p1`
- log in as `user1`, go to the project `p1` to enable project monitoring

Result:
-  log in as `user1`, go to `Apps`, see nothing
- the data section of the following API call's response is empty
```
https://my-url/v3/project/c-czk52:p-nnn6v/apps?limit=-1&sort=name
```
- log in as `user1`, go to `Workloads`, see workloads for the project monitoring
-  log in as `user2`, go to `Apps`, see the project monitoring app
- the data section of the above API call's response contains 1 item which is the project monitoring app

**Comment by sangeethah** [comment]
@orangedeng Is it possible that when you tested this scenario ,  the cluster owner (who created the cluster) was a global admin user?

**Comment by orangedeng** [comment]
I tried the exact steps and reproduce this problem. I think the user1 is missing the app privileges in p1 but as `cluster-owner`, it should have that privileges. No only the project monitoring thing, the cluster owner `user1` can't create any apps in `p1` also.

**Comment by orangedeng** [comment]
I tried that in v2.2.3 with following steps and can see this problem too:
- log in as admin, create users `user1` and `user2` as standard users
- log in as user `user1`, create an EC2 cluster
- log in as `user1`, add user `user2` as the cluster member
- log in as `user2`, create a new project `p1`
- log in as `user1`, go to the project `p1` and create a new app in `p1`

Result: 
```
apps.project.cattle.io is forbidden: User "<user1>" cannot create resource "apps" in API group "project.cattle.io" in the namespace "<p1-namespace>"
```

**Comment by loganhz** [comment]
I can reproduce it in 2.1.0 as well

![image](https://user-images.githubusercontent.com/21168270/58526885-2e036d00-8203-11e9-956e-09e7e596baa7.png)
![image](https://user-images.githubusercontent.com/21168270/58526903-44112d80-8203-11e9-8f27-70f78e2b7ee2.png)

**Comment by loganhz** [comment]
Current workaround is restarting Rancher server container

**Comment by alena1108** [comment]
The issue existed since 2.1.x. Per @cjellick 
```
i think the bug is that when a project is created, we don’t re-evaluate all the CRTBs to see if there are any new privileges we need to grant. finding relevant CRTBs and enqueueing them at the end of project creation would fix this.
```
The issue resolves itself on rancher server restart, or on periodic cache refresh (every 2 hours by default)

**Comment by rmweir** [comment]
Appears to be resolved by https://github.com/rancher/rancher/pull/22133. Tested before and after commit, using @orangedeng testing steps. Moving to test.

**Comment by jiaqiluo** [comment]
validated in master-head 79c9048b3

Steps:
- log in as admin, enable Github Auth, add Github user `user1` and `user2` as standard users
- log in as Github user `user1`, create an EC2 cluster
- log in as `user1`, add Github user `user2` as the cluster member
- log in as `user2`, create a new project `p1`
- log in as `user1`, go to the project `p1` to enable project monitoring

Result:
-  log in as `user1`, go to `Apps`, see the project monitoring app
- the data section of the following API call's response is empty
-  log in as `user2`, go to `Apps`, see the project monitoring app
