### ISSUE TITLE
Unable import k8s 1.14

### ISSUE THREAD

**Issue by stiks** [rancher/rancher#20472]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Try to import k8s 1.14.1

**Result:**
```
$ kubectl apply -f https://k8s/v3/import/zzz.yaml
error: SchemaError(io.k8s.api.apps.v1beta2.ScaleStatus): invalid object doesn't have additional properties
```

**Other details that may be helpful:**
Once imported, works fine. I can import 1.13.*, then upgrade the cluster to 1.14 and no issues, cluster function perfectly fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher 2.2.3 
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by stiks** [comment]
my fault =(

**Comment by darthcabs** [comment]
Is there a workaround for it?

**Comment by darthcabs** [comment]
What was your fault? haha

**Comment by stiks** [comment]
I have had 2 versions of kubectl installed, 1.10 and 1.14. I was trying to import using 1.10
