### ISSUE TITLE
[Windows] Cannot add Windows worker node from Aliyun

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20487]
rancher/rancher:v2.3.0-alpha-4

Steps:

1. Create Windows Server 2019 in Aliyun
2. Install Docker EE
3. Add this node as a worker into Rancher k8s cluster

Results:

ERRO[0000] Illegal characters in path

**Comment by kingsd041** [comment]
Tested  rancher/rancher:master (06/12)
According to the reproduce step test, I can add windows nodes on Aliyun
