### ISSUE TITLE
[Feature Request] too heavy permission requirements to query prometheus alerts

### ISSUE THREAD

**Issue by Heiko-san** [rancher/rancher#20483]
Hi, 

we use Rancher 2.2.3 and its builtin prometheus feature.
We want to query the prometheus/alert manager's alerts API using some kind of read-only user.

e.g.
```
curl -u 'token-123:secret' 'https://our.rancher.domain/k8s/clusters/c-123/api/v1/namespaces/cattle-prometheus/services/http:access-alertmanager:80/proxy/api/v1/alerts'
```

This works perfectly but requires "Manage Services" on the "System" Project as the least necessary permissions.
This seems to be too much for this purpose, a user that should only query these rules/alerts would then be able to also update them and/or alter other service related things.
Wouldn't something like "View Services" (or a separate role) fit better?

**Comment by liquid-cloud** [comment]
@Heiko-san  I have found a good solution: 

In Rancher you can create a "Get Services" Role in Global and then create a user that has only that Role. 

Use the user's token to access the Prometheus API. 
![image](https://user-images.githubusercontent.com/49679701/60672511-d8f7ee00-9e75-11e9-905e-1836390db9ee.png)

**Comment by basroovers** [comment]
@liquid-cloud I don't have the possibility to create a cluster role in the user interface, how did you create the role?

**Comment by liquid-cloud** [comment]
It's a Project role. Global -> Security->Roles->Projects.

**Comment by Heiko-san** [comment]
Thanks a lot, it's working like a charm. :)
