### ISSUE TITLE
[UI] - Add NS label in "Add Record / Alias of another DNS record's value"

### ISSUE THREAD

**Issue by sebastienroul** [rancher/rancher#20484]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
 * Have a cluster with many NS, and in each one workload named "api"
 * Go to "Service discovery" / Add Record / Resolve to 'Alias of another DNS record's value'
 * Add Target Record
  * Display the list

**Result:**
The list contains only items named "api" => Could you prefixe the workload name with the NS name ? ex. "NS_A - api"

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.7

Follow the steps outlined in the issue description. I just named my workloads "nginx" each in different namesapces.
Result:
![image](https://user-images.githubusercontent.com/45179589/62734714-819dee00-b9de-11e9-949b-ee000f024a55.png)

(We have reproduced, I can't really tell which workload is which thus making it hard for me to pick the correct one I want).

**Validation:**
master-head (v2.3) (8/8/19)

Test again and now we state which namespace for each workload:

![image](https://user-images.githubusercontent.com/45179589/62734848-cde92e00-b9de-11e9-98c1-3dc89f7b7694.png)

Another example:
![image](https://user-images.githubusercontent.com/45179589/62734926-f40ece00-b9de-11e9-9285-a6cf30f5535b.png)

It is sorted by which ns is created the latest. Newest NS are at the top of the list.
