### ISSUE TITLE
 v.2.2.3 cluster monitoring disable does not remove deployment

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#20489]
rancher v.2.2.3
docker 18.09.63-0ubuntu-cosmic
custom nodes

Issue: Given the cluster monitoring is still faulty I wanted to disable it...which I did. It's turned off. Deployment is not removed, pods are all still running,including the endlessly looping one from https://github.com/rancher/rancher/issues/20488

Did anyone bother to test this? Like proper testing...

**Comment by loganhz** [comment]
Sorry. I think you hit https://github.com/rancher/rancher/issues/19645

Please remove the cluster-monitoring app in `apps` tab. It will be fixed in 2.2.4

Close in favor of  https://github.com/rancher/rancher/issues/19645
