### ISSUE TITLE
v.2.2.3 cluster monitoring termination loop

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#20488]
rancher v.2.2.3
docker 18.09.6~3-0~ubuntu-cosmic 
custom nodes

So I just upgraded to v.2.2.3 from v2.2.2 and gotta report that your v0.0.2 alpha cluster monitoring ain't working

The pod 'prometheus-cluster-monitoring' is endlessly terminating itself over and over, I can't see pods logs, it dies too fast. API is never ready.

Pod status is this:
`Search
Normal	SuccessfulCreate	create Pod prometheus-cluster-monitoring-0 in StatefulSet prometheus-cluster-monitoring successful	32 minutes ago
....
**Warning	FailedCreate	create Pod prometheus-cluster-monitoring-0 in StatefulSet prometheus-cluster-monitoring failed error: The POST operation against Pod could not be completed at this time, please try again.	31 minutes ago**
....
Normal	SuccessfulCreate	create Pod prometheus-cluster-monitoring-0 in StatefulSet prometheus-cluster-monitoring successful	29 minutes ago
**Warning	FailedCreate	create Pod prometheus-cluster-monitoring-0 in StatefulSet prometheus-cluster-monitoring failed error: The POST operation against Pod could not be completed at this time, please try again**.`

Note to developers:
You guys are aware that v0.0.2 is alpha and should NOT be in a stable release? I mean what happened to software engineering principles? If you add buggy code to stable releases and then peoples production cluster suffer because of that....absolutely unacceptable, who signed this even off? And I am not talking about just this issue, but the many other before and my last one where the tiller bug killed my rancher-master off. This is not how you do releases, I mean you got paying customers or do they get a different version? I doubt it

**Comment by loganhz** [comment]
Can you provide the reproduce steps?

**Comment by superxor** [comment]
@loganhz yes well...enable monitoring. Thats all the steps ;) the other cattle-promeutheus pods are running, Grafana is up. Only the prometheus-cluster-monitoring one fails.
I wish I could tell you why but it deletes it too quickly to see any errors or logs. Except there is a trick that I don't know off. Maybe change retries or something?

**Comment by loganhz** [comment]
Could you provide the screenshot in enable cluster level monitoring page, please?

**Comment by superxor** [comment]
![image](https://user-images.githubusercontent.com/18516510/58457917-8584d880-8130-11e9-98e7-9e7607b770d6.png)

That? I left it all default. I remeber from v.2.2.2 I had to adjust cpu/memory limits but iirc you fixed the low defaults (200 it was or something). I am not sure its because of that anyway.

**Comment by loganhz** [comment]
Is there any useful log in apiserver or other components?

**Comment by loganhz** [comment]
Not sure if it works if you deploy another stateful set in the cluster

**Comment by superxor** [comment]
@loganhz I dont see anything in the logs, what could cause this to be terminated the moment its created? I never seen that before

**Comment by loganhz** [comment]
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L298

`The POST operation against Pod could not be completed at this time, please try again.` indicating the requested action could not be completed due to a transient error, and the client should try again.

It looks like k8s failed to create a pod.

**Comment by superxor** [comment]
After deleting and reenabling it twice is suddenly worked. Not sure why though, didn't touch anything.
I'll close the ticket for now.

**Comment by superxor** [comment]
Ok are redeploying monitoring we're having this issue again. Redeployment due to https://github.com/rancher/rancher/issues/20546

**Comment by loganhz** [comment]
Could you provide a gif or something, please? It will be great if we can have the log or pod events as well  (if possible).

**Comment by superxor** [comment]
Gif...Pod id creating, next second pod is terminating.
I can try to find some logs again, but didn't last time, maybe if I watch the API servers

**Comment by superxor** [comment]
@loganhz here some logs

`I0531 06:40:35.569306       1 trace.go:76] Trace[748634766]: "Delete /apis/apps/v1/namespaces/cattle-prometheus/controllerrevisions/prometheus-cluster-monitoring-55bb54db89" (started: 2019-05-31 06:40:34.959517092 +0000 UTC m=+74647.322928319) (total time: 609.728705ms):
I0531 06:40:40.899862       1 trace.go:76] Trace[741494827]: "Update /apis/apps/v1/namespaces/cattle-prometheus/statefulsets/prometheus-cluster-monitoring/status" (started: 2019-05-31 06:40:40.266343599 +0000 UTC m=+74652.629754726) (total time: 633.471162ms):
I0531 06:40:41.783472       1 trace.go:76] Trace[1290014782]: "Get /apis/apps/v1/namespaces/cattle-prometheus/statefulsets/prometheus-cluster-monitoring" (started: 2019-05-31 06:40:41.11783123 +0000 UTC m=+74653.481242347) (total time: 665.567802ms):
I0531 06:40:42.618909       1 trace.go:76] Trace[454911575]: "Update /apis/apps/v1/namespaces/cattle-prometheus/statefulsets/prometheus-cluster-monitoring" (started: 2019-05-31 06:40:42.027473101 +0000 UTC m=+74654.390884248) (total time: 591.38758ms):
I0531 06:40:44.060591       1 trace.go:76] Trace[219960586]: "Update /apis/apps/v1/namespaces/cattle-prometheus/statefulsets/prometheus-cluster-monitoring/status" (started: 2019-05-31 06:40:43.404532765 +0000 UTC m=+74655.767943932) (total time: 655.929079ms):
I0531 06:41:31.243659       1 trace.go:76] Trace[613467064]: "Delete /api/v1/namespaces/cattle-prometheus/pods/prometheus-cluster-monitoring-0" (started: 2019-05-31 06:41:30.592840148 +0000 UTC m=+74702.956251295) (total time: 650.76652ms):
I0531 06:41:32.551135       1 trace.go:76] Trace[851422426]: "Delete /api/v1/namespaces/cattle-prometheus/pods/prometheus-cluster-monitoring-0" (started: 2019-05-31 06:41:31.772509768 +0000 UTC m=+74704.135920915) (total time: 778.566668ms):
I0531 06:41:33.529781       1 trace.go:76] Trace[967980472]: "Delete /apis/apps/v1/namespaces/cattle-prometheus/controllerrevisions/prometheus-cluster-monitoring-f7f66cc55" (started: 2019-05-31 06:41:32.794846878 +0000 UTC m=+74705.158258025) (total time: 733.249844ms):
`

`I0531 06:40:57.048005       1 trace.go:76] Trace[1714079580]: "List /api/v1/namespaces/cattle-prometheus/secrets" (started: 2019-05-31 06:40:56.451505701 +0000 UTC m=+74670.621685042) (total time: 596.441205ms):
I0531 06:41:27.754412       1 trace.go:76] Trace[1947763967]: "Update /api/v1/namespaces/cattle-prometheus/services/prometheus-operated" (started: 2019-05-31 06:41:27.24614305 +0000 UTC m=+74701.416322391) (total time: 508.212473ms):
I0531 06:41:31.150452       1 trace.go:76] Trace[1213433859]: "Delete /apis/apps/v1beta2/namespaces/cattle-prometheus/statefulsets/prometheus-cluster-monitoring" (started: 2019-05-31 06:41:30.59710988 +0000 UTC m=+74704.767289191) (total time: 553.289313ms):
I0531 06:41:33.178577       1 trace.go:76] Trace[1052153060]: "Get /api/v1/namespaces/cattle-prometheus/secrets/exporter-etcd-cert" (started: 2019-05-31 06:41:32.666586927 +0000 UTC m=+74706.836766298) (total time: 511.860308ms):
I0531 06:41:33.182315       1 trace.go:76] Trace[528496692]: "List /api/v1/namespaces/cattle-prometheus/secrets" (started: 2019-05-31 06:41:32.657021273 +0000 UTC m=+74706.827201024) (total time: 525.209709ms):
I0531 06:41:33.364054       1 trace.go:76] Trace[544129004]: "Delete /apis/apps/v1beta2/namespaces/cattle-prometheus/statefulsets/prometheus-cluster-monitoring" (started: 2019-05-31 06:41:32.763363784 +0000 UTC m=+74706.933543105) (total time: 600.666888ms):
`
it just loops for no apparent reason

**Comment by superxor** [comment]
as said before:
If I pause prometheus-operator-monitoring-operator then prometheus-cluster-monitoring runs fine

![image](https://user-images.githubusercontent.com/18516510/58687270-de9b7900-8389-11e9-8535-e0f9c096b1a0.png)

**Comment by Confusingboat** [comment]
I'm also seeing this on Rancher 2.2.8.

Pausing the operator does stop it from occurring, but after looking at the pod logs for `prometheus-cluster-monitoring` it looks like there may be a conflicting operator causing image version flapping between `rancher/coreos-prometheus-config-reloader:v0.29.0` that Rancher uses and `rancher/coreos-prometheus-config-reloader:v0.33.0`.

**Comment by thxCode** [comment]
@superxor have you fixed this?

**Comment by thxCode** [comment]
Don't deploy different versions of Prometheus Operator in a cluster, because the injected part from Operator to Prometheus server StatefulSet could be different, i.e: the probes, the volume name, the image version and so on. If you really need two different Operators in one cluster, you have to do as below:
- Keep all command parameters as the same as possible, sync up the image version of the injected container(e.g: configmap-reloader). **If the flipping still appears, it may be necessary to compare the StatefulSet generated by the two versions of the Operator for the same Prometheus CRD.**
- Use the `--**-namespaces` parameters to select/deselect the Prometheus CRD. **A feasible way is to exclude the cluster-monitoring Prometheus CRD under cattle-prometheus Namespace.** https://github.com/rancher/system-charts/pull/227#issuecomment-630595963

cc @superxor

**Comment by raulsh** [comment]
I had the exact same problem here. I created a new fresh Amazon EKS cluster with eksctl and imported to Rancher. I'm using Rancher 2.4.3. There is no logs and not debugable state. I don't know why **prometheus-cluster-monitoring** can't be scheduled.

   Successfully assigned cattle-prometheus/prometheus-cluster-monitoring-0 to ...

And after that the container is terminated (I don't know why).

**Comment by Tejeev** [comment]
I believe you may be seeing: https://github.com/rancher/rancher/issues/25044
