### ISSUE TITLE
etcd doesn't downscale when nodes deleted

### ISSUE THREAD

**Issue by wilf1rst** [rancher/rancher#20490]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an HA cluster with 3 or 5 etcd nodes.
Add 2 nodes with worker and etcd roles
Delete those 2 nodes

**Result:**
Etcd keep complains that it's not in an healthy state as it tried to keep connection with the two nodes.
```
NAME                 STATUS      MESSAGE                                                                                         ERROR
etcd-5               Unhealthy   Get https://X.X.X.X:2379/health: dial tcp X.X.X.X:2379: connect: connection refused   
etcd-4               Unhealthy   Get https://Y.Y.Y.Y:2379/health: dial tcp Y.Y.Y.Y:2379: connect: connection refused   
scheduler            Healthy     ok                                                                                              
controller-manager   Healthy     ok                                                                                              
etcd-6               Healthy     {"health":"true"}                                                                               
etcd-0               Healthy     {"health":"true"}                                                                               
etcd-2               Healthy     {"health":"true"}                                                                               
etcd-3               Healthy     {"health":"true"}                                                                               
etcd-1               Healthy     {"health":"true"} 
```

**Other details that may be helpful:**
Firstly I delete the nodes using:
`kubectl delete node [nodename]`
As it won't work I delete the node from the rancher cluster.yml file and:
`rke up --update-only --config cluster.yml`
As it's still don't work I launch the following command from an etcd container for the two faulty nodes:
`etcd member remove [member_id]`
As nothing I tried works well how can I properly delete etcd nodes in my rancher clusters ?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
    - VM Centos 7.6 (x5)
    - 2 vCPU / 4G RAM
- Kubernetes version (use `kubectl version`): 1.14.1

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`): 

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by wilf1rst** [comment]
My bad it seems I didn't read that on that part on rancher doc: https://rancher.com/docs/rke/latest/en/managing-clusters/

## Removing Kubernetes Components from Nodes

In order to remove the Kubernetes components from nodes, you use the rke remove command.

    Note: This command is irreversible and will destroy the Kubernetes cluster.

This command does the following to each node in the cluster.yml:

    Remove the Kubernetes component deployed on it
        etcd
        kube-apiserver
        kube-controller-manager
        kubelet
        kube-proxy
        nginx-proxy

I will try and close this issue then.

**Comment by wilf1rst** [comment]
As my cluster is not in production yet I will destroy it and re-install it.
I let this issue open as it seems that's a bug with the rancher deployment / undeployment.

**Comment by timmy59100** [comment]
I have the same problem. How is it possible to remove the etcd node fully?
Rancher version: 2.3.5

**Comment by boris-savic** [comment]
Same issue. Deleted a node from the 3 node setup and while everything still work, i'm getting alerts that etcd is unhealthy. 

etcdctl member list shows:
```
docker exec etcd etcdctl member list
11e83f60ba359a88, started, etcd-worker-3, https://10.10.20.3:2380, https://10.10.20.3:2379,https://10.10.20.3:4001, false
497cbbf1f7654dbb, unstarted, , https://10.10.20.2:2380, , false
c15a42797f6144f0, started, etcd-worker-2, https://10.10.20.4:2380, https://10.10.20.4:2379,https://10.10.20.4:4001, false
```

So the node 10.10.20.2 was removed, but still stays inside etcd forever and thus results in errors.

**Comment by zbialik** [comment]
Same issue here with rancher v2.4.10

I believe it might have to do with deleting the leader etcd node (by chance) and having a high leader-election setting for the cluster config.
