### ISSUE TITLE
[Windows] Removed nodes will try to add itself back after restart

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20496]
rancher/rancher:v2.3.0-alpha3

Steps:

1. Create a Windows cluster
2. Add Windows node
3. Remove the node in Rancher UI
4. Restart the Windows node

Results:

The removed node will try to add itself back. 

![image](https://user-images.githubusercontent.com/21168270/58469229-ad486080-8171-11e9-97ed-e42e4f5d56e9.png)

Expected:

It should not try to add itself back

**Comment by sowmyav27** [comment]
reproduced the issue on `v2.3.0-alpha3`
**Steps:**

1. Create a Windows cluster
2. Add Windows node
3. Remove the node in Rancher UI
4. Restart the Windows node

**Results:**

The removed node will try to add itself back.
And gets added successfully.

<img width="1452" alt="Screen Shot 2019-07-01 at 2 34 42 PM" src="https://user-images.githubusercontent.com/26032343/60468798-a2b93500-9c0f-11e9-9c59-971ef3cd5f34.png">

verified on `rancher:master-head` and works fine.
**Steps:**

1. Create a Windows cluster
2. Add Windows node
3. Remove the node in Rancher UI
4. Restart the Windows node

**Results:**
The removed node will not add itself back.
