### ISSUE TITLE
Rancher show Alerting but email not received? 

### ISSUE THREAD

**Issue by dhirajdebut** [rancher/rancher#20492]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create cluster running 
Select cluster > global >Tools > Alert
Create alert

**Result:**
Alert changes to **Alerting** state but email is not revived . Test email is working fine.

**Other details that may be helpful:**
When test the email from SMTP details then it sends the email. I have added alerts to pods so i am scaling pods up and down then it turns into red color as ALERTING but email is never received. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.16
- Installation option (single install/HA):Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Hosted 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by dhirajdebut** [comment]
Anyone any idea or any solution for this ?

**Comment by dhirajdebut** [comment]
Hello all,
Does anyone here have the solution for this problem ? I could not receive the email for alerts. But Rancher shows ALERTING

**Comment by dhirajdebut** [comment]
Any Update on this issue ?

**Comment by loganhz** [comment]
Is there any useful log in alert manager?

**Comment by dhirajdebut** [comment]
I am not sure. Where i can find the logs. I see as ALERTING but still can not get logs.

**Comment by dhirajdebut** [comment]
Hello,
I have resolved this issue. I have checked log for alertmanager
AlertManager is found in CluserName ->System & there is AlertManager Pod.

My issue was i have added the Non TLS enabled SMTP credentials but looks like rancher required a TLS enabled SMTP Credentials.

**Comment by nikhil7875** [comment]
I have same issue, but Alert not change to "Alerting" state. Can someone help me to how to debug this issue.

**Comment by ayushi4** [comment]
> I have same issue, but Alert not change to "Alerting" state. Can someone help me to how to debug this issue.

You need to trigger alert by fulfilling alert condition. Check "prometheus alert" rules and try to replicate a condition.

**Comment by ayushi4** [comment]
I am facing same issue, my alerts are fired but they are not received as email notification.
