### ISSUE TITLE
Cannot exec shell from ui on started container with status not ready

### ISSUE THREAD

**Issue by benzman81** [rancher/rancher#20493]
**What kind of request is this (question/bug/enhancement/feature request):**
not sure, might be a bug or enhancement

**Steps to reproduce (least amount of steps as possible):**
Create a pod with a simple container and a readiness that fails for some minutes. In Rancher UI you can see that the container starts and even display logs. But while the container is in "not ready" state the menu item for execute shell is not visible.

**Result:**
You cannot execute shell from rancher ui although it works via kubectl. This would be helpfull to analyse why container does not come to ready state that is now only possible via kubectl.

**Environment information**
- Rancher version 2.2.2
- Installation option (single install/HA): single install

**Comment by mvehar** [comment]
This is really a problem if you have readiness check and some manual task (running a migration) before pod starts to receive traffic.

**Comment by davidnuzik** [comment]
Version: master-head (7/26/19)

I created a workload that sets a Readiness Check that will not succeed.
I confirmed that I am now able to exec shell, whereas this was not possible before (I compared to v2.2.5).

![image](https://user-images.githubusercontent.com/45179589/61966383-5e5b5380-af87-11e9-9251-6f5e6a7d5e09.png)

Exec shell working:
![image](https://user-images.githubusercontent.com/45179589/61966426-729f5080-af87-11e9-96dd-7422e9cac115.png)
