### ISSUE TITLE
unreadable. It is excluded and would be examined next time 

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#20494]
rancher-logging-fluentd log print "unreadable. It is excluded and would be examined next time "(image1),and i check the file is existed (image2)
![image](https://user-images.githubusercontent.com/14210543/58468604-6e65db00-8170-11e9-9a80-e58f509856ad.png)
![image](https://user-images.githubusercontent.com/14210543/58468669-92292100-8170-11e9-83a0-404b7a3cc80f.png)

rancher-logging-fluentd mounts list:

Volumes:
  custom:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/fluentd/etc/config/custom
    HostPathType:  
  dockerroot:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  
  varlogcontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/containers
    HostPathType:  
  varlogpods:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/pods
    HostPathType:  
  rkelog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/rke/log
    HostPathType:  
  customlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/log-volumes
    HostPathType:  
  fluentdlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/fluentd/log
    HostPathType:  
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rancher-logging-fluentd
    Optional:    false
  entry:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rancher-logging-fluentd-entry
    Optional:    false
  ssl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rancher-logging-fluentd-ssl
    Optional:    false
  libsystemddir:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/lib64
    HostPathType:  

rancher version: v2.2.3

**Comment by Amos-85** [comment]
@wuchencm ,
try to check the docker root folder,   `docker info | grep 'Docker Root Dir'`
seems your docker engine not installed on the default path `/var/lib/docker`
you can change it in the **rancher-logging** helm chart with this value `fluentd.cluster.dockerRoot`

**Comment by echolixiaopeng** [comment]
@Amos-85 ,
how to change ` fluentd.cluster.dockerRoot` in the rancher-logging helm chart ?
