### ISSUE TITLE
Feature Request: support set `nodeName` in UI

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#20495]
**What kind of request is this (question/bug/enhancement/feature request):**

feature request

**Other details that may be helpful:**

Aliyun support adding virtual node to the k8s cluster, and in order to schedule pods on it, one should set the `nodeName` field in the yaml.

By now, we can't set it in UI and we can't edit yaml on deployment, so I have to create the workload, and edit its yaml later, this is ... bad.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

v2.2.3

- Installation option (single install/HA):

single install

**Comment by loganhz** [comment]
Do you mean this ?
![image](https://user-images.githubusercontent.com/21168270/58469576-58f1b080-8172-11e9-94be-c9bda99fc912.png)

**Comment by zhaoyao91** [comment]
@loganhz no, I don't mean set the name of node, I mean schedule the pod on some node by its node name

**Comment by loganhz** [comment]
@zhaoyao91 can you add my wechat `howl6616`?
