### ISSUE TITLE
Deleted AD user got local admin privileges&profile

### ISSUE THREAD

**Issue by arymkus** [rancher/rancher#20491]
Got this by following scenario (wasn't able to reproduce with another account, first one is still strange)
- added Active Directory authentication
- successfully logged in as an AD user
- deleted this user
- reconfigured AD authentication
- logged in with the same AD user again
- AD user isn't listed in Users and it got local admin privileges&profile.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`global-admin.accounts.index`|

**Comment by danetz** [comment]
I can confirm that this bug exists in version 2.3.5, the deleted user is not recreated so it doesn't seem possible to disable login short of disabling AD authentication.
