### ISSUE TITLE
i18n support or ability to contribute localization

### ISSUE THREAD

**Issue by allustin** [rancher/rancher#205]
We want to use Racher for our team, but someone in our team is non-english spoken people.

Is it possible:

* localize the ui for German, Russian, France ?
or
* add messages for UI, to abillity for contribute with pull-request ?

if for UI using angular.js, http://angular-translate.github.io/ - this is simple way to translate angular

**Comment by vincent99** [comment]
The UI is Ember.js but similar libraries exist.  We don't have any specific plans yet but this is definitely on our todo list.

One big complication is that some of the most interesting info, like the messages on a transitioning resource and errors, come from strings generated by the API.  So we'll have to address that somehow.

**Comment by vincent99** [comment]
Merging with #1268..
