### ISSUE TITLE
Failed to ensure catalog system-library-rancher-monitoring

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#20501]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
We just upgraded our production environment from v2.1.7 to v2.2.3

Enabling the cluster monitoring feature doesn't work.

**Result:**

An error message is shown in the Rancher UI for the clusters that tried to enable monitoring:

```
Failed to ensure catalog "catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2": failed to find catalog by ID "catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2": catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
```

**Other details that may be helpful:**

I looked in the list of `catalogtemplates.management.cattle.io` resources and there is nothing for monitoring.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.3
- Installation option (single install/HA): HA on Kubernetes

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Openstack
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 64 cores, 240GB memory
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-27T01:15:02Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 18.6.1

**Comment by loganhz** [comment]
Thanks for the report

Fixed in https://github.com/rancher/rancher/issues/20309 with PR https://github.com/rancher/rancher/pull/20324

Close in favor of https://github.com/rancher/rancher/issues/20309

**Comment by loganhz** [comment]
Thanks for the report

Fixed in https://github.com/rancher/rancher/issues/20309 with PR https://github.com/rancher/rancher/pull/20324

Close in favor of https://github.com/rancher/rancher/issues/20309
