### ISSUE TITLE
Rancher-Compose: `restart: no` isn't working properly

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2050]
Version: v0.3.0-rc1

Tested out service with `restart: no` and error in deploying services.

docker-compose.yml
```
test:
  restart: no
  image: ubuntu
```

```
INFO[0000] Creating service test
ERRO[0000] Failed Starting test : invalid restart policy false 
ERRO[0000] Failed to start: test : invalid restart policy false 
FATA[0003] invalid restart policy false  
```

Somewhere in maybe docker/libcompose, it's converting the "no" to "false" based on how Docker displays it's errors in docker/docker/runconfig/parse/ParseRestartPolicy.

**Comment by deniseschannon** [comment]
Somewhere the string of "no" is being translated into a boolean value.

**Comment by deniseschannon** [comment]
Merged in libcompose. https://github.com/docker/libcompose/pull/67

**Comment by sangeethah** [comment]
Tested with rancher-compose version v0.4.1-rc2.

Able to start a service successfully from rancher-compose by setting restart: no policy.

```
~/rancher-compose-v0.4.1-rc2$ cat dc.yml
test12:
  restart: no
  tty: true
  image: ubuntu
  stdin_open: true

~/rancher-compose-v0.4.1-rc2$ ./rancher-compose -p test1 -f dc.yml up
INFO[0000] Project [test1]: Starting project            
INFO[0000] [0/1] [test12]: Starting                     
INFO[0000] Creating service test12                      
INFO[0006] [1/1] [test12]: Started                      
INFO[0006] Project [test1]: Project started 
```
