### ISSUE TITLE
Certificate of kube-apiserver is not renewed with all controlplane node entries when adding controlplane node causing 'x509: certificate is valid for' error when using kubectl

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20508]
This issue is to test https://github.com/rancher/rancher/issues/16151 on 2.3 (master)

**Comment by sowmyav27** [comment]
On rancher:master - latest(06/06/2019) - steps taken:

1. Created a custom cluster - 1etcd, 1 control plane (Control Node#1) , 1 worker node.
2. Scale the number of control planes to 10 nodes - automation provisioning.
3. Wait until the cluster comes to Active state
4. Executed the steps mentioned in -https://gist.github.com/superseb/36919dba64a18cb40951228254660f03#run-commands-to-retrieve-info
5. Output received - $ip is GOOD on certificate.
6. Verified that Control Node#1 had certificate for kube-apiserver with all names and IPs of each controlplane node added in step 2. Also verified the other control nodes had certificate for kube-apiserver with all names and IPs of each controlplane node.
7. Executed steps - 1 to 6, 2 - 3 times.
