### ISSUE TITLE
level=warning msg="can't get disk usage for /host/var/lib/system-docker/overlay2. Ignoring" Component=StorageSampler error="no such file or directory"

### ISSUE THREAD

**Issue by Gneisler** [rancher/rancher#20502]
Rancher 2.2.3, Running RancherOS v1.5.1 on a vsphere cluster.

When turning on syslog project logging in rancher 2.2.3 I get the following logs from fluentd container:

`level=warning msg="can't get disk usage for /host/var/lib/system-docker/overlay2. Ignoring" Component=StorageSampler error="no such file or directory"`

**Steps to reproduce:** Turn on SysLog logging at a project level (We go to papertrail), this will spin up fluentd containers and then logs start streaming.

SSHing into the host, there is not a system-docker directory in RancherOS v1.5.1. 

Not sure if this is a Rancher or a RancherOS issue.

![image](https://user-images.githubusercontent.com/11962917/58487342-6b99c480-8135-11e9-921c-007fcd6910d2.png)

**Comment by mehdico** [comment]
Same!
