### ISSUE TITLE
Unable to send email notification without SMTP authentication

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20507]
This issue is to test https://github.com/rancher/rancher/issues/20060 on v2.3

**Comment by rootwuj** [comment]
Tested with rancher/rancher:v2.3.0-alpha3 from May 30

Test:
1. Deploy rancher v2.3.0-alpha3 and add cluster
2. Add an email notifier without SMTP authentication
3. Add an alert

Result:
Alertmanager version is rancher/prom-alertmanager:v0.16.1 
Unable to send email notifications.

**Comment by rootwuj** [comment]
Tested with rancher/rancher:v2.3.0-alpha3 from May 30
Test:
* Freshly deployed rancher:v2.3.0-alpha3 and add cluster
* Edit `system-charts` branch to `dev`
* Add an email notifier without SMTP authentication
* Create alerts at the cluster level and project level

Result:
* Alertmanager version upgrade to `rancher/prom-alertmanager:v0.17.0`.
* Can send alert email notifications
