### ISSUE TITLE
Backport: Error while trying to create a cluster with AWS Asia Pacific (Hong Kong) Region 'ap-east-1'

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20515]
https://github.com/rancher/rancher/issues/20474

**Comment by alena1108** [comment]
Can be tested with v2.2.4-rc16

**Comment by rootwuj** [comment]
Tested with rancher/rancher:v2.2.4-rc19 from May 30

Steps:
1. Create an AWS node template
2. Region is ap-east-1
3. Instance type is t3.medium
4. Create EC2 cluster for region ap-east-1
5. Modify the count of cluster nodes
6. Delete cluster

Result:
Node template create successfully.
Cluster create/modify/delete successfully.

Verified fixed.
