### ISSUE TITLE
Support logging on Windows node

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20510]
Support logging on Windows node

**Comment by deniseschannon** [comment]
Can one pass be done to make sure that logging on linux clusters are still working as expected?

**Comment by sangeethah** [comment]
Note that logging is now supported only for HostGW network.

**Comment by kingsd041** [comment]
Version: master-head (9/7/19)
Use the host-gw network, verify the following test cases, and verify the pass.
- Cluster level and project level logging
- RKE workload logging
- windows workload logging
- Include System Log
