### ISSUE TITLE
Cannot see Windows Workload/Pod/Container metrics with cluster monitoring enabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20513]
rancher/rancher:v2.3.0-alpha3

Steps:

1. Deploy windows cluster
2. Enable cluster monitoring
3. Deploy a Windows workload
4. Try to look at the metrics for the windows workload

Results:

Cannot see it.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/29/19)

I am able to see Workload/Pod/Container metrics (CPU and Memory) without any issues on windows workloads now. I am going to check project-level monitoring via https://github.com/rancher/rancher/issues/20076
