### ISSUE TITLE
Local Auth not working with no hosts added to Rancher yet

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2051]
v0.37.1

Steps to Reproduce
1. Launch Rancher server, do not add any hosts
2. Go to Local Auth, add any user with any password.
3. Click on "Enable Local Auth"

Result: "Unauthorized".

Expected Result: Local Auth to be enabled and logged in.

Workaround 1: On a fresh setup, click on "Enable Local Auth" a second time and you will be logged in appropriately. Do not change any of the information in the text boxes and wait a little bit before clicking again.

Workaround 2: On a fresh setup, add a host to your setup and then enable local auth.

**Comment by kaos** [comment]
could this issue be valid for LDAP as well?

I've seen issues with null pointer exceptions in the rancher server log when a AD user tries to login. Logging in with the admin account works fine. (workaround 1 did not resolve the issue on this occasion, however.)

I've not yet compared logs, but they look pretty much like the ones I had on 0.34.0: http://forums.rancher.com/t/ldap-login-yields-internal-server-error/362

**Comment by deniseschannon** [comment]
This issue would not be the same as with LDAP. This is purely when trying to enable local auth. If you're seeing issues when a AD user tries to log in that would be separate. @kaos Can you open a separate issue to track your LDAP one? I know in your thread that you were able to get it working in the end, so not sure if I chalked it up to something with your LDAP setup.

**Comment by vincent99** [comment]
@kaos I don't think so, I believe the current issue with local auth is a race condition where it's not done being turned on yet when the UI tries to get a token to test auth.

**Comment by kaos** [comment]
@deniseschannon will do, once I've gathered more data.
@vincent99 ah, I see :)

**Comment by deniseschannon** [comment]
In v0.40.0-rc2, this is no longer reproducible.
