### ISSUE TITLE
RFE: Popeye for Rancher

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20527]
Rancher version:
2.2.2

Description:
Implement views similar to what Popeye gives us
https://github.com/derailed/popeye [github.com] 

gz#4459

**Comment by ankur111** [comment]
This looks like a good RFE for us that constantly monitors and cleans up a cluster.
This could tie nicely into our new 2.3 features like Security Scan. 
I will talk to the customer to understand it further and assign a priority to it.
