### ISSUE TITLE
RFE: Unified view of pods / services / etc, regardless of namespaces

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20525]
Rancher version;
2.2.2

Description:
A unified view to show all pods / services / etc (chosen via a drop down list), regardless of namespaces.  Should respect security.  Also should be able to sort by restarts, or filter by items having issues.  Right now as an admin I have to do a 'kubectl get po --all-namespaces' to see if there are any pods going nuts on me, would be nice to have this in the interface 

gz#4456

**Comment by vincent99** [comment]
See mostly https://github.com/rancher/rancher/issues/20526#issuecomment-497068455
