### ISSUE TITLE
Cannot see log of pods on virtual kubelet

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#20528]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

- create a rancher (single install)
- connect an aliyun managed k8s cluster to rancher
- add  a [virtual kubelet (virtual node)](https://help.aliyun.com/document_detail/118970.html)
- schedule some pods on the virtual kubelet

**Result:**

cannot see logs of these pods on rancher.

**Other details that may be helpful:**

but, `kubectl log` is ok to see the log

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.3
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 1.12.6-aliyun.1

**Comment by loganhz** [comment]
@zhaoyao91 can you add my wechat `howl6616`?
