### ISSUE TITLE
Backport: Errors in rancher logs when delete cluster

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#20531]
Original issue: https://github.com/rancher/rancher/issues/20300

**Comment by alena1108** [comment]
The fix will be available in v2.2.4-rc17

**Comment by davidnuzik** [comment]
Version: v2.2.4-rc18

I am no longer seeing the issue. A very small handful of [ERROR] entries are seen in the logs but this has been significantly improved. Error entires no longer loop and removal of clusters is significantly faster now. I only had to wait up to 30 seconds to remove many clusters at once (delete all at once).

I consider the issue resolved.
