### ISSUE TITLE
RFE: User Action Logging

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20535]
Rancher version:
2.2.2

Description:
We really need some kind of user action logging, especially when admins are doing maintenance. Example. Person X removed node Y from cluster Z on this date and time 

gz#4464

**Comment by ankur111** [comment]
Please try this doc link about audit logs : https://rancher.com/docs/rancher/v2.x/en/installation/options/api-audit-log/

**Comment by skyscooby** [comment]
@ankur111 
Why are metadata responses not logged in Level 1 - Metadata ?
Knowing if the requests were successful or not seems somewhat important to the overall use of this rather brief logging level.

Suggest adding another level including both request/response metadata only
