### ISSUE TITLE
rancher stack reverted versions after commit

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#20541]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**version:**
rancher/server:v1.6.26

**Steps to reproduce (least amount of steps as possible):**
1. Stack was deployed end of last year, via rancher cli
2. Stack was upgraded in Feb with an environment variable change and committed (finished the upgrade). via rancher cli
3. Stack was again upgraded in May with no changes, it is stuck when we tried to finish the upgrade so we rolled back, via UI
4. at step 3 it should rollback to step 2 but it rolled back to step 1

**Other details that may be helpful:**
ping directly for logs

**Comment by alena1108** [comment]
@aemneina is it possible to get the following info via db queries:

* select * from environment where id=stackId (environment is the table where we keep all the stacks)
* select * from service where environment_id=<stackId>
* Provide the stack info of version 1(step1) and version2 (step2).
* Where steps 1) and 2) performed on Rancher 1.6.26? If there was any diff version, please specify.
