### ISSUE TITLE
"Add Cluster", create etcd contaioner always fail

### ISSUE THREAD

**Issue by GlenLee** [rancher/rancher#20542]
[etcd] Failed to bring up Etcd Plane: Failed to start [etcd] container on host [10.0.2.4]: Error response from daemon: error while creating mount source path '/var/lib/etcd': mkdir /var/lib/etcd: read-only file system

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`authenticated.prefs`|

**Comment by superseb** [comment]
This is usually caused by either:

- Using snap to install Docker which has a bug related to this (should use upstream Docker)
- It is actually mounted read only (probably on `/var`) and need to be relocated (https://rancher.com/docs/rancher/v2.x/en/installation/options/etcd/) or made read-write.

**Comment by jorioux** [comment]
I had the same issue when installing docker from the ubuntu installer; it uses snap.

I needed to install docker with apt.
