### ISSUE TITLE
RFE: Network Rules Interface

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20548]
Rancher version:
2.2.2

Description:
We have to open firewall holes to external resources for specific applications, but because those rules are for all nodes, technically all pods have access to that resource. We need a way to secure network rules per project, namespace, deployment, etc. Right now we are looking at buying Twistlock for this, but having it built into Rancher would be a huge value add. 
I think this would go along with the security theme for Rancher 2.3 

gz#4455

**Comment by ankur111** [comment]
Implementing an interface is a start but we will also have to provide a way to either feed these rules to a runtime security tool (like Aqua/Twistlock) or to provide such capability from within Rancher. 
I think we can address this if (or when) we enable runtime security within Rancher.
