### ISSUE TITLE
Create generic Rancher compose template + upgrade for various apps

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2054]
* Generate a Compose template for:
  * Hadoop
    * [x] Install
    * [ ] Upgrade
  * Openstack/Swift
    * [ ] Install
    * [ ] Upgrade
  * ELK
    * [x] Install
    * [x] Upgrade
  * Jenkins
    * [x] Install
    * [ ] Upgrade
  * Gluster
    * [x] Install
    * [ ] Upgrade
  * Nexenta
    * [ ] Install as a VM
  * Kubernetes
    * [x] Install
    * [ ] Upgrade
  * Mesos
    * [ ] Install
    * [ ] Upgrade
  * Swarm
    * [ ] Install
    * [ ] Upgrade
* Show it can be launched with a few config items
* Be able to update from one version to another
* Goal is to determine what missing features Rancher needs to implement to provide this end to end solution.

**Comment by lavvy** [comment]
+1 . Distributed storage

**Comment by lavvy** [comment]
Hello, any news on this template ?, could there be a skeletal template at least, so that we can testing.

**Comment by cloudnautique** [comment]
@lavvy we are still in the process of creating the template. Right now its looking like it will start out as HDFS (Single namenode) cluster and Yarn. Does that seem like it would be useful? What are you planning to try and do with it?

**Comment by lavvy** [comment]
@cloudnautique i had just spinned up hadoop for the first time in rancher yesterday and it was pretty simple to kickstart and use . and it ran very smoothly . i could be able to use its web ui (hue). 
i used this image https://hub.docker.com/r/caioquirino/docker-cloudera-quickstart/ . 

BUT the only issue was how to add more nodes or scale it in rancher .

**Comment by lavvy** [comment]
yes i think it will be very useful . atleast having a distributed file system service with analytics and processing in the environment or infrastructure

**Comment by lavvy** [comment]
+1 . Mysql or mariadb service

**Comment by vincent99** [comment]
I could see multi-master Percona XtraDB clustering as there's work required to get the cluster setup..

 What would you want out of a MySQL/Maria template beyond the options in their normal official images?  Master/slave setup?  Auto failover between them?

**Comment by lavvy** [comment]
Yeah just to keep a generic relational database template for rancher that one can create a database and connect to. It must not be sophisticated but it should have replication and failover, I think that would be cool

**Comment by lavvy** [comment]
Still waiting to start testing hadoop in rancher, I came across this   https://github.com/lresende/docker-yarn-cluster    
I think it has both namenode and datanodes as containers

**Comment by cloudnautique** [comment]
@lavvy, I checked in the first pass of the Hadoop cluster and Yarn. Let us know what you think!

**Comment by lavvy** [comment]
Sorry for late response. I gave it a spin yesterday . That was a cool setup. Though I have not been able to test it for long. But I will want to suggest if the set-up could include hue manager . I think it will enable us navigate hadoop ecosystem better, just like what rancher is to docker

**Comment by lavvy** [comment]
Still testing the hadoop stack for rancher. Trying to decommission some datanodes, When you kill a datanode the rancher service recreates it again.

**Comment by cloudnautique** [comment]
@lavvy, when you say decommission, do you mean you have added to the blacklist and then manually deleted the node? The scale of the service would need to decrease, otherwise Rancher tries to keep it at the same capacity as you observed. 

We need to adjust the behavior in Rancher. What would you consider the ideal flow? Mark the node to be decommissioned, wait for draining, then scale down the service removing that node? Or something else?

**Comment by lavvy** [comment]
Yes, you gat the workflow right. But if you can stop the node in rancher and it appears decommissioned, cool too

**Comment by 2mind** [comment]
https://github.com/2mind/Dockerfiles/tree/master/consul - create consul cluster + webui using metadata
---
currently working on an adaptation of a ceph cluster
---
rancher great project
Спасибо ;)

**Comment by will-chan** [comment]
Will track catalog item as separate feature requests.
