### ISSUE TITLE
v.2.2.3 Monitoring - No pod/workload metrics

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#20546]
v.2.2.3
custom

Issue: Under Pod Metrics I see no information, only 'Not enough data for graph'. This is true for all pods on the cluster. Also for workload metrics!
Otherwise monitoring seems to work for nodes and general cluster info.

Does pod metrics require further steps to configure?

**Comment by loganhz** [comment]
No further steps required for pod metrics.

You could check it if in Prometheus UI -> Targets page. And search `kubelet`. Check if the kubelet targets are in red.

**Comment by superxor** [comment]
The only thing kubelet I find there is:
cattle-prometheus/exporter-kubelets-cluster-monitoring/0 (0/0 up) 

cattle-prometheus/exporter-kubelets-cluster-monitoring/1 (0/0 up)

There are no kubelet pods

**Comment by loganhz** [comment]
Imported cluster ?

**Comment by superxor** [comment]
No, running since rancher v2.1, just got an upgrade to k8s 1.12 2 days ago.

**Comment by thxCode** [comment]
@superxor , Pod/workload metrics collect by `kube-state-exporter`, you could confirm this target as below via `System Project > Apps > cluster-monitoring App > Prometheus UI > Targets page`, and then ensure its State is `UP` or not.
![image](https://user-images.githubusercontent.com/3394724/58611177-c7ed1780-82e0-11e9-8e04-6d27543b48b5.png)

**Comment by superxor** [comment]
![prom](https://user-images.githubusercontent.com/18516510/58611472-e2f76180-82b7-11e9-9c7b-28f6ea3dc419.png)

**Comment by thxCode** [comment]
@superxor , please confirm the kubelet ep as below:
  ```
  > k get svc -n cattle-prometheus
  > k get ep expose-kubelets-metrics -n cattle-prometheus -o jsonpath='{range .subsets[*]}{range 
  .addresses[*]}{.ip}{"\n"}{end}{end}'
  ```
![image](https://user-images.githubusercontent.com/3394724/58611891-3c28ba80-82e3-11e9-9a4d-e68c1852f949.png)

**Comment by superxor** [comment]
Error from server (NotFound): endpoints "expose-kubelets-metrics" not found
Only got those (redacted)
> kubectl get ep -ncattle-prometheus
NAME                            ENDPOINTS                                                      AGE
access-grafana                  
access-prometheus             
expose-grafana-metrics         
expose-kube-cm-metrics          
expose-kube-etcd-metrics        
expose-kube-scheduler-metrics   
expose-kubernetes-metrics    
expose-node-metrics             
expose-prometheus-metrics       
prometheus-operated

**Comment by thxCode** [comment]
Could you view the Operator log under `System Project > cattle-prometheus Namespace > prometheus-operator-monitoring-operator Pod`? The `expose-kubelets-metrics Service` is managed by Operator:
![image](https://user-images.githubusercontent.com/3394724/58614486-130c2800-82eb-11e9-966d-6cc6b895481f.png)

**Comment by superxor** [comment]
@thxCode that pod doesnt exist

**Comment by superxor** [comment]
![image](https://user-images.githubusercontent.com/18516510/58618272-d8929300-82ca-11e9-9f3f-3520985f9a0a.png)
![image](https://user-images.githubusercontent.com/18516510/58618294-e47e5500-82ca-11e9-9e1e-a71506840a9a.png)

**Comment by superxor** [comment]
After redeploying it we see the pod now but we're having this termination loop issue again.

**Comment by superxor** [comment]
Metrics work if I disable  prometheus-operator-monitoring-operator :

![image](https://user-images.githubusercontent.com/18516510/58687424-3c2fc580-838a-11e9-8c2a-927ad2ca6476.png)

**Comment by thxCode** [comment]
@superxor , please help me to confirm:
- From Configmap page, are there many `cluster-monitoring.v` prefix configmaps?
- After enabling cluster monitoring, I mean the Rancher way `Cluster > Tools > Monitoring`, from kubectl console, execute `watch kubectl get prometheus cluster-monitoring -n cattle-prometheus -o jsonpath='{.metadata.resourceVersion}'` to watch that does the version of cluster-monitoring Prometheus CRD instance change so fast and never stop?

**Comment by superxor** [comment]
a) only: 	cluster-monitoring.v1	cattle-prometheus	release	an hour ago
b) doesn't print anything when its looping, its never starting up the pod properly
c) same as b

**Comment by thxCode** [comment]
@superxor 
1. The Operator manages Prometheus via `Prometheus` CRD. I don't understand why b) doesn't print anything. If the revision of `Prometheus` CRD keeps changing, that means other controller (another Operator?) are constantly modifying the CRD, and then the Operator has to continually deploy the Prometheus.
1. It makes sense if `kubectl get prometheus cluster-monitoring -n cattle-prometheus -o jsonpath='{.metadata.resourceVersion}'` has been stable in the same number
1. if matching #_2,  but get Prometheus redeploying, take a look the events from Statefulset via `k describe -n cattle-prometheus statefulset prometheus-cluster-monitoring`.

Give some test steps, as I am still not so clearer on here
1. Pause the Operator Pod, drop the Prometheus Pod, and then the Prometheus Pod should not be able to back usually.
1. Resume the Operator Pod, the Prometheus Pod has been created.
1. Record the events from `k describe -n cattle-prometheus statefulset prometheus-cluster-monitoring` and `k describe -n cattle-prometheus pod prometheus-cluster-monitoring-0`

Does it cause in a fresh v2.2.3? OS info? HA?

**Comment by superxor** [comment]
![image](https://user-images.githubusercontent.com/18516510/58697529-57a6ca80-83a2-11e9-9113-ca96172cf7d8.png)

Prometheus-cluster-monitoring survives about 10 seconds:
![image](https://user-images.githubusercontent.com/18516510/58697668-90df3a80-83a2-11e9-9def-f9c90400b8ab.png)

This is in v2.2.3, Ubuntu 18.04, Single Node install, no HA

**Comment by dwitzig** [comment]
Im getting the same issue. Workload metrics are empty, Grafana dashboard has no data.
I'm using rancher 2.2.4 with imported k3s:v0.5.0 cluster. is there an issue with imported clusters?

when I check prometheus targets I see `cattle-prometheus/exporter-kubernetes-cluster-monitoring/0 (0/1 up) ` is down. all others are up

**Comment by loganhz** [comment]
@dwitzig Can you try to set `exporter-kubelets.https` to true in advanced options in cluster monitoring setting page?

**Comment by dwitzig** [comment]
no change unfortunately. I can see `exporter-kubelets.https = true` in Answers under System > Cluster monitoring app.

`exporter-kubernetes-cluster-monitoring` in prometheus targets is still down.
not sure if relevant however `exporter-kubernetes-cluster-monitoring` is the only target using localhost endpoint `https://127.0.0.1:6445/metrics` all others are using the node-ip or cni-ip

**Comment by loganhz** [comment]
Could you check the status of workloads under cattle-prometheus ns? @dwitzig

**Comment by dwitzig** [comment]
everything looks to be up. cluster monitoring is working as expected 

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1388617/59393790-5f159d00-8dc0-11e9-9594-dc67a12038af.png">

**Comment by dwitzig** [comment]
is there anyway to modify the exporter-kubernetes-cluster-monitoring endpoint in the prometheus config ?

**Comment by CoolDarran** [comment]
> @dwitzig Can you try to set `exporter-kubelets.https` to true in advanced options in cluster monitoring setting page?

I have the same issue. When I set `exporter-kubelets.https` to `true` in cluster-monitoring, `exporter-kubelets-cluster-monitoring` endpoints turns to up. 

But after some while, it seems that rancher detect the configuration was changed, the configuration entry `exporter-kubelets.https` was turned to be `true` and re-deployed. Is this a normal operation in rancher?

**Comment by CoolDarran** [comment]
> > @dwitzig Can you try to set `exporter-kubelets.https` to true in advanced options in cluster monitoring setting page?
> 
> I have the same issue as described in [coreos/prometheus-operator#926](https://github.com/coreos/prometheus-operator/issues/926)
> 
> When I set `exporter-kubelets.https` to `false` in cluster-monitoring, `exporter-kubelets-cluster-monitoring` endpoints turns to up.
> 
> But after some while, it seems that rancher detect the configuration was changed, the configuration entry `exporter-kubelets.https` was turned to be `true` and re-deployed. Is this a normal operation in rancher?

emmm...
Fixed by setting this configuration entry in `Tools -> Monitoring -> advanced options`

**Comment by webts** [comment]
@CoolDarran I tried `exporter-kubelets.https` both true and false. Made no difference with the endpoint. (for me it was a IP issue)
I didn't keep the cluster up long enough to notice if the setting reverted.

I have since updated to rancher 2.2.7 and K3S 0.8.0 cluster. All prometheus targets look to be active however I still do not get any pod/workload metrics 

are you deploying a K3S clusters?

**Comment by dwitzig** [comment]
@CoolDarran I tried exporter-kubelets.https both true and false. Made no difference with the endpoint. (for me it was a IP issue)
I didn't keep the cluster up long enough to notice if the setting reverted.

I have since updated to rancher 2.2.7 and K3S 0.8.0 cluster. All prometheus targets look to be active however I still do not get any pod/workload metrics

are you deploying a K3S clusters?

**Comment by pr0xxy** [comment]
> @superxor , Pod/workload metrics collect by `kube-state-exporter`, you could confirm this target as below via `System Project > Apps > cluster-monitoring App > Prometheus UI > Targets page`, and then ensure its State is `UP` or not.
> ![image](https://user-images.githubusercontent.com/3394724/58611177-c7ed1780-82e0-11e9-8e04-6d27543b48b5.png)

**RE: I have reds:**
**=================================================================**

![image](https://user-images.githubusercontent.com/18562381/65780841-95311f80-e118-11e9-9ad7-be3d76904068.png)

![image](https://user-images.githubusercontent.com/18562381/65780522-e7be0c00-e117-11e9-9f9d-5d66312018fb.png)

This happens on any node that happens to have "prometheus-cluster-monitoring-0" running on it.

Like the node exporter cannot "talk" to that pod if they are on the same host.   All the nodes are open to each other port-wise. When i log onto a node without the issue and run:

lsof -i:9796 : 

![image](https://user-images.githubusercontent.com/18562381/65781752-31a7f180-e11a-11e9-9515-8fd8a34f0ca1.png)

The blue arrow is pointing to the offending node not reporting. This also the node that is has the "prometheus-cluster-monitoring-0".  

On the offending node 9796 is open but no connection to itself I guess.

**Comment by Negashev** [comment]
Repeated (Not enough data for graph)
Rancher 2.3.4, Provider: Custom, Kubernetes Version: v1.17.0, Monitoring 0.0.7

After upgrade from Rancher 2.3.3, Kubernetes Version: v1.15.x, Monitoring 0.0.6

Data in Prometheus exist

**Comment by Negashev** [comment]
My Solution:
- Full disable all monitoring in the cluster
- remove monitoring-operator and alert-operator in System project
- remove all namespaces cattle-prometheus*
- Enable monitoring
