### ISSUE TITLE
[BUG] Error edit yalm ingress

### ISSUE THREAD

**Issue by ElGranLoky** [rancher/rancher#20545]
**Steps to reproduce (least amount of steps as possible):**

- Edit YAML in rancher HA (import & custom cluster) Ingress 

**Result:**
![image](https://user-images.githubusercontent.com/2712200/58556837-39639200-821d-11e9-9ef1-ff8bc10103c2.png)

**Environment information**
- Rancher version : 2.2.3:
- Installation option : HA

**Cluster information**
- Cluster type : Custom/Imported
- Machine type : metal
- Kubernetes version : v1.13.5
- Docker version : v18.6.3

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/19723#issuecomment-492780313
