### ISSUE TITLE
Backport: Missing Eks cluster driver in UI / V2.2.2

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20555]
Backport rancher/rancher#19838

**Comment by westlywright** [comment]
Available in ui tag `2.2.70`

**Comment by westlywright** [comment]
Available in UI Tag `2.2.81`

**Comment by davidnuzik** [comment]
Version: v2.2.5 (release) UI: v2.2.89 (default that comes with release)

This is a simple en-us.yaml translations fix. I can confirm that "Amazon EKS" is now named correctly in the UI. It was "Amazon ECS" before the fix.

![image](https://user-images.githubusercontent.com/45179589/61255192-55af8580-a71c-11e9-80a6-97cdd8051f92.png)
