### ISSUE TITLE
Feature: Terraform-backed node provisioning

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#20554]
Node Provisioning

Most customers use “Custom” cluster because:
1. Node drivers are unreliable
- Can fail to provision nodes 20% of the time - anecdotal evidence
- Docker machine is no longer maintained/upgraded
2. Node drivers are inflexible
- Cannot take into account customers’ workflow for provisioning - Node provisioning is a multi step process with specific steps to take before, during and after provisioning. 

Terraform Based Node Providers:
- Is a standard in most enterprises 
- More reliable and flexible 

#### Example 1
- log the event(“number of nodes fell below the minimum. Starting new node”) and send a notification
- try to start the nodes on target infrastructure
- Apply labels, taints etc
- if successful, send a notification
- if fail, wait 2 minutes 
  - Retry xx times (configurable)
  - time out after xx seconds (configurable) on each try
  - send failure notification to the admins

#### Example 2 - (requirement of some brazilian customer)
- Provision vSphere node 
- Add storage and networking (need vSphere expert to define this in more details)
- Give each new node a specific name - <Team Name>+<count>
- Apply a security tag
- Assign a security group

### User experience:
Cluster Creation - 
- New/improved Terraform powered node drivers behind provider tiles (AWS/Google/vSphere/Custom etc)   - no change for the user 
- Ability to revert to legacy node drivers 
- New BYOTerraform tile - (different from custom because you are still provisioning nodes from Rancher)

Add/Edit Cluster Page
- Support example 1 and 2
- Ask user to provide their terraform script to delete nodes 

Autoscaling Group
- New UI for user (see autoscaling group doc)

**Comment by cjellick** [comment]
I don't fully understand the aspect of allowing users to create a workflow. Those workflow items are going to be so specific to the user's setup that I don't think we can pull it into Rancher.

**Comment by cjellick** [comment]
What are the initial providers we have to support? Is it:
- Google
- Azure
- AWS
- Bring your own

I believe previously we agreed that where possible, we should use the equivalent of ASGs in each cloud, but we need to be able to support non-ASG type providers like DO. Is that still accurate?

**Comment by wzrdtales** [comment]
Looking forward to this, especially looking for the efforts of autoscaling in rancher. maybe you want to pick up my thoughts from here https://github.com/rancher/rancher/issues/15145 . It would be really benefical and would make rancher unique once again at this time, if rancher can handle auto scaling without the ASGs in the cloud, but just works everywhere, where there is a proper driver (which the user can write just like an docker-machine driver in doubt).

**Comment by wzrdtales** [comment]
was this released or given up @cjellick ?
