### ISSUE TITLE
Hide controller manager and scheduler for ACK cluster

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20560]
What kind of request is this (question/bug/enhancement/feature request):
enhancement

Due to an upstream bug in K8s, the ACK cluster shows the controller manager and scheduler unhealthy forever. But the ACK cluster still works without problems, so it will be great if we can hide those two items from UI.

**Comment by davidnuzik** [comment]
@loganhz I do not have Alibaba ACK credentials for which to test with. I either need to be privately messaged the credentials or we may need to assign to someone else instead.

**Comment by loganhz** [comment]
Done

**Comment by rootwuj** [comment]
Tested with rancher/rancher:master from Jun 12
This version of the ACK cluster has hidden controller manager and scheduler.
Verified fixed
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/42061003/59341355-482c6780-8d3a-11e9-80a5-e6affa829384.png">
