### ISSUE TITLE
Not able to display container stats in host detail view when container is restarted. Even after refresh , I don't see the stats being displayed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2056]
Server version - v0.38.0-rc1

Launch host detail page of any container.
Try to stop and start/ restart container.
After the container gets to "Running" state , Not able to display stats.

<img width="1311" alt="screen shot 2015-09-16 at 5 50 42 pm" src="https://cloud.githubusercontent.com/assets/4266958/9922352/371cb0f8-5c9c-11e5-9f67-b42f60f05900.png">

Even after i refresh the page , I don't see the stat being updated.

<img width="1291" alt="screen shot 2015-09-16 at 5 51 24 pm" src="https://cloud.githubusercontent.com/assets/4266958/9922361/53fad83a-5c9c-11e5-9344-7051ccf1fb29.png">

**Comment by vincent99** [comment]
This is just one of the cases of #2057.. The stats for the restarted container are not in the stream.
