### ISSUE TITLE
Cluster logging not shipping control plane and etcd logs

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#20565]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher and prepare two hosts.
2. Create custom cluster using two hosts, 1 etcd/control plane, 1 worker
3. Install splunk (can use one of the hosts or separate server). Use:
```
docker run -d -p 8000:8000 -p 8088:8088 -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_PASSWORD=Pass0word!" --name splunk splunk/splunk:latest
```
4. Create event collector and token in Splunk. See https://docs.splunk.com/Documentation/Splunk/7.0.0/Data/UsetheHTTPEventCollector#Configure_HTTP_Event_Collector_on_Splunk_Enterprise
5. Go to Logging option of newly created cluster. Select Splunk, enter endpoint URL with port 8088 and token created in step 4. You may need to disable SSL in global settings to get port 8088 up. 

**Result:**
The logging pods are only created on the worker and not the etcd/control plane node. The logging pod daemon sets should be created on *all* nodes.

```
> kubectl get nodes
NAME           STATUS   ROLES               AGE     VERSION
ip-10-0-0-10   Ready    controlplane,etcd   9m59s   v1.13.5
ip-10-0-0-11   Ready    worker              8m9s    v1.13.5
> kubectl get pods -n cattle-logging -o wide
NAME                                   READY   STATUS    RESTARTS   AGE   IP          NODE           NOMINATED NODE   READINESS GATES
rancher-logging-fluentd-f74t9          2/2     Running   0          81s   10.42.1.7   ip-10-0-0-11   <none>           <none>
rancher-logging-log-aggregator-lz4bq   1/1     Running   0          81s   10.42.1.8   ip-10-0-0-11   <none>           <none>
> kubectl get ds -n cattle-logging
NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
rancher-logging-fluentd          1         1         1       1            1           <none>          2m42s
rancher-logging-log-aggregator   1         1         1       1            1           <none>          2m42s
```
Appears to be caused by incorrect tolerations set on the pod for the taints on the nodes:
```
> kubectl get node ip-10-0-0-10 -o yaml | grep -A6 taints
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    value: "true"
```
```
> kubectl get pod rancher-logging-fluentd-f74t9 -n cattle-logging -o yaml | grep -A17 tolerations
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
```

**Other details that may be helpful:**
Can workaround this issue by manually adding the following tolerations to both pods:
Label Key: node-role.kubernetes.io/etcd Operator: Exists  effect: NoExecute
Label Key: node-role.kubernetes.io/controlplane Operator: Exists Effect:NoSchedule

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.1
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM, t3a.medium in AWS
- Kubernetes version (use `kubectl version`):
v1.13.5
- Docker version (use `docker version`):

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

gzrancher/rancher#5506

gzrancher/rancher#10325

**Comment by aiwantaozi** [comment]
Hi, because we don’t know what taints user may add to the node. So most of chart like fluentd, node exporter from the community will tolerate NoSchedule, so if the user doesn’t want pods to deploy to this node, then the user could add other taints as you sent above. I need to note you that, after we set to accept all trains by default, when user don’t want to deploy logging to some node, they need to update logging app.

**Comment by aiwantaozi** [comment]
After communicated with Alena and Logan. We going to add more schedule option in logging configure. Providing some simple options like schedule to all nodes, schedule to workers, and allow user to set nodeSelector and tolerations in advance. 

Step to continue:
1. add tolerations option 
- tolerations effect: NoSchedule, operator: Exists (default, should schedule to all node if no extra taints)
- toleration everything
2. add node selector option
Not support affinity, if user needs it, could support later.

**Comment by izaac** [comment]
I reproduced this in Rancher `v2.4.5` following the same steps in the description. 
Logging pods only available in the worker.

**Comment by zbialik** [comment]
yep i have a post cluster build script that will actually update the fluentd workloads to tolerate the controlplane/etcd taints...  if only this could be done when initially enabling the logging :)

**Comment by paynejacob** [comment]
To test this issue, create a cluster with 2 nodes, one node should have etcd and the control plane. The second node should have the worker role.  Install logging and ensure there is at least 2 aggregator pods.  In logging v2 this will be the fluentbit container.

**Comment by paynejacob** [comment]
https://github.com/rancher/dashboard/issues/1244

**Comment by izaac** [comment]
#29028

**Comment by maggieliu** [comment]
Moving back to 2.5 since there is a PR up for the bug. If this still doesn't fix it, then will re-assess.

**Comment by paynejacob** [comment]
https://github.com/rancher/charts/pull/673

**Comment by paynejacob** [comment]
https://github.com/rancher/charts/pull/673

**Comment by izaac** [comment]
This will work in `v2.5` `rancher-logging` (or Logging v2)

https://github.com/rancher/rancher/issues/29028#issuecomment-696942012
