### ISSUE TITLE
Backport: Fail to create persistent volume on OpenStack

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20562]
Backport https://github.com/rancher/rancher/issues/19237

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc19`.  @sangeethah it's an api/ui fix, and we can do the first round of testing w/o the real open stack cluster. Just need to make sure you can create open stack volume in the api - before it wasn't working

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.24-rc19

* Reproduced original issue in v2.2.3, v2.2.4-rc18
  * When creating openstack PV: 
    * `Validation failed in API: PersistentVolume "openstack-test" is invalid: [spec.cinder.volumeID: Required value, spec.cinder.secretRef.name: Required value, spec.cinder.secretRef.namespace: Required value]`
* Created cluster
* Created openstack PV successfully through UI with all required fields (did not test actual openstack cluster)

**Comment by kinarashah** [comment]
@bmdepesa could you also double check the edit use case? We also made a fix to not allow certain fields to be edited (volumeMode and spec.PersistentVolumeSource)

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.4-rc20

* Created cluster
* Created openstack PV
* Unable to edit `cinderPersistentVolumeSource` (API / no option in UI)
* Unable to edit `volumeMode` (API / no option in UI)
