### ISSUE TITLE
UI - no error message shows if the name exists when creating a cloud credential

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20577]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.2.4-rc20
- add a new cloud credential from either the node template or the cloud credential page
- enter a name that is already used
- fill out all fields
- click create to save

<img width="966" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58665726-5b751700-82e6-11e9-9a43-8c4083522165.png">
<img width="965" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58665733-6039cb00-82e6-11e9-9d91-83687d0cee58.png">

**Result:**
- cannot save the template, but there is no error message showing the reason
- the API response shows the error message
```
{"baseType":"error","code":"AlreadyExists","message":"secrets \"ec2\" already exists","status":409,"type":"error"}
```
<img width="851" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58665790-87909800-82e6-11e9-80ff-fd9c721c4208.png">

**Comment by davidnuzik** [comment]
Issue does NOT occur in v2.2.3

**Comment by deniseschannon** [comment]
In general, it seems that there is no error message when the API for creating a cloud credential is invalid:

https://github.com/rancher/rancher/issues/20577
https://github.com/rancher/rancher/issues/19677
https://github.com/rancher/rancher/issues/19759
https://github.com/rancher/rancher/issues/21215

**Comment by davidnuzik** [comment]
Version: master-head (7/25/19)

The UI now passes along the api error message:

![image](https://user-images.githubusercontent.com/45179589/61908397-6f06bd80-aee4-11e9-8d6a-e4b2fcc2985e.png)

I ensured this works correctly both via "Add Cloud Credential" modal from "Cloud Credentials" page and when creating a new node template (pick "Add New" button to make new cloud credential).
