### ISSUE TITLE
RKE cluster not recognized

### ISSUE THREAD

**Issue by ravenpride** [rancher/rancher#20587]
I've installed Kubernetes on a virtual machine with RKE 0.1.18. After that I installed helm and cert-manager as described in the rancher documentation. Everything went smoothly. Installing rancher 2.2.3 via helm worked fine as well. After logging into rancher I noticed, that rancher had added the cluster it is running on to the list of managed clusters as "local". The provisioner is "Imported". I would expect it to be "RKE". Rancher seems not to be able to detect a RKE cluster. Without recognizing RKE, there seems no way to edit RKE specific parameters like PSPs.

Is that behavior intentional or is there anything I can do to fix it?

Thank you in advance!

**Comment by ravenpride** [comment]
There is another issue popping up in conjunction with this. As the Cluster is not recognized as an RKE provisioned cluster, network isolation does not work. There are pods in different projects that can communicate with each other.

Any help is appreciated ;-)

**Comment by ravenpride** [comment]
Ok, now I see this is by design (see [blog post](https://rancher.com/blog/2019/2019-02-04-rancher-vs-rke/)).

To summarize:
1. RKE provisions a "pure" Kubernetes cluster. It does not do anything to prepare it for Rancher. Rancher can be installed onto this cluster to gain high availablity by storing Rancher data as Kubernetes resources which are replicated by etcd. Rancher sees its own cluster as "local" in the cluster list.
2. As far as I understand it, the only way to get a cluster with project isolation which is manageable via the Rancher UI is to separate the Rancher installation from the production cluster. I think I will install it on separate set of VMs - separated from the production cluster

**Comment by superseb** [comment]
Yes it is recommended to use the RKE cluster created for Rancher solely for Rancher as described here: https://rancher.com/docs/rancher/v2.x/en/installation/ha/

All the options for RKE are in the RKE docs here: https://rancher.com/docs/rke/latest/en/. Rancher specific features (like projects and project isolation) are available when using Rancher and creating clusters via Rancher.

Let me know if something else is unclear.
