### ISSUE TITLE
"failed to start user controllers for cluster XXXX" - "ClusterUnavailable 503: cluster not found"

### ISSUE THREAD

**Issue by surco1971** [rancher/rancher#20592]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
After respawning of master nodes of a client cluster, it was not possible anymore to register/remove nodes to the cluster. 

The rancher container on the seed instance complaint, that the api server can not be reached. But the apiserver IP was an old one, of a VM which was removed days ago.

https://github.com/rancher/rancher/issues/13314 describes similar error situation ("Turns out the cluster api definition shows the apiEndpoint and rkeConfig to still contain the node that I have already deleted from the ui, hence the issue while re-adding the instance again.")

So we tried to get rid of the apiEndpoint. Knowing that a new client cluster does not have the apiEndpoint in the etcd value for the cluster, we decided to remove the entry for the faulty cluster (in the etcd db). As well the old node entries were removed from the cluster json and also the keys. The changes were visible in the "View on API", but the rancher application had the following error:

"2019/05/31 15:33:12 [ERROR] ClusterController local [user-controllers-controller] failed with : failed to start user controllers for cluster c-jvfc5: ClusterUnavailable 503: cluster not found"

Looking into the code, it is tried in pkg/clustermanager/manager.go to load the  cluster.UID into a controller. I checked the UID in the etcd value, it seems not to be changed.

**Result:**
New master of a client cluster (still) stuck in Registering/"Waiting to register with Kubernetes"

What causes the rancher application to loose the cluster? How to overcome this situation?

**Other details that may be helpful:**
During analysis we saw that rke statefile and also the etcd value for the cluster still contains old IPs. is this a normal situation? Actually it is very hard to get single nodes respawned without trouble.

**Environment information**
- rancher/rancher-agent:v2.2.2
- HA

**Cluster information**
- Cluster type: Custom/Imported
- Machine type: Cloud 
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
18.06.3-ce
```

**Comment by surco1971** [comment]
We found a workaround, just pinning IPs for resapwned master VMs. That works more stable.

**Comment by superseb** [comment]
Could you describe the exact steps to reproduce so we can determine what the exact bug is and how to reproduce and fix it? This includes describing the exact steps taken to create the cluster, how many nodes with what roles are initially added and what `respawning of master nodes` exactly means and what we can do to reproduce that same behavior? (especially what it means, in what order, and what nodes with what roles were respawned)

The requirement for static IP (or DHCP reserved lease) for cluster nodes is documented, but not sure if respawns means rebuild or reboot or anything else, if you could clarify that we can look into the issue.

**Comment by superseb** [comment]
Let me know if this needs help.

**Comment by telderfts** [comment]
Would really love to know if there is a fix for this as we are experiencing the same issue as well
