### ISSUE TITLE
Support Image Scanning (Clair)

### ISSUE THREAD

**Issue by ankur111** [rancher/rancher#20597]
Users should be able to use Harbor UI to scan their images

**Comment by sowmyav27** [comment]
verified on `rancher:master` (06/05/2019)

1. On enabling Clair on Global Registry page on Rancher UI, Scanning is enabled on Harbor UI. 
2. Images can be scanned. 
3. The scanned images were used to deploy workloads on Rancher. 
4. Workload - `global-registry-harbor-clair` is available under local cluster --> System project --> cattle-system namespace.
