### ISSUE TITLE
Catalog needs to show certified entries before community entries

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#20602]
There are three types of entries in catalog today:

1. Partner certified (marked "Partner"), like JFrog and Portworx
2. Rancher maintained, like Wordpress and Longhorn
3. Community maintained, like those from upstream Helm repo

All these entries are mixed together. A small number of partner certified entries disappear into the vast number of community entries.

I'd like to change the catalog view so that it displays entries in sections, sort of like how Netflix displays movies in sections like "Recently watched, Popular on Netflix, My list, etc."

The sections should probably just correspond to different catalogs.

1. The catalog page should begin with the "Library" section. Both partner certified and Rancher maintained entries should go in that section. All entries should be marked as "Certified."
2. If the user scrolls down he should see other sections like "Helm Stable", "Helm Incubator", and custom catalogs.

**Comment by davidnuzik** [comment]
Version: master-head (7/30/19)

I am reopening the issue. The requirements are not in yet.
Observe that the styling changes are in as pictured below, however we are not separating things in sections as described in the issue description. I also only have the Library in this screenshot and yet all "Partner" apps are not at the top. There is also no "Certified", "Helm Stable", and "Helm Incubator" sections.

![image](https://user-images.githubusercontent.com/45179589/62155675-57ea1600-b2be-11e9-99d3-37185420073f.png)
![image](https://user-images.githubusercontent.com/45179589/62155694-60dae780-b2be-11e9-8469-8042cc8946d4.png)

**Comment by tfiduccia** [comment]
@vincent99 - Wireframes for catalog
https://xd.adobe.com/view/c1a93038-6113-43c1-628b-781b5c952fd8-b798/

**Comment by tfiduccia** [comment]
@davidnuzik - did initial pass and UI looks good.  Let me know if you need any help with a more thorough pass.

**Comment by davidnuzik** [comment]
The sections have been added (need to test further)

The prioritizing certified entries / partners/etc has been dropped based on offline discussion with @tfiduccia so this is no longer required. We should expect to see Experimental/Partners in various places (sort alphabetically only).

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

Confirmed we now separate different catalogs by sections now. You can Collapse them or Expand them (They are all expanded by default). This setting also persists which is nice. If I leave the page and come back any catalogs will still remain collapsed until I expand them again.

These are sorted by first any catalogs I have added (alphabetical) and then Library, then Helm Stable, then Helm Incubator.

Example Screenshot shows all my catalogs collapsed except for one. Notice the order is as I described:
![image](https://user-images.githubusercontent.com/45179589/62581830-3d381400-b85f-11e9-9114-a7035fbf3cec.png)

We decided to not order by partner/experimental/etc.

I smoke tested by deploying some apps to ensure they still deploy without any issues. Upgrades/etc working fine as well.

From a usability perspective the look/feel looks good. As far as changing the format nothing has really impacted usability in a negative manner. I can't get descriptions now when viewing apps list but it's also cleaner looking and I approve of the new look overall.
