### ISSUE TITLE
Simplify catalog submission to allow link to Helm chart

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#20603]
Today when a user submits a catalog into Rancher, he/she needs to create a PR including `questions.yml` and `app-readme.md` as well as all the files for the Helm chart itself.

I would like to make a change so that the user only needs to submit `questions.yml`, `app-readme.md`, and a new file, perhaps named something like `chart-repo` that contains a URL to the Helm chart. This will make it easier for partners to submit charts. User can of course continue to submit full charts as before.

**Comment by cjellick** [comment]
Raw notes from design/feasibility discussion:
- would this cause us to have to download, extract, and traverse all tarballs?
- security concerns: -  we don't control that external source. It could suffer a man-in-the-middle type attack. Can we require a hash to verify the content?
- Process/QA concerns:
  - The contents that the URL points at could change which could thus cause a breaking change without us knowing
    - Solving this is mostly a process issue. need to guide them to point at immutable versions of their charts
  - Debugging - how do we know what the chart was actually launched with
  - Who is making sure the integration with the external chart and the questions ? Who owns QA for these charts?
- Could this just be supported in git catalogs or would we also need to support it in real helm repos?
- Alternative solution: we could support loading/using a questions.yaml in non-git based catalogs. There are currently some issues with that. See this thread for more details: https://rancher.slack.com/archives/C039Y2P93/p1561641729120900
  - interesting highlights: in addition to icon url, we need to care about where catagory and labels are stored and that getting to those does not require downloading and extracting tarball.
  - Even if we supported that, we would still need a away to get a submission into our catalog
- Can we only support a tarball as the target or do we need to support git repos?
- How would we get the icon? It is currently specified on a per-version basis in either charts.yaml or the helm repo's index.yaml. Where would it come from in this case? We don't want to have to download and extract a tarball just to get the icon url.
- What if the integrator just had to specify an index.yaml file that contained ALL their versions?
- node driver style? supply a URL and we pull it down

**Comment by cjellick** [comment]
related https://github.com/rancher/rancher/issues/20977

**Comment by cjellick** [comment]
for security, should consider making use of provenance files: https://github.com/helm/helm/blob/master/docs/provenance.md

**Comment by cjellick** [comment]
@ibuildthecloud suggested a radically different approach which is this:
- Run a nightly cron to sync third party helm repos to our rancher/charts repo (start script here https://github.com/ibuildthecloud/rancher-charts/blob/master/clone.sh). This would literally merge new versions of a chart into our repo
- Have a repo where we only maintain questions. This would be structured on a per-chart basis, but under a chart directory, you could directly have a questions.yaml and app-readme.md file. This would be the default for all versions of the chart unless a specific version folder existed. If a specific version folder exist, use those questions instead.
- We could also possibly add some logic to detect if the values.yaml changed from the last version and make an intelligent decision about overlaying questions based on that.

**Comment by SimonHeimberg** [comment]
Deploying own charts is unhandy currently. For serving a chart with subcharts:
* Serve a repo for questions.yml to work (because of #20977).
* And for subcharts, serve a helm repo.

Being able to serve the questions with the helm repo, or to provide the questions somehow else (maybe solved by this issue) would help.

**Comment by deniseschannon** [comment]
As of v2.5, the new apps and marketplace repos support being able to handle repos with links to helm charts.
