### ISSUE TITLE
Can not create a stack

### ISSUE THREAD

**Issue by aa-aahmed** [rancher/rancher#20608]
unable to deploy cluster via API, I have tired creating key with or without scope but still no luck. 

[root]# rancher-compose -p ps up
ERRO[0000] Failed to open project ps: Can not create a stack, check API key [token-pthfb] for [https://rancher.belong/v3] 
FATA[0000] Failed to read project: Can not create a stack, check API key [token-pthfb] for [https://rancher.belong/v3] 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`authenticated.apikeys`|

**Comment by superseb** [comment]
`rancher-compose` is not for use with Rancher v2.x, it was in use for 1.6 (and also deprecated there).

The way to interact with Rancher is using the CLI as described on https://rancher.com/docs/rancher/v2.x/en/cli/
