### ISSUE TITLE
Is it possible to use private Docker registry in pipeline ?

### ISSUE THREAD

**Issue by mediarl** [rancher/rancher#20604]
I saw many related questions to this need. I want to use pipeline to publish my Docker images (after build) to an external registry, which seems a common case. 
In my case, I will be using canister.io, but same should apply to quay.io and other Docker registry.
I browsed the documentation and issues several times but can't find an answer.
What is the syntax to publish to an external registry ?

**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce**
In rancher-pipeline.yml, add a publish step:
...
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: my-image:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: cloud.canister.io:5000/username/repo
...

**Result:**
02:37:33 insecure registry cloud.canister.io:5000/username/repo is not valid: invalid host "cloud.canister.io"
02:37:48 time="2019-06-01T02:37:48Z" level=fatal msg="Error authenticating: exit status 1"

**Other details that may be helpful:**
Of course, as I dont provide username and password, I get this authentication error. Where should I pass those infos?
I tried creating a registry which takes an url and username/password. But then, how do I configure my rancher-pipeline.yml to use that registry info?

**Environment information**
- Rancher version: 2.2.3
- Installation option: single install

**Comment by gitlawr** [comment]
You can add registry credentials in project-resources-registries.
It will do a docker login to the remote registry with a matching credential in a publish-image step.

**Comment by samsiu2014** [comment]
I have the same issue.
It shows me "x509 certificate signed by unknown authority".
After i added 
```
 env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"  
```
to the rancher-pipeline.yml.
Then the error message becomes "insecure registry  is not valid: invalid host.
What should i do?

Environment information
- Rancher version: 2.2.6
- Installation option: single install
