### ISSUE TITLE
v2.2.3 all nodes down PLEG unhealthy - major outage

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#20607]
rancher v2.2.3
k8s 1.13

After upgrading another of our clusters yesterday to k8s 1.13 ALL(50+) worker nodes except the 3 master are dead in the water with: UNAVAILABLE 	PLEG is not healthy: pleg was last seen active 3h43m22.436428523s ago; threshold is 3m0s
Reboot fixed it but obviously it was a complete service outage because no pods were scheduled.
If I had to guess I'd say the upgrade process is unclean and forgetting something, I know this PLEG error from k8s but all at once is weird.

screenshot excerpt
![rancherfail](https://user-images.githubusercontent.com/18516510/58744563-6eeec200-844d-11e9-8b4f-14a5b262abdf.png)

**Comment by loganhz** [comment]
Just FYI. There is a blog for PLEG https://developers.redhat.com/blog/2019/11/13/pod-lifecycle-event-generator-understanding-the-pleg-is-not-healthy-issue-in-kubernetes/
