### ISSUE TITLE
[v2.2.x][v2.3.x] Unable to delete SSL certificates

### ISSUE THREAD

**Issue by niranjan94** [rancher/rancher#20614]
**What kind of request is this:** `bug`

**Steps to reproduce:**
- add certificate (1) to resources > certificates.
- use the certificate (1) on an ingress.
- add another certificate (2) with the same key and cert chain but different name.
- change the certificate the ingress uses to the other certificate (2).
- try deleting certificate (1) in resources > certificates or via API.

**Result:**
The request will give a `200` response. But the certificate will not have been deleted.

**Other details that may be helpful:**
- It is a wildcard certificate
- Might be related. I'm seeing a re-occurrence of https://github.com/rancher/rancher/issues/15073.

**Environment information**
- Rancher version: `v2.2.3`
- Installation option: `single install`

**Cluster information**
- Cluster type: `Infrastructure Provider`
- Machine type: `cloud`
- Kubernetes version: `v1.13.5`
- Docker version: `17.3.2`

**Comment by adrianovieira** [comment]
@niranjan94,
sometimes this thing happens here.

What I believe is that the problem would be related to the `301 redirect`, wouldn't be?

Have you tried to clean the browser cache?

**Comment by niranjan94** [comment]
@adrianovieira thanks for your response. But I don't think this is related to the browser cache. 

Calling the rancher API directly via curl or postman `DELETE /v3/project/<cluster>:<project>/certificates/<certificate>` also results in the same thing. The certificate does not get deleted.

**Comment by niranjan94** [comment]
Can confirm the issue exists in v2.2.4 too.

**Comment by mcvermeulen** [comment]
I have the same issue in v2.2.8, keeps using the old cert.

**Comment by niranjan94** [comment]
This exists in `v2.3.1` too

**Comment by rroemer** [comment]
We are seeing the same issue in Rancher 2.3.5. 
We are unable to delete the certificates. 
Calling a Delete from the API gives me 200 OK, but does nothing (see screenshot).
I can delete the secrets using kubectl but they still show up in the UI and API.
The certficates were added a long time ago (Around version 2.0.x).

![rancher-cert-error](https://user-images.githubusercontent.com/25124388/78259310-cd1c8380-74fc-11ea-8d8c-cc2b699b1ff7.png)

**Comment by MiroslavSotirov** [comment]
This seems to be present in 2.4.5 as well. I'm unable to update the ingress secret with a new cert(certificates from Files). Even completely deleting all secrets, the UI still shows the old(initial) certificate.
