### ISSUE TITLE
Tracing and Grafana URL in Kiali doesn't work

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20615]
rancher/rancher:master

Steps:

1. Enable istio in a cluster
2. Deploy istio bookinfo yaml
3. Go to kiali UI
4. Find the any service detail page in Kiali UI
5. Click the tracing URL or Grafana URL.

Result:

It shows a Rancher 404 page

Expected:

It should take users to Jaeger UI and pre-fill the related service field automatically.

**Comment by bmdepesa** [comment]
rancher/rancher:master

* Enable istio in a cluster
* Deploy istio bookinfo yaml
* Go to kiali UI
* Find the any service detail page in Kiali UI
* Click the tracing URL or Grafana URL.
* Grafana and Jaeger both load with the correct data
