### ISSUE TITLE
[UI] Istio - Support one click upgrade for Istio

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20617]
Support one click upgrade for Istio

**Comment by davidnuzik** [comment]
@n313893254 seeing as how we only have istio version 0.0.1 I suppose I just need to hold this issue for a while and wait for a newer version so can test upgrade functionality?
cc: @loganhz

**Comment by loganhz** [comment]
Yes

**Comment by davidnuzik** [comment]
Note: This is staying open until there is a newer version of Istio for me to upgrade to (so I can test).

**Comment by davidnuzik** [comment]
I think this is ready to test. Looks like Istio was bumped to v1.2.4; may need to contact logan et al to determine how we test. We need to go from v1.2.0 to v1.2.4 and ensure the one-click-upgrade works in the UI properly.

**Comment by loganhz** [comment]
istio added v0.0.3 for testing:
`https://github.com/guangbochen/system-charts.git`  `istio-test` branch

1. you can deploy the isito using default system-chart with v0.0.2
2. change the system-chart to custom repo and upgrade to v0.0.3

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (09/04/2019)

The upgrade is working with the instructions above there is one difference in the pods setup upgrading from Istio 1.2.4 (0.0.2) to 1.2.5/or latest (0.0.3). The pods configuration is now using sidekicks after the upgrade. 

But besides that all the pods were updated to the latest 1.2.5, and the graphs were functional. Access to Kiali, Jaeger, Grafana and Prometheus from within the  UI was working too.

Graphics are also properly generating after the upgrade in the Cluster dashboard.

Some screenshots: 

After activating Istio 1.2.4
![Screen Shot 2019-09-04 at 10 38 56 AM](https://user-images.githubusercontent.com/27659/64279737-9057c200-cf04-11e9-9488-3f688216eaf9.png)

Upgrade is available message (@loganhz undefined was left on purpose to get the latest?):

![Screen Shot 2019-09-04 at 10 40 11 AM](https://user-images.githubusercontent.com/27659/64279793-a82f4600-cf04-11e9-9d3f-d2a682e409e7.png)

Upgrading:

![Screen Shot 2019-09-04 at 10 40 45 AM](https://user-images.githubusercontent.com/27659/64279882-d01ea980-cf04-11e9-83f7-74147e9aeb42.png)

Upgrade completed (note the sidekicks):

![Screen Shot 2019-09-04 at 10 44 37 AM](https://user-images.githubusercontent.com/27659/64279909-e167b600-cf04-11e9-9cd6-c56008ecdad4.png)

Istio version after upgrade:

![Screen Shot 2019-09-04 at 10 45 05 AM](https://user-images.githubusercontent.com/27659/64280018-15db7200-cf05-11e9-813b-09f56b6f2aa5.png)

**Comment by izaac** [comment]
Rancher version: `master-head` (v2.3) (09/05/2019)

@sangeethah I just validated the Istio was still functional after the upgrade as suggested, so adding to my last comment. Upgrade is same from 1.2.4 to 1.2.5

![Screen Shot 2019-09-05 at 3 02 27 PM](https://user-images.githubusercontent.com/27659/64386558-54009080-cfee-11e9-9b4b-711dda56b221.png)

![Screen Shot 2019-09-05 at 3 01 35 PM](https://user-images.githubusercontent.com/27659/64386586-65e23380-cfee-11e9-914b-953461298e86.png)
