### ISSUE TITLE
[v2.2.3] Pipeline Pushes docker image over HTTPS to insecure registry, doesn't fall back to HTTP

### ISSUE THREAD

**Issue by ainiml** [rancher/rancher#20611]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1. Run registry:2
2. configure insecure registries in `/etc/docker/daemon.json` 
3. Run pipeline to build docker image and push to registry

**Result:**
![image](https://user-images.githubusercontent.com/28725423/58757494-59c07480-84db-11e9-902a-2139803078cc.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.3`
- Installation option (single install/HA): `single`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `custom`
- Machine type (cloud/VM/metal) and specifications (CPU/memory): `aws`
- Kubernetes version (use `kubectl version`): 

```
root@trawsasedsb01:~# rancher  kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
root@trawsasedsb01:~# docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ainiml** [comment]
Follow https://github.com/rancher/rancher/issues/16683#issuecomment-441161838

However, kube-dns doesn't have a round to the host address

```
08:15:27 Get https://registry:5000/v2/: dial tcp 172.17.0.5:5000: getsockopt: no route to host
```

**Comment by ainiml** [comment]
and using the `<deployment>.<namespace>` name, it doest' drop to http

```
08:25:47 Get https://registry.trawsasedsb01:5000/v2/: http: server gave HTTP response to HTTPS client

```

**Comment by gitlawr** [comment]
The publish-image steps use dind model, so it's not using the `/etc/docker/daemon.json
` you configure on the hosts.
You can confiture that by adding an environment variable for the step, see: https://github.com/rancher/rancher/issues/16218#issuecomment-432971660

**Comment by ainiml** [comment]
@gitlawr is the format correct?

**Comment by gitlawr** [comment]
Regarding this error message can you check: https://github.com/moraes/config/issues/1#issuecomment-18842169

**Comment by ainiml** [comment]
That fixed it!

Thanks!

A)
https://github.com/rancher/rancher/issues/16218
https://github.com/moraes/config/issues/1#issuecomment-18842169
