### ISSUE TITLE
Support configure Istio to re-use cluster level prometheus when monitoring is enabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20616]
Support configure Istio to re-use cluster level prometheus when monitoring is enabled

Now istio and monitoring will deploy 2 different prometheus instance.

Users should be able to select use existing Prometheus in cluster monitoring or deploy a new one for istio

**Comment by trondhindenes** [comment]
I couldn't agree more with this. Rancher's multi-prometheus design is extremely wasteful, especially in smaller clusters.

**Comment by loganhz** [comment]
@trondhindenes Yes, we have decided to remove the multi-prometheus design.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head

* When enabling Istio, user is prompted to enable monitoring first (if it is not enabled already)
* Istio does not deploy it's own prometheus and instead uses prometheus from cluster monitoring
* Metrics appear in Istio dashboard correctly.
* UI links direct user to prometheus / grafana correctly
