### ISSUE TITLE
Navbar menus go away when get a new node update while provisioning

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20627]
Version: Master (v2.3) (6/3/19)
This is probably a pre-existing issue

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster
- IMMEDIATELY go to the Nodes page. Click on the Tools menu.

**Result:**
The tools menu keeps going away as soon as there is a new update in the red info section.
![image](https://user-images.githubusercontent.com/45179589/58821151-4e5b6f00-85e9-11e9-8895-78f618cb0616.png)

It was difficult to get a screenshot, every time there is a new message in this info area the tools menu disappears and I have to keep clicking on "Tools". This makes it very hard to navigate. Consider this use case: I have a cluster up. I'm adding several worker nodes and as they provision the info section updates frequently. Now I can't easily navigate to Tools -> (anything) because the menu keeps disappearing.

**Comment by westlywright** [comment]
Note to self: shouldUpdateNav tree is updating because the cluster state is changing. we need to check that it actually changed before we replace it and redraw the menu.
