### ISSUE TITLE
[Enhancement] Prometheus Monitoring Remote Write

### ISSUE THREAD

**Issue by MaxDiOrio** [rancher/rancher#20624]
**What kind of request is this (question/bug/enhancement/feature request):**  Enhancement

**Other details that may be helpful:** I'm investigating using the built-in Rancher cluster and project level monitoring to replace the prometheus chart or prometheus-operator - mostly because it integrates directly with the dashboard, which is nice.  It seems to work well, however I'd like the ability to easily configure a Remote Write endpoint in Prometheus so we can export metrics to our long term storage server VictoriaMetrics.

**Comment by dawidmalina** [comment]
https://github.com/rancher/system-charts/pull/123

**Comment by jiaqiluo** [comment]
The enhancement is validated in master-head ff24cb9 with the monitoring template **0.0.8**

Steps:
 
- when enabling the **cluster monitoring**, pass the following answers under the advanced section in the monitoring enabling page
```
prometheus.remoteWrite[0].url = http://remote1/push
prometheus.remoteWrite[0].remoteTimeout = 33s
prometheus.remoteWrite[0].readRecent = true

prometheus.remoteWrite[1].url = http://remote2/push
prometheus.remoteWrite[1].name = rw_tls
prometheus.remoteWrite[1].tlsConfig.certFile = valid_cert_file
prometheus.remoteWrite[1].tlsConfig.keyFile = valid_key_file

prometheus.remoteRead[0].url = http://remote1/read
prometheus.remoteRead[0].proxyUrl = http://proxy.url
prometheus.remoteRead[0].bearerToken = token-value

prometheus.remoteRead[1].url = http://remote2/push
prometheus.remoteRead[1].remoteTimeout = 33s
prometheus.remoteRead[1].readRecent = true
```

![image](https://user-images.githubusercontent.com/6218999/74790634-678a7580-5275-11ea-9a09-a6d9017b8a49.png)

-  after the monitoring app is deployed and active, open the Prometheus endpoint and check its configuration. We can see that those values are applied

 
<img width="742" alt="Screen Shot 2020-02-18 at 5 36 07 PM" src="https://user-images.githubusercontent.com/6218999/74791308-5b9fb300-5277-11ea-906f-05c4bc62aefb.png">
