### ISSUE TITLE
HTTP 503 when attempt to access "Service Mesh" page before cluster is ready

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20626]
Version: Master (v2.3) (6/3/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster
- BEFORE the cluster is fully ready (i.e. right after you create it) go to cluster level and Tools > Service Mesh

![image](https://user-images.githubusercontent.com/45179589/58820325-2d921a00-85e7-11e9-853e-652d651b6f02.png)

**Result:**
HTTP 503

![image](https://user-images.githubusercontent.com/45179589/58820348-397ddc00-85e7-11e9-9b7e-94f07b55ad91.png)

**Expected Result:**
A growl error or we land on the page but it has a nice message saying not ready. Basically anything to more gracefully handle this.

**Comment by loganhz** [comment]
Now we will not allow users to go to that page if cluster is not ready like `Projects/Namespaces` menu

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/5/19)

I can confirm that the (Cluster level) > Tools > Service Mesh menu option is no longer clickable until the cluster is ready (at least have etcd,cp). This is similar to the behavior of the Projects/Namespaces nav bar option as Logan mentioned.

As soon as my cluster is ready then I am immediately allowed to click on the "Service Mesh" option on the Tools menu.
