### ISSUE TITLE
[MCA] Add entry to questions for charts to designate if app needs project or cluster role

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20634]
Version: Master (v2.3) (6/3/19) HA configuration
(Pre-existing issue v2.2.x)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Details:**
Today, the user must know if a multi-cluster app requires the "Project" or "Cluster" role before deploying.

This can be confusing if it is not clear to the user what the app is deploying and doing. Most apps do not specify all the required permissions in their descriptions.

We'd like to add some kind of flag or something in questions so that when a user configs a multi-cluster app the UI will be able to automatically pick Project or Cluster role for them.

This will reduce the likelihood of running into an issue when deploying a multi-cluster app but with insufficient permissions.

**Result:**
Streamline app deployment; user does not need to understand what the app is doing / what permissions are required. Reduce chance of app failing to deploy due to insufficient RBAC perms.

**Other details that may be helpful:**
Apps from library that require the cluster role based on my testing with simple/minimal configuration:

```
Artifactory-HA (Jfrog)
Cert-Manager (Let's encrypt)
Datadog
Drone
EFK
Etcd-operator
Grafana
Istio
Kafka
Kubeflow
Kubernetes-Dashboard (it clearly states in app details need cluster admin)
Longhorn
NFS-Provisioner
OpenEBS
Portworx
Prometheus
StoreageOS-Operator
Vault-Operator
18 of 31 (58%)
```

Apps that do not need cluster role based on my testing with simple/minimal configuration:
```
chartmuseum
docker-registry
fluentd-aggregator
hadoop
magento
mariaDB
memcached
mongoDB
mongoDB-replicaset
mysql
phpBB
redis
wordpress
13 of 31 (42%)
```

**Comment by davidnuzik** [comment]
Will probably need UI issue to leverage this once available.

**Comment by guangbochen** [comment]
We can add an optional field like `role: ["cluster", "project"]` in the `questions.yml` file of each chart (default to allow all users if no role is not specified). 
But this will require both backend and UI support and changes.
``` yaml
role:
- cluster
- project
questions: 
...
```
