### ISSUE TITLE
Using cloud config in Azure with a Service Principal that has multiple subscriptions fails to operate

### ISSUE THREAD

**Issue by ankur111** [rancher/rancher#20632]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
It appears that when a service principal is used that has multiple subscriptions, the proper subscription id is not passed down through cloud config. This occurs regardless of the underlying OS. The results are the the same using Ubuntu 18.04 and RancherOS. In contrast, using a service principal with only one subscription works when all the other configuration parameters are identical.

**Result:**
’ve found reference in your doc at https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/azure/ that we should be using the cloudproviders section in our config file. Furthermore, it states that we must use the hostname_override parameter to match the node name in Azure. When I follow the instructions, I get the following error:

INFO[0179] [sync] Syncing nodes Labels and Taints
FATA[0191] [ "kafkakubeworker1" not found]

**Other details that may be helpful:**
Logs:
kubelet.log

+ azure_cloud=AzureCloud
+ az cloud set --name AzureCloud
+ az login --service-principal -u REDACTED-p  REDACTED --tenant REDACTED
++ az vm nic list -g HCE-CHQ-Sandbox2-West --vm-name rancherkube
++ jq -r '.[0].id'
++ cut -d / -f 9
ERROR: Resource group 'HCE-CHQ-Sandbox2-West' could not be found.
+ local az_vm_nic=
++ az vm nic show -g HCE-CHQ-Sandbox2-West --vm-name rancherkube --nic
++ cut -d/ -f 11
++ jq -r '.ipConfigurations[0].subnet.id'
...
E0522 14:16:43.968728    6751 azure_backoff.go:67] GetVirtualMachineWithRetry(rnchr-master): backoff failure, will retry, err=compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2018-10-01' is invalid. The supported versions are '2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
I0522 14:16:43.968792    6751 azure_standard.go:584] GetPrimaryInterface(rnchr-master, ) abort backoff
E0522 14:16:43.968798    6751 azure_backoff.go:111] GetIPForMachineWithRetry(rnchr-master): backoff failure, will retry,err=compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2018-10-01' is invalid. The supported versions are '2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
I0522 14:16:43.968840    6751 azure_instances.go:53] NodeAddresses(rnchr-master) abort backoff: timed out waiting for the condition
I0522 14:16:43.968861    6751 cloud_request_manager.go:113] Node addresses from cloud provider for node "rnchr-master" not collected
E0522 14:16:44.041474    6751 kubelet.go:2266] node "rnchr-master" not found
F0522 14:16:44.054192    6751 kubelet.go:1379] Kubelet failed to get node info: failed to get instance ID from cloud provider: compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2018-10-01' is invalid. The supported versions are '2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
+ echo kubelet --cni-conf-dir=/etc/cni/net.d --cluster-domain=cluster.local --root-dir=/opt/rke/var/lib/kubelet --event-qps=0 --v=2 --cluster-dns=10.43.0.10 --resolv-conf=/etc/resolv.conf --streaming-connection-idle-timeout=30m --authentication-token-webhook=true --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --hostname-override=rnchr-master --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --volume-plugin-dir=/var/lib/kubelet/volumeplugins --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --fail-swap-on=false --pod-infra-container-image=rancher/pause:3.1 --read-only-port=0 --make-iptables-util-chains=true --network-plugin=cni --address=0.0.0.0 --anonymous-auth=false --enforce-node-allocatable= --register-with-taints=node-role.kubernetes.io/controlplane=true:NoSchedule --cloud-config=/etc/kubernetes/cloud-config --allow-privileged=true --cgroups-per-qos=True --cni-bin-dir=/opt/cni/bin --cloud-provider=azure

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by davidnuzik** [comment]
**QA Reproduction:**
Version: master-head (6/24/19)

We were able to see that when we supply azure cloud information the subscription id is essentially ignored.

- Create an RKE Azure nodeTemplate with correct credentials (Subscription ID, Client/app ID, secret); just make it a simple cluster, say 1 node with all 3 roles
- Fill out Azure cloud fields, but put in a fake subscription ID
- SSH into cluster node. Review kubelet logs and kube-controller-manager logs. grep for our fake subscription ID that we entered
- The fake subscription id is not found, instead we find another subscription id that we did not specify.

We expected provisioning the cluster to fail since we provided a false/fake subscription id in the azure cloud subscriptionid field. Instead, the cluster worked and came up for us (because in this case it used a subscriptionid that was set up and able to create the azure resources). In our case we had difficulty setting up a subscriptionid such that it would fail to provision -- but the point is that we have effectively reproduced because we saw when we inspect kubelet and kube-controller-manager logs that our fake subscription id was not used.

Here is an example:
```
root@david-invalidcloud1:/home/docker-user# cat temp2 | grep "8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6"
+ local az_subscription_id=8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6
+ '[' -z 8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6 ']'
+ jq '.subscriptionId="8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6"'
root@david-invalidcloud1:/home/docker-user# cat temp2 | grep "7070bfdf-3a92-47fe-bec5-2f3ae43d2bf6"
```

First command greps for incorrect subscription id (we did not supply this) Second command greps for what we actually entered in the UI when we plugged in subscriptionid for azure cloud field.

**Comment by davidnuzik** [comment]
This change causes failures bringing up a cluster even with correct cloud info provided (all four required fields).
Something's not quite right with the PR I think.

[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [40.78.127.185]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused, log: + az login --service-principal -u REDACTED -p REDACTED --tenant REDACTED]

**Comment by kinarashah** [comment]
Test steps, 
1) Created a cluster with correct subscriptionID, cluster got created successfully and became active.
2) Created cluster with incorrect subscriptionID (but correct subscriptionID in node template) - cluster still gets created successfully and becomes active. But the cloud provider specific features won't work. This can be seen by checking `kube-controller-manager` logs, 

```
E0627 02:04:40.042715       1 service_controller.go:219] error processing service kube-system/metrics-server (will retry): error getting LB for service kube-system/metrics-server: network.LoadBalancersClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'zzzzzz-14a619f7-a887-4635-8647-d8f46f92eaac' could not be found."
``` 
Also, confirmed the incorrect subscriptionID was passed by checking `kube-controller-manager` logs, 
```
local az_subscription_id=zzzz-14a619f7-a887-4635-8647-d8f46f92eaac
``` 

Note:
If you see any unclear error msgs in UI while provisioning clusters, like 
```
[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [40.78.127.185]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused, log: + az login --service-principal -u REDACTED -p REDACTED --tenant REDACTED]
``` 
we should first check `kube-controller-manger` logs, for this msg: 
```
'Some variables were not populated correctly, using the passed config!'
``` 
most likely, one of the required values is missing and needs to be accounted for. (Which happened for this bug, when the location wasn't passed.)

**Comment by davidnuzik** [comment]
**Validation:**
master-head (7/3/19)

Scenario 1:
- Created Azure cluster with correct Azure cloud credentials. Cluster comes up successfully. I can create an azure storage class and bind a disk (utilize Azure Cloud)
-  Review kube-controller-logs
- Ensured subscriptionid is correct, ensured no messages like 
```
E0703 19:23:42.053461       1 azure_backoff.go:252] LoadBalancerClient.List(david-forreal) - backoff: failure, will retry,err=network.LoadBalancersClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '7070bfdf-3a92-47fe-bec5-2f3ae43d2bf6' could not be found."
```

Scenario 2:
- Created Azure cluster with incorrect Azure cloud credentials. In my case I changed the subscriptionid first character to be a 7 instead of '8' which is what it should be in my case. This is an invalid subscription id we have supplied.
- Cluster comes up successfully (expected because Azure nodeTemplate is correct so node can come up). But, tried to leverage Azure cloud feature by creating Azure storage class and when try to bind a volume this does not work, as expected, since subscription id is wrong.
- Confirmed when searching  kube-controller-manager logs for SubscriptionNotFound we see:
```
E0703 19:23:42.053461       1 azure_backoff.go:252] LoadBalancerClient.List(david-forreal) - backoff: failure, will retry,err=network.LoadBalancersClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '7070bfdf-3a92-47fe-bec5-2f3ae43d2bf6' could not be found."
```
- Confirmed incorrect  subscriptionid was indeed passed also in the same logs:
```
docker-user@david-azure:~$ cat kcmlogs.txt | grep 7REDACTED
+ local az_subscription_id=7REDACTED
+ '[' -z 7REDACTED ']'
+ jq '.subscriptionId="7REDACTED"'
```

**Comment by davidnuzik** [comment]
In my case I did not get errors in the UI so did not find:
`'Some variables were not populated correctly, using the passed config!'` in logs.
