### ISSUE TITLE
Set Ingress capability on RKE clusters based on IngressConfig

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#20639]
Cluster capabilities controller sets RKE capabilities to nginx ingress by default. It should refer the IngressConfig on rke config instead.

**Comment by sangeethah** [comment]
Tested with latest build from master - `7c52b9e35`

Create a RKE cluster by setting  ingress provider as "haproxy" (by using Edit as yaml option in UI).
When cluster gets created , capabilities reflects the correct provider as expected

```
"ingressCapabilities": [
{
"ingressProvider": "haproxy",
"type": "/v3/schemas/ingressCapabilities"
}
],
```

When cluster gets created with nginx as ingress provider , capabilities reflects the correct provider as expected.

```
"ingressCapabilities": [
{
"customDefaultBackend": false,
"ingressProvider": "nginx",
"type": "/v3/schemas/ingressCapabilities"
}
```


```
"ingressCapabilities": [
{
"ingressProvider": "haproxy",
"type": "/v3/schemas/ingressCapabilities"
}
],
```
