### ISSUE TITLE
Support hiding app versions based off rancher version

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#20642]
Hide app versions based off the rancher version if they are not supported.

TemplateVersions are getting two new fields: `rancherMinVersion` and `rancherMaxVersion` for this purpose.

**Comment by dramich** [comment]
Backend: https://github.com/rancher/rancher/issues/18469

**Comment by cjellick** [comment]
note @westlywright  - we will need to backport this to 2.2 release

**Comment by deniseschannon** [comment]
@davidnuzik can you confirm this is working? it is related to rancher min/max version within the catalog.

**Comment by sowmyav27** [comment]
Verified it on rancher:master
**Precondition:**
```
rancher version: rancher:v2.3.2(custom image for testing) - r1
rancher version: rancher:v2.3.3(custom image for testing) - r2
rancher version: rancher:v2.3.4(custom image for testing) - r3
chart - fluentd-aggregator
chart version: latest - rancher_min_version: 2.3.2 and rancher_max_version: 2.4.0 - v3
chart version: v0.1.0 - rancher_max_version: 2.3.2 - v1
chart version: v0.2.1 - rancher_min_version: 2.3.3 - v2
```

**The basic test scenario:**
Verified when you deploy the custom app in the project

In rancher:r1 - v1 is available and v2 and v3 are NOT available
In rancher:r2 - v2 and v3 are available and v1 is NOT available
In rancher:r3 - v2 and v3 are available and v1 is NOT available

Template versions are hidden/available based on the rancher min/max value set up.
