### ISSUE TITLE
Global Registry Notary cpu and memory reservation doesn't work

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20645]
rancher/rancher:master

Steps:

1. Change the cpu reservation of Notary to 450m
2. Enable Global Registry 
3. Check the reservation on Notary workload

Results:

It's not 450m which I configured

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/7/19)

This was actually already validated in the UI Test Plan recently. I carefully confirmed that for each and every field in the Global Registry config (all cpu/memory reservation/limit options) are working correctly.

This test was done via:
- Set default settings, Enable Global Registry, ensure these all take effect in all areas (all workloads/containers).
- Disable, and now set unique settings, Enable Global Registry, ensure these all take effect in all areas (all workloads/containers).
- EDIT, and set new unique settings, Save, ensure these all take effect in all areas (all workloads/containers).

Notary settings for cpu limit/reservation now work.
