### ISSUE TITLE
json error when validating Fluentd logging endpoint settings

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20640]
Possibly related: rancher/rancher#20120 

Version: v2.2.4-rc22

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Set up Fluentd cluster logging config
- Change the Weight from 100 to 30. Then change it back to 100 again (no need to save we just need to change this number temporarily before we try to test)
- Click on the "Test" button

**Result:**
HTTP 500
`json: cannot unmarshal string into Go struct field FluentServer.weight of type int`

the test action fails /v3/clusterloggings?action=test with this message.

**Other details that may be helpful:**
HA setup but issue should happen regardless of environment

**Comment by davidnuzik** [comment]
This _probably_ shouldn't block v2.2.4 release; the issue only happens if you mess with the weight number and for testing only. I was able to Save and set up logging without any issues.

**Comment by guangbochen** [comment]
This should be fixed in the front-end, the backend expects the weight to be int only but for `TEST` action a string value is passed.

**Test Action**
![image](https://user-images.githubusercontent.com/4569037/61855753-41754080-aef3-11e9-88a8-bb570bf39914.png)

**Save Action**
![image](https://user-images.githubusercontent.com/4569037/61856214-4be40a00-aef4-11e9-8fd0-4b6f84330450.png)

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

Test again:
- Set up Fluentd cluster logging config
- Change the Weight from 100 to 30. Then change it back to 100 again (no need to save we just need to change this number temporarily before we try to test)
- Click on the "Test" button

Now when we click on "Test" we do not get the 500 error. The Test succeeds.

Confirmed the weight is an int now (UI sends int instead of string now)
![image](https://user-images.githubusercontent.com/45179589/62566524-01d91d80-b83e-11e9-8865-9498531ff075.png)
