### ISSUE TITLE
Project Owner and Member can see Istio stuff even istio is not enabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20644]
rancher/rancher:master

Steps:

1. Create a cluster
2. **DO NOT** enable istio
3. Login as project member
3. Go to project level

Results:

Project member still can see traffic graph and traffic metrics tabs

Expected:

It should say istio is not enabled yet. Please contact your cluster admin.

**Comment by sangeethah** [comment]
Tested with latest build from master - Jun 7 `fed523b3`
1. Create a cluster
2. DO NOT enable istio
3. Create a project - p1   and user1 as project member.
4. Log in as user1 and Go to project- p1 and access  "Service Mesh".

User is presented with the following message as expected:
"Cluster Service Mesh is not enabled yet. Please contact your cluster administrator."
