### ISSUE TITLE
Creating EKS Cluster - ValidationError: Parameter NodeInstanceType failed to satisfy constraint: Must be a valid EC2 instance type status code: 400

### ISSUE THREAD

**Issue by chorsnell** [rancher/rancher#20652]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- create cluster
- select AWS EKS
- select eu-west-1 + enter keys
- default cluster options
- default vpc + subnet
- nodes, change instance type to `t2.micro`

**Result:**
Cloudformation creates the VPC, and Service role, but then errors on:
```
Error creating stack: error creating master: ValidationError: Parameter NodeInstanceType failed to satisfy constraint: Must be a valid EC2 instance type status code: 400, request id: 301657f4-86af-11e9-abbc-dd205bb5ed66
```

**Other details that may be helpful:**
using `t2.small` worked ok

**Environment information**
- Rancher version 2.2.3 / `rancher/rancher` - 1d6627a9e2de32f6e6f1a58723b36cfdcb7293ee82fab70b8b3b756b91a0a25a
- Installation option - single install via docker

**Cluster information**
- Cluster type: AWS EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): t2.micro
- Kubernetes version (use `kubectl version`): 1.12

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.1
 Git commit:        e68fc7a
 Built:             Fri Jan 25 14:33:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by karaktaka** [comment]
Is there any plan on fixing this?
It does also happen on Rancher 2.2.8 with EKS 1.13 with Instance Type c5d.xlarge
