### ISSUE TITLE
Cloning a service with a specific host results in Error

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2065]
If you have a service that was deployed to a specific host, and clone it you will get a `Validation failed in API: requestedHostId` error. This is happening on latest UI.

You have to go to the scheduling tab in the service, select a different host, then select the host you really want.

**Comment by sonicsnes** [comment]
Not only this, but the host which is selected by default is not the proper host from the cloned service.

**Comment by djskinner** [comment]
Just came across this in 0.44. Thanks for the tip about how to work around it.

**Comment by jmreicha** [comment]
+1

Just ran in to this on v0.47.0-rc1

**Comment by vincent99** [comment]
This is because of #594, the ID that comes back from GETting the service isn't a valid hostId
