### ISSUE TITLE
how to use the command “calicoctl” in the rancher k8s cluster？

### ISSUE THREAD

**Issue by bobo200128** [rancher/rancher#20650]
I have created a cluster with calico。
I want use the commond “calicoctl” to see the the network at my cluster。
How can I set the env？
 

[root@Centos7 ~]# calicoctl get ipPool           
Failed to get resources: client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

**Comment by leodotcloud** [comment]
The Calico DaemonSet doesn't use it's own etcd backend, but runs on top of the K8S API server. Looking at the instructions below, one can install a calicoctl Pod.
https://docs.projectcalico.org/v3.5/usage/calicoctl/install

kubectl apply -f \
 https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calicoctl.yaml

If you inspect the manifest file, you can see a service account being created for use with calicoctl Pod (along with the necessary ClusterRole and ClusterRoleBinding).

After the Pod is installed, one can exec inside this Pod and run various commands. Example: `calicoctl get nodes` to verify.
