### ISSUE TITLE
Cannot repair catalog app with bad value once bad value is saved

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#20655]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** 
1. Deploy Wordpress (or really, any) catalog app, and set a strange value (i.e. an annotation as the value).
2. Attempt to "upgrade" the chart and change that strange value you provided.
3. Observe that it is not possible to upgrade the chart.

**Result:**
The chart now becomes un-upgradeable and you cannot repair the wrong value without manually editing the catalog CRD.

**Other details that may be helpful:**
N/A 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): doesn't matter

A good example of this is to deploy the wordpress catalog app from stable and (among other variables) set 

![image](https://user-images.githubusercontent.com/30601846/58889804-575a4800-869e-11e9-970d-c6c3eb95edb1.png)

You'll get the following result:

![image](https://user-images.githubusercontent.com/30601846/58889722-3abe1000-869e-11e9-8686-0b48c8cca6f1.png)

When you try to upgrade that value out of existence, it will fail.

**Comment by guangbochen** [comment]
This more seems to be a UI bug, test with Rancher `v2.2.2` and you can `upgrade` app successfully through the Rancher API.
![image](https://user-images.githubusercontent.com/4569037/59251286-1349e300-8c5c-11e9-8d26-5d430e39833e.png)

**Comment by davidnuzik** [comment]
This was reproduced and validated in latest v2.2 in https://github.com/rancher/rancher/issues/21027
As such, I do not show reproduction steps here again in this issue.

**Validation:**
Version: master-head (v2.3) (6/21/19)
I followed the steps to reproduce, now when you upgrade the app you can fix this (remove the answer that states the ingress annotation) and when you upgrade, the app will now be fixed essentially and becomes active.

There are no UI console errors and the HTTP and catalog app answers appear correct now.
Reference https://github.com/rancher/rancher/issues/21027#issuecomment-504549085 for testing details.
