### ISSUE TITLE
Failed to connect to proxy" error="websocket: bad handshake when adding new node to cluster

### ISSUE THREAD

**Issue by dhirajdebut** [rancher/rancher#20651]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug 

**Steps to reproduce (least amount of steps as possible):**
Select a cluster from existing cluster
edit cluster 
add node details and copy the worker commnad
got to vm and paste the worker command

**Result:**
time="2019-06-04T09:35:48Z" level=info msg="Connecting to proxy" url="wss://PUBLIC_IP/v3/connect"
time="2019-06-04T09:35:49Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-06-04T09:35:49Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

**Other details that may be helpful:**
When i am adding the new node to existing cluster then it is giving this error. It stucks.

 **This issue happens when the cluster and node are running on different cloud providers. But if my cluster and cloud provider is same then it works fine.**

We run below commond on worker node 

`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.1.6 --server https://PUBLIC_IP --token 9wdfgr66fghgfhghfghfh45648w --ca-checksum a0dfgfgrty65757g4a452353a2328531690 --worker`

--

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.16
- Installation option (single install/HA):docker

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by dhirajdebut** [comment]
```
*   Trying PUBLIC_IP...
* Connected to PUBLIC_IP (PUBLIC_IP) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: cattle (does not match 'PUBLIC_IP')
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: O=the-ranch,CN=cattle
* 	 start date: Thu, 14 Mar 2019 04:30:36 GMT
* 	 expire date: Tue, 12 May 2020 09:11:07 GMT
* 	 issuer: O=the-ranch,CN=cattle-ca
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> HEAD /v3/connect HTTP/1.1
> Host: PUBLIC_IP
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Wed, 05 Jun 2019 06:43:58 GMT
Date: Wed, 05 Jun 2019 06:43:58 GMT
< Content-Length: 21
Content-Length: 21
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8

< 
* Connection #0 to host PUBLIC_IP left intact
```

I get above result when i am connecting with curl

**Comment by pankajcheema** [comment]
Rancher is not able to add a node from different cloud provider into a running cluster on different cloud provider . My cluster with 1 master and 1 worker running on google cloud . When trying to add a node (AWS) to this cluster . its saying 

Waiting to register with Kubernetes
--

**Comment by Perfect-Web** [comment]
i have the same issue, im trying to add nodes from another aws account into a k8s cluster that already works, but i get 
```
time="2019-07-15T12:58:53Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
```

**Comment by cesarandreslopez** [comment]
Same issue here, with a bare-metal 3 months old cluster, trying to add a new node will give the above message.

**Comment by cesarandreslopez** [comment]
A bit more information. When I create a new cluster and add nodes everything works fine. The issue is on adding a new node on an existing cluster, in my case with all nodes bare-metal.

**Comment by pib** [comment]
I had the same problem and finally figured it out. I noticed in the clusters view that the cluster was listed as "Custom" instead of "Imported" and so I went to "View in API" for the cluster and saw that there was a value in `rancherKubernetesEngineConfig` of:
```json
{"addonJobTimeout":30,"authentication":{"strategy":"x509","type":"/v3/schemas/authnConfig"},"authorization":{"type":"/v3/schemas/authzConfig"},"bastionHost":{"sshAgentAuth":false,"type":"/v3/schemas/bastionHost"},"cloudProvider":{"type":"/v3/schemas/cloudProvider"},"ignoreDockerVersion":false,"ingress":{"provider":"nginx","type":"/v3/schemas/ingressConfig"},"kubernetesVersion":"v1.13.5-rancher1-2","monitoring":{"provider":"metrics-server","type":"/v3/schemas/monitoringConfig"},"network":{"plugin":"canal","type":"/v3/schemas/networkConfig"},"restore":{"restore":false,"type":"/v3/schemas/restoreConfig"},"services":{"etcd":{"creation":"12h","extraArgs":{"election-timeout":"5000","heartbeat-interval":"500"},"retention":"72h","snapshot":false,"type":"/v3/schemas/etcdService"},"kubeApi":{"alwaysPullImages":false,"podSecurityPolicy":false,"serviceNodePortRange":"30000-32767","type":"/v3/schemas/kubeAPIService"},"kubeController":{"type":"/v3/schemas/kubeControllerService"},"kubelet":{"failSwapOn":false,"type":"/v3/schemas/kubeletService"},"kubeproxy":{"type":"/v3/schemas/kubeproxyService"},"scheduler":{"type":"/v3/schemas/schedulerService"},"type":"/v3/schemas/rkeConfigServices"},"sshAgentAuth":false,"type":"/v3/schemas/rancherKubernetesEngineConfig"}
```

I'm not sure if the specific value was the issue, but just clearing it all out and saving fixed the issue. The node agents which were failing before instantly were able to connect and the cluster went back to being "imported" like it is supposed to be. I think the issue was perhaps initially caused by one of the earlier versions of the rancher2 terraform provider.

I don't know if this is the exact same issue that everyone is having, but hopefully it helps some of the folks running into the same thing.

**Comment by papanito** [comment]
I had the same problem and I followed the [cleaning cluster nodes guide](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/) and then re-added the cluster node
