### ISSUE TITLE
Global Registry - Storage Backend field should not be editable when global registry is already enabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20658]
Seen on `rancher:master`
**What kind of request is this:** Bug

**Steps to reproduce:**

1. On a HA setup - rancher:master, with cloud provider set, add a storage class - say localstorage under local cluster. 
2. Enable Global Registry with Storage backend for registry - S3; Database - internal - Storage Class: localstorage; and Redis - internal Storage Class: localstorage.
3. Click on Save. 
4. Global Registry related workloads should get deployed under System project in local cluster.
5. Go back to Global Registry page, and change Storage backend for registry to filesystem - Storage Class: localstorage.
6. Click on save.
7. On the Global Registry UI - message - "Installing registry into the system project of the local cluster..." is shown. And Harbor UI is not accessible from here anymore.

**Expected Result:** 
Changes made should be reflected and System project under local cluster, should be updated.

**Actual Result:** 
Harbor UI is not accessible anymore.
Message . - "Installing registry into the system project of the local cluster..."  is seen on Global Registry UI. No changes/updating of workloads seen under System project in local cluster.
![Screen Shot 2019-06-04 at 10.47.20 AM.png](https://zube.io/files/rancher/aa48e8534053d1d9fe3bb13ed0cef0fd-screen-shot-2019-06-04-at-10-47-20-am.png)

**Note:**
Storage Backend field should not be editable when global registry is already enabled.
User should not be allowed to change Database Config Type and Redis Config Type from internal to external or vice versa when global registry is already enabled.

**Comment by gitlawr** [comment]
Disable fields that may break registry. For data migration, users can disable first, then enable with updated options anyway.
Editable options are resources, node selectors, and enabling/disabling optional components.

**Comment by sowmyav27** [comment]
Verified on `rancher:master` (06/05/2019)
Fields : Storage Backend Type, Config Database Type and Config Redis Type are not editable after Global Registry has been enabled.
Other fields like resources, node selectors, and enabling/disabling optional components are editable after Global Registry has been enabled.
