### ISSUE TITLE
rancher1.6 cannot see live container metrics

### ISSUE THREAD

**Issue by 1978gzp** [rancher/rancher#20663]
![image](https://user-images.githubusercontent.com/51391292/58925856-a924d000-877b-11e9-9d64-a8582e688be8.png)

**Comment by zhu1531** [comment]
你发错了地方，这个库是2.0的

**Comment by 1978gzp** [comment]
能给个rancher1.6提交问题的url吗

**Comment by loganhz** [comment]
It looks like it's a websocket issue. Maybe your proxy doesn't support ws?

**Comment by benoist** [comment]
I have the same issue, I've connected directly to the IP address so no proxy in between..
The websocket stays pending.
I'm on rancher 1.6.28

**Comment by benoist** [comment]
I just checked in Firefox and that was working. I checked in Chrome incognito and that worked as well, I  cleared all cookies and that fixed this the issue.
