### ISSUE TITLE
Add a label to allow specifying an container IP within Rancher managed network

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2066]
Allow users to specify a label for a service or container that will allow the user to manage their own IP assignment within Rancher's 10.42.x.x./16 network.

Use label io.rancher.container.requested_ip=10.42.0.1 (for example) to assign the IP.  If the IP is already in use, Rancher will randomly pick an IP from the 10.42.0.0/16 address space.

**Comment by aruneli** [comment]
```
Component 	Version
Rancher 	v0.40.0-rc1
Cattle 	v0.96.0
User Interface 	v0.53.0
Rancher Compose 	beta/latest
```
Verified for container and service of 1 and more containers.
