### ISSUE TITLE
Global Registry - Upgrading workload fails when Backend Storage is PV

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20664]
Seen on `rancher:master`
**What kind of request is this:** Bug

**Steps to reproduce:**

1. Login to rancher (HA setup, Global Registry is enabled) as admin. 
2. Global Registry is enabled already with Amazon S3 and Database/Redis - PV internal
3. Navigate to Global --> Tools --> Global registry
4. Disable Clair/Notary.
5. Workloads under Local cluster --> System project should upgrade. 

**Expected Result:**
All the workloads should upgrade and come to Active state

**Actual Result:**
Harbor Registry related workload is stuck in Unavailable State.
Error seen:
![Screen Shot 2019-06-04 at 11.24.12 AM.png](https://zube.io/files/rancher/4cdbe7a5afc6aa9847b06e14f662bed0-screen-shot-2019-06-04-at-11-24-12-am.png)

**Comment by gitlawr** [comment]
The volume is held by the former pod and is not detached.
Related to https://github.com/goharbor/harbor-helm/issues/224

**Comment by loganhz** [comment]
@gitlawr is there anything we can do? Or how can we workaround or fix it manually?

**Comment by gitlawr** [comment]
We need to fix it by updating the chart

**Comment by jiaqiluo** [comment]
I met the same issue when using the EBS storage class.

**Comment by jiaqiluo** [comment]
a workaround is to scale the workload to 0, wait all pods get deleted, then scale up back to the previous value.

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: mater using the updated system-chart:dev

We can re-enable the global registry by using the existing PVCs or EBS class, and the data is consistent.
