### ISSUE TITLE
Can't ssh into nodes (2.2.3)

### ISSUE THREAD

**Issue by aplex** [rancher/rancher#20674]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Provision a 2-node cluster on vSphere
Try to ssh into the worker or master nodes, using the keys downloaded from the ui, or using "rancher ssh node-name", "rancher ssh rancher@node-name", "rancher ssh root@node-name"

**Result:**

ssh authentication fails and prompts for a password

**Other details that may be helpful:**

I tried to create a couple of clusters, but none of them could be ssh'd into. Generally, cluster seems to work, and there are bunch of services running on top of it, e.g. monitoring can be enabled.

**Environment information**
- Rancher 2.2.3

**Cluster information**
- Cluster type: vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):  1.13.5

**Comment by superseb** [comment]
Has this regressed from a previous version? Can you try `ssh -i KEY docker@IP` manually or `rancher ssh docker@node-name`?

**Comment by superseb** [comment]
Let me know if this needs help
