### ISSUE TITLE
"Monitoring API is not ready" on v2.2.3

### ISSUE THREAD

**Issue by lianlianhe** [rancher/rancher#20670]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
"Enabled" Monitoring for cluster

**Result:**
In "App" ,there are no expected deployment ,leak "monitoring operator".
At namespace "cattle-prometheus" leak prometheus-cluster-monitoring and prometheus-operator-monitoring-operator pod.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher single env with 2.2.3

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
# docker version
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
![App](https://user-images.githubusercontent.com/28640060/58939786-8958d080-87aa-11e9-9397-2c455f1075ca.png)
![namespace](https://user-images.githubusercontent.com/28640060/58939800-8d84ee00-87aa-11e9-9fca-3cf307ee7c25.png)


```

**Comment by lianlianhe** [comment]
upgrade rancher to 2.2.4 the issue persist.

**Comment by huegelc** [comment]
Possible related to https://github.com/rancher/rancher/issues/19688

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
