### ISSUE TITLE
Backport:Increase elasticsearch log precision

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20675]
https://github.com/rancher/rancher/issues/20405

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/pull/20676

**Comment by kinolaev** [comment]
Hello @loganhz! Already 7th release candidate released but without this fix. Will it be backported in 2.2.5?

**Comment by kinolaev** [comment]
Hello @alena1108 and @bmdepesa! Hope to see this PR backported to 2.2.6, maybe some of you want make it happen?)

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2-head 81b4458b

* Created cluster
* Enabled cluster logging
* Log statements show nanoseconds:
  * `"@timestamp":"2019-07-25T16:16:51.787937436+00:00"`
