### ISSUE TITLE
Admin Password and Encryption Key fields are not available on the Rancher Global Registry UI once it has been enabled.

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20687]
Seen on rancher:master (06/05/2019)
**What kind of request is this:** Bug

**Steps to Reproduce:**
Enable Global Registry on Rancher UI by providing in the details

**Expected Result:**
On enabling the Global Registry, admin should be able to see The Admin Password and Encryption Key For Harbor fields which can be editable, but the **contents** should not be visible.

**Actual Result:**
Global Admin, on enabling Global registry, cannot see The Admin Password and Encryption Key For Harbor fields anymore on the UI.
![Screen Shot 2019-06-05 at 3.30.47 PM.png](https://zube.io/files/rancher/eb4a4fda49c9bacc8674568436c719ed-screen-shot-2019-06-05-at-3-30-47-pm.png)

**Comment by loganhz** [comment]
@sowmyav27 For Admin Password, even if you change it after enabled registry. It will not take effect.

@gitlawr Can you confirm if Encryption Key fields will not take effect either? Or it is editable?

**Comment by sangeethah** [comment]
@loganhz  If admin user decides to change the password on harbor side, will the existing Global registry app have any kind of problem since it still has only the older password? Does it use this admin user creds for connecting to harbor or it was used only for creating the admin user first time we enabled global registry?

**Comment by loganhz** [comment]
@sangeethah  it was used only for creating the admin user first time we enabled global registry

**Comment by loganhz** [comment]
After that if users want to change the admin password . Users need to do it in Harbor UI

**Comment by sangeethah** [comment]
Thanks for the confirmation @loganhz .
@sowmyav27 Can you change the admin password on the harbor UI side and make sure global registry feature continues to work? Also try doing some other updates to the  global registry app and see that it is able to apply them successfully.

**Comment by loganhz** [comment]
Confirmed with @gitlawr 
Encryption key is editable.

**Comment by sowmyav27** [comment]
verified on rancher:master - latest - (07/07/2019)
**Before enabling Global Registry on Rancher**
1. Admin Password and Encryption Key for Harbor input fields are made as options for admin user to enter values.
2. Provide values to enable the Global Registry.
3. Click on Enable. 
4. The page changes to where Encryption Key is visible
<img width="1462" alt="Screen Shot 2019-06-07 at 1 02 52 PM" src="https://user-images.githubusercontent.com/26032343/59132582-753bdd00-892a-11e9-9894-5928a9f8a2bf.png">
5. After the Global Registry is enabled, and you have not moved from the page from step , you can see the page with the encryption key still visible
<img width="976" alt="Screen Shot 2019-06-07 at 1 33 52 PM" src="https://user-images.githubusercontent.com/26032343/59132676-ab795c80-892a-11e9-8848-febce4ae1862.png">
6. Once you hard refresh the page, the Encryption Key is not visible anymore.
<img width="881" alt="Screen Shot 2019-06-07 at 1 31 06 PM" src="https://user-images.githubusercontent.com/26032343/59132713-c9df5800-892a-11e9-9851-fc502095d4b7.png">

Also verified the change password scenario for admin user on Harbor UI
1. As an admin User, go to Harbor UI. (admin should have an image pushed into a repo)
2. Change password.
3. Scale up an existing workload deployed with an image( step 1).
4. Scaling up fails.
5. Go to Registries page under the project level. 
6. Enter the new credentials for the admin user.
7. Workload will get deployed with image/Scaling up also works.

**Comment by loganhz** [comment]
If you are using auto generate password, you will always see the password until you leave this page.
This is by design for the generate password component.

The generate password component is used in many places. Not Global Registry only.

Could you file another issue and we can ask UX to decide if we should do something better than current design for the generate password component?

**Comment by loganhz** [comment]
Move it back to to-test. So QA can notice it

**Comment by sowmyav27** [comment]
As per @loganhz 's comments, closing this issue. Logging another issue to track the generate password issue related to global registry page.
