### ISSUE TITLE
Global Registry - S3 Region and S3 Region Endpoint are not marked mandatory fields

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20689]
Seen on rancher:master (06/05/2019)
**What kind of request is this:** Bug

**Steps to reproduce:**
1. Login to Rancher UI HA setup, Navigate to Global Registry page.
2. Select Storage Backend Type as S3.
3. Do not enter data in S3 Region and S3 Region Endpoint fields. 
4. Enter other details on the page.
5. Click on Enable.

**Actual Result:**
Error is seen on UI - 
![Screen Shot 2019-06-05 at 1.08.47 PM.png](https://zube.io/files/rancher/29cefeddf0ff85b3a8de2f2dd2a97e9c-screen-shot-2019-06-05-at-1-08-47-pm.png)

**Expected Result:**
S3 Region and S3 Region Endpoint should be marked mandatory.

**Comment by loganhz** [comment]
@gitlawr Can you confirm if S3 Region and S3 Region Endpoint are required fields?

**Comment by gitlawr** [comment]
S3 Region defaults to `us-east-1` if it is not specified, But I think making it required avoids confusions to the users.
The endpoint is optional. When a region is set the client maps the region-specific endpoint by default.
See: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html
![image](https://user-images.githubusercontent.com/5697937/59004340-e22c7580-884b-11e9-91ad-82761d88fab6.png)

**Comment by sowmyav27** [comment]
verified on `rancher:master` (06/07/2019)

1. S3 Region is marked mandatory
2. S3 Region Endpoint is not a mandatory field
