### ISSUE TITLE
Global Registry - cannot work properly with NFS as storage option

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20681]
Bug

Steps:
- set up an NFS server on a Digital Ocean droplet 
- run Rancher: master in HA mode
- in the local cluster, add three persistent volumes using that NFS, each PV mounts a different directory in the NFS server 
- in the System project, add three persistent volume claims using those three PVs under the namespace cattle-system 
- go to enable the Global Registry and use those PVCs as storage options

Results:
![screenshot.png](https://zube.io/files/rancher/01539929343d6f95623f3dea45ef605e-screenshot.png)

- the workload `global-registry-harbor-database` does not run up because the container `databse` is unhealthy
```
	Liveness probe failed: /docker-healthcheck.sh: line 4: hostname: command not found psql: could not connect to server: Connection refused Is the server running on host "127.0.0.1" and accepting TCP/IP connections on port 5432?
```

**Comment by loganhz** [comment]
@gitlawr managed to use NFS for Global registry. Maybe you could share you Rancher setup to him. So he can look at it. Thanks

**Comment by gitlawr** [comment]
Can you elaborate the setup for NFS, I've validated NFS working so it might be a configuration issue.

**FYI**, here are the test steps I used:
1. Set Up NFS Server
On a fresh Ubuntu 1804 node:
```
$ apt-get update
$ apt-get install nfs-kernel-server nfs-common -y
# use /files for the shared directory
$ mkdir /files
$ vi /etc/exports
# Add this line to the file
/files *(rw,no_root_squash,async)
$ exportfs -a
$ /etc/init.d/nfs-kernel-server restart
# create subdirectory to use later
$ mkdir /files/sub1 /files/sub2 /files/sub3
```
2. Install nfs-common on all local cluster nodes
```
$ apt-get update
$ apt-get install nfs-common -y
```
3. Create PVCs for global registry
Go to local cluster - storage - pv, Create 3 PVs
```
Name: pv1,pv2,pv3
Capacity: 10GiB
Volume Plugin: NFS Share
Path: /files/sub1,/files/sub2,/files/sub3
Server: <IP of the NFS server>
```
Save.
4. Create 3 PVCs in System project, `cattle-system` namespace
with arbitrary names
5. Enable Global Registry with the above three existing PVCs

Result:
Global Registry is enabled successfully.

**Comment by jiaqiluo** [comment]
The issue is still under investigation, and not fixed yet.

**Comment by gitlawr** [comment]
When the local cluster is in aws ap-southeast region,
1. It works if the NFS server is in the same region
2. This issue is reproduced if NFS server is in us-east region.
The above two NFS is the same regarding instance type, os and NFS setup.

**Comment by gitlawr** [comment]
When the issue occurs, the `initdb` command halts without any error message.
Logs:
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... 
```
Turning on the debug mode, it shows that the command halts in the middle of a transaction:
```
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
DEBUG:  start transaction
DEBUG:  inserting row
DEBUG:  inserting column 0 value "3926"
DEBUG:  inserted -> 3926
DEBUG:  inserting column 1 value "20"
DEBUG:  inserted -> 20
DEBUG:  inserting column 2 value "0"
DEBUG:  inserted -> 0
DEBUG:  inserting column 3 value "3124"
DEBUG:  inserted -> 3124
DEBUG:  inserting column 4 value "int8range_canonical"
DEBUG:  inserted -> int8range_canonical
DEBUG:  inserting column 5 value "int8range_subdiff"
DEBUG:  inserted -> int8range_subdiff
DEBUG:  inserting row oid 0, 6 columns
DEBUG:  row inserted
DEBUG:  CommitTransaction
DEBUG:  name: unnamed; blockState:       STARTED; state: INPROGR, xid/subid/cid: 1/1/0 (used), nestlvl: 1, children:
DEBUG:  commit transaction
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
DEBUG:  start transaction
DEBUG:  close relation pg_range
DEBUG:  CommitTransaction
DEBUG:  name: unnamed; blockState:       STARTED; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
DEBUG:  commit transaction
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
DEBUG:  start transaction
DEBUG:  creating relation pg_transform 3576
DEBUG:  column trftype oid
DEBUG:  column trflang oid
DEBUG:  column trffromsql regproc
DEBUG:  column trftosql regproc
DEBUG:  CommitTransaction
DEBUG:  name: unnamed; blockState:       STARTED; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
DEBUG:  commit transaction
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
DEBUG:  start transaction
# Halt
```

**Comment by loganhz** [comment]
https://dev.mysql.com/doc/refman/8.0/en/disk-issues.html#disk-issues-nfs
https://www.postgresql.org/docs/9.1/creating-cluster.html#CREATING-CLUSTER-NFS

It looks like NFS is not a good option for RBD

**Comment by deniseschannon** [comment]
Due to the NFS issues related for the postgres component of Global Registry, we will not recommend using NFS as a storage option for Global Registry. 

We should discuss for GA of other storage options that do not require cloud providers.
