### ISSUE TITLE
Helm Stable - Redis App - persistence.enabled is set to false while deploying, but see error seen when launched

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20686]
Seen on `rancher:master` (06/05/2019)
**What kind of request is this:** Bug

**Steps to Reproduce:**
1. On rancher setup in HA, Enable Helm Stable Catalog.
2. Deploy redis app with following answers: #if no pv available, set: 
```
persistence.enabled=false
master.service.type=NodePort
password=testredis
```

**Expected Result:**
Redis app should have deployed successfully.

**Actual Result:**
Redis Master and Slave workloads fail to deploy with error `pod has unbound immediate PersistentVolumeClaims (repeated 3 times`

**Comment by gitlawr** [comment]
For the Redis chart, use the following values for ephemeral storage:
```
master.persistence.enabled=false
slave.persistence.enabled=false
```

**Comment by sowmyav27** [comment]
@gitlawr I am able to launch the redis app successfully with the above answers and values.
