### ISSUE TITLE
Global Registry - Admin Password can be renamed and the placeholder text is incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20688]
Seen on rancher:master (06/05/2019)
**What kind of request is this:** Bug

**Steps to reproduce:**
1. Login to Rancher UI HA setup, Navigate to Global Registry page.

`Initial Admin Password` - input field - can be renamed to `Admin Password`
Place holder text of this field should be `Harbor Admin password`
<img width="1481" alt="Screen Shot 2019-06-05 at 1 27 48 PM" src="https://user-images.githubusercontent.com/26032343/58995351-bb693300-87a8-11e9-9ed2-921da5dc2250.png">

**Comment by loganhz** [comment]
@sowmyav27 For Admin Password, even if you change it after enabled registry. It will not take effect.
So does it make sense to call it `Initial Admin Password`?

**Comment by sowmyav27** [comment]
@loganhz I think the field should be named `Admin password`. If it is `Initial Admin Password` it might give an incorrect meaning to the user, that he would have to change it somewhere after he has enabled the Global Registry with the `Initial Password`. @sangeethah please provide your comments.

**Comment by sangeethah** [comment]
I prefer `Admin password` over  `Initial Admin Password`.

**Comment by sowmyav27** [comment]
verified on `rancher:master` (06/07/2019)
Verified on a HA setup. 
Launch Rancher UI, navigate to Global --> Tools --> Global Registry
Below snapshot shows how the UI is now.
Admin password is now the field name. and the placeholder text is good.
<img width="1324" alt="Screen Shot 2019-06-07 at 11 39 56 AM" src="https://user-images.githubusercontent.com/26032343/59126187-4cf7b280-8919-11e9-80cd-7ae2b1b17adf.png">
