### ISSUE TITLE
Error is not displayed in UI when incorrect endpoint is provided for a cluster with S3 config and snapshot creation fails

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#20685]
Version: v2.2.4-rc23

Steps:
1. Create a cluster with S3 configuration for etcd bkp/restore, provide endpoint as " s3.us-east-2.amazon.com" instead of s3.us-east-2.amazonaws.com
2. Create a one time snapshot.

Snapshot is stuck in activating state with below error:
```
lastUpdateTime": "2019-06-05T21:08:39Z",
"message": "Failed to take one-time snapshot, exit code [1]: time=\"2019-06-05T21:08:39Z\" level=fatal msg=\"faield to set s3 server: failed to check s3 bucket:soumyap1test, err:Head https://s3.us-east-2.amazon.com/soumyap1test/: dial tcp: lookup s3.us-east-2.amazon.com on abcd: no such host\" \n",

```

There is no error presented in the UI. UI should display a relevant error.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `93019c54b`**

Steps:
Create a cluster with S3 configuration for etcd bkp/restore, provide endpoint as " s3.us-east-2.amazon.com" 
Create a one time snapshot.
Error in Rancher logs:
```
2019/08/20 16:20:54 [ERROR] EtcdBackupController c-997xj/c-997xj-rs-trfjs [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Failed to take one-time snapshot, exit code [1]: time="2019-08-20T16:20:52Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:<name>, err:Get https://s3.us-east-2.amazon.com/<bucket-name>/?location=: dial tcp: lookup s3.us-east-2.amazon.com on x.x.x.x:53: no such host" 
```
Error on Rancher UI:
<img width="1288" alt="Screen Shot 2019-08-20 at 9 23 27 AM" src="https://user-images.githubusercontent.com/26032343/63365463-8a6eb800-c32c-11e9-906a-94ca92c7fad4.png">
