### ISSUE TITLE
Global Registry - Failed to change the storage option

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20694]
Bug

Steps:
- run Rancher: master in HA mode 
- at the Local cluster, add a storage class `test-1` 
- enable the Global Registry using the storage class `test-1`
- notice the app is deployed successfully, and pv and pvc are created for it
- disable the Global Registry
- notice the app and its deployments are deleted, but the pv and pvc are kept
- add another  storage class `test-2`
-  reenable the Global Registry using the storage class `test-2`

Results:
- notice the app is deployed successfully but uses the old pv and pvc made from previous steps
- view the app in api, seeing that the storage class is set to `test-2` in the config 
```
"persistence.persistentVolumeClaim.database.storageClass": "test-2",
```

**Comment by gitlawr** [comment]
This is expected
1. PV/PVC is kept on disabling, users need to delete them manually if they want to clean up data.
2. When the registry is enabled the second time, PVCs with the same names exist so no new volumes are created for that.

**Comment by sangeethah** [comment]
@gitlawr ```When the registry is enabled the second time, PVCs with the same names exist so no new volumes are created for that.```
Even in this case where a different storage class being selected , will still not create new volumes ?

It is not obvious , that we will have the delete the existing PVS when disabling and enabling global registry to have a fresh start .
Ideally , we would expect the harbor registry to start fresh with no users/images from the previous instance when disabled and enabled. Should we have some kind of helper text that will communicate this to the user when disabling/ enabling  global registry ?

**Comment by gitlawr** [comment]
The PVC names created by the chart is fixed now because the release(app) name does not change.

Looks like we should create new volumes every time users do enabling with `Use a Storage Class to provision a new persistent volume` options.

Users can use previous data by choosing existing PVCs.

**Comment by deniseschannon** [comment]
We should minimally add a warning that PVs and PVCs need to be cleaned up when disabling global registry.

The PVs/PVCs story is something that needs to be discussed further

**Comment by deniseschannon** [comment]
Per @ibuildthecloud we should delete the PV/PVCs associated with global registry when disabling it with a big warning that all images for the registry will be removed. 

cc: @loganhz @sangeethah

**Comment by gitlawr** [comment]
@deniseschannon Should we delete them when users choose some existing PVCs to enable registry?
