### ISSUE TITLE
Project Owner / Member should also be able to see kiali, jaeger, grafana and prometheus UI

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20695]
rancher/rancher:master (June 5)

Steps:

1. Enable istio
2. Login as project member or owner
3. Go to service mesh page

Results:

Project Owner and Member cannot see Kiali, Jaeger, Grafana and Prometheus links.

**Comment by bmdepesa** [comment]
rancher/rancher:master fed523b3 6/7

* Create cluster
* Enable istio
* Add user2 as project owner, user3 as project member
* Login as user2
* View Service Mesh dashboard
* Links are accessible, traffic graph and metrics function.
* Login as user3
* View Service Mesh dashboard
* Links are accessible, traffic graph and metrics function.
