### ISSUE TITLE
Global Registry - Notary related resources are seen two times on the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20691]
Seen on rancher:master (06/05/2019)
**What kind of request is this:** Bug

**Steps to Reproduce:**
1. Login to Rancher UI - HA setup (Global Gistry is not yet enabled)
2. Navigate to Global Registry page.
3. Scroll to the bottom.

**Expected Result:**
Notary related resources should be seen only once on the UI 

**Actual Result:**
Notary related resources are seen two times on the UI 
![Screen Shot 2019-06-05 at 4.35.05 PM.png](https://zube.io/files/rancher/4990bb2db439ae3795ebab537a8e9688-screen-shot-2019-06-05-at-4-35-05-pm.png)

**Comment by sangeethah** [comment]
2 different set of parameters for Notary Server and Notary Signer,
