### ISSUE TITLE
HPA stuck in pending state when HPA is created with metrics type pod/object/external

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#20693]
Version: Master

Steps:
1. Create a deployment in a RKE cluster
2. Create a HPA pointing to a the deployment for the metrics type Pod/Object/External

The HPA is stuck in pending state with the below error in API
```
"the HPA was unable to compute the replica count: unable to get metric testpod: unable to fetch metrics from custom metrics API: no custom metrics API (custom.metrics.k8s.io) registered"

```

The custom metrics server associated with pod/object/external types is not available by default . 
Should these metrics types be disabled in UI ?

**Comment by loganhz** [comment]
It looks like there is no way to detect if users deployed the custom metrics server

**Comment by loganhz** [comment]
I think the error message in the HPA transition message helps?
I don't think we should disable it by default if we cannot detect custom metrics.

**Comment by loganhz** [comment]
`The HPA was unable to compute the replica count: unable to get metric sadf: unable to fetch metrics from custom metrics API: no custom metrics API (custom.metrics.k8s.io) registered`

@orangedeng is there a way we can check if custom metrics API (custom.metrics.k8s.io) registered or not?

If we can do that, we disable it in UI when it is not registered

**Comment by orangedeng** [comment]
Yes, but we need to introduce `apiservice.apiregistration.k8s.io` resource into Rancher API to do it.

**Comment by loganhz** [comment]
We will add a warning for preview release first. https://github.com/rancher/rancher/issues/20866
But we should remove it once we get this issue fixed

**Comment by loganhz** [comment]
For any cluster, check what version of HPA API is being used. List the version that's being used and that Rancher's requirements is v2beta2 (or whatever it is.

**Comment by loganhz** [comment]
Added the warning for HPA created with metrics type pod/object/external.

**Comment by soumyalj** [comment]
Tested with master-head build from Aug 1st. 
Create a deployment in a RKE cluster
Create a HPA pointing to a the deployment for the metrics type Pod/Object/External
During the HPA creation, there is a warning :

<img width="1283" alt="Screen Shot 2019-08-01 at 6 12 43 PM" src="https://user-images.githubusercontent.com/18536626/62294265-2d4bb900-b488-11e9-9d70-1ca798fef0bf.png">

<img width="1249" alt="Screen Shot 2019-08-01 at 6 14 44 PM" src="https://user-images.githubusercontent.com/18536626/62294331-50766880-b488-11e9-8547-90f8fe552c37.png">

<img width="1238" alt="Screen Shot 2019-08-01 at 6 14 59 PM" src="https://user-images.githubusercontent.com/18536626/62294354-5ec48480-b488-11e9-9eb4-6457d8b63fb4.png">
