### ISSUE TITLE
API sometimes hangs instead of loading on first load

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#207]
Server Version: v0.11.1

Steps to Reproduce:
Configure Access Control on your Rancher instance.
Create a new window and try to open the API. You should be prompted for an API key.
Go back to the Rancher instance window to generate the API key.
Input the username/password into the already opened window that has the prompt. 
Click Log In.

After I click Log In, the webpage remains blank. But if I refresh the page, the API shows up.

From a user perspective, it appears that the username/password doesn't work initially.

**Comment by vincent99** [comment]
This and #341 are a symptom of a problem with both Basic auth + token auth getting sent in the connection to the subscribe websocket and causing no resource.change events to get sent to update the UI as things are changed.  Fixed in this week's release/master.

**Comment by tfiduccia** [comment]
v0.14.2
Verified failed.

**Comment by vincent99** [comment]
I misread this as the problem being that the keys generated don't show up immediately..

**Comment by deniseschannon** [comment]
Verified that this is working now in v0.47.0.
