### ISSUE TITLE
Memory usage in UI seems confusing and/or wrong

### ISSUE THREAD

**Issue by rbq** [rancher/rancher#20703]
**What kind of request is this (question/bug/enhancement/feature request):**

A … question? Bug? You tell me. :)

**Steps to reproduce (least amount of steps as possible):**

1. Look at cluster's home page
2. Try to understand what's going on

**Result:**

Mostly confusion.

<img width="358" alt="WTF" src="https://user-images.githubusercontent.com/68766/59045522-86c8aa80-8880-11e9-808d-f712d3d5bc43.png">

So reserved and used memory are supposedly almost identical but still make up a completely different percentage of the total. This doesn't seem right. What am I missing?

**Other details that may be helpful:**

According to the cluster “metrics graph” below, set to “summary”, memory consumption is 4.5 %.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): standalone

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Bare metal/VMs, a bunch of totally different machines
- Kubernetes version (use `kubectl version`): 1.14.1
- Docker version (use `docker version`): 18.9.6

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/issues/23786
