### ISSUE TITLE
Update lb-controller image for cattle and k8s

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#20705]

**Comment by pasikarkkainen** [comment]
Related perhaps? https://github.com/rancher/rancher/issues/20427

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc1`

**Comment by soumyalj** [comment]
Tested with v1.6.29-rc2. 

Verified that in Cattle env,  Lb image has been updated to `rancher/lb-service-haproxy:v0.9.13`
![Screen Shot 2019-09-25 at 12 17 06 PM](https://user-images.githubusercontent.com/18536626/65632378-6dae4b80-df8e-11e9-9f9f-212468100eeb.png)



Verified that in Kubernetes environment, ingress controller image has been updated to v0.9.13
![Screen Shot 2019-09-25 at 12 14 11 PM](https://user-images.githubusercontent.com/18536626/65632237-0a241e00-df8e-11e9-906e-5bc9b13d8e3d.png)


Verified that the haproxy has been updated to version 2.0
```
root@288469e78662:/etc/haproxy# haproxy -v
HA-Proxy version 2.0.5-1ppa1~xenial 2019/08/16 - https://haproxy.org/

```
