### ISSUE TITLE
Translation missing "%monitoringPage.disable%"?

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#20700]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Update Rancher v2.2.3 -> v2.2.4

**Result:**
![Auswahl_030](https://user-images.githubusercontent.com/589662/59031378-cc2aaf00-8863-11e9-85ec-d4e1d71ddb2b.jpg)

**Other details that may be helpful:**
same happens with "$*%monitoringPage.enableActionLabel%*" on "Cluster Monitoring Configuration".

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): HA, 3 Node Cluster

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): BareMetal
- Kubernetes version (use `kubectl version`): 1.13.5

**Comment by davidnuzik** [comment]
@strowi you are running into an issue where the UI does not automatically refresh post-upgrade. In this case you do not have newer en-us translations. If you refresh the browser it should fix the issue or you may need to clear browser cache. Refer to https://github.com/rancher/rancher/issues/19586

We currently don't have a good way to determine when an upgrade has happened in the API and may try to fix this in a future release (TBD).

**Comment by davidnuzik** [comment]
Please re-open the issue if you still have issues after clear browser cache and refresh the web browser. We can investigate further if necessary.
