### ISSUE TITLE
'docker start rancher' error

### ISSUE THREAD

**Issue by isolution21321** [rancher/rancher#20701]
problem
I cann't use 【docker start rancher】 command to start Rancher.There are the logs:

s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise mysql: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise graphite_exporter: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise cattle: warning: unable to spawn ./run - waiting 10 seconds

env
system: CentOS Linux release 7.3.1611 (Core) (VMware)
docker: Docker version 18.03.1-ce, build 9ee9f40
rancher/server: v1.6.21

else
I created container with command【docker run -d --name=rancher -p 9090:8080 rancher/server】. And the Rancher started successfully. But once i stop the Rancher, i cann't start it any more. What should i do? help!!!

**Comment by alena1108** [comment]
@isolution21321 from the command - and image name `rancher/server` it seems like you are trying to start rancher 1.6 - the older version of rancher which has a limited support. To launch rancher 2.x, you have to use `rancher/rancher image` - https://rancher.com/docs/rancher/v2.x/en/installation/single-node/single-node-install-external-lb/#persistent-data-1

**Comment by isolution21321** [comment]
@alena1108 yes, i used rancher/server 1.6 image downloaded from a private registry which seems like missed some child nodes. I changed a new image on your suggestion and the problem was solved. Thanks a lot~~🙏
