### ISSUE TITLE
[HPA] Make HPA metrics Quantity placeholder more generic (%cruHpa.metrics.value.placeholder%)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20715]
Version: Master (v2.3) (6/6/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an HPA, pick anything other than "Resource" type.

**Result:**
Notice that the default Quantity has helper text of "e.g. 200Mi" (this is %cruHpa.metrics.value.placeholder%)
This isn't ideal because these quantity (values) are somewhat arbitrary. For example even our "e.g. packets-per-second" example helper text for "Metric Name" indicates something to do with networking (or count of network packets/second). So this "200Mi" value would not be correct.

I think we should instead make this much more generic like "e.g. 100"

**Comment by davidnuzik** [comment]
I will create a PR for this tomorrow.

**Comment by davidnuzik** [comment]
@loganhz (this is low priority can wait)
```
    value:
      label: Quantity
      placeholder: e.g. 200Mi
      cpuPlaceholder: e.g. 200m
      utilizationPlaceholder: e.g. 50
```
en-us.yaml

I want to change placeholder to "e.g. 100" so it's more generic like when we pick types that are not "Resource" i.e. "packets-per-second" etc metrics.
It looks like, though, this is probably used when we pick Resource > Memory though.

I think we need a memoryPlaceholder included.
This way have:
memoryPlaceholder: e.g. 200Mi
cpuPlaceholder: e.g. 200m
placeholder: 100

and placeholder should be used for non CPU/Memory cases (as generic placeholder).

I could try to implement this via the template, etc but am worried I'll break something... Is this something you or person working on HPA could possibly take on as low priority?

**Comment by loganhz** [comment]
Yes, we can work on it

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/11/19)

Now, when you pick Resource > CPU/Memory (and Average Value target type) the numbers are generic and instead to the right of the field we see "milli CPUs" and "MiB" for each respectively:

cpu avg value:
![image](https://user-images.githubusercontent.com/45179589/59305542-4cc82180-8c4f-11e9-9c9e-10cf1f91e1fe.png)

mem avg value:
![image](https://user-images.githubusercontent.com/45179589/59305558-53569900-8c4f-11e9-843e-cd5adbd12bee.png)

And in other situations where the unit of value cannot be known we simply get rid of this to the right of the "Quantity" field which I think is a good way of handling this. A couple of examples below:
![image](https://user-images.githubusercontent.com/45179589/59305607-6bc6b380-8c4f-11e9-9ad1-2682e08d6133.png)
![image](https://user-images.githubusercontent.com/45179589/59305617-72552b00-8c4f-11e9-821f-ae26ed053ed7.png)

I created some HPAs to test this and confirmed HPAs still work as expected.
