### ISSUE TITLE
When add project members/groups UI does not show the newly added member and never shows groups

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20714]
Version: v2.2.4 and Master (v2.3) (6/6/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- At the project level, add a member. Notice we don't see the newly added user in the UI until we refresh.
- Also at the project level, add a group. Notice that it will never show up even with a refresh.
- At the cluster level, add a member and a group. Notice here we DO see the newly added user and group in the UI WIHTOUT any manual refresh.

**Result:**
When add member at project level the newly added user does not show up without refresh.
When add a group at the project level the group will never show up even with a refresh.

**Comment by junkiebev** [comment]
Oddly, I'm seeing all of the members as not present in the UI post upgrade (though they still have access), even after a refresh, and I made 0 changes. This terrified me for a moment, but it *seems* to not have any adverse effect other than being _extremely_ annoying.

**Comment by davidnuzik** [comment]
Closing this original issue in favor of #20760 and see https://github.com/rancher/rancher/issues/20825 for a backport to v2.2.5
