### ISSUE TITLE
Rancher Release v2.2.4 contains invalid images in rancher-images.txt

### ISSUE THREAD

**Issue by Evolve-IT** [rancher/rancher#20718]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
We have a private repository for all of the images used by Rancher and we use the **rancher-images.txt** file which is published on the release page as input for the pulling and retagging of images for our private repository.
1. Download the **rancher-images.txt** file from the Rancher v2.2.4 release page (https://github.com/rancher/rancher/releases/tag/v2.2.4)
2. Attempt to pull all of the images in the **rancher-images.txt** file, you will see that the following images don't exist or have incorrect names:
    - jetstack/cert-manager-controller:v0.6.2
      - this is supposed to be quay.io/jetstack/cert-manager-controller:v0.6.2
    - rancher/coredns-coredns:1.1.2
    - rancher/prom-prometheus:v2.3.1
      - In Rancher release v2.2.2, the **rancher-images.txt** file contained the rancher/prom-prometheus:v2.7.1 image which leads me to believe that it should be the same for v2.2.4

**Result:**
```
$ docker pull jetstack/cert-manager-controller:v0.6.2
Error response from daemon: pull access denied for jetstack/cert-manager-controller, repository does not exist or may require 'docker login'
$ docker pull rancher/coredns-coredns:1.1.2
Error response from daemon: manifest for rancher/coredns-coredns:1.1.2 not found
$ docker pull rancher/prom-prometheus:v2.3.1
Error response from daemon: manifest for rancher/prom-prometheus:v2.3.1 not found
```

**Other details that may be helpful:**
N/A

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
  - https://github.com/rancher/rancher/releases/tag/v2.2.4

**Cluster information**
N/A

**Comment by superseb** [comment]
This is the same as https://github.com/rancher/rancher/issues/20696
