### ISSUE TITLE
chinese deploy-workloads manual 404 error

### ISSUE THREAD

**Issue by zw2020** [rancher/rancher#20724]
**What kind of request is this (question/bug/enhancement/feature request):**
https://www.cnrancher.com/docs/rancher/v2.x/cn/tasks/workloads/deploy-workloads/
404 error

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by MrYuanZhen** [comment]
You can access the workload related documentation through this link, but our translation work is still going on, and the part about the workload will be displayed in English.

URL: https://www.cnrancher.com/docs/rancher/v2.x/cn/configuration/projects/workloads/
