### ISSUE TITLE
update rancher cli to allow app updates

### ISSUE THREAD

**Issue by mshack70** [rancher/rancher#20722]
Installing an app with rancher (cli) works fine.  In my case I provide a questions.yaml with some default answers.  In the UI, one can 'upgrade' this app, change an answer (like the image tag), and the app will be redeployed with the new version.

But there isn't an option to just update values or answers of a deployed app in same way from command line, other than going thru kubectl.  The UI flexibility should be available in the cli, having an 'update' option might help with that when one wants to keep the helm chart version the same but just update variables.  If the helm app should be immutable in rancher, then the UI should not allow edit updates, but only 'upgrades' based on a new helm chart version.

gz#5179

**Comment by yogeshagr** [comment]
We really need this 👍

**Comment by jabowles** [comment]
"But there isn't an option to just update values or answers of a deployed app in same way from command line, other than going thru kubectl. "

At this moment, rancher updating my app is simply broken.  How do I  do this instead, directly using kubectl?

**Comment by brendarearden** [comment]
You can accomplish the same functionality using the cli command `rancher app upgrade` but point to the same version of the app you currently have installed while passing in the new answers / settings you would like. When using the upgrade command, it is not a requirement that you point to the next version of the app, upgrade can also be used to override existing values you have set. 

Were you having issues doing this? Kubernetes does have immutable objects, but those generally do not cause issues on upgrade unless you are using the `helm --force` command.

**Comment by nandlalushir** [comment]
This issue is still relevant.
