### ISSUE TITLE
Icons missing and font is not correct, v:0.38.0-rc1

### ISSUE THREAD

**Issue by clemenko** [rancher/rancher#2072]
v:0.38.0-rc1 OFFLINE install. 
It appears the font and glyphicons are missing from the rancher-server container. 

This is on an air-gapped network. aka. not interwebs.

**Comment by ibuildthecloud** [comment]
@vincent99

**Comment by vincent99** [comment]
Will check a copy of the actual release but they were loading for QA since they found a couple icons broken, not all of them.  @clemenko are there failed requests for them in the network requests inspector of the browser?

**Comment by clemenko** [comment]
This is an issue with an outdated version of Firefox. Specifically ESR 31.5.
