### ISSUE TITLE
Make the access url for services made available in UI.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#20739]
Rancher server version - Build from master - jun 7

Steps to reproduce the problem:
Deploy a cluster and enable "Sevice Mesh".
Create a project - `p1 and assign `user1` as project member.
Log in as `user1`.
Go to project - `p1` and Create workloads, gateway, and virtual service using 
[demobookservice.txt](https://github.com/rancher/rancher/files/3268093/demobookservice.txt)

Service is available at `http://<gatewayurl>:<port>/productpage .` But neither the gateway URL or port is displayed. The port is randomly generated, but there's no available. 

Currently there is no way to find out what the gateway url is  - `http://<gatewayurl>:<port>` .

As project owner/project member,  who has no access to the `cluster-istio` app deployed in "System" project where the gateway url is available as a endpoint.

We should be able to present this access end point in the associated workload/service page.

**Comment by loganhz** [comment]
it means we need to make virtual service, gateway as first class resource in rancher like deployment. That is the first step. Still have a lot of other steps to fix it. It might take two months or even more. So we can not fix it in preview release.

**Comment by deniseschannon** [comment]
Per @ibuildthecloud, this is not a path that users will use. 

An admin or cluster owner/member will have to point a DNS to the gateway.

For the project member,  the virtual service will have the same DNS name and the virtual service will have a destination mapping to the kubernetes service. 

We will not make the access URL available in the UI.
