### ISSUE TITLE
When enabling "Service Mesh" , "Ingress Gateway" is disabled by default .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#20738]
Rancher Server version - Build from master  - Jun 7

Steps to reproduce the problem:
Create a cluster.
Try to enable "Service Mesh" .
When enabling "Service Mesh" , "Ingress Gateway" is disabled by default .
Should we have this option enabled by default?

Only with Ingress gateway deployed we will have the gateway url being made available which is needed for viewing "Traffic Graph" when accessing services created with "VirtualService"  and "Gateway" in namespace enabled with istio-injection=enabled label.

Also mixer policy is not enabled by default .Should we have this option enabled by default as well?

<img width="1188" alt="Screen Shot 2019-06-07 at 9 03 16 PM" src="https://user-images.githubusercontent.com/4266958/59141762-d7ff9980-8967-11e9-9e57-c6241211dde2.png">

<img width="1143" alt="Screen Shot 2019-06-07 at 9 02 57 PM" src="https://user-images.githubusercontent.com/4266958/59141763-d8983000-8967-11e9-83f7-7538a0e183f9.png">

**Comment by loganhz** [comment]
Even without ingress gateway, users still can see the traffic graph and traffic metrics. Confirmed with Darren , we don’t need to enable them by default during design review meeting

**Comment by loganhz** [comment]
For mixer policy, I think we should make it enabled by default.

**Comment by loganhz** [comment]
Created another issue for enabling mixer policy https://github.com/rancher/rancher/issues/20840

**Comment by deniseschannon** [comment]
Per @ibuildthecloud the ingress gateway should be disable by default because it requires additional DNS configuration.

**Comment by loganhz** [comment]
Close, see https://github.com/rancher/rancher/issues/20738#issuecomment-501898183
