### ISSUE TITLE
DNS service discovery enhancements

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2073]
Hi,

it would be cool if the service discovery allowed for the following:

1) create individual A records for every single instance of a service application. For example:

```
[root@de6efebf6f58 /]# host -t A testapp.rancher.internal                       
testapp.rancher.internal has address 10.42.250.130                              
testapp.rancher.internal has address 10.42.237.226
```

you would then have for every single instance (e.g. 1):

```
host -t A testapp-1.rancher.internal
testapp-1.rancher.internal has address 10.42.250.130
```

2) Provide SRV records too

e.g.
```
host -t SRV _testapp._tcp.rancher.internal
_testapp._tcp.rancher.internal has SRV record 0 0 9999 testapp-1.rancher.internal.
...
```

Cheers,
Matteo

**Comment by ibuildthecloud** [comment]
Just out of curiosity, how would you use this information?  I know there must be a useful reason because other DNS based service discovery tools do the same.

**Comment by m4ce** [comment]
ibuildthecloud,

now that I know about the rancher-metadata serivice, whatever I wanted to do with DNS I can now do it via that service.

In any case, I would've used it to discover service instances to build up a cluster (e.g. zookeeper)

Cheers,
Matteo

**Comment by ibuildthecloud** [comment]
@m4ce FYI, for zookeeper, if you are doing that.  There is one field on the container called `create_index` that can be used for your zk id.  @cloudnautique Has a pretty cool setup he's been fooling with that uses confd with a custom Rancher Metadata backend that generates the zk conf and myid.

@cloudnautique Do you have any sample of that?  I know it's not complete.

**Comment by cloudnautique** [comment]
@m4ce here is a [WIP compose file](https://github.com/rancher/compose-templates/pull/1/files) that we have been working on for Zookeeper. It is using the Rancher metadata backend with our version of confd (hopefully an official version comes soon). It has a couple of issues that we need to address with the product, but the keys you'll be most interested in are:

/self/container/create_index
/self/service/containers
/containers

You can loop through the /self/service/containers to get the container names, then traverse /containers/<name>/primary_ip and /containers/<name>/create_index to get the unique ID and ip addresses of your peers.

**Comment by m4ce** [comment]
@ibuildthecloud,

thank you for sharing that, very much appreciated!

Marking the issue as closed.
