### ISSUE TITLE
Network Provider Reverting to Flannel on Cluster Creation

### ISSUE THREAD

**Issue by DarkRider1768** [rancher/rancher#20731]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create new custom cluster.
Select any Kubernetes version.
Select Weave/Canal/Calico as your Network Provider.
Continue to the next step while watching Network Provider.

**Result:**
Network Provider reverts to Flannel without user input or any notification that it's happening, other than the selection changing itself.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal
- Kubernetes version (use `kubectl version`): 1.14/1.13

- Docker version (use `docker version`): 18.09.6

**Comment by DarkRider1768** [comment]
Related but different issues:
Kubernetes version is also reverting but the drop down doesn't change. Selecting 1.14 still creates a cluster with 1.13.
Unable to configure cluster as YAML instead of Form (was trying to see if the form was failing to change the YAML configuration but it doesn't show the configuration at all).

Additional info about the original problem:
Despite appearing to revert to Flannel, it's actually creating the cluster with Canal regardless of CNI chosen.
Cache and cookies have been wiped to eliminate them as potential problems.
This has been tried with both Firefox and Vivaldi (Chrome) to rule out browser issues.

**Comment by cjellick** [comment]
@DarkRider1768 has this setup ever been upgraded to an RC or an alpha?

**Comment by DarkRider1768** [comment]
To the best of my knowledge, it has not. I'm pretty much the only person running it but it's been in place for a little while now. I try to avoid running RC unless it fixes a production blocking bug and we haven't had any so far.

If I remember correctly, we went from:
2.1.6 -> 2.1.7
2.1.7 -> 2.2.0
2.2.0 -> 2.2.1
2.2.1 -> 2.2.2
2.2.2 -> 2.2.4

**Comment by davidnuzik** [comment]
I have unfortunately not been successful in reproducing this issue yesterday with fresh 2.2.4 install (single rancher). I carefully followed steps and tested both with Chrome and Firefox on MacOS (latest). Tested both with a dirty cache and empty cache (incognito/private sessions). 

Today I tried v2.2.2 -> v2.2.4 upgrade (based on the new info provided).
- This time I created a custom cluster before the upgrade (v1.12 k8s, calico CNI) just incase having a cluster exist before upgrade is needed for some reason.
- I then upgraded to v2.2.4 and tried to add another custom cluster (v1.14 k8s, flannel CNI). I followed the steps to reproduce again and tried with both Firefox and Chrome (latest). 
- I again was unfortunately unable to reproduce.

For all tests I do not see the form switch values when I click Next button. I see HTTP is correct and clusters get created with correct k8s version I picked and correct CNI picked (check node annotations).

_Some theories as to why I cannot reproduce this:_
Possible:
- My server environment is different, I do not have multiple upgrades over time, etc
- My testing on the client-side was slightly different somehow (should not matter but tested on macOS)
Not likely:
- You could possibly have a browser extension or something that might change form right before submit for some reason? (I have personally had a situation like this before in the recent past).
- Mistake was made trying to reproduce (I feel I tested rather carefully)

**Comment by DarkRider1768** [comment]
Thanks for taking a look!

I'll roll out a fresh Rancher instance and see if it fixes things. Maybe it's some sort of corruption in our current instance. I'll report back with my findings.

**Comment by DarkRider1768** [comment]
Can confirm that a new Rancher instance on a new VM is showing expected behavior. The nodes didn't complete deployment (network plugin timeout, cni config uninitialized) at first but a quick restart got them connected and functioning as expected.

Likely just some incompatibility along the upgrade path we took or some silent corruption that happened within the original VM.

Thanks again for taking a look.
