### ISSUE TITLE
[rancher 1.6] optimize ingress controller requests to Rancher 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20736]
As a part of fixing https://github.com/rancher/rancher/issues/15288 and https://github.com/rancher/rancher/issues/8254 we have changed the rancher ingress controller logic to the full sync between k8s ingresses and rancher lbs. It solved the original problem, but introduced a performance issue seen on the user's setup having 600+ ingresses and lb version v0.9.11. Rancher responses to ingress controller would have more data now - 100 lbs by default, and it can cause issues on the setups having slower connection between ingress host and rancher server or/and slower API responses on the Rancher side when fetching a big set of data. We have also observed memory going up to 2GB for hte ingress controller

We have to investigate on the fix. A couple of thoughts:

* Check if fetching info from the metadata instead of sending the request to rancher is possible
* Re-evaluate the original fix and see if we can come up with the better solution that wouldn't require a full sync.

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
