### ISSUE TITLE
How do I rotate Kubelet logs?

### ISSUE THREAD

**Issue by portfield-slash** [rancher/rancher#20744]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
Keep RancherCluster running for a certain period of time.

**Result:**
Kubelet runs as a docker container. Not pods.
The size of the log in the following path increases.
How do I rotate Kubelet logs?
Is it better to use host OS log rotation? If you have a good way, please let me know.

```
/var/lib/docker/[Kubelet Container ID]/[Kubelet Container ID]-json.log
```

**Other details that may be helpful:**
Please ask questions if necessary.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):cloud 3Core/8GB
- Kubernetes version (use `kubectl version`):v1.13.3

```
v1.13.3
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by cortopy** [comment]
I just discovered this same issue in one of my nodes. The json log file was 100GB+ and my guess it could grow forever

**Comment by BeryJu** [comment]
I was running into this issue as well, I "fixed" it using these steps:
- To temporarily fix it, remove the log file and restart the container, without container restart the file handle isn't closed and the space is still consumed
- In your `/etc/docker/daemon.json` (file might not exist), set the following settings:

```json
{
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "10m",
        "max-file": "3"
    }
}
```

Afterwards, **restart** the docker daemon (a reload did not correctly load these settings for me). Afterwards, you have to stop and delete the kubelet container, and trigger an RKE-rebuild from Rancher, for example by changing a Cluster-setting.

This will re-create the container with the new settings.

**Comment by cortopy** [comment]
that sounds like the missing setting! thank you for that @BeryJu. But will that not make all containers to emit logs in json file formats? 

I was thinking of trying this https://sandro-keil.de/blog/logrotate-for-docker-container/

**Comment by BeryJu** [comment]
@cortopy It will, yes, but according to the [docs](https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver) this is already the default.

**Comment by cortopy** [comment]
Nice one @BeryJu It's all working great now. Thanks a lot
