### ISSUE TITLE
Expose environment variables in container

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2074]
Hi,

it would be useful if rancher could expose the following properties (in order of importance) as enviroment variables when launching a container:

1. service name
2. service instance
3. stack name

Cheers,
Matteo

**Comment by ibuildthecloud** [comment]
We expose this information in our Metadata Service http://docs.rancher.com/rancher/metadata-service/. Is that sufficient?

**Comment by m4ce** [comment]
@ibuildthecloud,

that's more than I was actually looking for! Great!

Closing issue.
