### ISSUE TITLE
GoLand debug error! help me!

### ISSUE THREAD

**Issue by liuwenjiegithub** [rancher/rancher#20746]
API server listening at: [::1]:51057
panic: accept tcp [::1]:51057: use of closed network connection

goroutine 6 [running]:
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run.func1(0xc00009d200)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/service/rpccommon/server.go:155 +0x13f
created by github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/service/rpccommon/server.go:145 +0x3ec

Debugger finished with exit code 2

**Comment by loganhz** [comment]
Please file a new issue with more info
