### ISSUE TITLE
Sending logs elastichsearch overload

### ISSUE THREAD

**Issue by aleksey005** [rancher/rancher#20745]
When logging is enabled, all the available logs are sent at once, which leads to large queues in the fluentd. There is no possibility to choose - send only logs that were formed after sending logs were enabled.

feature request

Steps to reproduce: Go to Tools --> Logging, select Elasticsearch, enter Elasticsearch Configuration, click Save

Result: go to monitoring Rancher components, see Fluentd output buffer queue and Fluentd output buffer size - result large send queues and buffer size, and elasticsearch can't handle the overload.

Environment information
- Rancher version: v.2.2.4
- Installation option (single install/HA): single

Cluster information
- Cluster type: Custom
- Machine type: metal
- Kubernetes version:  v1.14.1
...
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
...
- Docker version: 
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by franzmueller** [comment]
I'm seeing a lot of HTTP 413 errors when enabling logging and I think this might be related to this issue. Are there any workarounds?

**Comment by splattner** [comment]
Same here, everytime a fluentd pod is restarted a huge load is generated to our Elasticsearch, multiple gigs are loaded into ES and ofter ES cannot handle it anymore.. I assume fluentd does ship all the "old" logs again.
