### ISSUE TITLE
PSP Editor: Last capability cannot be removed

### ISSUE THREAD

**Issue by ravenpride** [rancher/rancher#20741]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1) Open a PSP in the editor form.
2) Select a capability in one of the three list boxes.
3) Save the PSP.
4) Open the PSP again.
5) Try to get rid of the selected capability.

**Result:**
There is no way to get rid of the last capability in each of the list boxes.

**Environment information**
- Rancher version: v2.2.3
- Installation option: single install

**Comment by loganhz** [comment]
`Command + click` will unselect it. Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
