### ISSUE TITLE
JavaScript Object in error

### ISSUE THREAD

**Issue by mlh758** [rancher/rancher#20752]
![image](https://user-images.githubusercontent.com/4331955/59205005-7dcd2700-8b67-11e9-9847-e722c6c4f678.png)

I see this error message sometimes when trying to click view/edit yaml on a deployment. It seems to happen when Rancher is running slow/having trouble connecting to the kubernetes instance.

In this case it is the `yaml` endpoint, the response we're getting is:

```
Error: 'x509: certificate is valid for ...
Trying to reach: 'https://some-ip:6443/apis/apps/v1beta2/namespaces/my-namespace/deployments/deployment'
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.3` UI: `v2.1.17` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
