### ISSUE TITLE
EKS cluster should have Kubernetes version v1.13 as default in UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#20759]
Version: Master

Steps:
1. Create a EKS cluster and we observe that k8s version v1.11 is chosen by default
Note: K8s 1.13 is available from end of March.

![Screen Shot 2019-06-10 at 1.37.20 PM.png](https://zube.io/files/rancher/3f88ad50c88662e64130d305afcea585-screen-shot-2019-06-10-at-1-37-20-pm.png)

Note: K8s 1.12 is chosen as default in rancher v2.2.4, v2.1.10 and v2.0.15

**Comment by davidnuzik** [comment]
Something must have changed recently. UI used to have 1.12 as default (v2.2.3, v2.2.4, master).

**Comment by davidnuzik** [comment]
Note, we see UI seems to set to v1.11 in v2.2. and in latest master, but in v2.2 it was 1.12 for some reason.

**component.js (master and v2.2.4):**
```
    if ( !config ) {
      config = get(this, 'globalStore').createRecord({
        type:              'amazonElasticContainerServiceConfig',
        accessKey:         null,
        secretKey:         null,
        region:            'us-west-2',
        instanceType:      'm4.large',
        minimumNodes:      1,
        maximumNodes:      3,
        kubernetesVersion: '1.11'
      });
```

If we inspect API in v2.2 and master we see little has changed:

**2.2.4:**
v3/settings/ui-k8s-supported-versions-range
```
default": ">= 1.11.0 <=1.13.x",
...
value": ">= 1.11.0 <=1.13.x"
```
v3/settings/ui-k8s-default-version-range
```
"default": "<=1.13.x",
...
value": "<=1.13.x"
```

**master:**
v3/settings/ui-k8s-supported-versions-range
```
default": ">= 1.11.0 <=1.14.x",
...
"value": ">= 1.11.0 <=1.14.x"
```
v3/settings/ui-k8s-default-version-range
```
"default": "<=1.14.x",
...
value": "<=1.14.x"
```

There doesn't appear to be any obvious explanation; will need more digging later.

**Comment by davidnuzik** [comment]
Also see https://github.com/rancher/rancher/issues/21043
I could not replicate in v2.2.4 but perhaps there is something going on that may cause the issue in v2.2.4 as well...

**Comment by davidnuzik** [comment]
Updated issue to reflect new addition of 1.13; so default should of course be 1.13 in the UI (not 1.12 as previously stated in the issue).

**Comment by deniseschannon** [comment]
@loganhz k8s 1.13 has been added into EKS as the default version

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (7/23/19)

Version 1.13 of k8s is now picked by default with EKS. But I'm confused why is 1.12 not selectable?
![image](https://user-images.githubusercontent.com/45179589/61733420-9fa7f500-ad34-11e9-8de3-12995df6beee.png)

For what reason do we block creation of 1.10, 1.11, 1.12, etc. I'm sure there is a good reason but I do not understand.
From AWS UI:
![image](https://user-images.githubusercontent.com/45179589/61733482-c6fec200-ad34-11e9-97ce-d59703bf7433.png)

For what reason is ui-k8s-supported-versions-range set to a value of ">=1.13.x <=v1.15.x" security concerns?

**Comment by davidnuzik** [comment]
Reopening as I have a question about the fix as per above.

**Comment by deniseschannon** [comment]
Typically, we prefer to only support 3 versions of Kubernetes. The latest and the previous 2 versions. The latest for 2.3 will be 1.15 and therefore Rancher will support 1.15, 1.14, 1.13.

**Comment by davidnuzik** [comment]
v2.2.7-rc4:

Possibly fixed by something else.
![image](https://user-images.githubusercontent.com/45179589/62497730-a7828300-b791-11e9-9856-2c625678ccbc.png)

and drop down looks correct:
![image](https://user-images.githubusercontent.com/45179589/62497739-ae10fa80-b791-11e9-8be5-e0ead7e3ef37.png)

v1.13 k8s cluster comes up successfully without any issues.

And we are only supporting that 3 versions so I think this can be closed?
