### ISSUE TITLE
Needs to switch to the environment to set it as default

### ISSUE THREAD

**Issue by andrefreitas** [rancher/rancher#2075]
If you are in environment A and create B, to set B as default, you need to switch to B first and then make it as default. Also, you need to refresh the page to see that the checked icon changed.

**Comment by deniseschannon** [comment]
What version are you running? I have no issues in v0.38.0.

I am able to set the default environment without switching to it. Note: This will not switch the environment that you are currently in. It will just switch it for when you login.

**Comment by andrefreitas** [comment]
@deniseschannon I am on version v0.37.1. Maybe it was fixed in v0.38.0. I was able to reproduce this problem a lot of times. I know that it doesn't switch the current environment.

If in the newest version it works fine I guess this issue is closed.
