### ISSUE TITLE
Navigating to HPA tab in GKE, EKS cluster gives 404 not found error

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#20758]
Version: Master

1. Create GKE, EKS clusters.
2. Navigate to HPA tab

It fails with the below error

![Screen Shot 2019-06-10 at 11 43 06 AM](https://user-images.githubusercontent.com/18536626/59218750-ce4b8100-8b75-11e9-936f-bd3a7ba750b8.png)

Note: For AKS and EKS clusters, this issue is not seen if K8s version is v1.12.x and above.
For RKE clusters too, the issue is not seen with k8s version v1.12.x and above.

(For k8s version v1.11.x,  the issue above is seen for all clusters)

**Comment by loganhz** [comment]
@orangedeng In GKE 1.13.6, there is no `v2beta2.autoscaling` api. How does it happen?

```
> kubectl get hpa.v2beta2.autoscaling
error: the server doesn't have a resource type "hpa"
```

**Comment by orangedeng** [comment]
Yes. I think we should not show the HPA in the UI when `kubectl get apiservice v2beta2.autoscaling` returns an active obj. There is no `v2beta2.autoscaling` api in GKE. Still looking for reference for this one.

**Comment by soumyalj** [comment]
Tested with master from June 11. 
Created GKE cluster and I do see the below note as expected

![Screen Shot 2019-06-11 at 4 19 08 PM](https://user-images.githubusercontent.com/18536626/59313180-c0c0f480-8c64-11e9-90c2-699d7b3aff94.png)
But the Add HPA button is still active in UI which allows entering values
![Screen Shot 2019-06-11 at 4 21 04 PM](https://user-images.githubusercontent.com/18536626/59313231-f5cd4700-8c64-11e9-8e76-3bdaf9b1654b.png)

**Comment by soumyalj** [comment]
Tested with master build from June 11. 
1. Created GKE cluster. The "Add HPA" button is disabled.
2. For EKS cluster with K8s v1.11 , the "Add HPA" button is disabled
