### ISSUE TITLE
Global Key - Encryption Key visible to user while enabling Global Registry until the page is refreshed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20761]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce:**
verified on rancher:master - latest - (07/07/2019)
**Issue - 1**
**Before enabling Global Registry on Rancher**
1. Admin Password and Encryption Key for Harbor input fields are made as options for admin user to enter values.
2. Provide values to enable the Global Registry.
3. Click on Enable. 
4. The page changes to where Encryption Key is visible
<img width="1462" alt="Screen Shot 2019-06-07 at 1 02 52 PM" src="https://user-images.githubusercontent.com/26032343/59132582-753bdd00-892a-11e9-9894-5928a9f8a2bf.png">
5. After the Global Registry is enabled, and you have not moved from the page from step , you can see the page with the encryption key still visible
<img width="976" alt="Screen Shot 2019-06-07 at 1 33 52 PM" src="https://user-images.githubusercontent.com/26032343/59132676-ab795c80-892a-11e9-8848-febce4ae1862.png">
6. Once you hard refresh the page, the Encryption Key is not visible anymore.
<img width="881" alt="Screen Shot 2019-06-07 at 1 31 06 PM" src="https://user-images.githubusercontent.com/26032343/59132713-c9df5800-892a-11e9-9851-fc502095d4b7.png">

**Expected Result:**
Encryption Key not be visible without a hard refresh, i.e when the user clicks on Enable Global Registry/Generate Pass, the page should not display the Encryption Key in visible text.

**Actual Result:**
Encryption Key is visible until the user refreshes the page.

**Issue - 2**
1. Navigate to Global Registry on Rancher UI. Global Registry is not enabled yet.
2. Enter an Encryption Key in the field. The entered test is not visible to the user.
3. Now click on **Generate**. Generated Key is visible to the user.
4. Now Delete the generated key, and type in an encryption key. 
5. Now the user will be able to see the entered text.

**Note:** This is the same case of Generate Password section, in Add new User page on rancher UI

**Expected Result:**
User should not be able to see the entered text in Encryption Key field or the Password field(Add User page)

**Actual Result:**
User is able to see the entered text in Encryption Key field or the Password field(Add User page)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher master
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment]
This is a general "Generate Password" workflow.
