### ISSUE TITLE
[Question] What is the Kubernetes distribution for each infra cloud provider?

### ISSUE THREAD

**Issue by gyliu513** [rancher/rancher#20768]
**What kind of request is this (question/bug/enhancement/feature request):**

When I install a k8s cluster on AWS via Rancher UI, what is the k8s version running on AWS? Is it just a native k8s cluster from community or a customized version by Rancher? How can I select k8s versions when install?

**Comment by loganhz** [comment]
it's community version. You can select the k8s version when you create cluster in UI
