### ISSUE TITLE
Where can I find the Rancher V3 Api Documentation?

### ISSUE THREAD

**Issue by S93rastogi** [rancher/rancher#20772]
With the release of version 2.x of rancher we started using v3 of the Apis but to my despair there is no proper documentation for the apis. If we visit the Rancher Documentation Page https://rancher.com/docs/rancher/v2.x/en/api/ we just find the brief intro and not the information about how to use the specific endpoints and what are the inputs accepted by them. For eg we have a v3/cluster endpoint to create the cluster but it requires "n" number of inputs in the form strings/objects. How could one find out what all attributes are needed and also what all attributes map to what thing in the UI.

There is some documentation available for v2 of the api but things have changed miles with the introduction of v3 of Rancherapi.

**UseCase :**  I need to automate the complete process of cluster creation to helm chart installation

I took some help from the medium blog : https://medium.com/@superseb/adding-custom-nodes-to-your-kubernetes-cluster-in-rancher-2-0-tech-preview-2-89cf4f55808a to understand the APIs

**Comment by mak3r** [comment]
You can get examples of many api calls right in the UI by selecting the hamburger menu and then select "View in API". From there, you will get a new tab that opens in your browser. The address bar of this new tab contains the url that returns the json you see on the page. In addition, you will see an an action menu at the top right of this tabbed page. From the action menu, you can do additional things by clicking on the buttons or links which will open up a form. The items in the form that have asterisks are required. At the bottom of the floating dialog, you can select the "Show Request" button which will provide you with both `RESTful` and `curl` commands to use. Use these as your templates.

If there is something you want to do but you don't see the "View in API" option, then you can use the browser tools to view the commands used.

Also you can find more information at this page
https://github.com/rancher/api-spec/blob/master/specification.md

**Comment by catherineluse** [comment]
The API docs are being tracked in the `rancher/docs` repo https://github.com/rancher/docs/issues/1587

**Comment by fsperling** [comment]
At https://your_rancher_cluster/v3/
you can browse the API resources and also build requests with the UI.
Maybe it could be better documented that you can find all resources there.

**Comment by ShadowJonathan** [comment]
I find the API explorer unintuitive and I feel like I don't have a complete overview of all methods/verbs/objects that there can be within reach, making a compiled list of all of this would surely help adoption of the API, as of right now (for me personally), building against the API would be not easy to do, which is not a good thing.

**Comment by lcax200000** [comment]
Has anyone tried it : https://github.com/rancher/client-python
Where can I find feature (or example)  about  client-python

**Comment by philipsparrow** [comment]
> Has anyone tried it : https://github.com/rancher/client-python
> Where can I find feature (or example) about client-python

Yes I'm using it. I didn't find much sample code though

**Comment by gitandre** [comment]
I am trying to find out if I am able to get the list of **related k8s namespaces for a given Rancher project**. I have explored the available v3/ endpoints and the project specific links but I can find no reference. The Project/Namespace UI page looks like it does something to get those relationships but I cannot see how it is done (even when looking at the network calls)

My only option seems to be to  pull each namespace and inspect its annotation to see if it belongs to the project in question? (I am hoping not)

If anyone has done something similar or if I missed something please let me know, thanks

**Comment by gitandre** [comment]
> I am trying to find out if I am able to get the list of **related k8s namespaces for a given Rancher project**. I have explored the available v3/ endpoints and the project specific links but I can find no reference. The Project/Namespace UI page looks like it does something to get those relationships but I cannot see how it is done (even when looking at the network calls)
> 
> My only option seems to be to pull each namespace and inspect its annotation to see if it belongs to the project in question? (I am hoping not)
> 
> If anyone has done something similar or if I missed something please let me know, thanks


I found an alternative way of getting the info i need using the GO K8s SDK
```
	nsList := corev1.NamespaceList{}
	err := r.r.List(context.Background(), &nsList, client.MatchingLabels{"field.cattle.io/projectId": "p-wwkqp"})
```
So all good for now, thanks
