### ISSUE TITLE
[UI] catalog filter didn't work

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#20771]
**What kind of request is this (question/bug/enhancement/feature request):**
UI bug

**Steps to reproduce (least amount of steps as possible):**
1. Go to the project level catalog apps page
2. filter catalog app either by name or type didn't work 
![image](https://user-images.githubusercontent.com/4569037/59247670-b0a01980-8c52-11e9-9621-c42bd21a6271.png)
The API has returned the correct number of catalog apps.

**Result:**
User should be able to filter catalog apps either by catalog name or categories.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master 06/11
- Installation option (single install/HA): single & HA

**Comment by davidnuzik** [comment]
This is a known issue @guangbochen refer to https://github.com/rancher/rancher/issues/20163

**Comment by guangbochen** [comment]
close if favor of https://github.com/rancher/rancher/issues/20163
