### ISSUE TITLE
Airgap support for API UI

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2077]
Server version - V0.38.0-rc1

Not able to load the "View in api" page in air gap setup.

<img width="1180" alt="screen shot 2015-09-18 at 10 21 08 am" src="https://cloud.githubusercontent.com/assets/4266958/9966104/a3285294-5def-11e5-897e-689e7f93acaf.png">

**Comment by vincent99** [comment]
The API UI is a separate package that was not included in the airgap release
