### ISSUE TITLE
"Failed to connect to proxy" error="websocket: bad handshake" while importing existing k8s cluster

### ISSUE THREAD

**Issue by ayanendude** [rancher/rancher#20786]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
2 K8s clusters are created on VirtualBox. 
Cluster 1 VMs. Kmaster, knode1, knode1
Cluster 2 VMs. Kmd, kn1, kn2
kubectl v1.14.2 on all vms

Rancher container is up using below command in kmd(Master of cluster 2).
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /home/<myid>/rancher:/var/lib/rancher rancher/rancher:latest
Rancher 2.2.3 is running.

Imported cluster 2 successfully in rancher. 
When I try to import cluster 1, it is in "Pending" state.
I tried removing cattle-system namespace re-creating cattle pods, but it did not help.

**Result:**
on kmaster
kubectl get pods -o wide --all-namespaces
NAMESPACE        NAME                                     READY   STATUS             RESTARTS   AGE     IP             NODE   NOMINATED NODE   READINESS GATES
cattle-system    cattle-cluster-agent-59c8cc49d5-st9qm    1/1     Running            6          2d1h    192.168.2.76   kn2    <none>           <none>
cattle-system    cattle-node-agent-fz7w6                  1/1     Running            6          2d1h    192.168.1.31   kn1    <none>           <none>
cattle-system    cattle-node-agent-t5v22                  1/1     Running            6          2d1h    192.168.1.32   kn2    <none>           <none>

<img width="367" alt="image" src="https://user-images.githubusercontent.com/25129134/59289522-441e1e00-8c44-11e9-93ad-af7a8d4bcace.png">

In Rancher UI, I see below.
This cluster is currently Pending; areas that interact directly with it will not be available until the API is ready.

Response in Kmaster (Cluster 1 master)
kubectl logs pod/cattle-cluster-agent-59c8cc49d5-st9qm  -n cattle-system

W0611 15:19:35.167659       1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 164863 (164880)
W0611 15:43:00.204276       1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 166576 (167240)
W0611 16:05:10.316230       1 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 168914 (169454)

kubectl -n cattle-system logs -l app=cattle-agent
time="2019-06-11T13:14:12Z" level=info msg="Option requestedHostname=kn2"
time="2019-06-11T13:14:12Z" level=info msg="Listening on /tmp/log.sock"
time="2019-06-11T13:14:13Z" level=info msg="Connecting to wss://192.168.1.30/v3/connect with token vhdkjsdcn22lkr9dc9p55lglzqgjxzflk9gv4v95dwprbrtvj979tq"
time="2019-06-11T13:14:13Z" level=info msg="Connecting to proxy" url="wss://192.168.1.30/v3/connect"
time="2019-06-11T13:14:13Z" level=info msg="Starting plan monitor"

**Other details that may be helpful:**
on kmaster, I am able to curl k8s api.
curl --insecure -Iv http://192.168.1.30:443
* Expire in 0 ms for 6 (transfer 0x556ad9bc35c0)
*   Trying 192.168.1.30...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x556ad9bc35c0)
* Connected to 192.168.1.30 (192.168.1.30) port 443 (#0)
> HEAD / HTTP/1.1
> Host: 192.168.1.30:443
> User-Agent: curl/7.64.0
> Accept: */*
>
* Closing connection 0
curl: (8) Weird server reply

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
<img width="59" alt="image" src="https://user-images.githubusercontent.com/25129134/59289403-002b1900-8c44-11e9-9656-d2b5c5a264b7.png">

- Installation option (single install/HA):
Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):1.14

```
(paste the output here)
```

- Docker version (use `docker version`):
ocker version
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Fri Apr 12 00:34:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Fri Apr 12 00:27:37 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
(paste the output here)
```

**Comment by ayanendude** [comment]
resolved. missed to bind role.

**Comment by Perfect-Web** [comment]
i have the same issue

**Comment by cesarandreslopez** [comment]
Same issue

**Comment by crowdy** [comment]
same issue with rancher v2.2.6

**Comment by gzericlee** [comment]
same issue with rancher v2.2.5

**Comment by zhming0** [comment]
same issue with rancher v2.2.7

The main problem is that there isn't enough information for debugging this issue.

**Comment by pib** [comment]
A potential solution for some folks: https://github.com/rancher/rancher/issues/20651#issuecomment-528683673
