### ISSUE TITLE
[RFE] Add busybox image to rancher-images.txt so this is pre-pulled in air-gapped installations for users wishing to enable audit logging

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#20780]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Other details that may be helpful:**

[The `--busyboxImage` parameter](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/) can be used when installing Rancher in an air-gapped environment, and configuring audit logging, to specify a private repository location for the busybox image used by audit logging.

However, a busybox image is not included in the list of images pulled and pushed to a private repository when following the [air-gapped installation documentation](https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/install-rancher/) (https://github.com/rancher/rancher/releases/download/v2.2.4/rancher-images.txt). Enhancement request is to include busybox in this list of images.

**Environment information**
Rancher v2.2.4

**Comment by deniseschannon** [comment]
can we also add alpine? https://github.com/rancher/rancher/issues/21650

**Comment by jiaqiluo** [comment]
The bug fix is validated in rancher:v2.3.0-alpha7

Confirm that the image `busybox` is in the `rancher-images.txt` file (https://github.com/rancher/rancher/releases/tag/v2.3.0-alpha7)

```
> cat rancher-images.txt | grep busybox
busybox
```

**Comment by HectorB-2020** [comment]
Hello! I'm following [this official guide](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha) to setup Rancher in air-gapped environment.
In particular it gives this command line:
```bash
   helm install rancher ./rancher-<VERSION>.tgz \
    --namespace cattle-system \
    --set hostname=<RANCHER.YOURDOMAIN.COM> \
    --set certmanager.version=<CERTMANAGER_VERSION> \
    --set rancherImage=<REGISTRY.YOURDOMAIN.COM:PORT>/rancher/rancher \
    --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ # Set a default private registry to be used in Rancher
    --set useBundledSystemChart=true # Use the packaged Rancher system charts
```
However I took courage to look inside `template\deployment.yaml` and found that `.Values.busyboxImage` is taken as is without adjustments to possible private registry.
Having searched through  existing issues led me to this one. And surprisingly I found what I exactly was expecting for, the example from @jiaqiluo 
```yaml
--set busyboxImage=my-registry:443/rancher/busybox \
```
Is this a gap in the documentation? Should I file a separate issue on this?

Other question if you don't mind. When will `systemDefaultRegistry` start playing its role? Do I still we have to always put full internal path into `image:` in manifests? If yes, what's use of `systemDefaultRegistry` then?

---
Meanwhile I found some other issues related to problems with private registry in air-gapped environment
* https://github.com/rancher/rancher/issues/41765
* https://github.com/rancher/rancher/issues/40546
* https://github.com/rancher/rancher/issues/39138
* https://github.com/rancher/rancher/issues/38810
* https://github.com/rancher/rancher/issues/38299
* https://github.com/rancher/rancher/issues/37221
* https://github.com/rancher/rancher/issues/35192
* https://github.com/rancher/rancher/issues/31136
* https://github.com/rancher/rancher/issues/29535
* https://github.com/rancher/rancher/issues/28420
* https://github.com/rancher/rancher/issues/24889

**Comment by jiaqiluo** [comment]
Hi @HectorB-2020 

It is expected that the value of `busyboxImage` contains the registry. It is a common rule that the image name, or "registry" in some charts, is the full path to the image if it is not DockerHub.  

Rancher uses `systemDefaultRegistry` to pull images for its components and provisioning clusters.
see https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/global-default-private-registry

**Comment by HectorB-2020** [comment]
Thanks for response, @jiaqiluo! I appreciate. 
I'm certainly not questioning that `busyboxImage` like other images used in manifests must contain full path to private registry.
I merely pointed to a gap in the documentation: `rancherImage` is properly redefined while `busyboxImage` is not even mentioned that it has to be redefined if used in air-gapped environment. Unless I dared to examine chars I would never have known that `busyboxImage` might require special attention.

However perhaps I'm not following the idea behind `systemDefaultRegistry`. If it's defined, may I forget specifying full path to our private registry? May leave my manifest with, let's say, `image: nginx:latest` unaltered and be sure Rancher & k8s are to adjust that definition to full internal path based on a hostname provided in `systemDefaultRegistry`? Sounds like a magic. Is this magic explained anywhere?

**Comment by jiaqiluo** [comment]
hi @HectorB-2020 , 

I wonder if this is what you are looking for: the option `busyboxImage` is described on [this page](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options).  

The systemDefaultRegistry is a user-defined private registry that will be used to pull all Rancher system container images.

For RKE1 downstream cluster, you still need to set the full path for the images of your deployments to pull from your private registry. ([docs](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries))

For RKE2 downstream cluster, you can configure the "mirror" when provisioning/updating the cluster. Then, you do not need to set the full path. ([RKE2 Docs](https://docs.rke2.io/install/containerd_registry_configuration?_highlight=registry&_highlight=mirror#registries-configuration-file))

**Comment by HectorB-2020** [comment]
I guess now it became clear. At least much better than before. :smile_cat: Thank you @jiaqiluo!
