### ISSUE TITLE
Creating AKS cluster on a /24 Azure VNet Subnet fails

### ISSUE THREAD

**Issue by dbsanfte** [rancher/rancher#20784]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a virtual network in Azure, then create a Subnet in it with a /24 IP allocation.
- Attempt to deploy a 3-node AKS cluster to this subnet via Rancher.

**Result:**
The cluster creation attempts to reserve 333 IP addresses, which is crazy:

Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InsufficientSubnetSize" Message="Pre-allocated IPs 333 exceeds IPs available in Subnet 251" Target="agentPoolProfile.count"
--

**Other details that may be helpful:**
A /24 subnet is very common and deploying to one shouldn't be broken out of the box.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v.2.2.4
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Provider - Azure AKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Standard_DS11_v2
- Kubernetes version (use `kubectl version`):
1.13.5

- Docker version (use `docker version`):
N/A

**Comment by dbsanfte** [comment]
Nevermind, you can close this I guess, this is an Azure AKS limitation. I guess I just need to create bigger subnets...

**Comment by leodotcloud** [comment]
**Root cause:** Even Advanced Networking is selected, the network Plugin was set to azure not kubenet.

**Workaround:** Use the API or curl to create the cluster by overriding "networkPlugin": "kubenet" in the azureKubernetesServiceConfig.
