### ISSUE TITLE
Creating AKS cluster with even moderately long Resource Group name results in field length error

### ISSUE THREAD

**Issue by dbsanfte** [rancher/rancher#20783]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Use the Rancher UI to create an AKS cluster in Azure with a resource group name of reasonable length (ie, rancher-kube-cluster-dev2) and monitoring enabled

**Result:**
Provisioning fails with:

Operationalinsights.WorkspacesClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=workspaceName constraint=MaxLength value="rancher-kube-cluster-dev2-c24b7341-10ad-4e4c-b3f7-f07c483184a9-WEU" details: value length must be less than or equal to 63; waiting on cluster-provisioner-controller
--

**Other details that may be helpful:**
The value for the OMS workspace name needs to be a lot shorter.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.4

- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Provider - Azure AKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Standard_DS11_v2
- Kubernetes version (use `kubectl version`):
1.13.5

- Docker version (use `docker version`):
N/A

**Comment by daxmc99** [comment]
Thanks @dbsanfte, we will be tracking this as part of https://github.com/rancher/rancher/issues/21061
