### ISSUE TITLE
Openstack userDataFile missing from fields converted to accept contents

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#20788]
Original issue: https://github.com/rancher/rancher/issues/20747

**Comment by sowmyav27** [comment]
With rancher server version - rancher:master (06/24/2019)
Create an openstack node driver with userdata set.
userdata field is now a multiline input field.

Driver machine call made by rancher server indicates that userdata gets passed as expected as file (inside /opt/jail/<cluster-id>) which has the correct userdata content set (as was passed from the multi line userdata field)

```
2019/06/24 23:36:50 [DEBUG] create cmd [create -d openstack --engine-install-url https://releases.rancher.com/install-docker/18.09.sh --openstack-endpoint-type adminURL --openstack-ssh-port 22 --openstack-username xxxx --openstack-image-name xxxx --openstack-domain-name Default --openstack-flavor-name m1.small --openstack-ip-version 4 --openstack-tenant-id xxxxxx --openstack-user-data-file /EBXOIZRFQU --openstack-active-timeout 200 --openstack-password xxxxxx --openstack-auth-url http://1x.x.x.x:5000/v3 --openstack-ssh-user admin]```

```
root@xxxxyyy:/opt/jail/c-w5lsp# cat EBXOIZRFQU
test1
test2
test3
test4
test12345root@xxxxyyy:/opt/jail/c-w5lsp# 
```
