### ISSUE TITLE
Backport: Unable to add node driver master

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#20799]
https://github.com/rancher/rancher/issues/20796

**Comment by sowmyav27** [comment]
Validated on the latest master (06/14/2019)
Able to add custom driver : **Linode**
`https://github.com/linode/docker-machine-driver-linode/releases/download/v0.1.8/docker-machine-driver-linode_linux-amd64.zip`
UI: `https://linode.github.io/rancher-ui-driver-linode/releases/v0.2.0/component.js`
logs:
```
Download https://github.com/linode/docker-machine-driver-linode/releases/download/v0.1.8/docker-machine-driver-linode_linux-amd64.zip
2019/06/14 16:39:50 [INFO] Found driver docker-machine-driver-linode
2019/06/14 16:39:50 [INFO] Copying management-state/machine-drivers/18206b37b5529c1138ddc9fe568a803b03ae3c39ebb8abe4ae1934aef49ba4bc-docker-machine-driver-linode => /opt/drivers/management-state/bin/docker-machine-driver-linode-tmp
2019/06/14 16:39:50 [INFO] uploading linodeConfig to nodeconfig schema
2019/06/14 16:39:50 [INFO] uploading linodeConfig to nodetemplateconfig schema
2019/06/14 16:39:50 [INFO] uploading linodecredentialConfig to credentialconfig schema
```
UI:
<img width="960" alt="Screen Shot 2019-06-14 at 9 41 16 AM" src="https://user-images.githubusercontent.com/26032343/59524386-98b1db00-8e88-11e9-8c91-010858cbf8d6.png">
