### ISSUE TITLE
Logging: Add option for fluentd log level in helm chart

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#20793]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Desired Result:**

Add an answer for the fluentd helm chart for cluster level logging that allows you to select the log level for the fluentd process. Right now you need to modify the fluentd.command answer and add the `-qq` flag (for example) to set to error level.

It seems that this should be relatively doable by just adding an answer that changes the log level in the `<system>` tag in the config:

https://docs.fluentd.org/deployment/logging#by-config-file

**Comment by Kampfmoehre** [comment]
The chart has changed since then and there seems to be no more fluentd.command answer in the new chart. Is there any way in the current chart to set the log level for FluentD? Setting it in the StatefulSet does not change anything and is reverted instantly and manually adding a logh level to any of the mounted secrets is deleted when the fluentd pod restarts (I assume it is newly generated).
We have 3 clusters and from one logging to ElasticSearch is not working and I have no idea why. The FluentD log is completely empty and I would like to see some logs to debug further on why no logs appear in ElasticSearch from this cluster.

**Comment by cm0s** [comment]
> The chart has changed since then and there seems to be no more fluentd.command answer in the new chart. Is there any way in the current chart to set the log level for FluentD? Setting it in the StatefulSet does not change anything and is reverted instantly and manually adding a `@log_level debug` to any of the mounted secrets is deleted when the fluentd pod restarts (I assume it is newly generated). We have 3 clusters and from one logging to ElasticSearch is not working and I have no idea why. The FluentD log is completely empty and I would like to see some logs to debug further on why no logs appear in ElasticSearch from this cluster.

Did you find a solution to set the debug mode permanently?

**Comment by Kampfmoehre** [comment]
> Did you find a solution to set the debug mode permanently?

Unfortunately not

**Comment by cm0s** [comment]
> 

 I encounter the same limitation. Still no solution ?

**Comment by Kampfmoehre** [comment]
>  I encounter the same limitation. Still no solution ?

Not that I know of.

**Comment by pankajsqe** [comment]
Test failed in update logging's fluentd log level.

Rancher : 2.9.0-alpha1
Cluster : 	v1.28.9+rke2r1
Logging chart : 104.0.0-rc1+up4.4.0

![Image](https://github.com/rancher/rancher/assets/149133120/0ad614b3-3dae-4f6b-979d-7c1c75b7bd16)




(Update Existing Logging's fluentd log level).
Once Logging chart has been installed with fluentd.logLevel=info and now when I am trying to upgrade existing logging chart from edit-config page with fluentd.logLevel=debug Values.yaml page is getting updated and showing logLevel as debug but in rancher-logging-root-fluentd-configcheck-ac2d4553 logs it still shows previous logLevel value which is info.

**Comment by dharmit** [comment]
@pankajsqe first off, my apologies for providing incorrect information on how to test this. I wasn't aware till I had a chat with @joshmeranda.

Try following steps:
* Install the CRDs:
  ```sh
  $ helm install logging-crds rancher-charts/rancher-logging-crd
  ```
* Install the chart
  ```sh
  $ helm install logging /path/to/git-clone/charts/rancher-logging/104.0.0-rc1+up4.4.0 --namespace cattle-logging-system
  ```
* Open a few terminals and run the following commands:
  ```sh
  $ kubectl logs logging-root-fluentd-0 -c fluentd -f
  $ kubectl logs logging-root-fluentd-0 -c config-reloader -f
  ```
* Now change the value of `logLevel` through UI or using helm:
  ```
  $ helm upgrade logging /path/to/git-clone/charts/rancher-logging/104.0.0-rc1+up4.4.0 --set fluentd.logLevel=debug
  ```

* Wait for logs in `config-reloader` container to show something like:
  ```sh
  $ k logs logging-root-fluentd-0 -c config-reloader -f
  2024/05/30 09:46:51 Watching directory: "/fluentd/etc"
  2024/05/30 09:46:51 Watching directory: "/fluentd/app-config"
  2024/05/30 09:49:31 config map updated
  2024/05/30 09:49:31 performing webhook request (1/1)
  2024/05/30 09:49:31 successfully triggered reload
  ```

* Also verify helm values using;
  ```sh
  $ helm get values logging 
  USER-SUPPLIED VALUES:
  fluentd:
    logLevel: debug
  ```

* Now switch back from `debug` to `info` logs using:
  ```sh
  $ helm upgrade logging /path/to/git-clone/charts/rancher-logging/104.0.0-rc1+up4.4.0 --set fluentd.logLevel=info
  ```

* Wait a few seconds, and you'll see the `fluentd-0` container emit debug logs. Debug logs have `[debug]` in them and show up when you switch log level from debug to info.
 
There's nothing else happening that causes debug logs to get generated after switching to `logLevel=debug` so you see debug logs only when switching the log level.

**Comment by pankajsqe** [comment]
Log level for fluentd has been added and working as expected for fresh installation of logging chart as well update logging chart.

Rancher : 2.9.0-alpha1
Cluster : v1.28.9+rke2r1
Logging chart : 104.0.0-rc1+up4.4.0

<img width="1725" alt="Screenshot 2024-05-24 at 7 44 28 PM" src="https://github.com/rancher/rancher/assets/149133120/d9e8ba81-f914-457a-b427-060707786f19">
<img width="758" alt="Screenshot 2024-05-31 at 9 11 34 PM" src="https://github.com/rancher/rancher/assets/149133120/cc34ae03-9c81-4013-bdaf-e13fd5165ede">
<img width="483" alt="Screenshot 2024-05-31 at 9 11 55 PM" src="https://github.com/rancher/rancher/assets/149133120/57023925-7e15-47e7-a5c8-2a24bd0e4a79">
<img width="754" alt="Screenshot 2024-05-31 at 9 12 18 PM" src="https://github.com/rancher/rancher/assets/149133120/9cc82fb7-e53b-48ad-b10c-30f8ac0cf1e9">
