### ISSUE TITLE
Global Registry - admin password is not upgraded after re-enable Global Registry

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20797]
Bug on Rancher: master
(All passwords here are random and for demonstration )

Steps:
- add EBS storage class
- enable GR for the first time, set admin password: NzfQ1Dd5lrLdTj27
- log in Harbor as admin user PASS
- docker login as admin user PASS
- open Harbor page to sign up a new account: testuser1 Abcd12345
- log in Harbor as testuser1 PASS
- docker login as testuser1  PASS
 
- disable GR
- wait for app and workloads being deleted
- re-enable GR with the same PV but a **NEW** admin password: 1Lo8VepiV72nq691
- log in Harbor as admin user **FAILED - password error BUT old password works**
- docker login as newuser1  **FAILED - password error BUT old password works**
- log in Harbor as testuser1 PASS
- docker login as testuser1  PASS

**Comment by gitlawr** [comment]
Regard it as expected.

This configuration is used on initialization.
>harbor_admin_password: The administrator's initial password. This password only takes effect for the first time Harbor launches. After that, this setting is ignored and the administrator's password should be set in the Portal. Note that the default username/password are admin/Harbor12345 .
https://github.com/goharbor/harbor/blob/608d7d5e78df8435b15dbfab8911e72397cd4d85/docs/installation_guide.md#required-parameters

When re-enabling using the same PV, the old password that persists in the database will be used.

**Comment by gitlawr** [comment]
When users choose existing PVC, we have no idea if the data exists or not.
I think we can add a description for the field about this.

**Comment by jiaqiluo** [comment]
@gitlawr  Thanks for the explanation, we definitely should notify users about this.

Could you confirm the following two cases are expected? 

1. If re-enable the global registry using the existing PVC, the admin password will be the old one

2. If re-enable the global registry using new PVC, the admin password will be the new one

**Comment by davidnuzik** [comment]
Is there no way we can handle this better? A description is nice so user is at least aware, but if we don't have a means to update password on existing PVC can't we flag this somewhere so when we re-enable with same PVC we do not ask for harbor admin password (ui somehow knows)? (and perhaps mention it's the same password as originally set) or something like that

**Comment by gitlawr** [comment]
@jiaqiluo @davidnuzik The expected cases are:
1. If re-enable the global registry using new PVC, the admin password will be the new one
2. If re-enable the global registry using the existing PVC, and there is **NO** initialized data in the PV, the admin password will be the new one
3. If re-enable the global registry using the existing PVC, and there is initialized data in the PV, the admin password will be the old one

And for case 2&3, it is hard to know if there is initialized data before enabling from our side.

**Comment by loganhz** [comment]
Yes, we know that. So we decided to just add a warning in admin password field

**Comment by jiaqiluo** [comment]
the bug fix is validated on Rancher: master with the latest version of the system-library chart

Now the UI shows the warning when re-enabling the global registry
<img width="1406" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/59541496-661ed700-8eb6-11e9-9c63-03f81077d140.png">
