### ISSUE TITLE
openstack cacert field is not coverted from a file path to field to an text input one

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#20792]
this field needs added like privateKeyFile and userdata

**Comment by alena1108** [comment]
Will be available in v2.2.5-rc2

**Comment by sangeethah** [comment]
Able to reproduce the issue with rancher server version - v2.2.4

Create an openstack node driver with cacert field.
Create a openstack cluster using this node driver.
Node creation fails with following error:

```Error creating machine: Error in driver during machine creation: open -----BEGIN RSA PRIVATE KEY----- ********* -----END RSA PRIVATE KEY-----: no such file or directory; Timeout waiting for ssh key```

With rancher server version - v2.2.5-rc3
Create an openstack node driver with cacert field.
cacert field is now a multiline input field.
<img width="467" alt="Screen Shot 2019-06-17 at 9 32 47 PM" src="https://user-images.githubusercontent.com/4266958/59653709-0d666d00-9148-11e9-8f28-d6d7d3ba3a53.png">


Driver machine call made by rancher server indicates that cacert gets passed as expected as file (inside /opt/jail/<cluster-id>) which has the correct cacert content set (as was passed from the multi line cacert field).

```
2019/06/18 04:08:28 [DEBUG] create cmd [create -d openstack --engine-install-url https://releases.rancher.com/install-docker/18.09.sh --openstack-flavor-name m1.small --openstack-image-name ubuntu16.04 --openstack-private-key-file /L2KTG3C3NQ --openstack-username admin --openstack-ssh-port 22 --openstack-ssh-user root --openstack-endpoint-type adminURL --openstack-domain-name Default --openstack-cacert /NWFVRFPHGU --openstack-tenant-id e****5 --openstack-active-timeout 200 --openstack-password 1****3 --openstack-ip-version 4 --openstack-keypair-name mytest1 --openstack-user-data-file /PPT3Q4ULUG --openstack-auth-url http://<ip>:5000/v3]
```
```
test5root@25d70eb5ae32:/opt/jail/c-6njzn# cat NWFVRFPHGU
-----BEGIN CERTIFICATE-----
*****
*****
-----END CERTIFICATE-----
```

**Comment by dramich** [comment]
@sangeethah Those steps look good to me.
