### ISSUE TITLE
Protect the required linux worker node in a windows cluster from windows workloads/deployments

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#20805]

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/62526733-6ca14d80-b86c-11e9-9412-a732e5e65af0.png)

@orangedeng sometimes I can see some linux pod failed to start up. But the toleration has been added. I have to remove and re-add them manually. Can you look at it, please?

**Comment by sowmyav27** [comment]
**Verified with latest master-head.**

Windows AWS node: `Windows_Server-1903-English-Core-Base-2019.08.16`
Linux Node: `18.04 Ubuntu LTS`

**Steps:**
1. Launch a custom cluster 1 etcd and control plane linux node, 1 worker linux node and 1 worker windows node.
2. Linux node docker - 18.09, Windows node docker - 19.03, k8s version - 1.15.3
3. when the cluster comes up `Active`, the nginx-ingress-controller pods are scheduled on etcd/ control plane node also. 

Nodes show this taint 
<img width="1060" alt="Screen Shot 2019-08-23 at 10 52 50 AM" src="https://user-images.githubusercontent.com/26032343/63614150-33205000-c597-11e9-96ee-dbb518541f7b.png">

**Comment by sangeethah** [comment]
Tested in latest master build
Create a linux cluster with 1 control plane , 1 etcd and 3 worker nodes.
nnginx-ingress-controller pods get scheduled only in the worker nodes as expected.

**Comment by sowmyav27** [comment]
Verified with latest master-head. - latest - commit id: `d2ebb03eabe8`
**Setup:**
```
Windows AWS node: `Windows_Server-1903-English-Core-Base-2019.08.16`
Linux Node: `18.04 Ubuntu LTS`
Linux node docker and Windows node docker - 19.03, k8s version - 1.15.3
```
**Steps:**

- Launch a custom cluster
- Register 1 etcd and control plane linux node
- Register 1 worker linux node
- Register 2 worker windows node.
- when the cluster comes up Active, the nginx-ingress-controller pods are scheduled on worker node of linux only
- Nodes show this taint

<img width="931" alt="Screen Shot 2019-08-29 at 10 31 32 PM" src="https://user-images.githubusercontent.com/26032343/63995368-1dd28680-caad-11e9-9af8-03b8d4044d6e.png">
