### ISSUE TITLE
etcd rolling backup naming scheme

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#20819]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

The new rolling backup naming scheme. When using rolling snapshots, the snapshot names are no longer meaningful. When passing in --once, I get a snapshot named '2019-06-07T23:05:09Z_etcd', which I can later use to parse and roll back to. With rolling snapshots, I get names like c-kk4hq-rl-2gd4z, ${cluster_id}-rl-${random-hash}. When we were using v0.1.17 rke, the rolling snapshots had the same naming scheme as the one-time snapshots. It would be nice to have the option to use the old naming scheme instead.

**Comment by phomein** [comment]
Would like to add that this is with a k8s version of v1.13.5-rancher1-3 and a rancher agent version of v2.2.4 for the k8s cluster, with the rancher cluster created using rke v0.2.4

**Comment by alena1108** [comment]
Can be tested with Rancher master build

**Comment by moelsayed** [comment]
Prior to this change, we had: 
- backup name in kubernetes: `c-6jc29-ms-w547c`
- backup filename on disk/s3, which is a zipped file: `c-6jc29-ms-w547c.zip`

As of this change, the backup name in kubernetes will remain the same. However, the backup filename on disk/s3 will contain and addition timestamp similar to the one used by rke cli, eg: `c-6jc29-ms-w547c_2019-07-17T14:59:27Z.zip`.

**Comment by sowmyav27** [comment]
### Verified on latest rancher:master-head
**Local backups on the UI are seen as below. `-ml-` - manual backups and `-rl-` is for recurring snapshots**
<img width="625" alt="Screen Shot 2019-07-23 at 10 36 26 AM" src="https://user-images.githubusercontent.com/26032343/61734059-01b52a00-ad36-11e9-9ab8-29bd1ad2ff24.png">

**On the node:**
<img width="614" alt="Screen Shot 2019-07-23 at 9 40 59 AM" src="https://user-images.githubusercontent.com/26032343/61734132-2dd0ab00-ad36-11e9-95b9-299df8aa8de4.png">

On doing a restore from snapshot(local), the file on the node, is unzipped, but is not deleted after. And when the restore happens from the same snapshot a second time, the unzipped file is overwritten. This is not the case with S3 snapshots, where there is no unzipped files(only zipped files exist in the S3 bucket)

Tracking this in another issue - https://github.com/rancher/rancher/issues/21710

**S3 backups on the UI are seen as below. `-ms-` - manual backups and `-rs-` is for recurring snapshots**
<img width="665" alt="Screen Shot 2019-07-23 at 10 36 37 AM" src="https://user-images.githubusercontent.com/26032343/61734170-3923d680-ad36-11e9-8972-be38287616a2.png">

**In the S3 bucket:**
<img width="1576" alt="Screen Shot 2019-07-23 at 10 41 20 AM" src="https://user-images.githubusercontent.com/26032343/61734242-6cfefc00-ad36-11e9-814d-f800e8a7f2aa.png">

**Comment by deniseschannon** [comment]
After this change, here are the names of the snapshots:

- rke cli - one-time snapshot: `rke_etcd_snapshot_2019-08-15T20:34:29+02:00.zip`
- rke cli - rolling snapshots: `2019-08-15T20:34:29Z_etcd.zip`
- backups taken from Rancher RKE clusters: `c-6jc29-ms-w547c_2019-08-15T20:34:29Z_etcd.zip`

**Comment by jacklozano** [comment]
Is there a way of customizing the rke cli - rolling snapshots naming scheme?  We have several rke deployed clusters and creating snapshots based on a timestamp alone makes it difficult to differentiate.
