### ISSUE TITLE
Backport: Unable to see project members after upgrade

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20825]
Backport rancher/rancher#20760

**Comment by alena1108** [comment]
The fix is available in v2.2.5-rc2

**Comment by davidnuzik** [comment]
Version: v2.2.5-rc2 (fresh install)
Version: v2.2.4 -> v2.2.5-rc2 (upgrade)

I can confirm that members are now seen with a fresh install or post-upgrade (from v2.2.4). Also, groups now show up (they didn't at all before in v2.2.4).
