### ISSUE TITLE
UI for Allow S3 Snapshot service to trust internally signed certs when talking to the S3 endpoint

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20829]
This ticket is for UI component of https://github.com/rancher/rancher/issues/19222 > we need to add one extra optional field in the snapshot configuration UI

@westlywright: @moelsayed worked on the backend part in case you have any questions.

**Comment by alena1108** [comment]
The backend support was merged to master

**Comment by sowmyav27** [comment]
Verified in rancher:master-head 

- Launch a minio server with Self-signed Keys and Certificates.
- Created a cluster, by configuring the minio server as S3 snapshot details and pass valid certs in `Custom CA Certificate` on the UI.
- take a snapshot. Snapshot will be stored in the minio server - created bucket.
- Restore from the snapshot, cluster gets restored successfully.
- Edit cluster, pass incorrect but valid certs in this field `Custom CA Certificate`
- Error message shows on the cluster - `Failed to validate cluster: invalid S3 endpoint CA certificate: data does not contain any valid RSA or ECDSA certificates`
- Edit cluster, leave the `Custom CA Certificate` blank. 
- take a snapshot - you will get this error in the rancher logs
```
2019/07/08 21:00:47 [WARNING] Failed to take one-time snapshot, exit code [1]: time="2019-07-08T21:00:46Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:sowmya-test, err:Get https://x.x.x.x:9000/sowmya-test/?location=: x509: certificate signed by unknown authority" 
```
