### ISSUE TITLE
Catalog/Apps: values.yaml preview blank in UI

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#20828]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Start process to create an app from the library, cert-manager works. You'll notice after filling out the form and click preview there is nothing there.

**Other details that may be helpful:**
It is populated when using the drop down to view a different file from the chart and then go back to values.yaml.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.4

**Comment by ekristen** [comment]
Verified on 2.2.4 -- seems to be just an initial render/load issue.

**Comment by davidnuzik** [comment]
Version: v2.2.4

Reproduced the issue. values.yaml is not rendered.

Version: master-head (8/6/19)

Values.yaml is now rendered in the UI:
![image](https://user-images.githubusercontent.com/45179589/62583602-b5a1d380-b865-11e9-8bbe-cbdf5fce45b3.png)

This works upon create app or upgrade without any issues. No JS errors.
