### ISSUE TITLE
Global Registry - S3 credentials are not validated when trying to enable global registry on rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20823]
**What kind of request is this:**
bug

**Steps to reproduce :**
on `rancher:master`
1. Navigate to Global Registry on Rancher UI.
2. Add an S3 bucket for Backend Storage for registry and external postgres and redis for DB and Redis configs. Give in incorrect creds for S3 like incorrect Accesskey/secret
3. Click on Save.
4. Global Registry is enabled successfully.
5. Errors seen on workloads - `global-registry-harbor-registry` when user tries to push an image to the Harbor registry

**Expected Result:** 
While enabling Global Registry, the validations of S3 should happen, like in the case of Postgres DB and Redis, where errors are seen in the workloads, when incorrect Postgress/Redis passwords are given.

**Actual Result:**
Global Registry is enabled successfully. Errors seen on workloads - `global-registry-harbor-registry` only when user tries to push an image to the Harbor registry.

**Comment by gitlawr** [comment]
The validation needs to be done on UI side
