### ISSUE TITLE
Istio CRDs are not removed after disabling Istio

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#20831]
rancher/rancher:master 7a23ff88

* Create a cluster
* Check for istio CRD in embedded kubectl
  * `kubectl get crd | grep istio | wc -l` 
  * returns 0
* Enable Istio and wait for it to be deployed
* Disable Istio
* Check for istio CRD in embedded kubectl
  * `kubectl get crd | grep istio | wc -l` 
  * returns 53

Expected:
The istio CRDs should be removed after istio is disabled

**Comment by guangbochen** [comment]
Link to https://github.com/rancher/system-charts/pull/62

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 66beb03f

* Create cluster
* Checked istio crd count before enabling istio:
  * `kubectl get crd | grep istio | wc -l` = 0
* Enable istio
* `kubectl get crd | grep istio | wc -l` = 23
* Disablio istio
* `kubectl get crd | grep istio | wc -l` = 0
