### ISSUE TITLE
[Windows] Error while trying to mount volume from Google Persistent Disk in a windows node

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20839]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Set up a GCE custom cluster with cloud provider set. Parameters to be set: 
```
cloud_provider:
  name: gce
  customCloudProvider: |-
    [Global]
    project-id=<your projcet ID, optional>
    network-name=<your network, optional if using default network>
    subnetwork-name=<your subnetwork of the above network, optional if using default network>
    node-instance-prefix=<your instance group name/your instance name specific prefix>
    node-tags=<your network tags, optional if not patching any tags>
services:
  kube-controller:
    extra_args:
      configure-cloud-routes: true
```
2. Register a Ubuntu 18.04 LTS - linux node - all roles
3. Register a Windows 2019 node - worker
4. For a cluster - Storage Classes - Add Storage class of type Google Persistent Disk
5. In a project--> Volumes --> Add a volume, and use the storage class created in the previous step.
6. Use this volume to deploy a workload - Windows type.

**Expected Result:**
The volume should mount successfully, and workload should get deployed successfully

**Actual Result:**
Error is seen while attaching volume in workload.
<img width="1426" alt="Screen Shot 2019-06-12 at 2 40 05 PM" src="https://user-images.githubusercontent.com/26032343/59389979-bfef9780-8d24-11e9-9631-11d28206335a.png">

**Note:** This works fine in a linux node.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher master - 06/12/2019
- Installation option (single install/HA): sinfle

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom - gce - cloud provider set

**Comment by sowmyav27** [comment]
Validated on latest master (06/14/2019) rancher version `8d2e572e`

While attaching the volume, we get the below error now. 

<img width="1444" alt="Screen Shot 2019-06-14 at 3 51 14 PM" src="https://user-images.githubusercontent.com/26032343/59542949-44751e00-8ebd-11e9-8f6a-a36cec73f509.png">

**Comment by thxCode** [comment]
You could not mount `ext4` file system type to Windows. Please follow the error message to try one of `FAT, FAT32, NTFS, exFAT, ReFS`.

**Comment by sowmyav27** [comment]
Verified with 2.3.0-alpha4
Able to mount/attach a GCE persistent disk to a GCE cluster with cloud config.

**Comment by sowmyav27** [comment]
Reopening this issue.
Verified on master-head latest -- commit id: `57cba5fec`

**Comment by sowmyav27** [comment]
verified with latest master-head.

Steps:
- Set up a GCE custom cluster with cloud provider set. Parameters to be set:
```
cloud_provider:
  name: gce
  customCloudProvider: |-
    [Global]
    project-id=<your projcet ID, optional>
    network-name=<your network, optional if using default network>
    subnetwork-name=<your subnetwork of the above network, optional if using default network>
    node-instance-prefix=<your instance group name/your instance name specific prefix>
    node-tags=<your network tags, optional if not patching any tags>
services:
  kube-controller:
    extra_args:
      configure-cloud-routes: true
```

- Register a Ubuntu 18.04 LTS - linux node - all roles
- Register a Windows 1903 node - worker - Windows Server version 1903 Datacenter Core and k8s version - 1.15.3
- For a cluster - Storage Classes - Add Storage class of type Google Persistent Disk
- In a project--> Volumes --> Add a volume, and use the storage class created in the previous step.
- Use this volume claim to deploy a workload - Windows type.

The error reported here is not seen anymore, but the below error is seen while attaching the volume claim.

**Error:**
```
Warning | FailedMount | MountVolume.MountDevice failed for volume "pvc-0xxxx33f6" : diskMount: format disk failed, error: exit status 1, output: "Format-Volume : Cannot validate argument on parameter 'FileSystem'. The argument \"ext4\" does not belong to the set \r\n\"FAT,FAT32,exFAT,NTFS,ReFS\" specified by the ValidateSet attribute. Supply an argument that is in the set and then try \r\nthe command again.\r\nAt line:1 char:180\r\n+ ... nDriveLetter -UseMaximumSize \| Format-Volume -FileSystem ext4 -Confir ...\r\n+ ~~~~\r\n + CategoryInfo : InvalidData: (:) [Format-Volume], ParameterBindingValidationException\r\n + FullyQualifiedErrorId : ParameterArgumentValidationError,Format-Volume\r\n \r\n
```
**Note:**
Creating a PV works fine.

- Create a PV in the cluster.
- Give the `Filesystem Type`: NTFS and `Persistent Disk Name`: <name of disk created in gce>.
- Go to Project --> Volumes --> Add Volume Claim. Add a volume claim, and select the PV created.
- Deploy a workload using this volume claim.
- Workload is deployed successfully. The volume is attached. And is accessible.

**Comment by loganhz** [comment]
Please try to specify the fs

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
 ····
 fsType: ext4
 ····
```


https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/plugins.go#L58

**Comment by sowmyav27** [comment]
### verified on `rancher:v2.3.0-rc5`

- Create a custom cluster with GCE nodes, and GCE cloud provider enabled. 1 Linux - all roles and 1 Windows worker node. (Windows enabled)
- Go to Cluster --> Storage Class and create a storage class through API from `http://<rancher-server>/v3/cluster/<cluster>/storageClasses/`

request:
```
Provisioner: kubernetes.io/gce-pd
paramaters: type: pd-standard and fsType: NTFS
```

- Navigate to a Project (Default) --> Volumes --> Add Volume Claim 
- Use the storage class to create a volume claim
- Go to Workload --> And deploy a workload using the created volume claim.
- Workload is deployed successfully.
- Volume is attached.
- Disk is created with the PVC created in GCE --> Disk page (backend GCE)
