### ISSUE TITLE
Error when drain worker via Rancher API 

### ISSUE THREAD

**Issue by dmlabs** [rancher/rancher#20832]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Drain a worker node via the Rancher API produces an error.  
There are two ways to reproduce it:

1)
When performed via the Rancher API UI (drain -> Show Request -> Send Request), the error says: "rancher.example.com says Error: parsererror", but the node DOES actually drain.

2)
When performed via CURL with the command from the Rancher API UI, for example:

```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"deleteLocalData":false, "force":false, "gracePeriod":-1, "ignoreDaemonSets":true, "timeout":60}' \
'https://rancher.example.com/v3/nodes/c-ab1234:m-abc1234567?action=drain'
```

The curl returns the following: "{"type":"error","status":"401","message":"clusterID does not match"}" and the node does NOT drain.

**Result:**
When performed via the Rancher API UI, the error says: "rancher.example.com says Error: parsererror", but the node DOES actually drain.

When performed via CURL, then curl returns the following: "{"type":"error","status":"401","message":"clusterID does not match"}" and the node does NOT drain.

I would expect the node to drain in both ways, without errors.  
Drain the Node on the Rancher UI (not API UI) with the menu "Drain" seams to work without an error.

**Other details that may be helpful:**
The worker node belongs to a Kubernetes cluster with 3 etcd, 2 control plane and 5 worker nodes.  
The cluster was deployed with the custom cluster option.  
Longhorn is also running in that cluster.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.2.4
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM (4 cores, 4 GB memory)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:11:19 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:59:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by axeal** [comment]
The `"{"type":"error","status":"401","message":"clusterID does not match"}"` response received when attempting to perform the drain by cURL is returned when using a Rancher API access that is scoped to a different cluster, than the one you are requesting an action on via the API. To fix this you should check to be sure you use an API access token scoped to that cluster, or can use an un-scoped access token.

I did reproduce the `Error: parsererror` when performing the request via the API browser, developer console tools show the request receives a 200 OK response, with an empty body, so it looks like there is an issue here with the API browser attempting to parse an empty response body.

**Comment by dmlabs** [comment]
I tried the same with a new access key with no cluster scope.  
With that access key, the curl command worked without errors:

```
curl -u "token-123ab:some-secret-key-with-no-scope" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"deleteLocalData":true, "force":true, "gracePeriod":-1, "ignoreDaemonSets":true, "timeout":60}' \
'https://rancher.example.com/v3/nodes/c-ab123:m-abc12345678?action=drain'
```

I then created another acces key with the scope for the cluster with the id c-ab123 but this time the curl command again showed the same error:

```
curl -u "token-123ab:some-secret-key-with-scope-for-clusterid-c-ab123" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"deleteLocalData":true, "force":true, "gracePeriod":-1, "ignoreDaemonSets":true, "timeout":60}' \
'https://rancher.example.com/v3/nodes/c-ab123:m-abc12345678?action=drain'
{"type":"error","status":"401","message":"clusterID does not match"}

I have only one cluster so it was not possible to mix up the acces keys and clusters.
Is it possible, that there is a bug while draining nodes with an access key with a cluster scope?

**Comment by dmlabs** [comment]
The Rancher support figured out, what i was doing wrong.  
An access key with a cluster scope works only for the v3/clusters/<clusterid> endpoint.  
As the endpoint for draining nodes is v3/nodes, the access key will not work.  
See also this issue: https://github.com/rancher/rancher/issues/18639#issuecomment-483428554

Case closed.
