### ISSUE TITLE
Feature Request - show the state of PVC in the volumes section

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20834]
Feature Request 

It is not easy to tell if a PVC is used by any pod and the name of the pod. Users can use `kubectl describe pvc` to get this info but it is not handy.

We should add this kind of information to the volume section under the project.

<img width="1432" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/59387477-1c9b8400-8d1e-11e9-9fbd-7c3c7def9f7b.png">

**Comment by loganhz** [comment]
Added in https://github.com/rancher/rancher/issues/22745
