### ISSUE TITLE
we need add some flag to kubelet

### ISSUE THREAD

**Issue by degilq** [rancher/rancher#20841]
we need add to Kubelet, the flags:

--anonymous-auth=false
--allow-privileged=false 

and I can't find the option on the rancher ui

**Comment by superseb** [comment]
This is covered in https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-add-additional-arguments-binds-environment-variables-to-kubernetes-components-in-a-rancher-launched-kubernetes-cluster

**Comment by amagura** [comment]
@superseb Is this not supported for non-rancher launched clusters?
