### ISSUE TITLE
Project members do not dynamically refresh

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#20846]
Hi, I created the user in the rancher to add the user to the corresponding project, but the UI will not be dynamically updated, I need to manually refresh

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4-ent-rc1` UI: `v2.2.70` |
|Route|`global-admin.clusters.index`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/20760
