### ISSUE TITLE
Re-enable istio app using native Helm will cause CRD already exists

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#20843]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Problem:**
The existing way of using Helm `crd-hook` to initialize istio CRDs will only work with our custom Helm version `v2.10.0-rancherx`, if a user chooses to use a vanilla Helm or if we revert the [rancher/helm #8213e9c73](https://github.com/rancher/helm/commit/8213e9c73d2e0f5a63ef9afd8431831bf06bfa55#diff-a483d6c0863082c3df21f4aad513afe2R121) changes in the future version bump,  the istio app will fail to install(if istio CRDs exist) and return the following error message: 
`Error: customresourcedefinitions.apiextensions.k8s.io "adapters.config.istio.io" already exists` 
Also, this is a known limitation of `crd-hook` of Helm with [#4440](https://github.com/helm/helm/pull/4440) and [#5054](https://github.com/helm/helm/issues/5054).

**Result:**
Ensure `rancher-istio` can be deployed/re-deployed with both rancher build-int Helm or native Helm.

**Comment by guangbochen** [comment]
https://github.com/rancher/system-charts/pull/62

**Comment by loganhz** [comment]
Refactored in istio 0.0.2
will be validated with https://github.com/rancher/rancher/issues/20831
