### ISSUE TITLE
Enable istio mixer policy by default

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20840]
Enable istio mixer policy by default

From https://github.com/rancher/rancher/issues/20738#issue-453754462

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/13/19)

I can confirm that now, by default, the Mixer Policy is Enabled.
![image](https://user-images.githubusercontent.com/45179589/59472619-ecbeb000-8df3-11e9-97a0-34bd146cfba7.png)

I double-checked javascript check on resources again as well (if have insufficient resources message appears at the bottom stating the minimum requirement for which we are lacking on the cluster).

I enabled Istio with the default settings, and ensured that the Mixer workload (istio-policy) was properly deployed including with custom cpu/mem limit/reservation. Edit Istio settings change these again and confirm workload gets recreated with the new limit/reservations.
