### ISSUE TITLE
Document that coredns is available as an option for k8s 1.12+ versions only

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20858]
CoreDNS was added as an optional provider in Rancher 2.2.x. There is one limitation that we have to document - CoreDNS is available for k8s 1.12+ versions only. If you try to use it for the earlier version of clusters, it is going to fail.

**Comment by deniseschannon** [comment]
Closing in favor of this docs bug: https://github.com/rancher/docs/issues/1578
