### ISSUE TITLE
Ability to set s3 backup path

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#20859]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Description**
It would be nice to have the ability to set the S3 backup path for etcd snapshots.

**Comment by alena1108** [comment]
https://github.com/rancher/rke/issues/1306

**Comment by sowmyav27** [comment]
verified on `rancher:master-head` (latest)

1. Create an aws cluster - 1 node.
2. Give in the S3 details.
3. `folder: "test"` parameter was given through the YAML file while creating the cluster.
4. Deploy the cluster.

Recurring snapshots and manual snapshots were successfully taken and stored in the folder in the S3 bucket.
