### ISSUE TITLE
Multi-cluster Apps - cannot get revisions

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20868]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- as a standard user, deploy the multi-cluster app mySQL with an old version v0.3.7
- wait for the app to be available 
- upgrade the app to the latest version, v0.3.8
- wait for the app to be available 
- click `Rollback`

**Result:**
- there are no revisions in the list 
<img width="1029" alt="Screen Shot 2019-06-13 at 3 17 27 PM" src="https://user-images.githubusercontent.com/6218999/59473115-cef24a80-8df5-11e9-828f-4eb251990e31.png">

**Other details that may be helpful:**
- the creatorID of the multi-cluster app is the same as the userID, but the creatorID of the revisions is NOT

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
Rancher: master on 6/13
- Installation option (single install/HA):
HA

**Comment by alena1108** [comment]
@kinarashah does the issue exist for MCA only, or regular apps as well?

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/20204

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher: master be3ae399

The same steps as the original issue's:
- as a standard user, deploy the multi-cluster app mySQL with an old version v0.3.7
- wait for the app to be available
- upgrade the app to the latest version, v0.3.8
- wait for the app to be available
- click Rollback

Result:
- see the revisions, and can choose one to rollback successfully 

<img width="1422" alt="Screen Shot 2019-06-24 at 10 25 06 AM" src="https://user-images.githubusercontent.com/6218999/60039132-e093e780-966a-11e9-93d5-777a45d6aa86.png">
