### ISSUE TITLE
Backport: Unable to set http_proxy config on Rancher notifier

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20867]
https://github.com/rancher/rancher/issues/17885

**Comment by alena1108** [comment]
Can be tested with rancher v2.2.5-rc3

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.5-rc5

* Deployed Rancher behind proxy
* Created custom cluster behind proxy
* Tested notifier without proxy URL
  * Test failed
* Tested notifier with proxy URL
  * Test passed
* Created alerts and saw them sent successfully through the proxy
