### ISSUE TITLE
[2.2 Backport] Snapshots will timeout when snapshot take longer to complete (when etcd contains a lot of data)

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20874]
Backport https://github.com/rancher/rancher/issues/19496

**Comment by soumyalj** [comment]
Tested with rancher version v2.2.5-rc3. 

Created Custom cluster with 3etcd only nodes, 1 control/worker node .
S3 Minio configuration was set for etcd backups

Exec into one of the etcd nodes. (The etcd nodes were 2core with 4G RAM)
for i in seq 1 1000; do cat testfile.out | etcdctl --endpoints=172.31.x.x:2379 put key; done
etcd was filled up to 1.8G
docker exec etcd etcdctl endpoint status --endpoints=172.31.x.x:2379 --write-out table
etcd was filled up to 1.8G

sudo docker exec etcd etcdctl endpoint status --endpoints=172.31.x.x:2379 --write-out table
2019-06-14 23:33:54.478207 W | pkg/flags: recognized environment variable ETCDCTL_ENDPOINTS, but unused: shadowed by corresponding flag
+-------------------+------------------+---------+---------+-----------+-----------+------------+
|     ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-------------------+------------------+---------+---------+-----------+-----------+------------+
| 172.31.13.52:2379 | 20982de1189c445c |  3.3.10 |  1.8 GB |      true |         4 |       4242 |
+-------------------+------------------+---------+---------+-----------+-----------+------------+

Snapshot was taken and it completed in around 5mins
Restore was also performed and it completed in around 6 mins

Other use cases tested for regression:
1. Snapshot restore using S3 minio configuration was tested and it was successful
2. Snapshot restore using S3 configuration was tested and it was successful
3. Created single node cluster with DO node. Snapshot was taken and restored. 
Two more etcd nodes were added and restore was performed . Restore was successful
4. Local back and restore was tested a few times and it was successful.

**Comment by junkiebev** [comment]
Should this maybe be _the_ v2.2.5 release and everything else pushed into v2.2.6? It's kinda... terrifying for lack of a better word?
