### ISSUE TITLE
Minor issue when launch app in v2.2.5-rc2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20871]
Version: v2.2.5-rc2
This is a minor issue

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- At the global level click on Apps and just before you create any Multi-Cluster app watch just above the Launch button and click launch

**Result:**
When you click on Launch you will see a red ribbon flash very briefly on the screen.
When you inspect the http traffic you will see that we made a GET request to get a generic svg icon but it was either canceled (in some cases) or was an HTTP 404
![image](https://user-images.githubusercontent.com/45179589/59474237-eb44b600-8dfa-11e9-8d04-55dd38a193e9.png)

![Screen Shot 2019-06-13 at 4 47 46 PM](https://user-images.githubusercontent.com/45179589/59474289-0c0d0b80-8dfb-11e9-93d7-6d01dd01cac4.png)

**Other details that may be helpful:**
This doesn't appear to hurt anything. And generic SVG icon for apps without icon still work fine. This doesn't appear to have any functional issues based on my testing in this area and general smoke testing around apps overall.
I don't think this should necessarily gate v2.2.5 release if it is not a very easy fix.

**Comment by davidnuzik** [comment]
I still observe the issue. Reopening.

**Comment by davidnuzik** [comment]
Additional: My app is missing the svg icon so this is breaking that icon sometimes.
![image](https://user-images.githubusercontent.com/45179589/62567618-672e0e00-b840-11e9-98b1-8a254bd55a46.png)

**Comment by davidnuzik** [comment]
@loganhz or @vincent99 is the svg icon not showing for the app related (or no and I should create a separate issue)? Thanks

Pictured is docker-registry app
![image](https://user-images.githubusercontent.com/45179589/62891119-c0db8000-bcf9-11e9-824d-bd3da1a9690b.png)

No browser dev console errors, no 404's or 500s

**Comment by loganhz** [comment]
@davidnuzik please file a new issue for it. Thanks!

**Comment by davidnuzik** [comment]
Created issue https://github.com/rancher/rancher/issues/22152 to track the svg icon issue. Looks like we might be blocking loading SVG icons (CORS).

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/13/19)

I followed my steps to reproduce and I no longer observe the issue. The error no longer briefly flashes on the screen when I launch my apps.
