### ISSUE TITLE
[2.2 Backport] CoreDNS as a supported default DNS provider for Rancher provisioned clusters

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20872]
Backport https://github.com/rancher/rancher/issues/20395

**Comment by alena1108** [comment]
Can be tested with v2.2.5-rc5

**Comment by sangeethah** [comment]
Run existing automation runs in 1.14 cluster to cover all automated test cases relating to networking and service discover.

Upgrade testing from K8s version 1.11/1.12 and 1.13 to k8s 1.14. In this case , as part of upgrade , we expect kube dns provider to be replaced with core dns provider.  We need to make sure that Service Discovery works as expected before and after upgrade for existing and new workloads and Service Discovery entries.

**Comment by jiaqiluo** [comment]
The following tests are done and passed on the upgrading path from Rancher v2.2.4 to v2.2.5-rc6

1. Rancher v2.2.4, add RKE cluster k8s 1.11, 1.12 and 1.13, check that the kubeDNS is deployed in the system project
2. add one more cluster k8s 1.13 and sets the DNS provider to kubeDNS in the config yaml, also check the kubeDNS is deployed 
3. Run pre-upgrade automation 
4. Upgrade Rancher to v2.2.5-rc6
5. Run post-upgrade automation. check that kubeDNS is still used in all clusters  
6. Upgrade each one of the RKE clusters to k8s 1.14
7. Check  coreDNS is used under the system projects
8. but for the one with kubeDNS fixed will not change to coreDNS even after upgrading k8s to 1.14
9. Run post-upgrade on each cluster

**Comment by jiaqiluo** [comment]
Update: The service discovery automation tests are done and passed on the above 4 clusters

The validation for supporting coreDNS is done, the issue is closed.
