### ISSUE TITLE
change the host roles

### ISSUE THREAD

**Issue by vincent927** [rancher/rancher#20877]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
i hava 3 nodes in cluster like this
![image](https://user-images.githubusercontent.com/10399425/59476808-08be6200-8e85-11e9-95d3-7203c0f9001d.png)
and i want to remove the node1 worker role, what can i do ?   
edit node1 label  node-role.kubernetes.io/worker=false ?
Will it affect the stability of my cluster?

**Result:**

**Other details that may be helpful:**

![image](https://user-images.githubusercontent.com/10399425/59476889-605ccd80-8e85-11e9-8da7-3c48a00253db.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA):singe

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/16703
