### ISSUE TITLE
Rancher CLI --debug flag does not show debugging information

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#20876]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
run `./rancher cluster`
run `./rancher --debug cluster`
run `./rancher --debug=true cluster`
run `RANCHER_CLIENT_DEBUG=true ./rancher cluster`

**Result:**
The first three commands produce the same output (no debugging information). The last command shows the API calls and responses. Would expect the `--debug` flag to show this.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
server v2.2.3, cli v2.2.0 (on MacOS)
- Installation option (single install/HA):
HA

**Comment by WMP** [comment]
Still open
