### ISSUE TITLE
Rancher only seems to create Public IPs for Layer 4 load balancers on AKS. Is there a way to create private ones without dropping to kubectl?

### ISSUE THREAD

**Issue by dbsanfte** [rancher/rancher#20886]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1) Create an AKS cluster in Rancher 2
2) Add some workload or other
3) Expose the workload via a Layer 4 Load Balancer

**Result:**
The load balancer is created with a public IP and is accessible over the internet.

**Is it possible to make Rancher/AKS create these load balancers only on the private VNet?**

I know you can do this via kubectl and YAMLs but I was wondering if it were possible to do it within the Rancher UI.

https://docs.microsoft.com/en-us/azure/aks/internal-lb

**Comment by superseb** [comment]
Ability to add annotations in UI were added in https://github.com/rancher/rancher/issues/15070, let me know if that doesn't work in this case.

**Comment by dbsanfte** [comment]
It does work, but it's a pretty bad user experience on AKS clusters to have to go into the hidden settings and add this. And given the default is to expose a cluster service directly to the internet it's a little bit dangerous too.
