### ISSUE TITLE
Feature flag UI Component

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#20885]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Description:**
create page for users to interface with the feature-flags feature

**Other details that may be helpful:**
need to consider schemas changing once a page has already been loaded

Backend Issue:
https://github.com/rancher/rancher/issues/20213

**Comment by deniseschannon** [comment]
Whenever we add in the UI, we need to make sure to do the docs: https://github.com/rancher/docs/issues/1573

**Comment by deniseschannon** [comment]
Original of #23184
