### ISSUE TITLE
"Import yaml " button should be disabled when HPA autoscaling/v2beta2 API is not supported in the cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#20887]
Version: Master

Steps
1. Create a GKE cluster or EKS cluster with K8s version 1.11
2. Navigate to HPA tab.

autoscaling/v2beta2 API is not available in these clusters and HPA will not be functional.
We should disable "Import yaml" button for HPA.

**Comment by loganhz** [comment]
First, users can deploy other resources here. It's not just for HPA.
Second, users should still be able to import HPA with v1 version or v2beta1 version API. We should not block them in this case.
