### ISSUE TITLE
[Feature Request] Azure China AKS Integration Support

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#20881]
AKS service is already launched in Azure China and some customers already use it. We need to support AKS service in Azure China, which includes:

1. Add China regions in location list of AKS creation page.
2. Call Azure China API endpoint when choosing China regions.
3. Test if there is any difference in API between Azure China and Global.

**Comment by kingsd041** [comment]
Version: master master-head (8/29/19)
Passed the following test cases:
1. Ensure that the cluster can be successfully created in `China North 2` and `China East 2`region
2. Create a workload in the cluster and create a nodeport to ensure access to the workload via nodeport
3. Ensure the L4 Balancer and storage class are available
4. Modify the cluster
