### ISSUE TITLE
Support Istio Gateway as first class resource in Rancher UI

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20892]
Support Istio Gateway as first class resources in Rancher UI

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: latest-2.3

* Gateway navigation tab is shown
* All Istio navigation tabs are shown
* Imported gateways appear in UI w/ correct values
* Created gateways are functional
* Gateway inputs match resulting CRD
