### ISSUE TITLE
Secret key returned on existing keys

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#209]
Server Version: v0.11.1

When creating the API key, there is a warning that this is the only time the API password will be shown. But if I click on the Edit button, the Edit API Key screen shows the password.

**Comment by vincent99** [comment]
The API shouldn't be providing the secret back to me except on create..

**Comment by hibooboo2** [comment]
Addressed and fixed in rancher/cattle#618

**Comment by deniseschannon** [comment]
Verified Fixed in v0.29.0-rc2
