### ISSUE TITLE
403 error when installing app

### ISSUE THREAD

**Issue by schurcht** [rancher/rancher#20905]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
(Install Rancher using quickstart guide)
Go into apps, and install anyone of them.

**Result:**
```
Failed to install app a-2zhfs. Error: UPGRADE FAILED: <html><head><title>Forbidden</title></head><body><h1>Forbidden</h1>Request was forbidden.</body></html> (get configmaps)
```
![image](https://user-images.githubusercontent.com/41570036/59561524-b5cde180-9021-11e9-8cc1-fbe0e22cf1ea.png)

**Other details that may be helpful:**
I'm running this as an administrator.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v.2.2.4
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM with 4 vCPU and 8GB of ram.
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by mrajashree** [comment]
@schurcht Were you trying to install the app at the global level (multi-cluster app) or is this in a project?

**Comment by schurcht** [comment]
@mrajaschree I tried both.
