### ISSUE TITLE
Add etcd and controlplane role to exising node

### ISSUE THREAD

**Issue by vistalba** [rancher/rancher#20904]
**What kind of request is this (question/bug/enhancement/feature request):**
bug
`Failed to reconcile etcd plane: Failed to add etcd member [etcd-node-1] to etcd cluster`

**Steps to reproduce (least amount of steps as possible):**
1. Create a Cluster with 3 etcd & controlplane nodes and 2 worker nodes
2. run some stuff
3. Edit cluster to flag one of the worker nodes for additional role etcd & controlplane
4. wait...

**Result:**
The cluster stucks with this error message (already waitet around 40 minutes in this state):
`Failed to reconcile etcd plane: Failed to add etcd member [etcd-node-1] to etcd cluster`

**Other details that may be helpful:**
If  I click edit again, disable etcd and controlplane on the worker node again everything looks fine. 

I want to add a 4th etcd to safely remove another etcd node after.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted vm datacenter ubuntu 16.04

**Comment by kinarashah** [comment]
Just to confirm, you didn't see any error while adding 4 etcd nodes? 1,3 or 5 etcd nodes are required to maintain etcd quorum and shouldn't have allowed adding this additional role to just one worker

**Comment by vistalba** [comment]
If I click for the 4th etcd node, the "1, 3 or 5" gets red and a message appear:
`Setting 4 etcd nodes is a waste of hardware because it doesn't increase the quorum until you have an odd number.`

I can save this configuarion normally and it starts with "updating cluster".

I'm aware that 4 etcd brings no benefit for me. I just want to replace one of the existing etcd nodes so i thought to add the 4th one before I remove one of the existing.

**Comment by kinarashah** [comment]
Gotcha, thanks for your reply. I am unable to reproduce this - able to add 4 etcd nodes to custom cluster

**Comment by vistalba** [comment]
Don't know what the problem is.
I now created a new cluster and there it works normal as discribed above.
The old cluster was haning on the step. I now migrated all workload and data to the new cluster and removed the old one.
