### ISSUE TITLE
Incorrect system images

### ISSUE THREAD

**Issue by zeronone** [rancher/rancher#20901]
Several images mentioned in https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/k8s_defaults.go (revision: https://github.com/rancher/types/commit/df0c8d4f7479ce0e194d7df55bfd6713262fd8f8) doesn't exist.

- quay.io/coreos/etcd:v3.2.24-rancher1
- k8s.gcr.io/defaultbackend:1.4-rancher1
- quay.io/coreos/flannel:v0.10.0-rancher1

**Comment by superseb** [comment]
Original tags will be added in https://github.com/rancher/rancher/issues/20765, see also https://github.com/rancher/rke/issues/1272
