### ISSUE TITLE
Question: OpenLDAP Support

### ISSUE THREAD

**Issue by willowandcreek** [rancher/rancher#2090]
Hi,

Is there any plans to allow OpenLDAP based access control? The current implementation is quite specific to AD since it uses the domain\user based credentials.

Thanks

**Comment by vincent99** [comment]
The defaults are for AD of course but the options for field names, values, etc were intended to support other schemas. We just have no idea what people's random schemas look like to know how well it will work in practice on not-AD.  Can you share yours?

I'm not sure if it actually does (@hibooboo2 ?) but the default domain should allow empty for logins that are not `domain\user`.

**Comment by willowandcreek** [comment]
Hmmm I am on Rancher 0.38.1 and it doesn't allow me to specify an empty value for default login domain. I get the error "Error (422 - MinLengthExceeded)"

**Comment by willowandcreek** [comment]
Oh and my schema is quite straightforward. I have a bunch of users of type inetOrgPerson and then a bunch of groups of type groupOfNames which contain a list of associated inetOrgPerson entries. I was hoping to be able to map the groups to environments in Rancher.

**Comment by willowandcreek** [comment]
Hi

Also would it be possible for the accountEnabled field to be optional as well? I have been trying to find an alternative field for it in openldap and seems like it is not doable without extending the schema and recreating my tree. So would be great if that field was optional as well. Thanks

**Comment by vincent99** [comment]
That seems reasonable.  Do you have some other kind of field for account status (e.g. a string?) that you'd want checked?

**Comment by willowandcreek** [comment]
Awesome! Actually any other kind of standard field such as a string or a standard integer works. It's just that a bit mask is a bit painful to extend on top of the inetOrgPerson schema. Plain integer or string works. So you guys can decide which one to use 👍👍 Thanks again

**Comment by vincent99** [comment]
What values would the integer have?  Because if it's 0 for disabled and 1 for enabled a bit mask of 1 would work today :-)

**Comment by willowandcreek** [comment]
Ouch. Didn't think of that haha. Will give it a try next week when am back at work n update again. Thanks for the idea :)

**Comment by willowandcreek** [comment]
Whoops, my bad. Won't be able to try it since the domain field isn't optional. Will wait for that to be made optional and then try. Thanks

**Comment by vincent99** [comment]
@hibooboo2 can you make domain optional please

**Comment by jangrewe** [comment]
+1 for being able to use OpenLDAP =)

**Comment by hibooboo2** [comment]
These two fields of `userEnabledField` and `defaultDomain` are now optional. When they are in a release I will Post a comment with the release info so that @willowandcreek can try to use openldap again.

**Comment by willowandcreek** [comment]
Awesome! Looking forward to the release. Thanks @hibooboo2 :+1:

**Comment by azmelanar** [comment]
Waiting for release :+1:

**Comment by akafrmn** [comment]
Cool, waiting for release :)  :+1: @hibooboo2

**Comment by jangrewe** [comment]
Did this make the cut for 0.41.0?

**Comment by deniseschannon** [comment]
Nope, this was not part of the release notes. When it's in the release, we'll make sure to add it to the release notes. :)

If you follow either github/rancher or the announcements category at forums.rancher.com, you'll get the release notes whenever we have a new release.

**Comment by jangrewe** [comment]
@deniseschannon Sorry for bothering you again, but is there any ETA for this change, or in which release it will make the cut? Thanks! :-)

**Comment by deniseschannon** [comment]
We are looking into the differences of AD and openLDAP as we speak, but we hope to have it out in a couple of weeks. Watch the release notes to see when it gets added. :)

**Comment by hibooboo2** [comment]
http://forums.rancher.com/t/openldap-support/843

**Comment by deniseschannon** [comment]
We have requested some information in our forums post linked above. If you could give us some feedback on the post, that'd be great.

**Comment by willowandcreek** [comment]
Posted the feedback @ http://forums.rancher.com/t/openldap-support/843/2?u=madhan.dennis :)

**Comment by hibooboo2** [comment]
rancher/cattle#1019 Has added this. No ui yet. and not in a release.

**Comment by Rhoa** [comment]
Hi, 

How to test this, I can beta test if you want .

**Comment by vincent99** [comment]
@Rhoa Support for the UI will be in the next release (v0.50).  If you really want to try it now you need to use the API to configure it, navigate to `/v1/openldapconfig`

**Comment by Rhoa** [comment]
@vincent99 Good Job all works fine :), access control work for group .
 I've try with last build-master this night, but there is  confusion with `domain` in API openldapconfig which matches with `search base` in UI.
It's possible to add in future a `search base` for group ? like ou=group,dc.... ?
