### ISSUE TITLE
`Manage Cluster Backups` cluster role is not sufficient to display and create backups

### ISSUE THREAD

**Issue by nazarewk** [rancher/rancher#20911]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. assign `Manage Cluster Backups` to user
2. create a snapshot
3. log in with that user
4. either of:
	- try to restore snapshot
    - go to `v3/clusters/<CLUSTER_ID>/etcdbackups`

**Result:**
backups list is empty even though there are backups

**Other details that may be helpful:**
it's simple enough
I don't know whether it affects other versions of rancher

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS EC2 instances
- Kubernetes version (use `kubectl version`): `1.13.5`

- Docker version (use `docker version`): `18.6.1`

**Comment by nazarewk** [comment]
Update: Owner of the cluster also does not allow listing etcd backups

**Comment by mrajashree** [comment]
@nazarewk Was the user created with the standard "user" global role or some custom role?

**Comment by mrajashree** [comment]
Users created with "User" global role won't face this issue.
I was able to repro this with a user created with a custom global role granting login access only. Basically any role except for the "User" global role will face this issue unless that role explicitly grants etcdbackups permissions.

**Comment by nazarewk** [comment]
User was created with `User Base` role so we have users that cannot create clusters by default.

**Comment by mrajashree** [comment]
Also found these issues:
1. Project members can view etcdbackups
2. Users with "user-base" role added to a cluster with Manage Backups role cannot create etcdbackups

Expected:
1. Only cluster members can view etcdbackups
2. Users with either "user" or "user-base" global role should be able to create etcdbackups if they are added to a cluster either as "owner" or with "Manage backups" role

**Comment by nazarewk** [comment]
@mrajashree any idea how can i grant permission to create backups on `2.2.6`?
Currently i've user that has `User Base` + following rules (created custom `GlobalRole` through kubernetest API on rancher cluster):
```json
{
  "rules": [
    {
      "apiGroups": [
        "management.cattle.io"
      ],
      "resources": [
        "etcdbackups"
      ],
      "type": "/v3/schemas/policyRule",
      "verbs": [
        "create",
        "get",
        "list",
        "update",
        "patch",
        "watch"
      ]
    }
  ]
}
```
And I still cannot

**Comment by mrajashree** [comment]
Based on discussion with @cjellick and @deniseschannon 
1. Manage backups role will allow "Snapshot Now" action, which creates etcdbackups, without checking for user's permissions for cluster update. This is because creating etcdbackup for a cluster without having update permission doesn't affect cluster state. Also there could be a use case for some bot added to a cluster only to take snapshots after certain changes and have no other permissions in the cluster otherwise.
2. But "Manage backups role" will not give permissions for "Restore Snapshot" action. Since this action actually updates a cluster, we will check for user's permissions on updating the cluster. Also user will require cluster update permission to take recurring snapshots via the "Recurring etcd Snapshot Enabled" setting on cluster config.

**Comment by sowmyav27** [comment]
### Reproduced the issue on `v2.2.7`

**Issue#1**
- For a user with `user-base` role, assign `Manage Cluster Backups` at the cluster level.
- Login as that user. 
- Etcd snapshots are not available for the user. And User is not able to take snapshots. Nor is he able to restore from any snapshot.

**Issue#2**
- Project member is able to view the snapshots available on the cluster level. 

### On master-head - commit id: `54432504`

**Scenario#1**
- For a user with `user-base` role, assign `Manage Cluster Backups` at the cluster level.
- Login as that user. 
- Etcd snapshots are seen available for the user. And User is able to take snapshots. 
- User is NOT able to restore from snapshots.

Scenario#2
- Project member is NOT able to view the snapshots available on the cluster level. 
- Project member is not able to take a snapshot
