### ISSUE TITLE
Metadata keyspace collision with two different copies of a stack

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2091]
If you create two copies of a stack with the service names the same, you can not traverse /service/<name>. You end up with the last service created it appears.

To reproduce create two stacks from the same docker-compose.yml file. Then query metadata from inside one of the containers for the service name.

**Comment by sangeethah** [comment]
Tested with latest build from master:

When there are services with same name that exists across multiple stacks, http://rancher-metadata/latest/services/ will still return one of the services with the matched name. But now we have a way to uniquely fetch the service details by name using http://rancher-metadata/latest/stacks//services/.

In this case I have a service named - "test1" in 2 stacks -> "Default" and "new".

```
root@a654ff2e44d7:/# wget --header="Accept:application/json" http://rancher-meta
data/latest/stacks/new/services/test1  

{"create_index":4,"expose":[],"external_ips":[],"fqdn":null,"hostname":null,"kin
d":"service","labels":{"io.rancher.container.pull_image":"always"},"links":{},"m
etadata":{},"name":"test1","ports":[],"scale":3,"sidekicks":[],"stack_name":"Default"}


root@a654ff2e44d7:/# wget --header="Accept:application/json" http://rancher-meta
data/latest/stacks/new/services/test1  


{"create_index":1,"expose":[],"external_ips":[],"fqdn":null,"hostname":null,"kin
d":"service","labels":{"io.rancher.container.pull_image":"always"},"links":{},"m
etadata":{},"name":"test1","ports":[],"scale":1,"sidekicks":[],"stack_name":"new"}

```
