### ISSUE TITLE
Include container security scanner

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20928]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description:**
Include container security/serviceability scanner such as Falco/Aqua to perform container run time/data at rest scanning.

This addon feature will enhance Rancher as a complete package as a complete solution for hosting kubernetes

**Rancher version:**
2.2.x

gz#4755

**Comment by pjbgf** [comment]
Not sure this is still relevant, since NeuVector is available through the Apps & Market Place.

![image](https://github.com/rancher/rancher/assets/5452977/869dc2bf-4753-41e0-a95b-83073048000f)

**Comment by pjbgf** [comment]
We haven't received any updates on this issue in a while, so we're closing this issue for now.

Feel free to reopen it if you have any further questions or if there's new information to add.
