### ISSUE TITLE
Rancher support on Linux on IBM Power Systems

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20929]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Description:**
We are planning to run kubernetes clusters on IBM Power Platform (architecture: ppc64le) with SuSE or RHEL Linux along with Docker. 

Currently Rancher cannot orchestrate a k8s environment using IBM power platform (ppc64le) hosts.

Operating systems SuSE/RHEL and Docker container engine is already available and supported for IBM power ppc64le architecture.

Requesting Rancher to consider supporting IBM platform to run/orchestrate kubernetes on the power platform.

We do not require the Rancher manager support on the Power platform, we are looking for support for the Rancher agent and the required ancillary containers that help orchestrate the k8s cluster.

**Rancher version:**
2.2.x

gz#4756

**Comment by dnoland1** [comment]
This is related - https://github.com/rancher/rke/issues/988

**Comment by MrBr-github** [comment]
Any updates/progress on ppc64le support ?

**Comment by hutchins** [comment]
It's been a year. Any updates/progress on supporting PPC64le?
