### ISSUE TITLE
Service with global deployment strategy: add max_count and odd_count

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2092]
Global deployment strategy for the service means that service will end up having one instance deployed per host in the system. We should add a cap to number of instances deployed. So say you define a service with strategy=global and max_count=2. It means that when there are 3 hosts in the system, only 2 of them will get service instances deployed.

Also need to add odd_count parameter. If specified along with global flag, odd number of instances will get deployed. For example, if there are 10 hosts in the system, only 9 instances will get deployed.

@ibuildthecloud ^^

**Comment by vincent99** [comment]
Unless you're worried about the case where there's only one host, isn't this just scale=2 and anti affinity to self?

**Comment by alena1108** [comment]
@vincent99 unfortunately scale=n and antiaffinity solution won't work when number of hosts in the system is < n: the service will fail to deploy in this case. While in case where global=true, max_count=n, hosts<n service will get deployed regardless as n in this case is the optimum.

**Comment by vincent99** [comment]
Yeah that's what I meant by "the case where there's only one host", specialized to the example from `n` hosts :smile: ..

I just think it's weird that this is called "global" at all.  It seems to me like it should be a "soft scale" modifier to say "...but allow less than that if there are no more eligible hosts right now" on the regular scale value.  Same for "always odd", though that could be used with global or a scale.

Maybe "soft scale" could even be on by default, and then as long as at least one container is running services can go to active.  This would help the issue where people say scale=42 but there are only 41 eligible hosts not spin on updating forever, and the UI could show 'desired scale is 42, but only 41 can currently be created".

**Comment by alena1108** [comment]
@vincent99 I like the soft scale idea, but I think we should still keep our original "hard" scale behavior in case user has a requirement for the particular number of service instances.

I agree that max/soft scale shouldn't be tight to global flag only.

**Comment by alena1108** [comment]
@ibuildthecloud do we still need this feature?

**Comment by alena1108** [comment]
This one is resolved with the scale policy. You can setup a maxCount and the interval to workaround the oddCount

**Comment by sangeethah** [comment]
@alena1108 , is this scale policy feature we have from v1.1.0? This has min/max/increment. We dont have any interval here. Wanted confirmation, that we are not planning to address anything with respect to odd_count parameter.
