### ISSUE TITLE
Intermittent Websocket Issues with Publicly Signed Certificate

### ISSUE THREAD

**Issue by aeekayy** [rancher/rancher#20934]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Deploy Rancher using RKE. Install Helm and Tiller. Install Rancher using Helm chart as highlighted here (https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/). Install Rancher with self-signed certificate then replace with public CA provided certificate. We updated the tls-rancher-ingress secret within the cattle-system namespace. This was done since we have a certificate available from Entrust. We placed the entire chain within tls.crt and the certificate key under tls.key. 

**Result:**
We're experiencing inconsistency when using Rancher. At times, we see a growl message in the Rancher UI that states the following: 
```
Error
Get https://172.20.0.1:443/api/v1/namespaces?timeout=30s: waiting for cluster agent to connect
```
In addition, in our browser (we are using Chrome), we are seeing the following from time to time in our console window:
```
WebSocket connection to 'wss://rancher.iocip.com/v3/projects/c-d7p9p:p-vgrw4/subscribe?sockId=135' failed: 
```
It appears as though the certificate that we have installed is having trouble, especially with websockets. We're not sure why we're getting inconsistent results. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:v2.2.4
- Installation option (single install/HA):
Single node behind a NLB (AWS)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
AWS, single node cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud, 4 vCPU, 8GB RAM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Docker version 17.03.3-ce, build e19b718
```

**Comment by superseb** [comment]
The Helm chart has options for certificates, if you want to change certificates (which has side effects as described in https://github.com/rancher/rancher/issues/14731) you need to upgrade the chart with the correct settings and not manually change created resources.

Regarding `waiting for cluster agent to connect`, the logs of the cluster agent will help here which can be retrieved using `kubectl -n cattle-system get pods -l app=cattle-cluster-agent -o wide`.

Also the template specifies single install behind NLB while you describe HA install

**Comment by aeekayy** [comment]
@superseb I have tried installing the Helm chart with the appropriate values. However, the certificate doesn't take. I create the secret tls-rancher-ingress in the cattle-system before installing the Helm chart with the appropriate values. I've tried reinstalling Rancher about 4 times with different configurations and I'm getting the same result. 

Here is the output of that pod: 
```
ubuntu@rancher:~$ kubectl -n cattle-system get pods -l app=cattle-cluster-agent -o wide
NAME                                   READY   STATUS             RESTARTS   AGE     IP           NODE             NOMINATED NODE   READINESS GATES
cattle-cluster-agent-f9754fc6b-kxr8t   0/1     CrashLoopBackOff   841        5d17h   10.42.0.69   10.210.148.113   <none>           <none> 
```
Here are the logs from that pod: 
```
INFO: Environment: CATTLE_ADDRESS=10.42.0.69 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-f9754fc6b-kxr8t CATTLE_SERVER=https://rancher.iocip.com
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local ec2.internal options ndots:5
ERROR: https://rancher.iocip.com/ping is not accessible (Failed to connect to rancher.iocip.com port 443: Connection timed out)
```
The logs are inconsistent. At times, you'll see that the cattle-cluster-agent pod is healthy for a period of time. However, with one timeout, you see the above.

**Comment by aeekayy** [comment]
Also, the installation is a single node behind a NLB. It is not HA

**Comment by superseb** [comment]
Can you please share the exact commands and configurations used in your setup? Half of the current text is about HA install with replacing certificates while it is a single install behind NLB.

If it's single install I guess you are talking to a custom cluster with kubectl which has the cattle-cluster-agent in CrashLoopBackOff? We have quite a few troubleshooting steps documented at https://rancher.com/docs/rancher/v2.x/en/troubleshooting/, that will help narrow down a possible cause.

**Comment by aeekayy** [comment]
@superseb here are the full steps. We have several Kubernetes clusters managed in Rancher so that may be where the confusion is coming from. 
1. Create the single instance Kubernetes instance using RKE
rke-config.yml
```
nodes:
  - address: 10.12.74.83
    internal_address: 10.12.74.83
    user: ubuntu
    role: [controlplane,worker,etcd]
    ssh_key_path: ~/.ssh/sshkey.pem

dns:
    provider: coredns
    upstreamnameservers:
    - 10.12.183.37
    - 8.8.8.8
```
Here's the command that we used to install Kubernetes:
```
rke up --config ./rancher-cluster.yml
```
2. Helm was setup with the Helm instructions. We installed with RBAC. 
3. Install the public certificate as a secret using the following:
```
kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key
```
4. We install Rancher with the following values
```
hostname: rancher.iocip.com
ingress:
  tls:
    source: secret
  extraAnnotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
```
Here's the command used:
```
helm upgrade rancher rancher-stable/rancher --namespace cattle-system --values rancher-values.yaml
```
5. Placed an NLB in front of the instance in AWS and updated DNS record. 
To answer your question, the single install is where we're seeing the CrashLoopBackOff error on the same host. I'll work through the troubleshooting steps. To see if I can narrow down the possible cause.

**Comment by aeekayy** [comment]
So to clarify, the Rancher local Kubernetes instance is the one experiencing issues with cattle-cluster-agent. All imported Kubernetes clusters are running cattle-cluster-agent alright right now.

**Comment by aeekayy** [comment]
Any updates on this? I've tried the troubleshooting but I've found no new information or any details that pop out to me that may help.

**Comment by superseb** [comment]
What is the status of all pods in the `kube-system` namespace? Is that single host able to connect to the URL? Is it only affecting one pod or multiple? If you run a pod yourself, can it connect or do you get the same error?

**Comment by superseb** [comment]
Let us know if this still needs help.
