### ISSUE TITLE
Rancher 2.2.x Node Template AWS cloud provider kubelet proxy setting

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#20938]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug?
How to use node template in Rancher to set up kubelet proxy setting ?

**Steps to reproduce (least amount of steps as possible):**
AWS in proxy environment  (VPN set up with AWS Direct connect to company network)
Create node template with AWS provider
Engine Environment:

- http_proxy: http://proxy:8080
- https_proxy: http://proxy:8080
- no_proxy:  localhost,127.0.0.1,169.254.169.254

AMI: RancherOS (rancheros-v1.5.1-hvm-1 - ami-0829d74b9ed70cb7a )
Update /etc/resolv.conf to correct nameservers 
Create cluster in Rancher 2.2.x, add new node using node template
**Result:**
A new node provision in AWS, but Kubelet failed in Health check and go into crash loop

[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.100.138.22]: Get https://localhost:10250/healthz: dial tcp [::1]:10250: connect: connection refused, log: I0618 03:53:17.586597 4417 aws.go:1007] Zone not specified in configuration file; querying AWS metadata service]

**Other details that may be helpful:**
**No proxy setting for kubelet**
 docker inspect kubelet | grep proxy

**Run curl inside kubelet container**
curl -sSL https://ec2.ap-southeast-2.amazonaws.com/
Timeout

**Login RancherOS**
**with proxy enabled**
[rancher@middleware-rancher1 ~]$ wget -Y on https://ec2.ap-southeast-2.amazonaws.com/
Connecting to proxy:8080 (10.137.234.224:8080)
wget: tls error at line 803 cipher:0000
wget: error getting response: Connection reset by peer

**proxy disable**
[rancher@middleware-rancher1 ~]$ wget -Y off https://ec2.ap-southeast-2.amazonaws.com/
Connecting to ec2.ap-southeast-2.amazonaws.com (54.240.195.243:443)
wget: can't connect to remote host (54.240.195.243): Connection timed out

**kubelet log**

I0618 01:48:28.871807    6872 aws.go:1007] Zone not specified in configuration file; querying AWS metadata service
F0618 01:50:29.145579    6872 server.go:261] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0b7ceadcbb50f5ecf: "error listing AWS instances: \"RequestError: send request failed\\ncaused by: Post https://ec2.ap-southeast-2.amazonaws.com/: dial tcp 99.82.185.0:443: i/o timeout\""

**docker info**
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 2bb99b3d44a1de2769866941e698f93f540b910c (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.85-rancher
Operating System: RancherOS v1.5.1
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 985.8MiB
Name: middleware-rancher1
ID: 5GO5:EFES:BS64:NXXS:EKTH:BIDQ:AOIW:D7UT:YNZZ:ZWWF:QZCI:CJFG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://proxy.auiag.corp:8080
HTTPS Proxy: http://proxy.auiag.corp:8080
No Proxy: localhost,127.0.0.1,169.254.169.254
Registry: https://index.docker.io/v1/
Labels:
 provider=amazonec2
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by superseb** [comment]
See https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file and https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/#extra-environment-variables to set environment variables for k8s components. Let me know if that doesn't solve the issue.
