### ISSUE TITLE
Show version and app version for Istio system chart

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#20932]
rancher/rancher:master

When enabling istio, both the version and the app version should be shown. Currently only the the version is shown - `0.0.1`, which does not make clear that Istio is using a different version. 

* Create a cluster
* Navigate to Enable Istio screen
* Version shows `0.0.1`

Expected:
* Version shows `0.0.1` (or current system chart version) and the App version (Istio version) shows the correct Istio version

**Comment by guangbochen** [comment]
this is a UI related fix, the chart should already contain the istio version with `1.1.5-rancher1` from the external, can we update to it accordingly thanks.

**Comment by loganhz** [comment]
We changed it back to `0.0.1` as `1.1.5-rancher1` is not a standard version style in Helm concept.

Maybe we need to use a label or something for istio info

**Comment by deniseschannon** [comment]
@loganhz this should correspond with the fact that we shouldn't pin versions in the backend and should show the versions. For istio specific, we should figure out how to show the chart version (0.0.1) as well as the app version (istio 1.2).

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 66beb03f

* Create cluster
* Enable Istio
* Istio version selector displays both the chart version, and the istio version

<img width="203" alt="Screen Shot 2019-07-30 at 11 40 18 AM" src="https://user-images.githubusercontent.com/21316915/62156044-1443dc00-b2bf-11e9-9902-1f3fde0057d1.png">
