### ISSUE TITLE
[UI] Windows Support - List all the limitations for Windows containers

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20940]
There are a lot of limitations for Windows containers and clusters.

https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#limitations

Show doc link for all the limitations for Windows containers in deploy workload page

**Comment by davidnuzik** [comment]
Version: master-head (8/2/19)

Now if i create a cluster that has windowsPreferedCluster: true (new clusterconfig param). I get a notice about Windows containers limitations in the UI when attempt to create a workload:

![image](https://user-images.githubusercontent.com/45179589/62400199-39d91b80-b533-11e9-85f2-a0c036b1d687.png)

I like the idea of this so users are less likely to run into any issues. I was confused however, why can I not pick HostPort anyway? What if my workload is for linux only and I schedule to a linux node? Does this disabled item go away then?

![image](https://user-images.githubusercontent.com/45179589/62400247-6c831400-b533-11e9-8bf9-9ce712e08772.png)

**Comment by davidnuzik** [comment]
@loganhz just had a quick question, reference my last comment, the last paragraph and picture. Is it expected that HostPort is hidden? I would have expected if my workload is to be scheduled on a linux worker node I should still be allowed to do this? or no?
Thanks

**Comment by loganhz** [comment]
@davidnuzik Per Will, we don't need to think the case for linux users in the Windows cluster. Users who are using Windows cluster only care Windows stuff.

Option 1: Allow users to select HostPort as we already have a warning. So if users really want to deploy a workload for linux in UI, they still can do it.

Option 2: Always hide the HostPort in Windows cluster.

Which option do you like?

**Comment by davidnuzik** [comment]
@tfiduccia what do you think about the above? (last 3 comments)

**Comment by davidnuzik** [comment]
@loganhz after discussion offline with Tani, do you think we could consider Option 1? If we do this we would allow selection of it; would be ideal to tweak the warning message accordingly.

**Comment by loganhz** [comment]
Sure. What’s the warning message should be?

**Comment by davidnuzik** [comment]
@loganhz honestly looking at it again it can probably stay the same. My bad :)

**Comment by davidnuzik** [comment]
Reference my last command for majoriting of testing steps: https://github.com/rancher/rancher/issues/20940#issuecomment-517852135

Version: master-head (v2.3) (8/14/19)

I can now confirm we have added back in the ability to pick "Host Port" from the dropdown when configuring port mapping for a workload on a cluster that has windows nodes.

![image](https://user-images.githubusercontent.com/45179589/63061612-8fee7d00-beaa-11e9-9ecd-a3704ca570d1.png)

This worked as expected. The original concern was that if we have a workload and want to schedule say only for a linux node we should still be able to do this. The user is taking on risk if they misconfigure, but we should allow them to pick the option if they so wish. We can do this now. (The warning is sufficient).
