### ISSUE TITLE
Default Ingress Controller Daemonset Should Use ClusterFirstWithHostNet

### ISSUE THREAD

**Issue by rajha-korithrien** [rancher/rancher#20950]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Deploy Rancher v2.2.4 in HA and ensure that it has a working nginx-ingress-controller

**Result:**
The daemon set that deploys the nginx-ingress-controller pods has the following in its configuration
```
dnsPolicy: ClusterFirst
hostNetwork: true
restartPolicy: Always
```
However Kubernetes docs state
```
For Pods running with hostNetwork, you should explicitly set its DNS policy “ClusterFirstWithHostNet”.
```
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

This current behavior can cause a problem if an ingress object specifies an annotation that causes it it need to use a cluster dns address for example an auth-url:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chc
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://authelia.coq.svc.cluster.local:9091"
```
Causes the error (in the logs of one of the nginx instances):
```
2019/06/18 16:37:23 [error] 11720#11720: *24849 authelia.coq.svc.cluster.local could not be resolved (3: Host not found), client: w.x.y.z, server: chc-coq.primary.a.b.c.d, request: "GET / HTTP/2.0", subrequest: "/_external-auth-Lw", host: "chc-coq.primary.a.b.c.d"
```
Notice that the internal cluster DNS name can not be resolved, even though it is known to be good by using nslookup on a pod that is configured with ```hostNetwork: false```
```
/$ nslookup authelia.coq.svc.cluster.local
Name:      authelia.coq.svc.cluster.local
Address 1: 10.43.9.76 authelia.coq.svc.cluster.local
/$
```
Changing the dnsPolicy to ```ClusterFirstWithHostNet``` in the nginx-ingress-controller daemon set and redeploying all the pods fixes the issue.

**Other details that may be helpful:**
It seems this is not the only place where the incorrect dns policy is used. The cattle-node-agent also has the same issue #16757

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA):
HA install & clusters deployed via the UI

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
RKE cluster created via the Rancher UI
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Bare metal, RancherOS v1.5.1, Intel(R) Xeon(R) CPU E7- 2860  @ 2.27GHz, 512GB
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:43:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:51:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by unki** [comment]
Have hit a similar issue with _ingress-nginx_ v0.32.0 on Rancher v2.4.5.
In my case related to _ingress-nginx_ failing to lookup a service-resource using _ExternalName_.

As deployed initially by Rancher, _ingress-nginx_ with `hostNetwork: true` (and default) `dnsPolicy: ClusterFirst`) failed to lookup an cluster-internal DNS record. As it was relying up on the host's _/etc/resolv.conf_:

```
bash-5.0$ cat /etc/resolv.conf 
nameserver 213.133.x.x
nameserver 213.133.y.y
nameserver 213.133.z.z
options timeout:5 attempts:1
```

after changing _ingress-nginx_ StatefulSet to `dnsPolicy: ClusterFirstWithHostNet`, _/etc/resolv.conf_ was correctly populated with the CoreDNS server.

```
bash-5.0$ cat /etc/resolv.conf 
nameserver 10.43.0.10
search ingress-nginx.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```
