### ISSUE TITLE
[gdapi-python] 

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2095]
why the name? Is there some association with Go Daddy? Is this library a supported part of Rancher?

Oh, and do you have some code examples for a python noob?

**Comment by vincent99** [comment]
Indirectly yes, the [api-spec](http://github.com/rancher/api-spec) and a couple clients were [open-sourced](https://github.com/godaddy/gdapi-python) while some of us worked there.  There's no particularly good reason our fork hasn't been renamed.

As far as examples, we use it for all the [validation-tests](https://github.com/rancher/validation-tests).  Closer to a 1.0 release we will be working on cleaning up the API, writing proper docs, getting started, more client languages, etc.

**Comment by deniseschannon** [comment]
@eebjr Please feel free to re-open if you have more questions.
