### ISSUE TITLE
[HPA] Active, then Pending (with error) then Active again if create workload then somewhat quickly create HPA

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20955]
Version: v2.3.0-alpha4
Version: master (v2.3) (6/18/19)
This has been an issue since introduction of HPA in Rancher. We are getting expected errors from kubectl. What we are concerned about is the user experience in the UI.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a new workload and set CPU and memory reservation
- Within 20 seconds (a reasonable amount of time), create an HPA for this new workload (Resource type, either CPU or Memory, either Average Utilization or Average Value, any value)

**Result:**
HPA is initially in Active state, then Pending state with "error" transition (Red Pending state in UI due to API), then 10-60 seconds later everything is fine and it is back in the Active state again.

_This causes user confusion with the Red Pending (error) state seen in the UI. Also, it's confusing that it's Active at first then after a moment in Pending then back to Active. We expected to not see it in Active state at first._

We see in the API while Pending:
```
 "state": "pending",
"transitioning": "error",
"transitioningMessage": "the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from resource metrics API",
```
While it is in the Pending state so the UI shows this as a red colored state implying there is an error. This is an expected message (k8s annotation on HPA object) when you first set up an HPA and query it before it is actually ready.

UI screenshots:

Add HPA, is Active at first:
![image](https://user-images.githubusercontent.com/45179589/59710890-c9627f00-91be-11e9-8863-e3e55d7860d8.png)

Several seconds later goes to Pending state and is red (error transition):
![image](https://user-images.githubusercontent.com/45179589/59710918-dd0de580-91be-11e9-811a-3c11eda38a63.png)

Then get a second error shortly thereafter:
![image](https://user-images.githubusercontent.com/45179589/59710954-edbe5b80-91be-11e9-8ed5-5175908f4244.png)

Then error will eventually go away and everything is fine:
![image](https://user-images.githubusercontent.com/45179589/59710974-fca50e00-91be-11e9-8f09-a9479ca2462c.png)

**Other details that may be helpful:**
The HPA will be in transitioning "error" state always. It does not matter if you wait for the workload to fully be Active (ready) or not. It does not matter if you wait a few minutes after deploying the workload or not.

This _seems_ to be normal k8s expected behavior... If we create a workload and quickly create and HPA and then query the HPA object so quickly after creating it it's not ready right away so will show this error in its annotations.

As such, the current behavior we see in the API and hence the UI is expected... but it's not awesome that the API is showing this in error state so quickly and would be nice to prevent this initially if possible I think... This is because in the UI we will always see the Pending state in red and red text implying there is an actual error that needs the user to review and fix...

**_The issue does NOT happen if you create a workload and wait for 1-2 mins, then eventually create HPA._** You might have to wait as little as 30 seconds, but I imagine most users fairly quickly creating an HPA right after creating a deployment.

**Environment information**
HA setup with v2.3.0-alpha4
Both HA and Single-node rancher are affected (does not matter)

**Comment by davidnuzik** [comment]
In my opinion this should not block alpha release, but is a nice to have for v2.3 release if this is a reasonable ask. We are basically getting expected behavior here -- kubectl will show the object is not ready when you create a workload then create HPA within 20 or so seconds (not an unreasonable amount of time).

Just would be nice if we could avoid the red Pending state in the UI somehow in my opinion. This is going to confuse people and make them think something is indeed wrong when there is nothing really wrong.

**Comment by orangedeng** [comment]
The root cause for this error is the hpa handler in controller manager can't get pod any metrics from metrics server. This error would happen when the pod is newly created or the metrics server is messed up. So I think we still need to show the errors until the condition `AbleToScale` condition is true.

**Comment by loganhz** [comment]
@orangedeng noticed 2 issues in master build.

- HPA got stuck in initializing state after creating it. I have to refresh the browser to see the current status.
- HPA shows as active. But it says `The desired replica count is increasing faster than the maximum scale rate` in transition states sometime.

**Comment by orangedeng** [comment]
The second problem is referred to this issue https://github.com/kubernetes/kubernetes/issues/49256

**Comment by orangedeng** [comment]
The first issue fixed in this PR https://github.com/rancher/rancher/pull/21897.

**Comment by orangedeng** [comment]
The second issue only happens in HPA resource is cpu and the target workload's cpu is zero. So we should not set state to error when the condition `ScalingLimited` is true.
Fixed in this PR https://github.com/rancher/types/pull/929

**Comment by orangedeng** [comment]
The metrics server needs time to calculate cpu metrics for newly created workload. So there is a small time that the HPA controller of controller manager can't calculate the expected replica count for that workload base on the cpu metrics. And the condition `ScalingActive` of this HPA will be set to false during this time. Then the state of HPA becomes error. I think it is acceptable because it only happens in newly created workload.

**Comment by loganhz** [comment]
@davidnuzik without the fix, even for not newly created workloads, we will still hit this issue.

But just like @orangedeng mentioned, we have some technical problem with HPA using cpu. It will so as red for 1 or 2 minutes. Could you help to check with Vince and Tani if we can do something for it, please?

**Comment by davidnuzik** [comment]
Thanks @loganhz and @orangedeng 
I will discuss with Tani/Vincent on Monday as to how we may want to handle this.

**Comment by davidnuzik** [comment]
Had discussion offline. Backend should fix this. If we don't like what the UI is showing -- we should have backend report a better state in the API.
Perhaps we could have some sort of transition/pending state during this time.

@loganhz how should we handle this? New issue for API backend to request this change?

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/3/19)

Now when you create an HPA in the Rancher UI or API it will instantly be in the "Initializing" state which is yellow in color (similar to "Updating" state for a cluster). 

However, in the UI I'm seeing the error state again:
![image](https://user-images.githubusercontent.com/45179589/64212083-13254200-ce5d-11e9-91b2-af33d72a7227.png)

This is somewhat brief but still happens.
A few seconds later then we are in the Active state.

**Comment by davidnuzik** [comment]
I can't always reproduce. It may just be the first HPA I make for my cluster. It's easier to see when manually refreshing the page every few seconds while the hpa comes up. This seems to be a little faster than the WS.

It's worth noting this is much, much more improved so if this is not an easy fix then perhaps we should just let this go, and assign back to me to test.

**Comment by orangedeng** [comment]
For now, backend will tolerate did-not-receive-metrics error for 60s. That is because metrics server's default scrape interval is 60s. The metrics server can only scrape cpu/memory metrics from kubelet for ready pod so if the pod is not ready for the whole time, this error will show eventually. 
I don't think we should tolerate this error for more then 60s because we still need to alert user if there is something wrong with the HPA.

**Comment by loganhz** [comment]
Please let us know if you think it's still an issue. https://github.com/rancher/rancher/issues/20955#issuecomment-527709699

**Comment by davidnuzik** [comment]
Thanks. I think this is agreeable/acceptable.

Version: master-head (v2.3) (9/3/19)

The error is no longer shown unless the error persists for greater than 60s. In a couple of tests I saw the error briefly. Now we instead show a show an "Initializing" state in the UI and API. Then the state will switch to Active when ready.

I smoke tested and didn't identify any issues with HPA.
