### ISSUE TITLE
Cluster fails to come up when powering down one etcd node and adding another etcd node in a cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20956]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
in `v2.2.5-rc6` and `2.2.4`
1. Deploy a custom cluster - 3 etcd nodes, 1 control plane and 2 worker nodes.
2. Power down one of the etcd nodes. 
3. The node will go to `Unavailable` status.
4. Add another etcd node to the cluster

**Expected Result:**

**Actual Result:**
The cluster fails to come up.
Error 
`Failed to reconcile etcd plane: Failed to add etcd member [etcd-ip-x-x-x-x] to etcd cluster`

Cluster is in `Updating` state

Kubectl on the Rancher UI: Etcd node is seen in `Not Ready` state
<img width="547" alt="Screen Shot 2019-06-18 at 12 55 17 PM" src="https://user-images.githubusercontent.com/26032343/59715926-b7d2a480-91c9-11e9-8cfc-2be008c11888.png">

**Note:**
When the etcd node which is `Unavailable` is deleted, the cluster recovers and comes up `Active`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.5-rc6` and `2.2.4`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.14 and 1.13
```

**Comment by sangeethah** [comment]
I am able to reproduce this issue in 2.1.7 as well.

**Comment by alena1108** [comment]
Marking with priority/2 as issue is not a regression in 2.2.5

**Comment by galal-hussein** [comment]
so the main problem here is that etcd prevents any cluster reconfiguration that may cause quorum loss, this can be overridden by setting --strict-reconfig-check to false: 

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--strict-reconfig-check

@cjellick @deniseschannon do you think we should set this flag to false by default or add it as an option to rke?

**Comment by galal-hussein** [comment]
After discussing the issue with @alena1108, the correct approach should be not to enable this option in rke, and just document the behavior and to workaround this the user should remove the failed/not-ready node before adding new one to the cluster since etcd enable this flag by default.
