### ISSUE TITLE
Ability to Clone a Stack in the UI

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2096]
Currently, we have the ability to clone a single service but it would be nice to be able to clone a stack and clone all services.

Note: Sidekicked services would not be able to be cloned in a stack.

http://forums.rancher.com/t/i-want-to-copy-a-stack/493

**Comment by vincent99** [comment]
To be not an infinite number of API calls I would probably use the export yml and pass that to create a stack and import yml.. so sidekicks would actually work.

**Comment by deitch** [comment]
@vincent99 any way to do it in the UI?

**Comment by vincent99** [comment]
You can export the yaml files and import them when creating a new stack today.  There is not currently an action that combines those 2 steps.

**Comment by deitch** [comment]
OK, thanks. Consider it a request, please.

**Comment by demarant** [comment]
+1

**Comment by eduwass** [comment]
Hi, just stumbled with this, wondering if this was/is ever going to be done, I personally would find it quite useful. Cheers

**Comment by deitch** [comment]
Wow, been a year? Wish I had the time to dig into the code and implement.

**Comment by bryan-kc** [comment]
+1. I find this useful for when I need 2 same stacks for HA.

**Comment by HaiNguyen007** [comment]
+1

**Comment by raviv** [comment]
+1

**Comment by vincent99** [comment]
I don't expect to ever automate this; in 2.0 you can view the yaml and re-import/edit it easily.  There are frequently going to be things you want to modify before creating the new resources.
