### ISSUE TITLE
rancher pod内部不能访问http请求外网环境

### ISSUE THREAD

**Issue by asAngus** [rancher/rancher#20967]
*Describe your issue here*
访问外部服务错误
/ # wget www.baidu.com
Connecting to www.baidu.com (180.97.33.107:80)
Connecting to www.baidu.com (180.97.33.107:443)
ssl_client: www.baidu.com: name `www.baidu.com' not present in server certificate
wget: error getting response: Connection reset by peer

程序访问:
返回报文为：<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`authenticated.project.dns.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or find us by searching `rancher2` via WeChat
