### ISSUE TITLE
Support mapping random ports 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2097]
Allow the ability to map to random ports.

**Comment by pwwebdev** [comment]
+1

**Comment by sshipway** [comment]
+1 here as well.  We have a specific use case for spinning up many ephemeral containers for students in classes mapping to randomly chosen ports

**Comment by sheng-liang** [comment]
We need to implement something like Kubernetes NodePort. Just randomly pick a port on individual nodes won't work for services like Rancher load balancer which has to listen on the same random port on multiple hosts.

The feature should work as follows: We allow the user to specify on a per-environment basis a range of service ports. Rancher will then assign ports out of the range for mapping service ports.

**Comment by sshipway** [comment]
This sounds a great solution that gives us the best of both worlds.  Looking forward to seeing it implemented...

**Comment by srikarm** [comment]
+1  looking forward to see this implemented..shipyard for now.

**Comment by flaccid** [comment]
+1

**Comment by romandvoskin** [comment]
+1 We're would really love this for integration with Consul, where services are discovered and registered using the host ip and randomly assigned port.

**Comment by jippi** [comment]
:+1: to both Consul and random port

**Comment by alena1108** [comment]
@sangeethah 

1) Port range is defined on per environment (project) basis. New API field is introduced for the project:

servicesPortRange (string, optional, default value "49153-65535", CRU permissions)

2) If service has a port defined under "ports" parameter as "80" or "80/tcp" (with no public port specified), public port will get automatically assigned to the port from environment.servicesPortRange

3) Port gets assigned to the service on its creation, and the assignment gets removed after service is removed. Once disassociated, the port can be used by other services.

Random port can't have duplicates among other ports generated in random manner.
We don't validate random port against public ports specified by the user explicitly. The assumption is that the servicesPortRange is reserved for random allocation, and user shouldn't specify ports from this range when creates service/standalone instance.

We should test port release by 1) specify smaller port range, say 2 ports. 2) Add 2 services. 3) Remove one of the services. Make sure the port can be released.

**Comment by sangeethah** [comment]
Tested with Build from master.

We have support for mapping random ports when public port is not provided in port maps for services.
Issues found when testing this feature is tracked in different issues.

**Comment by kolis** [comment]
:+1: 
When will this be available in the released container images? It does not seem to work in the current v0.56.1 release.

**Comment by vincent99** [comment]
@kolos this was in0.56; please open a separate issue with details about what you think isn't working.

**Comment by kolis** [comment]
lol, it actually seem to work now when I tested once again, not sure what happened before!
