### ISSUE TITLE
how to determine the default namespace in a custom catalog

### ISSUE THREAD

**Issue by dorsany** [rancher/rancher#20972]
How can I determine the default namespace in my custom catalog (using ```chart museum```). For example: I want that the default name space will be "default" and not the Catalog name

![image](https://user-images.githubusercontent.com/36127093/59749886-87047500-9286-11e9-82e1-bc53050d85ac.png)

**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1) choose a custom catalog (For example "Jfrog")
2) the namespace is is the name of the catalog "artifactory-ha" and not "default" by default

**Result:**
many of my clients can forget to change the namespace to "default" and leave the section with "Add to a new namespace" which can cause dependencies issue because many of my secretes, configmaps and services depends on the namespace that called "default", therefor this is really improtatnt that I will be able to determine the default  namespace to "default" in my custom catalog

**Other details that may be helpful:**
I have tried this but it didn't work: https://github.com/rancher/rancher/issues/13239
also this: https://github.com/rancher/rancher/issues/13519

I saw that you have a chart that somehow seems to have what I want.
Chart name: longhorn
Chart.yaml: https://github.com/longhorn/longhorn/blob/master/chart/Chart.yaml
no mention longhorn-system in the chart yaml and still you have changed the namespace to ```longhorn-system```  and disable the ability of the user to change it

![image](https://user-images.githubusercontent.com/36127093/59975034-3b223a80-95bc-11e9-9669-7583994ce41c.png)

is that possible to do this also to my custom Chart? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher-2.2.4 (from the chart https://releases.rancher.com/server-charts/latest/rancher-2.2.4.tgz)
- Installation option (single install/HA):
single

**Comment by loganhz** [comment]
https://github.com/longhorn/longhorn/blob/master/chart/questions.yml#L5

Yes, you can use `namespace` field in questions.yaml

**Comment by digger18** [comment]
This only works with charts hosted on Git, not Helm repos such as ChartMuseum.

https://github.com/rancher/rancher/issues/20977

**Comment by dorsany** [comment]
> https://github.com/longhorn/longhorn/blob/master/chart/questions.yml#L5
> 
> Yes, you can use `namespace` field in questions.yaml

Hi @loganhz , you solution is not working in rancher 2.2.8

and I'm using chart museum

**Comment by dorsany** [comment]
@loganhz ?

**Comment by dsvmacdonald** [comment]
FYI - if you set namespace in questions.yaml, it overrides app name.  This should be a bug

**Comment by smacedorj** [comment]
I'm also having the same problem with Rancher 2.4.5 and a local helm2 server ("helm serve" command line).
I'd like to restrict a specific app to kube-system without having to warn my users to change de default namespace. 
My production helm server is an artifactory server, managed by another team. 

Any hints on how to solve or, at least, work around this problem?

**Comment by dorsany** [comment]
Hi @loganhz , any chance that this will be done soon?
