### ISSUE TITLE
[vsphere] Cluster deletes VM from active Cluster when same node pool prefix is used

### ISSUE THREAD

**Issue by Nightapes** [rancher/rancher#20971]
**What kind of request is this (question/bug/enhancement/feature request):**
`BUG`

**Steps to reproduce (least amount of steps as possible):**

- Crete cluster with node template for vsphere
- Create cluster with nodepool prefix `all`
- Wait for cluster getting active
- Create new cluster with new name and  same nodepool prefix `all`
- New cluster will be complaining that a vm with the same name exists.
- Delete new cluster

**Result:**

- Rancher will delete the VM with the name, even it is part of of the first cluster

**Other details that may be helpful:**

Is it possible, that the vm name has the cluster name as prefix? 
`<clustername>-<nodepool-prefix><number>`

**Environment information**
- Rancher version : 

Tool| Version
-- | --
Rancher | v2.2.4
User Interface | v2.2.70
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1
vsphere |  6.5.0

- Installation option (single install/HA): `Single`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `vSphere`
- Machine type (cloud/VM/metal) and specifications (CPU/memory): `VM`
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by daxmc99** [comment]
@Nightapes Could you try this on rancher v2.2.7? 
I am seeing the second cluster fail with `500 internal server error` but on removal the other machine nodepool is fine.

**Comment by daxmc99** [comment]
See also https://github.com/rancher/rancher/issues/21757

**Comment by cjellick** [comment]
waiting on release of docker-machine

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 32dd7e2fa

* Reproduced in v2.2.4
  * Create a cluster
  * Create a second cluster with same prefix
  * Second cluster fails to create
  * Deleting second cluster results in node from first cluster being deleted

* Install master-head
  * Create a cluster
  * Create a second cluster with the same prefix
  * Second cluster fails to create
  * Delete second cluster
  * Cluster is removed, nodes from the first cluster are untouched
