### ISSUE TITLE
Add k8s 1.15 support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20986]
Kubernetes 1.15 was shipped on 06/19; we have to add support for it in Rancher.

**Comment by sangeethah** [comment]
Tested with latest build using master - `b4340af9`
k8s 1.15 is now presented as "Experimental" when creating RKE clusters.

Created a K8s 1.15 custom cluster with following node configuration with docker version - 18.09.6 and OS version - Ubuntu 16.04 :
1 control node
3 etcd nodes
3 worker nodes

> kubectl version  
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
> 
All existing automation runs succeeded.
