### ISSUE TITLE
Istio - ingress gateway endpoint is not easily viewed when enabling ingress gateway

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#20983]
rancher/rancher:v2.2.30-alpha4
System chart - `https://github.com/loganhz/system-charts:istio`

To reproduce:
* Set system charts catalog to test branch
* Create a cluster
* Enable Istio with ingress gateway
* Ingress gateway workload is deployed, but no endpoint for the nodeport is visible via the app or workload

![Screen Shot 2019-06-19 at 11.25.23 AM.png](https://zube.io/files/rancher/65417021f2e3f433ef3a68ade8addcca-screen-shot-2019-06-19-at-11-25-23-am.png)

![Screen Shot 2019-06-19 at 11.25.45 AM.png](https://zube.io/files/rancher/9400088bdd865e0b57ee78f75e5c3d44-screen-shot-2019-06-19-at-11-25-45-am.png)

![Screen Shot 2019-06-19 at 11.30.50 AM.png](https://zube.io/files/rancher/3f961578dec42a4d3d27033e88c8e56f-screen-shot-2019-06-19-at-11-30-50-am.png)

Previously this was shown in the workloads / app. 

* The user can go to System project `Service Discovery` tab under `Workloads` and view the endpoint there.

**Comment by loganhz** [comment]
Updated in my branch. Please try again

**Comment by bmdepesa** [comment]
After refreshing the catalog, the endpoints are showing correctly under the `istio-ingressgateway` workload, and `istio` app.
