### ISSUE TITLE
Backport: Timeout issues with helm after upgrading to 2.2.4-rc2

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#20987]
https://github.com/rancher/rancher/issues/20289

**Comment by bmdepesa** [comment]
rancher/rancher:master cd9265c0

Reproduced in v2.2.5 and saw /opt/jail/<jail>/etc/nsswitch.conf not present
Using wordpress app to test, I am able to see nsswitch.conf present in both cluster and app jails.

* Create cluster
* /opt/jail/<cluster>/etc/nsswitch.conf is present
* while true; do ls /opt/jail/wordpress/etc/; done;
* Deploy wordpress app
* /opt/jail/wordpress/etc/nsswitch.conf is present

Tested in both single node and HA
* Single node
  * docker exec -it <rancher container> /bin/bash
* HA
  * kubectl exec -it <rancher leader pod > -n cattle-system /bin/bash
  * to get rancher leader pod - kubectl get configmap/cattle-controllers -n kube-system -o yaml
