### ISSUE TITLE
Backport: RKE clusters: show auto generated certificates' expiration info in API/UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20994]
Backport https://github.com/rancher/rancher/issues/19103

**Comment by alena1108** [comment]
APIs support is in with this pr

**Comment by sowmyav27** [comment]
verified with `custom 2.2.4 image` with 30 minutes expiry
Scenarios verified:
**Rancher server with custom 2.2.4 image with a cluster--> expired --> and upgrade to `rancher:v2.2-head`**
1. create a cluster. Verify the certs expiry is 30 minutes from cluster creation time. 
2. wait for the cluster certs to expire
3. upgrade to rancher:v2.2-head. 
4. the cluster will be see in **Provisioning** state like the below snapshot.
<img width="1468" alt="Screen Shot 2019-06-25 at 2 35 21 PM" src="https://user-images.githubusercontent.com/26032343/60139891-8414f300-9764-11e9-9240-5ffe63865681.png">

5. The View in API does not contain the `certificatesExpiration` block
6. Do **Rotate Certificates**.
7. The cluster will come up `Active` after a couple of minutes.
8. The cluster will have the `certificatesExpiration` in View in API. and the expiration date would now be close to 10 years from the time the action was performed.


**Rancher server with custom 2.2.4 image --> upgrade to `rancher:v2.2-head` --> wait for the certs to expire**

1. create a cluster. 
2. upgrade to rancher:v2.2-head. 
3. View in API does have `certificatesExpiration` block
4. expiry would be 30 minutes from the time of creation of cluster
5. wait for the cluster certs to expire.
6. Do **Rotate Certificates**.
7. The cluster will go into `Updating` state and will come up `Active`.
8. The cluster will have the `certificatesExpiration` in View in API. and the expiration date would now be close to 10 years from the time the action was performed.

**Comment by sangeethah** [comment]
@alena1108 @moelsayed In case were user upgardes to 2.2.5 with an expired cert , we are NOT able to see the "certificatesExpiration" set for the cluster.

Is this something that can be addressed ? In this case the cluster itself is stuck in "provisioning" state.

**Comment by sowmyav27** [comment]
reopening to get a confirmation on this comment [https://github.com/rancher/rancher/issues/20994#issuecomment-505661582](url)

**Comment by moelsayed** [comment]
@sangeethah That's not possible. We run this as a user controller. It can't run on the user cluster if we can't connect to it, which is the case with clusters with expired certificates.
