### ISSUE TITLE
When the same image is present for multiple services in the docker-compose.xml , pull command ends up pulling images multiple times.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2099]
rancher-server version - v0.38.0-rc3
rancher-compose version - rancher-compose version v0.4.0

When the same image is present for multiple services in the docker-compose.xml , pull command ends up pulling the same image multiple times on the same set of hosts.

docker-compose file used:
```
webtest5:
  restart: always
  tty: true
  image: sangeetha/testupgrade:latest
  stdin_open: true
webtest6:
  restart: always
  tty: true
  image: sangeetha/testupgrade:latest
  stdin_open: true
```

```
root@sangee01:/home/sangeethahariharan1/latest# ./rancher-compose -f dc2.yml pull
INFO[0001] Checking for sangeetha/testupgrade:latest on sangee38rc3again-10acre-2... 
INFO[0001] Checking for sangeetha/testupgrade:latest on sangee38rc3again-10acre-3... 
INFO[0001] Checking for sangeetha/testupgrade:latest on sangee38rc3again-10acre-1... 
INFO[0001] Checking for sangeetha/testupgrade:latest on sangee38rc3again-10acre-2... 
INFO[0001] Checking for sangeetha/testupgrade:latest on sangee38rc3again-10acre-3... 
INFO[0001] Checking for sangeetha/testupgrade:latest on sangee38rc3again-10acre-1... 
INFO[0002] Finished sangeetha/testupgrade:latest on sangee38rc3again-10acre-2 
INFO[0002] Finished sangeetha/testupgrade:latest on sangee38rc3again-10acre-3 
INFO[0002] Finished sangeetha/testupgrade:latest on sangee38rc3again-10acre-1 
INFO[0002] Finished pulling sangeetha/testupgrade:latest 

INFO[0017] Finished sangeetha/testupgrade:latest on sangee38rc3again-10acre-2 
INFO[0017] Finished sangeetha/testupgrade:latest on sangee38rc3again-10acre-3 
INFO[0017] Finished sangeetha/testupgrade:latest on sangee38rc3again-10acre-1 
INFO[0017] Finished pulling sangeetha/testupgrade:latest 
root@sangee01:/home/sangeethahariharan1/latest# 
```

**Comment by xaka** [comment]
I have >40 services using the same image and it's painful to wait for `rancher-compose up` to finish. Would be nice to have fix. Thanks!

**Comment by deniseschannon** [comment]
@xaka - Just to make sure, you don't have the `io.rancher.container.pull_image: always` label on your service. Because if you do, there's no way around re-pulling each image since you've asked us to pull every time a service is launched. :)

**Comment by xaka** [comment]
Let me disagree a bit here and keep :cookie: to myself for now. Re-pulling images as requested and and doing so N times in row for command execution period are different things. Rancher should be smarter in this situation, collect list of images to pull for single host, reduce the set to unique values and proceed. I thought I'd send PR with fix, but realized it might require major changes to existing structure. So it's not easy, yes, but totally doable and definitely shouldn't be treated as user's mistake.
