### ISSUE TITLE
When deleting an unnamed API key, the delete confirmation box shows up the randomly assigned name.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#210]
Server Version: v0.11.1

If I didn't name my API key and I choose to delete it, the confirmation window shows me the randomly assigned name of the API key. On the UI screen, my API key shows "No name".

As a user this is confusing because I never knew the API was provided a random name.

Couple of options to make it less confusing for the user.

Option 1: Require a name so that it's clear.
Option 2: Show the randomly assigned name as the API key name. This would follow the approach that happens when adding a new host without a name. 
Option 3: In the confirmation screen, display the username of the API key when no name was created for the API key.

**Comment by vincent99** [comment]
Should have a custom delete confirm dialog that shows the public value + name

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/11984694/a7d9abe0-a97a-11e5-80dc-03ea4315b3b8.png)

**Comment by tfiduccia** [comment]
Version - Master Jan 07
Verified fixed
