### ISSUE TITLE
node template provision node with limit retry

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#21002]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Set up node template to provision a node with cloud provider.

If provision node failed, Rancher will remove and provision another one. 

There should be a limit number of retry as each node in AWS create will charge minimum of 1 hr usage. In operational prospective, no one is going to watch every node provision successfully. It may cost a lot in weekend something go wrong and Rancher keep provision node hundred and thousand times. 

Of course there should be Prometheus metrics for this and trigger alert :)

**Comment by vincent99** [comment]
The minimum EC2 charge is one minute, not one hour.  While this is still a problem it's not a significant cost compared to actually running the node you asked for.
