### ISSUE TITLE
Prometheus not deployed when activating monitoring

### ISSUE THREAD

**Issue by joharohl** [rancher/rancher#21006]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a new cluster in openstack
- Enable the default monitoring configuration.

**Result:**
Grafana, node-exporters, prometheus-operator etc are deployed fine. The deploy fails before it
can create the prometheus resource. Logs from the rancher docker container contains: 

```
[tiller] 2019/06/20 11:54:31 failed install perform step: release cluster-monitoring failed: Endpoints "expose-kube-cm-metrics" is invalid: [subsets[0].addresses[0].ip: Invalid value: "": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[0].ip: Invalid value: "": must be a valid IP address, subsets[0].addresses[1].ip: Invalid value: "": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[1].ip: Invalid value: "": must be a valid IP address, subsets[0].addresses[2].ip: Invalid value: "": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[2].ip: Invalid value: "": must be a valid IP address]
```

When I check the `expose-kube-cm-metrics` service it does look kind of empty.
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-06-20T11:54:13Z"
  labels:
    app: exporter-kube-controller-manager
    chart: exporter-kube-controller-manager-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    k8s-app: kube-controller-manager
    release: cluster-monitoring
  name: expose-kube-cm-metrics
  namespace: cattle-prometheus
  resourceVersion: "46272205"
  selfLink: /api/v1/namespaces/cattle-prometheus/services/expose-kube-cm-metrics
  uid: 1f3af8aa-9352-11e9-aced-fa163ef80418
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 10252
    protocol: TCP
    targetPort: 10252
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Other details that may be helpful:**
Fully aware that this might be something that is misconfigured on our end, but would love some help to figure out what is wrong.

**Environment information**
- Rancher version: 
2.2.4
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
Openstack

- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
3+4 nodes @ 8 vcpus, 8GB RAM

- Kubernetes version (use `kubectl version`): 
1.13

- Docker version (use `docker version`): 
18.9.6

**Comment by alena1108** [comment]
@orangedeng can you follow up

**Comment by orangedeng** [comment]
I would like to check the control plane nodes’ IP address. You can find those addresses in cluster -> nodes in ui pages.

**Comment by joharohl** [comment]
In my case they are: 

- 10.67.115.118
- 10.67.112.237
- 10.67.116.29

**Comment by orangedeng** [comment]
Are they `InternalIP`? I just want to make sure there will be an internal in the node status.

**Comment by joharohl** [comment]
```
NAME                     STATUS   ROLES               AGE     VERSION   INTERNAL-IP   EXTERNAL-IP     OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
gitlab-k8s-controller1   Ready    controlplane,etcd   57d     v1.13.5   <none>        10.67.115.75    CentOS Linux 7 (Core)   3.10.0-693.5.2.el7.x86_64    docker://18.9.5
gitlab-k8s-controller2   Ready    controlplane,etcd   57d     v1.13.5   <none>        10.67.112.245   CentOS Linux 7 (Core)   3.10.0-693.5.2.el7.x86_64    docker://18.9.5
gitlab-k8s-controller3   Ready    controlplane,etcd   57d     v1.13.5   <none>        10.67.115.33    CentOS Linux 7 (Core)   3.10.0-693.5.2.el7.x86_64    docker://18.9.5
gitlab-k8s-worker1       Ready    worker              5d22h   v1.13.5   <none>        10.67.114.57    CentOS Linux 7 (Core)   3.10.0-957.21.2.el7.x86_64   docker://18.9.6
gitlab-k8s-worker3       Ready    worker              5d22h   v1.13.5   <none>        10.67.113.199   CentOS Linux 7 (Core)   3.10.0-957.21.2.el7.x86_64   docker://18.9.6
gitlab-k8s-worker4       Ready    worker              6d      v1.13.5   <none>        10.67.115.176   CentOS Linux 7 (Core)   3.10.0-693.5.2.el7.x86_64    docker://18.9.6
```

Short answer is no I guess.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue in Rancher 2.3, and we'll reopen it

**Comment by vitobotta** [comment]
I opened another issue (https://github.com/rancher/rancher/issues/28028) about the same problem, sorry I didn't see this one before. @loganhz The Internal IPs are missing for me too because they "disappear" after installing the cloud controller manager for Hetzner Cloud. Is it possible to force the use of external IPs? Or is there another workaround? 

@joharohl did you find a solution?

**Comment by JannikZed** [comment]
same here .. after using the cloud controller for Hetzner Cloud.

**Comment by vitobotta** [comment]
@JannikZed to solve the issue ensure that the servers are added to a private network. That way the cloud controller manager will configure both internal and external IPs and Prometheus will work.
