### ISSUE TITLE
Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s)

### ISSUE THREAD

**Issue by usvgmani** [rancher/rancher#21007]
Using the Rancher UI to create a cluster with EC2 instances config is private ip, on a private subnet in AWS, we get Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s). The Rancher UI has cloud credentials with all the possible IAM permissions possible. 
The nodes get created but the cluster is not created.
Also used this doc to pass and create IAM roles for the etcd,worker and control plane node templates: 
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/cloud-providers/

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by usvgmani** [comment]
Had to dig in to rancher-agent container logs to find out what was happening!! The error messaging feedback was incorrect!

**Comment by cezarfw** [comment]
I'm really having trouble, could you describe what the solution was?

**Comment by MohamedBenighil** [comment]
I have exactly the same issue as you. Could you please elaborate how did you solve it ?

**Comment by usvgmani** [comment]
You have to check the container logs on the rancher ui pod... in my case it
was permissions on ec2 instances.. the ui does not provide clear error
messages  for everything  it gives the etcd error

**Comment by MohamedBenighil** [comment]
when i run docker container logs <id_rancher_agent>, i got these messages:

![Capture10](https://user-images.githubusercontent.com/49414837/60731905-ff3a8e00-9f48-11e9-837c-b923efa00946.PNG)


NB: when i would like to pull docker images (sau for example : ubuntu ) from docker hub, i have to do this:

#  docker pull dockerproxy-iva.si.francetelecom.fr/ubuntu:16.04

**Comment by rshiva777** [comment]
any update on this issue. I too face the same issue

Log:
2019/12/11 13:48:38 [INFO] stdout: Checking connection to Docker...
2019/12/11 13:48:38 [INFO] Checking connection to Docker...
2019/12/11 13:48:39 [INFO] stdout: Docker is up and running!
2019/12/11 13:48:39 [INFO] Docker is up and running!
2019/12/11 13:48:52 [INFO] Provisioning node awstest21 done
2019/12/11 13:48:52 [INFO] Generating and uploading node config awstest21
2019/12/11 13:48:52 [INFO] Provisioning cluster [c-bbqrd]
2019/12/11 13:48:52 [INFO] Creating cluster [c-bbqrd]
2019/12/11 13:48:57 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10580
2019/12/11 13:48:57 [INFO] cluster [c-bbqrd] provisioning: Initiating Kubernetes cluster
2019/12/11 13:48:57 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating CA kubernetes certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Service account token key
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Controller certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Scheduler certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Proxy certificates
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Node certificate
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating admin certificates and kubeconfig
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server proxy client certificates
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating etcd-172.31.30.0 certificate and key
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: Successfully Deployed state file at [management-state/rke/rke-395003924/cluster.rkestate]
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: Building Kubernetes cluster
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: [dialer] Setup tunnel for host [13.234.110.198]
2019/12/11 13:49:00 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Failed to set up SSH tunneling for host [13.234.110.198]: Can't establish dialer connection: can not build dialer to c-bbqrd:m-7kbsp
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Removing host [13.234.110.118] from node lists
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [13.234.110.118]
2019/12/11 13:49:00 [ERROR] ClusterController c-bbqrd [cluster-provisioner-controller] failed with : Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [13.234.110.198]

**Comment by jerkyrs** [comment]
This error appears to be caused by the AWS node you are provisioning being unable to communicate back to your rancher cattle server ( i think this is right terminology). I logged onto the remote AWS instance and checked the logs of the running container. 

You see an error like this
```
ERROR: https://rancher.example.com/ping is not accessible (The requested URL returned error: 404 Not Found)
```

So it appears as though the Rancher container you are running on needs a FQDN that resolves correctly and is accessible from the AWS instance (in my case it was not)
