### ISSUE TITLE
Custom CA Cert - openstack cloud provider

### ISSUE THREAD

**Issue by xotama** [rancher/rancher#21011]
Dear Team,
I start to try rancher with openstack cloud provider. I configured tls for endpoints ( self signed certificate) but i can't able to configure the ca cert inside the docker kubelet container. I receveid the error: 
[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.50.0.18]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused, log: F0620 16:39:55.999128 5374 server.go:266] failed to run Kubelet: could not init cloud provider "openstack": open /etc/ssl/certs/cloud-init-ca-certs.pem: too many levels of symbolic links]

I did some tests the last:
1) configure by cloud-init the custom CA on the VM and it works fine ( test curl $https://keystone_url and work)
 2) configure variable ca-file on YAML cluster cloud_provider file

have u any suggestions ?
tnx
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.5-rc6` UI: `v2.2.77` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by burakhoban** [comment]
This probably doesn't pertain to your situation, however I had a similar issue, albeit running a slightly older version of Rancher.

We had a Rancher launched Kubernetes cluster configured with OpenStack Cloud Provider settings which were pointing to an environment with a self-signed certificate.

Our workaround was to simply add the OpenStack self-signed cert into OS CA trust, and then copy the ca bundle under /etc/kubernetes/ and set ` ca-file: "/etc/kubernetes/tls-ca-bundle.pem"`. From there all controllers and worker nodes could connect to OpenStack endpoints. There would be less messing around if you provisioned a RKE cluster.

**Comment by patriziobassi** [comment]
So you added It in the rancher machine and not in the rancher deployed nodes (openstack vms). I will give a try.

**Comment by burakhoban** [comment]
In our environment, I added the self-signed OpenStack cert on all nodes
(Master, Controllers and Worker nodes) and copied the bundle to
/etc/kubernetes. We provision our VMs and use cloud-init to simply do a
docker run <blah>.. this let's use treat the underlying nodes as cattle, we
don't let Rancher control VM builds.

**Comment by patriziobassi** [comment]
yes i did the same and it works, but. it would be good to include a custom ca/cert via rancher instead of using cloud-init or any custom post-deploy configuration. For instance the certificate rotation/renewal won't include this custom one.

**Comment by kenhglee** [comment]
Thank you for the insight as I was working on the same use case with docker install and openstack. May I ask what was the physical space of "/etc/kubernetes/tls-ca-bundle.pem"? Is it he container or the host VM? I copied the certificates to both places but still ended up having "no such file or directory" upon creating the worker plane.

**Comment by burakhoban** [comment]
For me the `/etc/kubernetes/tls-ca-bundle.pem` path was on the worker/controller node itself, so VM layer. Then configuring the `ca-file` setting the custom launched rke cluster containers were able to read the ca-bundle and connect to OpenStack with its self-signed certificate

**Comment by lperrin-obs** [comment]
@burakhoban @patriziobassi 
I used your workaroung and it works for me too, thanks !

DId you tried to restore etcd and kubernetes version from rancher backup ?
When I'm doing this, the kubernetes directory is cleaned with the ca certificate and kubelet cannot start because it cannot find the `/etc/kubernetes/tls-ca-bundle.pem` file.

**Comment by lperrin-obs** [comment]
I found a workaround using the `extra_binds` option in the `cluster.yml` file : https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/
I mounted the certificate from another directory and now, restoration is working.

**Comment by pratik705** [comment]
- I was able to workaround the issue by manually copying the CA cert on the k8s nodes. 
- Instead of specifying the CA file path in cloud_provider section(`ca-file`), it would be better if it allows to paste the content of the CA cert. I guess that would be a permanent fix
