### ISSUE TITLE
Request for combined dashboards for clusters and projects

### ISSUE THREAD

**Issue by ebauman** [rancher/rancher#21018]
**What kind of request is this (question/bug/enhancement/feature request):** Enhancement

**Steps to reproduce (least amount of steps as possible):** n/a

**Result:** (Desired result)

It would be nice if there was a single dashboard where top-level metrics from each cluster were displayed. 

It would also be nice if there was a single dashboard where top-level metrics from each project were displayed.

**Comment by toddexp** [comment]
This would be a great feature to have. Additionally it would be awesome, If multiple clusters could aggregate to a single grafana dashboard.

**Comment by toddexp** [comment]
It seems that another issue has been opened for this that is getting more traction. We may want to close this one in favor of the other.

https://github.com/rancher/rancher/issues/23057

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/23057
