### ISSUE TITLE
Backport: Rancher crashing every 5 minutes with SIGSEGV in etcdbackup

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21015]
Backport https://github.com/rancher/rancher/issues/20964

**Comment by sowmyav27** [comment]
Issue is seen in v2.2.4, when the cluster does not have 
```
backupConfig:
    "enabled": true
```
In 2.2.4, edit the cluster CRD, and delete `enabled: true` for backup config. And every five minutes, you will see the rancher server restart after a panic.

Verified on `rancher:release-v2.2`.
Edit cluster CRD, and delete `enabled: true` for backup config. Rancher server is up and running fine. No panics are seen.
