### ISSUE TITLE
Backport v1.6: Node driver Error creating machine: Error running provisioning: something went wrong running an SSH command

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#21017]
https://github.com/rancher/rancher/issues/20753

**Comment by cjellick** [comment]
we dont need an immediate release for this, so it doesnt need tested immediately, but it should go out with next 1.6 release

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc1`

**Comment by soumyalj** [comment]
Tested with rancher/server:v1.6.29-rc2 
Tested with provisioning Ubuntu, Centos nodes using digital ocean node driver. 
Did not observe the issue "Error running provisioning: something went wrong running an SSH command " . 
Nodes got provisioned successfully and the setup was functional.
