### ISSUE TITLE
support for ARM (* pi) and others (hypriotos/arch nodes)

### ISSUE THREAD

**Issue by dbones** [rancher/rancher#2101]
unsure if this has been requested, I noted it has been form the Rancher OS (really cool project btw)

possible support for ARM devices such as \* PI, for both the agent and the master.

Raspberry PI (1 and 2), not sure if 1 is possible (you have mentioned a 1GB Ram requirement)
Banana PI
Orange PI

**Comment by geniousphp** [comment]
That'd be really awesome if Rancher team can add ARM support, I would like to try Rancher on Scaleway  which is ARM-Based cloud platform.

**Comment by faddat** [comment]
Here's where I am with all that:

Working with the various build tools (It's a bit more than rancher alone at this point) to get an automated system together for building

 * RancherOS

My biggest roadblock is time.  With a full week to devote only to this, I could have some kind of build system (and thus an in-sync release) set up.  If anyone here is interested in helping, I am more than happy to share the login info for the GCE instance where I'm working on this, and several hours or more if needed to get you up to speed on things.  I do know this:  A while back the Rancher crew put that Rancher uses buildroot for RancherOS.  Now really from there it's a very short walk indeed to getting it to work on the devices you mention here.  I'll also go ahead and share that I'm currently working on something shaped like this:

_|_|_|_|_|_

That uses ARM and runs Rancher.  The issue, as always is time.  <sarcasm, maybe> If anyone here can act in my stead on the SaaS project, I'll gladly fly off to Shenzhen and play with gizmos and doodads for a bit.  Here's a photo of one of the vertical lines from my illustration: </sarcasm, maybe>

![6187747668629523250](https://cloud.githubusercontent.com/assets/7142025/10239034/66d27d9e-68f1-11e5-8718-6c1b7d0eb88f.jpg)

....but I've got to ask you to imagine it without any ports or antennas, all connections handled through the connectors at the bottom.  

As for rancherOS on ARM, I think that I even got it running, but not quite for the board in question (that day, it was a banana pi....)

**Comment by faddat** [comment]
https://github.com/rancher/os/issues/417

**Comment by dbones** [comment]
@faddat its cool seeing the OS being made available for the OS. :), I thought that the other thread was limited to the OS, please correct me if i'm wrong.

re this thread, I would like to help out mainly by testing out (I have a few boards, rpi1 + 2 and Bni 1)

possibly start with the agent. 

a post seemed to be getting close with this (http://forums.rancher.com/t/requesting-access-to-rancher-agent-repository/176/4)

I would be interested also in using swarm with rancher as an alternative. hypriot for the pi's and using arch arm for the banana pi's (detailed here http://blog.oneiroi.co.uk/raspberrypi2/pi2/cluster/docker/swarm/arch/pi2-cluster-docker-swarm/).

**Comment by Skeen** [comment]
+1

**Comment by vekexasia** [comment]
+1 ? :+1:

**Comment by faddat** [comment]
So you guys know, it wasn't so much me porting the OS-- the Hypriot crew & Rancher crew deserve all the credit on that one.  I'm still working towards the modular compute system, and should have something to show sooner than later, but exactly when isn't real clear right now.

**Comment by lavvy** [comment]
Guys what is the status of this feature please

**Comment by dbones** [comment]
looks like there is an ARM thread here.

https://github.com/rancher/rancher/issues/4703

**Comment by tttmaximttt** [comment]
Hi, can I run rancher on ARM in 2016?

**Comment by gliwka** [comment]
What's the status on this issue? Considering Server Hosting Providers are now selling 96-Core ARM Server with 128GB Ram and 20Gbit/s Network for 0.05$/h, it would be great to test container workloads on those machienes (i.e. https://www.packet.net/bare-metal/servers/type-2a/)

**Comment by kvaes** [comment]
+1

**Comment by albertoig** [comment]
could be fine to have news about this issue.

**Comment by openhoat** [comment]
+1

**Comment by LarsVader666** [comment]
+1

**Comment by kingprimex** [comment]
+1

**Comment by gitgc** [comment]
+1. I have an Asus UP board (exact same form factor as the Raspberry Pi 3, but with x86 Atom CPU and 4GB RAM). This guy will obviously run the Rancher server fine, but I really want it to manage a bunch of Raspberry Pi 3 agents. Just getting an official ARM image for the agent alone would really make all the difference for a bunch of ARM use cases.

**Comment by mfuezesi** [comment]
+1

**Comment by fedya** [comment]
+1

**Comment by AdrianAntunez** [comment]
+1

**Comment by chymian** [comment]
+1

**Comment by chymian** [comment]
Can anyone of ranger please comment on the status and roadmap (if one) of arm-support – please.

**Comment by sbkg0002** [comment]
+1

**Comment by patrickaubertdelaruee** [comment]
+1

**Comment by klud1** [comment]
+1

**Comment by klud1** [comment]
+1 it's not only agent/server, but all of the services though. Not impossible, really exciting. If Rancher team agrees on doing this, manifest tool and mainfest list could be used, so the tag naming won't be affected that much.

**Comment by CodingSpiderFox** [comment]
+1

**Comment by cdknudsen8** [comment]
+1

**Comment by BulatSaif** [comment]
I see a some movements, and it's cool, a year ago I was trying to run it on PI Raspberry, and its possible to run the old version. You just need compile all source code and rebuild all  docker images. This is a good blog that I used:  https://blog.zhaw.ch/icclab/supporting-container-based-application-deployment-to-heterogeneous-hardware-using-rancher/

**Comment by antmanler** [comment]
check [rancherpi/rancher-arm64](https://github.com/rancherpi/rancher-arm64) and can run on raspberry pi 3b+ with most rancher features

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/16461
