### ISSUE TITLE
Missing Icons in v0.38.0

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2102]
v0.38.0

Running Status Icon on Container (In List View and Detailed View)
Restart on Container menu
Execute Shell on Container menu
View Logs on Container menu
Purge on Accounts menu
Restore on Accounts menu
Purge on Registries menu
Purge on API Keys

**Comment by deniseschannon** [comment]
v0.38.1

Running Status Icon on Container is showing up.

**Comment by vincent99** [comment]
Not all actions have icons..
