### ISSUE TITLE
Kube Api Server High CPU Usage 

### ISSUE THREAD

**Issue by rajiteh** [rancher/rancher#21025]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

N/A

**Result:**

API Servers are using very high cpu > 99% utilization.

**Other details that may be helpful:**

We run a fairly large rancher installation (~120 managed clusters on openstack) and recently we've noticed large portions of high cpu usage on the API Server instances that manage the k8s cluster which hosts rancher.

We have two master instances serving the cluster with 8 cores 16gigs RAM on each.

![image](https://user-images.githubusercontent.com/905419/59883597-91f0ff80-9383-11e9-8218-566d35a540b2.png)
![image](https://user-images.githubusercontent.com/905419/59883679-de3c3f80-9383-11e9-9b87-08d70086f28b.png)

When I observed the apiserver logs I noticed that rancher is making a very high number of queries to the apiserver listing all `node` objects. (This happens around 6 times a second)

```
master-01 / # docker logs --tail 10000  kube-apiserver 2>&1 | grep "List /apis/management.cattle.io/v3/nodes" | cut -d' ' -f2 | awk -F':' '{print $1":"$2}' | uniq -c
    234 21:40
    207 21:41
    253 21:42
    410 21:43
    184 21:44
    303 21:45
    319 21:46
    317 21:47
    385 21:48
    239 21:49
    189 21:50
     16 21:51
```
Highest we've seen is around 450/min

Is this expected behaviour ?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
```
rancher/rancher:v2.2.3
```
- Installation option (single install/HA):

HA Kubernetes

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Openstack RKE Provisioned
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Openstack (8 core/ 16gb ram)
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d7080c1
  Built:            Tue Feb 19 23:07:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by viniciusxyz** [comment]
I had the exact same problem and was able to solve it by removing the HA rancher from my cluster and simply uploading an instance and adding the cluster to it.
The problem is really very strange and has to be analyzed, in my case before removing the HA rancher my kube api reached 170% cpu usage (I have a 12 core machine) and after removing it was 0.6%, a very absurd difference.

**Comment by duard** [comment]
@viniciusxyz what is HA ?
