### ISSUE TITLE
Backport: Cannot repair catalog app with bad value once bad value is saved

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21027]
https://github.com/rancher/rancher/issues/20655

**Comment by westlywright** [comment]
https://github.com/rancher/rancher/pull/21030

**Comment by davidnuzik** [comment]
**Replication:**
Version: v2.2.4

Create wordpress app (from helm stable) and add a "strange" answer like:
`ingress.annotations: "certmanager.k8s.io/cluster-issuer: letsencrypt-production"`
(among other required answers)

App fails to install correctly:
![image](https://user-images.githubusercontent.com/45179589/59946342-23617f80-941f-11e9-8896-1fefa70316c2.png)

Try to upgrade the app to remove this answer to fix it.
We see the POST to the app (action=upgrade) goes thru. For some reason it still includes the answer that we removed.
Try to upgrade again and the answer we removed is indeed still there. Remove again and it will still be sent in the POST.

The app cannot be fixed via upgrading in the UI.

(These are what is exactly described in original issue description in #20655 

**Validation:**
Version: release-v2.2 (essentially v2.2.5rc)

Follow the steps again to attempt to reproduce. The app does initially fail to install (as expected), but now you can correct this via an upgrade. 

When we upgrade we see valuesYaml go thru instead and this allows us to make the correction and the app successfully comes up.

**Comment by davidnuzik** [comment]
Reopening. Need to check to ensure have correct ui-index.

**Comment by davidnuzik** [comment]
Use ui-index https://releases.rancher.com/ui/2.2.78/index.html to test this against v2.2-head image.

**Comment by davidnuzik** [comment]
I was successful in validating this against ui-index 2.2.78 as well. I had the same findings as my last test. See https://github.com/rancher/rancher/issues/21027#issuecomment-504549085
The only difference is we changed the naming convention for the rancher image. it's now `v2.2.-head`
