### ISSUE TITLE
Creating a local user account ends up creating and displaying an API Key that is unusable

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2103]
v0.38.0

Steps to Reproduce
1. Set up local access control
2. Create additional user under "Accounts"
3. Navigate to "API & Keys" and notice there is a new API key. No indication where the API key came from, but based on timestamps and tests, the addition of a user account is triggering the creation.
Note: Cannot deactivate the API key either.

Expected Result:
There shouldn't be a new API key showing up.

**Comment by hibooboo2** [comment]
@ibuildthecloud Why are apikeys being created as part of the default lifecycle when a new account is created?

**Comment by deniseschannon** [comment]
v0.41.0-rc1

Verified that API keys are no longer showing up
