### ISSUE TITLE
[Enhancement] Typo on new Istio Traffic Metrics 2.3-alpha-5

### ISSUE THREAD

**Issue by amioranza** [rancher/rancher#21045]
**What kind of request is this (question/bug/enhancement/feature request):**
Typo on the new Istio Traffic Metrics

**Steps to reproduce (least amount of steps as possible):**
Access the Istio Traffic Metrics page and look at the title of the percentile graphs

**Result:**
![image](https://user-images.githubusercontent.com/30518346/59936947-953dc700-9427-11e9-9fb5-e0c297b98824.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0-alpha5

- Installation option (single install/HA):
Single

**Comment by davidnuzik** [comment]
Version: master-head (7/1/19)

The spelling error has been resolved:
![image](https://user-images.githubusercontent.com/45179589/60471477-b2d61200-9c19-11e9-8c16-9468eb4c2a3e.png)
