### ISSUE TITLE
F0621 14:17:23.990013 7 main.go:72] Port 80 is already in use. Please check the flag --http-port

### ISSUE THREAD

**Issue by leepengcheng** [rancher/rancher#21044]
rancher version :v2.24
singbox deploy

nginx-ingress-controller pod logs:
-------------------------------------------------------------------------------
NGINX Ingress controller
Release: 0.21.0-rancher3
Build:
Repository: https://github.com/rancher/ingress-nginx.git
-------------------------------------------------------------------------------
F0621 14:17:23.990013 7 main.go:72] Port 80 is already in use. Please check the flag --http-port

**Comment by superseb** [comment]
Not sure if you are using the same host for running Rancher and adding a node to a cluster, if so, you can check https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#running-rancher-rancher-and-rancher-rancher-agent-on-the-same-node.

If not, please supply the requested information in the issue template to help investigate the issue.

**Comment by ainiml** [comment]
> Not sure if you are using the same host for running Rancher and adding a node to a cluster, if so, you can check https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#running-rancher-rancher-and-rancher-rancher-agent-on-the-same-node.
> 
> If not, please supply the requested information in the issue template to help investigate the issue.

The doc also shows to use `80:80 443:443` in `docker run -d --restart=unless-stopped \
	-p 80:80 -p 443:443 \
	rancher/rancher:latest \
	--acme-domain <YOUR.DNS.NAME>`
