### ISSUE TITLE
Rancher v2.2.4 stuck in EKS updating process

### ISSUE THREAD

**Issue by JimTim** [rancher/rancher#21043]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an EKS Cluster in AWS with Version 1.11. through Rancher UI
2. Edit EKS Cluster and update EKS Version to 1.12 through Rancher UI

**Result:**
This cluster is currently Updating.
InvalidParameterException: Unsupported Kubernetes minor version update from 1.12 to 1.12 status code: 400, request id: 9df72dc1-9405-11e9-8c95-63e680269e60

**Other details that may be helpful:**
In AWS the version is successfully updated and Rancher show also the correct 1.12 Version in the UI

**Environment information**
- rancher/rancher:latest (2.2.4)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): HOSTED (EKS AWS Ireland)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud, m3.xlarge
- Kubernetes version (use `kubectl version`): v1.12.6

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

![Bildschirmfoto 2019-06-21 um 11 01 07](https://user-images.githubusercontent.com/6737248/59913081-cd3d0e00-9417-11e9-9bbc-57bb830c0ca5.png)

**Comment by davidnuzik** [comment]
Related: https://github.com/rancher/rancher/issues/20759
