### ISSUE TITLE
Resource limits by stack

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#2105]
Any plans to support resource limits (cpu, mem and storage)  stack based?

It seems container / stack based storage could be difficult...

**Comment by pwFoo** [comment]
@deniseschannon
And / or environment based resources (CPU, RAM, ...) to limit customer stacks / environments?

**Comment by morganhein** [comment]
Is this still planned somewhere? I think Kube handles "pod" resource limits, not idea about the other implementation;, however this is critical in my environment.

**Comment by vincent99** [comment]
We don't have any specific UX for this but k8s has support for [Resource Quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/) on Namespaces.
