### ISSUE TITLE
[cli] Cluster Import Doesn’t Work

### ISSUE THREAD

**Issue by Mr-Howard-Roark** [rancher/rancher#21058]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug
**Steps to reproduce (least amount of steps as possible):**
./rancher clusters import myclustername

**Result:**
FATA[0001] Not found: myclustername

**Other details that may be helpful:**
All other commands including deleting and exporting clusters work fine 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI:
Server version v2.1.6
Cli versions attempted: 2.2.0 and 2.0.6

**Comment by fred2697** [comment]
Try this: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cloning-clusters/

**Comment by fred2697** [comment]
How do you export your cluster? Look at this issue: https://github.com/rancher/rancher/issues/21309 
Thanks!
