### ISSUE TITLE
Creating cluster template revision with cluster template created with "enabled=False" should not be allowed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21063]
Version: Master build from June 21
Steps:
1. Create a cluster template T1 with enabled=False
```
{
"annotations": { },
"baseType": "clusterTemplate",
"created": "2019-06-21T23:43:33Z",
"createdTS": 1561160613000,
"creatorId": "user-jq4b8",
"defaultRevisionId": null,
"enabled": false,
"enforced": false,
"id": "cattle-global-data:ct-8qvdc",
"labels": {
"cattle.io/creator": "norman"
},
"members": null,
"name": "clustertemplatedisabled",

```
2. Create a cluster template revision R1 with enabled=True in API using this template (T1) which is disabled and it succeeds. This should not be allowed. 
3. Creating a cluster with T1 and R1 succeeds which should not be allowed
4. Also, while creating/editing the cluster this disabled template T1 should not be displayed.

**Comment by prachidamle** [comment]
There is no "Enabled" flag on ClusterTemplate anymore. Only ClusterTemplateRevision will carry the "Enabled" flag.

**Comment by soumyalj** [comment]
Tested using master-head build from July 8th. 
Verified that Cluster template does not have "Enabled" flag. Only clusterTemplateRevision has "enabled" flag

![Screen Shot 2019-07-08 at 3 00 56 PM](https://user-images.githubusercontent.com/18536626/60845461-41561080-a191-11e9-89ab-688fb004f7c7.png)

![Screen Shot 2019-07-08 at 3 05 41 PM](https://user-images.githubusercontent.com/18536626/60845663-e1ac3500-a191-11e9-97ac-02c707377967.png)
