### ISSUE TITLE
Disabling cluster template when there is a cluster using the template/revision associated with it should not be allowed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21062]
Version: Master build from June 21

Steps
1. Create a cluster template T1 with enabled=True
```
"creatorId": "user-jq4b8",
"defaultRevisionId": "cattle-global-data:ctr2",
"description": "",
"enabled": true,
"enforced": false,
```
2. Create a cluster template revision R1 
3. Create a cluster template using T1/R1

Disable the template T1 through API by making enabled=False. This succeeds
```
"creatorId": "user-jq4b8",
"defaultRevisionId": "cattle-global-data:ctr2",
"description": "",
"enabled": false,
"enforced": false,
```
Disabling templates when there is a cluster using the revision associated this template should not be allowed. 
Note: This issue exists for both admin and standard user

**Comment by prachidamle** [comment]
There is no "Enabled" flag on ClusterTemplate anymore. Only ClusterTemplateRevision will carry the "Enabled" flag.

**Comment by soumyalj** [comment]
Tested using master-head build from July 8th. 
Verified that Cluster template does not have "Enabled" flag. Only clusterTemplateRevision has "enabled" flag

![Screen Shot 2019-07-08 at 3 00 56 PM](https://user-images.githubusercontent.com/18536626/60845461-41561080-a191-11e9-89ab-688fb004f7c7.png)

![Screen Shot 2019-07-08 at 3 05 41 PM](https://user-images.githubusercontent.com/18536626/60845663-e1ac3500-a191-11e9-97ac-02c707377967.png)
