### ISSUE TITLE
Pull doesn't work with private images

### ISSUE THREAD

**Issue by alex88** [rancher/rancher#2107]
I've tried the `rancher-compose pull -c` command and I get:

```
Image [org/project:development] failed to pull : Error: image org/project:development not found
```

seems that during pull it doesn't provide credentials, during service creation it works fine

**Comment by deniseschannon** [comment]
Yes, there is a bug with private registries and `rancher-compose pull`

**Comment by deniseschannon** [comment]
@alex88 Your error looks different from the tests that we've seen using private registries (#2110). 

Are you able to do a `rancher-compose up` with your image?

**Comment by alex88** [comment]
@deniseschannon I think it's because docker hub returns 404 for private images and quay returns 403. Anyway, I'm using rancher-compose just for updating since I've created everything with the UI

**Comment by alex88** [comment]
@deniseschannon I think we can close this one since it's the same issue (rancher not using authenticated session to pull these images)

**Comment by deniseschannon** [comment]
Pre-duplicate of #2110
