### ISSUE TITLE
[2.2.4] problems after changing domain?

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#21072]
**What kind of request is this (question/bug/enhancement/feature request): BUG

**Steps to reproduce (least amount of steps as possible):**
> remove DNS records for old domain which targets the rancher IP
> Setup new DNS records to an new domain
> redeploy rancher with docker command and new domain and existing volume
> Change the domain in the rancher interface
> rotate certificates

**Result:**
stuck in "This cluster is currently Updating"

**Other details that may be helpful:**
First error message:
`Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [IP]`
Second Error message after whaiting a while:
`Failed to rotate certificates: can't find old certificates`

**Environment information**
- Rancher version 2.2.4
- Installation option (single install/HA): multi node cluster but single install ranche

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) VM Ubuntu
Kubernetes version (use `kubectl version`): 1.13.5 rancher1-3

- Docker version (use `docker version`): 18.9.5

**Comment by MSandro** [comment]
I realy hope someon could help me soon, nothing works currently and I am not sure what I should do.
Thanks.

**Comment by alena1108** [comment]
@MSandro can you check https://github.com/rancher/rancher/issues/14731. The issue describes the steps that can be done to recover from situation you are facing.

**Comment by superseb** [comment]
Let us know if this needs a follow up.
