### ISSUE TITLE
Repositories with Gitea or Gogs for Pipelines

### ISSUE THREAD

**Issue by xnardo** [rancher/rancher#21074]
*Authorize my own repository*

Hello, i am trying to configure my repository with Gitea for pipeline, but only appear Github, Gitlab and Bitbucket. How i can to do for add other supplier in Authorize & Fetch Your Own Repositories, using my own program.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.project.pipeline.repositories`|

**Comment by benyanke** [comment]
Would love to see this as well - it would be great to support arbitrary git servers with an occasional cron fetch, and/or webhooks.

**Comment by mj520** [comment]
What version is expected to start supporting gitea/gogs

**Comment by pasikarkkainen** [comment]
support for gitea would be nice to have!

**Comment by sickcrow** [comment]
It is very necessary to be able to work with local repositories, especially in clusters on premises.

**Comment by angeloimm** [comment]
Any progress about this wonderful feature? It would be great to allow pipeline creation by using custom GIT software like gogs or gitea etc...

**Comment by cvscvs** [comment]
I am waiting Rancher to have such feature too...

**Comment by raf6** [comment]
Yes please, send this one straight to the top of the backlog.

**Comment by gyurobenjamin** [comment]
+1

**Comment by nlseven** [comment]
I'd still be keen to see Gitea/Gogs integrations for this.
