### ISSUE TITLE
请问rancher自带的prometheus的配置如何修改？

### ISSUE THREAD

**Issue by fish2018** [rancher/rancher#21076]
*Describe your issue here*
我希望添加k8s集群外的exporter到prometheus中，请问应该如何实现？
我尝试进入容器修改，提示只读。直接kubectl edit修改，立马会自动还原。

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`authenticated.project.secrets.index`|

**Comment by loganhz** [comment]
you can edit prometheus crd

Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or find us by searching `rancher2` via WeChat
