### ISSUE TITLE
Cannot get Rancher installed in a 3 node HA environment behind proxy using RKE

### ISSUE THREAD

**Issue by emcclure78** [rancher/rancher#21089]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Setup 4 nodes (3 for Rancher, 1 LB).  Install NGINX on LB one.  Create rancher-cluster.yml file with node information and proxy info.

**Result:**
Failed to apply the ServiceAccount needed for job execution: Post https://my.ip:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=30s: CONNECTnotallowed

**Other details that may be helpful:**
Behind a corporate proxy.  Proxy configured at ~/.docker/config.json and /etc/systemd/system/docker.service.d/proxy.conf
Able to do single node install with proxy settings specified without issue

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
Cluster is on VMware vCenter 6.5
- Docker version (use `docker version`):
18.09

This has been very frustrating.  Looked around everywhere, Rancher slack, Rancher forum, google, nothing I can find helps me get Rancher to install using rke in an HA cluster setup.  This all worked before we had a proxy, now I'm rebuilding with the proxy and I'm unable to do so.  Seems like I need to configure the rancher-cluster.yml in some specific way, but nothing I do works.   What I have currently is below:

nodes:
  - address: 10.0.0.1
    user: testuser
    role: [controlplane,worker,etcd]
  - address: 10.0.0.2
    user: testuser
    role: [controlplane,worker,etcd]
  - address: 10.0.0.3
    user: testuser
    role: [controlplane,worker,etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

---
kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        # Rancher install via RKE addons is only supported up to v2.0.8
        - image: rancher/rancher:v2.0.8
          imagePullPolicy: Always
          name: cattle-server
          env:
         - name: HTTP_PROXY
            value: "http://my.proxy:myport"
          - name: HTTPS_PROXY
            value: "http://my.proxy:myport"
          - name: NO_PROXY
            value: "localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,.my.domain"
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server

So what am I missing?  This is driving me nuts and I feel like I'm just some simple solution away from moving forward on this.

**Comment by superseb** [comment]
The RKE repo has an issue with the error here https://github.com/rancher/rke/issues/669, as the proxy config is not shared it's hard to tell what is wrong. Let me know if the solutions in that issue solve it, if not, please file it in the RKE repository as it seems you are hitting the issue using RKE CLI so we can investigate.

Also, not related to this issue, please note that v2.0.8 was released in August 2018 and is not recommended for use anymore. It is highly recommended to use a recent version using the steps described on https://rancher.com/docs/rancher/v2.x/en/installation/ha/

**Comment by emcclure78** [comment]
Unfortunately the link you provided did not work for me.  That was the first thing that came up when I got the error.  I am also installing Rancher using rancher/rancher:latest, which gives me 2.2.4 at the moment and I've been using the steps in the link you provided.

**Comment by emcclure78** [comment]
Opened issue here: https://github.com/rancher/rke/issues/1421
