### ISSUE TITLE
Derive Rancher supported Kubernetes Version for a clustertemplate

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#21084]
While creating a ClusterTemplate, template creator has a choice to

---- option a) Template creator can set exact K8sversion as value to this field. This will lock the k8sversion for this template revision. Values could be (1.14.3, 1.15.x)

---- option b) Template creator can turn this into a Question on the templaterevision (with a k8s range set using min/max). 

In both cases, we need backend processing to derive the Rancher supported Kubernetes version while creating a cluster from this template.

**Comment by prachidamle** [comment]
For:
 option b) Template creator can turn this into a Question on the templaterevision (with a k8s range set using min/max).

We will be supporting setting the KubernetesVersion into a Question. But setting a min/max range will not be supported right now.

**Comment by sangeethah** [comment]
Tested with rancher server version built from master - `f9aa0fe1`
We are now allowed to create clusterTemplateRevisions with versions in the following format - 
`{"rancherKubernetesEngineConfig": {"kubernetesVersion": "1.14.x"}}`
`{"rancherKubernetesEngineConfig": {"kubernetesVersion": "1.14.3"}}`

In both the cases we have cluster getting created with the `kubernetesVersion` set to correct image -`v1.14.3-rancher1-1`.

Related issue when creating clusters with invalid kubernetesVersion format - https://github.com/rancher/rancher/issues/21328
https://github.com/rancher/rancher/issues/21328

When having `kubernetesVersion` set to format like `1.15.x` , there could be a potential issue of cluster's k8s version getting upgraded when any update it attempted on the cluster.

Consider this scenario where a cluster was created with template revision that has following 
```
configuration:
"clusterConfig": {
"dockerRootDir": "/var/lib/docker",
},
"questions": [ 2 items
{
"default": "1.15.x",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": true,
"type": "string",
"variable": "rancherKubernetesEngineConfig.kubernetesVersion"
},
{
"default": "false",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": false,
"type": "boolean",
"variable": "rancherKubernetesEngineConfig.services.etcd.snapshot"
}
],
```
Create a cluster with this template revision with no answers.
Cluster gets created with snapshot set to "false" and k8s version set to `v1.15.0-rancher1-1` as expected.

Include support for another minor version of `v1.15`  say  `v1.15.1-rancher1-1`.

Edit the cluster to enable snapshot by passing following in answers section 
```
           "values": {

                "rancherKubernetesEngineConfig.services.etcd.snapshot":"true"

            }
```

With the current logic, this would result in k8s version of the cluster being upgraded to `v1.15.1-rancher1-1` (which is the latest at this point).

This should not be the case.

Reopening this ticket, to address this issue after discussing with @prachidamle .

**Comment by prachidamle** [comment]
New changes to this ticket:
---- If a template specifies Kubernetes version of the format 1.14.x, a Question for the "rancherKubernetesEngineConfig.kubernetesVersion" should also be set - API will error out if a question is not added. If using UI, UI will be adding a question before calling API.

---- When a cluster is created from a clusterTemplate that specifies the k8sversion of a format 1.14.x
backend will translate this to rancher supported kubernetes version on the create. If user does not provide an answer to the k8sversion Template Question, backend will use the default value on the Question for translation.

---- On editing such a cluster, if the answer to the k8sversion Template Question is not different, no translation will be done again. This prevents the auto-upgrade to newer version as was seen on earlier tests.

---- If user wants to upgrade the cluster to newer k8sversion, he/she should set the new answer(with specific k8sversion or higher patch as 1.15.x) on cluster edit or change the templateRevision having a newer k8s support.

**Comment by sangeethah** [comment]
Tested with build from master:

Scenario 1:

When creating a cluster template from UI with kubernetes version set to `1.14.x` (no override) , template gets created with the following questions:

```
 "questions": [
{
"default": "1.14.x",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": false,
"satisfies": ">=1.14.0 <1.15",
"type": "string",
"variable": "rancherKubernetesEngineConfig.kubernetesVersion"
}
]
```

When creating a cluster with this template, only all the  1.14.x versions will be presented as options to be picked for K8s version.

<img width="615" alt="Screen Shot 2019-08-06 at 1 54 00 PM" src="https://user-images.githubusercontent.com/4266958/62576479-d19b7a00-b851-11e9-957b-bbb32401845d.png">


Scenario 2:
When creating a cluster template from UI with kubernetes version set to `1.14.x` with override , template gets created with the following questions:

```
"questions": [
{
"default": "1.14.x",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": false,
"type": "string",
"variable": "rancherKubernetesEngineConfig.kubernetesVersion"
}
],
```

<img width="576" alt="Screen Shot 2019-08-06 at 2 00 29 PM" src="https://user-images.githubusercontent.com/4266958/62576897-9b122f00-b852-11e9-8c80-1332b8d1ab88.png">

**Comment by sangeethah** [comment]
UI issues relating to editing clusters that are created with templates having kubernetes version set to 1.14.x (with and without overrides)  -   https://github.com/rancher/rancher/issues/22021
