### ISSUE TITLE
rancher ui - host os unknown [rancherOS]

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2108]
I just updated `rancher/server` and discovered that hosts show their OS. For Ubuntu it works fine but it does not recognize rancherOS which is kind of sad. :/

**Comment by alex88** [comment]
Have you updated also the agents?

**Comment by fentas** [comment]
Jop. Restarted the whole thing. @alex88 Is it working for you?
~ maybe useful. I using the `rancheros-033-gce-01.tar.gz` image.

**Comment by alex88** [comment]
@fentas I don't have rancherOS images except the UI, just ubuntu! Just wanted to try to help

**Comment by ibuildthecloud** [comment]
It is sad 😞.  This works in RancherOS 0.4, but we have still yet to release that.  The issue is really in RancherOS and not Rancher.  When v0.4 is released it will work.

**Comment by deniseschannon** [comment]
With the release of v0.4.0 of RancherOS, the `RancherOS` is on the hosts page. 

Verified with v0.47.0 of Rancher
