### ISSUE TITLE
Unable to enable monitoring with PSP enabled

### ISSUE THREAD

**Issue by usvgmani** [rancher/rancher#21082]
> Unable to enable monitoring with PSP enabled I have just set no privilege escalation and user mustrunasnonroot, below is the policy set. The monitoring ds in cattle-promotheus does not start, has the error no policy to validate against. 

-----------------
Policy: no-root
Allow Privilege Escalation
No
Default Allow Privilege Escalation
No
Host IPC
Yes: The use of host’s IPC namespace
Host Network
Yes: The use of host networking
Host PID
Yes: The use of host’s PID namespace
Privileged
No
Read Only Root Filesystem
No
Allowed Capabilities
AUDIT_CONTROL , AUDIT_WRITE , BLOCK_SUSPEND , CHOWN , DAC_OVERRIDE , DAC_READ_SEARCH , FOWNER , FSETID , IPC_LOCK , IPC_OWNER , KILL , LEASE , LINUX_IMMUTABLE , MAC_ADMIN , MAC_OVERRIDE , MKNOD , NET_ADMIN , NET_BIND_SERVICE , NET_BROADCAST , NET_RAW , SETFCAP , SETGID , SETPCAP , SETUID , SYSLOG , SYS_ADMIN , SYS_BOOT , SYS_CHROOT , SYS_MODULE , SYS_NICE , SYS_PACCT , SYS_PTRACE , SYS_RAWIO , SYS_RESOURCE , SYS_TIME , SYS_TTY_CONFIG , WAKE_ALARM Default Add Capabilities
AUDIT_CONTROL , AUDIT_WRITE , BLOCK_SUSPEND , CHOWN , DAC_OVERRIDE , DAC_READ_SEARCH , FOWNER , FSETID , IPC_LOCK , IPC_OWNER , KILL , LEASE , LINUX_IMMUTABLE , MAC_ADMIN , MAC_OVERRIDE , MKNOD , NET_ADMIN , NET_BIND_SERVICE , NET_BROADCAST , NET_RAW , SETFCAP , SETGID , SETPCAP , SETUID , SYSLOG , SYS_ADMIN , SYS_BOOT , SYS_CHROOT , SYS_MODULE , SYS_NICE , SYS_PACCT , SYS_PTRACE , SYS_RAWIO , SYS_RESOURCE , SYS_TIME , SYS_TTY_CONFIG , WAKE_ALARM Required Drop Capabilities
AUDIT_CONTROL , AUDIT_WRITE , BLOCK_SUSPEND , CHOWN , DAC_OVERRIDE , DAC_READ_SEARCH , FOWNER , FSETID , IPC_LOCK , IPC_OWNER , KILL , LEASE , LINUX_IMMUTABLE , MAC_ADMIN , MAC_OVERRIDE , MKNOD , NET_ADMIN , NET_BIND_SERVICE , NET_BROADCAST , NET_RAW , SETFCAP , SETGID , SETPCAP , SETUID , SYSLOG , SYS_ADMIN , SYS_BOOT , SYS_CHROOT , SYS_MODULE , SYS_NICE , SYS_PACCT , SYS_PTRACE , SYS_RAWIO , SYS_RESOURCE , SYS_TIME , SYS_TTY_CONFIG , WAKE_ALARM
Volumes
*
Allowed host path policy
None
Fs Group Policy
RunAsAny - No default provided. Allows any fsGroup ID to be specified.
Host Ports Policy
None
Run as User policy
MustRunAsNonRoot - Requires that the pod be submitted with a non-zero runAsUser or have the USER directive defined in the image. No default provided.
SELinux poliicy
RunAsAny - Allows any seLinuxOptions to be specified
SupplementalGroups poloicy
RunAsAny - No default provided. Allows any supplementalGroups to be specified.
Labels
Key*	 	Value	 
cattle.io/creator=	norman
lifecycle.cattle.io/create.cluster-pspt-sync_local=	true
lifecycle.cattle.io/create.mgmt-pspt-lfc-handler=true
 	

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.cluster.monitoring.cluster-setting`|

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/20229
