### ISSUE TITLE
Backport: Add k8s 1.15 support 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21088]
Backport https://github.com/rancher/rancher/issues/20986

**Comment by sangeethah** [comment]
Tested with latest build using `rancher/rancher:v2.2-head`.
k8s 1.15 is now presented as "Experimental" when creating RKE clusters.

<img width="654" alt="Screen Shot 2019-06-25 at 9 28 30 PM" src="https://user-images.githubusercontent.com/4266958/60151079-3dd58900-9790-11e9-831f-c0166ecf4360.png">


Created a K8s 1.15 custom cluster with following node configuration with docker version - 18.09.6 and OS version - Ubuntu 16.04 :
1 control node
3 etcd nodes
3 worker nodes

All existing automation runs succeeded.
