### ISSUE TITLE
Reduce the etcd snapshot save/restore time for large data sizes

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21092]
Version: v2.2.5-rc3/master

Tested with rancher version v2.2.5-rc3.

Steps:

Created Custom cluster with 3etcd only nodes, 1 control/worker node .
S3 Minio configuration was set for etcd backups

Exec into one of the etcd nodes. (The etcd nodes were 2core with 4G RAM)
Create dummy file: dd if=/dev/zero of=testfile.out bs=1500 count=1024
for i in seq 1 1000; do cat testfile.out | etcdctl put key; done
etcd was filled up to 1.8G
docker exec etcd etcdctl endpoint status --endpoints=172.31.x.x:2379 --write-out table
etcd was filled up to 1.8G
sudo docker exec etcd etcdctl endpoint status --endpoints=172.31.x.x:2379 --write-out table
2019-06-14 23:33:54.478207 W | pkg/flags: recognized environment variable ETCDCTL_ENDPOINTS, but unused: shadowed by corresponding flag
+-------------------+------------------+---------+---------+-----------+-----------+------------+
| ENDPOINT | ID | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-------------------+------------------+---------+---------+-----------+-----------+------------+
| 172.31.x.x:2379 | 20982de1189c445c | 3.3.10 | 1.8 GB | true | 4 | 4242 |
+-------------------+------------------+---------+---------+-----------+-----------+------------+

Snapshot was taken and it completed in around 5mins
Restore was also performed and it completed in around 6 mins

Snapshot and restore time seems high for 1.8 G of data. It should not take this long for 1.8G of data

Note: On a master setup, increased the etcd default size by providing "quota-backend-bytes" as below
```
services:
    etcd:
      extra_args:
        quota-backend-bytes: SIZE_IN_BYTES
```
Verified the setting by doing a docker inspect on the etcd container. 

With this config, filling etcd with more than 2G data was failing with error as below.
```
Error: context deadline exceeded
Error: context deadline exceeded
Error: context deadline exceeded

```
```
sudo docker exec etcd etcdctl endpoint status --endpoints=172.31.6.x:2379 --write-out table
2019-06-24 21:45:59.106350 W | pkg/flags: recognized environment variable ETCDCTL_ENDPOINTS, but unused: shadowed by corresponding flag
+-------------------+------------------+---------+---------+-----------+-----------+------------+
|     ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-------------------+------------------+---------+---------+-----------+-----------+------------+
| 172.31.6.x:2379 | 9836003550d8a14d |  3.3.10 |  2.0 GB |     false |         2 |       1467 |



```

Exited from the data write process and tried to do a snapshot with 2G data.  It took around 20mins for the snapshot to complete. Restore took around 6mins.

**Comment by superseb** [comment]
@soumyalj Can you test this with the recommended node size (2CPU/8GB RAM)
