### ISSUE TITLE
Backport: Add node driver support for Pinganyun ECS

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21097]
https://github.com/rancher/rancher/issues/20878

**Comment by kingsd041** [comment]
I added the Pinganyun ECS cluster using `rancher/rancher: v2.2-head` and did a simple test and it works fine.

**Comment by kingsd041** [comment]
Adding a node using the Pinganyun node driver sometimes creates multiple duplicate Pinganyun instances at the same time and cannot be deleted automatically.

**Comment by JacieChao** [comment]
Sometimes, Pinganyun ECS will take a very long time to create/stop an instance, this will cause waiting timeout, and that kind of instances can't be deleted automatically.

**Comment by kingsd041** [comment]
Verified fixed
