### ISSUE TITLE
Add copy to clipboard icons for internal / external ip as well

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21096]
Originated from https://github.com/rancher/rancher/issues/19897
Version: master-head (6/24/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
- Visit new node dashboard page.
- Notice we have a copy to clipboard icon for the hostname but not the internal and external ip address. (Create an EC2 cluster to see both internal and external)

**Result:**
We need consistency. We need to add the clipboard icon to both internal and external ip. Also needs to work if we only have external ip from API.

**Comment by lvuch** [comment]
Looking at this further the core of the issue is that there are two components: copy-inline (sans icon) and copy-to-clipboard (has icon). I'm not sure why we have two or if there's an explanation for the use of no icon in certain places. @westlywright Do you know? I can provide a list of where copy-inline is used.

For now I'm converting this one to copy-to-clipboard versus modifying copy-inline.

**Comment by westlywright** [comment]
fixes merged into master.

**Comment by davidnuzik** [comment]
Version: master-head (7/1/19)

I can confirm that the clipboard now appears next to IPs:

From nodes page:
![Screen Shot 2019-07-01 at 2 43 59 PM](https://user-images.githubusercontent.com/45179589/60468543-d6e02600-9c0e-11e9-9240-02f923dfca4e.png)

Node dashboard page:
![Screen Shot 2019-07-01 at 2 45 26 PM](https://user-images.githubusercontent.com/45179589/60468567-ec555000-9c0e-11e9-856a-c95e5afdf6f4.png)

Both work with ec2 as well (has both internal and external ips)
![Screen Shot 2019-07-01 at 2 53 07 PM](https://user-images.githubusercontent.com/45179589/60468929-fc216400-9c0f-11e9-8275-67a0db336de4.png)

![Screen Shot 2019-07-01 at 2 51 45 PM](https://user-images.githubusercontent.com/45179589/60468904-eb70ee00-9c0f-11e9-85b9-23cbc36ed70d.png)

This is functionally working as well, I can click on the clipboard icon and it will still copy properly (anywhere on whole string including clipboard icon works for copy). The mouse over still happens as well to indicate that I only need to click to copy.
