### ISSUE TITLE
Fix node dashboard "Docker Version" to change label to "Containerd Version" when containerd detected

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21099]
Originated from https://github.com/rancher/rancher/issues/19897
Version: master-head (6/24/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create k3s cluster, import into rancher
- View node dashboard

**Result:**
Node dashboard incorrectly shows "Docker Version: containerd <version>"
Darren asked to fix this so that it shows label as "Containerd Version: <version>"

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/18593 for details to consider, `unknown` seems to be filtered in node list view but not in the node detail view. Also, k8s uses `containerRuntimeVersion` for container runtime.

**Comment by deniseschannon** [comment]
@sowmyav27 This was merged into the UI before 2.3 shipped so even though it's 1 PR it's available in 2.3-head and master.

**Comment by sowmyav27** [comment]
Verified in 2.3-head
Ui tag: `latest-2.3`

- Import a k3s cluster
- Node dashboard incorrectly shows "Docker Version: containerd "
<img width="1330" alt="Screen Shot 2019-11-04 at 11 43 13 PM" src="https://user-images.githubusercontent.com/26032343/68146024-158b4180-ff5d-11e9-8e9b-e975ab0e96d2.png">

**Comment by dnoland1** [comment]
Should we just consider having a more generic label like "Container Version", "Runtime Version", or "Container Runtime"? That way when we support a 3rd container type, we don't need to make another change.

**Comment by sangeethah** [comment]
Tested with latest build from `v2.3-head` .
Containerd version shows up as expected on imported k3s clusters:
`Containerd Version: 1.3.0-k3s.4`

<img width="908" alt="Screen Shot 2019-11-06 at 5 51 12 PM" src="https://user-images.githubusercontent.com/4266958/68353347-1edfef80-00be-11ea-8871-998907ccaece.png">
