### ISSUE TITLE
Backport: s3 Snapshot service to trust internally signed certs when talking to the S3 endpoint

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21103]
Backport https://github.com/rancher/rancher/issues/19222

**Comment by sowmyav27** [comment]
verified with rancher:v2.2-head - latest - 06/26/2019

Able to reproduce the issue without providing certs from the API/UI.

1. Launch a minio server with Self-signed Keys and Certificates.
2. Configure this as S3 snapshot details while creating a cluster - 1 node. Do not pass `customCa`. 
3. Error seen in the logs after taking a snapshot

```
2019/06/26 22:12:26 [WARNING] Failed to take one-time snapshot, exit code [1]: time="2019-06-26T22:12:25Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:sowmya-test, err:Get https://x.x.x.x:9000/sowmya-test/?location=: x509: certificate signed by unknown authority" 
```

- Now give in the `customCa` through the API.
- Create a cluster - 1 node.
- Take a snapshot from the UI. It will be stored successfully in the configured minio-bucket.
- Restore from the snapshot, the cluster is restored from the snapshot successfully.
- Add two etcd nodes, Take a snapshot again. 
- Snapshot is taken successfully.
- Restore from the snapshot, restore happens successfully.
