### ISSUE TITLE
UI will load js files even for inactive cluster drivers

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21108]
rancher/rancher:v2.2.4

Steps:

1. Do not enable Baidu cluster driver
2. Click `Add Cluster`
3. Check the network tab in Chrome. 

Results:

UI will load js files even for inactive cluster drivers

Expected:

UI should load js and ccs files only for active cluster drivers

Cluster edit will also fail and needs to be tested.

**Comment by davidnuzik** [comment]
@sowmyav27 may I ask for you to do same test as in the Backport when you have time?

I will do my test as well just like we did in the backport issue.

**Comment by sowmyav27** [comment]
verified with `rancher:master-head`(latest - 06/26/2019)
**Steps:**
1. Launch rancher server with custom 2.2.4 image(30 mins cert expiry)
2. Create a do cluster (3 nodes)
3. Upgrade to rancher:master-head. Let the certs expire. Do a Rotate Certificates on the cluster.
4. The cluster comes up `active`.
5. Do an edit cluster. There is no error seen. Save any changes made. No error seen on the UI

The `ui-index` is `https://releases.rancher.com/ui/latest2/index.html`

**Comment by davidnuzik** [comment]
**Reproduction:**
See https://github.com/rancher/rancher/issues/21109#issuecomment-505664409
(Already reproduced)

**Validation:**
Version: master-head

- Activate Baidu cluster driver. Click on Add cluster, we see appropriate component.js files load.
- Disable it.
- Again watch http traffic, now click on the add cluster button - notice we no longer load baidu component.js/css files (fixed).
