### ISSUE TITLE
Tiller crashes when downgrading while upgrading

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#21115]
Hey there,

I just had the following problem: I wanted to upgrade a package installed via ranchers catalogs. This package had an error which stopped it from updating. So I decided to roll it back. However, this doesn't work. In the rancher logs I found out that actually tiller is crashing now b/c it can't receive the history.

```
[main] 2019/06/25 13:45:20 Starting Tiller v2.10+unreleased (tls=false)

[main] 2019/06/25 13:45:20 GRPC listening on :35775

[main] 2019/06/25 13:45:20 Probes listening on :39968

[main] 2019/06/25 13:45:20 Storage driver is ConfigMap

[main] 2019/06/25 13:45:20 Max history per release is 1

[tiller] 2019/06/25 13:45:21 getting history for release gitlab

[storage] 2019/06/25 13:45:21 getting release history for "gitlab"

[tiller] 2019/06/25 13:45:21 preparing update for gitlab

[storage] 2019/06/25 13:45:21 getting deployed releases from "gitlab" history

[storage] 2019/06/25 13:45:21 getting last revision of "gitlab"

[storage] 2019/06/25 13:45:21 getting release history for "gitlab"

[storage] 2019/06/25 13:45:21 getting release history for "gitlab"

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12e8cc8]
```

**Comment by wzrdtales** [comment]
The worst thing about this is, the deployment is stuck and you can't upgrade or do anything with it anymore now.

**Comment by wzrdtales** [comment]
I could work around, by manually creating and copying the latest tiller artifact (release.vXX) and create the version before this version. It seems like for some reason the tiller artifacts from the config map are being deleted to early. Might be a problem introduced with the max history fix from the last version @superseb

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/21070
