### ISSUE TITLE
Backport: No more alert after upgrade rancher server

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21113]
https://github.com/rancher/rancher/issues/20975

**Comment by loganhz** [comment]
For regression test,

Please make sure

1. Enable cluster alerting in 2.2.3 and upgrade to 2.2.5, cluster alerting app can be upgraded successfully
2. Enable cluster alerting in 2.2.4 and upgrade to 2.2.5, cluster alerting app can be upgraded successfully
3. Cluster alerting still functional after upgrade to 2.2.5
4. There is no prometheus operator deployed in cluster-alerting app
5. There is only one prometheus operator deployed in monitoring-operator app

**Comment by jiaqiluo** [comment]
The bugfix is validated on the upgrade path from v2.2.3 -> v2.2-head
- Enable cluster alerting in 2.2.3 and upgrade to v2.2-head, cluster alerting app can be upgraded successfully
- Cluster alerting is still functional after upgrade to v2.2-head
- There is no Prometheus operator deployed in the cluster-alerting app
- There is only one Prometheus operator deployed in monitoring-operator app
<img width="1433" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60133795-f977c800-9752-11e9-830b-eedbd7b02365.png">


---------

Failed to validate the bugfix on the upgrade path from v2.2.4 -> v2.2-head 

The following is as expected 
- Enable cluster alerting in 2.2.4 and upgrade to v2.2-head, cluster alerting app can be upgraded successfully
- Cluster alerting is still functional after upgrade to v2.2-head
- There is only one Prometheus operator deployed in monitoring-operator app

BUT
- **There is a  Prometheus operator deployed in cluster-alerting app**
<img width="1426" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60133970-56737e00-9753-11e9-84d6-6f2c0a2e048a.png">

<img width="1413" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60134933-7b68f080-9755-11e9-85ff-4a5a0ee6e103.png">

@loganhz @aiwantaozi Is it expected? Why one `cluster-alerting` has the `prometheus-operator-cluster-alerting` but another one does not? They are the same version.

**Comment by davidnuzik** [comment]
@jiaqiluo please try changing ui-index (under settings) to https://releases.rancher.com/ui/2.2.79/index.html
Make sure browser cache is cleared.

**Comment by jiaqiluo** [comment]
@loganhz @aiwantaozi

The workload `prometheus-operator-cluster-alerting` under the `cluster-alerting` is gone ~10 mins after I post my last comment.  Is it just a timing issue?

<img width="1413" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60136281-9be67a00-9758-11e9-9648-3ee7ba543a9d.png">
<img width="1430" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60136290-9ee16a80-9758-11e9-845d-69b6551627c8.png">

**Comment by aiwantaozi** [comment]
Hi @jiaqiluo After the server upgrade, latest catalog log will be downloaded, after that alert can get a new version template. if the upgrade trigger before the catalog download before latest catalog download, it will not be upgraded, because no new version found. When project crd object update or next resync interval coming(2h), the upgrade will be triggered.

**Comment by loganhz** [comment]
@jiaqiluo From the code, it looks like it will never get removed in your case. I don't understand why it went away after 10mins. Did you do something during the 10 mins? Like remove the recipients and add them back? 

@aiwantaozi created another PR to fix your case.  

https://github.com/rancher/rancher/pull/21152

**Comment by jiaqiluo** [comment]
@loganhz I tested the upgrade path from `v2.2.4` to `v2.2-head` again, it looks like the issue I met is fixed. but there are some new findings on the cluster which has only the altering enabled, please read the following for details.

Is it the expected result: for the cluster which has only altering enabled, the workload `prometheus-operator-cluster-alerting` still exist after upgrading? 

Steps:
- run Rancher:v2.2.4 container
- add `cluster1`: single-node DigitalOcean
- add `cluster2`: single-node DigitalOcean
- in `cluster1`, enable the cluster monitoring -> add a notifier -> add a new cluster-level alter group -> use the notifier as reciver
- in `cluster2`, add a notifier -> add a new cluster-level alter group -> use the notifier as reciver

At this stage:

`cluster1` has 
 1. app `cluster-altering` v0.0.3
  |- worklaod `prometheus-operator-cluster-alerting`
  |- worklaod `alertmanager-cluster-alerting`
2. app `monitoring-operator` v0.0.3
 |- workload `prometheus-operator-monitoring-operator` 

`cluster2` has 
 1. app `cluster-altering` v0.0.3
 |- worklaod `prometheus-operator-cluster-alerting`
 |- worklaod `alertmanager-cluster-alerting`
2. app `monitoring-operator` v0.0.3
 |- workload `prometheus-operator-monitoring-operator` 
3. app `cluster-monitoring` v0.0.3
 |-  4 worklaods

- upgrade Rancher to v2.2-head

After upgrading is finished, alerting still works on both clusters, and 

- for `cluster1`, there is no change, it still have the same number of apps and the workloads as before
- for `cluster2`, the workload `prometheus-operator-cluster-alerting` is removed from the app `cluster-altering`

**Comment by loganhz** [comment]
@jiaqiluo for `cluster1`, I think it will get removed eventually. @aiwantaozi can you look at this issue, please?

**Comment by aiwantaozi** [comment]
Hi @jiaqiluo the upgrade will be triggered when 
1. after rancher server start/upgraded(because all the controller sync will be called at this time.
2. project crd object updated
3. regular interval sync (every two hours)
I have tried the same step but the ```prometheus-operator-cluster-alerting``` is removed

**Comment by jiaqiluo** [comment]
I tested the upgrade path from v2.2.4 to v2.2-head again, the steps are the same as my previous comment: https://github.com/rancher/rancher/issues/21113#issuecomment-506074671

This time for `cluster1`, the workload `prometheus-operator-cluster-alerting` is removed from the app `cluster-altering` after upgrading Rancher, which is expected.

The tests should be sufficient to validate the bug fix.

**Comment by jiaqiluo** [comment]
The following upgrading path has been covered:
- upgrade from Rancher v2.2.3 to 2.2-head
- upgrade from Rancher v2.2.4 to 2.2-head

The following cases are tested for both upgrading paths:
- a cluster which has both cluster monitoring and cluster altering enabled
- a cluster which has only the cluster altering enabled

The issue is closed.

**Comment by loganhz** [comment]
Due to issue https://github.com/rancher/rancher/issues/21364, I think we should reopen this issue.

If users have multiple clusters enabled alerting before upgrade to 2.2.5, users will still hit this issue in some clusters.
