### ISSUE TITLE
Logging integration doesn't work if Docker Root is not default /var/lib/docker

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#21112]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a server with Docker, but use a path other than /var/lib/docker for Docker's root. For example /data/var/lib/docker
2. Create a new custom cluster and add host above.
3. Set the Docker Root Directory to /data/var/lib/docker
4. Enable the logging integration.

**Result:**
The rancher-fluentd-logger is using /var/lib/docker as the dockerroot and will likely not be able to follow the symbolic links in /var/lib/rancher/rke/log/ to access the logs.

![image](https://user-images.githubusercontent.com/468462/60071457-02bf5100-96cf-11e9-8a27-f14024cd1a55.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.0-alpha5 (also reproducible on v2.2.4)
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
t3.medium
- Kubernetes version (use `kubectl version`):
1.14.3

- Docker version (use `docker version`):

```
$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:24:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:25:33 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by burakhoban** [comment]
Have you tried updating the pod via kubectl (or via UI)?

E.g. something like

- `kubectl get pod <container> -n cattle-logging --export -o yaml >> fluent.yaml`
- change path for dockerroot
- `kubectl apply -f fluent.yaml -n cattle-logging`

We had to do something similar when it came to cattle-agent falling over when our immediate CA certificates expired (there's no other nice way of doing it).

**Comment by dnoland1** [comment]
Sorry, should have mentioned that I was able to work around the problem by adding another mount to the fluentd container through the Rancher UI.

**Comment by corentin59** [comment]
@dnoland1 I have similar issue, 

![image](https://user-images.githubusercontent.com/2035983/61403229-2001cc80-a8d5-11e9-85c1-b2551d001720.png)

You make others changes ?

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 7e82f85f

When enabling logging, there is no field to change the default docker root; this can only be edited by editing answers after logging is already deployed. This field should be configurable from the logging setup page.

* Created Rancher server w/ non-default docker root
* Created custom cluster w/ non-default docker root
* Enable logging
* Test statement works correctly
* Logs do not come through
* Edit answers for logging app in system project of custom cluster to change docker root to the set directory
* Logs start to present

![Screen Shot 2019-07-23 at 8 41 06 AM](https://user-images.githubusercontent.com/21316915/61725969-a54a0e80-ad25-11e9-96a2-4d44debeb3c0.png)

**Comment by aiwantaozi** [comment]
@bmdepesa docker root could be configured under cluster option page

**Comment by bmdepesa** [comment]
The required field is present in cluster options.

**Comment by aiwantaozi** [comment]
Step to reproduce in HA mode local cluster.

server version: master

1. set up a ha mode rancher
2. enable logging for local cluster will get an error in app rancher-logging
```
Failed to install app rancher-logging. Error: release rancher-logging failed: DaemonSet.apps "rancher-logging-fluentd" is invalid: [spec.template.spec.volumes[1].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[4].name: Not found: "dockerroot", spec.template.spec.containers[0].volumeMounts[4].mountPath: Required value]
```
3. because local cluster is created by rancher backend controller, field dockerRootDir desen't exist for local cluster crd, this is a bit different from cluster created by UI.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 

* Reproduced in v2.2.7
  * Setup fluentd forward server
  * Created rke cluster where docker root is a different directory
  * Installed Rancher HA
  * Attempt to enable logging
  * Receive error
* Deploy rancher master-head in HA (2.2.8 chart, master-head image tag) with docker root as a different directory
* Enable logging
* Logging enabled successfully
* Logs are transported to fluentd server

**Comment by patrick0057** [comment]
This appears to be an issue still when upgrading from v2.2.8 to v2.3.1.

**Comment by bmdepesa** [comment]
@patrick0057 Was this working in v2.2.8 and then stopped working in v2.3.1?

**Comment by patrick0057** [comment]
@bmdepesa it was not working in v2.2.8 either.

**Comment by izaac** [comment]
Reproduced this issue in Rancher `v2.4.5` dockerroot volume doesn't get updated if we change the  Docker Root cluster value.

I checked this in an HA setup

Check workload `rancher-logging-fluentd-linux` in `System` project after provisioning/edit a cluster. 
App sets the answer `fluentd.cluster.dockerRoot` correctly in a custom cluster.
The app in the local HA cluster doesn't update the `fluentd.cluster.dockerRoot` answer in the `rancher-logging` App in my testing is that expected @aiwantaozi ?

**Comment by aiwantaozi** [comment]
For imported cluster, it should also updated app's answer. But we don't support edit imported cluster docker root in the UI, how you do it? by editing API?

**Comment by straffalli** [comment]
> For imported cluster, it should also updated app's answer. But we don't support edit imported cluster docker root in the UI, how you do it? by editing API?

Yes it's possible to do it by creating cluster definition through Rancher API. We do it to import K8S clusters created with PKS with a custom DockerRootDir (`/var/vcap/store/docker/docker/containers`). 

It works fine and rancher-logging app answer is also updated. Does your fix will also update `fluentd.fluentd-linux.cluster.dockerRoot` app answer?

**Comment by izaac** [comment]
@aiwantaozi it's possible to set the `docker_root_dir` to a non-default path in the RKE yaml configuration for the `local` imported HA cluster.

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#docker-root-dir

**Comment by aiwantaozi** [comment]
@izaac Yes, you can set the docker root in rke yaml

**Comment by izaac** [comment]
Rancher version `v2.4-head (07/09/2020)` commit: 43c8db4e2
RKE version `1.1.4-rc1`

docker info for cluster nodes (Docker Root Dir: `/mnt/docker-data`):

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 34
  Running: 22
  Paused: 0
  Stopped: 12
 Images: 14
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1023-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.798GiB
 Name: ip-172-31-41-54
 ID: CJES:7KO2:7AJT:NNHN:4AHN:R4YA:NX7Q:QLKD:XRHN:MDQV:7XQ4:7LMK
 Docker Root Dir: /mnt/docker-data
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

1. Import RKE cluster with nodes using a non-default `Docker Root Dir` from Rancher UI.
2. Enable Cluster Logging integration.
3. Check Project `System` -> Workload `rancher-logging-fluentd-linux` -> volumes
4. Volume `dockerroot` path and mount point are the default `/var/lib/docker`

![Screen Shot 2020-07-09 at 8 09 28 AM](https://user-images.githubusercontent.com/27659/87057385-a46eee80-c1bb-11ea-80a4-332814fb8b78.png)

If we check the container logs in the `rancher-logging-fluentd-linux` workload we can see the following warnings:

```
2020-07-09 15:11:10 +0000 [warn]: #0 /var/log/containers/canal-lgktl_kube-system_install-cni-76795ddcad092ef962a194adca71af1bfab5856763a641259683c5d7b1664f75.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/log/containers/rancher-logging-fluentd-linux-j2xgw_cattle-logging_rancher-logging-fluentd-reloader-66bb658176fc384e5ed4c4b307e557fd112705565b11facc91a8b37789355315.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/log/containers/rke-metrics-addon-deploy-job-866rd_kube-system_rke-metrics-addon-pod-a645d88fa2512f208a41391dcd429e603fbcefb54fdf7a8bd76dd7d9f5635231.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/log/containers/nginx-ingress-controller-hnslb_ingress-nginx_nginx-ingress-controller-e45d17d659779e5ac8220376351b66b79c1c25027eb9238cd6e6f7a5e16022a3.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/log/containers/canal-lgktl_kube-system_calico-node-6370394008c0a662c2114fc47742715cd80a6840bead40d7b0a033efb2e73b55.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/log/containers/cattle-node-agent-8r2l7_cattle-system_agent-2e1d89bb43b3f8bf0947448a0996c225e6f85be639c9b117ce8e7ddcd6e9c389.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/lib/rancher/rke/log/kube-apiserver_f7549d6cd823a99938c35f495b336120c1a0b6264aca9d482cc30d06c4469b8e.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/lib/rancher/rke/log/etcd_4df6cb2d5b7544714f6cf6ebb34980d1c3f57009f0a231931fbfde425817ad09.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/lib/rancher/rke/log/kube-scheduler_6b6eef43634dcfabb136bf40f5ce6d8b42a081ef81c6f7f0c6c6e86b9fd1741f.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/lib/rancher/rke/log/kube-controller-manager_5e6cf8d8b7da0be299bae56df7362cab2675e3c4d0e58ae980a9f6fcdbc9efff.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/lib/rancher/rke/log/kube-proxy_e782399c46ff58bfb5f0385f9c6687980a173b76b1a41a9a53895ddf89accf9d.log unreadable. It is excluded and would be examined next time.
2020-07-09 15:11:10 +0000 [warn]: #0 /var/lib/rancher/rke/log/kubelet_45835a081779f944aeb5d374b86c8702d977ce3cb2812415651dcdf60df18634.log unreadable. It is excluded and would be examined next time.
```

**Comment by aiwantaozi** [comment]
@izaac  Sorry I misinterpreted your question, for local cluster, rancher has a setting to configure init docker root the local cluster. CATTLE_INITIAL_DOCKER_ROOT_DIR could set in the environment to update the local cluster docker root. For example ``` docker run -itd -p 8443:443 -p 8080:80 -e CATTLE_INITIAL_DOCKER_ROOT_DIR=/data rancher/rancher:master --add-local=true```. For normally imported cluster need UI to support that open that configure when add imported cluster.

**Comment by izaac** [comment]
@aiwantaozi thanks for the explanation I checked this in an actual HA install in Rancher `v2.4.6-rc4` and `master-head (07/10/2020)` 8a032e73b  to check the imported local cluster.

Example `helm` command to install Rancher with a non-default docker root:

`helm_v3 install rancher rancher-latest/rancher --version v2.4.6-rc4 --namespace cattle-system --set hostname=<hostname> --set 'extraEnv[0].name=CATTLE_INITIAL_DOCKER_ROOT_DIR' --set 'extraEnv[0].value=/mnt/docker-data' `

After this enabling logging I see the `dockerroot` volume is set properly to `/mnt/docker-data` in the `rancher-logging-fluentd-linux` workload.
Logs were also sent properly to the external fluentd server.

**Comment by izaac** [comment]
As @straffalli [mentioned](https://github.com/rancher/rancher/issues/21112#issuecomment-654671462) imported clusters can also be configured to use a non-default `dockerRootDir` by editing the imported cluster definition and setting that json variable.

After this enabling logging I see the dockerroot volume is set properly to /mnt/docker-data in the rancher-logging-fluentd-linux workload.
Logs were also sent properly to the external fluentd server.

I've opened a separate improvement issue for that: https://github.com/rancher/rancher/issues/27896
