### ISSUE TITLE
Unable to complete cluster build with Rancher 2.2.5-rc6

### ISSUE THREAD

**Issue by emcclure78** [rancher/rancher#21125]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install single node Rancher behind proxy
Specify version v2.2.5-rc6
Create node templates
Create new cluster
Create nodes for cluster

**Result:**
Failure.  All machines constantly go thru loop of building, eventually say 'Docker is running' then fail to this error: 

  | Unable to find image  'rancher/rancher-agent:v2.2.5-rc6' locally  docker: Error response from daemon: Get  https://registry-1.docker.io/v2/: net/http: request canceled while  waiting for connection (Client.Timeout exceeded while awaiting  headers).  See 'docker run --help'.  Process exited with status 125 : exit status 1

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Installed with single node install
v2.2.5-rc6
- Docker version (use `docker version`):
18.09

**Comment by emcclure78** [comment]
From the single node I can run things like 'docker run hello-world' and have no issue.  If there's an alternate proxy spot to use instead of ~/.docker/config.json or /etc/systemd/system/docker.service.d/proxy.conf I'd like to know.  Seems most other things work with the proxy settings I have and the single node install works when I specify the proxy settings during the install.  Is there another location I need to configure the proxy to make this work?  Is this a Rancher issue?

**Comment by dsargent3220** [comment]
Make sure you are specifying both a proxy and a no proxy, like the below.
```sudo docker run -d \
  --restart=unless-stopped \
  --name rancher \
  --log-driver json-file \
  --log-opt max-size=100m \
  --log-opt max-file=3 \
  -p 80:80 -p 443:443 \
  -e HTTP_PROXY="http://your-proxy/" \
  -e HTTPS_PROXY="http://your-proxy/" \
  -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,localaddress,yourdomain.com,10.0.0.0/8" \
  -v /var/lib/rancher:/var/lib/rancher \
  -v /etc/rancher/ssl/cert.pem:/etc/rancher/ssl/cert.pem \
  -v /etc/rancher/ssl/key.pem:/etc/rancher/ssl/key.pem \
  rancher/rancher:v2.2.4 --no-cacerts```

**Comment by emcclure78** [comment]
So I did specify the proxy as shown above, but just with these commands:
--restart=unless-stopped \
-p 80:80 -p 443:443 \
  -e HTTP_PROXY="http://your-proxy/" \
  -e HTTPS_PROXY="http://your-proxy/" \
  -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,localaddress,yourdomain.com,10.0.0.0/8" \
   rancher/rancher:v2.2.5-rc6

So do I need those other items in there for a single node to work properly?  Is that why I'd get the same thing on a single node in 2.2.3, 2.3, etc?  If so the info here is missing info: https://rancher.com/docs/rancher/v2.x/en/installation/single-node/proxy/

**Comment by dsargent3220** [comment]
No, you shouldn't need more that what you have.  The rest is for storing Rancher config in an external directory and using our own certificates for encryption.

Just to be sure, you can run other docker workloads on all of your etcd, control plane and worker nodes, correct?
For example, you can `docker run hello-world` and it will pull the image and run correctly?
If not, you may be missing some proxy configs on those nodes themselves.

**Comment by emcclure78** [comment]
Hi @dsargent3220,

Yes.  My nodes are all based on a CentOS 7.6 template I created that has all the necessary proxy information in it.  So once I clone it I know all the nodes will work without having to make extra configurations.  As stated in this problem it's a single node setup, but I know I can pull things down without issue using 'docker pull' or 'docker run' commands.
