### ISSUE TITLE
Backport: Cluster remains in "Active" state when all 3 etcd nodes are powered OFF

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21122]
Backport https://github.com/rancher/rancher/issues/20927

**Comment by soumyalj** [comment]
Tested with release v2.2-head
K8s version : v1.14.3

Steps:
Create a custom cluster using S3 configuration with nodes as below:
N1 - control, worker
N2, N3, N4 - 3 etcds
Create a few workloads
Power off etcd nodes N2, N3, N4

After powering off the etcd nodes, the cluster changed to "Unavailable" state as expected.

![Screen Shot 2019-06-25 at 5 31 06 PM](https://user-images.githubusercontent.com/18536626/60151353-4ed2ca00-9791-11e9-96c2-fa2c06a76e22.png)

Cluster was accessible through UI. The etcd nodes were deleted and new nodes were added and cluster was restored from S3

**Comment by sangeethah** [comment]
Fix for this issue resulted in https://github.com/rancher/rancher/issues/21216

**Comment by soumyalj** [comment]
Tested with release v2.2.5-rc7
K8s version : v1.14.3

Steps:
Create a custom cluster using S3 configuration with nodes as below:
N1 - control, worker
N2, N3, N4 - 3 etcds
Create a few workloads
Power off etcd nodes N2, N3, N4

After powering off the etcd nodes, the cluster changed to "Unavailable" state as expected.

![Screen Shot 2019-07-01 at 1 10 07 PM](https://user-images.githubusercontent.com/18536626/60463813-cf665000-9c01-11e9-8d70-798ddcdcdc19.png)
