### ISSUE TITLE
Adding AWS keys error - TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by that0n3guy** [rancher/rancher#2113]
I just fired up a new rancher/server and when trying to add my AWS keys, I get the error below when I click "next: authenticate and select" :

```
TypeError: Cannot read property 'name' of undefined
```

I'm not sure if this bug belongs here, or in the UI repo.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/2104

This is being fixed in this week's release and coming out end of this week.

**Comment by that0n3guy** [comment]
Gotcha... thanks.   I didn't find it b/c the error was only in an image... not in the text so search didn't find it... thanks!

**Comment by deniseschannon** [comment]
@that0n3guy v0.39.0 was tagged this morning as latest and has this issue fixed.

**Comment by that0n3guy** [comment]
Yup, I've tested and I'm up and running.

**Comment by edit** [comment]
i have this error in the version Rancher 0.51.0 too.

**Comment by vytotas** [comment]
I also got this error in v.0.51.0

**Comment by hnaparst** [comment]
Same here in 1.1.4
