### ISSUE TITLE
v2.2.4 Pipeline authentication i/o timeout

### ISSUE THREAD

**Issue by ainiml** [rancher/rancher#21135]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
New Rancher cluster.
Add new Pipeline

**Result:**

```
Post http://gitlab.trawsasedsb01.172.17.0.5.xip.io/oauth/token: dial tcp 172.17.0.5:80: i/o timeout
```
![image](https://user-images.githubusercontent.com/28725423/60136336-e58f8e80-9771-11e9-8acb-1adbe902b8fa.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.4`
- Installation option (single install/HA): `single`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `custom`
- Machine type (cloud/VM/metal) and specifications (CPU/memory): `metal`
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by b0r1sp** [comment]
@ainiml did you find any fix for this issue? I'm in the same situation. Is your Gitlab instance located behind a proxy or ingress?

**Comment by ainiml** [comment]
@b0r1sp it's behind the Rancher Ingress using .xio to automatically setup a FQDN

I'm getting this error right now, which is making me want to go back to just using a `nginx` container.

The Rancher Ingress doesn't seem to be reliable enough to use. Though, it is very convenient to set up 

`Get http://gitlab.world0.192.168.86.10.xip.io/api/v4/projects/repo%2Fhev/repository/branches?per_page=100: dial tcp: lookup gitlab.world0.192.168.86.10.xip.io on 192.168.86.1:53: no such host`
