### ISSUE TITLE
Creating a cluster in API without a cluster template id but only template revision deploys a cluster without rancherKubernetesEngineConfig

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21130]
Version: Master

Steps:

1. Login to the setup as an admin and create a standard user "user1"
2. Login as "user1"
3. Create a cluster template "T1" in API and it succeeds
4. Create a cluster template revision "CTR1"  with rancherKubernetesEngineConfig in API
5. Create a cluster with out choosing template T1 and just choosing the revision "CTR1"

The cluster gets to "provisioning" state as an imported cluster . The cluster object gets created without rancherKubernetesEngineConfig . Should the cluster template not be associated with the template revision automatically ? 

The clustertemplateId is null
```
"clusterTemplateId": null,
"clusterTemplateRevisionId": "cattle-global-data:newctrfortemp1",

```
If a cluster template and template revision are both chosen, then the cluster gets to provisioning state as a Custom cluster

![Screen Shot 2019-06-25 at 1.39.28 PM.png](https://zube.io/files/rancher/1625d452a81590c539bd8a9a29de9de2-screen-shot-2019-06-25-at-1-39-28-pm.png)

**Comment by prachidamle** [comment]
The create Cluster API now accepts only clusterTemplateRevision.

**Comment by soumyalj** [comment]
Version: Master

Steps:
Login to the setup as an admin and create a standard user "user1"
Login as "user1"
Create a cluster template "T1" in API and it succeeds
Create a cluster template revision "CTR1" with rancherKubernetesEngineConfig in API
Create a cluster choosing the revision "CTR1". The cluster create API does not require a template . It just needs a template revision.

Snippet from Cluster API

```

},
"clusterTemplateId": "cattle-global-data:ct-c4vhg",
"clusterTemplateRevisionId": "cattle-global-data:rev1",


```

Create Cluster UI API

![Screen Shot 2019-07-09 at 10 46 07 AM](https://user-images.githubusercontent.com/18536626/60910915-d828d880-a236-11e9-9f6e-465488aaba0a.png)
