### ISSUE TITLE
Backport: Add support for k8s 1.13 on EKS

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21147]
Backport https://github.com/rancher/rancher/issues/20992

**Comment by davidnuzik** [comment]
Version: v2.2-head (ui-index 2.2.81)

Validated new UI option to pick 1.13 k8s version for EKS. Validated amazonElasticContainerServiceConfig. Smoke tested creating various EKS clusters including older k8s versions (make sure 1.12 creates 1.12, 1.11 creates 1.11, etc).
Validated that UI shows correct k8s version for the cluster and nodes.

HTTP looks good, API looks good, compare to AWS console looks good, all checks passed.

UI does not pick latest as default, but this is a separate issue tracked in #20759
