### ISSUE TITLE
  Add metadata field...to metadata

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2114]
Should let the user to define an arbitrary metadata which is gonna be propagated to Rancher metadata server.

Metadata will be a filed on the service object; type of the field in the API is map[json]
On the metadata server side, it will be accessible under:

`self/service.metadata`

`services/<servicename>.metadata`

@vincent99 @ibuildthecloud

**Comment by will-chan** [comment]
we should also allow containers to add metadata so that other containers form the same service can retrieve it.

**Comment by vincent99** [comment]
@alena1108 If you use angle brackets you have to escape them or put in backticks, it showed `services/.metadata` before and I was wondering why it would be a hidden dir :smile: (I fixed it in your comment)

Is there a reason we're mixing them in at the same level as services?  It seems weird to have

```
GET /services/

web/
web.metadata/
db/
db.metadata/
```

**Comment by alena1108** [comment]
@vincent99 my bad for not being precise/clear enough. By <servicename>.metadata I've actually meant that the metadata would be represented as a field on the service. Something like:

```
"service": {
    "name": "alena",
    "stack_name": "Default",
    "kind": "service",
    "hostname": null,
    "vip": "169.254.71.111",
    "external_ips": [
        
    ],
    "sidekicks": [
        
    ],
    "containers": [
        "Default_alena_1"
    ],
    "links": {
        
    },
    "ports": [
        
    ],
    "labels": {
        
    },
    "metadata": {
        "bar": {
            "foo": [
                {
                    "id": 0
                }
            ]
        }.........
```

**Comment by alena1108** [comment]
@will-chan can we treat container updating metadata service as a separate feature for now? As in this case the design might be slightly different - does container talk to metadata service directly? or is is supposed to call Rancher APIs to update a data on itself - container object - with the further propagation to the metadata service, from where other instances can read it.

@vincent99 @ibuildthecloud  ^^

**Comment by vincent99** [comment]
ah ok, that layout is good :smile:

Separate feature for update makes sense to me, especially if you want to be able to send the request to the metadata server, because it has no direct communication with the API today.

**Comment by alena1108** [comment]
@aruneli we have to test it using APIs before rancher-compose support is added. Reassigning to @ibuildthecloud for now

**Comment by aruneli** [comment]
@alena1108 ok, thanks for letting me know. You can assign to me once it is ready to test. We can sync up then.

**Comment by alena1108** [comment]
"metadata" field is supported in service.create and service.update

**Comment by sangeethah** [comment]
Tested with build made form master on Oct 6.

"metadata" field is now supported in service.create and service.update.

We are able to get "metadata" field as part of service when querying rancher-metadata.Works for service, LbService , DNS service and External Services.

service.update does not work for DNS service and External Services which is tracked in https://github.com/rancher/rancher/issues/2253
