### ISSUE TITLE
Join node to the master node

### ISSUE THREAD

**Issue by MohamedBenighil** [rancher/rancher#21158]
when I run rancher v2 (docker single node), it works fine. But when i would like to add a node to the cluster by selecting all options: i,e etcd, Control Plane and Worker, then i got this message:

![Capture](https://user-images.githubusercontent.com/49414837/60190453-f3591880-9832-11e9-9525-7afce7b6e6db.PNG)

Any help would be appreciated!

**Comment by loganhz** [comment]
Could you file a new issue and supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md) , please?
