### ISSUE TITLE
Rancher Single Node stopped working with 2019/06/26 16:00:38 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by checkelmann** [rancher/rancher#21161]
*Rancher stopped working with this error in the docker logs*

``
2019/06/26 16:00:38 [INFO] Waiting on etcd startup: Get https://localhost:2379/health: x509: certificate has expired or is not yet valid
`` 

![image](https://user-images.githubusercontent.com/584370/60199668-bac23a80-9844-11e9-9747-e5292f171f5f.png)

This looks like the same issue described here https://github.com/rancher/rancher/issues/20011

We had rancher 2.0.8 running so I changed back the system time a day, started the docker container and could update to 2.0.10 and hoped the issue would be fixed.

After changing back the system time to the current date, the problem was still there.

We have a rancher provisioned with our own certificates like described here (https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#custom-ca-certificate)
with the --no--cacerts flag

``
docker run --name rancher -d --restart=unless-stopped -v /var/lib/rancher:/var/lib/rancher -v /etc/rancher/fullchain.pem:/etc/rancher/ssl/cert.pem -v /etc/rancher/key.pem:/etc/rancher/ssl/key.pem -p 80:80 -p 443:443 rancher/rancher:v2.1.10 --no-cacerts
``

Our Certificates are valid until 2020.

In rancher there is no cacert listed as expected 
![image](https://user-images.githubusercontent.com/584370/60198912-0247c700-9843-11e9-8401-ff59eeccad9a.png)

But the API shows exactly the date we installed rancher with a created date one year ago.

``
{
"baseType": "setting",
"created": "2018-06-26T14:31:10Z",
"createdTS": 1530023470000,
"creatorId": null,
"customized": false,
"default": "",
"id": "cacerts",
"links": {
"remove": "…/v3/settings/cacerts",
"self": "…/v3/settings/cacerts",
"update": "…/v3/settings/cacerts"
},
"name": "cacerts",
"type": "setting",
"uuid": "92481b1f-794d-11e8-be4f-0242ac110002",
"value": ""
}
``

So it's not the Kubernetes Clusters Certificate which is expired but the rancher cacert which is not provided at all?!

**Is there any workaround to fix this issue?**

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.10` UI: `v2.1.23` |
|Route|`global-admin.clusters.index`|

It's a single Node installation

**Comment by oskapt** [comment]
Sorry to hear that you ran into this.

The instructions to fix it are on [our blog](https://rancher.com/blog/2019/kubernetes-certificate-expiry-and-rotation-in-rancher-kubernetes-clusters). Please go through those and then update this issue to let us know that the problem is resolved.

You can also find help on Slack - if you're not already there, you can request an invitation from https://slack.rancher.io.

**Comment by checkelmann** [comment]
Thank you for your reply, but the steps described are for k8s clusters provisioned by rancher where the certificate expired on the api server, but all certificates on our clusters are still valid.
Our first cluster was built in October (so still a couple months valid)

What I'm talking about is the rancher server itself which is running as a single node installation on one machine in a docker container.
The log I've posted is from the rancher container (docker logs rancher) not from any API Server.

As I said, all clusters were working fine and I'm able to connect to the API server with kubectl etc. directly. But rancher itself got this issue.

**Comment by SuperCipher** [comment]
@checkelmann does your rancher console show this too
![Screen Shot 2562-06-27 at 11 38 17](https://user-images.githubusercontent.com/6429197/60239540-476a0880-98d8-11e9-9b20-ec1c9b2ff62e.png)

**Comment by checkelmann** [comment]
Hi,

no the rancher UI was not accessible at all, as you can see in my docker run command in my first Post I'm using valid signed certificates from entrust and not nginx or a reverse proxy in front. 

When I'm chaning back the time on my rancher server and start the docker container I'm able to connect.

![image](https://user-images.githubusercontent.com/584370/60242485-0f51ce00-98b6-11e9-9c5d-9904dd6ea1e9.png)

This is the certificate on my machine.

**Comment by SuperCipher** [comment]
@checkelmann 
I hope this help.
![Screen Shot 2562-06-27 at 16 27 12](https://user-images.githubusercontent.com/6429197/60254659-860fbb00-98f8-11e9-8264-c7285af99ed8.png)

**Comment by checkelmann** [comment]
Yep with 2.2.4 it was working, 2.0.10 not.
