### ISSUE TITLE
Istio never loads a traffic graph

### ISSUE THREAD

**Issue by supermiguel** [rancher/rancher#21165]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Enable Istio at the cluster and workspace level,

**Result:**
When you click on Istio it just hands on a loading icon and never displays anything.

**Comment by davidnuzik** [comment]
Based on our slack conversation I think something else is going on. This is working for me. I'm not entirely sure what is happening but should not get any HTTP 503 errors when access the endpoints.

Version: v2.3.0-alpha5 single-node rancher on DigitalOcean host will open firewall

I tested but didn't identify any issues.

When enable Istio all workloads are up and good:
![image](https://user-images.githubusercontent.com/45179589/60209062-b2e7a380-980e-11e9-8136-aa80fc2d2a2b.png)
(I enabled with default settings)

Before doing anything, visit Istio page should see "Not enough data for graph"
![image](https://user-images.githubusercontent.com/45179589/60209102-c85ccd80-980e-11e9-810d-0a3552e07ae6.png)

All the UI links are accessible
![image](https://user-images.githubusercontent.com/45179589/60209132-d3aff900-980e-11e9-935a-40dd784f4a03.png)

Created auto-injection namespace
![image](https://user-images.githubusercontent.com/45179589/60209156-e88c8c80-980e-11e9-8ca9-43aea052aa58.png)

Imported the following YAML into this namespace:
https://raw.githubusercontent.com/rancher/rancher/80bdad0ebb8bcd3d2fd9d55dc45c1851443bcf30/tests/validation/tests/v3_api/resource/istio_files/bookinfo.yaml
https://raw.githubusercontent.com/rancher/rancher/80bdad0ebb8bcd3d2fd9d55dc45c1851443bcf30/tests/validation/tests/v3_api/resource/istio_files/bookinfo-gateway.yaml

Appears to be working and functional:
![image](https://user-images.githubusercontent.com/45179589/60209564-bf203080-980f-11e9-8658-55a861d2119e.png)

**Comment by deniseschannon** [comment]
@supermiguel If you are still facing issues with v2.3.0-rc5, please let us know.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by tegk** [comment]
I can reproduce this with Kubernetes Version: v1.15.4 and 0.1.1 with Istio 1.3.3
