### ISSUE TITLE
Backport: Update EKS regions (Mumbai, London, Paris) 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21160]
Backport: https://github.com/rancher/rancher/issues/18114

**Comment by davidnuzik** [comment]
Version: v2.2-head (6/27/19)

Validated new additional regions. 

HTTP looks good, API looks good, compare to AWS console looks good, all checks passed. I was not able to fully test all regions as our account does not have access to them all (cannot fully test those) but the PR looks good to me.

Regions:
![image](https://user-images.githubusercontent.com/45179589/60303221-b2bcd600-98ea-11e9-9e79-16c7e0d9210e.png)

**Comment by davidnuzik** [comment]
FYI:

ap-south-1 - mumbai
eu-west-2 - london
eu-west-3 - paris
