### ISSUE TITLE
Active Directory Permissions Not Showing in Members UI

### ISSUE THREAD

**Issue by KyleTheAutomator** [rancher/rancher#21168]
Not sure when this started occurring but within the last week I upgraded from 2.1.8 to 2.2.4.  I'm unable to see all Member assignments at the cluster and project level.  It appears that the missing member assignments are Active Directory groups.  When I attempt to re-add the missing Active Directory group as a member at the cluster or project level the UI accepts the input but never updates the member list.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.project.security.members.index`|

**Comment by davidnuzik** [comment]
See https://github.com/rancher/rancher/issues/20825 will be fixed in v2.2.5
