### ISSUE TITLE
Backport: Server panic during startup when k8s v1.14 is not available

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21177]
Backport https://github.com/rancher/rancher/issues/21129

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher:v2.2-head  5521557f

Steps:
- run Rancher:v2.2-head  container
- add a cluster with k8s v1.14 using EC2, 1 etcd, 1 control plane, 1 worker
- stop the etcd node on AWS
- `docker stop`  to stop the Rancher container
-  wait to see the UI is gone and it shows no connection
- `docker start` to start the Rancher container

Results:
- Rancher container is restarted successfully
- in Rancher's UI, the cluster is still in the unavailable state
- restart the etcd node, then the cluster goes back to active and is functional


<img width="1453" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60300965-0fb58d80-98e5-11e9-855f-2b4ee369be6b.png">
