### ISSUE TITLE
Backport: Allow S3 Snapshot service to trust internally signed certs when talking to the S3 endpoint

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21186]
Backport: https://github.com/rancher/rancher/issues/19222

Note: This is the issue for the API which is related to the backport RKE changes: https://github.com/rancher/rancher/issues/21103
and backport UI: https://github.com/rancher/rancher/issues/21104

**Comment by sowmyav27** [comment]
Verified this as part of https://github.com/rancher/rancher/issues/21103 and https://github.com/rancher/rancher/issues/21104. Closing this issue
