### ISSUE TITLE
[[network] Host [fe80::250:56ff:feb1:3e45] is not able to connect to the following ports: [fe80::250:56ff:feb1:3e45:2380, fe80::250:56ff:feb1:3e45:2379, fe80::250:56ff:feb1:6a59:2380, fe80::250:56ff:feb1:6a59:2379]. Please check network policies and firewall rules]

### ISSUE THREAD

**Issue by mihai-satmarean** [rancher/rancher#21184]
bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher 2.3
Add a vmware template
Create cluster with some nodes (3 in our case)

**Result:**
Everything seems to be running ok, but the message on the cluster is this: [[network] Host [fe80::250:56ff:feb1:3e45] is not able to connect to the following ports: [fe80::250:56ff:feb1:3e45:2380, fe80::250:56ff:feb1:3e45:2379, fe80::250:56ff:feb1:6a59:2380, fe80::250:56ff:feb1:6a59:2379]. Please check network policies and firewall rules]
The hosts individual messages are those: Waiting to register with Kubernetes

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | v2.2.3
-- | --
User Interface | v2.2.41
Helm | v2.10.0-rancher10
Machine | v0.15.0-rancher6-1

- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted):
- Machine type (VM) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by vocatan** [comment]
I'm also having issues with :2379 traffic between two nodes running CentOS7 with Docker 17.09.7 and Rancher 2.2.4

But my issue is that the error message shows IPV4 connection attempts and failures, whereas the listening socket is on IPV6

Background:
I spun up two brand new CentOS7 VirtualBox images, to do a step-by-step walkthrough install.

After copying/pasting the join command from the 2nd machine, on the 1st machine, the web UI shows "[[network] Host [192.168.1.49] is not able to connect to the following ports: [192.168.1.48:2379, 192.168.1.48:2380]. Please check network policies and firewall rules]"

Going to the 1st host, and looking at what network ports it is listening on, it is **ONLY** listening on IPV6 ports:

```
# netstat -tan |grep LIST
tcp        0      0 127.0.0.1:6440          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9099          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:40691         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp6       0      0 :::10250                :::*                    LISTEN
tcp6       0      0 :::10251                :::*                    LISTEN
tcp6       0      0 :::6443                 :::*                    LISTEN
tcp6       0      0 :::2379                 :::*                    LISTEN   <---
tcp6       0      0 :::10252                :::*                    LISTEN
tcp6       0      0 :::2380                 :::*                    LISTEN   <---
tcp6       0      0 :::80                   :::*                    LISTEN
tcp6       0      0 :::10257                :::*                    LISTEN
tcp6       0      0 :::10259                :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:25                  :::*                    LISTEN
tcp6       0      0 :::443                  :::*                    LISTEN
```

Trying to connect, (curl host1:2379) fails.

Is there a way to **ONLY** have CentOS use IPV4 sockets?  I'm going to reinstall, then update /etc/sysctl.conf to include

```
net.ipv6.conf.all.disable_ipv6=1
```
before I install Docker, and before I install Rancher.

Will report back

**Comment by vocatan** [comment]
Ah, my mistake.  As posted by somebody else at https://github.com/rancher/rancher/issues/15490 -- it's a firewall issue, and not IPV4 vs. IPV6.

instead of using 'netstat', I need to habituate myself to use 'ss' instead.  Understanding now that listening sockets will show up as if they are tcp6, but will still accept on tcp4 connections.

2nd machine was able to connect to port :2379 and successfully join now.
