### ISSUE TITLE
Cluster with certs expiration time, 30 days or less has alert with text which is not readable 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21196]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Have a cluster(DO cluster-3 nodes) in v2.2.4 - with custom image, giving 30 minutes of expiry for the cluster.
2. Upgrade to v2.2-head with UI tag 2.2.81.
3. Warning shown on the UI - `This cluster has certs expiring in 30 days or less. Please rotate your certificates now.`

The text `rotate` in the alert is not readable.

<img width="1333" alt="Screen Shot 2019-06-27 at 9 44 05 AM" src="https://user-images.githubusercontent.com/26032343/60287654-467cab00-98c7-11e9-8c0e-e1f00af36701.png">

**Note:**
It is readable on the cluster dashboard page though
<img width="1304" alt="Screen Shot 2019-06-27 at 9 43 57 AM" src="https://user-images.githubusercontent.com/26032343/60287698-5e542f00-98c7-11e9-8ab4-749e36b2542b.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2-head with UI tag `2.2.81`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): do 
- Kubernetes version (use `kubectl version`):

```
1.13
```

**Comment by westlywright** [comment]
I've fixed the light theme text color in UI tag `2.2.83`

**Comment by sowmyav27** [comment]
Verified on `rancher:v2.2-head` with UI tag `2.2.83`
The text on the UI is readable. `Rotate` is incorrect spelled. 
<img width="1548" alt="Screen Shot 2019-07-02 at 7 39 09 AM" src="https://user-images.githubusercontent.com/26032343/60525444-3425b700-9ca3-11e9-89f4-26dbc1900b47.png">
<img width="1372" alt="Screen Shot 2019-07-02 at 7 39 24 AM" src="https://user-images.githubusercontent.com/26032343/60525456-39830180-9ca3-11e9-9c28-187973d08dd2.png">

**Comment by westlywright** [comment]
@sowmyav27 typo is fixed in UI tag `2.2.84`

**Comment by sowmyav27** [comment]
verified in 2.2-head with UI tag `2.2.84`
Typo has been fixed
<img width="1387" alt="Screen Shot 2019-07-02 at 10 05 21 AM" src="https://user-images.githubusercontent.com/26032343/60532521-4ce99900-9cb2-11e9-85d5-876e5b485616.png">
<img width="1376" alt="Screen Shot 2019-07-02 at 10 05 30 AM" src="https://user-images.githubusercontent.com/26032343/60532525-4e1ac600-9cb2-11e9-9a91-48d261f483bf.png">
