### ISSUE TITLE
Error while trying to rotate certificates on a cluster with one service certificate rotated

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21193]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Have a cluster(DO cluster-3 nodes) in v2.2.4 - with custom image, giving 30 minutes of expiry for the cluster.
2. Upgrade to v2.2-head with UI tag `2.2.81`.
3. Warning shown on the UI - `This cluster has certs expiring in 30 days or less. Please rotate your certificates now.`
4. Click on rotate from the warning message
5. Select an individual service to rotate - say - etcd service
6. Click on rotate.
7. After the cluster has finished updating, click on rotate from the warning message.

**Expected Result:**
User should be able to perform Rotate Certificates action

**Actual Result:**
The UI is stuck, on the console - `Uncaught TypeError: Cannot read property 'daysUntil' of undefined` is seen.
<img width="1915" alt="Screen Shot 2019-06-27 at 10 07 26 AM" src="https://user-images.githubusercontent.com/26032343/60287119-fc46fa00-98c5-11e9-9e75-7a7ea91de790.png">

<img width="1912" alt="Screen Shot 2019-06-27 at 10 04 33 AM" src="https://user-images.githubusercontent.com/26032343/60287175-18e33200-98c6-11e9-990a-f9d0cad6ff11.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.2-head with UI tag `2.2.81`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO 
- Kubernetes version (use `kubectl version`):

```
1.13
```

**Comment by westlywright** [comment]
Fix available in UI tag `2.2.83`

**Comment by sowmyav27** [comment]
Verified in `rancher:v2.2-head` with UI tag `2.2.83`

Steps to reproduce:

1. Have a cluster(DO cluster-3 nodes) in v2.2.4 - with custom image, giving 30 minutes of expiry for the cluster.
2. Upgrade to v2.2-head with UI tag 2.2.83.
3. Warning shown on the UI - `This cluster has certs that are expiring or have expired. Roatate Now`
4. Click on rotate from the warning message
5. Select an individual service to rotate - say - etcd service
6. Click on rotate.
7. After the cluster has finished updating, click on rotate from the warning message.
8. User is able to do Rotate Certificates action. No error on the UI.
