### ISSUE TITLE
rancher-compose ps

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2119]
@fentas wrote in rancher-compose repo:

I am wondering. It's not really possible to figure out how many container are currently running with rancher-compose. 
The only 2 possible ways to figure this out (I know of) are rancher/server api or within a managed container per rancher-metadata.
Now it would be nice if 
```bash
$ rancher-compose scale web
```
would return current scale or
```bash
$ rancher-compose scale web=+1 # +/-number
```
would scale service relative to current state.

@ibuildthecloud and @fentas decided on creating a `rancher-compose ps` for his request.

**Comment by kevinsimper** [comment]
I feel this is super weird when you are just starting out with rancher that you can't list services with rancher-compose :(

**Comment by deniseschannon** [comment]
Instead of adding this into Rancher Compose, we recommend using the new [Rancher CLI](http://docs.rancher.com/rancher/cli/) which supports `rancher ps`.

**Comment by kevinsimper** [comment]
@deniseschannon That is not really helpful as it list every container with their long name, as not like docker-compose does, only shows it with their short name.

**Comment by deniseschannon** [comment]
@kevinsimper I'm not exactly sure what you mean.

```
$ docker-compose ps
      Name                Command          State        Ports      
------------------------------------------------------------------
nginx_1         nginx -g daemon off;   Up      443/tcp, 80/tcp 
```


```
# Show services in Rancher environment
$ rancher ps
ID           TYPE      NAME           IMAGE            STATE     SCALE     ENDPOINTS   DETAIL
1s722     service   Default/test   ubuntu:14.04.3   healthy   1  
# Show containers in Rancher environment
$ rancher ps -c
ID        NAME                 IMAGE                           STATE     HOST      IP             DOCKER         DETAIL
1i4       Network Agent        rancher/agent-instance:v0.8.3   running   1h1       10.42.26.69    5f82e2b70f7f   
1i5       Network Agent        rancher/agent-instance:v0.8.3   running   1h2       10.42.123.31   a39a33cc7b23   
1i6       Network Agent        rancher/agent-instance:v0.8.3   running   1h3       10.42.98.30    647b99844e2c   
1i322     test314373_test1_1   ubuntu:14.04.2                  running   1h3       10.42.133.79   aef400cae9fb   
1i1759    Default_test_1       ubuntu:14.04.3                  running   1h1       10.42.58.61    7f400f0f03c4
```
