### ISSUE TITLE
Rancher 2.2.4 LDAP groups can't be added to cluster member roles

### ISSUE THREAD

**Issue by troy256** [rancher/rancher#21192]
**Steps to reproduce:**

1) Deploy Rancher Server container rancher/rancher:v2.2.4
2) Configure OpenLDAP authentication
3) Create a cluster
4) Edit the cluster
5) Under "Member Roles" click "Add Member".  Add a LDAP group.
6) Save the cluster.
7) Edit the cluster, the LDAP group you just added is not there.

This worked on v2.1.6 and we upgraded directly to v2.2.4 we noticed that all the LDAP groups in the cluster "Member Roles" were missing and were unable to re-add them.

**Cluster information:**
This is an on-prem cluster of 5 Ubuntu 18.04 LTS VMware VMs.
Rancher v2.2.4
Kubernetes 1.13.5

**Comment by mrajashree** [comment]
Hi @troy256 this issue is fixed in 2.2.5 https://github.com/rancher/rancher/issues/20825
Closing as dup/fixed, please reopen if it persists
