### ISSUE TITLE
Enforcing private templates should not be allowed by Global Admin

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21208]
Version: Master head

Steps:

1. Login to the setup as an admin and create a standard user "user1"
2. As global admin, set the "cluster-template-enforcement" setting as true
3. Login as "user1"
4. Create a cluster template "T1" in API which is private. 
5. The template T1 gets created successfully 
6. As a global admin, turn of the enforcement flag and it succeeds. 
Enforcing private templates should not be allowed. API should error out with a relevant message

**Comment by prachidamle** [comment]
With redesigne ClusterTemplate Enforcement, we will be dropping the "Enforced" flag on the ClusterTemplate. So this issue is no longer valid.
