### ISSUE TITLE
No name resolution in pods from specific nodes

### ISSUE THREAD

**Issue by jocarren** [rancher/rancher#21205]
**What kind of request is this:**
Quiestion.

**Steps to reproduce:**
I have 2 sites with 2 bare metal (Ubuntu 16.04) hosts, connected through Openvpn. Istalled Rancher as single node in a VPS outside my 2 sites, then created a cluster using my hosts as nodes (4 nodes). 

**Result:**
Nodes get registered correctly, but I get DNS name resolution only in pods running inside nodes of ONE of the sites. It seems that the site "chosen" for name resolution is the one wihere the first node is provisioned.

What could be causing this behavior?

**Other details that may be helpful:**

I noticed this when deploying Longhorn, pod **longhorn-csi-plugin** got stuck initializing in this way: https://github.com/longhorn/longhorn/issues/500#issue-437480173
Then I deployed an alpine pod to test name resolution with the results described.

EDIT: I tested registering nodes first from "Site A": no DNS in "Site B", then killed the cluster and tried registering nodes first from "Site B": no DNS in "Site A".

**Environment information**
- Rancher version: 
rancher/rancher 
v2.2.4
- Installation option: 
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
Metal
- Kubernetes version: 

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version:

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:18:36 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:53:57 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by jocarren** [comment]
UPDATE: Moved pod kube-dns from one site to another and the problem manifests in the site kube-dns is NOT running.

**Comment by superseb** [comment]
We have troubleshooting docs for overlay network and DNS here: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/

This should help diagnosing the issue. kube-dns is scaled using autoscaler, you can modify the config to have different rules to scale kube-dns.

**Comment by jocarren** [comment]
Precisely, I figured out to scale modifying autoscale configmap, now the cluster doesn't resolve in any pod. Scaled back down, and it works as before. I'll take a look at the troubleshooting page you suggest. 
Thanks for your help, much apreciated.

**Comment by superseb** [comment]
Let me know if there is a bug here
