### ISSUE TITLE
Update azureconfig, image to newer Ubuntu 18.04

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21207]
Version: v2.2.4, master-head (6/27/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create Azure nodeTemplate, notice API still suggests old Ubuntu 16.04 as default image
- Compare to Azure console, it suggests 18.04

**Result:**
We should update to 18.04 image (we officially support this newer version and so it should also be default).

Azure web console default when add new VM:
![image](https://user-images.githubusercontent.com/45179589/60299409-7e90e780-98e1-11e9-9fda-f2c62ab3bb07.png)

**Other details that may be helpful:**
From /v3/schemas/azureconfig
```
"image": {
"create": true,
"default": "canonical:UbuntuServer:16.04.0-LTS:latest",
"description": "Azure virtual machine OS image",
"dynamicField": true,
"type": "string",
"update": true
}
```

**Comment by cbron** [comment]
Do we need to update terraform provider too ? https://github.com/terraform-providers/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_azure.go#L85

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/19/19)

I can confirm the schema has been updated and this works correctly in the UI as well.
I ensured that my node(s) had ubuntu 18.04 by connecting to the node via ssh and checking.

API schema:
`/v3/schemas/azureconfig`
![image](https://user-images.githubusercontent.com/45179589/63282189-1ae0c600-c263-11e9-9e64-60abbe0ed949.png)

UI nodeTemplate modal:
![image](https://user-images.githubusercontent.com/45179589/63282272-5085af00-c263-11e9-8056-b3c911e92812.png)

UI nodeTemplate http request (azureConfig)
`image: "canonical:UbuntuServer:18.04-LTS:latest"`

Confirm OS version of node:
![image](https://user-images.githubusercontent.com/45179589/63283947-65fcd800-c267-11e9-920e-a32b1e72ac6b.png)
