### ISSUE TITLE
Is it possible to set scrape period?

### ISSUE THREAD

**Issue by ilusharulkov** [rancher/rancher#21213]
Rancher:  v2.2.4
Question: I have setup custom metric monitoring using annatation (with enabled project level monitoring):
```
field.cattle.io/workloadMetrics: '[{"path":"/metrics","port":80,"schema":"HTTP"}]'
```
Is it the right way to do so ?
Defaul period of scrape is 1 min. Is it possible to edit this value (from service yaml configuration) ?

**Comment by orangedeng** [comment]
1. Yes. I think it is ok. 
2. You can add an extra answer in enable project monitoring page. The answer key is “prometheus.scrapeInterval”.

**Comment by orangedeng** [comment]
We don’t support adding custom scrape config in workload for now. But you can edit the service monitor object after you add the custom metrics.
There is a service monitor object with the same name as the service. You can edit the internal attribute in the endpoint you need.

**Comment by ilusharulkov** [comment]
Thanks for your reply! Rancher is awesome!!
