### ISSUE TITLE
Bug: Cloud Credentials Name with spaces shows no warning

### ISSUE THREAD

**Issue by simon-scherzinger** [rancher/rancher#21215]
**What kind of request is this (question/bug/enhancement/feature request):**
UI-Bug

**Steps to reproduce (least amount of steps as possible):**
1) Have a Rancher 2.2.4 installation
2) Go to Profile | Cloud Credentials | Add Cloud Credentials
3) Type in your credentials with a name with spaces
4) Click Create

**Result:**
*Expected:* Warning in name input is shown indicating problem with spaces
*Actual:* Nothing happens after click on Create

**Other details that may be helpful:**
Without spaces in the name everything seem to work as expected.

May be related to rancher/rancher#20577 and rancher/rancher#19755

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): HA
- Browser: Chrome 75.0.3770.100

**Comment by deniseschannon** [comment]
In general, it seems that there is no error message when the API for creating a cloud credential is invalid:

https://github.com/rancher/rancher/issues/20577
https://github.com/rancher/rancher/issues/19677
https://github.com/rancher/rancher/issues/19759
https://github.com/rancher/rancher/issues/21215

**Comment by davidnuzik** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/21888 which is our main issue to track problems with UI not showing errors when create Cloud Credentials with invalid names and/or with required fields not filled out.

Your issue mentioned here is in the second issue mentioned in #21888 which talks about spaces in the name of the Cloud Credential.
