### ISSUE TITLE
Rancher stuck  on [pre-deploy] Pulling image [rancher/hyperkube:v1.13.5-rancher1] on host [10.0.0.7]

### ISSUE THREAD

**Issue by drj1990** [rancher/rancher#21217]
**What kind of request is this (question/bug/enhancement/feature request):**

bug
**Steps to reproduce (least amount of steps as possible):**
Create VM on azure 
Install rancher on it 
run rancher 
login to rancher 
click on Add cluster 
Select custom 
In cloud provider select none 
Select etcd,control plane 
Copy the commond and paste on the VM.
progress messages will be shown but progress stucks on  [pre-deploy] Pulling image [rancher/hyperkube:v1.13.5-rancher1] on host [10.0.0.7]

**Result:**
```
stucks on below &rancher stopped  working after some time
 [pre-deploy] Pulling image [rancher/hyperkube:v1.13.5-rancher1] on host [10.0.0.7]
```
`80dd905125c2        rancher/rke-tools:v0.1.28      "/bin/bash"              31 seconds ago       Exited (0) 18 seconds ago                                              cluster-state-deployer`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.4
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):
```
(paste the output here)
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by superseb** [comment]
Are you adding the same VM to a cluster that is running Rancher? What is the machine type you are using? Can you manually pull that image on the host if this occurs?

**Comment by drj1990** [comment]
This seems to be issue with the rancher version. I was using v2.2 on azure it was not working on azure but v2.2 worked on google cloud.
When i used version 2.1.6 on azure cloud it worked.

Please try v2.2 on azure cloud. I have mentioned all platform details.

**Comment by lakmal-ya** [comment]
i also getting same error did you find what is the cause of these

**Comment by laball** [comment]
I got the same error,  stuck on "[pre-deploy] Pulling image [rancher/hyperkube:v1.14.6-rancher1] on host [10.0.2.15]".

Anybody know how to fix it ?

**Comment by superseb** [comment]
What are the specifications of the machine(s) being used? Provisioning uses Docker API to pull images which seems to hang. What is the state of the node when this happens? Can you manually issue `docker` commands on the node?

**Comment by asimsalam** [comment]
I see the same behavior with rancher-agent:v2.2.4 on joining vSphere based ubuntu bionic VM nodes:
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.2.4 --server https://ssgranch00.autocache.com --token 6fht2ctd77xbplb5mst28xnpdslcc7rlkfmcsx5zwv8wrpxm6jqjcm --ca-checksum bcf3687f2eedf992d02f70317f6c12a47aa93082b657ed722a186b1c63532ddd --worker
Unable to find image 'rancher/rancher-agent:v2.2.4' locally
v2.2.4: Pulling from rancher/rancher-agent
6abc03819f3e: Downloading [===============================================>   ]  27.18MB/28.86MB
05731e63f211: Download complete 
0bd67c50d6be: Download complete 
e7e8247bd935: Download complete 
1a35389393bc: Downloading [=============================================>     ]  29.99MB/32.63MB
7891f5237e19: Download complete 
480c5d8e76a1: Download complete 
a985e4338da5: Downloading [=============================================>     ]  22.73MB/25.24MB
786480892ac4: Waiting 
^C

Pulling directly through docker also hangs
--------------------------------------------------------
sudo docker pull rancher/rancher-agent:v2.2.4
v2.2.4: Pulling from rancher/rancher-agent
6abc03819f3e: Pull complete 
05731e63f211: Pull complete 
0bd67c50d6be: Pull complete 
e7e8247bd935: Pull complete 
1a35389393bc: Pull complete 
7891f5237e19: Pull complete 
480c5d8e76a1: Pull complete 
a985e4338da5: Pull complete 
786480892ac4: Downloading [==========================================>        ]  12.98MB/15.24MB

Pulling another rimage is snappy
------------------------------------------
sudo docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
89d9c30c1d48: Pull complete 
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest

**Comment by superseb** [comment]
Rancher/RKE talks to the node and uses the Docker socket to talk to Docker and pull images and run containers. If `docker pull` on the node also hangs/is extremely slow, we can't make that better (except for added retry logic but if its too slow it will still break)

Let me know if there is still a bug here that we need to investigate/fix.

**Comment by asimsalam** [comment]
Thanks for looking at this.

What's strange and unique here is the fact that only the pull on the rancher images hangs. If you try a pull on another image the next instance on the same node, as I showed above with the ceph/daemon example, it always succeeds.
What could be different?:
   - How we make the request to dockerd?
   - How the rancher images are published?
   - What else?
