### ISSUE TITLE
UI: workload detail: sorting pods by node name

### ISSUE THREAD

**Issue by patrikbeno** [rancher/rancher#21218]
Rancher 2.2.4

Workload detail: Sorting PODs by NODE changes the order of pods, but sorts neither by node name nor by node IP.

It looks like the sorting is done by POD NAME instead of NODE NAME.

**Comment by tfiduccia** [comment]
@patrikbeno 
I check the workloads page and grouped by Node.  The first level is Node Name and the order is actually determined by the Name: field.  So if Name is descending, the Node and Pods will sort a-z by the actual Name.  We do not take IP into account.  I checked and this is currently working correctly.   If you are seeing something different can you please add a screenshot with the IPs blanked out.

**Comment by patrikbeno** [comment]
sorted by pod name:
![image](https://user-images.githubusercontent.com/2464234/64628630-07ec8c00-d3f2-11e9-87a2-f6499727cb75.png)

sorted by node name:
![image](https://user-images.githubusercontent.com/2464234/64628701-28b4e180-d3f2-11e9-93e2-16113a223813.png)

sorting by node name does not honor hostname; instead, it uses pod name.

I.e. both PODNAME and NODENAME columns use PODNAME to sort

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 4beb5cf3e`

Create a workload with multiple pods.
When sorted by Pod Name:
![Screen Shot 2019-11-14 at 9 15 55 AM](https://user-images.githubusercontent.com/57409052/68875210-aaa9db00-06bf-11ea-9565-07f03685af77.png)

When sorted by Node Name:
![Screen Shot 2019-11-14 at 9 16 05 AM](https://user-images.githubusercontent.com/57409052/68875229-b5647000-06bf-11ea-959d-e8ba605460ec.png)
