### ISSUE TITLE
Fix rancher-images generation to include the original image tag

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21221]
Today on every Drone tag we generate rancher-images.txt file containing all the third party system images needed to launch Rancher microservices (code can be found here). Prior to generation, the images have to be tagged and pushed to Rancher repo - that is so they are all kept at the same location, and to make things easier to mirror for airgapped installs. This re-tag/pushToRancherDockerhub step is manual today. And it's better to offload it to Drone. For that, we have to generate the file containing an image source and destination in a following format:

rancherTag originalTag... (amd, arm, etc)

Example:
rancher/coreos-etcd:v1 cores/etcd:v1 cores/etcd:v1-arm64

**Comment by alena1108** [comment]
Today on every Drone tag we generate rancher-images.txt file containing all the third party system images needed to launch Rancher microservices (code can be found here). Prior to generation, the images have to be tagged and pushed to Rancher repo - that is so they are all kept at the same location, and to make things easier to mirror for airgapped installs. This re-tag/pushToRancherDockerhub step is manual today. And it's better to offload it to Drone. For that, we have to generate the file containing an image source and destination in a following format:

rancherTag originalTag... (amd, arm, etc)

Example:
rancher/coreos-etcd:v1 cores/etcd:v1 cores/etcd:v1-arm64

**Comment by alena1108** [comment]
@kinarashah that would require some code changes in https://github.com/rancher/rancher/blob/master/pkg/image/export/main.go based on the changes you are making for separating k8s images from rke/types.

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/20765

**Comment by sangeethah** [comment]
@jiaqiluo For validating this issue , following scenarios need to be validated in air gap setup.

1. Validate that we are able to deploy all supported K8s versions in the release successfully after the images from `rancher-images.txt` gets uploaded to the private registry used by airgap setup.

**Comment by sangeethah** [comment]
@kinarashah When we introduce new k8s version support in existing rancher server setup, we would expect `rke-metadata-url` to be point to a github server that is accessible to the air gap setup and is kept in sync with rancher's default `rke-metadata-url` .
With this in place , k8s version support changes will be reflected in air gapped setups as expected. But we will still not have a way to get an updated `rancher-images.txt` with the supporting system images needed.
We should have a V3 settings exposed that will carry this information and get re-evaluated  everytime changes done to kontainer metatdata.

**Comment by alena1108** [comment]
@kinarashah we should implement generateImages action that would produce a downloadable file, similar to how download keys work.

**Comment by kinarashah** [comment]
@sangeethah @jiaqiluo Opened a new issue to track this, since the original issue is to make changes to include original image tag. For metadata related changes, refer https://github.com/rancher/rancher/pull/22302 

cc: @alena1108

**Comment by alena1108** [comment]
Based on discussion with Bill and Taylor, the format of the image file will be the following:

```
rancher/coreos-etcd:v1 amd;coreos/etcd:v1 arm;coreos/etcd:v1-arm arm64;coreos/etcd:v1-arm64 windows-1903;coreos/etcd:v1-windows-1903
```

The tagging and pushing should be done in the repos where the images are originally defined: types, kontainer-driver-metadata, system-charts. Each repo will have the file with all the images referenced in the repo being checked in. On merge, drone should ensure that all images are present along with their manifest, and if not, tag/push the image with the manifest generation.

Rancher side changes would be to generate rancher-images.txt file based on the metadata in types, kontainer-driver-metadata, system-charts

**Comment by deniseschannon** [comment]
This already exists today for non multi-arch images with the istio mirror script. 

But we still need to solve multi-arch images.

**Comment by deniseschannon** [comment]
Support has been added and separated out to a separate repo: https://github.com/rancher/image-mirror
