### ISSUE TITLE
Multi-Cluster Apps show incorrect version after cancelling upgrade

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#21228]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Multi-Cluster app "Atlantis" using version 3.6.0
2. Observe "Upgrade available (3.6.1)" is displayed for the app
3. Click on yellow upgrade button
4. Click on "Cancel"
5. Observe "Up to date (3.6.1)" is displayed for the app

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): HA

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9cdd04bd5`

Deploy Multi-Cluster app `Atlantis` using `version 3.6.0`
`Upgrade available (3.8.4)` is displayed for the app
Click on yellow upgrade button
Click on `Cancel`
`Upgrade available (3.8.4)` is still displayed for the app
![Screen Shot 2019-11-15 at 11 02 40 AM](https://user-images.githubusercontent.com/57409052/68964789-7570bc00-0797-11ea-8595-ee2d15e3d0e0.png)
