### ISSUE TITLE
 Why can't my alertmanager trigger webhook？

### ISSUE THREAD

**Issue by arrowfeng** [rancher/rancher#21237]
I met a problem about alertmanager trigger dingding's webhook.
**What kind of request is this (question/bug/enhancement/feature request):**
question
**Steps to reproduce (least amount of steps as possible):**
i test my address , it's right
but i can't receive any message when condition is meet.
and email is ok.
now, I do not know what to do.

**Result:**
![image](https://user-images.githubusercontent.com/20623365/60383267-4df7ac00-9aa1-11e9-8701-a41715f34d37.png)

**Other details that may be helpful:**
this is an alertmanager pod's log
![image](https://user-images.githubusercontent.com/20623365/60383310-c1012280-9aa1-11e9-8424-51e558a68f89.png)
![image](https://user-images.githubusercontent.com/20623365/60383377-42f14b80-9aa2-11e9-88a9-c1a9bcd0f8c6.png)
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.4
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):
1.12.4

- Docker version (use `docker version`):
18.6.1

**Comment by aiwantaozi** [comment]
# Troubleshooting steps for alerting

If not receive any alert, could follow below troubleshooting steps:
## 1. Check whether notifies could receive message  
go to `Tools` -> `Notifiers` -> `Add Notifier` -> `Test`, check whether you could receive the notify first.

##	2. Check cluster-alerting app deploy status
go to `System Project` -> `Apps` -> check apps `monitoring-operator` and `cluster-alerting` is actived, all the workloads belong to those apps deployed successfully. If those apps not deploy success, check warning on apps first, then go to Workload for more details.

##  3. Check monitoring-operator and cluster-alerting workload logs
go to `System Project` -> `cattle-prometheus` namespace -> check logs for workload `alertmanager-cluster-alerting` and `	prometheus-operator-monitoring-operator`, whether those workload have any error logs.

## 4. Check connection between rancher server and cattle-cluster-agent.
go to `System Project` -> `cattle-system` namespace, view logs for `cattle-cluster-agent`, whether there are any errors.
curl alert service inside `cattle-cluster-agent` container
```
curl access-alertmanager.cattle-prometheus.svc.cluster.local/api/v1/alerts
{"status":"success","data":[]}
```

##  4. Check alert rule
Expression alert rule is different from others types, it's triggered by prometheus, which means monitoring need to be enabled, when the condition match the expression, prometheus will call alertmanager's api to trigger alert. While other alert rules are triggered by rancher server, rancher server will watch those alert rules, call alertmanager's api when match the configured condition. 
   

##  5. Check whether alertmanager receive alert
Go to `System Project` -> `Apps` -> `cluster-alerting` App, click the `/index.html` to view alermanager's UI, could see alerts event is alertmanager receives any events. If alertmanager could receive events but you don't receive any notifies, which means alertmanager has something wrong with send out event. Enable debug log for alertmanager. If alertmanager couldn't receive event, check the alert rule you configured, or enable rancher server's debug log. 


##  6. Enable debug log for alertmanager
Go to cluster page, copy the `Kubeconfig File` to kubeconfig, then run `kubectl get crd`, will got return like this
```
NAME                                          CREATED AT
alertmanagers.monitoring.coreos.com           2019-07-09T08:02:52Z
bgpconfigurations.crd.projectcalico.org       2019-07-09T08:01:20Z
```

then run `kubectl edit alertmanagers.monitoring.coreos.com -n cattle-prometheus --kubeconfig kubeconfig`, edit `logLevel: info` to `logLevel: debug`

then go to the alertmanager to `View logs`, it will help to check whether alertmanager receive the alert, and whether it could send out.
may get some logs like this
```
level=debug ts=2019-07-09T15:03:37.511451301Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=[433a194][active]
level=debug ts=2019-07-09T15:03:38.511774835Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{group_id=\"c-5h85q:event-alert\"}/{rule_id=\"c-5h85q:event-alert_deployment-event-alert\"}:{event_message=\"Scaled up replica set mynginx2-7994cd84ff to 1\", resource_kind=\"Deployment\", rule_id=\"c-5h85q:event-alert_deployment-event-alert\", target_name=\"mynginx2\", target_namespace=\"default\"}" msg=flushing alerts=[[433a194][active]]
```

## 7. Enable rancher server's debug log
Go inside rancher server container and run `loglevel --set debug`

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by wangqiongkaka** [comment]
I have a same issue。
Do you have a solution to this problem。
