### ISSUE TITLE
[Forwardport] Azure character limits on resource groups

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#21234]
Forwardport issue of https://github.com/rancher/rancher/issues/21061

**Comment by daxmc99** [comment]
PR here https://github.com/rancher/rancher/pull/21199

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.4

- Create AKS cluster with resource group greater than 63 chars but less than 90 chars (Azure does not allow > 90 chars for any RG name). You must have metrics enabled (but these are by default).
- Eventually get this error and cannot provision AKS cluster:
`Operationalinsights.WorkspacesClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=workspaceName constraint=MaxLength value="david-q2uyo9EKxqo6CpxRnoHvq155gcRCaYYEmJCsUCGqXnVABrKWY8X2s5qPouUpOkRA-14a619f7-a887-4635-8647-d8f46f92eaac-EUS" details: value length must be less than or equal to 63`

**Validation (FAILED):**
master-head (7/1/19)
ver according to logs: `b4340af9`

- Follow same steps as outlined in reproduction steps above (use same RG name, which is 70 chars)
- Cluster has a different error:
`Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="The length of the node resource group name is too long. The maximum length is 80 and the length of the value provided is 88. Please see https://aka.ms/aks-naming-rules for more details." Target="name"`

How did my RG length increase? shouldn't this decrease it?

**Comment by davidnuzik** [comment]
Here's what UI supplied:
`david-q2uyo9EKxqo6CpxRnoHvq155gcRCaYYEmJCsUCGqXnVABrKWY8X2s5qPouUpOkRA`
Here's what we got:
`david-q2uyo9EKxqo6CpxRnoHvq155gcRCaYYEmJCsUCGqXnVABrKWY8X2s5qPouUpOkRA-14a619f7-a887-4635-8647-d8f46f92eaac-EUS`

**Comment by davidnuzik** [comment]
**Reproduction:**
Please refer to https://github.com/rancher/rancher/issues/21234#issuecomment-507412994 (my last comment) where this was already reproduced in v2.2.4.

**Validation:**
v2.2-head

- Create AKS cluster with RG string greater than 63 chars, 64 chars in my case. You must have metrics enabled (but this is by default)
`david-rtnMHCqGl3L08ME8rk13ISYfc2wD57nORtegG7fks4pX43f3u7FBdmufh0`
- We now successfully create the Log Analytics resource in Azure console, we did not before.
![Screen Shot 2019-07-01 at 3 33 59 PM](https://user-images.githubusercontent.com/45179589/60470567-c2ebf280-9c15-11e9-8ed1-453575f8bef6.png)

- Note: We do get another separate error but this is a new, and separate issue. Azure seems to be appending our RG string with extra characters, this is not something Rancher is doing. Refer to https://github.com/rancher/rancher/issues/21264 for this separate Azure issue.
