### ISSUE TITLE
[AKS] Azure field client-side validation 

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#21231]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Add a bad ssh key to Azure, like random data. 
Azure will attempt to provision, taking a few minutes but then fail
Azure will fail with a validation error that the SSH key is bad

**Improvement**
We now do SSH key validation client-side which should catch invalidatlely formatted ssh keys or private keys before sending them to Azure for validation. 

**Other details that may be helpful:**
This will allow for quicker feedback to user when creating AKS clusters.

**Comment by daxmc99** [comment]
Available in master

**Comment by soumyalj** [comment]
Observed the issue in v2.3.3
1. Created an azure AKS cluster by providing random data as ssh keys.
2. Cluster creation fails with the below error message which is really long and not user friendly

<img width="1570" alt="Screen Shot 2020-01-22 at 2 31 27 PM" src="https://user-images.githubusercontent.com/18536626/72940565-ea2a1e80-3d23-11ea-9348-b93a253155fb.png">

Tested with master-build (b3bc13a88). 
1. Created an azure AKS cluster by providing random data as ssh keys.
2. Cluster creation fails with the better error message w.r.t ssh keys . The feed back also is slightly faster than the older version(~45s)

<img width="1419" alt="Screen Shot 2020-01-22 at 2 32 21 PM" src="https://user-images.githubusercontent.com/18536626/72940618-06c65680-3d24-11ea-9d63-3734599843cd.png">
