### ISSUE TITLE
Better error messaging for invalid API keys

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2123]
@miketheman wrote in the rancher-compose repository:

A [valid docker-compose file](https://github.com/miketheman/dorkbot/blob/master/docker-compose.yml#L9-L10) errors out on rancher-compose over the [`environment` variable setting](https://docs.docker.com/compose/yml/#environment).

```shellsession
$ ./rancher-compose -v
rancher-compose version v0.3.0
$ ./rancher-compose --verbose -f ~/git/miketheman/dorkbot/docker-compose.yml create
DEBU[0000] Opening compose file: /Users/miketheman/git/miketheman/dorkbot/docker-compose.yml
DEBU[0000] Reading file /Users/miketheman/git/miketheman/dorkbot/.env relative to /Users/miketheman/git/miketheman/dorkbot/docker-compose.yml
DEBU[0000] Opening rancher-compose file: /Users/miketheman/git/miketheman/dorkbot/rancher-compose.yml
DEBU[0000] Not found: /Users/miketheman/git/miketheman/dorkbot/rancher-compose.yml
DEBU[0000] Looking for stack dorkbot
INFO[0000] Creating stack dorkbot
ERRO[0000] Failed to open project dorkbot: Resource type [environment] is not creatable
2015/09/20 14:58:55 Failed to read project: Resource type [environment] is not creatable
```

@ibuildthecloud This happens when you API keys are not valid. We need to add an error message or check that validates the keys to make this more user friendly.

**Comment by deniseschannon** [comment]
@miketheman The `ERRO[0000] Failed to open project dorkbot: Resource type [environment] is not creatable` indicates that the `project` (our old API term for what is now `environment` in the UI, upper right hand corner) is not able to be accessed. 

Some notes. The API/Rancher-Compose have some terms changed around as we narrowed down to what we wanted to call our stuff in the UI.

**Comment by sangeethah** [comment]
Tested with rancher-compose-v0.4.1-rc2

When passing invalid values for RANCHER_ACCESS_KEY and RANCHER_SECRET_KEY , we are presented with the following error message:

```
ERRO[0000] Failed to open project test: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized] from [http://104.154.35.114:8080] 
FATA[0000] Failed to read project: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized] from [http://104.154.35.114:8080] 
```
