### ISSUE TITLE
Rancher 2 HA not accessible with LetsEncrypt

### ISSUE THREAD

**Issue by wyattjsmith1** [rancher/rancher#21244]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create DigitalOcean Kubernetes cluster (also tried creating RKE cluster with DO Droplets: https://rancher.com/docs/rancher/v2.x/en/installation/ha/kubernetes-rke/)
2. Install Helm/Tiller as instructed here: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-init/
3. Install Cert-Manager as instructed here: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#optional-install-cert-manager
4. Install Rancher with the following command (From `stable` chart):
```
helm install rancher-stable/rancher \
  --name rancher \
  --namespace cattle-system \
  --set hostname=rancher.rizzo.one \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=admin@rizzo.one \
  --set letsEncrypt.environment=staging \
  --set replicas=1
```
I understand I am using 1 replica, which defeats the purpose of HA, but I am just trying to get this to work, then scale it as needed.

**Result:**
All pods are running, but I still get connection refused. Here are my `Service`s.  There are a few things I find peculiar about the system. 
1. First, I'd assume that `cm-acme-http-solver-w2smd` would be exposed on port `80`, not `30734` (which changes every time I test).
2. I'd assume `rancher` would be a `NodePort`, not a `ClusterIP`. It is my understanding that `ClusterIP` is not exposed publicly: `Choosing this value makes the service only reachable from within the cluster.`
```
➜  ~ kubectl get service --all-namespaces
NAMESPACE       NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
cattle-system   cm-acme-http-solver-w2smd   NodePort    10.245.37.74     <none>        8089:30734/TCP           7m1s
cattle-system   rancher                     ClusterIP   10.245.25.151    <none>        80/TCP                   7m39s
default         kubernetes                  ClusterIP   10.245.0.1       <none>        443/TCP                  27m
kube-system     kube-dns                    ClusterIP   10.245.0.10      <none>        53/UDP,53/TCP,9153/TCP   27m
kube-system     tiller-deploy               ClusterIP   10.245.206.100   <none>        44134/TCP                11m
```
Even if these are expected, I am unable to access the home page: `https://rancher.rizzo.one`. I get the standard `Unable to connect`. I even get this when curling from the node running rancher.
For what it's worth:
- I have my DNS pointing at my cluster
- I don't have a Load Balancer yet.
- I have a firewall that currently has all TCP/UDP/ICMP open. Not secure; just for testing.
- I am able to issue commands with `kubectl` and `ping` it.

Thank you for any help you may provide.

**Other details that may be helpful:**
Here is an output of some of the Kubernetes objects. Let me know if more logs would be helpful:
```
➜  ~ helm status rancher
LAST DEPLOYED: Sun Jun 30 20:00:52 2019
NAMESPACE: cattle-system
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRoleBinding
NAME     AGE
rancher  5m10s

==> v1/Deployment
NAME     READY  UP-TO-DATE  AVAILABLE  AGE
rancher  1/1    1           1          5m10s

==> v1/Pod(related)
NAME                     READY  STATUS   RESTARTS  AGE
rancher-d95d845c9-t6nm2  1/1    Running  0         5m10s

==> v1/Service
NAME     TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)  AGE
rancher  ClusterIP  10.245.25.151  <none>       80/TCP   5m10s

==> v1/ServiceAccount
NAME     SECRETS  AGE
rancher  1        5m10s

==> v1alpha1/Issuer
NAME     AGE
rancher  5m10s

==> v1beta1/Ingress
NAME     HOSTS              ADDRESS  PORTS  AGE
rancher  rancher.rizzo.one  80, 443  5m10s


NOTES:
Rancher Server has been installed.

NOTE: Rancher may take several minutes to fully initialize. Please standby while Certificates are being issued and Ingress comes up.

Check out our docs at https://rancher.com/docs/rancher/v2.x/en/

Browse to https://rancher.rizzo.one

Happy Containering!

➜  ~ kubectl describe pod rancher-d95d845c9-t6nm2 -n cattle-system
Name:           rancher-d95d845c9-t6nm2
Namespace:      cattle-system
Priority:       0
Node:           pool-sh5vdwjeo-olkw/10.138.146.192
Start Time:     Sun, 30 Jun 2019 20:00:52 -0700
Labels:         app=rancher
                pod-template-hash=d95d845c9
                release=rancher
Annotations:    <none>
Status:         Running
IP:             10.244.0.18
Controlled By:  ReplicaSet/rancher-d95d845c9
Containers:
  rancher:
    Container ID:  docker://7c624dd0edc9a889d1ecd5dd0ea13d2ceaa1dd78e987762d86d26de7c0a299e1
    Image:         rancher/rancher:v2.2.4
    Image ID:      docker-pullable://rancher/rancher@sha256:b22d5e239b8750edb639d0fe181c528fccacea67fb23412dff3c5f66e57e44a2
    Port:          80/TCP
    Host Port:     0/TCP
    Args:
      --no-cacerts
      --http-listen-port=80
      --https-listen-port=443
      --add-local=auto
    State:          Running
      Started:      Sun, 30 Jun 2019 20:01:07 -0700
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:80/healthz delay=60s timeout=1s period=30s #success=1 #failure=3
    Readiness:      http-get http://:80/healthz delay=5s timeout=1s period=30s #success=1 #failure=3
    Environment:
      CATTLE_NAMESPACE:     cattle-system
      CATTLE_PEER_SERVICE:  rancher
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from rancher-token-spvpb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  rancher-token-spvpb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rancher-token-spvpb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age    From                          Message
  ----     ------     ----   ----                          -------
  Normal   Scheduled  5m28s  default-scheduler             Successfully assigned cattle-system/rancher-d95d845c9-t6nm2 to pool-sh5vdwjeo-olkw
  Normal   Pulling    5m25s  kubelet, pool-sh5vdwjeo-olkw  Pulling image "rancher/rancher:v2.2.4"
  Normal   Pulled     5m13s  kubelet, pool-sh5vdwjeo-olkw  Successfully pulled image "rancher/rancher:v2.2.4"
  Normal   Created    5m13s  kubelet, pool-sh5vdwjeo-olkw  Created container rancher
  Normal   Started    5m13s  kubelet, pool-sh5vdwjeo-olkw  Started container rancher
  Warning  Unhealthy  5m6s   kubelet, pool-sh5vdwjeo-olkw  Readiness probe failed: Get http://10.244.0.18:80/healthz: dial tcp 10.244.0.18:80: connect: connection refused
➜  ~ kubectl describe issuer rancher -n cattle-system
Name:         rancher
Namespace:    cattle-system
Labels:       app=rancher
              chart=rancher-2.2.4
              heritage=Tiller
              release=rancher
Annotations:  <none>
API Version:  certmanager.k8s.io/v1alpha1
Kind:         Issuer
Metadata:
  Creation Timestamp:  2019-07-01T03:00:52Z
  Generation:          2
  Resource Version:    1992
  Self Link:           /apis/certmanager.k8s.io/v1alpha1/namespaces/cattle-system/issuers/rancher
  UID:                 70214617-9bac-11e9-b931-2a967a476a8c
Spec:
  Acme:
    Email:  admin@rizzo.one
    http01:
    Private Key Secret Ref:
      Key:
      Name:  letsencrypt-staging
    Server:  https://acme-staging-v02.api.letsencrypt.org/directory
Status:
  Acme:
    Uri:  https://acme-staging-v02.api.letsencrypt.org/acme/acct/9803392
  Conditions:
    Last Transition Time:  2019-07-01T03:00:59Z
    Message:               The ACME account was registered with the ACME server
    Reason:                ACMEAccountRegistered
    Status:                True
    Type:                  Ready
Events:                    <none>
➜  ~ kubectl describe certificate tls-rancher-ingress -n cattle-system
Name:         tls-rancher-ingress
Namespace:    cattle-system
Labels:       <none>
Annotations:  <none>
API Version:  certmanager.k8s.io/v1alpha1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2019-07-01T03:00:57Z
  Generation:          7
  Owner References:
    API Version:           extensions/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Ingress
    Name:                  rancher
    UID:                   701dc4c6-9bac-11e9-b931-2a967a476a8c
  Resource Version:        4011
  Self Link:               /apis/certmanager.k8s.io/v1alpha1/namespaces/cattle-system/certificates/tls-rancher-ingress
  UID:                     731bd3fb-9bac-11e9-b931-2a967a476a8c
Spec:
  Acme:
    Config:
      Domains:
        rancher.rizzo.one
      http01:
        Ingress:
  Dns Names:
    rancher.rizzo.one
  Issuer Ref:
    Kind:       Issuer
    Name:       rancher
  Secret Name:  tls-rancher-ingress
Status:
  Acme:
    Order:
      Challenges:
        Authz URL:  https://acme-staging-v02.api.letsencrypt.org/acme/authz/muSc5xD8W3Wt6Zjro5jj5jO0D_sVtfFE-Y_veDBBK3s
        Domain:     rancher.rizzo.one
        http01:
          Ingress:
        Key:        UthLJZtcdZQBJyq5A1AsDGYBnl40lZ4U8n-PtzVcWwo.414kyRiQ6JoKDC5625bJRd_N0Rm2tDDRKCCa_g5sJQg
        Token:      UthLJZtcdZQBJyq5A1AsDGYBnl40lZ4U8n-PtzVcWwo
        Type:       http-01
        URL:        https://acme-staging-v02.api.letsencrypt.org/acme/challenge/muSc5xD8W3Wt6Zjro5jj5jO0D_sVtfFE-Y_veDBBK3s/326729051
        Wildcard:   false
      URL:          https://acme-staging-v02.api.letsencrypt.org/acme/order/9803392/38748512
  Conditions:
    Last Transition Time:  2019-07-01T03:07:22Z
    Message:               http-01 self check failed for domain "rancher.rizzo.one"
    Reason:                ValidateError
    Status:                False
    Type:                  Ready
Events:
  Type    Reason       Age    From          Message
  ----    ------       ----   ----          -------
  Normal  CreateOrder  7m12s  cert-manager  Created new ACME order, attempting validation...
➜  ~ kubectl get service --all-namespaces
NAMESPACE       NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
cattle-system   cm-acme-http-solver-w2smd   NodePort    10.245.37.74     <none>        8089:30734/TCP           7m20s
cattle-system   rancher                     ClusterIP   10.245.25.151    <none>        80/TCP                   7m58s
default         kubernetes                  ClusterIP   10.245.0.1       <none>        443/TCP                  27m
kube-system     kube-dns                    ClusterIP   10.245.0.10      <none>        53/UDP,53/TCP,9153/TCP   27m
kube-system     tiller-deploy               ClusterIP   10.245.206.100   <none>        44134/TCP                11m
```

**Environment information**
- Rancher version: `rancher/rancher` Helm chart
- Installation option: HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Tested on both DO Kubernetes, and Droplets and RKE using https://rancher.com/docs/rancher/v2.x/en/installation/ha/kubernetes-rke/
- Machine type (cloud/VM/metal) and specifications (CPU/memory): DO, 1vCPU, 2GB memory, 50GB Disk
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): NA

**Comment by vincent99** [comment]
The ingress controller is what's listening on 80 (and 443), not the solver.  The log says that validate failed, which usually means the name is pointing at the wrong IP or port 80 isn't open.  (It's been a while, but there's nothing responding on the name even though it resolves to a DO IP).

**Comment by wyattjsmith1** [comment]
@vincent99 Hmmm.... ok. I tore down the kubernetes cluster last night, so the test you ran was probably not going to work. My fault, I should have left it up. I have it up again and here is what I see:

1. I can ping the machine`ping rancher.rizzo.one`
2. `curl`ing from my laptop results in a connection refused:
```
➜  ~ curl rancher.rizzo.one
curl: (7) Failed to connect to rancher.rizzo.one port 80: Connection refused
```
3. `curl`ing both `rancher.rizzo.one` and `localhost:80` from a node in the cluster results in the same response as above. I would think this test would eliminate any potential issues involving DO routing.

I am keeping the cluster up, so you should be able to connect to it now.

**Comment by vincent99** [comment]
If you can't connect to the ingress (I can't either) then Let'sEncrypt can't connect to it either to perform the challenge.  RKE installs the ingress controller so this should be working (at least returning the default bcakend/404) before you even install Rancher at all.

So your problem this has nothing to do with Rancher installation, but with RKE/firewall/dns/etc.  Port 80 and 443 on that name are being actively refused, while any other port random port is being dropped.

**Comment by wyattjsmith1** [comment]
Hmm... ok. I understand Let'sEncrypt can't verify my domain because port 80 is blocked, but I am still confused as to why that is, and why port 30697 is open. I can `curl` this port and get a key back as Let'sEncrypt would, which I find very weird: 
```
➜  ~ curl rancher.rizzo.one:30697/.well-known/acme-challenge/ZDB71it96BxSEE9LyCwL-MlCzm6UVOmT2dCmMuZT7eA
ZDB71it96BxSEE9LyCwL...hidden...TMPAZyMxvQz95T3OAqU
```

I am also skeptical that Kubernetes is forwarding port 80 to the node as expected. If I run `python3 -m http.server 80` (Basically set up a dummy server) on my node, I can visit it at `rancher.rizzo.one`. I am not an expert in Kubernetes by any means, but it looks like this is an issue with the way kubernetes is set up, as I am able to connect to port 80 on my droplet. I will leave that running for a while if you want to verify it or test something.

One thing I want to reiterate: I am using DO's kubernetes engine, not RKE. I would not expect this to matter, and I originally tested on RKE with the same result.

**Comment by vincent99** [comment]
Again it doesn't matter what the solver is doing when there's nothing listening on 80/443 for the cluster to begin with.  Nothing is going to work until an ingress controller is listening on 80 and 443.  So it sounds like DO doesn't include an ingress controller by default, and you would therefore need to provide one.  

I haven't looked into exactly what CertManager does but it probably creates a NodePort service and also is selected by an Ingress rule that routes `http://rancher.rizzo.one:80/.well-known` to it, so the NodePort it's listening on for debugging or whatever is irrelevant.

We only really support running HA Rancher on top of a cluster created with RKE.  It should work (with the right configuration), but what you can do as far as backup and restore of etcd is limited or non-existent depending on the Kubernetes-as-a-Service provider.

RKE _does_ deploy nginx-ingress by default though, so I don't know what the problem was when you were trying that.

**Comment by wyattjsmith1** [comment]
Ok, that was it. I think I figured it out. DO's kubernetes did not deploy an Ingress as you pointed out. I have installed RKE with two independent droplets, and everything is working as expected now.

I realize this didn't work the first time I tried RKE because I had my dns pointing to the etcd/controlpanel node. This time, I pointed it at the worker node, and everything worked as expected.

Thank you so much @vincent99! You have taught me a lot about Kubernetes and helped me figure this out.

**Comment by expelledboy** [comment]
@wyattjsmith1 I want to setup a bootstrap project to deploy a single node HA rancher which can be scaled later using RKE and cert-manager via a single command, preferably `make` after a `vim .env` 🙂 It must be secure enough to be exposed to the internet, unlike the deployment you are left with after following the guides. If you have some time I would love to collaborate, perhaps we can assist each other on this journey.

But otherwise, what I noticed when following the same documentation, was that RKE installs kube, kubectl installs helm. Then you install cert-manager so you can expose rancher via HTTPS, and as I dip my toes into rancher I notice that it has a helm catalogue, from which you can install cert-manager... Do you think its possible, or is it even a worthwhile exercise getting the cert-manager installed in rancher to issue and re-new the certs used for rancher? Not to mention helm requires its own certificates to be truly secure when exposed to the internet..

**Comment by wyattjsmith1** [comment]
@expelledboy First, I want to point out that I am not by any means an expert with rancher/Kubernetes as can be seen by some of my comments above. 
That said, I don't see why rancher would not be secure enough to expose to the internet after the tutorial; it has TLS and you can set the admin password. Is there something else you expected?
In regards to using rancher to install cert manager again to renew certificates, I don't think that's necessary because the cert manager used to install Rancher should renew them automatically.
If you have any more issues, I think it would be best to open new issues instead of commenting on this resolved ticket.
