### ISSUE TITLE
enable cluster ,cattle-prometheus not deploy

### ISSUE THREAD

**Issue by damozhiying** [rancher/rancher#21249]
@loganhz 
``
 kubectl get deploy -n  cattle-prometheus
``
No resources found.
``
``
the cattle-system namespace everything is ok,

how  to manual deploy cattle-prometheus pod

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
