### ISSUE TITLE
Pod logs folder was not generated

### ISSUE THREAD

**Issue by wongkimshing** [rancher/rancher#21240]
**What kind of request is this (question/bug/enhancement/feature request):**
Pod logs folder was not generated after first pod deployed. As being mentioned in the documentation, /var/log/containers folder should be available for gathering all pod logs, but it didn’t happen anyway. So it caused no log data could be sent to Elasticsearch after configuring logging for cluster even though connection testing is successful.

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher Server
2. Create custom type of Cluster
3. Install Rancher Agent in the other server
4. Deploy an application on the Cluster just created
5. Navigate Tools -> Logging and select Elasticsearch and configure properly with successful connection testing
6. Only see the connection testing log in Kibana and no application logs are received 

**Result:**
/var/log/containers was not generated after 1st pod deployed. Logging function was not available.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): single install
- OS: CentOS 7.6

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Aliyun Cloud, 8 CPU/32G RAM
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
17.03 ce
```
(paste the output here)
```

**Comment by aiwantaozi** [comment]
Hi, @wongkimshing  ```/var/log/containers``` was generated by kubelet, could you check
1. whether this pod was scheduled to that node
2. whether docker logs $container_id return logs
3. check kubelet logs if there are any errors

**Comment by wongkimshing** [comment]
Yes, I can see the folder now, but it still has not log data sending to Elasticsearch

**Comment by wongkimshing** [comment]
Upgrading the system project -> apps rancher-logging and add answer fluentd.cluster.dockerRoot = you docker root dir can fix the issue manually.

**Comment by wongkimshing** [comment]
@aiwantaozi I followed your instructions and resolved the log problem, but the other problem occurred. Path /var/lib/rancher/fluentd/buffer grows up very soon and it occupies most of the disk spaces. Could you please advise how can I change the parameters to config the buffer path of Fluentd and limit it to certain size? Thanks a lot.

**Comment by aiwantaozi** [comment]
Hi @wongkimshing we don't support configure buffer now, the max size is 64G, after log delivered, the buffers would be deleted. Maybe too many logs or the target throughput isn't enough. If you need us to support configure the buffer, could file a feature request issue.

**Comment by wongkimshing** [comment]
@aiwantaozi It seems that the buffer will not be deleted even though the log has been delivered to Elasticsearch. That's why the buffer folder grows up very soon. So is it possible a bug?

**Comment by aiwantaozi** [comment]
After all the logs in this buffer chunk deliver success, it would delete, if not deliver success, the buffer would keep there, fluentd would handle the buffer deletion. Could you check is the total number and size of your log buffer, whether it's possible there are too many logs, the throughput isn't enough, the logs generated much faster than deliver.

**Comment by wongkimshing** [comment]
@aiwantaozi Can I config fluentd buffer path to other disk instead of system disk?
