### ISSUE TITLE
Clusters showing as custom instead of vsphere after rancher upgrade

### ISSUE THREAD

**Issue by dan-evolvere** [rancher/rancher#21251]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Created Vsphere clusters, upgraded rancher from 2.2.3 to 2.2.4

**Result:**
Some clusters show as Custom, instead of Vsphere after upgrade

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Vsphere, rancher created
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): various 1.14.1, 1.13.4
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- Docker version (use `docker version`):
17.3.2

**Comment by sangeethah** [comment]
@dan-evolvere  After upgrading to 2.2.4 , are you viewing this cluster as user who did not create this cluster ?

**Comment by dan-evolvere** [comment]
yes, the cluster was created with a different user.

**Comment by sangeethah** [comment]
This issue is tracked in https://github.com/rancher/rancher/issues/12038#issuecomment-502291089.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/12038
