### ISSUE TITLE
changes for CIS controller 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#21257]
1) I see we're using access functions for cluster scan, but I don't see roles added in `role_data.go`
2) When we fetch projects from management, it'll get all System projects? we would also need to pass cluster namespace?
https://github.com/rancher/rancher/pull/20981/files#diff-31ef4a6390c28ff5e259d44753d9f570R70

**Comment by leodotcloud** [comment]
Updates to the roles in this PR: https://github.com/rancher/rancher/pull/23641

**Comment by kinarashah** [comment]
comments addressed
