### ISSUE TITLE
cannot enable project level monitoring - 2.2.3

### ISSUE THREAD

**Issue by mshack70** [rancher/rancher#21252]
We have two 2.2.3 clusters (previously were 2.2.2).  I've tried enabling project level monitoring , but each time get errors.
![project_monitoring_enable_fail](https://user-images.githubusercontent.com/25782618/60447905-206a4a00-9bea-11e9-83e9-ebcb0c197e68.jpeg)

**Comment by mshack70** [comment]
we have cluster level monitoring enabled, and it seems fine btw.

**Comment by alena1108** [comment]
Project monitoring was temporarily disabled in 2.2.2 and 2.2.3. It is back in 2.2.4:

https://github.com/rancher/rancher/releases/v2.2.4

Closing the issue

**Comment by mshack70** [comment]
thanks. works great!
