### ISSUE TITLE
Cluster restore from S3 failed and recovered after around 90mins

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21263]
Tested with build v2.2.5-rc7
K8s version : v1.14.3

Steps:
Create a custom cluster using S3 configuration with nodes as below:
N1 - control, worker
N2, N3, N4 - 3 etcds
Create a few workloads
Power off etcd nodes N2, N3, N4

After powering off the etcd nodes, the cluster changed to "Unavailable" state as expected.

Cluster was accessible through UI. The etcd nodes were deleted and new etcd nodes were added.  Restore was performed from S3. Restore succeeded the first time and the second time, restore failed. Cluster was stuck in Updating state and recovered after around 90mins
Logs below:

```
2019/07/01 18:25:40 [ERROR] ClusterController c-ltv2b [cluster-provisioner-controller] failed with : [workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck for service [kubelet]: Failed to get gather logs from container [kubelet]: error during connect: Get http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/containers/kubelet/logs?stderr=1&stdout=1&tail=1: failed to find Session for client c-ltv2b:m-faf4e5ab53e6]
2019/07/01 18:25:42 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"c-ltv2b:m-32929735cff7","addresses":["abcd"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-kgf5m","allNodes":false},{"nodeName":"c-ltv2b:m-32929735cff7","addresses":["efgh"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-kgf5m","allNodes":false},{"nodeName":"c-ltv2b:m-faf4e5ab53e6","addresses":["hijk"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-6x8vn","allNodes":false},{"nodeName":"c-ltv2b:m-faf4e5ab53e6","addresses":["lmnp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-6x8vn","allNodes":false}]]

```

```
failure to delete a non-existing pod `2019/07/01 18:22:30 [ERROR] ClusterController c-ltv2b [cluster-provisioner-controller] failed with : [pods "nginx-ingress-controller-2tgtq" not found]`
```

**Comment by moelsayed** [comment]
It looks like the Control node for the cluster was having issues, two errors were found in the logs:
I found two errors in the logs:
- connection timeouts
- failure to delete a non-existing pod 2019/07/01 18:22:30 [ERROR] ClusterController c-ltv2b [cluster-provisioner-controller] failed with : [pods "nginx-ingress-controller-2tgtq" not found]

Kubeapi would take longer than usual to update the list of pods that should be removed. Which causes the second error when rke tries to delete it. We shouldn't error out on NotFound errors.

**Comment by soumyalj** [comment]
Tested with build master-head
K8s version : v1.14.3

Steps:
Create a custom cluster using S3 configuration with nodes as below:
N1 - control, worker
N2, N3, N4 - 3 etcds
Create a few workloads
Power off etcd nodes N2, N3, N4

After powering off the etcd nodes, the cluster changed to "Unavailable" state as expected.
Cluster was accessible through UI. etcd nodes were deleted and new etcd nodes were added and cluster was restored from S3.

Related issue is filed here:
#21319
