### ISSUE TITLE
[UI] Editing a stack causes JavaScript error in UI

### ISSUE THREAD

**Issue by skenmy** [rancher/rancher#2126]
Clicking "Edit" on a stack causes the following JavaScript error in line 23 of `component.js`:

`Uncaught TypeError: this.didInitAttrs is not a function`

Rancher	v0.38.1
Cattle	v0.94.0
User Interface	v0.50.0
Rancher Compose	beta/latest

**Comment by deniseschannon** [comment]
Reproduced in v0.38.1: I am unable to edit a stack.

**Comment by deniseschannon** [comment]
Verified with v0.39.0-rc1
