### ISSUE TITLE
Backport: Cluster restore from S3 failed and recovered after around 90mins

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21268]
Backport https://github.com/rancher/rancher/issues/21263

**Comment by soumyalj** [comment]
Tested with July 1st build from branch v2.2-head.

K8s version : v1.14.3

Steps:
Create a custom cluster using S3 configuration with nodes as below:
N1 - control, worker
N2, N3, N4 - 3 etcds
Create a few workloads
Power off etcd nodes N2, N3, N4

After powering off the etcd nodes, the cluster changed to "Unavailable" state as expected.

Cluster was accessible through UI. The etcd nodes were deleted and new etcd nodes were added. Restore was performed from S3. Restore was successful. Cluster was active.  Snapshot restore was performed several times and it was successful. 
Error logs  below were not found after the fix as expected. 

```
failure to delete a non-existing pod `2019/07/01 18:22:30 [ERROR] ClusterController c-abcd [cluster-provisioner-controller] failed with : [pods "nginx-ingress-controller-2tgtq" not found]`

```

Snapshot restore on local cluster was also tested. No issues were found
