### ISSUE TITLE
Cant provision new cluster, error message rpc error all SubConns are in TransientFailure

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#21274]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. not sure how the rancher server pod got in this state, but it seemed to have issues executing rke. 

**Result:**
```2019/07/02 03:03:14 [INFO] Updating cluster [c-cluster]
2019/07/02 03:03:14 [ERROR] ClusterController c-cluster [cluster-provisioner-controller] failed with : rpc error: code = Unavailable desc = all SubConns are in TransientFailure```

**Comment by alena1108** [comment]
@aemneina can we get Rancher version where this issue was observed? Wonder if it might be related to https://github.com/grpc/grpc-go/issues/2636 and caused by the older grpc version that we used prior to 1a64367368737271557abdac38b7582f689f78f6

**Comment by aemneina** [comment]
v2.1.8
