### ISSUE TITLE
Azure RG name validation issues when use southafricanorth region

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21271]
Version: master-head (7/1/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an AKS cluster, pick the South Africa North region

**Result:**
You will get an error only for this region like:
`Operationalinsights.WorkspacesClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=workspaceName constraint=Pattern value="david-akss-" details: value doesn't match pattern ^[A-Za-z0-9][A-Za-z0-9-]+[A-Za-z0-9]$`

**Other details that may be helpful:**
We are NOT supplying the extra dash on the end. I confirmed in the UI (http) and the API. Azure or the machine driver or something else appears to be doing this.

**Comment by davidnuzik** [comment]
May be related to https://github.com/rancher/ui/pull/3098 but this does seem to be a valid region. I see it in the Azure web UI.

**Comment by davidnuzik** [comment]
Something still isn't quite right. Is this an AKS issue or us? @daxmc99 what do you think?

I am still getting
`Operationalinsights.WorkspacesClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=workspaceName constraint=Pattern value="david-aks-rg-" details: value doesn't match pattern ^[A-Za-z0-9][A-Za-z0-9-]+[A-Za-z0-9]$`

and for Azure RKE cluster:
`Error creating machine: Error in driver during machine creation: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="SkuNotAvailable" Message="The requested size for resource '/subscriptions/14a619f7-a887-4635-8647-d8f46f92eaac/resourceGroups/david-rg/providers/Microsoft.Compute/virtualMachines/david-southafricanorth1' is currently not available in location 'southafricanorth' zones '' for subscription '14a619f7-a887-4635-8647-d8f46f92eaac'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details."`

**Comment by daxmc99** [comment]
Sorry @davidnuzik, this should not have been moved to test. The commit had not been added to rancher/rancher yet. PR is here for `rancher/rancher` https://github.com/rancher/rancher/pull/21381

**Comment by cjellick** [comment]
@dramich @daxmc99 can you guys get this to test without me

**Comment by davidnuzik** [comment]
Version: Master-head (7/16/19)

This appears to work correctly now. I now get this expected message (since we do not have ability with our subscription to create VMs here).

`Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The VM size of AgentPoolProfile:rancher is not allowed in your subscription in location 'southafricanorth'. "`
