### ISSUE TITLE
[Health Check] Provide API support for showing the health state reported by each of the hosts that are assigned to monitor instance's health. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2128]
Currently when instances have health check enabled , there is no way to find out the state reported by each of the hosts that are assigned to monitor instance's health.

It will be helpful to have this information presented in UI.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Able to get a list of hosts that monitor LB instance using container API - 
http://<ipaddress>:8080/v1/projects/1a5/containers/<containerid>/healthcheckinstancehostmaps

**Comment by swaroopkundeti** [comment]
Some thing weird with my setup. I had all my instance to allow all traffic(TCP, UDP) from my private subnet. 
Instance:1
<pre>
root@ip-10-0-4-74:~# ps aux | grep docker
root       914  0.7  0.6 1512512 51424 ?       Ssl  Jan08 126:43 /usr/bin/docker daemon
root     15828  0.0  0.0  17972  1524 ?        S    Jan19   0:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -docker_root /var/lib/docker
root     15852  0.0  0.1 226456 15496 ?        Sl   09:12   0:00 docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 4500 -container-ip 172.17.0.2 -container-port 4500
root     15868  0.0  0.1 226456 13452 ?        Sl   09:12   0:00 docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 500 -container-ip 172.17.0.2 -container-port 500
root     15878  1.0  0.4 418232 39352 ?        Sl   Jan19   5:56 /var/log/rancher/.cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -docker_root /var/lib/docker
root     17475  0.0  0.0  10464   932 pts/6    S+   09:13   0:00 grep --color=auto docker
root     22020  0.0  0.8 370528 72720 ?        Ssl  Jan11   2:13 /opt/flocker/bin/python /usr/sbin/flocker-docker-plugin --logfile=/var/log/flocker/flocker-docker-plugin.log
root     29242  0.0  0.1 226456 14640 ?        Sl   05:24   0:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.4 -container-port 80
root@ip-10-0-4-74:~# telnet localhost 4500
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
root@ip-10-0-4-74:~# netstat -atlupn | grep 4500
udp6       0      0 :::4500                 :::*                                15852/docker-proxy
root@ip-10-0-4-74:~# netstat -atlupn | grep 500
udp6       0      0 :::4500                 :::*                                15852/docker-proxy
udp6       0      0 :::500                  :::*                                15868/docker-proxy
</pre>

Instance: 2
<pre>
root@ip-10-0-4-44:~# ps aux | grep docker
root       898  0.8  0.6 1538036 52412 ?       Ssl  Jan08 141:38 /usr/bin/docker daemon
root     12288  0.0  0.2 226456 16400 ?        Sl   09:08   0:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.3 -container-port 80
root     14040  0.0  0.1 226456 14308 ?        Sl   09:12   0:00 docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 4500 -container-ip 172.17.0.2 -container-port 4500
root     14056  0.0  0.2 226456 16384 ?        Sl   09:12   0:00 docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 500 -container-ip 172.17.0.2 -container-port 500
root     20154  0.0  0.0  10464   932 pts/6    S+   09:23   0:00 grep --color=auto docker
root     22903  0.0  0.8 370660 73024 ?        Ssl  Jan11   2:57 /opt/flocker/bin/python /usr/sbin/flocker-docker-plugin --logfile=/var/log/flocker/flocker-docker-plugin.log
root     25291  0.0  0.0  17972  1524 ?        S    05:27   0:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -docker_root /var/lib/docker
root     25309  1.2  0.4 435716 39156 ?        Sl   05:27   3:02 /var/log/rancher/.cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -docker_root /var/lib/docker
root@ip-10-0-4-44:~# telnet localhost 4500
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
root@ip-10-0-4-44:~# telnet localhost 500
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
</pre>

**Comment by deniseschannon** [comment]
@swaroopkundeti I am not too sure why you have commented on this issue. Would you be able to open a new issue and provide more details?
