### ISSUE TITLE
Color of Rotate now to be changed to make it look like an Actionable text on the UI screen

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21283]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**on `rancher:v2.2-head` with UI tag `2.2.83`**
Have a cluster(DO cluster-3 nodes) in v2.2.4 - with custom image, giving 30 minutes of expiry for the cluster.
Upgrade to v2.2-head with UI tag 2.2.83.
Warning shown on the UI - `This cluster has certs that are expiring or have expired. Roatate Now`
<img width="1548" alt="Screen Shot 2019-07-02 at 7 39 09 AM" src="https://user-images.githubusercontent.com/26032343/60525444-3425b700-9ca3-11e9-89f4-26dbc1900b47.png">

Color of Rotate now to be changed to make it look like an Actionable text on that screen

**Comment by alena1108** [comment]
Can be tested with v2.2.5-rc10

**Comment by sowmyav27** [comment]
verified with `v2.2.5-rc11`
<img width="637" alt="Screen Shot 2019-07-09 at 11 55 39 AM" src="https://user-images.githubusercontent.com/26032343/60915744-7ae65480-a241-11e9-8b3f-cf12bbcb07fe.png">

`Rotate Now` is visible now and is seen as an Actionable item

`ui-index` is `https://releases.rancher.com/ui/2.2.86/index.html`
