### ISSUE TITLE
[release v2.0] Upgrade embedded kubectl to 1.12.9

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21291]
We should upgrade embedded kubectl to 1.12.9

**Comment by sowmyav27** [comment]
verified on `v2.0.16-rc1`. 
Client Version is `v1.12.9` - DO, AWS, Azure, Custom RKE cluster, AKS, GKE

**Comment by sowmyav27** [comment]
Amazon EKS - the kubectl is stuck in `Connecting..` state.
cattle-cluster-agent and cattle-node-agent components have not deployed correctly. Stuck in `Unavailable` state.

**Comment by sowmyav27** [comment]
created an EKS cluster in us-east-1 region. Cluster is deployed successfully. Client Version is `v1.12.9`
