### ISSUE TITLE
When nodes deleted from cluster (using kubectl delete node) are stopped and started , they get registered back as worker nodes that are non schedulable to the cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21299]
Rancher Server version - Latest build from master - `5144aa85`

Steps to reproduce the problem:
Create a custom cluster(no cloud provider) with following node configuration with nodes from AWS:
2 control nodes - c1,c2
3 worker nodes - w1, w2,w3
3 etcd nodes - e1, e2, e3

From AWS console , stop one of the worker nodes say w1.
This node gets to "Unavailable" state in rancher server UI as expected and it is in "Not Ready" state when monitoring node list from kubectl command.

Delete the node from cluster using kubectl command.
This results in node getting removed from cluster in  rancher server side as expected.

Start this worker node from AWS console .
The worker node gets registered to the cluster again as "worker" node in rancher server UI.
Node list from  kubectl command indicate that there is NO role assigned to this node.

Also containers dont get deployed on this worker node , since they are non schedulable.

<img width="1080" alt="Screen Shot 2019-07-02 at 8 08 56 PM" src="https://user-images.githubusercontent.com/4266958/60561717-7255c180-9d09-11e9-8d6d-17d77fd745ee.png">

Same behavior is seen when a control node / etcd node gets deleted from the custom cluster using `kubectl delete node` command and then it was stopped and started from the AWS console. In all the cases , the nodes get registered back as worker node that is not schedulable.

**Comment by cjellick** [comment]
@sangeethah what do you expect to happen in this case?

**Comment by sangeethah** [comment]
@cjellick , Ideally as part of removing a node from the cluster , we should be able to delete all the K8s related components on this node . This way , when the nodes get restarted , there will not be an attempt made to join the cluster back.

**Comment by cjellick** [comment]
Hm. @alena1108 what do you think? Is there anything we can do here?

**Comment by alena1108** [comment]
@cjellick I think the best we can do in this case is to instruct the user to cleanup the data on the node before bringing it back. So it gets registered as a new one.

**Comment by deniseschannon** [comment]
@sangeethah when we're deleting the node through kubectl delete, there is no way for us to clean up the node from these components. 


I don't think there is much we can do in this use case. If you choose to manage your k8s nodes outside using kubectl versus Rancher, we will hit use cases like this.

**Comment by sangeethah** [comment]
Related issue - https://github.com/rancher/rancher/issues/17893
