### ISSUE TITLE
Implement refresh action for k8s metadata

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21296]

**Comment by jiaqiluo** [comment]
The feature is tested by using testing Rancher images and forked `kontainer-driver-metadata` Github repo.

Steps:
- run Rancher-testing:v2.3.3
- in Rancher, check the k8s list: v1.12.4-rancher1-1 (default), v1.13.1-rancher1-1(experimental)
- in kontainer-driver-metadata, add a new k8s minor version v1.12.10-rancher1-1
- in kontainer-driver-metadata, add a new k8s major version v1.16.0-rancher1-1
- generate new metadata and push to Github
- in Rancher, refresh `v3/kontainerdrivers`

Result:
- the k8s list reflects the changes, meaning it shows newly-added v1.12.10-rancher1-1 as default and v1.16.0-rancher1-1 as experimental
- also checked the v3/settings and see proper values in the follow filed
```
- ui-k8s-supported-versions-range 
- ui-k8s-default-version-range 
- k8s-version-to-images
- k8s-versions-current
- k8s-version
- k8s-version-to-service-options
```
