### ISSUE TITLE
vagrant up on the latest code des not result in an working environment

### ISSUE THREAD

**Issue by mihai-satmarean** [rancher/rancher#2129]
the content of the version file is:
0.5.0-SNAPSHOT-e584b1579123fb430d97196a1ab5542f2059adef-288e48d6-7355-453d-9d31-22fa88238f4a

windows 7 Professional  32 bit
vagrant 1.7.2
virtual box 4.3.12
 
error that is shown is the following continuously

==> rancher-server: ERROR: http://172.19.8.100:8080 is not accessible

**Comment by deniseschannon** [comment]
Did you make any changes to the default Vagrantfile located [here](https://github.com/rancher/rancher/blob/master/Vagrantfile)? If so, can you provide your Vagrantfile?

**Comment by mihai-satmarean** [comment]
Thanks for looking into it,
actually I lowered the RAM to 512 but it did not worked befor either.
Simple git clone an vagrant up.

2015-09-28 19:46 GMT+02:00 Denise <notifications@github.com>:

**Comment by deniseschannon** [comment]
I saw the same issue, but you just need to wait a little bit and eventually it will become accessible. It takes a bit for rancher server to be ready after you launch the container.

**Comment by deniseschannon** [comment]
Note: I'm using VirtualBox 5.0.4, Vagrant 1.7.4

**Comment by mihai-satmarean** [comment]
Thanks! I will try.
Please add it as an info somewhere, nobody expects to wait these days.


2015-09-29 20:57 GMT+02:00 Denise <notifications@github.com>:

**Comment by Nalum** [comment]
@deniseschannon Typically how long does it take for rancher to be accessible over port 8080?

I've done the `git clone`/`vagrant up`, no changes to the files, and I've been waiting for 15 minutes for it so far.

**Comment by Nalum** [comment]
Vagrant output:

```
==> rancher-server: ERROR: Could not reach http://172.19.8.100:8080. Giving up.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by deniseschannon** [comment]
It usually only takes 1-2 min before the UI is accessible.

**Comment by Nalum** [comment]
@deniseschannon Thanks, I was able to get to it on `localhost:8080`. I was trying to access it on `http://172.19.8.100:8080` as that is what the vagrant output is looking at.

**Comment by enricomingardo** [comment]
I've the same problem. After little investigation i've found this:


```
VAGRANT_LOG=info vagrant up
...
INFO guest: Execute capability: configure_networks [#<Vagrant::Machine: rancher-server (VagrantPlugins::ProviderVirtualBox::Provider)>, [{:type=>:static, :adapter_ip=>"172.19.8.1", :ip=>"172.19.8.100", :netmask=>"255.255.255.0", :auto_config=>true, :interface=>1}]] (linux)
INFO ssh: Execute: ip link show|grep eth[1-9]|awk '{print $2}'|sed -e 's/:$//' (sudo=true)
INFO ssh: Execute: ros config set network.interfaces.eth1.address 172.19.8.100/24 (sudo=true)
INFO ssh: Execute: ros config set network.interfaces.eth1.match eth1 (sudo=true)
INFO ssh: Execute: ros config set network.interfaces.eth1.dhcp false (sudo=true)
INFO ssh: Execute: system-docker restart network (sudo=true)
...
```

but inside the vm:

```
vagrant ssh rancher-server

[rancher@rancher-server ~]$ sudo ros config export --full
....
network:
    dns:
      nameservers: [8.8.8.8, 8.8.4.4]
    interfaces:
      eth*:
        dhcp: true
      lo:
        address: 127.0.0.1/8
...
```

it seems that vagrant cannot set the ip address of eth1( ```172.19.8.100``` by default)

**Comment by zlatkoc** [comment]
@deniseschannon same problem here:
==> rancher-server: ERROR: http://172.19.8.100:8080 is not accessible

MacOS 10.11.1, VirtualBox 5.0.8, vagrant 1.7.4
* git clone / vagrant up
* same output as @enricomingardo

**Comment by floriankessler** [comment]
same here. I can workaround this issue by using the namespace as documented here:
http://docs.rancher.com/os/configuration/networking/

i.e. prefixing the ros commands with 'ranger.'

    sudo ros config set rancher.network.interfaces.eth1.address 172.19.8.100/24
    sudo ros config set rancher.network.interfaces.eth1.match eth1
    sudo ros config set rancher.network.interfaces.eth1.dhcp false
    sudo ros config get rancher.network

    sudo system-docker restart network

within the plugin:

    $ git diff
    diff --git a/vagrant_ros_guest_plugin.rb b/vagrant_ros_guest_plugin.rb
    index 567842d..5068755 100644
    --- a/vagrant_ros_guest_plugin.rb
    +++ b/vagrant_ros_guest_plugin.rb
    @@ -40,12 +40,12 @@ module VagrantPlugins
     
                                 if network[:type] == :static
                                     cidr = IPAddr.new(network[:netmask]).to_cidr
    -                                comm.sudo("ros config set network.interfaces.#{iface}.address #{network[:ip]}/#{cidr}")
    -                                comm.sudo("ros config set network.interfaces.#{iface}.match #{iface}")
    +                                comm.sudo("ros config set rancher.network.interfaces.#{iface}.address #{network[:ip]}/#{cidr}")
    +                                comm.sudo("ros config set rancher.network.interfaces.#{iface}.match #{iface}")
     
                                     dhcp = "false"
                                 end
    -                            comm.sudo("ros config set network.interfaces.#{iface}.dhcp #{dhcp}")
    +                            comm.sudo("ros config set rancher.network.interfaces.#{iface}.dhcp #{dhcp}")
                             end
     
                             comm.sudo("system-docker restart network")

**Comment by deniseschannon** [comment]
@enricomingardo @zlatkoc @floriankessler We have just updated the vagrant file to use the latest versions of RancherOS and updated the commands for the new RancherOS requirements. Please update and try to see if it fixes your issues.

**Comment by enricomingardo** [comment]
@deniseschannon now it works!

**Comment by floriankessler** [comment]
@deniseschannon works. Thank you.
