### ISSUE TITLE
Support exist condition for metric alert

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#21302]
Now we only support compare condition and the threshold for metric alert
First: user can't input expression with condition and threshold by themselves.
Second: it can't support an expression combine with multiple parts, for example:
`predict_linear(node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"}[6h], 4*60*60) <0`
`and`
`node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} < 0.2
and
node_filesystem_readonly_bytes{app="node-exporter",fstype=~"ext.|xfs"} == 0
`

![image](https://user-images.githubusercontent.com/5936271/60562886-09635d80-9d8c-11e9-92bc-cf4b7a75c637.png)

**Comment by loganhz** [comment]
cc @patrick0057

**Comment by gitlawr** [comment]
Do we need a UI change/ticket for this?

**Comment by aiwantaozi** [comment]
https://github.com/rancher/rancher/issues/21790 UI issue

**Comment by jiaqiluo** [comment]
the feature enhancement is validated in Rancher: master-head 7277535d

**Test 1**: expression with conditions and thresholds  and multiple parts + set the condition to `Not Null`

**Expresssion**: `sum (kube_deployment_labels  {deployment = "test"} or kube_deployment_labels  {deployment = "test31"}) >= 2`

**Result**: see the alerts triggered and sent to Slack

![Screen Shot 2019-08-15 at 1 26 12 PM](https://user-images.githubusercontent.com/6218999/63125430-7dd01580-bf62-11e9-81f7-adc85b2f0d42.png)

**Test 2**:  expression **without** conditions and thresholds + set the condition to any except `Not Null`

<img width="1410" alt="Screen Shot 2019-08-15 at 1 48 42 PM" src="https://user-images.githubusercontent.com/6218999/63125826-73fae200-bf63-11e9-82d9-4482379d8d16.png">

**Result**: see the alerts triggered and sent to Slack

![Screen Shot 2019-08-15 at 1 50 12 PM](https://user-images.githubusercontent.com/6218999/63125913-9db40900-bf63-11e9-8f11-a6b5b09f8c16.png)
