### ISSUE TITLE
[v2.3] Global DNS: not able to setup alidns

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#21305]
**What kind of request is this (question/bug/enhancement/feature request):** BUG

**Steps to reproduce (least amount of steps as possible):**
- Global > Tools > Global DNS Providers > Add DNS Provider
- select alidns
- Enter the Name, access key, secret key
- click save

**Result:**
Error Message:
"Api Email" is required
"Api Key" is required

**Other details that may be helpful:**
There is no API Email text box on the setup page, not shure where to enter those information

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.2.4
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):18.9.7

```
(paste the output here)
```

**Comment by MSandro** [comment]
Anyone knows whats going wrong?

**Comment by rootwuj** [comment]
Tested with rancher master-head from July 23
This version can add alidns in Global DNS and add it successfully.
