### ISSUE TITLE
input enter key in field "Docker Image" leading to the action of deleting field "port mapping"

### ISSUE THREAD

**Issue by zhongguanqun** [rancher/rancher#21304]
*Describe your issue here*

input enter key in field "Docker Image" leading to the action of deleting field "port mapping"
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`containers.run`|

**Comment by MSandro** [comment]
same issie in:
Rancher | v2.2.4
User Interface | v2.2.70

**Comment by loganhz** [comment]
Fixed in 2.3 https://github.com/rancher/rancher/issues/19109
