### ISSUE TITLE
Add external cloud provider option in cluster cloud provider

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21301]
Before we figure out how to fully solve: https://github.com/rancher/rancher/issues/20131, 

we should minimally add in a `external` cloud provider option for RKE clusters, that would allow users to select it and it populates the cluster yaml with the external option set. It would be similar to the "custom" option and show that users would need to edit the yaml, but would pre-populate to indicate to k8s that an external cloud provider was being used.

**Comment by kinarashah** [comment]
Backend is functioning as expected, needs UI support to show 
- One more option `external` under Cloud Provider. 
- Show instructions similar to `custom` option to user for editing yaml and specifying required addon for cloud controller manager. 
- Selecting `external` should send following to backend in cluster object: 
```
cloud_provider:
  name: external
```

**Comment by alena1108** [comment]
@westlywright

**Comment by deniseschannon** [comment]
@loganhz

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

Validated as per what Kinara stated above:

Backend is functioning as expected, needs UI support to show 
- One more option `external` under Cloud Provider. 
> This radio button has been added in the UI.
- Show instructions similar to `custom` option to user for editing yaml and specifying required addon for cloud controller manager. 
> The instructions state to edit the YAML and speicfy the required addon for the cloud controller manager.
Picture:
![image](https://user-images.githubusercontent.com/45179589/62561683-89219380-b834-11e9-9403-343e17601c55.png)

- Selecting `external` should send following to backend in cluster object: 
```
cloud_provider:
  name: external
```
> UI shows this in YAML:
![image](https://user-images.githubusercontent.com/45179589/62561885-ed445780-b834-11e9-9823-bd87f2a73b09.png)

> UI sends request with cloudProvider name "external"
![image](https://user-images.githubusercontent.com/45179589/62561937-0947f900-b835-11e9-8186-6b911c495b36.png)
