### ISSUE TITLE
Export cluster produces an invalid and incomplete yaml

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#21309]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a cluster on Azure using rancher UI.
- Run `rancher login` with appropriate token
 - Export cluster by running: `rancher clusters export CLUSTER`

**Result:**

Procuded yaml is incomplete. There is nothing useful here to be used to create a clone as stated here: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cloning-clusters/

```
Version: v3
clusters:
  product-dev-qa:
    dockerRootDir: /var/lib/docker
    enableNetworkPolicy: false
    localClusterAuthEndpoint: {}
```

**Environment information**
- Rancher version: 2.2.0
- Installation option (single install/HA): single install
- Rancher CLI version: 2.2.0
- cluster provider: Azure

We tested CLI on ubuntu and macOS.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Azure AKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud VM, 3 nodes, 2 cores/4GB each.
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by blackholegalaxy** [comment]
@deniseschannon do you have any though on that?

**Comment by deniseschannon** [comment]
@blackholegalaxy I'm wondering if something changed, it looks like the RKEConfig section isn't being exported. 

I'll see if I can have someone take a look.

**Comment by dramich** [comment]
This is due to putting configs like AKS into the GenericEngineConfig. Where the translation is done from a v3.Cluster to a client cluster [here](https://github.com/rancher/rancher/blob/master/pkg/api/customization/cluster/actions_yaml.go#L92) we don't have anything mapping back from GenericEngineConfig to the named config location.

**Comment by dramich** [comment]
https://github.com/rancher/docs/issues/1659

**Comment by dramich** [comment]
CLI will be in v2.3.0-rc4

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ca39b717
rancher/cli:v2.3.0-rc4

* Deploy Rancher
* Create each of the following clusters:
  * RKE nodedriver
  * Custom
  * GKE
  * AKS
  * EKS
* Check `exportYaml` action for each of the above via API browser
  * Disabled for all of the hosted providers (GKE/AKS/EKS)
* Login via Rancher CLI and attempt to export each of the above:
  * Not allowed for any of the hosted providers (GKE/AKS/EKS)
  * `FATA[0000] action [exportYaml] not available on [&{c-z27c6 cluster map....`
