### ISSUE TITLE
K8s metadata - change metadata url in settings

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#21310]
Currently the URL to data.json includes branch name and that gets cached, so it doesn't immediately reflect the changes after pushing to repository. 

Workaround:
Editing the URL to different branch, or changing the metadata-refresh-interval-minutes, would reload everything. This way new data will be loaded

**Comment by jiaqiluo** [comment]
The bug fix is validated with the rancher testing image v2.3.2

Saw the versions in the list is updated to the expected ones after either 
- editing the URL to a different branch
or 
- changing the `v3/settings/metadata-refresh-interval-minutes`
