### ISSUE TITLE
Ability to use IAM for etcd snapshot backups to s3

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21314]
To configure s3 as a backup target in Rancher UI/API, you have to provide s3 credentials. We should be able to leverage IAM as an alternative to that. The backend already supports it, just need to make sure that Rancher-RKE flow works.

**Comment by deniseschannon** [comment]
Can we make sure that we document it for RKE standalone CLI as well as Rancher docs after it's been tested?

**Comment by moelsayed** [comment]
Using IAM profiles for s3 backup auth is implemented and working in rke CLI and in Rancher.

**Comment by alena1108** [comment]
@sangeethah to test, follow the steps defined in the docs and see if you can setup s3 backup using IAM creds.

**Comment by soumyalj** [comment]
Tested with build from master-head. 
1. Created rancher server with node having IAM profile
2. Create cluster in EC2 with nodes having IAM profile by providing S3 bucket name and without other credentials.

![Screen Shot 2019-07-15 at 4 15 10 PM](https://user-images.githubusercontent.com/18536626/61255434-657b9980-a71d-11e9-82a3-2e6a7ed86daf.png)

**Comment by moelsayed** [comment]
During testing this my browser autofilled the key field. The `required` normal flag is now removed.

**Comment by soumyalj** [comment]
Tested with build from master head. 
Can create a cluster using S3 backup config, but snapshots are stuck in activating state. 
It fails with the below error in rancher logs:
```
2019/07/18 00:13:04 [ERROR] EtcdBackupController c-g6z9x/c-g6z9x-ms-678dv [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Failed to take one-time snapshot, exit code [1]: time="2019-07-18T00:13:03Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:soumyas3test, err:400 Bad Request" 
```

**Comment by soumyalj** [comment]
Tested with build from master head from July 18
Created rancher server with node having IAM profile with S3 access permissions
Create cluster in EC2 with nodes having the same IAM profile by providing S3 bucket name and without other credentials.
Creating cluster with S3 backup is successful
etcd snapshot and restore are functional as expected
