### ISSUE TITLE
Fix build for CLI alpha builds

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#21311]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
Navigate to alpha release.
Download a zip for an alpha tagged release for CLI and try to build it.

**Result:**
Alpha releases do not include binaries and running "make build" breaks with git error:

`Step 1/2 : FROM cli-2.2.0-alpha1:GwYkFYW
 ---> e8a34d6d0a27
Step 2/2 : COPY . /go/src/github.com/rancher/cli/
 ---> 53e852d84da2
Successfully built 53e852d84da2
Successfully tagged cli-2.2.0-alpha1:GwYkFYW
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
FATA[0049] exit status 128
make: *** [build] Error 1`

**Comment by cloudnautique** [comment]
Our build scripts require a .git directory to be present. Clone the repo, and checkout the tag/branch you want to build.
