### ISSUE TITLE
Add warning when purging environment will delete resources created by API/UI.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2132]
v0.39.0-rc1

Purging environments delete resources created by API/UI but there is no warning that we will be using `docker-machine` to remove them.

Would like a warning or something in the UI to let users know.

**Comment by vincent99** [comment]
@westlywright an additional blurb when deleting environment about this would be good.

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Text is cut off at end.
![image](https://cloud.githubusercontent.com/assets/11514927/13857122/bc281110-ec35-11e5-839c-b25ce5ae04c0.png)

**Comment by tfiduccia** [comment]
Version - master 3.20
Verified fixed
