### ISSUE TITLE
create k8s cluster with custom node error

### ISSUE THREAD

**Issue by bigriver1982** [rancher/rancher#21326]
*Describe your issue here*

why always this error"
Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system"?
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.0-alpha5` UI: `v2.3.2` |
|Route|`global-admin.clusters.index`|

**Comment by kinarashah** [comment]
@fumeiyutks123 could you post the output of `kubectl get configmap rke-network-plugin -n kube-system  -o json | jq -r ".data[]"` for more information?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
