### ISSUE TITLE
No error message presented when creating a cluster with template revision that has invalid kubernetes version format.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21327]
Rancher server version - build from master  `f9aa0fe1`
Steps to reproduce the problem:
Create a cluster template revision with invalid kubernetes version like
`{"rancherKubernetesEngineConfig": {"kubernetesVersion": "1.14"}}`

Create a cluster with this template revision.
Cluster creation fails , but no error message seen in API response:

<img width="968" alt="Screen Shot 2019-07-03 at 7 28 54 PM" src="https://user-images.githubusercontent.com/4266958/60635829-f9b63a00-9dc8-11e9-842c-ef6eec42b046.png">

Rancher server logs shows correct error message
```
2019/07/04 02:26:36 [ERROR] API error response 500 for POST /v3/clusters. Cause: Requested kubernetesVersion 1.14 is not of valid semver [major.minor.patch] format
```

**Comment by prachidamle** [comment]
Updated the error message to popup the log statement seen.

**Comment by sangeethah** [comment]
Tested with latest  build from master `622f66e4`.

Expected error message is presented to the user when a cluster is created with invalid kubernetes version.

```
HTTP/1.1 500
date: Thu, 11 Jul 2019 01:44:15 GMT
content-encoding: gzip
x-api-schemas: https://<ip>/v3/cluster/schemas
content-type: application/json
content-length: 155
expires: Wed 24 Feb 1982 18:42:00 GMT

{
"baseType": "error",
"code": "ServerError",
"message": "Requested kubernetesVersion 1.14 is not of valid semver [major.minor.patch] format",
"status": 500,
"type": "error"
}
```
