### ISSUE TITLE
feature run flag logs error even when not used

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#21321]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
run rancher locally

**Result:**
error ill be logged 

> [ERROR] failed to apply feature args: feature argument should be of the form "features=feature1=bool,feature2=bool"

**Other details that may be helpful:**
just need to return nil when config features is empty

**Comment by rmweir** [comment]
To validate: run locally before fix and after and check console for log error

**Comment by cjellick** [comment]
@dramich can you validate

**Comment by dramich** [comment]
Master 9/24: no longer see error when no feature flags are provided
