### ISSUE TITLE
应用商店存储路径是什么

### ISSUE THREAD

**Issue by yizhishang** [rancher/rancher#21332]
![图片](https://user-images.githubusercontent.com/12756407/60679585-b6d48f00-9eba-11e9-8439-8c1082ef1e6e.png)
“Update failed: fatal: index file smaller than expected : exit status 128”这个错误改怎么解决

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.project.project-catalogs`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or you can find us by searching `rancher2` via WeChat
