### ISSUE TITLE
unable to access 'https://git.rancher.io/community-catalog.git/': gnutls_handshake() failed: Handshake failed

### ISSUE THREAD

**Issue by iamarnavgarg** [rancher/rancher#21330]
**Steps to reproduce (least amount of steps as possible):**
1) `docker run -it --name ub ubuntu:14.04 /bin/bash`
2) `apt update && apt install git -y && git clone https://git.rancher.io/community-catalog.git`

**We receive the following error:**
fatal: unable to access 'https://git.rancher.io/community-catalog.git/': gnutls_handshake() failed: Handshake failed

**The Logs are as belows:**
![image](https://user-images.githubusercontent.com/36654563/60641646-4c840600-9e4a-11e9-92b9-8648ac35b106.png)

**Result:**

The error occurs when performing “`git clone https://git.rancher.io/community-catalog.git`” In rancher server container, having **Ubuntu 14.04**. 

Whereas, in **Ubuntu 16.04** by following the same above steps, **no error occurs**.

**Other details that may be helpful:**

- Docker version (use `docker version`):

```
 Version:           18.09.6
```

Could you please confirm what is the difference between both of these versions that's causing this issue. ?

**Comment by vincent99** [comment]
The version of git/the SSL library packaged with  14.04 does not support one of the algorithms used by the certificate that is presented by the server.

14.04 is not really supported by us (2.x explicitly, 1.x only says "modern"), and is [end-of-life](https://ubuntu.com/about/release-cycle) and  no longer supported by Ubuntu  community releases either.  You should not be using it for anything at this point.

**Comment by iamarnavgarg** [comment]
Dear @vincent99 ,

Thank you for your quick response. 
Actually, it was working fine till 22 jun, but after it, above mentioned error is occurring. happened after the date that it became unsupported and didn't run properly. Could you please confirm in detail?
