### ISSUE TITLE
Flapping connections to cluster agent

### ISSUE THREAD

**Issue by tobru** [rancher/rancher#21337]
**What kind of request is this (question/bug/enhancement/feature request):**

bug?

**Steps to reproduce (least amount of steps as possible):**

No reproduction available, only happens to one of the clusters managed by our central Rancher Management Server:

Every 30 seconds, the connection to the cluster is interrupted and the following lines are logged in Rancher Management Server:

```
2019/07/05 07:53:24 [INFO] Stopping cluster agent for c-sz8ln
E0705 07:53:24.368513       6 request.go:853] Unexpected error when reading response body: &http.httpError{err:"net/http: request canceled (Client.Timeout exceeded while reading body)", timeout:true}
E0705 07:53:24.368662       6 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ConfigMap: Unexpected error &http.httpError{err:"net/http: request canceled (Client.Timeout exceeded while reading body)", timeout:true} when reading response body. Please retry.
2019/07/05 07:53:24 [ERROR] ClusterController c-wtb9x [user-controllers-controller] failed with : failed to start user controllers for cluster c-sz8ln: timeout syncing controllers
2019/07/05 07:53:24 [INFO] Registering project network policy
2019/07/05 07:53:24 [INFO] registering podsecuritypolicy cluster handler for cluster c-sz8ln
2019/07/05 07:53:24 [INFO] registering podsecuritypolicy project handler for cluster c-sz8ln
2019/07/05 07:53:24 [INFO] registering podsecuritypolicy namespace handler for cluster c-sz8ln
2019/07/05 07:53:24 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-sz8ln
2019/07/05 07:53:24 [INFO] registering podsecuritypolicy template handler for cluster c-sz8ln
2019/07/05 07:53:24 [INFO] Registering monitoring for cluster "c-sz8ln"
2019/07/05 07:53:25 [INFO] Starting cluster controllers for c-sz8ln
W0705 07:53:25.075028       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v3.ClusterLogging ended with: too old resource version: 50009123 (50376441)
[...]
```

**Result:**

The connection to the cluster is interrupted and then restarted. On the Rancher webinterface the message `This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.` is displayed.

**Other details that may be helpful:**

* The rancher cluster agent and the node agents do not log anything when this reconnect happens.
* In the browser console I see:
```
Socket connecting (id=1, url=wss://rancher.example.com/v3/subscribe...)
Socket opened (state=connecting, id=1)
Cluster Subscribe connected (sockId=1)
Socket connecting (id=2, url=wss://rancher.example.com/v3/clusters/c-sz8ln/subscribe...)
Socket opened (state=connecting, id=2)
 Subscribe connected (sockId=2)
 Subscribe disconnect (sockId=2)
Socket closing (state=connected, id=2)
Socket 2 closed
 Subscribe disconnected (sockId=null)
```
* Probably related, probably not: Memory usage of the Rancher Management Server goes up and up until it gets OOM-killed and restarted.
* This connection issue only happens with one cluster, the Rancher Management Server manages a lot more clusters without any issues.
* The managed cluster with this issue is behind a firewall with NAT.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `2.2.4`
- Installation option (single install/HA): HA, exactly as described [here](https://rancher.com/docs/rancher/v2.x/en/installation/ha/).

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom (installed with rke on Ubuntu 18.04)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 32 GB RAM, 8 vCPU
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by yi-bai** [comment]
@tobru Hi, have you resolved this problem? We have this problem in latest 2.3.3 version, with an interval of about 30~40 seconds.

**Comment by estein9825** [comment]
Any update on this? I'm seeing similar behavior. Notably it happens because of giant collections of configmaps and secrets in the particular cluster. If it takes more than 30 seconds to read the body of the configmap return it fails. I would love to know how to increase that read timeout value.
