### ISSUE TITLE
cattle-cluster-agent pod CrashLoopBackOff:

### ISSUE THREAD

**Issue by zhangyingluo** [rancher/rancher#21343]
**What kind of request is this (question/bug/enhancement/feature request):**
when i use helm to install rancher-v2.2.4 HA,i found that the pod in namespace cattle-system named **cattle-cluster-agent-7779dd8467-5dtzm** can't Running!

**Steps to reproduce (least amount of steps as possible):**
0:make ssl cert
1:use RKE deploy K8S
2:use helm deploy rancher
3:login webui 

**Result:**
![image](https://user-images.githubusercontent.com/46877792/60716583-61e45780-9f52-11e9-87dc-0ccc39819ae1.png)

![image](https://user-images.githubusercontent.com/46877792/60716513-32354f80-9f52-11e9-80aa-9f0c9962ef36.png)

**Other details that may be helpful:**
1:user private cert 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
1:Rancher version 2.2.4
2:HA-online

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by ahmadarif** [comment]
Hi @zhangyingluo how to solve this issue?

**Comment by rchenzheng** [comment]
This is still happening for local deployments
