### ISSUE TITLE
High CPU usage from Kubelet, dockerd and systemd

### ISSUE THREAD

**Issue by fabiorauber** [rancher/rancher#21346]
**What kind of request is this (question/bug/enhancement/feature request):**
 bug

**Steps to reproduce (least amount of steps as possible):**
Create a Kubernetes 1.13.5 cluster using Rancher 2, with three etcd+Control Plane nodes and 17 worker nodes, all running Ubuntu 18.04 LTS with docker 18.9.2. Run 1400 pods in it.  

**Result:**
See kubelet + systemd + dockerd eating up from 30% to 50% of the CPU at all times. 

**Other details that may be helpful:**
Top screenshot:
![image](https://user-images.githubusercontent.com/2218824/60721049-0fc81580-9f03-11e9-8b6a-7bc6ce876b84.png)

**Environment information**
- Rancher version: v2.2.4
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type: Docker Machine XenServer 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs with 8 vCPUs and 32GB RAM.
- Kubernetes version (use `kubectl version`): 

```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Docker version 18.09.5, build e8ff056
```

**Comment by pierreozoux** [comment]
Did you find anything?

**Comment by GameScripting** [comment]
We are seeing this issue, too.

One Problem that we found was that our eviction-rules regarding nodefs where too tight. This let to kubelet trying to cleanup docker images. As all docker images on the node were used by containers, there was no docker images that could be collected. This resulted in an endless loop with calls to the docker api (trying to clean up images). After increasing the `housekeeping-interval` from `10s` to `3600s` (an acceptable value for *our usecase*) that load has decreased slightly (see https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/).

Now, we are seeing a lot of `streamwatcher.go:114] Unexpected EOF during watch stream event decoding: unexpected EOF` statements in the kubelets log.

**Comment by MatthewJohn** [comment]
@GameScripting, sorry to drag up such an old issue - but could you explain how you changed this?

Personally, since the kubelet mounts a volume for /opt/rke-tools (at least in Kubernetes version v1.22.7-rancher1-1), I updated the entrypoint.sh to add to execution of kubelet, i.e.:
```
if [ "$1" = "kubelet" ]; then
...
        exec "$@" --cgroup-driver=$CGROUPDRIVER $RESOLVCONF &
...
        exec "$@" --cgroup-driver=$CGROUPDRIVER $RESOLVCONF

```
to
```
if [ "$1" = "kubelet" ]; then
...
        exec "$@" --cgroup-driver=$CGROUPDRIVER $RESOLVCONF --housekeeping-interval=3600s --global-housekeeping-interval=3600s &
...
        exec "$@" --cgroup-driver=$CGROUPDRIVER $RESOLVCONF --housekeeping-interval=3600s --global-housekeeping-interval=3600s
```

Is there a way to do this with the cluster configuration in rancher itself?
