### ISSUE TITLE
Import compose->DOCKER-COMPOSE has to be a mandatory field

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2134]
```
Component   Version
Rancher     v0.39.0-rc1
Cattle  v0.95.0
User Interface  v0.52.0
Rancher Compose     beta/latest
```

Rancher compose CLI would not allow rancher-compose create without a valid docker-compose.yml. But in UI,  I uploaded a valid rancher-compose.yml and did not uploade any docker-compose.yml and create. Stack is still getting created. Some sort of validation is needed here.

<img width="1060" alt="screen shot 2015-09-24 at 2 56 25 pm" src="https://cloud.githubusercontent.com/assets/7720752/10088047/c274a08a-62cc-11e5-9c2b-9c7e36e345f4.png">

**Comment by vincent99** [comment]
The compose files are not required, there's nothing wrong with an empty stack.
