### ISSUE TITLE
Error modifying service type

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#21354]
![image](https://user-images.githubusercontent.com/16741882/60768005-6c3d5780-a0f2-11e9-9be1-d2612a4f3373.png)

Steps:

1. Create a workload with ClusterIp port
2. Go to Service Discovery page and edit the type to NodePort
3. Click Save

Results:

Failed to edit via Rancher UI. But it works via YAML

Expected:

Users should be able to change it from cluster ip to node port

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.5-rc4` UI: `v2.2.83-cn-rc1` |
|Route|`authenticated.project.dns.detail.edit`|

**Comment by izaac** [comment]
@loganhz are we only fixing this in master and not 2.3.x ?

**Comment by loganhz** [comment]
yes. If you think we should backport to 2.3, I can create a PR

**Comment by izaac** [comment]
@loganhz confirmed we're good with 2.4 only.

**Comment by izaac** [comment]
Rancher version: `2.4 head (01/13/2020)` commit id: 6c488064c

Validated this is working in 2.4 I can use the UI to change the Type from ClusterIp to NodePort and vice versa. 

Same for editing the YAML.
