### ISSUE TITLE
Command for creating cluster not working

### ISSUE THREAD

**Issue by fred2697** [rancher/rancher#21350]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/question: Is my yaml correct? Or it is a bug?

**Steps to reproduce (least amount of steps as possible):**
Executing the following command: rancher up --file cluster-template.yml

**Result:**
Nothing in the Rancher UI.
Nothing in the Rancher logs.

**Other details that may be helpful:**
Here's the tutorial that I've followed: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cloning-clusters/ 

Here's my yaml template file:
Version: v3
clusters:
    <CLUSTER_NAME>:
    azureKubernetesServiceConfig:
      adminUsername:
      agentPoolName:
      agentVmSize: Standard_D2_v2 
      clientId:
      clientSecret:
      count: 3
      kubernetesVersion: 1.11.9
      location: 
      osDiskSizeGb: 100
      resourceGroup: 
      sshPublicKeyContents: 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Just updated Rancher.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cortopy** [comment]
I just bumped into this issue today. I'm using rancher 2.5.1 and when running `rancher up --file` nothing happens. There is no verbose option in cli and the UI is like nothing happened
