### ISSUE TITLE
Problem with port names in istio (rancher integrated)

### ISSUE THREAD

**Issue by erSitzt** [rancher/rancher#21359]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

- enable Istio and create a Istio-enabled namespace
- create one workload without specifying a port
- create a second workload specifying a port e.g. 8080

**Result:**
The first workload creates a deployment and a service with a port named default and port number 42. The deployment has no matching port config
```
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
```
![image](https://user-images.githubusercontent.com/1625376/60795401-e827b600-a16b-11e9-9f1e-2e237d2ad0ce.png)

The second workload creates a workload and service too, but both have matching port configs.
like this :
```
  ports:
  - name: 8080tcp2
    port: 8080
    protocol: TCP
    targetPort: 8080
```
![image](https://user-images.githubusercontent.com/1625376/60795349-cdedd800-a16b-11e9-83ae-1bd1498fa4ac.png)

Both configs lead to errors in Kialis config check, the first because there is no matching port config in the deployment, the second because the port name is not regarded valid

**Other details that may be helpful:**

Manually correcting the configs does not help, as updates to the workload lead to the service beeing recreated i think...

**Environment information**
- Rancher version : v2.3.0-alpha5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.14.3

**Comment by mbchristoff** [comment]
We're having the same issue with grpc services.
If I create a separate service where the portname has the "grpc-" prefix istio works.
Everytime I try to edit the existing service my changes get reverted, to the best of my knowledge there is no other place within rancher to edit this name.

**Comment by teunis90** [comment]
Same issue here, subscribe to the thread.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/66745106-b7fd5b00-eeb0-11e9-8bf7-5900f61b0aad.png)

Port name has been added in 2.3.0
