### ISSUE TITLE
Azure subscription support

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2135]
Is any topic being discussed around Azure subscription support for hosts creation?

**Comment by deniseschannon** [comment]
In this upcoming release (v0.39.0), generic machine drivers are added to the UI and should be able to add an azure host. Previously, you could only do it through the API, but we've added it to the UI.

**Comment by cusspvz** [comment]
Thanks @deniseschannon ! :)

**Comment by deniseschannon** [comment]
I just found out that the generic machine drivers that had Azure related items did not account for some Azure specific needs. So it will need some additional UI work. I'm re-opening the issue until the special UI for Azure comes out.

**Comment by deniseschannon** [comment]
@cusspvz Apologies for the false info.

**Comment by cusspvz** [comment]
Currently creating images trough `docker-machine`, but it would be nice if it could store `subscription-id` and `subscription-cert`.

**Comment by cusspvz** [comment]
I've created successfully machines using `docker-machine` driver over UI (tried yesterday).
Seems that `cert` needs to be provided as base64.

Since i didn't tried any other drivers, is there any features on others that `docker-machine` doesn't have?

**Comment by cusspvz** [comment]
@deniseschannon 

On `0.39.0` i was able to create Azure instances as I've explained above.

But it seems its broken on `0.40.0-rc1`. :disappointed:

**Comment by deniseschannon** [comment]
@aruneli Can you take a look at this for v0.40.0-rc1?

**Comment by cusspvz** [comment]
forgot to mention whats the error it was throwing...

`this.get('driverChoices')` is returning `undefined` instead of `Array` instance.
<img width="713" alt="captura de ecra 2015-10-1 as 17 39 53" src="https://cloud.githubusercontent.com/assets/3604053/10228787/91888cac-686c-11e5-94b7-35e035d15b65.png">

**Comment by vincent99** [comment]
D'oh, broken in the UI in the last "one more thing" before the rc tag...  Will be fixed next build.

**Comment by aruneli** [comment]
```
Component 	Version
Rancher 	v0.40.0-rc2
Cattle 	v0.96.0
User Interface 	v0.54.0
Rancher Compose 	beta/latest
```

generic machine creation works now.
