### ISSUE TITLE
v2.2.4 Pipeline deployment does not redeploy pods

### ISSUE THREAD

**Issue by ainiml** [rancher/rancher#21352]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Pipeline auto triggers
Pipeline builds docker image
Pipeline pushes docker image with the **same tag** (tag is the same)
Pipeline deploys deployment.yml
New image is not redeployed

**Result:**
Pipeline does not redeploy service with new docker image

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.4`
- Installation option (single install/HA): `single`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `custom`
- Machine type (cloud/VM/metal) and specifications (CPU/memory): `metal`
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by gitlawr** [comment]
You should use `imagePullPolicy: Always` in your pod spec for this case

**Comment by ainiml** [comment]
@gitlawr yep! It still doesn't trigger it pull the new image if it's the same tag

```
imagePullPolicy: Always
```

**Comment by saintanger** [comment]
@ainiml I'm in the same boat here. Have you figured out what was it?

Thanks

**Comment by ainiml** [comment]
@saintanger yep! You're not going to like it

My solution was to change the docker tag in the deployment pipeline

That's the only way to get it to pull the new image

**Comment by saintanger** [comment]
@ainiml lol you'd end up with lots of images. I mean in a way it is the right way but if you want to use always latest on prod for example and run off small sprints its a worse situation I guess.

I think I found a bit more elegant solution.
After a lot of digging I've just found out this is something that people have been moaning about for a while.
https://github.com/kubernetes/kubernetes/issues/13488

So I just tried something and it works, as long as something is changing in the containers yaml description it still triggers an update YAY!

So I just put a new label for the container...

spec:
  template:
    metadata:
      labels:
        gitcommit: ${CICD_GIT_COMMIT} #not the best way to enforce an update, but hey, its working


I hope this helps out someone else as I was bashing my head on the keyboard for a while. It would be nice to be mentioned somewhere in the docs that you cannot just push the same yaml constantly as it would not make a difference

**Comment by ainiml** [comment]
I actually liked this comment

https://github.com/kubernetes/kubernetes/issues/13488#issuecomment-136928669

Something in the spec should change if something gets redeployed. So there is a fall back plan, When your deployment fails 

I do like the image versioning, because it ensures a working version before the new one is deployed

I would almost say it's working as intended, but the timestamp idea is a good one too

**Comment by gitlawr** [comment]
Sorry I hadn't taken a second look on this.
Yep updating the spec helps the redeployment. You can also update the annotation, that's how Rancher does the `redeploy` trick for workloads.
