### ISSUE TITLE
Is it possible to update from Ubuntu-14.04 to supported version(16.04 or higher) regarding rancher1.x docker image or not?

### ISSUE THREAD

**Issue by iamarnavgarg** [rancher/rancher#21360]
1. I pulled the docker image of rancher/server i.e. rancher v1.x from dockerhub and started its container. While checking the details about Ubuntu OS, it is still Ubuntu 14.04. So,could you confirm whether it is still supported ?

2. We understand that, rancher v1.x is not supported on Ubuntu 14.04. Can you please confirm, if Ubuntu- 14.04 can be upgraded to the supported version(16.04 or higher) in rancher1.x docker image? If it is not possible, could you confirm the reason(whether it is hard to support it or any other reason)?

**Comment by iamarnavgarg** [comment]
Hi @vincent99 , 

It seems that the certificates of rancher.io were recently updated. Please find the snapshot of the same as below:

![image](https://user-images.githubusercontent.com/36654563/60877239-120bd600-a25b-11e9-94ee-af0b8da0abdc.png)
If So, could you please confirm whether the issue #21330 is because of this updation in certificates of rancher.io?

**Comment by iamarnavgarg** [comment]
Hi @vincent99 , request you to please respond/confirm to our queries ?

**Comment by iamarnavgarg** [comment]
Hi , request you to please respond/confirm to our queries ?

**Comment by iamarnavgarg** [comment]
Hi sir, request you to please respond/confirm to our queries ?

**Comment by vincent99** [comment]
The cert is from Let'sEncrypt and expires every 90 days so it's updated every 60 (30, or something like that) days.  The service was moved to a different cluster with a different TLS config accepting only modern ciphers, and that is now configured to allow older ones supported by 14.04.

**Comment by iamarnavgarg** [comment]
Hi sir, can you also confirm about the future plan for supporting Rancher v1.x images on Ubuntu 14.04. Whether it has been configured to support it temporarily on Ubuntu 14.04 or will it continue, to support in future?

**Comment by SakshiSharma-India** [comment]
Hi @vincent99 ,

Can you please update on the above comment, i.e.,
about the future plan for supporting Rancher v1.x images on Ubuntu 14.04. Whether it has been configured to support it temporarily on Ubuntu 14.04 or will it continue to be supported in future?

**Comment by vincent99** [comment]
There is no future support of 1.x in general, it has passed our end-of-maintenance date for customers.
