### ISSUE TITLE
Integrate Grafana user authentication with Rancher

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#21365]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Enable monitoring in cluster or project
2. As cluster or project member (user1) access the Grafana GUI, login with default credentials and provide the new password when prompted
3. Login to Rancher as another cluster or project member (user2) and access the Grafana GUI

**Result:**
user2 unable to edit Grafana dashboards unless user1 creates a Grafana account and provides user2 with the credentials.

**Expected Result:**
Users should be automatically logged in the Grafana instance and be assigned a organization role (admin, editor, viewer) based on the role they are assigned in the cluster or project.

See [Grafana Auth Proxy](https://grafana.com/docs/auth/auth-proxy/)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): HA

**Comment by peterolivosuse** [comment]
Commenting to pull this out of stale. I still believe this to be relevant to rancher clients. Managing grafana users outside of rancher is not ideal.

**Comment by catherineluse** [comment]
This feature has been requested in the Rancher Users Slack as well. https://rancher-users.slack.com/archives/C3ASABBD1/p1639066561483300?thread_ts=1638958313.437400&cid=C3ASABBD1

**Comment by catherineluse** [comment]
Commenting to reopen the issue because there is still interest.

**Comment by bstrdsmkr** [comment]
Reset the stake clock, we also need this

**Comment by ppuschmann** [comment]
Reset the stale clock, we also need this

**Comment by bstrdsmkr** [comment]
Still a thing people need

**Comment by bstrdsmkr** [comment]
still a thing people need

**Comment by bstrdsmkr** [comment]
Still no...

**Comment by ZandercraftGames** [comment]
This would be quite useful to have...

**Comment by bstrdsmkr** [comment]
No please

**Comment by bstrdsmkr** [comment]
I'll stand outside this issue's window with a boom box playing "Every Breath You Take" until it gets the attention it deserves

**Comment by ZandercraftGames** [comment]
Honestly. Really hoping that this can be added.

**Comment by bstrdsmkr** [comment]
Could you... Not?

**Comment by bstrdsmkr** [comment]
Seagulls... Stop it now

**Comment by fentonfentonfenton** [comment]
bump

**Comment by lombardoja** [comment]
Please!

**Comment by dani882** [comment]
Im still surprised this feature haven't been implemented. Please work on this
