### ISSUE TITLE
Navigating to Project Pipeline Settings breaks GUI

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#21362]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a new project
2. Add a test user to the project with role "Project Member"
3. Login as test user and in browser navigate to Project->Tools->Pipelines

**Expected:**
Pipeline page displayed

**Actual:**
GUI stuck in loading. No way to cancel or navigate away. 

**Other details that may be helpful:**

<img width="455" alt="Screenshot 2019-07-08 at 18 28 28" src="https://user-images.githubusercontent.com/3813921/60828184-17611600-a1b2-11e9-88d7-9fd843d59cdb.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): HA

**Comment by davidnuzik** [comment]
v2.2.4

I have reproduced exactly as described in the issue description.

master-head

I also reproduced in latest master.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/11/19)

Now the test user (project member) can navigate to the Tools> Pipelines page without any errors and the UI loads properly. They do not have permission to create a pipeline so the expected banner is shown on this page:

![image](https://user-images.githubusercontent.com/45179589/64739656-8f480700-d4a7-11e9-9acd-931047060dc2.png)
