### ISSUE TITLE
Global DNS configuration shows credentials in clear text

### ISSUE THREAD

**Issue by daanemanz** [rancher/rancher#21369]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
* Configure global DNS provider for Route53 (via UI)
* Query the cluster for the new global DNS provider resource:
```
$ kubectl get globaldnsproviders.management.cattle.io route53 -n cattle-global-data -o yaml
apiVersion: management.cattle.io/v3
kind: GlobalDnsProvider
metadata:
  annotations:
    field.cattle.io/creatorId: <user>
  creationTimestamp: "2019-05-10T20:21:47Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  name: route53
  namespace: cattle-global-data
  resourceVersion: "30597018"
  selfLink: /apis/management.cattle.io/v3/namespaces/cattle-global-data/globaldnsproviders/route53
  uid: <uuid>
spec:
  rootDomain: example.com
  route53ProviderConfig:
    accessKey: <IAM Access Key ID in clear text>
    secretKey: <IAM Secret Access Key in clear text>
```

**Result:**
The IAM credentials used to configure the Global DNS provider are shown in clear text.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
`2.2.4`
- Installation option (single install/HA):
`HA`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by alena1108** [comment]
We can leverage "Storing credentials in secrets" feature for that.

**Comment by alena1108** [comment]
@sangeethah as a part of testing, we should check the upgrade use case. Globaldns created prior to upgrade, should continue working.

**Comment by sowmyav27** [comment]
Upgrade from 2.2.6 to master-head
In 2.2.6, create 2 clusters.
Add Global DNS provider and Global DNS entry pointing to cluster1 and project A.
Add a workload and ing pointing to the global DNS in  cluster 1 project A.
Verify global DNS provider resource. The secretKey is seen in plain text.

```
apiVersion: management.cattle.io/v3
kind: GlobalDnsProvider
metadata:
  annotations:
    field.cattle.io/creatorId: user-rflqr
  creationTimestamp: 2019-08-02T16:54:15Z
  generation: 1
  labels:
    cattle.io/creator: norman
  name: test-gdns
  namespace: cattle-global-data
  resourceVersion: "116633"
  selfLink: /apis/management.cattle.io/v3/namespaces/cattle-global-data/globaldnsproviders/test-gdns
  uid: 290ed3bc-b546-11e9-84e7-02c3ab165960
spec:
  rootDomain: x.y.z
  route53ProviderConfig:
    accessKey: xxx.....
    credentialsPath: /.aws
    region: us-east-1
    secretKey: +xxx.....
    zoneType: public
```
Upgrade rancher to master-head
Edit Global DNS entry  and add cluster 2 project B.
Add a workload and ing pointing to the global DNS in  cluster 2 project B.
