### ISSUE TITLE
[UI] Google Auth step 1 copy authorized domains IP to clipboard does not work correctly

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21372]
Version: master-head (7/8/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to set up google auth
- In step 1, click the copy-to-clipboard icon to get the ip/dns of the rancher server
- Follow the steps, when you paste the authorized domain into the Google UI you will get an error.

**Result:**
Google UI will mention that the address you pasted in should not include the http:// or any slashes. It's supposed to only be a proper DNS or FQDN. (Can't be IP too, see https://github.com/rancher/rancher/issues/21371)

We should fix the copy to clipboard function for this one area so it only copied the IP/DNS/FQDN for rancher server. It should not include the protocol and any slashes.

**Comment by etokatlian** [comment]
The same issue above applies to the redirect URI as well. I've added fixes for both.

**Comment by davidnuzik** [comment]
Version: master-head (7/11/19) (`066fcfcc`)

I can confirm that now both the "Authorized Domains" and "Authorized Redirect URIs" copy links now work correctly. The copy the string exactly as shown in the UI.
I double checked the other areas too that copy to clipboard and these are working fine as well.
