### ISSUE TITLE
Forward Port: Color of Rotate now to be changed to make it look like an Actionable text on the UI screen

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#21370]
Forward port rancher/rancher#21283

**Comment by sowmyav27** [comment]
verified with `master-head` (07/09/2019)
<img width="605" alt="Screen Shot 2019-07-09 at 12 17 22 PM" src="https://user-images.githubusercontent.com/26032343/60916556-8dfa2400-a243-11e9-89b2-a9eeac5e52f3.png">


`Rotate Now` is visible now and is seen as an Actionable item

`ui-index` is `https://releases.rancher.com/ui/2.2.86/index.html`
