### ISSUE TITLE
Exclusive deployment via Rancher Portal

### ISSUE THREAD

**Issue by expelledboy** [rancher/rancher#21373]
Question

The official installation docs basically follow;
- provision cloud zone
- create kube HA cluster https://rancher.com/docs/rancher/v2.x/en/installation/ha/kubernetes-rke
- install helm/tiller with its own certs https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-init
- install cert-manage and deploy rancher with certs https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#optional-install-cert-manager
```
helm install rancher-stable/rancher \
  --name rancher \
  --namespace cattle-system \
  --set hostname=rancher.example.com \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=admin@example.com \
  --set letsEncrypt.environment=staging \
  --set replicas=1
```

This would deploy a single node HA "ready" cluster node, on bare metal.

Now Rancher has helm catalogues, from which you can install cert-manager. Ultimately I want certs and helm charts to only be installed via rancher. What next steps can I do?

**Comment by ekristen** [comment]
These instructions are for setting up an HA cluster and then installing Rancher in HA mode. Generally you would then make this cluster (by default named local) off limits for use. Next you'd create additional clusters for use using Rancher. 

From there so long as you don't install helm/tiller stuff. Then generally the only way to install is to use the Apps section of rancher unless you use kubectl to import yaml to request resources.
