### ISSUE TITLE
[UI] Google Auth does not support IP address, should warn user

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21371]
Version: master-head (7/8/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to set up google auth on a single-node rancher (one that only has IP address)
- This will fail, google only supports proper FQDN when setting up auth

**Result:**
Google UI will mention that the address supplied is not proper. It then supplies a link mentioning must be proper FQDN basically.

I think it would be nice to have a message either in the 1st step or as a warning that the rancher URL must be proper FQDN. Otherwise, a user with rancher server URL that is just IP address will try to set up Google auth only to find that they must have proper DNS for rancher server URL.

**This should be documented as well in rancher/docs.**

**Comment by etokatlian** [comment]
I'll add some text in the instruction set indicating that URL must be a FQDN. Thanks David.

**Comment by davidnuzik** [comment]
The new message in grey text is helpful. Could we make this a little darker so it's more visible?
It's also not a big deal but is there a way to reduce the space between it and the "Authorized Domains" line? See below for a screenshot of how it looks currently:

![image](https://user-images.githubusercontent.com/45179589/61091752-37821680-a3f8-11e9-81b9-836aeb58d088.png)

**Comment by davidnuzik** [comment]
@lvuch if you get the cycles do you think you could tweak this a little? I assigned issue to you.
I was thinking we should maybe make the helper text that is in light gray below a little darker so it's easier to read.
And was wondering if there is an easy way to make there not so much space above it.

![Screen Shot 2019-07-11 at 4 23 47 PM](https://user-images.githubusercontent.com/45179589/61091814-73b57700-a3f8-11e9-9069-28bb877b1ffe.png)

**Comment by davidnuzik** [comment]
As for the textual content of the light-gray text (%authPage.googleoauth.notAuthenticated.ul.li2.helperText%) I created a separate issue for this: https://github.com/rancher/rancher/issues/21511

**Comment by davidnuzik** [comment]
Textual changes were validated as a part of https://github.com/rancher/rancher/issues/21511 please refer to that issue instead.

The gray text %authPage.googleoauth.notAuthenticated.ul.li2.helperText% still looks the same. So I am able to close this issue, I created a separate issue to track this minor styling issue here: https://github.com/rancher/rancher/issues/21713
