### ISSUE TITLE
On disabling authentication, the login still shows external auth user as logged in

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21385]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Login to Rancher UI
2. Go to Global --> Authentication --> Google
3. Enter valid credentials and click on Authenticate with Google. 
4. Enter google credentials and click on Allow to authenticate.
5. Google Authentication will be enabled.
6. Click on `Disable Google access`

UI shows message `Google is not configured` 

But on clicking on the user Avatar, it shows google user is logged in.
The principals of the user have not been updated, they still show the google auth user as logged in. And google auth is disabled. 

<img width="1282" alt="Screen Shot 2019-07-08 at 6 59 21 PM" src="https://user-images.githubusercontent.com/26032343/60854617-cd7a2f00-a1b5-11e9-9c90-7b638bafef32.png">

On logging out of Rancher, the user cannot sign in as google user. Google auth is disabled.

**Note:** this is the same behavior for Github Authentication also.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Comment by davidnuzik** [comment]
Note, this is true for ALL auth providers. You have to log out and log back in as local admin for it to be fixed currently.

**Comment by westlywright** [comment]
@deniseschannon David is right. Can we reprioritize this as a nice to have for 2.3?
