### ISSUE TITLE
Cattle-cluster-agent and cattle-node-agent do not rollback to the previous version

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21386]
Version: v2.2.4 to v2.2.5-rc9

Steps:
1. Create a custom cluster in rancher v2.2.4 and create few workloads in the cluster
2. Upgrade to rancher v2.2.5-rc9. 
3. After upgrade, cattle-cluster-agent and cattle-node-agent get upgraded to v2.2.5-rc9
3. Rollback to v2.2.4

After rollback, the cattle-cluster-agent and cattle-node-agent do not rollback to v2.2.4.

![Screen Shot 2019-07-08 at 9.24.19 PM.png](https://zube.io/files/rancher/fd144f7e30ba17711fff7cb60cdb97f6-screen-shot-2019-07-08-at-9-24-19-pm.png)

The same issue is seen for the the below rollbacks too.
1. Upgrade from v2.0.15 to v2.0.16-rc1 and rollback to v2.0.15
2. Upgrade from v2.1.10 to v2.1.11-rc1 and rollback to v2.1.10

**Comment by dramich** [comment]
I am not able to repro this. When doing an upgrade and rollback it can take some time for the cluster to run through the handlers and get updated. If checked immediately after upgrade they won't have had time to go through the controllers and update. It took about 30 seconds before I started seeing changes.

**Comment by cjellick** [comment]
Sending back to QA for er-verification that it exists and to see if we missed anything important about how to reproduce.

**Comment by soumyalj** [comment]
@dramich @cjellick : Reproduced the issue on an upgrade from v2.2.5 to master-head and rollback to v2.2.5. The agent continues to be master-head version

**Comment by dramich** [comment]
@soumyalj can you provide the steps you are doing? How are you running rancher > upgrade > rollback. Where is rancher running? I see the cluster you created is DO.

**Comment by soumyalj** [comment]
@dramich : 
1. Create a single node rancher setup running on a DO/AWS machine. 
2. Upgrade rancher using steps in the docs. 
https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/single-node/
3. Rollback rancher using the steps 
https://rancher.com/docs/rancher/v2.x/en/upgrades/rollbacks/single-node-rollbacks/

**Comment by Tejeev** [comment]
We have seen this issue occur with the following scenario:

1. Installed a Rancher HA Cluster with 2.3.0 and setup a downstream Kubernetes cluster with it. 
2. Created a backup (one-time snapshot) of the rancher HA cluster as described in: https://rancher.com/docs/rancher/v2.x/en/backups/backups/ha-backups/
3. Upgraded to 2.3.2
4. Performed disaster recovery like described here: https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/

The result was, that the rancher HA setup runs then in version 2.3.0 again (as expected), but the rancher agents on all nodes of the kubernetes cluster kept the version 2.3.2.


Running with RancherOS
- More info coming

**Comment by luthermonson** [comment]
2.3
Types: https://github.com/rancher/rancher/pull/24585
https://github.com/rancher/rancher/pull/24594

**Comment by luthermonson** [comment]
master
Types: https://github.com/rancher/types/pull/1057
Rancher: https://github.com/rancher/rancher/pull/24598

**Comment by luthermonson** [comment]
PRs are up, there was a bug in the logic to redeploy the agent during a backup and this is how it works.

1) start rancher 2.3.1, container agent env var == "rancher/rancher-agent:v2.3.1" and that agent is deployed to new clusters
2) snapshot the rancher filesystem using the mentioned ways, the crd for all clusters will contain 2.3.1 agent in that snapshot.
3) upgrade to 2.3.2, container agent env var == "rancher/rancher-agent:v2.3.1" and that agent is deployed.
4) stop the 2.3.2 container and rollback to 2.3.1 using the backup
5) rancher boots with agent env var == "rancher/rancher-agent:v2.3.1" **AND** the restored snapshot contains the clusters crd containing v2.3.1.

The clusterdeploy controller was only checking if the env and clusters crd were the same and never asked the downstream cluster. this can be recreated easily locally in goland if you use the CATTLE_AGENT_IMAGE env var and a local k3s cluster. 
1) Start goland with CATTLE_AGENT_IMAGE="rancher/rancher-agent:v2.3.1"
2) deploy a cluster, stop rancher and update the env var to v2.3.2 and your cluster will get the fresh agent
3) stop rancher, edit the clusters crd for your cluster and set the agentImage to v2.31 to simulate the backup
4) start rancher and you will reach the failing logic.

To fix this, I added a a validate process which reaches out to the deployments/daemon sets we create for the agent and ask for it's image and keep a local map of them and triple check the local rancher crd/envvar are for sure the right ones, redeploy the agent if not.

For debug purposes I also added an agentImageOverride field which you can set your own agent image. This will override this logic and let you run whatever agent you want. To rollback to rancher controlled agentImage you simply need to delete agentImage, agentImageOverride and any desiredAgentImage you find in the CRD and save it. The controller will take over again and redeploy the agent it expects.

**Comment by luthermonson** [comment]
2.3
types: https://github.com/rancher/types/pull/1063
rancher: https://github.com/rancher/rancher/pull/24731

**Comment by luthermonson** [comment]
master
types: https://github.com/rancher/types/pull/1064
master: https://github.com/rancher/rancher/pull/24598

**Comment by soumyalj** [comment]
Reproduced the issue with upgrade/rollback from v2.3.3 to master-head and back to v2.3.3. 
cattle-cluster-agent and cattle-node-agent did not rollback to v2.3.3 version. 

Verified on a upgrade rollback from v2.3-head to master-head and back. 
1. Created a rancher setup with v2.3-head .
2. Upgrade rancher server from v2.3-head to master-head
3. Rolled back rancher from master-head to v2.3-head. 
<img width="1313" alt="Screen Shot 2019-12-30 at 4 37 30 PM" src="https://user-images.githubusercontent.com/18536626/71606077-daebf280-2b22-11ea-8158-f79f1859f411.png">
