### ISSUE TITLE
Google Auth - Copy to clipboard issues under 'OAuth client ID' setup section

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21383]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Login to Rancher UI
2. Go to Global --> Authentication --> Google
3. Under section `1. Configure your Google Application settings`, pointrancher/rancher#3  - `Navigate to the "Credentials" tab to create your OAuth client ID:`

**Issue#1**
The copy to clipboard for `Authorized Javascript origins:` -- On copying the contents and entering this value in Google's `Create OAuth client ID` page-- gives this error **`Invalid Origin: URIs must not contain a path or end with "/".`**

**Expected Result:**
The text present to be copied should not have "/" in the end.

**Issue#2**
The copy to clipboard for `Authorized redirect URIs:` does not copy the whole content shown on the UI.

**Expected Result:**
Copy to clipboard action must copy all of the text shown on the UI.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Comment by etokatlian** [comment]
This has already been addressed in #21372

**Comment by sowmyav27** [comment]
verified on master-head (07/11/2019)
Copy to clipboard issues have been fixed.

Copies as displayed on the UI
<img width="801" alt="Screen Shot 2019-07-11 at 12 00 24 PM" src="https://user-images.githubusercontent.com/26032343/61077533-7baef000-a3d3-11e9-90b1-1cc840bde8f1.png">
