### ISSUE TITLE
CA Certificate or Key is empty

### ISSUE THREAD

**Issue by azbpa** [rancher/rancher#21392]
I tried to Rotate Certificates on a custom cluster `v1.11.9` on Rancher Server `v2.2.2`.

Howver the rotation seems to be not working and I get an endless update loop with the error message:

```
CA Certificate or Key is empty
```

Now the cluster is not operational anymore. What can I do to restore its heath?

**Comment by azbpa** [comment]
This happend again to another cluster. Any idea?

**Comment by superseb** [comment]
If you encounter this again, please include full logs of the container using the `rancher/rancher` image.
