### ISSUE TITLE
cannot import existing cluster 

### ISSUE THREAD

**Issue by grcann101** [rancher/rancher#21394]
*Describe your issue here*
Upgraded rancher to v2.2.4 on the local rancher cluster.
tried to import two current cluster into Rancher , however , the cluster do not connect to rancher.

imported a cluster 
ran the kubectl command to import the cluster from one of the existing cluster nodes.
but this did not import the cluster 
message in the log is:
level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.cluster.monitoring.index`|

Component	Version
Rancher	v2.2.4
User Interface	v2.2.70
Helm	v2.10.0-rancher11
Machine	v0.15.0-rancher8-1

**Comment by alxndr13** [comment]
You need to map the ca-certificates.crt file into your cluster node container. 

For example:
```
-v /etc/pki/tls/certs/ca-bundle.crt:/etc/ssl/certs/ca-certificates.crt
```
