### ISSUE TITLE
UI is very hard to read

### ISSUE THREAD

**Issue by jb1361** [rancher/rancher#21390]
The UI is very hard to read.

![Screenshot_2](https://user-images.githubusercontent.com/9522206/60900348-0b209b80-a23a-11e9-9918-a805c542b344.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Browser|Version 75.0.3770.100 (Official Build) (64-bit)|
|Route|https://172.22.101.101/g/clusters/add|
|Dxdiag Export|[DxDiag.txt](https://github.com/rancher/rancher/files/3373626/DxDiag.txt)|

**Comment by jb1361** [comment]
The image doesn't do my issue much justice, the text was much harder to read on the laptop screen.

**Comment by tfiduccia** [comment]
@jb1361 - 2.3 redesigned the Add cluster page.  The provider names are now in a brighter blue color.  Custom & import are also brighter.  Going to close this, if you feel changes were not adequate, please reopen.
