### ISSUE TITLE
Allow ability to edit ipsec ports due to already using ipsec ports for something else

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2139]
http://forums.rancher.com/t/ipsec-service-into-rancher/441

Summary:

Would like to be able to change the ipsec ports that Rancher uses when there is a conflict.

**Comment by stingelin** [comment]
+1

**Comment by DanielDent** [comment]
Here's another use case for being able to change the ports: I think it might be interesting to use Rancher to manage Rancher. This could be (1) for the purpose of having multiple isolated Rancher deployments, or it could be (2) to manage a HA cluster for the Rancher server.

Rancher's KVM integration can setup VMs which can be managed by a Rancher server. However, there are not always separate IP addresses available to route to the VMs. If ipsec can use a different set of ports, then I think the setup could work.

**Comment by cookandy** [comment]
+1 please.   This creates all sorts of headache for people already running ipsec on the rancher hosts.

**Comment by cooperaj** [comment]
Trying to setup my dev machine as a host in a personal dev rancher environment and I can't get it to work since OSX already has 4500 in use :( Would be great to choose another port.

**Comment by Dremor** [comment]
+1 for this idea. It would be really useful to me.

**Comment by lexrus** [comment]
+1
Have to stop all ipsec services from my servers for Rancher. Please make the port configurable. Thanks.

**Comment by vpusher** [comment]
On both Docker for windows and Docker for Mac, we get into trouble since on both platform the port 4500 is already allocated to IPSec. Would be nice to be able to configure this port.

I see this is not even schedule. In my mind, It's a major issue since most of people develop and test part of their stacks on their personal machine before test on production-like servers.

**Comment by derekhe** [comment]
+1

**Comment by TheBoroer** [comment]
+1 
Just ran into this problem trying to deploy my own ipsec containers on rancher hosts and having them conflict with the rancher-ipsec services
