### ISSUE TITLE
Editing cluster and changing the K8s version(which was a question) fails with "cannot update cluster, cluster cannot be changed to a new clusterTemplate is not a valid option"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21406]
Rancher Server version - Build from master (UI -v2.3.2)

Steps to reproduce the problem:

Scenario1:

Using UI:
Create a cluster Template Revision with `K8s version` and `Network Provider` as questions.
Create a cluster using the above cluster Template Revision by providing K8s version 1.12 and network provider as canal.

Edit cluster and change the   `K8s version` to 1.13.
Edit cluster fails wit following error:
`Validation failed in API: cannot update cluster, cluster cannot be changed to a new clusterTemplate is not a valid option`

When inspecting the call made from UI,  valid values are set for clusterTemplateId and clusterTemplateRevisionId in edit cluster call.

Scenario2:

Using UI:
Create a cluster Template Revision with `K8s version` and `Network Provider` as questions.
Create a cluster using the above cluster Template Revision by providing K8s version 1.12 and network provider as canal with out any nodetemplate set.
When UI complains that there needs to be a nodetemplate for the cluster , set the node template and create the cluster.
User is presented with the following error message

`Validation failed in API: cannot update cluster, cluster cannot be changed to a new clusterTemplate is not a valid option`

**Comment by davidnuzik** [comment]
This issue happens even in templates without any questions.

**Comment by soumyalj** [comment]
Scenario 3:

Using API:
1. Create a cluster template T1 and revisions R1, R2
2. Create cluster with revision R1
3. Edit the cluster and change the revision to R2

Edit fails with the below error:
```
{

    "baseType": "error",
    "code": "InvalidOption",
    "message": "cannot update cluster, cluster cannot be changed to a new clusterTemplate",
    "status": 422,
    "type": "error"

}

```
Changing template revisions should be allowed as long as it is derived from the same template.

**Comment by davidnuzik** [comment]
Note, this seems to be working now on latest master-head. I just didn't test scenario 3. I can edit clusters now that were created with templates whether or not they had any questions.

**Comment by soumyalj** [comment]
Scenario 3 does not error out as above. 
There is a related issue https://github.com/rancher/rancher/issues/21454
