### ISSUE TITLE
Backport: K8s upgrade isn't propagated to nodes manually tainted by users

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21405]
Backport https://github.com/rancher/rancher/issues/16050

**Comment by alena1108** [comment]
The fix is available in v2.2.5-rc12

**Comment by sowmyav27** [comment]
@superseb 

verified the below scenario

1. Had Rancher setup on v2.2.3
2. Deployed a cluster - 1 control plane, 1 worker and 31 etcd nodes.
3. Added taints on all the three nodes.
4. Upgraded the rancher server to v2.2.4
5. Noticed the `cattle-node-agent` and `cattle-cluster-agent` fail to deploy. 
6. upgraded to v2.2.5-rc12(which has the fix)

**Observations:**
`cattle-cluster-agent` is stuck in `Scheduling` state.
`cattle-node-agent` has upgraded to correct version `rancher-agent:v2.2.5-rc12`
`kube-api-auth` has failed to deploy. there are no pods available.
<img width="1335" alt="Screen Shot 2019-07-09 at 4 08 28 PM" src="https://user-images.githubusercontent.com/26032343/60929089-b5151d80-a264-11e9-9c22-6bdb27dbdb05.png">

**Comment by superseb** [comment]
Scenario 1:
- `cattle-cluster-agent` only tolerates etcd and controlplane taints, if those nodes are tainted manually, it won't be able to schedule. Before this it didnt have any tolerations, which made it schedule to workers only (and without workers, it wouldn't be scheduled)
- `cattle-node-agent` allows everything and will run everywhere
- `kube-api-auth` has the same tolerations as `cattle-cluster-agent`

Scenario 2:
Based on the information above, it all works as it is intended to in the logic of the PR.

@alena1108 2 options: allow all taints also for the `cattle-cluster-agent` and `kube-api-auth`, with preference for etcd/controlplane for `cattle-cluster-agent` or document that one of etcd or controlplane nodes can't be manually tainted to make sure the needed pods are scheduled.

**Comment by sowmyav27** [comment]
### 2.2.3 to 2.2.4 to 2.2-head upgrade
**In upgraded 2.2.4**

1 etcd, 1 control plane and 1 worker node
```
cattle-cluster-agent — 1 pod - fails to deploy
cattle-node-agent — fails to deploy - 0 pods
Kube-api-auth — on 3 pods on all 3 nodes - etcd, control plane, worker nodes
```
3 etcd, 2 control plane and 2 worker nodes
```
cattle-cluster-agent — 1 pod - worker - on node - which does not have taint
cattle-node-agent — fails to deploy - 4 pods - on nodes with no taint
Kube-api-auth — on 7 pods on all 7 nodes - etcd, control plane, worker nodes
```

**on an upgrade to rancher:v2.2-head**

1 etcd, 1 control plane and 1 worker node
```
cattle-cluster-agent — 1 on control plane - `rancher/rancher-agent:v2.2-head` --as expected
cattle-node-agent — 3 pods - 3 nodes --as expected
Kube-api-auth — 1 on control plane node --as expected
```
3 etcd, 2 control plane and 2 worker nodes
```
cattle-cluster-agent — 1 on control plane - `rancher/rancher-agent:v2.2-head` --as expected
cattle-node-agent — 7 pods on 7 nodes --as expected
Kube-api-auth — 2 pods on 2 control plane nodes --as expected
```

### v2.2.4 to 2.2-head upgrade
cluster spec: 3 etcd, 2 control plane and 3 worker nodes

**fresh install of 2.2.4**
```
cattle-cluster-agent — 1 on worker node
cattle-node-agent — 8 pods on 8 nodes
Kube-api-auth — 8 pods on 8 nodes
```
**In 2.2-head**
```
cattle-cluster-agent — 1 on control node
cattle-node-agent — 8 pods on 8 nodes
Kube-api-auth — 2 on 2 control nodes
```

pre upgrade and post upgrade automation scripts passed.
