### ISSUE TITLE
Enabled flag for a template revision is missing in UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21407]
Version: master-head

Steps:
1. Create a template in UI with a revision 
2. The flag required to enable a template revision is missing in UI

In the API, a template revision can be enabled or disabled by setting it to true/false
Enabled flag should be exposed in UI

We also need to support editing template revision which should allow for toggling enabled/disabled flag.

**Comment by davidnuzik** [comment]
Version: master-head (7/22/19)

This adds a new action to cluster template revisions in the UI. This allows us to disable or enable them:
![image](https://user-images.githubusercontent.com/45179589/61673258-91f65f00-aca3-11e9-8ddf-c95cec3b4d95.png)
![image](https://user-images.githubusercontent.com/45179589/61673275-a0447b00-aca3-11e9-852a-19c78c9f6da6.png)

_Case 1: _
Attempted to Disable all the cluster templates revisions.
Attempted to leverage this cluster template. It does not show up in the list when creating a cluster, as expected.

_Case 2:_
Create a revision, disable it, ensure can clone from this disabled revision.
This works, and the second revision is also disabled (inherited this enable/disable flag).

_Case 3:_
Use cluster template from case 2, enable the second revision, leave the first one disabled.
Leverage the template, ensure that when create cluster we only see revision 2 (the enabled one). This works correctly. Cluster comes up and works as expected.

_Case 4:_
Attempt to disable cluster template revision while it's still in use by a cluster.
Got growl error. Created two separate issues for this:
Growl error is confusing: https://github.com/rancher/rancher/issues/21698
UI still shows as disabled even though it actually isn't: https://github.com/rancher/rancher/issues/21699
Both of these are minor issues.
