### ISSUE TITLE
Repo with service templates ( with rancher composer config files )

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2141]
I know this isn't the right place to propose this but it would be good for rancher the existence of a repository with rancher composer files in it.

Docker follows the simplicity rule, they gained popularity for the way they handled image configuration. IMHO, rancher is following that also, but it would be even better if you had a repo where ui could grab services templates allowing dev ops, ops and sysadmins to deploy those common services on-the-fly.

**Comment by deniseschannon** [comment]
This sounds like a duplicate of this feature request. https://github.com/rancher/rancher/issues/1272

Please let me know if it's not. (Scroll down the issue to read more about the phases)

**Comment by cusspvz** [comment]
Basically! Thank you for relate both issues! :)

**Comment by vincent99** [comment]
Just FYI since #1272 doesn't have much info in it:  This is actually in the works, there are people currently actively working on creating templates for some common services, a "catalog" API and UI to deploy them.

**Comment by cusspvz** [comment]
Could you please point the repo or folder (in case it is on this repo)? I would be happy to join some.

Actually there is a huge dispersion around cloud-targeted services on containers world. I'm currently analysing *rancher* for the third time (at this moment it seems very useful for production) expect the fact that i don't know yet how services relate between them (maybe because I don't know how your discovery service works either).

After I get into that point, I would be happy to introduce some scalable database and storage solutions as images/compose templates.

**Comment by cloudnautique** [comment]
@cusspvz we are working on compose templates in [rancher/compose-templates](https://github.com/rancher/compose-templates)

**Comment by cusspvz** [comment]
@cloudnautique thanks!
