### ISSUE TITLE
Cannot search for projects with certain names

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21415]
Pre-existing issue.
Version: master-head (7/9/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a project named "123"
- Try to search for it, it will not return results.
- Create a project named "1234567890-=" searching for '=' or '-' will not return results.
- Try with other chars and some others also do not work.

**Result:**
There might be some whitelist or something for search. It doesn't appear to search all for any/all possible chars for project name.

**Comment by n313893254** [comment]
Sorry I can not reproduce it in master (7/11/19).

Here are my steps:
1. Create a project named "123", and Add a namespace named "dad"
2. Search it.

![image](https://user-images.githubusercontent.com/18737885/61028286-eae40e80-a3ea-11e9-8953-05306a402e7a.png)

3. Create a project named "123-=" and add a namespace named "adsdffff"
4. Search for '='

![image](https://user-images.githubusercontent.com/18737885/61028430-42827a00-a3eb-11e9-8a03-b21a29aad3d1.png)

Also, I create a project named "test" and contains no namespaces. Then search "test", it will not return results. 

So I notice there will not show project without namespace when input the search text.  https://github.com/n313893254/ui/blob/1ca84836c579e11b7f17e576c0ef88dac15a67df/app/components/namespace-table/template.hbs#L69

@davidnuzik  Should I fix the issue like this?  Return a result include projects without namespaces? 
![image](https://user-images.githubusercontent.com/18737885/61036318-7b2a4f80-a3fb-11e9-9c2c-8e4eb60b7f18.png)

**Comment by davidnuzik** [comment]
@n313893254 ah yes I think this is the true issue. I did not have namespaces in my projects. I would think yes, ideally we should also return results for projects that have no namespaces. Thanks!

**Comment by davidnuzik** [comment]
Version: master-head (7/12/19)

I am now able to search for projects that have no namespaces within them.

![image](https://user-images.githubusercontent.com/45179589/61159300-6f4c9500-a4b0-11e9-8f92-253e89deece6.png)

![image](https://user-images.githubusercontent.com/45179589/61159315-7bd0ed80-a4b0-11e9-9b9b-3b9fd40c6417.png)

This works regardless of chars in the project. The core issue was not that, it was that we weren't including projects without namespaces in results originally.
