### ISSUE TITLE
[UI] Cluster Templates - "Share Template" section should not be displayed when we add new revisions to a template

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21414]
Version: master-head from July 9th

Steps
1. Create a cluster template T1, template revision R1 and provide user1 "read-only" access
2. Add a new revision to the template T1
When adding new revisions the share template section is shown. It should not be displayed while adding new revisions

![Screen Shot 2019-07-09 at 5.07.28 PM.png](https://zube.io/files/rancher/420f4600a726315f9097e7f1ee8ce65f-screen-shot-2019-07-09-at-5-07-28-pm.png)

Share template is applicable only for templates and not revisions

**Comment by westlywright** [comment]
I disagree that we should hide this on new revision and think we should close this. When you're cloning a cluster revision you're also in an 'edit' state on the cluster template so you can add members to share. You can make the new revision the default, which sets a param on the template. 

cc @tfiduccia

**Comment by deniseschannon** [comment]
Can we test that we can share templates when adding a new revision? adding new members

**Comment by davidnuzik** [comment]
@deniseschannon @tfiduccia I don't see that this is how this works in the API. Membership is at CT level, not CTR level. We should need to rework API. If we expect it to work that way, then we can close this issue and fix this int he API so that API allows us to set members for each CTR

**Comment by davidnuzik** [comment]
Changing membership affects the whole CT (i.e. all revisions). We need to either:
A) Make this more clear to the user, if they change membership on cluster revision it affects ALL revisions.
B) Only allow changing membership at CT level, not CTR. And still ideal to explain that changing membership affects all CTRs

Last option is if we for some reason think it's a must to allow sharing of CTRs _individually_ then we need to create a separate issue and change how the API handles this.

**Comment by soumyalj** [comment]
Tested with build from master-head. We can share templates when adding a new revision

**Comment by davidnuzik** [comment]
I want to reopen this. I understand we have decided to show the "Share Template" section even for CTR (this doesn't make sense to me but the decision has been made). The issue I have, is that we don't make it clear to the user that when you change the membership under the "Share Template" section that it will affect ALL CTR (i.e. the whole CT). We should tweak the wording to make this more clear.

![image](https://user-images.githubusercontent.com/45179589/62649106-0ddde180-b909-11e9-9921-dd284b848ff0.png)

Could we please tweak the en-us.yaml translation for cruClusterTemplate.members.detail ?
Could we change it from "Share this cluster template with individual members or make it public to your organization." (organization is spelled wrong I show it with correct spelling) to something like this?

"Share this cluster template with individual members or make it public to your organization. This affects all template revisions in this cluster template."

**Comment by westlywright** [comment]
I have no problem adding this and push it with the next PR.

**Comment by davidnuzik** [comment]
We need to fix spelling of "orginization" in the string. One this is done we should be good to go :)

**Comment by westlywright** [comment]
I changed the text in rancher/ui#3216

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/12/19)

The fix is complete. We just changed the wording to make it more clear to the user that changing the membership for any CTR affects the entire CT and all revisions.

Screenshot:
![image](https://user-images.githubusercontent.com/45179589/62905134-feea9b00-bd1d-11e9-842a-2006b8a04aed.png)
