### ISSUE TITLE
Global DNS -  Unable to add annotation (rancher.io/globalDNS.hostname)  to Ingress

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#21418]
Rancher version: v2.2.5-rc11

To finalize configuring Global DNS entry, the ingress needs to contain the annotation (rancher.io/globalDNS.hostname), but adding annotations failed.

`"Name" contains an invalid character: .`

<img width="1346" alt="global" src="https://user-images.githubusercontent.com/42061003/60946067-d71fa600-a31f-11e9-8ff4-506f4434caec.png">

**Comment by davidnuzik** [comment]
It works for me @rootwuj 
Does the Name of the ingress contain a '.' ? This is not supported.

**Comment by rootwuj** [comment]
@davidnuzik  Sorry, the description is not clear enough.

**Add reproduce steps:**

Create Multicluster App with Global DNS enabled Ingress for fqdn - "xxx.xxx.com"
<img width="1270" alt="hostname" src="https://user-images.githubusercontent.com/42061003/61017406-a72ade00-a3c5-11e9-825c-623b6f056ee2.png">
The created ingress name is `hostname-namespace`, adding annotation failed because hostname contains '.'
<img width="1309" alt="ingressname" src="https://user-images.githubusercontent.com/42061003/61017417-b3af3680-a3c5-11e9-8d29-ffdbcfc4bea0.png">

**Comment by rootwuj** [comment]
Version - master-head 7/24
Verified fixed
