### ISSUE TITLE
Helm charts not found after Rancher version upgraded

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#21419]
This issue happens in cluster alert enabled and Rancher upgraded. Found in this issue: https://github.com/rancher/rancher/issues/21416.

**Steps to reproduce**

1. Start rancher 2.2.3
2. Add 3~5 clusters in the cluster.
3. Add notifier in each cluster
4. Edit cluster alert group and add a recipient
5. Check if alerting is enabled by looking at apps in system project
6. Upgrade rancher to 2.2.5-rc12
7. Check the status of monitoring-operator apps 

**Problem:**
 ![e.g.](https://user-images.githubusercontent.com/6218999/60932219-d6c8d180-a271-11e9-96c9-4f6fc6a3fc97.png)

As there is no re-try logic in helm controller, apps will be always in the error state until users trigger the update manually.

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/pull/21445

**Comment by orangedeng** [comment]
Fixed in master, closing this issue
