### ISSUE TITLE
Unable to fetch user info

### ISSUE THREAD

**Issue by damozhiying** [rancher/rancher#21417]
admin create some user;
this xx-user has Manage Users role,and is the cluster-one cluster owner;
why xx-user can't  add cluster member,and can't see all user info
![11](https://user-images.githubusercontent.com/10277950/60934692-d4aa5580-a2f9-11e9-9859-a51ba639f41d.png)

**Comment by damozhiying** [comment]
![22](https://user-images.githubusercontent.com/10277950/60934931-a24d2800-a2fa-11e9-85f2-66c3b5531e8d.png)

**Comment by damozhiying** [comment]
the cluster owner xx-user create user jack-1, but xx-user even can't see jack-1 user info 
![11](https://user-images.githubusercontent.com/10277950/60935016-f8ba6680-a2fa-11e9-93a1-dc8f8ad3336b.png)

**Comment by gitlawr** [comment]
Reproducible by the following steps:
1. Go to global - Users, and click `Add User`
2. choose `Custom` for `Global Permissions`, select `Manage Users`, save.
3. Add the user to be the owner of the Default project.
4. Log in as the user

Result:
The error shows in global - users page
The error shows in project - member page

**Comment by gitlawr** [comment]
The cause is missing permissions for the `principals` resource.
Related: https://github.com/rancher/rancher/issues/16216
