### ISSUE TITLE
UI: Click save button again, logging config disappear

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#21426]
**What kind of request is this (question/bug/enhancement/feature request):**

bug
**Steps to reproduce (least amount of steps as possible):**
1. Select the fluentd target and enable project logging.
2. Click save button again without any change.

**Result:**
![image](https://user-images.githubusercontent.com/18737885/60961495-e5c98580-a33e-11e9-8206-759edc221927.png)
Logging config disappear.

**Other details that may be helpful:**

**Environment information**
master ( 2019/07/10 )

**Comment by davidnuzik** [comment]
I wasn't able to reproduce in v2.2-head, or v2.3.0-alpha5; I think at this point we may have lost the ability to reproduce this as I don't have older master. I also reviewed the changes and they look good to me.

**Validation:**
master-head (7/11/19) (`066fcfcc`)

- At project level, enable Fluentd logging on a fresh cluster (click save once).
- Click Save button again. Logging config remains (no longer disappears).

![image](https://user-images.githubusercontent.com/45179589/61091361-bf672100-a3f6-11e9-92a3-03b398f799ea.png)
