### ISSUE TITLE
I deployed a three-node redis statefulset cluster (the k8s cluster has five worker nodes), and then I power off one of the nodes. After a while, check the status of the redis instance of the power-down node on the rancher interface. In the termination state, the redis instance of this node is not migrated to other nodes. Causes the cluster to be unavailable.

### ISSUE THREAD

**Issue by waynezhang1984** [rancher/rancher#21423]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**the cluster has 3 master，5 worker, redis cluster has 3 nodes.
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.2.4
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):1.13

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
please see https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/
