### ISSUE TITLE
[backport] Add ability to access aws ssh keys to EKS

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#21434]
backport of https://github.com/rancher/rancher/issues/14598

**Comment by daxmc99** [comment]
UI issue is here: https://github.com/rancher/rancher/issues/21433

**Comment by cjellick** [comment]
UI not merged yet

**Comment by jiaqiluo** [comment]
The feature is validated on Rancher:v2.2-head 8268cd5f

Steps:
- provision an EKS from Ranch, and during the configuration, choose a key pair from the drop-down list


Result:
- the EKS cluster is up
- check the instances in AWS console and confirm that the key pair name is the same as I chose. 
 - can ssh to the instances by using  the key I chose (this step requires configuring the security group)
