### ISSUE TITLE
Self-healing nodepools - Extremely large values cause `deleteNotReadyAfterSecs` to overflow

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#21431]
rancher/rancher:master-head a4944746

Extremely large numbers can be passed to `deleteNotReadyAfterSecs` field on a nodepool, causing the value to overflow. The ranges should be limited or the values truncated. 

Actual:
* Create a cluster with a dedicated worker nodepool
* Edit `deleteNotReadyAfterSecs` on nodepool to have an extremely large negative or positive number:
  * 100000000000000000000
  * -19223372036854776000
* `deleteNotReadyAfterSecs` overflows and the value is set to: 
  * `deleteNotReadyAfterSecs": -9223372036854776000`

Expected: 
* Values below 0 truncated to 0 or the request denied
* Values above a reasonable limit truncated or the request denied

**Comment by daxmc99** [comment]
Solved via: 

- values less than zero throw an error
- values greater than maxInt64 throw an error (> 9,223,372,036,854,775,807)

**Comment by bmdepesa** [comment]
rancher/rancher:master 17ecf7bf

* Created cluster
* Edited nodepool `deleteNotReadyAfterSecs` to a negative value
* API presented an error for `MinLimitExceeded`
* Edited nodepool `deleteNotReadyAfterSecs` to a value greater than maxInt64
* API presented an error for `MinLimitExceeded`
* Edited nodepool `deleteNotReadyAfterSecs` to a range of realistic values (minutes to days)
* API requests succeeded
* Edited nodepool `deleteNotReadyAfterSecs` to a few minutes, stopped a node, and saw a new node provisioned
