### ISSUE TITLE
Ability to schedule recurring containers that run on a cron-like schedule

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2143]
Per http://forums.rancher.com/t/scheduling-recurring-cron-like-tasks-using-containers/555

Create ability to schedule containers through Rancher

**Comment by alejom99** [comment]
+1

**Comment by eebjr** [comment]
+1

**Comment by tdensmore** [comment]
+1

**Comment by kaos** [comment]
+1

**Comment by wonderslug** [comment]
+1

**Comment by nhumrich** [comment]
+1

**Comment by renaudManda** [comment]
+1

**Comment by croemmich** [comment]
+1

**Comment by RVN-BR** [comment]
+1

**Comment by ibuildthecloud** [comment]
+1

**Comment by kaos** [comment]
@ibuildthecloud :)

**Comment by chazmuzz** [comment]
+1

**Comment by alena1108** [comment]
Its like the longest +1 (with 0 comments interruptions) list I've ever seen :)

**Comment by kaos** [comment]
Yeah, the title says it all :)

Skickat från min iPhone

**Comment by vincent99** [comment]
So nobody likes https://www.cronasaservice.com/ + API calls? :smile:

**Comment by chazmuzz** [comment]
@vincent99 That looks cool but most of the reason that I'm interested in Docker and Rancher is so that I don't have to rely on *aas providers!

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/10525155/feb894cc-7337-11e5-8385-fa74019dc3d8.png)

**Comment by kaos** [comment]
@alena1108 see what you started :p ;)

**Comment by alena1108** [comment]
+1 

@kaos (to get back to the main loop although I like @vincent99 gifs) :)

**Comment by RoryHunter** [comment]
+1

**Comment by antmanler** [comment]
+1

**Comment by trotro** [comment]
Seems crond and crontab are present in ranchOS v0.4.1, but `crontab -l` or -e failed (even as root)
`crontab: can't change directory to '/var/spool/cron/crontabs': No such file or directory`

`/var/spool/cron` is missing and the crond process doesn't seem to run.
I didn't try to create the missing dir and file yet.

**Comment by kaos** [comment]
@trotro This issue is for cron like support in `rancher`, not `rancherOS`..

**Comment by trotro** [comment]
@kaos sorry, I thought this can be related and helpful.

**Comment by dahendel** [comment]
Any update on whether or not this is getting implemented soon?

**Comment by michaellopez** [comment]
+1

**Comment by lavvy** [comment]
I had actually voted for this feature,  but i am kind of seeing more use cases with this. 
What if this feature should be developed to be job scheduler.  And the jobs will be subsequently saved for reuse. The jobs will be packaged like very simple containers and be running in cron then rancher will be monitoring and managing their lifecycles. 
The jobs processes will be scheduled according to time frame or resources available.

**Comment by budjizu** [comment]
+1

**Comment by ebr** [comment]
very much +1.
we currently use long-running tasks within containers that implement their own cron-like scheduling (i.e. using https://www.npmjs.com/package/node-schedule). But this is very inelegant and not manageable at any reasonable scale.
I was thinking of writing a containerized service that will only implement scheduling, yet be sufficiently privileged to access the docker daemon on the host to kick off jobs (but perhaps not anything else). Not yet sure how to approach it though.

**Comment by michaellopez** [comment]
@ebr Take a look at https://github.com/ActiveState/dockron/ it works well for a containerized cron implemented in Go that can talk to the daemon and launch sibling containers.

**Comment by ebr** [comment]
@michaellopez :heart_eyes: thank you. that's pretty much the way i've been thinking of tackling it.

**Comment by dahendel** [comment]
Just checking in to see if this will be implemented anytime in the near future.

**Comment by kaos** [comment]
@dahendel I'm not associated with Rancher, but I dare say that in the near future it is not, based on the fact that this issue is not (yet) part of any milestone.

**Comment by fernandoneto** [comment]
+1

**Comment by withinboredom** [comment]
+1

**Comment by clescot** [comment]
+1

**Comment by demarant** [comment]
+1

**Comment by dbones** [comment]
+1

**Comment by willseward** [comment]
+1

**Comment by tak3r** [comment]
+1

**Comment by kaos** [comment]
@jonwarghed (på tal om att köra cron job i docker...)

**Comment by atrauzzi** [comment]
+1

**Comment by ahansson89** [comment]
+1

**Comment by jonwarghed** [comment]
This would be a very nice addition, we have several reocurring jobs that would improve of being controlled from the rancher host and associated staff rather than the internal cron jobs from the container itself. +1

**Comment by CrystalMethod** [comment]
+1

**Comment by hwinkel** [comment]
Is rancher really the right place to schedule such things? I think a orchestrator should not be in charge of such process at least not the central rancher instance. You could argue that a service on the host could be responsible for that. In the same fashion as the agent-instance?

**Comment by michaellopez** [comment]
@hwinkel I like the idea of telling Rancher to run a certain stack at an interval. As I mentioned earlier, I don't mind going with https://github.com/ActiveState/dockron/ my self, without Rancher natively supporting this. I haven't gotten to tackling this issue myself yet, so maybe dockron is insufficient, I don't know...

**Comment by hwinkel** [comment]
@michaellopez fine with having such a cron functionality , but don't like to have the central instance responsible for that. So I would prefer to have it as part of the instance agent

**Comment by raphink** [comment]
For the record, we're using https://github.com/dshearer/jobber for that, which is better suited for containers than cron.

**Comment by eebjr** [comment]
(-1) I'm changing my mind on this one...

There are so many tools out there that are easy to use, like Jenkins, that can easily be set up to run a container or start an existing service stack periodically by simply using the Rancher API. 

Maybe it would be better to let some innovative person with time on their hands create a custom catalog service for this feature. :-)

**Comment by kaos** [comment]
@eebjr I wouldn't like having to rely on a jenkins instance for this. Sure, if I already had one, it would work, but it feels like an unnecessarily complex setup. I'd prefer to have a combination of a `start-once` service with a label indicating with which periodicity it should be started, or something like that, and be done with it ;)

But sure, this ought to be implementable as a global service, akin to the rancher dns one, looking at all services identifying which should be kicked when.. and as such could be contributed, +1 on that :) (not saying that a integrated solution couldn't be contributed as well, but perhaps harder to do..)

**Comment by atrauzzi** [comment]
@eebjr - Jenkins is orthogonal to what this ticket is describing.

_"not the one"_

**Comment by hugochinchilla** [comment]
+1

**Comment by ClementVidal** [comment]
+1

**Comment by opb** [comment]
+1

**Comment by Zenithar** [comment]
+1

**Comment by 2devnull** [comment]
+1

**Comment by kaos** [comment]
Why're not more ppl using the new github feature "Pick your reaction".. ??
![image](https://cloud.githubusercontent.com/assets/72965/14845896/4c69ba9e-0c61-11e6-9d88-d6661f55c2b0.png)

It helps reduce unwanted noise considerably, at the same time gives a better overview of the total sum of responses (there's currently 6 👍  for this feature request, and I don't know how many +1's in the comments, as I can't be bothered to count'em). Also, you can now clearly give 👍  on a particular comment too..

What am I missing here?

**Comment by keras** [comment]
@kaos, One reason: When you add new comment you can then search all the issues involving you with `involves:<myname>`. "Pick your reaction" doesn't `involve` me in the issue and it's forgotten for forever.

If you have another way for tagging an issue for later searching I'd love to know.

**Comment by kaos** [comment]
Ah, thanks @keras, that makes sense. I suppose that's a good enough reason until @github adds a search predicate for reactions. (would be nice with one for notification status too, so you can find all issues you're currently subscribed to; as that would work for this particular case too)

**Comment by c0deaddict** [comment]
+1

**Comment by smazurov** [comment]
I have created a [service](https://github.com/SocialEngine/rancher-cron) that can start containers on a schedule. Its pretty easy to get going.

First, launch it using this `docker-compose.yml`:

```yml
rancher-cron:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  image: socialengine/rancher-cron:0.1.0
```

Then, have a _Start Once_ container in a service with `com.socialengine.rancher-cron.schedule` label:

```yml
cron:
  labels:
    io.rancher.container.start_once: 'true'
    com.socialengine.rancher-cron.schedule: '@every 10m'
  image: your-cron-image
```

Then, [`rancher-cron`](https://github.com/SocialEngine/rancher-cron) service will use rancher metadata to find the schedule, and will launch `cron` container every 10 minutes.

**Comment by tejerka** [comment]
+1

**Comment by doc** [comment]
+1

**Comment by MaxNoe** [comment]
+1

**Comment by saphoooo** [comment]
looks weird discution as all tools are in ranchos. my use case: schedule a backup of the embedded cattle database. a bit oldschool maybe, but run perfectly:
```
#cloud-config
hostname: rancher-server
write_files:
  - path: /var/spool/cron/crontabs/rancher
    permissions: "0600"
    owner: root
    group: rancher
    content: |
      * * * * * /bin/docker exec -t rancher-server1 mysqldump -A > /home/rancher/cattle.sql
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      crond
rancher:
  network:
    interfaces:
      eth*:
        dhcp: true
  services:
    rancher-server1:
      image: rancher/server
      restart: always
      ports:
        - 8080:8080
```
et voila!

**Comment by ebr** [comment]
@saphoooo you are using `cloud-config` and `cron` - this has nothing to do with container scheduling, not to mention being unmaintainable.

**Comment by saphoooo** [comment]
right, my apologies, I'll put my glasses for the next time...

**Comment by keras** [comment]
So far my solution has been a [every](https://gist.github.com/keras/21ee88dce91faa1dbb6afdf8c431885b) -shell script. With rancher it usually fits quite well on to some sidekick container. But it doesn't depend on rancher in any way.

Usage:

```yaml
app:
  image: my-app
  command: every 10mins /srv/bin/periodic-task --args
```

**Comment by ebr** [comment]
@keras so this assumes an `app` container continuously runs, and the sidekick takes care of launching an executable inside the running `app` container? 
This is a cool idea and may work for some cases, although I don't think it fits the use case that is being asked for here:

  - provision a service whose default state is to have 0 running containers;
  - at configured time, or periodically, create and start `N` containers for this service, scheduled onto hosts as per service's scheduling rules;
  - assume the containers will perform work and exit (?);
  - at next scheduled run time, if the number of running containers for this service `n < N`, create and start `N - n` containers (i.e. consolidate current and desired states)

This should be an extension of the "restart policy" setting, even though it does not map directly to restart policies supported by Docker API.

**Comment by atrauzzi** [comment]
Odds of this being read after more comments pile in are slim, but for future commenters, it's really worth highlighting that this is a request for a rancher-level feature.  Not a workaround or hack via other supporting containers.

The idea behind this ticket is to avoid having to resort to creative designs and to get scheduling as a first class feature in Rancher so that it can work consistently across the various backends.

**Comment by frleb** [comment]
+1

**Comment by AlexisDucastel** [comment]
+1 :)

**Comment by opb** [comment]
Given rancher now supports mesos, chronos could potentially fill this requirements in some use cases.

**Comment by hugochinchilla** [comment]
@opb what about people who prefer cattle or swarm? I personally find Mesos too complex and prefer to stay away from it, cattle and swarm are easier to understand and debug if the case arises.

**Comment by lenzenmi** [comment]
+1, and an additional thought.

Also allow scheduling `docker exec` calls into a running container. Obviously rancher can open shells already, so this seems like a reasonable extension for a cron-like scheduler.

Why?

Say I have a gitlab omnibus container running. I'd like to automate backups. 

Currently, I can exec into the running container and issue the command `gitlab-rake gitlab:backup:create`. Great, but the command won't run from a sidekick container, so the so-far proposed cron pattern won't help.

I could schedule a cron job on the host to run this periodically, but every time I upgrade the container, the container id changes. Also, the container name seems to be in flux alternating between something like r-Gilab_gitlab_1 and random_dockername. Not good for programming into a crontab.

So, while we are on the topic of scheduling the run of one-shot containers, why not extend it to include scheduling the execution of commands in already running containers?

**Comment by roflmao** [comment]
Just created an image for every.sh which can run as a sidekick: https://github.com/roflmao/docker-scheduler

**Comment by francoishill** [comment]
@lenzenmi you should be able to achieve your goal with https://github.com/SocialEngine/rancher-cron

**Comment by atrauzzi** [comment]
@francoishill - See my last comment.

**Comment by francoishill** [comment]
I hear you @atrauzzi, agreed!

**Comment by smazurov** [comment]
You can do this with `rancher-cron`. Create a sidekick container and use that command as the main container command. Select 'start-once' and it will not try to re-run the command after it exits.

**Comment by atrauzzi** [comment]
@smazurov - See the comment I just pointed @francoishill to.  And to anyone jumping on this thread: We know there are ways to do this with containers.  That's not what this ticket is about.

**Comment by parruda** [comment]
+1

**Comment by dirkdevriendt** [comment]
Kubernetes is adding "Scheduled Jobs" as a core feature in 1.4 beta (see http://janetkuo.github.io/docs/user-guide/scheduled-jobs/ for preliminary docs). It would make sense for Rancher to provide a unified API+UI to create/manage jobs in Kubernetes and Mesos/Chronos (and of course add an implementation to cattle as well :-))
I wouldn't be surprised if there were already a scheduler of some sort in rancher for maintenance tasks that would benefit from a distributed approach.

**Comment by foobah** [comment]
+1

**Comment by diceone** [comment]
+1

**Comment by toughIQ** [comment]
+1

**Comment by roudrik** [comment]
+1

**Comment by warroyo** [comment]
+1

**Comment by Joeasaurus** [comment]
+1

I have exactly the same usecase as @lenzenmi.

As already stated in here, I can see it as a small extension on the run-once syntax. I'd just like to say "This docker runs <some job> and please start it once an hour". The container will be responsible for exiting once finished, and if it is still running at the next scheduled time, some action or nothing can happen (maybe a flag on that or something).

Rancher is the perfect place to implement such a thing. It's the orchestrator so help me orchestrate :)

**Comment by jim12321** [comment]
+1

**Comment by svenluzar** [comment]
+1

**Comment by deviousgeek** [comment]
+1

**Comment by willseward** [comment]
Well, we're about a quarter of the way to an "unscheduled" release, and this is on the roadmap, haha.

In my opinion, this would be a great infrastructure service.

**Comment by paeffgen** [comment]
+1

**Comment by jeffersonsouza** [comment]
+1

**Comment by Amooti** [comment]
+1

**Comment by ivan-savciuc** [comment]
+1

**Comment by sshipkov** [comment]
+1

**Comment by camilin87** [comment]
Is this helpful in any way?

https://www.tddapps.com/2017/02/18/how-to-run-any-container-on-a-schedule/

It is a container to run other containers on a schedule.

**Comment by inkadnb** [comment]
+1

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/23771086/f13ce950-04d2-11e7-9c2c-52c6653bab21.png)

**Comment by michaellopez** [comment]
@vincent99 I assume that picture is https://github.com/rancher/container-crontab ? Will it be added to the official catalog soon?

**Comment by justmiles** [comment]
It's already in the community catalog: https://github.com/rancher/rancher-catalog/tree/master/infra-templates/container-crontab

**Comment by michaellopez** [comment]
@justmiles Thanks for that. I missed looking in the `infra-templates`.

**Comment by inkadnb** [comment]
It doesn't look like it so correct me if I'm wrong, but does Rancher Container Crontab allow you to _schedule_ starting up a container at a specific time?

Basically my scenario is this: I want to be able to start short-lived containers based on different events happening in the system. I'm trying to cut down on EC2 costs for a server that's idle 99% of the time. The lifecycles of my containers are very predictable as they're essentially sequential.

**Comment by kimgust** [comment]
Is there a trick to starting containers _only_ on the cron schedule? As a rudimentary example, say I want to print the date on the minute every minute, what I get is the date printed when the container is first started up, followed by every minute on the minute.

docker-compose.yml:
```
version: '2'
services:
  jobs:
    image: centos:7
    command: date
    labels:
      cron.schedule: 0 * * * * *
      io.rancher.container.start_once: true
      io.rancher.container.pull_image: always
```
rancher-compose.yml:
```
version: '2'
services:
  jobs:
    scale: 1
    start_on_create: true
```
Deploy command:
```
rancher up -d
```
I get:
```
Thu Apr  6 22:07:45 UTC 2017
Thu Apr  6 22:08:00 UTC 2017
Thu Apr  6 22:09:00 UTC 2017
...
```
Basically, I'd like to skip the first run, since the container will first run whenever I run the deploy command.

One trick I could think of was to add something to the `command` to touch and check a file.

I was hoping to use this for running a script every night at midnight only.

Setting `start_on_create: false` in rancher-compose.yml doesn't appear to do anything.

**Comment by xaka** [comment]
@kimgust have you figured how to skip first run? thanks!

**Comment by kimgust** [comment]
We put put a first run check by touching a tmp file in the run script. For a really time sensitive one we also added a time window check.

**Comment by nimboya** [comment]
This could also help 
https://github.com/SocialEngine/rancher-cron

**Comment by meggarr** [comment]
Is this available for K8s env?
