### ISSUE TITLE
Support for Calico 3.5

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21448]
Rancher version:
v2.2.4

Description:
We need to work with Calico Ver 3.5 because of the pool per name space functionality. 
Currently the default is 3.4, when is 3.5 expected?

https://www.projectcalico.org/whats-new-in-calico-3-5/

**Comment by alena1108** [comment]
@jambajaar calico images are updated to the v3.7 for k8s 1.15 - the version that will be default in Rancher v2.3

https://github.com/rancher/kontainer-driver-metadata/pull/3

**Comment by alena1108** [comment]
https://github.com/rancher/rke/issues/1168

**Comment by sangeethah** [comment]
Tested with latest build from master using `master-head`

Create a cluster with network provider set to `calico` using K8s version - v1.15.0-rancher1-1.
Calico version v3.7.4 gets deployed.

Cluster gets deployed successfully.

<img width="1319" alt="Screen Shot 2019-07-18 at 11 51 19 AM" src="https://user-images.githubusercontent.com/4266958/61483828-73fec680-a952-11e9-83e6-da0b6eca3449.png">

All existing automation runs work as expected.
