### ISSUE TITLE
[UI] Add support for edit action of cluster template to change default template revision id, toggle public flag and template sharing.

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21442]
We'd like to add support for users to be able to edit cluster templates so that the admin/owner is able to change Template Sharing. 
We should be able to change the default template revision id .
We should be allowed to toggle public flag (Make public (read-only)).

**Comment by davidnuzik** [comment]
Version: master-head (7/18/19)

Overrides do not change when I change up my templates. I think that the UI isn't refreshing and reading in the new template when switch them from the dropdown.

**Comment by soumyalj** [comment]
Tested with master build from July 18th. 
Created a cluster template t2 and revision rev2 . rev2 was the defaultrevisionid
Created another template revision rev3.
Edited the template and changed the revision id to rev3. 
The default revision id does not change . 
The request sent with edit is:
```
{"annotations":{},"baseType":"clusterTemplate","created":"2019-07-18T19:57:12Z","createdTS":1563479832000,"creatorId":"user-nclc4","defaultRevisionId":"cattle-global-data:t2rev2","description":null,"enforced":false,"id":"cattle-global-data:ct-fmj9b","labels":{"cattle.io/creator":"norman"},"links":{"clusterTemplateRevisions":"https://45.79.108.77/v3/clusterTemplateRevisions?clusterTemplateId=cattle-global-data%3Act-fmj9b","clusters":"https://abcd/v3/clusters?clusterTemplateId=cattle-global-data%3Act-fmj9b","remove":"https://abcd/v3/clusterTemplates/cattle-global-data:ct-fmj9b","revisions":"https://abcd/v3/clusterTemplates/cattle-global-data:ct-fmj9b/revisions","self":"https://abcd/v3/clusterTemplates/cattle-global-data:ct-fmj9b","update":"https://abcd/v3/clusterTemplates/cattle-global-data:ct-fmj9b"},"members":[{"accessType":"read-only","groupPrincipalId":"*","type":"/v3/schemas/member","userPrincipalId":null}],"name":"test2","type":"clusterTemplate","uuid":"3b971dda-a996-11e9-8dd3-0242ac110002"}

```
The response is :
```
{"annotations":{},"baseType":"clusterTemplate","created":"2019-07-18T19:57:12Z","createdTS":1563479832000,"creatorId":"user-nclc4","defaultRevisionId":"cattle-global-data:t2rev2","description":null,"enforced":false,"id":"cattle-global-data:ct-fmj9b","labels":{"cattle.io/creator":"norman"},"links":{"clusterTemplateRevisions":"https://abcd/v3/clusterTemplateRevisions?clusterTemplateId=cattle-global-data%3Act-fmj9b","clusters":"https://45.79.108.77/v3/clusters?clusterTemplateId=cattle-global-data%3Act-fmj9b","remove":"https://abcd/v3/clusterTemplates/cattle-global-data:ct-fmj9b","revisions":"https://abcd/v3/clusterTemplates/cattle-global-data:ct-fmj9b/revisions","self":"https://abcd/v3/clusterTemplates/cattle-global-data:ct-fmj9b","update":"https://abcd/v3/clusterTemplates/cattle-global-data:ct-fmj9b"},"members":[{"accessType":"read-only","groupPrincipalId":"*","type":"/v3/schemas/member","userPrincipalId":null}],"name":"test2","type":"clusterTemplate","uuid":"3b971dda-a996-11e9-8dd3-0242ac110002"}



```

**Comment by davidnuzik** [comment]
Version: master-head (7/22/19)

**Case 1 - Change default rev id:**
- Created a cluster template with revision rev1. This was the default (as are all initially created).
- Added a second and third revision, rev2 and rev3.
- Performed Edit action in UI on the cluster template and got the new Edit Cluster Template modal. Changed the revision to rev2 and saved. Confirmed the UI listing updates and now the checkmark is seen on rev2 for "Default Revision"
- Performed "Set as Default" action in UI on rev3 revision and observed the UI update the Default Revision to rev3 immediately. A green pop-up at the top right also indicates success.

**Case 2 - "Make Public" setting:**
- Using the cluster template from case 1, performed the edit action to get the Edit Cluster Template modal.
- Clicked on the "Make public (read-only)" button. Immediately saw "Public (all members & groups)" show up below, see screenshot below:
![image](https://user-images.githubusercontent.com/45179589/61660806-8f820e00-ac7f-11e9-8ee3-61a4391ebfb5.png)
- Clicked on the "Make public (read-only)" button a second time, there is a small bug where this is now listed twice - created a separate issue for that here: https://github.com/rancher/rancher/issues/21685
- Removed extra entries. Confirmed I can add "Public" and remove, and re-add without any issues. Ensured http/api are correct.
- Logged in as a few standard users. Ensured they can all access the leverage the template without any not-yet-known issues. Note: due to a bug I could not actually fully create a cluster with public templates. This doesn't work correctly in the UI although a cluster may appear in the UI. Related to https://github.com/rancher/rancher/issues/21617 and various.
- Logged back in as admin, edited cluster template (which is in use by one of my standard users) and remove public access. I was able to do this even though it's in use currently. I am not certain if this is expected so created this issue to track: https://github.com/rancher/rancher/issues/21686
- Performed tests again, but while creating cluster instead of via Edit action. This too is working as expected.

**Case 3 - Template sharing:**
- Using the cluster template from case 1, performed the edit action to get the Edit Cluster Template modal.
- Briefly test all the different types of membership on different users (Owner, Member, Read-only).
- Logged in each, ensure that. Noticed that each Owner, Member, Read-Only all have the same access. They can leverage templates but can't clone, set defaults, enable/disable, delete, etc (none of them). Opened separate issue to track this: https://github.com/rancher/rancher/issues/21689
- Otherwise can confirm all users that are shared the template can leverage the template and create clusters.

NOTE: Due to known issues the members cannot always leverage the templates. They get a backend json error in rancher logs sometimes. This is being looked into and will create an issue if one does not exist.
