### ISSUE TITLE
Forwardport: Alerting - cluster-alerting app shows errors after upgrading Rancher

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#21449]
https://github.com/rancher/rancher/issues/21416

**Comment by jiaqiluo** [comment]
The bug fix is validated in the upgrade path from v2.2.3 to master-head

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:v2.2.3 container 
- as admin, enable Github auth
- log in as Github user user1
- add 4 EC2 single-node clusters, and configure them:
  - only-alerting
  - only-alerting
  - only-logging
  - both-logging-alerting
- upgrade Rancher to master-head e65f73a9

Results:
- `cluster-alerting` and `rancher-logging` apps upgrade to the latest versions automatically after upgrading Rancher.
- the `no such file or directory` error does not show anymore
- the `unable to handle the request` error still exists and has been tracked here:
https://github.com/rancher/rancher/issues/21480
