### ISSUE TITLE
rancher-compose build: Allow ability to authenticate against GHE to build

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2144]
http://forums.rancher.com/t/deployment-options-using-github-enterprise-rancher/541/5

Currently rancher-compose does not support being able to build against GHE. If Rancher is configured against GHE, it'd be nice to also allow the ability to build against it in rancher-compose.

**Comment by mdahiemstra** [comment]
👍

**Comment by lweeks** [comment]
👍

**Comment by nicolinux** [comment]
Any news on this issue? I think it is not nice to rely on public git repos when you want to avoid the S3 alternative...
