### ISSUE TITLE
Admin user icons differ between nav bar icon and edit cluster view Member Roles area

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21440]
Version: master-head (7/10/19)
Version: v2.1.9 (is a pre-existing issue)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, low impact

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster. Edit the cluster and expand the "Member Roles" pane.
- Look at the "admin" user display picture, compare to the user nav menu picture.

**Result:**
The two pictures are different for some reason.
![Screen Shot 2019-07-10 at 1 23 58 PM](https://user-images.githubusercontent.com/45179589/61002424-5dcf8580-a316-11e9-9fb2-146219a5b82d.png)

**Other details that may be helpful:**
Pre-existing issue and I can't imagine how this would be any significant impact to anyone.

**Comment by tfiduccia** [comment]
I'm not sure why this looks completely different from the add cluster member section.  These both need to be consistent and have same look and info.

**Comment by sowmyav27** [comment]
**Verified on latest -master**
ui tag: latest2
The admin icons are the same.

**On add cluster page.**
<img width="1309" alt="Screen Shot 2019-10-22 at 2 09 22 AM" src="https://user-images.githubusercontent.com/26032343/67241449-18703780-f471-11e9-802f-469dcb97da41.png">

**On edit cluster page.**
<img width="1297" alt="Screen Shot 2019-10-22 at 2 08 27 AM" src="https://user-images.githubusercontent.com/26032343/67241464-1efeaf00-f471-11e9-9d87-e912dcee23e4.png">

**Comment by deniseschannon** [comment]
@sowmyav27 This was merged into the UI before 2.3 shipped so even though it's 1 PR it's available in 2.3-head and master.

**Comment by soumyalj** [comment]
Reproduced the issue in v2.3.0
Tested with v2.3-head. 
Scenario 1:
Create a cluster. Edit the cluster and expand the "Member Roles" pane.
Look at the "admin" user display picture, compare to the "Member Roles" area in "Edit cluster". 
The icons are identical
<img width="595" alt="Screen Shot 2019-11-05 at 4 16 26 PM" src="https://user-images.githubusercontent.com/18536626/68257310-af97cc00-ffe7-11e9-9310-0ea2914c8df7.png">

<img width="523" alt="Screen Shot 2019-11-05 at 4 16 41 PM" src="https://user-images.githubusercontent.com/18536626/68257315-b3c3e980-ffe7-11e9-9180-80b9d6b1ea23.png">

Scenario 2:

"Add Member" from "Add Cluster" section and "Add Member" from "Edit Cluster" section are identical
<img width="1296" alt="Screen Shot 2019-11-05 at 4 19 19 PM" src="https://user-images.githubusercontent.com/18536626/68257435-1b7a3480-ffe8-11e9-829d-5c9b55b5f64c.png">

<img width="1328" alt="Screen Shot 2019-11-05 at 4 19 46 PM" src="https://user-images.githubusercontent.com/18536626/68257437-1f0dbb80-ffe8-11e9-93d4-df3bed394a81.png">
