### ISSUE TITLE
Cluster update is not triggered when cluster revision is changed by editing cluster in the API

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21454]
Version: Master-head

Using API:

1. Create a cluster template T1 and revisions R1, R2 from the same template
R1 with k8s version v1.12.9-rancher1-1 provided in the question
R2 with k8s version v1.13.7-rancher1-1 provided in the question as default value.(R2 is added thru add new revision in UI)
2. Create cluster with revision R1 and wait for the cluster to become active
3. Edit the cluster and change the revision to R2 through the API and provide the answer "v1.13.7-rancher1-1"

Changing template revision should trigger a cluster update to reflect the new k8s version.
Applied spec still has v1.12.9-rancher1-1 

```
answers": {
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"rancherKubernetesEngineConfig.kubernetesVersion": "v1.13.7-rancher1-1",
"rancherKubernetesEngineConfig.services.etcd.backupConfig.intervalHours": "5",
"rancherKubernetesEngineConfig.services.etcd.backupConfig.retention": "2"
}
},
"apiEndpoint": "https://209.97.149.113:6443",
"appliedEnableNetworkPolicy": false,
"appliedPodSecurityPolicyTemplateId": "",
"appliedSpec": {
"answers": {
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"rancherKubernetesEngineConfig.kubernetesVersion": "v1.12.9-rancher1-1",
"rancherKubernetesEngineConfig.services.etcd.backupConfig.intervalHours": "5",
"rancherKubernetesEngineConfig.services.etcd.backupConfig.retention": "2"
}
},



```

**Comment by prachidamle** [comment]
On a new setup, this usecase works and triggered cluster update. 

Seems like on the previous setup potentially the controllers on cluster update are not getting invoked.

**Comment by soumyalj** [comment]
Tested on another setup with master-build. 
The use case above is functional. Other use cases w.r.t editing a cluster created using templates are also functional.
