### ISSUE TITLE
Backport: Altering - cluster-altering app get auto-upgraded in only one cluster after upgrading Rancher

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21458]
https://github.com/rancher/rancher/issues/21455

**Comment by jiaqiluo** [comment]
The bug fix is validated in the upgrade path 
- from v2.2.3 to v2.2.5-rc13
- from v2.2.4 to v2.2.5-rc13

Did the same steps and tests in the original issue, and saw all ` cluster-alerting` and `rancher-logging` apps get upgraded automatically.

However, in one cluster, ` cluster-alerting` is stuck in upgrading; in another cluster, `rancher-logging` is stuck in upgrading, too.  This is tracked here: https://github.com/rancher/rancher/issues/21480
