### ISSUE TITLE
Altering - cluster-altering app get auto-upgraded in only one cluster after upgrading Rancher

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#21455]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:v2.2.3 container 
- as admin, enable Github auth
- log in as Github user user1
- add 4 EC2 single-node clusters, and configure them:
  - only-alerting
  - only-alerting
  - only-logging
  - both-logging-alerting
- upgrade Rancher to v2.2-head 8268cd5f

**Result:**
- There are the `cluster-alerting` apps in each cluster, totally 4, but only one of them get upgraded to `v0.0.3` automatically, and the rest show `Upgrade available (0.0.3 )` and need to upgrade manually
- There are two `rancher-logging` apps in two clusters totally, and none of them get upgraded to `v0.1.1` automatically, and both show `Upgrade available (0.1.1 )` and need to upgrade manually
![screenshot](https://user-images.githubusercontent.com/6218999/61013228-b1ea6200-a336-11e9-9581-be111797ac1e.png)

**Comment by jiaqiluo** [comment]
Wait for this issue to be merged then test both of them at the same time
https://github.com/rancher/rancher/issues/21449

**Comment by loganhz** [comment]
Please wait for https://github.com/rancher/rancher/pull/21450 merged

**Comment by jiaqiluo** [comment]
The bug fix is validated in the upgrade path from v2.2.3 to master-head

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:v2.2.3 container 
- as admin, enable Github auth
- log in as Github user user1
- add 4 EC2 single-node clusters, and configure them:
  - only-alerting
  - only-alerting
  - only-logging
  - both-logging-alerting
- upgrade Rancher to master-head e65f73a9

Results:
- `cluster-alerting` and `rancher-logging` apps upgrade to the latest versions automatically after upgrading Rancher.

- the `unable to handle the request error`  still exists and has been tracked here:
https://github.com/rancher/rancher/issues/21480
