### ISSUE TITLE
How to avoid pod of one workload sheduling on one node

### ISSUE THREAD

**Issue by artemus717** [rancher/rancher#21464]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
How to do this with rancher 2.x

![image](https://user-images.githubusercontent.com/16465173/61024916-a2742300-a3e1-11e9-8643-89037aa60912.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher 2.2.4 single install 

**Cluster information**
- Cluster type (Hosted):
- Machine type (cloud) and specifications (4c/8g):
- Kubernetes version (use `kubectl version`):

```


- Docker version (use `docker version`):
17.06-ce
```
(paste the output here)
```

**Comment by loganhz** [comment]
Please see https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
