### ISSUE TITLE
Workload node scheduling UI breaks when it is partially set

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#21462]
Rancher version:
v2.2.4 or master 07/10

**Steps to reproduce (least amount of steps as possible):**
1. Go to the default project
2. Deploy an nginx deployment named test, expand `Node Scheduling` tab, click `Show advanced options`, click `Add toleration`, input `abc` as label key, choose `Exists` operator.
3. Click `Launch` to deploy the workload.
4. Edit the test workload.
5. Expand `Node Scheduling` tab, choose `Run all pods for this workload on a specific node`

**Result**
1. Both the radio options are selected in the UI
2. See JS error in the console
3. Can edit node selector rules in the UI but they are not persisted when Saved.
![image](https://user-images.githubusercontent.com/5697937/61020967-232b2300-a3d2-11e9-9b32-864ceb3a1ec9.png)

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.4

I successfully reproduced, carefully following the steps above in the issue description:
![image](https://user-images.githubusercontent.com/45179589/62392665-e5c33c80-b51c-11e9-9c35-733f6a229d98.png)
![image](https://user-images.githubusercontent.com/45179589/62392693-f5db1c00-b51c-11e9-88f4-23beefd128e2.png)

**Validation:**
master-head (8/2/19)

I followed the same steps. now when I edit my changes appear correct and I don't get any JS errors. My changes take effect now. HTTP/API look good.
![image](https://user-images.githubusercontent.com/45179589/62392827-50747800-b51d-11e9-96dd-095bbe8c3188.png)

Notice picking "Run all pods for this workload on a specific node" now works
Tested and ensured this worked correctly.
