### ISSUE TITLE
Registry Configuration

### ISSUE THREAD

**Issue by artemus717** [rancher/rancher#21466]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1.Add a workload using custom registry
2.Add registry the workload used

**Result:**
The workload is still pulling . Can not recover by itself. 

![image](https://user-images.githubusercontent.com/16465173/61029675-26340c80-a3ee-11e9-85b5-2504fa8e67e5.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher:v2.2.4`:
- Installation option (single install):

**Cluster information**
- Cluster type (Hosted):
- Machine type (cloud and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
17.06-ce
```
(paste the output here)
```

**Comment by loganhz** [comment]
Please add the registry first and deploy the workload after that
