### ISSUE TITLE
Support selected version when we enable monitoring

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21460]
rancher/rancher:v2.2.4

Now monitoring version is hard coded in rancher server code.
UI should pass the monitoring version to the backend.

**Comment by orangedeng** [comment]
The major concern is that the answers of the monitoring app is coded in Rancher. So there is a chance that the old version monitoring answer will apply to the new monitoring app. It is hard to ensure the compatibility between old answer and new app.

**Comment by loganhz** [comment]
When you enable monitoring, UI will only allow users to enable the latest version.

**Comment by jiaqiluo** [comment]
In both v2.2.6 and master-head, when enabling the cluster/project monitoring, there is no value of version in the answers in the API request.
![Screen Shot 2019-07-31 at 5 09 29 PM](https://user-images.githubusercontent.com/6218999/62256415-0624b700-b3b6-11e9-81b8-f47eed9650f7.png)

**Comment by loganhz** [comment]
This is by design in master-head. If you keep the version field empty, it will use the latest one. As we only allow users to enable the latest one, so it is expected.

The problem before is the version is hard code in rancher/rancher code.

**Comment by jiaqiluo** [comment]
with master-head, the API call does not send the version when enabling the monitoring, UI shows the latest version but the version is not used in the API call. 

Currently, the latest system chart(v0.0.4) is severed which is not depended on the Rancher version. How do we handle the case when a newer version of monitoring chart(say v0.0.5) is made available for a newer version of Rancher server, but we do not want this v0.0.5 version of the chart made available to older Rancher version? 

We need to make the system chart support min/max Rancher versions in this case.

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:master-head bc3700f8 with the latest UI file.
By default, the UI index is `https://releases.rancher.com/ui/latest2/index.html` 

Steps:
- add a DO cluster
- enable the cluster monitoring and track the network
- enable the project monitoring and track the network

Result:
- the cluster monitoring's chart version is sent out in the API call
<img width="901" alt="Screen Shot 2019-08-07 at 10 25 56 AM" src="https://user-images.githubusercontent.com/6218999/62643941-edf4f080-b8fd-11e9-94ca-92ebf4f8ea27.png">

- the project monitoring's chart version is sent out in the API call
<img width="910" alt="Screen Shot 2019-08-07 at 10 24 52 AM" src="https://user-images.githubusercontent.com/6218999/62643961-f64d2b80-b8fd-11e9-951b-e2f3e92484f2.png">
