### ISSUE TITLE
Fix k8s 1.14 - > k8s 1.15 upgrades for CNI addons

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#21475]
**What kind of request is this (question/bug/enhancement/feature request):**
task

**Steps to reproduce (least amount of steps as possible):**
- Fix flannel template to match labels on DaemonSet
- Update Calico to 3.7.4
- Move static kube-controllers image to rancher namespace
- Assign default image for kube-controller in RKE
- Use IPAM migration for backend

**Comment by alena1108** [comment]
The current decision is to upgrade addons for k8s 1.15 - the default k8s version in 2.3. @sangeethah lets test the issue in this context.

**Comment by sangeethah** [comment]
Scenario 1:
Create a cluster with network provider set to calico using K8s version - v1.15.0-rancher1-2.
Calico version v3.7.4 gets deployed.

Scenario 2:
Create a cluster with network provider set to calico using K8s version - v1.14.4-rancher1-1.

<img width="1055" alt="Screen Shot 2019-07-30 at 7 13 59 PM" src="https://user-images.githubusercontent.com/4266958/62179184-77099780-b300-11e9-851e-59340ef10095.png">

Upgrade cluster to k8s version - v1.15.0-rancher1-2.
Calico version gets upgraded to v3.7.4 as expected.
