### ISSUE TITLE
Add helper text when creating EKS clusters

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#21472]
Rancher supports adding an SSH key to the EKS cluster while provisioning it, so the user can ssh into the nodes hosted in AWS EC2. But it requires users to edit the security group's inbound rules to enable the port 22.  
Since the port 22 is not exposed by default for security, and also the passing-SSH-Key feature is optional, so it is better to keep the port 22 closed but we can add some helper text in the UI to inform users that they need to open the port by themselves.

![61074974-d6dde400-a3cd-11e9-9fa4-b10ac4da59b8](https://user-images.githubusercontent.com/6218999/61076282-b6635900-a3d0-11e9-9107-5c2ddacff09b.png)

**Comment by tfiduccia** [comment]
@lvuch - Think we can add ? icon with text next to the ssh field.

**Comment by tfiduccia** [comment]
Add ? bubble icon next to the SSH key field.  Say "You may need to edit the security group's inbound rules to enable the port 22."

**Comment by tfiduccia** [comment]
Version - Master 8/13
Verified fixed
![image](https://user-images.githubusercontent.com/11514927/62965234-6f92c580-bdb9-11e9-9c42-818f02c48a67.png)
