### ISSUE TITLE
Confusing UI if host goes down and service was inactive, but service had restart:always

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2147]
http://forums.rancher.com/t/disabled-stack-on-reboot/463/2

Steps to Reproduce:
1. Create and start a service with restart always (default rancher setting)
2. Stop the service so that it's inactive and containers are stopped
3. Reboot the host

Result: UI will show an inactive service with running containers (due to the restart: always) policy that is set on the containers.

Not sure what the expected result should be, but it's mostly a weird user experience to see an inactive service.

**Comment by vincent99** [comment]
Not UI?  Those are the states things are in :smile:

**Comment by deniseschannon** [comment]
@vincent99 true... it's just confusing. :)

**Comment by vincent99** [comment]
This is the same as https://github.com/rancher/rancher/issues/1827..
