### ISSUE TITLE
[UI] Cluster Templates - Not allowed to edit cluster as an added cluster owner (who does not have access to  cluster template)

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21473]
Rancher server version - Build from master - `622f66e4`

Steps to reproduce the problem:
Create a cluster with template revision - R1 which has K8s version as a question.
Create a user - `test1` and assign this user as cluster owner to this cluster.
Log in as `test1` and try to edit the cluster.
User is brought back to the log in page.

Following list calls made to clusterTemplate and clusterTemplateRevision fails with `403` error:
<img width="1308" alt="Screen Shot 2019-07-11 at 12 33 47 PM" src="https://user-images.githubusercontent.com/4266958/61079742-4f49a280-a3d8-11e9-9636-275c91ff0d8e.png">

```
{baseType: "error", code: "Forbidden",…}
baseType: "error"
code: "Forbidden"
message: "clustertemplaterevisions.management.cattle.io "revision-iaoeisuo" is forbidden: User "u-9wzjq" cannot get resource "clustertemplaterevisions" in API group "management.cattle.io" in the namespace "cattle-global-data""
status: 403
type: "error"
```

```
{baseType: "error", code: "Forbidden",…}
baseType: "error"
code: "Forbidden"
message: "clustertemplates.management.cattle.io "ct-m75z4" is forbidden: User "u-9wzjq" cannot get resource "clustertemplates" in API group "management.cattle.io" in the namespace "cattle-global-data""
status: 403
type: "error"
```

**Comment by prachidamle** [comment]
To be able to edit cluster that is created via template, the user that has been granted the cluster access should also have permissions to the clustertemplate. The original cluster-owner should be explicitly granting atleast a "read-only" permissions on the clustertemplate to the other user.

**Comment by prachidamle** [comment]
For UI to be able to let the added cluster owner edit the cluster and change answers even if he/she does not have access to the template: Backend will be storing the Questions[] from the templateRevision on the clusterSpec.

**Comment by prachidamle** [comment]
@westlywright / @vincent99 assigning for UI changes - TemplateRevision Questions[] are now saved on Cluster spec by API- this is for the case where cluster-owner cannot see the template

**Comment by alena1108** [comment]
Per offline with @westlywright and @vincent99 , minimum we should do is we to allow cluster edits w/o actual templates update. That is to support the case of changing answers to the questions. In order to  support it, we have to:

- [x] Store questions as the cluster field - backend changes
- [ ] In UI, on template edit do the permission check for the corresponding template object. If you get an Unauthorized error, pull the questions from the cluster questions field - UI changes

**Comment by davidnuzik** [comment]
Version: master-head (8/8/19)

This is now working.

- Create a cluster with template revision - R1 which has K8s version as a question.
- Create a user - test1 and assign this user as cluster owner to this cluster.
- Log in as test1 and try to edit the cluster.

"test1" user is now allowed to edit the cluster and has access to the template so they can edit it.
We do run into a SEPARATE issue now though. Reference https://github.com/rancher/rancher/issues/12038#issuecomment-519661876 for this.
