### ISSUE TITLE
Bug: Option to set desired ASG in Amazon EKS cluster creation

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#21481]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Create a new EKS cluster
2) When asked about minimum and maximum ASG, set min to 1 and max to 2
3) finish configuring and then create cluster

**Result:**
Creation fails with the following error:
```
Desired capacity:3 must be between the specified min size:1 and max size:2 (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 2de277e5-a3e7-11e9-855c-ab8345c3a63c)
```

**Other details that may be helpful:**
Having the ability to set the desired ASG in the UI would resolve this issue.  Currently it appears to be hard coded to 3.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/18243
