### ISSUE TITLE
List driver options with logical order instead of alphabetical order

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2148]
```
Component 	Version
Rancher 	v0.39.0-rc1
Cattle 	v0.95.0
User Interface 	v0.52.0
Rancher Compose 	beta/latest

```
Makes sense to list password immediately after username. Also, list mandatory options first followed by optional fields. This applies to all the supported drivers.

<img width="688" alt="screen shot 2015-09-25 at 11 31 57 am" src="https://cloud.githubusercontent.com/assets/7720752/10109030/48794b34-6379-11e5-96bf-c5bd49a930b1.png">

**Comment by vincent99** [comment]
The point of the generic support / other option is to support any driver by just reading their options and presenting them.  There is no order to the parameters in the API, nor provided by docker-machine itself, so this would be someone manually determining what a logical order is.

**Comment by aruneli** [comment]
Is it possible to hardcode username/password for now?

**Comment by aruneli** [comment]
Closing this for now. Let us re-visit if external users are not comfortable with this approach.
