### ISSUE TITLE
Upgrade Istio to latest version 1.2.x before 2.3 out

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21487]
Upgrade Istio to latest version 1.2.x before 2.3 out

**Comment by deniseschannon** [comment]
@loganhz 1.2.4 has been released. can we update to that version for now?

**Comment by loganhz** [comment]
Do we need to upgrade again if 1.2.5 or 1.2.6 out before 2.3.0 out? Maybe we should upgrade to 1.2.4 first and think about it later? @deniseschannon 

cc @sangeethah  @bmdepesa @davidnuzik

**Comment by deniseschannon** [comment]
Yes, if they release a new version, we'll need to upgrade again, but first let's upgrade to 1.2.4 as that is the latest (released this past week).

**Comment by sangeethah** [comment]
@bmdepesa As part of validating the latest version of Istio ,  please validate tolerations available for  Istio workloads workloads also work as expected.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 57508ebba

* Deploy master-head
* Create cluster
  * Create a dedicated worker nodepool for istio nodes
    * add a taint with NoExecute to the nodepool
    * add a label for these nodes
  * Create another worker nodepool with no taints
* Enable istio
  * Add a label selector to only run the labeled istio nodes
  * Add a toleration to each of the istio components to match the taint on the istio worker nodes
* Istio is enabled successfully
* Check the istio pods in the System project and see they are running on the specified nodes
* Create some workloads 
  * These workloads are only deployed on the unlabeled/tainted nodes
* Basic istio validations pass

Still executing through the Istio test plan, will update with the final results.

**Comment by bmdepesa** [comment]
Completed execution of test plan, no outstanding issues.
