### ISSUE TITLE
授权集群访问地址功能

### ISSUE THREAD

**Issue by WJXZ** [rancher/rancher#21493]
*Describe your issue here*
启动配置好之后，用kubectl --context ha-fqdn cluster-info dump命令
Unable to connect to the server: x509: certificate is valid for localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not *.*.com
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.cluster.monitoring.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or you can find us by searching `rancher2` via wechat
