### ISSUE TITLE
K8s 1.14 (and k8s 1.15) with calico network mode - Cluster is not able to recover successfully after restoring from backup. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21490]
Rancher server version - v2.2.5-14

Steps to reproduce the problem:
Create a K8s 1.15 cluster with Flannel network mode and following configurations:
1 control plane node
3 etcd nodes
3 workers

Wait for the cluster to get to `active` state.

Execute`test_bkp_restore` test -https://github.com/rancher/rancher/blob/master/tests/validation/tests/v3_api/test_bkp_restore.py
 
```
 1. Create workloads
 2. Perform Backup
 3.Create workload after backup
 4. Perform Restore
```
All control and etcd nodes gets to `Unavailable` state after cluster is restored with following error message:

`Runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
--`

Calico-node is not able to start on etcd and control nodes.

<img width="1244" alt="Screen Shot 2019-07-11 at 10 46 43 PM" src="https://user-images.githubusercontent.com/4266958/61105134-da08bc80-a42d-11e9-9b13-ae412f151fe9.png">

<img width="986" alt="Screen Shot 2019-07-11 at 10 46 32 PM" src="https://user-images.githubusercontent.com/4266958/61105186-fad11200-a42d-11e9-8000-20a5af418cff.png">

**Comment by superseb** [comment]
Recreating the calico-node pods should make the nodes go in Ready state. You can delete them manually in the UI or delete them all via the CLI:

```
kubectl -n kube-system delete pods -l k8s-app=calico-node
```

Possibly related: https://github.com/projectcalico/calico/issues/2370

**Comment by sangeethah** [comment]
Confirmed that following the steps - https://github.com/rancher/rancher/issues/21490#issuecomment-510979333 gets the clusters to good state.

**Comment by sowmyav27** [comment]
**verified with `master-head` - commit id: `0afa73cbd`**
Steps:
- Create a K8s 1.15 cluster with Flannel network mode and following configurations:
1 control plane node
3 etcd nodes
3 workers
- Wait for the cluster to get to active state.
- Execute the below steps:
```
 1. Create workloads
 2. Perform Backup
 3.Create workload after backup
 4. Perform Restore
```
Cluster is seen in Active state.
All nodes are `Active`.
