### ISSUE TITLE
Enable cluster monitoring when prometheus is already installed

### ISSUE THREAD

**Issue by phillycheeze** [rancher/rancher#21499]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Details**
When a cluster is imported into Rancher and the cluster is already configured to work with prometheus, is it posslbe for Rancher to detect and pull data from the prometheus operator already in the cluster?

Currently, Rancher does not detect prometheus and shows the form to install cluster monitoring. I haven't actually tried to install it via the Rancher web UI since I assume this would cause some issues.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): Single

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17370
