### ISSUE TITLE
BUG- Container running in Rancher is showing 1 CPU only, where actually 8

### ISSUE THREAD

**Issue by mohammad-shah-alam** [rancher/rancher#21497]
**BUG**
Rancher created container is showing 1 CPU only where actually there are 8.

I have a Elastic search setup on rancher. When i run elastic search using plain docker command it shows 8 actual/available processor but in the container created by rancher shows 1 actual/available processors only.

Just FYI similar issue created before for v1.6 https://github.com/rancher/rancher/issues/15599

**Details** 
rancher/rancher:v2.2.4
----- Docker Info -------
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.41 GiB
Server Version: 18.09.7
---- Elastic search version -----
Tried 7.1.1 7.2.0
docker.elastic.co/elasticsearch/elasticsearch:7.1.1

**Steps to reproduce (least amount of steps as possible):**
Run container without rancher

- docker run -dit -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" 98.8.61.7:5000/docker.elastic.co/elasticsearch/elasticsearch:7.1.1

- fe37a6b4bc3e07efd949e3ba258e80af95a90f3ad31ec9dce835b717090edd56

- docker exec -it fe37a6b4bc3e07efd949e3ba258e80af95a90f3ad31ec9dce835b717090edd56 /bin/bash

- ./jdk/bin/jshell 
- Jul 12, 2019 4:05:28 PM java.util.prefs.FileSystemPreferences$1 run
- INFO: Created user preferences directory.
- |  Welcome to JShell -- Version 12.0.1
- |  For an introduction type: /help intro
- 
- jshell> Runtime.getRuntime().availableProcessors()
- $1 ==> 8    // Shows 8 processors which looks good.

GET call to http://localhost:9200/_nodes returns correct processor count

"os": {
"refresh_interval_in_millis": 1000,
"name": "Linux",
"pretty_name": "CentOS Linux 7 (Core)",
"arch": "amd64",
"version": "3.10.0-862.11.6.el7.x86_64",
"available_processors": 8,
"allocated_processors": 8
},

------- Running the container using rancher -----
docker exec -it 2ddce3e05600 /bin/bash

I ran a container using rancher and logged in 

./jdk/bin/jshell
Jul 12, 2019 4:10:33 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 12.0.1
|  For an introduction type: /help intro

jshell> Runtime.getRuntime().availableProcessors()
$1 ==> 1  shows incorrect value.

**Result:**
Since Elastic does a lot of auto configuration based on the processor count its impacting the capability of the cluster.

**Other details that may be helpful:**

**Environment information**

- Installation option HA

**Cluster information**
- Cluster type (Custom):
- Machine type (VM) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
Stepping:              1
CPU MHz:               2394.455
BogoMIPS:              4788.91
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-7

**Comment by mohammad-shah-alam** [comment]
Can some one confirm if this issue is noticed or need more details?

**Comment by Hitesh-Agrawal** [comment]
Seeing same issue in rancher 2.3.3 . The cpushare is set to 2 by rancher .Can we get this fixed.

**Comment by inewlife** [comment]
+1
