### ISSUE TITLE
Creating a cluster with "flannel" network plugin does not display "windows support" option

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21504]
Version: Master-head

Steps
1. Create a cluster with flannel network plugin option without using a template
Windows support option is not displayed . 

![Screen Shot 2019-07-12 at 1.04.19 PM.png](https://zube.io/files/rancher/c22fc1e037d2d1cd42cf2040835eb609-screen-shot-2019-07-12-at-1-04-19-pm.png)

Note: When you create a cluster template with flannel plugin, "windows support "option is displayed as below:
![Screen Shot 2019-07-12 at 1.12.35 PM.png](https://zube.io/files/rancher/6464d3493e857b4560b1b283ec9b5823-screen-shot-2019-07-12-at-1-12-35-pm.png)

**Comment by sangeethah** [comment]
Windows option will be presented  only for custom cluster.
