### ISSUE TITLE
Remove the term "CLI" from the error message in generic driver host add failure. 

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2150]
```
Component 	Version
Rancher 	v0.39.0-rc1
Cattle 	v0.95.0
User Interface 	v0.52.0
Rancher Compose 	beta/latest
```
This is not major issue. But it would be good not to confuse with "CLI" word here.

<img width="295" alt="screen shot 2015-09-25 at 11 39 26 am" src="https://cloud.githubusercontent.com/assets/7720752/10109190/665268ba-637a-11e5-9d8e-a1dd6c0ce5e6.png">

**Comment by deniseschannon** [comment]
I believe all error messages come through machine. And a lot of them come directly from docker-machine, but @wlan0 would need to confirm.

**Comment by vincent99** [comment]
Yes, this text is direct from docker-machine

**Comment by wlan0** [comment]
Yes, this is from docker-machine

**Comment by deniseschannon** [comment]
since this text is from docker-machine and Rancher has no control over it, I'm closing the issue.
