### ISSUE TITLE
Redesign Node Pool Section on Cluster Launch

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#21508]
With the new `DeleteNotReadyAfterSecs` property being exposed on the node pool model we need to reconsider the UX of node pool rows. Currently we are only adding one param but more self healing node pool options are incoming and we're loosing room. Additionally the new `DeleteNotReadyAfterSecs` is hard to represent in a label and requires a tooltip around the input to provide further context. If we rework this section to remove the table style and build a form driven section we can have labels and help-text to provide context as we do everywhere else. 

The new section should function the same way; Add action adds new section for a new node pool and remove action removes the section. The display of the section should be more form driven, similar to how the options for the other sections are laid out. 

**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Navigate to the launch page for an IAS Cluster Provider (anything with node pools will suffice)

**Result:**
Notice there is a new field, `Recreate Unreachable After`, in the individual node pool row.

**Other details that may be helpful:**
related to rancher/rancher#20862 & rancher/ui#3129

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher master after 9-12-19
- Installation option (single install/HA): Single

**Comment by tfiduccia** [comment]
@lvuch, @vincent99 & @tfiduccia will be working on this.  We will get a wireframe and go from there.

**Comment by lvuch** [comment]
updated form section:
<img width="850" alt="Screen Shot 2019-08-07 at 12 37 37 PM" src="https://user-images.githubusercontent.com/3013118/62652543-7c726d80-b910-11e9-90a9-41d13fb6b310.png">

**Comment by vincent99** [comment]
The 1/3/5 and ≥1 don't really make sense here.  They apply to the entire cluster/sum of the node pools, not an individual pool.

**Comment by tfiduccia** [comment]
@lvuch  - So the Number of nodes required can't be in each "node pool" section.  So we need a new footer that will go on the bottom of all the nodes pools that have this information:
Number of nodes required fo reach role, how many they have, and if they have enough.  Kind of like we have currently but way better.
![image](https://user-images.githubusercontent.com/11514927/62985547-af26d500-bdec-11e9-8928-9cfc9538f1c2.png)

**Comment by lvuch** [comment]
<img width="838" alt="Screen Shot 2019-08-14 at 1 07 12 PM" src="https://user-images.githubusercontent.com/3013118/63052570-7d694900-be94-11e9-9641-f32b933baa7c.png">

**Comment by vincent99** [comment]
Still needs an icon or something, I have no idea which one of those is the good state and which is bad.

**Comment by tfiduccia** [comment]
@vincent99 - They are red and green accordingly to the good/bad state so it's obvious like it was before.

**Comment by lvuch** [comment]
icons added: https://xd.adobe.com/view/acf2dd2b-16e0-4a38-4c78-21e443f090ec-dac3/

**Comment by tfiduccia** [comment]
Closing in favor of #23313.
