### ISSUE TITLE
Annotations in secrets and configmap

### ISSUE THREAD

**Issue by Leen15** [rancher/rancher#21513]
Hi, Is there a way to add annotations in secrets?
I'm configuring drone.io with k8s secrets and it asks to add annotations for every secret:
https://docs.drone.io/extend/secrets/kubernetes/config-in-kubernetes/

But there is no way to add annotations in rancher UI while adding a secret or a configmap:
![image](https://user-images.githubusercontent.com/3629071/61169178-29e4a200-a55a-11e9-9172-0e0e71c69de6.png)

I'm using Rancher HA v.2.2.4.
Thanks

**Comment by soumyalj** [comment]
Observed in v2.3.3 that secrets and config maps do not have option to set labels and annotations.
Tested with master build
Option to add labels to secret and configmap is available.
1. Created a config map along with providing labels and annotations. Config map got created successfully . Used the configmap in a workload as a volume.
```
> kubectl describe configmap testconfig
Name:         testconfig
Namespace:    default
Labels:       cattle.io/creator=norman
              label2=labelvalue2
              label3=labelvalue3
Annotations:  anno1: annovalue1
              field.cattle.io/creatorId: user-9vtvj

Data
====
key:
----
valu
Events:  <none>

```

2. Created a secret along with adding labels and annotations . Secret got created successfully. 
Used the secret in a workload . kubectl displays the annotations as expected but the labels are not displayed.
```
> kubectl get secret
NAME                  TYPE                                  DATA   AGE
default-token-x5vff   kubernetes.io/service-account-token   3      2d23h
newsecret             Opaque                                1      50s
test                  Opaque                                1      135m
> kubectl describe secret newsecret
Name:         newsecret
Namespace:    default
Labels:       <none>
Annotations:  field.cattle.io/creatorId: user-9vtvj
              field.cattle.io/projectId: c-7s9cd:p-mnmdz
              lifecycle.cattle.io/create.secretsController_c-7s9cd: true
              neanno: valueanno
              secret.user.cattle.io/secret: true

Type:  Opaque

Data
====
newkey:  8 bytes


```
