### ISSUE TITLE
Ceph RBD not creating needed configuration files

### ISSUE THREAD

**Issue by Raboo** [rancher/rancher#21516]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Add Ceph RBD storage class to your local rancher cluster(i.e. not workloads cluster).
Enable monitoring with Persistent Volume.

**Result:**
The Persistent Volume Claims complain.
Type: Warning
Reason: ProvisioningFailed
Message:

>(combined from similar events): Failed to provision volume with StorageClass "ceph-hdd": failed to create rbd image: exit status 1, command output: 2019-07-14 09:56:37.061822 7fce277c1100 -1 did not load config file, using default settings. 2019-07-14 09:56:37.073879 7fce277c1100 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.rancher.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory rbd: create error: (1) Operation not permitted 2019-07-14 09:56:37.083930 7fce277c1100 -1 librbd: Could not tell if kubernetes-dynamic-pvc-ab594aab-a61d-11e9-9f8e-0200ec7e0767 already exists 

So it appears it's looking for */etc/ceph/ceph.client.rancher.keyring* which I assume would have been generated by the secret when adding Ceph RBD as a storage class?

**Other details that may be helpful:**
Rancher running on Ubuntu 18.04 (Bioinic)
Got Ceph RBD to work on the workload cluster by modifying extra_binds for kubelet (#21189).

**Environment information**
- Rancher version: 2.2.4
- Installation option: HA
- Docker version: 18.09.5

**Comment by JasonGantner** [comment]
Still relevant for Rancher 2.3.3 with Docker 19.03.5 on Debian 10

**Comment by Raboo** [comment]
Okey, I actually got it to work. To bad documentation is non-existent.
I suspect that error message I got above might be a fallback, so when it fails it goes looking for keyring on disk as a fallback.

Here is how I did it, don't forget to adjust the commands for your environment, i.e. don't just copy-paste.

I add this to my cluster.yml file for rke and setup/update rancher cluster. Similar to https://github.com/rancher/rancher/issues/21189

```yaml
services:
  kubelet:
    extra_binds:
      - '/lib/modules:/lib/modules:ro'
      - '/usr/sbin/modprobe:/usr/sbin/modprobe:ro'
```

### Create Ceph pools for rancher cluster

Example 

```bash
ceph osd pool create rancher_hdd 64 64 replicated replicated_hdd
ceph osd pool application enable rancher_hdd rbd
ceph auth get-or-create client.rancher mon 'allow r, allow command "osd blacklist"' osd 'allow class-read object_prefix rbd_children, allow rwx pool=rancher_hdd'
# [client.rancher]
#   key = XXXXXX==
```

### add storage class in rancher/kubernetes

First create api key in the UI under your account -> API & Keys.  
Export these:

```bash
export ENDPOINT='https://rancher.deltaprojects.io/v3'
export CATTLE_ACCESS_KEY='token-xxx'
export CATTLE_SECRET_KEY='xxx'
export BEARER_TOKEN='token-xxx:xxx'
```

##### add ceph client key to kubernetes secrets

```bash
kubectl create secret generic ceph-rancher-secret --type="kubernetes.io/rbd" \
  --from-literal=key='XXXXX==' \
  --namespace=kube-system
```

##### Create storage class in kubernetes

```bash
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"allowVolumeExpansion":true, "allowedTopologies":[], "annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true", "storageclass.kubernetes.io/is-default-class":"true"}, "labels":{"cattle.io/creator":"norman"}, "mountOptions":[], "name":"ceph-hdd", "parameters":{"adminId":"rancher", "adminSecretName":"ceph-rancher-secret", "adminSecretNamespace":"kube-system", "fsType":"ext4", "imageFeatures":"layering", "imageFormat":"2", "monitors":"mon01:6789, mon02:6789, mon03:6789", "pool":"rancher_hdd", "userId":"rancher", "userSecretName":"ceph-rancher-secret", "userSecretNamespace":"kube-system"}, "provisioner":"kubernetes.io/rbd", "reclaimPolicy":"Delete", "volumeBindingMode":"Immediate"}' \
'https://rancher.deltaprojects.io/v3/clusters/local/storageclasses'
```

Even that I got this to work, I'm leaving this issue open since instructions needs to be added to documentation.
