### ISSUE TITLE
More details for imported cluster

### ISSUE THREAD

**Issue by dawidmalina** [rancher/rancher#21515]
**What kind of request is this (question/bug/enhancement/feature request):** 
Is it possible to once again view (find) link to manifest containing all agent object definitions for imported cluster?

Sorry it this was already answered (I couldn't find the answer).

**Steps to reproduce (least amount of steps as possible):**
1. Create new cluster type imported.
2. Special page will be displayed with proper links like this
```
kubectl apply -f https://rancher.xxxxxx/v3/import/wcdrfv8x5j88cgzwc4zfzq5spgl98xmvpgk682wc6gc86rj5kgj7bt.yaml
```
3. Cluster is bootstrapped

**Other details that may be helpful:**
It would be nice if this link or page with same details can be displayed from cluster details section.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA):
HA

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/12667
