### ISSUE TITLE
none-admin user can't see grafana link of workload, pod

### ISSUE THREAD

**Issue by zhongguanqun** [rancher/rancher#21517]
*Describe your issue here*

not privileged user see those，as：

![屏幕快照 2019-07-15 上午11 03 43](https://user-images.githubusercontent.com/4767546/61193856-92fe1e00-a6f0-11e9-9ddc-dac423e63eff.png)
![屏幕快照 2019-07-15 上午11 03 51](https://user-images.githubusercontent.com/4767546/61193861-972a3b80-a6f0-11e9-8224-0e12d648a339.png)

admin user see those, as:

<img width="1194" alt="屏幕快照 2019-07-15 上午11 08 16" src="https://user-images.githubusercontent.com/4767546/61193919-dd7f9a80-a6f0-11e9-92d3-3650d01ed3ee.png">
<img width="1195" alt="屏幕快照 2019-07-15 上午11 08 22" src="https://user-images.githubusercontent.com/4767546/61193922-e1abb800-a6f0-11e9-86c3-897ecb3c06f7.png">

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`global-admin.accounts.index`|

**Comment by olivier-mauras** [comment]
Same here on 2.2.5

Rancher | v2.2.5
User Interface | v2.2.89

Stangely in my setup though, not all non-admin users have the issue....
Users are binded to a specific role - basically a copy of the "project member" role with namespace creation removed - and this role is used for all projects.

Some projects have this grafana issue some don't...

**Comment by doog33k** [comment]
same issue for me

**Comment by doog33k** [comment]
same issue here ;-)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24213
