### ISSUE TITLE
[api] Questions randomly appear/disappear when using Helm Repo as source

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#21529]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Add a helm repo with `tbz` files that have `questions.yml` in the file.
2. Navigate to the version of the template in the v3 api
3. Refresh the API and review the data.

**Result:**

The `questions.yml` will appear/disappear randomly from the files object in the API and the questions array correspondingly appears and disappears. 

**Other details that may be helpful:**

Semi-related - https://github.com/rancher/rancher/issues/20977

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): HA

**Comment by vincent99** [comment]
Questions are only supported in git repos for the cluster manager API/UI and that's not going to change at this point.  They work in Helm repos in Explorer.
