### ISSUE TITLE
Cluster must have at least one etcd plane host

### ISSUE THREAD

**Issue by azelezni** [rancher/rancher#21525]
My cluster is stuck with the following message `Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [10.121.2.59]`
• There are no network issues (I can reach rancher from worker cluster and vice versa)
• There are no SSL issues (all certificates are valid)
• kubeapi is full of error like `http: TLS handshake error from 10.121.4.90:44086: EOF`

If I tried to add a new master I just get an error `Failed to inspect [kube-apiserver] container on host [10.121.2.76]: Error: No such container: kube-apiserver` and `level=error msg="Failed to connect to proxy" error="websocket: bad handshake"`

**Comment by thiagosantosleite** [comment]
I have the same issue in k8s cluster 1.16.3 after update rancher to v2.4.5

any updates on this?
