### ISSUE TITLE
Azure AD authentication configuration fails

### ISSUE THREAD

**Issue by kurbar** [rancher/rancher#21522]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Configure Azure AD following the docs at https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad/
2. Try to authorize

**Result:**
Microsoft login popup window gives an error
```
AADSTS901002: The 'resource' request parameter is not supported.
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): single install

**Comment by dramich** [comment]
@kurbar When setting up azure and getting the endpoints for your application ensure you are getting v1 of the endpoints, not v2. So the url under `OAuth 2.0 token endpoint (v1)` and `OAuth 2.0 authorization endpoint (v1)`

**Comment by kurbar** [comment]
Indeed, after changing the endpoints to v1 and fiddling with the permissions on Azure AD side, the configuration succeeded and is working.
