### ISSUE TITLE
[UI] Configuring pipeline authentication failed

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#21520]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Using the `master-head ui` configuration pipeline, authentication failed.

The error is as follows: 
`Error (undefined - undefined)`

<img width="1316" alt="github" src="https://user-images.githubusercontent.com/42061003/61199927-580ce200-a712-11e9-9e09-f8733e4b8f05.png">

I changed the ui-index to version `2.2.89` , everything works fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
master-head (7/15/2019)
- Installation option (single install/HA): 
single install

**Comment by davidnuzik** [comment]
**Reproduction:**
master-head (7/26/19) ui-index `https://releases.rancher.com/ui/2.3.1/index.html`

I attempted to reproduce but was not successful. I tried changing to older v2.3.1 ui-index but this didn't work. This makes me think something likely broke recently but between v2.3.1 and current v2.3.2. 

**Validation:**
master-head (7/26/19) (latest2 ui-index; which is default, OOTB, latest, ui-index)

I was successfully able to authenticate with GitHub without any issues. I smoke tested and didn't run into any issues.
