### ISSUE TITLE
container status indicator improvement idea

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2152]
Ok, this is a little nit-picky, but when I set io.rancher.container.start_once: true on a container, it works fine but then the container is colored "red" in the UI after it exits. In my case, the stack is designed with a container that is supposed to come up, do some work, then exit. But marking it as "red" makes appear to have failed. Now, I'll admit that I'm not 100% certain that the container in question actually returned a 0 when it exited. So let me know if Rancher already has a policy for like the one below...
What I'd like to see is something like this, if a container has start_once set to true:
- if the container starts up and exits with "0", then it's color is blue even gray 
- if the container starts up and exits with - non-zero, mark it red, so I know to go check out the logs.
- if it doesn't start up properly, then also red
- while it's running, it should be green like the others.
Thoughts?

**Comment by Rucknar** [comment]
+1, with 0.43.1 it now shows as 'Degraded' and in orange colour.

**Comment by vincent99** [comment]
Added a fake 'started-once' state that shows up green with a different kind of circle for state=stopped & has the start_once label.

**Comment by tfiduccia** [comment]
Version - Master with reskin UI
Verified fixed
