### ISSUE TITLE
[UI] Azure nodeTemplate Managed disks

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#21533]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
go to provision an RKE cluster
select azure as the node provider
follow steps to provision

**Result:**
1. There is no option to choose managed or unmanaged disk.
2. There is no option to choose fault domain count.
3. There is no option to choose update domain count.

**Desired:** 
Options 2 and 3 should probably be found under the "Placement" section underneath availability set, with a note explaining that if the AS has already been created then the options will be ignored.

Option 1 should appear under instance.

**Notes:**
fault domain count cannot be greater than 3
diskSize must be between 1 and 32767 (inclusive)

**Backend Issue:**
https://github.com/rancher/rancher/issues/15788

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

In the UI, this makes some changes to the azure node template modal.
This adds a few areas as Ricky mentions in the issue description; below are screenshots for each (defaults pictured).

1. Option to choose managed or unmanaged disk.
![image](https://user-images.githubusercontent.com/45179589/62574838-3ce34d00-b84e-11e9-879f-fcc5c44d219d.png)
(This is under the "Instance" section)

2. Option to choose fault domain count.
![image](https://user-images.githubusercontent.com/45179589/62574857-4967a580-b84e-11e9-9bd9-8e73ce7b670f.png)
(This is under the "Placement" section)

3. Option to choose update domain count.
![image](https://user-images.githubusercontent.com/45179589/62574886-56849480-b84e-11e9-9103-2c7afa81765a.png)
(This is also under the "Placement" section)

For each, I ensured that when I created my nodepool, that the settings in the Azure web console match and that the HTTP request / API appear correct as well. (In Azure check Availability Set details and check Storage account details)

New fields (default values shown)
`faultDomainCount: "3"`
`updateDomainCount: "5"`
`managedDisks: false`

I tested and tweaked settings for each field (performing standard field testing as well with all manner of data input; only valid positive integers are allowed and zeros). 

Everything worked as expected. The only issue I found was that values as zeros are not accepted and so I created a separate issue to track this here: https://github.com/rancher/rancher/issues/22015
