### ISSUE TITLE
Full support for docker-compose commands?

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2153]
A fairly normal use case for our teams is to do something like the following, especially during development.

docker-compose up
docker-compose ps
get the name of one of the containers
docker exec -it thecontainer /bin/bash 

We do all of this from the linux command line.  Any thoughts on supporting docker-compose commands like "ps" in rancher-compose? 

And then what about an ability to get to a shell one of the containers - something like "rancher-compose exec <container_name>, then I can run a shell, or other commands.

**Comment by deniseschannon** [comment]
There is already a request for "rancher-compose up". https://github.com/rancher/rancher/issues/2119

I believe rancher-compose exec will be much harder but would need input from @ibuildthecloud

**Comment by mathuin** [comment]
I would like to add another command to the list:  `rancher-compose config`.  This will greatly help folks submitting bug reports by allowing us to see what rancher-compose sees.  The existing command in `docker-compose` spits out a single YAML file, which obviously isn't enough for `rancher-compose` but I'm confident you guys can work it out. :-)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
