### ISSUE TITLE
"show_if" values remain set once selected, even if conditional value has been changed 

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#21536]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. When installing any app, set a value for a parameter that is a condition for `show_if` field for any other parameter 
2. Set a value for parameter that shows up
3. Unset a value for the first parameter

**Result:**
Second parameter is still in place, despite the condition value is not set anymore

![ScreenRecording2019-07-15at4](https://user-images.githubusercontent.com/51338077/61255996-de7bf080-a71f-11e9-8493-cf0c01d39114.gif)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.4
- Installation option (single install/HA):
single install

**Comment by guangbochen** [comment]
can you please provide your `show_if` condition of the second parameter, thanks.
And you may need to do `show_if: etcd=own_etcd&&etcdCluster=portworx_hostted` in order to hide the `region` when the first option is not selected.

**Comment by oksana-px** [comment]
>show_if: etcd=own_etcd&&etcdCluster=portworx_hostted
this works perfectly, thanks!

But I still have cases like this:
```
- variable: usedrivesAndPartitions
  show_if: "environment=Cloud&&deviceConfig=Consume Unused||environment=Cloud&&onpremStorage=Automatically scan disks"
  label: "Use unmounted drives and partitions"
  descrition: "Use unmounted disks even if they have a partition or filesystem on it. PX will never use a drive or partition that is mounted."
  type: boolean
  default: false
  group: "Storage Parameters"
``` 
I can't make this ` show_if: "environment=Cloud&&deviceConfig=Consume Unused||environment=Cloud&&onpremStorage=Automatically scan disks"` work in one line, so I have to use the construction below, and it leading to the same problem as I described in my original post. In this case I have issue `- variable: usedrivesAndPartitions` when `environment=Cloud` is unset 
```
- variable: onpremStorage
  show_if: "environment=OnPrem"
  type: enum
  label: "Select type of OnPrem storage"
  group: "Storage Parameters"
  required: true
  options:
    - "Automatically scan disks"
    - "Manually specify disks"

- variable: deviceConfig
  show_if: "environment=Cloud"
  description: "If you plan to use EC2 instance storage or plan to manage EBS volumes your own way, select 'Consume unused' or 'Use Existing disks'."
  label: "Select a type of disk"
  type: enum
  default: "Create Using a Spec"
  required: true
  group: "Storage Parameters"
  options:
    - "Create Using a Spec"
    - "Consume Unused"
    - "Use Existing Disks"

############ Consume unused ##############
- variable: usedrivesAndPartitions
  show_if: "deviceConfig=Consume Unused||onpremStorage=Automatically scan disks"
  label: "Use unmounted drives and partitions"
  descrition: "Use unmounted disks even if they have a partition or filesystem on it. PX will never use a drive or partition that is mounted."
  type: boolean
  default: false
  group: "Storage Parameters"```

**Comment by trierra** [comment]
I'm still not able to figure out the case ^

**Comment by guangbochen** [comment]
A combination of `&& and ||` is currently not supported in the `questions.yaml` with catalog UI, for now, you may have to split and simplify the condition questions and using Helm charts to handle more logics, will update if we add more enhancement on this, thanks.

**Comment by trierra** [comment]
>for now, you may have to split and simplify the condition questions

That's exactly what i'm doing right now, but that causes this problem, when fields are remain set

**Comment by trierra** [comment]
any updates on this issue?
