### ISSUE TITLE
Machine gives up too soon with error  - Maximum number of retries(50) exceeded

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2154]
Using openstack driver created a host. Instance got added in openstack and I was able to login to it successfully. But rancher stopped even before instance creation was complete and did not install agent. Pls. note instance creation in openstack for a image like ubuntu takes about 10 minutes.  
```
Component 	Version
Rancher 	v0.39.0-rc1
Cattle 	v0.95.0
User Interface 	v0.52.0
Rancher Compose 	beta/latest
```
server log:

```time="2015-09-25T22:24:04Z" level=info msg="Creating Machine" eventId="3b891f85-dd55-45d1-aa6e-6599e1703375" resourceId=1ph18
time="2015-09-25T22:24:04Z" level=info msg="Cmd slice: [create -d openstack -................................]"
time="2015-09-25T22:24:04Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/6e9e9d37-59af-4ecb-b73b-2652223223cb/certs/ca.pem" resourceId: =1ph18
time="2015-09-25T22:24:05Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/6e9e9d37-59af-4ecb-b73b-2652223223cb/certs/cert.pem" resourceId: =1ph18
time="2015-09-25T22:24:08Z" level=info msg="stdout: Creating machine..." resourceId: =1ph18
time="2015-09-25T22:27:43Z" level=info msg="stderr: Error creating machine: Maximum number of retries (50) exceeded" resourceId=1ph18```


<img width="394" alt="screen shot 2015-09-25 at 3 28 44 pm" src="https://cloud.githubusercontent.com/assets/7720752/10113618/34874d3e-639b-11e5-9ea0-981ebcd53918.png">



<img width="1488" alt="screen shot 2015-09-25 at 3 34 08 pm" src="https://cloud.githubusercontent.com/assets/7720752/10113597/e785bbb0-639a-11e5-8e4e-061b40214bcb.png">

**Comment by deniseschannon** [comment]
I believe this is just docker-machine giving up, but want to confirm with @wlan0.

**Comment by vincent99** [comment]
It is, and there are [no options](https://github.com/docker/machine/blob/c4cd2385bf1790ff17ed05ae6312b24341f8183b/libmachine/mcnutils/utils.go#L84) to change it.  I suppose we could tweak it in [rancher/machine](github.com/rancher/machine). 

Where is this OpenStack running that spinning up ubuntu takes 10 minutes?

**Comment by aruneli** [comment]
openstack is running on a host in DO

**Comment by aruneli** [comment]
Just FYI - docker-machine has a new parameter for retry/timeout - https://github.com/docker/machine/issues/1632

We can add this param in UI if API supports it.

**Comment by deniseschannon** [comment]
The parameter that was introduced into docker-machine is actually called `--openstack-active-timeout` and is available in the UI. As these options are added into docker-machine, I'll close this issue.
