### ISSUE TITLE
Fix istio metrics issue when re-using cluster monitoring

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#21545]
**Version: rancher/rancher:master-head**

Istio should get metrics from cluster Prometheus when chose to re-use cluster monitoring.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head

* When enabling Istio, user is prompted to enable monitoring first (if it is not enabled already)
* Istio does not deploy it's own prometheus and instead uses prometheus from cluster monitoring
* Metrics appear in Istio dashboard correctly. 
* UI links direct user to prometheus / grafana correctly
