### ISSUE TITLE
resourceQuotaSyncController: project.management.cattle.io not found

### ISSUE THREAD

**Issue by hameno** [rancher/rancher#21546]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
unknown

**Result:**
I'm getting periodic errors in the logs:

```
2019/07/16 06:33:23 [ERROR] NamespaceController default [resourceQuotaSyncController] failed with : project.management.cattle.io "cluster-vp4z8/project-zj5k9" not found, [resourceQuotaUsedLimitController] failed with : project.management.cattle.io "cluster-vp4z8/project-zj5k9" not found
2019/07/16 06:33:39 [ERROR] NamespaceController default [resourceQuotaSyncController] failed with : project.management.cattle.io "cluster-rvvmm/project-r6l6q" not found, [resourceQuotaUsedLimitController] failed with : project.management.cattle.io "cluster-rvvmm/project-r6l6q" not found
```

Those clusters do not exist (anymore) but I'm still getting those errors. Maybe something got inconsistent over time?

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.5
- Installation option (single install/HA): single

**Comment by bLuka** [comment]
Same issue here.
Happened after a updating the cluster size (from 4 nodes to 3: ok, 3 nodes to 2: ko, 2 nodes to 3: still ko, but sometimes works randomly for several minutes since  a few hours ago).

Any idea?

**Comment by IAkumaI** [comment]
Happens after reboot Virtualbox machine.

I'm experimenting with rancher in VM. So, after reboot I'm getting this error and my cluster is lost. Works, but Rancher lost it (just empty cluster list).
If shutdown then turn on machine - all ok. Error shows only whe rebooting.

**Comment by IAkumaI** [comment]
Oh. Reboot again - cluster comes back. Wow.

**Comment by IAkumaI** [comment]
Steps to reproduce:
VirtualBox 6.0.2 r128162 (Qt5.6.2)
ubuntu-18.04.3-live-server-amd64.iso

k8s ups with rke:
```
# cluster.yml
nodes:
  - address: 192.168.150.104
    hostname_override: "dev.k8s"
    user: akuma
    ssh_key_path: "...."
    role: [controlplane,worker,etcd]

services:
  etcd:
    snapshot: false

ingress:
  provider: nginx
```

Runcher on same machine:
docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher:latest

Add cluster to Rancher with "Import an existing cluster".

All works fine.

Reboot machine with `reboot` or from VBox interface.
Got en error.

**Comment by tegk** [comment]
Same here
