### ISSUE TITLE
[UI] Cluster Template Issues - Windows Support

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21557]
Moved over Windows Support specific issues from rancher/rancher#21410 

Version: master-head (7/16/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

### List of issues, steps, results for each:

- **_When Set k8s to v1.14 and CNI to Flannel and Enable Windows support, when leverage template windows support is actually disabled for some reason_**

1. Create a template like shown, otherwise have defaults (all other overrides disabled. Notice we did not enable override for Windows Support but set it to Enabled.

![image](https://user-images.githubusercontent.com/45179589/61009485-988de980-a327-11e9-9341-8715a0432288.png)

2. Try to leverage the template.

RESULT: For some reason the UI shows it as disabled when trying to create a cluster with the template.
![image](https://user-images.githubusercontent.com/45179589/61009543-cd9a3c00-a327-11e9-8ab9-b29431aaf585.png)

You can also have your template set with the override Enabled and set Windows Support to Enabled and for some reason when you leverage the template it is still disabled by default even though template defines it to be enabled.

- **_Flannel Backend disabled when create new clone from default_**

Note: You can create a clone from the last one created in the last issue.
1. (If you don't have one already) Create a cluster template like this otherwise with defaults:
![image](https://user-images.githubusercontent.com/45179589/61010471-37681500-a32b-11e9-92a0-ed4c79fb0fd4.png)

Note that Flannel Backend is not grayed-out (not disabled).
2. Create a clone of this (in my case new revision based on default). Notice for some reason Windows Support override is not enabled again, Enable it. Look at Flannel Backend section.

RESULT: Flannel backend is grayed out and I can't change the settings.
![image](https://user-images.githubusercontent.com/45179589/61010521-7007ee80-a32b-11e9-85e8-4e4e74798042.png)

Things can break if you try to use the template. I get lots of errors in rancher logs like this:
```
E0710 22:59:03.033356       7 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v3.Cluster: json: cannot unmarshal number into Go value of type string
E0710 22:59:03.035129       7 reflector.go:134] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v3.Cluster: json: cannot unmarshal number into Go value of type string
```

- **_Cannot make some cluster template fields overridable with disabled elements:_**

1. Create a cluster template. Under the Cluster Options section, set each area to overridable as pictured below.
![image](https://user-images.githubusercontent.com/45179589/60927085-75970300-a25d-11e9-81ad-c3860840b4b8.png)
2. Now, in order to allow "Windows Support" to be overridable let's pick Flannel Network Provider and Kubernetes version 1.14. Good, now we can set this, but notice -- now we can't access "Project Network Isolation" so we can also make this overridable. It's still allows override, but it's confusing in the UI.
![image](https://user-images.githubusercontent.com/45179589/60927117-9d866680-a25d-11e9-8594-556383a2a340.png)

RESULT: I can create the cluster template and it will actually let me override both but it was confusing to set up to me. I had to manually pick flannel first and k8s v1.1.4 just to be allowed to see override switch for "Windows Support"; I would think I should not have this restriction for disabled items in the UI. I.e. Windows Support.

- **_Create template with no quesitons but correct selections for windows support, still shows Windows Support as disabled when try to use template_**

1. Create a cluster template, You will fill it out so that Flannel is chosen and k8s 1.14 and newer is picked but DO NOT supply any questions (no overrides).
2. Leverage the template. For some reason Windows Support is still Disabled even though we did not pick this when we created the template.

RESULT:
![image](https://user-images.githubusercontent.com/45179589/61333035-a2f22c80-a7da-11e9-96be-bd49eed6fb0b.png)

We should have seen "Windows Support" "Enabled" since I picked this when made template.

**Comment by loganhz** [comment]
Created another issue for fixing the override issue https://github.com/rancher/rancher/issues/21910. Now we don't allow users to override the Windows settings in master.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/12/19)

This changes the way we handle CT for Windows Support. As Logan mentioned, we don't allow users to set an override for the Windows settings.
Here is an example, I'm creating a CT here and do not have overrides for "Windows Support" and "Flannel Backend"

![image](https://user-images.githubusercontent.com/45179589/62897817-d0ae9080-bd08-11e9-8b75-474bf2164398.png)

-----

- [x] **_When Set k8s to v1.14 and CNI to Flannel and Enable Windows support, when leverage template windows support is actually disabled for some reason_**
(See issue description for any additional details)

This is no longer happening. When I leverage the template now, "Windows Support" is enabled now.
![image](https://user-images.githubusercontent.com/45179589/62898016-5c282180-bd09-11e9-8bdc-4e5d7d290ba4.png)

- [ ] **_Flannel Backend disabled when create new clone from default_**

This still isn't working correctly. Flannel Backend is still disabled when I clone my CTR.

Updated steps to reproduce this issue:

- Create a new CT, make it like this:
![image](https://user-images.githubusercontent.com/45179589/62898240-e1133b00-bd09-11e9-8020-1eb6cd53e43e.png)
- Now clone this revision we just made. Flannel Backend is grayed out but should not be:
![image](https://user-images.githubusercontent.com/45179589/62898290-01db9080-bd0a-11e9-856a-33a433749813.png)

Use case: I am cloning my revision and want to make a revision that sets "Host Gateway (L2bridge)"

- [x] **_Cannot make some cluster template fields overridable with disabled elements:_**

This is effectively fixed because we removed "Windows Support" override. It's still a little confusing because if I switch CNI to Flannel the override switch disappears for "Project Network Isolation" but this is an improvement. Perhaps this is something we can revisit after v2.3 release.

- [x] **_Create template with no quesitons but correct selections for windows support, still shows Windows Support as disabled when try to use template_**

This is no longer the case. Windows Support is indeed "enabled" now when I leverage my template:
![image](https://user-images.githubusercontent.com/45179589/62898662-e1600600-bd0a-11e9-98e3-5743ec1f0da9.png)

**Comment by davidnuzik** [comment]
@loganhz could you investigate the 2nd issue? "Flannel Backend disabled when create new clone from default"

Or if you prefer I can make a new issue to track this. This is the only one that still isn't working quite right otherwise the other 3 issues are fine now.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/13/19)

This concludes testing. All issues are now resolved. reference https://github.com/rancher/rancher/issues/21557#issuecomment-520596657 (my last comment) for the other 3 tests done.

With the last fix this resolves:

**_Flannel Backend disabled when create new clone from default_**

The flannel backend setting is no longer grayed-out (disabled) when we clone our CTR.
