### ISSUE TITLE
[rancher/kontainer-engine] EKS clusters do not have the option to encrypt the EBS volume for `/dev/xvda1`

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#21552]
**What kind of request is this (question/bug/enhancement/feature request):** RFE

**Steps to reproduce (least amount of steps as possible):**
Create an EKS cluster using Rancher (or just `kontainer-engine`)

**Result:**
The `/dev/xvda1` volume is created without encryption

**Other details that may be helpful:**

The `/dev/xvda1` volume should be able to be created with encryption.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.x
- Installation option (single install/HA): Any

**Comment by dramich** [comment]
In master with pr https://github.com/rancher/rancher/pull/23868

**Comment by sangeethah** [comment]
Blocked on testing this fix - https://github.com/rancher/rancher/issues/24372

**Comment by izaac** [comment]
This is getting set in the backend and after creating the EKS cluster if I go to edit I see the EBS encryption checkbox selected but in the AWS console the EBS volume appears as `Not Encrypted`

The UI part is meeting the expectation. But the setting is not reflected in AWS. Reopening.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (02/24/2020)` commit id: f84c1e8f7

The UI option is visible, and now if we select EBS encryption as True the workers ECS' instances will be setup with an encrypted volume.

Closing.
