### ISSUE TITLE
Compose CLI - Rolling service restart

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2155]
Add an optional rancher-compose restart --batch-size "2" where it can restart "2" containers from a given service at a time rather than restarting all containers and potentially disrupting the service itself.

**Comment by fentas** [comment]
Also this could be useful(?) for rolling service restart
```bash
# Set the interval to 30 seconds, which is the time between 
# when the containers restart
$ rancher-compose restart service --interval "30000"
```

**Comment by sangeethah** [comment]
Tested with rancher-compose-v0.7.0-rc1
Rancher server - Build from master 

Rolling restart is now supported from rancher-compose using the following command:
 
./rancher-compose -p test1 -f dc.yml  restart --batch-size 2 --interval 30000

This should be available in the next rancher-server release.
