### ISSUE TITLE
Visual indicator for Imported cluster in Edit Cluster screen

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21562]
Rancher version:
v2.2.4

Request type;
enhancement

Description:
add a visual indicator in the edit cluster screen to inform user when cluster is of provider type: Imported.

this info is there in the list view but not in detailed

![clusterlist](https://user-images.githubusercontent.com/11086008/61320375-27828200-a7be-11e9-946c-4f762ba72a9e.png)

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/62993576-7e957880-be8a-11e9-87ee-7fe039cde1bb.png)

**Comment by davidnuzik** [comment]
@izaac when you get around to this one inform me. I'd like to demo utilizing RKE to bring up a cluster. You will need to have a clear understanding of how to do this so you may then import a cluster into rancher to test this.

**Comment by izaac** [comment]
Rancher versions: v2.2.4 and master-head (v2.3) (8/20/2019)

Replicated the reported issue in v2.2.4, see the following screenshot of the Edit Cluster webpage:

<img width="1745" alt="Screen Shot 2019-08-20 at 2 40 19 PM" src="https://user-images.githubusercontent.com/27659/63387324-fa476780-c359-11e9-90e9-ececb0054d07.png">


Latest Rancher master-head (v2.3) (8/20/2019), same Edit Cluster page now with the visual provider indicator:

<img width="1721" alt="Screen Shot 2019-08-20 at 2 47 24 PM" src="https://user-images.githubusercontent.com/27659/63387452-42668a00-c35a-11e9-946e-4ff58768a24b.png">


I've used latest Chrome and Firefox browsers to do the validations.

Provider indicators are still showing as expected in the list view and dashboard views as expected.
