### ISSUE TITLE
[UI] DeleteNotReadyAfterSecs UI tooltip needs a change

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21578]
Version: master-head (7/16/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- View tooltip. It doesn't mention that a value of 0 means we basically do nothing (no auto deletion/healing)

**Result:**
I'm not sure how to word this better, but we should mention this as end users may not understand that a value of "0" basically means this is disabled!

**Other details that may be helpful:**
Screenshot of tooltip:
![image](https://user-images.githubusercontent.com/45179589/61337183-20bd3480-a7e9-11e9-85db-66c8a66f0489.png)

Translation key:
**%clusterNew.rke.nodes.deleteNotReadyAfterSecsTooltip%**

**Comment by deniseschannon** [comment]
@vincent99 could you help with some nice wording?

**Comment by vincent99** [comment]
`If greater than 0, nodes that are unreachable for this long will be automatically deleted and replaced.`?

**Comment by vincent99** [comment]
Also note that this is more or less bandaid to get the option in.  Longer term the nodepool section needs different design that isn't a table so that each pool can have more space to display options like this and future things coming.

e.g. I'd much rather it be something like:

```
(*) Automatically replace nodes when they have been unavailable for more than [ 30 | minutes ]
( ) Do not automatically delete failed nodes
```

**Comment by tfiduccia** [comment]
@deniseschannon & @rmweir - Went over this with Will as well and he would like tip to be redesigned.  So when Lauren gets a change she will be modifying this and she can change the text at the same time.

**Comment by davidnuzik** [comment]
Version: master-head (7/23/19)

This change modifies the styling of the tooltips as well as the text in this area.

Style has changed to be smaller text globally, and transparent background of dark gray:
![image](https://user-images.githubusercontent.com/45179589/61731508-7b4a1980-ad30-11e9-8c05-8b8357943f1d.png)
A max-width setting was also established (see the PR) the changes make sense to me.
I smoke tested this global tooltip change by visiting various pages and ensured the tooltip looks the same in all areas. I didn't observe any issues with this change.

The language has been changed specifically for this area as well:
![image](https://user-images.githubusercontent.com/45179589/61731553-94eb6100-ad30-11e9-993b-3c1690570b5e.png)
