### ISSUE TITLE
Cluster Template - Ability to filter out windows support enabled templates for RKE clusters using node drivers (except for custom cluster).

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21575]
When creating a RKE cluster using node drivers from cluster template, cluster templates created with windows support enabled should not be presented as an option .

Cluster templates created with windows support enabled should  be presented as an option  only when creating custom cluster.

**Comment by loganhz** [comment]
It looks like wes already fixed it in master.

**Comment by davidnuzik** [comment]
Version: master-head (8/2/19)

- Create a CT with Windows Support enabled like:
![image](https://user-images.githubusercontent.com/45179589/62395555-71d96200-b525-11e9-8fb2-aac6dd0506c9.png)
- Attempt to create RKE cluster in all RKE providers except custom, confirmed for each, Windows Support is not shown:
![image](https://user-images.githubusercontent.com/45179589/62395621-b107b300-b525-11e9-8358-8b0fc2bb0b43.png)
- Now attempt with custom RKE cluster, confirmed Windows Support is shown:
![image](https://user-images.githubusercontent.com/45179589/62395645-c41a8300-b525-11e9-9250-4715eff9f801.png)
