### ISSUE TITLE
[UI] Cluster Template Issues - Cluster Owner can't see anything when edit cluster that Admin created

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21570]
- [ ] **_If admin creates a template, share with user2 who will be cluster owner, admin leverages template to create cluster and adds user2 as cluster owner, when log in as user2 and edit cluster can't see anything_**

1. Login in as the main admin user. Create a template with defaults, just share it with user2 (which is a standard user).
2. Now, still as the admin user, leverage the template to create a cluster. While you do so, add user2 as a cluster owner for this cluster.
3. Login as user2, try to edit the cluster.

RESULT: user2, the cluster owner, can't edit the cluster, they do NOT get permissions issue like in somewhat similar issue https://github.com/rancher/rancher/issues/21473 instead, they just see a blank page upon edit just showing the list of Member Roles section and nothing else.
This is strange, because they have access to the cluster template (I shared the cluster template to user2 as a member) and are cluster owner of the cluster itself.

**Comment by sangeethah** [comment]
@davidnuzik could you test this with custom cluster to eliminate this issue - https://github.com/rancher/rancher/issues/12038

**Comment by davidnuzik** [comment]
@sangeethah I did the following:

Scenario 1:
Re-test with NON-custom cluster - Reproduced.

Scenario 2:
Re-test WITH custom cluster (as you requested) - DID NOT REPRODUCE.
User2 is now able to see cluster options, and all other panes without any issues.

**Comment by davidnuzik** [comment]
Therefore is likely duplicate of https://github.com/rancher/rancher/issues/12038

**Comment by davidnuzik** [comment]
Closing as duplicate of #12038
