### ISSUE TITLE
Windows node fails to register in a cluster with k8s version 1.15.0

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21577]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a custom cluster on rancher:master-head
2. Add a linux node - Ubuntu 18.04 LTS - all roles
3. Add a windows node - 2019 - worker role.

**Expected Result:**
Node should get registered with the cluster

**Actual Result:**
Windows node fails to register
<img width="1220" alt="Screen Shot 2019-07-16 at 4 40 44 PM" src="https://user-images.githubusercontent.com/26032343/61337148-f5d2e080-a7e8-11e9-9a26-7171f6b51ff0.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`): 

```
1.15.0
```

**Comment by davidnuzik** [comment]
Hello @loganhz is this still on hold in review? Thanks

**Comment by loganhz** [comment]
yes

**Comment by loganhz** [comment]
@sangeethah @sowmyav27  Before these 2 PRs merged, the workloads under system project might not be scheduled successfully. You need to delete the red pods manually to workaround it.  

```
https://github.com/rancher/kontainer-driver-metadata/pull/29
https://github.com/rancher/rancher/pull/22346
```

**Comment by loganhz** [comment]
Link to PR https://github.com/rancher/kontainer-driver-metadata/pull/9

**Comment by sowmyav27** [comment]
**Verified with latest master-head.**
**Setup:**
```
Windows AWS node: `Windows_Server-1903-English-Core-Base-2019.08.16`
Linux Node: `18.04 Ubuntu LTS`
Linux node docker and Windows node docker - 19.03, k8s version - 1.15.3
```
**Steps:**
1. Launch a custom cluster 
2. Register 1 etcd and control plane linux node
3. Register 1 worker linux node
4. Register 2 worker windows node.
5. Windows cluster comes up active. Windows nodes are registered.

Basic test cases - deploying workloads, ingress, nodeport works.
