### ISSUE TITLE
Node pool roles helper text needs to be fixed

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21576]
Version: master-head (7/16/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
With the addition of node pool healing in the UI now, things have shifted around a bit:
![image](https://user-images.githubusercontent.com/45179589/61336922-1e0e0f80-a7e8-11e9-9d57-1783e68474a3.png)

- Now the red text is not in alignment with etcd, cp, worker.

**Result:**
Things are out of alignment. We need to tweak the page styling to fix this.
I'm not sure how to fix. Maybe we could make red text a little smaller and fix alignment? Maybe we can make other fields a little smaller as well to make it all fit correctly.

**Other details that may be helpful:**
Here is how it used to look (screenshot from v2.2.5)
![image](https://user-images.githubusercontent.com/45179589/61337038-8826b480-a7e8-11e9-8333-7a693bca13a9.png)

**Comment by davidnuzik** [comment]
Version: Master-head (7/19/19) (`4aa4e1ab`)

I still observe the issue. The red helper text for the node roles is still offset to the left.
![image](https://user-images.githubusercontent.com/45179589/61554465-d9fe5300-aa11-11e9-929a-45945e919dc9.png)

**Comment by davidnuzik** [comment]
Version: master-head (7/23/19)

One issue remains. The new changes look good except for that now we can't read the full text of "Recreate Unreachable After"
![image](https://user-images.githubusercontent.com/45179589/61732607-cf55fd80-ad32-11e9-9144-9c87259db68f.png)

I'm not sure how to handle this.

Some ideas:
- Change to just "Recreation" (and tooltip will explain)
- Possibly do:
letter-spacing: 0px (remove styling just for this text)
font-size: 12px

Remove sortability 
![image](https://user-images.githubusercontent.com/45179589/61732927-979b8580-ad33-11e9-92b5-e0333e5eb593.png)

Example:
![image](https://user-images.githubusercontent.com/45179589/61732957-a84bfb80-ad33-11e9-8458-2d78ba738959.png)

**Comment by westlywright** [comment]
This was fixed [here](https://github.com/rancher/ui/commit/a37f6aa400a7bc68d18bf6cad00d5ef52a457020#diff-8f5471df56e97fcf3c43189f622993c8) but got clobbered along the line somewhere, I'll push it back in on my next pr.

**Comment by davidnuzik** [comment]
I am closing the issue. The remaining issue mentioned above here https://github.com/rancher/rancher/issues/21576#issuecomment-514304583 is now fixed. The text was changed to "Auto Replace" which makes sense to me.

See below:
Version: master-head (7/26/19)
![image](https://user-images.githubusercontent.com/45179589/61966128-bf365c00-af86-11e9-8697-100fef194362.png)
