### ISSUE TITLE
Rancher cluster monitoring cannot monitor etcd 

### ISSUE THREAD

**Issue by z00314736** [rancher/rancher#21581]
**What kind of request is this (question/bug/enhancement/feature request):**

question

**Other details that may be helpful:**

I enabled the cluster monitoring. but etcd cannot be monitored,  need any extra config or plugins?

![image](https://user-images.githubusercontent.com/28840934/61343279-c622e780-a87f-11e9-9d01-380c3d03f1e2.png)

docker 17.03.2
Rancher 2.2.5 
kubernetes 1.14.3
etcd: rancher/coreos-etcd:v3.3.10-rancher1

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/18619#issuecomment-478179506
