### ISSUE TITLE
[UI] Support selected version when we enable monitoring

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#21582]
Backport issue: https://github.com/rancher/rancher/issues/21460

UI should pass the monitoring version to the backend on enabling monitoring.

![image](https://user-images.githubusercontent.com/4569037/61355763-98519900-a8a7-11e9-8d3c-5c9d8305fb95.png)

e.g `version: 0.0.3`

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/21460
