### ISSUE TITLE
Private registry in UI expects https:// but failed to pull system images

### ISSUE THREAD

**Issue by quentingodeau** [rancher/rancher#21591]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a rancher instance :
  - on an isolated network (no internet access)
  - with a private registry
  - with only VSphere provider
- Create a new cluster :
  - configure private registry on the UI
    - "URL" field expected a valid URL so fill it with "https://myregistry.com"
    - also fill login and password for the registry

**Result:**
In rancher logs:
> [ERROR] ClusterController c-nx577 [cluster-provisioner-controller] failed with : [Error checking if image [https://myregistry.com/rancher/rke-tools:v0.1.34] exists on host [10.111.30.37]: Error response from daemon: no such image: https:/myregistry.com/rancher/rke-tools:v0.1.34: invalid reference format]

**Other details that may be helpful:**
If we fill the "URL field" with "myregistry.com" (without "https://") :
- a red border appears
- BUT it works!

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.5
- Installation option (single install/HA): single install

**Comment by tfiduccia** [comment]
Version - master
Reproducible on master.  I'm not sure if this is a UI thing or backend API thing that isn't sending proper error message to front end.

**Comment by loganhz** [comment]
What's the expected behavior? We should not allow users to create a cluster with private registry starting with https://?

**Comment by vincent99** [comment]
This is from the `<input>` being `type="url"`, which causes a more appropriate keyboard to be shown for touch devices.  It also causes the browser to validate the value and add the `:invalid` pseudo-class.

And (only) Firefox has a default stylesheet that adds `input:invalid { border-color: red }`.

So 2 things:
 - The UI should probably strip off `https://` if it's impossible to use a registry with it
 - Add `input:invalid { box-shadow: initial; }` to form styles so that it doesn't show up red.

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:master-head 79c9048b3, user interface v2.3.5
in Chrome and Firefox 

Now when we enter or paste the private registry's URL, the protocol part `http://` or `https://` at the beginning of the input will be stripped out.

Adding a cluster with private registry is successful and no red border shows in the UI anymore.

**Comment by davidnuzik** [comment]
Side note (in case we find this issue later) a secure registry is required at least based on a test done late last year. Reference https://github.com/rancher/rancher/issues/17186
