### ISSUE TITLE
Provision vSphere nodes with ubuntu

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21605]
Rancher version:
v2.2.4

Type:
Enhancement

Description:
Add support for Ubuntu image in the OS ISO url field in the node template / vSphere use case.  Currently, it offers RancherOS as the only option.

<img width="1245" alt="vSphereNodeTemplate" src="https://user-images.githubusercontent.com/11086008/61426729-682aea00-a8e9-11e9-8927-23da6f955047.png">

**Comment by luthermonson** [comment]
@jambajaar this is a docker machine limitation as it was hardcoded to do only boot2docker isos and rancheros was built to support. i hightly recommend you read this PR https://github.com/rancher/rancher/issues/21483 as there's a really good chance you'll be happy with this implementation but would like your feedback. For testing I just grabbed off the shelf ubuntu ovas and imported them into vsphere and cloned that by name. leave feedback on that PR if you have any or write back on this issue if you dont think cloning will give you what you need.

**Comment by luthermonson** [comment]
Now supported from this issue: https://github.com/rancher/rancher/issues/21483

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3` 

* Using new node templates:
  * Create a node template that uses an Ubuntu template
  * Node is provisioned and cluster becomes active
  * Basic workload tests passing

**Comment by josedavireges** [comment]
Does anyone have a "how to" to use ubuntu on nodes?

The rancher always gives the following error: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded

**Comment by bmdepesa** [comment]
@josedavireges Which Ubuntu release are you trying to use? If using `19.04` you will need to change the Docker engine install URL to `https://get.docker.com`

**Comment by josedavireges** [comment]
18.04.3 LTS
However, apparently the rancher can not log in the machine. What would be the correct way to pass the login data?
