### ISSUE TITLE
How to recover cluster from Unavailable state

### ISSUE THREAD

**Issue by bmcgithub** [rancher/rancher#21603]
*Describe your issue here*

My cluster currently  in " Unavailable" state  withe following error:
Failed to ensure monitoring project name: failed to find "cattle-prometheus" Namespace: Get https://10.128.97.39:6443/api/v1/namespaces/cattle-prometheus?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers); Failed to communicate with API server: Get https://10.128.97.39:6443/api/v1/namespaces/kube-system?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

can you help me get the cluster back to "Active" state ?

Thanks,

**Comment by CyberCyclone** [comment]
I've got the same issue. Rancher 2.2.7 using Ubuntu 18.04.2 (x86) and the agents are arm64 based with Ubuntu 18.0.4.

The issue started after removing a node that failed to initialise.

**Comment by fjoesne** [comment]
same issue here on 2.2.8. seems to be stuck because rancher insists on using the removed node as a host for the api-server. Perhaps this is only on non HA setups?

**Comment by Ziul** [comment]
Getting the same error on Rancher 2.3.4. The problem started when an AWS spot instance was replaced.

**Comment by 00r2** [comment]
@StrongMonkey @sangeethah  Facing same issue with latest version 2.4.2 

I am assuming this is probably root cause for the above issue might be different 

underlying issue we got from logging

```
W0410 17:43:01.928054       1 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:187: watch of *summary.SummarizedObject ended with: unexpected object: &{{{Status v1} {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []}} }
--

```

**Comment by mkanakis** [comment]
@00r2 
Did you find any work around?

**Comment by pjmorr** [comment]
I am seeing this on 2.4.3.  5 clusters, 3 of which have spot nodes, and it also seems to be spamming the rancher api to the point that the UI is timing out with backlog errors to random sections of any cluster in the UI.  Even ones without spot instances.

**Comment by 00r2** [comment]
> @00r2 
> 
> Did you find any work around?

I applied Disabled_http2 and the timeouts stopped
