### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by fernandoneto** [rancher/rancher#2160]
If you have an organization in read-mode and then you grant to one of that organizations members owner permissions that same member is not allowed to create anything.

**Comment by cusspvz** [comment]
We encountered this issue while setting up @fernandoneto 's permissions on an environment.

**Comment by vincent99** [comment]
So @fernandoneto is added as an owner of the environment, but is also a member of an organization that is a read-only member of the same environment?

@hibooboo2 the "higher" mode should apply.

**Comment by cusspvz** [comment]
> So @fernandoneto is added as an owner of the environment, but is also a member of an organization that is a read-only member of the same environment?

Yup, seems that in someway (didn't read the chunk of code that causes that yet) organization data is overriding member data.

**Comment by deniseschannon** [comment]
Just to confirm, I was able to reproduce on v0.39.0.

**Comment by hibooboo2** [comment]
Just looked into it. The code is there and works. For some reason the settings are not being read from where the defaults were made. I just submitted a pr to fix this.

**Comment by hibooboo2** [comment]
Addressed with rancher/cattle#915

**Comment by sangeethah** [comment]
Tested with build from master - Oct 8

Created environment - e1 and made organization - "org1" as "readonly" member.  Added user -"U1" who is the member of "org1" as the "owner" of this environment.

When logged in as "U1" , U1 gets owner access to "org1".

**Comment by hibooboo2** [comment]
@sangeethah This is correct the highest permission role is the one that gets chosen. 

```
for (ProjectMember projectMember: projectMembers){

                if (role == null){
                    role = projectMember.getRole();
                } else {
                    String newRole = projectMember.getRole();

                    if (getRolePriority(newRole) < getRolePriority(role)){
                        role = newRole;
                    }
                }
            }
```

```
api.security.role.priority.owner=0
api.security.role.priority.member=1
api.security.role.priority.readonly=2
```

**Comment by cusspvz** [comment]
Thanks !! :)
