### ISSUE TITLE
AWS EKS setup bugs (ui/state)

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/rancher#21611]
Component | Version
-- | --
Rancher | v2.2.5
User Interface | v2.2.89
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1

## 1. Creation of EKS cluster.

Documentation specifies that you need to select *a* security group; the UI explicitly states "Choose the security groups that will apply to EKS instances."

![image](https://user-images.githubusercontent.com/83597/61454116-e1612600-a957-11e9-8745-d64037678e2e.png)

If you select more than one security group the build fails when creating the worker nodes 

```
"Error creating stack with worker nodes template: stack failed to create: Parameter validation failed: parameter value sg-xxx,sg-xxx,sg-xxx for parameter name ClusterControlPlaneSecurityGroup does not exist. Rollback requested by user."
```

##  2. Editing of EKS cluster in rancher

![image](https://user-images.githubusercontent.com/83597/61453964-70ba0980-a957-11e9-8914-f4bcb407b1a7.png)

On VPC & Subnet options VPC & subnet is greyed out and set to standard (it carries the standard through to next section on click) ignoring that the vpc was previously configured.

You have to click public ip to yes then back to no to be able to select custom again.
The subnets are all deselected at this point (again it's ignoring previous config).

Once you've made it to the save button, you can see the previous edit you made to the node config is there, but looking in AWS nothing has actually been applied (CF template params are the same / asg hasn't altered etc)

## 3. UI only allows the setting of a min + max capacity.

Setting Min 1, Max 2
Actually sets the stack as follows

NodeAutoScalingGroupDesiredCapacity | 3 | 
NodeAutoScalingGroupMaxSize | 2 | 
NodeAutoScalingGroupMinSize | 1 |

And errors

**Comment by davidnuzik** [comment]
To test / try to reproduce when able possibly next week.

**Comment by codyrancher** [comment]
Because this issue is three separate problems I'm creating three new issues to track each independently.

rancher/rancher#23878
rancher/rancher#23879
rancher/rancher#23880
