### ISSUE TITLE
Install app with kustomize

### ISSUE THREAD

**Issue by guilhem** [rancher/rancher#21614]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Current app implementation use _helm_ charts.
It would be great to be able to use a [_kustomization_](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/glossary.md#kustomization).

**Comment by antoniomo** [comment]
Still relevant. It would be great to have a Kustomize plugin that creates/assigns deployments to rancher projects. Similar to the terraform rancher2 provider, but without the need for terraform, as this would be trivial with a kustomize plugin :)
