### ISSUE TITLE
Rancher CLI login without context

### ISSUE THREAD

**Issue by azelezni** [rancher/rancher#21612]
Currently rancher cli required me to know in advance the cluster ID and project ID in order to be able to login, this makes it unusable in automation when I don't know the ID and I need rancher cli itself to get it.

It should be possible to login without context and be able to list clusters/projects to get their ID.

The current workaround is just using curl to get the ID and then running rancher login.

**Comment by datosh** [comment]
Was about to open a similar issue... I am also running into the same limitation.
I have a working solution with Terraform, which is fine, since I use Terraform to spin up my Rancher managed K8s clusters anyway, but it would be nicer, if I could get rid of this additional step, and simply use the rancher CLI for that.

```
data "rancher2_project" "system" {
    cluster_id = "${var.my_cluster_id}"
    name = "System"
}
```
Source: https://www.terraform.io/docs/providers/rancher2/d/project.html

Afterwards I'm able to 
```
output "rancher_project_id" {
  value = "${rancher2_project.system.id}"
}
```

Then I can do
```
rancher login -t ${RANCHER_TOKEN} --context `terraform output rancher_project_id` ${RANCHER_URL}
```

Maybe this helps someone as a workaround in the meantime :)

**Comment by wwjn** [comment]
@azelezni 

This seems to be resolved in the latest release.

**Comment by nagytech** [comment]
@azelezni 

This appears to be resolved in the latest release (v2.3.0-rc4).  The [docs](https://rancher.com/docs/rancher/v2.x/en/cli/) even indicate that you no longer need to login to a specific project.

**Comment by ryudice** [comment]
I'm using the rc-6 and it still asks you to select the project if you dont pass it using the --context option

**Comment by sbelyankin** [comment]
Using this [answer](https://github.com/rancher/rancher/issues/15821#issuecomment-447669601), I was able to put together this script that got me past this issue, hope it helps.

```
# login using first available cluster and context
 echo 1 | rancher login https://mycluster.com --token my-token

 # retrieve kube config for specific cluster and save to a local file
 rancher clusters kf my_cluster > my_cluster

 # tell kubectl to use our local config file
 export KUBECONFIG=my_cluster

 # retrieve specific namespace project ID, in this case 'default'
 CONTEXT_ID=$(kubectl get ns default -o jsonpath="{.metadata.annotations.field\.cattle\.io/projectId}")

 # login using using specific cluster and retrieved project ID as context
 rancher login https://mycluster.com --token my-token --name my_cluster --context "${CONTEXT_ID}"
```

**Comment by jgallucci32** [comment]
Using `rancher version v2.4.10` this is still an issue. Forced to specify cluster context even if all we need the Rancher CLI for is for global commands (e.g. create new cluster)

The workaround works good enough, just have to be careful as you are selecting first cluster by default.
