### ISSUE TITLE
UI: Ability to set s3 backup path

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#21619]
UI for https://github.com/rancher/rancher/issues/20859

Depends on https://github.com/rancher/rancher/pull/21584

**Comment by sowmyav27** [comment]
New field `S3 Folder` has been added on rancher:master-head(07/25/2019) latest
UI tag : `https://releases.rancher.com/ui/latest2/index.html`

1. Deploy an AWS cluster - 1 etcd, 1 control plane and 1 worker nodes with S3 backups enabled.
2. Enter S3 bucket-name, S3 folder, S3 Region Endpoint, S3 Access Key and S3 Secret key while configuring the cluster. (S3 bucket and the sub-folder in that bucket be created prior to this step)
3. Verified that the recurring snapshots and manual snapshots are taken and backed up in the given S3 targets.
4. Restore from these snapshots also work.
