### ISSUE TITLE
Backport: Ability to use IAM for etcd snapshot backups to s3

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21623]
Backport https://github.com/rancher/rancher/issues/21314

**Comment by alena1108** [comment]
Can be tested with `v2.2.6-rc2`

**Comment by soumyalj** [comment]
Tested with v2.2.6-rc2
Created rancher server with node having IAM profile with S3 access permissions
Create cluster in EC2 with nodes having the same IAM profile by providing S3 bucket name and without other credentials.
Creating cluster with S3 backup is successful
etcd snapshot and restore from S3 are functional as expected.
