### ISSUE TITLE
Recurring error in server logs, related to healthcheck

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#2162]
I'm getting a recurrent error in the logs at a rate of about 1 every 5 seconds:

```
2015-09-28 15:32:12,500 ERROR [:] [] [] [] [cutorService-25] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [7] output [INFO: Updating healthcheck
INFO: Downloading http://my.rancher.dns:PORT/v1//configcontent//healthcheck current=healthcheck-204-464be13ed9f0356d28455d3ca4a83d47177dbe2055fb0b0f3f9292ff2b6c6a88
]
2015-09-28 15:32:18,504 ERROR [:] [] [] [] [ecutorService-5] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [7] output [INFO: Updating healthcheck
INFO: Downloading http://my.rancher.dns:PORT/v1//configcontent//healthcheck current=healthcheck-204-464be13ed9f0356d28455d3ca4a83d47177dbe2055fb0b0f3f9292ff2b6c6a88
]
2015-09-28 15:32:24,504 ERROR [:] [] [] [] [cutorService-23] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [7] output [INFO: Updating healthcheck
INFO: Downloading http://my.rancher.dns:PORT/v1//configcontent//healthcheck current=healthcheck-204-464be13ed9f0356d28455d3ca4a83d47177dbe2055fb0b0f3f9292ff2b6c6a88
]
2015-09-28 15:32:30,506 ERROR [:] [] [] [] [cutorService-24] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [7] output [INFO: Updating healthcheck
INFO: Downloading http://my.rancher.dns:PORT/v1//configcontent//healthcheck current=healthcheck-204-464be13ed9f0356d28455d3ca4a83d47177dbe2055fb0b0f3f9292ff2b6c6a88
]
```

It's apparent this has to do with a healthcheck. I don't remember setting up any healthchecks that I haven't cleaned up in my testing. I also went through all active services, and can't find any active healthchecks.

How can I use these entries to troubleshoot this further, for tracking down and removing the offending item?

(PS - found a few similar issues, but none seemed general enough to tack this on).

**Comment by ebr** [comment]
I was eventually able to track it down to a Networking container that was a left over from some experimentation several weeks ago. I can close this issue, though it would still be helpful to frame some troubleshooting process for this type of an error. 

In this case, I was able to narrow it down to one of my environments by poking around in the DB, and getting eventually to the `healthcheck_instance_host_map` table, which only had a reference to a single `account_id` in all of the rows.

**Comment by alena1108** [comment]
@ebr is there a chance you can get agent.log from sep 29  - /var/log/rancher/agent.log from your host(s)? Want to see if there are more details on the error there

**Comment by ebr** [comment]
@alena1108 do you mean sep 28th, from before I fixed the issue? I can get that log, and I *think* it's the same instance that was causing the issue initially (i've rotated a few of them out since yesterday). However, there seems to be some private info in the logs that I would need to sanitize, so it's not practical to send entire log files. Would it help if I sent you (privately) just the relevant portions from around the time I was seeing these errors?

**Comment by ebr** [comment]
@alena1108 the new "Admin" tab in the UI is very helpful in tracking down these sorts of issues - thank you... I'm going to close this.
