### ISSUE TITLE
In airgap setup with private registry, cluster fails to provision - Error: No such image: registry:443/rancher/rke-tools:v0.1.34

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#21621]
rancher/rancher:v2.2.5
Airgap setup
Private registry
Single-node install

* Deploy Rancher in an airgap setup from a private registry
* Create a custom cluster
* After running registration command, node registers
* Cluster fails to provision with error: `[Failed to create [rke-etcd-port-listener] container on host [172.31.24.252]: Error: No such image: registry:443/rancher/rke-tools:v0.1.34]`

* `system-default-registry` setting is correctly set

![Screen Shot 2019-07-18 at 2.46.36 PM.png](https://zube.io/files/rancher/db39433e42ee0f41dc45798ca0d3ff08-screen-shot-2019-07-18-at-2-46-36-pm.png)

https://github.com/rancher/rke/issues/1472

**Comment by bmdepesa** [comment]
Rancher server logs:
```2019/07/18 22:00:56 [INFO] cluster [c-xk77g] provisioning: [network] Successfully pulled image [registry:443/rancher/rke-tools:v0.1.34] on host [172.31.18.230]
2019/07/18 22:00:56 [ERROR] cluster [c-xk77g] provisioning: [Failed to create [rke-etcd-port-listener] container on host [172.31.18.230]: Error: No such image: registry:443/rancher/rke-tools:v0.1.34]
2019/07/18 22:00:56 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/07/18 22:00:56 [ERROR] ClusterController c-xk77g [cluster-provisioner-controller] failed with : [Failed to create [rke-etcd-port-listener] container on host [172.31.18.230]: Error: No such image: registry:443/rancher/rke-tools:v0.1.34]
```

**Comment by kinarashah** [comment]
NOTE: This is not related to how private registry is passed while creating cluster but not the linked issue. https://github.com/rancher/rancher/issues/21622 
Removing blocker.

**Comment by bmdepesa** [comment]
User error: Including the private registry credentials in custom cluster configuration allowed cluster creation to succeed.
