### ISSUE TITLE
[UI/UX] Account Type set always as User even if you have Admin set

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2163]
On `/admin/accounts`, if you edit an user `Account Type` appears always as `User`.

Besides its an UI bug, it could lead to an **Admin** ungrant if other **Admin** starts playing with *edit* and *save* thinking there wasn't changes. That turns it into an UX bug.

**Comment by deniseschannon** [comment]
I am unable to reproduce your issue as for any user, as an admin I can edit the account type. 

Did you do a fresh install or some type of upgrade?

What authentication did you choose? Are you the initial admin or a user that was upgraded to admin?

**Comment by cusspvz** [comment]
> Did you do a fresh install or some type of upgrade?

fresh install

> What authentication did you choose?

GitHub

> Are you the initial admin or a user that was upgraded to admin?

Initial admin

--------

Sorry for not point all those steps. :p

**Comment by deniseschannon** [comment]
Okay, I finally understand what the issue is. I just didn't read it correctly the first time and kept trying the wrong use case. 

Steps To Reproduce:
When you try to edit an "Admin" account , it always picks User in the Account type dropdown.

@vincent99

**Comment by deniseschannon** [comment]
Verified in v0.40.0-rc1. UI v0.53.0
