### ISSUE TITLE
[CLI] rancher apps -o json doesn't produce valid JSON

### ISSUE THREAD

**Issue by ap1969** [rancher/rancher#21644]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Install two apps.
- Run 'rancher apps -o json'

**Result:**
Output starts:
{"ID":"p-c8sbj:phpbb","App":{"id":...

This should surely be an array of objects, so I'd expect it to be: 
[{"ID":"p-c8sbj:phpbb","App":{"id":...

Not having an array makes it hard to process in a CI environment.

**Environment information**
- Rancher version: 2.2.3
- Installation option: Single install
- CLI version: 2.2.0

**Comment by ekristen** [comment]
This is not a bug. @ap1969 it is valid JSON, it's called line delimited (or streaming) JSON. https://en.wikipedia.org/wiki/JSON_streaming

There are several tools including `jq` that support and understand how to parse it.
