### ISSUE TITLE
Enable support for k8s 1.16

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#21649]
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by deniseschannon** [comment]
Review our charts/system-charts that we aren't using any of these deprecated APIs.

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/21734

**Comment by alena1108** [comment]
We have to add experimental support for k8s 1.16. As a part of it, following needs to be done:

- [ ]  Release v1.6 hyperkube image (alpha tag is fine)
- [ ] Revise v1.16 addons' images and templates, and bump up the versions if needed
- [ ] Test v1.16 k8s APIs from Rancher UI/API to make sure the vendored client we use, is compatible. If not, we should consider bumping it up.

**Comment by sangeethah** [comment]
Rancher server version - Build from master - `24e4bdf`
Able to bring up a cluster with K8s version `1.16.0-beta1`  successfully.

Existing automation runs found 1 issue with rollback scenario that is tracked in https://github.com/rancher/rancher/issues/22583
