### ISSUE TITLE
where is docker-machine-driver-aliyunecs source code

### ISSUE THREAD

**Issue by better0332** [rancher/rancher#21643]
I can't find docker-machine-driver-aliyunecs source code(http://machine-driver.oss-cn-shanghai.aliyuncs.com/aliyun/1.0.2/linux/amd64/docker-machine-driver-aliyunecs.tgz), its different from `https://github.com/AliyunContainerService/docker-machine-driver-aliyunecs`,
it will create `Rancher Machine` security group

**Comment by loganhz** [comment]
https://github.com/cnrancher/docker-machine-driver-aliyunecs

Please submit another issue if you have any other question or issue.
