### ISSUE TITLE
Failed to build rancher locally 

### ISSUE THREAD

**Issue by saiyam1814** [rancher/rancher#21640]
I need to do some modifications to rancher UI and test the whole locally, For that, I am trying to build rancher/rancher code locally but its throwing error in the URL's formation.

Steps
1) Download the code locally 
2) run make build 

**Error**: Happy Helming!
Downloading 
curl: (3) <url> malformed
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: plugin install hook for "unittest" exited with error
The command '/bin/sh -c curl -sLf ${!HELM_URL} > /usr/bin/helm &&     curl -sLf ${!TILLER_URL} > /usr/bin/tiller &&     chmod +x /usr/bin/helm /usr/bin/tiller &&     helm init -c &&     helm plugin install https://github.com/rancher/helm-unittest' returned a non-zero code: 1
FATA[0062] exit status 1                                
make: *** [build] Error 1

Additional Requirement : 
For   Rancher UI the code base is rancher/ui
So need here is to take ui from the local branch to test the changes made to the UI and not the official rancher/ui branch. 
What would be the additional step required for the above?

**Comment by superseb** [comment]
Just ran a build on a clean environment and it doesn't error. Seeing `curl: (3) malformed`, something went wrong with the hook script in the unittest plugin. You can add `--debug` to the helm plugin install command in `Dockerfile.dapper` to get more info what's going wrong.

Let me know if you still see an issue which is related to this repository.

Regarding UI, this was answered on Slack, you can configure Rancher to point to a different UI source using `ui-index` or you can manually run the UI and point it to a running Rancher as described in https://github.com/rancher/ui

**Comment by saiyam1814** [comment]
yes , some problem with my mac I guess, on a plain ubuntu instance I was able to build it successfully. Thanks
