### ISSUE TITLE
[UI] Node Templates - When edit a Linode node template, cloud credential(s) are not found

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21652]
Version: master-head (v2.3) (7/19/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a Linode Cloud Credential
- Create a Linode node template that uses this cloud credential
- Edit the Linode node template

**Result:**
When you edit the existing Linode node template, the UI will ask you to create your first Linode cloud credential - but we already have one?

**Comment by tfiduccia** [comment]
Now it's showing all credentials, not just the linode ones.

![image.png](https://zube.io/files/rancher/32999daabaae05d1717969eb76a0ea4d-image.png)

**Comment by loganhz** [comment]
This need to be fixed in `https://github.com/linode/rancher-ui-driver-linode` repo

We need to extend the NodeDriver mixin or do something similar with https://github.com/rancher/ui/blob/master/lib/shared/addon/mixins/node-driver.js#L238

cc @deniseschannon @phillc

**Comment by phillc** [comment]
This should be fixed with a combination of https://github.com/rancher/rancher/issues/21838 and v0.3.0-alpha.3 of https://github.com/linode/rancher-ui-driver-linode

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/14/19)

I followed the steps to reproduce. Upon editing the Linode nodeTemplate, I encounter no issues now. Only any linode cloud credentials are listed for me to pick from and I can properly edit the node tempalte and leverage it after edit without any issues.

![image](https://user-images.githubusercontent.com/45179589/63066351-8111c580-bebe-11e9-97f6-cbdd99bbdcdc.png)
