### ISSUE TITLE
Feature request: Terraform support for enabling monitoring, setting up alerting

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21655]
Rancher version:
v2.2.3

Type:
RFE

Description:
We use Terraform to bring up all of our cloud infra and configure a new cluster via the Rancher terraform provider. It works great until you try to configure some of the finer details. Enabling monitoring to get Grafana metrics, as well as configuring alerts, is not supported by the Terraform provider.

This would be valuable, as our goal is to configure the cluster entirely without going into the Rancher UI.

**Comment by walkafwalka** [comment]
I suggest you post this request here: https://github.com/terraform-providers/terraform-provider-rancher2
