### ISSUE TITLE
The namespace does not automatically inherit the container resource limit of the project configuration.

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#21664]
Steps：

1、Create a project and set container resource limits
![image](https://user-images.githubusercontent.com/16741882/61576984-026e7600-ab14-11e9-9af6-e170f484ab01.png)
2、Create a namespace in the project
![image](https://user-images.githubusercontent.com/16741882/61576996-1fa34480-ab14-11e9-9d4e-d4cc77c4a4bf.png)
It can read this limit value, but it does not take effect after saving.

3、Edit it

![image](https://user-images.githubusercontent.com/16741882/61577016-495c6b80-ab14-11e9-9712-9d1c54619724.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.5` UI: `v2.2.89` |
|Route|`authenticated.cluster.projects.index`|

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.6

I followed the reproduction steps:
- Create a project, set a CPU limit (any value)
![image](https://user-images.githubusercontent.com/45179589/61970887-9320d800-af92-11e9-99dc-7e9a5deaa194.png)
- Create a namespace in the project, note it looks like we inherited the CPU limit
![image](https://user-images.githubusercontent.com/45179589/61970941-a9c72f00-af92-11e9-807b-08405aea2235.png)
NOTE: http is incorrect, resourceQuota is null
- Edit the NS, our CPU Limit is missing:
![image](https://user-images.githubusercontent.com/45179589/61971028-d11dfc00-af92-11e9-821c-4d50ba680d93.png)


**Validation:**
master-head (v2.3) (7/26/19)

- Follow the steps again to reproduce.
- When we create the namespace in the project, http is now correct, we requested setting CPU limit.
![image](https://user-images.githubusercontent.com/45179589/61971093-15a99780-af93-11e9-94b3-196300b49b33.png)

(This was not working before)
- Edit the NS and we can now see our CPU limit:
![image](https://user-images.githubusercontent.com/45179589/61971120-24904a00-af93-11e9-9499-856249ac1f8c.png)

API appears correct as well.
- Try to create a workload, requesting greater than limit of CPU. This does not work (as expected). This ensures our limit works.
