### ISSUE TITLE
UI for Azure China AKS Integration Support

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#21668]
UI ticket for https://github.com/rancher/rancher/issues/20881

1. For AKS clusters, add two options in the region list: China East 2(chinaeast2) and China North 2(chinanorth2) which are the current supported two in Azure China Cloud. When they are selected, pass the following fields in azureKubernetesServiceConfig:
```
baseUrl: https://management.chinacloudapi.cn/
authBaseUrl: https://login.chinacloudapi.cn/
```
2. UI should disable `HTTP Application Routing` configuration for these regions as it is not supported there.
3. UI should talks to the above endpoint when validating credentials for Azure China Cloud.

For reference: https://github.com/Azure/azure-cli/blob/24119559d134d9e6bd2317c3af4c28847b20de9f/src/azure-cli-core/azure/cli/core/cloud.py#L177

**Comment by gitlawr** [comment]
References for testing:
https://docs.azure.cn/zh-cn/aks/kubernetes-walkthrough
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/aks/

**Comment by davidnuzik** [comment]
I'm sorry @gitlawr @loganhz for the late notice. I tried and we aren't allowed to create AKS in these regions. Is this something your team might be able to validate?

![Screen Shot 2019-08-14 at 4 02 14 PM](https://user-images.githubusercontent.com/45179589/63062306-43587100-bead-11e9-951f-f3000154a9f2.png)

**Comment by loganhz** [comment]
sure. thanks

**Comment by kingsd041** [comment]
Version: master master-head (8/29/19)
Passed the following test cases:
1. Ensure that the cluster can be successfully created in `China North 2` and `China East 2`region
2. Create a workload in the cluster and create a nodeport to ensure access to the workload via nodeport
3. Ensure the L4 Balancer and storage class are available
4. Modify the cluster
