### ISSUE TITLE
In UI, volume management display incorrect.

### ISSUE THREAD

**Issue by gmle** [rancher/rancher#21669]
I used kubectl create a longhorn class, and I create a pvc volume.
When I checked volume management on Rancher2, the volume plugin name did not display correctly.
And in plugin configuration，No plugins are select.
So I don't change this pvc volume.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.5` UI: `v2.2.89` |
|Route|`authenticated.cluster.storage.persistent-volumes.detail.index`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24665
