### ISSUE TITLE
Setup Rancher 2.2.4 HA failed.Clone failed: Cloning into 'management-state/catalog-cache

### ISSUE THREAD

**Issue by nuaaparnec** [rancher/rancher#21673]
docker version:
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:24:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:25:33 2019
  OS/Arch:          linux/amd64
  Experimental:     false
OS: centos 7.5
HELM vesion:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

I have 3 nodes to set up the rancher cluster. The 3 nodes are in the isolated network,and cannot access to the internet. 
Command to set up the rancher is :
helm install ./rancher \
    --name rancher \
    --namespace cattle-system \
    --set hostname=rancher.ctyun.com \
    --set ingress.tls.source=secret \
    --set auditLog.level=3 \
    --set auditLog.destination=hostPath \
    --set auditLog.hostPath=/opt/rancher/auditlogs/ \
    --set auditLog.maxAge=20 \
    --set auditLog.maxBackups=20 \
    --set auditLog.maxSize=100 \
    --set privateCA=true \
    --set rancherImage=rancher/rancher
The error logs show below:
2019/07/22 10:27:47 [DEBUG] REST UPDATE apis/management.cattle.io/v3//catalogs/system-library
2019/07/22 10:27:47 [ERROR] CatalogController system-library [catalog] failed with : Clone failed: Cloning into 'management-state/catalog-cache/2284e9d6c1e82c5a56a5cb7c1d5c0144835734b1b66da6f75122d99c7989618f'...
fatal: unable to access 'https://git.rancher.io/system-charts/': Could not resolve host: git.rancher.io
: exit status 128
2019/07/22 10:27:49 [INFO] Received SIGTERM, cancelling
2019/07/22 10:27:49 [FATAL] leaderelection lost for cattle-controllers

**Comment by dinhanhhuy** [comment]
Up, still get this error

**Comment by superseb** [comment]
Air gap install is described at https://rancher.com/docs/rancher/v2.x/en/installation/air-gap/install-rancher/ and the system charts are bundled since v2.3.0. Lower versions have to follow https://rancher.com/docs/rancher/v2.x/en/installation/options/local-system-charts/#setting-up-system-charts-for-rancher-prior-to-v2-3-0.

Let me know if this doesn't work.
