### ISSUE TITLE
Adding a new cluster template revision and saving fails

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21679]
Version: master-head
Steps:
1. Create a cluster template and template revision through UI
2. Add another revision by changing one of the parameters and hit the "Save" button

It fails with the below error :

![Screen Shot 2019-07-22 at 10.31.10 AM.png](https://zube.io/files/rancher/e429032e2cf6747c777bfa5ac4a160ea-screen-shot-2019-07-22-at-10-31-10-am.png)

**Comment by davidnuzik** [comment]
A JS error also happens when click on Cancel button. The template will actually create, just doesn't appear to when Save.

**Comment by davidnuzik** [comment]
Version: master-head (7/23/19)

This issue is no longer occurring, I am successfully able to clone a template revision and save. 
I can leverage the saved template as well and it will work correctly.
