### ISSUE TITLE
UI: Add force deletion option

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#21672]
UI ticket for https://github.com/rancher/rancher/issues/17823

1. Add a force deletion option to the confirmation dialog when deleting a pod.
2. Give a warning to the users if the option is selected.

for [reference](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#delete)
>IMPORTANT: Force deleting pods does not wait for confirmation that the pod's processes have been terminated, which can leave those processes running until the node detects the deletion and completes graceful deletion. If your processes use shared storage or talk to a remote API and depend on the name of the pod to identify themselves, force deleting those pods may result in multiple processes running on different machines using the same identification which may lead to data corruption or inconsistency. Only force delete pods when you are sure the pod is terminated, or if your application can tolerate multiple copies of the same pod running at once. Also, if you force delete pods the scheduler may place new pods on those nodes before the node has released those resources and causing those pods to be evicted immediately.

3. Send deletion request to the API with query `gracePeriodSeconds=0` if the option is selected.
Example:
```
curl -u "$token" \
-X DELETE \
-H 'Accept: application/json' \
'https://rancher-url/v3/project/local:p-sm4qt/pods/default:ngx-69b8cc5456-79g27?gracePeriodSeconds=0'
```

**Comment by davidnuzik** [comment]
@tfiduccia could you review. Is this going to be okay to add in the UI?

![image](https://user-images.githubusercontent.com/45179589/63199240-17b2c380-c032-11e9-92b8-a8e6f61d0dea.png)

**Comment by tfiduccia** [comment]
@davidnuzik - No, I think we can improve on that.  I'll take a look and modify it.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/20/19)

This adds an option to force deletion of a pod. Reference #17823 as well which executed additional testing. This test just ensures that the option is added to the UI and work as expected.

Screenshot of delete pod modal (default option is of course that "Force Delete" is NOT checked)
![image](https://user-images.githubusercontent.com/45179589/63374694-33261300-c33f-11e9-8970-75fdf21ceea6.png)

When you check the checkbox for "Force Delete" the UI pops up this warning ribbon:
![image](https://user-images.githubusercontent.com/45179589/63374789-623c8480-c33f-11e9-8964-c85e0afb3b3e.png)

The difference between these two options, is that when you check (enable) "Force Delete" the UI also includes an argument of `gracePeriodSeconds=0`
![Screen Shot 2019-08-20 at 11 42 09 AM](https://user-images.githubusercontent.com/45179589/63374949-afb8f180-c33f-11e9-9c99-9e7c6b603fed.png)

The screenshot shows the difference. When you do NOT "Force Delete" we simply don't include the gracePeriodSeconds query param.

Deletion is successful both with and without Force Delete chosen. Again reference #17823 for additional tests/notes.
