### ISSUE TITLE
[s3 backup] etcd snapshots not ever created and/but not uploaded to s3 storage

### ISSUE THREAD

**Issue by ChrisHaPunkt** [rancher/rancher#21675]
**What kind of request is this (question/bug/enhancement/feature request):**
~~Bug~~ Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Create a Rancher custom cluster
2. Setup minio in rancher custom cluster
2. Enable and configure s3 backup config (minio s3) with self signed cert
3. Trigger snapshot from UI

**Result:**
TL;DR
Problem is the rke-tools log output from the container on the local host performing the etcd backup task. The logs are not propagated to a visible log collector (rancher logs for example), maybe this is due to "info" level for an error. And if the Backups fails, there is no indication that there was a problem (could not be uploaded, local storage full, ...)

>  sudo docker logs -f etcd-snapshot-once
> time="2019-07-22T14:40:26Z" level=info msg="Initializing Rolling Backups" creation=12h0m0s retention=72h0m0s
> time="2019-07-22T14:40:26Z" level=info msg="invoking set s3 service client"
> time="2019-07-22T14:40:26Z" level=warning msg="Backup failed" attempt=1 data="Error:  write /backup/c-8k8lp-ms-dq2mx.part: no space left on device\n" error="exit status 5"

Default Ingress-controller -> 413 Request Entity Too Large, retried 3 times
Problem resolved:
Increase client-max-bodysize

> time="2019-07-22T14:00:57Z" level=info msg="failed to upload etcd snapshot file: 413 Request Entity Too Large, retried 3 times"

### Rancher Logs:
No snapshot uploaded to s3.

> 2019/07/22 12:58:25 [INFO] Starting saving snapshot on etcd hosts
> 2019/07/22 12:58:25 [INFO] [dialer] Setup tunnel for host [10.45.51.130]
> 2019/07/22 12:58:25 [INFO] [etcd] Saving snapshot [c-nb4mv-ms-pvzdr] on host [10.45.51.130]
> 2019/07/22 12:58:25 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host [10.45.51.130]
> 2019/07/22 12:58:25 [INFO] Waiting for [etcd-snapshot-once] container to exit on host [10.45.51.130]
> 2019/07/22 12:58:25 [INFO] Container [etcd-snapshot-once] is still running on host [10.45.51.130]
> 2019/07/22 12:58:26 [INFO] Waiting for [etcd-snapshot-once] container to exit on host [10.45.51.130]
> 2019/07/22 12:58:26 [INFO] kontainerdriver rancherkubernetesengine stopped
... No more events and no backup is placed on s3 endpoint.

**Other details that may be helpful:**

If we misconfigure the s3 config (like giving a non existing bucket name) the following appears in the log file after trigger:

> 2019/07/22 12:58:32 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10341
> 2019/07/22 12:58:32 [INFO] Starting saving snapshot on etcd hosts
> 2019/07/22 12:58:32 [INFO] [dialer] Setup tunnel for host [10.45.51.130]
> 2019/07/22 12:58:32 [INFO] [etcd] Saving snapshot [c-nb4mv-ms-pvzdr] on host [10.45.51.130]
> 2019/07/22 12:58:32 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host [10.45.51.130]
> 2019/07/22 12:58:32 [INFO] Waiting for [etcd-snapshot-once] container to exit on host [10.45.51.130]
> 2019/07/22 12:58:32 [INFO] Container [etcd-snapshot-once] is still running on host [10.45.51.130]
> 2019/07/22 12:58:33 [INFO] Waiting for [etcd-snapshot-once] container to exit on host [10.45.51.130]
> 2019/07/22 12:58:33 [INFO] kontainerdriver rancherkubernetesengine stopped
> 2019/07/22 12:58:33 [WARNING] Failed to take one-time snapshot, exit code [1]: time="2019-07-22T12:58:32Z" level=fatal msg="faield to set s3 server: bucket backups-test is not found"
> 2019/07/22 12:59:06 [ERROR] EtcdBackupController c-nb4mv/c-nb4mv-ms-pvzdr [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: Failed to take one-time snapshot, exit code [1]: time="2019-07-22T12:59:05Z" level=fatal msg="faield to set s3 server: bucket backups-test is not found"

So the configuration seems correct, and it's checking the connection after the creation of the local snapshot. But the sebsequently upload is not happening.

### S3 Server Incoming Requests

Only a HEAD Request appearing, no PUT event.

> minio-s3-server-3.[strip-dns].cluster.local [REQUEST s3.HeadBucket] [13:32:04.32177]
> minio-s3-server-3.[strip-dns].cluster.local HEAD /backups/
> minio-s3-server-3.[strip-dns].cluster.local Host: minio.infra.paas.rewe.local
> minio-s3-server-3.[strip-dns].cluster.local Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20190722/rz-koeln-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=4a5b02a22c7bdffdd967970748b5a7f9af7451077142d713be9c0768bd0972be
> minio-s3-server-3.[strip-dns].cluster.local X-Forwarded-For: 10.62.43.155
> minio-s3-server-3.[strip-dns].cluster.local X-Forwarded-Host: minio.infra.paas.rewe.local
> minio-s3-server-3.[strip-dns].cluster.local X-Real-Ip: 10.62.43.155
> minio-s3-server-3.[strip-dns].cluster.local X-Scheme: https
> minio-s3-server-3.[strip-dns].cluster.local Content-Length: 0
> minio-s3-server-3.[strip-dns].cluster.local X-Amz-Date: 20190722T133204Z
> minio-s3-server-3.[strip-dns].cluster.local X-Forwarded-Proto: https
> minio-s3-server-3.[strip-dns].cluster.local X-Request-Id: 3a9123a0e4e6d11e60d0d7cc7d03ee3d
> minio-s3-server-3.[strip-dns].cluster.local User-Agent: Minio (linux; amd64) minio-go/v6.0.10
> minio-s3-server-3.[strip-dns].cluster.local X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> minio-s3-server-3.[strip-dns].cluster.local X-Forwarded-Port: 443
> minio-s3-server-3.[strip-dns].cluster.local X-Original-Uri: /backups/
> minio-s3-server-3.[strip-dns].cluster.local
> minio-s3-server-3.[strip-dns].cluster.local [RESPONSE] [13:32:04.32915]
> minio-s3-server-3.[strip-dns].cluster.local 200 OK
> minio-s3-server-3.[strip-dns].cluster.local X-Amz-Bucket-Region: rz-koeln-1
> minio-s3-server-3.[strip-dns].cluster.local X-Amz-Request-Id: 15B3BDEDB81DE669
> minio-s3-server-3.[strip-dns].cluster.local X-Xss-Protection: 1; mode=block
> minio-s3-server-3.[strip-dns].cluster.local Accept-Ranges: bytes
> minio-s3-server-3.[strip-dns].cluster.local Content-Length: 0
> minio-s3-server-3.[strip-dns].cluster.local Content-Security-Policy: block-all-mixed-content
> minio-s3-server-3.[strip-dns].cluster.local Server: MinIO/RELEASE.2019-07-17T22-54-12Z
> minio-s3-server-3.[strip-dns].cluster.local Vary: Origin
> minio-s3-server-3.[strip-dns].cluster.local
> minio-s3-server-3.[strip-dns].cluster.local

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.5
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.14.3

- Docker version (use `docker version`):

```
ce - 18.6.3
```

gz#11037

**Comment by panlith** [comment]
Setting `proxy-body-size` does the trick

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md

https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/#configuring-nginx-ingress-controller
