### ISSUE TITLE
Istio UI design review

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#21688]
** Statement **
Istio is new UI and we need to review the design of the Enable/Disable page and the Istio Graph/Metrics page.

**Comment by loganhz** [comment]
FYI, We have some PRs for Istio not merged yet. cc @deniseschannon @vincent99 

```
#### Istio

* https://github.com/rancher/system-charts/pull/69
* https://github.com/rancher/system-charts/pull/72
* https://github.com/rancher/rancher/pull/21544
* https://github.com/rancher/rancher/pull/21549
* https://github.com/rancher/types/pull/909
* https://github.com/rancher/ui/pull/3132
```

**Comment by tfiduccia** [comment]
A couple of things:

- [ ] The expand/collapse is set to "Expand All" when I go to the page, even thou all the accordions are already expanded.  We either need to have all expect Member Access collapsed or change the Expand All to Collapse All.
![image](https://user-images.githubusercontent.com/11514927/62565714-3fd54200-b83c-11e9-855c-c528f78433e0.png)

- [ ] Remove "Cancel" button from bottom of page.  This is not a "Add" page or a modal.  The only to and from this page should be from the menu.
![image](https://user-images.githubusercontent.com/11514927/62565568-ea993080-b83b-11e9-945a-e444700b2baa.png)

- [ ] I really don't care for the Disable button on top?  It should be on the bottom with Save?  Or we need to find another say to have the different options.  "Enable/Disable", "Save" & "Revert to defaults".
![image](https://user-images.githubusercontent.com/11514927/62565842-87f46480-b83c-11e9-897b-eb9c625062ca.png)

- [ ] "Show advanced options" only has 1 thing?  I almost feel like we should just have it there all the time with it's own accordion or something?
![image](https://user-images.githubusercontent.com/11514927/62565420-97bf7900-b83b-11e9-9295-ad7f080104c5.png)
![image](https://user-images.githubusercontent.com/11514927/62565445-a0b04a80-b83b-11e9-8d34-379728e2903f.png)

**Comment by davidnuzik** [comment]
If we change the disable button location we need to change it in ALL areas. Global Registry, monitoring, Auth, etc.

**Comment by tfiduccia** [comment]
@davidnuzik - Yes, I would like to change it for all the pages.

**Comment by loganhz** [comment]
Please raise another issue for re-locating the disable button for auth as it's a bit complicated. I will change the location for disable buttons for Istio and Monitoring in this issue.

**Comment by tfiduccia** [comment]
Version - 8/8 master
Verified fixed!  Thanks @loganhz
