### ISSUE TITLE
ADFS SAML config No Key Found error

### ISSUE THREAD

**Issue by MaxDiOrio** [rancher/rancher#21687]
Just set up a new test version of Rancher using the 2.3 alpha 5 branch.  Trying to get ADFS configured.  Set up everything in ADFS fine.  Went to go enable it in Rancher config, configure it all - create a new self-signed private key and certificate for the server domain name and get the following error:

{"baseType":"error","code":"ServerError","message":"SAML: no key found","status":500,"type":"error"}

The key is correct for the certificate, and I made sure it was in RSA format as well.

**Comment by MetalJacx** [comment]
Did you ever solve this running into this issue
