### ISSUE TITLE
Backport: etcd rolling backup naming scheme

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21697]
Backport https://github.com/rancher/rancher/issues/20819

**Comment by sowmyav27** [comment]
verified on v2.2-head - commit id - 81b4458b - (07/25/2019)
UI tag `2.2.91`
S3 backups on the UI are seen as below. -ms- - manual backups and -rs- is for recurring snapshots
On the UI:
<img width="716" alt="Screen Shot 2019-07-25 at 11 51 32 AM" src="https://user-images.githubusercontent.com/26032343/61900594-bdab5c00-aed2-11e9-804a-042b6a0f6b73.png">

Amazon S3
<img width="1404" alt="Screen Shot 2019-07-25 at 11 52 35 AM" src="https://user-images.githubusercontent.com/26032343/61900598-c0a64c80-aed2-11e9-9783-3470d0e9dcab.png">

Local backups on the UI are seen as below. -ml- - manual backups and -rl- is for recurring snapshots
On UI
<img width="730" alt="Screen Shot 2019-07-25 at 11 51 47 AM" src="https://user-images.githubusercontent.com/26032343/61900607-c56b0080-aed2-11e9-8752-070d82d48052.png">


On etcd node:
<img width="733" alt="Screen Shot 2019-07-25 at 11 49 16 AM" src="https://user-images.githubusercontent.com/26032343/61900615-ca2fb480-aed2-11e9-9049-7e51cf60ef0f.png">
