### ISSUE TITLE
[API] Cluster Templates - Growl error when attempt disable revision in use is confusing

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21698]
This is a minor issue, but is a nice-to-have for v2.3. I think it will help to make the message more clear.

Version: master-head (7/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster tempalte with one revision.
- Leverage the template to create a cluster.
- Either while the cluster is still provisioning or is fully ready, in the UI attempt to disable this (in-use) cluster template revision.

**Result:**
You will get an error message like this:
![image](https://user-images.githubusercontent.com/45179589/61673520-a4bd6380-aca4-11e9-9f8c-0f6917637bec.png)
The wording is confusing to me. I expected to see something more like:
`Cannot disable the clusterTemplateRevision until any clusters are no longer using it`
(or if need to be more generic, change 2nd word form "disable" to "update")

**Comment by prachidamle** [comment]
This should not apply any longer when this change is in: https://github.com/rancher/rancher/issues/22371

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/29/19)

Now there is no error message shown at all when you disable a CT that is currently in use (cluster provisioning).

There is also no error when the cluster is fully active and then you disable.
