### ISSUE TITLE
Backport: Ability to set s3 backup path

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21696]
Backport: https://github.com/rancher/rancher/issues/20859

**Comment by sowmyav27** [comment]
verified on `v2.2-head` - commit id - `81b4458b` - (07/25/2019)
**Scenario#1**

1. Deploy an AWS cluster - 1 etcd, 1 control plane and 1 worker nodes with S3 backups enabled.
2. Enter S3 bucket-name, S3 folder, S3 Region Endpoint, S3 Access Key and S3 Secret key while configuring the cluster. (S3 bucket and the sub-folder in that bucket be created prior to this step)
3. Verified that the recurring snapshots and manual snapshots are taken and backed up in the given S3 targets.
4. Restore from these snapshots also work.

**Scenario#2**

1. Deploy an AWS cluster - 1 etcd, 1 control plane and 1 worker nodes with S3 backups enabled.
2. Enter S3 bucket-name, S3 folder, S3 Region Endpoint, S3 Access Key and S3 Secret key while configuring the cluster. (S3 bucket be created prior to this step. NO folder has been created in the bucket)
3. Verified that the recurring snapshots and manual snapshots are taken and backed up in the given S3 targets.
4. A new folder is seen created in the bucket with the name as given in `S3 folder`. And the snapshots are stored here.
5. Restore from these snapshots also work.

**Scenario#3**

1. S3 Bucket name and folder name given are the same while configuring the cluster. 
2. Verified that the recurring snapshots and manual snapshots are taken and backed up in the given S3 targets.
3. Restore from these snapshots also work.

**Scenario#4**

1. S3 folder - with special characters e.x. `&` work similarly as the previous scenarios.
2. Verified that the recurring snapshots and manual snapshots are taken and backed up in the given S3 targets.
3. Restore from these snapshots also work.
