### ISSUE TITLE
Cleaning up etcd snapshots after backup/restore operations

### ISSUE THREAD

**Issue by OlliL** [rancher/rancher#21703]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):**
- Activate S3 for etcd Backups
- Backup
- Restore

**Result:**
- after the Backup is done and is uploaded into S3, the Backups is still kept in the local filesystem.
- on Restore: the Backup is downloaded from S3 and after the Restore is done, the ZIP-file also remains in the local filesystem
- I would expect that the ZIP files are removed once S3 is enabled and after they where uploaded to S3 as well as after a restore is done.

**Other details that may be helpful:**

**Environment information**
- Rancher 2.2.5

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/21702:

Uncompressed file are left behind after restore

**Comment by OlliL** [comment]
It's of course OK for me when you merge both issues - I just thought the one is S3 related and the other (uncompressed file is left behind) is not related to S3

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/21710
