### ISSUE TITLE
kubelet and kube-proxy do not restart to apply changes after rotating certificates

### ISSUE THREAD

**Issue by canhnt** [rancher/rancher#21709]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
K8s clusters:
- v1.13.4
- v1.12.3
- v1.11.2

Rotate certificates with the option `Rotate all service certificates` to above clusters before their certs are expired.

**Result:**
- Certs are rotated in all nodes: (expected)
- K8s components in master nodes are restarted (expected).
- K8s components (kubelet, kube-proxy) in worker nodes are not restarted, they still use the old certs (unexpected).

Consequent: on the expiration date, worker nodes become NotReady due to authorization errors. 

Restarting kubelet and kube-proxy fixed the problem.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): mentioned above

```
(paste the output here)
```

- Docker version (use `docker version`): 

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
Please check https://github.com/rancher/rancher/issues/20381#issuecomment-498383136 to see if that applies to the situation

**Comment by canhnt** [comment]
Thanks for your referencing, it related. #20318 covered two cases mentioned in https://github.com/rancher/rancher/issues/20381#issuecomment-498383136

However I think this issue is another use-case:
```
* Cluster got created on a) 2.0.13 or earlier on 2.0 release line and its certs are *not* expired while being on that version.
* The setup is upgraded to 2.2.x before expiration date.
* Try to rotate the certs on the cluster, rotation was successful partly as described in the first post.
```

**Comment by superseb** [comment]
Let me know if this still happens on the latest release.
