### ISSUE TITLE
decompressed etcd backups not removed on restore

### ISSUE THREAD

**Issue by OlliL** [rancher/rancher#21702]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
- Backup etcd via UI
- Restore etcd via UI

**Result:**
- the decompressed file is kept in the filesystem after the restore is done
- Expectation: The decompressed file should be removed after the restore ended
```
root@host (host) [/opt/rke/etcd-snapshots]
# ls -l
total 18328
-rw-r--r--. 1 root root 13422624 Jul 23 08:39 c-nb4mv-rs-8ts89
-rw-------. 1 root root  5340711 Jul 23 08:39 c-nb4mv-rs-8ts89.zip
```

**Other details that may be helpful:**

**Environment information**
Rancher 2.2.5

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/21703
