### ISSUE TITLE
Add ability to assign annotations & labels to a cluster, project, nodes and namespaces

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21700]
**What kind of request is this:**
Feature request

**Rancher version:**
v2.2.4

**Description:**
This is not supported in the main GUI.  But it is currently supported in API.  Able to crud them by clicking on the "View in API" of the desired cluster, making changes and clicking save.

In addition to clusters, it would also be nice if the UI also let you assign annotations and labels to projects and namespaces.

**Likely related ticket:**
https://github.com/rancher/rancher/issues/16881

**Comment by sowmyav27** [comment]
Verified on `master-head`.
Annotations are not available for `Projects`. Reopening the issue.

**Comment by sowmyav27** [comment]
verified on master-head Commit id: `85dedb19b`

**Scenario#1**
Setting labels and annotations on clusters

- User is able to set labels and annotations while creating a cluster on the UI
<img width="1230" alt="Screen Shot 2019-08-21 at 10 58 37 AM" src="https://user-images.githubusercontent.com/26032343/63455953-b2304f80-c402-11e9-9502-8c6939698c08.png">

- Labels and annotation set are available on the management plane of rancher server - `kubectl get clusters <cluster-id> -o yaml`
- User is able to unset labels and annotations and they are NOT seen in the management plane when queried for in the cluster yaml.

**Scenario#2**
Setting labels and annotations on projects

- User is able to set labels and annotations on a Project from the UI
- Labels and annotation set are available on the management plane of rancher server - `kubectl get project <project-id> -n <cluster-id> -o yaml`
- User is able to unset labels and annotations and they are NOT seen in the management plane when queried for.

**Scenario#3**
Setting labels and annotations on namespaces

- User is able to set labels and annotations on a namespace from the UI.
- Labels and annotation set are available in the object in cluster - `kubectl get namespace <namespace> -o yaml`.
- User is able to unset labels and annotations and they are NOT seen on the object.

**Scenario#4**
Setting labels and annotations on nodes
- User is able to set/unset labels on the nodes.
- Can verify on the cluster kubectl - `kubectl get nodes <node-name> -o yaml`
- Issue while setting annotations on nodes - tracked in this issue - https://github.com/rancher/rancher/issues/22328
