### ISSUE TITLE
etcd backup restore - unzipped files during restore local snapshot are not deleted after restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21710]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. On `rancher:master-head` deploy a cluster and have local snapshots enabled(by default it is).
2. Take a manual snapshot.
3. a zip file corresponding to the snapshot is stored on the etcd.
4. Restore from the snapshot.

**Expected Result:**
The cluster should go into `Updating` state and turn to `Active` when the restore has been completed. 
There should be no additional files created on the etcd node. 

**Actual Result:**
The cluster goes into `Updating` state and turns to `Active` when the restore has been completed. 
unzipped version of the snapshot file is generated on the etcd node in 

<img width="614" alt="Screen Shot 2019-07-23 at 9 40 59 AM" src="https://user-images.githubusercontent.com/26032343/61735055-01b62980-ad38-11e9-81cd-e8cc39a1d928.png">

**Note:**
This is not the case when S3 snapshots are enabled. No additional files are created after restoring from the S3 stored snapshots.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master-head
- Installation option (single install/HA): single

**Comment by OlliL** [comment]
This was also reported with #21702

**Comment by superseb** [comment]
Both cases need to be validated after a fix has been made.
