### ISSUE TITLE
Support for generic HAProxy config

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2171]
Rancher supports specific HAProxy config such as SSL term, virtual host, etc.  Rancher should be able to a method of allowing generic configuration of HAProxy assuming the user knows how to modify the config files.  This could simply be a form of uploading the config files.

**Comment by alena1108** [comment]
@will-chan is it the same request as https://github.com/rancher/rancher/issues/1871? If yes, then it would be a bit harder than just uploading the config as some parameters are actually defined in the sections formed only when services get linked to the LB. The haproxy config consists of following sections:

* defaults
* frontend - (n) number of them can be defined. Each frontend is uniquely identified by listener port/protocol, and this is the section where hostname routing rules and backend reference(s) are defined.
* backend - (n) number of them can be defined. Container ips are represented here

Having custom "defaults" section is easy as this section is pretty much static. The rest would require more elaborate design discussion. I'll keep this ticket up with updates.

**Comment by will-chan** [comment]
Closing this as a duplicate of #1871
