### ISSUE TITLE
Provide option to view the cluster template revision

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21716]
Version: Master-head

Steps
1. As global admin, create cluster template and template revision. 
We need an option to view the template revision so that the creator and anyone who uses the template revision can see the selections  made.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/12/19)

You can now click on the name of the CTR to get a "detail" view much like viewing details of a workload, pod, etc. This is a read-only view that lets us see what is set for the cluster template revision.

I believe the intent of adding this enhancement was so a user may review and see how the cluster template is set up before leveraging the template. I had expected when viewing the details of a CTR to be able to tell what fields do or do not have an override associated with them, but you can't tell what has an override or not in this view. Overrides seem to be important to be able to know so I think the detail view should show what has overrides and what does not.

As such, I'd like to reopen the issue and see if we can add this in. I'm not certain how we could visually show if a field has an override or not. Perhaps the override toggle switches need to be shown but not be interactive.

**Comment by deniseschannon** [comment]
@davidnuzik can you create a new issue for the enhancement to be able to see the override options in the template revision from this view? and then we can close this original issue.

**Comment by davidnuzik** [comment]
@deniseschannon thanks; I created a separate issue to track that: https://github.com/rancher/rancher/issues/22183

I am going to close the issue based on my testing performed earlier. I wasn't able to spot any other issues during my testing 8/12. Reference my last comment https://github.com/rancher/rancher/issues/21716#issuecomment-520548709
