### ISSUE TITLE
When launch Kubectl in UI or view logs, WebSocket reports 403 error

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21712]
Version: master-head (7/22/19) and (7/23/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to open kubectl for a cluster in the UI as admin
- Try to view pod/container logs as admin

**Result:**
The WS will fail to open with error 403 (Forbidden)
`component.js:119 WebSocket connection to 'wss://RancherServerURLHere/v3/clusters/c-6mpwt?shell=true' failed: Error during WebSocket handshake: Unexpected response code: 403`

No errors in rancher server logs.
Single-node install.

**Comment by alena1108** [comment]
I don't think it's a UI issue

**Comment by sowmyav27** [comment]
verified on rancher - master-head(yesterday's)
Not able to launch kubectl for all versions of supported k8s version - 1.15, 1.14 and 1.13

**Comment by davidnuzik** [comment]
Version: master-head (7/26/19)

I am no longer observing the issue. I tested with launch Kubectl, view pod/container logs, and exec shell into containers. All of these work without any issues. No JS issues and WS messages appear correct.

Smoke tested each and observed no issues.

**Comment by sowmyav27** [comment]
verified on master-head (7/26/2019) - latest
On all k8s version - 1.13, 1.14 and 1.15 - I am able to launch kubectl in the cluster, exec shell on workloads and view logs also work.
