### ISSUE TITLE
Rancher 1.6: performance improvements for lb service metadata generation

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21727]
On metadata reload request for a single LB service, we fetch all the services and stacks for the account which is not optimal:

https://github.com/rancher/cattle/blob/v1.6/code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerInfoDaoImpl.java#L193

And what really these services/stacks are needed for - is for port_name rule generation that use only stack/service names. We should consider storing services/stacks in cache, and fetch the info from there.

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
