### ISSUE TITLE
Backport: Bug: vSphere node provisioning results in x509 error v2.2

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#21729]
https://github.com/rancher/rancher/issues/21306

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2-head a031c2f5 7/29

* The iso downloads successfully, but the cluster fails to provision with error: `Error creating machine: Error running provisioning: error selecting docker: (ssh command error:`

```2019/07/29 20:17:12 [INFO] stdout: Provisioning with rancheros...
2019/07/29 20:17:12 [INFO] Provisioning with rancheros...
2019/07/29 20:17:47 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2019/07/29 20:17:47 [INFO] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2019/07/29 20:17:47 [INFO] stdout:
2019/07/29 20:17:47 [INFO]
2019/07/29 20:17:47 [INFO] Generating and uploading node config brandon-vsphere1
2019/07/29 20:17:48 [ERROR] NodeController c-4qfwf/m-7rclp [node-controller] failed with : Error creating machine: Error running provisioning: error selecting docker: (ssh command error:```

The cluster is able to provision on v2.2.6

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2-head a031c2f 7/29

The above was from an unrelated error with vsphere node template docker engine install version. 

Using the proper UI tag `2.2.92`, the cluster is able to be provisioned with the iso hosted on a server with self-signed certs

* ```docker run -v /root/state:/var/lib/rancher -d -p 80:80 -p 443:443 --restart=unless-stopped -v /root/certs/ca-additional.pem:/etc/ssl/certs/ca-additional.pem  rancher/rancher:v2.2-head```
* Provisioned vsphere cluster with rancheros iso coming from self-hosted webserver
* Cluster provisions successfully
