### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by jas99** [rancher/rancher#2172]
Wanna run following image.
https://hub.docker.com/r/kaixhin/cuda/
I want to run cuda. I can choose can ami with cuda driver running but still need device tags.
1: It will be great if i can ssh in the host from UI itself
2: Provide a way to add misc. args to the docker command from ui.

take care 
Thx

**Comment by jas99** [comment]
Hey SOS :P
Ability to pass addition misc args to docker run from UI

**Comment by jas99** [comment]
@will-chan relp :)

**Comment by vincent99** [comment]
Device binding is under the Security/Host section, do you need something else?

![image](https://cloud.githubusercontent.com/assets/753917/10177071/1457259c-66ad-11e5-948a-e69fd9b333c1.png)

**Comment by jas99** [comment]
@vincent99 Oops missed that. Thx :)
