### ISSUE TITLE
The Rancher always restart， it can't work, why

### ISSUE THREAD

**Issue by arrowfeng** [rancher/rancher#21736]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
I follow offical document to deploy rancher HA
**Result:**
three rancher always restart

**Other details that may be helpful:**
![image](https://user-images.githubusercontent.com/20623365/61759304-ae58df80-adfa-11e9-835e-ba7c9deb17b6.png)
three rancher's log as follow:
![image](https://user-images.githubusercontent.com/20623365/61759366-cfb9cb80-adfa-11e9-9c6c-41992106c7a9.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.2.6,v2.2.5,v2.2.4, i both try it.
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
- Custom
- kubernetes1.13.5
```

- Docker version (use `docker version`):
```
18.9.8
```

**Comment by ajax-2** [comment]
Hello, I think this is a yail error, in my rancher, I only have one container, maybe you can delete the yail or get the detailed log of yail with kubectl -ncattle-system logs -f rancher-xxxx -c jail (or Other name)
 
Racher-1[image](https://user-images.githubusercontent.com/29370146/61760217-6be4d200-adfd-11e9-91fb-82f55639e060.png)

**Comment by arrowfeng** [comment]
Thanks answer, other container is sidecar using to record auditLog,  I also deploy rancher HA without the function of auditLog, but the result is same below.

**Comment by arrowfeng** [comment]
Suddenly received kiiled signal
![image](https://user-images.githubusercontent.com/20623365/61770220-56809f80-ae1f-11e9-83ea-109ded6f75c8.png)

**Comment by happydenn** [comment]
I'm also having similar issue when upgrading from 2.2.4 to 2.2.5 or 2.2.6, getting the same fatal log at the end. Rolling back to 2.2.4 and everything's back to normal.

Interestingly, I've attempted to upgrade 3 clusters and the previous 2 was successfully upgraded and only the third one is having this issue. I can provide more information if needed.

**Comment by dramich** [comment]
@arrowfeng that error is coming from attempting to setup 'jails' for the kontainer-drivers, which happens during startup. The script has 10 seconds to complete before we kill the script. Are you able to see if the jail is getting created at all by looking in the rancher container at the path `/opt/jail` and see if anything is in there?

More details on your host would be helpful as well.
