### ISSUE TITLE
Save grafana dashboard button does not work

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21735]
Type:
Bug

Rancher version:
v2.2.5

Description:
We just upgraded 2.2.4 to 2.2.5, here's what I'm doing that doesn't work.

For whatever reason, I'm able to save reliably by hitting the "ctrl-s" keyboard shortcut, but not with the "save" button in the ui. So, at least I have a workaround.

See this on Firefox 68 on Ubuntu 18.04.  Did not try on other browsers

**Comment by codyrancher** [comment]
I was able to verify that the save button now works in 2.2.5.
![grafana](https://user-images.githubusercontent.com/55104481/68499359-3b8f3b00-0216-11ea-9e31-28df4fbe8209.gif)

**Comment by jiaqiluo** [comment]
Tested the builtin Grafana (template version `v3.8.6`)in both Rancher:`v2.3-head` and `master-head`
Both the saving button and the shortcut `Ctrl + s` work
