### ISSUE TITLE
First DNS queries fail when using CoreDNS

### ISSUE THREAD

**Issue by gwiersma** [rancher/rancher#21742]
**What kind of request is this (bug):**
After the upgrade from rancher 2.2.2 to 2.2.5, we experience a lot of DNS issues in our application. Our application shows a lot of DNS errors like: this host could not be resolved. The problem occurs when resolving external DNS records. 

When a new pod is deployed, the first ping attempts fail. When i ping a second domain that is outside of the Rancher env, coredns is able to resolve the domain. After that the issue does not occur until the App or cordns pod is being redeployed. 

Internal Rancher records work fine (services etc.) 

```
root@worker-64495466ff-gts26:/app# ping external-1.domain.com
ping: external-1.domain.com: No address associated with hostname
root@worker-64495466ff-gts26:/app# ping external-1.domain.com
ping: external-1.domain.com: No address associated with hostname
root@worker-64495466ff-gts26:/app# ping external-1.domain.com^C
root@worker-64495466ff-gts26:/app# ping external-1.domain.com
ping: external-1.domain.com: No address associated with hostname
root@worker-64495466ff-gts26:/app# ^C
root@worker-64495466ff-gts26:/app# ping external-2.domain.com
PING external-2.domain.com (172.20.20.10) 56(84) bytes of data.
64 bytes from 172.20.20.10 (172.20.20.10): icmp_seq=1 ttl=62 time=0.281 ms
^C
--- external-2.domain.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.281/0.281/0.281/0.000 ms
root@worker-64495466ff-gts26:/app# ping external-1.domain.com
PING external-1.domain.com (172.20.20.10) 56(84) bytes of data.
64 bytes from 172.20.20.10 (172.20.20.10): icmp_seq=1 ttl=62 time=0.278 ms
^C
--- external-1.domain.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.278/0.278/0.278/0.000 ms
root@worker-64495466ff-gts26:/app# 
```

**Steps to reproduce (least amount of steps as possible):**
- Deploy a app 
- Try to ping a DNS record outside the rancher cluster
- Error message: No address associated with hostname
- Ping a different DNS record outside of the cluster
- Ping response
- Redeploy app/coredns 
- Issue returns

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): V2.2.5
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.14.3-rancher1-1

- Docker version (use `docker version`): 

```
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54
 Built:             Wed Mar 27 18:34:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment]
Does it happen for every container deployed (excluding a certain OS as base image)? Does rancher containers see the same issue when executed in there? What does the CoreDNS logging show? What does enabling the query logging show? Can you isolate the issue to a node running CoreDNS (scale down to one and move it around) or is it always happening? Did you try any of the troubleshooting steps? (https://rancher.com/docs/rancher/v2.x/en/troubleshooting/)

**Comment by gwiersma** [comment]
- Does it happen for every container deployed (excluding a certain OS as base image)? 
  Yes it does. We have tested the issue on multiple base images.
- Does rancher containers see the same issue when executed in there? What does the CoreDNS logging show? 
 This problem also occurs on rancher containers 

```
root@rancher-logging-fluentd-2czp5:/# ping google.nl
connect: Cannot assign requested address
root@rancher-logging-fluentd-2czp5:/# ping google.nl
connect: Cannot assign requested address
root@rancher-logging-fluentd-2czp5:/# ping google.nl
connect: Cannot assign requested address
root@rancher-logging-fluentd-2czp5:/# ping google.nl
PING google.nl (172.217.168.195) 56(84) bytes of data.
64 bytes from ams16s32-in-f3.1e100.net (172.217.168.195): icmp_seq=1 ttl=55 time=7.44 ms
^[[A64 bytes from ams16s32-in-f3.1e100.net (172.217.168.195): icmp_seq=2 ttl=55 time=7.42 ms
```
- What does enabling the query logging show? Can you isolate the issue to a node running CoreDNS (scale down to one and move it around) or is it always happening? 
  We moved the CoreDNS container around some hosts and also restarted a couple of hosts during this proces. When moving the CoreDNS container, the probem is always present. 


- Did you try any of the troubleshooting steps? (https://rancher.com/docs/rancher/v2.x/en/troubleshooting/)
i have tried the dns deamonset deployment. We use multiple namespaces and i have deployed the dns test in multiple namespaces. What i dont get is that the dnstest works in the default namespaces (i could not reproduce the issue there) but is doesn't work in the application namespace. Pod security etc is not enabled.

**Comment by superseb** [comment]
`Cannot assign requested address` sounds like IPv6 related, or possibly some pool thats full that cant allocate something needed to complete the request.

There seem to be more conditions than the title suggests, you get this error only in non-default namespaces? Are the nodes in used in each project/namespace identical? Did you check the overlay network just to be sure? Can you use `dig` on a working and non working pod and see what the response is, this can also be retrieved from a query log on CoreDNS to see what is being reached and what isn't. Also, any additional info that can be provided to scope this down so we can reproduce helps.

Additionally, switching back to kube-dns resolves all issues instantly?

**Comment by gwiersma** [comment]
- you get this error only in non-default namespaces? 
No the issue also occurs in the default namespace and the kube-system namespace. 

-  Are the nodes in used in each project/namespace identical?
Yes. The nodes use the same os and docker version.

- Did you check the overlay network just to be sure
How can i check the overlay network? Is there a KB article about this procedure? 

- 

Output:
```

root@test-7dcc67d646-pwv7s:/# dig google.nl

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> google.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 3873
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.nl.                     IN      A

;; Query time: 1 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Fri Jul 26 06:51:25 UTC 2019
;; MSG SIZE  rcvd: 38

root@test-7dcc67d646-pwv7s:/# dig google.nl

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> google.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 3861
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.nl.                     IN      A

;; Query time: 1 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Fri Jul 26 06:51:32 UTC 2019
;; MSG SIZE  rcvd: 38

root@test-7dcc67d646-pwv7s:/# dig google.nl

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> google.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3078
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.nl.                     IN      A

;; ANSWER SECTION:
google.nl.              30      IN      A       172.217.17.35

;; Query time: 11 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Fri Jul 26 06:51:33 UTC 2019
;; MSG SIZE  rcvd: 63
```
So after a couple of retries, the dns starts working. I have tested this from the default namespace. 


- Additionally, switching back to kube-dns resolves all issues instantly?
Is it possible to switch back to kube-dns?

**Comment by gwiersma** [comment]
So just to be sure, i have created a whole new cluster with a fresh Rancher installation. Unfortunately the issue persists.

**Comment by gwiersma** [comment]
I have downgraded rancher from 2.2.6 to 2.2.4. We don't experience any problems right now.

**Comment by wzrdtales** [comment]
have the same problem here. dunno why, downgrading is not necessary @gwiersma i replaced coredns with kubedns again and everything works fine... Something is odd though @superseb

**Comment by wzrdtales** [comment]
About one in three attempts to resolve fails:

```
@-service-55678db8cb-lf9xj:/home/node# curl something.some.svc.cluster.local -vvv
* Rebuilt URL to: something.some.svc.cluster.local/
* Hostname was NOT found in DNS cache
*   Trying 10.43.150.192...
^C
@-service-55678db8cb-lf9xj:/home/node# curl something.some.svc.cluster.local -vvv
* Rebuilt URL to: something.some.svc.cluster.local/
* Hostname was NOT found in DNS cache
*   Trying 10.43.150.192...
^C
@-service-55678db8cb-lf9xj:/home/node# curl something.some.svc.cluster.local -vvv
* Rebuilt URL to: something.some.svc.cluster.local/
* Hostname was NOT found in DNS cache
* Could not resolve host: something.some.svc.cluster.local
* Closing connection 0
curl: (6) Could not resolve host: something.some.svc.cluster.local
```

However I can not reproduce this by using for example dig.

**Comment by wzrdtales** [comment]
For me the env is:

rancher 2.2.6
ubuntu 16.04 for the hosts
node:10 for the image tested in
canal as a transport
coredns as now the default in rancher
latest k8s that is not experimental in rancher

**Comment by superseb** [comment]
It doesn't reproduce on the setup that I use and I'm pretty certain it's either related to the host configuration or network it is attached to. If it can be reproduced on any public cloud, I can use that to debug. If it's not, if you have time to provide me access to a lab environment where it shows, I can look at it.

Adding a query log of CoreDNS while it happens would also help to see if there is anything related.

Does `dig` always work for you from the start @wzrdtales ?

**Comment by wzrdtales** [comment]
yes @superseb . it sporadically does not resolve with toolsets like nodes dns resolver, curl and others (even ping though). i haven't been *yet* able to see it happening on dig though.

**Comment by wzrdtales** [comment]
and sporadically doesn't means less often. it happens often enough that processes crashes. as said about 1 in 3 requests with a pause of ~500ms will fail.

**Comment by wzrdtales** [comment]
I think I already have a second cluster now having the same problem. Two very different setups, the second cluster uses calico instead of canal and ubuntu 18.04 is already on the hosts. Only thing similar is both are custom cluster types I can recall now.

**Comment by superseb** [comment]
Anyone hitting this issue, please provide exact info from the hosts (most are in the output of `docker info`), query log from CoreDNS when it does happen and does not happen, and if possible tcpdump packet captures from the traffic when it does happen and does not happen so we can investigate. Any setup that uses cloud instances/images that can be used to reproduce helps too.

**Comment by gwiersma** [comment]
@superseb So we have updated our VM's to Ubuntu 18.04 and our Docker engines to 19.3.2 and we haven't experienced this problem anymore.

**Comment by gwiersma** [comment]
So i am just checking the kube-system namespace and it seems that kubedns and coredns are both active and both are being used by the kubedns service (both pods have the kube-dns label). Could it be that there is a internal DNS conflict when resolving external domains? The screenshot is taking from a clean Rancher HA cluster. 

![afbeelding](https://user-images.githubusercontent.com/10595726/65672982-3f8e4180-e04a-11e9-819b-20d1f0197912.png)

**Comment by gwiersma** [comment]
I think we found the issue. We had a replication issue with on of our internal DNS servers. So one of the backup DNS servers resolved to a WAN adres instead of a local adres. That does not explain why the google lookup's didnt succeed but after upgrading all the worker nodes to the latest docker version, this issue didn't occour anymore.

**Comment by superseb** [comment]
I don't really see a relation between the DNS server replication issue and upgrading Docker versions, what version did you upgrade to (for people that possibly run into a similar issue)?

We can re-open if this issue happens without external factors and with the requested information provided to investigate.

**Comment by wzrdtales** [comment]
i just reverted on another cluster again to kube-dns. CoreDNS is just so incredibly broken for some reason. I do not have a single cluster which is working actually...
