### ISSUE TITLE
Release page has wrong information about the helm version

### ISSUE THREAD

**Issue by ajfriesen** [rancher/rancher#21741]
On your release page you see the helm chart version is: v2.2.6

https://github.com/rancher/rancher/releases/tag/v2.2.6

That is wrong.
When you install rancher via helm you would define the version with
```
--version=2.2.6
```

The helm version really is without the **v**
```
helm search rancher-stable/rancher -l
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION                                                 
rancher-stable/rancher	2.2.6        	v2.2.6     	Install Rancher Server to manage Kubernetes clusters acro...
rancher-stable/rancher	2.2.5        	v2.2.5     	Install Rancher Server to manage Kubernetes clusters acro...
rancher-stable/rancher	2.2.4        	v2.2.4     	Install Rancher Server to manage Kubernetes clusters acro...
rancher-stable/rancher	2.2.3        	v2.2.3     	Install Rancher Server to manage Kubernetes clusters acro...
rancher-stable/rancher	2.2.2        	v2.2.2     	Install Rancher Server to manage Kubernetes clusters acro...
rancher-stable/rancher	2.1.11       	v2.1.11    	Install Rancher Server to manage Kubernetes clusters acro...
rancher-stable/rancher	2.1.10       	v2.1.10    	Install Rancher Server to manage Kubernetes clusters acro...
```

Just want to point that out since I ran into this issue some time back.
Back then you guys always had the **v** in front of the version but changed that some time back.

**Comment by superseb** [comment]
The semver parsing in Helm should make sure this still works, what issue are you running into with this today?

The release pages seems inconsistent between versions so I will check why this was changed, let me know if this is blocking you from using the chart today so I can take action.

**Comment by ajfriesen** [comment]
Nothing is blocking.

I just remember that we had a problem when we specified "X.X.X" and the install did break because it was expecting "vX.X.X".

But this was really long ago, maybe a year.
Did not know that helm can parse this.
