### ISSUE TITLE
After upgrade to 2.2.5 jenkins can not create dynamic agents

### ISSUE THREAD

**Issue by matandomuertos** [rancher/rancher#21740]
After upgrade from 2.2.4 to 2.2.5 (even testing with 2.2.6) Jenkins is not able to create dynamic agents. I tested installing rancher from scratch and the problem is still the same, I get 
> "Local headers refused by remote: Unknown client name: XXXXXX"

The same happened before: https://github.com/rancher/rancher/issues/17063

The problem is in JNLP container, seems that jenkins is not able to recognize it, this is the log:

```Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior 
Jul 24, 2019 7:07:44 AM hudson.remoting.jnlp.Main createEngine 
INFO: Setting up agent: test-2j0f3 
Jul 24, 2019 7:07:45 AM hudson.remoting.jnlp.Main$CuiListener <init> 
INFO: Jenkins agent is running in headless mode. 
Jul 24, 2019 7:07:45 AM hudson.remoting.Engine startEngine 
INFO: Using Remoting version: 3.29 
Jul 24, 2019 7:07:45 AM hudson.remoting.Engine startEngine 
WARNING: No Working Directory. Using the legacy JAR Cache location: /home/jenkins/.jenkins/cache/jars 
Jul 24, 2019 7:07:45 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Locating server among [https://jenkins.kube.internal/] 
Jul 24, 2019 7:07:46 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve 
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping] 
Jul 24, 2019 7:07:46 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve 
INFO: Remoting TCP connection tunneling is enabled. Skipping the TCP Agent Listener Port availability check 
Jul 24, 2019 7:07:46 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Agent discovery successful 
  Agent address: kubenodes.internal 
  Agent port:    31404 
  Identity:      be:72:61:51:9f:98:73:9c:XX 
Jul 24, 2019 7:07:46 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Handshaking 
Jul 24, 2019 7:07:46 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Connecting to kubenodes.internal:31404 
Jul 24, 2019 7:07:46 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Trying protocol: JNLP4-connect 
Jul 24, 2019 7:07:46 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Remote identity confirmed: be:72:61:51:9f:98:73:9c:XX 
Jul 24, 2019 7:07:46 AM org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv 
INFO: [JNLP4-connect connection to kubenodes.internal/10.201.15.127:31404] Local headers refused by remote: Unknown client name: test-2j0f3 
Jul 24, 2019 7:07:47 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Protocol JNLP4-connect encountered an unexpected exception 
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: test-2j0f3 
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223) 
	at hudson.remoting.Engine.innerRun(Engine.java:614) 
	at hudson.remoting.Engine.run(Engine.java:474) 
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: test-2j0f3 
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:378) 
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:433) 
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816) 
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287) 
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:172) 
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816) 
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154) 
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48) 
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93) 
	at java.lang.Thread.run(Thread.java:748) 
	Suppressed: java.nio.channels.ClosedChannelException 
		... 7 more 
 
Jul 24, 2019 7:07:47 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Connecting to kubenodes.internal:31404 
Jul 24, 2019 7:07:47 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Server reports protocol JNLP4-plaintext not supported, skipping 
Jul 24, 2019 7:07:47 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Protocol JNLP3-connect is not enabled, skipping 
Jul 24, 2019 7:07:47 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Server reports protocol JNLP2-connect not supported, skipping 
Jul 24, 2019 7:07:47 AM hudson.remoting.jnlp.Main$CuiListener status 
INFO: Server reports protocol JNLP-connect not supported, skipping 
Jul 24, 2019 7:07:47 AM hudson.remoting.jnlp.Main$CuiListener error 
SEVERE: The server rejected the connection: None of the protocols were accepted 
java.lang.Exception: The server rejected the connection: None of the protocols were accepted 
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:682) 
	at hudson.remoting.Engine.innerRun(Engine.java:639) 
	at hudson.remoting.Engine.run(Engine.java:474)
```

The connection is:
Jenkins -> Rancher -> K8s -> proxy -> Jenkins

Rancher version working: 2.2.4
Rancher version with problems: 2.2.5 and 2.2.6
Jenkins Version: 2.170
Kubernetes plugin version: 1.16.2

Some idea what changed?

**Comment by matandomuertos** [comment]
Seems that was fixed in the jenkins plugin version: https://github.com/rancher/rancher/issues/21777#issuecomment-525262994

**Comment by HirendraKoche** [comment]
I am receiving same error with below Jenkinsfile code:
podTemplate(
    cloud: 'kubernetes',
    name: 'build-agent'
    label: 'build-agent'
    namespace: 'jenkins', 
    containers: [
        containerTemplate(
            args: 'cat', 
            command: '/bin/sh -c', 
            image: 'maven:3-alpine', 
            name: 'maven', 
            resourceLimitCpu: '', 
            resourceLimitMemory: '', 
            resourceRequestCpu: '', 
            resourceRequestMemory: '', 
            ttyEnabled: true, 
            workingDir: '/home/jenkins/agent'
        ), 
        containerTemplate(
            image: 'jenkins/inbound-agent', 
            name: 'jnlp',  
            envVars: [
                envVar(
                    key: 'JENKINS_URL',
                    value: 'http://jenkins-svc:8080'
                ),
                envVar(
                    key: 'JENKINS_TUNNEL',
                    value: 'jenkins-svc:50000'
                ),
            ],
            resourceLimitCpu: '', 
            resourceLimitMemory: '', 
            resourceRequestCpu: '', 
            resourceRequestMemory: '', 
            ttyEnabled: true, 
            workingDir: '/home/jenkins/agent'
        )
    ], 
    volumes: [
        hostPathVolume(
            hostPath: '/var/run/docker.sock', 
            mountPath: '/var/run/docker.sock'
        )
    ]
){
    node('build-agent'){
        container('maven'){
            stage 'CheckOut Code'
            checkout scm

            stage 'Build code'
            sh 'mvn clean package'
        }
    }
}

I am able to address issue with below code in Jenkinsfile:

podTemplate(
    cloud: 'kubernetes', 
    namespace: 'jenkins', 
    containers: [
        containerTemplate(
            args: 'cat', 
            command: '/bin/sh -c', 
            image: 'maven:3-alpine', 
            name: 'maven', 
            resourceLimitCpu: '', 
            resourceLimitMemory: '', 
            resourceRequestCpu: '', 
            resourceRequestMemory: '', 
            ttyEnabled: true, 
            workingDir: '/home/jenkins/agent'
        ), 
        containerTemplate(
            image: 'jenkins/inbound-agent', 
            name: 'jnlp',  
            envVars: [
                envVar(
                    key: 'JENKINS_URL',
                    value: 'http://<HOST>:<PORT>'
                ),
                envVar(
                    key: 'JENKINS_TUNNEL',
                    value: '<HOST>:<PORT>'
                ),
            ],
            resourceLimitCpu: '', 
            resourceLimitMemory: '', 
            resourceRequestCpu: '', 
            resourceRequestMemory: '', 
            ttyEnabled: true, 
            workingDir: '/home/jenkins/agent'
        )
    ], 
    volumes: [
        hostPathVolume(
            hostPath: '/var/run/docker.sock', 
            mountPath: '/var/run/docker.sock'
        )
    ]
){
    node(POD_LABEL){
        container('maven'){
            stage 'CheckOut Code'
            checkout scm

            stage 'Build code'
            sh 'mvn clean package'
        }
    }
}

I removed label and name from PodTemplate and use "POD_LABEL" variable node().
