### ISSUE TITLE
Cant reach container's in other hosts in virtualbox

### ISSUE THREAD

**Issue by fernandoneto** [rancher/rancher#2174]
Hi,

Im making some tests locally using virtual-box, and i create a stack that run some containers in diff hosts. 
im having some issues and i found container's communication between  host's are not working. 

Example:

Im running a docker container in host A that are linked to a redis container in host B with link-name redis-link . So inside container in Host A i ping the link name and getting no response. 

this is stack im using to test
![stack](https://cloud.githubusercontent.com/assets/6515784/10166119/802b908e-66ba-11e5-858e-d82f21efb341.png)

this is infrastructure
![infra](https://cloud.githubusercontent.com/assets/6515784/10166160/b16fb800-66ba-11e5-8fa7-c5ca2c817495.png)

and this is ping and dig result. 
![dig](https://cloud.githubusercontent.com/assets/6515784/10166230/f5da1800-66ba-11e5-9459-8deae9a55197.png)

version
![version](https://cloud.githubusercontent.com/assets/6515784/10166362/93d8454a-66bb-11e5-8be1-62aa1f323a22.png)

**Comment by deniseschannon** [comment]
The host in the UI with IP (`172.17.42.1`) is most likely the the docker internal IP and will not work. You will need to re-register your host with the [correct IP](http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#samehost).

After that, your containers should be able to communicate. If you get `Please re-register this agent` in the agent logs, then you might be hitting https://github.com/rancher/rancher/issues/1528. The workaround is in the second comment.

**Comment by deniseschannon** [comment]
@fernandoneto Please let me know if you have corrected the IP of your host to see if your containers on different hosts can communicate.

**Comment by fernandoneto** [comment]
@deniseschannon yes i correct the host ip but the problem persist. 
using something like this to start the agent `docker run -d -e CATTLE_AGENT_IP=192.168.99.100 -v /var/run/docker....`  and in host UI the correct IP is show, but when starting containers in diff host's they don't communicate .

**Comment by deniseschannon** [comment]
@fernandoneto Can you look at the troubleshooting FAQs to make sure the expected networking is set up correctly? 

http://docs.rancher.com/rancher/faqs/troubleshooting/

**Comment by fernandoneto** [comment]
@deniseschannon ok thanks

**Comment by fernandoneto** [comment]
![captura de ecra de 2015-10-08 15 26 30](https://cloud.githubusercontent.com/assets/6515784/10369434/28e0a250-6dd2-11e5-8fc1-a13bb8b53082.png)

running with this version's seems to resolve the problem. 
i also run the the agent that is at rancher-server host with variable `-e CATTLE_AGENT_IP=` 

thanks
