### ISSUE TITLE
UI does not show the default values when creating cluster with a template revision where defaults and config value for a field are different

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21758]
Version: Master-head

Steps:
1. Create a cluster template/revision T1/R1 with default value set for field nodeport range is "30000-32100". In the cluster spec keep the nodeport range as "30000-32767". (This can be done in UI using "Add new revision where the default in question section is editable. For the first revision created for a template, the default value is not an editable box)
2. Create a cluster using the revision R1
The default value is not populated the create cluster screen. The cluster config value "30000-32767" is populated.
![Screen Shot 2019-07-24 at 2.49.21 PM.png](https://zube.io/files/rancher/8e276ac992388d50959225fea4a170e0-screen-shot-2019-07-24-at-2-49-21-pm.png)

If the same use case is done through API, the cluster gets created correctly with the correct value for nodeportrange

**Comment by westlywright** [comment]
There was an underlying bug here where the built in fields override questions were showing up in the overrides section as editable. I have fixed that. If the field exists in the UI then the default value for the override is pulled from the corresponding UI field. This is by design. The second bug you found where the values were not updating/applying correctly I have also fixed and will PR shortly.

**Comment by soumyalj** [comment]
Tested with master-head build from July 30
The default value and the config value for a field cannot be different. They are in sync.
1. Created a template which had node port range, snapshot creation and retention count as questions as below:
<img width="1000" alt="Screen Shot 2019-07-31 at 12 03 49 AM" src="https://user-images.githubusercontent.com/18536626/62155521-c06cdd80-b326-11e9-8061-7d0cd352c308.png">

2. During cluster creation, the default values were shown correctly. 
Cluster creation succeeded and it had the right values as in the template.
