### ISSUE TITLE
Cluster creation in API should error out when no answers are provided and when using a template having no defaults and required set to true

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21752]
Version: Master-head

Steps:
1. Create a cluster template/revision with azure cloud provider through API with questions set as below:
```
questions": [ 4 items
{
"default": "",
"group": "password",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": true,
"type": "password",
"variable": "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret"
},
{
"default": "",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": true,
"type": "string",
"variable": "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId"
},
{
"default": "",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": false,
"type": "string",
"variable": "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.subscriptionId"
},
{
"default": "",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": false,
"type": "string",
"variable": "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.tenantId"
}
]
````
2. Create a cluster using this template/revision and do not provide answers

Cluster gets created which it should not. API should error out since defaults are empty and answers are also not provided

**Comment by prachidamle** [comment]
I am not sure that cluster creation API should error out in case answers are not provided and defaults are not set on the clustertemplate.

If we want to really avoid this, during clustertemplate creation, we should error out while setting questions with `required: true` and default empty.
BUT I am not very sure that `default=""` should be assumed as default not provided and we error out on that. There could be some property for which `default=""` can be a valid value.

**Comment by alena1108** [comment]
@prachidamle I think it's ok to assume that required=true expects non-empty answer, and error out if that's not the case.

**Comment by soumyalj** [comment]
Create a cluster template/Revision T1/R1 in **UI** having S3 credentials access key/ secret key as empty, and required set to true and other S3 fields filled out. 
Create a cluster with T1/R1 without providing access/secret keys.
The cluster gets created without providing any errors although we have not provided access/secret key .

**Comment by sowmyav27** [comment]
verified on `master-head` commit id: `400bb3b6`
**Scenario#1**
**Steps:**
1. Create a cluster template/revision with azure cloud provider through API with questions set as below:
```
questions": [ 4 items
{
"default": "",
"group": "password",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": true,
"type": "password",
"variable": "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret"
},
{
"default": "",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": true,
"type": "string",
"variable": "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId"
},
{
"default": "",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": false,
"type": "string",
"variable": "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.subscriptionId"
},
{
"default": "",
"max": 0,
"maxLength": 0,
"min": 0,
"minLength": 0,
"required": false,
"type": "string",
"variable": "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.tenantId"
}
]
```
2. Create a cluster through the API using this template revision.
3. Cluster creation errors out
```
{
"baseType": "error",
"code": "MissingRequired",
"message": "Missing answer for a required clusterTemplate question: rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId",
"status": 422,
"type": "error"
}
```

**Scenario#2**
- Create a cluster template/Revision T1/R1 in UI having S3 credentials access key/ secret key as empty(allow overide - yes), and required set to true and other S3 fields filled out.
- Create a cluster with T1/R1 without providing access/secret keys.
- UI shows an error saying the access key/ secret key are required fields
<img width="1393" alt="Screen Shot 2019-08-16 at 2 19 25 PM" src="https://user-images.githubusercontent.com/26032343/63199124-b7238680-c031-11e9-94ca-ba443e23b792.png">
