### ISSUE TITLE
Rancher throws 'config map' error when trying to create an Amazon EKS cluster with the same name as an existing EKS cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21757]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. create an Amazon EKS cluster with the same name as an existing EKS cluster

**Issue#1**
Below error is seen.
<img width="1441" alt="Screen Shot 2019-07-19 at 1 28 59 PM" src="https://user-images.githubusercontent.com/26032343/61830620-749acf80-ae20-11e9-8c65-00c1687a8530.png">

**Expected Result:**
Relevant error message can be displayed

**Issue#2**
On deleting this cluster, the other cluster(already existing) is also deleted from rancher.

**Expected Result:**
This cluster has an error in deploying, there are no nodes shown. So deleting this should not cause the other EKS cluster to delete from rancher.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): single

**Comment by cjellick** [comment]
@sowmyav27 or @daxmc99 please break this out into two separate issues

**Comment by cjellick** [comment]
Let's discuss how to solve this before you go to implement

**Comment by cbron** [comment]
Closing, as this issue no longer exists in KEv2 version.
