### ISSUE TITLE
[UI] Cluster Templates - Updating a cluster with a template revision having a k8s version lower than the existing one fails

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21756]
Version: Master-head

Steps:
1. Create a cluster template/revision T1/R1 having K8s version v1.15.0-rancher1-2
2. Create a cluster using this template revision R1
3. Create another revision R2 under template T1 with K8s version v1.13.8-rancher1-1
4. Edit the cluster and change the template revision to R2. 
Cluster update fails as we are downgrading the K8s version. 
We need a way to prevent this through Cluster templates/UI

**Comment by davidnuzik** [comment]
There is a similar issue with changing CNI. We should not be allowed to change network plugin.
I created a separate issue to track this here: https://github.com/rancher/rancher/issues/21778

**Comment by davidnuzik** [comment]
Version: master-head (8/8/19)

I followed the steps outlined in the issue description:

Steps:

1. Create a cluster template/revision T1/R1 having K8s version v1.15.0-rancher1-2
2. Create a cluster using this template revision R1
3. Create another revision R2 under template T1 with K8s version v1.13.8-rancher1-1

Upon attempting step 3 (create second revision with lower k8s version) the UI now blocks this.
The UI now only let's us create a revision with higher or same k8s version:
![image](https://user-images.githubusercontent.com/45179589/62726377-f582cb00-b9cb-11e9-894e-db2850895a08.png)
