### ISSUE TITLE
Rancher should update AWS tags for resources used when creating node pools

### ISSUE THREAD

**Issue by SinisterMinister** [rancher/rancher#21751]
When creating a new cluster with the AWS infrastructure provider, the creation request does not update the tags of the related security groups, route tables, or subnets with the proper values as per what k8s needs to enable the cloud provider. This causes load balancers to deploy to single availability zones instead of using all of the available resources as well as not clean up properly when destroyed.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Provision a k8s cluster using Rancher into AWS using the infrastructure provider
Provision a load balancer in the k8s cluster and wait for it to provision
Delete load balancer in the k8s cluster

**Result:**
Load balancer only deploys to the AZ where the controller lives
Load balancer security groups will not be deleted after deletion

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-21T13:09:06Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): v17.3.2

**Comment by SinisterMinister** [comment]
Until the AWS cloud provider no longer requires the `clusterId` to be set in tags, Rancher should add the correct tags with the value of `shared` to the required security groups, subnets, and route tables so Kubernetes functions properly without out-of-band actions being necessary by the user.

**Comment by ajfriesen** [comment]
We are creating a basic vpc network via terraform.
After that we create a k8s cluster via rancher api and terraform.

This works like a charm.
Only problem we face is, that rancher is not setting the proper tags for the AWS ELB.
This could be done on cluster creation since the subnets anyway need to be specified.

My workaround for this is a null resource with a local-exec which needs to be removed manually:

```

#TODO:
# Remove when this issue gets fixed:
# https://github.com/rancher/rancher/issues/21751
resource "null_resource" "resource_tagging" {
  count = var.cluster_az_count
  provisioner "local-exec" {
    command = <<EOF
    export AWS_PROFILE=${var.aws_role_profile}
    aws ec2 create-tags --region ${var.region} --resources ${var.cluster_private_subnets[count.index]} --tags 'Key=kubernetes.io/cluster/${rancher2_cluster.rancher_ec2_cluster.id},Value=owned'
    aws ec2 create-tags --region ${var.region} --resources ${var.cluster_public_subnets[count.index]} --tags 'Key=kubernetes.io/cluster/${rancher2_cluster.rancher_ec2_cluster.id},Value=owned'
    aws ec2 create-tags --region ${var.region} --resources ${aws_security_group.rancher_ec2_cluster_sg.id} --tags 'Key=kubernetes.io/cluster/${rancher2_cluster.rancher_ec2_cluster.id},Value=owned'
    unset AWS_PROFILE
    EOF
  }
}```
