### ISSUE TITLE
Cluster driver logo is not showing properly for non-default cloud providers

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#21767]
**What kind of request is this (question/bug/enhancement/feature request):**
UI bug

**Steps to reproduce (least amount of steps as possible):**
1. go the `Global -> Tools -> Cluster Drivers` and enable some cloud providers like Alibaba ACK
2. Add cluster and the driver's UI is not showing properly

![image](https://user-images.githubusercontent.com/4569037/61843256-9a31e280-aecd-11e9-88f5-16fc7dcbdb61.png)

**Comment by loganhz** [comment]
@lvuch Not sure if it is the right solution. Cloud you have a look, please? Thanks!

**Comment by izaac** [comment]
Version: master-head (v2.3) (8/16/19)

@loganhz the icons look better now in current master-head. But the Baidu icon is touching the edge of the box to left. If you enlarge the image and notice the leftmost blue part of the Baidu logo.

<img width="1195" alt="Screen Shot 2019-08-16 at 12 55 39 PM" src="https://user-images.githubusercontent.com/27659/63194626-57bf7980-c025-11e9-8580-b3e049c0e020.png">

**Comment by izaac** [comment]
Version: master-head (v2.3) (08/21/2019)

All the logos are now properly centered and displayed in the browser.


<img width="1338" alt="Screen Shot 2019-08-21 at 12 52 43 PM" src="https://user-images.githubusercontent.com/27659/63463754-b06e8800-c412-11e9-9b7f-f7aa9434ed38.png">
