### ISSUE TITLE
upgrade rancher-external-dns apiversion to be k8s v1.16 compatible

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#21768]
Need to update the Deployment [api version](https://github.com/rancher/system-charts/blob/dev/charts/rancher-external-dns/v0.0.1/templates/deployment.yaml#L1) to `apps/v1` of `rancher-external-dns` chart,  since the `extensions/v1beta1` is deprecated in k8s v1.16.
 
Refer to [this helps.tpl](https://github.com/rancher/system-charts/blob/dev/charts/rancher-monitoring/v0.0.4/templates/_helpers.tpl#L76) as a good example.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 17ecf7bf

I'm not sure if this is fully testable yet, but I was poking around at this and version `0.0.2` of the chart fails to install in k8s `v1.15.0` -- would this be a valid scenario (`0.0.2` of the chart in a cluster < `1.16.0`? I also tested this by installing as a catalog app and not by enabling the feature.

* Add `system-charts:dev` as a catalog
* Create ec2 cluster (k8s v1.15.0)
*  Install rancher-external-dns app version `0.0.2` to System project
* Error: 
```
Failed to install app rancher-external-dns. Error: release rancher-external-dns failed: Deployment.apps "rancher-external-dns" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"rancher-external-dns", "heritage":"Tiller", "release":"rancher-external-dns"}: `selector` does not match template `labels`]
```

Installing rancher-external-dns `0.0.1` to the System project works successfully, and upgrading to 0.0.2 also succeeds:
* Create cluster
* Install rancher-external-dns `0.0.1` to System project
* Installs successfully 
* Upgrade to `0.0.2` -- success

**Comment by guangbochen** [comment]
This should be a valid testing case and it is caused by `apps/v1` apiVersion changes, adding expected `selector` labels will fix this issue, will add a fix for it, thanks for the report @bmdepesa .

**Comment by bmdepesa** [comment]
After refreshing the catalog and installing again, I see version `0.0.2` of the chart installing correctly on 1.15.0 cluster. 

Is there any easy way to validate this against a v1.16 cluster in Rancher? I see in master-head the latest version we allow is 1.15.0

**Comment by guangbochen** [comment]
we can upgrade the cluster manually to v1.16 by using `rancher/hyperkube:v1.16.0-alpha.2-rancher1` image, but since this is not formal release so maybe we can wait for it and then verify them accordingly.
```
system_images:
  kubernetes: rancher/hyperkube:v1.16.0-alpha.2-rancher1
```

**Comment by sangeethah** [comment]
We should be able to test this using our GDNS provider that is available in HA setups.

**Comment by sangeethah** [comment]
@guangbochen 
Got a HA set up done using alpha7 chart pointing to latest master rancher server

```helm install rancher-alpha/rancher --name rancher --namespace cattle-system --set hostname=<fqdn> --version 2.3.0-alpha7 --set rancherImageTag=master-head```

Create a GDNS provider.
I still see 0.0.1 version of the `rancher-external-dns` being used. 

We expect this to be `0.0.2` version?

<img width="1093" alt="Screen Shot 2019-09-03 at 6 46 25 PM" src="https://user-images.githubusercontent.com/4266958/64219679-41197f00-ce7b-11e9-8edd-7aea105f61d8.png">
<img width="714" alt="Screen Shot 2019-09-03 at 6 45 45 PM" src="https://user-images.githubusercontent.com/4266958/64219680-41197f00-ce7b-11e9-9b1a-7bcffcbacec9.png">

**Comment by guangbochen** [comment]
Yes, the app should be `0.0.2` version, seems the rancher side is not passing the correct app `externalID` to the backend so it still using the old version.

**Comment by guangbochen** [comment]
we can actually validate the upgrade case in your scenario, and deploy the latest version should also work, the logic should be updated on the rancher side.

**Comment by sangeethah** [comment]
Tested with latest build of rancher server from master with local cluster that uses K8s version - 1.15.3

Create a GDNS provider.
I see 0.0.2 version of the rancher-external-dns being used as expected.

<img width="1219" alt="Screen Shot 2019-09-04 at 7 44 46 PM" src="https://user-images.githubusercontent.com/4266958/64307966-9bcedb80-cf4c-11e9-8b8e-0435b30618e0.png">

Able to see external DNS (route53) entries getting created for MCAPPs.

**Comment by sangeethah** [comment]
Tested with rancher server using `2.3.0-rc1`  on a HA set up with local cluster that uses K8s version - `v1.16.0-beta.1`
Once local cluster is up and running , create a Global DNS Provider.
"Rancher-External-Dns" APP version -  `0.0.2` gets deployed successfully in "cattle-global-data" namespace.
