### ISSUE TITLE
Create Troubleshooting FAQs for networking issues

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2177]
How to check your Host Registration is set correctly? 
What to check if Go-machine-service continually restarting in Rancher server logs?
Hosts unable to ping each other (Assumption that questions 1&2 were corrected); Provide info on checking docker bridge IP was not used for rancher agent. 
How to checking IPtables rules are not being malformed.
Machine created in Cloud Provider but not connecting back to Rancher. Stuck at “Almost there”.

**Comment by alena1108** [comment]
+1
