### ISSUE TITLE
Backport: Bug: vSphere node provisioning results in x509 error v2.2

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21773]
rancher/rancher#21306

**Comment by deniseschannon** [comment]
Already available to test for v2.1-head

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1-head 826b90ea

* ```docker run -v /root/state:/var/lib/rancher -d -p 80:80 -p 443:443 --restart=unless-stopped -v /root/certs/ca-additional.pem:/etc/ssl/certs/ca-additional.pem rancher/rancher:v2.1-head```
* Set UI tag to 2.1.25
* Provisioned vsphere cluster with rancheros iso coming from self-hosted webserver
* Cluster provisions successfully
