### ISSUE TITLE
[ERROR] failed on subscribe serviceMonitor: NotFound 404: the server 

### ISSUE THREAD

**Issue by zh88236** [rancher/rancher#21771]
2019/07/25 14:57:45 [ERROR] failed on subscribe serviceMonitor: NotFound 404: the server could not find the requested resource (get serviceMonitors.meta.k8s.io)
2019/07/25 14:57:45 [ERROR] failed on subscribe alertmanager: NotFound 404: the server could not find the requested resource (get alertmanagers.meta.k8s.io)
2019/07/25 14:57:45 [ERROR] failed on subscribe prometheus: NotFound 404: the server could not find the requested resource (get prometheuses.meta.k8s.io)
2019/07/25 14:57:45 [ERROR] failed on subscribe prometheusRule: NotFound 404: the server could not find the requested resource (get prometheusRules.meta.k8s.io)
2019/07/25 14:57:46 [ERROR] failed on subscribe serviceMonitor: NotFound 404: the server could not find the requested resource (get serviceMonitors.meta.k8s.io)
2019/07/25 14:57:46 [ERROR] failed on subscribe alertmanager: NotFound 404: the server could not find the requested resource (get alertmanagers.meta.k8s.io)
2019/07/25 14:57:46 [ERROR] failed on subscribe prometheus: NotFound 404: the server could not find the requested resource (get prometheuses.meta.k8s.io)
2019/07/25 14:57:46 [ERROR] failed on subscribe prometheusRule: NotFound 404: the server could not find the requested resource (get prometheusRules.meta.k8s.io)
2019/07/25 14:57:48 [ERROR] failed on subscribe serviceMonitor: NotFound 404: the server could not find the requested resource (get serviceMonitors.meta.k8s.io)
2019/07/25 14:57:48 [ERROR] failed on subscribe prometheus: NotFound 404: the server could not find the requested resource (get prometheuses.meta.k8s.io)
2019/07/25 14:57:48 [ERROR] failed on subscribe prometheusRule: NotFound 404: the server could not find the requested resource (get prometheusRules.meta.k8s.io)
2019/07/25 14:57:48 [ERROR] failed on subscribe alertmanager: NotFound 404: the server could not find the requested resource (get alertmanagers.meta.k8s.io)
2019/07/25 14:57:52 [ERROR] failed on subscribe serviceMonitor: NotFound 404: the server could not find the requested resource (get serviceMonitors.meta.k8s.io)
2019/07/25 14:57:52 [ERROR] failed on subscribe alertmanager: NotFound 404: the server could not find the requested resource (get alertmanagers.meta.k8s.io)
2019/07/25 14:57:52 [ERROR] failed on subscribe prometheus: NotFound 404: the server could not find the requested resource (get prometheuses.meta.k8s.io)
2019/07/25 14:57:52 [ERROR] failed on subscribe prometheusRule: NotFound 404: the server could not find the requested resource (get prometheusRules.meta.k8s.io)
2019/07/25 14:57:56 [ERROR] failed on subscribe prometheus: NotFound 404: the server could not find the requested resource (get prometheuses.meta.k8s.io)
2019/07/25 14:57:56 [ERROR] failed on subscribe prometheusRule: NotFound 404: the server could not find the requested resource (get prometheusRules.meta.k8s.io)
2019/07/25 14:57:56 [ERROR] failed on subscribe alertmanager: NotFound 404: the server could not find the requested resource (get alertmanagers.meta.k8s.io)
2019/07/25 14:57:56 [ERROR] failed on subscribe serviceMonitor: NotFound 404: the server could not find the requested resource (get serviceMonitors.meta.k8s.io)

**Comment by adampl** [comment]
@zh88236 I've got the same on Rancher 2.2.8. Do you remember what was that and how you fixed it?

**Comment by quangnhut123** [comment]
me too some one know how to fix it ?

**Comment by vkamlov** [comment]
If you encounter this problem, then most likely you have activated cluster monitoring in the Rancher in the past. But then, for some reason, it was turned off incorrectly or broken. You may have removed the CRDs.

In my case, helped to activate the cluster monitoring again in the Rancher UI and then, when the monitoring is activated, you can disable it.

After that, the errors disappeared, and the UI started working very quickly and well.
