### ISSUE TITLE
Rancher  CPU show is error

### ISSUE THREAD

**Issue by symenghuan** [rancher/rancher#21789]
Rancher version: 2.2.4
Question:  My rancher access to the alibaba  k8s，my ECS  the CPU is use less than 10%，but rancher show more than 90%  
I want to know how to solve！ 

The cluster show CPU：
![image](https://user-images.githubusercontent.com/44770931/61920646-eabc4500-af8c-11e9-83d7-01040472f276.png)

The node show CPU：
![image](https://user-images.githubusercontent.com/44770931/61920672-fc9de800-af8c-11e9-8f89-b094481b4df9.png)

The picture is contains cluster monitor

**Comment by superxor** [comment]
it shoes reserved usage, green is actual usage

**Comment by wusphinx** [comment]
with compare, try this command 
```
kubectl top nodes
```

**Comment by symenghuan** [comment]
@superxor 
green is  open the cluster monitor data,  blue is rancher data



@wusphinx 
This operation is normal
![image](https://user-images.githubusercontent.com/44770931/61938518-e3645e00-afc3-11e9-979f-6eb7f9c9300b.png)

**Comment by symenghuan** [comment]
My server CPU is normal，but the blue date more than 90%, Through the blue data determine the alarm

**Comment by symenghuan** [comment]
@aiwantaozi  tks，tell how to resolve this problem
