### ISSUE TITLE
This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.

### ISSUE THREAD

**Issue by ajithreddy444** [rancher/rancher#21783]
*Describe your issue here*
facing this after restarting k8 and rancher

i am stuck here..plz help !!

This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`authenticated.cluster.index`|

**Comment by loganhz** [comment]
Please file a new issue and supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md) Thanks!
