### ISSUE TITLE
Created namespace for Volumes doesn't appear for Workloads in the same project

### ISSUE THREAD

**Issue by vkim-rogers** [rancher/rancher#21786]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.6` UI: `v2.2.90` |
|Route|`volumes.index`|

**Comment by tfiduccia** [comment]
@vkim-rogers - The Namespace will show up in the Namespace drop-down in the "Deploy workload" page.  It will not show up in the workloads page until there is actually a workload to it.  Verified that this is working as expected.
