### ISSUE TITLE
kubelet 不能安装

### ISSUE THREAD

**Issue by wangxuan112** [rancher/rancher#21793]
[etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.5` UI: `v2.2.89` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or you can find us by searching `rancher2` via wechat
