### ISSUE TITLE
rancher/nginx-ingress-controller images (0.21.0/1.5) break sticky sessions

### ISSUE THREAD

**Issue by sneumann** [rancher/rancher#21797]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Hi, 

we have two rancher clusters (old 2.2.4, new 2.2.5) with nginx ingress. The cluster is running behind 
an Apache as reverse proxy using `mod_rewrite`, and the endpoints are `nip.io` adresses.
We had a problem with a regression in 2.2.5 with sticky sessions in the new setup because it returns 
```
  Set-Cookie: INGRESSCOOKIE=18f...39; Domain=xyz.10.10.10.2.nip.io; Path=/app; HttpOnly
```
if you have >1 replicas of the service running, while the working 2.2.4 setup has no `Domain=` in `INGRESSCOOKIE`.

Seems this has been fixed upstream with: https://github.com/kubernetes/ingress-nginx/pull/3648

The images used by rancher 2.2.5 are:
```
   rancher/nginx-ingress-controller:0.21.0-rancher3
   rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
```
I forced rancher 2.2.5 to use the images from 2.2.4:
```
   rancher/nginx-ingress-controller:0.16.2-rancher1
   rancher/nginx-ingress-controller-defaultbackend:1.4
```
which now works (so far). Proper solution will be updated `rancher/nginx-ingress-controller` images.
Hope that helps someone, yours, Steffen

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
It has been bumped to 0.25.0. Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
