### ISSUE TITLE
Ability to edit exiting service

### ISSUE THREAD

**Issue by jas99** [rancher/rancher#2180]
I think this is by design; and I can easily clone and edit but seems cumbersome and gets in the way when trying things out.

I would rather suggest lock the service config after working on it for avoid accidental change. Plus once you initially create service you can enforce lock on it.

Thx

**Comment by deniseschannon** [comment]
This has been discussed previously in https://github.com/rancher/rancher/issues/1060 and https://github.com/rancher/rancher/issues/1689, but essentially, docker containers are immutable so editing a service doesn't quite make sense as we wouldn't be able to edit the containers. We allow editing the Rancher specific components that can be changed.

**Comment by jas99** [comment]
@deniseschannon Now I have been using rancher allot. Cloning has become common and cumbersome practice. Docker container are immutable; I knew that and understand why you can't change the config.

But what I am saying if I stop the service then full configurations can appear and edited. In background having effect of running new container by tearing down old containers.

Let me share one of  my workflow. 

I create mysql service and start it. Now i need to change something. I clone mysql and name it mysql2 because mysql is already in use. Then I run it and delete mysql. Then again goes from mysql2 to mysql :P 
:p :p :p

Thx

**Comment by jas99** [comment]
@deniseschannon @adamcarlile @vincent99 @westlywright @imikushin 

Eagerly waiting on any of your guys comment on this. Because this UX is very annoying to me as a user.

Hope you think abt this.

Thx

**Comment by nlhkh** [comment]
I think this is a critical component for Rancher. If you have ever used Tutum, they have the ability to let you modify your service, and if the modification requires redeploy, then you can invoke redeployment one container after another. The same goes for scaling, they simply terminate some containers, or add some new containers to scale up and down.

**Comment by jas99** [comment]
nlhkh makes very good point.
@deniseschannon @adamcarlile @vincent99 @westlywright @imikushin

**Comment by vincent99** [comment]
We're working on in-service upgrade, https://github.com/rancher/rancher/issues/1874.  Please don't spam the world with @'s.

**Comment by jas99** [comment]
@vincent99 haha didn't knew who was admin; now I do. Will only spam you from now on.
:):);)
jas

**Comment by nlhkh** [comment]
Actually, there is an option to scale up and down the service buried in the API view.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/10594888/7f7e3f5c-7686-11e5-871e-b92a341291c5.png)

There used to be a button on the non-detail screen too but that's apparently gone missing last release (https://github.com/rancher/rancher/issues/2349) and will be back.
