### ISSUE TITLE
Backport: Update to Docker 19.03

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21808]
rancher/rancher#21804

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc2`

**Comment by soumyalj** [comment]
Tested with v1.6.29-rc2. Docker 19.03 is shown in the Docker version list and is displayed as the default version.
![Screen Shot 2019-09-25 at 10 52 52 AM](https://user-images.githubusercontent.com/18536626/65626668-a811eb80-df82-11e9-8033-748760ba41b7.png)
