### ISSUE TITLE
Backport: Update to Docker 19.03 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21807]
rancher/rancher#21804

**Comment by alena1108** [comment]
UI tag 2.1.25

**Comment by sangeethah** [comment]
Tested with rancher server image `v2.1-head` -`bfedfd79` and UI tag `2.1.25`

Docker 19.03.1 is presented as the default option in UI when creating new node Templates.
Able to create following version of K8s clusters using docker version 19.03.1 for hosts by enabling Require a supported Docker version option on cluster creation.

v1.13.5
v1.11.9
v1.12.7

Automation runs on cluster with 1 control , 3 etcd and 3 worker nodes did not report any new issues when testing on K8s v1.13.5 cluster with os versions Ubuntu 18.04.2 LTS 4.15.0-52-generic
