### ISSUE TITLE
Remove PUT request on disabling auth 

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#21803]
After clicking on `Disable Auth`, UI sends two requests
```
/v3/adfsConfigs/adfs?action=disable POST
/v3/adfsConfigs/adfs PUT
```
The payload of PUT contains all the fields of that authconfig, because of which they get saved again on the authconfig CR. We want to unset these fields when auth is disabled.

The backend already sets enabled=false as a response to the disable action. [This](https://github.com/rancher/rancher/pull/21798) backend change also unsets all other fields including `allowedPrincipalIds` and `accessMode`. 
So the PUT request from UI should be removed, as it is preventing the removal of auth provider specific fields from the resource, also it isn't needed anymore with the changes in backend.

**Comment by alena1108** [comment]
A UI part needed for the https://github.com/rancher/rancher/issues/20323 fix

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

Confirmed that PUT request no longer occurs after the POST to (authprovider)?action=disable
![image](https://user-images.githubusercontent.com/45179589/62559984-f4696680-b830-11e9-8043-ed7e7156e558.png)

Confirmed that in the UI the auth config fields are empty now (the only have the normal defaults in) (One example is below)
![image](https://user-images.githubusercontent.com/45179589/62560017-03e8af80-b831-11e9-95c4-88c3bc36d9a2.png)
