### ISSUE TITLE
Update to Docker 19.03

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21804]
With 19.03 out and available in the install docker repo, we need to update the node templates to default to 19.03. 

Also, update support in RKE so it doesn't complain about an unsupported version. 

Update the UI so it's considered a supported Docker version

**Comment by sangeethah** [comment]
Tested with rancher server built form master - `e0de45af`

Docker 19.03.1 is presented as the default  option in UI when creating new node Templates.
Able to create following version of K8s clusters using docker version 19.03.1 for hosts by enabling `Require a supported Docker version` option on cluster creation.

v1.13.8
v1.14.4
v1.15.0.

Automation runs on cluster with 1 control , 3 etcd and 3 worker nodes did not report any new issues when testing on K8s `v1.15.0` cluster with os versions - `Ubuntu 16.04.6 LTS 4.4.0-154-generic` and `Ubuntu 18.04.2 LTS 4.15.0-52-generic`

**Comment by sangeethah** [comment]
Related issue for ROS - https://github.com/rancher/rancher/issues/21843
