### ISSUE TITLE
Feature Request: Allow paste from clipboard in Execute Shell window

### ISSUE THREAD

**Issue by rubenmch** [rancher/rancher#2181]
We frequently need to paste long text in shell windows such as URLs or other long text.

In Rancher UI there's no way to paste text into the shell window that appears when using the Execute Shell option in the containers. 

So right now we have to connect through SSH to the host and then execute bash in the container or retype all the text in the shell window.

Supporting paste in the Rancher UI shell windows would greatly simplify this process.

**Comment by ebuildy** [comment]
The context menu copy/paste doesnt work for you?

**Comment by lavvy** [comment]
+1 for this feature

**Comment by rubenmch** [comment]
@ebuildy There's no paste option in the context menu, Ctrl+V doesn't work either. Tested it in Google Chrome and Firefox on Windows 10.

If I select some text in the shell window Copy appears in the context menu but Paste never appears.

**Comment by ebuildy** [comment]
With context menu I can copy/paste shell content or external contents:

![capture-d ecran-2015-10-02-a-09 09 40](https://cloud.githubusercontent.com/assets/1219817/10241207/2dfa630c-68e6-11e5-862d-769a7cb903af.jpg)

**Comment by rubenmch** [comment]
That option is missing for me. 
What browser/operating system are you using?

Screenshot from Google Chrome / Windows 10:
![image](https://cloud.githubusercontent.com/assets/10353268/10250333/bacac868-68ef-11e5-98a6-d6ba7dcf9305.png)

**Comment by rubenmch** [comment]
Inspecting the terminal I see there are no html inputs, only div elements, one div per line. That might be why there is no paste option in the browser, there's no input field to paste the text into.

@ebuildy Maybe in your browser some other type of html elements are being used for the terminal.

![image](https://cloud.githubusercontent.com/assets/10353268/10252124/02499308-68fb-11e5-9b9c-f3360c63113c.png)

**Comment by dmzaytsev** [comment]
+1 for this feature

**Comment by vincent99** [comment]
The HTML doesn't change.. the parent element is set to `contentEditable`, but apparently that only adds paste as a context-menu option in Chrome on Mac OS.

**Comment by demarant** [comment]
+1

**Comment by f-w** [comment]
+1

**Comment by vincent99** [comment]
https://github.com/chjj/term.js/pull/97 claims to support this better

**Comment by tfiduccia** [comment]
Version - master 3/17
Verified fixed
