### ISSUE TITLE
Importing a previously Rancher-owned EKS Cluster

### ISSUE THREAD

**Issue by kamushadenes** [rancher/rancher#21814]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
- Blow up your Rancher installation
- Give up and setup a new one
- Import old clusters

**Result:**
An EKS cluster previously created by Rancher, when imported, is not identified and lacks some AWS integration.

How can I make Rancher recognize it was it who created the cluster in the first place?

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
```
Previous 2.2.2, new 2.2.6
```

- Installation option (single install/HA):
```
HA
```

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
```
Previously hosted, now imported
```
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
``` 
m5.large
```

- Kubernetes version (use `kubectl version`): 

```
v1.12.6-eks-d69f1b
```

- Docker version (use `docker version`):

```
18.6.1
```

**Comment by kamushadenes** [comment]
Up

**Comment by kamushadenes** [comment]
Hello guys, any tip on this? I'm really lost.

**Comment by jpereiraio** [comment]
👍
