### ISSUE TITLE
update prometheus version

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21827]
check to see if latest prometheus version is being used.

**Comment by guangbochen** [comment]
Link to PR https://github.com/rancher/system-charts/pull/77 and update the Grafana image.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ca39b71

* Deploy Rancher
* Create Cluster
* Enable Cluster monitoring
* Monitoring enables successfully
* Prometheus is versioned correctly and using images from rancher: `rancher/prom-prometheus:v2.11.1`
* Grafana is versioned correctly and using images from rancher: `rancher/grafana-grafana:6.3.2`
