### ISSUE TITLE
Feature Request: Make the Rancher UI shell window resizable

### ISSUE THREAD

**Issue by rubenmch** [rancher/rancher#2182]
The size of the current shell window that appears when using the Execute Shell option in the containers makes viewing with large log files or other large content hard. 

An option to resize the shell window or make it full screen would be very helpful.

**Comment by smw355** [comment]
+1

**Comment by zijam** [comment]
+1

**Comment by andrzejpiasecki** [comment]
+100000

**Comment by teon** [comment]
+2000

**Comment by kchudy** [comment]
+1000000

**Comment by kkrzysztofik** [comment]
+1

**Comment by cruel20** [comment]
+10

**Comment by demarant** [comment]
+1TB :)
actually all text fields should be resizable in my opinion, e.g. those for adding stack > docker/rancher-compose yml

**Comment by vincent99** [comment]
I don't think this worked last time I tried it, but term.js has a `resize()`.

**Comment by ckaenzig** [comment]
+1

**Comment by LLParse** [comment]
+1

It would also be nice if the shell had immediate focus. Currently (Firefox 45) you have to click inside the window to transfer focus.

**Comment by ahfeel** [comment]
+1

**Comment by averri** [comment]
+1

It's a very valuable feature.

**Comment by rguareschi** [comment]
+1

**Comment by LLParse** [comment]
Could we also retain the full log? The log is truncated very aggressively, which is of limited use - I usually have to SSH to the host machine and run `docker logs` to get access to the part of the log I need.

**Comment by rguareschi** [comment]
LLParse, that'd be awesome! 
+1

**Comment by logicethos** [comment]
I would like to see the container screen tabbed, where the second tab is the shell.  Additional shells (tabs) could be started.  Then you can still get to the control panel, without closing the shell.

**Comment by umonteiro** [comment]
not only for logs is useful, if you need a good troubleshooting the big screen can save your time to solve problems.

**Comment by akorolyov** [comment]
+1

**Comment by Siftah** [comment]
+1, I find the shell next to useless with the size of it being so small :(

**Comment by oroc95** [comment]
+1, I find the shell next to useless with the size of it being so small, too :-(

**Comment by dongcj** [comment]
+10000

**Comment by coutouly** [comment]
++++

**Comment by psyhonut** [comment]
+1

**Comment by skandpurohit** [comment]
**+1**

**Comment by danielscai** [comment]
+1

**Comment by danielscai** [comment]
small size shell will do harm to our eyes!!!

**Comment by jrmyr** [comment]
+1

**Comment by oleynikandrey** [comment]
There is a workaround for that case. It is possible to use rancher cli to connect to a container instead of using UI: `rancher exec -it {container_name} bash`

**Comment by tfiduccia** [comment]
Version - 5/24
Verified added

**Comment by stszap** [comment]
Is this feature finally implemented? I don't see any changes in Rancher v1.6.1.

**Comment by vincent99** [comment]
In master, for 2.0.

**Comment by ballerabdude** [comment]
Not sure what I am doing wrong. How can I resize the shell? I am running on docker from the master tag.

**Comment by vincent99** [comment]
@ballerabdude 2.0 is not released yet, you're not running it without compiling everything from source.
