### ISSUE TITLE
Pipeline configuration download does nothing

### ISSUE THREAD

**Issue by b0r1sp** [rancher/rancher#21822]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Edit pipeline > Klick Done Button > Select Option Download > Confirm

**Result:**

* `https://rancher.url/v3/project/c-jpc6m:p-477ff/pipelines/p-477ff:p-7sbjf/yaml?configs={...}` results with errror 500 (see Network Console)
* Changes are lost upon closing the screen.

**Other details that may be helpful:**

Expectation: should download `.rancher-pipeline.yml` including changes from UI. 

**Environment information**

Rancher: v.2.2.5
Browser: Latest Chrome on Mac (Version 75.0.3770.142)

**Comment by gitlawr** [comment]
What's the browser type and version?

**Comment by b0r1sp** [comment]
Latest Chrome on Mac (Version 75.0.3770.142)

**Comment by b0r1sp** [comment]
Still the case with `rancher/rancher:v2.3.0-rc10`
Firefox 66.0.5
Chrome 77.0.3865.90
