### ISSUE TITLE
Rancher-UI API-View: no S3 backups available in dropdown list of restoreFromEtcdBackup

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#21821]
**Bug**: possible UI

**Scenario**: Creating a set of etcd backups in client cluster with S3 backend

**Result:** 
Etcd backups are listed in the Snapshots menu and **not listed anymore** in API View restoreFromEtcdBackup drop down menu (list is empty, but backups are there)

**Other details that may be helpful:**
Maybe a problem with file extensions .zip?

**Environment information**
- Rancher version v2.2.5 (worked in 2.2.2) 
- Installation option (single install/HA): HA

**Comment by nazarewk** [comment]
most likely #20911

**Comment by mrajashree** [comment]
@eumel8 Are you logged in as a user created with some custom global role and having "Manage Cluster Backups" role in the cluster?

**Comment by eumel8** [comment]
@mrajashree thats not the case

**Comment by eumel8** [comment]
works in 2.2.8
