### ISSUE TITLE
[UI] Istio - Enabling Istio still requires us to enable monitoring

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21837]
Version: master-head (7/29/19) `e0de45af`

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Attempt to enable Istio

**Result:**
UI still asks to enable monitoring, even though this is no longer required for Istio operation.

**Comment by bmdepesa** [comment]
@loganhz Is there a backend component to this? Our understanding is that: 

* If cluster monitoring is not enabled:
  * Istio will deploy prometheus without prompting for monitoring to enabled
  * Other monitoring components will remain disabled
* If cluster monitoring is enabled:
  * Istio will re-use existing prometheus (currently working)

**Comment by loganhz** [comment]
@bmdepesa There is no backend component to this. Only UI changes. Maybe we will not cover `Other monitoring components will remain disabled` in this issue. We need Darren's inputs for it.

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

The user no longer needs to first visit the monitoring page to enable monitoring, then enable Istio. This is now all handled when you enable Istio.

![image](https://user-images.githubusercontent.com/45179589/62558099-35f81280-b82d-11e9-987f-605fd4c81eb8.png)
Notice that there is now a disabled checkbox (which is checked) that states "Enable Monitoring" so the user understands that monitoring must be enabled. The tooltip explains further and offers the user to visit the monitoring config page to change any settings and save if they wish (thereby also enabling monitoring).

I ensured that Istio works as expected. This is true whether I tweak monitoring resources manually and enable first then enable Istio, or if I do it all in one go (Monitoring would have default resources in this case).

I wasn't able to identify any problems.
