### ISSUE TITLE
Avatar Images under Access Control in the Site Access section are not loaded 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2183]
v0.39.0

With authentication enabled (Github), the avatar image doesn't seem to load when you get to the page. 

![screen shot 2015-09-29 at 2 21 54 pm](https://cloud.githubusercontent.com/assets/11410997/10178579/76dcd420-66b5-11e5-8aeb-0b9335187986.png)

Steps to Reproduce
1. Fresh install, turn on Github authentication
2. Go to Access Control and click on "Customize"

Result: Admin account avatar is missing. 

Expected Results: Avatar should show up.

Additional issues:
If you add in users, the new users avatar will come up when they are looked up. BUT if you click out of Access Control and come back, any user on the list will not have a valid image.

**Comment by hibooboo2** [comment]
Api is returning correct urls. Vincent must be using the urls incorrectly.

**Comment by hibooboo2** [comment]
```
<div id="ember1017" class="ember-view gh-block">                      <button class="btn-circle-x btn-sm pull-right gh-action" data-ember-action="1018"></button>

  <div class="gh-avatar">
      <div class="gh-placeholder"></div>
  </div>
<div class="gh-block-content">
  <div class="clip gh-block-name">
        <a target="_blank" href="https://github.com/hibooboo2">hibooboo2</a>
  </div>
  <div class="gh-block-detail clip">
      James Jeffrey
  </div>
</div>
</div>
```
Shows Up for the blank elements.

**Comment by vincent99** [comment]
This is because the identities in `allowedIdentities` don't have a `type` field ...identifying... them as an `identity`.  Will hack for now and add to #1052.

**Comment by deniseschannon** [comment]
Verified with master and UI version v0.55.0
