### ISSUE TITLE
Feature Request: Add Execute Shell option for hosts

### ISSUE THREAD

**Issue by rubenmch** [rancher/rancher#2184]
Being able to connect to the hosts from the Rancher UI would be very useful to perform maintenance or monitor the hosts.

**Comment by deniseschannon** [comment]
We would have no way of doing this for hosts that were added using the Custom option, but it might be possible to use `docker-machine ssh` into hosts that were created using the UI (i.e. `docker-machine`).

**Comment by will-chan** [comment]
This isn't something we can do at the moment.
