### ISSUE TITLE
UI: Grafana URL in project level Istio is wrong

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#21845]
**What kind of request is this (question/bug/enhancement/feature request):**

bug
**Steps to reproduce (least amount of steps as possible):**
1. Log in as an admin user.
2. Enable cluster-level monitoring and istio.
3. Go to project istio.
4. Click Grafana icon.

**Result:**

![image](https://user-images.githubusercontent.com/18737885/62095846-3dab3a80-b2b4-11e9-960b-73e866bac273.png)

**Other details that may be helpful:**
The namespace should be `cattle-prometheus`.

**Environment information**

master (2019/07/30)

**Comment by davidnuzik** [comment]
Version: master-head (7/30/19)

1. Log in as an admin user.
2. Enable cluster-level monitoring and istio.
3. Go to project istio.
4. Click Grafana icon.

Result: This is now working, we are taken to the proper Grafana URI and I can see the dashboards:
![image](https://user-images.githubusercontent.com/45179589/62155434-bb277880-b2bd-11e9-8591-ddfc2f000411.png)
