### ISSUE TITLE
Enable more Node Selector options in Rancher Monitoring

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21848]
Rancher version:
v2.2.4

Type:
Enhancement

Description:

Below need to have nodeSelector enabled:

grafana-cluster-monitoring 
exporter-kube-state-cluster-monitoring 
prometheus-cluster-monitoring 
prometheus-operator-monitoring-operator

exporter-node-cluster-monitoring takes care of node metrics and should be on every node

**Comment by loganhz** [comment]
Fixed in master
