### ISSUE TITLE
pipeline-env

### ISSUE THREAD

**Issue by xiaoyuaiheshui** [rancher/rancher#21846]
rancher/rancher:v2.1.3

Steps:

Add a Deploy YAML step
Click advanced options
Add a customized env with DEMO=aa
Make sure there is ${DEMO} in the target yaml
Results:

The text ${DEMO} in yaml file is not replaced as expected.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17233
