### ISSUE TITLE
[UI] Cluster Templates - Inconsistency with editing overrides

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21840]
Version: master-head (7/29/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster template with some overrides.

Notice these will create overrides but the Default Value is not editable (like pictured below)
![image](https://user-images.githubusercontent.com/45179589/62090939-97afef80-b223-11e9-9f9b-7fc06f68d813.png)
- Create a clone of this template

**Result:**
Now the fields are editable for some reason.
![image](https://user-images.githubusercontent.com/45179589/62090971-b0b8a080-b223-11e9-9344-6538226414ba.png)

**Comment by davidnuzik** [comment]
@westlywright could you point me to the PR?

**Comment by westlywright** [comment]
It was fixed as a side affect of another bug in this pr https://github.com/rancher/ui/pull/3184

**Comment by davidnuzik** [comment]
Thanks

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

This is now working as expected.

Create a CT. Notice any overrides that are objects in the form are not editable.
Any that we manually add are still editable (expected).
![image](https://user-images.githubusercontent.com/45179589/62557810-9044a380-b82c-11e9-8de3-73e5adfbc831.png)

Clone the CT. The fields are the same (this is the fix). We can still edit our custom override and not the others that are in the form.
![image](https://user-images.githubusercontent.com/45179589/62557849-a5213700-b82c-11e9-9248-196d75908d69.png)
