### ISSUE TITLE
The custom ingress configmap configuration is lost when k8s1.13.x is upgraded to 1.14.x

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#21851]
**What kind of request is this (question/bug/enhancement/feature request):**
**BUG**

**Steps to reproduce (least amount of steps as possible):**
1. Run `docker run -d --network host -v /home/rancher:/var/lib/rancher rancher/rancher:v2.2.4` to create the rancher server;
2. Create a custom K8S cluster,K8S version 1.13.x;
3. Switch to the `system project | resource | configmap`, modify the `nginx-configuration`
4. Run `docker stop <rancher_container_id>` Stop the rancher server container
5. Run `docker run -d --network host -v /home/rancher:/var/lib/rancher rancher/rancher:v2.2.6` to upgrade the rancher server;
6. Edit and upgrade the K8S cluster to 1.14;

**Result:**

The modified configmap is restored to the default configuration, and the custom configuration is lost entirely

**Comment by fabiorauber** [comment]
Seen this as well. Everytime I want to upgrade the cluster to a newer version, I save the nginx configmap manually to reapply later. It would be awesome not have to do that.

**Comment by gitlawr** [comment]
The nginx ingress controller is deployed as a rke addon, so it is defined in the cluster.yml specification in a declarative way. If you want the custom configurations to be persistent during the upgrade, you can specify them explicitly in the cluster.yml, by clicking `Edit as Yaml` on creation/editing, and fill in the `options` field, as mentioned in [rke docs](https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/#configuring-nginx-ingress-controller)

**Comment by xiaoluhong** [comment]
Thank you.
