### ISSUE TITLE
Add support for SNI in rancher/agent

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#2185]
https://github.com/liris/websocket-client supports SNI, but requires a newer version of Python than is packaged in the `rancher/agent` image.  Without this the `rancher/server` needs to have an IP dedicated to it or happen to be the default VHost for SSL agent connections to work.

**Comment by dkiser** [comment]
+1 for SNI load balancing

**Comment by vincent99** [comment]
@dkiser (hey I know that name :smile:, how's things...) just to clarify, this is only for SNI support in the `rancher/agent` specifically to connect to a `rancher/server` that is behind something doing SSL termination (and Rancher isn't the default VHost).

The load balancer services *inside* of Rancher that you use as a user already supports SNI.

**Comment by dkiser** [comment]
@vincent99 things are good.  Well hot damn, i didnt see that in the ftl template for haproxy, maybe i missed something.  Thanks!

**Comment by rlex** [comment]
will be a nice feature to have, since i terminate all of my SSL websites via nginx on single IP.

**Comment by kbrownlees** [comment]
Just ran into this, here is the error I got in case someone is searching for it:

```2016-03-15 01:31:21,547 ERROR root [140657990538896] [_logging.py:54] error from callback <function on_error at 0x7fed7d90a848>: Received websocket error: [hostname 'zz.com' doesn't match either of 'xx.com', 'ww.xx.com']```

**Comment by vincent99** [comment]
@cloudnautique Can you put in a newer python?  This really seems like it should be fixed for GA.

**Comment by SerialVelocity** [comment]
For people to workaround for now, try this:
```
FROM rancher/agent:v0.10.0

RUN apt-get update && \
     apt-get install -y software-properties-common python-software-properties && \
     add-apt-repository -y ppa:fkrull/deadsnakes-python2.7 && \
     apt-get update && \
     apt-get upgrade -y python2.7

RUN sed -i'' "s/info \"Starting agent for \${CATTLE_ACCESS_KEY}\"/sed -i\"\" 's#^upgrade\$##' \"\$SCRIPT\"/" /run.sh
```

**Comment by cloudnautique** [comment]
This will be supported in rancher/agent:v0.11.0

**Comment by deniseschannon** [comment]
@dkiser @rlex @kbrownlees @SerialVelocity Would any of you be able to test SNI with our v1.0.0-rc1?

**Comment by kbrownlees** [comment]
Just upgraded to 1.0.0-rc1 and everything seems happy.

**Comment by deniseschannon** [comment]
Thanks @kbrownlees!
