### ISSUE TITLE
Waiting for etcd and controlplane nodes to be registered for worker

### ISSUE THREAD

**Issue by kamleshNEC** [rancher/rancher#21874]
I want to setup one master node and 3 worker nodes in my local VM based environment.
Orchestrating Tool: Kubernetes
Rancher: v2.2.6 ( Running in Virtual Machine A)
Now i have created one Kubernetes Cluster as “TestingCluster” by choosing
{“From nodes in an infrastructure provider=custom”}
because i want to use my own virtual as infrastructure.
Node Option: etcd and ControlPlane
Rest options are left as default. It has generated one command for me and i fired it on my separate virtual machine named as “B”. After getting provisioned my ectd , controlPlane and supported services started running on virtual machine B.
Now I want to add 3 worker node into this “TestingCluster” cluster.
And i don’t have any clue how Rancher GUI going to help me to do this task.

 Note: I have tried creating a new cluster and provisioned it Node option as worker. But it is showing me Waiting for etcd and controlplane nodes to be registered error.

**Comment by tfiduccia** [comment]
@kamleshNEC 
1.  Go to Cluster list page
2.  Edit Cluster
3.  At the bottom of the edit page you will see the Customize Node Run Command section
4.  Uncheck etcd & control plane and just have worker selected.
5.  Copy the Run command
6.  Cancel out of the edit

Then you can just go to the nodes you want to add as a worker and run that command.  It will add those nodes as workers into that cluster.

**Comment by kamleshNEC** [comment]
> @kamleshNEC
> 
> 1. Go to Cluster list page
> 2. Edit Cluster
> 3. At the bottom of the edit page you will see the Customize Node Run Command section
> 4. Uncheck etcd & control plane and just have worker selected.
> 5. Copy the Run command
> 6. Cancel out of the edit
> 
> Then you can just go to the nodes you want to add as a worker and run that command. It will add those nodes as workers into that cluster.

**Comment by kamleshNEC** [comment]
Thank you to share your knowledge.
