### ISSUE TITLE
Deploying Rancher as a container (single server mode) on kubernetes

### ISSUE THREAD

**Issue by pradeep-av** [rancher/rancher#21875]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Question**
How can we deploy Rancher in a k8s cluster like a native docker container ? In other words how can we prevent Rancher binding to the k8s resources on which it is deployed ?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/16102#issuecomment-429306953

**Comment by pradeep-av** [comment]
Thanks @superseb !
