### ISSUE TITLE
vSphere StorageClass: ServerFaultCode: Cannot complete login due to an incorrect user name or password

### ISSUE THREAD

**Issue by rldourado** [rancher/rancher#21880]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

* Using Rancher 2.2.6.
* add cluster with **From nodes in an infrastructure provider** as **vSphere** or **From my own existing nodes** as **Custom**.
* **Cloud Provider** as **Custom**
* Edit as YAML and insert:

```
cloud_provider: 
  name: "vsphere"
  vsphereCloudProvider: 
    global: 
      insecure-flag: true
      soap-roundtrip-count: 0
    virtual_center: 
      10.10.10.10: 
        datacenters: "Suassuna"
        password: "password"
        soap-roundtrip-count: 0
        user: "domain\\username"
    workspace: 
      datacenter: "Suassuna"
      default-datastore: "/Suassuna/datastore/vDisk"
      folder: "/kubernetes"
      server: "10.10.10.10"
```

* After cluster is up, add StorageClass with **Provisioner** as **VMWare vSphere Volume** and **Disk Format** as **Thin**
* Then, in the **Default Project**, **Volumes** and **Add Volume**, select **Storage Class** as created before.

**Result:**

* Volume stays in **Pending** state.
* Here is the kube-controller-manager log:

```
I0730 20:02:19.181924       1 vsphere_volume.go:366] Provision with allowedTopologies : []
I0730 20:02:19.181977       1 vsphere.go:1165] Starting to create a vSphere volume with volumeOptions: &{CapacityKB:2097152 Tags:map[kubernetes.io/created-for/pv/name:pvc-f83ff13c-b300-11e9-9051-0050569e6828 kubernetes.io/created-for/pvc/name:test kubernetes.io/created-for/pvc/namespace:default] Name:kubernetes-dynamic-pvc-f83ff13c-b300-11e9-9051-0050569e6828 DiskFormat:thin Datastore: VSANStorageProfileData: StoragePolicyName: StoragePolicyID: SCSIControllerType: Zone:[]}
E0730 20:02:24.227896       1 connection.go:65] Failed to create govmomi client. err: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
E0730 20:02:24.227954       1 nodemanager.go:390] Cannot connect to vCenter with err: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
E0730 20:02:24.227981       1 vsphere.go:616] failed connecting to vcServer "10.10.10.115" with error ServerFaultCode: Cannot complete login due to an incorrect user name or password.
I0730 20:02:24.228058       1 pv_controller.go:1492] failed to provision volume for claim "default/test" with StorageClass "vsphere-volume-thin": ServerFaultCode: Cannot complete login due to an incorrect user name or password.
E0730 20:02:24.228261       1 goroutinemap.go:150] Operation for "provision-default/test[f83ff13c-b300-11e9-9051-0050569e6828]" failed. No retries permitted until 2019-07-30 20:04:26.228222073 +0000 UTC m=+2934.141549618 (durationBeforeRetry 2m2s). Error: "ServerFaultCode: Cannot complete login due to an incorrect user name or password."
I0730 20:02:24.228335       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test", UID:"f83ff13c-b300-11e9-9051-0050569e6828", APIVersion:"v1", ResourceVersion:"3011", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "vsphere-volume-thin": ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.6
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider/Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM with 4 vCPUs and 16Gb RAM
- Kubernetes version (use `kubectl version`): 1.14.3

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by rldourado** [comment]
To rule out the possibility of the credentials being wrong I've tested the same operation using #[govc](https://github.com/vmware/govmomi/tree/master/govc) cli and there were no issues with the credentials.

**Comment by omerlin** [comment]
I confirm the bug.
I have exactly the same behavior with kubernetes 1.14.5 ( rke v0.2.7 ).
I have checked several times my credentials.
It was working with kubernetes version 1.13.5.
I suspect it could be more a rights issues than really a credential issues.

**Comment by omerlin** [comment]
After investigation it appears that the bug was me.
The problem was network related as i couldn't reach the vcenter directly but thru a haproxy. The haproxy was down and a process was listening in place on the port 443 ... 
The error message make me think there was a credential error - which was not the case - it was purely network related - a subtle issues yet.
All my tests (and i did a lot) showed me it works for many version ( at least 1.13.5, 1.14.5, 1.14.6)

**Comment by rldourado** [comment]
> After investigation it appears that the bug was me.
> The problem was network related as i couldn't reach the vcenter directly but thru a haproxy. The haproxy was down and a process was listening in place on the port 443 ...
> The error message make me think there was a credential error - which was not the case - it was purely network related - a subtle issues yet.
> All my tests (and i did a lot) showed me it works for many version ( at least 1.13.5, 1.14.5, 1.14.6)

@omerlin , your username has a "domain\login" format (as a active directory user from vSphere)?

**Comment by minlu001** [comment]
rldourado,

Is this issue fixed? I am running into exact the same issue. Is there an workaround? 

Thanks!

**Comment by minlu001** [comment]
> rldourado,
> 
> Is this issue fixed? I am running into exact the same issue. Is there an workaround?
> 
> Thanks!

rldourado, never mind. It seems to work with email address for GOVC_USERNAME So I am fine now. Thanks.
