### ISSUE TITLE
[UI] Cloud Credentials - Add support for showing errors

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21888]
Version: v2.2.6, master-head (7/31/19)

**What kind of request is this:**
Bug

**Summary:**
This bug is intended to capture various issues that all related to Cloud Credentials not showing most errors in the UI.

**Issues and Steps:**

-----

**_No error shown if cloud credentials fields are all are empty_**
- Create a new cloud credential such as with EC2. Do not supply a name, region, access key, secret key.

Result: The UI will at least report you must pick a region, but if we do that and leave everything else blank it won't report any issues. We expected the UI to first check if credentials are null and if so first report that you must supply xyz. We then expected a check if the name is empty.

**_No error shown if create a cloud credential with a name that is not of type dnsLabel_**
- When you create a cloud credential that does not conform to dnsLabel type the UI doesn't report any error or explanation.
- You can attempt to create a cloud credential that has a name with spaces in it or underscores in it and no error is provided to the user.

Result: When you click "Create" nothing happens which is confusing.

-----

**Conclusion:**
Fixing these issues will make user error and confusion less likely. It will make it more clear to the user when something has gone wrong if they make any mistakes.

**Additional Information:**
This issue was created based on these issues (which are now closed and captured in this issue to make things easier to work on).
https://github.com/rancher/rancher/issues/19759
https://github.com/rancher/rancher/issues/21503
https://github.com/rancher/rancher/issues/21215
https://github.com/rancher/rancher/issues/19677
https://github.com/rancher/rancher/issues/19758

**Comment by loganhz** [comment]
Fixed in master-head

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/13/19)

I tested each area:

**_No error shown if cloud credentials fields are all are empty_**

We now get messages when we don't supply EC2 cloud credential with Access Key and Secret Key
![image](https://user-images.githubusercontent.com/45179589/62963278-846d5a00-bdb5-11e9-85fc-061b5d6526a8.png)

It's expected that the name is not required because it gets automatically generated if not supplied by the user.

**_No error shown if create a cloud credential with a name that is not of type dnsLabel_**

The UI now explains when invalid chars are in the name field:
![image](https://user-images.githubusercontent.com/45179589/62963492-f04fc280-bdb5-11e9-90c2-d8834e4e4bc6.png)
