### ISSUE TITLE
How upgrade/rollback suppose to work?

### ISSUE THREAD

**Issue by summerQLin** [rancher/rancher#2188]
I tried upgrade feature, it's really great. But I wonder how that suppose to work in reality?

Can you please help to see if I understand right?

1. write two versions of service in docker-compose.yml, 
```
myservice-v1:
  ...
myservice-v2:
  ...
```
2. run command line `rancher-compose upgrade myservice-v1 myservice-v2`
3. In case new service fails, to rollback from myservice-v2, run `rancher-compose upgrade myservice-v2 myservice-v1`?
4. finally remove myservice-v1 from docker-compose.yml.

Are the steps correct?

**Comment by deniseschannon** [comment]
It would probably be more like this method:

1. Write version 1 in docker-compose.yml
2. When ready to upgrade, create another docker-compose.yml
```
#Only need name of old service not entire definition
myservice-v1: 
myservice-v2:
  ...
```
3. run command line `rancher-compose upgrade myservice-v1 myservice-v2`
4. If new service fails to work, rollback by scaling myservice-v1 back up to desired number (using either `rancher-compose scale myservice-v1=number` or using UI). And remove or stop myservice-v2

**Comment by mattapperson** [comment]
I would like to inject here, that while this flow works, it is HIGHLY verbose, and very hard to ever automate for a CD scenario where daily deployment workflows are used. There really needs to be a way to just say upgrade X-SERVICE and it just upgrades

**Comment by nhumrich** [comment]
+1 to what mattapperson said.
Can I inject a feature proposal? 
Usually when doing a rolling upgrade, you are only updating the docker image. So what about something like

    rancher-compose upgrade service1 --image myorg/mycontainer:mynewtag

or even just `rancher-compose upgrade service1 --pull` just upgrades the containers by pulling the image again.

Its kind of silly that I have to duplicate everything in my service1 to a new service just to change the docker image. Its also funny that I have to have a docker-compose file in my directory. This makes it hard to use upgrade, as I pretty much have to make an empty directory, make a file, then run the command from that directory, then delete the directory, just to do a simple upgrade.

Is there an API that can be called for rolling upgrades?

**Comment by mattapperson** [comment]
+1

**Comment by nhumrich** [comment]
I will just add, as an implementation detail, using a "second service" is fine, as long as I dont have to create myself. Ideally, 

    rancher-compose upgrade service1 --image myorg/mycontainer:mynewtag

Would just edit a service in place, but if this is too large of a refactor, the implementation of creating a second service is just fine. The rancher service could 

1. Clone service1 to service2
2. Modify the docker image of service2 as part of the clone
3. Do the upgrade like normal

All these features already exist in rancher, so its just tying them together in a much nicer flow.

**Comment by summerQLin** [comment]
Great idea, most of time we might only need to upgrade image, and this command will help simply the process.

**Comment by mattapperson** [comment]
Working on this (in this example, Deploy is an app/service)
https://twitter.com/mattapperson/status/652222415326572548

**Comment by nhumrich** [comment]
I would love to see a gist/PR for this.

**Comment by mattapperson** [comment]
@nhumrich buttoning it up over the next few days... but its a NodeJS based script

**Comment by andyshinn** [comment]
I found this issue first. But also relevant is #1874. A combination of #1874 and what was mentioned earlier here (ability to specify an image with `--image` or maybe a pull with `--pull`) would give me the ability to try out Rancher as a deployment scenario.

**Comment by mattapperson** [comment]
@andyshinn my not exactly done nodes script to do this... https://gist.github.com/mattapperson/57cab7520bec1d1ab190

**Comment by cloudnautique** [comment]
We are going to be creating in place upgrade scenarios to address these situations. At this point there will be a docker-compose file still required. You could do variable substitution for image tags which should mean your not really having to edit on the fly. 

Current thoughts are that It will be more inline with the existing Docker compose --recreate options.

**Comment by deniseschannon** [comment]
We have added in place upgrades and updated the documentation on upgrading using rancher-compose.

http://docs.rancher.com/rancher/rancher-compose/upgrading/

Please re-open if you still have questions.

**Comment by mikepc** [comment]
That docs link is broken.

**Comment by deniseschannon** [comment]
I've updated the link to the original link that it was pointing to, but this is the latest version of the link.

http://docs.rancher.com/rancher/v1.3/en/cattle/upgrading/#in-service-upgrade
