### ISSUE TITLE
Metadata should return /self/host for net host

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2189]
When running a container with net: host we should be able to get at the /self/host/agent_ip from the metadata service.

**Comment by alena1108** [comment]
There are a couple of issues here:

1) Host container record in the metadata service has incorrect ip address - I'm going to fix it to reflect the ip address of the host where container resides (agent_ip), just the way we do for DNS service. 

2) Even with correct ip address set, I'm not sure if metadata service would return self as the ip of the host container might not be equal to client ip that metadata service reads from the request. Going to test it after 1) is fixed.

**Comment by alena1108** [comment]
The fix would be is to introduce following sections under "default": 

/self/host
/hosts

@vincent99

**Comment by cloudnautique** [comment]
Should we also include host in the container response?

**Comment by alena1108** [comment]
@cloudnautique thinking if it should rather be a name of the host, just like we include service.name/stack.name to the container data, not the entire service/stack objects. So using hostName, you can retrieve desired host object from /hosts target.

**Comment by alena1108** [comment]
@sangeethah new fields have been added to metadata

Added uuid field to host in metadata
Added host_uuid/hostname fields to container metadata

Also have to verify that for host networking container, self/host returns the container's host info

**Comment by sangeethah** [comment]
Tested with build from master - Oct 7

From a container that is launched with  net: host ,  querying rancher-metadata for self and self/host returns container's host info.
Host info now includes uuid as well.

```                                       
{"agent_ip":"146.148.39.143","labels":{},"name":"sangeemaster-10acre-1","uuid":"
f9aa9c7f-63d5-4f03-aff6-71e460ce33f8"}root@sangeemaster-10acre-1:/# cat self    
{"host":{"agent_ip":"146.148.39.143","labels":{},"name":"sangeemaster-10acre-1",
"uuid":"f9aa9c7f-63d5-4f03-aff6-71e460ce33f8"}}root@sangeemaster-10acre-1:/#    
```

Also container metadata now retruns  host_uuid/hostname fields:

```
root@900f9393d623:/# cat container                                              
{"create_index":2,"host_uuid":"8a402b1f-1464-4a7f-b591-0c36fef8916b","hostname":
"sangeemaster-10acre-2","ips":["10.42.135.235"],"labels":{"io.rancher.project.na
me":"Default","io.rancher.project_service.name":"Default/test1","io.rancher.sche
duler.affinity:container_label_soft":"io.rancher.service.deployment.unit=1e8714d
5-a4f5-478c-b85b-6cf98a984157","io.rancher.service.deployment.unit":"1e8714d5-a4
f5-478c-b85b-6cf98a984157","io.rancher.service.launch.config":"io.rancher.servic
e.primary.launch.config","io.rancher.stack.name":"Default","io.rancher.stack_ser
vice.name":"Default/test1"},"name":"Default_test1_2","ports":[],"primary_ip":"10
.42.135.235","service_name":"test1","stack_name":"Default"}root@900f9393d623:/# 
root@900f9393d623:/#   
```
