### ISSUE TITLE
Java stack log multi-line matching collection

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#21900]
**What kind of request is this (question/bug/enhancement/feature request):**

**enhancement**

**Steps to reproduce (least amount of steps as possible):**

In the current version, rancher-logging collects log information by line. In applications like Java, stack logs are split into multiple lines of output. So, what eventually gets sent to elasticsearch store and presented via Kibana are multiple logs.

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/20707603/62260402-6cf0b180-b444-11e9-9fc0-94a374adc867.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/20707603/62260411-7548ec80-b444-11e9-9649-e721e3547587.png">

gz#8786

gz#12614

gz#12648

gz#14981

**Comment by rmalchow** [comment]
hi xiaohulong,

you might want to look into using some kind of JSON encoder (we use the logstash encoder) for your output. this encodes a single log object as a single-line java object. many log shipping tools can then handle it correctly down the line. other than that, this is a docker issue, not a rancher issue.

what we do to solve this: 

1.) add the logstash encoder
```
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
		</dependency>
```
2.) let filebeat pick up the logs, and tell it to interpret the "log" field as a nested json object:

filebeat.yml:
```
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              fields_under_root: true
              json.message_key: log
```

3. profit:

`{ "timestamp" : "3838849551" , "log" : "{ \"level\" : \"LOG\", \"message\" : \"foobar\", \"stacktrace\" : [ \"one\", \"two\", \"three\" ] }" } 
`
becomes:

`{ "timestamp" : "3838849551", "level" : "LOG", "message" : "foobar", "stacktrace" : [ "one", "two", "three" ] }`

with all the data that yo uhave in your initial log object neatly represented

**Comment by aiwantaozi** [comment]
@loganhz this is an internal issue, should it be included in 2.3

**Comment by ifeldshteyn** [comment]
In terms of handling multiline in rancher, check out this post.

**Comment by deniseschannon** [comment]
@aiwantaozi @loganhz 

Conferring with @cjellick and we agree that at this point, neither Docker/Rancher should be making the decision on which logs are multiline or not. This should be configured on the logging application itself. This means that there would be no direct fix in Rancher for determining a multi-line log. 

Based on the last suggestion of how to handle this, is it possible to be able to enhance our fluentd to enable plugins so users could configure it themselves if they wanted to?

**Comment by gitlawr** [comment]
To support this we need to enable the concat plugin in fluentd image. And we need to do an enhancement on Rancher side. The fluentd configurations are generated by Rancher controllers and it's not easy for users to tweak the configurations before that.

**Comment by ifeldshteyn** [comment]
I would much prefer that the concat plugin is added to Rancher for cluster and project logging (at the moment I had to host my own fluentd instance wit the plugin).

What we really need is to be able to add this stanza to rancher's system fluentd instances. Here is how I am currently setup in prod. 

```
<filter **>
  @type concat
  **key** log
  **multiline_start_regexp** /\w+ \d+.\d+.\d+ \d+:\d+:\d+: /
  **stream_identity_key** tag
</filter>
```

I think **stream_identity_key** and **key** should be left alone but we'd need to allow users to update **multiline_start_regexp** . For each new type of regex, perhaps join by pipes.

I am surprised this wasn't added at the beginning, who here doesn't have containers that dump multiline messages from time to time?

**Comment by aiwantaozi** [comment]
There is a plugin that supports detected list of language exception stack traces we may install it by default, and in the UI, could let user select enable it or not, which language want to enable, if the language list not enough, could input custom format. Here is the plugin. https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions

**Comment by GoKael** [comment]
Looks like this issue still exist. Not mush we can do in "Edit as a Form".
Does rancher has plan to add plugin in future release?

**Comment by netrounds-martin** [comment]
Seems this was reverted? I'm also curious whether or not this will be added at all or if we have to opt-in for a workaround.

**Comment by Tejeev** [comment]
Are we able to make use of https://docs.fluentd.org/parser/multiline to resolve this?

**Comment by grvlle** [comment]
> Are we able to make use of https://docs.fluentd.org/parser/multiline to resolve this?

This requires the installation of that plugin. This can be done when deploying the helm charts using the configuration variable `plugins.pluginsList`, see all supported configuration parameters [here](https://hub.helm.sh/charts/stable/fluentd). But there are no good means of configuring the plugin itself.
