### ISSUE TITLE
Loadbalancer catch 22

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2190]
This may be a peculiar scenario, but one that we're actually facing.

I have a setup with one "global" load balancer, routing all traffic for all stacks. Now, in my stack, I have services that need to link to this global LB, thus, it must exist before I can setup my stack, or the links fail.

But, in order to create the LB, it must have outgoing links, or it won't function properly. This results in the catch 22, when I start from scratch, there's a bootstrapping issue. The workaround is to have a temp service along with the LB for the sake of getting the LB up, but that feels awkward.

When using the GUI, it won't allow me to create a LB without links, which makes it pretty clear what is required, but when using rancher-compose, this restriction is not present. Everything is reported as just fine, even without any links to other services.

But, here's the real issue, the LB is non-functional as I can't link to it. It exists, and is green on the stacks page, and I can access it when following the "View in API" link, but when I click on it, to go to to service page (i.e. `.../apps/1e2/services/1s1`) it fails (redirected to `/fail` page).

So, whatever logic is used to find the service when rancher-compose looks for it, it doesn't see it, and I can view it in the services page, but it looks fine in the API.

Let me know if you fail to reproduce, and I'll provide more detailed step-by-step instructions.

Ps.
The target server dropdown doesn't remove entries for services I just deleted either (those being dysfunctional LB services, in case that may matter)...

Pps.
I think that the best would be to allow LBs' to be created "empty" in cases where all links are setup using the upcoming feature rancher/cattle#813.

**Comment by vincent99** [comment]
The fail thing when clicking on the balancer is probably an unrelated UI bug... Can you open the browser Dev tools console and see what the error is?

Rancher-compose is supposed to support circular links;  are you doing `up` or `create` + `start`? (https://github.com/rancher/rancher/issues/1851)

**Comment by kaos** [comment]
UI logs:

Request:
```
GET /v1/services/1s12 HTTP/1.1
Host: 192.168.99.100:8080
Connection: keep-alive
x-api-project-id: 1a5
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36
x-api-no-challenge: true
Accept: application/json
X-Requested-With: XMLHttpRequest
x-api-csrf: 2A102A814C5DCB8E3F835726790C4420
Referer: http://192.168.99.100:8080/apps
Accept-Encoding: gzip, deflate, sdch
Accept-Language: sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: CSRF=2A102A814C5DCB8E3F835726790C4420
```

Response:
```
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Wed, 30 Sep 2015 10:55:51 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: CSRF=2A102A814C5DCB8E3F835726790C4420;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a5
X-Api-Client-Ip: 192.168.99.1
X-Api-Schemas: http://192.168.99.100:8080/v1/schemas
Content-Length: 768

{"id":"1s12","type":"loadBalancerService","links":{"self":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12","account":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/account","consumedbyservices":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/consumedbyservices","consumedservices":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/consumedservices","environment":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/environment","instances":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/instances","loadBalancerConfigs":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/loadbalancerconfigs","loadBalancerListeners":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/loadbalancerlisteners","loadBalancers":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/loadbalancers","serviceExposeMaps":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/serviceexposemaps"},"actions":{"upgrade":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/?action=upgrade","update":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/?action=update","remove":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/?action=remove","setservicelinks":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/?action=setservicelinks","removeservicelink":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/?action=removeservicelink","addservicelink":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/?action=addservicelink","deactivate":"http://192.168.99.100:8080/v1/loadbalancerservices/1s12/?action=deactivate"},"name":"HAproxy","state":"active","accountId":"1a5","certificateIds":null,"created":"2015-09-30T10:50:56Z","createdTS":1443610256000,"defaultCertificateId":null,"description":null,"environmentId":"1e3","kind":"loadBalancerService","launchConfig":{"labels":{"io.rancher.loadbalancer.target.dummy":"dummy:80=80","io.rancher.loadbalancer.target.www/app3":"app2.lab.....:9200=9200","io.rancher.loadbalancer.target.www/app4":"api.www.lab.....:80=9000","io.rancher.loadbalancer.target.www/app2":"app2.lab.....:80=8080","io.rancher.loadbalancer.target.www/app2":"www.lab.....:80=7000,cdn1.lab.....:80=7002","io.rancher.loadbalancer.target.www/app1":"app1.lab.....:80=4080"},"logConfig":{},"networkMode":"managed","ports":["80","9200"],"privileged":false,"publishAllPorts":false,"readOnly":false,"startOnCreate":true,"stdinOpen":false,"tty":false},"loadBalancerConfig":{"name":"HAproxy config"},"removed":null,"scale":1,"transitioning":"no","transitioningMessage":null,"transitioningProgress":null,"upgrade":null,"uuid":"a7413567-46e8-4a64-aa45-9ca798196623","vip":"169.254.70.192"}
```

Console:
```
Application Error Error: Unknown link
    at t.default.Mixin.create.followLink (http://192.168.99.100:8080/assets/vendor.js:47:14674)
    at e.default.t.default.Object.extend.connect (http://192.168.99.100:8080/assets/ui.js:51:20148)
    at null.onAvailableChanged (http://192.168.99.100:8080/assets/ui.js:51:19985)
    at e.default.t.default.Object.extend.init (http://192.168.99.100:8080/assets/ui.js:51:19577)
    at n [as init] (http://192.168.99.100:8080/assets/vendor.js:10:933)
    at new m (http://192.168.99.100:8080/assets/vendor.js:13:19850)
    at Function.E.create (http://192.168.99.100:8080/assets/vendor.js:13:22331)
    at e.default.t.default.Route.extend.activate (http://192.168.99.100:8080/assets/ui.js:36:6735)
    at n [as activate] (http://192.168.99.100:8080/assets/vendor.js:10:933)
    at m.default.extend.enter (http://192.168.99.100:8080/assets/vendor.js:11:8765)
ui.js:33 Set previous route to environments.index []
```


Regarding rancher-compose, the load balancer runs in a different stack, while a compose file is for a single stack at a time, so I don't think #1851 really covers this use case..

**Comment by kaos** [comment]
Ps. I've noticed that the link info in the service boxes doesn't seem to be updated live. Not a big deal, but as so much else are, it's easy to miss this..

**Comment by deniseschannon** [comment]
@kaos Do you have an docker-compose.yml that I could easily try to reproduce?

**Comment by kaos** [comment]
Ok, there's definitely something fishy going on here, but I don't think I'm close to the root of it all yet..

I'm going to toss out a lot of bits and pieces as I go along, see where it'll get me (and perhaps you as well) in the end.

First, starting with a clean instance of rancher/server 0.39.0 (default settings running locally in a virtualbox machine, no auth enabled, 1 host registered, also running locally in virtualbox).

I add a single API key, to use with rancher-compose.

Then I run `rancher-compose up` for the global stack. This seems to go fine. But clicking on the HAproxy link on the apps page to get to the services page for that service, I get the link error page.

I then run `rancher-compose up` for the app stack. Which also seems to go fine, when looking in the UI (and the output of rancher-compose). The agent logs says something interesting though:

```
time="2015-10-02T11:11:23Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b6de9560aff90e11d910ec502f63213e79b839050b0b202449cd27fb5de0180e\", From:\"busybox:latest\", Time:1443784283}" 
time="2015-10-02T11:11:23Z" level="info" msg="Assigning IP [10.42.162.186/16], ContainerId [b6de9560aff90e11d910ec502f63213e79b839050b0b202449cd27fb5de0180e], Pid [6942]" 
time="2015-10-02T11:11:23Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b6de9560aff90e11d910ec502f63213e79b839050b0b202449cd27fb5de0180e\", From:\"-simulated-\", Time:0}" 
time="2015-10-02T11:11:23Z" level="info" msg="Container locked. Can't run StartHandler. ID: [b6de9560aff90e11d910ec502f63213e79b839050b0b202449cd27fb5de0180e]" 
2015/10/02 11:11:24 "token is expired"
goroutine 46 [running]:
github.com/rancherio/host-api/app/common.CheckError(0x7f57f7bb2df8, 0xc2080c8d40, 0x2)
	/source/gopath/src/github.com/rancherio/host-api/app/common/error.go:17 +0x8a
github.com/rancherio/host-api/auth.GetAndCheckToken(0xc2080b8039, 0x2c3, 0x8bbd80, 0x5)
	/source/gopath/src/github.com/rancherio/host-api/auth/auth.go:51 +0x87
github.com/rancherio/host-api/logs.(*LogsHandler).Handle(0xb25610, 0xc2080b8000, 0x24, 0xc2080b8029, 0x2d3, 0xc208132b40, 0xc2080aa8a0)
	/source/gopath/src/github.com/rancherio/host-api/logs/logs.go:33 +0x429
created by github.com/rancherio/websocket-proxy/backend.connectToProxyWS
	/source/Godeps/_workspace/src/github.com/rancherio/websocket-proxy/backend/backend.go:72 +0x5c5

E1002 11:11:24.399959    2066 error.go:26] %q
%s
 token is expired
2015/10/02 11:12:16 "token is expired"
goroutine 53 [running]:
github.com/rancherio/host-api/app/common.CheckError(0x7f57f7bb2df8, 0xc2080b2f20, 0x2)
	/source/gopath/src/github.com/rancherio/host-api/app/common/error.go:17 +0x8a
```

The server logs seems ok:

```
time="2015-10-01T14:53:35Z" level=info msg="Creating Machine" eventId="2fdfd887-2461-4159-b2c6-873476342e49" resourceId=1ph1 
time="2015-10-01T14:53:36Z" level=info msg="Activating Machine" eventId="a3d90b79-8592-48b0-ad10-93909a9a48de" resourceId=1ph1 
time="2015-10-01T14:53:36Z" level=info msg="Registering backend for host [9360f5b7-0e33-422f-85a5-8061185724e5]" 
time="2015-10-01T14:57:37Z" level=info msg="Environment Create Event Received" eventId=6a50fe59-0840-42c5-b8bf-734efd688e3d resourceId=1e2 
time="2015-10-01T14:58:19Z" level=info msg="Environment Create Event Received" eventId=7d69c764-d9d1-4970-b522-b3168bfdcfc5 resourceId=1e3 
```

About the test stacks:

One global LB that directs traffic to services running in other stacks.
One service, `svcA`, that links to the LB in order to link to another (yet undefined) service, `svcB`, using a alias of svcB.example.com.

The idea is that once the app stack is up, to update the global/HAproxy service with links to app/svcA (this is not part of this test).

Compose Files: (replace `_` with `/` in the filenames, github gists didn't allow me to have slash in them..)
https://gist.github.com/kaos/8964a55297b86f6bc56c

---

As it turns out, I just noticed we have this very same issue (fail link when trying to access service page for LB) on our rancher deployment in our test environment. It ALSO seems like that LB did not function properly any more (not routing traffic). This used to work, and there has not been much activity here. There seems to have been a restart of the docker daemon, however, and the space for `/var/log` has run out, so that may cause various issues.. It is however very interesting to note that the UI does show this host as OK, but there is no agent running on it. Following this, gave me the idea to check the rest of this environment, and I can see that on the second host, the agent does run, but all other images have been stopped/killed, so it runs alone. But in the UI, it shows a whole bunch of containers as running. So, I draw the conclusion that the server is not processing updates or other stuff as it should. But the logs on the servers are quiet, last logged messages seems fine.. almost too quiet, as the last log entry is from 30/9. But, this could be explained by the `/var` being full also on this host... bah.

For any LB with this issue, I can't access the Console nor are there any data in the View Logs from the UI.


Starting to think if this may be related to the token expired error... ?
Also, full disks seems to cause various silent issues...

I have some cleaning up to do to really know the state of our test deployment. But, the tests that I run locally should be indicative and repeatable.

**Comment by kaos** [comment]
@vincent99 
Ok, I've cleaned up our environment, and stuff's looking better. However, I still get a link error when trying to go to the service page for our LB service. But, if I stop the LB service, it works ok. It also works ok while the containers are in blue state just when I start it up again, but as soon as they're up, it fails (I press reload during start, and it works up until they're green, then it starts failing..)

How can I debug this deeper?
It got to be some data in the db that's not quite what's expected, right?

**Comment by deniseschannon** [comment]
The error that you are seeing related to the load balancer is most likely this issue. https://github.com/rancher/rancher/issues/2211

I am on my phone and will need to spend some time when I get into work to read the rest but wanted to let you know of the UI error.

**Comment by kaos** [comment]
@deniseschannon thanks, that's it, yes. I had some other issues, but I think this issue got in the way of that. Will re-open a new issue once this is out of the way, if it still persists being an issue...
