### ISSUE TITLE
v2.2.5 Gitlab webhook failed with :  422: {"error":"Invalid url given"}

### ISSUE THREAD

**Issue by sauber** [rancher/rancher#21901]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Install Rancher
* Build Cluster
* Add Project
* Tools -> Pipeline -> Gitlab -> Authenticate
* Repository -> Enable -> Done

**Result:**
Gitlab Application is created
Gitlab project webhook is not created

**Other details that may be helpful:**
This has been working consistently in prior version of Rancher and also version v2.2.5 until this week.
From docker log there is no information beyond this vague message:
2019/08/01 07:11:47 [ERROR] PipelineController p-x46kr/p-2zpxj [pipeline-controller] failed with :  422: {"error":"Invalid url given"}

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 1xCPU, 2.5GB RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}```

- Docker version (use `docker version`): 18.9.6

```
(paste the output here)
```

**Comment by jakubriegel** [comment]
@sauber Did you fix the issue?

**Comment by acuetoe** [comment]
Same issue here.

**Comment by ararog** [comment]
Go to Admin > Settings > Network > Outbound requests and check if there's anything fitting related with your issue that you can change there. I'm using gitlab with jenkins in a local network, so making changes there worked for me.
