### ISSUE TITLE
[UI] Windows Support - Protect the required linux worker node in a windows cluster from windows workloads/deployments

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21909]
UI for https://github.com/rancher/rancher/issues/20805

**Comment by davidnuzik** [comment]
Testing note: (Will delete this later)
Try again but with v1.14 k8s due to bug https://github.com/rancher/rancher/issues/21577
Need to get it right the first time or will run into this bug again: https://github.com/rancher/rancher/issues/22161

**Comment by davidnuzik** [comment]
Blocked by an issue where windows can't get an image it needs. This is being investigated and an issue will be created if necessary. Then I will link to it.

**Comment by davidnuzik** [comment]
Based on 8/21/19 discussion with Sangeetha, holding off on testing temporarily; we may make more changes with Taints/Tolerations in this area.

**Comment by sowmyav27** [comment]
Verified on master - head.
Workloads deployed in a windows cluster, end up on windows node only.
To deploy a linux workload, the linux node has to be selected in the `Node Scheduling` section of the workload. And the workload deploys in a linux workload.
