### ISSUE TITLE
Exec shell and view logs do not work in an upgraded set up from rancher v2.2.6 to 2.2.7-rc1

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21919]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Have an rke cluster in v2.2.6 - AWS - 3 etcds, 2 control plane and 3 worker nodes.
Deploy some workloads in the cluster
Upgrade rancher to v2.2.7-rc1
Do an exec shell/view logs of the workload's pod.

**Expected Result:**
User should be able to exec shell/view logs of the workload's pod.

**Actual Result**
User is not able to exec shell/view logs of the workload's pod.
Error in console
```
WebSocket connection to 'wss://x.x.x.x/k8s/clusters/c-6mqzn/api/v1/namespaces/post-ns1/pods/post-testingresswl1-2rl9g/log?container=test1&tailLines=500&follow=true&timestamps=true' failed: Error during WebSocket handshake: Unexpected response code: 403
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.6 to 2.2.7-rc1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS rke

**Comment by sangeethah** [comment]
@sowmyav27 Can be tested with `v2.2.7-rc2`.

**Comment by deniseschannon** [comment]
@sowmyav27 let's use this to track that for 2.3 upgrades, that exec shell still works.

**Comment by sangeethah** [comment]
Have few  rke clusters in v2.2.6  with dedicated worker nodes:
 AWS  cluster - k8s 1.13
 AWS  cluster - k8s 1.14
 Custom cluster -  k8s 1.13
 Custom cluster -  k8s 1.14

Deploy few workloads in all the clusters.

Upgrade rancher to v2.2.7-rc4
After upgrade , exec shell/view logs works for pods in all the above clusters.
