### ISSUE TITLE
Main Nav needs to be on click vs on hover

### ISSUE THREAD

**Issue by lvuch** [rancher/rancher#21914]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Decrease browser size, view on mobile, or mobile inspect

**Result:**
- The main nav's drop downs don't behave correctly. On mouse over should be on click for mobile
- the dropdowns also overlap the other items

<img width="502" alt="Screen Shot 2019-08-01 at 10 23 59 AM" src="https://user-images.githubusercontent.com/3013118/62314028-002ae680-b447-11e9-95fe-214b7d8d0159.png">

**Comment by dsargent3220** [comment]
I would add that OnHover for all navigation is super annoying in general, including in the desktop version of the navigation menu.  It's especially frustrating in the project selector as one slight mouse movement will change selection to a cluster you don't want and you can easily end up in the wrong version of a project (prod cluster --> my project, instead of test cluster --> my project)

**Comment by izaac** [comment]
@codyrancher I did a Main Nav comparison test between `master-head (v2.3) (09/19/2019)` and  `v2.2.8` the experience with that menu is improved on mobile. But there's a regression I've seen with the User Menu. It expands behind the main section.

Here are a couple of screens using a real device. Same happens in both Mobile Chrome and Mobile Safari but I'm focusing the manual test on Mobile Chrome. I also slightly notice the same using Desktop Chrome responsive device tool if I switch to the iPhone 7 plus profile.

Version `v2.2.8`:

![IMG_8952](https://user-images.githubusercontent.com/27659/65255082-1ef64280-dab2-11e9-8789-9027559e8b44.jpg)

Version `master-head (v2.3) (09/19/2019)`:

![IMG_8953](https://user-images.githubusercontent.com/27659/65255127-333a3f80-dab2-11e9-8bbc-e6850a0cb24f.jpg)

**Comment by codyrancher** [comment]
@izaac I'll work on it.

**Comment by izaac** [comment]
Rancher version: `master (v2.3) (09/19/19)`

Re-tested the UI and the experience is improved after my last comment. 

- Created a Cluster
- Navigate the UI in the different Global and cluster level UI areas with Desktop Chrome.
- Use Mobile Chrome to navigate too.
- Original issue looks fixed, the experience feels better in small screen sizes.
- Regression reported about the User menu is also not happening.
