### ISSUE TITLE
Loadbalancer udp support?

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#2192]
It's great to use LB to route tcp / http / https traffic to service containers, but is it possible to route also udp traffic?

**Comment by vincent99** [comment]
Haproxy does not support this as far as I kno, so it would have to use something else like LVS. What application are you trying to balance?

**Comment by pwFoo** [comment]
I think you're right.

> HAProxy
> The Reliable, High Performance TCP/HTTP Load Balancer

Haven't found anything about udp in the feature list.

Maybe different (rancher) services need the same udp port like OpenVPN. Port could be changed, but independent services shouldn't share / negotiate ports with other services.

So it isn't a must have feature, but would be nice to route udp traffic to the right container by domain like done with http / tcp traffic.

**Comment by vincent99** [comment]
Routing only works with HTTP though, because it's a single known protocol with standard fields that can be routed based on.  For arbitrary TCP/UDP the balancer knows nothing about the packets going through it so it doesn't have anything to decide how to route on.

**Comment by pwFoo** [comment]
Thanks for reply. 
Integrated LB build with haproxy for TCP connections are great and should cover all important use cases.

I'll close this issue.

**Comment by johnrengelman** [comment]
I could see a use of a UDP load balancer for something like Logstash. If you have machines outside the rancher environment that you want to have send logs to a Logstash cluster being run by Rancher. UDP is beneficial for having less overhead here (you could run Logstash with a TCP connection as well).
I think it would be worthwhile to look at having a separate UDP load balancer service as an option.

**Comment by erindru** [comment]
I agree with @johnrengelman, another UDP-based service is a RADIUS server, and im sure theres plenty more examples. In these situations it would be very handy to have a UDP load balancer, so we dont have to tie our apps to a specific Rancher node in order to use them. I think we can mangle a UDP load balancer up ourselves using nginx but it would be nice of Rancher supported this directly like it does for TCP/HTTP

**Comment by fabiorauber** [comment]
DNS services also rely on UDP, so using the Rancher LB does not work for DNS servers.

**Comment by lgcosta** [comment]
And Nginx to support udp load balance ? now support:

https://www.nginx.com/blog/announcing-udp-load-balancing/

**Comment by itomaldonado** [comment]
I have the same usage needs. I have a centralized LB stack for all my services (that are exposed outside of the environment) and having Logstash + a Metrics server that use UDP is forcing me to deploy a custom NGINX service (since they not support UDP) instead of using the nice Load Balancer service provided by rancher...

**Comment by OliDow** [comment]
Same as @johnrengelman, I'm implementing a single GrayLog server across multiple Environments/stacks and want to listen to UDP which requires you to jump through hoops with a TCP load balancer.

**Comment by MadOtis** [comment]
I know this is an old, closed bug, but like @johnrengelman and @OliDow, I have centralized Graylog server across multiple environments and it would be awesome to be able to change it back to UDP (I am using a TCP based raw input, just to get around the lack of a native UDP load balancer).  It works, but could be much more efficient and less work setting up.

**Comment by matfiz** [comment]
@MadOtis have you found a solution? I'm facing the same issue - trying to optimize Graylog logging through UDP

**Comment by lgcosta** [comment]
> @MadOtis have you found a solution? I'm facing the same issue - trying to optimize Graylog logging through UDP

I'm using a dedicated instance for this, I had to make some tweaks to have this automated, but it works fine!
https://hub.docker.com/r/instantlinux/udp-nginx-proxy/
