### ISSUE TITLE
UI turns blurry and non-editable when creating a cluster using template with overrides for fields not exposed in UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21928]
Version: Master-head

Steps:
1. Create a cluster template/revision T1/R1with overrides for fields which are not exposed in UI as below:
<img width="1253" alt="Screen Shot 2019-08-02 at 8 32 11 AM" src="https://user-images.githubusercontent.com/18536626/62341921-a851b580-b502-11e9-9d66-b2a44206e01d.png">

Edit as yaml did not have the above entries

2. Create a cluster with using template/revision T1/R1. Once T1/R1 is selected in the dropdown,  the UI turns blurry and non editable as below:

<img width="1436" alt="Screen Shot 2019-08-02 at 8 39 32 AM" src="https://user-images.githubusercontent.com/18536626/62342005-febef400-b502-11e9-9ebd-68b04335e965.png">

***IMPORTANT NOTE *** : Adding a new revision with this template also results in the same blurry, non-editable screen. This needs to be fixed too.

**Comment by westlywright** [comment]
I saw this issue while fixing another bug yesterday and will have a fix in today. 

One note, the edit as yaml will not contain these overrides unless they are added to the yaml by you. Think of the form and edit as yaml as the the cluster object (cluster base spec), everything that goes down to overrides is one way, it does not populate back up as the overrides are a separate resource (questions). The cluster base spec is that, the template as configured by you, that will be applied to the new cluster. It wouldn't make sense to populate overrides back up to the cluster spec. If you're editing the template in the yaml form you're in advanced mode for the cluster spec. At this point there is no easy easy way to add toggles for overrides to the yaml editor so you are on your own. This has been well discussed and accepted.

**Comment by davidnuzik** [comment]
Version: master-head (8/2/19) `bec76ef3`

I followed the steps outlined in the issue description. When I pick the CT now with the custom override the UI does not turn gray (is usable). The cluster comes up as expected without any issues and I see the override when creating the cluster (it's at the bottom of the cluster config in the UI in the Cluster Option Overrides section). The UI/HTTP/API look good.
