### ISSUE TITLE
Tiller version too old to install JupyerHub (2.11 required)

### ISSUE THREAD

**Issue by ananace** [rancher/rancher#21932]
**What kind of request is this (question/bug/enhancement/feature request):** bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Add the [JupyterHub catalogue](https://jupyterhub.github.io/helm-chart/) to Rancher
2. Try to launch the JupyterHub application from it

**Result:**
`Failed to install app jupyterhub. Error: Chart incompatible with Tiller v2.10+unreleased`

**Other details that may be helpful:**
The [JupyterHub chart](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/Chart.yaml#L10) requires at least Tiller version 2.11

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.6
- Installation option (single install/HA): HA

**Comment by HelenCousins** [comment]
I also have this issue

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/16971
