### ISSUE TITLE
backport (2.2): Jenkins kubernetes plugin can't watch pods after 2.2.5 or 2.2.6 upgrade

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#21940]
backport: https://github.com/rancher/rancher/issues/21777

**Comment by sangeethah** [comment]
@bmdepesa  This can be tested in  latest `2.2-head`.

**Comment by sangeethah** [comment]
@bmdepesa This can be tested with `2.2.7-rc3`

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.7-rc3

* Reproduced in v2.2.6
* Deploy v2.2.7-rc3
* Create cluster
* Enable Helm catalog
* Create jenkins-custom secret w/ access token
* Make sure serverUrl is edited in YAML file contents
* Launch Jenkins app in cluster
  * Edit yaml and paste contents from file
* Create ingress to Jenkins workload
* Retrieve Jenkins admin password from secret
* Access Jenkins
* Create job w/ sh build step
* Job builds without error
