### ISSUE TITLE
backport (2.1): Jenkins kubernetes plugin can't watch pods after 2.2.5 or 2.2.6 upgrade

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#21945]
backport: https://github.com/rancher/rancher/issues/21777

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.12-rc2

* Reproduce in v2.1.11
* Deploy Rancher v2.1.12-rc2
* Create cluster
* Enable Helm catalog
* Create jenkins-custom secret w/ access token
* Make sure serverUrl is edited in YAML file contents
* Launch Jenkins app in cluster
  * Edit yaml and paste contents from file
* Create ingress to Jenkins workload
* Retrieve Jenkins admin password from secret
* Access Jenkins
* Create job w/ sh build step
* Job builds and executes correctly 

YML located here: https://github.com/rancher/rancher/issues/21777#issuecomment-517439874
