### ISSUE TITLE
Forward port (master): Exec shell and view logs do not work in an upgraded setup

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#21947]
https://github.com/rancher/rancher/issues/21919

**Comment by deniseschannon** [comment]
@sowmyav27 Can be tested with v2.2.7-rc2.

**Comment by sowmyav27** [comment]
verified on an upgrade setup..
v2.2.6 to master-head
Have few rke clusters in v2.2.6 with dedicated worker nodes:
AWS cluster - k8s 1.13 - 1 control , 1 etcd , 2 worker
Custom cluster - k8s 1.13 - 1 control , 1 etcd , 12 worker

Deploy few workloads in all the clusters.

Upgrade rancher to master-head
After upgrade , exec shell/view logs works for pods in all the above clusters.
clusterrole is created on upgrade.
