### ISSUE TITLE
Should be able to determine state of container and thus scheduling without tcp-based health checks

### ISSUE THREAD

**Issue by deitch** [rancher/rancher#2195]
Reference the extended conversation at https://github.com/rancher/rancher/issues/1877

This is necessary for 2 key reasons:
1. Many services run containers that have zero tcp sockets listening. It is important we be able to monitor them on containers as easily as on VM or bare-metal hosts, so Rancher provides a complete solution, and it is unrealistic to expect someone to rewrite/rebuild their container just to add some socket listener to respond and say, "hey, I am here" when asked.
2. Enterprise managers _expect_ it to work this way. I tell you about my service, if you can start it, then you can monitor it. tcp-based checks are a valuable higher-level service, but do not replace the basic container watching.

Since the agent already exists, and can monitor the containers locally and thus know their state(s), they should be able to act as their own local health-checkers, and their state, in turn, can be determined by other agents.

**Comment by vincent99** [comment]
This is not going to happen in 1.x, and 2.0/k8s has command health checks.
