### ISSUE TITLE
UI显示未激活

### ISSUE THREAD

**Issue by herrywen-nanj** [rancher/rancher#21960]
*Describe your issue here*

![image](https://user-images.githubusercontent.com/33476935/62415742-54111780-b661-11e9-8403-e135fa380a32.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.5` UI: `v2.2.89` |
|Route|`authenticated.cluster.monitoring.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

or you can find us via WeChat by searching `rancher2`
