### ISSUE TITLE
Rancher keeps stale data in /var/lib/rancher/management-state/rke

### ISSUE THREAD

**Issue by RaceFPV** [rancher/rancher#21976]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
exec into the rancher server container and perform an ls on /var/lib/rancher/management-state/rke

**Result:**
Over time, the rke folder fills with thousands of 'rke-###' folders which each store old rke state files. At two months of running rancher server I am now at 2600+ folders and 4gb+ of data.

**Other details that may be helpful:**
The rke state files are all the same size at 120kb

**Environment information**
- Rancher version: 2.2.6
- Installation option: single install

**Comment by davidnuzik** [comment]
We have reports from another user as well with many GB as well here

**Comment by ssirag** [comment]
I've got 11 GB of drive space soaked up by these files... I'm using Rancher v2.2.4, and my server is only about 3 months online.  Estimate about 90k files.

My server is down from lack of drive space; any advice on clearing some out to get back online, as well as the final fix for keeping them from accumulating?

**Comment by RaceFPV** [comment]
Continuing to slowly have my drive space consumed by this, can we get a rough eta on a fix or at least a workaround? Thanks!

**Comment by cprivite** [comment]
I'd settle for just an acknowledgement at this point that we're not doing something stupid and this is indeed considered a bug by the rancher devs.

**Comment by RaceFPV** [comment]
Still continuing to lose drive space to this, eventually things will fall over...

**Comment by RaceFPV** [comment]
Another bump, still losing space to this

**Comment by p-caetano** [comment]
Same here: 
1.2GB on management-state/rke dir
11GB on management-state/driver-metadata/rke dir

Is it safe to delete the older ones?

**Comment by tarakanof** [comment]
Same on Rancher 2.5.5 standalone installation: /var/lib/rancher/management-state/rke = 26Gb

**Comment by kravciak** [comment]
Reproduced on 2.5.5
Works fine on master-head (3e89bb8) and 2.5-head (12cd346)
