### ISSUE TITLE
Backport: Add in Kubernetes 1.13.9

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21978]
#21977 

In 2.1.x, we only support up to Kubernetes 1.13.x

**Comment by sangeethah** [comment]
Tested with `v2.1.12-rc5`

Deploy RKE cluster with k8s version  - `1.13.9` with following node configuration:
1 control node
3 etcd nodes
3 worker nodes

All existing automation runs reports success when run on this cluster.
