### ISSUE TITLE
Remove "Rancher" from helper text and misc areas Phase 2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21971]
Phase 1: https://github.com/rancher/rancher/issues/21690 (just covered en-us.yaml)
Phase 2 to cover everywhere else (template.hbs, etc)

It's best to avoid the company's name in helper text and miscellaneous areas in the UI where possible.

We should review template.hbs and any other files and see if there are areas we can remove mentioning "Rancher" (case insensitive) in situations where this shows up in the UI for end-users.

**Comment by davidnuzik** [comment]
%NODEDRIVER.TEMPLATEOPTIONS%
This is not in en-us.yaml it seems this is an example of something that should change (should just be "Template"

![image](https://user-images.githubusercontent.com/45179589/62483543-c0c50880-b76c-11e9-824c-abfd8fe3867e.png)

**Comment by tfiduccia** [comment]
Having appName is ok in this case.  I'm going to close this issue.  If you find anymore just enter new issues.
![image](https://user-images.githubusercontent.com/11514927/66517072-49c32d80-ea97-11e9-8500-2b7d821448f0.png)
