### ISSUE TITLE
EKS non-functional on v2.1.x (AMIs out of date)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21980]
Version: v2.1.12-rc5, v2.1.11, (and probably all older v2.1.x)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to create EKS cluster

**Result:**
Worker nodes won't become available. I'm not sure what the root cause of the issue is, but in the UI we don't prompt for k8s version and UI doesn't even specify one, so AWS picks the latest (now 1.13) and this seems to be the issue. UI should presumably use 1.12 to fix this or we should fix the root cause of the issue.
![image](https://user-images.githubusercontent.com/45179589/62495853-047b3a80-b78c-11e9-98e5-f0c21d8a296c.png)

This was last known to be working when we tested v2.1.11 (back then only v1.12 k8s was available in AWS for creating EKS clusters).

**Comment by davidnuzik** [comment]
Version: v2.1.12-rc6

I tested with the us-west-2 and us-east-1 regions and can confirm the cluster now comes up without any issues. Notice that our worker nodes k8s version is newer now. The worker nodes are now v1.13.7-eks-c57ff8 whereas before the fix they were older v1.10.3 k8s.

The cluster is healthy and I smoke tested and couldn't identify any issues.
I am not able to test the eu-west-1 region due to limitations on our QA testing AWS account. This was not checked.

Automation tests are being run as well (in progress).

**Comment by sangeethah** [comment]
@superseb Could you please test with "eu-west-1" and see if you are able to get an EKS cluster up successfully using v2.1.12-rc6 ?

**Comment by superseb** [comment]
Version: v2.1.12-rc6

Cluster successfully created in `eu-west-1` region, AMI for the workers: `amazon-eks-node-1.13-v20190701 (ami-00ac2e6b3cb38a9b9)`.

EKS version:
```
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
Kubernetes Version
1.13
Platform Version
eks.2
```

This was released yesterday so might just fall between the times of testing (https://docs.aws.amazon.com/eks/latest/userguide/doc-history.html)

**Comment by davidnuzik** [comment]
Closing issue. We were able to validate the AMIs for each region. There are no newer AMIs available at this time; we are up to date.
