### ISSUE TITLE
Add Secrets page

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21985]
Version: master-head (v2.3) (8/5/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Request:**
Add "Secrets" page to encapsulate "Secrets", "Certificates", and "Registries" similar to https://xd.adobe.com/view/3a10455b-f004-4bc1-636d-0415a0fed4b0-4c21/screen/d4c2d662-a93b-4173-8305-1d6a26c85070/Web-1366-2 this should go on the Resources menu as a means for the end-user to navigate to this page and access all three of these pages from this "Secrets" page.

Perhaps we want a similar model to Workloads where we have "tabs" to go from one area to the next.
(i.e. sort of like this)
![image](https://user-images.githubusercontent.com/45179589/62499404-5d040500-b797-11e9-8853-ca8a83fd30fe.png)

**Result:**
Conforms closer to the wireframe
Related to https://github.com/rancher/rancher/issues/21887

**Other details that may be helpful:**
Issue created based on Slack conversation with Tani (8/5/19)

**Comment by tfiduccia** [comment]
Still need to change "Security" to say secrets in drop-down.  I can do that.

**Comment by tfiduccia** [comment]
@david - after my pull request has been merged this will be ready to test.

**Comment by davidnuzik** [comment]
Version: master-head (8/8/19)

Confirmed that we changed "Security" to "Secrets" and that the new page has been added:
![image](https://user-images.githubusercontent.com/45179589/62722470-4fcb5e00-b9c3-11e9-9e0f-133520b9ea47.png)

The secrets page allows us to access Secrets, Certificates, and Registries
![image](https://user-images.githubusercontent.com/45179589/62722512-6c679600-b9c3-11e9-9712-2761d0b5c07c.png)

For each, there is a button at the top right to add the resource such as the example below.
![image](https://user-images.githubusercontent.com/45179589/62722561-9620bd00-b9c3-11e9-8136-f77f4ea4ebc2.png)

Or you can use the main button:
![image](https://user-images.githubusercontent.com/45179589/62722589-a6389c80-b9c3-11e9-9d04-97647cdbd0b8.png)

I smoke tested each and only found a minor issue.
When searching and have zero results there is no en-us.yaml translation string:

![image](https://user-images.githubusercontent.com/45179589/62723002-848be500-b9c4-11e9-9885-6bd466ec1d5e.png)

![image](https://user-images.githubusercontent.com/45179589/62723056-a1c0b380-b9c4-11e9-9dce-51b977693e4b.png)

Secrets is good though.
Since we need to fix these two translations so they have values I am reopening the issue.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/12/19)

The remaining issues have been resolved. Refer to my last comment with all the other testing notes.
We now have translation strings for Certificates and Registry Credentials when a search is done and there are no search results (reference my last comment) https://github.com/rancher/rancher/issues/21985#issuecomment-519607080

Certificates:
![image](https://user-images.githubusercontent.com/45179589/62888994-4c064700-bcf5-11e9-9fad-80390debee16.png)

Registry Credentials:
![image](https://user-images.githubusercontent.com/45179589/62889043-67715200-bcf5-11e9-9a4d-1b29edbcc791.png)
