### ISSUE TITLE
Backport: Add in Kubernetes 1.13.9, 1.14.5, 1.15.2

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21981]
#21977

**Comment by sangeethah** [comment]
Tested with - v2.2.7-rc5

Following are the Ks8 version that are available for deploying cluster:
```
v1.13.9
v1.14.5
v1.15.2
```

All existing automation runs succeeded when create cluster with 1 control , 3 etcd and 3 worker nodes:
```
v1.13.9
v1.14.5
v1.15.2
```
