### ISSUE TITLE
HA Airgap -Rancher pulls image from wrong place  

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#21996]
bug found in v2.2.6 and v2.2.7-rc6 fresh install in air-gapped HA mode

install Rancher:v2.2.7-rc6 in air-gapped HA mode, following Rancher's documentation at https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/

Result:
- under the local cluster, the workload `cattle-cluster-agent` and `cattle-node-agent` are pulling image `rancher/rancher-agent:v2.2.7-rc6`, which should be from my private registry `private-registry/rancher/rancher-agent:v2.2.7-rc6`

<img width="1419" alt="Screen Shot 2019-08-05 at 7 02 03 PM" src="https://user-images.githubusercontent.com/6218999/62506109-24beef80-b7b4-11e9-8753-49c0ad7c6c88.png">
<img width="1434" alt="Screen Shot 2019-08-05 at 7 02 14 PM" src="https://user-images.githubusercontent.com/6218999/62506111-24beef80-b7b4-11e9-8b7c-fd46f2b40322.png">

- the following screenshot shows that all other workloads pull images from the private registry by default and be active 

<img width="1431" alt="Screen Shot 2019-08-05 at 7 02 25 PM" src="https://user-images.githubusercontent.com/6218999/62506135-41f3be00-b7b4-11e9-8ba6-8790625db105.png">

Workaround:

- editing the workload to change the image from `rancher/rancher-agent:v2.2.7-rc6` to `private-registry/rancher/rancher-agent:v2.2.7-rc6` can solve the problem.

**Comment by jiaqiluo** [comment]
**how to reproduce the bug:**

It turns out that if we don't set the system default registry after Rancher is running up and before the workloads `cattle-cluster-agent` and `cattle-node-agent` is deployed by Rancher itself, those two workloads will use the image `rancher/rancher-agent:v2.2.7-rc7` (of course because the system default registry is not set when they are deployed ).

**Workaround:**

Add the following parameters to the helm command that generate Rancher's template:

```
 --set 'extraEnv[0].name=CATTLE_SYSTEM_DEFAULT_REGISTRY' \
 --set 'extraEnv[0].value=<REGISTRY.YOURDOMAIN.COM:PORT>'
```

The full command will be 
```
helm template ./rancher-<VERSION>.tgz --output-dir . \
 --name rancher \
 --namespace cattle-system \
 --set hostname=<RANCHER.YOURDOMAIN.COM> \
 --set rancherImage=<REGISTRY.YOURDOMAIN.COM:PORT>/rancher/rancher \
 --set 'extraEnv[0].name=CATTLE_SYSTEM_DEFAULT_REGISTRY' \
 --set 'extraEnv[0].value=<REGISTRY.YOURDOMAIN.COM:PORT>'
```

**Comment by sangeethah** [comment]
Doc issue for this - https://github.com/rancher/docs/issues/1643
