### ISSUE TITLE
Backport(2.2): Update EKS AMI's for k8s 1.13

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#21993]
backport: https://github.com/rancher/rancher/issues/21992

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2-head ec468dea 

* Saw older AMIs being used in v2.2.8
* Deploy 2.2-head
* Create 1.13 EKS cluster
* Cluster is using the updated ami for the region (us-east-2): `ami-0355b5edf93d47112
* Cluster comes up successfully
