### ISSUE TITLE
Send proper Content-Types for assets

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#2199]
Currently the server sends no Content-Type at all for js/css/fonts/svgs that are served up, causing confusion in some browsers.

**Comment by vincent99** [comment]
MS Edge has a much more consistent problem with this and won't show our fonts if hosted by Cattle.

**Comment by RobertKozak** [comment]
Does this help? it has errors CSS3120, CSS3111

![untitled](https://cloud.githubusercontent.com/assets/85093/17347916/ab1b8312-58c7-11e6-951a-45940a121cfc.png)

**Comment by vincent99** [comment]
@RobertKozak We know that the problem is that Cattle serves up the font with the wrong headers, it just hasn't been fixed yet.
