### ISSUE TITLE
Dns intermittently unable to resolve

### ISSUE THREAD

**Issue by lndj** [rancher/rancher#22009]
*Describe your issue here*
When I curl a dns name like: xxx.xxx.svc.cluster.local
Sometimes, it resolved, but sometimes not.

![image](https://user-images.githubusercontent.com/9111083/62558711-1e13a380-b8ac-11e9-8945-4a648d7b9970.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.6` UI: `v2.2.90` |
|Route|`workload`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
