### ISSUE TITLE
Feature Request - Event Feed

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#2200]
Rancher is fast, i mean really fast at recovering services. As a result, by the time i open a browser a service has usually recovered and it's not easy for me to tell if anything untoward has happened.

It would be a neat to have a list of recent events somewhere in the UI that's easy to get to.
I'm not suggesting this is another log, more an informational list of the last X recent events, this could include HA events for containers, upgrades or services being stopped/started. 

As a crude example of what i'm getting at, opsview has a similar concept but for alerts, can be seen here.
https://docs.opsview.com/lib/exe/detail.php?id=opsview4.6%3Agetting-started-with-dashboard&media=opsview4.6:dashboard:event-table.png

Something like that but for services and perhaps less garish would be really useful.

**Comment by lavvy** [comment]
+1

**Comment by cusspvz** [comment]
+1

**Comment by willowandcreek** [comment]
+1

**Comment by nhumrich** [comment]
+1

**Comment by cusspvz** [comment]
It could also include, not only system actions, but also user taken actions, giving you an entire view of changes history.

**Comment by RVN-BR** [comment]
+1 as requested in the forums a while ago

**Comment by ahfeel** [comment]
+1

**Comment by Rucknar** [comment]
@will-chan This might actually be a duplicate of https://github.com/rancher/rancher/issues/52
Thinking about it, might be worth events/alerts having their own feature requests though, both reasonably big features.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
