### ISSUE TITLE
Rancher v2 : How to mount my logstash.conf file to logstash container

### ISSUE THREAD

**Issue by MohamedBenighil** [rancher/rancher#22008]
I deployed logstash container in rancher v2, and i added a volume to put my log files using rancher UI (by clicking on : Workloads -> Volumes section -> add volume Button ( choosing : Bind-mount a directory from the node )): 

![Ldata](https://user-images.githubusercontent.com/49414837/62545440-fd266080-b861-11e9-8854-b4181ab3fbfb.PNG)
And it works fine.

I followed exact same steps to mount the logstash.conf file to the logstash container using same steps as before: 
![logstashConfigurartion](https://user-images.githubusercontent.com/49414837/62545169-7c676480-b861-11e9-8c57-570492fc39d0.PNG)

but it does not work, and the logstash container logs gives : 
![logstashLog](https://user-images.githubusercontent.com/49414837/62545201-8b4e1700-b861-11e9-982f-ff00995d8467.PNG)

Any idea to fix this issue ?

**Comment by ekristen** [comment]
That is one way of doing it, but I would recommend you use a Config Map instead. 

However with the way you've done it, it appears that it's getting an access denied error, which seems to indicate that the file permissions on the config file are not correct for the user context that the logstash container is running in.

**Comment by MohamedBenighil** [comment]
@ekristen i resolved the issue by applying these tow commands to my volume :
1. chown 1000:1000 /path/to/my/LogstashVolume
2. chmod g+rwx /path/to/my/LogstashVolume

and it works!

However, i got another acess denied error : logstash container not able to process my log files : 
![logstashLogDenied](https://user-images.githubusercontent.com/49414837/62704827-8cf81600-b9ec-11e9-8191-56c569764758.PNG)


I applied the same commands as (1 and 2) to my volume (/dump/logstashLogs:/var/tmp/log) but it does not work,

Any idea to resolve this issue ?

Thank you in advance!

**Comment by loganhz** [comment]
It looks like the original issue has been resolved. Could you file a new issue for the other issue in your comment, please?
