### ISSUE TITLE
update rancher charts for k8s 1.16 as of 10/15

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#22005]
Update the existing [rancher/charts](https://github.com/rancher/charts) to a newer version for 2.3 release

1. make the updated charts to be compatible with k8s v1.16
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#action-required

**Comment by deniseschannon** [comment]
1.16 compatible charts - rancher/charts#272

**Comment by deniseschannon** [comment]
10/15 available charts in the `k8s-1.16` branch: 

etcd-operator v0.8.4
vault-operator v0.1.3
chartmuseum v2.3.1
drone v2.0.7
traefik v1.7
docker-registry v1.8.1
memcached 2.9.0
nfs-server 0.3.0
mongodb-replicaset chart to 3.9.6
kubernetes dashboard to 1.8.0
efk v7.3.0
datadog chart to v1.33.0
Kafka to v0.8.0
Hadoop to v1.1.1
grafana to v3.8.6
prometheus chart to v9.1.0
mariadb chart to v6.7.4
Magento v5.1.4
mongodb to v7.2.6
wordpress to v7.3.8

**Comment by deniseschannon** [comment]
@jiaqiluo For any chart that has an issue, please open a new issue for each one as it's easier to debug/track for dev/QA purposes.

**Comment by deniseschannon** [comment]
Added charts as of 10/17
Harbor v1.2.0
phpbb v6.0.1
 Redis 0.9.2 chart
Fluentd-aggregator 0.3.1

**Comment by jiaqiluo** [comment]
Steps:
- run Rancher:v2.3-head e7ac6ffe6
- change the global library's branch to `k8s-1.16` 
- enable Github Auth 
- log in as a Github user, provision a k8s `1.16.2` cluster with 1 etcd + control plane, 3 workers
- add a new project and deploy apps

Here is the list of all apps and their template versions that passe the test 
 
App | Template version
-- | --
etcd-operator | 0.9.0
vault-operator | 0.1.3
chartmuseum | 2.3.1
drone | 2.0.7
traefik | 1.0.0
docker-registry | 1.8.1
memcached | 2.9.0
nfs-server | 0.3.0
mongodb-replicaset | 3.9.6
kubernetes   dashboard | 1.8.0
efk | 7.3.0
datadog | 1.33.0
Hadoop | 1.1.1
grafana | 3.8.6
prometheus | 9.1.0
mariadb | 6.7.4
mongodb | 7.2.6
wordpress | 7.3.8
Harbor | 1.2.0
phpbb | 6.0.1
Fluentd-aggregator | 0.3.1


Here is the list of all apps and their template versions that have issues


Apps | Template version | GH issue
-- | -- | --
Kafka | 0.8.0 | https://github.com/rancher/rancher/issues/23460
Magento | 5.1.4 | https://github.com/rancher/rancher/issues/23528
Harbor | 1.2.0 | https://github.com/rancher/rancher/issues/23529

**Comment by guangbochen** [comment]
Add charts as of 10/18
App | Template version | Related PR
-- | -- | --
mysql | 1.3.1 | https://github.com/rancher/charts/pull/288

@jiaqiluo I think we can have this issue open to link all charts tests, thanks.

**Comment by jiaqiluo** [comment]
The following chart is validated in the clusters with k8s 1.15 and 1.16 in rancher:v2.3-head 

App | Template version | Related PR
-- | -- | -- |
mysql | 1.3.1 | https://github.com/rancher/charts/pull/288

**Comment by guangbochen** [comment]
@jiaqiluo, since all issues for k8s 1.16 related charts are fixed, can we close this issue, thanks.
