### ISSUE TITLE
UI - Edit cluster should not allow for downgrading K8s version.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#22018]
Rancher server version - Build from master

Steps to reproduce the problem.
Create a cluster with K8s version - 1.14.4.  (No Cluster Templates).
Edit cluster.
Notice that we are allowed to  downgrade K8s version.

<img width="552" alt="Screen Shot 2019-08-06 at 2 32 09 PM" src="https://user-images.githubusercontent.com/4266958/62579059-9a2fcc00-b857-11e9-9cd5-f60d78d94bc5.png">

In this case , 1.13.8 should have been greyed out and listed as "unsupported).

**Comment by davidnuzik** [comment]
Version: master-head (8/7/19)

I am no longer allowed to downgrade k8s version when editing a cluster. This is true without a CT and even with a CT.

![image](https://user-images.githubusercontent.com/45179589/62661542-39bb9000-b926-11e9-9cda-d36f7767b1a8.png)
