### ISSUE TITLE
release channels

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2201]
Because of the issue reported at #2196, I've been thinking in the usability to have auto-updates on server based on release channels. 

At this point, i cannot find anywhere information about a stable release. As so, it would be great to have release channels as docker tags and allow rancher-server to re-run a new image with data, based on a new image pull.

**Comment by fernandoneto** [comment]
+1

**Comment by will-chan** [comment]
Part of the original reasons for our weekly milestone releases was to get our features out sooner for people to try and provide feedback.  Given that the number of deployments have grown immensely within the past 3-4 months, we are already talking about changing our weekly releases to release candidates (bleeding edge releases with no upgrade testing) and ship a more stable release (maybe monthly) when it has been more fully baked.  We are already on a path to the GA so certainly this new release plan will take action after GA.  We are currently debating whether to implement this before that.

**Comment by cusspvz** [comment]
@will-chan thanks for your response. :smile: 

Inspite that workflow could bring up new features right away to *rancher* users, that doesn't mean they are well tested and production-ready. Thats what I will try to cover up with this issue.

I've liked the approach CoreOS has taken. They have in mind all future implementations as you are having, but their `alpha`, `beta`, `stable` release pick up is apart from the development flow (semver). Instead, they keep filtering up versions by stability between channels.

As so, all their releases go into `alpha` channel. From then they pick up the most stable ones into `beta` channel. Same approach is applied from `beta` to `stable`, meaning that `stable` is always the best choice for production and you will always know which well-known bugs it has.

In my humble opinion, and to complement my proposal, Rancher is amazing! You all did a great job so far, and this is the only thing it misses to really be what it should be **A Platform for Operating Docker in Production**.

**Comment by deniseschannon** [comment]
As of GA, we now have a `stable` release tag and our `latest` tag.

see more details: http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/#rancher-server-tags
