### ISSUE TITLE
[UI] Mobile - Improve Mobile Support

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22010]
Version: master-head (v2.3) (8/6/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce:**
Use Rancher UI on a mobile device with average sized screen. Smoke test by visiting various locations and interacting with the UI.

**Issues:**
- [x] At login screen, if click on Translations drop down it's cut off. (This also happens when logged in).
![SmartSelect_20190806-103351_Chrome](https://user-images.githubusercontent.com/45179589/62564684-2d5a0900-b83a-11e9-9b1d-6cc5b91adc9b.jpg)

-----

- [ ] When open the user menu the footer moves up and there is an odd artifact at the right of the page.
![SmartSelect_20190806-103705_Chrome](https://user-images.githubusercontent.com/45179589/62564768-511d4f00-b83a-11e9-853c-7f7f2e399000.jpg)

-----

- [ ] When create or edit a cluster the placement of fields/objects is all over the place (edit shown below). Also at the bottom of the page the Save/Cancel buttons are partially cut off.
![SmartSelect_20190806-103852_Chrome](https://user-images.githubusercontent.com/45179589/62564827-698d6980-b83a-11e9-8d4a-3f6e103bc6f1.jpg)

-----

- [ ] When you view the global page showing the list of clusters. If a cluster has any issues and has multiline text explaining the issue this is cut off.
![SmartSelect_20190806-103548_Chrome](https://user-images.githubusercontent.com/45179589/62565070-e0c2fd80-b83a-11e9-9819-8434c9d3de29.jpg)

-----

- [ ] Similar to above, if we view Projects/Namespaces page there is a lot of white space below the page header.
(No screenshot shown, similar to above white space below page header)

-----

- [ ] At the cluster level, open the global menu at the top right, click on the "Tools" submenu. Nothing happens and the global menu is dismissed so we can't navigate to the tools submenu items. The same is true for other submenus.
(No screenshot shown, just perform the steps to reproduce this)

-----

- [ ] Monitoring - When try to change to custom timeframe, UI doesn't look right.
![SmartSelect_20190806-104217_Chrome](https://user-images.githubusercontent.com/45179589/62564953-a8bbba80-b83a-11e9-82d6-c55374133ac1.jpg)

-----

- [ ] Monitoring - UI does weird wrapping in some situations like pictured below. This is probably true in other areas too like node/cluster details page with small window width.
![SmartSelect_20190806-110308_Chrome](https://user-images.githubusercontent.com/45179589/62564971-b40ee600-b83a-11e9-8173-205d3623830f.jpg)

-----

- [ ] Menus tend to open very wide taking nearly 100% screen width for some reason.
![SmartSelect_20190806-110051_Chrome](https://user-images.githubusercontent.com/45179589/62564983-ba04c700-b83a-11e9-9c6e-a1130bb880c0.jpg)

-----

**Other details that may be helpful:**
I tested on Samsung Galaxy S8+ with Chrome for Android.

Related: https://github.com/rancher/rancher/issues/16926

**Comment by davidnuzik** [comment]
This is not an exhaustive list. The UI still needs further review even past these identified issues with a mobile view.
We still have other concerning issues as well such as https://github.com/rancher/rancher/issues/16794 which blocks using UI Global Menu on mobile

**Comment by lvuch** [comment]
A lot of these are js issues. #2 user menu, and #3 js is adding 100px on top of sortble-table
