### ISSUE TITLE
Allow private registry to be more easily configured during Rancher HA air gap install

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher#22014]
I'm revising the HA air gap install docs so that people are encouraged to configure the private registry with an environment variable during the Rancher installation instead of configuring the private registry from the Rancher UI. This update led to @deniseschannon 's suggestion: users should be able to configure the private registry directly when they install Rancher, instead of having to use an environment variable.

**What kind of request is this (question/bug/enhancement/feature request):**

Feature request

**Comment by deniseschannon** [comment]
It should be an option in the helm chart.

**Comment by guangbochen** [comment]
Link to https://github.com/rancher/rancher/pull/22291

**Comment by jiaqiluo** [comment]
The enhancement is validated in Rancher:v2.3.0-rc1 air-gap HA mode

Now we can pass the `systemDefaultRegistry` option when rendering the templates for Rancher

```
helm template ./rancher-2.3.0-rc1.tgz --output-dir . \
 --name rancher \
 --namespace cattle-system \
 --set hostname=jiaqi-ag-lb-e4f7e0724eaa18d0.elb.us-west-1.amazonaws.com \
 --set rancherImage=your-private-registy/rancher/rancher \
 --set systemDefaultRegistry=your-private-registy
```

After Rancher is available, we can confirm that the value of  `system default registry` under settings is set properly
