### ISSUE TITLE
[UI] Internal IP address cut off when view workload details

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22017]
Version: master-head (8/6/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable monitoring
- View workloads details of "exporter-node-cluster-monitoring" Daemon Set

**Result:**
Internal IP address is cut off under the "Node" column.
![Screen Shot 2019-08-06 at 2 21 41 PM](https://user-images.githubusercontent.com/45179589/62578341-bf233f80-b855-11e9-900e-ad44d3a26428.png)

**Comment by davidnuzik** [comment]
test comment

**Comment by davidnuzik** [comment]
test comment

**Comment by izaac** [comment]
Version: master-head (8/16/19)

Now only the external IP address is shown below the node name in the node column in that table fixing the reported issue.

What I'm seeing now is that the **external** IP address is shown in both under the Image and the Node columns. The internal IP address is no longer shown in the table.

Notice the black squares in the screenshot below, those are the same external IP addresses in each row.

<img width="1319" alt="Screen Shot 2019-08-16 at 1 28 41 PM" src="https://user-images.githubusercontent.com/27659/63196731-d4088b80-c02a-11e9-990b-2c3a1da09d84.png">

We can close this issue if that's expected.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/16/19)

The change is just to widen the width of the node column. External IPs may only show up in some situations. For example in my case with an EC2 RKE cluster. However, yes this is working as expected now, my IP addresses are not cut off any longer due to the increased width of the "Node" column.

![Screen Shot 2019-08-16 at 3 42 51 PM](https://user-images.githubusercontent.com/45179589/63202036-c5c36b00-c03c-11e9-9105-a699b6458f28.png)
