### ISSUE TITLE
Rancher Logging misconfigured project Endpoint causes cluster logging crash loop

### ISSUE THREAD

**Issue by ifeldshteyn** [rancher/rancher#22011]
This affects rancher 2.2.6.

If you set fluentd in the project logging configuration and give it an invalid endpoint (ex: foo:123) then the entire rancher-fluentd loggers (every instance on each node)  would go into a crash loop. They will complain upon starting that the endpoint doesn't exist and crash. This causes all logging to halt on the entire cluster. 

Example log: 

2019-08-06 17:56:38 +0000 [info]: adding forwarding server 'ooga.booga:80' host="ooga.booga.123" port=80 weight=100 plugin_id="object:3fa3b5b1d1ac"
/var/lib/gems/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/out_forward.rb:706:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)

When you set an invalid SPLUNK HEC endpoint, it will complain that it cannot flush the buffer but it won't go into a crash loop. 

Now this is expected behavior in a misconfigured project. However, this is affecting the entire cluster logging and killing logging for all the users and projects. 

**What kind of request is this (question/bug/enhancement/feature request):**
Can we please segregate fluentd endpoint failures per project and not make it affect the entire cluster?

**Steps to reproduce (least amount of steps as possible):**
1. Go to Rancher Project logging page
2. Choose Fluentd
3. Give it an invalid endpoint Ex:  blah:123

**Result:**
Watch the System Rancher fluentd instances fail and enter a crash loop causing clusterwide logging failures.

**Other details that may be helpful:**
This does NOT happen with a misconfigured Splunk HEC (I haven't tested other endpoints).

**Environment information**
- Rancher version 2.2.6 
- Installation option: HA

**Cluster information**
- Cluster type: Hosted
- Machine type VM with 281 gigs and 128 cpu cores. versio nv1.13.7
- Kubernetes version 

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Docker version

Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

>

**Comment by contain-me-not** [comment]
in rancher 2.2.6, each of our projects is configured to log to a _custom_ `fluentd` pod, which performs some processing before forwarding the logs to another endpoint.  these _custom_ `fluentd` pods live within the project and so can be controlled/modified by the project owners.  if _one_ project owner deletes their _custom_ `fluentd` deployment without removing the project logging configuration, it crashes the **_rancher_** `fluentd` pods and takes down logging for **_all projects_** in that cluster.

**Comment by ifeldshteyn** [comment]
@aiwantaozi 

Hi, I did some digging and it seems rancher's fluentd executes a copy and forward stanza. Here is what I am seeing on our end. 

`<match  cluster.** cluster-custom.** > 
  @type copy
  <store>
        @type forward
        compress gzip
        <server>
          host cluster-logging.cluster-logging.svc.cluster.local
          port 80
          weight  100
        </server>
        <buffer>
          @type file
          path /fluentd/log/buffer/cluster.buffer
          flush_mode interval
          flush_interval 60s
          flush_thread_count 8
          queued_chunks_limit_size 200
        </buffer> 
        slow_flush_log_threshold 40.0
</store>`

Is it possible to try out https://docs.fluentd.org/output/copy#ignore_error-argument  ? 
It may prevent project-level misconfigurations from affecting the entire cluster.

Thanks!

**Comment by stayfrostnl** [comment]
+1

We are also encountering this issue. When consumers uses project-level logging and misconfigure it, its blocks the whole fluentd daemonset from sending it to Elasticsearch. Anyway to work-around this issue?
