### ISSUE TITLE
add features to `docker-machine` host driver that it already has

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2202]
It would be wonderful if we could bind some features from `docker-machine` to `docker-machine` host driver on UI such as:
- [ ] `docker-machine restart`
- [ ] `docker-machine ssh`
- [ ] `docker-machine upgrade`

**Comment by cusspvz** [comment]
Just tried to use configs provided by rancher, even after fixing up all paths, they doesn't work.

**Comment by will-chan** [comment]
restart and upgrade are easier.  SSH might be a bit trickier since we have to integrate it similarly to how we expose docker "exec".

**Comment by demarant** [comment]
+1

**Comment by taketnoi** [comment]
+1

**Comment by demarant** [comment]
+1

**Comment by rvion** [comment]
+1

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
