### ISSUE TITLE
[UI] Istio - Project-level Istio Prometheus URL is wrong

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#22023]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Enable Istio.
2. Go to project-level istio page
3. Click the Prometheus icon.

**Result:**

The URL is linked to Grafana UI.

**Environment information**
master (2019/08/07)

**Comment by rootwuj** [comment]
Test with rancher/rancher:master-head bc3700f8 8/7
The user clicks the project-istio Prometheus icon. Can link to Prometheus UI.
