### ISSUE TITLE
Istio - https port does not work with ingress gateway

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#22024]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create cluster
2. Enable istio with ingress gateway of type NodePort
3. Enable auto-injection on a namespace
4. Import bookinfo service
5. Generate traffic on the service by going to the URL

**Result:**
The app cannot be accessed via `https://<gatewayurl>:<https_port>`

**Other details that may be helpful:**
The app can be accessed via `http://<gatewayurl>:<http_port>`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
rancher/rancher:master-head bc3700f8 8/7
- Installation option (single install/HA):
single install

**Comment by gitlawr** [comment]
Can you show the gateway spec? I can access HTTPS ingress gateway with proper TLS configurations. For reference: https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/

**Comment by loganhz** [comment]
Confirmed not an issue
