### ISSUE TITLE
[UI] Cluster Templates - Edit cluster k8s version list issue when created from cluster templates that have version with ".x" format.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#22021]
Rancher server version - Build from master:

Scenario1:
Create a cluster template from UI with kubernetes version set to 1.14.x (no override) .
Create cluster using this template using 1.14.4 version.
Edit cluster.

<img width="669" alt="Screen Shot 2019-08-06 at 5 14 07 PM" src="https://user-images.githubusercontent.com/4266958/62585446-acb50000-b86d-11e9-8f91-6121a24c7cae.png">

Expected Behavior - There should be no 1.14.x entry and the existing K8s version should be selected.

Scenario2:
Create a cluster template from UI with kubernetes version set to 1.14.x (with override) .
Create cluster using this template using 1.14.4 version.
Edit cluster.

<img width="682" alt="Screen Shot 2019-08-06 at 5 13 43 PM" src="https://user-images.githubusercontent.com/4266958/62585448-b0488700-b86d-11e9-8d44-dff630b5fcf0.png">

Expected Behavior - There should be no 1.14.x entry and the existing K8s version should be selected.
Also `1.13.8` should be greyed out and marked "not supported"

**Comment by davidnuzik** [comment]
Version: master-head (8/7/19)

Scenario 1: Create CT with k8s version set to 1.14.x WITHOUT override

UI appropriately shows dropdown now. This wasn't working before the fix.
![image](https://user-images.githubusercontent.com/45179589/62663045-f6175500-b92a-11e9-80da-4220782d9ae6.png)

Although I do not understand why this is interactive. (Why am I allowed to access the dropdown at all?)

Scenario 2: Create CT with k8s version set to 1.14.x WITH override this time

UI appropriately shows the k8s drop down now:
![image](https://user-images.githubusercontent.com/45179589/62663091-23fc9980-b92b-11e9-8db3-1f199fc90b5c.png)
