### ISSUE TITLE
Rancher 2.x - Enable Kube-API Audit Logging

### ISSUE THREAD

**Issue by Kralor-Guldan** [rancher/rancher#22034]
**What kind of request is this (question/bug/enhancement/feature request):**
Question: How do I enable kube-api audit logging using rancher 2.x?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.5
- Installation option (single install/HA):
HA

**Comment by superseb** [comment]
You can see how to change arguments/binds/environment variables for Kubernetes components here: https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-add-additional-arguments-binds-environment-variables-to-kubernetes-components-in-a-rancher-launched-kubernetes-cluster

Regarding auditing, we also have the hardening guide here: https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.2/
