### ISSUE TITLE
dns

### ISSUE THREAD

**Issue by fkklx** [rancher/rancher#22030]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`global-admin.global-dns.providers.new`|

**Comment by fkklx** [comment]
![image](https://user-images.githubusercontent.com/50471051/62612584-3d591200-b93a-11e9-80a0-04d6cda7f594.png)

**Comment by loganhz** [comment]
Fixed
