### ISSUE TITLE
Add bash-completion support for Rancher CLI

### ISSUE THREAD

**Issue by jnicholls** [rancher/rancher#22035]
Feature Request: Add bash completion support to the `rancher` CLI. It would also be great for it to pass down to the `kubectl` completion if it is available on the system. Seeing how the `kubectl` sub-command is implemented, that may be a little tricky. I would change the CLI context to not only load the `cli2.json` config file, but to also pro-actively retrieve the kubeconfig file for the current context and store that in `.rancher` as well, instead of retrieving the kubeconfig on-demand in the `kubectl` sub-command. Based on the stored kubeconfig's creation time, the CLI could regularly attempt to refresh it first-thing before any sub-commands are executed. Just a thought.

**Comment by uvwild** [comment]
Dont we get sooo spoiled with those things?
the times before bash completion are almost forgotten   :)

**Comment by jnicholls** [comment]
@uvwild Indeed! It would be extremely handy and convenient to have. I'm renewed in my sadness and doubt of Rancher's ability to manage their open source projects well, seeing this ticket go unacknowledged for over 10 months. Thanks for highlighting this @uvwild 😭

**Comment by fabiorauber** [comment]
Still a nice feature to have!
