### ISSUE TITLE
[UI] Cluster Templates - Share Template member search does not work

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22039]
Version: master-head (8/7/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a CT. Under the "Share Template" section add a few members. Try searching
- Clone the CTR, search box is gone under "Share Template" section

**Result:**
Searching does not work; no results will be shown for users. When you try to search while creating a CT the user names will be wiped out when you cancel searching (remove all text in the search field):
![image](https://user-images.githubusercontent.com/45179589/62651439-e0476700-b90d-11e9-8a17-332607682e1c.png)
When we clone our CTR the search box is now gone in the "Share Template" section (not sure if this is expected)
![image](https://user-images.githubusercontent.com/45179589/62651587-2ac8e380-b90e-11e9-9fe0-e859bbf04277.png)

**Other details that may be helpful:**

_**We may want to consider just completely removing the search box here when we create CT**_
I think there is little value in the search box in this area. If someone needs to share with many users those should be groups.

**Comment by westlywright** [comment]
I agree with you that we don't really gain much my having this search here so I will remove it.

**Comment by davidnuzik** [comment]
Version: master-head (8/7/19)

I can confirm we removed the search functionality:
![image](https://user-images.githubusercontent.com/45179589/62663186-6aea8f00-b92b-11e9-85c2-0411041e128d.png)

Sharing still works without any issues.
