### ISSUE TITLE
Remove option to set Environment Variables from pipeline's Publish Catalog Template step in UI

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#22031]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

When configuring the Publish Catalog Template step in a pipeline within the Rancher UI, the option to set Environment Variables is presented. However, per conversation with @gitlawr, it is not possible to reference custom set environment variables within this step, so this option is misleading.

**Environment information**
- Rancher v2.2.4

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/22057

Per @gitlawr we can fix it instead of removing it from UI.
