### ISSUE TITLE
Agent - Connection pool is full

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#2204]
```
2015-10-01 13:55:13,842 WARNING requests.packages.urllib3.connectionpool [140708359895312] [connectionpool.py:272] Connection pool is full, discarding connection: xxx.xxx.xxx.xxx
```
```
Rancher	v0.39.0
Cattle	v0.95.0
User Interface	v0.52.0
Rancher Compose	beta/latest
```

The parent host for this agent is showing as 're-connecting'. The error seemingly comes out the blue. We are building many services, upgrading them, destroying them again and again...

**Comment by Rucknar** [comment]
Agent then failed to stop with a 'docker stop' command, had to kill it and re-run it up. Seems okay after being restarted. It had been running 3 days.

**Comment by deniseschannon** [comment]
Can you provide us the agent logs from the stopped rancher/agent? 

http://docs.rancher.com/rancher/faqs/troubleshooting/#agent-logs

**Comment by Rucknar** [comment]
I've looked but can't seem to find the logs for that instance i'm afraid. I'll close the issue and re-open it should it appear again with some more context.
