### ISSUE TITLE
Cluster Template - Cluster owner update visibility 

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#22047]
Version:  rancher/rancher:master-head 8/7/2019 

As an admin/cluster owner (particularly of multiple clusters) it is not easy to tell which template and revision is being used. As an admin, if I am enforcing compliance/configuration, I need to be able to see the revision and template each cluster is using.

Similarly, when a new revision of the template is created, there is no way to identify which clusters need to upgraded / modified.

**Comment by codyrancher** [comment]
I threw together this mock. Is this kind of what you had in mind?
![Screen Shot 2019-09-18 at 11 58 29 AM](https://user-images.githubusercontent.com/55104481/65177614-e00db180-da0b-11e9-8f27-771cb2d7fdd8.png)

**Comment by codyrancher** [comment]
@cloudnautique just checking in to see if you've had a chance to take a look at my mock above.

**Comment by codyrancher** [comment]
@tfiduccia would you mind taking a look at the mock above and let me know if you have any feedback on changing how it looks?

Also, do you have any feedback on what you think we should sort that field on? I currently have it sorting on clusterName then revisionName. @westlywright had made a suggestion that we instead sort on whether or not an upgrade was available.

**Comment by deniseschannon** [comment]
@cloudnautique Would you want the reverse where on the RKE templates page, for each revision, you'd be able to see which clusters are using that revision?

**Comment by cloudnautique** [comment]
@deniseschannon no, I don't think so. I like that it is pulling it to a more scoped location, but I think it will get really busy once we do create template from existing cluster. @tfiduccia suggested maybe a details page with the cluster template as a separate issue, but for now she has some suggestions that I think will work well. She will update here.\

**Comment by tfiduccia** [comment]
@codyrancher - Instead of adding another row.  Let's :
1.  If upgrade available, on right side of cluster name add "icon-notification" icon with yellow background.  On hover, make a tooltip come up that says "Version <%rke-version-name%> available for upgrade."
2.  On cluster dashboard, change "Version:" to "Kubernetes Version:"
3.  After Kubernetes Version column, add column with "RKE Template:" <%template-name%>/<%version-name%>, then notification icon with tooltip info to right if upgrade available.

**Comment by codyrancher** [comment]
@tfiduccia 
In these examples V0 would be the latest revision.

Clusters page:
![Screen Shot 2019-09-25 at 12 59 03 PM](https://user-images.githubusercontent.com/55104481/65635700-aa317580-df95-11e9-99aa-8d3134ce6bb9.png)

Cluster page:
![Screen Shot 2019-09-25 at 12 58 47 PM](https://user-images.githubusercontent.com/55104481/65635702-aa317580-df95-11e9-9410-68f1a0b04780.png)

I made one change from your original ask:
1. I switched from 'version' to 'revision' to be consistent with the RKE Templates page verbiage.

Here's a couple questions that came up while implementing:
1. I noticed there's an icon/tooltip for warnings and cert expiration beside the cluster name as well. Both of these are using the 'icon-alert' icon. Would you prefer I use 'icon-alert' instead?
1. Do you want me to keep my change to 'revision'? If so do you want me to switch Kubernetes Version back to Version on the cluster page?

**Comment by tfiduccia** [comment]
@codyrancher 
1.  Revision is fine, but I would still like to keep "kubernetes version"
2.  Vincent thought the icon-alert would be too much "!" for an upgrade.  So I compromised on the icon-notification instead

Question back:
Is that the standard icon size?  Cause it looks a bit big.  Can we make sure with Lauren that size i the correct one?

**Comment by codyrancher** [comment]
@tfiduccia the icon library uses em for the size which means the icons will pretty much always be relative to the current font size where you insert the icon. We can however adjust the size of this icon no problem.

Here's a few samples otherwise we can adjust while you're here.
circle: 1.5em notification: 1em
![Screen Shot 2019-09-25 at 3 25 48 PM](https://user-images.githubusercontent.com/55104481/65644706-d8b94b80-dfa9-11e9-82ae-51dc4b072089.png)

circle: 1em notification .75em
![Screen Shot 2019-09-25 at 3 30 45 PM](https://user-images.githubusercontent.com/55104481/65644731-ef5fa280-dfa9-11e9-8c44-1a34502aaad1.png)

circle: 1.25em notification: 0.85em
![Screen Shot 2019-09-25 at 3 33 09 PM](https://user-images.githubusercontent.com/55104481/65644739-f5558380-dfa9-11e9-8664-41e2c2cb2efa.png)

**Comment by lvuch** [comment]
@codyrancher @tfiduccia  I'm not sure it's the font size, but also the visual weight. I think something closer to the visual style of `class="banner bg-warning"` 
<img width="139" alt="Screen Shot 2019-09-25 at 3 57 35 PM" src="https://user-images.githubusercontent.com/3013118/65645687-4e72e680-dfad-11e9-9e5f-23ec7498f55c.png">

**Comment by tfiduccia** [comment]
@codyrancher - I'm good with just changing the color and leaving the icon font size.

**Comment by codyrancher** [comment]
Thanks @lvuch and @tfiduccia. Here's updated screenshots based on the feedback.

![Screen Shot 2019-09-26 at 9 15 18 AM](https://user-images.githubusercontent.com/55104481/65706476-6abf6380-e03f-11e9-9fee-66321a733855.png)
![Screen Shot 2019-09-26 at 9 12 07 AM](https://user-images.githubusercontent.com/55104481/65706478-6abf6380-e03f-11e9-8130-a0f064b00f74.png)

**Comment by deniseschannon** [comment]
@codyrancher if there are multiple revisions available what does the UI show?

**Comment by codyrancher** [comment]
@deniseschannon  It shows the latest revision.

**Comment by codyrancher** [comment]
@tfiduccia it looks like we want to try and get this feature into 2.3. Are you okay with signing off on the latest?

**Comment by tfiduccia** [comment]
@codyrancher - Yes, I'm good with it.

**Comment by soumyalj** [comment]
Tested with master-head build from Sep 27. 

Some of the use cases tested: 

*For a Cluster owner
1. If a new revision is available,  Display icon with the the latest revision available.Cluster Dashboard page should show template/revision and icon with tool tip 
2. When multiple revisions are available (v1, V2, V3), If  revision V3 is deleted, then V2 must be available as the latest revision available
3. Disable a revision and disabled revisions must not be displayed as available for upgrade 

* Test as cluster member or with custom role

The below issues have been filed:
https://github.com/rancher/rancher/issues/23125
https://github.com/rancher/rancher/issues/23126
