### ISSUE TITLE
[UI] Cluster Templates - Should block CT creation with Azure Cloud for required fields when override NOT set and string is null

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22041]
Version: master-head (8/7/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a CT. Pick "Azure" for the cloud option. Do NOT set any overrides. Do NOT supply ANYTHING in the template (make no changes). Submit.

**Result:**
We should not have been allowed to submit the form. This is because we picked "Azure" cloud and did not include values for the four required fields. Related to https://github.com/rancher/rancher/issues/21759

Basically, if it does not require significant effort, I think we should block creation of the cluster template in the situation where we are NOT providing overrides for the fields AND NOT providing values. Basically, today we can have a user create a broken cluster template because the required fields are not questions and have empty values.

This doesn't make sense -- we are allowing the user to (fairly easily) get in to a bad state with their CT. The UI should block creation of the template in this case for these four fields if they do not have an override and do not have a value set. If an override IS set then continue to allow CT creation even if value is empty (Since user can then fill out these required fields when leveraging the template).

**Comment by davidnuzik** [comment]
@vincent99 this may not be related to your changes but I see this now:
![image](https://user-images.githubusercontent.com/45179589/62984055-87cd0980-bde6-11e9-8d58-7421171f3610.png)

And "Saving" button keeps going with html spinner

If not related I'll create another issue to track.

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/22/2019)

I now see an error wether any of the mandatory fields are missing or all of them. And either selected for override or not.

<img width="1264" alt="Screen Shot 2019-08-22 at 10 22 19 AM" src="https://user-images.githubusercontent.com/27659/63535781-16b4e280-c4c7-11e9-8fab-d1edcacada7a.png">

There are so many inputs in that page, specially for when the Azure cloud provider is selected. Would it be possible to also add a visual indicator for the user to see which are the missing mandatory fields for creating the CT? 

@vincent99

**Comment by davidnuzik** [comment]
We should NOT show the error when we have applied an override to any/all of these four fields. We should ONLY throw the error when we do NOT have an override set for any.

**Comment by izaac** [comment]
I think we should throw the error if there's an override but has an empty value. Which is how is currently behaving. @davidnuzik

**Comment by davidnuzik** [comment]
We should not actually. If there is an override then the end-user can supply the string needed. This issue was created because we need to only throw these errors when an override is NOT set and the string for that field is null. When an override is not set and the field (string) is null, it's impossible for the end-user leveraging the template to actually utilize azure cloud features because they can't possibly plug in the required fields.

When an override is set on any of these fields they may be null and should never throw an error -- the use case is an admin creates a CT and they perhaps want people leveraging the CT to plug in one or more of these fields, so those have overrides for the end-user has to plug in that/those string(s). But the Admin may have one or more NOT have any overrides and the admin is then therefore responsible for plugging in the string -- otherwise the CT is useless to the end user.

So, this issue (validation) needs to ensure that only in the case where one of these four fields does NOT have an override set AND is null string, then and only then do we throw the error(s). 
Any other situation should result in reopening this issue.

There is an argument to be made that we might want to _warn_ the user when they have an override set and the string is null because this could alert the person making the CT that the end-user will have to enter the string (and therefore know the secret(s)). We could optionally open an issue (enhancement) to request this functionality.

**Comment by davidnuzik** [comment]
Please contact me if there is any confusion. Hopefully this clears it up.

**Comment by izaac** [comment]
@davidnuzik  it makes sense to me and even more with the warning enhancement idea. Ok so as of the current implementation the UI is enforcing the user to fill those mandatory inputs even if the override is set for those (empty or not).

That should get fixed. @vincent99

**Comment by davidnuzik** [comment]
Reopened issue.

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (09/03/2019)

Now if any of the mandatory fields is marked to override this won't alert the user of missing mandatory fields if they are left empty and the revision will be saved.

If the mandatory fields are marked as override and filled, no alerts.

If any combination of mandatory field is not marked as override and is left blank, an alert will be displayed to the user.

This is now meeting all the requirements.
