### ISSUE TITLE
[UI] Istio may be overestimating required mCPU and may not check properly when enable monitoring first

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22040]
Version: master-head (8/7/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an EC2 RKE cluster with 3 worker nodes each of instance type t2.large
- Attempt to enable Istio (ensure you Enabled Ingress Gateway as well) (You won't have enough CPU)
- Manually enable monitoring first, now we can enable Istio (But shouldn't have enough CPU?)

**Result:**
Istio config UI claims we must have a minimum of 5150 milli CPUs available. (If you don't see this try creating a workload that reserves about 100mCPU first).
![image](https://user-images.githubusercontent.com/45179589/62654752-5a2f1e80-b915-11e9-9358-6e5657e9b823.png)

Is this 5150 milli CPUs correct? I recall monitoring needing only about 1650 mCPU by default. If I add up the mCPU requests in the Istio config UI it's only:
Pilot: 500
Mixer Telemetry: 1000
Mixer Policy: 1000
Tracing: 100
Ingress Gateway: 100
Istio SUM: 2700 mCPU
Monitoring: 1650 mCPU
Grand Total: 4350 mCPU

Are we missing something? Perhaps there are other Istio-related workloads that are not customizable that the JS check is including to come up with 5150mCPU required?

**_If I manually enable monitoring first (with defaults) then enable Istio I'm not longer getting a message showing I have insufficient CPU. This is confusing to me._**

**Other details that may be helpful:**
I tried to review UI JS code for Istio. I see the const vars such as these:
```
const NODE_EXPORTER_CPU = 100;
const NODE_EXPORTER_MEMORY = 30;
const MONITORING_CLUSTER_CPU = 900 + 750;
const MONITORING_CLUSTER_MEMORY = 970 + 750;
const ISTIO_CLUSTER_CPU = 500;
const ISTIO_CLUSTER_MEMORY = 500;
```
But was unable to read through and understand all the logic that came up with the 5150 mCPU value. We are just requesting some more information and want to doubly check this is correct.

**Comment by davidnuzik** [comment]
Additionally, I noticed that often when we enable monitoring first, then Istio not all workloads can deploy because we indeed seem to have insufficient resources. 

So perhaps this reveals that the JS checks for resources may be correct as far as value, issue is that if enable monitoring first then istio JS check doesn't work right on Istio config page.

![image](https://user-images.githubusercontent.com/45179589/62656554-4ab1d480-b919-11e9-9041-14fbd40f1e9a.png)

**Comment by n313893254** [comment]
- Monitoring CPU reservation: Prometheus + node.length * Node-exporter + min-cpu, so it is   750 + 3 * 100 + 900 = 1950 mCPU
- Istio CPU reservation: Pilot + ...  + min-cpu = 2700 + 500 = 3200 mCPU

So when Monitoring is disabled, Enable Istio required 1950 + 3200 = 5150, the check is as expected.

But enable Monitoring using 1700 mCPU in fact. There will be 250 mCPU left and Istio can enable it. So enable Monitoring first, Istio can enable is as expected.

Then enable Istio, I can reproduce the issue, istio-pilot cannot deploy success. Check the cluster page and node page.
![image](https://user-images.githubusercontent.com/18737885/62672983-3e884e80-b9cf-11e9-8705-32ecddf50c72.png)
![image](https://user-images.githubusercontent.com/18737885/62672996-4e079780-b9cf-11e9-8424-67ad3b6fbab5.png)

The cluster left 1100 mCPU, but in every node, there have no 500 mCPU left for deploy istio-pilot.
I think is as expected.

**Comment by loganhz** [comment]
@davidnuzik could you provide more info about how to reproduce it, please?
Like  enable istio very quickly after enable monitoring

**Comment by davidnuzik** [comment]
@n313893254 was the setup the same as mine? 3 worker nodes t2.large ec2 nodes? this specifically seems to cause the issue. May need to also create 1 deployment such as ubuntu:xenial that reserves 100mCPU before you attempt to reproduce.

and @loganhz yes it's possible timing is a factor actually. I enable monitoring then fairly quickly enable istio afterwards. Istio does not warn that I have insufficient CPU when I quickly go to the istio config page right after quickly enabling montioring and not all istio deployments may succeed (runs out of resources). 

Both @bmdepesa and myself have run into this issue. I have reproduced a couple of times now.

**Comment by davidnuzik** [comment]
The PR makes sense and seems to fix the overestimating.

We still run into this issue though. Quickly enable monitoring then istio; Istio does not complain about insufficient resources. some workloads will fail to load due to insufficient resources

![image](https://user-images.githubusercontent.com/45179589/62971437-baffa080-bdc6-11e9-9608-fdb82b854650.png)

Is it expected behavior that when we enable monitoring then quickly enable istio to run into this problem?

If so, does it make sense for me to create a separate issue for this so we can perhaps look into this further later? (probably post v2.3 release)

**Comment by davidnuzik** [comment]
Reopening for my question.

**Comment by vincent99** [comment]
Quickly as in the helm chart is still deploying stuff?  They should both be looking at what is available (unreserved) on what's running on the cluster.

If it's not all reserved yet because the first I've is still deploying, there's no reasonable way to speculate how much is going to be reserved "soon" and then see if what's left will be sufficient for the 2nd chart...

**Comment by davidnuzik** [comment]
Yes I figured this was the case. It seems that the workloads are still deploying and in progress by the time I quickly enable istio right after monitoring, but this is something that end-users will probably do often.

I wonder if this is worth calling out like with an info bubble or something? cc: @tfiduccia 
I don't have to do this super-fast I can do it a reasonable-amount-of-fast i.e. enable monitoring, wait several seconds, enable Istio config and run into this issue.

**Comment by loganhz** [comment]
@davidnuzik maybe we can add a warning message if the monitoring is still deploying.

**Comment by davidnuzik** [comment]
@loganhz I think this may be ideal; it takes a little while before I can safely enable istio after enabling monitoring. Others in QA have run into this issue too.

**Comment by davidnuzik** [comment]
Needs minor en-us.yaml fix
https://github.com/loganhz/ui/commit/d1ac88320dc1715af800ae146e725f48122349aa#diff-764752746bf6eae927962cbb2bb6026bR7
There were some spelling and grammar issues, but would like to tweak it overall.

"Monitoring is still deploying. Please wait for monitoring to complete deploying as Istio may not be able to deploy successfully if there are not enough resources in the cluster."

@tfiduccia could you review. Do you agree with this? If not, do you have any recommendations on how to handle this?

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/21/19)

We now show a message if monitoring is still deploying to indicate that you should wait until it is done before attempting to enable Istio. This should help reduce the chance of users running into issues enabling monitoring then istio manually.

![image](https://user-images.githubusercontent.com/45179589/63469352-d69a2500-c41e-11e9-8b62-7309d9d19300.png)

This message also disappears the second that the monitoring api is reachable.
![image](https://user-images.githubusercontent.com/45179589/63469397-f29dc680-c41e-11e9-9c5b-618499918899.png)

I tested a few times where I enable monitoring first and then istio. Each time the message shows up appropriately (only while monitoring is still deploying and api not ready).
