### ISSUE TITLE
Some node scheduling rule doesn't work as expected 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#22058]
rancher/rancher:stable

Steps:

1. Create a workload
2. Click `Node Scheduling` 
3. Click `Add Rule`
4. Input some rules as the screenshot
![image](https://user-images.githubusercontent.com/21168270/62684253-de0b0880-b9f2-11e9-9096-73981029d630.png)
5. Click `Save`

Results:

Can not create the workload

Expected:

- `>=` and `<=` are not valid operators `https://kubernetes.io/docs/concepts/configuration/assign-pod-node/`, We should remove them.
- `NotIn` should work

**Comment by sowmyav27** [comment]
### reproduced the issue in `v2.2.7`
**Steps:**

- Create a workload
- Click Node Scheduling
- Click Add Rule
- Add some rules like:
<img width="629" alt="Screen Shot 2019-08-08 at 3 24 50 PM" src="https://user-images.githubusercontent.com/26032343/62741690-b7e46900-b9f0-11e9-9a73-bcc2ccc87cd9.png">

- Click on Save.

**error seen on the UI:**
`Validation failed in API: Deployment.apps "wk011" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[5].key: Invalid value: "f not": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
`

### Validated on master-head. commit id: `bc3700f8`
**Steps:**

- Create a workload
- Click Node Scheduling
- Click Add Rule
- Add some rules like:
<img width="652" alt="Screen Shot 2019-08-08 at 3 23 37 PM" src="https://user-images.githubusercontent.com/26032343/62741722-d3e80a80-b9f0-11e9-89bb-1b2a37086808.png">
- `>=` and `<=` are not available in the `Operator` dropdown
- Click on save.
- workload gets created successfully. Is seen in `Active` state.
- Verified `NotIn` works.
