### ISSUE TITLE
[jailer] Check if cert is file, not that it exists

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#22068]
If ca-additional-certs secret does not have the key `ca-additional.pem` the jailer will attempt to copy the dir which is still mounted but will fail with the error:
`[FATAL] error running the jail command: cp: -r not specified; omitting directory '/etc/ssl/certs/ca-additional.pem`

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 210f4fa8

* Reproduced in v2.2.7
```
mkdir -p /root/certs/ca-additional.pem/
docker run -v /home/ubuntu/state:/var/lib/rancher -d -p 80:80 -p 443:443 -v /root/certs/ca-additional.pem:/etc/ssl/certs/ca-additional.pem --restart=unless-stopped rancher/rancher:v2.2.7
docker logs -f d0c
2019/08/12 20:30:57 [FATAL] error running the jail command: cp: -r not specified; omitting directory '/etc/ssl/certs/ca-additional.pem'
```

* Running the same in `master-head` does not crash with the error, and rancher starts successfully:
```
docker run -v /home/ubuntu/state:/var/lib/rancher -d -p 80:80 -p 443:443 -v /root/certs/ca-additional.pem:/etc/ssl/certs/ca-additional.pem --restart=unless-stopped rancher/rancher:master-head
```
