### ISSUE TITLE
Improve agent error when cacerts is not JSON

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#22063]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
put HA Rancher Cluster behind Cloudflare Proxy

**Result:**
cattle-node-agent pods crashing. rancher/rancher-agent:v2.2.7

**Other details that may be helpful:**
I've installed the Cluster via RKE. Maybe I need to get the hash of the cloudflare certificate? and replace the cert in the environment variables of the cattle-node-agent workload in the system project. How could I optain the hash?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:2.2.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 VMs (8 Cores 16 GB RAM)
- Kubernetes version (use `kubectl version`): 1.14.5

```
(paste the output here)
```

- Docker version (use `docker version`):
19.03

```
INFO: Environment: CATTLE_ADDRESS=91.132.145.79 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=2e76e834397ca1db5b57bfc5edc5754b732ba0285f51b5391d2f5a94b49c6549 CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=91.132.145.79 CATTLE_SERVER=https://my.domain.com
INFO: Using resolv.conf: nameserver ########### search domain.com
INFO: https://###########/ping is accessible
INFO: my.domain.com resolves to 104.24.121.210 104.24.120.210
parse error: Invalid numeric literal at line 1, column 10
```

**Comment by MSandro** [comment]
I've now generated the hash from cloudflares certificate with
`openssl x509 -noout -fingerprint -sha256 -inform pem -in cloudflare.cer` and removed the : between the letters, and wrote the string into the CATTLE_CA_CHECKSUM env variable, but this didn't solve the problem.

Hope someon knows whats going wrong. Currently the continously crashing cattle-node-agent does not affect my cluster but it would be good the get it working again.

**Comment by MSandro** [comment]
Any help?

**Comment by cjellick** [comment]
@superseb any thoughts on this?

**Comment by superseb** [comment]
This seems to break on:

```
    curl --insecure -s -fL $CATTLE_SERVER/v3/settings/cacerts | jq -r '.value | select(length > 0)' > $temp
```

Can you run `curl --insecure -s -fL $CATTLE_SERVER/v3/settings/cacerts` on the host and in the container so see what the response is?

**Comment by MSandro** [comment]
well, it was my fault, I configured cloudflares access controll feature with google authentifikation, and my IP bypass configurations was wrong. 
Nevertheless, many thanks.

**Comment by yoliander** [comment]
Hi guys, this issue was solve?

I am having the same issue in k8s.

`INFO: Environment: CATTLE_ADDRESS=x.x.x.x CATTLE_CA_CHECKSUM=c634d3a288462e204a3da64f04030333d5db4f58aba05b099f420a9e99b63c02 CATTLE_CLUSTER=true CATTLE_FEATURES=dashboard=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-5485b55f76-grl5l CATTLE_SERVER=https://rancher.my.org
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local mshome.net nameserver x.x.x.x options ndots:5
INFO: https://rancher.my.org/ping is accessible
INFO: rancher.my.org resolves to x.x.x.x
parse error: Invalid numeric literal at line 1, column 10`

Persistent CrashLoop

**Comment by VGerris** [comment]
you probably followed the tutorial and used the standard hostname rancher.my.org as it seems - that resolves to an existing public ip. it should resolve to the local rancher ip.

This command may fix your issue :
kubectl -n cattle-system patch  deployments cattle-cluster-agent --patch '{
    "spec": {
        "template": {
            "spec": {
                "hostAliases": [
                    {
                      "hostnames":
                      [
                        "rancher.my.org"
                      ],
                      "ip": "172.27.0.2"
                    }
                ]
            }
        }
    }
}'

I found it somewhere on another git post, there are other solutions, like changing the name to a working local address, but then DNS in your container should also resolve properly.
You also need to add the name to your local DNS with that IP (or /etc/hosts)
