### ISSUE TITLE
Add disk size to non-managed disks for Azure infra

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#22074]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Problem:**
Azure disk size is only used for managed disk, but it should be used for blob as well. It is a valid parameter. There is also an issue with the ui where if you switch from managed to unmanaged the disk space parameter will stay visible.

**Related issues:**
backend: https://github.com/rancher/rancher/issues/15788
ui: https://github.com/rancher/rancher/issues/21533

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher: mater-head 

Steps:
- add an Azure node template and set the `Disk Type` as `Unmanaged Disk` and `Disk Size` as `31`

<img width="1364" alt="Screen Shot 2019-08-20 at 2 34 44 PM" src="https://user-images.githubusercontent.com/6218999/63386590-4d201f80-c358-11e9-80ca-296f064814a6.png">


- create a cluster using this template 

Result:
- the VM is provisioned successfully in Azure with desired disk type and size 
- the cluster is active in Rancher

<img width="1173" alt="Screen Shot 2019-08-20 at 2 39 59 PM" src="https://user-images.githubusercontent.com/6218999/63386646-69bc5780-c358-11e9-8dcd-e33103c3d4e1.png">

**Comment by jiaqiluo** [comment]
> There is also an issue with the UI where if you switch from managed to unmanaged the disk space parameter will stay visible.

This is the expected behavior because Rancher supports setting the disk size for unmanaged disk now.
