### ISSUE TITLE
question: should a machine purge remove it from provider?

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2207]
I've successfully created (with `0.39.0`) some hosts on Azure using the `Other` and `azure` driver.
A host wen't broken, containers were kept onto a `deleting` stage, reboot didn't fixed so I tried to purge it.

As host configs wasn't working with my local `docker-machine`, I've deactivated, removed and purged using the UI.

Went to check if host was running on my provider and it was. Here's my question: Shouldn't a Delete/Purge on UI remove host on provider trough its driver?

**Comment by vincent99** [comment]
It should, yes.  @aruneli can you see if this is just Azure, all generic drivers, or if the first-class ones are broken too?

**Comment by deniseschannon** [comment]
@vincent99 @aruneli I had no issues purging DO machines using the UI.

**Comment by cusspvz** [comment]
Forgot to mention because i was writing while talking to a co-worker about internal issues. Hosts were created with `0.39.0` but were purged with `0.40.0-rc1`.

**Comment by deniseschannon** [comment]
@cusspvz Please reopen if you are still seeing this issue. We haven't been able to reproduce and I'm wondering if it's related to the other issues you were seeing with Azure hosts.

**Comment by cusspvz** [comment]
@deniseschannon deal! :)

**Comment by cusspvz** [comment]
Tested now with `0.40.0`, and **it is deleting correctly**.
Removed machine using UI, it took about 40sec. Host was displayed as `Removed` and it was purged after a page refresh.

Entered into *Azure Manager* and related cloud and machine were still running.
Waited for about 5 minutes, just to ensure, and cloud changed into `deleting` stage.

**For those who get on this issue, it may took a while to Azure apply cloud deletion.**

**Comment by deniseschannon** [comment]
@cusspvz Thanks for the update!
