### ISSUE TITLE
Add Cluster template page needs to indicate it's only for RKE clusters

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#22078]
**Comment:**
A way to indicate that the cluster template is only for RKE clusters - weird side note, we don't use the word RKE in the product or docs for rancher at all

**Comment by tfiduccia** [comment]
Add info banner to top, "From existing nodes and New nodes in an infrastructure provider only"
![image](https://user-images.githubusercontent.com/11514927/62886845-d26c5a00-bcf0-11e9-96cd-7f247a2a6391.png)

**Comment by tfiduccia** [comment]
@davidnuzik - What I actually did was change the text on the Add Cluster selection page /clusters/add/select, to include the RKE verbiage.  Then changed the cluster template info box to reference RKE.  Let me know if you have any questions.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/14/19)

I can confirm the two text string changes:

Add cluster:
![image](https://user-images.githubusercontent.com/45179589/63038156-6b2be280-be75-11e9-9b30-662951692238.png)

Create CT or clone a revision:
![image](https://user-images.githubusercontent.com/45179589/63038326-c1992100-be75-11e9-91ff-26d51ad22023.png)
