### ISSUE TITLE
Failing test test_app_rollback_validation

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#22071]
Drone publish failed https://drone-publish.rancher.io/rancher/rancher/1117/1/2

**Comment by dramich** [comment]
Nothing for QA to test and current builds have not seen the issue.

**Comment by rmweir** [comment]
http://drone-pr.rancher.io/api/repos/rancher/rancher/builds/6854/logs/1/2,
http://drone-pr.rancher.io/api/repos/rancher/rancher/builds/6772/logs/1/2

**Comment by rmweir** [comment]
https://drone-pr.rancher.io/rancher/rancher/6860/2/2
