### ISSUE TITLE
If RKEConfig key missing, throw error  & disable "Edit as Form"

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#22076]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Description of issue:**  In Add Cluster Template and Add Cluster we have changed the Edit as YAML to include "rancher_kubernetes_engine_config:" key and indentation of addons need to be indented.  If customer saved yaml from previous version, that key and indentation will not be proper and the cluster won't create

**Fix:**  
- [ ] If that key is missing on read/paste/save, throw an error that will tell them it's missing with link to proper doc page for fix.
- [ ] If that key is missing, disable "Edit as YAML"

**Comment by tfiduccia** [comment]
Issues:

-[ ] The error on Save  & Read from file needs to be on bottom of form.  On my laptop, when I click save nothing happens and I can't see the error.
![image](https://user-images.githubusercontent.com/11514927/62885359-7f44d800-bced-11e9-8fc9-aaf6c32faf74.png)

- [ ] After Error, I can't get Create to be active again.  I put the rancher_kubernetes_engine_config: tag back in but the create doesn't activate?
![image](https://user-images.githubusercontent.com/11514927/62885655-435e4280-bcee-11e9-9b24-69bf275a6ac4.png)

- [ ]

**Comment by tfiduccia** [comment]
@davidnuzik - Added errors on top and bottom so they can easily been seen.  Adding the RKEconfig tag back in reactivates the Create button.  The Edit as YAML is ready for testing.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/14/19)

I can confirm the errors are shown now both on top of the YAML and below the form right above the Create/Cancel buttons now.

![image](https://user-images.githubusercontent.com/45179589/63061875-a0ebbe00-beab-11e9-8619-219924aacc0e.png)
![image](https://user-images.githubusercontent.com/45179589/63061877-a3e6ae80-beab-11e9-8364-7c3521b9aa5e.png)

I was able to create the CT even though my `rancher_kubernetes_engine_config` - Is this expected @tfiduccia

**Comment by davidnuzik** [comment]
Reopening, based on in-person discussion, we should prevent creation of the CT if we Edit as YAML and remove the rancher_kubernetes_engine_config line.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/16/19)

We now block CT creation if the rancher_kubernetes_engine_config is missing in the YAML. You'll get an error at the top of the YAML immediately when it is removed.

If you attempt to Create, you'll get the error below the form as well.

Upon adding this back in to the YAML we are then allowed to save and create our CT.
