### ISSUE TITLE
[Backport 2.2] Failed conformance tests due to kube-apiserver node subresources permissions

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#22083]
rancher/rancher#22081

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.8

* Created a cluster w/ Rancher
  * k8s 1.15.3, 1.14.6
  * 1 worker, etcd node
  * 1 worker, controlplane node
  * 1 worker node
* Executed Sonobuoy conformance tests
* The 2 failing tests are now passing, with 0 failing tests:
```
- name: '[sig-network] Proxy version v1 should proxy logs on node with explicit
      kubelet port using proxy subresource  [Conformance]'
    status: passed
- name: '[sig-network] Proxy version v1 should proxy logs on node using proxy subresource  [Conformance]'
    status: passed
```
