### ISSUE TITLE
[UI] Cluster Templates - Kubernetes Version dropdown shows up empty on a cluster and the revision, when the revision specifies K8sVersion in the form major.minor.x

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#22085]
Version: master-head (8/8/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a CT. 
- In the CTR, set "Kubernetes Version" as an override and choose "1.14.x" as the default value
- Add Cluster using this CT and CTR
- Click on "Edit Cluster" to see the "Kubernetes Version" field value - the dropdown shows up empty and no value is shown on the cluster form.
- Also check the CTR - try to clone the CTR - the "Kubernetes Version" dropdown shows up empty on the cloned CTR form too.

**Result:**
- The K8sVersion selected on the cluster should show up on edit cluster form
- The K8sVersion set as default on the CTR should also show up

**Other details that may be helpful:**
- Screenshot of empty dropdowns on Cluster during Edit Cluster:

<img width="1336" alt="Screen Shot 2019-08-08 at 3 50 27 PM" src="https://user-images.githubusercontent.com/1470602/62744639-53c7a200-b9fc-11e9-8519-e4f79355f243.png">

- Screenshot of empty dropdown on CTR during Clone:

<img width="1337" alt="Screen Shot 2019-08-08 at 3 50 57 PM" src="https://user-images.githubusercontent.com/1470602/62744655-6215be00-b9fc-11e9-8037-914caee9ff17.png">

**Environment information**
- Version: master-head (8/8/19)- Installation option (single install/HA):
- Single node

**Comment by davidnuzik** [comment]
@izaac I would like for us to review this before you start testing please.

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/20/2019)

The dropdown is now getting populated in both "clone Cluster Template" and "Edit Cluster".

As seen in the next screenshots:

<img width="1396" alt="Screen Shot 2019-08-20 at 3 39 57 PM" src="https://user-images.githubusercontent.com/27659/63389855-ee5fa380-c361-11e9-87a4-60d3d65a3985.png">

<img width="1229" alt="Screen Shot 2019-08-20 at 3 42 30 PM" src="https://user-images.githubusercontent.com/27659/63389878-01727380-c362-11e9-88e3-fd67c200e04f.png">

Edit Cluster was fine while provisioning displaying 1.14.x, but when the Cluster status changed to **Active** I clicked again in Edit Cluster, now the version shown was 1.15.x instead of the template override, is that expected? Look at the sample screenshot below:

<img width="1728" alt="Screen Shot 2019-08-20 at 3 46 07 PM" src="https://user-images.githubusercontent.com/27659/63389933-40a0c480-c362-11e9-860b-e5e603383ca6.png">


@davidnuzik @vincent99

**Comment by davidnuzik** [comment]
@izaac if your cluster template template defined v1.14.x and when you leveraged it ended up being v1.15 then this is not expected (you mentioned it showed up when edit).
I think we should reopen this issue if this is the case.

**Comment by izaac** [comment]
@vincent99 moving the the ticket as reopened, as mentioned above the Edit Cluster was fine while the cluster was provisioning displaying 1.14.x as the dropdown's default.

After that the cluster was Active, I clicked Edit Cluster and the version in the dropdown was 1.15.x (1.14.x was still in the dropdown options).

**Comment by vincent99** [comment]
@izaac @davidnuzik I don't know how to replicate this, if it's still happening.. It's a little odd that the version stays 1.14.x while provisioning but that's a backend issue if you want it addressed.  After it's done I see the appropriate version picked and the others disabled.

![image](https://user-images.githubusercontent.com/753917/64056965-43fb3380-cb4c-11e9-9a41-2307539dadee.png)

**Comment by prachidamle** [comment]
@vincent99 I do not think this is a backend bug - after creating a cluster from the template revision (for latest 1.14 k8s version) - I see that the cluster's appliedSpec on API shows the k8s version as "rancherKubernetesEngineConfig.kubernetesVersion": "v1.14.6-rancher3-1"

But on UI, "edit cluster" form shows the latest k8s version selected in the dropdown.

<img width="1294" alt="Screen Shot 2019-09-04 at 5 15 39 PM" src="https://user-images.githubusercontent.com/1470602/64302293-a92d9b00-cf37-11e9-8cb1-df0bd5821a0d.png">
<img width="1360" alt="Screen Shot 2019-09-04 at 5 15 14 PM" src="https://user-images.githubusercontent.com/1470602/64302294-a9c63180-cf37-11e9-804b-fde28d188d2b.png">
<img width="1377" alt="Screen Shot 2019-09-04 at 5 15 04 PM" src="https://user-images.githubusercontent.com/1470602/64302295-a9c63180-cf37-11e9-9212-c2594258bb58.png">
<img width="645" alt="Screen Shot 2019-09-04 at 5 11 23 PM" src="https://user-images.githubusercontent.com/1470602/64302301-b64a8a00-cf37-11e9-97c6-0cf6ed4cc5f3.png">

**Comment by prachidamle** [comment]
@vincent99 I see that on edit form of a provisioned cluster, I see the correct k8sversion  - as long as I do not refresh the browser. Once I refresh the browser, it starts showing the latest k8sversion and not the one the cluster is provisioned with.

**Comment by prachidamle** [comment]
@vincent99 the clusters' version shown on edit cluster form on UI is changing over time. It shows correct right after the cluster is active - if you check after sometime it shows the incorrect k8sversion

**Comment by vincent99** [comment]
So the "as an override" part is important here, and I don't think I had that last time.  There's code in the UI several levels down that ends up copying the question answer values back onto the cluster config, which replaces the 1.14.6-rancher3-1 with the 1.14.x from the template definition.  Then 1.14.x isn't in the list, so the default for a dropdown is the first item in the dropdown.

So I changed 2 different places that were doing that behavior, and it fixes that problem and other stuff seems to work fine.  That's not exactly confidence-inspiring though, so editing a cluster made from a template (that is the only situation that the changes apply to) needs a good looking over again.

**Comment by izaac** [comment]
Rancher version: `master-head (v2.3) (09/11/2019)`

Now the dropdown stays in the version overridden in the CT/CTR. Both during Provisioning and Active states and going to the Edit view.

I tried setting the override to 1.14.x and 1.15.x both meeting the expectation aforementioned.

But the `Cluster Options Overrides` is empty when I go to **Edit** the Cluster that I applied the Template to.
Also when **Creating** a cluster if I select one of the CTs I don't see the overrides in the `Cluster Options Overrides`

Example Edit Custer with the Overrides table empty:

![Screen Shot 2019-09-11 at 12 09 29 PM](https://user-images.githubusercontent.com/27659/64727151-0e7c1180-d48d-11e9-9046-a5c632c6373f.png)

![Screen Shot 2019-09-11 at 12 09 21 PM](https://user-images.githubusercontent.com/27659/64727166-19cf3d00-d48d-11e9-9ef0-d94ee765e048.png)

The `Cluster Option Overrides` table only appear in Clusters created with Cluster templates it seems.

@vincent99

**Comment by westlywright** [comment]
@izaac The reason you don't see this is in the overrides section is because when consuming a template we don't show overrides for items in the config that UI components. Since the version is something the UI has built in already there is no need to show the override again. As such I think this is passing and could be move to a done state.

**Comment by sangeethah** [comment]
@westlywright @deniseschannon We do not show override entries in "Edit Cluster" pages for any questions that appears in Cluster Template that was created using UI. May be we should just hide the "Cluster Options Overrides" section .


Note - In case were we create  Cluster Templates using UI and have overrides for parameters that are not supported in Cluster Template/Cluster Create page UI, "Edit Cluster" page shows the override parameters. Do we need to provide support for this ?

**Comment by deniseschannon** [comment]
@sangeethah we are going to track hiding the "Cluster Options Overrides" in the edit cluster with this ticket: https://github.com/rancher/rancher/issues/23066

**Comment by deniseschannon** [comment]
@sangeethah I think this can be closed since we are tracking the "clsuter options overrides" section in the other ticket.

**Comment by sangeethah** [comment]
@deniseschannon Closing this issue.
