### ISSUE TITLE
[UI] Cluster - Cannot properly edit RKE cluster as cluster owner when admin created the cluster

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22080]
Similar issue: https://github.com/rancher/rancher/issues/12038

Version: master-head (v2.3) (8/8/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps and results:**
- Create a cluster (without CT) as an admin. Make a user "test1" a cluster owner.
- Log in as the "test1" user, try to edit the Cluster. Rancher UI thinks it's a custom cluster so they can't properly edit the cluster.
![image](https://user-images.githubusercontent.com/45179589/62743162-35f73e80-b9f6-11e9-9a33-01cbde17a8ed.png)
- Create another cluster (this time with a simple CT) as an admin. Make user "test1" a cluster owner.
- Log in as the "test1" user, try to edit the Cluster. We have access to the cluster template (even though we did not share the CT) per https://github.com/rancher/rancher/issues/21473 so we don't need to be shared the CT.
Same issue, "test1" user sees cluster as custom and when edits cluster gets "Custom" cluster UI for editing (asking to chose roles and update nodes with new commandline).

**Comment by westlywright** [comment]
I made a fix here that changed this but forgot that the previous view was deemed acceptable in 2.2. I will revert this change to get us back to the old behavior. 

In order to fix this whole custom thing we need a way for either the node-template to be shared or at the very least a way to figure out what provider the cluster is on without access to the nodes.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/12/19)

Still not quite right, the revert was an attempt to let us have the workaround in https://github.com/rancher/rancher/issues/12038 where we pick the rke cluster and can then edit properly. The main issue is we don't have access to the node template, which is a known issue. The past way we could from the UI pick what kind of rke cluster it is and then edit properly.

When I log in as the "test1" user and try to edit the cluster I just see a blank page now:
![image](https://user-images.githubusercontent.com/45179589/62905012-7cfa7200-bd1d-11e9-8c31-45a342f99518.png)

**Comment by vincent99** [comment]
@cjellick Can I get the nodeTemplate->driver copied onto the nodePool so this can be improved instead of just reimplementing the asking for what driver to use thing we had in 2.2?

**Comment by cbron** [comment]
Backend PR merged to master.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/3/19)

I tested both scenarios. I didn't identify any issues.

Scenario 1:
Create a cluster (without using a template).
- Make sure you add "test1" user as a cluster owner
- Log in as "test1" user and edit the cluster - we now are able to edit without any issues.
- Change something and ensure the change takes and the cluster updates accordingly.
- Smoke test to ensure the cluster is still in a good state and usable.

Scenario 2:
Same steps as above, except create the CT as admin and create the cluster with this CT as admin.
Make sure to add "test1" user as a cluster owner and test editing again.

In both scenarios this now works without any issues. The "test1" cluster owner user is able to edit a cluster whether or not it was created with a CT without any issues.
