### ISSUE TITLE
Remove Ability to Add Unknown Overrides from Cluster Templates

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#22084]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

We are going to remove the ability to add unknown overrides to the overrides section for 2.3 until a better solution can be found for the non-scalar type questions. 

This means the "add override" button will be removed from the UI.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/12/19)

This change was intended for v2.3 release; later, we'll see if we can improve this area after release.

This essentially just removes the "Add Override" button as Wes mentioned. I ensured this is gone when creating a cluster template or cloning a revision, etc. I ensured that overrides still work as expected. We can still create overrides - this just removes the button so we can't make our _own_ overrides such as those that are no in the UI form.

If this situation arises where a customer must define custom questions this can still be done via the API.

During my testing I was not able to identify any issues.

Screenshot shows an example, I created a k8s version override via the UI form, but the button to add custom overrides has been removed.
![image](https://user-images.githubusercontent.com/45179589/62905448-6a813800-bd1f-11e9-93ff-7020860aec75.png)
