### ISSUE TITLE
Rancher CLI - Error while logging into rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22095]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Log into rancher master using the latest cli - version - `rancher version v2.3.0-rc3`

**Result:**
Error:
`Do you want to continue connecting (yes/no)? yes
FATA[0003] json: cannot unmarshal number 9223372036854776000 into Go struct field Field.max of type int64 `

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master-head-linux-amd64 ; cli version - rancher version v2.3.0-rc3
- Installation option (single install/HA): single

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/22090

**Comment by dramich** [comment]
This was an issue with rancher server, fix has been merged and should be in next build

**Comment by sowmyav27** [comment]
Verified with latest master-head - commit id: `de1ba1b5`
Able to login using rancher CLI. No error seen while logging in.
