### ISSUE TITLE
UI - can't select existing secret in the catalog ui

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#22092]
**What kind of request is this (question/bug/enhancement/feature request):**
UI bug

**Steps to reproduce (least amount of steps as possible):**
1. add a custom catalog(https://github.com/guangbochen/charts - chartmuseum-2.3 Branch) with a `secret` type defined in the `questions.yaml`. e.g, https://github.com/guangbochen/charts/blob/chartmuseum-2.3/charts/chartmuseum/v2.3.1/questions.yml#L149
2. create a secret in the same namespace the catalog app will be deployed to
3. deploy the app but can't select the existing secret
![image](https://user-images.githubusercontent.com/4569037/62760619-03f9e100-bab7-11e9-9003-96e37367c065.png)

**Expected Result:**
user should be able to select an existing secret from the same namespace.

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.7

I carefully followed the steps to reproduce the issue (see issue description).

I reproduced the issue; my secret is not shown in the dropdown.
![image](https://user-images.githubusercontent.com/45179589/63196796-07e3b100-c02b-11e9-9af4-5deb2ebca36b.png)


**Validation:**
master-head (v2.3) (8/16/19)

I carefully followed the steps to reproduce again.

Now when I try to deploy the custom app (see issue description) into my NS where I added my secret, it's listed in the dropdown.
![image](https://user-images.githubusercontent.com/45179589/63195968-eeda0080-c028-11e9-97b8-20ce2c837bfb.png)
