### ISSUE TITLE
Stop spamming me

### ISSUE THREAD

**Issue by pavelmachek** [rancher/rancher#22094]
I'm not sure where 
Kateryna Ivashchenko <hi@portworx.com>
got my address, but she is pretty annoying at this point. Hopefuly you can contact her boss, and kindly ask her to stop spamming me... Because she is getting annoying.

**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by davidnuzik** [comment]
Hello, please contact Portworx this issue tracking system is for Rancher Labs
https://portworx.com/contact-us/
