### ISSUE TITLE
UI - Refactor EKS node ASG-size fields

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#22097]
**What kind of request is this:**
UI fix for Kontainer Engine Bug

**Steps to reproduce:**
Short version: when you create an EKS cluster with 1 min and max node you get an error.
See: https://github.com/rancher/rancher/issues/18243

**Fix:**
Replace "Min ASG Size" and "Max ASG Size" inputs with a single input that then sets min, max, and desired nodes so they are all the same. 
The [relevant doc](https://github.com/rancher/docs/blob/master/content/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/_index.md) will also need to be updated.

**Blocker**
The desired-nodes argument in KE is getting added as an argument by the following PR, so it blocks this issue: https://github.com/rancher/rancher/pull/22089

<img width="1282" alt="ASG-node-size" src="https://user-images.githubusercontent.com/571419/62797505-c1251280-ba90-11e9-8462-e8fb6e2132f5.png">

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/13/19)

This change in the UI allows us to now have a 1 or 2 node EKS cluster. Earlier we could not have one smaller than 3 nodes. Reference https://github.com/loganhz/ui/commit/be627792f931305b3cc8ffb574f1744574ff85df

Notice that there is a new UI field "Desired Nodes" and minimum and maximum have been removed. You can input the desired size and this will result in the correct count of worker nodes in the cluster.

Example screenshot showing default view of the "Node Options" section:
![image](https://user-images.githubusercontent.com/45179589/62957609-ffc90e80-bda9-11e9-953a-7abad0287615.png)


I tested with a value as small as one, then tried 2, then tried 3, and four. This resulted in four EKS clusters all with the correct count of worker nodes.

Note the UI statically sets minimumNodes and maximumNodes now per what we specify in the UI for "Desired Nodes" so if I set a value of 1 I get:.
```
maximumNodes: 1
minimumNodes: 1
```
and it sets desiredNodes per what we specify in the UI:
```
desiredNodes: 1
```

If I set to a different value like 2 then maximumNodes, minimumNodes, desiredNodes are all set to 2.

I smoke tested the clusters and did not identify any issues. The worker count always matches (in AWS web console, ec2 instances) what we specified in the rancher UI. The Rancher UI shows the correct node count per cluster as well. The API/HTTP look good. The UI only allows whole numbers in this field, as expected.

I only found one minor and unrelated issue while testing. Any EKS clusters created after the first have the wrong k8s version picked by default for some reason. This is tracked here: https://github.com/rancher/rancher/issues/22149
