### ISSUE TITLE
RKE Azure - allocated resources left in Azure after deleting the Azure cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#22100]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug in Rancher: master-head bc3700f8

_NOTE_: this issue is concerned with the deletion of all resources inside the resource group EXCEPT for the Disk resource that is provisioned when using managed disks. Deleting the disk will be track by this issue - https://github.com/rancher/rancher/issues/22345

**Steps to reproduce (least amount of steps as possible):**
Run the same steps in both v2.2.7 and Rancher: master-head bc3700f8 :
- add an Azure node template, in the template, set a new resource group such that Azure will create a dedicated  resource group for this cluster, set disk type to "Managed Disks".
- add a single-node RKE Azure cluster 
- wait for the cluster be active 
- check Azure console to see resources are allocated for the cluster under the resource group
- delete the cluster in Rancher
- check Azure console again 

**Result:**

In v2.2.7, all resources are deleted except the resource group itself 

<img width="1046" alt="Screen Shot 2019-08-09 at 11 48 44 AM" src="https://user-images.githubusercontent.com/6218999/62802507-e61f8280-ba9c-11e9-8663-d72e69918a1f.png">

**after the cluster is deleted:**

<img width="1096" alt="Screen Shot 2019-08-09 at 11 56 29 AM" src="https://user-images.githubusercontent.com/6218999/62802511-e881dc80-ba9c-11e9-9847-6f784138c838.png">

in master-head, only the VM is deleted 

<img width="1078" alt="Screen Shot 2019-08-09 at 11 48 52 AM" src="https://user-images.githubusercontent.com/6218999/62802609-20891f80-ba9d-11e9-95fc-5ae6ceefb42f.png">

**after the cluster is deleted:**

<img width="1060" alt="Screen Shot 2019-08-09 at 11 56 49 AM" src="https://user-images.githubusercontent.com/6218999/62802611-20891f80-ba9d-11e9-8ab1-6163328dfc6a.png">

**Comment by rmweir** [comment]
@cjellick this is likely related to my changes docker machine for managed disks, more specifically the azure library updates.

**Comment by davidnuzik** [comment]
I think this is pre-existing issue. It's also in v2.2.7 did we backport that too @rmweir ?

**Comment by rmweir** [comment]
No we did not, but I believe @jiaqiluo tried to reproduce with 2.2.7?

**Comment by davidnuzik** [comment]
My bad @jiaqiluo v2.2.7 screenshot still shows all the objects so I was confused.

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:master-head 19e84cee4

Steps:

- add an Azure node template, in the template, set a new resource group such that Azure will create a dedicated resource group for this cluster, set disk type to "Managed Disks".
- add a single-node RKE Azure cluster
- wait for the cluster be active
- check Azure console to see resources are allocated for the cluster under the resource group
- delete the cluster in Rancher
- check Azure console again

Results:

All resource except the managed disk is deleted. 
The disk issue is tracked here https://github.com/rancher/rancher/issues/22345

<img width="1363" alt="Screen Shot 2019-08-28 at 4 09 14 PM" src="https://user-images.githubusercontent.com/6218999/63898532-390a9c80-c9ae-11e9-9d9a-7f6571aba6d4.png">
