### ISSUE TITLE
Aliyun Node Driver shows all instances types instead of available instances types

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#22111]
rancher/rancher:v2.2.7

Steps:
1. Enable Aliyun EC2 driver
2. Create a template
3. Create a cluster based on the tempalte

Results:

Cannot create the cluster. It shows ecs.xxx.xxx not available. 

Expected:

We should only show the available instances types in UI. So users cannot select the unavailable instance.

**Comment by loganhz** [comment]
cc @pengjiang80

**Comment by rootwuj** [comment]
Tested with rancher/rancher:master-head `eed8d334`

Steps:
* Add node template.
* Verify instance type list for each region and available zone.
* Create node templates for different region.
* Create cluster using the node template.

Result:
* Each region only shows the instance types available for this region, and the instance type list data is correct.
* The node template was created successfully.
* The cluster was created successfully.
