### ISSUE TITLE
Select GKE version in UI is not working

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#22117]
Rancher version: master 8/11

Step to reproduce:
1. Select default gke version with `1.13.7-gke.8` to provision cluster.
2. Wait for cluster is ok and check for the cluster version.
3. Cluster version in cluster page is `1.12.8-gke.10`.
4. `view in api` for the newly created cluster and find `masterVersion`. And you will see empty string value for `masterVersion`.
5. Check the cluster version in gke, the version is also `1.12.8-gke.10`.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/13/19)

Now the correct cluster version is shown in the UI:
![image](https://user-images.githubusercontent.com/45179589/62973622-3ebb8c00-bdcb-11e9-8cf3-bcf8afa1899e.png)

When view in API the masterVersion is now correctly set `"masterVersion": "1.13.7-gke.8"`

I also tried with the older v1.13.6-gke.13 in the UI to ensure the UI now correctly sets the right string. In each test the correct k8s version is set in the UI and API.
