### ISSUE TITLE
calico-node fails with CrashLoopBackOff

### ISSUE THREAD

**Issue by michaellqu** [rancher/rancher#22116]
*Describe your issue here*
After use rke install k8s,calico pods keep restarting ... 

Current Behavio：
root@honops01:~# kubectl get pods -A
NAMESPACE       NAME                                        READY   STATUS             RESTARTS   AGE
cattle-system   cattle-cluster-agent-67c8664c7c-kqf6r       1/1     Running            2          28h
cattle-system   cattle-node-agent-fnrdn                     1/1     Running            4          28h
cattle-system   cattle-node-agent-gr7p8                     1/1     Running            2          28h
cattle-system   cattle-node-agent-pbpl8                     1/1     Running            3          28h
cattle-system   rancher-f5fc8d855-8fcqw                     1/1     Running            3          20h
cattle-system   rancher-f5fc8d855-llpdv                     1/1     Running            4          28h
cattle-system   rancher-f5fc8d855-r9zhz                     1/1     Running            186        28h
ingress-nginx   default-http-backend-5954bd5d8c-f6qv6       1/1     Running            1          28h
ingress-nginx   nginx-ingress-controller-78bkx              1/1     Running            2          28h
ingress-nginx   nginx-ingress-controller-dw5fk              1/1     Running            2          28h
ingress-nginx   nginx-ingress-controller-p7wj2              1/1     Running            3          28h
kube-system     canal-l6d2l                                 1/2     Running            22         68m
kube-system     canal-nzdks                                 1/2     CrashLoopBackOff   21         68m
kube-system     canal-t4f9h                                 1/2     CrashLoopBackOff   21         68m
kube-system     cert-manager-cert-manager-c667dcdbb-fhqsn   2/2     Running            4          28h
kube-system     coredns-autoscaler-5d5d49b8ff-6g29d         1/1     Running            1          28h
kube-system     coredns-bdffbc666-t9nf5                     1/1     Running            9          20h
kube-system     metrics-server-7f6bd4c888-nmdk2             1/1     Running            3          28h
kube-system     tiller-deploy-7f4f87c787-4zq27              1/1     Running            1          28h

root@honops01:~# kubectl describe pod -n kube-system canal-l6d2l
Name:           canal-l6d2l
Namespace:      kube-system
Priority:       0
Node:           192.168.20.2/192.168.20.2
Start Time:     Mon, 12 Aug 2019 04:08:09 +0000
Labels:         controller-revision-hash=87c4f6cd8
                k8s-app=canal
                pod-template-generation=4
Annotations:    cattle.io/timestamp: 2019-08-12T04:05:10Z
                scheduler.alpha.kubernetes.io/critical-pod:
Status:         Running
IP:             192.168.20.2
Controlled By:  DaemonSet/canal
Init Containers:
  install-cni:
    Container ID:  docker://874cbbd3a75505e657273f0cc9b65711588ac21832c1bf3aff5073ec95543fc6
    Image:         rancher/calico-cni:v3.4.0
    Image ID:      docker-pullable://rancher/calico-cni@sha256:b3f4045680586133039f1e77f3ebb4bb5e6c60fa85f184f395eee32303462715
    Port:          <none>
    Host Port:     <none>
    Command:
      /install-cni.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 12 Aug 2019 04:08:09 +0000
      Finished:     Mon, 12 Aug 2019 04:08:09 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      CNI_CONF_NAME:         10-canal.conflist
      SLEEP:                 false
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'canal-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from canal-token-48wlp (ro)
Containers:
  calico-node:
    Container ID:   docker://c65b422f21e09da6a0d65cbdb746e6f5db0c5b867819108c67cf36f8e435c4bd
    Image:          rancher/calico-node:v3.4.0
    Image ID:       docker-pullable://rancher/calico-node@sha256:2f46157483904649f334da83e6b5e522bf20cbd3ea6ec9f43456673933021d5a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 12 Aug 2019 05:16:52 +0000
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 12 Aug 2019 05:15:45 +0000
      Finished:     Mon, 12 Aug 2019 05:16:52 +0000
    Ready:          False
    Restart Count:  23
    Requests:
      cpu:      250m
    Liveness:   http-get http://:9099/liveness delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  http-get http://:9099/readiness delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      CALICO_DISABLE_FILE_LOGGING:        true
      CALICO_IPV4POOL_CIDR:               192.168.0.0/16
      CALICO_NETWORKING_BACKEND:          none
      CLUSTER_TYPE:                       k8s,canal
      DATASTORE_TYPE:                     kubernetes
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_HEALTHENABLED:                true
      FELIX_IPTABLESREFRESHINTERVAL:      60
      FELIX_IPV6SUPPORT:                  false
      FELIX_LOGFILEPATH:                  none
      FELIX_LOGSEVERITYSCREEN:            Warning
      FELIX_LOGSEVERITYSYS:
      IP:
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/run/calico from var-run-calico (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from canal-token-48wlp (ro)
  kube-flannel:
    Container ID:  docker://3fb54aa1ae5f7aa06591777aff3cbc16622b343fbba79dae601ffe17f62df94f
    Image:         rancher/coreos-flannel:v0.10.0
    Image ID:      docker-pullable://rancher/coreos-flannel@sha256:57f85f0bb7360f2dd378d74ffc01ac99a4c152ad463455ff429867c6879f4386
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/bin/flanneld
      --ip-masq
      --kube-subnet-mgr
    State:          Running
      Started:      Mon, 12 Aug 2019 04:08:13 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      POD_NAME:          canal-l6d2l (v1:metadata.name)
      POD_NAMESPACE:     kube-system (v1:metadata.namespace)
      FLANNELD_IFACE:    <set to the key 'canal_iface' of config map 'canal-config'>  Optional: false
      FLANNELD_IP_MASQ:  <set to the key 'masquerade' of config map 'canal-config'>   Optional: false
    Mounts:
      /etc/kube-flannel/ from flannel-cfg (rw)
      /run/xtables.lock from xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from canal-token-48wlp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  flannel-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      canal-config
    Optional:  false
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  canal-token-48wlp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  canal-token-48wlp
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoSchedule
                 :NoExecute
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                    From                   Message
  ----     ------     ----                   ----                   -------
  Warning  Unhealthy  14m (x118 over 69m)    kubelet, 192.168.20.2  Liveness probe failed: Get http://192.168.20.2:9099/liveness: dial tcp 192.168.20.2:9099: connect: connection refused
  Warning  BackOff    4m37s (x207 over 63m)  kubelet, 192.168.20.2  Back-off restarting failed container

corresponding logs:

root@honops01:~# kubectl logs canal-l6d2l -c calico-node -n kube-system
2019-08-12 05:16:52.723 [INFO][8] startup.go 244: Early log level set to info
2019-08-12 05:16:52.723 [INFO][8] startup.go 260: Using NODENAME environment for node name
2019-08-12 05:16:52.723 [INFO][8] startup.go 272: Determined node name: 192.168.20.2
2019-08-12 05:16:52.725 [INFO][8] startup.go 304: Checking datastore connection
2019-08-12 05:16:52.734 [INFO][8] startup.go 328: Datastore connection verified
2019-08-12 05:16:52.734 [INFO][8] startup.go 92: Datastore is ready
2019-08-12 05:16:52.761 [INFO][8] startup.go 518: FELIX_IPV6SUPPORT is false through environment variable
2019-08-12 05:16:52.761 [INFO][8] k8s.go 262: EnsuringInitialized - noop
2019-08-12 05:16:52.768 [INFO][8] startup.go 169: Using node name: 192.168.20.2
2019-08-12 05:16:52.796 [INFO][16] allocate_ipip_addr.go 43: Kubernetes datastore driver handles IPIP allocation - no op

root@honops01:~# kubectl logs canal-l6d2l -c kube-flannel -n kube-system
I0812 04:08:13.584909       1 main.go:475] Determining IP address of default interface
I0812 04:08:13.585306       1 main.go:488] Using interface with name ens160 and address 192.168.20.2
I0812 04:08:13.585329       1 main.go:505] Defaulting external address to interface address (192.168.20.2)
I0812 04:08:13.600878       1 kube.go:131] Waiting 10m0s for node controller to sync
I0812 04:08:13.600962       1 kube.go:294] Starting kube subnet manager
I0812 04:08:14.601154       1 kube.go:138] Node controller sync successful
I0812 04:08:14.601374       1 main.go:235] Created subnet manager: Kubernetes Subnet Manager - 192.168.20.2
I0812 04:08:14.601419       1 main.go:238] Installing signal handlers
I0812 04:08:14.601721       1 main.go:353] Found network config - Backend type: vxlan
I0812 04:08:14.601883       1 vxlan.go:120] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
I0812 04:08:14.602940       1 main.go:300] Wrote subnet file to /run/flannel/subnet.env
I0812 04:08:14.603032       1 main.go:304] Running backend.
I0812 04:08:14.603110       1 main.go:322] Waiting for all goroutines to exit
I0812 04:08:14.603295       1 vxlan_network.go:60] watching for new subnet leases

---
| Useful | Info |

| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`containers.index`|

**Comment by fjoesne** [comment]
Hi, I have this problem, I guess you figured it out as it was closed the same day you created it :) can you provide some more info on what may be wrong or and a workaround if possible? 
I'm thinking its either caused by the node where its LAN CIDR is within the cluster CIDR. or that its not taking the node public ip into consideration (node launched with the --address <public ip>), or a combination of these factors
