### ISSUE TITLE
Custom roles have all the permissions of the POD, but can't see the logs?

### ISSUE THREAD

**Issue by liulipengju** [rancher/rancher#22114]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**

1. Create a user who can only log in
![image](https://user-images.githubusercontent.com/10510950/62843027-5c182980-bce9-11e9-8e72-fc7c5e459e34.png)

2. Create a role with all permissions for the POD
![image](https://user-images.githubusercontent.com/10510950/62843047-7eaa4280-bce9-11e9-888d-b9a23fe4068f.png)

3. Use this account to log in to RANCHER
4. View the POD in a workload and click View Log

**Result:**
![image](https://user-images.githubusercontent.com/10510950/62843111-f8dac700-bce9-11e9-83e8-2e54f9325bd5.png)

not show

**Other details that may be helpful:**
use admin user can display
![image](https://user-images.githubusercontent.com/10510950/62843088-caf58280-bce9-11e9-966c-980bd21320cf.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher v2.2.7   

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
custom cluster
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by catherineluse** [comment]
I can see that you created a user called `exam`, and I can see that you created a role called `dev-item-new.` But I don't see that the role has been assigned to the user. I think you need to add that role to the user.

In the Rancher UI, from the Global view, click the **Users** tab. Go to the user that you want to see pods, then click the vertical ellipsis **(...)** and click **Edit.**

Then in the Global Permissions section, click the **Custom** option, click the box for `dev-item-new`, and click **Save.** This should give permission to the user. Please let me know if it doesn't work.

**Comment by liulipengju** [comment]
![image](https://user-images.githubusercontent.com/10510950/63076425-cfc76a00-bf67-11e9-9316-ce01fd9fc97f.png)

I am sure I have assigned a role.

**Comment by gitlawr** [comment]
This is how kubernetes RBAC works, [see](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources)
You need to give permissions for the `pods/log` resource.

**Comment by liulipengju** [comment]
ok,i set custom right, it's worked;
