### ISSUE TITLE
Workload with sidecar can't be edited

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#22120]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Workload
2. Add a sidecar to the Workload just created
3. Edit this Workload

**Result:**
Unable to edit this Workload, as shown below
![image](https://user-images.githubusercontent.com/19684717/62848455-5d0f8200-bd0e-11e9-8424-074cdbd7df12.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master-head
- Installation option (single install/HA):single

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/13/19)

NOTE: I tried to reproduce in v2.2.7 but could not; this looks like it was just an issue in earlier master-head so there is no way I can go back and try to repro.
v2.2.7 screenshot:
![image](https://user-images.githubusercontent.com/45179589/62956754-53d2f380-bda8-11e9-9da4-2b2e3a6fe7c9.png)


Validation:
Follow the steps and attempt to edit the workload with a sidecar. 
This works without any issues I can see the selection screen to chose what I want to upgrade.
![image](https://user-images.githubusercontent.com/45179589/62956808-6ea56800-bda8-11e9-8022-a8fa8895d917.png)
