### ISSUE TITLE
docker-machine replacement in work?

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#22125]
Very short question,

since docker-machine is EOL or at least in maintenance only mode, is there any plan to replace its functionality in rancher, or is it just intended to be used as is since it just works as of now? See for reference https://github.com/docker/machine/issues/4537

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/20554

**Comment by wzrdtales** [comment]
any news about that? the other linked issue was closed and the topic seems dead now?
