### ISSUE TITLE
[UI] Multi-Cluster App - Make error message more friendly when do not supply target projects

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22129]
Version: master-head (v2.3) (8/12/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
- Create a multi-cluster app. Supply a Name for the app. Do not supply any Target Projects from the dropdown. Click on the "Launch" button.

**Result:**
We get two errors:
![image](https://user-images.githubusercontent.com/45179589/62896812-a360e300-bd06-11e9-8bae-6d32fa99a2ac.png)

There is no "Values" field (I presume this is part of the target projects drop-down). This is a bit confusing to the user. We should make the error more friendly like "You must designate one or more target projects" or if we can remove the "Values is required" error as the "Targets is required" message is fairly clear -- this would work too.

Thank you Sowmya for identifying this issue.

**Comment by tfiduccia** [comment]
@davidnuzik & @sowmyav27 - I only see "Targets" is required and not the other "Values" error message when I leave the Target field blank.  I think whatever app you are using is requiring another field and for some reason it's not being displayed?  The Wording itself - we pull the value from the API and use control's 'Name' field and don't deal with pluralizations.  This is a standard for the Rancher application.  So this is a won't fix.

![image](https://user-images.githubusercontent.com/11514927/66510407-d535c200-ea89-11e9-9e19-cb34f6b0dbcd.png)
