### ISSUE TITLE
Step 37/45 : COPY entrypoint.sh rancher /usr/bin/ COPY failed: stat /var/lib/docker/tmp/docker-builder792574749/rancher: no such file or directory

### ISSUE THREAD

**Issue by xuqil** [rancher/rancher#22121]
Step 37/45 : COPY entrypoint.sh rancher /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder792574749/rancher: no such file or directory

**Comment by superseb** [comment]
Can you describe the exact steps you used to get this error so we can reproduce and decide what we can do?

**Comment by xuqil** [comment]
> Can you describe the exact steps you used to get this error so we can reproduce and decide what we can do?

I want to compile the Dockerfile under package, and that's what happened at “COPY entrypoint.sh rancher /usr/bin/”.

**Comment by superseb** [comment]
It copies the compiled binary, which is created in the `build-server` script/target. You can use `make` to run the full CI cycle or use scripts in the `scripts` directory if you want to run them manually.

Let me know if that doesn't work and what commands you used.

**Comment by xuqil** [comment]
> It copies the compiled binary, which is created in the `build-server` script/target. You can use `make` to run the full CI cycle or use scripts in the `scripts` directory if you want to run them manually.
> 
> Let me know if that doesn't work and what commands you used.

ok
