### ISSUE TITLE
TKE doesn't work

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#22137]
master-head(8/13)

Steps:

1. Create a TKE cluster with default value

Results:

Cluster failed to provision

More Info:

We can fix it by changing some default values. But the controller and scheduler status is red

**Comment by gitlawr** [comment]
Reproduction:
Cluster creation failed due to unavailable disk type/size. It succeeded after changing disk type/size.

There are multiple disk options provided by Tencent Cloud: `LOCAL_BASIC/LOCAL_SSD/CLOUD_BASIC/CLOUD_PREMIUM/CLOUD_SSD`.
Available options depend on the region & instance type. It may even be possible that none is available when the disk is sold out. The cloud provider UI suggests users choose another instance type in this case.
![image](https://user-images.githubusercontent.com/5697937/63324695-27484a00-c35b-11e9-99d0-493de6f3f6db.png)

Can UI get that info dynamically? This is the related API grabbed from the console
```
Request URL: https://iaas.cloud.tencent.com/cgi/capi?i=cbs/DescribeCbsQuota&uin=xxx
Request Method: POST
#Request body
{
  "serviceType": "cbs",
  "action": "DescribeCbsQuota",
  "regionId": 8,
  "data": {
    "inquiryType": "INQUIRY_CVM_CONFIG",
    "payMode": "postPay",
    "deviceClass": [
      "VSHIO"
    ],
    "zoneIds": [
      800001
    ],
    "cpu": 4,
    "mem": 16
  }
}
#Response
{
  "data": {
    "code": 0,
    "message": "",
    "codeDesc": "Success",
    "detail": [
      {
        "available": 0,
        "throttleTime": "1998-11-11 00:00:00",
        "instanceFamily": "I1",
        "storageType": "cloudPremium",
        "deviceClass": "VSHIO",
        "diskType": "data",
        "payMode": "postPay",
        "maxiDiskSize": 16000,
        "miniDiskSize": 10,
        "zoneId": 800001
      },
      {
        "available": 0,
        "throttleTime": "1998-11-11 00:00:00",
        "instanceFamily": "I1",
        "storageType": "cloudPremium",
        "deviceClass": "VSHIO",
        "diskType": "root",
        "payMode": "postPay",
        "maxiDiskSize": 500,
        "miniDiskSize": 50,
        "zoneId": 800001
      },
      {
        "available": 0,
        "throttleTime": "1998-11-11 00:00:00",
        "instanceFamily": "I1",
        "storageType": "cloudSSD",
        "deviceClass": "VSHIO",
        "diskType": "data",
        "payMode": "postPay",
        "maxiDiskSize": 16000,
        "miniDiskSize": 100,
        "zoneId": 800001
      },
      {
        "available": 0,
        "throttleTime": "1998-11-11 00:00:00",
        "instanceFamily": "I1",
        "storageType": "cloudSSD",
        "deviceClass": "VSHIO",
        "diskType": "root",
        "payMode": "postPay",
        "maxiDiskSize": 500,
        "miniDiskSize": 50,
        "zoneId": 800001
      }
    ],
    "cbsQuota": 500000,
    "curStorageNum": 0
  },
  "message": "",
  "code": 0
}
```

**Comment by gitlawr** [comment]
Incorrect controller/scheduler unhealthy status is an upstream bug tracked in https://github.com/rancher/rancher/issues/11496

**Comment by n313893254** [comment]
API doc: https://cloud.tencent.com/document/api/362/16318

**Comment by kingsd041** [comment]
Version: master master-head (8/28/19) 
Confirmed fix. Different disk types can be queried according to different zones.
