### ISSUE TITLE
where is webhook/receiver in 2.x

### ISSUE THREAD

**Issue by guozili** [rancher/rancher#22138]
1.x has this feature,but 2.x lost it.
i want to trigger a url to rancherto  redeploy.
such as "http://myrancherip:8888/" from aliyun trigger
work flow: aliyun gitlab ->aliyun docker register -> rancher webhook/receiver -> rancher workload

The CI/CD aims  i hope:
i push a tag:release-1.0.1(aliyun gitlab)
then rancher will deploy mydockerapp:1.0.1

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13475 or https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/pipelines/
