### ISSUE TITLE
When enable monitoring, grafana-cluster-monitoring fails to deploy - image not found

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22134]
Version: master-head (v2.3) (8/12/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to enable monitoring

**Result:**
grafana-cluster-monitoring fails to deploy properly:
![image](https://user-images.githubusercontent.com/45179589/62904440-3d328b00-bd1b-11e9-8abe-2875303039f4.png)

**Comment by loganhz** [comment]
image pushed, please try again

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/12/19)

I can confirm the image exists now. I was able to enable monitoring without any issues. the grafana-cluster-monitoring pod comes up without any issues.
![image](https://user-images.githubusercontent.com/45179589/62907193-df0ba500-bd26-11e9-89bb-c6570d3c0b5e.png)

![image](https://user-images.githubusercontent.com/45179589/62907264-3c9ff180-bd27-11e9-9bb1-88c06ff52640.png)
