### ISSUE TITLE
Build an agent to relay events from convoy to rancher 

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#2213]
Overview
---------------

Create an agent that will run on every host where convoy runs. This agent will know about volume create and delete events from convoy, and will relay these events back to rancher.

Things to do
------------------

 - [x] Create the agent that polls/subscribes to convoy events, and relay them to cattle.

    The agent will listen to the following events
         1. Create Volume
         2. Delete Volume

    The agent will use standard rancher API calls to communicate with rancher.

 - [x] Package, and Distribute this agent as a rancher catalog/rancher compose template

    The agent needs to be packaged as a docker container, and then a rancher-compose template is needed for this image.

**Comment by jas99** [comment]
@wlan0 @will-chan :+1: 
How much more time u gonna make us wait for convoy in Rancher UI :p 
Thx

**Comment by lavvy** [comment]
Lol. @wlan really itching to see convoy in ui

**Comment by pwFoo** [comment]
Will convoy-agent shipped with RancherOS?

**Comment by wlan0** [comment]
@pwFoo It will not be packaged with RancherOS out of the box
