### ISSUE TITLE
Catalogs system-libray not working

### ISSUE THREAD

**Issue by pcasis** [rancher/rancher#22148]
Hello,

I got a problem with the system-library catalog. It seems that it can't be accessed whereas others catalogs are well accessed.

As you can see here :
![image](https://user-images.githubusercontent.com/25147189/62953383-b69aae00-bded-11e9-94cb-697d276419b1.png)

Is there something wrong ?

**Comment by cjellick** [comment]
We haven't seen this problem for others. I checked, that branch (release/v2.2) does exist for that repo.
What version of rancher are you running?

**Comment by pcasis** [comment]
The version is 2.2.5

Le mar. 13 août 2019 à 18:16, Craig Jellick <notifications@github.com> a
écrit :

**Comment by catherineluse** [comment]
It looks like a git error that happens when you try to check out a branch but you don't have a local tracking branch. Maybe you can try to fetch the remote branch and try again.
