### ISSUE TITLE
Very high CPU, RAM, I/O usage with monitoring enabled

### ISSUE THREAD

**Issue by pcasis** [rancher/rancher#22141]
**What kind of request is this (question/bug/enhancement/feature request):**
It seems to be a bug

**Steps to reproduce (least amount of steps as possible):**
Enable monitoring while Catalogs can't be accessed.

**Result:**
Very high CPU, RAM and I/O usage

**Other details that may be helpful:**
CPU :
![image](https://user-images.githubusercontent.com/25147189/62926885-baaad980-bdb5-11e9-831a-45f7c8b47268.png)
RAM : 
![image](https://user-images.githubusercontent.com/25147189/62926945-d8783e80-bdb5-11e9-95be-c2416d245c30.png)
I/O : 
![image](https://user-images.githubusercontent.com/25147189/62926968-e332d380-bdb5-11e9-8d51-94e54cfe5572.png)

**Environment information**
- Rancher version : 2.2.5
- Installation option : Single Node

**Cluster information**
- Cluster type : Custom
- Machine type : VM

Kubectl
```
v1.13.7
```

- Docker version (use `docker version`):

```
Docker version 19.03.1, build 74b1e89
```

**Comment by cjellick** [comment]
How did you make your catalog unavailable?

**Comment by pcasis** [comment]
I haven't indicate my corp proxy during th single node install of Rancher.
So it can't access the catalogs.


Le mar. 13 août 2019 à 18:20, Craig Jellick <notifications@github.com> a
écrit :

**Comment by catherineluse** [comment]
I wonder if it's a connectivity issue. If something repeatedly tries to reach something else without success, it can increase the CPU and memory usage. Do your host firewall rules allow internal traffic between Prometheus and the node exporter? https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/prometheus/#node-exporter

**Comment by pcasis** [comment]
The thing is that Rancher can't even launch the application.
Here are the logs : 

[```
ERROR] AppController p-l7r9t/monitoring-operator [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.3" not found
2019/08/12 06:38:01 
[ERROR] AppController p-l7r9t/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.3" not found
```
