### ISSUE TITLE
Cluster Logging: Syslog: Allow format element

### ISSUE THREAD

**Issue by vish-in** [rancher/rancher#22142]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Choose logging to syslog
2. Click "Edit as File"
3. Add format element, e.g.:
```
<match *>
  @type remote_syslog
  host graylog-tcp.graylog.svc.cluster.local
  port 514
  severity notice
  protocol tcp
  packet_size 65535
  program rancher
  verify_mode 0
  <format>
    @type json
  </format>
</match>
```
4. Click "Save" or "Dry Run"

**Result:**
Got an "unexpected configure element: format" error

**Other details that may be helpful:**
remote_syslog plugin accepts a format section: https://github.com/dlackty/fluent-plugin-remote_syslog#format-section

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.7
- Installation option (single install/HA): HA

**Comment by janeczku** [comment]
The fact that custom `<format>`  blocks are not allowed in the raw logging configuration is intentional. But the error message should be improved (e.g. "<format> is not allowed").

**Comment by vish-in** [comment]
Why is it intentional? I'm still able to modify clusterloggings.management.cattle.io resource to get it work but I also have to make changes to rancher-logging-fluentd secret accordingly which is so frustrating.
