### ISSUE TITLE
Azure AD - server error while authenticating: graphrbac.UsersClient

### ISSUE THREAD

**Issue by caleno** [rancher/rancher#22143]
I'm trying to setup Azure AD authentication but I get this error which I think is produced on the Rancher side. In the Azure portal I can see I successfully singed in. 

`server error while authenticating: graphrbac.UsersClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="Invalid version: xxxx" InnerError={"date":"2019-08-13T09:49:47","request-id":"xxxxx"}`

I've tried both endpoint versions, the v2.0 give doesn't work (wont log me in) and isn't the version I supposed to use. Ref. https://github.com/rancher/rancher/issues/21522

Is there anyone experiencing the same problem? 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`global-admin.security.authentication.azuread`|

**Comment by dramich** [comment]
@caleno that error is coming from the azure API when we are attempting to get the user. It could be a permissions issue in azure so I would suggest following the docs and ensure your app has all the correct permissions. https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad/

**Comment by caleno** [comment]
@dramich Thanks for the tip, I'll check on Azure if I can find the problem.

**Comment by caleno** [comment]
I am pretty sure I have the API permissions needed, both legacy Windows Azure Active Directory and new Microsoft Graph. 

Problem persists.

**Comment by caleno** [comment]
Found the problem. In the new UI you get different top domain for graph url then legacy.

Use https://graph.windows.net/ and not https://graph.windows.com/

Problem solved.
