### ISSUE TITLE
Proxy URL is sent as null after focus breaking Test functionality for notifiers

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#22144]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a notifier, e.g. Slack
1. Fill in Name, URL and Default Channel
1. Focus/click on Proxy URL but don't fill anything yet
1. Hit Test 

**Result:**

Error is shown
```
Post https://hooks.slack.com: proxyconnect tcp: dial tcp :0: connect: connection refused
```

**Other details that may be helpful:**
When Proxy URL is not active/focussed, it wont be sent in the request (and it succeeds). If it was active/focussed, it is sent as `null`.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.7 and `master-head` (`085130a3`)
- Installation option (single install/HA): single

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/30/2019)

Now the key won't be send if the key is not populated in the proxy input or `null` .

Tested with:
 - Reported scenario (not focused proxy field).
 - Not focused field with proxy input filled.
 - Invalid Proxy.
 - Valid Proxy.
 - Previous scenarios in combination of the channel input empty /filled(`defaultRecipient`)

In this case the `defaultRecipient` key is sent as empty string (`""`) in the payload, I'm just curious of the decision behind removing the key entirely is `defaultRecipient` a mandatory key in the Slack json schema and the `proxyUrl` is optional?

@n313893254

**Comment by izaac** [comment]
Closing I will follow up the API change in a future conversation.
