### ISSUE TITLE
[UI] Apps - SVG icon not showing up

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22152]
Version: master-head (v2.3) (8/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Launch a MCapp or an app at project level.

**Result:**
The SVG icon for the app is not shown (assuming the app includes an icon). We show the default SVG icon.

No http issues from browser side of things. No JS errors.
I did see some warnings though -- perhaps this is related to CORS and similar related fixes recently.

![Screen Shot 2019-08-13 at 10 59 14 AM](https://user-images.githubusercontent.com/45179589/62965294-8fc28480-bdb9-11e9-8781-f2b7bb8c4a84.png)

**Comment by davidnuzik** [comment]
We should fix this in v2.3; it could have other implications too possibly.

**Comment by izaac** [comment]
@loganhz @davidnuzik  I still notice this in latest rancher master-head (v2.3) (08/20/2019)

See the browser console.

<img width="2076" alt="Screen Shot 2019-08-20 at 3 01 06 PM" src="https://user-images.githubusercontent.com/27659/63388213-91152380-c35c-11e9-9ec4-0ff179053fe8.png">

**Comment by loganhz** [comment]
Hi @izaac I have fixed the issue that users cannot see the app icon in the apps page. It always show the default icon.

In your screenshot, I can see the icon for docker-registry. 

Please create another issue for the warning in console log. It should be fixed in catalog app page.

**Comment by izaac** [comment]
@loganhz sounds good, closing this issue and opened https://github.com/rancher/rancher/issues/22315 for the CORB warnings.
