### ISSUE TITLE
[UI] Helper pop-up text carrot is offset

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22154]
Version: master-head (v2.3) (8/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create EKS cluster, when you get to the last step, hover over the SSH Key help icon.

**Result:**
The carrot is offset. For some reason it does not point to the icon.
![image](https://user-images.githubusercontent.com/45179589/62978640-990e1a00-bdd6-11e9-986a-b3164c393b5c.png)

**Comment by izaac** [comment]
Version: master-head (v2.3) (8/16/19)
Test executed in both Firefox and Chrome, the tooltip is always showing on top of the question mark as expected. Even resizing the browser.

<img width="450" alt="Screen Shot 2019-08-16 at 11 58 55 AM" src="https://user-images.githubusercontent.com/27659/63191388-3d819d80-c01d-11e9-9deb-9f9b02663c1c.png">
