### ISSUE TITLE
[UI] Istio - Description text for each pane should more clearly define what each area is for

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22156]
Version: master-head (v2.3) (8/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Go to the Istio config page.

**Result:**
The strings for each pane in the config are extremely generic. They don't really explain what each section is for. We expected to have some more information like what each of these do.
![image](https://user-images.githubusercontent.com/45179589/62979910-eb9d0580-bdd9-11e9-8444-1de7bbe110cf.png)

_also notice_ that there are no translation keys for the pane titles:
![image](https://user-images.githubusercontent.com/45179589/62981354-d9bd6180-bddd-11e9-862b-fc2163f2929e.png)

_also notice_ that the key appears to be static for four of them (clusterIstioPage.workload.detail)

**Comment by izaac** [comment]
Version: master-head (v2.3) (8/14/19)

I validated this in the latest master-head in both latest Chrome and Firefox. Descriptions look more aligned with the upstream lstio documentation.

<img width="470" alt="Screen Shot 2019-08-14 at 10 50 03 AM" src="https://user-images.githubusercontent.com/27659/63043569-52c1c500-be81-11e9-9bc2-1ad92e11f228.png">

The translation keys verification will be part of other issue scope. https://github.com/rancher/rancher/issues/22175

**Comment by davidnuzik** [comment]
@tfiduccia should this say "Configure tracking requests." Or "tracing" ?
![image](https://user-images.githubusercontent.com/45179589/63044227-9d900c80-be82-11e9-9024-c864e82366de.png)

**Comment by tfiduccia** [comment]
@davidnuzik - I used tracking on purpose.  But here is the "Istio" definition I got from their site, if you have suggestion on how to word better, I can fix.  
"Distributed tracing enables users to track a request through mesh that is distributed across multiple services. This allows a deeper understanding about request latency, serialization and parallelism via visualization."

**Comment by davidnuzik** [comment]
I think this is fine @tfiduccia I just wanted to double-check to make sure this was correct. I think the description is good. Thanks!
