### ISSUE TITLE
[UI] Cluster Templates index page still shows image

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22163]
Version: master-head (v2.3) (8/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
There was a recent change to remove most images in the Rancher UI. If you view the Cluster Templates page (without having any cluster templates) there is still an image shown in the UI here.

**Result:**
![image](https://user-images.githubusercontent.com/45179589/62984786-56a20880-bde9-11e9-82e5-bbbe93dac960.png)
The image should be removed and we should just have a text string that states something like "There are no Cluster Templates defined." or similar.

**Comment by izaac** [comment]
Original issue for reference: https://github.com/rancher/ui/pull/3204

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/21/2019)

This is fixed in the latest build.

<img width="1356" alt="Screen Shot 2019-08-21 at 2 00 35 PM" src="https://user-images.githubusercontent.com/27659/63468217-288d7b80-c41c-11e9-819f-aeb4193a4a60.png">
