### ISSUE TITLE
[UI] Cluster Templates - Remove filled in "First revision" text for Template Revision Name field

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22162]
Version: master-head (v2.3) (8/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a CT

**Result:**
Notice for some reason there is text filled in in the Template Revision Name field.
![image](https://user-images.githubusercontent.com/45179589/62984223-35d8b380-bde7-11e9-8c8d-f43ebfbbbd80.png)

This used to not be there (I'm not aware of an issue to add this).

This could be helper text (that grayed out helper text that isn't actual text content) but I don't even like the idea of "First revision" revisions should be descriptive and very briefly explain what the revision is in my opinion. Also spaces are not allowed.

**Comment by davidnuzik** [comment]
If revision names aren't really going to be sort-of for describing the revision (e.g. windowssupport, k8s155, etc) then we should expose the description field in the UI so people can describe their CT and the /g/cluster-teamplates/index page should shown description as a column or something.

**Comment by vincent99** [comment]
I added a default for the revision name when creating a new template because it's just an obstacle to have to come up with two different names on template create.  You don't really care about revisions until there's a second one.

**Comment by vincent99** [comment]
Tani, Darren and I agreed on leaving it but changing to `v1`.

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/21/2019)

The latest version is filling the Revision field with  "**v1**" by default now as agreed.
