### ISSUE TITLE
Update cli to a non-rc version in pipeline-tools

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#22164]
Update cli to a non-rc version in pipeline-tools when there is a non-rc cli ready

https://github.com/rancher/pipeline-tools/commit/cc560f65c391fe5ec0645b75b37933eae4084d0f

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.0-rc11

* Reproduced in master-head (before RC11), saw Rancher CLI version as `2.3.0-rc7`
* Create a cluster
* Enable a pipeline
* Execute pipeline
* While pipeline is executing, exec shell into the executor/agent pod (with pipeline tools image)
* From shell, exec `rancher`
* Outputs:

```
bash-4.4# rancher
Rancher CLI, managing containers one UTF-8 character at a time

Usage: rancher [OPTIONS] COMMAND [arg...]

Version: v2.3.0

Options:
  --debug        Debug logging
  --help, -h     show help
  --version, -v  print the version
```
