### ISSUE TITLE
rancher2.2.7 .rancher-pipeline.yml runScriptConfig how to set volumes?

### ISSUE THREAD

**Issue by wichell** [rancher/rancher#22169]
stages:
- name: package
  steps:
  - runScriptConfig:
      image: xxxx/maven:3-jdk-8
      shellScript: mvn clean package
      **volumes:????????????**
- name: build_docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demo/testdragonshard:1.0.0
      pushRemote: true
      registry: 10.20.10.80:8888
timeout: 60
notification: {}

config like this ,so how can i write volumes??

**Comment by xingyuli** [comment]
Needs this feature as well...
Downloading maven dependencies in each pipeline run is very time consuming and slowdown the CICD.

**Comment by wichell** [comment]
so i want to set volumes ,that can save the .m2 cache to the physical machine.
Looking forward to future versions

**Comment by xingyuli** [comment]
Are there any other issue tracking this problem(feature request)? Or any roadmap mentioned this? If not, why this has been closed?

**Comment by ryangsun** [comment]
hi,how to fix this?
