### ISSUE TITLE
[UI] Ensure we have translation keys in all appropriate areas - QA Review

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22175]
Set up master-head rancher. Review the UI and utilize the "Shift + L" shortcut to show the translation keys. You should see these nearly everywhere. Exceptions are any warnings/errors form the API, any Javascript warning/info ribbons such as those under Istio config and Monitoring config, and a couple other areas.

Review any areas you are not sure on with David.

**Comment by izaac** [comment]
I went through all the UI elements using Global View and Cluster View using Chrome and Firefox and I've opened these issues related to the State web component within Tables which is globally used without translation keys:

https://github.com/rancher/rancher/issues/22199
https://github.com/rancher/rancher/issues/22205
https://github.com/rancher/rancher/issues/22206
https://github.com/rancher/rancher/issues/22208
https://github.com/rancher/rancher/issues/22209

I'll close this, if we notice any more of these we will open additional issues for tracking, as this task was originally created for validation after https://github.com/rancher/rancher/issues/22156
