### ISSUE TITLE
feature request: support self-signed SSL certs in rancher-compose

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2217]
relates to #1853 but for rancher-compose.
As it is now, all I get is:

```
ERRO[0000] Failed to open project default: Get https://rancher..../: x509: certificate signed by unknown authority 
```

**Comment by deniseschannon** [comment]
@kaos I'll need to talk to @ibuildthecloud if this would even be possible/make sense.

**Comment by kaos** [comment]
It shouldn't have to be more than being able to point at a ca bundle to use, or something like that..

Skickat från min iPhone

**Comment by vincent99** [comment]
The CLI for 2.0 has an option for this, and interactive prompt to take the cert from the server if desired.

**Comment by aa-aahmed** [comment]
is this issue been resolved? I am getting same error 
root@K8S-MASTER 0.3.1]# rancher-compose -p es up
ERRO[0000] Failed to open project es: Get https://xxxxxxxxxxx/v3: x509: certificate signed by unknown authority 
FATA[0000] Failed to read project: Get https://xxxxxxxxx/v3: x509: certificate signed by unknown authority 
[root@K8S-MASTER 0.3.1]#

**Comment by Firzum** [comment]
Hello, I got the same one (with the same compose template, from elastic). export DOCKER_TLS_VERIFY=0 has not effect.

**Comment by aa-aahmed** [comment]
you need to start rancher with custom certificates, i was able to resolve that issue. just run this SH Script 

#!/bin/bash
if [[ $DEBUG == "true" ]]; then
  set -x
fi
export FQDN="rancher.net"
export CA_SUBJECT="Rancher CPI CA"
export CA_EXPIRE="1825" # CA expires in 5 years
export SSL_EXPIRE="365" # Certificate expires in 1 year
export SSL_SUBJECT="${FQDN}"
export SSL_DNS="${FQDN}" # Additional SANs (comma separated) can be added
export SILENT="true"
docker run -v /opt/certs:/certs \
  -e CA_SUBJECT \
  -e CA_EXPIRE \
  -e SSL_EXPIRE \
  -e SSL_SUBJECT \
  -e SSL_DNS \
  -e SSL_IP \
  -e SILENT \
  superseb/omgwtfssl

docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v /opt/rancher:/var/lib/rancher \
  -v /opt/certs/cert.pem:/etc/rancher/ssl/cert.pem \
  -v /opt/certs/key.pem:/etc/rancher/ssl/key.pem \
  -v /opt/certs/ca.pem:/etc/rancher/ssl/cacerts.pem \
# If you have proxy then enable these options.
#  -e HTTP_PROXY="http://10.xx.xx.xxx:8080" \
#  -e HTTPS_PROXY="http://10.xx.xx.xxx:8080" \
# -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.13.0.0/24,10.12.0.0/24,rancher.net" \
  rancher/rancher:latest



hope this helps let me know if you still have issues :)
