### ISSUE TITLE
[UI] Remove images from pages in Rancher UI - QA Review

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22174]
Please bring up v2.2.7 rancher and compare to latest master-head rancher UI.

Notice that we removed images from most pages where you have zero objects for that page. Text replaced the images.

Please review and ensure the text makes sense. It should have proper spelling and grammar.
For example there is one area, where when you are bringing up a cluster (still pending) and you view the Cluster page it mentions something similar to "Not enough data for graphs." this could probably be explained in a better way. In this case you would open an issue to change this text.

There is one known issue: https://github.com/rancher/rancher/issues/22163

**Comment by izaac** [comment]
Original issue for reference: https://github.com/rancher/ui/pull/3204

**Comment by izaac** [comment]
Opened issue during execution:
https://github.com/rancher/rancher/issues/22181

**Comment by izaac** [comment]
Version: master-head (v2.3) (8/14/19)

Validated version 2.3 performing some comparison testing against 2.2.7 which doesn't including the related change. Comparing all the screens and links that could be navigated with a browser. Chrome and Firefox.

Issue with cluster templates https://github.com/rancher/rancher/issues/22163 is still valid.

Samples of common areas tested:

Login screen v2.3.x

<img width="1853" alt="Screen Shot 2019-08-14 at 11 57 02 AM" src="https://user-images.githubusercontent.com/27659/63060262-9a0e7c80-bea6-11e9-9ee4-89c691c46231.png">

Login screen v2.2.7

<img width="1852" alt="Screen Shot 2019-08-14 at 11 56 53 AM" src="https://user-images.githubusercontent.com/27659/63060239-86631600-bea6-11e9-803a-1d8c7971bf28.png">

Clusters screen v2.3

<img width="1359" alt="Screen Shot 2019-08-14 at 12 07 01 PM" src="https://user-images.githubusercontent.com/27659/63060316-c2967680-bea6-11e9-8c0b-71365ccfbf02.png">

Clusters screen v2.2.7

<img width="1357" alt="Screen Shot 2019-08-14 at 12 06 51 PM" src="https://user-images.githubusercontent.com/27659/63060343-cd510b80-bea6-11e9-8768-9ccf9d204f59.png">

Clusters Provisioning screen v2.3

<img width="1267" alt="Screen Shot 2019-08-14 at 12 12 06 PM" src="https://user-images.githubusercontent.com/27659/63060475-3df82800-bea7-11e9-802e-c0b701d10713.png">

Clusters Provisioning screen v2.2.7

<img width="1272" alt="Screen Shot 2019-08-14 at 12 13 33 PM" src="https://user-images.githubusercontent.com/27659/63060499-4d777100-bea7-11e9-8b7a-d03ef8ceaa0a.png">
