### ISSUE TITLE
[UI] Minor en-us translation issue in cloud provider warning

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22178]
Version: master-head (v2.3) (8/14/19)
Version: v2.2.7 (pre-existing issue)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, minor

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster, pick on a cloud option like Azure

**Result:**
This helper text has a space in an inappropriate area.
![image](https://user-images.githubusercontent.com/45179589/63043792-c368e180-be81-11e9-9e48-b3b8225189cf.png)

This is key %cloudProvider.warning%

**Comment by tfiduccia** [comment]
I checked the translation key and there is no space there.  So must be something with the html for the box.

**Comment by izaac** [comment]
Version: master-head (v2.3) (8/15/19)

Validated with clusters listed in the section: **With RKE and new nodes in an infrastructure provider**. With Firefox and Chrome.

<img width="1072" alt="Screen Shot 2019-08-15 at 12 08 34 PM" src="https://user-images.githubusercontent.com/27659/63119631-77876c80-bf55-11e9-8ea9-5a11d3ea656c.png">

The helper banner is now displaying as expected. The cloud provider radio buttons show different options depending on the cloud provider selected but the helper is the same and also expected.

<img width="1233" alt="Screen Shot 2019-08-15 at 12 07 16 PM" src="https://user-images.githubusercontent.com/27659/63119740-b3bacd00-bf55-11e9-9fcf-cbcd26afd684.png">

The helper is also good while responding to browser resizing.

<img width="633" alt="Screen Shot 2019-08-15 at 12 13 14 PM" src="https://user-images.githubusercontent.com/27659/63120014-3c396d80-bf56-11e9-9df6-51398ba8f3fa.png">
