### ISSUE TITLE
rancher/rancher:latest seems to be pointing to v2.2.4

### ISSUE THREAD

**Issue by th0th** [rancher/rancher#22188]
I have tried to upgrade to `2.2.7` from `2.2.4`. But the `rancher/rancher:latest` tag on dockerhub seems to be pointing to `2.2.4`.

I have been using the `latest` tag, I tried to find anything related but couldn't, did image tagging change? Do I need to use `rancher/rancher:v2.2.7` now?

**What kind of request is this (question/bug/enhancement/feature request):** Question

**Steps to reproduce (least amount of steps as possible):**

* Stop the existing rancher container
* Run `docker pull rancher/rancher:latest`
* Start a new container using the existing rancher path as volume

**Result:**

![chrome_QYmmP9B2pb](https://user-images.githubusercontent.com/698079/63064174-b6430580-bf08-11e9-83a1-5574e2710dfe.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:latest - v2.2.4`
- Installation option (single install/HA): single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted on Hetzner
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): N/A

```

```

- Docker version (use `docker version`):

```
Docker version 19.03.1, build 74b1e89
```

**Comment by deniseschannon** [comment]
I've updated `rancher/rancher:latest` to 2.2.7.
