### ISSUE TITLE
Make empty table text more consistent

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#22187]
**What kind of request is this (question/bug/enhancement/feature request):**  UX/UI design issue.

**Steps to reproduce (least amount of steps as possible):**
1.  Go to each page in Rancher and ensure that the text is consistent for all empty tables.  This should check on global, cluster and project level.

**Result:** Currently each area has different type of text.  For the Clusters list, it says "There are no clusters yet."  For Node Templates it says "There are no node templates defined".  I would all pages to have the same type of verbiage.

Change all pages so they basically say `There are no <items> defined.`

**Comment by izaac** [comment]
@tfiduccia 
Go to one project in a cluster and in its resources the Load Balancing and Volumes tables are missing the default text when they are empty.

<img width="1387" alt="Screen Shot 2019-08-21 at 2 03 49 PM" src="https://user-images.githubusercontent.com/27659/63468478-d9941600-c41c-11e9-93e5-48bbc68a5938.png">

<img width="1391" alt="Screen Shot 2019-08-21 at 2 03 55 PM" src="https://user-images.githubusercontent.com/27659/63468487-ddc03380-c41c-11e9-900b-38b36c8b8f5c.png">

**Comment by tfiduccia** [comment]
@izaac - I have an issue for that already. https://github.com/rancher/rancher/issues/22215

**Comment by izaac** [comment]
@tfiduccia ok additional to that I found this other small style issue in a couple of tables: https://github.com/rancher/rancher/issues/22337

Besides those I didn't find any other area missing the text or being inconsistent with the latest changes.

I'll close this issue and will open new ones if anything comes up later on.
