### ISSUE TITLE
[UI] - Cluster Dashboard text while provisioning a new cluster should be improved.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22181]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**

1. Add a new cluster
2. While the cluster is still provisioning click in it to see the dashboard

**Result:**
As the cluster is still in provisioning status the Gauges in 2.3 won't be shown and now a text message will be displayed during this state. This could be improved by clarifying the reason of why there isn't enough data, or suggest a better wording for this.

<img width="1267" alt="provisioning" src="https://user-images.githubusercontent.com/27659/63054561-f10d5500-be98-11e9-9f45-4a404721e6e7.png">

**Other details that may be helpful:**

In Rancher 2.2.7 the cluster image is displayed instead of this text.

<img width="1272" alt="Screen Shot 2019-08-14 at 12 13 33 PM" src="https://user-images.githubusercontent.com/27659/63054615-14380480-be99-11e9-8a0c-868547019159.png">

**Environment information**
- Rancher master-head (08/14/2019)
- Single node install.

**Comment by izaac** [comment]
This comes from this original task https://github.com/rancher/rancher/issues/22174

**Comment by loganhz** [comment]
It looks like this is by design.

https://github.com/rancher/ui/commit/873e9abf79ef7020d2742f1ee13abe8a80aeaedf#diff-e28d0ea29e1bbef8316e9afbe964107e

cc @tfiduccia @vincent99 @lvuch

**Comment by tfiduccia** [comment]
@loganhz - yea, don't worry about it.  I'll take a look and if we decide on something better, I can change.

**Comment by tfiduccia** [comment]
@izaac - How about we change the text to say something like - "Graph information from Cluster currently not available".  I can't really say "why" cause I don't know.  This is that weird state thing again.  Unless there is active data, we don't show the graph.

**Comment by izaac** [comment]
@tfiduccia it sounds better, what do you think @davidnuzik ?

**Comment by davidnuzik** [comment]
I agree that should work @tfiduccia @izaac

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/21/2019)

This is showing the agreed text content from here: https://github.com/rancher/rancher/issues/22181#issuecomment-521839156

Validated with cluster options while provisioning to get the message before the cluster is Active.

<img width="1367" alt="Screen Shot 2019-08-21 at 12 47 18 PM" src="https://user-images.githubusercontent.com/27659/63463504-245c6080-c412-11e9-9e9d-6824af0843ac.png">
