### ISSUE TITLE
Stats are missing in LB page

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2218]
```
Component 	Version
Rancher 	v0.40.0-rc2
Cattle 	v0.96.0
User Interface 	v0.54.0
Rancher Compose 	beta/latest
```

<img width="1371" alt="screen shot 2015-10-02 at 9 45 46 am" src="https://cloud.githubusercontent.com/assets/7720752/10252142/62b95fe0-68ea-11e5-9fab-1c5a63dabd0b.png">

**Comment by deniseschannon** [comment]
This was causing #2211.
