### ISSUE TITLE
Run time in admin -> Processes page is shown in ms

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2219]
```
Component 	Version
Rancher 	v0.40.0-rc2
Cattle 	v0.96.0
User Interface 	v0.54.0
Rancher Compose 	beta/latest
```
It will be easy to read if Run time is in seconds

<img width="1311" alt="screen shot 2015-10-01 at 2 32 36 pm" src="https://cloud.githubusercontent.com/assets/7720752/10252196/c3d51fee-68ea-11e5-97d9-cf698ef3423b.png">

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/13615337/0a5cd9ca-e532-11e5-8a78-41a3bd64d42b.png)
