### ISSUE TITLE
[UI] Cluster Templates - Rename the clustertemplate access Type "Read-only" to "User"

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#22200]
ClusterTemplates can be shared with specific users and/or groups with the accessType "Read-Only" - which enables those users to list and use these templates for cluster creation.

We need to change the "Read-only" type to "User" in the UI to indicate that the user can read as well as use this template.

Please note that we only need this to be renamed on the UX - API will still expect the accessType value as "read-only", so no changes to the call made to the API.

Screenshot of the accessType to be renamed:
<img width="1380" alt="Screen Shot 2019-08-15 at 11 48 11 AM" src="https://user-images.githubusercontent.com/1470602/63118874-9edd3a00-bf53-11e9-90e3-4340aeacf32d.png">

**Comment by loganhz** [comment]
Please hold off the test due to https://github.com/rancher/rancher/issues/22201#issuecomment-522183775

**Comment by loganhz** [comment]
Fixed. We can test it in master-head now

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/19/19)

I can confirm that we have renamed the "read-only" access type on the Cluster Template page to "User". This change essentially adds a localized label. In the en-us.yaml translations file we simply change the name to "User"
`'read-only': 'User'`

Screenshot:
![image](https://user-images.githubusercontent.com/45179589/63282004-bfaed380-c262-11e9-85ba-8b3e0cd59193.png)
