### ISSUE TITLE
Add warning against naming rancher-agent in `docker run` command

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2220]
Per http://forums.rancher.com/t/warn-against-naming-rancher-agent/605/1

Add a warning in UI that people should not try to add the `--name=rancher-agent` in the "custom" command of `docker run rancher/agent` as it will cause the rancher/agent container to fail.

**Comment by vincent99** [comment]
Is this really common enough that we want to do this?  There are an infinite number of things they can add to the command that will break it.

**Comment by vincent99** [comment]
So I claim "no", or if we want it the agent container itself should detect and warn when the first (normally unnamed) container is run that this situation is actually occurring.
