### ISSUE TITLE
[UI] When cluster is Provisioning, and we click on Istio config page, should route to /c/CLUSTERID/monitoring

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22213]
Version: master-head (v2.3) (8/15/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a custom cluster but don't actually set it up. It will essentially always be in "Provisioning" state.
- Click on it to go to the cluster level. Try to go to the Istio Config page.

**Result:**
We tweaked this a while back to not allow going to Istio config page. But what we are doing right now is kind-of a hack in a way. We don't let the user click or hover over this item. We should be doing this properly.

For example, here is an example of the proper way we handle this.
- On your custom cluster (that is continuously in Provisioning state) go to the Node page
- Try to click on Storage > Persistent Volumes on the nav bar.
NOTICE we are routed back to /c/CLUSTERID/monitoring

This is true for most other areas too -- try going to the Nodes page and then clicking on "Projects/Namespaces" and notice you are properly routed to /c/CLUSTERID/monitoring

**Other details that may be helpful:**
I don't think this is a huge deal / blocker for v2.3 release but we should ideally correct this so it's in alignment with how we handle other similar areas.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/21/19)

Istio doesn't appear at all in the Tools menu now until the cluster is ready. Is this expected? It looks like we're doing something special again.

cc: @tfiduccia

**Comment by tfiduccia** [comment]
@n313893254 - Can we have the Istio menu act like the other Cluster menu items.  It should be there.  But if you try to click on it before Cluster is fully provisioned it will redirect you back to the dashboard.  This way customers can see feature sets before cluster is fully provisioned but we stop them from setting up until it's ready.  Thanks.

**Comment by loganhz** [comment]
Hi @tfiduccia 

@vincent99 suggested to hide it. 

https://github.com/rancher/ui/pull/3270#discussion_r315443120

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/28/2019)

I created three clusters with different status and tried to reach the Istio route through the UI:

- A cluster in *Active* state.
  - ===> UI redirects to /c/CLUSTERID/istio/cluster-setting :white_check_mark:
- A cluster was kept in *Updating* state.
  - ===> UI redirects to /c/CLUSTERID/istio/cluster-setting :white_check_mark:
- Final cluster in *Provisioning* state (original issue).
  - ===> UI redirects to /c/CLUSTERID/monitoring :white_check_mark:

Closing.
