### ISSUE TITLE
[UI] EKS - Seeing "(not allowed by template)" in EKS k8s version dropdown

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22216]
Version: master-head (v2.3) (8/15/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- On any rancher install (fresh or not) try to create an EKS cluster. Click on the K8s Version dropdown.

**Result:**
For some reason the unsupported k8s versions say "(not allowed by template)" on them. EKS /g/clusters/add/launch/amazoneks page should have nothing to do with templates.
Perhaps what is mentioned here is helpful: https://github.com/rancher/rancher/issues/22149#issuecomment-521476099

**Comment by izaac** [comment]
This is how I see the k8s dropdown now in Amazon EKS comparing master-head (v2.3) (08/22/2019) and v2.2.8.

v2.3 (08/22/2019):

<img width="1094" alt="Screen Shot 2019-08-22 at 9 05 06 AM" src="https://user-images.githubusercontent.com/27659/63531293-0e57aa00-c4bd-11e9-9220-a9db1f908594.png">

v2.2.8:

<img width="865" alt="Screen Shot 2019-08-22 at 9 11 46 AM" src="https://user-images.githubusercontent.com/27659/63531319-1d3e5c80-c4bd-11e9-86af-8681effb38ff.png">


Not Allowed is not showing anymore, but I would need to double check the supported versions for 2.3 before closing this issue. @davidnuzik

**Comment by izaac** [comment]
I'm closing as the original reported issue is resolved now (see previous comment). 

I'll follow up in a separate issue for the supported/unsupported versions if needed.
