### ISSUE TITLE
[UI] emptying a table in the UI get their headers uncentered

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22217]
Version: master-head (v2.3) (8/15/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Locate a table that has at least one row in the Rancher UI
- Or populate one like the clusters with one cluster.
- Empty the table by removing all the rows.

**Result:**

 - the table headers get uncentered to the left.

<img width="1628" alt="Screen Shot 2019-08-15 at 4 28 01 PM" src="https://user-images.githubusercontent.com/27659/63133511-6f8df380-bf7a-11e9-9675-421faf8e53b5.png">

**Environment information**
- rancher v2.3 head-master
- single install

**Comment by tfiduccia** [comment]
Not going to fix in the 2.4 timeframe.  Shouldn't be an issue for redesign.
