### ISSUE TITLE
Remove deprecated Fluentd config

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#22219]
Fluentd config `merge_json_log` and `preserve_json_log` are for parsing the source message info JSON, removed since 2.1.x. We are going to upgrade Fluentd version, need to remove these two deprecated configure. After this [PR](https://github.com/rancher/system-charts/pull/80), if we use the latest dev system-chart with these deprecated configure will have warning log in Fluentd pod.
```
2019-08-16 01:03:08 +0000 [warn]: parameter 'merge_json_log' in <filter cluster.**>
@type kubernetes_metadata
merge_json_log true
preserve_json_log true
</filter> is not used.
2019-08-16 01:03:08 +0000 [warn]: parameter 'preserve_json_log' in <filter cluster.**>
```

In the previous version, it will parse the source message into JSON and attaching it to the payload as below. In the latest version of https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter, this function is removed, if still need it, could use JSON parser to implement it.
Original: 
```
{"source":"stdout","log":"{\"level\":\"warn\", \"msg\":\"this is a log message\"}","container_id":"3fd8678d","container_name":"/angry_kalam"}
```
After parsed:
```
{"source":"stdout","log":"{\"level\":\"warn\", \"msg\":\"this is a log message\"}","container_id":"3fd8678d","container_name":"/angry_kalam", "level":"warn", "msg":"this is a log message"}
```

**Comment by aiwantaozi** [comment]
QA could verify, after upgraded:
1. whether the new Fluentd pod have warning log related to `merge_json_log` and `preserve_json_log`
2. whether the json source messge would be parsed into JSON and attaching it to the payload

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ad1679532

* Created cluster
* Enabled logging
* Checked fluentd logs
* There are no warnings for: 
  * `merge_json_log`
  * `preserver_json_log`
* Log statements do not have json parsed and added to the payload:

![Screen Shot 2019-08-20 at 2 15 29 PM](https://user-images.githubusercontent.com/21316915/63385040-04b33280-c355-11e9-9ed6-99a34c3d86a9.png)
