### ISSUE TITLE
Having a problem provisioning cluster node using Terraform and Rancher2 provider.

### ISSUE THREAD

**Issue by Babramson** [rancher/rancher#22212]
**What kind of request is this (question/bug/enhancement/feature request):**
This is a bug, as far as i can tell.

**Steps to reproduce (least amount of steps as possible):**
I am provisioning AWS assets using the Terraform AWS provider and resources. Rancher Master and slave nodes are EC2s. Once the Rancher Master EC2 is online i'm using the below listed path.

Code:
**Provider info** (main.tf)
```
provider "rancher2" {
  alias = "bootstrap"
  api_url = "https://${var.client_endpoint_fqdn}"
  insecure = true
  bootstrap = true
}

provider "rancher2" {
  api_url = "${rancher2_bootstrap.admin.url}"
  token_key = "${rancher2_bootstrap.admin.token}"
  insecure = true
}
```

**Rancher assets** (rancher.tf)
```
# Create a new rancher2 Bootstrap
resource "rancher2_bootstrap" "admin" {
  provider = "rancher2.bootstrap"
  telemetry = false
}

resource "rancher2_cluster" "dev-tier1" {
  name = "dev-tier1"
  description = "Development cluster, including dev-tier1"
  rke_config {
    network {
      plugin = "canal"
    }
  }
}

resource "rancher2_cluster_logging" "dev-tier1-elastic" {
  name = "dev-tier1-elastic"
  cluster_id = "${rancher2_cluster.dev-tier1.id}"
  kind = "elasticsearch"
  elasticsearch_config {
    endpoint = "${var.elastic_endpoint}"
    ssl_verify = false
  }
}

resource "rancher2_node_template" "dev-tier1-temp_a" {
  name = "${var.account_name}-dev-rancher-node-"
  description = "Development Tier1 template"
  amazonec2_config {
    ami =  "${var.rancher_slave_ami}"
    region = "${var.aws_region}"
    security_group = ["${var.sec_group_all_name}", "${var.sec_group_node_name}"]
    subnet_id = "${var.subnet_a}"
    vpc_id = "${var.vpc_main}"
    zone = "a"
    instance_type = "m5.large"
    tags = "tier_level,${var.tier_level},cluster_id,${var.cluster_id}"
  }
}

resource "rancher2_node_pool" "dev-tier1-node_a" {
  cluster_id =  "${rancher2_cluster.dev-tier1.id}"
  name = "dev-tier1-node-a"
  hostname_prefix =  "dev-tier1-node-a"
  node_template_id = "${rancher2_node_template.dev-tier1-temp_a.id}"
  quantity = 1
  control_plane = true
  etcd = true
  worker = true
}

```
**Terraform Execution Steps**
1) provision AWS assets using `terraform apply` and `-target=` for each asset needed. (the AMI comes up with Rancher Master starting back up, unconfigured.)
2) execute `terraform apply -target=rancher2_bootstrap.admin`
3) provision Rancher assets using `terraform apply -target=rancher2_cluster.dev-tier1 -target=rancher2_node_template.dev-tier1-temp_a -target=rancher2_node_pool.dev-tier1-node_a`

I'm including 2 logs from the Rancher Master server, which was from 2 separate build/destroy paths. The first path was using Terraform to provision all the way up to the `rancher2_cluster` resource creation, after which i manually add a node using the UI provided Node Run Command snippet. The second path was using Terraform to provision all the way up to (and including) the `rancher2_node_pool` resource.

**Result:**
The EC2 provisions and the Rancher UI shows that the node's state is "Waiting for SSH to be available...". It stays like this indefinitely. 

**Other details that may be helpful:**
@luthermonson had tried helping me in the rancher users slack channel and has more context on the issue. Here is the original message i posted the channel:

> question for anyone who can help: i'm using the Terraform Rancher2 provider to build out my infrastructure on AWS (using EC2), and i'm running into an issue with the rancher2_node_template being invoked when i launch a rancher2_node_pool. The node provisioned stays in a "Waiting for SSH to be available" state indefinitely (in the Rancher UI), however i have confirmed that the EC2 is up and running and can be accessed over SSH via the Rancher Master docker container (i did this manually). can anyone help?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher version v2.2.4
Docker Image: rancher/rancher:latest (ImageId: 2c8edab4e2d9)
Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
  Provider: Amazon EC2 (as listed in the `Global` interface; cloud provider radio for cluster is checked `None`)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
 Cloud; Amazon EC2; m5.large; 2xvCPU/8xECU/8GB
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2-lite5", GitCommit:"bc906af66ea66ec77794bdbcb4ae4adf189b1c13", GitTreeState:"clean", BuildDate:"2019-02-28T06:49+00:00Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2-lite5", GitCommit:"bc906af66ea66ec77794bdbcb4ae4adf189b1c13", GitTreeState:"clean", BuildDate:"2019-02-28T06:49+00:00Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
[rancher_master_manual_node_add.log](https://github.com/rancher/rancher/files/3507334/rancher_master_manual_node_add.log)
[rancher_master_terraform_node.log](https://github.com/rancher/rancher/files/3507335/rancher_master_terraform_node.log)

**Comment by superseb** [comment]
What AMI/OS are you using? The default SSH user in the provider is `root`, while that is almost never the SSH user on EC2 instances/AMIs.

**Comment by Babramson** [comment]
I'm using bionic release 20190722.1 (ami-03b6f27628a4569c8) which uses `ubuntu` as default SSH user, and for the node being provisioned the `config.json` has `"SSHUser": "ubuntu"`.

**Comment by WMcKibbin** [comment]
Hey all,

Are there any updates on this?

**Comment by Babramson** [comment]
Hey @superseb,

Any news on what might be the issue?

**Comment by cloudnautique** [comment]
@Babramson I think where @superseb was going is that in the `amazonec2_config` on your node template you should set the `ssh_user = ubuntu`.

https://www.terraform.io/docs/providers/rancher2/r/nodeTemplate.html#ssh_user
