### ISSUE TITLE
Alert - threshold is reset to the default in alert's editing page

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#22210]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug in Rancher: master-head 

**Steps to reproduce (least amount of steps as possible):**
- enable cluster monitoring 
- add a cluster alert with a condition and threshold 
- check the alert in the `Cluster Alert Groups` page, see the condition is `Greater Than 50`

<img width="1439" alt="Screen Shot 2019-08-15 at 2 14 59 PM" src="https://user-images.githubusercontent.com/6218999/63128343-8ed05500-bf69-11e9-9da5-2085ee0aa729.png">

- edit the alert

**Result:**
- the threshold is set to the default valule 0, not 50

<img width="1433" alt="Screen Shot 2019-08-15 at 2 15 16 PM" src="https://user-images.githubusercontent.com/6218999/63128039-d4d8e900-bf68-11e9-8833-44b1bb5cb754.png">

**Other details that may be helpful:**
This is not seen in v2.2.7, in other words, the threshold is reserved in the alert's editing page in v2.2.7

**Comment by izaac** [comment]
Version: master-head (2.3) (8/16/2019)

I went through adding alerts with the Expression condition as described above where the expression value wasn't persisting after adding and then editing.

I also included the Expression condition and Interval as part of the regression test to validate there wasn't any introduced after the code change.

Tested using Chrome and Firefox.
In summary I wasn't able to reproduce the issue anymore in today's latest build and it looks good.
