### ISSUE TITLE
[UI] Tooltips have cut-off text in some cases

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22229]
Version: master-head (v2.3) (8/16/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a CT. Hover over some of the override switches to get tooltips. Several areas show that the text is cut off.

**Result:**
![image](https://user-images.githubusercontent.com/45179589/63184998-b678f900-c00d-11e9-9acc-1a8fa5ad7495.png)
I think we need to tweak styling -- if I had to guess this is happening due to the method we do wrapping or something.

Other examples:
![image](https://user-images.githubusercontent.com/45179589/63185075-e1fbe380-c00d-11e9-8c60-7f25c7b8f5ce.png)
![image](https://user-images.githubusercontent.com/45179589/63185082-e6280100-c00d-11e9-9655-32ec9981a8e8.png)

**Other details that may be helpful:**
This is probably happening in other areas of the Rancher UI as well; I just haven't found any additional areas as of yet. The change we make should be global ideally so we can fix this on all pages!

**Comment by tfiduccia** [comment]
@davidnuzik - I just removed the key from the text.  So now it just says "Allow user override?"

**Comment by davidnuzik** [comment]
I think this makes sense. We don't allow custom overrides anymore and so that isn't really needed anymore.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/21/19)

Now all the help text for the override switches just says "Allow user override?"
![image](https://user-images.githubusercontent.com/45179589/63475177-b2474400-c430-11e9-9986-2b0a13f49632.png)
