### ISSUE TITLE
v2.1.x project namespace gets stuck in terminating if they had alerts

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#22231]
Steps are somewhat theoretical, but I've seen it in a user's setup:

1. Create a project and project alerts in v2.1
2. Upgrade to v2.2
3. Delete the project
4. Using kubectl against the rancher control plane kubernetes, do `kubectl get ns`

You'll see that the namespace corresponding to the project you deleted is stuck in terminating.
If you do `kubectl -n <project id> get projectalerts -o yaml` you should see at least one alert that is stuck in deleting with a finalizer that looks like `clusterscoped.controller.cattle.io/project-alert-podtarget_c-123456`.

This is because the lifecycle for project alerts was dropped here https://github.com/rancher/rancher/blame/master/pkg/controllers/user/alert/watcher/pod.go#L65

Probably should backport fix to v2.2. Please check to see if any other lifecycles were dropped in that PR.

**Comment by sowmyav27** [comment]
Validated the issue - upgraded from `rancher:v2.1.13` to `v2.3.0-alpha7`.

- Create a project and project alerts in v2.1.13
- Upgrade to v2.3.0-alpha7
- Delete the project
- Using kubectl against the rancher control plane kubernetes, do kubectl get ns
- namespace corresponding to the project deleted is stuck in terminating.
- do kubectl -n <project id> get projectalerts -o yaml, alerts are available in `Active` status. They are NOT in deleting status.

Validated the fix. Validated the issue - upgraded from `rancher:v2.1.13` to `master-head` (latest).
- Create a project and project alerts in v2.1.13
- Upgrade to master
- Delete the project
- Using kubectl against the rancher control plane kubernetes, do kubectl get ns
- namespace corresponding to the project is not available and has been deleted.
