### ISSUE TITLE
[UI] Provide disk size field for non-managed azure clusters

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#22236]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. go to create an rke cluster using azure
2. the disk size field shows once selecting managed, but does not show prior

**Result:**
Disk size is now valid for managed and non managed, so we should show it regardless. Also would like to point out that the field did not disappear if switch back to non-managed, not that this should matter after this change.

**Other details that may be helpful:**
Backend issue: https://github.com/rancher/rancher/issues/22074

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/19/19)

Now when you create a nodeTemplate in the UI you see the Disk Size for Unmanaged Disk (default) it is shown in both situations (as it once did) but actually works now for unmanaged.

![image](https://user-images.githubusercontent.com/45179589/63303410-9dce4480-c294-11e9-999a-3490ec32e9b6.png)

I smoke tested by creating a couple of clusters one with default and one with non-default value for the Disk Size. I launched the Azure web console and looked at the disk to ensure the size was correct. the UI and API both look good. I was not able to identify any issues.
