### ISSUE TITLE
Update cert-manager version for HA installs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#22235]
LetsEncrypt is no longer going to support cert-manager < v0.8.0 as of November 1, and the docs on how to install/use cert-manager is pinned to v0.5.2.

Need to investigate if there are any other issues with using a later version of cert-manager version and update docs after investigation. 

There’s a new yam file for cert-manager CRDs that we just need to reference in the docs and also potentially host on our site

https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#optional-install-cert-manager

**Comment by deniseschannon** [comment]
We also need to investigate/account for the users who are using the old cert-manager and need to upgrade to the latest cert-manager.

**Comment by cjellick** [comment]
Update:
The steps are slightly more complicated that before. See here: https://cert-manager.readthedocs.io/en/latest/getting-started/install/kubernetes.html

Has a lot of implications. Heres what we need to do:
1. These steps also involve putting cert-manager into its own namespace called cert-manager, so we will add that to the list of namesapces that get automatically added to the system project (Dan)
3. The docs update will have a link to the official install steps, but also inline those steps in our documentation. (Dan)
4. Docs also need a "call out" or "note" section that warns people that they need to upgrade cert-manager because the old version will stop working with letsEncrypt soon (Dan)
5. Rancher HA *upgrade* docs should have a reference to upgrading cert-manager (Dan)
6. We should call out in our v2.3 release notes that ppl need to update cert-manager (Bill or Craig or Denise)
7. We should send out an advisory warning people of this (Denise)

**Comment by dnoland1** [comment]
@deniseschannon , @cjellick As part of this issue, do we also plan on updating the Let's Encrypt cert-manager available in the catalog? Currently it only let's you select v0.5.2, v0.4.1, and v0.3.2.

**Comment by dramich** [comment]
@dnoland1 https://github.com/rancher/charts/issues/179

**Comment by kingmatusevich** [comment]
> Update:
> The steps are slightly more complicated that before. See here: https://cert-manager.readthedocs.io/en/latest/getting-started/install/kubernetes.html
> 
> Has a lot of implications. Heres what we need to do:
> 
> 1. These steps also involve putting cert-manager into its own namespace called cert-manager, so we will add that to the list of namesapces that get automatically added to the system project (Dan)
> 2. The docs update will have a link to the official install steps, but also inline those steps in our documentation. (Dan)
> 3. Docs also need a "call out" or "note" section that warns people that they need to upgrade cert-manager because the old version will stop working with letsEncrypt soon (Dan)
> 4. Rancher HA _upgrade_ docs should have a reference to upgrading cert-manager (Dan)
> 5. We should call out in our v2.3 release notes that ppl need to update cert-manager (Bill or Craig or Denise)
> 6. We should send out an advisory warning people of this (Denise)

You should know jetstack has been notifying users about the passing of 0.8.0 via the email registered with LE, so that's at least on its way already

**Comment by bmdepesa** [comment]
rancher/rancher:master-head dbd970ae7

#### Fresh install
* Deployed Rancher in HA with self-signed certs using new cert manager installation instructions 
  * https://github.com/rancher/docs/pull/1691
* Created a cluster
* Deployed some workloads / ingress
* Installation was successful
* cert-manager namespaces are present in `System` project

#### Upgrade
* Deployed Rancher v2.2.8 in HA with self signed certs, following existing cert manager installation instructions
* Followed new docs to backup and upgrade cert manager
  * https://github.com/rancher/docs/pull/1691
* Upgraded Rancher to master-head with 2.3.0-alpha7 chart
* cert-manager is upgraded (now version 0.9.1)
* cert-manager namespaces are present in `System` project

**Comment by jiaqiluo** [comment]
Fresh install `Rancher:v2.3.0-rc1` in the air-gapped HA mode

Steps:

0. Prepare Images 
```
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm fetch jetstack/cert-manager --version v0.9.1
helm template ./cert-manager-v0.9.1.tgz | grep -oP '(?<=image: ").*(?=")' >> ./rancher-images.txt
```
1. Render the cert-manager template
```
helm template ./cert-manager-v0.9.1.tgz --output-dir . \
--name cert-manager --namespace cert-manager \
--set image.repository=my-registry/quay.io/jetstack/cert-manager-controller
```

2. Download the required CRD file for cert-manager
```
curl -L -o cert-manager/cert-manager-crd.yaml https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml
```
3. Create the namespace for cert-manager
```
kubectl create namespace cert-manager
kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true
```
4. deploy 
```
kubectl apply -f cert-manager/cert-manager-crd.yaml
kubectl  apply -R -f ./cert-manager
 ```

**Comment by cjellick** [comment]
https://github.com/rancher/docs/pull/1713

**Comment by jiaqiluo** [comment]
**Upgrade**
- Deployed Rancher v2.2.8 in HA with self signed certs, following existing cert-manager installation instructions (cert-manager:v0.5.2)
- add a custom RKE cluster and enable cluster monitoring and istio
- Upgraded Rancher to v2.3.0-rc2
- cluster still works
- upgrade cert-manager to version 0.9.1
- cert-manager namespaces are present in System project
- cluster still works, I can also rotate certificates

**Comment by amagura** [comment]
Is there any sort of timeline for when the cert-manager chart in the `https://git.rancher.io/charts` library will be updated to allow users to install cert-manager versions `>= 0.8.0`?
