### ISSUE TITLE
[UI] Issues on Cluster Templates page

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22230]
Version: master-head (v2.3) (8/16/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create 2 or more cluster templates
- Try to click on the "Select all" checkbox on the Cluster Templates page
- Try to click on any checkbox for any cluster template revision
- Notice the Delete button is now missing (it also is from function menu)

**Result:**
Select-all checkbox does not select all the CTRs anymore
Delete button is gone now (is this expected?)
Delete action is also missing from the function menu for each CTR
![image](https://user-images.githubusercontent.com/45179589/63185409-d1983880-c00e-11e9-9561-d6e9f5c94d33.png)

Can't click on individual CTR any longer (nothing happens)
![image](https://user-images.githubusercontent.com/45179589/63185273-77977300-c00e-11e9-8f45-80398fac3d9b.png)

**Other details that may be helpful:**
No JS errors for any of these problems.

**Comment by vincent99** [comment]
You only have one revision (per template), and you can't delete the default revision, so the checkbox is disabled.  There was an attempt at this in the code before but it was not actually working, so I made it work.

**Comment by vincent99** [comment]
Tani and I concluded you should be able to deactivate but not delete the default revision, so I took out the disabled checkbox.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/23/19)

I can now select all without any issues (select all checkbox) this selects all the revisions in view.
I am able to disable/enable any/all CTR including if they are default.

I am able to delete via the delete function menu and the button in situations where the default revision is not checked.

I tested by doing various smoke tests and could not identify any issues.
