### ISSUE TITLE
[UI] Cluster Templates - Correct UI message when there are no cluster templates 

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#22250]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Login to Rancher setup
2. Navigate to User Profile -> Cluster Templates
3. When there are no cluster templates, UI shows "There are no clusters defined."

**Result:**
Error Message should be  "There are no cluster templates defined."

<img width="955" alt="Screen Shot 2019-08-16 at 5 27 00 PM" src="https://user-images.githubusercontent.com/1470602/63204348-8d775900-c04b-11e9-901c-fef208ace29c.png">

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/19/19)

Both the formatting (page styling) and the text has been fixed:
![image](https://user-images.githubusercontent.com/45179589/63292538-baf61980-c27a-11e9-930b-271d9d06741a.png)

This is also working correctly in a mobile-view (small page dimensions):
![image](https://user-images.githubusercontent.com/45179589/63292580-d6f9bb00-c27a-11e9-95fa-9b20c54c3e35.png)
