### ISSUE TITLE
Blank error message when attempting to edeploy EFK App

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#22252]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Attempt to launch EFK app from Catalog 

**Result:**
Error message without any information

**Other details that may be helpful:**
Using the dark theme.  See error message at bottom of screen
![image](https://user-images.githubusercontent.com/8906089/63204930-1c5c9380-c095-11e9-8dd5-a360a72556f5.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.6
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Fixed in new version of EFK
