### ISSUE TITLE
Cronjob Schedule doesn't use masters timezone but UTC

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#22259]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- setup host-timezone on control-nodes to sth different than UTC
- schedule a cronjob for a specific hour

**Result:**
Cronjob runs on UTC rather than timezone set on master

**Other details that may be helpful:**
I guess the Problem is that the host-timezone is ignored within the kube-* containers.
relating issue: https://github.com/kubernetes/kubernetes/issues/80577

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): 1.14.5

regards,
strowi

**Comment by elvizlai** [comment]
same issue

**Comment by mentgmery** [comment]
@elvizlai do you mean can resolve it by mounting /etc/localtime to kube-controller-manager?

**Comment by pakali** [comment]
Edit cluster.yaml (Edit cluster > Edit as YAML) and add this lines to services section:

`
services:
    kube-controller:
      extra_binds:
        - '/etc/localtime:/etc/localtime'
`

After that configure correct timezone on Control Plane role nodes.
