### ISSUE TITLE
Allow catalog apps to be able to configure min or max app versionn

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#22266]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**

A major version upgrade of apps may require the user to re-install the app, and upgrading from the old version may not be supported, so Rancher should allow the catalog apps to config the minimum and maximum upgradeable version.

The configuration can be added to the `questions.yml` with following labels.
```
labels:
  io.rancher.app_min_version: 1.0.2
  io.rancher.app_max_version: 1.9.2
````

**Result:**
UI will filter out the upgradeable version upon the `app_min_version` and `app_max_version`.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/20523
