### ISSUE TITLE
canal Health check error

### ISSUE THREAD

**Issue by huntsman-li** [rancher/rancher#22263]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
systemctl restart docker
 

**Result:**
rke deploy：
![image](https://user-images.githubusercontent.com/36752240/63236240-8c267600-c26f-11e9-966d-89d1f63838ab.png)

**Other details that may be helpful:**
Stand-alone deployment configuration:
![image](https://user-images.githubusercontent.com/36752240/63236314-d4459880-c26f-11e9-95c4-6170933ac851.png)

rke deploy:
![image](https://user-images.githubusercontent.com/36752240/63236357-fdfebf80-c26f-11e9-9026-de386d193f4f.png)

version:
Stand-alone deployment configuration: 2.2.4
![image](https://user-images.githubusercontent.com/36752240/63236406-21296f00-c270-11e9-807c-3f16ac471394.png)

rke deploy:2.2.7
![image](https://user-images.githubusercontent.com/36752240/63236411-271f5000-c270-11e9-9c3c-570c5479d4be.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/19992 && https://github.com/rancher/rancher/issues/20749
