### ISSUE TITLE
Add k8s versions 1.13.10, 1.14.6, 1.15.3

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#22269]
**What kind of request is this (question/bug/enhancement/feature request):**
Add k8s 1.13.10, 1.14.6, 1.15.3

**Comment by sangeethah** [comment]
Tested with master - `797db23c2`

During cluster creation , we are are not presented with 1.13.10. We still see `1.13.9` version.
 
<img width="541" alt="Screen Shot 2019-08-21 at 4 01 55 PM" src="https://user-images.githubusercontent.com/4266958/63474569-81660f80-c42e-11e9-975b-c27e05c00703.png">

Able to create cluster with K8s version `1.14.6` and  `1.15.3` successfully.

Reopening to make K8s `1.13.10` available.

**Comment by kinarashah** [comment]
Bug on rancher metadata feature, the PR is fine.

**Comment by sangeethah** [comment]
Tested with latest master build - `c3eece0ca`
Able to create cluster with K8s version 1.13.10 is presented in UI as expected .
Able to get a cluster up and running with this version successfully.
