### ISSUE TITLE
Backport: Add k8s v1.13.10 to 2.1.x

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#22270]
**What kind of request is this (question/bug/enhancement/feature request):**
Backport v1.13.10 to 2.1.x (https://github.com/rancher/rancher/issues/22269)

**Comment by sangeethah** [comment]
Tested with v2.1.13-rc2
K8s version 1.13.10-rancher1-1 is available .
Able to deploy cluster successfully. Automation runs did not report any new failures.
