### ISSUE TITLE
Machine scaling groups

### ISSUE THREAD

**Issue by jas99** [rancher/rancher#2227]
Create cluster/swarm of hosts with ability create and edit config  such as small to medium type on EC2. And ability to scale that same config. i.e one set of labels.

Right now host1,host2,host3 will be created. This does't make sense as I have to edit labels on each of them.

So if the scale of cluster will 3. Then 3 docker containers can be scheduled on each machine. I you want diff label to constraint you create another cluster with diff capability.

Thx

**Comment by deniseschannon** [comment]
Currently, when you create hosts in the UI, you can add labels and create many of them at once. 

Just so we're clear, you want to be able to cluster the hosts together so that any further edits to the hosts (ie. labels) would be able to applied to the cluster. 

Is that correct?

Also, for scheduling, if all the hosts have the same label, you can create a scheduling rule with the host label that matches those hosts and another rule so that there are no other of the same containers to schedule your 3 containers on the 3 different hosts in your cluster.

**Comment by jas99** [comment]
@deniseschannon 
denise - "Just so we're clear, you want to be able to cluster the hosts together so that any further edits to the hosts (ie. labels) would be able to applied to the cluster."

Yup it doesn't make sense to show all clones. Lets say I want 5 machines with same config. And maybe i just want to bump it up to 8. This should be one item. If and want diff lable and diff machine type I will create seprate item or cluster.

**Comment by deniseschannon** [comment]
To bump to eight, you could just clone (to get the same configuration) and then change the scale to the additional number that you would want.

**Comment by jas99** [comment]
@deniseschannon But I am arguing for one list item on UI. Right now it will be Machine1 Machine2 Machine3 .... 
I say show one Item Machine with scale 3 in desc. Consequentially any changes made such as label will be for all of them.

Thx

**Comment by vincent99** [comment]
Showing 3 hosts as one of the current boxes makes no sense.. They are independent computers with independent states, IPs, etc that fail (usually) independently.

I could see a way to define "host groups" as maybe useful, or a more general way to do bulk selection/tagging without introducing another top level resource.

**Comment by ibuildthecloud** [comment]
I think machine scaling groups would be useful.  They say a common template for settings and you can easily scale up/down the number of them.

**Comment by jas99** [comment]
@vincent99 Agreed to what you said. Was thinking same thing might not have communicated in a better way.
Thx

**Comment by vincent99** [comment]
2.0 has `hostTemplates` which do mostly this, especially combined with the webhook for scaling the number of hosts (which is also in 1.6 via cloning a host by selector instead).
