### ISSUE TITLE
Backport: Add k8s versions 1.13.10, 1.14.6, 1.15.3 to v2.2.x

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#22271]
**What kind of request is this (question/bug/enhancement/feature request):**
Add k8s versions 1.13.10, 1.14.6, 1.15.3 to v2.2.x (https://github.com/rancher/rancher/issues/22269)

**Comment by sangeethah** [comment]
Tested with `v2.2.8-rc3`
K8s version `1.13.10-rancher1-2` is available .
Able to deploy cluster successfully. Automation runs did not report any new failures.
