### ISSUE TITLE
Windows agent clean up script doesn't work

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#22282]
master-head (08/14)

Steps:

In host gateway mode, when reuse node, kubernetes api server's cluster ip 10.43.0.1 is unreachable. 

After delete that windows node from cluster, run clean.ps1 under c:/etc/rancher, and run get-hnspolicylist | remove-hnspolicylist to clean the policy, then add back that node, the api server' cluster ip is reachable again.

Expected: 

We should be able to re-use host after running clean.ps1. Users don't have to run  `get-hnspolicylist | remove-hnspolicylist` manually

From https://github.com/rancher/rancher/issues/20968#issuecomment-506585924

**Comment by kingsd041** [comment]
Version: master master-head (8/28/19) 
Confirmed fix.  Followed the same steps as the ticket describes and got the expected result.
