### ISSUE TITLE
[UI] Cluster Templates - Remove access type "Member"

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#22280]
Based on this discussion, Cluster Templates Members will only have two access types: "Owner" and "User"
https://github.com/rancher/rancher/issues/21720#issuecomment-521759473

**Comment by sowmyav27** [comment]
**Verified on `master-head` - commit id: `93019c54b`**
Cluster Templates Members have two access types: "Owner" and "User"
<img width="1333" alt="Screen Shot 2019-08-20 at 8 56 15 AM" src="https://user-images.githubusercontent.com/26032343/63363475-8476d800-c328-11e9-97af-3abc221775da.png">
