### ISSUE TITLE
Cannot create HPA via Rancher UI in GKE

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#22292]
Rancher HPA support will be enabled in Rancher 2.3. We are using HPA in `v2beta2.autoscaling` API group. But in some reasons, GKE doesn't support API group `v2beta2.autoscaling` so we don't support HPA function in GKE.

**Comment by shandyDev** [comment]
**UPD**:
Since GKE 1.15.5 v2beta2.autoscaling API is working!
https://issuetracker.google.com/issues/135624588

**Comment by deniseschannon** [comment]
@soumyalj Is this working now with the latest GKE versions?

**Comment by soumyalj** [comment]
@deniseschannon :
Created a rancher setup using master-head build.
Created GKE cluster with K8s version : v1.15.7-gke.2 in Rancher . 
Yes, HPA is functional in this K8s version v1.15.7-gke.2
