### ISSUE TITLE
[UI] [Huawei CCE] Available Zone is not change after switch region

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#22294]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**
1. Select a region (not default region: cn-north-1)
2. Click next and click Save

**Result:**
availableZone still cn-north-1a

**Other details that may be helpful:**
master (8/20/2019)

**Comment by kingsd041** [comment]
Version: master master-head (8/27/19) 
Confirmed fix. Create a Huawei CCE cluster. AvailableZone can view the correct value.
