### ISSUE TITLE
how to add dns entity in jenkins slave

### ISSUE THREAD

**Issue by damozhiying** [rancher/rancher#22293]
i have a gitlab server in k8s, access by ingress ，such as gitlab.xx.com, the rancher pipeline jenkins slave can't resolving the gitlab.xx.com, so i want to know how to config etc/hosts or add dns entity in rancher pipeline jenkins slave

**Comment by Amos-85** [comment]
@damozhiying ,
have you tried to run curl from the jenkins slave to the gitlab ClusterIP ?
if it's not on same namespace you should point to gitlab ClusterIP with the  suffix namespace
