### ISSUE TITLE
Rancher 2: not able to add https:// to my service

### ISSUE THREAD

**Issue by MohamedBenighil** [rancher/rancher#22295]
Hello, 

I have a service running on  on rancher, but when i click on its link (red reectangle):
![singature1](https://user-images.githubusercontent.com/49414837/63335174-302a2300-c33d-11e9-95d9-e5355c3cdede.PNG)

It takes me to web page which has the following link : http://10.XXX.XXX.13:30666. 

But what i would like, is to take me to : https://10.XXX.XXX.13:30666   (so : https and not http).

is there any way to fix this ?

Any help would be appriciated!

**Comment by tfiduccia** [comment]
@MohamedBenighil - if the listening ports ends in 443 or it's an ingress it will go to https.

**Comment by MohamedBenighil** [comment]
@tfiduccia, if it's an ingress that says the protocol is https, how can i do that ?

**Comment by leodotcloud** [comment]
@MohamedBenighil I am assuming you had asked this question: https://stackoverflow.com/questions/57771839/how-add-https-to-docker-container-as-default-rather-than-http. 

You can find an example of creating an Ingress using TLS on the Kubernetes docs website. https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
