### ISSUE TITLE
v2.3.0-alpha5 切换catalogs功能无效，切换后都会出现全部

### ISSUE THREAD

**Issue by CodingAdai** [rancher/rancher#22290]
*v2.3.0-alpha5 切换catalogs功能无效，切换后都会出现全部*

![image](https://user-images.githubusercontent.com/9160284/63320382-3249ad00-c350-11e9-872d-82ecb806641d.png)
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.0-alpha5` UI: `v2.3.2` |
|Route|`apps-tab.index`|

**Comment by loganhz** [comment]
fixed in master-head
