### ISSUE TITLE
When client id/client secret values is of invalid length provide error message to users.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#223]

**Comment by sangeethah** [comment]
Version - V0.11.1
Try to enable access control.
When client id/client secret values is of invalid length, "Authenticate with GitHub" key is inactive. It is kind of confusing to see the key still inactive when we have entered all the required values. It would be better to provide a error message indicating that the field length is invalid.

**Comment by vincent99** [comment]
Removed the length check, it's not terribly useful.
