### ISSUE TITLE
Create a dev branch for kontainer-driver-metadata once Rancher v2.3 ships

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22308]
After v2.3 ships, we should remember to create a dev (staging) branch for kontainer-driver-metadata repo. Also as a part of it, we would need to update rancher to use dev branch by default for the non official release images.

**Comment by deniseschannon** [comment]
Should it be a dev branch or per release branch?

**Comment by deniseschannon** [comment]
Spoke with @alena1108, no need to branch rke-tools. We branched kontainer-driver-metadata.

We have also branched rancher/rancher, so need to work on updating the master branch in rancher/rancher to use dev branch.
