### ISSUE TITLE
Clone a container with Networking/Links missing

### ISSUE THREAD

**Issue by renaudManda** [rancher/rancher#2230]
If I clone a container with  networking>links inside, the result container doesn't contain the networking>links of the source container.

**Comment by deniseschannon** [comment]
Can you provide a screenshot as I'm unable to find the "Networking/Links" portion that you are discussing?

Also, what version of Rancher server are you running?

**Comment by deniseschannon** [comment]
@renaudManda Never mind, I was looking at adding services and not adding containers. 

Reproduced in v0.40.0

**Comment by tfiduccia** [comment]
Version - master UI 318
Verified fixed
