### ISSUE TITLE
[v2.2.8] blank white page after upgrading from 2.2.7 to 2.2.8 via helm

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#22318]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
> install RKE
> setup a cluster with RKE
> install rancher 2.2.7
> upgrade to rancher 2.2.8

**Result:**
blank web page when browsing the rancher url

**Other details that may be helpful:**
Tested with Brosers: Chrome and Edge
Browser Console output:
```
GET https://rancher.#####/assets/vendor-c71a5040def4e5865621fc1d9d2bcaea.js 404
service.js:1 Uncaught ReferenceError: define is not defined
    at service.js:1
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.2.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 VMs, 8 Cores and 16 GB RAM per VM
- Kubernetes version (use `kubectl version`): v1.14.6
- Docker version (use `docker version`): 19.03.1, build 74b1e89

**Comment by andreastoermer** [comment]
i've got nearly the same problem. he cannot find my ui and vendor js file anymore.

**Comment by loganhz** [comment]
Which page did you see this issue? Can you still login Rancher UI?

**Comment by andreastoermer** [comment]
No, you can see it when open https://rancher.sandboxer-technik.de/

Directly after open the url, the problem start and he cannot find the ui and vendor js file and cannot show the login page or anything else

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/63414641-db66d500-c42e-11e9-94ce-c8f191ab9cec.png)

Can you try to disable the cache? I can open this url

**Comment by andreastoermer** [comment]
thats strange, different browser on same pc, same problem
use laptop where i open rancher in the past, same problem
use tablet, where i never open the page, everything works

**Comment by MSandro** [comment]
same problem here, I've downgraded to 2.2.7

**Comment by andreastoermer** [comment]
@loganhz I see in your screenshot, that the js names are different:

Before 2.2.8: 
vendor-c71a5040def4e5865621fc1d9d2bcaea.js
ui-3a8eb40963e8653e795a4827b004ae78.js

2.2.8:
engine-vendor-....js
engine-....js

Can this change maybe broke something?

**Comment by loganhz** [comment]
Please open your chrome dev tools -> Select `Network` section and Click `Disable cache`

![image](https://user-images.githubusercontent.com/21168270/63417524-09024d00-c434-11e9-95d8-dd4e0b6b484e.png)

**Comment by andreastoermer** [comment]
https://imgur.com/a/iQ4gzNA

As said 30 min ago, i tried this!

> disable cache, same problem
> different newly installed browser on same pc, same problem
> use laptop where i open rancher in the past, same problem
> use tablet, where i never open the page, everything works

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/63417805-95ad0b00-c434-11e9-8ba5-3534ba431016.png)

**Comment by andreastoermer** [comment]
I know that you don't have this problem, I don't have this problem on a tablet that never open the page before too.

But on my computers, where i open the page before the update i have it.

**Comment by loganhz** [comment]
Can you open https://rancher.sandboxer-technik.de/assets/vendor-c71a5040def4e5865621fc1d9d2bcaea.js on your PC?

**Comment by MSandro** [comment]
Already tried to disable cashing, deleted cokies and much more, but nothing worked
![rancher-blank](https://user-images.githubusercontent.com/10937159/63418346-384c9600-c403-11e9-8ed1-1bb8fa1667f3.png)

**Comment by andreastoermer** [comment]
404 page not found

**Comment by andreastoermer** [comment]
ok i found the problem (but i don't know how to solve it). It only occurs when i use my internet provider. When for example a use my mobile provider (handy as a hotspot) or vpn, everything works. But at the moment i don't know why

**Comment by MSandro** [comment]
I've tried to upgrade again today, and got the same issue :(

**Comment by infinytum** [comment]
Can confirm this behaviour. Switching to another network (mobile, vpn) shows me the working page. Using TOR seems to load up the page as well.

I'm using 2.3.2 and upgraded from 2.2.7

**Comment by govbetrieb** [comment]
I also got this problem. It was caused by my reverse-proxy. Adding one of the Node-IPs for the Domain in my /etc/hosts solved the Problem.
