### ISSUE TITLE
[UI] CORB errors in browser console on some external images while launching apps

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22315]
Version: master-head (v2.3) (8/20/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**

- Keep the Browser console open in developer tools.
- Launch a MCapp or an app at project level.

**Result:**

- CORBS warning messages will appear in the console about external images loaded.

**Other details that may be helpful:**

No http issues from browser side of things. No JS errors.
I did see some warnings though -- perhaps this is related to CORS and similar related fixes recently.

<img width="2076" alt="test" src="https://user-images.githubusercontent.com/27659/63396105-d6484e00-c37a-11e9-9f86-43e867632a91.png">

**Environment information**
- Installation option (single install/HA):

**Comment by loganhz** [comment]
@guangbochen some icons are missing in our Library. I think we need to change the logo url for those apps

**Comment by guangbochen** [comment]
will update to use local file instead of remote URL, thanks.

**Comment by guangbochen** [comment]
@izaac we have updated to use local icon path in `https://github.com/rancher/charts` with `k8s-1.16` branch, can u please help to validate using this branch, thanks.

**Comment by deniseschannon** [comment]
the k8s-1.16 branch has been merged to master as of v2.3.2

**Comment by soumyalj** [comment]
Reproduced the issue with v2.3.0
On launching multi cluster apps, we observe the CORB errors as below:
<img width="617" alt="Screen Shot 2019-11-05 at 3 03 26 PM" src="https://user-images.githubusercontent.com/18536626/68253714-778b8b80-ffdd-11e9-8866-132e3ff81a2f.png">

**Comment by loganhz** [comment]
@soumyalj please try 2.3.2 as the new version will only show in 2.3.2. This is a known issue in 2.3.0

**Comment by soumyalj** [comment]
Tested with version v2.3.2. On launching multi cluster apps,the CORB errors were not observed
![Screen Shot 2019-11-08 at 10 07 45 AM](https://user-images.githubusercontent.com/18536626/68500120-aab56100-020f-11ea-988b-1a4314ca0fa4.png)
