### ISSUE TITLE
修改网络模式为主机模式后依然保留原来托管模式分配的ip

### ISSUE THREAD

**Issue by kaswu1987** [rancher/rancher#22322]
rancher版本是1.6.14 
问题描述：
原来的容器是托管模式，因此被打上系统标签：io.rancher.container.ip，后来升级更换网络模式为主机模式，显示的依然还是这个ip，并且在重启容器时，会在宿主机上临时生成一块带有原来托管模式分配ip的网卡，在这块网卡存在的过程中会影响宿主机的网络通信，请问如何清理这个原来分配的ip

![image](https://user-images.githubusercontent.com/41895259/63422200-87fb8380-c43c-11e9-91d3-190877904949.png)

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or you can find Chinese community group via WeChat `rancher2`
