### ISSUE TITLE
New LDAP user first login can not see any of the clusters

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#22324]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
The first time a new user logs into our Rancher Server, they do not see any of the clusters. A logout/login resolves the problem. 

**Result:**
I can easily re-create the issue by deleting the user account from the Rancher Server, then having them login again.

**Other details that may be helpful:**
Our user accounts are backed by Active Directory.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.7
- Installation option (single install/HA): HA

gz#8604

**Comment by mattmattox** [comment]
This issue also effects v2.2.8

**Comment by tfiduccia** [comment]
@davidnuzik @izaac - this seems bad, can we check if it's a UI issue or backend?

**Comment by davidnuzik** [comment]
Version: v2.2.8

@mattmattox I wasn't able to reproduce. Are there any special steps required? None were provided in the issue.

- Enable Active Directory auth.
- Create a cluster, add a second (non-admin) user as the cluster owner (so they see the cluster on login)
- Log in as the second (non-admin) user and they see the cluster on first login (did not reproduce)

I also tried what you suggested as well:
> I can easily re-create the issue by deleting the user account from the Rancher Server, then having them login again.
- Follow the same steps above
- Delete the user account from the /g/accounts page (remove from rancher server)
- Log in as the second user and I now do NOT see the cluster
- BUT when I log in again I still don't see the cluster (not the same issue exactly as reported)
- When I log in as the admin user I see that removing the user from the /g/accounts page removed them as cluster owner so I guess that makes sense -- they shouldn't see the cluster.

What am I missing here? Appreciate any help and steps to reproduce.

**Comment by cjellick** [comment]
These steps don't make sense as is, but I am guessing that the missing step is that the user that cannot see the clusters (but supposedly should) is part of a group that has been granted access to those clusters.

**Comment by prachidamle** [comment]
yeah I agree to @cjellick's comment - this might be some delay added due to not able to find group memberships - which get refreshed on later login?

@mattmattox any chance you have more details on type of auth provider/ nested group is enabled etc.?

**Comment by zaggash** [comment]
Can you confirm it is a dup of https://github.com/rancher/rancher/issues/17318 ?
