### ISSUE TITLE
Annotations set on a node are not shown on the UI and labels get deleted

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22328]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster.
2. Go to Cluster--> Nodes --> Edit --> Labels & Annotations
3. Add an Annotation.

**Expected Result:**
Annotations set should be seen on the UI.
Labels set should NOT get deleted.

**Actual Result:**
- In the API request sent, you will see the annotation set.
- In the API request sent, `Labels` is not passed.
- Click on Nodes --> Edit --> Labels & Annotations, the labels section is `blank` and the annotation you set above, will NOT be available.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher-master - Commit id: `85dedb19b`
- Installation option (single install/HA): single

**Comment by n313893254** [comment]
Annotation cannot set is not a UI issue. 


After clicking edit and add a new annotation: `test: "test"`, respond is 200 status code but in the response body lack of `test: "test"`.

**Comment by sowmyav27** [comment]
Verified on latest master-head - commit id: `0fed88523`

**Steps:**

- Create a cluster.
- Go to Cluster--> Nodes --> Edit --> Labels & Annotations
- Add an Annotation.
- In the API request sent, you will see the annotation set.
- In the API request sent, Labels is passed.
- Click on Nodes --> Edit --> Labels & Annotations, the labels section is NOT blank anymore, and has the required set of labels.
- The annotation you set above, is NOT available.
- on kubectl - kubectl get nodes <node-name> -o json -- you will NOT see the annotation set

**Comment by loganhz** [comment]
`0fed88523` doesn't have the change. Please try to pull the master-head again

**Comment by sowmyav27** [comment]
verifying on master-head - commit id: `a98b70f17`

Steps:

- Create a cluster.
- Go to Cluster--> Nodes --> Edit --> Labels & Annotations
- Add an Annotation.
- In the API request sent, you will see the annotation set.
- In the API request sent, Labels is passed.
- Click on Nodes --> Edit --> Labels & Annotations, the labels section is NOT blank anymore, and has the required set of labels.
- The annotation you set above, is available.
- on kubectl - kubectl get nodes -o json -- you will see the annotation set
