### ISSUE TITLE
UI not selecting properly roles

### ISSUE THREAD

**Issue by Toriniasty** [rancher/rancher#22323]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug (couldn't raise it in UI project)

**Steps to reproduce (least amount of steps as possible):**
When selecting a global role for a user it will work as intended if you click the tick box (1). 
https://i.ibb.co/QdKTLf5/Screen-Shot-2019-05-07-at-15-23-50.png

**Result:**
if you click anywhere else in the selection box (2) it will tick the tick box but upon saving won't save the new settings.

**Environment information**
Affected is v.2.2.90 and below

**Comment by tfiduccia** [comment]
Version - master (will be in 2.3 release)
This has been fixed.
