### ISSUE TITLE
[UI] Multi-Cluster apps and Apps empty table missing bottom gray line as other tables.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22337]
Rancher version: master-head (v2.3) (08/21/2019)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Cluster Apps and Multi Cluster Apps (Global) empty tables are missing the same bottom line style from other empty tables.

**Result:**

For example this empty table has a gray line at the bottom after the "There are no <object> .." message. (Surrounded by the green square).

<img width="1379" alt="Screen Shot 2019-08-21 at 2 42 12 PM" src="https://user-images.githubusercontent.com/27659/63470759-4827a280-c422-11e9-8e0a-97d3dd0d1aec.png">

But Multi-Cluster apps and Apps tables are missing that gray bar.

<img width="1370" alt="Screen Shot 2019-08-21 at 2 46 20 PM" src="https://user-images.githubusercontent.com/27659/63470894-a5235880-c422-11e9-98e9-28d2dd7c704a.png">

<img width="1364" alt="Screen Shot 2019-08-21 at 2 46 30 PM" src="https://user-images.githubusercontent.com/27659/63470899-a785b280-c422-11e9-92ba-5fd2059d0e5f.png">

**Environment information**

- Installation option (single install/HA):

**Comment by tfiduccia** [comment]
Decided against fixing this.
