### ISSUE TITLE
[UI] Advanced Options section in Add Cluster should be at the bottom

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22332]
Rancher version: master-head (v2.3) (08/21/2019)

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- Check the options sections order in Rancher v2.2.8 for Add Cluster (DigitalOcean, Amazon EC2, etc).
- Compare the same UI section with latest master-head v2.3 (08/21/2019)

**Result:**

Order in v2.2.8:

<img width="1248" alt="Screen Shot 2019-08-21 at 12 27 26 PM" src="https://user-images.githubusercontent.com/27659/63462607-258c8e00-c410-11e9-9066-d3fc00ad1ab7.png">

Order in v2.3 (08/21/2019)

<img width="1256" alt="Screen Shot 2019-08-21 at 12 27 36 PM" src="https://user-images.githubusercontent.com/27659/63462627-30472300-c410-11e9-80d2-8694885d3661.png">

I think we should keep Advanced Option at the bottom in v2.3

**Environment information**

- Installation option (single install/HA):

**Comment by tfiduccia** [comment]
Closing in favor of: #23313
