### ISSUE TITLE
Logic mismatch in docker back-population can cause endless container event spamming

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#2233]
For native docker integration, we have logic designed to ignore rancher system containers so that they don't show up in the Rancher API, UI. "Rancher system containers" are ones that use the "rancher/agent" image.

Because of a logic mismatch between cattle and python-agent, a rancher system container using an older rancher/agent image can be interpreted as a system container in cattle and as a user container by python-agent. This logic mismatch causes the two systems to never get in sync for this container and a new container event being added and processed every 5 seconds for it.

The mismatch occurs because cattle checks if the image name contains "rancher/agent" but python-agent does not. Python-agent relies solely on the labels of the image.

We are going to fix this by removing the image name check from cattle. This will result in the container being processed as a use container and showing up in the API/UI.

If it seems weird that this fix will cause the container to show in the UI, it is, but it is the best we can do. Image names are not reliable, so we cannot match against them. We plan to revisit the sync logic in the future so that system containers are handled differently. But we need to make this fix so that we are not spamming container events.

**Comment by cjellick** [comment]
Steps to reproduce:
1. use a docker 1.8 host
2. On the host, run this command: `docker run -itd --entrypoint /bin/bash rancher/agent:v0.8.0`

Expected result:
The container shows up in the UI. The container_event table is not spammed with events.

Actual result:
The container does not show up in the UI. The container_event table is spammed with an event for this container every five seconds.

**Comment by sangeethah** [comment]
Tested with build from master - Aug 6

```
root@sangeemaster-10acre-1:/home/sangeethahariharan1# docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```
1. On the host, executed this command: docker run -itd --entrypoint /bin/bash rancher/agent:v0.8.0
2. Container shows up in the UI as expected.

Only 1 entry is created in container_event when this container is synced.

Also rancher-server is able to sync , stop and start states of the container successfully when the container is stopped and started from the host.
