### ISSUE TITLE
Standard Labels and Annotations for cluster, node, project and namespace should be made read-only on the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22331]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
On cluster/node/project/namespace, under Edit--> Labels & Annotations, the standard ones can be made read-only

**Cluster -** 
<img width="1225" alt="Screen Shot 2019-08-21 at 11 52 26 AM" src="https://user-images.githubusercontent.com/26032343/63460801-13a8ec00-c40c-11e9-8856-36ce1a4ad8ec.png">

**Node -**
<img width="973" alt="Screen Shot 2019-08-21 at 11 51 42 AM" src="https://user-images.githubusercontent.com/26032343/63460809-1acffa00-c40c-11e9-8849-1ff22f750d7e.png">

**Project -**
<img width="1215" alt="Screen Shot 2019-08-21 at 11 53 07 AM" src="https://user-images.githubusercontent.com/26032343/63460842-30452400-c40c-11e9-9e7e-4091b699f728.png">

**Namespace -** 
<img width="967" alt="Screen Shot 2019-08-21 at 11 52 39 AM" src="https://user-images.githubusercontent.com/26032343/63460852-33401480-c40c-11e9-92de-a2d9578a1b3c.png">

**Actual Result:**
The above fields are editable. And clusters will fail to come up, when any labels/annotations are deleted. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master-head - Commit id: `85dedb19b`
- Installation option (single install/HA): single

**Comment by sowmyav27** [comment]
Verified on master-head.
Cloud provider setup - AWS cluster, has few labels which are editable.
Hence reopening the issue.
<img width="979" alt="Screen Shot 2019-09-04 at 8 53 31 AM" src="https://user-images.githubusercontent.com/26032343/64271736-b5dbd000-cef2-11e9-84c1-219cfcff9c5a.png">

**Comment by loganhz** [comment]
@sowmyav27 would you still like to see this label in node list page? Usually we will hide the read-only labels there as well.

**Comment by sowmyav27** [comment]
Verified on latest master-head
On a cloud provider AWS setup, the failure-domain labels are not available on the UI.
