### ISSUE TITLE
[UI] Add send resolved option to notifiers

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#22348]
UI ticket for https://github.com/rancher/rancher/issues/17962

`send_resolved` is a common configuration for all kinds of notifier type.
https://prometheus.io/docs/alerting/configuration

Add a boolean option in Notifier(all types) UI for it. It defaults to false.

For example:

[ ]  Send Resolved Alerts

**Comment by davidnuzik** [comment]
Reference https://github.com/rancher/rancher/issues/17962#issuecomment-527657446 I too am awaiting information based on Jack's comment/question.

**Comment by davidnuzik** [comment]
Ensure options take by viewing details of the alerting app.
Ensure the send resolved works for each notifier by ensuring the setting took.

functional testing already complete in the backend issue.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/4/19) `f867995f`

When POSTing to the `/v3/notifier` endpoint (via the UI add a notifier) we now always send `sendResolved: true` boolean for ALL of the notifiers in the request body.

I also validated that we see "send_resolved: true" when checking the cluster-alerting index.html (check Status page for each notifier type)

Last, I did a quick sanity check to ensure I get the resolved message once my alert is resolved (this was already tested in the backend issue). This too is working fine for me.
I also ensured that if I do NOT opt-in to the send_resolved option in the UI when creating a notifier that I do NOT get the resolved messages (this is the default option, we don't send_resolved by default).

Note, there is some caching of alerts and so there can be a delay. If you resolve your alert (in my case make node CPU reservation go under 75%) you may get several alerts before is resolved. This is expected.

![image](https://user-images.githubusercontent.com/45179589/64295602-57304980-cf26-11e9-9485-1d82b1a79b59.png)
