### ISSUE TITLE
Upgrade k8s 1.12.x to the latest for 1.6

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22340]
We have to upgrade Kubernetes to the latest version of 1.12.x for Rancher v1.6

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.29-rc1`

**Comment by soumyalj** [comment]
Tested on rancher/server:v1.6.29-rc2 with K8s 1.12.10-racher1-1
The following OS and Docker versions have been validated. 
1. Docker 1.13.x RHEL 7.5
2. Docker 17.03 Ubuntu 14.04
3. Docker 17.03 Ubuntu 16.04
4. Docker 18.06 RancherOS 1.5.4
