### ISSUE TITLE
[forwardport] Global Rolebindings can become stuck on cluster removal 

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#22341]
Fowardport https://github.com/rancher/rancher/issues/22281

**Comment by jiaqiluo** [comment]
The bug fix is validated in master-head e4019a564
Steps:
- as the default admin, enable Github Auth
- open another browser to log in as Github user `rancherdev`
- as the default admin, go to the `Users` page to change rancherdev's role to `Administrator`
- change rancherdev's role back to `Standard User`  -> the change takes effect
- change rancherdev's role to `Administrator` again
- as rancherdev, create a cluster
- wait for the cluster to be active
- as the default admin, delete the cluster
- as the default admin, go to the `Users` page to change rancherdev's role to `custom` and selected some permissions
- save and refresh the page 

Result:

- rancherdev's role is changed successfully
