### ISSUE TITLE
rancher pipeline not trigger when push 

### ISSUE THREAD

**Issue by damozhiying** [rancher/rancher#22350]
``
stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven/maven:3.6-jdk-8
      shellScript: mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xstore/pipeline-test:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.30.88:7080
      imagePullSecrets: 
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"  
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml

``

![image](https://user-images.githubusercontent.com/10277950/63492914-0152af00-c4ed-11e9-9be8-152b490e8949.png)

how to config the auth with harbor?

**Comment by damozhiying** [comment]
pipeline  push docker images to harbor, how to config the auth info

**Comment by gitlawr** [comment]
Go to the Project-Resources-Registries page and add credentials there

**Comment by damozhiying** [comment]
@gitlawr thanks a lot

![image](https://user-images.githubusercontent.com/10277950/63499137-d15dd880-c4f9-11e9-9282-483089e3dc35.png)

![image](https://user-images.githubusercontent.com/10277950/63499226-0702c180-c4fa-11e9-8c0e-b6188fba78cd.png)

if base docker images from private register,
how to config the pipeline

**Comment by damozhiying** [comment]
i know add ip:port  is success,such as 
![image](https://user-images.githubusercontent.com/10277950/63499475-81334600-c4fa-11e9-8669-7bfbe0d62394.png)
now,i don't want to add ip:port,i had add private register
![image](https://user-images.githubusercontent.com/10277950/63499542-9f00ab00-c4fa-11e9-8f73-617fe8c678ef.png)

**Comment by damozhiying** [comment]
@gitlawr thanks a lot
gitlab is private, not trigger when push ,i see there not webhook,    is need to manual add webhook?

**Comment by damozhiying** [comment]
![image](https://user-images.githubusercontent.com/10277950/63504979-42ef5400-c505-11e9-9c3c-ab6343b6a64f.png)
![image](https://user-images.githubusercontent.com/10277950/63505072-6b774e00-c505-11e9-8a9c-4e7a28237845.png)

**Comment by damozhiying** [comment]
![image](https://user-images.githubusercontent.com/10277950/63505624-6e267300-c506-11e9-97d6-ba8da21b165c.png)

**Comment by damozhiying** [comment]
@gitlawr can you give some tip?

**Comment by gitlawr** [comment]
Did you enable the repo before setting `Allow requests to the local network from hooks and services`? In that case, you need to re-enable the repo on Rancher side

**Comment by damozhiying** [comment]
![image](https://user-images.githubusercontent.com/10277950/63565955-c3fa2a00-c59d-11e9-851c-71a51d11af4f.png)

re-enable the repo

![image](https://user-images.githubusercontent.com/10277950/63565973-d70cfa00-c59d-11e9-8512-8536cfbb0b76.png)

![image](https://user-images.githubusercontent.com/10277950/63566014-f73cb900-c59d-11e9-9674-18151cd88d9e.png)

event not triger build?

i see there is not webhook auto generate

![image](https://user-images.githubusercontent.com/10277950/63566045-1d625900-c59e-11e9-82b9-a7ced4560d9e.png)

**Comment by damozhiying** [comment]
gitlab deploy in rancher, access by ingress

**Comment by damozhiying** [comment]
@gitlawr now i want to  add webhook manual,what's the rancher webhook notification endpoint or url

**Comment by gitlawr** [comment]
Do you see any related error in Rancher server logs when you do enable/re-enable

**Comment by damozhiying** [comment]
![image](https://user-images.githubusercontent.com/10277950/63667655-37eb3b00-c807-11e9-9fdd-00e6901b4866.png)
![image](https://user-images.githubusercontent.com/10277950/63667715-649f5280-c807-11e9-8c0f-4d3463fe0dfc.png)

@gitlawr i see the url is right

**Comment by damozhiying** [comment]
manual run above  pipeline success

**Comment by damozhiying** [comment]
![image](https://user-images.githubusercontent.com/10277950/63668069-91a03500-c808-11e9-9a95-c3031b6b4de9.png)

**Comment by damozhiying** [comment]
there is no pod with the ip 10.43.239.108 all namspaces,  where is the endpoint 10.43.239.108:8080

**Comment by gitlawr** [comment]
What is the `server-url` in Rancher settings?

**Comment by damozhiying** [comment]
@gitlawr 
![image](https://user-images.githubusercontent.com/10277950/63669114-bd70ea00-c80b-11e9-9f17-f82fc190ecd2.png)
manual run success
![image](https://user-images.githubusercontent.com/10277950/63669153-e1ccc680-c80b-11e9-974a-05fc9fa1251c.png)

rancher logs
![image](https://user-images.githubusercontent.com/10277950/63669169-f0b37900-c80b-11e9-836e-390891ad231d.png)

**Comment by damozhiying** [comment]
@gitlawr thank y a a lot
![image](https://user-images.githubusercontent.com/10277950/63669678-3f154780-c80d-11e9-9072-c1a002c6f9d0.png)
rancher logs show error,but there is webhook exist in gitlab, because i add hostalias gitlab in k8s

**Comment by damozhiying** [comment]
@gitlawr thanks a lot ,provide support all the time,y are good   ,i think my question is classical, should be write into pipeline faq

**Comment by damozhiying** [comment]
now ,pipeline auto triger,there is no problem
