### ISSUE TITLE
etcd s3 backups to buckets in AWS ap-east-1 region fail

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#22355]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a single container Rancher instance and launch a custom cluster with a single all role node. Did this in Digital Ocean using https://github.com/superseb/tf-do-rancher2/
2. Enable the Hong Kong ap-east-1 region on your AWS account.
3. Create two test buckets, one in Hong Kong (ap-east-1) and one in AWS Japan (ap-northeast-1).
4. Configure etcd s3 backups for the custom cluster to the bucket in ap-northeast-1, click 'Snapshot Now' and observe the backup successfully pushed to the S3 bucket.
5. Change the etcd s3 backups for the custom cluster to the bucket in ap-east-1, click 'Snapshot Now' and observe the backup is not pushed to S3.
6. Run `kubectl get etcdbackups -o yaml --all-namespaces` and observe the backup to ap-east-1 failed with message of the following format, where `as-rancher-test` was the bucket name, which does in fact exist:
```
message: "Failed to take one-time snapshot, exit code [1]: time=\"2019-08-22T10:25:38Z\"
        level=fatal msg=\"failed to set s3 server: failed to check s3 bucket:as-rancher-test,
        err:400 Bad Request\" \n"
```
7. Test pushing a file to the ap-east-1 bucket using the AWS CLI (https://www.systutorials.com/239665/uploading-large-files-amazon-s3-aws-cli/) from the Rancher server and see that this completes successfully, confirming the bucket is reachable from the DO VMs.

**Environment information**
- Rancher v2.2.8

**Comment by superseb** [comment]
This is solved by a vendor update of minio-go: https://github.com/minio/minio-go/pull/1105

**Comment by soumyalj** [comment]
Tested with master-head build from Sep 11. 
Created S3 bucket in Asia pacific Hongkong region ```ap-east-1``` region. 
Used the S3 bucket when creating clusters with S3 configuration. Cluster creation was successful and snapshot was successfully saved in the bucket in region ```ap-east-1```

The following region and endpoint combinations were tested in Rancher UI : 

Region       |    Endpoint
...................................................
ap-east-1  |   s3.amazonaws.com
Empty        |   s3.amazonaws.com
ap-east-1  |   s3-ap-east-1.amazonaws.com
Empty      | s3-ap-east-1.amazonaws.com
