### ISSUE TITLE
Unable to edit workload scheduling rule in UI

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#22351]
**Rancher version**
master 8/22

**Steps to reproduce (least amount of steps as possible):**
1. Go to the `Default` project, click Deploy
2. input `ngx` as the name, `nginx` as the image. Click Launch.
3. Edit the `ngx` workload, click `Node Scheduling`,
4. Add a `a=b` rule to the require-all session. Click Save.

**Result:**
The rule is not saved.
See JS errors in the console.
![image](https://user-images.githubusercontent.com/5697937/63493600-8c807480-c4ee-11e9-9eb9-9da4bf255355.png)

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/28/2019)

I was able to use all the operators individually and save the rules without errors in a workload.
Also tested combination of operators, all were saved without JS errors.

In both cases the rules were applied to the workload pods.
