### ISSUE TITLE
Fix rancher-images to work with metadata feature

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#22364]
When we introduce new k8s version support in existing rancher server setup, we would expect rke-metadata-url to be point to a github server that is accessible to the air gap setup and is kept in sync with rancher's default rke-metadata-url .
With this in place , k8s version support changes will be reflected in air gapped setups as expected. But we will still not have a way to get an updated rancher-images.txt with the supporting system images needed.
We should have a V3 settings exposed that will carry this information and get re-evaluated everytime changes done to kontainer metatdata.

For validating this issue , following scenarios need to be validated in air gap setup: 

- Validate that we are able to deploy all supported K8s versions in the release successfully after the images from rancher-images.txt gets uploaded to the private registry used by airgap setup.
- Introduce new k8s version support in existing rancher server setup

**Comment by jiaqiluo** [comment]
The following tests are done in the Rancher:master-head testing image:
- run Rancher container in air-gapped env
- create a custom cluster with k8s v1.15.2
- in the air-gapped setup, change the metadata url to a new git repo, 
- refresh to get the new data
- see the new k8s version (v.1.15.3) in the droplist 
- create a new cluster with k8s v.1.15.3
- upgrade cluster from v1.15.2 -> v1.15.3
- create clusters with existing k8s versions v1.13.10 and v1.14.6
