### ISSUE TITLE
UI - Standard User see himself role as custom user 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#22365]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug 

**Steps to reproduce (least amount of steps as possible):**

- as the default admin, enable Github Auth
- open another browser to log in as Github user `rancherdev`
- as the default admin, go to the `Users` page to change rancherdev’s role to `Administrator`
- change rancherdev’s role back to `Standard User` 

**Result:**
- in the admin's view, `rancherdev`'s role is `standard user`
- in `rancherdev`'s view, his role is `custom`

<img width="1904" alt="Screen Shot 2019-08-22 at 11 33 28 AM" src="https://user-images.githubusercontent.com/6218999/63550345-4d025a00-c4e7-11e9-8368-6624c18061f8.png">

**Other details that may be helpful:**

Rancher:master-head e4019a564

<img width="748" alt="Screen Shot 2019-08-22 at 2 16 47 PM" src="https://user-images.githubusercontent.com/6218999/63550432-82a74300-c4e7-11e9-8303-1577f400c418.png">

**Comment by jiaqiluo** [comment]
the same as this one https://github.com/rancher/rancher/issues/15854

**Comment by davidnuzik** [comment]
Dynamic rbac required https://github.com/rancher/rancher/issues/15107

**Comment by cjellick** [comment]
Hmph. This is a weird one. I don't think dynamic rbac is the root cause...maybe contributing though

**Comment by cjellick** [comment]
based on the bug we see is a dupe, this has been around since v2.1. im going to bump out of v2.3.0

**Comment by davidnuzik** [comment]
@cjellick I claim it to be related to dynamic RBAC based on the issue Jack referenced (and Logan's comment in the issue: https://github.com/rancher/rancher/issues/15854#issuecomment-432932417)
