### ISSUE TITLE
Kubernetes version is not preserved when cluster is restored from a snapshots taken before kubernetes version is upgraded.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#22368]
Currently kubernetes version is not preserved when cluster is restored from a snapshots taken before kubernetes version is upgraded.

Consider the following scenario:
Create a cluster with K8s version say 1.13.
Deploy few workloads.
Take a snapshot , say S1.
Deploy few more workloads.
Upgrade K8s version on the cluster to say 1.14.
Restore from snapshot S1 which was taken when K8s version was in 1.13.
K8s version continue to be in 1.14.

Expected Behavior:
We should be able to get to K8s version 1.13 in this case , the k8s version that was present on the cluster when the snapshot was taken.

**Comment by alena1108** [comment]
As we don't support rolling back k8s version for RKE clusters, we should prevent this from happening during restoration from the snapshot. Can be achieved via:

* Store k8s version on the snapshot
* Do an api validation when restoring

**Comment by dnoland1** [comment]
This looks closely related to an RFE I filed few days back. See https://github.com/rancher/rancher/issues/22232

**Comment by deniseschannon** [comment]
In 2.4, we introduced being able to restoreand specify/change k8s version on restore. https://github.com/rancher/rancher/issues/22232
