### ISSUE TITLE
Sensitive data on node templates should be controlled by secrets 

### ISSUE THREAD

**Issue by alkimake** [rancher/rancher#22378]
**What kind of request is this:**
enhancement / security

**Steps to reproduce:**

- Create a node-template one with of the following drivers;
  - aliyunecs
  - amazonec2
  - azure
  - digitalocean
  - exoscale
  - openstack
  - otc
  - packet
- Add sensitive data eg. `privateKeyFile` for openstack

**Result:**
When editing node-template or getting CRD for node-templates, these information can be retrieved easily. We believe these informations should be handled as `passwords` since they are sensitive informations.

For example; openstack `privateKeyFile` should not be available to retreive after registered on node-template. Currently it is visible on node-templates custom resource definitions. 

**Proposal**:

Aliases of sensitive parameters of node drivers can be saved as kubernetes `secret` resource. And record the `secret` name on CRD. Therefor these information can not be achieved from CRD by other users.

**UI**
 Also it is possible to make it hidden in node-templates ui. 
- On Creation: of node-template rancher will write these parameter aliases to secrets
- On Edit:
   - Input will be empty (like password)
   - If the input is empty, secret will be untouched on save
   - If input is changed secret will be updated
- On Cluster/Node creation: Rancher will update/create files in `jail` environment from `secret` 

**Environment information**
- Rancher version: 2.2.5
- Installation option (single install/HA): both

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Any
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Any
- Kubernetes version (use `kubectl version`): 1.13+

**Comment by kinarashah** [comment]
@alkimake This is currently getting fixed for 2.3, all sensitive fields would be marked as password.

**Comment by alkimake** [comment]
@kinarashah i have checked `2.3.0-alpha7` now. On UI side looks like it is fixed and when i want to edit, i can not see sensitive fields are being filled.

But i can still get them by getting `nodetemplates.management.cattle.io` resource. These data should be saved to k8s secrets i believe.

**Comment by tfiduccia** [comment]
@davidnuzik @izaac - We should validate for the UI side of things.  Then send to Sangeetha for backend.  @kinarashah believes this should be fixed for 2.3

**Comment by davidnuzik** [comment]
@izaac would you mind taking a look at this one? Intent is to doubly verify what @alkimake reported in the UI (UI should indeed be fixed). Then once verified we can discuss with Sangeetha as far as assignment to fix the backend issue.

**Comment by izaac** [comment]
@davidnuzik sure I'll take a look at this issue.

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (09/04/2019)

I went through the drivers linode, ec2, openstack, DigitalOcean. I can see the behavior is as described by @alkimake  [here.](https://github.com/rancher/rancher/issues/22378#issuecomment-525995227).

The only thing I've noticed was with Linode. In the Authentication section of the node template creation there's a root password field this field is returned by the API when editing the cluster as `string` type.

However the field type is `password` you can only see the stars in the input but if you go to View API you can see `rootPass`'s value in the body:

![Screen Shot 2019-09-04 at 2 46 34 PM](https://user-images.githubusercontent.com/27659/64294702-5696b380-cf24-11e9-84e5-73ab3090aca5.png)

@tfiduccia @kinarashah @alkimake

**Comment by izaac** [comment]
By the way this is the BE issue:

https://github.com/rancherlabs/rancher-security/issues/177

**Comment by izaac** [comment]
Rancher version: `master-head` (v2.3) (09/04/2019)

I checked a few node drivers and created node templates for them. I only found an issue and created a separate ticket for tracking.

UI looks good, and the expected sensitive information is being keep secret as expected after creating the templates.

**Comment by alkimake** [comment]
Can we get the Back-end issue number ?

**Comment by sangeethah** [comment]
@alkimake Issue with being able to get  sensitive fields from `nodetemplates.management.cattle.io` (by accessing the management plane) is still present. We will use this ticket for tracking it.

**Comment by cbron** [comment]
This was handled in recently releases.
