### ISSUE TITLE
Improve log message when jailer script fails to complete before timeout

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#22379]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

If the jailer script fails to complete within the configured timeout of 10 seconds the Rancher log will show a message of the following format (https://github.com/rancher/rancher/blob/v2.2.8/pkg/jailer/jailer.go#L55):

`[FATAL] error running the jail command: : signal: killed`

The request is to add a specific log message indicating the script reached the timeout.

**Environment information**
- Rancher v2.2.8

**Comment by fengzixu** [comment]
Same problem

**Comment by fengzixu** [comment]
Are the 10 seconds sufficient for processing jailer script? @axeal

**Comment by paulsmithuk** [comment]
+1

Our AV is causing the script to timeout...personally, I'd rather give it a little more time to complete, rather than having a nicer fail message!

**Comment by sangeethah** [comment]
Tested with `2.3-head`  
Following are the error message seen when  jailer script fails to complete before timeout:

```2019/10/11 23:48:26 [ERROR] NodeController c-ff8nn/m-dmf2n [node-controller] failed with : node create jail error: error running the jail command: timed out waiting for the script to complete: signal: killed```

<img width="1048" alt="Screen Shot 2019-10-11 at 4 48 36 PM" src="https://user-images.githubusercontent.com/4266958/66690795-41a9f000-ec47-11e9-90ed-02eb2128ca3d.png">
