### ISSUE TITLE
[UI] Add timeout and wait fields for Apps and Multi-cluster Apps

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#22373]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
go to create an app or mcapp

**Result:**
there is no way to configure the new timeout/wait fields for apps and mcapps.

**Other details that may be helpful:**
Labels should make it clear these are for helm. I recommend "helm wait" and "helm timeout"

Backend issue:
https://github.com/rancher/rancher/issues/17471

**Comment by westlywright** [comment]
@cjellick @rmweir I was talking with @vincent99 about this and he brought up a good question. Should `wait` be enabled by default? Is there a downside to enabling `wait` by default?

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by izaac** [comment]
Validated with Rancher `2.4 master-head (11/26/2019) 781cd0fdc`
**Wait** is disabled by default.

### Use cases covered for Apps and Multi Cluster Apps.

- Wait true and 100 seconds
```bash
[kube] 2019/11/26 17:09:58 beginning wait for 5 resources with timeout of 1m40s
[kube] 2019/11/26 17:10:00 Deployment is not ready: registry-test-p-gqkks/registry-test-p-gqkks-docker-registry
…
LAST DEPLOYED: Tue Nov 26 17:09:57 2019
NAMESPACE: registry-test-p-gqkks
STATUS: DEPLOYED
```

- Wait true and timeout with low value
```bash
[kube] 2019/11/26 18:17:02 beginning wait for 4 resources with timeout of 1s
[tiller] 2019/11/26 18:17:03 warning: Release "test2-p-gqkks" failed: timed out waiting for the condition
[storage] 2019/11/26 18:17:03 updating release "test2-p-gqkks.v1"
[tiller] 2019/11/26 18:17:03 failed install perform step: release test2-p-gqkks failed: timed out waiting for the condition
2019/11/26 18:17:03 [ERROR] AppController p-gqkks/test2-p-gqkks [helm-controller] failed with : failed to install app test2-p-gqkks. Error: release test2-p-gqkks failed: timed out waiting for the condition
```
- Wait false just don’t set any timeout value and keeps going until the app is deployed or an error occurs


Closing.
