### ISSUE TITLE
[UI] Cluster Templates - Use disable/enable actions on ClusterTemplateRevision object

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#22374]
With this change https://github.com/rancher/rancher/issues/22371, API has added two new actions on clusterTemplateRevision: "enable" and "disable"

So UI should call these APIs for enabling disabling the clusterTemplateRevision instead of the current PUT request.

new APIs:
To disable: /clusterTemplateRevisions/<revision_Id>?action=disable

To enable: /clusterTemplateRevisions/<revision_Id>?action=enable

**Comment by davidnuzik** [comment]
This has been tested as a part of https://github.com/rancher/rancher/issues/21698

The actions work without any issues. The UI appropriately updates the state accordingly. You are able to enable/disable any CTR regardless if it is in use or not.

When a CTR is disabled, you cannot utilize it to create a new cluster, but any clusters that were already created with it work fine. If you edit a cluster with a disabled CTR you just need to supply another CTR to use instead. This works without any issues based on my testing.
