### ISSUE TITLE
RFE: Allow changing Rancher Server URL

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#22377]
Issue:
Currently, this is not supported as published in the docs:
https://rancher.com/docs/rancher/v2.x/en/admin-settings/

> After you set the Rancher Server URL, we do not support updating it. Set the URL with extreme care.

RFE:
Add support for updating the Rancher Server URL

Rancher version:
v2.2.x

**Comment by superseb** [comment]
This is covered in https://github.com/rancher/rancher/issues/14731, either should be merged/close.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/14731
