### ISSUE TITLE
Disable windows support for k8s 1.14

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#22375]
Per Will, we would like to only support k8s 1.15 and above for Windows cluster

**Comment by loganhz** [comment]
Need to verify the upgrade case for Windows cluster from k8s 1.14 to k8s 1.15 before disable it

**Comment by davidnuzik** [comment]
May I request to know the reason we want to disable Windows Support for k8s 1.14.x? or could you enter this in the issue description?

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/29/2019)

Windows version looks enabled for kubernetes version 1.15.x and up in latest master.
If I pick Kubernetes version 1.14.x or below Windows support is always disabled regardless of Network provider. ✅
