### ISSUE TITLE
Implement capability reflecting Taint support in RKE clusters

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22387]
Prior to v2.3 CNI addons in Rancher clusters didn't have tolerations allowing them to be started on  tainted nodes. In v2.3 tolerations were added to the system addons templates, and should get applied on the very first rke reconcile for the cluster for every k8s version. The thing that is left to implement is an indication that the tolerations are applied, hence the taints are supported. We should:

* Add TaintSupport capability (type *bool)
* The value should be left as nil for the hosted k8s providers
* The value should be set to true at the end of the very first rke reconcile (provisioner.go). Once set to true, the value will never be averted again.

**Comment by sowmyav27** [comment]
Verified on an upgrade from `2.2.8` to `master-head`.

**Cluster specs:**
```
2 custom clusters - minimum - 1etcd, 1 control plane and 1 worker node
2 rke DO clusters -  minimum - 1etcd, 1 control plane and 1 worker node with individual node pools
```
**Steps:**

- Have the cluster deployed in `2.2.8`. 
- Upgrade rancher to `master-head`.
- The clusters do not have `taintSupport": true` flag.

**Scenarios verified:**

**On rancher upgrade -** 
- In Edit custom cluster --> register page --> Add Taints is available
- In Custom cluster --> Edit node --> No Taints available.
- In rke cluster - Edit node does NOT have taints
- In rke cluster - Edit cluster --> Node pool has taints

- Edit node template -- has taints. Taints can be added.

- Add a taint on the node template and scale up the worker node. `taintSupport": true` flag is seen set on the cluster after it comes up `Active`. 

- etcd and control plane nodes, do not show existing kubernetes taints -- logged issue --https://github.com/rancher/rancher/issues/22565

- new cluster created in master-head has the `taintSupport": true` flag set and the nodes --> Edit node --> Have taints available, user can add taints.
