### ISSUE TITLE
Adding new windows node in 2.3.0-alpha7 doesn't work. 

### ISSUE THREAD

**Issue by cprivite** [rancher/rancher#22385]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Run:
`PowerShell -Sta -NoLogo -NonInteractive -Command "& {docker run --rm -v C:/:C:/host rancher/rancher-agent:v2.3.0-alpha7 -server https://tst-rancher.epic.com -token XXXX -caChecksum XXXX; Out-String -InputObject $? | Select-String -AllMatches -Pattern 'True' | ForEach-Object {& c:/etc/rancher/run.ps1;}}"`

**Result:**
Seems to work for a while but then endless spits out the following:
`WARN[2685379] Error while getting agent config: invalid response 500: Failed to construct node config. Error: failed to get windows system images v1.15.3-rancher2-1: rkek8swindowssystemimages.management.cattle.io "wv1.15.3-rancher2-1" not found`

**Other details that may be helpful:**
Windows Server 2019 with latest patches. Rancher 2.3.0-alpha7, kubernetes version is set to 1.15.3-rancher2-1 in the cluster options.
After upgrading to 2.3.0-alpha7 from -alpha5 I lost the button to say a host was a windows host, so if you added some weird boundaries to prevent us from trying to install this version of kubernetes on windows, they only sort of worked, resulting in a cluster that's upgraded to 1.15.-rancer2-1 and a windows node that can no longer talk to it. I did try cleaning the node so that's probably not helping either. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0-alpha7
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): 1.15.3-rancher2-1

```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
C:\Users\cprivite>docker version
Client: Docker Engine - Enterprise
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f660560464
 Built:             07/25/2019 20:59:52
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       f660560464
  Built:            07/25/2019 20:57:41
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by davidnuzik** [comment]
This should be fixed in latest master-head image; you could use this instead to try it out. I don't think the fix made it in to alpha7

**Comment by davidnuzik** [comment]
Also, there is a bug with 1.15 k8s try 1.14 with windows. Reference: https://github.com/rancher/rancher/issues/21577
This _should_ be fixed too in master-head but has not been tested yet (as of the time I'm writing this).

**Comment by cprivite** [comment]
Ok thanks. I'll have to try the master route given you can't downgrade k8s.
