### ISSUE TITLE
[Enhancement] Project level - App UI optimization

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#22386]
Currently the App UI in project level only shows the deployed applications with big rectangles. With normal screen resolution, you will only be able to see two apps in a single line. If there are many apps deployed, it will be hard to manage them and find a specific app. Some enhancement ideas include:

1. Support different view switch between something like large/small icons. Maybe something similar with view switch in finder or windows explorer.
2. Support label/tag in app deployment and support categary view based on label/tag.
3. Support search function.
4. Others. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `master-head` UI: `v2.3.3` |
|Route|`apps-tab.index`|

**Comment by pengjiang80** [comment]
@loganhz

**Comment by tfiduccia** [comment]
@pengjiang80 - we updated the rancher catalog pages for v2.3.0 to address some of these issues.

1.  The new rectangles are actually smaller than the old ones and allow for more apps to be shown.
2.  We added a collapse to each library so you only view the one/ones you want.
3.  We still have a "Search" box so you don't actually have to scroll through the apps at all.  You can just type in what you are looking for.
4.  We also still have the Categories drop-down that will enable you to filter your search.

Based on this you should be able to find any app you would like.
![image](https://user-images.githubusercontent.com/11514927/66512884-bede3500-ea8e-11e9-932b-2bbc64277dd9.png)
