### ISSUE TITLE
Service selectors

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2239]
- Ability to create a selector link that will automatically link services based on labels. 
- Ability to create a selector so that standalone containers can join the service DNS. As standalone containers, none of the service actions will affect the container. (Delete, scale, healthcheck, etc)

Selectors get represented in docker-compose.yml as labels.
```
io.rancher.service.selector.container: foo=bar
io.rancher.service.selector.link: foo in (bar)
```

**Comment by alena1108** [comment]
Supported selectors format:

```
key in (value1, value2)
key notin (value1, value2)
key
key = value
key != value
and any combination of them can be specified in coma separated way:
key != value, key in (value1, value2), key = value
```

**Comment by sangeethah** [comment]
Tested Service selector feature for both selectorContainer and selectorLink with build from master on Oct 8. Issues found when testing this feature are tracked in different issues - #2278 , #2276 , #2273 ,#2271 ,  #2270 , #2269 .
