### ISSUE TITLE
Actions on containers that are on a deactivated host hang forever

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#224]
Version - V0.11.1

Steps to reproduce the problem:
Have few containers started on a host.
Deactivate the host.

Try to Start/Stop/Restart  containers that are on this host.

UI shows that the operation is in progress forever.

The state of the containers are stuck in "Starting"/"Stopping".

Expected Behavior:
We should not allow for these options to be presented to the user. 
If they are presented to the user, API should error out gracefully stating that these operations are not allowed because of the state in which the host is in.
![screen shot 2015-03-17 at 4 03 35 pm](https://cloud.githubusercontent.com/assets/4266958/6699428/350c3e5e-ccbf-11e4-9d6c-b7e64ccd84c5.png)

**Comment by vincent99** [comment]
Inactive means only that new containers are not scheduled there.  Actions should still work.  They seem fine to me so I think this was addressed a while ago.

**Comment by sangeethah** [comment]
Tested with rancher-server vesrion - v0.52.0-rc3

Able to Start/Stop/Restart containers on host that are in "inactive" state.
