### ISSUE TITLE
Bulk deactivate of node drivers is not working

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#22404]
Running rancher locally on dev machine, the node drivers are not available which causes the node drivers to stay in "Downloading" state. If I select all 4 drivers and click "Deactivate" they don't get deactivated, have to do that by selecting one by one.

**Comment by stefanvangastel** [comment]
This issue persists in Rancher 2.3.4. Seems like the confirmation modal is not triggered, bypassing confirmation with CTRL  key does work.

This issue also applies to cluster drivers.

Bulk deactivation does nothing:
![deactivate_multiple_not_working](https://user-images.githubusercontent.com/2473490/72606448-e6129100-391e-11ea-89b4-e3aa74c91e74.gif)

Bypassing with CTRL:
![deactivate_multiple_not_working_ctrl](https://user-images.githubusercontent.com/2473490/72606458-eca10880-391e-11ea-9102-cca2dd4357e2.gif)

**Comment by slickwarren** [comment]
Reproducible in v2.5.8:
single driver deactivation -- alerts user with popup, deactivates node
2 driver deactivation -- same behavior as above
3 or more driver deactivation -- alerts user with popup for last checked node driver, deactivates that driver but none of the other selected options
