### ISSUE TITLE
Rancher Launched Cluster's Notification is Stuck

### ISSUE THREAD

**Issue by dabidpaolo** [rancher/rancher#22409]
*Describe your issue here*
Cluster status is stuck in `Provisioning` with the status:
`Exit status 1, Error from server (NotFound): error when deleting "management-statefile_path_redacted": daemonsets.extensions "kube-api-auth" not found`

This happened after disabling `Authorized Cluster Endpoint` on the cluster.

Reverting it back could have caused the error and it never went away since then.

So far, I have not experienced any issue with my cluster in terms of deployment and queries. Can this be a bug on the UI? 

---
| Useful | Info |
|:-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`authenticated.cluster.monitoring.index`|

**Comment by dabidpaolo** [comment]
Here's the screenshot 
![image](https://user-images.githubusercontent.com/9943205/63658963-3c9cf880-c7e1-11e9-8294-72f03d65895c.png)

**Comment by dabidpaolo** [comment]
This is fixed.
1. Disabled `Authorized Cluster Endpoint`
2. Re-enabled `Authorized Cluster Endpoint`

**Comment by tfiduccia** [comment]
Are we not clearing an error during a change event.  Or is the change event not being sent?

**Comment by davidnuzik** [comment]
This doesn't happen in the v2.3 upcoming release (master-head image). We will try to check v2.2.8 when we are able.
