### ISSUE TITLE
Cannot create multiple hosts from same AMI

### ISSUE THREAD

**Issue by ccirello** [rancher/rancher#2240]
I cannot create more than one host using custom AMI in Rancher.

I have deleted /var/lib/cloud and /etc/ssh/ssh_host* in order to force different fingerprint among different hosts. 

Even if I do it manually, it conflicts if both machines come from customized AMI.

**Comment by vincent99** [comment]
If the host was added to Rancher before creating the AMI, you'll need to wipe out `/var/lib/rancher/state` too.

**Comment by ccirello** [comment]
it worked.
