### ISSUE TITLE
[Windows] Optimize the drone build of Windows rke-tools

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#22407]
We need to increase the speed of Windows rke-tools build for Drone. For now, it took 20 mins for Windows build to complete.

**Comment by loganhz** [comment]
Before it takes around 20mins for building rke-tools. https://drone-publish.rancher.io/rancher/rke-tools/55

Now it is 1 min https://drone-publish.rancher.io/rancher/rke-tools/60
