### ISSUE TITLE
[Windows] DNS resolution and ping on windows workloads do not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22400]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Setup:**
```
Windows AWS node: `Windows_Server-1903-English-Core-Base-2019.08.16`
Linux Node: `18.04 Ubuntu LTS`
Linux node docker - 19.03, Windows node docker - 19.03, k8s version - 1.15.3
```
**Steps:**
1. Launch a custom cluster 
2. Register 1 etcd and control plane linux node
3. Register 1 worker linux node
4. Register 2 worker windows node.
5. The cluster will come up active.
6. Deploy windows workloads

**Expected Result:**
User should be able to do `curl <workload-2>` on workload-1. User should also be able to `curl <service discovery>`

**Actual Result:**
It is seen to work intermittently. It does NOT work always. 

User is NOT able to do `curl <workload-2>` on workload-1. User is NOT able to do `curl <service discovery>`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest
- Installation option (single install/HA): single

**Comment by loganhz** [comment]
If you hit some weird issue in master-head for Windows node, please try to delete the windows cattle agent pod in system project. It should workaround it for now. We will fix it soon.

**Comment by sowmyav27** [comment]
Verified with latest master-head - commit id: `d7b425da7`
**Setup:**
```
Windows AWS node: `Windows_Server-1903-English-Core-Base-2019.08.16`
Linux Node: `18.04 Ubuntu LTS`
Linux node docker - 19.03, Windows node docker - 19.03, k8s version - 1.15.3
```
**Steps:**
- Launch a custom cluster
- Register 1 etcd, control plane and worker linux node
- Register 2 worker windows node.
- The cluster will come up active.
- Deploy windows workloads
- User is able to do curl <workload-2> on workload-1. 
- User is also be able to curl <service discovery>
- Curl <workload>.<namespace>.svc.cluster.local works - across different namespace workloads.
