### ISSUE TITLE
kube-proxy: --hostname-override in AWS Cloud Provider

### ISSUE THREAD

**Issue by stokowski** [rancher/rancher#22416]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Add Cluster - Amazon EC2 Provider + Amazon Cloud Provider
2. Add proper tags for resources in AWS (subnets/nodes etc)
3. Install custom ingress + NLB - https://kubernetes.github.io/ingress-nginx/deploy/#aws

**Result:**
NLB health-check fails

**Other details that may be helpful:**
This in Service:

externalTrafficPolicy: Local
type: LoadBalancer

When adding nodes to cluster we need to specify hostname prefixes. Then kube-proxy is setting that name in --hostname-override parameter on start on each node. That name is not recognized by kubernetes cluster, because hostnames/ip addresses are grabbed from AWS (check kubectl get nodes).

This is related to this issue: https://github.com/kubernetes/kubernetes/issues/80579

One of the solutions could be set this parameter to "" (empty) when creating ec2 nodes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider EC2 + Cloud provider: Amazon
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud t3.medium
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:07:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

gzrancher/rancher#11551

gz#12799

SURE-2489

**Comment by stokowski** [comment]
Adding to cluster conf:

```
  kubelet: 
    extra_args: 
      hostname-override: ""
  kubeproxy: 
    extra_args: 
      hostname-override: ""
```

also doesn't work.

**Comment by stokowski** [comment]
I was able to deal with this by creating cluster from custom nodes with cloud provider AWS enabled.

When setting up docker to register to cluster I've added those parameters:

`--internal-address $(curl http://169.254.169.254/latest/meta-data/local-ipv4) --node-name $(curl http://169.254.169.254/latest/meta-data/hostname)`

adding --node-name in my case is required because ec2.internal is added to hostname

(if you have public-address you need also add --public-address)

Now NLB and nodeIP services works as supposed with `externalTrafficPolicy: Local` in Service.

I hope that this will be added to Amazon EC2 Clusters creation.

**Comment by oded-dd** [comment]
This is a super important feature for us because ELB using `least outstanding requests routing algorithm` which cause data loss and NLB has limitations of 250 nodes per AZ. Once this feature/bug is resolved we can setup the NLB with `externalTrafficPolicy: Local` which will override the limitation of 250 nodes.

**Comment by bentastic27** [comment]
It seems to me that we just need a way to set the node's hostname to what's provided in EC2 metadata (ip-1-2-3-4.us-east-2.compute.internal for example). I tried using the userdata field to accomplish this, but it seems to always get overwritten by what's set in the node template.

I was able to determine this by creating a single node cluster then set extra_args.hostname-override to that hostname for kube-proxy. Once that is set this essentially works. This obviously doesn't scale past single node clusters though.

**Comment by atsai1220** [comment]
> It seems to me that we just need a way to set the node's hostname to what's provided in EC2 metadata (ip-1-2-3-4.us-east-2.compute.internal for example). I tried using the userdata field to accomplish this, but it seems to always get overwritten by what's set in the node template.
> 
> I was able to determine this by creating a single node cluster then set extra_args.hostname-override to that hostname for kube-proxy. Once that is set this essentially works. This obviously doesn't scale past single node clusters though.
> 
> gz#12799

Are there any updates on this?

**Comment by atsai1220** [comment]
As a side effect, we see this over and over again in `kubelet`.
```
W0104 03:10:20.631256 1539583 setters.go:198] replacing cloudprovider-reported hostname of ip-1-2-3-4.hello.world.io with overridden hostname of aws-worker3
```

**Comment by atsai1220** [comment]
This documentation seems incorrect. It says this but this is not true in practice.

> There is an exception for the AWS cloud provider, where the hostname_override field will be explicitly ignored.

https://rancher.com/docs/rke/latest/en/config-options/nodes/#overriding-the-hostname

**Comment by atsai1220** [comment]
I believe this is where the `kube-proxy` container's `--hostname-override` flag is configured. Where it really should be the output of
```
curl http://169.254.169.254/latest/meta-data/hostname
```


Reference: https://github.com/rancher/rke/blob/2159597d0f5e7e765d0bbb46e70ab2adb8980372/cluster/plan.go#L628


``` go
func (c *Cluster) BuildKubeProxyProcess(host *hosts.Host, serviceOptions v3.KubernetesServicesOptions) v3.Process {
	kubeproxy := &c.Services.Kubeproxy
	Command := c.getRKEToolsEntryPoint(host.OS(), "kube-proxy")
	CommandArgs := map[string]string{
		"cluster-cidr":      c.ClusterCIDR,
		"hostname-override": host.HostnameOverride,
		"kubeconfig":        pki.GetConfigPath(pki.KubeProxyCertName),
	}
```

**Comment by atsai1220** [comment]
From here
https://github.com/rancher/rke/blob/2159597d0f5e7e765d0bbb46e70ab2adb8980372/cmd/config.go#L68-L86
``` go
func getConfig(reader *bufio.Reader, text, def string) (string, error) {
	for {
		if def == "" {
			fmt.Printf("[+] %s [%s]: ", text, "none")
		} else {
			fmt.Printf("[+] %s [%s]: ", text, def)
		}
		input, err := reader.ReadString('\n')
		if err != nil {
			return "", err
		}
		input = strings.TrimSpace(input)

		if input != "" {
			return input, nil
		}
		return def, nil
	}
}
```
I'm unsure how this is generated.
``` go
func getHostConfig(reader *bufio.Reader, index int, clusterSSHKeyPath string) (*v3.RKEConfigNode, error) {
	host := v3.RKEConfigNode{}
...
...
...
	hostnameOverride, err := getConfig(reader, fmt.Sprintf("Override Hostname of host (%s)", address), "")
	if err != nil {
		return nil, err
	}
	host.HostnameOverride = hostnameOverride
```

**Comment by kinarashah** [comment]
https://github.com/rancher/rke-tools/pull/143

**Comment by kinarashah** [comment]
Fix now available to test with the latest k8s versions (which have rke-tools v0.1.79): 
- v1.23.4-rancher1-1 
- v1.22.6-rancher1-2, 
- v1.21.9-rancher1-2, 
- v1.19.16-rancher1-4 

Can be tested on v2.6-head (which vendors RKE v1.3.4-rc8 so has the RKE fix as well).

**Comment by rishabhmsra** [comment]
Validated this on rancher v2.6-head(99974f0)

**Validation steps followed:**

1. Created k8s `1.23.4-rancher1-1`, `1.22.7-rancher1-1`, `1.21.10-rancher1-1`, `1.19.16-rancher1-4` single node ec2 node driver cluster with in-tree cloud provided enabled.
2. SSH'ed into the cluster nodes. 
3. The `--hostname-override` arg is present in the `kube-proxy` process but **not** showing up on running `docker inspect kube-proxy`

**Result :**
> Note: I've removed the IPs from the below outputs

```
ps -ef | grep -i kube-proxy
root        9611    9588  0 06:08 ?        00:00:05 kube-proxy --bind-address=<> --cluster-cidr=<>/16 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml --v=2 --healthz-bind-address=127.0.0.1 --hostname-override=ip-<>.us-east-2.compute.internal
```
- **Not showing up in the container args :**
```
docker inspect kube-proxy

[
    {
        "Id": "4836bd72ee4d78e2c137e03fc78a989d21c5a60541ae4b4c6fe8763285ddb200",
        "Created": "2022-03-15T06:08:45.959944677Z",
        "Path": "/opt/rke-tools/entrypoint.sh",
        "Args": [
            "kube-proxy",
            "--bind-address=<>",
            "--cluster-cidr=<>/16",
            "--kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml",
            "--v=2",
            "--healthz-bind-address=127.0.0.1"
        ],
...
```

5. Also created custom ingress + NLB as mentioned [here](https://github.com/rancher/rancher/issues/22416#issue-485187046) on all downstream clusters. LoadBalancer service created for `ingress-nginx-controller` and on accessing the `http://<EXTERNAL-IP>/healthz` getting `HTTP/1.1 200 OK` response

**Comment by rishabhmsra** [comment]
Verified the logs of kube-proxy on all k8s clusters `1.23.4-rancher1-1`, `1.22.7-rancher1-1`, `1.21.10-rancher1-1`, `1.19.16-rancher1-4` and the `--hostname-override` is getting set correctly to the node name assigned by the cloud provided, hence closing the issue.
