### ISSUE TITLE
cadvisor is using 15-25% CPU with 54 containers

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2241]
Watching `top` on my Docker host, the `.cadvisor` process is using anywhere between 15 to 25% CPU all the time. I have 54 containers, not very active.

I notice that the [version of cadvisor](https://github.com/rancher/cattle/blob/master/resources/content/cattle-global.properties) used by rancher is quite old -- version 0.4.0 released September 2014. The latest version is 0.18.0, released September 2015. I don't know how much performance has improved, but it may be worth a look.

I'm guessing that rancher is also using the default sampling interval of 1 second. For demo purposes this is nice and shows a pretty graph, but for production an interval of 5 or 10 seconds would have less overhead. It should be possible to configure the sampling interval in the Rancher UI.

**Comment by deniseschannon** [comment]
We are actually using version v0.16.0 of cadvisor. The release number in the link you sent is the release for `rancher/cadvisor-package` repo.

https://github.com/rancher/cadvisor-package

@cloudnautique Can you look into the default sampling?

**Comment by gordontyler** [comment]
I read some comments in a cadvisor issue on this subject and apparently it's usage of `du` for measuring disk usage on aufs-backed containers seems to be the cause.

**Comment by gordontyler** [comment]
It looks like the underlying problem has been fixed in a newer version of cadvisor. It's a little hard to tell because they don't keep a particular accurate changelog, but judging from commit dates, I think it's in the v0.19.2 release.

**Comment by cloudnautique** [comment]
Thanks! Will take a look at the new release.

**Comment by Rucknar** [comment]
+1

**Comment by ibuildthecloud** [comment]
+1 @cloudnautique :smile:

**Comment by cloudnautique** [comment]
Testing out 0.19.3

**Comment by sangeethah** [comment]
With v0.46.0-rc3 , we are packaging v0.19.3:
```
agent.package.cadvisor.url=https://github.com/rancher/cadvisor-package/releases/download/v0.19.3/cadvisor.tar.gz
```

**Comment by psviderski** [comment]
The issue wasn't fixed yet. I simulated the environment when I have 50 not very acrive containers (most of them run `/bin/bash`). The `.cadvisor` process is using about 10-20% CPU.
In my real environment I have similar ~330 containers. According to `htop` sensors the `.cadvisor` process is using 60-100% CPU.
I tried to reduce the scheduling priority for the .cadvisor process: `renice -20 CADVISOR_PID`. That didn't make any significant impact on CPU usage. I also tried to pin the `rancher-agent` container to a particular CPU core to not overload others. Still it's not a solution.

Frankly speaking I use rancher only for continuous starting and destroying a bunch of containers. I don't need any metrics for those containers. Is there any way to just **disable** cadvisor in `rancher-agent` container?

**Comment by gordontyler** [comment]
Using Rancher v0.49.0, I can confirm this. cadvisor is still using 15-20% CPU on a host with 12 active containers. Which version of rancher/agent-instance or rancher/agent has this new version of cadvisor?

**Comment by cloudnautique** [comment]
@gordontyler the package is updated via Rancher server and not the rancher/agent version. Most of our agent code is updated this way.

@psviderski, there is no way to disable it right now. We have it in the roadmap to allow passing options so you could adjust the sample rate. We rely on cAdvisors metadata information for a few things, so Im not sure how easy it would be to completely turn it off.

**Comment by gtrias** [comment]
Same problem here. 18 containers not very active and cadvisor is taking about 10-15% CPU constant usage.

rancher-server v1.0.0.

**Comment by SydOps** [comment]
Any updates for this issue?

**Comment by smaccona** [comment]
Same problem here. Only 1 container active apart from the Rancher agents, and consistently seeing 20%+ CPU usage. This is on a hardware server with 4 cores & 8GB RAM.

**Comment by kiakj** [comment]
v1.0.2 with 15+ containers per host, cadvisor is registering ~10% cpu usage

**Comment by teon** [comment]
I have 1.1.x version - and .cadvisor is taking 50% CPU on one of my hosts (ubuntu LTS 16.04)

**Comment by snipking** [comment]
v1.0.2 with 11 container, .cadvisor is taking 5% ~ 10% CPU. But `docker stats` shows rancher-agent container taking 300%+ CPU.

Another host seems fine.

**Comment by deniseschannon** [comment]
@snipking In our next release (v1.2.0-pre4), we have removed cadvisor from Rancher and will be using `docker stats` to report stats.
