### ISSUE TITLE
Log certificate info when x509 error is seen in agent

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#22419]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Create/import cluster so agents get deployed, when certificates are incorrect or incomplete (intermediates missing), an error log is show regarding x509. First troubleshooting steps here are running `openssl` commands or any tool that can parse certificates, while we can easily add this information if an x509 error is seen. This should help in diagnosing most of the certificate issues as there are usually only a few root causes.

**Comment by superseb** [comment]
Scenarios to validate, in all cases agent should log a proper indication of the error and certificate details.

- Set up Rancher with self signed certificates but dont configure CA certificate (cacerts.pem), create custom cluster and add a node.
- Set up Rancher with expired certificates, create custom cluster and add a node.
- Set up Rancher with certificates not containing IP and DNS names, create custom cluster and add a node.
- Set up Rancher with self signed certificates using an intermediate CA certificate and don't use the intermediate certificate, create custom cluster and add a node. (see https://gist.github.com/superseb/14ce3c94e0d6896bb43b19b70543be67 for an example)

All setups with properly configured certificates should still work.

**Comment by soumyalj** [comment]
Tested with v2.3-head. The 
Set up Rancher with expired certificates, create custom cluster and add a node.
```
time="2019-10-18T19:26:10Z" level=fatal msg="Server certificate is not valid, please check if the host has the correct time configured and if the server certificate has a notAfter date and time in the future. Certificate information is displayed above. error: Get https://abcd: x509: certificate has expired or is not yet valid"

```
Set up Rancher with self signed certificates using an intermediate CA certificate and don't use the intermediate certificate, create custom cluster and add a node
```
time="2019-10-18T21:26:13Z" level=error msg="Issuer of last certificate found in chain (CN=intermediate-ca,O=dummy-ca) does not match with CA certificate Issuer (CN=root-ca,O=dummy-ca). Please check if the configured server certificate contains all needed intermediate certificates and make sure they are in the correct order (server certificate first, intermediates after)"


```

**Comment by soumyalj** [comment]
@superseb : For the first use case:
Set up Rancher with self signed certificates but dont configure CA certificate (cacerts.pem), create custom cluster and add a node.

When the cacerts are omitted I see 
```
time="2019-10-18T23:46:21Z" level=info msg="DNS Names: [*.qa.rancher.space *.qa.rancher.space]"
time="2019-10-18T23:46:21Z" level=info msg="IPAddresses: <none>"
time="2019-10-18T23:46:21Z" level=info msg="NotBefore: 2019-06-10 18:11:37 +0000 UTC"
time="2019-10-18T23:46:21Z" level=info msg="NotAfter: 2020-06-09 18:11:37 +0000 UTC"
time="2019-10-18T23:46:21Z" level=info msg="SignatureAlgorithm: SHA256-RSA"
time="2019-10-18T23:46:21Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2019-10-18T23:46:21Z" level=fatal msg="Server certificate does not contain correct DNS and/or IP address entries in the Subject Alternative Names (SAN). Certificate information is displayed above. error: Get https://abcd: x509: cannot validate certificate for abcd because it doesn't contain any IP SANs"
```
We should see this error :
```
certErr = fmt.Errorf("Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: %s", err)


```


```

**Comment by soumyalj** [comment]
Tested with v2.3-head using  certs having IP and DNS names. 
Set up Rancher with self signed certificates but don't configure CA certificate (cacerts.pem), create custom cluster and add a node. 

```
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /root/certs/cert.pem:/etc/rancher/ssl/cert.pem -v /root/certs/key.pem:/etc/rancher/ssl/key.pem  rancher/rancher:v2.3-head --no-cacerts


```

With ca-certs omitted the correct error was displayed as below:
```
time="2019-10-22T18:50:21Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get https://abcd: x509: certificate signed by unknown authority"


```

**Comment by ainiml** [comment]
Where do we fix this when Rancher shows `Certificate chain is not complete`?

Which step in "Optional: Installing Rancher on a Single-node Kubernetes Cluster" does this occur in?

We're following this documentation: https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/

We have:
- kubernetes installed via rke
- rke deployed without an external tls
- cert-manager installed via helm
- cert-manager acme issuer installed
- rancher/latest installed via helm
- rancher scaled down to 1

**Comment by superseb** [comment]
Please share the exact commands used and the full log of the agent (please redact any sensitive info)
