### ISSUE TITLE
Support authentication with service account tokens

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#22417]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

Many 3rd party integrations available for Kubernetes (e.g. for Gitlab, Vault, Avi, etc.) involve giving an external process access to the Kubernetes API using a native Kubernetes Service Account token for authentication.

Rancher's Auth Proxy has no notion of SA tokens and sending any request to the Rancher endpoint that uses such token will result in an auth error.

**Expected behaviour:**

Ranchers auth proxy should support authentication of requests that specify a Service Account token in the Authorization Bearer header

**Additional notes:**
Implementation could leverage TokenReview API

gz#12686
gz#12674

**Comment by samjustus** [comment]
SURE_2746

**Comment by dasarinaidu** [comment]
https://github.com/rancher/dashboard/issues/11444

**Comment by dasarinaidu** [comment]
Completed validations on `v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head` below new issues got reported. None of them are blockers and closing this card.

https://github.com/rancher/rancher/issues/46170
https://github.com/rancher/dashboard/issues/11444

None of them are blockers and closing this card.
