### ISSUE TITLE
In the admin tab, expanding individual processes do not stay open.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2242]
v0.40.0

In the Admin page, the "Expand All" button works, but not when you click on the individual "+" sign for the process. 
<img width="920" alt="screen shot 2015-10-06 at 2 19 35 pm" src="https://cloud.githubusercontent.com/assets/11410997/10323047/8a3ce99e-6c35-11e5-8dfb-8ffc20baf5e4.png">

**Comment by sangeethah** [comment]
Tested with server version - V0.43.0-rc2

In the Admin page, when you click on the individual "+" sign for the process , child processes get listed as expected.
