### ISSUE TITLE
UI: Show ability to add taints based on the cluster's TaintSupport capability

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#22424]
Cluster.Status.Conditions.TaintSupport will be set to True for RKE provisioned clusters upon the first successful RKE reconcile. 
This flag is a bool ptr set to nil for all other clusters

**Comment by sowmyav27** [comment]
Verified on an upgrade from `2.2.8` to `master-head`.

**Cluster specs:**
```
2 custom clusters - minimum - 1etcd, 1 control plane and 1 worker node
2 rke DO clusters -  minimum - 1etcd, 1 control plane and 1 worker node with individual node pools
```
**Steps:**

- Have the cluster deployed in `2.2.8`. 
- Upgrade rancher to `master-head`.
- The clusters do not have `taintSupport": true` flag.

**Scenarios verified:**

**On rancher upgrade -** 
- In Edit custom cluster --> register page --> Add Taints is available
- In Custom cluster --> Edit node --> No Taints available.
- In rke cluster - Edit node does NOT have taints
- In rke cluster - Edit cluster --> Node pool has taints

- Edit node template -- has taints. Taints can be added.

- Add a taint on the node template and scale up the worker node. `taintSupport": true` flag is seen set on the cluster after it comes up `Active`. 

- etcd and control plane nodes, do not show existing kubernetes taints -- logged issue --https://github.com/rancher/rancher/issues/22565

- new cluster created in master-head has the `taintSupport": true` flag set and the nodes --> Edit node --> Have taints available, user can add taints.
