### ISSUE TITLE
UI: show download images link on kontainerdrivers page

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#22422]
Since we have dynamic updates to metadata now, we have now added a new link `rancher-images` to allow users to download `rancher-images.txt` which has list of newer images to download.  

We need to show this option in UI. Probably near the `refresh` action. 

https://github.com/rancher/rancher/issues/22364

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:master-head d7b425da7

Now the extension of the downloaded file is `.txt`
