### ISSUE TITLE
Project members see incorrect cluster provider type

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#22436]
**Rancher Version**
v2.2.8

**Steps to reproduce (least amount of steps as possible):**
1. Set up Rancher(HA)
2. Add an EC2 cluster with 3 all-role nodes.
3. Create a project in the cluster.
4. Create a user and set it as the project member.
5. Log in as the user in another browser.

**Result:**
View from the global admin:
![image](https://user-images.githubusercontent.com/5697937/63757204-419a9e80-c8ec-11e9-9847-a1e8117c4c6e.png)

View from the project member:
![image](https://user-images.githubusercontent.com/5697937/63757253-537c4180-c8ec-11e9-96dc-03a4f4957e4b.png)

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/12038
