### ISSUE TITLE
Expose metadata field in "Add Service" and "Edit Service" pages.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2243]

**Comment by vincent99** [comment]
@loganhz Add a new component & section (similar to `Labels`) to detail and add/edit service/container?  (`app/components/container/new-edit`).  It should be able to just be a wrapper around `app/components/form-key-value`, like various other parts of container definition use.

**Comment by loganhz** [comment]
@vincent99 `labels` is `map[string]` and `metadata` is `map[json]`
so can I just use a `textarea` to let user input the `json` for each key of `metadata`?

**Comment by vincent99** [comment]
Hmm, I didn't know they were arbitrary JSON.  I think a textarea (`{{input-multiline}}`) is fine, and if you want to enter arbitrary JSON that's fine.  But I want to be able to just type a string and not have to quote it.

So you can add a Util method which takes a value, trims it, and if it:
- Is not the word `true`, `false` `null`
- And is not numeric (`Util.isNumeric()`)
- And does not start with `"`, `[` or `{`

Then assume it is a string and return the value wrapped with double-quoted.
Else return original string.

Then apply that to all the metadata values in app/components/container/new-edit/component.js `willSave()` just before the call at the end to `this.validate()`.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Verified fixed
