### ISSUE TITLE
Installing MariaDB container / Raplicating Mysql/mariadb possible?

### ISSUE THREAD

**Issue by RVN-BR** [rancher/rancher#2244]
I'm getting the following error over and over when trying to start a mariadb image from rancher... (I'm setting the env variable with the password)...

```
0/6/2015 8:41:48 PM151006 23:41:48 [Note] mysqld (mysqld 10.0.21-MariaDB-1~jessie) starting as process 1 ...
Invalid Date Invalid Date151006 23:41:48 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Invalid Date Invalid Date151006 23:41:48 [Note] InnoDB: The InnoDB memory heap is disabled
Invalid Date Invalid Date151006 23:41:48 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Invalid Date Invalid Date151006 23:41:48 [Note] InnoDB: Memory barrier is not used
Invalid Date Invalid Date151006 23:41:48 [Note] InnoDB: Compressed tables use zlib 1.2.8
Invalid Date Invalid Date151006 23:41:48 [Note] InnoDB: Using Linux native AIO
Invalid Date Invalid Date151006 23:41:48 [Note] InnoDB: Not using CPU crc32 instructions
Invalid Date Invalid Date151006 23:41:48 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Invalid Date Invalid DateInnoDB: mmap(274726912 bytes) failed; errno 12
Invalid Date Invalid Date151006 23:41:48 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
Invalid Date Invalid Date151006 23:41:48 [ERROR] Plugin 'InnoDB' init function returned error.
Invalid Date Invalid Date151006 23:41:48 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Invalid Date Invalid Date151006 23:41:48 [Note] Plugin 'FEEDBACK' is disabled.
Invalid Date Invalid Date151006 23:41:48 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
Invalid Date Invalid Date151006 23:41:48 [ERROR] Unknown/unsupported storage engine: InnoDB
Invalid Date Invalid Date151006 23:41:48 [ERROR] Aborting
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:41:48 [Note] mysqld: Shutdown complete
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:42:01 [Note] mysqld (mysqld 10.0.21-MariaDB-1~jessie) starting as process 1 ...
Invalid Date Invalid Date151006 23:42:01 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Invalid Date Invalid Date151006 23:42:01 [Note] InnoDB: The InnoDB memory heap is disabled
Invalid Date Invalid Date151006 23:42:01 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Invalid Date Invalid Date151006 23:42:01 [Note] InnoDB: Memory barrier is not used
Invalid Date Invalid Date151006 23:42:01 [Note] InnoDB: Compressed tables use zlib 1.2.8
Invalid Date Invalid Date151006 23:42:01 [Note] InnoDB: Using Linux native AIO
Invalid Date Invalid Date151006 23:42:01 [Note] InnoDB: Not using CPU crc32 instructions
Invalid Date Invalid Date151006 23:42:01 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Invalid Date Invalid DateInnoDB: mmap(274726912 bytes) failed; errno 12
Invalid Date Invalid Date151006 23:42:01 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
Invalid Date Invalid Date151006 23:42:01 [ERROR] Plugin 'InnoDB' init function returned error.
Invalid Date Invalid Date151006 23:42:01 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Invalid Date Invalid Date151006 23:42:01 [Note] Plugin 'FEEDBACK' is disabled.
Invalid Date Invalid Date151006 23:42:01 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
Invalid Date Invalid Date151006 23:42:01 [ERROR] Unknown/unsupported storage engine: InnoDB
Invalid Date Invalid Date151006 23:42:01 [ERROR] Aborting
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:42:01 [Note] mysqld: Shutdown complete
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:42:27 [Note] mysqld (mysqld 10.0.21-MariaDB-1~jessie) starting as process 1 ...
Invalid Date Invalid Date151006 23:42:27 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Invalid Date Invalid Date151006 23:42:27 [Note] InnoDB: The InnoDB memory heap is disabled
Invalid Date Invalid Date151006 23:42:27 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Invalid Date Invalid Date151006 23:42:27 [Note] InnoDB: Memory barrier is not used
Invalid Date Invalid Date151006 23:42:27 [Note] InnoDB: Compressed tables use zlib 1.2.8
Invalid Date Invalid Date151006 23:42:27 [Note] InnoDB: Using Linux native AIO
Invalid Date Invalid Date151006 23:42:27 [Note] InnoDB: Not using CPU crc32 instructions
Invalid Date Invalid Date151006 23:42:27 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Invalid Date Invalid DateInnoDB: mmap(274726912 bytes) failed; errno 12
Invalid Date Invalid Date151006 23:42:27 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
Invalid Date Invalid Date151006 23:42:27 [ERROR] Plugin 'InnoDB' init function returned error.
Invalid Date Invalid Date151006 23:42:27 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Invalid Date Invalid Date151006 23:42:27 [Note] Plugin 'FEEDBACK' is disabled.
Invalid Date Invalid Date151006 23:42:27 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
Invalid Date Invalid Date151006 23:42:27 [ERROR] Unknown/unsupported storage engine: InnoDB
Invalid Date Invalid Date151006 23:42:27 [ERROR] Aborting
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:42:27 [Note] mysqld: Shutdown complete
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:43:19 [Note] mysqld (mysqld 10.0.21-MariaDB-1~jessie) starting as process 1 ...
Invalid Date Invalid Date151006 23:43:19 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Invalid Date Invalid Date151006 23:43:19 [Note] InnoDB: The InnoDB memory heap is disabled
Invalid Date Invalid Date151006 23:43:19 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Invalid Date Invalid Date151006 23:43:19 [Note] InnoDB: Memory barrier is not used
Invalid Date Invalid Date151006 23:43:19 [Note] InnoDB: Compressed tables use zlib 1.2.8
Invalid Date Invalid Date151006 23:43:19 [Note] InnoDB: Using Linux native AIO
Invalid Date Invalid Date151006 23:43:19 [Note] InnoDB: Not using CPU crc32 instructions
Invalid Date Invalid Date151006 23:43:19 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Invalid Date Invalid DateInnoDB: mmap(274726912 bytes) failed; errno 12
Invalid Date Invalid Date151006 23:43:19 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
Invalid Date Invalid Date151006 23:43:19 [ERROR] Plugin 'InnoDB' init function returned error.
Invalid Date Invalid Date151006 23:43:19 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Invalid Date Invalid Date151006 23:43:19 [Note] Plugin 'FEEDBACK' is disabled.
Invalid Date Invalid Date151006 23:43:19 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
Invalid Date Invalid Date151006 23:43:19 [ERROR] Unknown/unsupported storage engine: InnoDB
Invalid Date Invalid Date151006 23:43:19 [ERROR] Aborting
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:43:19 [Note] mysqld: Shutdown complete
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:45:02 [Note] mysqld (mysqld 10.0.21-MariaDB-1~jessie) starting as process 1 ...
Invalid Date Invalid Date151006 23:45:02 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Invalid Date Invalid Date151006 23:45:02 [Note] InnoDB: The InnoDB memory heap is disabled
Invalid Date Invalid Date151006 23:45:02 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Invalid Date Invalid Date151006 23:45:02 [Note] InnoDB: Memory barrier is not used
Invalid Date Invalid Date151006 23:45:02 [Note] InnoDB: Compressed tables use zlib 1.2.8
Invalid Date Invalid Date151006 23:45:02 [Note] InnoDB: Using Linux native AIO
Invalid Date Invalid Date151006 23:45:02 [Note] InnoDB: Not using CPU crc32 instructions
Invalid Date Invalid Date151006 23:45:02 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Invalid Date Invalid DateInnoDB: mmap(274726912 bytes) failed; errno 12
Invalid Date Invalid Date151006 23:45:02 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
Invalid Date Invalid Date151006 23:45:02 [ERROR] Plugin 'InnoDB' init function returned error.
Invalid Date Invalid Date151006 23:45:02 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Invalid Date Invalid Date151006 23:45:02 [Note] Plugin 'FEEDBACK' is disabled.
Invalid Date Invalid Date151006 23:45:02 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
Invalid Date Invalid Date151006 23:45:02 [ERROR] Unknown/unsupported storage engine: InnoDB
Invalid Date Invalid Date151006 23:45:02 [ERROR] Aborting
Invalid Date Invalid Date
Invalid Date Invalid Date151006 23:45:02 [Note] mysqld: Shutdown complete
Invalid Date Invalid Date
```

Any ideas?

Also, is it possible/supported to have multiple mariadb or mysql instances running master/slave replication for example? how does one achieve this? I havent found anything online...

thanks!

PS: on the latest 0.40 I read in the release notes there would be a dockerfile interface to add docker-compose and rancher-compose straight through the web gui, but didnt find that? is that on there?

thanks

**Comment by vincent99** [comment]
Do you have a memory limit set on the container or running on a very small VM?  The critical lines are:

```
[Note] InnoDB: Initializing buffer pool, size = 256.0M
InnoDB: mmap(274726912 bytes) failed; errno 12
[ERROR] InnoDB: Cannot allocate memory for the buffer pool
```

i.e. the database is running out of memory and failing to startup.

The rancher/server image starts up a database to make it as simple as possible to install.  It is possible to do master/slave, multi-master clusters, etc, but if you want to do anything beyond standard you're better off running your own separate database container.  You can tell Rancher/Cattle where to find it by adding a "mysql" link, or using the environment variables described in database parts of the [HA setup docs](http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/).  If either are specified it will not startup the internal default database server.

Compose import is on the screen for adding a new Stack.  You can only use it when adding a new stack at this time.

**Comment by RVN-BR** [comment]
Thanks vincent...  I had assumed that initially so gave the vagrant machine 8gb of ram...  still not enough? or is there a per-container limit I missed somewhere?

I was referring more to replication/HA for databases that are run within rancher, for my own apps, not the rancher DB itself... although maybe the HA setup docs have enough instructions to get me started?  I assume I'd have to somehow create a docker image for masters, and a docker image for slaves with the particular replication options? Would then there be a way to promote them?

If anyone has an example of a full stack running some sort of web app loadbalanced, with HA database I'd really like to take a look to get some basic understanding...

Is there anywhere I can find stack compose files to take as examples?  Like a web+mysql+redis stack, for example?

Also, should one run 1 or multiple LBs generally?  I'm finding that some LBs are failing to start (but I'm not in the office anymore and that is another thread so I will post more tomorrow)...

I'll try this out on an amazon machine to speed up things since sometimes my internet connection isnt the quickest...  Is there any special quick deploy for a rancher server to aws, or just boot up a ubuntu or coreos and run the docker rancher-server cmd?

thanks for all help! rancher is very promissing!!

**Comment by vincent99** [comment]
oh, duh.. those logs are *from* rancher, so you're not talking about its internal DB.. sorry, ignore most of what I said :-) .

You can set a memory limit for each container but there's no limit by default, so each container can use as much as is available.

I don't know of any compose template for running a master/slave cluster.. automatic failover/promotion and all that is not a (open-source) well-solved problem in general that I'm aware of, whether Docker is involved or not.  You can bind-mount config in to `/etc/mysql/conf.d` to do whatever you want though

We are sort of starting to get into defining some common [compose templates](https://github.com/rancher/compose-templates) that you'll eventually be able to deploy from the UI, but there isn't one for mysql yet.  There was a [blog post](http://rancher.com/setting-up-a-scalable-and-highly-available-wordpress-environment-with-rancher-and-docker/) about setting up WordPress that includes XtraDB Cluster (multi-master) that's a bit of that and a bit of example of a loadbalanced app.

One balancer vs several is mostly up to personal preference.. The public port can only be used by one balancer/container though.  This might be why your balancers aren't starting, if there's no hosts with the requested port(s) available.

**Comment by RVN-BR** [comment]
In rgds to the loadbalancer... 
![image](https://cloud.githubusercontent.com/assets/1218902/10337077/c3816c22-6cd3-11e5-8012-2ab1b091b3e1.png)

I started this up yesterday, connected to the container, but it just doesnt start, no logs or anything available? (nothing else is in rancher... only these 2 services/containers)

**Comment by deniseschannon** [comment]
Can you provide the docker-compose.yml for your stack? On the detailed stack page, you can click on this: 

![vvvvvvv](https://cloud.githubusercontent.com/assets/11410997/10351766/2abdb130-6d00-11e5-9780-76f2454f0892.png)

Also, how many hosts do you have on your Infrastructure page?

**Comment by RVN-BR** [comment]
Damn... I deleted everything :(  I'll post if I can reproduce... I think im having somewhat similar issues now discussing in the forum, guess thats the better place... will close this for now?
