### ISSUE TITLE
Rancher GUI logging off

### ISSUE THREAD

**Issue by tardich** [rancher/rancher#22442]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

We should be able to create a user (or set a user parameter) to keep it logged forever in the UI. For monitoring purposes, it's rather annoying to have to log back in on every day.

**Environment information**

**Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI):**
 v2.2.7

**Comment by vincent99** [comment]
I agree that we'd probably not add a feature for this; if anything we more frequently get requests to make it smaller or automatically signing out after X minutes of whatever "inactivity" is defined as.

But if you really want you _can_ make this work on a TV or something with one-time setup... Create an API key, copy the token, log out, open up browser dev tools console and run:

```javascript
document.cookie='R_SESS=<your-token-string>;max-age=300000000;secure;path=/'
```
(replacing `<your-token-string>` with the string you got, e.g. `token-7n7mq:77z4p6v9mk4dzg6z46jxltj5bmf8wdns9hqq5lbr97z4qprddqfh2v`)

Then change the URL to `/g/clusters` or similar.
