### ISSUE TITLE
Determine and document RKE system addons placement

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22448]
We have to determine and document the following for the rke cluster:

- [ ] Default taints we/k8s apply to the nodes
- [ ] Default tolerations and node selectors for the system rke addons, and the addons placement it results in. Addons list: coredns/kubedns/ingress/metrics/cni
- [ ] UPDATE: as an extra item, lets document cluster/node agent and api auth controller default placement too

**Comment by superseb** [comment]
Taints for nodes:
https://rancher.com/docs/rke/latest/en/config-options/nodes/#kubernetes-roles

Taints/tolerations for addons
DNS

| x                   | v0.2.8                                                        | master                                                       |
| ------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| coredns             | - Tolerations: `[map[key:CriticalAddonsOnly operator:Exists]]` <br/>- nodeSelector: `map[beta.kubernetes.io/os:linux]` | - Tolerations: `[map[key:CriticalAddonsOnly operator:Exists] map[effect:NoExecute operator:Exists] map[effect:NoSchedule operator:Exists]]` <br/>- nodeSelector: `map[beta.kubernetes.io/os:linux]` |
| coredns-autoscaler  | - Tolerations: `<no value>` <br/>- nodeSelector: `map[beta.kubernetes.io/os:linux]` | - Tolerations: `[map[effect:NoExecute operator:Exists] map[effect:NoSchedule operator:Exists]]` <br/>- nodeSelector: `map[beta.kubernetes.io/os:linux]` |
| kube-dns            | - Tolerations: `[map[key:CriticalAddonsOnly operator:Exists]]` <br/>- nodeSelector: `<no value>` | - Tolerations: `[map[key:CriticalAddonsOnly operator:Exists] map[effect:NoExecute operator:Exists] map[effect:NoSchedule operator:Exists]]` <br/>- nodeSelector: `<no value>` |
| kube-dns-autoscaler | - Tolerations: `<no value>` <br/>- nodeSelector: `<no value>` | -Tolerations: `[map[effect:NoExecute operator:Exists] map[effect:NoSchedule operator:Exists]]` <br/>- nodeSelector: `<no value>` |



Metrics

| x              | v0.2.8                                                        | master                                                       |
| -------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| metrics-server | - Tolerations: `<no value>` <br/>- nodeSelector: `<no value>` | - Tolerations: `[map[effect:NoExecute operator:Exists] map[effect:NoSchedule operator:Exists]]` <br/>- nodeSelector: `<no value>` |



Ingress

| x                        | v0.2.8                                                        | master                                                       |
| ------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| nginx-ingress-controller | - Tolerations: `<no value>`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[effect:NoExecute operator:Exists] map[effect:NoSchedule operator:Exists]]`<br/>- nodeSelector: `<no value>` |
| default-http-backend     | - Tolerations: `<no value>`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[effect:NoExecute operator:Exists] map[effect:NoSchedule operator:Exists]]`<br/>- nodeSelector: `<no value>` |



CNI

| x            | v0.2.8                                                        | master                                                       |
| ------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| canal        | - Tolerations: `[map[effect:NoSchedule operator:Exists] map[key:CriticalAddonsOnly operator:Exists] map[effect:NoExecute operator:Exists]]`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[effect:NoSchedule operator:Exists] map[key:CriticalAddonsOnly operator:Exists] map[effect:NoExecute operator:Exists]]`<br/>- nodeSelector: `<no value>` |
| kube-flannel | - Tolerations: `[map[effect:NoSchedule operator:Exists] map[effect:NoExecute operator:Exists] map[effect:NoSchedule key:node.kubernetes.io/not-ready operator:Exists]]`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[operator:Exists]]`<br/>- nodeSelector: `<no value>` |
| calico-node  | - Tolerations: `[map[effect:NoSchedule operator:Exists] map[key:CriticalAddonsOnly operator:Exists] map[effect:NoExecute operator:Exists]]`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[effect:NoSchedule operator:Exists] map[key:CriticalAddonsOnly operator:Exists] map[effect:NoExecute operator:Exists]]`<br/>- nodeSelector: `map[beta.kubernetes.io/os:linux]` |
| weave-net    | - Tolerations: `[map[effect:NoSchedule operator:Exists] map[effect:NoExecute operator:Exists]]`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[effect:NoSchedule operator:Exists] map[effect:NoExecute operator:Exists]]`<br/>- nodeSelector: `<no value>` |


Rancher agents

| x                         | v2.2.8                                                       | master-head                                                  |
| ------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| cattle-node-agent         | - Tolerations: `[map[operator:Exists]]`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[operator:Exists]]`<br/>- nodeSelector: `<no value>` |
| cattle-cluster-agent      | - Tolerations: `[map[operator:Exists]]`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[operator:Exists]]`<br/>- nodeSelector: `<no value>` |
| kube-api-auth             | - Tolerations: `[map[operator:Exists]]`<br/>- nodeSelector: `<no value>` | - Tolerations: `[map[operator:Exists]]`<br/>- nodeSelector: `<no value>` |
| cattle-node-agent-windows | n/a                                                          | - Tolerations: `[map[value:true effect:NoExecute key:node-role.kubernetes.io/etcd] map[key:node-role.kubernetes.io/controlplane value:true effect:NoSchedule]]`<br/>- nodeSelector: `<no value>` |
