### ISSUE TITLE
NodeSelector support for remaining rke addons in Rancher API

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22447]
Have to enable NodeSelector support for all rke addons - cni, coredns, kubedns - similar to how we enable it for the ingress controller config https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/rke_types.go#L363

**Comment by mrajashree** [comment]
Node selectors are already supported for DNS addons: coredns, kubedns
and for nginx ingress addon

Node selector support is now being added to network addons: canal, calico, flannel and weave
And the monitoring addon: metrics-server

**Comment by soumyalj** [comment]
Tested with master-head build
Node selectors was tested for network addons Canal, Calico, Flannel and Weave which are daemonsets. 

Created custom cluster by providing node selectors in the yaml file and providing desired labels to the nodes. If the labels did not exist on the nodes, cluster creation would not be complete. 
On editing the node and adding the label, the cluster creation completes successfully.

Node selectors were tested for metrics server also which is a a deployment.
