### ISSUE TITLE
Issue with cattle-node-agent after upgrading to Rancher 2.2.8

### ISSUE THREAD

**Issue by lpereiraa** [rancher/rancher#22446]
Ever since we upgraded from Rancher 2.2.4 to Rancher 2.2.8, Rancher's system cattle-node-agent can't correctly connect to the worker nodes proxy and keeps logging:

time="2019-08-27T15:45:50Z" level=info msg="Starting plan monitor"
time="2019-08-27T15:46:00Z" level=error msg="Failed to connect to proxy" error="read tcp X.X.X.X:51812->X.X.X.X:443: i/o timeout"
time="2019-08-27T15:46:10Z" level=info msg="Connecting to wss://rancher.domain.name/v3/connect with token XXXXXXXXXXXXXXXX"
time="2019-08-27T15:46:10Z" level=info msg="Connecting to proxy" url="wss://rancher.domain.name/v3/connect"

time="2019-08-27T15:52:06Z" level=info msg="Starting plan monitor"
time="2019-08-27T15:52:16Z" level=error msg="Failed to connect to proxy" error="read tcp X.X.X.X:56462->X.X.X.X:443: i/o timeout"
time="2019-08-27T15:52:26Z" level=info msg="Connecting to wss://rancher.domain.name/v3/connect with token XXXXXXXXXXXXXXXX"
time="2019-08-27T15:52:26Z" level=info msg="Connecting to proxy" url="wss://rancher.domain.name/v3/connect"

This is only happening in worker nodes, ETCD and ControlPlane Nodes are fine. Our cluster is an on-prem, VM based cluster. Nodes are 8 core and 32 GiB RAM.

Rancher Version: 2.2.8
Single install
K8s version: 1.14.6

Thanks in advance!

**Comment by lpereiraa** [comment]
Hi David, thanks for the fast reply!

This is happening on nodes running Ubuntu 16.04.6 LTS and this cluster is actually running on Azure, and not "on-prem" as I had previouly mentioned.

**Comment by lpereiraa** [comment]
David,
Thank you for the ultra-fast feedback! If you could please link me that bug issue that is related to mine, I'll follow it and close this one.

**Comment by calexandre** [comment]
@davidnuzik what are the current implications of running a cattle-node-agent in this state?
