### ISSUE TITLE
Pipeline executors don't start causing job execution to fail - 403 

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#22459]
rancher/rancher:master-head ff9cf13b9

Opening this out of rancher/rancher#21777 as it is not related to upgrade specifically, and blocks the basic pipeline workflow. This does not occur in v2.2.8.

* Deploy Rancher
* Create cluster
* Create a pipeline
* Run a job
  * The build executors never finish setting up, and in Jenkins pod logs see:
```
Aug 26, 2019 3:31:46 PM io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1 onFailure
WARNING: Exec Failure: HTTP 403, Status: 403 -
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by rmweir** [comment]
I can confirm that this upgrading the kubernetes version is why the current version of the jenkins plugin is no longer working for us. The plugin has been updated to be compatible: https://github.com/jenkinsci/kubernetes-plugin/commit/98b4f430c4c42c5955cfb507dfa1010277915871

Dax's fix upgrades the plugin.

**Comment by cjellick** [comment]
@rmweir can you get this updated in rancher? I _think_ you just need to update here: https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/tools_system_images.go#L22
cc @loganhz @gitlawr

**Comment by cjellick** [comment]
I have release for it: I have a release for it: https://github.com/rancher/pipeline-jenkins-server/releases/tag/v0.1.4

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 57508ebba

* Created cluster
* Enabled pipeline
* Pipeline executed successfully
