### ISSUE TITLE
Don't allow built-in cluster drivers to be deleted

### ISSUE THREAD

**Issue by nlowe** [rancher/rancher#22454]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Delete a built-in cluster-driver via the API

**Result:**

The cluster driver is deleted. Following the steps outlined in #15267 but adapting it for the cluster driver re-adds it in the UI but shows it stuck flipping rapidly between `Downloading` and `Activating`. The logs are filled with

```txt
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
cattle-system/rancher-67c5bfcd9-sxvwv[rancher]: 2019/08/27 18:58:53 [INFO] update kontainerdriver kd-55tcd
```

until the driver is deleted again. This is with using `local://` for the `url` as outlined in #15267. If I leave it blank (as it appears in the API of a working rancher install) I get a 409 saying the URL is already in use. If I omit the URL, I get a 422 saying it's required.

**Other details that may be helpful:**

If there's no easy way to re-add these via the UI I would expect the API to prevent you from deleting them, only allowing them to be disabled.

This was accidentally deleted with the rancher2 terraform provider, see terraform-providers/terraform-provider-rancher2#109.

**Environment information**

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.5
- Installation option (single install/HA): HA via the helm chart, installed into an EKS Cluster provisioned by Terraform.

**Comment by nlowe** [comment]
I was able to re-install the driver by restarting each of my rancher server pods.

**Comment by tfiduccia** [comment]
@deniseschannon @cloudnautique - do we want to stop allowing built in drivers to be deleted.  Only deactivated?  Or find some other way of allowing them to be added back without forcing admin to restart all servers?

**Comment by zbialik** [comment]
Some organizations will want to delete certain cluster/node drivers that are built-in to rancher. I noticed that the deleted drivers return once you redeploy rancher. This is actually something I do not want to happen. I want those drivers to remain deleted even after a redeploy.
