### ISSUE TITLE
Make node template and cloud credentials consistent with cluster templates

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#22467]
The current implementation of node templates and cloud credentials doesn't fully align with new cluster template  model for sharing, portablility and management. 

The use case we want to be able to enable is allowing administrators to create credentials and node templates for users to consume, but not freely edit. Users of these templates can consume these directly or through cluster templates. Post cluster template enhancements, the `cluster-template-enforcing` setting will also allow enforcing the use of a node template and indirectly cloud credentials.  

For node templates:
1. A role binding should exist that can be attached to a user for editing templates.
1. Admins should be able to share node templates with individuals, groups and publicly for the installation.
1. Global admins should be able to see and edit all templates.
1. An admin should be able to define overrides that the user will be able to enter in.
1. A user should be able to use a template that has been made public, or shared with them.
1. An admin should be able to store Node templates in Git and have new revisions created within Rancher.
1. Cloud credentials should be an overridable option if the administrator choses to do so. 

Cloud credential improvements:
1. Cloud credentials need to support use for all supported node drivers and hosted k8s providers.
1. Admins should be able to opt-in a cloud credential for a specific 3rd party node driver. 
1. Global admins can view (not the secrets) and update all cloud credentials.
1. Users can consume the cloud credential as part of being allowed to use a specific node template.

UI Enhancements:

1. move cluster, node and credential templates out of the "User" drop down into it's own global level menu.

**Comment by cloudnautique** [comment]
#20128 - Cloud credential usage expansion.

**Comment by ledsole** [comment]
Is this feature still being worked on?
