### ISSUE TITLE
Change UI's screenshot image on README.md

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2246]
Rancher UI is appellative for most Sysadmins and DevOps, much more than it was, and congrats for your UI responsables for that!

For someone that comes directly to the repo instead of your site (maybe because someone they are following starred it) could stop looking to know more because current screenshot.

**Comment by deniseschannon** [comment]
Which repo has UI screenshot? I wasn't able to find any in the rancher/rancher README.md or in the rancher/os README.md.

**Comment by cusspvz** [comment]
What the hell, I was going nuts trying to figure out where i did saw that.

I did a search for [config.sh](https://github.com/rancher/rancher/search?utf8=%E2%9C%93&q=config.sh) trying to figure out where it was loading. After checking up the [first file](https://github.com/rancher/rancher/blob/d75427c126a3c00922234f2d9e006879253d1c91/agent/agent.sh), clicked on *rancher* link and it moved me to [commit tree view of rancher repo](https://github.com/rancher/rancher/tree/d75427c126a3c00922234f2d9e006879253d1c91).

My fault for didn't notice that, sorry. :/
