### ISSUE TITLE
Can't shoose k8s version for update after rancherHA upgraded with helm.

### ISSUE THREAD

**Issue by kinbod** [rancher/rancher#22465]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
after rancherHA upgraded with helm, then I found that rancherHA's k8s version is still what I first installed. when I try to update it, but there is no way to do that.

**Result:**

**Other details that may be helpful:**
k8s version of rancherHA hosts can't be updated.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
18.9.6
```
(paste the output here)
```

**Comment by reymonlu** [comment]
Did you change your rke config file with the new version of kubernetes ?

**Comment by kinbod** [comment]
> Did you change your rke config file with the new version of kubernetes ?

I updated rke version from 0.2.6 to 0.2.8 witch hyperkube version is 1.14.6-rancher-1-1

**Comment by kinbod** [comment]
Yes, I have update rancher with helm, and then I found that local rancher cluster’s k8s version is still old version, so I want to update it, but I can’t find the entry.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Lucas Reymond <notifications@github.com>
发送时间: Wednesday, August 28, 2019 2:17:36 PM
收件人: rancher/rancher <rancher@noreply.github.com>
抄送: Bodkin Quan <carlquan@outlook.com>; Author <author@noreply.github.com>
主题: Re: [rancher/rancher] Can't shoose k8s version for update after rancherHA upgraded with helm. (#22465)


Did you change your rke config file with the new version of kubernetes ?

―
