### ISSUE TITLE
通过Rancher创建的集群，为什么修改不了集群名称？

### ISSUE THREAD

**Issue by jingruhou** [rancher/rancher#22464]
![image](https://user-images.githubusercontent.com/6825570/63819035-44da6c80-c976-11e9-8762-b81380ed91a7.png)

**Comment by loganhz** [comment]
See this.

![image](https://user-images.githubusercontent.com/21168270/63840736-26936180-c9b4-11e9-997f-7e5947c84d43.png)

![image](https://user-images.githubusercontent.com/21168270/63840686-167b8200-c9b4-11e9-8888-2367313171f7.png)

**Comment by jingruhou** [comment]
找到了，谢谢。（不支持中文的）
