### ISSUE TITLE
Translation missing from Github auth page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#22460]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1.  Go to Github Authentication setup page

**Result:**  Translation missing from Step 1
![image](https://user-images.githubusercontent.com/11514927/63815631-33e41980-c8ea-11e9-8f93-584c3a8c581c.png)

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/30/2019)

This is looking good in both dark and light themes in latest master-head. Translation key is also present by pressing SHIFT-L in the browser.
