### ISSUE TITLE
Rancher should allow importing  "in-docker" clusters like k3d

### ISSUE THREAD

**Issue by chrisbulgaria** [rancher/rancher#22474]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement / bug

**Steps to reproduce (least amount of steps as possible):**
Standard Rancher 2.2.8, latest k3d.  (both on premise)

Import k3d cluster from Rancher frontend according to instructions, execute resulting yaml on k3d.  cattle cluster agent connects, but catte node agent fails.
Errors below. The same works flawlessly with k3s instead of k3d (on same host) - so problem seems to be related to "in docker". 

**Result:**
Import fails. Errors below. It looks like Rancher tries to connect somehow back to k3d using a k3d docker-local ip.

**Other details that may be helpful:**
Errors  in Rancher log :

2019/08/28 09:23:48 [INFO] Handling backend connection request [c-28msr]
I0828 09:23:48.827652       8 http.go:110] HTTP2 has been explicitly disabled
2019/08/28 09:24:00 [INFO] Stopping cluster agent for c-28msr
2019/08/28 09:24:00 [ERROR] ClusterController c-28msr [user-controllers-controller] failed with : failed to start user controllers for cluster c-28msr: failed to contact server: Get https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=30s: net/http: TLS handshake timeout
2019/08/28 09:24:10 [INFO] Stopping cluster agent for c-28msr
2019/08/28 09:24:10 [ERROR] ClusterController c-28msr [user-controllers-controller] failed with : failed to start user controllers for cluster c-28msr: failed to contact server: Get https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=30s: net/http: TLS handshake timeout

node agent log in k3d : 

WARN: Please bind mount in the docker socket to /var/run/docker.sock if docker errors occur
WARN: example:  docker run -v /var/run/docker.sock:/var/run/docker.sock ...
INFO: Environment: CATTLE_ADDRESS=172.18.0.2 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=453a002a536c7a9eb0c8f2c6e70c0bba346625df6d0c6342c2c0f597f7167950 CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=k3d-k3s-default-server CATTLE_SERVER=https://myhostname:8443
INFO: Using resolv.conf: search  ************* 
INFO: https://myhostname:8443/ping is accessible
INFO: myhostname resolves to xxxxxxxxxxxx
INFO: Value from https://myhostname:8443/v3/settings/cacerts is an x509 certificate
time="2019-08-28T09:23:48Z" level=info msg="Rancher agent version v2.2.8 is starting"
time="2019-08-28T09:23:48Z" level=info msg="Option etcd=false"
time="2019-08-28T09:23:48Z" level=info msg="Option controlPlane=false"
time="2019-08-28T09:23:48Z" level=info msg="Option worker=false"
time="2019-08-28T09:23:48Z" level=info msg="Option requestedHostname=k3d-k3s-default-server"
time="2019-08-28T09:23:48Z" level=info msg="Option customConfig=map[address:xxxxxxxxxxxxxx       internalAddress: label:map[] roles:[]]"
time="2019-08-28T09:23:48Z" level=info msg="Listening on /tmp/log.sock"
time="2019-08-28T09:23:48Z" level=info msg="Connecting to wss://myhostname:8443/v3/connect with token bg2rlj9dqr4klvfd426dwk6g6m6g8n6q5qr4nbqldhf26cb4gqqph6"
time="2019-08-28T09:23:48Z" level=info msg="Connecting to proxy" url="wss://myhostname:8443/v3/connect"
time="2019-08-28T09:23:48Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2019-08-28T09:23:48Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

**Comment by chrisbulgaria** [comment]
Hmm - solved this myself kind of - we are behind a proxy so run rancher (and k3d) with PROXY/NO_PROXY settings. And for this cluster import to work I need to explicitly include the kubernetes service ip (10.43.0.1) in the NO_PROXY. On the Rancher side, not on k3d.
Was never needed before - not for anything else. But for this cluster import apparently. Very strange. Will leave open for a while if anyone wants to shed further light on this and otherwise close.

**Comment by Tanoh-Hermann** [comment]
Thank you for sharing chrisbulgaria . I would also like to try this configuration in order to test multicluster applications with Rancher. How did you configure the proxy url with all the other non-proxy parameters during the installation of rancher? Have you been able to add k3d clusters (with or without traefik) to ranch UI? Does it work?

**Comment by chrisbulgaria** [comment]
Hi,
yes, worked. But is quite some time ago. So to my best recollection:

Rancher:
sudo docker run -d --restart=unless-stopped   \
  -p 8080:80 -p 8443:443 \
-e HTTPS_PROXY=http:myproxy \
-e HTTP_PROXY=http:myproxy \
-e NO_PROXY=localhost,127.0.0.1,0.0.0.0,.mydomain.net,{localip range}/16,10.43.0.1/16 \
-v /etc/pki/ca-trust/source/anchors:/container/certs \
-e SSL_CERT_DIR="/container/certs


k3d  

k3d create  -workers 3 -e HTTPS_PROXY=http://myproxy   -e NO_PROXY=localhost,127.0.0.1,0.0.0.0,.mydomain.net,k3d-$name-server  -v /etc/pki/ca-trust/source/anchors:/container/certs –e SSL_CERT_DIR="/container/certs"     -a $PORT -name $name


Is your proxy maybe BETWEEN rancher and k3d ? Then - there is currently a bug, see #24681

**Comment by Tanoh-Hermann** [comment]
Hi @chrisbulgaria . Ok thanks I will try this I had not considered the configuration on the side of k3d. Thank you
