### ISSUE TITLE
[Windows] host-gw mode get the wrong internal address

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#22475]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Setup rancher server
- Create a Windows cluster with host-gw mode
- Add Linux controlplane
- Add Windows worker

**Result:**
The cluster is fine, but the internal address of the Windows node isn't expected:
![image](https://user-images.githubusercontent.com/3394724/63850018-ce655b00-c9c5-11e9-81a1-7b0efd65557c.png)

query via `kubectl get node -o wide`:
![image](https://user-images.githubusercontent.com/3394724/63850103-f0f77400-c9c5-11e9-89a0-874318bca8e1.png)

**Other details that may be helpful:**
Seems the Windows kubelet could not detect the appropriate network adapter by itself when using bridge network:
![image](https://user-images.githubusercontent.com/3394724/63850422-93aff280-c9c6-11e9-9d0b-906d47563db9.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master-head
- Installation option (single install/HA): single install

**Comment by kingsd041** [comment]
Version: master-head (9/6/19)
Follow the same steps as the ticket description, will get the correct internal IP address of the Windows node.
![image](https://user-images.githubusercontent.com/19684717/64395717-c5435080-d08d-11e9-9f59-7ec1fdd8293a.png)

![image](https://user-images.githubusercontent.com/19684717/64395734-d4c29980-d08d-11e9-8370-ad85e95cd9ea.png)
