### ISSUE TITLE
openstack cloud credentials have gone missing

### ISSUE THREAD

**Issue by tibers** [rancher/rancher#22479]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Install rancher 2.2.8, attempt to create a cloud credential, the "openstack" cloud credential type is missing. 

**Result:**

**EDIT:**
~API/TF will return a 401 (not authorized) or the Openstack cloud credential type is simply missing in the UI.~

This is a red herring, the only problem is the missing UI elements.

**Other details that may be helpful:**

This was working at some point, I can view previous cloud credentials in our previous rancher installation however they appear to be incomplete and can only be seeing through VIEW IN API. They appear as:

```

"annotations": { },
"baseType": "cloudCredential",
"created": "2019-08-23T18:32:20Z",
"createdTS": 1566585140000,
"creatorId": "u-xmh7dvxzc2",
"id": "cattle-global-data:<SNIP>",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"nodeTemplates": "…/v3/nodeTemplates?cloudCredentialId=cattle-global-data%3A<SNIP>",
"remove": "…/v3/cloudCredentials/cattle-global-data:<SNIP>",
"self": "…/v3/cloudCredentials/cattle-global-data:<SNIP>",
"update": "…/v3/cloudCredentials/cattle-global-data:<SNIP>"
},
"name": "<SNIP>",
"openstackcredentialConfig": { },
"type": "cloudCredential",
"uuid": "57e23247-c5d4-11e9-b980-9e96fc4be211"
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA): HA

**Comment by tibers** [comment]
OK. I narrowed down the 40x errors to the cluster which had the hardening guide on it, which means that those are a red herring. I have two 2.2.8 clusters which can provision things successfully, so I suspect the hardening guide does something which makes rancher unhappy, which should be treated as a seperate issue and is unrelated to the missing UI elements.

**Comment by deniseschannon** [comment]
@tibers Cloud credentials don't exist today for the openstack node driver. I'm going to close this issue in favor of https://github.com/rancher/rancher/issues/20351
