### ISSUE TITLE
Feature Request - Container Scheduling so at least X number of instances are running on these hosts

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#2247]
At present you have the options to schedule where a services containers run based upon either host labels or container labels / names. You can then schedule the service to 'should run' or 'must run' based upon these tags.

In our scenario, we have a number of blade enclosures that contain our rancher hosts. I'd like to tell rancher to ensure that the service is running across both enclosures to ensure my service is resilient to an enclosure failure. This could be a common requirement if you wanted to span racks or perhaps even datacentres. Host labels seem an obvious choice, i'm not sure how it would be best presented through the UI but something along the lines of:

Always run at least one instance of this service on each of the following host labels. ___

This may or may not then affect the scale of the service i guess if you have more host labels than the scale of the service, again not sure how that would be best handled.

**Comment by disaster37** [comment]
Maybee a good way is to add a minimal scale docker instance (under the scale docker).

For exemple you can scale 6 instances for this service and you should there is always at minimal 3 instances online. So if the counter is under 3 it'move on instance in other online node. I think it' can work in addition with host label.

You think it can asnwere of your problem ?

**Comment by Rucknar** [comment]
Don't think that would cut it i'm afraid @disaster37 
In this scenario we are looking for guarantees that we have resources split across our physical boundaries. Scaling currently won't give us that guarantee plus we would be wasting resources keeping surplus containers online.

**Comment by vincent99** [comment]
You can do soft anti-affinity to a container label to accomplish some of this.  If you add a scheduler rule for "should not have the container label io.rancher.stack_service.name=${stack_name}/${service_name}` then no two containers of the service will go to the same host until there are more instances of it than hosts.  This won't guarantee that they are e.g. in different datacenters though.

The global scale ("always run one container on each host") can also be used to run one (but not more) instance on every host that matches the scheduling rules

**Comment by Rucknar** [comment]
Thanks @vincent99 i'll give that a try, still think there would be value as a new feature but that might give us some protection in the meantime.

**Comment by Rucknar** [comment]
@vincent99 Just got around to testing this. I ended up using the following format in my docker compose to avoid the variable substitution picking up the values:
```
io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=stack_name/service_name
```

**Comment by demarant** [comment]
this issue is related to https://github.com/rancher/rancher/issues/2590 and this https://github.com/rancher/rancher/issues/2558

**Comment by deniseschannon** [comment]
I believe we have introduced global scale with x number of containers on each host in the refactoring. @tfiduccia can you test it?

**Comment by vincent99** [comment]
Yes, (but only in 2.0)

**Comment by tfiduccia** [comment]
Version: 6/26 master (2.0)
Feature has been added to 2.0
