### ISSUE TITLE
Redundant images in the  downloaded rancher-image.txt file

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#22485]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement 

**Steps to reproduce (least amount of steps as possible):** 
- run rancher-master 
- go to Tools -> Driver -> Download Image List  

**Result:**
The downloaded rancher-image.txt file contains images for **all** current k8s visions instead of only for the newly-added ones
 
it will be good if we can remove those already existing images from the file.

**Comment by kinarashah** [comment]
@mrajashree 
`rancher-images.txt` should point to images list user would need to download if metadata is updated dynamically. Currently, we do it for current k8s versions (versions that show in dropdown while creating cluster from UI). This flow is similar to how we generate it for the first time, so it should be fine. 

Additional images present won't affect performance in anyway, loading them would just print it already exists. 

@alena1108 we can move this out of 2.3 

cc: @sangeethah

**Comment by deniseschannon** [comment]
I don't believe this is an issue to have existing images in the file and will close this issue.
