### ISSUE TITLE
externally added metadata should get updated 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#22489]
Issue:
- Add a new template or service option in metadata and update `data.json` 
- Check it gets loaded under `v3/rkeAddons` or `v3/rkek8sserviceoptions` 
- Update it in metadata and push new `data.json` 
- The objects don't get updated. 

Note:
- the objects would get updated only if they're not builtin (not vendored in)

**Comment by kinarashah** [comment]
Sample example, 
 - rancher running kontainer-driver-metadata at `f5abbfa5182ea0b77237404637638283cf5daa23` 
- check `1.15.3-rancher3-2` is not present 
- Add a new version `1.15.3-rancher3-2` (update your fork to point to `c1c23cfb7cd9085713364dc60a63a3d533fcd2d6` from `https://github.com/kinarashah/kontainer-driver-metadata.git`, branch `ssm`) 
- see it getting shown in Rancher 
- Update service options and template for this new version. (update fork of metadata to point to latest commit `8a447b4d97f36560b23b90194ff65e97b3d1ecad` from `https://github.com/kinarashah/kontainer-driver-metadata.git`, branch `ssm`) 
- refresh metadata 
- see it getting updated.

**Comment by jiaqiluo** [comment]
The bug fix is validated with self-built rancher images from rancher:mater-head 19377a560b660f293ec9ccbcc60969b9ddfd8361

The steps are the same as @kinarashah's previous comment provides.

we can update the metadata of the k8s version which is not Rancher built-in one

<img width="652" alt="Screen Shot 2019-09-03 at 5 52 04 PM" src="https://user-images.githubusercontent.com/6218999/64217809-aff2da00-ce73-11e9-9a1e-81c04322418e.png">
