### ISSUE TITLE
Want to pass "engine" options through to Docker Machine

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2248]
I'd like to pass the same options docker-machine for every host, so I don't need anything dynamic. Initially, I want to pass in "--engine-insecure-registry myregistry.company.com" and maybe a couple of "--engine-opt key=value" settings as well.  

This will allow me to set up the docker engine on hosts without having to log in and edit /etc/default/docker (I hope). 

Here's more information on what I'm talking about: 
https://docs.docker.com/machine/reference/create/
See this section of the page: "Specifying configuration options for the created Docker engine"

**Comment by deniseschannon** [comment]
This was impemented as of v0.50.0
