### ISSUE TITLE
rancher app install Fails to Launch Local Helm Chart

### ISSUE THREAD

**Issue by rextca** [rancher/rancher#22484]
I recently started having a problem launching local Helm charts via the Rancher CLI (2.0.6 and 2.2.0) on Windows.  They launch successfully when I enter the same command on a Linux machine or from Windows if I tell it to get the chart from a repository by omitting ./ in the app install command.
To reproduce:
- Put the chart in C:\<base dir>\<chart name>
- cd to C:\<base dir>
- rancher app install ./<chart name>
At this point the app appears in the Rancher web page with error, "Wait helm template failed. Error: no Chart.yaml exists in directory "/" : exit status 1"
After a few minutes, the command line reports, "[31mFATA[0m[0131] timed out waiting for app notes, the app could still be installing. Run 'rancher apps' to verify"
rancher apps returns, "[31mFATA[0m[0000] Bad response statusCode [404]. Status [404 Not Found]. Body: [message=failed to find resource by id, baseType=error, code=NotFound] from [https://rancher-server.mydomain.com/v3/project/c-gkz6s:p-48tst/apprevisions/p-48tst:]"

(The more intuitive 'rancher app install .\<chart name>' fails immediately with "[31mFATA[0m[0002] Not found: .\spring-hello".  I don't believe that ever worked.)

Rancher version is 2.2.6.  This previously worked, maybe on 2.2.4, but I'm not sure when it broke because I don't use Windows often.  Windows version is Windows 10 Version 1809 (OS Build 17763.678).

The cluster is hosted on a locally hosted VM.  Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"

Rex

**Comment by rextca** [comment]
I made a mistake in my previous post: the command that used to work on Windows was:
rancher app install ./name
where name is the name of the directory containing the Charts.yaml file and is a subdirectory of the current directory.

So my problem is that on the Windows command line I can't use the Rancher CLI to launch a chart from local disk - only by uploading it to a repository and launching it from the repo.  Launching from local disk always hangs with "Wait helm template failed. Error: no Chart.yaml exists in directory "/" : exit status 1".

If I let it wait too long, the etcd database fills up, so it appears to leak DB objects.

Other syntax that I tried:
>rancher app install .\name
[31mFATA[0m[0001] Not found: .\name
>cd name
>rancher app install .
web Apps page shows => Wait helm template failed. Error: no Chart.yaml exists in directory "/" : exit status 1

Has anyone gotten this to work on Windows?

Rex

**Comment by jrwhetse** [comment]
I'm having this same problem and know it previously worked. I can deploy files in the helm chart directly , for example rancher app install ./name/templates/deployment.yaml . And I can confirm etcd fills up quickly

**Comment by hrbu** [comment]
Faced the same issue with Rancher v2.2.8 and the CLI in Windows.

A painless workaround for me: Run the `rancher-cli` using the [WSL](https://docs.microsoft.com/en-us/windows/wsl/about).

**Comment by rextca** [comment]
I probably should have marked this as kind/bug when I submitted it.  I don't see a way to do that now.
