### ISSUE TITLE
Control Plane HA scenario results in the worker nodes to get into Unavailable state if one of the Control Plane nodes was turned off and Unavailable under certain conditions

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22494]
Rancher version: master-head (v2.3) (08/27/2019) d1718af7d

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Control Plane HA scenario results in the workers nodes to go into Unavailable state if one of the two Control Plane nodes was turned off and Unavailable even with the second Control Plane still Active.

1. Create a cluster with 1 Control Plane 3 etcd and 3 Workers. I used Ubuntu 18.04.3 with Docker 19.03.1
2. Create one new Control Plane once all the nodes are Active. 
   - Let's say cp1 is the existing Control Plane and the new cp2
3. Turn Off the first Control Plane (cp1) from the infrastructure/cloud provider.
4. Wait until the node is not responding (ping)
5. Remove the node (cp1) from the UI before its state is `Unavailable`.
   - Here if the next steps do not reproduce the issue try when its state is `Unavailable`
6. The node cp1 will be recreated. Wait until active.
7. Remove cp2 node.
8. After cp2 comes online cp1 will be Unavailable making all workers Inactive.

This is a very intermittent issue that might require more experiments in above steps I was only able to reproduce it once and the above steps might require some improvements.

**Result:**

![ErrorControlPlane](https://user-images.githubusercontent.com/27659/63863972-edcb9c00-c963-11e9-81ba-40ece5d658bc.png)

**Other details that may be helpful:**

Quoting @moelsayed:

> We have a component called nginx-proxy acts as a revers proxy for the api on each worker node.. this allows kubelet to talk to localhost reach the Control Plane nodes..
> 
> nginx-proxy get the configuration from an environment that has a list of the control nodes, in this case that list has only the node that you turned off..
> 
> it should have both..

**Environment information**

- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DigitalOcean
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 1.15.3-rancher1-2

- Docker version (use `docker version`):

```
Docker 19.03.1.
```

**Comment by moelsayed** [comment]
I am unable to reproduce this issue. I tried several times with different permutations in the steps and still can't reproduce.

**Comment by izaac** [comment]
@moelsayed I also tried to reproduce it a few times but I'm unable to. I think we can close this issue if it's just making noise as the reproduction steps are hard to figure out. And reopen it in case we stumble upon it in the future 

I kept the Rancher Server logs in case someone is interested in doing some further analysis.

**Comment by izaac** [comment]
closing as I was not able to repro these past couple of days. We will re-open if we figure out the precise conditions to reproduce.
