### ISSUE TITLE
Better Websocket Error Logging

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#22496]
Through debugging some things with clients and debugging the proxy it was decided we need some better logging in the web proxy.

**Comment by luthermonson** [comment]
https://github.com/rancher/norman/pull/301

**Comment by cjellick** [comment]
you can see the better error logging if you do something like kill the LB in front of rancher or even just straight up stop rancher

**Comment by luthermonson** [comment]
check for resp being nil: https://github.com/rancher/norman/pull/302

**Comment by cbron** [comment]
Validating...

**Comment by cbron** [comment]
Validated. Using new rancher-agent image by specifying `CATTLE_AGENT_IMAGE` env var in upstream cluster. Stopped upstream rancher server to replicate a failure and checked logs in downstream cluster. From both cluster agent and node agent we now get the descriptive error: 
```
time="2019-09-09T18:41:13Z" level=error msg="Failed to connect to proxy. Response status: 502 - 502 Bad Gateway. Response body: \n<!doctype html5....a long custom error"  error="websocket: bad handshake"```
