### ISSUE TITLE
Prometheus monitoring cannot use remote storage

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#22504]
Currently, when rancher cluster monitoring and project monitoring are enabled, the monitoring data cannot be stored on the remote storage and can only be stored in the local storage. The problem is that the monitoring number cannot be monitored.Hope to configure prometheus remote storage can be docked as influxdb, Elasticsearch
https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`authenticated.cluster.monitoring.index`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/20624
