### ISSUE TITLE
Cannot provide machines on openstack with rancher 2.2.4 to 2.2.8

### ISSUE THREAD

**Issue by fabouya** [rancher/rancher#22507]
Hello.

**What kind of request is this**
Bug

** Steps to reproduce (least amount of steps as possible): **
* create ubuntu 16.04 LTS on cloud openstack
* install docker-ce 18.06.3~ce~3-0~ubuntu
* install rancher 2 (with docker-compose) and mapping some directories
      version: '2.0'
      services:
        rancher:
          container_name: rancher_compose
          image: rancher/rancher:v2.2.8
          ports:
          - 443:443
          restart: unless-stopped
          volumes:
            - /USR/rancher/logs:/var/log
            - /USR/rancher/lib:/var/lib/rancher

* place CA for openstack and other needed stuff (userdatas files, ssh key for nodes) in /USR/rancher/lib
* on rancher GUI
** Activate openstack driver
** Create an openstack node template with needed information (use only openstack ids and not symbolic names when choice exists)
** Create an openstack cluster using the template (one single node with all roles)

**Result:** 
Fail with error:
NodeController c-mq9kg/m-fd9r5 [node-controller] failed with : Error creating machine: Error in driver during machine creation: Ill-formed CA certificate(s) PEM file

**Other details that may be helpful:**
Openstack version : Queens
Ubuntu :
  Distributor ID: Ubuntu
  Description:    Ubuntu 16.04.5 LTS
  Release:        16.04
  Codename:       xenial
Docker : Docker version 18.06.3-ce, build d7080c1
Images used for nodes : rancher OS 151, rancher OS 153, ubuntu 16.04

* Note : all rancher 2.2.x version from 2.2.4 to 2.2.8 fails to create instances.

* Error for version 2.2.4 is :
2019/08/29 09:12:57 [INFO] Generating and uploading node config rnnod1
2019/08/29 09:13:12 [ERROR] NodeController c-4d7bv/m-qjx8t [node-controller] failed with : Error setting machine configuration from flags provided: open /var/lib/rancher/userdata/userdata_rancher.yml: no such file or directory

** Note : the userdata file exists in the specified path
root@8f6469114dbd:/var/lib/rancher# ls -l /var/lib/rancher/userdata
total 8
-rw-r--r-- 1 root root  112 Aug 29 08:54 userdata_rancher.yml
-rw-r--r-- 1 root root 1021 Aug 29 08:54 userdata_ubuntu.yml
root@8f6469114dbd:/var/lib/rancher#

* Notes :

** From version 2.2.5 to 2.2.8 the message is the one related above:
node-controller] failed with : Error creating machine: Error in driver during machine creation: Ill-formed CA certificate(s) PEM file

** The Last working version with openstack is 2.2.3 (using always the same node template)

** Changing images for nodes or docker version produce same errors

** All rancher servers are made the same way using openstack heat with exactly the same files, only the rancher/rancher version is modified in the docker compose to check v2.2.3 to 2.2.8

**Comment by seancharlton** [comment]
I can confirm that rancher v2.2.2 is the only version that works with my openstack as a node driver.

In my Case the parameter "--openstack-private-key-file" is broken in the docker-maschine exec above rancher server v2.2.2. The parameter puts out a wrong path to the ssh key, so the state from the cluster nodes stays at "waiting for ssh to be reachable."

If i copy the whole docker-machine command and change the private-key-file parameter to the actual path, everything works.

SSH Key Path set in the Rancher Driver Template: /opt/sshkeys/rancher.pem
Docker-Machine exec parameter: "--openstack-private-key-file /6A7BPTO4ZY/id_rsa"

**Comment by SvenMW** [comment]
> I can confirm that rancher v2.2.2 is the only version that works with my openstack as a node driver.
> 
> In my Case the parameter "--openstack-private-key-file" is broken in the docker-maschine exec above rancher server v2.2.2. The parameter puts out a wrong path to the ssh key, so the state from the cluster nodes stays at "waiting for ssh to be reachable."
> 
> If i copy the whole docker-machine command and change the private-key-file parameter to the actual path, everything works.
> 
> SSH Key Path set in the Rancher Driver Template: /opt/sshkeys/rancher.pem
> Docker-Machine exec parameter: "--openstack-private-key-file /6A7BPTO4ZY/id_rsa"

did you try a newer release since then?
I'm also having trouble deploying on openstack and wonder if we hit the same or different problems.

could you also share how you where able to extract the needed docker machine command from rancher?

Thanks in advance.

**Comment by denzs** [comment]
The problem mentioned by @seancharlton stillt exists with v2.4.5

**Comment by SvenMW** [comment]
This actually works for me in v.2.4.5. I had a different problem, which I was able to sort out.

What exact problem are you hitting @denzs ? Can you provide your node template, and/or the error message you receive?

**Comment by denzs** [comment]
It is exactly as describe by seancharlton, rancher-machine seems to reference an ssh key which does not exist...

2020/07/13 12:36:46 [ERROR] NodeController c-kkbpd/m-zngk4 [node-controller] failed with : Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

**Comment by SvenMW** [comment]
Did you try to paste the private key content in the rancher/openstack node template?
The original report makes me suspicious, because in fact, the command which get's executed by rancher is not docker-machine, but the forked variant "rancher-machine"?

Can you explain how you installed rancher? (dockerized, kubernetes HA?)
Can you provide the complete rancher-machine commandline and did you verify the path to the keyfile?

**Comment by denzs** [comment]
Thank you so much! We actually entered the path to the privatekey file instead of the content!
Now with the content instead of the path - it works! :)

**Comment by seancharlton** [comment]
Thank you for mentioning this. In Version v2.2.2 and lower you had to give the full path to the ssh private keyfile. We just copied the content in the field, now the provistioning works as intended.
