### ISSUE TITLE
Stuck upgrading EKS Cluster: Virtual network, subnet, and security group must all be set together

### ISSUE THREAD

**Issue by nlowe** [rancher/rancher#22519]
**What kind of request is this (question/bug/enhancement/feature request):**

Upgrading my EKS cluster from 1.12 to 1.13 via the UI causes the cluster to get stuck in the `Updating` state with the following error:

```txt
Virtual network, subnet, and security group must all be set together
```

**Steps to reproduce (least amount of steps as possible):**

1. From the `Global` Clusters view, Click `Add Cluster`
2. Select the `Amazon EKS` cluster driver
3. Select your region, enter your access & secret access key, and click `Next`
4. Select Kubernetes `1.12` and the Standard, Rancher-generated service role. Click `Next`
5. Select `No: Private IPs only` and click `Next`
6. Select your VPC and at least two private subnets. Click `Next`
7. Select an existing security group for Rancher to Customize. Click `Next`
8. Set your node specifications, click `Create`. Allow the cluster to create and become fully available.
9. Edit the cluster. Re-enter your secret access key and click `Save`
10. Change the kubernetes version to 1.13 and click `Save`.
11. Click `Save` for the remaining prompts to keep the same settings.

**Result:**

The cluster goes into the `Updating` state with an error:

```txt
Virtual network, subnet, and security group must all be set together
```

Logs from rancher:

```txt
cattle-system/rancher-67c5bfcd9-fbbwc[rancher]: W0829 20:01:36.520078       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 34343616 (34344790)
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: W0829 20:01:51.604223       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 39457223 (39458146)
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:01:52 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10429
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:01:52 [INFO] kontainerdriver amazonelasticcontainerservice stopped
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:01:52 [INFO] Provisioning cluster [c-m6lss]
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:01:52 [INFO] Updating cluster [c-m6lss]
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:01:57 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10233
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:01:57 [INFO] Starting update
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:01:57 [INFO] kontainerdriver amazonelasticcontainerservice stopped
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:01:57 [ERROR] ClusterController c-m6lss [cluster-provisioner-controller] failed with : virtual network, subnet, and security group must all be set together
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:02:02 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10676
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:02:02 [INFO] kontainerdriver amazonelasticcontainerservice stopped
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:02:07 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10296
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:02:07 [INFO] kontainerdriver amazonelasticcontainerservice stopped
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:02:12 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10756
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:02:12 [INFO] kontainerdriver amazonelasticcontainerservice stopped
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:02:17 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:10628
cattle-system/rancher-67c5bfcd9-jp5hh[rancher]: 2019/08/29 20:02:17 [INFO] kontainerdriver amazonelasticcontainerservice stopped
```

The cluster must be deleted and recreated before any further changes can be made, although I can still interact with the cluster via `kubectl` while it is stuck in this state.

**Other details that may be helpful:**

Perhaps a regression of #14919, however I'm using an existing VPC and Subnets. I found this while playing with the terraform provider (terraform-providers/terraform-provider-rancher2#118) and figured I'd test if you even upgrade EKS Clusters via the UI.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.5
- Installation option (single install/HA): HA via the Helm Chart on an EKS Cluster provisioned by Terraform

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted (Amazon EKS)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud t3.medium
- Kubernetes version (use `kubectl version`):

```
Virtual network, subnet, and security group must all be set together
```

**Comment by nlowe** [comment]
If I edit the `amazonElasticContainerServiceConfig` property in the API to re-add my `secretKey` and change the cluster version, it appears the API upgrades just fine, but not the workers. Going to open a separate issue for that.

**Comment by cxadmin** [comment]
Same issues. Waiting for a solution.
 
![image](https://user-images.githubusercontent.com/22290258/67405273-36e34980-f5bd-11e9-9fae-672e1ba2a63f.png)

**Comment by mshivanna** [comment]
Any Update on the above issue? We are also stuck at the above issue.

**Comment by mshivanna** [comment]
followed @cxadmin's suggestion and it worked. thanks @cxadmin 😄

**Comment by mshivanna** [comment]
Followed @nlowe 's suggestion and it worked. thanks @nlowe  😄
