### ISSUE TITLE
Edit Service dialog limits scale to 11 and overrides existing higher scale setting

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2251]
If I have deployed a stack using rancher-compose with the scale for a service set to a value greater than 11, when I edit that service in the Rancher UI the scale is reduced to 11 and will alter the scale to 11 when Save is clicked.

**Comment by vincent99** [comment]
In the next release the scale still defaults to 11 but will double every time you drag it up to the max so it can be set higher, and if the initial value is set higher it's not lost.

![image](https://cloud.githubusercontent.com/assets/753917/10672347/434457cc-78a4-11e5-8089-9d24c85e7dc1.png)

**Comment by sangeethah** [comment]
Tested with server version - v0.43.0-rc2

UI is now able to show any value for scale without any limit.
 
Tried to create a service with scale 20 from rancher-compose.
When editing this service from UI , the scale is shown at being set to 20 as expected.
