### ISSUE TITLE
[backport] Pipeline executors don't start causing job execution to fail - 403 

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#22511]
Backport https://github.com/rancher/rancher/issues/22459

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2-head ec468dea

* Reproduced in v2.2.8 (`k8s 1.15.3`, `pipeline-jenkins-server 0.1.0`)
* Deployed v2.2-head
* Created a cluster (k8s 1.15.3)
* Enable pipeline
* Pipeline executes successfully
* `pipeline-jenkins-server` version is `0.1.4`
