### ISSUE TITLE
[rancher-compose] rancher-compose rm -f doesn't remove project

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#2252]
Hello,

I'm doing the following in a jenkins job, but the project is still there in rancher.
```sh
14:24:53 >>>> Running rancher-compose -p ezhdanrs1119pro -f docker-compose.yml rm --force
14:24:53 time="2015-10-07T11:24:53-07:00" level=info msg="Project [ezhdanrs1119pro]: Deleting project " 
14:24:53 time="2015-10-07T11:24:53-07:00" level=info msg="[0/3] [db]: Deleting " 
14:24:53 time="2015-10-07T11:24:53-07:00" level=info msg="[0/3] [db]: Deleted " 
14:24:53 time="2015-10-07T11:24:53-07:00" level=info msg="[0/3] [web]: Deleted " 
14:24:53 time="2015-10-07T11:24:53-07:00" level=info msg="[0/3] [elastic]: Deleted " 
```

At one point doing an rm with rancher-compose would remove the project if you didn't specify any services to remove.

**Comment by deniseschannon** [comment]
I am surprised that it would do it previously as I have this issue open: https://github.com/rancher/rancher/issues/1723

**Comment by jwhitcraft** [comment]
Maybe i'm just remembering wrong, but i'll watch that other ticket and close this one out.
