### ISSUE TITLE
Rename Cluster Template to RKE Template for 2.4

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#22529]
To mitigate confusion in 2.3, we are going to call the current implementation of cluster templates RKE Templates. 

To accomplish this, we will:
1. Rename cluster template to RKE Template in the UI.
2. Move the “Cluster Template” create button off the create cluster page.
3. Move “Cluster Template” item from the user menu to the Tools menu in global as “RKE Template”.

As cluster templates are expanded in scope and functionality, the RKE Template will be renamed back to cluster template in 2.4.

**Comment by izaac** [comment]
Rancher version: `master-head` (v2.3) (09/04/2019)

I was able to verify the requirements are met in the latest 2.3 build from today as expected:

> Rename cluster template to RKE Template in the UI.
> Move the “Cluster Template” create button off the create cluster page.
> Move “Cluster Template” item from the user menu to the Tools menu in global as “RKE Template”.

Navigating is also without issues. 

But only thing is that "RKE Template" is plural in the implementation "RKE Templates" but I think it makes sense.

**Comment by izaac** [comment]
Documentation has a separate issue for updates.
