### ISSUE TITLE
[UI] Monitoring - Show amount reserved by node host operating system on Cluster/Node dashboards

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22535]
Version: v2.2.0, v2.2.x, v2.3 (master-head 8/29/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement Request

**Steps to reproduce (least amount of steps as possible):**
- Create a windows cluster (because a windows node needs much more CPU/Memory reserved for OS system)
- Enable monitoring - view the Cluster and Node dashboards

**Result:**
- Notice the significant gap in how much CPU/Memory is used versus reserved.
We should consider completing the reserved band so the remainder is basically "Reserved by Host" cpu or memory.

So essentially, rather than seeing this:
![image](https://user-images.githubusercontent.com/45179589/63982556-c4039980-ca77-11e9-98c8-0699073e2f69.png)

You would see the last bit of the band for reserved filled in with perhaps yellow or orange or red hashed lines. For example, Vincent had a good idea to make it somewhat like this:
![image](https://user-images.githubusercontent.com/45179589/63983952-e3052a00-ca7d-11e9-977f-5b37bb77bcb8.png)
The last bit of the reserved band could have these red "slashes" in a repeating pattern to make it clear this is unusable cpu/memory.

Upon hover you should get a tooltip explaining that this is "Reserved by Host" or something along those lines.

**Other details that may be helpful:**
This should make it much more clear to people whom are new to kubernetes that this is memory that is on the node(s) but not actually usable in the k8s cluster since the OS needs some of the CPU and Memory for each node.

It's more important to consider adding something like this with the advent of Windows support. Now we see much larger gaps between reserved and used since Windows needs much more CPU and Memory to be reserved for the OS.

**Comment by tfiduccia** [comment]
Closing in favor of: #23314
