### ISSUE TITLE
[CLI ]Catalog automatically converts a numbered string into number instead of https://github.com/rancher/rancher/issues/22532keeping it as string

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#22532]
Fix https://github.com/rancher/rancher/issues/13158 in CLI

**Comment by anupama2501** [comment]
Verified on master-head f33188d node driver rke1 cluster with 3 worker nodes, 1 cp and 1 etcd

**Single app:**

- Installed docker-registry single app in the default project by passing the values as follows:

```
./rancher apps install docker-registry --version 1.8.1 --set var=true --set-string varstr="true" --no-prompt
```

- verified the app created in the default project with the values reflected in `answer` and `answerSetString`:

<img width="400" alt="Screen Shot 2021-07-18 at 12 54 21 PM" src="https://user-images.githubusercontent.com/38144301/126080708-9581e95d-68c0-49cb-a827-da9cfe5845dd.png">
 
**Multicluster app:**
Verified by passing values to the multi cluster and the app is installed in local default project and  cluster default project:
```
./rancher multiclusterapps install --no-prompt --set-string c-clj9f:ans-str1=1 --set-string  c-clj9f:p-glql6:ans-str2=2 --set local:p-gvrj9:ans1=1 --set-string local:ans2=2 --target c-clj9f:p-glql6 --target local:p-gvrj9 --version 1.8.1 docker-registry docker-reg
```
cluster-default project
<img width="400" alt="Screen Shot 2021-07-18 at 1 19 42 PM" src="https://user-images.githubusercontent.com/38144301/126081084-4b8b33f5-fb4c-4b1c-b470-f6f54e3df942.png">

local-default project:
<img width="400" alt="Screen Shot 2021-07-18 at 1 21 41 PM" src="https://user-images.githubusercontent.com/38144301/126081142-598a335c-9c68-42ba-8d65-98a8b2561680.png">

**Comment by anupama2501** [comment]
**Upgrade test case:**

- Verified on v2.5.8, create a node driver rke1 3 worker, 1 cp, 1 etcd cluster
- Install docker-registry in the cluster `./rancher apps install docker-registry --version 1.8.1 --set var=true --set-string varstr="true" --no-prompt`
- Upgrade the cluster to master-head f33188d
- Via cli, upgrade the docker-registry and set the value in `--set-string` :
- `./rancher app upgrade --set foo=bar --set-string baz=bunk docker-registry 1.8.1`
- Verified the values are applied in the cluster --> apps --> docker-registry
