### ISSUE TITLE
Metadata - updated metadata is not propagated for DNS and External Services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2253]
Build from master - Oct 6

Steps to reproduce the problem:
Create a DNS service by passing metadata field.
Able to see the metadata field, when querying for metadata of DNS service.

Update service and set metadata field to a different value.
We still see the old values for the metadata , when querying for metadata of DNS service.

Same behavior is also seen when updating external service's metadata.

Expected Behavior is to see the updated metadata.

**Comment by alena1108** [comment]
@sangeethah good catch

**Comment by alena1108** [comment]
should be fixed in the latest

**Comment by sangeethah** [comment]
Tested with latest  build from master:

updated metadata is propagated for DNS and External Services.
