### ISSUE TITLE
istio can not be re-enabled due to sidecards crd is not removed

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#22542]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

istio v1.2.5 can not be re-enabled due to sidecards crd is not removed from rancher-istio.

**Steps to reproduce (least amount of steps as possible):**
1. enabled the istio with latest version 1.2.5
2. disable the istio, and the `sidecards` crd is not removed.
3. re-enable the istio will fail and encounter CRD not exist errors.

**Result:**
should add to delete the `sidecards` CRD.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 57508ebba

* Deploy master
* Create cluster
* Enable Istio
* Disable istio
* Check sidecar crds are removed
  * `kubectl get crd | grep istio` - none returned
* Re-enable istio
* Istio enables successfully
