### ISSUE TITLE
[cadvisor-package] Storage backend to cadvisor

### ISSUE THREAD

**Issue by cicerocomp** [rancher/rancher#2254]
As the rancher already runs cadvisor in each `rancher/agent`. It would be important to avoid using another monitoring system (would be a resource-wasting) by adding an option to the rancher, to configure a storage for cadvisor as the cadvisor has support for multiple storage backends: [https://github.com/google/cadvisor/tree/master/storage (BigQuery, ElasticSearch, InfluxDB, Redis and StatsD)]

**Comment by etlweather** [comment]
+1

**Comment by egwada** [comment]
+1 we want to use ElasticSearch for the cadvisor storage backends

**Comment by deniseschannon** [comment]
We are no longer using cadvisor as of v1.2.0 instead we're using `docker stats` for container stats and https://github.com/shirou/gopsutil for host stats.

**Comment by etlweather** [comment]
@deniseschannon - are we able to grab the stats from Rancher so as to not duplicate the stats collection?

**Comment by vincent99** [comment]
There is no "collection" anymore, live non-historical data is streamed only while you're looking at it.  You can certainly run cAdvisor as a container on your own.

**Comment by etlweather** [comment]
@vincent99  - Thanks, that makes sense.
