### ISSUE TITLE
[Windows] Windows agent reconnects per 10s

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#22543]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Setup rancher server
- Create a Windows cluster with VxLan network mode
- Add a Linux controlplane
- Add a Windows worker
- When the Windows worker is ready, view the log of Windows node agent

**Result:**
The agent reconnects to the server per 10s and reports a timeout error:
![image](https://user-images.githubusercontent.com/3394724/64008200-3348be80-cb48-11e9-96d5-e4dee231dc64.png)

**Other details that may be helpful:**
- In my environment, the Linux agent is fine, but it seems other guys meet this too on Linux agent: https://github.com/rancher/rancher/issues/17617

- A comment from this `read tcp .... i/o timeout` issue of `gorilla/websocket` indicates that these timeout errors are expected when setting read deadline: https://github.com/gorilla/websocket/issues/234#issuecomment-289930527

- After researching, it seems that the read latency of WebSocket is too short, we could increase the amount of the `PingWaitDuration` of remotedialer to fix it: https://github.com/rancher/norman/blob/7317090b9b718dede97240857645d6af81e949a2/pkg/remotedialer/types.go#L8

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master-head
- Installation option (single install/HA): single

**Comment by cjellick** [comment]
regarding fix, see my comment here:
https://github.com/rancher/norman/pull/303#issuecomment-526681195

**Comment by sowmyav27** [comment]
Verified on latest master-head commit id: `c464c7058`
**Steps:**

- Setup rancher server
- Create a Windows cluster with VxLan network mode
- Add a Linux controlplane/etcd, one worker node - linux
- Add 2 Windows worker
- When the Windows worker is ready, view the log of Windows node agent.
- No errors are seen in the logs.
- The agent does NOT reconnect every 10 s.
