### ISSUE TITLE
level=error msg="Failed to connect to proxy" error="websocket: bad handshake" when importing eks cluster 

### ISSUE THREAD

**Issue by Amos-85** [rancher/rancher#22552]
**Bug:**

**Steps to reproduce:**

import eks cluster,
running the yaml file that install all the cattle stuff
rancher node agent container exception:

**Result:**
level=error msg="Failed to connect to proxy" error="websocket: bad handshake

**Other details that may be helpful:**

We manage an on premise HA cluster in one of our data centers and trying to import an existing eks cluster that we've created with terraform 

server mtu: 9000
docker engine mtu: 9000
eks worker mtu: 9001

**Environment information**
- Rancher version: 2.2.8
- Installation option (HA): 

**Cluster information**
- Cluster type (Hosted):
- Machine type (metal) and specifications (CPU/memory): Dell R730XD
- Kubernetes version : v1.14.1

```
- Docker version`: 19.03.1

**Comment by pib** [comment]
I found a potential solution to the issue: https://github.com/rancher/rancher/issues/20651#issuecomment-528683673
