### ISSUE TITLE
better protection against websocket buffering

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#22560]
@ibuildthecloud and i observed a user where agents were disconnecting bc websocket pings were getting stuck in a buffer.

To mitigate, we just want to increase the websocket ping wait to a minute (like we do here, but we cant switch to this package in 2.2 https://github.com/rancher/remotedialer/pull/5)

**Comment by cjellick** [comment]
https://github.com/rancher/rancher/pull/22946
https://github.com/rancher/norman/pull/307

**Comment by sangeethah** [comment]
Tested with latest build from 2.2 branch - `v2.2-head`

Automation tests run against RKE clusters with all supported versions(1.15, 1.14 and 1.13) ,GKE , EKS and imported clusters did not show any regressions.
