### ISSUE TITLE
Add link for downloading windows system images

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#22569]
Right now the `Download Image List` button in Tools -> Driver page always sends request to a single link. And this downloads a list of images, some of which such as kubelet-pause are specific to windows platform.
We need another link to download windows specific system images. 
The API link will be `https://localhost:8443/v3/kontainerdrivers/rancher-windows-images`
And the current `Download Image List` button will be converted to a dropdown, so users can select the link for Linux or for Windows, as per discussion with @vincent99 @alena1108 @kinarashah 

API issue: https://github.com/rancher/rancher/issues/22463

**Comment by jiaqiluo** [comment]
The enhancement is validated in master-head 41ce3ac49

Now the UI looks like this and we can successfully download the image list file for Linux or Windows separately.

<img width="661" alt="Screen Shot 2019-09-04 at 10 15 26 AM" src="https://user-images.githubusercontent.com/6218999/64290737-855c5c00-cf1b-11e9-9c38-012c5e7a7d25.png">
