### ISSUE TITLE
Ability to add labels and annotations at node pool and node template level.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#22574]
Rancher server version - Build from master 

Currently we do not have the ability to set labels and annotations on nodes that get created as part of node pools as part of cluster creation.

We need to have the ability to add labels and annotations at node pool and node template level like we have for taints.

**Comment by bgagnon** [comment]
Another concrete use case for this is to set the `node.kubernetes.io/exclude-from-load-balancer=true` label on nodes which influences their inclusion/exclusion from a load balancer pool. _This requires feature flag `ServiceNodeExclusion` which is Alpha in K8S <1.18 and Beta in 1.18+._

Without this feature in Rancher, nodes need to be labeled after they are provisioned by Rancher (eg. via a `DaemonSet`), which introduces a race condition of them being included in the load balancer pool only to be removed later.

**Comment by ctrox** [comment]
I'm somewhat confused about node labels, it seems to be sort of implemented in the latest public release (2.5.8). You can specify them at node template level which works fine but at a node pool level, while a field in the API exists `nodeLabels` it does not seem to propagate to the nodes created by the node pool. Is this a known limitation or a bug?
