### ISSUE TITLE
UI: show setting `rke-metadata-config` under settings

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#22573]

**Comment by jiaqiluo** [comment]
In Rancher:v2.3.0-rc1 

The `rke-metadata-config` shows under settings and its value can be changed now. 

<img width="1453" alt="Screen Shot 2019-09-05 at 1 28 20 PM" src="https://user-images.githubusercontent.com/6218999/64379135-1f3b0c00-cfe3-11e9-8dba-298107d942c4.png">
