### ISSUE TITLE
user settings shouldn't get overridden by driver metadata

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#22572]
Issue:
Currently metadata sync updates a couple of settings, `k8s-version`, `k8s-versions-current` and corresponding UI settings. If user updates these values, the next metadata refresh shouldn't override these values.

**Comment by jiaqiluo** [comment]
here is the list of issues found during validating this issue:
- https://github.com/rancher/rancher/issues/24146
- https://github.com/rancher/rancher/issues/24152
- https://github.com/rancher/rancher/issues/24150
