### ISSUE TITLE
[Metadata] - Metadata for all services/containers are stored in network agent of all hosts.  

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2257]
Currently Metadata information for all services/containers are stored in network agent of all hosts. 
This is lot of redundant information being stored across all hosts. Is it possible to host this information in one of the hosts / potentially hosted as as service in rancher-server instead of in every host?

Also the size of metadata for service can potentially be very large. currently there is no explicit limit for metadata which is tracked in - #2256 . When service metadata is stored in Network Agent  , should the data be compressed ?

**Comment by vincent99** [comment]
We could switch to YAML and use references to make the file smaller, but it would still be expanded out to multiple copies in memory (I think, maybe the YAML parser is smart).

**Comment by vincent99** [comment]
Answers file is YAML now and unserialized into shared objects instead of multiple separate copies.
