### ISSUE TITLE
Error master: Unschedulable

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#22586]
Please help me. My  cluster's master (custom cluster) show unschedulable 

My master node has: 2G RAM, and 40GB disk

The master status show:  kubelet has no disk pressure

And the below is detail 

  

> 
> 
> admin Log Out
> {
> "allocatable": {
> "cpu": "1",
> "ephemeral-storage": "34776022983",
> "hugepages-1Gi": "0",
> "hugepages-2Mi": "0",
> "memory": "1760808Ki",
> "pods": "110"
> },
> "annotations": {
> "flannel.alpha.coreos.com/backend-data": "{\"VtepMAC\":\"0e:45:0f:a5:7f:11\"}",
> "flannel.alpha.coreos.com/backend-type": "vxlan",
> "flannel.alpha.coreos.com/kube-subnet-manager": "true",
> "flannel.alpha.coreos.com/public-ip": "192.168.94.130",
> "node.alpha.kubernetes.io/ttl": "0",
> "rke.cattle.io/external-ip": "192.168.94.130",
> "rke.cattle.io/internal-ip": "192.168.94.130",
> "volumes.kubernetes.io/controller-managed-attach-detach": "true"
> },
> "baseType": "node",
> "capacity": {
> "cpu": "1",
> "ephemeral-storage": "36850Mi",
> "hugepages-1Gi": "0",
> "hugepages-2Mi": "0",
> "memory": "1863208Ki",
> "pods": "110"
> },
> "clusterId": "c-6xxcm",
> "conditions": [ 7 items
> {
> "status": "True",
> "type": "Initialized"
> },
> {
> "message": "registered with kubernetes",
> "status": "True",
> "type": "Registered"
> },
> {
> "status": "True",
> "type": "Provisioned"
> },
> {
> "lastHeartbeatTime": "2019-09-01T00:49:49Z",
> "lastHeartbeatTimeTS": 1567298989000,
> "lastTransitionTime": "2019-08-31T15:57:09Z",
> "lastTransitionTimeTS": 1567267029000,
> "message": "kubelet has sufficient memory available",
> "reason": "KubeletHasSufficientMemory",
> "status": "False",
> "type": "MemoryPressure"
> },
> {
> "lastHeartbeatTime": "2019-09-01T00:49:49Z",
> "lastHeartbeatTimeTS": 1567298989000,
> "lastTransitionTime": "2019-08-31T15:57:09Z",
> "lastTransitionTimeTS": 1567267029000,
> "message": "kubelet has no disk pressure",
> "reason": "KubeletHasNoDiskPressure",
> "status": "False",
> "type": "DiskPressure"
> },
> {
> "lastHeartbeatTime": "2019-09-01T00:49:49Z",
> "lastHeartbeatTimeTS": 1567298989000,
> "lastTransitionTime": "2019-08-31T15:57:09Z",
> "lastTransitionTimeTS": 1567267029000,
> "message": "kubelet has sufficient PID available",
> "reason": "KubeletHasSufficientPID",
> "status": "False",
> "type": "PIDPressure"
> },
> {
> "lastHeartbeatTime": "2019-09-01T00:49:49Z",
> "lastHeartbeatTimeTS": 1567298989000,
> "lastTransitionTime": "2019-08-31T15:58:40Z",
> "lastTransitionTimeTS": 1567267120000,
> "message": "kubelet is posting ready status",
> "reason": "KubeletReady",
> "status": "True",
> "type": "Ready"
> }
> ],
> "controlPlane": true,
> "created": "2019-08-31T15:51:04Z",
> "createdTS": 1567266664000,
> "creatorId": null,
> "customConfig": {
> "address": "192.168.94.130",
> "type": "/v3/schemas/customConfig"
> },
> "dockerInfo": {
> "debug": false,
> "experimentalBuild": false,
> "type": "/v3/schemas/dockerInfo"
> },
> "etcd": true,
> "externalIpAddress": "192.168.94.130",
> "hostname": "master1",
> "id": "c-6xxcm:m-d5802d05bbf0",
> "imported": true,
> "info": {
> "cpu": {
> "count": 1
> },
> "kubernetes": {
> "kubeProxyVersion": "v1.14.6",
> "kubeletVersion": "v1.14.6"
> },
> "memory": {
> "memTotalKiB": 1863208
> },
> "os": {
> "dockerVersion": "1.13.1",
> "kernelVersion": "3.10.0-957.27.2.el7.x86_64",
> "operatingSystem": "CentOS Linux 7 (Core)"
> }
> },
> "ipAddress": "192.168.94.130",
> "labels": {
> "beta.kubernetes.io/arch": "amd64",
> "beta.kubernetes.io/os": "linux",
> "kubernetes.io/arch": "amd64",
> "kubernetes.io/hostname": "master1",
> "kubernetes.io/os": "linux",
> "node-role.kubernetes.io/controlplane": "true",
> "node-role.kubernetes.io/etcd": "true"
> },
> "links": {
> "remove": "…/v3/nodes/c-6xxcm:m-d5802d05bbf0",
> "self": "…/v3/nodes/c-6xxcm:m-d5802d05bbf0",
> "update": "…/v3/nodes/c-6xxcm:m-d5802d05bbf0"
> },
> "name": "",
> "namespaceId": null,
> "nodeName": "master1",
> "nodePoolId": "",
> "nodeTemplateId": null,
> "podCidr": "10.42.0.0/24",
> "requested": {
> "cpu": "250m",
> "pods": "4"
> },
> "requestedHostname": "master1",
> "sshUser": "root",
> "state": "active",
> "taints": [ 2 items
> {
> "effect": "NoSchedule",
> "key": "node-role.kubernetes.io/controlplane",
> "type": "/v3/schemas/taint",
> "value": "true"
> },
> {
> "effect": "NoExecute",
> "key": "node-role.kubernetes.io/etcd",
> "type": "/v3/schemas/taint",
> "value": "true"
> }
> ],
> "transitioning": "no",
> "transitioningMessage": "",
> "type": "node",
> "unschedulable": false,
> "uuid": "23d25408-cc07-11e9-990b-0242ac110002",
> "worker": false
> }

--

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`authenticated.cluster.monitoring.node-detail`|

**Comment by superseb** [comment]
etcd and controlplane nodes are tainted, this is shown as Unschedulable in the UI. Because these are the main components of the cluster, you don't want to run workloads on those nods by default. More information can be found on https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/production/
