### ISSUE TITLE
rancher 2.2.8 access fail

### ISSUE THREAD

**Issue by 160618407** [rancher/rancher#22581]
hi, can anyone solve my problem?
   when I config 2.2.8 envirement, I get a issue,as follow:
                                       
 kubectl -n cattle-system  logs -f cattle-cluster-agent-765948d576-q4qbx  
time="2019-08-31T01:57:18Z" level=info msg="Connecting to proxy" url="wss://hyrancher.hytera.com/v3/connect/register"
time="2019-08-31T01:57:18Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-08-31T01:57:18Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-08-31T01:57:28Z" level=info msg="Connecting to wss://hyrancher.hytera.com/v3/connect/register with token vddb5cbkmkjp2fjklbsdrxjnww4m7cjhg4f2p7cl6m7q4dl9s2wjvb"

**Comment by superseb** [comment]
We'll need more info on your setup, basically what is requested in the issue template. If you are getting certificate errors, it helps to supply wether you use single or HA install, and what certificates you are using. If the certificate chain is incomplete, either the server certificate does not include the needed intermediate certificate(s) or the CA certificate is incorrect. You can also use `docker run superseb/ranchercheck https://rancher.yourdomain.com` to get more information on the certificate, we have https://github.com/rancher/rancher/issues/22419 open to add this info to the agent.

Let me know if this doesn't solve the issue.

**Comment by 160618407** [comment]
Thank you fast reply.
  Today,I operated as your guid.  then the result is follow:
  hcip@hcip01:~$ docker run superseb/ranchercheck https://hyrancher.hytera.com
No value configured at https://hyrancher.hytera.com/v3/settings/cacerts, assuming certificate signed by trusted CA
Certificate details from https://hyrancher.hytera.com
Certificate #0 (https://hyrancher.hytera.com)
        Subject: CN=*.hytera.com,O=Hytera Communications Corporation Limited,L=Shenzhen,ST=Guangdong,C=CN
        Issuer: CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
        IsCA: false
        DNS Names: [*.hytera.com hytera.com]
        IPAddresses: <none>
        NotBefore: 2018-10-29 00:00:00 +0000 UTC
        NotAfter: 2020-11-24 12:00:00 +0000 UTC
        SignatureAlgorithm: SHA256-RSA
        PublicKeyAlgorithm: RSA
Certificate chain is not complete, error: Get https://hyrancher.hytera.com: x509: certificate signed by unknown authority

**Comment by 160618407** [comment]
this is the statement for creating cert :
kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=/home/hcip/ca/tls.crt --key=/home/hcip/ca/tls.key

**Comment by 160618407** [comment]
detail:
1.
-----------------------
hcip@hcip01:~/ca$ kubectl get pod -o wide -A
NAMESPACE       NAME                                        READY   STATUS             RESTARTS   AGE     IP                NODE                NOMINATED NODE   READINESS GATES
cattle-system   cattle-cluster-agent-6c44bc4db7-nmkv7       1/1     Running            13         2d1h    10.42.1.11        hcip02.hytera.com   <none>           <none>
cattle-system   cattle-node-agent-cr4rb                     1/1     Running            20         2d1h    192.168.240.165   hcip01.hytera.com   <none>           <none>
cattle-system   cattle-node-agent-k7nv9                     1/1     Running            11         2d1h    192.168.240.166   hcip02.hytera.com   <none>           <none>
cattle-system   cattle-node-agent-prbzg                     0/1     CrashLoopBackOff   131        2d1h    192.168.240.167   hcip03.hytera.com   <none>           <none>
cattle-system   rancher-5d57b47d5f-29mnd                    1/1     Running            0          5m29s   10.42.2.31        hcip01.hytera.com   <none>           <none>
cattle-system   rancher-5d57b47d5f-5pmh7                    1/1     Running            0          5m29s   10.42.0.23        hcip03.hytera.com   <none>           <none>
cattle-system   rancher-5d57b47d5f-5v7mp                    1/1     Running            0          5m29s   10.42.1.15        hcip02.hytera.com   <none>           <none>
ingress-nginx   default-http-backend-5954bd5d8c-st8jz       1/1     Running            4          2d2h    10.42.0.20        hcip03.hytera.com   <none>           <none>
ingress-nginx   nginx-ingress-controller-ccz4h              1/1     Running            3          2d2h    192.168.240.166   hcip02.hytera.com   <none>           <none>
ingress-nginx   nginx-ingress-controller-pdvx9              1/1     Running            9          2d2h    192.168.240.165   hcip01.hytera.com   <none>           <none>
ingress-nginx   nginx-ingress-controller-wwtd9              1/1     Running            4          2d2h    192.168.240.167   hcip03.hytera.com   <none>           <none>
kube-system     canal-9jbf2                                 2/2     Running            8          2d2h    192.168.240.167   hcip03.hytera.com   <none>           <none>
kube-system     canal-bt8k2                                 2/2     Running            16         2d2h    192.168.240.165   hcip01.hytera.com   <none>           <none>
kube-system     canal-srl46                                 2/2     Running            8          2d2h    192.168.240.166   hcip02.hytera.com   <none>           <none>
kube-system     cert-manager-cert-manager-c667dcdbb-68rcs   2/2     Running            8          2d2h    10.42.0.18        hcip03.hytera.com   <none>           <none>
kube-system     coredns-autoscaler-5d5d49b8ff-lrkgk         1/1     Running            8          2d2h    10.42.2.28        hcip01.hytera.com   <none>           <none>
kube-system     coredns-bdffbc666-zqttn                     1/1     Running            6          2d2h    10.42.1.13        hcip02.hytera.com   <none>           <none>
kube-system     metrics-server-7f6bd4c888-tv28m             1/1     Running            3          2d2h    10.42.0.21        hcip03.hytera.com   <none>           <none>
kube-system     rke-coredns-addon-deploy-job-nkgdj          0/1     Completed          0          2d2h    192.168.240.165   hcip01.hytera.com   <none>           <none>
kube-system     rke-ingress-controller-deploy-job-n46rx     0/1     Completed          0          2d2h    192.168.240.165   hcip01.hytera.com   <none>           <none>
kube-system     rke-metrics-addon-deploy-job-kd7fw          0/1     Completed          0          2d2h    192.168.240.165   hcip01.hytera.com   <none>           <none>
kube-system     rke-network-plugin-deploy-job-p952j         0/1     Completed          0          2d2h    192.168.240.165   hcip01.hytera.com   <none>           <none>
kube-system     tiller-deploy-7cb87ddf7d-xspx7              1/1     Running            8          2d2h    10.42.2.29        hcip01.hytera.com   <none>           <none>

2.
---------------------------------------
kubectl -n cattle-system logs -f cattle-cluster-agent-6c44bc4db7-nmkv7
time="2019-09-02T12:14:14Z" level=info msg="Connecting to proxy" url="wss://hyrancher.hytera.com/v3/connect/register"
time="2019-09-02T12:14:15Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-09-02T12:14:15Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-09-02T12:14:25Z" level=info msg="Connecting to wss://hyrancher.hytera.com/v3/connect/register with token dg6f99x8zjv85zbzxznx78ht2r6cjvbp2mwmn45xqk6frqtj9jdrmj"
time="2019-09-02T12:14:25Z" level=info msg="Connecting to proxy" url="wss://hyrancher.hytera.com/v3/connect/register"
time="2019-09-02T12:14:25Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-09-02T12:14:25Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-09-02T12:14:35Z" level=info msg="Connecting to wss://hyrancher.hytera.com/v3/connect/register with token dg6f99x8zjv85zbzxznx78ht2r6cjvbp2mwmn45xqk6frqtj9jdrmj"
time="2019-09-02T12:14:35Z" level=info msg="Connecting to proxy" url="wss://hyrancher.hytera.com/v3/connect/register"
time="2019-09-02T12:14:35Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-09-02T12:14:35Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-09-02T12:14:45Z" level=info msg="Connecting to wss://hyrancher.hytera.com/v3/connect/register with token dg6f99x8zjv85zbzxznx78ht2r6cjvbp2mwmn45xqk6frqtj9jdrmj"
time="2019-09-02T12:14:45Z" level=info msg="Connecting to proxy" url="wss://hyrancher.hytera.com/v3/connect/register"
time="2019-09-02T12:14:46Z" level=error msg="Failed to connect to proxy" error="dial tcp: lookup hyrancher.hytera.com on 10.43.0.10:53: no such host"
time="2019-09-02T12:14:46Z" level=error msg="Failed to connect to proxy" error="dial tcp: lookup hyrancher.hytera.com on 10.43.0.10:53: no

**Comment by 160618407** [comment]
hi,I select the HA install style,command as follow:
helm install rancher-stable/rancher  --name rancher  --namespace cattle-system --set hostname=hyrancher.hytera.com  --set ingress.tls.source=secret

**Comment by 160618407** [comment]
kubectl -n cattle-system get pods
NAME                                    READY   STATUS             RESTARTS   AGE
cattle-cluster-agent-6c44bc4db7-nmkv7   1/1     Running            13         2d13h
**cattle-node-agent-48zm8                 0/1     CrashLoopBackOff   4          2m46s**
cattle-node-agent-cr4rb                 1/1     Running            20         2d13h
cattle-node-agent-k7nv9                 1/1     Running            11         2d13h
rancher-5d57b47d5f-29mnd                1/1     Running            0          12h
rancher-5d57b47d5f-5pmh7                1/1     Running            0          12h
rancher-5d57b47d5f-5v7mp                1/1     Running            0          12h

 **kubectl -n cattle-system logs -f cattle-node-agent-48zm8**
INFO: Environment: CATTLE_ADDRESS=192.168.240.167 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=hcip03.hytera.com CATTLE_SERVER=https://hyrancher.hytera.com
INFO: Using resolv.conf: nameserver 8.8.8.8 nameserver 114.114.114.114 nameserver 223.5.5.5 search hytera.com
ERROR: https://hyrancher.hytera.com/ping is not accessible (**Could not resolve host: hyrancher.hytera.com**)

**Comment by superseb** [comment]
DigiCert needs intermediates yes, adding those after the server certificate should resolve the certificate issue.

Regarding DNS, the name doesn't seem to resolve. There are workarounds for not having DNS but those will bite you in the end and you should just setup proper DNS for your Rancher setup, so the configured names resolve properly.

**Comment by 160618407** [comment]
thank you,superseb.
   The first problem:DigiCert problem,I want to know what is intermediates cert? And how can I config the cert?
   this is my CA cert:star_hytera_com.crt  , star_hytera_com.pem , star_hytera_com.key.


   The second problem:dns resolve error
   I list my cluster all nodes as follow:
   ngnix-server   192.168.240.171     domainname: hyrancher.hytera.com
   cluster-work-node1   192.168.240.165 
   cluster-work-node2   192.168.240.166
   cluster-work-node3   192.168.240.167

   this is the dns mapping result:
   $:nslookup hyrancher.hytera.com
   Server:         192.168.8.10
   Address:        192.168.8.10#53

   Name:   hyrancher.hytera.com
   Address: 192.168.240.171

for the two problem,I cannot get any method to fix, trouble you to help me,  thank you very much!

**Comment by superseb** [comment]
The nameserver shown in this output if different from the nameserver shown in the logs, so the machine where you are running `nslookup` from has nameservers configured that can resolve the configured server-url but the nodes in the cluster can't using the nameservers they have configured  (`nameserver 8.8.8.8 nameserver 114.114.114.114 nameserver 223.5.5.5`)

**Comment by 160618407** [comment]
dns resolve problem is fixed by you guide.  but cert problem was still existing.
Failed to connect to proxy" error="x509: certificate signed by unknown authority


Any other method  can fix it?

**Comment by superseb** [comment]
A possible solution is described in https://github.com/rancher/rancher/issues/22581#issuecomment-527390430, what did you try and what happened after applying it?

**Comment by 160618407** [comment]
finally，a problem for cannot solve host  exist around the process------------------ 原始邮件 ------------------
发件人: "Sebastiaan van Steenis"<notifications@github.com>
发送时间: 2019年9月4日(星期三) 晚上8:04
收件人: "rancher/rancher"<rancher@noreply.github.com>;
抄送: "160618407"<799184126@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rancher/rancher] rancher 2.2.8 access fail (#22581)



A possible solution is described in #22581 (comment), what did you try and what happened after applying it?
 
&mdash;
