### ISSUE TITLE
prometheus-project-monitoring : panic: runtime error: invalid memory address

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#22587]
v 2.2.8
fresh new cluster, enabled monitoring

prometheus-project-monitoring dies with:

> level=error ts=2019-09-01T11:48:16.886031058Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:cattle-prometheus-p-vrhqx:project-monitoring\" cannot list resource \"pods\" in API group \"\" in the namespace \"cattle-logging\""
> level=error ts=2019-09-01T11:48:16.928613083Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:301: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:cattle-prometheus-p-vrhqx:project-monitoring\" cannot list resource \"services\" in API group \"\" in the namespace \"default\""
> level=error ts=2019-09-01T11:48:16.929034452Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:cattle-prometheus-p-vrhqx:project-monitoring\" cannot list resource \"pods\" in API group \"\" in the namespace \"default\""
> level=error ts=2019-09-01T11:48:16.930437106Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:301: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:cattle-prometheus-p-vrhqx:project-monitoring\" cannot list resource \"services\" in API group \"\" in the namespace \"cattle-logging\""
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x669c12]
> goroutine 252 [running]:
> net/http.(*Client).deadline(0x0, 0xc0074a32b8, 0x40bb8f, 0xc00092ace0)
> /usr/local/go/src/net/http/client.go:187 +0x22
> net/http.(*Client).do(0x0, 0xc002beda00, 0x0, 0x0, 0x0)
> /usr/local/go/src/net/http/client.go:527 +0xab
> net/http.(*Client).Do(0x0, 0xc002beda00, 0x23, 0xc001aa71a0, 0x9)
> /usr/local/go/src/net/http/client.go:509 +0x35
> github.com/prometheus/prometheus/scrape.(*targetScraper).scrape(0xc002d56cf0, 0x1fd4a60, 0xc000cf05a0, 0x1fb2760, 0xc000322f50, 0x0, 0x0, 0x0, 0x0)
> /app/scrape/scrape.go:471 +0x111
> github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc002eb6f00, 0xdf8475800, 0x2540be400, 0x0)
> /app/scrape/scrape.go:813 +0x487
> created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
> /app/scrape/scrape.go:336 +0x45d

**Comment by superseb** [comment]
Please provide steps to reproduce and all the requested info from the template in https://github.com/rancher/rancher/issues/20963 so it can help the investigation.
