### ISSUE TITLE
2.2.8 Version

### ISSUE THREAD

**Issue by 160618407** [rancher/rancher#22582]
kubectl -n cattle-system  logs -f cattle-node-agent-8lg8z 
time="2019-08-31T03:55:00Z" level=info msg="Connecting to proxy" url="wss://hyrancher.hytera.com/v3/connect"
time="2019-08-31T03:55:00Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"
time="2019-08-31T03:55:00Z" level=error msg="Failed to connect to proxy" error="x509: certificate signed by unknown authority"

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/22581
