### ISSUE TITLE
Editing service compose settings

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2259]
Is there a limitation that prevents users to edit `docker-compose` related configs on services?
I didn't figured out yet how to roll version upgrades trough `rancher-compose`, since it isn't updating related service docker image tag.

cc @fernandoneto

**Comment by deniseschannon** [comment]
You are most likely looking for in-service upgrades, where you can change any settings (including image) to an existing service and "upgrade" to it. It basically would delete the existing container and relaunch a new container for the service. 

https://github.com/rancher/rancher/issues/1874

Let me know if you are thinking of something else.

**Comment by cusspvz** [comment]
Thats it. Going to comment there. :) Thanks once again @deniseschannon
