### ISSUE TITLE
cert-manager can't renew cert for rancher

### ISSUE THREAD

**Issue by patrickkeller** [rancher/rancher#22592]
**What kind of request is this (question/bug/enhancement/feature request):**
Cert-manager can't renew the cert for rancher. It's a bug. But i have no clue what's the cause. 

**Steps to reproduce (least amount of steps as possible):**
Install rancher according to manual and wait until the cert is about to expire (30 days before expiry date).

**Result:**
cert-manager can't renew cert.

Error-Message:
`E0902 12:08:54.544002 1 controller.go:180] certificates controller: Re-queuing item "cattle-system/tls-rancher-ingress" due to error processing: error creating x509 certificate: x509: only RSA and ECDSA public keys supported`

**Other details that may be helpful:**
rancher v2.2.7
cert-manager v0.5.2 (recommended in manual)
kubernetes v1.12.10

I appreciate any help to find the issue

**Comment by taishin** [comment]
I also encountered the same problem.
I was able to renew cert by doing helm upgrade.
```
helm upgrade rancher rancher-latest/rancher --version 2.2.8 \
  --set hostname=rancher-hostname \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=xxx@xxx.xx
```
