### ISSUE TITLE
阿里云ECS创建k8s集群，拉起机器报错

### ISSUE THREAD

**Issue by yyw2006** [rancher/rancher#22598]
![image](https://user-images.githubusercontent.com/17873734/64146527-efa7ca80-ce4f-11e9-9ff0-eca0864340d1.png)
报错如上图。

在rancher配置主机模板的时候也没找到选择密钥对的地方，阿里云账号下是配置有密钥对的

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or you can join the China users WeChat group via `rancher2`
