### ISSUE TITLE
[Windows] Failed to upgrade K8S version

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#22599]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Setup rancher server
- Create a Windows cluster with Kubernetes `v1.14.6-rancher3-1`. (for now, we could not set up this version explicitly, as a workaround, we could fill up a Windows allowed version and then `edit as yaml` to change the Kubernetes version to `v1.14.6-rancher3-1`. An example shows at the bottom.)
- Add a Linux controlplane
- Add a Windows worker
- Upgrade the cluster to `v1.15.3-rancher3-1`

**Result:**
The control plane has been upgraded, but the Windows node hasn't.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master-head
- Installation option (single install/HA): single install

---
![屏幕快照 2019-09-03 15 10 59](https://user-images.githubusercontent.com/3394724/64151723-9050b700-ce5d-11e9-97c9-65bed6f70bb5.png)
![屏幕快照 2019-09-03 15 12 03](https://user-images.githubusercontent.com/3394724/64151727-947cd480-ce5d-11e9-950b-9f23e27c851c.png)

**Comment by loganhz** [comment]
We can change `ui-index` to `https://rancherui.oss-cn-shanghai.aliyuncs.com/ui/test/latest2/index.html` for testing. It will allow you to enable Windows cluster with k8s 1.14

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/22676
