### ISSUE TITLE
Missing IP of rancher server

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#22590]
My rancher server has ip: 192.168.94.131 (I used this ip to access rancher), but the command add nodes show "192.168.142.133":

> sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.2.8 --server https://192.168.142.133 --token m24gh64w88njqqsnzphqhvwffh2ngdgpvs8p7rqz7dbvxbn2lrbhxf --ca-checksum adc0b764c96c0fe0c78dc0a1147e013688a485d99e3f5b406d62db410b7dc3b2 --worker

Please see my rancher link in the attached file [https://drive.google.com/open?id=1hYVJxu24K31Q-d4C6iA2r-RfFaaHMgKI](url)

So, I think maybe it is because of I moved my vmware from another laptop, so the ip changed. I tried to edit yaml for Cattle-system project, but not successfully (It come back to show the old one after editting).

Do you know how to fix this ?

Thank you 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`authenticated.cluster.monitoring.index`|

**Comment by superseb** [comment]
This is covered in https://github.com/rancher/rancher/issues/14731, using DNS and/or load balancer helps to avoid these situations.
