### ISSUE TITLE
[UI Cluster Templates]: Tooltip shows "Create RKE Template" as the global role owner must have instead of "Create Cluster Template"

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#22608]
09/03 master
<img width="1311" alt="Screen Shot 2019-09-03 at 10 21 27 AM" src="https://user-images.githubusercontent.com/10672776/64194871-fd9c2200-ce34-11e9-8224-39a7ee062e24.png">
This message presented while adding a user with "Owner" access to a cluster template mentions "Create RKE Template" as the global role needed. Whereas the global role is named "Create Cluster Templates"
The message should show "Create Cluster Templates" as the role name.

**Comment by tfiduccia** [comment]
We renamed "Cluster Templates" to "RKE Templates".  Does the role need to be changed?

**Comment by tfiduccia** [comment]
Two changes:
1.  Changed the text back to say "Create Cluster Templates".  
2.  Changed it from a code snippet to a link back to the Global Roles page.

**Comment by tfiduccia** [comment]
@mrajashree - you're going to change the display name to Create RKE Templates?

**Comment by deniseschannon** [comment]
This seems invalid now cause it's already been removed.  https://github.com/rancher/rancher/issues/22683

**Comment by tfiduccia** [comment]
Verified tooltip is gone.
