### ISSUE TITLE
Feature request: project monitoring source labels base name

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#22605]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Description**
We noticed the following behavior using custom metrics on Rancher. When a target is added to the Prometheus Project Monitoring instance, it doesn't prefix the kubernetes metrics labels with "kubernetes_". Example can be found below:

* source_labels: [__meta_kubernetes_namespace] 
separator: ; 
regex: (.*) 
target_label: namespace 
replacement: $1 
action: replace

If an application is using the label "namespace" in it's metrics, it now collides. The result is the label for the application is changed from "namespace" to "exported_namespace".

Another example below, 

In Pulsar metrics
  namespace=test

In Prometheus metrics:
  exported_namespace=test

Desired behavior is to have Rancher not modify source label's base name.

gzrancher/rancher#5223

**Comment by maggieliu** [comment]
This will no longer be a problem in monitoring v2 (which will be available in 2.5) because we will no longer be automatically creating service monitors / pod monitors / prometheus rules for workloads in monitoring v2 anymore.

So it will be up to the user to define correctly those labels

**Comment by jiaqiluo** [comment]
This will no longer be a problem in monitoring v2
