### ISSUE TITLE
Validate tolerations when enabling monitoring workloads.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#22606]

**Comment by jiaqiluo** [comment]
The feature is validated in Rancher:master-head 

Prepare the cluster such that:
- the cluster has at least 2 worker nodes
- add the label `usage=monitroing` and the taint `dedicated=monitoring:NoExecute` to `worker-node-1`
<img width="1450" alt="Screen Shot 2019-09-03 at 11 48 03 AM" src="https://user-images.githubusercontent.com/6218999/64200519-8ae57380-ce41-11e9-83df-cc0db6a7f0d0.png">

Cluster monitoring and project monitoring:
- enable the cluster monitoring and the project monitoring with the label selector and toleration with those applied values
<img width="1505" alt="Screen Shot 2019-09-03 at 11 48 22 AM" src="https://user-images.githubusercontent.com/6218999/64200479-7608e000-ce41-11e9-9476-c62d21d786b7.png">
- Results:  all  monitoring-related workloads and pods (except the daemon set) are assigned to `worker-node-1` as expected
