### ISSUE TITLE
PVC fails to attach during workload creation

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22614]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a single node cluster - AWS - cloud provider set
2. Create a PV in the cluster level named pv1
3. Go to the default project, create a pvc named pvc1 using the existing PV.
4. Volume is created successfully.
5. Attach the volume in a workload.
6. The workload fails to deploy.

**Expected Result:**
Attaching of volume should succeed

**Actual Result:**
Error seen while attaching PVC while creating workload
```
Warning | FailedAttachVolume | AttachVolume.Attach failed for volume "pv1" : InvalidParameterValue: Value (v1) for parameter volumes is invalid. Expected: 'vol-...'. status code: 400, request id: 5aa82c06-7784-407b-89c3
Warning | FailedAttachVolume | (combined from similar events): AttachVolume.Attach failed for volume "pv1" : InvalidParameterValue: Value (v1) for parameter volumes is invalid. Expected: 'vol-...'. status code: 400, request id: 697475bc-9884-4a40-83aa-035d125118a7 
Warning | FailedMount | Unable to mount volumes for pod "wk01-c46cf7c8-zmvkj_default(5bcf07f2-ea88-48ab-9b41-7556b4185b25)": timeout expired waiting for volumes to attach or mount for pod "default"/"wk01-c46cf7c8-zmvkj". list of unmounted volumes=[vol1]. list of unattached volumes=[vol1 default-token-7m5sk]
```

**Note:**
This was seen in `v2.2.8` of rancher also.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher-master latest
- Installation option (single install/HA): single

**Comment by daxmc99** [comment]
Per the rancher docs https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/  & the k8s docs for ebs https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore.
Assuming aws & cloud-provider is set

If a Persistent Volume is created in Rancher, then an equivalent EBS volume must be created in AWS. 
1. Create ebs volume in aws.
2. use volume-id from aws for creating the PV in Rancher. 
3. Persistent volume can be used to create volumes at the project level
4. Volumes can be mounted into workloads
_Note_: All of the steps above will complete successfully until attempting to mount the volume if there is an error in step 1 and 2. 

To enable dynamic provisioning of PersistentVolumes without the need to create EBS volumes every time you can define a storage class https://kubernetes.io/docs/concepts/storage/storage-classes/
1. Define an EBS storage class
2. Use this storage class when creating new persistent volumes.

**Comment by sowmyav27** [comment]
On `rancher:master-head`
**Steps:**

1. Create an EBS volume on AWS. Note the `Volume-id`
2. Create a single node cluster - AWS - cloud provider set
3. Create a PV in the cluster level named pv1, add `Volume-id` created in Step 1 while creating this.
4. Go to the default project, create a pvc named pvc1 using the existing PV.
5. Volume Claim is created successfully.
6. Deploy a workload and attach this volume to the workload.

**Comment by sowmyav27** [comment]
Was validated -- https://github.com/rancher/rancher/issues/22614#issuecomment-528959250
