### ISSUE TITLE
[Alerts] Not working in Windows cluster as alertmanager-cluster-alerting system workload sets the matcher as kubernetes.io/os = linux

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22615]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Add Custom Windows Cluster with Azure cloud.
  - I used 1 master (etcd/control plane), one linux worker, two windows 1903 nodes .
- Activating alerts at cluster level.
- Setup an alert to trigger with some pod action. With notifier Slack or email.
- 

**Result:**

Alert fails:
`[ERROR] Failed to send alert: Post http://alertmanager-operated.cattle-prometheus.svc.cluster.local:9093/api/v1/alerts: dial tcp: lookup alertmanager-operated.cattle-prometheus.svc.cluster.local on 10.43.0.10:53: no such`

![Screen Shot 2019-09-03 at 3 44 42 PM](https://user-images.githubusercontent.com/27659/64213997-9d70a480-ce63-11e9-87c0-8afa0ef09a3b.png)

**Other details that may be helpful:**

The alerts workload **alertmanager-cluster-alerting** has:

`kubernetes.io/os = linux`

Linux Worker in the Custom cluster has:

`cattle.io/os=linux:NoSchedule`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (v2.3) (09/03/2019)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom/Azure Cloud provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`):

```
19.03.1
```

@sangeethah

**Comment by cjellick** [comment]
@aiwantaozi @loganhz the associated pr also changed monitoring. this issue is only for alerting. So, make sure you call out both in the issue so that QA knows what they need to test

**Comment by izaac** [comment]
Rancher version: `master-head` (v2.3) (09/05/2019)

Alerts are now flowing in the Windows cluster, I tested using a Slack notifier and got the notifications as expected.
**alertmanager-cluster-alerting** is now in available state and pods functional. 

It was deployed in the Linux worker with the tolerations working.

Monitoring and further Alerts test coverage is planned to be part of https://github.com/rancher/rancher/issues/16460. For now this is not longer blocking QA.
