### ISSUE TITLE
When "," is present as part of label value, using this value in selector_link is not functional.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2261]
Server version - Build from master = Oct 7
Steps to reproduce the problem:
Created a service S1 with - selector_link as "foo=bar1,bar2".
Created a service S2 with label = "foo" and value as "bar1,bar2".

Service S2 does not get linked to S1.
If this is the expected behavior , we should document this behavior.

**Comment by alena1108** [comment]
Its expected. As supported selector formats include "key only" specification, the use case from the bug would get translated as follows:

```
foo=bar1,bar2 - all objects having labels 1) key "foo" with value "bar1" 1) key "bar"2 would satisfy the selector
```
@deniseschannon we should document all the supported formats (https://github.com/rancher/rancher/issues/2239) in more detail

**Comment by deniseschannon** [comment]
@alena1108 Yep, I've already included the possible formats in my docs. :)
