### ISSUE TITLE
Logging to Elasticsearch not working

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#22611]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Change the docker dir from "/var/lib/docker" to a custom path. Example: /mnt/docker
- Deploy custom cluster with the option "Docker Root Directory" being to set to "/mnt/docker"
- Enable cluster logging

**Result:**
- No events will be sent to the log server

**Other details that may be helpful:**
By default fluentd does a bind mount to "/var/lib/docker" but the logs file are symbolic links to the custom data path IE "/mnt/docker" which is not available inside the pod.

**Workaround**
Adding a bind mount to the custom dir for the fluentd pods.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.7
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment]
Duplicate https://github.com/rancher/rancher/issues/21112

Already fixed in v2.3
