### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by 160618407** [rancher/rancher#22624]
2019/09/04 07:25:42 [INFO] Removing peer 10.42.0.5
2019/09/04 07:25:43 [INFO] Handling backend connection request [10.42.1.5]
2019/09/04 07:26:16 [INFO] Adding peer wss://10.42.1.6/v3/connect, 10.42.1.6
2019/09/04 07:26:16 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2019/09/04 07:26:16 [ERROR] Failed to serve peer connection 10.42.1.5: websocket: close 1006 unexpected EOF
2019/09/04 07:26:16 [INFO] Removing peer 10.42.1.5
2019/09/04 07:26:18 [INFO] Handling backend connection request [10.42.1.6]
2019/09/04 07:27:19 [ERROR] Failed to connect to peer wss://10.42.0.5/v3/connect [local ID=10.42.2.7]: dial tcp 10.42.0.5:443: connect: connection timed out
2019/09/04 07:27:19 [ERROR] Failed to connect to peer wss://10.42.0.6/v3/connect [local ID=10.42.2.7]: dial tcp 10.42.0.6:443: connect: connection timed out
2019/09/04 07:29:35 [ERROR] Failed to connect to peer wss://10.42.0.6/v3/connect [local ID=10.42.2.7]: dial tcp 10.42.0.6:443: connect: connection timed out
2019/09/04 07:31:50 [ERROR] Failed to connect to peer wss://10.42.0.6/v3/connect [local ID=10.42.2.7]: dial tcp 10.42.0.6:443: connect: connection timed out
2019/09/04 07:34:05 [ERROR] Failed to connect to peer wss://10.42.0.6/v3/connect [local ID=10.42.2.7]: dial tcp 10.42.0.6:443: connect: connection timed out
2019/09/04 07:36:20 [ERROR] Failed to connect to peer wss://10.42.0.6/v3/connect [local ID=10.42.2.7]: dial tcp 10.42.0.6:443: connect: connection timed out
2019/09/04 07:38:35 [ERROR] Failed to connect to peer wss://10.42.0.6/v3/connect [local ID=10.42.2.7]: dial tcp 10.42.0.6:443: connect: connection timed out
2019/09/04 07:40:50 [ERROR] Failed to connect to peer wss://10.42.0.6/v3/connect [local ID=10.42.2.7]: dial tcp 10.42.0.6:443: connect: connection timed out
W0904 07:42:39.697417       7 reflector.go:270] github.com/rancher/norm

**Comment by superseb** [comment]
Please use the issue template and read https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions before filing issues. There are also Troubleshooting docs https://rancher.com/docs/rancher/v2.x/en/troubleshooting/, which can help troubleshoot the overlay network which this seems to come from. Without provided info, one can only guess what the issue is.

**Comment by sandeep-sarpe** [comment]
Any solution found for tyhis? I am getting the same error. I have installed Rancher using helm on k3s cluster

**Comment by superseb** [comment]
The same question applies, did you run through the troubleshooting steps to make sure the cluster is functioning correctly? Are all the Rancher pods ready and active, is cluster networking functioning correctly? What version are you using, what cluster type etc etc, basically please create a new issue and provide information. The more information you provide, the better the help can be.
