### ISSUE TITLE
2.2.8 issue

### ISSUE THREAD

**Issue by 160618407** [rancher/rancher#22625]
hcip@hcip01:~$ kubectl -n cattle-system logs -f cattle-cluster-agent-f5486c5dd-hs6wq
INFO: Environment: CATTLE_ADDRESS=10.42.0.7 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-f5486c5dd-hs6wq CATTLE_SERVER=https://hyrancher.hytera.com
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
ERROR: https://hyrancher.hytera.com/ping is not accessible (Could not resolve host: hyrancher.hytera.com)

**Comment by superseb** [comment]
Please use the issue template when filing issues. This is not something not already answered in https://github.com/rancher/rancher/issues/22581
