### ISSUE TITLE
When invalid syntax is passed to the "selectorLink"/selectorContainer", API should error out.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2262]
Server version - Build from master = Oct 7
Steps to reproduce the problem:
Created a service S1 with - selector_link as "foo not in (bar1,bar2)".
Created a service S2 with label = "foo" and value as "bar3.

I expected S2 to be linked to service S1 , which does not happen since there is a syntax error in  selector_link. It should have been "notin" instead of "not in".

In such cases , we should be able to error out when creating service S1 with invalid syntax for selector_link.

**Comment by rancherdev** [comment]
This issue will be seen with any invalid format that is provided for  selector_link/ selector_container.

**Comment by sangeethah** [comment]
Tested with rancher-server version -  v0.43.0-rc1:

When creating service with invalid value for selectorLink/selectorContainer , service creation fails and API throws following error:
       ApiError: (ApiError(...), "InvalidFormat : None\n{'status': 422, 'code': u'InvalidFormat', 'links': {}, 'detail': None, 'actions': {}, 'fieldName': u'Invalid format selector : c1 not in (value1)', 'message': None, 'type': u'error', 'id': u'385c6100-3c9c-4b5d-9ac4-fd168f431c11'}")
