### ISSUE TITLE
Add a dashboard display information description

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#22620]
**What kind of request is this (question/bug/enhancement/feature request):**

**enhancement**

**Steps to reproduce (least amount of steps as possible):**

Information displayed on the dashboard, such as' Used 'and' Reserved ', blue and green progress bars, Users often ask what they mean. So can we add a text description of the information below the dashboard?

**Comment by tfiduccia** [comment]
Closing in favor of #23314
