### ISSUE TITLE
Add Bahrain to EKS regions (me-south-1)

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#22630]
https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-eks-now-available-bahrain-region/

**Comment by deniseschannon** [comment]
The backend for kontainer-engine needs to include this new region.

We need to add in this region for all k8s versions supported. 

We need to check if machine requires any changes. @superseb do you know?

**Comment by deniseschannon** [comment]
k8s 1.14 for EKS was merged/added in after the current PR that @rmweir had made. Can you do one more PR to include `me-south-1` into the k8s 1.14 section?

**Comment by rmweir** [comment]
@deniseschannon done

**Comment by bmdepesa** [comment]
rancher/rancher:master-head dbf2f73e4

* Deploy Rancher
* Create EKS cluster in `me-south-1` (validated 1.13 & 1.14)
* An error appears (#22897), but the cluster does provision successfully
* Cluster becomes active in Rancher & AWS
* Automation passes successfully
