### ISSUE TITLE
UI - Dependencies problem when init rancher-ui environment

### ISSUE THREAD

**Issue by disaster37** [rancher/rancher#2263]
I will try to contribute on rancher-ui. When I following the github instruction to init the development envionment, it's doesn't work.

After npm install & bower install, I lauch npm start and I get the following error :

> ui@0.54.0 start /home/dev/workspace/ui
> ember server

version: 1.13.8
Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Environment: development
Proxying to http://localhost:8080
Livereload server on http://localhost:49152
Serving on http://localhost:8000/
ENOENT, no such file or directory 'node_modules/ember-cli-moment/node_modules'
Error: ENOENT, no such file or directory 'node_modules/ember-cli-moment/node_modules'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at symlink (/home/dev/workspace/ui/node_modules/symlink-or-copy/index.js:63:26)
    at symlinkOrCopySync (/home/dev/workspace/ui/node_modules/symlink-or-copy/index.js:58:5)
    at /home/dev/workspace/ui/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/home/dev/workspace/ui/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/dev/workspace/ui/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/dev/workspace/ui/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/dev/workspace/ui/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)

**Comment by disaster37** [comment]
Tims report on IRC that all work fine on his workstation when start from scratch like me.

It's use npm version 2.10.1 & node v0.12.4

In my case, I have node 0.12.7, and npm 3.3.5. Maybee this issue is link with npm version ?

**Comment by vincent99** [comment]
The exact minor node version shouldn't matter.. Npm is a little more likely, I think at some point they changed to being smart about how many copies of the same dependency are put into the tree by symlinking (and the error mentions symlinking).  I'm not at a computer now but will try a newer npm later.

Did `npm install` end in an error?  I'd `rm -rf node_modules` and run it again, it could have just been a transient failed request.

**Comment by disaster37** [comment]
I have already trying to remove node_module (first think), but it's the same.
npm install end without any error.

**Comment by disaster37** [comment]
I have try to downgrade npm to version 2.14.6. Now all work fine. So this issue is in link with recent version of npm.
