### ISSUE TITLE
[UI]  EKS clusters do not have the option to encrypt the EBS volume for `/dev/xvda1`

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#22633]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement
Original issue here https://github.com/rancher/rancher/issues/21552

**Steps to reproduce (least amount of steps as possible):**
We have added a new EKS driver boolean option to enable EBS encryption on the worker nodes. 

**Result:**
This should be another advanced option on EKS configuration. 

**Other details that may be helpful:**
TBD: Name in API

**Comment by deniseschannon** [comment]
Available in `master`

**Comment by izaac** [comment]
this is getting set in the backend and after creating the EKS cluster if I go to edit I see the EBS encryption checkbox selected but in the AWS console the EBS volume appears as `Not Encrypted`

The UI part is meeting the expectation. Closing.
