### ISSUE TITLE
[UI] Ingress does not see workloads in non-default namespace in Default project

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22637]
v2.2.8 (pre-existing issue)
master-head (v2.3) (9/4/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster. Go to the Default project and create a second namespace "test"
- Create one nginx workload under the "test" namespace
- Create one nginx workload under the "default" namespace
- Create an ingress

**Result:**
We don't see the "test" namespace listed and its nginx workload in the UI

**Other details that may be helpful:**
This issue does NOT happen for any projects I create myself. If I create my own project and namespace and the ingress always shows the workloads in my created namespaces. It looks like this just happens in the Default project "default" namespace.

**Comment by loganhz** [comment]
Does refresh the page work?

UI will filter out the workloads which not in the namespace where you would like to create the ingress. Did you change it to `test` namespace here? 

![image](https://user-images.githubusercontent.com/21168270/64301939-a6708b80-cfb3-11e9-8467-a3f75ec9bab9.png)

**Comment by davidnuzik** [comment]
Yes that's all the issue was @loganhz my bad there.
cc: @tfiduccia FYI
