### ISSUE TITLE
Rancher UI: PV source doesn't show up for Longhorn

### ISSUE THREAD

**Issue by yasker** [rancher/rancher#22639]
Rancher Version: 2.2.4

<img width="1277" alt="Screen Shot 2019-09-04 at 12 28 35 PM" src="https://user-images.githubusercontent.com/3344618/64285135-fa299900-cf0f-11e9-9300-1f7bd3f968f8.png">
<img width="1274" alt="Screen Shot 2019-09-04 at 12 28 42 PM" src="https://user-images.githubusercontent.com/3344618/64285140-fd248980-cf0f-11e9-8dbc-2c0dc22201ac.png">
<img width="1287" alt="Screen Shot 2019-09-04 at 12 28 46 PM" src="https://user-images.githubusercontent.com/3344618/64285144-feee4d00-cf0f-11e9-87e5-94f8bf089975.png">

Steps to reproduce:
1. Install Longhorn.
2. Create a pod using Storage Class Longhorn.
3. Check PV in the cluster page.

Longhorn related issue: https://github.com/longhorn/longhorn/issues/708

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24665
