### ISSUE TITLE
Catalog: update kubeflow to latest version.

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#22636]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**

A customer would like the version of kubeflow in our catalog updated to the latest version (0.6). The current version looks to be 0.2.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/charts/pull/342 with kubeflow v0.6.2
