### ISSUE TITLE
Trying to import a dual stack k8s cluster not working

### ISSUE THREAD

**Issue by nistiwar** [rancher/rancher#22648]
-->

**What kind of request is this 
Question

**Steps to reproduce
Create a dual stack k8s cluster, try to import it via ranche ui

** Results
Rancher node agents come up online on IPv4 and are just fine. Able to resolve rancher server url, howver cluster-agent comes up on IPv6 and is not able to talk to rancher server url and keeps crashing in loop.

**Other details that may be helpful:**

**Environment information**
- Rancher version 
2.X
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type: rancher is installed on RKE on VMs from Openstack. K8s dual stack cluster is in the same VLan as rancher is. Rancher cluster is only IPv4 stack.
- Machine type VM
specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by nistiwar** [comment]
Does Rancher 2.x even support importing of UPv6 clusters?

**Comment by jroucheton** [comment]
Any news?
