### ISSUE TITLE
Cluster templates: allow template owner to create revisions w/o explicit global role grant

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22645]
Today when you add a user to the owner to the template, you have to grant him a global role with templateRevision create permission. That should happen by default. Things to do:

- [ ] Include templateRevision create permission to the UserBase role
- [ ] Make sure there is an api check that would allow regular user to create the revisions for the templates that he is assigned as an owner to.

@vincent99

**Comment by cloudnautique** [comment]
@vincent99 do you feel "Owner" is the right word for the permission? Feels like an "editor".

**Comment by vincent99** [comment]
That's the current name and behavior, you have total control over the template.  

I could see an intermediate "editor" role beng useful that can manipulate the revisions but not the member list/delete the template .  But up to you if you think it's needed to ship.

**Comment by soumyalj** [comment]
Tested with master build from September 6th. 
Create a cluster template T1  with  standard user "user1" as Owner to T1
Create a cluster template T2 with standard user "user1" as just "user"
1. As "user1" add new template revision R1 for template T1 and it succeeded
2. As "user1" add new template revision R2 for T2, and it fails as expected.  Add new cluster template and this should fail too.
3. For "user1", provide “Create cluster template” role by editing "user1". Add new template T2, it should succeed. Add new revision to template T1. It should still fail
