### ISSUE TITLE
Openstack node driver can not create multiple network attached nodes

### ISSUE THREAD

**Issue by alkimake** [rancher/rancher#22654]
This issue is created for MR https://github.com/rancher/machine/pull/36

**What kind of request is this (question/bug/enhancement/feature request):** enhancement
**Steps to reproduce (least amount of steps as possible):** Adding node-template for openstack has no option to put multiple network names or network id's supported by openstack docker-machine driver.

**Other details that may be helpful:**
Openstack can assign more than 1 network to instances that is created. This can be crucial for companies/people needs to connect their nodes to more than 1 network interface.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8
- Installation option (single install/HA): both

https://github.com/rancher/machine/pull/36 merde request fixes this issue `docker-machine-driver` level. There is no need to alter UI also.

**Comment by daxmc99** [comment]
Why is there no need to alter the UI here? Is this just an improvement to docker-machine?

**Comment by alkimake** [comment]
Yes. Also it looks like subtexts of parameters (`network-id`, `network-name`) on node-template comes from docker machine.

**Comment by Kwangwook-Kwon** [comment]
When this feature is released?  I'm really expecting this one!

**Comment by tingtingq** [comment]
Expecting this feature too!!!
