### ISSUE TITLE
Containers stuck at starting/stopping after scaling app down and then up

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2265]
I have a service stack using a locally built image. I rebuilt the image using the same tag and, to update the containers in the service, I used `rancher-compose scale app=0` to destroy all existing containers using the old image and then `rancher-compose scale app=20` to recreate the containers with the new image.

However, the scale up command has hung and the infrastructure view shows duplicate named containers, some stopping and some starting. Additionally, `docker ps` executed on the hosts directly does not match what the infrastructure view is showing.

How do I recover from this and what can I do to prevent it happening in the future?

**Comment by gordontyler** [comment]
Restarting the rancher-agent container on each host and then deleting each of the bogus containers through the rancher UI seems to have done the trick. It slowly removed and then purged all of the bogus containers.

**Comment by gordontyler** [comment]
Although, there were a few "removed" containers whose name changed to a UUID and I had to manually purge them.

**Comment by deniseschannon** [comment]
Was the purpose of scaling down and up to use the new image? The in-service upgrade feature that is coming out for rancher-compose should solve the ability to upgrade your service with a new image. 

https://github.com/rancher/rancher/issues/1874

**Comment by gordontyler** [comment]
Yes, that's the only method I know of to upgrade to a new image with the same tag, without doing the service-to-service migration.

I look forward to in-service upgrades :)

**Comment by deniseschannon** [comment]
Since in-service upgrade is now implemented, we would recommend users to use the upgrade in your scenario. I'm going to close this issue.

**Comment by gordontyler** [comment]
To confirm, I have been successfully using the in-service upgrade in conjunction with a private image repo to upgrade services to a new image.
