### ISSUE TITLE
Restoring Rancher (HA) steps by step 

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#22650]
Hi,

I read some guides about Backup/Restoring Rancher/Cluster in HA, but I am not clear about them, some of them only tell about snapshot. Could you please provide steps by steps for this ? 

My system uses custom cluster and includes: 1 rancher server, 3 etcd nodes, 2 master nodes, 2 worker nodes.

- What should I backup ? (only etcd snapshot is enough ?)
- What will happen if my rancher server node die ? How can I recovery 
- What will happen if one of my etcd nodes  die ?  How can I recovery 
- What will happen if one of my master nodes die ? How can I recovery 
- How can I move the system to another places ?

Many thanks !

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`global-admin.clusters.index`|

**Comment by JerryCurl** [comment]
The process is different depending on if you are talking about the Rancher Server HA cluster itself - or the clusters you are managing with Rancher.

For the cluster hosting Rancher Server in HA, you use RKE to backup and restore.  You also need a copy of your rkestate file and cluster.yml file.  Full docs [here](https://rancher.com/docs/rancher/v2.x/en/backups/)

For the child clusters - you can use the cluster snapshot function within Rancher GUI

**Comment by superseb** [comment]
Referenced docs and https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/production/ should help in answering most questions, let us know if you need to know more.
