### ISSUE TITLE
Support for etcd 3.4.x

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#22655]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Details**
Etcd 3.4.0 was released on 30-AUG-2019. According to comments in the Kubernetes etcd Slack channel, etcd v3.4 may be supported as early as k8s v1.17. Rancher HA deployments and Rancher/RKE deployed clusters should support etcd v3.4.x.

**Comment by dramich** [comment]
This is being done as part of the uplift to k8s 1.17 here https://github.com/rancher/rancher/issues/23088

**Comment by dnoland1** [comment]
Awesome! There are some great improvements in etcd 3.4 - https://kubernetes.io/blog/2019/08/30/announcing-etcd-3-4/
