### ISSUE TITLE
[Rancher-Compose] Use of variables?

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#2266]
Is it possible to use variables inside of rancher-compose / docker-compose?

**Comment by deniseschannon** [comment]
Are you looking for something like this issue? https://github.com/rancher/rancher/issues/1271

That feature is coming out in the next release of rancher-compose.

**Comment by pwFoo** [comment]
Yes, thanks! :)
I need it to deploy services with the same containers but different passwords, domain settings, ...

I'll follow #1271 and close this issue here.
