### ISSUE TITLE
Enable Tag/Custom Attribute Assignment for vSphere

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#22660]
Add another string slice flag to docker-machine to allow tags and/or attributes to be passed in and assigned to new VMs created by docker-machine.

ideas for flag? `--tag tag1:value1 --tag tag2:value2`

**Comment by luthermonson** [comment]
Tags and Custom Attributes are two different things in vSphere so we'll need to add more flags than initially discussed.

### Tags
Tags are created before hand and associated later. There is a whole creation UI and we will probably ant to take something like `--vmwarevsphere-tag category_name:tag_name` as a category is mandatory. We will need to use the REST API to look up the names passed and create proper IDs to call [AttachTag](https://github.com/vmware/govmomi/blob/88f294ec7bddd6a0dd63ed5c1ef92527777fda39/vapi/tags/tag_association.go#L40). Today it looks like the easiest thing is to associate existing tags already made via the UI, look them up, find ids and attach them.

### Custom Attributes
did some looking, can't find much in govmomi for these... gonna have to look deeper.

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/39

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3`

* User can assign multiple tags during node template creation
* User can assign multiple CustomAttributes to a node during node template creation
* Nodes created have both Tags and Custom Attributes correctly assigned

Note: Custom Attributes / Tags must be created in vCenter prior to being used in node template creation
