### ISSUE TITLE
Move download Image list to Version pop-up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#22664]
**Steps to reproduce (least amount of steps as possible):**
1.  Go to Drivers list page

**Result:**  Move this:
![image](https://user-images.githubusercontent.com/11514927/64366928-1854cf00-cfcc-11e9-9292-7990e9645e84.png)

to this:
![image](https://user-images.githubusercontent.com/11514927/64367391-b9438a00-cfcc-11e9-80c1-cd36280a4143.png)

**Comment by jiaqiluo** [comment]
The enhancement is validated in Rancher:master-head e78ddbbb9

See the download button and can download the expected image files successfully. 

<img width="754" alt="Screen Shot 2019-09-06 at 4 29 44 PM" src="https://user-images.githubusercontent.com/6218999/64465872-aeb7ec00-d0c3-11e9-8ca4-00afcb65936b.png">
