### ISSUE TITLE
Grafana only shows metrics for Linux nodes and windows deployed pods show No Data Points.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22667]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a Windows Cluster. I used Azure and deployed 2 Windows 1903 workers.
  - 1 Linux master (etcd/Control Plane) and 1 Linux Worker 
- Activate Alerts (might be optional)
- Activate monitoring
- Make sure all the system workloads are in Active and functional state.
- Deploy a windows pod in a windows node for testing.

**Result:**

- Grafana starts showing metrics in graphics.
- If trying to select a Windows node in Grafana, none is listed.
- Going to pods and selecting a pod deployed on windows, **No data points** is displayed

![Screen Shot 2019-09-05 at 11 49 28 AM](https://user-images.githubusercontent.com/27659/64370762-f5c6b400-cfd3-11e9-8755-28b9b7428134.png)

![Screen Shot 2019-09-05 at 11 49 19 AM](https://user-images.githubusercontent.com/27659/64370746-f0696980-cfd3-11e9-97a1-d38cf0235040.png)

![Screen Shot 2019-09-05 at 11 49 42 AM](https://user-images.githubusercontent.com/27659/64370779-ffe8b280-cfd3-11e9-9f77-5b6752e44be8.png)

**Other details that may be helpful:**

Azure as cloud provider.
Custom Cluster.

**Environment information**
- Rancher version : `master-head` (v2.3) (09/05/2019)
- Installation option (single install/HA): 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
1.15.3-rancher3-1
```

- Docker version (use `docker version`):

```
19.03.1
```

**Comment by izaac** [comment]
Pod level and container level we are not getting data points in the Grafana UI, @davidnuzik confirmed that linux clusters are also experiencing this issue

**Comment by izaac** [comment]
Rancher version: `master-head (v2.3) (09/10/2019)`

Windows Nodes are now getting listed in Grafana properly with CPU, Memory utilization and Network traffic getting properly collected.

Windows Pods however, the Network traffic is not getting collected, still "No data points". I tried simulating some traffic with a Load test tool, but still not getting the graphics for pods.

![Screen Shot 2019-09-10 at 3 00 43 PM](https://user-images.githubusercontent.com/27659/64653979-b7b6ff00-d3dc-11e9-9f2b-81e3578a30ec.png)


Linux nodes and pods are looking good.

**Comment by davidnuzik** [comment]
@loganhz I faintly recall some mention that we only support getting CPU and memory metrics. Is this correct? Seems like we can get disk too but that's it for windows - just those three yes?

**Comment by loganhz** [comment]
We can get cpu and memory only for Windows pods.

**Comment by sangeethah** [comment]
@loganhz @deniseschannon Should we document this restrictions for windows cluster ?

**Comment by deniseschannon** [comment]
No, there's no need to document this.
