### ISSUE TITLE
[UI] (2.2.x backport) - Azure and VMware node templates are tagged to incorrect cloud credentials

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22663]
Version: v2.2.8
Version: master-head (v2.3) (9/5/19) (tracked separately in issue https://github.com/rancher/rancher/issues/22662)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, major

**Steps to reproduce (least amount of steps as possible):**
Reference: https://github.com/rancher/rancher/issues/18737

1. In a Rancher HA set up (or single-node rancher), create an Amazon cloud credential.
2. Create an Azure/VMware cloud credential.
3. Go to 'Node Templates' page.
4. Create an Azure/VMware node template. 
5. Select the appropriate azure/vmware cloud credential while creating the template.
6. After creation of the template, click on 'View in API'
7. Once you have multiple cloud credentials to pick from (azure, vsphere, do) if you attempt to create a DO nodeTemplate, you'll get an error in the UI: 
![image](https://user-images.githubusercontent.com/45179589/64364754-71baff00-cfc8-11e9-94a3-d3f8b7c9031c.png)
This happens even though we have properly selected the "DO" cloudCredential in the UI.

**Expected Result:**
`cloudCredentialId` should be tagged to the azure/vmware cloud credential selected while creating the template.

**Actual Result:**
`cloudCredentialId` is tagged to Amazon cloud credential, which is the first one on the Cloud Credentials page.

**Comment by westlywright** [comment]
Available in UI version `2.2.95` when the new rc is released

**Comment by sowmyav27** [comment]
### Reproduced the issue on 2.2.8
**Steps:**

- In a rancher setup, create an Amazon cloud credential.
- Create an Azure/VMware cloud credential.
- Go to 'Node Templates' page.
- Create an Azure/VMware node template.
- Select the appropriate azure/vmware cloud credential while creating the template.
- After creation of the template, click on 'View in API'
- The aws cloud credential is tagged to the azure node template.

Verified on 2.2-head with UI Tag : `2.2.96`.
**Steps:**

- In a rancher setup, create an Amazon cloud credential.
- Create an Azure/VMware cloud credential.
- Go to 'Node Templates' page.
- Create an Azure/VMware node template.
- Select the appropriate azure/vmware cloud credential while creating the template.
- After creation of the template, click on 'View in API'
- The Azure cloud credential is tagged to the azure node template.
- Create an AWS node template.
- AWS cloud credential is tagged to the AWS node template.
