### ISSUE TITLE
[ui] No scope option disappears from drop down when adding API key

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#22675]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Log in to Rancher.
2. Go to API & Keys.
3. Click `Add Key` button in top right.
4. In the Scope dropdown, note `No Scope` is selected. Select another scope. Now try to select "No Scope", but it's no longer there. It's gone, vanished, disappeared, forever lost! Well, not forever, you can cancel and add key again to work around this issue.

**Result:**
<img width="992" alt="image" src="https://user-images.githubusercontent.com/468462/64393051-83ba9300-d004-11e9-9230-ffd12b1898cb.png">

**Other details that may be helpful:**
Firefox 68.0.2 on MacOSX 10.14.6

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.8, UI v2.2.94
- Installation option (single install/HA):
HA

**Comment by davidnuzik** [comment]
I have reproduced this, exactly as the issue describes in v2.3 (master-head (9/6/19)
I have also reproduced in v2.2.8

There are no browser dev console errors. I was unable to determine the cause.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/9/19)

The issue no longer occurrs. You can pick "No scope" after picking something else from the drop down. The API key is created without any issues. HTTP/API look good.
