### ISSUE TITLE
Add/Edit Taint on node pool should not be available until `"taintSupport": true` capability is set on the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22671]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Have an rke cluster- AWS - 1 etcd, 1 control plane and 1 worker node. in v2.2.8
2. Upgrade to rancher master latest - `4c7e3263a` - commit id.

**Expected Result:**
On Edit Cluster --> `Taint` on the node pool should NOT be available until `"taintSupport": true` is set on the cluster.

**Actual Result:**
On Edit Cluster --> `Taint` is available. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8 to `master-head`
- Installation option (single install/HA): single

**Comment by loganhz** [comment]
If you edit the taints on node pool, it will not take effect until you add a new node or edit field for the cluster.

So our RKE workloads will be updated and they will still work.

**Comment by sowmyav27** [comment]
Reopening the issue because of this issue -- https://github.com/rancher/rancher/issues/22670, which is going to get addresses.

Hence the user should NOT be allowed to add taints on Edit Cluster -- Node Pool.

**Comment by sowmyav27** [comment]
Verified with an upgrade from 2.2.8 to master-head - commit id: ``

**Steps:**

- Have an rke cluster- AWS - 1 etcd, 1 control plane and 1 worker node. in v2.2.8
- Upgrade to rancher master-head latest
- On Edit Cluster --> Taint on the node pool is NOT available; "taintSupport": true  is not set on the cluster
- Edit cluster, change number of hours for the recurring snapshot, and click on Save.
- "taintSupport": true is seen on the cluster after it comes up `Active`. 
- On Edit Cluster --> Taint on the node pool is available now.
