### ISSUE TITLE
Scaling up the worker node should not give capability - "taintSupport": true on a cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22670]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Have an rke cluster- AWS - 1 etcd, 1 control plane and 1 worker node. in v2.2.8
2. Upgrade to rancher master latest - `4c7e3263a` - commit id.
3. Scale up the number of worker nodes

**Expected Result:**
`"taintSupport": true` should NOT be set/seen on the cluster. (View in API, after the cluster has come up `Active`)

**Actual Result:**
`"taintSupport": true` should is set on the cluster.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8 to rancher-master
- Installation option (single install/HA): single

**Comment by mrajashree** [comment]
Tested the fix locally with [these](https://github.com/rancher/rancher/pull/22674#issuecomment-528996895) steps

**Comment by sowmyav27** [comment]
Waiting for this issue to be fixed -- https://github.com/rancher/rancher/issues/22773

**Comment by sowmyav27** [comment]
verified on upgrade from 2.2.8 to latest master-head, commit id: `ad92680c1`

**Steps:**

- Have an rke cluster- AWS - 1 etcd, 1 control plane and 1 worker node. in v2.2.8
- Upgrade to rancher master-head latest 
- Scale up the number of worker nodes
- "taintSupport": true is NOT set/seen on the cluster. (View in API, after the cluster has come up Active)
