### ISSUE TITLE
[Windows] Support K8S v1.16

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#22685]
We should support K8S v1.16 on Windows cluster

**Comment by loganhz** [comment]
lgtm

**Comment by kinarashah** [comment]
Linked kontainer driver metadata PR got merged and vendored in Rancher, moving it to test

**Comment by sowmyav27** [comment]
verified with latest master-head - commit id: `2bd183e61`. 

**Steps:**

- Bring up a windows cluster. AWS - custom cluster
- Cluster spec:

```
1 etcd/control plane - Linux 18.04 LTS
1 worker node - Linux 18.04 LTS
2 Worker nodes - WIndows - Windows_Server-1903-English-Core-Base-2019.08.16
```

- The cluster comes up successfully.
- Deploy some workloads.
- Deploy a node port workload.
- Deploy an ingress
- They work as expected.
