### ISSUE TITLE
[UI] Cluster Templates - Remove the tooltip when sharing template with owner access

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#22683]
With the backend fix https://github.com/rancher/rancher/issues/22645 that grants standard users permission to create clustertemplaterevisions for templates they have access to - we no longer need the below tooltip on UI while sharing clustertemplate with "owner" access:

"When assigning an Owner, the user must have the Create Cluster Template global role in order to create new revisions. These permissions can be granted by an administrator." 

-- This is not needed any more.

<img width="969" alt="Screen Shot 2019-09-05 at 11 04 48 PM" src="https://user-images.githubusercontent.com/1470602/64404807-fb52e700-d031-11e9-846c-416dd7a0df72.png">

**Comment by soumyalj** [comment]
Tested with master-head build from Sep 10.
1. Create a cluster template T1 and share the template as an owner with "user1" (who is a standard user)
The tool tip is not presented in the UI
![Screen Shot 2019-09-10 at 11 36 55 AM](https://user-images.githubusercontent.com/18536626/64640753-7ebc6180-d3bf-11e9-8f1f-5486b648900f.png)

Also, tested when editing a template and changing the template access from user to owner and the tool tip was not presented.
