### ISSUE TITLE
[Alerting] Node disk is running full within 24 hours default alert is unexpectedly firing

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22680]
Version: master-head (v2.3) (9/5/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable alerting

**Result:**
- After a while Node disk is running full within 24 hours alert may fire even though all linux nodes appear to have sufficient free space

**Comment by davidnuzik** [comment]
@aiwantaozi I see the same issue as the Windows Expression issue. No metric graph data. And the expression results in No data Points in prometheus for me.

![image](https://user-images.githubusercontent.com/45179589/64465573-4583a900-d0c2-11e9-8969-88d710442f40.png)

**Comment by aiwantaozi** [comment]
Yes, you could see it would alert when the value is not null, so it wouldn't have any value, this is an alert for the disk is running full within 24h, also an example to tell the user they can input an expression without threshold. There shouldn't have any graph when the predicted value of disk space is not less than 0, you could update the expression to another value, like 1073741824(1G) or other values

**Comment by davidnuzik** [comment]
Thanks. I will create a separate issue to track this secondary issue as Logan has requested in https://github.com/rancher/rancher/issues/20122

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/9/19)

I have been trying various things and can never get the rule to fire. I successfully got the Windows node disk alert rule to fire, but never the linux version.

To test I basically did the same as my windows test. I would create files about 1GB in size and every 10 mins create another. Eventually I got to 78% disk utilization in as little as an hour. The rule will never fire.

This is also true if I decrease the timeframe for `predict_linear(node_filesystem_files_free{mountpoint!~"^/etc/(?:resolv.conf|hosts|hostname)$"}[6h], 3600 * 24) < 0`

For example I tried the following. None of these worked (rule never fires)

`predict_linear(node_filesystem_files_free{mountpoint!~"^/etc/(?:resolv.conf|hosts|hostname)$"}[10m], 3600 * 24) < 0`
`predict_linear(node_filesystem_files_free{mountpoint!~"^/etc/(?:resolv.conf|hosts|hostname)$"}[20m], 3600 * 24) < 0`

and 30m, 1h, etc and tried changing timescale to all sorts of time ranges and made no difference.

I think that there may be a mistake in the expression or something. Have we ever seen this work since the change? Also the range vector is different in this than the widows one. Is this expected? I think so but it doesn't seem to work right.

I can see that data is indeed changing I can query prometheus like:
`predict_linear(node_filesystem_files_free{mountpoint!~"^/etc/(?:resolv.conf|hosts|hostname)$"}[10m], 3600 * 24) > 0`

Notice the change of < to > operator. As I fill up disk space the values indeed change over time so data is coming in to prometheus correctly I just think the expression might possibly be not correct.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/11/19)

This is now working correctly. Thank you for all the help.
This alert now fires exactly like the windows disk alert does.

When I start slowly increasing disk space in a manner that will trigger the prometheus function the alert triggers as expected. Later the alert is resolved and I get a resolved message (since I opted into this notification for my notifier).

I didn't identify any issues during my testing.
