### ISSUE TITLE
bug: fluentd consumes all inodes

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#22689]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Description**
Fluentd will start creating hundreds of thousands of 0 byte buffer log files when the partition it is on runs out of space.  Eventually it will max out all of the inodes on the partition as well.  Please see the following upstream GitHub issue.

https://github.com/fluent/fluentd/issues/2593

The reason for creating this Rancher GitHub issue is to have the upstream fix merged as soon as possible.

**Comment by deniseschannon** [comment]
It's fixed in upstream fluentd, but they haven't made a release as of today. Need to see if a new release will be made before we release.

**Comment by cjellick** [comment]
pr merged and made this tag: https://github.com/rancher/fluentd/releases/tag/v0.1.17
something else needs updated to use it

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 006998b45

* Create cluster
* Enable logging
* Logging is deployed with `rancher/fluentd:v0.1.17` images
* Logging statements are transported correctly
