### ISSUE TITLE
keep logs of crashed containers

### ISSUE THREAD

**Issue by rmalchow** [rancher/rancher#22688]
**What kind of request is this: Enhancement**

**Steps to reproduce (least amount of steps as possible):**
deploy a workload that prints an error and then dies immediately (most popular "cannot access: /foo/bar/config: Permissions denied" and "unable to obtain lock") 

**Result (I wish):**
workload goes into a crash loop, but logs of recently crashed containers are still visible in the UI (for "a while").

**Other details that may be helpful:**
there are situations (a lot, actually), where things don't come up correctly and barf with an error message. from the UI (and from the CLI as well), it can be relatively difficult to grab the corresponding logs. for a quick diagnosis, it would be incredibly helpful to be able to access whatever the container logged, even after it's been shot and disposed of.

**Comment by superseb** [comment]
For previous pod logs, we have https://github.com/rancher/rancher/issues/21344 open. You can also enable logging as described on https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/logging/.

Let me know if that doesn't cover what you need.

**Comment by rmalchow** [comment]
i think #21344 is what i am looking for. thank you very much!
