### ISSUE TITLE
[css issue]bottom bar is not always in bottom

### ISSUE THREAD

**Issue by loveship00** [rancher/rancher#22682]
*Describe your issue here*

**css issue**
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-alpha3` UI: `v2.2.1` |
|Route|`authenticated.cluster.logging.logging`|

**Comment by tfiduccia** [comment]
@loveship00 - can you take a screenshot and what you do to reproduce.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it. It might be due to some browser plugin
