### ISSUE TITLE
Add support for labels for Service Alias and External Service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2269]
Add support for adding labels when creating Service Alias and External Service.

**Comment by vincent99** [comment]
@loganhz These are in the DNS tab in 2.0 and all kinds of entries should be allowed to have labels.

**Comment by loganhz** [comment]
@vincent99 Do I need to change the schema for all kinds of DNS entries to support labels or just put labels to `launchConfig.labels`? It seems `launchConfig` must have a `image` field.

**Comment by vincent99** [comment]
I can't think of a good reason to actually do this.  I think we were thinking of selectors at the time, but selectors select containers and these aren't going to have any.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
No labels will be added to DNS services.  Closing
