### ISSUE TITLE
[UI] add docker 19.03 to the list of engines in Rancher 1.6

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#22695]
docker installation url for 19.03 needs to be added to Rancher UI in 1.6, related issue https://github.com/rancher/rancher/issues/21808

**Comment by alena1108** [comment]
@westlywright the backend support is in

**Comment by alena1108** [comment]
can be tested with `v1.6.29-rc2`

**Comment by soumyalj** [comment]
Tested with v1.6.29-rc2. Docker 19.03 is shown in the list of Docker version list. 
![Screen Shot 2019-09-25 at 10 52 52 AM](https://user-images.githubusercontent.com/18536626/65626668-a811eb80-df82-11e9-8033-748760ba41b7.png)
