### ISSUE TITLE
[UI] Uncaught TypeError when create a cluster with Calico CNI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22692]
Version: master-head (v2.3) (9/6/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create any rke cluster (I chose Linode) and just pick Calico as the CNI

**Result:**
Watch the browser dev console. Create the cluster.
You will get an Uncaught TypeError ONLY for this CNI for some reason.
```
Uncaught (in promise) TypeError: Cannot read property 'find' of undefined
    at cluster.js:268
    at Array.forEach (<anonymous>)
    at n.<anonymous> (cluster.js:266)
    at n.a.get (metal.js:2984)
    at Object.ie [as get] (metal.js:1592)
    at n.<anonymous> (cluster.js:306)
    at n.a.get (metal.js:2984)
    at ie (metal.js:1592)
    at t.r.compute (glimmer.js:604)
    at t.value (glimmer.js:384)
```

**Other details that may be helpful:**
The cluster appears  to be usable and indeed uses Calico according to the http and API.
That is to say, I couldn't find that this actually breaks anything at least based on my smoke tests.

**Comment by davidnuzik** [comment]
@loganhz I just saw the issue again in a different scenario. I think this may not be specific to Calico (I can update the issue later if you agree).

I created an amazon nodeTemplate using defaults from the UI. I created an ec2 rke cluster in Rancher UI and used this default (t2.medium) template, no other changes to cluster use all defaults (so uses Canal, etc). And I ran into the same issue. I just don't see it in most situations i.e. linode cluster, DO cluster, etc with Canal.

Something else is probably causing this -- not just the CNI.

**Comment by loganhz** [comment]
It will not break anything.
But still submitted a PR to address it https://github.com/rancher/ui/pull/3338.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/9/19)

I tested per the issue description and with an ec2 nodeTemplate as well (my comment above). The issue no longer happens in either case now.
I smoke tested the clusters and didn't identify any issues.
