### ISSUE TITLE
Support for adding "selector link" and "selector container" when adding a service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2270]
Support for adding "selector link" and "selector container" when adding a service.

**Comment by kaos** [comment]
Is this the issue that would resolve this?:
![image](https://cloud.githubusercontent.com/assets/72965/13667859/0161c7da-e6b9-11e5-9ec9-d878926d36e8.png)

Or is there a way to specify this `selectorContainer` in some other way.. ?

**Comment by deniseschannon** [comment]
@kaos There needs to be a way in the UI to set the selectorLink and selectorContainer that is in the API that is something outside of just using labels.

**Comment by kaos** [comment]
Oh? Ok. It seems to work just fine using labels alone when using a compose
file, though.
mån 14 mars 2016 kl. 21:35 skrev Denise <notifications@github.com>:

**Comment by vincent99** [comment]
Selector services are in the 2.0 UI.
