### ISSUE TITLE
Permissions + CRDs

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#22702]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature

**Steps to reproduce (least amount of steps as possible):**
1. create project with all permissions except:
- create namespaces
- manage project catalogs
- manage project members

2. try to list crds with above user (here shopify / kubernetes-deploy is used):

**Result:**
```
~> [INFO][2019-09-07 16:50:27 +0000]	
[INFO][2019-09-07 16:50:27 +0000]	------------------------------------Phase 1: Initializing deploy------------------------------------
[INFO][2019-09-07 16:50:27 +0000]	Context test found
[INFO][2019-09-07 16:50:27 +0000]	Namespace test found
[INFO][2019-09-07 16:50:28 +0000]	All required parameters and files are present
[WARN][2019-09-07 16:50:28 +0000]	The following command failed and will be retried (attempt 1/5): kubectl get CustomResourceDefinition --namespace\=test --context\=test --output\=json --request-timeout\=15
[WARN][2019-09-07 16:50:28 +0000]	Error from server (Forbidden): customresourcedefinitions.apiextensions.k8s.io is forbidden: User "u-zbw65mdtej" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**Other details that may be helpful:**
Would expect those permissions view/manage to be manageable same way as others..

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.7
- Installation option (single install/HA): HA

regards,
strowi

**Comment by vincent99** [comment]
CRDs are a cluster-level resource managed by cluster roles.

**Comment by strowi** [comment]
Oh right, I forgot.. Thx!
