### ISSUE TITLE
Associate AD group with Rancher role

### ISSUE THREAD

**Issue by fmunteanu** [rancher/rancher#22707]
I have AD authentication enabled in Rancher 2.2.8, with 2 AD groups:
- rancher-admin
- rancher-user

I would like to automatically associate all `rancher-admin` users to Rancher `Admin` role and `rancher-user` users to Rancher `User` role. Is there a way to do this?

**Comment by cloudnautique** [comment]
For any auth provider that Rancher has group support for, we want to be able to address this usecase and #22726.

**Comment by tfiduccia** [comment]
Changes only to user screen:
1.  Add a button on the User list page that says Add Group.  It should only show if you are logged into an Auth provider that supports groups.

2.  Add group page:
     Drop-down with list of groups pulled from auth provider
     Global Permissions section
     Create/Cancel buttons

**Comment by jiaqiluo** [comment]
The feature is tested in Rancher:master-head 5845c2d

Now admin can assign global roles to an AD group.

More tests are done and tracked in the test plan, and new issues will be made for bugs found during the validation.
