### ISSUE TITLE
gitlab for pipeline: one "http://.../xx.git" includes multiple projects, and needs multiple pipelines.

### ISSUE THREAD

**Issue by landinged** [rancher/rancher#22713]
*Describe your issue here*

We use gitlab as repository. The structure of codes in gitlab is not typical that in one "http://.../xx.git", there are multiple projects. While using rancher's pipeline, only one pipeline can be created, under a "http://.../xx.git". Actually multiple projects need multiple pipeline, even in one "http://.../xx.git". 

Is there any solution to this requirement ? 

THANKS very much.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`authenticated.project.pipeline.settings`|

**Comment by usernamecantbeXXX** [comment]
we have the same problem，in one git repository contains several spring cloud services，we need something like a on-off button to choose which service we need to deploy

**Comment by lmdkfs** [comment]
we have the same problem
