### ISSUE TITLE
[cli] rancher-cli update/access project level catalog-app not possible

### ISSUE THREAD

**Issue by haselere** [rancher/rancher#22717]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- create a **no scope api key** for a user with only **projectowner rights**
- setup a custom catalog only available in project level
- `./rancher --login https://<your-rancher-server-url>/v3 --token <Bearer-Token>`
- `./rancher catalog ls`

**Result:**
Only cluster/global wide catalogs are available. Catalogs setup only for project level  are not available.
```
ID               NAME             URL                                    BRANCH         KIND
library          library          https://git.rancher.io/charts          master         helm
system-library   system-library   https://git.rancher.io/system-charts   release-v2.2   helm
```
Because of the catalog not being available users with project-owner rights arent able to update an app via rancher cli.

```
rancher app upgrade <app_name> 1.1.30
FATA[0000] version 1.1.30 is not valid  
```
Updates through rancher-ui is possible?!
Any ideas?

**Other details that may be helpful:**
- 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.2.8
- Installation option (single install/HA): single
- Rancher_cli: https://github.com/rancher/cli/releases/tag/v2.2.0

**Comment by bglee** [comment]
I have been running into the same issue. I would like to be able to run a catalog refresh on a project level catalog. It seems that I am unable to find that catalog. 

**rancher catalog list** just shows global catalogs:
```
ID               NAME             URL                                                      BRANCH         KIND
library          library          https://git.rancher.io/charts                            master         helm
system-library   system-library   https://git.rancher.io/system-charts                     release-v2.2   helm
```

but if I check **rancher context current**:
`Cluster:test-cluster Project:test-project`

or **rancher project list**:
```
ID                NAME         STATE     DESCRIPTION
c-xxxxx:p-xxxxx   test-project   active    
```

In the UI under the project I can find the catalog just fine. How do I switch the context of the cli correctly to get the catalog under a project?

**Comment by metal3d** [comment]
Same problem for me, I need to refresh catalog from CLI

**Comment by bglee** [comment]
> Same problem for me, I need to refresh catalog from CLI

Since the CLI refresh doesn't work for catalogs under projects my current work around to make it work in a BASH script is to use Rancher API to send the refresh request using CURL. 

Something like this:
```
curl -u '${ranchertoken}' -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --insecure -d '{}' '${rancheraddress}/projectCatalogs/${projectid}:${catalog}?action=refresh
```

Still would prefer to use Rancher CLI

**Comment by haselere** [comment]
problem still exists with 
- rancher 2.3.2
- rancher_cli 2.3.2

**Comment by sneumann** [comment]
Hi, I am also having issues installing an app from a project-level catalog, 
getting `FATA[0020] Bad response statusCode [404]. Status [404 Not Found]. Body: [baseType=error, code=NotFound, message=failed to find resource by id] from [https://rancher.xxx.yy/v3/project/c-xyz:p-zyx/apps]`
Are these related ? Yours, Steffen

**Comment by lwiedenhoeft** [comment]
any update on this issue?

**Comment by theAkito** [comment]
What's the current status on this?

**Comment by yagyaomnius** [comment]
bump
