### ISSUE TITLE
Rancher 2.3-rc1 node driver EC2 Waiting to register with Kubernetes"

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#22710]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) AWS EC2 no internet access with AWS direct connect back to company.
2) Install Rancher HA
3) Add Cloud Credentials
4) Add Node Template
5) Add Cluster with 2 node pools. Node1 with all roles, Node2 worker role only
6) Add proxy setting to cluster setting

    kube-controller:
      extra_env:
        - 'HTTP_PROXY=http://proxy.corp:8080'
        - 'HTTPS_PROXY=http://proxy.corp:8080'
        - >-
          NO_PROXY=localhost,127.0.0.1,169.254.169.254,10.42.0.0/16,10.43.0.0/16,mycloud.net,10.96.0.0/22
    kubelet:
      extra_env:
        - 'HTTP_PROXY=http://proxy.corp:8080'
        - 'HTTPS_PROXY=http://proxy.corp:8080'
        - >-
          NO_PROXY=localhost,127.0.0.1,169.254.169.254,10.42.0.0/16,10.43.0.0/16,mycloud.net,10.96.0.0/22

**Result:**
2nd node always "Waiting to register with Kubernetes"

It seems proxy setting not picking up ??!??!?!?!?!

![image](https://user-images.githubusercontent.com/15118220/64487555-604f4c80-d27f-11e9-86b8-0f9675ca9628.png)

log file for kubelet in node 'waiting to register with kubernetes'

E0908 11:19:16.948877   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.048991   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.149104   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.249220   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.349344   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
I0908 11:19:17.389241   13269 trace.go:81] Trace[492034721]: "Reflector k8s.io/kubernetes/pkg/kubelet/kubelet.go:453 ListAndWatch" (started: 2019-09-08 11:18:48.38209444 +0000 UTC m=+121.862568137) (total time: 29.007125314s):
Trace[492034721]: [29.007125314s] [29.007125314s] END
E0908 11:19:17.389258   13269 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: an error on the server ("") has prevented the request from succeeding (get nodes)
I0908 11:19:17.389650   13269 trace.go:81] Trace[231301024]: "Reflector k8s.io/kubernetes/pkg/kubelet/kubelet.go:444 ListAndWatch" (started: 2019-09-08 11:18:48.381063689 +0000 UTC m=+121.861537380) (total time: 29.008571431s):
Trace[231301024]: [29.008571431s] [29.008571431s] END
E0908 11:19:17.389664   13269 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)
I0908 11:19:17.391312   13269 trace.go:81] Trace[917390158]: "Reflector k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47 ListAndWatch" (started: 2019-09-08 11:18:48.383207103 +0000 UTC m=+121.863680793) (total time: 29.008090855s):
Trace[917390158]: [29.008090855s] [29.008090855s] END
E0908 11:19:17.391326   13269 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: an error on the server ("") has prevented the request from succeeding (get pods)
I0908 11:19:17.399454   13269 trace.go:81] Trace[1769353341]: "Reflector k8s.io/client-go/informers/factory.go:133 ListAndWatch" (started: 2019-09-08 11:18:48.395209514 +0000 UTC m=+121.875683208) (total time: 29.004225148s):
Trace[1769353341]: [29.004225148s] [29.004225148s] END
E0908 11:19:17.399467   13269 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: an error on the server ("") has prevented the request from succeeding (get csidrivers.storage.k8s.io)
I0908 11:19:17.402540   13269 trace.go:81] Trace[807752031]: "Reflector k8s.io/client-go/informers/factory.go:133 ListAndWatch" (started: 2019-09-08 11:18:48.396288925 +0000 UTC m=+121.876762688) (total time: 29.006240346s):
Trace[807752031]: [29.006240346s] [29.006240346s] END
E0908 11:19:17.402552   13269 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: an error on the server ("") has prevented the request from succeeding (get runtimeclasses.node.k8s.io)
E0908 11:19:17.449492   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.549616   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.649749   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.749878   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.850003   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:17.950125   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.050255   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.150371   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.250486   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.350600   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
W0908 11:19:18.355878   13269 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
E0908 11:19:18.439851   13269 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.450723   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.460457   13269 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
E0908 11:19:18.550847   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.650976   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.751102   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.851223   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.951347   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:18.980535   13269 controller.go:125] failed to ensure node lease exists, will retry in 7s, error: Get https://127.0.0.1:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/ip-10-96-2-49.ap-southeast-2.compute.internal?timeout=10s: context deadline exceeded
E0908 11:19:19.051466   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
I0908 11:19:19.126533   13269 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
I0908 11:19:19.126557   13269 kubelet_node_status.go:334] Adding node label from cloud provider: beta.kubernetes.io/instance-type=m5.xlarge
I0908 11:19:19.126567   13269 kubelet_node_status.go:345] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=ap-southeast-2b
I0908 11:19:19.126577   13269 kubelet_node_status.go:349] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=ap-southeast-2
W0908 11:19:19.126619   13269 setters.go:144] replacing cloudprovider-reported hostname of ip-10-96-2-49.ap-southeast-2.compute.internal with overridden hostname of test2-worker2
I0908 11:19:19.128135   13269 kubelet_node_status.go:471] Recording NodeHasSufficientMemory event message for node ip-10-96-2-49.ap-southeast-2.compute.internal
I0908 11:19:19.128161   13269 kubelet_node_status.go:471] Recording NodeHasNoDiskPressure event message for node ip-10-96-2-49.ap-southeast-2.compute.internal
I0908 11:19:19.128171   13269 kubelet_node_status.go:471] Recording NodeHasSufficientPID event message for node ip-10-96-2-49.ap-southeast-2.compute.internal
I0908 11:19:19.128192   13269 kubelet_node_status.go:72] Attempting to register node ip-10-96-2-49.ap-southeast-2.compute.internal
E0908 11:19:19.151581   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:19.251688   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:19.351797   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:19.451911   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:19.552033   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:19.652157   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:19.752274   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:19.852406   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:19.952514   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.052632   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.152748   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.252852   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.352955   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.453060   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.553167   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.653297   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.753400   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.853505   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:20.953613   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:21.053734   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:21.128987   13269 kubelet_node_status.go:94] Unable to register node "ip-10-96-2-49.ap-southeast-2.compute.internal" with API server: Post https://127.0.0.1:6443/api/v1/nodes: read tcp 127.0.0.1:40158->127.0.0.1:6443: read: connection reset by peer
E0908 11:19:21.153833   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:21.253971   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:21.354105   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found
E0908 11:19:21.454220   13269 kubelet.go:2248] node "ip-10-96-2-49.ap-southeast-2.compute.internal" not found

**Other details that may be helpful:**
I have the same configuration with Rancher 2.2.7 and it works
* Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Docker 1.13.1

**Comment by panho66** [comment]
docker log -f nginx-proxy

", bytes from/to client:0/0, bytes from/to upstream:0/0
2019/09/08 14:15:17 [error] 16#16: *4701 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.96.1.144:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2019/09/08 14:15:18 [error] 16#16: *4703 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.96.1.144:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2019/09/08 14:15:18 [error] 16#16: *4705 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "10.96.1.144:6443", bytes from/to client:0/0, bytes from/to upstream:0/0


any idea?

**Comment by docdiesel** [comment]
Looks pretty much like the problem I had today with Ubuntu 18.04 & Rancher 1.17.4. Fixed it by disabling the "uncomplicated firewall":
`sudo ufw disable`
(Check firewalld on RedHat/Centos.)
