### ISSUE TITLE
Rancher 2.3-rc1 force to provide AWS access/secret for S3 bucket backup

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#22711]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Using API to create cluster or GUI both failed with error message:  **Unable to validate S3 backup target configration: Access Denied.**

You have to provide access/secret key.

However, it current version Rancher 2.2.7 I do not need to provide access/secret. I have InstanceProfile associate with EC2 where control plan / etcd running and it could back up to S3 bucket without access/ secret key

Prefer not to provide access/secret key but using service role in AWS. (Company policy)

**Comment by fmunteanu** [comment]
Definitely a road block for us also.

**Comment by moelsayed** [comment]
@panho66 The validation, and later the backup rotation are done from the rancher server side. So, for the full cycle to work, the Rancher server node(s) also needs to have the same instance profile. Is that how it's configured in your case ?

**Comment by panho66** [comment]
Ah, I have complicated environment AWS/Application architect want me to provision Rancher into.

There are two or more AWS accounts for Rancher.

Rancher HA Master in one of the AWS account (e.g. ACC#1)  and manage other Rancher cluster in different AWS accounts (e.g. ACC#2)
.
In 2.2.7 without validation, I create S3 bucket in AWS account where cluster running as S3 DNS is unique so there are two different S3 buckets e.g. S3BucketMaster in ACC#1 and S3BucketManagedCluster in ACC#2.

In 2.3, without access/secret key, I use API to create cluster in ACC#2 and bucket name S3BucketManagedCluster where it exists in ACC#2 and Rancher S3 bucket validation failed as it check for S3BucketManagedCluster  in ACC#1 account.

Look like work around is to have only 1 S3 bucket to share between accounts.......

Is there a way to enhance validation or bypass so that without S3 bucket share?
Maybe validation could pick up access/secret key from Cloud Credentials where Cluster to be provision if not provide in cluster configuration.

P.S. I test work around with share S3 bucket in one of the account and it works.

**Comment by panho66** [comment]
@sangeethah  after upgrade to 2.3 rc3 it works
